### ISSUE TITLE
Typescript Broccoli Plugin doesn't pass error message to broccoli

### ISSUE THREAD

**Issue by rodyhaddad** [angular/angular-cli#1]
The current version of the broccoli-typescript plugin directly logs any compiler error to the console, using `console.log`, instead of throwing it for Broccoli to catch.

We need to change this so whenever we `broccoli serve` or `ng serve` a project,  broccoli can output any compilation errors to the browser for the user to see when reloading the page.

/cc @IgorMinar

**Comment by IgorMinar** [comment]
I landed this in angular master: https://github.com/angular/angular/commit/a7ea2e5566d8df42428619dc635cb9cd92aa7810

**Comment by filipesilva** [comment]
This issue seems to be resolved. If it is not, feel free to reopen it.
