### ISSUE TITLE
why class's name change in production mode ?

### ISSUE THREAD

**Issue by icepoint0** [angular/angular-cli#10005]
Environment:

> Angular CLI: 1.7.3
> Node: 9.8.0
> OS: darwin x64
> Angular: 5.2.9
> ... animations, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, platform-server, router
> ... service-worker
> 
> @angular/cdk: 5.2.4
> @angular/cli: 1.7.3
> @angular-devkit/build-optimizer: 0.3.2
> @angular-devkit/core: 0.3.2
> @angular-devkit/schematics: 0.3.2
> @ngtools/json-schema: 1.2.0
> @ngtools/webpack: 1.10.2
> @schematics/angular: 0.3.2
> @schematics/package-update: 0.3.2
> typescript: 2.4.2
> webpack: 3.11.0

this is my class , a Array Extenion

> export class TypeArray<T> extends Array<T> {
>   constructor(type: any, items = []) {
>     super(...items);
>     this.GENERIC_MODEL = type
>     Object.setPrototypeOf(this, Object.create(TypeArray.prototype));
>   }
> 
>   GENERIC_MODEL: T
> 
>   public getType(): T {
>     return this.GENERIC_MODEL
>   }
> }
> 

when i construct the object :

i want to get object's property and its name,for example

>  let properties = Object.getOwnPropertyNames(obj)
>     //check the type and build the output type
>     let property_types = properties.map(p => {
>       return {p: p, creator: (obj[p] || {}).constructor, name: (obj[p] || {}).constructor.name}
>     })

but in dev environment:

The object's properties are: 

> 0: {p: "id", creator: ƒ, name: "Object"}1: {p: "name", creator: ƒ, name: "Object"}2: {p: "desc", creator: ƒ, name: "Object"}creator: ƒ Object()name: "Object"p: "desc"Symbol(): (...)Symbol(): (...)__proto__: Object

`3: {p: "templates", creator: ƒ, name: "TypeArray"}`

the property 'templates'  name is **"TypeArray"**

But In Prod Mode:

4) [{…}, {…}, {…}, {…}]0: {p: "id", creator: ƒ, name: "Object"}1: {p: "name", creator: ƒ, name: "Object"}2: {p: "desc", creator: ƒ, name: "Object"}

`3: {p: "templates", creator: ƒ, name: "t"}creator: ƒ t(e,l)name: "t"`

why this happened ? anyone can help me ?

**Comment by WandererInVoids** [comment]
read about uglify plugin for webpack, simple it just optimization

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
