### ISSUE TITLE
My angular website is not showing its content instead showing some angular stuff after hosting it in git hub pages.

### ISSUE THREAD

**Issue by GudaPraveenKumar** [angular/angular-cli#10009]
[](url)https://gudapraveenkumar.github.io/practice-angular-app1/

practice-angular-app
View on GitHub
MyFirstApp
This project was generated with Angular CLI version 1.7.3.

Development server
Run ng serve for a dev server. Navigate to http://localhost:4200/. The app will automatically reload if you change any of the source files.

Code scaffolding
Run ng generate component component-name to generate a new component. You can also use ng generate directive|pipe|service|class|guard|interface|enum|module.

Build
Run ng build to build the project. The build artifacts will be stored in the dist/ directory. Use the -prod flag for a production build.

Running unit tests
Run ng test to execute the unit tests via Karma.

Running end-to-end tests
Run ng e2e to execute the end-to-end tests via Protractor.

Further help
To get more help on the Angular CLI use ng help or go check out the Angular CLI README.

practice-angular-app is maintained by GudaPraveenKumar. This page was generated by GitHub Pages.

**Comment by aassaad** [comment]
Looking at the console:

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (styles.4e78828142a341a98544.bundle.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (main.a7c2e13a3cc38726f825.bundle.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (inline.318b50c57b4eba3d437b.bundle.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (polyfills.bf95165a1d5098766b92.bundle.js, line 0)
```

And the network tab shows requests to `https://gudapraveenkumar.github.io/main.a7c2e13a3cc38726f825.bundle.js`, `https://gudapraveenkumar.github.io/polyfills.bf95165a1d5098766b92.bundle.js`,  etc.

Your index.html defines `<base href="https://GudaPraveenKumar.github.io/practice-angular-app1">`, which is missing a trailing slash.

This causes the script tags to resolve to e.g `github.io/*.js` instead of `github.io/practice-angular-app1/*.js`

Just change the base href to`https://GudaPraveenKumar.github.io/practice-angular-app1/`

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
