### ISSUE TITLE
Budgets combined option "minimum" not working for absolute sizes

### ISSUE THREAD

**Issue by kartheininger** [angular/angular-cli#10002]
### Versions
```
Angular CLI: 1.7.3
Node: 9.8.0
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

A sample repro would be: https://github.com/kartheininger/budget-angularcli-example/blob/minimum/.angular-cli.json#L31
In that repo the sizes of the bundles are:
```
chunk {0} polyfills.bf95165a1d5098766b92.bundle.js (polyfills) 59.4 kB [initial] [rendered]
chunk {1} main.92c0495b4f0612b30632.bundle.js (main) 387 kB [initial] [rendered]
chunk {2} styles.fad189d6710a14941065.bundle.css (styles) 47.4 kB [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]
```
And the budgets are:
```   
 "budgets": [
        { "type": "all", "baseline": "800kb", "warning": "1kb" },
        { "type": "bundle", "name": "main", "baseline": "800kb", "maximumWarning": "100kb", "minimumWarning": "1kb" },
        { "type": "bundle", "name": "polyfills", "baseline": "100kb", "warning": "2%" },
        { "type": "any", "maximumWarning": "900kb" }
      ]
```

The warning for the polyfills is working, but not the one for "all" and for the "main-bundle". For "any" (you need to convert maximumWarning to minimumWarning) it will work.

* Step 1 Set minimum/minimumWarning to an absolute value, set the baseline higher than your real generated bundles are.  
e.g. (if all bundles together are 500kb, set 800kb as the baseline)
```
{ "type": "all", "baseline": "800kb", "warning": "1kb" },
{ "type": "bundle", "name": "main", "baseline": "800kb", "maximumWarning": "100kb", "minimumWarning": "1kb" }
```
* Step 2 Run `npm build`

### Observed behavior
Only warning for polyfill is shown.

### Desired behavior
Shouldn't there be a warning for the "all" and the "bundle": main displayed too?
According to the story: https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/budgets.md it should be possible to set sizes in bytes, kilobytes, megabytes and in percentages relative to the baseline. If i set for a generated file size of 500kb, the baseline to 400kb and the warning to something less than 100kb then i get a warning. But if my javascript file is less than baseline minus warning, then there is no warning on the console.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
