### ISSUE TITLE
stylePreprocessorOptions includePaths do not work in 6.0.0-beta.6

### ISSUE THREAD

**Issue by euangoddard** [angular/angular-cli#10007]
### Versions
```
@angular/cli: 6.0.0-beta.6
@angular-devkit/architect: 0.0.7
@angular-devkit/build-optimizer: 0.4.6
@angular-devkit/build-webpack: 0.0.7
@angular-devkit/core: 0.4.6
@angular-devkit/schematics: 0.4.6
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-beta.6
@schematics/angular: 0.4.6
@schematics/package-update: 0.4.6
typescript: 2.7.2
webpack: 4.1.1
```

### Repro steps
* Set up a brand new CLI project using `ng new --next ng6`
* Configure the files as per this [E2E test](https://github.com/angular/angular-cli/blob/b75b21f13c696b6e9fc07ff29ce92d33661540b8/tests/e2e/tests/build/styles/include-paths.ts)

### Observed behavior
```
ERROR in ../node_modules/@angular-devkit/build-webpack/src/angular-cli-files/plugins/raw-css-loader.js!../node_modules/postcss-loader/lib??embedded!../node_modules/sass-loader/lib/loader.js??ref--14-3!./styles.scss
Module build failed: 
@import "variables";
^
      File to import not found or unreadable: variables.
Parent style sheet: stdin
      in /Users/euan/Sites/ng6/src/styles.scss (line 2, column 1)
```

### Desired behavior
This type of SCSS/Sass import should work out of the box.

**Comment by sandangel** [comment]
same here, changed to relative path but it doesnt work too

**Comment by BhaskaranR** [comment]
same here. forced me to downgrade again

**Comment by ciesielskico** [comment]
Where in the angular.json do you guys add the stylePreprocessorOptions?

**Comment by sandangel** [comment]
@ciesielskico you should add it like this

```json
            "styles": [
              {
                "input": "src/styles.scss"
              },
              {
                "input": "node_modules/bootstrap/scss/bootstrap.scss"
              }
            ],
            "stylePreprocessorOptions": {
              "includePaths": ["./src", "./src/styles"]
            },
            "scripts": []
```

**Comment by euangoddard** [comment]
@sandangel that works fine. It looks like this has been fixed now

**Comment by MickL** [comment]
@sandangel Don't add `./`:

"stylePreprocessorOptions": {
              "includePaths": ["src", "folder/you/want/to/include"]
            },

**Comment by bellizio** [comment]
I'm having the same issue after upgrading to version 6. I've tried everything noted here and in the other related issues (#10036, #10473)  for this bug, but have not had any luck.

In my case, I am importing a variables.scss file in a number of component files, so the error is something like the following:
```
ERROR in Module build failed:
@import 'variables';
^
      File to import not found or unreadable: variables.
      in /ng6/src/app/home/home.component.scss (line 1, column 1)
```

**Comment by christo8989** [comment]
I was getting this error on `ng test` and @bellizio 's comment made me realize I was missing the `stylePreprocessorOptions` inside that part of the configuration.

**Comment by Askiater** [comment]
@MickL For me it works in both ways.
Like this:
` "stylePreprocessorOptions": {
              "includePaths": [
                "src/",
                "src/styles/"
              ]`
And like this also:
` "stylePreprocessorOptions": {
              "includePaths": [
                "./src/",
                "./src/styles/"
              ]`

**Comment by johnnysainz** [comment]
@Askiater, I just `ng update`ed my app and added exactly what you have. Why is it looking for colors in node_modules? Using `@import "colors";` in my scss file. What's wrong?

```
ERROR in ./src/app/routed/admin/some.component.scss
Module build failed: 
var colors = require('./colors');
^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var colors = requir"
      in /app/node_modules/colors/lib/index.js (line 1, column 1)
ℹ ｢wdm｣: Failed to compile.
```

**Comment by bakgaard** [comment]
It seems as if there is a specific order the array must load in:

```json
"includePaths": [
	"src/assets/styling",
	"node_modules/bootstrap/scss"
]
```
works for me, but 
```json
"includePaths": [
	"node_modules/bootstrap/scss",
	"src/assets/styling"	
]
```
does not. I can't quite put my finger on why though.

**Comment by tahiryasin** [comment]
`{
abc
}`

**Comment by ArthurianX** [comment]
Just upgraded from `@angular-cli` `8.0.2` to `8.2.0`  and this isn't working anymore.

I have no example as the codebase is huge, the only gotcha is that in an `scss` project I was including paths for `sass` files and it worked.

If I add the full path it still works so I believe it's something from the new version, or is it ?
Anyone else?

**Comment by xninjaxelitex** [comment]
Finally it works!!  -  Angular: 8.2.2

`src/stylings/_mixins.scss`

```
"stylePreprocessorOptions": {
    "includePaths": [
        "src/", "src/stylings/
     ]
}
```
`@import "mixins";`
