### ISSUE TITLE
 TypeError: undefined is not a constructor (evaluating 'this.service.getDat().subscribe') in http://localhost:9876/_karma_webpack_/main.bundle.js (line 2892) [INFO]  ngOnInit@http://localhost:9876/_karma_webpack_/main.bundle.js:2892:54

### ISSUE THREAD

**Issue by Mean563** [angular/angular-cli#10006]
**On page Load Making Service call to get the data, I am using Mock serivces for I am getting below Error**

```
 TypeError: undefined is not a constructor (evaluating 'this.service.getData().subscribe') in http://localhost:9876/_karma_webpack_/main.bundle.js (line 2892)
[INFO]  ngOnInit@http://localhost:9876/_karma_webpack_/main.bundle.js:2892:54
```

This Is the code I am using:
`Component.ts File`

```
 ngOnInit() {
    this.myForm = new FormGroup({
      userName: new FormControl('', Validators.compose([Validators.required,
      CustomValidator.nameValidator])),
      userEmailId: new FormControl('', Validators.compose([Validators.required,
      CustomValidator.emailValidator])),
   
    });
    
    this.service.getData().subscribe(res => {
      console.log(res);
      this.userRoles = JSON.parse(res._body);
    },
      error => {
        console.log(error);
      });
  }
```
`component.spec.ts`

```
  it('should fetch userRole data',
    (done: DoneFn) => {
      officialsService.getUserRole().subscribe(value => {
        expect(value).toBe('observable value');
        done();
      });
    });
```

Could you please some one help me how can solve the issue

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
