### ISSUE TITLE
Feature request: Function to create an Angular library other than application

### ISSUE THREAD

**Issue by guoyunhe** [angular/angular-cli#10011]
For example, you can run this command to create a well structured Angular library project:

```
ng new --lib angular-easy-dropdown
```

When you run `ng serve --open`, it start a demo app, just like a normal Angular application generated by angular-cli.

When you run `ng build`, it generate files that can be imported to other Angular projects, placed in `/dist` folder.

**Comment by clydin** [comment]
Duplicate of #1692
