### ISSUE TITLE
feature: run ng lint with --project flag by default or add config option

### ISSUE THREAD

**Issue by Hotell** [angular/angular-cli#10013]
### Versions
```
Angular CLI: 1.7.3
Node: 8.10.0
OS: darwin x64
Angular: 5.2.9
```

### Repro steps
* add tslint rule that needs to run type checker, let's say `'no-use-before-declare':true`
* set `"lintFix": true` to `angular-cli.json` `defaults`
* `ng g c helloWorld`

### Observed behavior
```
ng g c helloWorld 
```

will generate component and `ng lint` will be run, which will produce warning because ng lint is not run with `--project` flag

![image](https://user-images.githubusercontent.com/1223799/37609131-8b507f7a-2b9c-11e8-9edb-2c6a020b3a32.png)

### Desired behavior
Run ng lint with `--project` as default or provide configuration option for it in `angular-cli.json`

**Comment by hansl** [comment]
Hi @Hotell ,

Something I find confusing in this report; the `--project` flag was added to Angular CLI 6.0 but you're reporting this issue for 1.7.3. Did you update your workspace?

In any case, I'm marking this as a feature request and it's something we should consider. Thanks!

**Comment by filipesilva** [comment]
As far as I know this doesn't happen anymore. Let me know if it's still the case.
