### ISSUE TITLE
SCSS styles: [] generates modularized CSS instead of being truly global

### ISSUE THREAD

**Issue by JohnGalt1717** [angular/angular-cli#10024]
Angular CLI: 1.7.3
Node: 9.3.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

### Repro steps
* Create a new project ng new --styles=scss
* ng build --extract-css

### Observed behavior
observe the contents of the styles.bundle.css file has everything in the styles.scss prefixed with :global

### Desired behavior
Should allow these styles to survive without module code.

### Mention any other details that might be useful (optional)

Also noticed this with webpack. However with webpack setting the sass-loader's option for modules: false fixed the problem. Can't do that with the CLI.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
