### ISSUE TITLE
Help to debug the error better

### ISSUE THREAD

**Issue by Mani2693** [angular/angular-cli#10021]
Hi All, 

Can anyone help me how to trace down the error scenario which I am getting below 
I am finding hard time to debug the cli code and tracing seems impossible for the below error 

I am getting the below error in production code ( ng build --prod --sourcemaps ) 

Do we have any other way to do better debugging ? 

![typeerror](https://user-images.githubusercontent.com/11607412/37659083-002db4c4-2c75-11e8-888c-697490d6290b.PNG)

Thanks in advance 
Mani

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
