### ISSUE TITLE
allow profile flag with stats-json flag

### ISSUE THREAD

**Issue by gatimus** [angular/angular-cli#10028]
Allow passing --profile to webpack when building with --stats-json

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
