### ISSUE TITLE
can merging lazy modules reduce the time of build project   ?

### ISSUE THREAD

**Issue by Christian-health** [angular/angular-cli#10020]
The same amount of code, for example, a project has 20 components.

The first case: put 20 components in a lazy module.

The second case: put 20 components in 20 lazy modules.

Excuse me, in both cases, the kind of build time is long? Will the build time be the same?

My problem is: the same amount of code (20 components), excessive use of lazy modules. Will it lead to increased build time?

We want to increase the build time by reducing the number of lazy modules (merging lazy modules). Is this correct?

thank you very much !!!!!!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
