### ISSUE TITLE
angular-cli does not articulate path to bundles or assets

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular-cli#10032]
angular router docs 
`https://angular.io/guide/router#!#base-href`
state to set 
`  <base href="/">`

but upon doing so 
the app does not run standalone hanging off a tomcat server regardless of prod or dev

```
Angular CLI: 1.7.3
Node: 9.3.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.13
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript-collections: 1.3.2
typescript: 2.6.2
webpack: 3.11.0
```

**Comment by nhhockeyplayer** [comment]
omitting the 
<base href="/">
permits the app to run but assets are not found there after

Is there continuity here ?

throughout my app my components are referring to root dir location of my assets 
and run fine on ng serve out of the project

but I am wondering if all permutations of path spec's converge so the app will run

there seems to be a break in continuity
where too many paths are able to be set in too many places

**Comment by clydin** [comment]
If the entire application is deployed to a single location, then HTML base href should be set to the value that represents the base of the application as deployed.
For example, if deployed to `www.example.com/my-app/` then the HTML base href should be `/my-app/`.

For more complex deployment scenarios, the `APP_BASE_HREF` Angular token can be used to set the router base path and the HTML base href can be used to specify the location of the application's resources and assets if different then the end user's URL to access the application (i.e., the router base path).
As an example, the end user accesses `www.example.com/my-app/` but the resources are located at `www.example.com/resources/`.  Then the HTML base href should be `/resources/` and the `APP_BASE_HREF` token should be defined as `/my-app/`.

**Comment by alan-agius4** [comment]
Closing a per above explanation.
