### ISSUE TITLE
How to separate index.html and all built js files while running ng build ?

### ISSUE THREAD

**Issue by anilarya** [angular/angular-cli#10033]
Just asked one question  on stackoverflow as well related to same issue. Please check this . Stuck for long time on this.

https://stackoverflow.com/questions/49399183/angular5-error-child-compilation-failed-entry-module-not-found

**Comment by hansl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
