### ISSUE TITLE
ng g m testModule --flat=true --module=app.module introduces error in root module

### ISSUE THREAD

**Issue by ssourav28** [angular/angular-cli#10055]
Output from: `ng --version`.
Angular CLI: 1.7.2
Node: 8.9.4
OS: win32 x64
Angular:

When creating a new module using "ng g m testmodule --module=app.module", the app.module file is getting errors as the new entry introduces syntax error.

eg.
Lets say i have  a import statement and few components under declaration of root module.

import { BrowserModule } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { AppMaterialModules } from './material.module';
import { AppComponent } from './app.component';
import { LoginComponent } from '../pages/login/login.component';

@NgModule({
import: [BrowserModule, FormsModule],
declarations: [
        AppComponent,
        AppLayoutComponent,
        LoginComponent,]
})

and after that i usse ng n m testmodule --flat=true --module=app,module

import { BrowserModule } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { AppMaterialModules } from './material.module';
import { AppComponent } from './app.component';
import { LoginComponent } from '../pages/login/login.componen;
import { TestModule} from '../pages/login/login.component't';

@NgModule({
import: [BrowserModule, FormsModule],
declarations: [
        AppComponent,
        AppLayoutComponent,
        LoginComponen,
         TestModulet]
})

if you notice,  these lines have error at the end which is introduced after command
import { LoginComponent } from '../pages/login/login.componen;
import { TestModule} from '../pages/login/login.component't';

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
