### ISSUE TITLE
[ BUG ] ng serve with Safari 10.1 not working

### ISSUE THREAD

**Issue by workfel** [angular/angular-cli#10054]
I tried to launch my app `ng serve` with Safari 10.1 but i have an error `404` on `showdown.js.map`.

When i tried with Google Chrome all is fine, the app is launched.

### Versions
```
<!--
`ng --version` : 1.6.1
`OS` : macOS 10.13.3
`Safari`:  10.1
`angular` : 5.1.1
`node` : 8.6.0
-->
```

Thx

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
