### ISSUE TITLE
ng new app-name fails on missing yarn (6.0.0-beta.6)

### ISSUE THREAD

**Issue by gnesher** [angular/angular-cli#10065]
### Versions
```
Angular CLI: 6.0.0-beta.6
Node: 8.10.0
OS: linux x64
Angular:
```

### Repro steps
* Clean install of node 8.10 / npm 5.6
* npm install -g @angular/cli@6.0.0-beta.6
* ng new app-name

### Observed behavior
Build fails as yarn is not installed. Installing yarn globally fixes bug. I was not aware that yarn is a hard dependency. Either docs need an update or we need to fallback to npm

### Desired behavior
I would have expected npm to be used for the installation

**Comment by robertbaker** [comment]
Yarn must be installed globally if you want to use yarn, that isn't angular/cli's limitation either, that's just a requirement...

**Comment by gnesher** [comment]
@robertbaker I didn't tell the angular/cli to use Yarn. If I would have used the packageManager=yarn flag that this would have been completely my bad. But as you notice I did not use said flag. I assume Yarn is being used by default due to some change?

**Comment by robertbaker** [comment]
Sorry I misinterpreted.

I created a new project with it and it uses npm for me by default. Perhaps you have a user-global `angular.json` or the older `angular-cli.json` in your user directory (or parent dir) that has `  "packageManager": "yarn"` set

**Comment by gnesher** [comment]
Your right, there was an older .angular-cli.json in my home folder, probably from an older project.
Might be worth attaching a notification about that config somehow? Anyhow I'm closing this
