### ISSUE TITLE
ReferenceError: window is not defined (ng-build --aot)

### ISSUE THREAD

**Issue by sagarloona4180** [angular/angular-cli#10062]
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\Sagar\Documents\my-ngccrm\ngccrm-cli\src'
ERROR in C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:132
        return window && document && document.all && !window.atob;
        ^

ReferenceError: window is not defined
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:132:2
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:121:46
    at ./node_modules/style-loader/lib/addStyles.js.module.exports (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:176:88)
    at Object../node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:82:81)
    at __webpack_require__ (C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:20:30)
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:63:18
    at C:/Users/Sagar/Documents/my-ngccrm/ngccrm-cli/node_modules/ngx-perfect-scrollbar/dist/lib/perfect-scrollbar.component.css:66:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at Object.runInNewContext (vm.js:135:38)

my package.json

{
  "name": "ngccrm",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --aot  --env=prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.6",
    "@angular/common": "^4.3.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.3.6",
    "@angular/forms":"^4.3.6",
    "@angular/http": "^4.3.6",
    "@angular/platform-browser": "^4.3.6",
    "@angular/platform-browser-dynamic": "^4.3.6",
    "@angular/router": "^4.3.6",
    "@types/jquery": "^3.2.11",
    "@types/moment": "^2.13.0",
    "angular2-loaders-css": "^1.0.9",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "file-saver": "^1.3.3",
    "install": "^0.10.1",
    "jquery": "^3.2.1",
    "jspdf": "^1.3.5",
    "jspdf-autotable": "^2.3.2",
    "jszip": "^3.1.4",
    "moment": "^2.18.1",
    "ng2-bs3-modal": "0.13.0",
    "ngx-bootstrap": "^2.0.3",
    "ngx-perfect-scrollbar": "^4.9.6",
    "ngx-popover": "0.0.16",
    "node-sass": "^4.7.2",
    "npm": "^5.5.1",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "^1.4.0",
    "@angular/compiler-cli": "^4.3.6",
    "@angular/language-service":"^4.3.6",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "dargs": "^5.1.0",
    "grunt": "^1.0.1",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-contrib-sass": "^1.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "2.4.0"
  }
}

**Comment by SaiKrishnaTej23** [comment]
Hi I have similar issue. Is there any work around ?
Is it fixed ?
`

 "dependencies": {
    "@angular/animations": "4.3.0",
    "@angular/common": "4.3.0",
    "@angular/compiler": "4.3.0",
    "@angular/compiler-cli": "4.3.0",
    "@angular/core": "4.3.0",
    "@angular/forms": "4.3.0",
    "@angular/http": "4.3.0",
    "@angular/platform-browser": "4.3.0",
    "@angular/platform-browser-dynamic": "4.3.0",
    "@angular/platform-server": "4.3.0",
    "@angular/router": "4.3.0",
    "@angular/upgrade": "4.3.0",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.4",
    "@swimlane/ngx-charts": "^6.1.0",
    "@swimlane/ngx-datatable": "10.2.2",
    "@types/file-saver": "^1.3.0",
    "angular-2-dropdown-multiselect": "1.5.4",
    "angular-bootstrap-md": "4.3.1",
    "angular-in-memory-web-api": "0.3.2",
    "angular2-csv": "^0.2.3",
    "angular2-notifications": "^0.7.4",
    "bootstrap": "^4.0.0-beta",
    "core-js": "2.4.1",
    "d3": "^5.0.0",
    "file-saver": "^1.3.3",
    "font-awesome": "^4.7.0",
    "ie-shim": "0.1.0",
    "intl": "^1.2.5",
    "mdbootstrap": "4.3.2",
    "ngx-bootstrap-pagination": "^1.0.0",
    "rxjs": "^5.1.0",
    "simple-xsidebar": "0.0.22",
    "xlsx": "^0.12.1",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ngtools/webpack": "^1.5.1",
    "@types/jasmine": "^2.5.53",
    "@types/node": "^8.0.12",
    "angular-router-loader": "^0.6.0",
    "angular2-template-loader": "^0.6.2",
    "awesome-typescript-loader": "^3.2.1",
    "clean-webpack-plugin": "^0.1.16",
    "codelyzer": "^3.1.2",
    "concurrently": "^3.5.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "file-loader": "^0.11.2",
    "sass-loader": "^6.0.6",
    "html-webpack-plugin": "^2.29.0",
    "jasmine-core": "^2.6.4",
    "jquery": "^3.2.1",
    "json-loader": "^0.5.4",
    "karma": "^1.7.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^1.1.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-spec-reporter": "^0.0.31",
    "karma-webpack": "^2.0.4",
    "node-sass": "^4.5.3",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.1",
    "source-map-loader": "^0.2.1",
    "style-loader": "^0.18.2",
    "tslint": "^5.5.0",
    "tslint-loader": "^3.5.3",
    "typescript": "^2.4.1",
    "url-loader": "^0.5.9",
    "webpack": "^3.2.0",
    "webpack-dev-server": "^2.5.1",
    "webpack-merge": "4.1.0",
    "common-config": "0.1.0",
    "extended-define-webpack-plugin": "0.1.3"
  },
  "-vs-binding": {
    "ProjectOpened": [
      "watch-webpack-local"
    ]
  }
`

**Comment by nickbullock** [comment]
got the same error

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
