### ISSUE TITLE
ng serve doesn't work in FAT32 driver of windows

### ISSUE THREAD

**Issue by tjzfg** [angular/angular-cli#1006]
1. OS: Windows 7 x64

2. angular-cli: 1.0.0-beta.5
node: 4.4.5
os: win32 x64

3. ng new project
cd project
ng serve

4. `The Broccoli Plugin: [Funnel] failed with:
Error: EISDIR: illegal operation on a directory, symlink '...\src' -> '...\tmp\funnel-input_base_path-CWcRWSHb.tmp\0'
`
5. It looks like that angular-cli's serve command doesn't support FAT.When I change the project directory from a FAT32 driver into a NTFS driver,it works perfect!

another error same as mine in this post:  [http://stackoverflow.com/questions/36752014/ember-js-error-eisdir-illegal-operation-on-a-directory/37588472#37588472]

> forgive for my poor English

**Comment by filipesilva** [comment]
beta.5 on windows still requires admin privileges for `ng serve` to work. Were you running it in an admin prompt?

beta.6 won't require admin privileges though.

**Comment by tjzfg** [comment]
@filipesilva  yes,i run `ng serve` with `runas /user:administrator` in cmd.it has no effect on this issue.I also try to change the privileges of project,useless too.I am working with beta 5 in a NTFS driver now,so I believe that is the reason.
Maybe i can try beta6 in FAT32 driver in my free time,i will give feedback then.

**Comment by filipesilva** [comment]
Issue made obsolete by #1455.
