### ISSUE TITLE
Problem with Build process result

### ISSUE THREAD

**Issue by snook-st** [angular/angular-cli#10070]
Hi all,
my problem is:
when I execute the console "ng build" command, Angular/cli make a "dist" folder (all ok) but it do a duplicate of all assets files and put these at the index estructure level. The App prioritize the duplicated files before the assets's files; if I delete some duplicate file, it dessapears of the App. I tried the "ng build -prod -aot false" without a positive result.

I also made a new App (Welcome app), in case it could be of my app, but it does the same.

Some idea about it ?
 
Thanks in advance!!!

### Versions
```
Angular CLI: 1.7.3
Node: 8.9.4
OS: darwin x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
```
"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
"project": {
"name": "ws-snook.v1"
},
"apps": [
{
"root": "src",
"outDir": "dist",
"assets": [
"assets",
"favicon.ico"
],
"index": "index.html",
"main": "main.ts",
"polyfills": "polyfills.ts",
"test": "test.ts",
"tsconfig": "tsconfig.app.json",
"testTsconfig": "tsconfig.spec.json",
"prefix": "app",
"styles": [
"styles.scss"
],
"scripts": [

],
"environmentSource": "environments/environment.ts",
"environments": {
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}
}
],
"e2e": {
"protractor": {
"config": "./protractor.conf.js"
}
},
"lint": [
{
"project": "src/tsconfig.app.json",
"exclude": "**/node_modules/**"
},
{
"project": "src/tsconfig.spec.json",
"exclude": "**/node_modules/**"
},
{
"project": "e2e/tsconfig.e2e.json",
"exclude": "**/node_modules/**"
}
],
"test": {
"karma": {
"config": "./karma.conf.js"
}
},
"defaults": {
"styleExt": "scss",
"component": {}
}
}

```

### Observed behavior
```
![screenshot](https://user-images.githubusercontent.com/22953451/37922142-0f3cdf2e-312c-11e8-8f60-3941cf69e7f8.png)


```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
