### ISSUE TITLE
ng build -prod exception in browser

### ISSUE THREAD

**Issue by neilhem** [angular/angular-cli#1007]
1. OS?  Mac OSX El Capitan 10.11.5

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.5
node: 6.2.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Updated to latest version of angular-cli (1.0.0-beta.5)

4. The log given by the failure. Normally this include a stack trace and some more information.
EXCEPTION: TypeError: h.Observable.throw is not a function
main.js:13 EXCEPTION: TypeError: h.Observable.throw is not a functionb.logError @ main.js:13

5. Mention any other details that might be useful.
Rxjs is imported in main.ts file
```ts
import 'rxjs/add/operator/debounceTime';
import 'rxjs/add/operator/distinctUntilChanged';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/share';
import 'rxjs/add/operator/retryWhen';
import 'rxjs/add/operator/delay';
import 'rxjs/add/operator/mergeMap';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/throw';
```

**Comment by cironunes** [comment]
Can you confirm if the issue persists on the newest version? I tried to reproduce and it worked just fine.

**Comment by neilhem** [comment]
No, I have no error right now with new version 1.0.0-beta.8
