### ISSUE TITLE
ng help support for custom schematics

### ISSUE THREAD

**Issue by blaineadams** [angular/angular-cli#10072]
When creating a custom collection of schematics it would be really helpful if the ng help command could be given the collection to display help documentation like it does for the default angular collection of schematics.

The current implementation does not appear to support adding a collection to the help command.
### Versions
```
Example output 

$ ng generate my-custom-service --collection=@myscope/my-custom-collection --help
The option '--collection' is not registered with the help command. Run `ng help --help` for a list of supported options.

<!--
Angular CLI: 1.7.3
Node: 8.9.1
OS: win32 x64
Angular: 5.1.3
-->
```

### Repro steps

* Create a custom collection and schematic
* npm link the project and add to a test project.
* issue command: ```ng generate my-custom-service --collection=@myscope/my-custom-collection --help``` 

### Observed behavior
```
Error: Schematic "my-custom-service" not found in collection "@schematics/angular".
```

### Desired behavior
display the output of the schema.json file for the schematic as it does for @schematics/angular schematics.

**Comment by miguelyoobic95** [comment]
I am running custom schematics (without the help flag) and I get the exact same error than you have listed in the observed behavior. I have not changed any of the commands I used to do but suddenly I get the same error. Any ideas ? i'm investigating on my end so I will update if I find out what the issue is

**Comment by alan-agius4** [comment]
`--collection` is not valid option.

Use the below syntax instead. 

```
ng generate @myscope/my-custom-collection:my-custom-service  --help
```
