### ISSUE TITLE
get error JSON is not defined

### ISSUE THREAD

**Issue by hungvu2803** [angular/angular-cli#10088]
### Versions
```
@angular/cli: 1.3.2
node: 6.11.2
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.3.2
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
```

### Repro steps

* Step 1: run command line "ng serve"
* Step 2: open browser on http://localhost:4200
* Step 3: get  error 
```
ERROR ReferenceError: JSON is not defined
    at debugCheckAndUpdateNode (core.es5.js:13158)
```
![error](https://user-images.githubusercontent.com/4714057/38014671-afc5b1ec-3293-11e8-8680-c417fc463bf9.png)

### Observed behavior
```
I get the error after I use AfterViewChecked
```

**Comment by robertbaker** [comment]
You are running a very old version of angular cli and an old node version.

You should update your cli in global and project. Generate a new project and do a diff compare to upgrade your project.

**Comment by mgechev** [comment]
Closing the issue for now, looks like an environment specific problem. If I'm wrong, please open a new issue following the template & sharing a minimal demo.
