### ISSUE TITLE
angular-cli off TOMCAT tomcat cannot find assets

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular-cli#10091]
using
```
Angular CLI: 1.7.3
Node: 9.3.0
OS: win32 x64
Angular: 5.X.X
win-X64
```

days have been spent on this to no avail
I have an angular project living beneath the %TOMCAT_HOME/webapps/root
named app
it is built in place as it sits for convenience dev build not prod which shouldnt matter

building dev angular-cli  bundles everything out to app/dist fine
app runs fine with ng serve
tomcat is running and serves up other pages normally

when I goto url for `%TOMCAT_HOME%/webapps/root/new/app/dist/index.html`
assets are nowhere to be found giving 404

I have changed the `<base href="">` tag inside and out every which way
I have done the same to `ng build --base-href  .`

```
.
/
./dist
dist
""
app
assets
app/assets
```

even tried -bh './'

--base-href doesnt even produce an href tag in index.html and continuity to finding assets beneath the app/dist/assets dir is broken

i run out of tries

currently blue in the face

someone needs to check this logic it seems to have taken a hit

these paths are not shaking hands

any help is appreciated

**Comment by nhhockeyplayer** [comment]
```
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "project": {
        "name": "app"
    },
    "apps": [
        {
            "root": "src",
            "outDir": "dist",
            "assets": [
                "assets",
                "favicon.ico"
            ],
            "index": "index.html",
            "main": "main.ts",
            "polyfills": "polyfills.ts",
            "test": "test.ts",
            "tsconfig": "tsconfig.app.json",
            "testTsconfig": "tsconfig.spec.json",
            "prefix": "app",
            "styles": [
                "styles.scss",
                "../node_modules/bootstrap/dist/css/bootstrap.min.css"
            ],
            "scripts": [
                "../node_modules/jquery/dist/jquery.js",
                "../node_modules/bootstrap/dist/js/bootstrap.js"
            ],
            "environmentSource": "environments/environment.ts",
            "environments": {
                "dev": "environments/environment.ts",
                "prod": "environments/environment.prod.ts"
            }
        }
    ],
    "e2e": {
        "protractor": {
            "config": "./protractor.conf.js"
        }
    },
    "lint": [
        {
            "project": "src/tsconfig.app.json",
            "exclude": "**/node_modules/**"
        },
        {
            "project": "src/tsconfig.spec.json",
            "exclude": "**/node_modules/**"
        },
        {
            "project": "e2e/tsconfig.e2e.json",
            "exclude": "**/node_modules/**"
        }
    ],
    "test": {
        "karma": {
            "config": "./karma.conf.js"
        }
    },
    "defaults": {
        "styleExt": "scss",
        "component": {}
    }
}

```

**Comment by Destreyf** [comment]
If your app is located under the directory `app` in the browser then you'll need to run the cli with `--bh /app/` this tells the app it'll be under the /app/ directory when it loads, this should fix your assets, i do something similar with a different named directory served from nodejs.

**Comment by nhhockeyplayer** [comment]
thanks friend will give that a try

**Comment by nhhockeyplayer** [comment]
Ok nothing is working

actually the app lives off of
%TOMCAT_HOME%/webapps/root/new/app

I cant be the only person on the planet trying to do this

the path to my app shouldnt even matter

if the -bh or --baseHref 
feature did what its suppose to really do something would give here

**Comment by nhhockeyplayer** [comment]
correction

--bh doesnt exist
its -bh
or --baseHref

according to the ng --help

C:\>ng --help | grep bh
    aliases: -bh <value>, --baseHref <value>
    aliases: -bh <value>, --baseHref <value>
    aliases: -bh <value>, --baseHref <value>
    aliases: -bh <value>, --baseHref <value>

**Comment by nhhockeyplayer** [comment]
well I had honk the assets directory to %TOMCAT_HOME%/webapps/root/
in order to get them to show up in the app

this is the workaround until this logic is ironed out

**Comment by scurk1415** [comment]
try it with `--deploy-url /`

**Comment by Destreyf** [comment]
@nhhockeyplayer to expand on what @scurk1415 said, in your case having it as `--deploy-url /app/` should do the trick for you.

**Comment by nhhockeyplayer** [comment]
neither of those options worked
receiving 404 on inline bundle

i will look into it some more

using latest a5

**Comment by mgechev** [comment]
@nhhockeyplayer for support requests we strongly recommend the Angular channel on gitter or StackOverflow. Thanks for giving Angular CLI a try! :)
