### ISSUE TITLE
Generated routing doesnt work

### ISSUE THREAD

**Issue by blacksonic** [angular/angular-cli#1009]
1. OS
Ubuntu 15.04

2. Versions
angular-cli: 1.0.0-beta.5
node: 6.2.1
os: linux x64

3. Repro steps.
ng new local-heroes
ng generate route heroes --lazy false
ng serve
open http://localhost:4200/heroes

The router with its outlet and the new component is generated, but doesn't display the component associated with route when opening the page. No error message either.
Can't find the difference between this and angular2-seed, because the router over there is working like a charm.

**Comment by twmiller** [comment]
I believe this is the same issue as [#989](https://github.com/angular/angular-cli/issues/989).

This [comment](https://github.com/angular/angular-cli/issues/989#issuecomment-223581291) seems to offer a temporary solution that's working for me.

**Comment by blacksonic** [comment]
Yes it seems the same. Here are some related bug reports for it.
https://github.com/angular/angular/issues/9020
https://github.com/angular/angular/issues/8409

**Comment by filipesilva** [comment]
I'm closing it as a duplicate as @twmiller showed, but please continue the discussion there.
