### ISSUE TITLE
ng server change detection needs click to update GUI

### ISSUE THREAD

**Issue by Skuriles** [angular/angular-cli#10092]
### Versions
```
Angular CLI: 1.7.3
Node: 8.9.3
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.8.1
webpack: 3.11.0
```

### Repro steps
We are using a bigger application which uses Angular and a .Net Server. 
For communication we use HTTP and Signalr. 
Some parts of the GUI are updated by Signalr asynchronously (data is requested and answer can be few seconds later). 
The responds of the requests are handled correctly in code (we can debug it) but the GUI will not be updated until we click on the GUI element. 
We already tried to wrap some updates in "setTimeout" blocks but that didn't help.

### Observed behavior
There are two issues regarding this (so far only when running ng serve with a proxy)
1. GUI is not updated until a interaction like a click is done on a GUI element
2. Signalr Connection takes quite longer than in prod mode (but this is not a real issue)
Additional information: 
Small changes in GUI (e.g. a spinner) even won't work in prod build as well!

### Desired behavior
Update GUI after data has been updated without clicking around when using "ng serve"

Are we missing any parameters for running "ng serve" or do we have to modify the proxy config file?

Currently we have to do a prod build to test connection stuff as the ng serve is not reliable.

**Comment by Skuriles** [comment]
Additional Info:
I've added some ngZone.run in different points which seems to fix the problem so far. Still seems a little bit hacky to add this

**Comment by robertbaker** [comment]
If you are running ng server in production, even behind a proxy, that's not supported and it's terrible idea. The purpose of `ng serve --prod` is to test your production env vars if you have them, and test compiled, minified, aot, and shaked code. It's not meant for you to actually run it in production!

Without a reproducible repo, this issue should be closed. It sounds like an issue somewhere with your code or with the project files not being properly updated (If you generated your project with an older version of the cli).

**Comment by Skuriles** [comment]
No, I never said that we use ng serve for running in production!!
We only use it for development, but it is sometimes hard to use as the GUI is not updated properly in some situations and signalr takes much more time to connect. In ng build --prod (which is used for production) everything works fine. 
So my problem is more: How can I get the same results with ng serve as it is in production. 
But nevermind. I had to use ngZone in some places at this solved most of the issues so far. Will have a look on this issue in future versions.
