### ISSUE TITLE
Can't use custom schematics with v6.0.0-beta8

### ISSUE THREAD

**Issue by sebastien-yoobic** [angular/angular-cli#10108]
### Versions
```
v6.0.0-beta8
```

### Repro steps

This is the command I use to run with the previous version of angular-cli: 

`ng -- g schematicName  --collection ./@custom/main --app @custom`

### Observed behavior
```
Schematic "schematicName" not found in collection "@schematics/angular".
Error: Schematic "schematicName" not found in collection "@schematics/angular"
```

### Desired behavior

Want to be able to use custom schematics 

### Mention any other details that might be useful (optional)

It is related to the new version since the command use to work with angular-cli v5. I saw new commits about the way the schematics are handled. The app flag seems to have been removed and replace by some kind of workspace config. 

What is the new way to use custom schematics with angular-cli ? 

Thanks for your help !

**Comment by robertbaker** [comment]
Did you update your project structure to match a newly generated project layout?

If not, you need to do that :)

**Comment by sebastien-yoobic** [comment]
Hi Thanks for your reply, do you know where I can find documentation about the new project structure ? :)

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by alan-agius4** [comment]
Closing as no further feedback provided.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
