### ISSUE TITLE
Flag to provide a new service

### ISSUE THREAD

**Issue by JacopoSciampi** [angular/angular-cli#10119]
### Versions
@angular/cli": "1.6.5"
@angular/compiler-cli": "5.2.0"
@angular/language-service": "5.2.0"
@angular/core": "5.2.0"

Output from: `ng --version`.

Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

This is not quite an Issue, but a request to a feature.

Every time I create a service using the cli (ng g s service-name) it creates the files necessary, but by default it doesn't provide the new service in any module. 

My questions are two : 

1) I think would be nice to have an option flag like -p (p stands for provide) that simply add to the providers in your app.module the new service

2) Another flag with a param that specify the name of the module where to provide to service. 

I.E. -> I have a module called "ComponentModule", and I want to generate a new service that will be provided in that module. Something like "ng g s service-name -flag-name=ComponentModule" could do the job.

The result will be a new service that is auto-provided in the specified module (ComponentModule)

**Comment by clydin** [comment]
The `--module <path-to-module>` option provides this functionality.  For more details as to the available options, you can refer to the wiki: https://github.com/angular/angular-cli/wiki/generate
