### ISSUE TITLE
ng new <app-name> error

### ISSUE THREAD

**Issue by vadymsem** [angular/angular-cli#10129]
$ng new foo
console:
Error: Path "/app/app.module.ts" does not exist.
Path "/app/app.module.ts" does not exist.

I have tried to reinstall angular cli and it was not help

Angular CLI: 1.7.3
Node: 9.10.1
npm: 5.6.0
OS: darwin x64

**Comment by tianjy** [comment]
hello, I have the same issue.
how do you resolve it?

**Comment by vadymsem** [comment]
Hello!
Please, text me in skype: vadym.sem18
I will help you

2018-05-15 8:54 GMT+03:00 tianjy <notifications@github.com>:
