### ISSUE TITLE
Error: No NgModule metadata found for 'function (){}' when running npm serve

### ISSUE THREAD

**Issue by 2ngddo** [angular/angular-cli#10127]
### Versions
Angular CLI: 1.7.3
Angular: 5.2.9
Node: 8.10.0
NPM: 5.8.0
OS: linux x64

### Repro steps
https://github.com/Project-Candlelight/CWS
on command line, **npm run serve:universal --sm**

### Observed behavior
No error is produced during the 'build' process, but when going through 'serve',
we're facing an error as such: https://github.com/Project-Candlelight/CWS/issues/1

### Desired behavior
I expect the terminal to say something like "Webpack: bundle is now VALID" or "Webpack: compiled successfully" and expect to see the bundled components rendered on our web page.

### Other details
We have read through the posts on Angular-Cli Issues and tried almost every solution that seems to have any relation with the error, but none helped.

Excerpt from **package.json**
{
  "main": "server.js",
  "scripts": {
    "build:universal": "npm run build:client-and-server-bundles && npm run webpack:server",
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
    "serve:universal": "npm run build:universal && cd dist && node server",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "test": "ng test",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "start": "npm-run-all -p start:server start:build",
  "start:server": "nodemon ./dist/dev.bundle.js --watch \"./dist\"",
  "start:build": "node ./scripts/build-dev",
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/platform-server": "^5.2.9",
    "@angular/router": "^5.2.9",
    "@ngtools/webpack": "^1.10.2",
    "@nguniversal/express-engine": "^5.0.0-beta.8",
    "@nguniversal/module-map-ngfactory-loader": "^5.0.0-beta.8",
    "html-webpack-plugin": "^3.1.0",
    "jasmine-core": "^2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^3.0.0",
    "nodemon": "^1.17.2",
    "npm-run-all": "^4.1.2",
    "null-loader": "^0.1.1",
    "protractor": "~5.1.2",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.6.2",
    "style-loader": "^0.20.3",
    "to-string-loader": "^1.1.5",
    "ts-loader": "^3.5.0",
    "tslint": "~5.9.1",
    "typescript": "^2.6.2",
    "webpack-dev-server": "^3.1.1",
    "webpack-merge": "^4.1.2"
  }
}

**Comment by Ruud-cb** [comment]
For me this error occurs when running production mode, I have explained in details the problem on this stackoverflow question, in hope it was not a bug but it appears to be one:
https://stackoverflow.com/questions/52892251/bootstrap-multiple-or-single-modules-based-on-url-in-main-ts
Would like to see the help from the devs :).

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by 2ngddo** [comment]
Since the linked repository has been removed and I'm unable to rebuild the development environment, I will close the issue.
