### ISSUE TITLE
Sourcemaps flag is working unexpectedly with build optimizer

### ISSUE THREAD

**Issue by alexshakura** [angular/angular-cli#10120]
### Versions

```

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.2
Node: 8.9.3
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.2
@angular/material-moment-adapter: 5.2.3
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps

Try this commands on heavy projects :
`build-optimizer=true` and `sourcemaps=true` after that
`build-optimizer=false` and `sourcemaps=true`

Check sample repo: https://github.com/alexshakura/sourcemap-issue , where I'm using same versions as in private project.

### Observed behavior

For my project:
```
Using `build-optimizer=true` and `sourcemaps=true` - size is 32MB, time ~ 600s
Using `build-optimizer=false` and `sourcemaps=true` - size is 25,2 MB ~ 160s
```
When project size is growing  `build-optimizer` doesn't show any profit.  At some point size of build with `build-optimizer` is the same (or more) than build without it.

### Desired behavior
That would be nice to see smaller build time and size when enabling `sourcemaps` with `build-optimizer`.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
