### ISSUE TITLE
Feature Request: Make the --next flag available for the new command

### ISSUE THREAD

**Issue by mayordwells** [angular/angular-cli#10125]
For those of us on mac who installed the cli with brew, we don't have access to use the next version of angular, we can only create an angular project with the latest version. 
We would be able to create a project with the next version if we installed cli with npm though with this - `npm install -g @angular/cli@latest`
I tried using the -next flag with the new command but got this:
`The option '--next' is not registered with the new command. Run `ng new --help` for a list of supported options.`
Which is right cos `ng help` already showed me that it is not available (Just wanted to try).
I believe if the -next command is available for ng update it should be available for the new command as well. 
In a framework like rails, you can even create a new project with a specific version number.

However, a workaround for using the next version of angular, when using the cli from brew is to create a new project and then update it with `ng update -next`, which I just figured out I could do while typing this feature request.

Thanks for looking into this.

**Comment by splincode** [comment]
It would be great to have such command

`ng update --version latest`
`ng update --version beta` 
`ng update --version alpha`

or as nvm

`ng use angular@6.2`
`ng use angular@5.0`
with emulate environment (rxjs, builder, tsc, etc)

**Comment by alan-agius4** [comment]
Hi, to you the next version you need to install the `next` version of the CLI via `npm install -g @angular/cli@next`

For existing projects, you can you `ng update` the `--next` flag see https://angular.io/cli/update
