### ISSUE TITLE
Installation failed with a few errors

### ISSUE THREAD

**Issue by ApolloMars** [angular/angular-cli#10130]
I had it successfully installed a long time, it worked pretty well, I wanted to update cli to the latest version, so I tried to uninstall cli completely, and reinstall it, it keeps failing.

node version 8.11.1
npm version 5.8.0

**The log given by the failure**

/Users/kevinchiong/.npm-global/bin/ng -> /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/bin/ng

> fsevents@1.1.3 install /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents
> node install

[fsevents] Success: "/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.8.3 install /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied, mkdir '/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.8.3 postinstall /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.11.1 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:13:12)\n    at F (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:68:19)\n    at E (/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:80:29)\n    at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/which/which.js:89:16\n    at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/index.js:42:5\n    at /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.11.1
gyp verb command install [ '8.11.1' ]
gyp verb install input version string "8.11.1"
gyp verb install installing version: 8.11.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.11.1
gyp verb build dir attempting to create "build" dir: /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/build
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass/build'
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/bin/node" "/Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/kevinchiong/.npm-global/lib/node_modules/@angular/cli/node_modules/node-sass
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.8.3 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.8.3 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @angular/cli@1.7.3
added 1000 packages from 704 contributors and updated 1 package in 116.527s

**Comment by trglassaltec** [comment]
[This](https://github.com/angular/angular-cli/issues/7645) post helped me reinstall when I was getting the EACCES error.

**Comment by ApolloMars** [comment]
@trglassaltec Thanks for replying, but is that only EACCES which stops installing cli correctly?

I tried to fix the permission problem according to a doc file from npm official website, but obviously it haven't worked out.

**Comment by ApolloMars** [comment]
I didn't say cli was installed successfully cuz I haven't see OK in the last line, and also it came out with many errors, but when I do ng --version,  the angular cli's version number appeared, I really can't figure it out.

Hope someone can help me get through ASAP, many thanks.

**Comment by trglassaltec** [comment]
I had to install Python 2 because apparently the angular/cli install depends on it and doesn't do a check before. Once I did that,  npm install -g @angular/cli -unsafe-perm   ran successfully in it's entirety and I didn't get the EACCES error

**Comment by trglassaltec** [comment]
Unfortunately I still had to, the easiest way was to just run a quick home brew. "brew install python"

**Comment by ApolloMars** [comment]
@trglassaltec It's already pre installed on Mac OS, here is the pic shows that it is in the version of 2.7.10
<img width="93" alt="screen shot 2018-04-04 at 11 33 42 pm" src="https://user-images.githubusercontent.com/2524858/38317955-d66099fc-3860-11e8-993a-e1b3b88c21c3.png">

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI.
