### ISSUE TITLE
ng e2e running into pipelines' butbucket with a docker image

### ISSUE THREAD

**Issue by joaopcm** [angular/angular-cli#10132]
### Issue
My e2e test with Protractor does not run like expect because I do not know how to create/run docker images in pipelines of Bibucket when the test runs. Could you help me?

### Versions
Version 1.5.4 of Angular CLI;
Latest version of Docker for Windows;

```

### Repro steps
* Coded my e2e test with Protractor
* Configured bitbucket-pipelines.yml file to do a commit.
* I have a proxy file "proxy.conf.json"
* In local storage, I start the Docker image that uses the MongoDB
* run "ng e2e --proxy-config proxy.conf.json" and the test executes all of all specs successfuly
* when I commit my project to Bitbucket, I see the e2e test running in pipelines page, but the test does not run like expect because there are not Docker images running.

### Desired behavior
* I need to run this e2e test in pipelines page of Bitbucket when I commit my repo.

**Comment by everflux** [comment]
You can see an example for bitbucket with ng-cli docker image here: https://github.com/trion-development/docker-ng-cli-e2e/issues/1

**Comment by joaopcm** [comment]
Thanks, everflux! This example was helpful.
