### ISSUE TITLE
SCSS Folder Not found after create new project. Style files with extension .css

### ISSUE THREAD

**Issue by tomavic** [angular/angular-cli#10135]
### Versions
```
Angular CLI: 1.7.3
Node: 8.10.0
OS: win32 x64
Angular: 5.2.0
```

### Repro steps

* Run command `ng new project`

### Observed behavior
```
Check styles, found it was generated with extension .css instead of .scss
```

### Desired behavior
Need to generate styles with extension .scss instead of .css

**Comment by markgoho-EDT** [comment]
@tomavic what are your global defaults set to? Unless you've changed them to use scss as the default style extension, it will create css files.

try `ng new project --style=scss`

**Comment by tomavic** [comment]
That should be mentioned in the docs 🥇

**Comment by mischkl** [comment]
Just creating the project using `--style=scss` doesn't help, because as soon as a component is generated it defaults to using `css`.

I couldn't find any documentation on how to set the global defaults. Attempting to do `ng config -g defaults.styleExt '"scss"'` or various variants `'scss'`or `scss` or `=scss`all failed. Documentation is completely missing for how to set anything using the new `ng config` command - nothing works. Please help ASAP.

**Comment by tomavic** [comment]
Hi @mischkl It's been hard to notice something like that in documentation. Although, Did you try to edit `.angular-cli.json` file. Make sure the `defaults` object is same as that

```
  "defaults": {
    "styleExt": "scss",
    "prefixInterfaces": false
  }
```

try it and let me know :)

**Comment by mischkl** [comment]
Turns out there is an undocumented way to get Angular 6 to default to SCSS styles, namely adding

```json
"schematics": {
    "@schematics/angular:component": {
      "styleext": "scss"
    }
  }
```
to the end of the `angular.json` file. This should really be automatically done when a project is created with `--style=scss`. So I think it is accurate to classify this as an open issue (at least for Angular 6).

**Comment by maroy1986** [comment]
Issue also exposed in #10105 .

**Comment by IAMRogerXi** [comment]
Even with CLI 6.0.8, I have got the same exception. 

**CLI & OS information:**
Angular CLI: 6.0.8
Node: 10.2.0
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.0
@angular/cli                      6.0.8
@angular/material                 6.2.0
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

**CLI command:**
ng config -g schematics.@schematics/angular.component '{ styleext: "scss"}'

**Exception:**
Invalid JSON character: "s" at 0:11.

**Comment by martaszymek** [comment]
Angular CLI: 6.0.8
Node: 8.11.3
OS: linux x64
Angular: 6.1.1

Set scss:
- globally, for all new projects, explained [here](https://github.com/angular/angular-cli/issues/11537):
`$ ng config -g schematics.@schematics/angular:ng-new.style scss`
- when creating a new project:
`$ ng new awesome-project --style=scss`
- in an existing project:
`$ ng config schematics.@schematics/angular:component.styleext scss`
There is no need of editing `angular.json` manually. Change extension in already existing css files, update `styleUrls:` in already existing components.

**Comment by mgechev** [comment]
@little-pinecone thanks for the comment!
