### ISSUE TITLE
[feature request] tsconfig paths for generator

### ISSUE THREAD

**Issue by renanBritz** [angular/angular-cli#10133]
### Versions
```
Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Observed behavior
To my understanding, the generator creates the specified blueprint relative to the directory that you're currently in. So if i'm in the `src/app/models/customer/` directory, and I want to create a new component, I would have to use the command like this:
`ng g c ../../components/example`.

It makes us have to constantly check relative paths and the current directory, which leads to mistakes and confusion, since the generator always creates the blueprints.

### Desired behavior
tsconfig.json allows us to register paths that helps the typescript compiler know what an import refers to. It tremendously helps with relative paths, since we can replace it with a convenient alias.

> Example paths in tsconfig.json

```json
{
    "baseUrl": ".",
    "paths": {
      "@components/*": ["components/*"],
      "@models/*": ["models/*"],
    }
  }
}
```

My request is that these paths could be used in the generator. Example:

`ng g c @components/example` OR `ng g c {@components}/example`. The curly braces would, theoretically, make it easier to distinguish an 'alias' string.

Thank you!

**Comment by mgechev** [comment]
@renanBritz the suggestion makes sense. Let us not stretch the scope of the CLI at the moment and revisit the feature request again in future.

If you think this is an essential functionality that we must definitely support, please open a new issue.
