### ISSUE TITLE
Generated selectors now is module/component-name, so a slash instead of a dash. v6.0.0-rc.0

### ISSUE THREAD

**Issue by AlQuraian** [angular/angular-cli#10144]
### Versions
Angular CLI: 6.0.0-rc.0
Node: 9.9.0
OS: win32 x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.0
@angular/cli: 6.0.0-rc.0
@angular/material-moment-adapter: 6.0.0-rc.0
@angular/material: 6.0.0-rc.0
@angular-devkit/architect: 0.5.0
@angular-devkit/build-angular: 0.5.0
@angular-devkit/build-optimizer: 0.5.0
@angular-devkit/core: 0.4.9
@angular-devkit/schematics: 0.4.9
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.0
@schematics/angular: 0.4.9
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: 4.1.0

### Repro steps
Create a component using ng:
ng g c module/comp

### Observed behavior
selector: 'module/comp'

### Desired behavior
selector: 'module-comp'

**Comment by Brocco** [comment]
The actual behavior would be to have a selector of `app-comp` and be placed in the `module` directory. The PR linked above will address this.
