### ISSUE TITLE
"ng update" doesn't honor "packageManager": "yarn" in .angular-cli.json

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#10154]
### Versions
```
Angular CLI: 6.0.0-rc.0
Node: 8.9.4
OS: darwin x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router
```

### Repro steps

* go to a cli 1.7.3 project installed by yarn with .angular-cli.json containing `"packageManager": "yarn"`
* update @angular/cli in package.json to `^6.0.0-rc.0`
* `yarn install`
* `ng update @angular/cli --migrate-only --from=1.7.3`

### Observed behavior
the project is updated, but npm is used to install all the new dependencies. this results in npm's package-lock.json file to be created and yarn.lock file not to be updated.

### Desired behavior
yarn should have been used to perform the update.

**Comment by IgorMinar** [comment]
workaround:
- delete `package-lock.json`
- rerun `yarn install` to update the `yarn.lock` file

**Comment by dominikg** [comment]
might cause more trouble: ["npm install" deletes everything from a Yarn-produced tree](https://github.com/yarnpkg/yarn/issues/5240)
