### ISSUE TITLE
Package undefined not found error when updating to @angular/cli 6.0.0-rc.0

### ISSUE THREAD

**Issue by benjamincombes** [angular/angular-cli#10167]
### Versions
```
Angular CLI: 6.0.0-rc.0
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 6.0.0-rc.0
@angular/material: 5.2.4
@angular-devkit/architect: 0.5.0
@angular-devkit/core: 0.5.0
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: error
```

### Repro steps

* Open an existing project
* Update to angular 6.0.0-rc.0 and to @angular/cli 6.0.0-rc.0
* Try to run the app, and get this error message :
```
An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
```
* Run the required command

### Observed behavior
The following error message is displayed:
```
Package undefined was not found in package.json.
```

### Desired behavior
App should be updated succesfully.

**Comment by zackarychapple** [comment]
I've started digging into this a bit and found its an error thrown by the schematic here, https://github.com/angular/devkit/blob/master/packages/schematics/update/update/index.ts#L393

**Comment by benjamincombes** [comment]
Hi @zackarychapple, thanks a lot for your answer! Yes, I'm using Verdaccio (https://github.com/verdaccio/verdaccio) to publish private packages used in all my projects.
Do you have any clue of wether this issue will be possible to fix without having to stop using private packages?

**Comment by hansl** [comment]
Seems like update is not compatible with private packages. The normal update flow might be a problem but we should be able to fix the migration one.

**Comment by aboodz** [comment]
just a little addition on @zackarychapple, even if you have a private package on an internal, or private, npm registry, you get the same error. The only dirty workaround is to remove private dependencies, execute the update, and then re add your dependencies again.

**Comment by manfredsteyer** [comment]
What do you think about just providing a parameter ``--registry`` to point to a custom registry? We could also store a default value for this somewhere. Even though this solution isn't perfect (b/c, in theory, everyone could locally configure several registries for several scopes) it would be easy to implement and it should be suitable for the majority of cases. 

I've also tried to spawn a process for ``npm info`` to get the semantics from npm (searching and respecting different .npmrc files, etc.) but this is very slow and we would need to call it for each and every dependency. 

What do you think?

**Comment by zackarychapple** [comment]
@manfredsteyer that would not resolve the issue because not all the packages are necessarily on the private repository.  Sometimes it's prefixed packages `@cb` are in private.   I think we should look at the following when deciding to upgrade. 

* is the version a URL already
* try to hit npm, if 404 then assume private and don't try to upgrade

**Comment by playground** [comment]
Hi, I'm getting the same error when try to update from 1.6.3 to either 6.0.0 or 6.0.1 with the following commands:

ng update @angular/cli --migrate-only --from=1.6.3 or ng update @angular/cli

ng update @angular/cli                   
404 Not Found: @angular/cli

ng update @angular/cli
404 Not Found: @types/jasmine

ng update @angular/cli --migrate-only --from=1.6.3
404 Not Found: @types/node
