### ISSUE TITLE
Angular CLI failes to run karma tests on jenkins

### ISSUE THREAD

**Issue by GeorgeTailor** [angular/angular-cli#10161]
### Versions
Local machine:
```
Angular CLI: 1.7.2
Node: 8.6.0
OS: darwin x64
Angular: 5.2.7
```

Remote machine:
```
Node: 6.9.4
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
No angular-cli installed globally.
```

### Repro steps
Run ng test with headless Chrome (puppeteer) or any other browser on a machine that is used as a CI/CD server.

### Observed behavior

Running 'npm test', which has an alias in package.json like the following:
'ng test --browser=ChromeHeadless --code-coverage=true --single-run=true'
does not run the tests, the application is transpiled, the karma server is run, karma process connects to the headless Chrome, but the tests are not run.
Increasing timeouts and retry counts does not fix the issue.

> karma.conf.js:

```
process.env.CHROME_BIN = require('puppeteer').executablePath();

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    customLaunchers: {
      ChromeHeadless:  {
        base: 'Chrome',
        flags:  [
          '--headless',
          '--disable-gpu',
          '--no-sandbox',
          '--remote-debugging-port=9222'
        ],
      }
    },
    browserNoActivityTimeout: 70000,
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_DEBUG,
    autoWatch: false,
    browsers: ['ChromeHeadless'],
    singleRun: true
  });
};
```

Note. The problem does not occur when the tests are run on a local machine.

### Desired behavior
Tests are run without additional configuration on a remote CI/CD machine.

### Mention any other details that might be useful (optional)

As a workaround I've managed to fully replace angular-cli configuration with `karma-typescript` + `karma-typescript-angular2-transform`.
The corresponding karma.conf.js is as follows:

```
process.env.CHROME_BIN = require('puppeteer').executablePath();

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', 'karma-typescript'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('karma-typescript')
    ],
    angularCli: {
      environment: 'dev'
    },
    files: [
      { pattern: "base.spec.ts" },
      { pattern: "src/**/*.+(ts|html)" }
    ],
    karmaTypescriptConfig: {
            bundlerOptions: {
                entrypoints: /\.spec\.ts$/,
                transforms: [
                    require("karma-typescript-angular2-transform")
                ]
            },
            compilerOptions: {
                lib: ["ES2015", "DOM"]
            }
    },
    preprocessors: {'**/*.ts': 'karma-typescript'
    },
    mime: {
      'text/x-typescript': ['ts', 'tsx']
    },
    reporters: ["dots", "karma-typescript"],
    port: 9876,
    colors: true,
    browserNoActivityTimeout: 80000,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['ChromeHeadless'],
    singleRun: true
  });
};
```

additional base.spec.ts file is as follows:
```
import 'core-js';
import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

import { TestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());

```

I suspect that Angular-CLI somehow makes some additional steps for test files to be found by karma, why those steps are not taken by a remote machine remains a mystery.

Maybe some specific config is needed for angular-cli project's `test.ts` ?

**Comment by GeorgeTailor** [comment]
Anyone who should face similar issue, the solution is to use puppeteer for headless chrome with an extension in karma.conf.js:

```
customLaunchers: {
      "Chrome-headless": {
        base: 'ChromeHeadless',
        flags: [
          '--headless', 
          '--remote-debugging-port=9222',
          '--no-sandbox', 
          '--proxy-server=\'direct://\'',
          '--proxy-bypass-list=*'
        ]
      }
    }
```

I've found out that when angular-cli built the project bundles, my vendor.js was about 17MB, and headless chrome had some problems with downloading such bundle in small amount of time due to some strange proxy settings on remote server.

**Comment by sasos90** [comment]
@GeorgeTailor and what about Firefox then for example?

**Comment by GeorgeTailor** [comment]
@sasos90 testing on different browsers is e2e testing, why do you need karma for that ? As for testing the components themselves and maybe for some integration tests karma with a headless Chrome is enough.

**Comment by sasos90** [comment]
Yes, I know and it makes total sense. But with E2E tests you don't cover all of the components whereas with unit tests you could cover most of them.
But if you say that Chrome headless is enough, I will take a look at it! Thanks! :)

**Comment by helzgate** [comment]
I wish GeargeTailor's suggestion worked.  I'm using the latest Jenkins docker container and no matter what, jenkins doesn't finish the ng test

**Comment by sasos90** [comment]
Can you provide your karma.conf.js perhaps? And the package.json as well.

**Comment by helzgate** [comment]
I resolved my issue by following [this comment](https://github.com/karma-runner/karma-chrome-launcher/issues/154#issuecomment-393504570)
