### ISSUE TITLE
ng serve fails

### ISSUE THREAD

**Issue by norbert-tasi** [angular/angular-cli#10177]
I got this error and cannot serve:

ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'c:\development\apa\frontend\apamanger'
ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'c:\development\apa\frontend\apamanger'
### Versions
```Angular CLI: 6.0.0-rc.0
Node: 9.7.1
OS: win32 x64
Angular: 6.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.0
@angular-devkit/architect: 0.5.0
@angular-devkit/build-angular: 0.0.10
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.5.0
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.7.2
webpack: 4.1.0
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by norbert-tasi** [comment]
Thank you for your quick reply.
I've created the repo: https://github.com/norbert-tasi/ngissue
I could manage to reproduce it easily. 
1. create new app
2. yarn

I've tried yarn cache clean, reinstall, but fails.

ERROR in multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'c:\development\apa\frontend\ngissue'
ERROR in multi ./src/polyfills.ts
Module not found: Error: Can't resolve '@ngtools/webpack' in 'c:\development\apa\frontend\ngissue'
i ｢wdm｣: Failed to compile.

**Comment by norbert-tasi** [comment]
npm install resolved this issue.

**Comment by clydin** [comment]
Closing as resolved.
