### ISSUE TITLE
Feature request: configure watcher for additional files

### ISSUE THREAD

**Issue by steveblue** [angular/angular-cli#1018]
I haven't found any examples of this feature so it doesn't seem possible. 

> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Max OSX

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: local (v1.0.0-beta.5, branch: master)
node: 5.5.0
os: darwin x64

5. Mention any other details that might be useful.
> ---------------------------------------------------------------

It would be a great feature to configure file globs that can be added or excluded to the watcher. The use case for this is simple: global CSS stored in a specific location, vendor files that need to be augmented for the project, etc.

**Comment by steveblue** [comment]
If someone points me in the right direction I will implement and submit pull request. @filipesilva know where I can start?

**Comment by filipesilva** [comment]
You can find most of the file copying logic in `lib/broccoli/angular2-app.js`, it makes heavy usage of https://github.com/broccolijs/broccoli.

By the way, are you sure that what you want to do can't be done via the `public` folder? Whatever is in there should be copied as is.

**Comment by filipesilva** [comment]
Made obsolete by #1455. Anything that gets copied over is being watched now.
