### ISSUE TITLE
Allow / in asset paths

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#10181]
### Versions
```
Angular CLI: 6.0.0-rc.0
Node: 9.2.0
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

@angular/cdk: 5.2.4
@angular/cli: 6.0.0-rc.0
@angular/material: 5.2.4
@angular-devkit/architect: 0.5.0
@angular-devkit/build-angular: 0.0.10
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.5.0
@angular-devkit/schematics: 0.5.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-beta.9
@schematics/angular: 0.5.0
@schematics/update: 0.5.0
typescript: 2.4.2
webpack: 4.1.0

```

### Repro steps
```
{
                "glob": "favicon.ico",
                "input": "src",
                "output": "/"
              },
```

works, but 
```
{
                "glob": "favicon.ico",
                "input": "/src",
                "output": "/"
              },
```
does not recognize / generate the assets

### Desired behavior
Throw an error if my config is wrong / invalid, or support the /

**Comment by filipesilva** [comment]
`/src` and `src` mean different things though. `/src` is an absolute path, from the root of your file system. 

I don't think this is a bug, I think it fails because you don't have a `/src` folder at the root of your file system.

**Comment by StephenFluin** [comment]
I'm fine closing this. I logged this because "/src" was what the migration script created for me. I thought from a brief conversation that this was the bug, but feel free to close this one and then let's update the migration script.

**Comment by filipesilva** [comment]
Talking to @hansl about the intended semantics atm.

**Comment by hansl** [comment]
We decided that right now: (using Windows paths)

```
`/src/a/b/` => `C:\src\a\b`
`src/a/b/` => `${workspaceRoot}/a/b/`
`./src/a/b/` => `${workspaceRoot}/a/b/`
```

**Comment by filipesilva** [comment]
Checked the current workspace file and update logic and could not find any other instanced of paths starting with '/'. I think we are good for now.
