### ISSUE TITLE
Bug Report: Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Hyurl** [angular/angular-cli#10189]
### Versions
webpack 4.4.1
webpack-cli 2.0.13

### Observed behavior
Uncaught ReferenceError: global is not defined
    at <anonymous>:10:4

### Desired behavior
There is a **bug** when packing to `umd`, webpack passes the variable `global` to the function
`webpackUniversalModuleDefinition()`, while the browser doesn't have this variable pre-defined, the 
variable `window` should be passed instead, please fix this bug as soon as possible, I assume many users 
are suffering from this problem.

The argument should be passed as `typeof window === 'object' ? window : global`

**Comment by filipesilva** [comment]
I'm sorry, but I don't follow. Is this happening with Angular CLI? If so, can you provide a reproduction please?

**Comment by Hyurl** [comment]
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(global, function() { ... })

This is the top lines of generated bundle file (using `umd` as `output.libraryTarget`), which the `global` is passed to the function, and browsers, they don't have `global` defined, it should be changed to something like this:

`typeof window === 'object' ? window : global`

Otherwise the `Uncaught ReferenceError: global is not defined` will be thrown when including the bundle file in the web page.

**Comment by Hyurl** [comment]
Sorry, I've now noticed that I posted the issue to the wrong repository, I was gonna post it to webpack, but I opened too many pages in the browser, then... you know, sorry again.
