### ISSUE TITLE
ng new validation failed error

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#10187]
### Versions
```
 ng --version

Angular CLI: 6.0.0-rc.1
Node: 8.9.1
OS: win32 x64
Angular:
...
```

### Repro steps

* ng new ng-cli-6-1

### Observed behavior
Error `validation failed`

### Desired behavior
No error

**Comment by filipesilva** [comment]
I can confirm this happens. I think it is our validation of what is a valid project name. The name must be a valid HTML selector, and in those you must have a character after a dash.

So `ng new ng-cli-v6dot1` would work, as well as `ng new rc-one-project`.

Regardless, that error message is not very useful and it should be improved either way.

**Comment by alan-agius4** [comment]
Thanks, chaning the `name` to `ng new ng-cli-v6dot1` works :) Ps: that error message is from `ajv`
