### ISSUE TITLE
ng new build uses --prod

### ISSUE THREAD

**Issue by derobiom** [angular/angular-cli#10191]
### Versions
Angular CLI: 1.6.4
Node: 8.9.1
OS: win32 x64

### Repro steps
ng new testprog

### Observed behavior
Default build includes "--prod"

{
  "name": "testprog",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    **"build": "ng build --prod",**
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },...

### Desired behavior
Do not include "--prod"

Generating the project with  "build": "ng build --prod" causes production environment variables to be used. Such as, a production api.  This is not a good thing. I don't recall "--prod" being the default in older versions of the CLI?

### Mention any other details that might be useful (optional)
I was mortified when my app hit the production payments api. No damaged done except to my reputation and my inner child. Both DOA.

**Comment by hansl** [comment]
I agree this is an oversight. Better safe than sorry.
