### ISSUE TITLE
[es2015] Constructor don't call super

### ISSUE THREAD

**Issue by mantyz** [angular/angular-cli#10193]
### Versions
```
Angular CLI: 6.0.0-rc.1
Node: 8.11.1
OS: linux x64
Angular: 6.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router


@angular-devkit/architect: 0.5.1
@angular-devkit/build-angular: 0.5.1
@angular-devkit/build-optimizer: 0.5.1
@angular-devkit/core: 0.5.1
@angular-devkit/schematics: 0.5.1
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.1
@schematics/angular: 0.5.1
@schematics/update: 0.5.1
typescript: 2.7.2
webpack: 4.5.0
Linux (Debian 8)
```
### Repro steps

* ng new project
* change tsconfig.json target to es2015
* ng serve --prod
* run localhost:4200
* open browser DevTools console

### Observed behavior
![bug](https://user-images.githubusercontent.com/8867223/38381636-14ad4246-3910-11e8-971d-57bf03ce148e.png)

### Desired behavior
I want to see the demo page, but I see an error in the console.

**Comment by filipesilva** [comment]
I think this happens because Build Optimizer does not support ES2015 yet. This is something we mean to support. Meanwhile you can turn off Build Optimizer in your production configuration in the `angular.json` file.

**Comment by markgoho** [comment]
@filipesilva is there any urgency to fixing this? Or is it like if we set the output to es6 then it's already "optimized" and we're not losing much by not having Build Optimizer.

**Comment by filipesilva** [comment]
Heya, just wanted to mention that we are tracking this problem in https://github.com/angular/devkit/issues/816.

@markgoho I don't have an exact timeframe but it is definitely a 6.x concern.

**Comment by svstartuplab** [comment]
It only took 6 hours of troubleshooting to find this thread but in the angular.json file this works:
    "buildOptimizer": false,
