### ISSUE TITLE
Generate docs somehow

### ISSUE THREAD

**Issue by cironunes** [angular/angular-cli#102]
The CLI should generate the docs for the application code. We can probably use dgeni for that?

**Comment by daniele-zurico** [comment]
+1

**Comment by adamclerk** [comment]
+1

**Comment by caseyhoward** [comment]
This would be great. I have looked at dgeni a few times and still have no idea how to begin using it. I don't want to have to come up with my own HTML templates, CSS, and basically write a javascript program just to generate some docs.

On a related note, I like to run my protractor tests against the documentation examples directly. It would be nice to have that option.

**Comment by vamsivarikuti** [comment]
Take a look at https://github.com/rangle/angular2-dgeni-starter

**Comment by hansl** [comment]
This will be supported later next year with addon support. Closing this, we will have a separate discussion about it when the project is ready.

**Comment by caseyhoward** [comment]
So what do I follow to know when the project is ready?
