### ISSUE TITLE
“Http failure response for (unknown url): 0 Unknown Error” Angular

### ISSUE THREAD

**Issue by med004** [angular/angular-cli#10209]
I try use service httpClient post but I have this error:

https://i.stack.imgur.com/q49od.png

code service:

`constructor(private http:HttpClient) { }

              Login(data)
              {

                let headers: any = new HttpHeaders();
                headers.append('Content-Type', 'application/json');

                return this.http.post('link api',data,{headers: headers})
                .subscribe(res => console.log(res),err => { console.log(err);});

              }
`

and I try add responseType: 'text' but also error ... I use angular 4

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by AlessAndree** [comment]
I have the same problem!
How i can solve?

**Comment by kishore0207** [comment]
I am having the problem with the Unknown url.
How can i solve this problem?
 
{"headers":{"normalizedNames":{},"lazyUpdate":null,"headers":{}},"status":0,"statusText":"Unknown Error","url":null,"ok":false,"name":"HttpErrorResponse","message":"Http failure response for (unknown url): 0 Unknown Error","error":{"isTrusted":true}}
