### ISSUE TITLE
Component is not showing after ng build --prod 

### ISSUE THREAD

**Issue by sumitheda** [angular/angular-cli#10207]
using ng serve the app is working fine
but when i make a build using ng build --prod then a component is not showing in the ui 
all component elements showing as hidden 

sometimes with normal build using 'ng build' the component is showing in the ui.

and there is no error in console and while making the build

Angular cli version -> 1.7.3

**Comment by Worthy7** [comment]
It's because of the CSS.
There is some kind of bug right now in prod versions which reverses the order of the CSS imports:
https://github.com/angular/angular-cli/issues/8577

**Comment by BranCounts** [comment]
I am having the same problem, even with new update, I have read that the default is with dev, see if running your build with —prod helps you

**Comment by sumitheda** [comment]
@BranCounts i tried with ng build --prod but it doesn't work for me. My component still not showing in the build.

**Comment by BranCounts** [comment]
Not sure what the problem is, are you using express to serve it?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
