### ISSUE TITLE
ng new broken on 6.0.0-rc2

### ISSUE THREAD

**Issue by robertbaker** [angular/angular-cli#10206]
### Versions
```
Angular CLI: 6.0.0-rc.2
Node: 9.11.1
OS: win32 x64
Angular:
```

### Repro steps
*  ```ng new tester```

### Observed behavior
```
events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

### Desired behavior
Works

### Mention any other details that might be useful (optional)
 Node 9.11.1

I uninstalled node, deleted my npm and yarn global folders, reinstalled node and cli with yarn

**Comment by filipesilva** [comment]
This is a bug in our rc.2 release, fixed via https://github.com/angular/angular-cli/pull/10208 and will be in the rc.3 release.

This does mean `ng new` and generators are broken on rc.2 when using rc.2. I'll have to ask you to use rc.1 if you are on Windows. Sorry about that :/

**Comment by filipesilva** [comment]
Another workaround until the new version is out is to use both `--skip-install --skip-git` on `ng new` (thanks to @clydin for pointing that out).

**Comment by filipesilva** [comment]
@markgoho-EDT I think what you're running into now is https://github.com/angular/angular-cli/issues/10335. We're looking at how to fix it ATM.
