### ISSUE TITLE
@angular-devkit/schematics: error

### ISSUE THREAD

**Issue by jimmy-khalifa** [angular/angular-cli#10212]
Hi,
I just installed angular/cli 1.7.4 when I run the command 
`ng g c test --module app`
I got the following error 
```
Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
```

When I run `ng -v` I got the following
```
@angular/cli: 1.7.4
@angular-devkit/build-optimizer: error
@angular-devkit/core: 0.5.4
@angular-devkit/schematics: error
```

### Versions
1.7.4

### Repro steps
Run `ng -v`
or Run `ng g c test --module app`

### Observed behavior
Errors with @angular-devkit/schematics
Nothing happened

### Desired behavior
Generate new component

**Comment by filipesilva** [comment]
@jimmy-khalifa I think the error is accurate: you don't seem to have the packages installed. Something probably went wrong during installation.

Please try to remove your `node_modules`, `package-lock.json` and reinstalling dependencies via `npm install`.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by blowsie** [comment]
I have this issue with Angular 6.2.3
```
Angular CLI: 6.2.3
Node: 10.10.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.3
@angular-devkit/core         0.8.3
@angular-devkit/schematics   0.8.3
@schematics/angular          0.8.3
@schematics/update           0.8.3
rxjs                         6.2.2
typescript                   2.9.2
```

Reverting to angular 6.1.1 fixed the issue.

**Comment by blowsie** [comment]
@alan-agius4  does this information suffice?

**Comment by hampton1122** [comment]
Same issue.

`Angular CLI: 6.2.5
Node: 8.12.0
OS: darwin x64
Angular: 6.0.7
... animations, common, core, forms, http, language-service
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.3
@angular-devkit/build-angular     0.8.3
@angular-devkit/build-optimizer   0.8.3
@angular-devkit/build-webpack     0.8.3
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cli                      6.2.5
@angular/compiler                 6.1.10
@angular/compiler-cli             6.1.10
@ngtools/webpack                  6.2.3
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.20.2`

I run command `ng generate store State --root --statePath store/reducers --module app.module.ts`

And get the follwoing
`Cannot find module '@angular-devkit/schematics'
Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /Users/champton/git/sp/sp-system-checkout/node_modules/@ngrx/schematics/src/store/index.js:50:24
    at Object.defineProperty.value (/Users/champton/git/sp/sp-system-checkout/node_modules/@ngrx/schematics/src/store/index.js:41:17)
    at Object.<anonymous> (/Users/champton/git/sp/sp-system-checkout/node_modules/@ngrx/schematics/src/store/index.js:47:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)`
