### ISSUE TITLE
[es2015, angular/material, moment.js] Strange function transformation

### ISSUE THREAD

**Issue by mantyz** [angular/angular-cli#10217]
### Versions
```
Angular CLI: 1.7.4
Node: 8.11.1
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.4
@angular/material-moment-adapter: 5.2.4
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
[Initial issue](https://github.com/angular/material2/issues/10347) contains repro steps.

### Observed behavior
Strange [daysInMonth](https://github.com/moment/moment/blob/23104ffecdcf7a084babe20997d96a410540ff98/src/lib/units/month.js#L19-L26) function transformation with `target=es2015`
View details in comment https://github.com/angular/material2/issues/10347#issuecomment-378780775

### Desired behavior
I want to see a working material datepicker.

**Comment by mantyz** [comment]
Opened an issue for UglifyJS https://github.com/mishoo/UglifyJS2/issues/3055

**Comment by filipesilva** [comment]
@mantyz can you try with `--build-optimizer=false`? Build Optimizer does not support es2015.

**Comment by mantyz** [comment]
@filipesilva, Yes, it works with `--build-optimizer = false`. But it also works with sets various `--prod` flags where `--build-optimizer = true`.
```
ng build --aot=true --environment=prod --output-hashing=all --sourcemaps=false \
--extract-css=true --named-chunks=false --build-optimizer=true
```
[This page](https://github.com/angular/angular-cli/wiki/build#es2015-support) does not indicate that you need to disable `--build-optimizer` for es2015 support.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
