### ISSUE TITLE
Consider webpack+typescript optimization

### ISSUE THREAD

**Issue by kondi** [angular/angular-cli#10224]
This article talks about a very nice incremental build speedup: https://medium.com/@kenneth_chau/speeding-up-webpack-typescript-incremental-builds-by-7x-3912ba4c1d15

Is the second tip applicable for angular cli projects? (Enemy #<span></span>2: Competing resolution logic between Webpack and ts-loader)

About the first one, I am not sure if angular cli is affected, would be amazing if it is.

**Comment by filipesilva** [comment]
There's a lot of really nice information in here. Some of this is definitely applicable to the build setup we use in Angular CLI. I have some performance benchmarking I want to do soon (but after 6.0 final probably) and I will add these to the list. Thanks!

**Comment by alan-agius4** [comment]
Closing as this should be addressed by now.
