### ISSUE TITLE
The completion command is missing in 6.0.0-rc.2

### ISSUE THREAD

**Issue by xxxtonixxx** [angular/angular-cli#10238]
### Versions
```
Angular CLI: 6.0.0-rc.2
Node: 9.5.0
OS: linux x64
```

### Repro steps

`ng completion --zsh >> ~/.zshrc`

**Comment by hansl** [comment]
This is by design. It got stale in 1.7, was too hard to maintain, and even harder as we moved to the new build and with additional schematics.

We would prefer that someone else maintains a Oh-my-Zsh plugin or some shell script that works better.

Closing this as working as intended.
