### ISSUE TITLE
Serving or building with --sourcemaps failing

### ISSUE THREAD

**Issue by cwillwer** [angular/angular-cli#10234]
### Versions
```
$ node_modules/.bin/ng -v
_                      _                 ____ _     ___
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
/ △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
/ ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
|___/

Angular CLI: 1.7.4
Node: 8.6.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.1.0
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.3.4
webpack: error
```
**Notice the error for the webpack version above.**

### Repro steps
* Step 1: The CLI has not been installed globally. `package.json` contains the following entries.
```
"devDependencies": {
  "@angular/cli": "^1.7.4",
  "@angular/compiler-cli": "^4.0.0",
  "@angular/language-service": "^4.0.0",
...
```
* Step 2: Install all modules with `npm install`.
* Step 3: `package.json` contains the following definition for running the server with `npm start` or building it with `npm run-script build`:
```
"scripts": {
  "start": "ng serve --sourcemaps",
  "build": "ng build --sourcemaps",
...
}
```

### Observed behavior
```
$ npm start

> website@1.0.1 start C:\path\to\angularproject
> ng serve --sourcemaps

Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\path\to\angularproject\node_modules\html-webpack-plugin\lib\compiler.js:11:26)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\path\to\angularproject\node_modules\html-webpack-plugin\index.js:7:21)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! website@1.0.1 start: `ng serve --sourcemaps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the website@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Desired behavior
I should not have to install the CLI globally. The relative path to the `webpack/lib/node/NodeTemplatePlugin` module does exist under the CLI module as shown below (running in Git Bash shell on Windows), so it should be able to find everything that it needs in order to build the sourcemaps.
```
$ ls C:/path/to/bitbucket/angularproject/node_modules/@angular/cli/node_modules/webpack/lib/node/
NodeChunkTemplatePlugin.js           NodeMainTemplate.runtime.js       NodeOutputFileSystem.js  NodeTemplatePlugin.js
NodeEnvironmentPlugin.js             NodeMainTemplateAsync.runtime.js  NodeSourcePlugin.js      NodeWatchFileSystem.js
NodeHotUpdateChunkTemplatePlugin.js  NodeMainTemplatePlugin.js         NodeTargetPlugin.js
```
This system where I am running this is primarily used as a business laptop, not for development, so I don't want to pollute it with globally installed development tools. In addition, this is the only project I have that uses Angular, so when I move from system to system to do development, I want it to be as self-contained as possible so that each new system requires minimal setup. I should be able to install node/npm, check out the code repo, do an `npm install`, and start using the project locally or making small changes to it. That is not currently the case.

**Comment by cwillwer** [comment]
Actually, this doesn't have to do with the CLI being installed globally. I just did a global install (`npm install -g @angular/cli@1.7.4` and got the same error, so I'll update the title to reflect that it's just failing. Perhaps it's due to Windows, running in a Git Bash shell, or the `html-webpack-plugin` package mentioned in the callstack. That seems most likely since that package is installed at the root of the `node_modules` directory while `webpack` is installed under the cli module for some reason. npm 5.3.0 is installed. I'm not sure who is dictating where webpack should be installed. I thought npm after version 3 was supposed to install all packages at the top `node_modules` path in order to support package reuse, but that doesn't appear to be happening because there is no `webpack` under the top-level `node_modules`.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by glebmachine** [comment]
i've got the same about half year long

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
