### ISSUE TITLE
Versions of @angular/compiler-cli and typescript could not be determined.

### ISSUE THREAD

**Issue by hardy12994** [angular/angular-cli#10256]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 8.9.4
OS: linux x64
Angular: 4.4.3
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cdk: 2.0.0-beta.12
@angular/cli: 1.7.4
@angular/compiler-cli: 5.2.9
@angular/language-service: 5.2.9
@angular/material: 2.0.0-beta.12
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.5.4
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0
```

### Package.json
```
"dependencies": {
    "@angular/animations": "4.4.3",
    "@angular/common": "4.4.3",
    "@angular/compiler": "4.4.3",
    "@angular/core": "4.4.3",
    "@angular/forms": "4.4.3",
    "@angular/http": "4.4.3",
    "@angular/platform-browser": "4.4.3",
    "@angular/platform-browser-dynamic": "4.4.3",
    "@angular/router": "4.4.3",
    "core-js": "2.5.1",
    "rxjs": "5.4.3",
    "zone.js": "0.8.17",
    "hammerjs": "2.0.8",
    "@angular/cdk": "2.0.0-beta.12",
    "@angular/material": "2.0.0-beta.12",
    "angular2-cool-storage": "^3.0.1",
    "angulartics2": "^2.2.0",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "cropperjs": "^1.0.0-beta.1",
    "croppie": "^2.4.0",
    "font-awesome": "^4.7.0",
    "intl": "^1.2.5",
    "jquery": "^3.1.1",
    "lato-font": "^2.0.0",
    "material-design-icons": "^3.0.1",
    "mutationobserver-shim": "^0.3.2",
    "ng2-bs3-modal": "^0.10.4",
    "ng2-dnd": "^2.0.1",
    "ng2-file-upload": "^1.1.4-2",
    "ng2-toasty": "^2.3.1",
    "swiper": "^3.4.2",
    "web-animations-js": "^2.2.5"
  },
  "devDependencies": {
    "@angular-devkit/core": "^0.5.4",
    "@angular/cli": "^1.7.4",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.4.2"
  }
```

### Observed behavior

**ON `ng serve` Command** i am getting this -

ERROR -

```
Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.
```

**Comment by joelebeau1** [comment]
Having the same issue with the following dependencies

`"dependencies": {
    "@angular/animations": "^4.0.1",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@ionic/storage": "^2.1.3",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-beta.4",
    "@types/gapi": "0.0.35",
    "@types/gapi.auth2": "0.0.47",
    "@types/lodash": "^4.14.62",
    "angular2-moment": "^1.8.0",
    "angulartics2": "^2.3.0",
    "aws-sdk": "^2.3.5",
    "bluebird": "^3.3.5",
    "body-parser": "^1.15.0",
    "bootstrap": "4.1.0",
    "composable-middleware": "^0.3.0",
    "compression": "^1.6.1",
    "connect-mongo": "^1.1.0",
    "cookie-parser": "^1.4.1",
    "core-js": "^2.4.1",
    "cron": "^1.3.0",
    "dotenv": "^4.0.0",
    "ejs": "^2.5.5",
    "errorhandler": "^1.4.3",
    "express": "^4.13.4",
    "express-jwt": "^5.1.0",
    "express-session": "^1.13.0",
    "ionic-angular": "^3.9.2",
    "ionicons": "^3.0.0",
    "jsonwebtoken": "^7.3.0",
    "lodash": "4.17.4",
    "lusca": "^1.3.0",
    "method-override": "^2.3.5",
    "moment": "^2.13.0",
    "moment-range": "^3.1.1",
    "moment-timezone": "^0.5.14",
    "mongoose": "4.9.3",
    "morgan": "^1.7.0",
    "ng2-file-upload": "^1.2.1",
    "ng2-select": "^1.2.0",
    "ng2-tag-input": "^1.0.5",
    "ng2-toastr": "^4.1.0",
    "ngx-bootstrap": "^2.0.5",
    "ngx-progressbar": "^2.0.3",
    "nodemailer": "^3.1.8",
    "nodemailer-mailgun-transport": "^1.3.5",
    "passport": "^0.3.2",
    "passport-local": "^1.0.0",
    "request": "^2.72.0",
    "rxjs": "^6.1.0",
    "serve-favicon": "^2.3.0",
    "tinymce": "^4.5.6",
    "ts-helpers": "^1.1.1",
    "validator": "^7.0.0",
    "xml2js": "^0.4.19",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.47",
    "@types/node": "^7.0.12",
    "chai": "^3.5.0",
    "chai-http": "^3.0.0",
    "codelyzer": "^3.1.2",
    "del": "^2.2.0",
    "eslint": "^4.2.0",
    "eslint-config-airbnb-base": "^11.2.0",
    "eslint-plugin-import": "^2.2.0",
    "font-awesome": "^4.7.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.5.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^1.0.0",
    "karma-jasmine": "^1.0.2",
    "lint-staged": "^3.4.0",
    "mockgoose": "^7.1.1",
    "nodemon": "^1.11.0",
    "postcss": "^5.2.17",
    "pre-commit": "^1.2.2",
    "protractor": "~5.1.0",
    "stylelint": "^7.10.1",
    "stylelint-config-standard": "^16.0.0",
    "ts-node": "3.0.2",
    "tslint": "^5.5.0",
    "tslint-eslint-rules": "^4.1.1",
    "typescript": "^2.4.2"
  }`

**Comment by PrabalKM** [comment]
Any update on this?

**Comment by kikkiraj** [comment]
Issue fixed for me when i updated my CLI 

`npm install -g @angular/cli`

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.7.4.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
