### ISSUE TITLE
Angular compiler option "preserveWhitespaces" only works if placed in tsconfig.app.json, gets ignored in base tsconfig.json

### ISSUE THREAD

**Issue by fillmorejl** [angular/angular-cli#10262]
### Versions
```
Angular CLI: 1.7.4
Node: 9.11.1
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.8.1
webpack: 3.11.0
```

### Repro steps

As the title says, if you place the following:
```
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  },
```

in the outer tsconfig.json like the Angular documentation says, It will not strip all the HTML template white spaces. As soon as you place it in the inner tsconfig.app.json, which extends the base tsconfig.json, the HTML white space stripping works as intended.

### Desired behavior
Placing:

```
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  },
```
into the base tsconfig.json like the Angular documentation says:

[https://angular.io/guide/aot-compiler#angular-compiler-options](https://angular.io/guide/aot-compiler#angular-compiler-options)

should properly enable HTML white space stripping.

**Comment by criduvero** [comment]
@fillmorejl Check this issue: https://github.com/angular/angular-cli/issues/10859

**Comment by KlausHans** [comment]
Hello, this is quite confusing. The Angular documentation/the upgarde helper (https://update.angular.io/) says

> Choose a value of off for preserveWhitespaces in your tsconfig.json to gain the benefits of this setting while the default is still to preserve whitespace.

In the linked issue @danwulff says to alter tsconfig.app.json. Whats the way to go now? Both?

**Comment by obtdap** [comment]
I still have the problem !!
I've put preserveWhitespaces: true in tsconfig.app.json, in tsconfig.json and in options of bootstrapModule but it don't works.
The only way I've found is to put preserveWhitespaces: true in all the components !!

Anyone has still the problem ?

Angular V.6.1.7

**Comment by X4V1** [comment]
the process is still running after more than one hour. Is it normal ? Is there any way of doing it in verbose mode or manually ?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

Angular 7 now resolves extended config
