### ISSUE TITLE
How to use in a folder?

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#1027]
I'm working on an open source project, where I want to have a demo folder based on Angular CLI. I want all files for the demo inside the /demo folder, but it should not have its own node_modules and typings folder obviously; it should look at the parent folder for that.
I already receive the following error: 
````
$ ng build
Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat 'C:\Projects\git\yjg\ng2-bingmaps\demo\typings'
````
Is there a way that I can set the root folder to be the parent? Or is what I want just too hard?

**Comment by filipesilva** [comment]
The CLI isn't very well suited to be used as a completely separate subproject inside another project. It requires a certain structure at the top level and being a subproject runs contrary to that.

My suggestion for your case is to use https://github.com/angular/quickstart instead.
