### ISSUE TITLE
Getting error when installing Angular CLI

### ISSUE THREAD

**Issue by Iamguy84** [angular/angular-cli#10279]
Hi folks,

I am trying to install angular cli but I am getting error message and it says:

> C:\>npm install -g @angular/cli@latest
> C:\Users\asalahuddin\AppData\Roaming\npm\ng -> C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
> 
> > node-sass@4.8.3 install C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node":
> 
> tunneling socket could not be established, statusCode=407
> 
> Hint: If github.com is not accessible in your location
>       try setting a proxy via HTTP_PROXY, e.g.
> 
>       export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
>       npm config set proxy http://example.com:8080
> 
> > uglifyjs-webpack-plugin@0.4.6 postinstall C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\webpack\node_modules\uglifyjs-webpack-plugin
> > node lib/post_install.js
> 
> 
> > node-sass@4.8.3 postinstall C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> > node scripts/build.js
> 
> Building: C:\Program Files\nodejs\node.exe C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp\\bin\\node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.6.2
> gyp info using node@6.10.2 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` failed Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed  python2 { Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb check python checking for Python executable "python" in the PATH
> gyp verb `which` failed Error: not found: python
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed  python { Error: not found: python
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb could not find "python". checking python launcher
> gyp verb could not find "python". guessing location
> gyp verb ensuring that file exists: C:\Python27\python.exe
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at Object.failNoPython (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\lib\configure.js:483:19)
> gyp ERR! stack     at Object.<anonymous> (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-gyp\lib\configure.js:508:16)
> gyp ERR! stack     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\node-sass
> gyp ERR! node -v v6.10.2
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> Build failed with error code: 1
> C:\Users\asalahuddin\AppData\Roaming\npm
> `-- @angular/cli@1.7.4
>   +-- @angular-devkit/build-optimizer@0.3.2
>   | +-- source-map@0.5.7
>   | `-- typescript@2.6.2
>   +-- @angular-devkit/core@0.3.2
>   | +-- ajv@5.5.2
> .........
> ........
> **//omitted**

**OS**
Microsoft Windows [Version 10.0.16299.125]

**Version**
Node: 6.10.2
NPM: 3.10.10

**Comment by filipesilva** [comment]
It looks like a problem installing `node_sass`, which is a dependency of `@angular/cli`. Specifically it looks like a problem downloading the node sass binaries.

Please have a look at https://github.com/sass/node-sass#binary-configuration-parameters for help with these problems.

There isn't much we can do outside of removing the dependency (and thus the sass support), which isn't really an option right now.

**Comment by Iamguy84** [comment]
@filipesilva 
I tried 

> npm install node-sass --sass-binary-site=https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node -g

**Error:**

> C:\Users\asalahuddin\AppData\Roaming\npm\node-sass -> C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\bin\node-sass
> 
> > node-sass@4.8.3 install C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node/v4.8.3/win32-x64-48_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node/v4.8.3/win32-x64-48_binding.node":
> 
> tunneling socket could not be established, statusCode=407
> 
> Hint: If github.com is not accessible in your location
>       try setting a proxy via HTTP_PROXY, e.g.
> 
>       export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
>       npm config set proxy http://example.com:8080
> 
> > node-sass@4.8.3 postinstall C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass
> > node scripts/build.js
> 
> Building: C:\Program Files\nodejs\node.exe C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.6.2
> gyp info using node@6.10.2 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` failed Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed  python2 { Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb check python checking for Python executable "python" in the PATH
> gyp verb `which` failed Error: not found: python
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed  python { Error: not found: python
> gyp verb `which` failed     at getNotFoundError (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:13:12)
> gyp verb `which` failed     at F (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:68:19)
> gyp verb `which` failed     at E (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:80:29)
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\which\which.js:89:16
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\index.js:42:5
> gyp verb `which` failed     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\isexe\windows.js:36:5
> gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:123:15)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb could not find "python". checking python launcher
> gyp verb could not find "python". guessing location
> gyp verb ensuring that file exists: C:\Python27\python.exe
> gyp ERR! configure error
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
> gyp ERR! stack     at Object.failNoPython (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:483:19)
> gyp ERR! stack     at Object.<anonymous> (C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\node-gyp\lib\configure.js:508:16)
> gyp ERR! stack     at C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass\node_modules\graceful-fs\polyfills.js:284:29
> gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
> gyp ERR! System Windows_NT 10.0.16299
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\asalahuddin\\AppData\\Roaming\\npm\\node_modules\\node-sass\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd C:\Users\asalahuddin\AppData\Roaming\npm\node_modules\node-sass
> gyp ERR! node -v v6.10.2
> gyp ERR! node-gyp -v v3.6.2
> gyp ERR! not ok
> Build failed with error code: 1
> npm ERR! Windows_NT 10.0.16299
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "--sass-binary-site=https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node" "-g"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> 
> npm ERR! node-sass@4.8.3 postinstall: `node scripts/build.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the node-sass@4.8.3 postinstall script 'node scripts/build.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the node-sass package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node scripts/build.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs node-sass
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls node-sass
> npm ERR! There is likely additional logging output above.
> npm ERR! Windows_NT 10.0.16299
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "--sass-binary-site=https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node" "-g"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! path C:\npm-debug.log.629499236
> npm ERR! code EPERM
> npm ERR! errno -4048
> npm ERR! syscall open
> 
> npm ERR! Error: EPERM: operation not permitted, open 'C:\npm-debug.log.629499236'
> npm ERR!     at Error (native)
> npm ERR!  { Error: EPERM: operation not permitted, open 'C:\npm-debug.log.629499236'
> npm ERR!     at Error (native)
> npm ERR!   errno: -4048,
> npm ERR!   code: 'EPERM',
> npm ERR!   syscall: 'open',
> npm ERR!   path: 'C:\\npm-debug.log.629499236' }
> npm ERR!
> npm ERR! Please try running this command again as root/Administrator.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\npm-debug.log

**Comment by msterba** [comment]
@Iamguy84 

1. Download the binary https://github.com/sass/node-sass/releases/download/v4.8.3/win32-x64-48_binding.node/v4.8.3/win32-x64-48_binding.node manual via your browser.
2. Set an environment variable to pointing to the downloaded binary, e. g.: `SASS_BINARY_PATH=C:\downloads\.....win32-x64_binding.node`
3. `npm install @angular/cli`

Keep the downloaded binary file and the environment variable, even if you don't use SASS. Otherwise you might get errors every time you add dependencies to your package.json or create a new project.

You'll probably have to add another version of the sass binary when you update your node.js installation.

If you just want to try Angular, you could just use an online IDE like https://stackblitz.com/fork/angular

**Comment by altschuler** [comment]
I fixed this by manually installing the latest version of node-sass

**Comment by bluehenry** [comment]
Thanks @msterba, your way works on my side.

**Comment by Iamguy84** [comment]
@altschuler 
It works!
