### ISSUE TITLE
New command fails (ng add @angular/pwa --project foobar) [6.0.0-rc.3]

### ISSUE THREAD

**Issue by un33k** [angular/angular-cli#10287]
[x] Bug

### Versions
```
Angular CLI: 6.0.0-rc.3
Node: 9.6.1
OS: darwin x64
Angular: 6.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.1
@angular/flex-layout: 5.0.0-beta.14
@angular/material: 6.0.0-rc.1
@angular/platform-server: error
@angular/pwa: 0.5.5
@angular/service-worker: 5.2.9
@angular-devkit/architect: 0.5.5
@angular-devkit/build-angular: 0.5.4
@angular-devkit/build-ng-packagr: 0.5.5
@angular-devkit/build-optimizer: 0.5.4
@angular-devkit/core: 0.5.5
@angular-devkit/schematics: 0.5.5
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.2.4
@schematics/angular: 0.5.5
@schematics/update: 0.5.5
typescript: 2.7.2
webpack: 4.5.0
```

### Repro steps
* ng config -g cli.packageManager '"yarn"'
* ng add @angular/pwa --project foobar

### Observed behavior

```error An unexpected error occurred: "`install` has been replaced with `add` to add new dependencies. Run \"yarn add @angular/pwa\" instead.".```

### Desired behavior
It seems that the pwa command is tied to **npm** as far as the params go.  In this case, we want to run `yarn add` instead of `yarn install`.

### Workaround
* ng config -g cli.packageManager '"npm"'
* ng add @angular/pwa --project foobar
* ng config -g cli.packageManager '"yarn"'

**Comment by hansl** [comment]
Fixed by #10290
