### ISSUE TITLE
ng documentation is missing command option descriptions

### ISSUE THREAD

**Issue by SetTrend** [angular/angular-cli#10296]
Throughout the documentation of `ng` commands, their options are missing a description of the repercussions from the arguments they understand.

For example:

[`ng generate service`](https://github.com/angular/angular-cli/wiki/generate-service)

```
module

--module (aliases: -m)

Specifies where the service should be provided.
```

- Not a word about a module name that can be added to this option.
- Not an example whatsoever.

I believe this information should be added.

**Comment by filipesilva** [comment]
Heya, this is part of the large wiki issue https://github.com/angular/angular-cli/issues/10438, and will be added for 6.0.

**Comment by SetTrend** [comment]
Excellent!

I'm very much looking forward to the updated documentation.
