### ISSUE TITLE
6rc3 build size multiplied by 4 & build time multiplied by 2

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#10294]
### Versions
```
Angular CLI: 6.0.0-rc.3
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.1
@angular/material: 6.0.0-rc.1
@angular-devkit/architect: 0.5.5
@angular-devkit/build-angular: 0.5.5
@angular-devkit/build-optimizer: 0.5.5
@angular-devkit/core: 0.5.5
@angular-devkit/schematics: 0.5.5
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.3
@schematics/angular: 0.5.5
@schematics/update: 0.5.5
typescript: 2.7.2
webpack: 4.5.0
```

### Repro steps
update from 1.7.x to 6rc3

### Observed behavior
| cli version | build size in MB | build time in ms | command                                                       |
|-------------|------------|------------|---------------------------------------------------------------|
| 1.7.x       | 8.24    | 150000           | ng build --prod (+ others i18 options)                                |
| 6 rc.x      | 40.4    | 325078           | ng build myProject (+see image below) |

![image](https://user-images.githubusercontent.com/2789203/38662562-0c4be330-3e35-11e8-81f5-30f84edcd5c9.png)

**Comment by skreborn** [comment]
Why aren't you building with `--prod` in v6's case? Isn't it still required to actually make use of the defined `production` configuration?

**Comment by istiti** [comment]
@skreborn  with `--prod`  it is same. Maybe another syntax instead of `ng build myProject --prod ` ...

**Comment by filipesilva** [comment]
Heya @istiti, and 4x build size sounds like something is broken somewhere. `ng build myProject --prod` should give you a prod build.

I'm not sure where to start. Can you tell me if the output from CLI 6 in dist looks like it is uglified? All the vars renamed and in a single line.

Other than that I'd have to debug myself... in the projects we tests, we didn't see a size increase and the build time went down.

**Comment by istiti** [comment]
thanks @filipesilva  ,
I tried many times... same behavior.

The only problem is "build size" I still get `>40 MB` ( see screenshot I delete intentially)
### 1.7.x verison build
![image](https://user-images.githubusercontent.com/2789203/38682678-fe46e50a-3e6b-11e8-8f74-ff7ceaa2d32d.png)


#### 6rc3 build
![image](https://user-images.githubusercontent.com/2789203/38682573-b7009ef2-3e6b-11e8-86a9-7c07aedd2ced.png)

My heart is broken too ^^

To answer to your question: yes one line and yes vars renamed

**Comment by filipesilva** [comment]
@istiti very helpful information in your last comment, thank you!

@clydin was wondering if our sourcemaps were bugged but looking at the bundle you uploaded and the screenshot of file sizes, we now know that's not the case.

So we can see that some bundles just got much, much bigger. 

I think that explains why the build time is longer: webpack and build optimizer have a lot more code to process.

I don't have an explanations for why the bundles got bigger in the first place. 

I notice you have a vendor chunk in the second rc.3 example. Can you try setting `vendorChunk` to false in the production configuration please?

**Comment by istiti** [comment]
@filipesilva  if you want to see content of some module let me know: 
![image](https://user-images.githubusercontent.com/2789203/38685379-1611831a-3e72-11e8-876b-5adeeff2dd17.png)

**Comment by istiti** [comment]
@filipesilva  yep some are weird, here you are: 
![image](https://user-images.githubusercontent.com/2789203/38724864-b7fc154e-3f05-11e8-8684-13874a2e35ad.png)

my routing.ts are declared from /src/... example: 
```
{
    path: '', component: WrapperComponent,
    children: [
      // Module des immeubles
      {path: 'immeuble', loadChildren: 'src/app/immeuble/immeuble.module#ImmeubleModule'},

      // Module des objets
      {path: 'objet', loadChildren: 'src/app/objet/objet.module#ObjetModule'},
      
      // Module des baux
      {path: 'bail', loadChildren: 'src/app/bail/bail.module#BailModule'},

      // Module des loyers
      {path: 'loyer', loadChildren: 'src/app/loyer/loyer.module#LoyerModule'},

      // Module des personnes
      {path: 'personne', loadChildren: 'src/app/personne/personne.routes.module#PersonneRoutesModule'},

      // Modules des autorisations (Utilisateurs et groupes)
      {path: 'authorisation', loadChildren: 'src/app/autorisations/autorisations.module#AutorisationsModule'},

      {path: 'donnees-statiques', loadChildren: 'src/app/donnees-statiques/donnees-statiques.module#DonneesStatiquesModule'},

      {path: 'societe', loadChildren: 'src/app/societe/societe.module#SocieteModule'},
      {path: 'sauvegardes-rapides', loadChildren: 'src/app/sauvegardes-rapides/sauvegardes-rapides.module#SauvegardesRapidesModule'},

      {path: 'home', component: HomeComponent},
      {path: '', pathMatch: 'full', redirectTo: 'home'}
    ]
  }
```

**Comment by istiti** [comment]
I edit my last [comment](https://github.com/angular/angular-cli/issues/10294#issuecomment-381064792)

**Comment by istiti** [comment]
I found the bug here! But i can't understand.

If it can help you here you are the squelete of my code. If you are interested in one module/file in particular let me know .

In this [stackblitz](https://stackblitz.com/edit/angular-gitter-skchb7?file=app%2Fapp.module.ts) repro, I write (not working) structure of my app.

Please check where is imported DialogModule.

If in app.module = 115 numeroted chunks generated.
If in wrapper.module = 96 numeroted chunks generated.


cc @filipesilva @clydin

**Comment by clydin** [comment]
The observed behavior isn't necessarily a bug but a result of the new behavior for Webpack 4, and as a result CLI 6.0.  The module analysis and splitting is significantly more advanced.  In CLI 1.x all common modules found within lazy routes where combined into one potentially large common chunk.  While this reduced the size of the affected modules, it required all these lazy routes to download and use this common chunk regardless of how many of those common modules were actually needed for that route.  The new behavior now creates more granular common chunks based on the specific needs of each lazy chunk and only loads the necessary common chunks for each lazy route.  This is the cause for the increase in file count.  Overall this should provide a benefit to end users of the application by reducing the amount of data necessary to visit a particular lazy route.  This can be especially true if, for example, two routes (out of potentially many) require a vary large dependency that would in CLI 1.x be required to be downloaded by all lazy routes but now would not.

The settings may need to be fine tuned over time as more data is collected from a variety (e.g., lazy route count, dependency count & size, etc.) of projects.

**Comment by clydin** [comment]
Also, a blog post by the Webpack team provides some more details regarding the new behavior: https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366

**Comment by istiti** [comment]
@clydin 
thanks to your explanation !
I was thinking it's bug but your response convice me to like this approach of lazyroutes! 

I just notice that when more chunks are created size of app is around 1 MB bigger. This is too normal ?

You let my issue still opened I won't close it myself, feel free close it.

ps : someone create duplication here https://github.com/angular/angular-cli/issues/10364 might be related

thanks again

**Comment by clydin** [comment]
This should now be improved in the upcoming release.  If you are still encountering issues after the new release, please open a new issue with your findings.
