### ISSUE TITLE
Error when trying to install latest version

### ISSUE THREAD

**Issue by TheStap** [angular/angular-cli#10298]
### Versions
```
no versions, just trying to install my project dependencies
Angular CLI: 1.5.5
Node: 8.9.1
OS: win32 x64
Angular: error
... animations, cdk, cli, common, compiler, compiler-cli, core
... flex-layout, forms, http, language-service, material
... platform-browser, platform-browser-dynamic, router


typescript: error
webpack: error


```

### Repro steps

* Step 1
yarn cache clean
* Step 2
yarn add @angular/cli@latest

### Observed behavior
```
yarn add v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/mat5.js/-/mat5.js-1.3.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\[username]\\WebstormProjects\\[project]\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

### Desired behavior

Install goes correctly

It looks like @angular/cli depends on outdated package, which is not incluided in yarnpkg or npmjs registry. Is there any solution?

Also, it can be useful, this is my yarn lock file

[yarn.zip](https://github.com/angular/angular-cli/files/1902508/yarn.zip)

```yarn why v1.5.1
[1/4] Why do we have the module "md5.js"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "md5.js@1.3.4"
info Reasons this module exists
   - "@angular#cli#webpack#node-libs-browser#crypto-browserify#browserify-cipher#evp_bytestokey" depends on it
   - Hoisted from "@angular#cli#webpack#node-libs-browser#crypto-browserify#browserify-cipher#evp_bytestokey#md5.js"
Done in 0.62s.
```

**Comment by istiti** [comment]
try:
1. remove node_modules
2. remove package lock file  or yarn lock file
3. yarn remove @angular/cli
4. yarn global remove @angular/cli
5. yarn global add @angular/cli@latest 
6. yarn add @angular/cli@latest
7. yarn install
8. ng -v

**Comment by TheStap** [comment]
That worked, thanks. link was incorrect because it was hand-edited. Issue can be closed.

**Comment by istiti** [comment]
@TheStap please close issue yourself

**Comment by filipesilva** [comment]
Closing as @istiti, figured out how to solve this problem, cheers!
