### ISSUE TITLE
Angular 4 unexpected token

### ISSUE THREAD

**Issue by anivaisu** [angular/angular-cli#10295]
hi ,

 I am trying to create prod build using this command

 `ng build --prod --aot=false`

 Here is my tsconfig.json

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "noStrictGenericChecks": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "ES5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2015",
      "es2016",
      "es2017",
      "dom"
    ]
    
  }
  
}
```

I got this issues.

```
ERROR in 0.803ef7037b38f740459f.chunk.js from UglifyJs
Unexpected token: name (SpinnerComponent) [0.803ef7037b38f740459f.chunk.js:36822,4]

ERROR in vendor.854b1629f48f001f3cee.bundle.js from UglifyJs
Unexpected token: name (StarRatingUtils) [vendor.854b1629f48f001f3cee.bundle.js:49814,6]
```

I dont know whats this error.

How can i fix this issue.

Kindly help me.

**Comment by istiti** [comment]
can you please fill correctly template 

ps: https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#submit

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

If I had to bet, one of your libraries is shipping ES2015 files. That library is the one exporting ` `SpinnerComponent` and `StarRatingUtils`.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
