### ISSUE TITLE
Brand new angular app build fails on missing package (6.0.0-rc.3)

### ISSUE THREAD

**Issue by un33k** [angular/angular-cli#10303]
```
[x] Bug report
```

### Versions
```
Angular CLI: 6.0.0-rc.3
Node: 9.6.1
OS: darwin x64
Angular: 6.0.0-rc.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 6.0.0-rc.3
@angular-devkit/architect: 0.5.5
@angular-devkit/build-angular: 0.5.5
@angular-devkit/build-ng-packagr: error
@angular-devkit/build-optimizer: 0.5.5
@angular-devkit/core: 0.5.5
@angular-devkit/schematics: 0.5.5
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.3
@schematics/angular: 0.5.5
@schematics/update: 0.5.5
typescript: 2.7.2
webpack: 4.5.0
```

### Repro steps
* ng new myProj
* cd myProj
* ng build # <--- success
* ng g library myPkg
* ng build # <--- fails

### Observed behavior
```
Error: Could not find module "@angular-devkit/build-ng-packagr"
```

### Desired behavior
Perhaps we might need to auto-install `@angular-devkit/build-ng-packagr`.

### Mention any other details that might be useful (optional)
Some docs on releases > RC.0 would be nice to help us help you in early testing.

**Comment by devarg** [comment]
Same here, after migration from 5.x to 6.x this package is not added as necessary, though is added when generating a new app via  **ng new myapp**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by sudhirdeshmukh** [comment]
Hi,
I am still facing the same issue,
Angular CLI: 7.3.9
Node: 8.9.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.9
@angular-devkit/core         7.3.9
@angular-devkit/schematics   7.3.9
@schematics/angular          7.3.9
@schematics/update           0.13.9
rxjs                         6.3.3
typescript                   3.2.4
