### ISSUE TITLE
6rc4 showCircularDependencies

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#10318]
### Versions
```
Angular CLI: 6.0.0-rc.4
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6
@angular-devkit/build-angular     0.5.6
@angular-devkit/build-optimizer   0.5.6
@angular-devkit/core              0.5.6
@angular-devkit/schematics        0.5.6
@angular/cdk                      6.0.0-rc.3
@angular/material                 6.0.0-rc.3
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.4
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.0.0-turbo-rc.4
typescript                        2.7.2
webpack                           4.5.0

```

### Repro steps
add `"showCircularDependencies":false` in projects.myProject.architect.serve.configuration.production have no effet, circular warning are shown

**Comment by filipesilva** [comment]
That option is part of the build options, not the serve options. Can you try adding it to the build configuration instead?

**Comment by istiti** [comment]
ah sooo !!! :o

@filipesilva you are right!

I misunderstood, i was ALWAYS thinking:
architect.build is when using -> ng build
architect.serve is when using -> ng serve
but it seems not the case ^^, hope it will be explained soon.

Can we close this issue or interesting  as reminder

**Comment by filipesilva** [comment]
Yeah we will explain this in a blog post for CLI 6.0 changes. 

`ng serve` uses the `serve` entry, which references the `build` one.

```
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "my-app:build",
            "port": 4200,
            "host": "localhost"
          },
          "configurations": {
            "production": {
              "browserTarget": "my-app:build:production"
            }
          }
        },
```

This configuration means:

"When you run `ng serve`, we will build `my-app:build` and serve on localhost:4200".

The production configuration for `serve` changes what browser target it uses. Instead of using `my-app:build`, it will use `my-app:build:production` instead. That is why the options change.

**Comment by filipesilva** [comment]
I will close the issue for now.
