### ISSUE TITLE
rc.4 test command doesn't take --environment flag in account

### ISSUE THREAD

**Issue by rokerkony** [angular/angular-cli#10320]
### Versions
```
Angular CLI: 6.0.0-rc.4
Node: 9.11.1
OS: darwin x64
Angular: 6.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.6
@angular-devkit/build-angular     0.5.6
@angular-devkit/build-optimizer   0.5.6
@angular-devkit/core              0.5.6
@angular-devkit/schematics        0.5.6
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.4
@schematics/angular               0.5.6
@schematics/update                0.5.6
rxjs                              6.0.0-turbo-rc.4
typescript                        2.7.2
webpack                           4.5.0
```

### Repro steps
* Generate new project with cli@rc.4
* update `angular.json` test section and add configuration:
```
"configurations": {
  "production": {
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.prod.ts"
      }
    ]
  }
}
```
* Add log to `./src/app/app.component.ts`
```
  constructor() {
    console.log('environment', environment);
  }
```

* run tests with `ng test --environment=production` or `ng test --environment=prod` or change environment in karma.conf.js as follows:
```
    angularCli: {
      environment: 'prod'
    },
```

### Observed behavior
prints:
`LOG: 'environment', Object{production: false}`

in other words it doesn't switch environment file

### Desired behavior
Environment flag should update my environments files...

Maybe `--environment` flag is deprecated now?

p.s.: works with flag `--prod` (link to #10319) but environment allows us to use different env for tests e.g.: `testing` or `qa`

**Comment by balteo** [comment]
@rokerkony 
If you wish to specify an environment, say **myEnv**, use the following config:

```  
  "configurations": {
            "myEnv": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.myEnv.ts"
                }
              ]
            }
          }
```

and then run your tests as follows: `ng test --environment=myEnv`

If you wish to enable prod build, use the **--prod** flag.

**Comment by rokerkony** [comment]
ok so `--configuration` is a way to go! it works :) thank you

btw. does the environment make still any sense?

**Comment by rokerkony** [comment]
same question goes fo environment flag in karma config

**Comment by balteo** [comment]
> btw. does the environment make still any sense?

It seems the `--environment` command line flag is gone but of course your environment files are still valid and being used.

**Comment by rokerkony** [comment]
closing as a solution is now to use `--configuration myEnv`

**Comment by balteo** [comment]
> same question goes for environment flag in karma config, does it make sense to keep it?

Good question ! I am not sure.
