### ISSUE TITLE
Not able to install angular-cli

### ISSUE THREAD

**Issue by ankiy** [angular/angular-cli#10321]
Hi,
When i hit the command "npm install -g @angular/cli", i have error:

C:\Users\Mac>npm install -g @angular/cli
npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT: no such file or directory, stat 'C:\Users\Mac\angular\cl
i'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.3.9600
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Mac\\AppData\
\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"

npm ERR! cwd C:\Users\Mac
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.13
npm ERR! path C:\Users\Mac\angular\cli
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Mac\npm-debug.log
npm ERR! not ok code 0

C:\Users\Mac>

**Comment by filipesilva** [comment]
To use Angular CLI you need NPM 3 or higher, as described in https://github.com/angular/angular-cli#prerequisites.

At the moment you are using NPM 1.
