### ISSUE TITLE
system-builder -> buildStatic

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#1032]
I found the file: https://github.com/angular/angular-cli/blob/master/lib/broccoli/angular-broccoli-bundle.js
there are `builder.bundle(...`
but why do you use `bundle` instead of `buildStatic`?
if I work on some lib like: `bootstrap` or `angular.materials` it is ok. but if I work with some services/website I don't need sytem js into my build of project.
if I use `buildStatic` my build will be smaller.
Maybe will be a good idea to add some option for build command: `ng build --static`?

**Comment by filipesilva** [comment]
Made obsolete by #1455.
