### ISSUE TITLE
--proxy-config option missing in new ng e2e

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#10329]
### Versions
```
cli 6.0.0-rc.4
```

### Repro steps
- `npm i @angular/cli@next -g`
- `ng new helloworld`
- add `--proxy-config proxy.config.json` to npm `e2e` script in `package.json`
- `cd helloworld`
- `npm run e2e`

### Observed behavior
```
Unknown option: '--proxyConfig'
```

### Desired behavior
`ng e2e` should continue to support a proxy config as before.

### Mention any other details that might be useful (optional)
Works with `ng serve`.

**Comment by cyrilletuzi** [comment]
Looks like `ng e2e` is now taking options directly from `ng serve` options. For info, you need to config your `angular.json` like this: 

```json
"serve": {
  "options": {
    "browserTarget": "appname:build",
    "proxyConfig": "proxy.conf.json"
   }
}
```

**Comment by Bartosz-D3V** [comment]
Hi @cyrilletuzi 
I am not sure about latest version of Angular CLI, but in version 1.6.5 you can add a proxy to protractor by a command line like this:
(package.json)
``
"e2e": "ng e2e --proxy-config proxy.conf.json",
``
Not sure why it was not documented in the wiki, it looks like a 'natural' way of adding a proxy - similar to the ng serve.

**Comment by mcherb** [comment]
for .angular-cli.json i added

"serve": {
      "port": 4200,
      "host": "localhost",
      "proxyConfig": "./proxy.conf.json"
    }

thanks @cyrilletuzi
