### ISSUE TITLE
ERROR ReferenceError: 'Proxy' is undefined

### ISSUE THREAD

**Issue by bhenav** [angular/angular-cli#10324]
hello,
not working ie and safari. 

**$ node -v**
v8.10.0

**$ npm -v**
5.8.0

**$ ng -v**
Your global Angular CLI version (1.7.3) is greater than your local
version (1.6.6). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

Angular CLI: 1.6.6
Node: 8.10.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.6
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.6.2
webpack: 3.10.0

![angular-ie-bug](https://user-images.githubusercontent.com/14276250/38740247-c28207c8-3f3f-11e8-9a8d-5de49d084461.gif)

Thank you in advance for your help.

**Comment by msterba** [comment]
I assume the polyfills have nothing to do with the problem and are accidentally in the gif.

Are you trying to redirect to an internal backend system or an external service?
What is the content of your proxy.conf.js? Be sure to xxx-out confidental information, if you post it.

When I got my proxy-configuration wrong, I had never a related message in the browser, always on the shell. Browser just showed a generic connection problem. But that may vary depending on the proxy, I'm no expert.

What's the request your app is sending? Maybe the Network-tab of you browser dev-tools have additional information.

**Comment by bhenav** [comment]
thank you @msterba .  save my day :)

**Comment by filipesilva** [comment]
Thanks @msterba, that was a very detailed and insightful post! I think that addresses the problem @bhenav was having so I'll close this issue. Thanks again!
