### ISSUE TITLE
Default project for ng add

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#10327]
### Versions
```
cli 6.0.0-rc.4
material 6.0.0-rc.3
```

### Repro steps
- `npm i @angular/cli@next -g`
- `ng new helloworld`
- `npm install @angular/{material,cdk}@next`
- `ng add @angular/material`

### Observed behavior
```
Multiple projects are defined; please specify a project name
```

### Desired behavior
Should install in the default project when there is just one.

**Comment by clydin** [comment]
There's two projects by default: the app and e2e.  Either an option or some heuristics would need to be added to define the _default_ project.

**Comment by cyrilletuzi** [comment]
Oh, OK. Thanks for the info. Closing then.

**Comment by clydin** [comment]
I think it is an import usability concern though.  So I'd like to keep it open for discussion.

**Comment by hansl** [comment]
`ng add` does not do anything, this is Material's issue. We just pass the flags to material itself.

We should provide helper functions to read and manage `angular.json`, but in the meantime everyone's responsible for managing it themselves. Material should support not having a project though.

**Comment by hansl** [comment]
Material will fix this on their side; their issue for reference is https://github.com/angular/material2/issues/10833

**Comment by cyrilletuzi** [comment]
For info, there is a similar problem with `ng g service-worker`, but maybe it is by design.

**Comment by keatkeat87** [comment]
ng add @angular/material --project=name 
it work.
