### ISSUE TITLE
Add more support to yarn create

### ISSUE THREAD

**Issue by SandHilt** [angular/angular-cli#10339]
Yarn supports add "create-*" in global _env_ and update automagically: https://yarnpkg.com/docs/cli/create/
Why don't create an alias? like ```yarn create angular-app ng-app```<br>
I use a command similar in npm with npx
```bash
npx @angular/cli new ng-app --minimal
```

**Comment by cmckni3** [comment]
This would be very nice. The package [`create-angular-app`](https://www.npmjs.com/search?q=create-angular-app) already exists on npm.

The create command supports namespaces as well though.

It could be something like:

```
yarn create @angular/cli my-app
```

This would require the cli to be published as `@angular/create-cli` as well.

Another option I like is `yarn create @angular/app my-app` which would require a `@angular/create-app` package to be published.

However, my initial thought is that yarn should have a generalized command and function like `npx`.

**Comment by cmckni3** [comment]
However, my initial thought is that yarn should have a generalized command and function like `npx`.

**Comment by alan-agius4** [comment]
Also related to https://github.com/angular/angular-cli/issues/14292

**Comment by dgp1130** [comment]
We were able to take ownership of the `create-angular` package, which is how `yarn create angular` would actually be implemented. Currently this package is empty, so we'll need to push a new version that just runs `ng new`. Hopefully we can do a simple one-off publish, but we might need to include this in our usual release cycle (sadly `npx` is not installed by default with `yarn`, so we can't just `npx @angular/cli@latest new`).
