### ISSUE TITLE
ng g module app-routing throws error in project

### ISSUE THREAD

**Issue by kombattriarii** [angular/angular-cli#10347]
### Versions
Angular CLI: 6.0.0-rc.3
Node: 9.4.0
OS: win32 x64
Angular: 6.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 6.0.0-rc.1
@angular/material: 6.0.0-rc.1
@angular-devkit/architect: 0.5.5
@angular-devkit/build-angular: 0.5.5
@angular-devkit/build-optimizer: 0.5.5
@angular-devkit/core: 0.5.5
@angular-devkit/schematics: 0.5.5
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.0.0-rc.3
@schematics/angular: 0.5.5
@schematics/update: 0.5.5
typescript: 2.7.2
webpack: 4.5.0

### Repro steps
this is a bit hard. this is a small existing Angular cli project where slight editing was done to the app.comonent.
1) create project.
2) modify the basic component slightly.
3) add a few imports to app.module
4) then try ng g module app-routing

### Observed behavior
Unexpected token } in JSON at position 1307

### Desired behavior
ideally the angular cli routeing base would be added. if it cannot due to something that has been changed, then a slightly more helpful error message should be displayed.

**Comment by sandangel** [comment]
I think you need to specify the --project flag

**Comment by sandangel** [comment]
no, you must specify the project name you want to generate template to because cli now support multi project in 1 workspace. so cmd will look likes: `ng g m app-routing --project projectName`

**Comment by kombattriarii** [comment]
Unexpected token } in JSON at position 1307

adding that returns this again.

**Comment by hansl** [comment]
Please try with rc.5. A lot of errors regarding reading the configuration were fixed.

**Comment by kombattriarii** [comment]
Got:

Unexpected token } in JSON at position 1307

with:

ng -v

Angular CLI: 6.0.0-rc.5
Node: 9.4.0
OS: win32 x64
Angular: 6.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.5
@angular-devkit/build-angular     0.5.5
@angular-devkit/build-optimizer   0.5.5
@angular-devkit/core              0.5.5
@angular-devkit/schematics        0.5.7
@angular/cdk                      6.0.0-rc.1
@angular/cli                      6.0.0-rc.5
@angular/material                 6.0.0-rc.1
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.0-rc.3
@schematics/angular               0.5.7
@schematics/update                0.5.7
rxjs                              6.0.0-tactical-rc.1
typescript                        2.7.2
webpack                           4.5.0

**Comment by kombattriarii** [comment]
to add to this I get the same message from

 ng g component componets/home-view

but,

ng build and ng serve both see work.

**Comment by TheILPlace** [comment]
in 6.0.0-rc.5 it works without a problem (both generating modules and components)

**Comment by hansl** [comment]
Downgrading this to nice to have, seems to be a user error and need more information (angular.json content).

**Comment by kombattriarii** [comment]
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "NewUI": {
      "root": "",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/NewUI",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ],

            "styles": [
              {
                "input": "src/styles.css"
              },
              {
                "input":
                  "./node_modules/materialize-css/dist/css/materialize.min.css"
              }
            ],
            "scripts": [
              {
                "input":
                    "./node_modules/materialize-css/dist/js/materialize.min.js"
              }
            ],
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "src": "src/environments/environment.ts",
                  "replaceWith": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "NewUI:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "NewUI:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "NewUI:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              {
                "input": "styles.css"
              }
            ],
            "scripts": [],
            "assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "NewUI-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "NewUI:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  }
}

**Comment by Brocco** [comment]
There is a trailing comma after the `scripts` section for the `NewUI` project.

**Comment by filipesilva** [comment]
Closing as per @Brocco's comment.
