### ISSUE TITLE
Module generation broken in 1.7.4

### ISSUE THREAD

**Issue by pumano** [angular/angular-cli#10340]
When I execute `ng g m Settings --routing`
I got broken settings module. Problem in filename when it has been generated. For more details check "Observed behavior" section below.
### Versions
```
Angular CLI: 1.7.4
Node: 9.7.1
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.7
@angular-devkit/schematics-cli: 0.4.9
@angular-devkit/schematics: 0.4.7
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
@schematics/schematics: 0.4.9
typescript: 2.8.1
webpack: 3.11.0

macOS (High Sierra)
```

### Repro steps

* Step 1: install angular cli 1.7.4 and cd to project root
* Step 2 ng g m Settings --routing
* Step 3 check console output and __path__ folder in project root

### Observed behavior
```
$ ng g m Settings --routing
  create src/app/settings/settings-routing.module.ts (251 bytes)
  create __path__/__name@dasherize@if-flat__/__name@dasherize__.module.ts (287 bytes)
$ 
```

### Desired behavior
`ng g m Settings --routing` should generate 2 files with proper filenames

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
