### ISSUE TITLE
Issue: How to resolve warnings in angular-cli?

### ISSUE THREAD

**Issue by bhaidar** [angular/angular-cli#10341]
Hello,
This is a question and I need your assistance, please.
I am publishing an application with angular-cli to be able to host it on a web server. However, I am getting warnings after the package is generated.

`WARNING in Empty property 'top' at 38528:2. Ignoring.`

Can you guide me on where to search to try to find this warning?

See details below:

> ng build --prod --aot
> Date: 2018-04-14T16:43:39.496Z
> Hash: 2f4b4864e5fc06f19a78
> Time: 29637ms
> chunk {scripts} scripts.6a3664adfa303ed2dcb2.bundle.js (scripts) 1.58 MB [initial] [rendered]
> chunk {0} 0.09154b285423265e2524.chunk.js (common) 378 kB  [rendered]
> chunk {1} 1.1f5e8eaa29da0635c303.chunk.js () 4.01 kB  [rendered]
> chunk {2} 2.8ad14273acdb738cda55.chunk.js () 96.1 kB  [rendered]
> chunk {3} main.a64634c8f4ce92fcfb5a.bundle.js (main) 779 kB [initial] [rendered]
> chunk {4} polyfills.a5214ab831fec809b225.bundle.js (polyfills) 59.4 kB [initial] [rendered]
> chunk {5} styles.57c1b3dde10b6adf85c2.bundle.css (styles) 1.48 MB [initial] [rendered]
> chunk {6} inline.a1e76fba20a162a90f22.bundle.js (inline) 1.45 kB [entry] [rendered]
> 
> WARNING in Empty property 'top' at 38528:2. Ignoring.

**Comment by msterba** [comment]
Maybe a CSS issue? Similar to https://github.com/angular/angular-cli/issues/9784

**Comment by bhaidar** [comment]
Hi @msterba 
I am importing the Metronic 5 template and I've got hundreds of CSS/JS files. I've been searching for many hours now for this empty property 'top' and I cannot seem to find anything! Is there a log I can generate from angular-cli that would point me to more info about this warning? That's really difficult to find without additional info!

**Comment by bhaidar** [comment]
I was able to find the problem after a long time searching on that. It was a css rule using this:
`top: !important`

I changed to
`top: 0 !important`

Now it works fine!

**Comment by fhurta** [comment]
I have similar issue - the build ends with:

`WARNING in Invalid background value at 3171:18. Ignoring.`

I went through css and scss files but cannot find the problem. Some more info would be needed to find the source of the problem.

**Comment by Eddie541** [comment]
Same thing WARNING in Invalid background value at 12851:18. Ignoring.
Searched through [dist] css and scss files but cannot find the problem

**Comment by nathan-douds-cc** [comment]
Yea, similar question here: getting multiple animation warnings and I have literally commented out all of my animation code (so I don't know where else to look), yet I still get:
```WARNING in Invalid animation value at 10069:24. Ignoring.
WARNING in Invalid animation value at 10139:24. Ignoring.
WARNING in Invalid animation value at 10228:24. Ignoring.
WARNING in Invalid animation value at 10316:24. Ignoring.
```

**Comment by zicaros** [comment]
Yeah, these warning so a bit annoying.
`WARNING in Invalid animation value at 211:12. Ignoring.`

Please tell more information of warning
