### ISSUE TITLE
ng build --prod error because ngsw-config.json not moved during migration

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#10357]
### Versions
```
cli v6.0.0-rc.4
```

### Repro steps
From an Angular 5 project generated with `--service-worker`:
* update and migrate to v6
* ng build --prod

### Observed behavior
```
Error: Expected to find an ngsw-config.json configuration file in the /path/to/app folder.
```

### Desired behavior
Migration from CLI 1.7 to 6.0 should move `/src/ngsw-config.json` to `/ngsw-config.json` if existing.

**Comment by santhoshnv** [comment]
same problem here...

**Comment by trojanc** [comment]
I resolved my issue on windows by changing the path created in `angular.json` during `ng upgrade` from
`"ngswConfigPath": "/src/ngsw-config.json",`
to
`"ngswConfigPath": "src/ngsw-config.json",`

Removing the leading /

**Comment by royling** [comment]
but `ngswConfigPath` option isn't defined in the cli json schema... editor is reporting it as invalid...

**Comment by royling** [comment]
@markau Thanks, it also needs to move `src/ngsw-config.json` to the project root dir (same as `angular.json`). I guess that's how service worker works implicitly within the new CLI.

**Comment by ranbuch** [comment]
I was having the same problem when my config file configure like this:
`"ngswConfigPath": "src/ngsw-config.json"`
I was trying to build `ng b --prod` from `src/app/shared` instead of building from the root folder.
Building from the root folder fix the issue for me.

**Comment by SamiHK** [comment]
Well. My "ngsw-config.json" file is in the root directory and in my angular.json I set 
`"ngswConfigPath": "./ngsw-config.json"` AND its working smoothly. So idea is to provide the path of ngsw-config.json file simple.
