### ISSUE TITLE
Do not pin versions on ng update

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#10356]
### Versions
```
cli 6.0.0-rc.4
```

### Repro steps
From an Angular 5 project:
* update the CLI to v6 and migrate
* `ng update @angular/core --next`

### Observed behavior
Pinned versions in `package.json`:
```json
"@angular/compiler": "6.0.0-rc.5",
"@angular/core": "6.0.0-rc.5",
"typescript": "2.7.2"
...
```

### Desired behavior
Keep semantic versionning in `package.json`:
```json
"@angular/compiler": "^6.0.0-rc.5",
"@angular/core": "^6.0.0-rc.5",
"typescript": "~2.7.2"
...
```

### Mention any other details that might be useful (optional)
Pinned versions mean we can't do anymore minor/patch updates of the whole project simply with `npm update` and goes against semver.

It's not the role of the CLI to pin the versions. It's the role of the package manager, and as Angular 6 and CLI 6 require Node >= 8.9 and npm >= 5.5, it means the job is already done in a proper way by the `package-lock.json`.

**Comment by hansl** [comment]
I'm pretty sure this is a dupe as we've talked about it internally, but can't find the original issue so marking this as required.
