### ISSUE TITLE
Circular dependency error on ng update

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#10367]
### Versions
```
cli v6.0.0-rc.5
```

### Repro steps
From an Angular 5 project with Material:
* `npm install @angular/cli@next`
* `ng update @angular/cli --migrate-only --from 1`

If doing the Angular/RxJS update first:
`ng update @angular/core --next`
Errors to:
`Package "@angular/cdk" has an incompatible peer dependency to "@angular/common" (requires "^5.0.0", would install "6.0.0-rc.5").`

If doing the Material update first:
`ng update @angular/material --next`
Errors to:
`Package "@angular/common" has an incompatible peer dependency to "rxjs" (requires "^6.0.0-rc.0", would install "5.5.10")`

If doing a global update:
`ng update --next --all`
Errors to:
`Package "@angular/core" has an incompatible peer dependency to "rxjs"`

Maybe it's just because of the `--next` option which causes a version mismatch, or because `rxjs` use `rc` tag instead of `next` tag, but not sure, so signaling.

**Comment by hansl** [comment]
You can use `--force` to force it.  I think the better approach is to update Angular Core first. There will be a material update that's compatible with Angular 6 (it already is, just didn't say so in the package.json).

**Comment by hansl** [comment]
Marking this as required, but I don't think there's a proper path to fixing this. We just need to have our documentation in order when doing the update.

**Comment by hansl** [comment]
Special casing Angular X to be also compatible with Angular X+ (therefore a peer dep to Angular Core 5.x will be compatible with 6.x).
