### ISSUE TITLE
6rc5 observed behaviors

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#10365]
### Versions before update
```
Angular CLI: 6.0.0-rc.4 (global and local)
Angular: 6.0.0-rc.5
Rxjs 6rc7
```

### Repro steps & Observed behavior
1. my project is already on new strcuture with cli6rc4 / rxjsrc7 / 
2. npm i -g @angular/cli@next ( to install rc5) I get this message, I don't understand why it show me that while I was on 6rc4: 
![image](https://user-images.githubusercontent.com/2789203/38851060-78e2ddcc-4214-11e8-9575-bcc7f7825ce2.png)
I think this message should appear only if im on old structure of project.

3. I run `ng update --next` to check if new version exist it say me I can update to 6rc5 using `ng update @angular/cli`
4. I run it and I get somes "PERM ERRORS" so I delete node_modules I open package.json quickly to check if something's weird, I can't explain why but I notice I have in dependencies{} and devDependencies{} : `"@angular/cli": "^6.0.0-rc.3",`
5. I run `npm update --next` it ask me to update typescript 2.7.2 to typescript 2.9.abcdg...
6. I remove cli from package.json, I delete `node_modules` then `npm i @angular/cli@next` then `npm i` and now it's OK.

**Comment by filipesilva** [comment]
Heya @istiti thank you for checking this! That's definitely not the expected experience when updating. We'll look at this for 6.0 final 👍
