### ISSUE TITLE
Bug in 'ng build' when using npm's link option

### ISSUE THREAD

**Issue by costescuandrei** [angular/angular-cli#10368]
### Versions
```
Angular CLI: 1.7.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
typescript: 2.5.3
webpack: error
 
For Tooling issues:
- NPM version: 5.8.0
- Platform:  Windows 10
```

### Repro steps
Environment vars set below make npm packages be installed in a specific 'global' location and using the link setting to reuse packages and avoid 300 MB downloaded and installed for each separate app. This way each default CLI new app will use 50-60 KB of disk space instead of ~300 MB each. So for example with those set the cli install would be equivalent to a `npm install --link --prefix D:\angularCLI\alternateGlobalNPMRepo -g @angular/cli` command.

To reproduce it run the following commands inside an empty dir (in my case 'D:\angularCLI') (I am on windows 10, using cmd):

```
set npm_config_link=true
set npm_config_prefix=D:\angularCLI\alternateGlobalNPMRepo
set PATH=%PATH%;%npm_config_prefix%

npm install -g @angular/cli
ng new my-new-app
cd my-new-app

ng build
ng serve --open
```

Both `ng build` and `ng serve --open` will give an error: 
> ERROR in No NgModule metadata found for 'AppModule'.

But if you change something in app.module.ts, save, change it back, save then `ng serve` compiles successfully and refreshing the browser will show the app.

### Observed behavior
'ng build' gives an incorrect error in scenario detailed below. If I do 'ng serve --open' it also fails to compile initially but if I remove a bracket, save and undo + save again in app.module.ts for example then compile will pass and app runs normally. So there seems to be a glitch in ng build the first time it runs, because the second time it works correctly although the contents are identical.

### Desired behavior
'ng build' should pass as it is just a default new app generated using CLI
'ng serve' should work from the start without the workaround described above

### Mention any other details that might be useful (optional)
Npm link basically creates OS symbolic links in the node_modules folder towards the global npm folder - so I don't know why ng build fails first time. Please fix this so I don't have to download and store the same 300 MB multiple times when I don't need to.

**Comment by filipesilva** [comment]
I'm sorry to say, but I am not sure if your approach can ever work. Npm link has known problems with peer dependencies, and building a project requires correct peer dependencies.

But I am happy to say that with 6.0 the global CLI got drastically smaller.

**Comment by costescuandrei** [comment]
Thanks for the comment.

I hoped it would not be a dead-end. I like it when available options work well together or are documented not to work together... So you are saying this is an npm bug right?

Are you thinking of a particular reported issue on npm?

**Comment by hansl** [comment]
Hi @costescuandrei,

You can try running node with `--preserve-symlinks` (see [here](https://nodejs.org/api/cli.html#cli_preserve_symlinks)), but that also has its own set of problems.

Like @filipesilva said, this is likely to never work. I'm going to close this as such.

**Comment by agil-NUBBA** [comment]
same here, back to `@angular/cli@1.7.4`.

**Comment by costescuandrei** [comment]
As a hint you can try to use pnpm instead of npm with the option --shamefully-flatten, as some stuff that angular uses rely on the underlying structure of node_modules dir. (https://github.com/pnpm/pnpm)

So you can check if something like this works for you:
```
npm install -g pnpm
pnpm install -g pnpm

pnpm install -g --shamefully-flatten @angular/cli
ng new test-pnpm --skip-install
cd test-pnpm
pnpm i --shamefully-flatten
ng build
```
