### ISSUE TITLE
alias -d for --directory conflicts with -d for --dry-run

### ISSUE THREAD

**Issue by StevenLiekens** [angular/angular-cli#10366]
`ng new` suggests that `--directory` has an alias `-d` but that actually triggers a dry run.
https://github.com/angular/angular-cli/blob/b517c0fbe2796764e48b75bc7d2846e64bfc1332/docs/documentation/new.md

I don't know if this is a documentation issue only, or a real problem in the code.

**Comment by hansl** [comment]
There is no `directory` option on `ng new` anymore in 6.0, so this is not related to that milestone.

Thanks for the report @StevenLiekens.  This seems to be a mistake in our documentation. There should not be an alias for directory.

**Comment by StevenLiekens** [comment]
Alright well it would be nice if that wiki page received some more attention. I noticed other things that don't look right to me. The aliases for `skip-commit` and `skip-git` and `skip-install` don't seem to work either. Also I'm not sure what I should expect when I use both `skip-commit` and `skip-git`.

**Comment by kolkov** [comment]
...and how now to create an application in the current folder?

**Comment by dgp1130** [comment]
Documentation has since been updated to remove `--directory`. There's a separate effort to review existing docs and make sure they are up to date and usable. I don't think there's anything else to handle in this issue.
