### ISSUE TITLE
ng build -prod + AsyncRoute (router-deprecated)

### ISSUE THREAD

**Issue by demetrio812** [angular/angular-cli#1036]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

v4.2.6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

1) Create an app `ng new TestProdBuild`
2) Create a route `ng g route test`
3) Adding a link to the main component to check if the route is working.

`ng build -prod` is working properly

4) Replacing the router with the router-deprecated (changed `package.json` and `system-config.ts`)
5) Change the router annotation to use the Sync routing

`ng build -prod` is working properly

6) Use `AsyncRoute` and obviously the loader tries to load the js file (that doesn't exist)

4. The log given by the failure. Normally this include a stack trace and some
   more information.

After the step 6 I get this in the browser:

```
zone.js:101 GET http://localhost:8181/app/+test/index.js 404 (Not Found)
EXCEPTION: Error: Uncaught (in promise): Error: Error: XHR error (404 Not Found) loading http://localhost:8181/app/+test/index.js
  at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:8181/vendor/zone.js/dist/zone.js:769:30)
  at ZoneDelegate.invokeTask (http://localhost:8181/vendor/zone.js/dist/zone.js:356:38)
  at Object.inner.inner.fork.onInvokeTask (http://localhost:8181/main.js:19:22470)
  at ZoneDelegate.invokeTask (http://localhost:8181/vendor/zone.js/dist/zone.js:355:43)
  at Zone.runTask (http://localhost:8181/vendor/zone.js/dist/zone.js:256:48)
  at XMLHttpRequest.ZoneTask.invoke (http://localhost:8181/vendor/zone.js/dist/zone.js:423:34)
Error loading http://localhost:8181/app/+test/index.js
```

@filipesilva that was my problem, what are my options here? Should I avoid AsyncRoute until we get the new (new) router?

Thanks,
Dem

**Comment by filipesilva** [comment]
This... doesn't work at all at the moment. Bundling in the CLI didn't get as far as async routers yet, unfortunately.

**Comment by filipesilva** [comment]
Work working on getting async loading to work, but only on the new router. I don't have any details to share but since we're not focusing on the deprecated router anymore, I'll close this issue.
