### ISSUE TITLE
configuration to exclude few modules from bundling

### ISSUE THREAD

**Issue by syamalasravya** [angular/angular-cli#10374]
### Observed behavior
```
modules are not excluded from bundling
```

### Desired behavior
have some Questions..
1. Can we exclude specific modules from bundling?
2.Is there any configuration for turning off minification while bundling with angular cli

### Mention any other details that might be useful (optional)

I tried by adding 'exclude' in tsconfig.json file

{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  },
"exclude":["app-config.ts"]
}

**Comment by mgechev** [comment]
For support requests, the best channels would be gitter or stackoverflow.

We'd strongly recommend following the issue template and formatting your code. Thank you! :)
