### ISSUE TITLE
Mat-typography doesn’t work when I build my angular app.

### ISSUE THREAD

**Issue by LeonardoGastonRossi** [angular/angular-cli#10370]
### Versions
Angular  CLI: 1.7.4
Angular: 5.2.10
Material: 5.1.1

### Repro steps
* Generate build for some environment (dev, prod).
* Push app in that environment.

### Observed behavior
The font family and font sizes don't match with my configuration in mat-typography-config:

$raam-typography: mat-typography-config(
  $font-family: 'Open Sans',
  $headline: mat-typography-level(24px, 1.33, 400),
  $body-1: mat-typography-level(16px, 24px, 500),
  $button: mat-typography-level(16px, 1.0, 600)
);
@include angular-material-typography($raam-typography);

It's showing the default mat-typography-configuration for material.

### Desired behavior
The app should show the proper font family and font sizes.

### Mention any other details that might be useful (optional)
This starts to happen after updating my package.json and updating angular CLI and Angular version. (material version didn't change).

**Comment by Chan4077** [comment]
@LeonardoGastonRossi Please report this at the angular/material2 repo. This repo is meant for Angular CLI

**Comment by LeonardoGastonRossi** [comment]
@Chan4077 I didn't it because I didn't change the material version. Only angular and CLI version changed.

**Comment by Chan4077** [comment]
@LeonardoGastonRossi As I said, consider reporting this at the angular/material2 repo.

**Comment by LeonardoGastonRossi** [comment]
@Chan4077 at the end I could fixed the issue: I had to change the version of Angular CLI to 1.6.8. 
The latest versions are having this issue.

Thank you for your help.
