### ISSUE TITLE
Documentation: Code samples aren't visible when printed

### ISSUE THREAD

**Issue by SetTrend** [angular/angular-cli#10375]
I'm reading the documentation in a printed version as it's more versatile to me than to fuzz with a tablet, particularly in bed or outdoors.

Today I noticed that when printed by Firefox (latest, Windows 10), the code samples aren't visible:

![nocodeindocumentation](https://user-images.githubusercontent.com/9283914/38928769-8ab2e212-430a-11e8-89b1-47b58cddcc38.png)

<hr/>

PS: I'd like to give my kudos to those guys who have set up the documentation for easy printing. Great job!

I'd like to suggest to add a page containing the documentation as a whole, so that it can be printed as one big brochure instead of dozens of small brochures with empty trailing pages.

**Comment by istiti** [comment]
are you sure your issue is related to angular-cli ? i thing it's related to angular repo which contain aio

ps: i think you can remove background image when printing (on chrome you can) with firefox you could too

**Comment by SetTrend** [comment]
D'oh! .. I'm sorry, I'm always mixing these two repos up ... gee ... 😥 

Thanks for the hint, but I wouldn't want to play printer settings by ear. I'd easily have forgotten my previous settings next time I needed them.
