### ISSUE TITLE
IIS Server & +lazy-route not compatible

### ISSUE THREAD

**Issue by sharpmachine** [angular/angular-cli#1037]
The default security for IIS disallows `+` in the path names. When you try to go to a route where the parent component's directory is prepended with a `+` , the browser console logs a 404 error for all the parent component's resources: `http//:localhost:4200/subject`

If you try and hit a resource directly in the browser, IIS gives you a 404.11 error: `http://localhost:38772/app/+subjects/shared/index.js`

```
HTTP Error 404.11 - Not Found
The request filtering module is configured to deny a request that contains a double escape sequence.
```
![unknown](https://cloud.githubusercontent.com/assets/600836/15868860/782de738-2c9e-11e6-92b0-779248ddcb25.png)

**Comment by filipesilva** [comment]
We have it planned to be able to configure the prefix for routes, but that feature isn't implemented yet. 

Meanwhile, the workaround is to generate routes and remove the prefix manually.

**Comment by sharpmachine** [comment]
Thanks @filipesilva. Would you happen to know the ballpark ETA on that feature?

**Comment by filipesilva** [comment]
I don't have a rough ETA, no. But I labelled it as `required` which means it'll be there before 1.0 version of the CLI for sure.

**Comment by delasteve** [comment]
I haven't tried it, but it looks like https://github.com/angular/angular-cli/pull/846 addresses this.

**Comment by elvirdolic** [comment]
you can do a url rewrite something linke this

`<security>
        <requestFiltering allowDoubleEscaping="true"/>
    </security>
     <rewrite>
      <rules>
        <rule name="AngularJS Routes" stopProcessing="true">
          <match url=".*" />
          <conditions logicalGrouping="MatchAll">
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
            <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
          </conditions>
          <action type="Rewrite" url="/" />
        </rule>
      </rules>
    </rewrite>`

**Comment by filipesilva** [comment]
Oh wow, I completely forgot to check the current master! Thanks for catching it @delasteve!

So yeah, it should be in the next beta then. I'm closing the issue then, but feel free to reopen if it doesn't work when the next version is out.
