### ISSUE TITLE
6rc5 serving without sourcemaps

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#10372]
### Versions
```
Angular CLI: 6.0.0-rc.5 (global and local)
Angular: 6.0.0-rc.5
Rxjs 6rc7
webpack 4.5
```

### Repro steps
I can't `ng serve` my app without sourcemap (yes i need disable them in my large project, recompile is too long ! 
with `ng serve` command I tried theses options:
--no-sourcemap
--sourcemap=false
--sourceMap=false

I tried too add in `angular.json` serve.configuration production nothing works

### Observed behavior
It always serve sourcemap :(

### Desired behavior
Serving without sourcemap

**Comment by hansl** [comment]
This should work, might just be an oversight.

**Comment by istiti** [comment]
@hansl  i don't understand label "nice to have", this will works for v6 release again? in my medium (1.2k files) project, rebuilding in ng serve is multiplied by 3or4 and get me crazy

**Comment by istiti** [comment]
@hansl is it possible that this is working again in 6rc6 ? on my side i succeed to serve without sourcemaps, we can close or?

**Comment by clydin** [comment]
Closing as this appears to be resolved.
