### ISSUE TITLE
ng add @angular/material

### ISSUE THREAD

**Issue by kamalkech** [angular/angular-cli#10381]
Angular CLI: 6.0.0-rc.5
Node: 8.11.0
OS: darwin x64
Angular: 6.0.0-rc.5

when try to add angular material with commande : `ng add @angular/material`

i get this error : 

![telechargement 1](https://user-images.githubusercontent.com/1313428/38962032-54f29c7c-4363-11e8-9390-317bf4382aa0.png)

any idea ?

**Comment by MRMokwa** [comment]
You need to install the packages first:
`npm install --save angular/material2-builds@next angular/cdk-builds@next`
then
`ng add @angular/material`

**Comment by kamalkech** [comment]
@MRMokwa thank you for but i get this error when try to install packages : 

![npm-install](https://user-images.githubusercontent.com/1313428/39004972-b89c5086-43f6-11e8-86a8-742025e62253.png)

**Comment by MRMokwa** [comment]
Do you mind trying a new project from zero?

> ng n test-app
> cd test-app
> npm install --save @angular/material@next @angular/cdk@next
> ng add @angular/material

My versions:
![image](https://user-images.githubusercontent.com/12090931/39005501-c5fbcc7c-43d6-11e8-96ac-542d9c8c0058.png)

**Comment by lehoffma** [comment]
@MRMokwa When I try doing that, I only get a "Cannot read property 'includes' of undefined" message.

![image](https://user-images.githubusercontent.com/6012444/39008663-992ac206-4409-11e8-9731-947d2affe911.png)

My versions:
![image](https://user-images.githubusercontent.com/6012444/39008722-c0d5217a-4409-11e8-98b0-76d9c91ec26f.png)

Could the different node versions be the cause of this issue?

**Comment by kamalkech** [comment]
Hi @MRMokwa, i follow your instructions and i creat another new app and this a result: 

![am](https://user-images.githubusercontent.com/1313428/39008842-ccabbd40-4401-11e8-930b-2b562e650359.png)

**Comment by MRMokwa** [comment]
I just downgraded my Node and it still working as expected for me.
![image](https://user-images.githubusercontent.com/12090931/39009576-67035f1c-43e2-11e8-9f1a-c9c6b7849116.png)

![image](https://user-images.githubusercontent.com/12090931/39009595-702b8fce-43e2-11e8-83d0-65dce5747ff7.png)

Really weird issue, don't know what's causing it.

**Comment by cduran** [comment]
I'm having the same issue.

Here is my full version
![screen shot 2018-04-19 at 12 23 36 pm](https://user-images.githubusercontent.com/164527/39010662-8c062558-43cc-11e8-81d2-9b3e0a465c85.png)

And when I run `ng add @angular/material`
![screen shot 2018-04-19 at 12 22 17 pm](https://user-images.githubusercontent.com/164527/39010722-b0519910-43cc-11e8-8beb-5b3e2a19355f.png)

**Comment by FernandoGomez** [comment]
I'm getting the same issue.  On a new project:

![image](https://user-images.githubusercontent.com/3443120/39036613-46a4737e-443b-11e8-99ba-14a6a4e276e1.png)

These are my versions:

![image](https://user-images.githubusercontent.com/3443120/39036646-5bdf0bbe-443b-11e8-9f9a-db7c90557db0.png)

**Comment by FernandoGomez** [comment]
I've updated material and cdk to rc.12 and I'm now having the same issue as @cduran

**Comment by tobi-or-not-tobi** [comment]
This should be managed by the material team as its part of their schematics; its not a CLI issue. I had already logged the issue at https://github.com/angular/material2/issues/10912. 
@kamalkech you might want to close this one.

**Comment by kamalkech** [comment]
@tobi-or-not-tobi ok!

**Comment by kamalkech** [comment]
@tobi-or-not-tobi fixed when you update angular cli  to rc.7

**Comment by tobi-or-not-tobi** [comment]
Thanks @kamalkech, I'm unfortunately blocked by #10513.

**Comment by tobi-or-not-tobi** [comment]
@kamalkech But works fine when I update an existing project. Thanks for the heads-up.

**Comment by NELBNL** [comment]
with cli6 this works:

ng new x
cd x
ng add @angular/material@^6.0.0

No docs on schematics tho as seen in ngconf :( (and even docs for ng add are missing from the cli wiki)

**Comment by freelancersunil** [comment]
When i do:

`npm install --save @angular/material @angular/cdk `

it installs below:
+ @angular/material@6.3.2
+ @angular/cdk@6.3.2

Then, as per above solutions: 

I do:

`ng add @angular/material`

it throws as below:

Installing packages for tooling via npm.
Cannot read property 'startTag' of undefined

**Comment by freelancersunil** [comment]
ng add @angular/material@6.3.2  <----------- This worked for me
