### ISSUE TITLE
Webpack support for FeathersJS V3.x

### ISSUE THREAD

**Issue by yd021976** [angular/angular-cli#10385]
Hello, since V3.x, FeathersJS is shipped as ES6 code (see [Feathers migrating guide](https://docs.feathersjs.com/migrating.html#updating-client-side-applications)). Thus, we need a way to instruct webpack to transpile FeathersJS.

### Versions
```
Angular CLI: 1.7.3
Node: 6.10.3
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.14
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.4.8
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
Just add anywhere in angular app : `import * as feathers from '@feathersjs/feathers'`
I don't still test this, but sure it will not work in the browser because it doesn't support ES6.

### Observed behavior
Browser javascript error (for browser that don't support ES6) while parsing FeathersJS in ES6 code.

### Desired behavior
Angular build should transpile FeathersJS node module if it exists

### Mention any other details that might be useful (optional)
I know i can use "eject" from angular-cli to customize Webpack config. But i don't want to loose benefits of angular-cli and learn deep webpack config.

**Comment by mgechev** [comment]
Usually the package maintainer is the one responsible for shipping the correct versions of their library. `package.json` allows you to specify separate fields for different ES versions.

If, however, you prefer to customize your build, I'd recommend you to give `ngx-build-plus` a try. No need to eject.
