### ISSUE TITLE
Environment flag not working or not event check by webpack

### ISSUE THREAD

**Issue by yc09od** [angular/angular-cli#10392]
Environment flag not working.
It seems angular not even load or check the environment. It only import the enviroment.ts directly.

I using command "npm run ng server --prod" to test. It shows it pick the enviroment.ts but not enviroment.prod.ts all the time.

Event I change.

.angular-cli.json as 

"environmentSource": "./src/haha/environments/environment.ts",
      "environments": {
        "dev": "./src/haha/environments/environment.ts",
        "prod": "./src/haha/environments/environment.prod.ts"
      }

There is no error.

### Versions
Angular CLI: 1.6.3
Node: 8.11.1
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cli: 1.6.3
angular-devkit/build-optimizer: 0.0.36
angular-devkit/core: 0.0.22
angular-devkit/schematics: 0.0.42
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.9.3
schematics/angular: 0.1.11
schematics/schematics: 0.0.11
typescript: 2.5.3
webpack: 3.10.0

### Repro steps
At app.component.ts

import {environment} from '../environments/environment';

constructor() {
    console.log(environment);
  }

always return 
production : false

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
