### ISSUE TITLE
update: v5->v6 error because could not find assets that didn't exist

### ISSUE THREAD

**Issue by wardbell** [angular/angular-cli#10393]
`ng update` produced error **" Path "../something/somewhere/" is invalid."**

Here's the actual example
```
ng update @angular/cli --migrate-only --from=1                                                                                                  
            Updating karma configuration
            Updating configuration
           Path "/../server/" is invalid.
```
The old `.angular.json` had this
```
      "assets": [
        "assets",
        "favicon.ico",
        {
          "allowOutsideOutDir": true,
          "glob": "**/*.*",
          "input": "../server/",
          "output": "../server/"
        }
      ],
```
The error can be traced to the part that allows content to come from outside.  As it happened, there was no `../server/` directory. That didn't bother the CLI v5 but it caused the error seen above.

I was able to delete this part because I didn't need it.

What if someone really does need something external? That's a question for this issue too.

**Comment by istiti** [comment]
related  https://github.com/angular/angular-cli/issues/10350

**Comment by mgechev** [comment]
Let us keep track of this issue in https://github.com/angular/angular-cli/issues/10350.
