### ISSUE TITLE
Accelerate deployment `ng new project --config`

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#10399]
## I'm submitting a...
<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[x] Other... Please describe: Build improvements
</code></pre>
## Current behavior
In total, to run the first application, and the usual demo, I need to spend 6 minutes until it installs all the packages.  This is sometimes very annoying.

```
$ ng new demo
349.36 sec ~ 6 min
Project 'demo' successfully created
```

-------

If we use Vue then we can simply add a script

```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Vue CDN</title>
</head>
<body>
    ...
    <script src="https://cdn.jsdelivr.net/npm/vue@2.5.13/dist/vue.js"></script>
</body>
</html>
```

And all, you can write to start the application or if you usage vue init it's best start config cli

## Expected behavior

```
$ ng new project --config
? default install all dependencies (Y/n) n
# ========================
? Install @angular/router? (Y/n) n
? Use TSLint to lint your code? (Y/n) n
? Set up unit tests Karma (Y/n) n
? Setup e2e tests with Protractor? (Y/n) n
# Project initialization finished!
# ========================
To get started:

  ng serve

Documentation can be found at https://angular.io/guide/quickstart

```

If you make a customizable way to install the application, you could create simple applications faster.

**Comment by istiti** [comment]
imo this shouldn't be default but appear when `ng new project --config`

**Comment by Toxicable** [comment]
Those things are already configurable through flags.
In my opinion this is faster than a UI that Polls you for answers

**Comment by mgechev** [comment]
We're already working on prompts. Thanks for the early suggestion though, glad we're on the same page here :)
