### ISSUE TITLE
Running builds from /node_modules instead of /dist/vendor

### ISSUE THREAD

**Issue by nareshbhatia** [angular/angular-cli#1040]
Is there any reason to run builds from /dist/vendor? This not only requires an entry in `angular-cli-build.js` for every library that we want to add, but additional entries for every dependency of that library. This is very painful and completely unnecessary because `npm` has already done the hard job of recursively fetching all those dependencies into `node_modules`. Am I missing something? Is there an easy way to do this?

**Comment by kylecordes** [comment]
I believe some of the underlying tools are not yet able to understand how to find library files directly in node_modules. It is certainly possible: webpack does it by default, and rollup has a plug-in that enables it to understand node package resolution.  But, to serve the case where we aren't bundling files, this would mean node_modules is also served directly to the web browser, which is sort of ugly.

**Comment by nareshbhatia** [comment]
Still trying to understand how this case is different from [angular2-seed](https://github.com/mgechev/angular2-seed) - it serves the dev build from `node_modules` and the prod build from a compressed packaged bundle. I don't know anything about the underlying tools for angular-cli, but can't they support a similar workflow?

**Comment by kylecordes** [comment]
Unfortunately that is "over my pay grade" :-). Someone on the CLI team could possibly comment on why they have chosen to make CLI work quite differently from the seed project you linked. I personally have four different sets of build tooling for Angular 2 (we use it when teaching classes), and there are endless trade-offs and things partly done everywhere.

**Comment by filipesilva** [comment]
The decision was mostly because Angular-CLI is based on Ember-CLI, and that's how Ember-CLI did it. 

That being said there are trade-offs between different approaches. For instance, it's still very valuable to generate a standalone, portable `dist/` dir for deployments. Copying over all of `node_modules` isn't a good way of going about it because a lot of stuff there is needed for the build process rather than the runtime app.

**Comment by nareshbhatia** [comment]
@filipesilva, I don't see the trade off. Running from `node_modules` is only for dev builds. For prod builds, the tool should be smart enough to package only what's needed - automatically. What's painful currently is to *manually* figure out what's needed for either build. Please look at the angular-seed workflow - it has done this already.
