### ISSUE TITLE
Run two categories of test with ng test

### ISSUE THREAD

**Issue by YoannBureau** [angular/angular-cli#10402]
### Description
I have two different types of tests:
* Unit tests (standard angular cli **.spec.ts** files)
* Functional tests (my specific **.func.spec.ts** files, works the same way as .spec.ts files, but not mocked and injects data in my db, so no need to run them all the time)

I am trying to :
* Exclude the .func.spec.ts files from the `ng test` command to only run **.spec.ts** test file
* Call the test command to only run **.func.spec.ts**

So my functional tests are not executed in the regular `ng test` context and can be run separately.

I tried to create a different karma config file that excludes the files I don't want but it does not work.

### Versions
```
Angular CLI: 1.7.3
Node: 8.4.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by sandangel** [comment]
have you try exclude from tsconfig.spec.json?

**Comment by sandangel** [comment]
then just create tsconfig.func.spec.json and declare 1 more app in .angular.json

**Comment by YoannBureau** [comment]
@sandangel thank you for your suggestion and sorry for the long time to answer.

I tried to create another app that is an exact copy of my first one, expect that I reference another testTsConfig file:
`"testTsconfig": "tsconfig.func-spec.json",`

Then in this tsconfig file I change the include property from:
`  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]`
to:
`  "include": [
    "**/*.func.spec.ts",
    "**/*.d.ts"
  ]`

That should theoretically work, but unfortunately the module bundler expects .spec.ts on every angular cli generated file (component, service, etc). I got this kind of error:
> Uncaught Error: Module build failed: Error: C:\\(...)\\src\\app\\app.component.spec.ts is missing from the TypeScript compilation.

Any other suggestion?

**Comment by sandangel** [comment]
have you tried to add exclude **/*.spec.ts to tsconfig.func-spec.json?

**Comment by YoannBureau** [comment]
Yes, but same error: components, services and so on are still found and the ng test command tries to build the bundle with the spec files.

**Comment by sandangel** [comment]
may be you should try include all func test in a specific folder
and use tsconfig path map for short import.

**Comment by YoannBureau** [comment]
Tried to do that. Unfortunately it's still the same : Because I need to build my components and so on, the build error appears as well.

**Comment by YoannBureau** [comment]
Anyone has an idea? I've tested so many workarounds, but none of them worked.

**Comment by mgechev** [comment]
For support requests it'll be best to use StackOverflow or gitter. Although we see value in introducing separate setups for these different types of tests, I'd still recommend to explore ngx-build-plus or alternative way to extend the build. Let us keep this outside of the CLI.
