### ISSUE TITLE
ng server module _baseIteratee

### ISSUE THREAD

**Issue by MrDziobak** [angular/angular-cli#1041]
$ ng serve
```
module.js:341
    throw err;
    ^

Error: Cannot find module './_baseIteratee'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (G:\!!!PROJECTS!!!\angular2\example\node_modules\angular-cli\node_modules\lodash\_createFind.js:1:82)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by mgpeng** [comment]
I have same problem, search for no solution found, MrDzlobak, have you fixed it ?

**Comment by filipesilva** [comment]
Hm, weird error. Can you tell me your node version, npm version and angular-cli version?

**Comment by mgpeng** [comment]
I list all global below with some errors 
Mac:material2-backup-2 apple$ npm ls -g --depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.6
├── npm@3.9.3
└── update@0.4.2

npm ERR! extraneous: assertion-error@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/assertion-error
npm ERR! extraneous: deep-eql@0.1.3 /usr/local/lib/node_modules/angular-cli/node_modules/deep-eql
npm ERR! extraneous: doctrine@1.2.2 /usr/local/lib/node_modules/angular-cli/node_modules/doctrine
npm ERR! extraneous: escope@3.6.0 /usr/local/lib/node_modules/angular-cli/node_modules/escope
npm ERR! extraneous: espree@3.1.4 /usr/local/lib/node_modules/angular-cli/node_modules/espree
npm ERR! extraneous: file-entry-cache@1.2.4 /usr/local/lib/node_modules/angular-cli/node_modules/file-entry-cache
npm ERR! extraneous: formatio@1.1.1 /usr/local/lib/node_modules/angular-cli/node_modules/formatio
npm ERR! extraneous: growl@1.9.2 /usr/local/lib/node_modules/angular-cli/node_modules/growl
npm ERR! extraneous: ignore@3.1.2 /usr/local/lib/node_modules/angular-cli/node_modules/ignore
npm ERR! extraneous: is-resolvable@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/is-resolvable
npm ERR! extraneous: jade@0.26.3 /usr/local/lib/node_modules/angular-cli/node_modules/jade
npm ERR! extraneous: lolex@1.3.2 /usr/local/lib/node_modules/angular-cli/node_modules/lolex
npm ERR! extraneous: optionator@0.8.1 /usr/local/lib/node_modules/angular-cli/node_modules/optionator
npm ERR! extraneous: pluralize@1.2.1 /usr/local/lib/node_modules/angular-cli/node_modules/pluralize
npm ERR! extraneous: progress@1.1.8 /usr/local/lib/node_modules/angular-cli/node_modules/progress
npm ERR! extraneous: require-uncached@1.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/require-uncached
npm ERR! extraneous: table@3.7.8 /usr/local/lib/node_modules/angular-cli/node_modules/table
npm ERR! extraneous: text-table@0.2.0 /usr/local/lib/node_modules/angular-cli/node_modules/text-table
npm ERR! extraneous: to-iso-string@0.0.2 /usr/local/lib/node_modules/angular-cli/node_modules/to-iso-string
npm ERR! extraneous: type-detect@1.0.0 /usr/local/lib/node_modules/angular-cli/node_modules/type-detect
npm ERR! extraneous: util@0.10.3 /usr/local/lib/node_modules/angular-cli/node_modules/util
npm ERR! extraneous: lodash._setcache@4.1.1 /usr/local/lib/node_modules/npm/node_modules/lodash._baseuniq/node_modules/lodash._setcache
npm ERR! extraneous: lodash._setcache@4.1.1 /usr/local/lib/node_modules/npm/node_modules/lodash.without/node_modules/lodash._basedifference/node_modules/lodash._setcache
npm ERR! invalid: inquirer2@0.1.1 /usr/local/lib/node_modules/update/node_modules/question-cache/node_modules/inquirer2

**Comment by mgpeng** [comment]
node v6.2.1

**Comment by mgpeng** [comment]
after some searching , I used  "npm install ora" in local folder, solved this problem.

**Comment by samirthebti** [comment]
`npm install ora ` Resolve the problem. thanks @mgpeng

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/1250, should be in the next release.
