### ISSUE TITLE
all parameter are passed as a strings, when using external schematics collection

### ISSUE THREAD

**Issue by maciejtreder** [angular/angular-cli#10419]
### Versions
```
Angular CLI: 6.0.0-rc.5
Node: 8.11.1
OS: darwin x64
```

### Repro steps

* Create schematics with ie boolean parameter:

schema.json
```
{
  "$schema": "http://json-schema.org/schema",
  "id": "AngularUniversalPWANgNew",
  "title": "Angular Ng New Options Schema",
  "type": "object",
  "properties": {
    "param": {
      "description": "custom param",
      "type": "boolean",
      "default": false
    }
  }
}
```
schema.d.ts
```
export interface Schema {
    param: boolean;
}
```
index.ts:
```
export default function (options: Schema): Rule {
    console.log(options);
    return tree => tree;
}
```

### Observed behavior
```
ng new --collection customSchematics myApp --param false

{ param: 'false' }
```

### Desired behavior

Parameters should be passed in same type as described in `schema.d.ts` and `schema.json` , so output should be:

```
ng new --collection customSchematics myApp --param false

{ param: false }
```

### Mention any other details that might be useful (optional)

Default values described in `schema.json` are mapped properly.

You can reproduce this issue with my custome schematics (parameter/property `firebug`):
https://github.com/maciejtreder/angular-universal-pwa/tree/firebug

**Comment by sulco** [comment]
@maciejtreder I was experiencing this issue on `"@angular-devkit/core": "^0.7.1"` - I've just updated to `0.7.3` and it doesn't seem to appear anymore.

**Comment by mgechev** [comment]
@maciejtreder please open a new issue of this is still reproducible with the latest CLI, thanks!
