### ISSUE TITLE
documentation info angular cli v6 support nodejs 8.9.x+

### ISSUE THREAD

**Issue by djleonskennedy** [angular/angular-cli#10425]
### Versions
6.0.0
```

### Repro steps
N/A


### Observed behavior
N/A

### Desired behavior
N/A


### Mention any other details that might be useful (optional)
Please add minimum nodejs version in repo description

**Comment by tiaguinho** [comment]
@mgechev I think this is already in the readme of the repository. https://github.com/angular/angular-cli#installation
There is any other place to add the information?

**Comment by mgechev** [comment]
@tiaguinho thanks for pointing this out. I think this is enough.
