### ISSUE TITLE
Cannot output tslint report formats in batch mode.

### ISSUE THREAD

**Issue by krotscheck** [angular/angular-cli#10422]
### Versions
```
Angular CLI: 6.0.0-rc.5
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.5.7
@angular-devkit/build-angular      0.5.7
@angular-devkit/build-ng-packagr   0.5.7
@angular-devkit/build-optimizer    0.5.7
@angular-devkit/core               0.5.7
@angular-devkit/schematics         0.5.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0-rc.5
@schematics/angular                0.5.7
@schematics/update                 0.5.7
rxjs                               6.0.0-uncanny-rc.7
typescript                         2.7.2
webpack                            4.5.0
```

### Repro steps
Begin with an angular repository with more than one project (two libraries, for instance). Then, attempt to use tslint's `--format checkstyle --out <outfile>` parameters to output the report to a machine readable format (for jenkins). Documentation for their CLI is here: https://palantir.github.io/tslint/usage/cli/

I have attempted the following:
```
> ng lint --format checkstyle -o ./checkstyle.xml
Architect commands with multiple targets cannot specify overrides....
```
```
> ng lint projectname --format checkstyle --out ./checkstyle.xml
Unknown option: '--out'
```
```
# Added format to angular.json >> lint.options.format and lint.options.out
# Format works, adding --out results in 
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(out).
```
```
> ng lint projectname --format checkstyle > ./checkstyle.xml
# Works
```

### Observed behavior
See above.

### Desired behavior
It should be possible for the `ng lint` command to output all of tslint's report formats, in batch mode.

### Mention any other details that might be useful (optional)
We're using Jenkins as CI, and the checkstyle reporter to pull in all the generated checkstyle files.

**Comment by krotscheck** [comment]
Current workaround for unix-based systems, on the basic folder structure (using `projects` as the directory).

```
find projects -mindepth 1 -maxdepth 1 -type d | cut -c 10- | xargs -I % sh -c "yarn --silent lint % --format checkstyle --force > projects/%/checkstyle.xml"
```

**Comment by samherrmann** [comment]
@krotscheck, in the new `angular.json` under the `projects` field you will see the following:

    "lint": {
        "builder": "@angular-devkit/build-angular:tslint",
            "options": {
               ...
             }
         }
    }

You should be able to add your `format` option in there now. See documentation [here](https://github.com/angular/angular-cli/wiki/angular-workspace). I am not sure about the `out` option though since it's not defined in the options [schema](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L1519-L1594).

**Comment by mgechev** [comment]
@samherrmann thanks for sharing the suggestion!
