### ISSUE TITLE
Using external typescript definition file giving "TypeError: Cannot read property 'text' of undefined" on alternate ng serve --aot runs

### ISSUE THREAD

**Issue by aks1994** [angular/angular-cli#10420]
### Versions
```
"@angular/cli": "1.7.4"
```

### Repro steps
* Install external typescript definition file: `"@types/big.js": "^4.0.4"` using `npm install --save @types/big.js`
* Run `ng serve --aot` (Works fine without aot)

### Observed behavior
First compile works fine, but when I make a change and save it, it gives this error
`Error: "TypeError: Cannot read property 'text' of undefined"`

If I again make a change and save, it will compile again. So basically on alternate saves, it gives this error.

If I remove the `@types/big.js` package, it works fine.

### Desired behavior

Should not inconsistently give the error. I've read some other related posts and seems to be a bug.

**Comment by mgechev** [comment]
@aks1994 please open a new issue if this is still reproducible with the latest CLI, thanks!
