### ISSUE TITLE
Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by antoinecomp** [angular/angular-cli#10435]
I am learning how to configure an Angular application from the lecture and following the instructions given [here](https://www.coursera.org/learn/angular/supplement/uokSs/exercise-instructions-configuring-your-angular-application). Yet I have the issue mentioned in the title when trying to launch the server.

### Versions
```
Output from: `ng --version` :

- Angular CLI: 1.7.4
- Node: 9.2.1
- OS: linux x64
- Angular: 5.2.10
- ... animations, common, compiler, compiler-cli, core, forms
- ... http, language-service, platform-browser
- ... platform-browser-dynamic, router
- 
- @angular/cdk: 5.2.5
- @angular/cli: 1.7.4
- @angular/flex-layout: 2.0.0-rc.1
- @angular/material: 5.2.5
- @angular-devkit/build-optimizer: 0.3.2
- @angular-devkit/core: 0.3.2
- @angular-devkit/schematics: 0.3.2
- @ngtools/json-schema: 1.2.0
- @ngtools/webpack: 1.10.2
- @schematics/angular: 0.3.2
- @schematics/package-update: 0.3.2
- typescript: 2.4.2
- webpack: 3.11.0

I'm using Linux 16.04
```

### Repro steps

You can reproduce the issue either following the instruction given in the link above or clone [my own repo](https://bitbucket.org/AntoineCompagnie/confusion/src)

### Observed behavior

When trying to launch the server with `ng serve --open` I got the following error message :

```
mike@mike-thinks:~/Documents/Coursera/Angular/conFusion$ ng serve --open
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 11% building modules 11/14 modules 3 active ...usion/node_modules/webpack/hot/log.jswebpack: wait until bundle finished: /
Date: 2018-04-23T14:24:16.442Z                                                       
Hash: ce4fd82122a4d224b89c
Time: 13126ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 42.2 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

ERROR in AppComponent cannot be used as an entry component.

webpack: Failed to compile.
```

I don't perfectly get neither what AppComponent or what raised this error. Before having this error I was struggling with this error message :

```
ng serve --open
Your global Angular CLI version (1.7.4) is greater than your local
version (1.5.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
module.js:544
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/mike/Documents/Coursera/Angular/conFusion/node_modules/@angular-devkit/schematics/src/tree/virtual.js:10:16)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

But I think I dealt with it with `sudo npm install -g @angular-devkit/core`. I used sudo because otherwise I had an error : `Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
`

### Desired behavior

I would like to see the server launch itself properly when launching this after configuring my Angular Application, only that :)

**Comment by jhalaa** [comment]
Just doing an `npm install @angular-devkit/core` fixed the issue for me.  I was wondering if this should be added to the list of dependencies?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
