### ISSUE TITLE
ng g component newcomp

### ISSUE THREAD

**Issue by afrinnusrat** [angular/angular-cli#10432]
![image](https://user-images.githubusercontent.com/8726007/39111381-81ba46aa-46f2-11e8-96a5-15d78067275e.png)

Please suggest me the possible reason for this error and how to resolve this issue????

**Comment by UTSA123432** [comment]
Don't navigate into the src folder, from your command line you want to be /d/Afrin/Project/tripDongle-Web.  If you want to create a new component in the src file use, ng g c src\'name of your component'

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
