### ISSUE TITLE
Doesn't support my username 

### ISSUE THREAD

**Issue by jgo4th** [angular/angular-cli#1043]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MacOS Yosemite

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.5
node: 4.3.1
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
"ng init" returns "We currently do not support a name of `josh.goforth`."

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
This is just my user account on my mac. Don't understand why a simple user name could break it.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by aciccarello** [comment]
Are you trying to create an angular application with a name with a period in it?

**Comment by jgo4th** [comment]
Created a new git repository, cloned into a folder called MasterDataClientTracking and cd inside and try to run 'ng init'. And I get the error 

This name is my user profile name on my terminal shell

**Comment by aciccarello** [comment]
Odd. Tried looking at ember-cli to see if it was throwing this but I don't know why `packageName` would be resolved as the user name.

## [Search results](https://github.com/ember-cli/ember-cli/search?utf8=%E2%9C%93&q=We+currently+do+not+support+a+name+of)
- [init command](https://github.com/ember-cli/ember-cli/blob/87154e7975c6be13375bb7fed977a9f63ddccb19/lib/commands/init.js#L98)
- [new command](https://github.com/ember-cli/ember-cli/blob/8c35073b0a1a207c0a2e5badd76dde844415c0a4/lib/commands/new.js#L60)

**Comment by filipesilva** [comment]
Does `ng new` give you the same problem?

**Comment by filipesilva** [comment]
Possibly related: https://github.com/angular/angular-cli/issues/1079

**Comment by osnoser1** [comment]
Command: init.
OS: Windows 10.
Same issue with 1.0.0-beta.15.
Folder name in the format 'a.b'.
I created a symbolic link in the form 'a-z' and it worked.

**Comment by filipesilva** [comment]
Ah I see what's happening. You're running `ng init` on your user folder. We do not support project names with a dot, no.

Instead do `ng new project-name` with dash separators.
