### ISSUE TITLE
Assets library not serving

### ISSUE THREAD

**Issue by PeterDavidCarter** [angular/angular-cli#10431]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Attempting to reference an image (logo.svg) from within the assets folder using the src assets/images/logo.svg results in the following error

`logo.svg:1 GET http://localhost:4200/assets/images/logo.svg 404 (Not Found)`

## Expected behavior

I expected the logo to serve from the assets directory

## Minimal reproduction of the problem with instructions

Reproduce exact file structure on my system and run the correctly setup Angular project from the same folder I was running it from. It currently appears there is either an issue with Angular being unable to consume some non-standard file-paths -- a problem I ran into before where moving from a directory containing the %20 character in the name to an otherwise identical folder without these characters fixed a similar issue. Hence the way Angular CLI handles special character may be one possible cause of the issue. Another would be Linux permissions which were causing issues before but the reports on this given by Git were accurate and allowed debugging steps to resolve the issues. If this is the root of the issue I would suggest a lack of appropriate error handling is at fault here. Either way if I am provided with an error reporting tool that enables me to send the correct data on the difference between the two file paths and associated environments I would be able to send you the correct information to assist you in improving your product by removing this bug.

## What is the motivation / use case for changing the behavior?

That users do not receive errors that do not relate to any debug pathway that would be obvious to an industry professional with substantial Angular experience. 

## Environment

Windows Linux subsystem with most current version of Ubuntu downloadable from the Windows Store at time of writing.

<pre><code>
Angular version: 5.2.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

Moving the complete folder to the Windows root directory from the Linux subsystem fixed the issue with no changes to the code. Hence this is not an issue with my code or with the cli .json file paths.

**Comment by mgechev** [comment]
Are you still able to reproduce this issue with the latest version?

**Comment by mgechev** [comment]
Closing it due to inactivity. If the problem is still reproducible with the latest CLI, please open a new issue following the template and sharing a minimal demo where we can reproduce it. Thank you! :)
