### ISSUE TITLE
how build angular 2 with separated reusable output libraries?

### ISSUE THREAD

**Issue by molikh** [angular/angular-cli#10448]
[X] Question.
I have 4 angular apps that use same libraries ( like angular , angular-material ... ).

I'm trying to get libraries in on file and my codes in another file so then I can use same library for all 4 apps(client don't have to load same library in 4 different app).

> detail

I want to share a single js file for all my app that client uses for which I want to use same URL for js file in all Apps so browser will automatically use cached js file instead of loading file each time, that's why I'm trying to have build structure like this :

lib.js include all libraries like angular , angular-material and ... ( I will use this one as shared library js file in all apps )
my.js it's include code written by myself for each app ( in this case I will have 4 different my.js file for different apps)

Is this possible with angluar-cli?

**Comment by alan-agius4** [comment]
Hi @molikh, this is outside of the scope of the CLI and the above approach will hinder smaller bundle sizes as tree-shaking and code splitting will not work properly.
