### ISSUE TITLE
"ng update @angular/cli --migrate-only --from=1.7.1" produces an unhandled error event

### ISSUE THREAD

**Issue by lehtiniemi** [angular/angular-cli#10442]
### Versions
```
Angular CLI: 6.0.0-rc.2
Node: 9.4.0
OS: win32 x64
Angular: 5.2.8
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.2.5
@angular/cli: 6.0.0-rc.2
@angular/flex-layout: 5.0.0-beta.14-17a70ee
@angular/material: 5.2.5
@angular/platform-server: 5.2.10
@angular-devkit/architect: 0.5.4
@angular-devkit/build-angular: 0.5.7
@angular-devkit/build-optimizer: 0.4.9
@angular-devkit/core: 0.5.7
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 6.0.0-rc.5
@schematics/update: 0.5.4
typescript: 2.6.2
webpack: 4.5.0
```

### Repro steps
* I installed the latest version of angular cli into my existing project (ng cli 1.7.1) by using the official update instructions in the github page (but instead of @latest, I used @6.0.0-rc.2
* after completing the installation, I tried ng serve
* I got the following instructions:
An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
* I ran the first command and got an error message

### Observed behavior

I got this error after running the first command:

```PS C:\Users\Juhana Lehtiniemi\Koodaus\nordic-sounds> ng update @angular/cli --migrate-only --from=1.7.1
            Updating karma configuration
            Updating configuration
            Removing old config file (.angular-cli.json)
            Writing config file (angular.json)
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

### Desired behavior
There should be no error and the migration should run smoothly.

### Mention any other details that might be useful (optional)
After trying the migration again, I got an error saying there's no configuration file. I tried ng serve again and this time it started the compilation. However, then I got another error:
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed:
@import 'common';
^
      File to import not found or unreadable: common.
      in C:\Users\Juhana Lehtiniemi\Koodaus\nordic-sounds\src\styles.scss (line 5, column 1)
ERROR in No NgModule metadata found for 'AppModule'.
```

I don't know if this is because of unfinished migration or some other error, but this error didn't exist when running the project with 1.7.1 and obviously there should be no errors when the project worked before. The error seems to be related to the fact that the stylePreprocessor tag isn't in the new configuration file anymore. This tag contained the paths of the stylesheets that should be "global". This tag is gone in the new config so that's probably why the stylesheets aren't found. Should they be there or was this because unfinished conversion?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
