### ISSUE TITLE
ng new fails sporadic with useless error message

### ISSUE THREAD

**Issue by dealloc** [angular/angular-cli#10449]
### Versions
![version](https://user-images.githubusercontent.com/2164354/39171748-ff4f1c28-479f-11e8-91ca-ee6d1ff1555a.png)

### Repro steps

* run `ng new foobar`

### Observed behavior
![snipimage](https://user-images.githubusercontent.com/2164354/39171771-125d30c0-47a0-11e8-98d2-1e8445cb0dcf.JPG)

A colleague of mine started observing Angular CLI crashing when creating a new project (hence screenshots instead of console output, my apologies) without providing any additional information (the custom schematic is to attempt dumping options etc).

I myself have experienced the same problem sporadic but it went away after a while without any obvious reason, another colleague of mine did not experience the problem at all, his version info is listed below
![version-colleague](https://user-images.githubusercontent.com/2164354/39171934-84a9cf4e-47a0-11e8-9b41-6bc58edb0f6a.png)

### Desired behavior
The CLI should either provide clear information as to why it failed (and perhaps allow me to extract more debugging information) or work.

### Mention any other details that might be useful (optional)
Looking through the schematics source code a quick search reveals that the only place this specific message is thrown seems to be in [utility/config.ts](https://github.com/angular/devkit/blob/master/packages/schematics/angular/utility/config.ts#L457), not sure if that's relevant

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
