### ISSUE TITLE
Right click on chart.

### ISSUE THREAD

**Issue by GokulGawali** [angular/angular-cli#10446]
I am not able to handle right click on ng2-charts and doesn't get chart data on right click using contextmenu.

Using: 
angular : 4.4.4
ng2-charts : 1.6.0

Please help me. how to handle right click on chart for get click point data.

Thanks.

**Comment by RicardoVaranda** [comment]
Hi @GokulGawali ,

It would be better to post this issue on the ng2-charts repo: https://github.com/valor-software/ng2-charts

This repo is for angular-cli is not associated with your problem.

**Comment by GokulGawali** [comment]
Thanks..
