### ISSUE TITLE
ng build --prod bundle is much bigger in size than in ng serve --prod

### ISSUE THREAD

**Issue by vugar005** [angular/angular-cli#10477]
**Versions**

![angular-cli](https://user-images.githubusercontent.com/28726265/39350446-45dbbd10-4a0f-11e8-82a5-a75fc704a81b.JPG)

**Repro steps**
When running project with 
1. `ng serve --prod --aot=true`
the main.bundle size  is 1.1 mb

![7pnei](https://user-images.githubusercontent.com/28726265/39325938-60a61dec-4948-11e8-94d3-c689e205b730.jpg)

2. `ng build --prod --aot=true`
the main.bundle size is  5.3 mb. 

![2zoe8](https://user-images.githubusercontent.com/28726265/39325954-6ad7cc3e-4948-11e8-888f-b4b0fb4b5d31.jpg)

**Observed behavior** 
ng build --prod main size is almost 5 times bigger than ng serve --prod.

**Desired behavior**
`ng serve --prod --aot=true` and `ng build --prod --aot=true` should produce same results.

Thanks

**Comment by kakarlus** [comment]
i have the same problem :smile:

**Comment by alan-agius4** [comment]
Hi, this is expected as `ng serve` uses the live reload client which is relatively big.

Most likely, you'd need to disable live reload https://angular.io/cli/serve

**Comment by jboeijenga** [comment]
@alan-agius4 This is not really an answer to the question. Question is why ng serve bundle size are smaller than build bundle sizes. Not the opposite. If the reload client is relatively big it makes me even wonder more why the difference in size is so big.
