### ISSUE TITLE
Location of generated coverage reports

### ISSUE THREAD

**Issue by victormejia** [angular/angular-cli#10479]
### Versions
```
Angular CLI: 6.0.0-rc.6
Node: 8.11.1
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.5.8
@angular-devkit/core         0.5.8
@angular-devkit/schematics   0.5.8
@ngtools/json-schema         1.1.0
@schematics/angular          0.5.8
@schematics/update           0.5.8
rxjs                         6.0.0
typescript                   2.7.2
```

### Repro steps
* `ng new sample-app`
* `ng test --code-coverage`

### Observed behavior
Coverage reports get generated under `src/` folder.

### Desired behavior
Usually this was generated at the root. Is this by design?

**Comment by victormejia** [comment]
A side effect of running this:

```
ng test --code-coverage --watch`
```

The tests continually run in a loop since coverage reports get generated under `src/` which then triggers the watch, which triggers the suite to run again.

**Comment by MarcScheib** [comment]
I had the same problem (+ side effect). Quick fix:
- Open `src/karma.conf.js`
- Change `dir: require('path').join(__dirname, 'coverage'),` to `dir: require('path').join(__dirname, '../coverage'),`

**Comment by victormejia** [comment]
This isn't an issue anymore with the latest RC 10. Closing.
