### ISSUE TITLE
ng build --prod --watch  (void 0) is not a function

### ISSUE THREAD

**Issue by 1456118242** [angular/angular-cli#10471]
I have this problem too. I have the demo https://github.com/1456118242/angular-watch-demo

![w](https://user-images.githubusercontent.com/18241022/39289891-61e824a8-4960-11e8-9208-6276346e089a.png)

### Versions
```
"@angular/common": "^5.2.0",
"@angular/cli": "~1.7.2",
```

### Repro steps

* Step 1 run  ng build --watch --prod 
* Step 2 Modify the compent file
* Step 3 refresh page
* Step 4 Modify the compent file
* Step 5 refresh page

### Observed behavior
```
![3](https://user-images.githubusercontent.com/18241022/39288390-5a0614da-495a-11e8-919b-4e73e5bd9888.png)
![2](https://user-images.githubusercontent.com/18241022/39288426-7cabfd9c-495a-11e8-9afa-d95d30454c6d.png)

```

**Comment by evanlalo** [comment]
Same problem.

**Comment by alan-agius4** [comment]
Hi, Thanks for reporting this issue. I tried to replicate this using the current latest version of the CLI (7.3.0) and I was unable.

Please update to the most recent Angular CLI version. If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by MiraYuan** [comment]
my project work well when ng s --prod, but cannot work well and error happen"(void 0) is not a function" when it is used in a websphere project...
