### ISSUE TITLE
ng build --prod --aot fail

### ISSUE THREAD

**Issue by ssinghal1989** [angular/angular-cli#10481]
Hi Team,

I am getting below issue while running "ng build --prod --aot" 

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/Users/B0096396/sonu/LMS/LMS_FrontEnd/src'

PFB version details

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.8
Node: 8.9.4
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0

**Comment by alexzuza** [comment]
Hello, could you provide minimal reproduction so that we can investigate it?

**Comment by orizens** [comment]
hi @alexzuza 
I noticed that with latest ng-cli (1.7.4) as well in my project. 
you can fork my project https://github.com/orizens/echoes-player and run `ng build --prod`

**Comment by alexzuza** [comment]
Hi, @orizens. I have successfully built your project (master branch).

**Comment by orizens** [comment]
@alexzuza 
build process is fine, however, if you try to run `npm run start:prod`(that - assuming you run ng server --prod, no need to pass in youtube keys) - the resulting localhost:4200 appears to be broken.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
