### ISSUE TITLE
Feature request: Support service worker in development mode

### ISSUE THREAD

**Issue by ronzeidman** [angular/angular-cli#10483]
I have a pretty complex logic in creating push notifications with multiple users + multiple sub apps + fallback logic and debugging production mode is hard. If support service workers under development mode was under a flag I'd have a much easier time debugging.
Thanks!

**Comment by oberoivarun** [comment]
Could the angular team just allow service workers in `ng serve --prod` ??

**Comment by dgp1130** [comment]
Duplicate of #16883
