### ISSUE TITLE
6.0.0-rc.7 update/generate commands fail if angular.json is in home folder

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#10508]
If there is a `angular.json` or `.angular.json` file in the home folder and `6.0.0-rc.7` is used, `ng update` and `ng generate` commands will fail.

A workaround for now is to delete the `.angular.json`/`angular.json` in the home folder.

**Comment by hansl** [comment]
Dupe of #10513 which is going to be fixed soon.
