### ISSUE TITLE
8 digits border color property disappear when `ng build --prod`

### ISSUE THREAD

**Issue by ryoya-fujimoto** [angular/angular-cli#10510]
### Versions
```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 8.11.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

* `ng new test-app`
* Set css border property with 8 digit color, like `border: solid 5px #00000050;`.
* `ng build --prod`
* `border: solid 5px;` generated

### Mention any other details that might be useful (optional)
Tried pattern is here.
* `background-color: #00000050;` and `ng build --prod` => OK
* `border-color: #00000050;` and `ng build --prod` => OK
* `border: solid 5px #00000050;` and `ng build` => OK
* `border: solid 5px #00000050;` and `ng build --prod` => NG

**Comment by orizens** [comment]
my project is also getting css with errors after `prod` compilation with 1.7.4 (http://github.com/orizens/echoes-player)

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
