### ISSUE TITLE
6.0.0-rc.7 Regression: Cannot find package.json when running ng update

### ISSUE THREAD

**Issue by andrewseguin** [angular/angular-cli#10514]
I've got a project I want to update to Angular v6. First step was to move update the CLI from `1.7.4` to `6.0.0-rc.7`. Found that didn't work.

Note that this error does not come up if you update to the previous `6.0.0-rc.6` version.

### Versions

Started with this before changing my `package.json` to `6.0.0-rc.7`
```
Angular CLI: 1.7.4
Node: 8.9.4
OS: darwin x64
Angular: 5.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cdk: 5.2.4
@angular/cli: 1.7.4
@angular/material: 5.2.4
@angular/tsc-wrapped: 4.4.6
@ngtools/webpack: error
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: error
```

### Repro steps

* Step 1: Clone repo for test case https://github.com/andrewseguin/beautiful-day
* Step 2: Update CLI version from `^1.7.4` to `6.0.0-rc.7`
* Step 3: Install packages: `npm i`
* Step 3: Run `ng update @angular/cli`

### Observed behavior

An error message is printed telling me that it cannot find a `package.json`.

```
Could not find a package.json. Are you in a Node project?
```

### Desired behavior

CLI successfully updates itself.

### Mention any other details that might be useful (optional)

Do you intend to show a message when users update `@angular/cli` to v6 using yarn? I noticed that with `npm i` I see the following message:

```
====================================================================
The Angular CLI configuration format has been changed, and your existing configuration can
be updated automatically by running the following command:

  ng update @angular/cli
====================================================================
```

But if I do the update using `yarn`, no message is provided that lets me know to do anything.

**Comment by lehtiniemi** [comment]
I get this too. I also came from 1.7.4. Ran the update commands given in the official update guide in GitHub. When I ran ng update @angular/cli, I got the same message. This didn't appear when I tried with rc-2 some days ago.

**Comment by lehtiniemi** [comment]
I was able to migrate with rc5 by running the recommended ng update @angular/cli --migrate-only --from=1

And then update to rc7. I don't know if this command also works in rc7, but I had to downgrade to rc5 to get the suggestion for this command.

**Comment by gerhardboer** [comment]
I'm having the same problem, and i've traced it down to a line in `schematics-command.js:73`, where `this.project.root` is set to my User folder, instead of the project folder.
If I set the property to an absolute URL of the location of the project, the command goes through as expected.
I'm not sure (yet) how the `project.root` is set, but maybe this information helps

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions and repro you provided.

Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by peternixey** [comment]
To add a little colour to this, I had a similar problem when trying to update `angular/cli` from outside of a project directory. 

The installation was failing because it couldn't find `package.json`. There wasn't a package.json because I wasn't in a project. 

I ran:

````
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli
````

and all was well again.
