### ISSUE TITLE
[6.0.0-rc.7] ng new fail

### ISSUE THREAD

**Issue by mantyz** [angular/angular-cli#10513]
### Versions
```
Angular CLI: 6.0.0-rc.7
Node: 8.11.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.5.10
@angular-devkit/core         0.5.10
@angular-devkit/schematics   0.5.10
@ngtools/json-schema         1.1.0
@schematics/angular          0.5.10
@schematics/update           0.5.10
rxjs                         6.0.0
typescript                   2.7.2
```

### Repro steps

* `ng new project-name`

### Observed behavior
```bash
pc@mantyz:~/dev/node$ ng new project-name
This command can not be run inside of a CLI project.
```

### Desired behavior
Angular-cli must create a project.

### Mention any other details that might be useful (optional)
`ng new` work with cli v6.0.0-rc.6
The project is successfully created relative to the "/"(root) directory, but is not created relative to the "/home/username" and subdir.

**Comment by mantyz** [comment]
Hmm... The project is successfully created relative to the "`/`"(root) directory, but is not created relative to the "`/home/username`".

**Comment by tobi-or-not-tobi** [comment]
I have the same experience with 6.0.0-rc.7, i'm not able to create a new app.

**Comment by mantyz** [comment]
Changes 
```javascript
const root = path.parse(from).root; 
``` 
to 
```javascript
const root = path.parse(from).dir; 
``` 
work for me
https://github.com/angular/angular-cli/blob/c7088901b70d850cc818d002daa30dd100d57c22/packages/%40angular/cli/utilities/find-up.ts#L8

**Comment by dimitrijuchtmans** [comment]
I experienced exactly the same thing, untill I realised that i had a .angular-cli.json file in my folder or parent folder structure somewhere.

**Comment by mantyz** [comment]
@dimitrijuchtmans, thank you. Yea, the directory "/ home / username" contained an angular cli file.

**Comment by rokerkony** [comment]
I have the same problem after migration from `rc.6`. I run the command from a different folder (ng is not installed locally)

My flow:
1. `cd /www` // folder with all cloned repositories we have
2. `./other-updated-project/node_modules/.bin/ng new --style=scss new-project-name`
3. I get `This command can not be run inside of a CLI project.`

I have no angular-cli project at `/www` path only in subdirectories... 

it was working in `rc.6`

**Comment by rokerkony** [comment]
It seems to be a bit related to alredy fixed issue: https://github.com/angular/angular-cli/issues/10163

**Comment by amcdnl** [comment]
On RC9, I can confirm this is still happening. Had to remove the `.angular.json` file in my home directory to get it to work.

**Comment by mehocode** [comment]
I don't have .angular.json file in home folder but this is still happening. I also tried to reinstall angular cli - no luck so far.
