### ISSUE TITLE
Angular CLI 1.7.4 does not support NodeJS 10

### ISSUE THREAD

**Issue by aJ5fa1JGN1FatBw6Fa0md5RrVBEk2G** [angular/angular-cli#10527]
### Versions
Node 10.0.0
NPM 6.0.0
Windows 10

### Repro steps
Install the latest NodeJS 10, the latest  NPM 6 with Angular 1.7.4

### Observed behavior
When trying to run ng serve on an angular 1.7.4 project it fails because
Angular 1.7.4 uses node-sass 4.8.3
Node-sass 4.8.3 only supports up to NodeJS 9 
See:
https://github.com/sass/node-sass/releases/tag/v4.8.3

### Desired behavior
Update Angular 1.7.4 to support NodeJS by upgrading node-sass to v4.9.0
Node-sass 4.9.0 supports up to NodeJS 10.
See:
https://github.com/sass/node-sass/releases/tag/v4.9.0

**Comment by akaustav** [comment]
Found a similar problem when I was following the checklist of items generated by the [Angular Update Tool](https://update.angular.io/) for upgrading from Angular 5.2 to Angular 6.0. This problem occurred for me when trying to use the `ng update @angular/cli` command.

### My Versions
Node 10.0.0
NPM 5.6.0 (I didn't realize there is a 6.0.0 already)
Windows 10

### Temporary Workaround
1. Download and save a local copy of the correct version of node-sass binary - [win32-x64-64_binding.node](https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-64_binding.node). For example download it to the following location:
`C:\node-sass\win32-x64-64_binding.node`
1. Provide reference to the full path of the node-sass binary file in the `sass_binary_path` npm configuration parameter (in the `~/.npmrc` file):
`npm config set sass_binary_path <path to node-sass binary>`
For example,
`npm config set sass_binary_path C:\node-sass\win32-x64-64_binding.node`
1. Run the `npm install` command again to install `@angular/cli` correctly.
1. Execute `ng serve` or `npm start` and your should be past the problem.

### Explanation of the Workaround
1. The `NODE_MODULE_VERSION` of Node 10.0.0 is `64`. See their [previous releases page](https://nodejs.org/en/download/releases/) for a detailed table. More explanation at the [footer of that page](https://nodejs.org/en/download/releases/#ref-1).
1. I understood it was looking for [win32-x64-64_binding.node](https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-64_binding.node) inside the node-sass 4.8.3 folder.
1. [node-sass 4.8.3](https://github.com/sass/node-sass/releases/tag/v4.8.3) doesn't have a node-sass binary compiled with the NODE_MODULE_VERSION set to `64`. Hence, it fails downloading.
1. However, [node-sass 4.9.0](https://github.com/sass/node-sass/releases/tag/v4.9.0) has a node-sass binary compiled with the NODE_MODULE_VERSION set to `64`. Hence, that binary will do.

**Comment by SimonKomlos** [comment]
@akaustav I tried following your suggestion for the temporary work around but it caused a huge issues with my `node-sass` .. you can read more here if you want: https://github.com/sass/node-sass/issues/2397

Do you know how I can revert the config changes you suggested?

**Comment by akaustav** [comment]
Hi @SimonKomlos
Apologies, I am not in front of a computer at the moment. But if you've still not figured it out by now, perhaps you've mixed up the backslashes ( \ ) on Windows. Do you mind pasting the contents of the .npmrc file in your windows home folder here?

**Comment by SimonKomlos** [comment]
@akaustav thanks for replying. My `.npmrc` files content is 

`sass_binary_path=C:node-sasswin32-x64-64_binding.node`

It does look like it missed the `/`.. I ended up deleting my C:/node-sass folder after I reinstalled node, but I guess it's still looking for it now. Do you think I should follow your workaround again.. correctly this time, or should I reset it? I'm not sure how I would reset it though.

I appreciate you replying :)

**Comment by akaustav** [comment]
Hi @SimonKomlos, I am not very sure node-sass is necessary to be installed at the root of your project - not even as a dev dependency. It's a sub-dependency. Looks like your current `node_modules` folder might be corrupt. You probably want to start a fresh project by deleting your `node_modules` folder and perform an `npm install`. If that doesn't help, you might as well start a new project using `ng new projectx`.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
