### ISSUE TITLE
v6 Documentation?

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#10530]
It seems that the interface has completely changed in v6; is there (or will there be) documentation on how to use / migrate to the latest versions of these commands?

Specifically, `build` and `serve` have both gone from offering a pretty big set of options (many of which our existing scripts and workflow depend on) to only `--configuration` and `--prod`. If `--configuration` is the replacement for all the options that were removed, it isn't clear from the `--help` output how it's meant to be used.

Edit: Okay, I think I figured it out. Sets of flags now have to be configured in angular.json,  and `--configuration` references the name of a pre-defined configuration?

In that case, a feature request: the ability to specify a configuration inline (e.g. `ng serve --options '{"browserTarget": "cyph.ws:build:dev"}'`) (and/or just continued backwards compatibility with the 1.x flags).

**Comment by devoto13** [comment]
See https://github.com/angular/angular-cli/issues/10438 and https://github.com/angular/angular-cli/pull/10470
