### ISSUE TITLE
Support any number of environments

### ISSUE THREAD

**Issue by netmikey** [angular/angular-cli#1053]
Currently, it seems angular-cli only supports 2 environments: `dev` and `prod`. But what if the app is being used in more than those environments? 

In our case, we have at least 3 environments requiring different configuration:
* During development on developers' machines (an API mock is run on localhost)
* During an internal staging phase (a test API Backend is run on an internal staging server)
* For production (this obviously talks to the production API)

You could easily imagine any number of custom and complex project environments requiring way more than just `dev` and `prod`.

Instead of adding more and more environment configuration files into SCM, how about being able to override configuration settings at build time? Maybe through environment variables: that would make it easy to automate a fully custom configured build using docker, travis, gitlab-ci etc. (just thinking out loud here...)

**Comment by vargalas** [comment]
I agree with you.
Theorethically it's supported. You can use the --environment option. 
[A good tutorial is here](http://tattoocoder.com/angular-cli-using-the-environment-option/) 

Although currently it doesn't seem to work for me, only works correctly with --environment=dev or --environment=prod parameters. And the same with their shortcuts.

angular-cli: 1.0.0-beta.5
node: 6.2.1
os: win32 x64

**Comment by netmikey** [comment]
@vargalas It seems to be hardcoded to only those 2 environments right now, see here for instance: https://github.com/angular/angular-cli/blob/d81e4b16387dd3fae05fcbf20d7ed6948875a39c/lib/broccoli/environment.js#L11

**Comment by netmikey** [comment]
Probably a duplicate of #899
