### ISSUE TITLE
stylePreprocessorOptions loads node_modules instead of scss

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#10535]
Using `@import 'file'` imports from node_modules when the file is named the same way any node module is named.

**Angular.json**

```
"stylePreprocessorOptions": {
              "includePaths": [
                "src/styles"
              ]
            },
```

**Existing files**
```
src 
   - styles
          - _globals.scss
          - _rxjs.scss
```

**my-component.scss**
```
@import 'globals';
```
-> Imports node-module "globals" index.js

**my-component.scss**
```
@import 'rxjs';
```
-> Imports node-module "rxjs" index.js

**Version**
@angular/cli: 6.0.0-rc.7

**Comment by iowaz** [comment]
This also happens if file name is 'colors'

**Comment by dev-nicolaos** [comment]
I can as well. Initially broke an existing project when using the new ng update cli command, as well as with a fresh app generated with ng new (CLI version 6.0.3)

**Comment by dev-nicolaos** [comment]
Any update from the team on this?

**Comment by ethanj** [comment]
@ZbigiMan 

I got Angular 6 with Foundation 6 working with a variation of your question/answer...

Include your stylePreprocessorOptions config, then copy 

> node_modules/foundation-sites/scss/settings/_settings.scss 

into your src directory, then edit this line:

> @import 'util/util';

to be

> @import 'node_modules/foundation-sites/scss/util/util';

In your style.scss you can now do:

> @import 'settings';
@import 'foundation';
@include foundation-everything;


I still get a warning I have not worked on yet, but everything compiles.

**Comment by AlexBachmann** [comment]
Hey @ethanj. The problem of this issue is not exactly the problem @ZbigiMan describes. In fact quite the opposite. The problem is NOT that you cannot add include paths to the stylePreprocessorOptions of the CLI. You can, and it works, as you described. 

The problem is, that the loader FIRST tries to load from the node_modules directory and THEN tries to load from the included paths.

That means, if you have a module called "colors" in node_modules, or a module called "base" then these SCSS statements will trigger an error, because the compiler doesn't look in your include paths FIRST but instead tries to load the module in node_modules.

```
@import "base"
@import "colors"
```
We did not have this behavior in the old version of the CLI and this is why it's breaking existing code.

**Comment by MickL** [comment]
Also it tries to import js files, which seems not correct to me, too.

**Comment by ZbigiMan** [comment]
I also noticed that is problem with sass-loader 7. Downgrades to sass-loader 6 solves the issue, so It's not problem with @angular/cli itself but with dependency - sass-loader.

⁣Wysłano z BlueMail ​

W dniu 28.06.2018, 10:09, o 10:09, użytkownik Alexander Bachmann <notifications@github.com> napisał:

**Comment by MickL** [comment]
Guys if you have the same issue upvote the issue itself. Contributers dont see your +1 comments and dont see your upvotes on the „colors“ thingy.

**Comment by ZbigiMan** [comment]
Here is link to webpack sass-loader issue https://github.com/webpack-contrib/sass-loader/issues/556

**Comment by krismeister** [comment]
If anyone finds this in the short future, until the commits above are merged. I am on:
```
Angular CLI: 6.2.3
Angular: 6.1.9
```
Downgrading sass-loader in `package.json` fixed this issue for me.
```
  "dependencies": {
        ...
        "sass-loader": "~6.0.7",
        ...
```

**Comment by cichacz** [comment]
Yea, it looks like it's still there in sass-loader@7.1.0

**Comment by shprink** [comment]
Same here when upgrading from v6 to Angular v7.

Downgrading sass-loader to `6.0.7` worked for me.

**Comment by nyxz** [comment]
My workaround was to prefix my style files with my project name abbreviation to avoid naming collusion with libraries inside `node_modules`. So
```
src 
   - styles
          - _globals.scss
          - _rxjs.scss
```
will become
```
src 
   - styles
          - _asdf_globals.scss
          - _asdf_rxjs.scss
```

Then the import is:

```
@import 'asdf-globals';
@import 'asdf-rxjs';
```

**Comment by daverickdunn** [comment]
Slight digression: For persons trying to use this in multi-app projects, you need to use the full path to the app (project).

e.g.
```
"stylePreprocessorOptions": {
    "includePaths": [
        "projects/my_app/src/styles"
    ]
}
```

Took me a few minutes to realise this...
