### ISSUE TITLE
WebSocket Connection

### ISSUE THREAD

**Issue by rushdeep** [angular/angular-cli#10547]
I created a brand new angular cli project following steps given in the below link
https://docs.microsoft.com/en-us/aspnet/core/spa/angular?view=aspnetcore-2.1&tabs=visual-studio

Its a angular cli project that runs with in visual studio 2017, and the framework is .net core 2.0. I am behind a proxy so I had to add it to my nuget.config and node config (.npmrc)

I followed the steps in the above link and when I run the app I get the following error. There is very little information about this topic out there.

![image](https://user-images.githubusercontent.com/16278948/39447425-b45e3c22-4c8f-11e8-82f9-4b6ffbe9813b.png)

node 8.11.1
npm 5.6.0
Windows 7.

**Comment by clydin** [comment]
This appears to be an issue with a third-party integration of the CLI.  If this problem is still occurring, please consider opening an issue with the owner of the integration.
