### ISSUE TITLE
ng serve --poll

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#10559]
Was the `--poll` flag removed in v6, or is that just an error in the newly committed docs? As per https://github.com/angular/angular-cli/issues/5212 it's needed to support Docker on Windows, which is still the case as far as I'm aware.

**Comment by filipesilva** [comment]
@buu700 it's still there, but it is a build option and not a serve option. If you add it to `projects.project-name.architect.build.options.poll` it should work. I tried it on a new project modifying templates and ts files with a 10000ms poll and saw rebuilds.

**Comment by buu700** [comment]
Got it, thanks! It'd be easier to use as a command line flag since our serve script conditionally adds it based on whether the host OS is Windows, but not a blocker since copying and transforming angular.json is an option too.

**Comment by filipesilva** [comment]
You can create a configuration that contains poll, and conditionally use that:

```
"build": {
  ...
  "configurations": {
    "docker": {
      "poll": 2000
````

Then use that one on serve. WDYT? Or maybe poll should be on serve as well, as we do have some duplicated options there.

**Comment by buu700** [comment]
Awesome, thanks! So that will add `--poll` back to the `serve` command?

**Comment by filipesilva** [comment]
Yeap, it should be on the next release of `@angular-devkit/build-angular`!

**Comment by hbarve1** [comment]
poll option is still not available in @angular/cli@6.2.3 serve!

is there any other way to enable poll option?

**Comment by rogusdev** [comment]
The new option is better than the old: it takes an argument for the milliseconds time to wait between polls.  (You can see this in the commit referenced above.)  However, if you simply pass --poll it has no default so it appears as if it is not working...

```
ng serve --host 0.0.0.0 --poll 200
```
Works as expected in vagrant on win10 host

```
ng serve --host 0.0.0.0 --poll
```
Does nothing tho, so perhaps a sensible default should be added? 500 or 1000 ms?

**Comment by maroom1** [comment]
I am new to this option, when do you use this poll.. can anybody help on atleast one usecase? where it helps. 

Thank you

**Comment by clydin** [comment]
@rogusdev The next version (9.0) will default to 500ms if the poll option is provided without a value. https://github.com/angular/angular-cli/pull/15417
