### ISSUE TITLE
Portable "src" directory, free of build tooling or config

### ISSUE THREAD

**Issue by kylecordes** [angular/angular-cli#1055]
This is a feature request:

Adopt a policy that CLI keeps its hands off the src directory, in terms of any build tooling or configuration, to the greatest extent possible. It only manipulates the contents of that directory to perform things like component generation.

Rather, keep the src directory completely **portable**, where it could be copied to a project using different tooling and still work. That portability is true of the component generation function CLI performs, but it is not true of the other files CLI writes.

As I look at Beta 5, I spot these things that should change to accomplish it:
- move tsconfig.json up out of this directory; it will need to be different for different tooling, and getting it out of src would be more similar to how most other projects arrange the files.
- delete typing.d.ts; Instead reference the file created by the typings tool, and include whatever additional typing is needed to avoid this one ad hoc bit of typing.d.ts created by 'ng new'.
- move favicon over to the public directory, it makes more sense there anyway
- unfortunately I think system-config.ts has to stay, perhaps as the one on avoidable bit of tooling that must live with source code.

One obvious question to ask is: why would anyone want this? I'm a huge fan of CLI, but I still think this is a very good idea because:
- Will CLI be the best for every project? Seems unlikely.
- Will some projects need to move back and forth between different tooling? Very likely.
- Tooling comparisons are good. They are much facilitated by separating build tooling from source code.
- I believe compatibility with future really slick IDE support for Angular 2 will be much facilitated by cordoning off the debris of a particular build tool from the users essential source code.

As a minor example justifying one of the bullet points above, I currently have approximately four different sets of Angular 2 running here in various forms. Each of them has different requirements for the tsconfig file.

I actually think this item should be thought of in reverse. It should be the default position, the maximum possible isolation between build tooling files and developer project source code. From that point of view, is there a good justification to mix them?

**Comment by intellix** [comment]
I'm for this. With the latest webpack version (beta 17), we no longer have `system-config.ts`.
I'd like to have the `tsconfig.json` and `typings.d.ts` out of the src directory though but am not sure of the implications.

**Comment by hansl** [comment]
The CLI needs a link to the `src/` folder, but it's in the config. We could probably manage _most_ of configuration from the `tsconfig.json` file but we'd still need that.

Nothing is preventing you from moving the `src/` folder anywhere, as long as you update your config. Closing this as fixed, also note this is a really old issue and we fixed most of the points above.
