### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by leenMalka** [angular/angular-cli#10568]
I tried to build my project with ng build 
### but I get this error:
`95% emittingX:\NewClalWeb\base-project\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:70
                                callback.apply(null, data);
                                         ^
TypeError: Cannot read property 'apply' of undefined

    at X:\NewClalWeb\base-project\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:70:14

    at _combinedTickCallback (internal/process/next_tick.js:131:7)

    at process._tickCallback (internal/process/next_tick.js:180:9)`

I show a suggest to change angular cli version in package.json
 but it still throw this error...
I tried a few trying of version (**my version** is `@angular/cli: "1.6.8"` )
Any help?!

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
