### ISSUE TITLE
ng update @angular/cli

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular-cli#10563]
[ X ] Bug

version 6.0.0-rc.2+

### Repro steps
Migrate a previous 1.6 project that has three styles files configured

### Observed behavior
subsequent angular-cli.json files wont build

**Comment by nhhockeyplayer** [comment]
workaround

```
              "styles": [
                  {
                      "input": "src/styles.scss"
                  }
              ],
```

**Comment by filipesilva** [comment]
Heya, can you give me a repro I can follow to see that? The paths look right to me. How does it fail building?

**Comment by nhhockeyplayer** [comment]
I am closing this

sorry for distraction

I confused the output with this bug

https://github.com/angular/angular-cli/issues/9994

build system seems to be in major play... 
praying for some kind of workaround from this one https://github.com/angular/angular-cli/issues/9994
