### ISSUE TITLE
Generate code coverage

### ISSUE THREAD

**Issue by SLYJason** [angular/angular-cli#10574]
### Versions
```
Angular CLI: 1.7.3
Node: 8.11.1
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack-concat-plugin: 2.4.2
webpack-dev-server: 3.1.1
webpack: 3.11.0
```

### Repro steps

In code coverage [README.md](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/code-coverage.md), it said set the value within the configuration file `angular.json` should generate coverage report whenever run tests:
```
...
  "test": {
    "options": {
      "codeCoverage": true
    }
  }
```
What is `angular.json`? Should be `angular.cli.json`?
I added this in `angular.cli.json`, but it doesn't generate report when run unit tests.

### Observed behavior
Nothing generated.

### Desired behavior
Should generate `coverage` directory.

**Comment by hansl** [comment]
Hi @SLYJason,

The stories are meant to be published to the wiki when we release. In your case, you're looking at the documentation for 6.0.0-rc.8.

You can find the documentation for 1.7.3 here; https://github.com/angular/angular-cli/wiki/stories-code-coverage

Thanks!
