### ISSUE TITLE
Add webpack extensions, or customize the discussion to add plug-ins.

### ISSUE THREAD

**Issue by Gaosir-18** [angular/angular-cli#10593]
use @angular/cli  add webpack extensions, or customize the discussion to add plug-ins.

I read an article in the morning, though. installing an improved cli-eject， This problem can be solved, but it is not straightforward and flexible, and the operation is too complex.

I want to know if there is a way to configure, modify, or add code directly in a file to solve this problem.

For example：
I want to add a webpack-spritesmith plug-in.What should I do?

**Comment by vincentjames501** [comment]
+1 . If you're removing eject, there should be a better documented way to customize the build process. I also need to add just a single webpack plugin.

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.x+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
