### ISSUE TITLE
6rc.X --stats-json or sourceMap blocking at 95% when optimisation&buildOptimizer are set to true

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#10591]
### Versions
```
Angular CLI: 6.0.0-rc.9 
Node: 10.0.0
OS: win32 x64
Angular: 6.0.0-rc.6
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.12
@angular-devkit/build-angular     0.5.12
@angular-devkit/build-optimizer   0.5.12
@angular-devkit/core              0.5.12
@angular-devkit/schematics        0.5.12
@angular/cli                      6.0.0-rc.9
@ngtools/webpack                  6.0.0-rc.10
@schematics/angular               0.5.12
@schematics/update                0.5.12
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
Build with this configuration : 
```
 "optimization": true,
              "outputHashing": "none",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": true,
```

### Observed behavior
Blocking at 95% but folder and map exist on filesystem, cli never finish 95% step. (it works if disabled optimisation option)
` 95% emitting index-html-webpack-plugin`

### Desired behavior
Finish generation build with sourcemap when optimisation and buildOptimizer are enabled in configuration

update: same behavior in v6 release of angular&cli

**Comment by vytautas-pranskunas-** [comment]
Have same issue just with Angular 6 and Angular-Cli 6

**Comment by robport** [comment]
+1

**Comment by raulalexe** [comment]
+1

**Comment by encool** [comment]
+1

**Comment by Maximaximum** [comment]
I've got similar problem, but for me it freezes at 92%

**Comment by AwsmOli** [comment]
Does the same thing on my mac though

**Comment by zwwtj2014** [comment]
Have same issue  Angular-Cli 6 on win10

**Comment by ArsalRaza** [comment]
I also have the same problem, any work around for this?

**Comment by TylerHelmuth** [comment]
Currently still experiencing this issue in angular-cli 6.0.8

**Comment by lucasBertola** [comment]
+1

**Comment by vladjerca** [comment]
+1

**Comment by Maciejszuchta** [comment]
+1

**Comment by lanmolsz** [comment]
+1

**Comment by SonicReal** [comment]
+1

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
