### ISSUE TITLE
Production build doesnt copy environment.prod.js

### ISSUE THREAD

**Issue by thodo** [angular/angular-cli#1060]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
v6.2.1

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Have'nt tried before
ng build copies environment.dev.js to app/environment.js
BUT
ng build -prod does not copy environment.prod.js to app/environment.js
there is no environment.js file

4. The log given by the failure. Normally this include a stack trace and some
   more information.
no error during build

5. Mention any other details that might be useful.
btw: you made a good job - thank you
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by thodo** [comment]
I've found it. will be included in mininfied file and includes my production flags too. fine.
but I have a message 'angular runnng in development mode...' in console even built with "ng build -prod"
Why?

**Comment by filipesilva** [comment]
That's odd and unintended. Which version of the CLI are you using?

**Comment by thodo** [comment]
I've tried inbetween with Beta 6 and it works well. Thank you very much

**Comment by filipesilva** [comment]
Glad to hear that's sorted!
