### ISSUE TITLE
Fails to load non scss files referenced by scss files in @import statements

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular-cli#10604]
I reference an scss file in the assets folder from styles.scss, using the @import statement. That file references a css file in the same folder, however ng build reports an error that the css file in question cannot be found, even though in the context of the @import statement the file is in the location it should be.

I am using angular/cli@1.7.4.

I have created a repo project on github, and a more detailed description of the problem in the README file: https://github.com/williamBurgeson/ng-css-load-problem

**Comment by williamBurgeson** [comment]
Just copying over the readme to better describe the problem: 

This project represents a much simplified example of an issue which I encountered on a separate project I have been working on.

In that project there is a folder containing a number of style files, both scss and css, but also woff2 files (for ng material fonts), which are copied over from a central location in the larger company repo. There are a couple of "top level" scss files in this folder, which @import the other scss and (either directly or indirectly) import css and woff2 files too.

When I add an @import to the inbuilt styles.scss file to reference the scss "master" file from my copied-over folder, and run ng build I get an error to the effect that the css file couldn't be found, despite the fact that it is in the same folder as the scss file containing the @import statement.

Another Angular project in the larger repo which uses a custom webpack config file does not encounter this problem when using these shared files.

This problem doesn't occur when other scss files are @imported.

My expectation as a "user" is that if a file is referenced by another one in the same folder, the system should be able to find that file.

I suspect what is happening is that the system picks up and inlines the scss code, and then searches for any non-scss imports, by which time the current working location context of the original @import statement is lost. I believe this is a bug and hae created this repository to recreate the issue.

The project is simply a vanilla ng new project, with a handful of scss and css files added to te assets folder. The default styles.scss file @imports the external-styles.scss file, which in turn @imports both the external-styles.css and another-file.scss file, in that order.

When running ng build or ng serve we get an rror to the effect that external-styles.css could not be found. If we change the name of the file to be a scss file (we also need to slightly ament the file name to avoid a naming clash) and then reference that renamed file, the project builds and serves with no problems, and we can observe that the rules defined kick in (the background is red and divs have a green 1px border).

**Comment by williamBurgeson** [comment]
I have found a workaround (or rather my boss did): if the sass file is referenced directly from the styles list of the `angular-cli.json` file, the problem doesn't occur. I assume this is because each entry in the styles creates a new "context" for the purposes of resolving non compilable (ie non sass) file references.
IMO the behaviour described above is still a bug.
I have updated the repo slightly to reflect this.

**Comment by williamBurgeson** [comment]
I can confirm this is also happening in ng6: I referenced one of the scss files from within my project directly (it had been "indirectly" referenced via the angular.cli file) as I wanted to access some $ scss variables. That particular scss file also referenced a css file and therefore the build failed due to not being able to find the css file.

Just to repeat the issue: when a scss file references a css file which is local to it, the build process should be able to either inline the css file, or at least record the location the css file was originally in, so that it can be located.

**Comment by alan-agius4** [comment]
This is related to the fact that Sass does not provide url rewriting see https://github.com/webpack-contrib/sass-loader#problems-with-url 

This issue is also related to this https://github.com/angular/angular-cli/issues/12797

**Comment by alan-agius4** [comment]
This is related to the fact that Sass does not provide url rewriting see https://github.com/webpack-contrib/sass-loader#problems-with-url

This issue is also related to this #12797

**Comment by alan-agius4** [comment]
This is related to the fact that Sass does not provide url rewriting see https://github.com/webpack-contrib/sass-loader#problems-with-url

This issue is also related to this #12797

The recommended and common practice is that the library provides a way to have to specify the path for the location of assets/resources.

Example
external file:
```
@import url("#{$some-path}/external-css-file.css");
````

Your styles,scss
```
$some-path: "assets/styles";
@import "external-sass-file";
```
