### ISSUE TITLE
"ng new new-project" failed (node 10, npm 6, ...)

### ISSUE THREAD

**Issue by ge0rgecz** [angular/angular-cli#10609]
### Versions
AngularCLI 1.7.4
Node 10.0.0
OS: Ubuntu Linux 18.04 LTS
NPM: 6.0.0

### Repro steps
* type command "ng new new-project"

### Observed behavior

> npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
> npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
> npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
> npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
> npm WARN deprecated buildmail@4.0.1: This project is unmaintained
> npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
> npm ERR! code ERR_STREAM_WRITE_AFTER_END
> npm ERR! write after end
> npm ERR! code ERR_STREAM_WRITE_AFTER_END
> npm ERR! write after end
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/douby/.npm/_logs/2018-05-03T19_57_56_063Z-debug.log
> Error: Package install failed, see above.
> Package install failed, see above.

### Mention any other details that might be useful (optional)
node js installed this way:

> curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
> sudo apt-get install -y nodejs

**Comment by mantyz** [comment]
@ge0rgecz It seems that this is a problem with npm. See this issue https://github.com/npm/npm/issues/19989
