### ISSUE TITLE
ng build does not work for the quickstart app

### ISSUE THREAD

**Issue by TheChrisPratt** [angular/angular-cli#10606]
### Versions
```
Angular CLI: 1.7.4
Node: 10.0.0
OS: win32 x64
Angular: 4.3.6
... common, compiler, core, forms, http, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.1.6
webpack: 3.11.0
```

### Repro steps
Followed Steps at https://angular.io/guide/setup
* git clone https://github.com/angular/quickstart.git quickstart
* cd quickstart
* npm install
Then followed the steps on https://angular.io/guide/deployment
* ng build

### Observed behavior
Initially
```
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"

Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.
```
If you follow the included directions and try again
```
Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.
```

### Desired behavior
No error, project built and ready to be copied to a web server

### Mention any other details that might be useful (optional)
I'm trying to follow the Angular Guide to create a web site deployed on my resin server, but am running into problems that I would not expect in an environment as mature as NodeJS.

**Comment by filipesilva** [comment]
Heya, I talked to the docs team and the Setup guide actually hasn't been updated to use the CLI. There is now an issue in Angular itself to cover that: https://github.com/angular/angular/issues/23693

**Comment by TheChrisPratt** [comment]
Any help getting past the immediate issue of how to create, build and deploy an Angular app would be very much appreciated.
