### ISSUE TITLE
Wallaby not finding wallabyTest.js

### ISSUE THREAD

**Issue by c-science1** [angular/angular-cli#10608]
Facing this weird issue that Wallaby is still complaining about not finding wallabyTest.js file even tough I have it saved as attached.

Unable to move ahead with Wallaby due to this. Also I can't seem to see the Wallaby toolbar I used to have in my previous company using phpStorm,

![image](https://user-images.githubusercontent.com/19345360/39561347-f8ed9bee-4e9c-11e8-8b4d-ae9a7f10ea24.png)

**Comment by istiti** [comment]
![wallaby](https://user-images.githubusercontent.com/2789203/39561940-374b8cb4-4ea9-11e8-9630-ce14ae1e85cd.gif)

**Comment by c-science1** [comment]
Sorry that was by mistake, had wrong window open.
