### ISSUE TITLE
Mixing configurations

### ISSUE THREAD

**Issue by ocombe** [angular/angular-cli#10612]
### Versions
v6

### Observed behavior
You cannot use `--prod` with a custom `configuration` since `--prod` is an alias for `--configuration=production`. This means that if I make a custom configuration for my project, I need to duplicate it for the prod build to include everything from the `production` configuration.

### Desired behavior
I'd like to be able to mix configurations, where each one overwrites the precedent. For example with `-c=prod,xxx`, where `xxx` overwrites `production` values if they both define the same property

For example if I'm doing i18n, I would like to have something like that:
```
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "fr": {
              "aot": true,
              "outputPath": "dist/my-project-fr/",
              "i18nFile": "src/locale/messages.fr.xlf",
              "i18nFormat": "xlf",
              "i18nLocale": "fr",
              "i18nMissingTranslation": "error"
            }
          }
        },
```

And use `-c=production,fr`, or `--prod -c=fr`

**Comment by filipesilva** [comment]
@buu700 was also interested in something similar in https://github.com/angular/angular-cli/issues/10559

**Comment by phl3x0r** [comment]
That would be a great addition.
At the moment (in the 1.x.x config) I have a setup with many apps sharing a lot of the same (duplicate) configuration. I was hoping that 6.0 would provide a way to share common configuration between app flavors, but at this point, the config will just be even more bloated than before.
In my case it's not the i18n files (although potentially it will be in the future), but assets, styles and environment files that changes between customers (apps).

**Comment by MickL** [comment]
Alternative to using multiple configurations they could have a extend feature as mentioned here: https://github.com/angular/angular-cli/issues/11206

**Comment by MickL** [comment]
@hansl Personally i would set this issue to priority 2 (required):

serve (builder `@angular-devkit/build-angular:dev-server`) does not allow to set properties like `assets` or `fileReplacements`. So instead of:

`ng build -c=prod,theme1,en` and `ng serve -c=theme1,en`

we have to make TONS configurations

```
"build": {
   ...
    "configurations": {
        "theme1": {
            // Asset configuration theme 1
        },
        "theme1-en": {
            // Asset configuration theme 1
            // Load language files EN
        },
        "theme1-prod-en": {
            // Production settings
            // Asset configuration theme 1
            // Load language files EN
        },
        "theme1-de": {
            // Asset configuration theme 1
            // Load language files DE
        },
        "theme1-prod-de": {
            // Production settings
            // Asset configuration theme 1
            // Load language files DE
        },
         "theme2": {
            // Asset configuration theme 2
        },
        "theme2-en": {
            // Asset configuration theme 2
            // Load language files EN
        },
        "theme2-prod-en": {
            // Production settings
            // Asset configuration theme 2
            // Load language files EN
        },
        "theme2-de": {
            // Asset configuration theme 2
            // Load language files DE
        },
        "theme2-prod-de": {
            // Production settings
            // Asset configuration theme 2
            // Load language files DE
        },
    },
    "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
                    "browserTarget": "posident:build"
          },
          "configurations": {
                    "theme1": {
                            "browserTarget": "posident:build:theme1"
                    },
                    "theme1-en": {
                            "browserTarget": "posident:build:theme1-en"
                    },
                    "theme1-de": {
                            "browserTarget": "posident:build:theme1-de"
                    },
                    "theme2": {
                            "browserTarget": "posident:build:theme2"
                    },
                    "theme2-en": {
                            "browserTarget": "posident:build:theme2-en"
                    },
                    "theme2-de": {
                            "browserTarget": "posident:build:theme2-de"
                    },
    }
}
```

**Comment by phl3x0r** [comment]
Looks like our situation. 30+ configurations x 6 different environments = wall of config

**Comment by rmsmq** [comment]
> Alternative to using multiple configurations they could have a extend feature as mentioned here: #11233 . Definitely need either one of them.

Unless I am misunderstanding, I don't think this will reduce the number of configurations, only duplication within the configurations.

I would prefer the proposed solution in this issue, which should allow for significantly less configurations.

**Comment by pmattke** [comment]
+1

would definitely need such a feature!

**Comment by PhoneixS** [comment]
I think that it should be mentioned in the documentation in [Deployment](https://angular.io/guide/deployment) because nowadays it is in [i18n](https://angular.io/guide/i18n):

> For production builds, you define a separate production-fr build configuration in the CLI configuration file, angular.json.

**Comment by robertjk** [comment]
I also think this feature is essential to write maintainable, clean configurations, especially when you implement internationalization.

I wonder if this problem could also be solved by allowing `angular.json` to be written in YAML (`angular.yaml`), as YAML lets you declare anchors to duplicate properties.

**Comment by wulfsberg** [comment]
I agree with @MickL that this is beyond a "nice to have". Even something as trivial as changing the default locale (for pipes) explodes into a barrage of cut'n'paste all over the already-not-too-friendly `angular.json`.

**Comment by listepo-alterpost** [comment]
Any news?

**Comment by splincode** [comment]
@mgechev it would be cool to be able to inherit

```ts
"build": {
  ...
  "configurations": {
    "production": {
      (...)
    },
    "pl": {
      "extends": "config/pl.angular.json",
      (...)
    },
    "en": {
      "extends": "config/en.angular.json",
      (...)
    }
  }
}
```

**Comment by waterplea** [comment]
Any news on that? I have a workspace with many libraries and I have to duplicate test configs and other similar stuff for all of them.

**Comment by syndimann** [comment]
we are facing the same problem. for the time being is there any workaround/best practice to avoid copy and paste a great amount of the same configuration parts that someone could share?

thank's a lot in advance

**Comment by MaximSagan** [comment]
I'd like to throw my hat in support of the solution proposed in #11233 where we have the ability to extend configs/use base configs in angular.json (rather than on the command line as suggested here). Since that issue was closed in favor of this one, I'm commenting here.

This functionality would be so convenient for [nx](https://github.com/nrwl/nx) projects that may contain hundreds of libs all requiring the exact same configuration (e.g. for tests). @filipesilva, please let us make this happen.

**Comment by asvishnyakov** [comment]
As a workaround I store angular.json as javascript object in angular.ts script. It allow me to store production configuration in single constant and reuse it with typescript spread syntax, i.e.
```typescript
configurations: {
    production: ...productionConfiguration(),
    anotherProductionConfiguration: {
        ...productionConfiguration(myParams),
        otherProperty: 'value'
    }
}
```
I compile it and run as `node angular.js` before build and serve commands (I use `npm run build`, `npm run start` which internally call this task).

**Comment by appleseedexm** [comment]
This feature would also solve the current issue that you can't use a global assets definition in options together with a build-specific assets definition. I assumed the assets in options would always be loaded, however they are ignored in case there is an assets array in your build configuration

`
"options": {
    // will only load for production, not for integration
    "assets": [
        {
            "output": "assets",
            "glob": "**/*",
            "input": "src/assets"
        }
    ]
},
"configurations": {
    "integration": {
        "assets": [
            {
                "output": "json",
                "glob": "someFile.json",
                "input": "src/json"
            }
        ]
    },
    "production": {}
}
`

**Comment by anik786** [comment]
I personally think that angular.json should be a angular.js that exports an object. I noticed this was requested here:  https://github.com/angular/angular-cli/issues/12943

This means we can do what @ashasvishnyakov described:

```
configurations: {
    production: ...productionConfiguration(),
    anotherProductionConfiguration: {
        ...productionConfiguration(myParams),
        otherProperty: 'value'
    }
}
```

**Comment by abariatti** [comment]
> I compile it and run as `node angular.js` before build and serve commands (I use `npm run build`, `npm run start` which internally call this task).

@asvishnyakov Would you have the awesomness of providing a running gist?

**Comment by asvishnyakov** [comment]
@abariatti I cannot show you full code because of my contract limitations, but the idea is simple.

Add `angular.ts` and put your current json to it as typescript object, i.e.
```typescript
const angularJson = { ... };
```
Then add output to the angular.json:
```typescript
const fs = require('fs');
const angularJson = { ... };
fs.writeFileSync('angular.json', JSON.stringify(angularJson, null, 4), 'utf8');
```

Now, in `packages.json` add tasks to compile and run it:
```json
{
  "scripts": {
    "angular-json:build": "tsc --moduleResolution node --lib es2018 --outFile angular.js angular.ts",
    "angular-json:transform": "npm run angular-json:build && node angular.js",
```

Then run `angular-json:transform` task manually every time you change `angular.ts` or add it before every build or run task in `packages.json`:
```json
{
  "scripts": {
    "build": "npm run angular-json:transform && ng build"
```
