### ISSUE TITLE
Feature Requeset: Allow passing custom file as configaration file

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular-cli#10626]
**Relevant Stackoverflow Question** https://stackoverflow.com/q/42008254/1859367

### Observed behavior
Currently config file location is hard coded to `.angular-cli.json`

### Desired behavior
Should be possible to override location of config file from command line

### Mention any other details that might be useful (optional)
We are using multiple `app` feature of `.angular-cli.json`
for reference our project directory structure is like

```
|-src
|   |-app1
|   |   |-...app1 files
|   |
|   |-app2
|   |   |-...app 2 files
|   |
|   |-common
|   |    |- shared code between above two apps
|
|-.angular-cli.json & other files 
```
currently we have two entries in  `.angular-cli.json` `apps` array

On CI we build both apps and shared `common` code is built twice
What I want to do is `rollup` shared code once on CI, and we can use `path aliasing` from `tsconfig.json` to use rolledup code for application building.

I know I can add two more apps in existing `.angular-cli.json` but it will complicate configuration in single place, And I want to keep both dev build and prod build configs seperate

**Comment by alan-agius4** [comment]
Hi @abdulkareemnalband, 

Thanks for this feature request. However, at the moment this is not on the Angular CLI. 

Let's reconsider this in the future if we see more interest for this.
