### ISSUE TITLE
`ng install ng2-bootstrap ng2-bootstrap` fails

### ISSUE THREAD

**Issue by shmert** [angular/angular-cli#1062]
1. OS

Mac OS X 10.10.5

2. Versions
   run in a Terminal: 
        node --version
   And paste the result here.

```
% ng version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.5
node: 4.4.5
os: darwin x64


```
3. Repro steps

Run the following from cmd line:

```
% ng install ng2-bootstrap ng2-bootstrap
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
installing ng2
The `ng generate <entity-name>` command requires an entity name to be specified. For more details, use `ng help`.

```

5. Mention any other details that might be useful.

Steps to workaround by editing the system.config.js and angular-cli-build.js are here: https://github.com/valor-software/ng2-bootstrap/issues/208

**Comment by filipesilva** [comment]
`ng install` was actually removed some time ago. 3rd party libs are now supported via the instructions here https://github.com/angular/angular-cli/wiki/3rd-party-libs.
