### ISSUE TITLE
Commands ng test and npm run test do not watch

### ISSUE THREAD

**Issue by ryanmccormick** [angular/angular-cli#10623]
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: linux x64 - Ubuntu 18.04 LTS
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
* Step 1 run  `npm run test` or `ng test` from the command line.

### Observed behavior
Even though the karma config `src/karma.config.js` explicitly sets singleRun to false and autoWatch to true, the test runner exits after running the test runner command.

### Desired behavior
Test runner should not exit after running tests. Runner should watch for file changes and re-run tests as targeted files change.

#### Workaround
I found that adding --watch after the ng test command in the command line produces the expected behavior.

Also, I found that adding --watch after the ng test in the package.json scripts and running `npm run test` produces the expected behavior.

#### Browsers
I have tried running with the default browser Chrome as well as ChromeHeadless and the same behavior exists.

**Comment by filipesilva** [comment]
Hi @ryanmccormick, the behaviour you see is intentional: we default `watch` to false and it overrides what is in the Karma configuration. But it is confusing that `singleRun` is set there. Maybe we should remove the setting in the karma config.

**Comment by ryanmccormick** [comment]
Thank you for responding so quickly. It is confusing the way it is set up, especially when moving from an ng5 cli project where watch works out of the box. 

Shouldn't the karma configuration file override the default configuration? I think that could be the confusing part.

**Comment by jguix** [comment]
Thanks, this info was very useful for my project.
