### ISSUE TITLE
ng add @angular/material installs @angular/material but does not install @angular/cdk

### ISSUE THREAD

**Issue by ayush987goyal** [angular/angular-cli#10627]
### Versions
```
Angular CLI: 6.0.0
Node: 8.9.3
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router
```

### Repro steps

* Step 1: `ng add @angular/material`
* Step 2 It will update multiple files and add `@angular/material` and `@angular/cdk` to `package.json`

### Observed behavior
```
It will install @angular/material but won't install @angular/cdk
```

### Desired behavior
```
It should either install both or none.
```

**Comment by Barvor** [comment]
have the same issue and manually installing it wants me to install @angular-devkit/angular-build as well.
manually installing the devkit results in:  "You seem to not be depending on "@angular/core" and/or "rxjs". This is an error."

All on a freshly created angular project, while importing a local frontend repo

**Comment by filipesilva** [comment]
Heya, I moved this issue over to https://github.com/angular/material2/issues/11159 because it is a problem it the add schematic that Material has.
