### ISSUE TITLE
ng update @angular/core fails

### ISSUE THREAD

**Issue by markgoho-EDT** [angular/angular-cli#10621]
### Versions
``` bash
Angular CLI: 6.0.0
Node: 8.9.1
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@angular/cli                 6.0.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         5.5.10
typescript                   2.6.2
```

### Repro steps
* Follow steps at https://update.angular.io/
* `ng update @angular/core`

### Observed behavior
``` bash
Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.6.2")
Invalid range: ">=4.3.0"
```

### Desired behavior
I would expect this to work properly.

### Mention any other details that might be useful (optional)
I tried to manually update the compiler-cli and run the update function again and got this:
```bash
$ ng update @angular/core
Invalid range: ">=4.3.0"
```

**Comment by lordgreg** [comment]
@markgoho-EDT, the `ng update` itself doesn't do anything else as showing the packages that have to be updated:
```
ng update
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/core                      5.0.5 -> 6.0.0           ng update @angular/core
      @angular/material                  5.2.0 -> 6.0.0           ng update @angular/material
      rxjs                               5.5.2 -> 6.1.0           ng update rxjs


    There might be additional packages that are outdated.
    Or run ng update --all to try to update all at the same time.
```

Doing `ng update --all` isn't doing its job either:
```
ng update --all
                  Package "karma-jasmine-html-reporter" has a missing peer dependency of "jasmine" @ "^3.0.0".
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.8.3")
                  Package "@auth0/angular-jwt" has an incompatible peer dependency to "@angular/common" (requires "^4.4.6||^5.0.0", would install "6.0.0")
                  Package "ng2-pdf-viewer" has a missing peer dependency of "pdfjs-dist" @ "2.0.489".
Invalid range: ">=6.0.0-rc.0"
```

**Comment by Jrubzjeknf** [comment]
I updated the cli first with `ng update @angular/cli`. Running `ng update @angular/core` after that gives me the error `Invalid range: ">=4.3.0||>5.0.0"`.

**Comment by lordgreg** [comment]
So, the `Invalid range: ...` doesn't say much. It could at least state from which `package.json` (aka from which node module this is coming from)

**Comment by bop10** [comment]
I tried to run _ng update @angular/core_ and my terminal shows this:
                                                                                                                                                         [[24;154R                                                                                                                                                Invalid range: ">=2.3.0 <3.0.0||>=4.0.0"

**Comment by Theo59** [comment]
Same here. I tried to different version of Typescript (2.4, 2.6, 2.7, 2.8) and i get differents "Invalid range" error :

**Comment by IterationCorp** [comment]
same for me, just did
npm install @angular/compiler@6.0.0
npm install @angular/compiler-cli@6.0.0
...
for all @angular/... package and it was ok

**Comment by lordgreg** [comment]
@IterationCorp - this doesn't update your configuration files then, which means your karma, tslint and angular config won't get updated at all.

**Comment by kublaios** [comment]
Same here,
```
$ ng update --all
                  Package "angular2-moment" has an incompatible peer dependency to "@angular/core" (requires ">=2.0.0 <6.0.0", would install "6.0.0")
                  Package "countup.js-angular2" has an incompatible peer dependency to "ts-node" (requires "~3.2.0", would install "6.0.2").
                  Package "bootstrap" has a missing peer dependency of "popper.js" @ "^1.14.3".
                  Package "ng2-dnd" has an incompatible peer dependency to "@angular/core" (requires "^4.0.0 || ^5.0.0", would install "6.0.0")
Invalid range: ">=4.0.1||>5.0.0||<=6.0.0"
```

**Comment by istiti** [comment]
try `ng update --all --force` but even `ng update`  seems still in beta step or out of scope

**Comment by MarkStega** [comment]
Same: Invalid range: ">=5.0.0"

**Comment by PierreRoudaut** [comment]
Same here:   `Invalid range  ">2.4.2"`

**Comment by frohrka** [comment]
I had the same issue. Upgraded my angular packages manually `yarn add @angular/$PACKAGE`, run `ng update @angular/core` again.

**Comment by tolvaly** [comment]
Workaround: 
1. Update manually the angular packages to 6.0.0
2. ng update rxjs
3. ng update angular/core
4. ng update angular/material
5. if ng update installs typescript 2.8.3 you have to install typescript version 2.7.2. angular compiler doesn;t work with 2.8.3

**Comment by bluefire2121** [comment]
This should have been checked before angular 6.0.0 was released. Now I have to downgrade everything.

**Comment by kanagunbr** [comment]
I had to uninstall the following to make "ng update @angular/core" successful. The good ting is the "ng update @angular/core" automatically installs the latest compatible @ngrx. 

npm uninstall @ngrx/db --save
npm uninstall @ngrx/core --save
npm uninstall @ngrx/effects --save
npm uninstall @ngrx/router-store --save
npm uninstall @ngrx/store --save
npm uninstall angularfire2 --save
npm uninstall @angular/flex-layout --save

**Comment by Mallfurion** [comment]
My workaround:
remove @angular/compiler-cli from package.json
run ng update @angular/core
npm i --save-dev @angular/compiler-cli@latest

seems to work :D

**Comment by JuanHB** [comment]
I was experiencing the same problem reported by @markgoho-EDT, with **some changes I was able to fix it**, bellow you can see my steps, maybe it will help someone else. 

The error message:
`Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.6.2")`

I was following along the steps from the https://update.angular.io page, but the above error poped when I was trying to run the `ng update @angular/core` bit.

What I have installed so far:
- Angular CLI (local and global): 6.0.0
- Typescript: 2.8.3

My steps:

`$ ng update`
  
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/core                      5.2.10 -> 6.0.0          ng update @angular/core
      rxjs                               5.5.10 -> 6.1.0          ng update rxjs
    
    
    There might be additional packages that are outdated.
    Or run ng update --all to try to update all at the same time.

`$ ng update --all`

    Package "karma-jasmine-html-reporter" has a missing peer dependency of "jasmine" @ "^3.0.0".
    Package "@angular/platform-browser-dynamic" has a missing peer dependency of "@angular/compiler" @ "6.0.0".

`$ ng update @angular/core`

    Package not installed: "@angular/compiler". Skipping.

`$ ng update @angular/compiler`    

    Package not installed: "@angular/compiler". Skipping.

`$ npm install @angular/compiler` -> the compiler was installed, but the version was `5.2.0`

    + @angular/compiler@6.0.0
    removed 7 packages and updated 1 package in 11.763s

`$ ng update core` -> worked fine, no messages this time

Then, just to be sure, run `$ ng update` again, and got:

    We analyzed your package.json and everything seems to be in order. Good work!

This is what I've done, worked for me, maybe will work for someone else. I think the key step was installing the `@angular/compiler` again, to force its update.

Note: I've just started this project, so no big changes for me, my dev env was almost pristine.

**Comment by chiangs** [comment]
These steps haven't helped me clear the error, and when I try ng build --prod --base-href / i get the following:
```
92% chunk asset optimization UglifyJSPluginUnhandled rejection TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/Users/dev/Projects/ChiangsNinja/node_modules/uglifyjs-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:20:20)
    at UglifyJsPlugin.buildError (/Users/dev/Projects/ChiangsNinja/node_modules/uglifyjs-webpack-plugin/dist/index.js:116:23)
    at /Users/dev/Projects/ChiangsNinja/node_modules/uglifyjs-webpack-plugin/dist/index.js:275:45
    at Array.forEach (<anonymous>)
    at /Users/dev/Projects/ChiangsNinja/node_modules/uglifyjs-webpack-plugin/dist/index.js:259:19
    at step (/Users/dev/Projects/ChiangsNinja/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/Users/dev/Projects/ChiangsNinja/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at tryCatcher (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/dev/Projects/ChiangsNinja/node_modules/bluebird/js/release/promise.js:569:18)
```

**Comment by KissBalazs** [comment]
I also had that issue: `ng update @angular/core` says "Invalid range: ">=2.1.0" 
Things, that **did not help** so far:
- updating everything manually to the latest version
- updating rxjs manually
- updating typescript to 2.7.2 and then to 2.8.3
- trying to `ng update --all`
- `npm install @angular/compiler@6.0.0`
until that point, ng -v showed my Angular version is 5.2. but...

 **What finally worked:** 
- `npm install @angular/core@6.0.0`

**Comment by RyanYizhaoHuang** [comment]
This is how I make it work.

My Environment:

Angular CLI Global : 6.0.0, Local: 1.7.4, Angular: 5.2
> Note:  To enable `ng Update` you need to install Angular CLI 6.0 first 
`npm install -g @angular/cli or npm install @angular/cli`

1.  `ng update  //update Angular Package core/common/complier... to 6.0.0`

2.  `ng update @angular/cli    //change angular-cli.json to angular.json`

optional if you have angular-material 5.4.2, ngx-translate 9.1.1, ng-bootstrap/ng-bootstrap 1.1.1:

3. `ng update @angular/material  //upgrade to 6.0.1`

4. `npm install @ngx-translate/core@10.0.1 --save   //upgrade ngX translate to 10.0.1 for Angular 6`

5 `npm install --save @ng-bootstrap/ng-bootstrap@2.0.0  //for ng-bootstrap`

If you use Observable and get the error: 

`ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'. node_modules/rxjs/observable/of.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/observable/of'.`

Change: `import { Observable } from "rxjs/Observable"; import { of } from 'rxjs/observable/of';
`

To 

`import { Observable, of } from "rxjs";`

**Comment by bluefire2121** [comment]
I finally got mine to work by doing the following:
Step 1: Run `ng ls --depth=1` to see if there is more than one version of webpack. 

Step 2: If so, then `npm uninstall webpack`

Step 3: delete all of the other _webpack-_ related folders in your **node_modules** directory. It is unnecessary to delete the entire node_modules directory.

Step 4: Run `npm install @angular-devkit` . @angular-devkit contains its own copy of webpack.

Step 5: Ensure that your webpack dependencies are met. You shouldn't see any errors in your console related to webpack not being installed.

**Comment by Bjeaurn** [comment]
@bluefire2121 Did you mean `npm ls --depth=1` ?

**Comment by keefmarshall** [comment]
I also got: `Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.6.2")`

I just fixed this by running `npm install typescript@2.7.2` immediately after seeing the error. 

I did subsequently get a heck of a lot of warnings and things that look like errors during the angualr/material update though it claimed to complete successfully.

**Comment by Bjeaurn** [comment]
In regards to the `Invalid range: xxx` errors, I've taken a quick peek at the `@angular-devkit/schematics` repo to see where the error was thrown and what was actually happening.

The error is thrown at https://github.com/angular/devkit/blob/master/packages/schematics/update/update/index.ts#L41

If I look at the surrounding function, seems that it's expecting `semver` versioned packages only, and no `logical` (by the lack of a better term?) versioning. 

I would try to debug it further, but can't seem to locate the compiled files in my project to tinker with it.

**Comment by bluefire2121** [comment]
@Bjeaurn yes 👍  Thank you. Updated.

**Comment by scharris** [comment]
It appears to be important to initially leave the local @angular/cli version at 1.7.4 (or whatever) and not 6.0.0. This is actually what the "npm install @angular/cli" in the update instructions does do, but  it gives a warning that the local one is at an older version, causing me to first try setting it at 6.0.0 like the global one before continuing, which lead to the range errors.  Starting over again from previous state pulled from version control,  I had luck by just ignoring that warning, and was able to get through the install as described at update.angular.io.

**Comment by manuelescamilla** [comment]
Thanks @scharris
![screenshot 2018-05-08 22 52 49](https://user-images.githubusercontent.com/10171118/39793234-90378bb2-5312-11e8-97fb-d021991e001f.png)

**Comment by KissBalazs** [comment]
Yeah, @scharris  and @manuelescamilla , that method causes this problem: https://github.com/angular/angular-cli/issues/10664

**Comment by isametal88** [comment]
Downgrading to 2.7.2. breaks a lot of @angular imports with no apparent reason. Using 2.8.3, the imports work but the compiler fails and nothing is usable. Waiting for a fix, I don't know what to do. I already tried to uninstall the whole node_modules folder and start from scratch and the behaviour is the same. I tried verifying my package configuration through npm-check and everything is ok.

**Comment by bbuehrer** [comment]
When i downgrade to typescript 2.7.2 and use angular/cli 6.0.0 then i have many errors with rxjs/Subscription and rxjs/Observable.
My rxjs version is 6.1.0

**Comment by scharris** [comment]
@bbuehrer, are you using the new import points for rxjs 6? They are changed (much simplified) so that could just be a legit compile error until imports are adjusted or the rxjs-compat package is added.

**Comment by bbuehrer** [comment]
ok i added the rxjs-compat package and it worked

**Comment by bbuehrer** [comment]
how can I find out if a new typescript version is compatible with angular/cli?

**Comment by StrangeCargo74** [comment]
I installed typescript 2.7.2 as soon as I got that error, and then proceeded ok.

npm install typescript@2.7.2

**Comment by lakerko** [comment]
None of the mentioned solutions helped me because even though I had installed typescript 2.7.2, I had typescript ^2.8.3 in `devDependecies`. When I changed it to 2.7.2 everything worked correctly. So if you are as stupid as I am, check your package.json, install isn't enough in that case.

**Comment by isametal88** [comment]
Am I the only one that is facing the imports issue downgrading to 2.7.2.? What am I doing wrong? I checked my node_modules, tyescript is 2.7.2 as expected, but none of the imports of classes of angular work anymore.
Anyway, should I expect a fix about this problem or it's gonna take a long time?

**Comment by lakerko** [comment]
@isametal88 did you try to delete node_modules nad package-lock,json and run npm install again?

**Comment by ninrod** [comment]
I had to manually add the 6.0.0 to all angular components and 2.7.2 to typescript. then it worked.

**Comment by isametal88** [comment]
@lakerko Yes, I did.

**Comment by Bjeaurn** [comment]
@isametal88 is your global tsc taking over? 

`tsc -v`

**Comment by isametal88** [comment]
I wasn't able to run that command, I tried with this one (it seems to do a similar thing)

npm list -g typescript
[..]
+-- @angular/cli@6.0.0
| `-- @schematics/angular@0.6.0
|   `-- typescript@2.7.2
+-- rxjs-tslint@0.1.3
| `-- typescript@2.8.3
`-- typings@2.1.1
  `-- typings-core@2.3.3
    `-- typescript@2.6.1

I doubled-check the typescript folder in node_modules and it is 2.7.2.

**Comment by isametal88** [comment]
tsc -v
message TS6029: Version 1.5.3

**Comment by Bjeaurn** [comment]
That version is way too old. Explains why your imports etc aren’t working. Your situation seems unrelated to the reported issue.

**Comment by ewaschenko** [comment]
Still getting these errors.  Manually upgraded to Angular 6 with RxJS at 6.1.0 and Typescript 2.7.2

```
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.
node_modules/rxjs/Subscription.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subscription'.
```

```
Angular CLI: 6.0.0
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      6.0.1
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.0.1
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by clement911** [comment]
same here what is the official recommended way forward here? 
not giving much confidence in the hyped ng update.

**Comment by jtsom** [comment]
Ran into the "Invalid range" error also, just trying to use `ng update @angular/cli` to update to 6.0.1, something I think should have been easy. Nope. Ended up doing an `npm update` to get 6.0.1, but still doing `ng update @angular/core` (because `ng update` said it needed to), I'm seeing 
```
Invalid range: ">2.4.2"
```

No idea what is triggering this - it's pretty much a standard CLI app.

**Comment by imakshath** [comment]
<img width="637" alt="screen shot 2018-05-11 at 6 40 42 pm" src="https://user-images.githubusercontent.com/9428527/39925841-e079545e-554a-11e8-8b61-d556341931bc.png">

**Comment by ray-kay** [comment]
Similar issues here. I just started a new Angular 6.0.0 project from CLI 6.0.0 a week ago.
I could update angular-cli to version 6.0.1 but doing 
`ng update @angular/core` shows me
Invalid range: ">=5.0.0"

I have typescript@2.7.2 and rxjs@6.0.1 installed

Anybody facing the same issue trying to update angular/core from 6.0.0 -> 6.0.1 ?

**Comment by ddahan** [comment]
@ray-kay 
I had a clean install of 6.0.0.
When running `ng update --all` to try update to the 6.0.1, here is the error I have:

```
Package "karma-jasmine-html-reporter" has a missing peer dependency of "jasmine" @ ">=3".
Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.8.3").
Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.8.3")
Incompatible peer dependencies found. See above.
```

My package.json contains `"typescript": "2.7.2"` in devDependencies. That makes no sens to me.

**Comment by ray-kay** [comment]
@ddahan I had the same issue before I think.
Could solve by just update the locale angular cli on its own:
`ng update @angular/cli`

Hope this will help with your issue. After that try:
`ng update @angular/core` and it  should say:
Invalid range: ">=5.0.0"

**Comment by ray-kay** [comment]
I just run 
`npm update` instead ng update and it updated Angular's packages to 6.0.1 without any issues.
Maybe an issue in the cli ng update dependency detection?

**Comment by jtsom** [comment]
Except, for me anyway, when I initially updated to 6.0, the package.json items were set like 
“@angular/common”: “6.0.0”
Locking it to that version. Npm update would not update anything.

**Comment by ddahan** [comment]
Sorry for beeing so negative and off topic, but what's the point for Google to provide a new `ng update` command supposed to ease things if we need 58 comments in a an issue and 6 steps, to go from 6.0.0 to 6.0.1 in the end?
I gave up, I will update this later when tools will be less cumbersome to use.

**Comment by duncandean** [comment]
The main problem seems to be with `ng update --all` not doing its job properly.
Following @Rumsha001 's approach seems to work well. 

Just don't forget the `@`s:

4. `ng update @angular/core`
5. `ng update @angular/material`

I also needed to `ng update @angular/cli`

**Comment by Tyrcheg** [comment]
What I was doing:

1. Follow "Before updating guide" from https://update.angular.io/
2. Then set typescript package version to 2.7.2 (yarn upgrade typecsript@2.7.2)
3. yarn add global @angular/cli
4. ng update @angular/cli
5. yarn add @angular/cli
6. then continue following the guide
7. ??????
8. profit

**Comment by rogercoder** [comment]
I tried following the steps @Rumsha001  laid out but was still having "Invalid range" failures at the `ng update @angular/core` step. Then I changed step 1 to use version '6.0.2' and finally things worked. No guarantees this was the magic touch though ... I tried many things tonight, in various orders, etc. 

Overall, very frustrating, I've gotta say ...

**Comment by jtsom** [comment]
I know this is "closed" with a "fix" in place, but trying to ng update to 6.0.2 produces the same "invalid range" error. ng update is more of a problem that it's solving at the moment.

**Comment by Sevensnake** [comment]
same problem with 6.0.2 what is going on.
`WARNING in ./node_modules/ng-http-loader/node_modules/@angular/core/esm2015/core.js
5354:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ng-http-loader/node_modules/@angular/core/esm2015/core.js
5370:15-102 Critical dependency: the request of a dependency is an expression`

**Comment by chriscurnow** [comment]
It certainly looks like ng update needs more work. 

But people complaining here should have been around when Angular (2) was still in alpha. It was pretty hairy back then with breaking changes every couple of days sometimes.

That experience taught me it was worth sticking with Angular. It just gets better all the time. Sure a new feature like ng update might not work for everyone straight out of the box but I think we can all rest assured the engineers at Google will be working on it until they get it pretty well right.

Also remember updating from v5 to v6 is going to be a pretty huge task to accomplish with a single tool. After we have updated to v6, I'm sure the update process for future versions will be a whole lot better.

**Comment by Tyrcheg** [comment]
@chriscurnow well. for me to update the angular from 5 to 6 I only needed this thread, ng-update guide and one day)

**Comment by BarnT** [comment]
I couldn't use ng update @angular/core to upgrade to 6.0.2. Then @angular/cli 6.0.3 has been released. After updating to @angular/cli 6.0.3 all ng update command worked well!

**Comment by crgolden** [comment]
I'm also confused.

In my package.json I have `"typescript": "^2.7.2"`.

When I run `tsc -v` I get `'tsc' is not recognized as an internal or external command, operable program or batch file`, so it is _not_ installed globally.

When I run `ng -v` I get
⋮
`Angular CLI: 6.0.3`
`Node: 8.9.1`
`OS: win32 x64`
`Angular: 6.0.2`
`... animations, cdk, common, compiler, compiler-cli, core, forms`
`... http, material, platform-browser, platform-browser-dynamic`
`... platform-server, router`
⋮
`@angular-devkit/architect    0.6.3`
`@angular-devkit/core         0.6.3`
`@angular-devkit/schematics   0.6.3`
`@angular/cli                 6.0.3`
`@ngtools/webpack             6.0.3`
`@schematics/angular          0.6.3`
`@schematics/update           0.6.3`
`rxjs                         6.1.0`
`typescript                   2.8.3`
`webpack                      4.8.3`

When I run `webpack`, I get `ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.8.3 was found instead.`

Where is this `2.8.3` TypeScript version installed? I didn't install it, but it looks like `Angluar CLI` installed it, and now `Angular Compiler` breaks because it's installed, and I can't run `webpack` as a result...

How do I remove this `2.8.3` TypeScript version (that I didn't install), so I can `webpack` my project?

**Comment by alberthendriks** [comment]
@tolvaly How do you "1. Manually update the angular packages to 6.0"?
I tried "ng update @angular/animations@6.0.3" but (after waiting 10 minutes) I get the same error.

**Comment by BarnT** [comment]
> @tolvaly How do you "1. Manually update the angular packages to 6.0"?
> I tried "ng update @angular/animations@6.0.3" but (after waiting 10 minutes) I get the same error.

"Manually" means that you should update packages using "npm install" instead of "ng update", like this:
```
npm install @angular/core@6.0.0 --save
npm install @angular/common@6.0.0 --save
etc...
```

**Comment by tolvaly** [comment]
>@alberthendriks 
> How do you "1. Manually update the angular packages to 6.0"?
> I tried "ng update @angular/animations@6.0.3" but (after waiting 10 minutes) I get the same error.

Meanwhile I found out why updating doesn't work with `ng update`. It's because of 3rd-party libraries witch depends on angular.
You have to find out witch of them is breaking your update, and you have to update them manually to the latest version witch support angular and rxjs 6. You have to analyse your package.json, check each dependency under "dependencies". This is also a good opportunity to throw out old libraries witch aren't  used or maintained anymore!

Couple of example libraries that broke my update were:
> - @ angular/flex-layout; Currently latest version: 6.0.0-beta.15
> - ng2-signalr;  Currently latest version: 6.0.0
> - @ ngx-translate/core;  Currently latest version: 10.0.2
> - ngx-moment; Currently latest version: 2.0.0

Until today all of them released a new version supporting angular6, and today I managed to update my packages to angular 6.0.5 running `ng update @angular/cli` without any issue. I was using angular/cli version 6.0.3

And responding to your question, under **manual update** I mean, you have to change the version numbers in package.json manually and run `npm install` to update the outdated packages.

**Comment by AmebaBrain** [comment]
As for many others - after upgrading to angular 6 package.json held fixed `"6.0.0"` version. Manually switching it to `"^6.0.0"` and executing `npm install @angular/{core,forms,...,router}` succesfully updates packages

**Comment by rcadhikari** [comment]
Running below should help to update your dependencies to latest version.
```
npm i -g npm-check-updates
ncu -u
npm install
```

**Comment by alexislargaiolli** [comment]
I had a typescript version missmatch like many people (requires ">=2.7.2 <2.8", would install "2.8.3").
My package.json contained typescript 2.7.2 but my package-lock.json contained typescript 2.9...
I remove this entry from package-lock.json and i run `npm install typescript@2.7.2`

I also needed to install angular-devkit/build-angular  as dev dependency `npm install --save-dev @angular-devkit/build-angular`

This solved my problem.

**Comment by zoonman** [comment]
So far I stuck with this:

```
 npm list typescript
client@0.0.0 /www/liverecord/client
├─┬ @angular-devkit/build-angular@0.6.1
│ └─┬ @angular-devkit/build-optimizer@0.6.1
│   └── typescript@2.7.2  deduped
├─┬ @angular/cli@6.0.7
│ └─┬ @schematics/angular@0.6.7
│   └── typescript@2.7.2  deduped
├─┬ @schematics/angular@0.6.0
│ └── typescript@2.7.2  deduped
├─┬ rxjs-tslint@0.1.4
│ └── typescript@2.8.3 
└── typescript@2.7.2 
```
Looks like `rxjs-tslint@0.1.4` screws everything.

**Comment by sanjeevSOPRA** [comment]
I could have faced incompatible peer dependency issues when i ran the command ng update @angular/core to update the core library of the existing angular project.

Issues

Package "@angular/cdk" has an incompatible peer dependency to "@angular/common" (requires ">=5.0.0-rc.0 <6.0.0||>=4.0.0 <5.0.0", would install "6.0.0").
Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.0").
Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.0").

in second time i used the following command to update the core library
ng update --next but still there an issue.

issue had fix when i use the following command with --force flag,
ng update @angular/core --next --force

now, my project library has been updated from version 4 to 6. Well done :)

"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/cdk": "^2.0.0-beta.8",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/material": "^2.0.0-beta.8",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^6.2.0",
    "zone.js": "^0.8.26",
    "rxjs-compat": "^6.0.0-rc.0"
  },

Good Luck !!!

**Comment by ZeeshanQurban** [comment]
I  have facing incompatible peer dependency issues when i ran the command ng update @angular/core to update the core library of the existing angular project.

Package "angulartics2" has an incompatible peer dependency to "@angular/router" (requires ">=7.0.0-rc.0 <8.0.0||>=4.4.0 <=6.0.0", would install "6.0.5").

Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.5").

can some one help on this

**Comment by benjamincharity** [comment]
From the message it seems that both of those libraries are specifically disallowing the 6.x.x version range.

I'm not personally using these, but from what I can see:

For `angulartics2` it looks like they moved to support Angular 6.x when they released version 6 of the package: https://github.com/angulartics/angulartics2/releases/tag/v6.0.0

For `codelyzer` it seems they should be supporting Angular 6.x starting with 4.2.1: https://github.com/mgechev/codelyzer/commit/3112b38607f56002106b9039619693193a134eac

**Comment by nalvadesharayu29** [comment]
I have the same issue with it.

> ng update @angular/core

Package "ngx-bootstrap" has an incompatible peer dependency to "@angular/forms" (requires ">=7.0.0-rc.0 <8.0.0||6.0.1", would install "6.0.7").
Incompatible peer dependencies found. See above.


Package.json

"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@auth0/angular-jwt": "^2.0.0",
    "alertifyjs": "^1.11.1",
    "bootstrap": "^4.1.1",
    "bootswatch": "^4.1.1",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^1.12.4",
    "ng2-file-upload": "^1.3.0",
    "ngx-bootstrap": "^3.0.0",
    "ngx-gallery": "^5.3.2",
    "popper.js": "^1.14.3",
    "rxjs": "^6.2.1",
    "time-ago-pipe": "^1.3.2",
    "underscore": "^1.9.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/cli": "^6.0.8",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "@types/underscore": "^1.8.8",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2"
  }

**Comment by CraigWarford** [comment]
I gotta say, the rabbit hole on this issue is a little nuts.  I'm trying an ng update from 6.0.2 to 6.2.4, and I've chased through several missing packages that were apparently added in between those two versions.  I started with @angular-devkit/build-angular, but then also hit clean-css, compression and dom-converter.  I got stuck on the last two, because attempting to install either one states that the other one is missing.  ng update is a big fat fail for me.  There should be something to detect missing packages between versions, and install those as part of the ng update process.  Otherwise, it's faster to create a project from scratch and manually copy everything over.

**Comment by gaelganlut** [comment]
**npm install typescript@3.1.3**
then **ng update @angular/core** worked for me
Good luck guys

**Comment by kobusbeets** [comment]
**For future reference.** I got frustrated trying so many "solutions" with no avail so I decided to just run the following command.

`$ ng update --all --force`

It was a wild gamble and took a while to update but now everything is working and my project is up-to-date.

**Comment by daverickdunn** [comment]
`ng update --all --force` worked for me also. 

@kobusbeets I can't say it was a "wild gamble" though, not with a version control system.
