### ISSUE TITLE
Build application with a custom path

### ISSUE THREAD

**Issue by miguelleitevieira** [angular/angular-cli#10637]
I made a deploy of my webapp in dev enviroment, on the location site.com/webapp but the import path in index.html file don't have the reference to the folder webapp, so I can't get the files:

Refused to execute script from 'https://site.com/inline.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
spfamily-dev.smithmicro.io/:1 Refused to execute script from 'https://site.com/polyfills.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
site.com/:1 Refused to execute script from 'https://site.com/styles.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
site.com/:1 Refused to execute script from 'https://site.com/scripts.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
site.com/:1 Refused to execute script from 'https://site.com/vendor.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
site.com/:1 Refused to execute script from 'https://site.com/main.bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I runned the command "ng build -bh "/webapp/" and solved part of the problem but I continued with problems to load assets folder with correct path.

How I can add this webapp folder on build configuration. Someone have an example?

Thanks.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
