### ISSUE TITLE
Compilation fails when using lazy loading feature modules

### ISSUE THREAD

**Issue by samalexander** [angular/angular-cli#10630]
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
* ng new test-cli --routing
* ng generate module orders --routing
* Add the following to the route config
```
{
    path: 'orders',
    loadChildren: 'app/orders/orders.module#OrdersModule'
}
```
* ng serve

### Observed behavior
```
ERROR in Could not resolve module app/orders/orders.module relative to /Users/Sam/Developer/test-cli/src/app/app-routing.module.ts
ℹ ｢wdm｣: Failed to compile.
```

### Desired behavior
Compilation completes successfully

**Comment by intellix** [comment]
Does this work? `./orders/orders.module#OrdersModule`

**Comment by samalexander** [comment]
@intellix already tried that out, it produces the same error

**Comment by intellix** [comment]
Tried this myself and it worked :) 

![screenshot 2018-05-04 12 53 21](https://user-images.githubusercontent.com/1162531/39624575-2463dc72-4f9a-11e8-8a9a-8a3998a35d5a.png)

**Comment by samalexander** [comment]
Sorry, didn't spot the fact you'd omitted app from the path. Confirmed it works with this. However, does not match up with the docs [here](https://angular.io/guide/lazy-loading-ngmodules). I have opened a pull request [here](https://github.com/angular/angular/pull/23704) to fix this issue with the docs.

**Comment by samalexander** [comment]
Closing as resolved.
