### ISSUE TITLE
ng add @angular/material throws error while adding angular material to the Angular 6 cli project

### ISSUE THREAD

**Issue by mbaljeetsingh** [angular/angular-cli#10640]
### Versions
![image](https://user-images.githubusercontent.com/872762/39632434-b45fe630-4fd2-11e8-8f66-817b0d304210.png)

### Repro steps
* ng new my-app
* ng add @angular/material

### Observed behavior
![conemu64_2018-05-04_11-14-37](https://user-images.githubusercontent.com/872762/39632496-db762680-4fd2-11e8-9f41-3f40193a8037.png)

### Desired behavior
It should successfully add angular material to the angular cli project.

**Comment by hansl** [comment]
Hi @mbaljeetsingh,

Are you using an NPM cache or private registry?

**Comment by dtomaszewski** [comment]
I have similar issue 
<img width="492" alt="screen shot 2018-05-04 at 21 03 35" src="https://user-images.githubusercontent.com/4403684/39647359-e79a746e-4fde-11e8-832d-08a7b3595678.png">

<img width="843" alt="screen shot 2018-05-04 at 21 05 06" src="https://user-images.githubusercontent.com/4403684/39647367-ecbb9338-4fde-11e8-8963-a20d601de067.png">

**Comment by danzrou** [comment]
Same here with ng add @angular/material

**Comment by mbaljeetsingh** [comment]
One solution I found is, If you install `@angular/material` and `@angular/cdk` dependencies locally before running ng add command, then it seems to work.

```
npm install --save @angular/material @angular/cdk
ng add @angular/material
```
I

**Comment by dtomaszewski** [comment]
@eyev this solution does not work for me, however @mbaljeetsingh solution with manual install before ng add works as a workaround

**Comment by leandropiga** [comment]
@mbaljeetsingh the solution worked for me.  Thanks!!

**Comment by Shraddha80011** [comment]
I am facing same problem with ng add @angular/material.
Error: Collection "@angular/material" cannot be resolved.

**Comment by Shraddha80011** [comment]
Temp solution, use old version
ng add @angular/material@6.2.1

**Comment by kernelgis** [comment]
The solution is to indicate the version, it works for me like this: ng add @angular/material@6.3.0

**Comment by CSDisciple** [comment]
So I had a similar issue regarding material not working and getting the "typerror some function not defined".
**Fix**
1. Run **ng update**  in project console ( shows what can be updated )
2. ng update **filename to update**
 THEN
4. npm install  (to update the project build?)
 THEN 
5. ng serve (rerun your project and that should work (that's how I fixed my issue))

Please let me know if I need a more thorough explanation!

**Comment by pom1004** [comment]
I followed this process to update my project first.
[https://www.techiediaries.com/updating-angular-cli-projects/](URL) because "ng add" is a feature of angular 6 but in my project, as it is running angular 5 so the main file 'angular.json' file was missing. And that is why "ng add was not working in my project".  
![capture](https://user-images.githubusercontent.com/8271730/42935973-94d5c1a0-8b68-11e8-9a8f-4ae2dfb98193.PNG)

**Comment by smilemuffie** [comment]
When I was installing ng-zorro-antd, I had the same issue. What I did was, deleted the node_module and install it again. After that, I run `ng add ng-zorro-antd`, and got an warning: 
![image](https://user-images.githubusercontent.com/24146295/45878700-9bd5da00-bdd4-11e8-9220-a20ca874e796.png)
I found the lines it remind me, and corrected ‘targets’ to 'architect', run `ng add ng-zorro-antd` again, success!!
![image](https://user-images.githubusercontent.com/24146295/45878765-d8a1d100-bdd4-11e8-8fe9-4cf93423e5ba.png)

**Comment by Hassanramadan03** [comment]
what's the best version of angularMaterial compatible with angular 6 ?

**Comment by JigmeLodey** [comment]
./node_modules/@angular/material/__ivy_ngcc__/fesm2015/form-field.js
Module build failed: Error: ENOENT: no such file or directory, open '/root/Documents/lodey/project/node_modules/@angular/material/__ivy_ngcc__/fesm2015/form-field.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Storage.provideSync (/root/Documents/lodey/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:109:13)
    at CachedInputFileSystem.readFileSync (/root/Documents/lodey/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:289:32)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (/root/Documents/lodey/project/node_modules/@ngtools/webpack/src/webpack-input-host.js:35:51)
    at Observable._trySubscribe (/root/Documents/lodey/project/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/root/Documents/lodey/project/node_modules/@ngtools/webpack/node_modules/rxjs/internal/Observable.js:30:22)
    at SyncDelegateHost._doSyncCall (/root/Documents/lodey/project/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:22:20)
    at SyncDelegateHost.read (/root/Documents/lodey/project/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:49:21)
    at WebpackCompilerHost.readFileBuffer (/root/Documents/lodey/project/node_modules/@ngtools/webpack/src/compiler_host.js:165:44)
    at VirtualFileSystemDecorator.readFile (/root/Documents/lodey/project/node_modules/@ngtools/webpack/src/virtual_file_system_decorator.js:42:54)
    at processResource (/root/Documents/lodey/project/node_modules/loader-runner/lib/LoaderRunner.js:202:11)
    at iteratePitchingLoaders (/root/Documents/lodey/project/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at runLoaders (/root/Documents/lodey/project/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/root/Documents/lodey/project/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/root/Documents/lodey/project/node_modules/webpack/lib/NormalModule.js:446:15)

**Comment by SchnWalter** [comment]
I just tested `ng add @angular/material` using the latest Angular CLI in a brand new project and it worked just fine.

<details><summary>$ npx ng version // click for details</summary>
<pre>
Angular CLI: 9.1.7
Node: 12.16.1
OS: linux x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/material                 9.2.4
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
    
</pre>
</details>

The initial report is almost 2 years old and the last comment is unrelated. I think that this can be closed.

@JigmeLodey, you should never use the Angular CLI (or npm for that matter) while logged in as the `root` user. If you still encounter the error,  you should create a new issue, but make sure that you read the [Submission Guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

**Comment by mbaljeetsingh** [comment]
This actually works with the latest version of Angular. So closing it.
