### ISSUE TITLE
wildcard in angular.json

### ISSUE THREAD

**Issue by shahraship** [angular/angular-cli#10645]
### Versions
```
Angular CLI: 6.0.0
Node: 10.0.0
OS: darwin x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
* Create a new project
* Update angular.json file assets to include a wildcard entry like this: "assets": ["src/*.png"]
* Run ng serve

### Observed behavior
```
fs.js:110
    throw err;
    ^
Error: ENOENT: no such file or directory, stat '/User/myproj/src/*.png'
    at Object.fs.statSync (fs.js:914:3)
    at Observable.rxjs_1.Observable.obs [as _subscribe] 
```

### Desired behavior
Expect wildcard entries in angular.json file to be respected. It worked in earlier versions of angular/cli, stopped working in the latest release.

**Comment by hansl** [comment]
Hi @shahraship,

We do not support strings with glob as assets anymore, because they're ambiguous. For example, did you mean to copy those images to `dist/src` or `dist/`?

We still support the long form though, which includes a glob field. Take a look at the [documentation](https://github.com/angular/angular-cli/wiki/stories-asset-configuration).

Cheers!

**Comment by shahraship** [comment]
To answer your question, I'm trying to move these images to `dist/`
Thank you for pointing me to the documentation, it helps.

**Comment by shahraship** [comment]
By the way, I tried this  `{ "glob": "*.png", "input": "/src", "output": "/" }` as suggested in the document, and it doesn't copy over the resources

**Comment by jonrimmer** [comment]
We just ran into the same problem when using `ng update`. Wouldn't it be worth flagging a warning that the `angular.json` generated is invalid, and why?
