### ISSUE TITLE
ng update @angular/cli with `allowOutsideOutDir ` not working - Path is Invalid

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#10647]
### Versions
```

Angular CLI: 6.0.0
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      5.2.4
@angular/material                 5.2.4
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
* create an angular app with a src of `/src/client`
* create a folder `src/server` (this is where i could put a node server)
* add this to your `package.json` inside of `apps`, `assets`.

```
        {
          "glob": "**/*.*",
          "input": "../server/",
          "output": "../",
          "allowOutsideOutDir": true
        },
        {
          "glob": "package.json",
          "input": "../../",
          "output": "../",
          "allowOutsideOutDir": true
        }
```

* run `ng update @angular/cli`

### Observed behavior
```
▶ng update @angular/cli
            Updating karma configuration
            Updating configuration
Path "/../" is invalid.
```

### Mention any other details that might be useful (optional)
I removed those `allowOutsideOutDir` entries and it seems to work. But I think it should work with them.

cc @filipesilva

**Comment by johnpapa** [comment]
it seems `allowOutsideOutDir` has been removed.

i do not see any reference to it in the changelog.

Any guidance is appreciated.

**Comment by filipesilva** [comment]
I think we should both show a warning on the release notes, and also show a warning during `ng update` about those assets entries.

**Comment by devarg** [comment]
I also had bugs after executing update to upgrade from 1.7.4
I came to find that it is not finding anymore module 'Webpack' and it is not building in prod config

The workarounds are
To fix missing webpack import (shouldn't it be included in cli?)
```
 npm i webpack --save-dev 
```
To fix production builds
```
   npm i @angular-devkit/build-optimizer --save-dev
```
And everything works smoothly. However... when you build ng new app this libraries install both of build-optimizer and webpack even though they are not explicited in package.json what I assume is the correct behaviour.

My version is

```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0 (cli-only)
@angular-devkit/schematics        0.6.0 (cli-only)
@schematics/angular               0.6.0 (cli-only)
@schematics/update                0.6.0
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.7.0
```

My current dependencies are
```
  "dependencies": {
    "@angular/animations": "6.0.0",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",
    "argob-poncho": "^0.3.4",
    "bootstrap": "^4.0.0",
    "card": "^2.4.0",
    "core-js": "^2.5.4",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "moment": "^2.22.1",
    "ngx-card": "^0.2.4",
    "popper.js": "^1.14.3",
    "rxjs": "6.0.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.0",
    "@angular/cli": "~6.0.0",
    "@angular/compiler-cli": "^6.0.0",
    "@angular/language-service": "^6.0.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "~2.7.2",
    "webpack": "^4.7.0",
    "@angular-devkit/build-optimizer": "^0.6.0"
  }
```

Thanks!

**Comment by filipesilva** [comment]
@devarg I don't think your comment is related to the issue shown here by @johnpapa. Can you instead open a new issue? Thanks!

**Comment by filipesilva** [comment]
Added a `Breaking Changes` section to https://github.com/angular/angular-cli/releases/tag/v6.0.0, with this change listed.

**Comment by devarg** [comment]
@filipesilva I'm sorry you are right, build the issue has been moved to this thread 
[https://github.com/angular/angular-cli/issues/10649 ](url)

**Comment by istiti** [comment]
@johnpapa can you please search before open issue https://github.com/angular/angular-cli/issues/10350

It is not first time you open this one https://github.com/angular/angular-cli/issues/8122

While this already exist https://github.com/angular/angular-cli/issues/7773

Thanks

**Comment by ramandeep-singh-1983** [comment]
Since allowOutsideOutDir has been removed, what all options do i have? 
@johnpapa i followed your guide to setup my project and my server is in src/server directory and it gets packaged in dist/ directory and my client app gets packaged in dist/public directory. 

How can i migrate to Angular CLI 6.0.0 in this case when allowOutsideOutDir has been removed?
