### ISSUE TITLE
ng completion no longer exists

### ISSUE THREAD

**Issue by ethancane** [angular/angular-cli#10652]
Just updated to use the latest version of Angular CLI (6.0).

How to setup bash completion for the ng binary?

It used to be ng completion --bash >> .bashrc

..but now no longer.

Can this still be achieved?

Thanks

**Comment by martinstofko219** [comment]
I have noticed that as well after updating to 6.0. 

I went through the docs for the new CLI version but could not find any references to either the completion command or its removal. 

Thanks!

**Comment by jibbers42** [comment]
The release notes at https://github.com/angular/angular-cli/releases/tag/v6.0.0 says...
> The completion command has been removed as the functionality no longer aligns with this version.

I think this means it was out of sync and they didn't want to update it.

Perhaps the OP can re-pupose and re-title this issue as a feature request to re-implement completion?

**Comment by ninrod** [comment]
> Perhaps the OP can re-pupose and re-title this issue as a feature request to re-implement completion?``

I went ahead and did it: #11043

**Comment by clydin** [comment]
Closing as this is being tracked in the feature request issue above.
