### ISSUE TITLE
[6.0.0 Regression] build-optimizer breaks exports

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#10655]
### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.0
Node: 9.11.1
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* `git clone https://github.com/buu700/ng6-quill-test.git`
* `cd ng6-quill-test`
* `npm install .`
* `ng serve --prod`

This project is a small modification of `ng new`'s output which adds `import 'parchment';`. The relevant code within the `parchment` package is as follows:

```
src/registry.ts:

. . .
export enum Scope {
  . . .
  INLINE_BLOT = INLINE & BLOT, // 0110
  . . .
}
. . .


src/blob/abstract/leaf.ts:

. . .
import * as Registry from '../../registry';

class LeafBlot extends ShadowBlot implements Leaf {
  static scope = Registry.Scope.INLINE_BLOT;
. . .
```

### Observed behavior
Logged to console:
```
Uncaught TypeError: Cannot read property 'INLINE_BLOT' of undefined
```

### Desired behavior

As when building/serving without `--prod`, `Registry.Scope` should be defined.

### Mention any other details that might be useful (optional)

Disabling the build optimizer fixes the issue. I didn't run into this with 6.0.0-rc.7, so the regression is from some time between 6.0.0-rc.8 and 6.0.0 final.

**Comment by aripp** [comment]
Yes, that happens here too when I try to start my app that was built with command @ng build --base-href /AppPortal/ --prod.

**Comment by leocaseiro** [comment]
Thanks @aripp it worked for me too. The bundle is slighter bigger, but works for the time being.

For who wants to test using @angular/elements try my modified version:

```js
{
   "configurations":{
      "production":{
         "optimization":true,
         "outputHashing":"none",
         "sourceMap":false,
         "extractCss":false,
         "namedChunks":false,
         "aot":true,
         "extractLicenses":true,
         "vendorChunk":false,
         "buildOptimizer":false,
         "fileReplacements":[
            {
               "replace":"src/environments/environment.ts",
               "with":"src/environments/environment.prod.ts"
            }
         ]
      }
   }
}
```

cc https://github.com/angular/angular-cli/issues/7799

**Comment by leocaseiro** [comment]
See https://github.com/angular/devkit/issues/816

**Comment by andriykrasnychuk** [comment]
this workaround worked for me: 
`
export enum YourEnum {
    Prop1 = 'prop1',
    Prop2 = 'prop2',
}
`

**Comment by filipesilva** [comment]
Does this happen with the 6.1.x betas?

**Comment by buu700** [comment]
Although, I see that #10983 is using `@angular-devkit/build-optimizer@0.6.3`, so maybe they're different issues, and/or maybe this repro is insufficient? I'll try again in my actual project some time soon and see if that behaves any differently.

**Comment by dsoltesz** [comment]
I manually added "@angular-devkit/build-optimizer": "0.6.8" as dev dependency to package json and issue seems to be resolved with this version.

**Comment by buu700** [comment]
Can't reproduce the problem in @cyph either after upgrading to 6.1, so I'll close this again.

**Comment by Leanvitale** [comment]
Try for this..

> ng build --prod --optimization=false

**Comment by zernolo** [comment]
by this issue, seems that the build-optimizer is not working anymore https://github.com/valor-software/ngx-bootstrap/issues/4948

**Comment by filipesilva** [comment]
@zernolo can you open a new issue with a reproduction please?
