### ISSUE TITLE
unknown option -extractCss in 6.0.0 - this was previously working in 1.7.4

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#10666]
### Versions
```
Angular CLI: 6.0.0
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* ng new aaCLI --routing --style=scss
* ng serve --open --extract-css --vendor-chunk --common-chunk --named-chunks --verbose

### Observed behavior
```
Unknown option '-extractCss
```
### Desired behavior
The app builds and opens normally on localhost:4200
### Mention any other details that might be useful (optional)
If I remove --extract-css from the above example as shown below:
```
ng serve --open --vendor-chunk --common-chunk --named-chunks --verbose
```
The error changes to 
```
Unknown option: '--named Chunks'
```
The command will only work after I remove _**BOTH**_  `--extract-css` and `--named-chunks` parameters.

**Comment by mantyz** [comment]
@fmorriso You can add a serve rule to build architect

```json
"build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
           ---
          },
          "configurations": {
            "production": {
              ---
            },
            "serve": {
              "extractCss": true,
              "namedChunks": true,
              "vendorChunk": true,
              "commonChunk": true,
              "verbose": true
            }
          }
        },
```

Then change `serve->options->browserTarget->project-name:build` to `project-name:build:serve` 
```json
"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "open": true,
            "browserTarget": "<project-name>:build:serve"
          },
          "configurations": {
            "production": {
              "browserTarget": "ng-d3:build:production"
            }
          }
        }
```

And run `ng serve`

**Comment by ibraheemalkilanny** [comment]
I am geetting now (after applying above)

Data path "['build']" should NOT have additional properties(serve).
at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project]

**Comment by ibraheemalkilanny** [comment]
@mantyz Thanks, solved the problem for me

**Comment by fmorriso** [comment]
Please include some of these tips, such as creating a "serve" rule in angular.json, in some type of WikI entry, readme.md or releasenotes.md so that everyone can benefit from the information about how to upgrade from Angular-CLI version 1.7.4 to 6.x.   I did an extensive search prior to posting this issue and found no such information in any existing upgrade guides.
