### ISSUE TITLE
ng-serve is not working - Could not find module "@angular-devkit/build-angular"

### ISSUE THREAD

**Issue by DineshChopra** [angular/angular-cli#10661]
### Versions
ng : 6.0.0
node : v8.9.0
npm : 6.0.0
Operating System : macOS
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

I have created new project with angular-cli.
ng new testapp
cd testapp
npm install
ng serve

ng serve is not working. I found following error
```
Could not find module "@angular-devkit/build-angular" from "/Users/dic/workspace/projects/carpool".
Error: Could not find module "@angular-devkit/build-angular" from "/Users/dic/workspace/projects/carpool".
    at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:162:69)
    at DoOperator.call (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:159:22)
    at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
```

dic@dic.local [~/workspace/projects/carpool]$ ng --version

So request you to please help me to resolve that issue
### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by tomash970** [comment]
Same here:

Angular CLI: 6.0.0
Node: 10.0.0
Ubuntu 16.04

Could not find module "@angular-devkit/build-angular" from "/opt/lampp/htdocs/newp".
Error: Could not find module "@angular-devkit/build-angular" from "/opt/lampp/htdocs/newp".
    at Object.resolve (/opt/lampp/htdocs/newp/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/opt/lampp/htdocs/newp/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable.subscribe (/opt/lampp/htdocs/newp/node_modules/rxjs/internal/Observable.js:162:69)
    at DoOperator.call (/opt/lampp/htdocs/newp/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/opt/lampp/htdocs/newp/node_modules/rxjs/internal/Observable.js:159:22)
    at /opt/lampp/htdocs/newp/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/opt/lampp/htdocs/newp/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/opt/lampp/htdocs/newp/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/opt/lampp/htdocs/newp/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/opt/lampp/htdocs/newp/node_modules/rxjs/internal/operators/mergeMap.js:112:18)

**Comment by DineshChopra** [comment]
I remove my repo.
Create new project again `ng new testapp`
`cd testapp`
`npm install`
`ng serve`

Its working for me know, but dont know why its not working earlier. Either its a problem of angular-cli or its a problem of my system.

It waste my 3 hours.  So please clarify what exactly we have to do when we face that kind of issue.

**Comment by AhnpGit** [comment]
I encountered this issue when use `ng update` to upgrade from 5 to 6. After successfully upgraded, the app couldn't start

**Comment by Blair2004** [comment]
Same right here...  but have seen that the last CLI command to update : 
`rxjs-5-to-6-migrate -p src/tsconfig.app.json`

doesn't work as expected. Indeed that throw an error : 

```
Running the automatic migrations. Please, be patient and wait until the execution completes.
'C:\Users\Blair' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.
child_process.js:644
    throw err;
    ^

Error: Command failed: C:\Users\Blair Jersyer\AppData\Roaming\npm\node_modules\rxjs-tslint\node_modules\.bin\tslint -c C:\Users\Blair Jersyer\AppData\Roaming\npm\node_modules\rxjs-tslint\rxjs-5-to-6-migrate.json -p src/tsconfig.app.json --fix
```
Should probably mention that, my Windows username has a space between "Blair Jersyer", does it have anything to do with ?

**Comment by Blair2004** [comment]
@DineshChopra i've finally made this npm install @angular-devkit/build-angular and it worked. I'm wondering it sould be within the dev deps or not ?

**Comment by casoetan** [comment]
@Blair2004 it should be in dev deps (@angular-**devkit**).

**Comment by superstator** [comment]
Was running into this, and it ended up being a mismatch between the version of `rxjs` in `package-lock.json` and my installed version. Updated all my machines to 6.1 with `npm i -g rxjs` and am able to build and run again. Supremely unhelpful error message, though...

**Comment by shauvet** [comment]
You can try rm -rf node_modules then reinstall npm i. This works for me.

**Comment by superstator** [comment]
FWIW, I wasn't upgrading an old project. I started a brand new project over the weekend on one machine (Win 10) and then checked it out and attempted to run on another (MacOS High Sierra). Both have brand new node installs, and `@angular/cli` 6.0, I just somehow ended up with `rxjs` 6.0 on one and 6.1 on the other, and the build was apparently flummoxed by the mismatched version. 

I saw the crash both ways, too - the project was created with a reference to `rxjs` 6.0, and this crashed when I checked it out on the machine with `rxjs` 6.1. Somehow I managed to thrash around and upgrade the project without realizing it, and it started working on the 6.1 machine. Then I moved back to the original machine with 6.0 and it started crashing again, and I had to go take a break before I threw something out the window. I finally figured it out by nuking the entire project folder on the 6.0 machine, recreating from scratch with `ng new`, verifying that ran OK, and then stepping through the git diff until I narrowed it down to the `rxjs` version.

**Comment by krishragu12395** [comment]
I think RxJS v6 has major changes from v5, v6 brings backwards compatibility package rxjs-compat that will keep your applications working, but you should refactor TypeScript code so that it doesn't depend on rxjs-compat. For the same run following 
        npm install -g rxjs-tslint,
        rxjs-5-to-6-migrate -p src/tsconfig.app.json 
        npm uninstall rxjs-compat for. 
Then npm install --force for bypass the node-sass issues. You'll have a broken node-sass install but everything else will still work.
Now my existing angular 5 app is upgraded to angular 6.

**Comment by JoA-MoS** [comment]
I had the same issue I found that running the command to create the new project in PowerShell rather than Git Bash seemed to solve the problem for some reason.

**Comment by ken107** [comment]
I checked in `node_modules` and apparently only dependencies are installed, not devDependencies.  With the new NPM, we need to explicitly get the devDependencies:
`npm i --only=dev`

**Comment by sliceofbytes** [comment]
I recently helped someone debug this issue, problem ended up being an old yarn install he had forgotten about.

I had him uninstall yarn completely and attempt to `ng new test-app`

the next error made the problem obvious. 

`'yarn' is not recognized as an internal or external command,
operable program or batch file.
Package install failed, see above.`

Had him set angular-cli package manager back to npm.

`ng config -g cli.packageManager npm`

and everything worked. Hope this helps someone.

**Comment by lichunbin814** [comment]
I have the same issue with @ken107 , but I don't know why my NPM config had set to production if you have the same problem, you can check it by below command

Run ` npm config get production `

https://stackoverflow.com/a/35098833/7291379

**Comment by ikiong** [comment]
Have the same issue with `gitlab-ci`
```
Running with gitlab-runner 10.8.0-rc3 (5470b911)
  on docker-auto-scale 0277ea0f
Using Docker executor with image node:latest ...
Pulling docker image node:latest ...
Using docker image sha256:d17c9e1d584e713eef654f95c51b5c58d5a91cdf358ca40fe5157bfdbbab0d14 for node:latest ...
Running on runner-0277ea0f-project-6742411-concurrent-0 via runner-0277ea0f-srm-1528160870-333c7489...
Cloning repository...
Cloning into '/builds/kenyx/build-stacks'...
Checking out a5d95ddf as master...
Skipping Git submodules setup
Skipping cache extraction due to empty cache key
$ npm install -g --silent firebase-tools
/usr/local/bin/firebase -> /usr/local/lib/node_modules/firebase-tools/bin/firebase

If you're using the Emulator via the Firebase CLI, you can
disregard this message.

If you're upgrading @google-cloud/functions-emulator, these
are the recommended upgrade steps:

1.  Stop the currently running emulator, if any:

        functions stop

2.  Uninstall the current emulator, if any:

        npm uninstall -g @google-cloud/functions-emulator

3.  Install the new version of the emulator:

        npm install -g @google-cloud/functions-emulator

If you have trouble after upgrading, try deleting the config
directory found in:

    ~/.config/configstore/@google-cloud/functions-emulator

Then restart the emulator. You can also check for any renegade
Node.js emulator processes that may need to be killed:

    ps aux | grep node

+ firebase-tools@3.18.5
added 528 packages from 262 contributors in 32.338s
$ npm install -g @angular/cli
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@6.0.7 postinstall /usr/local/lib/node_modules/@angular/cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular/cli@6.0.7
added 246 packages from 188 contributors in 15.12s
$ ng build --prod
Could not find module "@angular-devkit/build-angular" from "/builds/kenyx/build-stacks".
Error: Could not find module "@angular-devkit/build-angular" from "/builds/kenyx/build-stacks".
    at Object.resolve (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (/usr/local/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/src/architect.js:132:40)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:162:69)
    at DoOperator.call (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:159:22)
    at /usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (/usr/local/lib/node_modules/@angular/cli/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
ERROR: Job failed: exit code 1
```
But I am pretty sure it works on my `local` and `travis-ci`.

**Comment by craviteja** [comment]
Please do below steps

1.run:  npm install @angular-devkit/build-angular
2. delete node_modules and package-lock.json (if you have one) 
3. And npm install again.

Its will be work perfectly.

**Comment by aeksco** [comment]
I got this working by moving a few things around in `package.json`

I moved the following from `devDependencies` into `dependencies`:

```
@angular-devkit/build-angular
typescript
@angular/compiler-cli
```

My particular issue was builds passing locally on my development machine, but failing in my Jenkins CI pipeline. Using `angular ^6.0.0`, codebase generated with `angular/cli` and I was trying to run `ng build`.  Moving those dependencies around seemed to do the trick, but I cannot speak to why those changes fixed the build

**Comment by nanoseconds** [comment]
All of the above answer are correct but they did not work for me. The only way I was able to make this work was by follow steps/commands
 
    ng new MY_PROJECT_NAME
    cp -r from_my_old_project to_new_MY_PROJECT_NAME

**Comment by princeV** [comment]
Another issue could be with your dev-dependencies.
Please check if they have been installed properly (check if they are availabe in the node_modules folder)

If not then a quick fix would be:

    npm i --only=dev

Or check how your npm settings are regarding prod:

    npm config get production

In case they are set to true - change them to false:

    npm config set -g production false

and setup a new angular project.

Found that hint here:
https://github.com/angular/angular-cli/issues/10661
(ken107 and lichunbin814)

Hope that helps.

**Comment by shivymehta98** [comment]
@Angular/cli 6.0.8 version : 
node -v :8.11.2
npm -v : 6.1.0
I was facing the below issue from 2 days and tried all possible solutions.

Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    
**Solution** : First confirm that you are there in a write folder where u have created a new file n downloaded angular.json .
Do ng serve
If still it doesn't work
 Look inside node_modules..You must have only dependencies are installed n v need devDependencies 
Type
npm i --only=dev

**Comment by NoahStevan** [comment]
I am having the same issue.
when checking my angular cli >ng -v
![angular-cli](https://user-images.githubusercontent.com/40655603/42152497-d9b7047c-7e12-11e8-9e77-84567f1dc276.jpg)


there is packages error, so i do @nanoseconds  does
```
npm unistall -g @angular/cli@6.0.8
npm cache clean --force
npm install -g @angular/cli@6.0.8
npm install node-sass -g
```
still not working. 
`npm ERR! Unexpected end of JSON input while parsing near '...browserstack-launch
er'`

**Comment by NoahStevan** [comment]
Thanks its working now.

**Comment by Madslick** [comment]
craviteja's answer worked for me

delete node_modules/ and package-lock.json 
npm install

all better

**Comment by soheshdoshi** [comment]
npm i -D @angular-devkit/core it's work

**Comment by Shubham246** [comment]
Tried all the options but worked only with **npm i --only=dev**

**Comment by Snedden** [comment]
Same prob here  tried all the above solution , had to make a new project

**Comment by rahimnagori** [comment]
I'm also facing the same issue : 
I installed and started a test app successfully.
I git push it from a machine.
Then I pulled it on another machine and now this issue occurs.

**Comment by shivymehta98** [comment]
You can go for "npm install" everytime whenever you git pull some another
app to your machine as the pushed code on the github is not having node
modules.

**Comment by jphustman** [comment]
A simple, `npm install` is what fixed this for me.

**Comment by felix20000** [comment]
I have the same issue. But i dont know how to fix it.

**Comment by shervinee** [comment]
> I have the same issue. But i dont know how to fix it.

Did you try the 3 fixes that are mentioned in this threat? I've had this issue with a couple of my projects and for each one the fixes worked.

**Comment by prashantubale5008** [comment]
npm i --only=dev
this worked for me

**Comment by RomanKlimov** [comment]
npm cache clean
npm install

worked for me

**Comment by FDiskas** [comment]
`npm ci`
