### ISSUE TITLE
Upgrade @angular/router to version 3.0.0

### ISSUE THREAD

**Issue by Trendy** [angular/angular-cli#1066]
Recently announced by @StephenFluin in [this blog post](http://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html), version 2.0 of @angular/router has been deprecated. angular-cli still installs version 2.0.0-rc.1, and it should upgrade to  version 3.0.0-alpha.3.

We should try to keep up with changes so that angular-cli projects do not fall behind the curve.

**Comment by mbeckenbach** [comment]
@Trendy 
You're absolutely correct. 

I tried angular-cli for the first time today, and that part was not funny. Not a happy start for me and angular-cli. :-)

Anyway this project is damn cool. Thank you for all the work that you guys put into it!

**Comment by vamsivarikuti** [comment]
I think the pull request #1077 resolves this

**Comment by Trendy** [comment]
This was resolved by #1077
