### ISSUE TITLE
ng update failed with angular 5 project generated by CLI 1.7.4

### ISSUE THREAD

**Issue by AhnpGit** [angular/angular-cli#10664]
### Versions
```
Your global Angular CLI version (6.0.0) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.4
Node: 8.11.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps
* Step 1: clone this repo example: https://github.com/AhnpGit/ng-update-error and run `yarn`
* Step 2: install @angular/cli 6.0.0 by `npm install -g @angular/cli`
* Step 3: cd to the cloned example and run `ng update`

### Observed behavior
An error occurs caused by `semver.intersects`
```
Your global Angular CLI version (6.0.0) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Error: semver.intersects is not a function
semver.intersects is not a function
```

### Desired behavior
Should update successfully

### Mention any other details that might be useful (optional)
**N.A**

**Comment by AlgoTrader** [comment]
I updated the @angular/cli to latest version manually. `npm install @angular/cli` does minor upgrades only

**Comment by hansl** [comment]
`ng update` is a CLI 6.0 only command. CLI 1.7.4 did have some support but we disabled it in 1.7.5 to avoid these kind of issues.

You'll need to follow the instructions at update.angular.io like @criduvero said. To make sure you're using CLI 6.0 locally, run `ng version`.

Running `yarn add @angular/cli` then `ng update @angular/cli` worked properly for me.

Closing this as non reproducible in 6.0.1.

**Comment by chriscurnow** [comment]
@hansl however it is a problem with the update instructions. Following the update instructions exactly does not work for CLI 1.7.4.

Specifically `npm install @angular/cli` does not upgrade CLI.

**Comment by AlgoTrader** [comment]
@chriscurnow you shoud aware `npm install @angular/cli` is absolutly not enough. 

The correct CLI update is 

```
npm install -g @angular/cli
npm install @angular/cli
ng update @angular/cli
```

**Comment by johnqiuwan** [comment]
@AlgoTrader , follow the instruction does not work for me.

What I did 

```
npm install -g @angular/cli
npm install @angular/cli
ng update @angular/cli
```

As @hansl mentioned, Following the update instructions exactly does not work for CLI 1.7.4.

**Comment by JohannesHoppe** [comment]
Similar issue here. I got the same feedback for one project (by mail), so I don't have the full error message:

```
npm install -g @angular/cli
npm install @angular/cli
ng update @angular/cli

Your global Angular CLI version (6.0.8) is greater than your local
version (1.5.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
module.js:549
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp7.1\htdocs\angular\Buch\book-monkey2\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

According to the error message, the local CLI wasn't updated. What could be the root of this issue? Anybody having a solid solution?

**Comment by JohannesHoppe** [comment]
see https://github.com/angular/angular-cli/issues/9307

**Comment by mikecabana** [comment]
Doing this...
`
npm install -g @angular/cli
npm install @angular/cli
npm intall
ng update @angular/cli
`
...fixed it for me.

**Comment by hbakir** [comment]
```
npm uninstall @angular/cli --save
npm install @angular/cli --save
ng update @angular/cli
```

...fixed it for me

**Comment by alvics** [comment]
//  Global package 
```
npm uninstall -g @angular/cli
npm cache verify
npm install -g @angular/cli@latest
```
// Local project package 
```
rm -rf node_modules dist // first remove node modules folder and dist (if applicable)
npm install --save-dev @angular/cli@latest
npm install
ng update @angular/cli
ng update @angular/core
```
