### ISSUE TITLE
HMR stories. `module` not defined

### ISSUE THREAD

**Issue by Dok11** [angular/angular-cli#10662]
https://github.com/angular/angular-cli/wiki/stories-configure-hmr

![image](https://user-images.githubusercontent.com/2697890/39662206-aec3944e-5066-11e8-90b3-73c8cc00e341.png)

**Comment by shyamal890** [comment]
+1

**Comment by sandangel** [comment]
you should add 'node' in types of tsconfig.app.json

**Comment by Dok11** [comment]
Yes, but in the documention about this no one word

**Comment by filipesilva** [comment]
Heya, just checked https://github.com/angular/angular-cli/wiki/stories-configure-hmr and now it lists adding the node typings as well.
