### ISSUE TITLE
Feature request: Disable test generation

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#1067]
I know unit and e2e tests are important. But in some cases - quick and dirty projects - you simply don't need it. There should be a parameter to "ng new" that disables the auto generation of any test files and simply create a project without any protractor or karma dependencies.

> ## Please provide us with the following information:
> 1. OS?  
>    Windows 10
1. Versions. 
   angular-cli: 1.0.0-beta.5
   node: 5.9.1
   os: win32 x64
2. Repro steps. 
   ng new whatever
3. The log given by the failure. 
   no failure

**Comment by delasteve** [comment]
Can be done with `ng g X --no-spec`.

**Comment by hansl** [comment]
Closing this as obsolete. @delasteve provided an answer.
