### ISSUE TITLE
Wiki: Continuous Integration Story: "Unknown option" errors

### ISSUE THREAD

**Issue by ersimont** [angular/angular-cli#10677]
### Versions
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0
Node: 8.9.2
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-ng-packagr   0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0
@schematics/update                 0.6.0
ng-packagr                         3.0.0-rc.2
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

### Repro steps

* Run this command from [the travis CI section of the wiki story for Continuous Integration](https://github.com/angular/angular-cli/wiki/stories-continuous-integration#using-travis-ci):
  `npm run e2e -- --no-progress --config=protractor-ci.conf.js`

### Observed behavior
Instead of running end-to-end tests, it prints this error:
```
> ng-app-state-platform@0.0.0 e2e S:\Programming\git repositories\ng-app-state
> ng e2e "--no-progress" "--config=protractor-ci.conf.js"

Unknown option: '--progress'
```

### Desired behavior
It should run the end-to-end tests.

### Mention any other details that might be useful (optional)
Removing the `--no-progress` flag causes it to complain that `--config` is an unknown option. This is also a problem for the line above it in the file: `npm run test -- --single-run --no-progress --browser=ChromeNoSandbox`

**Comment by Tataraovoleti** [comment]
I m getting similar issue with below command

 ng test --code-coverage --single-run

Unknown option: '--singleRun'

**Comment by JonnyBGod** [comment]
Fixed this by:
- create ```protractor-ci.conf.js``` file in e2e folder with:
```
const config = require('./protractor.conf').config;

config.capabilities = {
  browserName: 'chrome',
  chromeOptions: {
    args: ['--no-sandbox']
  }
};

exports.config = config;

```

- add **ci** configuration to angular.json app-e2e project
```
"app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "app:serve"
          },
          "configurations": {
            "ci": {
              "protractorConfig": "e2e/protractor-ci.conf.js"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": ["**/node_modules/**"]
          }
        }
      }
    },
```

- ```ng e2e -c ci```

**Comment by ersimont** [comment]
Update: after some experimentation, I've come close to making this work. The new equivalent of `--config=__` is `--protractor-config=___`. For the other command, the new equivalent of `--single-run` is `--watch=false`. I tried `--progress=false` in place of `--no-progress`, but I didn't notice any difference, so I just dropped the flag entirely. Here are my new lines:

```yaml
script:
  # Use Chromium instead of Chrome.
  - export CHROME_BIN=chromium-browser
  - xvfb-run -a yarn test --code-coverage --watch=false --browsers=ChromeNoSandbox
  - xvfb-run -a yarn e2e --protractor-config=e2e/protractor-ci.conf.js
```

The last line now works :tada:. However, the line above it still given an error:
```sh
Cannot load browser "ChromeNoSandbox": it is not registered!
```

**Comment by djhojd** [comment]
What I found is that your can run any command like `ng test` or `ng e2e` and add `--help` and it will print all the available options for v6 and I don't see anything related to progress, this flag has moved inside angular json file under `build-angular:dev-server` options.

@ersimont Tip: You don't need `xvfb` to run Chrome anymore, you can use the headless version like so `--browsers=ChromeHeadless` and if you also need the `no-sandbox` flag you can add a `customLaunchers` based from ChromeHeadless and add that flag
