### ISSUE TITLE
CLI --exports option not working for component generation

### ISSUE THREAD

**Issue by santonica** [angular/angular-cli#10678]
### Versions
6.0.0

Angular CLI: 6.0.0
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

### Repro steps

* Step 1 ng g c about --exports
* Step 2 check module file to see if about is registered under exports array.

### Observed behavior
No AboutComponent added to exports array

```

### Desired behavior
What would like to see implemented? Similar to adding component under declarations, it should be added to exports array.
What is the usecase? User of the CLI is trying to declare and export a generated component 
What did you expect to see? exports array populated with AboutComponent

**Comment by Brocco** [comment]
The option is `--export` (not "exports") you can read more about it [here](https://github.com/angular/angular-cli/wiki/generate-component).
