### ISSUE TITLE
ng e2e - wiki update

### ISSUE THREAD

**Issue by Bartosz-D3V** [angular/angular-cli#10671]
It is possible to pass proxy-config parameter when running ng e2e command like this:
``
ng e2e --proxy-config proxy.conf.json
``
This is the same parameter as when running ng serve command, nevertheless it is not documented in the wiki:
https://github.com/angular/angular-cli/wiki/e2e

I personally think that it would save some developers time, when configuring protractor to run against the real backend, that requires proxy.
If the missed argument in the wiki is desired - is there any reason not to pass the argument just like we do when running ng serve?

**Comment by mbark** [comment]
If anyone else stumbles on this wondering how to use a proxy for `e2e`-tests in Angular 6 then this is now done in the `angular.json` file by configuring the `serve` option used by your `e2e` tests `devServerTarget` and adding the `proxyConfig` to your `options`.

For example I have `e2e` tests for `angular-login` with the following configuration:
```
"angular-login-e2e": {
  "root": "e2e/",
  "projectType": "application",
  "architect": {
    "e2e": {
      "builder": "@angular-devkit/build-angular:protractor",
      "options": {
        "protractorConfig": "e2e/protractor.conf.js",
        "devServerTarget": "angular-login:serve"
      }
    }
  }
}
```
The `devServerTarget` option refers to `angular-login:serve` which is the webpack dev server which will be started.

What you want to do is to add the `proxyConf` option to that dev server. In my `angular-login`'s `serve` I have included `proxyConfig` under `options`, which will work the same way as before:
```
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "browserTarget": "angular-login:build",
    "proxyConfig": "proxy.conf.json",
  },
  "configurations": {
    "production": {
      "browserTarget": "angular-login:build:production"
    }
  }
}
```

**Comment by plurch** [comment]
Is it possible to set the value of `proxyConfig` dynamically? We are currently creating a dynamic proxy config file in a temp folder for CI runs.

**Comment by mbark** [comment]
@plurch would it work to create a symlink from `proxy.conf.json` to the dynamically created one in the temporary directory?

**Comment by plurch** [comment]
Thanks for the suggestion, @mbark . Seems like that would work. We decided to just overwrite the same `proxy.conf.json` file directly.

**Comment by sarathchand09** [comment]
thats works, THank you
