### ISSUE TITLE
'ng [command] --help' only shows content of 'ng' command

### ISSUE THREAD

**Issue by johren01** [angular/angular-cli#10682]
### Versions
```
angular cli 6.0.0
```

### Repro steps

* ng new [projectname]
* ng [generate] --help

### Observed behavior
```
Use of ng[command] --help does not display specific help prompts.
```

### Desired behavior
[command] --help navigates to more information on individual ng commands.

### Mention any other details that might be useful (optional)

Screenshot of issue
[https://drive.google.com/open?id=1ivfapn7CEMSbivOddDngatTocjzFS5W5](url)

**Comment by rmsmq** [comment]
Try `ng generate --help' instead. The square brackets are not part of the command.

**Comment by Brocco** [comment]
@rmsmq is right, the help section should be working just fine without using `[` and `]` around the command names.
