### ISSUE TITLE
ng build results in Uncaught Error: Can't resolve all parameters for

### ISSUE THREAD

**Issue by alexfung888** [angular/angular-cli#10685]
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
ng build
deploy or host with http-server
open using browser

### Observed behavior
```
application will produce at run time:
Uncaught Error: Can't resolve all parameters for [my service name] (?, ?)

does not happen with ng serve
```

### Desired behavior
I expect the application to run normally, like in `ng serve`

### Mention any other details that might be useful (optional)
Circumvention: change
```ts
  providers: [ AuthService ]
```
```ts
@injectable()
export class AuthService {
```
to, for each service
```ts
@injectable({providedIn: 'root'})
export class AuthService {
```

After this, application will complain at run time 

compiler.js:215 Uncaught Error: Can't resolve all parameters for HomeComponent: (?, ?, ?, ?).
    at syntaxError (compiler.js:215)

In order to circumvent that, I would need to add "@Inject()" to each dependency of every component. This is a lot of work and I have only manually updated one of them.

I also submitted an issue to angular
https://github.com/angular/angular/issues/23734
but I think this is probably a cli issue instead.

**Comment by gioragutt** [comment]
Can you provide a working [Stackblitz](https://stackblitz.com/) repro?

It's not possible to understand from your explanation what's going wrong.

**Comment by alexfung888** [comment]
stack trace first. My AuthService has exactly two dependency injected.

Uncaught Error: Can't resolve all parameters for AuthService: (?, ?).
    at syntaxError (compiler.js:215)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (compiler.js:10810)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (compiler.js:10703)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getInjectableTypeMetadata (compiler.js:10925)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getProviderMetadata (compiler.js:10934)
    at compiler.js:10872
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getProvidersMetadata (compiler.js:10832)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:10551)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleSummary (compiler.js:10381)

**Comment by gioragutt** [comment]
@alexfung888 did you manage to reproduce it in a stackblitz project? this might help you point out differences between a clean project and yours...

**Comment by alexfung888** [comment]
@gioragutt I am still trying to cut small the project. it will demonstrate both the provide problem for service and DI problem for components.

I haven't used stackblitz before so I need to learn how to.

If stackblitz is like plunker, it won't work. The problem does not appear when you ng serve it. You need to build and host the /dist with an http server to get the run time error.

finally, error only when built without --aot. if you ng build --aot, then there is no error.

**Comment by alexfung888** [comment]
@gioragutt I've cut the project into a small one, but neither stackblitz nor plunker allows me to upload a project. Dragging files into stackblitz is not successful either. 

[Please download the project from here](http://alexfung.info/cli.issue.10685.zip). It is a 354k zip file containing the project source. `yarn` it. 

Read the `readme.md`. It describes how to hit three different errors.

Remember you need to `ng build`, and without `--aot`. `ng serve` never fails. Nor `ng build --aot`.

**Comment by alexfung888** [comment]
I located the problem. My error. I have missed one line in the `polyfills.ts`:

```ts
/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';
```

I have been using `--dev --aot` in all my build commands until now, so I never noticed the import is missing. Now that I need to remove `--dev` from my scripts (or else it fails), I also tried removing `--aot` and ran into the problem.

Sorry for having asked a question caused by my mistake.

**Comment by lucasdobson88** [comment]
That resolved the issue for me as well :)

**Comment by jddeltoro** [comment]
@alexfung888 Your solution also solve my problem, thankyou.

**Comment by southnick92** [comment]
damn this actually worked for me too, by just simply injecting that line into the polyfill.ts. THANK YOU!!!!
