### ISSUE TITLE
e2e: Unknown option: '--configuration'

### ISSUE THREAD

**Issue by rokerkony** [angular/angular-cli#10699]
### Versions
```
Angular CLI: 6.0.0
Node: 10.0.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* Create new cli project
* Add configuration section as follow to `"<PROJECT_NAME>-e2e": {`:
    ```
    "configurations": {
        "ci": {
            "serve": "false"
        }
    }
    ```
* run `ng e2e --configuration=ci`

### Observed behavior
```
Unknown option: '--configuration'
```

### Desired behavior
`e2e` should support configuration

### Mention any other details that might be useful
Unfortunatelly it is not only about `--configuration` but it doesn't respect also serve `ng e2e --serve=false` will still serve the app

**Comment by markgoho** [comment]
It looks like the [build file](https://github.com/angular/devkit/blob/master/packages/angular_devkit/build_angular/src/protractor/index.ts#L25-L35) options object is missing `serve` and `configuration`

**Comment by filipesilva** [comment]
Heya, the `serve` option is actually replaced with `devServerTarget`. If you set it to `''` it will not be served. https://github.com/angular/devkit/pull/876 should fix the `serve` option being erroneously accepted.

https://github.com/angular/angular-cli/pull/10763 should fix `--configuration` not working with `ng e2e`.

**Comment by filipesilva** [comment]
I also updated https://github.com/angular/angular-cli/releases/tag/v6.0.0 to show this breaking change.

**Comment by dethstrobe** [comment]
Is there a way to have the configurations for the e2e swap the environment variables?

I tried adding something like 

```
                        "test": {
                            "fileReplacements": [{
                                "src": "src/environments/environment.ts",
                                "replaceWith": "src/environments/environment.test.ts"
                            }, {
                                "src": "src/environments/config.scss",
                                "replaceWith": "src/environments/config.test.scss"
                            }]
                        }
```

but it outputs 

```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(fileReplacements).
```

So instead I try and replace the `devServerTarget` with my test config from my server like

```
                        "test": {
                            "devServerTarget": "mxc:serve:test"
                        }
```

But it doesn't like that either and outputs: 

```
Unknown option: '--configuration'
```

Anyway, I'd like to be able to run my e2e tests against other environments before deploying to them. Is the only way to get around this is to create an e2e project for each environment?

**Comment by rokerkony** [comment]
@dethstrobe `--configuration` is already working on v6.0.1 (and `@angular-devkit/build-angular@0.6.1`)

**Comment by dethstrobe** [comment]
Thanks @rokerkony that is it. I just needed that small version bump. Thanks

**Comment by JounQin** [comment]
@filipesilva https://github.com/angular/angular-cli/wiki/e2e should be updated about these changes.
