### ISSUE TITLE
ng build replaces HTML entities with the escaped value

### ISSUE THREAD

**Issue by luisabreu** [angular/angular-cli#10696]
Angular CLI: 6.0.0
Node: 10.0.0
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

The index.html page (index page of the project) ahs the following title:

<title>Ve&iacute;culos</title>

After running the following command:

ng build --prod --aot --base-href ~/views/dist/

The HTML entity is replace by it's value in the destination folder (instead of keeping the escaped value):

<title>Veículos</title>

I'm almost positive that this didn't happen in the previous releases...

**Comment by clydin** [comment]
Are you considering this a defect?  This appears to function properly in a web browser.

**Comment by luisabreu** [comment]
well, is there any justification for replacing the HTML entity with its value on the file that is copied to the dist folder? Loading in the browser ends up showing "veÃ­culos" instead of "veículos"...maybe it's related with the file's encoding?
