### ISSUE TITLE
angular-cli 6  ng build --prod  no minify or uglify

### ISSUE THREAD

**Issue by mrjohnr** [angular/angular-cli#10705]
Hi. Using angular-cli 6 
` ng build --prod `
does  no minify or uglify

test also with  

```
ng build --target=production --environment=prod
ng build --prod --env=prod

```

same problem,
thanks

```
Angular CLI: 6.0.0
Node: 10.0.0
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
angular-devkit/architect         0.6.0
angular-devkit/build-angular     0.6.0
angular-devkit/build-optimizer   0.6.0
angular-devkit/core              0.6.0
angular-devkit/schematics        0.6.0
ngtools/webpack                  6.0.0
schematics/angular               0.6.0
schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

**Comment by mrjohnr** [comment]
Hi,thanks:
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "rez": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/rez",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css",
			   "./node_modules/bootstrap/dist/css/bootstrap.css",
               "./node_modules/font-awesome/css/font-awesome.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "rez:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "rez:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "rez:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "rez-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "rez:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "rez"
}
```

**Comment by mrjohnr** [comment]
Hi.file is attached.thanks
[angular.zip](https://github.com/angular/angular-cli/files/1984074/angular.zip)

**Comment by mrjohnr** [comment]
any fix? thanks

**Comment by Matmo10** [comment]
Site note: My js bundles are minified/uglified, but I noticed that my index.html is no longer minifed (whitespace removed) during prod builds.

**Comment by mrjohnr** [comment]
all project js files  contains also comments and white spaces  :(

**Comment by clydin** [comment]
Please provide the console output of both `ng build` and `ng build --prod`.

**Comment by rodneyjoyce** [comment]
Can someone confirm what the --prod flag is doing? 

I want to target a configuration of X but with everything else identical to the prod buid (e.g. AOT) but using the X environment file. The ng build documentation does not go into detail what --prod does.

**Comment by clydin** [comment]
`--prod` is shorthand for and equivalent of `--configuration=production`.

**Comment by rodneyjoyce** [comment]
Ok, thanks, but I thought that targeting prod was also implicitly setting some build flags for optimal optimisation.

So say I want to build an exact mirror of Prod, but pointing at a Test configuration file which has Prod = true and the test api; maybe something like this?

ng build --configuration test --aot --build-optimizer

**Comment by BergerLand** [comment]
AS of July 12, 2018 I am still having the issue of my bundles not minified/uglified with a configuration defined for production.

**Comment by vl-lapikov** [comment]
This comment helped me to enable optimization https://github.com/angular/angular-cli/issues/10807#issuecomment-388452249

**Comment by Leanvitale** [comment]
Try for this..
> ng build --prod --optimization=false

**Comment by alan-agius4** [comment]
Closing as it looks like the issue has been solved with https://github.com/angular/angular-cli/issues/10807#issuecomment-388452249

**Comment by rt012** [comment]
> Hi. I'm getting this error ... I don't know what's causing it ... but if I set the `optimization = false` the error won't come up.
> ![optimizing error](https://user-images.githubusercontent.com/42328653/51025014-f84c4780-15c5-11e9-9ea8-a05223a1029e.png)
> Can someone help me with this?

try to downgrade tether to  "tether": "1.4.3", or 1.4.4 .. this fixed this problem in my case

**Comment by jmortega13** [comment]
> > Hi. I'm getting this error ... I don't know what's causing it ... but if I set the `optimization = false` the error won't come up.
> > ![optimizing error](https://user-images.githubusercontent.com/42328653/51025014-f84c4780-15c5-11e9-9ea8-a05223a1029e.png)
> > Can someone help me with this?
> 
> @jmortega13 try to downgrade tether to "tether": "1.4.3", or 1.4.4 .. this fixed this problem in my case

Hi! thanks for your help. I have resolved this recently. The problem was just in our code structure. Thanks!

**Comment by leogilardi6** [comment]
> > > Hi. I'm getting this error ... I don't know what's causing it ... but if I set the `optimization = false` the error won't come up.
> > > ![optimizing error](https://user-images.githubusercontent.com/42328653/51025014-f84c4780-15c5-11e9-9ea8-a05223a1029e.png)
> > > Can someone help me with this?
> > 
> > 
> > @jmortega13 try to downgrade tether to "tether": "1.4.3", or 1.4.4 .. this fixed this problem in my case
> 
> Hi! thanks for your help. I have resolved this recently. The problem was just in our code structure. Thanks!

Hi! I'm having the same problem, do you remember what kind of structures make that problem appear?
Thanks in advance!

**Comment by jmortega13** [comment]
> > > > Hi. I'm getting this error ... I don't know what's causing it ... but if I set the `optimization = false` the error won't come up.
> > > > ![optimizing error](https://user-images.githubusercontent.com/42328653/51025014-f84c4780-15c5-11e9-9ea8-a05223a1029e.png)
> > > > Can someone help me with this?
> > > 
> > > 
> > > @jmortega13 try to downgrade tether to "tether": "1.4.3", or 1.4.4 .. this fixed this problem in my case
> > 
> > 
> > Hi! thanks for your help. I have resolved this recently. The problem was just in our code structure. Thanks!
> 
> Hi! I'm having the same problem, do you remember what kind of structures make that problem appear?
> Thanks in advance!

It was a very long story.
@leogilardi6 Recursive structure of function in js/ts files caused that error in our project. What l did was I removed all the imported js/ts files in manifest.ts and built it again then the error no longer appeared and after that, I individually re-imported the js/ts files to find out which file caused the error, once I found out which file caused the error, I scanned inside the js/ts file. That's how I found out that there's a `recursive structure` of function inside the js/ts file.

e.g.:

```
function func1() {

      func2();

      function func2 {
          func1(); // What happened here is that it's calling it's parent function
      }
}
```
What I did was I pulled out the func2() outside

```
function func1() {

      func2();
}

function func2 {
     func1();
}
```

**Comment by leogilardi6** [comment]
> > > > > Hi. I'm getting this error ... I don't know what's causing it ... but if I set the `optimization = false` the error won't come up.
> > > > > ![optimizing error](https://user-images.githubusercontent.com/42328653/51025014-f84c4780-15c5-11e9-9ea8-a05223a1029e.png)
> > > > > Can someone help me with this?
> > > > 
> > > > 
> > > > @jmortega13 try to downgrade tether to "tether": "1.4.3", or 1.4.4 .. this fixed this problem in my case
> > > 
> > > 
> > > Hi! thanks for your help. I have resolved this recently. The problem was just in our code structure. Thanks!
> > 
> > 
> > Hi! I'm having the same problem, do you remember what kind of structures make that problem appear?
> > Thanks in advance!
> 
> It was a very long story.
> @leogilardi6 Recursive structure of function in js/ts files caused that error in our project. What l did was I removed all the imported js/ts files in manifest.ts and built it again then the error no longer appeared and after that, I individually re-imported the js/ts files to find out which file caused the error, once I found out which file caused the error, I scanned inside the js/ts file. That's how I found out that there's a `recursive structure` of function inside the js/ts file.
> 
> e.g.:
> 
> ```
> function func1() {
> 
>       func2();
> 
>       function func2 {
>           func1(); // What happened here is that it's calling it's parent function
>       }
> }
> ```
> What I did was I pulled out the func2() outside
> 
> ```
> function func1() {
> 
>       func2();
> }
> 
> function func2 {
>      func1();
> }
> ```

Hi! thanks for reply, ok, I'll look if I have something like that on my code. It seems like it's something different, but just in case..

Thank for the info!
