### ISSUE TITLE
CLI -Workspace

### ISSUE THREAD

**Issue by DevinathS** [angular/angular-cli#10709]
Angular-cli 6 does not have commands to create a workspace having multiple projects?
Because configuring the angular.json file won't beneficial as earlier angular-cli.json also supports configuration by adding multiple apps.

Existing 
------------------------
When we create a new project using ng new <project-name> it's creating a new project with some predefined folder structure. As per the documentation of CLI, we can customize angular.json with multiple projects.

Expected
--------------------------
Can't we have command to create top level workspace with the feasibility of having separate directory for each project  and the common component directories which can be shared between multiple projects similar to the one which NRWL is providing(https://nrwl.io/nx).

**Comment by zverbeta** [comment]
All commands available in cli, but wiki empty, i check it. 

`ng generate application myapp` it's command create `packages` folder in root directory

**Comment by TauseefMalik** [comment]
I wish to create empty project using Angular CLI 6. I used createApplication/minimal flags but still it created the entire sample app structure.

**Comment by alan-agius4** [comment]
Hi @DevinathS and @TauseefMalik, `ng new my-workerspace --no-create-application`, will create an empty workspace without an application scaffolding.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
