### ISSUE TITLE
Network request initiator

### ISSUE THREAD

**Issue by RayLuxembourg** [angular/angular-cli#10718]
Is it possible to see who made the request?

for example here it says zone.js did it but i would love to see the component that did the request.

![image](https://user-images.githubusercontent.com/15327989/39743301-248eb28c-52a9-11e8-8d5b-fc9b7f4990d7.png)

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
