### ISSUE TITLE
Remove # from angular 5 APP URL In production mode 

### ISSUE THREAD

**Issue by Divya2894** [angular/angular-cli#10719]
Hello ,

In my project, I m using angular 5
When i deploying my project my step is
1) ng build
2) ng build --prod
3) add expressjs
4) add server.js file

but  when serve the project on server at time app run successfully. but when i hit F5(reload the page). Its give me "Cannot GET /home" msg and page is empty.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
