### ISSUE TITLE
ng test not obeying single run flag

### ISSUE THREAD

**Issue by jwa107** [angular/angular-cli#10711]
### Versions
```
Angular CLI: 6.0.0
Node: 10.0.0
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cdk                      6.0.1
@angular/material                 6.0.1
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
* Upgrade Angular CLI to V6 (global/local)
* Upgrade Angular to V6
* Upgrade other dependencies
* Ensure karma.conf.js has `singleRun: false` in it
* Run `ng t` OR run `ng t --single-run=false`

### Observed behavior
If `ng t` is run, tests will run successfully but browser window will close on finish (despite karma.conf.js having `singleRun: false` inside it)

If `ng t --single-run=false` is run, it errors: `Unknown option: '--singleRun'` Note that running  `ng t --no-single-run` creates the same error. 
### Desired behavior
I would like the browser window to remain open, as it always did, pre-upgrade

**Comment by Ratikant01** [comment]
Same issue here as well, any fix?

**Comment by JohannesHoppe** [comment]
Same here, any solutions? It's a bit urgent.

**Comment by JohannesHoppe** [comment]
This works:

`ng test --watch`

Cheers!

**Comment by WizardPC** [comment]
Same here

**Comment by JohannesHoppe** [comment]
@Tataraovoleti Sure, `ng test --watch --code-coverage` gives me watch-mode and code-coverage. It's located in './coverage'

**Comment by Tataraovoleti** [comment]
Can you please provide me your karma.conf.js configuration

**Comment by JohannesHoppe** [comment]
It's the default:

```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, 'coverage'), reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

**Comment by Tataraovoleti** [comment]
Hi @JohannesHoppe 
Thank you , this configuration is working for me.

**Comment by mmenik** [comment]
I created a new project with Angular CLI 6.0, I have not modified the Karma configuration file.
I confirm that when the test ends google closes

 ng test --watch is a workaround, we wait for fix, thks

**Comment by Tataraovoleti** [comment]
is `ng test --single-run` is equivalent to `ng test ` now in angular6? 
I observed same behavior.

**Comment by jordanpowell88** [comment]
I'm experiencing same issue after upgrading. ng test --watch works like ng test did before upgrade. Is this the expected behavior?

**Comment by clydin** [comment]
@jwa107 This should be corrected in 6.0.1.  The `singleRun` karma option is only changed if the watch option is explicitly used. The single run command line flag no longer exists in v6.

If issues still presents with the latest version of the CLI, please open a new issue detailing the problem.

**Comment by rkrisztian** [comment]
`--no-watch` should also work (more elegant).

**Comment by pumano** [comment]
I switch `ng test --single-run=false` to `ng test --watch=false` and it is works good.

**Comment by Dewald15** [comment]
Since we cannot specify overrides, like "ng test --watch=false" if there are "multiple targets", is there another way to keep the browser window(s) open? Is it possible to append the next project's spec text to the browser window, or to log each project's spec text (like it was)?

**Comment by chrillewoodz** [comment]
`ng test --watch=false` doesn't work with Angular CLI `7.0.1`, it still watches and can't be killed unless you spam ctrl + c about 15 times quickly..

**Comment by mahcr** [comment]
Same result in `@angular/cli@7.1.0` and actually it looks like the test runs twice
