### ISSUE TITLE
Invalid JSON character when running ng update @angular/cli

### ISSUE THREAD

**Issue by cado1982** [angular/angular-cli#10715]
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2
```

### Repro steps
* npm install -g @angular/cli
* npm install @angular/cli@latest
* ng update @angular/cli

### Observed behavior
```
Invalid JSON character: "﻿" at 0:0.
```

### Desired behavior
Configuration should be migrated to the new angular.json format. If there is a problem, an understandable error message should be shown.

### Mention any other details that might be useful (optional)
.angular-cli.json
```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "<removed>"
  },
  "apps": [
    {
      "root": "Client",
      "outDir": "wwwroot",
      "assets": [
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "<removed>",
      "styles": [
        "../node_modules/@clr/icons/clr-icons.min.css",
        "../node_modules/@clr/ui/clr-ui.min.css",
        "../node_modules/font-awesome/css/font-awesome.css",
        "../node_modules/ng2-toastr/bundles/ng2-toastr.min.css",
        "../node_modules/tether-drop/dist/css/drop-theme-arrows.css",
        "../node_modules/tether-drop/dist/css/drop-theme-arrows-bounce.css",
        "styles.scss"
      ],
      "scripts": [
        "../node_modules/@webcomponents/custom-elements/custom-elements.min.js",
        "../node_modules/@clr/icons/clr-icons.min.js",
        "../node_modules/tether/dist/js/tether.min.js",        
        "../node_modules/tether-drop/dist/js/drop.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "protractor.conf.js"
    }
  },
  "lint": [
    {
      "files": "Client/**/*.ts",
      "project": "tsconfig.app.json"
    },
    {
      "files": "Client/**/*.ts",
      "project": "tsconfig.spec.json"
    },
    {
      "files": "Client/**/*.ts",
      "project": "e2e/tsconfig.e2e.json"
    }
  ],
  "test": {
    "karma": {
      "config": "karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "scss",
    "serve": {
      "ssl": true,
      "sslCert": "server.cert",
      "sslKey": "server.key"
    },
    "component": {}
  }
}

```

**Comment by Swellenator** [comment]
I have the same issue as mentioned over  at #10396

**Comment by YoannBureau** [comment]
Same here

**Comment by cado1982** [comment]
@YoannBureau @Swellenator I managed to get this fixed. I simply opened my .angular-cli.json file in notepad++ and clicked Convert to UTF-8 from the Encoding menu before saving the file. Running ng update @angular/cli now works as expected. There must have been a hidden BOM at the start of the file.

**Comment by chrismbarr** [comment]
@cado1982's answer worked for me!

 My `.angular-cli.json` was open in VSCode as a "UTF8 with BOM" encoding, but changing to to be "UTF8" and then running `ng update @angular/cli` finally worked and upgraded me as expected.

For those not familiar, in VSCode on the bottom toolbar on the right is shows the file encoding.  Click this to show a menu to change it.

**Comment by tomvanoost** [comment]
@martindevos I fixed the issue by converting some more .json files (tsconfig, etc.) to UTF8.

**Comment by Swellenator** [comment]
@cado1982 `.angular-cli.json` was in UTF8, but `tslint.json` was UTF8 with BOM - I made it UTF8 and can finally progress. The problem was `tslint.json`.

**Comment by martindevos** [comment]
After converting all of my .json files to UTF8 (without  BOM) as Tom suggested, it finally worked. Thanks alot !

**Comment by JoostvdB94** [comment]
It would however be nice when angular-cli shows the file with the JSON error :)

**Comment by Ventzy** [comment]
I got the same error with ng g library. I didn't had any encoding issues, however I had one excessive comma in tsconfig.json, which made it invalid json.

**Comment by duard** [comment]
I got the same problem, and I try everything and it dont work yet :-( 

`Invalid JSON character: "\"" at 3:6.
`

**Comment by FrankiePo** [comment]
I had the same issue
Solved by removing comments form `tsconfig.json`

**Comment by Tyler-V** [comment]
I'll second Ventyz's comment, ng g lib seems to add an additional entry for package_name/* which I keep removing when I generate new libraries, make sure the last element isn't trailing with an extra comma.

**Comment by azollai** [comment]
I had the same as @FrankiePo , I just got a comma at the end of an object in tsconfig.json.
I think you should check your tsconfig.json, with e.g. https://jsonlint.com/ . 
Good luck.

**Comment by ryanbasnet** [comment]
@Swellenator 's solution worked for me.

**Comment by krishna1990fis** [comment]
@chrismbarr I have tried everything you mentioned, i cross checked all the files ( **angular.json, package.json, tsconfig.json, tslint.json etc** )  for their encoding at the right bottom of the VS Code, they all are in UTF-8 format and i could not see any other way to fix this issue.  

I am trying to migrate my angular application from angular 6 to angular 7, and when i try executing following command in the terminal, i get below error

**Command:**
`ng update @angular/cli @angular/core`

**Error:**
`Unexpected token < in JSON at position 0
<html>
  <head>
    <title>npm Enterprise</title>
    <link rel="stylesheet" media="all" href="/main.css">
  </head>
  <body>
    <div class="container narrow">

  <hgroup>
    <h1>login</h1>
    <h2>ohai</h2>
  </hgroup>


  <form action="/login" method="post">
      <label for="name">username</label>
      <input type="text" id="name" name="name" required="required" autocorrect="off" autocapitalize="off" autofocus="">

      <label for="password">password</label>
      <input type="password" id="password" name="password" required="required">

    <input type="hidden" name="_csrf" value="hTNoOm9L-w3KF-KwoFNLpbsMR4j4WAWH06zA">

    <input type="submit" class="full-width" value="login">
  </form>

</div>

  </body>
</html>`

**Comment by N1nJaC0d3** [comment]
> @martindevos I fixed the issue by converting some more .json files (tsconfig, etc.) to UTF8.

same here ! :)
