### ISSUE TITLE
Is there any thing like module reload/refresh concept in angular???

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#10720]
i have requirement like i will load modules only once and when ever i need i can reload/refresh the modules without destroying the modules

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
