### ISSUE TITLE
scss @import relative path not working V6

### ISSUE THREAD

**Issue by RayLuxembourg** [angular/angular-cli#10721]
I used to do
`@import "~mixins.scss";`

Now this doesn't work and i have to do this.

`@import "../../../mixins.scss";`

**Comment by clydin** [comment]
The use of the tilde is a webpack specific capability; and, as webpack is an internal implementation detail that is not guaranteed to be used, the general recommendation is to avoid the use of the tilde to ensure forward compatibility.
