### ISSUE TITLE
assets kept in public is not properly ported to dist.

### ISSUE THREAD

**Issue by a5hik** [angular/angular-cli#1072]
There are several problems using assets in public folder.
I have an assets folder inside public to keep images and _scss files.

1. The images kept are copied to dist/assets/ not dist/public/assets
2. The scss files are copied in dist/assets 

Why there is an duplicate folder created and why the scss are copied to dist.
How do I port my images then?

**Comment by JonCubed** [comment]
whatever is in the *public* should be copied into your output path (*dist/* by default). So you should be expecting *public/assets* to be copied to *dist/assets*

if you wanted your images to be @ *dist/public/assets* then you should put them @ *public/public/assets*

**Comment by filipesilva** [comment]
Yeah need to add some documentation about the public dir, this behaviour is a bit confusing.

**Comment by filipesilva** [comment]
Closed as obsolete due to #1455. Documentation about the public dir is still needed but being tracked in https://github.com/angular/angular-cli/issues/339
