### ISSUE TITLE
feature request: Make node-sass as Optional dependency

### ISSUE THREAD

**Issue by changhuixu** [angular/angular-cli#10738]
After upgrade angular apps to version 6, our CI build process has trouble. 

In Angular 5.2, node-sass is an optional dependency for cli. We skip install node-sass because we are not using it AND the post installation step of node-sass is painful because our build server (via teamcity) is not allowed to access outside internet. 

In Angular 6.0, node-sass is no longer an optional dependency and is required by @angular-devkit/build-angular.

Is it possible to set node-sass as an optional dependency?
Thank you.

**Comment by kdekooter** [comment]
@clydin Still a required dependency in the latest release of angular-cli (7.1). Please reopen this issue.
