### ISSUE TITLE
Cannot Install AngularCli

### ISSUE THREAD

**Issue by xTheDoctah** [angular/angular-cli#10734]
###Version
NPM : 1.4.21
NodeJS: 8.11.1
Linux : Linux DESKTOP-GRRJH7U 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1 (2018-04-29) x86_64 GNU/Linux

###Command 
 sudo npm install -g @angular/cli (Tried first without and next with sudo, same errror.

###Error 
npm ERR! git clone git@github.com:angular/cli Clone nel repository spoglio '/root/.npm/_git-remotes/git-github-com-angular-cli-515723dd'...
npm ERR! git clone git@github.com:angular/cli Permission denied (publickey).
npm ERR! git clone git@github.com:angular/cli fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:angular/cli 
npm ERR! git clone git@github.com:angular/cli Please make sure you have the correct access rights
npm ERR! git clone git@github.com:angular/cli and the repository exists.
npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT: no such file or directory, stat 'angular/cli'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.9.0-6-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@angular/cli"
npm ERR! cwd /home/xthedoctah
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! path angular/cli
npm ERR! syscall stat
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xthedoctah/npm-debug.log
npm ERR! not ok code 0

###NPM LOG
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@1.4.21
3 info using node@v8.11.1
4 verbose cache add [ '@angular/cli', null ]
5 verbose cache add name=undefined spec="@angular/cli" args=["@angular/cli",null]
6 verbose parsed url Url {
6 verbose parsed url   protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: '@angular/cli',
6 verbose parsed url   path: '@angular/cli',
6 verbose parsed url   href: '@angular/cli' }
7 verbose cache add name="" spec="angular/cli" args=["","angular/cli"]
8 verbose parsed url Url {
8 verbose parsed url   protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'angular/cli',
8 verbose parsed url   path: 'angular/cli',
8 verbose parsed url   href: 'angular/cli' }
9 silly lockFile 5cecaa1c-angular-cli angular/cli
10 verbose lock angular/cli /root/.npm/5cecaa1c-angular-cli.lock
11 info maybeGithub Attempting angular/cli from git://github.com/angular/cli
12 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
13 verbose lock git://github.com/angular/cli /root/.npm/057ccbdd-git-github-com-angular-cli.lock
14 verbose addRemoteGit [ 'git://github.com/angular/cli', 'master' ]
15 verbose git clone git://github.com/angular/cli Clone nel repository spoglio '/root/.npm/_git-remotes/git-github-com-angular-cli-057ccbdd'...
15 verbose git clone git://github.com/angular/cli fatal: remote error:
15 verbose git clone git://github.com/angular/cli   Repository not found.
16 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
17 silly lockFile 057ccbdd-git-github-com-angular-cli git://github.com/angular/cli
18 info maybeGithub Attempting angular/cli from git+ssh://git@github.com:angular/cli
19 silly lockFile 515723dd-git-github-com-angular-cli git@github.com:angular/cli
20 verbose lock git@github.com:angular/cli /root/.npm/515723dd-git-github-com-angular-cli.lock
21 verbose addRemoteGit [ 'git@github.com:angular/cli', 'master' ]
22 error git clone git@github.com:angular/cli Clone nel repository spoglio '/root/.npm/_git-remotes/git-github-com-angular-cli-515723dd'...
22 error git clone git@github.com:angular/cli Permission denied (publickey).
22 error git clone git@github.com:angular/cli fatal: Could not read from remote repository.
22 error git clone git@github.com:angular/cli
22 error git clone git@github.com:angular/cli Please make sure you have the correct access rights
22 error git clone git@github.com:angular/cli and the repository exists.
23 silly lockFile 515723dd-git-github-com-angular-cli git@github.com:angular/cli
24 silly lockFile 515723dd-git-github-com-angular-cli git@github.com:angular/cli
25 silly lockFile 5cecaa1c-angular-cli angular/cli
26 silly lockFile 5cecaa1c-angular-cli angular/cli
27 error addLocal Could not install angular/cli
28 error Error: ENOENT: no such file or directory, stat 'angular/cli'
29 error If you need help, you may report this *entire* log,
29 error including the npm and node versions, at:
29 error     <http://github.com/npm/npm/issues>
30 error System Linux 4.9.0-6-amd64
31 error command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "@angular/cli"
32 error cwd /home/xthedoctah
33 error node -v v8.11.1
34 error npm -v 1.4.21
35 error path angular/cli
36 error syscall stat
37 error code ENOENT
38 error errno -2
39 verbose exit [ -2, true ]

**Comment by clydin** [comment]
`NPM : 1.4.21` is extremely old.  Please upgrade to the latest version.  A minimum of 5.5.1 is needed with 6.0.0 being the latest.
