### ISSUE TITLE
ng update @angular/cli fails with npm link'ed module

### ISSUE THREAD

**Issue by supdegrave** [angular/angular-cli#10746]
### Versions
```
Angular CLI: 6.0.0
Node: 9.5.0
OS: darwin x64
Angular: 5.2.5
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0
@angular-devkit/core         0.6.0
@angular-devkit/schematics   0.6.0
@angular/cli                 6.0.0
@schematics/angular          0.6.0
@schematics/update           0.6.0
rxjs                         5.5.6
typescript                   2.5.3    
```

I have a project which uses `npm link` to pull in a shared library "@ teachtown/shared"^, which is TS source code, not transpiled / packaged as JS. The intention is that this library will be used in multiple projects. 

^  space after "@" so that github doesn't try to parse as user/project

I'm trying to upgrade the consuming project, Angular 5.2.5 => 6, following the instructions provided on https://update.angular.io/. 

I reached the following steps, and got an error: 

```
npm install -g @angular/cli
npm install @angular/cli
ng update @angular/cli

> Not found : @teachtown/shared
```

(Aside: I had to update the second command to `npm install @angular/cli --save-dev` for it to properly update CLI in my project.) 

Note that @ teachtown/shared does exist: 

```
$ ls node_modules/@teachtown
> shared
```

### Repro steps
see above description

### Observed behavior
see above description

### Desired behavior
One of the following: 
* Angular CLI provides support for shared projects in source form. 
* Update process recognizes the shared project (by detection of package.json?) and offers option to include as / convert to a library, since CLI now supports `ng generate library`.

**Comment by MrAntix** [comment]
We are using libraries in a private repo these fail with "not found"
Can we have a way to ignore these and carry on?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
