### ISSUE TITLE
Compiler ignoring @import statement within my .scss files

### ISSUE THREAD

**Issue by StephenPaul** [angular/angular-cli#1074]
1. OS : Ubuntu
2. Versions:
angular-cli: 1.0.0-beta.1
node: 5.8.0
os: linux x64
3. Repro steps:
I cannot seem to @import another sass partial. My @Import statement is ignored by the compiler. Any assistance / direction would be greatly appreciated.
4. Log: N/A

**Comment by drala** [comment]
Hi @StephenPaul , you have to enable the whole assets folder to be watch not only the main scss file and make sure the compiler ignore partials. I had the same problem and http://stackoverflow.com/a/37600065/440791 solved the problem for me.

**Comment by StephenPaul** [comment]
@drala thanks for the tip. Unfortunately still seems to be compiling my partials (with their '_' prefix). Is this connected to my issue? Somehow Sass doesn't recognise a partial as a partial?

**Comment by Blasz** [comment]
I'd try upgrading angular-cli to the latest version, sass imports work fine for me.

**Comment by drala** [comment]
@StephenPaul how does your angular-cli-build.js looks like? Strangely, you have to give the path to the folder where all scss files live. Only the main scss file wont do the trick

```
sassCompiler: {
      cacheExclude: [/\/_[^\/]+$/],
      includePaths: [
        'src/app/assets/styles/' 
      ]
    }
```
You also have to install node-sass. `npm install --save-dev node-sass`

**Comment by StephenPaul** [comment]
@Blasz I ended up upgrading my project and this fixed the problem. @drala thanks to you also for your assistance.
