### ISSUE TITLE
ng6 - Can't reexport the named export 'graphql' from non EcmaScript module

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular-cli#10744]
### Versions
```
Angular CLI: 6.0.0
Node: 9.8.0
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/flex-layout              5.0.0-beta.14
@angular/pwa                      0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* `ng new fresh`
* `cd fresh`
* `npm i graphql@latest`
* add the following to the `app.module.ts`:
```
import { graphql } from 'graphql';
...
export class AppModule {
  constructor() {
    // it does not matter what it is below as long as we're using something from `graphql`
    const t = graphql();
  }
}
```
* `npm start`

### Observed behavior
```
ERROR in ./node_modules/graphql/index.mjs
2:0-49 Can't reexport the named export 'graphql' from non EcmaScript module (only default export is available)
ERROR in ./node_modules/graphql/index.mjs
2:0-49 Can't reexport the named export 'graphqlSync' from non EcmaScript module (only default export is available)
...
// continues reporting the same error for all .mjs files
```

### Desired behavior
Build should work

### Mention any other details that might be useful (optional)
I don't know much about `.mjs`, but it appears it might be used instead of `.js` in some cases: http://2ality.com/2017/05/es-module-specifiers.html

It appears this might be an issue of Webpack 4 configuration. See [this](https://github.com/graphql/graphql-js/issues/1272#issuecomment-377384574) for details.

**Comment by amitport** [comment]
For real world applications using graphql, this is a critical issue.

Tried a few workarounds- forking and optimistically editing `@angular-devkit`; using `fileReplacements` for graphql.mjs; specifying exact imports (`from 'graphql` -> `from 'graphql/utilities/index.js'`).

None worked. This is the only issue blocking Angular@6 migration for us

**Comment by elmoGrummelig** [comment]
I am currently working on a project and i have these dependencies:
angular  6
rxjs 6
aws-amplify 0.3.3
aws-amplify-angular 0.1.0

I followed every step of the Amplify guide ( https://aws.github.io/aws-amplify/media/quick_start ) till the last line of section "Connect to Your Backend".
When i run "ng serve" i get lots of these errors :

"ERROR in ./node_modules/graphql/index.mjs
2:0-49 Can't reexport the named export 'graphql' from non EcmaScript module (only default export is available)"

I hope that helps someone to fix this...

**Comment by amitport** [comment]
@elmoGrummelig
fixed for me by https://github.com/angular/devkit/commit/ddf7eddec3d7eb8f6f2c1277d2b951f73f151e0b 
(need to wait for the test to pass and a release of `@angular-devkit/build-angular`)

**Comment by amitport** [comment]
Should work when `graphql@0.13.3` is released (at least for me) (you can also install unreleased version https://github.com/graphql/graphql-js#want-to-ride-the-bleeding-edge)

see https://github.com/graphql/graphql-js/issues/1344#issuecomment-389547106

**Comment by amitport** [comment]
Works with `graphql@14.0.0-rc.2` and `@angular-devkit/build-angular@0.6.3`. Can be closed
