### ISSUE TITLE
ERROR in ./src/node_modules/@angular/core/@angular/core.es5.js Module not found: Error: Can't resolve 'rxjs/Observable' in "project Path" ..I'm facing this issue while migrating from angular 4 to 6

### ISSUE THREAD

**Issue by deepakpookkote** [angular/angular-cli#10748]
WARNING in ./src/node_modules/@angular/core/@angular/core.es5.js
5870:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./src/node_modules/@angular/core/@angular/core.es5.js
5886:15-102 Critical dependency: the request of a dependency is an expression

ERROR in ./src/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '/var/www/html/school-bus-ng-6/schoolbus/src/node_modules/@angular/core/@angular'
ERROR in ./src/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '/var/www/html/school-bus-ng-6/schoolbus/src/node_modules/@angular/core/@angular'
ERROR in ./src/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/merge' in '/var/www/html/school-bus-ng-6/schoolbus/src/node_modules/@angular/core/@angular'
ERROR in ./src/node_modules/@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/operator/share' in '/var/www/html/school-bus-ng-6/schoolbus/src/node_modules/@angular/core/@angular'
ERROR in node_modules/@types/jasminewd2/index.d.ts(18,13): error TS2428: All declarations of 'Matchers' must have identical type parameters.
node_modules/@types/jasminewd2/index.d.ts(42,13): error TS2430: Interface 'ArrayLikeMatchers<T>' incorrectly extends interface 'Matchers<ArrayLike<T>>'.
  Types of property 'toBe' are incompatible.
    Type '(expected: any, expectationFailOutput?: any) => Promise<void>' is not assignable to type '{ (expected: any, expectationFailOutput?: any): boolean; (expected: any, expectationFailOutput?: ...'.
      Type 'Promise<void>' is not assignable to type 'boolean'.
node_modules/@types/jasminewd2/index.d.ts(43,20): error TS2304: Cannot find name 'Expected'.
node_modules/@types/jasminewd2/index.d.ts(44,23): error TS2304: Cannot find name 'Expected'.
src/node_modules/@types/jasmine/index.d.ts(33,41): error TS2314: Generic type 'Matchers<T>' requires 1 type argument(s).
src/node_modules/@types/jasmine/index.d.ts(34,39): error TS2314: Generic type 'Matchers<T>' requires 1 type argument(s).
src/node_modules/@types/jasmine/index.d.ts(159,24): error TS2314: Generic type 'Matchers<T>' requires 1 type argument(s).
src/node_modules/@types/jasmine/index.d.ts(308,15): error TS2428: All declarations of 'Matchers' must have identical type parameters.
src/node_modules/@types/jasmine/index.d.ts(339,14): error TS2314: Generic type 'Matchers<T>' requires 1 type argument(s).
src/node_modules/@types/jasmine/index.d.ts(396,24): error TS2314: Generic type 'Matchers<T>' requires 1 type argument(s).
src/node_modules/@types/jasmine/index.d.ts(409,30): error TS2314: Generic type 'Matchers<T>' requires 1 type argument(s).

ℹ ｢wdm｣: Failed to compile.

any idea regarding this i tried all most every possible solutions !!! help me out

**Comment by truginis** [comment]
Try adding rxjs-compat. That solved a bunch of problems for me.

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by deepakpookkote** [comment]
@truginis :where and how to add the rxjs-compact ??
