### ISSUE TITLE
"Workspace needs to be loaded before it is used." when trying to generate a new Service.

### ISSUE THREAD

**Issue by danbenge** [angular/angular-cli#10757]
### Versions
```
6.0.0
```

### Repro steps

* Open Visual Studio Code to your root Angular project folder.
* Type in ng g component mynewcomponent

### Observed behavior
```
Returns 

Workspace needs to be loaded before it is used.
Error: Workspace needs to be loaded before it is used.
    at Workspace._assertLoaded (D:\learn\Angular\my-first-app\node_modules\@angular-devkit\core\src\workspace\workspace.js:59:19)
    at Workspace.getProjectByPath (D:\learn\Angular\my-first-app\node_modules\@angular-devkit\core\src\workspace\workspace.js:103:14)
    at Object.getDefaultSchematicCollection (D:\learn\Angular\my-first-app\node_modules\@angular\cli\utilities\config.js:194:35)
    at GenerateCommand.parseSchematicInfo (D:\learn\Angular\my-first-app\node_modules\@angular\cli\commands\generate.js:71:39)
    at GenerateCommand.<anonymous> (D:\learn\Angular\my-first-app\node_modules\@angular\cli\commands\generate.js:36:58)
    at Generator.next (<anonymous>)
    at D:\learn\Angular\my-first-app\node_modules\@angular\cli\commands\generate.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\learn\Angular\my-first-app\node_modules\@angular\cli\commands\generate.js:3:12)
    at GenerateCommand.initialize (D:\learn\Angular\my-first-app\node_modules\@angular\cli\commands\generate.js:30:16)

```

### Desired behavior
Should create a new component.

Created the project using Angular CLI.  Tried other projects and getting the same result.

**Comment by juanpablodelatorre** [comment]
Same here using `ng update --all`.

**Comment by bluesolution** [comment]
Do you have angular.json  on project root.

**Comment by Muhanady** [comment]
actually i have the same problem, i found out that when updating angular it deletes angular-cli.json and adds an empty angular.json file. in the created file nothing related to project. am trying to add options to the new file but not sure that it will work because am receiving the same error .
``
Workspace needs to be loaded before it is used.
Error: Workspace needs to be loaded before it is used.
    at Workspace._assertLoaded (D:\NetAngular\node_modules\@angular-devkit\core\src\workspace\workspace.js:59:19)
    at Workspace.getProjectByPath (D:\NetAngular\node_modules\@angular-devkit\core\src\workspace\workspace.js:103:14)
    at Object.getPackageManager (D:\NetAngular\node_modules\@angular\cli\utilities\config.js:97:35)
    at UpdateCommand.runSchematic (D:\NetAngular\node_modules\@angular\cli\models\schematic-command.js:74:38)
    at UpdateCommand.<anonymous> (D:\NetAngular\node_modules\@angular\cli\commands\update.js:70:25)
    at Generator.next (<anonymous>)
    at D:\NetAngular\node_modules\@angular\cli\commands\update.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\NetAngular\node_modules\@angular\cli\commands\update.js:3:12)
    at UpdateCommand.run (D:\NetAngular\node_modules\@angular\cli\commands\update.js:69:16)
``

**Comment by bmunugoti** [comment]
I had the same experiance. i tried to create new angular.json file but still no lucks :(

**Comment by Muhanady** [comment]
EUREKA.............

dotnet new angular comman does not create an angular.json file on the root of the application. in some sites they say that after using

`npm install --save--dev @angular/cli@latest`
command use

`npm update @angular/cli`
which will migrate you angular-cli.json file to angular.json file!!! but the point here there is no angular-cli.json file nor angular.json.

I solved the problem by creating my own angular.json file as bellow (you may change vega with your project name)
` {
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "vega": {
      "root": "",
      "sourceRoot": "ClientApp",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "ClientApp/dist/vega"
          },
          "configurations": {
            "production": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.prod.ts"
              }],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        }
      }
    }
  }
}`

after that i was able to use angular cli command and create components and services.

> Code to be Happy

>

**Comment by ashish9342** [comment]
This bug might be due to syntax error. If you miss simple comma while referencing the css in styles array, you can get this error. This is how I  fixed it for me.

**Error : ** Missed comma after adding bootstrap css in styles  array. After which you can see this bug.

`"styles": [
          "../node_modules/bootstrap/dist/bootstrap.min.css"
          "src/styles.css"

        ]`

**Solution : ** Adding comma  after "../node_modules/bootstrap/dist/bootstrap.min.css", fixes the problem for me.

`"styles": [
          "../node_modules/bootstrap/dist/bootstrap.min.css",
          "src/styles.css"

        ]`

**Comment by Theraghav** [comment]
This link helps:
https://update.angular.io/

**Comment by nexeh** [comment]
I have confirmed that if you have a syntax problem in your angular.json file there this error happens. I would say this is unexpected behavior and should be changed to say there is a syntax problem in the file instead.

**Comment by thongcome** [comment]
check your angular-cli.json is only or not , remove read only will be fine.

**Comment by paakcmd** [comment]
Check your misspelling or misindentation on angular.json

**Comment by wendzhue** [comment]
> check your angular-cli.json is only or not , remove read only will be fine.

Works for me. Or you can just remove the file.

**Comment by hirankit** [comment]
A blank (e.g. created by command: touch) angular-config.json in home directory can also cause this problem.

**Comment by schungx** [comment]
Well, looks like *any* errors on `angular.json`, not just syntax ones, will give this extremely unfriendly error message.

In my case, `version` is wrongly set to a string (should be a number).  There is no syntax error, but this error still comes up.  Changing `version` back to a number resolved it.

**Comment by LucasMaliszewski** [comment]
Using Angular 8 and this is still occurring for me on OS X when using ng new.

**Comment by LucasMaliszewski** [comment]
Found this [link](https://stackoverflow.com/questions/55601510/workspace-needs-to-be-loaded-before-it-is-used-on-ng-new) and it was the fix for me on OS X.

**Comment by srmkumar** [comment]
Team Please help me to get rid of this.

Os version: win 10 64 bit
Node version:  10.15.0
npm version: 6.9.2
angular version: 7.0.4

I reinstalled node several times and uninstalled angular and npm as well for several times and cleared cache also.

At the time of Installing angular It looks like below Image: 

![i](https://user-images.githubusercontent.com/14026447/60490240-c938a800-9cc3-11e9-9a29-c3de2d97fee0.png)

When I try to create new project getting below error.
![issue](https://user-images.githubusercontent.com/14026447/60489959-31d35500-9cc3-11e9-9bc9-864706c3d678.png)

**Comment by mgechev** [comment]
@srmkumar did you try https://stackoverflow.com/questions/55601510/workspace-needs-to-be-loaded-before-it-is-used-on-ng-new
