### ISSUE TITLE
Generating Module Uses Default Source Rather Than Custom Source with ng v6.0.0

### ISSUE THREAD

**Issue by christo8989** [angular/angular-cli#10769]
### Versions
node - 9.11.1
npm - 5.6.0
ng - 6.0.0 (local & global)

### Repro steps
```
// angular.json file
{
  ...
  "projects": {
    "name": {
      "root": "",
      "sourceRoot": "CustomSource",
      ...
    }
  }
}
```
`ng g m shared --spec true --dry-run`

### Observed behavior
It used **src** as the source.
```
CREATE src/app/shared/shared.module.spec.ts (275 bytes)
CREATE src/app/shared/shared.module.ts (190 bytes)
```

### Desired behavior
I want it to use **CustomSource** as the source.
```
CREATE CustomSource/app/shared/shared.module.spec.ts (275 bytes)
CREATE CustomSource/app/shared/shared.module.ts (190 bytes)
```

### Mention any other details that might be useful (optional)
I'm using the Git Bash command line tool. Even though that shouldn't matter...

**Comment by christo8989** [comment]
The current workaround is:

`ng g m ../../CustomSource/app/shared --spec true --dry-run`

**Comment by dgp1130** [comment]
This seems to be working in latest v9.1.7. I'm assuming this has since been fixed, please re-open if you're still seeing this on latest Angular CLI.

```
douglasparker@basilisk (~/Source/fixit)
[20-05-26 12:10:32]$ cat angular.json | grep sourceRoot
      "sourceRoot": "customSrc",
douglasparker@basilisk (~/Source/fixit)
[20-05-26 12:09:47]$ ng g m shared --dry-run
CREATE customSrc/app/shared/shared.module.ts (192 bytes)

NOTE: The "dryRun" flag means no changes were made.
```
