### ISSUE TITLE
Excessive CPU use with 6.0.0 project

### ISSUE THREAD

**Issue by smlombardi** [angular/angular-cli#10764]
### Versions
```
Angular CLI: 6.0.0
Node: 10.1.0
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.0 (cli-only)
@angular-devkit/core         0.6.0 (cli-only)
@angular-devkit/schematics   0.6.0 (cli-only)
@schematics/angular          0.6.0 (cli-only)
@schematics/update           0.6.0 (cli-only)
rxjs                         6.1.0 (cli-only)
typescript                   2.6.2
```

### Repro steps
Updated an Angular 5 project to 6.0 this morning. Ran project with `npm start` on my MBP 15 2017 with 10.13.4 and the fans are going crazy. CPU use went up to 268% for the `ng` process and generally hovers around 170%.

Stop the `ng` process and the CPU and fans return to normal.

**Comment by clydin** [comment]
This generally indicates that the `fsevents` package was not installed or improperly installed.  It is normally installed automatically during project initialization.  However, from the version output above, there appears to be some package installation issues.  Is that output from within the project in question? `Angular:` should not be shown as `undefined`.

If so, (or regardless), something to try is to remove both `node_modules` and any lock files (`package-lock.json`/`yarn.lock`) and reinstall the packages for the project.

**Comment by smlombardi** [comment]
I deleted node_modules and re-installed them.  CPU use calmed down, and the version output makes sense now:
```
Angular CLI: 6.0.0
Node: 10.1.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```
