### ISSUE TITLE
how to use multiple outlets for modules..

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#10779]
how to use multiple outlets for modules..??

like below 

{path: '', outlet: 'auth', loadChildren: 'app/+auth/auth.module#AuthModule'},

giving error like => ERROR Error: Uncaught (in promise): Error: Cannot match any routes.

how to use outlets for module wise navigation???

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
