### ISSUE TITLE
Wrong path in tsconfig.server.json of universal & monorepo

### ISSUE THREAD

**Issue by wellwind** [angular/angular-cli#10770]
### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.0
Node: 8.11.1
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* Step 1

```
ng new demo-project
```

* Step 2

Generate application

```
ng generate application universal-demo
```

* Step 3

Generate universal to the generated project before

```
ng generate universal --clientProject universal-demo
```

* Step 4

Build the server script (will fail)

```
ng run universal-demo:server
```

### Observed behavior

In projects/universal-demo/src/tsconfig.server.json

```json
{
  "extends": "./tsconfig.app.json", <- wrong path
  "compilerOptions": {
    "outDir": "../../out-tsc/app-server",
    "baseUrl": ".",
    "module": "commonjs"
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
}
```

### Desired behavior

```json
{
  "extends": "../tsconfig.app.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/app-server",
    "baseUrl": ".",
    "module": "commonjs"
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
}
```

### Mention any other details that might be useful (optional)

The path of `"extends": "./tsconfig.app.json"` is wrong when generating the universal project to the application.  

Or `tsconfig.app.json` sould be placed in `projects/universal-demo/`

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

That said, the path generated `./tsconfig.app.json` is correct as the `app` and `server` tsconfig reside in the same folder.
