### ISSUE TITLE
How can I config the styleExt in the angular.json

### ISSUE THREAD

**Issue by lichangfeng** [angular/angular-cli#10774]
In angular-cli 1.7.2,I could config the angular-cli.json like this:
"defaults": {
    "styleExt": "less",
    "component": {}
  }
Then I can do 'ng generate component [name]' to create component with less style。
Now in angular6,angular.json has no this config.
In the 'stories css preprocessors',I see 'ng config schematics.@schematics/angular:component.styleext less',but it is not work.

**Comment by pagelinsan** [comment]
Hi, 
it is in angular.json
projects {
projectname { 
 "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
...

**Comment by totkeks** [comment]
Unfortunately this is not overwritten from the global config (.angular-config.json). There I have
```json
"schematics": {
  ":component": {
    "styleext": "scss"
  }
}
```

and after creating a new app, it is still using CSS instead of SCSS.
Is there any way to mimic the behavior of `ng new my-app --style=scss` using the global config file?

**Comment by lichangfeng** [comment]
@pagelinsan  I try it,but it not work still.

**Comment by lichangfeng** [comment]
"projects": {},
"schematics": {
    "@schematics/angular:component": {
      "styleext": "less"
    }
  }

this is.
