### ISSUE TITLE
ERROR in EPERM: operation not permitted, stat 'D:\System Volume Information'

### ISSUE THREAD

**Issue by ShadowQueen** [angular/angular-cli#10776]
Hello,

I have updated my project from Angular 5.2 to new version Angular 6. I have used Angular Update Guide - 5.2 -> 6.0 for Medium Apps.  Everything went well. But I have an error if I try to use ng build, ng build --prod or ng s. The error message is ERROR in EPERM: operation not permitted, stat 'D:\System Volume Information'

### Versions

Angular CLI: 6.0.0
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

### Repro steps

* Step 1
execute command ng build or ng build --prod or ng s
### Observed behavior
**ng s**
** Angular Live Development Server is listening on localhost: 4200, open your browser on http://localhost:4200/ **

Date: 2018-05-10T08:50:54.287Z
Hash: f2a2a12ef36617e0d5cc
Time: 22694ms
chunk {0} 0.js, 0.js.map () 1.53 MB  [rendered]
chunk {main} main.js, main.js.map (main) 1.37 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 417 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 7.96 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 381 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 360 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 7.72 MB [initial] [rendered]

ERROR in EPERM: operation not permitted, stat 'D:\System Volume Information'
i ｢wdm｣: Failed to compile.

![image](https://user-images.githubusercontent.com/16406109/39872805-61e3acfc-5469-11e8-939b-687a0db05284.png)

Stack:
"ReferenceError: error is not defined
    at eval (eval at errors (http://localhost:4200/vendor.js:173286:5), <anonymous>:1:1)
    at Object.errors (http://localhost:4200/vendor.js:173286:5)
    at SockJS.onmessage (http://localhost:4200/vendor.js:173568:25)
    at SockJS.EventTarget.dispatchEvent (http://localhost:4200/vendor.js:162610:20)
    at http://localhost:4200/vendor.js:163323:16
    at Array.forEach (<anonymous>)
    at SockJS._transportMessage (http://localhost:4200/vendor.js:163321:17)
    at WebSocketTransport.EventEmitter.emit (http://localhost:4200/vendor.js:162526:18)
    at WebSocketTransport.ws.onmessage [as __zone_symbol__ON_PROPERTYmessage] (http://localhost:4200/vendor.js:165397:10)
    at WebSocket.wrapFn (http://localhost:4200/polyfills.js:7940:39)"

### Desired behavior
successful compile and build

### Mention any other details that might be useful (optional)
 I have not uninstalled rxjs-compat, because I have some third party dependencies that use the old version of rxjs.

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by ShadowQueen** [comment]
HI,

I have had created repo-app but unfortunately, I don't get the same error. As I said earlier this is a medium application intend to be large very soon. I will try to roll back the application and try everything from begin, again. The major problem is error message: ERROR in EPERM: operation not permitted, stat 'D:\System Volume Information'  - it does not mean anything to me, is not descriptive.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
