### ISSUE TITLE
ng new <name>

### ISSUE THREAD

**Issue by tonmanayo** [angular/angular-cli#10773]
### Versions
ng --version
Angular CLI: 6.0.0
Node: 8.11.1
OS: linux x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

### Repro steps
ng new foo

### Observed behavior

ng new tut
CREATE tut/README.md (1020 bytes)
CREATE tut/angular.json (3376 bytes)
CREATE tut/package.json (1307 bytes)
CREATE tut/tsconfig.json (384 bytes)
CREATE tut/tslint.json (2805 bytes)
CREATE tut/.editorconfig (245 bytes)
CREATE tut/.gitignore (503 bytes)
CREATE tut/src/environments/environment.prod.ts (51 bytes)
CREATE tut/src/environments/environment.ts (631 bytes)
CREATE tut/src/favicon.ico (5430 bytes)
CREATE tut/src/index.html (290 bytes)
CREATE tut/src/main.ts (370 bytes)
CREATE tut/src/polyfills.ts (3194 bytes)
CREATE tut/src/test.ts (642 bytes)
CREATE tut/src/assets/.gitkeep (0 bytes)
CREATE tut/src/styles.css (80 bytes)
CREATE tut/src/browserslist (375 bytes)
CREATE tut/src/karma.conf.js (964 bytes)
CREATE tut/src/tsconfig.app.json (194 bytes)
CREATE tut/src/tsconfig.spec.json (282 bytes)
CREATE tut/src/tslint.json (314 bytes)
CREATE tut/src/app/app.module.ts (314 bytes)
CREATE tut/src/app/app.component.css (0 bytes)
CREATE tut/src/app/app.component.html (1141 bytes)
CREATE tut/src/app/app.component.spec.ts (986 bytes)
CREATE tut/src/app/app.component.ts (207 bytes)
CREATE tut/e2e/protractor.conf.js (752 bytes)
CREATE tut/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE tut/e2e/src/app.po.ts (208 bytes)
CREATE tut/e2e/tsconfig.e2e.json (213 bytes)

> node-sass@4.9.0 install /home/foo/angular/tut/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/linux-x64-57_binding.node
Download complete  ] - :
Binary saved to /home/foo/angular/tut/node_modules/node-sass/vendor/linux-x64-57/binding.node
Caching binary to /home/foo/.npm/node-sass/4.9.0/linux-x64-57_binding.node
Failed to cache binary: { Error: EACCES: permission denied, open '/home/foo/.npm/node-sass/4.9.0/linux-x64-57_binding.node'
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/home/foo/.npm/node-sass/4.9.0/linux-x64-57_binding.node' }

> node-sass@4.9.0 postinstall /home/foo/angular/tut/node_modules/node-sass
> node scripts/build.js

Binary found at /home/foo/angular/tut/node_modules/node-sass/vendor/linux-x64-57/binding.node
Testing binary
Binary is fine

> @angular/cli@6.0.0 postinstall /home/foo/angular/tut/node_modules/@angular/cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1080 packages from 1262 contributors in 68.103s
[!] 15 vulnerabilities found [21356 packages audited]
    Severity: 10 Low | 5 High
    Run `npm audit` for more detail

    Successfully initialized git.

### Desired behavior
packages installed successful

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
