### ISSUE TITLE
Cli installation stuck on shallow-clone

### ISSUE THREAD

**Issue by littlestuart** [angular/angular-cli#10789]
Trying to install the cli and its stuck here for 15 mins now.

C:\AngularProjects>npm install -g @angular/cli
[            ......] / unbuild:shallow-clone: info lifecycle shallow-clone@1.0.0~postuninstall: shallow-clone@1.0.0

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
