### ISSUE TITLE
incomplete documentation for ng generate

### ISSUE THREAD

**Issue by supdegrave** [angular/angular-cli#10784]
### Versions
```
N/A - issue relates to website / documentation
```

### Repro steps
* Navigate to https://github.com/angular/angular-cli/wiki/generate
* View documentation

### Observed behavior
Note the following: 
```
Available blueprints:
    class
    component
    directive
    enum
    guard
    interface
    module
    pipe
    service
```

### Desired behavior
Documentation should include all schematics listed in command `ng generate --help`

```
Available schematics:
    serviceWorker
    application
    class
    component
    directive
    enum
    guard
    interface
    module
    pipe
    service
    universal
    appShell
    library
```

The following schematics are missing from the online documentation: 

* serviceWorker
* application
* universal
* appShell
* library

**Comment by clydin** [comment]
Resolved via https://github.com/angular/angular-cli/pull/10753
