### ISSUE TITLE
Loading chunk failed on a different port from ng serve port

### ISSUE THREAD

**Issue by rishabh-94** [angular/angular-cli#10781]
### Versions
```
Angular CLI: 1.7.4
Node: 8.9.4
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.2.5
@angular/cli: 1.7.4
@angular/material-moment-adapter: 5.2.5
@angular/material: 5.2.5
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Repro steps

* Step 1: Make an angular app with a lazy loaded module
* Step 2 ng serve on port 4200 and include scripts in an html page running on a different port 8080
```
        <script type="text/javascript" src="http://localhost:4200/inline.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/polyfills.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/styles.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/vendor.bundle.js"></script>
        <script type="text/javascript" src="http://localhost:4200/main.bundle.js"></script>
```
* Step 3 Navigate to localhost:8080/lazy-loaded-route and see that loading of lazy-loaded.module.js has failed

### Observed behavior
The chunk is being loaded from localhost:8080/lazy-loaded.module.js and resulting in a 404

### Desired behavior

The chunk should be correctly loaded from localhost:4200/lazy-loaded.module.js
(the port that is serving the angular app)

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
