### ISSUE TITLE
AOT Error: Cannot determine the module for class.. Possible Regression

### ISSUE THREAD

**Issue by pain0486** [angular/angular-cli#10791]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Windows 10
NPM: 6.0.0
Angular CLI: 6.1.3
Node: 8.11.1
OS: win32 x64
Angular: 6.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.7.3
@ngtools/webpack                  6.0.0
@schematics/angular               0.7.3
@schematics/update                0.7.3
rxjs                              6.1.0
typescript                        2.9.2
webpack                           4.6.0
```

### Repro steps

* Create a nested layer of modules
* Create a component that inherits from abstract class
   
- AppModule
    - NaviationModule (exports InboxModule)
        - InboxModule (Declares and exports InboxNavigationComponent)
            - InboxNavigationComponent

### Observed behavior
```
ERROR in : Cannot determine the module for class InboxNavigationComponent in D:/Users/{{UserName}}/Desktop/Frontend/CannotDetermineModuleTest/src/app/core/inbox/inboxNavigation.component.ts! Add InboxNavigationComponent to the NgModule to fix it.
```

### Mention any other details that might be useful (optional)
Here is a reproduction from a generated cli 6.0.0 project
[CannotDetermineModuleTest.zip](https://github.com/angular/angular-cli/files/1992622/CannotDetermineModuleTest.zip)

**Comment by PawOrmstrupMadsen** [comment]
+1

**Comment by pain0486** [comment]
Anyone have any movement on this? I am unable to upgrade to version 6 if I cant do a production build. Any ideas for a work around? I would like to keep current with angular. If I can't I will be forced into moving off angular.

**Comment by PawOrmstrupMadsen** [comment]
try looking for import statements where you have lower/upper-case inconsistencies in the full path of files/modules.

That was my issue with these errors.

it's also the reason wry the reproduction excample fails. look in inbox.module import, there are a Uppercase but the file is lowercase.

**Comment by pain0486** [comment]
Thank You so much I had entirely forgotten about case sensitivity! I actually didn't know it mattered that it didn't match the file name but I did remember having to be consistent when importing it.
While it still does not compile.... its a completely different error!

Thanks you so much @PawOrmstrupMadsen for your help.
