### ISSUE TITLE
ng build: extractLicenses not including all licenses

### ISSUE THREAD

**Issue by Bbansjkl** [angular/angular-cli#10794]
### Versions
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.0
Node: 8.9.1
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cli                      6.0.0
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              5.5.10
typescript                        2.5.3
webpack                           4.6.0

Windows 10 1803
```

### Repro steps
* create new Angular app `ng new <name>`
* build the app for production `ng build --prod`
* open `dist\<name>\3rdpartylicenses.txt`

See my repo [angular-extract-licenses-test](https://github.com/Bbansjkl/angular-extract-licenses-test), which has `@angular/cli@1.6.6` in the master repository and was updated to `@angular/cli@6.0.0` in the "ngcli6" branch, using the commands
```
npm install @angular/cli@latest
ng update @angular/cli
```

### Observed behavior
The file `3rdpartylicenses.txt` in the dist folder contains the license notices of the packages `core-js` and `zone-js`

### Desired behavior
From what I understand from the sparse documentation in the [wiki](https://github.com/angular/angular-cli/wiki/build), the option "extractLicenses" should get all license files from used dependencies - in this case only production dependencies - and collect them in one file.
This seemed to kinda work in Angular CLI v1.6.6, although I'm also missing some package license paragraphs there, e.g. from the `rxjs` package.

Could also be that this is a simple user error and the "extractLicenses" feature has a different scope that I'm not aware of.

### Mention any other details that might be useful (optional)

Creating a new project with the v6.0.0 CLI or updating an existing one to v6.0.0 doesn't seem to make a difference.

**Comment by tkoenig89** [comment]
I'm having the same issue and might be able to add some more information. 

If I'm running simply `ng build` (**without --prod**), there are a lot more licences showing up in `3rdpartylicenses.txt`. E.g. rxjs and others. Which seems to me like a more complete list of packages we use in the final application. But I would not guarantee, that it's really the complete list of all the packages.

So maybe the issues is somewhere related to the `--prod` flag.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by kumaresan-subramani** [comment]
is there any way to avoid `3rdpartylicenses.txt` generation while running below command:

> ng build --prod window --aot --source-map=false --vendor-chunk=true --output-hashing none
