### ISSUE TITLE
Path to ngsw-config.json

### ISSUE THREAD

**Issue by zygimantas** [angular/angular-cli#10793]
### Versions
```
Angular CLI: 6.0.0
Node: 10.0.0
OS: win32 x64
Angular: 6.0.0
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Observed behavior

ngsw-config.json must be in src/ directory

### Desired behavior

There may be multiple apps configured in angular.json, so the path ngsw-config.json should be configurable also; ngsw-config.json should not be shared across different apps; file name should be configurable;

**Comment by menosprezzi** [comment]
I suggest also a custom path to `ngsw-config.json` as we see in other config files in `angular.json`

**Comment by mackelito** [comment]
Correct me if I'm wrong but if we run 'ng add  @angular/pwa --project *project-name*' the ngsw-config is added to root '/' right?

**Comment by alan-agius4** [comment]
There is already an option to specify the ngsw config path location. This is called `ngswConfigPath` which can be specified in the build options https://angular.io/cli/build

That said maybe, we should generate `ngsw-config.json` under the project `sourceRoot` if `root` is empty similar to the `karma.conf.js`

Proposed:
```
-- src
---- ngsw-config.json
-- project
---- app
------ ngsw-config.json
```

Current:
```
-- ngsw-config.json
-- src
-- project
---- app
------ ngsw-config.json
```

@clydin, @filipesilva, what do you reckon?

**Comment by filipesilva** [comment]
@alan-agius4 yes, I agree it should be like your proposal. Similar config files are also under `src/`.
