### ISSUE TITLE
ng new projectname fails with Error compiling schema, function code: var customRule0

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#10804]
### Versions

ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.1
Node: 6.11.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.1
@angular-devkit/core         0.6.1
@angular-devkit/schematics   0.6.1
@angular/cli                 6.0.1
@schematics/angular          0.6.1
@schematics/update           0.6.1
rxjs                         6.1.0
typescript                   2.8.3

### Repro steps

* Step 1
npm i @angular/cli@latest
* Step 2
ng new testproject
* Step 3

### Observed behavior
 ng new testproj
Error compiling schema, function code: var customRule0 = customRules[0]; var validate = async function(data, dataPath, parentData, parentDataProperty, rootData) { 'use strict';  var vErrors = null;
  var errors = 0;      if (rootData === undefined) rootData = data;  if ((data && typeof data === "object" && !Array.isArray(data))) {   if (data.di .....

### Desired behavior
a new project. I did not install this cli version global because i have already anothr porject with anotehr version of cli and angular.
I just wanted to test the latest cli + angular6.

**Comment by brianxu** [comment]
I ran into the same issue. Turns out I forgot to switch to node 8.10+

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
