### ISSUE TITLE
Issue with loading third party library in Angular 6

### ISSUE THREAD

**Issue by Santhosh25** [angular/angular-cli#10801]
Issue with loading third party library which is dependence on another third party library.
In my case, i'm using bootstrap(v3.3.7) which is required JQuery. I included these libraries as per angular suggested way and successfully compile the application, if run it in browser i got a console error.  

### Versions
```
"dependencies": {
    "@angular/animations": "^6.0.0",
    "@angular/common": "^6.0.0",
    "@angular/compiler": "^6.0.0",
    "@angular/core": "^6.0.0",
    "@angular/forms": "^6.0.0",
    "@angular/http": "^6.0.0",
    "@angular/platform-browser": "^6.0.0",
    "@angular/platform-browser-dynamic": "^6.0.0",
    "@angular/router": "^6.0.0",
    "@types/bootstrap": "^3.3.33",
    "@types/jquery": "^3.3.1",
    "bootstrap": "^3.3.7",
    "core-js": "^2.5.4",
    "jquery": "3.3.1",
    "malihu-custom-scrollbar-plugin": "3.1.5",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  }
```
### Sample code
_angular.json_
![angular-json](https://user-images.githubusercontent.com/12733968/39909896-697dda60-5512-11e8-99ec-7c7dfed50d18.jpg)

_app.component.ts_
![app-component](https://user-images.githubusercontent.com/12733968/39909918-7fff04b2-5512-11e8-93bc-84f08fcbeba2.jpg)

### Console Error
![bootstrap](https://user-images.githubusercontent.com/12733968/39909634-3d136950-5511-11e8-8ccd-a156d1b994fd.jpg)

**Comment by WandererInVoids** [comment]
did u add bootstrap js? also u can use CDN for them

**Comment by alan-agius4** [comment]
You are setting `jQuery` as a global, however you are importing using a direct import. This will result in having jQuery twice in your application.

See https://github.com/angular/angular-cli/wiki/stories-global-scripts#using-global-libraries-inside-your-app
