### ISSUE TITLE
How to build without bundling ?

### ISSUE THREAD

**Issue by mjeson** [angular/angular-cli#10811]
I am trying to build without bundling the files. I know there is `source-map` argument to show the source code inside browser, but how to truly bundle while keeping individual files on their respective source folders ? I have used `ng build` , `ng build dev`, `npm run build`, all with no luck.

Shows as Bundled
![image](https://user-images.githubusercontent.com/12972146/39938367-932a6064-5507-11e8-944a-5e4797e6b0a6.png)

Need to have deployment assets as truly unbundled, following original folders
![image](https://user-images.githubusercontent.com/12972146/39938410-bca03018-5507-11e8-8b9c-4027e1987509.png)

Please help. Thank you in advance.

**Comment by lucasvanhalst** [comment]
Why would you want that? It would be very slow to load in due to the sheer amount of files involved

**Comment by bmayen** [comment]
Given that Webpack is the core build tool here, and given that it's a bundler, my guess is that this won't get much traction.

We do some post-build environment config as well, so I see what you mean here, but in our case it wasn't insurmountable and the benefits of Webpack bundles outweighed the less-than-ideal devops config.

**Comment by hitandyrun** [comment]
You can find some ideas here: https://github.com/angular/angular-cli/issues/3855

It is possible to do, just not a "default".

Basically have a service that starts with your application and have that load your config and run from there. As for your environment files, you can set them in a similar way to "assets" and have them retain the same folder structure.

**Comment by mjeson** [comment]
A very rich discussion in #3855 . The silver lining appears on issue where `build` and `bundling` are tightly coupled in a single action, thus causing various other issues.

**Comment by andregs** [comment]
A build with no bundling would be useful for an app served via HTTP/2, wouldn't it? I'm thinking about server pushing and multiplexing...

**Comment by nhhockeyplayer** [comment]
needs to be decoupled we cannot guess nor see what URL's and PATHs are ACTUALLY being fabricated under dist folder when debugging something that went to production

please decouple asap

if you debug a production app you will see the issues that unfold especially with SSL

**Comment by mgechev** [comment]
Bundling the application is an essential part of the production build. Disabling bundling doesn't seem like solution of the issue for management of multi-configuration. Let's keep track of this feature in https://github.com/angular/angular-cli/issues/3855.

In production applications using different CLI tools and technologies, I've usually approached this problem by providing placeholders which can be later replaced with real values. I know it's not idea but it's a good workaround until we find a better solution.
