### ISSUE TITLE
Executing "ng serve" or "npm start" command browser is not opening automatically 

### ISSUE THREAD

**Issue by deepaksibar** [angular/angular-cli#1081]
1. OS?  
Window 7

2. Versions?
angular-cli: 0.0.39
node: 5.4.1
os: win32 x64

I have generated a project using angular-cli by following steps given in installation section. Project is running right now. But i have to open browser manually by typing http://localhost:4200/ into browser.

Could it be possible like when user will execute "ng serve" or "npm start" command, browser will open automatically?

Please let me know if it is possible or give me any solution for this.

Thanks in advance.

-Deepak

**Comment by Trendy** [comment]
I don't think the intention is to open the browser automatically. When you visit the URL (http://localhost:4200) the browser should be refreshed automatically when changes occur in the code.

**Comment by filipesilva** [comment]
We don't have this functionality at the moment, no. But I'll leave the issue open as a 'nice to have'.

**Comment by Splaktar** [comment]
Yes, it would be nice to have this as an option.

**Comment by deepaksibar** [comment]
Thanks for response.

**Comment by kamran-pervaiz** [comment]
can we not use lite-server written by john papa to open the browser after ng server on inside ng serve

**Comment by deepaksibar** [comment]
There may be ambiguity between lite-server port and ng server port.

**Comment by nitro52** [comment]
> I don't think the intention is to open the browser automatically. When you visit the URL (http://localhost:4200) the browser should be refreshed automatically when changes occur in the code.

@Trendy I would consider them 2 different features. The way i have seen the Refresh work is that you hit your site, the site has some javascript injected into it that listens for a command to tell it that something changed then it reloads the page. This is different from when you start the app sending a command to launch a browser and navigate to the URL. 

If you never navigated to the url of your app then there would be no code running to listen when something changed. I guess its still doable but then you would probably need a browser plugin to listen instead

**Comment by chrisfoster78** [comment]
You can just change what npm start does in the package.json.

E.g. change 
`"start": "ng serve"`
to
`"start": "start http://localhost:4201 & ng serve -port 4201"`
(for windows)

See http://stackoverflow.com/a/35261624 for Mac/Linux equivalents.

Or you could use the following if you want a cross platform
https://www.npmjs.com/package/open

**Comment by deepaksibar** [comment]
Thanks

**Comment by craigcosmo** [comment]
Guys can you consider browser option? like open in chrome or firefox

**Comment by rsprince** [comment]
I like having the app launch the first time in the browser, like using browserSync with Gulp.

Checked ng-cli documentation, it's #ng start -o

https://github.com/angular/angular-cli/wiki/serve

**Comment by arbimauday** [comment]
![error ang](https://user-images.githubusercontent.com/25823087/27250452-5b7c4d44-535a-11e7-8f1f-d6b5aacba731.JPG)

**Comment by Gillespie59** [comment]
This behavior should definitely be available,  but through an option.  
Right now, you can maybe use the npm opn module ?

**Comment by kamlesh131986** [comment]
This is issue for default browser. you can properly uninstall browser again browser install.

**Comment by rsprince** [comment]
As I mentioned, the functionality is there. There are a bunch of options on the serve command. READ THE DOCUMENTATION:
ng serve --open
OR
ng serve -o

**Comment by neapi666** [comment]
Para que la ejecución sea automática es necesario ejecutar >ng serve -o

**Comment by filipesilva** [comment]
@dhinged this command has worked for a while now, and it still seems to work as I've just tried it. I wonder why it doesn't work for you... for reference the library we use to open the browser is https://www.npmjs.com/package/opn.

**Comment by dhinged** [comment]
I apologize, trying it again today, it just took a while for the server to "boot up" but it did open a browser tab (after I'd opened it myself based on the instructions URL).

So basically I ran the command (either time), it looked like it was running, but there was no output for maybe 15 seconds so I figured it was just running. I then later noticed a ton of output from node, so I just need to wait.

Thanks for being there!

**Comment by kamok** [comment]
Just go into your `package.json`, and add the `-o` flag.
For example:
`"start": "ng serve -o",`
Now when you do `npm start`, it'll open up the browser window and right port for you and save you a few strokes on the keyboard.

**Comment by nirmalmohanty91** [comment]
after changing from "start": "ng serve" to "start": "ng serve -o", it worked for me.

**Comment by nitanshu1808** [comment]
Hi 
I am not able to create angular js application(LINUX- UBUNTU 16) as every time i try to run it ng it opens a text editor in the terminal 
--**-Mg: *scratch* (fundamental)----All-----------------

Can anyone please help me in creating a angular js application in ubuntu.

**Comment by rsprince** [comment]
Try debugging.

**Comment by abhinandanmadaan** [comment]
> Hi
> I am not able to create angular js application(LINUX- UBUNTU 16) as every time i try to run it ng it opens a text editor in the terminal
> --**-Mg: _scratch_ (fundamental)----All-----------------
> 
> Can anyone please help me in creating a angular js application in ubuntu.

I'm facing the same problem. Could you resolve the issue?
