### ISSUE TITLE
no such file or directory, rename 'C:\Users\a dmin\AppData\Roaming\npm-cache 

### ISSUE THREAD

**Issue by sagaroo** [angular/angular-cli#10823]
-- Error--

C:\Users\admin>npm install -g @angular/cli
Unhandled rejection Error: ENOENT: no such file or directory, rename 'C:\Users\a
dmin\AppData\Roaming\npm-cache\_cacache\tmp\5e48d2c1' -> 'C:\Users\admin\AppData
\Roaming\npm-cache\_cacache\content-v2\sha512\37\3a\1d27cde6e835484f51dba40f513c
52618b05975cdb2b6fdb83ffc91288c9f75fb606fa0bfe04f46a2a30ac8750f9c1efd47be657ddd0
cee5210add0d16a5'

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2018-05-12T15_18_23_
935Z-debug.log

--- Log File ---
0 info it worked if it ends with ok
1 verbose cli [ 'H:\\nodeJS-Install\\node.exe',
1 verbose cli   'H:\\nodeJS-Install\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose npm-session cc3627ccf63bc6ad
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@angular%2fcli 2309ms
8 silly pacote tag manifest for @angular/cli@latest fetched in 3102ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule @angular/cli@6.0.1 checking installable status
14 http fetch GET 200 https://registry.npmjs.org/rxjs 499ms
15 silly pacote range manifest for rxjs@^6.0.0 fetched in 515ms
16 silly resolveWithNewModule rxjs@6.1.0 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/resolve 519ms
18 silly pacote range manifest for resolve@^1.1.7 fetched in 525ms
19 silly resolveWithNewModule resolve@1.7.1 checking installable status
20 http fetch GET 200 https://registry.npmjs.org/semver 543ms
21 silly pacote range manifest for semver@^5.1.0 fetched in 552ms
22 silly resolveWithNewModule semver@5.5.0 checking installable status
23 http fetch GET 200 https://registry.npmjs.org/silent-error 554ms
24 silly pacote range manifest for silent-error@^1.0.0 fetched in 581ms
25 silly resolveWithNewModule silent-error@1.1.0 checking installable status
26 http fetch GET 200 https://registry.npmjs.org/opn 588ms
27 silly pacote range manifest for opn@~5.3.0 fetched in 599ms
28 silly resolveWithNewModule opn@5.3.0 checking installable status
29 http fetch GET 200 https://registry.npmjs.org/symbol-observable 169ms
30 silly pacote range manifest for symbol-observable@^1.2.0 fetched in 177ms
31 silly resolveWithNewModule symbol-observable@1.2.0 checking installable status
32 http fetch GET 200 https://registry.npmjs.org/yargs-parser 168ms
33 silly pacote range manifest for yargs-parser@^10.0.0 fetched in 172ms
34 silly resolveWithNewModule yargs-parser@10.0.0 checking installable status
35 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2farchitect 946ms
36 silly pacote version manifest for @angular-devkit/architect@0.6.1 fetched in 966ms
37 silly resolveWithNewModule @angular-devkit/architect@0.6.1 checking installable status
38 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fschematics 1113ms
39 silly pacote version manifest for @angular-devkit/schematics@0.6.1 fetched in 1119ms
40 silly resolveWithNewModule @angular-devkit/schematics@0.6.1 checking installable status
41 http fetch GET 200 https://registry.npmjs.org/@angular-devkit%2fcore 1235ms
42 silly pacote version manifest for @angular-devkit/core@0.6.1 fetched in 1241ms
43 silly resolveWithNewModule @angular-devkit/core@0.6.1 checking installable status
44 http fetch GET 200 https://registry.npmjs.org/@schematics%2fupdate 1290ms
45 silly pacote version manifest for @schematics/update@0.6.1 fetched in 1298ms
46 silly resolveWithNewModule @schematics/update@0.6.1 checking installable status
47 http fetch GET 200 https://registry.npmjs.org/@schematics%2fangular 1737ms
48 silly pacote version manifest for @schematics/angular@0.6.1 fetched in 1743ms
49 silly resolveWithNewModule @schematics/angular@0.6.1 checking installable status
50 http fetch GET 200 https://registry.npmjs.org/chokidar 206ms
51 silly pacote range manifest for chokidar@^2.0.3 fetched in 212ms
52 silly resolveWithNewModule chokidar@2.0.3 checking installable status
53 http fetch GET 200 https://registry.npmjs.org/source-map 222ms
54 silly pacote range manifest for source-map@^0.5.6 fetched in 228ms
55 silly resolveWithNewModule source-map@0.5.7 checking installable status
56 http fetch GET 200 https://registry.npmjs.org/ajv 328ms
57 silly pacote range manifest for ajv@~6.4.0 fetched in 341ms
58 silly resolveWithNewModule ajv@6.4.0 checking installable status
59 http fetch GET 200 https://registry.npmjs.org/fast-deep-equal 166ms
60 silly pacote range manifest for fast-deep-equal@^1.0.0 fetched in 173ms
61 silly resolveWithNewModule fast-deep-equal@1.1.0 checking installable status
62 http fetch GET 200 https://registry.npmjs.org/json-schema-traverse 172ms
63 http fetch GET 200 https://registry.npmjs.org/uri-js 173ms
64 http fetch GET 200 https://registry.npmjs.org/fast-json-stable-stringify 181ms
65 silly pacote range manifest for json-schema-traverse@^0.3.0 fetched in 185ms
66 silly resolveWithNewModule json-schema-traverse@0.3.1 checking installable status
67 silly pacote range manifest for uri-js@^3.0.2 fetched in 186ms
68 silly resolveWithNewModule uri-js@3.0.2 checking installable status
69 silly pacote range manifest for fast-json-stable-stringify@^2.0.0 fetched in 190ms
70 silly resolveWithNewModule fast-json-stable-stringify@2.0.0 checking installable status
71 http fetch GET 200 https://registry.npmjs.org/punycode 195ms
72 silly pacote range manifest for punycode@^2.1.0 fetched in 206ms
73 silly resolveWithNewModule punycode@2.1.0 checking installable status
74 http fetch GET 200 https://registry.npmjs.org/is-binary-path 186ms
75 http fetch GET 200 https://registry.npmjs.org/readdirp 186ms
76 http fetch GET 200 https://registry.npmjs.org/is-glob 192ms
77 http fetch GET 200 https://registry.npmjs.org/async-each 196ms
78 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 193ms
79 http fetch GET 200 https://registry.npmjs.org/inherits 196ms
80 http fetch GET 200 https://registry.npmjs.org/normalize-path 197ms
81 http fetch GET 200 https://registry.npmjs.org/glob-parent 203ms
82 http fetch GET 200 https://registry.npmjs.org/anymatch 206ms
83 http fetch GET 200 https://registry.npmjs.org/braces 206ms
84 silly pacote range manifest for is-binary-path@^1.0.0 fetched in 211ms
85 silly resolveWithNewModule is-binary-path@1.0.1 checking installable status
86 silly pacote range manifest for readdirp@^2.0.0 fetched in 215ms
87 silly resolveWithNewModule readdirp@2.1.0 checking installable status
88 silly pacote range manifest for is-glob@^4.0.0 fetched in 217ms
89 silly resolveWithNewModule is-glob@4.0.0 checking installable status
90 silly pacote range manifest for path-is-absolute@^1.0.0 fetched in 219ms
91 silly resolveWithNewModule path-is-absolute@1.0.1 checking installable status
92 silly pacote range manifest for async-each@^1.0.0 fetched in 224ms
93 silly resolveWithNewModule async-each@1.0.1 checking installable status
94 silly pacote range manifest for normalize-path@^2.1.1 fetched in 223ms
95 silly resolveWithNewModule normalize-path@2.1.1 checking installable status
96 silly pacote range manifest for inherits@^2.0.1 fetched in 224ms
97 silly resolveWithNewModule inherits@2.0.3 checking installable status
98 silly pacote range manifest for anymatch@^2.0.0 fetched in 229ms
99 silly resolveWithNewModule anymatch@2.0.0 checking installable status
100 silly pacote range manifest for glob-parent@^3.1.0 fetched in 230ms
101 silly resolveWithNewModule glob-parent@3.1.0 checking installable status
102 silly pacote range manifest for braces@^2.3.0 fetched in 231ms
103 silly resolveWithNewModule braces@2.3.2 checking installable status
104 http fetch GET 200 https://registry.npmjs.org/upath 164ms
105 http fetch GET 200 https://registry.npmjs.org/fsevents 165ms
106 silly pacote range manifest for upath@^1.0.0 fetched in 173ms
107 silly resolveWithNewModule upath@1.0.5 checking installable status
108 silly pacote range manifest for fsevents@^1.1.2 fetched in 171ms
109 silly resolveWithNewModule fsevents@1.2.3 checking installable status
110 silly pacote trying https://registry.npmjs.org/fsevents/-/fsevents-1.2.3.tgz by hash: sha512-X+57O5YkDTiEQGiw8i7wYc2nQgweIekqkepI8Q3y4wVlurgBt2SuwxTeYUYMZIGpLZH3r/TsMjczCMXE5ZOt7Q==
111 silly pacote data for sha512-X+57O5YkDTiEQGiw8i7wYc2nQgweIekqkepI8Q3y4wVlurgBt2SuwxTeYUYMZIGpLZH3r/TsMjczCMXE5ZOt7Q== not present. Using manifest.
112 http fetch GET 200 https://registry.npmjs.org/fsevents/-/fsevents-1.2.3.tgz 6610ms
113 silly pacote https://registry.npmjs.org/fsevents/-/fsevents-1.2.3.tgz extracted in 6650ms
114 silly addBundled read tarball
115 silly cleanup remove extracted module
116 http fetch GET 200 https://registry.npmjs.org/micromatch 328ms
117 silly pacote range manifest for micromatch@^3.1.4 fetched in 335ms
118 silly resolveWithNewModule micromatch@3.1.10 checking installable status
119 http fetch GET 200 https://registry.npmjs.org/object.pick 195ms
120 http fetch GET 200 https://registry.npmjs.org/regex-not 199ms
121 http fetch GET 200 https://registry.npmjs.org/arr-diff 207ms
122 http fetch GET 200 https://registry.npmjs.org/nanomatch 205ms
123 http fetch GET 200 https://registry.npmjs.org/kind-of 207ms
124 http fetch GET 200 https://registry.npmjs.org/array-unique 211ms
125 http fetch GET 200 https://registry.npmjs.org/extend-shallow 211ms
126 http fetch GET 200 https://registry.npmjs.org/define-property 217ms
127 silly pacote range manifest for regex-not@^1.0.0 fetched in 222ms
128 silly resolveWithNewModule regex-not@1.0.2 checking installable status
129 silly pacote range manifest for object.pick@^1.3.0 fetched in 227ms
130 silly resolveWithNewModule object.pick@1.3.0 checking installable status
131 http fetch GET 200 https://registry.npmjs.org/extglob 230ms
132 http fetch GET 200 https://registry.npmjs.org/fragment-cache 235ms
133 silly pacote range manifest for arr-diff@^4.0.0 fetched in 239ms
134 silly resolveWithNewModule arr-diff@4.0.0 checking installable status
135 silly pacote range manifest for nanomatch@^1.2.9 fetched in 235ms
136 silly resolveWithNewModule nanomatch@1.2.9 checking installable status
137 silly pacote range manifest for kind-of@^6.0.2 fetched in 237ms
138 silly resolveWithNewModule kind-of@6.0.2 checking installable status
139 silly pacote range manifest for extend-shallow@^3.0.2 fetched in 239ms
140 silly resolveWithNewModule extend-shallow@3.0.2 checking installable status
141 silly pacote range manifest for array-unique@^0.3.2 fetched in 242ms
142 silly resolveWithNewModule array-unique@0.3.2 checking installable status
143 silly pacote range manifest for define-property@^2.0.2 fetched in 242ms
144 silly resolveWithNewModule define-property@2.0.2 checking installable status
145 silly pacote range manifest for extglob@^2.0.4 fetched in 244ms
146 silly resolveWithNewModule extglob@2.0.4 checking installable status
147 silly pacote range manifest for fragment-cache@^0.2.1 fetched in 248ms
148 silly resolveWithNewModule fragment-cache@0.2.1 checking installable status
149 http fetch GET 200 https://registry.npmjs.org/to-regex 156ms
150 silly pacote range manifest for to-regex@^3.0.2 fetched in 275ms
151 silly resolveWithNewModule to-regex@3.0.2 checking installable status
152 http fetch GET 200 https://registry.npmjs.org/snapdragon 283ms
153 silly pacote range manifest for snapdragon@^0.8.1 fetched in 288ms
154 silly resolveWithNewModule snapdragon@0.8.2 checking installable status
155 silly pacote range manifest for extend-shallow@^2.0.1 fetched in 11ms
156 silly resolveWithNewModule extend-shallow@2.0.1 checking installable status
157 http fetch GET 200 https://registry.npmjs.org/fill-range 197ms
158 http fetch GET 200 https://registry.npmjs.org/isobject 201ms
159 http fetch GET 200 https://registry.npmjs.org/snapdragon-node 205ms
160 http fetch GET 200 https://registry.npmjs.org/arr-flatten 207ms
161 http fetch GET 200 https://registry.npmjs.org/split-string 208ms
162 silly pacote range manifest for fill-range@^4.0.0 fetched in 214ms
163 silly resolveWithNewModule fill-range@4.0.0 checking installable status
164 silly pacote range manifest for isobject@^3.0.1 fetched in 216ms
165 silly resolveWithNewModule isobject@3.0.1 checking installable status
166 silly pacote range manifest for snapdragon-node@^2.0.1 fetched in 216ms
167 silly resolveWithNewModule snapdragon-node@2.1.1 checking installable status
168 silly pacote range manifest for arr-flatten@^1.1.0 fetched in 218ms
169 silly resolveWithNewModule arr-flatten@1.1.0 checking installable status
170 silly pacote range manifest for split-string@^3.0.2 fetched in 218ms
171 silly resolveWithNewModule split-string@3.1.0 checking installable status
172 error cb() never called!
173 error This is an error with npm itself. Please report this error at:
174 error <https://github.com/npm/npm/issues>

**Comment by Brocco** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
