### ISSUE TITLE
Angular CLI: 6.0.1 Ng Serve Error

### ISSUE THREAD

**Issue by Toso82** [angular/angular-cli#10836]
### Versions
```
Angular CLI: 6.0.1
Node: 10.1.0
OS: win32 x64
Angular: 6.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1 (cli-only)
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1 (cli-only)
@schematics/update                0.6.1 (cli-only)
rxjs                              6.1.0
typescript                        2.8.3
webpack                           4.6.0
```

### Repro steps
When do ng serve first time not compile give me this:

> ** Angular Live Development Server is listening on localhost: 4200, open your browser on http://localhost:4200/ **
> 
> Date: 2018-05-14T09:12:02.581Z
> Hash: 8a1ca2344d4061312bc9
> Time: 6238ms
> chunk {main} main.js, main.js.map (main) 1.99 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 712 bytes [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 5.4 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 207 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]
> 
> ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.8.3 was found instead.
> i ｢wdm｣: Failed to compile.

If i do change of code start to compile well why?

### Mention any other details that might be useful (optional)
- TypeScript Version 2.8.3
- This is my package.json

```
{
  "name": "xx-xx",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.2",
    "@angular/animations": "^6.0.1",
    "@angular/cdk": "6.0.1",
    "@angular/common": "^6.0.1",
    "@angular/compiler": "^6.0.1",
    "@angular/core": "^6.0.1",
    "@angular/forms": "^6.0.1",
    "@angular/http": "^6.0.1",
    "@angular/material": "6.0.1",
    "@angular/platform-browser": "^6.0.1",
    "@angular/platform-browser-dynamic": "^6.0.1",
    "@angular/router": "^6.0.1",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@types/googlemaps": "^3.30.8",
    "algebra.js": "^0.2.6",
    "bootstrap": "^4.1.1",
    "core-js": "^2.5.6",
    "mathjs": "^4.2.2",
    "ng2-dnd": "^5.0.2",
    "rxjs": "^6.1.0",
    "rxjs-compat": "^6.1.0",
    "select2": "^4.0.6-rc.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/compiler-cli": "^6.0.1",
    "@angular/language-service": "^6.0.1",
    "@types/jasmine": "~2.8.7",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.1",
    "@types/jqueryui": "^1.12.2",
    "@types/node": "~10.0.8",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "protractor": "~5.3.2",
    "ts-node": "~6.0.3",
    "tslint": "~5.10.0",
    "typescript": "~2.8.3"
  }
}
```

**Comment by meewyczawski** [comment]
This is probably caused due to your version of TypeScript. Please uninstall TypeScript 2.8.3 and install e.g. TypeScript 2.7.2

**Comment by Toso82** [comment]
@meewyczawski  It could be but it is strange. Because just do a modify in my code and compile well without error

**Comment by VRaj23** [comment]
Hi All,

I am facing same problem  after upgrading angular 5 project to angular 6.0.1

Current Version:

Angular CLI: 6.0.1
Node: 10.0.0
OS: linux x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.1
@angular-devkit/core         0.6.1
@angular-devkit/schematics   0.6.1
@schematics/angular          0.6.1
@schematics/update           0.6.1
rxjs                         6.1.0
typescript                   2.7.2
webpack                      4.6.0


Error on running ng serve or ng build --prod:

`ng serve
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(project).
Error: Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(project).
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/@angular-devkit/core/src/workspace/workspace.js:173:42)
    at MergeMapSubscriber._tryNext (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/operators/mergeMap.js:122:27)
    at MergeMapSubscriber._next (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/operators/mergeMap.js:112:18)
    at MergeMapSubscriber.Subscriber.next (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MergeMapSubscriber.notifyNext (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/operators/mergeMap.js:141:26)
    at InnerSubscriber._next (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/InnerSubscriber.js:30:21)
    at InnerSubscriber.Subscriber.next (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/Subscriber.js:103:18)
    at SwitchMapSubscriber.notifyNext (/home/varad/code/retail_shop/RetailShopFrontend/node_modules/rxjs/internal/operators/switchMap.js:122:26)
`

**Comment by alan-agius4** [comment]
As @meewyczawski currently mentioned it's due to the TypeScript version as the Angular 6 compiler only supports TypeScript >=2.7.2 and <2.8.0.

That said, if you can suppress this error by using `https://angular.io/guide/aot-compiler#disabletypescriptversioncheck`

https://angular.io/guide/aot-compiler#disabletypescriptversioncheck
