### ISSUE TITLE
typescript 2.8.3

### ISSUE THREAD

**Issue by bbuehrer** [angular/angular-cli#10839]
Is it compatible with typescript 2.8.3 ?

**Comment by Toso82** [comment]
@bbuehrer With me give not compile first time and after a change work well.  
https://github.com/angular/angular-cli/issues/10836

It is suggest typescript version:
`The` Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.8.3 was found instead

**Comment by norbert-tasi** [comment]
I have also 

> ERROR in The Angular Compiler requires TypeScript >=2.7.2 and <2.8.0 but 2.8.3 was found instead.

Angular and cli are up-to-date versions.

**Comment by DSchroer** [comment]
Same here.
It would be nice to have this error downgraded to a warning. It seems to be a bug in the build process more than anything else. As of right now its holding us back from upgrading to Angular 6.

**Comment by clydin** [comment]
The Angular AOT Compiler v6.0.x only officially supports TypeScript 2.7.x.  Using any other version is not guaranteed to function properly.  However, if using TypeScript 2.8 is preferred, the error can be disabled by using the `disableTypeScriptVersionCheck` option within `angularCompilerOptions` inside the application's `tsconfig`.

**Comment by bbuehrer** [comment]
@clydin :
Error: tsconfig.json(11,5): error TS5023: Unknown compiler option 'disableTypeScriptVersionCheck'.

**Comment by DSchroer** [comment]
Worked for me. Make sure that you set it in `tsconfig.app.json` and not `tsconfig.json`.

**Comment by clydin** [comment]
Example of an augmented new project application's config:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true
  }
}
```

**Comment by bbuehrer** [comment]
Ok, i set it in the tsconfig.app.json and it work.
Thanks
