### ISSUE TITLE
lot of time to load components..

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#10835]
i have 50 components in a module 

it taking nearly 10-12 seconds time..

i can't divide into multiple parts b'coz all are related..

can any one help me to reduce load time..

angular version 4.4.3

**Comment by Brocco** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by adityarw** [comment]
it is a bug it is taking lot of time to load all 50 components..

**Comment by adityarw** [comment]
it is a bug it is taking lot of time to load all 50 components..
