### ISSUE TITLE
I am Getting an Error when installing Angular

### ISSUE THREAD

**Issue by mhdasif** [angular/angular-cli#10830]
**Versions**
Node  v8.4.0
npm  v3.3.12

Error Log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Muhammed Asif\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@3.3.12
3 info using node@v8.4.0
4 verbose stack Error: Cannot find module 'internal/fs'
4 verbose stack     at Function.Module._resolveFilename (module.js:489:15)
4 verbose stack     at Function.Module._load (module.js:439:25)
4 verbose stack     at Module.require (module.js:517:17)
4 verbose stack     at require (internal/module.js:11:18)
4 verbose stack     at evalmachine.<anonymous>:40:20
4 verbose stack     at Object.<anonymous> (C:\Users\Muhammed Asif\AppData\Roaming\npm\node_modules\npm\node_modules\cmd-shim\node_modules\graceful-fs\fs.js:11:1)
4 verbose stack     at Module._compile (module.js:573:30)
4 verbose stack     at Object.Module._extensions..js (module.js:584:10)
4 verbose stack     at Module.load (module.js:507:32)
4 verbose stack     at tryModuleLoad (module.js:470:12)
5 verbose cwd C:\Users\Muhammed Asif
6 error Windows_NT 10.0.16299
7 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Muhammed Asif\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
8 error node v8.4.0
9 error npm  v3.3.12
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'internal/fs'
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]

**Comment by AhnpGit** [comment]
You should update your `NodeJs`. Angular v6 released with breaking changes that minimum version of `NodeJs` is 8.9+. You can check here https://github.com/angular/angular-cli/commit/29338bca7fcb24691254831c8d768821fc571875

**Comment by Brocco** [comment]
Minimum versions are:
node 8.9.9
npm 5.5.1

A PR is pushed to update this information.

**Comment by Brocco** [comment]
PR mentioned above has been merged... closing!
