### ISSUE TITLE
Angular 6.0.0 Build problems when using typed-rest-client library

### ISSUE THREAD

**Issue by cryo75** [angular/angular-cli#10844]
### Versions
```
Angular CLI: 6.0.0
Node: 8.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.0
@angular/cdk                       6.0.1
@angular/flex-layout               6.0.0-beta.15
@angular/material                  6.0.1
@angular/material-moment-adapter   6.0.1
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0
@schematics/update                 0.6.0
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0
```

### Repro steps
* Step 1: Create Angular 6.0.0 project
* Step 2: Install typed-rest-client
* Step 3: Add the following code in a component:

`import * as hm from 'typed-rest-client/Handlers';
import * as httpm from 'typed-rest-client/HttpClient';

    async run() {
        const username = '';
        const password = '';
        const workstation = '';
        const domain = '';
        const url = '';

        const ntlmHandler: hm.NtlmCredentialHandler = new hm.NtlmCredentialHandler(username, password, workstation, domain);

        const httpClient: httpm.HttpClient = new httpm.HttpClient('vsts-node-api', [ntlmHandler]);
        const response: httpm.HttpClientResponse = await httpClient.get(url);
        console.log('response code: ' + response.message.statusCode);
    }`

* Step 4: Run "ng build"

### Observed behavior
The following errors on build:

ERROR in ./node_modules/typed-rest-client/opensource/node-http-ntlm/ntlm.js
Module not found: Error: Can't resolve 'crypto' in 'C:\app\node_modules\typed-rest-client\opensource\node-http-ntlm'
ERROR in ./node_modules/typed-rest-client/HttpClient.js
Module not found: Error: Can't resolve 'fs' in 'C:\app\node_modules\typed-rest-client'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'http' in 'C:\app\node_modules\tunnel\lib'
ERROR in ./node_modules/typed-rest-client/HttpClient.js
Module not found: Error: Can't resolve 'http' in 'C:\app\node_modules\typed-rest-client'
ERROR in ./node_modules/typed-rest-client/handlers/ntlm.js
Module not found: Error: Can't resolve 'http' in 'C:\app\node_modules\typed-rest-client\handlers'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'https' in 'C:\app\node_modules\tunnel\lib'
ERROR in ./node_modules/typed-rest-client/HttpClient.js
Module not found: Error: Can't resolve 'https' in 'C:\app\node_modules\typed-rest-client'
ERROR in ./node_modules/typed-rest-client/handlers/ntlm.js
Module not found: Error: Can't resolve 'https' in 'C:\app\node_modules\typed-rest-client\handlers'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'net' in 'C:\app\node_modules\tunnel\lib'
ERROR in ./node_modules/tunnel/lib/tunnel.js
Module not found: Error: Can't resolve 'tls' in 'C:\app\node_modules\tunnel\lib'

### Desired behavior
Should build successfully.

**Comment by clydin** [comment]
The library in question appears to be a Node.js library and not a browser library.  The modules referenced above do not exist within a web browser.  If the library is, in fact, intended to be used within a browser, then it should provide a build which is browser compatible within the package (preferable referenced via the `browser` property within `package.json`).
