### ISSUE TITLE
[Angular CLI: 6.0.0] ng lint Invalid lint configuration. Nothing to lint.

### ISSUE THREAD

**Issue by akinorew** [angular/angular-cli#10842]
### Versions
```
Angular CLI: 6.0.0
Node: 9.0.0
OS: darwin x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

macOS (High Sierra)
```

### Repro steps

Running ng lint.
The files are linted but there is still an error "Invalid lint configuration. Nothing to lint.". Same effect when success and error.

```
      "lint": {
                    "builder": "@angular-devkit/build-angular:tslint",
                    "options": {
                        "tslintConfig": "tslint.json",
                        "tsConfig": [
                            "tsconfig.app.json"
                        ],
                        "files": [
                            "source/**/*.ts"
                        ],
                        "exclude": [
                            "source/**/*.spec.ts",
                            "source/**/*.mock.ts"
                        ]
                    }
                }
```

### Observed behavior
<img width="400" alt="screen shot 2018-05-14 at 15 19 55" src="https://user-images.githubusercontent.com/3313388/39999862-8117f140-578a-11e8-9390-85b34c6ba288.png">

**Comment by adamkundrat** [comment]
I'm experiencing same error. Any ideas what it might be? It seems to be processing the files but at the end it throws this error message.

**Comment by GerritK** [comment]
Same error here. Would be nice to see it fixed soon.

**Comment by AlexGS74** [comment]
As far as I understand, **ng lint** command runs lint configs for all projects. By default, even if you created just one, you actually have two configured in **angular.json**: the main and e2e version. I can imagine if you add no e2e test it will complain about wrong configuration as there is no single test to run.

I'd say it's not a bug. To workaround, you can:
1. Add a e2e test spec,
2. Or remove e2e configuration if you don't plan to do e2e at all;
3. Or run linting per project: **ng lint project-name**

**Comment by akinorew** [comment]
@AlexGS74 Thank you for that explanation. It fixed my issue, I just removed lint for e2e tests. Would it be possible to add to that error message name of the project, so that it's easier to figure out what is going on?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
