### ISSUE TITLE
Can not unpack a library

### ISSUE THREAD

**Issue by mailok** [angular/angular-cli#10846]
### Versions
```
Angular CLI: 6.0.0
Node: 8.9.4
OS: win32 x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

```

### Repro steps

* Create a new project: ng new test-lib
* Create a new Lib: ng generate library my-lib
* Add a function to a service created in my-lib

```
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MyLibService {

  constructor() {
  }

  print() {
    console.log('Test library');
  }
}

```

* Compile my library: ng build my-lib --prod

* Then: cd dist/my-lib, npm publish

* Import in another proyect: npm i --save my-lib

### Observed behavior

**Does not install**

![captura](https://user-images.githubusercontent.com/3769277/40008462-5fb56fb8-576d-11e8-91df-7e43c78fd995.PNG)

Then I tried another way:

*  cd dist/my-lib
* npm pack .
* copy  my-lib-0.0.1.tgz inside my other proyect
* and install: npm i --save -d ./my-lib-0.0.1.tgz
* and get the same error
[2018-05-14T15_56_51_406Z-debug.log](https://github.com/angular/angular-cli/files/2001583/2018-05-14T15_56_51_406Z-debug.log)

Why???!!

**Comment by filipesilva** [comment]
Heya, I was looking into this problem and I could not reproduce. Can you upload a repro that shows this behaviour?

It's also important to mention that `ng-packagr@3.0.0` does not generate the `.tgz` file automatically anymore (https://github.com/dherges/ng-packagr/issues/802).

But you can do it yourself with `npm pack ./dist/my-lib`, and then you can install that file via `npm install ./my-lib-0.0.1.tgz`. When I did this I didn't see the errors you saw.

**Comment by mailok** [comment]
@filipesilva I tried reproduce, but I could not reproduce. I remove all my node_modules of my proyect and ejectute npm install -d,  and it working properly, so now I have no idea why he gave me that error.

**Comment by filipesilva** [comment]
Maybe it was some kind of network problem at the time? If you get it again and can reproduce let me know and I will reopen.
