### ISSUE TITLE
Update wiki page documentation

### ISSUE THREAD

**Issue by sunilpes** [angular/angular-cli#10841]
### Versions
```
Angular CLI: 6.0.1
Node: 8.9.0
OS: darwin x64 (Mac)
Angular: 6.0.1
```

### Repro steps
1. run `ng --help` it list the following commands:
* add: Add support for a library to your project.
*  new: Creates a new directory and a new Angular app.
* generate: Generates and/or modifies files based on a schematic.
* update: Updates your application and its dependencies.
*  build: Builds your app and places it into the output path (dist/ by default).
*  serve: Builds and serves your app, rebuilding on file changes.
*  test: Run unit tests in existing project.
*  e2e: Run e2e tests in existing project.
*  lint: Lints code in existing project.
*  xi18n: Extracts i18n messages from source code.
*  run: Runs Architect targets.
*  eject: Temporarily disabled. Ejects your app and output the proper webpack configuration and scripts.
*  config: Get/set configuration values.
*  help: Help.
*  version: Outputs Angular CLI version.
*  doc: Opens the official Angular API documentation for a given keyword.

### Observed behavior
```
Lack of documentation for the following commands in the wiki page:
1. ng run 
2. ng add
3. ng eject

and 

1. `ng run --help` throws the error 
Cannot determine project or target for Architect command.
Error: Cannot determine project or target for Architect command.
```

### Desired behavior
```
Please provide appropriate documentation for the listed commands on the wiki page.
and

1. `ng run --help` command should show help manual.

and 

Running test case for the projects inside the workspace should be documented on the wiki
e.g: `ng test my-lib` run test cases for my-lib project



```

**Comment by thefliik** [comment]
So after checking out the source code, it appears that `ng run` expects one argument in the form `project_name:architect_target`. For example, if your `angular.json` had something like this:
```
  "projects": {
    "login": {
      "architect": {
        "build": { ... },
        ...
      },
      ...
    },
    ...
  }
```

You could `ng run login:build` (which appears to be the same as calling `ng build login`). I also notice that different architect targets like `"serve"` contain an `"options"` object with a `"browserTarget"` of the same form (i.e. `"login:build"`). So perhaps `ng run` is being used behind the scenes when you call other commands (like `ng build login`). I'm just speculating.

**Comment by macjohnny** [comment]
I got a similar error. Executing the command
```
ng build --target=production --configuration=prod --aot=true --source-map=true
```
resulted in 
```
Error: Cannot determine project or target for Architect command.
```
I finally found that I needed to change the command to
```
ng run my-project:build:prod --target=production --aot=true --source-map=true
```
The wiki page about `ng run` is outdated.

**Comment by eranation** [comment]
What's really bugs me is that they have a defaultProject property, ng run et al should use that as the, well, default instead of throwing an error

**Comment by thefliik** [comment]
@eranation that wouldn't be enough to fix this issue. You need to pass a project and architect target to `ng run`.

**Comment by cmckni3** [comment]
[ng lint wiki page](https://github.com/angular/angular-cli/wiki/lint) is missing the `--project` option available in ng cli 6.x.

**Comment by alan-agius4** [comment]
Hi all, Documentation for the CLI has been moved to https://angular.io/cli.
