### ISSUE TITLE
Feature proposal: Install given Angular version

### ISSUE THREAD

**Issue by DanielKucal** [angular/angular-cli#10857]
That's actually a feature proposal. I have a library and want it to be compatible with let's say last 3 Angular versions. There is a breaking change in the compiler, so I have to manually install proper version for every Angular package separately. Instead I'd like to have a command like `ng version 4` that will install Angular4 packages. The final use case is to have publishing scripts like:
```
"publish:4": "ng version 4 && npm run build && npm publish --tag v4",
"publish:5": "ng version 5 && npm run build && npm publish --tag v5",
"publish:6": "ng version 6 && npm run build && npm publish --tag v6",
```
I was googling for "angular version manager" but unsuccessfully. What do you think?

**Comment by alan-agius4** [comment]
If you want version X of angular, then install version X of the CLI. 

We feel that the latest version of Angular is always the most appropriate one to use.
