### ISSUE TITLE
ng new <project>

### ISSUE THREAD

**Issue by jardoHS** [angular/angular-cli#10856]
### Versions

Angular CLI: 6.0.1
Node: 10.1.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.1
@angular-devkit/core         0.6.1
@angular-devkit/schematics   0.6.1
@schematics/angular          0.6.1
@schematics/update           0.6.1
rxjs                         6.1.0
typescript                   2.7.2

### Repro steps
C:\>ng new exam1
CREATE exam1/angular.json (3396 bytes)
CREATE exam1/package.json (1309 bytes)
CREATE exam1/README.md (1022 bytes)
CREATE exam1/tsconfig.json (384 bytes)
CREATE exam1/tslint.json (2805 bytes)
CREATE exam1/.editorconfig (245 bytes)
CREATE exam1/.gitignore (503 bytes)
CREATE exam1/src/environments/environment.prod.ts (51 bytes)
CREATE exam1/src/environments/environment.ts (631 bytes)
CREATE exam1/src/favicon.ico (5430 bytes)
CREATE exam1/src/index.html (292 bytes)
CREATE exam1/src/main.ts (370 bytes)
CREATE exam1/src/polyfills.ts (3194 bytes)
CREATE exam1/src/test.ts (642 bytes)
CREATE exam1/src/assets/.gitkeep (0 bytes)
CREATE exam1/src/styles.css (80 bytes)
CREATE exam1/src/browserslist (375 bytes)
CREATE exam1/src/karma.conf.js (964 bytes)
CREATE exam1/src/tsconfig.app.json (194 bytes)
CREATE exam1/src/tsconfig.spec.json (282 bytes)
CREATE exam1/src/tslint.json (314 bytes)
CREATE exam1/src/app/app.module.ts (314 bytes)
CREATE exam1/src/app/app.component.html (1141 bytes)
CREATE exam1/src/app/app.component.spec.ts (986 bytes)
CREATE exam1/src/app/app.component.ts (207 bytes)
CREATE exam1/src/app/app.component.css (0 bytes)
CREATE exam1/e2e/protractor.conf.js (752 bytes)
CREATE exam1/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE exam1/e2e/src/app.po.ts (208 bytes)
CREATE exam1/e2e/tsconfig.e2e.json (213 bytes)

> node-sass@4.9.0 install C:\exam1\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\Gerardo\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-64_binding.node

> node-sass@4.9.0 postinstall C:\exam1\node_modules\node-sass
> node scripts/build.js

Binary found at C:\exam1\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> @angular/cli@6.0.1 postinstall C:\exam1\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN rollback Rolling back node-pre-gyp@0.9.1 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\exam1\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1081 packages from 1274 contributors in 159.373s
[!] 14 vulnerabilities found [21355 packages audited]
    Severity: 10 Low | 4 High
    Run `npm audit` for more detail

    Successfully initialized git.

### Desired behavior
packages installed successful

**Comment by Brocco** [comment]
FYI, there are no NPM errors here, just some warnings.

As for the vulnerabilities message that is being tracked in another issue.
