### ISSUE TITLE
schematics does not generate help for $default argument

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#10854]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
macOS HS,
node: 10.1.0
npm: 6.0.1

### Repro steps
ng g c -h

### The log given by the failure
Does not generate help (description) with $default argv (`<name>` in this case)
```
usage: ng generate c <name> [options]
options:
  --change-detection (-c)
    Specifies the change detection strategy.
  --dry-run (-d)
    Run through without ...
```

### Desired functionality

Show help that written in 'description' of $default argv in schema

**Comment by Brocco** [comment]
@sandangel

**Comment by alan-agius4** [comment]
This looks like it's been solved in the latest beta

```bash
usage: ng generate c <name> [options]
arguments:
  schematic
    The schematic or collection:schematic to generate.
  name
    The name of the component.
options:
  --change-detection (-c)
    Specifies the change detection strategy.
  --dryRun (-d)
....
```

**Comment by alan-agius4** [comment]
Closing as per above comment.
