### ISSUE TITLE
Import ES6 module globally

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular-cli#10863]
Hello,

is there any way how to import ES6 javascript module globally?

When I insert it into _scripts_ in _.angular-cli.json_ file, it throws error. (import in .js file is Uncaught SyntaxError: Unexpected string).

**Comment by filipesilva** [comment]
Heya, global scripts are for things that would be put as a script tag directly in a webpack. It doesn't support ES modules. I know some browsers now support it, but that's outside of our scripts functionality.
