### ISSUE TITLE
Improve example on wiki page for stylePreprocessorOptions.includePaths

### ISSUE THREAD

**Issue by slavafomin** [angular/angular-cli#10868]
Hello!

The example on the ["stories global styles"](https://github.com/angular/angular-cli/wiki/stories-global-styles) wiki page could be improved. I would suggest to add the `root` property to the examples, because it affects the paths resolution process and the example wouldn't be complete without it.

I naively tried to copy the example for `includePaths`, but it failed for me, because in my case the `root` property was pointing to another base directory (`./src`), so I have to remove the `./src/` part from my `includePaths`. It's not a big deal, but could be a time waster for quick searchers like me.

**Comment by rainstormza** [comment]
In angular 7 I have to remove "src/".

Like this
`"stylePreprocessorOptions": {
  "includePaths": [
    "style-paths"
  ]
},`

It will work.

@filipesilva

**Comment by tiaguinho** [comment]
@mgechev I think this issue is blocked since there will be changes on the CLI wiki.

**Comment by alan-agius4** [comment]
Closing as this is obsolete. New docs can be found https://next.angular.io/guide/workspace-config
