### ISSUE TITLE
ng build --prod.   ERROR in Error during template compile of 'ɵe'...

### ISSUE THREAD

**Issue by nickraphael** [angular/angular-cli#10866]
### Versions
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.1
Node: 9.5.0
OS: win32 x64
Angular: 6.0.1
... cdk, cli, common, compiler, compiler-cli, core, forms, http
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/animations               6.0.0
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
* Step 1
ng build --prod

### Observed behavior
```
Date: 2018-05-15T11:03:17.349Z
Hash: 213f86e0cbc775837a34
Time: 20927ms
chunk {scripts} scripts.de5314edceb29a27db2f.js (scripts) 123 kB  [rendered]
chunk {0} runtime.6afe30102d8fe7337431.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.4cfead7b18b77f2f5148.css (styles) 334 kB [initial] [rendered]
chunk {2} main.8301efec6ec2f3742cda.js (main) 128 bytes [initial] [rendered]

ERROR in Error during template compile of 'ɵe'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'Injectable'
    'Injectable' calls 'ɵmakeDecorator'.
```

### Desired behavior
I'd obviously like it to build.  But if there is an error in my code, I'd like some indication of where the error is.  The provided error does not give any information regarding where the error lies.  I've removed all function calls in my module decorators - I think.  I have a large number of lazy loaded modules.

**Comment by nickraphael** [comment]
By the looks or 'ERROR in Error', I say that the code that resolves the problem file has errored.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no re-production was provided.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by christophstockinger** [comment]
https://github.com/angular/angular/issues/32134
