### ISSUE TITLE
Firefox Broken Styles

### ISSUE THREAD

**Issue by MrJmpl3** [angular/angular-cli#10860]
### Versions
```
Windows 10
Angular 6.0.1
```

### Repro steps
* In styles.scss
```
.test {
 @import "datepicker.scss";
}
```

* In datepicker.scss
```
/* This comment is
 * several lines long.
 * since it uses the CSS comment syntax,
 * it will appear in the CSS output. */
 
/*!
 * Datetimepicker for Bootstrap 3
 * version : 4.17.37
 * https://github.com/Eonasdan/bootstrap-datetimepicker/
 */
 
// First element
.bmd-layout-canvas {
  // added by js?
  position: absolute;
  width: 100%;
  height: 100%;
}
```
- But in Firefox , the comments styles has broken

```
/* This comment is
 * several lines long.
 * since it uses the CSS comment syntax,
 * it will appear in the CSS output. */
  * Datetimepicker for Bootstrap 3
 * version : 4.17.37 * https: //github.com/Eonasdan/bootstrap-datetimepicker/;
.test .bmd-layout-canvas {
    position: absolute;
    width: 100%;
    height: 100%;
}
```
- Look , some parts in comments is delete

**UPDATE**

I fix:
* In styles.scss
```
 @import "datepicker.scss";
```

* In datepicker.scss
```
.test {
 /* This comment is
  * several lines long.
  * since it uses the CSS comment syntax,
  * it will appear in the CSS output. */
 
 /*!
  * Datetimepicker for Bootstrap 3
  * version : 4.17.37
  * https://github.com/Eonasdan/bootstrap-datetimepicker/
  */
 
 // First element
 .bmd-layout-canvas {
   // added by js?
   position: absolute;
   width: 100%;
   height: 100%;
 }
}
```

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
