### ISSUE TITLE
ng upgrade: incompatible peer dependency error prevents from auto-updating

### ISSUE THREAD

**Issue by juristr** [angular/angular-cli#10875]
### Versions
```
Angular CLI: 6.0.1
Node: 9.11.1
OS: darwin x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              5.5.10
typescript                        2.5.3
webpack                           4.6.0


macOS 10.11.6
```

### Repro steps

* Clone the `upgrade` branch of repo https://github.com/juristr/ng-upgrade-test
* `yarn install` (or `npm install` => I used yarn)
* Try upgrading the Angular dependencies, using for instance `ng update @angular/core`. I already performed the `@angular/cli` upgrade command which adjusts the `angular.json` etc.

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

I get the following output

```
❯ ng update @angular/core
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.5.3")
Incompatible peer dependencies found. See above.
```

### Desired behavior

It should automatically update the Angular dependencies as well as RxJS and TypeScript (as described in the `update.angular.io` guide).

**Comment by juristr** [comment]
@clydin Hi, I was chatting about this in the Angular Slack with @filipesilva and he told me to open the issue here

**Comment by brandonroberts** [comment]
I'm running into a similar issue when trying to update NgRx.

I run `ng update @ngrx/store --next` and I get

```
Package "@ngrx/schematics" has a missing peer dependency of "@angular-devkit/core" @ "^0.6.0".
```

If I run `yarn list @angular-devkit/core`, I see 

```
@angular-devkit/core@0.6.1
```

**Comment by intellix** [comment]
Not sure if it's the same thing, but I'm getting errors like:

```
Package "bootstrap" has a missing peer dependency of "jquery" @ "1.9.1 - 3".
```

I'm using the bootstrap SCSS framework but have no intentions of ever including jQuery ofc. I dunno if this is a problem with bootstrap itself that it has jquery as a peerDep or if CLI is being too anal about installing them all.

Is it perhaps possible to just force the `ng update --all`?

**Comment by Teamop** [comment]
I have the same issue, but instead run `ng update @angular/compiler-cli` successfully without error.

**Comment by getabetterpic** [comment]
I'm running into this issue as well, seems the updater is trying to install `typescript@2.8.3` but `@angular/compiler-cli` has a peer dependency of `typescript@">=2.7.2 <2.8"`.

**Comment by sachinpachori** [comment]
When I ran "ng update @angular/core" got the following errors and cannot upgrade to angular 6:
Package "angular2-resizable" has an incompatible peer dependency to "@angular/core" (requires ">=3.0.0-rc.0 <4.0.0||>=2.0.0 <3.0.0", would install "6.0.2").
Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.2").

**Comment by sachinpachori** [comment]
@brandonroberts @clydin thank you that solved my issue.

**Comment by HarryWang74** [comment]
**ng update @angular/core --next --force** works for me

**Comment by Sharondio** [comment]
I'm doing a fresh install of my npm modules, and running into this issue:

```
$ npm install -g @ngrx/schematics@latest
npm WARN @ngrx/schematics@6.0.1 requires a peer of @angular-devkit/core@^0.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/schematics@6.0.1 requires a peer of @angular-devkit/schematics@^0.6.0 but none is installed. You must install peer dependencies yourself.
```
@angular-devkit/schematics@0.6.8 is installed.

**Comment by Sharondio** [comment]
@clydin They are installed globally. Still getting error.

**Comment by clydin** [comment]
If `npm ls -g --depth=0` doesn't show the warnings then everything should be fine.
Please note that this is actually an `npm` issue (and possible a defect) and not a CLI issue.

**Comment by matheo** [comment]
So I figured out that `ng update --all` doesn't work as expected,
so you better upgrade everything in order:
```
yarn global @angular/cli
ng update @angular/cli
yarn upgrade tsickle
ng update @angular/core
ng update @angular/material
ng update rxjs
yarn add @angular-devkit/schematics@^0.6.0 --dev
ng update @ngrx/store
ng update @nrwl/nx
```
Note that I had to update some dependencies because `@angular/core` installs `typescript 2.9.2` and the version I had of `tsickle` didn't supported it:
```
Package "tsickle" has an incompatible peer dependency to "typescript" (requires ">=2.4.2 <2.9", would install "2.9.2").
```
and also `@ngrx/store` had a missing dependency:
```
Package "@ngrx/schematics" has a missing peer dependency of "@angular-devkit/schematics" @ "^0.6.0".
```

**Comment by prasanthlouis** [comment]
If anyone's still running into this error you could just run

npm i --save-dev codelyzer@4.0.1

instead of forcing ng update which ignores those warnings.

**Comment by asmaa3107** [comment]
it gave me a successful serve but in browser I got this error
```
AppComponent.html:1 ERROR TypeError: (intermediate value).switchMap is not a function
    at new AngularFireAuth (auth.js:21)
    at _getAngularFireAuth (auth.module.js:6)
    at _callFactory (core.js:16720)
    at _createProviderInstance (core.js:16676)
    at resolveNgModuleDep (core.js:16636)
    at _createClass (core.js:16709)
    at _createProviderInstance (core.js:16673)
    at resolveNgModuleDep (core.js:16636)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:17345)
    at resolveDep (core.js:17716) 
```

**Comment by leonardox12** [comment]
ng update @angular/cli@version --force it worked for me

**Comment by sameersayani** [comment]
ng update --all --force this worked for me.

**Comment by odahcam** [comment]
Happening on update to Angular 7 and TypeScript 3.1 too.

**Comment by sameersayani** [comment]
Wow that's great news!

**Comment by odahcam** [comment]
The update with `--force` does work, but some packages like `ng-packagr` breaks due to `tsickle` version.

**Comment by demonguru18** [comment]
ng update @angular/cli  this will do the trick

**Comment by odahcam** [comment]
At this time, just the update as @demonguru18 said should work.

**Comment by demonguru18** [comment]
Here is an Starter Project I created for Asp.net Core 2.1, Angular 7.0.3 and Bootstrap 4.1.3 You can download this project and start. In case you want to start from scratch
https://github.com/demonguru18/Angular7DotNetCore2.1BootStrap4

If updating old project, follow this
 
first run ng update --all
then run ng update @angular/cli
Make sure you have update version of Jquery to run Bootsrap 4 
Cheers 👍

**Comment by arulsuju** [comment]
> Not sure if it's the same thing, but I'm getting errors like:
> 
> ```
> Package "bootstrap" has a missing peer dependency of "jquery" @ "1.9.1 - 3".
> ```
> I'm using the bootstrap SCSS framework but have no intentions of ever including jQuery ofc. I dunno if this is a problem with bootstrap itself that it has jquery as a peerDep or if the problem is that CLI throws for peer dep WARN.
> 
> Is it perhaps possible to just force the `ng update --all`?

try 

> npm install --save bootstrap

**Comment by sanjaytarani0** [comment]
I've tried executing ng update --all --force but I still get the error

**Tried:**
ng update @angular/core --force

UPDATE package.json (1579 bytes)

npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, rmdir 'C:\Users\Ben\Projects\QuixxiStaging\node_modules\fsevents\node_modules'
npm WARN angular2-ladda@2.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.1 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.1 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.1 requires a peer of @angular/platform-browser-dynamic@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.1 requires a peer of @angular/platform-browser@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@4.0.1 requires a peer of @angular/common@^2.3.1 || >=4.0.0-beta <6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by codemcu** [comment]
Hi, be careful with this command, 
ng update @ angular / core --next --force, 
I have used it to update from Angular 4 to 7 and now I have version 8.0.0-beta.3

**Comment by briancodes** [comment]
@codemcu The `--next` flag is probably not what most people here want. From the Angular [docs](https://angular.io/cli/update)

> --next=true|false Use the largest version, including beta and RCs. Default false

**Comment by adhivenkatesh** [comment]
when bootstrapping angular application


What are the order priorites while bootstrapping and main-usage of those file, if any one knows Please clearly explain.

index.js
main.ts,

package.json,

tsconfig.json,

tsconfig.app.json,

tsconfig.spec.json,

angular.json

**Comment by Splaktar** [comment]
@adhivenkatesh the [Angular Bootstapping Guide](https://angular.io/guide/bootstrapping) might be helpful as well as the [Project File Structure Guide](https://angular.io/guide/file-structure). However, I'm not sure that they address that exact question.

**Comment by adhivenkatesh** [comment]
Yes , splaktar, good day, thanks for your revert, i will go through the angular bootstrapping guide, thank you.

**Comment by adhivenkatesh** [comment]
Hi  i think some of the files corrected i am using angular 7 version ,  
i have tried in many angles deleted directory and remove ng_modules and installed npm command also nothing happened , here i also used npm cache clean --force , then remove ng_modules then npm install , 
i have created 3 new projects and again getting the same issue 
please help with best solution ,

======================= error =============
ERROR in node_modules/rxjs/src/internal/scheduled/scheduled.ts(25,40): error TS2345: Argument of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerAction<T>' is not assignable to type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/Subscription").Subscription'.
                Type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/Subscription").Subscription' is not
assignable to type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(27,37): error TS2345: Argument of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(29,35): error TS2345: Argument of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(31,38): error TS2345: Argument of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/observable/from.ts(116,29): error TS2345: Argument of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/types").SchedulerAction<T>' is not assignable to type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/Subscription").Subscription'.
                Type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/src/internal/Subscription").Subscription' is
not assignable to type 'import("D:/AngularProjects/AngularRouting/Routing/node_modules/rxjs/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.
========================

**Comment by Splaktar** [comment]
@adhivenkatesh please open a new issue with a reproduction.

**Comment by Riccardo-Andreatta** [comment]
I am getting the same error when I am upgrading from version 5 to version 6 but running `ng update @angular/core --next --force` is forcing update to the latest release: is there a workaround to update just to the version I want?

**Comment by Splaktar** [comment]
@Riccardo-Andreatta `ng update @angular/core --from=5 --to=6 --force`. See more details in `ng update --help` or https://angular.io/cli/update.

**Comment by cjonasw** [comment]
I didn't want to use --force as it installs betas and also one shouldn't have to.

I found a solution to the above that worked for me. I installed the latest codelyzer

`npm install codelyzer@latest`

then ran the `ng update @`whatever I needed to do and it worked with no complaints.

**Comment by adhivenkatesh** [comment]
Thanks charlie for your suggestion, will follow the suggestion when i get
any further issues/errors.




Thank You,

Adhi Venkatesh.,Banglore,India.

**Comment by ahmar-appify** [comment]
Reinstalling cli worked for me as it installed latest.
npm uninstall @angular/cli
npm install @angular/cli

after this all ng update worked

**Comment by Ferie** [comment]
@Splaktar I have tried the `--from` and `--to` options but they are not working: still they are upgrading directly to the last version available.

I had to install the specific version (`ng update @angular/core@6.1.0`) both for core and cli, and then update manually the `package.json` to update every single module that my application needs (`http`, `common`, `forms`, etc).

**Comment by clydin** [comment]
The `--from` and `--to` options will only affect the `--migrate-only` option.  CLI versions 8.0+ will now error if the options are used incorrectly.
