### ISSUE TITLE
Google crawler not crawling website or not rendering dynamic content into view page source of any browser

### ISSUE THREAD

**Issue by codershahezads90** [angular/angular-cli#10878]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

**Comment by Brocco** [comment]
You will need to provide some more information for the team to be to determine how to assist. I am closing this issue, but please feel free to open a new issue with more information.

With that being said, I believe the confusion lies in the fact that your app is being rendered in the client, not on the server. Viewing page source only represents what the server is delivering to the browser. If you'd like to render your application on the server, please start [here](https://angular.io/guide/universal).
