### ISSUE TITLE
ng serve --prod --source-map does not produce source maps

### ISSUE THREAD

**Issue by Maximaximum** [angular/angular-cli#10886]
### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.1
Node: 8.9.4
OS: win32 x64
Angular: 6.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@angular/flex-layout              5.0.0-beta.13
@ngtools/webpack                  6.0.1
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* Run `ng serve --prod --source-map`

### Observed behavior
The ouput js and css bundles do not contain the source maps.

### Desired behavior
The output bundles should contain the source maps, and the browser (Chrome) should recognize them.

**Comment by jmesa-sistel** [comment]
You can change it in angular.json in architect -> build -> "builder": "@angular-devkit/build-angular:browser" -> configurations -> production -> sourceMap

**Comment by Maximaximum** [comment]
Thank you, @jmesa-sistel. Indeed, it works. But:
1. Nowhere in the documentation could I find any information on this. It would be nice to add explicit documentation.
2. IMO, since there is a `--source-map` command-line flag, it should do something :smile: Anyway, it would be nice to have an ability to enable sourcemaps via CLI, without modifying the `angular.json` file.

**Comment by jmesa-sistel** [comment]
@Maximaximum 
Docs about new schemas system:
[https://github.com/angular/angular-cli/wiki/angular-workspace](https://github.com/angular/angular-cli/wiki/angular-workspace)
To understand how it works I used a json online viewer to understand the organization.
I have to say that this new config system is very powerful, I usually had to eject the configuration, now it is not needed for me.
Seems that the angular.json configuration has precedence over cli parameters, with --prod you select production configuration so --source-map parameter is overwritten , maybe it is a bug, I do not know.
