### ISSUE TITLE
ng new: "Please choose a version of [angular tool] from this list"

### ISSUE THREAD

**Issue by brownieboy** [angular/angular-cli#10895]
### Versions
```
Angular CLI: 6.0.1                                     
Node: 8.11.1                                           
OS: win32 x64                                          
Angular:                                               
                                             
                                                       
Package                      Version                   
------------------------------------------------------ 
@angular-devkit/architect    0.6.1                     
@angular-devkit/core         0.6.1                     
@angular-devkit/schematics   0.6.1                     
@schematics/angular          0.6.1                     
@schematics/update           0.6.1                     
rxjs                         6.1.0                     
typescript                   2.7.2
```

### Repro steps
* ng new mynewfoldername

That's it!

### Observed behaviour
After doing some initial installs, the CLI will prompt me for which version of some tool do I want to use, like so:
```
Please choose a version of "@ngtools/webpack" from this list: (Use arrow keys)
> 6.0.1
  6.0.0
  6.0.0-rc.11
  6.0.0-rc.10
  6.0.0-rc.9
  6.0.0-rc.8
  6.0.0-rc.7
  6.0.0-rc.6
  6.0.0-rc.5
  6.0.0-rc.4
  6.0.0-rc.3
  6.0.0-rc.2.4
  6.0.0-rc.2.3
  6.0.0-rc.2.2
  6.0.0-rc.2
  6.0.0-rc.1
  6.0.0-rc.0
  6.0.0-beta.9
  6.0.0-beta.8
  6.0.0-beta.7
  6.0.0-beta.6
  6.0.0-beta.5
  6.0.0-beta.4
  6.0.0-beta.3
  6.0.0-beta.2
  1.10.2
  1.10.1
  1.10.0
  1.10.0-rc.0
  1.10.0-beta.3
  1.10.0-beta.2
(Move up and down to reveal more choices)
```
Sometimes it's `@ngtools/webpack` that it asks about, as above.  Other times it's `@angular-devkit/core`.  Another time, I was asked this question about a dozen times in a row, each one for a different constituent Angular component.

### Desired behaviour
Should it not just install the latest stable versions of each component for a new project?  It was doing this for a while, and I wasn't seeing any of these prompts.  But then they came back.

**Comment by filipesilva** [comment]
That's pecurial, never seen this reported before. It seems related to Yarn. Do you have any custom yarn configuration, or some kind of proxy?

**Comment by brownieboy** [comment]
Yes, I am behind a proxy at work.  In fact, we use an internal Nexus mirror server for our NPM packages, so this may well be an issue with that. 

I will investigate further...

**Comment by brownieboy** [comment]
It's working for me now, after  I made a config change to my .yarnrc file. 

So here's the entries for our Nexus mirror server that were in my .npmrc file:
```
registry=http://acme.com/content/groups/public-npmjs/
@angular:registry=http://acme.com/content/groups/public-npmjs/
@types:registry=http://acme.com/content/groups/public-npmjs/
```

When I checked my .yarnrc file, however, I saw that I only had _one_ of the three equivalent entries there:

`registry "http://acme.com/content/groups/public-npmjs/"`

So, I updated my .yarnrc to add the missing entries for Angular, like so:
```
registry "http://acme.com/content/groups/public-npmjs/"
"@angular:registry" "http://acme.com/content/groups/public-npmjs/"
"@types:registry" "http://acme.com/content/groups/public-npmjs/"
```

That appears to have fixed things for now.  But as I said in the original report, the problem was intermittent anyway.  I'll close this one for now.
