### ISSUE TITLE
 API fatal error handler returned after process out of memory

### ISSUE THREAD

**Issue by germwire** [angular/angular-cli#10890]
1. Change angular.json styles to a custome material themed scss:
            `"styles": [
              "src/material-theme.scss"
            ]`

2.  Make the file size large example styles.js.map:

 "chunk {styles} styles.js, styles.js.map (styles) 101 MB [initial] [rendered]"

3. In command terminal type: ng serve

I would like faster builds and more memory allocated to the angular build process otherwise building project is impossible. 

package.json
{
  "name": "proj",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "dev": "node --max_old_space_size=5048 ./node_modules/@angular/cli/bin/ng serve",
    "build": "ng build",
    "master": "ng build --prod --build-optimizer --deploy-url=/static/",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.2",
    "@angular/cdk": "^6.0.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/material": "^6.0.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "chart.js": "^2.7.2",
    "core-js": "^2.5.6",
    "d3": "^5.4.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.2.1",
    "rxjs": "^6.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/core": "^0.6.1",
    "@angular-devkit/schematics": "^0.6.1",
    "@angular/cli": "^6.0.1",
    "@angular/compiler-cli": "^6.0.2",
    "@angular/language-service": "^6.0.2",
    "@types/d3": "^5.0.0",
    "@types/jasmine": "^2.8.7",
    "@types/jasminewd2": "^2.0.2",
    "@types/node": "^10.1.0",
    "codelyzer": "^4.3.0",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^2.0.2",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "protractor": "^5.3.2",
    "ts-node": "^6.0.3",
    "tslint": "^5.10.0",
    "typescript": "^2.8.3",
    "@angular-devkit/build-angular": "~0.6.1"
  }
}
### Versions
Windows 10)
@angular-devkit/architect              0.6.1
@angular-devkit/build-angular      0.6.1
@angular-devkit/build-optimizer   0.6.1
@angular-devkit/core                     0.6.1
@angular-devkit/schematics          0.6.1
@angular/cli                                   6.0.1
@ngtools/webpack                        6.0.1
@schematics/angular                     0.6.1
@schematics/update                      0.6.1
rxjs                                                  6.1.0
typescript                                        2.8.3
webpack                                         4.6.0
npm                                                6.0.0

### Additional details that might be useful (optional):
To make scss file large include this code:

@function get-primary-color($primary-name) {
  @if($primary-name=='pink') {
    @return mat-palette($mat-pink);
  }
  @else if($primary-name=='purple') {
    @return mat-palette($mat-purple);
  }
  @else if($primary-name=='deep-purple') {
    @return mat-palette($mat-deep-purple);
  }
  @else if($primary-name=='indigo') {
    @return mat-palette($mat-indigo);
  }
  @else if ($primary-name=='blue') {
    @return mat-palette($mat-blue);
  }
  @else if($primary-name=='light-blue') {
    @return mat-palette($mat-light-blue);
  }
  @else if($primary-name=='cyan') {
    @return mat-palette($mat-cyan);
  }
  @else if($primary-name=='teal') {
    @return mat-palette($mat-teal);
  }
  @else if($primary-name=='green') {
    @return mat-palette($mat-green);
  }
  @else if($primary-name=='light-green') {
    @return mat-palette($mat-light-green);
  }
  @else if($primary-name=='lime') {
    @return mat-palette($mat-lime);
  }
  @else if($primary-name=='yellow') {
    @return mat-palette($mat-yellow);
  }
  @else if($primary-name=='amber') {
    @return mat-palette($mat-amber);
  }
  @else if ($primary-name=='orange') {
    @return mat-palette($mat-orange);
  }
  @else if($primary-name=='deep-orange') {
    @return mat-palette($mat-deep-orange);
  }
  @else if($primary-name=='brown') {
    @return mat-palette($mat-brown);
  }
  @else if($primary-name=='grey') {
    @return mat-palette($mat-grey);
  }
  @else if($primary-name=='blue-grey') {
    @return mat-palette($mat-blue-grey);
  }
  @else if($primary-name=='black') {
    @return mat-palette($mat-grey, 900, 400, 700);
  }
  @else {
    @return mat-palette($mat-grey, 50, 400, 700);
  }
}

@function get-accent-color($accent-name) {
  @if($accent-name=='pink') {
    @return mat-palette($mat-pink, A200, A400, A700);
  }
  @else if($accent-name=='purple') {
    @return mat-palette($mat-purple, A200, A400, A700);
  }
  @else if($accent-name=='deep-purple') {
    @return mat-palette($mat-deep-purple, A200, A400, A700);
  }
  @else if($accent-name=='indigo') {
    @return mat-palette($mat-indigo, A200, A400, A700);
  }
  @else if ($accent-name=='blue') {
    @return mat-palette($mat-blue, A200, A400, A700);
  }
  @else if($accent-name=='light-blue') {
    @return mat-palette($mat-light-blue, A200, A400, A700);
  }
  @else if($accent-name=='cyan') {
    @return mat-palette($mat-cyan, A200, A400, A700);
  }
  @else if($accent-name=='teal') {
    @return mat-palette($mat-teal, A200, A400, A700);
  }
  @else if($accent-name=='green') {
    @return mat-palette($mat-green, A200, A400, A700);
  }
  @else if($accent-name=='light-green') {
    @return mat-palette($mat-light-green, A200, A400, A700);
  }
  @else if($accent-name=='lime') {
    @return mat-palette($mat-lime, A200, A400, A700);
  }
  @else if($accent-name=='yellow') {
    @return mat-palette($mat-yellow, A200, A400, A700);
  }
  @else if($accent-name=='amber') {
    @return mat-palette($mat-amber, A200, A400, A700);
  }
  @else if ($accent-name=='orange') {
    @return mat-palette($mat-orange, A200, A400, A700);
  }
  @else if($accent-name=='deep-orange') {
    @return mat-palette($mat-deep-orange, A200, A400, A700);
  }
  @else if($accent-name=='brown') {
    @return mat-palette($mat-brown, 500, 200, 700);
  }
  @else if($accent-name=='grey') {
    @return mat-palette($mat-grey, 500, 200, 700);
  }
  @else if($accent-name=='blue-grey') {
    @return mat-palette($mat-blue-grey, 500, 200, 700);
  }
  @else if($accent-name=='black') {
    @return mat-palette($mat-grey, 900, 400, 700);
  }
  @else {
    @return mat-palette($mat-grey, 50, 400, 700);
  }
}

@mixin app-component-theme($primary-name, $accent-name) {
  $primary: get-primary-color($primary-name);
  $accent: get-accent-color($accent-name);
  $warn: mat-palette($mat-red);
  $theme: mat-light-theme($primary, $accent, $warn);
  @include angular-material-theme($theme);
}
$colors: 'pink',
'purple',
'deep-purple',
'indigo',
'green',
'blue',
'light-blue',
'cyan',
'teal',
'green',
'light-green',
'lime',
'yellow',
'amber',
'orange',
'deep-orange',
'brown',
'grey',
'blue-grey',
'black',
'white';
@for $i from 1 through length($colors) {
  @for $j from 1 through length($colors) {
    $theme-class: '.primary-#{nth($colors,$i)}.accent-#{nth($colors, $j)}';
    #{$theme-class} {
      @include app-component-theme(nth($colors, $i), nth($colors, $j));
    }
  }
}

**Comment by germwire** [comment]
I changed typescript version to 1.7.5 for compatibility with angular 6.0.2

**Comment by tiaguinho** [comment]
@germwire I think the loop of colors that you have is responsible for this very large file.
Why are you generating so many material themes?

**Comment by kyliau** [comment]
Closing this, since issue is more than two years old and there is not a clear repro step. Please reopen if you'd like to continue the discussion.
