### ISSUE TITLE
Incomplete error log for invalid class name indicated with lazy loaded module path

### ISSUE THREAD

**Issue by ChrisDahmCS** [angular/angular-cli#10894]
### Versions
```
Angular CLI: 6.0.1
Node: 10.1.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.1
@angular-devkit/core         0.6.1
@angular-devkit/schematics   0.6.1
@schematics/angular          0.6.1
@schematics/update           0.6.1
rxjs                         6.1.0
typescript                   2.7.2
```

### Repro steps
* Generate a new project `ng new my-err-project`
* Change directories into the root of the new project
* Create an extra module `ng g m real`
* Add a route with lazy loading of the module you created to `app.module.ts` imports and put the wrong classname after the hash
```RouterModule.forRoot({
    path: 'test-path',
    loadChildren: './real/real.module#Bigfoot'
})
```
* Run `ng build`, `npm start` or `ng serve` to see the error thrown and a failure to compile

### Observed behavior
* Upon attempting to run `ng build`, `npm start` or `ng serve`:
```
ERROR in No NgModule metadata found for 'BigFoot'.
ℹ ｢wdm｣: Failed to compile.
```
* While using `npm start` or `ng serve` change a ts file to force a recompile and you get:
```
ℹ ｢wdm｣: Compiled successfully.
```

### Desired behavior
* The error message should indicate what file the error is in when compilation fails running `ng build`, `npm start` or `ng serve`.
* Triggering a recompile after the first `npm start` or `ng serve` should not end in success
* Running `ng build --prod` should not build successfully

### Mention any other details that might be useful (optional)
* Completely cleaning and reinstalling node/node_modules/npm/angular CLI and starting fresh did not seem to cure this behavior

**Comment by kyliau** [comment]
Closing this, since string-based `loadChildren` has been deprecated.
Please see https://angular.io/api/router/LoadChildren
