### ISSUE TITLE
created project folder tree too deep for windows

### ISSUE THREAD

**Issue by JimInWoodstock** [angular/angular-cli#1090]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 Pro 64bit

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
3.8.6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

1. Create project folder using "ng new PROJECT_NAME"
2. Delete the just created project folder.

The combination of folder names and folder depth is greater than Windows can handle when deleting. Got errors when deleting the file tree. The only way that I was able to delete the project folder was to rename parent folders in the path to the "too deep" folder/file to "a", "b", etc so that the foldername/depth would be shorter. This took quite a few (a dozen or so) renaming steps. I would look at the error box and see the path to the file/folder that was too deep. I would then rename the parent folders up the line to "a", "b", etc and try the delete again. Some other folder path would be too long so a repeat renaming of the parent tree to that folder would be needed. 

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by JonCubed** [comment]
You just need to update node to 4+, clean *node_modules/* and run `npm install` again. This is a known issue with node <4.

**Comment by kylecordes** [comment]
It is true this is a known issue, but at the same time CLI could make the initial developer experience much better by noticing and objecting to an insufficiently new node.

**Comment by filipesilva** [comment]
@JonCubed is correct, and node 4 is listed as one of the pre-requisites in the readme: https://github.com/angular/angular-cli#prerequisites. 

It's also listed in the required engines: https://github.com/angular/angular-cli/blob/master/package.json#L19-L21

Note sure what else we could reasonably do in the CLI, but am open to suggestions.

**Comment by kylecordes** [comment]
The CLI could check the running version of node and refuse to run if not new enough. That way, people using the tool get immediate feedback and go fix their prerequisites (rather than having to discover them in the documentation), and they get up and running again in a couple of minutes instead of filing an issue. I don't know whether this is reasonable per se, but I would find it helpful and there are many other tools on many other platforms that check their dependencies at runtime rather than only document the dependencies. So it is certainly not unheard of to do so.
