### ISSUE TITLE
ng build Warnings fails Angular 6.0.2

### ISSUE THREAD

**Issue by Sevensnake** [angular/angular-cli#10908]
After the upgrade I get this warning and It does not continue to build.

I update core not sure what else is needed.
`PS C:\git\projects\myproj> ng build

Date: 2018-05-17T20:12:54.258Z
Hash: 894c5f4391cbe98877f3
Time: 49404ms
chunk {main} main.js, main.js.map (main) 436 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 250 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 515 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 14 MB [initial] [rendered]

WARNING in ./node_modules/ng-http-loader/node_modules/@angular/core/esm2015/core.js
5354:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ./node_modules/ng-http-loader/node_modules/@angular/core/esm2015/core.js
5370:15-102 Critical dependency: the request of a dependency is an expression`

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by Sevensnake** [comment]
I will see if I can this weekend. Currently this bug is effecting a large application that I have to revert at this time.  I will see if I can this weekend. Thanks

**Comment by Sevensnake** [comment]
Ok I figured it out.  First check all packages make sure they are the one you are using.
The ng-http-loader was  a dependencies that was not needed and causing the build to fail.
