### ISSUE TITLE
Break up an app into subprojects with Angular CLI?

### ISSUE THREAD

**Issue by joeattardi** [angular/angular-cli#10906]
Apologies if this isn't the appropriate medium in which to ask this question.

I have what's currently a medium-sized Angular 5 app with several lazy-loaded feature modules. What I'd like to do is be able to break the app up so each of these feature modules is a sub-project that can be built and tested independently. 

With the new support for generating "libraries", would I be able to leverage Angular CLI for this purpose? The main piece I don't know about is how I would pull in those sub-projects into the main app when the app is built/run (we do not want to publish the sub-projects to an npm registry).

Would Angular CLI 6 fit this use case?

**Comment by filipesilva** [comment]
Heya, you should be able to break the project apart into libraries. You don't need to publish them into npm either, when you generate a library we set tsconfig configuration to look for the library in its built folder. 

You just have to build them in the right order.

**Comment by joeattardi** [comment]
That sounds great! Thanks for the information.
