### ISSUE TITLE
Got error when using `ng update @angular/cli`

### ISSUE THREAD

**Issue by Teamop** [angular/angular-cli#10903]
### Versions
```
Angular CLI: 6.0.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.3
@angular-devkit/build-angular      0.6.3
@angular-devkit/build-optimizer    0.6.3
@angular-devkit/core               0.6.3
@angular-devkit/schematics         0.6.3
@angular/cdk                       5.2.5
@angular/cli                       6.0.3
@angular/flex-layout               5.0.0-beta.14
@angular/material                  5.2.5
@angular/material-moment-adapter   5.2.5
@ngtools/webpack                   6.0.3
@schematics/angular                0.6.3
@schematics/update                 0.6.3
rxjs                               5.5.10
typescript                         2.6.2
webpack                            4.8.3
```

### Repro steps

Today I tried to update to angular 6, so when using the new `ng update @angular/cli` command I got two issues:
1. for `lint` in the `.angular-cli.json`
* Step 1 in the old config
```javascript
    {
      "files": [
        "app.js",
        "config/**/*.js"
      ]
    }
```
* Step 2 just run the `ng update @angular/cli`
* Step 3 Got error `Cannot read property 'indexOf' of undefined`

The reason why I add that code in the `lint` is to leverage TSLint and `ng lint` to check the format of the js files, for these js files, it's an express server for production and some configurations.

2. another issue which can be trivial is for the `name` in `project` in the `.angular-cli.json`, so the `name` can be `AAA BBBB`, but with the update command, it just use this name to construct the new config file which will be an inappropriate name for the property key. Like: `AAA BBBB-e2e`, `"browserTarget": "AAA BBBB:build"`

### Observed behavior
**For the first problem**, It's just because the [the code just get project from lint](https://github.com/angular/devkit/blob/master/packages/schematics/angular/migrations/update-6/index.ts#L471), just add a null check can solve this. But the problem is I cannot use this `lint` property to check the js files except I also add a new tsconfig file for these js files which I think it's not right.

**For the second problem**, just got inappropriate property in the json file

### Desired behavior

1. Maybe a better way to check the js files as I need without adding more tsconfig
2. Maybe transform the name to a Camel Case or something.

**Comment by pwpatton** [comment]
Got the same error
```
E:\landmark\sandbox1\web10x\client\LawsonWebClient\WebContent\cli>ng update @angular/cli
            Updating karma configuration
            Updating configuration
Cannot read property 'indexOf' of undefined
```

Had to debug and found the offending issue here:
```
        // Tslint target
        const lintOptions = {
            tsConfig: removeDupes(tsConfigs).filter(t => t.indexOf('e2e') === -1),
            exclude: removeDupes(excludes),
        };
```

Turns out I had an extra object in my lint array in angular-cli.json 

```
"lint": [
  {"project": "src/tsconfig.app.json", "exclude": "**/node_modules/**"},
  {"project": "src/tsconfig.spec.json", "exclude": "**/node_modules/**"},
  {"project": "e2e/tsconfig.e2e.json", "exclude": "**/node_modules/**"},
  {}
],
```

Actual Behavior: error message with little helpful information
Desired Behavior: a better error message indicating the problem.

**Comment by Teamop** [comment]
@pwpatton  you can remove the last empty object in lint, that should work

**Comment by pwpatton** [comment]
@Teamop Yes, I should have mentioned that I did remove that and the update ran successfully. Just wanted to add what I found in case anyone else went looking, 
Thanks!

**Comment by clydin** [comment]
Closing as resolved by the referenced PR above.
