### ISSUE TITLE
Help with Angular CLI Version

### ISSUE THREAD

**Issue by calioto** [angular/angular-cli#10907]
### Versions
```
Angular CLI: 1.7.4
Node: 8.9.4
OS: win32 x64
Angular:
...
```

### Repro steps

N/A

### Observed behavior
```
N/A
```

### Desired behavior

At my company, we can only work with approved versions of software. We are approved for Angular 5, but not 6. What version of the CLI can I install to insure that I will only be using Angular 5 code? Thanks in advance for your response.

~ Christopher

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
