### ISSUE TITLE
Cannot import from node_modules using LESS

### ISSUE THREAD

**Issue by michael-letcher** [angular/angular-cli#10913]
### Versions
```
Angular CLI: 6.0.3
Node: 8.11.1
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
* Create a new CLI project with bootstrap as a dependancy
* Import bootstrap into less file using `~`

### Observed behavior
```
@import (reference) "~bootstrap/less/mixins.less";
^
'~bootstrap/less/mixins.less' wasn't found. Tried - .../src/app/shared/styles/~bootstrap/less/mixins.less,npm://~bootstrap/less/mixins.less,~bootstrap/less/mixins.less
      in .../src/app/shared/styles/mixins.highlighted-area.less (line 1, column 0)
ERROR in ./src/app/shared/profile/profile-avatar-upload/profile-avatar-upload.component.less
Module build failed:
```

### Desired behavior
To import and compile correctly

**Comment by filipesilva** [comment]
Can you try not using the `~` character as well please? I think this was changed recently to allow not using it.

**Comment by michael-letcher** [comment]
@filipesilva It works thank you. Is this mentioned anywhere?

**Comment by clydin** [comment]
Please note that the use of the tilde was never officially supported.  It was something that _happened _ to work (in certain situations) in the past due to the behavior of certain webpack loaders used internally.  The tilde usage is also not something that is built into webpack itself but rather is particular to a certain set of loaders; each of which can potentially interpret its usage in different ways.

**Comment by michael-letcher** [comment]
Thank you for this clarification.

**Comment by Sergey80** [comment]
work-around?

**Comment by michael-letcher** [comment]
@Sergey80 What's your issue? Note in v7 they have swapped it and now you require the ~
