### ISSUE TITLE
Maintain a Changelog or Release notes

### ISSUE THREAD

**Issue by ninrod** [angular/angular-cli#10921]
related to #554 but only `ng update` was provided. We still don't have patch notes.

**Comment by deebloo** [comment]
is this not sufficient? https://github.com/angular/angular-cli/releases

**Comment by filipesilva** [comment]
@ninrod we do maintain a Angular CLI changelog in the releases: https://github.com/angular/angular-cli/releases. 

It is worth mentioning that a lot of code is actually maintained in DevKit, for which there is no changelog yet, but support for one is being tracked in https://github.com/angular/devkit/issues/648.

**Comment by ninrod** [comment]
@filipesilva, thanks. I think ng serve --env was replaced by ng serve --configuration, which was a non documented as a breaking change nor it was mentioned in the migration guide. We should closely watch these types of changes to ease the pain of upgrading. Adding them to the breaking changes section would be really helpful.
