### ISSUE TITLE
Angular CLI v6: Unknown option: '--browser'

### ISSUE THREAD

**Issue by sehranhas** [angular/angular-cli#10920]
### Versions
```
Angular CLI: 6.0.3
Node: 8.11.1
OS: linux x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

```

### Repro steps
* Install Angular 6 
* `ng test --browser ChromeHeadless --code-coverage=true --single-run=true`

### Observed behavior
```
Unknown option: '--browser'
```

### Desired behavior

Updated documentation
Fix `--browser`

### Mention any other details that might be useful (optional)
I would like the command line to pick up a browser (e.g Chrome or ChromeHeadless) when running the tests.

**Comment by sehranhas** [comment]
@mboughaba thank you, this works for me! Looks like `--single-run` is no longer available. The current workaround for it is to use `--watch=false`. Linking #10711

**Comment by filipesilva** [comment]
I think at one point we accepted both `browsers` and `browser` as the same thing, and that got cleaned up in v6. Sorry for the confusion.

**Comment by jsgoupil** [comment]
@filipesilva Please update the doc. https://github.com/angular/angular-cli/issues/11582
