### ISSUE TITLE
Couldn't install angular/cli

### ISSUE THREAD

**Issue by dexty007** [angular/angular-cli#10928]
There's an attached preview of the error i'm dealing with ......
NOTE: the versions of NODE & NPM in the photo.......
@
![whatsapp image 2018-05-19 at 1 47 16 pm](https://user-images.githubusercontent.com/33428852/40270597-cf340964-5bad-11e8-8b54-69777c8439a3.jpeg)

**Comment by lennieh** [comment]
You need node v8

**Comment by dexty007** [comment]
so, should i rollback to that version
??

**Comment by mgarcia66** [comment]
Did you find a solution?

**Comment by dexty007** [comment]
yeah !!
http://www.ubuntugeek.com/install-latest-version-of-node-js-and-npm-on-ubuntu-17-10-server.html

This site helped :wink: :wink:
