### ISSUE TITLE
`ng build` output truncated when run as a child process

### ISSUE THREAD

**Issue by dwieeb** [angular/angular-cli#10922]
The output of `ng build` is truncated to 8192 bytes when run as a child process. 

### Versions
```
Angular CLI: 6.0.1
Node: 8.10.0
OS: darwin x64
Angular: 6.0.2
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@angular/cli                      6.0.1
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.1
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* `git clone https://github.com/dwieeb/ng-build-truncated-output`
* `npm install`
* `node script.js`

### Observed behavior
![image](https://user-images.githubusercontent.com/236501/40255140-b4665d06-5aab-11e8-9c20-bad4e34a8046.png)

### Desired behavior
﻿
![screen shot 2018-05-18 at 2 57 40 pm](https://user-images.githubusercontent.com/236501/40255184-e35dc694-5aab-11e8-9c06-ef1fabb39401.png)

### Mention any other details that might be useful (optional)

Something I observed is that using `setBlocking(true)` in the `ng` bin file appears to flush the output properly:

```
#!/usr/bin/env node
'use strict';

process.stdout._handle.setBlocking(true);
process.stderr._handle.setBlocking(true);

// Provide a title to the process in `ps`.
// Due to an obscure Mac bug, do not start this title with any symbol.
process.title = 'ng';

var version = process.version.substr(1).split('.');
if (Number(version[0]) < 8 || (Number(version[0]) === 8 && Number(version[1]) < 9)) {
  process.stderr.write(
    'You are running version ' + process.version + ' of Node.js, which is not supported by Angular CLI v6.\n' +
    'The official Node.js version that is supported is 8.9 and greater.\n\n' +
    'Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.\n'
  );

  process.exit(3);
}

require('../lib/init');
```

Could be related to stdout not being flushed before a `process.exit()` is called.

**Comment by filipesilva** [comment]
This is an interesting problem. For reference the issues on node seem to be https://github.com/nodejs/node/issues/2360 and https://github.com/nodejs/node/issues/19218.

A specially relevant highlight is https://github.com/nodejs/node/issues/19218#issuecomment-377876168:

> And the root cause identified as the fact that console.log non blocking, so if a process issues it and exits afterwards, the actual number of bytes written depends on the time gap between the two actions and the capability of the I/O channel to transfer the data in between the gap.

This makes me think that we shouldn't use `console.log` across our loggers and use `process.stdout.write` instead.

**Comment by dwieeb** [comment]
@filipesilva Would you accept a PR where the loggers are switched to using `process.stdout.write`?

**Comment by filipesilva** [comment]
@dwieeb I think we already do now in CLI 7.

Out webpack build uses a provided logger:
https://github.com/angular/angular-cli/blob/e5aea19a6a32a5c2b60b5f4a53efe164e34df6a3/packages/angular_devkit/build_angular/src/browser/index.ts#L189-L205

The logger is instantiated in the CLI:
https://github.com/angular/angular-cli/blob/e5aea19a6a32a5c2b60b5f4a53efe164e34df6a3/packages/angular/cli/lib/cli/index.ts#L16

And will use `process.stdout` and `process.stderr`:
https://github.com/angular/angular-cli/blob/e5aea19a6a32a5c2b60b5f4a53efe164e34df6a3/packages/angular_devkit/core/node/cli-logger.ts#L18-L22

**Comment by alan-agius4** [comment]
Hi @dwieeb, is this still a problem?

**Comment by dwieeb** [comment]
No, I haven't seen this in a while.
