### ISSUE TITLE
PostCSS Loader tries to load node_module JS without ~ prefix

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#10925]
### Versions
```
Angular CLI: 6.0.3
Node: 8.9.4
OS: darwin x64
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* Step 1 - ng new blah && cd blah
* Step 2 - npm i bootstrap
* Step 3 - Create a file called _bootstrap.scss with `@import '~bootstrap/scss/bootstrap'`
* Step 4 - Add `@import "bootstrap"` to styles.scss

### Observed behavior
Because you have a library called `bootstrap` inside node_modules, it seems to be trying to import JS from there. I don't think it should be trying to import anything from node_modules without a ~ prefix, surely?
```
ERROR in ./src/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed:
(function (global, factory) {
^
      Invalid CSS after "  */": expected selector, was "(function (global, "
      in /Users/dominicwatson/Sites/github/rulbricht/coineqt/packages/www/node_modules/bootstrap/dist/js/bootstrap.js (line 6, column 1)
```

### Desired behavior
It should just import the local file called _bootstrap and not try to load stuff from node_modules without a ~ prefix. I guess it should at least not be trying to import JS

### Mention any other details that might be useful (optional)

**Temporary workaround** is to rename `_bootstrap.scss` to `_twbootstrap.scss`

**Comment by filipesilva** [comment]
Related to https://github.com/angular/angular-cli/issues/10913

**Comment by clydin** [comment]
I was unable to replicate this.  Here is a working repository created by following the steps indicated above: https://github.com/clydin/cli-scss-bootstrap

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by knnwulf** [comment]
Instead of rename the scss file you can add the full path

@import "~bootstrap/scss/bootstrap";

**Comment by intellix** [comment]
Sorry I didn't get around to creating a reproduction :)

It's when coupled with `stylePreprocessorOptions.includePaths` to allow easily importing variables into components. Here's the commit that reproduces it @alan-agius4:

https://github.com/intellix/angular-cli-10925/commit/a11ff848792686d4836aa00b6429652103cec273

You can rename the import from `bootstrap` to `_bootstrap` to reproduce the error. You'll notice that `variables` works because there's no library called that
