### ISSUE TITLE
angular CLI ng g component error: Unexpected token ] in JSON at position 942

### ISSUE THREAD

**Issue by uurrahman** [angular/angular-cli#10938]
Hello,

I have updated angular cli and due to some reason i getting this error:

**Unexpected token ] in JSON at position 942**

`ng serve ` is working properly.

My development environment is:

Angular CLI: 6.0.3
Node: 8.11.2
OS: linux x64
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package     |    Version
----------- | -----------
angular-devkit/architect  |       0.6.3
angular-devkit/build-angular |    0.6.3
angular-devkit/build-optimizer |  0.6.3
angular-devkit/core       |       0.6.3
angular-devkit/schematics  |      0.6.3
angular/cli             |         6.0.3
ngtools/webpack    |              6.0.3
schematics/angular  |             0.6.3
schematics/update   |             0.6.3
rxjs                     |         6.1.0
typescript            |            2.7.2
webpack              |             4.8.3

**Comment by bresleveloper** [comment]
you probably put commented something in  `angular.json`
