### ISSUE TITLE
`ng serve` automatically rebuilds

### ISSUE THREAD

**Issue by sarunint** [angular/angular-cli#10935]
### Versions
```
Angular CLI: 6.0.3
Node: 10.0.0
OS: linux x64
Angular: 6.0.2
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* run `ng serve --aot`. (Not tested with non-AOT yet)

### Observed behavior
Webpack recompiles many times without file changes, which leads to multiple browser refresh. Notice that the hash stays the same.
![image](https://user-images.githubusercontent.com/3850197/40289725-422e44f2-5ce4-11e8-80c4-c1f87d8e7940.png)

### Desired behavior
Webpack rebuilds only on file changes.

**Comment by sarunint** [comment]
Strange, this issue started to appear since v6. Before that, I don't have any "auto-rebuild".

For the record, my system is Windows 10 but running node in WSL.

**Comment by sarunint** [comment]
Hi @filipesilva, I did what you asked me to do, and here's the result!

![image](https://user-images.githubusercontent.com/3850197/40347566-f6a18778-5dca-11e8-8edc-90595253d4f8.png)

**Comment by filipesilva** [comment]
Well, this is unfortunate.... it looks like random files are being touched, but not modified, all the time. I'm not really sure what we can do about that. 

Does this happen if you run outside WSL?

**Comment by sarunint** [comment]
Will try soon! Thanks for your help.

**Comment by sarunint** [comment]
@filipesilva long time no see!

Recently, no "auto-rebuilds" has occurred yet. (Yes, in WSL.) I will assume that this issue is resolved.

Thanks for you help anyway.

**Comment by sarunint** [comment]
I may try downgrade the CLI to see which version resolves this problem though.

**Comment by argygkou** [comment]
I have the same problem from version 5 to version 7 that I updated two days ago. Every time I click on a file or a folder in vs code, angular cli rebuilds. 
I'm using Angular v7  with Nx v7.
Can anyone help? it's very frustrating!!!!!

**Comment by jeffgammon** [comment]
I have the same auto-rebuild problem also. Files that have not been edited cause a rebuild. Also super frustrated. 
Windows 10
Angular 6.0.3
node v8.11.2
I do not use WSL.
I have run ng serve from from both git's bash shell and Windows Command Prompt, and rebuild happens in both.

I edited node_modules/@ngtools/webpack/src/angular_compiler_plugin.js as suggested by @filipesilva and captured a similar log as @sarunint. I see no pattern to the touched files. Sometimes they are my files, sometimes they are other's files down in node_modules.  I can sometimes get them to "touch" by simply listing files in some directory from a bash shell; i.e., `cd ` to some component folder in the project and then `ls` will cause the rebuild. Opening a file in VS Code sometimes also triggers the rebuild. 

I welcome any other suggestions or workarounds.

![cli_rebuilds](https://user-images.githubusercontent.com/5641467/49167938-b5733080-f2f3-11e8-9ae8-76d9963d4d33.png)

**Comment by jeffgammon** [comment]
The `--poll 1000 ` workaround appears to be working for me as well. 2 days and no unexpected rebuilds. Thank you @filipesilva

**Comment by ykamal** [comment]
> 
> 
> The `--poll 1000 ` workaround appears to be working for me as well. 2 days and no unexpected rebuilds. Thank you @filipesilva

Thanks! This has fixed the issue for me too!
