### ISSUE TITLE
ts-node version upgrade when using 'ng update @angular/core'

### ISSUE THREAD

**Issue by Teamop** [angular/angular-cli#10941]
### Versions
Using `ng update @angular/core` to update Angular 5.2 to Angular 6.0

### Repro steps

* Step - Using `ng update @angular/core` to update Angular 5.2 to Angular 6.0

### Observed behavior
After the update, the ts-node is still `"ts-node": "~4.1.0",`

### Desired behavior

I tested with the a totally new application created with `ng new`, the result is `"ts-node": "~5.0.1"`, so I think when using the 'ng update @angular/core', the corresponding package version should also be updated.

**Comment by filipesilva** [comment]
It's true that a new project will have a new version of `ts-node`. We don't really update non Angular packages, such as `ts-node`. Those packages can have different public APIs and break in unexpected ways.
