### ISSUE TITLE
ng-eject is disabled so how do we add a loader to webpack ?

### ISSUE THREAD

**Issue by appsolutegeek** [angular/angular-cli#10945]
In the latest v6 of the cli it appears you can't EJECT, so how is is possible to add a webpack loader ?

I need to add a loader for graphql.

Any ideas ?

**Comment by ampgular** [comment]
Hi appsolutegeek, I haven´t yet reviewed the source code, but If I´ve understood properly. I think the way to customize the build workflow is with architect_cli where you define a custom target.
If I would have your requirements I would head toward the architect source code

**Comment by appsolutegeek** [comment]
I thanks for the reply. Sure, I just need to add 1 loader for webpack to be able to import graphql extension files.

The loader is explained here. https://www.apollographql.com/docs/react/recipes/webpack.html

Standard loader as far as I can see. 

Does that explain everything?

Thanks in advance

**Comment by koshevy** [comment]
Loaders and aliases and plugins! Last "feature" make CLI unusable. Solutions like this — https://github.com/gdi2290/angular-starter — is much more usable now.

Meanwhile, you intend to reinvent Webpack config in your `angular.json`? :)

**Comment by filipesilva** [comment]
@appsolutegeek we're adding back eject soon but bear in mind there will not be a way to add a loader to the pipeline Angular CLI uses (see more about that in https://github.com/angular/angular-cli/issues/1656). Eject will give you a webpack config that you can use and is separate from the Angular CLI pipeline.

**Comment by clydin** [comment]
Also, just as `create-react-app` has an unofficial third-party utility to enable such a feature (https://github.com/timarney/react-app-rewired), so too could a third-party create a similar unofficial utility for the Angular CLI.  Please note the disclaimer within the aforementioned package and the linked similar [response](https://github.com/facebook/create-react-app/issues/99#issuecomment-234657710) from `create-react-app`.

**Comment by BatsShadow** [comment]
If you are unwilling to allow developers to modify the build pipeline, then at the very least have something that will spit out the existing webpack build config and allow the developer to take it over. I don't care if the cli ignores what was spit out.

I am trying to use pug with pug-ng-html-loader for nicer pug syntax, but it seems there is no way to do so in angular8 without starting my build config from scratch.

**Comment by mgechev** [comment]
@BatsShadow [`ngx-build-plus`](https://github.com/manfredsteyer/ngx-build-plus) is probably what you're looking for.

**Comment by BatsShadow** [comment]
@mgechev Thanks, I'll take a look
