### ISSUE TITLE
tslint is missing custom rules in 1.0.0-beta.6

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#1094]
1. OS?  
Mac OSX El Capitan

2. Versions. 
angular-cli: 1.0.0-beta.6
node: 6.2.0
os: darwin x64

3. Repro steps. 
In a new project, run `tslint "src/**/*.ts"`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
throw new Error(ERROR_MESSAGE);
        ^

Error:
            Could not find implementations for the following rules specified in the configuration:
            directive-selector-name
component-selector-name
directive-selector-type
component-selector-type
use-input-property-decorator
use-output-property-decorator
use-host-property-decorator
no-input-rename
no-output-rename
use-life-cycle-interface
use-pipe-transform-interface
component-class-suffix
directive-class-suffix
```

5. Mention any other details that might be useful.
Looks like the rules directory was removed in #740 
Maybe that's not necessary anymore, but I'm using the last tslint release 3.11, so something must be missing.

Current workaround is to add the rules directory again:

```
  "rulesDirectory": [
    "node_modules/codelyzer"
  ],
```

cc @filipesilva

**Comment by filipesilva** [comment]
@mgechev can you advise?

**Comment by filipesilva** [comment]
@cexbrayat added a PR doing exactly what you mentioned as a fix. I mistakenly removed that lint config entry.
