### ISSUE TITLE
Impossible d'importer Observable depuis 'rxjs/Observable'

### ISSUE THREAD

**Issue by valere12** [angular/angular-cli#10942]
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import 'rxjs/Rx';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  secondes: number;

  constructor (){

  }

  ngOnInit() {

    const counter = Observable.interval(1000);
    counter.subscribe(
      (value: number) => {
        this.secondes = value;
      },
      (error: any) => {
        console.log('Erreur !!!');
      },
      () => {
        console.log('Observable complete !');
      }
    );
  }

}

terminal

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'rxjs/Observable' in '/Volumes/DONNEES PE/PROJETS/ANGULARJS/val/src/app'
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'rxjs/Rx' in '/Volumes/DONNEES PE/PROJETS/ANGULARJS/val/src/app'
ℹ ｢wdm｣: Failed to compile.
ERROR in node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Rx.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat'.
src/app/app.component.ts(2,10): error TS2305: Module '"/Volumes/DONNEES PE/PROJETS/ANGULARJS/val/node_modules/rxjs/Observable"' has no exported member 'Observable'.

**Comment by valere12** [comment]
besoin d"aide svp !

**Comment by deebloo** [comment]
What versions of angular and rxjs are you using?

**Comment by valere12** [comment]
Angular CLI 6.0.3

**Comment by valere12** [comment]
version de rxjs : 6.0.0

**Comment by valere12** [comment]
merci a vous j'ai fait les deux importations donc vous m'avez suggere . mais voici une autre erreur.

ERROR in src/app/app.component.ts(22,32): error TS2339: Property 'interval' does not exist on type 'typeof Observable'.

**Comment by hitandyrun** [comment]
`import { Observable, Subject, interval } from 'rxjs';`

**Comment by valere12** [comment]
Desole j'ai ajoute l'importation proposee mais toujours la meme erreur.

code: 

import { Component, OnInit } from '@angular/core';
import { Observable, Subject, interval } from 'rxjs';
import { map, switchMap } from 'rxjs/operators';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {

  secondes: number;

  constructor (){

  }


  ngOnInit() {

    const counter = Observable.interval(1000);
    counter.subscribe(
      (value: number) => {
        this.secondes = value;
      },
      (error: any) => {
        console.log('Erreur !!!');
      },
      () => {
        console.log('Observable complete !');
      }
    );
  }

}


erreur :
ERROR in src/app/app.component.ts(22,32): error TS2339: Property 'interval' does not exist on type 'typeof Observable'.

**Comment by clydin** [comment]
`const counter = interval(1000);`

**Comment by valere12** [comment]
Merci infiniment pour vos reponses j'ai remplace ma ligne de code const counter = Observable.interval(1000); par const counter = interval(1000); et tout fonctionne.

**Comment by rivers-dash** [comment]
try this I found it in an other thread and it resolved my problem 
`npm install rxjs@6 rxjs-compat@6 --save`
