### ISSUE TITLE
Option to make xi18n extract every string into a separate unit.

### ISSUE THREAD

**Issue by jaska45** [angular/angular-cli#10948]
xi18n when extracting strings looks them by string values. If two or more location on templates or source code use the same string only one unit element will be created into XLIFF/XMB. It would be good to have an option that would make one unit element created for each string. So no unit element would be shared with multiple string instances.

This is because sometimes there is a need to translate the string in a different way depending on the context. For example we might have two templates both having word `hard`.  In one template the meaning is solid and on other the meaning is difficult. We also might have a word `access `that would be noun on one location but verb on another.

Right now we have a workaround if we add meaning into i18n attribute. For example `i18n="difficult|"` and `i18n="solid|"`. This will make two unit element to appear in XLIFF file. However this requires additional template editing (i.e. adding attribute value). Developers might not even notice the need to have a meaning until translator/tester will notice it. That time it might be too late. It would be good that there is an option to add a separate unit element for each string instance.

### Versions
All

### Repro steps
Add the same string into two locations and run xi18n

**Comment by jaska45** [comment]
This might be difficult to implement because the id value is calculated hash from value and meaning. It does not matter where in the template the string is or at what template file.

**Comment by filipesilva** [comment]
Heya, this feature request should be added to the https://github.com/angular/angular issue tracker instead. The `i18n` functionality proper is not part of Angular CLI actually, it's part of the Angular Compiler. I understand the distinction is not very clear, just trying to direct people to the right repos.
