### ISSUE TITLE
AOT replaces window.location object to null

### ISSUE THREAD

**Issue by fetis** [angular/angular-cli#10957]
### Versions
```
Angular CLI: 6.0.3
Node: 8.9.4
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
```

### Repro steps
I have a static method `.forRoot` to configure my authorization module with next code

```
@NgModule({
  imports: [
    AuthModule.forRoot<Auth0AdapterConfig>({
      adapterConfig: {
       ...
        redirectUri: `${location.protocol}//${location.host}/callback`,
        scope: 'openid'
      }
    })
  ],
```

### Observed behavior
When I use `--aot` option (explicitly or implicitly via --prod) the `redirectUri` parameter is replaced by hardcoded value `redirectUri: "null//null/callback"`

### Desired behavior
AOT must preserve `location` variable

**Comment by AlexGS74** [comment]
Doubt it's a bug. You have a string interpolation expression there, which will be executed by Angular-compiler and replaced with a static value at compile time, whereas in Jit mode the expression gets executed at run-time, which is a side effect you rely on.

**Comment by fetis** [comment]
@AlexGS74 why it's executed by the Angular compiler? string interpolation is TS thing (as part of ES6 spec)

**Comment by deebloo** [comment]
@fetis it is because window does not exist during build time. You will have to use Dependency Injection and you can use "useFactory" to return window and access it that way

**Comment by AlexGS74** [comment]
@fetis This is whole point of AOT, as it's stated [here](https://angular.io/guide/aot-compiler) (a good read, btw):

> The Angular Ahead-of-Time (AOT) compiler converts your Angular HTML and TypeScript code into efficient JavaScript code during the build phase before the browser downloads and runs that code.

**Comment by deebloo** [comment]
@fetis I think what @AlexGS74 meant is similar to what I said. location is not defined at build time because it is not running in the browser

**Comment by AlexGS74** [comment]
@deebloo That is correct. There are shims used by the Angular Compiler, but these are static with no real values.

BTW, here is one more resource that might help: [AoT Do's and Don'ts](https://github.com/rangle/angular-2-aot-sandbox#aot-dos-and-donts)

**Comment by fetis** [comment]
It's still unclear for me why AOT tries to optimize this string. Please note, **it's not a template**
Is any way to prevent this behavior?

**Comment by deebloo** [comment]
@fetis it isn't trying to optimize the string. It is running that code. and at the time that it runs the code. location is not defined. Think about it this way, that but of code is being run in node. not in the browser. If you want to do something like that you can use an injection token and create a factory function that returns the value you want. that will be run in the browser and you will see the value you want

**Comment by AlexGS74** [comment]
@fetis One of the things AOT does it tries to detect the lazy-load routes. For that it needs to execute/optimize etc. the modules and the forRoot methods. As @deebloo pointed out, it will be run in node environment, hence all the restrictions on what you can or can't to for AOT to work.

The code @deebloo provided above is perfect example of how to "move" the execution to runtime only.

**Comment by deebloo** [comment]
@fetis yes. I am not positive about the example you showed with the router but I am willing to bet that is the case there as well

**Comment by hassanasad** [comment]
Try dropping this at the end of your `polyfills.ts` file and try then:

`(window as any).global = window;`

If its fixed - read here ( https://github.com/angular/angular-cli/issues/9827#issuecomment-386154063 )

**Comment by deebloo** [comment]
@fetis im not sure why you are seeing that

**Comment by roopeshreddy** [comment]
@deebloo Your code works fine, if just one config alone. What if, you're sending the bunch of configuration and one of the value needs **location.origin** like below - 

`   cacheLocation: 'localStorage',
    redirectUri: `${window.location.origin}/login``

**Comment by deebloo** [comment]
same way. just return the object from the factory function

**Comment by roopeshreddy** [comment]
I made it working this way - 

`export function getRedirectUrl() {
  return `${window.location.origin}/login`; // 'http://localhost:4200/login';
}

adalConfig: {
    cacheLocation: 'localStorage',
    redirectUri: getRedirectUrl 
  },

`
Hope it helps!

**Comment by filipesilva** [comment]
Closing as there seem to be a lot of good responses and alternatives here, and also because this isn't really a CLI issue. Thanks all for the help!

**Comment by fetis** [comment]
@filipesilva could u please re-open the issue. I still have a problem with it. My configuration looks next now

```
@NgModule({
...
})
export class AuthModule {
  static forRoot<T>(config: AuthModuleConfig<T>): ModuleWithProviders {
    return {
      ngModule: AuthModule,
      providers: [
...
        { provide: BROWSER_LOCATION, useFactory: locationFactory  }
      ]
    };
  }
}
```

and location factory exported from another file
```
export function locationFactory() {
  return window.location;
}
```

this all is packed as a library with `ng-packagr`.

Config works fine for `ng serve --aot`, but when I run this in production mode it still fails
and produces next warning 

```
WARNING in ./src/app/app.module.ngfactory.js
21:1871-1889 "export 'locationFactory' (imported as 'i7') was not found in '@XXXX/auth-module'
```

**Comment by fetis** [comment]
I think it was some misconfiguration of libraries on my machine, after some struggle it works fine

**Comment by Jay1989** [comment]
Hi, Still I am getting null !!!
My configuration like...
export const oauthConfig: AuthConfig = {
  clientId: environment.oauth.clientId,
  issuer: environment.oauth.url,
  loginUrl: `${environment.oauth.url}/xyz`,
  logoutUrl: `${environment.oauth.url}/xyz`,
  redirectUri: `${environment.host}`
};
enviroment.host = window.location.origin something like this.
while prod mode I am getting window null.

**Comment by Nodarii** [comment]
Isn't better to use `@Inject(DOCUMENT) private doc: Document`?

so my code looks like: 
```
import { DOCUMENT } from '@angular/common';

....

constructor (@Inject(DOCUMENT) private doc: Document) {
}

....

getOrigin(): string {
   return this.doc.location.origin;
}
```

**Comment by aradys** [comment]
Hi,
I read your solutions, but none of them works for me.
I'm using this library https://github.com/reyesoft/ngx-jsonapi and I need to set my API url in `AppModule`. 
``` 
imports: [
    NgxJsonapiModule.forRoot({
      url: myUrl,
    })
  ]
```
I want `myUrl` to be dynamically set depending on the current `window.location.origin`, but I can't make it work in AOT build. I tried with `InjectionToken`, but I need this value before the constructor, in imports section in NgModule.
Is it possible to make it work?
