### ISSUE TITLE
ng serve sourcemaps are ineffective after angular 6 migration

### ISSUE THREAD

**Issue by bioub** [angular/angular-cli#10959]
### Versions
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.3
Node: 10.1.0
OS: darwin x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
    

```

### Repro steps
* `ng new test-app`
* `cd test-app && npm start`
* Launch Chrome and try to find the sources

### Observed behavior
In Angular 5, in Chrome DevTools sources were present in webpack:// > . > src, now I don't have them anymore (ng serve outputs .map files were created)

### Desired behavior
Debugging sources

**Comment by bioub** [comment]
I deleted and recreated my Chrome Profile and now it works again !

**Comment by filipesilva** [comment]
Not sure why that was happening but glad to hear it's sorted.

**Comment by stefvardalos** [comment]
The same thing happens to me, only when I try to serve the application with an environment ( ng serve --configuration user ). Regular ng server works as expected. Tried different browsers and also deleting my Chrome account, doesnt change anything. (identical version on everything with bioub )
