### ISSUE TITLE
Allow to do module imports with "provided" scope

### ISSUE THREAD

**Issue by Antoniossss** [angular/angular-cli#10951]
So if I have a `SharedModule` that contains shared code and I use that in lazy loaded module, every lazy module bundle will contains `SharedModule` code. 

What If I could tell the compiler that given import will is already provided so it will know that there is no need for inclusion?

It would work like in Maven - dependency scope=provided means that this dependency will be present on runtime and there is no need to pack it with application.

it could looks like this:
```
@NgModule({
  imports: [
    { token: CommonModule, provided:true },
    HttpClientModule,
    ReactiveFormsModule,
    FormsModule,
  ],
```

or with separate property of NgModule like 

```
@NgModule({
   providedDependencies:[
    HttpClientModule,
    ReactiveFormsModule,
    FormsModule,]
})
```

**Comment by filipesilva** [comment]
Closing as it was answered by @juristr, cheers!

**Comment by clydin** [comment]
>So if I have a SharedModule that contains shared code and I use that in lazy loaded module, every lazy module bundle will contains SharedModule code.

This is actually not the case for CLI 6+ (and partially for older versions).  Any common javascript modules will be split out and only loaded once as needed by the lazy routes.

**Comment by Antoniossss** [comment]
is there a way to verify whitch module goes to separate file? or is it like
if 1 impprt is used in 2 modules the this one is extracted to separate
dependency file?

wt., 22.05.2018, 16:32 użytkownik clydin <notifications@github.com> napisał:
