### ISSUE TITLE
ng generate @angular/material:material-nav not working

### ISSUE THREAD

**Issue by felsteadd** [angular/angular-cli#10960]
### Versions
```
Angular CLI: 6.0.3
Node: 10.1.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.1.0
typescript                   2.7.2
```

### Repro steps
* ng new my-new-app --routing
* ng add @angular/material
* npm install
* ng generate @angular/material:material-nav --name=home
* ng serve

### Observed behavior
Fails to compile with the following error:

ERROR in src/app/home/home.component.ts(13,3): error TS2322: Type ‘Observable<boolean>’ is not assignable to type ‘Observable<BreakpointState>’. Type ‘boolean’ is not assignable to type ‘BreakpointState’.

The code causing the error is the generated code from step 4 above (home.component.ts)
```
sHandset$: Observable<BreakpointState> = this.breakpointObserver.observe(Breakpoints.Handset)
.pipe(
map(result => result.matches)
);
```
### Desired behavior
ng serve should compile and run the generated application locally without the observed error.

### Mention any other details that might be useful (optional)
OS Mac OSX High Sierra

**Comment by Airblader** [comment]
This is an issue in Angular Material, not in Angular CLI. And it was fixed in https://github.com/angular/material2/pull/11448

**Comment by hlm61** [comment]
Change 
isHandset$: Observable<BreakpointState> =
in
isHandset$: Observable<boolean> =

**Comment by hlm61** [comment]
Sorry, change
isHandset$: Observable<BreakpointState> =
in
isHandset$: Observable<boolean> =

**Comment by hlm61** [comment]
Sorry Change BreakpointState in boolean

**Comment by hlm61** [comment]
Change :
isHandset$: Observable<boolean> = this.breakpointObserver
    .observe(Breakpoints.Handset)
    .pipe(map(result => result.matches));

**Comment by hlm61** [comment]
**Change:**<br>
`isHandset$: Observable<BreakpointState> = this.breakpointObserver`<br>
`.observe(Breakpoints.Handset)`<br>
`.pipe(map(result => result.matches));` <br>
**in**<br>
`isHandset$: Observable<boolean> = this.breakpointObserver`<br>
`.observe(Breakpoints.Handset)`<br>
`.pipe(map(result => result.matches));`<br>

**Comment by felsteadd** [comment]
Closing this issue as I have a manual workaround based on angular/material2#11448
