### ISSUE TITLE
Problem with upload image, Cannot read property 'subscribe' of undefined

### ISSUE THREAD

**Issue by Redgull6** [angular/angular-cli#10968]
I have a simple create post function that and i want to create a post when i fill the title,content and image:
![createpost](https://user-images.githubusercontent.com/39133455/40419547-58e582fe-5e8e-11e8-94f3-0396f1f0a4e7.PNG)

But when i upload an image the progress bar fills, the image is uploaded to firebase but it doesn't let me create a post and when i test it in console it has this error:
![error](https://user-images.githubusercontent.com/39133455/40419914-5f8baf88-5e8f-11e8-9821-b0f9550692fb.PNG)

Here is the code for upload image and create post:
![postimage](https://user-images.githubusercontent.com/39133455/40419335-b313f7d4-5e8d-11e8-85f5-627ac7f7b940.PNG)

**Comment by vamshi9666** [comment]
check usage of `downloadURL`  in other files .

**Comment by Redgull6** [comment]
I only have this:
`downloadURL: Observable<string>`
 above the upload image and create post code.

**Comment by vamshi9666** [comment]
you imported Observable ?

**Comment by Redgull6** [comment]
Yes I have : 
import {observable} from 'rxjs/ observable';

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
