### ISSUE TITLE
 angular2-time-select@0.9.3 postinstall: `typings install`

### ISSUE THREAD

**Issue by ankitpachori** [angular/angular-cli#10971]
Unable to install npm getting error 
[2018-05-23T11_47_33_072Z-debug.log](https://github.com/angular/angular-cli/files/2030836/2018-05-23T11_47_33_072Z-debug.log)
s installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.2.4 requires a peer of @angular/common@2.2.4 but none
 is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.2.4 requires a peer of @angular/platform-browser@2.2.
4 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/router@3.2.4 requires a peer of rxjs@5.0.0-beta.12 but none is
 installed. You must install peer dependencies yourself.
npm WARN ng2-select@1.2.0 requires a peer of @angular/common@^2.3.0 but none is
installed. You must install peer dependencies yourself.
npm WARN ng2-select@1.2.0 requires a peer of @angular/core@^2.3.0 but none is in
stalled. You must install peer dependencies yourself.
npm WARN ng2-tooltip@0.0.7 requires a peer of @angular/core@^2.0.0 but none is i
nstalled. You must install peer dependencies yourself.
npm WARN The package jquery is included as both a dev and production dependency.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular2-time-select@0.9.3 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-time-select@0.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ankit.Panchori\AppData\Roaming\npm-cache\_logs\2018-05-24T
07_35_04_036Z-debug.log

**Comment by vamshi9666** [comment]
can you mention your error more specifically .
how you produced this error ?
what you expected to happen ?

**Comment by vamshi9666** [comment]
this error is caused due to this [package](https://www.npmjs.com/package/angular2-time-select )
sadly it  is unmaintained.

**Comment by ankitpachori** [comment]
I am getting this error when going to install npm

**Comment by vamshi9666** [comment]
installing npm ? it comes wit installing node itself .
specify node and npm versions ?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
