### ISSUE TITLE
Do not pass `ng test` when an unknown option prevent them to run

### ISSUE THREAD

**Issue by maxime1992** [angular/angular-cli#10970]
### Versions
```
Angular CLI: 6.0.3
Node: 10.0.0
OS: linux x64
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@angular/flex-layout              5.0.0-beta.13
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* run `ng test --single-run true`

### Observed behavior
```
$ ng test --single-run true
Unknown option: '--singleRun'
Done in 0.69s.
Job succeeded
```

:warning: **None of the tests run but the job succeeded** :warning: 

**People who upgraded to angular-cli 6.x might have missed that and get their tests passing without actually running them.**

### Desired behavior
If the tests are not run, `ng test` should fail.

### Mention any other details that might be useful (optional)
Possibly a bit related to https://github.com/angular/angular-cli/issues/10677

**Comment by gperdomor** [comment]
@maxime1992 `ng test --watch=false` should work

**Comment by maxime1992** [comment]
@gperdomor yep thanks, I've checked the doc right after and I've seen the changes.

My point here is that for people upgrading from 5 to 6 and who've missed that out... Some of them might have a :evergreen_tree: :evergreen_tree: :evergreen_tree: CI with actually no tests running.

Pretty dangerous. If tests are not running, an error should be thrown instead.

**Comment by filipesilva** [comment]
There's a PR about this problem, but it's revealing some problems in our error handling logic https://github.com/angular/angular-cli/pull/10923

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
