### ISSUE TITLE
ng serve plays multiple beep sound

### ISSUE THREAD

**Issue by Qriva** [angular/angular-cli#10974]
### Versions

```
Angular CLI: 6.0.3
Node: 8.9.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.2.0
typescript                   2.7.2
```
### Repro steps
* Updated cli by `npm install -g @angular/cli`
* Created new project by `ng new PROJECT-NAME`
* Moved to project and used `ng serve`

### Observed behavior

After running `ng serve`, console plays all the time "beep" sound.
```
$ ng serve
** Angular Live Development Server is listen
host:4200/ **
 10% building modules 3/3 modules 0 active

[...]
```
It looks like *beep* is played for each emited/built module (it plays 3 times for the strart and then spam like around 100 times).
First of all running ng serve is very annoying because sound plays many many times and second - as long as console plays *beeps* it hangs and it is not possible to close it or stop the task.

### Desired behavior
No ear rape :)

### Mention any other details that might be useful (optional)
As I siad it plays probably for everyone compiled module and this can be actually webpack fault.
Also asked other people if it happens for them and 1 of 3 confirmed it happens to him too.

**Comment by ryvo** [comment]
I have the same problem:

```
Angular CLI: 6.0.3
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
...

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by filipesilva** [comment]
I have no idea of what can cause this. I have never seen it myself. 

Maybe it's related to your console? Which one are you using?

There was a problem in the past with some characters, but we've removed it since: https://github.com/angular/angular-cli/pull/9336 and https://github.com/angular/angular-cli/pull/9336

**Comment by ryvo** [comment]
I'm using Windows 7 Professional SP1 64-bit command line.

**Comment by Qriva** [comment]
I'm on Win7 too and I use git bash to do all the stuff in most of cases. The problem is I checked windows console too and `ng serve` still produce sounds.

Maybe this may help a little:
Friend created new project with new angular cli and when I served it I got beeps first time.
Later I decided to test a little so I used `ng serve` on project created around 4-5 months ago and everthing was fine. After this I created new project by `ng new project` and this project was also fine but it was using older cli/angular _( package.json from this project below )._
I decided then to run `npm install -g @angular/cli` and from this moment new generated projects are beeping.
```

{
  "name": "test-beeps",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.0",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
}

```

**Comment by Qriva** [comment]
@filipesilva Could you try provide some instructions what should I do to fix it?
I mean some kind of angular reinstall? clear cache or any action that may repair it?

I understand it can be hard to reproduce or find the exact problem but maybe you know something I can do to find solution.

**Comment by matsnd** [comment]
The same situation on  win7 64. Console process not responding while beeping.

**Comment by norbertpeplak** [comment]
I have the same issue, every single time. Real madness. It just beeping with every command line : 
48% bulding modules ...
92% after chunk asset optimization ...
after that is not responding and beeping like crazy, later it compiles successfully but with a Time: 14137ms

**Comment by tachycardian** [comment]
@filipesilva - yep - just checked and seems global thing on Win7 64 (Home Premium / Professional licenses checked yet) using windows ```cmd```. ```ng serve``` is causing multiple (around 100? beeps - seems related to bullet characters around 1 per compile percent / as per previous issue ?) causing some additional time +-3min to compile + ear rape ;)

**Comment by sirzooro** [comment]
The same for me, very annoying! I use Win 7 Pro SP1 x64.

Fortunately these beeps are not played when I use Cygwin console, so some workaround is available.

I also noticed one more thing: when I use Windows cmd line, "ng serve --open" printed every progress update in new line. In Cygwin console every new update overwrites previous one.

There is also some problem with special chars on Windows cmd line. In Cygwin I have this at the end:
```
i ｢wdm｣: Compiled successfully.
```
In Windows cmd line it looks this ways:
```
i ?wdm?: Compiled successfully.
```

**Comment by filipesilva** [comment]
Hi all, do you still have these beeps with the latest versions?

**Comment by metimus** [comment]
I had this problem too (Win 7 Ultimate SP1) don't remember exactly when it was fixed, but I don't have this problem anymore.

**Comment by filipesilva** [comment]
Closing for now then. If someone else is seeing this still please let me know.
