### ISSUE TITLE
Unable to update / install beta6

### ISSUE THREAD

**Issue by olakara** [angular/angular-cli#1097]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?   
    Windows 8

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
λ ng -v
angular-cli: 1.0.0-beta.5
node: 4.2.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
 I tried to update the cli version from beta 5 to beta 6 by issuing: npm update -g angular-cli

4. The log given by the failure. Normally this include a stack trace and some
   more information.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\NodeJs\\node.exe" "C:\\NodeJs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-c
li"
npm ERR! node v4.2.2
npm ERR! npm  v3.9.3
npm ERR! path c:\NodeJs\node_modules\.staging\abbrev-0137066c
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'c:\NodeJs\node_modules\.staging\abbrev-0137066c' ->
'c:\NodeJs\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'c:\NodeJs\node_modules\.staging\abbrev-0137066c' ->
'c:\NodeJs\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Abdel\npm-debug.log
npm ERR! code 1

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by olakara** [comment]
All problems solved after updating in this manner:
```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
```

**Comment by JB-Tellez** [comment]
On OSX 10.11.4, Node 5.4.1, NPM 3.9.5, NVM 0.31.1 I ran

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

and hang about 25% of the way through on "loadRequestedDeps"

**Comment by filipesilva** [comment]
@olakara glad to hear it's fixed!
@JB-Tellez I will check your problem in the other opened issue, https://github.com/angular/angular-cli/issues/1110
