### ISSUE TITLE
how can i sloved this 

### ISSUE THREAD

**Issue by fuzitu** [angular/angular-cli#10988]
![111111](https://user-images.githubusercontent.com/25705181/40480156-31b77d0c-5f80-11e8-817e-96be02692c70.png)
![2222](https://user-images.githubusercontent.com/25705181/40480158-32a6303c-5f80-11e8-812f-d6c2981b37bd.png)
Thank you very much!!How can i  use this .ttf.woff font?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If I had to bet, that error about the path to the font is the cause of your problem. Maybe that font doesn't exist.
