### ISSUE TITLE
enum in separate file throws runtime error when built with AOT

### ISSUE THREAD

**Issue by dsoltesz** [angular/angular-cli#10983]
### Versions
```
Angular CLI: 6.0.3
Node: 8.11.1
OS: win32 x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      6.1.0
@angular/flex-layout              6.0.0-beta.15
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

```

### Repro steps

On opening the resulting webpage i receive Cannot read property 'none' of undefined errors. Those errors result from undefined enums at runtime.

Very much simplified example (with 2 separate files)

action-type.enum.ts (enum in separate file)
export enum eActionType {
    none,
    actionA
    ...
}

test.component.ts (component in separate file)
import { eActionType } from './action-type.enum';

@Component({ ... })
export class Test {

    // @Runtime eActionType (eActionType.none) will be undefined
    private/protected/public actionType: eActionType = eActionType.none;

### Observed behavior
```
runtime error but only when building in AOT
```

### Desired behavior
enum should not be undefined

**Comment by Principe92** [comment]
I am getting the same error. If I run `ng serve aot` I don't get the error. However, if I run `ng build --prod --aot` I get the error

**Comment by Principe92** [comment]
@dsoltesz according to [https://github.com/angular/angular-cli/issues/10655](url), setting the `"buildOptimizer": false,`  in angular.json seems to fix it.

**Comment by dsoltesz** [comment]
Doesn’t that kinda negate the benefits of using aot?

**Comment by Principe92** [comment]
@dsoltesz Yep. I guess we will have to turn it off until they fix it.

**Comment by dsoltesz** [comment]
is anyone going to look at this...seems to be a pretty big regression, enums not working in AOT?

**Comment by dsoltesz** [comment]
This is a breaking change from past releases.  Is there any target build that this will be addressed?

**Comment by Invis1ble** [comment]
> any work around

set `buildOptimizer` to `false` in `angular.json`

**Comment by dsoltesz** [comment]
this does work but obviously lose that optimization...hopefully someone will fix this.

**Comment by filipesilva** [comment]
Heya, does this still happen with the latest 6.0.x releases?

**Comment by filipesilva** [comment]
Actually, I'm going to close in favor of https://github.com/angular/angular-cli/issues/10655. It seems to be the exact same thing but there's some more information and a better repro there.

**Comment by dsoltesz** [comment]
this didn't start happening until we upgraded to 6.0.x

**Comment by dsoltesz** [comment]
ok, will subscribe to that post, thanks
