### ISSUE TITLE
Issues with multiple outlets

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#10989]
i am trying to use multiple outlets for lazyloading(for modules) like below

import {NgModule} from '@angular/core';
import {Routes, RouterModule} from '@angular/router';

const routes: Routes = [
    {
        path: '',
        loadChildren: './dashboard/dashboard.module#DashboardModule',
        data: {pageTitle: 'Dashboard'}
    },
    {
        path: 'user',
        loadChildren: './user/user.module#UserModule',
        outlet: 'users',
    }
];

@NgModule({
    imports: [RouterModule.forRoot(routes)],
    exports: [RouterModule]
})
export class AppRoutingModule {}

for the above am getting this below errors

Error: Invalid configuration of route 'user': a componentless route cannot have a named outlet set
    at validateNode (router.js:526)
    at validateConfig (router.js:515)
    at Router.push../node_modules/@angular/router/fesm5/router.js.Router.resetConfig (router.js:3546)
    at new Router (router.js:3427)
    at setupRouter (router.js:5385)
    at _callFactory (core.js:9291)
    at _createProviderInstance$1 (core.js:9237)
    at initNgModule (core.js:9170)
    at new NgModuleRef_ (core.js:9899)
    at createNgModuleRef (core.js:9888)

please fix the above error...

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
