### ISSUE TITLE
Provide option to re-use configurations in angular.json

### ISSUE THREAD

**Issue by PapaNappa** [angular/angular-cli#10987]
I am working on a project with different languages.
This requires that each language is a separate configuration in the `angular.json`, eg

```
"configurations": {
  "prod-en": {
    "optimization": true,
    "outputHashing": "all",
    "sourceMap": false,
    "extractCss": true,
    "namedChunks": false,
    "aot": true,
    "extractLicenses": true,
    "vendorChunk": false,
    "buildOptimizer": true,
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.prod.ts"
      }
    ],
    "i18nLocale": "en",
    "baseHref": "/en/"
  },
  "prod-fr": {
    "optimization": true,
    "outputHashing": "all",
    "sourceMap": false,
    "extractCss": true,
    "namedChunks": false,
    "aot": true,
    "extractLicenses": true,
    "vendorChunk": false,
    "buildOptimizer": true,
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.prod.ts"
      }
    ],
    "i18nLocale": "fr",
    "baseHref": "/fr/"
  },
  …
]
```

This very soon becomes a maintenance nightmare and is definitely not DRY.
And all this only for enabling different languages.
The languages *could* be configured using `ng build --i18n-locale=en …`, but unfortunately `ng serve` does not provide these options.
(Before v6, i18n could be configured using CLI parameters for `ng serve`.)

This becomes worse when one wants to have a different set of options for `ng serve` (hashing, disable optimisations, source maps, etc.).
Then, one has to add another set of configurations (e.g. 'dev-en', 'dev-fr'), containing only the i18n options.

A third dimension (the first two being 'locale' and 'buildType') are different environment files.
Thus, if my application is deployed in three languages on three different environments, I need 9 different configurations for the build, and up to 9 more for local testing.

Thus, a mechanism to easily mix and match different sets of configurations would be great.
Or am I missing another feature that would solve my problem?

**Comment by istiti** [comment]
what about `ng build -c=prod-fr`

**Comment by PapaNappa** [comment]
I know how to build these configurations. But as stated above (in my edited post), the current system can easily lead to (for example) 18 different configurations. And most of them share a large part.

This leads to a large `angular.json` file, which also is not very easy to read due to so man duplications. And editing all of them is error-prone. You might easily forget one config or mess something different up.

**Comment by istiti** [comment]
apologize i still not understand, is this what you are speaking about: https://github.com/angular/angular-cli/issues/10612 

Why not putt other options  inside build.options like : 
![image](https://user-images.githubusercontent.com/2789203/40477330-7a390e90-5f46-11e8-8bf4-800f63899e0b.png)


And if you don't want write  i18n specific to language inside angular.json you cant still write them inline in command 
so package.json insdie scripts : `"fr": "ng build --i18nLocale=fr (...and so on)",`
then your file angular.json  will be small :-D and you run build `npm run fr`

**Comment by PapaNappa** [comment]
Yeah, #10612 seems to be what I want.

---

Of course I can use `ng build --i18nLocale`, but I cannot use `ng serve --i18nLocale`, so I still need more configuration, bloating up the `angular.json`.

The issue is not only with languages, but generally with different build options, environments etc.
