### ISSUE TITLE
A11y reads only Loading then return to Window Title infinite loop

### ISSUE THREAD

**Issue by hijoncon** [angular/angular-cli#1099]
Currently using this for new project, but notice it's not compatible in accessibility.  I am using voice over to test my site.  For some reason, the page load reads the "Loading" and return back to the window title...

> ## Please provide us with the following information:
> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>    El Capitan
1. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
       node --version
   And paste the result here.
   v5.11.0
2. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
3. The log given by the failure. Normally this include a stack trace and some
   more information.
4. Mention any other details that might be useful.
   
   > ---
   > 
   > > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
The www.angular.io authors are currently looking at acessibility concerns at the moment, but there isn't yet a lot of information about how to address it with A2 apps. 

Once there's a guide there we'll look at implementing it's recommendations.

**Comment by filipesilva** [comment]
Closing as outdated.
