### ISSUE TITLE
Environment variable in angular6 libraries

### ISSUE THREAD

**Issue by Rkubisiak** [angular/angular-cli#10996]
### Versions
```
Angular CLI: 6.0.2
Node: 9.11.1
OS: win32 x64
Angular: 6.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.3
@angular-devkit/build-ng-packagr   0.6.0
@angular-devkit/build-optimizer    0.6.3
@angular-devkit/core               0.5.13
@angular-devkit/schematics         0.5.13
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.3
@schematics/angular                0.6.2
@schematics/update                 0.6.2
ng-packagr                         3.0.0-rc.3
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.8.3
```

### Repro steps
* ng generate library lib_name
* create 2 environment files inside library folder
* in angular.json set configurations for lib_name project (with fileReplacements array which will switch environment file depending on configuration used)
* run ng build lib_name

### Observed behavior
```
Error:
"Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(fileReplacements)."
```

### Desired behavior
Lib should build accordingly to selected configuration

**Comment by filipesilva** [comment]
The library builder does not support the same options as the app browser builder. Building libraries uses https://github.com/dherges/ng-packagr, which has different functionality.

You can see what options you can use in the `angular.json` file by running `ng build lib_name --help`.
