### ISSUE TITLE
Cannot find module '@angular/cli/plugins/webpack'

### ISSUE THREAD

**Issue by RockGuitarist1** [angular/angular-cli#10994]
### Versions
```
Angular CLI: 6.0.3
Node: 8.9.4
OS: win32 x64
Angular: 6.0.3

@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.2.0
typescript                   2.7.2
webpack                      3.10.0
```

I have an Electron app using Angular 6 (just upgraded) and upon trying to run the app, I got this error: 'Cannot find module '@angular/cli/plugins/webpack''. I looked in the node_modules folder and found where the webpack file used to exist, but now it is gone. What is the solution to this?

NOTE: The angular app was ejected, hence why I am using Webpack.

I still need reference to these 2 imports in webpack: NamedLazyChunksWebpackPlugin,
  BaseHrefWebpackPlugin

UPDATE: Also ngtools/webpack is missing too. I see there is a npm library for it, but not sure if it will work since webpack has been removed from the cli folder.

**Comment by filipesilva** [comment]
I'm not sure what you're doing exactly, but there is no eject command in Angular CLI 6 yet. If you are using a ejected application I suggest you use Angular CLI 1.7 instead. You can still use Angular 6 proper, just not the CLI 6 with ejected applications.

Either way I am sorry to say that when you eject the responsibility of your build configuration is now wholly on your side.

**Comment by robbiesmith79** [comment]
Where did these functions go?! I need them or alternate functions to use instead.

**Comment by BruneXX** [comment]
Hi Guys, there's no nothing to do with this? those plugins like "NamedLazyChunksWebpackPlugin" are deprecated in new versions?
