### ISSUE TITLE
ng test Istanbul code coverage report exclude files

### ISSUE THREAD

**Issue by sureshdotariya** [angular/angular-cli#10997]
In Angular 5.2, we can exclude the files from Istanbul code coverage report using **.angular-cli.json** with below code and it works fine.

`"test": {
        "karma": {
            "config": "./karma.conf.js"
        },
        "codeCoverage": {
            "exclude": [
               XXX/X.ts",
               XXX/X.ts"
            ]
        }
    },`

In Angular 6.0.3, we tried adding in **angular.json**  with below code. But its not working.

`"test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": ["src/app/lib/hammerJs/hammer.js"],
            "styles": [],
            "assets": ["src/resources"],
            "codeCoverage": {
               "exclude": [
               XXX/X.ts",
               XXX/X.ts"
               ]
             }
          }
        }`
 
### Versions
```
Angular CLI: 6.0.3
Node: 8.9.1
OS: darwin x64
Angular: 6.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.2.0
typescript                        2.8.3
webpack                           4.8.3

```

**Comment by sureshdotariya** [comment]
'codeCoverageExclude' property inside 'options' solved my problem.

**Comment by kwa** [comment]
Example of the solution:

```json
"test": {
  "builder": "@angular-devkit/build-angular:karma",
  "options": {
    "main": "src/test.ts",
    ...
    "codeCoverageExclude": [
      "src/app/in-memory-data.service.ts",
      "src/test-util/stubs.ts"
    ]
  }
}
```
(using node v8.11.3 and ng v6.0.8)
