### ISSUE TITLE
Provide test command for generated projects

### ISSUE THREAD

**Issue by rodyhaddad** [angular/angular-cli#11]
We should overwrite ember-cli's test command, as it uses testem and is setup to test ember-cli applications.

We'd want to it to fire-up karma instead.

We'll need to figure out the story for karma pre-processors, combined with the broccoli build pipelines, as we need to account for addons in projects.

Related #10

**Comment by filipesilva** [comment]
@Brocco has been working on this in https://github.com/angular/angular-cli/pull/86

**Comment by Brocco** [comment]
Closing as it is being tracked via #86
