### ISSUE TITLE
Run custom webpack plugin while running CLI scripts

### ISSUE THREAD

**Issue by rmartin94** [angular/angular-cli#11004]
### Versions
```
Angular CLI: 1.7.4
Node: 8.9.0
OS: win32 x64
Angular: 5.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.8.3
webpack-bundle-analyzer: 2.11.1
webpack-dev-server: 2.11.2
webpack: 3.11.0
```

### Observed behavior

Angular CLI uses webpack under the hood so as to bundle, serve, build you app. This is clear. It's also clear that they don't expose the webpack.config.js used to the developers and this has it's reasons. For more advance webpack configuration requirements you have the option to use ng eject and then disable angular cli by taking full control and responsibility for the the build and dev server which will become part of the app itself 

### Desired behavior

My project now has the need to retrieve, process and merge certain .json files onto an output file. The only way I found for doing this is by using a webpack plugin called MergeJsonWebpackPlugin (+WriteFilePlugin to store the output on disk rather than on virtual memory)

Now, for achieving this I have to explicitly run the webpack dev server. Is there a possibility for having this plugins to run while executing the common npm start script (= ng serve)? I mean is there's a possibility to append this plugin/configuration to the webpack.config that angular cli uses under the hood while running this common scripts?

I've read that we have the option to run ng eject which will return the current cli webpack config but then angular cli will be disabled as a whole, loosing some other great features it has. Its not an option

Is there a way to do this with cli?

**Comment by vadjs** [comment]
Now i know the only one way to customize Webpack config witout eject. It's monkey-patching `node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js` file using `postinstall` script. It's really dirty way but it works.

It could be really good and useful feature if i could import current webpack config and modify it using built-in tools.

**Comment by loftyduck** [comment]
This request seems similar/related to https://github.com/angular/angular-cli/issues/1656

**Comment by clydin** [comment]
eject functionality is no longer available in the latest version (6.x+).  For custom webpack configurations the following unofficial add-on is a suggested solution: https://github.com/manfredsteyer/ngx-build-plus
