### ISSUE TITLE
(app.assets || []).map is not a function

### ISSUE THREAD

**Issue by hpdrago** [angular/angular-cli#11001]
### Versions
```
Angular CLI: 6.0.3
Node: 10.2.0
OS: win32 x64
Angular: 6.0.3
... animations, cli, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, upgrade

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@angular/cdk                 6.1.0
@angular/material            6.1.0
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.2.0
typescript                   2.8.3
webpack                      3.12.0
```

### Repro steps

I am running: 'ng update @angular/cli to migrate from Angular 5 to Angular 6

### Observed behavior
```
C:\Users\michael.earl\Projects\StockTracker\MyStockTickersUI>ng update @angular/cli
            Updating karma configuration
            Updating configuration
(app.assets || []).map is not a function

C:\Users\michael.earl\Projects\StockTracker\MyStockTickersUI>ng --version
```

### Mention any other details that might be useful (optional)
I have done the following:
1. Updated to latest NPM version
2. Updated to latest node.js
3. Package.json included below:

{
  "name": "my-stock-tickers-ui",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update`",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.0.3",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/material": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/platform-server": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@angular/upgrade": "^6.0.3",
    "@types/lodash": "^4.14.105",
    "@types/node": "^7.0.56",
    "@types/quill": "^1.3.2",
    "ajv": "^6.3.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.5.6",
    "css-loader": "^0.28.11",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jasmine": "^3.1.0",
    "jquery": "^3.2.1",
    "json-typescript-mapper": "^1.1.3",
    "json2typescript": "^1.0.5",
    "ng2-currency-mask": "^4.3.4",
    "ng2-toastr": "^4.1.2",
    "ngx-cookie-service": "^1.0.9",
    "primeng": "^5.2.3",
    "quill": "^1.3.6",
    "reflect-metadata": "^0.1.10",
    "retyped-http-status-codes-tsd-ambient": "^1.0.5-0",
    "rxjs": "^6.2.0",
    "rxjs-tslint": "0.1.4",
    "systemjs": "0.19.40",
    "tether": "^1.4.0",
    "ts-helpers": "^1.1.2",
    "webpack": "^3.4.1",
    "webpack-dev-server": "^2.11.2",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "^6.0.3",
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.7",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.16.4",
    "@types/node": "^10.1.1",
    "codelyzer": "^4.3.0",
    "css-loader": "^0.28.7",
    "gulp": "^3.9.1",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.0",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "~5.3.2",
    "style-loader": "^0.18.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.10.0",
    "typescript": "~2.8.3",
    "webpack": "^3.4.1",
    "webpack-dev-server": "^2.4.5"
  }
}

**Comment by sheyooo** [comment]
I commented out "assets": "assets" from `angular-cli.json`, then ran the command again, that worked for me

**Comment by hpdrago** [comment]
They sheyooo, I'll give that a try..  Much appreciate the response.

**Comment by alan-agius4** [comment]
My two cents would be that in your `assets` you had a string instead of an array which is not following the schema.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
