### ISSUE TITLE
npm i -g @angular/cli not working in winodows 

### ISSUE THREAD

**Issue by devqualwebs** [angular/angular-cli#11008]
### Versions
```
node v8.9.1
npm 5.5.1
Windows 10
```

I am simply trying to install @angular/cli through npm. But I am getting this issue related to permission. I have searched and found some solution like cleaning cache by the command `npm cache clean -f` or deleting cache folder or run as administrator too. But nothing worked for me.

![screenshot_115](https://user-images.githubusercontent.com/17046430/40528423-a04e46d6-600e-11e8-92a2-81f1e6b83dce.png)

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
