### ISSUE TITLE
load 3rd lib's css?

### ISSUE THREAD

**Issue by Newbie012** [angular/angular-cli#1101]
Windows 10
angular-cli: 1.0.0-beta.5
node: 6.2.1
os: win32 x64

I'm pretty new to the whole front-end thing. Actually I never used Angular 1, so my question might sound foolish.

There are some libraries that require me to load a css file. I thought about adding it to the `vendorNpmFiles` but I really don't know how I'm suppose to fetch the item next.

BTW, Will it be smart if I should install gulp/grunt in case I'll have to load many 3rd css'?

**Comment by hmrc87** [comment]
In order to fetch CSS files within a library (in node_modules) you can add it to the filetypes-glob like this 

```
 /* global require, module */

var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
    //[...]  more packages
      "ng2-dragula/**/*.+(css|js|js.map)",
   // [...] more packages
    ]
  });
};

```

In my case dragula finds the CSS file because it will get exported to dist/vendor while building (production & development)

Hope this helps

**Comment by filipesilva** [comment]
@hmrc87 answer is correct. You can then load it via a `<link href="vendor/my-lib/style.css" rel="stylesheet">` tag.

Whatever is on the `vendorNpmFiles` array gets copied over to the `dist/vendor/` directory.
