### ISSUE TITLE
Angular 6 npm install

### ISSUE THREAD

**Issue by mhpm** [angular/angular-cli#11018]
hey guys, i have this issue: agular 6.0.5
i installed angular 6: npm install -g @angular/cli
i created a new project: ng new angularstore
and i have this issue
![image](https://user-images.githubusercontent.com/32468301/40553152-68744f0a-6007-11e8-9625-aeed5bcbe0da.png)

and inside the folder que i run: npm install i hace the same issue,

![image](https://user-images.githubusercontent.com/32468301/40552712-2132db44-6006-11e8-94fb-9f7110a0d209.png)

I don't know why .. =(  i need help

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
