### ISSUE TITLE
Generated library's ng-package.json file creates the wrong output file path reference for the build system

### ISSUE THREAD

**Issue by bh3605** [angular/angular-cli#11017]
## I'm submitting a...
<pre><code>
[ x ] Bug report 
</code></pre>

## Current behavior
After building a library using the Angular CLI, app cannot find a reference to library when importing in app.module.ts

## Expected behavior
It finds a proper reference to MyTestLibrary.

## Minimal reproduction of the problem with instructions
Create a library containing capital letters like MyTestLibrary with the command
<code>ng g library MyTestLibrary</code>

Build MyTestLibrary with command <code>ng build MyTestLibrary</code>
Import library in app.module.ts with <code>import { MyTestLibraryComponent } from 'MyTestLibrary';</code>
*see error: can not find module MyTestLibrary*
## What is the motivation / use case for changing the behavior?
The Angular CLI is not providing a proper reference to where the build system outputs the library.

I found the library's generated ng-package.json file is using the libary's hyphenated form instead of the actual name of the library. The generator is also providing a file reference so you can actually reference your built library in tsconfig.json. These 2 file paths are differing. That's the problem. The build system will output your library to dist/my-test-library while your app only has an expected reference of dist/MyTestLibrary.

## Environment
Any

<pre><code>
Angular CLI version: 6.0.0

**Comment by DenisVuyka** [comment]
@filipesilva All libraries generated with 6.1.3. cannot be imported into the app using just the name. Example: `ng g library my-lib`. It is not possible to `import { MyModule } from 'my-lib'`, it will raise an error `Cannot find module 'my-lib'`

**Comment by DenisVuyka** [comment]
@bh3605 This helped me a lot https://github.com/angular/angular-cli/wiki/stories-create-library#note-for-upgraded-projects

**Comment by bh3605** [comment]
I'm not quite sure how your link references this issue. The partial build feature is def appreciated though. If you are getting `Cannot find module 'my-lib'`, and you are SURE it should be working, I typically ignore it or close and reopen vs code. You can also run `ng build` to make sure.
