### ISSUE TITLE
ng update - Custom Certificate for Registry

### ISSUE THREAD

**Issue by novatiny** [angular/angular-cli#11010]
We have a ProGet Server running internal, which we use to host our private packages but also to mirror the official npm registry. This ProGet Server uses a certificate trusted by our own local ca.

NPM works fine with our custom cert but "ng update" seems to ignore out ca settings.

"ng update" works fine with strict-ssl disabled, but this is not a solution that meets our internal security ruling.

### Versions

```
Angular CLI: 6.0.5
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.5
@angular/cli                      6.0.5
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.5
@schematics/update                0.6.5
ng-packagr                        2.4.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

You need a npm repository with an custom certificate.

* Set the registry - `npm config set registry https://proget.xxx.com/npm/repo`
* Configure the npm cert with `npm config set cafile "C:\\XXX.cer"` or `npm config set ca "BASE64 CERT"`
* run `ng update`

### Observed behavior

```
unable to get local issuer certificate
```

### Desired behavior

- Use the custom cert
- Show me the packages to update

### Mention any other details that might be useful (optional)
`ng update` works fine without the custom registry.

**Comment by BrAwnyTime** [comment]
I also need ng update to use the cafile npmrc configuration.

Would the changes be similar to that of the [strict-ssl changes](https://github.com/angular/angular-cli/issues/10596)? If so i can do up a pull request.

**Comment by clydin** [comment]
`cafile` as well as `_auth`, `username`, and `password` will be supported in 6.1 (currently in beta).
