### ISSUE TITLE
Running tests on multiple targets with yarn ignores SIGINT

### ISSUE THREAD

**Issue by texel** [angular/angular-cli#11024]
### Versions
```
Angular CLI: 6.0.5
Node: 8.9.4
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.5
@angular-devkit/build-angular      0.6.5
@angular-devkit/build-ng-packagr   0.6.5
@angular-devkit/build-optimizer    0.6.5
@angular-devkit/core               0.6.5
@angular-devkit/schematics         0.6.5
@angular/cli                       6.0.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.5
@schematics/angular                0.6.5
@schematics/update                 0.6.5
ng-packagr                         3.0.0
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
```

### Repro steps
* Run `$ yarn test` in a project with multiple projects (an app and a library for instance)
* Attempt to kill with ctrl+c

### Observed behavior
Tests continue to run in the background, requiring a manual `killall`. Running via `npm` lets me kill the test process but multiple SIGINTs have to be issued.

### Desired behavior
Tests should stop running when SIGINT is issued.

### Mention any other details that might be useful (optional)
I set up a repo that reproduces this issue: https://github.com/texel/angular-cli-sigkill-repro
The readme includes detailed instructions.

I am able to work around this by running `$ yarn test app-name`.

**Comment by filipesilva** [comment]
Just tried it with yarn and as far as I can tell the processes were killed. Let me know if you're still seeing this.
