### ISSUE TITLE
Package "@angular/material" was found but does not support schematics

### ISSUE THREAD

**Issue by playground** [angular/angular-cli#11021]
### Versions
```
Angular CLI: 6.0.5
Node: 9.4.0
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.5
@angular/cli                      6.0.5
@ngtools/webpack                  6.0.5
@schematics/angular               0.6.5
@schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* ng new newproject
* ng add @angular/material

```
ng add @angular/material
Installing packages for tooling via npm.
Package "@angular/material" was found but does not support schematics.
Error: Package "@angular/material" was found but does not support schematics.
    at NodeModulesEngineHost._resolveCollectionPath (/Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:77:23)
    at NodeModulesEngineHost.createCollectionDescription (/Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:106:27)
    at SchematicEngine._createCollectionDescription (/Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular-devkit/schematics/src/engine/engine.js:78:40)
    at SchematicEngine.createCollection (/Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular-devkit/schematics/src/engine/engine.js:71:43)
    at Object.getCollection (/Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular/cli/utilities/schematics.js:28:31)
    at AddCommand.getOptions (/Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular/cli/models/schematic-command.js:193:41)
    at AddCommand.<anonymous> (/Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular/cli/commands/add.js:30:49)
    at Generator.next (<anonymous>)
    at /Users/ljeff/git_repo/sandbox/wu/ngmat/node_modules/@angular/cli/commands/add.js:7:71
    at new Promise (<anonymous>)

```

**Comment by srijanreddy98** [comment]
In case its very urgent for you, you can install it via
`npm install --save @angular/material @angular/cdk`

**Comment by Brocco** [comment]
This is likely due to an earlier version of `@angular/material` prior to it including support for `ng add`.

To verify please run `npm ls @angular/material`

This could be caused by a proxy or already having an older version already installed.

**Comment by JackHitcher** [comment]
I face the same issue and could not add sidenav component with this material

**Comment by fmlong37** [comment]
I had similar issue. Went to install @angular/material and got a message that it was found but something was wrong (sorry, I forget). Looking for answers I found someone say its due to a bug and to modify the install script to npm add @angular/material@6.21 which actually worked.  From there, I needed to install the the other part, @angular/cdk. The errors I am seeing now line up with what I am seeing here. "Package "@angular/cdk" was found but does not support schematics." I tried ng add @angular/cdk@6.21 just like before but no difference this time. not sure where to go with this. Its halting a lot of style rendering in the UI

**Comment by playground** [comment]
> This is likely due to an earlier version of `@angular/material` prior to it including support for `ng add`.
> 
> To verify please run `npm ls @angular/material`
> 
> This could be caused by a proxy or already having an older version already installed.

@Brocco 
npm ls @angular/material
my-project@0.0.0 /workspace/my-project
└── (empty)

ng add @angular/material is still failing.

**Comment by cthulhuhoop** [comment]
I'm getting this error too installing @progress/kendo-* components. although it actually seems to install ok - just throwing the error.

Angular CLI: 6.2.5
Node: 8.11.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli,
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cli                      6.2.5
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.21.0

**Comment by yanfali** [comment]
Same issue adding d3. Angular noob

```console
Angular CLI: 6.2.7
Node: 10.11.0
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.7
@angular-devkit/build-angular     0.8.7
@angular-devkit/build-optimizer   0.8.7
@angular-devkit/build-webpack     0.8.7
@angular-devkit/core              0.8.7
@angular-devkit/schematics        0.8.7
@angular/cli                      6.2.7
@ngtools/webpack                  6.2.7
@schematics/angular               0.8.7
@schematics/update                0.8.7
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
```

**Comment by tanzeelrana** [comment]
did anyone find a solution to this ?

**Comment by hwebb** [comment]
I've finally managed to find where it came from for me.
it was the @angular/cdk that was not up to date, a `ng update @angular/cdk` was necessary

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
