### ISSUE TITLE
Issue with release 6.0.4

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#11022]
Post mortem of the issue with release 6.0.4

### What happened
Version 6.0.4 of the Angular CLI was published to npm on May 24. After it was released reports of [issues](https://github.com/angular/angular/issues/24120) with the new and generate commands were reported. As a result the decision was made to release version 6.0.5 which is the same version as 6.0.3, essentially rolling back release 6.0.4.

### What went wrong
Tracing down the issue led to this PR angular/devkit#899 which restricted the properties that can be sent to the default schematics to only those defined within the schema. The CLI removes non-schematic specific options so they are not passed through to the schematic engine, which allows schematics to specify the `additionalProperties` value to be false. A bug in the CLI was not removing the `dryRun` option because it was being defined as `dry-run` and the property `dryRun` was the one being removed. This caused the `dryRun` property to be passed to schematics which now have `additionalProperties` set to false, causing the reported issues.

### How is it being addressed
The bug in the CLI has been addressed in PR #11015 which renamed the property definition to `dryRun` which will allow proper filtering of the non-schematic options. The other step to address this is as this logic is changing the public API of the schematics, it will be included in a future minor release.

### What is being done to prevent it
Integration of the CI from the angular/devkit repo to also run the angular/angular-cli CI would catch errors like this in the future.

**Comment by filipesilva** [comment]
Closing as this has been sorted now, and the issue has been up for a while for visibility.
