### ISSUE TITLE
More to the point error message

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#11027]
### Versions
```
All up to 6.0.5
```

### Repro steps
I typed the faulty command: `ng add alib`, and was welcomed with:

### Observed behavior
![image](https://user-images.githubusercontent.com/1249083/40573980-7c601238-60ca-11e8-8597-143bdc9f6194.png)

### Desired behavior
A more to the point error message, without a large stack-trace that's not interesting to a user of the CLI.
The wall of red text obscured the message for me.

**Comment by alan-agius4** [comment]
This has been addressed and now it shows

```
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
```
