### ISSUE TITLE
Do you have a method to add DLL configuration in @angular/cli?

### ISSUE THREAD

**Issue by iwe7** [angular/angular-cli#11020]
### Versions
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

### Repro steps

* Step 1
* Step 2
* Step 3

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

### Mention any other details that might be useful (optional)

Do you have a method to add DLL configuration in @angular/cli?

**Comment by filipesilva** [comment]
No, we do not support DLL functionality. You can read more about why in https://github.com/angular/angular-cli/issues/4565.
