### ISSUE TITLE
Remove version when building

### ISSUE THREAD

**Issue by thanhngvpt** [angular/angular-cli#11036]
### Versions
```
Angular CLI: 6.0.3
Node: 10.2.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.1.0
typescript               2.7.2
```

Hi all,
How can i remove ng-version in `<app ng-version="x.x.x"></app>` when building?
I want to hide it to avoid detect tools can detect what/which version i'm using?
thanks.

**Comment by clydin** [comment]
This is not done during build but rather at runtime via Angular itself.  If this is an issue that you would like to pursue, please open an issue at https://github.com/angular/angular
