### ISSUE TITLE
Subresource integrity option

### ISSUE THREAD

**Issue by rhanb** [angular/angular-cli#11038]
Hello team,

Since the angular-cli v6, a lot of command option has been changed. I saw that acronyms has been deleted and only full name options are supported. Since the wiki is well documented it's not an actual issue.

But some options are still missing in the wiki. I'm actually aware of at least one: the subresource integrity:

#### Before v6:

```bash
-scd
```

#### After v6:

```
--subresource-integrity
```

I think this command should be more known and, why not, default. 

Unfortunately only contributors can change the wiki, that's why I'm creating an issue.

Thanks for this great tool, cheers from France 🇫🇷

**Comment by alan-agius4** [comment]
Documentation is now available in https://angular.io/cli
