### ISSUE TITLE
ng update @angular/cli fails when updating dotnet Angular template

### ISSUE THREAD

**Issue by danstur** [angular/angular-cli#11033]
### Versions
```
 ng --version
Your global Angular CLI version (6.0.5) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 8.11.2
OS: win32 ia32
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps
Use PowerShell with the current dotnet SDK (2.1.201), create an Angular template and then try to update it from angular 5 to 6 following the steps outlined [here](https://update.angular.io/)
```
dotnet new angular
cd .\ClientApp
npm install -g @angular/cli
npm install @angular/cli
ng update @angular/cli
```

### Observed behavior
`ng update @angular/cli` fails with the following error:
```
Your global Angular CLI version (6.0.5) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Error: Unexpected end of JSON input
Unexpected end of JSON input
```

### Desired behavior
`ng update @angular/cli`  should not fail.

**Comment by danstur** [comment]
The problem seems to be that the used template has a dev-dependency on angular/cli 1.7.4 specified which is not replaced with the given instructions, so all the installing is useless and we're still using the old angular-cli version.

Not sure if this is a bug in the angular template (should angular/cli be a dev-dependency?) or a valid scenario. In any case since the dotnet template is presumably quite popular, at least in some parts of the web, mentioning this somewhere might be helpful.

**Comment by drullo** [comment]
@danstur thank you!  For me, this error only occurred after upgrade @angular/cli from 6.0.3 to 6.0.7.  All of the projects that I upgraded prior to today on earlier 6.x versions worked fine.

Also, I did not have to upgrade typescript manually to get @angular/core to upgrade - it just worked as expected.  So forcing @angular/cli to @latest is the only modification I had to make to the process.

**Comment by arunranjan1988** [comment]
i have updated but not work... kindly share compelete solution

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
