### ISSUE TITLE
13 vulnerabilities (9 low, 4 high) at ng new foo

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#11037]
Fresh ng new project reports this by npm:
found 13 vulnerabilities (9 low, 4 high)

Looks like everything is related to karma somehow, so i think this should not be critical.
Anyway getting a security warning when creating a new project does not feel good. 

### Versions
```
Angular CLI: 6.0.5
Node: 8.11.1
OS: darwin x64
Angular: 6.0.3
```

### Repro steps
ng new foo

### Observed behavior
see obove

### Desired behavior
fixed versions in default setup

**Comment by clydin** [comment]
Duplicate of #10963
