### ISSUE TITLE
Due to changes in the router, route generation has been temporarily disabled.

### ISSUE THREAD

**Issue by neerajyadav** [angular/angular-cli#1103]
Environment:

- Os: Windows 10

- angular-cli: 1.0.0-beta.6
node: 6.2.1
npm: 3.9.3
os: win32 x64

This app was created with angular-cli.
**package.json**

` "dependencies": {
    "@angular/common":  "2.0.0-rc.2",
    "@angular/compiler":  "2.0.0-rc.2",
    "@angular/core":  "2.0.0-rc.2",
    "@angular/http":  "2.0.0-rc.2",
    "@angular/platform-browser":  "2.0.0-rc.2",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.2",
    "@angular/router":  "2.0.0-rc.2",
    "@angular/router-deprecated":  "2.0.0-rc.2",
    "@angular/upgrade":  "2.0.0-rc.2",
    "angular2-universal": "^0.102.1",
    "body-parser": "^1.15.1",
    "es6-shim": "0.35.1",
    "express": "^4.13.4",
    "preboot": "^2.1.2",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "angular-cli": "1.0.0-beta.6",
    "codelyzer": "0.0.20",
    "ember-cli-inject-live-reload": "1.4.0",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "protractor": "3.3.0",
    "ts-node": "0.5.5",
    "tslint": "3.11.0",
    "typescript": "1.8.10",
    "typings": "0.8.1"
  }`

while generating new route from cli, it gives error:

> Due to changes in the router, route generation has been temporarily disabled. You can find more information about the new router here: http://victorsavkin.com/post/145672529346/angular-router

>

**Comment by alexandrearc** [comment]
Is this related? It happens while create a new app:

@angular/router@3.0.0-alpha.3 postinstall: `typings install`
spawn ENOENT
Error: @angular/router@3.0.0-alpha.3 postinstall: `typings install`
spawn ENOENT
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/npm/lib/utils/spawn.js:17:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by tagazok** [comment]
@alexandrearc it happened to me also.
I removed typings and reinstalled it : 
```
rm -rf /usr/local/bin/typings
npm install typings --global
```

**Comment by alexandrearc** [comment]
@tagazok i will give it a try. I have open a new issue for it, maybe invalid then.

**Comment by jasonswett** [comment]
I think this might be a dup of https://github.com/angular/angular-cli/issues/1093.

I'm experiencing the same issue.

**Comment by filipesilva** [comment]
Closing as dup of  #1093.
