### ISSUE TITLE
fatal: unable to auto-detect email address

### ISSUE THREAD

**Issue by ghuser** [angular/angular-cli#11040]
### Versions

Angular CLI: 6.0.5
Node: 8.11.1
OS: linux x64

### Repro steps

* `git config --global unset user.email`
* `ng new mytestapp`

### Observed behavior

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (
```
I consider that since there is a fatal error, the command has not ended successfully.
Why a generation of a new project requires that I have a globally set `user.email`? I setup this per-project, not globally.

### Desired behavior

Not to raise a fatal error, if `git` user.email has not been set globally.

**Comment by Brocco** [comment]
I am marking this as a feature, if you would like to create a project while controlling the git options, you can use the `--skip-git` option which will not create the repo.

**Comment by alan-agius4** [comment]
Closing as this is not currently in the roadmap.
