### ISSUE TITLE
Scripts not loading from angular.json file

### ISSUE THREAD

**Issue by tjpatange** [angular/angular-cli#11044]
### Versions
```
Angular CLI: 6.0.3
Node: 8.9.4
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.3
@angular-devkit/core         0.6.3
@angular-devkit/schematics   0.6.3
@schematics/angular          0.6.3
@schematics/update           0.6.3
rxjs                         6.1.0
typescript                   2.7.2
Windows 10x64
```

### Repro steps
I need to use admin-lte in my project
* Step 1: I added it via terminal using npm install admin-lte --save
* Step 2: I added jquery via terminal using following:
npm install --save jquery
npm install --save-dev @types/jquery
* Step 3: I added all the necessary .css and .js files in the angular.json file including first script reference of jquery from nod_modules

"scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/admin-lte/plugins/bootstrap/js/bootstrap.min.js",
              "node_modules/admin-lte/plugins/fastclick/fastclick.js",
              "node_modules/admin-lte/dist/js/adminlte.min.js",
              "node_modules/admin-lte/plugins/slimscroll/jquery.slimscroll.min.js",
              "node_modules/admin-lte/plugins/select2/select2.full.min.js",
              "node_modules/ion-rangeslider/js/ion.rangeSlider.min.js",
              "node_modules/alertifyjs/build/alertify.min.js",
              "node_modules/datatables.net/js/jquery.dataTables.js"
            ]

### Observed behavior
jquery and other js files are not loading

### Desired behavior
I have used a collapsable panel from the admin-lte template and it should toggle

**Comment by timbru31** [comment]
Experiencing the same issue with our external tracking JS

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by raydvard** [comment]
What happened to this issue ?

**Comment by ternyk** [comment]
I have this problem also, need a fix.

**Comment by sixteenigor** [comment]
Try move this scripts to src/assets/ folder and change all url like "src/assets/node_modules/jquery/dist/jquery.js"

**Comment by alan-agius4** [comment]
Can someone please create a minimal reproduction as explained above by @filipesilva. Thank you.

**Comment by alan-agius4** [comment]
> Repro steps
https://github.com/cactusjack66/ScriptRouteTest.git

Desired functionality
The collapse button on the top right corner of the box collapses the box on page1 after the page has been loaded. After clicking the redirect button to page2 it does not work any longer. You have to reload the page to make it work again. I have added all neccessary scripts and styles to the angular.json file.

Mention any other details that might be useful
After checking out use npm install @angular-devkit/build-angular to get it work.

From #12043 //cc @cactusjack66

**Comment by flowp98** [comment]
So with Angular we can't load any external js file when we create a routing project because after the first routing change all the scripts are "destroyed" and not loaded again ?..

**Comment by clydin** [comment]
The scripts are not destroyed.  They are still there and working.
What will not work are scripts that expect to be run against static HTML.  Single Page Applications are my definition dynamic and therefore incompatible with such a script unless the script is manually re-triggered upon change to the HTML.
Please also note that this is not Angular specific.

**Comment by dalelotts** [comment]
@filipesilva the [documentation](https://github.com/angular/angular-cli/wiki/stories-global-scripts) seems to be completely incorrect.

**Comment by patricknazar** [comment]
I'm not having the problem for `build` but for `test`. Initially karma gave me `undefined`, then I added the scripts, and that error went away. However my test code cannot access the global variables. I've tried using `files` option in karma config that doesn't help either.

**Comment by willianlima** [comment]
I having the same issue with angular2-materialize.

Temporary solution is add manual tag <script> on index.html, this worked but isn't elegant.

**Comment by machester4** [comment]
I have the same problem, but even including the <script> tag does not work. but the js files are loaded.

**Comment by hugo-marello** [comment]
I have the same problem, my angular app is not loading the scripts. I have the two scenarios on stackblitz:

(Project with angular@5.2 - working) https://stackblitz.com/edit/script-bug-5
(Project with angular@7 - NOT working) https://stackblitz.com/edit/scripts-bug-7

I was trying to add an external script to sanitize my app called 'xss'.

**Comment by vguhesan** [comment]
** Solution ** (hidden from view)

Hello All:
When you add a script or style to the angular.json file in angular@6+ (or in angular-cli.json in angular@5orEarlier), the expected results is that those js files whether they are bootstrap.min.css or jquery.min.js will get processed and combined into the new **style.js** or **scripts.js** files.

When you examine those files (**style.js** or **scripts.js**)... you will notice the derivatives of the files such as bootstrap.min.css or jquery.min.js will be in them.

![angular-support_1](https://user-images.githubusercontent.com/193960/49171918-a305f080-f30d-11e8-87a5-a08e31421fd7.jpg)

This is by design. If you examine the contents of either **style.js** or **scripts.js** and you fail to see the content block - then you need to investigate further.

Hope this helps clarify the issue. I believe this issue can be closed.

**Comment by donprecious** [comment]
what i did to reference external script was to add 
add a reference to the script in index.html 
<script src="./asset/srcipt.js"></script>

**Comment by taochenpro** [comment]
Just a reminder, you need to rebuild the project to get the scripts included.

**Comment by malithkuruwita** [comment]
if it is only working for the first time 
This answer worked for me.
Check this out

https://stackoverflow.com/a/55675403/6314955

you have to load the script inside component.ts file where you want

**Comment by Moralde-Sama** [comment]
this one works for me https://github.com/angular/angular-cli/issues/11044#issuecomment-414082628

**Comment by nhducseuit** [comment]
This issue sounds ridiculous. We've got jQuery external script working on angular 5 iirc :))

**Comment by reza3zar** [comment]
use this syntax:
"./node_modules/jquery/dist/jquery.js"
instead of 
"node_modules/jquery/dist/jquery.js"

**Comment by deser1** [comment]
Im add this and not working script. I have use materialize.js but not working any in this project. What can i do?

**Comment by edgarduran** [comment]
I found that some custom elements do not load before the app. The way I solved for it was to `npm i @webcomponents/webcomponentsjs` and `npm i document-register-element@1.8.1` (this was the only version that worked in my specific case). Make sure to `import 'document-register-element';` in your projects `pollyfills.ts`.

**Comment by mansrivas** [comment]
You can check with below command but this is not recommend ;
ng build --prod --aot=false --build-optimizer=false --base-href=\ProjectName\

**Comment by vincentw56** [comment]
So I was having this issue too. For some reason, if I did this:

```
"scripts": [
              "node_modules/jquery/dist/jquery.slim.min.js",
              "node_modules/popper.js/dist/popper.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.min.js"
            ]
```

It didn't work, but if I did this:

```
"scripts": [
              "node_modules/jquery/dist/jquery.slim.min.js",
              "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
            ]
```

It worked. I am not sure if there is an issue with popper.js or not.

**Comment by dineshkumar3795** [comment]
Pls add the below in index.html file.

<link rel="stylesheet" type="text/css" href="node_modules/bootstrap/dist/css/bootstrap.min.css" />

**Comment by vincentw56** [comment]
> Pls add the below in index.html file.

The "below" is missing.

**Comment by zbahadir** [comment]
The solution is simple: 

**Actually, that's not a problem.**

If you manually add to the angular.json file, you must build the application. Content will be included in the application.

`ionic build`

If you build the application, it will also check if the content you added is incorrect.
