### ISSUE TITLE
ng update @angular/cli hangs

### ISSUE THREAD

**Issue by choiking** [angular/angular-cli#11049]
### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.5
Node: 10.1.0
OS: darwin x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.5
@angular-devkit/core         0.6.5
@angular-devkit/schematics   0.6.5
@angular/cli                 6.0.5
@schematics/angular          0.6.5
@schematics/update           0.6.5
rxjs                         5.5.5
typescript                   2.3.4
```

### Repro steps
ng serve
"The Angular CLI configuration format has been changed, and your existing configuration can
be updated automatically by running the following command:

  ng update @angular/cli
"

ng update @angular/cli hangs

### Observed behavior
```
just hangs!
even I started with sudo
```

### Desired behavior
should run smoothly

### Mention any other details that might be useful (optional)

npm install functioned normally, I believe the network is OKAY.

**Comment by choiking** [comment]
After many try, ng update @angular/cli ends with a bug below:

Cannot find module '/Users/nanshengtu/Desktop/6150/pp2/node_modules/@schematics/update/update'
Error: Cannot find module '/Users/nanshengtu/Desktop/6150/pp2/node_modules/@schematics/update/update'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at new ExportStringRef (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular-devkit/schematics/tools/export-ref.js:15:32)
    at NodeModulesEngineHost._resolveReferenceString (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:92:21)
    at NodeModulesEngineHost.createSchematicDescription (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:167:34)
    at SchematicEngine.createSchematic (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular-devkit/schematics/src/engine/engine.js:142:38)
    at CollectionImpl.createSchematic (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular-devkit/schematics/src/engine/collection.js:12:29)
    at Object.getSchematic (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular/cli/utilities/schematics.js:36:23)
    at UpdateCommand.getOptions (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular/cli/models/schematic-command.js:194:40)
    at UpdateCommand.<anonymous> (/Users/nanshengtu/Desktop/Mean Project/contactlist/node_modules/@angular/cli/commands/update.js:39:49)

**Comment by allanbond** [comment]
Mine hangs for a few minutes then outputs the following:

`503 Service Unavailable`

Is there a verbose option? Would be nice to see what it's doing under the hood.

**Comment by MonsieurMan** [comment]
Hangs forever without any output in my case.

**Comment by codephobia** [comment]
I am getting a hang as well. Finished with a connection timeout.

ng -v
```
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.0
@angular/cli                      6.0.8
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.3.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```
ng update
`connect ETIMEDOUT 104.18.98.96:443`

**Comment by juniormayhe** [comment]
I was having this errors but now it worked here after running VSCode as administrator in Windows environment. Git bash is default terminal.

I do not know if it has something to do with permissions or an intermitent timeout.

```
Junior@MYPC MINGW64 /c/Projects/SampleApp.SPA (master)
$ ng update @angular/cli
Your global Angular CLI version (6.1.1) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Junior@MYPC MINGW64 /c/Projects/SampleApp.SPA (master)
```

**Comment by hani647** [comment]
I also experienced this issue when upgrading from Angular 5 to Angular 6. On my internet connection i.e. 2 MB/s it took half an hour but no result and then I increased my internet speed to 50 - 60 (MB/s) at this speed it took hardly 5 - 10 mins to run update command. Overall ng update is working but it seems that nothings happening so wait and let NG do its work. Hope it help you 👍

**Comment by samenz** [comment]
Just want to chime in here to say I'm getting hanging as well when I run `ng update @angular/cli@6` going from angular version `5.2.0` to `6.1.1`. Specifically I run:
```
npm install @angular/cli@6.1.1
npm update @angular/cli
```
The console hangs without displaying anything. I'm using windows 10

**Comment by samenz** [comment]
Just want to chime in here to say I'm getting hanging as well when I run `ng update @angular/cli@6` going from angular version `5.2.0` to `6.1.1`. Specifically I run:
```
npm install @angular/cli@6.1.1
npm update @angular/cli
```
The console hangs without displaying anything. I'm using windows 10

**Comment by clydin** [comment]
Numerous improvements have been made to the `ng update` command since version 6.0.  If anyone is still encountering issues with the update command on 5.x/6.x, please consider updating to a newer version via npm/yarn and then manually executing the update migrations `ng update --migrate-only --from=<original_version>`.
