### ISSUE TITLE
recompiling removes ts file content randomly.

### ISSUE THREAD

**Issue by ratidzidziguri** [angular/angular-cli#11042]
### Versions
```
Angular CLI: 6.0.3
Node: 9.1.0
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cdk                      5.0.4
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
not identified happens randomly.

### Observed behavior
from time to time, when i have file open for editing or adding new file but important thing here is that angular is running in development mode and save reloads and rebuilds app. sometimes it complains complains about file not being found. whenever I open ts file after this file content is completely empty and something removes ts file content completely.
`

### Desired behavior
file content is not removed .

### Mention any other details that might be useful (optional)
this is normal angular 6 application the only thing is i have entries in tsconfig like those.
![image](https://user-images.githubusercontent.com/22529146/40626845-459d018a-62cc-11e8-939f-cff52b0710b8.png)

checking output information gives no error or exception.

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by ratidzidziguri** [comment]
I would love to do this but as i explained there is nothing particular to do except live experience that i have there is nothing that is some logic based because it might happen randomly and i can not really hunt for this but mostly it happens i think whenever i have app running in development mode and i add new file or entry in ts and save file but again, this is very general statement the only thing i know is the reality i see every day.

**Comment by ratidzidziguri** [comment]
any update on this?

**Comment by filipesilva** [comment]
It's not something we can reproduce. I don't know of anything we do that can cause that... Have you tried in another machine? It might be something on your current setup.

**Comment by ratidzidziguri** [comment]
tried on another machine and can not reproduce there as well but fact is primary workstation does this almost every day

reinstalling Windows is not an option :) maybe there is something i can collect logs from and send it to you?

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
