### ISSUE TITLE
Running ng add turns JSON files into random number arrays

### ISSUE THREAD

**Issue by Jelledb** [angular/angular-cli#11048]
### Versions
```
Angular CLI: 6.0.1
Node: 6.11.2
OS: win32 x64
Angular: 6.0.2
```

### Repro steps
* Run ng-add (e.g. `ng add @angular/elements`)

### Observed behavior
* `package.json` & `angular.json` will be turned into a comma-separated file with a bunch of random numbers.

For example, a part of my package.json: 
`123,10,32,32,34,110,97,109,101,34,58,32,34,97,110,103,117,108,97,114,45,115,105,103,110,97,103,101,34,44,10,32,32,34,118,101,114,115,105,111,110,34,58,32,34,48,46,48,46,48,34,44,10,32,32,34, (.. goes on like this)`

### Desired behavior
Keep my package.json intact and add a package instead of messing up the file.

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
