### ISSUE TITLE
reimplement ng completion, gone in version 6

### ISSUE THREAD

**Issue by ninrod** [angular/angular-cli#11043]
continuing from #10652, reimplement `ng completion --zsh` (and the --bash counterpart) for bash and zsh users. 

version 6 just [got rid](https://github.com/angular/angular-cli/releases/tag/v6.0.0) of the completion feature simply stating in the release notes: `The completion command has been removed as the functionality no longer aligns with this version.` 

It really increases the comfort of using the ng client in the shell. We shell users highly appreciate this.

**Comment by dgp1130** [comment]
Brought this up today with the team and we definitely agree this is a great feature to have. Currently our argument/option parsing is very custom logic with a custom schema. While it could be expanded to provide autocomplete support, this would be a lot of work to implement and maintain.

There is a separate effort to refactor our argument parsing logic to use a more standardize tool, and some of them support autocompletion out of the box. We will keep this issue in mind when we get to that refactor and hopefully we will get autocompletion more or less "for free" as a part of that refactor.

**Comment by rsteube** [comment]
tinkered a bit with a [completer](https://github.com/rsteube/carapace-bin/tree/master/completers/ng_completer/cmd) for ng
[![asciicast](https://asciinema.org/a/454410.svg)](https://asciinema.org/a/454410)
