### ISSUE TITLE
Ng new app_name fails to install @angular/router@3.0.0

### ISSUE THREAD

**Issue by alexandrearc** [angular/angular-cli#1104]
1.Environment:
Mac OSX El Capitan

2. Versions.

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.6
node: 4.4.5
os: darwin x64

3. Repro steps. 

$ ng new APP_NAME

4. The log given by the failure. Normally this include a stack trace and some
   more information.

@angular/router@3.0.0-alpha.3 postinstall: `typings install`
spawn ENOENT
Error: @angular/router@3.0.0-alpha.3 postinstall: `typings install`
spawn ENOENT
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/npm/lib/utils/spawn.js:17:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by RicardoVaranda** [comment]
#1092 Duplicate entry of the same issue, problem is in typings install not router, you can manually fix it by running the following command from the project directory:

> npm run postinstall

**Comment by filipesilva** [comment]
I'm closing this one as a duplicate, but will continue addressing it in #1092.
