### ISSUE TITLE
What is the `webpack://` protocol?

### ISSUE THREAD

**Issue by npetruzzelli** [angular/angular-cli#11058]
Per Webpack's issue template:

```
<!-- Bug reports and Feature requests must use other templates, or will be closed -->
<!-- Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). -->
<!-- Issues which contain questions or support requests will be closed. -->
```
I originally tried asking this question on StackOverflow, but with no luck. Since the question will likely be deleted, I will copy the contents below:

> I downloaded and searched the [documentation repository]( https://github.com/webpack/webpack.js.org ) using my text editor for the string `webpack://`, and found it located in only two documents:
> 
> -   [src/content/configuration/index.md]( https://github.com/webpack/webpack.js.org/blob/fbd6a152d330b057f9d4fed1e0433cc60ce9c899/src/content/configuration/index.md )
>     -   which goes to: <https://webpack.js.org/configuration/>
> -   [src/content/configuration/output.md]( https://github.com/webpack/webpack.js.org/blob/fbd6a152d330b057f9d4fed1e0433cc60ce9c899/src/content/configuration/output.md )
>     -   which goes to: <https://webpack.js.org/configuration/output/>
> 
> As far as I can tell, this is not an actual protocol, much less one a browser can understand.
> 
> **Questions:**
> 
> 1. What is the `webpack:` protocol intended to be used for?
> 2. Where can I find documentation on it?
> 3. (assuming it is used internally by webpack or webpack dev server) Why do I see it output in Source Maps or in some project boiler plates, when the browser has no way of understanding what it should do with the protocol?
> 
> **Update 2018-05-25**
> 
> I checked Webpack's source code in addition to their documentation repo, and this is what I found:
> 
> -   `https://github.com/webpack/webpack/tree/v4.8.3/examples/source-map/`
> -   [`lib/EvalDevToolModuleTemplatePlugin.js`]( https://github.com/webpack/webpack/blob/v4.8.3/lib/EvalDevToolModuleTemplatePlugin.js#L15-L17 )
> -   [`lib/EvalSourceMapDevToolModuleTemplatePlugin.js`]( https://github.com/webpack/webpack/blob/v4.8.3/lib/EvalSourceMapDevToolModuleTemplatePlugin.js#L17-L19 )
> -   [`lib/SourceMapDevToolPlugin.js`]( https://github.com/webpack/webpack/blob/v4.8.3/lib/SourceMapDevToolPlugin.js#L67-L71 )
> 
> (Paths instead of links since I lack the reputation to post more than 8)

**StackOverflow Comments**

> I mean that the _structure_ of the source URL in a sourcemap is meaningless to tooling. ie, the protocol doesn't matter. – [SLaks](https://stackoverflow.com/users/34397/slaks) [May 25 at 15:17](https://stackoverflow.com/questions/50516885/what-is-the-webpack-protocol?noredirect=1#comment88076605_50516885)
> 
> ... The protocol shouldn't matter, but for some reason it does, especially when the final sourcemap includes this as a protocol. The browser has no way of understanding a `webpack://` URL. It shows up in the links above and in Angular CLI ( [github.com/angular/angular-cli/blob/1.7.x/packages/%40angular/…](https://github.com/angular/angular-cli/blob/1.7.x/packages/%40angular/cli/models/webpack-configs/browser.ts#L46-L63) ) when you eject a configuration (I'm currently on 1.7.4, they recently made the jump from 1.x to 6.x, which temporarily removes "eject"). I'd like to know why the webpack and angular teams use it. – [nick](https://stackoverflow.com/users/210548/nick) [May 25 at 16:27](https://stackoverflow.com/questions/50516885/what-is-the-webpack-protocol#comment88078774_50516885)

---

Since Angular CLI also uses/used the `webpack://` protocol, is there anyone here who might be able to explain it to me?

Thanks and regards.

**Comment by noscripter** [comment]
this is a custom protocol used in webpack source map, you can custom it by checking out this doc:  https://webpack.js.org/configuration/output/#output-devtoolmodulefilenametemplate

**Comment by vanmxpx** [comment]
how can i override devtoolModuleFilenameTemplate in angular.json? Since i cannot eject webpack config from angular project i need to rewrite this option in angular.json. This option generate many troubles while debugging in chrome or firefox.

**Comment by npetruzzelli** [comment]
@vanmxpx - Your problem doesn't seem to be related to the original topic of this issue, you may be better served opening a new issue to get the correct attention on it. You may also find the following helpful:

https://github.com/angular/angular-cli/blob/v6.0.7/docs/documentation/config.md

Though, I don't know if that applies to webpack configuration under the hood.

Since [the docs]( https://github.com/angular/angular-cli/blob/v6.0.7/docs/documentation/eject.md ) note that eject is `temporarily` disabled, I imagine they are aware of it and already have an issue open for resolution in the future.

**Comment by vanmxpx** [comment]
@npetruzzelli I have create the [issue](https://github.com/angular/angular-cli/issues/11513), but still quite. Thank you for response and for `ng config`, might be helpful.

**Comment by npetruzzelli** [comment]
You're welcome, and good luck!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
