### ISSUE TITLE
AOT Compilation makes other applications at server non-responsive

### ISSUE THREAD

**Issue by drweb86-work** [angular/angular-cli#11056]
Hello

Within AOT compilation which takes 29 mins in my project server is almost dead in that period:
- SMTP does not work,
- MySQL is not responsive

So within AOT compilations other projects located on the same server affected.

Could you please add ability to limit CPU and memory usage within AOT compilation via WebPack

Thank you.

**Comment by clydin** [comment]
Throttling an application can be handled at the OS level, there are a variety of command line utilities that can be used to allow this depending on the OS.

Also, compiling and/or building is generally not something that should be done on the actual production server used to handle client requests.  Rather the project should be deployed to the production server after being fully built and staged.

**Comment by drweb86-work** [comment]
Could you please suggest some throttling utilities? 
As i didn't find any for Windows.
