### ISSUE TITLE
ng serve --configuration=en throws error

### ISSUE THREAD

**Issue by bobKasbi** [angular/angular-cli#11059]
**### Versions**
```

Output from: `ng --version`.

Angular CLI: 6.0.3
Node: 8.11.1
OS: darwin x64 (Sierra)
Angular: 6.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.3
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.3
@angular/cli                      6.0.3
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.3
@schematics/update                0.6.3
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3
    
[](url)

**### Repro steps**
Step 1:
I did add this to my angular.json file for i18n translation - it's based on the doc [here](https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app): 

`...
"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "demo:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "demo:build:production"
            },
            "en": {
                "aot": true,
                "outputPath": "dist/en/",
                "i18nFile": "src/assets/i18n/messages.en.xlf",
                "i18nFormat": "xlf",
                "i18nLocale": "en"
            }
          }
    },
.......`

Step 2:
Run the command: `ng serve --configuration=en --port 4900`

Step 3: Run/try other command: `for lang in en de; do ng build --output-path=dist/$lang --aot --prod --i18n-file=src/assets/i18n/messages.$lang.xlf --i18n-format=xlf --locale=$lang; done`


**### Observed behavior**
When I run the command: `ng serve --configuration=en --port 4900`, I get the following error:

> Schema validation failed with the following errors:
> Data path "" should NOT have additional properties(outputPath).

When I run the following: `for lang in en de; do ng build --output-path=dist/$lang --aot --prod --i18n-file=src/assets/i18n/messages.$lang.xlf --i18n-format=xlf --locale=$lang; done`, I get the following error:

> Unknown option: '--locale'

**### Desired behavior**

What would like to see implemented?
i18n Internazionalization  for different languages - in this case EN and DE

What is the usecase?
Serving the App in specific language based on the serve command mentioned above.

What did you expect to see?
Serving the App in specific language based on the serve command mentioned above.

**Comment by chimung** [comment]
Move your "en" configuration into configuration of build command. Then referance in configuration of serve command.
` "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "Risk_Advisor:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "Risk_Advisor:build:production"
            },
            "qa": {
              "browserTarget": "Risk_Advisor:build:qa"
            }`

**Comment by mglavall** [comment]
@chimung How do you reference the configuration from the serve area?

**Comment by chimung** [comment]
in my configuration of "qa" in serve. I reference by "name-of-your-project:build:qa". It will get configuration of "qa" in build

**Comment by bobKasbi** [comment]
In this way, it would work:

`
"projects": {
    "ProjectName": {
     .....,
     "build": {
            "builder": "@angular-devkit/build-angular:browser",
            ....,
            "configurations": {
                "production": {
                    "fileReplacements": [
                        {
                            "replace": "src/environments/environment.ts",
                            "with": "src/environments/environment.prod.ts"
                        }
                    ],
                    "optimization": true,
                    "outputHashing": "all",
                    ....
                },
                "en": {
                    "aot": true,
                    "outputPath": "dist/en",
                    "i18nFile": "src/assets/i18n/messages.en.xlf",
                    "i18nFormat": "xlf",
                    "i18nLocale": "en"
                },
                ....
            }
        },
        "serve": {
            "builder": "@angular-devkit/build-angular:dev-server",
            "options": {
                "browserTarget": "ProjectName:build"
            },
            "configurations": {
                "production": {
                    "browserTarget": "ProjectName:build:production"
                },
                "en": {
                    "browserTarget": "ProjectName:build:en"
                }
            }
        },
      .....
     }
}`

**Comment by coder77** [comment]
@bobKasbi 's json in formatted

`"projects": {
  "ProjectName": {
    .....,
    "build": {
      "builder": "@angular-devkit/build-angular:browser",
      ....,
      "configurations": {
        "production": {
          "fileReplacements": [
            {
              "replace": "src/environments/environment.ts",
              "with": "src/environments/environment.prod.ts"
            }
          ],
          "optimization": true,
          "outputHashing": "all",
          ....
        },
        "en": {
          "aot": true,
          "outputPath": "dist/en",
          "i18nFile": "src/assets/i18n/messages.en.xlf",
          "i18nFormat": "xlf",
          "i18nLocale": "en"
        },
        ....
      }
    },
    "serve": {
      "builder": "@angular-devkit/build-angular:dev-server",
      "options": {
        "browserTarget": "ProjectName:build"
      },
      "configurations": {
        "production": {
          "browserTarget": "ProjectName:build:production"
        },
        "en": {
          "browserTarget": "ProjectName:build:en"
        }
      }
    },
    .....
  }
}`

**Comment by cghislai** [comment]
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/internationalization.md

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/internationalization.md should be updated with correct instructions on how to do this.
