### ISSUE TITLE
Unit test error: Router outlet is not a known element

### ISSUE THREAD

**Issue by mariadigiledge** [angular/angular-cli#11057]
i am getting following error when running a unit test using karma and jasmine

Error:
 Failed: Template parse errors:
'router-outlet' is not a known element:
1. If 'router-outlet' is an Angular component, then verify that it is part of this module.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  <a routerLink="/home">home</a>
  </nav>
  [ERROR ->]<router-outlet></router-outlet>
  "): ng:///DynamicTestModule/AppComponent.html@5:2

My app.module.ts

![screen shot 2018-05-29 at 7 27 17 pm](https://user-images.githubusercontent.com/39727684/40663525-7bc4572c-6376-11e8-8443-53a087859df4.png)

app.component.html
![screen shot 2018-05-29 at 7 27 35 pm](https://user-images.githubusercontent.com/39727684/40663699-e5434bf4-6376-11e8-8a7a-b73bc09c65fc.png)

app.component.ts
![screen shot 2018-05-29 at 7 27 29 pm](https://user-images.githubusercontent.com/39727684/40663725-f3c45d30-6376-11e8-8c4f-a30b99a37e35.png)

app.component.spec.ts
![screen shot 2018-05-29 at 7 27 56 pm](https://user-images.githubusercontent.com/39727684/40663747-02e34128-6377-11e8-992a-5bdea6812f62.png)

**Comment by BenjaminHofstetter** [comment]
Add

```typescript
import { RouterTestingModule } from '@angular/router/testing';
```

and then 

```typescript
describe('AppComponent', () => {
  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [
        RouterTestingModule
      ]
....
```

**Comment by mariadigiledge** [comment]
where should i add this code

**Comment by BenjaminHofstetter** [comment]
@mariadigiledge do you need still help?

**Comment by mariadigiledge** [comment]
Yes

**Comment by BenjaminHofstetter** [comment]
ok..
at  the top of your xxx.spec.ts file. Add import { RouterTestingModule } from '@angular/router/testing';

Then in the section 

```typescript
  TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [    //  <------ add the imports Array with the RouterTesting Module
        RouterTestingModule
      ]
```

**Comment by alan-agius4** [comment]
The `RouterTestingModule` is automatically added to `app.component.spec.ts` when you create an application with routing

**Comment by salesmask-akash** [comment]
Hello,

Here is the Quick and Simple Solution if anyone is getting the error:

" 'router-outlet' is not a known element " in angular project,

then,

Just go to the " app.module.ts " file & add the following Line:

" import { AppRoutingModule } from './app-routing.module'; "

and also ' AppRoutingModule ' in imports.

Thank you!!

**Comment by pramodjb** [comment]
> hello Every one please help me,
i'm using angular7 and ionic 4 version ,
i'm getting error
App.module.ts

> import { NgModule } from '@angular/core';
> import { BrowserModule } from '@angular/platform-browser';
> import { RouteReuseStrategy } from '@angular/router';
> import { LanguagePopoverPageModule } from './pages/language-popover/language-popover.module';
> import { IonicModule, IonicRouteStrategy } from '@ionic/angular';
> import { SplashScreen } from '@ionic-native/splash-screen/ngx';
> import { StatusBar } from '@ionic-native/status-bar/ngx';
> 
> import { AppComponent } from './app.component';
> import { AppRoutingModule } from './app-routing.module';
> import { IonicStorageModule } from '@ionic/storage';
> import { LocalStorageModule } from 'angular-2-local-storage';
> import { AuthServiceService } from './auth-service.service';
> import { HttpClientModule, HttpClient } from '@angular/common/http'; 
> import { TranslateModule, TranslateLoader} from '@ngx-translate/core';
> import { TranslateHttpLoader} from '@ngx-translate/http-loader';
> 
> 
> export function createTranslateLoader(http: HttpClient) {
>   return new TranslateHttpLoader(http, 'assets/i18n/', '.json');
> }
> 
> @NgModule({
>   declarations: [AppComponent],
>   entryComponents: [],
>   imports: [BrowserModule, HttpClientModule,
>     AppRoutingModule, 
>     IonicStorageModule.forRoot(), 
>     TranslateModule.forRoot({
>       loader: {
>         provide: TranslateLoader,
>         useFactory: (createTranslateLoader),
>         deps: [HttpClient]
>       }
>     }),
>     LanguagePopoverPageModule,
>     LocalStorageModule.forRoot()],
>   providers: [
>     StatusBar,
>     SplashScreen,
>     { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
>     AuthServiceService
>   ],
>   bootstrap: [AppComponent]
> })
> export class AppModule {}

app-routing.module.ts
import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', redirectTo: 'login', pathMatch: 'full' },
  { path: 'home', loadChildren: './home/home.module#HomePageModule' },
  { path: 'login', loadChildren: './login/login.module#LoginPageModule' },
  { path: 'language-popover', loadChildren: './pages/language-popover/language-popover.module#LanguagePopoverPageModule' },


];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {
  static forRoot: any;
}
![ionicerr](https://user-images.githubusercontent.com/13535859/61371279-04d19580-a8b2-11e9-92c6-26978e1981df.PNG)

advance thanks plz help how to clear this error,i'm stuck with this
