### ISSUE TITLE
 AddnewinvoiceComponent should create

### ISSUE THREAD

**Issue by mariadigiledge** [angular/angular-cli#11050]
Failed: Template parse errors:
'app-header' is not a known element:
1. If 'app-header' is an Angular component, then verify that it is part of this module.
2. If 'app-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<body ng-app=" ">
  [ERROR ->]<app-header></app-header>
 <app-sidemenu></app-sidemenu>
<h1>Add new Invoice</h1>
"): ng:///DynamicTestModule/AddnewinvoiceComponent.html@1:2
'app-sidemenu' is not a known element:
1. If 'app-sidemenu' is an Angular component, then verify that it is part of this module.
2. If 'app-sidemenu' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("<body ng-app=" ">
  <app-header></app-header>
 [ERROR ->]<app-sidemenu></app-sidemenu>
<h1>Add new Invoice</h1>
<hr>
"): ng:///DynamicTestModule/AddnewinvoiceComponent.html@2:1

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
