### ISSUE TITLE
ng serve with configuration ignores sourceMap

### ISSUE THREAD

**Issue by slavede** [angular/angular-cli#11061]
### Versions

Angular CLI: 6.0.5
Node: 10.1.0
OS: win32 x64
Angular: 6.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.3
@angular-devkit/build-angular     0.6.3
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.3
@angular-devkit/schematics        0.6.5
@angular/cdk                      6.1.0
@angular/cli                      6.0.5
@angular/material                 6.1.0
@ngtools/webpack                  6.0.3
@schematics/angular               0.6.5
@schematics/update                0.6.5
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

I've added configuration for build:

```
            "layer": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.layer.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "styles": [
                "src/styles.scss",
                "node_modules/layer-ui/styles.css"
              ]
            },
```

And same for serve:

```
            "layer": {
              "browserTarget": "portal-test:build:layer",
              "sourceMap": true,
              "optimization": false,
              "aot": false,
              "vendorChunk": true
            },
```

I'm running it with 

`ng serve -o --proxy-config proxy.config.js -c layer`

### Observed behavior
```
<!-- Normally this includes a stack trace and some more information. -->
```

Everything is minified/uglified

### Desired behavior

How should I run configuration layer in dev mode so I get sourceMaps generated, I've tried with --sourceMap flag as well, but it does not work, I never get source maps generated.

I'm basically not sure how can I run some configuration in dev mode

**Comment by slavede** [comment]
I believe there is still the issue. I have updated it to 6.0.7.

No maps are generated, and I can't find app.component.ts because of it.

![image](https://user-images.githubusercontent.com/2838038/40727119-7bb1aabc-6427-11e8-8fc2-3ada463b3d56.png)

**Comment by slavede** [comment]
@filipesilva Any news with this one?

**Comment by filipesilva** [comment]
@slavede no news yet, we just haven't had time to look at it yet. If you want to try and having a look yourself, I suggest editing `./node_modules/@angular-devkit/build-angular/dev-server` directly and checking what's happening to the option merging.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
