### ISSUE TITLE
Template Parse error

### ISSUE THREAD

**Issue by mariadigiledge** [angular/angular-cli#11068]
Error: 
HomeComponent should create
Failed: Template parse errors:
'app-heading' is not a known element:
1. If 'app-heading' is an Angular component, then verify that it is part of this module.
2. If 'app-heading' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<app-heading></app-heading>
gdfgdgtgh
"): ng:///DynamicTestModule/HomeComponent.html@0:0

home.component.html
![screen shot 2018-05-30 at 2 57 41 pm](https://user-images.githubusercontent.com/39727684/40711916-fcfb5c0c-6419-11e8-95dd-15f03c88487c.png)

app.module.ts
![screen shot 2018-05-30 at 2 57 52 pm](https://user-images.githubusercontent.com/39727684/40711932-08e10ce2-641a-11e8-93c7-ff3c47361cdc.png)

home.component.ts
![screen shot 2018-05-30 at 2 58 03 pm](https://user-images.githubusercontent.com/39727684/40711969-1e930fb8-641a-11e8-9034-09b55bb43207.png)

**Comment by colinbull** [comment]
I think order matters in the declarations, have you tried moving HeadingComponent above HomeComponent?

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
