### ISSUE TITLE
requested @angular-devkit/core@0.6.7 does not exist (node 8.11.2)

### ISSUE THREAD

**Issue by ghuser** [angular/angular-cli#11069]
### Versions

Angular CLI: 6.0.5
Node: 8.11.2
OS: linux x64
npm version: default (5.6.0)

### Repro steps

> Performing below action inside an empty directory

`ng new myproject`

### Observed behavior

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for `@angular-devkit/core@0.6.7`
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget 
> npm ERR! notarget It was specified as a dependency of `@angular-devkit/build-angular`
> npm ERR! notarget 

### Desired behavior

> To be able to create a new project, with a fresh installation of current node LTS

### Mention any other details that might be useful (optional)
`npm view @angular-devkit/core`
Shows versions up to `0.6.5`.

**Comment by clydin** [comment]
The version is published (see here: https://www.npmjs.com/package/@angular-devkit/core).  This may be due to the npm registry (or a configured proxy) not fully propagating or due to the npm registry issue that occurred yesterday (https://status.npmjs.org)

**Comment by ghuser** [comment]
my bad. I should have checked first. 

> FIX: I had to click on the: `invalidate-cache` button on nexus proxy instance in order to be able to perform `npm install @angular-devkit/core@0.6.7`
