### ISSUE TITLE
ng e2e --specs option fails

### ISSUE THREAD

**Issue by gawicks** [angular/angular-cli#11073]
### Versions
Angular CLI: 6.0.5
Node: 8.9.4
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular-devkit/architect         0.6.5
angular-devkit/build-angular     0.6.5
angular-devkit/build-optimizer   0.6.5
angular-devkit/core              0.6.5
angular-devkit/schematics        0.6.5
angular/cli                      6.0.5
ngtools/webpack                  6.0.5
schematics/angular               0.6.5
schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps
ng e2e --specs=foo.spec.ts

### Observed behavior
Fails with:
Schema validation failed with the following errors:
  Data path ".specs" should be array.

**Comment by ajaypbarokar** [comment]
@gawicks  ----specs option is not available with ng e2e command in angular CLI 6.
Please find below option that are available in Angular CLI 6
ng e2e -h
usage: ng e2e <project> [options]
options:
  --base-url
    Base URL for protractor to connect to.
  --configuration (-c)
    Specify the configuration to use.
  --dev-server-target
    Dev server target to run tests against.
  --element-explorer
    Start Protractor's Element Explorer for debugging.
  --host
    Host to listen on.
  --port
    The port to use to serve the application.
  --prod
    Flag to set configuration to "prod".
  --protractor-config
    The name of the Protractor configuration file.
  --suite
    Override suite in the protractor config.
  --webdriver-update
    Try to update webdriver.

**Comment by gawicks** [comment]
@ajaypbarokar Do you have any knowledge of why this was removed? Surely such a breaking change should be documented.

**Comment by gawicks** [comment]
So.. it looks like the option is still there . But it isn't documented (?) .  The validation error is because we're expecting `--specs=foo.spec.ts` to be parsed into an array. Due to the way the yargsparser is configured , it works only when passing multiple arguments. i.e.: `--specs=foo.spec.ts --specs=bar.spec.ts`

**Comment by gawicks** [comment]
A quick fix for this is to change this [line ](https://github.com/angular/angular-cli/blob/77f2dfdd7937abe22c78d600550d5a3d6adb2198/packages/%40angular/cli/models/command-runner.ts#L36)

to 

`        const rawOptions = yargsParser(args, { alias: { help: ['h'] }, boolean: ['help'], array: ['specs'] });
`

But this looks somewhat ugly to me. Anybody got a better idea?

**Comment by gawicks** [comment]
A quick fix is to change this [line ](https://github.com/angular/angular-cli/blob/77f2dfdd7937abe22c78d600550d5a3d6adb2198/packages/%40angular/cli/models/command-runner.ts#L36)

to 

`        const rawOptions = yargsParser(args, { alias: { help: ['h'] }, boolean: ['help'], array: ['specs'] });
`

But this looks somewhat ugly to me. Anybody got a better idea?

**Comment by twaraich** [comment]
yes I'm running into the same issue any solution @gawicks ? @ajaypbarokar ?

**Comment by gawicks** [comment]
@twaraich  I'm using protractor --specs . Bypassing ng e2e for the moment.

**Comment by yashjit** [comment]
@ajaypbarokar 

ng e2e --configuration --dev-server-target=dev

Unexpected end of file.
Error: Unexpected end of file.
    at _token (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/parser.js:60:19)
    at _readObject (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/parser.js:426:13)
    at _readValue (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/parser.js:564:22)
    at parseJsonAst (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/parser.js:605:17)
    at Object.parseJson (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/json/parser.js:631:12)
    at MapSubscriber._host.read.pipe.operators_1.map.str [as project] (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/workspace/workspace.js:178:154)
    at MapSubscriber._next (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:86:35)
    at MapSubscriber.Subscriber.next (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:103:18)
    at MapSubscriber._next (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/rxjs/internal/operators/map.js:92:26)
    at MapSubscriber.Subscriber.next (/projects/cff-ui-new/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:103:18)

**Comment by dabruns** [comment]
It is not a new thread here but maybe someone will help the following instructions. 

The angular 6 way is:
- Add your e2e test in the "suites" section of the protractor.conf.js. If this section not exists, add it - for example:

    suites: {
        'exampleTest': './src/example-test.e2e-spec.ts',
    }

- You can run this test with following command:
ng e2e --suite=notFound

Best regards

**Comment by jvitor83** [comment]
As @dabruns has shown (great solution anyway), i have made a sample with cucumber that use the same approach as suites, but it create the object dynamically with the function (and then the `--suite` parameter works again without having to put every suite at config):
```
// npm i --save-dev globule

function getSuites() {
  const fileSufix = ".feature";
  const globulePathsArray = require(`globule`).find([ `${process.cwd()}/e2e/src/features/**/*${fileSufix}` ]);
  const suites = { };
  globulePathsArray.forEach(pathFile => {
      const filename = require("path").basename(pathFile);
      const filenameWithoutSufix = filename.replace(fileSufix, '');
      suites[filenameWithoutSufix] = pathFile;
  });
  return suites;
}
```

More details could be seen here: https://github.com/jvitor83/angularcli-cucumber/blob/master/README.md

**Comment by nspire909** [comment]
The getSuites() function above only works on the default project.  If you have multiple projects in your workspace, replace the globulePathsArray declaration with:
```
const globulePathsArray = require(`globule`).find([ require('path').join(__dirname, `./src/**/*${fileSufix}`) ]);
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
