### ISSUE TITLE
How to specify creds for custom npm repository during ng update

### ISSUE THREAD

**Issue by j--wong** [angular/angular-cli#11081]
Hi,

I am trying to update our project from version 5.2.9 to 6 using `ng update`.  We use an internal NPM registry where we publish internal modules.

I am able to specify registry URL using `ng update --registry <internal npm registry>` .  However, I can't find an option to set credentials required to authenticate with our internal repo.

`npm` commands work fine as I have setup creds in `npmrc`  but `ng update` does not seem to use the npm config.

Is there a way to set credentials for `ng update` command to work with custom repo which requires authentication?

Thanks,
Josh

**Comment by j--wong** [comment]
Hi @filipesilva, any update on this? 

Any pointers on workaround or how we can help resolve the issue would be greatly appreciated.

Thanks,
Josh

**Comment by filipesilva** [comment]
@hansl @clydin can you have a look please?

**Comment by clydin** [comment]
Support for reading `.npmrc` is available in the latest version of the CLI (7.3.5).  If problems are still encountered, please open a new issue detailing the current environment and version information.
