### ISSUE TITLE
The ng commands do not respect tslint semicolon setting (i.e. stop adding them) 

### ISSUE THREAD

**Issue by mockuniverse** [angular/angular-cli#11099]
### Versions
```
ngular CLI: 6.0.7
Node: 8.11.2
OS: darwin x64
Angular: 6.0.3

```

### Repro steps
ng generate a component

### Observed behavior
```
Components, directives, etc., are littered with (useless) semicolons despite our lint settings. 
```

### Desired behavior
Generate artifacts without semicolons (i.e. remove wholly unnecessary clutter) based on lint settings.

**Comment by alan-agius4** [comment]
Generate commands have the option to run the ts lint fixers, you can do so by either using `--lintFix` via the command line or specifying the option in the `angular.json`

```js
"schematics": {
  "@schematics/angular:component": {
    "lintFix": true
  }
},
```

**Comment by panKt** [comment]
@alan-agius4 unfortunately solution with `@schematics/angular:component` in `angular.json` does not work anymore. Is it still possible to use config to make `angular-cli` run linter for every item generated?
