### ISSUE TITLE
feature request / configuration ability to default dry run and explicitly commit to generate.

### ISSUE THREAD

**Issue by kjr247** [angular/angular-cli#11090]
This is a feature request. I love the CLI, but the affects can cause more headache if you don't know how to use it properly (ex. generating all kinds of things I didn't mean to or not generating things I actually wanted, now I have to go clean up the mess and try again). 

While learning or teaching others, I would love to be able to default dry run in a configuration and then have to explicitly commit the changes to really generate.

This would make adoption and conversion easier for new comers from other technologies.

**Comment by kyliau** [comment]
Closing this, since there is a known solution as suggested by @clydin.
