### ISSUE TITLE
[ng6] `ng serve`; `ng build -prod` fails on `ng g library` dependent project

### ISSUE THREAD

**Issue by SamuelMarks** [angular/angular-cli#11097]
### Versions
```
Angular CLI: 6.0.7
Node: 8.11.2
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cdk                      6.2.0
@angular/cli                      6.0.7
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.2.0
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* `ng new angular-vertical-tabs && cd $_`
* `ng add @angular/material; npm i --save @angular/flex-layout==6.0.0-beta.15`
* `ng g library material-tabs -p vertical`
* `ng build material-tabs --prod`
* Add `dist` to git, then import in other Angular 6 project

https://github.com/SamuelMarks/angular-vertical-material-tabs

### Observed behavior
Works fine on `ng serve`. On `ng build --prod` I get:
```
ERROR in ./node_modules/angular-vertical-tabs/dist/material-tabs/material-tabs.ngfactory.js
Module not found: Error: Can't resolve 'material-tabs' in 'my-new-repo/node_modules/angular-vertical-tabs/dist/material-tabs'
ERROR in ./src/app/slash/slash.module.ngfactory.js
Module not found: Error: Can't resolve 'material-tabs' in 'my-new-repo/src/app/slash'
ERROR in ./src/app/slash/slash.component.ngfactory.js
Module not found: Error: Can't resolve 'material-tabs' in 'my-new-repo/src/app/slash'
```

### Desired behavior
`ng build --prod` should work.

### Mention any other details that might be useful (optional)
My previous hack solution was to `--aot false`.

**Comment by rtm** [comment]
My error (and versions of everything) is nearly identical:

```
ERROR in ./node_modules/@nims/red-shared/lib/components/display-item-artifacts/display-item-artifacts.component.ngfactory.js
Module not found: Error: Can't resolve '../../../node_modules/@nims/ngutils/lib/editable-markdown/editable-markdown.component.ngfactory' in '/home/rtm/repos/nims/red/app/node_modules/@nims/red-shared/lib/components/display-item-artifacts'
```

`@nims/red-shared` is a library with a component called `display-item-artifacts` which is bringing in components such as `editable-markdown` from another library called `ngutils`. 

This was compiling fine before the upgrade to 6.0.0 etc., although I probably also changed some other things in the meantime.

**Comment by rtm** [comment]
Related? https://github.com/dherges/ng-packagr/issues/913

**Comment by Chan4077** [comment]
For me, it seems that removing the `rootDir` property of `tsconfig.app.json` solved the issue.

See this commit for more info: https://github.com/Chan4077/ngx-ytd-api/commit/5b1970cb090fc097e6bf748981d5c650958155ad

**Comment by aissamJ** [comment]
Dear all, 

We fixed the issue on our side by making the following changes:
-  removing   "baseUrl": "./"   from src/tsconfig.app.json file
- adding "paths" to  tsconfig.json file

**Comment by olilutz** [comment]
Hi,

I fixed the issue with the **package.json** name attribute in my lib. I wanted to use the library  like this:
```
folder-structure:
| - node_modules
    | - @mylib
        | -  components
        | -  etc

Import Statement in e.g. app.module.ts:
import { ExampleModule } from '@mylib/components';
```
The problem was that by generating ```ng g library mylib-components``` the **package.json** was named ```"name": "mylib-components"``` due to the library-structure
```
| - projects
    | - mylib-components
        | - src
```
Then it couldn't generate the **mylib-component.ngfactory.js** because it couldn't resolve the path as shown in the folder-structure ```@mylib/components```. To solve the problem I changed the name in the **package.json** file to ```"name": "@mylib/components"```. And in the generated **metadata.json file** the ```"importAs: @mylib/components"``` is now correct instead of ```"importAs: mylib-components"```.
Now the production build works with the library.

Hope it helps.

**Comment by alan-agius4** [comment]
Indeed it is paramount to set the name inside the package.json to the actual library name that will eventually be imported by the consumers as the name set in the package.json will be used as a flatModuleId for ngc.

**Comment by liiyannjiee** [comment]
Hi,
We fixed the issue on our side by making the following changes:

- removing "paths": "./" from src/tsconfig.app.json file
- edit "paths" to tsconfig.json file 
` "baseUrl": "src/",
 "agc": [
        "../dist/agc"
      ],
"paths": {
      ...
      "agc/*": [
        "../dist/agc/*"
      ]
}`

**Comment by SamuelMarks** [comment]
Got it working, Previously, I was uploading my `repo-name/dist` in my `org/repo-name` repository. Library was called `lib0`.

In `org/repo-name2` angular project, I included in my `package.json`: `{"repo-name": "org/repo-name"}`. Compiled fine on `ng build`; `ng build --prod` proved the problem.

Pushing the `dist` directory to its own repository `org/lib0`; removing the previous from my `package.json`; then adding: `{"lib0": "org/lib0"}`; proved to be the solution.

Now `ng build --prod` works; and the rendered static files give no unexpected errors.

**Comment by jslaff117** [comment]
@olilutz that is the solution I ended on! Thanks for the help!

**Comment by saranyatpillai** [comment]
import { Injectable } from '@angular/core';
import { Http, Response} from '@angular/http';
import 'rxjs/Rx';

@Injectable({
  providedIn: 'root'
})
export class ProfileService {

  constructor( private http:Http) { }

  saveprofile(){
    let url="https://reqres.in/api/users";
    return this.http.post(url, {name:'Saranya', city:'Adoor'})
    .map((res:Response)=>res.json());

  }
}


I used the above code but it showing the error-Module not found: Error: Can't resolve 'rxjs/Rx/add/operator/map'. How can I solve it.

**Comment by alan-agius4** [comment]
You need to import rxjs differently.

https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

**Comment by saranyatpillai** [comment]
Thank you.

**Comment by sheikalthaf** [comment]
Hi,

Still I'm facing this issue in one of my library. [@ngu/carousel](https://www.npmjs.com/package/@ngu/carousel/v/1.4.9-beta-3) beta version.
Don't know how to solve this issue

Git repo [here](https://github.com/sheikalthaf/ngu-carousel)

**Comment by gmerabishvili** [comment]
@sheikalthaf Could you tell me how did you solve that issue? I'm facing exactly same issue on my library @angular-ng-autocomplete . Here is my repo: https://github.com/gmerabishvili/angular-ng-autocomplete.
