### ISSUE TITLE
HMR story is pointing wrong configuration

### ISSUE THREAD

**Issue by carlos-algms** [angular/angular-cli#11093]
Currently it saying that we should put the configuration withing "**server**" section:

```json
"serve": {
  "configuration": {
    "hmr": {
      "hmr": true,
      "fileReplacements": [
        {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.hmr.ts"
        }
      ]
    }
  }
}
```
But it is not allowed, due to schema validation:

![image](https://user-images.githubusercontent.com/4634613/40866399-d34842b0-65d3-11e8-916c-cfbbe2f72178.png)

And it is breaking with a not so friendly error, because the "path" is empty:
(actually it should be a bug, because every wrong key, breaks with an empty path error)

```shell
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(fileReplacements).
```

## The correct location should be within "**build**" section:

![image](https://user-images.githubusercontent.com/4634613/40866452-17c84192-65d4-11e8-8cb2-547f9b50369e.png)

## And under **server** section only: 

```json
"serve": {
  "configurations": {
      "hmr": {
          "hmr": true
      }
  }
}
```

Angular version: 6.0.3
Angular CLI version: 6.0.3

**Comment by robertbaker** [comment]
Please submit a PR and sign the CLA.

**Comment by robert-claypool** [comment]
See also #11121

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/11029
