### ISSUE TITLE
Lint - Unable to specify a tslint configuration file per tsconfig project

### ISSUE THREAD

**Issue by felpel** [angular/angular-cli#11098]
x-post from original [issue](https://github.com/angular/angular/issues/24275) in `angular/angular` repository

### Versions
```
Angular CLI: 6.0.7
Node: 8.11.1
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cli                      6.0.7
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

* Create new project for Angular 6 with `ng new`;
* Create two separate `tslint` configurations for production/test code (`tslint.json` and `tslint.test.json`);
* Extend `tslint.json` in `tslint.test.json` and overwrite some rules as `no-unsafe-any : false`;
* Run `ng lint`;
* Check if any warnings appears.

### Observed behavior

In Angular 2/4/5, we were able to associate a `tslint` configuration to a specific TypeScript project's configuration. As for now, `ng` only offers a single `tslint` configuration for all the projects with `--tslint-config`. 

### Desired behavior

As I mentioned in the previous issue, with the Angular-CLI configuration file (`.angular-cli.json`), we were able to achieve with the following way: 

```json
    "lint": [
                {
                         "project": "src/tsconfig.app.json",
			"tslintConfig": "tslint.json",
		},
		{
			"project": "src/tsconfig.spec.json",
			"tslintConfig": "tslint.test.json", // Specific linting configuration for specs
		}
      ]
```

It was very useful since we were able to disable specific rules for our spec files like this:

```json
{
    "extends": "./tslint.json",
    "rules": {
        "max-classes-per-file": false,
        "no-empty": false,
        "no-floating-promises": false,
        "no-magic-numbers": false,
	"no-unsafe-any": false,
	"rxjs-finnish": false
    }
}
```

**We want our rules to be stricter for the production code compared to the tests one.**

**Comment by Ennas** [comment]
To get around this, I created 2 new projects in angular.json 
```
"lint-app": {
  "root": "",
  "sourceRoot": "src",
  "projectType": "application",
  "architect": {
    "lint": {
      "builder": "@angular-devkit/build-angular:tslint",
      "options": {
        "tsConfig": [
          "src/tsconfig.app.json"
        ],
        "tslintConfig": "tslint.json",
        "exclude": [
          "**/node_modules/**",
          "**/*.spec.ts"
        ]
      }
    }
  }
},
"lint-test": {
  "root": "",
  "sourceRoot": "src",
  "projectType": "application",
  "architect": {
    "lint": {
      "builder": "@angular-devkit/build-angular:tslint",
      "options": {
        "tsConfig": [
          "src/tsconfig.spec.json"
        ],
        "tslintConfig": "tslint.spec.json",
        "exclude": [
          "**/node_modules/**"
        ]
      }
    }
  }
}
```
Now running ng lint should run each configuration separately. I removed "lint" option from my existing projects as it seemed redundant after doing this.

**Comment by filipesilva** [comment]
You should also be able to just add a `lint-app` and `lint-test` target inside your main app, but then you'll have to run them all separate via `ng run my-app:lint-app`, etc.

**Comment by TheeRFG** [comment]
I know that this issue is incredibly old, but could you elaborate more on how I would properly set up two separate targets with different tslintConfig files?

**Comment by filipesilva** [comment]
@TheeRFG in your `angular.json` file you can find the `tslint` target under the `architect` key:
```
{
  // ...
  "projects": {
    "my-app": {
      // ...
      "architect": {
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
```

You can add a tslint file here via the `tslintConfig` key:
```
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tslintConfig": "tslint.custom.json",
```

You can also make another target, that uses a different tslint config
```
        "lint": { ... },
        "another-lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tslintConfig": "tslint.another.json",
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
```

To run the newly created one, you can do `ng run my-app:another-lint`.

**Comment by TheeRFG** [comment]
Nice! I didn't even think to try such a thing!

So yesterday while waiting, I managed to get the original proposed solution in place and have out `tslint.app.json` and out `tslint.test.json` running in two separate projects defined in `angular.json`. For the most part things are fine, but I've noticed that the output is not as nice as it was before the update.

The output ends up looking like this
```
ng lint


All files pass linting.


All files pass linting.
```
Which is fine when things pass, but incredibly misleading when the first one errors and the second one still says "_All_ files pass linting"

So if you actually have errors you end up with something like
```
ng lint

/src/somefile/whatever/bla.ts [147,21] some linting errors
/src/somefile/whatever/bla.ts [149,11] some linting errors
/src/somefile/whatever/bla.ts [153,46] some linting errors

**All files pass linting.**
```
I know why this happens, but this does not seem right.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
