### ISSUE TITLE
Update of non-beta angular CLI version 

### ISSUE THREAD

**Issue by Hardiki** [angular/angular-cli#11091]
There is no mention or description of how to update the non-beta version of angular CLI.

**Comment by jared-christensen** [comment]
Does this help?
https://update.angular.io/

**Comment by Hardiki** [comment]
@jared-christensen This is not what I exactly want. I want to update the CLI, not the project.

**Comment by mgol** [comment]
@Hardiki The https://update.angular.io/ page specifies how to update CLI as well. Set it to say how to update from version 5.2 to 6 and look for "Update your Angular CLI globally and locally, and..."

**Comment by filipesilva** [comment]
Closing as answered by @jared-christensen and @mgol, thank you!
