### ISSUE TITLE
'ng g component' sometimes updates app.module but sometimes not

### ISSUE THREAD

**Issue by fenyiwudian** [angular/angular-cli#11094]
### Versions
```
$ node -v
v8.9.1

$ ng -v
Angular CLI: 1.6.5
Node: 8.9.1
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.5.3
webpack: 3.10.0
```

### Repro steps

* Step 1
    + new a project in command line   => OK
    ```
        ng new my-ng-app
    ```
* Step 2
    + go to project    => OK
   ```
      cd my-ng-app
   ```
* Step 3
    + try to create some componets    => not OK
 ```
    $ ng g component first-cmp
    create src/app/first-cmp/first-cmp.component.html (28 bytes)
    create src/app/first-cmp/first-cmp.component.spec.ts (643 bytes)
    create src/app/first-cmp/first-cmp.component.ts (280 bytes)
    create src/app/first-cmp/first-cmp.component.css (0 bytes)
    update src/app/app.module.ts (408 bytes)  // updated

   $ ng g component layout/main-layout
      create src/app/layout/main-layout/main-layout.component.html (30 bytes)
      create src/app/layout/main-layout/main-layout.component.spec.ts (657 bytes)
      create src/app/layout/main-layout/main-layout.component.ts (288 bytes)
      create src/app/layout/main-layout/main-layout.component.css (0 bytes)
      update src/app/app.module.ts (515 bytes)  // updated

    $ ng g component ui/button
      create src/app/ui/button/button.component.html (25 bytes)
      create src/app/ui/button/button.component.spec.ts (628 bytes)
      create src/app/ui/button/button.component.ts (269 bytes)
      create src/app/ui/button/button.component.css (0 bytes)
      update src/app/app.module.ts (600 bytes)     // updated

    $ ng g component ui/input
      create src/app/ui/input/input.component.html (24 bytes)
      create src/app/ui/input/input.component.spec.ts (621 bytes)
      create src/app/ui/input/input.component.ts (265 bytes)
      create src/app/ui/input/input.component.css (0 bytes)
      update src/app/app.module.ts (681 bytes)     // updated

    $ ng g component component/input
      create src/app/component/input/input.component.html (24 bytes)
      create src/app/component/input/input.component.spec.ts (621 bytes)
      create src/app/component/input/input.component.ts (265 bytes)
      create src/app/component/input/input.component.css (0 bytes)
      // not updated

    $ ng g component feature/input
      create src/app/feature/input/input.component.html (24 bytes)
      create src/app/feature/input/input.component.spec.ts (621 bytes)
      create src/app/feature/input/input.component.ts (265 bytes)
      create src/app/feature/input/input.component.css (0 bytes)
     // not updated

    $ ng g component features/input
      create src/app/features/input/input.component.html (24 bytes)
      create src/app/features/input/input.component.spec.ts (621 bytes)
      create src/app/features/input/input.component.ts (265 bytes)
      create src/app/features/input/input.component.css (0 bytes)
       // not updated

    $ ng g component ui/text
      create src/app/ui/text/text.component.html (23 bytes)
      create src/app/ui/text/text.component.spec.ts (614 bytes)
      create src/app/ui/text/text.component.ts (261 bytes)
      create src/app/ui/text/text.component.css (0 bytes)
      update src/app/app.module.ts (758 bytes)   // updated

    $ ng g component some/text
      create src/app/some/text/text.component.html (23 bytes)
      create src/app/some/text/text.component.spec.ts (614 bytes)
      create src/app/some/text/text.component.ts (261 bytes)
      create src/app/some/text/text.component.css (0 bytes)
      // not updated
```

### Observed behavior

+ As you can see in step 3, sometimes app.module.ts file got updated but sometimes not.

### Desired behavior
+  Always update app.module.ts

### Mention any other details that might be useful (optional)
+ No special

**Comment by jnizet** [comment]
I can reproduce this, with the latest version of the CLI (6.0.7 at this time).

My guess is that some components are not added to the module simply because they have the same name as already added components.
To add a second component also named "input", the CLI would have to use aliased imports:
```
import { InputComponent as InputComponent1 } from './component/input.component';
[...]
     declarations: [
        ...,
        InputComponent1
     ]
```

But even then, you would also have to tweak the selector of these components to avoid a name clash, and the selector you would choose would probably be different from the name (InputComponent1 in the above example) that the CLI would choose.
So I wonder if
 - using two components with the same name in the same module is a good idea in the first place
 - forcing you to choose an alias and a selector for a component that has the same name as an already existing one is not the best solution after all.

**Comment by Brocco** [comment]
@jnizet is correct that having 2 components with the same name in the same module is not a great idea. That being said, adding a message about this is something the team will consider adding.

**Comment by moisesh18** [comment]
Hi. I have the same issue, and I don't have any component with shared names. Any solve for this? 
![image](https://user-images.githubusercontent.com/31388995/74800117-1e97e880-5298-11ea-873d-98e6c899ba6d.png)
![image](https://user-images.githubusercontent.com/31388995/74800135-29527d80-5298-11ea-9ea5-7877dac82107.png)
ionic -v 6.1.0
ng -v 8.3.25

**Comment by ljayz** [comment]
im having the same issue as @moisesh18 

Angular CLI: 9.1.6
Node: 10.16.3
OS: win32 x64

**Comment by SchnWalter** [comment]
The example from this issue is producing 3 different `InputComponent` classes, all of them having the same selectors. You can rename them importing in the `app.module.ts`, but you can't fix the selector conflict, they all have the same `app-input` selector. The directory is not taken into account when creating a new component. If you really want 3 different input components, you need to give them different names.

This works as intended. I think that this issue should be closed.

**Comment by fenyiwudian** [comment]
I end up with using different component names,such as:
```shell
ng g component ui/ui-input
ng g component feature/feature-input
ng g compoinent xxxx/yyyy/zzzz/xxxx-yyyy-zzzz-input
```
generating component files like `xxxx-yyyy-zzzz-input.component.ts` component names like `XxxxYyyyZzzzInputComponent` to avoid it.

It's just that they have very long filenames and component names. And the component file name carries the meaning that the directory level can already indicate. 

however it works, Try to get used to it.

close this issue.

**Comment by SchnWalter** [comment]
You could also use:
```
ng g component ui/input/ui-input --flat
CREATE src/app/ui/input/ui-input.component.css (0 bytes)
CREATE src/app/ui/input/ui-input.component.html (23 bytes)
CREATE src/app/ui/input/ui-input.component.spec.ts (636 bytes)
CREATE src/app/ui/input/ui-input.component.ts (282 bytes)
UPDATE src/app/app.module.ts (846 bytes)
```
This way, your directory will have a shorter name.
