### ISSUE TITLE
Unexpected token / in JSON at position 762

### ISSUE THREAD

**Issue by viswanathamsantosh** [angular/angular-cli#11103]
### Versions
```

Angular CLI: 6.0.7
Node: 8.9.4
OS: linux x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cli                      6.0.7
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              5.5.11
typescript                        2.5.3
webpack                           4.8.3

```

### Repro steps
* Step 1 give command `ng g service data` to generate a service

### Observed behavior
```
Unexpected token / in JSON at position 762

```

### Desired behavior
A new service should be created in the designated folder

### Mention any other details that might be useful (optional)
Was working fine with before angular cli 1.7.x. Updated my cli and I'm completely struck now. couldnt even find any articles to go back from 6.x to 1.7.x

**Comment by ashgibson** [comment]
I am having the same issue on v6.0.7 but slightly different 

`Unexpected token ] in JSON at position 1389`

I have tried adding --verbose but am not getting any further information.

**Comment by ashgibson** [comment]
See https://github.com/angular/angular-cli/issues/10880. Your angular.json is probably not valid json.

**Comment by viswanathamsantosh** [comment]
my angular.json looks fine. just linted with jsonlint.
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "pwc": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles.css"
            ],
            "scripts": [
              "src/assets/js/appkit.min.js",
              "src/assets/js/vendor.min.js",
              "src/assets/js/appmain.js"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "pwc:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "pwc:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "pwc:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [
              "src/assets/js/appkit.min.js",
              "src/assets/js/vendor.min.js",
              "src/assets/js/appmain.js"
            ],
            "styles": [
              "src/styles.css"
            ],
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "pwc-e2e": {
      "root": "",
      "sourceRoot": "",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "pwc:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "pwc",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "styleext": "css"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}`

**Comment by viswanathamsantosh** [comment]
I'm not sure what happened but an `npm update` fixed it! I was able to generate my pipe with cli.

**Comment by filipesilva** [comment]
I'm not too sure what happened here either, but happy to hear it's not a problem anymore.
