### ISSUE TITLE
problem using angular-cli in hybrid app (angular.js + angular 5)

### ISSUE THREAD

**Issue by emilgadzaev** [angular/angular-cli#11104]
Hi,
My team and I want to use angular-cli in our project,
Our client app is hybrid app (angular.js with angular 5)
We encounter several problems.
So first of all before trying to find solution...is at all possible to use angular-cli in hybrid app?
If so...where can we find guide to the correct integration?

**Comment by synapze** [comment]
There are several guides out there to upgrade your app with ngUpgrade but a good resource we used was https://blog.nrwl.io/using-nrwl-nx-to-upgrade-you-angularjs-applications-to-angular-f5b8adf188aa

**Comment by filipesilva** [comment]
It is possible but the build system in Angular CLI is focused on building Angular applications only. If you want to use a hybrid application and it needs to be built, you will need to do it beforehand. I hope that helps.
