### ISSUE TITLE
Build with --watch flag does not work with a lib project

### ISSUE THREAD

**Issue by zbarbuto** [angular/angular-cli#11100]
### Versions
```
Angular CLI: 6.0.7
Node: 9.6.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.5
@angular-devkit/build-angular      0.6.5
@angular-devkit/build-ng-packagr   0.6.5
@angular-devkit/build-optimizer    0.6.5
@angular-devkit/core               0.6.5
@angular-devkit/schematics         0.6.5
@angular/cdk                       6.1.0
@angular/cli                       6.0.7
@angular/material                  6.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.5
@schematics/angular                0.6.5
@schematics/update                 0.6.7
ng-packagr                         3.0.0
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
```

### Observed behavior

Running `ng build --watch` works perfectly fine on the default app in a monorepo with the default app. 

However, running `ng build mylib --watch` or `ng build --watch mylib` after generating a lib with the CLI gives `Unknown option: '--watch'`

### Desired behavior

Can build any of the apps or libs in an Angular cli monorepo in --watch mode.

### Mention any other details that might be useful (optional)

Have tried various combinations of ordering the arguments as well as `--watch=true` and `-w`. None seem to work.

**Comment by elclanrs** [comment]
This is not supported yet. I'm eagerly awaiting for [this PR](https://github.com/dherges/ng-packagr/pull/884) to be merged in ng-packagr.

**Comment by gabrielalan** [comment]
So they launch a new CLI breaking one of the commands? 😂

**Comment by jrista** [comment]
Any idea on when this might be available? We are doing a lot of work with libs at the moment, no ability to watch is really rough...

**Comment by alan-agius4** [comment]
This should become available with Angular-CLI v6.2

**Comment by bezysoftware** [comment]
I installed the latest 6.2.0 beta.0, but am still unable to do `ng build --watch` for a library ("unknown switch"). Here's outcome of `ng --version`:

```
Angular CLI: 6.2.0-beta.0
Node: 8.11.3
OS: win32 x64
Angular: 6.1.0
... common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.2
@angular-devkit/build-angular      0.7.2
@angular-devkit/build-ng-packagr   0.7.2
@angular-devkit/build-optimizer    0.7.2
@angular-devkit/build-webpack      0.7.2
@angular-devkit/core               0.7.2
@angular-devkit/schematics         0.8.0-beta.0 (cli-only)
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.2
@schematics/angular                0.8.0-beta.0 (cli-only)
@schematics/update                 0.8.0-beta.0 (cli-only)
ng-packagr                         4.0.1
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.9.2
```

Whats should I do?

**Comment by alan-agius4** [comment]
@bezysoftware you need to update all `@angular-devkit/<packages>` to `0.8.0-beta.0`

**Comment by bezysoftware** [comment]
Thanks, that worked. Now first time compilation works, but the diff compilation fails:

```
File change detected. Starting incremental compilation...

BUILD ERROR
no elements in sequence
EmptyError: no elements in sequence
    at new EmptyError (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\util\EmptyError.js:16:28)
    at C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\operators\last.js:11:294
    at Object.complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\operators\throwIfEmpty.js:12:23)
    at TapSubscriber._complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\operators\tap.js:76:31)
    at TapSubscriber.Subscriber.complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\Subscriber.js:76:18)
    at TakeLastSubscriber._complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\operators\takeLast.js:71:21)
    at TakeLastSubscriber.Subscriber.complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\Subscriber.js:76:18)
    at MergeMapSubscriber._complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\operators\mergeMap.js:80:30)
    at MergeMapSubscriber.Subscriber.complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\Subscriber.js:76:18)
    at FilterSubscriber.Subscriber._complete (C:\Users\**\projects\Nexus\WidgetMessaging\node_modules\rxjs\internal\Subscriber.js:94:26)


Compilation failed. Watching for file changes...
```

I guess tha'ts worth a separate issue

**Comment by alan-agius4** [comment]
That is a known error, if you are trying to change a file that is not part
of the compilation.

https://github.com/dherges/ng-packagr/pull/1029

**Comment by xino1010** [comment]
Hi @bezysoftware  @alan-agius4 !
How can I install the latest 6.2.0 beta.{0,1}?
Thanks

**Comment by xino1010** [comment]
Hi @bezysoftware @alan-agius4 !
How can I install the latest 6.2.0 beta.{0,1}?
Thanks

**Comment by GeorgeKnap** [comment]
Watch mode works for these versions :)
`@angular-devkit` at `0.8.0-rc.0` 
`@angular` at `6.1.4`
`ng-packagr` at `4.1.0`

sweet!

**Comment by KoBe321** [comment]
It's working for me with:
```
@angular-devkit/build-angular": "^0.8.1
@angular-devkit/build-ng-packagr": "^0.8.1
@angular/cli": "^6.2.1
ng-packagr": "^4.1.1
```

However, if I make any changes in the lib, it reloads the page twice.

**Comment by arm1n** [comment]
Although it's working for `--watch` now, it seems that no one of the other flags are working though, f.e. `--output-path` or `--delete-output-path` when using with a library. Im using Angular CLI 6.2.2. Can anyone else confirm this?

**Comment by drizzt74** [comment]
@arm1n I can confirm it for Angular CLI 7.0.4. Althought I didn't extensively check, it seems the only working flags are those reported by the ng build --help command, not those described in documentation page: https://angular.io/cli/build
