### ISSUE TITLE
CSS assets with same name are overwritten

### ISSUE THREAD

**Issue by TomVanWemmel** [angular/angular-cli#11117]
### Versions
```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.7
Node: 9.5.0
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.7
@angular-devkit/build-angular     0.6.7
@angular-devkit/build-optimizer   0.6.7
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.7
@angular/cli                      6.0.7
@ngtools/webpack                  6.0.7
@schematics/angular               0.6.7
@schematics/update                0.6.7
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
* `ng new my-project`
* `cd my-project`
* `npm install flag-icon-css`
* add "node_modules/flag-icon-css/css/flag-icon.min.css" to _styles_ in angular.json
* `ng build`
* `ls dist/my-project`
* `ng build --output-hashing=all`
* `ls dist/my-project`

### Observed behavior

The flag-icon-css package defines a stylesheet with links to svg files. There are two svg files (squared and rectangular flag) for each supported country, both have the same name but are located in a different folder.
For a build without arguments, a list of svg files is shown, _only one_ for each country supported by the css file. 
With `--output-hashing` all svg files are shown. 

### Desired behavior
`ng build` should copy all files to the _dist_ folder.

**Comment by alan-agius4** [comment]
Relates to #12186
