### ISSUE TITLE
Angular 5 Prod Build fails with AOT for relative paths

### ISSUE THREAD

**Issue by tdmitchal** [angular/angular-cli#11119]
"dependencies": {
    "@agm/core": "1.0.0-beta.3",
    "@angular/animations": "^5.2.11",
    "@angular/common": "^5.2.11",
    "@angular/compiler": "^5.2.11",
    "@angular/core": "^5.2.11",
    "@angular/forms": "^5.2.11",
    "@angular/http": "^5.2.11",
    "@angular/platform-browser": "^5.2.11",
    "@angular/platform-browser-dynamic": "^5.2.11",
    "@angular/router": "^5.2.11",
    "@compodoc/compodoc": "^1.1.3",
    "@ng-bootstrap/ng-bootstrap": "^1.1.2",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^2.0.1",
    "@swimlane/ngx-charts": "^7.4.0",
    "@swimlane/ngx-datatable": "^12.0.0",
    "angular-calendar": "^0.24.1",
    "angular-plotly.js": "^0.1.13",
    "angular-split": "^1.0.0-rc.3",
    "angular-tree-component": "^6.1.0",
    "angular2-text-mask": "^9.0.0",
    "bootstrap": "^4.1.1",
    "cesium": "^1.46.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.6",
    "d3": "^5.4.0",
    "d3-collection": "^1.0.4",
    "d3-ng2-service": "^2.2.0",
    "date-fns": "^1.29.0",
    "dragula": "3.7.2",
    "intl": "^1.2.5",
    "ng-sidebar": "7.2.0",
    "ng2-dragula": "1.5.0",
    "ng2-file-upload": "1.3.0",
    "ng2-toasty": "^4.0.3",
    "ng2-validation": "4.2.0",
    "ngx-logger": "^2.2.4",
    "ngx-toastr": "^8.7.3",
    "npm": "^5.10.0",
    "plotly.js": "^1.38.2",
    "quill": "1.3.6",
    "resize-observer-polyfill": "^1.5.0",
    "rxjs": "5.6.0-forward-compat.5",
    "satellite.js": "^2.0.2",
    "screenfull": "^3.3.2",
    "spinthatshit": "^1.0.4",
    "text-mask-addons": "^3.7.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.21"
  },
  "devDependencies": {
    "@angular/cli": "1.7.4",
    "@angular/compiler-cli": "^5.2.11",
    "@angular/language-service": "^5.2.11",
    "@types/d3": "^5.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.109",
    "@types/node": "~6.0.112",
    "angular-ide": "^0.9.41",
    "codelyzer": "^4.3.0",
    "jasmine-core": "~3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "protractor": "~5.3.2",
    "ts-node": "~6.1.0",
    "tslint": "~5.10.0",
    "typescript": "~2.5.3"
  }

* ng build - Everything works fine
* ng build --prod --aot --progress --verbose --base-href=/SPACEOPS/ --app SPACEOPS      This fails to resolve relative paths
* ng build --prod --aot=false --progress --verbose --base-href=/SPACEOPS/ --app SPACEOPS     This works fine

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided
