### ISSUE TITLE
Running any variation of "ng update" triggers this error : "connect ETIMEDOUT 104.18.97.96:443"

### ISSUE THREAD

**Issue by brianjly** [angular/angular-cli#11110]
### Versions

Angular CLI: 6.0.7
Node: 8.9.4
OS: win32 x64
Angular: 6.0.3

### Repro steps
Started the process of upgrading from 5.2 to 6.  Followed all the steps up until the part about updating angular CLI.  Ran the following commands to update cli, which worked fine:

```
npm install -g @angular/cli
npm install @angular/cli
```

### Observed behavior

However, when running:
```
ng update @angular/cli
```

I get this error: 

```
connect ETIMEDOUT 104.18.97.96:443
```
### Desired behavior
My angular-cli.json file is not converted to angular.json.  Tried using different variations of ng update.  Tried installing cli again using yarn.  Made sure there is no corporate proxy set up and that there is no npmrc file.  

Any temporary workaround ?

**Comment by therawk** [comment]
I have the same problem. Started happening when I added FontAwesome Pro packages to my project 👎

**Comment by Sioxas** [comment]
I got the same error.

**Comment by geisslercom** [comment]
Are you having a coperate proxy?

**Comment by fschell** [comment]
same problem, no proxy, npm runs correctly, also FontAwesome Pro installed

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
