### ISSUE TITLE
[Question] CPU and IO throttling utilities for Windows for AOT build

### ISSUE THREAD

**Issue by drweb86-work** [angular/angular-cli#11112]
Hello

Could you please suggest some CPU and IO throttling utilities for Windows?
Google doesn't bring result.

It would be a pity to setup additional server just to make AOT compilation to not affect other projects (SMTP, MySQL fails with timeouts upon compilation).

Thanks.

**Comment by filipesilva** [comment]
I don't quite follow what issue you are reporting. Can you add a bit more detail please? What you're seeing, how it affects you, etc.

**Comment by drweb86-work** [comment]
Hello

I reported recently an issue that upon AOT build on dev server other applications gets non-responsive. DEV server is shared across huge number of applications. Also we do compilation in prod servers on them own.

AOT build takes 30 minutes. During this time MySQL fails with SSL Timeout Exceptions, SMTP fails with SSL errors too. Remote desktop is almost unresponsive.

That's a pity that additional server is needed for AOT compilation. Because it will take more money to develop, e.g. for each dev application to rent a VM.

For example in .Net world compilation does not make entire server unresponsive.

Issue was closed and I was told to find some throttling tools for windows for IO and CPU usage. But there're none of them, isn't it? 

So there's a question. How to live with AOT compilation without renting additional servers for its compilation.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by drweb86-work** [comment]
Hello

 

Actually I found a reason of an issue – its UglifyJsPlugin with enabled parallel.

So issue is not actual for me

 

Thanks
