### ISSUE TITLE
Documentation style guide and cli support for .md file creation

### ISSUE THREAD

**Issue by ganeshkbhat** [angular/angular-cli#11126]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Versions
Angular CLI: 6.0.0
Node: 9.11.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@ angular-devkit/architect    0.6.0
@ angular-devkit/core         0.6.0
@ angular-devkit/schematics   0.6.0
@ schematics/angular          0.6.0
@ schematics/update           0.6.0
rxjs                         6.1.0
typescript                   2.7.2

### Repro steps
NA

### The log given by the failure
NA

### Desired functionality

What would like to see implemented?
Can we have a documentation format/style guide like jsdoc or a javadoc for angular code and style guide for cli to create .md (P1) or .rst (P2) or HTML (P3) files based on priority mentioned or as suggested by community? This is definitely a low priority task and good to have. If anyone is willing to take this up as a separate community project, I will be willing to pitch in with help.

What is the usecase?
Documentation creation for opensource or projects. 

### Mention any other details that might be useful
NA

**Comment by alan-agius4** [comment]
Thanks for this feature request. However this is currently not in the Angular CLI roadmap.

Let's re-visit this in future.
