### ISSUE TITLE
Angular 6 imports throwing errors for spec but not for regular app serving

### ISSUE THREAD

**Issue by seekheart** [angular/angular-cli#11122]
### Versions
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.0
Node: 9.3.0
OS: linux x64
Angular: 6.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps

* setup angular project with `ng new <project name> --style=scss` and add `stylePreprocessorOptions` to angular json with path to common scss sheet (see below).
* setup a directory for common scss sheets (variables, mixins, colors, etc) under `src/styles`
* in a component `@import 'colors'` for example as common sheet
* run ng test
* test bombs out for a component saying cannot `@import 'colors'`

### Observed behavior
```
ERROR in ./src/app/user/user-detail/user-detail.component.scss
Module build failed: 
@import "variables";
^
      File to import not found or unreadable: variables.
      in /home/mike/workspace/coder-directory-ui/src/app/user/user-detail/user-detail.component.scss (line 2, column 1)
 @ ./src/app/user/user-detail/user-detail.component.ts 30:21-60
 @ ./src/app/user/user-detail/user-detail.component.spec.ts
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
```

### Desired behavior

I would like the test to pass or at least for there to be documentation as to why my component's scss import works for `ng serve` but fails at `ng test`.

### Mention any other details that might be useful (optional)
You can clone this project of mine to reproduce located [here](https://github.com/seekheart/coder-directory-ui/tree/users).

**Comment by seekheart** [comment]
@robertbaker They are partials that I be importing though

**Comment by seekheart** [comment]
I managed to find the fix, it appears completely unrelated to sass partials.
The issue was after I had upgraded this project from angular 5 to 6, karma became corrupted some how and thus could not run properly.

To fix this I had to remove my `package-lock.json` and `node_modules` folder and rerun `npm install` to get everything to work again.

**Comment by robertbaker** [comment]
@seekheart I understand that, but there will be multiple copies of the shared stuff unless you remove the imports and import them with angular.json. This was covered somewhere in the CLI docs.
