### ISSUE TITLE
Angular 4 Assets not copying when creating build using Jenkins

### ISSUE THREAD

**Issue by ihd2911** [angular/angular-cli#11123]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report
- [ ] feature request
```

### Versions

Windows 10
Node: 8.11.2
Angular cli in project: 1.7.3 
Angular cli global: 6.0.3

### Repro steps
I am creating build of angular 4 project using Jenkins and then publishing build on ftp.

Following is command that i am running

`npm install && npm run dev`

I have created dev as following in package.json.

`"dev": "ng build"`

When jenkins build run, build is created and uploaded on the ftp. All the content is uploaded on the ftp except the content which is in angular-cli.json assets

```
"assets": [
    "assets",
    "favicon.ico",
    ".htaccess"
  ],
```
Assets, favicon and htaccess files are not getting uploaded on the ftp.

I went on to check jenkins workspace folder for my project

`C:\Program Files (x86)\Jenkins\workspace\projectname`

and did not found assets in this folder.
Looking forward on help ASAP.

Thanks

**Comment by ihd2911** [comment]
Figured it out.
Issue was with folder name (Program Files (x86)), Installed jenkins to another directory and it worked

**Comment by mViniciusMarques** [comment]
> 
> 
> Figured it out.
> Issue was with folder name (Program Files (x86)), Installed jenkins to another directory and it worked

Seriously ? Is that the right way to solve the problem ?  
I can't change the installation path in my case, It's looks a poor solution btw !

**Comment by sunt89** [comment]
@mViniciusMarques  you can change the workspace of your jenkins task, Make sure there are no Spaces in the workspace path
