### ISSUE TITLE
ERROR [karma]: RangeError: Invalid string length

### ISSUE THREAD

**Issue by brianpilati** [angular/angular-cli#11134]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x ] devkit
- [ ] schematics
```

### Versions
node --version
v8.9.4

npm --version
5.6.0

 ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.7
Node: 8.9.4
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.7
@angular/cdk                       6.2.1
@angular/cli                       6.0.7
@angular/material                  6.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.7
@schematics/update                 0.6.7
ng-packagr                         2.4.5
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3

### Repro steps
ng test --watch=true

### The log given by the failure
06 06 2018 11:34:13.315:ERROR [karma]: RangeError: Invalid string length
    at Socket.ProcessLauncher._onStderr <path_removed>/node_modules/karma/lib/launchers/process.js:59:31)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

### Desired functionality
In previous versions, `ng test --watch` would run continually. Now in Angular-cli 6, it works for maybe 2 test runs and fails with this error. 

### Mention any other details that might be useful
I have also tried using --poll without any success.

**Comment by filipesilva** [comment]
Heya, I tried to reproduce this by triggering some 30 rebuilds in `ng test` (watch mode) and couldn't see this error. 

Do you have a repro up that I can look at?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
