### ISSUE TITLE
`ng build` and `ng serve` do nothing and print no output

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#11133]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
```
Angular CLI: 6.0.8
Node: 8.9.4
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@angular/cli                 6.0.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.0
typescript                   2.7.2
```

### Repro steps

I can't share the repo, but if you point me at a log file location, I can share logs.

### The log given by the failure

No printed output.

### Desired functionality

The command should either succeed, or should print an error message.

**Comment by fr0** [comment]
I noticed that `webpack` wasn't in my `node_modules` folder, which led me to discover that `@angular-devkit/build-angular` wasn't in my `package.json` -- I had to migrate from Angular 5 to Angular 6 by hand because I had trouble with the automated tools, which explains that.

Sorry for the extraneous issue. If you want, you _might_  consider adding an error message for this case, instead of printing nothing. Or you can close the issue with no action required, up to you.

**Comment by filipesilva** [comment]
Yeah we should definitely print something in this case.

**Comment by kkocel** [comment]
I think I've been hit by this issue as well. https://stackoverflow.com/questions/46269681/gitlab-ci-failing-with-angular-cli

**Comment by KhizerRehan** [comment]
@fr0 which version of angular-devkit/build-angular is required for angular-devkit/build-angular is required?

Current Cli version:
![screenshot_1](https://user-images.githubusercontent.com/17727069/41200042-bb9b36ec-6cb6-11e8-8408-8ba765428bba.png)

Thanks!

**Comment by jpvanhal** [comment]
I had the same problem. I did some debugging and noticed that this exception was swallowed:

```
Error: Could not find module "@angular-devkit/build-angular" from "...".
    at Object.resolve (.../node_modules/@angular-devkit/core/node/resolve.js:141:11)
    at Observable.rxjs_1.Observable [as _subscribe] (.../node_modules/@angular-devkit/architect/src/architect.js:137:42)
    at Observable.subscribe (.../node_modules/rxjs/internal/Observable.js:162:69)
    at DoOperator.call (.../node_modules/rxjs/internal/operators/tap.js:71:23)
    at Observable.subscribe (.../node_modules/rxjs/internal/Observable.js:159:22)
    at .../node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (.../node_modules/rxjs/internal/util/subscribeToResult.js:7:45)
    at MergeMapSubscriber._innerSub (.../node_modules/rxjs/internal/operators/mergeMap.js:132:38)
    at MergeMapSubscriber._tryNext (.../node_modules/rxjs/internal/operators/mergeMap.js:129:14)
    at MergeMapSubscriber._next (.../node_modules/rxjs/internal/operators/mergeMap.js:112:18)
```

So the solution was to install `@angular-devkit/build-angular`.

**Comment by stephaneeybert** [comment]
I had forgotten to run a `npm install` after a `git clone`.

Now I can run a `ng serve` all right.

**Comment by alan-agius4** [comment]
Using Angular CLI 7 as a global, and running `ng serve` on a project that doesn't have `node_modules` it now bubbles up the error that was previously swallowed.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
