### ISSUE TITLE
The generated file name should prefix.component.ts prefix.component.css prefix.component.html when creating project with prefix parameter

### ISSUE THREAD

**Issue by santoshugale** [angular/angular-cli#11151]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
Angular CLI: 1.7.3
Node: 9.8.0
OS: win32 x64

### Repro steps
ng new AppWithPrefix --prefix awp
This generates an app.component.ts, app.component.html, app.component.css.

### Desired functionality
Should generate files with provided prefix like awp.component.ts, awp.component.html, awp.component.css.

### Mention any other details that might be useful
As prefix is used in component selector, is should be used file file naming also.

**Comment by clydin** [comment]
The prefix option’s only purpose is to prefix the html selectors within the project and intentionally has no relation to file names.
