### ISSUE TITLE
GitHub Release listings contain invalid links to referenced commits

### ISSUE THREAD

**Issue by psylum** [angular/angular-cli#11155]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
angular-cli version 6.1.0-beta2

### Repro steps

1. Visit Github page for [@angular/cli](https://github.com/angular/angular-cli/).
1. Click on "releases" link.
1. Find the 6.1.0-beta2 release.
1. Click on an image in the _Commit_ column in a table, which has a hash and commit type.

### The log given by the failure
GitHub shows a 404 error. The URL linked to is `https://github.com/angular/devkit/commit/_HASH_`

### Desired functionality
GitHub shows the commit page for the referenced commit. The links should be to `https://github.com/angular/angular-cli/commit/_HASH_`

### Mention any other details that might be useful
These image/commit links appear to be new, previous usages of just text-based links relied on GitHub auto-linkifying them to this repository.

**Comment by hansl** [comment]
Fixed now, thanks!
