### ISSUE TITLE
@angular-devkit/build-optimizer@0.6.8 depends on typescript 2.9.1 (was 2.7.2 in 0.6.7)

### ISSUE THREAD

**Issue by dominikg** [angular/angular-cli#11150]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Repro steps
```
update @angular/cli  in existing project from 6.0.7 to 6.0.8
notice the additional dependency on typescript 2.9.1 in yarn.lock 
```

### Desired functionality
stick with main typescript version of angular

**Comment by clydin** [comment]
That change was intentional.  The build optimizer’s use of typescript is independent of the rest of the system.  2.9.1 brought an important bug fix for the build optimizer’s use case.
