### ISSUE TITLE
No error reported when using buildOptimizer with aot set to false

### ISSUE THREAD

**Issue by zackporter92** [angular/angular-cli#11157]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

node --version is v10.1.0
npm --version is 5.6.0

### Repro steps

I ran ng new testtheprob
I entered the repo.
run ng build --prod --aot=false and notice that no dist folder is created
I then tried modifying the angular.json so that the prod build had aot:false
I ran ng build --prod and no dist folder was created

### The log given by the failure

Nothing is printed to the console.  The command just stops without building a dist folder.  Also I tried running --verbose=true to see if that added details but it did not

### Desired functionality
I need to be able to do a prod build without aot.  Neither editing the angular.json file nor using the command line args works.  

We have multiple servers that we are testing our code on, our app is so big that running an aot build takes several minutes, this won't work for us on some of our servers that we are deploying to many times per day.  In angular 5 we were able to turn off aot, but are no longer able too with angular 6.

**Comment by filipesilva** [comment]
I think we're swallowing an error somewhere. Using the `buildOptimizer` option (which is in the prod default) without AOT should show an error. But it doesn't seem to be showing it.

You should be able to use `ng build --prod --aot=false --build-optimizer=false` as a workaround for now, but we should fix this to show the proper error.

**Comment by Greentea1204** [comment]
Hi filipesilva , wondering what's the difference between the two commands:
ng build --prod --aot=false --build-optimizer=false
ng build --prod --aot=true --build-optimizer=true

the package that 'ng build --prod --aot=false --build-optimizer=false' created is still considered as an AOT build?  what's the difference between ato=true and ato=false? As my understanding is they both create a main********.js file.

Thanks

**Comment by raviurlams** [comment]
its working for me with **ng b --prod --aot=false --build-optimizer=true**

**Comment by danielpcampagna** [comment]
@raviurlams Could you share your versions? (`ng version`)
