### ISSUE TITLE
how to use --proxy-config in ng e2e modal? 

### ISSUE THREAD

**Issue by 100cm** [angular/angular-cli#11165]
i want to set the proxy in e2e modal? any idea?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by 100cm** [comment]
@filipesilva  i have solved this problem now , angular-cli e2e  load the  default server config.
