### ISSUE TITLE
PR: Update for wiki story page

### ISSUE THREAD

**Issue by fmalcher** [angular/angular-cli#11169]
Since GitHub can't handle PRs to the wiki section, here's an issue.
I updated the "GitHub Pages story" page:

https://github.com/fmalcher/angular-cli-wiki/commit/ac102c5c3b5d937d758f41a1abda5594efddb3a8

* Added specific command for `angular-cli-ghpages`
* Changes repo url since we moved the repo to another org

Thanks for reviewing and merging this 🚀

**Comment by filipesilva** [comment]
Heya, you can make a PR to change our wiki by changing the files in this folder: https://github.com/angular/angular-cli/tree/master/docs/documentation

**Comment by fmalcher** [comment]
Oooh good, I didn't know this! 😎
Then let's close this for now, I will start a PR then.
