### ISSUE TITLE
ng update @angular/core

### ISSUE THREAD

**Issue by liuwu1211** [angular/angular-cli#11162]
### Bug Report or Feature Request (mark with an `x`)
```
 Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.4").
 Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=5.0.0-rc.0 <6.0.0||>=2.3.1 <3.0.0||>=4.0.0-beta <5.0.0", would install "6.0.4").
Incompatible peer dependencies found. See above.
```

- What should I do

### Versions
```
node -v
v8.11.1

npm -v
5.6.0
```

**Comment by filipesilva** [comment]
You should update the version of `codelyzer` manually. That error says that the version of codelyzer you currently have doesn't support `@angular/core@6.0.4`, so the update stops. We don't update your packages if that would cause errors with other packages.
