### ISSUE TITLE
feat request: minify PNG, JPEG, GIF, SVG and WEBP images with imagemin

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#11166]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```
### Desired functionality
Support image-webpack-loader to minify PNG, JPEG, GIF, SVG and WEBP images with imagemin
I want to be able to use png,jpg assets and have webp ones generated and used if supported.
I have svg assets that I want to be optimized in prod.

### Mention any other details that might be useful
https://github.com/tcoopman/image-webpack-loader

**Comment by mackelito** [comment]
Any change for this to make it into the cli?

**Comment by alan-agius4** [comment]
Closing as per comment in https://github.com/angular/angular-cli/issues/18547#issuecomment-677860061
