### ISSUE TITLE
How will the, now closed/moved, angular/devkit repo's issues be tracked

### ISSUE THREAD

**Issue by CharlBest** [angular/angular-cli#11171]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Desired functionality

Create/move/copy all the issues in the Angular CLI project repo?
Maybe I'm missing something and it is somewhere. Sorry if that is the case.

### Mention any other details that might be useful

Specifically I don't want to lose the conversations on issue https://github.com/angular/devkit/issues/729 about SEO :)

**Comment by filipesilva** [comment]
We'll be moving the existing issues to this repo actually. We can't move the comments but will link back to the original issue.

**Comment by CharlBest** [comment]
Ok cool thanks. It's good to know.

**Comment by CharlBest** [comment]
@filipesilva I haven't seen this (https://github.com/angular/devkit/issues/729) issue migrated over to this repo. Do you want me to create one or are you guys still in the process of moving things over? I don't want the issue to get lost although I don't think many people are interested in it unfortunately.

**Comment by filipesilva** [comment]
They haven't been moved yet but @alexeagle is working on it.

**Comment by CharlBest** [comment]
Ok thanks for the update.

**Comment by filipesilva** [comment]
Moved now as https://github.com/angular/angular-cli/issues/12120

**Comment by CharlBest** [comment]
Thanks @filipesilva I'm glad :)
