### ISSUE TITLE
Browser detection in compiler

### ISSUE THREAD

**Issue by jonahbron** [angular/angular-cli#11172]
A NPM module my application has been using ([grpc-web-client](https://github.com/improbable-eng/grpc-web/tree/master/ts)) has been broken by the disabling of Node stdlib shims in Angular 6.  This is reasonable, and I'm working on a PR for the library.  However, the method I thought would be obvious (check for window object, conditionally `require()` the stdlib modules) was thwarted by the Angular compiler.

It seems that the code is being executed by the compiler within Node.  This of course breaks my browser detection, and it tries to import those absent modules.

I'm sure there are many other packages out there that can handle this properly, but I haven't found any information on how this can be done in a way that is generic _and_ supports Angular.

**Comment by jonahbron** [comment]
Here's the solution I've come up with for now.

https://github.com/improbable-eng/grpc-web/pull/203/files

Basically I'm aliasing `require` so that I can prevent Webpack from knowing the exact file I'm trying to load.  This results in a `WARNING Critical dependency: the request of a dependency is an expression` error, but at least it's not fatal, so my application works now.

This feels very much like a hack, and I'm very interested in learning a better approach.

**Comment by filipesilva** [comment]
Heya, a quick look at your PR (https://github.com/improbable-eng/grpc-web/pull/203/files) makes me think there might not be a better way than what you are doing. 

Bundlers in general will look for require/import calls and try to resolve them. You PR intentionally tries to break that detection.

I'm not aware of any great solution to conditionally use node modules without telling bundlers to include them. Doing that will surely also break bundling for the case where you want to actually want them to be bundled. One common approach is to provide different bundles for different platforms.

**Comment by jonahbron** [comment]
@filipesilva Thanks for the response.  The ability to do something _like_ this in the future would be nice, and the empty module shims from pre-Angular 5 provided a nice way to do that.  I hope you all figure out a good solution at some point.  I also came up with an alternate fix in which Node is removed from the transport auto-detection, and must be explicitly imported by the application if desired.  This seems like the more idiomatic approach for now.

https://github.com/improbable-eng/grpc-web/pull/204
