### ISSUE TITLE
@angular/cli 6.X How to use Autoprefixer?

### ISSUE THREAD

**Issue by whevether** [angular/angular-cli#11188]
"Browserslist": [
	   "> 1%",
    "Last 2 versions" ], no effect in @angular/cli 6.X

**Comment by dominikg** [comment]
cannot repoduce this with

Angular CLI: 6.0.8
Node: 8.11.2
OS: darwin x64
Angular: 6.0.4
autoprefixer: 8.6.2

this config doesn't add flexbox fallback syntax
```
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 Firefox versions",
    "last 2 ie versions",
    "last 2 Edge versions",
    "last 2 Safari versions",
    "last 2 iOS versions",
    "last 2 android versions",
    "last 2 ie_mob versions",
    "not ie < 11",
    "not ie_mob < 11",
    "not iOS < 11",
    "not Safari < 11",
    "not android < 61"
  ]
```

this config does:
```
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 Firefox versions",
    "last 2 ie versions",
    "last 2 Edge versions",
    "last 2 Safari versions",
    "last 2 iOS versions",
    "last 2 android versions",
    "last 2 ie_mob versions"
  ]
```

**Comment by ux-powered** [comment]
Same here. The repro steps:

1. Upgrage to latest @angular/cli
```
npm uninstall -g @angular/cli
npm cache verify
npm install -g @angular/cli@latest
```
2. Create new project
`ng new my-app-ng --style=scss`
3. Add the next code to my-app-ng/src/styles.scss
```scss
img {
  display: flex;
}
```
4. Add the next code to my-app-ng/src/app/app.component.scss
```scss
img {
  display: flex;
}
```
5. Add browserslist config to my-app-ng/package.json
```json
{
  "name": "my-app-ng",
  ...
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "ie >= 10"
  ]
}
```
6. Run server and visit localhost:4200
```
cd my-app-ng
ng serve
```

The result:
![screen shot 2018-06-13 at 17 29 20](https://user-images.githubusercontent.com/39078782/41336791-99287be8-6f30-11e8-8681-4895a9a4d711.png)

----
Environment:

- Mac OS X 10.13
- Node v8.11.0
- NPM v5.6.0

**Comment by dominikg** [comment]
angular cli v6 adds a file 'browserslist' to src with the following content

```
# This file is currently used by autoprefixer to adjust CSS to support the below specified browsers
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries
# For IE 9-11 support, please uncomment the last line of the file and adjust as needed
> 0.5%
last 2 versions
Firefox ESR
not dead
# IE 9-11
```
if the list of sources for browserslist queries ( https://github.com/browserslist/browserslist#queries ) is ordered by precedence or angular cli explicitly calls autoprefixer with this config file, your query might not be used.
 
I checked it in an upgraded project that does not contain a separate browserslist file and it works as expected.

**Comment by clydin** [comment]
Closing as answered by @dominikg (thank you).

Also note that the standard browserslist order is honored.  If desired, the default `browserslist` file can be deleted if a different method of configuration is preferred.

**Comment by BBlackwo** [comment]
I had an issue where I had two `browserslist` files: one in `/` and one in `src/`. So the one in `/src` was taking precedence. Not sure why Angular CLI v6 puts it in `src/`...
