### ISSUE TITLE
Create a angular project for specified version, Through any version of the angular-cli tool

### ISSUE THREAD

**Issue by qq1209974887** [angular/angular-cli#11182]
I‘m using angular-cli@6.0.3, but the version number of angular of our company must be 4.x.x. I want to create a angular@4.x.x project demo using "ng new demo" without changing the version of angular-cli. I don't know what I should do.

**Comment by filipesilva** [comment]
We don't provide a way to generate projects for older versions of Angular through Angular CLI 6. You can change to use older dependencies manually though. 

But I should warn you that Angular CLI 6.x was made to work in Angular 5 and 6. We don't test it with Angular 4.
