### ISSUE TITLE
Please update ng2 blueprint to RC2

### ISSUE THREAD

**Issue by billfranklin** [angular/angular-cli#1119]
Current version only utilizes Angular2 RC1.  Please update to RC2 with current required dependencies and RC2 router.

**Comment by MrCroft** [comment]
Agree about all @angular dependencies, except one: the router... As of now, v3 is the new "new router" :) which is pretty different and we should be using it (especially if you have the luxury of not having to go to production very soon).
Anyway, I'm sure we'll have rc2 with the next CLI release. This time I think the beta.6 version of the CLI was released just a couple of hours before rc2 was released (?)

**Comment by filipesilva** [comment]
RC2 is in for the next version in https://github.com/angular/angular-cli/pull/1096.

Currently we are waiting for a new version of the router that fixes https://github.com/angular/angular-cli/issues/1092 before we can cut a new version.

**Comment by filipesilva** [comment]
Mind you, it's perfectly reasonable to manually update the dependencies to rc.2, everything should work.
