### ISSUE TITLE
Non production Angular Cli Libraries should emit ts files in order to debug them.

### ISSUE THREAD

**Issue by gerardcarbo** [angular/angular-cli#11194]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
Angular Cli 6.0.7
Node v10.2.1
Npm v5.6
Windows 10

### Repro steps
Create a Angular Cli project, add a library to the project and some code on the main project to test the library. Compile the library in non production mode -> ng build 'lib-name'. Serve the project -> ng serve. If you try to debug the project with developer tools, the main project has the .ts files, but the library only has the transpiled .js files.

### Desired functionality
The generated debug library should had the ts files exported to be able debug using them, but only has the transpiled js code and .map's.

**Comment by filipesilva** [comment]
The source map files should give you the necessary mappings to debug. Outputting typescript files from libraries is an anti-pattern because it forces the consumers to use the same typescript version as the library did itself. You can try to find ways around this problem on your setup but we prefer to default to best practices.

**Comment by gerardcarbo** [comment]
Sorry, possibly I have not expressed myself well, using the default provided cli configuration, the .maps are generated for the lib, but not loaded into the chrome debugger. Only the .js bundle is loaded:

![image](https://user-images.githubusercontent.com/9449644/41226339-74aaa72a-6d71-11e8-8b65-05afec3b0221.png)

Maybe I am missing something?

**Comment by filipesilva** [comment]
We don't usually load vendor sourcemaps by default, but you can do it with the `--vendorSourceMap` option.

See https://github.com/angular/devkit/pull/767 for the PR that added this functionality.
