### ISSUE TITLE
ng update @angular/cli caused error "unexpected token function"

### ISSUE THREAD

**Issue by Bushan11** [angular/angular-cli#11198]
### Bug Report or Feature Request (mark with an `x`)
```
- [ `x`] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```

### Versions
`node --version`  = v6.11.3
`npm --version` =  3.10.10

Angular CLI: 6.0.8
Node: 6.11.3
OS: win32 x64
Angular: 4.4.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, tsc-wrapped

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@angular/cli                 6.0.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         5.5.11
typescript                   2.3.4

### Repro steps
I was trying to generate the service in my project created today with name JWTLogin.

ng g s security/security 

it gives me error "cannot read property 'nulllogger' of undefined "
to solve this i updated the project with latest cli.

npm install --save @angular/cli@latest

after this when i entered below command 

ng update @angular/cli

causes the below error in console window
![error](https://user-images.githubusercontent.com/31878643/41230150-538dc29a-6d9c-11e8-85c8-3048ce468159.PNG)

**Comment by leon99adolfo** [comment]
I have the same problem.

**Comment by neb1neuron** [comment]
Same here

**Comment by kumaro** [comment]
upgrading to node8 fixed it for me. Details about actual error would definitely be helpful.

Luckily i found update guide (https://update.angular.io/) which says we have to update to Node8 or later before running ng update

**Comment by hansl** [comment]
We only support Node 8.9 and above in the CLI 6.

Ref. https://github.com/angular/angular-cli/blob/master/package.json#L44
