### ISSUE TITLE
Error message when angular.json is invalid is not very descriptive

### ISSUE THREAD

**Issue by rafidka** [angular/angular-cli#11204]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report
- [x] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
Output of `ng --version`:

```
Angular CLI: 6.0.8
Node: 9.8.0
OS: darwin x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
1. Create a new project: `ng new test-angular`
2. Edit `angular.json` and add some invalid input, for example add a comment to the first line.
3. Use the CLI to add a new module `ng generate module New`

### The log given by the failure
Unexpected token / in JSON at position 0

### Desired functionality
1. The message should be a little bit more descriptive. It is currently a bit difficult to understand the problem, and for new comers, it might seem there is a problem with the package instead of `angular.json`. Here are some issues which shows other users also had confusion about this:

https://github.com/angular/angular-cli/issues/10843
https://github.com/angular/angular-cli/issues/10938
https://github.com/angular/angular-cli/issues/11103

2. Replace absolute position with line and line position. It doesn't help much if I get position 1277 and have to find out which line this is.

**Example**: Found an unexpected token / in `angular.json` in line 123 character 45.

This is much more descriptive and clearly tells the user that there is a problem in his/her `angular.json` file and the line where the error is found.

**Comment by rafidka** [comment]
Also, I just noticed https://github.com/angular/angular-cli/issues/5610 which seems to have been addressed, which suggests comment should be allowed and the CLI should not complain about `/` characters in `angular.json`. Or am I missing something?

**Comment by sam-s4s** [comment]
This is very frustrating...

```
Invalid JSON character: "﻿" at 0:0.
Error: Invalid JSON character: "﻿" at 0:0.
```

Ummm... which file?

If I look at the error through a different text output, it reads:
```
Invalid JSON character: "ï»¿" at 0:0.
Error: Invalid JSON character: "ï»¿" at 0:0.
```

So I'm gonna have to open all the json files with a hex editor I guess... :/
