### ISSUE TITLE
[Suggestion] Using ts version of lib files during development

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#11209]
With `angular-cli@6` we can finally use `libraries`.

Generating new library cli adds `paths` to `tsconfig`. Those paths points to `dist` version of specific library.
It is very confusing during development - with every change You have to build library :/

How about pointing to `projects` folder instead of `dist`?

```json
      "testing": [
        // "dist/testing"
        "projects/testing/src"
      ],
```

You have to add to lib's `src` folder `index.ts` file with content: `export * from './public_api';`
With that we could have better development experience.
Are there some drawbacks of such solution? If not can You implement it in cli?

**Comment by filipesilva** [comment]
There's a section in the wiki for library creation that answers this question: https://github.com/angular/angular-cli/wiki/stories-create-library#why-do-i-need-to-build-the-library-everytime-i-make-changes
