### ISSUE TITLE
error “implement me” when running `ng --help` command

### ISSUE THREAD

**Issue by hanijizan** [angular/angular-cli#1120]
I'm using `angular-cli` beta.6 on windows using Visual Studio. It runs `ng.cmd` under the `node_modules/.bin` and it throws the following error as a result of "ng --help":

    internal/process/stdio.js:86
            throw new Error('Implement me. Unknown stdin file type!');
            ^
    Error: Implement me. Unknown stdin file type!
        at process.stdin (internal/process/stdio.js:86:15)
        at C:\apptest\myapp\node_modules\angular-cli\bin\ng:33:27
        at C:\apptest\myapp\node_modules\angular-cli\node_modules\resolve\lib\async.js:44:21
        at ondir (C:\apptest\myapp\node_modules\angular-cli\node_modules\resolve\lib\async.js:187:31)
        at C:\apptest\myapp\node_modules\angular-cli\node_modules\resolve\lib\async.js:153:39
        at onex (C:\apptest\myapp\node_modules\angular-cli\node_modules\resolve\lib\async.js:93:22)
        at C:\apptest\myapp\node_modules\angular-cli\node_modules\resolve\lib\async.js:24:18
        at FSReqWrap.oncomplete (fs.js:117:15)

Ok, so it seems to me something is not implemented yet? it's already in beta.6 so i assume there has to be something else going on?

**Comment by nosachamos** [comment]
@hanijizan the command is `ng help` or `ng -h`

I suppose this could be closed.

**Comment by hanijizan** [comment]
Still the same error for `ng help`.

**Comment by filipesilva** [comment]
Does that happen when not using visual studio as well?

**Comment by hanijizan** [comment]
Visual studio runs it using nodejs engine (version 6) and since i have other scripting tasks such as gulp and systemjs builder, then i'm confident that my environment is right. Just hoping to replace systemjs builder with cli to get smaller and more efficient bundles, if i could get around the error.

**Comment by filipesilva** [comment]
I'm sorry but there just isn't much I can do about running CLI commands from inside Visual Studio. Since they run outside of VS, I have to assume there's some issue with how VS handles them.

Perhaps try bringing it up with the VS team?

**Comment by ceottaki** [comment]
I know the issue has been closed already but it is not a VS issue, it is an issue of NodeJS in Windows when using process.stdin from a GUI where Windows does not provide an stdin.

I've opened another [issue](https://github.com/angular/angular-cli/issues/4870) and a [pull request](https://github.com/angular/angular-cli/pull/4871) to fix this.
