### ISSUE TITLE
Feature Request: fileReplacements for assets

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-cli#11206]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Desired functionality

Currently, `fileReplacements` option supports only for TypeScript module resolution.
I'd love to use it for `assets`.

Use cases

- replace manifest.json
- replace images with same URL

**Comment by MickL** [comment]
@sebek64 Could you provide more informations how to archive that, or at least the according pull request?

I would like to build the same app multiple times with different assets.

**Comment by sebek64** [comment]
Yes, the corresponding issue is for example https://github.com/angular/angular-cli/issues/10992.

**Comment by alan-agius4** [comment]
Hi all. thanks for this feature request. But I don't think that we want to continue expanding the scope of `fileReplacements`.

Most likely in the future we'll provide some sort of token based replacement, but until then replacing non TS files is out of scope.
