### ISSUE TITLE
ng new error

### ISSUE THREAD

**Issue by shubhamsony** [angular/angular-cli#11219]
getting error while creating new project using angular cli 6.0.8

npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump

added 1113 packages from 1284 contributors and audited 21849 packages in 235.594s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by pevargasg** [comment]
@shubhamsony I don't think audit exist in the npm version 5.6.0 :(

**Comment by shubhamsony** [comment]
not sure but audit exist in npm version 6.1.0

**Comment by BeRoots** [comment]
I have the same error. This problem is the same with fresh install of node LTS and node@latest versions.

https://gist.github.com/BeRoots/f8d664494116926fad38a6dfdb9cb373

**Comment by shubhamsony** [comment]
actually this issue is due to karma package which is installing some other packages that are deprecated.
the deprecated packages that karma is installing are istanbul-lib-hook, nodemailer, mailcomposer ,node-uuid, buildmail ,uws,and socks.

**Comment by shivakumarprabha** [comment]
still getting same error.......

**Comment by hollygood** [comment]
getting same error here, any updates or recommendations?

**Comment by takao42** [comment]
It's just a warning. Packages will finish installing if you wait for a while.

**Comment by shubhamsony** [comment]
@takao42  yes, but it leaves some vulnerabilities in our project.

**Comment by netbitshift** [comment]
npm v 6.1
Im getting these issues also.  After running ng new, the resulting console messages are like those mentioned above.  Then with npm audit, there are 13 vulnerabilities, 4 high.  I need to resolve this before selling the team on using the latest version of angular on a new project.  Seems like "high" issues relate to protractor and ws.  However, it seems like a major annoyance to have to manually update dependencies when spinning up a new app via ng new, especially when some of these dependencies have "high" security vulnerabilities.  I could understand if one was using beta versions etc, but not for production apps.

**Comment by vkyadav998** [comment]
i'm also getting same error when using ng new with,
Angular CLI: 6.0.8
Node: 10.6.0

**Comment by Diegotxz** [comment]
any solution? I see people creating projects and they have no problem

**Comment by vkyadav998** [comment]
hey @Diegotxz,
Now it's showing "WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump".
But its working fine with all new update.

**Comment by filipesilva** [comment]
Heya, we're tracking these vulnerability warnings/errors in https://github.com/angular/angular-cli/issues/10963.

**Comment by sdsdjr** [comment]
I have run this command
npm install -g istanbul
then create my new Angular project without any problem ( warning and errors)

**Comment by MandelaMan** [comment]
npm install -g istanbul

tried this and got a response that this was not a valid command

**Comment by Eduk29** [comment]
I have the same problem here. But I can't install node_modules, because the cli not found istanbul^0.4.5. 
Node: 10.1.0
npm: 6.0.1
ng: 6.1.2
OS: Win7/x64
