### ISSUE TITLE
Invalid import breaks UglifyJS

### ISSUE THREAD

**Issue by Etchelon** [angular/angular-cli#11214]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Versions

node v9.7.0, npm 6.0.0

### Repro steps

In any Angular file, write this:
import { Component } from "@angular/core/";
Then build the project using
ng build --prod

### The log given by the failure

At the final step of the build, "Minifying UMD Bundle", you get the following error:
Syntax error: Name expected.
at JS_Parse_Error.get(... *incomprehensible other stuff*

### Desired functionality

That the tooling tells me that importing from "@angular/core/" instead of "@angular/core" is illegal and will break everything!

### Mention any other details that might be useful

I debugged the parse.js script from Uglify JS and finally noticed that the parser was finding two commas in a row and threw and error saying it wanted a token of type "name" after the first comma. I therefore dumped the text that was being parsed and noticed that my bundle.umd.js file contained the following code:
![image](https://user-images.githubusercontent.com/4141889/41302151-0eff823e-6e6a-11e8-95b9-9511fdd8ad42.png)
And I was able to realize that an extra slash was making the compiler not find the module "@angular/core/", leaving a hole in the dependencies of the module.

I'm not really suggesting it's a bug, I just have no idea who to notify about this problem that I think is to be handled by the tooling around Angular, so I'm opening an issue here. Sorry if I should not, but since I couldn't find anything in google for a while I reckon I should share this for the next people who will have the problem!

**Comment by filipesilva** [comment]
Yeah I can see how this can be frustrating. Off the top of my head, I think webpack or uglify are the right places to notify this. 

My reasoning is that webpack outputs the code in your screenshot, which then is parsed by uglify and breaks. If the code you highlighted (double comma on args) is not valid JS then it is a webpack bug. If that is valid code then Uglify should accept it.

I hope that helps.

**Comment by Etchelon** [comment]
Thank you Filipe.

**Comment by suriyanS** [comment]
> 
> ### Bug Report or Feature Request (mark with an `x`)
> 
> ```
> - [X] bug report -> please search issues before submitting
> - [ ] feature request
> ```
> 
> ### Area
> 
> ```
> - [X] devkit
> - [ ] schematics
> ```
> 
> ### Versions
> 
> node v9.7.0, npm 6.0.0
> ### Repro steps
> 
> In any Angular file, write this:
> import { Component } from "@angular/core/";
> Then build the project using
> ng build --prod
> ### The log given by the failure
> 
> At the final step of the build, "Minifying UMD Bundle", you get the following error:
> Syntax error: Name expected.
> at JS_Parse_Error.get(... _incomprehensible other stuff_
> ### Desired functionality
> 
> That the tooling tells me that importing from "@angular/core/" instead of "@angular/core" is illegal and will break everything!
> ### Mention any other details that might be useful
> 
> I debugged the parse.js script from Uglify JS and finally noticed that the parser was finding two commas in a row and threw and error saying it wanted a token of type "name" after the first comma. I therefore dumped the text that was being parsed and noticed that my bundle.umd.js file contained the following code:
> ![image](https://user-images.githubusercontent.com/4141889/41302151-0eff823e-6e6a-11e8-95b9-9511fdd8ad42.png)
> And I was able to realize that an extra slash was making the compiler not find the module "@angular/core/", leaving a hole in the dependencies of the module.
> 
> I'm not really suggesting it's a bug, I just have no idea who to notify about this problem that I think is to be handled by the tooling around Angular, so I'm opening an issue here. Sorry if I should not, but since I couldn't find anything in google for a while I reckon I should share this for the next people who will have the problem!

Thank You So Much .. I too faced the same problem and I fixed by seeing your issue.
