### ISSUE TITLE
Is it possible to add Angular Elements to existing Angluar/CLI project?

### ISSUE THREAD

**Issue by distolma** [angular/angular-cli#11211]
Hello,
Can someone tell me how to add Angular Element to existing Angular CLI project to compile projects and elements separately? And how to compile multiple Elements in one project?

**Comment by cgatian** [comment]
A potential stopgap while tooling is developed.
 https://github.com/manfredsteyer/ngx-build-plus

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
