### ISSUE TITLE
(generate library): Directive from Library isn't working. However component works.

### ISSUE THREAD

**Issue by AhsanAyaz** [angular/angular-cli#11216]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

MacOs (High Sierra)
Node v8.11.1
npm 5.6.0

### Repro steps

- `ng new my-workspace`
- `ng g library my-lib`
- `ng g directive test --project=my-lib`
- Export it from the `public_api.ts`
- `ng build --prod my-lib`
- Import the module to the workspace (app.module.ts)
- Use that directive `test` in the project.

### The log given by the failure

```
[Angular] Can't bind to 'test' since it isn't a known property of 'div'.
```

### Desired functionality

The directive should work as it exists in the library. Same as the component is working. Though the component still looks weird in the IDE because of Angular Language Services maybe.

### Mention any other details that might be useful

Angular CLI: 6.0.8
Node: 8.11.1
OS: darwin x64
Angular: 6.0.4

**Comment by alan-agius4** [comment]
By default, components and directives get a prefix to the selector, example `myLibTest`. Are you sure that you don't have a prefix in the selector?

**Comment by AhsanAyaz** [comment]
@alan-agius4 
That's right. I already have the selector and I tried using it properly. Didn't work.
You could try cloning the repo and see: 
`https://github.com/AhsanAyaz/ngx-read-time`

**Comment by alan-agius4** [comment]
So, the problem is that you are importing the library as if it was a normal file in your `app.module` file.

ie: 
```ts
import { NgxReadTimeModule } from 'projects/ngx-read-time/src/lib/ngx-read-time.module';
```

this should be changed to import the distributed library as 
```ts
import { NgxReadTimeModule } from 'ngx-read-time';
```

**Comment by AhsanAyaz** [comment]
@alan-agius4  I had that earlier which wasn't working.
So I just changed it to the current one using which it currently works.

**Comment by alan-agius4** [comment]
Strange I tried it and it works on my machine without any build errors

**Comment by AhsanAyaz** [comment]
@alan-agius4 
I just tried it and it works fine for me too. 
I may be doing something wrong earlier then. Closing the issue. Thanks for jumping in.

**Comment by alan-agius4** [comment]
Glad it’s solved
