### ISSUE TITLE
ng serve fails if file disappears

### ISSUE THREAD

**Issue by alexfung888** [angular/angular-cli#11217]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
```

### Area
```
- [X ] devkit
- [ ] schematics
```

### Versions
npm: 6.0.1

ng v output:
```
Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/flex-layout              6.0.0-beta.16
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

- ng serve --aot
- switch branch using git, so that some files disappear

### The log given by the failure
Lots of errors in the form:
ERROR in ./src/app/todo/todo-routing.module.ts
Module build failed: Error: ENOENT: no such file or directory, open 'D:\...\src\app\todo\todo-routing.module.ts'

### Desired functionality
ng serve should compile the project.
Currently, need to break out of ng serve and start ng serve again.

### Mention any other details that might be useful
This happens a lot when switching git branches. Whole directory with the new features could disapper: modules, routing modules, components. And ng serve will complain.

**Comment by alexfung888** [comment]
Furthermore, when switching back to a branch with all the files, although ng serve successfully compiles the project, when I eventually navigate to the lazy loaded new module, I got:
```
core.js:1542 ERROR Error: Uncaught (in promise): Error: Cannot find 'TodoModule' in 'app/todo/todo.module'
Error: Cannot find 'TodoModule' in 'app/todo/todo.module'
    at checkNotEmpty (core.js:4854)
    at core.js:4840
```
I am not sure whether it is a CLI issue or core issue.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
