### ISSUE TITLE
[Bug] libraries dependencies using index.ts

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#11210]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
node v8.11.2
npm v6.1.0

### Repro steps
Here is project: https://github.com/piernik/lib-deps-bug

It contains two libraries. `Second` is dependent on `First`.  Build first lib using `npm run first:build`, then build second using `npm run second:build` - it fails.
Now go to https://github.com/piernik/lib-deps-bug/blob/master/projects/first/src/lib/first.module.ts and comment in `import {MyPipePipe} from './pipes';` and comment out  `// import {MyPipePipe} from './pipes/my-pipe/my-pipe.pipe';`
It is working now.

### The log given by the failure

```
Building Angular Package
Building entry point 'second'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc

: Unexpected value 'undefined' exported by the module 'FirstModule in C:/strony/www/libsNg/deps/dist/first/first.d.ts'
: Unexpected value 'undefined' declared by the module 'FirstModule in C:/strony/www/libsNg/deps/dist/first/first.d.ts'
```

### Desired functionality

`Pipes` folder is exported as a whole with `index.ts` so it should work.

**Comment by filipesilva** [comment]
I have heard of this problem as well, and think the issue where it is best described is the one @alan-agius4 mentioned. I am closing this issue to focus the discussion there.
