### ISSUE TITLE
cannot run ng-serve anymore

### ISSUE THREAD

**Issue by danieltutu** [angular/angular-cli#11223]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
angular cli 6.0.8
windows 7 x64
node 8.11.2
npm 5.6.0

### Repro steps
Please check the following link https://stackoverflow.com/questions/50824207/cannot-run-ng-serve-page-keep-loading

### The log given by the failure
No stacktrace.

### Desired functionality
I am expecting the app to open but the instead I get the white page, the loading indicator of the page keep spinning.

### Mention any other details that might be useful
I do not know if cli is the problem but it may seem like it because I updated it recently from version 1.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided
