### ISSUE TITLE
Unnecessary slash is being inserted into assets URLs when baseHref option doesn't have one

### ISSUE THREAD

**Issue by fr-ench** [angular/angular-cli#11226]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

![image](https://user-images.githubusercontent.com/16224535/41347561-728793aa-6f23-11e8-9489-895c1ebe6ceb.png)

My operating system is macOS High Sierra.

### Repro steps

1) I have a font with an absolute URL in my SCSS file:
```
 @font-face {
    font-family: 'some-font';
    src: url('/assets/some-font.woff') format('woff');
  }

```
2) In my angular-cli.config I have this configuration for styles:

```
      "styles": [
        "styles/styles.scss"
      ]
```

Styles.scss imports the file with a font-face definition.

3) In all of the cases listed below (disregard what value is being used for base-href) I'm geting the same results for fonts url. 

Build commands:

```
- ng build --base-href '$(SOME_VAR)/' 
- ng build --base-href '/$(SOME_VAR)' 
- ng build --base-href '$(SOME_VAR)' 
- ng build --base-href '/$(SOME_VAR)/' 
```

The build output I'm getting for my styles:

`url('/$(SOME_VAR)/assets/some-font.woff') format('woff');`

### The log given by the failure

No error log

### Desired functionality

There should not be any additional slashes in case there is a base-href option explicitly provided. The thing is, $(SOME_VAR) already has the required slash in my case, but it is only being replaced during CI when deploy is happening (which is after the ng build). 

Right now, I'm getting **//base-path/assets/** path for fonts on my website, which browser interprets as **http://base-path/assets/**, while what I need is **http://my-site.com/base-path/assets/** and it breaks the deployment.

**Comment by clydin** [comment]
The CLI has been updated significantly since version 1.6.8.  The current stable version is 8.3.5.  If this problem is still being encountered with the current version, please consider opening a new issue with updated details.
