### ISSUE TITLE
ng serve not working automatically

### ISSUE THREAD

**Issue by akgssivagami** [angular/angular-cli#11224]
### Versions
Angular CLI: 6.0.8
Node: 8.9.0
OS: linux x64
Angular: <error>
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@angular/cli                 6.0.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.1 (cli-only)
typescript                   <error>
#1209 

ng serve is not working automatically..
For every single changes, I have to run ng serve
Please give solution

**Comment by filipesilva** [comment]
There is an open issue about this problem in https://github.com/angular/angular-cli/issues/1610. Please check that issue for reasons why reload might not work.

**Comment by akgssivagami** [comment]
If I run "sudo ng serve"  it works fine.. Thank you

**Comment by chapultepec** [comment]
@akgssivagami that's the solution! Thank you!
There's a lot of people asking about this... I hope they find this issue!
