### ISSUE TITLE
Unable to install angular cli latest version

### ISSUE THREAD

**Issue by cal2dev** [angular/angular-cli#11228]
I have ubuntu 16.04 and have installed node through nvm. I have been trying to install angular cli 
with command 
`npm install -g @angular/cli`

but after installation it shows the version is 1.2.1

Output of following command: 
`nvm ls` 
        v6.14.3
        v8.11.3
->      v10.4.1
         system
default -> node (-> v10.4.1)
node -> stable (-> v10.4.1) (default)
stable -> 10.4 (-> v10.4.1) (default)
iojs -> N/A (default)
lts/* -> lts/carbon (-> v8.11.3)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.14.3
lts/carbon -> v8.11.3

`node -v`
v10.4.1

`npm -v`
6.1.0

`ng -v` 
@angular/cli: 1.2.1
node: 10.4.1
os: linux x64

**Comment by cal2dev** [comment]
Already tried 
`npm install -g @angular/cli@6.0.7`
and 
`npm install -g @angular/cli@latest`

need a way to get the latest cli

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by cal2dev** [comment]
Thanks for the response.
As I stated above the command installing cli properly but after install why I always get version 
@angular/cli: 1.2.1

Can you please tell me why its installing old version. i don't think so its a npm Issue.

**Comment by filipesilva** [comment]
I really can't say. `npm` is the one installing the package. If after running `npm` the right version isn't installed, then it's probably some problem in the npm install. I know some users end up with two npm global folders and the right one isn't on their system path. But it's not something we can do anything about here, it's an installation problem specific to your setup.

**Comment by cal2dev** [comment]
Thanks for the response again.
I resolved the issues. The issue was having to node_modules folder in different directory. One has old angular and one have the latest one.
Thanks again.
