### ISSUE TITLE
ng new <appname> is broken

### ISSUE THREAD

**Issue by mlamba9390** [angular/angular-cli#11234]
it seems like one of the files is corrupted and after that there are errors
see below

npm WARN tarball tarball data for typescript@~2.9.1 (sha512-Gr4p6nFNaoufRIY4NMdpQRNmgxVIGMs4Fcu/ujdYk3nAZqk7supzBE9idmvfZIlH/Cuj//dvi+019qEue9lV0w==) seems to be corrupted. Trying one more time.

and after that there are the following errors

npm ERR! path c:\Users\msing\Angular_Projects\LambaMotors\node_modules\.staging\typescript-a6526030\lib\typescriptServices.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'c:\Users\msing\Angular_Projects\LambaMotors\node_modules\.staging\typescript-a6526030\lib\typescriptServices.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'c:\Users\msing\Angular_Projects\LambaMotors\node_modules\.staging\typescript-a6526030\lib\typescriptServices.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'c:\Users\msing\Angular_Projects\LambaMotors\node_modules\.staging\typescript-a6526030\lib\typescriptServices.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'c:\\Users\\msing\\Angular_Projects\\LambaMotors\\node_modules\\.staging\\typescript-a6526030\\lib\\typescriptServices.js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'c:\\Users\\msing\\Angular_Projects\\LambaMotors\\node_modules\\.staging\\typescript-a6526030\\lib\\typescriptServices.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'c:\\Users\\msing\\Angular_Projects\\LambaMotors\\node_modules\\.staging\\typescript-a6526030\\lib\\typescriptServices.js',
npm ERR!   parent: '@angular-devkit/build-optimizer' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\msing\AppData\Roaming\npm-cache\_logs\2018-06-13T22_38_53_006Z-debug.log
Package install failed, see above.

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] None
```

### Area
```
- [ ] devkit
- [ ] schematics
- [x] use of the cli to create a new app breaks when a package being downloaded by npm is found to be corrupted. See above for details
```

### The log given by the failure

Log attached
[2018-06-13T22_38_53_006Z-debug.log](https://github.com/angular/angular-cli/files/2100240/2018-06-13T22_38_53_006Z-debug.log)

**Comment by Code-Monkey-Nick** [comment]
Try running the command npm install -g typescript@~2.9.1. Then try to recreate your app.

**Comment by mlamba9390** [comment]
Seems good now. I think the corrupted dependency may have been corrected

**Comment by SaBworld** [comment]
I don't think the corrupted library has been fixed because I've just had the exact same issue which has been solved with Code-Monkey-Nick solution hence installing typescript on its own.
