### ISSUE TITLE
Extract CSS to sub-folder "dist/assets/css" with correct asset paths

### ISSUE THREAD

**Issue by actra-gschuster** [angular/angular-cli#11239]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
Devkit 0.6.8

### Desired functionality
As currently implemented one can only specify "extractCss: true" - it would be nice to specify the output filename to extract to e.g. an "dist/assets/" folder.
The usecase is to have a clean, structured dist package.

### Mention any other details that might be useful
In order to implement this feature, the "postcss-cli-resources" plugin has to be modified.
As currently implemented it can't handle the asset paths relative to the "to-be-extracted" css file, so I think there's a need to tell the plugin where the css file will later be outputted to so it can modify the paths accordingly.

**Comment by MickL** [comment]
Does this really make sense? In production mode mostly we use `outputHashing: true` which generates random hash names for all files. This ensures updated files are not cached by the browser. Also files that did not change don't have to be uploaded(file upload can skip exisiting file names).

Is it really more clean to have a styles.css in assets folder? Personally i would leave generation / naming of automatically generated files to webpack/angular-cli.

**Comment by actra-gschuster** [comment]
Depends, my current customer wants it that way and I try to implement what's desired.
Personally I'm also a big fan of clean structures so I don't have to scroll through huge directory listings of images, HTML, whatever to find a specific file.

**Comment by clydin** [comment]
You can move the extracted CSS to any location desired as long as the `index.html` is updated to reflect the new location.

Also please note that _clean_ is a highly opinionated topic.  Some would argue a flat directory structure to be _cleaner_ than a large amount of nested directories.  It can also be useful to consider the output (`dist`) directory to be an opaque object that is transferred directly to the deployment server; wherein the structure is largely irrelevant.
