### ISSUE TITLE
Unable to uninstall angular cli

### ISSUE THREAD

**Issue by avarela1012** [angular/angular-cli#11230]
Angular checks for updates instead of uninstalling.

### Area

devkit

### Versions
node version: v8.11.2
npm version: 5.6.0
Windows: 10
Angular cli version: 6.0.8

### Repro steps
I tried simply running:
`npm uninstall -g @angular-cli`

then I read I had to run:
`npm cache clean --force`
`npm uninstall -g @angular-cli`

### The log given by the failure
The output is:

> up to date in 0.055s

 
### Desired functionality
I want to uninstall the angular-cli no update it.

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by scotts985** [comment]
On Windows 7 the npm uninstall does not work. The solution I found is to 1. uninstall node.js, 2. delete the npm and npm-cache directories, 3 reinstall node js and 4 install the cli version you need. Note: ng -v will still show the prior version of the cli if it exists in a nod-modules directory in the path where you call it. it. 
In my case the directories to delete were as followed:
C:\Users\userid\AppData\Roaming\npm-cache
C:\Users\userid\AppData\Roaming\npm

To install specific version of the Angular CLI:
npm install -g @angular/cli@1.7.4

Finally to have ng -v report the correct version. I deleted a node-modules directory which contained the previous Angular cli version (in my case was 6.1)

Scott

**Comment by ganeshkavhar** [comment]
I am getting this erro while installing Angualr 

C:\>npm install -g @angular/cli
[..................] | loadIdealTree:loadAllDepsIntoIdealTree: sill install loadIdealTree[..................] / fetchMetadata: sill removeObsoleteDep removing uuid@3.3.2 from the tree as its been replaced by a newer version or is no longer [..................] - fetchMetadata: sill removeObsoleteDep removing uuid@3.3.2 from the tree as its been replaced by[..................] | fetchMetadata: sill removeObsoleteDep removing uuid@3.3.2 from the tree as its been replaced by a n[..................] - fetch[        ..........] | extract:run-async: http fetch GET 200 https://registry.npmjs.org/promise-retry/-/promise-retry-1.1.1.tg[        ..........] | extract:run-asynpm ERR! path C:\Users\GANESH\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\.bin
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\GANESH\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\.bin'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\GANESH\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\.bin']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\GANESH\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\.bin'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\GANESH\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\.bin' },
npm ERR!   stack:
npm ERR!    "Error: EPERM: operation not permitted, unlink 'C:\\Users\\GANESH\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\.bin'",
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\GANESH\\AppData\\Roaming\\npm\\node_modules\\@angular\\cli\\node_modules\\.bin' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GANESH\AppData\Roaming\npm-cache\_logs\2019-06-11T04_35_21_488Z-debug.log
