### ISSUE TITLE
I couldn't open application with my local ip address in local network

### ISSUE THREAD

**Issue by gopal-augment** [angular/angular-cli#11243]
I have used both commands in cli v6.0.8. ng serve --host 0.0.0.0 and ng serve --host 1.1.1.1(My ip).
It doesn't work in another machine that connected via local network.
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Versions
Angular CLI: 6.0.8
Node: 8.11.3
OS: linux x64
Angular: 6.0.4

`node --version` - 6.1.0
`npm --version` - 8.11.3

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
