### ISSUE TITLE
NgTools. Setting compilerOptions.module to es6 leads to dead code not removed

### ISSUE THREAD

**Issue by WiseBird** [angular/angular-cli#11240]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

node -v
v8.9.3

npm -v
4.1.2

uname -a
Linux computer 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Repro steps

I have simple ts file that imports one function from lodash:
```
import {uniq} from 'lodash-es';
uniq([1,2,3,2,1])
```
Tsconfig:
```
  "compilerOptions": {
    "target": "es5",
    "module": "es6",
    ...
```

Building with bare minimum of options for ngtools plugin:
```
        new ngToolsWebpack.AngularCompilerPlugin({
            tsConfigPath: './tsconfig.json',
        }),
```
gives expected result:
```
           Asset      Size  Chunks             Chunk Names
./bundle.main.js  6.24 KiB       0  [emitted]  main

```

but if `compilerOptions.module` is added (note that this should be a noop as the same value set via `tsconfig`):
```
        new ngToolsWebpack.AngularCompilerPlugin({
            tsConfigPath: './tsconfig.json',
            compilerOptions: {
                module: "es6",
            },
        }),
```
then result is unexpected:
```
           Asset      Size  Chunks             Chunk Names
./bundle.main.js  98.6 KiB       0  [emitted]  main

```
complete lodash lib was included into build!

### Desired functionality

Dead code should be removed

### Mention any other details that might be useful

[Reporduction](https://github.com/WiseBird/ngtools_dead_code)

**Comment by alan-agius4** [comment]
Hi, I had a look at this and this looks like it's not a bug. `module` in this case is of type `ModuleKind`, which is a enumeration. `ES6` is not valid value. Thus providing `es6` value here is setting it to the default module in typescript which I think it's `CommonJS` .

The correct way to override this setting via the webpack config is;

```ts
const ts = require( "typescript");

...

new ngToolsWebpack.AngularCompilerPlugin({
    tsConfigPath: './tsconfig.json',
    compilerOptions: {
        module: ts.ModuleKind.ESNext,
    },
}),
```
