### ISSUE TITLE
Dry-run to print useful information

### ISSUE THREAD

**Issue by djhojd** [angular/angular-cli#11242]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality

Right now, with the new `angular.json` format we can add some `options` at the top level under each `Architect target` and lots of different `configurations` which also can have their own `options` overwriting the top ones, on top of this we now can target other `architect` with it's own configuration/options.
What I think would be great is a CLI `dry-run` command to check the final `options` that are being used and maybe other useful information for each target we pass through.

**Comment by alan-agius4** [comment]
Thanks for this feature request. 

However, at the moment this is outside of the scope of the Angular CLI.  Let's reconsider this in the future if there is more interest from the community.
