### ISSUE TITLE
Support fileReplace for scss files.

### ISSUE THREAD

**Issue by robindijkhof** [angular/angular-cli#11253]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
CLI 6.1.0-rc.0

### Desired functionality
I think it would very very useful if fileReplace would support `scss` file. This would allow for different material2 theming for different configurations. I found a issue and pr to support `html` files, however,`scss` was not included.

**Comment by alan-agius4** [comment]
Hi @robindijkhof, Thanks for this feature request, however this feature is currently not in the Angular CLI roadmap.
