### ISSUE TITLE
Generating a library produces wrong destination directory in prod

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular-cli#11251]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [] schematics
```

### Versions

**npm:** 6.0.0
**node:** 8.11.2
**Windows:** 10

### Repro steps

I am using v6.0.7 of the CLI, when a library is e.g. `ng generate library button`, the generated `ng-package.prod.json` has the path `"../../dist/lib`" for the dest path instead of the library name

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/lib",
  "lib": {
    "entryFile": "src/public_api.ts"
  }
}
```

Generate library 

### Desired functionality

Should use library's name
```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/${libraryName}",
  "lib": {
    "entryFile": "src/public_api.ts"
  }
}
```

**Comment by alan-agius4** [comment]
What versions of packages are you using? I am using the `~0.7.0-beta.2` and when doing 

```cmd
ng generate library button
```

the `dest` option is populated correctly as expected ie
```js
  "dest": "../../dist/button",
```

**Comment by MurhafSousli** [comment]
@alan-agius4 It happened after I updated CLI to `6.0.7`
```
"@angular-devkit/build-angular": "~0.6.0",
"@angular-devkit/build-ng-packagr": "~0.6.0",
"@angular/cli": "^6.0.7",
"@angular/compiler-cli": "^6.0.0",
"@angular/language-service": "^6.0.0",
```

**Comment by Brocco** [comment]
This has since been fixed and will be included in the next release.
