### ISSUE TITLE
ng update not working on ejected project

### ISSUE THREAD

**Issue by FARHANE** [angular/angular-cli#11264]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
node v8.11.3
npm 6.1.0

nothing happens when I run : ng update @angular/cli for an ejected project.
I leave the computer for 14 hours and nothing happening no log no error message.

**Comment by clydin** [comment]
Once a project is ejected, the maintenance and overall management of the project is no longer handled by the CLI.  `ng update` is not intended to function in such a scenario.
