### ISSUE TITLE
angular 6.0.8 Upgrade failure with lot of warnings  (CLI or peer dependencies.)

### ISSUE THREAD

**Issue by maifs** [angular/angular-cli#11260]
I am complaining the same issue second time but couldn't be listened properly ( and my issue was closed) and my issue is still there.
### Bug Report (`x`)
- [X] bug report
- [ ] feature request

### Area
```
Unsure of source, problem exhibits in CLI or peer dependencies.
```

### Versions

Output from: `node --10.4.0` and `npm --6.1.0`.
  Windows (10).

### Repro steps
This is the actual repository source : [https://github.com/emonney/QuickApp](url)
1). Please get source from above link 
2). upgrade all packages to latest versions (angular 6.0.8).  
3). install angular material 6.2.1 and @angular/cdk (6.2.1) 
i am using these command mentioned in this web side please see below:
[http://www.talkingdotnet.com/upgrade-angular-5-app-angular-6-visual-studio-2017/](url)

### The log given by the failure
added 1502 packages from 1897 contributors and audited 40701 packages in 681.056s
found 6 vulnerabilities (1 low, 5 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

M:\StoreApplications\Git\SaleStoreApp\SaleStoreApp\SaleStoreAppUI\ClientApp>npm audit fix
npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'M:\StoreApplications\Git\SaleStoreApp\SaleStoreApp\SaleStoreAppUI\ClientApp\node_modules\fsevents\node_modules'
npm WARN @ngtools/webpack@6.0.0-beta.7 requires a peer of typescript@~2.5.0 | ~2.6.0 | ~2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.1.0 requires a peer of jasmine@>=3 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-toasty@4.0.3 requires a peer of @angular/core@^2.4.7 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-bootstrap@3.0.0 requires a peer of @angular/forms@6.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\karma\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

moved 2 packages in 61.518s
fixed 0 of 6 vulnerabilities in 40701 scanned packages
  6 vulnerabilities required manual review and could not be updated

### Desired functionality
I want to work my application perfectly with angular material 6.2.1 and bootstrap 4.1.1 and with all updated packages. I have upgraded my application from 5.2.9 to angular 6.0.8  ( and now removed it too and install angular 6.0.1 for the issue of ngx-bootstrap resolution) but i am still facing these issue even after doing everything mentioned in all articles. I don't know why it show these messages even i have set the right packages now.

### Mention any other details that might be useful
Angular CLI: 6.0.1
Node: 10.4.0
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/build-webpack     0.0.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.1
@angular/cdk                      6.2.1
@angular/cli                      6.0.1
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.12.0

Please see my package.json file---------------------------

{
  "name": "SaleStoreApp",
  "version": "2.5.3",
  "description": "Angular6 (with ASP.NET Core) ",
  "author": {
    "name": "SaleStoreApp",
    "email": "info@salestoreapp.com",
    "url": "https://www.salestoreapp.com/about"
  },
  "license": "MIT",
  "homepage": "https://www.salestoreapp.com/",
  "repository": "https://github.com/salestoreapp/a.git",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:ssr": "npm run build -- --app=ssr --output-hashing=media",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "dependencies": {
    "@angular-devkit/build-webpack": "0.0.8",
    "@angular/animations": "^6.0.1",
    "@angular/cdk": "^6.0.1",
    "@angular/common": "^6.0.1",
    "@angular/compiler": "^6.0.1",
    "@angular/core": "^6.0.1",
    "@angular/forms": "^6.0.1",
    "@angular/http": "^6.0.1",
    "@angular/material": "^6.0.1",
    "@angular/platform-browser": "^6.0.1",
    "@angular/platform-browser-dynamic": "^6.0.1",
    "@angular/router": "^6.0.1",
    "@ngtools/webpack": "^6.0.1",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@swimlane/ngx-datatable": "^13.0.1",
    "@types/node": "^10.1.4",
    "angular": "^1.7.1",
    "angular-archwizard": "^3.0.0",
    "bootstrap": "^4.1.1",
    "bootstrap-datepicker": "1.8.0",
    "bootstrap-select": "1.13.1",
    "bootstrap-toggle": "^2.2.2",
    "chart.js": "^2.7.2",
    "core-js": "^2.5.7",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "ng2-charts": "^1.6.0",
    "ng2-toasty": "^4.0.3",
    "ngx-bootstrap": "^3.0.0",
    "popper": "^1.0.1",
    "popper.js": "^1.14.3",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "typescript": "^2.7.2",
    "web-animations-js": "^2.3.1",
    "webpack": "^4.12.0",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.6.8",
    "@angular-devkit/core": "^0.6.8",
    "@angular/cli": "^6.0.1",
    "@angular/compiler-cli": "^6.0.1",
    "@angular/language-service": "^6.0.1",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.2",
    "codelyzer": "^4.3.0",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.1",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^1.1.0",
    "protractor": "~5.3.2",
    "ts-node": "^6.1.0",
    "tslint": "~5.10.0"
  },
  "keywords": [
    "ng",
    "angular",
    "angular2",
    "angular5",
    "angular6",
    "angularX",
    "aspnetcore",
    "aspnet-core",
    "startup",
    "template",
    "quick-app",
    "quickapp",
    "quickapplication",
    "rad",
    "ng2",
    "ng5",
    "ngX"
  ]
}

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
