### ISSUE TITLE
Make docs for angular-cli / angular.json more discoverable

### ISSUE THREAD

**Issue by toupeira** [angular/angular-cli#11266]
I just spent way too much time finding documentation on the options in `angular.json` and thought I'd document my journey to hopefully improve the situation :)

I'm pretty new to Angular and ran into an issue when upgrading an app from Angular 5 to 6: apparently it was previously possible to specify a *file* path for the output of assets:

```json
{
  "glob": "README.md",
  "input": "../node_modules/foo/",
  "output": "./foo-README.md"
}
```
But in Angular 6 the output path is always treated as a directory, resulting in a path of `dist/foo-README.md/README.md` for the above example. I couldn't find any documentation of this change, and am unsure if it's even a change in `@angular/cli` or maybe a Webpack 4 thing. Anyway, all I wanted to know is if I can specify other options to get the same output path as before.

Google wasn't much help so I jumped on https://angular.io/ and tried a few searches:
- "angular.json", ".angular-cli.json": no results
- "configuration", "assets", "cli": no useful results

Googling `"angular.json" site:"https://angular.io"` brought me to https://angular.io/guide/quickstart which says "Check out the official documentation if you want to know more.". Hmm... isn't this precisely what I'm trying to do? :)

After some more googling I stumbled over https://cli.angular.io/. After browsing around a bit I found these pages which were also a dead-end:

- https://github.com/angular/angular-cli/wiki/serve (should link to https://github.com/angular/angular-cli/wiki/stories-asset-configuration)
- https://github.com/angular/angular-cli/wiki/angular-workspace (should link to https://github.com/angular/angular-cli/blob/master/packages/angular/cli/lib/config/schema.json)

After yet more googling and realizing I overlooked the "stories" link at the bottom of the wiki index I found https://github.com/angular/angular-cli/wiki/stories-asset-configuration which finally gave me the information I was looking for. Unfortunately there aren't any additional options to specify a file output path, so I ended up converting to directories and changing the application code correspondingly.

Hope this helps, I realize documentation is always a struggle and saw the previous issues about this, but just adding some links in the right places would be *very* helpful :)

**Comment by clydin** [comment]
Angular CLI documentation is now part of the main Angular website and can be found here: https://angular.io/cli
