### ISSUE TITLE
The 3rdpartylicenses.txt does not contain the licences for all packages in package.json.

### ISSUE THREAD

**Issue by flipZomb** [angular/angular-cli#11263]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request

The 3rdpartylicenses.txt does not contain the licences for all packages in package.json. 
For example licence for Angular Material is missing.

Filled this issue in the past and it was resolved but now it seems to be back again.

```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
Angular CLI :6.0.8
node --version: v8.11.2
npm --version: 5.6.0
 Windows 10

### Repro steps
I presume run
ng build --aot --prod

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by flipZomb** [comment]
Thanks you for answer.

Here is the repository 

https://github.com/flipZomb/repro-app

App useds angular material but it's license is not listed when building with "ng build --aot --prod"

**Comment by filipesilva** [comment]
I could reproduce using the repro in https://github.com/angular/angular-cli/issues/11263#issuecomment-398699349.

I tested manually including https://github.com/angular/angular-cli/pull/12352 and could verify material was there. This will be released in the upcoming `@angular-devkit/build-angular@0.9.0-beta.4`.
