### ISSUE TITLE
ng update fails to migrate project artifacts (eg angular-cli.json)

### ISSUE THREAD

**Issue by williamBurgeson** [angular/angular-cli#11269]
Having upgraded @angular/cli globally to v6, and running `ng update @angular/cli` on a v5 project, it updated all @angular related dependencies in package.json but failed to update anything else. 

When manually setting @angular/cli in package.json to 6 this didn't happen.

This happened in 6.0.0 however I believe I was getting similar or intermittent problems with all versions o6 6.0.x during the course of the day today.

I mistakenly thought this issue was address in https://github.com/angular/angular-cli/issues/11109 however on closer reading I was mistaken - however within the code itself the potential solution may be related.

**Comment by clydin** [comment]
The official recommendation (https://update.angular.io) is to install both globally and locally first before the `ng update` command.  This is due to the need to use the newer (and much more comprehensive) update functionality present in CLI 6.0.
