### ISSUE TITLE
Angular-cli Version Manager

### ISSUE THREAD

**Issue by inunotaisho26** [angular/angular-cli#11265]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Versions

All that angular-cli is compatible with.

### Desired functionality

I would like Angular-cli to create something similar to NVM (Node Version Manager). I am only able to install one version of the angular-cli at a time and I am having to move to and from Angular 4, 5, and 6 on a routine basis. I am working on projects that use angular 4 and i am also trying to refactor that same project into angular 5. I will eventually need angular 6 full time once all the major kinks are worked out.

**Comment by clydin** [comment]
The globally installed CLI automatically delegates to the local, project version of the CLI.  You can currently have multiple projects all with different local versions of the CLI and successfully develop each.

**Comment by inunotaisho26** [comment]
@clydin I have ask this then. Are you still able to eject the projects using an older version of angular or are we stuck on that front?

**Comment by clydin** [comment]
Ejecting essentially removes the CLI as the _manager_ of the project.  The local dependencies and the generated webpack configuration file are the controlling element of the project from that point.

**Comment by clydin** [comment]
It is currently only not present for CLI 6.0./6.1.  A more advanced form is currently under development and will be included in a future 6.x minor release.

**Comment by aemonge** [comment]
Or can we at least have a table where we can know which version of angular/cli install a angular project. 

So we can set via `nvm` a specific version of the `npm i @angular/cli@x.y.z` to create different versions of angular.

A table like this would be just fine:

|   CLI   |    Angular
_______________
  1.7.0  |      7
  1.6..8  |      5
