### ISSUE TITLE
[ng generate] refer an already existing module to an other module.

### ISSUE THREAD

**Issue by SerkanSipahi** [angular/angular-cli#11276]
I dont know whether is this a bug report or a feature request! I search for a solution but noting found. 

[x] bug report
[x] feature request

I want to `modify` any `module` over `cli` in order to refer it to a other module but it does not work as expected! Either you can `create` a `module` or your can `force`(override) them without any modification. 

My Question: is there a way to link a module to other one? (this also applies to components, directives, etc)

#### This is my workflow:
1.) (works fine)Create Module:
```
ng generate module modules/toolbar-layout
```

2.) (works fine)Create component, export them and refer it to a module:
```
ng generate component components/search-bar -st -c=OnPush -m modules/search-bar --export
```

3.) (works not fine, it overrides instead of updating them) Refer an already existing module to an other module
```
ng generate module modules/search-bar -m app -f
```

#### System:
```
Angular CLI: 6.0.8
Node: 9.3.0
OS: darwin x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.2.1
@angular/cli                       6.0.8
@angular/flex-layout               6.0.0-beta.16
@angular/material                  6.2.1
@angular/pwa                       0.6.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.1
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.8.3
```

**Comment by SerkanSipahi** [comment]
@clydin what does this tag (` comp: schematics/angular`) mean?

**Comment by clydin** [comment]
It is an issue triage tag which targets the system component related to the issue.

**Comment by SerkanSipahi** [comment]
Will you guys implement that feature?

**Comment by clydin** [comment]
To clarify, you're trying to add `modules/search-bar` (which already exists) to the application's main module?

If so, that is not the purpose of the generate command.  Its intention is to actually _generate_ a module.  Overall, it would also probably be less typing to open up the application's module and add the import then it would be to type out a command on the command line to do the equivalent;  while keeping the intention of generate consistent.
There's also the alternative (which is generally the typical workflow) of creating the `modules/search-bar` first with the above command and then creating the component.

**Comment by SerkanSipahi** [comment]
sound good, thanks.
>There's also the alternative (which is generally the typical workflow) of creating the modules/search-bar first with the above command and then creating the component.

**Comment by Brocco** [comment]
@SerkanSipahi it appears that the suggestion from @clydin is working for you so I am closing this issue.

Thanks!
