### ISSUE TITLE
Setting Library Version on Build

### ISSUE THREAD

**Issue by jayoungers** [angular/angular-cli#11270]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
Node v8.11.2
NPM 6.1.0

### Desired functionality
Prior to Angular CLI 6 when using ng-packagr, on package generation it would update the version of the /dist/package.json file to match the version number of the base package.json file.

Given the following layout in angular-cli 6:
/package.json (@1.1.1)
/projects/myLib/package.json (@0.0.1)

Is there a configuration or setting that would pull in the version from that base package.json (or from the process) into `/dist/myLib/package.json`?  It appears by default it just pulls in whatever the value is in `/projects/myLib/package.json`.

**Comment by alan-agius4** [comment]
The library version is always determined by the `package.json` inside the `myLib`. There is/was no such functionality as you are mentioned.

**Comment by jayoungers** [comment]
I think the difference for my project was there was only one `package.json` file: it was a single angular-cli project containing a 'lib' directory and another to test out the library (referenced directly).

I'm guessing not many have switched yet to the new library project layout, but I'm hoping someone's run into a similar situation: how to go about getting either angular-cli or semantic-release to update the library project's `package.json` file (either before or after it's generated); I know what the version needs to be, I'm just not sure what the cleanest way of setting it in this situation is.  

I would guess maybe the intended solution would be to have these build scripts at the library project level and not the overall workspace level, but I'm not sure how that would work.  With tagging the repo and everything I'm not sure if there'd be a reason you'd want the various projects at different versions.

**Comment by alan-agius4** [comment]
In kinda boils down to what versioning strategy you want to use.  In some cases it might make sense to use independent versioning.

That said, neither `Angular CLI` nor `ng-packagr` have any integration to `semantic-release` or something similar. That said, I do think that it would be beneficial if in future there would be something like that.

**Comment by alan-agius4** [comment]
yes, that can be done. Though publishing shouldn't publish by lerna as it
doesn’t support custom publishing folder example from ‘dist ’

**Comment by jayoungers** [comment]
In case anyone else stumbles upon this, for now I've just created an extra node script to run after `ng build`:

```
const loadJsonFile = require('load-json-file');
const writeJsonFile = require('write-json-file');

loadJsonFile('dist/myLib/package.json').then(pkg => {
  pkg.version = process.env.npm_package_version;

  writeJsonFile('dist/myLib/package.json', pkg);
});
```

**Comment by clydin** [comment]
Closing this as there are some very good answers above.  (Thank you)
