### ISSUE TITLE
How is the ng-new workflow supposed to work for a custom collection?

### ISSUE THREAD

**Issue by CarstenLeue** [angular/angular-cli#11279]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] clarification
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Repro steps
It is possible to hook into the "ng new" workflow with a custom collection by specifying the "-c" parameter. However it is unclear to me how this collection has to be installed. What works for me is:

- install the cli globally (`npm install -g @angular/cli`)
- install the custom collection locally, i.e in the folder where you plan to run `ng new` from (`npm install MY_COLLECTION`)
- create a new project using your collection (`ng new -c MY_COLLECTION <NAME>`)

However this workflow seems to be strange, since I typically do not have a local project when running `ng new`, so having to first install my collection in the local folder is weird.

I would have expected either of the following:
(1) I can install my collection GLOBALLY, just as I did with `@angular/cli`. Calling `ng new -c MY_COLLECTION <NAME>` would then work from any directory. However this does NOT work, my collection is not picked up when installed globally.
(2) the `ng new` process automatically instally my collection (just as `ng add` does), so I do not have to bother to install it, first.

Could you please motivate why my collection has to be installed, locally? Or is this a bug?

**Comment by hansl** [comment]
We look for collections globally, so this should work.

**Comment by pfeileon** [comment]
What is the current status of this issue?

**Comment by kyliau** [comment]
> the ng new process automatically instally my collection (just as ng add does), so I do not have to bother to install it, first.

I think this should have worked. If not, then it is a bug. You shouldn't have to install a collection before it's used.

**Comment by Lykathia** [comment]
I just ran into this. Can confirm still an issue w/ angular 11. Had to create a temp directory, `npm install`, then `ng new` to get the collection to take.

**Comment by alan-agius4** [comment]
This is expected, collections are not installed when automatically. Automatic installation only happens when using `ng add`.

**Comment by alan-agius4** [comment]
Closing as per above.
