### ISSUE TITLE
[schematics/angular] No need to generate a module spec

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#11277]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Repro steps

When generating a module, a spec file is created.
This file has no real interest and was not generated before CLI v6 if I'm not mistaken.
It's possible to skip the generation with the `spec` option,
but as the test is not really useful, the test should never be created and the option removed?

```
module-spec git:master ❯ ng g m shared
CREATE src/app/shared/shared.module.spec.ts (275 bytes)
CREATE src/app/shared/shared.module.ts (190 bytes)
```

### Desired functionality

It should not generate a spec file.

**Comment by damienwebdev** [comment]
So, the real question for.me, and this has now come up in several projects, is WHY this came to be. Was this intentional but never discussed, or was this a mistake. Generally, speaking most module specs are useless, but was there a use-case that supported ALWAYS generating a spec file?
