### ISSUE TITLE
build_angular - dev_server: buildWebpackConfig is never called

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular-cli#11281]
In this line [1], the contents of the ``buildWebpackConfig`` method is repeated instead of calling it. On the other side, the ``buildWebpackConfig`` is never called.

I think we should replace those three lines of code with a method call for ``buildWebpackConfig``.

[1] https://github.com/angular/angular-cli/blob/76f46bc00a9400bf481dc3bdfb41de08facda340/packages/angular_devkit/build_angular/src/dev-server/index.ts#L88

**Comment by clydin** [comment]
Yes. It definitely should.  Would you be willing to put together a PR?

**Comment by lacolaco** [comment]
It seems going to be fixed in the commit. (not released yet)
https://github.com/angular/angular-cli/commit/cb588b68b34641cbfc31b563f741f94f48211b2d

**Comment by filipesilva** [comment]
Fixed via https://github.com/angular/angular-cli/pull/11508
