### ISSUE TITLE
Angular 6 Production on local IIS, Manual Url/Refresh Page is not working 

### ISSUE THREAD

**Issue by sajjadkhadim** [angular/angular-cli#11285]
The project is built successfully, deployed on local-IIS. The routes are working fine when navigate through index.html but when i refresh the page, it shows Http Error 404.0 - Not Found.

Following is the detail of versions, running on my system.

### Versions
Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect             0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core                    0.6.8
@angular-devkit/schematics         0.6.8
@angular/cli                                  6.0.8
@ngtools/webpack                       6.0.8
@schematics/angular                    0.6.8
@schematics/update                     0.6.8
rxjs                                                 5.5.8
typescript                                      2.5.3
webpack                                        4.8.3

![angular 6 url manual issue](https://user-images.githubusercontent.com/28727426/41523155-54112bf2-72f2-11e8-8e3a-b7b9f755810e.jpg)

**Comment by derkachdeveloper** [comment]
@sajjadkhadim, repo link, please.

**Comment by sajjadkhadim** [comment]
after adding web.config, showing HTTP Error 500.19 - Internal Server Error
![angular 6 url issue webconfig file](https://user-images.githubusercontent.com/28727426/41523453-7a1450ee-72f3-11e8-8c5e-58ddf9bc129f.jpg)


<system.webServer>
  <rewrite>
    <rules>
      <rule name="Angular Routes" stopProcessing="true">
        <match url=".*" />
        <conditions logicalGrouping="MatchAll">
          <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
          <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
        </conditions>
        <action type="Rewrite" url="/index.html" />
      </rule>
    </rules>
  </rewrite>
</system.webServer>

**Comment by derkachdeveloper** [comment]
@sajjadkhadim, it is a not angular bug.
![image](https://user-images.githubusercontent.com/6834477/41524079-e477b0f2-72e4-11e8-89a4-b13d33afcae7.png)
![image](https://user-images.githubusercontent.com/6834477/41524086-ec495c7c-72e4-11e8-993f-ab1c82091bce.png)

system.webServer should be wrapped by configuration node.

**Comment by sajjadkhadim** [comment]
@derkachdeveloper thanks for your reply, i have tried with <configuration> tag, but still showing error

![angular 6 url issue webconfig file configuration](https://user-images.githubusercontent.com/28727426/41525203-9e522b4c-72f9-11e8-9c55-f08fb8151e27.jpg)

**Comment by derkachdeveloper** [comment]
@sajjadkhadim, do you can share repo? i to try.

**Comment by sajjadkhadim** [comment]
@derkachdeveloper now my web.cofig file is below
![webconfig file](https://user-images.githubusercontent.com/28727426/41525427-66790b2c-72fa-11e8-8631-a01c6dec10bf.JPG)

**Comment by sajjadkhadim** [comment]
@derkachdeveloper, project is confidential, can not share repo.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sajjadkhadim** [comment]
@clydin  Above issue is resolved by configuration of URL Rewrite.

I have followed instruction given below
https://stackoverflow.com/questions/12614072/how-do-i-configure-iis-for-url-rewriting-an-angularjs-application-in-html5-mode/26152011#26152011

I have installed urlrewrite.exe and then deployed in C:\inetpub\wwwroot\GTSS, 'GTSS' is project directory.

**Comment by AbderrahmeneDZ** [comment]
Hello everyone, 
in few weeks ago, I was really stuck because of this 404 error, so after trying more than one solution, and all of those solutions were returning sometimes 404 or 500 errors, I decided to redirect the any wrong request to index.html in case of error.

so I googled for it and I found this solution : 
web.config : 
```
<?xml version="1.0" encoding="UTF-8"?>

<configuration>
  <system.web>
    <compilation targetFramework="4.0" />

    <customErrors mode="On" redirectMode="ResponseRewrite">
      <error statusCode="404" redirect="/index.html" />
    </customErrors>
  </system.web>

  <system.webServer>
    <httpErrors errorMode="Custom">
      <remove statusCode="404"/>
      <error statusCode="404" path="/index.html" responseMode="ExecuteURL"/>
    </httpErrors>
  </system.webServer>
</configuration>
```
the good part of this solution, all my route are working as they should, and I can refresh and write the url manually without any error.

**Comment by ArunEdathadan** [comment]
This helped me with the routing issue
[https://blog.angularindepth.com/deploy-an-angular-application-to-iis-60a0897742e7](url)

<?xml version="1.0" encoding="utf-8"?>
<configuration>

<system.webServer>
  <rewrite>
    <rules>
      <rule name="Angular Routes" stopProcessing="true">
        <match url=".*" />
        <conditions logicalGrouping="MatchAll">
          <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
          <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
        </conditions>
        <action type="Rewrite" url="./index.html" />
      </rule>
    </rules>
  </rewrite>
</system.webServer>

</configuration>
