### ISSUE TITLE
warning TS0: @interface annotations are redundant with TypeScript equivalents

### ISSUE THREAD

**Issue by derkachdeveloper** [angular/angular-cli#11282]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Versions

NPM 5.6.0
NodeJS v10.1.0

### Repro steps

- ng generate library dd-ng-primitives --prefix=dd
- add interfaces with JSDoc. Sample:
```
/**
 * Container size.
 * @export
 * @interface Size
 */
export interface Size {
  /**
   * Container width into pixels.
   * @type {number}
   * @memberof Size
   */
  width: number;

  /**
   * Container height into pixels.
   * @type {number}
   * @memberof Size
   */
  height: number;
}
```
-- ng build --prod dd-ng-virtualized

### The log given by the failure
BUILD ERROR
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(1,1): warning TS0: @interface annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(7,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(14,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(7,1): warning TS0: @class annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/dd-ng-primitives.module.ts(6,1): warning TS0: @class annotations are redundant with TypeScript equivalents

Error: projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(1,1): warning TS0: @interface annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(7,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(14,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(7,1): warning TS0: @class annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/dd-ng-primitives.module.ts(6,1): warning TS0: @class annotations are redundant with TypeScript equivalents

    at Object.<anonymous> (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(1,1): warning TS0: @interface annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(7,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(14,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(7,1): warning TS0: @class annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/dd-ng-primitives.module.ts(6,1): warning TS0: @class annotations are redundant with TypeScript equivalents

Error: projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(1,1): warning TS0: @interface annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(7,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/size.ts(14,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(7,1): warning TS0: @class annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
@implements annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(22,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/resize-notifier/resize-notifier.component.ts(44,3): warning TS0: @type annotations are redundant with TypeScript equivalents
projects/dd-ng-primitives/src/lib/dd-ng-primitives.module.ts(6,1): warning TS0: @class annotations are redundant with TypeScript equivalents

    at Object.<anonymous> (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at C:\PROJECTS\dd-ng-primitives\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

### Desired functionality
Library builded without errors.

### Mention any other details that might be useful
repo: https://github.com/derkachdeveloper/dd-ng-primitives

**Comment by alan-agius4** [comment]
Hi, those JSDocs are redundant and should be removed in order to get your library working.

Redundant JSDocs will cause the build to fail.

**Comment by derkachdeveloper** [comment]
@alan-agius4, it is will be to work follow(next releases)?

**Comment by alan-agius4** [comment]
@derkachdeveloper, I am not quite sure what you meant above. However, if you meant, if this is a bug, that will be solved in the future. No, this is not a bug, and redundant JSDocs needs to be removed in order to get your build working.

I suggest you enable the `no-redundant-jsdoc ` tslint rule. https://palantir.github.io/tslint/rules/no-redundant-jsdoc/

**Comment by alan-agius4** [comment]
Take a look at: https://github.com/angular/angular/issues/19969

**Comment by derkachdeveloper** [comment]
@alan-agius4 , thank you. Close issue.

**Comment by matheusdavidson** [comment]
My solution was change my ```tsconfig.lib.json``` config, 

from this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": true
    ...
    ...
}
```
to this:
```json
"angularCompilerOptions": {
    "annotateForClosureCompiler": false
    ...
    ...
}
```
