### ISSUE TITLE
how to add image in library

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular-cli#11280]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```
in absence of assets folder for library project how I should add an image?
is the new library project support adding images?
### Area
```
- [x] schematics
```

### Versions

- node v9.7.1
- npm v6.1.0
- macOs High Sierra

```
Angular CLI: 6.1.0-beta.2
Node: 9.7.1
OS: darwin x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.0-beta.2
@angular-devkit/build-angular      0.7.0-beta.2
@angular-devkit/build-ng-packagr   0.7.0-beta.2
@angular-devkit/build-optimizer    0.7.0-beta.2
@angular-devkit/build-webpack      0.7.0-beta.2
@angular-devkit/core               0.7.0-beta.2
@angular-devkit/schematics         0.7.0-beta.2
@angular/cdk                       6.2.1
@angular/cli                       6.1.0-beta.2
@angular/language-service          6.0.4
@angular/material                  6.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.0-beta.2
@schematics/angular                0.7.0-beta.2
@schematics/update                 0.7.0-beta.2
ng-packagr                         3.0.1
rxjs                               6.2.0
typescript                         2.7.2
webpack                            4.10.2
```
### Desired functionality
I would like to be able to add images assets to library

**Comment by alan-agius4** [comment]
Assets such as images get tricky to be resolved by the consumer due to the different module formats.

A way to overcome this and include certain assets is to use css background image and embed the assets with `data URIs`

Checkout this document on how to do it: https://github.com/dherges/ng-packagr/blob/master/docs/embed-assets-css.md

**Comment by ofirrifo** [comment]
@alan-agius4 
for some reason when I had my image in the same location of my scss file
and I used `background: url('my-imagr.png');` I get error the file not found so insted I convert my image to base64 and I manually set it in my css and it did work.
thanks for your help.
