### ISSUE TITLE
"stories universal rendering" is not working with angular-cli 6

### ISSUE THREAD

**Issue by walker-walks** [angular/angular-cli#11298]
Hello, guys.
I wanted to create a SSR project whith Angular 6. I followed and instruction [**[stories universal rendering]**](https://github.com/angular/angular-cli/wiki/stories-universal-rendering) but I got few problems. Can you help me?

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
Angular CLI: 6.0.8
Node: 8.9.3
OS: darwin x64
Angular: 6.0.5

### Repro steps
follow the instructions in [**[stories universal rendering**]](https://github.com/angular/angular-cli/wiki/stories-universal-rendering)
I changed few configurations below:

/package.json
```json
"scripts": {
  "build:client-and-server-bundles": "ng build --prod && ng build --prod --app 1 --output-hashing=false",
// to 
    "build:client-and-server-bundles": "ng build --prod && ng build --prod --project=pwa-client --output-hashing=none",
}
```
since --app was uncontinued and now uses --project, and "--output-hashing=false" has changed to "--output-hashing=none"

/server.ts
```typescript
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/server/main.bundle');
// to
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/**MY_APP_NAME**/main');
```
it was not generating "/dist/server/main.bundle" so i tried to change to "my-app-name" and it worked.

### The log given by the failure
new when I run `npm run serve:ssr` it shows the result below.

```terminal
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/marciokojicarvalho/projects/branavi_next/pwa-client/dist/browser/index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at eval (webpack:///./server.ts?:18:21)
    at Object../server.ts (/Users/marciokojicarvalho/projects/branavi_next/pwa-client/dist/server.js:4567:1)
    at __webpack_require__ (/Users/marciokojicarvalho/projects/branavi_next/pwa-client/dist/server.js:20:30)
    at /Users/marciokojicarvalho/projects/branavi_next/pwa-client/dist/server.js:69:18
    at Object.<anonymous> (/Users/marciokojicarvalho/projects/branavi_next/pwa-client/dist/server.js:72:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
```

### Desired functionality
I would like to run Angular6 in SSR mode.

**Comment by sandangel** [comment]
Hi @walker-walks, I think the error was obvious. You are using the wrong path in the server.ts file. You should specify the path to index.html file correctly from the compiled server.js file location, not from the server.ts file.

**Comment by alan-agius4** [comment]
Closing as it was answered above.
