### ISSUE TITLE
 Cannot find name 'FileReplacements'.

### ISSUE THREAD

**Issue by gatimus** [angular/angular-cli#11294]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Versions
node --version v8.11.1
npm --version 6.1.0

### Repro steps
`import { BrowserBuilderSchema } from '@angular-devkit/build-angular';`

### The log given by the failure
node_modules/@angular-devkit/build-angular/src/browser/schema.d.ts(52,21): error TS2304: Cannot find name 'FileReplacements'.

### Desired functionality
Compile w/o error when importing from `@angular-devkit/build-angular`.

### Mention any other details that might be useful
[BrowserBuilderSchema.fileReplacements](https://github.com/angular/angular-cli/blob/012672161087a05ae5ecffbed5d1ee307ce1e0ad/packages/angular_devkit/build_angular/src/browser/schema.d.ts#L52) is type `FileReplacements[]` but that is not a type. There is type [FileReplacement](https://github.com/angular/angular-cli/blob/012672161087a05ae5ecffbed5d1ee307ce1e0ad/packages/angular_devkit/build_angular/src/browser/schema.d.ts#L265) though.

**Comment by Narrator** [comment]
Same issue is in server `node_modules/@angular-devkit/build-angular/src/server/schema.d.ts(75,21): error TS2304: Cannot find name 'FileReplacements'.`

**Comment by phodal** [comment]
Hi, it seems the change not publish in latest version 0.8.1, our CI was broken now.

**Comment by lgavSKOPOS** [comment]
Also having this issue. Has this been fixed yet?
