### ISSUE TITLE
How do I convert ng serve parameters in package.json to equivalent angular.json syntax?

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#11292]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Area
```
- [x ] devkit
- [ ] schematics
```

### Versions
v8.9.4
6.1.0

### Repro steps
1. Start with a package.json file from version 1.7.x that contains one or more of the following lines in the `scripts` section:
```
"start": "ng serve --open --common-chunk --vendor-chunk --extract-css --named-chunks --progress --verbose",
```
2. Upgrade Angular-CLI to version 6.x

3. Attempt to use `npm run start` or manually enter directly the ng serve command shown above and see numerous errors about unrecognized parameters.

### The log given by the failure
Unknown option: '--extractCss'
(many more, as each of the multiple parameters are removed after seeing the 'unrecognized' error)

### Desired functionality
Either or both of the following:

1. Automated conversion tool that converts correctly specified `ng build` and `ng serve` parameters located in package.json scripts section to their equivalent angular.json.  It is not intuitively obvious how to convert to the new  technique.

or

2. Well-documented guidance, including examples, on how to manually convert the above.

**Comment by alan-agius4** [comment]
A full list of options available in `serve` can be found here https://angular.io/cli/serve

Whatever options are not listed there are not supported.
