### ISSUE TITLE
Projects generated by angular cli , do not obey baseUrl for ng e2e

### ISSUE THREAD

**Issue by Caspain** [angular/angular-cli#11293]
Current package.json
   "@angular-devkit/build-angular": "^0.6.5",
    "@angular/animations": "6.0.0",
    "@angular/cli": "6.0.0",
    "@angular/common": "6.0.0",
    "@angular/compiler": "6.0.0",
    "@angular/compiler-cli": "6.0.0",
    "@angular/core": "6.0.0",
    "@angular/forms": "6.0.0",
    "@angular/http": "6.0.0",
    "@angular/platform-browser": "6.0.0",
    "@angular/platform-browser-dynamic": "6.0.0",
    "@angular/router": "6.0.0",

   protractor : "protractor": "~5.3.2",

To solve the current issue, i have to issue the command using the global protractor cli on the specific protractor configuration.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by intellix** [comment]
Related: https://github.com/angular/angular-cli/issues/11089

**Comment by filipesilva** [comment]
Closing as a repro was never provided.
