### ISSUE TITLE
Add a config file like .ngcli or ngcli-conf.js to the generated app

### ISSUE THREAD

**Issue by tapas4java** [angular/angular-cli#113]
Customization is an important factor for any tools to succeed. It would be better if we could add one config file like `.ngcli` or `ngcli-conf.js` so that developer can customize their own work flow.

e.g:
* Directory structure (e.g: src/components/mycomp)
* SASS setup enable/disable
* etc.

**Comment by dancancro** [comment]
Hi Tapas,

I'm not sure whether this is interesting to you, but [here](https://docs.google.com/spreadsheets/d/1482oa_iHp9EcUY_dBFTC0D5VmWxcHTKDDf-nlLDUJok/edit#gid=1274152722) is a study I did of different ways people put configurations/settings into files. Maybe this will help you decide which way you like best. The spreadsheet shows the organization of all sorts of code, but the configuration stuff (I called "settings") are on rows 124-140.

**Comment by cironunes** [comment]
That's true. You are supposed to use the `ember-cli-build.js` to achieve the same goal, but right know the angular-cli isn't so extensible.

**Comment by dvenske** [comment]
I would argue that directory structure is something that angular-cli should be opinionated about and it should probably not be configurable.

The main reason for this is that using something like angular-cli should create a situation where anyone with experience in angular-cli could jump into a project and know exactly where everything is.

**Comment by hansl** [comment]
We're already building an `angular-cli.json` file for route configurations (https://github.com/angular/angular-cli/issues/287). Code generated using that file will live next to your code (for IDE support).

Alternatively, support for SASS/SCSS and other tools are added using the `ng install` command.

I consider this solved indirectly.
