### ISSUE TITLE
Connection drops on ng new command

### ISSUE THREAD

**Issue by RobiFerentz** [angular/angular-cli#1130]
When attempting to use `ng new whateverApp` the printout reaches the installing modules part and then simply stalls. The net connection seems to get blocked and it actually requires a router reboot.
This may be a problem with node itself, rather than this cli, but since it happens consistently, I'm posting it here.

I'm on osx (El Capitan)

ng --version gives this: 

> re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.6
node: 6.2.2
os: darwin x64

**Comment by filipesilva** [comment]
Hm, not too sure of what's happening myself. Can you try installing via npm separately?
```
ng new whateverApp --skip-npm
cd whateverApp
npm install
```

**Comment by RobiFerentz** [comment]
I've tried it again at work and while it takes a while, it manages to finish the setup.
Of course, at work I'm on LAN connection, not wifi, and the connection didn't drop.

I will try your suggesting when at home and see if anything changes.

**Comment by stevenpkent** [comment]
@filipesilva I am seeing this issue also.  I tried your suggested steps  
It works!

One thing I noticed.  And maybe it is fine, not sure.  When I npm installed angular-cli, the ember-cli.json file was added with owner as root.  I looked at the other files in the .config/configstore folder and the owner on them was me.

My info, if you need it
$ ng -v
(node:1483) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.6
node: 6.2.2
os: darwin x64

HTH

**Comment by mrsweaters** [comment]
I'm having hang here when I run `ng new appName`:
```
⠦ Installing packages for tooling via npm
├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

 https://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz
 https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-1.4.0.tgz
 https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz
 https://registry.npmjs.org/align-text/-/align-text-0.1.4.tgz
```

**Comment by filipesilva** [comment]
This problem seems to be related to a new one we had recently, and https://github.com/angular/angular-cli/pull/1250 was the fix. It should also fix this one.
