### ISSUE TITLE
Src path being stripped from imported scss

### ISSUE THREAD

**Issue by dcp3450** [angular/angular-cli#11308]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
```
ngular CLI: 6.0.8
Node: 10.4.0
OS: darwin x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
In my `src/scss/style.scss` I have `~wfk-roboto\roboto.css`. The css has `src: url('fonts/roboto-bold-italic.ttf') format('truetype');` when compiled the `fonts` is removed and the font isn't loaded

### The log given by the failure
No error, the font just doesn't load

### Desired functionality
Am I doing this wrong or is there a current workaround?

**Comment by dcp3450** [comment]
It looks like this doesn't affect something like "material icons" since those fonts aren't in a subdirectory in the package.

**Comment by Brocco** [comment]
FYI, using `~` to reference the root of the project is not officially supported. I would suggest switching to using a relative path for these references.
