### ISSUE TITLE
No NgModule metadata found for 'AppModule' (again)

### ISSUE THREAD

**Issue by martin31821** [angular/angular-cli#11309]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

`node --version: 10.3.0`
`npm --version: 6.1.0`
`ng version`:
```
Angular CLI: 6.0.8
Node: 10.3.0
OS: linux x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

Running on ArchLinux

### Repro steps

ng build and ng build --aot run fine, when I open my compiled website in the browser I get an exception: "No NgModule metadata found for 'AppModule'".

### Desired functionality

I expect to see aot and production builds working.

### Mention any other details that might be useful

I tried the fix recommended in the other bugs (namely adding `main.ts` and `app.module.ts` to `files` in `tsconfig.app.json`). 
While debugging, I discovered something interesting:

When i compile without aot the output looks like this: 
```js
let AppModule = class AppModule {
    constructor(/*redacted*/) {/*redacted*/}
};
AppModule = __decorate([
    Object(_angular_core__WEBPACK_IMPORTED_MODULE_0__["NgModule"])({
        imports: [
            // redacted for readability
        ],
        providers: [
            // redacted for readability
        ],
        bootstrap: [
            // redacted for readability
        ],
    }),
    __metadata("design:paramtypes", [/*redacted*/], AppModule);
```

while the exact same code looks like this when compiled with aot enabled:
```
class AppModule {
    constructor(/*redacted*/) {
      /*redacted*/
    }
}
```
I noticed that typescript does not emit any decorators when compiling with aot.

For the code required to reproduce, please contact me.

**Comment by martin31821** [comment]
I got it fixed. The problem was that I tried to bootstrap my module dynamically. Changing it to `platformBrowser().bootstrapModuleFactory()` did the trick.

**Comment by nezhar** [comment]
Just in case somebody else also encounters this error, make sure you call `platformBrowserDynamic().bootstrapModule(AppModule)` only once, When adding HRM I forgot to remove the old block and ended up with this in my `main.ts`:

```
...
platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.log(err));


const bootstrap = () => platformBrowserDynamic().bootstrapModule(AppModule);
...
```

This will work normally with `ng serve` and also allows to build the app. A non AOT build will also work as expected, however, the AOT build will generate the posted error.
