### ISSUE TITLE
`ng build` does not fail with non-zero exit code when given wrong parameters.

### ISSUE THREAD

**Issue by bert2** [angular/angular-cli#11306]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

```
$ node --version
v9.11.1
```
```
$ npm --version
5.6.0
```
Windows 7

### Repro steps

* Inside your Angular 6 project type `$ ng build --env=foo; echo $?`
* Output will be:
```
Unknown option: '--env'
0
```

### Desired functionality

The exitcode of `ng build` should be non-zero in cases of misuse.

**Comment by clydin** [comment]
This is fixed in master and will be included in the next release.

**Comment by MonsieurBon** [comment]
Is this fixed for `ng test` too?
