### ISSUE TITLE
SyntaxError: Unexpected end of JSON input while parsing near '...","tarball":"https://'

### ISSUE THREAD

**Issue by clowiee** [angular/angular-cli#11311]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```

### Versions

node v8.11.3
npm v6.1.0
Windows 7 x84

### Repro steps

1. When executing `ng new my-app-name`

### The log given by the failure

error: `SyntaxError: Unexpected end of JSON input while parsing near '...","tarball":"https://'`
complete error log:
[2018-06-20T03_52_10_796Z-debug.log](https://github.com/angular/angular-cli/files/2117812/2018-06-20T03_52_10_796Z-debug.log)

### Desired functionality

To successfully create/generate new angular project

### Mention any other details that might be useful

trying to fix this by running the commands below but the error still exist
```
npm cache clean --force
npm cache verify
```

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
