### ISSUE TITLE
It has different ways of expression when click the select between win10 and macOs

### ISSUE THREAD

**Issue by simonchenxy** [angular/angular-cli#11310]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Repro steps

This is the repository source https://github.com/simonchenxy/angular4-Pagination
1). Please get the code from above link.
2). npm install and npm start.

### Mention any other details that might be useful

It has different ways of expression when run it on Win 10 and macOs(Sierra).
I bind a click function 'getCurrentCount()' on select label in 'src/app/pagination/pagination.component.html'.
This function can success when I click the select on Chrome of Win 10.
But it failed on Chrome of macOs(Sierra), because it seems like this function doesn't emit the parameter to father component or maybe it work when the select blur.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
