### ISSUE TITLE
ng new videolib error

### ISSUE THREAD

**Issue by ketulrastogi** [angular/angular-cli#1131]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.6
node: 6.1.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ng new videolib
(node:3484) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
installing ng2
  create .editorconfig
  create README.md
  create src\app\app.component.css
  create src\app\app.component.html
  create src\app\app.component.spec.ts
  create src\app\app.component.ts
  create src\app\environment.ts
  create src\app\index.ts
  create src\app\shared\index.ts
  create src\favicon.ico
  create src\index.html
  create src\main.ts
  create src\system-config.ts
  create src\tsconfig.json
  create src\typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config\environment.dev.ts
  create config\environment.js
  create config\environment.prod.ts
  create config\karma-test-shim.js
  create config\karma.conf.js
  create config\protractor.conf.js
  create e2e\app.e2e-spec.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create e2e\typings.d.ts
  create .gitignore
  create package.json
  create public\.npmignore
  create tslint.json
  create typings.json
Successfully initialized git.
/ Installing packages for tooling via npm
└── (No dependencies)

 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-3484-ae90eac3\registry.npmjs.org\broccoli-viz\-\broccoli-viz-2.0.1.tgz
unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\https-proxy-agent\-\https-proxy-agent-1.0.0.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\binaryextensions\-\binaryextensions-2.0.0.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\bower-endpoint-parser\-\bower-endpoint-parser-0.2.2.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\hoek\-\hoek-2.16.3.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\editions\-\editions-1.1.1.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\esprima-fb\-\esprima-fb-15001.1001.0-dev-harmony-fb.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\escope\-\escope-3.6.0.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\es5-ext\-\es5-ext-0.10.11.tgz
 error reading C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\bower-config\-\bower-config-1.4.0.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\xmlhttprequest-ssl\-\xmlhttprequest-ssl-1.5.1.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\yargs\-\yargs-3.10.0.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\graceful-fs\-\graceful-fs-4.1.4.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\got\-\got-5.6.0.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\hawk\-\hawk-3.1.3.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\xmldom\-\xmldom-0.1.22.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\globals\-\globals-6.4.1.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\xregexp\-\xregexp-3.1.1.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\growly\-\growly-1.3.0.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\handlebars\-\handlebars-4.0.5.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\backbone\-\backbone-1.3.3.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\babylon\-\babylon-5.8.38.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\diff\-\diff-2.2.3.tgz
 unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\angular-cli\-\angular-cli-2.5.0.tgz
 error reading C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\babel-register\-\babel-register-6.9.0.tgz
https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz
 https://registry.npmjs.org/alter/-/alter-0.2.0.tgz
 https://registry.npmjs.org/ansi/-/ansi-0.3.1.tgz
 https://registry.npmjs.org/after/-/after-0.8.1.tgz
 https://registry.npmjs.org/ws/-/ws-1.0.1.tgz
 https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz
 https://registry.npmjs.org/widest-line/-/widest-line-1.0.0.tgz
 https://registry.npmjs.org/walk-sync/-/walk-sync-0.2.6.tgz
 https://registry.npmjs.org/window-size/-/window-size-0.1.0.tgz
 https://registry.npmjs.org/acorn/-/acorn-1.2.2.tgz
 https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz
 https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-3.0.1.tgz
 https://registry.npmjs.org/type-detect/-/type-detect-1.0.0.tgz
 https://registry.npmjs.org/ansi-regex/-/ansi-regex-0.2.1.tgz
 https://registry.npmjs.org/amdefine/-/amdefine-1.0.0.tgz
 https://registry.npmjs.org/ansi-escapes/-/ansi-escapes-1.4.0.tgz
 https://registry.npmjs.org/array-to-error/-/array-to-error-1.1.0.tgz
 https://registry.npmjs.org/arraybuffer.slice/-/arraybuffer.slice-0.0.6.tgz
 https://registry.npmjs.org/archy/-/archy-1.0.0.tgz
 https://registry.npmjs.org/array-equal/-/array-equal-1.0.0.tgz
unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\lodash._basedifference\-\lodash._basedifference-4.5.0.tgz
 https://registry.npmjs.org/inflection/-/inflection-1.10.0.tgz
unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\lru-cache\-\lru-cache-2.7.3.tgz
unzip error C:\Users\Ketul\AppData\Local\Temp\npm-9744-71b6f1e7\registry.npmjs.org\babel-core\-\babel-core-5.8.38.tgz

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Can you try installing npm modules separately?

```
ng new videolib
cd videolib
npm install
```

**Comment by ketulrastogi** [comment]
@filipesilva yes, I installed modules separately using npm install and worked fine. may be problem is in ng new for module installs.

**Comment by filipesilva** [comment]
I'm glad to hear your problem is solved!
