### ISSUE TITLE
How building process takes place in angular 6? 

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [angular/angular-cli#11312]
I'm new one to angular 6.

I know how to build the application but i don't know the inner process happened while taking build.

May i know which bundling system Angular CLI using and Is there necessary to use external bundling system like rollup, browsify, ...

Further i need to add the tree shaking feature in my application.

please assist me

Thanks,
Buhari Mohamed Ismail

**Comment by alan-agius4** [comment]
This is not an issue, Best that you redirect support questions to the gitter channel
https://gitter.im/angular/angular-cli

Thanks.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow ](https://stackoverflow.com/) using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation.](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)

**Comment by BUHARIMOHAMEDISMAIL** [comment]
I raised the same as in gitter and stackoverflow but no one is responding i'm still waiting for the solution.

**Comment by alan-agius4** [comment]
Angular CLI is using webpack under the hook. And tree-shaking is provided out of the box. 

https://github.com/angular/angular-cli/wiki/build

**Comment by Brocco** [comment]
@BUHARIMOHAMEDISMAIL Thanks for the inquiry, the build system currently uses webpack under the hood.
