### ISSUE TITLE
How to change URL while opening a fancybox and revert back URL when closed this fancybox?

### ISSUE THREAD

**Issue by anujanjaan** [angular/angular-cli#11313]
Hi Guys,
I am looking to change the URL whenever fancybox is opened and the URL should get back to its original after closing the fancybox. Any help would be appreciated.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow ](https://stackoverflow.com/) using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation.](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
