### ISSUE TITLE
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump

### ISSUE THREAD

**Issue by Nomitha-95** [angular/angular-cli#11325]
I am getting "npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump" whenever i try to create a new Angular Application.I have refered this "ng new error #11219". But my node and npm version are 10.5.0 and 6.1.0 and i am using windows version 10 (64-bit). Below is the error i am getting

$ ng new my-app
CREATE my-app/angular.json (3548 bytes)
CREATE my-app/package.json (1310 bytes)
CREATE my-app/README.md (1022 bytes)
CREATE my-app/tsconfig.json (384 bytes)
CREATE my-app/tslint.json (2805 bytes)
CREATE my-app/.editorconfig (245 bytes)
CREATE my-app/.gitignore (503 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (631 bytes)
CREATE my-app/src/favicon.ico (5430 bytes)
CREATE my-app/src/index.html (292 bytes)
CREATE my-app/src/main.ts (370 bytes)
CREATE my-app/src/polyfills.ts (3194 bytes)
CREATE my-app/src/test.ts (642 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/styles.css (80 bytes)
CREATE my-app/src/browserslist (375 bytes)
CREATE my-app/src/karma.conf.js (964 bytes)
CREATE my-app/src/tsconfig.app.json (194 bytes)
CREATE my-app/src/tsconfig.spec.json (282 bytes)
CREATE my-app/src/tslint.json (314 bytes)
CREATE my-app/src/app/app.module.ts (314 bytes)
CREATE my-app/src/app/app.component.html (1141 bytes)
CREATE my-app/src/app/app.component.spec.ts (989 bytes)
CREATE my-app/src/app/app.component.ts (207 bytes)
CREATE my-app/src/app/app.component.css (0 bytes)
CREATE my-app/e2e/protractor.conf.js (752 bytes)
CREATE my-app/e2e/src/app.e2e-spec.ts (302 bytes)
CREATE my-app/e2e/src/app.po.ts (208 bytes)
CREATE my-app/e2e/tsconfig.e2e.json (213 bytes)

**npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump**

> node-sass@4.9.0 install C:\Users\lenovo\documents\angular\my-app\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/win32-x64-64_binding.node
Download complete
Binary saved to C:\Users\lenovo\documents\angular\my-app\node_modules\node-sass\vendor\win32-x64-64\binding.node
Caching binary to C:\Users\lenovo\AppData\Roaming\npm-cache\node-sass\4.9.0\win32-x64-64_binding.node

> node-sass@4.9.0 postinstall C:\Users\lenovo\documents\angular\my-app\node_modules\node-sass
> node scripts/build.js

Binary found at C:\Users\lenovo\Documents\angular\my-app\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> @angular/cli@6.0.8 postinstall C:\Users\lenovo\documents\angular\my-app\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1114 packages from 1285 contributors and audited 21861 packages in 265.928s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
warning: LF will be replaced by CRLF in .editorconfig.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in .gitignore.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in angular.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in e2e/protractor.conf.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in e2e/src/app.e2e-spec.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in e2e/src/app.po.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in e2e/tsconfig.e2e.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in package-lock.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.component.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.component.spec.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.component.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/app/app.module.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/browserslist.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/environments/environment.prod.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/environments/environment.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/index.html.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/karma.conf.js.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/main.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/polyfills.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/styles.css.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/test.ts.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/tsconfig.app.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/tsconfig.spec.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in src/tslint.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tsconfig.json.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in tslint.json.
The file will have its original line endings in your working directory.

**Comment by OmarHegazi94** [comment]
the same warning here

**Comment by Rhadamez** [comment]
The same.

**Comment by Nomitha-95** [comment]
Hi while installing Angular CLI: 6.0.8 globally in my system i am getting below npm warn.Did anyone got the same?Is this is the reason why i am getting ***npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump*** while creating new angular application. 

$ npm install -g @angular/cli
C:\Users\lenovo\AppData\Roaming\npm\ng -> C:\Users\lenovo\AppData\Roaming\npm\no           de_modules\@angular\cli\bin\ng

> @angular/cli@6.0.8 postinstall C:\Users\lenovo\AppData\Roaming\npm\node_module           s\@angular\cli
> node ./bin/ng-update-message.js

**npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@an           gular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@           1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}           )**

+ @angular/cli@6.0.8
added 248 packages in 63.666s

**Comment by JheyssonD** [comment]
the same

**Comment by kjmohit** [comment]
same error i'm getting

**Comment by codredd** [comment]
I am getting the same error since a couple of days. doesn't look like someone found a resolution :(

**Comment by dostiharise** [comment]
I guess, I am facing the same error: `npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump`

**Comment by dostiharise** [comment]
Actuall, looks like this is just a warning. 

Its either that I just had to wait for the installation - Or - Upgrading node to the latest version helped I guess.

**Comment by quirogamauricio** [comment]
Guys, that's not an error. That's a warning.

**Comment by Archita21** [comment]
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN notice [SECURITY] ws has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=ws&version=1.1.2 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.3.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] parsejson has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=parsejson&version=0.0.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] tunnel-agent has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=tunnel-agent&version=0.4.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

**Comment by Archita21** [comment]
getting error while creating a project in angular js?
how cn this be resolved

**Comment by juliobrazao** [comment]
Even when I try to skip this warn and start a server for a project I got some another errors.

**Comment by CoolBoi567** [comment]
Guys those are just **warning** and not **errors**..

Your application will work irrespective of those warning. 
Use `ng serve -o` to run your application, it should work fine..

**Comment by Achyuthkodali** [comment]
Looks like no one having the answer for that error.... And of course i'm getting the same error....

**Comment by tcalhounjr** [comment]
It's true that it's only a warning but my npm install is taking a ridiculous amount of time to complete.

**Comment by isaacSandoval** [comment]
it's my first app in angular, but the warning dont generate problems in the future?

**Comment by bahuwang** [comment]
the same.

**Comment by tony254** [comment]
Similar warning. I hope it doesn't affect the app later

**Comment by da45** [comment]
should I abort with ctrl-C ?

**Comment by BobrovSergey** [comment]
@da45 if you want to skip your command - use Ctrl+C
Also get the same warning. Looks like this package is required by some jest or another packages

**Comment by feyex** [comment]
I faced similar problem. It was solved after clearing npm cache.

npm cache clean --force.

This should help

**Comment by briancalma** [comment]
@feyex i am still getting the same warning :npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump.

**Comment by jasonvuriker** [comment]
the same

**Comment by ndembi** [comment]
the same

**Comment by blakeguitar** [comment]
ditto

C:\Users\blake\Documents\Code\Angular>npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.

You have to appreciate the humor emanating from the npm development staff.

I realize this is just a warning, but it is also a distraction. Why is this warning appearing, will there be any ramifications if the warning is ignored, why is there not a more descriptive message referring to a URL where one can glean more information when determining whether or not to ignore the warning! Yes some warnings are just annoying distractions that can be ignored, but sometimes they also cause minor/major issues that result in wasted time and resources when not addressed up front.

My guess is the warning can be ignored, similar to this warning I am also getting when creating a new Angular <project>:

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Also spent some time on one thread regarding this fsevents issue and finally came to the conclusion that the warning should not be displayed when running ng on Windows, but then again I could be wrong. 

Yes warnings are warnings, but they also cause a lot of grief that could be avoided by simply performing a few more checks in the code producing the warning or by providing a more descriptive response action.

Just my 2 cents worth...:)

**Comment by kamssa** [comment]
the same

**Comment by oussama19000** [comment]
go to cmd and type :

**Comment by junavi** [comment]
try           
 https://npm.runkit.com/istanbul-lib-hook

**Comment by sharif210** [comment]
do anyone have answer for that question.I am facing problem project is not getting created because of that error

**Comment by junavi** [comment]
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 , it is just a warning.
try:

$ npm audit fix

I have installed Angular CLI: 6.1.2 not problem in my project 
$ node -v
v10.6.0
$ npm -v
6.1.0
$ tsc -v
Version 3.0.1

**Comment by qsmarkus** [comment]
Just as @blakeguitar has said, it is just a warning. After running npm cache clean --force, try serving your angular project. It should work perfectly.

it worked perfectly.

thanks

**Comment by Enami93** [comment]
try this  : npm i istanbul-lib-hook then npm i

**Comment by wandersonsc** [comment]
As previously mentioned, that is nothing but an **warning** , make sure your npm as well as your CLI  is up to date then you should be fine.

**Comment by MandelaMan** [comment]
i used cmd and run it as administrator then run the following command
"npm install -g istanbul"

works like magic

**Comment by alan-agius4** [comment]
Closing as it's a third party issue which has been solved.
