### ISSUE TITLE
is it a good place to ask help ?

### ISSUE THREAD

**Issue by stann84** [angular/angular-cli#11329]
angular 5 

i just want to ask if is a good place to ask some help about angular and firebase. i m just strarting to dev in angular and i have lot of questions about angular generaly but particulary about version because all tuto are in different versions.
 and after i will ask some help like what is a good way to switch the firebase config from app module to environement.

I tried different things but i m stock in this error
 FirebaseError {code: "app/no-app", message: "Firebase: No Firebase App '[DEFAULT]' 

this part is very confusing

i have  AngularFireModule.initializeApp(environment.firebase), 
but thats dosnt work 
thank you

**Comment by alan-agius4** [comment]
Not really, this place if to report a bug or for feature requests. For support you should post on [StackOverflow ](https://stackoverflow.com/) using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation.](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
