### ISSUE TITLE
production build - 79% chunk modules optimization ModuleConcatenationPlugin takes too much time about 15 minutes

### ISSUE THREAD

**Issue by devwaheed** [angular/angular-cli#11327]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] feature request
it should build just change module or component
```

### Area
```
CLI - Production Build Time

```

### Versions

windows 10 
  npm: 5.6.0
  Angular CLI: 6.0.7
  Node: 9.11.1
  OS: win32 x64
  Angular: 6.0.3

### The log 

 ng build --prod --build-optimizer false  --extract-css false

Date: 2018-06-21T08:08:31.532Z
Hash: e32517fc45f6d4ffb87a
Time: 931576ms
chunk {26} 26.ff311d52ae3f6683da11.js () 324 kB  [rendered]
chunk {scripts} scripts.41924ea69bd9c6533a4e.js (scripts) 160 kB  [rendered]
chunk {0} common.e26c0c0d51d2df5001be.js (common) 25.5 kB  [rendered]
chunk {1} 1.c1e66b858fd6fe88cd5f.js () 26.2 kB  [rendered]
chunk {2} 2.39675380bd944d73df8c.js () 63.9 kB  [rendered]
chunk {3} 3.0e55ac7153f150486005.js () 48.5 kB  [rendered]
chunk {4} 4.0fc0a82d42ed08914306.js () 182 kB  [rendered]
chunk {5} 5.dcc63abe9822069d02c2.js () 928 kB  [rendered]
chunk {6} 6.57403ceb4e9bac30f80a.js () 149 kB  [rendered]
chunk {7} 7.fca98dfcadfcef69ed52.js () 33.6 kB  [rendered]
chunk {8} 8.dbeb2e9e28cdaba862a7.js () 20.8 kB  [rendered]
chunk {9} 9.0af367ceb324729d8c47.js () 56.4 kB  [rendered]
chunk {10} 10.9ef2304e3de2d75be73a.js () 196 kB  [rendered]
chunk {11} 11.73c2164f23e553a1652b.js () 51.9 kB  [rendered]
chunk {12} 12.d8e2d0631bfe09037971.js () 22.1 kB  [rendered]
chunk {13} 13.0816f5547dcd27e84903.js () 34.3 kB  [rendered]
chunk {14} 14.5e0ce628be46963be33d.js () 290 kB  [rendered]
chunk {15} 15.4e4309476f6a7d602620.js () 23.5 kB  [rendered]
chunk {16} 16.9f04f8a035458a6368c9.js () 80.1 kB  [rendered]
chunk {17} 17.906ff37a1e8f96ca025f.js () 153 kB  [rendered]
chunk {18} 18.eff87b68dd7bf0afbcf6.js () 36.2 kB  [rendered]
chunk {19} 19.1d3c8e09928372e2606e.js () 76.8 kB  [rendered]
chunk {20} 20.2f17b3227a81ba891b2e.js () 98 kB  [rendered]
chunk {21} 21.8f5ae5f4b19b78df3e06.js () 129 kB  [rendered]
chunk {22} 22.446e4107a7ffbbf63499.js () 176 kB  [rendered]
chunk {23} 23.cfc03ff4f164d01f9ff3.js () 273 kB  [rendered]
chunk {24} 24.3a08ee0c582e89e49d00.js () 1.14 MB  [rendered]
chunk {25} 25.a0a1308d227d615e218e.js () 3.23 MB  [rendered]
chunk {27} 27.a5538d048b5959c4be46.js () 430 kB  [rendered]
chunk {28} 28.b5978a7d49075f1c7cc7.js () 5.48 kB  [rendered]
chunk {29} 29.fe503eeadeaa97b5e32f.js () 203 kB  [rendered]
chunk {30} 30.b04d92c74e5ba03b88f7.js () 54.9 kB  [rendered]
chunk {31} 31.20d08166c1d5e76a7622.js () 77.8 kB  [rendered]
chunk {32} 32.f0f508b73269000a6f27.js () 192 kB  [rendered]
chunk {33} 33.7afa46ab123eec80fe87.js () 329 kB  [rendered]
chunk {34} 34.17705852fbf5641b34f7.js () 430 kB  [rendered]
chunk {35} 35.fd1a8ed923f531439b07.js () 2.68 MB  [rendered]
chunk {36} 36.d8fc436a241f395a5f65.js () 83.3 kB  [rendered]
chunk {37} 37.946bccd347460824408a.js () 86.3 kB  [rendered]
chunk {38} 38.83377bb86965bc9db216.js () 62.9 kB  [rendered]
chunk {39} 39.9854ec5c58f593a41f1e.js () 101 kB  [rendered]
chunk {40} 40.0ee570e8345b1d732466.js () 229 kB  [rendered]
chunk {41} 41.27fe71be8f0672995a17.js () 121 kB  [rendered]
chunk {42} 42.3bdc9d570485102f4284.js () 701 kB  [rendered]
chunk {43} 43.1af0b29b5b487403e483.js () 4.95 MB  [rendered]
chunk {44} 44.aa7620d0e34da38376b3.js () 61.4 kB  [rendered]
chunk {45} 45.ba683f48c5edd9639d5e.js () 648 kB  [rendered]
chunk {46} 46.07755939e3ae0bc7fc73.js () 497 kB  [rendered]
chunk {47} 47.7baba17226a3fecf8f1f.js () 476 kB  [rendered]
chunk {48} runtime.9f7f2f6ec0b15f30e75f.js (runtime) 3.07 kB [entry] [rendered]
chunk {49} styles.af329127296b33f62b16.js (styles) 122 kB [initial] [rendered]
chunk {50} polyfills.42605b2f1d92fab49545.js (polyfills) 59.7 kB [initial] [rendered]
chunk {51} main.da65fcdb5fd9f2cb260c.js (main) 2.08 MB [initial] [rendered]

### Desired functionality

compilation should be fast on large projects. it should build only changed module(s) in production mode. it works with ng build --watch mode  without --prod flag but not in production mode.

### Mention any other details that might be useful

I have project of containing almost 50 modules. Its production build time 15 minutes and it takes too much time on chunk modules optimization ModuleConcatenationPlugin.

**Comment by clydin** [comment]
Node.js has a known performance issue with versions greater than 8.9.4 and less than 10.0 that greatly affects the performance of webpack.  Please try upgrading to Node.js 10+.

**Comment by devwaheed** [comment]
I've installed Node.js v10.5, and it does not improve build time, it still taking almost 15 minutes.

**Comment by devwaheed** [comment]
It would be nice, if like
for dev build
ng build --watch just compile the changed or modified module(s)
and for Production build
ng build --prod --watch this should compile only changed or modified module(s).

Our company uses Angular for all Application. Angular is default choice for building application for us.
We deploy many  times in a day.

**Comment by williangd** [comment]
I have the same problem with ModuleConcatenationPlugin. This problem did not occur in angular 5 and angular/cli 1.7.x.

**Comment by Sevensnake** [comment]
I have the same problem with Angular 6.7

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

Another thing I'd recommend is increasing the memory limit as described in https://github.com/angular/angular-cli/issues/5618#issuecomment-450151214.
