### ISSUE TITLE
This domain is not registered with TinyMCE Cloud. Get a free API key to disable this message

### ISSUE THREAD

**Issue by luckFine** [angular/angular-cli#11326]
Can you advise on how to use the API KEY to remove the “This domain is not registered with TinyMCE Cloud. Get a free API key to disable this message.” message?
<img width="834" alt="2018-06-21 3 33 09" src="https://user-images.githubusercontent.com/24777461/41704292-709fce68-7568-11e8-972b-14c5bc288658.png">

**Comment by Brocco** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
