### ISSUE TITLE
Annoying autoprefixer warnings

### ISSUE THREAD

**Issue by iamimbohacker** [angular/angular-cli#11333]
Imagine the biggest level of not giving a **** about something. This is me about IE support. I don't wish to see this messages! How to disable it? 
# IE 9-11 is commented in browserlist file

WARNING in ./src/app/components/create/create.component.css
(Emitted value instead of an instance of Error) autoprefixer: C:\Users\imbohacker\Documents\GitHub\imboapp\src\app\components\create\create.component.css:165:35: auto-fill value is not supported by IE

**Comment by gethinoakes** [comment]
I'd like to know the answer for this also. I have browserlist settings in my package.json to not include ie or ie_mob but it doesn't remove these warnings.

**Comment by marcorosi** [comment]
i had the some issue, adding this .browserslistrc in project root solved the problem for me
(i'm using @angular-devkit/build-angular": "0.7.2")

```
# Browsers that we support
last 1 version
> 5%
not dead
not ie > 1
not ie_mob > 1
```

**Comment by gethinoakes** [comment]
I can confirm that upgrading to the latest version has fixed these autoprefixer warnings showing 👍

**Comment by filipesilva** [comment]
Using a browser config as described by @marcorosi is the preferred way of addressing these warning. New project should come with this file.

**Comment by nazarkryp** [comment]
@filipesilva why have you closed that issue?
Project generaeted by **Angular CLI** has project has 'browserslist' file. Which has **EXCLUDED** IE as well `# IE 9-11`.
Why do people need to add some other file to handle that problem.

**Comment by BenRacicot** [comment]
CLI 6.2.1 I'm getting the error 
```
WARNING in ./scss/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./scss/styles.scss)
(Emitted value instead of an instance of Error) autoprefixer: /scss/breakpoints/_base.scss:84:8: grid-auto-rows is not supported by IE
```
with the browserlist config:
```
last 1 version
> 5%
not dead
not ie > 1
not ie_mob > 1
```

**Comment by ufollettu** [comment]
> CLI 6.2.1 I'm getting the error
> 
> ```
> WARNING in ./scss/styles.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./scss/styles.scss)
> (Emitted value instead of an instance of Error) autoprefixer: /scss/breakpoints/_base.scss:84:8: 
> grid-auto-rows is not supported by IE
> ```
> with the browserlist config:
> 
> ```
> last 1 version
> > 5%
> not dead
> not ie > 1
> not ie_mob > 1
> ```

Hi, did you solve this? I have the same warning

**Comment by StevenSwitten** [comment]
We've managed to suppress these warnings by putting:
`/* autoprefixer: off */`
before each line that generated a warning in our scss files

**Comment by BenRacicot** [comment]
Just updated the CLI to `7.0.2` and the warning seems to be gone (same config as my previous comment) :)

**Comment by johnhamm** [comment]
Works using Angular CLI 7.1 and modifying the src/browserslist file to:
```
> 0.5%
last 2 versions
Firefox ESR
not dead
not ie > 1
not ie_mob > 1
```
