### ISSUE TITLE
Provide a way to unhook a particular page from ng serve's autoreload mechanism

### ISSUE THREAD

**Issue by earshinov** [angular/angular-cli#11332]
### Bug Report or Feature Request
```
- [ ] bug report
- [x] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

Applicable to any Angular version and any environment.

### Desired functionality

Sometimes it is useful to keep a page as a reference, for example during layout adjustments. However, if a page is served by `ng serve`, it will automatically reload as soon as any change is made. I would like to have a way of preventing a particular page from reloading, basically unhook it from the angular's autoreload mechanism. A command to be executed in browser developer tools (like `ng.probe`) would be very welcome.

**Comment by earshinov** [comment]
Interestingly enoug, in Chrome one may use `onbeforeunload` as a workaround. Just execute in DevTools console:

```
window.onbeforeunload = () => false;
```

This works because Chrome fires `beforeunload` even if page location change is triggered programmatically. Tested in Chrome 68.0.3440.106.

Does not work in Firefox, though (Firefox 61.0.2).

**Comment by clydin** [comment]
Page reloading is currently controlled by the `webpack-dev-server`.  A feature request for that project may be useful if this request is still needed.
As an alternative the ng serve process can be stopped and then restarted on a different port.  The old page should stay as-is and the new serve process can be used to continue development.
This feature request is currently outside the scope for the CLI.  However, if there is more interest by the community in the future, this may be reconsidered for inclusion.
