### ISSUE TITLE
Prod build error Assignment to constant variable when using object rest.

### ISSUE THREAD

**Issue by olaf89** [angular/angular-cli#11348]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
```

### Versions
Cli 6.0.7, was working on 1.7.4

### Repro steps
App code
```
const { id, ...data } = action.payload;
      return {
        data: state.data,
        requests: {
          ...state.requests,
          [id]: {
            status: 'init',
            hash: hashRequestData(data)
          }
        }
      };
```

Output

```
const n = e.payload , {id: i} = n, o = r(n, ["id"]);
                    return {
                        data: t.data,
                        requests: Object.assign({}, t.requests, {
                            [i]: {
                                status: "init",
                                hash: (o = o,
                                a.sha3(JSON.stringify(o)))
                            }
                        })
                    }
```

Outputted code throws error Assignment to constant variable.
problem is with line hash: (o = o,
cause o (data in original example is contant)

### The log given by the failure
Assignment to constant variable

### Desired functionality
No errors in prod build

**Comment by clydin** [comment]
This was due to defects in the underlying optimizer/minifier (uglify-es).  CLI 7.0 (prerelease versions available) has switched to using a new and maintained minifier named terser which should solve the problem illustrated above.  If you are still encountering the issue with 7.0+ please let us know.
