### ISSUE TITLE
Pollyfills.ts not included in main.ts

### ISSUE THREAD

**Issue by jforjava1981** [angular/angular-cli#11356]
### Bug Report or Feature Request (mark with an `x`)
- [x] bug report -> please search issues before submitting
- [ ] feature request

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

Angular-cli 6.0.8.

### Repro steps

Remove pollyfills entry from angular.json. as  pollyfills.ts
is in src folder it should be included in generated main.ts 
file. But it doesn't get included.

### Desired functionality
When pollyfills entry is not present in angular.json and pollyfills.ts
is present in src folder which is given as folder to generate 
the bundles from. It (pollyfills.ts) should be included in main.ts bundle.

**Comment by alan-agius4** [comment]
Having a typescript file in the ‘src’ folder doesn’t mean it gets bundled.

For a file to get included in the compilation and bundled it has to be referenced from a file that is referenced in main.ts as the main.ts is the entrypoint and only files that are resolved from main.ta or it’s children will be included in the compilation and eventually bundle.
