### ISSUE TITLE
Add Jest and Puppeteer as two new options to Angular-CLI

### ISSUE THREAD

**Issue by HamedFathi** [angular/angular-cli#11352]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Versions
Angular CLI: 6.0.8
Node: 10.1.0
OS: Win 10

### Desired functionality

Make unit testing possible with [Jest](https://facebook.github.io/jest/) instead of Jasmine.
Make E2E testing possible with [Puppeteer](https://github.com/GoogleChrome/puppeteer) instead of Protractor.

### Mention any other details that might be useful
for now no way to doing this. [Jest Puppeteer](https://github.com/smooth-code/jest-puppeteer) and [jest-preset-angular](https://github.com/thymikee/jest-preset-angular) have two different and unmergeable `presets` so we can not use them together. I think Angular-CLI team can do this as an option for Angular world. 

Please make this happen.

**Comment by Nick0n** [comment]
Yes, please!

**Comment by Waterstraal** [comment]
Just a heads up that the new Vue CLI 3.0.0 has configurable options for unit and e2e testing, much like you propose:

>In addition, there are many optional integrations that you can mix and match when you create a new project, such as:
> - [...]
>- Unit Testing via Jest or Mocha
>- E2E Testing via Cypress or Nightwatch

https://medium.com/the-vue-point/vue-cli-3-0-is-here-c42bebe28fbb

It would be nice if Angular Cli would support alternatives as well. Personally, I prefer e2e testing with [Cypress](https://www.cypress.io/) or [Testcafe](https://devexpress.github.io/testcafe/) instead of Puppeteer. So maybe add multiple options in the cli?

**Comment by michaeljota** [comment]
I think this could start with Jest first, and after that adds the others. Having first class support to Jest from Angular team would be huge for the usage of that Framework.

**Comment by dereklin** [comment]
You can use jest with nrwl/nx.  I am interested in knowing how to swap out protractor with puppeteer for e2e.

**Comment by alan-agius4** [comment]
Closing this as this is not currently in the CLI roadmap and as mentioned above there are already other alternatives.

**Comment by Waterstraal** [comment]
> You can use jest with nrwl/nx. I am interested in knowing how to swap out protractor with puppeteer for e2e.

This is a request to get support for Jest in Angular CLI, I don't see what it has to do with nrwl/nx. 

> Closing this as this is not currently in the CLI roadmap and as mentioned above there are already other alternatives.

What do you mean by alternatives?

**Comment by michaeljota** [comment]
> What do you mean by alternatives?

By alternatives, he means that though it's not officially supported, it have tools that allow the integration _kind of_.

https://github.com/meltedspark/angular-builders/tree/master/packages/jest

However, I would like to mention that currently there is no way to override the Angular CLI file generator per file basis. So, you have to manually rewrite the test for then to fit better with Jest.
