### ISSUE TITLE
Unable to use custom tslint formatters after update to angular (cli) 6

### ISSUE THREAD

**Issue by viliks** [angular/angular-cli#11361]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> regression
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

"angular/cli": "6.0.8"
"angular-devkit/build-angular": "0.6.8"
"angular": 6.0.6

### Repro steps

installed npm package
"tslint-teamcity-reporter": "2.0.0"

run 
ng lint project_name --format=tslint-teamcity-reporter

### The log given by the failure

Schema validation failed with the following errors:
  Data path ".format" should be equal to one of the allowed values.

### Desired functionality

ng lint should use custom formatter, as states e.g. in #5253

**Comment by ArtturiSipila** [comment]
This is still not working for me. Trying to use tslint-teamcity-reporter. Using Angular CLI 6.1.2 same reporter version as in original issue (2.0.0)
Gives me
Data path ".format" should be equal to one of the allowed values.
