### ISSUE TITLE
ng error Cannot load module 'expand-range'

### ISSUE THREAD

**Issue by vmax109** [angular/angular-cli#11363]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x ] devkit
- [ ] schematics
```

### Versions
npm --version
6.0.1
node --version
v8.11.2

### Repro steps
After installing Angular-cli latest version 
npm install -g @angular/cli
then ng version says ok installed version 6
Logout from Windows 10
Login again on Windows 10 then run CMD
ng version or any other ng command gives an Error (see log below)
Uninstall/reinstall angular-cli OK
Logout/Login error again 
This happens every day

### The log given by the failure
>ng version
module.js:549
    throw err;
    ^

Error: Cannot find module 'expand-range'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\......\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\braces\index.js:14:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by Brocco** [comment]
This appears to be an issue with your installation. Can you please try these steps and report back?

```
npm uninstall @angular/cli -g
npm cache clean
npm install @angular/cli -g
ng version
```

Thanks!

**Comment by vmax109** [comment]
Hi Mike

Thank you for answering.
I already did what you’re suggesting.
The problem occurs after I leave the office whit a logoff and next morning I get back and login again.
So every day I have to do what you are suggesting to repair the installation.
I would like to resolve this issue to avoid repairing it every day.

Thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
