### ISSUE TITLE
angular Not suitable for the front end, only suitable for background management ? 

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular-cli#1136]
Angular to do the background management program is very good

But it is not suitable for the front end, because it is too big

i used angular-cli

Generated file is too large

1-2MB

if i used jquery, just 100KB

The official did not provide a very good compression program, a house, no matter how beautiful you decorate the inside, if the appearance is very ugly, very few people live in

I hope official can provide very good compression scheme, to dispel the concerns of us, let each of us can proceed to use it

Many times, I am hesitant, want to change jQuery to do my website front end

I love angular, and use it to do the management interface

**Comment by iloveyo123u1** [comment]
ng s -prod    Generated file is too large    1-2MB

**Comment by kylecordes** [comment]
@iloveyo123u1 This is something to evaluate after these critical upcoming improvements are in place:

* Build-time template compiler, which will reduce how much of Angular needs to be shipped at all.
* Tree shaking during the production build process. There are multiple paths to do this.

Once these things are working, smoothly, out of the box using CLI, we will all benefit greatly with reasonably compact production assets with almost no effort.  But there is work still to be done by both the core Angular team and the CLI team... but I think those groups wisely do not promise dates or feature details before they ship.

**Comment by filipesilva** [comment]
jQuery and Angular 2 have two different usecases. If what you need is a very lightweight library for simple html manipulation, then jQuery might be better suited for you.

The challenges of single page apps often call for more powerful frameworks and that scenario is where Angular 2 shines. 

For instance, a marketing site might be very well just need jQuery whereas your main application, thousand of lines long, is made much more maintainable and scalable via the use of Angular 2.

That being said, the upcoming offline compiler will help immensely with payload size - at ngconf a total of 50-60kb was the total payload of an hello-world type app with Angular 2. 

@kylecordes currently the CLI already does tree shaking on production builds.

**Comment by kylecordes** [comment]
@filipesilva I see Rollup in the dependencies - I assume that is being used for this? Is there a way to flip it off for a build, to see how much benefit is obtained? Obviously these numbers reported there (I am at 800KB for main.js on a tiny example app with "-prod" are not yet in the range discussed at the ng-conf talks and elsewhere.

**Comment by filipesilva** [comment]
We currently use [SystemJS Builder](https://github.com/systemjs/builder), which performs tree shaking, for bundling when users do `ng build -prod`.

For a payload as small as seen in ng-conf the offline compiler is needed. We ran some tests with the CLI and the payload was reduced to similar sizes, but it's not yet ready for general availability.
