### ISSUE TITLE
@angular-devkit/build-angular:server commonChunk and vendorChunk options do not work

### ISSUE THREAD

**Issue by amir-zahedi** [angular/angular-cli#11371]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
`@angular-devkit/build-angular: 0.7.0-rc.0`
`@angular-devkit/build-ng-packagr: 0.7.0-rc.0`
`@angular/cli: 6.1.0-rc.0`

I need the `@angular-devkit/build-angular:server` to build a chunked server app rather than one giant main.js bundled file as my project is a sizeable one and the CI process struggles to keep up with the server side app.
I can see the options are clearly there
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/server/schema.d.ts

But turning  commonChunk and vendorChunk flags on has no effect to the output of the build process although some of those options clearly work e.g. sourceMap and verbose options.

This is my angular.json server configuration
` "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "optimization": true,
            "outputHashing": "none",
            "sourceMap": false,
            "vendorChunk": true,
            "vendorSourceMap": true,
            "commonChunk": true,
            "verbose": false,
            "extractLicenses": true,
            "outputPath": "dist/apps/sociall/server",
            "main": "apps/sociall/src/main.server.ts",
            "tsConfig": "apps/sociall/src/tsconfig.server.json"
          },
          "configurations": {
            "server-default": {
              "fileReplacements": [
                {
                  "replace": "apps/sociall/src/environments/environment.ts",
                  "with": "apps/sociall/src/environments/environment.server.ts"
                }
              ]
            }
        }`

And this is the associated tsconfig files for the sever app:
tsconfig.server.json:
`{
  "extends": "../tsconfig.app.json",
  "compilerOptions": {
    "module": "commonjs"
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
}
`
tsconfig.app.json:
`{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../dist/out-tsc/apps/sociall",
    "module": "es2015"
  },
  "include": [
    "../../**/*.ts"
  ],
  "exclude": [
    "**/*.spec.ts",
    "src/test.ts"
  ]
}`

### Desired functionality
Getting chunked files as the output of the server app rather than single large js file containing everything. In my case (and imagine many other projects) the octopus deploy machine runs a variable replacement tasks on the output of the cli build and as it happens the ~15MB bundle size crashes the process. It's reasonable to expect a 15 MB file processing not to crash your server given the good resources allocated and we have raised this with Octopus as well but also reasonable to have the option of breaking that large bundle into pieces if need be.
### Current Behaviour
Single main.js file is created the holds the entirety of the project

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
