### ISSUE TITLE
Base URL "./" is not acceptable while I build a npm package project.

### ISSUE THREAD

**Issue by ParitoshikPaul** [angular/angular-cli#11377]
In that case dist should go inside the projects/my-eg-project directory not "./"

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

**Comment by alan-agius4** [comment]
We need more detail about this.

Can we have a small reproduction? as there is an integration test with uses ` "baseUrl": "./",`
https://github.com/angular/angular-cli/blob/master/tests/%40angular_devkit/build_ng_packagr/ng-packaged

**Comment by Brocco** [comment]
Closing as the issue template was not followed (actually no content at all).
