### ISSUE TITLE
Angular v6 - CLI - Wiki - CI Stories - wrong commands

### ISSUE THREAD

**Issue by scycer** [angular/angular-cli#11379]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] Wiki
```

### Repro steps
This wiki is out of date: https://github.com/angular/angular-cli/wiki/stories-continuous-integration

```
Now you can run the following commands to use the --no-sandbox flag:

ng test --single-run --no-progress --browser=ChromeNoSandbox <---THIS LINE
ng e2e --no-progress --config=protractor-ci.conf.js
```

### Desired functionality
I think the command should be as follows:
```
Now you can run the following commands to use the --no-sandbox flag:

ng test --watch=false --no-progress --browsers=ChromeNoSandbox <---THIS LINE
ng e2e --no-progress --config=protractor-ci.conf.js
```

**Comment by itamark** [comment]
This is valid.
Tried to run the original command and got:
`Unknown option: '--singleRun'`

**Comment by alan-agius4** [comment]
The command argument should be `--single-run`

**Comment by alan-agius4** [comment]
the correct command in this case would be
