### ISSUE TITLE
ng serve detects change whenever I open the file in Atom Editor

### ISSUE THREAD

**Issue by darron1217** [angular/angular-cli#11378]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

Windows 10
node v8.11.3
npm 5.6.0
@angular/cli@1.7.4

### Repro steps

1. Run `ng serve`
2. Open file in Atom Editor (Preview open)
3. See browser is reloading...

### The log given by the failure

No error

### Desired functionality

Just opening a file should not be treated as a change!

### Mention any other details that might be useful

None

**Comment by Brocco** [comment]
Just a hunch here, but I believe that the editor is touching the file in some way that is triggering the change.

A simple test would be to open a file not being watched by the CLI and see if the update timestamp on the file is changed.

**Comment by clydin** [comment]
This appears to be an issue with the editor in question.  `ng serve` receives notifications of changes from the operating system itself.
