### ISSUE TITLE
Angular BuildOptimizer and webpack 4

### ISSUE THREAD

**Issue by josephliccini** [angular/angular-cli#11370]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

Node 8.9.1
Windows 10

### Repro steps

Hi!

I am using an ejected webpack config, and one of the warnings that's popped up is coming from the use of `@angular-devkit/build-optimizer`.

```js
// module.rules:
                {
                    test: /(\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
                    use: isDebug ? '@ngtools/webpack' : [
                        {
                            loader: '@angular-devkit/build-optimizer/webpack-loader',
                            options: {
                                sourceMap: true
                            }
                        },
                        '@ngtools/webpack'
                    ]
                },
```
```js
// plugins:
[
    //...
    new PurifyPlugin()
]
```

### The log given by the failure

It seems that the `PurifyPlugin` isn't upgraded for webpack 4:
```
(node:29548) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

### Desired functionality

This plugin be upgraded for webpack 4

**Comment by clydin** [comment]
The purify plugin is no longer needed with webpack 4 and will be removed in a future major release.

**Comment by josephliccini** [comment]
Great thanks!!

Does the same go for the webpack loader from the same package?

**Comment by josephliccini** [comment]
Sounds good.  Thanks! 👍
