### ISSUE TITLE
ng test Unknown option `--reporters`

### ISSUE THREAD

**Issue by Vaelor** [angular/angular-cli#11376]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
- [x] Don't know
```

### Versions
```
$ ng --version

Angular CLI: 6.0.8
Node: 10.4.1
OS: linux x64
Angular: 6.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/json-schema              1.2.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
ng-packagr                        2.4.1
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
Run ng test with the `--reporters` option. This worked on previous versions and is now gone.

### The log given by the failure
`Unknown option: '--reporters'`

### Desired functionality
At least a migration guide to what use instead - I have not found any info on the removal on the releases page (which serves as the changelog).
Between releases this option was just removed:
[Diff for ng test wiki](https://github.com/angular/angular-cli/wiki/test/_compare/88920277bc85fe50409accd2237f059403ed38ef...1cf783837c392f5fadc7286e1fb28220b9a1b507)

**Comment by Brocco** [comment]
I believe that reports now need to be configured within your karma file.

**Comment by mgol** [comment]
This issue in tandem with #11385 made my team unaware we've not been running unit tests in CI for some time.

**Comment by Vaelor** [comment]
@Brocco It was nice to have for CI - just calling with a specific reporter thats easy to parse, while locally the one configured in karma was used (or a dev could use another installed reporter locally)
Now this would mean to set up some kind of environment which I need to use in the karma config.
I also couldn't find a hint on why it was removed.

**Comment by aarjithn** [comment]
Similarly `ng test --sourcemaps=false` is returning `Unknown option: '--sourcemaps'`. -sm doesn't work too. Strangely, error is `Unknown option: '-s'`

**Comment by KellyR-STCU** [comment]
Would also like to know the deal with this..What is the correct way to do this now..?

**Comment by maccurt** [comment]
Yes, why mess with this? Is there some documentation on what to do now or why it was removed?

**Comment by lundn** [comment]
Hopefully someone can answer this?

**Comment by lsuarez5280** [comment]
Adding to the chorus. Would be much simpler to replace my progress and kjhtml runners with junit in the CI test run scenario via command line argument.

**Comment by joashmusyoka** [comment]
I also was using the --reporters options for running unit test in a CI environment. Got surprised it was removed.
