### ISSUE TITLE
Error IE11 (polyfill)

### ISSUE THREAD

**Issue by haengjin** [angular/angular-cli#11384]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

linux
node v8.9.4
npm 5.6.0
"@angular/cli": "~6.0.5",
"@angular/compiler-cli": "^6.0.3",

### The log given by the failure

I run "ng serve" and open page on ie11. I got the error.
(it is working on chrome)

this is problem line (runtime.js-bootstrap)
var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);

error message 
SCRIPT438: Object doesn't support property or method 'bind'

### Mention any other details that might be useful

I uncomment in polyfills.ts
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
import 'classlist.js'
import 'core-js/es6/reflect';
import 'core-js/es7/reflect';
import 'core-js/es7/array';

network loading order
runtime.js > polyfills.js > styles.js > scripts.js > vendor.js > main.js

and I should open site on compatibility view 
(User always check Display intranet sites in Compatibility View)

**Comment by haengjin** [comment]
solve myself.

I added code to index.html
<meta http-equiv="X-UA-Compatible" content="IE=edge">

**Comment by clydin** [comment]
Closing as resolved.

**Comment by mnick86** [comment]
@clydin what did you do to solve the issue?

**Comment by haengjin** [comment]
@mnick86  @rk-ravikiran 
I added it in <head> tag

`<meta http-equiv="X-UA-Compatible" content="IE=edge">`

**Comment by mubinahmed** [comment]
Same setup, but didn't work for me on IE11. Any other solution?

**Comment by prabagarane** [comment]
> Same setup, but didn't work for me on IE11. Any other solution?

i am also facing the same issue, Can you please post the solution?

**Comment by sumitcodename47** [comment]
Worked like a charm..!
Thanks @haengjin

**Comment by FF128** [comment]
Thanks @haengjin. Still working now.
