### ISSUE TITLE
Ng update @angular/cli Error: connect ECONNREFUSED 

### ISSUE THREAD

**Issue by hamzahamidi** [angular/angular-cli#11386]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

I'm trying to update angular 5 project to v6. I installed first  angular-cli v6. Then I run the following command:
```
$ ng update @angular/cli
Your global Angular CLI version (6.0.8) is greater than your local
version (1.7.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 104.18.94.96:80
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```

### Repro steps

1- Start from an angular v5 project
2- Install angular cli v6
3- Run the command $ ng update @angular/cli

**Comment by LeoUrzua** [comment]
Have your try:
```
npm uninstall --save-dev @angular/cli
npm install --save-dev @angular/cli@latest
```
?

**Comment by hamzahamidi** [comment]
It was just an error from our Proxy. Im closing this issue.

**Comment by EsmaeilSheikhali** [comment]
ng update command  ignore .npmrc configuration file. You need to manually set the proxy in your current session.
e.g.

set proxy=http://ip:post
set http_proxy=http://ip:post
set httpa_proxy=http://ip:post
