### ISSUE TITLE
Header Title won't change

### ISSUE THREAD

**Issue by shinkaze21** [angular/angular-cli#11397]
### Versions

Angular CLI: 1.7.3
Node: 8.9.4

### IOS Version
iPhone 6S Plus, iOS 10.3.1

### Repro steps

1.  ng build --prod --aot --build-optimizer --no-sourcemap -bh /project1/
2. deploy on server
3. Access from mobile apps
4. header title won't change

### Desired functionality

Header title change

### Mention any other details that might be useful

I have apps that call my webview, when I test it on iphone 6s plus, that header title won't change when i move to another page, ex: I have Electricity and Installment page. Default page title is "**TEST**", when I go to Electricity or Installment page, that pages header title won't change.
I have tried using `document.title = 'Electricity'`.
When I try on iphone 5s, the web title comes up.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
