### ISSUE TITLE
Add option to output styles inline

### ISSUE THREAD

**Issue by filipbech** [angular/angular-cli#11395]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Desired functionality
It would be cool if there was a build-option that would take the processed/minified css and put it inline in a <style>-element in index.html instead of as a seperate file.
Useful when it doesn't change so often, and the styles are limited.

Rob asked me to make a Feature-request... https://twitter.com/robwormald/status/1012084975766626304

**Comment by christianliebel** [comment]
Useful for critical/“above-the-fold” CSS. Maybe it’s also possible to process the contents of a `style` tag in `src/index.html`?

**Comment by slavoroi** [comment]
What is the status with this ticket?
It will be amazing if we could have an option:
"styles": [
              "src/styles.scss"
            ],
"inline-styles": [
              "src/inline-styles.scss"
            ]
And it will add the styles in the index.html inline in the head with
 ng build ---prod.

**Comment by naveedahmed1** [comment]
I would also suggest adding `inline` and `preload` options in styles in `angular.json` file

```
"styles": [
      { "input": "src/critical-path-styles.scss", "inline": true },
      { "input": "src/lazy-styles.scss", "preload": true }
  ]
```

With above settings, Angular CLI should inline the contents of `critical-path-styles.scss` in head tag, and it should generate `<link href="/lazy-styles.96106fab.css" rel="preload" as="style" onload="this.rel='stylesheet'">` for `lazy-styles.scss`.

**Comment by spock123** [comment]
Hi, is there any hopes of this ever becoming a feauture?
Running lighthouse tests just gives red lights all over because of this. It's a pretty common thing to inline resources and it would be a great cli feature.

I would add that inlining the main bundle would also be a great feature.

Thanks again

**Comment by alan-agius4** [comment]
Hi,

We did an RFC for this see: https://github.com/angular/angular-cli/issues/18730.

In the prerelease version of Angular CLI v11 inlining of fonts is already available, other parts of the RFC are scheduled to be available in 11.1.

**Comment by spock123** [comment]
> Hi,
> 
> We did an RFC for this see: #18730.
> 
> In the prerelease version of Angular CLI v11 inlining of fonts is already available, other parts of the RFC are scheduled to be available in 11.1.

Yeah I actually heard Minko mention it on the latest Angular podcast - I'm so happy - this is YUUGE guys!
Thank you so much

**Comment by naveedahmed1** [comment]
Amazing work @alan-agius4 @clydin 👍

**Comment by spock123** [comment]
I'm gonna pour myself a gin/tonic and celebrate this. Thank you @alan-agius4 !
