### ISSUE TITLE
Error installing @angular/cli on Windows 10

### ISSUE THREAD

**Issue by ashzu** [angular/angular-cli#11406]
When I try to install @angular/cli, I get the following error:
```
npm install -g @angular/cli
npm ERR! code EINTEGRITY
npm ERR! sha512-p5TCYZDAO0m4G344hD+wx/LATebLWZNkkh2asWUFqSsD2OrDNhbAHuSjobrmsUmdzjJjEeZVU9g1h3O6vpstnw== integrity checksum failed when using sha512: wanted sha512-p5TCYZDAO0m4G344hD+wx/LATebLWZNkkh2asWUFqSsD2OrDNhbAHuSjobrmsUmdzjJjEeZVU9g1h3O6vpstnw== but got sha512-E5VK7nmVCgoG5n2pXQ3NJohIuTRUpth/eK0i3mCUcR3+sfTN3SOSNxjIyxNTgiAzRYAk03ftJZ2C0qZqiQynBA==. (625272 bytes)


```

```

```

### Versions

node --version 8.11.3
npm --version 5.6.0
Windows 10

### Repro steps

npm install -g @angular/cli

### Desired functionality

Angular CLI installs

**Comment by Emeryao** [comment]
That is your network issue in most instances

**Comment by ashzu** [comment]
My network is ok. I've tried installing it several times now but it keeps stalling each time on the below package:

**npm install -g @angular/cli
[            ......] / extract:rxjs: sill pacote rxjs@https://registry.npmjs.org/rxjs/-/rxjs-6.2.1.tgz extracted to C:\**

And then throws the error:

npm ERR! code EINTEGRITY
npm ERR! sha512-p5TCYZDAO0m4G344hD+wx/LATebLWZNkkh2asWUFqSsD2OrDNhbAHuSjobrmsUmdzjJjEeZVU9g1h3O6vpstnw== integrity checksum failed when using sha512: wanted sha512-p5TCYZDAO0m4G344hD+wx/LATebLWZNkkh2asWUFqSsD2OrDNhbAHuSjobrmsUmdzjJjEeZVU9g1h3O6vpstnw== but got sha512-E5VK7nmVCgoG5n2pXQ3NJohIuTRUpth/eK0i3mCUcR3+sfTN3SOSNxjIyxNTgiAzRYAk03ftJZ2C0qZqiQynBA==. (625272 bytes)

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by patrick-tingson** [comment]
I encounter this when trying to npm install. 
Try to run as administrator the cmd and its solve my problem.
