### ISSUE TITLE
ng e2e --proxy-config proxy-config.json is not possible

### ISSUE THREAD

**Issue by tuxmatta** [angular/angular-cli#11408]
### Feature Request

I use for the e2e test on the jenkins server a different `proxy-config.json`. It would be nice if I can use the following two `ng e2e` commands like the `ng serve`:

```
ng e2e --proxy-config proxy-config.json      // for local e2e test
ng e2e --proxy-config proxy-config.ci.json   // for e2e tests on jenkins
```
Currently the ng e2e command return with `Unknown option: '--proxyConfig'`

### Versions
node: v9.8.0
npm: 6.1.0
on ubuntu 16.04

### Repro steps
`ng e2e --proxy-config proxy-config.json`

### The log given by the failure
`Unknown option: '--proxyConfig'`

### Desired functionality
The command `e2e` should be pass the `proxy-config` option to the `serve` command.

Thank you for your great work

**Comment by filipesilva** [comment]
We generally don't support passing through options. Instead, it is preferable that you create a configuration for your serve target and use it, like described in https://github.com/angular/angular-cli/issues/11412.
