### ISSUE TITLE
Error TS2307: Cannot find module 'path'.

### ISSUE THREAD

**Issue by Plautus123** [angular/angular-cli#11416]
x  I am following an angular tutorial on youtube and I get t error ts2307 when compiling.

![image](https://user-images.githubusercontent.com/40147258/42123219-76e04c2a-7c4e-11e8-8540-a46a8340a206.png)

so I have just looked into the folder for the first time and I found the files. So I guess in the files the modules are missing. I must have forgot to install somehting

the project is "Angular 5 CRUD Application Using Firebase" a youtube tutorial

I never had this error before, and this isnt my first time using angular, so why does all of a sudden angular not find my modules?
or is this simply because the guy in the tutorial uses Angular 5 and my version is 6 ?

**Comment by alan-agius4** [comment]
Hello, this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow ](https://stackoverflow.com/) using tag angular.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation.](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)
