### ISSUE TITLE
Invalid JSON character: "\""

### ISSUE THREAD

**Issue by Plautus123** [angular/angular-cli#11421]
I get the following error

![image](https://user-images.githubusercontent.com/40147258/42131258-903a9e5e-7cfe-11e8-9577-6a7e85edc523.png)

no idea what's going on.
I am working with angular 6

**Comment by rchod** [comment]
what version of node do you have? if under 8.9 try to update node

**Comment by lordKnighton** [comment]
What did you modify before starting this app, And what it is saying in the console log section?

**Comment by Plautus123** [comment]
solved it somehow but dont remember how

**Comment by clydin** [comment]
Closing as resolved.
