### ISSUE TITLE
Feature Request - ng init/new guided configuration

### ISSUE THREAD

**Issue by nitro52** [angular/angular-cli#1143]
It would be good if during ng init or new you were asked a series of questions that would help you configure the project based on your needs. 

Some example questions
1. Would you like to include end to end tests?
2. Would you like to use Typescript?
3. Would you like to customize the folder structure?
-      a. use standard folder structure (think i've seen it called LIFT?)
-      b. use folder per type structure 

This way you can create a bare bones project if you wanted to test something or add all the bells and whistles for a full developer environment.

**Comment by filipesilva** [comment]
This isn't something we're looking at doing. We do have plans for a mechanism to allow for custom blueprints, which I believe would also solve this problem.
