### ISSUE TITLE
Does Angular Cli 6 support @import ~ anymore?

### ISSUE THREAD

**Issue by dereklin** [angular/angular-cli#11435]
I just create a brand new app with angular cli 6.  I tried use do 

```
@import '~styles/variables';
```
But I got file not found error.

Here is my code:

https://stackblitz.com/github/dereklin/myng6app?file=src%2Fapp%2Fapp.component.scss

Is @import ~ no longer supported?

**Comment by LeoUrzua** [comment]
Rename the file from "/src/styles/_variables.scss" to "/src/styles/variables.scss" and it worked

"import" is part of typescript and angular 6 implements typescript

**Comment by dereklin** [comment]
That's interesting.  While stackblitz appears to work, running ng serve locally still produces the same error after change the file name:

```
ERROR in ./src/app/app.component.scss
Module build failed: 
@import '~styles/variables';
^
      File to import not found or unreadable: ~styles/variables.
      in /Users/delin/sandbox/myng6app/src/app/app.component.scss (line 1, column 1)
ℹ ｢wdm｣: Failed to compile.
```
Here is my repo: https://github.com/dereklin/myng6app

On another note, stackblitz seems to cache my old app.  When I do https://stackblitz.com/github/dereklin/myng6app, I can still see _variables.scss instead of the newly named variable.scss.

But I really think _variables.scss is the right file name since they are partials and I don't want sass to compile them: https://kolosek.com/sass-import/

**Comment by LeoUrzua** [comment]
Change the app.component.scss to

`@import '../../styles/variables`

and name the variables file as you want "_variables.scss"

![image](https://user-images.githubusercontent.com/23623792/42200479-138e182a-7e59-11e8-9a81-140afa27ec5f.png)

**Comment by dereklin** [comment]
But that's relative import.  My original question is regarding the support of @import ~.  It used to work before my upgrading to Angular 6.  Some claim it's still working (https://github.com/storybooks/storybook/issues/3814).  I want to find out if it's indeed supported still.

**Comment by VitalDoVilmate** [comment]
Did you find the way how to solve the issue?

**Comment by clydin** [comment]
The usage of the tilde was/is not officially supported and is actual an artifact of the internal implementation of the build system.  While it may currently work in certain situations, it is not guaranteed to continue to function in the future.  In the style use cases outlined above, a relative path or the use of the `includePaths` option ([more details](https://github.com/angular/angular-cli/wiki/stories-global-styles)) is recommended.

**Comment by NickLanam** [comment]
@clydin Is this a change of stance? On [#9166](https://github.com/angular/angular-cli/issues/9166#issuecomment-357249253) (back in January), you noted that this syntax being unsupported was a defect. It also appears that there are [unit tests](https://github.com/angular/angular-cli/blob/6.0.x/tests/e2e/tests/build/styles/material-import.ts#L20) in 6.0.x that check if tilde imports work.

Has something changed in policy?

**Comment by clydin** [comment]
The Angular Material documentation contained a usage of the tilde and to prevent wide spread breakage a set of tests for a limited usage of the tilde were added at that time.  These tests were carried over into 6.x to attempt to ease transition.  However, there is currently not a guarantee that the tilde will continue to function (even in the tested limited capacity) moving into the future.

**Comment by NickLanam** [comment]
I see. Given that this functionality happens to work sometimes (despite not being intentionally supported), what sort of work do you think it would take to make it intentionally supported? I'd be interested in taking a stab at it if it's not too hairy. It's quite a handy thing to have, after all.

**Comment by damienwebdev** [comment]
@NickLanam I've proposed an idea that may solve this issue in #12573. Let me know if that would handle your use-case, especially if @clydin is unwilling to commit to supporting `~` this may be a feasible alternative.

**Comment by NickLanam** [comment]
@damienwebdev That proposal would add a fair bit of flexibility, but I'm not sure that it achieves the same use case. In the issue here, a working implementation avoids the need for manually specifying where to find each thing. It defaults to finding `node_modules` (no matter how deep in the tree the file you're working on might be).

**Comment by Albejr** [comment]
In my case (Angular 7):

angular.json
```
"projects": {
    "MyProject": {
      "sourceRoot": "src"
}}
```

styles.scss
`@import "assets/css/variables.scss";`

**Comment by rtyx** [comment]
What about server side applications?

In my `angular.json` file, adding:

```
"stylePreprocessorOptions": {
							"includePaths": [
								"src/styles"
							]
						},
```

to the `architect.build.options` seems to work, but it fails with `ng run myapplication:server:dev`.

Do I have to add it also in `architect.server.options`?

**Comment by ViieeS** [comment]
In my case `~src` label doesn't work only for SSR, because I can't define assets in options of the server scheme:

```json
"assets": [
   "src/assets"
]

```

When I try to do so I get an error: 
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(assets).
```
`stylePreprocessorOptions > includePaths` working though...
