### ISSUE TITLE
A site packed in Webpack is normal when the first load, but I'll get an error after refresh

### ISSUE THREAD

**Issue by fukua777** [angular/angular-cli#11436]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

node   v6.10.2
npm   3.10.10
windows  7
"@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "scss": "^0.2.4",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"

**Comment by fukua777** [comment]
![err1](https://user-images.githubusercontent.com/19884392/42202544-6053dfb2-7ece-11e8-8065-7d1eb8220284.png)
![err2](https://user-images.githubusercontent.com/19884392/42202549-64bdbed8-7ece-11e8-947b-3f867209a512.png)


as shown on the images, it should be var e2 = .., what should I do?

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by fukua777** [comment]
I've created a new demo via `ng new webApp`  and got the prod via `ng build --env=prod`. Then I put the project on the server that provided by amazon.
I guess the project is ok, is it a server problem. The server is an example provided by amazon lightsail.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
