### ISSUE TITLE
ng serve: The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with: ',' expected

### ISSUE THREAD

**Issue by webia1** [angular/angular-cli#1144]
The automatically created files have errors:

`.....-app/tmp/broccoli_type_script_compiler-input_base_path-mHmvIylP.tmp/0/src/whatever-app.routes.ts (7, 3): ',' expected.`

```
import { RouterConfig } from '@angular/router';
import { WhatEverAppComponent } from './';

export const WhatEverApp_ROUTES: RouterConfig = [{
  path: '/what-ever-app', component: WhatEverAppComponent, index: true
  children: [ ]
}];
```

As you see, ',' is missing after path and additional I get the error:  Cannot find module './'.

----------------------------------------
Windows 7, Node 5.11.1

**Comment by filipesilva** [comment]
How are you generating that file? Route generation is disabled as of beta.6.

**Comment by webia1** [comment]
here: delasteve:feature/router-v3

**Comment by filipesilva** [comment]
@webia1 you'll have to talk to the author of that PR about it.
