### ISSUE TITLE
ng serve --configuration local with production FALSE still serves in production mode

### ISSUE THREAD

**Issue by stellasoft-will** [angular/angular-cli#11447]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

v8.11.3

### Repro steps

new project create configuration that has production "false" with environment file with production false, then serve. Still serves as production true, which then pops up warning about this.

### The log given by the failure

N/A

### Desired functionality

Should it not serve production false if false value is set in environment file?

**Comment by filipesilva** [comment]
The environment file contains only runtime variables. It doesn't affect build options. You should use the configuration options in `angular.json` for build options.
