### ISSUE TITLE
ng serve cli host argument override not working 

### ISSUE THREAD

**Issue by dominikg** [angular/angular-cli#11448]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
Angular CLI: 6.0.8
Node: 10.5.0
OS: darwin x64
Angular: 6.0.7

### Repro steps
`ng serve --host localhost --host 127.0.0.1`

### The log given by the failure
Schema validation failed with the following errors:
  Data path ".host" should be string.

### Desired functionality
serve works with host set to 127.0.0.1

### Mention any other details that might be useful

this worked with cli 1.7.4

it still works with other options
`ng serve --prod=false --prod=true`
-> serves in production mode

`ng serve --prod=true --prod=false`
-> serves in development mode

**Comment by dominikg** [comment]
Usecase: overriding single options in package.json scripts using yarn run

```
    "serve:default": "ng serve --host defaulthost ...more options ...",
    "serve:other": "yarn run serve:default --host other",
```

**Comment by alan-agius4** [comment]
Seems that this is no longer reproducible with Angular CLI version 7 rc 2

```
ng serve --host localhost --host 127.0.0.1
** Angular Live Development Server is listening on 127.0.0.1:4200, open your browser on http://127.0.0.1:4200/ **
...
```
