### ISSUE TITLE
Is there a way to exclude a file from being merged during build (IE keep the file separate from bundles)

### ISSUE THREAD

**Issue by pain0486** [angular/angular-cli#11441]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Area 
```
- [ ] devkit
- [x ] schematics ??
```

### Desired functionality
OK so here is what I am trying to solve, perhaps there is a better way. 
I have a config file that will provide and organization code and server code (among other things) to the rest of my application. The organization code will be a will be unique per client using the site while the sever code will be something representing live or demo. Each client will have their own site on a sub domain. For example

- client1.mysite.com, 
- client2.mysite.com.

What I would like to do is build the application 1 time using ng build and deploy the site to each client site that has their own config file. Then have the built code reference the config file in the folder of the client site.

So instead of taking config.orgCode and inserting the value in the consuming file I want the consuming file to import   ./config and use the orgCode property.

### Mention any other details that might be useful
I know I could probably do this via multiple application support, but rebuilding each application and only changing a few small values in a handful of files seems very wasteful use of the CI server's resources.

**Comment by clydin** [comment]
Please see this issue (https://github.com/angular/angular-cli/issues/7506) for details on how this can be accomplished.
