### ISSUE TITLE
Angular 6 can't build server bundle with aot=false

### ISSUE THREAD

**Issue by psamusev** [angular/angular-cli#11452]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Versions
node --version v8.9.4
npm --version 6.1.0
macOS High Sierra

"@angular-devkit/build-angular": "~0.7.0-rc.0",
"@angular/cli": "^6.1.0-rc.0",

### Repro steps
ng new test-project
ng generate universal
set "aot: false" to "options" of angular.json "server" configuration
ng run test-project:server

### The log given by the failure
```
Schema validation failed with the following errors:
Data path "" should NOT have additional properties(aot).
```

### Desired functionality
I need build my server bundle with --aot=false flag

**Comment by paulogr** [comment]
You can't set aot configuration on server build, but I dont' know why... even `aot=true` doens't work.

**Comment by psamusev** [comment]
@paulogr I found out that schema of "server" builder doesn't support it. Moreover it's hardcoded as value here https://github.com/angular/angular-cli/blob/6.1.x/packages/angular_devkit/build_angular/src/server/index.ts#L90

**Comment by filipesilva** [comment]
AOT is not an option in the server builder, no. This is by design.
