### ISSUE TITLE
Feature Request: Support Renaming App Folder and Main Entrypoint

### ISSUE THREAD

**Issue by sqwk** [angular/angular-cli#1145]
At the moment the cli expects the main entrypoint to be at `src/main.ts` and the AppComponent at `src/app/index.ts` If one renames/moves them to `src/js/bootstrap.ts` and `src/js/app.ts` respectively, production compilation will fail. Normal compilation works fine. It seems that `main.ts` is hardcoded into the production build somewhere.

**Comment by Lightw3ight** [comment]
I would really like this feature too
I am using a-cli to make a component library and so having a folder named "app" doesn't make much sense, I have managed to rename my app folder changed my config files and seem to have compilation working but I cannot use the generator as it seems to only want to generate files in the app folder (which doesn't exist)

**Comment by platosha** [comment]
Is it coming in #1633?

**Comment by intellix** [comment]
I think it'd be cool to rename/move anything actually, with references updated.
I have a component called meh and I want to rename it to meh-lol and I have to update quite a few file names, and references

**Comment by yogeshgadge** [comment]
As of 1.2.6 I don't believe this is fixed. `ng g c my-component` still generates it here `src\app\my-component`

**Comment by ghaschel** [comment]
Same result as @yogeshgadge here

**Comment by yogeshgadge** [comment]
@ghaschel try CLI 6.x you will have control over folder structure.
