### ISSUE TITLE
Cannot delete files in custom schematics

### ISSUE THREAD

**Issue by dealloc** [angular/angular-cli#11460]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics (?)
```

### Versions

Node: v9.11.1 (via NVM)
Yarn: 1.7.0
NPM: 5.6.0

Windows 10 Pro (v1803 build 17134.112)

### Repro steps

Given the following schematic:
```typescript
export default function (_options: any): Rule {
	// The chain rule allows us to chain multiple rules and apply them one after the other.
	return chain([
		(tree: Tree) => {
			tree.create('test', 'test');
			tree.delete('test');
		},
	]);
}
```

### The log given by the failure

`Path "/test" does not exist.`

### Desired functionality

The file should be deleted without an error.

### Mention any other details that might be useful

This is a minimal reproduction of a problem I encountered, in my custom schematic I try to delete files generated earlier by another (external) schematic or a template call (from another collection, but same collection).
However whenever I call delete, the schematic aborts and reports that the file I try to delete does not exist.
Strangely enough, calls to "rename", "exist" etc on the same file work as expected.

**Comment by clydin** [comment]
The schematics backend was refactored for 6.1 as a result this should be corrected in the upcoming version.  Please note the next RC (rc.1) will have several bug fixes that will most likely apply to custom schematic usage.

**Comment by dealloc** [comment]
Are there any instructions as to how I could test and confirm this?

If this has been fixed, I can close the issue after confirmation of a fix

**Comment by ThomasBurleson** [comment]
This is a significant bug that affects development in Nx Schematics.

**Comment by dealloc** [comment]
@filipesilva In out internal company schematics the problem seems to occur but not in every situation.
Sometimes we're able to remove files (far as I can see when doing so directly after they've been generated in the operation before), but sometimes the operation fails silently (no error or output, but the file is still present in the output), this usually seems to happen with files generated by another schematic.

I'm currently out of the country until next week, so I'll try to get a minimal reproduction working then.
The package.json used for those schematics has following dependencies:
```json
  "dependencies": {
    "@angular-devkit/core": "0.8.3",
    "@angular-devkit/schematics": "0.8.3",
    "@schematics/angular": "0.8.3",
    "@types/node": "^8.0.31",
    "typescript": "^2.5.2"
  },
  "devDependencies": {
    "dtsgenerator": "^1.1.0"
  }
```

**Comment by filipesilva** [comment]
@dealloc thanks for getting back to me, let me know when you have a repro up.

**Comment by alan-agius4** [comment]
@FrozenPandaz is this still re-producible from your end?

Thanks.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
