### ISSUE TITLE
Cannot create any project

### ISSUE THREAD

**Issue by frodefi** [angular/angular-cli#1146]
Using OSX 10.11.5, Node  4.4.5, npm 3.10.1 and angular-cli@1.0.0-beta.6.

When I try to create a new project with something like `ng new my-dream-app`, I get the following error before the cli hangs:
`Installing packages for tooling via npmtypings ERR! message Unknown dependency: registry:dt/es6-shim#0.31.2+20160317120654`

When the cli hangs, the internet is not working either. Maybe because it is related to this [npm issue](http://stackoverflow.com/questions/37635493/npm-install-just-spins-and-blocks-other-internet-use)?

**Comment by hacknaked** [comment]
According to https://angular.io/docs/ts/latest/quickstart.html#!#prereq
Angular 2 requires at least node v5.x.x and npm 3.x.x. So I'd recommend to upgrade your Node to v6.x (the next LTS version).

**Comment by frodefi** [comment]
Upgraded to node 6.2.2 with npm 3.9.5, same problem :(

```
DigitalWife:t2 ff$ node --version
v6.2.2
DigitalWife:t2 ff$ npm --version
3.9.5
DigitalWife:t2 ff$ sudo npm install -g angular-cli
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
- rewire@2.5.1 node_modules/angular-cli/node_modules/rewire
/usr/local/lib
└── angular-cli@1.0.0-beta.6 

DigitalWife:t2 ff$ ng new blisteinrik
(node:1216) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
  create src/app/app.component.html
  create src/app/app.component.spec.ts
  create src/app/app.component.ts
  create src/app/environment.ts
  create src/app/index.ts
  create src/app/shared/index.ts
  create src/favicon.ico
  create src/index.html
  create src/main.ts
  create src/system-config.ts
  create src/tsconfig.json
  create src/typings.d.ts
  create angular-cli-build.js
  create angular-cli.json
  create config/environment.dev.ts
  create config/environment.js
  create config/environment.prod.ts
  create config/karma-test-shim.js
  create config/karma.conf.js
  create config/protractor.conf.js
  create e2e/app.e2e-spec.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create .gitignore
  create package.json
  create public/.npmignore
  create tslint.json
  create typings.json
⠋ Installing packages for tooling via npmtypings ERR! message Unknown dependency: registry:dt/es6-shim#0.31.2+20160317120654

typings ERR! cwd /Users/ff/Google Drive/Developing/t2/blisteinrik/node_modules/@angular/router
typings ERR! system Darwin 15.5.0
typings ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/typings/dist/bin/typings-install.js"
typings ERR! node -v v6.2.2
typings ERR! typings -v 0.6.2

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

⠋ Installing packages for tooling via npm
```

**Comment by filipesilva** [comment]
This might be related to https://github.com/angular/angular-cli/issues/1092 actually, or even a dupe. 

In beta.6, one of the installed dependencies has a `typings install` hook, which unfortunately uses the global typings. In your case, I would say that your global typings is a pre-`1.0.0` version that has trouble with the new registry formats.

This will be fixed in beta.7, which should come out soon. Meanwhile, you can follow https://github.com/angular/angular-cli/issues/1092#issuecomment-226528424 to get it working.
