### ISSUE TITLE
--skip-tests is not working

### ISSUE THREAD

**Issue by hizliemre** [angular/angular-cli#11462]
My cli version is 6.0.8 and node version is 8.11.3.

And i am trying to setup new application with skip-tests option but it's not work.

I dont want use e2e, tests, specs etc. I need a resolution like the --minimal flag in the previous version

the result is as follows:

CREATE test-app/angular.json (4100 bytes)
CREATE test-app/package.json (1312 bytes)
CREATE test-app/README.md (1024 bytes)
CREATE test-app/tsconfig.json (384 bytes)
CREATE test-app/tslint.json (2805 bytes)
CREATE test-app/.editorconfig (245 bytes)
CREATE test-app/.gitignore (503 bytes)
CREATE test-app/src/environments/environment.prod.ts (51 bytes)
CREATE test-app/src/environments/environment.ts (631 bytes)
CREATE test-app/src/favicon.ico (5430 bytes)
CREATE test-app/src/index.html (294 bytes)
CREATE test-app/src/main.ts (370 bytes)
CREATE test-app/src/polyfills.ts (3194 bytes)
CREATE test-app/src/test.ts (642 bytes)
CREATE test-app/src/assets/.gitkeep (0 bytes)
CREATE test-app/src/styles.css (80 bytes)
CREATE test-app/src/browserslist (375 bytes)
CREATE test-app/src/karma.conf.js (964 bytes)
CREATE test-app/src/tsconfig.app.json (194 bytes)
CREATE test-app/src/tsconfig.spec.json (282 bytes)
CREATE test-app/src/tslint.json (314 bytes)
CREATE test-app/src/app/app.module.ts (314 bytes)
CREATE test-app/src/app/app.component.html (1141 bytes)
CREATE test-app/src/app/app.component.ts (207 bytes)
CREATE test-app/src/app/app.component.css (0 bytes)
CREATE test-app/e2e/protractor.conf.js (752 bytes)
CREATE test-app/e2e/src/app.e2e-spec.ts (304 bytes)
CREATE test-app/e2e/src/app.po.ts (208 bytes)
CREATE test-app/e2e/tsconfig.e2e.json (213 bytes)

**Comment by Brocco** [comment]
Tagging this as a feature, to re-add the `--minimal` flag.

**Comment by thismarcoantonio** [comment]
@Brocco, any news in this feature? I'm trying to refactor my library in Version 6 without tests and I just can't.

**Comment by alan-agius4** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/11904
