### ISSUE TITLE
Issue with code generation for @Injectable when using providedIn: 'root' and tsconfig paths

### ISSUE THREAD

**Issue by bfarrelly** [angular/angular-cli#11467]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

Angular v6.0.7
node v8.9.4
npm v6.1.0
win 10

### Repro steps

Firstly, I am not using **ng**, I am using **ngc** as we use SystemJS and Rollup due to the extra flexibility they give us (We have a rather large in house enterprise platform we are transitioning from AngularJS that makes extensive use of lazy loading).

The steps:

- Create two separate libraries, with a service each (Service A and Service B) using @Injectable with providedIn: 'root'
- Export serviceB using an index.js for use in serviceA
- npm link Lib B to Lib A
- Create a path mapping in lib A's tsconfig to lib B module in tsconfig e.g. 

    `"lib-two": ["../node_modules/lib-two/build/src"]`

- Import serviceB into serviceA.

ServiceA.ts

```
import { Injectable } from "@angular/core";
import { ServiceB } from 'lib-two';

@Injectable({
    providedIn: 'root'
})
export class ServiceA {
    constructor(private serviceB: ServiceB) {

    }
}
```
ServiceB.ts
```
import { Injectable } from "@angular/core";

@Injectable({
    providedIn: 'root'
})
export class ServiceB {
    constructor() {

    }
}
```

- Compile using ngc, target: es5, module: es2015
- Observe that as part of the code gen to add the factory for @Injectable, the original imports are duplicated using import * syntax

ServiceA.js

```
import { Injectable } from "@angular/core";
import { ServiceB } from 'lib-two';
import * as i0 from "@angular/core";
import * as i1 from "lib-two/build/src/index";
var ServiceA = /** @class */ (function () {
    function ServiceA(serviceB) {
        this.serviceB = serviceB;
    }
    ServiceA.decorators = [
        { type: Injectable, args: [{
                    providedIn: 'root'
                },] }
    ];
    /** @nocollapse */
    ServiceA.ctorParameters = function () { return [
        { type: ServiceB }
    ]; };
    ServiceA.ngInjectableDef = i0.defineInjectable({ factory: function ServiceA_Factory() { return new ServiceA(i0.inject(i1.ServiceB)); }, token: ServiceA, providedIn: "root" });
    return ServiceA;
}());
export { ServiceA };
```

ServiceB.js

```
import { Injectable } from "@angular/core";
import * as i0 from "@angular/core";
var ServiceB = /** @class */ (function () {
    function ServiceB() {
    }
    ServiceB.decorators = [
        { type: Injectable, args: [{
                    providedIn: 'root'
                },] }
    ];
    /** @nocollapse */
    ServiceB.ctorParameters = function () { return []; };
    ServiceB.ngInjectableDef = i0.defineInjectable({ factory: function ServiceB_Factory() { return new ServiceB(); }, token: ServiceB, providedIn: "root" });
    return ServiceB;
}());
export { ServiceB };
```
This isn't what I expected.  Of course when I go to use rollup to turn this into a systemJS module it adds the additional imports, breaking my SystemJS mappings.

I did think that I had a workaround by adding my own factory using the _useFactory_ attribute:

ServiceA.ts
```
import { Injectable, inject } from "@angular/core";
import { ServiceB } from 'lib-two';

@Injectable({
    providedIn: 'root',
    useFactory: () => {
        return new ServiceA(inject(ServiceB))
    }
})
export class ServiceA {
    constructor(private serviceB: ServiceB) {

    }
}
```

Which then resulted in some workable code.

ServiceA.js
```
import { Injectable, inject } from "@angular/core";
import { ServiceB } from 'lib-two';
import * as i0 from "@angular/core";
var ɵ0 = function () {
    return new ServiceA(inject(ServiceB));
};
var ServiceA = /** @class */ (function () {
    function ServiceA(serviceB) {
        this.serviceB = serviceB;
    }
    ServiceA.decorators = [
        { type: Injectable, args: [{
                    providedIn: 'root',
                    useFactory: ɵ0
                },] }
    ];
    /** @nocollapse */
    ServiceA.ctorParameters = function () { return [
        { type: ServiceB }
    ]; };
    ServiceA.ngInjectableDef = i0.defineInjectable({ factory: ɵ0, token: ServiceA, providedIn: "root" });
    return ServiceA;
}());
export { ServiceA };
export { ɵ0 };
```
This worked for a few days however today I hit another issue (in a more complex example) in which a successful compile resulted in the code generation referencing a type from index.js '../../index' rather than relative path './ServiceC', causing cyclic dependency warnings to start showing up when bundling with rollup. 

Generated code
```
import { Injectable } from '@angular/core';
import { PluginStarter } from './plugin-starter-service';
import _ from 'lodash';
import * as i0 from "@angular/core";
import * as i1 from "../../index";

....

PluginRegistry.ngInjectableDef = i0.defineInjectable(
    { factory: ɵ0, token: i1.PluginRegistry, providedIn: "root" });
```
So time to understand/fix the root cause...

### The log given by the failure

No logs... just broken code

### Desired functionality

I don't understand why the import statements and types need to reproduced to support the generation of the factory?  Why cant it continue to use the types provided?  Is there a better way that we could be doing this and still get the same ourcome?

We need to use paths as we have npm packages with multiple submodules inside them.  We use paths to point the compiler at the right place and ensure that the import "symbol" remains consistent to our convention for SystemJS mapping/loading.

Coming from an AngularJS background, we also make heavy use of global services in all of our existing app content, so this feature was the one that made us decide it was finally time to look seriously at making the move.

I am just starting out on my "Angular" journey, so this may all be due to a lack of knowledge, but I figure I have to ask as I cant see a way forward for our platform at the moment.

Hope someone can help!

### Mention any other details that might be useful

The problem goes away when you remove "providedIn" as it  doesn't do the factory code generation, it also doesn't inject any services!

Here is the example in git.  I have checked in the compiled source as well just in case you don't want to pull it down and build it yourself.

[Github - Lib One](https://github.com/bfarrelly/angular-injectable-issue-lib-one)
[Github - Lib Two](https://github.com/bfarrelly/angular-injectable-issue-lib-two)

This has been driving me nuts for a few days now so any help/guidance would be appreciated!

Thanks.

**Comment by filipesilva** [comment]
Heya, the right place to report issues with `ngc` proper is https://github.com/angular/angular, can you reopen there please?
