### ISSUE TITLE
ng serve is not working after updating angular/cli

### ISSUE THREAD

**Issue by farah-1213** [angular/angular-cli#11474]
Greetings,

I am at beginner level in Angular JS. I'm facing an issue that the code is not updating after running ng serve. Thoroughly search the web and apply all the mentioned steps but still it couldn't solved.
1- uninstall and reinstall angular
2- Create a new project

The issue persists that the listener on localhost:4200; browser is not automatically opened on ng serve. Although before updating the angular/cli; the code was working fine.

Your cooperation will be highly appreciated in this regard. Thanks in advance!

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
