### ISSUE TITLE
Default e2e test fails with new generated app in 6.0.x

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#11477]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Repro steps

```
ng new hello
cd hello
ng e2e
```

### The log given by the failure

```
workspace-project App
    ✗ should display welcome message
      - Expected 'Welcome to app!' to equal 'Welcome to hello!'.
```

### Desired functionality

The default e2e test should not fail.

**Comment by cexbrayat** [comment]
@alan-agius4 Hmm, the other issue is about unit tests whereas this issue is about e2e tests. I agree that they are most probably related though.

**Comment by alan-agius4** [comment]
Apologies, I missed that part. 

Though, this issue should be already fixed in the 6.1.0 rc version.

**Comment by cexbrayat** [comment]
Ha nice, I missed the fix (probably one of the changes in the HostTree/VirtualTree ?).
Closing as it is indeed working with 6.1.0-rc.0

**Comment by alan-agius4** [comment]
It was fixed when schematics moved into the cli mono repo
