### ISSUE TITLE
Update node-saas version to 4.9.1

### ISSUE THREAD

**Issue by vishnugupta20** [angular/angular-cli#11470]
Since there is a new version of node-saas release 4.9.1 can you please update it in @angular-devkit/build-angular@0.6.8

The result I got when I executed `npm list node-sass`
└─┬ @angular-devkit/build-angular@0.6.8
  └── node-sass@4.9.0 

Here was some vulnerability issue in node-sass which they had made a fix in this release. Please update the dependency node-sass to latest version 4.9.1 to resolve the vulnerability issue.

Reported here as it was mentioned [angular-devkit](https://github.com/angular/devkit) this repository has been moved to Angular CLI repo

**Comment by clydin** [comment]
Already updated for the next version (https://github.com/angular/angular-cli/commit/67ffe5ea19c5194cf52ffb981a9450c888798268)

**Comment by vishnugupta20** [comment]
@clydin When are you planning to release the next version?
