### ISSUE TITLE
Is ng cli planing to make ng cli gui like vue-cli-gui?

### ISSUE THREAD

**Issue by iamdenny** [angular/angular-cli#11476]
### Question

Is ng cli planing to make ng-cli-gui like vue-cli-gui ?

ref : https://github.com/egoist/vue-cli-gui

It will be awesome if it made.

**Comment by Sergged** [comment]
https://marketplace.visualstudio.com/items?itemName=sasxa-net.angular-gui As I understand it is something like just vue-cli-gui, but third-person developed

**Comment by seanbotha123** [comment]
https://angularconsole.com

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/10342

**Comment by alan-agius4** [comment]
Closing as this is out side of the scope of the CLI and at the moment there is https://angularconsole.com which can be used.
