### ISSUE TITLE
Injectable Class in namespace can't get service instance after --prod build

### ISSUE THREAD

**Issue by andyhuang15** [angular/angular-cli#11487]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions

node v8.11.0
npm v5.6.0
windows 10
### Repro steps

my code as follows

import {Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';

export namespace HttpUtilNs {
  export interface UfastHttpResT<T> {
    code: number;
    message: string;
    value: T;
  }

  @Injectable()
  export class HttpUtilService {
    constructor(private http: HttpClient) {
        console.log(this.http);
    }
  }
}

1 if i run "ng serve",  this console log output is not undefined, this.http can be used;
2 if i run " ng build --prod --aot=false", this console log output is not undefined, this.http can be used;
3 if i run " ng build --prod or ng serve --prod", this console log output is undefined, this .http can't be used;

### Desired functionality

 i hope this http can been injected and not undefined.

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction provided.
