### ISSUE TITLE
Detect local angular/angular dist directory

### ISSUE THREAD

**Issue by matsko** [angular/angular-cli#1148]
During initialization, if the CLI project was smart enough to detect and ask if the package.json in the newly initialized project should make use of the dist code present in `angular/angular/` then it could save the work involved with configuring NPM. It would then be super cool if angular-cli can automatically export the angular umd files when a custom build of angular is used.

I am willing to take on the development of this feature.

cc @hansl

**Comment by hansl** [comment]
Closing this as obsolete. We will have a story for moving an app over.
