### ISSUE TITLE
Library: Bump up version feature

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#11486]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Area
```
- [ X] devkit
- [X ] schematics
```

### Versions
```
Angular CLI: 6.0.8
Node: 8.9.1
OS: darwin x64
Angular: 6.0.7
```

### Repro steps
Before you build a library(ies) there is no option to bump up a version across all packages.json.

### Desired functionality

To avoid having different hybrid solution by mixing different tools and have true CLI support its desirable to have it already part of Angular CLI, along with maybe generating a changeLOG.

**Comment by alan-agius4** [comment]
There is also some more context about the publish/bump workflow in this issue 
https://github.com/angular/angular-cli/issues/13836#issue-417954832

**Comment by kyliau** [comment]
There are two ways to achieve this without requiring explicit support from CLI:

1. Manually bump version with [npm version](https://docs.npmjs.com/cli/version)
2. Use [ngx-deploy-npm](https://www.npmjs.com/package/ngx-deploy-npm)

If neither of these works for you / is difficult to integrate, please reopen this issue for further discussion.
