### ISSUE TITLE
Passing a HTTP DELETE request through angular cli proxy end in 501 Not implemented error

### ISSUE THREAD

**Issue by BernhardBehrendt** [angular/angular-cli#11481]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ?] devkit
- [ ?] schematics
```

### Versions
Angular CLI: 6.0.8
Node: 8.11.3
OS: darwin x64
Angular: 6.0.7

### Repro steps
- Setup a backend which accept DELETE Requests.
- Configure proxy conf so that this backend is available via localhost:4200
- Submit a request like `httpClient.delete('url/to/deletion/endpoint')`
- Or alternatively execute a DELETE request against the proxy url using e.g. Postman

- It results in a response `501 This method may not be used` which does not occur when I call the the endpoint directly (without the proxy in between).

### The log given by the failure
The log does not produce any output

### Desired functionality
I want to see the request passed through the proxy to my backend service 

### Mention any other details that might be useful
Here the proxy.conf.json content:

````json
{
  "/gate/abc/api": {
    "target": "https://mydomain.com/gate/abc/api",

    "secure": false,
    "pathRewrite": {
      "^/gate/abc/api": ""
    }
  }
}
````

**Comment by filipesilva** [comment]
Our proxy functionality just exposes the proxy supplied by https://github.com/webpack/webpack-dev-server. Can you open this bug there please?
