### ISSUE TITLE
ngtools/webpack: Using externals prevents splitting off lazy modules

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular-cli#11490]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x ] devkit
- [ ] schematics
```

### Versions
Node: v8.11.3
npm: 5.8.0

### Repro steps

Once you define externals in an webpack config, ngtools/webpack does not split off lazy modules anymore.

1. Clone https://github.com/manfredsteyer/simple-webpack-config
2. npm i
3. npm run build
4. We get two bundles; a main bundle and a lazy chunk
5. Open webpack.config and remove comments around externals block
6. npm run build
8. Now, we get **only one bundle**

### Desired functionality

We should also get two bundles in step 8.

**Comment by clydin** [comment]
`@angular/core` cannot be made an external for the same reason the DLLPlugin is incompatible with the `@ngtools/webpack` plugin.  Currently, to support both JIT and AOT modes, `@angular/core` contains the module loader for all lazy routes.  This causes `@angular/core` to become the parent of all lazy routes from a loading perspective.  By making it an external, both the module and all of its children (the lazy routes) are now removed from the application.  Future work may alleviate this limitation but as of now, this is not possible.

**Comment by lefoulkrod** [comment]
I like Angular but for anything besides the simplest SPA use case you are blocked hard.
