### ISSUE TITLE
ng is not recognized as valid command even after successful npm install

### ISSUE THREAD

**Issue by indcoder** [angular/angular-cli#1149]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
 v5.9.1

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
'ng' is not recognized as an internal or external command,
operable program or batch file.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Th angular cli version +-- angular-cli@1.0.0-beta.6

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by bentolor** [comment]
I did the following:
1. Download https://nodejs.org/dist/v6.2.2/node-v6.2.2-x64.msi
2. Install
3. [Windows key], type "command prompt", right click "Run as Administrator"
4. `npm install -g angular-cli`

Open a termina. Run `ng`. Works

**Comment by filipesilva** [comment]
I'm running it on windows 10 as well, and didn't need to run it as an administrator. 

@indcoder Can you give me the console log from when you did `npm install -g angular-cli`?

**Comment by ramon26cruz** [comment]
I still get the same problem

**Comment by indcoder** [comment]
Hi @filipesilva

Thanks for looking into this.
 
I don't  have the logs of the previous install but I ran the npm install again 
C:\Users\xxxxxxx\AppData\Roaming\npm\ng -> C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
 C:\Users\xxxxxxx\AppData\Roaming\npm
`-- angular-cli@1.0.0-beta.6


I think the ng bin is not gettingput in the path

AC

**Comment by indcoder** [comment]
Hi @filipesilva Do you still need more info from my end?

**Comment by indcoder** [comment]
I tried to install as an Administrator and I get this error.
[npm-debug.zip](https://github.com/angular/angular-cli/files/342062/npm-debug.zip)

**Comment by indcoder** [comment]
Upgraded to node v6.2.2 but same error has above....but a big improvement. ng command is  working
but throws an error.

ng --help
module.js:442
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Augustine\AppData\Roaming\npm\node_modules\angular-cli\node_modules\leek\lib\leek.js:3:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by indcoder** [comment]
Ok so I upgraded my node from 5.* to 6.2.2. Nuked the .npm and .npm-cache folders and then installed ng. It works correctly.

I think:
1. There is some incompatibility between node 4 or 5. 
2. Multiple npm install of angular cli messed up the other npm modules.

**Comment by filipesilva** [comment]
Sorry it took me a while to get back to you. Weird bug overall, am glad you got it to work. 

The missing rsvp module is this issue: https://github.com/angular/angular-cli/issues/1186, it should be fixed next beta.

**Comment by sthallapelly** [comment]
Hi,
I'm facing the same issue with v4.5.0. I want to work on this stable version, is there any way to fix "ng not recognized" error in 4.5.0?

**Comment by filipesilva** [comment]
@sthallapelly if you get that message, it means that the npm install failed. Can you open a new issue with the log you get from running the command?

**Comment by Dbharali** [comment]
I am also getting the same error:  'ng' is not recognized as an internal or external command,
operable program or batch file. Plz guide on how to resolve this..

Thanks in advance

**Comment by bonganintshwanti** [comment]
I'm getting the same problem< 'ng' is not recognized as an internal or external command,
operable program or batch file

**Comment by kingshreyash** [comment]
Hi, I installed Nodes 7.2.1, which is latest as of now. 
Now for Angular 2, i ran command npm install -g angular-cli
But, ng command is not being recognized.

Am stuck here. please help

**Comment by JanStureNielsen** [comment]
@kingshreyash  -- this issue is closed. If you have a bug or feature to report, please open a new issue but it sounds like you have a support question which should be directed to StackOverflow.

**Comment by kingshreyash** [comment]
😔

**Comment by LunaBawa** [comment]
Hello philipo this is what am getting any help

C:\Users\USER>ng --version
'ng' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\USER>node --version
v6.9.5

**Comment by himanshu331** [comment]
Hi, I installed Nodes 7.2.1, which is latest as of now.
Now for Angular 2, i ran command npm install -g angular-cli
But, ng command is not being recognized.

Am stuck here. please help

**Comment by stevenjiangnz** [comment]
i had similar issue, did a nvm check, found the terminal and the ide were running on different version of node

**Comment by amyDoxy** [comment]
I was stuck on the same issue for many days. 
Either 'npm' nor 'ng' commands were recognized within Spring Tool Suite(Eclipse) but it was working in Windows (and Mac) terminals.
I updated the user and environment variables, reboot the IDE, but still it was not working.
But I have restarted the computer, and now Waaaaaouuh, it works fine.
So the best way to do is  restart the computer just after installing NodeJs, so that changes can take effects globally.

Hope this comment will help.

**Comment by Shrutikarekal123** [comment]
Try to run in node command prompt

![untitled](https://user-images.githubusercontent.com/18300185/27373010-446ac95a-5684-11e7-9127-c760a5850d27.png)

**Comment by gautamjgithub** [comment]
Just open your command prompt (run as administrator). Ensure node --v is 6.9.0 or higher and npm --v is 3.0.0 r higher.

After that run the following command: 

npm install -g @angular/cli

Once angular is installed. you can see an entry of angular cli in the path

C:\Users\Dell\AppData\Roaming\npm\node_modules\@angular

Then try ng help. It will work.

**Comment by PaulaOliveiraM** [comment]
When installing Angular Cli from Windows Power Shell with administrative privileges it doesn't create the global variable, the solution was add it manually. Just go to Enviroment Variables and add in the Path variable the directory for the NG exe. In my case, the path was "C:\NPM-Package\", after doing so, you have to restart your computer in order to apply the changes.

**Comment by dhanabalu** [comment]
There is an error in ng...
I tried npm cache clean
uninstall and installed again but there is no use and also i changed the path
C:\Users\admin\AppData\Local\atom\bin;C:\Users\admin\AppData\Roaming\npm;C:\ProgramData\admin\atom\bin and also C:\Users\admin\AppData\Roaming\npm\node_modules@angular\cli\bin\ng..

npm install -g @angular/cli
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\webpack\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
ng -v
'ng' is not recognized as an internal or external command,
operable program or batch file.
node -v
v6.10.1
npm -v
3.10.10
There is no use in this changes..Iam using windows 7..Help me to solve these issues

**Comment by TheDioniz** [comment]
1. you need to run installation with administrative privileges
- sudo on Unix / admin on Windows
2. you need to have the "ng" program in your PATH variable

**Comment by filipesilva** [comment]
I'm gonna have to chime in regarding the admin install: you definitely shouldn't not use admin privileges for npm installs, it leads to a lot of problems. You can read more about it here: https://docs.npmjs.com/getting-started/fixing-npm-permissions.

**Comment by TheDioniz** [comment]
well, I fully agree with you, but yet that solved my issue with "ng" not recognized

**Comment by vivekghanchi7** [comment]
C:\Users\Vivek Ghanchi>npm list -g --depth=0
C:\Users\Vivek Ghanchi\AppData\Roaming\npm
`-- @angular/cli@1.2.0


C:\Users\Vivek Ghanchi>ng
'ng' is not recognized as an internal or external command,
operable program or batch file.
I am running on windows10 can any solve this problem

**Comment by raferbop** [comment]
For those using windows 7, gautamjgithub's recommendation works.

**Comment by naru6be** [comment]
At last find the solution for ng command is not working issue ,Find the solution below http://itechiesol.blogspot.com/2017/07/angular-cli-ng-command-is-not-working.html

**Comment by ubgen** [comment]
Hello,

I installed the MEAN stack locally (without -g option) in my home directory. Now bash does not find ng command. I found it in my node_modules directory, under the path: _~/node_modules/@angular/cli/bin_ but to use it I have to type (e.g.) "_./ng --version_"

This is my npm list --depth=0 output (from my home dir in bash):
![npm_list](https://user-images.githubusercontent.com/28753134/33326925-9080671e-d456-11e7-9832-e4c3e6096e86.png)


And this is the "./ng --version" output
![ng_version](https://user-images.githubusercontent.com/28753134/33326928-92b5a86e-d456-11e7-8e1f-de4a79899fa8.png)

**Comment by pushp1992** [comment]
ng command mostly works fine with windows command prompt but it has some dependency issues with VS code or other editor, although we have installed the dependency for ng using npm install -g angular/cli 
Currenty my Node version is v8.9.4 and npm version is v5.6.0

Try executing **ng new [projectName]** using command prompt, it will work.

**Comment by SatishMHiremath** [comment]
I have faced and fixed this issue relates node-sass and python error.Try installing latest angular cli command with the steps below

Set the system variable path as well:
C:\Users\windowsusername\AppData\Roaming\npm

C:\Users\windowsusername\AppData\Roaming\npm\node_modules\@angular\cli\bin;

C:\Program Files\nodejs;

Then start using angular cli command prompt using:
angular client project folder path>npm install -g @angular/cli@latest

angular client project folder path>npm install -g node-gyp

**Comment by anamarquezz** [comment]
(All this on Windows 10 )
1.-Uninstall Node from computer,
2.-Remove this folders  (npm and npm-cache)
     >C:\Users\YourPcName\AppData\Roaming\npm and 
     >C:\Users\YourPcName\AppData\Roaming\npm-cache
3. Install  the Latest Version, in my case was node 10.5.0
4.- Open cmd and run npm install -g @angular/cli
and this work for me

**Comment by gjgiraldo** [comment]
is easy

add to environment variables your path to ng in my case
C:\Users\Administrador\AppData\Roaming\npm

in command prompt type  PATH

now it Works !

**Comment by mahmoudelkhadragy** [comment]
it works for me as 
1- in command prompt type PATH
2- type ng
3-close command and open it for the folder path and create new project by angular 
by type ng new app2

**Comment by srigowrideo** [comment]
i am finding an error in visual studio code, here when i run my programs on react, those will  give problems to display my program in chrome i am getting a texual examination for all the programs i write so what can i do?

**Comment by pushp1992** [comment]
For react mpn works and for angular ng works. So, try npm start for react
and ng serve for angular.
it would be great if you can attach screenshot of the error.



*Thanks and regards,*
*Pushp Singh*
*Mob: +91-958-498-9057*
*Linkedin: https://www.linkedin.com/in/pushp-singh-1a83b336/
<https://www.linkedin.com/in/pushp-singh-1a83b336/>*

**Comment by srigowrideo** [comment]
How to do that??

**Comment by pushp1992** [comment]
Fir taking screenshot, you can use your laptop shortcut key it take photo
of error and send

**Comment by srigowrideo** [comment]
I am not able to debug the program in visual studio code , I came across that we need to change the port of the local host but I don’t know how to change the port of the local host so I felt it’s taking dummy variable than my code , here is the problem

**Comment by srigowrideo** [comment]
I am not able to attach screen shorts for react

**Comment by pushp1992** [comment]
By default, localhost run on port 3000.
If you want to run on different port use the below command.

ng serve --host 0.0.0.0 --*port* 5000(any port)
OR,
2. In package.json use below line of code

"scripts": {
    "start": "ng serve --port 5000"
}


*Thanks and regards,*
*Pushp Singh*
*Mob: +91-958-498-9057*
*Linkedin: https://www.linkedin.com/in/pushp-singh-1a83b336/
<https://www.linkedin.com/in/pushp-singh-1a83b336/>*

**Comment by srigowrideo** [comment]
No sir my local host is running on 8081 port so only I wanted to change the port

**Comment by srigowrideo** [comment]
Sent from Mail for Windows 10

**Comment by pushp1992** [comment]
Hi,
I had provided 2 option. have you tried the second one ?

2. In package.json use below line of code
"scripts": {
"start": "ng serve --port 5000"
}

*Thanks and regards,*
*Pushp Singh*
*Mob: +91-958-498-9057*
*Linkedin: https://www.linkedin.com/in/pushp-singh-1a83b336/
<https://www.linkedin.com/in/pushp-singh-1a83b336/>*

**Comment by pushp1992** [comment]
Sounds good !

let me know, once your problem is solved.
I will be happy to know.

*Thanks and regards,*
*Pushp Singh*
*Mob: +91-958-498-9057*
*Linkedin: https://www.linkedin.com/in/pushp-singh-1a83b336/
<https://www.linkedin.com/in/pushp-singh-1a83b336/>*

**Comment by MojtabaTaha** [comment]
hi i just have the same problem of ng is not recognized as an internal or external command. how can i fix it please

**Comment by srigowrideo** [comment]
If you install the npm correctly then there will be no problem occurring so please check the tutorials point videos ( specifically videos because it will give the answer ) and you can find the answer

**Comment by CODevOp** [comment]
I was getting this error, The term 'ng' is not recognized as the name of a cmdlet, function, script file, or operable program. 
**The Fix for me** was to uninstall node from appwiz.cpl and reinstall.
