### ISSUE TITLE
Is angular 4 stable

### ISSUE THREAD

**Issue by AliSinaSaemi** [angular/angular-cli#11517]
I want to know which version of angular is stable or angular 4 is stable or not

**Comment by hansl** [comment]
Hi @AliSinaSaemi ,

This is the CLI repo. You probably meant to file this on the Angular Framework repo (http://github.com/angular/angular).

Angular 4 LTS will end on September. Angular 6 (latest major version) LTS will end on November 2019. You can find more information here; https://angular.io/guide/releases
