### ISSUE TITLE
Installation of angular 4

### ISSUE THREAD

**Issue by AliSinaSaemi** [angular/angular-cli#11518]
How should I install angular 4 in my system because there is angular 5 and 6 along?

**Comment by Sathishchary** [comment]
You can install any version of angular with specific command.You need to run the below command with version like 
**npm install -g @angular/cli@1.4.2**

**Comment by hansl** [comment]
Hi @AliSinaSaemi ,

You'll need an older version of the CLI. Please note that Angular is currently at version 6.
