### ISSUE TITLE
Error Path not found if use ng generate --inline-style

### ISSUE THREAD

**Issue by daddykom** [angular/angular-cli#11512]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```

### Versions

Angular CLI: 1.7.0
Node: 8.11.3
npm: 5.6.0
OS: darwin x64 
Mac OS X High Sierra 10.13.5 (17F77)

Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.4.0
@angular-devkit/core: 0.4.0
@angular-devkit/schematics: 0.4.0
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1

### Repro steps

use the option --inline-style gives Error
works fine without option

$ ng generate component tracking/tracking-modal-track --flat --inline-style --dry-run
Error: Path "/app/tracking/tracking-modal-track.component.ts" does not exist.
Path "/app/tracking/tracking-modal-track.component.ts" does not exist.

$ ng generate component tracking/tracking-modal-track --flat  --dry-run
  create src/app/tracking/tracking-modal-track.component.css (0 bytes)
  create src/app/tracking/tracking-modal-track.component.html (39 bytes)
  create src/app/tracking/tracking-modal-track.component.spec.ts (714 bytes)
  create src/app/tracking/tracking-modal-track.component.ts (323 bytes)

### Desired functionality

$ ng generate component tracking/tracking-modal-track --flat  --dry-run
  create src/app/tracking/tracking-modal-track.component.html (39 bytes)
  create src/app/tracking/tracking-modal-track.component.spec.ts (714 bytes)
  create src/app/tracking/tracking-modal-track.component.ts (323 bytes)

### Mention any other details that might be useful

.angular-cli.json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "time-tracker"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.scss",
        "../node_modules/font-awesome/css/font-awesome.min.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.min.js",
        "../node_modules/popper.js/dist/umd/popper.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js",
        "../node_modules/moment/min/moment.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
