### ISSUE TITLE
ng lint hangs , angular 6 

### ISSUE THREAD

**Issue by duduav** [angular/angular-cli#11519]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x] schematics
```

### Versions

node -v : v8.9.1
npm -v 5.5.1
Windows 10

### Repro steps

in my local project i upgraded from angular 5 to 6 
ng lint now hangs , no errors  

### Mention any other details that might be useful

private repo

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by duduav** [comment]
how can i know which rules are deprecated in angular 6 cli

**Comment by ajspera** [comment]
check your package.json if you have `rxjs-tslint` as a dependency. We were running into this a couple weeks ago when we migrated and I believe uninstalling that is what ended up fixing it. You shouldn't need it with v6 anyway.

**Comment by duduav** [comment]
thanks  i don't have rxjs-tslint in package.config

**Comment by duduav** [comment]
the issue was solve after removing some costume rules from the config file
