### ISSUE TITLE
ng build --prod throws warnings due to code in a node modules

### ISSUE THREAD

**Issue by jacopolanzoni** [angular/angular-cli#11514]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
    <node.version>v8.11.3</node.version>
    <npm.version>6.1.0</npm.version>

### Repro steps
Create a project with a node module containing an error which would raise a warning.
Run 'ng build --prod'

### The log given by the failure
Warning: Can't resolve all parameters for XXXX in /Users/lanjac/Development/my_project/node_modules/my_dependency/..: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for XXXX in /Users/lanjac/Development/my_project/node_modules/my_dependency/..: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for XXXX in /Users/lanjac/Development/my_project/node_modules/my_dependency/..: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for XXXX in /Users/lanjac/Development/my_project/node_modules/my_dependency/..: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for XXXX in /Users/lanjac/Development/my_project/node_modules/my_dependency/..: (?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for XXXX in /Users/lanjac/Development/my_project/node_modules/my_dependency/..: (?). This will become an error in Angular v6.x

### Desired functionality
I should not see warnings due to dependency code (right?)

**Comment by clydin** [comment]
This is correct behavior.  Production mode will compile, bundle, and optimize all aspects of the application to create a smaller and faster final output.
