### ISSUE TITLE
Base64 images are incorrectly embedded (appends file name to data incorrectly)

### ISSUE THREAD

**Issue by Magn3s1um** [angular/angular-cli#11515]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x ] devkit
- [ ] schematics
```

### Versions
```
node version v8.11.1

npm version 5.6.0

Angular Cli 6.0.0

Windows 10
```

### Repro steps

Add a style in the styles section of the angular.json file that embeds an image asset.  
Notice that the base64 image is prepended with original asset name.  Example: 
[Base64 image is incorrectly specified](https://imgur.com/i2ETfsr)

### The log given by the failure

[Base64 image is incorrectly specified](https://imgur.com/i2ETfsr)

### Desired functionality

Shouldn't append the file name to the base64 image.  
If I intercept the element before this, and remove the ")image-name.png text, it renders correctly.

**Comment by angelmartinez-wz** [comment]
You cannot embed a base 64 as a reference it will be marked as a security risk, you need to implement a sanitizer that returns a base 64 clean reference, another thing that you can do is create a pipe that validates if the element has no style returns default asset image in other case embed base 64 string.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. 

In Angular CLI version 7 we no longer embed resources in outputted CSS files. We retain the resources as external files to take advantage of HTTP2 and Caching among other things.
