### ISSUE TITLE
Allow run time variable for useHash in RouterModule

### ISSUE THREAD

**Issue by Swellenator** [angular/angular-cli#11529]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
Node v8.11.1. 
NPM 5.6.0. 
Windows 10.

Angular CLI: 1.6.5
OS: win32 x64

Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.6.2
webpack-bundle-analyzer: 2.9.2
webpack: 3.10.0

### Repro steps
Given the following:

```
        // Workaround for IE 9 - have to use # location strategy
        RouterModule.forRoot(appRoutes, { useHash: !history.pushState })
```

when compiled using

```
ng build --prod
```

And loading on a modern Chrome browser I find I am using the hash location strategy.

### The log given by the failure
No console or error logs.

### Desired functionality
When I use a variable in the root `AppModule.ts` for the hash location strategy it seems to be ignored and is compiled to true. It should be variable and available at run time. 

### Mention any other details that might be useful
To support IE 9 with Angular we have to always use hash location strategy which is annoying. We should only have to punish IE 9 users with an inferior URL, not everyone.

**Comment by clydin** [comment]
The AOT compiler processes and compiles the Angular metadata at build time.  This is not something the CLI can control.  Disabling AOT is an option but this will result in a less optimized final build.  Asking for help on a site such as stackoverflow may be a prudent option.

**Comment by gizm0bill** [comment]
```typescript
@NgModule
({
  ...
  imports:
  [
   ...,
   AppRouterModule, //  RouterModule.forRoot( ROUTES...
  ],
  providers:
  [
    {
      provide: LocationStrategy,
      useFactory: ( inj: Injector ) => !history.pushState
        ? new HashLocationStrategy( inj.get(PlatformLocation), inj.get(APP_BASE_HREF) )
        : new PathLocationStrategy( inj.get(PlatformLocation), inj.get(APP_BASE_HREF) ),
      deps: [ Injector ]
    },
  ]
})
export class AppModule {}
```
