### ISSUE TITLE
Routes generated with /xx/... are no longer working

### ISSUE THREAD

**Issue by a5hik** [angular/angular-cli#1152]
angular-cli: 1.0.0-beta.5
node: 6.2.1
os: darwin x64
angular: 2.0.0-rc.1

The Parent routes with /... notation is no longer working and had to manually remove the '...', in order for the child routes to work. I guess this needs a fix.

**Comment by filipesilva** [comment]
beta.6 removes route generation, so at the moment we are no longer supporting this functionality.

See https://github.com/angular/angular-cli/issues/1093 for more information.
