### ISSUE TITLE
Module build failed: Error: Can't resolve '../../../~@angular/material/prebuilt-themes/deeppurple-amber.css'

### ISSUE THREAD

**Issue by QingBei** [angular/angular-cli#11525]
### Bug Report or Feature Request (mark with an `x`)
I have an Angular project created with Angular-cli, and after I installed the Angular material as its documentation, npm install --save @angular/material @angular/cdk and insert the related theme into my styles.less file, the build output the above error Module build failed: Error: Can't resolve '../../../~@angular/material/prebuilt-themes/_deeppurple-amber.css'. i have tried to remove the tilde sign, but it not work at all.

### Area
```
- [ ] devkit
- [ ] schematics
```

### Versions
Angular version: 6.0.7
Material version: 6.3.2
OS: Windows 10 professional
TypeScript version: 2.7.2
Browser: Chrome

### Repro steps
after installing angular material and paste ` @import '~@angular/material/prebuilt-themes/deeppurple-amber.css';` in the styles.less file, then get build errors.

### The log given by the failure
![image](https://user-images.githubusercontent.com/17331623/42609430-2bd8d560-85bf-11e8-917c-f74e3540a26d.png)

### Desired functionality
want to set angular material theme successfully.

### Mention any other details that might be useful
![image](https://user-images.githubusercontent.com/17331623/42609468-5fbc3ad4-85bf-11e8-9faf-9714f2e8936f.png)
![image](https://user-images.githubusercontent.com/17331623/42609479-6769c6e8-85bf-11e8-8e30-0ba432a30634.png)

**Comment by QingBei** [comment]
Sorry guys, this errors occurs again... this time, there's no circular dependency, here is the screen shot: 
![image](https://user-images.githubusercontent.com/17331623/42812711-25cd279e-89f1-11e8-8c59-a3f84127ce9f.png)

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
