### ISSUE TITLE
save-exact=true in .npmrc

### ISSUE THREAD

**Issue by matzkoh** [angular/angular-cli#11520]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality

It would be nice if angular-cli follows `.npmrc` options.

```
save-exact = true
```

`package.json`

actual:

```
"@angular/common": "^6.0.3",
"@angular/compiler": "^6.0.3",
"@angular/core": "^6.0.3",
```

expected:

```
"@angular/common": "6.0.3",
"@angular/compiler": "6.0.3",
"@angular/core": "6.0.3",
```

(ref: https://github.com/angular/angular-cli/issues/11180#issuecomment-400536699)

**Comment by alan-agius4** [comment]
Hi @matzkoh, thanks for this feature request, however this is currently out of scope of the Angular CLI.

Let's revisit this in the future if we see more interest in this.
