### ISSUE TITLE
upgrade license-webpack-plugin

### ISSUE THREAD

**Issue by xz64** [angular/angular-cli#11536]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
N/A

### Repro steps
N/A

### The log given by the failure
N/A

### Desired functionality
I am the author of license-webpack-plugin which is used by projects generated with angular's cli and have been working on a new major release. I would like to see if you could upgrade the library to the next major release. Currently I am looking for feedback as it has not been tested by many end users as of now.

### Mention any other details that might be useful
You can install the alpha of the next major release at `license-webpack-plugin@next`
You can view the state of the next major release here: https://github.com/xz64/license-webpack-plugin/tree/dev
There are breaking changes so please make sure to check the documentation I have put on the repository.

**Comment by hansl** [comment]
Hi @xz64,

We do not allow beta or RC dependencies in our master branch. That being said, if you want to test the beta, we can make a PR for it and look it through.

Do you have a list of new features and breaking changes for that release?

**Comment by xz64** [comment]
Yes, you can find the information here:

https://github.com/xz64/license-webpack-plugin/blob/dev/DOCUMENTATION.md
https://github.com/xz64/license-webpack-plugin/blob/dev/MIGRATION.md

At this point I am not interested in putting an RC into master, but just want to see how it could affect people's builds and get some feedback.

I think I should start with advertising the alpha release on my repository so that I can get more testers. I will revisit this issue once I have received more feedback.
