### ISSUE TITLE
ng e2e documentation, clarify [project] parameter requires -e2e suffix

### ISSUE THREAD

**Issue by tongfa** [angular/angular-cli#11533]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```

### Versions
6.0.8

Will attach a PR shortly.

**Comment by tongfa** [comment]
https://github.com/angular/angular-cli/pull/11534

**Comment by hansl** [comment]
The ng e2e command accept any project, but by default we use the same project name and add -e2e to it. There's nothing preventing you from renaming that project (or having a new one) with a different name.

Going to close this but I'll keep a note with the documentation team to see if it's something we want to explain.
