### ISSUE TITLE
@angular/pwa noscript fallback missing

### ISSUE THREAD

**Issue by markgoho** [angular/angular-cli#11543]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Repro steps
`ng add @angular/pwa`

### Desired functionality
in the `index.html` file, we should see
`<noscript>Please enable JavaScript to continue using this application.</noscript>`

### Mention any other details that might be useful
This code was merged in on May 21: https://github.com/angular/devkit/pull/853 by @filipesilva but has somehow been lost in the shuffle.

**Comment by markgoho** [comment]
It looks like the code is still there: https://github.com/angular/angular-cli/blob/44086c60ff1d6c26d30850bef125120f6c498ac1/packages/angular/pwa/pwa/index.ts#L100

However, the index.html file is not being updated with this line.

**Comment by Brocco** [comment]
I agree that the code and test appear to be OK, perhaps it is how we are parsing the index.html file in order to determine where to place this text.

Can you please share the contents of your `index.html` file for testing?

Thanks!
