### ISSUE TITLE
Missing write access

### ISSUE THREAD

**Issue by gosaitarun** [angular/angular-cli#11542]
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:

How I grant this permission ?
Thanks

**Comment by ajspera** [comment]
Run the install with sudo or have node installed in a directory your user has access to. This is more a unix / npm and has nothing to do with angular-cli. You should close this and head over to stackoverflow with this question if my first sentence still leaves you stumped.
