### ISSUE TITLE
angular-cli doesn't install

### ISSUE THREAD

**Issue by jorgeherrera9103** [angular/angular-cli#11544]
### Bug Report or Feature Request (mark with an `x`)
D:\JORGEHERRERA\angular-cli>npm install -g @angular/cli
C:\Users\jorge.herrera\AppData\Roaming\npm\ng -> C:\Users\jorge.herrera\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

> @angular/cli@6.0.8 postinstall C:\Users\jorge.herrera\AppData\Roaming\npm\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
### Area
```
- [ ] devkit
- [ ] schematics
```

**Comment by ajspera** [comment]
Those warnings are normal and not indicative of the cli not installing. fsevents is specifically for interacting with a mac OS api which it appears you are not using.

**Comment by jorgeherrera9103** [comment]
@ajspera  thanks bro, I fixed, i just have to clean de npm and install again.

thanks!
