### ISSUE TITLE
Proposal: Add default prettier config to package.json

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#11545]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [ ] devkit
- [X] schematics
```
### Desired functionality
I think it might be good if we become more opinionated and recommend the use of something like Prettier for standardizing coding styles. We could pre-configure it for users to help with its adoption.

**Comment by michaeljota** [comment]
Maybe this review again? Prettier have support for Angular template now, and the Typescript support have become better. I really think this should be considered.

**Comment by alan-agius4** [comment]
Considering the little interest shown in this issue and the fact the prettier configuration is trivial to create we feel that we shouldn't add this by default in the CLI.
