### ISSUE TITLE
CLI installation fails

### ISSUE THREAD

**Issue by sayantanHack** [angular/angular-cli#11554]
I had tried to install the ajs using cli but it fails there have a log file please help me to find out the reason 
[2018-07-14T21_48_50_346Z-debug.log](https://github.com/angular/angular-cli/files/2195296/2018-07-14T21_48_50_346Z-debug.log)

**Comment by hansl** [comment]
This looks like an NPM issue, not CLI related. Have you tried contacting NPM or the NPM repo?

Closing this as there's nothing we can do.
