### ISSUE TITLE
Is there something like of registering new thirdparty compenents properly (like ng-bootstrap) in a single step ?

### ISSUE THREAD

**Issue by webia1** [angular/angular-cli#1155]
.. so that you only have to write in your own component, e.g.: 

`import {Alert} from 'ng2-bootstrap/ng2-bootstrap';`

without you need any further configuration steps except installing it with npm before (npm install ng-bootstrap --save) ?

thank you!

**Comment by filipesilva** [comment]
We don't have that at the moment, no. We also recognize it is a major pain point in CLI usage. There's some discussion going on about it in  https://github.com/angular/angular-cli/issues/882.

If you'd like to discuss it, can you do it there? It's easier to gather feedback when it's on a single thread.
