### ISSUE TITLE
No such file or directory as cli.js when doing 'ng new any-app'

### ISSUE THREAD

**Issue by adoi** [angular/angular-cli#11553]
----
### I think this is a bug because the user who was having it tried changing the PATH env variable, tried to change the @angular-devkit/build-optimizer, and the version of node he uses is 8.11.3 (greater than 8) and npm is 6.2.0 (greater than 5).

--- 

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
Node: 8.11.3
Angular: 6.0.8
npm: 6.2.0

### The log given by the failure

![image](https://user-images.githubusercontent.com/23533750/42727239-3e1edbf8-87a3-11e8-8345-84511322d9f8.png)

### Desired functionality

![image](https://user-images.githubusercontent.com/23533750/42727241-43f87ee4-87a3-11e8-9968-976f364087c5.png)

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
