### ISSUE TITLE
Lint shows template errors in typescript files

### ISSUE THREAD

**Issue by Ledzz** [angular/angular-cli#11557]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions

Windows 10
node v10.0.0
npm v5.6.0
```
"dependencies": {
  "@angular/animations": "6.0.1",
  "@angular/common": "6.0.1",
  "@angular/compiler": "6.0.1",
  "@angular/core": "6.0.1",
  "@angular/forms": "6.0.1",
  "@angular/http": "6.0.1",
  "@angular/platform-browser": "6.0.1",
  "@angular/platform-browser-dynamic": "6.0.1",
  "@angular/router": "6.0.1",
  "@types/underscore": "^1.8.8",
  "core-js": "^2.4.1",
  "rxjs": "^6.1.0",
  "zone.js": "^0.8.26"
},
"devDependencies": {
  "@angular-devkit/build-angular": "~0.6.1",
  "@angular/cli": "6.0.1",
  "@angular/compiler-cli": "6.0.1",
  "@angular/language-service": "6.0.1",
  "@angularclass/hmr": "^2.1.3",
  "codelyzer": "^4.0.1",
  "jasmine-core": "~2.6.2",
  "jasmine-spec-reporter": "~4.1.0",
  "karma": "~1.7.0",
  "karma-chrome-launcher": "~2.1.1",
  "karma-cli": "~1.0.1",
  "karma-coverage-istanbul-reporter": "^1.2.1",
  "karma-jasmine": "~1.1.0",
  "karma-jasmine-html-reporter": "^0.2.2",
  "protractor": "~5.1.2",
  "ts-node": "~3.2.0",
  "tslint": "~5.7.0",
  "typescript": "2.7.2"
}
```

### Repro steps

I don't know how to reproduce since I see it on only one project, if I create new - it goes away. Here's component typescript file: https://codepen.io/ledzz/pen/YjwrMp

### Current behaviour
If I run `ng lint` in project I get template errors in TS files like this:
```
ERROR: component-path/component-name.component.ts[37, 19]: Missing
 whitespace in interpolation end; expecting {{ expr }}
```

**Comment by splincode** [comment]
@Ledzz Add github repo for reproduce

**Comment by gregorybarale** [comment]
@Ledzz I had the same bug today. Is there any ngFor or ngIf in your template where there is no space between a semicolon and the next character?

For example `*ngIf="myBoolean;else myTemplate"` instead of `*ngIf="myBoolean; else myTemplate"`?

I had it and adding the space solves the problem. I don't know why.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
