### ISSUE TITLE
@angular-devkit/build-angular@6.1.0-rc.2 output doesn't for on Firefox<50

### ISSUE THREAD

**Issue by suau** [angular/angular-cli#11552]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

npm 6.1.0
macOS 10.13.4
@angular/cli@6.1.0-rc.2
@angular-devkit/build-angular@6.1.0-rc.2

### Repro steps

- bootstrap a new project with angular-cli
- build the project with the --prod flag
- serve it with your favorite server
- open in Firefox < 50
- check the developer console for errors

### The log given by the failure
the main bundle with crash with a `SyntaxError`

### Desired functionality

the project should run properly

### Mention any other details that might be useful

This is the bug behind it: #9340
The issue seems to be with `uglify-es`>`3.2.2`
Pinning the version of `uglifyjs-webpack-plugin` to `1.1.5` in `@angular-devkit/build-angular` would resolve it.

**Comment by filipesilva** [comment]
Heya, I'm going to close this issue in favor of https://github.com/angular/angular-cli/issues/9340 since that seems to be the main one. I'll ping the team about this though.
