### ISSUE TITLE
ng: command not found

### ISSUE THREAD

**Issue by arianlopezc** [angular/angular-cli#11563]
### Bug Report or Feature Request (mark with an `x`)
ng: command not found

### Versions
node 10.6.0
npm 6.1.0
Angular 6.0.8

### Repro steps
I have installed Node and Npm using Brew in macOS High Sierra.

I can see npm and node working because I can get the versions from them and start an Express application.

When I install npm install -g @angular/cli it says that it was installed satisfactorily.

But when I run ng serve or any ng operation it shows ng: command not found.

I followed some recommendations of cleaning the cache of npm but it doesn't work despite doing this. Also I tried npm link and despite executing  the commands on @angular when I enter ng serve the problem persists.

I can see that angular get's installed and if I uninstall it it happens too.

But no matter what the ng command can't be found.

Please help

**Comment by arianlopezc** [comment]
I solved the problem by establishing an alias in my .bash_profile
For some reason @angular/cli wasn't creating the path.

**Comment by jBC006-learner** [comment]
I'm facing the same issue, did several ways of trouble shooting .. till it says ng command not found
