### ISSUE TITLE
Persist "serve" informations ("port", "live-reload-port") into the angular-cli.json

### ISSUE THREAD

**Issue by angelozerr** [angular/angular-cli#1156]
angular-cli.json is used to persist informations about Angular2 project.

It should be cool if we could save too the information about "serve":
- port
- live-reload-port

in the angular-cli.json like this:

``` json
{
  "serve": {
    "port": 4201,
    "live-reload-port": 49153
  }
}
```

It will avoid passing port and live-reload-port when you do `ng serve`

If you accept to do that, it should be very cool too to update the JSON Schema https://github.com/angular/angular-cli/blob/master/lib/config/schema.json that I'm using to have completion for Eclipse Editor. Thanks!

**Comment by yahyaKacem** [comment]
you can actually do that but not in the `angular-cli.json` file rather in `.ember-cli` in the root of your project like this:
```
{
  "port": 4201,
  "liveReload": true,
  "host": "dev.domain.org",
  "live-reload-port": 49153
}

```

**Comment by pavlos256** [comment]
Thank you @yahyaKacem.

I wonder if it would be too much to ask for an optional "--save" parameter/flag to `ng serve` that would persist the options, like this:

    ng serve --port 4201 --live-reload-port 50000 --host 0.0.0.0 --save

Not that it's hard to edit .ember-cli by hand but this way it would be documented right there and easier to discover.

**Comment by angelozerr** [comment]
Many thanks @yahyaKacem!

**Comment by sinedied** [comment]
Why not also persist the proxy settings in the configuration file?

**Comment by Mahi8686** [comment]
ng serve  --host 0.0.0.0 --live-reload-port 49153
Is not working...

When i terminate the application its webpage is not getting loaded...
Can anybody help!!!

**Comment by kunalingole** [comment]
We are deployed project of Angular 2 and angular cli on AWS server. Change angular-cli.json file
as per below. Use command : ng serve.

angular-cli.json
{
  "port": 4201,
  "liveReload": true,
  "host": "example.com",
  "live-reload-port": 49153
}
we use live host name. but error disply
Provided host example.com could NOT be bound. Please provide a different host                                                                                                                 address or hostname . on aws(amazon) server. 
i have attach  screen shot also.
Please any  suggestion to  how  to serve application on AWS(amazon)server live host name.


![error](https://user-images.githubusercontent.com/15111598/30240645-eaf60bc6-9591-11e7-8008-656d9d366683.png)
