### ISSUE TITLE
Version strategy about packages of @angular-devkit and @schematics

### ISSUE THREAD

**Issue by Teamop** [angular/angular-cli#11560]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [x] schematics
```

### Repro steps

N/A

### The log given by the failure

N/A

### Desired functionality

  I just have questions about the version strategy about the packages of @angular-devkit and @schematics.
  As we all know that, the angular-cli version strategy follows the angular one 6.x currently, but for these @angular-devkit and @schematics packages, the version is currently `0.6.8(latest), 0.7.0-rc.2(next)`,  but in the github release, seems all these packages follow the angular-cli 6.x, so this conflict makes it hard to understand the changes or histories about devkit and schematics.
  So just wonder what's your thoughts about it? maybe it's just in development phrase and not ready? Or can just add version badge for the schematics and devkit ones in the release page currently?
thanks

### Mention any other details that might be useful

N/A

**Comment by hansl** [comment]
These packages are not considered ready for a full release. We have a list of requirements, and those packages are still considered experimental. For the DevKit packages, that mostly means they lack some documentation, for example, and some internal support. We are constantly working towards making those packages fully ready, so expect some update soon, and they'll be right off whichever major the rest is at.

Closing this issue as answered.
