### ISSUE TITLE
Angular cli Installation error via npm cmd

### ISSUE THREAD

**Issue by shifas05** [angular/angular-cli#11571]
hey guys i got this error while installing angular cli 

C:\Users\Shihas>npm install -g @angular/cli@latest
C:\Users\Shihas\ng -> C:\Users\Shihas\node_modules\@angular\cli\bin\ng

> @angular/cli@6.0.8 postinstall C:\Users\Shihas\node_modules\@angular\cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@an
gular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"
})

npm ERR! file C:\Users\Shihas\AppData\Roaming\npm
npm ERR! path C:\Users\Shihas\AppData\Roaming\npm
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Users\Shihas\AppData\Roaming\npm
npm ERR! @angular/cli@6.0.8 postinstall: `node ./bin/ng-update-message.js`
npm ERR! spawn C:\Users\Shihas\AppData\Roaming\npm ENOENT
npm ERR!
npm ERR! Failed at the @angular/cli@6.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Shihas\AppData\Roaming\npm-cache\_logs\2018-07-17T12_53_40
_555Z-debug.log

C:\Users\Shihas>ng -v
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\Shihas\node_modules\@angular\cli\bin\ng'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

C:\Users\Shihas>

what is this ? how to resolve?

**Comment by jorgeherrera9103** [comment]
Hi bro,

did you check the PATH variables?

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
