### ISSUE TITLE
I can't create new project after installed latest angular CLI (Pls., Help me)

### ISSUE THREAD

**Issue by NicolasJax** [angular/angular-cli#11573]
I can't create new project after installed latest angular CLI.

It was occurred below error message.

![image](https://user-images.githubusercontent.com/5396323/42831402-3ec7c812-8a14-11e8-84bf-f9bc92a4f9aa.png)

How can I solve this issue. Please help me.
Thanks..

**Comment by gabrielCachavilano** [comment]
Hola, tengo el mis problema, pudiste solucionarlo?

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by Rango941001** [comment]
I founded the same error!.
But it doesn't angular-cli err!

**Comment by nik2code** [comment]
I am facing the same issue 
reinstall latest node and angular
npm set registry https://registry.npmjs.org/
npm cache clean --force
npm cache verify
npm install


![err](https://user-images.githubusercontent.com/17030925/49693631-7cae4380-fb9e-11e8-9413-15093c41e7a6.png)
