### ISSUE TITLE
Karma unti test with $httpBackend.Response(500) nevers callsback the .then onError()

### ISSUE THREAD

**Issue by jacSparrow** [angular/angular-cli#11579]
### Test
it("Test", function () {
        var group;
        group = { "name": "G1", "id": "a73b8a9c-e319-4058-9499-9c615a9b1c7e" };
        $httpBackend.expectPOST("api/myUrl").respond(500);
        returnedPromiseObject = mySvc.getNames(dummyData);
        $httpBackend.flush();
        expect(returnedPromiseObject.$$state.value.status).toBe(error.status);
    });
```

### Service
 function getNames(group) {
            var deferred = $q.defer();
            $http.post("api/myUrl", group).then(
                function (response) {
                    deferred.resolve(response.data);
                },
                function (error) {
                    deferred.reject(error);
                }
            );
            return deferred.promise;
        };
```

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
