### ISSUE TITLE
Underscore module not found?

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/angular-cli#1157]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.6
node: 6.2.1
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
In component:
`import * as _ from 'underscore';`

In angular-cli-build:
`      'underscore/**/*.js'`

in system-config:

`  'underscore': 'vendor/underscore/underscore.js'`

and

```
  'underscore':{
    format: 'cjs'
  }
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
language-form.component.ts (2, 20): Cannot find module 'underscore'.

5. Mention any other details that might be useful.

Normally have no issue adding new libraries to angular but for some reason getting a weird error when I try to install underscore saying it can't find it, did I miss a step?

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by RicardoVaranda** [comment]
Update: 

underscore is one of the exceptions which doesn't automatically install typings and so requires further steps.

I've outlined them and updated the wiki for people in the future who have similar issues to refer to.

https://github.com/angular/angular-cli/wiki/3rd-party-libs

**Comment by NullVoxPopuli** [comment]
I'm getting a similar issue with `sinon`.

I'm currently trying ot figure out a basic typings.d.ts for `sinon`, but typings/ts is putting up a fight.

**Comment by RicardoVaranda** [comment]
Seems like most of the typings I try to install only have the dt version of them, not sure if this has anything to do with it but today I tried to install Chartist and I'm running into the exact same error.

**Comment by filipesilva** [comment]
Is there something wrong with typings from dt? They should work well, since this is a compilation problem.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
