### ISSUE TITLE
Router children path is not working 

### ISSUE THREAD

**Issue by dineshmaths1** [angular/angular-cli#11572]
This is my routing module code
{
path: 'accounts/:id',canActivate:[AuthGuard], component: AccountComponent,
children: [
{ path: 'consent', component: AccountconsentComponent },
{ path: 'contacts', component: AccountcontactComponent },
{ path: 'preferences', component: AccountpreferenceComponent },
{ path: 'sessions', component: AccountsessionComponent },
{ path: 'data', component: AccountdataComponent },
{ path: 'calls', component: AccountsCallsComponent},
{ path: 'calldetail/:id', component: AccountCallsDetailComponent},
{ path: '', component: AccountsessionComponent }
]
}

 I did url: '/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent' but its not going to children path. Her children path is consent.
 this.router.navigate(['../', id, 'consent'],{relativeTo:this.route});
same url if u reload the page  its working proper.Its not working working while click button.

Router enableTracing code

[Show/hide group.] Router Event: NavigationStart platform-browser.js:224
NavigationStart(id: 4, url: '/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent') platform-browser.js:219
Object { id: 4, url: "/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent", navigationTrigger: "imperative", restoredState: null }
platform-browser.js:219
[Show/hide group.] Router Event: RoutesRecognized platform-browser.js:224
RoutesRecognized(id: 4, url: '/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent', urlAfterRedirects: '/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent', state: Route(url:'', path:'') { Route(url:'accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5', path:'accounts/:id') { Route(url:'consent', path:'consent') }  } ) platform-browser.js:219
Object { id: 4, url: "/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent", urlAfterRedirects: "/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent", state: {…} }
platform-browser.js:219
[Show/hide group.] Router Event: GuardsCheckStart platform-browser.js:224
GuardsCheckStart(id: 4, url: '/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent', urlAfterRedirects: '/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent', state: Route(url:'', path:'') { Route(url:'accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5', path:'accounts/:id') { Route(url:'consent', path:'consent') }  } ) platform-browser.js:219
Object { id: 4, url: "/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent", urlAfterRedirects: "/accounts/0b0fdcd2-af5b-3cad-b053-d309b8a261a5/consent", state: {…} }
platform-browser.js:219
[Show/hide group.] Router Event: ChildActivationStart platform-browser.js:224
ChildActivationStart(path: '') platform-browser.js:219
Object { snapshot: {…} }

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
