### ISSUE TITLE
A wrong NPM package for @angular-devkit/build-webpack

### ISSUE THREAD

**Issue by AKlaus** [angular/angular-cli#11576]
### Bug Report

It seems that you published a wrong NPM package for `@angular-devkit/build-webpack` v0.0.8 - `build-angular` instead of `build-webpack`

**Comment by filipesilva** [comment]
Heya, actually what happened is that `build-angular` before was called `build-webpack`, and we renamed it. When the `next` come becomes `latest, that will be cleared up. Sorry for the confusion.
