### ISSUE TITLE
Add "paths" to tsconfig.json by default or by a parameter

### ISSUE THREAD

**Issue by oleksiipotiekhin** [angular/angular-cli#11570]
### Feature Request
```
- [x] feature request
```

### Area
```
- [x] schematics
```

### Versions
`node --version` v8.11.2
`npm --version` 5.6.0

### Desired functionality
Is it possible to add "paths" to **tsconfig.json** by default or by a parameter? Currently I'm doing in manually every time I start a new project. IMHO it is a good improvement.
![paths](https://user-images.githubusercontent.com/30025319/42804581-b3940090-89a9-11e8-8577-c39b61c9cdbf.png)

### Example
`ng new application --style scss --routing` **--alias** or **--aliases**

**Comment by alan-agius4** [comment]
Hi @oleksiipotiekhin,

Thanks for opening this feature request. None-the-less at the moment this doesn't fall in the Angular CLI roadmap. 

Let's reconsider this in the future.
