### ISSUE TITLE
App shell schematic does not use production configuration

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#11578]
When adding app-shell via `ng generate app-shell`, the generated target is
```
"app-shell": {
  "builder": "@angular-devkit/build-angular:app-shell",
  "options": {
    "browserTarget": "latest-project:build",
    "serverTarget": "latest-project:server",
    "route": "shell"
  }
}
```

Since `browserTarget` is `latest-project:build`, the production build will never be used when running the app-shell target and thus bundles sizes will be very big.

We should either use `"browserTarget": "latest-project:build:production",` or add a production configuration for the app shell target too.

```
"app-shell": {
  "builder": "@angular-devkit/build-angular:app-shell",
  "options": {
    "browserTarget": "latest-project:build",
    "serverTarget": "latest-project:server",
    "route": "shell"
  },
  "configurations": {
    "production": {
      "browserTarget": "latest-project:build:production"
    }
  }
}
```

**Comment by prasannapattam** [comment]
I am getting enableProdMode() warning. Is this related to the server distribution?
