### ISSUE TITLE
 Cannot read property 'controls' of null

### ISSUE THREAD

**Issue by nbansal1** [angular/angular-cli#11584]
<form >
<input type="text" class="form-control"
(keyup.enter)="onAdd()"
>
<ul class="list-group">
  <li 
  *ngFor="let topic of form.get('topic').controls"
  class="list-group">
  {{topic.value}}
</li>
</ul>
</form>?

**Comment by filipesilva** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
