### ISSUE TITLE
inputs defined in Component metadata not recognized when running ng test

### ISSUE THREAD

**Issue by gatimus** [angular/angular-cli#11585]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
```
Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.0
@angular/cli                      6.0.8
@angular/material                 6.4.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```
Windows 10

### Repro steps
Write a component that uses an input defined in Component metadata or use [MatButton](https://material.angular.io/components/button/api#MatButton) and it's `color` input.

duplication repo: https://github.com/gatimus/color-bind

`ng serve` > success
`ng test` > error

### The log given by the failure

> Can't bind to 'someProp' since it isn't a known property of 'app-some'.
or
> Can't bind to 'color' since it isn't a known property of 'button'.

### Desired functionality
`ng test` succeed like `ng serve`

**Comment by gatimus** [comment]
Using an input defined in Component metadata may be uncommon and goes against the [styleguide](https://angular.io/guide/styleguide#decorate-input-and-output-properties) but material2 is a very common library inputs defined in Component metadata is common there due to mixins.

**Comment by alan-agius4** [comment]
I think this is expected to fail. 

The reason being is that in your Unit Tests, you are not importing the component declaration nor using `NO_ERRORS_SCHEMA`. The `serve` is working due to the fact that it is using the `AppModule`, but the tests are not, since for the `spec` each component is bootstrap using a different module.

To fix this, you should add the `SomeComponent` in the declarations https://github.com/gatimus/color-bind/blob/master/src/app/app.component.spec.ts#L5, or add `NO_ERRORS_SCHEMA` 

Example;

```ts
TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      schemas: [
        NO_ERRORS_SCHEMA
      ]
    }).compileComponents();
```

**Comment by gatimus** [comment]
So should the materials install schematics add `NO_ERRORS_SCHEMA` too all the spec files? Or is the exception that out of the box `ng new`, `ng add @angular/material` follow doc to implement button `ng test` to succeed to specific?

**Comment by gatimus** [comment]
May continue in material2 issue.

**Comment by alan-agius4** [comment]
You'd need to import the material module in the spec file. ex;

```ts
TestBed.configureTestingModule({
      imports: [
         MatButton
      ],
      declarations: [
        AppComponent
      ]
}).compileComponents();
```

**Comment by gatimus** [comment]
@alan-agius4 edit `MatButtonModule`

**Comment by alan-agius4** [comment]
Opps yeah, I didnt' know that by heart. More details about testing can be found here: https://angular.io/guide/testing#nested-component-tests
