### ISSUE TITLE
Deprecated Switches are not updated in Continuous Integration Story Wiki

### ISSUE THREAD

**Issue by jsgoupil** [angular/angular-cli#11582]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- wiki
```
Your page https://github.com/angular/angular-cli/wiki/stories-continuous-integration is outdated
I can't find how to get the Circle-CI to run properly with all these ng test switch that have been deprecated in Angular 6

**Comment by filipesilva** [comment]
Heya, we recently merged https://github.com/angular/angular-cli/pull/11492 which should update that story. It will be published when re release 6.1.

**Comment by bartvanderwal** [comment]
The docs on testing at angular.io still mention/instruct to use the `--browser` option instead of `--browsers`. And also the --single-run option, which I understand should now be `--watch=false`

Source: https://angular.io/guide/testing#configure-cli-for-ci-testing-in-chrome

This instruction:
>ng test --single-run --no-progress --browser=ChromeHeadlessCI

Should now be:
>ng test --watch=false --no-progress --browsers=ChromeHeadlessCI

**Comment by bartvanderwal** [comment]
But the next line in the docs source mentions also returns  two now missing cli options in the current ng cli `7.0.7` that I'm using:
>ng e2e --no-progress --config=protractor-ci.conf.js

returns:
`Unknown option: '--no-progress'`
`Unknown option: '--config'`

And I can't find replacements as quickly.

**Comment by bartvanderwal** [comment]
Can this issue be reopened on v7? Or should I post the above in a new issue? @filipesilva
