### ISSUE TITLE
Page elements (text, images) appear smaller when run using "ng serve"

### ISSUE THREAD

**Issue by jalbr74** [angular/angular-cli#11580]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```
I apologize, I'm not sure which to choose here.

### Versions

Node: v8.9.4
NPM: 5.6.0
Windows 10
@angular/cli@6.0.8

### Repro steps

This can be reproduced quickly using a newly-generated project, and three separate terminals.  First, create a new project and serve it up:
```
$ ng new hello
$ cd hello
$ ng serve --prod
```

In a 2nd terminal, build the project in watch mode:
```
$ ng build --watch
```

In a 3rd terminal, use live-server to serve up the built files:
```
$ cd dist/hello
$ live-server
```

Open both up in a browser, and switch back and forth between tabs opened at: http://localhost:4200/, and http://127.0.0.1:8080/.

Here's a video demonstrating the difference I'm seeing:
https://www.dropbox.com/s/ra13p0n6a0wngi1/ng-serve-difference.webm?dl=0

### Desired functionality

The page rendered using "ng serve" should look the same as the page rendered using "ng build --watch" and "live-server".

### Mention any other details that might be useful

I was pulling my hair out trying to figure out why all the styles I was applying were rendering too small.  However, when I performed a build of the project everything looked correct.  So I decided to do an experiment to see if serving up the project two different ways yielded different results.  When it did, I figured I'd better report it as an issue.

**Comment by filipesilva** [comment]
Heya, looking at your video you seem to have `localhost:4200` zoomed out in chrome:
![image](https://user-images.githubusercontent.com/4172079/42952055-8128063e-8b6f-11e8-9b05-85140488a475.png)

You can click the magnifier icon to reset the zoom.

**Comment by jalbr74** [comment]
I can't believe I didn't see that.  How embarrassing 

```
. . . . . .. . . . . . . . . . . ,.-‘”. . . . . . . . . .“~.,
. . . . . . . .. . . . . .,.-”. . . . . . . . . . . . . . . . . .“-.,
. . . . .. . . . . . ..,/. . . . . . . . . . . . . . . . . . . . . . . ”:,
. . . . . . . .. .,?. . . . . . . . . . . . . . . . . . . . . . . . . . .\,
. . . . . . . . . /. . . . . . . . . . . . . . . . . . . . . . . . . . . . ,}
. . . . . . . . ./. . . . . . . . . . . . . . . . . . . . . . . . . . ,:`^`.}
. . . . . . . ./. . . . . . . . . . . . . . . . . . . . . . . . . ,:”. . . ./
. . . . . . .?. . . __. . . . . . . . . . . . . . . . . . . . :`. . . ./
. . . . . . . /__.(. . .“~-,_. . . . . . . . . . . . . . ,:`. . . .. ./
. . . . . . /(_. . ”~,_. . . ..“~,_. . . . . . . . . .,:`. . . . _/
. . . .. . {.._ ;_. . .”=,_. . . .“-,_. . . ,.-~-,}, .~”; /. .. .}
. . .. . .((. . .*~_. . . .”=-._. . .“;,,./`. . /” . . . ./. .. ../
. . . .. . .\`~,. . ..“~.,. . . . . . . . . ..`. . .}. . . . . . ../
. . . . . .(. ..`=-,,. . . .`. . . . . . . . . . . ..(. . . ;_,,-”
. . . . . ../.`~,. . ..`-.. . . . . . . . . . . . . . ..\. . /\
. . . . . . \`~.*-,. . . . . . . . . . . . . . . . . ..|,./…..\,__
,,_. . . . . }.>-._\. . . . . . . . . . . . . . . . . .|. . . . . . ..`=~-,
. .. `=~-,_\_. . . `\,. . . . . . . . . . . . . . . . .\
. . . . . . . . . .`=~-,,.\,. . . . . . . . . . . . . . . .\
. . . . . . . . . . . . . . . . `:,, . . . . . . . . . . . . . `\. . . . . . ..__
. . . . . . . . . . . . . . . . . . .`=-,. . . . . . . . . .,%`>–
```
