### ISSUE TITLE
Github deployment failed

### ISSUE THREAD

**Issue by bampakoa** [angular/angular-cli#1158]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
_Windows 10_

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
_angular-cli: 1.0.0-beta.6
node: 4.4.2
os: win32 x64_

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
_I created a new application using the CLI, I switched to the working directory and then without any change I tried to deploy it to the GitHub using `ng github-pages:deploy`. I entered my personal token and my username and then pressed Enter._

4. The log given by the failure. Normally this include a stack trace and some
   more information.
_Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "git push origin gh-pages:gh-pages"
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)_

5. Mention any other details that might be useful.
_The repository was created successfully though._

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
To use the deploy feature you need to have ssh keys configured, as per https://github.com/angular/angular-cli#deploying-the-app-via-github-pages. That error is usually due to missing ssh keys, can you double check?

**Comment by bampakoa** [comment]
Oh, I see what you mean. I totally missed that part! Does it also support access through HTTPS?

**Comment by filipesilva** [comment]
Not right now, no. We don't want to ask people for passwords so opted for ssh only.

**Comment by maxbellec** [comment]
I am using ssh, and having the same issue
git remote -v outputs:
    
    origin	git@github.com:maxbellec/***.git (fetch)
    origin	git@github.com:maxbellec/***.git (push)

any idea about why this is happening?

**Comment by filipesilva** [comment]
@maxbellec not sure tbh, would need more information. Can you open a new issue?

**Comment by maxbellec** [comment]
@filipesilva thanks for your reply, fixed it by now by doing `ssh-add /path/to/my/key` (I had an SSH key, but it was not known to the ssh-agent for some reason, and it never prevented git to work for any other stuff).
For others having the same issue, read http://stackoverflow.com/a/28444641/3218806

**Comment by filipesilva** [comment]
Glad to hear you got it sorted!
