### ISSUE TITLE
Need help , i am trying to setup Angular 5 installation error  "npm install -g angular/cli@1.5.0 npm ERR! code ENOLOCAL npm ERR! Could not install from when i run npm install angular\cli@1.5.0       "angular\cli@1.5.0" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by sandeepmulukala** [angular/angular-cli#11589]
![image](https://user-images.githubusercontent.com/41391837/42906646-8d6d15fe-8a90-11e8-83a1-96dcf241f88c.png)

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
```

**Comment by hansl** [comment]
Looks like you really want to `npm install -g @angular/cli@1.5.0` (notice the `@` on `@angular`).

**Comment by sandeepmulukala** [comment]
@hansl Yeah got it thanks.. And now i had this issue    after runing it , it installed but when i check the ng -v i see these error
![image](https://user-images.githubusercontent.com/41391837/42913236-0a4e34a2-8ab1-11e8-8ae6-4cab49d472ec.png)

**Comment by sandeepmulukala** [comment]
@hansl  Thank you its working now, but i have other issue when i run ng serve
![image](https://user-images.githubusercontent.com/41391837/42915850-800224ca-8abf-11e8-849b-31c96e82cb59.png)
