### ISSUE TITLE
ng generate - not working as it used to

### ISSUE THREAD

**Issue by ChrisDevinePimss** [angular/angular-cli#11593]
### Bug Report 
- [x] bug report 

### Area
- [x ] devkit

### Versions
NODE: v8.9.4
NPM: v5.6.0
WINDOWS 10
Angular 6

### Repro steps
When trying to run a "ng g c <PATH>" command, i keep getting invalid or cannot find module. example code: 
"ng g c asset\asset-attributes\asset-type-attributes-list"

This used to create the folder in the path if they never existed and use the module closest in the path hierarchy. 

Now it throw an error and requires you the cmd to be in the path location before running, as seen in code example: 
"F:\project\src\app\asset\asset-attributes>  ng g c asset-type-attributes-list"

### The log given by the failure
error 1 if using a long path 
Selector (app-asset-attributes\asset-type-attributes-list) is invalid.
error 2 if not app folder
Could not find an NgModule. Use the skip-import option to skip importing in NgModule.

### Desired functionality
work how it used to and is mentioned above

**Comment by rahuls** [comment]
Facing the same issue in Linux(Manjaro). Unable to find a solution. I have tried running ng g c component in another terminal session but alas, it keeps saying the selector is invalid. Is there any solution for this?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
