### ISSUE TITLE
i18n tag break properties verification/validation AOT Mode

### ISSUE THREAD

**Issue by wupaz** [angular/angular-cli#11598]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ ] schematics
- [X] build
```

### Versions
Windows 10, version 1803
node --version :: v8.9.4
npm --version :: 5.6.0

### Repro steps

If I build in AOT this code (Partial) 

```
...
<div> Line 1: {{customer.Name}} </div>
<div i18n="@@customerName"> Line 2: {{customer.Name}} </div>
...

```
I got an error on **Line 1** because customer didn't have Name properties. But I didn't get an error on **line 2**. This is not normal !

Build command : 
ng build -bh /projectname/en/ --aot --sm -oh=all --i18nFile=src/locale/messages.en.xlf --i18nFormat=xlf --locale=en

### The log given by the failure
no log 

### Desired functionality
I expect I got an compile error on line 2 (see sample in Repro steps)

**Comment by filipesilva** [comment]
Moved this issue to the main Angular tracker: https://github.com/angular/angular/issues/24995

Please subscribe to that issue for updated.
