### ISSUE TITLE
Angular 6 build outputs different bundle size with --verbose than without

### ISSUE THREAD

**Issue by P3tronius** [angular/angular-cli#11597]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
Angular CLI: 6.0.8
Node: 8.11.2
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.0
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

### Repro steps
Since ng 6, we have different bundle sizes when using --verbose flag.

### The log given by the failure:
> ng build --prod --source-map

Date: 2018-07-19T14:22:21.217Z
Hash: 51752f5ef1984a124cbb
Time: 22625ms
chunk {main} main.js, main.js.map (main) 2.74 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 1.03 MB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 1.75 MB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.55 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 5.54 MB [initial] [rendered]

 > ng build --prod --source-map --verbose

[...]
index.html    1.28 KiB             [emitted]
Entrypoint main [big] = runtime.js runtime.js.map vendor.js vendor.js.map main.js main.js.map
Entrypoint polyfills [big] = runtime.js runtime.js.map polyfills.js polyfills.js.map
Entrypoint styles [big] = runtime.js runtime.js.map styles.js styles.js.map
Entrypoint scripts [big] = scripts.js scripts.js.map
chunk {main} main.js, main.js.map (main) 2.3 MiB ={runtime}= ={vendor}= [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 854 KiB ={runtime}= [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 0 bytes ={main}= ={polyfills}= ={styles}= ={vendor}= [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 0 bytes [rendered]
chunk {styles} styles.js, styles.js.map (styles) 2.42 MiB ={runtime}= [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.74 MiB ={main}= ={runtime}= [initial] [rendered] split chunk (cache group: vendor) (name: vendor)

**Comment by Petronious** [comment]
Same goes without --source-map

**Comment by filipesilva** [comment]
I think this might be bad reporting instead of files actually being of different sizes.

Running builds on a new I did indeed see differences in the console output between `ng build --prod`, `ng build --prod --source-map` and `ng build --prod --verbose`.

Checking the output directories however, I saw no difference in file sizes.

**Comment by Petronious** [comment]
Oh you're right, it's indeed only in the console output, the files are have same sizes on disk.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
