### ISSUE TITLE
ng build --prod: WARNING in Invalid property name '[class*="col-"] { 

### ISSUE THREAD

**Issue by RoBak42** [angular/angular-cli#11592]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

Angular CLI: 6.0.8
npm: 6.1.0

### Repro steps

Created new project with `ng new ng6test` and added the following code in `src/styles.css`:
```
.no-padding {
    [class*="col-"] {
        padding-left: 0 !important;
        padding-right: 0 !important;
    }
}

.table-nowrap {
    white-space: nowrap;
}
```

### The log given by the failure

Building with `node_modules\.bin\ng build --prod` results in:
```
Date: 2018-07-19T07:55:13.417Z
Hash: 19bfb55bd559b0688fc2
Time: 12827ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.c2beba92f6b81f12b611.css (styles) 38 bytes [initial] [rendered]
chunk {2} polyfills.2f4a59095805af02bd79.js (polyfills) 59.6 kB [initial] [rendered]
chunk {3} main.c90dd6c6837f01338918.js (main) 158 kB [initial] [rendered]

WARNING in Unexpected '}' at 8:0.

WARNING in Invalid property name '[class*="col-"] {
        padding-left' at 4:4. Ignoring.

WARNING in Invalid selector '}

.table-nowrap' at 8:0. Ignoring.
```

### Desired functionality

The CSS loader(s)/packer(s) should understand ...`[class*="col-"]`...

**Comment by clydin** [comment]
The selector syntax is not actually the issue.  The actual problem is that CSS does not support nested rules.  As a result the selector is being treat as a property (which of course does not exist).  This is working as intended.  Options are to either remove the nesting or switch to a CSS preprocessor that supports it (e.g., SCSS).

**Comment by jamsheedpk** [comment]
WARNING in Unexpected '}' at 13099:0.

WARNING in Invalid property name '@include bp(5) {
      width' at 13082:2. Ignoring.

WARNING in Invalid selector '}
    .toggle-link-grey' at 13099:0. Ignoring.


 issue fixed 

angular.json   /    angular_cli.json 

css problem  
:+1:  replace  un supported  csss
 "styles": [
              ......................,
..............................
            ],

plz check
