### ISSUE TITLE
getting error 404 not find

### ISSUE THREAD

**Issue by nbansal1** [angular/angular-cli#11602]
import { PostService } from './../services/post.service';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-posts',
  templateUrl: './posts.component.html',
  styleUrls: ['./posts.component.css']
})
export class PostsComponent implements OnInit {
  posts : any[];
  
  constructor(private service : PostService) { 
    
  }
  ngOnInit(){
   this.service.getPost()
    .subscribe(response => {
    this.posts = response.json();
     });
  }
  createPost(input : HTMLInputElement){
    let post = {title : input.value};
    input.value='';
     this.service.createPost(post)
     .subscribe(response =>{
       post['id'] = response.json().id;
       this.posts.splice(0,0,post);
     }
    );
  }
   updatePost(post){
     this.service.updatePost(post)
     .subscribe(response => {
       console.log(response.json());

     })

   }
   deletePost(post){
    this.service.deletePost(post.id)
     .subscribe(response =>{
       let index = this.posts.indexOf(post);
       this.posts.splice(index , 1);
     } 
    )
   }

}
![capture](https://user-images.githubusercontent.com/41234207/42961160-95e7b754-8bab-11e8-8522-3d0d22a6c02f.JPG)

**Comment by arnavvats** [comment]
Check the url you are hitting in your getPost method in the PostService.

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
