### ISSUE TITLE
Website: The Learn Angular link in the bottom bar points to wwww.angular.io ... which doesn't work

### ISSUE THREAD

**Issue by benlesh** [angular/angular-cli#11619]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
### Repro steps
Navigate to cli.angular.io, and try to click the `Learn Angular` link at the bottom of the page.

### What happens?

Womp womp. It goes nowhere fast.

### Desired functionality
It should navigate to  angular.io

### Mention any other details that might be useful
Special thanks to [Ahmet Omer for tweeting about this](https://twitter.com/ahmetomerv/status/1020455005835485184)

**Comment by Brocco** [comment]
Assigning this to @hansl this [site](https://cli.angular.io/) is not part of the public repo.

**Comment by Brocco** [comment]
Also, this issue exists on the main angular repo... angular/angular#23381

**Comment by hansl** [comment]
This is a dupe of angular/angular#23381
