### ISSUE TITLE
ng e2e should include the Jasmine specDone result field "duration"

### ISSUE THREAD

**Issue by cgreczkowski** [angular/angular-cli#11614]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

Node v8.11.1, Windows 10

Run the following:
ng e2e --config="/path/to/protractor/conf"
In any Jasmine reporter, examine the 'result' object passed to specDone().

### Desired functionality

The "duration" field of the Jasmine specDone result is not present. This field should contain the execution time of the associated spec, eg. "12 secs".

Running 'protractor /path/to/protractor/conf' yields the desired result object, with duration included. Unsure why running protractor tests these two ways would yield different results, when everything else remains the same.

Calling:
`ng e2e --config="/path/to/protractor/conf"`
Gives the specDone result: 
`failedExpectations:[]
description: should pass the test
fullName: This suite should pass the test
pendingReason:
id: spec0
status: passed
deprecationWarnings:
passedExpectations: [...]`

Calling:
`protractor /path/to/protractor/conf`
Gives the specDone result: 
`duration: 13 secs
failedExpectations:[]
description: should pass the test
fullName: This suite should pass the test
pendingReason:
id: spec0
status: passed
deprecationWarnings:
passedExpectations: [...]`

**Comment by filipesilva** [comment]
Heya, I tried to reproduce this problem and could not. 

I edited the default reporter in a new CLI project, `./node_modules/jasmine-spec-reporter/built/spec-reporter.js`, to print `result`:
```
    SpecReporter.prototype.specDone = function (result) {
      console.log(result)
        this.metrics.stopSpec(result);
        if (result.status === "pending") {
        // ...
```

I could not see the `duration` field with neither `ng e2e` or `protractor` directly:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/latest-project (master)
$ ng e2e
[13:48:44] I/update - chromedriver: file exists D:\sandbox\latest-project\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.41.zip
[13:48:44] I/update - chromedriver: unzipping chromedriver_2.41.zip
[13:48:45] I/update - chromedriver: chromedriver_2.41.exe up to date
(node:16312) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[13:48:45] I/launcher - Running 1 instances of WebDriver
[13:48:45] I/direct - Using ChromeDriver directly...
[0807/134846.625:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:52203/devtools/browser/8cda5932-bd60-4181-a6be-e438047642f7
Jasmine started
[0807/134848.853:INFO:CONSOLE(34165)] "Angular is running in the development mode. Call enableProdMode() to enable the production mode.", source: http://localhost:4200/vendor.js (34165)
{ id: 'spec0',
  description: 'should display welcome message',
  fullName: 'workspace-project App should display welcome message',
  failedExpectations: [],
  passedExpectations:
   [ { matcherName: 'toEqual',
       message: 'Passed.',
       stack: '',
       passed: true } ],
  pendingReason: '',
  status: 'passed' }

  workspace-project App
    √ should display welcome message

Executed 1 of 1 spec SUCCESS in 0.811 sec.
[13:48:49] I/launcher - 0 instance(s) of WebDriver still running
[13:48:49] I/launcher - chrome #01 passed

kamik@RED-X1C6 MINGW64 /d/sandbox/latest-project (master)
$ npm run e2e

> latest-project@0.0.0 e2e D:\sandbox\latest-project
> protractor ./e2e/protractor.conf.js

(node:14852) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[13:49:22] I/launcher - Running 1 instances of WebDriver
[13:49:22] I/direct - Using ChromeDriver directly...
[0807/134923.522:ERROR:gpu_process_transport_factory.cc(1016)] Lost UI shared context.

DevTools listening on ws://127.0.0.1:52236/devtools/browser/09f86a24-ed1a-4577-a337-f63d04b7222d
Jasmine started
[0807/134925.753:INFO:CONSOLE(34165)] "Angular is running in the development mode. Call enableProdMode() to enable the production mode.", source: http://localhost:4200/vendor.js (34165)
{ id: 'spec0',
  description: 'should display welcome message',
  fullName: 'workspace-project App should display welcome message',
  failedExpectations: [],
  passedExpectations:
   [ { matcherName: 'toEqual',
       message: 'Passed.',
       stack: '',
       passed: true } ],
  pendingReason: '',
  status: 'passed' }

  workspace-project App
    √ should display welcome message

Executed 1 of 1 spec SUCCESS in 0.806 sec.
[13:49:25] I/launcher - 0 instance(s) of WebDriver still running
[13:49:25] I/launcher - chrome #01 passed
```

Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by filipesilva** [comment]
Closing as there's no repro do go on with.
