### ISSUE TITLE
404 Not Found while running ng update after installing @angular/cli@6.0.8

### ISSUE THREAD

**Issue by adityashukla74** [angular/angular-cli#11611]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.9
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect                 0.6.8
@angular-devkit/build-angular         0.6.8
@angular-devkit/build-optimizer      0.6.8
@angular-devkit/core                        0.6.8
@angular-devkit/schematics            0.6.8
@angular/cli                                       6.0.8
@angular/language-service              5.2.11
@ngtools/webpack                            6.0.8
@schematics/angular                        0.6.8
@schematics/update                         0.6.8
rxjs                                                    6.2.1
typescript                                         2.7.2
webpack                                          4.16.0

<img width="599" alt="screen shot 2018-07-20 at 5 08 28 pm" src="https://user-images.githubusercontent.com/11692248/43001188-ed3c7206-8c41-11e8-8bab-55ff734c2bfa.png">

### Repro steps

- Open an existing project
- Update Angular 5 to Angular 6
- Try to run the app, and get this error message :
- 404 Not Found

### The log given by the failure

404 Not Found
### Mention any other details that might be useful
I tried updating my project using the following commands
npm cache verify
npm i -g @angular/cli@latest
npm i @angular/cli@latest
npm install
ng update

### Abnormal Behaviour 

<img width="1256" alt="screen shot 2018-07-20 at 5 01 06 pm" src="https://user-images.githubusercontent.com/11692248/43001129-ba4eb796-8c41-11e8-88af-47090272f4da.png">

Running ng update command again and again, shows that it marks absent one of the many dependencies randomly.
<img width="993" alt="screen shot 2018-07-20 at 5 37 06 pm" src="https://user-images.githubusercontent.com/11692248/43001639-8e9f7494-8c43-11e8-8f9f-cc4853c0fa96.png">

**Comment by adityashukla74** [comment]
Anyone?

**Comment by Brocco** [comment]
We are not able to determine what is going on here with the information provided, please provide either a link to the repo or at least your `angular.json` file

**Comment by adityashukla74** [comment]
#11684 Angular.json 

``{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "dice-ui-cli": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/dice-ui-cli",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "dice-ui-cli:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "dice-ui-cli:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "dice-ui-cli:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "dice-ui-cli-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "dice-ui-cli:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "dice-ui-cli:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "dice-ui-cli"
}''

# I think there is a problem with **schematics**, not being able to recursively recognize already installed packages. 
Problem persists after creating new applications also while doing **ng update**

**Comment by adityashukla74** [comment]
Any update on this?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by rjoseph2** [comment]
logs/2018-12-13T15_08_07_329Z-debug.log
11 verbose stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
11 verbose stack     at processImmediate (timers.js:632:19)
12 verbose cwd /Users/rjoseph/workspace/iornics/myApp
13 verbose Darwin 18.2.0
14 verbose argv "/usr/local/Cellar/node/11.3.0_1/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/angular-cli"
15 verbose node v11.4.0
16 verbose npm  v6.4.1
17 error code E404
18 error 404 Not Found: @angular/angular-cli@latest
19 verbose exit [ 1, true ]

**Comment by rjoseph2** [comment]
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/11.3.0_1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 18.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/11.3.0_1/bin/node" "/usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/Cellar/node/11.3.0_1/lib/node_modules/@angular/cli/node_modules/fsevents
node-pre-gyp ERR! node -v v11.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/11.3.0_1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
