### ISSUE TITLE
Uncaught TypeError: Cannot read property 'defineProperty' of undefined after building project

### ISSUE THREAD

**Issue by naraharig** [angular/angular-cli#11625]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> 
Application built using **ng build --prod --base-href=".../PjAssy/SiteAssets/PJ/"** which is deployed to sharePoint is not loading with the error TypeError: Cannot read property 'defineProperty' of undefined after building project
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

ng build --prod --base-href=".../PjAssy/SiteAssets/PJ/"
```

### The log given by the failure
main.6aecf7dd8c6704e072b7.bundle.js:1 Uncaught TypeError: Cannot read property 'defineProperty' of undefined
    at main.6aecf7dd8c6704e072b7.bundle.js:1
    at Object.cDNt (main.6aecf7dd8c6704e072b7.bundle.js:1)
    at o (inline.08778ffafc652e2fbf55.bundle.js:1)
    at Object.1 (main.6aecf7dd8c6704e072b7.bundle.js:1)
    at o (inline.08778ffafc652e2fbf55.bundle.js:1)
    at window.webpackJsonp (inline.08778ffafc652e2fbf55.bundle.js:1)
    at main.6aecf7dd8c6704e072b7.bundle.js:1

### Desired functionality
My desfault page should be loaded.

### Mention any other details that might be useful
I was using typescript@2.5.3 while start of the aimplementation along with this is used SP-rest-proxy package. which was not working properly, so i updated it to latest fixed version. after that i was getting error with @angular/types/bludebird/index.d.ts which was vanished after typescript update and nodemodule complete removal and reinstallation.
after reinstallation everything works locally but production build failes to show data.
tried to go back to previous version of typescript: 
	tired typescript versions:  
	2.5.2
	2.4.2
	2.5.0
	2.6.2
	2.5.3
	2.4.1
	2.9.2  ng serve works ng build is also succeded after build on page load getting the following error.

My package.json dependencies list: 
"private": true,
  "dependencies": {
    "@angular/animations": "^5.2.11",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.2.11",
    "@angular/compiler": "^5.2.11",
    "@angular/core": "^5.2.11",
    "@angular/flex-layout": "^5.0.0-beta.15",
    "@angular/forms": "^5.2.11",
    "@angular/http": "^5.2.11",
    "@angular/material": "^5.2.5",
    "@angular/material-moment-adapter": "^5.2.5",
    "@angular/platform-browser": "^5.2.11",
    "@angular/platform-browser-dynamic": "^5.2.11",
    "@angular/router": "^5.2.11",
    "@ng-bootstrap/ng-bootstrap": "^1.1.2",
    "angular4-material-table": "^0.2.0",
    "bootstrap": "^4.1.2",
    "chart.js": "^2.7.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.7",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "npm": "^6.2.0",
    "rxjs": "^5.5.11",
    "web-animations-js": "^2.3.1",
    "xlsx": "^0.12.13",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/cli": "1.6.6",
    "@angular/compiler-cli": "^5.2.11",
    "@angular/language-service": "^5.2.11",
    "@angularclass/hmr": "^2.1.3",
    "@types/jasmine": "^2.8.8",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.114",
    "codelyzer": "^4.4.2",
    "concurrently": "^3.6.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^2.0.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "sp-rest-proxy": "^2.7.0",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "^2.9.2"
  }

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
