### ISSUE TITLE
about web worker

### ISSUE THREAD

**Issue by z3214965** [angular/angular-cli#11624]
I want use web worker in angular6，what should I do？

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`. More your request doesn't fall under to Angular CLI project.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation.](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)

**Comment by filipesilva** [comment]
Closing as per @alan-agius4 comment 👍

**Comment by filipesilva** [comment]
There's also an issue on this topic here https://github.com/angular/angular-cli/issues/5885
