### ISSUE TITLE
propose that ng config should consider a default schematic

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#11634]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```

Angular CLI: 6.0.8
Node: 8.11.1
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

### Desired functionality

I was thinking this is a big leap for folks who never or rarely use schematics and just want to set to set something simple like new projects to have SASS as their default for components. Would be cool if there was a way to assume the default schematic if none is specified. Is that possible? If so I can open an issue.

So instead of ... `ng config schematics.@schematics/angular:component.styleext scss` ... `ng config component.styleext scss`

**Comment by nrdev88** [comment]
If those folks do not read the documentation, it's the end of a good programmer!

`ng new project --style scss`

**Comment by alan-agius4** [comment]
Hi @johnpapa,

Thanks for this feature request. However, consider the little activity this feature request received it doesn't warrant to be included in the Angular CLI.
