### ISSUE TITLE
ng update --all not working

### ISSUE THREAD

**Issue by mungpara** [angular/angular-cli#11635]
I run ng update --all command but it show below error.

Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.8", would install "2.9.2").

Incompatible peer dependencies found. See above.

**Comment by ivelfan** [comment]
Same error when I download the angular-cli repo and I launch `npm run test`.

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue #11387. Please subscribe to that issue for future updates.
