### ISSUE TITLE
@angular-devkit/build-optimizer/webpack-loader freeze when include angularfire2

### ISSUE THREAD

**Issue by vincent-cm** [angular/angular-cli#11639]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.0.8
Node: 10.6.0
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8 (cli-only)
@angular-devkit/build-optimizer   0.7.0-beta.1
@angular-devkit/core              0.6.8 (cli-only)
@angular-devkit/schematics        0.6.8 (cli-only)
@angular/cdk                      6.4.1
@angular/cli                      6.0.8
@angular/material                 6.4.1
@ngtools/webpack                  6.1.0-beta.1
@schematics/angular               0.6.8 (cli-only)
@schematics/update                0.6.8 (cli-only)
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.16.2

### Desired functionality

Build success with AoT

### Mention any other details that might be useful

**Potential bug found**

Conflict with @angular-devkit/build-optimizer/webpack-loader'

See below code snippet:

config buildOptimizerLoader
```
const buildOptimizerLoader = {
    loader: '@angular-devkit/build-optimizer/webpack-loader',
    options: {
      sourceMap
    }
  };
```

**execlude @firebase/database/dist from buildOptimizerLoader(AoT) build success in AoT mode**

```
const loaders = [{
      test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
      exclude: [helpers.root('node_modules', '@firebase/database/dist')],
      use: buildOptimizer ? [buildOptimizerLoader, '@ngtools/webpack'] : ['@ngtools/webpack']
    },
    ...buildOptimizer ? [{
      test: /\.js$/,
      exclude: [helpers.root('node_modules', '@firebase/database/dist')],
      use: [buildOptimizerLoader]
    }] : [],
    ...[{
      test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
      include: [helpers.root('node_modules', '@firebase/database/dist')],
      use: ['@ngtools/webpack']
    }]
  ];
```

But if not, the build will **freeze** at
69% building modules 1720/1726 modules 6 active …ient/node_modules/....js

**This can not be reproduced when the project is small.**

**Comment by filipesilva** [comment]
Do you have any reproduction, even on a big project, that we can look at?

Have you also tried increasing the memory limit? You can add the npm script below and then run `ng build --prod` to build it with 8gig max memory.
```
"ng-high-memory": "node--max_old_space_size=8192 --inspect --debug-brk ./node_modules/@angular/cli/bin/ng serve"
```

**Comment by robertbaker** [comment]
You should update those dependencies, they are quite out of date and stable versions exist...

**Comment by vincent-cm** [comment]
Fixed Angular6.1
