### ISSUE TITLE
Build specific lazy loaded user chunks

### ISSUE THREAD

**Issue by mistrykaran91** [angular/angular-cli#11638]
If I want to build specific lazy loaded user chunks, how can I achieve it because our app is quiet big because of which I'm not able to do prod build?

**Comment by filipesilva** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

You can use `import()` statements if you configure your `tsconfig.app.json` to use `"module": "esnext",`, but setting up lazy loading manually is not trivial.

**Comment by mistrykaran91** [comment]
Ok thanks, but is there any way I can resolve this, if any will be appreciated.
