### ISSUE TITLE
Testing (ng test) fails on docker only

### ISSUE THREAD

**Issue by FlyingWraptor** [angular/angular-cli#11647]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [X] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
NodeJS:  `v8.10.0`
NPM: `3.5.2`
Angular CLI: `6.0.8` (Angular 6.0.9)
Docker: `18.06.0-ce`, build `0ffa825`
Host: Ubuntu 18.04 LTS

Container: wraptor/npm-chrome

### Repro steps
Create a couple of default tests using services, components etc.

### The log given by the failure
Desktop build (Windows linux subsystem ubuntu bash):
> wraptor@PC-Wraptor:/mnt/d/Developement/Git/Angular/Wheezie/Wheezie-Frontend$ ./node_modules/@angular/cli/bin/ng test --watch false --progress false
> (node:573) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> 24 07 2018 22:27:56.250:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
> 24 07 2018 22:27:56.254:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
> 24 07 2018 22:27:56.264:INFO [launcher]: Starting browser Chrome
> 24 07 2018 22:28:04.046:INFO [HeadlessChrome 67.0.3396 (Linux 0.0.0)]: Connected on socket OoPNs1huY2JVMx_tAAAA with id 91895679
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 12 of 12 SUCCESS (0.712 secs / 0.724 secs)

Docker test:

> $ ./node_modules/@angular/cli/bin/ng test --watch false --progress false
> (node:11) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> 24 07 2018 16:54:08.140:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
> 24 07 2018 16:54:08.143:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
> 24 07 2018 16:54:08.151:INFO [launcher]: Starting browser Chrome
> 24 07 2018 16:54:26.318:INFO [HeadlessChrome 67.0.3396 (Linux 0.0.0)]: Connected on socket cWNPXY1q_5RIJLsnAAAA with id 23845975
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 0 of 12 SUCCESS (0 secs / 0 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 1 of 12 SUCCESS (0 secs / 0.099 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 2 of 12 SUCCESS (0 secs / 0.324 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 3 of 12 SUCCESS (0 secs / 0.586 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 4 of 12 SUCCESS (0 secs / 0.696 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 5 of 12 SUCCESS (0 secs / 1.039 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0) HttpService should be created FAILED
> 	[object ErrorEvent] thrown
> HeadlessChrome 67.0.3396 (Linux 0.0.0) HttpService should be created FAILED
> 	[object ErrorEvent] thrown
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 6 of 12 (1 FAILED) (0 secs / 1.139 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0) HttpService should be created FAILED
> 	[object ErrorEvent] thrown
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 7 of 12 (1 FAILED) (0 secs / 1.182 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 8 of 12 (1 FAILED) (0 secs / 1.353 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 9 of 12 (1 FAILED) (0 secs / 1.44 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 10 of 12 (1 FAILED) (0 secs / 1.456 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 11 of 12 (1 FAILED) (0 secs / 1.488 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 12 of 12 (1 FAILED) (0 secs / 1.509 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 12 of 12 (1 FAILED) (1.741 secs / 1.509 secs)

Commenting out the HttpService Service component's testing functions results in the next in chain to fail:

> $ ./node_modules/@angular/cli/bin/ng test --watch false --progress false
> (node:12) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
> 24 07 2018 20:16:51.515:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
> 24 07 2018 20:16:51.518:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
> 24 07 2018 20:16:51.528:INFO [launcher]: Starting browser Chrome
> 24 07 2018 20:17:10.713:INFO [HeadlessChrome 67.0.3396 (Linux 0.0.0)]: Connected on socket FATncIw0GAT1Oz2nAAAA with id 31134648
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 0 of 11 SUCCESS (0 secs / 0 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 1 of 11 SUCCESS (0 secs / 0.102 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 2 of 11 SUCCESS (0 secs / 0.38 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 3 of 11 SUCCESS (0 secs / 0.613 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 4 of 11 SUCCESS (0 secs / 0.743 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 5 of 11 SUCCESS (0 secs / 1.026 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0) LoadbarComponent should create FAILED
> 	[object ErrorEvent] thrown
> HeadlessChrome 67.0.3396 (Linux 0.0.0) LoadbarComponent should create FAILED
> 	[object ErrorEvent] thrown
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 6 of 11 (1 FAILED) (0 secs / 1.09 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0) LoadbarComponent should create FAILED
> 	[object ErrorEvent] thrown
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 7 of 11 (1 FAILED) (0 secs / 1.205 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 8 of 11 (1 FAILED) (0 secs / 1.286 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 9 of 11 (1 FAILED) (0 secs / 1.303 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 10 of 11 (1 FAILED) (0 secs / 1.327 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 11 of 11 (1 FAILED) (0 secs / 1.353 secs)
> HeadlessChrome 67.0.3396 (Linux 0.0.0): Executed 11 of 11 (1 FAILED) (1.568 secs / 1.353 secs)

### Desired functionality
It to work witout any issues in docker

### Mention any other details that might be useful
https://github.com/FlyingWraptor/docker--npm-chrome

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

You provided us with the docker image but no project. The repro steps of "Create a couple of default tests using services, components etc." aren't very good to reproduce, if it doesn't work on my machine then we'd have to do a back and forth until you provided me with the code that actually breaks.

This might also be related to https://github.com/angular/angular-cli/pull/11627. If so, it should work by using `@angular-devkit/build-angular@0.6.7` and the upcoming 6.1.1.

**Comment by FlyingWraptor** [comment]
I'm on @angular-devkit/build-angular@0.6.8.

The reconstruction isn't hard at all. All my tests are the default cli ng new's test files.

```typescript
it('should be created', inject([SomeService], (service: SomeService) => {
  expect(service).toBeTruthy();
}));
```

This applies to all components and services. etc.
Whenever I comment out the failing test the next test will fail. Always the 5th test.

**Comment by yusijs** [comment]
@FlyingWraptor any chance you can share your final dockerfile and karma config? I'm unable to run any tests in Docker because headless chrome fails for various reasons, and I've not spent 3-4 hours trying to get it working :|

**Comment by FlyingWraptor** [comment]
@yusijs I'm sorry I completely forgot about this issue, the project I was using had some dependencies locked at a specific version which caused the fail when building in docker.

My current docker file is based on the latest node image:
```
FROM node:latest

LABEL version="1.1.0" \
    description="A Docker instance running the latest (stable) Chrome and @angular/cli running on the latest node image." \
    maintainer="wraptor@wheezie.be"

RUN apt-get update -y && apt-get install -y wget libxss1 libindicator7 fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxtst6 lsb-release xdg-utils

# Chrome repository
RUN cd /tmp/
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN dpkg -i ./google-chrome*.deb
RUN rm ./google-chrome*.deb
RUN apt-get install -f
```

Current karma config:
```javascript
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '/',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      dir: require('path').join(__dirname, '../coverage'),
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['ChromeHeadless'],
    singleRun: true,
    customLaunchers: {
      ChromeHeadless: {
        base: 'Chrome',
        flags: [
          '--disable-web-security',
          '--no-sandbox',
          '--disable-setuid-sandbox',
          '--disable-dev-shm-usage',
          '--remote-debugging-port=9223',
          '--headless',
          '--disable-gpu',
        ]
      }
    }
  });
};
```

This works fine for me

**Comment by samirotiv** [comment]
@FlyingWraptor I am facing the same issue. Could you please tell me what dependencies those were??

**Comment by FlyingWraptor** [comment]
I don't fully recall but they where related to Karma and Jasmine

**Comment by filipesilva** [comment]
Thanks for reporting this issue. This issue was originally reported a long time ago and since then we've had many releases, one of which might have addressed this problem. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
