### ISSUE TITLE
ng new --dry-run vs --dryRun

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#11641]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps

`ng new foo --dry-run`
`ng new foo --dryRun`

### The log given by the failure
Both work. But the wiki says `--dry-run` and the `ng --help` says --dryRun`. 

### Desired functionality

Allow both, that's fine. But let's make it the docs consistent to say `--dry-run` if that is the preferred.

cc @Brocco as per previous chat

**Comment by TheSamsterZA** [comment]
Please take this as my vote for `--dry-run`.

**Comment by noelmace** [comment]
As I agree that both docs should be consistent, and, as we use it by default for schematics, dash case should always be the preferred, I quickly tried to test this, and it breaks the schema validation as I expected : https://github.com/noelmace/angular-cli/commit/b3e60841cb5f5ea345da8816c8b919b75afe9ffa

```
$ ng new foo --dry-run
Schematic input does not validate against the Schema: {"dryRun":true,"skipGit":true,"version":"6.1.0","skipInstall":false,"linkCli":false,"commit":true,"newProjectRoot":"projects","inlineStyle":false,"inlineTemplate":false,"routing":false,"prefix":"app","style":"css","skipTests":false}
Errors:

  Data path "" should NOT have additional properties(dryRun).
```

I'm not practiced enough with this high level schematic stuff, but as dryRun is a special, global kind of option, I suppose there is some code responsible of converting dash case to camel case which does not support the opposite, right?

**Comment by rlove** [comment]
This also applies to generate commands.

**Comment by alan-agius4** [comment]
This should be fixed in the new documentation available in https://angular.io/cli/
