### ISSUE TITLE
ng build -prod not genarating .js and .js.map files

### ISSUE THREAD

**Issue by enyachoke** [angular/angular-cli#1165]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS? Linux (Ubuntu 15.10)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
angular-cli: 1.0.0-beta.6
node: 5.4.1
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I switched from the default router to ngrx/router and https://github.com/auth0/angular2-jwt for authentication and a bunch of third party directives. If I run ng build the tree command generates all the necessary files and the app in the dist directory runs just fine.
dist$ tree
.
├── api
│   ├── in-memory-store.service.js
│   └── in-memory-store.service.js.map
├── app
│   ├── +class-rooms
│   │   ├── class-room
│   │   │   ├── class-room.component.css
│   │   │   ├── class-room.component.html
│   │   │   ├── class-room.component.js
│   │   │   ├── class-room.component.js.map
│   │   │   ├── class-room.component.spec.js
│   │   │   ├── class-room.component.spec.js.map
│   │   │   ├── index.js
│   │   │   └── index.js.map
│   │   ├── class-room-list
│   │   │   ├── class-room-list.component.css
│   │   │   ├── class-room-list.component.html
│   │   │   ├── class-room-list.component.js
│   │   │   ├── class-room-list.component.js.map
│   │   │   ├── class-room-list.component.spec.js
│   │   │   ├── class-room-list.component.spec.js.map
│   │   │   ├── index.js
│   │   │   └── index.js.map
│   │   ├── class-rooms.component.css
│   │   ├── class-rooms.component.html
│   │   ├── class-rooms.component.js
│   │   ├── class-rooms.component.js.map
│   │   ├── class-rooms.component.spec.js
│   │   ├── class-rooms.component.spec.js.map
│   │   ├── index.js
│   │   ├── index.js.map
│   │   └── shared
│   │       ├── class-room.model.js
│   │       ├── class-room.model.js.map
│   │       ├── class-room.model.spec.js
│   │       ├── class-room.model.spec.js.map
│   │       ├── class-room.service.js
│   │       ├── class-room.service.js.map
│   │       ├── class-room.service.spec.js
│   │       ├── class-room.service.spec.js.map
│   │       ├── class-room-subject.model.js
│   │       ├── class-room-subject.model.js.map
│   │       ├── class-room-subject.model.spec.js
│   │       ├── class-room-subject.model.spec.js.map
│   │       ├── class-room-subject.service.js
│   │       ├── class-room-subject.service.js.map
│   │       ├── class-room-subject.service.spec.js
│   │       ├── class-room-subject.service.spec.js.map
│   │       ├── index.js
│   │       └── index.js.map
│   ├── class-timings
│   │   ├── class-timings.component.css
│   │   ├── class-timings.component.html
│   │   ├── class-timings.component.js
│   │   ├── class-timings.component.js.map
│   │   ├── class-timings.component.spec.js
│   │   ├── class-timings.component.spec.js.map
│   │   ├── index.js
│   │   ├── index.js.map
│   │   └── shared
│   │       ├── class-timing.model.js
│   │       ├── class-timing.model.js.map
│   │       ├── class-timing.model.spec.js
│   │       ├── class-timing.model.spec.js.map
│   │       ├── class-timing.service.js
│   │       ├── class-timing.service.js.map
│   │       ├── class-timing.service.spec.js
│   │       ├── class-timing.service.spec.js.map
│   │       ├── index.js
│   │       └── index.js.map
│   ├── +dashboard
│   │   ├── dashboard.component.css
│   │   ├── dashboard.component.html
│   │   ├── dashboard.component.js
│   │   ├── dashboard.component.js.map
│   │   ├── dashboard.component.spec.js
│   │   ├── dashboard.component.spec.js.map
│   │   ├── dashboard-index.component.html
│   │   ├── dashboard-index.component.js
│   │   ├── dashboard-index.component.js.map
│   │   ├── index.js
│   │   ├── index.js.map
│   │   └── shared
│   │       ├── index.js
│   │       └── index.js.map
│   ├── datepicker.directive.js
│   ├── datepicker.directive.js.map
│   ├── datepicker.directive.spec.js
│   ├── datepicker.directive.spec.js.map
│   ├── environment.js
│   ├── environment.js.map
│   ├── index.js
│   ├── index.js.map
│   ├── +login
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── login.component.css
│   │   ├── login.component.html
│   │   ├── login.component.js
│   │   ├── login.component.js.map
│   │   ├── login.component.spec.js
│   │   ├── login.component.spec.js.map
│   │   └── shared
│   │       ├── auth.service.js
│   │       ├── auth.service.js.map
│   │       ├── auth.service.spec.js
│   │       ├── auth.service.spec.js.map
│   │       ├── index.js
│   │       ├── index.js.map
│   │       ├── login.model.js
│   │       ├── login.model.js.map
│   │       ├── login.model.spec.js
│   │       ├── login.model.spec.js.map
│   │       ├── profile.model.js
│   │       ├── profile.model.js.map
│   │       ├── profile.model.spec.js
│   │       └── profile.model.spec.js.map
│   ├── rxjs-operators.js
│   ├── rxjs-operators.js.map
│   ├── savannah-academia-angular.component.css
│   ├── savannah-academia-angular.component.html
│   ├── savannah-academia-angular.component.js
│   ├── savannah-academia-angular.component.js.map
│   ├── savannah-academia-angular.component.spec.js
│   ├── savannah-academia-angular.component.spec.js.map
│   ├── +settings
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── profile
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── profile.component.css
│   │   │   ├── profile.component.html
│   │   │   ├── profile.component.js
│   │   │   ├── profile.component.js.map
│   │   │   ├── profile.component.spec.js
│   │   │   └── profile.component.spec.js.map
│   │   ├── settings.component.css
│   │   ├── settings.component.html
│   │   ├── settings.component.js
│   │   ├── settings.component.js.map
│   │   ├── settings.component.spec.js
│   │   ├── settings.component.spec.js.map
│   │   ├── shared
│   │   │   ├── index.js
│   │   │   └── index.js.map
│   │   └── system
│   │       ├── index.js
│   │       ├── index.js.map
│   │       ├── system.component.css
│   │       ├── system.component.html
│   │       ├── system.component.js
│   │       ├── system.component.js.map
│   │       ├── system.component.spec.js
│   │       └── system.component.spec.js.map
│   ├── shared
│   │   ├── auth-guard.js
│   │   ├── auth-guard.js.map
│   │   ├── config.js
│   │   ├── config.js.map
│   │   ├── http.js
│   │   ├── http.js.map
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── router-config.js
│   │   ├── router-config.js.map
│   │   └── top-navigation
│   │       ├── index.js
│   │       ├── index.js.map
│   │       ├── top-navigation.component.css
│   │       ├── top-navigation.component.html
│   │       ├── top-navigation.component.js
│   │       ├── top-navigation.component.js.map
│   │       ├── top-navigation.component.spec.js
│   │       └── top-navigation.component.spec.js.map
│   ├── +student-groups
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── shared
│   │   │   ├── day.model.js
│   │   │   ├── day.model.js.map
│   │   │   ├── day.model.spec.js
│   │   │   ├── day.model.spec.js.map
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── student-group.model.js
│   │   │   ├── student-group.model.js.map
│   │   │   ├── student-group.model.spec.js
│   │   │   ├── student-group.model.spec.js.map
│   │   │   ├── student-group.service.js
│   │   │   ├── student-group.service.js.map
│   │   │   ├── student-group.service.spec.js
│   │   │   └── student-group.service.spec.js.map
│   │   ├── student-group
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── student-group.component.css
│   │   │   ├── student-group.component.html
│   │   │   ├── student-group.component.js
│   │   │   ├── student-group.component.js.map
│   │   │   ├── student-group.component.spec.js
│   │   │   └── student-group.component.spec.js.map
│   │   ├── student-group-list
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── student-group-list.component.css
│   │   │   ├── student-group-list.component.html
│   │   │   ├── student-group-list.component.js
│   │   │   ├── student-group-list.component.js.map
│   │   │   ├── student-group-list.component.spec.js
│   │   │   └── student-group-list.component.spec.js.map
│   │   ├── student-groups.component.css
│   │   ├── student-groups.component.html
│   │   ├── student-groups.component.js
│   │   ├── student-groups.component.js.map
│   │   ├── student-groups.component.spec.js
│   │   └── student-groups.component.spec.js.map
│   ├── +students
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── shared
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── student.model.js
│   │   │   ├── student.model.js.map
│   │   │   ├── student.model.spec.js
│   │   │   ├── student.model.spec.js.map
│   │   │   ├── student.service.js
│   │   │   ├── student.service.js.map
│   │   │   ├── student.service.spec.js
│   │   │   └── student.service.spec.js.map
│   │   ├── student
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── student.component.css
│   │   │   ├── student.component.html
│   │   │   ├── student.component.js
│   │   │   ├── student.component.js.map
│   │   │   ├── student.component.spec.js
│   │   │   └── student.component.spec.js.map
│   │   ├── student-list
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── student-list.component.css
│   │   │   ├── student-list.component.html
│   │   │   ├── student-list.component.js
│   │   │   ├── student-list.component.js.map
│   │   │   ├── student-list.component.spec.js
│   │   │   └── student-list.component.spec.js.map
│   │   ├── students.component.css
│   │   ├── students.component.html
│   │   ├── students.component.js
│   │   ├── students.component.js.map
│   │   ├── students.component.spec.js
│   │   └── students.component.spec.js.map
│   ├── +subjects
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── shared
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── subject.model.js
│   │   │   ├── subject.model.js.map
│   │   │   ├── subject.model.spec.js
│   │   │   ├── subject.model.spec.js.map
│   │   │   ├── subject.service.js
│   │   │   ├── subject.service.js.map
│   │   │   ├── subject.service.spec.js
│   │   │   └── subject.service.spec.js.map
│   │   ├── subject
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── subject.component.css
│   │   │   ├── subject.component.html
│   │   │   ├── subject.component.js
│   │   │   ├── subject.component.js.map
│   │   │   ├── subject.component.spec.js
│   │   │   └── subject.component.spec.js.map
│   │   ├── subject-list
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── subject-list.component.css
│   │   │   ├── subject-list.component.html
│   │   │   ├── subject-list.component.js
│   │   │   ├── subject-list.component.js.map
│   │   │   ├── subject-list.component.spec.js
│   │   │   └── subject-list.component.spec.js.map
│   │   ├── subjects.component.css
│   │   ├── subjects.component.html
│   │   ├── subjects.component.js
│   │   ├── subjects.component.js.map
│   │   ├── subjects.component.spec.js
│   │   └── subjects.component.spec.js.map
│   ├── +teachers
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── shared
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── teacher.model.js
│   │   │   ├── teacher.model.js.map
│   │   │   ├── teacher.model.spec.js
│   │   │   ├── teacher.model.spec.js.map
│   │   │   ├── teacher.service.js
│   │   │   ├── teacher.service.js.map
│   │   │   ├── teacher.service.spec.js
│   │   │   └── teacher.service.spec.js.map
│   │   ├── teacher
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── teacher.component.css
│   │   │   ├── teacher.component.html
│   │   │   ├── teacher.component.js
│   │   │   ├── teacher.component.js.map
│   │   │   ├── teacher.component.spec.js
│   │   │   └── teacher.component.spec.js.map
│   │   ├── teacher-list
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── teacher-list.component.css
│   │   │   ├── teacher-list.component.html
│   │   │   ├── teacher-list.component.js
│   │   │   ├── teacher-list.component.js.map
│   │   │   ├── teacher-list.component.spec.js
│   │   │   └── teacher-list.component.spec.js.map
│   │   ├── teachers.component.css
│   │   ├── teachers.component.html
│   │   ├── teachers.component.js
│   │   ├── teachers.component.js.map
│   │   ├── teachers.component.spec.js
│   │   └── teachers.component.spec.js.map
│   ├── +terms
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── shared
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── term.model.js
│   │   │   ├── term.model.js.map
│   │   │   ├── term.model.spec.js
│   │   │   ├── term.model.spec.js.map
│   │   │   ├── term.service.js
│   │   │   ├── term.service.js.map
│   │   │   ├── term.service.spec.js
│   │   │   └── term.service.spec.js.map
│   │   ├── term
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── term.component.css
│   │   │   ├── term.component.html
│   │   │   ├── term.component.js
│   │   │   ├── term.component.js.map
│   │   │   ├── term.component.spec.js
│   │   │   └── term.component.spec.js.map
│   │   ├── term-list
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── term-list.component.css
│   │   │   ├── term-list.component.html
│   │   │   ├── term-list.component.js
│   │   │   ├── term-list.component.js.map
│   │   │   ├── term-list.component.spec.js
│   │   │   └── term-list.component.spec.js.map
│   │   ├── terms.component.css
│   │   ├── terms.component.html
│   │   ├── terms.component.js
│   │   ├── terms.component.js.map
│   │   ├── terms.component.spec.js
│   │   └── terms.component.spec.js.map
│   ├── time.pipe.js
│   ├── time.pipe.js.map
│   ├── time.pipe.spec.js
│   ├── time.pipe.spec.js.map
│   ├── +users
│   │   ├── index.js
│   │   ├── index.js.map
│   │   ├── shared
│   │   │   ├── index.js
│   │   │   ├── index.js.map
│   │   │   ├── user.model.js
│   │   │   ├── user.model.js.map
│   │   │   ├── user.model.spec.js
│   │   │   ├── user.model.spec.js.map
│   │   │   ├── user.service.js
│   │   │   ├── user.service.js.map
│   │   │   ├── user.service.spec.js
│   │   │   └── user.service.spec.js.map
│   │   ├── users.component.css
│   │   ├── users.component.html
│   │   ├── users.component.js
│   │   ├── users.component.js.map
│   │   ├── users.component.spec.js
│   │   └── users.component.spec.js.map
│   └── +years
│       ├── index.js
│       ├── index.js.map
│       ├── shared
│       │   ├── index.js
│       │   ├── index.js.map
│       │   ├── year.model.js
│       │   ├── year.model.js.map
│       │   ├── year.model.spec.js
│       │   ├── year.model.spec.js.map
│       │   ├── year.service.js
│       │   ├── year.service.js.map
│       │   ├── year.service.spec.js
│       │   └── year.service.spec.js.map
│       ├── year
│       │   ├── index.js
│       │   ├── index.js.map
│       │   ├── year.component.css
│       │   ├── year.component.html
│       │   ├── year.component.js
│       │   ├── year.component.js.map
│       │   ├── year.component.spec.js
│       │   └── year.component.spec.js.map
│       ├── year-list
│       │   ├── index.js
│       │   ├── index.js.map
│       │   ├── year-list.component.css
│       │   ├── year-list.component.html
│       │   ├── year-list.component.js
│       │   ├── year-list.component.js.map
│       │   ├── year-list.component.spec.js
│       │   └── year-list.component.spec.js.map
│       ├── years.component.css
│       ├── years.component.html
│       ├── years.component.js
│       ├── years.component.js.map
│       ├── years.component.spec.js
│       └── years.component.spec.js.map

ng build -prod generates

dist$ tree
.
├── app
│   ├── +class-rooms
│   │   ├── class-room
│   │   │   ├── class-room.component.css
│   │   │   └── class-room.component.html
│   │   ├── class-room-list
│   │   │   ├── class-room-list.component.css
│   │   │   └── class-room-list.component.html
│   │   ├── class-rooms.component.css
│   │   └── class-rooms.component.html
│   ├── class-timings
│   │   ├── class-timings.component.css
│   │   └── class-timings.component.html
│   ├── +dashboard
│   │   ├── dashboard.component.css
│   │   ├── dashboard.component.html
│   │   └── dashboard-index.component.html
│   ├── +login
│   │   ├── login.component.css
│   │   └── login.component.html
│   ├── savannah-academia-angular.component.css
│   ├── savannah-academia-angular.component.html
│   ├── +settings
│   │   ├── profile
│   │   │   ├── profile.component.css
│   │   │   └── profile.component.html
│   │   ├── settings.component.css
│   │   ├── settings.component.html
│   │   └── system
│   │       ├── system.component.css
│   │       └── system.component.html
│   ├── shared
│   │   └── top-navigation
│   │       ├── top-navigation.component.css
│   │       └── top-navigation.component.html
│   ├── +student-groups
│   │   ├── student-group
│   │   │   ├── student-group.component.css
│   │   │   └── student-group.component.html
│   │   ├── student-group-list
│   │   │   ├── student-group-list.component.css
│   │   │   └── student-group-list.component.html
│   │   ├── student-groups.component.css
│   │   └── student-groups.component.html
│   ├── +students
│   │   ├── student
│   │   │   ├── student.component.css
│   │   │   └── student.component.html
│   │   ├── student-list
│   │   │   ├── student-list.component.css
│   │   │   └── student-list.component.html
│   │   ├── students.component.css
│   │   └── students.component.html
│   ├── +subjects
│   │   ├── subject
│   │   │   ├── subject.component.css
│   │   │   └── subject.component.html
│   │   ├── subject-list
│   │   │   ├── subject-list.component.css
│   │   │   └── subject-list.component.html
│   │   ├── subjects.component.css
│   │   └── subjects.component.html
│   ├── +teachers
│   │   ├── teacher
│   │   │   ├── teacher.component.css
│   │   │   └── teacher.component.html
│   │   ├── teacher-list
│   │   │   ├── teacher-list.component.css
│   │   │   └── teacher-list.component.html
│   │   ├── teachers.component.css
│   │   └── teachers.component.html
│   ├── +terms
│   │   ├── term
│   │   │   ├── term.component.css
│   │   │   └── term.component.html
│   │   ├── term-list
│   │   │   ├── term-list.component.css
│   │   │   └── term-list.component.html
│   │   ├── terms.component.css
│   │   └── terms.component.html
│   ├── +users
│   │   ├── users.component.css
│   │   └── users.component.html
│   └── +years
│       ├── year
│       │   ├── year.component.css
│       │   └── year.component.html
│       ├── year-list
│       │   ├── year-list.component.css
│       │   └── year-list.component.html
│       ├── years.component.css
│       └── years.component.html

Note the missing .js and .js.map files

4. The log given by the failure. Normally this include a stack trace and some
   more information.

There was not stacktrace the build completes successfully 

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Production builds bundle all js code into `main.js`, that behavior is intended.
