### ISSUE TITLE
ng g c component-name command not working

### ISSUE THREAD

**Issue by gchawla7** [angular/angular-cli#11650]
ng g c component-name command not working using the ngx-admin project
while the same command works if we have default Angular 2 application.

It is throwing the exception:

ng g c test-component
Error compiling schema, function code: var customRule0 = customRules[0];var customRule1 = customRules[1]; var validate = async function(data, dataPath, parentDa
.....
, message: 'should be object'  } ]);  }    if (errors === 0) return data;
     else throw new ValidationError(vErrors);  }; return validate;
Unexpected token function

Thanks in advance!

**Comment by sujith2014** [comment]
same issue solved by updating npm 

https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
