### ISSUE TITLE
[XI18N] Unknown option: '--progress'

### ISSUE THREAD

**Issue by hugodes** [angular/angular-cli#11667]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.1.0
Node: 8.11.3
OS: darwin x64
Angular: 6.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.0
@schematics/update                0.7.0
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.8.3

### Repro steps

ng xi18n --output-path src/locales/ --progress false

### The log given by the failure

Unknown option: '--progress'

### Desired functionality

The --progress option seemed to have been removed in 6.1, with no mention of it in the changelog or any migration examples.

### Mention any other details that might be useful

Worked fined in 6.0.9

**Comment by sinedied** [comment]
Same with the `e2e` option, `--progress` was there, and now it's not working anymore.

**Comment by sinedied** [comment]
@hansl does your commit also fix the `--progress` option for the e2e command? As this issue was referenced when closing this other one: https://github.com/angular/angular-cli/issues/12057
Thanks!
