### ISSUE TITLE
error when creating a new project by CLI command

### ISSUE THREAD

**Issue by phongtv89** [angular/angular-cli#11664]
I'ma newbie in angular. When I try run new project like tutorial, i always get a error as below:
** Angular Live Development Server is listening on localhost:8082, open your browser on http://localhost:8082/ **

Date: 2018-07-26T06:46:54.486Z
Hash: 4d3e973e83c839f26163
Time: 4843ms
chunk {main} main.js, main.js.map (main) 1.91 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 671 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in node_modules/@angular/platform-browser-dynamic/src/compiler_factory.d.ts(18,22): error TS2720: Class 'CompilerImpl' incorrectly implements class 'Compiler'. Did you mean to extend 'Compiler' and inherit its members as a subclass?
  Property 'getModuleId' is missing in type 'CompilerImpl'.
node_modules/@angular/platform-browser-dynamic/testing/src/compiler_factory.d.ts(12,22): error TS2720: Class 'TestingCompilerImpl' incorrectly implements class 'TestingCompiler'. Did you mean to extend 'TestingCompiler' and inherit its members as a subclass?
  Property 'getModuleId' is missing in type 'TestingCompilerImpl'.

i ｢wdm｣: Failed to compile.

**Comment by angelmartinez-wz** [comment]
What versions of NPM, Angular-CLI, and Node are you using?

**Comment by sclode** [comment]
I had the same problem and solved it by updating @angular/platform-browser and @angular/platform-browser-dynamic to "^6.1.0" in my package.json. Before the versions had been stuck at "6.0.9" which was different to the versions of angular (6.1.0) and angular-cli (6.1.1).

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by Diandres** [comment]
@sclode workarround Seems to have fixed my issue.
