### ISSUE TITLE
Warning message is displayed when using TypeScript 2.9.2

### ISSUE THREAD

**Issue by micksatana** [angular/angular-cli#11665]
Angular version 6.1.0 support typescript 2.9. But when I change typescript dependency in `package.json`. This warning is shown.
```
@angular/compiler-cli@6.1.0 requires typescript@'>=2.7.0 <2.8.0' but 2.9.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.7.0 <2.8.0'

To disable this warning run "ng config cli.warnings.typescriptMismatch false".
```

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
node --version
v8.9.4
```
```
npm --version
6.2.0
```
```
ng --version
Angular CLI: 6.1.0
Node: 8.9.4
OS: darwin x64
Angular: 6.1.0
... animations, bazel, cli, common, compiler, compiler-cli, core
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.0
@angular-devkit/build-angular     0.7.0
@angular-devkit/build-optimizer   0.7.0
@angular-devkit/build-webpack     0.7.0
@angular-devkit/core              0.7.0
@angular-devkit/schematics        0.7.0
@ngtools/webpack                  6.1.0
@schematics/angular               0.7.0
@schematics/update                0.7.0
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
```

### Repro steps

1. Create new angular project
`ng new testNg61`
2. Change typescript version in `package.json` to 2.9.2
3. Run `npm i`
4. Run `ng serve`

### The log given by the failure

```
@angular/compiler-cli@6.1.0 requires typescript@'>=2.7.0 <2.8.0' but 2.9.2 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

    npm install typescript@'>=2.7.0 <2.8.0'

To disable this warning run "ng config cli.warnings.typescriptMismatch false".
```

### Desired functionality

Serve correctly without showing the warning

### Mention any other details that might be useful

`versionCombos` variable in `node_modules/@angular/cli/upgrade/version.js` seem not being built correctly. The [codes](https://github.com/angular/angular-cli/blob/aeb4ff5b298a8959e478413851c6666859522d46/packages/angular/cli/upgrade/version.ts#L154-L155) in `upgrade/version.ts` file seem correct.

**Comment by sundarchi1** [comment]
Is the referenced fix complete? Creating a new project in the CLI, why is the default typescript version set to "~2.7.2" in package.json? Shouldn't it be set to 2.9 by default now or is 2.7 the default for some specific reason?

**Comment by sarunint** [comment]
@sundarchi1 Yes, it does fix the issue when you already upgraded to TypeScript 2.9. The issue you've just raised is a separated issue in which Angular CLI generates TypeScript 2.7 as default.

As for that issue, #11669 is pending.

**Comment by micksatana** [comment]
@sundarchi1 I tested on my local. the fix is complete. when change version to 2.9.2, no warning display.
