### ISSUE TITLE
ng add @angular/pwa fails with 'Invalid rule result: Function().'

### ISSUE THREAD

**Issue by mruknowme** [angular/angular-cli#11663]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```txt
node --version
v10.2.1
```

```txt
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.8
Node: 10.2.1
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/pwa                      0.7.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

```txt
npm --version
6.2.0
```

### Repro steps

```bash
ng new projectName --routing --prefix=prfx --style=scss && cd projectName && ng add @angular/pwa
```

### The log given by the failure

```txt
ng add @angular/pwa
Installing packages for tooling via npm.
+ @angular/pwa@0.7.0
updated 1 package and audited 26697 packages in 6.57s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
Invalid rule result: Function().
```

**Comment by bobweeman** [comment]
@mruknowme Do you have a solution yet. Am having the same issue.

**Comment by proeben** [comment]
Same problem here. 6.1.0 doesnt work either (different error). I tried to downgrade and got this.

**Comment by gsphamnguyen** [comment]
You should to use @angular/pwa@0.6.8. Goodluck!

**Comment by gkalpak** [comment]
Sounds similar to #11640 (although the error message is different).

**Comment by odineshrao** [comment]
Same problem, i thing there is bugs in pwa@0.7.1, you need to use lower version

**Comment by dgpuranik** [comment]
@hansl I am using @angular-devkit/schematics 0.7.1. I still get same error. @odineshrao I tried installing lower version pwa@0.7.0 but still get same error. Do you know which lower version work proper?

**Comment by dgpuranik** [comment]
@odineshrao 0.6.8 worked.

**Comment by gagle** [comment]
0.6.8 is failing with

Cannot read property 'options' of undefined (https://github.com/angular/angular-cli/issues/10469)

Event with "ng add @angular/pwa --project myprojectname" is failing.

**Comment by durdevic** [comment]
Hi guys, with 0.6.8 version I get ```newTree.optimize is not a function``` . I couldn't find a solution to this, does anybody have any idea?

**Comment by durdevic** [comment]
The solutions that worked for me in the end was from sksvenson https://stackoverflow.com/questions/51555017/path-ngsw-config-json-already-exists

> I had the same issue. I came from Angular 5 and updated to Angular 6.
> 
> I use these specific versions to get it work:
> ```
> npm install --save @angular/cli@6.0.8
> npm install --save @angular/pwa@0.6.8
> ```
> And I had also to remove this entry from angular.json:
> ```
> "ngswConfigPath": "src/ngsw-config.json"
> ```

**Comment by johnpaulmanoza** [comment]
The solution that worked for me is to downgrade to version 6.0.0.

**Comment by ohabash** [comment]
none of these solution works. how come when i do `ng g c cname` i get `Invalid rule result: Function().`
