### ISSUE TITLE
ng add  @angular/pwa fails

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#11662]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.1.0
Node: 10.7.0
OS: darwin x64
Angular: 6.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.0
@angular-devkit/build-angular      0.7.0
@angular-devkit/build-ng-packagr   0.7.0
@angular-devkit/build-optimizer    0.7.0
@angular-devkit/build-webpack      0.7.0
@angular-devkit/core               0.7.0
@angular-devkit/schematics         0.7.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.0
@schematics/angular                0.7.0
@schematics/update                 0.7.0
ng-packagr                         3.0.3
rxjs                               6.2.2
typescript                         2.7.2
webpack                            4.9.2

### Repro steps
```
ng new something
cd something
ng add @angular/pwa
```

### The log given by the failure
```
Installing packages for tooling via npm.
+ @angular/pwa@0.7.0
added 2 packages from 2 contributors and audited 29129 packages in 7.355s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
Path "/ngsw-config.json" already exist.
```

### Desired functionality
Service worker being added successfully to my project

**Comment by proeben** [comment]
Same problem here

**Comment by batbrain9392** [comment]
@proeben : The problem wasn't there with the previous cli version I had - 6.0.8

**Comment by gkalpak** [comment]
Duplicate of #11640.

**Comment by guysenpai** [comment]
I got the same error after updating after getting latest update

```
_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.1
Node: 9.11.2
OS: darwin x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.1
@angular-devkit/build-angular     0.7.1
@angular-devkit/build-optimizer   0.7.1
@angular-devkit/build-webpack     0.7.1
@angular-devkit/core              0.7.1
@angular-devkit/schematics        0.7.1
@angular/cli                      6.1.1
@angular/pwa                      0.7.1
@ngtools/webpack                  6.1.1
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```

**Comment by bernhard-pointner** [comment]
Same issue v6.1.1

**Comment by html5ravi** [comment]
Same issue here too CLI V6.1.1

**Comment by paulimfavarato** [comment]
yep, it doesn't work on v6.1.1 :(

**Comment by schankam** [comment]
I will wait the 6.2.0 to be release and PWA 0.8.0 to be release personally....  This issue has been around for 3 weeks, seriously that is ridiculous...
