### ISSUE TITLE
Where to place Router latest which are generated using Beta.5

### ISSUE THREAD

**Issue by a5hik** [angular/angular-cli#1167]
The latest docs of router says to keep router in a separate file. app.routes.ts

https://angular.io/docs/ts/latest/guide/router.html

and also mentions...

> We must register router providers in bootstrap. We cannot wait to do it in AppComponent.

I have  routers generated using beta.5, which are part of AppComponent, Do I need to refactor and place the routers in a separate file and Bootstrap.

PS: I have now upgraded the cli to beta.6, and I guess the route generation is disabled now.

**Comment by a5hik** [comment]
I had followed the guidance from here. and done myself manually all the steps. It works fine now.
The app is now in cli version beta6 and router version 3. It is created using beta.5

https://angular.io/docs/ts/latest/guide/router.html

1. Create new file app-routes.ts
2. Edit your main.ts to bootstrap routes.
3. Move your Routes path from components file to routes file.
4. remove slashes in the route paths.
5. add front slash in the routerLink of your html for all your routes.
6. repeat the steps for child routes.

Keeping it here as this might be useful for someone.
Also the steps can be validated.

**Comment by a5hik** [comment]
I'm still not sure why I need to add a front slash '/' in all the router Links. otherwise its not working.
Also need to know If there is an other way of doing it.

**Comment by filipesilva** [comment]
Heya, glad you got it working! Not too sure about the slash myself, but keep an eye on the Angular 2 release notes and the docs, as that might change.
