### ISSUE TITLE
@schematics/angular still depends on TS <2.8

### ISSUE THREAD

**Issue by josephliccini** [angular/angular-cli#11678]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI 6.1.1 
Windows 10
Node 8.11.1

### Repro steps

![image](https://user-images.githubusercontent.com/7726025/43282325-a6a506f4-90ca-11e8-8dfa-b686e66cfbda.png)

`yarn list typescript`
```
yarn list v0.27.5
├─ @schematics/angular@0.7.1
│  └─ typescript@2.7.2
└─ typescript@2.9.2
```
### The log given by the failure

I have 2 'TypeScript' versions in my `node_modules`.  I think this is giving me some issues during build (we are in an ejected configuration).

### Desired functionality

I think the dependency for this package should be upgraded to match those of the rest of Angular CLI (like `@angular-devkit/build-optimizer` depends on `~2.9.1`

**Comment by clydin** [comment]
Please see this pull request and comment for further details: https://github.com/angular/angular-cli/pull/11670#issuecomment-408074668

**Comment by hansl** [comment]
Closing this as this is a direct dependency and would not show warning/error to the user. We'll fix it so it can get deduped, but there's no issue with the current state.
