### ISSUE TITLE
ng build --configuration=production hash chunks are always the same

### ISSUE THREAD

**Issue by alexw10** [angular/angular-cli#11677]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

➜  ~/projects/Web.ClinicianSite node --version
v10.4.0
➜  ~/projects/Web.ClinicianSite npm --version
6.2.0
➜  ~/projects/Web.ClinicianSite ng --version
Angular CLI: 6.0.8
Node: 10.4.0
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

My angular.json contains this for the production configuration
`
"configurations": {
   "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            },
`

so outputHashing which I believe makes these unique and makes it so in production when new version is deployed it will get changed when refreshed is turned to "all"

Running `ng build --configuration=production`
The hashes for the chunks are always the same:
![image](https://user-images.githubusercontent.com/9453636/43281430-42ce1814-90d9-11e8-94f7-587b05c29fa6.png)

Everytime I run it, the hashes are the same, this is causing in production the application to be cached and we don't see the updates when we deploy a new version. Really need this fixed.

**Comment by alexw10** [comment]
Just to add to this you can also do a new application with the CLI:
`ng new my-test-app`

go into it and run this twice:
`ng build --configuration=production`

This produces the same bundles as well the production configuration being the same as mine above...
![image](https://user-images.githubusercontent.com/9453636/43283145-b11eca3a-90dd-11e8-93f5-cfb155df18dc.png)

**Comment by clydin** [comment]
The hashes only change if the code changes.  If you haven't changed any of the application code then this is working as intended.

**Comment by alexw10** [comment]
@clydin thanks seems like this is the case not sure why our build not updating prod properly then ill have to look deeper.

**Comment by chintan12** [comment]
ERROR in : Type AuthenticationsComponent in /var/www/html/hywyhaul/src/app/authentications/authentications.component.ts is part of the declarations of 2 modules: AppRoutingModule in /var/www/html/hywyhaul/src/app/app-routing.module.ts and AuthenticationsModule in /var/www/html/hywyhaul/src/app/authentications/authentications.module.ts! Please consider moving AuthenticationsComponent in /var/www/html/hywyhaul/src/app/authentications/authentications.component.ts to a higher module that imports AppRoutingModule in /var/www/html/hywyhaul/src/app/app-routing.module.ts and AuthenticationsModule in /var/www/html/hywyhaul/src/app/authentications/authentications.module.ts. You can also create a new NgModule that exports and includes AuthenticationsComponent in /var/www/html/hywyhaul/src/app/authentications/authentications.component.ts then import that NgModule in AppRoutingModule in /var/www/html/hywyhaul/src/app/app-routing.module.ts and AuthenticationsModule in /var/www/html/hywyhaul/src/app/authentications/authentications.module.ts.

**Comment by behrooz** [comment]
> 
> 
> The hashes only change if the code changes. If you haven't changed any of the application code then this is working as intended.

how to disable this option ? i want to create new hash every time that i run ng build --env=stage --prod  --build-optimizer  --aot

**Comment by jkon** [comment]
@behrooz did you figure out a way to do this? also want a way to have new filenames for each build. I have a qa and uat environment deployed that my qa testers browser's are caching. Even when there are large code changes, the filenames aren't changing. Does anyone know a good way to create random filenames, instead of hashes of the code?

**Comment by behrooz** [comment]
@jkon Actually i have this issue when i upload on amazon aws and could't find any solution instead i use cloudfront invalidation in aws console

**Comment by jkon** [comment]
@behrooz I have my app deployed as a lambda, so I'm not sure that I could do manual cloudfront invalidation. But, what I don't get is why the hash doesn't change. If I could just add to the hash by using a commit hash or build number or something, I could get the filenames to be different on every deployment and then I wouldn't have to worry about the user not getting the update
