### ISSUE TITLE
ng serve and ng build --watch don't actually build the project

### ISSUE THREAD

**Issue by vaindil** [angular/angular-cli#11671]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Windows 10
node: v10.6.0
npm: 6.2.0

```
Angular CLI: 6.0.8
Node: 10.6.0
OS: win32 x64
Angular: 6.0.9
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
Angular CLI: 6.0.8
Node: 10.6.0
OS: win32 x64
Angular: 6.0.9
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps
 - Build project with `ng build`
 - Make changes to files
 - Attempt to use `ng build --watch` or `ng serve`

### The log given by the failure
No log.

### Desired functionality
If I run `ng build` successfully, then I do something like delete a component and update the code accordingly, I cannot use `ng build --watch` or `ng serve` unless I run `ng build` on its own first. The CLI throws errors stating that the component couldn't be resolved and thus it couldn't build, but if I go to the lines in the error log (.ts files) there's no mention of the component. I did a find across my entire project and the component no longer exists anywhere except in the built .js files, yet the CLI somehow still thinks they're being referenced.

### Mention any other details that might be useful
N/A

**Comment by angelmartinez-wz** [comment]
If you run ng build without flags or with the flag `--output-path` the project is built?
Did you try with the `--verbose` flag to log the output of the build.

[Angular CLI Build Documentation](https://github.com/angular/angular-cli/wiki/build)

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by filipesilva** [comment]
Closing as inactive.
