### ISSUE TITLE
Sourcemaps are partially missing when building for prod

### ISSUE THREAD

**Issue by deli6z** [angular/angular-cli#11676]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node -v
v6.10.1
npm -v
5.0.3
Angular CLI: 1.7.4

### Repro steps

When I am building for prod I want to debug it sometimes but some files don't have sourcemaps for some reason. This is the command I am using:

`ng build --prod --deploy-url=/path/to/files/ --sourcemap
`

I noticed that the only sourcemaps are present is the files which are loaded for the lazy loaded modules.

Please help if anyone had similar issue.
Thanks.

**Comment by clydin** [comment]
Please try updating to version 6.1.  The version being used is outdated.  If the problem persists please open a new issue with the version details.
