### ISSUE TITLE
[question] error catch sourcempa needed

### ISSUE THREAD

**Issue by BennieMeng** [angular/angular-cli#11684]
our angular project is now catching error by sentry.
but when i had updated angularcli version to 6.0.0,  i can't actually find which row of code cause this error like below
![image](https://user-images.githubusercontent.com/37033797/43304773-eed029d0-91a7-11e8-8f88-123012635b25.png)

the begin build command is
 `node --max_old_space_size=2048 ./node_modules/@angular/cli/bin/ng build --aot --prod --build-optimizer --base-href \"/public/\""`,

and part of my config file angular.json is below
`"production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }`
 i need help how to open the mapsource , i can exactly find the reason . thank you~

**Comment by alan-agius4** [comment]
From your config it looks like `sourcemaps` are disabled for prod builds.

If you take a look at the `angular.json` , `sourceMap` is set to false, you probably want to change this to `true`

**Comment by BennieMeng** [comment]
@alan-agius4  sorry for my silly. i also have a question. when i change my code, brower will reload current page, this is not my expect. i what the brower updates where i changed without reloading page, because it takes a little long time. if can, thank you very much~

**Comment by BennieMeng** [comment]
my ng sever command is
`ng serve --host 0.0.0.0 --disable-host-check --proxy-config proxy.config.js`,
i also try --hmr , but not get the desired result

**Comment by alan-agius4** [comment]
Take a look here: https://github.com/angular/angular-cli/wiki/stories-configure-hmr

**Comment by BennieMeng** [comment]
@alan-agius4  thank you very much. i try to write a directive by myself ,below part of code,
`import {Directive, ElementRef} from '@angular/core';

@Directive({selector: '[light]'})

export class LightDirective{
  constructor(el: ElementRef) {
    el.nativeElement.style.backgroundColor = 'green';
  }
}`
alse had declarated on NgModule declarations.
and bind to one element, such as `<span *light>123</span>`
i can get information inside constructor , but the element display none , and only <-- --> left, 
what's wrong with my step, can you help me ?

**Comment by alan-agius4** [comment]
Hi @BennieMeng, After, reviewing this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`. More your request doesn't fall under to Angular CLI project.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation.](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem)

**Comment by BennieMeng** [comment]
@alan-agius4 , ok , thank you for your patient help~
