### ISSUE TITLE
the scss file not generate css file in dist folder, so no styles

### ISSUE THREAD

**Issue by welkang** [angular/angular-cli#1169]
- angular-cli: 1.0.0-beta.6
- node: 6.2.2
- os: win32 x64

**the scss file not generate css file in dist folder, so no styles....**

**Comment by a5hik** [comment]
Its working fine for me I run the beta.6 version.

**Comment by tyoungjr** [comment]
Had a fun afternoon with this exact same issue. It might be do to a node upgrade, but basically what I did was reinstall angular-cli re download my project and npm install. Voila.

**Comment by filipesilva** [comment]
@welkang are you still having this issue after following the suggestions in comments?

**Comment by filipesilva** [comment]
Closed as inactive.
