### ISSUE TITLE
CLI doesn't support LTS version of Node.js, 6.14.3

### ISSUE THREAD

**Issue by rudolfolah** [angular/angular-cli#11701]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
rudolfo:~/Code$ node --version
v6.14.3
rudolfo:~/Code$ npm --version
3.10.10
rudolfo:~/Code$ ng --version
You are running version v6.14.3 of Node.js, which is not supported by Angular CLI v6.
The official Node.js version that is supported is 8.9 and greater.

Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.
rudolfo:~/Code$ 
```

### Desired functionality
Should support LTS versions of Node.

**Comment by alan-agius4** [comment]
This is not a bug, Angular CLI 6+ only supports node versions 8.9+. This was one of the Breaking changes from the previous CLI version.

Relates to: https://github.com/angular/angular-cli/issues/10425

**Comment by hansl** [comment]
Please note that Node 6 is in maintenance LTS (see [here](https://github.com/nodejs/Release)), but many of our dependencies don't support Node 6 anymore and keeping Node at LTS would be a problem.

**Comment by rudolfolah** [comment]
okay thanks for the explanation!

**Comment by edthenet** [comment]
but how can i install a other version of node on my CentOS 6 server?
