### ISSUE TITLE
error  

### ISSUE THREAD

**Issue by vierita13** [angular/angular-cli#11702]
npm ERR! Unexpected end of JSON input while parsing near '...@types/mkdirp":"lates'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\FRANCO\AppData\Roaming\npm-cache\_logs\2018-07-29T14_51_04_875Z-debug.log

**Comment by alexeagle** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
