### ISSUE TITLE
Dynamic load styles for themes

### ISSUE THREAD

**Issue by YaroslavLyzlov** [angular/angular-cli#11706]
I want to use different color themes (by env variables), but since angular-cli use his loader
and this not working:

`styles: [require('./header.component.styl'),require('./header.component.${environment.theme}.styl')]
`

what are the solutions?

**Comment by hansl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
