### ISSUE TITLE
ng init creates app file prefix with 'app' everytime

### ISSUE THREAD

**Issue by a5hik** [angular/angular-cli#1170]
angular-cli: 1.0.0-beta.6
node: 6.2.1
os: darwin x64

Whenever you run 'ng init' the cli seems to create files prefix with name 'app' ., for example..

app.component.ts etc., But I had created this application using 'ng create' so it took my project name and created files with prefix of 'myapp-component.ts', 

So I expect these files should not created as new every time I upgrade cli.
In other words it should follow the same naming pattern to override.

**Comment by hansl** [comment]
Closing this as obsolete.
