### ISSUE TITLE
Stories in Wiki are out of sync with Stories in repo

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#11718]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

The stories in the Wiki for instance https://github.com/angular/angular-cli/wiki/build is not in sync with the story in the CLI repo https://github.com/angular/angular-cli/blob/master/docs/documentation/build.md

As one can see for instance there is no reference to `vendor-source-map` in the first. 

Apart from the build story there are also other stories such as `continuous-integration`

**Comment by hansl** [comment]
Will be fixed with the next release (tomorrow). Sorry about that.

**Comment by alan-agius4** [comment]
@hansl, this is still a problem.
