### ISSUE TITLE
cannot create a new project

### ISSUE THREAD

**Issue by yomi7117** [angular/angular-cli#11719]
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '...1.1","xxhashjs":"^0.2'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yomi\AppData\Roaming\npm-cache\_logs\2018-07-31T09_14_41_204Z-debug.log
Package install failed, see above.

**Comment by hansl** [comment]
Could you share your package.json?

**Comment by yomi7117** [comment]
i was able to resolve the issue by uninstalling the angular/cli and node as an adminstrator, i also deleted the npm and npm-cache folder in the%appdata% and reinstalled a new node.js
