### ISSUE TITLE
ng new angular-tour-of-heroes  shows found 13 vulnerabilities (9 low, 4 high)   run `npm audit fix` to fix them

### ISSUE THREAD

**Issue by thaniyarasu** [angular/angular-cli#11714]
user@ubuntu18.04:~/projects$ nodenv -v
nodenv 1.1.2-1-g18489d7
user@ubuntu18.04:~/projects$ nodenv versions
* 10.7.0 (set by /home/user/.node-version)
user@ubuntu18.04:~/projects$ node -v
v10.7.0
user@ubuntu18.04:~/projects$ ng -v
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.1.1
Node: 10.7.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.1
@angular-devkit/core         0.7.1
@angular-devkit/schematics   0.7.1
@schematics/angular          0.7.1
@schematics/update           0.7.1
rxjs                         6.2.2
typescript                   2.7.2
    
user@ubuntu18.04:~/projects$ 

user@ubuntu18.04:~/projects$ ng new angular-tour-of-heroes
CREATE angular-tour-of-heroes/README.md (1036 bytes)
CREATE angular-tour-of-heroes/angular.json (3692 bytes)
CREATE angular-tour-of-heroes/package.json (1327 bytes)
CREATE angular-tour-of-heroes/tsconfig.json (408 bytes)
CREATE angular-tour-of-heroes/tslint.json (2805 bytes)
CREATE angular-tour-of-heroes/.editorconfig (245 bytes)
CREATE angular-tour-of-heroes/.gitignore (503 bytes)
CREATE angular-tour-of-heroes/src/favicon.ico (5430 bytes)
CREATE angular-tour-of-heroes/src/index.html (306 bytes)
CREATE angular-tour-of-heroes/src/main.ts (370 bytes)
CREATE angular-tour-of-heroes/src/polyfills.ts (3194 bytes)
CREATE angular-tour-of-heroes/src/test.ts (642 bytes)
CREATE angular-tour-of-heroes/src/styles.css (80 bytes)
CREATE angular-tour-of-heroes/src/browserslist (375 bytes)
CREATE angular-tour-of-heroes/src/karma.conf.js (964 bytes)
CREATE angular-tour-of-heroes/src/tsconfig.app.json (170 bytes)
CREATE angular-tour-of-heroes/src/tsconfig.spec.json (256 bytes)
CREATE angular-tour-of-heroes/src/tslint.json (314 bytes)
CREATE angular-tour-of-heroes/src/assets/.gitkeep (0 bytes)
CREATE angular-tour-of-heroes/src/environments/environment.prod.ts (51 bytes)
CREATE angular-tour-of-heroes/src/environments/environment.ts (631 bytes)
CREATE angular-tour-of-heroes/src/app/app.module.ts (314 bytes)
CREATE angular-tour-of-heroes/src/app/app.component.css (0 bytes)
CREATE angular-tour-of-heroes/src/app/app.component.html (1141 bytes)
CREATE angular-tour-of-heroes/src/app/app.component.spec.ts (1043 bytes)
CREATE angular-tour-of-heroes/src/app/app.component.ts (226 bytes)
CREATE angular-tour-of-heroes/e2e/protractor.conf.js (752 bytes)
CREATE angular-tour-of-heroes/e2e/tsconfig.e2e.json (213 bytes)
CREATE angular-tour-of-heroes/e2e/src/app.e2e-spec.ts (318 bytes)
CREATE angular-tour-of-heroes/e2e/src/app.po.ts (208 bytes)
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump

> node-sass@4.9.2 install /home/user/projects/angular-tour-of-heroes/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/user/.npm/node-sass/4.9.2/linux-x64-64_binding.node

> node-sass@4.9.2 postinstall /home/user/projects/angular-tour-of-heroes/node_modules/node-sass
> node scripts/build.js

Binary found at /home/user/projects/angular-tour-of-heroes/node_modules/node-sass/vendor/linux-x64-64/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1103 packages from 1285 contributors and audited 24200 packages in 51.078s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
    Directory is already under version control. Skipping initialization of git.
user@ubuntu18.04:~/projects$

**Comment by hansl** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/10963
