### ISSUE TITLE
sourcemaps for libraries are not included

### ISSUE THREAD

**Issue by d-bechtel** [angular/angular-cli#11715]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps

ng new some-app-name
ng generate library some-lib-name
ng build some-lib-name
ng serve
open chrome, point to http://localhost:4200 and open developer tools. 

### Desired functionality

Developer tools should show the original source code (ts code) for the library

**Comment by alan-agius4** [comment]
Most likely you need to enable `vendorSourceMap` in `angular.json` or as a command argument `vendor-source-map`

**Comment by d-bechtel** [comment]
enabling vendorSourceMap doesn't change anything on this issue

**Comment by alan-agius4** [comment]
I have tried this out and adding `vendorSourceMap` did solve this issue;

![image](https://user-images.githubusercontent.com/17563226/43504921-67303db4-9565-11e8-8e28-4d42313c169f.png)

Here's an extract from my `angular.json`
```js
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
    "vendorSourceMap": true,
    "outputPath": "dist/some-app-name",
    "index": "src/index.html",
    "main": "src/main.ts",
    "polyfills": "src/polyfills.ts",
    "tsConfig": "src/tsconfig.app.json",
    "assets": [
      "src/favicon.ico",
      "src/assets"
    ],
    "styles": [
      "src/styles.css"
    ],
    "scripts": []
  },
```

**Comment by d-bechtel** [comment]
the property in angular.json works, but is not compatible with the schema.json
the cli argument: **ng serve --source-map --vendor-source-map** doesn't work

**Comment by imike57** [comment]
there is a solution for this ? 

I created a lib following this https://angular.io/guide/creating-libraries
Yet, any css related to the library provide a source map. All style are in a <style> tag. 

I try to add `"vendorSourceMap": true` in my angular.json, but not working and found nothing elsewhere... Someone know a solution ? 

Thank's

Mike
