### ISSUE TITLE
How to include custom file in -prod build?

### ISSUE THREAD

**Issue by rkralston** [angular/angular-cli#1172]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
os: win32 x64

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.6
node: 6.1.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
na

4. The log given by the failure. Normally this include a stack trace and some
   more information.
na

5. Mention any other details that might be useful.
Deploying an angular app to IIS requires the inclusion of a Web.config file that contains custom URL rewriting instructions.

How do I include that file in my prod build?

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by elvirdolic** [comment]
You can put it into the src folder then it will be copied. Nothing special. My web.config is in the src folder

**Comment by filipesilva** [comment]
@rkralston does @elvirdolic's solution not work for you?

**Comment by rkralston** [comment]
Yes, sorry. Perfect. Please close.

**Comment by sryeruva** [comment]
Hi ,

My Name is Sundara, I have added web.config under source folder. But it does not copy the file to dist folder. Any ideas.

**Comment by kimhyunj** [comment]
@sryeruva Hi, 

https://stackoverflow.com/questions/39538464/how-to-include-custom-files-with-angular-cli-build
This answer might help you with this issue.

**Comment by sryeruva** [comment]
Thanks you and appreciate your response. I figured it out.
