### ISSUE TITLE
"ng is not recognized as an internal or external command"

### ISSUE THREAD

**Issue by Nagavarmas** [angular/angular-cli#11722]
i am not able to use "ng" command in command prompt which shows "ng is not recognized as an internal or external command" but it can be opened using node.js command prompt . how to rectify the error in normal command prompt .

**Comment by hansl** [comment]
You need to setup your PATH environment variable to point to your node bin folder. You can find that folder by running `npm bin -g`. See this; https://stackoverflow.com/questions/33819757/global-npm-install-location-on-windows

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
