### ISSUE TITLE
Better, comprehensive initial angular.json

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#11724]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Command (mark with an `x`)
```
- [ x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
ps>node --version
v8.9.4
ps>npm --version
6.2.0
ps>ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.1
Node: 8.9.4
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.1
@angular-devkit/core         0.7.1
@angular-devkit/schematics   0.7.1
@schematics/angular          0.7.1
@schematics/update           0.7.1
rxjs                         6.2.2
typescript                   2.7.2
```
### Repro steps

```
ng new aaCLI
```

### The log given by the failure

Since this is a feature request, no log is included.

### Desired functionality

When the initial/default angular.json is created, it does not include a separate configuration called development.  Therefore, you cannot do either of the following "out-of-the-box":
```
ng build --configuration development
```
```
ng serve --open --configuration development
```
Suggested change: include by default, a separate configuration inside the initial/default angular.json that builds and  serves the application with the following settings, the key ones being aot / false, buildOptimizer / false and aot / false:
```
"development": {             
              "optimization": false,
              "outputHashing": "none",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": true,
              "aot": false,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": false
            }
```
There are two key benefits to this  enhancement:

1. There would be two separate examples of how to create configurations right from the start.
2. A clear separation of production from development
[angular.json.txt](https://github.com/angular/angular-cli/files/2245493/angular.json.txt)

**Comment by alan-agius4** [comment]
Following several changes in version 12, `development` and `production` configurations are creating for most build targets. Also, in version 12 we will default to `production` builds by default.

See https://github.com/angular/angular-cli/pull/20128 and https://github.com/angular/angular-cli/pull/20233 for more context about these changes.
