### ISSUE TITLE
docs: template section missing in angular_devkit/schematics/README.md

### ISSUE THREAD

**Issue by michaelmcandrew** [angular/angular-cli#11733]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Documentation issue / version independent.

### Repro steps

Have a look at https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/schematics/README.md.

It mentions the template section `(see the Template section)` a few times but this section doesn't seem to exist.

### The log given by the failure
NA

### Desired functionality

I'm currently trying (and failing) to get my head around how to generate files from templates by looking through code examples. A few sentences on how templates have been architected might help be get my head around them.

### Mention any other details that might be useful

Happy to share source files / explain more about my use case if appropriate.

**Comment by michaelmcandrew** [comment]
After a big more digging, I found that the comments in 

* [packages/schematics/schematics/schematic/files/src/my-full-schematic/index.ts]((https://github.com/angular/angular-cli/blob/84ec3022c2e568b5c9c83b6a624b2b4ef2963633/packages/schematics/schematics/schematic/files/src/my-full-schematic/index.ts)
* [packages/schematics/schematics/schematic/files/src/my-other-schematic/index.ts]((https://github.com/angular/angular-cli/blob/84ec3022c2e568b5c9c83b6a624b2b4ef2963633/packages/schematics/schematics/schematic/files/src/my-full-schematic/index.ts)
* [packages/schematics/schematics/schematic/files/src/my-schematic/index.ts]((https://github.com/angular/angular-cli/blob/84ec3022c2e568b5c9c83b6a624b2b4ef2963633/packages/schematics/schematics/schematic/files/src/my-full-schematic/index.ts)

were really helpful and aided my understanding of how it is supposed to work.

**Comment by hansl** [comment]
Yes, those comments are meant to be as close a documentation as we can for the time being. We should point to those though, so I'll leave this issue open.
