### ISSUE TITLE
`ng g --help` only prints schematics from default collection

### ISSUE THREAD

**Issue by emilio-martinez** [angular/angular-cli#11737]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
node --version
v8.9.4

npm --version 
6.2.0

ng --version
Angular CLI: 6.0.1
Node: 8.9.4
OS: darwin x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.1
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.1
@angular-devkit/schematics        0.6.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

1. Run `ng g --help`. Will print available options from default schematics collection.
2. Run `ng g --schematic @third-party/schematics --help`. Will still print available options from default schematics collection, not `@third-party/schematics`.
3. Set `cli.defaultCollection` on `angular.json` to another schematic, e.g., `@third-party/schematics`, and then run `ng g --help`. Will display options relevant to `@third-party/schematics`.

### The log given by the failure

As described above. No error or stack trace.

### Desired functionality

To see the requested schematics based on the `schematic` argument rather than always pulling from the default schematic.

**Comment by william-lohan** [comment]
Isn't it `ng g --collection @third-party/schematics --help`

**Comment by emilio-martinez** [comment]
🤷‍♂ This was a while ago and the CLI has changed quite a bit since then. I'll close for now and reopen if I face this again down the line.
