### ISSUE TITLE
Warning on autoPrefixer on IE support

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#11731]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] unexpected finding
```

### The log given by the failure

![image](https://user-images.githubusercontent.com/1249083/43501585-810954e6-9556-11e8-98ef-0d9b59089165.png)

### Mention any other details that might be useful
I got the above waring in one of my projects. As I'm not supprting IE, I wanted to know how to get rid of this waring. As the warning is thrown by the CLI that was the first place I looked. 
Turns out AutoPrefixer is responsible for this warning (and it is right, my app will not work in IE!)
adding the following to your `package.json` will fix it.

```
    "browserslist": [
        "last 2 version",
        "> 5%",
        "not IE > 0",
        "not ie_mob > 0" 
    ]
```

Notice the last  line `not ie_mob >0`. I did not expect I would need that, as I had the >5% rule.

**Comment by alan-agius4** [comment]
Addresses as we have updated to `Autoprefixer 9.2`  see https://github.com/postcss/autoprefixer/issues/1137
