### ISSUE TITLE
servePath does not render correct paths for JS files when using `ng serve`

### ISSUE THREAD

**Issue by paullessing** [angular/angular-cli#11755]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
$ node --version
v8.11.3
$ npm --version
5.6.0
$ yarn --version
1.6.0
$ ng --version

Angular CLI: 6.1.2
Node: 8.11.3
OS: linux x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cli                      6.1.2
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
```

### Repro steps
```
ng new <project-name>
```
Update `angular.json`: Set `serve -> options -> servePath` to a URL such as `/foobar`
```
ng serve
```
Go to http://localhost:4200/foobar

See that the index file loads, but all the other files don't resolve.

### The log given by the failure
404 for all the assets including all JS files

### Desired functionality
Asset paths should be based on the `servePath` property, e.g. `<script type="text/javascript" src="foobar/main.js"></script>` instead of `<script type="text/javascript" src="main.js"></script>`

### Mention any other details that might be useful
This used to work in <= 1.6, seems to have been broken in v6.x

**Comment by clydin** [comment]
This is working as intended.  `servePath` only affects the underlying development web server.  It has no effect on the actual application.

**Comment by paullessing** [comment]
@clydin I'm sure this used to behave differently. It doesn't make sense to me for `servePath` to serve but not update child files - if you check out [the minimal repro](https://github.com/paullessing/angular-cli-serve-path-bug) you can see a project that does not work at all using `serve`

**Comment by clydin** [comment]
Its only purpose to modify the base path of the web server.  It has no knowledge of the application or that there even is an application.  It really is meant only for more exotic development setups such as when using proxies.  The `baseHref` option is the option intended to modify the behavior of the application.  As a convenience, the `servePath` option will default to the value of the `baseHref` option if provided.

**Comment by paullessing** [comment]
@clydin The "more exotic setup" is exactly what we're attempting to do. This worked for previous setups - everythign we had was under /subfolder so that the reverse proxy could map paths starting with `/subfolder` to the `ng serve` application; `baseHref` is not an option for us because it not the entire application sits under that subdirectory, just its files are mapped there.

Previously, under cli@1.7.4 with angular@5.1.3, setting `--servePath=/subfolder/` in `ng serve` would produce output where the bundled `js` files are mapped as `/subfolder/file.js`.
This is no longer the case, and it seems like a regression to me.

**Comment by clydin** [comment]
By more exotic, I mean situations where the base href needs to be set but the serve path should still be root (`/`) or when the base href is set to an absolute URL (`http://cdn.xyz/`) and the serve path should be something other than root.

Please note that `servePath` is a dev server setting and not a build setting.  It will in no way affect the built application.

Base href sounds like exactly what you want (most likely combined with  the `APP_BASE_HREF` provider token ([documentation](https://angular.io/api/common/APP_BASE_HREF))

**Comment by paullessing** [comment]
Our setup is this:
1. Dev server at `localhost:4200/angular`
2. Traefik load balancer maps `www.local.dev` to `localhost:4200/angular/index.html` and `www.local.dev/angular/*` to `localhost:4200/angular/*
Another application is also at `www.local.dev`, and the load balancer distinguishes between them by looking at the `/angular` prefix.

Previously, using both `servePath` and `deployUrl` set to `/angular/`, we got the result that on `www.local.dev`, everything looked like it was running at the root directory (which is why we can't use `baseHref` - setting that to `/angular` would make all paths start with `/angular`, which we don't want). 
Angular's router mapped everything correctly (once the user has entered the application at `/`, all relative routes work correctly), and all assets including JS files are correctly mapped because webpack prefixes their paths with `/angular/`.

This prefixing is no longer happening, and I can't work out if it's an intended behaviour (seems unlikely), or a bug with either `servePath` or `deployUrl`. Is it possible it's a problem with `deployUrl` not working in `ng serve`?

**Comment by jak** [comment]
@clydin You wrote "Its only purpose is to modify the base path of the web server."

Just to clarify, using `ng serve --serve-path /assets/` (or equivalent) means that the HTML served should contain script tags with `<script type="text/javascript" src="/assets/main.js"></script>`?
