### ISSUE TITLE
Change the cache dir of build-optimizer and uglifyjs-webpack-plugin

### ISSUE THREAD

**Issue by williangd** [angular/angular-cli#11752]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality

I need to change the 'build-optimizer' and 'uglifyjs-webpack-plugin' cache directory to another location, outside the 'node_modules'. I will store the cache for the other builds, done in the CI.

Is this possible?

**Comment by filipesilva** [comment]
This isn't a setting we expose currently, no.

**Comment by clydin** [comment]
This is not something we are considering at this time.  Each new option increases the overall sustainment cost of the CLI and this appears to be an option that will be used infrequently.
However, modification of the Webpack configuration can now be achieved through the use of custom builders such as https://github.com/manfredsteyer/ngx-build-plus
