### ISSUE TITLE
bug: `ng g c SomeComponent` fails with "Invalid rule result: Function()."

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#11754]
### Bug Report 
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: 10.8.0
npm: 6.2.0 or 6.3.0
ng: 6.0.4
ng CLI: 6.0.8 or 6.1.2
OS: linux x64_86 (Linux Mint 19 or 18)

Due to a hard limitation, I cannot upgrade from Angular 6.0.4 for the time being.

### Repro steps

`ng g c SomeComponent`

### The log given by the failure
The CLI tool returns unsuccessfully with:
```log
Invalid rule result: Function().
```

### Desired functionality
Would like to generate a new component with the CLI tool, not manually.

Was able to create a new component with NG CLI 6.0.4.

### Mention any other details that might be useful
n/a

**Comment by catull** [comment]
I also get this behaviour with node versions 10.6.0 and 10.7.0.

**Comment by catull** [comment]
Found a "dirty" work-around.

`ng update @angular/cli`   # to 6.1.2
`ng update @angular/core`  # to 6.1.0

Then

`ng generate component PublicationSearch`

It produced the component files, then I flashed back the change in package.json.
Job done.

**Comment by filipesilva** [comment]
I think this is related, but not quite a duplicate of https://github.com/angular/angular-cli/issues/11663.

**Comment by nitinprajapati1404** [comment]
this error comes because of the version mismatch of your project and your system so use following command to execute

`ng g c patients/all-patients/patients-collection --version=6.0.8`

where 6.0.8 is the version of angular of my project

**Comment by catull** [comment]
@nitinprajapati1404 Perhaps that is also the case.

However, in case I was unclear, it was not the case for me.
I had the exact same version in /usr/local and in my project's workspace, when I looked into the bug in August 2018.

I switched to and from the versions, kept them at the same version meticulously.

The problem has not manifested for a long while now.

Thus I close it now.
