### ISSUE TITLE
ng new project creation failed

### ISSUE THREAD

**Issue by pankajnarwal11** [angular/angular-cli#11762]
2168 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...oader":"~0.8.0","scri'
2168 verbose stack     at JSON.parse (<anonymous>)
2168 verbose stack     at parseJson (/usr/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
2168 verbose stack     at consumeBody.call.then.buffer (/usr/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)
2168 verbose stack     at <anonymous>
2168 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
2169 verbose cwd /home/pankaj/work/angular-test-projects/section2exercise/basic-assignment3
2170 verbose Linux 3.13.0-32-generic
2171 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--quiet"
2172 verbose node v8.11.3
2173 verbose npm  v6.2.0
2174 error Unexpected end of JSON input while parsing near '...oader":"~0.8.0","scri'
2175 verbose exit [ 1, true ]

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by pankajnarwal11** [comment]
i have updated node js. please check my node js version
pankaj@ubuntu:~/work/angular-test-projects$ node --version
v10.8.0
pankaj@ubuntu:~/work/angular-test-projects$ npm -v
6.2.0



When i'm create new project using cmd : ng new basics-assignment3

It's generating 

npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '...oader":"~0.8.0","scri'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pankaj/.npm/_logs/2018-08-05T16_51_56_882Z-debug.log
Package install failed, see above.


I'm attaching log file in attchment. please provide me solution
[2018-08-05T16_51_56_882Z-debug.log](https://github.com/angular/angular-cli/files/2260507/2018-08-05T16_51_56_882Z-debug.log)
