### ISSUE TITLE
Extension for @angular/pwa package

### ISSUE THREAD

**Issue by sanfelici** [angular/angular-cli#11771]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Mention any other details that might be useful

dopo
ng add @angular/pwa
mi risponde
+ @angular/pwa@0.7.2
added 5 packages from 2 contributors and audited 55747 packages in 30.834s
found 14 vulnerabilities (9 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
Invalid rule result: Function().

**Comment by filipesilva** [comment]
Thanks for reporting this issue. However, this issue is a duplicate of an existing issue https://github.com/angular/angular-cli/issues/11663. Please subscribe to that issue for future updates.
