### ISSUE TITLE
Angular6 ERROR in No NgModule metadata found for 'AppModule'. after installing angularfire2

### ISSUE THREAD

**Issue by CarlitoMurta** [angular/angular-cli#11779]
### Bug Report or Feature Request
```
- [x ] bug report 

### Command
```
- [ x ] ng serve

### Versions

Angular: 6.1.2
Node: 10.6.0
OS: win32 x64
NPM: 6.1.0
Package Version
------------------------------------------------------
@angular-devkit/architect    0.7.2
@angular-devkit/core         0.7.2
@angular-devkit/schematics   0.7.2
@schematics/angular          0.7.2
@schematics/update           0.7.2
rxjs                         6.2.2
typescript                   2.7.2

### Repro steps
I just run ng serve command and the error break the command

### The log given by the failure

ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-08-05T06:49:34.367Z
Hash: 6013366703b13f99e9c0
Time: 2841ms
chunk {main} main.js, main.js.map (main) 1.93 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 682 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 74.7 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]

ERROR in No NgModule metadata found for 'AppModule'.
i ｢wdm｣: Failed to compile.

### Mention any other details that might be useful

Soon after installing angularfire2 to do a user authentication for my application and the error appeared

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
