### ISSUE TITLE
Regression: ng update ignores strict-ssl configuration

### ISSUE THREAD

**Issue by CSchulz** [angular/angular-cli#11785]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.1.1

### Repro steps

- Custom .npmrc:
  ```
  registry=myCustomRegistry
  strict-ssl=false
  ```
- Run `ng update @angular/cli`
- It fails with `unable to verify the first certificate`

### Mention any other details that might be useful
Old issue #10596 

it was working with Angular CLI 6.0.8.

**Comment by clydin** [comment]
This should be corrected in 6.1.2 (latest).  If this does not solve the issue, please re-open the issue.
