### ISSUE TITLE
after upgrading to angular 6 ng serve throw error:  No module factory available for dependency type: ContextElementDependency

### ISSUE THREAD

**Issue by zymr-keshav** [angular/angular-cli#11788]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
```

### Command (mark with an `x`)
```
- [x] serve

```

### Versions
 

- node -v 8.9.2
-  npm -v 6.1.0
- ng -v

```
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cli                      6.1.2
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.5
```
  
- mac os x High Sierra 10.13.3

### Repro steps

earlier I have one project based on angular 4 and now upgrade it using

ng update 

ng update @/angular.cli

remove node_modules 

-clear npm cache 

- remove package-lock.json

run `npm install`

and now when run 

`ng serve`

it throw this error in terminal

```

** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **
 10% building modules 3/3 modules 0 active(node:68496) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
 13% building modules 32/32 modules 0 activeError: No module factory available for dependency type: ContextElementDependency
    at addDependency (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:669:12)
    at iterationOfArrayCallback (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:186:3)
    at addDependenciesBlock (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:687:5)
    at iterationOfArrayCallback (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:186:3)
    at addDependenciesBlock (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:690:5)
    at Compilation.processModuleDependencies (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:698:4)
    at afterBuild (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:830:15)
    at buildModule.err (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:874:11)
    at callback (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:611:5)
    at module.build.error (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:651:12)
    at resolveDependencies (/opt/step-wizard/node_modules/webpack/lib/ContextModule.js:282:4)
    at ContextModule.result.resolveDependencies (/opt/step-wizard/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:500:25)
    at ContextModule.build (/opt/step-wizard/node_modules/webpack/lib/ContextModule.js:203:8)
    at Compilation.buildModule (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:616:10)
    at factory.create (/opt/step-wizard/node_modules/webpack/lib/Compilation.js:857:14)
    at hooks.afterResolve.callAsync (/opt/step-wizard/node_modules/webpack/lib/ContextModuleFactory.js:163:16)
/opt/step-wizard/node_modules/neo-async/async.js:14
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/opt/step-wizard/node_modules/neo-async/async.js:14:11)
    at /opt/step-wizard/node_modules/neo-async/async.js:2805:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### The log given by the failure

I searched many answers but none of them are working. some saying to update webpack while others are sying to remove webpack deom dev depenedenices.. I have tries all way but still give this error.

what coule be possible issue and how to fix it?

here is my package.json

```
"dependencies": {
    "@angular-devkit/build-angular": "^0.7.2",
    "@angular/animations": "6.1.1",
    "@angular/common": "6.1.1",
    "@angular/compiler": "6.1.1",
    "@angular/core": "6.1.1",
    "@angular/forms": "6.1.1",
    "@angular/http": "6.1.1",
    "@angular/platform-browser": "6.1.1",
    "@angular/platform-browser-dynamic": "6.1.1",
    "@angular/router": "6.1.1",
    "core-js": "^2.4.1",
    "rxjs": "^6.2.2",
    "rxjs-compat": "^6.2.2",
    "webpack": "^4.16.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/core": "0.7.2",
    "@angular/cli": "6.1.2",
    "@angular/compiler-cli": "6.1.1",
    "@angular/language-service": "6.1.1",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "autoprefixer": "^7.2.3",
    "circular-dependency-plugin": "^4.2.1",
    "codelyzer": "^4.0.1",
    "copy-webpack-plugin": "~4.4.1",
    "file-loader": "^1.1.5",
    "html-webpack-plugin": "^2.29.0",
    "istanbul-instrumenter-loader": "^3.0.0",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "less-loader": "^4.0.5",
    "ngx-toastr": "^8.10.0",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.10",
    "postcss-url": "^7.1.2",
    "protractor": "^5.4.0",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.1",
    "stylus-loader": "^3.0.1",
    "tailwindcss": "^0.6.4",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "2.9.2",
    "uglifyjs-webpack-plugin": "^1.1.8",
    "url-loader": "^0.6.2",
    "webpack-dev-server": "~2.11.0"
  }
```

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by mderazon** [comment]
It is reproducing for me here:
https://github.com/mderazon/repro-app

```
$ ng test
 10% building modules 1/1 modules 0 active(node:22840) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
$ node -v
v8.11.4
$ npm -v
6.4.1
$ ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.2.4
Node: 8.11.4
OS: linux x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.8.4
@angular/cdk                       6.4.7
@angular/cli                       6.2.4
@angular/material                  6.4.7
@angular/material-moment-adapter   6.4.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.8.4
@schematics/update                 0.8.4
ng-packagr                         3.0.6
rxjs                               6.3.3
typescript                         2.7.2
webpack                            4.8.3
