### ISSUE TITLE
Unable to install angular cli 6.1.2 (current installed version 6.1.1)

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#11780]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node -v
v8.11.2

npm -v
6.3.0

ng -v
Angular CLI: 6.1.1
Node: 8.11.2
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.1
@angular-devkit/core         0.7.1
@angular-devkit/schematics   0.7.1
@schematics/angular          0.7.1
@schematics/update           0.7.1
rxjs                         6.2.2
typescript                   2.7.2

### Repro steps

<img width="655" alt="screen shot 2018-08-05 at 11 34 14" src="https://user-images.githubusercontent.com/598463/43684628-e74dd7fe-98a3-11e8-8544-b81ff67d8d21.png">

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

Best I can say is that I can definitely see and install the latest version on my machine:
```
kamik@RED-X1C6 MINGW64 ~
$ npm i -g @angular/cli@latest
C:\Program Files\nodejs\ng -> C:\Program Files\nodejs\node_modules\@angular\cli\bin\ng
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@6.1.2
added 1 package from 3 contributors, removed 2 packages and updated 25 packages in 19.844s

kamik@RED-X1C6 MINGW64 ~
$ npm show @angular/cli version
6.1.2
```

Perhaps you are running into some problem with the propagation of packages in `npm`, or a proxy issue, but either way that's up to the result of running `npm` and there isn't anything we can do there.

**Comment by mackelito** [comment]
setting it to latest in package.json manually and reinstalling worked.. so all good..

**Comment by renasance** [comment]
So having this WARN is not a problem? 
![image](https://user-images.githubusercontent.com/17243418/52266852-6e985b80-2972-11e9-8ca3-89b42da68ece.png)
