### ISSUE TITLE
Angular.json won't import/load CSS files

### ISSUE THREAD

**Issue by AmitBarlev** [angular/angular-cli#11782]
Hey guys,
So recently I've started working with Angular cli and opened a project.
Downloaded bootstrap and every once in a while the project "decides" not to include bootstrap.css file no matter what I do (unless I import it explicitly with @import '~bootstrap/dist/css/bootstrap.min.css'; in styles), although it's a solution,
I wonder why my Angular.Json wont load it.
here's how my Angular.Json looks:
https://stackblitz.com/edit/angular-eydeoz?file=angular.json
Sorry I can't share anymore than that.

Angular-cli version:
Angular CLI: 6.1.2
Node: 10.8.0
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cli                      6.1.2
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

Thank you.

**Comment by alan-agius4** [comment]
Hi, from your reproduction, it looks like the `npm package` of `bootstrap` is missing.

Installing `bootstrap` solved the problem

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by AmitBarlev** [comment]
Well, I have no idea what I did but somehow it works (for now).
Thanks and sorry for the mess ;]
