### ISSUE TITLE
[build-optimizer] Ivy code is not full tree shaken / marked @PURE

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#11796]
Building an app with Ivy and optimizations on, I see the following code still there:

Before Uglify:
```javascript
var NgModuleFactory$1 = /** @class */ (function (_super) {
    __extends(NgModuleFactory$$1, _super);
    function NgModuleFactory$$1(moduleType) {
        var _this = _super.call(this) || this;
        _this.moduleType = moduleType;
        return _this;
    }
    NgModuleFactory$$1.prototype.create = function (parentInjector) {
        return new NgModuleRef$1(this.moduleType, parentInjector);
    };
    return NgModuleFactory$$1;
}(NgModuleFactory));
```

After Uglify (with mangle off):
```javascript
        !function(_super) {
            function NgModuleFactory$$1(moduleType) {
                var _this = _super.call(this) || this;
                return _this.moduleType = moduleType,
                _this
            }
            __extends(NgModuleFactory$$1, _super),
            NgModuleFactory$$1.prototype.create = function(parentInjector) {
                return new NgModuleRef$1(this.moduleType,parentInjector)
            }
        }(function() {}),
```

We would expect the first snippet to have a `@PURE` annotation on it following the `@class`, and the function not to be there at all after uglify.

**Comment by hansl** [comment]
Seems like we don't use the `@class` annotation as hint to add `@PURE`, which we should.

**Comment by kzc** [comment]
On a hunch I searched for `__extends` in the repo. It may be due to the `\w+` in this regex:

https://github.com/angular/angular-cli/blob/44086c60ff1d6c26d30850bef125120f6c498ac1/packages/angular_devkit/build_optimizer/src/transforms/prefix-classes.ts#L30

`\w+` doesn't match the `$` character in the bundler renamed `NgModuleFactory$$1`.

```
$ node -p '/\w*\.?__extends\(\w+, _super\);/.test("__extends(NgModuleFactory$$1, _super);")'
false
```

Possible alternatives: `\S+` or `[A-Za-z_$][A-Za-z0-9_$]*`.
```
$ node -p '/\w*\.?__extends\(\S+, _super\);/.test("__extends(NgModuleFactory$$1, _super);")'
true

$ node -p '/\w*\.?__extends\([A-Za-z_$][A-Za-z0-9_$]*, _super\);/.test("__extends(NgModuleFactory$$1, _super);")'
true
```

**Comment by filipesilva** [comment]
Yeah I think this was the renamed class. https://github.com/angular/angular-cli/commit/07ceb05985043f85142ac4462e5a1279c9bb5a3b fixed a similar thing.

The "gatekeeper" regex didn't correctly identify it though, for the reasons highlighted by @kzc. #13613 should fix it.

**Comment by filipesilva** [comment]
@kzc heya could you drop me a line on https://twitter.com/filipematossilv please? If you prefer some other venue let me know (e.g. https://gitter.im/angular/angular-cli).
