### ISSUE TITLE
Angular 5.2.10 with Agular-CLI not working with IE11

### ISSUE THREAD

**Issue by 51103220** [angular/angular-cli#11790]
I have a project with angular 5.2.10 and angular-cli 1.7.3 and I run into a same problem as  [<a href="https://github.com/angular/angular-cli/issues/9578">#9578</a>]. Even though i tried to uncomment all metioned lines in polyfill.ts i still had these lines:

![image](https://user-images.githubusercontent.com/8266389/43728448-522c0f6a-99cf-11e8-95e5-06033db25d4f.png)

- the 1st line indicates the bug of "Fetch" (the hot-reload)

![image](https://user-images.githubusercontent.com/8266389/43728491-7d456fd4-99cf-11e8-94be-4a5162b8b9cd.png)

- the second:
![image](https://user-images.githubusercontent.com/8266389/43728529-9e1f718c-99cf-11e8-840c-306b2fe2f413.png)

- the last:
![image](https://user-images.githubusercontent.com/8266389/43728546-a95f774a-99cf-11e8-8a1f-d18bc759161a.png)
-------------------------------------------------------------------------------------------------------
This is my polyfill.ts:

![image](https://user-images.githubusercontent.com/8266389/43728580-bcee7ef0-99cf-11e8-8490-e26db69567e8.png)
--------------------------------------------------------------------------------------------------------
And my package.json:
![image](https://user-images.githubusercontent.com/8266389/43728633-df69320e-99cf-11e8-9d35-42cc2b313b24.png)

Everything works fine on Chrome, Fifrefox, Opera, Edge,... but IE11. I researched and followed other similar threads but nothing helps. 
I would appreciate it if someone helps me find out what is wrong with my project configuration. I will provide more details if needed. 

Thank you.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by 51103220** [comment]
Dear @filipesilva,

Thank you so much. I found out what caused the bugs. It's the library [node-Jose](https://github.com/cisco/node-jose) 1.0.0. 

I downgraded to the version 0.9.4 and everything works as expected. Anyway, i still dont know why the latest version causes the bugs. 

This issue should be resolved.
Thank you

**Comment by Acelero** [comment]
Tried the fix but we are still getting errors. IE issue in scipt bundle.js, main bundle.js 

"dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@nicky-lenaers/ngx-scroll-to": "^1.0.0",
    "@types/c3": "^0.6.0",
    "angular-user-idle": "^2.0.0",
    "c3": "^0.4.23",
    "chart.js": "^2.7.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "d3": "^5.5.0",
    "jquery": "^3.3.1",
    "mydatepicker": "^2.6.4",
    "ng2-currency-mask": "^5.3.1",
    "ng2-scroll-to-el": "^1.2.1",
    "ng2-tooltip-directive": "^2.1.5",
    "ngx-bootstrap": "^3.0.0",
    "ngx-device-detector": "^1.3.0",
    "ngx-fullpage": "^4.0.6",
    "ngx-loading": "^1.0.14",
    "ngx-swiper-wrapper": "^6.0.0",
    "ngx-ui-switch": "^2.1.0",
    "rxjs": "^5.5.11",
    "source-map-support": "^0.5.6",
    "swiper": "^4.3.5",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "~1.7.3",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/chartjs": "0.0.31",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.3.4",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "husky": "^0.14.3",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "npm-run-all": "^4.1.3",
    "prettier": "^1.13.7",
    "pretty-quick": "^1.6.0",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
ERRORS---
SCRIPT5009: 'require' is undefined
SCRIPT1002: Syntax error

**Comment by zhangjinsong** [comment]
I want to know if this problem has been solved, how to solve it, because I have the same problem, but I have encountered it in ik-cli6.1.3
