### ISSUE TITLE
Cannot debug unit test with karma in CLI version 6.1.2

### ISSUE THREAD

**Issue by sawyerbutton** [angular/angular-cli#11799]
### Versions

- angular CLI: 6.1.2
- angular-devkit/build-angular: ~0.7.2
- ide: Webstorm 2018.2
### The log given by the failure

- Before angular-devkit/build-angular: 0.7.2(like 0.6.8), there is a problem with 'importing node_modules using Less'.
- In angular-devkit/build-angular:0.7.2, unit test with karma can not debug(breakpoints cannot get into debug dialog) in Webstorm 2018.2, but the bug with importing node_modules fixed. 

### Desired functionality

- Unit-test can run properly. 

### Mini repo for issue
-  angular-devkit/build-angular: 0.6.8 version with module import problem the [link](https://github.com/sawyerbutton/mini-repo-oldkit/tree/master/Github/mini-repo-oldkit)
- angular-devkit/build-angular: 0.7.2 version with debug problem [link](https://github.com/sawyerbutton/mini-repo-newkit)

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by sawyerbutton** [comment]
Sorry for forgetting to follow the issue rules.
I set up two mini repo for these two problems. 
For the first one(Before angular-devkit/build-angular: 0.7.2(like 0.6.8)), the repo [link](https://github.com/sawyerbutton/mini-repo-oldkit/tree/master/Github/mini-repo-oldkit),
For the second one(In angular-devkit/build-angular:0.7.2), the repo [link](https://github.com/sawyerbutton/mini-repo-newkit)
After consideration, I think the debug problem may caused by Webstorm adpting new devkit.
Thanks for helping.

**Comment by alan-agius4** [comment]
@sawyerbutton are you still experiencing the issue?

**Comment by hansl** [comment]
I'm going to close this as fixed in the latest version. If you still experience this issue please create a new issue and follow the template.
