### ISSUE TITLE
Wiki -> Stories -> Autocompletion no longer links to an existing page

### ISSUE THREAD

**Issue by seangwright** [angular/angular-cli#11792]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
None

### Versions
Current

### Repro steps
Go to Wiki in the github repo. Click "Stories" in right side menu. Click "Autocompletion" in left side list.

### The log given by the failure
"Could not find version "autocompletion" " is displayed in a blue bar at the top of the page.

### Desired functionality
"Autocompletion" links to wiki page about autocompletion

**Comment by kartik-budhiraja** [comment]
@filipesilva I would like to work on this issue.

**Comment by mgechev** [comment]
@kartik-budhiraja go ahead!

**Comment by bartduisters** [comment]
Still the case.

**Comment by alan-agius4** [comment]
`ng complete` no longer exists see https://github.com/angular/angular-cli/issues/11043
