### ISSUE TITLE
Global option --no-warnings to disable all warnings

### ISSUE THREAD

**Issue by rendmath** [angular/angular-cli#11802]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command
```
All
```

### Versions
node --version: v9.2.0
npm --version: 5.8.0
ng --version: 6.0.8
OS: Windows 10 x64

### Repro steps
PowerShell
```
$defaultProject = ng config defaultProject
$defaultProject
```
Bash
```
OUTPUT="$(ng config defaultProject)"
echo "${OUTPUT}"
```

Both variables now contains the value :
```
Your global Angular CLI version (6.1.1) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
name-of-the-default-project
```

### Desired functionality
A global option in all Angular CLI commands to disable warnings altogether, in order to make it easier to retrieve the output generated by the command inside a script, without any pollution from warnings.

**Comment by hansl** [comment]
We should output warnings to the STDERR.
