### ISSUE TITLE
Why angular cli ng build --watch command don't work like webpack with hot module replacement

### ISSUE THREAD

**Issue by alex2sorin** [angular/angular-cli#11817]
If I run ng build --watch, angular cli updates my code but I need to refresh page every time to see the new changes, With webpack and hmr page is updated without refreshing and without to do something.

**Comment by fchiumeo** [comment]
[Configure Hot Module Replacement](https://github.com/angular/angular-cli/wiki/stories-configure-hmr)

**Comment by alex2sorin** [comment]
I don't use ng serve, only ng build because I use static files from dist folder.

**Comment by clydin** [comment]
`ng build` solely builds files and places them in the output folder.  It does not serve them or communicate with a web browser in any way.  This is the function of `ng serve` which is designed specifically to provide the functionality requested.
