### ISSUE TITLE
Package Install Failed

### ISSUE THREAD

**Issue by Arulkp** [angular/angular-cli#11812]
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '...pqBR7JtUowW24PWgICTsl'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ARULKUMAR\AppData\Roaming\npm-cache\_logs\2018-08-08T20_07_43_328Z-debug.log
Package install failed, see above.

**Comment by filipesilva** [comment]
This seems like a problem with your node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
