### ISSUE TITLE
I can't create a new project after I installed the latest angular-cli (version 6.1.2) and latest nodejs (version 8.11.3)

### ISSUE THREAD

**Issue by emmonmoses** [angular/angular-cli#11827]
C:\Users\AAAIT\Desktop>ng new project
CREATE project/angular.json (3557 bytes)
CREATE project/package.json (1312 bytes)
CREATE project/README.md (1024 bytes)
CREATE project/tsconfig.json (408 bytes)
CREATE project/tslint.json (2805 bytes)
CREATE project/.editorconfig (245 bytes)
CREATE project/.gitignore (503 bytes)
CREATE project/src/favicon.ico (5430 bytes)
CREATE project/src/index.html (294 bytes)
CREATE project/src/main.ts (370 bytes)
CREATE project/src/polyfills.ts (3194 bytes)
CREATE project/src/test.ts (642 bytes)
CREATE project/src/styles.css (80 bytes)
CREATE project/src/browserslist (375 bytes)
CREATE project/src/karma.conf.js (964 bytes)
CREATE project/src/tsconfig.app.json (170 bytes)
CREATE project/src/tsconfig.spec.json (256 bytes)
CREATE project/src/tslint.json (314 bytes)
CREATE project/src/assets/.gitkeep (0 bytes)
CREATE project/src/environments/environment.prod.ts (51 bytes)
CREATE project/src/environments/environment.ts (631 bytes)
CREATE project/src/app/app.module.ts (314 bytes)
CREATE project/src/app/app.component.html (1141 bytes)
CREATE project/src/app/app.component.spec.ts (998 bytes)
CREATE project/src/app/app.component.ts (211 bytes)
CREATE project/src/app/app.component.css (0 bytes)
CREATE project/e2e/protractor.conf.js (752 bytes)
CREATE project/e2e/tsconfig.e2e.json (213 bytes)
CREATE project/e2e/src/app.e2e-spec.ts (303 bytes)
CREATE project/e2e/src/app.po.ts (208 bytes)

**npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '...:"0.1.1","fresh":"0.1'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AAAIT\AppData\Roaming\npm-cache\_logs\2018-08-09T09_19_21_148Z-debug.log
Package install failed, see above.**

> LOG
I have attached the log
[2018-08-09T09_19_21_148Z-debug.txt](https://github.com/angular/angular-cli/files/2273667/2018-08-09T09_19_21_148Z-debug.txt)

**Comment by robertbaker** [comment]
This is a problem with your npm/node install. I'm making the assumption that you upgraded from an older version of node, as I've seen the similar error in those situations.

Try running `npm cache clean --force`
then try again. If you get the same error, uninstall nodejs. Then go to program files\nodejs and delete the entire folder. Then go to %appdata% (c:\username\appdata\roaming) and delete the npm and npm-cache folders.
Then reinstall nodejs, I recommend 10.8+ unless you really need to run the older 8.x

**Comment by alexeagle** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
