### ISSUE TITLE
ng is not recognized as an internal or external command

### ISSUE THREAD

**Issue by muscaiu** [angular/angular-cli#1183]
Running windows 7 Professional 32bit.

I tried running npm install -g angular-cli both under normal or admin.
![2016-06-23_14h46_40](https://cloud.githubusercontent.com/assets/11426309/16302839/061eae06-3956-11e6-8e55-a6ddc6b55e93.jpg)

I also tried adding it to the Enviorment Variables under PATH: (C:\Users\Administrator\AppData\Roaming\npm\node_modules\angular-cli\bin\ng) , with no success also.  
![2016-06-23_14h56_48](https://cloud.githubusercontent.com/assets/11426309/16302861/1a1c0412-3956-11e6-8d2d-3360ec766daf.jpg)

What am i doing wrong?

**Comment by RicardoVaranda** [comment]
The only thing that you are doing wrong is using windows :smile:

Just add %AppData%\npm; to the user variable(since %AppData% dir is depending on user) PATH to fix it.

You will need to log out then log back in for the change to your PATH variable to take effect.

**Comment by filipesilva** [comment]
@muscaiu are you still having this problem? @RicardoVaranda's solution seems the right one. Your system wasn't configured with the right PATH for some reason.

**Comment by XK8** [comment]
I have the same problem, the path to npm added to the **PATH** variable, so I think the problem is that the system can not run "ng" file.

**Comment by muscaiu** [comment]
I fixed the problem. 
See here: http://stackoverflow.com/questions/37991556/ng-is-not-recognized-as-an-internal-or-external-command

**Comment by XK8** [comment]
Thanks, fix it.

**Comment by dasariramacharan** [comment]
In case you are editing environment variables make sure you edit for account you are running under.

**Comment by luizhsalazar** [comment]
After spend about one hour to fix "ng is not recognized" in my Windows console I opened a new prompt as "administrator", unninstalled the "angular-cli", cleaned npm cache via "npm cache clean" and installed it again and finally worked o/

**Comment by Shrutikarekal123** [comment]
Try to run in _**node command prompt**_


![untitled](https://user-images.githubusercontent.com/18300185/27373097-8b0d96bc-5684-11e7-8782-9423760cc4a9.png)

**Comment by gautamjgithub** [comment]
Just open your command prompt (run as administrator). Ensure node --v is 6.9.0 or higher and npm --v is 3.0.0 r higher.

After that run the following command: 

npm install -g @angular/cli

Once angular is installed. you can see an entry of angular cli in the path

C:\Users\Dell\AppData\Roaming\npm\node_modules\@angular

Then try ng help. It will work.

**Comment by dhanabalu** [comment]
i had same "ng is not recognized as internal and external command,operable program or batch file "
node version:6.10
just upgrade new version like node 6.11 or latest
while re-installing angular put it in new path like c://erp/ee

**Comment by naru6be** [comment]
At last find the solution for ng command is not working issue ,Find the solution below http://itechiesol.blogspot.com/2017/07/angular-cli-ng-command-is-not-working.html

**Comment by NataliaReyes** [comment]
@Shrutikarekal123  it works now perfectly, thank you very much :)

**Comment by renatop7** [comment]
@gautamjgithub i added %APPDATA%\npm\node_modules@angular to my PATH and it worked! Thanks!

**Comment by willypelz** [comment]
if you try any of the above method and not working make make sure you are using a git bash. This works for one window system i work on. you can download a git bash for window system here https://git-scm.com/downloads

**Comment by yaswanthbs** [comment]
I had the same problem today and have gone through the following path -
 (***%USERPROFILE%\AppData\Roaming\npm***) and came to know that there is some junk data and when I cleared everything under npm directory. Now when I ran (***npm install*** command again). Now everything works fine.

**Comment by joaopgrassi** [comment]
Just as an update for anyone running into the same. `ng` was working fine for me. Yesterday I installed Miktex on my computer and after that ng stopped working. I think it messed up with my Path variable somehow. Adding the npm path again as @RicardoVaranda said works.

**Comment by dinukarumesh** [comment]
Use NodeJS command prompt. I fix my problem.

**Comment by cjoantony** [comment]
Add the **ng** command path from the folder **.bin** under the **node_modules** to PATH variable in the system env settings
e.g: add `C:\testProject\node_modules\.bin\` to `PATH`

**Comment by SunaliBandara** [comment]
run : npm install -g angular-cli
set the path variable =C:\Users\ACER\AppData\Roaming\npm\node_modules\angular-cli\bin

**Comment by AhmetFUsta** [comment]
> You will need to log out then log back in for the change to your PATH variable to take effect.

You don't have to log out and back in, all you need to do is restart explorer.exe OR open up your CMD and run `refreshenv`

**Comment by Sachinists** [comment]
I had the same issue **"'ng' is not recognized as an internal or external command,
operable program or batch file."** when I was trying to run ng serve --host 0.0.0.0  form my command prompt.
But as I run it via node.js command prompt, my issue resolve and I was able to run
ng serve --host 0.0.0.0.
And
It also ran when I prefix it with **npm run** ng serve as mentioned above, but then I was facing issue for --host 0.0.0.0 as it was throwing error.

Can anyone tell me the reason why? What is happening which I am unable to get.?

**Comment by b2rpt** [comment]
please don't confuse yourself... just do one thing

ADD -> " C:\Users\DELL\AppData\Roaming\npm " to PATH in system variable

All set !

**Comment by tarundvarma49** [comment]
Please try to use Node.js command prompt it will work.

**Comment by atul-bajpai** [comment]
npm start also works great
