### ISSUE TITLE
webpack output is no longer colored in git bash

### ISSUE THREAD

**Issue by bedag-moo** [angular/angular-cli#11833]
### Bug Report or Feature Request 
```
- [x] bug report
```

### Command (mark with an `x`)
```
- [x] serve
```

### Versions

```
$ node --version
v8.11.3

$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.2
Node: 8.11.3
OS: win32 x64
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cli                      6.1.2
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

$ git --version
git version 2.14.2.windows.2
```

I use the mingw terminal.

### Repro steps

Run `ng serve`

Expected: webpack output uses colors as in @angular/cli@1.6
Actual: webpack output does not use color

### Mention any other details that might be useful

The color detection logic in 

https://github.com/angular/angular-cli/blob/44086c60ff1d6c26d30850bef125120f6c498ac1/packages/angular_devkit/core/src/terminal/caps.ts#L79-L144

does not recognize the terminal as color capable, because the following if matches:

```
  if (stream && !stream.isTTY) {
    return 0;
  }
```

(`stream` is a Socket, no clue why)

However, git-bash does set a couple environment variables that may be helpful in detecting it, including:

  MSYSTEM: 'MINGW64',
  TERM: 'xterm',

I'll submit a PR shortly.

**Comment by mark-langer** [comment]
@bedag-moo It's great that you guys are addressing this. I just tested version 6.1.4 which should include [your commit](https://github.com/angular/angular-cli/commit/3d2a2f5dab8504bd99f6e5098a385422fbcbb346) and I can see a slight difference vs before:
![image](https://user-images.githubusercontent.com/18142114/44394710-29a17980-a538-11e8-9724-2e747c5b6a7c.png)

The warning at the bottom is now colored in yellow but the chunks are still not colored. Is that behavior intended?

This is what I get in another project with v6.0.8:
![image](https://user-images.githubusercontent.com/18142114/44395077-10e59380-a539-11e8-9e8f-0fa7e4277442.png)

**Comment by bedag-moo** [comment]
In my git-bash, the chunks are colored when using @angular/cli@6.1.4. No clue what's different about your setup ...

**Comment by jensdc92** [comment]
Did you find a solution for this issue?
