### ISSUE TITLE
run-module-worker.js doesn't check message.hash correctly (bad 'if' compare)

### ISSUE THREAD

**Issue by scovetta** [angular/angular-cli#11842]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

master

### Repro steps

The file `packages/angular_devkit/build_angular/src/utils/run-module-worker.js` contains a bug in an `if` statement -- this will always evaluate to 'true':

```
  if (message.hash = '5d4b9a5c0a4e0f9977598437b0e85bcc') {
```

I believe this is intended to be either `==` or `===`:
```
  if (message.hash == '5d4b9a5c0a4e0f9977598437b0e85bcc') {
```

### The log given by the failure

n/a

### Desired functionality

n/a

### Mention any other details that might be useful

This was found through static analysis.

**Comment by alexeagle** [comment]
Root cause here is that we aren't running the right static analysis. We should make this a compiler error in http://tsetse.info I think.

**Comment by clydin** [comment]
There's a tslint rule that covers that: [`no-conditional-assignment`](https://palantir.github.io/tslint/rules/no-conditional-assignment/).  The rule is currently not used (PR in progress to fix that).  The file is also a Javascript file which are not currently linted.
