### ISSUE TITLE
Problem on ng add @angular/pwa

### ISSUE THREAD

**Issue by jeanmazc** [angular/angular-cli#11853]
### Versions
Angular CLI: 6.2.0-beta.2
Node: 10.8.0
OS: win32 x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.0-beta.2
@angular-devkit/build-angular     0.8.0-beta.2
@angular-devkit/build-optimizer   0.8.0-beta.2
@angular-devkit/build-webpack     0.8.0-beta.2
@angular-devkit/core              0.8.0-beta.2
@angular-devkit/schematics        0.8.0-beta.2
@angular/cli                      6.2.0-beta.2
@angular/pwa                      0.7.3
@ngtools/webpack                  6.2.0-beta.2
@schematics/angular               0.8.0-beta.2
@schematics/update                0.8.0-beta.2
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.5

### Repro steps
ng new my-app
cd my-app
ng add @angular/pwa

### The log given by the failure
Installing packages for tooling via npm.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/pwa@0.7.3
updated 1 package and audited 28982 packages in 11.073s
found 12 vulnerabilities (9 low, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
Could not find index file for the project

### Desired functionality
Add the power of pwa. 
The files and configurations were not generate in the project
![pwa](https://user-images.githubusercontent.com/28394621/43975966-a974a820-9cb5-11e8-84be-135ba1e6db47.JPG)

**Comment by alexeagle** [comment]
I think this is a duplicate of #11640
