### ISSUE TITLE
Support --output-hashing for serve command

### ISSUE THREAD

**Issue by dinony** [angular/angular-cli#11852]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

`build` supports `--prod` and `--output-hashing` flags. It would be great if we could use the same flags for `serve`.

E.g.
`ng serve --prod --output-hashing none`

Also see [issue](https://github.com/StudioProcess/rvp/issues/173).

**Comment by filipesilva** [comment]
`ng serve --prod` is already supported, and uses the production configuration in this target:
```
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "latest-project:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "latest-project:build:production"
            }
          }
        },
```

The production configuration here says "use the production build options", which already includes all the production settings like output hashing.

If you have a custom configuration of options you need to use for building, you can add it as a new configuration inside the build target, then point at it from your serve target.
