### ISSUE TITLE
build --optimization documentation is incomplete

### ISSUE THREAD

**Issue by novaterata** [angular/angular-cli#11856]
From the documentation for the `ng build` command at https://github.com/angular/angular-cli/wiki/build
 
    --optimization
    
        Defines the optimization level of the build. 

What are the valid levels? Reading this documentation, I have no idea how to use this option.

**Comment by alan-agius4** [comment]
@novaterata I think the documentation wording there might be a bit misleading

`optimization` can only be `true` or `false`. `true` being `production` and `false` being `development`
