### ISSUE TITLE
Cannot use schematics in custom folder.

### ISSUE THREAD

**Issue by Parth-Agarwal** [angular/angular-cli#11866]
I cannot use the angular material schematics to create the navbar in the src/components folder. The app crashes. Basically, the updates are not happening properly. I can only create using schematics in the src folder.

**Comment by alexeagle** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
