### ISSUE TITLE
Allow to override default template files or folder when generating new files with ng g

### ISSUE THREAD

**Issue by jhcao23** [angular/angular-cli#11860]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
I believe its a common scenarios that developers want to override the default template files, such as components files, under `__name@dasherize@if-flat__` folder. In the src code of @schematics/angular, the location is hard coded as `./files` in the `index.ts`:
```   
 const templateSource = apply(url('./files'), [
```
So can we add this feature so that each time when we generate, the command line (schema) allow user to pass the parameter of the template folder location, such as a component `ng g c componentName -templateFolder = ~/PATH_TO_SOME_DIR/__name@dasherize@if-flat__`?

**Comment by jhcao23** [comment]
+1

**Comment by hansl** [comment]
What you probably want is to use the `--path=a/b/c` option, which is supported by the Component schematic and will move the new files to the path you give it.

Closing this as answered.

**Comment by jhcao23** [comment]
sorry I just realized this `--path` option is not what I wanted. In contrast, the real option I'd need is `--templateFilesPath=~/template/ng-cli/component/files`, which referring to my own template files to replace the @schematics/angular provided files.
