### ISSUE TITLE
Running ng when project is stored on shared network drive

### ISSUE THREAD

**Issue by Maciejszuchta** [angular/angular-cli#11878]
Hello

I moved my project to remote desktop on Windows 10. The local drive that project is on is symlinked to a network drive so all computers in my company have access to it. Unfortunately, when things are configured this way,  I cannot run any ng command. They always give an error like this.

![image](https://user-images.githubusercontent.com/12434636/44032823-9dd9b29e-9f08-11e8-9d82-e3297aaf8ab3.png)

It's because it tries to acces the project via `'C:\192.168.1.10\Projects_D2\AITeF\AITeF` while the path should look like this `C:\Projects\AITeF\AITeF`.

I tried adding "preserveSymlinks": true in my angular.json file but this doesn't work.

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
