### ISSUE TITLE
TSConfig Path resolutions fails for karma.config.ts

### ISSUE THREAD

**Issue by codeNoobie** [angular/angular-cli#11873]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version: v8.11.3
yarn --version: v1.7.0
ng --version: 

Angular CLI: 6.1.3
Node: 8.11.3
OS: darwin x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.3
@angular-devkit/build-angular      0.7.3
@angular-devkit/build-ng-packagr   0.7.3
@angular-devkit/build-optimizer    0.7.3
@angular-devkit/build-webpack      0.7.3
@angular-devkit/core               0.7.3
@angular-devkit/schematics         0.7.3
@angular/cdk                       6.2.0
@angular/cli                       6.1.3
@angular/material                  6.2.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.3
@schematics/angular                0.7.3
@schematics/update                 0.7.3
ng-packagr                         4.0.1
rxjs                               6.2.2
typescript                         2.9.2
webpack  

### Repro steps

1. Create a karma.config.ts and add it to angular.json as the karma configuration for the app or library.
2. Import a local workspace library in karma.config.ts. tsconfig already has the necessary path mapping to the bundle of this workspace library in dist folder.
3. Run ng test

### The log given by the failure

```
12 08 2018 11:42:49.516:ERROR [config]: Invalid config file!
  Error: Cannot find module '@demo/test-config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/<Home_directory>/projects/demo/components/karma.config.ts:9:1)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/<Home_directory>/node_modules/ts-node/src/index.ts:400:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/<Home_directory>/node_modules/ts-node/src/index.ts:403:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.parseConfig (/<Home_directory>/node_modules/karma/lib/config.js:363:22)
    at new Server (/<Home_directory>/node_modules/karma/lib/server.js:56:20)
```
### Desired functionality

Currently, we maintain a local project(@demo/test-config) in our Angular workspace which contains the karma configuration in typescript. This project is then bundled and uploaded on our local nexus so that other team in the company can use the same test configuration. It also consumed in a similar fashion by local workspace library projects.

For other projects in the same repo as `@demo/test-config`, the tsconfig's path resolution doesn't work when we try to import the karma config from `@demo/test-config`. Here is how the karma.config.ts of the other projects looks.
```typescript
import { ExtendedKarmaConfig, KarmaConfigurationGenerator } from "demo/test-config";

export default (config: ExtendedKarmaConfig) => {
    const configGenerator: KarmaConfigurationGenerator = new KarmaConfigurationGenerator(config);
    const karmaConfig = configGenerator.getKarmaConfiguration();
    karmaConfig.coverageIstanbulReporter.dir += "/components";
    config.set(karmaConfig);
};
```
However, when we put the @demo/test-config bundle in node_modules then the test command works fine. Otherwise, it gives the error shown above in the logs section.

**Expected Behavior**: 
Just like local projects path is resolved for non-test code using paths in tsconfig, the same resolution should also work when we import something in karma.config.ts

**Comment by filipesilva** [comment]
Please bear in mind that we don't actually support transpiling the karma configuration. 

Karma itself is trying to transpile your configuration file via `ts-node`. You'll have to look into how Karma loads the paths in the tsconfig. I suggest trying to do this with Karma in a non-CLI project and then trying to backport it into your project.
