### ISSUE TITLE
Unsupported OS error occurred while GULP SERVE

### ISSUE THREAD

**Issue by iubaid** [angular/angular-cli#11877]
AngularJS : 1.4.8
Node: 6.10.3
OS: linux x64
Angular Version is older(1.4.8), That is why i am asking this question separately Kindly answer as per version based.

I am using Linux-x64. and i am unable to start my project as it gives error about "index.controller.js" in developers tools, and while i am running "npm audit fix" it shows this error about unsupported OS.

I have wasted my 2 days but of no use.

**Issue is listed below:**

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Desired Behaviour**

Fix this issue
 
ANY HELP WILL BE APPRECIATED !

**Comment by alexeagle** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by iubaid** [comment]
Thanks @alexeagle
