### ISSUE TITLE
Cannot upgrade globally from beta.5 to beta.8 without extra work

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#1187]
On OSX when I tried to do `npm install -g angular-cli` it would fail with the below error.  However if I do an `npm uninstall -g angular-cli` and then try the `npm install -g angular-cli`

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /usr/local/lib/node_modules/.staging/abbrev-432cdd5a
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-432cdd5a' -> '/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-432cdd5a' -> '/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/zchapple/npm-debug.log
npm ERR! code 1
```

**Comment by BenevidesLecontes** [comment]
I did it and everything works fine.

**Comment by anode7** [comment]
Same for me 
Linux 4.4.0-25-generic
node v6.2.2
npm  v3.10.2
path ~/.npm-global/lib/node_modules/.staging/abbrev-f8dddc67
code ENOENT
errno -2

`npm r -g angular-cli` and `npm i -g angular-cli` works fine...

**Comment by choucry13** [comment]
+1 unfortunaly. I have the problem since the beta 6 for me.

**Comment by anoopzoondia** [comment]
Still having the same issue for me. Please see that attachment. 
<img width="960" alt="cordova issue" src="https://cloud.githubusercontent.com/assets/3204788/16356556/0dcebefc-3afa-11e6-961d-b306fb2bda7e.png">

**Comment by neilhem** [comment]
@anoopzoondia uninstall angular-cli first then install

**Comment by butters16** [comment]
Uninstalling angular-cli and reinstalling it worked for me.

I was getting the same error (....staging/abbrev...)

I fixed it with
`sudo npm uninstall -g angular-cli`
`sudo npm install -g angular-cli`

**Comment by filipesilva** [comment]
This might happen between versions, but according to the update steps in https://github.com/angular/angular-cli#updating-angular-cli you do need to uninstall before.
