### ISSUE TITLE
angular 5 project not created .project stop successfully initalized git

### ISSUE THREAD

**Issue by HASSAANALVI20** [angular/angular-cli#11886]
![1](https://user-images.githubusercontent.com/42384476/44102873-2a2df808-a004-11e8-8726-96a18732f656.PNG)

**Comment by HASSAANALVI20** [comment]
please help

**Comment by alexeagle** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
