### ISSUE TITLE
npm ERR! code Z_DATA_ERROR  

### ISSUE THREAD

**Issue by mhsadiqhussain** [angular/angular-cli#11884]
I'm executing the following command from Git Bash:  
   npm install -g @angular/cli@latest

It's throwing the Error as:
npm ERR! code Z_DATA_ERROR
npm ERR! errno Z_DATA_ERROR
npm ERR! Invalid response body while trying to fetch http://registry.npmjs.org/@angular%2fcli: incorrect header check

I tried with Updating Node.js version, unfortunately didn't work.

Current Node.js installation details are:
node -v :   v8.9.4
npm -v:     5.6.0

Please, help me out people.

**Comment by alexeagle** [comment]
Looks like an npm issue with connecting to the network, not related to Angular CLI.
If you keep having problems with using npm, you might want to try https://angularconsole.com/ which has everything you need in a single download.
