### ISSUE TITLE
Https certificate not recognize by the browser on Angular 6 + .net Core 2.1.2

### ISSUE THREAD

**Issue by ranouf** [angular/angular-cli#11887]
Hi,

I generated the certificate using the following dotnet command:
` dotnet dev-certs https --trust -v --export-path "C:\PATH\localhost.pfx" --password "PASSWORD"`

Then in package.json if have:
`"start": "ng serve --ssl true --ssl-cert 'C:\PATH\localhost.pfx' --proxy-config proxy.config.json"`

When I launch the website on https://localhost:4200/

The certificate is still not recognize by the browser.

How to make it work?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

That said, the `ssl-cert` usually has an extension of `crt` and not `pfx`, ie `--ssl-key` for the key file and `--ssl-cert` for the certificate file

**Comment by ranouf** [comment]
Ok, thanks for your help, I will continue to investigate.

**Comment by ranouf** [comment]
I followed these instructions and every thing works correctly now

**Comment by alan-agius4** [comment]
Glad to hear that :)
