### ISSUE TITLE
Question::Angular 6 - Is there a way to import AppModule into library?

### ISSUE THREAD

**Issue by abedali** [angular/angular-cli#11897]
Our application is already developed and matured one, We are trying to refactor into smaller chunks by creating node modules for re-usability.
Is there a way to import services from AppModule into Library? Please help us.

### Bug Report or Feature Request (mark with an `x`)
```x -Not sure if this feature exists, if yes it is more of like a question.
- [] bug report -> please search issues before submitting
- [Maybe] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [X ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.0.8
Node: 8.11.1
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cli                       6.0.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.3
rxjs                               6.2.1
typescript                         2.7.2
webpack                            4.8.3

**Comment by alexeagle** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by abedali** [comment]
Thanks Alex.

https://stackoverflow.com/questions/51861418/angular-6-is-there-a-way-to-import-appmodule-into-library
