### ISSUE TITLE
`ng new` does not allow creation without any testing

### ISSUE THREAD

**Issue by LoganDark** [angular/angular-cli#11894]
Maybe I don't want or need tons and tons of unnecessary testing frameworks like Protractor, Karma, Jasmine, etc.

What do you think of an option to skip these? There's only an option to omit spec files at the moment, but a flag to skip all testing would be great for, for example, developers who want to use different testing frameworks, or (like me) no testing frameworks. (I prefer to do the testing by hand)

Right now, my solution is:

    rm -rf e2e/ src/karma.conf.js src/*.spec.* tslint.json src/tslint.json .editorconfig src/test.ts
    npm un --save-dev protractor karma karma-chrome-launcher karma-coverage-istanbul-reporter karma-jasmine karma-jasmine-html-reporter jasmine-core jasmine-spec-reporter @types/jasmine @types/jasminewd2 tslint codelyzer

It would be nice not to have these files generated in the first place and added to `package.json`.

**Comment by alexeagle** [comment]
Automated testing of some sort is pretty integral to the Angular ecosystem. You're free to do as you like of course, but I suspect we wouldn't add this option since we want to keep most users on the recommended path.
After you delete the files, are you done? Or does the CLI keep re-adding them?

**Comment by LoganDark** [comment]
Yeah, I'm done. I would be pretty pissed if the CLI kept adding them.

In my opinion, manual testing allows me to get more of a feel for how the user might experience it, but that's just my personal opinion.

**Comment by hansl** [comment]
We used to have a `--minimal` option but it's been disabled until we figure out what it means to have a minimal project. Once that option is re-enabled, that's probably what you're looking for.

**Comment by hansl** [comment]
I opened https://github.com/angular/angular-cli/issues/11904 to track re-enabling the flag.

**Comment by LoganDark** [comment]
This command removes 14 vulnerabilities and almost 200 packages:

```
npm un -D codelyzer jasmine-core jasmine-spec-reporter karma karma-chrome-launcher karma-coverage-istanbul-reporter karma-jasmine karma-jasmine-html-reporter protractor
```

Bloat.
