### ISSUE TITLE
'rootDir' is expected to contain all source files

### ISSUE THREAD

**Issue by samherrmann** [angular/angular-cli#11893]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version:
8.9.0

npm -v:
5.6.0

ng -v:
```
Angular CLI: 6.1.3
Node: 8.9.4
OS: linux x64
Angular: 6.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.7.3
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.7.3
@angular/cli                       6.1.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.7.3
@schematics/update                 0.7.3
ng-packagr                         3.0.6
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.8.3
```

### Repro steps

1. Clone https://github.com/samherrmann/angular-sandbox
2. Checkout `rootDir-expect-all-source-files-error` branch
3. Run `npm install`
4. Run `npm run build`

### The log given by the failure

```
error TS6059: File '/code/projects/bar/src/lib/types.ts' is not under 'rootDir' '/code/projects/foo/src'. 'rootDir' is expected to contain all source files.

Error: error TS6059: File '/code/projects/bar/src/lib/types.ts' is not under 'rootDir' '/code/projects/foo/src'. 'rootDir' is expected to contain all source files.

    at Object.<anonymous> (/code/node_modules/ng-packagr/lib/ngc/compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at /code/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/code/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/code/node_modules/ng-packagr/lib/ngc/compile-source-files.js:19:12)
    at Object.<anonymous> (/code/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at /code/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

### Desired functionality

I would expect the build to be successful. I am not sure at this point if this is a `tsconfig` issue, or a `tsc` issue, or some other issue.

### Mention any other details that might be useful

I also asked this on [StackOverflow](https://stackoverflow.com/questions/51850063/rootdir-is-expected-to-contain-all-source-files)

**Comment by alan-agius4** [comment]
This looks like a problem that is occurring due to the `import types` which was introduced in `TypeScript 2.9`. When emitted these are not being rewired properly (line 3);

**dist/bar/lib/bar.component.d.ts(5,11):**
```ts
export declare class BarComponent implements OnInit {
    private barService;
    list: import("projects/bar/src/lib/types").Item[]; // this should be something like `import("./types").Item[];`
    constructor(barService: BarService);
    ngOnInit(): void;
}
```

The issue though cannot be addressed by Angular-CLI, as the libraries are build with [ng-packagr](https://github.com/dherges/ng-packagr). Would you mind opening the issue there?

Thanks.

**Comment by alan-agius4** [comment]
A workaround for this can be that from your code instead infering the type, you explicitly set it.

in `bar.component.ts` change the below;
```ts
  list = this.barService.list();
```

to: 
```ts
  list: Item[] = this.barService.list();
```

This will remove the type import and and the consuming library will build.

**Comment by alexeagle** [comment]
nice analysis, thanks @alan-agius4 ! I hadn't seen how they fixed the "type cannot be named" issue that was so confusing with the `--declaration` flag. Is there a corresponding issue on the TS repo?

Looks like there is nothing for us to do here?

**Comment by alan-agius4** [comment]
Indeed those errors used to be confused.

TS issue should be: https://github.com/Microsoft/TypeScript/issues/25685

I don’t think there is anything that Angular nor ng-packagr can do.

**Comment by samherrmann** [comment]
@alexeagle, @alan-agius4 many thanks for helping me trace this down!

**Comment by fkolar** [comment]
I wanted to check this really considered fixed? I have two publishable libraries (using nrwl) and facing the same problem

**Comment by ruimarques** [comment]
Note that I was playing with Angular elements like a monkey (and angular libs as a consequence) and got this error by importing stuff from the main app into the lib.

**Comment by Rambou** [comment]
`tsc` alone seems to run fine. So there must be something with `angular/cli` or `ng-packagr` (for me) otherwise makes no sence.
