### ISSUE TITLE
`--minimal` flag does nothing

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#11904]
We should get styleguide guidance for what the `--minimal` flag should act on 6.x / 7.x. Or just implement it the way it was before.

**Comment by marzsocks** [comment]
As of now an empty Angular project is 275mb without a line of project code! It's insane to assume every project needs to be this bloated.

**Comment by LoganDark** [comment]
@marzsocks especially with 3 testing frameworks, that alone equates to _**14**_ vulnerabilities and 196 packages.

**Comment by hansl** [comment]
@marzsocks @LoganDark you'll be happy to know that we don't have any vulnerability listed in `npm audit` as of 6.2.3 and the latest 7.0.0 beta.

**Comment by LoganDark** [comment]
@hansl it's great to know that those few forgetting to install all the testing frameworks won't be vulnerable, however, those testing frameworks (hopefully!!) aren't in use unless you specifically invoke them, so the vulnerabilities weren't that severe anyway.

That still doesn't solve the root issue here. See @marzsocks' comment above.

**Comment by hansl** [comment]
> As of now an empty Angular project is 275mb without a line of project code! It's insane to assume every project needs to be this bloated.

Although I agree that smaller project sizes are nice (and this issue is about re-adding the `--minimal` flag), I think there's a lot of disagreement over what bloated mean. 280MB of node_modules during development is really not large.

The size of node_modules doesn't really impact much, outside of bandwidth and disk size for the developer itself, which I would assume are not that limited. The final size of Angular when bundled and minimized went down significantly with every major release, and this is the size that really matters for end users (along with TTI).

In any case, this issue is about re-implementing the minimal flag.

As a workaround, we moved a lot of dependencies over the time to the project itself, but none of this code affect the final application. You can always `ng new --skip-install` then remove the dependencies you think you won't need. The default path will always contain all testing infrastructure we fully support, as this is the best practices we want to push forward.

**Comment by LoganDark** [comment]
In my opinion, forcing 3 (or more) testing frameworks on people isn't a best practice, but it doesn't matter to me, only adds around 5 minutes of my time wasted removing them all. Not that horrible compared to the weeks it takes to create a good project.

**Comment by LoganDark** [comment]
> Sorry but saying its "best practice" is only true in a certain professional context. Think of the millions of home-style websites, or educational projects out there that don't need all this jazz.

Educational projects usually go with the (One True "Best Practices Ever"™)++ and use 29 testing frameworks with 3 GB of documentation for something like a simple to-do list app.

The fact that such a seemingly trivial issue compelled me to spend so much time here trying to get it changed should be enough proof that, in certain cases, test frameworks are not always desired, like @marzsocks' fourth bullet point.

**Comment by rsarky** [comment]
I would like to help with this issue. A quick scan of the conversation till now tells me that `--minimal` flag needs to be implemented to have minimum bloat in the project. (Less testing frameworks etc.)
Are there any further pointers?

**Comment by LoganDark** [comment]
Not really. Preferably it would have *no* testing frameworks - no Protractor, no Jasmine, no Karma, no .spec files, no TSLint, etc. A minimal project should only have the are minimum. :)

**Comment by rsarky** [comment]
@LoganDark Understood.
Is there anything that is considered as `bloaty` other than testing frameworks?

**Comment by LoganDark** [comment]
It's been 'needing discussion' for a long time. There have been many discussions, but everyone keep pushing it off because they didn't see their opinion in there.

The general consensus is that people want a project that doesn't take up 200+ MB with no modifications. Part of that would be removing all the testing frameworks. Every little bit counts, but I don't want to lose any features of Angular. I just want to use stuff I don't need and won't use and have to spend effort removing with every new project.

**Comment by rsarky** [comment]
@LoganDark Makes sense. I will try to open an initial PR and then we can have further discussions over that. Are the maintainers okay with this?

**Comment by LoganDark** [comment]
I'm sure they'll understand.

**Comment by hansl** [comment]
We just had a meeting internally and we I'm going to work on re-enabling this flag today.

Just a clarification on the `need discussion` label; we have those discussions normally twice a week, but if work planning takes over these discussions may happen once a week.

**Comment by LoganDark** [comment]
Okay, thanks.

**Comment by rsarky** [comment]
Hey @hansl.
I am looking to come onboard and would love to start with this.
Would you be willing to guide me?

**Comment by hansl** [comment]
@LoganDark Could you clarify what you mean by this?

> The general consensus (the opinion people don't like) is that people want a project that doesn't take up 200+ MB with no modifications.

What does having a large node_modules prevent you from doing or what kind of inconveniences does that do?

**Comment by hansl** [comment]
@rsarky I'm going to be on gitter this afternoon, if you want to discuss. But this is time sensitive as the final is in 2 weeks, so I might just actually fix this in 1-2 hours before leaving today.

**Comment by rsarky** [comment]
@hansl I understand. Give me a day?
I think I will be able to do it in that time.

**Comment by LoganDark** [comment]
@hansl it's also an opinion I don't like, to be honest - I just want the inconvenience (testing frameworks) out. I don't care about the size personally, but I was being objective in that statement.

**Comment by LoganDark** [comment]
@rsarky Also, please move the discussion to Gitter or some other IM service. I'm getting an email for every single comment you post here, and you're cluttering up the issue as well.

**Comment by hansl** [comment]
@LoganDark considering @rsarky is discussing the issue at hand it's fine to keep a trail here. you can mute the conversation if you don't want notifications for every messages.

**Comment by LoganDark** [comment]
K
