### ISSUE TITLE
 while installing angular cli and create new angular project  

### ISSUE THREAD

**Issue by vermalove** [angular/angular-cli#11901]
while installing angular cli and create new angular project 

npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'cacache'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\love\AppData\Roaming\npm-cache\_logs\2018-07-01T17_58_21_8
65Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\love\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@6.0.0
3 info using node@v10.8.0
4 verbose stack Error: Cannot find module 'cache'
4 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:637:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:20:18)
4 verbose stack     at Object.<anonymous> (C:\Users\love\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\with-tarball-stream.js:5:17)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:689:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:599:32)
4 verbose stack     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:637:17)
4 verbose stack     at require (internal/modules/cjs/helpers.js:20:18)
4 verbose stack     at Object.<anonymous> (C:\Users\love\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\extract.js:12:27)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:689:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:599:32)
5 verbose cwd D:\new ang
6 verbose Windows_NT 6.3.9600
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\love\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
8 verbose node v10.8.0
9 verbose npm  v6.0.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'cacache'
12 verbose exit [ 1, true ]

**Comment by alexeagle** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
