### ISSUE TITLE
Add option to preserve unused components (with factories) in the bundle

### ISSUE THREAD

**Issue by WiseBird** [angular/angular-cli#11907]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version
v8.9.3

npm --version
4.1.2

Angular CLI: 1.6.0

### Repro steps

[Reproduction](https://github.com/WiseBird/ng_unused_components_removal) shows that when you have unused component (the one added to a module and exported from it but not used in any template) it is removed from bundle on production build.

Run `npm run build` and check `bundle/bundle.main.js`. There is no `NotUsedComponent` that is included in a module:
```
@NgModule({
    imports: [
        CommonModule,
    ],
    declarations: [
        UsedComponent,
        NotUsedComponent,
    ],
    exports: [
        UsedComponent,
        NotUsedComponent,
    ],
})
export class ComponentsModule {
}
```

### Desired functionality

Our use case is plugins - build independently from main app and loaded dynamically in run time. We have components library that is shared among main app and plugins. Would be great to load it only once with the app an reuse for each plugin. In such case plugins can be much smaller.

But if one of the library components is used only in plugin then it will not be included in main app. So we forced to bundle shared components with every plugin hence bigger size and more time to load.

**Comment by alan-agius4** [comment]
Hi @WiseBird,

Kindly see: https://github.com/angular/angular-cli/issues/15809#issuecomment-543281509 or https://github.com/angular/angular/issues/35314 on ways to retain unused components in the final bundle.

Thanks.
