### ISSUE TITLE
I execute the " ng add @angular/pwa" command, and do not automatically create relevant files of service worker after successful installation

### ISSUE THREAD

**Issue by shellChang** [angular/angular-cli#11914]
### Bug Report or Feature Request (mark with an `x`)
I execute the " ng add @angular/pwa" command, and do not automatically create relevant files of service worker after successful installation

### Command (mark with an `x`)
 ng add @angular/pwa

### Versions

node -v
v10.6.0

npm -v
6.1.0

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.8
Node: 10.6.0
OS: win32 x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.4.5
@angular/cli                      6.0.8
@angular/pwa                      0.7.3
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

windows version
windows 10 家庭版

### Repro steps

excute command after 

ng add @angular/pwa
Installing packages for tooling via npm.
+ @angular/pwa@0.7.3
updated 1 package in 8.534s
Installed packages for tooling via npm.
Invalid rule result: Function().

it say "Invalid rule result: Function()."

Is this reason?

**Comment by enniob** [comment]
I'm having the same issue. I made a new app using 

`
ng new MyPWA

ng add  @angular/pwa
`
and I get the following error:

Installing packages for tooling via npm.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/pwa@0.7.3
added 5 packages from 2 contributors in 19.266s
[!] 14 vulnerabilities found [26695 packages audited]
    Severity: 9 low | 5 high
    Run `npm audit` for more detail

Installed packages for tooling via npm.
Invalid rule result: Function().


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/pwa                      0.7.3
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3

**Comment by enniob** [comment]
This is fixed with the latest cli update :). I just tested and its working fine

**Comment by clydin** [comment]
Duplicate of #11663
