### ISSUE TITLE
doesn't angular-cli has runtimeArgs of --nolazy like nodejs?

### ISSUE THREAD

**Issue by shenchaoran** [angular/angular-cli#11912]
When debugging with VS Code, the breakpoint often become `Unverified breakpoint`,  and node could avoid this by `--nolazy`, but ng couldn't. So I want to ask how to avoid `Unverified breakpoint`?

**Comment by hansl** [comment]
You can manually run the CLI with `node --nolazy node_modules/.bin/ng` if you want to use this. You can configure VSCode to use that command.

**Comment by shenchaoran** [comment]
@hansl  this solved my problom, thanks
