### ISSUE TITLE
Customize Uglify JS Option

### ISSUE THREAD

**Issue by SridharSathaSivam** [angular/angular-cli#11910]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Desired functionality
I am need to customize the uglifier option from the webpack configuration. Can you please suggest me to how to pass the custom option for uglify JS.

### Clarification
I hope `ng eject` is disabled in Angular 6. So can you please let know will it available in future if so can tell proximate timeline. 

Also, It would better to Customize whole webpack options.

**Comment by filipesilva** [comment]
I'm sorry to say that adding fine grained control to uglify-js is something we've discussed and decided not to do at the moment.

**Comment by keenondrums** [comment]
@SridharSathaSivam  I created a [small custom builder for that](https://github.com/keenondrums/angular-builder-custom-terser-options). Hopefully we won't have to use for a long time and Angular teams adds this functionality at some point to their default builder.
