### ISSUE TITLE
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory

### ISSUE THREAD

**Issue by anivaisu** [angular/angular-cli#11911]
Hi,

I got error Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'F:\anitha\jofoz-web\src'
resolve './$$_gendir/app/app.module.ngfactory' in 'F:\anitha\jofoz-web\src'

My angular cli version 
 "@angular/cli": "^1.5.0"

My global angular cli version
Angular CLI: 6.1.3

How can i fix this problem.

Kindly advice me,

Thanks

**Comment by hansl** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If you file a new issue, please follow the template and provide a reproduction.
