### ISSUE TITLE
padEnd does not exist on type string error during build

### ISSUE THREAD

**Issue by WeiZhou2** [angular/angular-cli#11922]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node --version: v8.11.3
npm --version: 5.4.2 
ng --version: 
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.3.1
@angular/cli                       6.0.8
@angular/material                  6.3.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.3
rxjs                               6.2.1
typescript                         2.7.2
webpack                            4.8.3

### Repro steps

> `let firstLine: String = 'WORK ITEM MISPAY-LOCATE MISSING PAYMENT HAS BEEN CREATED.';
    firstLine = firstLine.padEnd(50, ' ');`

### The log given by the failure
BUILD ERROR
projects/transaction-management/src/lib/transaction-management.component.ts(695,35): error TS2339: Property 'padEnd' does not exist on type 'string'.

Error: projects/transaction-management/src/lib/transaction-management.component.ts(695,35): error TS2339: Property 'padEnd' does not exist on type 'string'.

    at Object.<anonymous> (C:\workspace\transaction-management\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at C:\workspace\transaction-management\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\workspace\transaction-management\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\workspace\transaction-management\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\workspace\transaction-management\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at C:\workspace\transaction-management\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

### Desired functionality
I am building a library and using the string.padend and cannot build

**Comment by clydin** [comment]
PadEnd is part of ES2017.  Ensure that the project’s TS config is configured appropriately for using ES2017 features. It may also be prudent to review the project’s required browser suppport to ensure that they support the necessary ES2017 features.
