### ISSUE TITLE
Can anyone let me know how to update from version 6.0.7 to 6.1.4

### ISSUE THREAD

**Issue by rajguru827** [angular/angular-cli#11930]

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow ](https://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) explanation.

That said, please check https://github.com/angular/angular-cli/wiki/update

**Comment by rajguru827** [comment]
Sorry about that...
