### ISSUE TITLE
ng build library doesn't include json files like normal app

### ISSUE THREAD

**Issue by florian-kittel** [angular/angular-cli#11931]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
```

### Command (mark with an `x`)
```
- [ x ] build

```

### Versions
node --version
v8.11.1
npm --version
5.6.0

Angular CLI: 6.1.4
Node: 8.11.1
OS: win32 x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.4
@angular-devkit/build-angular      0.7.4
@angular-devkit/build-ng-packagr   0.7.4
@angular-devkit/build-optimizer    0.7.4
@angular-devkit/build-webpack      0.7.4
@angular-devkit/core               0.7.4
@angular-devkit/schematics         0.7.4
@angular/cli                       6.1.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.4
@schematics/angular                0.7.4
@schematics/update                 0.7.4
ng-packagr                         3.0.6
rxjs                               6.2.2
typescript                         2.7.2
webpack                            4.9.2

Windows 7

### Repro steps

(Important: This issue is related to import a .json file in a via cli generated library and not in the default app in src, first steps are to show the complete way for reproducing.) 

1. Create a new project with "ng new my-app" (you can also add common options)
2. Generate a new component with "ng g c feature/settings"
3. Create a json file in the src/app/feature/settings folder and name it settings.json with following content
```
{
  "title": "Settings configuration",
  "content": "This is the settings page."
}
```

4. Import the settings file in settings.component.ts with
```
import { Component, OnInit } from '@angular/core';
import * as config from './settings.json';

@Component({
  selector: 'app-display-settings',
  templateUrl: './display-settings.component.html',
  styleUrls: ['./display-settings.component.scss']
})
export class SettingsComponent implements OnInit {
  config: any;
  constructor() { }
  ngOnInit() {
    this.config = config;
  }
}

```
5. In settings.component.html add the output of the config via
```
<h1>{{config.title}}</h1>
<p>{{config.content}}</p>
```
6. When you try to build the app now we `ng build --prod` you will get the following error:
```
ERROR in src/app/feature/settings/settings.component.ts(2,25): error TS2307: Cannot find module './settings.json'.
```
7. This would be normally solved by adding a typings.d.ts file in src folder. So we do it, with the following content:
```
declare module "*.json" {
  const value: any;
  export default value;
}
```
8. Now run `ng build --prod` again, and it will work like expected and generate "my-app" under the dist folder. All is good and fine, but now comes the issue.
9. Generate a new library with `ng g library my-lib`.
10. To check if all works fine execute the build command for the lib via `ng build my-lib --prod`. It will generate the lib in the dist folder under dist/my-lib.
11. In the projects/my-lib/src/lib folder add the same settings.json form above
12. Extend the my-lib.component.ts with the import and use of the config like we did before. Your file should look like this:
```
import { Component, OnInit } from '@angular/core';
import * as config from 'config.json';
@Component({
  selector: 'lib-my-lib',
  template: `
  <h1>{{config.title}}</h1>
  <p>{{config.content}}</p>
  `,
  styles: []
})
export class MyLibComponent implements OnInit {
  config: any;
  constructor() { }
  ngOnInit() {
    this.config = config;
  }
}
```
13. Now execute `ng build my-lib --prod` again. You will run in the following error:
```
projects/my-lib/src/lib/my-lib.component.ts(2,25): error TS2307: Cannot find module 'config.json'.
```

### The log given by the failure
```
BUILD ERROR
projects/my-lib/src/lib/my-lib.component.ts(2,25): error TS2307: Cannot find module 'config.json'.

Error: projects/my-lib/src/lib/my-lib.component.ts(2,25): error TS2307: Cannot find module 'config.json'.

    at Object.<anonymous> (C:\Users\...\development\pocs\my-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at C:\Users\...\development\pocs\my-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\...\development\pocs\my-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\Users\...\development\pocs\my-app\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (C:\Users\...\development\pocs\my-app\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:26:32)
    at Generator.next (<anonymous>)
    at C:\Users\...\development\pocs\my-app\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

### Desired functionality
It should build the library like the app by including the json file.

### Mention any other details that might be useful
I tried out to import the component directly in the app via public_api.ts and it will work. It also build the app including the component from the projects folder and as well with the json file. But it won't build the library standalone in the dist folder.
I also tried out to include the typings.d.ts in the tsconfig.lib.json and as well to put a separate file in the projects/my-lib/src folder, but it changes nothing.

**Comment by alan-agius4** [comment]
Libraries are built using a 3rd party packages [ng-packagr](https://github.com/dherges/ng-packagr). I'd suggest you re-post your issue there.

That said, please check https://github.com/dherges/ng-packagr/issues/1050 and https://github.com/dherges/ng-packagr/issues/966

**Comment by florian-kittel** [comment]
@alan-agius4 I also tried your suggestion with "Bdw, to import a json in TypeScript version 2.9 you can use resolveJsonModule together with esModuleInterop, no need to create a custom module.", but it seems, that is is not working with angular cli.

**Comment by alan-agius4** [comment]
Yes, indeed as mentioned in the original tread. 

Also the mentioned issue, is related to `Angular Compiler` and not the `CLI`. Which is being tracked here https://github.com/angular/angular/issues/25456

**Comment by alan-agius4** [comment]
I am still struggling a bit to understand the need to support Json at a library level.

For me there are 2 better alternatives IMHO.

1) Instead of JSON use a tokenised object literal in TypeScript, Which eventually consumers can even change via DI.


```ts
// Tokens and Models
export interface DefaultOptions {
  timeout: number;
}

export const DEFAULT_OPTIONS =  new InjectionToken<DefaultOptions>('default-options');

// Module
@NgModule({
  providers: [
    {
      provide: DEFAULT_OPTIONS,
      useValue: {  timeout: 10  } as DefaultOptions
    }
  ]
})

// Usage
export class DefaultComponent {
    constructor(@Inject(DEFAULT_OPTIONS) private _defaultOptions: DefaultOptions){}
}
```
2). Use the `forRoot` pattern
https://angular.io/guide/singleton-services#forroot

It is important to note, when building and developing a libraries is different than an application.

**Comment by florian-kittel** [comment]
@alan-agius4 we are currently migrating our Angular 4 Library to Angular 6 with the new project folder structure. The library is used in the financial industry, has a large codebase and consits of many large legal related components. We prebundel the default text within the components. This has the benefit, that the user will only need to download the component and text when he reach the page via lazy loading, where the component is shown and so we can use the component without any additional setup. We have as well the possiblity to overwrite the texts with i18n variables, but we don't want to bundle all texts into a large translation json file, when we deliver by default all in one language.

The example was only short, that everybody can see what the issue is. At the end the json files are very large with a lot of configuration, that changes over time. For now I created a workaround, that takes alle json files, rewrite them as .ts file and included in component for the build, instead of the json file. This enables the author to change the content in the given json format and a script rewrites all to .ts files automatically. But anyway to include a json file in typesript should not be an issues for the new cool library bundling with the Angular Cli.

**Comment by dominique-mueller** [comment]
@alan-agius4 I don't see how Dependency Injection solves the issue of importing JSON files. Sure, one could use DI (here Injection Tokens) to:
- import the JSON file into the application instead
- provide the imported JSON file to the library using the Injection Tokens

But that would require:
- additional code in the application (duplicate and unnecessary code)
- all JSON files to be published within the library (this would be required now, not optional)

**Comment by thierrybellevue** [comment]
`
// Replace
import * as config from 'config.json';
// With
const config = require('config.json');
`
Works for me. And "declaration" is false in my tsconfig.lib.json files.
`
"compilerOptions": {
    ...
    "declaration": false
}
`
I was finally able to include the JSON file in my library.

**Comment by supamax** [comment]
Showstopper for me too.

**Comment by kamuran21** [comment]
I resolve this problem by this way : 

```
...
fs.writeFile('./src/environments/html-maps/build.map.ts','export const buildMap = ' + JSON.stringify(fullMap),(err)=>{
    if(err){
        console.log('hata->',err)
    } else{
        console.log('baba canavar')
    }
})
```
create a ts file thanks of nodejs and import the file in my environment.

**Comment by rmcsharry** [comment]
I get the same error by trying to import `package.json` into my `environment.ts` file.

After running `ng serve`, the error shows up:

`ERROR in src/environments/environment.ts(5,27): error TS2307: Cannot find module '../../package.json'.
`
**｢wdm｣: Failed to compile.**

**environments\environment.ts**
```
import * as settings from '../../package.json';

export const environment = {
  version: settings.version,
  name: settings.name,
  production: false,
...other settings...
};
```

**tsconfig.json**
```
{
  "compileOnSave": false,
  "preserveWhitespaces": "off",
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "lib": [
      "es2016",
      "dom"
    ],
    "module": "es2015",
    "baseUrl": "./",
    "resolveJsonModule": true,
    "esModuleInterop": true
  }
}
```

Now [watch this ](url)(<2 min vid) - it consistently goes away and comes back every time I edit the import statement. I think something strange is happening here in the ng build process.
