### ISSUE TITLE
Angular Compiler was detected but it was an instance of the wrong class

### ISSUE THREAD

**Issue by ajeeshc** [angular/angular-cli#11937]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ x] config
- [ ] help
- [x ] version
- [ ] doc
```

### Repro steps
ng build

### The log given by the failure
ERROR in ./src/main.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (C:\WORK\folder\folder\folder\node_modules\@ngtools\webpack\src\loader.js:33:15)
 @ multi ./src/main.ts
ERROR in ./src/polyfills.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with `npm ls @ngtools/webpack`, and then remove the extra copies.
    at Object.ngcLoader (C:\WORK\folder\folder\folder\node_modules\@ngtools\webpack\src\loader.js:33:15)
 @ multi ./src/polyfills.ts
ERROR in Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (C:\WORK\folder\folder\folder\node_modules\@angular\compiler\bundles\compiler.umd.js:20291:23)
    at CompileMetadataResolver.getNgModuleMetadata (C:\WORK\folder\folder\folder\node_modules\@angular\compiler\bundles\compiler.umd.js:15244:60)
    at visitLazyRoute (C:\WORK\folder\folder\folder\node_modules\@angular\compiler\bundles\compiler.umd.js:31182:104)
    at AotCompiler.listLazyRoutes (C:\WORK\folder\folder\folder\node_modules\@angular\compiler\bundles\compiler.umd.js:31150:20)
    at AngularCompilerProgram.listLazyRoutes (C:\WORK\folder\folder\folder\node_modules\@angular\compiler-cli\src\transformers\program.js:228:34)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\WORK\folder\folder\folder\node_modules\@angular\compiler-cli\src\ngtools_api.js:47:40)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\WORK\folder\folder\folder\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\ang

### Desired functionality
should build the project 

### Mention any other details that might be useful
Version info
```
Angular CLI: 1.7.0-beta.2
Node: 8.9.4
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

@angular/cli: 1.7.0-beta.2
@angular/compiler-cli: 6.1.3
@angular/language-service: 6.1.3
@angular-devkit/architect: 0.8.0-beta.3
@angular-devkit/build-angular: 0.8.0-beta.3
@angular-devkit/build-optimizer: 0.8.0-beta.3
@angular-devkit/build-webpack: 0.8.0-beta.3
@angular-devkit/core: 0.8.0-beta.3
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 6.2.0-beta.3
@schematics/angular: 0.1.17
@schematics/package-update: 0.0.7
typescript: 2.9.2
webpack: 4.16.5

```

package.config
```
{
  "name": "app1",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@progress/kendo-angular-buttons": "^3.0.4",
    "@progress/kendo-angular-dateinputs": "^2.2.0",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-grid": "^2.1.2",
    "@progress/kendo-angular-inputs": "^2.2.0",
    "@progress/kendo-angular-intl": "^1.3.2",
    "@progress/kendo-angular-l10n": "^1.0.7",
    "@progress/kendo-data-query": "^1.2.0",
    "@progress/kendo-drawing": "^1.5.1",
    "@progress/kendo-ui": "^2018.2.620",
    "angular-font-awesome": "^3.1.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0-beta.0",
    "@angular/cli": "1.7.0-beta.2",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}
```

npm list -global --depth 0

+-- @angular/cli@1.6.8
    +-- angular-1.6-cli@1.6.3
    +-- gulp@3.9.1
    +-- gulp-cli@2.0.1
    +-- typescript@2.9.2
    +-- uglify-js@3.3.24
    +-- webpack@4.16.2
    +-- webpack-cli@3.1.0
    `-- webpack-dev-server@3.1.5

I have tried all the possible thinks like

Deleting the node_module folder and Package.lock.json
Reinstalling the npm - npm Install
Tried npm update

**Comment by hansl** [comment]
> Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with npm ls @ngtools/webpack, and then remove the extra copies.

Can you do `npm ls @ngtools/webpack` and report the result? Thanks.

**Comment by Rush** [comment]
I also have the same problem. There is only one `@ngtools/webpack`.

**Comment by wtmenten** [comment]
I had this problem today and fixed it by downgrading my angular-cli to version 1.6.8 in my package.json
This could be due to a difference in required typescript versions between 1.6.x and 1.7.x, but I havn't investigated that portion of it.

**Comment by gajalchouhan** [comment]
Please, someone, suggest to me that I am facing the same problem.
Actually my project in Angular version 1.0.0-beta.28.3. I am using angular as global angular 6.2.2.
when I am trying to use ng serve this error has come. Can anyone suggest me that what should I do?

ERROR in ./src/main.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with npm ls @ngtools/webpack, and then remove the extra copies.
at Object.ngcLoader (/home/gajal/lok/AuBankProject/node_modules/@ngtools/webpack/src/loader.js:458:19)
@ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
ERROR in ./src/polyfills.ts
Module build failed: Error: Angular Compiler was detected but it was an instance of the wrong class.
This likely means you have several @ngtools/webpack packages installed. You can check this with npm ls @ngtools/webpack, and then remove the extra copies.
at Object.ngcLoader (/home/gajal/lok/AuBankProject/node_modules/@ngtools/webpack/src/loader.js:458:19)
@ multi ./src/polyfills.ts

**Comment by DivyanshuLoktra** [comment]
Facing the similar problem stated above
Tried everything listed on all forums, Nothing works

**Comment by mathias-nordicfactory** [comment]
I had this issue as well when working with submodules in conjunction with ng-packagr. What I had to do in order to resolve the issue was to completely re-install `@angular-devkit/build-angular` everywhere (main project and submodule/package).
`npm uninstall @angular-devkit/build-angular`

`npm install @angular-devkit/build-angular -D`

Not sure why this fixed the issue though

**Comment by filipesilva** [comment]
Hey all,

The `@ngtools/webpack` webpack plugin does not support having multiple instances in the same webpack compilation.

To the best of our knowledge, this problem only comes up when there are multiple `@ngtools/webpack` installed in your node modules. 

This should never happen in a CLI project with the default configuration. Angular CLI >=6 should be used with `@angular-devkit/build-angular`, while Angular CLI <6 should be used without it.

If you use npm, you should be able to check this by running `npm ls @ngtools/webpack`. If you use yarn, the command is `yarn list @ngtools/webpack` instead. 

If you find several installs of `@ngtools/webpack` then most likely you have added it, or another package that depends on it, by accident to your `package.json`. If that's the case just remove the extra packages and reinstall the node modules. On CLI projects you only need to have `@angular-devkit/build-angular` installed.

If you are using a custom webpack setup, you must make sure there is a single instance of `@ngtools/webpack` in the webpack compilation.
