### ISSUE TITLE
Error in repo docs for environment, should be in config folder not under app.

### ISSUE THREAD

**Issue by yahyaKacem** [angular/angular-cli#1193]
[This section](https://github.com/angular/angular-cli#environments) in the `README.md` file:
>You can also add your own env files other than dev and prod by creating a src/client/app/environment.{NAME}.ts and use them by using the --env=NAME flag on the build/serve commands.

Point out that we should putting the environment file under the `src/app` folder when I did that it complained about no file `config/environment.{NAME}.ts`, and when I moved the file there it worked correctly.

**Comment by filipesilva** [comment]
Right you are! Would you be interested in submitting a PR correcting this? Ping me back here and I will approve it.

**Comment by filipesilva** [comment]
Closed by https://github.com/angular/angular-cli/pull/1275.
