### ISSUE TITLE
issue while creating ng new command

### ISSUE THREAD

**Issue by Warangswati** [angular/angular-cli#11943]
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major vers
ion bump
npm WARN tarball tarball data for @angular/language-service@^6.1.0 (sha512-cAIpt
ulTWn1LGFTmRzBbNY4axhnyQl/YaocX0JqutmI+eaWTofSiDwHVB2spYSDTWhy9fg+OMK2KmhghpZmc1
g==) seems to be corrupted. Trying one more time.
npm WARN tarball tarball data for @types/jasminewd2@~2.0.3 (sha512-hYDVmQZT5VA2k
igd4H4bv7vl/OhlympwREUemqBdOqtrYTo5Ytm12a5W5/nGgGYdanGVxj0x/VhZ7J3hOg/YKg==) see
ms to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\dotdot\abc\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\core-135fbd58\esm2015\src\di\defs.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Swati\De\node_mo
dules\.staging\resolve-2ec61d22\test'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Swati\De\node_mo
dules\.staging\uri-js-97284a45\dist\esnext\schemes'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\core-135fbd58\esm2015\src\di\forward_ref.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\faulty_basedir.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\filter_sync.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\deprecated\date_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\core-135fbd58\esm2015\src\di\injectable.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\filter.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\mock_sync.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\deprecated\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\core-135fbd58\esm2015\src\di\injection_token.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\mock.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\deprecated\intl.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\deprecated\number_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\core-135fbd58\esm2015\src\di\injector.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\module_dir.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\i18n_plural_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\i18n_select_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\index.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\invalid_pipe_argument_error.d.t
s'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\json_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\keyvalue_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\number_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\pipes\slice_pipe.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\platform_id.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\version.d.ts'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\src\viewport_scroller.d.ts'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Swati\De\node_mo
dules\.staging\@angular\compiler-c68f2e6d\esm2015\src'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\rxjs-b6a7ac7b\_esm2015\ajax\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\compiler-c68f2e6d\esm2015\src\compiler.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\rxjs-b6a7ac7b\_esm2015\ajax\index.js.map'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\less-16b6d9d4\lib\less\environment\abstract-file-manager.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\less-16b6d9d4\lib\less\environment\abstract-plugin-loader.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\less-16b6d9d4\lib\less\environment\environment-api.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\less-16b6d9d4\lib\less\environment\environment.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\less-16b6d9d4\lib\less\environment\file-manager-api.js'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\Swati\De\node_mo
dules\.staging\less-16b6d9d4\lib\less'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\resolve-2ec61d22\test\module_dir\xmodules\aaa\index.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\fesm5\http\testing.js'
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Swati\De\node_mod
ules\.staging\@angular\common-6d67cb82\fesm5\http\testing.js.map'
npm ERR! path C:\Users\Swati\De\node_modules\.staging\@angular\language-service-
d0224425\src\typescript_host.js
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\Swati\De\node_m
odules\.staging\@angular\language-service-d0224425\src\typescript_host.js'
npm ERR!  { Error: EPERM: operation not permitted, unlink 'C:\Users\Swati\De\nod
e_modules\.staging\@angular\language-service-d0224425\src\typescript_host.js'
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\Swati\De\n
ode_modules\.staging\@angular\language-service-d0224425\src\typescript_host.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path: 'C:\\Users\\Swati\\De\\node_modules\\.staging\\@angular\\lan
guage-service-d0224425\\src\\typescript_host.js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, unlink \'C:\\Users\\Sw
ati\\De\\node_modules\\.staging\\@angular\\language-service-d0224425\\src\\types
cript_host.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\Swati\\De\\node_modules\\.staging\\@angular\\langua
ge-service-d0224425\\src\\typescript_host.js',
npm ERR!   parent: 'de' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or ant
ivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check t
he
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended
).
npm WARN tarball tarball data for codelyzer@~4.2.1 (sha512-CKwfgpfkqi9dyzy4s6ELa
xJ54QgJ6A8iTSsM4bzHbLuTpbKncvNc3DUlCvpnkHBhK47gEf4qFsWoYqLrJPhy6g==) seems to be
 corrupted. Trying one more time.
npm WARN tarball tarball data for karma-chrome-launcher@~2.2.0 (sha512-uf/ZVpAab
DBPvdPdveyk1EPgbnloPvFFGgmRhYLTDH7gEB4nZdSBk8yTU47w1g/drLSx5uMOkjKk7IWKfWg/+w==)
 seems to be corrupted. Trying one more time.

**Comment by Warangswati** [comment]
can anyone tell me what is going wrong

**Comment by hansl** [comment]
This is a Node error. It seems you have some problem with your node/npm configuration. You could try to use the `--skip-install` flag and `npm install` yourself after it's done.

Closing this as it happens outside of the CLI.
