### ISSUE TITLE
Feature Request - multiple environments management

### ISSUE THREAD

**Issue by yahyaKacem** [angular/angular-cli#1194]
1. OS: Linux (Ubuntu 14.04).
2. `ng --version`:
```
angular-cli: 1.0.0-beta.6
node: 6.2.1
os: linux x64
```
It would be nice to have the possibility to add/list/rename/delete environments something like:
```
ng add env NAME
ng rename env NAME
ng delete env NAME
ng list env
```
For me I have a prod, beta and dev version they have some environment differences, that's easier to configure during the build.

**Comment by briananderson1222** [comment]
currently you can create environment files in the config folder. I know this doesn't work via the cli but the cli recongizes the following format when building: 

`environment.${env}.ts`

`ng build --environment=beta`

**Comment by yahyaKacem** [comment]
@briananderson1222 thank you for you reply, I'm already doing that, this is a feature request for the cli to handle the add/delete/list/rename environments.

**Comment by filipesilva** [comment]
I'm sorry but I don't see the benefit of this feature. It would be the same as just doing cp/mv/rm/ls.

I'm closing it for now but feel free to convince me otherwise.
