### ISSUE TITLE
Customizing UI components in @nebular

### ISSUE THREAD

**Issue by rmdss** [angular/angular-cli#11949]
I am customizing UI of register page in @nebular/auth. I downloaded the source code from '[](https://github.com/akveo/nebular/tree/master/src/framework/auth/components)' and added routings. But when I build it it gives the following error.
ERROR in src/app/@theme/components/auth/auth.module.ts(9,3): error TS2305: Module '"project/node_modules/@nebular/theme/index"' has no exported member 'NbButtonModule'. How can I resolve this error?

**Comment by thefliik** [comment]
I think you've mistakenly posted your question to the wrong repo. This is the angular-cli repo. Not an `@nebular` repo. And regardless, I don't believe the angular-cli team answers issues which are just questions.

**Comment by hansl** [comment]
Hi @rmdss ,

Like @thefliik said, this is the Angular CLI repo. You should submit an issue on the Nebular repo.
