### ISSUE TITLE
3rd Party Lib (Tiff.js) import errors out requiring node globals

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#11944]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```bash
> node -v
  v10.9.0

> yarn -v
  v1.9.4

> sw_vers
  ProductName:	Mac OS X
  ProductVersion:	10.13.6
  BuildVersion:	17G65
```

### Repro steps

```bash
> npx @angular/cli@6.1.4 new explorer
> cd explorer && yarn add tiff.js
```

In app.component.ts
```ts
import * as tiff from 'tiff.js'

console.log(tiff);
```

### The log given by the failure

```bash
ERROR in ./node_modules/tiff.js/tiff.min.js
Module not found: Error: Can't resolve 'crypto' in '~/explorer/node_modules/tiff.js'
ERROR in ./node_modules/tiff.js/tiff.min.js
Module not found: Error: Can't resolve 'fs' in '~/explorer/node_modules/tiff.js'
ERROR in ./node_modules/tiff.js/tiff.min.js
Module not found: Error: Can't resolve 'path' in '~/explorer/node_modules/tiff.js'
ℹ ｢wdm｣: Failed to compile.
```

### Desired functionality

`ng serve` should not fail with Tiff.js import

### Mention any other details that might be useful

Tiff.js size is 2MB when compiled with angular-cli and therefore, I need to use dynamic import for quicker TTI
```ts
const tiff = await import('tiff.js');
```

##### Workaround
Add 'tiff.js' in `angular.json` scripts section.  This works for me but application take long time to show UI.
```json
 "scripts": ["./node_modules/tiff.js/tiff.min.js"]
```

I tried to create an example project hosted on `stackblitz.com` with tiff.js import however it works as expected.

**Comment by alan-agius4** [comment]
Please take a look here: https://github.com/angular/angular-cli/issues/1548#issuecomment-286151056

**Comment by clydin** [comment]
The workaround is not really a workaround but rather the intended usage with a browser platform.  The package only supports the import/require usage on the Node.js platform as indicated in the package's [readme](https://github.com/seikichi/tiff.js/blob/master/README.md#usage).

A browser and Node.js are distinct platforms (that happen to share a language).  Outside of what is defined within Javascript specification, both have differing builtin APIs; almost all of which are not shared between the two.

**Comment by JoeKahl** [comment]
We are suffering this same issue. After upgrading from Angular 2.0.0 to Angular 6.1.10 we are using the CLI for ng build and we have no more web pack.  Our web app is using pdf and jpeg and tiff images heavily.  We are using the tiff.js library and the ng build is resulting in:
ERROR in ./node_modules/tiff.js/tiff.min.js
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\jkahl1\Source\Repos\servicecenter-fe\node_modules\tiff.js'
ERROR in ./node_modules/tiff.js/tiff.min.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\jkahl1\Source\Repos\servicecenter-fe\node_modules\tiff.js'
ERROR in ./node_modules/tiff.js/tiff.min.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\jkahl1\Source\Repos\servicecenter-fe\node_modules\tiff.js'
We tried:
angular.json - "scripts": ["./node_modules/tiff.js/tiff.min.js"] and get the same results.
Is there a CLI only way to get this library to work?
Do we need to fork tiff.js?  Please provide guidance.

**Comment by shijianjian** [comment]
Help needed on this.

**Comment by shijianjian** [comment]
This worked:
https://blog.lysender.com/2018/07/angular-6-cannot-resolve-crypto-fs-net-path-stream-when-building-angular/
