### ISSUE TITLE
Too much requests when I load

### ISSUE THREAD

**Issue by Newbie012** [angular/angular-cli#1195]
angular-cli: 1.0.0-beta.2-mobile.4
    node: 6.2.1
    os: win32 x64

When I load my app, I get like 383 requests. My Firefox can't handle it. What can I do?

**Comment by zackarychapple** [comment]
Possibly you need to update Firefox or run in prod mode are the two best ways.  Development mode doesn't bundle and compress.

**Comment by neilhem** [comment]
Waiting 5-10 seconds to app load every time when you make changes is not good on development

**Comment by zackarychapple** [comment]
What version of Firefox are you on?

**Comment by Newbie012** [comment]
The latest. It crushes when my elements inspector (f12) is on.

**Comment by filipesilva** [comment]
We're working on an update of the build system that would always bundle up everything using webpack. It should help in your case, but it's very weird that Firefox can't handle requests in such a way.

**Comment by elvirdolic** [comment]
@filipesilva is there any design doc or issue where this change to webpack is explained?. I think a issue/feature where this changes are tracked would avoid a lot of questions regarding webpack.

**Comment by filipesilva** [comment]
@elvirdolic no design doc unfortunately.
