### ISSUE TITLE
improve ng generate component maerdo-contextmenu --module maerdo  to create module if it's not created.

### ISSUE THREAD

**Issue by nblaudez** [angular/angular-cli#11960]
Hi,

I suggest to add a feature that permits to create the module during the component creation if it doesn't exist.

Best regards,

Nicolas

**Comment by clydin** [comment]
The typical workflow is to first create the owner of a component before creating a component itself.  The amount of typing is essentially the same and would not require the extra feature and logic (as well as the necessary testing and long-term maintenance of said feature).

As an example (and assuming cwd is the project root), the generated component will automatically be imported into the nearest module:
```
ng g m moduleA
cd src/app/module-a
ng g c componentA
```
