### ISSUE TITLE
ng build and ng serve fail when library is installed using npm link

### ISSUE THREAD

**Issue by myrddraall** [angular/angular-cli#11962]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 6.1.4
Node: 8.11.3
OS: winfows 10 x64
Angular: 6.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.4
@angular-devkit/build-angular     0.7.4
@angular-devkit/build-optimizer   0.7.4
@angular-devkit/build-webpack     0.7.4
@angular-devkit/core              0.7.4
@angular-devkit/schematics        0.7.4
@angular/cdk                      6.4.6
@angular/cli                      6.1.4
@angular/material                 6.4.6
@angular/pwa                      0.7.4
@ngtools/webpack                  6.1.4
@schematics/angular               0.7.4
@schematics/update                0.7.4
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
```
### Repro steps

* create an angular 6 library project 
* publish the built lib to npm
* link it from the generated dist folder `npm link`
* create a new angular application
* install library from npm
* at this point everything works
* link the lib `npm link MYLIB` 
* in the application `ng build` or `ng serve`
* results in error below

* re-install lib from npm and copt contents to the dist folder so that the linked and installed versions are identical
* re-link lib in application

* error persists even though the only difference is  that the lib is symlinked

 

### The log given by the failure

during compile:
```
WARNING in ng-libs/node_modules/@angular/core/fesm5/core.js
4954:15-36 Critical dependency: the request of a dependency is an expression

WARNING in ng-libs/node_modules/@angular/core/fesm5/core.js
4966:15-102 Critical dependency: the request of a dependency is an expression
```
when running the app

```
Error: inject() must be called from an injection context
    at inject (core.js:1390)
    at BreakpointObserver_Factory (layout.es5.js:264)
    at _callFactory (core.js:8438)
    at _createProviderInstance (core.js:8396)
    at resolveNgModuleDep (core.js:8371)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9064)
    at resolveDep (core.js:9429)
    at createClass (core.js:9301)
    at createDirectiveInstance (core.js:9186)
    at createViewNodes (core.js:10406)

```

in this case it fails to inject BreakpointObserver_Factory (matrials) but if i remove the injection all other contructor injections seem to fail

### Desired functionality

the compilation shouldn't fail if the library is linked

### Mention any other details that might be useful

I've made sure all files in the linked directory are identical to the npm installed version
the library only has peerDeps so there is no node_modules in the library in either case
the only differance seems to be symlinked vs not symlinked

the warnings come from `ng-libs/node_modules/` where ng-libs in the Library Project, i'm not sure why the compiler is looking up angular/core there

**Comment by myrddraall** [comment]
adding:
"paths": {
      "@angular": [
        "node_modules/@angular"
      ],
      "@angular/*": [
        "node_modules/@angular/*"
      ]
    }

to tsconfig.json in the Application project fixes the issue. Not sure if that should be necessary, but at least it allows linking. 

I;m not sure if this is a typescript issue or an issue with the loader that the cli uses

**Comment by alan-agius4** [comment]
The entry below is enough as in reality there are no modules which match `@angular`
`
```ts
{
  "compilerOptions": {
    // ...
    // Note: these paths are relative to `baseUrl` path.
    "paths": {
      "@angular/*": [
        "./node_modules/@angular/*"
      ]
    }
  }
}
```

See this issue for more context: https://github.com/angular/angular-cli/issues/11883

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
