### ISSUE TITLE
Schematic - Tree type is not supported.

### ISSUE THREAD

**Issue by AdamKernig** [angular/angular-cli#11963]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ X ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Output from: `node --version`, `npm --version` and `ng --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra? High Sierra?)

Node v8.11.3
Npm 6.4.0
@angular-devkit/architect          0.7.4
@angular-devkit/build-angular      0.7.4
@angular-devkit/build-ng-packagr   0.7.4
@angular-devkit/build-optimizer    0.7.4
@angular-devkit/build-webpack      0.7.4
@angular-devkit/core               0.7.4
@angular-devkit/schematics         0.7.4
@angular/cli                       6.1.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.4
@schematics/angular                0.7.4
@schematics/update                 0.7.4
ng-packagr                         3.0.6
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.9.2

### Repro steps
1. Create custom schematic with a library
2. publish schematic to npm
3. install in angular project
4. run ng G schematic:library <library name>

### The log given by the failure
$ ng g custom:library testmodule
HostCreateTree {
  _backend: Empty { capabilities: { synchronous: true } },
  _id: -7,
  _ancestry: Set {},
  _dirCache: Map {},
  _record:
   CordHost {
     _cache:
      Map {
        '/' => <Directory>,
        '/__name@dasherize@if-flat__' => <Directory>,
        '/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts' => <File size(654)>,
        '/__name@dasherize@if-flat__/__name@dasherize__.config.ts' => <File size(214)>,
        '/__name@dasherize@if-flat__/__name@dasherize__.module.spec.ts' => <File size(396)>,
        '/__name@dasherize@if-flat__/__name@dasherize__.module.ts' => <File size(1741)> },
     _watchers: Map {},
     _back: SafeReadonlyHost { _delegate: [Object] },
     _filesToCreate:
      Set {
        '/__name@dasherize@if-flat__/__name@dasherize__-routing.module.ts',
        '/__name@dasherize@if-flat__/__name@dasherize__.config.ts',
        '/__name@dasherize@if-flat__/__name@dasherize__.module.spec.ts',
        '/__name@dasherize@if-flat__/__name@dasherize__.module.ts' },
     _filesToRename: Map {},
     _filesToRenameRevert: Map {},
     _filesToDelete: Set {},
     _filesToOverwrite: Set {} },
  _recordSync:
   SyncDelegateHost {
     _delegate:
      CordHost {
        _cache: [Object],
        _watchers: Map {},
        _back: [Object],
        _filesToCreate: [Object],
        _filesToRename: Map {},
        _filesToRenameRevert: Map {},
        _filesToDelete: Set {},
        _filesToOverwrite: Set {} } } }
Tree type is not supported.

### Desired functionality
The library to be created

### Mention any other details that might be useful
This is specifically around the base.js file located in @angular-devkit/schematics/src/rules.base,js line 83

The function filter()

When removing the last throw exception the library will actually build correctly the logged info above is when I console log out the tree being passed in.

If it helps the following information I debugged yesterday,
My custom schematic library consists of a service, module and component.
Running the following works
ng g component
ng g module
ng g service
ng g library
ng g schematic:component
ng g schematic:module
ng g schematic: service

ng g schematic:library <-- does not work

**Comment by alan-agius4** [comment]
Can you please provide which version of angular-cli and sub-packages are you using?

You can use `ng --version`

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by clydin** [comment]
This should be solved in the latest version of the CLI and `@angular-devkit/schematics` (6.1.5/0.7.5).  If the problem persists after upgrading, please open a new issue with further details.
