### ISSUE TITLE
Not possible to create library called `anything-routing`

### ISSUE THREAD

**Issue by pawelkondraciuk** [angular/angular-cli#11961]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: v8.11.3
npm: 6.1.0
ng: 6.1.4
Mac HighSierra

### Repro steps

`ng g lib anything-routing`

### The log given by the failure

`Could not find an NgModule. Use the skip-import option to skip importing in NgModule.`

### Desired functionality

If you treat libraries as Feature Modules and follow [Angular guidelines](https://angular.io/guide/module-types) you should be able to create library called `feature-routing`

**Comment by alan-agius4** [comment]
Note: at the moment anything which is `-routing.module.ts` is reserved for routing.

**Comment by alan-agius4** [comment]
This needs to be discussed further due to style guides. If we should allow non routing modules to be named with `-routing`

//cc @IgorMinar & @robwormald
