### ISSUE TITLE
Enabling ng serve to use https

### ISSUE THREAD

**Issue by jmurphzyo** [angular/angular-cli#1197]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.6
node: 4.4.5
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
N/A

4. The log given by the failure. Normally this include a stack trace and some
   more information.
N/A

5. Mention any other details that might be useful.
> I am really wondering if its possible to have ng serve use HTTPS instead of the standard HTTP. I looked through the src code and couldn't find the location of where you guys setup express. If there is a link or some type of documentation I can follow I would greatly appreciate it!

**Comment by jmurphzyo** [comment]
<<< Nit whit.... I just found it in the serve options.

**Comment by aderbas** [comment]
I try to use `ng serve --ssl true --ssl-key /path/to.key --ssl-cert /path/to.crt` but https not accessible, aways run over http.
