### ISSUE TITLE
snapshot builds have release versions

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#11976]
https://github.com/angular/cli-builds/blob/0bad65e52b514f91bd5bbbf727573a46bce56369/package.json
has
`"version": "6.2.0-beta.3"`
but really it's not that version, it's 6.2.0-somehash

This matters so that if I want to install a new later snapshot, I ought to get a later version per semver, otherwise my package manager will see the version is unchanged and will use the cached package.
Also it's confusing that the CLI will report a released version is being used when I'm actually on a snapshot build.

(Came across this while thinking about how to document for users to try snapshot builds)

**Comment by kyliau** [comment]
Closing this, snapshot builds now contain commit hash.
