### ISSUE TITLE
Create New Project Failing Windows 10

### ISSUE THREAD

**Issue by tomshaw** [angular/angular-cli#11984]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Windows 10

### Repro steps

npm install -g @angular/cli
ng new myproj

### The log given by the failure

npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '...oader":"0.5.x","i18n-'

### Desired functionality

A new project created free from errors.

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by tomshaw** [comment]
Another error after completely reinstalling node.js and deleting the cache

```
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm ERR! Unexpected end of JSON input while parsing near '...{},"dist":{"integrity'
```
