### ISSUE TITLE
Unable to do anything with `ng`

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular-cli#11986]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [x] generate
- [x] add
- [x] update
- [x] lint
- [x] xi18n
- [x] run
- [x] config
- [x] help
- [x] version
- [x] doc
```

### Versions

```text
lazar@lazar:/media/lazar/Elements$ npm list -g --depth 0
/home/lazar/.nvm/versions/node/v10.8.0/lib
├── @angular/cli@6.1.4
├── npm@6.3.0
├── terser@3.8.1
└── wane@0.0.7 -> /home/lazar/wane

npm ERR! peer dep missing: jasmine@^2.4.1, required by jasmine-pretty-html-reporter@0.2.5
lazar@lazar:/media/lazar/Elements$ ng -v
angular-cli[11689]: ../src/node_contextify.cc:637:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8b8210 node::Abort() [angular-cli]
 2: 0x8b82e5  [angular-cli]
 3: 0x8eb237 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [angular-cli]
 4: 0xb4daa8  [angular-cli]
 5: 0xb4fa12 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [angular-cli]
 6: 0x3d74905841bd 
Aborted (core dumped)
lazar@lazar:/media/lazar/Elements$ node -v
v10.8.0
lazar@lazar:/media/lazar/Elements$ npm -v
6.3.0
lazar@lazar:/media/lazar/Elements$ 
```

I'm on Linux, Ubuntu 17.04.

### Repro steps

Uh... Type a command? :thinking: 

### The log given by the failure

I'll repeat it here from the version output:

```text
angular-cli[11689]: ../src/node_contextify.cc:637:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8b8210 node::Abort() [angular-cli]
 2: 0x8b82e5  [angular-cli]
 3: 0x8eb237 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [angular-cli]
 4: 0xb4daa8  [angular-cli]
 5: 0xb4fa12 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [angular-cli]
 6: 0x3d74905841bd 
```

### Desired functionality

Ha!

### Mention any other details that might be useful

I'm pretty sure it used to work at some point. Haven't used Angular in a while and tried to create a new project now :thinking:

**Comment by KevinGruber** [comment]
I have the same problem when using cli Version 6.2.0-beta.3
I get the error serve.json not found on Windows.
With every command i try.

**Comment by rlove** [comment]
@lazarljubenovic 

This most likely is not a bug in the CLI, it most likely caused by how installed the cli.

The CLI has many dependencies and you don't have them installed.
They are listed on the @angular/cli page on the npmjs site.
https://www.npmjs.com/package/@angular/cli
Each of those packages has other dependencies that are not installed.    It's a huge tree and you need to let npm do its work to get those dependencies for you.

1. To resolve you need to uninstall the current version

`npm uninstall -g @angular/cli `

2. The verify you npm cache.

`npm cache verify`

3. Then reinstall allowing all the dependencies to download.

`npm install -g @angular/cli `

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
