### ISSUE TITLE
generated dist folder not working on s3 bucket

### ISSUE THREAD

**Issue by kanishkamehta20** [angular/angular-cli#11983]
I uploaded my dist folder on s3 bucket after adding dist in base href like base href="/folder name/dist/" 
 and next try to access index.html file from s3 bucket, it is working fine but when I refresh the same page, it is giving me error "key does not exist".
I am new to s3 bucket, Please let me know if I am doing any mistake.

Thanks in advance.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
