### ISSUE TITLE
why ng build is not detecting my file chnages whereas ng serve is working file.... Please help me.

### ISSUE THREAD

**Issue by ajaynshd** [angular/angular-cli#11989]
why ng build is not detecting my file chnages whereas ng serve is working file.... Please help me.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by ajaynshd** [comment]
Thank you so much.  ng build --watch works for me.
