### ISSUE TITLE
Angular Universal: Schema validation failed with the following errors:   Data path "" should NOT have additional properties(index).

### ISSUE THREAD

**Issue by scorpion-3** [angular/angular-cli#11982]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node v10.5.0
NPM v6.1.0

Angular CLI: 6.0.8
Node: 10.5.0
OS: win32 x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/platform-server          6.1.4
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

ng serve or npm run build:ssr

### The log given by the failure

Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(index).
npm ERR! code ELIFECYCLE

### Desired functionality

No errors.

### Mention any other details that might be useful

I am trying to implement Angular Universal, I have followed this article 
https://angular.io/guide/universal
I did go through other articles with similar problems, all of them say to downgrade npm package versions to 0.6.3. I currently run the latest cli, hence opening this issue. Please let me know if additional details are needed

**Comment by alan-agius4** [comment]
Can you try if the problem was solved in the lastest `@angular/cli` and `@angular-devkit/<package>` changes? Ie `6.1.4` and `0.7.4` respectively.

Otherwise if the problem persists, Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Can you try to upgrade `@angular-devkit/build-angular` to `0.7.x`? As this issue might have been resolved in another release?

**Comment by scorpion-3** [comment]
after updating to the latest version it got fixed. hence closing this issue. Thanks a lot for the help!

**Comment by pradeeprajr93** [comment]
Create a fresh ng project using latest angular-cli and compare angular.json with your project's angular.json.
You might be able to figure our the issue.
