### ISSUE TITLE
HttpEvent<T>.type is undefined when build for Production using "ng build --prod"

### ISSUE THREAD

**Issue by ictran** [angular/angular-cli#11980]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.1.4
Node: 9.8.0
OS: win32 x64
Angular: 6.1.4

NPM: 5.6.0

### Repro steps

```ts
import { HttpClient, HttpEvent, HttpRequest } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { Media } from './models/media';

@Injectable()
export class MediaService {

  constructor(private http: HttpClient) {
  }

  postFile(file: File): Observable<HttpEvent<Object>> {
    let req = new HttpRequest('POST', `/api/file`, file, { reportProgress: true });
    return this.http.request<Object>(req);
  }
}
```
The following code does not work correctly because x.type is undefined.
```ts
service.postFile(file).subscribe((x: HttpEvent<Object>) => {
  // The line below outputs the appropriate type in integer when building normally,
  // but outputs undefined when building with --prod
  console.log(x.type);
  switch (x.type) {  // x.type is undefined
    case HttpEventType.UploadProgress:
      // do something
      break;
    case HttpEventType.Response:
      // do someting
      break;
  }
});
```
### The log given by the failure

The log indicates the HttpEvent<Object>.type as undefined.

### Desired functionality

Building angular app with --prod should behave the same with normal build.

### Mention any other details that might be useful

The issue occurs in a few earlier minor version too, I think since 6.1.x.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by ictran** [comment]
Please find the minimal repro code here: https://github.com/ictran/angular-cli-issue-11980.

Thank you.

**Comment by alan-agius4** [comment]
You are using an older version of `@angular-devkit/build-optimizer` which in reality you don't need to specify as a dependencies since it is a dependency of `@angular-devkit/build-angular`

Side-note: `Webpack` is also a redundant `devDependencies`.

Remove the `@angular-devkit/build-optimizer`, `package.lock` and re installing the `node_modules` solved the issue in `prod` mode.

**Comment by ictran** [comment]
I removed the `@angular-devkit/build-optimizer` and things are working as expected. Thank you.
