### ISSUE TITLE
@angular-devkit/core v0.7.5 published with broken typescript declarations

### ISSUE THREAD

**Issue by vladimiry** [angular/angular-cli#11992]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
### Versions

node v8.9.4
yarn v1.9.4
typescript v3.0.1

### Repro steps

Just run the build that uses `@angular-devkit/core` in any way.

### The log given by the failure

Error output:
```
ERROR in node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(36,41): error TS2307: Cannot find module '../../../../../../../../../../../Users/hansl/Sources/hansl/angular-cli/packages/angular_devkit/core/src/virtual-fs/path'.
node_modules/@angular-devkit/core/src/virtual-fs/host/test.d.ts(44,33): error TS2307: Cannot find module '../../../../../../../../../../../Users/hansl/Sources/hansl/angular-cli/packages/angular_devkit/core/src/virtual-fs/path'.
```

### Desired functionality

Declarations were not broken with previous v0.7.4 version.

### Mention any other details that might be useful

Here is the workaround, `tsconfig.json`:
```json
{
  "compilerOptions": {
    "skipLibCheck": true
  },
}
```

**Comment by vladimiry** [comment]
cc @hansl

**Comment by alan-agius4** [comment]
I tried to build angular core locally with Bazel and it looks like the types are being generated correctly even with the current version of TypeScript.

example;
```ts
    protected _list(path: Path): import("@angular-devkit/core/src/virtual-fs/path").PathFragment[];
```

**Comment by aaaa0441** [comment]
Hi @hansl, will there be a 0.7.6 release with this fixed? If yes, approximately when will that be?
