### ISSUE TITLE
cli tool still outputs `ember` to the console

### ISSUE THREAD

**Issue by rodyhaddad** [angular/angular-cli#12]
Currently ember-cli does not make use of the `cli.name` parameter we pass it, and so it always outputs `ember` in its help commands for example.

I already started work in my ember-cli fork to fix that.
I should have a PR for ember-cli soon.

I'll update this issue with my progress in the coming days.

**Comment by gdi2290** [comment]
:+1:

**Comment by jimthedev** [comment]
So is this still happening? I was confused when I loaded this up. :D

**Comment by Brocco** [comment]
This has been resolved in PR #157
