### ISSUE TITLE
92% chunk asset optimization UglifyJSPluginUnhandled rejection TypeError: Cannot read property 'sections' of null

### ISSUE THREAD

**Issue by nickwinger** [angular/angular-cli#12009]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

  Linux Ubuntu Server 16.04
node --version 
v8.9.4
npm --version
6.4.0
ng --version
Angular CLI: 6.0.1
Node: 8.9.4
OS: linux x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.1
@angular-devkit/build-angular      0.6.1
@angular-devkit/build-optimizer    0.6.1
@angular-devkit/core               0.6.1
@angular-devkit/schematics         0.6.1
@angular/cdk                       6.3.0
@angular/flex-layout               6.0.0-beta.15
@angular/material                  6.3.0
@angular/material-moment-adapter   6.3.0
@ngtools/webpack                   6.0.1
@schematics/angular                0.6.1
@schematics/update                 0.6.1
rxjs                               6.0.0
typescript                         2.7.2
webpack                            4.6.0

### The log given by the failure

92% chunk asset optimization UglifyJSPluginUnhandled rejection TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/uglifyjs-webpack-plugin/node_modules/source-map/lib/source-map-consumer.js:20:20)
    at UglifyJsPlugin.buildError (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/uglifyjs-webpack-plugin/dist/index.js:116:23)
    at /home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/uglifyjs-webpack-plugin/dist/index.js:275:45
    at Array.forEach (<anonymous>)
    at /home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/uglifyjs-webpack-plugin/dist/index.js:259:19
    at step (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:90:11)
    at done (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/uglifyjs-webpack-plugin/dist/uglify/index.js:99:22)
    at tryCatcher (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/cwi01/jenkins/workspace/KPD_Frontend/Angular Linux/temp/test/KPD2.0/node_modules/bluebird/js/release/promise.js:569:18)

### Desired functionality

no error

### Mention any other details that might be useful

All of a sudden our build hangs after 1 year...
I really tried everything i could find in the net, for example: increasing the memory for the node process.

It has to do with angular.json file option "optimization".
If we set it to false it works...
On our windows machine it is working, so it has something to do with Linux/Ubuntu...
Please anyone, help us with a little suggestion what could be wrong.
In the source-code there was just 2 lines changed and since then the build is not working anymore...
The 2 lines are really simple code changes...
We tried to put : export NODE_OPTIONS=--max_old_space_size=4096
inside the .bashrc but still not working...

Any hints please

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Can you please provide the full output of `ng —version`.

**Comment by nickwinger** [comment]
it's:
Angular CLI: 6.0.1
Node: 8.9.4
OS: linux x64
Angular: 6.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.1
@angular-devkit/build-angular      0.6.1
@angular-devkit/build-optimizer    0.6.1
@angular-devkit/core               0.6.1
@angular-devkit/schematics         0.6.1
@angular/cdk                       6.3.0
@angular/flex-layout               6.0.0-beta.15
@angular/material                  6.3.0
@angular/material-moment-adapter   6.3.0
@ngtools/webpack                   6.0.1
@schematics/angular                0.6.1
@schematics/update                 0.6.1
rxjs                               6.0.0
typescript                         2.7.2
webpack                            4.6.0

**Comment by alan-agius4** [comment]
Can you update to the latest versions and @angular/cli and @angular-devkit
packages and see if the problem persists?

Also if you can create a minimal reproduction of the issue. Can could help
further to pin point the root cause.

**Comment by nickwinger** [comment]
I will try updating.

Reproduction is kinda hard to tell without giving the full source code ;)
However, the issue happend "all of a sudden", so maybe it's really "just" a memory issue, but as i said, we tried to increase it with node...

So maybe you could reproduce it, by giving a VM not much memory and building a bigger Angular-Application ?

These are our files in the output folder:
```
27.08.2018  11:35            44.036 0.0cc053a61f49c53842e5.js
27.08.2018  11:35             2.531 1.630caed8c268d0257961.js
27.08.2018  11:35             5.312 10.415d45d7c37afd45c3e5.js
27.08.2018  11:35             1.128 11.dc0eb4229e56cf727e05.js
27.08.2018  11:35               385 12.f273052281cac910e853.js
27.08.2018  11:35             2.667 13.a4c8bbb46743b57ef4d7.js
27.08.2018  11:35               650 14.277975c12312a3235c16.js
27.08.2018  11:35               587 15.7197de05084e894a18e6.js
27.08.2018  11:35            56.573 16.16693ddd161e6609c12b.js
27.08.2018  11:35           621.536 17.c0ef9c1f04c13e39a571.js
27.08.2018  11:35           613.553 18.5830e4f82f6176c43a76.js
27.08.2018  11:35           235.023 19.6e354e6dee7f0870747b.js
27.08.2018  11:35            44.036 2.9450c2e2c94ac8af8958.js
27.08.2018  11:35           191.011 20.a7f3a370b15c160ea95d.js
27.08.2018  11:35           232.151 21.ce4bfa1cd5c759220143.js
27.08.2018  11:35           355.828 22.744eac65e8f89902aeb1.js
27.08.2018  11:35           162.075 23.4b3f15076dfc29898111.js
27.08.2018  11:35           160.757 24.1ede2189e84a528e6e0f.js
27.08.2018  11:35           361.721 25.ed0be60d4862e594d129.js
27.08.2018  11:35           168.160 26.3f183861b7b19941daf0.js
27.08.2018  11:35           150.370 27.2cac0644e4f49183ad15.js
27.08.2018  11:35           149.485 28.87841cca1d0a4c2a5cf1.js
27.08.2018  11:35           204.997 29.9aa895fff683e80d6745.js
27.08.2018  11:35             2.531 3.ca815128ddecf33f82b8.js
27.08.2018  11:35           432.447 30.5bc2bba90b5da0c189d8.js
27.08.2018  11:35           215.372 31.50a16151c10a0ea61959.js
27.08.2018  11:35           191.595 32.c453cdc1c089b77243a4.js
27.08.2018  11:35            92.132 33.d49bce597f088ea556d1.js
27.08.2018  11:35           106.788 34.690c2c6b72bf651deda5.js
27.08.2018  11:35           126.643 35.7b58d1ece10f7fe95edc.js
27.08.2018  11:35            84.871 36.9e5798928529c041c365.js
27.08.2018  11:35           188.263 37.6711ee651f9ed1281af7.js
27.08.2018  11:35           163.575 38.c5aeb3651135f8fd0f54.js
27.08.2018  11:35           467.025 39.79e18a5f49a58a10161f.js
27.08.2018  11:35            86.930 3rdpartylicenses.txt
27.08.2018  11:35             2.366 4.ae0e951d7572c47d83d0.js
27.08.2018  11:35           633.469 40.f3d56480fca69cb08423.js
27.08.2018  11:35           477.429 41.2f470d5bb57bdf1e947a.js
27.08.2018  11:35           518.127 42.0047a0c8dd72dd3d9be6.js
27.08.2018  11:35           217.993 43.07041b1135fce9552533.js
27.08.2018  11:35           190.136 44.9bd2c951691a1c0de34e.js
27.08.2018  11:35           290.335 45.51c1037bd56b4465780f.js
27.08.2018  11:35            72.514 46.382566cc8f555bdc0df3.js
27.08.2018  11:35            77.386 47.1e7acfe4429eb9765f2a.js
27.08.2018  11:35         2.053.675 48.7c0ecc7c4ae252318086.js
27.08.2018  11:35           362.276 49.6a4e2edceda4c9f8ab8e.js
27.08.2018  11:35             1.411 5.af199f69388e80637ea3.js
27.08.2018  11:35           220.755 50.85d0c174bde8eccab021.js
27.08.2018  11:35           320.520 51.0d1bbb52607dd1b33900.js
27.08.2018  11:35           164.268 52.da6e3d2d37d26f6ab1ea.js
27.08.2018  11:35           139.193 53.b41db68d8d9f78721bb8.js
27.08.2018  11:35           262.367 54.b9485aac1e357fe4fe4b.js
27.08.2018  11:35           148.893 55.0f3700d9e8a1eb63e7ed.js
27.08.2018  11:35           160.849 56.bafb3f6b4e66edcd5b02.js
27.08.2018  11:35           293.269 57.98f8f20549e457a0b58f.js
27.08.2018  11:35           322.968 58.6c11ddb8ccdf86a03e7b.js
27.08.2018  11:35           155.166 59.285f26a7fdf18f922f91.js
27.08.2018  11:35            66.820 6.6a6b5f318996cadf70f3.js
27.08.2018  11:35           134.771 60.af2a73f3f4ac96558e03.js
27.08.2018  11:35           237.570 61.c36fff1193b09687f0ac.js
27.08.2018  11:35           348.869 62.de5bcbc6c4f58ef9c6df.js
27.08.2018  11:35           321.780 63.fc99402273df20c6e095.js
27.08.2018  11:35           152.880 64.da5fe4ba56ca684c1a5e.js
27.08.2018  11:35           184.846 65.244b3530bb6889649d20.js
27.08.2018  11:35           207.692 66.a7e840ae0e0ced191db7.js
27.08.2018  11:35           450.533 67.8e0de9d34ac1718dc360.js
27.08.2018  11:35           173.568 68.e7b65e77840c8f48a972.js
27.08.2018  11:35         2.082.528 69.835700fa25aae0fa2d8f.js
27.08.2018  11:35             5.404 7.8b8b6d4798651c550de5.js
27.08.2018  11:35            59.252 70.18586f2b4d1f28e7f689.js
27.08.2018  11:35           336.396 71.6d0c805ed83aa3f55129.js
27.08.2018  11:35           738.653 72.d5577ae445393c327e85.js
27.08.2018  11:35            95.980 73.e55fdfdab805de6515c3.js
27.08.2018  11:35            57.336 74.5748eb7a0b64e86a2f8e.js
27.08.2018  11:35           271.834 75.912d355f8a85b5d912ac.js
27.08.2018  11:35            87.570 76.134faf77fd79ac5a2f9d.js
27.08.2018  11:35            59.652 77.c8d9619ad92ec43fb590.js
27.08.2018  11:35           265.781 78.b8546b6a3976d617b5b9.js
27.08.2018  11:35           165.086 79.95d0a6ab40f34b038a57.js
27.08.2018  11:35               503 8.6d175a008b55524f4f9f.js
27.08.2018  11:35           391.015 80.e8cea38454311299d8c6.js
27.08.2018  11:35           314.598 81.ed0722445c67f2370204.js
27.08.2018  11:35            68.150 82.7e4b60d154a2f32e7f42.js
27.08.2018  11:35            66.370 83.a3cb81f3a33d1c763bf8.js
27.08.2018  11:35            49.547 84.178f40588e5b388b6758.js
27.08.2018  11:35               545 9.099ce12099224e2a16ac.js
27.08.2018  11:35    <DIR>          assets
27.08.2018  11:35           132.960 bpmn.27b5b1904737f806dcb1.svg
27.08.2018  11:35            41.724 bpmn.609860a7b5830bab8c78.eot
27.08.2018  11:35           123.499 common.7e4495fb70fd6f7c9437.js
27.08.2018  11:35           112.492 favicon.ico
27.08.2018  11:35             3.507 index.html
27.08.2018  11:35            15.344 KFOmCnqEu92Fr1Mu4mxK.5d4aeb4e5f5ef754e307.woff2
27.08.2018  11:35            15.500 KFOmCnqEu92Fr1Mu72xKOzY.e3836d1191745d29137b.woff2
27.08.2018  11:35            11.936 KFOmCnqEu92Fr1Mu7GxKOzY.15d8ede0a816bc7a9838.woff2
27.08.2018  11:35        10.177.349 main.07b53fca3d18f3f9ba1d.js
27.08.2018  11:35            49.028 material.d3a4b3bfc67f733e8bb2.woff2
27.08.2018  11:35           470.265 polyfills.9fcaf92b40a51b8abc8f.js
27.08.2018  11:35           114.624 RobotoMono-Regular.a48ac41620cd818c5020.ttf
27.08.2018  11:35            10.365 runtime.54296ad5774a928c2f91.js
27.08.2018  11:35           347.220 styles.53e93a8a1a3d979b5676.css
```

**Comment by nickwinger** [comment]
It's crazy i have found the problem, it was this line of javascript code:
        stringFilter = stringFilter.replace(/(?<=[\d])(,)(?=[\d])/g, '.');
This regex is not supported yet in Javascript.
In Chrome it works, it does not output any Typescript errors or build errors...
However it makes the uglifier (angular.json optimization: true) crash ...

crazy...
