### ISSUE TITLE
Inline css styles are not minified. Styles with multi-line comments are not minified

### ISSUE THREAD

**Issue by thienedits** [angular/angular-cli#12006]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Npm: 5.5.1

Angular CLI: 1.7.4
Node: 9.1.0
OS: win32 x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

@angular/cdk: 5.1.1
@angular/cli: 1.7.4
@angular/material-moment-adapter: 5.1.1
@angular/material: 5.1.1
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.1
webpack: 3.11.0
```

### Repro steps

Running `ng serve --prod`. Inline styles coming from the Component styles property are not minified. Whereas, styles from the Component styleUrls property are properly minified.

Image 1
![inline-css](https://user-images.githubusercontent.com/2762906/44617931-04a35400-a821-11e8-828a-739ff19e7562.PNG)

Image 2
![inline-css-2](https://user-images.githubusercontent.com/2762906/44617947-7d0a1500-a821-11e8-9f4c-a910bc2b0bc2.PNG)

### Desired functionality

The inline styles are minified with spaces and comments removed.

**Comment by alan-agius4** [comment]
At the moment this is working as expected. When styles or templates are inlined these cannot be minified, since the minification is being done via `webpack` which can only run on 'external' styles and templates.
