### ISSUE TITLE
Config for default generate path

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#12018]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X ] feature request
```

### Desired functionality

`ng g m dashboard`
`ng g c myComponent --module=dashboard`
It would be nice if there was a setting in angular.json for when generating anything there could be a prefix path.. in the example about I would like to have the component generated in the "components" folder in the dashboardModule

if the command is executed from the root and no module is given, user should be prompted with available modules

**Comment by alan-agius4** [comment]
Hi @mackelito, thanks for this feature request. This currently out of the scope of the Angular CLI. You can create/extend the schematics to achieve the above mentioned behaviour.

Let's revisit this in the future, if we see a bigger demand for this feature.

Thanks.
