### ISSUE TITLE
lazy loading chunks not built if bootstrap is not in main.ts file

### ISSUE THREAD

**Issue by DevVersion** [angular/angular-cli#12025]
Currently if people want to use lazy loading within Angular CLI projects and their `bootstrap` code is not placed inside of the `$PROJECT_ROOT/main.ts` file, the chunks for the lazy-loading module are not being generated.

This leads to JIT runtime errors that indicate that the lazy module couldn't be found.

```ts
core.js:1673 ERROR Error: Uncaught (in promise): Error: Cannot find module 'lazy/slider.module'
Error: Cannot find module 'lazy/slider.module'
    at $_lazy_route_resource lazy namespace object:5
```

Moving the `boostrap` call to the `main.ts` file fixes this issue (credits to @filipesilva for this finding)

--

It would be good to have some warning or note that implicates that lazy modules won't be detected if the `bootstrap` call is placed somewhere else.

Issue demonstration: https://github.com/DevVersion/lazy-load-test-cli

cc. @filipesilva

**Comment by santiago-elustondo** [comment]
Is there a workaround? I need to call `bootstrapModule()` in a different file.

**Comment by mascarenhas** [comment]
You can get around this by adding an `entryModule` key in the application's `angularCompilerOptions` object in the `tsconfig.json` file pointing to your main module, like this: `"entryModule": "./app/app.module#AppModule"`.
