### ISSUE TITLE
[Question/Documenation] Need more information about the usage of barrels

### ISSUE THREAD

**Issue by bastienJS** [angular/angular-cli#1202]
In the system.config.ts there is:

```
const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };
});
```

I could nowhere find information about:

```
1.) What exactly is a barrel
2.) Why gets each barrel a object { main: 'index' } assigned
```

Would you please explain the infrastructure you setup in your documentation.

**Comment by hcsalis** [comment]
Angular Glossary is a useful resource for Angular 2 vocabulary. You can find barrel definition here: 

[https://angular.io/docs/ts/latest/glossary.html#!#B]

Regarding index files, barrel definition says:

> The Angular scoped packages each have a barrel named index.

Hope this helps.

**Comment by bastienJS** [comment]
@hcsalis Thanks so is there a way not to use barrels? I can`t find anything useful in them personally. Now there is another layer of complexity just for exporting types from files? Thats cumbersome in my opinion.

**Comment by slmyers** [comment]
`ng g <type>` will result in barrel registration of the object. 

[generate results in barrel registration](https://github.com/angular/angular-cli/search?utf8=%E2%9C%93&q=barrel)
["barrel spec"](https://github.com/angular/angular-cli/blob/67b577deb3bbee27228ec0b559bca6ba90603dcc/tests/acceptance/barrel-management.spec.js)

**Comment by filipesilva** [comment]
@bastienJS barrels - `index.ts` files were generated by the `route` (now disabled) and `component` generators automatically, as well as automatically updating `system-config.ts` to include these.

You don't have to use barrels, but since it is a best practice included in the [style guide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#04-10) the CLI helps out in it.
