### ISSUE TITLE
Update docs with examples

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#12029]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] feature request
```

### Command (mark with an `x`)
```
- [ x ] config
```

### Desired functionality

Show how we can update build configurations using the terminal
something like:
ng config architect.@angular-devkit/build-angular:dev-server.namedChunks true

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, this issue is a duplicate of #11795. Please subscribe to that issue for future updates.
