### ISSUE TITLE
There is an error in browser/schema.d.ts in the @angular-devkit/build-angular@0.7.5 distribution.

### ISSUE THREAD

**Issue by iwe7** [angular/angular-cli#12020]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```
@angular-devkit/build-angular/src/browser/schema.d.ts
```ts
 fileReplacements: FileReplacements[];
```
### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, this issue is a duplicate of #11992. Please subscribe to that issue for future updates.

**Comment by alan-agius4** [comment]
Please fill in the template with more details. Thanks

**Comment by iwe7** [comment]
fileReplacements: FileReplacements[]; // i think should is FileReplacement[]
