### ISSUE TITLE
MomentJS code is included in main.js instead of chunk.js, when using MomentDateAdapter in lazy loading module from a library.

### ISSUE THREAD

**Issue by Pradeep12191** [angular/angular-cli#12034]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v8.11.2
npm: 5.6.0
Angular CLI: 6.0.8, 
OS: Windows 10, win32 x64
Angular: 6.1.4

### Repro steps

"@angular/material-moment-adapter": "^6.4.6",
"@angular/material": "^6.4.6"

1. create a new angular cli app - `ng new service-app`
2. create a library inside service-app - `ng generate library service-lib.`
3. Inside library create a module 'ServiceLibModule' and provide `MomentDateAdapter` for Material `DateAdapter`.

```
import { NgModule } from '@angular/core';
import { ServiceLibComponent } from './service-lib.component';
import { ServiceLibService } from './service-lib.service';
import { DateAdapter } from '@angular/material';
import { MomentDateAdapter } from '@angular/material-moment-adapter';

@NgModule({
  imports: [
  ],
  declarations: [ServiceLibComponent],
  exports: [ServiceLibComponent],
  providers: [
    ServiceLibService,
    {
      provide: DateAdapter,
      useClass: MomentDateAdapter
    }
  ]
})
export class ServiceLibModule { }
```
4. In service-app create module for lazy loading as below and import the `ServiceLibModule` from `service-lib`(library) which uses MomentDateAdapter.

```
import { NgModule } from "@angular/core";
import { ServiceLibModule } from "service-lib";
import { RouterModule } from "@angular/router";
import { LazyComponent } from "./lazy.component";

@NgModule({
    imports: [
        ServiceLibModule,
        RouterModule.forChild([
            {path: '', component: LazyComponent}
        ])
    ],
    declarations:[LazyComponent]
})
export class LazyModule {

}
```
When I build the library and application, moment code is included in 0.chunk.js which is fine.

![image](https://user-images.githubusercontent.com/10145706/44793249-71bd3d80-abc3-11e8-8879-44fa33d7070a.png)
In the above screenshot, chunk.js size is 343kb, since moment code is included, which is expected behavior, and it is working fine.

**Unexpected behavior:**
But when I create another one service in service-lib(service does not include any moment related code) `CustomService` and use it in `app.module.ts`, and when I do build, momentjs code goes to main.js. But I expect moment code stays in 0.chunk.js since I am using moment used module (`ServiceLibModule`) only in Lazy loading module not in appModule.

```
import { Injectable } from '@angular/core';

@Injectable()
export class CustomService{
    constructor(){
        console.log('service from library is used in app')
    }
}
```

provide the service in appModule

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';

import { AppComponent } from './app.component';
import { CustomService } from 'service-lib';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot([
      {path: 'lazy', loadChildren:'./lazy/lazy.module#LazyModule'}
    ])
  ],
  providers: [CustomService],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
here we can see after including the `CustomService` from library, and build the app, moment code moves to main.js(main.js file size increased) instead of 0.chunk.js(file size reduced), which is unexpected behavior.
![image](https://user-images.githubusercontent.com/10145706/44793436-df696980-abc3-11e8-971b-9d9c041285f4.png).

### Desired functionality

We would like to keep the main.js file as small as possible. And we are using MomentDateAdapter only in LazyLoad Module via library, but this increases main.js file, since entire moment code is included in main.js instead of 0.chunk.js.

This might be a behavior with `provider with useValue or useClass`.

 Please provide suggestion.

**Comment by filipesilva** [comment]
Thank you for the detailed repro! I think this happens because libraries get compiled into a single big file, and that file cannot be split across chunks. So as soon as something gets on the main chunk, the whole file goes there. 

There might be something we can do with scope analysis (https://github.com/vincentdchan/webpack-deep-scope-analysis-plugin comes to mind). At the moment there isn't anything you can do on your side to affect this behaviour I think.

**Comment by alan-agius4** [comment]
Closing as this is not currently actionable from our end. Webpack doesn't support code-motion.
