### ISSUE TITLE
Provide an option to extend Webpack with webpackbar

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular-cli#12041]
It would be nice to have an option so that the implicit invocation of Webpack can be extended with the Webpack plugin webpackbar. See https://github.com/nuxt/webpackbar.

**Comment by alan-agius4** [comment]
Hi, this is outside of the scope of the CLI. 

If you'd like to add this you can use https://github.com/manfredsteyer/ngx-build-plus
