### ISSUE TITLE
Preventing unloading of modules on lazy loading other modules

### ISSUE THREAD

**Issue by adityarw** [angular/angular-cli#12040]
Is there any way to prevent unloading of modules on lazy loading other modules??
(means earlier views(of modules) must be there along with currently loading views(of modules))

[if anyone thinking about i can use oultlet's but in that also it will unload the modules and lazy load the modules in respective Outlet, i don't need this. i need both should be there..]

i haven't found anything like this in angular documents. 

@angular-cli team,

if it is not yet implemented, then this will be a great feature.

please let me know if any..

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
