### ISSUE TITLE
Cannot read property 'appendChild' of undefined at lstr.js:26

### ISSUE THREAD

**Issue by peter-snr** [angular/angular-cli#12042]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version 8.9.3
npm --version  6.4.0
ng --version 6.0.8

### Repro steps

ng create somecomponent
cd somecomponent
npm run start

### The log given by the failure

Error in google web tools console:
core.js:3123 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
lstr.js:26 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at lstr.js:26
(anonymous) @ lstr.js:26

### Desired functionality

No errors when creating a new project.
[localhost-1535624327980.log](https://github.com/angular/angular-cli/files/2335752/localhost-1535624327980.log)

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by peter-snr** [comment]
**GitHub repo created.**

https://github.com/peter-snr/repro-app

**I also got this warning from GitHub.**

_

> We found potential security vulnerabilities in your dependencies.
> Some of the dependencies defined in these manifest files have known security vulnerabilities and should be updated:
> 
> package-lock.json 2 vulnerabilities found

_

**Comment by peter-snr** [comment]
@filipesilva I tried incognito mode with Chrome and it is fine, I also checked with Firefox and also fine.  I guess you are correct, it is most likely related to a plugin.  Thank you for taking a look.
