### ISSUE TITLE
rxjs verison v6.3.0 in angular/cli having problem in ng serve

### ISSUE THREAD

**Issue by lalitmee** [angular/angular-cli#12052]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc
```

### Versions

node --version v8.11.4
npm --version v5.6.0
ng --version v6.1.2

### Repro steps

Remove your old `@angular/cli` and install again you will find that the `rxjs` version is `v6.3.0`.

### The log given by the failure

On `ng serve` my application is not loading and it is giving this error
```
ERROR Error: Uncaught (in promise): TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_2__.Observable.of is not a function
```

### Desired functionality

I think the `rxjs` version `v6.2.x` will be fine for me.

### Mention any other details that might be useful

I also checked the latest release commits of @angular/cli and there I saw a commit which is having this issue described there.
See this https://github.com/angular/angular-cli/commit/7e63dd791b67ad49de4b0b2f55ecc386e4cad20e

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, as you pointed out this issue has already been solved with this commit https://github.com/angular/angular-cli/commit/7e63dd791b67ad49de4b0b2f55ecc386e4cad20e Thus, I am going to close it issue.
