### ISSUE TITLE
NG generate command messing up the declarations array of the concerned module

### ISSUE THREAD

**Issue by trichetriche** [angular/angular-cli#12054]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report
```

### Command (mark with an `x`)
```
- [ X ] generate
```
### Versions

````
λ node --version
v8.11.3
````
````
λ npm --version
5.6.0
````
````
Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.3.0
@angular/cli                       6.0.8
@angular/flex-layout               6.0.0-beta.16
@angular/material                  6.3.0
@angular/material-moment-adapter   6.3.0
@ngtools/webpack                   6.0.8
@schematics/angular                0.6.8
@schematics/update                 0.6.8
rxjs                               6.2.1
typescript                         2.7.2
webpack                            4.8.3
````
### Repro steps

- generate a component into a module
- The component is appended to the list of `declarations`, but it splits the previous one. For instance,
````
declarations:[AComponent],
λ ng g c b-component
declarations: [Acompone, BComponentnt]
````

Here is a visual representation, made just now. 

![ng-cli-g-issue](https://user-images.githubusercontent.com/7789922/44900005-bf40c400-ad03-11e8-8279-7fdc9417b967.gif)

### The log given by the failure

No logs because no failure. The failure happens at build time, since the components cannot be found. 

### Desired functionality

That it works

### Mention any other details that might be useful
The project being industrial, I am not allowed to share it publicly. But if a person from the Angular team can't reproduce the issue, I imagine I can send a zipped version to him (if it is project-related)

**Comment by alan-agius4** [comment]
If it is not happening in the latest version. Most likely it was solved in a newer release.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
