### ISSUE TITLE
ng update @angular/cli fails silently when local node_modules folder doesn't exists

### ISSUE THREAD

**Issue by raboud** [angular/angular-cli#12058]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Node:  v8.11.2
npm: 6.4.0
ng

    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.1.5
Node: 8.11.2
OS: win32 x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.5
@angular-devkit/core         0.7.5
@angular-devkit/schematics   0.7.5
@angular/cli                 6.1.5
@schematics/angular          0.7.5
@schematics/update           0.7.5
rxjs                         6.3.1
typescript                   2.9.2

Windows 10

### Repro steps

1. Get from github https://github.com/RandREng/BootAngular
2. npm install -g @angular/cli
3. npm install @angular/cli
4. ng update @angular/cli
5, ng update @angular/core

.angular-cli.json still exists...no angular.json

the above steps worked on on repository, then has failed on the next 2

**Comment by juanpjacob** [comment]
Have the same issue with this config also:
```
Angular CLI: 6.1.5
Node: 8.11.2
OS: linux x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.5
@angular-devkit/core         0.7.5
@angular-devkit/schematics   0.7.5
@angular/cli                 6.1.5
@schematics/angular          0.7.5
@schematics/update           0.7.5
rxjs                         5.5.12
typescript                   2.6.2
```
The `ng update @angular/cli` command does nothing, I still have the `.angular.json` file.

**Comment by alan-agius4** [comment]
Your repo needs to have `node_modules` installed prior of doing `ng update @angular/cli`

**Comment by raboud** [comment]
have done an npm install as step 1.a and it still does not create a angular.json

**Comment by alan-agius4** [comment]
@raboud unfortunately i cannot look into this further as the reproduction provided is no longer valid.
