### ISSUE TITLE
Unable to build using --prod flag. Indeterminable error returned during UglifyJs process.

### ISSUE THREAD

**Issue by det-jscott116** [angular/angular-cli#12064]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: 8.11.1
Npm: 5.6.0
Angular Cli: 6.1.5

### Repro steps

Building with ``--prod``, e.g. ``ng build --prod`` returns an error:

```
ERROR in main.55704d1fa620b76d62c5.js from UglifyJs
Unexpected token: punc ()) [main.55704d1fa620b76d62c5.js:75494,2]
```

As per #5741 I attempted to troubleshoot this issue by adding the ``--source-map`` flag, e.g. ``ng build --prod --source-map`` and the build is successful, with no errors reported. As the output has been Uglified I am unable to find the line number that is being referenced to determine the cause of this problem.

Why is it that the build would be successful with the ``--source-map`` flag added? Is this normal behaviour?

### The log given by the failure

As above.

### Desired functionality

Build should be successful.

### Mention any other details that might be useful

Seems to be related to #5741 but I am not sure how identify the problem to resolve this issue.

Any help will be greatly appreciated!

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by filipesilva** [comment]
Closing as no repro has been provided.
