### ISSUE TITLE
Cache busting issue

### ISSUE THREAD

**Issue by samuelrajsams** [angular/angular-cli#12065]
Can u help me how to solve the cache busting issue. ngbuild --prod is not solved the cache busting issue

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
