### ISSUE TITLE
Cannot read property '0' of null

### ISSUE THREAD

**Issue by CarlosMoralesSal** [angular/angular-cli#12073]
Trying to create a component with ng generate component <namecomponent> I have this error:

    `Cannot read property '0' of null  `   

I have uninstall node and angular cli and I have started from the begining but nothing occurs, so I don't know what is the problem.

I have this version:

```
     Angular CLI: 6.1.5
Node: 8.11.4
OS: win32 x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.0
typescript                        2.7.2
webpack                           4.9.2
```
What is the problem?. Thanks so much

**Comment by alan-agius4** [comment]
Can you provide the full stacktrace please? Also have you tried to update the CLi and devkit packages to the latest versions?

**Comment by CarlosMoralesSal** [comment]
I just have these two lines so it's an error without much information and it's fustrating, I have updated everything and nothing, is there any way to extract more information about the ng generate process?. Thanks

**Comment by alan-agius4** [comment]
Does the problem still persists when updating to the newest versions of the packages?

**Comment by CarlosMoralesSal** [comment]
Yes here it is:
 
    `{
        "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
         "version": 1,
         "newProjectRoot": "projects",
         "projects": {
         "aprendiendo-angular": {
        "root": "",
        "sourceRoot": "src",
        "projectType": "application",
        "prefix": "app",
        "schematics": {},
        "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/aprendiendo-angular",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "aprendiendo-angular:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "aprendiendo-angular:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "aprendiendo-angular:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "aprendiendo-angular-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "aprendiendo-angular:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "aprendiendo-angular:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
   },
   "defaultProject": "aprendiendo-angular"
 }`

**Comment by CarlosMoralesSal** [comment]
Any  hint about this problem?. Thanks so much

**Comment by jasonwismer** [comment]
I too have this issue.  This does not happen with a new project, but only when I place an old project into it by pasting over the src, and pasting in that projects package.json and reinstalling.  This seems to imply my package.json is the culprit.  Here it is:

[package.txt](https://github.com/angular/angular-cli/files/2362475/package.txt)

**Comment by alan-agius4** [comment]
Hi, I think the root cause here was that one of that the `ngModule` metadata was probably missing leading withspaces. Ie: Not formatting.
