### ISSUE TITLE
Need option to add behavior to devServer in angular.json

### ISSUE THREAD

**Issue by jlowcs** [angular/angular-cli#12078]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
angular-cli 6.1.5
angular-devkit 0.7.5

### Desired functionality
It would be most useful to be able to add behavior to the dev server. This could be done by adding an option allowing to specify the value of the `before` and `after` options of webpack-dev-server.

Using only `proxyConfig` is limiting because it doesn't allow for asynchronous behavior, or for rewriting the response body.

### Mention any other details that might be useful
We are currently migrating for our custom toolstack to angular-cli, as it has majorly evolved since we bootstrapped our apps, but are hitting a roadblock because of this.

I'd be willing to create a pull request with the changes. I've already experimented with an additional option, and it works quite well:

```typescript
  private _buildServerConfig(
    root: Path,
    projectRoot: Path,
    options: DevServerBuilderOptions,
    browserOptions: BrowserBuilderSchema,
  ) {
    // ...

    if (options.devServerConfig) {
      this._addDevServerConfig(systemRoot, options, config);
    }

    return config;
  }

  // ...

  private _addDevServerConfig(
    root: string,
    options: DevServerBuilderOptions,
    config: WebpackDevServer.Configuration,
  ) {
    let devServerConfig = {};
    const devServerPath = path.resolve(root, options.devServerConfig as string);
    if (existsSync(devServerPath)) {
      devServerConfig = require(devServerPath);
    } else {
      const message = 'Dev server config file ' + devServerPath + ' does not exist.';
      throw new Error(message);
    }
    Object.assign(config, devServerConfig);
  }
```

And in `schema.json`
```json
    "devServerConfig": {
      "type": "string",
      "description": "Dev server configuration file."
    },
```

Usage:
`angular.json`:
```json
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "main:build",
            "devServerConfig": "./dev-server.conf.js"
          },
        },
```
`dev-server.conf.js`:
```js
module.exports = {
	before: (app) => {
		app.get('/hello', (req, res, next) => {
			res.send('hello!!');
		});
	}
}
```

https://github.com/jlowcs/angular-cli/commits/feat-devServerConfig-option

**Comment by dsnoeck** [comment]
Hi @alan-agius4,
I have the same requirement. Do you know if this can be implemented with a custom builder ? Have you some more code to share ?

**Comment by dsnoeck** [comment]
Found the way. Follow this blog post: http://opensourceforgeeks.blogspot.com/2018/12/how-to-customize-build-configuration.html and use the devServer.before config: https://webpack.js.org/configuration/dev-server/#devserverbefore

**Comment by jlowcs** [comment]
Really? I don't remember it being possible with an older version of the cli. Maybe that changed. I'll try it next week.

**Comment by kochax** [comment]
This actually goes for all webpack config. It should be allowed to pass any piece of config trough options, like in the solution @dsnoeck mentioned.

**Comment by zuzusik** [comment]
This is the functionality we also could benefit from

**Comment by kyliau** [comment]
This is currently out of scope for CLI because we plan to revamp the `ng serve` workflow to make it more modular.

For now, you could consider taking one of two approaches:
1. Use a custom Webpack [dev-server](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#Custom-webpack-dev-server)
2. Write your own builder that invokes `ng build` in watch mode, then serve the file any way you want

In the future, our approach will be more aligned with the second suggestion above, where we would decouple the Webpack dev server from `ng serve` and focus on incremental building. Users could then roll their own dev server solution.
