### ISSUE TITLE
:host-context special selector fails build when used in Sass file

### ISSUE THREAD

**Issue by chrishandorf** [angular/angular-cli#12070]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

$ node --version
v8.11.4
$ npm --version
5.6.0
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.5
Node: 8.11.4
OS: darwin x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.1
typescript                        2.7.2
webpack                           4.9.2

### Repro steps

The :host-context Special Selector is documented here:
https://angular.io/guide/component-styles#host-context

It is as simple as this to demonstrate the problem:

$ ng new —style=sass mynewproj
$ cd mynewproj
$ echo ":host-context(.myclass1) .myclass2" >> src/app/app.component.sass
$ echo "  color: red" >> src/app/app.component.sass
$ cat src/app/app.component.sass 
:host-context(.myclass1) .myclass2
  color: red
$ ng serve

### The log given by the failure

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2018-09-03T18:11:36.109Z
Hash: fd8f7012853b1b62f00b
Time: 4270ms
chunk {main} main.js, main.js.map (main) 10.9 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 15.9 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.27 MB [initial] [rendered]

ERROR in ./src/app/app.component.sass
Module build failed: 
:host-context(.myclass1) .myclass2
^
      Invalid CSS after "h": expected 1 selector or at-rule, was "host-context(.mycla"
      in /mynewproj/src/app/app.component.sass (line 1, column 1)
ℹ ｢wdm｣: Failed to compile.

### Desired functionality

The :host-context selector works fine when using a CSS file, but when using SASS there is a build failure.
I'm working around it temporarily by using both Sass and CSS in the component.  Yuck.

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.sass', './login.component.css'],
})

Why does the :host-context special selector not work in a Sass file?

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the  `libsass` project or file an issue on their issue tracker.
