### ISSUE TITLE
I am not able use ng cli command on Bash.

### ISSUE THREAD

**Issue by mohitidol** [angular/angular-cli#12076]
I did do the uninstall and install of the angular/cli.
I am using Bash, when I do npm start. My application does run

I wanted to create the new component using ng g c compname. But this gives me error as command not found.

Need help urgently.
![error](https://user-images.githubusercontent.com/23230112/45022106-fe974980-b050-11e8-8b04-39b96dc3e395.PNG)

**Comment by alan-agius4** [comment]
Please follow https://github.com/angular/angular-cli/wiki

**Comment by mohitidol** [comment]
Did the same still same issue
