### ISSUE TITLE
ng build --prod error : FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by csquareEductaion** [angular/angular-cli#12074]
13% building modules 26/35 modules 9 active ...\css\roboto\sass\roboto-fontface.scss(node:1940) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56 parseQuery() will be replaced with getOptions() in the next major version of loader 67% building modules 775/806 modules 31 active ...eExportInvoice.component.ngfactory.ts <--- Last few GCs --->

595802 ms: Mark-sweep 1261.6 (1434.6) -> 1258.4 (1434.6) MB, 2055.2 / 0.0 ms [allocation failure] [GC in old space requested]. 597996 ms: Mark-sweep 1258.4 (1434.6) -> 1258.1 (1434.6) MB, 2193.3 / 0.0 ms [allocation failure] [GC in old space requested]. 600240 ms: Mark-sweep 1258.1 (1434.6) -> 1269.0 (1404.6) MB, 2243.5 / 0.0 ms [last resort gc]. 602404 ms: Mark-sweep 1269.0 (1404.6) -> 1281.0 (1404.6) MB, 2163.6 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000003298D93FA99 2: encodeLastRecordedSourceMapSpan [E:\Projects\Diamond\NewDiamondUI\diamond\node_modules\typescript\lib\typescript.js:~61639] [pc=000003435ECE10DE] (this=0000019C03836CE1 ) 3: emitPos [E:\Projects\Diamond\NewDiamondUI\diamond\node_modules\typescript\lib\typescript.js:61704] [pc=000003435EBA0306] (this=0000019C03836CE1 ,pos=345540) 4: emitNodeWi...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by alan-agius4** [comment]
Closing as it doesn't follow the template
