### ISSUE TITLE
Bootstrap and Jquery not found during project compilation with ng serve

### ISSUE THREAD

**Issue by Clearbryan** [angular/angular-cli#12080]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI 6.1.5
Windows 7
Node 8.11.4
npm 5.6.0

### Repro steps
I generated a project using the cli with the following command
ng new myapp
cd myapp
npm install bootstrap jquery
In the angular.json,  styles["../node_modules/bootstrap/dist/css/bootstrap.min.css"] and scripts["../node_modules/jquery/dist/jquery.min.js", "../node_modules/bootstrap/dist/js/bootstrap.min.js",]

### The log given by the failure

C:\Users\A\Desktop\Data\SMSAPP>ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-09-04T09:27:31.325Z
Hash: 384e28c2c61257bb02c1
Time: 132394ms
chunk {main} main.js, main.js.map (main) 10.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 227 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.27 MB [initial] [rendered]

ERROR in multi ../node_modules/bootstrap/dist/css/bootstrap.css ./src/styles.css
Module not found: Error: Can't resolve 'C:\Users\A\Desktop\Data\node_modules\bootstrap\dist\css\bootstrap.css' in 'C:\Users\A\Desktop\Data\SMSAPP'
 i ?wdm?: Failed to compile.

### Desired functionality
This should allow bootstrap css styles and javascripts to be loaded and run. It works on my other machine with angular version 1.7.4

**Comment by alan-agius4** [comment]
From your error it looks like the issue is the `../` infront of `node_modules`.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Clearbryan** [comment]
Thank you apparently the issue had to do with my path to the bootstrap files
