### ISSUE TITLE
How to use AngularCompilerPlugin to bundle stand-alone modules?

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12089]
_From @pavel-agarkov on June 2, 2018 19:5_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
node: v6.11.0
npm: 3.10.10
webpack: 3.11.0
angular: 5.2.10
ngtools/webpack: 1.10.2
Windows 10

### Repro steps
Take any simple angular module with some components and use it as additional entry point in webpack like this:
```js
const example = {
    context: __dirname,
    resolve: { extensions: ['.js', '.ts'] },
    output: { filename: '[name].js', publicPath: '/dist/' },
    module: {
        rules: [{
            test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
            include: /ClientApp/,
            loader: '@ngtools/webpack'
        }]
    },
    entry: { 'schemes-module-client': './ClientApp/schemes/schemes.client-module.ts' },
    output: {
        path: path.join(__dirname, clientBundleOutputDir),
        libraryTarget: 'commonjs'
    },
    plugins: [
        new webpack.DllReferencePlugin({
            context: __dirname,
            manifest: require('./wwwroot/dist/vendor-manifest.json')
        })
    ].concat([
        new AngularCompilerPlugin({
            mainPath: path.join(__dirname, 'ClientApp/schemes/schemes.client-module.ts'),
            tsConfigPath: './tsconfig.json',
            entryModule: path.join(__dirname, 'ClientApp/schemes/schemes.client-module#SchemesClientModule'),
            exclude: ['./**/*.server.ts']
        })])
}
```

### The log given by the failure
The following code is produced by the `AngularCompilerPlugin` but it includes only a declaration of `SchemesClientModule`:
```js
!function(e,t){for(var n in t)e[n]=t[n]}(exports,function(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var n={};return t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{configurable:!1,enumerable:!0,get:r})},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="/dist/",t(t.s=0)}([function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),n.d(t,"SchemesClientModule",function(){return r});var r=function(){function e(){}return e}();t.default=r}]));
```

### Desired functionality
Correct bundle should be produced

### Mention any other details that might be useful
It is used to work for all module types with old version of `AotPlugin`.  

It works with a new version of `AngularCompilerPlugin` for root modules (for which `platformBrowserDynamic().bootstrapModule` was called).  

It stopped working with stand-alone modules after update to `AngularCompilerPlugin` - produced bundle includes only code from file that was specified as `entryModule` and does not include any components or services from the module.  

Similar issue has been mentioned on [stackoverflow](https://stackoverflow.com/questions/47746938/ngtools-webpack-angularcompilerplugin-configuration-for-angular-5-ionic-3-lib) but with no luck.

_Copied from original issue: angular/devkit#1003_

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
