### ISSUE TITLE
pwa with angular 6 does not work

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12099]
_From @vikceo on May 16, 2018 21:10_

### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x] devkit
- [ ] schematics
```

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#926_

**Comment by alexeagle** [comment]
_From @vikceo on May 16, 2018 21:10_

complete details: https://stackoverflow.com/questions/50361196/angular-6-pwa-does-not-work?noredirect=1#comment87741844_50361196

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
