### ISSUE TITLE
Running externalSchematics in unit tests

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12101]
_From @maciejtreder on May 15, 2018 11:58_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Area
```
- [ x ] devkit
- [ ] schematics
```

### Versions

<pre>
@angular-devkit/core 0.6.1
node: v8.11.1
npm: 5.8.0
</pre>

### Desired functionality
For purpose of creating external libraries, to be used with ```ng-add``` I would like to be able to test my schematics within raw/fresh project created by CLI. In other words, I would like to run externalSchematic from `@angular/schematics`

_Copied from original issue: angular/devkit#916_

**Comment by alan-agius4** [comment]
Hi @maciejtreder, 

You can take a look at https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/migrations/update-9/schematic-options_spec.ts to see how you can run external schematic on an empty tree.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
