### ISSUE TITLE
ServerBuilder: merge additional webpack configs (pakage @angular-devkit/build-angular)

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12106]
_From @enten on May 8, 2018 9:58_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

```shell
$ node --version
v8.9.4
$ npm --version
5.6.0
```

#### angular.json

```diff
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ng-universal": {
      "root": "",
      "projectType": "application",
      "prefix": "app",
      "architect": {
        // ...
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/app/server",
            "main": "src/app/ngmodule.ts",
            "tsConfig": "src/tsconfig.server.json",
+           "webpackMergeFiles": [
+             "webpack.server.config.ts"
+           ]
          },
          "configurations": {
            "production": {
            }
          }
        },
        // ...
      }
    }
  }
}
```

#### webpack.server.config.ts

```ts
module.exports = (wco, webpackConfig) => {
  return {
    name: 'server'
  };
};
```

### Desired functionality

**I would like to customize webpack server target configuration** wihout ejecting the CLI or extending the [ServerBuilder](https://github.com/angular/devkit/blob/v6.0.0/packages/angular_devkit/build_angular/src/server/index.ts) (with architect).

I suggest a new ServerBuilder's option - named `webpackMergeFiles` for example - to set a list of additional webpack config files merged with [webpack-merge](https://github.com/survivejs/webpack-merge).

**If you think this feature is interesting: it can be useful for the browser target too. Sould I open another issue for that?**

```json
"webpackMergeFiles": {
  "description": "List of additional webpack config files merged with webpack-merge.",
    "type": "array",
    "items": {
    "type": "string"
  },
  "default": []
}
```

### Mention any other details that might be useful

Note: the patch below can only be apply after the commit [598c5389](https://github.com/angular/devkit/commit/598c5389081932babc23a2ae9e568e60caa7fffc).

Patch:

* Add `webpackMergeFiles` property into _packages/angular_devkit/build_angular/src/server/schema.json_ ;
* Add `webpackMergeFiles` property into _packages/angular_devkit/build_angular/src/server/schema.d.ts_ ;
* Add `webpackMergeFiles` property into _packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts_ ;
* Update `ServerBuilder.buildWebpackConfig()` to resolve and merge additional webpack configs.

```diff
diff --git a/packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts b/packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
index 26c060e..37e2e89 100644
--- a/packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
+++ b/packages/angular_devkit/build_angular/src/angular-cli-files/models/build-options.ts
@@ -56,6 +56,7 @@ export interface BuildOptions {
   styles: ExtraEntryPoint[];
   stylePreprocessorOptions?: { includePaths: string[] };
   lazyModules: string[];
+  webpackMergeFiles: string[];
   platform?: 'browser' | 'server';
 }
 
diff --git a/packages/angular_devkit/build_angular/src/server/index.ts b/packages/angular_devkit/build_angular/src/server/index.ts
index fa369b1..0b80423 100644
--- a/packages/angular_devkit/build_angular/src/server/index.ts
+++ b/packages/angular_devkit/build_angular/src/server/index.ts
@@ -155,7 +155,24 @@ export class ServerBuilder implements Builder<BuildWebpackServerSchema> {
       webpackConfigs.push(typescriptConfigPartial);
     }
 
-    return webpackMerge(webpackConfigs);
+    let webpackConfig = webpackMerge(webpackConfigs);
+
+    if (wco.buildOptions.webpackMergeFiles) {
+      wco.buildOptions.webpackMergeFiles.forEach(webpackMergeFile => {
+        const webpackMergePath = getSystemPath(normalize(resolve(root, normalize(webpackMergeFile))));
+
+        let webpackMergeConfig = require(webpackMergePath);
+        if (typeof webpackMergeConfig === 'function') {
+          webpackMergeConfig = webpackMergeConfig(wco, webpackConfig);
+        }
+
+        if (webpackMergeConfig !== webpackConfig) {
+          webpackConfig = webpackMerge(webpackConfig, webpackMergeConfig);
+        }
+      });
+    }
+
+    return webpackConfig;
   }
 
   private _deleteOutputDir(root: Path, outputPath: Path, host: virtualFs.Host) {
diff --git a/packages/angular_devkit/build_angular/src/server/schema.d.ts b/packages/angular_devkit/build_angular/src/server/schema.d.ts
index 12ec739..a49bbbb 100644
--- a/packages/angular_devkit/build_angular/src/server/schema.d.ts
+++ b/packages/angular_devkit/build_angular/src/server/schema.d.ts
@@ -113,6 +113,10 @@ export interface BuildWebpackServerSchema {
    * Use file name for lazy loaded chunks.
    */
   namedChunks?: boolean;
+  /**
+   * List of additional webpack config files merged with webpack-merge.
+   */
+  webpackMergeFiles?: string[];
 }
 
 /**
diff --git a/packages/angular_devkit/build_angular/src/server/schema.json b/packages/angular_devkit/build_angular/src/server/schema.json
index e3533f3..1f28d59 100644
--- a/packages/angular_devkit/build_angular/src/server/schema.json
+++ b/packages/angular_devkit/build_angular/src/server/schema.json
@@ -152,6 +152,14 @@
         "type": "string"
       },
       "default": []
+    },
+    "webpackMergeFiles": {
+      "description": "List of additional webpack config files merged with webpack-merge.",
+      "type": "array",
+      "items": {
+        "type": "string"
+      },
+      "default": []
     }
   },
   "additionalProperties": false,
```

_Copied from original issue: angular/devkit#864_

**Comment by alexeagle** [comment]
_From @actra-gschuster on May 8, 2018 15:14_

Added a PR today: https://github.com/angular/devkit/pull/868 ;-)

**Comment by alexeagle** [comment]
_From @enten on May 8, 2018 15:24_

@actra-gschuster Awesome! It would be nicer if we can set array of webpack configs (to compose them like component' styles with `NgModule.styleUrls`).

**Comment by alexeagle** [comment]
_From @actra-gschuster on May 8, 2018 16:10_

@enten Added the option to specify an array of scripts that will be run.
Each script receives the config object and the build target (as specified in angular.json) and has to return the new config object.

```
module.exports = function(config, target) {
	console.log('Modify this config:', target, config);
        
	// config.module.rules.push({test: /\.abc$/, use: [{loader: 'abc-loader'}]});
	
	return config;
};
```

**Comment by alexeagle** [comment]
_From @enten on May 8, 2018 16:35_

@actra-gschuster Sorry I confused you (with my comparison between what I'm expect an `NgModule.styleUrls`). I would like to do something like that:

```diff
"server": {
  "builder": "@angular-devkit/build-angular:server",
  "options": {
    "outputPath": "dist/app/server",
    "main": "src/app/ngmodule.ts",
    "tsConfig": "src/tsconfig.server.json",
+   "webpackMergeFiles": [
+     "webpack/externals-all-deps.config.ts"
+   ]
  },
  "configurations": {
    "production": {
+     "webpackMergeFiles": [
+       "webpack/externals-none-deps.config.ts",
+       "webpack/custom-minify-plugin.config.ts"
+     ]
    }
  }
},
```

In that way **we can easily compose partial webpack configs across projects and targets and check customization by environment only with open the `angular.json` file** (no need to open other files and read code).

**Comment by alexeagle** [comment]
_From @actra-gschuster on May 8, 2018 17:14_

That's what my change is for.
Inside the script you can use webpack-merge or any other tools to modify the config.

**Comment by alexeagle** [comment]
_From @enten on May 8, 2018 18:17_

@actra-gschuster I'm sorry I missed to read your last commit. Awesome! Thanks for your work.

It's may be useful to pass the [`wco: WebpackConfigOptions`](https://github.com/actra-development-oss/devkit/blob/f9f2605df9be2012e810f1360063c8a1dadad718/packages/angular_devkit/build_angular/src/karma/index.ts#L130) like angular-cli do with [webpack config models](https://github.com/angular/devkit/tree/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs) when the custom config is a function.

In addition, in the case of a custom config as a function, we can optimize the handle of the value returned:
* if nothing is returned: do nothing ;
* if something is returned but it equals the [current `mergedConfig`](https://github.com/actra-development-oss/devkit/blob/f9f2605df9be2012e810f1360063c8a1dadad718/packages/angular_devkit/build_angular/src/karma/index.ts#L147): do nothing ;
* if something different that the [current `mergedConfig`](https://github.com/actra-development-oss/devkit/blob/f9f2605df9be2012e810f1360063c8a1dadad718/packages/angular_devkit/build_angular/src/karma/index.ts#L147) is returned: merge it with webpack-merge.

**Comment by alexeagle** [comment]
_From @actra-gschuster on May 9, 2018 5:31_

I think it's better to let the user handle merging as it's more flexible, one may want to remove some settings that would be re-added when the builder does the merging.

**Comment by alan-agius4** [comment]
Hi, if your use case require such I'd recommend you to look at [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus.). You can customize your build using it.

Closing this. If you think we're missing something and it's essential for the CLI to support this out of the box (i.e., you have use cases that we have thought about), please open a new issue.+
