### ISSUE TITLE
Universal schema uses hardcoded src value instead of angular.json value

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12104]
_From @GJordan904 on May 11, 2018 7:5_

### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x ] schematics
```

### Versions
node 10.1.0
npm 6.0.1
angular 6.0.1
angular-devkit 0.6.1

### Repro steps
Start a project with the CLI and change srcRoot to something other than src, I will use browser. Then run `ng generate universal --client-project ng-universal-test --app-dir browser`

### The log given by the failure
Module file (/src/app/app.module.ts) not found

### Desired functionality
Instead of hardcoding src, use the value from angular.json, or --app-dir unless that is for something else.

### Mention any other details that might be useful
Nothing more, pretty simple.

###
###
Well it looks like the `--source-dir` option no longer exists for ng-new and as a result, nothing ran after it checks for it either. Oh well, my oversight. I would like to be able to change the src directory name though as I like to make a browser folder for my client app and a server folder for my express app.

_Copied from original issue: angular/devkit#894_

**Comment by Pringels** [comment]
+1 please address this
