### ISSUE TITLE
findModule function looks in wrong folders for Modules on Mac OS High Sierra

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12114]
_From @anakinjay on April 26, 2018 16:1_

### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ X ] schematics
```

### Versions

ajimac:app slayjay$ node --version
v8.11.1
ajimac:app slayjay$ npm --version
5.6.0

macOS High Sierra

### Repro steps

- create a new project using:
- ng new projectName
- cd into the project folder
- attempt to generate a new component using:
- ng g c componentName

### The log given by the failure

Could not find an NgModule. Use the skip-import option to skip importing in NgModule.

### Desired functionality

new component generated

### Mention any other details that might be useful

I've been able to track this bug down to the function findModule in find-module.js.  On line 52, dir.subfiles *always* returns the file listing for what is in the main root project folder (angular.json, package.json etc...) . It does not look inside any subdirectories, so obviously it won't find any module files.

Even if I change directory into the /src/app folder where the module file is and attempt to generate the component from there, the dir.subfiles function still only returns files from the main project root.

```javascript
function findModule(host, generateDir) {
    let dir = host.getDir('/' + generateDir);
    const moduleRe = /\.module\.ts$/;
    const routingModuleRe = /-routing\.module\.ts/;
    while (dir) {
        const matches = dir.subfiles.filter(p => moduleRe.test(p) && !routingModuleRe.test(p));
        if (matches.length == 1) {
            return core_1.join(dir.path, matches[0]);
        }
        else if (matches.length > 1) {
            throw new Error('More than one module matches. Use skip-import option to skip importing '
                + 'the component into the closest module.');
        }
        dir = dir.parent;
    }
    throw new Error('Could not find an NgModule. Use the skip-import '
        + 'option to skip importing in NgModule.');
}
exports.findModule = findModule;
```

_Copied from original issue: angular/devkit#787_

**Comment by alexeagle** [comment]
_From @anakinjay on April 26, 2018 16:33_

Possibly / probably related:

in filesystem.js in the definition of the subfiles function if I add in this code:
```javascript
   this._host.list(this._path).filter(name => {
            console.log(name);
            return false;
        });
```

I get this error:
```
ENOENT: no such file or directory, scandir '/Users/slayjay/Sites/repos/angular-starter-kit/users/slayjay/sites/repos/angular-starter-kit/src/app/asdf'
```

looks like it's doubling up the file path for some reason.

**Comment by alexeagle** [comment]
_From @anakinjay on April 26, 2018 16:52_

Another weird bit I've noticed...  2 directories down (so /users/slayjay/sites in my case if my project is in /Users/slayjay/Sites/repos/angular-starter-kit) . it creates a .angular.json file with just: {"version":1} in it.

If I delete the file, and run ng g c componentName again, that file is immediately recreated.

**Comment by alexeagle** [comment]
_From @anakinjay on April 26, 2018 18:46_

**Progress:**

If in get subfiles() in filesystem.js   I overwrite the _path property with the correct subpath(/src/app) everything works fine.  Still trying to track down with _path is being improperly set.

```javascript
  get subfiles() {
    this._path = '/src/app';
```

**Comment by alexeagle** [comment]
_From @anakinjay on April 26, 2018 20:26_

I think I've reached the end of how far I can debug, starting to get really deep into the weeds into parts of angular cli i don't understand.

I made a gif here showing the whole process, please let me know if there's anything else I can do to help, or any more information I can provide.

https://i.imgur.com/fuTizgm.gifv

**Comment by alexeagle** [comment]
_From @anakinjay on April 27, 2018 12:50_

Another potential clue:

```
ng g c testingcomp --module='/src/app/app.module.ts'
```
returns the error: Specified module does not exist.

It's like it's not picking up the current working directory on mac.  Knowing that, I tried specifying the directory like this, and this DOES indeed work. 

```
ng g c testingcomp --path="/src/app"
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
