### ISSUE TITLE
Schematics plugins for IDEs

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12115]
_From @FriOne on April 26, 2018 11:11_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Desired functionality
I am waiting the next release of angular and hope there will be docs for schematics. It would be convenient to have a plugin(s) to use schematics from UI. E.g. Webstorm. For example nestjs already implemented own schematics but we can use it only from command line. Is there some work in this direction? Or it will be made by community only? Does schematics have a (easy) way for IDEs to integrate schematics as a plugin?
[Jetbrains issue](https://youtrack.jetbrains.com/issue/WEB-32531)

_Copied from original issue: angular/devkit#785_

**Comment by alan-agius4** [comment]
Hi, thanks for opening the issue, however at the moment this is currently outside of the scope of the CLI.

There are already a couple of community driven plugins.

VS Code:
https://marketplace.visualstudio.com/items?itemName=cyrilletuzi.angular-schematics
https://marketplace.visualstudio.com/items?itemName=nrwl.angular-console

Webstorm
https://plugins.jetbrains.com/plugin/10768-angular-schematic-generator
