### ISSUE TITLE
Library Builder Output Optimizations

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12110]
_From @clydin on May 2, 2018 19:42_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Desired functionality

The library builder should support running safe build optimizer passes on built libraries as a final production build action.

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#839_

**Comment by alan-agius4** [comment]
While this is still relevant, there are multiple places where we need to do such transformations.

1. ng-packagr for community/workspace libraries
2. Angular ng_package for 1st party packages or packages that are using the bazel rule to build their library in APF format. (@angular/, @ngrx, @nguniversal etc..)

Most likely it makes sense that these transformations are consolidated and consumed by all the tools.

**Comment by alan-agius4** [comment]
Closing this for now as it's not planned. Potentially such optimisations can be done when during a re-write of ng-packagr.
