### ISSUE TITLE
assets option for @angular-devkit/build-ng-packagr:build 

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12124]
_From @gatimus on April 11, 2018 19:15_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions
npm --version 5.8.0
node --version v9.8.0

### Desired functionality
property or option like "assets" to allow copying static files to npm package output like `README.md`

_Copied from original issue: angular/devkit#680_

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/11317
