### ISSUE TITLE
AngularFire2 - Firestore - LLRBEmptyNode is not a constructor

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12127]
_From @patrickmichalina on April 4, 2018 0:31_

### Summary
I get a catastrophic error when importing the `AngularFirestoreModule`. This does NOT happen when using the `AngularFireDatabaseModule`.

## Version info
```
    "@angular-devkit/build-optimizer": "^0.4.6",
    "@angular/animations": "6.0.0-rc.1",
    "@angular/cdk": "5.1.1",
    "@angular/common": "6.0.0-rc.1",
    "@angular/compiler": "6.0.0-rc.1",
    "@angular/compiler-cli": "6.0.0-rc.1",
    "@angular/core": "6.0.0-rc.1",
    "@angular/forms": "6.0.0-rc.1",
    "@angular/http": "6.0.0-rc.1",
    "@angular/material": "5.1.1",
    "@angular/platform-browser": "6.0.0-rc.1",
    "@angular/platform-browser-dynamic": "6.0.0-rc.1",
    "@angular/platform-server": "6.0.0-rc.1",
    "@angular/router": "6.0.0-rc.1",
    "@angular/service-worker": "6.0.0-rc.1",
    "@firebase/app": "^0.1.10",
    "@firebase/auth-types": "^0.2.0",
    "@firebase/database": "^0.2.1",
    "@firebase/database-types": "^0.2.0",
    "@firebase/firestore": "^0.3.7",
    "@firebase/firestore-types": "^0.2.2",
    "@firebase/messaging-types": "^0.1.2",
    "@firebase/storage-types": "^0.1.2",
    "@nguniversal/common": "5.0.0-beta.8",
    "@nguniversal/express-engine": "5.0.0-beta.8",
    "angularfire2": "^5.0.0-rc.6.0-next",
```

### What is the expected behavior?
AOT compiles nicely

### Actual behavior
App fails at runtime

<img width="1554" alt="screen shot 2018-04-01 at 7 37 44 pm" src="https://user-images.githubusercontent.com/6701211/38179098-9e17af6e-35e4-11e8-88cf-30dda2b76e94.png">

<img width="862" alt="screen shot 2018-04-01 at 7 37 59 pm" src="https://user-images.githubusercontent.com/6701211/38179101-a6436eda-35e4-11e8-8306-224e50bdd659.png">

_Copied from original issue: angular/devkit#618_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
