### ISSUE TITLE
@ngtools/webpack failed to compile

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12129]
_From @vincent-cm on April 2, 2018 15:31_

Error when compile

non-AoT
`ERROR in Must have a source file to refactor`
AoT
`ERROR in Could not resolve module @angular/core`

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Versions

node v9.10.1
npm 5.6.0

### Repro steps

`npm i @ngtools/webpack@6.0.0-beta.8 --save `

### The log given by the failure

npm start or npm run start:aot

### Desired functionality

should compile

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#602_

**Comment by alan-agius4** [comment]
I am sorry but the errors reported in the reproduction seems to be related to configuration and not causing by the `devkit` / `cli` packages. As even the `IDE` is showing some errors, considering that the reproduction provide is relatively large it's hard for us to pinpoint the actual cause of such issues.

![image](https://user-images.githubusercontent.com/17563226/46019453-5cf99a00-c0dc-11e8-9afb-9be9eb5df2d7.png)
