### ISSUE TITLE
Rename file(a=>b), update content of b , throws error b doesn't exist

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12133]
_From @sebawita on March 16, 2018 18:47_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
```
node: v6.9.1
npm: v5.7.1

"@angular-devkit/core": "^0.4.5",
"@angular-devkit/schematics": "^0.4.5",
"@schematics/angular": "^0.4.5",
```

### Repro steps
Run Schematic the below Schematic, it will throw an error when trying to call `tree.beginUpdate`, claiming that the file doesn't exist.

```
export function rename(options: any): Rule {
  return (tree: Tree, _context: SchematicContext) => {
    tree.rename('test.txt', 'test.txt.old');
    const buffer = tree.read('test.txt.old'); // <-- this is fine

    const recorder = tree.beginUpdate('test.txt.old'); // <-- this is not fine
    recorder.insertLeft(0, 'new text');
    tree.commitUpdate(recorder);

    return tree;
  };
}
```

When reversing the order of actions - update then rename. This will result in two files:
- FileA - will contain the updated text
- FileB - will contain the original text from FileA
To test, run this Schematic
```
export function rename(options: any): Rule {
  return (tree: Tree, _context: SchematicContext) => {
    const fileA = 'test.txt';
    const fileB = 'test.txt.new';

    const recorder = tree.beginUpdate(fileA); // <-- updates the content of test.txt
    recorder.insertLeft(0, 'new text');
    tree.commitUpdate(recorder);

    tree.rename(fileA, fileB); // <-- creates a second file (fileB) with the original contents of fileA
    const buffer = tree.read(fileB); 

    return tree;
  };
}
```

### The log given by the failure
In the first case I get an error like this:
`error! test.txt.old does not exist..`

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#516_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
