### ISSUE TITLE
bug(schematics): component changeDetectionStrategy alias -c clashes with --collection alias shorthand

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12132]
_From @Hotell on March 17, 2018 18:29_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [] devkit
- [x] schematics
```

### Versions
Node: 8.10
Npm: 5.7.1
OS: High Sierra

### Repro steps

When creating custom schematic and extending from current `@schematics/angular@0.4.6` for custom `component` blueprint, alias for `changeDetection` is `c`, which clashes with `--collection` shorthand alias 

```sh
yarn ng g myc helloWorld -c=OnPush -d -c @martin_hotell/schematics
```

- myc : is custom blueprint for **component** which uses the same collection metadata as current `@schematic/angular`

### The log given by the failure
![image](https://user-images.githubusercontent.com/1223799/37558740-060b60fc-2a19-11e8-82af-797a886d55ce.png)

### Desired functionality

There are multiple typos fro aliases names within component blueprint
- changeDetection : https://github.com/angular/devkit/blob/master/packages/schematics/angular/component/schema.json#L55
- viewEncapsulation: https://github.com/angular/devkit/blob/master/packages/schematics/angular/component/schema.json#L48
- inlineTemlate: https://github.com/angular/devkit/blob/master/packages/schematics/angular/component/schema.json#L42
- inlineStyle:
https://github.com/angular/devkit/blob/master/packages/schematics/angular/component/schema.json#L36

before, the aliases were different
- `cd` not `c` 
- `it` not `t`
- `is` not `s`
- `ve` not `v`

I can send PR, if you want. 

Thanks

_Copied from original issue: angular/devkit#520_

**Comment by clydin** [comment]
The `--collection`/`-c` option no longer exists on the generate command.
