### ISSUE TITLE
appShell fails if the app already has a RouterModule

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12138]
_From @cexbrayat on November 24, 2017 23:18_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Repro steps
Generate a new app `ng new hello`.

Edit `app.module.ts` to add a `RouterModule`:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { AppComponent } from './app.component';

const routes: Routes = [];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(routes)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
Add `router-outlet` in index.html.
Run unviersal: ` ng g universal server-app`
Run appShell: `ng g app-shell shell --universal-app serverA-app`

### The log given by the failure
```
Error: Chunk cannot be found.
Chunk cannot be found.
```

_Copied from original issue: angular/devkit#297_

**Comment by alan-agius4** [comment]
Fixed by https://github.com/angular/angular-cli/pull/11603
