### ISSUE TITLE
bug: unable to execute custom schematic application blueprint

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12131]
_From @Hotell on March 18, 2018 20:3_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
Angular CLI: 1.7.3
Node: 8.10.0
OS: darwin x64

![image](https://user-images.githubusercontent.com/1223799/37642976-66503264-2c1f-11e8-8e12-736b6849224b.png)

### Repro steps
```
npm i -g @martin_hotell/schematics typescript @angular/cli @angular-devkit/schematics-cli

ng new better-cli --material --collection @martin_hotell/schematics -d
```

### The log given by the failure
![image](https://user-images.githubusercontent.com/1223799/37570394-9adacfca-2aef-11e8-8093-7bf201facf82.png)
![image](https://user-images.githubusercontent.com/1223799/37570441-2f09b940-2af0-11e8-85f7-5bc12ac0addd.png)

Locally installed project schematics works:
![image](https://user-images.githubusercontent.com/1223799/37570502-c8600a0e-2af0-11e8-92e8-a00ecb2242f9.png)

And yes my schematics have been generated via @schematic/schematic 
https://github.com/Hotell/ng-cli-schematics/blob/master/package.json ✌️

### Desired functionality
being able to generate new app via custom schematic

### Mention any other details that might be useful
There were issues created before which were closed for unknown reasons :) not cool at all 👀

Related:

- https://github.com/angular/devkit/issues/351
- https://github.com/angular/devkit/issues/322

_Copied from original issue: angular/devkit#528_

**Comment by clydin** [comment]
The referenced package targets 1.x of the Angular CLI.  Unfortunately, the schematics are not supported on newer versions of the CLI (currently 9.x).  Angular CLI 1.x is also no longer supported.  As a result this issue cannot be further investigated.  If anyone is still encountering problems with the latest version of the CLI, please open a new issue with updated information.
