### ISSUE TITLE
chain() RuleFactory doesn't respect order

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12142]
_From @douglasward on March 2, 2018 7:42_

### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x ] schematics
```

### Versions
```
node: v6.9.4
npm: v5.6.0
linux: ubuntu 16.04
```

### Repro steps

Following Hans' example in his blog post to add license text to newly generated components: https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2

Or set up a simple schematic using the `chain()` rule. eg:
```ts
export function myComponent(options: any): Rule {
  return chain([
    (tree: Tree, _context: SchematicContext) => {
      console.log('I will execute before externalSchematic()')
      return tree;
    },
    externalSchematic('@schematics/angular', 'component', options),
    (tree: Tree, _context: SchematicContext) => {
      console.log('I will execute before externalSchematic()')
      return tree;
    }
  ]);
}
```
No matter what order you use in the `chain()` array, the `externalSchematic()` function executes last. This means it is impossible to change the newly generated component after it is created as you can only execute code before it is created.

### Desired functionality

I would expect that the `chain()` respects the order in the array. Any functions coming before 
 `externalSchematic()` would be executed beforehand any any functions coming after it will be executed afterwards

_Copied from original issue: angular/devkit#475_

**Comment by roychoo** [comment]
Hi,

actually, it does respect the order.
I ***think*** the physical creation or update is always done at the last step.
but the buffer(tree) is still executing in the correct order.

thats why the log messages are appearing first, then the physical creation/update is next

**Comment by clydin** [comment]
Closing as correctly answered by @roychoo.  Thank you.
