### ISSUE TITLE
Rename file, then create a new file with the same as the renamed file fails.

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12140]
_From @sebawita on March 9, 2018 15:32_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
```
    "@angular-devkit/core": "^0.4.5",
    "@angular-devkit/schematics": "^0.4.5",
    "@schematics/angular": "^0.4.5",
```
### Repro steps
Run a schematic with a file called `test.txt`
```
tree.rename('test.txt', 'other.txt');
tree.create('test.txt', 'content');
```
This will fail saying `error! test.txt already exists.`

Also the same happens, when I use apply url, that generates a previously renamed file.
```
tree.rename('test.txt', 'other.txt');
apply(url('./_files'), ...)
```

### The log given by the failure
`error! filename already exists.`

### Desired functionality
It should be possible to create a file that was previously deleted or renamed.

### Mention any other details that might be useful

_Copied from original issue: angular/devkit#491_

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
