### ISSUE TITLE
schematics-cli on linux fails to create a new semantics project

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12144]
_From @douglasward on February 24, 2018 17:54_

### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [ x] schematics
```

### Versions
```
node: v6.9.4
npm: v5.6.0
linux: ubuntu 16.04
```

### Repro steps

run:
```
$ schematics  blank --name=my-component
```

### The log given by the failure
```bash
CREATE /my-component/README.md (635 bytes)
CREATE /my-component/.gitignore (191 bytes)
CREATE /my-component/package.json (535 bytes)
CREATE /my-component/src/collection.json (231 bytes)
CREATE /my-component/tsconfig.json (631 bytes)
CREATE /my-component/src/my-component/index.ts (317 bytes)
CREATE /my-component/src/my-component/index_spec.ts (474 bytes)
npm ERR! file /tmp/my-component/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected token , in JSON at position 3 while parsing near '123,10,32,32,34,110,97,...'
npm ERR! File: /tmp/my-component/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

### Desired functionality
The blank schematics folder should be created with the expected content.

### Mention any other details that might be useful

All of the files in the folder include contents such as `123,10,32,32,34,110,97`.

Downgrading to `~0.3.2` fixes the problem.

Might be the same problem as https://github.com/angular/devkit/issues/453, if so I apologise, and please feel free to close.

_Copied from original issue: angular/devkit#464_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
