### ISSUE TITLE
For polyfill es7/reflect, it should be mentioned that tests are not run in AOT mode

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12148]
_From @fredgate on January 25, 2018 11:7_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions
angular CLI 1.6.4

### Repro steps
Use AOT to serve and build the application.

In the `polyfills.ts` file, comment the `import 'core-js/es7/reflect';` line as it is mentioned that :
```
/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
// import 'core-js/es7/reflect';
```

Then execute unit tests. Tests where a provider (the system under test, or any other class) has a injected dependency will fail with a message indicating that it can resolve all parameter for the class. It is not because its dependencies are not registered in the testing module, but because it can not read metadata of the class and so determine the dependant classes.

### The log given by the failure
```
Error: Can't resolve all parameters for MyService: (?). in http://localhost:9876/_karma_webpack_/vendor.bundle.js (line 20595)
syntaxError@http://localhost:9876/_karma_webpack_/vendor.bundle.js:20595:34
../../../compiler/esm5/compiler.js/CompileMetadataResolver.prototype._getDependenciesMetadata@http://localhost:9876/_karma_webpack_/vendor.bundle.js:35802:35
```

### Desired functionality
The `polyfills.ts` should mention for the _es7/reflect_ polyfill that unit tests are not run in AOT mode.

_Copied from original issue: angular/devkit#408_

**Comment by alexeagle** [comment]
_From @fredgate on January 25, 2018 11:9_

People are having problems like : angular/angular#21440

**Comment by alexeagle** [comment]
_From @fredgate on January 25, 2018 11:10_

I can propose a pull request.

**Comment by moniuch** [comment]
Any more info on that? I am currently having a problem as described above `Can't resolve all parameters for BsModalService: (?, ?)` however commenting the es7/reflect in or out doesn't seem to matter. I am using Jest 23.6, Angular 6.1.0

**Comment by leonardochaia** [comment]
@moniuch in my scenario [I'm using the ReflectiveInjector](https://github.com/leonardochaia/timoneer/blob/d7a0f34d7832b6200f545285627e7831b4bd431c/src/app/jobs/job-runner.service.ts#L32) and [custom decorators](https://github.com/leonardochaia/timoneer/blob/d7a0f34d7832b6200f545285627e7831b4bd431c/src/app/jobs/job.decorator.ts#L5) which requires the Reflect API. My prod builds got broken after upgrading to Angular 7

I managed to fix it by [adding the polyfill back](https://github.com/leonardochaia/timoneer/commit/263ef6ca896ea8676be24b294c128559fe238449)(that was removed by the CLI when I did the update)

Note that the CLI entirely removes the line (instead of commenting it)
```typescript
/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect'; 
```

As a side note, a similar line remains commented, which confused me at first:
```typescript
/** IE10 and IE11 requires the following for the Reflect API. */
// import 'core-js/es6/reflect';
```

(Note the `es6` vs `es7`) 
adding/removing the `es6` line had no effect for me, apparently I need the `es7` one.

**Comment by devoto13** [comment]
@leonardochaia This is because of https://github.com/angular/angular-cli/commit/30f8352ca2b3cccd72f5fcff8e09a543f9c70a8d. If you need this polyfill for other reasons than JIT, than adding it back manually is the right course of action.

**Comment by moniuch** [comment]
@devoto13 As I mentioned, there is no effect of having that line in or out
![screenshot 2018-11-06 at 10 20 39](https://user-images.githubusercontent.com/681956/48054480-a6dea100-e1ad-11e8-82ba-69eff874bb71.png)

**Comment by ravioshankar** [comment]
> Getting similar issue on ubuntu 
> CLI version is
>  "@angular/cli": "~7.3.8",
>  "@angular-devkit/build-angular": "~0.13.8",

ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/openworkshop/git/prithvi/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models'
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/openworkshop/git/prithvi/src'
ℹ ｢wdm｣: Failed to compile.

**Comment by owenmecham** [comment]
@ravioshankar which version of core-js do you have specified in your package.json?

**Comment by penfold** [comment]
@ravioshankar It doesn't work with core-js 3. Revert to 2.6.5 fixed the same error for me..

`npm install core-js@2.6.5 --save`

**Comment by silkentrance** [comment]
@penfold this package depends on core-js@3.0.1. Why is it not possible for projects depending on this package to use newer versions of core-js, too?

**Comment by clydin** [comment]
Angular CLI 8.0+ automatically handles JIT related polyfills; manually including them is no longer necessary.
