### ISSUE TITLE
Issue with collection cache name when using FileSystemEngineHost

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12156]
_From @sasxa on November 19, 2017 14:40_

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ ] devkit
- [x] schematics
```

### Versions

    "@angular-devkit/schematics": "0.0.36",

### Repro steps

[`FileSystemEngineHost`](https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/tools/file-system-engine-host.ts#L28-L40) cannot resolve `collection.json` in subfolder. For example, with `@nrwl/schematics` it's in `@nrwl/schematics/src/collection.json`. I extended it and used this;

```typescript
import { sync as globSync } from 'glob';

export class MyEngineHost extends FileSystemEngineHost {
  constructor(protected _root: string) { super(_root); }

  protected _resolveCollectionPath(name: string): string {
    // Allow `${_root}/${name}.json` as a collection.
    if (existsSync(join(this._root, name + '.json'))) {
      return join(this._root, name + '.json');
    }

    // Allow `${_root}/${name}/collection.json.
    if (existsSync(join(this._root, name, 'collection.json'))) {
      return join(this._root, name, 'collection.json');
    }

    // Allow `${_root}/ ** /${name}/collection.json.
    const collectionJsonPath = globSync(`${ name }/**/collection.json`, {
      cwd: this._root
    })[ 0 ];
    if (collectionJsonPath) {
      return join(this._root, collectionJsonPath);
    }

    throw new CollectionCannotBeResolvedException(name);
  }
}
```
Next, I created `host`, `engine` and `collection`:

```typescript
const host = new MyEngineHost('my_root');
host.registerOptionsTransform(/* ... */)
const engine = new SchematicEngine(host);
const collection = engine.createCollection('@nrwl/schematics');
```

So far everything works:

    host.listSchematics(collection); /* OK */

but when I try to create schematics:

    const schematic = collection.createSchematic('app');

I get an error ` Error: Unknown collection "nx".`

### The log given by the failure

It turns out that `createSchematic()` is using `name` from `@nrwl/schematics/src/collection.json` which is set to `nx`, but is caching it using `@nrwl/schematics`;

![collection-cache](https://user-images.githubusercontent.com/4272818/32991371-7274bd2e-cd3a-11e7-9271-3fac5e856144.PNG)

### Desired functionality

Since `name` in `collection.json` is optional (it's not set in `@schematics/angular`) I believe collection name should be used and not `name` from `collection.json`.

### Mention any other details that might be useful

Chaning [`FileSystemEngineHost _transformCollectionDescription()`](https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/tools/file-system-engine-host.ts#L60) to match [`NodeModulesEngineHost _transformCollectionDescription()`](https://github.com/angular/devkit/blob/master/packages/angular_devkit/schematics/tools/node-module-engine-host.ts#L90-L93) should solve the issue

```typescript
    // return desc as FileSystemCollectionDesc;
    return {
      ...desc,
      name,
    } as FileSystemCollectionDesc;
```

_Copied from original issue: angular/devkit#285_

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
