### ISSUE TITLE
Add change log for `@angular-devkit/build-optimizer`

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12151]
_From @emilio-martinez on December 18, 2017 8:49_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Area
```
- [X] devkit
- [ ] schematics
```

### Desired functionality
Given that `@angular-devkit/build-optimizer` can be used as a standalone, I believe it should have a changelog. There's no indication of what has changed, nor are releases tagged to at lease see the commits that are included in a version diff.

_Copied from original issue: angular/devkit#341_

**Comment by alexeagle** [comment]
_From @filipesilva on December 18, 2017 9:0_

I think this is a problem with overall packages in the devkit. 

@hansl it seems we had a changelog once (https://github.com/angular/devkit/releases) but only that one. We should add detailed changelogs on releases.

**Comment by alexeagle** [comment]
_From @emilio-martinez on March 25, 2018 2:53_

@filipesilva @hansl pinging on this item again. This would be immensely helpful.

I understand that when used with Angular CLI this is more seamless, but when used with a non-Angular CLI Webpack setup using these packages somewhat feels like flying blind.

**Comment by alan-agius4** [comment]
Obsolete as changelog has been added in this repo.
