### ISSUE TITLE
Specify multiple default collections

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12157]
_From @jeffbcross on October 31, 2017 22:4_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [] devkit
- [x] schematics
```

### Desired functionality
It'd be nice to have multiple collections configured in my CLI project instead of a single default collection. I.e. I'd like to have a project that gives preference to `nrwl/schematics` but will fall back to `angular/schematics` if I try to generate something not provided by `nrwl/schematics`. This would make it easier to publish many focused schematics without requiring the user to specify the collection each time they're generating something new. My naive suggestion is to change the `.angular-cli.json` schema from a single `collection` value to a cascading array of `collections` like so:

```json
"defaults": {
  "collection": "nrwl/schematics"
}
```

```json
"defaults": {
  "collections": [
    "nrwl/schematics",
    "angular/schematics"
  ]
}
```

Then when calling `ng generate`, schematics would use the first collection that provides a matching schematic.

This issue seems cross-cutting between CLI and Schematics, so I thought this repository was the most appropriate place to open it, but lmk if I should open it on angular/angular-cli.

(This may seem similar to #34, but it's more focused on end user experience than schematics author experience).

_Copied from original issue: angular/devkit#249_

**Comment by leon** [comment]
It's been a year since the last comment.
Any progress on this?

**Comment by Splaktar** [comment]
I don't believe so.

**Comment by cherurg** [comment]
I also faced it. For me, would be great to use `@ngrx/schematics` and `@ngneat/spectator` schematics at the same time.

**Comment by G-Cyrille** [comment]
It definitely would be great for working with different sets of schematics !
I currently switch manually from one set to the other (@ngrx/schematics <-> @ionic/angular-toolkit)

**Comment by konradst** [comment]
Yep, it would be especially useful for mobile dev. I also have to switch between @ngrx/schematics and @nativescript/schematics
