### ISSUE TITLE
Display dry-run generated files contents in verbose mode

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12155]
_From @wardbell on November 20, 2017 17:57_

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Area
```
- [x] devkit
- [ ] schematics
```

### Desired functionality

Current DryRun lists the files that will be created/touched but not their contents. 

Proposing a verbose variant that would output the files themselves. The developer could scroll through the console log or (more likely) capture the stdout to file.

Maybe this happens with the flag combo `--dry-run --verbose`

_Copied from original issue: angular/devkit#286_

**Comment by alexeagle** [comment]
_From @ssilvert on January 10, 2018 15:34_

+1

Usually, you are just working on the output of one file at a time.  So perhaps another option would be to specify a single file.

--verbose would dump all modified files
--verbose=myPath would dump a single file

**Comment by alan-agius4** [comment]
Closing since there is little to no interest in this issue from the community since it was opened in 2018 and therefore it doesn't warrant to be included as part of our API.

Let's reconsider this in the future if there is a bigger demand for this.
