### ISSUE TITLE
Interactive input dialog

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12163]
_From @dansanderson on June 14, 2017 22:40_

The command line tool should have two running modes: an interactive mode and a batch mode. In batch mode, all inputs for the schematic are specified on the command line, and input validation errors terminate the tool with a message. In interactive mode, a schematic can be invoked with or without arguments on the command line, and the tool begins an interactive dialog describing the behavior of the schematic, and presents and prompts for values for some or all inputs. Inputs with defaults or whose values were provided by another source are presented for confirmation ("press enter to accept default"-style). After all prompts have been presented, show a confirmation screen with all inputs and accepted values, and allow selective adjustment of values.

Schematic properties will need short and long descriptions and a value type (string, boolean, maybe number).

The confirmation screen can come after all rules have been evaluated to report conflicts and errors and allow the user to adjust inputs interactively to resolve the conflicts. After confirmation, the schematic can execute side effects (FSSink, task execution).

(Ask me for a more detailed design or demo. I have a full implementation in a related tool.)

_Copied from original issue: angular/devkit#11_

**Comment by PonnarV** [comment]
### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### 

> 

> [``]([url]([url]([url]([url]([url]([url](url)))))))

> 

- 

- 

- 

- 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] ### ### ### ### ### ### ### ### 

> 

> 

> 

> 
        #########
- [ ] 

- [ ] 

1. 

> 

> [****](url)

> 

> [`****`](

- url

)

**Comment by cyrilletuzi** [comment]
@alexeagle How do you choose the batch mode in CLI v7?

Interactivity can be a problem for tools like Angular Schematics extension for VS Code (see cyrilletuzi/vscode-angular-schematics#14) (and I suppose the Angular Console will be concerned as well).

**Comment by clydin** [comment]
There's no current batch mode.  But you can turn off prompts with `--no-interactive`/ `--interactive false`.

**Comment by cyrilletuzi** [comment]
@clydin Thanks for the answer. I have a few more questions to be sure about how to handle that:

1. Do you confirm that `no-interactive` can be used with all commands? (this option doesn't seem to appear in the commands schemas)

2. Is `no-interactive` backward-compatible (no error if still in CLI v6 for example)?

3. Sorry if it's a stupid question, but in my extension, commands are launched with Node `exec` function, is this a case where the interactive mode is automatically disabled?

**Comment by clydin** [comment]
1) Only schematic related commands (e.g., `new`, `generate`, `add`, `update`) can have prompts currently.

2) The option is only present in 7.0 so no it is not backward compatible.

3) If executed in an environment that doesn't have a terminal then yes.  Otherwise, you should be able to use spawn to control the `stdout` stream.

**Comment by alan-agius4** [comment]
Closing as prompts has been implemented
