### ISSUE TITLE
schematics: Cannot generate same element again

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12162]
_From @lacolaco on September 20, 2017 6:53_

My use-case, I'd like to generate .spec.ts file only into already existing components/pipes generated by CLI. 

```
src/app/core/components/
└── my-cmp
    ├── my-cmp.component.html
    ├── my-cmp.component.scss
    ├── (my-cmp.component.spec.ts) <-- I want to generate this later
    └── my-cmp.component.ts
```

Currently, I cannot generate spec without other files.

```
> ng g component core/components/my-cmp --spec
error! src/app/core/components/my-cmp/my-cmp.component.html already exists.
error! src/app/core/components/my-cmp/my-cmp.component.ts already exists.
```

`--force` option allows do that, but it will initialize existing code. I'd like to just append .spec.ts. 

_Copied from original issue: angular/devkit#156_

**Comment by alan-agius4** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/7727
