### ISSUE TITLE
Generated directive selector name should be camelcase

### ISSUE THREAD

**Issue by Blasz** [angular/angular-cli#1216]
##### Version
```
$ ng --version
(node:20286) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.6
node: 6.2.1
os: linux x64
```

##### Repro steps

The following generate command produces a kebab case selector name instead of camelCase.
```
$ ng g directive shared/directives/wrap-if
(node:20210) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing directive
  create src/app/shared/directives/wrap-if.directive.spec.ts
  create src/app/shared/directives/wrap-if.directive.ts
```

src/app/shared/directives/wrap-if.directive.ts
```
import { Directive } from '@angular/core';

@Directive({
  selector: '[wrap-if]'
})
export class WrapIf {

  constructor() {}

}
```

As per the [styleguide](https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-06),

> Do Use lower camel case for naming the selectors of our directives.

I've passed `ng generate` the name in kebab case because the [README](https://github.com/angular/angular-cli#generating-components-directives-pipes-and-services) states so and follows the convention of passing the file name where file names should [use dashes to separate words in the descriptive name](https://angular.io/docs/ts/latest/guide/style-guide.html#02-02).

I've read #424 and acknowledge that passing the name as camelCase to `ng generate` produces the correct selector but it is unintuitive and doesn't follow the [README](https://github.com/angular/angular-cli#generating-components-directives-pipes-and-services). I don't think we should make an exception to the convention of passing kebab case file names to `ng generate`.

Instead of not modifying the selector name at all for directives, I think they should be modified to be camelCase as per the styleguide.

**Comment by choeller** [comment]
As an addition according to the Style-Guide, the Selector for Directives should also take the prefix of the app into account. So I would assume

```ts
ng g directive lower-case
```
to create a Direktive with the selector
```ts
[appLowerCase]
```

**Comment by filipesilva** [comment]
@Brocco can you weigh in?

**Comment by Brocco** [comment]
The style guide does dictate camelCase for directive selectors **and** prefixing them with the application prefix. I will put together a PR for this.

Reference: https://angular.io/docs/ts/latest/guide/style-guide.html#!#02-08

**Comment by nukec** [comment]
what if you prefix is kebab case? `app-something`, then you are doomed. why is component kebab case and directive camel case in style guide? can't we just use kebab case for everything consistently?
