### ISSUE TITLE
Allow ng serve to serve multiple applications at once

### ISSUE THREAD

**Issue by ly-cultureiq** [angular/angular-cli#12181]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

Allow multiple apps to be served with ng serve
Webpack dev server supports multiple configurations already.
Currently the way command-runner is designed it only does the multiTarget consecutively, rather than allowing to run synchronously, which would allow for multiple webpack configs to be created and merged together for serve.

**Comment by alandroid** [comment]
Similar or duplicate issues:

https://github.com/angular/angular-cli/issues/12107
https://github.com/angular/angular-cli/issues/5072
https://github.com/angular/angular-cli/issues/4624
https://github.com/angular/angular-cli/issues/7954

**Comment by alan-agius4** [comment]
Hi @ly-cultureiq, 

Thanks for this feature request. However, unfortunately currently this doesn't fall in the Angular CLI roadmap. Let's re-visit this in the future.

Thanks,
Alan
