### ISSUE TITLE
Using different name for import ng-packagr lib from dist folder is not working

### ISSUE THREAD

**Issue by jakubjosef** [angular/angular-cli#12184]
Hi everyone, I facing interesting problem with Angular ng-packagr powered libraries.
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
macOS High Sierra 10.13.6
```
- node -v
v8.11.1
- npm -v
5.6.0
- ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.1.5
Node: 8.11.1
OS: darwin x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cli                       6.1.5
@ngtools/json-schema               1.1.0
@schematics/angular                0.6.8
@schematics/update                 0.6.8
ng-packagr                         3.0.6
rxjs                               6.3.2
typescript                         2.7.2
webpack                            4.17.2
```

### Repro steps
Generate library using ng generate library and change tsconfig path.
From:
```
      "ui-components": [
        "dist/ui-components"
      ],
      "ui-components/*": [
        "dist/ui-components/*"
      ]
```

To:
```
     "@ui-components": [
        "dist/ui-components"
      ],
      "@ui-components/*": [
        "dist/ui-components/*"
      ]
```
And use `import { something } from '@ui-components'`. Basically the assumption was I will use `@ui-components` in ui-starter app and `ui-components` in all other places. But looks like there is some "magic" because any other name than original one causing the same error.

### The log given by the failure

``` 
ERROR in ./src/app/pages/registration/steps/step-info/step-info.component.ngfactory.js
Module not found: Error: Can't resolve '../../../../../../dist/ui-components/ui-components.ngfactory' in '/Users/jakob/ui-starter/src/app/pages/registration/steps/step-info' 
```

### Desired functionality
It should work with a different name inside "main" application.

### Mention any other details that might be useful
You might want to know why I want to have this feature. Let me shorty explain our problem.

We have application called ui-starter, this application contains projects folder with ui-components library. From ui-starter project we using this library by `import { something } from 'ui-components'` with "tsconfig path hack" and everything works nice and smooth. 

The problem started when we add another application (table-app) which has dependency to ui-components project. This application wants to consume ui-components source code during AOT build and it fails with error: `ERROR in : Error: Trying to import a source file from a node_modules package:` It's maybe possible to have some circular dependencies but I think it's normal use case.

```
ui-starter app -> contains ui-components project
ui-starter app -> using table-app as dep
table-app -> has dep to ui-components from npm - wanted to use them but read path from tsconfig.json
```

So my assumption was let's change paths config and use some prefixed version inside ui-starter app, let's say `@ui-components` or `_ui-components`. But unfortunately I am not able to use this approach. I spend lot of time reading other issues here, in stackoverflow and in other repos, that's the reason why I create my own one.

Thank you very much for any help.

**Comment by alan-agius4** [comment]
Hi, changing the tsconfig paths is not enough. You need to change the library name from the `package.json`, update the `angular.json` with the new library path and rebuild the library as the library name is also present in the generated `metadata.json`

**Comment by jakubjosef** [comment]
@alan-agius4 Thank you for your answer. So I cannot use different name :(
That means this problem is unsolvable - you cannot have a dependency which has a dependency on NPM version of library you have inside `projects` folder. 

This diagram should help you understand my case, I don't have much time these days but I hope I create small reproduction soon. 

So the problem is about `app B` should use `lib A` from node_modules but tsconfig.json override path to projects folder, which is prohibited my compiler (seriously, related check can be removed from code and everything will be working. In the other words - we want to have green line, but we have red line.

![angular-dep-issue](https://user-images.githubusercontent.com/4058213/45169616-dcb5d800-b1b2-11e8-8ccf-7b27dc323a9c.png)

**Comment by alan-agius4** [comment]
The tsconfig path to node module is not prohibited. Thought the library must be already compiled to JavaScript. I think what you want is to lookup from dist if exists otherwise lookup in node_modules using tsconfig paths.

We have reviewed, this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
