### ISSUE TITLE
Installation failed under Windows 10

### ISSUE THREAD

**Issue by hantsy** [angular/angular-cli#1218]
Try to install the latest angular cli (1.0.0-beta.8)under Windows 10 64 bit.

    npm install -g angular-cli --registry=http://registry.npmjs.com

And got the following failure info.

 >  npm ERR! enoent ENOENT: no such file or directory, rename 'E:\Users\hantsy\AppData\Roaming\npm\node_modules\.staging\abbrev-fe5ffaa2' -> 'E:\Users\hantsy\AppData\Roaming\npm\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\node_modules\abbrev'
> npm ERR! enoent ENOENT: no such file or directory, rename 'E:\Users\hantsy\AppData\Roaming\npm\node_modules\.staging\abbrev-fe5ffaa2' -> 'E:\Users\hantsy\AppData\Roaming\npm\node_modules\angular-cli\node_modules\ember-cli\node_modules\npm\node_modules\abbrev'

**Comment by neilhem** [comment]
Try to uninstall angular-cli first then install it again

**Comment by hantsy** [comment]
@neilhem It works. Thanks.
