### ISSUE TITLE
Error: EINVAL: invalid argument, read when upgrading Angular app.

### ISSUE THREAD

**Issue by wannadream** [angular/angular-cli#12182]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v10.9.0
npm: 6.4.1
ng (global): 6.1.5
ng (local): 1.7.4

OS Information:
WindowsBuildLabEx                                       : 15063.0.amd64fre.rs2_release.170317-1834
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Professional
WindowsInstallationType                                 : Client
WindowsInstallDateFromRegistry                          : 6/6/2017 5:07:25 PM
WindowsProductId                                        : 00330-80000-00000-AA317
WindowsProductName                                      : Windows 10 Pro
WindowsSystemRoot                                       : C:\WINDOWS
WindowsVersion                                          : 1703

### Repro steps

I am doing upgrade for my app from 5.2 to 6.1, following the Angular Update Guide: https://update.angular.io/.

After I ran 'npm install -g "@angular/cli"', the latest cli was installed successfully. Next, I ran 'npm install "@angular/cli"' in my app source folder. An fatal error happened.

### The log given by the failure

5906 verbose stack Error: EINVAL: invalid argument, read

5906 verbose stack     at C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\gentle-fs\lib\rm.js:245:7
5906 verbose stack     at C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\gentle-fs\node_modules\iferr\index.js:13:50
5906 verbose stack     at C:\Users\xxxxxxx\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:287:18
5906 verbose stack     at FSReqWrap.oncomplete (fs.js:153:5)
5907 verbose cwd H:\w\shepherd.io\src\ui
5908 verbose Windows_NT 10.0.15063
5909 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxxxxxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@angular/cli"
5910 verbose node v10.9.0
5911 verbose npm  v6.4.1
5912 error code EINVAL
5913 error EINVAL: invalid argument, read
5914 verbose exit [ 1, true ]

### Desired functionality

I am not sure where goes wrong. It should work as the guide tells.

### Mention any other details that might be useful

I have tried 'npm cache clean --force'.
I have tried removing the whole node_modules folder.

Log file attached:
[2018-09-05T17_08_43_757Z-debug.log](https://github.com/angular/angular-cli/files/2353863/2018-09-05T17_08_43_757Z-debug.log)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by DanWizard** [comment]
I am having this same error. Any solutions?
