### ISSUE TITLE
Angular loads only modules that are in src/app folder

### ISSUE THREAD

**Issue by evgdim** [angular/angular-cli#1219]
1.    Windows 10

2. angular-cli version - 1.0.0-beta.8, 
    angular version - 2.0.0-rc.3

3. 
I have created an angular2 project with angular-cli(version 1.0.0-beta.8, angular version is 2.0.0-     rc.3) 
But the components are loaded only if they are in src\app\ folder. If I move the module folder in a sub folder angular cant load the js file for that module.
See my SO question for more details: http://stackoverflow.com/questions/38041493/angular-2-load-components-only-from-root-app-folder

4. 
     All the components are correctly compiled irrespective of the folder, but in the browser I get:

    zone.js:101 GET http://localhost:4200/app/project/my-component.js 404 (Not Found)

5.     
    The application tries to load /app/project/my-component.js while the generated file is /app/project/my-component.component.js

**Comment by filipesilva** [comment]
Seems like your issue was answer on stack-overflow. 

Mostly it seems like you were importing the wrong thing:

```
import { MyComponentComponent } from './my-component';
```

where you should be doing

```
import { MyComponentComponent } from './my-component.component';
```
