### ISSUE TITLE
environment.ts should be merged not overwritten

### ISSUE THREAD

**Issue by snebjorn** [angular/angular-cli#12190]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
<pre><code>
Angular CLI: 6.1.5
Node: 9.10.1
OS: win32 x64
Angular: 6.1.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      6.4.7
@angular/cli                      6.1.5
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.1
typescript                        2.9.2
webpack                           4.9.2
</code></pre>

### Current functionality
environment.ts is overwritten with environment,target.ts

#### Example

**environment.ts**
```
export const environment = {
  production: false,
  foo: "bar"
}
```

**environment.prod.ts**
```
export const environment = {
  production: true
}
```

**Result (ng build --configuration=prod)**
```
{
  production: true
}
```

### Desired functionality
environment.ts should be merged with environment,target.ts

#### Example

**environment.ts**
```
export const environment = {
  production: false,
  foo: "bar"
}
```

**environment.prod.ts**
```
export const environment = {
  production: true
}
```

**Expected result (ng build --configuration=prod)**
```
{
  production: true
  foo: "bar"
}
```

### What is the motivation / use case for changing the behavior?
Frameworks like ASP.NET or Spring Boot merge environment configs like the desired example given. So when working with these environment files it's reasonable to expect they work in a similar fashion.

### Workaround
It's possible to achieve the desired behavior without *much* hassle. Using a base class and the spread operator. But I still think it sould be the default behavior :)

**environment.base.ts**
```
export const environment = {
  production: false,
  foo: "bar"
}
```

**environment.ts**
```
import { environment as base } from "./environment.base";

export const environment = {
  ...base,
}
```

**environment.prod.ts**
```
import { environment as base } from "./environment.base";

export const environment = {
  ...base,
  production: true
}
```

**Comment by iamruslanbakirov** [comment]
So, it's good idea
How long wait changes ?

**Comment by snebjorn** [comment]
Great news everyone, or some at least not bad.

With the new ivy compiler both `serve` and `build` now uses the same compiler. Meaning the mentioned workaround now works when building the application. Before it only worked when using `ng serve` which took me a while to track down :(

But now the workaround works! 🎉

Now all we wait for is the merge functionality.

**Comment by alan-agius4** [comment]
Merging file contents of files specified in `fileReplacements` is not something that we'd like to add. As the option name implies the file is replaced. The contents of the source and target file can be anything, it can contain a Classes, Object literals, Const, Components etc..., which would make merging not feasible.

In future, we will be providing alternative method to replace settings/content in files.
