### ISSUE TITLE
ng generate class --type documentation incomplete

### ISSUE THREAD

**Issue by chrisvelevitch** [angular/angular-cli#12199]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc
```

### Desired functionality
The description of the `--type` option needs to explain what this option does and the values or range of values that this option accepts/expects.

### Mention any other details that might be useful

see `https://github.com/angular/angular-cli/wiki/generate-class`

**Comment by btargac** [comment]
How I got here ?
I was searching for available options of --type ❓

**Comment by alan-agius4** [comment]
Documentation is now available at https://angular.io/cli/generate

**Comment by alan-agius4** [comment]
This has been addressed in https://angular.io/cli/generate

`type` properties are of type string, which by default is set to an empty string.
