### ISSUE TITLE
[7 beta] ng new error: "new command requires to be run outside of a project, but a project definition was found", doesn't say where the stray file is

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#12198]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.0-beta.2
Node: 10.10.0
OS: linux x64

(ng new doesn't have other versions yet)

### Repro steps
`ng new newProjecct`

### The log given by the failure
![image](https://user-images.githubusercontent.com/1249083/45199386-9f615100-b26b-11e8-9f12-8ce919b2552d.png)

### Desired functionality
A new project ;)

**Comment by amitport** [comment]
same here. `Angular CLI: 7.0.0-beta.2` on **windows 10**

**Comment by alan-agius4** [comment]
I am unable to replicate this. Any help to replicate this would be appreciated. 

```
c:\git\cli-repos\test 
λ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.0.0-beta.2
Node: 10.3.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.9.0-beta.2
@angular-devkit/core         0.9.0-beta.2
@angular-devkit/schematics   0.9.0-beta.2
@schematics/angular          0.9.0-beta.2
@schematics/update           0.9.0-beta.2
rxjs                         6.2.2
typescript                   3.0.3


c:\git\cli-repos\test 
λ ng new testNg --next
? Would you like to generate a routing module? (y/N)
```

**Comment by alan-agius4** [comment]
Following a convo with @SanderElias, I might be that there is a hidden `.angular.json`.

Kindly try to check if that's the case by executing  `ls -a` in a terminal in the directory that you are trying to using the `ng new` command

**Comment by alexeagle** [comment]
I had the same issue but it was a `.angular.json` in my home directory. So you should walk up the parent directories from the place where you ran `ng new` and locate/delete that file.

Renaming this to be the thing Hans said he would do to fix.

**Comment by SanderElias** [comment]
I can confirm that there was a stray (hidden)  `.angular.json`  3 level's up the folder tree.
This error would be much more useful if it points to the location + name of the config it detected.

**Comment by amitport** [comment]
Still getting this error when trying from `c:\` with no `angular.json`

**Comment by Insight707** [comment]
same

**Comment by lanemc** [comment]
Just downloaded the new version 7.1.0 and can confirm this issue still exists. The angular.json file appeared in the directory where I tried to run the ng new command. I could see it by running ls -a as suggested. When I deleted it I was able to run the ng new command again and successfully generate a project.

**Comment by davvit** [comment]
Can we re-open this?

![image](https://user-images.githubusercontent.com/4433698/49541464-6ea7ac80-f898-11e8-902e-334a38fc3a2a.png)

Angular CLI: 7.0.4
Node: 10.13.0
OS: win32 x64
Angular: 2.4.10
... compiler, compiler-cli, core

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.4
@angular-devkit/core         7.0.4
@angular-devkit/schematics   7.0.4
@angular/cdk                 2.0.0-beta.12
@angular/cli                 7.0.4
@angular/tsc-wrapped         0.5.2
@ngtools/json-schema         1.1.0
@ngtools/webpack             1.10.2
@schematics/angular          7.0.4
@schematics/update           0.10.4
rxjs                         6.3.3
typescript                   3.1.6
webpack                      2.2.0
