### ISSUE TITLE
Document all the possible cli command abbreviations

### ISSUE THREAD

**Issue by chrisvelevitch** [angular/angular-cli#12200]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc
```

### Desired functionality
I've seen examples of command abbreviations like `ng g c <component-name>` to generate components and `ng g cl <class-name>` to generate classes, but these are undocmented.

All the the possible abbreviations ought to be documented.

**Comment by adampenn** [comment]
Haven't contributed to a lot of projects before but I'd be happy to take this issue.

**Comment by adampenn** [comment]
I created a PR and signed the CLA let me know if there is anything else I need to do.
