### ISSUE TITLE
Cannot generate library with name app-routing

### ISSUE THREAD

**Issue by broweratcognitecdotcom** [angular/angular-cli#12206]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version = v8.11.3
npm --version = 5.6.0

Angular CLI: 6.1.5
Node: 8.11.3
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.5
@angular-devkit/core         0.7.5
@angular-devkit/schematics   0.7.5
@schematics/angular          0.7.5
@schematics/update           0.7.5
rxjs                         6.2.2
typescript                   2.9.2

### Repro steps

I created a new app so that I could generate a number of different libraries:
1. Create a new application: ng new libraries

from the libraries folder that just got created, I generated a library:

ng g library @companyname/authentication

The library is generated in the libraries/projects/companyname/authentication/ folder

I attempt to generate another library:

ng g library @companyname/app-routing

I receive an error: Could not find an NgModule. Use the skip-import option to skip importing in NgModule.
This has to be a bug. Can anyone please confirm?

### Desired functionality

It should not give an error when I want to create a library called @companyname/app-routing

**Comment by alan-agius4** [comment]
Related to https://github.com/angular/angular-cli/issues/11961
