### ISSUE TITLE
angular 2 local storage 

### ISSUE THREAD

**Issue by karthikkavin** [angular/angular-cli#1221]
how to add angular 2 local storage and configure the angular 2 cli project

**Comment by elvirdolic** [comment]
Please read: https://github.com/angular/angular-cli/wiki/3rd-party-libs

**Comment by stijn26** [comment]
karthikkavin, were you able to get this to work? Can you provide a step-by-step guide? I'm also struggling with including 3rd party libs into CLI. The link of elvirdolic doesn't cut it.

**Comment by delasteve** [comment]
@stijn26, @karthikkavin 

I answered this a while back for someone on StackOverflow (using a LocalStorage ng2 provider called `h5webstorage`).

http://stackoverflow.com/questions/37747813/add-script-in-angular-cli-project/37754302#37754302

Also, see https://github.com/angular/angular-cli/issues/1204

**Comment by karthikkavin** [comment]
thanks stijin26, now i clearly understand and successfully configured.

**Comment by karthikkavin** [comment]
can you please advise, how to update angular 2 rc 3 to rc 4 full package?

**Comment by filipesilva** [comment]
@karthikkavin you should be able to just update them in `package.json`.

Closing this issue as it seems that it's mostly answered.

**Comment by karthikkavin** [comment]
ok, thanks

**Comment by karthikkavin** [comment]
i have update package.json angular rc 3 to rc 4 got this error on console.
Failed to parse SourceMap: http://localhost:4200/vendor/@angular/common/src/localization.js.map
Failed to parse SourceMap: http://localhost:4200/vendor/rxjs/add/observable/forkJoin.js.map
Failed to parse SourceMap: http://localhost:4200/vendor/rxjs/observable/DeferObservable.js.map
How to fix?

**Comment by filipesilva** [comment]
Can you open a new issue with reproduction steps (or a repo) that I can follow to get those errors?
