### ISSUE TITLE
Allow user-specific configuration

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#12217]
### Bug Report or Feature Request (mark with an `x`)
This is a feature request

### Background
With the CLI's support of multiple applications and libraries with the intention of supporting monorepoes it is a challenge for developers working on different applications in the same monorepo to specify a different [defaultProject](https://github.com/angular/angular-cli/blob/38fda3ea6057ad0eb5ca2a831146310770585a9d/packages/angular_devkit/core/src/workspace/workspace-schema.ts#L22-L25).

Developer A could be working on application `foo` while developer B could be working on application `bar`. To change the defaultProject independently for each user is a tedious task every time they would rebase or get a latest version.

### Desired functionality
Developers should be able to manage user-specific settings in a local file that could be easily ignored for source control.

My initial suggestion would be to support a file named `angular-user.json` in a workspace root where defaults could be specified.
```
// angular-user.json
{
  "defaultProject": "foo"
}
```

### Mention any other details that might be useful
This file could be created with `ng new`, but I think just adding it to the default `.gitignore` would be sufficient. This file could also be used to override other values as well, but the `defaultProject` use-case is the most important.

**Comment by alexeagle** [comment]
We've discussed something similar for google3 and needing a "global" config for a large org (like all of Google's Angular apps) along with a team-specific config that should extend from it.

Makes sense to me that there could be [`monorepo/angular.json`,  `monorepo/my_org/my_team/angular.json`, `~/angular.json`] to be composed in that order

**Comment by sgwatgit** [comment]
Good ideas!

I'm already doing something related to this for application configuration.

I have `environments/environment.local.ts` which is ignored by source control but required for local development. Developers can copy `environments/environment.ts` and modify it as they see fit (some devs run an api locally while some use the shared dev api).

I also have runtime settings deployed from the CD tool as a separate app-settings.json file.
For local development, since there is no CD, developers need to create a `config/app-settings.local.ts` file that gets copy to `src/app-settings.json` which is listed in the `assets` for `local` configuration.

Both `config/app-settings.local.json` and `src/app-settings.json` are ignored by source control.

It seems like per developer configuration of things like `environment`, `defaultSchematics`, `defaultProject` could all be helpful.

**Comment by seangwright** [comment]
I know I'm not @Brocco but...

We toggle `environment.debug` (`boolean`) on / off per dev. Some devs want to see all the route/auth/interceptor logs in the console and some don't.

This is also dependent on what is being worked on - oauth/routing flows are heavily state dependent and sometimes can involve race conditions so verbose logging can be helpful when working on it.

This setting can also toggle something like Redux dev tools on/off.

`environment.apiHost` could be different per local dev environment for various reasons (though we try to provide documentation to ensure environments are consistent). Maybe a dev has different instances/versions of an api running locally on different ports and wants to switch back and forth.

These hosts would both be for the `local` environment but would be different values.

When working on time-based eventing (inactivity modals, app update polling, form auto-saving) we want to switch to shorter timeouts/intervals than the default `local`/`app` setting to test the UX.

Yes, this last one could be pulled down during app init in runtime settings, but for the previous two they need to be compile time.

**Comment by Brocco** [comment]
@hansl thanks for reaching out. The main reasoning for requesting is the default project setting on a per user basis, but as pointed out by @seangwright there are other settings which individuals may want to override on a per user basis.

Also this is the next logical extension of having multiple configurations, currently there is global (user specific on all workspaces) and specific workspace, but this is giving an individual control over the workspace-wide settings/configuration.

I realize that this is not a super-critical feature, but it would be a good way to increase productivity/usability for users working in a larger workspace where they focus on specific projects.

**Comment by hansl** [comment]
Overriding builder options and configurations might be hard. I think philosophically we shouldn't let people overwrite the `projects` key with custom data from a generic `angular.json` file (workspace), but there has to be a way to make this work (maybe a per level overriding?)

Definitely need further discussion. We're meeting weekly to address those so we'll keep the discussion and feedback open.

Thanks!

**Comment by alan-agius4** [comment]
Hi all, this is currently out of scope of the Angular CLI. Let's revisit this if there is a bigger interest in this feature.

Thanks
