### ISSUE TITLE
1.7.4 can not be installed checksum error.

### ISSUE THREAD

**Issue by etavener** [angular/angular-cli#12224]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ x] version
- [ ] doc
```

### Versions

1.7.4

### Repro steps

`npm install angular/cli@1.7.4` is broken

### The log given by the failure

Error: sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= integrity checksum failed when using sha1: wanted sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= but got sha1-n85YVY2wat0OAtpXcaw7bNk4gak=. (1814 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183░░░░░░⸩ ⠦ extract:performance-now: sill extract node-forge@0.7.5
      throw er; // Unhandled 'error' event
      ^

Error: sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= integrity checksum failed when using sha1: wanted sha1-iaf92TgmEmcxjq/hT5wy5ZjDaQk= but got sha1-n85YVY2wat0OAtpXcaw7bNk4gak=. (1814 bytes)
    at Transform.on (/usr/local/lib/node_modules/npm/node_modules/ssri/index.js:275:19)
    at emitNone (events.js:111:20)
    at Transform.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm WARN extract-text-webpack-plugin@3.0.2 requires a peer of webpack@^3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN axe-webdriverjs@1.3.0 requires a peer of selenium-webdriver@>= 2.53.1 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, rename '/Users/ewantavener/Documents/projects/moj/cpp.ui.core/node_modules/.staging/fsevents-582d71b6/node_modules/safer-buffer' -> '/Users/ewantavener/Documents/projects/moj/cpp.ui.core/node_modules/.staging/safer-buffer-25590353'

### Desired functionality

I need to use a set version of Angular CLI for Angular 5. However, the last supported CLI (1.7.4) cannot be installed. I think this is due to a dependency version issue.

### Mention any other details that might be useful

When I copied the dependency details from another package-lock.json it worked fine.

**Comment by alexeagle** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue if the problem you are experiencing isn't known.
