### ISSUE TITLE
Error creating new ng app

### ISSUE THREAD

**Issue by agi0s** [angular/angular-cli#12231]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Node: 9.5.0
NPM: 5.6.0
Angular CLI: 6.2.1
OS: Windows 10 x64

### Repro steps
ng new my-app

### The log given by the failure
C:\Users\User\Desktop\hometask_ui>ng new my-app
CREATE my-app/angular.json (3544 bytes)
CREATE my-app/package.json (1312 bytes)
CREATE my-app/README.md (1022 bytes)
CREATE my-app/tsconfig.json (408 bytes)
CREATE my-app/tslint.json (2837 bytes)
CREATE my-app/.editorconfig (245 bytes)
CREATE my-app/.gitignore (503 bytes)
CREATE my-app/src/favicon.ico (5430 bytes)
CREATE my-app/src/index.html (292 bytes)
CREATE my-app/src/main.ts (371 bytes)
CREATE my-app/src/polyfills.ts (3194 bytes)
CREATE my-app/src/test.ts (642 bytes)
CREATE my-app/src/styles.css (80 bytes)
CREATE my-app/src/browserslist (388 bytes)
CREATE my-app/src/karma.conf.js (964 bytes)
CREATE my-app/src/tsconfig.app.json (166 bytes)
CREATE my-app/src/tsconfig.spec.json (256 bytes)
CREATE my-app/src/tslint.json (314 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (662 bytes)
CREATE my-app/src/app/app.module.ts (314 bytes)
CREATE my-app/src/app/app.component.html (1141 bytes)
CREATE my-app/src/app/app.component.spec.ts (995 bytes)
CREATE my-app/src/app/app.component.ts (210 bytes)
CREATE my-app/src/app/app.component.css (0 bytes)
CREATE my-app/e2e/protractor.conf.js (752 bytes)
CREATE my-app/e2e/tsconfig.e2e.json (213 bytes)
CREATE my-app/e2e/src/app.e2e-spec.ts (302 bytes)
CREATE my-app/e2e/src/app.po.ts (208 bytes)
npm ERR! Maximum call stack size exceeded

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-09-10T19_50_20_853Z-debug.log
Package install failed, see above.

debug.log:
3415 http fetch GET 404 https://registry.npmjs.org/@xtuc%2flong 877ms
3416 silly fetchPackageMetaData error for @xtuc/long@4.2.1 404 Not Found: @xtuc/long@4.2.1
3417 verbose stack RangeError: Maximum call stack size exceeded
3418 verbose cwd C:\Users\User\Desktop\hometask_ui\my-app
3419 verbose Windows_NT 10.0.14393
3420 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--quiet"
3421 verbose node v9.5.0
3422 verbose npm  v5.6.0
3423 error Maximum call stack size exceeded
3424 verbose exit [ 1, true ]

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by subramn** [comment]
Facing same issue today. any work around?

**Comment by FelipeLujan** [comment]
i have the same issue.

**Comment by iamdimitar3d** [comment]
Same issue.

Angular CLI: 6.2.1
Node: 8.11.4
npm: 6.4.1

**Comment by sg-garg** [comment]
I am facing same issue

3414 silly resolveWithNewModule @webassemblyjs/helper-fsm@1.7.6 checking installable status
3415 http fetch GET 404 https://registry.npmjs.org/@xtuc%2flong 125ms
3416 silly fetchPackageMetaData error for @xtuc/long@4.2.1 404 Not Found: @xtuc/long@4.2.1
3417 verbose stack RangeError: Maximum call stack size exceeded
3417 verbose stack     at RegExp.test (<anonymous>)
3417 verbose stack     at isDepOptional (/usr/local/lib/node_modules/npm/lib/install/deps.js:398:27)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:414:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3417 verbose stack     at failedDependency (/usr/local/lib/node_modules/npm/lib/install/deps.js:430:9)
3418 verbose cwd /Users/gargs11/work/repo/PLATFORM/my-app
3419 verbose Darwin 16.7.0
3420 verbose argv "/usr/local/Cellar/node/10.5.0_1/bin/node" "/usr/local/bin/npm" "install" "--quiet"
3421 verbose node v10.5.0
3422 verbose npm  v6.1.0
3423 error Maximum call stack size exceeded
3424 verbose exit [ 1, true ]

**Comment by babysnakes** [comment]
Just in case it helps, I encountered the same error trying to pull `@xtuc/long@4.2.1` (as a dependency of different package) and it turned out I had `~/.npmrc` file that had some settings to use artifactory which for some reason interfered with pulling this package. renaming this file solved the issue (although it's not a permanent solution... )

**Comment by oleza** [comment]
This error is just killing me, i can't find the solution

**Comment by raDiesle** [comment]
not the case for me, still doesn't work

**Comment by fzxt** [comment]
@raDiesle Clearing `~/.npmrc` **completely** fixed it for me.

**Comment by daniele-pecora** [comment]
@fzxt Same here. Removing `~/.npmrc` solved it.
