### ISSUE TITLE
Error: ng g interface image => Invalid blueprint: interface

### ISSUE THREAD

**Issue by albanx** [angular/angular-cli#1224]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**MAC OSX Yosemite 10.10.5**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 0.0.39
node: 4.1.1
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng g interface image`

Just trying to generate an interface with the CLI. Not working.
Cheers
Thank you
Alban

**Comment by Splaktar** [comment]
@albanx Can you try with an updated CLI version like `1.0.0-beta.6` or `1.0.0-beta.8`?
