### ISSUE TITLE
Angular localhost server constantly reloading

### ISSUE THREAD

**Issue by mdewell** [angular/angular-cli#12240]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

$ npm --version
5.8.0

$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

ng serve --o

### The log given by the failure

// the whole site runs fine on the C-Drive but not from the D-drive
I am using Windows 10 and I have a development directory system on my D drive. This is a separate drive from the hidden AppData directory, in my C drive User's directory. I write my code, on the D drive directory, start the localhost server from there, and it appears to run fine, for a while, but after a random amount of time, it starts recompiling, and reloading pages. I tried moving my development directory back to my C drive, into my user directory there, and started the ng serve from the C drive directory, and it runs fine, without reloading all the time. I would think it would not matter where the code is at, but it appears to.

Note: I did move my Documents, and other personal data directories, by windows procedures, to the D drive. But I do not think this would matter.

### Desired functionality

I would hope that the web pages/TS code does not have to recompile constantly on a localhost server, when code is not on the same drive as the user's home directory.

**Comment by filipesilva** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to https://github.com/angular/angular-cli/issues/5368

**Comment by filipesilva** [comment]
Closing as inactive.
