### ISSUE TITLE
ng build --watch with hmr

### ISSUE THREAD

**Issue by junimohano** [angular/angular-cli#12257]
I can't find anywhere to use hmr on ng build --watch

There is no way to do that?

Using ng serve which loads on localhost has problem in my case so that I should've used ng build --watch.

I really need to have live loading with hmr on ng build --watch.

**Comment by Avinkav** [comment]
i'm no expert but the watch switch, watches changes and outputs to your output folder, it does not use webpack dev server therefore there is no hot module replacement.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
