### ISSUE TITLE
ng generate application [number] fails

### ISSUE THREAD

**Issue by duncanwerner** [angular/angular-cli#12251]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node 10.10.0, npm 6.4.1, ng 6.2.1, Windows 10

### Repro steps
ng generate application 200

### The log given by the failure
str.indexOf is not a function

### Desired functionality
Create a project named "200". Presumably whatever ng is using to parse arguments is interpreting the name "200" as a number, and the string method fails. I understand this is an edge case, but I would like to use a number as the application name (it's not actually 200). 

Note that quoting "200" still fails.

### Mention any other details that might be useful
Workaround is obviously to add some alpha characters to the name

**Comment by alan-agius4** [comment]
The name must be a valid HTML selector, and numeric values are not allowed.

In the beta version of the CLI this has been addressed to print a more meaningful error message 

```bash
 ng generate application 200
Project name "200" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.
```

Example
```bash
ng generate application foo
```
