### ISSUE TITLE
ng update and ng update --all do not agree with each other

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#12261]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 6.1.2
Node: 8.11.4
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.2
@angular-devkit/core         0.7.2
@angular-devkit/schematics   0.7.2
@schematics/angular          0.7.2
@schematics/update           0.7.2
rxjs                         6.2.2
typescript                   2.7.2
```

### Repro steps

```
ng update
ng update --all
```

### The log given by the failure

```
ng update                  
    We analyzed your package.json and everything seems to be in order. Good work!

~/_git/vikings  master ✗                                                           17h22m ⚑  
▶ng update --all            
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.10", would install "3.0.3").
Incompatible peer dependencies found. See above.
```

### Desired functionality

If `ng update` says it's all clear, then the `ng update --all` should agree. Not sure which is right.

**Comment by julianpoemp** [comment]
+1 I have the same problem

**Comment by billfranklin** [comment]
also getting 'unable to verify the first certificate' for packages like primeng that work fine in NPM but fail on 'ng update primeng'.  Something bad has happened to ng update.

**Comment by brianivander** [comment]
I have the same problem:
`Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=2.7.2 <2.10", would install "3.0.3")`

This might be the same issue: [(https://github.com/angular/angular-cli/issues/12243)]

How to fix this?

**Comment by Whiteseeker** [comment]
I just did: npm install -g typescript@latest
and then I could run the ng update --all without issue

**Comment by Whiteseeker** [comment]
instead of doing the ng update --all I.m running each update one by one:
ng update @angular/core 
[...]
It seems to be working so far ... weird

**Comment by jmbarnes1987** [comment]
@Whiteseeker,  I'm doing the same, but ng update is literally taking 20-30+min on each manual update. I found another issue that is closed and that issue essentially concluded: ng update is terrible in terms of performance and user experience, deal with it.

Are you having the same experience? It has taken me nearly the entire workday to update my project.

**Comment by mackelito** [comment]
Any updates to this old issue? :)
