### ISSUE TITLE
ng new creating a project with compilation errors

### ISSUE THREAD

**Issue by scott18891** [angular/angular-cli#12266]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Node v8.12.0
NPM 6.4.1
ng --version
Angular CLI: 6.2.1
Node: 8.12.0
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

OS
Windows 10

### Repro steps

Following the set up guide here:  https://angular.io/guide/quickstart

Step 1: Installed Angular CLI
Step 2: ng new my-app
Step 3: ng serve --open fails due to a compilation error.

### log
ERROR in C:/Users/Scott/Documents/Apps/my-app/src/main.ts
Module build failed (from C:/Users/Scott/Documents/Apps/my-a
Error: C:\Users\Scott\Documents\Apps\my-app\src\main.ts is m in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Scottar_compiler_plugin.js:753:23)
    at plugin.done.then (C:\Users\Scott\Documents\Apps\my-ap
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:
ERROR in C:/Users/Scott/Documents/Apps/my-app/src/polyfills.
Module build failed (from C:/Users/Scott/Documents/Apps/my-a
Error: C:\Users\Scott\Documents\Apps\my-app\src\polyfills.tsit is in your tsconfig via the 'files' or 'include' property
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Scottar_compiler_plugin.js:753:23)
    at plugin.done.then (C:\Users\Scott\Documents\Apps\my-ap
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:
i ｢wdm｣: Failed to compile.

### Desired functionality
Should generate a project template that compiles

### Mention any other details that might be useful
Running the command in Windows Command prompt fixed the issue. Running the command in bash breaks.  In Bash I was navigating to my-app via a symlink. Once I navigate directly to this folder it works.

I've installed and uninstalled and reinstalled the Angular CLI. So I don't know what I am doing wrong :(

**Comment by scott18891** [comment]
Update: I found the issue. For whatever reason if you try to run ng serve --open on a project that you navigated to through a symlink it fails. I have nod idea why and I don't know if this is a bug with Angular CLI or not. Leaving this issue incase someone runs into the same thing.

**Comment by alan-agius4** [comment]
Hi, this seems to be because you have were not using `preserveSymlinks`, which is required when using symlinks so that the real path is not used when resolving modules, which is false by default.
