### ISSUE TITLE
Find the next free port when the specified one is taken

### ISSUE THREAD

**Issue by lazarljubenovic** [angular/angular-cli#12268]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

All

### Repro steps

- Have two apps.
- Run `ng serve` on both.
- One fails.

### The log given by the failure

`Port 4200 is already in use. Use '--port' to specify a different port.`

### Desired functionality

You don't usually care in development which port exactly it is as long as you can see which one it ended up running on. I shift a lot between apps on a daily basis and I'm getting the "already in use" error multiple times a day. Then I have to guess which port is free, which usually ends up a random number because chances are that half of 420x I've already taken.

### Mention any other details that might be useful

I think Vue's or React's CLI does it (can't remember which or if both), and it's a nice little feature.

There should probably also be a new flag for turning off this behavior for CIs or something where the porn could be important.

**Comment by clydin** [comment]
This is by design.  Generally, if the port is taken, it is something that should be investigated not ignored. If you would like to guarantee a free port is chosen pass `0` as the port number (`--port 0`).

**Comment by lazarljubenovic** [comment]
> it is something that should be investigated not ignored

There's nothing to investigate, it's just taken by another app. Will try out the `0` trick, didn't see it documente anywhere.
