### ISSUE TITLE
When running ng serve an error occurs: NgTools_InternalApi_NG_2 not found

### ISSUE THREAD

**Issue by Jeff-Kumar** [angular/angular-cli#12276]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: 8.11.4
NPM: 5.6.0
Angular CLI:  6.2.1

Running ng serve fails. 
 
### The log given by the failure
ERROR in node_modules/@angular/compiler-cli/index.d.ts(20,10): error TS2305: Module '"/opt/local/apache2/htdocs/angular-components/angular-project/node_modules/@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.

### Desired functionality
It should compile and run the test site successfully.

**Comment by alan-agius4** [comment]
This error is related to this issue 
https://github.com/angular/angular/issues/23112

However this shouldn’t happen on ng serve.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Closing as no further feedback received.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by akvaliya** [comment]
I am not sure why this is closed since it's clearly a bug. ngtools_api.d.ts does not have `NgTools_InternalApi_NG_2`.  It creates issue on ng serve & then it disappears when we have any file & code recompiled.

**Comment by exequielc** [comment]
same issue here with 

    "@angular/compiler": "7.2.0",
    "@angular/compiler-cli": "7.2.8",


when running  have this error on the console. 

Typescript Error
Module '"@angular/compiler-cli/src/ngtools_api"' has no exported member 'NgTools_InternalApi_NG_2'.



Please reopen this issue

**Comment by kirillgroshkov** [comment]
Same issue for us

**Comment by exequielc** [comment]
@kirillgroshkov  you should remove the  @angular/compiler-cli   imports.  And then it should work perfectly fine again. I my case that was the problem .

**Comment by kirillgroshkov** [comment]
@exequielc exactly, realized that just after some more digging. tnx!
