### ISSUE TITLE
How to create specific version of Angular using the CLI?

### ISSUE THREAD

**Issue by RaviGprec** [angular/angular-cli#12270]
![image](https://user-images.githubusercontent.com/35065303/45547739-6d3d8980-b83f-11e8-83b8-93a5111212f6.png)
Actually, my **npm vesrion is 5.5.1** and **angular-cli version is 6.2.1**
When I create a new project with the command **ng new ProjectName** . It is creating the latest angular project. i.e in my case **it is creating Angular version ^6.1.0**

Here my question is "**How to create a specific of angular project like 4, or 2 ,and not the latest angular like 6, using the angular cli?**"

I've tried searching answer for question everywhere. But no where I got the solution for this problem. I'm hoping here to get the answer.

Thanks in advance!!
Ravi Kumar

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by RaviGprec** [comment]
@alan-agius4 , Thanks for your comment and my apologies for opening this issue.

Solution can be found at : https://stackoverflow.com/questions/52331625/how-to-create-a-specific-version-of-angular-project-using-cli
