### ISSUE TITLE
Importing CLI project to another CLI project 

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#1228]
When I import a CLI based project into another CLI based project with this line in the angular-cli-build.js `'cb-vdl/src/**/*.+(html|css|js|js.map)',` the application works however all of the map files that were part of the original application begin to fail to be parsed.  I imported the project by running `tsc --declaration src/main.ts` in the first project. 

<img width="1171" alt="screen shot 2016-06-27 at 3 04 16 pm" src="https://cloud.githubusercontent.com/assets/2133184/16392281/1ce36d9a-3c79-11e6-98a2-972f0bad3544.png">

**Comment by filipesilva** [comment]
Can you try on the next release after #1455?

**Comment by filipesilva** [comment]
Closing as outdated.
