### ISSUE TITLE
ng config --global needs a project

### ISSUE THREAD

**Issue by anthonybriand** [angular/angular-cli#12296]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
* Node : 9.7.1
* Npm : 6.3.0
* Ng : 6.2.2
* macOS High Sierra : 10.13.6

### Repro steps
Install @angular/cli globally and run : 
```bash
ng config -g cli.packageManager yarn
# or
ng config cli.packageManager yarn -g
# or
ng config cli.packageManager yarn --global
```

### The log given by the failure
The command simply returns :
```
This command can only be run inside of a CLI project.
```

### Desired functionality
Before, this command doesn't needs a project to apply a global config.

**Comment by YuZaiShui** [comment]
Thanks very much.It's help for me.
