### ISSUE TITLE
"--watch" added to ng build [project]

### ISSUE THREAD

**Issue by cjonasw** [angular/angular-cli#12307]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
#### What would like to see implemented?
`--watch` added to `ng build [project]`

```ng build projectName --watch```

#### What is the usecase?

When building projects to be used in other apps, this command needs to be run manually each time.

**Comment by alan-agius4** [comment]
We are not understanding the issue here, as `ng build projectName --watch` already exists.

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by cjonasw** [comment]
@alan-agius4

**Comment by cjonasw** [comment]
Works in Angular 7+ FYI. Update all dependencies of course.
