### ISSUE TITLE
Explicitly document the licence for the generated code

### ISSUE THREAD

**Issue by r3mi** [angular/angular-cli#12317]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc
```

### Versions

```
NPM 6.4.1
Angular CLI: 6.2.2
Node: 10.10.0
OS: darwin x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.2
@angular-devkit/core         0.8.2
@angular-devkit/schematics   0.8.2
@schematics/angular          0.8.2
@schematics/update           0.8.2
rxjs                         6.2.2
typescript                   2.9.2
```

### Repro steps
The licence for the generated code is not explicitly stated.
As there is no strong distinction between your templates and the generated files, we can implicitly assume that the generated code is MIT (same licence as `angular-cli`). But, being legal matters, it would be better to be explicit.

### Desired functionality

Add an explicit statement on the rights granted on the generated code (aka licence) e.g. at the end of your [README.md](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/README.md#license).

### Mention any other details that might be useful

many thanks for your efforts !

**Comment by alan-agius4** [comment]
Thanks for this request, but I am going to close it as there isn’t much interest from the community around this feature request.

Let’s reconsider it things change. Thanks.
