### ISSUE TITLE
Feature request to expose Webpack watchOptions.ignored for the build command

### ISSUE THREAD

**Issue by grantlucas** [angular/angular-cli#12313]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 6.2.2
Node: 8.12.0
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.3
@angular-devkit/build-angular     0.8.3
@angular-devkit/build-optimizer   0.8.3
@angular-devkit/build-webpack     0.8.3
@angular-devkit/core              0.8.3
@angular-devkit/schematics        0.8.2
@angular/cli                      6.2.2
@ngtools/webpack                  6.2.3
@schematics/angular               0.8.2
@schematics/update                0.8.2
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.19.1
```

### Repro steps

N/A

### The log given by the failure

N/A

### Desired functionality

The ability to set [Webpack's watchOptions.ignored](https://webpack.js.org/configuration/watch/#watchoptions-ignored) is greatly needed in order to run an Angular application properly within a Vagrant setup. As it is right now, with the `--poll` option set, CPU usage hovers around 80-90% while watching files. In all other Webpack setups I have running within Vagrant, I've always ignored `node_modules` with great success.

In my initial local testing I altered the watch options the build command uses to set ignored to `/node_modules/`.  After the changes, my VM's CPUs hovered around 5% usage. This showed that this could resolve my issue if that option's exposed.

### Mention any other details that might be useful

I've tried the following with little to no success:

- Using `nice` to reduce priority
- Increasing the poll time up to 5 seconds
- A combination of both `nice` and increased poll time

With a slow poll time, and nice, I was able to reduce CPU usage to about 60% but this was still vastly more than the 5% average I was seeing after adding `node_modules` to the ignored list.

#### My typical watch options

```
        watchOptions: {
            ignored: /node_modules/,
            aggregateTimeout: 300,
            poll: 1000
        },
```

Any help with this would be _greatly_ appreciated.

**Comment by miladfm** [comment]
+1

**Comment by altinselimi** [comment]
I am also in dire need of this API inside angular-cli. I have a folder inside the project which modifies frequently, and that sucks performance and productivity wise.

**Comment by elixiao** [comment]
+1

**Comment by smallsong** [comment]
+1

**Comment by laser-me** [comment]
Maybe it is not direct solution of your case. But I switched off polling because of CPU overusage and heating. My machine is windows so polling was only solution to hot reload/recompile code. 

Instead I made use of File Watchers in IDE: https://stackoverflow.com/a/58429096/3012081

**Comment by dsebastien** [comment]
Same issue here under Kubernetes. The CPU usage is insane with polling enabled and without having the possibility to customize it to ignore at least node_modules

**Comment by alan-agius4** [comment]
Hi all, 

Since version 9.1 of the Angular CLI we automatically ignore `node_modules` when polling. 
See #16153 for more details.

Therefore, this request should no longer be required.   Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue.

Thanks.
