### ISSUE TITLE
Unable to install latest angular cli on using node v10.10.0

### ISSUE THREAD

**Issue by ajaypbarokar** [angular/angular-cli#12315]
Unable to install latest angular cli on using node v10.10.0

### Versions
 
C:\Users\ajay_barokar>node -v
v10.10.0

C:\Users\ajay_barokar>npm -v 
6.4.1
 
Windows  10

### Repro steps

Install Node version 10.10.0
Run below command :
npm install -g @angular/cli

### The log given by the failure

C:\Users\ajay_barokar>npm install -g @angular/cli
C:\Users\ajay_barokar\AppData\Roaming\npm\ng -> C:\Users\ajay_barokar\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm WARN rollback Rolling back node-pre-gyp@0.10.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Users\ajay_barokar\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\fsevents\node_modules'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@angular\cli\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @angular/cli@6.2.3
updated 1 package in 23.057s

C:\Users\ajay_barokar>ng -v
'ng' is not recognized as an internal or external command,
operable program or batch file.

### Desired functionality
Angular CLL should get install and ng command should work.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
