### ISSUE TITLE
Missing doc for angular builder

### ISSUE THREAD

**Issue by akisiel1** [angular/angular-cli#12318]
```
- [x] bug report 
- [ ] feature request
```

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc
```

Can you please provide some proper documentation to @angular-devkit/build-angular? I am working on an issue with e2e tests not being transpiled after I did an upgrade: https://stackoverflow.com/questions/52420169/e2e-typescript-tests-are-not-being-transpiled-after-angular-upgrade and current documentation is not really helpful: https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/README.md

**Comment by alan-agius4** [comment]
Hi, thanks for filing this issue. 

I checked your stackoverflow issue, and it seems that from the stacktrace you have a typescript error.

```bash
e2e/....e2e-spec.ts(27,111): error TS2322: Type '0' is not assignable to type '{ label: number; sent: () => any; trys: any[]; ops: any[]; }'.
```

Some docs about the various builds steps can be found here; https://github.com/angular/angular-cli/wiki

**Comment by akisiel1** [comment]
Hi @alan-agius4 !

Thanks for answering, but as I wrote it is not a problem of typescript error, because when I did a revert to Angular v5.4 all tests worked. Also I am pretty sure it is not a compilation error, because when I have changed 
`const { LoginWindow } = require('./e2e/loginWindow.po');` to be typescript, I got an error: ```[11:16:01] E/configParser - ...\e2e\loginWindow.po.ts:1
(function (exports, require, module, __filename, __dirname) { import { browser, element, by } from 'protractor';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module.m._compile (...\node_modules\ts-node\src\index.ts:439:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (...\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
An unexpected error occurred: undefined
```

Thank you for this readme :) I saw it, but it is also not much help, since I am looking for specific configuration for `@angular-devkit/build-angular:protractor` builder

**Comment by alan-agius4** [comment]
So the error that you are seeing is related to typescript being emitted with a module format of `es2015` instead of `common-js`. It looks like this might not be working as expected;
```ts
 beforeLaunch: function() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  },
```

I think the project path is incorrect here as it should be
```ts
 beforeLaunch: function() {
    require('ts-node').register({
      project: 'tsconfig.e2e.json'
    });
  },
```

That said, this doesn't look like it's an Angular-CLI issue. It's more the configuration and usage of `ts-node`

**Comment by akisiel1** [comment]
Thank you @alan-agius4 for help, but the path is right - my e2e tests, and ts.config are in `e2e` folder under `src`. I also saw that in #4737 and tried it before - didn't help. 

Still my main request is about the documentation. It would help a lot if we have it.

**Comment by akisiel1** [comment]
If someone would look for it, I have finally found json definition for options for [@angular-devkit/build-angular:protractor schema](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L1268-L1323) and for [@angular-devkit/build-angular:browser](https://github.com/angular/angular-cli/blob/v6.0.0-rc.8/packages/%40angular/cli/lib/config/schema.json#L521-L906)

**Comment by alan-agius4** [comment]
Closing.

As this is being tackled somewhere else.
https://github.com/angular/angular/pull/26484
