### ISSUE TITLE
ServiceWorker are not using --deploy-url (Followup issue from 9753)

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#12312]
This is a followup issue from https://github.com/angular/angular-cli/issues/9753

I tested my app with different configurations and below is my conclusion:

Using an HTML base HREF of https://cdn.domain.com and an Angular APP_BASE_HREF of / doesn't work.

Using an HTML base HREF of https://cdn.domain.com and dynamically setting Angular APP_BASE_HREF to mydomain.com works.

e.g.:

`environment.appBaseHref: window.location.protocol + "//" + window.location.hostname + (window.location.port ? ':' + window.location.port:'')`

`{ provide: APP_BASE_HREF, useValue: environment.appBaseHref }`

Though the second option works, but it introduces another issue, since we have now set the HTML base HREF to our CDN domain, this breaks other libraries that we are using. For example in my case
we are using other libraries such as Firebase Messaging for Push Notifications. When HTML base HREF is set to CDN it doesn't work.

I think we do need support for --deploy-url

So, when --deploy-url is provided, the urls generated in service worker should have the --deploy-url prepended to the assets.

**Comment by alan-agius4** [comment]
Closing as it doesn't follow the template.

Please file a new issue that follows the template. Thank you.

**Comment by naveedahmed1** [comment]
@alan-agius4 is it necessary to follow template even if its in continuation of an already marked as solved issue?

I mentioned that its followup issue from https://github.com/angular/angular-cli/issues/9753 which has been marked as solved, whereas the issue still exists.
