### ISSUE TITLE
Warn about state:new translations

### ISSUE THREAD

**Issue by lippoliv** [angular/angular-cli#12321]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
npm: 6.4.1
Angular CLI: 6.0.8
Node: 8.11.4
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

1. Make i18n running with your Project
1. Provide at least two translations (master and some other language)
1. For easyer usage, use ngx-i18nsupport (xliffmerge) to merge Translation-changes to the xlf files
1. Generate and translate all xlf files
1. Add a new Translation
1. Run xliffmerge to get your files updated (`<target state="new" />`)

### Desired functionality

At this Point it would be really nice, to be able (like missing translations) to let the build process file out an warning OR error out compleetly.

For Projects with multiple languages and thousands of strings, this would help making sure that all translations are done.

**OF course** we can "just don't use xliffmerge". But then we have a lot of work-overload to make sure the translations got transferred in all files.
Second thought on this: Why do we have a state Attribute on "target", if there is no way to let the CI handle this value...

**Comment by alan-agius4** [comment]
Hi @lippoliv,  it sounds like you use the `i18nMissingTranslation` option to show warnings or errors for missing translations.

See: https://angular.io/cli/build
