### ISSUE TITLE
When ngcli will support Angular RC2?

### ISSUE THREAD

**Issue by fedojo** [angular/angular-cli#1232]
Ive got a question about support of RC2 version. When ng cli will support it? Or maybe there is another way to add this support int projects based on ng cli?

Thanks in advance for answer
Kind regards

**Comment by elvirdolic** [comment]
If you look to the commit log, you will see that the current version already supports rc3

https://github.com/angular/angular-cli/commit/cbe6a2eb88ae6a20401fc4ba8f0e0d3d29ec11a3

**Comment by neekers** [comment]
I have rc3 installed and it works great!

**Comment by fedojo** [comment]
Thanks for help!
