### ISSUE TITLE
Cannot use same target name in angular.json for multiple projects

### ISSUE THREAD

**Issue by EricABC** [angular/angular-cli#12320]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report
```

### Command (mark with an `x`)
```
- [ X ] build
- [ X ] serve
```

### Versions

7.0.0-beta.3 and 4.

### Repro steps

Using an angular.json with multiple projects sharing the target name (ie, 'serve' and 'build' under the 'architect' node) will cause this error, even when specifying the project (ie. not a multiTarget).  A recent change [here](https://github.com/angular/angular-cli/commit/c72c45f9db5c09ed3099e62d7a74c6bc47c70ef6#diff-49c59d4b23aaa32fbbf5f84864e50b1fR98) caused this regression.  It will give the error 'Could not determine a single project for the 'serve' target.' from within the call to getProjectNamesByTarget(), even though I have specified the project.

```json
  "projects": {
    "stuff": {
      "architect": {
        "build": {

        }
      }
    },
    "morestuff": {
      "architect": {
        "build": {
```

### The log given by the failure

Error: Could not determine a single project for the 'serve' target.
    at ServeCommand.getProjectNamesByTarget (/Stuff/Spore/Typescript/node_modules/@angular/cli/models/architect-command.js:167:19)
    at ServeCommand.initialize (/Stuff/Spore/Typescript/node_modules/@angular/cli/models/architect-command.js:75:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:11)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)
### Desired functionality

Ability to still use the same target names, 'build', 'serve', etc... across numerous projects in the same angular.json.  A workaround is to use unique names.

**Comment by alan-agius4** [comment]
The error is indicated that it cannot locate a single project when you use `build` and `run` Thus in order to use the these builders you'd need to provide the project name as an argument.

Ex;
```
$ ng serve morestuff 
```

**Comment by EricABC** [comment]
Yup.  This error occurs even when that is done.

**Comment by EricABC** [comment]
@alan-agius4 can you please reopen?

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
I checked a bit regarding this, and it seems it happens when you don't have a `defaultProject` set.

**Comment by EricABC** [comment]
I can, if you give me a min.  getProjectNamesByTarget() is designed to get the default project for all non multiTargets (which this is).  target will be set to 'build' or 'serve' and there is no check to see if targetSpec.project is set.

**Comment by EricABC** [comment]
err...ya, ok ill skip the repro unless you poke me again.

**Comment by EricABC** [comment]
Oh, and its not the defaultProject, because I do have that set. (theres also another issue with that i think).  Its that targetSpec.project.
