### ISSUE TITLE
build documentation

### ISSUE THREAD

**Issue by boicetomlin** [angular/angular-cli#12324]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node v10.0.0, npm 5.6.0, cli 6.1.5

### Repro steps

documentation on build has --output-hashing as an option but does not specify possible values.  if you specify --output-hashing without a value you get an error that says you must use one of the "allowed values" but doesn't say what those allowed values are.  This same scenario is true for a lot of the build options.

### Desired functionality

Complete documentation with flags and possible and values.

**Comment by alan-agius4** [comment]
Fixed in https://angular.io/cli/build
