### ISSUE TITLE
NG6 - ngsw doesn't work offline

### ISSUE THREAD

**Issue by renatomullerventura** [angular/angular-cli#12329]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Win 10
Angular CLI: 6.2.2
Node: 8.11.2
npm: 5.6.0
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.2
@angular-devkit/build-angular     0.8.2
@angular-devkit/build-optimizer   0.8.2
@angular-devkit/build-webpack     0.8.2
@angular-devkit/core              0.8.2
@angular-devkit/schematics        0.8.2
@angular/cdk                      6.4.7
@angular/cli                      6.2.2
@angular/material                 6.4.7
@angular/pwa                      0.8.2
@ngtools/webpack                  6.2.2
@schematics/angular               0.8.2
@schematics/update                0.8.2
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.19.0

### Repro steps
To reproduce this bug you can:
 - npm install -g @angular/cli@latest
 - ng new project 
 - ng add @angular/material
 - ng add @angular/pwa
 - ng build --prod

I did some lazy load but I think it doesn't matter...

### The log given by the failure
When I refresh the browser on offline mode, none of my files stay on cache. The service worker ngsw-worker.js get registered normally online andit seems that cache some of my *.js and *.css files, but not my main.js or index.html. And then, again, offline it caches nothing.

I would like to solve this by not creating my own sw.js, but I am new at angular and I think it is the only way for now.

![onlinemode](https://user-images.githubusercontent.com/1858987/45843813-f567d700-bcf6-11e8-9cc3-047ed63a5dad.PNG)

![offlinemode](https://user-images.githubusercontent.com/1858987/45843812-f567d700-bcf6-11e8-9075-04be014f2033.PNG)

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by renatomullerventura** [comment]
Hi @alan-agius4, there's no problem. I setted up a github and start the code on a server, in case you want to see it running.

That's my repository: [Repo](https://github.com/renatomullerventura/repro-app-ng6-pwa)
And that's where the code is running rigth now [Link](https://renato-lobito.000webhostapp.com/)

Thanks for the answer =D

**Comment by renatomullerventura** [comment]
Anyone?
@alan-agius4 can you help me?

**Comment by ganySA** [comment]
@alan-agius4  - did you manage to fix this? I have exactly the same issue.

**Comment by renemarty** [comment]
I also have the same issue... any news on this? I disconnect from Internet, refresh and get a page load error and nothing works...

**Comment by srikanthwevio** [comment]
I have also same issue with offline mode  I am using angular 7 project in to pwa .in offline mode only works with /index.html
