### ISSUE TITLE
ng update advice incorrect. ng update @angular/cli does nothing

### ISSUE THREAD

**Issue by PooperPig** [angular/angular-cli#12348]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node --version
v10.3.0
npm --version
6.4.1
 ng --version
Your global Angular CLI version (6.2.3) is greater thanyour local
version (6.0.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _ ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| ||_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | | | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.0
Node: 10.3.0
OS: darwin x64
Angular: 6.0.0
... cli, common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.0
@angular-devkit/build-angular      0.6.0
@angular-devkit/build-ng-packagr   0.6.0
@angular-devkit/build-optimizer    0.6.0
@angular-devkit/core               0.6.0
@angular-devkit/schematics         0.6.0
@angular/animations                6.0.1
@angular/cdk                       6.0.2
@angular/material                  6.0.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.0
@schematics/angular                0.6.0
@schematics/update                 0.6.0
ng-packagr                         3.0.0-rc.3
rxjs                               6.1.0
typescript                         2.7.2
webpack                            4.6.0

### Repro steps
Existing ng 6 CLI project with three projects (one app and two libraries)
following output from ng update
```
 ng update
Your global Angular CLI version (6.2.3) is greater than your local
version (6.0.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       6.0.0 -> 6.2.3           ng update @angular/cli
      @angular/core                      6.0.0 -> 6.1.8           ng update @angular/core
      @angular/material                  6.0.2 -> 6.4.7           ng update @angular/material
      rxjs                               6.1.0 -> 6.3.2           ng update rxjs


    There might be additional packages that are outdated.
    Or run ng update --all to try to update all at the same time.

$ ng update @angular/cli
Your global Angular CLI version (6.2.3) is greater than your local
version (6.0.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
            Found a modern configuration file. Nothing to be done.

```

### Desired functionality
ng update @angular/cli should update to the version as indicated by the ng update command.

**Comment by markgoho** [comment]
Still broken in ng7 and cli v7.

ng update yields:
``` bash
We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       6.4.7 -> 7.0.1           ng update @angular/cdk
      @angular/cli                       6.1.2 -> 7.0.3           ng update @angular/cli
      @angular/core                      6.1.10 -> 7.0.1          ng update @angular/core
      @angular/material                  6.4.7 -> 7.0.1           ng update @angular/material
      @ngrx/store                        6.0.1 -> 6.1.0           ng update @ngrx/store
      rxjs                               6.2.2 -> 6.3.3           ng update rxjs
```

running `ng update @angular/cli` yields:
`Found a modern configuration file. Nothing to be done.`
With no packages being updated

**Comment by mackelito** [comment]
Remove node_modules and try again

**Comment by blogcraft** [comment]
ng update has never worked as it should...

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
