### ISSUE TITLE
Libraries added to other Library with npm install <folder> does not compile

### ISSUE THREAD

**Issue by KrauseStefan** [angular/angular-cli#12340]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Windows: 10 1709
node: v8.9.4
npm: 5.6.0
ng: 6.2.3
@angular-devkit/build-ng-packagr: 0.8.2           
ng-packagr: 4.2.0           

### Repro steps
Create two library modules with the ng cli tool, in separate work spaces (module a and b).
Build module b.
Use npm to reference module b build output form module a using the folder path. (`npm install <pathOtherModuleBuildOutput>`.)
Npm creates a symbolic link when you do this.
Add module b as an import to module a.
build module a.

I've created a small repository that reproduces the issue here
https://github.com/KrauseStefan/ng-packagr-symlink-issue

### The log given by the failure
```
Building Angular Package
Building entry point 'a'
Compiling TypeScript sources through ngc

BUILD ERROR
Error during template compile of 'NgModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
: Unexpected value 'BModule in C:/git/symlink-error/subModule/dist/b/b.d.ts' imported by the module 'AModule in C:/git/symlink-error/mainModule/projects/a/src/lib/a.module.ts'. Please add a @NgModule annotation.

Error: Error during template compile of 'NgModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called.
: Unexpected value 'BModule in C:/git/symlink-error/subModule/dist/b/b.d.ts' imported by the module 'AModule in C:/git/symlink-error/mainModule/projects/a/src/lib/a.module.ts'. Please add a @NgModule annotation.

    at Object.<anonymous> (C:\git\symlink-error\mainModule\node_modules\ng-packagr\lib\ngc\compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at C:\git\symlink-error\mainModule\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\git\symlink-error\mainModule\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (C:\git\symlink-error\mainModule\node_modules\ng-packagr\lib\ngc\compile-source-files.js:17:12)
    at Object.<anonymous> (C:\git\symlink-error\mainModule\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at C:\git\symlink-error\mainModule\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
```

### Desired functionality
Building libraries depending on other libraries through a npm install created symlink

### Mention any other details that might be useful
It will be great for this to work in order to prevent excessive copying of files. I'm looking into creating a build environment where we are able to build our modules separately, I would like to maintain as fast build speeds as possible, this means that I would also like `ng build --watch` to still function but not be active on all modules. Symlinks with npm install <folder> is my first shot at this.

I belvie there should be a flag for library build just like there is for final browser builds, therefor I file this as a bug.

**Comment by alan-agius4** [comment]
This is most likely due to that you have multiple versions of angular packages due to the links. 

Most information here;
https://github.com/angular/angular-cli/blob/master/docs/documentation/1-x/stories/linked-library.md

**Comment by KrauseStefan** [comment]
I believe you are right that this might be because of duplicated packages, it disappears if I instead copy the dependency or extending every.
I would really love to avoid this, as I expect this library to be used from many applications/libraries, not necessarily situated in the same work space in our repo, this kind of setup seems to be supported by the `@angular-devkit/build-angular:browser` builder.

I did not debug too deeply into the AOT compiler, but I went the full trip for the Webpack source to discover a very simuler issue for `@angular-devkit/build-angular:browser`, there the problem was that the dependency was resolved to the place where the symbolic link points, thus replacing the `node_modules` folder and coursing two different instances of `@angular/core` to be loaded.

You refer to information about the `npm link` command, `npm install` is different in that the symlink is in your local repository and at least in my mind should pickup the context in which the link is placed.
If resolving the symlink dependencies in context of that link doesn't that just make symlinks useless even though this is the default way for npm to handle this.
 
Webpack has a `resolve.symlinks` flag that is mapped to `preserveSymlinks` for the `@angular-devkit/build-angular:browser` builder.
What I miss here is an option for the same thing with the `@angular-devkit/build-ng-packagr` builder.

I was in doubt if this should be regarded as an bug report or a feature request, I choose bug report for two reasons:
* Log output is very confusing
* I could find no documentation about a limitation for this even though this is the default way for npm to handle installations from a local folder.
* The feature is supported for `@angular-devkit/build-angular:browser` and therefore there is some consistency issue between the tools in the angular cli.

I might also not that the error message when this is seen from `@angular-devkit/build-angular:browser` is also less than help full See the readme in the repository that I created to reproduce this.
https://github.com/KrauseStefan/ng-packagr-symlink-issue/blob/master/mainModule/README.md

**Comment by KrauseStefan** [comment]
The status is still need more information is this still the case @alan-agius4 ?

**Comment by alan-agius4** [comment]
Can you try to use `preserveSymlinks` https://www.typescriptlang.org/docs/handbook/compiler-options.html in the library tsconfig?

**Comment by KrauseStefan** [comment]
Thank you, I am a little embarrassed that I missed that one, thank you.
