### ISSUE TITLE
how to install typescript

### ISSUE THREAD

**Issue by Sasibeeke** [angular/angular-cli#12342]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

**Comment by cedvdb** [comment]
yes

**Comment by Sasibeeke** [comment]
Any Command  for to install typescript?

**Comment by cedvdb** [comment]
@Sasibeeke google it

**Comment by Sasibeeke** [comment]
> @Sasibeeke google it
> 
> you can do `npm install typescrript -g`. -g means it will be installed on your computer and not just for the project


Thank u

**Comment by Sasibeeke** [comment]
Can i do paypal integration on localhost?when i am doing i got an error?


We aren't able to process your payment using your PayPal account at this time. Please go back to the merchant and try using a different payment method.
