### ISSUE TITLE
Deprecate --prod in favour of -c production

### ISSUE THREAD

**Issue by sarunint** [angular/angular-cli#12351]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

Currently, both `--prod` and `-c production` does the same thing. We should ditch `--prod` as `-c` is more general.

### Mention any other details that might be useful

This is clearly a breaking change.

**Comment by clydin** [comment]
It is a heavily used convince alias.  What would be the advantage to dropping it?

**Comment by michaeljota** [comment]
Does this actually does the same thing? I know `--prod` mode turns on the optimization for the package, and the `configuration` can do more than just optimize the bundle. I actually have a script to build an optimice bundle, but with the development configuration. So, I don't think this is actually an alias.

**Comment by clydin** [comment]
@michaeljota It does in 6.0+ wherein `--prod` is converted to `--configuration=production` internally and will override and `--configuration` option specified on the command line.

**Comment by clydin** [comment]
Closing as this is not something we are looking at doing at this point in time.

**Comment by michaeljota** [comment]
So I can set multiple configuration files? Cause I have this in cli@6.1 and is working fine. How to know that files are actually being used? Does it merge? Does it just ignore the `configuration=dev`?

**Comment by clydin** [comment]
Configuration merging has been proposed and may be implemented in the future.
However, currently `ng build --configuration=dev --prod` is equivalent to `ng build --configuration=production`.
