### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by KeshShan** [angular/angular-cli#12359]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node --version = 8.11.2
npm --version = 5.6.0
ng --version = 1.6.6

### Repro steps
Trying to run "ng test --code-coverage" on Jenkins causes this error.
PhantomJS is configured headless browser and it works fine in local environment

### The log given by the failure
> tempathic@1.3.0 test /var/lib/jenkins/jobs/AMAMS/jobs/SONAR-Frontend/workspace/web-app
> ng test --code-coverage

/var/lib/jenkins/jobs/AMAMS/jobs/SONAR-Frontend/workspace/web-app/node_modules/@angular/cli/bin/ng:8
const CliConfig = require('../models/config').CliConfig;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
npm ERR! weird error 8
npm ERR! not ok code 0
Build step 'Execute shell' marked build as failure
Finished: FAILURE

### Desired functionality
It should run the test and produce the coverage report

**Comment by alan-agius4** [comment]
Hi @KeshShan, are you sure you are running node 8.11.2 on genkins? The error seems to indicate otherwise. As that error is displayed in `node <=5` https://node.green/#ES2015-bindings-const

**Comment by KeshShan** [comment]
Hi @alan-agius4 Yes I am running node 8.11.2 Check below attached images 
![img_25092018_101030_0](https://user-images.githubusercontent.com/12506034/46031758-723fea00-c117-11e8-990e-ef1c1ba4e0d9.png)
![configuration](https://user-images.githubusercontent.com/12506034/46031776-7d931580-c117-11e8-99f7-6fd8ae131b62.PNG)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue, however this seems like an environment issue and is not caused by Angular CLI.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
