### ISSUE TITLE
As a CLI user, I want the doc command to guide me to the version of Angular I'm using

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#12365]
Right now the `ng doc` command uses the latest version of the doc. It would be nice to (acceptance criteria):

1. provide a flag to specify which version to use, and
2. by default, use the version of angular core that's installed in the project.

This way people can use the doc command with the version of angular.io they care about.

**Comment by cexbrayat** [comment]
This issue was partially fixed by #14788 as it's now possible to use:

```
ng doc --version 6 // opens v6.angular.io
ng doc --version next // opens next.angular.io
```

The second part of the issue requires to read the Angular version installed in the project.
@alan-agius4 @clydin What would you recommend to use to grab the Angular version in the `doc` command?

**Comment by mgechev** [comment]
`require('@angular/core').VERSION` seems the most accurate way to me.

**Comment by clydin** [comment]
I agree.  Wrap that in a try catch and use a split on the periods to extract the major version. Use the default domain if an exception occurs.

**Comment by cexbrayat** [comment]
Thanks for the feedback!

@LakhyariMs Would you like to give it a try and open a new PR with this? Or do you prefer that someone else does it?
