### ISSUE TITLE
Angular is not running using my updated node version

### ISSUE THREAD

**Issue by ShreeGiriKumar** [angular/angular-cli#12368]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node version under c:\program files\nodejs is 6.9.4  (couldn't uninstall due to lack of admin perm)

updated node under c:\user\node\ is 8.12.0 (installed myself without admin perm using a guidance mentioned in https://stackoverflow.com/questions/37029089/how-to-install-nodejs-lts-on-windows-as-a-local-user-without-admin-rights/37029090?noredirect=1#comment76298984_37029090) 

npm is 6.4.1
ng is 6.2.3
windows 7 Enterprise 64 bit

### Repro steps
created a new angular app using the updated node in command prompt navigating to installed folder path.
The new app with angular version 6.2.3 is created.
-->

### The log given by the failure
You are running version v6.9.4 of Node.js, which is not supported by Angular CLI
 v6. The official Node.js version that is supported is 8.9 and greater.
Please visit https://nodejs.org/en/ to find instructions on how to update Node.js.

### Desired functionality
I would expect it to somehow mention angular to make use of the updated node version

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
