### ISSUE TITLE
Universal that relies only on static web servers

### ISSUE THREAD

**Issue by asnowwolf** [angular/angular-cli#12366]
### Bug Report or Feature Request (mark with an `x`)
- [ ] bug report -> please search issues before submitting
- [x] feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Versions

6.2.2

### Repro steps

N/A

### The log given by the failure

N/A

### Desired functionality

Start the local SSR server, then use `wget -m` or `wget -m --adjust-extension` to grab the site and merge the html files corresponding to each route into the dist directory.
This way, we can deploy it to a static file server without the help of a server such as express or dotnet. For some small apps or sites with static content, this can significantly simplify deployment.
The target directory structure has two forms: `route/index.html` or `route`, the former is universal, but an extra `/` suffix is added; the latter requires the mime type to be configured on the server (but github pages already Supported).

### Mention any other details that might be useful

N/A

**Comment by alan-agius4** [comment]
From what you are explaining this can be done using the univeral prerender strategy.

https://github.com/angular/universal-starter/blob/master/prerender.ts

**Comment by asnowwolf** [comment]
Cool, thank you! 

should I use universal starter instead of Angular CLI?
