### ISSUE TITLE
ng serve failing after updating CLI to latest version

### ISSUE THREAD

**Issue by DeonBonthuys** [angular/angular-cli#12377]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.2.3
Node: 8.11.3
OS: win32 x64
Angular: 6.1.9
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect             0.8.3
@angular-devkit/build-angular     0.8.3
@angular-devkit/build-optimizer  0.8.3
@angular-devkit/build-webpack   0.8.3
@angular-devkit/core                    0.8.3
@angular-devkit/schematics         0.8.3
@angular/cli                                   6.2.3
@ngtools/webpack                        6.2.3
@schematics/angular                    0.8.3
@schematics/update                     0.8.3
rxjs                                                 6.3.3
typescript                                       2.9.2
webpack                                        4.20.2

### Repro steps

Updated local version of the CLI to the latest version and updated npm to latest.
Fixed all dependency errors it was complaining about and then update core to latest.

### The log given by the failure

91% additional asset processing scripts-webpack-plugin× ｢wdm｣: Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:675:18)
    at tryReadSync (fs.js:540:20)
    at Object.fs.readFileSync (fs.js:583:19)
    at Storage.provideSync (C:\Projects\Tradify\TradifyWeb2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:98:13)

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by matteo-mosca** [comment]
I am having the same issue. Upgrading from 0.8.1 to 0.8.3, building or serving with or without --aot give the error:

`Cannot find module 'merge-descriptors'`
If I proceed to add that module manually, I get another error:
`Cannot find module 'finalhandler'`
And then again:
`Cannot find module 'path-to-regexp'`
And again:
`Cannot find module 'methods'`
Yet again:
`Cannot find module 'content-disposition'`

Then I honestly stopped and reverted back to 0.8.1.

**Comment by DeonBonthuys** [comment]
> This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?
> 
> You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

Sure thing, i will get on that. If this does not work, i will share the full repo.

**Comment by ashishragpotra** [comment]
@DeonBonthuys I m facing the same error could you please point me to that line where u find the folder instead of file?
[angular.txt](https://github.com/angular/angular-cli/files/3125339/angular.txt)
