### ISSUE TITLE
Build library using watch mode without live-reload

### ISSUE THREAD

**Issue by softdays** [angular/angular-cli#12385]
### Command
```
build (library)
```

### Versions
Angular CLI: 6.2.3
Node: 8.12.0
OS: win10
Angular: 6.1.8
Npm: 6.4.1

### Desired functionality
**As a** developer, **I want** to build my library in watch mode without live-reload, **so that** I will not be bothered anymore by a double reload of my demo app.

### Usage context 
Here is my workaround to build both library and demo in watch mode using a single command:
```
"start": "npm run clean && run-p --race start:*",
"start:lib": "ng build mylibrary --watch",
"start:demo": "wait-on ./dist/mylibrary/package.json && ng serve"
```
plugins: [npm-run-all](https://github.com/mysticatea/npm-run-all) + [wait-on](https://github.com/jeffbski/wait-on)

### Any other details that might be useful
At the moment the command 
```
ng build my library --watch --live-reload=false
```
throws an error:
```
$ ng build mylibrary --watch --live-reload=false
Unknown option: '--liveReload'
```

**Comment by alan-agius4** [comment]
The library builder doesn’t have a live reload cause it doesn’t serve.

What I think is happening is that since ng-packagr writes the files to disk over a period of time instead of writing everything at the end is causing webpack to trigger twice.

**Comment by softdays** [comment]
Thanks for your feedback. Do you think I should fill another issue on the ng-packgr side?

**Comment by alan-agius4** [comment]
@softdays it would be better. Thanks.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of `ng-packgr` project or file an issue on their issue tracker.
