### ISSUE TITLE
Disable browser tools with webpack build

### ISSUE THREAD

**Issue by no-more** [angular/angular-cli#12393]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node: v8.9.4
npm: 6.4.0

Angular CLI: 6.2.1
Node: 8.9.4
OS: win32 x64
Angular: 6.1.4
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.0
@angular-devkit/build-angular      0.8.0
@angular-devkit/build-ng-packagr   0.8.0
@angular-devkit/build-optimizer    0.8.0
@angular-devkit/build-webpack      0.8.3
@angular-devkit/core               0.8.0
@angular-devkit/schematics         0.8.1
@angular/cdk                       6.4.6
@angular/cli                       6.2.1
@angular/compiler-cli              6.1.0
@angular/flex-layout               6.0.0-beta.17
@angular/language-service          6.1.0
@angular/material                  6.4.6
@angular/material-moment-adapter   6.4.6
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.0
@schematics/angular                0.8.1
@schematics/update                 0.8.1
ng-packagr                         4.1.0
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.19.0

### Desired functionality

I'm trying to build a monorepo which contains all the code for frontend(angular) and backend (node + typescript). I'm trying to switch from a all webpack build to a all angular-cli build (with "@angular-devkit/build-webpack:webpack" for backend builds)
But it seems even if using custom webpack config, the cli still applies some browser specific build step and I have the following errors: 
`Module not found: Error: Can't resolve 'utf-8-validate'`
`Module not found: Error: Can't resolve 'bufferutil'`
It would be great to be able to completely disable this in order to make the build process platform independent.

**Comment by mgechev** [comment]
Hey @no-more, this is outside the scope of the CLI but I'd strongly encourage you to follow the architect API that we're working on https://github.com/angular/angular-cli/pull/13463 as well as `ngx-build-plus`. Both provide extensibility points that you can use to introduce this extra piece of functionality.

**Comment by no-more** [comment]
Thanks, I'll keep an eye on this.
