### ISSUE TITLE
Output of webpack loader emitting ng-containers and structural directives significantly increases build time

### ISSUE THREAD

**Issue by meoblast001** [angular/angular-cli#12395]
### Bug Report or Feature Request
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

`node --version` = v10.11.0
`npm --version` = 6.4.1
Angular CLI: 6.1.4
Windows 10

### Repro steps

I've been using the plugin "actra-development-oss/ng-i18n-aot-loader" with Angular as a temporary workaround to the lack of runtime i18n, in a project which I'm building through Webpack's "@ngtools/webpack". The aforementioned plugin preprocesses Angular templates and XLIFF files to produce a new template with a sort of "switch-case" to dynamically switch languages at runtime. It does this by producing ng-containers at the root level of the template with structural directives to perform the selection (https://github.com/actra-development-oss/ng-i18n-aot-loader#example). After measuring build speed using speed-measure-webpack-plugin, I've noticed that the amount of languages used in a project does not affect the loader speed much, but significantly affects the Angular compiler run time. One additional language on a project with approximately 115 components can add minutes to the build time. Currently three languages are used (plus standard text, resulting in 4 of these ng-containers per template) and the build times have already exploded from about a minute to over 10 minutes. Under some circumstances I've even experienced heap out of memory errors.

### The log given by the failure

```
EXEC : FATAL error : Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

### Desired functionality

Ideally I would not expect additional ng-containers and structural directives at the root level of templates to cause the Angular compiler's runtime to explode in this way. If there is a caveat by which this performance hit is unavoidable with ng-containers and structural directives, then it would be nice to know what that caveat is so I can change the loader to not use them (and ideally avoid running into the same problem in other areas).

**Comment by alan-agius4** [comment]
I think this would need some reproductions to tackle this as it also dependents on the size of your templates.

However, I want to point out that I don't think this is the optimal approach to have a multilingual application. With this approach I see some cavets.

1. Slower builds times since there is more code to compile, remember in AOT HTML gets transformed to JS.
2. Larger bundle sizes.
3. Not scalable, as you will reach a point that you won't be able to add additional languages because it the final bundle size will be too big.

Personally I'd go a different approach using https://github.com/ngx-translate/core

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
