### ISSUE TITLE
Document how to build angular-cli source

### ISSUE THREAD

**Issue by MadfishDT** [angular/angular-cli#12401]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc
```

### Versions
node --version = v8.11.4
npm --version = 6.1.0
Angular CLI: 6.2.3
Windows 10, macOS(Sierra, High Sierra)

### Repro steps
angular-cli 6.2.x Readme file describe about build instruction for contributor, clone git-> npm install ->npm run build. but npm build make error and fail build. Document do not describe 'yarn' command

### The log given by the failure
```
Cannot find module 'license-webpack-plugin '
```

### Desired functionality
document describe build instruction like this
```
npm install -g yarn
npm yarn
npm install
npm run build
```

**Comment by noelmace** [comment]
I'm ok to do the required contributions after getting the right informations, as I encounter the same issue when trying to run build and test.

Not sure it's a Doc issue ... There seems to be some missing dependencies, along with problems with noImplicitAny.

https://github.com/angular/angular-cli/commit/cc15444615c32798ee09dcaf1f9500d5893b4dfa (https://github.com/angular/angular-cli/pull/11711) was ok at the time it was merged, so the modifications that are creating this issue have been done after that.

After trying to fix the most obvious errors (https://github.com/noelmace/angular-cli/commit/bbc8a28cbbfaccf945029be01a99b3ba5bf80fd4) I get the following output:

```
➜ npm run build

> @angular/devkit-repo@0.0.0 build /home/noel/git/hub/angular/angular-cli
> npm run admin -- build


> @angular/devkit-repo@0.0.0 admin /home/noel/git/hub/angular/angular-cli
> node ./bin/devkit-admin "build"

Cleaning...
  Removing dist/...
Generating JSON Schema....
Building...
packages/angular_devkit/build_angular/src/angular-cli-files/utilities/service-worker/index.ts:21:8 - error TS2307: Cannot find module '@angular/service-worker/config'.

21 } from '@angular/service-worker/config'; // tslint:disable-line:no-implicit-dependencies
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/angular_devkit/build_ng_packagr/src/build/index.ts:17:28 - error TS2307: Cannot find module 'ng-packagr'.

17 import * as ngPackagr from 'ng-packagr';
                              ~~~~~~~~~~~~

packages/angular_devkit/build_ng_packagr/src/build/index.ts:113:18 - error TS7006: Parameter 'e' implicitly has an 'any' type.

113           .catch(e => obs.error(e));
                     ~

scripts/create.ts:10:17 - error TS2307: Cannot find module '@angular/cli/lib/cli'.

10 import cli from '@angular/cli/lib/cli';
                   ~~~~~~~~~~~~~~~~~~~~~~

Command failed: node "/home/noel/git/hub/angular/angular-cli/node_modules/typescript/bin/tsc", "-p", "tsconfig.json"
STDOUT:
null
STDERR:
null
npm ERR! code ELIFECYCLE
npm ERR! errno 99
npm ERR! @angular/devkit-repo@0.0.0 admin: `node ./bin/devkit-admin "build"`
npm ERR! Exit status 99
npm ERR! 
npm ERR! Failed at the @angular/devkit-repo@0.0.0 admin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noel/.npm/_logs/2018-09-30T15_33_25_726Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 99
npm ERR! @angular/devkit-repo@0.0.0 build: `npm run admin -- build`
npm ERR! Exit status 99
npm ERR! 
npm ERR! Failed at the @angular/devkit-repo@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noel/.npm/_logs/2018-09-30T15_33_25_734Z-debug.log
```

**Comment by noelmace** [comment]
I'm ok to do the required contributions after getting the right informations, as I encounter the same issue when trying to run build and test and currently investigating this.

https://github.com/angular/angular-cli/commit/cc15444615c32798ee09dcaf1f9500d5893b4dfa (https://github.com/angular/angular-cli/pull/11711) was ok at the time it was merged, so the modifications that are creating this issue have been done after that (https://github.com/angular/angular-cli/commit/c729b0e7d9033ebd7928fc3653038d05dc952ca0#diff-928cd6b06b08c834e130799ab0191acf
to begin with).
