### ISSUE TITLE
ng build error

### ISSUE THREAD

**Issue by yonus** [angular/angular-cli#1241]
I try to build by using ng buid I get error as following:

Build failed.
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat 'typings'
    at Error (native)
    at Object.fs.lstatSync (fs.js:976:18)

angular-cli: 1.0.0-beta.8
node: 6.2.2
os: linux x64

**Comment by burhan** [comment]
In your project directory, run `npm run typings install`

**Comment by filipesilva** [comment]
There is some spurious problem with typings where it doesn't install for some reason, we're getting it across multiple projects for the last months. @burhan instructions should fix it.
