### ISSUE TITLE
--vendorChunk needs a way to exclude a namespace for first party content

### ISSUE THREAD

**Issue by httpete** [angular/angular-cli#12421]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

the option to create one vendor.js chunk is great, but we have a private company namespace @mycompany that we want to exclude.  In webpack I did this with a regular expression on the splitChunks config.

I really want all first and third party code to be in separate files in ANY chunk, not just this one.

```
      splitChunks: {
        chunks: 'all',
        cacheGroups: {
          vendor: {
            test: /[\\/]node_modules[\\/](?!@mycompany)/,
            name: "vendor",
            priority: 10
          }
        }
      }
```

**Comment by clydin** [comment]
Please note that the vendor chunk only exists to facilitate faster rebuilds during development.  It is not recommended in production scenarios as it can greatly increase the overall size of the application.

If customization of the webpack configuration is desired, please consider this third-party package: https://github.com/manfredsteyer/ngx-build-plus

**Comment by httpete** [comment]
Thank you @clydin I will look into this package.
