### ISSUE TITLE
error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by MubarakSULAYMAN** [angular/angular-cli#12422]
Trying to run "npm install -g @angular/cli" and having "npm ERR! request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line".

A complete log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose npm-session 96494b2e529de658
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 1556ms
10 verbose type system
11 verbose stack FetchError: request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line
11 verbose stack     at ClientRequest.req.on.err (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:182:13)
11 verbose stack     at onerror (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:100:9)
11 verbose stack     at callbackError (C:\Program Files\nodejs\node_modules\npm\node_modules\agent-base\index.js:122:5)
12 verbose cwd C:\Users\Mubarak\Documents\Screes
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
15 verbose node v10.11.0
16 verbose npm  v6.4.1
17 error request to http://registry.npmjs.org/@angular%2fcli failed, reason: error:0906D06C:PEM routines:PEM_read_bio:no start line
18 verbose exit [ 1, true ]

**Comment by clydin** [comment]
This appears to be a problem with Node.js/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
