### ISSUE TITLE
 --eval-source-map does not work correctly

### ISSUE THREAD

**Issue by dwadezp** [angular/angular-cli#12434]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

`node --version`
v8.11.3 

`npm --version`
5.6.0

`ng version`
```
Angular CLI: 7.0.0-rc.1
Node: 8.11.3
OS: darwin x64
Angular: 7.0.0-rc.0
```
### Repro steps
1. generate new project `ng new my-project`
2. Go to package.json and modify build command 
`"build": "ng build  --eval-source-map",`

### The log given by the failure
Source maps are broken - developer can see transpiled code https://drive.google.com/file/d/1C5PLWOAjFuhoEQtFYlMTD8o_1gM-r-9e/view?usp=sharing 

### Desired functionality
I would like to see correct source maps but i see them partially: i can see ts file but code is transpiled ( please see screenshot above )

**Comment by alan-agius4** [comment]
We should either change the underlaying devtool to `cheap-module-eval-source-map` or remove the option completely as initially this was an optimization for `Angular 4` with `Webpack 3`.

**Comment by dwadezp** [comment]
I need inline source maps because i'm concating main.js scripts.js into one file via gulp in order to use  it as webcomponent. What can you suggest me to use instead eval or inline source maps for my case?

**Comment by filipesilva** [comment]
Heya, the `--eval-source-map` option is mean to use the Webpack `eval` devtool as described in https://webpack.js.org/configuration/devtool/, which does not include original source quality sourcemaps.

Thus the option is working as intended and we're not looking to change its semantics. If you need to process the sourcemaps after creation there's a number of tools that let you concatenate files and include their sourcemaps. 

https://github.com/Rich-Harris/sorcery and https://github.com/mozilla/source-map come to mind, but you should be able to find a file concatenator that does it with more ergonomic usage.
