### ISSUE TITLE
when i use cli1.5.3 run ng test it tailed [object ErrorEvent] thrown

### ISSUE THREAD

**Issue by liliangce** [angular/angular-cli#12433]
my package.json:
     
  "name": "sta-easyui",
  "version": "1.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy.conf.json --poll=5000",
    "build": "ng build",
    "test": "ng test --watch --browsers Chrome --sourcemaps=false",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.1.2",
...

Your help will be my pleasure.

**Comment by liliangce** [comment]
and it don't given anymore info.

**Comment by alan-agius4** [comment]
Closing as it doesn't follow the template
