### ISSUE TITLE
Does Angular CLI 6.x support Angular 5.x

### ISSUE THREAD

**Issue by tkumark** [angular/angular-cli#12448]
I recently upgraded my project from Angular CLI 5.2 to 6. But I get the following error when I build

`ng build --configuration=qa`
From my understading Angular CLI 6 is supposed to be compatible with angular 5.2. I perfer not to roll back if it does support.

> ERROR in Either route or analyzedModules has to be specified!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
