### ISSUE TITLE
Launch site after ng serve?

### ISSUE THREAD

**Issue by nitro52** [angular/angular-cli#1245]
Is it possible to have ng serve launch your site after it starts up? I find this easier than having to copy the localhost with port address from the terminal and paste it into a new browser tab

**Comment by austin94** [comment]
This could be pretty easy to implement.  I've done this before with the OPN package [https://www.npmjs.com/package/opn](https://www.npmjs.com/package/opn).

There could be an additional flag on the serve command similar to the ones below:
- `ng serve --browser` to open the default browser
- `ng serve --browser=firefox` to open a specific browser

If anyone else thinks this is a good idea I may try a pull-request at this one.

**Comment by nitro52** [comment]
Being able to select a browser like you suggested would be a nice touch as well.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1081

**Comment by filipesilva** [comment]
Please feel free to continue the discussion and proposals in the other issue though!

**Comment by keepscoding** [comment]
@austin94 do you mind show how you implement OPN?

**Comment by austin94** [comment]
This conversation should probably be moved to the duplicate issue if that's still active, but from opn README https://www.npmjs.com/package/opn (or you can use the opn-cli package) we could just grab the port that it was started on and add the app name based off of a argument passed in.

`// specify the app to open in 
opn('http://localhost:3000', {app: 'firefox'});
opn('http://localhost:3000', {app: 'google chrome'});

// for default browser
opn('http://localhost:3000');
`

**Comment by keepscoding** [comment]
@austin94 where to add these code e.g. open default browser?

**Comment by craigcosmo** [comment]
Is it going to be implemented?

**Comment by austin94** [comment]
@craigcosmo the issue that this was duplicating had a PR associated with it that was merged in.  Not sure if the command is still valid, but you can try the -o flag? I would check in #1081
