### ISSUE TITLE
PWA App Build with element selectors in scss losing styles 

### ISSUE THREAD

**Issue by ianadavies** [angular/angular-cli#12459]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] build

```
### Repro steps
PWA App Build with element selectors losing styles 

Not sure if this is an ionic or Angular issue but problem happens without ionic build also

See 
https://stackoverflow.com/questions/52626827/ionic-4-angular-6-pwa-styles-not-working-broken/52631004#52631004

### Desired functionality
Styles to be shown for element selectors on PWA builds

**Comment by alan-agius4** [comment]
Closing as it doesn't follow the template.
