### ISSUE TITLE
dynamic import() doesn't work from Angular app

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#12467]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 6.1.2
Node: 8.9.4
OS: darwin x64
Angular: 6.1.1
... animations, common, compiler, compiler-cli, core, elements
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.2
@angular-devkit/build-angular     0.7.2
@angular-devkit/build-optimizer   0.7.2
@angular-devkit/build-webpack     0.7.2
@angular-devkit/core              0.7.2
@angular-devkit/schematics        0.7.2
@angular/cli                      6.1.2
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.1.2
@schematics/angular               0.7.2
@schematics/update                0.7.2
ng-packagr                        4.1.0
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.9.2
```

### Repro steps

`ng start`

From browser dev tools console:

`import('@angular/core')`

### The log given by the failure

```
Uncaught (in promise) TypeError: Failed to resolve module specifier '@angular/core'
```

### Desired functionality

Dynamic `import()` should work from an angular cli app.

### Mention any other details that might be useful

Information about dynamic `import()`:
https://developers.google.com/web/updates/2017/11/dynamic-import

The most obvious use case for this is to access symbols from the debugger console.

**Comment by clydin** [comment]
Dynamic imports in the usage outlined above are a function of the web browser.  You’re attempting to import a node module but that is only relevant on a platform that understands node modules (I.e., node.js).  Browsers have no such concept.  For a browser, the import needs to reference a file available to fetch from the server.
