### ISSUE TITLE
`ng new` failed after execute inside a folder with a README inside with the error `ERROR! myApp/README.md already exists. The Schematic workflow failed. See above.`

### ISSUE THREAD

**Issue by cancelajavi** [angular/angular-cli#12463]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version: v10.11.0

npm --version: 6.4.1

ng --version: 

Angular CLI: 7.0.0-rc.1
Node: 10.11.0
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.9.0-rc.1
@angular-devkit/core         7.0.0-rc.1
@angular-devkit/schematics   7.0.0-rc.1
@schematics/angular          7.0.0-rc.1
@schematics/update           0.9.0-rc.1
rxjs                         6.3.3
typescript                   3.1.1

### Repro steps

Just try to `ng new myApp` when myApp is a folder which contains a README

### The log given by the failure

> ? Would you like to generate a routing module? Yes
> ? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
> ERROR! siddng/README.md already exists.
> The Schematic workflow failed. See above.

### Desired functionality

I think it should ask if you want to overwrite it instead of stopping the execution of the command

Thanks for the help (:

**Comment by alexeagle** [comment]
It would be nice to ask, but ng new isn't run that often and it has been like this for a while so I don't think it's worth fixing.
