### ISSUE TITLE
ng update to v7rc has TypeScript dependency issue (v 6.0.5)

### ISSUE THREAD

**Issue by DeborahK** [angular/angular-cli#12464]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node 8.10.0
npm  6.2.0
Windows 10

Angular CLI: 6.0.5
Node: 8.10.0
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.5
@angular-devkit/build-angular     0.6.5
@angular-devkit/build-optimizer   0.6.5
@angular-devkit/core              0.6.5
@angular-devkit/schematics        0.6.5
@angular/cli                      6.0.5
@ngtools/webpack                  6.0.5
@schematics/angular               0.6.5
@schematics/update                0.6.5
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

ng update @angular/core @angular/cli --next

Sample repo: 
https://github.com/DeborahK/Angular-NgRx-GettingStarted/tree/master/APM-Demo4

When I run the `ng update` command against this repo, I get the error indicated in the log below and the `ng update` does not run.

### The log given by the failure

Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.1.1 <3.2", would install "2.7.2")
Incompatible peer dependencies found. See above.

### Desired functionality

Should successfully run `ng update`

### Mention any other details that might be useful

The package-lock.json file for this version includes the following:

```
    "@schematics/angular": {
      "version": "0.6.5",
      "resolved": "https://registry.npmjs.org/@schematics/angular/-/angular-0.6.5.tgz",
      "integrity": "sha512-oB9j+IqVtoSn3kEV6mnBslG8pxaOlUW2Kw7aCVf9DzEqTZEH5awKuPuhRkAVyiXdwHPDn21xoUGVRLy4y/BafA==",
      "dev": true,
      "requires": {
        "@angular-devkit/core": "0.6.5",
        "@angular-devkit/schematics": "0.6.5",
        "typescript": ">=2.6.2 <2.8"
      }
    },
```

If I manually change the `typescript` line to this:

`"typescript": ">=2.6.2 <2.10"`

It executes `ng update` as expected.

**Comment by noelmace** [comment]
I think you should always update the cli first with `npm i @angular/cli --next` and then update other packages. I don't think this should be considered as an issue, but I may be wrong. At least we should document it.

Doing so in your project, it worked perfectly (tested with ng serve), see the PR above :wink: 

BTW, an error message is still occurring when doing so:
``` 
ng update @angular/cli --next
Your global Angular CLI version (7.0.0-rc.1) is greater than your local
version (6.0.5). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
    Updating package.json with dependency @angular/cli @ "7.0.0-rc.1" (was "6.0.5")...
UPDATE package.json (1502 bytes)
npm WARN bootstrap@4.1.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.1 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 56 packages from 65 contributors, removed 2 packages, updated 6 packages and audited 21888 packages in 6.439s
found 21 vulnerabilities (9 low, 5 moderate, 7 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Invalid rule result: Function().
```

**Comment by alexeagle** [comment]
I think @StephenFluin will explain how the upgrade process works, in the past we were careful to say which order to update things in.

**Comment by noelmace** [comment]
It seems like the issue was in with the packages order (trying to upgrade angular before the CLI). Do you think the CLI should reorder them internally or it's just a doc issue ?

**Comment by rattkin** [comment]
Every time I try to update anything, I run into snags similar to this one.
It's not a insurmountable problem, I wish there was just single command which would update all the things. What is the best way to update ng and npm?
