### ISSUE TITLE
(node:1679) UnhandledPromiseRejectionWarning: Error: Exited with code 3

### ISSUE THREAD

**Issue by camillevillnv** [angular/angular-cli#12469]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node--version: v10.3.0
npm --version: 6.1.0
ng --version:

Angular CLI: 6.0.8
Node: 10.3.0
OS: linux x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, co
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
--------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   **error**
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

Tried to run ng serve --open

### The log given by the failure

(node:1679) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/var/www/sms-client/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
(node:1679) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not h
(). (rejection id: 1)
(node:1679) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Desired functionality

Be able to successful serve angular application.

### Mention any other details that might be useful

node_modules/@angular-devkit/build-optimizer is missing files like a /src folder, after comparing with other working projects

**Comment by alan-agius4** [comment]
Have you tried remove the node_moduels and install them again?

**Comment by camillevillnv** [comment]
@alan-agius4 Yes, several times. 

The problem I encounter is that I can't delete the .bin folder under node_modules, and now also under @angular-devkit/build-angular/node_modules.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
