### ISSUE TITLE
Nothing happens when execute ng e2e myproject-e2e

### ISSUE THREAD

**Issue by mouf13** [angular/angular-cli#12475]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Node : v8.9.3
npm : 6.1.0
Angular CLI: 7.0.0-rc.1
Node: 8.9.3
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              7.0.0-rc.1
@angular-devkit/schematics        7.0.0-rc.1
@angular/cli                      7.0.0-rc.1
@ngtools/webpack                  6.2.4
@schematics/angular               7.0.0-rc.1
@schematics/update                0.9.0-rc.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.20.1

### Repro steps
just try to run ng e2e myproject-e2e

### The log given by the failure
No log, no trace, nothing

### Desired functionality
Launch my project e2e tests

**Comment by alan-agius4** [comment]
Can you please try to update the devkit packages from `0.8.4`to `0.9.0-rc.1`?

**Comment by mouf13** [comment]
Thanks @alan-agius4 it's works
