### ISSUE TITLE
Build failing after updating to the latest version

### ISSUE THREAD

**Issue by borntodesign** [angular/angular-cli#1247]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX Yosemite

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

v6.1.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I was trying to upgrade the cli because my vendor folders was not being created. Part of a larger issue where I am trying to upgrade to using the new firebase console and the latest version of angularfire2.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

`bay-publishing-magazine-cms@0.0.0 /Users/lorne/projects/bay-publishing-magazine-cms
├── UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.3
├── @angular/forms@0.1.1 
├── @angular/http@2.0.0-rc.3 
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0-rc.3
├── UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.0.0-rc.3
├── @angular/router@3.0.0-alpha.7 
├── codelyzer@0.0.20 
├─┬ karma@0.13.22
│ └─┬ chokidar@1.6.0
│   └─┬ fsevents@1.0.12 
│     ├── nan@2.3.5 
│     └─┬ node-pre-gyp@0.6.25 
│       ├─┬ mkdirp@0.5.1 
│       │ └── minimist@0.0.8 
│       ├─┬ nopt@3.0.6 
│       │ └── abbrev@1.0.7 
│       ├─┬ npmlog@2.0.3 
│       │ ├── ansi@0.3.1 
│       │ ├─┬ are-we-there-yet@1.1.2 
│       │ │ └── delegates@1.0.0 
│       │ └─┬ gauge@1.2.7 
│       │   ├── has-unicode@2.0.0 
│       │   ├─┬ lodash.pad@4.1.0 
│       │   │ ├── lodash.repeat@4.0.0 
│       │   │ └── lodash.tostring@4.1.2 
│       │   ├── lodash.padend@4.2.0 
│       │   └── lodash.padstart@4.2.0 
│       ├─┬ rc@1.1.6 
│       │ ├── deep-extend@0.4.1 
│       │ ├── ini@1.3.4 
│       │ ├── minimist@1.2.0 
│       │ └── strip-json-comments@1.0.4 
│       ├─┬ request@2.69.0 
│       │ ├── aws-sign2@0.6.0 
│       │ ├─┬ aws4@1.3.2 
│       │ │ └─┬ lru-cache@4.0.1 
│       │ │   ├── pseudomap@1.0.2 
│       │ │   └── yallist@2.0.0 
│       │ ├── bl@1.0.3 
│       │ ├── caseless@0.11.0 
│       │ ├─┬ combined-stream@1.0.5 
│       │ │ └── delayed-stream@1.0.0 
│       │ ├── extend@3.0.0 
│       │ ├── forever-agent@0.6.1 
│       │ ├─┬ form-data@1.0.0-rc4 
│       │ │ └── async@1.5.2 
│       │ ├─┬ har-validator@2.0.6 
│       │ │ ├─┬ chalk@1.1.3 
│       │ │ │ ├── ansi-styles@2.2.1 
│       │ │ │ ├── escape-string-regexp@1.0.5 
│       │ │ │ ├─┬ has-ansi@2.0.0 
│       │ │ │ │ └── ansi-regex@2.0.0 
│       │ │ │ ├── strip-ansi@3.0.1 
│       │ │ │ └── supports-color@2.0.0 
│       │ │ ├─┬ commander@2.9.0 
│       │ │ │ └── graceful-readlink@1.0.1 
│       │ │ ├─┬ is-my-json-valid@2.13.1 
│       │ │ │ ├── generate-function@2.0.0 
│       │ │ │ ├─┬ generate-object-property@1.2.0 
│       │ │ │ │ └── is-property@1.0.2 
│       │ │ │ ├── jsonpointer@2.0.0 
│       │ │ │ └── xtend@4.0.1 
│       │ │ └─┬ pinkie-promise@2.0.0 
│       │ │   └── pinkie@2.0.4 
│       │ ├─┬ hawk@3.1.3 
│       │ │ ├── boom@2.10.1 
│       │ │ ├── cryptiles@2.0.5 
│       │ │ ├── hoek@2.16.3 
│       │ │ └── sntp@1.0.9 
│       │ ├─┬ http-signature@1.1.1 
│       │ │ ├── assert-plus@0.2.0 
│       │ │ ├─┬ jsprim@1.2.2 
│       │ │ │ ├── extsprintf@1.0.2 
│       │ │ │ ├── json-schema@0.2.2 
│       │ │ │ └── verror@1.3.6 
│       │ │ └─┬ sshpk@1.7.4 
│       │ │   ├── asn1@0.2.3 
│       │ │   ├─┬ dashdash@1.13.0 
│       │ │   │ └── assert-plus@1.0.0 
│       │ │   ├── ecc-jsbn@0.1.1 
│       │ │   ├── jodid25519@1.0.2 
│       │ │   ├── jsbn@0.1.0 
│       │ │   └── tweetnacl@0.14.3 
│       │ ├── is-typedarray@1.0.0 
│       │ ├── isstream@0.1.2 
│       │ ├── json-stringify-safe@5.0.1 
│       │ ├─┬ mime-types@2.1.10 
│       │ │ └── mime-db@1.22.0 
│       │ ├── node-uuid@1.4.7 
│       │ ├── oauth-sign@0.8.1 
│       │ ├── qs@6.0.2 
│       │ ├── stringstream@0.0.5 
│       │ ├── tough-cookie@2.2.2 
│       │ └── tunnel-agent@0.4.2 
│       ├─┬ rimraf@2.5.2 
│       │ └─┬ glob@7.0.3 
│       │   ├─┬ inflight@1.0.4 
│       │   │ └── wrappy@1.0.1 
│       │   ├── inherits@2.0.1 
│       │   ├─┬ minimatch@3.0.0 
│       │   │ └─┬ brace-expansion@1.1.3 
│       │   │   ├── balanced-match@0.3.0 
│       │   │   └── concat-map@0.0.1 
│       │   ├─┬ once@1.3.3 
│       │   │ └── wrappy@1.0.1 
│       │   └── path-is-absolute@1.0.0 
│       ├── semver@5.1.0 
│       ├─┬ tar@2.2.1 
│       │ ├── block-stream@0.0.8 
│       │ ├─┬ fstream@1.0.8 
│       │ │ └── graceful-fs@4.1.3 
│       │ └── inherits@2.0.1 
│       └─┬ tar-pack@3.1.3 
│         ├─┬ debug@2.2.0 
│         │ └── ms@0.7.1 
│         ├─┬ fstream-ignore@1.0.3 
│         │ └─┬ minimatch@3.0.0 
│         │   └─┬ brace-expansion@1.1.3 
│         │     ├── balanced-match@0.3.0 
│         │     └── concat-map@0.0.1 
│         ├─┬ once@1.3.3 
│         │ └── wrappy@1.0.1 
│         ├─┬ readable-stream@2.0.6 
│         │ ├── core-util-is@1.0.2 
│         │ ├── isarray@1.0.0 
│         │ ├── process-nextick-args@1.0.6 
│         │ ├── string_decoder@0.10.31 
│         │ └── util-deprecate@1.0.2 
│         └── uid-number@0.0.6 
├─┬ protractor@3.3.0
│ └─┬ request@2.67.0
│   └─┬ http-signature@1.1.1
│     └─┬ sshpk@1.8.3
│       ├── ecc-jsbn@0.1.1 
│       ├── jodid25519@1.0.2 
│       ├── jsbn@0.1.0 
│       └── tweetnacl@0.13.3 
└── tslint@3.11.0 

npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/common@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/compiler@2.0.0-rc.2 but none was installed.
npm WARN angularfire2@2.0.0-beta.2 requires a peer of @angular/platform-browser-dynamic@2.0.0-rc.2 but none was installed.
bay-publishing-magazine-cms $ sudo ng firebase:deploy
(node:17912) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
The specified command firebase:deploy is invalid. For available options, see `ng help`.
bay-publishing-magazine-cms $ ng build -prod
(node:17916) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Build failed.
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/advert/advert.component.ts (2, 10): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'OnActivate'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/advert/advert.component.ts (2, 22): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'RouteSegment'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/comment/comment.component.ts (2, 10): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'OnActivate'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/comment/comment.component.ts (2, 22): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'RouteSegment'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/image/image.component.ts (2, 10): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'OnActivate'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/image/image.component.ts (2, 22): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'RouteSegment'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/text/text.component.ts (2, 10): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'OnActivate'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/text/text.component.ts (2, 22): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'RouteSegment'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/video/video.component.ts (2, 10): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'OnActivate'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/articles/video/video.component.ts (2, 22): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'RouteSegment'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/auth/auth.service.ts (3, 29): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'Routes'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/bay-publishing-magazine-cms.component.ts (2, 29): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'Routes'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/users/users-form/edit-user-form.component.ts (2, 37): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'OnActivate'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/users/users-form/edit-user-form.component.ts (2, 49): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'RouteSegment'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/users/users-form/users-form.component.ts (2, 37): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'OnActivate'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/app/users/users-form/users-form.component.ts (2, 49): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'RouteSegment'.
  /Users/lorne/projects/bay-publishing-magazine-cms/tmp/broccoli_type_script_compiler-input_base_path-rBHW1qjX.tmp/0/src/main.ts (3, 10): Module '"/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/@angular/router/index"' has no exported mng 'ROUTER_PROVIDERS'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/lib/broccoli/angular2-app.js:321:18)
    at Angular2App._buildTree (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/lib/broccoli/angular2-app.js:116:23)
    at new Angular2App (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23)
    at module.exports (/Users/lorne/projects/bay-publishing-magazine-cms/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/build.js:15:19)
    at /Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/lib/commands/build.js:32:24
    at lib$rsvp$$internal$$tryCatch (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/lorne/projects/bay-publishing-magazine-cms/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)`

5. Mention any other details that might be useful.

I feel out of my depth with when it goes wrong with dependencies and build errors.

**Comment by houssemzaier** [comment]
try to run " npm run typings install"
from your **project directory**

**Comment by borntodesign** [comment]
I got it working in the end, the upgrade change my package file meaning that it was now using the new router. Also I did npm uninstall angular-cli -g then an npm i -g angular-cli and that seemed to patch a few things up so I am fully upgraded on all fronts. Feeling fresh now.

**Comment by alazzawimahmoud** [comment]
Hey guys, I'm having the same issue with these settings:

Windows 10
angular-cli: 1.0.0-beta.8
node: 4.4.5
os: win32 x64

```
C:\projects\ng2MobileTest>ng build
```

```
Build failed.
```

```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  C:/projects/ng2MobileTest/tmp/broccoli_type_script_compiler-input_base_path-Y3oPHGr5.tmp/0/src/system-config.ts (33, 3): ',' expected.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (C:\projects\ng2MobileTest\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:120:19)
    at BroccoliTypeScriptCompiler.build (C:\projects\ng2MobileTest\node_modules\angular-cli\lib\broccoli\broccoli-typescript.js:43:10)
    at C:\projects\ng2MobileTest\node_modules\angular-cli\node_modules\broccoli-caching-writer\index.js:152:21
    at lib$rsvp$$internal$$tryCatch (C:\projects\ng2MobileTest\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\projects\ng2MobileTest\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\projects\ng2MobileTest\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\projects\ng2MobileTest\node_modules\angular-cli\node_modules\broccoli-caching-writer\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

```


![image](https://cloud.githubusercontent.com/assets/11873646/16521412/fb20545e-3f96-11e6-8a35-0011e7ed7cb4.png)

@houssemzaier I tried this, I got this and it didn't solve the issue, so am I missing something here??

![image](https://cloud.githubusercontent.com/assets/11873646/16521936/a600a114-3f9a-11e6-838a-11019ba0a21a.png)

Thanks!

**Comment by filipesilva** [comment]
@alazzawimahmoud it seems you have a missing comma in `src/system-config.ts`:

`C:/projects/ng2MobileTest/tmp/broccoli_type_script_compiler-input_base_path-Y3oPHGr5.tmp/0/src/system-config.ts (33, 3): ',' expected.`

**Comment by alazzawimahmoud** [comment]
@filipesilva Thank your very much, it is working perfectly.
