### ISSUE TITLE
Wrong merge assets folders

### ISSUE THREAD

**Issue by WuglyakBolgoink** [angular/angular-cli#12489]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 6.2.4
Node: 10.11.0
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cli                      6.2.4
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.19.1
```

### Repro steps
I try to **merge** default `assets/images` folder with custom customer folder `src/customers/A/assets/images`. 
```
"assets": [
                            {
                                "glob": "favicon.ico",
                                "input": "src/customers/A/",
                                "output": "/"
                            },
                            {
                                "glob": "**/*",
                                "input": "src/assets/images",
                                "output": "/assets/images"
                            },
                            {
                                "glob": "**/*",
                                "input": "src/customers/A/assets/images",
                                "output": "/assets/images"
                            }
                        ]
```
`/src/assets/images` folder has default `bg-login.jpg` image, after `ng build` I have same image in `/dist` folder.

 
### Desired functionality
as I understand, the files will be copy be `index` in `assets`-list. Also first `ng` copy files from default folder, and after copy files from customer folders, and **if `dist` folder has same files, this files should be `replaced` with a new files**

Do I something wrong or need I another option like `'force:true'`

----

`dirty fix` is using `fileReplacements` list. But if I have to much files in both folders this cost many time to support a multiple customers (min 10x)

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

That said, coping of files happens asynchronously.
