### ISSUE TITLE
Best practice to copy a contents of a folder into another

### ISSUE THREAD

**Issue by enricosecondulfo** [angular/angular-cli#12504]
Hello guys,
i'm creating a custom builder and i need to copy a contents of a folder into another. What's the best practice to archive that?

Thank you

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by enricosecondulfo** [comment]
Sorry
