### ISSUE TITLE
Order of Module attributes inconsistent between default and generated

### ISSUE THREAD

**Issue by marlowp** [angular/angular-cli#12509]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 6.2.4
Node: 10.6.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cdk                      6.4.5
@angular/cli                      6.2.4
@angular/material                 6.4.5
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps

The default module created using `ng new` creates a module whose first attribute is `declarations` followed by `imports`, when you generate a new module using `ng generate module` the order of attributes is `imports` followed by `declarations`.

### Desired functionality

The order should be consistent.

### Mention any other details that might be useful

Looks like either of the following files needs updating:
- https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/application/other-files/app.module.ts
- https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/module/files/__name%40dasherize%40if-flat__/__name%40dasherize__.module.ts

**Comment by ZionDials** [comment]
I created a pull request for this and made them match for file generation. Thanks  [https://github.com/angular/angular-cli/pull/12528]

**Comment by inthevortex** [comment]
Has this issue been resolved?
