### ISSUE TITLE
Module not found: Error: Can't resolve '.'

### ISSUE THREAD

**Issue by Muhammad-Soban** [angular/angular-cli#12523]
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Versions
`node 10.11.0`, `npm 6.4.1`, `ng 6.2.4` and `Windows 10`.
* **Data Table Version:** 
"@swimlane/ngx-datatable": "^13.1.0"
```
Angular CLI: 6.2.4
Node: 10.11.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cli                      6.2.4
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps
**Current behavior**
it is working fine if build it using ng serve and ng build --prod. But I am facing issues when I build it for server side rendering with angular universal. I am using following commands to build
```
npm run build:ssr
```
ERROR in ./dist/server/main.js
Module not found: Error: Can't resolve '.' in 'C:\Users\me\Desktop\example\dist\server'
 @ ./dist/server/main.js 96:17-29
 @ ./server.ts
```
npm run serve:ssr
```
> example@0.0.0 serve:ssr C:\Users\me\Desktop\example
> node dist/server

C:\Users\me\Desktop\example\dist\server.js:54955
module.exports = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module '.'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
                                                                                                                                                   ^

Error: Cannot find module '.'
    at webpackMissingModule (C:\Users\me\Desktop\example\dist\server.js:54955:82)
    at Object.. (C:\Users\me\Desktop\example\dist\server.js:54955:158)
    at __webpack_require__ (C:\Users\me\Desktop\example\dist\server.js:54879:30)
    at Object../node_modules/@swimlane/ngx-datatable/release/utils/tree.js (C:\Users\me\Desktop\example\dist\server.js:62913:10)
    at __webpack_require__ (C:\Users\me\Desktop\example\dist\server.js:54879:30)
    at Object../node_modules/@swimlane/ngx-datatable/release/utils/index.js (C:\Users\me\Desktop\example\dist\server.js:62194:10)
    at __webpack_require__ (C:\Users\me\Desktop\example\dist\server.js:54879:30)
    at Object../node_modules/@swimlane/ngx-datatable/release/components/header/header-cell.component.js (C:\Users\me\Desktop\example\dist\server.js:59818:15)
    at __webpack_require__ (C:\Users\me\Desktop\example\dist\server.js:54879:30)
    at Object../node_modules/@swimlane/ngx-datatable/release/components/header/header-cell.component.ngfactory.js (C:\Users\me\Desktop\example\dist\server.js:60109:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! example@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the example@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\me\AppData\Roaming\npm-cache\_logs\2018-10-06T07_02_52_121Z-debug.log

**Desired functionality**
Create ssr build without errors.

**Reproduction of the problem**
I have created a test project to reproduce the issue. Following is the  github link.
https://github.com/Muhammad-Soban/ngx-datatable-ssr-issue.git

**Comment by filipesilva** [comment]
Hi, I was able to use your repro to see the following error when running `npm run build:ssr`:
```
ERROR in ./dist/server/main.js
Module not found: Error: Can't resolve '.' in 'D:\sandbox\ngx-datatable-ssr-issue\dist\server'
 @ ./dist/server/main.js 96:17-29
 @ ./server.ts
```

However, looking over your `webpack.server.config.js`, I notice it is different from the one in our guide: https://github.com/angular/angular-cli/wiki/stories-universal-rendering#webpackserverconfigjs-root-project-level. I tried using that one and didn't see the first error.

But I also notice that your `src/server.ts` is different from the one in our guide. I'm not sure which guide you are using, but I suggest you use our official one.
