### ISSUE TITLE
 `ng new` should error on multiple args

### ISSUE THREAD

**Issue by vikerman** [angular/angular-cli#12549]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
v7.0.0-rc.2

### Repro steps
Running `ng new` with extra args doesn't throw an error. This could happen when user forgets to put --directory

```shell
ng new hello test/path/hello
```
Should display an error. Instead it just creates a new directory hello/ and continues without any errors.

### Desired functionality
Display error message about extra args

**Comment by alan-agius4** [comment]
Apparently even invalid arguments are not erroring our example

`ng new my app —foo`
