### ISSUE TITLE
Cannot update to 1.0.0-beta.8

### ISSUE THREAD

**Issue by nunoarruda** [angular/angular-cli#1254]
1. OS?  Mac OSX El Capitan 10.11.5

2. Versions. 

`ng --version`
`````
module.js:442
    throw err;
    ^

Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/leek/lib/leek.js:3:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
````

`node --version`
`v6.2.2`


3. Repro steps.
`npm install -g angular-cli`


4. The log given by the failure.

`````
- inquirer node_modules/angular-cli/node_modules/inquirer
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.2
npm ERR! path /usr/local/lib/node_modules/.staging/abbrev-432cdd5a
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-432cdd5a' -> '/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/.staging/abbrev-432cdd5a' -> '/usr/local/lib/node_modules/angular-cli/node_modules/ember-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nunoarruda/npm-debug.log
npm ERR! code 1
````

**Comment by flyer1** [comment]
Dup #1242

**Comment by filipesilva** [comment]
Dupe https://github.com/angular/angular-cli/issues/1186
