### ISSUE TITLE
Javascript error on 'generate' command 

### ISSUE THREAD

**Issue by zaerl** [angular/angular-cli#12544]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: `v10.11.0`
NPM: `6.4.1`
ng:
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.2.4
Node: 10.11.0
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cli                      6.2.4
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps

Run (exactly) `ng generate module`

### The log given by the failure

`Cannot read property 'match' of undefined`

### Desired functionality

The `generate` command and other commands (`ng generate class`, `ng generate directive` etc.) that accept a third argument should output an informative text like the one generated when only the first argument is passed. E.g. the output of `ng generate`

`The "ng generate" command requires a schematic name to be specified. For more details, use "ng help".`

A valid error could be something like this:

`The "ng generate module" command requires a module name to be specified. For more details, use "ng generate module --help".`

### Mention any other details that might be useful

Maybe this issue exists in all commands.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this. But this has already been fixed in master and is available in version 7.

**Comment by zaerl** [comment]
Thank you for your time, I had not noticed a previous issue closed on master. Sorry, my bad.
