### ISSUE TITLE
Guide on Compiling Third Party UMD Modules 

### ISSUE THREAD

**Issue by sqwk** [angular/angular-cli#1255]
Is there a a guide for compiling third party libraries using browserify that are written in ES6 for use with the Angular CLI?

Currently any modules that I am trying to bundle can not be found by the cli when bundling them like this:

    "dist:lib-es6": "rollup --format cjs src/foo.js --output dist/foo.rollup.js && browserify dist/foo.rollup.js --standalone Foo > dist/foo.es6.js"

**Comment by filipesilva** [comment]
I am not aware of any documentation about that, no. In case it helps, SystemJS is what ultimately loads the modules. Perhaps the configuration issue is there.
