### ISSUE TITLE
test.ts should contain // tslint:disable:ordered-imports

### ISSUE THREAD

**Issue by vovikdrg** [angular/angular-cli#12550]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Command (mark with an `x`)
```
- [ x] new
```

### Desired functionality
TSLint has feature for auto fixing. And in our project we do have check for ordered-imports, and after I did save my test.ts by adding new code tslint reordered my imports which cause failure for test fakeAsync. While import order is important there is not information about that in file. There is also issue which was solved https://github.com/angular/angular/issues/11317. 

To prevent this type of issues would be nice to update test.ts file when you create a project with disabling tslint rule for this case.

**Comment by vovikdrg** [comment]
If its get approved I can make a PR

**Comment by alan-agius4** [comment]
This rule doesn't come by default when create a new application. 

Thus, I don't think we should disable rules that have been might be added by consumers. In that case it is up to the consumer to decide were a rule needs to be disabled and if it should be disabled at all.

**Comment by vovikdrg** [comment]
@alan-agius4  But then how to avoid problem like this? When I did run my tests it shows me error without any clue what is wrong.

**Comment by Akxe** [comment]
@alan-agius4 It might not, but since, if someone does `ng new`, edits `tslint` (spaces to tabs, imports order), and then run `ng lint`, it will just break without the user ever knowing what happened, it is the only file where imports have meaning side effects. This gave us a headache for a few days
