### ISSUE TITLE
ng serve --open does not work

### ISSUE THREAD

**Issue by camillevillnv** [angular/angular-cli#12551]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

npm-v

> 6.1.0

ng-v

> Angular CLI: 6.0.0
> Node: 10.3.0
> OS: linux x64
> Angular: 6.0.0
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.6.0
> @angular-devkit/build-angular     0.6.0
> @angular-devkit/build-optimizer   0.6.0
> @angular-devkit/core              0.6.0
> @angular-devkit/schematics        0.6.0
> @ngtools/webpack                  6.0.0
> @schematics/angular               0.6.0
> @schematics/update                0.6.0
> rxjs                              6.1.0
> typescript                        2.7.2
> webpack                           4.6.0

### Repro steps

Running ng serve --open on Windows Powershell inside a docker container.

### The log given by the failure

It compiles successfully but it doesn't open a browser. When I try to go to localhost:4200, I get an **ERR_CONNECTION_REFUSED** error.

When I exit/do CTRL + C, I get this error:

> Error: Exited with code 3
>   at ChildProcess.cp.once.code (.../node_modules/opn/index.js:84:13)
>   at Object.onceWrapper (events.js:273:13)
>   at ChildProcess.emit (events.js:182:13)
>   at maybeClose (internal/child_process.js:961:16)
>   at Socket.stream.socket.on (internal/child_process.js
>   at Socket.emit (events.js:182:13)
>   at Pipe._handle.close [as _onclose] (net.js:596:12)

### Desired functionality

Should open a browser or browser tab upon command execution.

### Mention any other details that might be useful

This only seems to happen on Windows Powershell. When I try to do this using Git bash, it works. 

On Git bash:
npm -v
> 5.5.1

ng -v 

> Angular CLI: 6.0.0
> Node: 8.9.1
> OS: win32 x64
> Angular: 6.0.0
> ... animations, cli, common, compiler, compiler-cli, core, forms
> ... http, language-service, platform-browser
> ... platform-browser-dynamic, router
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.6.0
> @angular-devkit/build-angular     0.6.0
> @angular-devkit/build-optimizer   0.6.0
> @angular-devkit/core              0.6.0
> @angular-devkit/schematics        0.6.0
> @ngtools/webpack                  6.0.0
> @schematics/angular               0.6.0
> @schematics/update                0.6.0
> rxjs                              6.1.0
> typescript                        2.7.2
> webpack                           4.6.0
>

The last major change I remember making before this happened was accidentally deleting the `assets` folder under `src`. When I tried to run it the first time I encountered an error:

> fs.js:948
>   binding.stat(pathModule._makeLong(path));
> 
> Error: ENOENT: no such file or directory, stat '..\src\assets'
>     at Object.fs.statSync (fs.js:948:11)

I brought the `assets` folder back and that's when the issue with `ng serve --open` failing to open started to happen.

**Comment by filipesilva** [comment]
I'm not really sure that running ng serve --open on Windows Powershell inside a docker container should/can do anything at all.

The `--open` flag asks the environment to open `http://localhost:4200`, using whatever programs it has configured to open that address. 

If you are inside a container, you'd need a headless browser inside the container to possibly do something. Even then I'm not sure how that would look like. Opening a web address inside a container should definitely not open the browser of the host OS.

If you want to use the server inside the container you'll need to configure docker to bind a local port to a container port. https://docs.docker.com/v17.09/engine/userguide/networking/default_network/binding/ might help.

Either way though, we're really not looking to making the `--open` flag reach outside of containers to do things. That's just sounds like a huge security issue.
