### ISSUE TITLE
Warning about CircularJSON shown on 7.0.0-rc.2 new app

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#12555]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI 7.0.0-rc.2.

### Repro steps
```
npm install -g @angular/cli@7.0.0-rc.2
ng new my-app
```

### The log given by the failure
At the end of `ng new my-app`, 

```
> circular-json@0.5.7 postinstall C:\Users\kamik\AppData\Local\Temp\angular-cli-create-z0dWss\help-project\node_modules\circular-json
> echo ''; echo "\x1B[1mCircularJSON\x1B[0m is in \x1B[4mmaintenance only\x1B[0m, \x1B[1mflatted\x1B[0m is its successor."; echo ''

''; echo "\x1B[1mCircularJSON\x1B[0m is in \x1B[4mmaintenance only\x1B[0m, \x1B[1mflatted\x1B[0m is its successor."; echo ''
```

### Desired functionality
No odd messages on install.

### Mention any other details that might be useful
Circular JSON seems to be an indirect dependency of Karma 3:
```
$ npm list circular-json
help-project@0.0.0 C:\Users\kamik\AppData\Local\Temp\angular-cli-create-z0dWss\help-project
`-- karma@3.0.0
  `-- log4js@3.0.6
    `-- circular-json@0.5.7
```

Related to https://github.com/karma-runner/karma/issues/3169

**Comment by IgorMinar** [comment]
I filed an issue against circular-json to have the message removed. These kinds of messages are not something npm packages should issue via postinstall scripts because end users can't act on the message. https://github.com/WebReflection/circular-json/issues/50

**Comment by filipesilva** [comment]
With https://github.com/WebReflection/circular-json/issues/50 in, this should clear in a couple of days.
