### ISSUE TITLE
Component generation without spec file?

### ISSUE THREAD

**Issue by duncanhunter** [angular/angular-cli#1256]
Frequently we make components with no logic that we do not wish to write unit tests for. We would like to use the CLI to generate components with no spec file.

1. How do you use the generation feature of the CLI with out creating a spec file?

**Comment by kylecordes** [comment]
I think this is especially relevant for projects that follow the "smart component vs visual component" pattern. The purely visual components in such a design usually should not have anything in them worthy of a test.

**Comment by jschwarty** [comment]
Maybe an api like:

`ng g c new-component --nospec`

**Comment by LordJoStar** [comment]
to generate a component without a "...spec.ts" file you simply run "--spec false". Example below

ng g c testfile --spec false

**Comment by ARambazamba** [comment]
Would be nice to have a default for the whole project ... like only write —spec true when you want something testable

**Comment by Ranjita-M** [comment]
Hi there!!
Look at the default settings of component in **schema.json**(node_modules/@angular/cli/lib/config/schema.json) file. Change as required..

If you don't want to generate spec file, just make default property value to false..
"component":
 {
          "properties": 
{
            "spec":
 {
              "description": "Specifies if a spec file is generated.",
              "type": "boolean",
              "default": true
            }
          }
        }

**Comment by hayat12** [comment]
Hello, i am advancing you to create the component manually, most when we use **cli** we don't know what is the use of the generated files. and in case of you want to generate the file without spec you can use this `ng g component list --spec==false`

**Comment by amitarora1991** [comment]
you can use -S with command to skip the test files

**Comment by agupadilla** [comment]
> to generate a component without a "...spec.ts" file you simply run "--spec false". Example below
> 
> ng g c testfile --spec false

Option "spec" is deprecated: Use "skipTests" instead.

**Comment by aledroner** [comment]
Option "spec" is deprecated: Use "skipTests" instead. Example:
``ng g s my-service --skipTests``

**Comment by Yash-777** [comment]
#### application
```
ng generate application <name> [options]
```
| OPTION | DESCRIPTION |
| :-- | :-- |
| --skipTests=true\|false |When true, does not create "spec.ts" test files for the app.<br />Default: false<br />Aliases: -S |

#### [component](https://angular.io/cli/generate#component)
```
ng generate component <name> [options]
```
| OPTION | DESCRIPTION |
| :-- | :-- |
| --skipTests=true\|false | When true, does not create "spec.ts" test files for the new **`component`**/`directive`/**`class`**/`guard`.<br />Default: false |
| --spec=true\|false | _**Deprecated**_: Use "skipTests" instead.<br />When true (the default), generates a "spec.ts" test file for the new component.<br />Default: true |

---

Angular 2:
```
ng g c component-name --spec false
```
[angular-cli.json](https://github.com/Yash-777/AngularApp/blob/master/.angular-cli.json)
```json
"defaults": {
  "spec": {
    "class": false,
    "component": true,
    "directive": true,
    "module": false,
    "pipe": true,
    "service": true
  }
}
```

**Comment by mmmichl** [comment]
for consistency `angular.json` with angular cli 7:

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  ...
  "projects": {
    "your-app": {
      ...
      "schematics": {
        "@schematics/angular:component": {
          "inlineStyle": false,
          "spec": false
        }
      },
....
}
```

**Comment by life347** [comment]
@mmmichl Working Solution!

**Comment by ahadGitHub** [comment]
ng generate directive "directiveName" --skipTests
