### ISSUE TITLE
Get error when I try to create a new app

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular-cli#12560]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
6.2.4

### Repro steps
ng new myapp

### The log given by the failure
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/parser@^7.1.3
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/traverse'
npm ERR!

**Comment by alan-agius4** [comment]
This package was just published, and it might take time to propagate through caches & proxies.
