### ISSUE TITLE
ng serve doesn't consider the timezone when printing the output

### ISSUE THREAD

**Issue by nsebs** [angular/angular-cli#12562]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.2.4
Node: 8.12.0
Yarn: 1.10.1
OS: linux x64
Angular: 6.1.10

### Repro steps
`ng serve`

### The log given by the failure
As it's seen on the next image, the date on the machine and the date on the `ng serve` output differ (more precisely, the timezone is not being considered).

![screenshot from 2018-10-11 14-42-42](https://user-images.githubusercontent.com/35010914/46823590-f4115380-cd64-11e8-92fe-d35589933963.png)

### Desired functionality
The log should print the correct local date and time.

**Comment by clydin** [comment]
The time is in UTC notice the Z at the end of the time stamp.  This is intentional and intended.

**Comment by virajkanwade** [comment]
For somebody who still wants to override this:
`node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/stats.js`

replace `new Date().toISOString()` with `new Date().toString()`

**Comment by alexagranov7** [comment]
Is there any plan to have this configurable at least for all workspaces?
