### ISSUE TITLE
upgrade guide should mention to make sure all .json files are encoded in UTF8 without BOM

### ISSUE THREAD

**Issue by rekna1** [angular/angular-cli#12578]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps
I can happen that the editor (VScode) encodes files in UTF8 with BOM (don't know exactly when and why but in my cased it happened and I've seen reports of other people having the same issue

### The log given by the failure
Invalid JSON character: "﻿" at 0:0.

### Desired functionality
update the upgrade guide

### Mention any other details that might be useful
This might apply to any of the following files:
.angular-cli.json
package-lock.json
tslint.json
package.json
angular.json
compilerconfig.json
tsconfig.json

open each of these files in an editor (like notepad++) and convert to UTF8 without BOM if necessary

**Comment by alan-agius4** [comment]
Thanks for reporting this but I don’t think this needs to be added in the CLI documents as this is a JSON standard. 

JSON files should never have BOM https://tools.ietf.org/html/rfc7159#section-8.1

If you notice that your editor is adding BOMs in JSON files I suggest you open an issue in their issue tracker.

**Comment by rekna1** [comment]
While I agree it's not an issue of the angular-cli, I'm not sure what caused the change of UTF8 encoding, it happened without me being aware of it and I thought it might help other people who encounter this error...
