### ISSUE TITLE
Removing component through Angular CLI - 6.1.10

### ISSUE THREAD

**Issue by ahamedama** [angular/angular-cli#12576]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Versions
Not implemented upto the recent versions

### Desired functionality

Generating component is already equipped well. But deleting the component is also be a much-needed feature.

### Acceptance criteria
```
Deleting or removing means
-Remove the generated component files.
-Remove the references that made when generating the component files.
```

### Command should be or something like the below one
```
ng remove/rm 'specific.component'
```

**Comment by clydin** [comment]
Duplicate of #900
