### ISSUE TITLE
ng test --watch with karma autoWatch: false and singleRun: true does not execute tests

### ISSUE THREAD

**Issue by joostme** [angular/angular-cli#12570]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
OS: Windows 10

node --version
v8.12.0

npm --version
6.4.1

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.2.5
Node: 8.12.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.5
@angular-devkit/build-angular     0.8.5
@angular-devkit/build-optimizer   0.8.5
@angular-devkit/build-webpack     0.8.5
@angular-devkit/core              0.8.5
@angular-devkit/schematics        0.8.5
@angular/cli                      6.2.5
@ngtools/webpack                  6.2.5
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```
### Repro steps

When creating a new Angular project using `ng new` and then changing `autoWatch: false` and `singleRun: true` in the `karma.conf.js` running `ng test --watch` does not execute any tests.

### The log given by the failure

After running the command the execution stops after the following outputs. Karma window stays open.

No errors or other logs. Neither in the terminal nor in the console of the karma window.
```
ng test --watch
 10% building modules 2/2 modules 0 active12 10 2018 13:46:07.001:INFO [karma]: Karma v3.0.0 server started at http://0.0.0.0:9876/
12 10 2018 13:46:07.009:INFO [launcher]: Launching browser Chrome with unlimited concurrency
12 10 2018 13:46:07.131:INFO [launcher]: Starting browser Chrome                                                                                                                                                                             12 10 2018 13:46:19.156:INFO 
[Chrome 69.0.3497 (Windows 10 0.0.0)]: Connected on socket J__tQF9yHHlFQ-uiAAAA with id 86526619
```

### Desired functionality

Execute the tests in watch-mode.

### Mention any other details that might be useful

When setting `autoWatch: true` the test command works as expected. `ng test` runs tests once and `ng test --watch` executes them in watch-mode.

**Comment by alan-agius4** [comment]
@joostme, Thanks for reporting this, however you don't need to set `autoWatch` to `false` from your end when running `singleRun`. As `autoWatch` is get disabled internally in Karma when running a `singleRun` https://github.com/karma-runner/karma/blob/29523ff55567b1f7296bf3adc9c3a0f3088c94bd/lib/config.js#L175-L178

I have also looked into the issue a bit and this issue is not caused by Angular CLI. Please contact the author(s) of the Karma project or file an issue on their issue tracker.
