### ISSUE TITLE
3rd party lib can't find it's files

### ISSUE THREAD

**Issue by gooor** [angular/angular-cli#1258]
I have angular2-meteor - and it can't find it's files inside:
in angular-cli-build.js
```
'angular2-meteor/build/*.js',
'angular2-meteor-auto-bootstrap/build/bootstrap.js'
```

in system-config.ts
```
const map: any = {
  'angular2-meteor-auto-bootstrap': 'vendor/angular2-meteor-auto-bootstrap/build/bootstrap.js',
  'angular2-meteor': 'vendor/angular2-meteor/build/index.js'
};
```
And I receive error `vendor/angular2-meteor/build/mongo_cursor_observer 404 (Not Found)` (and many more for every import inside `angular2-meteor/build/indrex.js`)
Nothing I put in `const packages: any ` changes this  :(

Btw: why I need to do all this stuff - can't it just normally find those packages without me? It doesn't look good and adds more and more work for me ....

*Edit*
It looks like everything that has `__export(require('./some_dependency_name'));` inside does not work - garbage

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
