### ISSUE TITLE
Global config: allow setting the default style preprocessor for new projects

### ISSUE THREAD

**Issue by dennisheer** [angular/angular-cli#12583]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

#### `node --version`
```
v10.12.0
```

#### `npm --version`
```
6.4.1
```

#### `ng --version`
```
Angular CLI: 6.2.5
Node: 10.12.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.5
@angular-devkit/core         0.8.5
@angular-devkit/schematics   0.8.5
@schematics/angular          0.8.5
@schematics/update           0.8.5
rxjs                         6.2.2
typescript                   2.9.2
```

### Desired functionality

I would like to generate new projects with `scss` as a preprocessor by default (using `ng new`). I would like to configure this with `ng config --global`. Running `ng new` with no flags should create `scss` files.

### Mention any other details that might be useful

* I read through [documentation, stackoverflow and stories](https://github.com/angular/angular-cli/wiki/stories-css-preprocessors) and couldn't find a working answer.
* Running `ng new northwind --style scss` works as expected.
* #10774 is not working for me

`ng config` doesn't allow setting a default style preprocessor when generating projects with `ng new`. I found the `/usr/local/lib/node_modules/@angular/cli/lib/config/schema.json` shows the available JSON paths for `ng config`. It does not provide a configuration for setting the default style preprocessor.

This is my `~/.angular-config.json`:
```
{
  "version": 1,
  "schematics": {
    "@schematics/angular:component": {
      "styleext": "scss"
    }
  }
}
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by alan-agius4** [comment]
For the ng new schematics, you need to add the config to a different json path, which should be 
```cmd
 ng config --global schematics.@schematics/angular:ng-new.style styl
 ng new --noInteractive foo-barz --dryRun
```
