### ISSUE TITLE
No lazy modules are generated when @angular/core is external

### ISSUE THREAD

**Issue by sis0k0** [angular/angular-cli#12592]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Description
We've got a rather complicated scenario in NativeScript where we don't want to include `@angular/core` in the webpack bundle. Instead, that package is external. The structure of the build application is something like:
```
bundle.js                  <-- the bundled application
vendor.js                  <-- some plugins. @angular/* can't be here.
node_modules               <-- other plugins, including all @angular/* packages.
	@angular/core
	@angular/common
	nativescript-angular
	...	
``` 

We found out that this approach doesn't work with lazily loaded modules. We created and registered a custom `NgModuleLoader`. It is almost the same as the default `SystemJSModuleLoader`, but instead of being external, it is bundled together with the app.

However, the `AngularCompilerPlugin` doesn't generate any chunks for the lazy modules. We tracked the problem to this expression - https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L706, which expects the requests to come from `@angular/core`. However, in the described above setup, the request comes from the custom module loader. The plugin ignores the request and as a result, no lazy chunks are generated.

### Desired functionality

We need a way to make the application work with externalized `@angular/*` packages.
Even if we find a way to generate the lazy chunks, we may still need a `NgModuleLoader` bundled inside the application. If it's external, the `System.import`/`require` won't work, because the lazy chunks map is inside `bundle.js`.

### Versions
- node - v10.9.0
- npm - 6.4.1
- @angular/* - 6.1.10
- @ngtools/webpack - 6.2.5

### Repro steps
https://github.com/sis0k0/ns-preview-custom-loader

**Comment by FahdLihidheb** [comment]
I think it is currently impossible to remove or externalize the angular/core while keeping the lazy behaviour. as angular core is the parent of all lazy modules, externalizing it means externalizing all your lazy modules. see this [Using externals prevents splitting off lazy modules](https://github.com/angular/angular-cli/issues/11490)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
