### ISSUE TITLE
ng github-pages:deploy left the localproject on  gh-pages branch

### ISSUE THREAD

**Issue by xmlking** [angular/angular-cli#1259]
> ## Please provide us with the following information:
> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> 
> ```
> OSX -  El Capitan
> ```
1. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
       node --version
   And paste the result here.

```
(node:6824) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: darwin x64
```
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
2. The log given by the failure. Normally this include a stack trace and some
   more information.
3. Mention any other details that might be useful.
   
   > ---

After running `ng github-pages:deploy --message "Optional commit message"` command with no changes to code base, my local project is left on gh-pages branch. it should leave on master branch. 

> when it fails (it leaves in gp-pages branch) 

![image](https://cloud.githubusercontent.com/assets/627951/16513618/fe589c98-3f1a-11e6-8811-855650ec3b1c.png)

> when it works 

![image](https://cloud.githubusercontent.com/assets/627951/16541529/4b897ce2-403a-11e6-9ac1-6369eb03744c.png)

**Comment by cre8** [comment]
You have to add the `--user-page` parameter to push it to the master 

> This command pushes the app to the master branch on the github repo instead of pushing to gh-pages, since user and organization pages require this.

**Comment by xmlking** [comment]
@cre8 I don't want to push to master. I wanted to push to normal gp-pages branch. When it works , this commend brings back to master branch. But when it fails , it left my project directory at gp-pages branch. 
My point is this angular-cli commend should not leave the code in gp-pages branch state whether it succeed or fail. 

PS: I got email from github with title "[xmlking/parking] Page build failure". May be github had issues at that time.

**Comment by filipesilva** [comment]
@xmlking you're right, the command shouldn't leave your repo in the wrong branch. Will investigate.
