### ISSUE TITLE
Pipe generated transform method has wrong parameters

### ISSUE THREAD

**Issue by tchatel** [angular/angular-cli#12602]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
All versions are affected, including v7.0.0-rc.3.

### Repro steps
```
ng generate pipe ...
```

### Problem
The generated method _transform_ has wrong parameters. The second parameter, _args_, will not receive all the pipe arguments, but only the first one, and other arguments are lost.

The generated method is:
```
transform(value: any, args?: any): any {
  return null;
}
```
A right version should be:
```
transform(value: any, ...args: any[]): any {
  return null;
}
```

**Comment by alan-agius4** [comment]
Not sure about this, because I think in general it preferred to specify all the parameter needed.

Example;
```ts
 transform(value: any, argOne: number, argTwo?: number): any {
```

**Comment by tchatel** [comment]
Yes, I agree, you should always rewrite the method with meaningful parameters and right types, even the first one (value).
It's what I explain when I give Angular trainings. But I don't like having to tell that the generated code is wrong. Generated code should not be wrong, it should not mean that all the pipe arguments will be sent in the second method parameter, since it's not what happen.

Perhaps it may generate something like that:
```
transform(value: any, arg1: any, arg2: any): any {
```
or any other syntax that won't confuse the users.
