### ISSUE TITLE
Problem using esri library.

### ISSUE THREAD

**Issue by vivekimsit** [angular/angular-cli#1260]
```
angular-cli: 1.0.0-beta.8
node: 5.11.1
os: linux x64

```

I am following [this](https://github.com/tomwayson/angular2-esri-example) example but I am not able to make it work. I am getting erros something like:

`map.service.ts (2, 21): Cannot find module 'esri'`

**Comment by pavlos256** [comment]
https://github.com/tomwayson/angular2-esri-example/issues/16

**Comment by filipesilva** [comment]
Please see https://github.com/angular/angular-cli#3rd-party-library-installation for instruction on how to install 3rd aprty libs.

**Comment by vivekimsit** [comment]
@filipesilva already tried that, the issue is that it uses dojo and hence it gives error loading modules.

**Comment by tomwayson** [comment]
FYI in case anyone else comes across this, I've created a different repo that demonostrates how to use the ArcGIS API w/ angular-cli:

https://github.com/tomwayson/esri-angular-cli-example

For a more in depth reason behind why it doesn't work and the avaiable workarounds, see: 

http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/
