### ISSUE TITLE
ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' 

### ISSUE THREAD

**Issue by rameshpraja** [angular/angular-cli#12619]
Hello,
From Last week I found the below error, I have tried many things like update @angular/cli version but I am not able to resolved the production error.
my version :
Angular version - 4
"@angular/cli": "1.0.0",
"@angular/compiler-cli": "4.0.2"

Throwing below Error  while enter ng build --prod 
ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/user2/Project/Streetwork/streetworkapp/material/loan_calculator/src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts

Please help me how to fixed that issue ?

**Comment by alan-agius4** [comment]
Doesn't follow template
