### ISSUE TITLE
Angular CLI installing for long time (nearly a day)

### ISSUE THREAD

**Issue by senthil-wd** [angular/angular-cli#12617]
I installed Node v8.12.0-x86 version in my windows laptop, it has npm version of 6.4.1
When I install `npm install -g @angular/cli --loglevel verbose`, it stops at 
`npm http fetch GET 304 http://registry.npmjs.org/fsevents 436ms (from cache)`

No more action / update after that command. I am not sure what causing this issue and how to check it in logs. Please help.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
