### ISSUE TITLE
angular.json Scripts file not compile ES6 module to es5 ?

### ISSUE THREAD

**Issue by debugly** [angular/angular-cli#12618]
I write a javascript file named Toast.js 
```
export class XQL {
   ///....
};

```
I want to use the file in my angular component, i add it's to angular.json scripts:

```
"scripts": ["src/assets/js/Toast.js"]
```

when i restart my ng serve, i got an error:

```
Uncaught SyntaxError: Unexpected token export
```
I knew in scripts file ,will bundle to scripts.js :

```
export class XQL {

};
;
//# sourceMappingURL=scripts.js.map
```

** i want to know why my js file not compile by webpack ??**

then, i change  Toast.js  to Toast.ts, i got this:

```
var XQL = /** @class */ (function () {
    function XQL() {
    }
    return XQL;
}());
export { XQL };
```
but also give me `Uncaught SyntaxError: Unexpected token export` error !

Plase help me, thank you very much!

### Versions

Angular CLI: 6.2.1
Node: 10.10.0
OS: darwin x64
Angular: 6.1.7
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.1
@angular-devkit/build-angular     0.8.1
@angular-devkit/build-optimizer   0.8.1
@angular-devkit/build-webpack     0.8.1
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/animations               6.1.8
@angular/cdk                      6.4.7
@angular/cli                      6.2.1
@angular/material                 6.4.7
@ngtools/webpack                  6.2.1
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.18.0

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
