### ISSUE TITLE
styles/angular.json documentation

### ISSUE THREAD

**Issue by javajohnHub** [angular/angular-cli#12628]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
  Windows (10)

### Repro steps
documentation

### Desired functionality
I need to name or id my files in the styles: [] portion of angular.json

### Mention any other details that might be useful
"styles": [
              { "input": "src/styles/rm-styles.scss", "lazy": true, "bundleName": "rm-style" },
              { "input": "src/styles/gl-styles.scss", "lazy": true, "bundleName": "gl-style" },
               { "input": "src/styles/na-styles.scss", "bundleName": "na-style" }
            ],
is there some sort of id or name property i can set on these files?

**Comment by alan-agius4** [comment]
See: https://github.com/angular/angular-cli/wiki/stories-global-styles
