### ISSUE TITLE
Scripts.js file does not get generated for Angular Elements that is under project folder

### ISSUE THREAD

**Issue by playground** [angular/angular-cli#12636]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node version - 9.4.0
npm version - 6.4.1
Angular CLI: 6.2.4
Node: 9.4.0
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.8.4
@angular-devkit/build-ng-packagr   0.8.4
@angular-devkit/build-optimizer    0.8.4
@angular-devkit/build-webpack      0.8.4
@angular-devkit/core               0.7.5
@angular-devkit/schematics         0.7.5
@angular/cdk                       6.4.7
@angular/cli                       6.2.4
@angular/elements                  6.1.3
@angular/flex-layout               6.0.0-beta.18
@angular/material                  6.4.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.4
@schematics/angular                0.7.5
@schematics/update                 0.8.4
ng-packagr                         4.2.0
rxjs                               6.3.3
typescript                         2.9.2
webpack                            4.20.2

### Repro steps

ng build my-project-element (under projects/my-project-element)
This does not generate scripts.js file

ng build my-element (under default src/my-element)
This works fine

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by playground** [comment]
@alan-agius4 

The repo is [here](https://github.com/playground/my-element)

I just upgraded to ng cli v7.0.1, seems like something broke, it's not bootstrapping anymore without this line bootstrap: [AppComponent] in NgModule

```
  bootstrap: [AppComponent],
  entryComponents: [AppComponent, SnackBarComponent]
})
export class AppModule {
  constructor(private injector: Injector) {
    const el = createCustomElement(AppComponent, { injector });
    customElements.define('my-element', el);
  }
  ngDoBootstrap() {}
}
```

And here are the output of ng build for my-element and my-project-element
```
ng build my-project-element
                                                                                          
Date: 2018-10-19T15:30:53.578Z
Hash: 4a4ec662e671b38ed853
Time: 25387ms
chunk {main} main.js, main.js.map (main) 29.9 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 241 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.43 MB [initial] [rendered]

ng build my-element   
                                                                                          
Date: 2018-10-19T15:31:31.633Z
Hash: 2785ffffa2584c9d3b22
Time: 21119ms
chunk {main} main.js, main.js.map (main) 29.7 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 228 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 13.7 kB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 6.39 MB [initial] [rendered]

```

**Comment by alan-agius4** [comment]
@playground, I has a quick look at your reproduction and the act the the script file is not being emitted is due to the fact that it is not provided. https://github.com/playground/my-element/blob/master/angular.json#L163

**Comment by playground** [comment]
@alan-agius4 thanks for pointing this out.  Would be nice if we can do something like "ng add @angular/elements --project my-project-element.

Does the element render for you in v7 without having to have the property in NgModule?
```
bootstrap: [AppComponent]
```

**Comment by alan-agius4** [comment]
The bootstrap is always required check:
https://angular.io/guide/elements

For the `ng add` schematics, i’d suggest you open a new feature request with the expected behaviour and further details.
 
Thanks
