### ISSUE TITLE
Initialization error (angular 2 language service).

### ISSUE THREAD

**Issue by maxkorz** [angular/angular-cli#12637]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
Windows 10, WebStorm 2018.2
```
Angular CLI: 7.0.1
Node: 10.12.0
OS: win32 x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.1
@angular-devkit/build-angular     0.10.1
@angular-devkit/build-optimizer   0.10.1
@angular-devkit/build-webpack     0.10.1
@angular-devkit/core              7.0.1
@angular-devkit/schematics        7.0.1
@angular/cli                      7.0.1
@angular/platform-server          6.1.10
@ngtools/webpack                  7.0.1
@schematics/angular               7.0.1
@schematics/update                0.10.1
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

### Repro steps
Create a new project
Try to use Angular Language Service

### The log given by the failure
`Error:Initialization error (angular 2 language service). Cannot read property 'CommandTypes' of undefined`

**Comment by maxkorz** [comment]
@alan-agius4 hi. The problem occurs on an empty project, right after I do `ng new repro-app` and `ng server`.

**Comment by alan-agius4** [comment]
Lock file should be enough.

I am unable to replicate any issues when doing the following;
```
ng new foo
cd foo
ng serve foo
```

**Comment by maxkorz** [comment]
1. `ng new repro-app`
2. Open created project in WebStorm
3. In Webstorm Terminal run `ng serve`

new TypeScript tab opens with the error
![image](https://user-images.githubusercontent.com/25089646/47207302-9481fc00-d393-11e8-9bc1-0aad9a31dfd1.png)

https://github.com/maxkorz/repro-app

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the Webstorm project or file an issue on their issue tracker.

**Comment by maxkorz** [comment]
@alan-agius4 you saying that Angular Language Service 7.x is not compatible with present IDEs?

**Comment by maxkorz** [comment]
Thanks, I found an issue in WebStorm tracker https://youtrack.jetbrains.com/issue/WEB-34463
