### ISSUE TITLE
Custom HtmlWebpackPlugin Options.

### ISSUE THREAD

**Issue by fiture** [angular/angular-cli#12639]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] feature request
```

### Command (mark with an `x`)
```
- [ x ] build
```

### Desired functionality

How to customize configuration of  `HtmlWebpackPlugin`，eg: custom outputpath of index.html to `xx/xx/index.html` with `filename`？

**Comment by filipesilva** [comment]
I'm sorry but this isn't a feature we currently have or are thinking of adding.
