### ISSUE TITLE
Error: Unexpected value 'FormBuilder' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by Ankur07015364395** [angular/angular-cli#12633]
Error: Unexpected value 'FormBuilder' imported by the module 'AppModule'. Please add a @NgModule annotation. compiler.js:1021
	syntaxError
compiler.js:1021
./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNgModuleMetadata/<
compiler.js:10583
forEach self-hosted:268:13 ./node_modules/@angular/compiler/fesm5/compiler.js/CompileMetadataResolver.prototype.getNgModuleMetadata
compiler.js:10558
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._loadModules
compiler.js:23876
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype._compileModuleAndComponents
compiler.js:23857
./node_modules/@angular/compiler/fesm5/compiler.js/JitCompiler.prototype.compileModuleAsync
compiler.js:23817
./node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js/CompilerImpl.prototype.compileModuleAsync
platform-browser-dynamic.js:143
./node_modules/@angular/core/fesm5/core.js/PlatformRef.prototype.bootstrapModule
core.js:4344
./src/main.ts
main.ts:11
__webpack_require__
bootstrap:83
0
http://localhost:8101/main.js:1923:18
__webpack_require__
bootstrap:83
checkDeferredModules
bootstrap:45
webpackJsonpCallback
bootstrap:32
<anonymous>
http://localhost:8101/main.js:1:2

**Comment by alan-agius4** [comment]
Not following template.
