### ISSUE TITLE
ng-packagr was not updated

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#12642]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
I just updated to 7.0.0 using command `ng update @angular/cli @angular/core`.
But `ng-packagr` was not updated and also there was problem with `tsickle` versioning.
Now since `ng-packagr` is used for generating library it should be updated as well.

**Comment by JonnyBGod** [comment]
Any temporary workaround for this?

**Comment by alexeagle** [comment]
tsickle was removed as a dependency from Angular v7
But we forgot to remove it from ng-packagr and build-ng-packagr. See https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/library/index.ts#L115

**Comment by alexeagle** [comment]
Note, this means that libraries published by CLI will no longer be compatible with Closure Compiler downstream consumption by default. To build a library that works with Closure Compiler, you'll have to manually add the tsickle dependency, and get on a version of TypeScript that works with tsickle, which may lag the version used/required by Angular.
/cc @mprobst

**Comment by alan-agius4** [comment]
`tsickle` version `0.33.1` now supports TypeScript `3.1.1`

**Comment by alan-agius4** [comment]
Follow a discussion in our team meeting. We feel that we should only update `@angular-devkit/build-ng-packagr`.

This is to have the same workflow as for other non Angular CLI/Devkit packages that are used within a CLI project such `@angular/<packages>`, `TypeScript`, `Karma`, `tslint`, `tsickle` etc... All the mentioned packages needs to be manually updated by the consumers and thus `ng-packagr` should be no different.

**Comment by rdhelms** [comment]
Sorry, so just to clarify regarding the role of `tsickle` - you're saying for now we can use the updated `tsickle` version `0.33.1` and be fine, but should we be on the lookout for an opportunity to totally remove `tsickle` as a dependency? Is there another existing issue for us to track that?

**Comment by alan-agius4** [comment]
No at the moment there is no existing issue to remove `tsickle`.

**Comment by playground** [comment]
I'm running into the similar issue when try to update.

```
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       7.1.0 -> 7.3.7           ng update @angular/cdk
      @angular/core                      7.1.0 -> 7.2.13          ng update @angular/core
      @angular/material                  7.1.0 -> 7.3.7           ng update @angular/material
      rxjs                               6.3.3 -> 6.4.0           ng update rxjs
    
    
    There might be additional packages that are outdated.
    Run "ng update --all" to try to update all at the same time.
    
 ljeff@jefflu  ~/git_repo/sandbox/soconnect   update-cli ●  ng update --all
                  Package "tsickle" has an incompatible peer dependency to "typescript" (requires "~3.3.1", would install "3.4.4")
                  Package "@angular-devkit/build-ng-packagr" has an incompatible peer dependency to "ng-packagr" (requires "^2.2.0 || ^3.0.0 || ^4.0.0", would install "5.1.0").
                  Package "@angular/core" has an incompatible peer dependency to "zone.js" (requires "~0.8.26", would install "0.9.0")
                  Package "@angular/core" has an incompatible peer dependency to "zone.js" (requires "~0.8.26", would install "0.9.0").
                  Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.1.1 <3.3", would install "3.4.4").
Incompatible peer dependencies found. See above.

```
