### ISSUE TITLE
ERROR in : Template parse errors: The pipe 'async' could not be found

### ISSUE THREAD

**Issue by rdbhagat999** [angular/angular-cli#12641]
### Bug Report
```
- [x ] bug report
```

### Command (mark with an `x`)
```
- [x ] build
```

### Versions
npm - 6.4.1
node - 10.12.0
angular cli - 7.0.1
angular - 7.0.0
Windows 10 (64-bit)

![image](https://user-images.githubusercontent.com/20500206/47200863-57b70480-d395-11e8-9ec2-6eb606171fc0.png)

### Repro steps

- Generate new project
- add angular material
- add angular flex layout
- Use material tooltip in a component
- ng build --prod

### The log given by the failure

ERROR in : Template parse errors:
The pipe 'async' could not be found ("<div class="mat-tooltip" [ngClass]="tooltipClass" [[ERROR ->]class.mat-tooltip-handset]="(_isHandset | async)?.matches" [@state]="_visibility" (@state.start)="_an"): C:/Users/Admin/Desktop/dev-admin/node_modules/@angular/material/tooltip/typings/index.d.ts.TooltipComponent.html@0:51

![image](https://user-images.githubusercontent.com/20500206/47201657-43c0d200-d398-11e8-90c6-f082e9562f23.png)

### Desired functionality

 Template parse errors should be fixed.

### Mention any other details that might be useful

Packages:
  "dependencies": {
    "@agm/core": "^1.0.0-beta.3",
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/material-moment-adapter": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/pwa": "^0.10.1",
    "@angular/router": "^7.0.0",
    "@angular/service-worker": "^7.0.0",
    "@ctrl/ngx-csv": "^1.1.3",
    "@types/moment-timezone": "^0.5.9",
    "body-parser": "^1.18.3",
    "core-js": "^2.5.4",
    "express": "^4.16.4",
    "file-saver": "^2.0.0-rc.4",
    "hammerjs": "^2.0.8",
    "lodash-es": "^4.17.10",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "ngx-moment": "^3.1.0",
    "ngx-progressive-image-loader": "^3.0.2",
    "rxjs": "^6.2.2",
    "xlsx": "^0.14.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.10.1",
    "@angular/cli": "~7.0.1",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/language-service": "^7.0.0",
    "@types/jasmine": "~2.8.9",
    "@types/jasminewd2": "~2.0.5",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.3.1",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.1",
    "tslint": "~5.11.0",
    "typescript": "~3.1.3"
  }

![image](https://user-images.githubusercontent.com/20500206/47201945-3a843500-d399-11e8-9be8-e394500d49d4.png)
![image](https://user-images.githubusercontent.com/20500206/47201979-538ce600-d399-11e8-836b-4b3c2efb07b9.png)

**Comment by rdbhagat999** [comment]
Log file:
[2018-10-19T06_59_55_286Z-debug.log](https://github.com/angular/angular-cli/files/2494766/2018-10-19T06_59_55_286Z-debug.log)

**Comment by alan-agius4** [comment]
From the log file provided it looks like npm install failed.

```
4393 verbose stack Error: adminpanel@0.0.0 postinstall: `npm run build`
4393 verbose stack Exit status 1
4393 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
4393 verbose stack     at EventEmitter.emit (events.js:182:13)
4393 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
4393 verbose stack     at ChildProcess.emit (events.js:182:13)
4393 verbose stack     at maybeClose (internal/child_process.js:962:16)
4393 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
4394 verbose pkgid adminpanel@0.0.0
4395 verbose cwd C:\Users\Admin\Desktop\dev-admin
4396 verbose Windows_NT 10.0.17763
4397 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
4398 verbose node v10.12.0
4399 verbose npm  v6.4.1
4400 error code ELIFECYCLE
4401 error errno 1
4402 error adminpanel@0.0.0 postinstall: `npm run build`
4402 error Exit status 1
4403 error Failed at the adminpanel@0.0.0 postinstall script.
4403 error This is probably not a problem with npm. There is likely additional logging output above.
4404 verbose exit [ 1, true ]
```

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by albanx** [comment]
I got this error when I enabled IVy

**Comment by benjaminvazquez** [comment]
@albanx do you still having the problem? I just enable Ivy and got the error.

**Comment by albanx** [comment]
@benjaminvazquez UNfortunately now, I had to disable Ivy. it is still experimental

**Comment by camu891** [comment]
Did anyone solve this problem without disabling Ivy? I have exactly the same error.
