### ISSUE TITLE
`ng update @angular/cli` from 7.0.0-rc.1 fails to update @angular-devkit/build-angular

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#12647]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
@angular/cli@7.0.1

### Repro steps
Update shown in https://github.com/angular/angular/pull/26555 needed followup commit to fix devkit/build-angular version: https://github.com/angular/angular/pull/26555/commits/9631b3a7f6ca97e2dc87e80fb5e9db635f055b2e

### Mention any other details that might be useful
Reported by @IgorMinar

**Comment by IgorMinar** [comment]
I believe that this was fixed between rc.1 and final, and only folks using 7 rcs were affected.

**Comment by Splaktar** [comment]
I saw this yesterday as well with an `ng update @angular/cli` to 7.0.1. It did not update `"@angular-devkit/build-angular": "^0.9.0",` to `"@angular-devkit/build-angular": "^0.10.1",`.

This was also mentioned in https://github.com/angular/angular-cli/issues/12646#issuecomment-431317797 and https://github.com/angular/angular-cli/issues/12624#issuecomment-431260073.

**Comment by alfaproject** [comment]
It also doesn't remove the reflect polyfill unless that's intentional?

**Comment by Splaktar** [comment]
It seems like https://github.com/angular/angular-cli/pull/12598/files#r227164792 is related to this as well.
