### ISSUE TITLE
@angular-devkit/build-angular 0.10.1 fails to extract license during build step

### ISSUE THREAD

**Issue by Marabyte** [angular/angular-cli#12649]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.1
Node: 8.11.1
OS: darwin x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.1
@angular-devkit/build-angular     0.10.1
@angular-devkit/build-optimizer   0.10.1
@angular-devkit/build-webpack     0.10.1
@angular-devkit/core              7.0.1
@angular-devkit/schematics        7.0.1
@angular/cli                      7.0.1
@angular/pwa                      0.8.5
@ngtools/webpack                  7.0.1
@schematics/angular               7.0.1
@schematics/update                0.10.1
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

### Repro steps
ng build --prod

### The log given by the failure
 92% chunk asset optimization LicenseWebpackPluginlicenseType.indexOf is not a function
TypeError: licenseType.indexOf is not a function

### Desired functionality
To build without errors 

### Mention any other details that might be useful
https://github.com/xz64/license-webpack-plugin/pull/53

This issue was fixed in version 2.0.2 of the plugin.
Manually updating the plugin to the latest version fixes this problem.

**Comment by Jefiozie** [comment]
@alan-agius4, I can have a look if you don't mind?

**Comment by Jefiozie** [comment]
@alan-agius4, I can have a look if you don't mind?

**Comment by Jefiozie** [comment]
@alan-agius4, I can have a look if you don't mind?

**Comment by ShinDarth** [comment]
Confirmed. I have the same issue.

**Comment by alan-agius4** [comment]
@Jefiozie, sure go ahead :)

**Comment by alan-agius4** [comment]
@Jefiozie, sure go ahead :)

**Comment by Jefiozie** [comment]
@alan-agius4 , I believe the only change was the version of the package. There is the PR for. If needed I can make more changes.
