### ISSUE TITLE
Error in when i try to ng serve

### ISSUE THREAD

**Issue by onixortiz** [angular/angular-cli#12656]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.1
Node: 10.12.0
OS: darwin x64
Angular: 7.0.0
... cdk, common, compiler, core, material

### Repro steps
npm i --save
npm install @angular/cli -g
ng serve

### The log given by the failure
ERROR in ./src/assets/styles/app.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/assets/styles/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Dart Sass version 1.2.0 is incompatible with ^1.3.0.
    at getRenderFuncFromSassImpl (/Users/onixortiz/Documents/GitHub/Cinco-validation/cinco-validation/node_modules/sass-loader/lib/loader.js:103:19)
    at Object.sassLoader (/Users/onixortiz/Documents/GitHub/Cinco-validation/cinco-validation/node_modules/sass-loader/lib/loader.js:46:20)
ERROR in node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(72,67): error TS1144: '{' or ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,33): error TS1005: ';' expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(74,39): error TS1109: Expression expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(79,5): error TS1128: Declaration or statement expected.
node_modules/@angular/flex-layout/extended/typings/style/style.d.ts(80,1): error TS1128: Declaration or statement expected.

### Mention any other details that might be useful
I have uninstall and re-install node a few times
I'm the only one in my team that can't access de project.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
