### ISSUE TITLE
Installation of Angular-cli gives me warning error

### ISSUE THREAD

**Issue by ychalodiya** [angular/angular-cli#12658]
I am trying to install Angular-cli in my terminal but when i run following command:

#### Yogesh:_logs yogi$ npm install @angular/cli -g 

 it gives me an error like this: 
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/core
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@schematics/angular
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@schematics/update
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@schematics
npm WARN checkPermissions Missing write access to /Users/yogi/.npm-global/lib/node_modules/@angular
npm ERR! path /Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics'
npm ERR!  { Error: EACCES: permission denied, access '/Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/Users/yogi/.npm-global/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yogi/.npm/_logs/2018-10-19T23_26_46_228Z-debug.log.

#### -bash: ng: command not found

anyone know where's the problem?

**Comment by waguirre** [comment]
Your project is open with editor.... and folder exists?

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
