### ISSUE TITLE
Timout with package install - material-design-icons

### ISSUE THREAD

**Issue by JasonGoemaat** [angular/angular-cli#12668]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] yarn
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v10.12.0  
yarn: 1.10.1

### Repro steps

1. Clone the angular-cli repository
2. run `yarn` to try and install packages

### The log given by the failure

```
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/material-design-icons/-/material-design-icons-3.0.1.tgz: ESOCKETTIMEDOUT".
```

From yarn-error.log:

```
Yarn version: 
  1.13.0-0

Node version: 
  10.12.0

Platform: 
  win32 x64

Trace: 
  Error: ESOCKETTIMEDOUT
```

### Desired functionality

Packages should install

### Mention any other details that might be useful

My network connection is great, downloading the package in a browser takes about 5 seconds at 5-6mb/second.  I think the problem is the package is 31mb and has almost 90,000 files in it, so maybe it is actually expanding the package in the cache when it says it is fetching it?

Starting a new package and running `time yarn add material-design-icons@3.0.1 --network-timeout 600000` works in 4m18s:
[yarn-error.log](https://github.com/angular/angular-cli/files/2498317/yarn-error.log)

```
$ time yarn add material-design-icons@3.0.1 --network-timeout 600000
yarn add v1.10.1
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ material-design-icons@3.0.1
info All dependencies
└─ material-design-icons@3.0.1
Done in 258.03s.

real    4m18.609s
user    0m0.045s
sys     0m0.137s
```

Just annoying, I didn't think about it having to expand the package and it being so large, but I knew there wasn't a problem with my network connection so it was a little hard to track down.  Plus yarn doesn't give you any information while it is working and retrying multiple times, just "there appears to be a network error" which isn't the actual case.  I don't know where the 'ESOCKETTIMEDOUT' is coming from, it doesn't appear to be a real network issue.

**Comment by alan-agius4** [comment]
Personally I've never encountered this issue.

**Comment by JasonGoemaat** [comment]
1.10.1 is the most recent 'stable' version (@latest), I also tried building myself from master which is 1.13.0 and it did the same thing.

**Comment by AngelCut** [comment]
Hi there!

I'm running into same issue... :-(

Any idea if another version of the dependency could do the trick ?
Is this really needed for angular-ci (I guess it should but just in case of...) ?

Regards,
Angelo

**Comment by clydin** [comment]
The package is no longer a development dependency of the CLI.
