### ISSUE TITLE
experimental ivy creates angular cli project v7.0.0-rc3 while cli is version 7.0.2

### ISSUE THREAD

**Issue by kfirufk** [angular/angular-cli#12667]
```

- [x ] bug report 
```

### Command (mark with an `x`)
```
- [x ] new
```

### Versions

MacOS Mojave 10.4
NodeJS v10.12.0
Angular CLI 7.0.2

### Repro steps

`ng new a --experimental-ivy
`

### Desired functionality
it should create a project with angular 7 final

### Mention any other details that might be useful
it creates a project with angular cli v7.0.0-rc3, it doesn't happen if I don't enable experimental ivy.

**Comment by alan-agius4** [comment]
When selecting to create a project with `experminalIvy` it will create the project with the `next` versions of the package instead of the stable one.
