### ISSUE TITLE
@angular-devkit/benchmark isn't released

### ISSUE THREAD

**Issue by noelmace** [angular/angular-cli#12663]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
N/A (angular-devkit)

### Versions
N/A

### Repro steps
``npm i -g @angular-devkit/benchmark``

### The log given by the failure
```
npm ERR! code E404
npm ERR! 404 Not Found: @angular-devkit/benchmark@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noel/.npm/_logs/2018-10-20T11_44_31_673Z-debug.log
```

### Desired functionality
@angular-devkit/benchmark should be available through npm

### Mention any other details that might be useful
README say to install the benchmark package, but this package already exist and isn't related to the angular-devkit.

For now, we need to use a local build:
1. Go to your local angular-cli clone
1. Run yarn build
1. Go to dist/@angular-devkit/benchmark folder
1. Run npm / yarn link

We may also need to give some more informations on the how and why this package was created and how it could help angular-cli users.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

It was not released intentionally. Removed reference from release notes.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

This package was intentionally not released. Reference in release notes has been removed.
