### ISSUE TITLE
Service Worker files ngsw.json and ngsw-worker.js not getting bundled 

### ISSUE THREAD

**Issue by giridharkannan** [angular/angular-cli#12665]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 7.0.2
Node: 8.11.2
OS: linux x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.0.2
@angular/cdk                      6.3.2
@angular/cli                      6.2.6
@angular/material                 6.3.2
@angular/pwa                      0.10.2
@ngtools/webpack                  6.0.8
@schematics/angular               7.0.2
@schematics/update                0.8.6
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

### Repro steps

ng build --prod

### The log given by the failure

missing ngsw.json and ngsw-worker.js in dist

### Desired functionality

must create appropriate ngsw.json and ngsw-worker.js in dist

### Mention any other details that might be useful

The service worker files are added in dist folder for the same private repo if Angular CLI : 6.2.6 is used

**Comment by alan-agius4** [comment]
Hi, from the logs above, it shows that you are using Angular CLI version` 6.2.6` and not `7.0.2` as initially stated.

Also, can you please setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by giridharkannan** [comment]
I tried creating repro-app as per your instruction and  ngsw.json, ngsw-worker.js are getting populated when creating a production build (ng build --prod)
In the prevate repo, all the angular dependencies where using 6.0.7 and have moved them manually to 7.0.0 (@angular/animations, @angular/core, @angular/forms ...). After this, things are working properly.

Thanks for your help.

**Comment by schankam** [comment]
I got the same issue here, updating angular PWA module and not working as expected anymore. I have angular CLI 7, and Angular 7 everywhere. What can be the issue ?

**Comment by garthmountain** [comment]
@JudahGabriel - this helped me, thank you sir,
