### ISSUE TITLE
ng build fails on dynamically linked directories

### ISSUE THREAD

**Issue by kfirufk** [angular/angular-cli#12675]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
```

### Command (mark with an `x`)
```
- [x ] build
```

### Versions
MacOS Mojave 10.14
node version v10.12.0
yarn v1.10.1 - angular cli is configured to use yarn instead of npm
angular cli v7.0.2

### Repro steps
if I generate a component with

`ng generate component tuxin-ec-accessibility
`
and then I would move the directory outside of the project and create a dynamic link to it, the project fails to build

### The log given by the failure
```
ERROR in ../tuxin-ec-libs/tuxin-ec-accessibility/tuxin-ec-accessibility.component.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Volumes/osx-storage/projects/wd/tuxin-ec-libs/tuxin-ec-accessibility/tuxin-ec-accessibility.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Volumes/osx-storage/projects/wd/windy-client/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:762:23)
    at plugin.done.then (/Volumes/osx-storage/projects/wd/windy-client/node_modules/@ngtools/webpack/src/loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Desired functionality
build will succeed

### Mention any other details that might be useful

in general I have several components that I wanna share between every project, and creating a library and pack it  just creates a hassle and makes it harder to debug.. so I decided just to share components code that have the same prefix.

created an issue on stackoverflow with more details information:
https://stackoverflow.com/questions/52908500/ng-build-fails-when-there-are-dynamically-linked-directories-in-the-project

**Comment by alan-agius4** [comment]
You need to use `preserveSymlinks` either via the command line or via the options inside the `angular.json` under `architect/build/options`

Ex:

```js
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "preserveSymlinks": true,
      "index": "src/index.html",
      "main": "src/main.ts",
      ....
    }
  }
}
```

Check here: https://angular.io/cli/build

**Comment by kfirufk** [comment]
yes! it addresses my issue! 👍 
thank you very much
