### ISSUE TITLE
Unable to install angular-cli

### ISSUE THREAD

**Issue by sreegodavarthi** [angular/angular-cli#12677]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps

Simple steps to reproduce this bug.
installed angular using sudo npm install -g @angular/cli

### The log given by the failure

Srees-MacBook-Pro:~ sreegodavarthi$ ng
An invalid configuration file was found ['/Users/sreegodavarthi/.angular.json']. 
Please delete the file before running the command.

**Comment by sreegodavarthi** [comment]
Getting the below error, but I do not see angular.json in the path mentioned.

Srees-MacBook-Pro:~ sreegodavarthi$ ng
An invalid configuration file was found ['/Users/sreegodavarthi/.angular.json']. Please delete the file before running the command.

**Comment by RicardoVaranda** [comment]
Hi @sreegodavarthi ,

Could you please post your npm and node versions by running:

```
npm -v
node -v
```

**Comment by alan-agius4** [comment]
Can you execute the following please?

```bash
ls /Users/sreegodavarthi/.angular.json
```

**Comment by sreegodavarthi** [comment]
> Hi @sreegodavarthi ,
> 
> Could you please post your npm and node versions by running:
> 
> ```
> npm -v
> node -v
> ```

node version - 8.11.4
npm version - 6.4.1

**Comment by sreegodavarthi** [comment]
> Can you execute the following please?
> 
> ```shell
> ls /Users/sreegodavarthi/.angular.json
> ```
> 
> If the file doesn't exists you should be getting;
> 
> ```
> No such file or directory.
> ```

Yes when I tried "ls /Users/sreegodavarthi/.angular.json" I get redirected to users folder, but there is no .angular.json file in the folder

**Comment by alan-agius4** [comment]
@sreegodavarthi what do you mean you get redirected?

Can you show the exact output in the console when executing `ls 
/Users/sreegodavarthi/.angular.json`?


Try running
```
mv /Users/sreegodavarthi/.angular.json /Users/sreegodavarthi/angular.json.txt
```

**Comment by sreegodavarthi** [comment]
@alan-agius4 Thank you!!, it worked

**Comment by Chirag5528** [comment]
I deleted the angular.json file from the directory the error was showing.
Then tried to run ng new my-pro
That worked.
Can i know what will be the errors I will be facing after deleting that file.
