### ISSUE TITLE
Add support for JSS styling

### ISSUE THREAD

**Issue by kmturley** [angular/angular-cli#12672]
### Bug Report or Feature Request
```
- [ ] bug report
- [x] feature request
```

### Command
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
Add support for [JSS styling](https://github.com/cssinjs/jss) template:
`ng new sassy-project --style=jss`

One of the really existing things about JSS (apart from faster compilation times), is that it supports TypeScript definitions, which results in stricter rules and more consistent code. Essential for large projects with multiple developers!!

### Mention any other details that might be useful

> JSS is a more powerful abstraction over CSS. It uses JavaScript as a language to describe styles in a declarative and maintainable way. It is a high performance JS to CSS compiler which works at runtime and server-side. This core library is low level and framework agnostic. It is about 6KB (minified and gzipped) and is extensible via plugins API.

https://github.com/cssinjs/jss

**Comment by abumuawiyah** [comment]
I used angular-jss codebase by kmturley and it really help me save time.

**Comment by alan-agius4** [comment]
Hi @kmturley, 

Thanks for this feature request.

Currently this doesn't fall in the Angular CLI roadmap as the interest in this issue is low. Let's re-consider this in the future if things change.
