### ISSUE TITLE
MediaTypeBlocked when installing @angular/cli

### ISSUE THREAD

**Issue by pappasa** [angular/angular-cli#12684]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version: v8.12.0
npm --version: 6.4.1
ng --version: 
@angular/cli: 1.0.0-rc.0
node: 8.12.0
os: win32 x64

### Repro steps
npm install -g @angular/cli

the following error appears:

npm ERR! code E403
npm ERR! 403 MediaTypeBlocked: opn@5.3.0

### The log given by the failure
3976 verbose unlock done using C:\Users\x85397\AppData\Roaming\npm-cache\_locks\staging-9fc8d0708d169797.lock for C:\Users\x85397\AppData\Roaming\npm\node_modules\.staging
3977 timing stage:rollbackFailedOptional Completed in 1ms
3978 timing stage:runTopLevelLifecycles Completed in 299303ms
3979 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\@angular\cli\node_modules\chokidar\node_modules\fsevents):
3980 warn optional SKIPPING OPTIONAL DEPENDENCY: 403 MediaTypeBlocked: https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz
3981 verbose stack Error: 403 MediaTypeBlocked: opn@5.3.0
3981 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
3981 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
3981 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
3981 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
3981 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
3981 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
3981 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
3981 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
3981 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
3981 verbose stack     at runCallback (timers.js:810:20)
3981 verbose stack     at tryOnImmediate (timers.js:768:5)
3981 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
3982 verbose cwd C:\temp\ngx-bootstrap-2.0.0-beta.8\package
3983 verbose Windows_NT 10.0.16299
3984 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
3985 verbose node v8.12.0
3986 verbose npm  v6.4.1
3987 error code E403
3988 error 403 MediaTypeBlocked: opn@5.3.0
3989 verbose exit [ 1, true ]

### Mention any other details that might be useful
[2018-10-22T08_50_09_017Z-debug.log](https://github.com/angular/angular-cli/files/2500712/2018-10-22T08_50_09_017Z-debug.log)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by pappasa** [comment]
From the log one can see, that it tries to load https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz. When I try to download just this file, I get the following error message: 


File Blocked
McAfee Web Gateway has blocked the file, because the detected media type (see below) is not allowed.
URL: https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz
Filename: package/build/gyp-mac-tool
Media Type (detected): text/x-python, text/plain
Media Type (from file name): Transaction ID:91DpLZ6RekwDhvPnxyxGtFiwfTBoPq8eH/9BYMozfD4VRPUgt0/DxSiR9UCW8WFTsu5tgwwnOfIgNwxWmakYnQ==This message was generated by webwash2 |   | File Blocked | McAfee Web Gateway has blocked the file, because the detected media type (see below) is not allowed. | URL: https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgzFilename: package/build/gyp-mac-toolMedia Type (detected): text/x-python, text/plainMedia Type (from file name): Transaction ID:91DpLZ6RekwDhvPnxyxGtFiwfTBoPq8eH/9BYMozfD4VRPUgt0/DxSiR9UCW8WFTsu5tgwwnOfIgNwxWmakYnQ==
![mcafee](https://user-images.githubusercontent.com/23055341/47342375-411def80-d6ac-11e8-9fc7-b63d6f56d608.jpg)
This message was generated by webwash2


It seems, that the internet filter blocks python scripts. As I am working on a Windows 10 machine, I think I do not need fsevents, because as I read, fsevents is for Mac OS X. I would suggest that angular-cli should not require fsevents on Windows machines.
