### ISSUE TITLE
File is blocked, when downloading zip file

### ISSUE THREAD

**Issue by pappasa** [angular/angular-cli#12685]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version: v8.12.0
npm --version: 6.4.1
ng --version: 
@angular/cli: 1.0.0-rc.0
node: 8.12.0
os: win32 x64

### Repro steps
Download [zip angular-cli](https://github.com/angular/angular-cli/archive/master.zip).

The following error appears:

Archive Not Supported
This file is blocked, because its detected type is not supported by archive handler.
URL: https://codeload.github.com/angular/angular-cli/zip/master
Filename: angular-cli-master/.circleci/github_token
Media Type (detected): application/x-mwg-encrypted
Media Type (from file name): 
Transaction ID:RaI8WfwiKhsmzz+mUJTElkKAYzRHt2dCd9/cKGC2n2p0kDc66QBklSAvN6E8U7e6H3BnRa2mCaXWGnh4cw0bRg==
This message was generated by webwash2

Why does angular-cli need to have media type application/x-mwg-encrypted? Angular is supposed to be a nodejs project, it should have javascript files, which should not be blocked by an internet filter.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. This seems to be something related to your environment setup.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. This seems to be something related to your environment setup.

**Comment by pappasa** [comment]
As you can see from the log, it was able to load until zone.js. If failed upon loading opn@4.0.2. Why is opn blocked? Beeing a Nodejs package, it should have only Javascript files. I think, it is a bug, because Nodejs packages should have content that is not blocked by internet filters.
