### ISSUE TITLE
ng new fails with "Schematic input does not validate against the Schema"

### ISSUE THREAD

**Issue by breningham** [angular/angular-cli#12690]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node Version:
```
$ node --version
v10.12.0
```

NPM Version:
```
$ npm --version
6.4.1
```

Angular Version:
```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.0.2
Node: 10.12.0
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
```

OS: MacOS Mojave

### Repro steps

`ng new ng7app` 

### The log given by the failure

Schematic input does not validate against the Schema: {"name":"ng7app"}
Errors:

  Data path "" should have required property 'version'.

### Desired functionality

I would like to generate a new Angular Workspace.

### Mention any other details that might be useful

if i provide a 'version', then i get a different error : 
```
$ ng new ng7app --version 7
Cannot read property 'entries' of undefined
```

**Comment by hexl84** [comment]
I can not create a new workspace with ng new in windows10

Command : ng new my-app
npm: 6.4.1
Angular CLI: 7.0.2
Node: 8.12.0
OS: win32 x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3

I get error after I run the ng new my-app

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by alexeagle** [comment]
This is generally because the CLI found some file like an old `angular.json` in the current directory or a parent directory. We should improve the error message - for now, try running the `ng new` command in a different directory or removing some stale files if you can guess which they are...

**Comment by breningham** [comment]
hi @alexeagle thanks,

i didn't have a rogue angular.json file, but i did have a rogue 'local' install in my Projects folder, must of forgot the `-g` sometime previously.

Anyway, Seems to have been resolved by removing the unneeded node_modules folder.

**Comment by jvdboom** [comment]
Same here:
ng -version:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.0.3
Node: 11.0.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.3
@angular-devkit/core         7.0.3
@angular-devkit/schematics   7.0.3
@schematics/angular          7.0.3
@schematics/update           0.10.3
rxjs                         6.3.3
typescript                   3.1.3

**>ng new DemoApp
Schematic input does not validate against the Schema: {"name":"DemoApp"}
Errors:

  Data path "" should have required property 'version'.**

**Comment by westdabestdb** [comment]
Same here ._.
```
> ng --version

Angular CLI: 7.0.4
Node: 10.7.0
OS: darwin x64
Angular: 
... 
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.4
@angular-devkit/core         7.0.4
@angular-devkit/schematics   7.0.4
@schematics/angular          7.0.4
@schematics/update           0.10.4
rxjs                         6.3.3
typescript                   3.1.3
    
>bash-3.2$ ng new serv
Schematic input does not validate against the Schema: {"name":"serv"}
Errors:

  Data path "" should have required property 'version'.
```

**Comment by SantiPrll** [comment]
Con la nueva actualización del Angular CLI 
debes de especificar con que tipo de versión trabajarás 

ng new project-name --version=7.0.4
o
ng new project-name --version=7.0.2

Saludos

**Comment by westdabestdb** [comment]
@SantiPrll Hello, thank you for help but now I get this error.
`ng new freeng --version=7.0.2`
`Could not find (undefined)`

**Comment by unaor** [comment]
using @SantiPrll comment it worked for me

**Comment by SantiPrll** [comment]
![image](https://user-images.githubusercontent.com/21017099/48036516-5e33d300-e12e-11e8-9b1a-6142abbce996.png)


@westdabestdb  Si te fijas replique tu ejemplo y si trabaja, te recomiendo que resinstalar el CLI de forma global.

**Comment by SantiPrll** [comment]
Que versión de node estás utilizando?

**Comment by josalvatorre** [comment]
> Que versión de node estás utilizando?

v11.0.0

**Comment by StarDrop9** [comment]
I remover node_modules folder in users/{user name} and ng new [appname] now working.

**Comment by meysamsahragard** [comment]
Hi, For resolve this error uninstall @schematics/angular package or remove @schematics directory from node_modules directory then install a previous version. For example:
npm i @schematics/angular@0.7.0 --save-dev

**Comment by movadee** [comment]
> node_modules

this solved my issue! thanx

**Comment by breningham** [comment]
I'm closing this issue as the original issue has been resolved.

**Comment by StephenWTurner** [comment]
I had the same error when I used underscores in the new ap name instead of hyphens:

npm new my_new_app   >>> Fails
npm new my-new-app   >>> Succeeds

**Comment by vsanandan** [comment]
After trying all these things, I get the following error for the command 
ng new getrequest --version=7.1.2

Tree type is not supported.

I am trying the above command on CLI.

**Comment by MartinJohns** [comment]
> I had the same error when I used underscores in the new app name instead of hyphens:

I had the same error when one of the name-parts was digits, e.g. `prototype-1234`. Changing it to `prototype-s1234` works. So here it's a case of a bad regex.

**Comment by B1u2Pr0** [comment]
Hello, StephenWTurner
Thanks for your comment
Could you tell me the reason why it solves the issue?

**Comment by StephenWTurner** [comment]
Hi B1u2Pr0, I'm not sure it does solve the original issue at all. However, it allows a simple typo to be eliminated before getting unrelated 'me toos',

**Comment by SubbuSwaroop** [comment]
I was facing the same issue... The problem for me was , I was using an underscore when creating the directory name.
I was using "ng new Test_Angular". Then I changed it to "ng new Test-Angular" and it worked for me

**Comment by Mulperi** [comment]
> I had the same error when I used underscores in the new app name instead of hyphens:
> npm new my_new_app >>> Fails
> npm new my-new-app >>> Succeeds

This worked for me. Thanks! (Still, it's strange)

**Comment by daton89** [comment]
in my case using @angular/cli 7.2.3

`ng new angular-7-test` failed with error 

```bash 
Schematic input does not validate against the Schema: {"name":"angular-7-test","version":"7.2.3","routing":true,"style":"scss"}
Errors:

  Data path ".name" should match format "html-selector".
```

`ng new angular7test`success

**Comment by Rajkumar9386** [comment]
@meysamsahragard
> npm i @schematics/angular@0.7.0 --save-dev

work for me

**Comment by meysamsahragard** [comment]
> @meysamsahragard
> 
> > npm i @schematics/angular@0.7.0 --save-dev
> 
> work for me
> Thanks :)

Hi dear Rajkumar. You're welcome.

**Comment by veerapandiyanp** [comment]
> I was facing the same issue... The problem for me was , I was using an underscore when creating the directory name.
> I was using "ng new Test_Angular". Then I changed it to "ng new Test-Angular" and it worked for me
Yes. you are right. i faced same issue

**Comment by veerapandiyanp** [comment]
@SubbuSwaroop Yes. i faced same issue and it was successful after removing uderscore 
is there any specific usage for uderscore?

**Comment by cronaldo9999** [comment]
I have the same error creating new project with underscore

```
ng new angular_wip
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? Sass   [ http://sass-lang.com   ]
Schematic input does not validate against the Schema: {"name":"angular_wip","version":"7.3.2","routing":true,"style":"sass"}
Errors:

  Data path ".name" should match format "html-selector".
```

Anyway to resolve this? It's ridiculous that the project must not contain underscore in order for the cli to successfully initialize the app.

**Comment by khandelwalriya** [comment]
Angular CLI: 6.2.9
Node: 10.15.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.9
@angular-devkit/core         0.8.9
@angular-devkit/schematics   0.8.9
@schematics/angular          0.8.9
@schematics/update           0.8.9
rxjs                         6.2.2
    

Schematic input does not validate against the Schema: {"version":"6.2.9","skipGit":false,"experimentalIvy":false,"skipInstall":false,"linkCli":false,"commit":true,"newProjectRoot":"projects","inlineStyle":false,"inlineTemplate":false,"routing":false,"prefix":"app","style":"css","skipTests":false,"createApplication":true,"minimal":false}
Errors:

  Data path "" should have required property 'name'.

**Comment by pacozevallos** [comment]
> I removed node_modules folder in users/{user name} and ng new [appname] now working.

Eliminar la carpeta de node_modules funcionó para mí, había quedado un package.json que también lo eliminé.

Angular CLI: 7.3.4
Node: 10.15.2
OS: darwin x64

**Comment by johnmanoahs** [comment]
Apparently if your project name has a "_" or "-" (underscore or hyphen) it tends to throw this error. I removed the special chars and it worked ok.

**Comment by royelias** [comment]
> I had the same error when I used underscores in the new app name instead of hyphens:
> 
> npm new my_new_app >>> Fails
> npm new my-new-app >>> Succeeds

had same issue and using hyphens instead of underscore worked perfectly

**Comment by alexbrtsv** [comment]
have the sane trouble

npm uninstall -g angular-cli
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest

reinstall helps me

**Comment by n8bizall** [comment]
I had this same issue and just had to make it 
ng new myApp --version 7.3.6 <-the version of angular I am using

**Comment by aneeshjoshi** [comment]
> Apparently if your project name has a "_" or "-" (underscore or hyphen) it tends to throw this error. I removed the special chars and it worked ok.

 🤦‍♂️ - This worked for me. 

Thanks @johnmanoahs

**Comment by rafaelzuckerberg** [comment]
For me, before, I updated npm : "npm update" and after run : "ng new projetc-teste --version=7.3.6"

**Comment by mohanacchu** [comment]
i'm still facing the same issue.My current angular version is 7.3.6 but error still exist

ng new learn-curve
C:\Users\mohan.n\Desktop\My Help in Angular Nov\angular-learn>ng new learn-curve
Schematic input does not validate against the Schema: {"name":"learn-curve"}
Errors:

  Data path "" should have required property 'version'.

i also tried ng new projetc-teste --version=7.3.6 
for which i'm getting Cannot read property 'entries' of undefined


![angular install error](https://user-images.githubusercontent.com/33092062/55060161-d75ca400-5096-11e9-97a1-7da5004cf1b1.PNG)


Please help me out

**Comment by chemc2** [comment]
@mohanacchu try no to use '-' on the name of the project. Something is wrong with newer versions in that regard

**Comment by rafaelzuckerberg** [comment]
Try inside yout project to remove node_module and run npm install again

**Comment by farooqahmedkhan** [comment]
> I had the same error when I used underscores in the new app name instead of hyphens:
> 
> npm new my_new_app >>> Fails
> npm new my-new-app >>> Succeeds

Strange but this actually resolved the schematic issue.

**Comment by Cuica20** [comment]
> For me, before, I updated npm : "npm update" and after run : "ng new projetc-teste --version=7.3.6"

Thanks, this worked for me.

**Comment by Sivaneymar07** [comment]
3 things you should check if you face problem on ng new
 1) check the directory name - should not have alphanumeric and special characters.
 2) type ng --version in node cmd, check whether all package is clear without showing error on the package version or else install those packages.
 3) if cmd shows error on @angular\cli then delete c:\users\username\Appdata\Roaming\npm\node_modules\@angular\cli and then install it, it will work. if you feel appdata is missing in the folder then it is in hidden, u should do C: -> Organize -> Folder Options -> View -> Hidden files and folder -> Show hidden files.....

Hope this will help you....

**Comment by renanss** [comment]
> 3 things you should check if you face problem on ng new
> 
> 1. check the directory name - should not have alphanumeric and special characters.
> 2. type ng --version in node cmd, check whether all package is clear without showing error on the package version or else install those packages.
> 3. if cmd shows error on @angular\cli then delete c:\users\username\Appdata\Roaming\npm\node_modules@angular\cli and then install it, it will work. if you feel appdata is missing in the folder then it is in hidden, u should do C: -> Organize -> Folder Options -> View -> Hidden files and folder -> Show hidden files.....
> 
> Hope this will help you....

mine had alphanumeric. Removed the number and now its working. Ty

**Comment by yogeshdotnet** [comment]
HI,
This issue may be resolved by applying the following command in cmd.

npm i @schematics/angular@latest --save-dev

after applying this no need to write version after angular 7 project name just write
ng new ang-project-name

**Comment by rafmos** [comment]
I deleted the -3 at the end of my project name and then it worked. :)

ng new my-project-3        ----> Doesn't work
ng new my-project-three  ----> Works

**Comment by crissdev** [comment]
It seems the CLI doesn't like project names that end with a dash/underscore and only digits (e.g `app-name-01`, `app-name_02`). Removing the dash/underscore works, ie. `app-name01`, `app-name02`.

**Comment by vip9** [comment]
For me, helped removing ~/package-lock.json (who knows why that file was in my home)

**Comment by alikarimii** [comment]
use `--clientProject project-name` flag work for me

**Comment by sagar87966** [comment]
previous CLI version:--  7.3.8
solution:-- updated CLI version to the latest 
use CLI version:- 7.3.9
work for me

**Comment by iappwebdev** [comment]
In my case i had an app anem like `abc-2-xyz`. Changing it to `abc2xyz` resolved the problem.

**Comment by Nocturnal-2** [comment]
I was getting this error when I had an underscore sign in my project name. Worked normally after removing them. 

Angular CLI: 7.3.8

**Comment by inajad** [comment]
> I had the same error when I used underscores in the new app name instead of hyphens:
> 
> npm new my_new_app >>> Fails
> npm new my-new-app >>> Succeeds

this one worked fine for me.
Thanks.

**Comment by vrathaure** [comment]
Resolved as follows:- 

npm uninstall -g @angular/cli@next
npm uninstall @angular/cli@next
npm cache verify
npm install -g @angular/cli@next
npm install @angular/cli@next
npm i @schematics/angular@next

**Comment by Anand-Chavan** [comment]
first type ng -v
then according to your version install following command
@schematics/angular@6.0.8

**Comment by dsun-ge** [comment]
I had the same problem with **ng new naq_monthly_settlement_report**. I fixed it with **ng new naq-monthly-settlement-report**
