### ISSUE TITLE
github repo v6.2.x README points to v7 links

### ISSUE THREAD

**Issue by gkamperis** [angular/angular-cli#12700]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Repro steps

switch to branch 6.2.x

The readme points to link for v7

### Desired functionality
I should see the readme for version 6 of the devkit/cli

**Comment by gkamperis** [comment]
@hansl this is still an issue when I switch to the 6.2.x branch

**Comment by alan-agius4** [comment]
https://github.com/angular/angular-cli/pull/13022

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/commit/ae22982650183249431c877ff8b4906c738cd681

**Comment by gkamperis** [comment]
@alan-agius4 don't know if it is too early but switching to the 6.2.x branch still shows the 7.1.0 readme

**Comment by alan-agius4** [comment]
Can you kindly indicate which link is incorrect?

**Comment by gkamperis** [comment]
@alan-agius4 
https://github.com/angular/angular-cli/tree/6.2.x
