### ISSUE TITLE
ng test 404 for .js.map since angular 7.0

### ISSUE THREAD

**Issue by maximedupre** [angular/angular-cli#12702]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

npm `v6.4.1`
Angular CLI: 7.0.2
Node: 9.5.0
OS: darwin x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              7.0.2
@angular-devkit/schematics        7.0.2
@angular/cli                      7.0.2
@ngtools/webpack                  7.0.2
@schematics/angular               7.0.2
@schematics/update                0.10.2
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

### The log given by the failure

    22 10 2018 17:10:07.402:WARN [web-server]: 404: /node_modules/@angular/core/fesm5/testing.js.map
    22 10 2018 17:10:07.404:WARN [web-server]: 404: /node_modules/@angular/core/fesm5/core.js.map
    22 10 2018 17:10:07.406:WARN [web-server]: 404: /node_modules/rxjs/_esm5/index.js.map
    22 10 2018 17:10:07.407:WARN [web-server]: 404: /node_modules/rxjs/_esm5/internal/Observable.js.map
    22 10 2018 17:10:07.409:WARN [web-server]: 404: /node_modules/rxjs/_esm5/internal/util/canReportError.js.map
    22 10 2018 17:10:07.411:WARN [web-server]: 404: /node_modules/rxjs/_esm5/internal/Subscriber.js.map
    22 10 2018 17:10:07.423:WARN [web-server]: 404: /node_modules/rxjs/_esm5/internal/util/isFunction.js.map
    22 10 2018 17:10:07.426:WARN [web-server]: 404: /node_modules/rxjs/_esm5/internal/Observer.js.map
    [...]

### Mention any other details that might be useful

Occurs since updating to angular 7.0

**Comment by alan-agius4** [comment]
Hi, I tried to look into this but I cannot reproduce
![image](https://user-images.githubusercontent.com/17563226/47341860-69085580-d6a2-11e8-8c13-5f0fa6343654.png)


Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by maximedupre** [comment]
@alan-agius4 Thanks for the response. In my attempt to create a minimal repro I deleted 'node_modules' and reinstalled everything and now everything works.

**Comment by britvik** [comment]
I'm having the same issue after upgrading to angular 7. It doesn't show the warnings at first, but after few reruns (by rerun I mean automatic test execution after any change made to test or sourcecode files).
I'm using same versions as OP + "jasmine-core": "2.6.4",  "karma": "1.7.1",

**Comment by werthdavid** [comment]
That only happens if you open developer tools in the Test-Chrome (at least for me)
