### ISSUE TITLE
ng add @angular/elements --project my-project-element is not updating angular.json

### ISSUE THREAD

**Issue by playground** [angular/angular-cli#12717]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 7.0.0-rc.3
Node: 9.4.0
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.9.0-rc.3 (cli-only)
@angular-devkit/core         7.0.0-rc.3 (cli-only)
@angular-devkit/schematics   7.0.0-rc.3 (cli-only)
@schematics/angular          7.0.0-rc.3 (cli-only)
@schematics/update           0.9.0-rc.3 (cli-only)
rxjs                         6.3.3 (cli-only)

### Desired functionality

Would be nice if we can do something like "ng add @angular/elements --project my-project-element that will update angular.json accordingly such as

```
    "my-project-element": {
      "root": "projects/my-project-element/",
            ...
            "scripts": [
              "node_modules/document-register-element/build/document-register-element.js"
            ]

```

**Comment by clydin** [comment]
Any specific capabilities of `ng add` beyond package installation are of the domain of the package being added and not the CLI.  If there is interest in such additional capabilities they would need to be added to the package and a request to the package itself would be the appropriate next step.
