### ISSUE TITLE
"typescript" is still "~3.1.1" in the root folder package.json file.

### ISSUE THREAD

**Issue by Nothing-Works** [angular/angular-cli#12714]
I just fresh installed angular-cli,  typescript is still showing 3.1.1 in the root package.json file, it's 3.1.3 though. anything I did wrong?
```
"typescript": "~3.1.1"

```

**Comment by Nothing-Works** [comment]
@alan-agius4 sorry I did not get it, can u explain it a little bit? 3.1.1 is the same as 3.1.3?

**Comment by Nothing-Works** [comment]
@alan-agius4 I mean why is showing 3.1.1

**Comment by alan-agius4** [comment]
In `package.json` when having `~` it will means and patch version thus, `"typescript": "~3.1.1"` will be the same as `3.1.x`
