### ISSUE TITLE
NodePackageInstallTask not triggered after app generation

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular-cli#12719]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
**node**: v8.12.0
**npm**: 6.4.1
**yarn**: 1.10.1

**Angular CLI**:
**@angular-devkit/architect**    0.10.2
**@angular-devkit/core**         7.0.2
**@angular-devkit/schematics**   7.0.2
**@angular/cli**                 7.0.2
**@schematics/angular**          7.0.2
**@schematics/update**           0.10.2
**rxjs**                         6.3.3
**typescript**                   3.1.3

### Repro steps

Execute the following commands in the exact order:
- `ng new foo --create-application false --routing false --style css`
- `cd foo`
- `ng g app playground`
    - _notice here that package.json was updated but package manager was not triggered_
- `ng serve` - **Failure**

Simply running package manager of choice after will resolve the issue.

### The log given by the failure

After `ng serve` is triggered Angular CLI correctly reports the following error:
`Could not find module "@angular-devkit/build-angular" from "/Relative/path/to/workspace".`

### Desired functionality

The same as with library schematic, `NodePackageInstallTask` should be executed as the last task.
Probably `--skip-install` flag in the schema would equally make sense.

**Comment by alan-agius4** [comment]
Are you experiencing any errors when running `ng new`? As I am unable to replicate this issue.

**Comment by klemenoslaj** [comment]
@alan-agius4, no the problem is not with `ng new.` Sorry for the misunderstanding. Basically, my observation is related to `ng g app` command.

---

When a workspace with `--create-application false` flag is created, the initial application in src folder is not being generated, nor the related dependencies added to package.json.

Generating an app right after that will result with the app in the projects and with the new dev dependency `@angular-devkit/build-angular` added to package.json.

That's all fine, however, since package manager was not triggered `@angular-devkit/build-angular` is not installed yet, so executing `ng serve` now will result in an error.

I was thinking that a package manager has to be triggered after the app generation the same way as it is when generating a library (as well `--skip-install` flag is available in the library schematic).

**Comment by alan-agius4** [comment]
Thanks, for the explanation. I now see the problem.
