### ISSUE TITLE
add prompt for directory on ng new

### ISSUE THREAD

**Issue by lloydst** [angular/angular-cli#12710]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Command (mark with an `x`)
```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
add a prompt on ng new asking generate in new folder (appname) or in current directory.

i often forget too add the --directory ./ flag and i doubt i am alone in that

**Comment by clydin** [comment]
The `--directory` option is considered an advanced option that should only be used for specific situations.  The recommended approach is to generate a new project in a directory named after the project name.  The prompts have been chosen to facilitate the customization of a small set of commonly used options.  With the primary goal of aiding new developers through the process of setting up a new project.
