### ISSUE TITLE
How do you set the basehref dynamically using angular cli version 6

### ISSUE THREAD

**Issue by hijazikaram** [angular/angular-cli#12720]
Im using webpack right now but im switching everything to angular cli.
```
new HtmlWebpackPlugin({
        // This test isn't backwards! We manage the production base URL with
        // Salt. It executes a find and replace on <base href="/">.
        baseUrl: process.env.NODE_ENV === 'production' ? '/' : '/apps/brief/',
        version: packageObj.version,
        template: 'client/index.html.ejs',
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
