### ISSUE TITLE
Angular CLI 7.0.2 projects with SASS/SCSS fail to build properly

### ISSUE THREAD

**Issue by JacobWDavidson** [angular/angular-cli#12724]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X] new (maybe?)
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

macOS High Sierra

Node
```v8.12.0```

Angular
```
Angular CLI: 7.0.2
Node: 8.12.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
```

### Repro steps

Generate a new project and set the style flag to sass or scss and then try to build the project.

https://github.com/JacobWDavidson/angularcliv7sassissue
https://github.com/JacobWDavidson/angularcliv7scssissue

### The log given by the failure

With SASS:
```
ERROR in ./src/styles.sass (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.sass)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
TypeError: Cannot read property 'split' of undefined
    at getRenderFuncFromSassImpl (/Users/jacobwdavidson/Documents/Projects/sasstest/node_modules/sass-loader/lib/loader.js:88:29)
    at Object.sassLoader (/Users/jacobwdavidson/Documents/Projects/sasstest/node_modules/sass-loader/lib/loader.js:46:20)
```
With SCSS:
```
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
TypeError: Cannot read property 'split' of undefined
    at getRenderFuncFromSassImpl (/Users/jacobwdavidson/Documents/Projects/scsstest/node_modules/sass-loader/lib/loader.js:88:29)
    at Object.sassLoader (/Users/jacobwdavidson/Documents/Projects/scsstest/node_modules/sass-loader/lib/loader.js:46:20)
```

### Desired functionality

The build should complete without issue.

### Mention any other details that might be useful

Easily reproducible with 
```ng new <projectname> style=scss | sass```
```cd <projectname>```
```ng build```

**Comment by JacobWDavidson** [comment]
Made two, one for sass, one for scss

https://github.com/JacobWDavidson/angularcliv7sassissue
https://github.com/JacobWDavidson/angularcliv7scssissue

**Comment by jmayerbm** [comment]
Having the same issue with 7.0.0, bump!

**Comment by clydin** [comment]
@JacobWDavidson Tried both repositories and both appear to function properly.  (`ng build` & `ng build --prod`).

Do you have a very old version of `dart-sass` installed by any chance?

**Comment by JacobWDavidson** [comment]
@clydin I don't believe so. I tried adding a console log in the sass-loader to see what the issue may be
```
function getRenderFuncFromSassImpl(module) {
    console.log(JSON.stringify(module));
    const info = module.info;
    const components = info.split("\t");
```
And it looks like the module object being passed in doesn't have this ```info``` property it's looking for:
```
{"version":"0.5.0","expansions":["-moz-","-webkit-"]}  
```

I added another console log where the loader calls ```getRenderFuncFromSassImpl``` to log the options that it's pulling the implementation from and get this:

```
{ implementation: 
   { version: '0.5.0',
     expansions: [ '-moz-', '-webkit-' ],
     collect: [Function],
     render: [Function] },
  fiber: undefined,
  sourceMap: '/Users/jacobwdavidson/Documents/Projects/angularcliv7scssissue/sass.map',
  precision: 8,
  includePaths: 
   [ '/Users/jacobwdavidson/Documents/Projects/angularcliv7scssissue/src' ],
  data: '/* You can add global styles to this file, and also import other style files */\n',
  sourceMapRoot: '/Users/jacobwdavidson/Documents/Projects/angularcliv7scssissue',
  omitSourceMapUrl: true,
  sourceMapContents: true,
  indentedSyntax: false,
  importer: [ [Function] ] }
```

I put another higher up in the process to show the sass-loader being passed in via loader context and see this:
```
  {
    "path": "/Users/jacobwdavidson/Documents/Projects/angularcliv7scssissue/node_modules/sass-loader/lib/loader.js",
    "query": "??ref--10-2",
    "options": {
      "implementation": {
        "version": "0.5.0",
        "expansions": [
          "-moz-",
          "-webkit-"
        ]
      },
      "sourceMap": true,
      "precision": 8,
      "includePaths": []
    },
```

**Comment by JacobWDavidson** [comment]
Attaching my yarn.lock too just in case that can provide additional context
[yarn.lock.zip](https://github.com/angular/angular-cli/files/2510981/yarn.lock.zip)

**Comment by clydin** [comment]
`node-sass` has a very old version of `0.5.0`. Do you have `node-sass` installed manually?

**Comment by JacobWDavidson** [comment]
I don't believe so.

```
angularcliv7scssissue$ node-sass -v
node-sass       4.9.3   (Wrapper)       [JavaScript]
libsass         3.5.4   (Sass Compiler) [C/C++]
```

**Comment by clydin** [comment]
It appears that versions of node-sass before 2.0.0 will exhibit the behavior described here.

This part:
```
"implementation": {
        "version": "0.5.0",
        "expansions": [
          "-moz-",
          "-webkit-"
        ]
      }
```
is the result of the `sass-loader` performing a `require('node-sass')`.

**Comment by JacobWDavidson** [comment]
Where would it be finding that version of node-sass? Looking through the yarn lock, it's not installed there and I don't have it locally. Nothing is installed globally so it's not getting it there either.

**Comment by JacobWDavidson** [comment]
Found the issue. There were node_modules under usr/local/lib, Users/<myuser>, and within the project. I had cleaned out the first and third, but hadn't looked into the Users/<myuser> directory. Sorry for the mixup!

**Comment by clydin** [comment]
No problem at all.  npm/node can be quite mysterious sometimes.

**Comment by m-tomczyk** [comment]
Got stuck on similar issue. It seams like node-sass searches upwards in dir structure and uses top most node_modules found. Ensuring that there are none above project directory fixed problem.
