### ISSUE TITLE
npm WARN tarball tarball data for @angular/compiler@~7.0.0 seems to be corrupted

### ISSUE THREAD

**Issue by maltekosian** [angular/angular-cli#12726]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

npm --version
6.4.1
ng --version
Angular CLI: 7.0.2
Node: 10.9.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3

### Repro steps

call ng new projectname

### The log given by the failure

npm WARN tarball tarball data for @angular/compiler@~7.0.0 (sha512-4fkohfGyG1BEpeYenOartuJmduyZ/R3XQx46hDDiR/9A8/Go4qLGkgr9Bd/JL/gPIR1XAHH9D5ii2sh+28ZEmA==) seems to be corrupted. Trying one more time.
[            ......] \ extract: sill extract @angular/common@~7.0.0 extracted to xxxxxxxxxxxxxxxxxxxx

### Desired functionality

It shall not slow down and than stop inbetween

**Comment by alan-agius4** [comment]
I am unable to replicate this, and usefully such errors are related to npm registry, and this might be some regional server problem on npmjs's side.

**Comment by vinothvkr** [comment]
Guys facing same issue. Is there any workaround for this?

**Comment by largeDachshund** [comment]
I'm getting this on the latest build: 1.7.4

the registry trick didn't work either.

**Comment by unmeimusu** [comment]
`npm WARN tarball tarball data for @angular/compiler@~7.1.0 (sha512-AvYXtjEJ27Rhv4c27DXNEa58Lit63jdydzbz7VuyFhNU+FwDUK2DC4gZe0nWZsf7HUniJezVRFkECDCZQeSKCQ==) seems to be corrupted. Trying one more time. `


having the same problem here ...
I did re-install angular cli several times but no-one is working.
npm uninstall and then npm clear cache --force
and then npm install @angular/cli ....but sad same error appears.
even with and w/o cmd run as admin.

**Comment by daveshale** [comment]
Solution:
	npm install -global typescript@3.1.6
Rerun command:
        npm install -global @angular/cli

The above solve the error: WARN tarball tarball data for typescript@3.1.6 (sha512-tDMYfVtvpb96msS1lDX9MEdHrW4yOuZ4Kdc4Him9oU796XldPYF/t2+uKoX0BBa0hXXwDlqYQbXY5Rzjzc5hBA==) seems to be corrupted.

**Comment by alvesa** [comment]
> `npm WARN tarball tarball data for @angular/compiler@~7.1.0 (sha512-AvYXtjEJ27Rhv4c27DXNEa58Lit63jdydzbz7VuyFhNU+FwDUK2DC4gZe0nWZsf7HUniJezVRFkECDCZQeSKCQ==) seems to be corrupted. Trying one more time. `
> 
> having the same problem here ...
> I did re-install angular cli several times but no-one is working.
> npm uninstall and then npm clear cache --force
> and then npm install @angular/cli ....but sad same error appears.
> even with and w/o cmd run as admin.

That's work to me, but unless "clear" i use "clean"

**Comment by csinghVBS** [comment]
I was having the same problem ,after some research i found that the version is different in Package-lock.json is different for the described package .so i just changed the package version and it works fine. Search with the mentioned package name in package-lock file and make the version same.

**Comment by renyuns** [comment]
i have the same problem,do you salve it?

**Comment by csinghVBS** [comment]
> i have the same problem,do you solve it?

Please check the version of package name mentioned in the issue in package-lock.json file. if the version is different make it same.

**Comment by charybdeBE** [comment]
I installed 7.1.4 instead and it works
