### ISSUE TITLE
Unload bundle styles, loaded by lazy load global styles

### ISSUE THREAD

**Issue by yamaoto** [angular/angular-cli#12727]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Versions
Windows (7/8/10).
```
$ node --version
v8.11.1
````

```
npm --version
5.6.0
```

```
ng --version

     _                      _                 ____ _     ___    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|                |___/

Angular CLI: 7.0.2Node: 8.11.1OS: win32 x64
Angular: 7.0.0... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              7.0.2
@angular-devkit/schematics        7.0.2
@angular/cdk                      7.0.1
@angular/cli                      7.0.2
@angular/material                 7.0.1
@ngtools/webpack                  7.0.2
@schematics/angular               7.0.2
@schematics/update                0.10.2
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

### Repro steps
1. ng new
2. add lazy load module
3. add lazy load global style like this https://github.com/angular/angular-cli/issues/5880 in component
4. here. unload styles in ngOnDestroy <-- feature request

### Desired functionality
Unload bundle styles, loaded by lazy load global styles.
For example we can set unique id on style element in DOM, and if you want, unload it by bundle name or unique id.

It may be helpful in case: lazy load module have global style imports from css libraries (bundled from node_modules), but if you will navigate to another route with another module --> styles from first can conflict with second

**Comment by alan-agius4** [comment]
For lazy styles, it is your responsibility to add and remove them from the DOM. Similar to how you are doing the `load`, you need to implement an `unload`
