### ISSUE TITLE
yarn workspaces is not compatible with bazel-managed deps

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#12736]
yarn workspaces lays out `node_modules` in several directories, nested with your source code. It relies on node module resolution semantics of looking for a `node_modules` in parent directories when a dependency isnt' resolved

Bazel-managed dependencies are in a single node_modules directory that's outside the source code.

We could have multiple bazel-managed node_modules, but would still need each of these to be a complete copy of deps needed for a given binary to run.

**Comment by clydin** [comment]
Another viable dependency management method is to run npm/yarn/pnpm individually for each package and the root of the monorepo.  This would also cause issues with Bazel.

**Comment by alexeagle** [comment]
Plan: advertise that yarn workspaces doesn't work.
The same use case can be achieved by having multiple independent package.json files.
Maybe we need some tooling to convert from one to the other.

**Comment by alexeagle** [comment]
Actually, having Bazel lay out its managed dependencies into multiple `node_modules` directories that live in your sources could work.

**Comment by clydin** [comment]
workspace support is being tracked/discussed here: https://github.com/bazelbuild/rules_nodejs/issues/266
