### ISSUE TITLE
 compiler failed to include relative path

### ISSUE THREAD

**Issue by GlauberF** [angular/angular-cli#12734]
### Angular CLI: 7.0.1

I'm trying to load the following module in loadchildren ```./dashboard/dashboard.module#DashboardModule```

![captura de tela de 2018-10-23 18-14-18](https://user-images.githubusercontent.com/11314585/47390368-99291600-d6ed-11e8-88e2-c116db92ec40.png)

and calling otherwise in the loadchildren, example:
```app/dashboard/dashboard.module#DashboardModule```
```dashboard/dashboard.module#DashboardModule```

does not work, 
I need to use the relative path

### my route file
![captura de tela de 2018-10-23 17-45-00](https://user-images.githubusercontent.com/11314585/47388792-801e6600-d6e9-11e8-91ef-583a9450a4e5.png)

**Comment by alan-agius4** [comment]
Doesn't follow the template

**Comment by GlauberF** [comment]
@alan-agius4 
What you want to diser with,
"Does not follow the template"?
