### ISSUE TITLE
Can't resolve all parameters ng build --prod

### ISSUE THREAD

**Issue by Sevensnake** [angular/angular-cli#12737]
ng build --prod
When I do a build I keep getting this error below.  
ERROR in : Can't resolve all parameters for AuthorizationGuard in /Services/authorization.guard.ts: (?, [object Object], [object Object]).
I added @Injectable()
`@Injectable()
export class AuthorizationGuard implements  CanActivateChild {

    canActivateChild(childRoute: ActivatedRouteSnapshot, state: RouterStateSnapshot): boolean | Observable<boolean> | Promise<boolean> {
     //   throw new Error("Method not implemented.");
     return true;
    }
    constructor(private allowedRoles:string[],
                private authService:AuthService, private router:Router) {
    }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) {
        this.router.navigate(['Home/index']);
        return true;

    }

}`

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
