### ISSUE TITLE
@schematics/angular --minimal still generate e2e project

### ISSUE THREAD

**Issue by noelmace** [angular/angular-cli#12739]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 7.0.2
Node: 10.11.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3
```

### Repro steps
Run ng new --minimal or ng g app --minimal.
The e2e schematic seems to have been executed anyway.

### The log given by the failure
N/A

### Desired functionality
Don't run the e2e schematic when using --minimal.

### Mention any other details that might be useful
Will handle this asap with a PR, just creating the issue to remind me to do so :wink:

**Comment by collinstevens** [comment]
It looks like --minimal was removed in v6, but the documentation was never removed from --help. See https://github.com/angular/angular-cli/issues/10982. --skip-tests will omit the spec files, but will leave e2e.
