### ISSUE TITLE
installation instructions fail

### ISSUE THREAD

**Issue by hansifer** [angular/angular-cli#12744]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [] doc
- [x] installation
```

### Versions
node --version
> v10.12.0

npm --version
> 6.4.1

ng --version
> Error: Cannot find module 'temp'

OS: Windows 10

### Repro steps
simply follow the installation steps in the readme. when running the `yarn` step, output is:

```
yarn install v1.10.1
$ node ./tools/yarn/check-yarn.js
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@xtuc/long/-/long-4.2.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\hans.meyer\\Documents\\tmp\\angularcli2\\a
ngular-cli\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
info There appears to be trouble with your network connection. Retrying...
```
... then nothing. confirmed network connection is fine.

### The log given by the failure

[yarn-error.log](https://github.com/angular/angular-cli/files/2512905/yarn-error.log)

### Desired functionality
the installation instructions should work.

**Comment by alan-agius4** [comment]
Hi, can you check if you can still reproduce this? It might have been some problem from the registry which effected your region.

I am unable to replicate this issue at this time.

**Comment by hansifer** [comment]
Thanks, I appreciate the quick response.

The 404 resolved itself and I was able to get past the timeout with:

> yarn --network-timeout 100000
