### ISSUE TITLE
ng generate component create only typescript file

### ISSUE THREAD

**Issue by emiliogambone** [angular/angular-cli#12747]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 6.0.1
Node: 8.11.1
OS: darwin x64
Angular: 6.0.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.1
@angular/cli                      6.0.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.6.1
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

```
ng generate component example
ng generate component example --module app
ng generate component example --project test
```

### The log given by the failure

```
Could not find an NgModule. Use the skip-import option to skip importing in NgModule.

More than one module matches. Use skip-import option to skip importing the component into the closest module.
```
Or create the component but only the .ts file

### Desired functionality

create all the component files

### Mention any other details that might be useful

I tried also with angular cli version 6.0.8 but same issue

Here you can find a minimal repro:

https://github.com/emiliogambone/sampleAngular

**Comment by alan-agius4** [comment]
You might have more than one module in the same folder, which is causing the issue.  However when specifying the `module` using the command argument, it should work.

I have tried this and it works when using `--module app`.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by emiliogambone** [comment]
i created a sort of minimal repro

**Comment by alan-agius4** [comment]
Hi, thanks for your reproduction, however it look like the issue has been fixed in that latest version of the CLI. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
