### ISSUE TITLE
App will continue to reload after running Lighthouse Audits

### ISSUE THREAD

**Issue by playground** [angular/angular-cli#12752]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 7.0.0-rc.3
Node: 9.4.0
OS: darwin x64
Angular: undefined
...

Package Version
@angular-devkit/architect 0.9.0-rc.3 (cli-only)
@angular-devkit/core 7.0.0-rc.3 (cli-only)
@angular-devkit/schematics 7.0.0-rc.3 (cli-only)
@schematics/angular 7.0.0-rc.3 (cli-only)
@schematics/update 0.9.0-rc.3 (cli-only)
rxjs 6.3.3 (cli-only)

### Repro steps

Load the app in chrome, then open developer tools, go to audits tab, run audit.  After that, the app will not stop reloading.  Will have to kill chrome and wait a while then the app is back to running normal again.  Not sure if this is CLI or Chrome related.

### The log given by the failure

![image](https://user-images.githubusercontent.com/243495/47506891-0c8e6d00-d83f-11e8-8d79-b57e430d5657.png)

**Comment by alan-agius4** [comment]
I was unable to replicate this, with the CLI version 7.0.3.

That said it is important to not that running audits on the dev-server, will give you incorrect reports as for instance text compression is not available.

**Comment by playground** [comment]
@alan-agius4 just tried out cli v7.0.3 and chrome 69.0.3497.100, the issue still exists.

Was wanting to get some metrics during development.  Does cli use sockjs-node for webpack to do reload and incremental build?

**Comment by alan-agius4** [comment]
No, nor CLI nor Webpack depends on `sockjs-node`. `webpack-dev-server` depends on `sockjs-client`, if you use HMR.

**Comment by alan-agius4** [comment]
'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
