### ISSUE TITLE
Angular v6.1.9 \ Angular-CLI v6.2.4 blank project doesnt work on Internet Explorer v11  (already tried uncommenting polyfills.ts)

### ISSUE THREAD

**Issue by michael-ibrahim** [angular/angular-cli#12751]
### Bug Report or Feature Request (mark with an `x`)
```
- [*] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ *] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
### node --version
v8.12.0

### npm --version
6.4.1

### ng --version
Angular CLI: 6.2.4
Node: 8.12.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.4
@angular-devkit/build-angular     0.8.4
@angular-devkit/build-optimizer   0.8.4
@angular-devkit/build-webpack     0.8.4
@angular-devkit/core              0.8.4
@angular-devkit/schematics        0.8.4
@angular/cli                      6.2.4
@ngtools/webpack                  6.2.4
@schematics/angular               0.8.4
@schematics/update                0.8.4
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps

ng new project
cd project
ng serve
modify polyfills.ts like this:
```
/**
 * This file includes polyfills needed by Angular and is loaded before the app.
 * You can add your own extra polyfills to this file.
 *
 * This file is divided into 2 sections:
 *   1. Browser polyfills. These are applied before loading ZoneJS and are sorted by browsers.
 *   2. Application imports. Files imported after ZoneJS that should be loaded before your main
 *      file.
 *
 * The current setup is for so-called "evergreen" browsers; the last versions of browsers that
 * automatically update themselves. This includes Safari >= 10, Chrome >= 55 (including Opera),
 * Edge >= 13 on the desktop, and iOS 10 and Chrome on mobile.
 *
 * Learn more in https://angular.io/docs/ts/latest/guide/browser-support.html
 */

/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/weak-map';
 import 'core-js/es6/set';


/** IE10 and IE11 requires the following for the Reflect API. */
 import 'core-js/es6/reflect';


/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.
import 'core-js/es7/reflect';



/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js';  // Run `npm install --save classlist.js`.

/**
 * Web Animations `@angular/platform-browser/animations`
 * Only required if AnimationBuilder is used within the application and using IE/Edge or Safari.
 * Standard animation support in Angular DOES NOT require any polyfills (as of Angular 6.0).
 **/
 import 'web-animations-js';  // Run `npm install --save web-animations-js`.

/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 */

 // (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 // (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 // (window as any).__zone_symbol__BLACK_LISTED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames

 /*
 * in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 * with the following flag, it will bypass `zone.js` patch for IE/Edge
 */
// (window as any).__Zone_enable_cross_context_check = true;

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.



/***************************************************************************************************
 * APPLICATION IMPORTS
 */
```

finally, try on Internet Explorer => doesn't work!

### The log given by the failure

Internet Explorer just gives a white blank screen 

### Desired functionality

Works fine on IE

**Comment by alan-agius4** [comment]
Can you please specify what is the error, and which version of IE are you using?

Thanks.

**Comment by michael-ibrahim** [comment]
> 
> 
> Can you please specify what is the error, and which version of IE are you using?
> 
> Thanks.

Gives a blank white screen .. No errors

**Comment by clydin** [comment]
The javascript console is blank as well?

**Comment by michael-ibrahim** [comment]
> 
> 
> The javascript console is blank as well?

Yes

**Comment by alan-agius4** [comment]
That's odd, from my end I cannot replicate it.

![image](https://user-images.githubusercontent.com/17563226/47506185-dcab8d80-d86f-11e8-9e49-3c9a1693cd84.png)

**Comment by michael-ibrahim** [comment]
> 
> 
> That's odd, from my end I cannot replicate it.
> 
> ![image](https://user-images.githubusercontent.com/17563226/47506185-dcab8d80-d86f-11e8-9e49-3c9a1693cd84.png)

what versions are you using?

**Comment by alan-agius4** [comment]
Angular 7, With Angular 6 I managed to get it working without any issues in Internet Explorer 10.

**Comment by clydin** [comment]
Try opening the javascript console before navigating to the page.

**Comment by michael-ibrahim** [comment]
> 
> 
> Try opening the javascript console before navigating to the page.

This worked .. Now I get an error:
SCRIPT1002: Syntax error
vendor.js (128981,1)

When I navigate to the file .. this is the highlighted method
class Dom7 {                       //this is line 128981
  constructor(arr) {
    const self = this;
    // Create array-like object
    for (let i = 0; i < arr.length; i += 1) {
      self[i] = arr[i];
    }
    self.length = arr.length;
    // Return collection with methods
    return this;
  }
}

**Comment by clydin** [comment]
There is a `let` in that section of code.  This is only supported with es2015.  Once of the libraries in use is not providing es5 compatible code.

**Comment by michael-ibrahim** [comment]
> 
> 
> There is a `let` in that section of code. This is only supported with es2015. One of the libraries in use is not providing es5 compatible code.

How can I solve this? 
I tried fixing this bug in the vendor file, yet it gave another bug and so on .. etc

**Comment by clydin** [comment]
Unfortunately, usage of third party libraries is outside the scope of the CLI.  Creating an issue with the owner of the library in question would be the best method to receive further assistance.

**Comment by michael-ibrahim** [comment]
> 
> 
> Unfortunately, usage of third party libraries is outside the scope of the CLI. Creating an issue with the owner of the library in question would be the best method to receive further assistance.

How Can I detect which library caused the issue? and How can a blank project have an issue from a third library?

**Comment by alan-agius4** [comment]
If a library has code which is not compatable when the browser tries to parse the js content and encounters something which it cannot understand it will bail out.

You can identify which library is causing the issue, by reading the stack trace, understanding which dependencies you have and debugging.
