### ISSUE TITLE
from and to flags have no effect on ng update

### ISSUE THREAD

**Issue by mogusbi** [angular/angular-cli#12754]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node 10.12.0
NPM 6.4.1
NG CLI 7.03
Mac OS High Sierra

### Repro steps

I am trying to update an Angular 5 application up to Angular 6 rather than 7.

Using the command `ng update @angular/core --from=5.2.10 --to=6.1.10` it tries to update me to version 7.0.1

### Desired functionality

To be able to update to version 6 rather than 7

**Comment by clydin** [comment]
```
  --from
    Version from which to migrate from. Only available with a single package being updated, and only on migration only.
  --to
    Version up to which to apply migrations. Only available with a single package being updated, and only on migrations only. Requires from to be specified. Default to the installed version detected.
```
Those only apply to the following option:
```
  --migrate-only
    Only perform a migration, does not update the installed version.
```

You can use the following to instruct update to use the latest in the 6 version series:
`ng update @angular/core@6`

Any particular reason you wouldn't want to use 7?  There are minimal breaking changes and numerous improvements. [Blog release announcement](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c)

**Comment by mogusbi** [comment]
Commercial software so it needs to have a tried and tested version rather than the latest and greatest

**Comment by clydin** [comment]
All major versions are considered stable and go through a pre-release vetting process.  Also note that 6.x is currently considered a long term support release; whereas 7.x is under active support.  For more information please see here: https://angular.io/guide/releases#support-policy-and-schedule
