### ISSUE TITLE
ng new is working but gives a warning as 1st line of output 

### ISSUE THREAD

**Issue by indcoder** [angular/angular-cli#1276]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 Pro

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
v6.2.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new <project_name>

4. The log given by the failure. Normally this include a stack trace and some
   more information.

(node:3344) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by prijindal** [comment]
Don't worry 
This is a warning with node 
It is occurring in a lot of Plugins but it doesn't break anything

**Comment by filipesilva** [comment]
Yeap, it's just a warning, nothing to worry about at all. Can't really remove it right now without doing some wonky wacks due to a lot of libs using that dep.
