### ISSUE TITLE
Deprecate / remove experimentalAngularNext

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#12769]
Following this PR https://github.com/angular/angular-cli/pull/12709

We no longer use `experimentalAngularNext` in our code base and this is a hidden option.
 
https://github.com/angular/angular-cli/blob/f52f043e4f423554d2f5b26e75c5a77e973ce8b2/packages/schematics/angular/workspace/schema.json#L16-L20

If removed, we can clean up:
https://github.com/angular/angular-cli/blob/f52f043e4f423554d2f5b26e75c5a77e973ce8b2/packages/schematics/angular/workspace/files/package.json#L14-L30

In our next team meeting we should discuss if to remove this option since it's hidden and experimental or deprecate this and remove it in V8.

**Comment by alexeagle** [comment]
I think we can just remove this one since it wasn't documented.
