### ISSUE TITLE
Angular cli webpack prod build error in combination with OpenLayers

### ISSUE THREAD

**Issue by ArgV04** [angular/angular-cli#12760]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

macOS - Sierra
node - v8.11.2
npm - 6.3.0
ol - 5.2.0

Angular CLI: 7.0.3
Node: 8.11.2
OS: darwin x64
Angular: 7.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@angular/flex-layout              7.0.0-beta.19
@ngtools/.DS_Store                <error>
@ngtools/webpack                  7.0.3
@schematics/.DS_Store             <error>
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1

### Repro steps

The bug occurs when build a prod build including open layers library and "**buildOptimizer**": set to **true** in angular.json.

There is already an open ticket in the open layers area which describes the issue: **https://github.com/openlayers/openlayers/issues/8815**
But I don't know right if it's there the right place or better here?

### The log given by the failure

Stack trace see here too: **https://github.com/openlayers/openlayers/issues/8815**

### Desired functionality

Use case is using of open layers map with Angular 7.0.x :) in production mode

**Comment by fredj** [comment]
In a nutshell, OpenLayers defines a function and calls it to _initialize_ the module:
https://github.com/openlayers/openlayers/blob/7321541de83db157de38417cc83e32bd3eca397d/src/ol/proj.js#L495-L510

Because no code imports this `addCommon` function, the code (and the call) are removed from the build.

**Comment by clydin** [comment]
That in itself is not a problem.  The issue here is that the package has identified itself as being side effect free in its package.json.

**Comment by clydin** [comment]
Closing as the CLI is acting appropriately based on the information it is given from the package.
