### ISSUE TITLE
ng build --profile generates empty speed-measure-plugin.json

### ISSUE THREAD

**Issue by Adam-Michalski** [angular/angular-cli#12763]
`ng build --profile` generates empty `speed-measure-plugin.json`
```
- [x] bug report -> please search issues before submitting
```

### Command (mark with an `x`)
```
- [x] build
```

### Versions
`ng --version`
```
Angular CLI: 7.0.3
Node: 11.0.0
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

### Repro steps
Create new project and run `ng build --profile`

1. `ng new tester-measure`
2. `cd tester-measure`
3. `ng build --profile`

### failure
Generated empty `speed-measure-plugin.json`

### Desired functionality
Not empty `speed-measure-plugin.json`

### additional

`chrome-profiler-events.json` way to big to open in chrome. (Chrome crashes)

**Comment by Lakston** [comment]
I can confirm this on a fresh project in `7.0.3` too.

**Comment by filipesilva** [comment]
Yeah the `speed-measure-plugin` seems broken... I'm not sure why, probably incompatible with the webpack version we're using atm.

Big `chrome-profiler-events.json` are hard to open in chrome sometimes. I don't have a good answer to that. In the past when I had trouble with those I had to manually profile only on rebuilds or something. Using https://github.com/GoogleChromeLabs/ndb might also help but not sure.

**Comment by Lakston** [comment]
I took a look at the files quickly and the implementation looks ok so yes it might be a problem with the webpack version, I'll try to test that this week-end if I can find some time to do it!

**Comment by szymonbultrowicz** [comment]
Hi, any progress on that issue? It still happens in 7.1.0. Thanks.

**Comment by guillaumebouhier** [comment]
Issue is still reproducible on my side. Is there any workaround ?

**Comment by alan-agius4** [comment]
This seems to be a bug in `speed-measure-webpack-plugin`. I have created a PR to address this issue https://github.com/stephencookdev/speed-measure-webpack-plugin/pull/76
