### ISSUE TITLE
production build fails with `--sourceMap` option if sweetalert2 is used.

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#12773]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 6.2.1
Node: 10.10.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.6
@angular-devkit/build-angular     0.8.6
@angular-devkit/build-optimizer   0.8.6
@angular-devkit/build-webpack     0.8.6
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/cli                      6.2.1
@ngtools/webpack                  6.2.6
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.23.1
```

### Repro steps
clone [this repo](https://github.com/SanderElias/strangeCompilationIssue)
`yarn ng build --prod --sourceMap`

The build will end with:
![image](https://user-images.githubusercontent.com/1249083/47578762-865f4d00-d94a-11e8-957e-3fc07e65ca9f.png)

### Mention any other details that might be useful
Filed this issue at the request of @filipesilva

**Comment by filipesilva** [comment]
I suspect this is related to a TS bug while parsing comments with `allowJs` turned on, as we do inside build-optimizer. Probably in that file shown in the error. Next steps are for us to try and make a repro just using TS and see if that's the case.

**Comment by filipesilva** [comment]
I tried to make a reproduction to report this to TypeScript, and found the problem was still there in 3.1.3 but not anymore in 3.1.4. #12822 should fix this on our side.
