### ISSUE TITLE
Any build fails after updating angular-devkit/build-angular

### ISSUE THREAD

**Issue by maktarsis** [angular/angular-cli#12776]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 7.0.3
Node: 8.12.0
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cdk                      7.0.2
@angular/cli                      7.0.3
@angular/material                 7.0.2
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

### Repro steps

[Clone repository](https://github.com/maktarsis/concept-store-platform/tree/build-angular-issue)

> `npm ci` (`npm install`)
> `ng build` (`ng serve`) 

### The log given by the failure

![image](https://user-images.githubusercontent.com/21989873/47600163-6de04880-d9c5-11e8-8dcd-e35c2a224b30.png)

### Desired functionality
Normal and stable functionality without failures.

### Mention any other details that might be useful

What I have to say is that this issue initially came up from `ng update @angular/cli`
After my deep research I found out **that the cause of the error** wasn't **@angular/cli** package but **@angular-devkit/build-angular** version **0.10.3**.

**Comment by alan-agius4** [comment]
Hi I have a look at this and the issue seems to be this change. https://github.com/maktarsis/concept-store-platform/commit/8dc60f3589b83999ac02a74f4ffb6e3435383219#diff-e5e546dd2eb0351f813d63d1b39dbc48

The `baseUrl` has been changed from `src` to `./` however the actual paths have not been updated.

**Comment by maktarsis** [comment]
@alan-agius4 did you fork this project and try?

**baseUrl and Paths have nothing related with this bug**

Reopen this,
or fork and show me proof of stable **angular-devkit/build-angular** package

**Comment by clydin** [comment]
The “env/environment” module doesn’t appear to exist in the source code.  Also you are using imports prefixed with “!” which causes webpack to bypass the loaders and as a result, webpack is trying to parse typescript directly

**Comment by maktarsis** [comment]
@clydin 

Yes, that is right.

Unfortunately, now I need to refactor all paths to environment in  **0.10.3** , but ok.

Thank you.
