### ISSUE TITLE
Imported json file as indexed type always giving undefined, but not when running ng serve --prod

### ISSUE THREAD

**Issue by pnguyen9** [angular/angular-cli#12781]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Node (node --version): v9.11.1
npm (npm --version): v5.6.0
Angular CLI (ng --version): 7.0.2
OS: Debian GNU/Linux 8 (jessie)

### Repro steps
The following is a stackblitz demo link: 
https://stackblitz.com/edit/angular-h2aspf?file=tsconfig.json

If you run it on the browser, it will work properly (the console will properly display "Change language"). 

However, if you download it and run it locally, you will notice that the console will display "undefined" instead.

To run it locally:

    Download and unzip the stackblitz demo in a folder
    Run npm i in the project folder
    Run ng serve and notice the "undefined" output in the web browser console
    Run again with ng serve --prod, and notice the "Change language" output in the web browser

### The log given by the failure
None; the CLI is running properly. However, the website isn't, depending on whether I run it with `ng serve` or `ng serve --prod`. 

### Mention any other details that might be useful
I've also opened an issue on the Angular project, since I'm unsure whether it comes from Angular or the CLI: 

https://github.com/angular/angular/issues/26785

**Comment by alan-agius4** [comment]
A workaround for this is to specify `"esModuleInterop": true` in your tsconfig and change the import statement to:

```
import resources from '../assets/resources/ResourcesBundle.json';
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
