### ISSUE TITLE
Why ng new command launch a make command

### ISSUE THREAD

**Issue by adrienpsn** [angular/angular-cli#12792]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
`node --version: v11.0.0`
`npm --version: v6.4.1`
`ng --version: v7.0.3`
`uname -a: Linux valhalla 4.14.78-1-MANJARO #1 SMP PREEMPT Sun Oct 21 07:57:51 UTC 2018 x86_64 GNU/Linux`

### Repro steps
`ng new blog`

I dont understand why the `ng new` command launch a `make` command. Also, I can't install the package `npm install firebase @angular/fire --save` since `ng new` command launch a `make` command. I do not know if it's related...

**Comment by alan-agius4** [comment]
That is strange as we are not using make commands. I also had a look at the `node_modules` and it seems to no one has a `postinstall` script that uses `make` either.

**Comment by aivarsliepa** [comment]
Hi, I am not sure If I should create a separate issue for this. But for me this is the reason (I think) `ng new` command fails.
`gyp ERR! stack Error: not found: make`

**Comment by clydin** [comment]
Both `node-sass` and `fsevents` (if on MacOS) will attempt to build themselves if prebuilt binaries are not available for your platform.  Since node 11 is fairly new, prebuilt packages may take some time to materialize.
