### ISSUE TITLE
:host >>> (deep selector) does not work in .scss components

### ISSUE THREAD

**Issue by rcbyron** [angular/angular-cli#12798]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version: v8.11.3
npm --version: 6.4.1
ng --version:
Angular CLI: 6.2.3
Node: 8.11.3
OS: win32 x64
Angular: 6.1.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

### Repro steps

Create a child component:
HTML: `<div class="red">Hello Angular Community!</div>`
CSS: `.red {background-color: red; width: 100%; height: 100%; }`

Create a parent component:
HTML: `<app-child-component></app-child-component>`
SCSS (not CSS): `:host >>> .red {background-color: blue;}`

The background is not overridden to "blue" by the parent component. 

### The log given by the failure

None

### Desired functionality

The >>> should work for components with .scss files.

### Mention any other details that might be useful

By manually transpiling the .scss file, the deep selector seems to be output to the CSS file as :host > > > (with spaces) instead of :host >>>

:host /deep/ seems to work instead of >>>

**Comment by alan-agius4** [comment]
Sass itself, doesn't support `>>>` as this is deprecated.

Find more info here:
https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep
https://github.com/sass/dart-sass/issues/154
https://github.com/sass/sass/issues/2136#issuecomment-245683153
