### ISSUE TITLE
Inconsistency with Angular universal guide

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [angular/angular-cli#12795]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 7.0.3
Node: 8.11.2
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.3
@angular-devkit/build-angular     0.10.3
@angular-devkit/build-optimizer   0.10.3
@angular-devkit/build-webpack     0.10.3
@angular-devkit/core              7.0.3
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@ngtools/webpack                  7.0.3
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1
```

### Repro steps
```
>ng n test-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
>cd test-app
>ng g universal --clientProject=test-app
```

### The log given by the failure
`ng g universal` does not generate server.ts, webpack.server.ts and does not produce additional package.json commands for universal build as mentioned in https://angular.io/guide/universal

### Desired functionality
Upon using this command, I expect fully functional universal app to be generated. But if such behavior is intended, then probably a proper `ng g universal` [documentation is required](https://angular.io/cli/generate#universal-command): maybe I just mixed up its use-cases? What should it generate? How to use output result?

**Comment by alan-agius4** [comment]
There is a currently a PR to fix some issues regarding the Angular Universal documentation.

https://github.com/angular/angular/pull/26444

In the documentation however, it is stated clearly that you need to create the `server.ts` 
> At the root level of your project, next to package.json, create a file named server.ts and add the following content.

**Comment by alan-agius4** [comment]
Closing this in favor of https://github.com/angular/angular/issues/28158
