### ISSUE TITLE
404: fse-v1.2.4-node-v67-darwin-x64.tar.gz 

### ISSUE THREAD

**Issue by MingxunBai** [angular/angular-cli#12803]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Command (mark with an `x`)
```
- [x] npm i -g @angular/cli
```

### Versions

macOS High Sierra
node: v11.0.0

### Repro steps

```
npm i -g @angular/cli
npm i -g @angular/cli@6.1
```
same error

### The log given by the failure

```
> fsevents@1.2.4 install /usr/local/lib/node_modules/@angular/cli/node_modules/fsevents
> node install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.0.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
```

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI.

`fsevents` events doesn't seem to support Node 11 yet. Please contact the author(s) of the fsevents project or file an issue on their issue tracker.
