### ISSUE TITLE
change scss partial file not cause main file updated

### ISSUE THREAD

**Issue by cuiliang** [angular/angular-cli#1280]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Win10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
ng --version:
```
Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Leal\node_modules\angular-cli\lib\cli\index.js:5:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```
the real version is 1.0.0-beta.9. I reinstalled angular-cli for several times, it can run `ng build` `ng serve` normally but can not run `ng --version`.

node version:
v6.2.1

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
project created with angular-cli.

added the following code to 'angular-cli-build.js' to deal with partial scss files:
```
 "sassCompiler": {
      "cacheExclude": [/\/_[^\/]+$/]
   }
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
no error.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

running `ng serve`
when partial file changed, their will be a rebuild action on angular-cli,
but the output css not updated.
I have to change the main scss file (for example insert a space character), then the output css file will be updated.

**Comment by Madd** [comment]
Remove cacheExclude option. Partials are ignored but watched by default in 1.0.0-beta.9.

**Comment by cuiliang** [comment]
@Madd Working now, thanks.
