### ISSUE TITLE
[feature] The chrome profiler and speed measure file should be added to the gitignore file

### ISSUE THREAD

**Issue by Lakston** [angular/angular-cli#12804]
```
- [X] feature request
```

### Command (mark with an `x`)
```
- [X] build --profile
```

### Versions
npm: 6.4.1
Angular CLI: 7.0.3
Node: 10.12.0
OS: darwin x64
Angular: 7.0.1

### Desired functionality
Generating a new project should add the profiler and spead measure file to the gitignore by default.

Maybe that's something I can take care of ?

**Comment by alan-agius4** [comment]
Good idea, it needs to be added here: https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/__dot__gitignore

**Comment by Lakston** [comment]
Should I close this issue since it's been merged or is it going to be done automatically ?
