### ISSUE TITLE
main bundle contains both ngfactory + fesm5, do we need both?

### ISSUE THREAD

**Issue by x1c0** [angular/angular-cli#12807]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report/question?
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
```

### Versions
Node: v9.0.0
npm: 6.4.1
ng: 7.0.2
macOS Mojave

### Repro steps
- I have a library generated with CLI called epp-core.
- I build that library and publish it to a local npm.
- I imported that library on another project and run:
- `ng build --prod --stats-json`
- `webpack-bundle-analyzer dist/stats.json`

### The log given by the failure
No error

### Desired functionality
When I analyse the project that imports the library I see this:

![image](https://user-images.githubusercontent.com/2421483/47721468-79936f80-dc50-11e8-8d16-628e191ef6e1.png)

Is that normal that I have both ngfactory and fesm5 on my main bundle? can this be optimised? Sorry if this is a silly question :)

**Comment by filipesilva** [comment]
It is the intended behaviour, yes. `*.ngfactory.js` files contain code generated by the AOT compiler and are needed in AOT mode in general. You can't see it in webpack-bundle-analyzer but there are also also `.ngfactory.js` files for all your app components.
