### ISSUE TITLE
Debug angular-cli generated application chrome/ vscode

### ISSUE THREAD

**Issue by ankeshdave** [angular/angular-cli#1281]
I was trying to debug my application (No modification) created using `ng init` command in chrome and vscode (Default environment-Debug).
I was not able to find the **`*.ts`** files in the output folder 'dist'. On further searching for **`.ts`** files i found the files in the `tmp` directory with a random generated folder path.

How can configure **`angular-cli`** build so that i can emit the `*.ts` files in the 'dist' folder so vscode debugger [`vschrome debugging extension`] (https://github.com/Microsoft/vscode-chrome-debug) can find all files ` [*.ts,*.js,*.map] ` and use them for debugging
Also : #1223 
is
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  
```
All.
```
2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
```
angular-cli: 1.0.0-beta.8
node: 6.2.2
os: win32 x64
```
.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by bthharper** [comment]
See https://github.com/angular/angular-cli/issues/1266.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.

**Comment by santoshsas** [comment]
@filipesilva can you provide VsCode launch config and any other steps that i need to make it work with Chrome extension

**Comment by code1line** [comment]
I would like to have these steps too. Thx!

**Comment by arfeifei** [comment]
I would like to have these steps too. Thx!

**Comment by zoiverd** [comment]
+1

**Comment by filipesilva** [comment]
@santoshsas @code1line @arfeifei @zoiverd see https://github.com/angular/angular-cli/issues/2453 for a usable config.

**Comment by willyelm** [comment]
have you tried https://github.com/atom-bugs/atom-bugs-chrome?
