### ISSUE TITLE
Proposal: fileReplacements generator support

### ISSUE THREAD

**Issue by kyubisation** [angular/angular-cli#12810]
### Proposal
configuration.fileReplacements currently supports { replace: string, with: string }.
This proposal wants to add support for { replace: string, withGenerator: string }, where "withGenerator" is the path to the generator file.
The generator file exports a function, which generates the code/content that should replace the file defined in "replace".

### Motivation
This would enable more reusability for build-time configuration. The generator could be configured via environment variables. (See #3855 or #4318)

### Open Questions
- Is this even a feature that should be supported?
- Is "withGenerator" an appropriate name for this functionality?
- Should *.ts and/or esm be supported as generators?
- Should an cli argument like --envVar=ENV_VAR=some_value be supported or should this be left to tools like cross-env?

### Implementation Proposal
This would be my first contribution to angular-cli. I'm not overly familiar with the code base, so I will most likely need some guidance, if this proposal is accepted.
For this I'll provide an outline of my proposal implementation:
- schema.d.ts: New interface GeneratorFileReplacement and add it to FileReplacement
- normalize-file-replacements: Adapt normalizeFileReplacements
- build-options.ts: Union type for fileReplacements
- typescript.ts: Adapt hostReplacementsPaths to contain with or withGenerator
- angular_compiler_plugin.ts: Split normal replacement and generator replacement potentially with a new (delegator) host implementation

The potential host implementation is my big question mark. Would it work to implement a host similar to ResolverHost, that delegates most functionality, but overrides read(path: Path) (and other appropriate methods), which executes the generator?

**Comment by no-more** [comment]
That's exactly what I need, and according to #4318 it's a highly requested feature.

Please implement this.

Thanks.

**Comment by kyubisation** [comment]
Due to shifting priorities I have not yet spent any time on this issue.
I should be able to provide an initial implementation by end of december. However, whether that will be accepted depends on the Angular CLI team.

**Comment by mgechev** [comment]
@kyubisation I'd recommend you to write a design document so that we can review it first; here's a template https://goo.gl/YCQttR.

**Comment by kyubisation** [comment]
In my eyes this is no longer necessary. At least my requirements can be met with fileReplacements and the builders API.
