### ISSUE TITLE
Automatically alphabetizing barrels introduces circular dependencies in some cases

### ISSUE THREAD

**Issue by Blasz** [angular/angular-cli#1282]
##### Version
```
$ ng --version
(node:11205) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.6
node: 6.2.1
os: linux x64
```

##### Repro steps

1. Structure components in a shared folder where certain ordering in the barrel is necessary - http://plnkr.co/edit/vDsAp8dzqBVsl7C1G8Q7?p=preview
2. Generate a new module in the same shared folder

    ```
app/ $ ng generate pipe shared/something
    ```
3. Angular-CLI re-orders the shared barrel file alphabetically and causes circular dependency issues

Related to https://github.com/angular/angular/issues/9334 and introduced in https://github.com/angular/angular-cli/issues/582

I'm not sure what the best way around this is but I think it involves a higher level discussion where, when and how barrels should be used.

**Comment by filipesilva** [comment]
Closed as obsolete following #1455.
