### ISSUE TITLE
 JIT Compiler errors

### ISSUE THREAD

**Issue by Frozen-byte** [angular/angular-cli#12832]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
nope 8.10
angular 7.0.1
angular-cli 7.0.3

### Repro steps

Use this repository to reproduce the error. 
[GUI-cTor_minimal_repro.zip](https://github.com/angular/angular-cli/files/2542585/GUI-cTor_minimal_repro.zip)

### The log given by the failure
`core.js:1394 Uncaught TypeError: ctorParameters.map is not a function` [jit-error.log](https://github.com/angular/angular/files/2536511/jit-error.log)

### Desired functionality
After upgrading from Angular v6
When starting my app with `ng serve` the App crashes on browser with an error ([jit-error.log](https://github.com/angular/angular/files/2536511/jit-error.log) appended).
When starting my app with `ng serve --aot` the App runs well in browser.
ng serve jit compiling should not fail with error
`core.js:1394 Uncaught TypeError: ctorParameters.map is not a function`

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Frozen-byte** [comment]
Use this repository to reproduce the steps. 
[GUI-cTor_minimal_repro.zip](https://github.com/angular/angular-cli/files/2542585/GUI-cTor_minimal_repro.zip)

I pinned the problem down to MatTableModule, maybe it is a Problem from "@angular/material" ?

**Comment by alexzuza** [comment]
Related to https://github.com/angular/material2/pull/13709 and https://github.com/angular/material2/pull/13834
