### ISSUE TITLE
Math minified on --prod build

### ISSUE THREAD

**Issue by Gamblt** [angular/angular-cli#12838]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report
```

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ ] serve
```

### Versions
Angular CLI: 7.0.3
Node: 8.12.0
Npm 6.4.1 
OS: linux x64
Angular: 7.0.1

After update angular from v6.1 to v7 with all dependencies **serve** and **build** with flag _--prod_  make an issue in crypto-js library with native Math function.
`ERROR TypeError: Cannot read property 'ceil' of undefined`  

Library code: `words.length = Math.ceil(sigBytes / 4);`
Minified code: `t.length=r.ceil(e/4)`
r - undefined as expected.

### Desired functionality
Save native window.[Objects] without minification

### Repro steps

```
ng new testapp
cd ./testapp
npm install crypto-js --save
```

Update app.component
```
import { Component } from '@angular/core';
import * as CryptoJS from 'crypto-js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'Title:' + CryptoJS.SHA256('helloworld');;
}

```
`ng serve --prod
`

**Comment by alan-agius4** [comment]
This is an upstream bug https://github.com/terser-js/terser/issues/156, which should been solved by https://github.com/terser-js/terser/pull/154

However, it has not been released yet.

**Comment by LosD** [comment]
Ugh. Happens for me as well. Just my luck that I updated right before adding PWA to our app, which kinda needs production builds to make sense.

Oh well, at least it seems like a fixed release of Terser is imminent (I guess it's possible to manually bump Terser as soon as they release, instead of waiting for an angular-cli release to pick it up).

**Comment by alan-agius4** [comment]
@LosD actually, the package bump will be picked automatically as `Terser` is not a direct dependency of Angular CLI, but rather a transitive one.

**Comment by KClough** [comment]
Our team resolved this issue by manually installing the fixed release of Terser.

**Comment by Temkit** [comment]
This might be helpful, https://github.com/angular/angular-cli/issues/12414

**Comment by kzc** [comment]
Please try `terser@3.10.10` and report your findings in this thread.

You'd have to adapt the instructions in this post to install this new terser version: https://github.com/angular/angular-cli/issues/12414#issuecomment-434615979

**Comment by alan-agius4** [comment]
Closing a terser released a fix for this.
