### ISSUE TITLE
Uncaught Error: Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by ljorge19** [angular/angular-cli#12844]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ x ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

the same structure tha i use in angular 4, 5 and 6 it doesn't work for angular 7, i got this error after compile the system cannot access the Jquery broking my code, i got this isssue and i give up to use angular 7 and came back to angular 6.1.0.

this error appears just in my console, i can compile but my code broke if i have to load some bootstrap that needs jquery's structure.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
