### ISSUE TITLE
CLI 7.0.4 does not include app.component.scss

### ISSUE THREAD

**Issue by EatonZ** [angular/angular-cli#12846]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
CLI 7.0.4

### Repro steps
`ng new --minimal=true --prefix="new-app" --skip-git=true --skip-install=true --skip-tests=true --style="scss"`

Creating a new project with that excludes the normally included app.component.scss file. Both the actual file and the style reference inside of app.component.ts (pictured below) are missing.

It's possible this was an intentional change, but I couldn't find it.

![2018-11-01_22-27-29](https://user-images.githubusercontent.com/3020941/47890517-8f0dc280-de25-11e8-9936-2df9b0c5fde0.png)

**Comment by alan-agius4** [comment]
Hi, this is by design, when using the `minimal` option only inline styles are available.
