### ISSUE TITLE
ng build with AOT is not working

### ISSUE THREAD

**Issue by woppa684** [angular/angular-cli#12841]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 7.0.3
Node: 8.11.3
OS: win32 x64
Angular: 7.0.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.3
@angular-devkit/build-angular      0.10.3
@angular-devkit/build-ng-packagr   0.10.3
@angular-devkit/build-optimizer    0.10.3
@angular-devkit/build-webpack      0.10.3
@angular-devkit/core               7.0.3
@angular-devkit/schematics         7.0.3
@angular/cli                       7.0.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.3
@schematics/angular                7.0.3
@schematics/update                 0.10.3
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.4
webpack                            4.19.1
```

### Repro steps
According to the documentation at https://angular.io/cli/build I can use --aot for a library build. When I try to call it with 
```
ng build @scope/lib --aot 
```
I get  `Unknown option: '--aot'`

### Desired functionality
It works as expected and documented.

**Comment by alan-agius4** [comment]
Closing in favor of 
https://github.com/angular/angular/issues/26569

**Comment by woppa684** [comment]
Is a library truly build in AOT mode? When I load the generated UMD bundle with SystemJS I don't see any factories for example, even though I specified a component as entrycomponent. Anyway, irrelevant to my initial question and yeah, the docs should definitely be improved ;)

**Comment by woppa684** [comment]
@alan-agius4 Where dit you get that libraries are "solely build in AOT mode"? ng-packagr and the Angular package format don't ay anythin about it. It's only specified that there's metadata in the output to be used by the AOT compiler. That's not exactly the same thing I guess ;) So I need to do something else to get a factory for my entrycomponent in my bundle then. Should I make another issue for this then? As it appears now there's no out of the box option to use AOT in a library, which makes it quite useless as I see it.
