### ISSUE TITLE
Angular cli adds script tags on build to beginning of index file

### ISSUE THREAD

**Issue by natcohen** [angular/angular-cli#12864]
I am currently using a **pug** file as index in my angular project. When building, Angular Cli adds the following lines:

```
<script type="text/javascript" src="/static/runtime.js"></script>
<script type="text/javascript" src="/static/polyfills.js"></script>
<script type="text/javascript" src="/static/vendor.js"></script>
<script type="text/javascript" src="/static/main.js"></script>
```
In Angular cli v1.6 it was adding these lines to the end of file. In Angular cli v7, it is adding them at the beginning of file. Adding to the beginning messes everything up. Would it be possible to reverse this behaviour?

**Comment by alan-agius4** [comment]
Pug is not something that we officially support.

Templates must be HTML parsable, and must have the following tags, ‘html`, `head` and `body`.
