### ISSUE TITLE
Custom environment on ng build and ng serve

### ISSUE THREAD

**Issue by dpolicastro** [angular/angular-cli#12865]
### Bug Report or Feature Request 
```
- [x] feature request
```

### Command 
```
- [x] build
- [x] serve
```

### Desired functionality
I would like to set the environment.ts file on ng serve and ng build, for example, running `ng serve|build --env=dev|homolog|prod|custom-env`. I didn't find anything related to env vars on cli documentation, neither anything to show me how to configure my `angular.json` to make this happen.

**Comment by alan-agius4** [comment]
What you need to use is the `configuration` option

Create a section similar to the `production` section in your `angular.jaon`

Then you can use it something like;
```
ng build —configuration qa
```



See: https://angular.io/guide/workspace-config#project-configuration-options

**Comment by dpolicastro** [comment]
Thank you sir, I'll check it out
