### ISSUE TITLE
Can't install angular/cli

### ISSUE THREAD

**Issue by enemysik** [angular/angular-cli#12862]
### Bug Report or Feature Request
```
- [x] bug report
```
### Versions
```
Node: 10.13.0
NPM: 6.4.1
```

### Repro steps
```
I type to cmd this command: npm install -g @angular/cli
After this it interrupt on step:
/ fetchMetadata: sill resolveWithNewModule punycode@2.1.1
```

### The log given by the failure
```
No logs
```

### Desired functionality
```
I want to install @angular/cli
```

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
