### ISSUE TITLE
unable to install angular cli

### ISSUE THREAD

**Issue by pardhasaradhihulk** [angular/angular-cli#12861]
kindely get solution to this error

i installed node and then installing angular

npm install -g @angular/cli
after that if it is installed correclty or not checking purpose i m using ng -v command it is unable to display the angular cli picture
![screenshot 1](https://user-images.githubusercontent.com/22253045/47953280-8641fb80-dfa1-11e8-80af-7624e709ddea.png)

**Comment by wvanderdeijl** [comment]
Have you tried `ng version` or `ng v`, so without the dash before the v. As far is I can see this is what the screenshot says

**Comment by alan-agius4** [comment]
```
ng --version
ng --v
ng -v
ng version
```

Should all the valid, however there is a bug that single dashed aliases are not working at the moment.
