### ISSUE TITLE
Error: loading chunk xx failed

### ISSUE THREAD

**Issue by adriellr01** [angular/angular-cli#12869]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
```

### Versions
NodeJs v8.12.0
npm 6.4.1
ng 6.2.3
Hosting on Windows Server

### Repro steps
Deploy with ng build --prod.
Open browser on the page with new deployed changes

### The log given by the failure
Browsers show the following error:
  Uncaught SyntaxError: Unexpected token <
  ERROR Error: Uncaught (in promise): Error: Loading chunk 25 failed.
Why the browsers are loading non-existing files instead of new chunk JS files?

### Desired functionality
Browsers should load automatically new chunk JS files correctly instead of old files (non-existent).

### Mention any other details that might be useful
When I hit F5 all files load correctly, but sometimes when I open the site again, the same error are shown and I have to refresh again. I have been looking for a solution for many days but I could not find a final solution.
Any suggestion or comment would be very helpful.
Thanks

**Comment by alan-agius4** [comment]
Do you have `disable cache` enabled?

**Comment by adriellr01** [comment]
Hello, thanks for your comments,
I can disable browser cache, but what happends when I deploy new changes and no expert users have the same problem. If the browser doesn't support reloading changes then the site itself should force a complete reload or something like that. The idea is that users can see the changes without having knowleage on cache stuffs. 
I am using ng build to generate files to deploy on production in a dedicated server (This happens on production).

**Comment by alan-agius4** [comment]
Thanks for some clarifications, the files should get updated as soon as you build, since each of the file are fingerprinted.

I am not sure if that's the case, but is it possible that you are doing the following?;
1. open the site
2. do a deploy 
3. Try to navigate to a lazy route

**Comment by clydin** [comment]
@adriellr01 Your server should set the appropriate caching headers.  For more details please see here: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI.
