### ISSUE TITLE
value.split is not a function

### ISSUE THREAD

**Issue by scrivy** [angular/angular-cli#1286]
1. Mac OSX El Capitan 10.11.5
2. angular-cli: 1.0.0-beta.9, node: 4.4.6, os: darwin x64
3. Repro steps.

Run ng init to upgrade from angular-cli 1.0.0-beta.7 to beta.9, when asked to Overwrite src/favicon.ico? try to diff

4.

> ? Overwrite src/favicon.ico? Diff
> value.split is not a function
> TypeError: value.split is not a function
>     at Object.lineDiff.tokenize (/srv/fuma/frontend/node_modules/angular-cli/node_modules/diff/lib/diff/line.js:22:32)
>     at Object.diff (/srv/fuma/frontend/node_modules/angular-cli/node_modules/diff/lib/diff/base.js:36:39)
>     at diffLines (/srv/fuma/frontend/node_modules/angular-cli/node_modules/diff/lib/diff/line.js:47:19)
>     at structuredPatch (/srv/fuma/frontend/node_modules/angular-cli/node_modules/diff/lib/patch/create.js:18:83)
>     at createTwoFilesPatch (/srv/fuma/frontend/node_modules/angular-cli/node_modules/diff/lib/patch/create.js:131:14)
>     at Object.createPatch (/srv/fuma/frontend/node_modules/angular-cli/node_modules/diff/lib/patch/create.js:151:10)
>     at /srv/fuma/frontend/node_modules/angular-cli/node_modules/angular-cli/lib/models/file-info.js:65:23
>     at lib$rsvp$$internal$$tryCatch (/srv/fuma/frontend/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
>     at lib$rsvp$$internal$$invokeCallback (/srv/fuma/frontend/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
>     at lib$rsvp$$internal$$publish (/srv/fuma/frontend/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11)

**Comment by filipesilva** [comment]
That's a bug that I don't think we can fix right now. The `ng init` command on the version of `ember-cli` we use fails when diffing images.

**Comment by dzonatan** [comment]
I think this is fixed by #2617 and can be closed.

**Comment by filipesilva** [comment]
@dzonatan is most correct, thanks!
