### ISSUE TITLE
SessionId will change when set "rewrite" in proxy.conf.json

### ISSUE THREAD

**Issue by ChenXiangY** [angular/angular-cli#12875]
SessionId will change when set "rewrite" in proxy.conf.json
![image](https://user-images.githubusercontent.com/22198015/48071879-4cc5f600-e216-11e8-8765-0e25dc6463b0.png)

Sorry for my poor english.
I try to do this..But my backend will receive different sessionId of every request.

**Comment by ChenXiangY** [comment]
So sorry for my poor English, I will try my best to say my problem clearly..
I hava found the reason, my backend is java,  which is running at http://localhost:8082/MusicJava...
but my frontend which uses Angular will send a post request at http://localhost:4200/api..
My code:
![image](https://user-images.githubusercontent.com/22198015/48108369-df4db000-e27d-11e8-9571-e2133813c277.png)

----
I try to change the file `proxy.conf.json` so that I can make my request /api/... forward to /MusicJava/api/..., however, when I send a request I can get a correct result, but cookie without setting path by backend will set path of cookies as 'MusicJava' such as sessionid..
 
![image](https://user-images.githubusercontent.com/22198015/48108545-829ec500-e27e-11e8-923a-54adc3d3adf8.png)

----
everytime I send a request, I can't take cookie correctly, because current url is `http://localhost:4200/`, not `http://localhost:4200/MusicJava/` where the cookie at..(I think,I don't konw whether it's wrong or correct, sorry.)

----

I fixed it by change my send url like this.
![image](https://user-images.githubusercontent.com/22198015/48108789-9a2a7d80-e27f-11e8-84b5-03b1f4150253.png)
Then all request will take cookie correctly...
I can get correct result now but I still can't understant why...I thought `pathRewrite` just change my send url, It seems like I'm wrong..
Could you please tell me why? Apologize again for my poor English.
I have tried google, but I can't get answer...
Thank you!

**Comment by alan-agius4** [comment]
From what I can see, it is because the cookie is being dropped with a path of MusicJava, which means it has a restriction for the path.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
