### ISSUE TITLE
Start using fixed versions of 3rd party packages (or at least same minor version) in LTS versions

### ISSUE THREAD

**Issue by dozer75** [angular/angular-cli#12874]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Desired functionality

As seen in issue #12866 the usage of non fixed versions causes lots of problems when a dependent package breaks Angular, this is not the first time and probably not the last time. So I suggest that an LTS version uses fixed versions of external packages to avoid issues like this. 

Waiting (like in this example 8 hours) for a fix may be costly for some users of the Angular platform. Luckily enough this fix was simple by adding webpack to your own package.json file, but it is quite costly to analyze and search for a solution when these things happens.

**Comment by alan-agius4** [comment]
Hi, we are already using fixed versions for direct dependencies in version 7.

**Comment by alexeagle** [comment]
Generally, users should use a lock file to prevent breakages. Even if we pin our direct dependencies, our transitive dependencies can still push updates which are broken and which match whatever semver range the intermediate dependency requires.

Pinning direct dependencies is only a partial fix.
We could back-port the pinning to LTS, how much work do you think that is @alan-agius4 ? If it's just a couple hours I think we should do it.

**Comment by alan-agius4** [comment]
@alexeagle, yeah it's just a couple of hours.

I'll be on it tomorrow.

**Comment by alan-agius4** [comment]
Fixed via https://github.com/angular/angular-cli/pull/13007
