### ISSUE TITLE
server dist with proxy to test/debug service worker

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#12876]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] a desperate attempt to get some help
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: v8.11.2
NPM: 6.4.1
Angular CLI: 6.1.5

### Repro steps

ng serve --prod --proxy-config proxy.conf.json

### Desired functionality

Serve from dist so that we can work with service worker

### Mention any other details that might be useful

So sorry for posting here but I have tried SO, gitter and other forums/slacks but no luck...

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by mackelito** [comment]
@alan-agius4 this is more a request..
Right now there is no way to run service worker locally using the cli..

I'm requesting a solution to serve from dist and also use the proxy.config settings

**Comment by mackelito** [comment]
@alan-agius4 sorry to bother you on this issue again but I still haven't found a solution to our problem.
We need a way to develop/test service workers locally using the proxy settings in angular.json

If you could just point us in a direction it would be great!

**Comment by alan-agius4** [comment]
Hi @mackelito, this should be possible in a couple of ways

1) Use a lite-server (https://github.com/johnpapa/lite-server) and configure a proxy (https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/servers.md#lite-server).
2) Use nginx on top of a standard node http server like lite-server, http-server etc..
