### ISSUE TITLE
ng new 2 hours to install

### ISSUE THREAD

**Issue by gilbertoalbino** [angular/angular-cli#12883]
I've run:

`ng new myapp --routing --styles=scss`

to start a new Angular 7.0.0 app, but it took nearly 2 hours to finish installing.

My computer is a:

```
i7 8th generation
16GM ram
512 SSD
Windows 10 Pro
```
I have a 240MB internet link.

Can't believe it is that slow!

But I could check that the installer got stuck in the /node_modules/.staging folders.

However, the other processes were fast.

**Comment by alan-agius4** [comment]
I am sorry, but this doesn’t seem like an Angular CLI issue. Npm installation should take only a couple of minutes. And if it’s taking much longer than that it must be something unrelated to Angular CLI. 

It might have been some intermittent issue from NPM or your environment.

This seems like a problem with your node/npm and not with Angular CLI.
