### ISSUE TITLE
generate component in src folder

### ISSUE THREAD

**Issue by sipolyashhivangi** [angular/angular-cli#12880]
I want to generate component in "src" folder not in "src/app" folder.
for example 
I run "ng generate component test1"
then this command will create folder in  "src/app/test1"
but I want component in path "src/test1"

Please advise me

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
