### ISSUE TITLE
@angular/cli v7.0.4 typescript v3.1.6 prod builds remain slow

### ISSUE THREAD

**Issue by pmnevill** [angular/angular-cli#12892]
`ng build --prod` takes ~3min locally, 20+min in our Jenkins CI build.
Prior to upgrading to v7 our prod builds were ~5min.

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```Angular CLI: 7.0.4
Node: 8.9.4
OS: darwin x64
Angular: 7.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@angular/flex-layout              7.0.0-beta.19
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```

### Repro steps

`ng build --prod`

### Desired functionality

Normal build times

### Mention any other details that might be useful

Related to #12646

**Comment by alan-agius4** [comment]
Hi, I am not quite sure, how a build of 3mins+ locally is taking 20mins+ on Jenkins. We don't differentiate between CI and local environment. Thus, a builds should be quite consistent if it runs on different machines with the same modules and resources. 

In CI, be sure that the same node packages are used. Maybe they are not being busted correctly, and if you are using a package lock, this is committed correctly.

**Comment by pmnevill** [comment]
We do commit package lock. It could be a [memory allocation](https://github.com/angular/angular-cli/issues/12646#issuecomment-437327365) issue on our VM so we'll be looking into that. The longer build times only occur on our v7 projects so if increasing memory fixes the issue I'll post back here and to the comment above.

**Comment by pmnevill** [comment]
Increasing the memory worked
