### ISSUE TITLE
Compiler hangs using v.7.0.x

### ISSUE THREAD

**Issue by bregnvig** [angular/angular-cli#12904]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: v11.0.0
npm: 6.4.1
ng: 7.0.4

OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

### Repro steps

Cant really reproduce it. 

The problem is that after I have saved one or more files 10 - 20 times over a period of time the compiler just hangs.

It could look something like this: 

```
Date: 2018-11-08T20:02:21.788Z - Hash: 3452219029f614f5d384 - Time: 1256ms
23 unchanged chunks
chunk {app-fund-fund-module} app-fund-fund-module.js, app-fund-fund-module.js.map (app-fund-fund-module) 224 kB  [rendered]
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
```
So what you see is a previous successful compiled chunk, and the browser reloads fine, then the next time I saved it just said `compiling...` and nothing more happen. If I press Ctrl+C I still need to find the process and kill it. The process is using 100% of a CPU core, at that point. 

It a rather large project and before version 7 of the CLI and Angular this never happened.

**Comment by dhardtke** [comment]
Can you try if using Nodejs 8 fixes it? I had a similar issue like that and for me NodeJS 11 was the root cause (although, I am on Windows).

**Comment by bregnvig** [comment]
@dhardtke I'll try that! Thank you :-) I'll report back

**Comment by bregnvig** [comment]
Seems to be related to the node version. Going back to 10.9.0 fixed the problem.

@dhardtke Thank you very much. It was driving me insane!

**Comment by filipesilva** [comment]
Yeah https://github.com/angular/angular-cli/issues/12816 has reports of problem with node 11.. we haven't gotten around to testing it on CI yet :/
