### ISSUE TITLE
ng serve error  Initializers are not allowed in ambient contexts 

### ISSUE THREAD

**Issue by ReneI** [angular/angular-cli#12906]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### The log given by the failure

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-11-08T22:00:30.731Z
Hash: f117422efbf14779f0da
ERROR in node_modules/@angular/common/http/src/response.d.ts(253,21): error TS1039: Initializers are not allowed in ambient contexts.
Time: 17685ms
chunk {main} main.js, main.js.map (main) 1.94 kB [initial] [rendered]
node_modules/@angular/common/http/src/response.d.ts(259,19): error TS1039: Initializers are not allowed in ambient contexts.
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 698 bytes [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.22 kB [entry] [rendered]
node_modules/@angular/common/src/directives/ng_if.d.ts(122,65): error TS2304: Cannot find name 'NonNullable'.
chunk {styles} styles.js, styles.js.map (styles) 156 kB [initial] [rendered]

chunk {vendor} vendor.js, vendor.js.map (vendor) 328 kB [initial] [rendered]
i ｢wdm｣: Failed to compile.

### Mention any other details that might be useful
   

Angular CLI: 7.0.4
Node: 9.11.1
OS: win32 x64
Angular: 6.1.10
... animations, compiler, compiler-cli, core, elements, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.7
@angular-devkit/build-angular     0.8.7
@angular-devkit/build-optimizer   0.8.7
@angular-devkit/build-webpack     0.8.7
@angular-devkit/core              0.8.7
@angular-devkit/schematics        7.0.4
@angular/cdk                      7.0.3
@angular/cli                      7.0.4
@angular/common                   7.0.3
@angular/fire                     5.1.0
@angular/language-service         5.2.11
@angular/material                 7.0.3
@ngtools/webpack                  6.2.7
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.25.1

**Comment by alan-agius4** [comment]
You seem to be using @angular/common version 7, instead of the version used by the other @angular/* packages. 

Version 7, needs the other packages to be updated to the same version and also requires TypeScript 3.1.x.

My recommendation would be either upgrade to version 7 or downgrade @angular/common package.

**Comment by filipesilva** [comment]
Closing as no more information has been provided.
