### ISSUE TITLE
add multiple proects in single angular.json 

### ISSUE THREAD

**Issue by sipolyashhivangi** [angular/angular-cli#12900]
How can we add multiple projects in centralized angular.json? 
If we add 10 projects in single angular.json then how can we make angular.json small because 10 projects in single angular.json file makes file so large?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
