### ISSUE TITLE
@angular/cli 7.0.5 does not install -- missing dependency

### ISSUE THREAD

**Issue by spikemadden** [angular/angular-cli#12907]
### Bug Report or Feature Request
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc
```

### Versions
root@3a48fcb74f54:/app# node --version
v10.13.0
root@3a48fcb74f54:/app# npm --version
6.4.1
root@3a48fcb74f54:/app# uname -a
Linux 3a48fcb74f54 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linux

### Repro steps
npm install -g @angular/cli@7.0.5

### The log given by the failure
root@3a48fcb74f54:/app# npm install -g @angular/cli@7.0.5
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @schematics/update@0.10.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-08T22_54_53_573Z-debug.log

### Desired functionality
To be installed.

### Mention any other details that might be useful
It looks like the dependency: @schematics/update@0.10.5 is not available.

**Comment by mhosman** [comment]
Same problem here!!!

```
npm ERR! notarget No matching version found for @schematics/angular@7.0.5
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular/pwa'
npm ERR! notarget
```

**Comment by clydin** [comment]
If you are using a proxy or cache, the registry information may have not propagated fully.

Both of them are published:
https://www.npmjs.com/package/@schematics/angular
https://www.npmjs.com/package/@schematics/update

**Comment by mhosman** [comment]
Yes, now working
