### ISSUE TITLE
Autoprefix CSS in libraries

### ISSUE THREAD

**Issue by Eddman** [angular/angular-cli#12901]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [x] feature request
```
### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
$ node --version
v8.12.0
$ npm --version
6.4.1
$ ng --version
Angular CLI: 6.2.7
Node: 8.12.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.7
@angular-devkit/build-angular     0.8.7
@angular-devkit/build-optimizer   0.8.7
@angular-devkit/build-webpack     0.8.7
@angular-devkit/core              0.8.7
@angular-devkit/schematics        0.8.7
@angular/cdk                      6.4.7
@angular/cli                      6.2.7
@angular/material                 6.4.7
@ngtools/webpack                  6.2.7
@schematics/angular               0.8.7
@schematics/update                0.8.7
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.16.4
```

### Repro steps
Try to build project with `@angular/material` for instance. It contains a lot of CSS files bundled into `*.metadata.json`.

I'm fine with the result of `ng serve` as it is not using AoT compilation, but for `--prod` (AoT) build that is using `*.metadata.json` I'd expect CSS to be processed by `postcss`. 

### Desired functionality
I know about #11480. But in my case we use external libraries, eg. `@angular/material` with components that already have CSS bundled inside + they have `*.metadata.json`. It should be easy to run `postcss` for styles in this file.

Otherwise all external libraries can't be used.

**Comment by alan-agius4** [comment]
This is not something that is supported and it something pretty complex to achive as CSS in components within libraries is never preprocessed by the application build system. Libraries, when built, always inline their CSS, so that ends up being unprocessable as well. It should be up to the library authors to autoprefix their CSS.

**Comment by alan-agius4** [comment]
Hi @Eddman, thanks for this feature request. However currently this request is out of scope of the Angular CLI.
