### ISSUE TITLE
NPM ERR Extraneous after install Angular-cli beta9

### ISSUE THREAD

**Issue by choopage** [angular/angular-cli#1290]
1. 
OSx

2. 
(node:492) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.9
node: 6.2.2
os: darwin x64

3. 
After running `npm -g list --depth=0`

4. 
![screen shot 2016-07-06 at 9 39 57 am](https://cloud.githubusercontent.com/assets/6467136/16605060/0e6e8c2c-435e-11e6-8c8e-046c2264cb27.png)

**Comment by 5amfung** [comment]
Did you try uninstall first and install again?   I think I got similar error when I just run npm install with uninstalling first.

**Comment by choopage** [comment]
Hi @5amfung I did uninstall, clean cache, and install before posting this here.

```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
```

**Comment by cristiandeschamps** [comment]
See -> https://github.com/npm/npm/issues/13284

My fix right now:  Adding this to the host file:
151.101.16.162  registry.npmjs.org

**Comment by borntorun** [comment]
This stituation still happens. Don't think it is related to the npm issue.
I uninstalled angular-cli, cleaned the cache and installed latest version 1.0.0-beta.9
Using node 4.4.5

![erros](https://cloud.githubusercontent.com/assets/820692/16958738/b58a5100-4dd9-11e6-9d09-5db14d25adf5.jpg)

**Comment by oscar6echo** [comment]
Same here.
Cf issue https://github.com/npm/npm/issues/10004

**Comment by ryanaltvater** [comment]
@oscar6echo I'm still experiencing the same issue as @borntorun. I've tried updating everything, and I've referenced every suggestion on npm issue #10004. Nothing seems to work, yet that issue is closed with people still experiencing the problem. Do we know if there's a solution for this yet? Or whether it's an npm issue or angular-cli issue?

For reference, I'm using node v6.4.0 and npm v3.10.6

**Comment by oscar6echo** [comment]
It is not really an answer, but I have installed `angular-cli@1.0.0-beta.11-webpack.2`.
Most of the npm ERR messages disappear.
````
Olivier@Central:~ (3) $ npm list -g --depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.11-webpack.2
├── npm@3.10.3
````
There is still
````
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6
````
But it seems to have no impact besides this message...

**Comment by choopage** [comment]
same as @oscar6echo. I installed `angular-cli@1.0.0-beta.11-webpack.2` and most of the npm ERR messages disappeared too. I still have 2 errors which is the same as mentioned above.

**Comment by mcferren** [comment]
I installed angular-cli@1.0.0-beta.11-webpack. and am also seeing the two errors after the install and also as a result of npm -g list --depth=0

Afterwards when I run ng --help, I am still seeing ng: command not found
