### ISSUE TITLE
Error caused by missing commands/*.md file

### ISSUE THREAD

**Issue by square-li** [angular/angular-cli#12905]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 7.0.4
Node: 10.13.0
OS: darwin x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@angular/flex-layout              7.0.0-beta.19
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```

### Repro steps
Turn on Yarn AutoClean which would remove *.md file after install. By default, yarn Autoclean would remove all markdown files under library.
Then the run build would give errors.

### The log given by the failure

File myProject/node_modules/@angular/cli/commands/add.md was not found while constructing the subcommand add.
add: File myProject/node_modules/@angular/cli/commands/add.md was not found while constructing the subcommand add.
    at parseJsonSchemaToSubCommandDescription (/node_modules/@angular/cli/utilities/json-schema.js:59:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
error Command failed with exit code 1.

### Desired functionality
What would like to see implemented?
It is going to build the project.
What is the usecase?
Project build and serve etc.

### Mention any other details that might be useful
Disable Autoclean function or remove .md from .autoclean, then run install again would solve this problem.

**Comment by alan-agius4** [comment]
`.md` files are required for Angular CLI to function properly. As `.md` files are used for help commands.

Thus md files are not safe to remove, and shouldn't be excluded when doing the auto cleaning.

**Comment by square-li** [comment]
Thanks.
