### ISSUE TITLE
All ng commands fail with common error in command-line, but work in WebStorm.

### ISSUE THREAD

**Issue by willkara** [angular/angular-cli#12918]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [x] generate
- [x] add
- [x] update
- [x] lint
- [x] xi18n
- [x] run
- [x] config
- [x] help
- [x] version
- [x] doc
```

### Versions
```
C:\Users\wkara\Resilio Sync\Development\Civis>node --version
v10.13.0
```

```
C:\Users\wkara\Resilio Sync\Development\Civis>npm --version
6.4.1

C:\Users\wkara\Resilio Sync\Development\Civis>yarn --version
1.6.0
```

Angular CLI version: 7.0.4

### Repro steps

This is a weird one. I was able to correctly generate a new Angular-CLI project within WebStorm(2018.2.5). After that, I can't run ANY **ng** based commands without the following error.

```
C:\Users\wkara\Resilio Sync\Development\Civis>ng --version
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'upath'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\wkara\AppData\Local\Yarn\Data\global\node_modules\chokidar\index.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

```

After some investigation, it turns out I can't even run it normally in PowerShell! The only way it works is if I run it in the WebStorm project creator.

### Mention any other details that might be useful

My only guess is that there's a discrepency in used node libraries for WebStorm and what's on my path for PowerShell.

**Comment by tarikhamlat** [comment]
i hade the same problem, If you blow away your node_modules directory and reinstall from scratch, you should restore the folder.

cd your_project_folder
rm -rf node_modules
npm install

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
