### ISSUE TITLE
Update .editorconfig website

### ISSUE THREAD

**Issue by EatonZ** [angular/angular-cli#12923]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

The CLI generates a .editorconfig file in new projects. Consider changing the website reference at the top of the file from this:
`# Editor configuration, see http://editorconfig.org`

...to this:
`# Editor configuration, see https://editorconfig.org`

The website redirects to HTTP**S** now, so this file should be updated accordingly.

**Comment by alan-agius4** [comment]
PRs are welcome.
