### ISSUE TITLE
"ng generate" create file name is too long

### ISSUE THREAD

**Issue by TimChen44** [angular/angular-cli#12929]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] feature request
```

### Command (mark with an `x`)
```
- [X] generate
```

### Versions
`node 11.1.0`, `npm 6.4.1` and `ng 7.0.0`.
 Windows 10

### Desired functionality
'ng generate' can create template very good, but create file name is too long.
Like the "my.component.ts", too much space, tab display too little
![p](https://user-images.githubusercontent.com/7581981/48312490-54a4e200-e5ea-11e8-9dba-bfa0647b64d1.PNG)

Want add option, can output file name like 
"my.component.ts" --> "my.c.ts" 
"my.service.ts" --> "my.s.ts
etc.

**Comment by alan-agius4** [comment]
Hi, the file names here are created based on the style guide https://angular.io/guide/styleguide#symbols-and-file-names

Changing this to something else would mean not to follow the style guide with is not a good practice.

If you really want to change this, you are free to do so by extending the schematics and implement that logic to rename the files. There are a couple of good articles on how to extend a schematics.
