### ISSUE TITLE
Jasmine-core and karma-jasmine-html-reporter` upgrade in package.json needed

### ISSUE THREAD

**Issue by nasreddineskandrani** [angular/angular-cli#12922]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Command (mark with an `x`)
```
- [ x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.5

### Repro steps
When i generate an angular project with the version on top of the cli.,
I get a version of `jasmine-core` and `karma-jasmine-html-reporter` that doesn't support the log
*ERROR: 'Spec test b has no expectations.'*

**Example explained:**
---------------------------
i have a test that i crafted in stackblitz here:
https://stackblitz.com/edit/testing-false-positiv?file=src%2Fapp%2Ftest-b%2Ftest-b.service.spec.ts

focus on the fact that one test expectation is not reached and the test-reporter is mentionning: 
`SPEC HAS NO EXPECTATIONS ...1a`

So i went to angular-cli => created a project and added the same test in the new project as in stackblitz.
the output was:
![img_no_error](https://user-images.githubusercontent.com/1953635/48296055-6a869b80-e460-11e8-8e56-db23d15ea064.png)

No error is flagged.

**Solution to see the error:**
upgraded in `package.json`
`jasmine-core` to `3.0.0` and `karma-jasmine-html-reporter` to `1.1.0`

**Result:**
![no_error](https://user-images.githubusercontent.com/1953635/48297363-33ba8080-e474-11e8-8770-3f50815c3dc9.png)

### Desired functionality
`ng new` should create an angular project with in `package.json`:
the versions for `jasmine-core` and `karma-jasmine-html-reporter` to activate this feature in the tests reporter (not mandatory to stick to the upgrade versions i picked)

*one of my friend is investigating Jest behavior with this `No expectation test` feature if available.

### Mention any other details that might be useful
Next:
In the jasmine repo, an issue exists:
https://github.com/jasmine/jasmine/issues/1467

The jasmine member @slackersoft said:
> I'd be happy to review a pull request that adds another option like 'stop execution on spec failure' called something like 'fail specs with no expectations'. Oddly, I think the easiest way to implement that will be to add an expectation failure to the spec with the appropriate message just before the Spec object marks itself complete and successful.

When the flag available, i hope devs will enable it (and maybe the cli will have it by default enable) to be able to detect false-positive tests that are hurting a lot (i saw a lot stuf around this happening in legacy tests of new teams i joined that's why i dived on the topic).

**in the futur when the flag will be added to jasmine i'll open another issue to maybe enable by default in cli depending on cli team feedback.**

medium: https://medium.com/@nasreddine.skandrani/detect-false-positive-tests-in-your-angular-project-b6907d661841

**Comment by alan-agius4** [comment]
@hansl are you aware if internally within Google, Jasmine 3 is now supported?

**Comment by nasreddineskandrani** [comment]
i think the good call to do is:
- move to Jest (NX did, i did :) )
- if the cli continue to avoid jest => google team you need to rewrite karma or improve it (too slow) and have your own test framework (when ivy is done please :P)
