### ISSUE TITLE
Feature request: add ability to define angular.json in TypeScript as a .ts file

### ISSUE THREAD

**Issue by ilDon** [angular/angular-cli#12943]
### Bug Report or Feature Request
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Any

### Desired functionality

Currently all configuration goes into one single file `angular.json`.

As some projects grow in dimensions, such `json` file can get long (in terms of lines) and messy (in terms of number of configurations and alike). To make life easier angular-cli could support also a configuration file in TypeScript (e.g. `angular.ts`).

Such file could be exporting: `const config: AngularConfiguration = { ... }`.

This would make it possible to split the different parts of the configurations in multiple sub-files, that we could import in `angular.ts` configuration constant, and all other awesome things that TypeScript allows us to do.

### Mention any other details that might be useful

The `cli` could look first for `angular.json`, if it does not find it, it could look for `angular.ts`. Then, if `angular.ts` is present, it could parse the exported `config` `constant` (`JSON.parse(config)`) and work as usual.

Eventually, we could add to the TS config file the ability to define WebPack Plugins to be added to the build process, so that we do not need to run `ng eject`, keeping everything tide and clean. In this case, though, we would need a deeper review of the cli, as the `parse` route described above would not work for this purpose.

**Comment by jonathanlie** [comment]
would love this as well. That said, is there any way we could define the project definition in just `.js`? Currently in need to define several custom architect commands that share common options, this would help a lot.

**Comment by fetis** [comment]
I think it relates to this https://github.com/angular/angular-cli/issues/10612

**Comment by JounQin** [comment]
> would love this as well. That said, is there any way we could define the project definition in just `.js`? Currently in need to define several custom architect commands that share common options, this would help a lot.

+1 for this, is there any news? Or related PR? But is seems a lot of Angular related tools like `@storybook/angular` hard codes `angular.json` in its source files. It maybe a BREAKING CHANGE.

**Comment by clydin** [comment]
Having the configuration be represented as data (JSON) provides support for the update and migration stories of the Angular CLI.  It would drastically increase the complexity and in many cases prevent the current migration experience from occurring if the format was changed to be code instead of data.  Based on this, the Angular CLI does not have any plans to expand the supported formats at this time.
