### ISSUE TITLE
Install Node-sass isn't working anymore in a fresh new project

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#1294]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
**4.4.2**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**did a fresh ng new then did npm install node-sass --save-dev and i got an error and sass isn't added.**

4. The log given by the failure. Normally this include a stack trace and some
   more information.
**13422 verbose stack Error: The package @angular/common@2.0.0-rc.3 does not satisfy its siblings' peerDependencies requirements!
13422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:125:32
13422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\lib\install.js:268:7
13422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:142:5
13422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
13422 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
13422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
13422 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
13422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
13422 verbose stack     at cb (C:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
13422 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-installed\read-installed.js:263:14
13423 verbose cwd C:\Repos\test
13424 error Windows_NT 10.0.10586
13425 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-sass" "--save-dev"
13426 error node v4.4.5
13427 error npm  v2.15.5
13428 error code EPEERINVALID
13429 error peerinvalid The package @angular/common@2.0.0-rc.3 does not satisfy its siblings' peerDependencies requirements!
13429 error peerinvalid Peer @angular/forms@0.2.0 wants @angular/common@^2.0.0-rc.4
13429 error peerinvalid Peer @angular/platform-browser@2.0.0-rc.3 wants @angular/common@2.0.0-rc.3
13429 error peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.3 wants @angular/common@2.0.0-rc.3
13429 error peerinvalid Peer @angular/router@3.0.0-alpha.8 wants @angular/common@^2.0.0-rc.2
13430 verbose exit [ 1, true ]**

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by masaanli** [comment]
So then I installed Node 6.2.2 and the install was going good, but when i change a .css file to .scss it doenst generate an .css file at the same location.

I've runned ng serve.

**Comment by gregbown** [comment]
If I may add my findings. With the default npm install -g angular-cli (version 1.0.0.0-beta.6) adding scss compilation works as described in README.md.  After removing angular-cli as described in upgrade and then installing the latest npm install -g angular-cli@latest (version 1.0.0-beta.9) and creating a new project followed by npm install node-sass scss compilation does not work. Oddly, after doing a build with the --watch flag, the console seems to indicate it is working?? 
                file changed app\app.component.scss
                Build successful - 3859ms.
however there is no output.

Windows 10
Node 5.4
npm 3.8
angular2 2.0.0-rc.4
mterial2 2.0.0-alpha.6

**Comment by relevantmedia** [comment]
I am having issues where nested scss is not compiling
```
.sidebar {
	height: calc(100vh - 180px);
	margin-top: 30px;
	padding-right: 10px;
	font-size: 20px;
	border-right: solid 1px #ccc;
	#smList {
		position: absolute;
		bottom:150px;
	}
}
```
This does not work. I have to break smList out of sidebar to get it to work.

**Comment by jkuri** [comment]
Guys, this does work for me. Try updating `node-sass` (that's what I've done). Also, @relevantmedia, your example works in my case.

**Comment by tchoulihan** [comment]
I can verify this bug too, `ng build` no longer writes out `.scss` files into the `dist/app` directory.
