### ISSUE TITLE
Issue with having multiple `--base-href` option. (Data path “.baseHref” should be string.)

### ISSUE THREAD

**Issue by mcshiva** [angular/angular-cli#12948]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node -> v8.11.3
npm -> v5.5.1
ng -> v6.2.7

### Repro steps

I have recently upgraded to Angular 6 from Angular 5. I am having Angular-cli@6.2.7
In my `package.json`, I have configured script  **"build": "ng build --prod --base-href=/my-ui/"**
now when I run **yarn build --base-href=/my-ui-2/.** resulting following error

### The log given by the failure

```
$ng build --prod --base-href=/my-ui/ --base-href=/my-ui-2/
Schema validation failed with the following errors:
  Data path ".baseHref" should be string.
error Command failed with exit code 1.
```

### Desired functionality

It used to work in earlier versions of angular-cli considering the last option i.e my-ui-2.

**Comment by alan-agius4** [comment]
Hi, I have looked at this and it seems that is no longer reproducible in version 7 of the CLI.

**Comment by clydin** [comment]
I think there is still an open concern here regarding the behavior in the case an option is specified two or more times.  Should it error? Warn? Which of the options should be used? etc.

**Comment by mcshiva** [comment]
In the case an option is specified two or more times. In earlier versions it used to pick the last option. which is the expected as well.

**Comment by dominikg** [comment]
I reported a similar issue here: https://github.com/angular/angular-cli/issues/11448
and agree with @mcshiva that the behavior (last value is used when an option is passed multiple times) is expected.
