### ISSUE TITLE
prefixInterfaces question

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#1295]
there are some options inside the cli-options file, but what is the recommended way of interfaces? I was thinking all Interfaces shall start with 'I'.

Why is this setting disabled by default? Will Enabled not be better just as the guidelines?

"defaults": {
    "prefix": "app",
    "sourceDir": "src",
    "styleExt": "scss",
    "prefixInterfaces": false,
    "lazyRoutePrefix": "+"

**Comment by filipesilva** [comment]
We opted to not use the `I` prefix as it is the current style guide recommendation: https://angular.io/docs/ts/latest/guide/style-guide.html#!#03-03
