### ISSUE TITLE
Allow to override schematics files for default library individually 

### ISSUE THREAD

**Issue by michaeljota** [angular/angular-cli#12952]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```shell
node: v8.12.0
npm: 6.4.1
ng:

Angular CLI: 6.2.3
Node: 8.12.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.3
@angular-devkit/core         0.8.3
@angular-devkit/schematics   0.8.3
@schematics/angular          0.8.3
@schematics/update           0.8.3
rxjs                         6.2.2
typescript                   2.9.2
```

### Desired functionality

I would like to override a single schematic in the default angular schematics. In my case, I would like to replace the `spec` files with a custom Jest optimized file instead of the Jasmine file. One thing I notice I could do with Jest, is to resolve promises using `async/await`, but the current schematics uses `async` function instead. 

I don't want to create a package just to change one schematics, but just to configure the Angular CLI to read a custom schematic when it would create a file that I want to override.

**Comment by CWSpear** [comment]
I have almost the same exact use-case as you. I have some default stuff I want to change in the default templates, and I'd like to support everything the default templates do options/schema-wise, but just be able to tweak the output, but it doesn't seem as though this is possible. :(

**Comment by FrancescoBorzi** [comment]
The same use case here. Ideally, I'd like to change the way `*.component.spec.ts` files are generated.

**Comment by shastaxc** [comment]
Same issues here. I want my spec files to use Jest and Spectator, which is possible with spectator's schematics. However, in order to use the custom schematics, it requires a different command than the default. In this case, I have to generate my components with `ng g cs <comp-name>` instead of `ng g c <comp-name>`. It can be challenging to re-educate all the devs working on the project to use the different generator. It also means we only have whatever options are given by Spectator's schematic, which doesn't necessarily include all the options in the default component schematic. For example, Spectator's component schematic doesn't have a `--spec-only` flag, which I would find very useful.

**Comment by badgerduke** [comment]
We have a requirement to place spec files in a test folder outside of src/app.  It would be nice for developers to use the same generate commands e.g.` ng g c <name>` but have it use an overridden version of the default schematic.

**Comment by MaciejWWojcik** [comment]
any news, or possible workarounds for that? 👀 

I also have the same situation - would love to just override spec file generation and still be able to use `ng g c` command

**Comment by alan-agius4** [comment]
Hi, 

Changing a file in the default schematic can be done by extending the schematic.

Below is a simple example to filter out `.spec.ts` files and write other files which are located in `./files` example. 

```ts
export default function (options: ComponentOptions): Rule {
 const parsedPath = parseName(options.path, options.name);

  return chain([
    externalSchematic('@schematics/angular', 'component', options),
    filter(f => !f.endsWith('spec.ts')),
    mergeWith(apply(url('./files'), [ // Custom spec files are located here.
      template({...options}),
      move(parsedPath.path)
    ])),
  ]);
}
```


You can still use the same commands to run your custom schematic, etc.. IE: point `ng generate component` to your schematic. This can be done changing setting the defaultCollection to your schematic ex: `ng config cli.defaultCollection @myorg/schematic`.

For a real-world example see the `@ngrx/schematics`.

Docs: https://ngrx.io/guide/schematics
Sourcecode: https://github.com/ngrx/platform/blob/master/modules/schematics/collection.json
