### ISSUE TITLE
How to go about loading dynamic plugins

### ISSUE THREAD

**Issue by stupidJunior** [angular/angular-cli#12963]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```
### Versions
Versions / Env:
angular-cli: 6.0.8
node: 8.11.3
os: Window x64

## Desired functionality
**Requested functionality:** A way to create a component at a run time with ability to resolve dependencies
**Use case:** loading dynamic plugin that contains javascript code and html code in run time and displaying it on the page.

## Description

**The workaround to the following problem is not clear:**

It is possible in AngularJS to load JavaScript and HTML code (let's call it **_dynamic plugin_**) in a form of directive and display it in the page. The question is how one can go about loading of the dynamic plugins in Angular 2.

### AngularJs

So the process that I created in AngularJS can be described as follows:

 - We want to inject a custom dynamic content into a page, let's call it a plugin
 - That content **is not defined** in the web-client, instead it is being retrieved from a server in a structured form

That is we receive from the server **html** and **js** files that are necessary for the plugin to function and we load and display on the page. On the client I create an AngularJs directive to hold the necessary logic if the plugin.

Here is the code example for javascript  plugin code:

    () => {
        return {
            templateUrl: 'directive-template-name',
            restrict: "E",
            controller: ['$scope', ... /* other dependecies */, function ($scope, ...) {
                /* directive code */
            }]
        };
    }

Here is the code example for plugin loader code:

    // evaluate js function and compile directive
    var diretiveFactory = eval(content.jsFile);
    
    // AngularJS CompileProvider
    CompileProvider.directive.apply(null, [content.name, diretiveFactory]);
    
    // append html code to element using angular
    var wrapper = angular.element("#" + wrapperName);
    wrapper.html(requestedDirective[0].htmlContent);
    
    // initialize dynamic content
    var wrapperScope = wrapper.scope();
    this.$compile(wrapper)(wrapperScope);

As one can see, this method allows to load a valid javascript and *"compile"* it into a AngularJS directive and then display it on the page at will.

### Angular 2+

The problem with new angular is that concept of the **directive**, as far as I understand, is replace by a concept of **component**. Moreover, all client-side code is now written in typescript and transpiled into javascript for the client's browser. As far as I understand, all dependencies are being resolved in the traspilation process.

**That creates some problems** that prevent from creating dynamic plugins for Angular 2+:

 - A do not know how to inject dependencies into a dynamically created component as I do not know what exactly do I need when the transpilation happens.
 - Let's say I want several components to co-exist simultaneously (for example a parent dynamic components that holds children componets) and be able to communicate, in the case of AngularJs I could solve this problem by using scope variable. In case of Angular 2+ components are isolated so how to I go about this problem.
 - Moreover, I do not know how one can go about creating *ViewContainerRef* to hold the dynamically created component in evaluated javascript code. (See code examples below)

I will provide code examples of I got so far below. Content loader typescript code:

    //some imports
    import { Component, ComponentRef, Compiler, Injector, NgModule, NgModuleRef, ViewContainerRef} from '@angular/core';
    
    // plugin content structure
    class DynamicPageModel {
        name: string;
        htmlFile: string;
        jsFile: string;
    }
    
    export class DynamicContentService {
        
        constructor(
            private _compiler: Compiler,
            private _injector: Injector,
            private _m: NgModuleRef<any>
        ) { }
    
        public LoadDynamicContent(container: ViewContainerRef, content: DynamicPageModel) {
            // evaluate js function and compile component
            var tmpCmp = Component({
                template: content.htmlFile,
                selector: content.name
            })(eval(content.jsFile)());
            var tmpModule = NgModule({declarations: [tmpCmp as any]})(class { });
            var factories = this._compiler.compileModuleAndAllComponentsSync(tmpModule)
            var f = factories.componentFactories[0];
    
            var cmpRef =  f.create(this._injector, [], null, this._m);
    
            // insert component into the container
            container.insert(cmpRef.hostView);
        }
    }

For reference to what is going on in this piece of code, I got it from [here](https://blog.angularindepth.com/here-is-what-you-need-to-know-about-dynamic-components-in-angular-ac1e96167f9e).

Plugin example javascript code:

    () => {
        function dynamicMain() {
            this.componentName = 'Dynamic Example Main';
        }
        return dynamicExampleMain;
    }

As one can see, this is quite simple dynamic plugin that is unable to use any services or other components as it is unable to inject them into itself.

**Comment by alan-agius4** [comment]
Hi, I think this request is more suitable for https://github.com/angular/angular/issues

For dynamic component loading you can see here: https://angular.io/guide/dynamic-component-loader 

However, this doesn't cover creation of components at runtime, for instance getting HTML and CSS from a CMS for instance and you create an Angular Component from it.

That said, as far as I can tell for the Angular IO website something similar to this approach is being used and can be found https://github.com/angular/angular/blob/master/aio/src/app/layout/doc-viewer/doc-viewer.component.ts, that said the contents of this is strictly plain html.
