### ISSUE TITLE
ng update fails when using local library

### ISSUE THREAD

**Issue by elboukhari** [angular/angular-cli#12977]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version : v10.13.0
npm --version : 6.4.1
ng --version : 
`
Angular CLI: 7.0.6
Node: 10.13.0
OS: linux x64
Angular: 7.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.25.1
`
`uname -a : Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`
### Repro steps

just type : 
`ng update`

### The log given by the failure

`Not found : XXXXXX ()`

In my package.json this library is declared as : 

`"dependencies":
...
"XXXXXX": "file:lib/xxxxx.tgz",
...`

### Desired functionality

just ignore local libraries and update angular ones

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this but this should be fixed by #12526 and is available in the `v7.1.0-beta.1`

**Comment by elboukhari** [comment]
I'm still having  the issue even with : 
`"@angular/cli": "7.1.0"`

the error is the same as in the previous comment:
`404 Not Found - GET https://registry.npmjs.org/XXXXXXX - Not found`

**Comment by Kim-Andersen** [comment]
Tested in 8.0.3 and not working.
