### ISSUE TITLE
Can't specify output path when building a library project

### ISSUE THREAD

**Issue by avatsaev** [angular/angular-cli#12979]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node: 10
npm: 6
cli: 7.0.6
os: linux

### Repro steps
issue a command to build a library with `output-path` flag

`ng build  my-lib --output-path=dist`

### The log given by the failure
```
Unknown option: '--output-path'
```

### Desired functionality

 build command should accept custom output path for libs

**Comment by alan-agius4** [comment]
The output path for library needs to be specified in the `ng-package.json` One of the reasons why this is not an option is because when changing the output path you’d need to change the path mappings in tsconfig.

**Comment by tottomotto** [comment]
@avatsaev  The [build-ng-packagr](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_ng_packagr/src/build/schema.json) schema just doesn't support other properties than project, tsConfig and watch.

```
{
  "title": "ng-packagr Target",
  "description": "ng-packagr target options for Build Architect.",
  "type": "object",
  "properties": {
    "project": {
      "type": "string",
      "description": "The file path of the package.json for distribution via npm."
    },
    "tsConfig": {
      "type": "string",
      "description": "The file path of the TypeScript configuration file."
    },
    "watch": {
      "type": "boolean",
      "description": "Run build when files change.",
      "default": false
    }
  },
  "additionalProperties": false,
  "required": [
    "project"
  ]
}
```

**Comment by avatsaev** [comment]
I understand, thank you for the explanation

Closing

**Comment by alan-agius4** [comment]
Kindly subscribe to https://github.com/angular/angular/issues/26569

**Comment by nolafs** [comment]
Hi,

This is driving my nuts. Since I have updated my project to angular 8, the dist folder gets deleted before a production build. The library is symlink from this dist folder. My project fails to build because it keeps deleting the folder because it is missing the library. Possibly my setup is wrong, can anybody point me the right direction?

Cheers
Olaf
