### ISSUE TITLE
Styleext configuration not honored when generating component

### ISSUE THREAD

**Issue by WhitWaldo** [angular/angular-cli#12978]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node --version
`v8.11.1`
npm --version
`6.4.0`
ng --version
`Angular CLI: 7.0.5
Angular: 7.0.3`

### Repro steps
Run the following in a project directory:
`ng config schematics.@schematics/angular:component:styleext scss
ng g component test`

Observe the following get generated:
`CREATE src/app/test/test.component.html (23 bytes)`
`CREATE src/app/test/test.component.spec.ts (614 bytes)`
`CREATE src/app/test/test.component.ts (261 bytes)`
`CREATE src/app/app.module.**css** (388 bytes)`
`UPDATE src/app/app.module.ts (388 bytes)`

Notably, it creates the style file with a CSS extension despite the "scss" configuration

### The log given by the failure
No failure observed, just incorrect output.

### Desired functionality
Should be creating a style file with "test.scss", not with "test.css".

### Mention any other details that might be useful
Happy to provide anything else if you can think of it, but the above repro steps were sufficient from a new project to reproduce on my machine.

**Comment by alan-agius4** [comment]
Hi, the command you are using is not the correct one. 

You need to use;
```
ng config schematics.@schematics/angular.component.styleext scss
```
