### ISSUE TITLE
Configure ng build to transpile electron source code

### ISSUE THREAD

**Issue by hanct** [angular/angular-cli#12993]
@angular/cli version: 7.0.6

Hi,
I have created an electron application which uses angular framework (generated by @angular/cli)
However, to enjoy the typing system supported by typescript,  my electron AND angular scripts are all written using typescript. But question is how do I configure angular.json, such that when i trigger ng build, it not only transpile my angular source codes, but also transpile my electron source code at the same time ?

In the angular.json, I saw the architect.build.options.main set to main.ts (angular bootstrap file), but is it possible to also set it to point to my electron source code as well, so that ng build transpile both files.

I search internet for answer for few days but to no avail. Cos most articles writes electrons in javascript , not typescript.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
