### ISSUE TITLE
Can't make new project with : "ng new pro_name"

### ISSUE THREAD

**Issue by stavalfi** [angular/angular-cli#1299]
**1. OS?** 
Win7 64 bit

**2. Versions. Please run `ng --version`. If there's nothing outputted, please**
angular-cli: 1.0.0-beta.9
node: 6.3.0
os: win32 x64

**4. The log given by the failure. Normally this include a stack trace and some
   more information.**
C:\Users\armyTik\Desktop\angular2_projects\1\newFolder>ng new pro_name
(node:6604) fs: re-evaluating native module sources is not supported. If you are using
 the graceful-fs module, please update it to a more recent version.
**You cannot use the new command inside an angular-cli project.**

**Comment by jkuri** [comment]
You got a nice message why this is not working; "**You cannot use the new command inside an angular-cli project.**".

**Comment by stavalfi** [comment]
In angular-cli there is a command : "ng new project-name".

**Comment by akanieski** [comment]
Sorry @jkuri I'm having the same issue. Not sure what I'm doing wrong. 
```
C:\code\wk
λ ng new wkmobile
(node:17592) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
You cannot use the new command inside an angular-cli project.
```
