### ISSUE TITLE
generate component, folder name issue

### ISSUE THREAD

**Issue by qmarquez** [angular/angular-cli#13000]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node v10.3.0
npm 6.4.1
@angular-devkit/architect 0.8.7
@angular-devkit/build-angular 0.8.7
@angular-devkit/build-optimizer 0.8.7
@angular-devkit/build-webpack 0.8.7
@angular-devkit/core 0.8.7
@angular-devkit/schematics 0.8.7
@angular/pwa 0.8.7
@ngtools/webpack 6.2.7
@schematics/angular 0.8.7
@schematics/update 0.10.5 (cli-only)
rxjs 6.3.3
typescript 3.1.6
webpack 4.16.4

### Repro steps
with an existing +module-with-words folder that contains folders with components
ng g c \+moduleWithWords/aNewComponent
it create a new folder "+moduleWithWords" and update +module-with-words/*.module.ts

### The log given by the failure
NaN

### Desired functionality
it should create the component inside +module-with-words folder instead create a new one

### Mention any other details that might be useful
NaN

**Comment by alan-agius4** [comment]
I think you need to use `--flat` options.
See https://angular.io/cli/generate#component

If this doesn't help can you please share the folder structure you have before and after the `ng g component` command?

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
