### ISSUE TITLE
service worker received date

### ISSUE THREAD

**Issue by maxisam** [angular/angular-cli#13001]
### Bug Report or Feature Request (mark with an `x`)
```
- [V] bug report -> please search issues before submitting
- [ ] feature request
```
![image](https://user-images.githubusercontent.com/456807/48731313-60a02d80-ec02-11e8-9386-a0f01c5ad332.png)

The received date is always 12/31/1969

### Versions

cli: 7.0.6

### Repro steps

just a very simple pwa example like ng add @angular/pwa

### Desired functionality
Should show correct date

**Comment by alan-agius4** [comment]
Hi, this might be that your local time is incorrect.

Can you do the following in the browser console?
```
new Date()
```

**Comment by maxisam** [comment]
local time is correct.

**Comment by alan-agius4** [comment]
That’s odd, as I am unable to replicate when having the correct time in the browser.

**Comment by maxisam** [comment]
You are right. It works on a different machine. Even better, it works in the different chrome instance. That is so odd.

**Comment by alan-agius4** [comment]
Hi, I am closing as it looks like this is something which is not caused by the CLI.

**Comment by maxisam** [comment]
Thanks for your help!

**Comment by JWess** [comment]
I am seeing this same behavior. Were you ever able to figure out why it happens? My PC's clock is accurate.

**Comment by maxisam** [comment]
nope. it is still a myth to me.  It is still wrong on my machine.
