### ISSUE TITLE
ERROR 'Unexpected value' when change generated library module names.

### ISSUE THREAD

**Issue by jdavidls** [angular/angular-cli#13006]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```
Angular CLI: 7.0.6
Node: 8.12.0
OS: linux x64
Angular: 7.0.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.6
@angular-devkit/build-angular      0.10.6
@angular-devkit/build-ng-packagr   0.10.6
@angular-devkit/build-optimizer    0.10.6
@angular-devkit/build-webpack      0.10.6
@angular-devkit/core               7.0.6
@angular-devkit/schematics         7.0.6
@angular/cli                       7.0.6
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.6
@schematics/angular                7.0.6
@schematics/update                 0.10.6
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1
```

### Repro steps

```bash
ng new dummy
cd dummy
ng generate library mylib
cat projects/mylib/mylib.module.ts
```
```typescript
import { NgModule } from '@angular/core';
import { MylibComponent } from './mylib.component';

@NgModule({
  declarations: [MylibComponent],
  imports: [
    
  ],
  exports: [MylibComponent]
})
export class AnyOtherMylibModule { } // * Rename the library module *
```
```bash
cat src/app/app.module.ts
```
```typescript
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';

import { AnyOtherMylibModule } from 'mylib';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AnyOtherMylibModule, // MylibModule,
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
### The log given by the failure
```bash
ng build mylib   # OK
ng build --prod
> ERROR in : Unexpected value 'AnyOtherMylibModule in /.../dummy/mylib/mylib.d.ts'
> imported by the module 'AppModule in /.../dummy/src/app/app.module.ts'.
> Please add a @NgModule annotation.

```
### Desired functionality

```bash
> Hash: f9217edcbe394f6842c4
> Time: 1ms # it would be wonderful too
```
### Mention any other details that might be useful

This only happens with for `--prod` target compilation, I'm have the same results with 7.1.0-betas. Is a stranger error, BUT if you simply put a number at the end of the module name works well `MylibModule2`. as a result of this behavior, we can only export modules with the same name from a library :(

**Comment by alan-agius4** [comment]
Hi, this usually happens if you do the change after building the library without rebuilding.  I am unable to replicate this issue otherwise.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
