### ISSUE TITLE
Bundle generated through bundleDependencies=all is incompatible with uglifyjs after 7.0.0-beta.2

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#13013]
<pre><code>[x ] Bug report  </code></pre>

## Current behavior

Generating a bundle with option bundleDependencies set to all and then minifying it using uglifyjs is broken after 7.0.0-beta.2 and throw below error:

Parse error at main.js:157164,23
module.exports = class NodeList extends Array {
                       ^
ERROR: Unexpected token: name (NodeList)
    at JS_Parse_Error.get (eval at <anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\tools\node.js:20:1), <anonymous>:71:23)
    at fatal (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:291:53)
    at run (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:235:9)
    at Object.<anonymous> (C:\Users\UserName\AppData\Roaming\npm\node_modules\uglify-js\bin\uglifyjs:160:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

## Expected behavior
The generated bundle should be compatible with uglifyjs.

## Minimal reproduction of the problem with instructions

Generate a bundle with below options:

```
              "optimization": false,
              "bundleDependencies": "all",

```

Then use uglifyjs to minify the bundle.

`uglifyjs main.js --output main1.js`

And it will throw above error

## What is the motivation / use case for changing the behavior?

For .Net developers using Angular Universal/SSR, its necessary to have all dependencies bundled in one file before we could successful deploy it on server Windows Server.

generating a server bundle with optimization set to true and bundleDependencies set to all doesn't work
as a work around we generate bundle with optimizations set to false and then use uglifyjs to tree-shake and minify bundle.

## Environment

<pre><code>
Angular version: 7.0.0-beta.5

Browser:
- [x] All
 
For Tooling issues:
- Node version: v8.11.4
- Platform: Windows
</code></pre>

**Comment by clydin** [comment]
Domino is meant to run on a server which doesn’t have the limitations that certain browsers have of only supporting ES5.  Later versions of ES are nearly universally preferred as they provide improved performance and smaller code size.

**Comment by JSMike** [comment]
@naveedahmed1 FYI, I was running in to this as well, specifically around testing. The issue was that the `@nguniversal/module-map-ngfactory-loader` was being included (for me, specifically when testing because I had made a module test for it).  Make sure you're not accidentally including files or modules in the front-end that have the `@nguniversal/module-map-ngfactory-loader` import.
