### ISSUE TITLE
Update wiki for font-awesome 

### ISSUE THREAD

**Issue by codeaddslife** [angular/angular-cli#13018]
Story https://github.com/angular/angular-cli/wiki/stories-include-font-awesome describes how to include font-awesome icons. 

The npm dependency is out-of-date.

```
npm install --save font-awesome
```

This is the old (v4.7) version of font-awesome. 
As described on https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers, the current npm depencendy should be 

```
npm install --save-dev @fortawesome/fontawesome-free
```

**Comment by devoto13** [comment]
There is an official [library](https://github.com/FortAwesome/angular-fontawesome) for Angular, which is the recommended way to use FontAwesome icons in Angular apps. There is an extensive documentation available in the [README](https://github.com/FortAwesome/angular-fontawesome#usage).

**Comment by codeaddslife** [comment]
Great! If this is the recommended way, it may be a good idea to change wiki page
https://github.com/angular/angular-cli/wiki/stories-include-font-awesome?

**Comment by devoto13** [comment]
If it is fine with the CLI team, then go ahead! We even have an issue requesting to add this documentation: https://github.com/FortAwesome/angular-fontawesome/issues/7.

**Comment by kartik-budhiraja** [comment]
@codeaddslife , @devoto13 , @alan-agius4  I would love to work on this issue if it is available.

**Comment by mgechev** [comment]
@kartik-budhiraja sure, feel free to take it.
