### ISSUE TITLE
UI not rendering as intended

### ISSUE THREAD

**Issue by Meyer-dev** [angular/angular-cli#13016]
![screenshot 32](https://user-images.githubusercontent.com/31076768/48809548-b02f4800-ed2d-11e8-8842-5d880444bbfd.png)

### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

**HTML**
<div class="card" >
  <div class="card-content">
    <span class="card-title " style="text-align: center">Add Product</span>
    <form (ngSubmit)="onSubmit()">
      
      <div class="row">
        <div class="input-field col s6">
          <input type="number" placeholder="add product reference" [(ngModel)]="product.product_ref" name="product reference">
          <label>Product Reference</label>
        </div>
        <div class="input-field col s6">
          <input type="string" placeholder="add product name" [(ngModel)]="product.name" name="product name">
          <label>Product Name</label>
        </div>
      </div>

      <div class="row">  
        <div class="input-field col s6">
          <input type="string" placeholder="add product description" [(ngModel)]="product.description" name="product description">
          <label>Product Description</label>
        </div>
        <div class="input-field col s6">
          <input type="number" placeholder="add product price" [(ngModel)]="product.price" name="product price">
          <label>Product Price</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s6">
          <select [(ngModel)]="product.perishable" name="product perishability">
            <option value="True">True</option>
            <option value="False">False</option>
          </select>
          <label>Perishable ?</label>
        </div>
        <div class="input-field col s6">
          <select [(ngModel)]="product.category"name="product category">
            <option value="Fruit & Veg">Fruit & Veg</option>
            <option value="Dairy">Dairy</option>
            <option value="Cupboard">Cupboard</option>
            <option value="Bakery" selected>Bakery</option>
          </select>
          <label>Product Category</label>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s6">
          <select [(ngModel)]="shopapplicable"name="product category">
            <option value="PnP Rondebosch">PnP Rondebosch</option>
            <option value="Pnp Claremont">Pnp Claremont</option>
            <option value="PnP Wynberg">PnP Wynberg</option>
            <option value="Pnp Observatory">Pnp Observatory</option>
          </select>
          <label>Applicable Shops** (requires quick multiselectoptions)</label>
        </div>
        <div class="input-field col s6">
        <input type=submit value="Submit" class="btn">
        </div> 
      </div>
    </form>

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
