### ISSUE TITLE
short, ambiguous error log when build failure 

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#13014]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

i updated angular-cli to 6.2.6 then failed executing `ng build --prod `
only one line error was logged:
`ERROR in Cannot read property 'type' of null`
without any other information.

i opened an [issue](https://github.com/angular/angular-cli/issues/12728) in Angular-cli then they told me it might be an issue with library that defines its Angular dependencies incorrectly.

until now i could not locate where the problem is through the single-line error message

## Expected behavior

any solution to locate where the error came from, if there isn't, better add some

**Comment by alan-agius4** [comment]
@hakimio, in need it is a duplicate of https://github.com/angular/angular/issues/24143

Thanks.
