### ISSUE TITLE
Install and Configure Karma in existing Project

### ISSUE THREAD

**Issue by hanct** [angular/angular-cli#13019]
Hi,
@angular/cli: v7.0.6

I previously create new angular project using @angular/cli with this command
          ng new --inline-style --minimal --skip-git --skip-tests

Hence test related packages are skipped. After my source code development completes, I wanted to install back the test packages (e.g karma, jasmine, karma-coverage-istanbul-reporter, etc) and the preconfigured  test configuration file(such as karma config file).  Possible to do this with angular cli command line? If not possible, would like to suggest to provide a new ng command option to  install and preconfigure the test packages to an existing angular project .

**Comment by alan-agius4** [comment]
Hi, at the moment we don’t offer this functionality.

**Comment by clydin** [comment]
This is not a capability we are considering as a complete implementation with proper configuration would be non-trivial.

The minimal option is intended for use cases such as class exercises, quick experiments, demos, etc.

Creating a new project and reviewing the test related additions and then adding them to the existing project as well as an option setup within angular.json specific to the project would probably be the most efficient method currently.

**Comment by hanct** [comment]
ok. noted.
