### ISSUE TITLE
project wrongly in required flags in some schematics

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#13010]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
```

### Command (mark with an `x`)
```
- [x] generate
```

### Versions
CLI v7.0.6

### The log given by the failure
#12196 wrongly added `project` as a required flag in `class`, `guard` and `service-worker` schematics JSON schemas.

It creates wrong behavior in tools using schematics, which check the required flags to ask the user, like cyrilletuzi/vscode-angular-schematics#20.

### Desired functionality
`project` should be removed from `required` in schematics JSON schemas, as it's only an option (the CLI defaults to the main project).

**Comment by alan-agius4** [comment]
Hi, the `project` is always required when running a schematic as without it the schematic will not execute successfully.

At the moment, when no project is provided and you use the schematics via the `ng generate` command. The default project is picked up and passed from Angular CLI to the schematics https://github.com/angular/angular-cli/blob/a3e3bb2524d51ca77c1f937ed6b1abca2ae6a4d7/packages/angular/cli/utilities/config.ts#L303

If you try to run the schematics directly without `ng generate` command such as when using the `schematics cli` you need to always provide the project name.

```
schematics @schematics/angular:component foo --project my-app
```

Looping in @hansl as he is more aware of this.

**Comment by alan-agius4** [comment]
@cyrilletuzi, AFAIK this is the indented behaviour as in some cases when no Project is provided we throw an error, such as https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/component/index.ts#L131

That said, I am not sure why `project` is not required in all schemas.

**Comment by cyrilletuzi** [comment]
@alan-agius4 Thanks for the answer.

As a feedback for other tools maintainers, I discovered a similar problem with other options like `target` and `configuration` in service worker schematics, which are now marked as `required` too, despite the fact they have a default value in their schemas.

So I'll filtered required options if they have `default` or `$default` in their schemas.

Thanks again for your quick answer.

**Comment by cyrilletuzi** [comment]
In fact I think the issue is wider than expected and not resolved.

For example, `ng g service-worker` is not working anymore, as `--target` and `--configuration` are now flagged as required, despite the fact they have a `default` in their schemas.

@alan-agius4 Is it the expected behavior?

**Comment by alan-agius4** [comment]
@cyrilletuzi, that seems a bug. 

@hansl should properties that have a `default` be present in the `required`?

**Comment by cyrilletuzi** [comment]
Hi, any news about this issue? Thanks.

**Comment by alan-agius4** [comment]
There’s an open PR for address this.

**Comment by cyrilletuzi** [comment]
@alan-agius4 I don't know why, but this issue stays in my Github opened issues list. Surely a Github bug, but could you please reopen and close this issue to try to clean this?

**Comment by cyrilletuzi** [comment]
Seems my comment triggered something, all is OK now, thanks.
