### ISSUE TITLE
Feature request - gh-pages -- private github repo

### ISSUE THREAD

**Issue by daftster** [angular/angular-cli#1301]
> ## Please provide us with the following information:
> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>    CentOS
1. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
       node --version
   And paste the result here.
   angular-cli: 1.0.0-beta.6
   node: 6.2.2
   os: linux x64
2. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   ng github-pages:deploy --user-page --message "testing github-pages"
3. The log given by the failure. Normally this include a stack trace and some
   more information.
4. Mention any other details that might be useful.
   
   > ---
   > 
   > > Thanks! We'll be in touch soon.

It would be nice to be able to pass a private github repo in the paramter.

**Comment by JohannesHoppe** [comment]
You are welcome:
https://www.npmjs.com/package/angular-cli-ghpages

:smile:

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
