### ISSUE TITLE
My Factory Annotation does not work after prod build any more

### ISSUE THREAD

**Issue by QuerdenkerAndFriends** [angular/angular-cli#13011]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.6
Node: 8.9.4
OS: win32 x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.6 (cli-only)
@angular-devkit/build-angular      0.10.6
@angular-devkit/build-ng-packagr   0.10.6
@angular-devkit/core               7.0.6
@angular-devkit/schematics         7.0.6
@angular/cli                       7.0.6
@ngtools/json-schema               1.1.0
@schematics/angular                7.0.6
@schematics/update                 0.10.6 (cli-only)
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.25.1

### Repro steps

Download stackblitz project and run ng s --prod or ng build --prod
https://stackblitz.com/edit/angular-x3mabk?file=src%2Fapp%2Ffactory-annotation.ts

### The log given by the failure

window.Reflect.getOwnMetadata('design:paramtypes', factoryMeta.instantiable);

returns undefined instead of the constructor deps of factoryMeta.instantiable (standard build).
That's why my code throws an exception. 

Please set breakpoint in the stackblitz code sample and you will see. I commented the point. 
factory.annotation line 12.

### Desired functionality

background story
My problem was that I wanted to have an intatiable class that may have deps to angular service. The common way to approach this is creating a FactoryService with a create-method. The factory then has to have the same constructor deps as the instantiable class and forward these deps to the constructor of the instance in the create method. Another annoying point going along with this bloat code were the merge conflicts. You always had to keep in mind the order of the deps in the instantiable class and use the same order in the constructor of the factory and the create method where you call the constructor of the instantiable class. 

To solve this problem,
I created an annotation, using the existing DI to register an abstract FactoryService (with generated provider) for an Instantiable class which may have deps to angular services, but it does not work after prod build.

I would like to know
- how to create an instantiable class with deps to angular services
- how to get the deps from instantiable to generate my factory
- why it does not work
- if its a bug or by design :)

### Mention any other details that might be useful

https://stackblitz.com/edit/angular-x3mabk?file=src%2Fapp%2Ffactory-annotation.ts

**Comment by hansl** [comment]
We remove Reflect Metadata from the bundle on prod by default. To add it back you need to provide it through your `polyfills.ts`. This is because Angular itself does not need reflect metadata for AOT, so we remove it to save space (it's >50kb large). If you need it specifically for your app, you should manually add it to polyfills so it doesn't get stripped out.

**Comment by QuerdenkerAndFriends** [comment]
> We remove Reflect Metadata from the bundle on prod by default. To add it back you need to provide it through your `polyfills.ts`. This is because Angular itself does not need reflect metadata for AOT, so we remove it to save space (it's >50kb large). If you need it specifically for your app, you should manually add it to polyfills so it doesn't get stripped out.

Hi hansl,
Thank you for your fast reply. I updated the stackblitz code and its still not working. I am sorry but could you please tell me if you tested your suggestion and maybe have a look at my updated sample? 

I might be wrong but Reflect.getMetadata was a function when I debugged the code (non updated), so I did not have the idea of a missing polyfill. The problem is that the function returns undefined after prod build.

**Comment by alan-agius4** [comment]
Hi, this is one of the features of build optimizer. Decorators metadata are being stripped since in general shouldn't and are not by default needed an AOT compilation.

If you want to retain this, you need to disable `buildOptimizer` from your `angular.json`. However this will result in a larger bundle.

To create factories, you shouldn't be depending on reflection but rather DI. See https://angular.io/guide/dependency-injection-providers#factory-providers
