### ISSUE TITLE
ERROR INSTALLING ANGULAR-CLI

### ISSUE THREAD

**Issue by deygordillos** [angular/angular-cli#13023]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### ERROR TO INSTALL ANGULAR CLI

npm install -g @angular/cli

loadShrinkwrap → install  ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @angular/cli@7.0.6: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine @angular/cli@7.0.6: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (culoadDep:symbol-observable ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine inquirer@6.2.0: wanted: {"node":">=6.0.0"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine @angular-devkit/architect@0.10.6: wanted: {"node":">= 8.9.0","npm":"loadDep:symbol-observable ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @schematics/update@0.10.6: wanted: {"node":">= 8.9.0","npm":">= 5.5.loadDep:symbol-observable ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @schematics/angular@7.0.6: wanted: {"node":">= 8.9.0","npm":">= 5.5.loadDep:symbol-observable ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @angular-devkit/schematics@7.0.6: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"4.2.6","npm":"3.5.2"})
WARN engine @angular-devkit/core@7.0.6: wanted: {"node":">= 8.9.0","npm":">= 5.5loadDep:source-map → 304  ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine source-map@0.7.3: wanted: {"node":">= 8"} (current: {"node":"4.2.6",loadDep:punycode → 304    ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"4.2.6","nploadDep:urix → 304        ▀ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine atob@2.1.2: wanted: {"node":">= 4.5.0"} (current: {"node":"4.2.6","nloadDep:uuid → resolveWit ▐ ╢██████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine har-validator@5.1.3: wanted: {"node":">=6"} (current: {"node":"4.2.6npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular/cli
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/@angular
/usr/local/lib
└── @angular/cli@7.0.6 

npm WARN optional Skipping failed optional dependency /@angular/cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib/node_modules/@angular/cli
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/@angular/cli'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/@angular/cli']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/@angular/cli' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/usuario/npm-debug.log

**Comment by clydin** [comment]
From the log:
`WARN engine @angular/cli@7.0.6: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"4.2.6","npm":"3.5.2"})`

The system appears to have NodeJS version 4.2.6 but the CLI requires a minimum of 8.9.0.  Please install a more recent version of NodeJS.
