### ISSUE TITLE
[ivy]: experimentalIvy flag generates an app with no change detection

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#13024]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 7.1.0-rc.0
Node: 8.11.3
OS: darwin x64
Angular: 7.1.0-rc.0

### Repro steps

Generate a new app with `experimentalIvy`

```
ng new ivy-cd --experimental-ivy --defaults
cd ivy-cd
$(npm bin)/ivy-ngcc
ng serve --aot
```

add a simple `setTimeout` in `app.component.ts` like:

```typescript
constructor() {
  setTimeout(() => {
    console.log('set timeout');
    this.title = 'hello';
  }, 2000);
}
```

will result in a trace in the browser console, but no update in the DOM. It looks like change detection is not run. After discussing with @jasonaden on Slack, he confirms that if the app is bootstrapped using `renderComponent` (as it is currently when using the `experimentalIvy` flag) then CD is not running. But he pointed out that using `platformBrowser` fixes it, and indeed it does.

### Desired functionality

The `experimentalIvy` flag could be simplified to probably just add the Angular compiler option in `tsconfig.app.json` but the rest could be removed and use the default bootstrap mechanism.

### Mention any other details that might be useful

I can submit a PR if the CLI team agrees.

@jasonaden asked me to also cc @alxhub for his input.

**Comment by dirkluijk** [comment]
@cexbrayat Same issue here. How should I use platformBrowser (the workaround you mentioned) exactly?

**Comment by klimentru1986** [comment]
@cexbrayat try to use [markDirty](https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/core/src/render3/instructions.ts#L2557) function. [Example here](https://github.com/klimentru1986/angular-ivy/blob/master/src/app/app.component.ts).

Or you can do it in bowser console
```
// Get component
let comp = ng.getComponent(document.querySelector('app-root'));
// MarkDirty
ng.markDirty(comp);

**Comment by IgorMinar** [comment]
Given that we want to roll out ivy as backwards compatible solution, I think this proposal makes sense.

So the way this would work is that you `ng new` a new app in a normal way. Turn on enableIvy in tsconfig, run `ngcc`, and then the toolchain uses `ngtsc` to build the app with ivy.

eventually we need to figure out how to integrate `ngcc` into this workflow more tightly so that it's not a step developer needs to do explicitly, but that will be a bigger change and should be handled separately.
