### ISSUE TITLE
npm install on newly created project fails

### ISSUE THREAD

**Issue by arupadhy** [angular/angular-cli#1302]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

  windows 7 enterprise

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
                 angular-cli: 1.0.0-beta.9
                 node: 4.4.7
                 os: win32 x64

        node --version
                  v4.4.7
     
   And paste the result here.

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

yes. No change done...trying to create a new project.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.3 does not satisfy its
 siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@0.2.0 wants @angular/common@^2.0.0-rc.4

npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.3 wants @angular/co
mmon@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.3 wants @an
gular/common@2.0.0-rc.3
npm ERR! peerinvalid Peer @angular/router@3.0.0-alpha.8 wants @angular/common@^2
.0.0-rc.2

npm ERR! Please include the following file with any support request:
npm ERR!     C:\playgroundApp\npm-debug.log

5. Mention any other details that might be useful.

old project that i created 2 months back works fine.Since then i have updated/reinstalled latest version of node and angular-cli.

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by arupadhy** [comment]
manually fixing package.json resolves the issue.

**Comment by hartz89** [comment]
I'm experiencing this as well.  @arupadhy: What exactly did you change in package.json to fix this?

**Comment by jkuri** [comment]
@arupadhy can you post the answer what did you done to make this working so I can close the issue?

**Comment by arupadhy** [comment]
i updated all occurences of 2.0.0-rc.3 to 2.0.0-rc.4 ( new version) in package.json and ran npm install again.

**Comment by jkuri** [comment]
@arupadhy thanks. I can see this is now updated in the [package.json](https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/ng2/files/package.json). Closing.

**Comment by hartz89** [comment]
Shouldn't this remain open since it's an existing issue with the CLI-generated `package.json`?

**Comment by jkuri** [comment]
It is updated in [package.json](https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/ng2/files/package.json).
