### ISSUE TITLE
livereload configuration

### ISSUE THREAD

**Issue by aggro80** [angular/angular-cli#1303]
With lite-server I could configure the server to serve specific path and use https with the following 'bs-config.js' configuration file that simulated the real server quite nicely: 

```
var modRewrite  = require('connect-modrewrite');

module.exports = {
  "port": 3000,
  "server": { "baseDir": "./" },
  "https": true,
  "startPath": '/base/web/static/',
  "middleware": [
               modRewrite([
                   '^/base/web/static/foo(.*)$ https://localhost:3000/index.html [P]',
                   '^/base/web/static/(.*)$ https://localhost:3000/$1 [P]'
               ])
          ]
};
```

It seems that livereload that is used by the angular-cli can only change the port, and even that has to be done from the command line when server is started. 

Is there a reason why angular-cli can't use lite-server by default and thus make it possible for more advanced configurations? If that is not possible, is it possible to add documentation about how use lite-server instead of livereload?

**Comment by jkuri** [comment]
`angular-cli` uses built-in `ember-cli` version of web server (`express-server`) to host the files; see [`this`](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/serve.js#L6). However I believe this question is not directly related to `angular-cli`. Closing.
