### ISSUE TITLE
Not able to skip README.md on new angular project setup using angular cli

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular-cli#13035]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Windows 10
node: v10.12.0
npm: 6.4.1
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.2
Node: 10.12.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.2
@angular-devkit/core         7.0.2
@angular-devkit/schematics   7.0.2
@schematics/angular          7.0.2
@schematics/update           0.10.2
rxjs                         6.3.3
typescript                   3.1.3

### Repro steps

ng new project-name --directory "./"
![image](https://user-images.githubusercontent.com/4208015/48912342-5187dc80-ee9b-11e8-8ad1-3c4257967e02.png)

### The log given by the failure

```
PS D:\Projects\angular-template-form> ng new template-driven --directory "./"
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
ERROR! README.md already exists.
The Schematic workflow failed. See above.
```

```
PS D:\Projects\angular-template-form> ng new template-driven --directory .
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
ERROR! README.md already exists.
The Schematic workflow failed. See above.
PS D:\Projects\angular-template-form>
```

### Desired functionality

**I already have my README.md , so i just want to skip while creating new angular project using cli**
Not able to skip README.md on new setup of angular project

Should have a flag 
ng new project-name --directory . --skipREADME true

### Mention any other details that might be useful

No

**Comment by alan-agius4** [comment]
Hi,

This is not a capability we are considering currently as this is quite an edge case, and I trivial to remove and paste the readme file.

Thanks.
