### ISSUE TITLE
Environment config for assembled application artifact

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular-cli#13037]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
any

### Repro steps
E.g. We have assembled application artifact (which was made on the separate Jenkins-server). Next we want to deploy it on prod, staging, etc. servers. Any of these servers has own configuration which is have to be included to the artifact (we can't use angular environment files in this case because the artifact is already assembled)

We can solve the issue for now by several ways
1. To have some module with environment config which content we will replace in the bundle by regexp
2. To have separate bundle just for environment config and replace it to the correct one
3. To store the config in e.g. assets/environment.json, replace it to the correct one and use it inside the application by ajax

### Desired functionality
There is not good idea for me to change something in the assembled files. I would like to have special EnvironmentConfig module in the default application (created by ng new) which exports content of assets/environment.json file as a constant (in sync way of course).

Or we can also use index.html for this because it is not in the bundle. E.g. declare js-module/const inside the script tag and replace our config by this way.

Or something else.

Anyway we have to have some part of code which we can simple replace in the assembled application

**Comment by alan-agius4** [comment]
Hi @tamtakoe, from your explanation you seem to what you need is runtime configuration which is outside of the scope of the CLI.

This is something that can already be done, using `json` files and services. There are a couple of good examples in this post:
https://github.com/angular/angular-cli/issues/3855
