### ISSUE TITLE
ng-packagr@4.4.0 requires a peer of [missing peer version] but none is installed. You must install peer dependencies yourself - error

### ISSUE THREAD

**Issue by zoezydk** [angular/angular-cli#13036]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting (searched here --> https://github.com/angular/angular-cli/issues/8767 but still doubts...)
```

### Command (mark with an `x`)
```
- [ x ] npm install ng-packagr
```

### Versions
```
<!--
Output from:
`node --version` --> v8.12.0
`npm --version` --> 6.4.1
`ng --version`  -->
Angular CLI: 7.0.3
Node: 8.12.0
OS: win32 x64
Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.3 (cli-only)
@angular-devkit/core         7.0.3 (cli-only)
@angular-devkit/schematics   7.0.3 (cli-only)
@ngtools/json-schema         1.1.0
@schematics/angular          7.0.3 (cli-only)
@schematics/update           0.10.3 (cli-only)
ng-packagr                   4.4.0
rxjs                         6.3.3
typescript                   2.5.2
webpack                      4.26.0
  Windows (10)
```

### Repro steps
```
In terminal running npm i ng-packagr command results in issue.
```

### Desired functionality
```
What would like to see implemented? No warning in CLI when installing package
```

Ran following command in terminal `npm i ng-packagr ` and ended up with this...

![cli_ngpackgr_install_requires_peer_dependency_error](https://user-images.githubusercontent.com/12489567/48916355-3e1c4780-ee82-11e8-9126-8a3d819d864b.PNG)

...so found this thread about similar issues --> [https://github.com/angular/angular-cli/issues/8767](https://github.com/angular/angular-cli/issues/8767) which seem to indicate a problem with the CLI itself.

What am I supposed to do in regards to the first four warnings on the list (ignoring the rest of the remaining)?

The project is a typeorm project accessing a MSSQL database and was created using this manual --> [https://github.com/typeorm/typeorm#quick-start](https://github.com/typeorm/typeorm#quick-start) if that should matter.

Looking forward to any input.

Thanks.

**Comment by alan-agius4** [comment]
Hi, you are trying to install `ng-packagr` directly which requires some `peerDependencies` to work. `peerDependencies` always need to be installed manually unless already specified in your `package.json`

To use ng-packagr within the CLI. You should create a library using the library schematics.

See: https://angular.io/cli/generate#library & https://github.com/angular/angular-cli/wiki/stories-create-library

**Comment by zoezydk** [comment]
@alan-agius4 Hi again and thanks for your input. I tried to download and manually install the latest typescript from here --> [https://github.com/Microsoft/TypeScript](https://github.com/Microsoft/TypeScript) but am getting errors identical to the output in this thread -->[https://github.com/gatsbyjs/gatsby/issues/6834](https://github.com/gatsbyjs/gatsby/issues/6834).

I was able to audit npm packages before that error above occurred by using the `fix` appendix and could remove the first three out of the four initial warnings. However, I am unable to use that command to audit fix the new warnings which basically look like this...

![ng-packagr_cli_warning2](https://user-images.githubusercontent.com/12489567/49015195-a91b9600-f182-11e8-8782-4798f098b59a.PNG)

...indicating an issue with the typescript library. However the current project was not made with Angular but instead was created as a typescript project. I added Angular capability in node_modules, so this is all working. But the typescript library still remains a problem. As can be seen from the screenshot, the best common suitable package to fix this problem would be typescript 3.2 but..., when I try to find that version, all I get is typescript 3.1 as the latest stable version, whereas typescript 3.2 is listed only as "release candidate" --> [https://libraries.io/npm/typescript](https://libraries.io/npm/typescript) and that just that spells trouble.

So considering the warnings, I am at a loss as to what should be installed instead.

Any input to the above would be greatly appreciated.

**Comment by zoezydk** [comment]
@alan-agius4 Unless of course..., this is the package needed right here --> [https://libraries.io/npm/typescript/3.2.0-dev.20181117](https://libraries.io/npm/typescript/3.2.0-dev.20181117)

Can you confirm that?

**Comment by zoezydk** [comment]
@alan-agius4 I'm kind of stuck with the above problem and am in doubt on how to proceed. Did you have any input on the above which could point me into the right direction?

Thanks in advance.

**Comment by zoezydk** [comment]
Also just to mention. My present typescript version is 6.4.1 so I am wondering if I would have to downgrade to fix these issues? As in downgrade to typescript 3.2 as mentioned earlier? I read some additional post here --> [https://stackoverflow.com/questions/23267858/how-do-i-install-typescript](https://stackoverflow.com/questions/23267858/how-do-i-install-typescript) which has a mention of the (possible) need of uninstalling typescript from Control Panel since a version of it resides in there as well. This version is set to override any installed npm version of typescript. As such I am wondering if the current 6.4.1 version being listed in terminal is pointing towards the Control Panel version and not the actual npm version.

Could this be causing the warnings?

**Comment by zoezydk** [comment]
@alan-agius4 I just ran the following command in my typescript module... 
![tsc_version_in_node_modules_typescript_folder](https://user-images.githubusercontent.com/12489567/49142663-a2fbf580-f2f9-11e8-984b-5017c293d335.PNG)
 ...and can now 100% positively confirm, that the issue _isn't related to what you referred to initially in your answer_ but to the fact that the typescript version being used by npm is the one that resides in the Control Panel and not the actual installed npm typescript version in Node JS.

I have tried to locate the SDK being used by npm at the moment following this suggestion here --> [https://stackoverflow.com/a/29711046/4976069](https://stackoverflow.com/a/29711046/4976069) as well as the next suggestion with screenshot following underneath but can neither locate the `PATH` option in "Advanced System Settings" nor does the "Microsoft SDKs" folder have any "Typescript" folder in it. Considering that the post and answers are 4-5 years old and I cannot find the aforementioned folder I'm mostly tending to believe that the issue is related to this --> [https://stackoverflow.com/a/26596145/4976069](https://stackoverflow.com/a/26596145/4976069) which indicates, that the typescript now in use is bundled inside either the Visual Studio Code or related packages in Control Panel...
![control_panel_visual_studio_code_installations](https://user-images.githubusercontent.com/12489567/49144024-9e850c00-f2fc-11e8-84f5-aab2729ca6ff.PNG)
...and the question now is, which ones and how to make npm use typescript from node_modules instead. I am not sure if changing the curent `package.json` typescript dependency setting which retrieves typescript from github directly would alter this behavior but if so, I would like to get some input on how to achieve that.

Would you kindly get back on the above? Also I would appreciate if you'd reopen the question from the "Closed" status as it isn't answered yet. Thanks.

**Comment by alan-agius4** [comment]
Hi, if you take a look at the warnings, they are stating that  you need that you need to install `TypeScript 3.1.3+`

You need to install these dependencies version by specifying them in your `package,json`.

**Comment by alan-agius4** [comment]
The CLI itself, doesn't install TypeScript. TypeScript is not a direct dependency of the CLI. But rather it gets installed as specified in your `package.json`

TypeScript should not be installed globally, but rather locally. in your local `package.json` You need to specify the correct TypeScript version, as local versions superseed global versions.

More over, in the screen mentioned https://user-images.githubusercontent.com/12489567/48916355-3e1c4780-ee82-11e8-9126-8a3d819d864b.PNG it does show that you don't have the correct dependency installed.

Go to the application folder, and run: 
```bash
npm ls typescript
```

**Comment by alan-agius4** [comment]
Hello, you are trying to run `npm audit fix` in `node_modules`. `npm audit fix` needs to be executed in parallel to the your `package.json` & `package-lock.json`.

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Thanks for your understanding.

**Comment by zoezydk** [comment]
@alan-agius4 Hi again Alan! Yes, my bad. Sorry. It was late yesterday and I was tired, so I ran it from the wrong directory. However as you can see from below screenshot, that really doesn't matter...
![npm_fix_audit_run_in_app](https://user-images.githubusercontent.com/12489567/49209056-b8d0ef80-f3b9-11e8-9f90-7fd06d61bd94.jpg)
...since the issue persists when running it from the app folder. The CLI still uses the wrong version of typescript installed. So if you would be so kind as to look into this, I'd appreciate it a lot. This is not a SO question, it's related to the CLI as can be seen from the screenshot. Thanks.

**Comment by zoezydk** [comment]
@alan-agius4 I solved the problem following the instructions in this link [https://www.reddit.com/r/node/comments/8mwg0x/how_to_update_packagelockjson_properly](https://www.reddit.com/r/node/comments/8mwg0x/how_to_update_packagelockjson_properly). Apparently `package-lock.json` wasn't updated and running the command did the job. You can close this post now. Thanks.
