### ISSUE TITLE
cannot install @angular-devkit/build-angular@0.10.6

### ISSUE THREAD

**Issue by IvannaBabchanik** [angular/angular-cli#13033]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
node --version v11.2.0

### Repro steps
1) run npm i @angular-devkit/build-angular@0.10.6
Observed: error when install node-sass@4.9.3
Expected:  it should be possible to install build-angular without any issues.
NOTE: node-sass version is hard coded in build-angular package.json.  node-sass@4.10.0 installed without any issue.

### The log given by the failure

> node-sass@4.9.3 install C:\Users\Ivanna_Babchanik\Documents\web-drillplan\node_modules\@angular-devkit\build-angular\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.3/win32-x64-67_binding.node":

HTTP error 404 Not Found

**Comment by alan-agius4** [comment]
Hi, the current version of node sass that we listed as a dependnecy is not comparable with node 11.

Will create a fix for this soon.

**Comment by alan-agius4** [comment]
Actually a fix for this has already been done and merged

See: https://github.com/angular/angular-cli/pull/12890
