### ISSUE TITLE
IE 11 : Error TypeError: Unable to get property 'length' of undefined or null reference

### ISSUE THREAD

**Issue by beyondrakeshb** [angular/angular-cli#13041]
I am stuck in angular 7 with IE 11, project is working perfectly fine  all other browser chrome, firefox or even IE (Edge) but giving error in IE 11.
Thanks in advanced

### The log given by the failure
 **Error TypeError: Unable to get property 'length' of undefined or null reference**
 **Error TypeError: Unable to get property 'message' of undefined or null reference**

### Desired functionality
we want to solve calling api request.

 **Environment** 
Angular CLI: 7.0.6
Node: 8.10.0
NPM : 3.5.2
OS: linux x64
Angular: 7.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

### Repro steps

1. ng build --prod
2. My Project folder -> dist -> Copy build folder and paste in new folder on root
3. For apache server deployement, we can put .htaccess file in new angular app folder.
4. Change <base href="/"> to <base href="/myproject/"> in index.html of angular app.
5. Open IE 11 browser and run project with http://192.***.*.***/myproject/
6. **After that in console network tab, note making any http request.** (Major issue)

### Mention any other details that might be useful

.htaccess file (project root for apache server configuration)

<IfModule mod_rewrite.c>

  RewriteEngine On

  RewriteBase /myproject/

  RewriteRule ^index\.html$ - [L]

  RewriteCond %{REQUEST_FILENAME} !-f

  RewriteCond %{REQUEST_FILENAME} !-d

  RewriteRule . /index.html [L]

</IfModule>

---------------------------------------------------------------------------------------------------------------------
pollyfills.js

/***************************************************************************************************
* BROWSER POLYFILLS
*/
/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
/** IE10 and IE11 requires the following for NgClass support on SVG elements */
// import 'classlist.js';  // Run `npm install --save classlist.js`.
/** IE10 and IE11 requires the following for the Reflect API. */
import 'core-js/es6/reflect';
import 'core-js/es7/array';
import 'core-js/es7/object';
/** Evergreen browsers require these. **/
// Used for reflect-metadata in JIT. If you use AOT (and only Angular decorators), you can remove.

/**
* Required to support Web Animations `@angular/platform-browser/animations`.
* Needed for: All but Chrome, Firefox and Opera. http://caniuse.com/#feat=web-animation
**/
// import 'web-animations-js';  // Run `npm install --save web-animations-js`.
/***************************************************************************************************
* Zone JS is required by default for Angular itself.
*/
import 'zone.js/dist/zone';  // Included with Angular CLI.

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

/**
 * Date, currency, decimal and percent pipes.
 * Needed for: All but Chrome, Firefox, Edge, IE11 and Safari 10
 */
import 'intl';  // Run `npm install --save intl`.
/**
 * Need to import at least one locale-data with intl.
 */
import 'intl/locale-data/jsonp/en';

------------------------------------------------------------------------------------------------------------------
tsconfig.json

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": ["googlemaps"],
    "lib": [
      "es2017",
      "dom"
    ]
   
  }
}

---------------------------------------------------------------------------------------------------------------------------
angular.json

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "simpaltekCSWeb": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/Nexx.CustomerSupport",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              //"../node_modules/bootstrap/dist/css/bootstrap.min.css",
              "src/styles.scss",
              "src/assets/vendor/bootstrap/css/bootstrap.min.css",
              "src/assets/vendor/font-awesome/css/font-awesome.min.css",
              "src/assets/css/fontastic.css",
              "src/assets/css/style.default.css"
            ],
            //"scripts": [ "./node_modules/jquery/dist/jquery.min.js" ],
            //"scripts": [ "./node_modules/jquery/dist/jquery.min.js" ],
            "scripts": [
              "./node_modules/jquery/dist/jquery.min.js",
              "./node_modules/bootstrap/dist/js/bootstrap.js",
              "src/assets/vendor/bootstrap/js/bootstrap.min.js"

            ]

          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "simpaltekCSWeb:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "simpaltekCSWeb:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "simpaltekCSWeb:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "simpaltekCSWeb-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "simpaltekCSWeb:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "simpaltekCSWeb:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "simpaltekCSWeb"
}

**Comment by alan-agius4** [comment]
Hi, what is the stacktrace of the errors?, does this happen with an `ng new` application?

**Comment by ahnpnl** [comment]
@beyondrakeshb I encountered this error before when I didn't uncomment import 'classlist.js' . Maybe you can try to uncomment it.

**Comment by beyondrakeshb** [comment]
@ahnpnl  Thank you for your valuable answer and i have uncommented 'classlist.js'. It has been working in IE 11 and IE 10 also.
