### ISSUE TITLE
Can't install angular-cli

### ISSUE THREAD

**Issue by ZhangPuXi** [angular/angular-cli#1304]
My operating system is Windows8, and I'm sure that the typescript and typings are correctly installed on my machine. My node version is 4.4. The problem is when I install the angular-cli, it's not complete after a long time,  my command line shows nothing, just nothing, neither error messages nor success info. Please help me

**Comment by RicardoVaranda** [comment]
Can you post the results for the following:

npm -v
node -v

**Comment by diahron** [comment]
try updating your node js.

**Comment by jkuri** [comment]
as @diahron said, try updating your node version to version 5 or 6.

**Comment by felipealfonsog** [comment]
it's seems to be that upgrading the version of node.js is going to fix this issue .... I've updated the version to 9.1.0
