### ISSUE TITLE
Errors when project using rxjs 6, rxjs-compat 6, and dependency lib uses rxjs 5

### ISSUE THREAD

**Issue by rekhubs** [angular/angular-cli#13058]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Windows 10
$node -v
v8.11.2
$npm -v
6.0.0

### Repro steps
My project is using rxjs 6 and rxjs-compat 6, and a dependency lib which uses rxjs 5. 
`ng build` working, no errors reported, `ng serve` starts successfully, but errors reported in console when page loaded (logs below), and elements can't be loaded. The page is using customized directive from the dependency lib.

I would expect `ng build` and `ng serve` can resolve the syntax in the dep lib, since I have rxjs-compat in my project depencies.

### The log given by the failure
ExploreComponent.html:88 ERROR TypeError: rxjs_Observable__WEBPACK_IMPORTED_MODULE_1__.Observable.of is not a function
    at UserService.push../node_modules/@my-lib/lib/esm5/lib.js.UserService.hasAuthority (lib.js:323)
    at HasAuthorityDirective.push../node_modules/@my-lib/lib/esm5/lib.js.HasAuthorityDirective.ngOnInit (lib.js:368)
    at checkAndUpdateDirectiveInline (core.js:9243)
    at checkAndUpdateNodeInline (core.js:10507)
    at checkAndUpdateNode (core.js:10469)
    at debugCheckAndUpdateNode (core.js:11102)
    at debugCheckDirectivesFn (core.js:11062)
    at Object.eval [as updateDirectives] (ExploreComponent.html:88)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11054)
    at checkAndUpdateView (core.js:10451)

### Desired functionality
I would expect `ng build` and `ng serve` can resolve the syntax in the dep lib, since I have rxjs-compat in my project depencies. 
And it's , say a new project uses rxjs 6/7, rxjs-compat 6, then adds a lib dep which uses rxjs 5, there could be similar issues, and it's a valid use case.

### Mention any other details that might be useful
$ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.2.7
Node: 8.11.2
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.7
@angular-devkit/build-angular     0.8.7
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/build-webpack     0.8.7
@angular-devkit/core              0.8.7
@angular-devkit/schematics        0.6.1
@angular/cdk                      6.4.7
@angular/cli                      6.2.7
@angular/flex-layout              6.0.0-beta.18
@angular/material                 6.4.7
@ngtools/webpack                  6.2.7
@schematics/angular               0.8.7
@schematics/update                0.8.7
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.16.4

$npm ls webpack
`-- @angular-devkit/build-angular@0.8.7
  `-- webpack@4.16.4

$npm ls @ngtools/webpack
`-- @angular-devkit/build-angular@0.8.7
  `-- @ngtools/webpack@6.2.7

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by JoostK** [comment]
I have seen this issue too and have attempted to create a minimal reproduction but was unable to find the exact setup. I did track this issue down to originate from https://github.com/ReactiveX/rxjs/pull/3974, you can test with RxJS 6.2.x using which I did not experience this issue.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
