### ISSUE TITLE
sourcemap generation stuck at 95% using styleUrls for .css file 

### ISSUE THREAD

**Issue by suraj-magadum** [angular/angular-cli#13053]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions 
Node version:  v8.9.3
Npm version: 5.5.1
ng version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.4
Node: 8.9.3
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

### Repro steps
1.Create new angular app
2.Add any css rule in app.component.css file 
3.run comand " ng build --prod --sm "
4.build stuck at 95% for infinite time

### Desired functionality
Should generate source map successfully

### Mention any other details that might be useful
rename of app.component.css  to app.component.scss will generate source map successfully

**Comment by clydin** [comment]
Angular CLI's version 1.x is no longer actively supported.  Please consider updating to the most recent version (currently 7.0.6).
