### ISSUE TITLE
Feature Request: configure ng update defaults via angular.json

### ISSUE THREAD

**Issue by adamdport** [angular/angular-cli#13056]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node 8.12.0, npm 6.4.1, ng 7.0.6

### Desired functionality
I'd like to configure the default flags (eg. registry) for `ng update` so that I can run

    ng update

 Instead of

    ng update --registry http://my.company.registry/

**Comment by clydin** [comment]
`ng update` should be using `.npmrc` files present on the system.  Can you try with CLI 7.1.0?  It greatly improves the handling of registry configuration settings.

**Comment by adamdport** [comment]
@clydin yes, 7.1.0 respected my `npmrc`. Thanks!
