### ISSUE TITLE
Angular 7, lazy loading feature modules doesn't work with JIT compiler

### ISSUE THREAD

**Issue by nehawadhwa** [angular/angular-cli#13068]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.6
Node: 10.7.0
OS: win32 x64
Angular: 7.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.6
@angular-devkit/build-angular     0.10.6
@angular-devkit/build-optimizer   0.10.6
@angular-devkit/build-webpack     0.10.6
@angular-devkit/core              7.0.6
@angular-devkit/schematics        7.0.6
@angular/cli                      7.0.6
@ngtools/webpack                  7.0.6
@schematics/angular               7.0.6
@schematics/update                0.10.6
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

### Repro steps
I have implemented lazy loading for angular 7 app. Feature module doesn't seem to lazy load with JIT compiler when just using ng serve and gives error as mentioned below in stack- undefined is not a function.. It works well(chunks are created) with aot(ng serve --aot). 
I am not importing lazy loaded module in app.module. 
Careers is my feature module here
careers-routing.module.ts file looks like this:
export const ROUTES: Routes = [
  {
    canActivate: [AuthGuard],
    path: '',
    component: CareerDashboardComponent
  },
  {
    canActivate: [AuthGuard],
    path: ':id',
    component: CareerProfileComponent,
  }
];

@NgModule({
  imports: [RouterModule.forChild(ROUTES)],
  exports: [RouterModule],
})
export class CareersRoutingModule { }
careers.module.ts file:
@NgModule({
  imports: [
    CommonModule,
    SharedModule,
    StoreModule.forFeature(CAREER_FEATURE_KEY, {
      career: reducer,
    }),
    EffectsModule.forFeature(effects),
    CareersRoutingModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: TranslateLoaderFactory,
        deps: [HttpClient, Injector]
      }
    })
  ],
app-routing.module.ts:
export const ROUTES: Routes = [
  { path: '', pathMatch: 'full', component: LoginComponent },
  { path: 'careers', loadChildren: 'src/careers/careers.module#CareersModule' },
];

@NgModule({
  imports: [RouterModule.forRoot(ROUTES, {
    enableTracing: true,
    scrollPositionRestoration: 'enabled',
    preloadingStrategy: PreloadAllModules
  })],
  exports: [RouterModule]
})
export class AppRoutingModule { }
app.module.ts:
@NgModule({
  declarations: [
    AppComponent,
    BaseTemplateComponent,
    ActionViewComponent,
    SessionTimeoutComponent
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    BrowserAnimationsModule,
    SharedModule,
    SortablejsModule.forRoot({ animation: 150 }),
    AboutMeModule,
    AuthModule,
    StoreModule.forRoot(reducers, {}),
    StoreRouterConnectingModule,
    EffectsModule.forRoot(effects),
    StoreDevtoolsModule.instrument({}),
    InlineSVGModule.forRoot(),
    AppRoutingModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: TranslateLoaderFactory,
        deps: [HttpClient, Injector]
      }
    })
  ]

### The log given by the failure
"TypeError: undefined is not a function
    at Array.map (<anonymous>)
    at webpackAsyncContext (http://localhost:4200/main.js:58:34)
    at SystemJsNgModuleLoader.push../node_modules/@angular/core/fesm5/core.js.SystemJsNgModuleLoader.loadAndCompile (http://localhost:4200/vendor.js:58258:82)
    at SystemJsNgModuleLoader.push../node_modules/@angular/core/fesm5/core.js.SystemJsNgModuleLoader.load (http://localhost:4200/vendor.js:58250:60)
    at RouterConfigLoader.push../node_modules/@angular/router/fesm5/router.js.RouterConfigLoader.loadModuleFactory (http://localhost:4200/vendor.js:77886:82)
    at RouterConfigLoader.push../node_modules/@angular/router/fesm5/router.js.RouterConfigLoader.load (http://localhost:4200/vendor.js:77874:35)
    at MergeMapSubscriber.project (http://localhost:4200/vendor.js:76883:47)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._tryNext (http://localhost:4200/vendor.js:155605:27)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/mergeMap.js.MergeMapSubscriber._next (http://localhost:4200/vendor.js:155595:18)
    at MergeMapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (http://localhost:4200/vendor.js:150052:18)"

### Desired functionality
I want to be able to lazy load feature modules with JIT compiler. For local development purposes, don't want the AoT enabled.

### Mention any other details that might be useful

**Comment by alan-agius4** [comment]
Hi, 

Application routes need to be relative to the routing module. Kindly see: https://angular.io/guide/lazy-loading-ngmodules#routes-at-the-app-level

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by nehawadhwa** [comment]
@alan-agius4 it doesn't work with relative routing, I have tried with
  { path: 'careers', loadChildren: './careers/careers.module#CareersModule' } and it still gives same error.
