### ISSUE TITLE
Ng update

### ISSUE THREAD

**Issue by DuncanFaulkner** [angular/angular-cli#13060]
when running ng update --all

Affected Package
Package "@angular-devkit/build-webpack" has a missing peer dependency of "webpack" @ "^4.6.0".

Description
When running ng update I get a list of files that are able to be updated
when I run ng update --all I get the following error
Package "@angular-devkit/build-webpack" has a missing peer dependency of "webpack" @ "^4.6.0"

doing an ng v, I get the following information

Angular CLI: 7.0.6
Node: 8.11.4
OS: linux x64
Angular: 7.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router, upgrade

Package Version
@angular-devkit/architect 0.10.6
@angular-devkit/build-angular 0.10.6
@angular-devkit/build-optimizer 0.10.6
@angular-devkit/build-webpack 0.10.6
@angular-devkit/core 7.0.6
@angular-devkit/schematics 7.0.6
@angular-devkit/schematics-cli 0.10.6
@angular/cli 7.0.6
@angular/flex-layout 7.0.0-beta.19
@ngtools/webpack 7.0.6
@schematics/angular 7.0.6
@schematics/schematics 0.10.6
@schematics/update 0.10.6
rxjs 6.3.3
typescript 3.1.6
webpack 4.19.1

as you can see webpack is at 4.19.1 which appears to be the latest version

ubuntu 18.04.1
vs code 1.30

**Comment by DuncanFaulkner** [comment]
Any update on this?

running ng update returns:
   Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       7.2.1 -> 7.2.2           ng update @angular/cdk
      @angular/cli                       7.2.1 -> 7.2.2           ng update @angular/cli
      @angular/core                      7.2.0 -> 7.2.2           ng update @angular/core
      @angular/material                  7.2.1 -> 7.2.2           ng update @angular/material

yet when I run ng update --all I get
  Package "@angular-devkit/build-webpack" has a missing peer dependency of "webpack" @ "^4.6.0".

**Comment by mgechev** [comment]
@DuncanFaulkner would you share a repo where we can reproduce the problem?

You can delete the `src` directory, we're mostly interested in `package.json`.

**Comment by DuncanFaulkner** [comment]
I'm not able to put a repo together but can share package.json here if that helps
```
{
  "name": "frontend",
  "version": "0.41.15",
  "description": "Administration Portal",
  "author": "Duncan",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.json -s -w",
    "build:server": "ng build && cp server/* dist",
    "build:server-prod": "ng build --prod && cp server/* dist",
    "serve-build": "npm run build:server && cd dist && node server.js",
    "serve-build-prod": "npm run build:server-prod && cd dist && node server.js",
    "build:sass": "node-sass src/scss/ -o src/assets/css/",
    "watch:sass": "npm run build:sass && node-sass src/scss/ -wo src/assets/css/"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.2",
    "@angular/cdk": "^7.2.2",
    "@angular/common": "^7.2.2",
    "@angular/compiler": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/material": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/platform-server": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@angular/upgrade": "^7.2.2",
    "@auth0/angular-jwt": "^2.1.0",
    "@schematics/angular": "^7.2.2",
    "angular-svg-round-progressbar": "^2.0.0",
    "angular2-highcharts": "^0.5.5",
    "angular2-text-mask": "^9.0.0",
    "angular2-uuid": "^1.1.1",
    "core-js": "^2.6.2",
    "hammerjs": "^2.0.8",
    "moment": "^2.23.0",
    "ng-inline-svg": "^8.3.0",
    "ng2-mqtt": "^0.1.2",
    "ngx-device-detector": "^1.3.5",
    "ngx-pipes": "^2.3.6",
    "rxjs": "^6.3.3",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.2",
    "@angular-devkit/build-webpack": "^0.12.2",
    "@angular-devkit/architect": "^0.12.2",
    "@angular-devkit/build-optimizer": "^0.12.2",
    "@angular-devkit/core": "^7.2.2",
    "@angular-devkit/schematics": "^7.2.2",
    "@angular-devkit/schematics-cli": "^0.12.1",
    "@angular/cli": "^7.2.2",
    "@angular/compiler-cli": "^7.2.2",
    "@angular/language-service": "^7.2.2",
    "@compodoc/compodoc": "^1.1.7",
    "@types/hammerjs": "^2.0.36",
    "@types/jasmine": "^3.3.5",
    "@types/lodash": "^4.14.119",
    "@types/node": "^10.12.18",
    "@types/uuid": "^3.4.4",
    "codelyzer": "^4.5.0",
    "es6-promise-loader": "^1.0.2",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.1.4",
    "karma-chrome-launcher": "^2.2.0",
    "karma-jasmine": "^2.0.1",
    "karma-remap-istanbul": "^0.6.0",
    "node-sass": "^4.11.0",
    "protractor": "^5.4.2",
    "ts-node": "^7.0.1",
    "tslint": "^5.12.1",
    "typescript": "^3.2.4"
  }
}
```

**Comment by clydin** [comment]
Based on the package.json, this is expected behavior. The “ng version” command displays the CLI’s internal version of webpack.  The package “@angular-devkit/build-webpack” requires that a version of webpack is install directly.  From the package.json this appears to not be the case.
