### ISSUE TITLE
95% emitting CopyPlugin bug

### ISSUE THREAD

**Issue by victorschinaider** [angular/angular-cli#13061]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node Version: v11.0.0
Npm Version: 6.4.1
Angular Cli: 7.0.2 and 7.0.6

### Repro steps

It's a little difficult to reproduce, but happens constantly. I'm using the command:
```
ng serve --host=myhost.com
```

### The log given by the failure

95% emitting CopyPlugin

### Desired functionality

To not bug things. In add to it,when the serve pass the '95%' phase, but it freezes when the serve reloads.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by victorschinaider** [comment]
Thanks for feedback, @alan-agius4.
I'll try to create.

**Comment by victorschinaider** [comment]
Apparently, in Angular ci 7.1.0 was solved. I'm testing, and no bugs. So i'm closing for now. Thanks @alan-agius4
