### ISSUE TITLE
@alan-agius4 <-- Closed question --> ng-packagr@4.4.0 requires a peer of [missing peer version] but none is installed. <-- still unanswered/please reopen

### ISSUE THREAD

**Issue by zoezydk** [angular/angular-cli#13072]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting (posted issue here but received incorrect answer --> https://github.com/angular/angular-cli/issues/13036
```
_Issue still persists!_

### Command (mark with an `x`)
```
- [ x ] npm install ng-packagr
```

### Versions

Output from:
`node --version` --> v8.12.0
`npm --version` --> 6.4.1
`ng --version`  -->
Angular CLI: 7.0.3
Node: 8.12.0
OS: win32 x64
Angular: undefined

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.3 (cli-only)
@angular-devkit/core         7.0.3 (cli-only)
@angular-devkit/schematics   7.0.3 (cli-only)
@ngtools/json-schema         1.1.0
@schematics/angular          7.0.3 (cli-only)
@schematics/update           0.10.3 (cli-only)
ng-packagr                   4.4.0
rxjs                         6.3.3
typescript                   2.5.2
webpack                      4.26.0
Windows (10)

### Repro steps

In terminal running npm i ng-packagr command results in issue.

### Desired functionality

No warning in CLI when installing package

### Mention any other details that might be useful

Posted this issue about a week ago...
[https://github.com/angular/angular-cli/issues/13036](https://github.com/angular/angular-cli/issues/13036)... but got an incorrect answer and issue was closed right after that.

@alan-agius4 --> I'd like you to take a look at my new posts and get back to me with a viable solution as the answer you posted _is incorrect_. Also I'd appreciate it if the issue wasn't closed until there was some kind of common understanding that the issue is actually solvable with the given answer. As such I'd kindly ask you to reopen and not to close before that status is achieved. Thanks.

**Comment by alan-agius4** [comment]
Will reply in the other issue.
