### ISSUE TITLE
Hybrid/ngUpdate build does not output a changed chunk when updating AngularJS javascript sources

### ISSUE THREAD

**Issue by ManuelRauber** [angular/angular-cli#13076]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Windows 7, Node 10 LTS, Angular 7.1.0

### Failure Description

I've an Angular project, which is currently upgraded using NgUpgrade from an older AngularJS project. Yesterday, I've updated from Angular 6 to Angular 7 using `ng update` and started the project as usual with `ng serve`. 

However, I've noticed a strange behaviour with the update. When I've used Angular 6 and I changed some code within the JS-Files from the AngularJS project, the CLI recompiled the app and outputted one changed chunk. 
With Angular (CLI) 7, the CLI recompiles after a change as well, but does not output a changed chunk, so the changed code is not there after the live reload. Source Maps are also broken at this point. However, if I change code within a template file of the AngularJS app, then a new chunk will be generated. 

In both versions it worked perfectly when changing TypeScript sources (but still, won't update the JS sources within the changed chunk)

### Desired functionality

It should work like it did before, so whenever I change code within the AngularJS code base, the recompilation should output a changed chunk with the new code.

I've also noticed, that if I remove `allowJs` from my `tsconfig.app.json`, it works as expected with Angular 7. 

### Package Versions:

Angular (CLI/ Compiler CLI, Language Service etc.): 7.1.0
@angular-devkit/build-angular: 0.11.0

**Comment by alan-agius4** [comment]
This might be somewhat also related to https://github.com/angular/angular-cli/issues/12964
