### ISSUE TITLE
How can i ignore some files updating when testing

### ISSUE THREAD

**Issue by johnny-mh** [angular/angular-cli#13079]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node v10.13.0
npm 6.4.1
ng 7.0.5

### Repro steps
I'm using spacemacs for editing source codes.

Spacemacs using `flycheck` to displaying lint errors in live.

Some technical reason. `flycheck` make and delete temporary files in short time. while editing file.

The temporary filename rule is `flycheck_{{filename}}` (flycheck_app.component.ts)

I asked flycheck contributors that how to move temporary files path.

But they recommands that just ignore temporary files. (**/flycheck*)

So I modifying configuration files to ignore those but those are not work properly.

1. karma.conf.js

```
config.set({
  exclude: ['**/flycheck*']
});
```

NOT WORK

2. tsconfig.spec.json
```
{
  ...
  "exclude": ['**/flycheck*']
  ...
}
```

NOT WORK

How can i ignore some pattern of files when testing?

![watch](https://user-images.githubusercontent.com/1061205/49191562-57f5e700-f3ba-11e8-9440-6149bc800217.gif)

### Desired functionality
Test watch ignore some pattern files.

**Comment by alan-agius4** [comment]
Hi, i think the pattern needs to be added in the `tsconfig.spec.json`.

If the problem persists it would be great to have a reproduction. 

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by johnny-mh** [comment]
@alan-agius4 I got it. here is the link https://github.com/johnny-mh/repro-app

**Comment by filipesilva** [comment]
This is actually the same as https://github.com/angular/angular-cli/issues/11880#issuecomment-425485744.

The rebuild happens because the test file does a require for all files that end with .spec.ts, and you are indeed creating more such files.

You can adjust that regex I believe.
