### ISSUE TITLE
build returns an error when using --output-path  flag 

### ISSUE THREAD

**Issue by OrrTytocare** [angular/angular-cli#13084]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.0.6
Node: 10.13.0
OS: win32 x64
NPM: 6.4.1

### Repro steps
create new application ```ng g application new-app``` 
run build  ```ng build new-app --output-path=/dev```

### The log given by the failure
Unknown option: '--output-path'

### Desired functionality
The build will be set to /dev directory

### More
When running ```ng build --help``` output-path is suggested as an option

**Comment by alan-agius4** [comment]
Hi, can you please provide the complete output of `ng version`?

Also, can you try to update to the latest version of the Angular CLI and Devkit packages?

**Comment by OrrTytocare** [comment]
It looks like upgrading solved the issue, thanks !
