### ISSUE TITLE
gh-pages:deploy - skip changing base tag in index.html

### ISSUE THREAD

**Issue by PascalTemel** [angular/angular-cli#1308]
> ## Please provide us with the following information:
> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>    Ubuntu 16.04
1. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
       node --version
   And paste the result here.
   v6.2.2
2. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   Created and deployed with angular cli
3. Mention any other details that might be useful.
   I have my own domain that redirects to my gh-pages project through A records. Deploying to gh-pages through angular-cli results in the `base` tag in the index.html file being changed to my project name, however, this is not necessary in my case since the base is still '/'. The result is paths that use this tag point to the wrong files and I have to manually adjust the tag after every deploy.
   Therefore I would like some option to disable the tag-change.

**Comment by MuhammedHasan** [comment]
I have the same issue.

Ubuntu 16.04
angular-cli beta-8

**Comment by lirantal** [comment]
This has been fixed already: https://github.com/angular/angular-cli/issues/2222
Use `ng github-pages:deploy --base-href /`

**Comment by filipesilva** [comment]
Closing as fixed, thanks @lirantal!
