### ISSUE TITLE
ng serve, subsequent compilations are successful regardless of type errors.

### ISSUE THREAD

**Issue by DanielSwiegersServian** [angular/angular-cli#13083]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node --version
<code>v10.13.0</code>

npm --version
<code>6.4.1</code>

ng --version
<pre><code>     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.7
Node: 10.13.0
OS: linux x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1</code></pre>
</code></pre>

### Repro steps
Create new project <code>ng new demo</code>  
(No extra routing, css stylesheet)

Modify app.component.ts
<pre><code>
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: 'It Works!'
})
export class AppComponent {
  mySurvey: Survey = { id: 'a' };
  constructor() {
    this.mySurvey.id = 'b';
  }
}
export interface Survey {
  id?: string;
}
</code></pre>

run <code>ng serve</code>
> compiles successfully

Update and save <code>this.mySurvey.idsss = 'b';</code>
> compiles successfully (displays error in console but compiles successfully)

Stop and start <code>ng serve</code>
> fails to compile with error

Save file with no additional changes
> compiles successfully

### The log given by the failure
<pre><code>➜  demo git:(master) ✗ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2018-11-29T03:28:21.352Z
Hash: 92635ada15821b678c59
Time: 7627ms
chunk {main} main.js, main.js.map (main) 8.92 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 223 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.2 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.31 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
                                                                                          
Date: 2018-11-29T03:28:24.864Z - Hash: 136e61461f142c284392 - Time: 1632ms
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 8.92 kB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.

ERROR in src/app/app.component.ts(10,19): error TS2339: Property 'idsss' does not exist on type 'Survey'.

^C
➜  demo git:(master) ✗ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2018-11-29T03:28:38.310Z
Hash: 07924f65201bbc73626e
Time: 4405ms
chunk {main} main.js, main.js.map (main) 1.91 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.4 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.2 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 318 kB [initial] [rendered]

ERROR in src/app/app.component.ts(10,19): error TS2339: Property 'idsss' does not exist on type 'Survey'.

ℹ ｢wdm｣: Failed to compile.
ℹ ｢wdm｣: Compiling...
                                                                                          
Date: 2018-11-29T03:28:47.173Z - Hash: 136e61461f142c284392 - Time: 4432ms
2 unchanged chunks
chunk {main} main.js, main.js.map (main) 8.92 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 223 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.31 MB [initial] [rendered]
ℹ ｢wdm｣: Compiled successfully.

ERROR in src/app/app.component.ts(10,19): error TS2339: Property 'idsss' does not exist on type 'Survey'.
</code></pre>

### Desired functionality
<code>ng serve</code> should fail to compile on **type** errors on save, currently it only fails the first time <code>ng serve</code> is run, then always succeeds

### Mention any other details that might be useful
Non **type** errors successfully cause compilation to fail (e.g. renaming a component class but not its module declaration) on save.

**Comment by alan-agius4** [comment]
@filipesilva, can you chime in on this? I know you look at something similar in the forked type checker a couple of week ago.

Thanks.

**Comment by filipesilva** [comment]
This is the intended behaviour actually. By default we fork the type checker and it runs in a separate process. This way you get a faster rebuild on errors that don't prevent transpilation.

This does mean you can get a successful compilation, followed by type errors. The other way around is also possible but unlikely. But overall 

You can turn it off though, using the `forkTypeChecker` option on the build target.

**Comment by DanielSwiegersServian** [comment]
For those who run into this you can disable the option by modifying the following field in your <code>angular.json</code>
<pre><code>{
  "projects": {
    "my-project-name": {
      "architect": {
        "build": {
          "options": {
            "forkTypeChecker": false
          }
        }
      }
    }
  }
}</code></pre>
