### ISSUE TITLE
Help to build with different static file paths

### ISSUE THREAD

**Issue by danilohgds** [angular/angular-cli#13090]
### Command (mark with an `x`)
```
- [ ] new
- [x] build
```

### Versions
Node v 8.11.3 , Linux machine

### Repro steps
start an application, build with 
ng build --base-href=/whatever/ --deploy-url=/whatever/  --prod --build-optimizer

Host on nginx with

location /whatever {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html =404;
  } 

### The log given by the failure
runtime.c88d7988090c0cf17003.js:1 Uncaught SyntaxError: Unexpected token <
polyfills.c6871e56cb80756a5498.js:1 Uncaught SyntaxError: Unexpected token <
main.f6db57f5db3471ef76b6.js:1 Uncaught SyntaxError: Unexpected token <

### Desired functionality
I want to be able to use ng build and have different paths for different versions of the application such as:

- localhost:xxxx/master/
- localhost:xxxx/testing

I realize this is a help request not an issue per se, but I assume this is the best place to write to anyway.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
