### ISSUE TITLE
Dependency not found in webpack and webpack-dev-server

### ISSUE THREAD

**Issue by mguz369** [angular/angular-cli#13091]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 7.1.0
Node: 10.14.0
OS: win32 x64
Angular: 7.1.1
NPM: 6.4.1

### Package Version
```
@angular-devkit/architect 0.11.0 (cli-only)
@angular-devkit/build-angular 0.11.0
@angular-devkit/core 7.1.0 (cli-only)
@angular-devkit/schematics 7.1.0 (cli-only)
@angular/cli 7.1.0
@schematics/angular 7.1.0 (cli-only)
@schematics/update 0.11.0 (cli-only)
rxjs 6.3.3
typescript 3.1.6
```

### Repro steps
```
npm install -g @angular/cli
ng new testapp
cd testapp
ng serve
```

### The log given by the failure
```
$ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2018-11-29T15:36:27.948Z
Hash: 3464f74bc6e73aaf9a5d
Time: 9808ms
chunk {main} main.js, main.js.map (main) 9.98 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 223 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.38 MB [initial] [rendered]

ERROR in (webpack)/hot/emitter.js
Module not found: Error: Can't resolve 'events' in 'C:\Users\bnetz\Desktop\testapp\node_modules\@angular-devkit\build-angular\node_modules\webpack\hot'
ERROR in (webpack)-dev-server/client?http://0.0.0.0:0
Module not found: Error: Can't resolve 'url' in 'C:\Users\bnetz\Desktop\testapp\node_modules\@angular-devkit\build-angular\node_modules\webpack-dev-server\client'
```

### Desired functionality
Fix dependency issue

### Mention any other details that might be useful
Created multiple projects using ng new, all got the same error. Installed/Uninstalled @angular/cli a couple times to make sure I had the most up to date version. Updated Node and NPM to current versions. Was only able to fix by installing the missing packages 'events' and 'url' into the 'webpack' and 'webpack-dev-server' respectively.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
