### ISSUE TITLE
buildOptimizer makes openlayers functionality differ

### ISSUE THREAD

**Issue by AnthonNilsson** [angular/angular-cli#13092]
The functionality in openlayers will break/change if using it with angular-cli buildOptimizer true.

I have posted this error in the openlayers github page, but maybe it beloongs here instead. Here is a link to the issue: https://github.com/openlayers/openlayers/issues/9019

**Comment by deebloo** [comment]
@AnthonNilsson can you fill out the issue template please? It will help troubleshoot your issue.

**Comment by alan-agius4** [comment]
Might be related to https://github.com/angular/angular-cli/issues/12760

Also, as @deebloo kindly follow the template.

Thanks.

**Comment by AnthonNilsson** [comment]
Ok, no problem. I have opened a new issue with a better description.
