### ISSUE TITLE
ng serve compiling again and again without any saving changes

### ISSUE THREAD

**Issue by HazizKhan** [angular/angular-cli#13099]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Windows 10
@angular/cli: 7.1.0
node: 8.9.4
npm: 5.6.0

### Repro steps
run ng serve --disable-host-check
after some time it will start compiling again and again without any changes

### Desired functionality
Only compile once after change made by me.

### Mention any other details that might be useful

![image](https://user-images.githubusercontent.com/5469508/49271655-6ca4ae80-f490-11e8-8bcf-7dfbf2044c62.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However we'd need some more information to look into this.

Can you install `node-watch` via `npm i node-watch` and run it in a separate terminal while running `ng serve`, so that we can determine which files are causing the recompilation to re-trigger?

Thanks

**Comment by HazizKhan** [comment]
@alan-agius4 Thanks for replying
after installing `node-watch` there is no such file called `node-watch` in `node_modules/.bin`
![image](https://user-images.githubusercontent.com/13147389/49362149-d080de80-f6ff-11e8-8b35-382b2868b4ae.png)

**Comment by alan-agius4** [comment]
@HazizKhan, I updated my above comment.

**Comment by vovikdrg** [comment]
Looks the same as my problem #13125

**Comment by vovikdrg** [comment]
@HazizKhan  do you have `dist` folder in your project?

**Comment by vovikdrg** [comment]
@alan-agius4 Give me some time. I need to ask permission. 

Also its probably does not make sense to create new. I am thinking to leave same structure but remove all project related stuff. It seems to bug in structure or specifically in way we created it.

**Comment by vovikdrg** [comment]
@alan-agius4 It won't be before Monday for sure.

**Comment by HannesT117** [comment]
Any updates on this? I have a similar problem. For some reason, when removing assets from root path in angular.json, it stopped recompiling. I was not able to reproduce this in a demo app, though. In any other projects, this wasn't a problem at all. Perhaps someone has a clue what's happening, so I'm sharing it anyways.

```
"projects": {
  "myProject": {
    "root": "",
     "sourceRoot": "src",
     "assets": [
        <!-- removed this -->
        {
          "glob": "README.md",
          "input": "",
          "output": "/assets"
        }
        <!-- until here -->
      ]
   }
}
```

**Comment by alan-agius4** [comment]
My though would be something related to https://github.com/webpack-contrib/copy-webpack-plugin/pull/296

Can you check which version of `copy-webpack-plugin` you have installed. (`npm ls copy-webpack-plugin`) it should be at a minimum version 4.5.4.

**Comment by HannesT117** [comment]
Awesome! It was v4.5.3. After updating @angular-devkit/build-angular to the current version, my problem was gone. Thanks a lot! 
@vovikdrg, do you think this could help you as well?

**Comment by alan-agius4** [comment]
This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by tony2tones** [comment]
To resolve this issue i did the following:

ng update @angular/cli @angular/core

**Comment by yogeshgadge** [comment]
I am having the same problem @alan-agius4 even with 
npm ls copy-webpack-plugin
`-- @angular-devkit/build-angular@0.13.8
  `-- copy-webpack-plugin@4.6.0

**Comment by falasvand** [comment]
problem still exists with angular 7.2.15 and angular-cli 7.3.0

**Comment by OussamaHan** [comment]
I had this problem as well. I suggest that you re-install copy-webpack-plugin. This is what fixed it for me. 
`npm install copy-webpack-plugin --save-dev`

**Comment by falasvand** [comment]
project im working on doesnt use webpack
