### ISSUE TITLE
ng serve --open : unknown option: '-n'

### ISSUE THREAD

**Issue by jeremyspatrick** [angular/angular-cli#13094]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node -v v10.14.0 
npm -v 6.4.1 

@angular-devkit/architect 0.10.7
@angular-devkit/build-angular 0.10.7
@angular-devkit/build-optimizer 0.10.7
@angular-devkit/build-webpack 0.10.7
@angular-devkit/core 7.0.7
@angular-devkit/schematics 7.1.0
@angular/cdk 7.1.0
@angular/cli 7.1.0
@ngtools/webpack 7.0.7
@schematics/angular 7.1.0
@schematics/update 0.11.0
rxjs 6.2.2
typescript 3.1.6
webpack 4.19.1

### Repro steps

ng serve --open

### The log given by the failure

unknown option: '-n'

### Desired functionality

build and open a browser

**Comment by alan-agius4** [comment]
Hi kindly update your `@angular-devkit` packages to the latest version `v0.11.0`.

**Comment by jeremyspatrick** [comment]
Did an npm update and set the angular-devkit to v0.11.0 and that did not solve the issue.  What details do you need? 

@angular-devkit/architect 0.11.0 
@angular-devkit/build-angular 0.11.0 
@angular-devkit/build-optimizer 0.11.0 
@angular-devkit/build-webpack 0.11.0 
@angular-devkit/core 7.1.0 
@angular-devkit/schematics 7.1.0 
@angular/cdk 7.1.0 
@angular/cli 7.1.0 
@ngtools/webpack 7.1.0 
@schematics/angular 7.1.0 
@schematics/update 0.11.0 
rxjs 6.2.2 typescript 3.2.1 
webpack 4.23.1

**Comment by jeremyspatrick** [comment]
This error was caused by running open with one dash instead of two

ng serve -open

instead of

ng serve --open
