### ISSUE TITLE
Angular Universal ttfb to first byte is very slow and fully page load

### ISSUE THREAD

**Issue by Easyschools** [angular/angular-cli#13098]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
<--
Linux (Centos) - CPANEL= NGINX- 10 CPU cores & 60 gb ram
npm -v
6.4.1
node -v
v10.10.0
Angular CLI 6
-->

### Repro steps
<--
Simple steps to reproduce this bug.
Please include: commands run (incl args), packages added, related code changes.
A link to a sample repo would help too.
-->

I have followed all the github repo to build application with universal as I needed it fully rendered HTML for seo. but I had a situation with my Angular app TTFB it takes about 7 seconds to byte. which I am really it's really huge for it. I have tried everything on the web to increase it's performance with luck. I used App Shell, Webpack and even changed my server to nginx to serve static content but it's the same. Also another problem that the page takes about 18 seconds to fully which is really huge. Although I am using i18n because the application it's multi language. When I used App shell, my TTFB decreased to 60 ms which is ideal but the probelm that the page only rendered in the static html for the homepage for the whole app. If i tried to analyze any route it will return the same html which will effect my SEO. I understand that I can use csr and google can index it but i don't want to target only google and can be indexed from any craweler.
However, I tried using prerender instead of server side and it did it's magic and loaded the page very quickly but the problem that my web app is really huge have about 80k routes which is not logic. Although that I have a huge server that can store all of this but I thought that's would be stupid idea. Does anyone know any ideas to solve this situation. you will find below my website link and please let me know what do you think with this situation!!!
www.easyschools.org

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Easyschools** [comment]
No i think this problem with it. as it's respionsible for the application bootstrap and page initial load. i am sure that is not normal for ttfb to be 8 seconds for angular project. Although the page size is not that big for this whole load problem.
