### ISSUE TITLE
@angular-devkit/build-angular has a dependency that no longer exists

### ISSUE THREAD

**Issue by mackenziemi** [angular/angular-cli#13104]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] install
```

### Repro steps
run npm install from fresh repo and you will get a missing reference to  har-validator@5.1.2.

### The log given by the failure
2018-11-30T03:31:39.3300137Z 13894 verbose stack Error: 404 Not Found: har-validator@5.1.2

### Desired functionality
npm install should work on my cloud CI/CD servers

### Mention any other details that might be useful
I added the recommended dependencies for Material Design to a basic Angular 7 project. Once I did my CI build started failing on the NPM install step. It appears there is a dependency to har-validator version 5.1.2. It would be good if the dependency could be updated to 5.1.3 which still exists.

**Comment by clydin** [comment]
As described this is due to the project's lock file and not the CLI.  `har-validator` is a transitive dependency of the CLI originating from a direct dependency of `request`.  `request` has `"har-validator": "~5.1.0"` for its dependency definition which includes `5.1.3`.
