### ISSUE TITLE
deploying with libraries linked to cdn in system-config.js

### ISSUE THREAD

**Issue by sathishvj** [angular/angular-cli#1310]
The default system-config.js file sets the path of libraries to the vendor directories.  And that is in the section marked " \* Everything underneath this line is managed by the CLI.".  So I guess we are not supposed to edit that.

At the time of deployment how do we link to cdn libraries?  Is there a prescribed way of doing this?

**Comment by filipesilva** [comment]
#1455 changed the build drastically and there is no system-config anymore.

There's no way of doing this yet so I'm leaving the issue open as a feature request.

**Comment by filipesilva** [comment]
We've talked about this feature internally and it's not something we're looking at adding currently. There's a lot of pitfalls with versioning and transient dependencies.
