### ISSUE TITLE
Typings mismatch error after update and running ng new

### ISSUE THREAD

**Issue by keithmichelson** [angular/angular-cli#1311]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
angular-cli: 1.0.0-beta.9
node: 4.0.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Just did an update using the 3 steps under Global Packets, then created a new probject using ng new

4. The log given by the failure. Normally this include a stack trace and some
   more information.
test-cli@0.0.0 postinstall: `typings install`
Exit status 1

Then when running ng serve
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (/Users/keith/Documents/test-cli/node_modules/angular-cli/node_modules/broccoli-sane-watcher/index.js:90:11)

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by keithmichelson** [comment]
Didn't see #1092  but it is still happening.
Did this as well and it worked:
npm run postinstall

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455. On the next release we are not using `typings` anymore.

In your case the problem happened because we updated typings versions.
