### ISSUE TITLE
ERROR in Internal Error: The structure of the program changed during codegen.

### ISSUE THREAD

**Issue by agranmo** [angular/angular-cli#13110]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### The log given by the failure
ng build --prod

Date: 2018-12-01T15:56:44.438Z
Hash: 49ff8f3c3c3e9e0730b8
Time: 5876ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.273f8c61146d671f6103.css (styles) 16.5 kB [initial] [rendered]

ERROR in Internal Error: The structure of the program changed during codegen.
PS C:\code\palko> ng build --prod --verbose
Hash: 49ff8f3c3c3e9e0730b8
Version: webpack 4.23.1
Time: 6823ms
Built at: 2018-12-01 15:57:01
                            Asset       Size  Chunks  Chunk Names
             3rdpartylicenses.txt    1 bytes
     main.9868d9b237c3a48c54da.js  128 bytes       1  main
polyfills.85f47f0bf59079cbc23a.js  130 bytes       2  polyfills
  runtime.ec2944dd8b20ec099bf3.js   1.41 KiB       0  runtime
  styles.273f8c61146d671f6103.css   16.5 KiB       3  styles
Entrypoint main = runtime.ec2944dd8b20ec099bf3.js main.9868d9b237c3a48c54da.js
Entrypoint polyfills = runtime.ec2944dd8b20ec099bf3.js polyfills.85f47f0bf59079cbc23a.js
Entrypoint styles = runtime.ec2944dd8b20ec099bf3.js styles.273f8c61146d671f6103.css
chunk    {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 0 bytes ={1}= ={2}= ={3}= [entry] [rendered]
chunk    {1} main.9868d9b237c3a48c54da.js (main) 28 bytes ={0}= [initial] [rendered]
 [0] multi ./src/main.ts 28 bytes {1} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     multi entry
 [zUnb] ./src/main.ts 0 bytes {1} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\code\palko\src\main.ts [0] multi ./src/main.ts main[0]
chunk    {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 28 bytes ={0}= [initial] [rendered]
 [1] multi ./src/polyfills.ts 28 bytes {2} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     multi entry
 [hN/g] ./src/polyfills.ts 0 bytes {2} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\code\palko\src\polyfills.ts [1] multi ./src/polyfills.ts polyfills[0]
chunk    {3} styles.273f8c61146d671f6103.css (styles) 18 KiB ={0}= [initial] [rendered]
 [2] multi ./src/theme/variables.scss ./src/global.scss 40 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     multi entry
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss 2.52 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [fFqt] ./src/theme/variables.scss
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss 15.3 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [8oQk] ./src/global.scss
 [8oQk] ./src/global.scss 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\code\palko\src\global.scss [2] multi ./src/theme/variables.scss ./src/global.scss styles[1]
 [fFqt] ./src/theme/variables.scss 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\code\palko\src\theme\variables.scss [2] multi ./src/theme/variables.scss ./src/global.scss styles[0]

ERROR in Internal Error: The structure of the program changed during codegen.
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!src/global.scss:
                   Asset     Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1 bytes
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 15.4 KiB [entry] [rendered]
     [gDV9] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/global.scss 15.4 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\code\palko\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\code\palko\node_modules\postcss-loader\src\index.js??extracted!C:\code\palko\node_modules\sass-loader\lib\loader.js??ref--14-3!C:\code\palko\src\global.scss  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!src/theme/variables.scss:
                   Asset     Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1 bytes
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 2.64 KiB [entry] [rendered]
     [2LIy] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/theme/variables.scss 2.64 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\code\palko\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\code\palko\node_modules\postcss-loader\src\index.js??extracted!C:\code\palko\node_modules\sass-loader\lib\loader.js??ref--14-3!C:\code\palko\src\theme\variables.scss  mini-css-extract-plugin

ERROR in Internal Error: The structure of the program changed during codegen.

**Comment by alan-agius4** [comment]
Closing as it doesn’t follow the template.
