### ISSUE TITLE
Fonts defined in shared directly doesn't get loaded due to 404

### ISSUE THREAD

**Issue by zlepper** [angular/angular-cli#13118]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
C:\dev\work\test\scss-import-issue>node --version
v8.9.4

C:\dev\work\test\scss-import-issue>npm --version
6.4.1

C:\dev\work\test\scss-import-issue>ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.0
Node: 8.9.4
OS: win32 x64
Angular: 7.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.0
@angular-devkit/build-angular     0.11.0
@angular-devkit/build-optimizer   0.11.0
@angular-devkit/build-webpack     0.11.0
@angular-devkit/core              7.1.0
@angular-devkit/schematics        7.1.0
@angular/cli                      7.1.0
@ngtools/webpack                  7.1.0
@schematics/angular               7.1.0
@schematics/update                0.11.0
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

Windows 10 pro. 
```

### Repro steps
Repro: https://github.com/zlepper/scss-import-issue

run `ng serve`. 
Open a browser to localhost:4200, see that Avenir Next font doesn't load due to 404. 

### The log given by the failure
Nothing unusual in the log. So apparently webpack does find the font-file

### Mention any other details that might be useful
This issue doesn't happen for @angular-devkit/build-angular version 0.8.8.

**Comment by alan-agius4** [comment]
Hi, I have looked at this and it looks that you are using `~/` to resolve the font files. This is equivalent to `/shared-assets`.

When using this pattern, the CLI will won't process the files, and is up to the user to provide it in the `dist`. A way to do this is via the `assets` option in your `angular.json`.

Alternatively the recommended approach is to use relative paths, so instead of `~/` you should use `../`. Remember that in SCSS relative paths are relative to the stylesheet entrypoint and not to the partial scss file.

**Comment by zlepper** [comment]
Neither of those works. If you look in the angular.json file, you will also see the font files being provided as assets. 

Again, this is something that worked previously.

**Comment by alan-agius4** [comment]
@zlepper, I highly doubt this worked in 0.8.8. Usually when using `~/` it will try to resolve in `node_modules` which should result in an exception like `Can't resolve '../node_modules/shared-assets/fonts`
