### ISSUE TITLE
schematics for generating a component with onpush change detection strategy should not generate extra comma

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular-cli#13114]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI v7.1.0

### Repro steps

Generate component and use the `OnPush` change detection strategy

![image](https://user-images.githubusercontent.com/8130692/49349031-b7553f00-f6b9-11e8-8b3e-4530c6d87e36.png)

e.g.:

`ng generate @angular/material:nav sidenav --project=new-app --changeDetection=OnPush`

Extra comma is generated

![image](https://user-images.githubusercontent.com/8130692/49349063-e966a100-f6b9-11e8-9a36-1289f4c8692d.png)

**Comment by klemenoslaj** [comment]
I am pretty sure this is the issue with Angular Material schematics. In fact some minutes ago I opened the same issue on the material repo: https://github.com/angular/material2/issues/14366
