### ISSUE TITLE
wiki page for underscore inclusion needs a fix.

### ISSUE THREAD

**Issue by jjarrell50** [angular/angular-cli#1312]
The wiki page hooking underscore is in-correct for the /// reference it should be
```/// <reference path="../../typings/globals/underscore/index.d.ts" />```
not three sets of dots.

Also needed this for import statement.
```import * as _ from 'underscore'```

**Comment by bpyle0092** [comment]
`/// <reference path="../../typings/globals/underscore/index.d.ts" />`
goes in *.component.ts correct? Same for the import statement? Could you provide an example?

**Comment by istibekesi** [comment]
I think the number of '..' depends on the location from where you are referencing it.

Component in folder src/app/ > 2 set of dots works.
Component in folder src/app/component-name/ > 3 set of dots works.
...

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455. You shouldn't need to do this anymore.
