### ISSUE TITLE
[7.1.1] The new command requires to be run outside of a project, but a project definition was found at ".angular-cli.json".

### ISSUE THREAD

**Issue by davvit** [angular/angular-cli#13138]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
PS C:\xxx\Desktop\New folder> node --version
v10.13.0
PS C:\xxx\Desktop\New folder> npm --version
6.4.1
PS C:\xxx\Desktop\New folder> ng --version
Your global Angular CLI version (7.1.1) is greater than your local
version (7.0.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Angular CLI: 7.0.4
Node: 10.13.0
OS: win32 x64
Angular: 2.4.10
... compiler, compiler-cli, core
```

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.4
@angular-devkit/core         7.0.4
@angular-devkit/schematics   7.0.4
@angular/cdk                 2.0.0-beta.12
@angular/cli                 7.0.4
@angular/tsc-wrapped         0.5.2
@ngtools/json-schema         1.1.0
@ngtools/webpack             1.10.2
@schematics/angular          7.0.4
@schematics/update           0.10.4
rxjs                         6.3.3
typescript                   3.1.6
webpack                      2.2.0
### Repro steps

1) Create empty folder on desktop
2)  ng help   or  ng new testProj

### The log given by the failure

Your global Angular CLI version (7.1.1) is greater than your local
version (7.0.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The new command requires to be run outside of a project, but a project definition was found at ".angular-cli.json".

### Desired functionality

No error; Should initialize a new project.

### Mention any other details that might be useful

Yes i have seen this closed 'fixed' bug report. 
https://github.com/angular/angular-cli/issues/12198

![image](https://user-images.githubusercontent.com/4433698/49541023-220fa180-f897-11e8-9446-994e98ddf5b6.png)

**Comment by alan-agius4** [comment]
Hi can you check is that file is located in your user directory?
