### ISSUE TITLE
Uncommitted file changes found! Please commit all changes before deploying.

### ISSUE THREAD

**Issue by funnytao** [angular/angular-cli#1313]
Hi,

My OS is Win 10 and the version of CLI is: 

angular-cli: 1.0.0-beta.8
node: 4.4.6
os: win32 x64

I am trying to deploy my app on GitHub Page with

`ng github-pages:deploy --message "Optional commit message"`

but I got 

**Uncommitted file changes found! Please commit all changes before deploying.**

I tried to make a new repository and used `git push origin master` but my repository only contained basic files when the project was generated. I mean, all other components I created later were not there. Am I missing something to configure it right? Thank you so much.

**Comment by funnytao** [comment]
I should use `git commit` before deploying. My fault. Thank you.

**Comment by lexcaraig** [comment]
@funnytao how did you do it man

**Comment by funnytao** [comment]
Typically, you just need to follow the basic process like 'git add .', 'git commit' and 'git push origin master', then you should be fine.
