### ISSUE TITLE
ng g component component_name give errors

### ISSUE THREAD

**Issue by rumes** [angular/angular-cli#1314]
1. OS  Linux (Ubuntu 14.04)

2. Versions.
  angular-cli: 1.0.0-beta.9
  node: 5.6.0
  os: linux x64

I'm try to create new component call user.

1. ng g component user

it create the component in app/user/ but give some errors

`import { Component, OnInit } from '@angular/core';

@Component({
  moduleId: module.id,
  selector: 'app-user',
  templateUrl: 'user.component.html',
  styleUrls: ['user.component.css']
})
export class UserComponent implements OnInit {

  constructor() {}

  ngOnInit() {
  }

}
`
errors are 
Cannot find module '@angular/core'.
Cannot compile modules unless the '--module' flag is provided. 
 what is the problem here?.

**Comment by aciccarello** [comment]
I think that's a typescript error. I would investigate

1. Did `@angular/core` get installed by npm
2. Did typescript find the tsconfig file?

**Comment by filipesilva** [comment]
I agree with @aciccarello, this seems like a broken npm install. Try deleting `node_modules` and re-doing `npm install`.
