### ISSUE TITLE
*.bundle.js files no longer being generated, only *.js files instead 

### ISSUE THREAD

**Issue by TheeRFG** [angular/angular-cli#13145]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

`node --version: v8.9.3`
`npm --version: 5.5.1`
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.1
Node: 8.9.3
OS: win32 x64
Angular: 7.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        0.8.8
@ngtools/webpack                  7.0.7
@schematics/angular               7.1.1
@schematics/update                0.8.8
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

```

### Repro steps

trying to run `ng build --configuration=dev` no longer builds `main.bundle.js`, `vendor.bundle.js`, etc and instead builds `main.js`, `vendor.js` etc. 
This was not the case in 7.0.3 and seems new to 7.1.0 I am curious why this changed, if I've done something wrong, or if there's a way to revert this. What is the best course of action to take when moving forward? 

### Desired functionality

I would like to see the the old `main.bundle.js` and `vendor.bundle.js` files back unless there is a good reason their names have changed.

**Comment by alan-agius4** [comment]
Hi, the `.bundle` has been dropped since version `6.0.0`.

The suffixes didn’t provide any real value and where only there because the default webpack config originally used happen to have them (along with a collection of other arbitrary config options). Their only function was to make the file names longer and add confusion as to the difference between a bundle and chunk. The new chunk splitting code also made almost everything a chunk.

**Comment by ToniaDemchuk** [comment]
IMHO this is worth mentioning as breaking changes in migration docs (https://update.angular.io/).
I have spent hours discovering what went wrong with my project 😢
