### ISSUE TITLE
Command: ng coc OR ng diversity  --coc

### ISSUE THREAD

**Issue by willi84** [angular/angular-cli#13148]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Desired functionality

A possibility to print out our current community code of conduct or ressources about diversity & community inside the command line

**Comment by mgechev** [comment]
Hey @willi84, this sounds like a good idea! We should definitely have something like this. I'd suggest to keep just a link to the CoC so that we don't have to maintain two copies of it.

We'll discuss during the triage meeting this week.

**Comment by mgechev** [comment]
@willi84 the code of conduct is very important for us and we're strongly encouraging all community members to follow it. We want to have a direct reference it for everyone before an interaction of someone with the community.

We discussed how introducing the CoC in the CLI would look like but we don't think many people will notice it given the specifics/purpose of the tool.

Again, thanks for the suggestion!
