### ISSUE TITLE
ng test: Debug with VS Code (Unverified Breakpoint)

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#13154]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```
There are similar bugs logged however most of them are outdated(2017) and have been closed

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
```bash
> yarn ng --version
```
Angular CLI: 7.1.2
Node: 11.3.0
Yarn: 1.12.3
OS: darwin x64 (Mojave 10.14.1)
Angular: 7.1.2

### Repro steps
```bash
> npx @angular/cli@7.1.2 new explorer
```
- Launch VS Code and configure tests for debugging (Refer: https://github.com/Microsoft/vscode-recipes/tree/master/Angular-CLI#configure-launchjson-file)
	- ```json
		{
      "name": "ng test",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:9876/debug.html",
      "webRoot": "${workspaceFolder}"
    	},
		```
- `yarn test` and Start debugging from VS Code (opens a separate chrome window)
- <img width="1319" alt="debug" src="https://user-images.githubusercontent.com/13006107/49691523-082dc300-fb12-11e8-8a24-b24fa1251b8e.png">
- Breakpoints are not hit (Unverified breakpoint)

### The log given by the failure
No logs

### Desired functionality
**Breakpoints should be hit inside VSCode**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

That said, you should be able to solve your issue by adding:
```
"sourceMaps": true,
"sourceMapPathOverrides": {
    "./*": "${webRoot}/*",
    "src/*": "${webRoot}/*",
    "*": "*",
    "./~/*": "${webRoot}/node_modules/*",
}
```

**Comment by alan-agius4** [comment]
@prabh-62, I am unable to replicate your problem.
![image](https://user-images.githubusercontent.com/17563226/49799442-37784600-fd45-11e8-8ee2-9d587103b7ab.png)

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by prabh-62** [comment]
Instead of creating a repro, I updated my whole project to latest CLI and angular packages. fiddled with chrome debug extension [trace](https://github.com/Microsoft/vscode-chrome-debug#other-optional-launch-config-fields) and eventually, breakpoints were in sync with the source code.
