### ISSUE TITLE
ng build --prod  > to_single_file

### ISSUE THREAD

**Issue by ORESoftware** [angular/angular-cli#13151]
This is a feature request - I know it's been asked before. In some cases, it really helps for simplicity to have one output file - html, js and css bundled into one.

Is there some cli option we can use to output to a single file? I swear with Angular-CLI version 5, this was possible.

**Comment by ORESoftware** [comment]
Right now, in lieu of this feature, I have this script:

```js
#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const folder = path.resolve(__dirname,'../apps/api-app/dist/api-app');
const one = path.resolve(`${folder}/index.html`);
const two = path.resolve(`${folder}/index-final.html`);

const index1 = fs.readFileSync(one, 'utf8');

const webRoot = 'https://raw.githubusercontent.com/typeaware/tarballs/master/docgen';

const index2 = ['runtime.js','main.js','styles.css','favicon.ico'].reduce((a,b) => {
    return a.replace(`="${b}"`,`="${webRoot}/${b}"`)
}, String(index1));
  

fs.writeFileSync(two, index2);
```

it takes dist/index.html and transforms it to dist/index-final.html, replacing the relative filepaths to www urls.

But I imagine quite a few people would want this feature and implementing the functionality yourself is a little rough.

**Comment by ORESoftware** [comment]
Ok so my answer above was answered by:
https://blog.chai-jay.com/angular-2-use-cdn-path-angular-cli-generated-index-html/

we can do:

```bash
ng build --prod --output-hashing none --deploy-url "$deploy_url"
```

but I am still curious about how to concat into a single file, so will leave the issue open...

**Comment by alan-agius4** [comment]
Hi, there is no such feature to concatenate files into a single one.

Can you explain why you would want to do something like this? While the might have been a recommended approach with HTTP1, with HTTP2 one should levarge the advantages of multiplexing of requests.
