### ISSUE TITLE
configure ng e2e to serve application with npm script

### ISSUE THREAD

**Issue by anthony-telljohann** [angular/angular-cli#13165]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

- node v11.4.0
- npm 6.4.1
- ng 7.2.0-beta.1
- macOS Mojave Version 10.14.1

### Desired functionality

As a developer, I would like to configure `ng e2e` to serve my application with my `npm run serve` script, so that I can configure it with dynamically with environment variables.

Could it make sense to specify this as an alternative to `devServerTarget`?

**Comment by alan-agius4** [comment]
Hi, can you kindly explain a bit further your use case? As you can have various E2E configs based on `configurations` option/flag.

**Comment by atelljohannsmothers** [comment]
When running end-to-end tests on our local servers in our saucelabs grid, we need to set the public host with the $HOSTNAME environment variable. Without it, requests cannot be routed to the local server. In addition, without using the $HOSTNAME environment variable, local development would require each developer to edit their npm scripts and hardcode their own $HOSTNAME. I believe this is not an acceptable solution to impose on our developers.

```
"serve": "cross-env-shell ng serve --host=0.0.0.0 --port=$PORT --publicHost=$HOSTNAME.domain.com"
```

Alternatively, maybe it could make sense to support parsing environment variables in the `angular.json`?

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

You can run protoactor on any url. To do so, you need to remove the `devServerTarget` and provide a `baseUrl`.

See: https://angular.io/cli/e2e
