### ISSUE TITLE
Lazy loading only uses absolute routes

### ISSUE THREAD

**Issue by TheeRFG** [angular/angular-cli#13163]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node: 8.9.3
NPM: 5.5.1
NG:
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.2
Node: 8.9.3
OS: win32 x64
Angular: 7.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        0.8.8
@ngtools/webpack                  7.0.7
@schematics/angular               7.1.2
@schematics/update                0.8.8
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
```

### Repro steps

I have this in my base `tsconfig.json` file
```
{
    "compileOnSave": false,
    "compilerOptions": {
        "outDir": "./dist/out-tsc",
        "baseUrl": "src",
        "sourceMap": true,
        "declaration": false,
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es5",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2016",
            "dom"
        ],
        "noEmit": false,
        "noImplicitAny": false
    }
}
```
I have this in my `tsconfig.app.json`
```
{
    "extends": "../tsconfig.json",
    "compilerOptions": {
        "outDir": "../out-tsc/app",
        "module": "es2015",
        "baseUrl": "src",
        "types": [
            "jquery",
            "node"
        ]
    },
    "exclude": [
        "test.ts",
        "**/*.spec.ts",
        "**/*.mock.ts",
        "node_modules",
        "dist"
    ]
}
```
My modules are lazy loaded like this:
```
{
  path: 'projects',
  loadChildren: './modules/projects/projects-hub.module#ProjectsModule'
},
```
Where projects.routing module looks like this:
```
const appRoutes: Routes = [
    {
        path: '',
        component: ProjectsHubComponent,
        canActivate: [AuthenticatedRedirectGuardService, IframeUnloadGuardService]
    }
];

@NgModule({
    imports: [
        RouterModule.forChild(appRoutes)
    ],
    exports: [
        RouterModule
    ]
})
export class ProjectsHubRoutingModule {
}
```
My `angular.json` build configuration for this app looks like this
```
"projects": {
        "my-angular-app": {
            "root": "",
            "sourceRoot": "src",
            "projectType": "application",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        "outputPath": "build\\application",
                        "index": "src/index.html",
                        "main": "src/main.ts",
                        "tsConfig": "src/tsconfig.app.json",
                        "polyfills": "src/polyfills.ts",
                        "assets": [
                            "src/assets",
                            "src/favicon.ico"
                        ],
                        "styles": [
                            "src/styles.css",
                            "node_modules/quill/dist/quill.core.css",
                            "node_modules/quill/dist/quill.snow.css"
                        ],
                        "scripts": [
                            "node_modules/chart.js/dist/Chart.bundle.min.js",
                            "node_modules/quill/dist/quill.js"
                        ]
                    },
                    "configurations": {
                        "production": {
                            "optimization": true,
                            "outputHashing": "none",
                            "sourceMap": false,
                            "extractCss": false,
                            "namedChunks": false,
                            "aot": true,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                }
                            ]
                        },
                        "dev": {
                            "optimization": true,
                            "outputHashing": "none",
                            "sourceMap": true,
                            "extractCss": false,
                            "namedChunks": true,
                            "aot": false,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "buildOptimizer": false
                        }
                    }
                },
```

We put our files on the server in an `/angular/files/dist` folder, in version 5 this used to lazy load things fine from `/angular/files/dist/modules-projects-projects-hub-module.js` but now, no amount of changing the `baseHref` in my `angular.json` or changing the `baseUrl` in either of my `tsconfig.json` files will get files to load from here. I have tried setting baseHref/baseUrl to `""`, `"./"`, `"src"`, and even `"/"`, just to see, in all files; but no matter what, they all seem to want to load from `/modules-projects-projects-hub-module.js` and produce a 404 for literally every module file. 

### The log given by the failure

`GET http://localhost/modules-projects-projects-hub-module.js net::ERR_ABORTED 404 (Not Found)`

### Desired functionality

I would like to lazy load chunks from the relative path of wherever my angular files are actually located. I feel like this is probably possible (as it was in V5) and I have very likely just misconfigured something, but I can't seem to figure it out and am seeking advice.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by TheeRFG** [comment]
I have recreated a minimal example of our angular configuration for how we are lazy loading in our application for a single module [here](https://github.com/TheeRFG/NG7-Lazy-Loading-Urls). 

I cannot provide an exact replication of our server configuration, but we are using embedded tomcat. Angular files are bootstrapped onto our server's `index.html` as follows
```
<script src="angular/dist/runtime.js" />  
<script src="angular/dist/polyfills.js" />
<script src="angular/dist/styles.js" />
<script src="angular/dist/main.js" />
```
This will get the app itself to bootstrap and initialize at index, but I can confirm that trying to navigate to `/index.html#/lazy` provides the following message `GET http://localhost/4.js net::ERR_ABORTED 404 (Not Found)` which makes sense since it should really be looking for `angular/dist/4.js` instead....

furthermore, the baseUrl in `tsconfig.json is currently set to  `"baseUrl": "src",` as things were when they worked in Ng5, but I also tried `"./"` just for my sanity and noticed no change.

**Comment by clydin** [comment]
The application appears to have been build properly.  This is not an issue with tsconfig but rather the deployment setup.
A web browser will use the base HREF of the page to find relative URLs (within JS and HTML).  The URL of the lazy route is `4.js` so the web browser takes the base HREF of `/` (assuming the default) and tries to request `/4.js` (which is `http://localhost/4.js` if running on localhost).

**Comment by TheeRFG** [comment]
With ng5 this has worked before without needing the base set in index. I thought the purpose of having the options available in ts was so that you didn't have to set it in html.

Also it seems counter to that point that this was working in previous versions of angular, but I'm willing to admit I know literally almost nothing.

**Comment by alan-agius4** [comment]
Hi @TheeRFG,

Let me start by explain a bit `baseUrl` and `baseHref`. They are not related to each other, and they serve different purposes. 

**baseUrl**
This is used during for build time and informs the compiler where to find modules during build time. All module imports with non-relative names are assumed to be relative to the baseUrl.

More information about path mappings can be found here: https://www.typescriptlang.org/docs/handbook/module-resolution.html

**baseHref**
This is the base URL to use for all relative URLs contained within a document. Including `a` tags which might not be something that you want, thus your other option would be to use `deployUrl`

**deployUrl**
This the Base Url where files will be deployed. Files will be fetched from this path.

A full list of build options can be found here: https://angular.io/cli/build

If previously you didn't need to set a `baseHref` nor `deployUrl` and the lazy module were not being loaded from the root of your application. Example `http://localhost/4.js` this was an incorrect behaviour.

**Comment by TheeRFG** [comment]
> Hi @TheeRFG,
> 
> Let me start by explain a bit `baseUrl` and `baseHref`. They are not related to each other, and they serve different purposes.
> 
> **baseUrl**
> This is used during for build time and informs the compiler where to find modules during build time. All module imports with non-relative names are assumed to be relative to the baseUrl.
> 
> More information about path mappings can be found here: https://www.typescriptlang.org/docs/handbook/module-resolution.html
> 
> **baseHref**
> This is the base URL to use for all relative URLs contained within a document. Including `a` tags which might not be something that you want, thus your other option would be to use `deployUrl`
> 
> **deployUrl**
> This the Base Url where files will be deployed. Files will be fetched from this path.
> 
> A full list of build options can be found here: https://angular.io/cli/build
> 
> If previously you didn't need to set a `baseHref` nor `deployUrl` and the lazy module were not being loaded from the root of your application. Example `http://localhost/4.js` this was an incorrect behaviour.

So it sounds like what you're saying is that this was broken before and that what I really want to set is a relative deploy URL (or the static matching path) to fix my issue?

**Comment by clydin** [comment]
This would not have worked with any version of Angular unless the server deployment setup (configuration or file structure) or the deploy URL/base HREF/APP_BASE_HREF options were configured differently.  The CLI configuration file format did change radically for 6.0, so it is quite possible that certain settings were not migrated in the process (there were defects in the initial migration process which have since been corrected).
It is also relevant to note that the on-disk file structure of the hosted files does not necessarily need to match the hosted (i.e., the URL used by a web browser) structure.  The web server's configuration is the defining element for the later.

Overall, the CLI appears to be working as intended.  The underlying issue represented here is one of deployment and usage of the deployment related options.  To answer the final question, using deploy URL or base HREF/APP_BASE_HREF would provide a fix for the situation.

**Comment by TheeRFG** [comment]
HAH! I can confirm that the old angular-cli.json does actually have a deployUrl set to the static location on the server where our files are located. This variable is no longer set in the project after the upgrade. 

I believe while most of the configuration variables were auto-upgraded, the deployUrl was not. I know a few other people have had issues with this, so that may be the real underlying bug here. This makes it look like Angular6 is the problem when really the configuration is just missing. 

I'm currently building this with the deployUrl set. I expect that it will work but I will report back to you when I know for sure. Thank you very much for your information! It was extremely helpful in diagnosing this issue!

**Comment by sudha-malpeddi** [comment]
hi TheeRFG,

I am stuck with the same issue from a week, can you please let me know how did you solve this.
