### ISSUE TITLE
ng build -prod stopped writing out my 3rd party libaries

### ISSUE THREAD

**Issue by tchoulihan** [angular/angular-cli#1316]
> Please provide us with the following information:
> ---------------------------------------------------------------

> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 14.04

> 2. Versions. Please run `ng --version`. 

angular-cli: 1.0.0-beta.9
node: 6.1.0
os: linux x64

> 3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

2 days ago, `ng build -prod` wrote out my third party libraries in `angular-cli-build.js` fine, now, probably with a new angular-cli update, it doesn't. Only a few directores, such as `zone.js`, are in the `dist/vendor` folder.

**Comment by delasteve** [comment]
https://github.com/angular/angular-cli#bundling

They won't be there in a prod build. `ng serve --prod` will bundle all files (besides the polyfills) into a `main.js` file.

If you haven't included the 3rd party libs in the project somewhere, you won't see them in the output.

See https://github.com/delasteve/ng2-issue-1204 for an example of how to include `jquery`. There is also https://github.com/angular/angular-cli/wiki/3rd-party-libs for a guide on 3rd party libs.

**Comment by tchoulihan** [comment]
Hey @delasteve , is there any way I can get angular-cli to write out a html file separately for this one case? Its a javascript library that I need to reference in the `index.html`. The only other alternative I have is to use a CDN, if I can't get it to write out to the dist/ directory.

**Comment by delasteve** [comment]
@tchoulihan I have not needed to do that, so I wouldn't know how to get it to work like you want.

Why do you need to reference it in the `index.html`?

**Comment by tchoulihan** [comment]
Its this library: https://github.com/jackmoore/autosize

I have a bunch of other third party libraries working as intended, but for this one, I've tried everything. The only possible way I could get it to work was by including it in the `index.html`, and then using `declare var autosize: any;` in typescript.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455 - but please tell me if you're still having problems with the next release.

**Comment by tchoulihan** [comment]
Rgr, thanks.
