### ISSUE TITLE
Adding Fonts

### ISSUE THREAD

**Issue by CLOUGH** [angular/angular-cli#1317]
Hi im having a very difficult time trying to add font awesome to my application. The css loads fine and everything but I cant get it to load the fonts. What should I do to load the font in angular 2

**Comment by zackarychapple** [comment]
The paths are relative to your CSS file.  If you put a font directory in your app it should get copied to dist.  Just need to make sure that you update the CSS file.  I'm pretty sure that font-awesome has a variable you can tweak if you're using the SCSS version.

**Comment by serhiiso** [comment]
Question more like about how to copy correctly fonts from node_modules into src folder

**Comment by CLOUGH** [comment]
I didn't had any issues copying over the font from the library with the same folder structure.
The big question now is do I really need to modify the font awesome font location to explicitly state its in the vendor folder. I can imagine this would get very difficult to manage with libraries with multiple relative fonts defined in thier CSS. 
That's my real issue I don't want to have to do that and plus I can't really change the font awesome CSS if I'm pulling it in from npm only of I overload it and that's still don't feel right.

**Comment by filipesilva** [comment]
I'm closing this in favor of https://github.com/angular/angular-cli/issues/1463. 

This issue here was older but in #1455 we drastically changed the build system, and #1463 describes the current situation better.
