### ISSUE TITLE
ERROR WHILE CREATING NEW APP BY 'ng new' 

### ISSUE THREAD

**Issue by oudarjya718** [angular/angular-cli#13170]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node version-v10.14.1, `npm version=6.4.1  
ng --version-  7.1.2
  Windows (10). x64

### Repro steps
ng new app9

### The log given by the failure
 npm ERR! code EINTEGRITY
npm ERR! Verification failed while extracting @angular/compiler@~7.1.0:
npm ERR! Verification failed while extracting @angular/compiler@~7.1.0:
npm ERR! sha512-ua6Wh+c5XzxAeJT6guwAFYnwa1XzJpncppUrceRXIS9VAn9X7ApxRr45DvbVeYwXBb1iNdHWtZFm1koFVQpydA== integrity checksum failed when using sha512: wanted sha512-ua6Wh+c5XzxAeJT6guwAFYnwa1XzJpncppUrceRXIS9VAn9X7ApxRr45DvbVeYwXBb1iNdHWtZFm1koFVQpydA== but got sha512-IlGs/k6c9XH1frbiG5gSO30RQ6/XnB34+70DHDk8GK5sb2gnoS4eGfx8IwFemRRxY6xhWHQ9zxA/LcTEG3cbhg==. (32133 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/oudarjya718/.npm/_logs/2018-12-11T12_06_05_985Z-debug.log
Package install failed, see above. 

### Desired functionality
the app should be created without errors and  should be served on ng serve
![image](https://user-images.githubusercontent.com/36289901/49800001-6f46b400-fd6c-11e8-90c0-71ff28a46eed.png)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by Jatin-8898** [comment]
$ node -v
v10.14.2

$ npm -v
6.5.0

Windows 10 x64

$ ng new project
CREATE project/angular.json (3777 bytes)
CREATE project/package.json (1306 bytes)
CREATE project/README.md (1024 bytes)
CREATE project/tsconfig.json (435 bytes)
CREATE project/tslint.json (2824 bytes)
CREATE project/.editorconfig (246 bytes)
CREATE project/.gitignore (576 bytes)
CREATE project/src/favicon.ico (5430 bytes)
CREATE project/src/index.html (294 bytes)
CREATE project/src/main.ts (372 bytes)
CREATE project/src/polyfills.ts (3234 bytes)
CREATE project/src/test.ts (642 bytes)
CREATE project/src/styles.css (80 bytes)
CREATE project/src/browserslist (388 bytes)
CREATE project/src/karma.conf.js (980 bytes)
CREATE project/src/tsconfig.app.json (166 bytes)
CREATE project/src/tsconfig.spec.json (256 bytes)
CREATE project/src/tslint.json (314 bytes)
CREATE project/src/assets/.gitkeep (0 bytes)
CREATE project/src/environments/environment.prod.ts (51 bytes)
CREATE project/src/environments/environment.ts (662 bytes)
CREATE project/src/app/app.module.ts (314 bytes)
CREATE project/src/app/app.component.html (1120 bytes)
CREATE project/src/app/app.component.spec.ts (981 bytes)
CREATE project/src/app/app.component.ts (211 bytes)
CREATE project/src/app/app.component.css (0 bytes)
CREATE project/e2e/protractor.conf.js (752 bytes)
CREATE project/e2e/tsconfig.e2e.json (213 bytes)
CREATE project/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE project/e2e/src/app.po.ts (204 bytes)
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Unexpected end of JSON input while parsing near '...qwI6B1JYuHRLN2IsLDvkA'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\varly\AppData\Roaming\npm-cache\_logs\2018-12-12T15_53_53_673Z-debug.log
Package install failed, see above.

I tried every solution found on github, stackoverflow but nothing helps.!!!!!
Unable to create a new angular project

**Comment by oudarjya718** [comment]
is this on a subsystem
or entirely linux
