### ISSUE TITLE
Angular CLI version 1.6.8 does not show Angular version

### ISSUE THREAD

**Issue by ksurendra** [angular/angular-cli#13174]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc
```

### Versions

ngular CLI: 1.6.8
Node: 10.5.0
OS: darwin x64

### Repro steps

1.  Install Angular CLI using command `npm install -g @angular/cli@6`
2. Run the commands `ng -v` or 'ng --version` or `ng version`

### Desired functionality

`ng -v` shows Angular version and dependencies. None of the command variants show Angular version.

![screen shot 2018-12-11 at 7 32 53 pm](https://user-images.githubusercontent.com/902972/49841098-db7ce400-fd7b-11e8-942b-cc1fd0b46d5a.png)

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this. However I am closing this issue as Angular CLI 1.X.X is no longer in LTS support. The current LTS version is 6.x.x.

Kindly update to a more recent version of the CLI.

Thanks
