### ISSUE TITLE
Prompts should not accept empty string as a value for required options

### ISSUE THREAD

**Issue by natsid** [angular/angular-cli#13183]
```
- [x] bug report -> please search issues before submitting
- [x] feature request
```

Currently, if an option is marked as required in the schema the schematics CLI will error if no value is passed for that option in non-interactive mode. However, if you are interactive mode and don't provide a value for a required option at its prompt, it is interpreted as having the "value" of the empty string.

You can work around this by adding validation to your schema to not accept the empty string, but that defeats the purpose / convenience of marking options as required.

Prompts should reject the empty string as a value for required options.

**Comment by alan-agius4** [comment]
Not following template.

**Comment by alan-agius4** [comment]
In this case the `minLength` must specify that at least a single character is required, example

```json
"name": {
  "type": "string",
  "description": "The name of the component.",
  "minLength": 1,
  "x-prompt": "What name would you like to use for the component?"
},
```
