### ISSUE TITLE
angular not installing in windows 7 32 bit 

### ISSUE THREAD

**Issue by gourav18** [angular/angular-cli#13187]
C:\Users\surya\angular>npm install -g @angular/cli@6
npm ERR! Unexpected end of JSON input while parsing near '...04ea7c00e2a026e5658
",'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\surya\AppData\Roaming\npm-cache\_logs\2018-12-13T12_27_25_
492Z-debug.log

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
