### ISSUE TITLE
`ng e2e` call `npm run e2e` cause we cant run `npm run e2e` directly

### ISSUE THREAD

**Issue by zixia** [angular/angular-cli#1318]
> ## Please provide us with the following information:
> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>    linux ubuntu 14.04
1. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
       node --version
   And paste the result here.

$ node --version
v5.11.0

$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.8
node: 5.11.0
os: linux x64
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

after run `ng init` to get a fresh new project, I want to run `npm run e2e` to start e2e test.

so I modified packages.json, change `e2e` in `scripts` to:

```
    "e2e": "ng e2e"
```

after that, when I run `npm run e2e`, It never return, hanged.

Then I check the angular-cli source code, found that actully the angular-cli is invoking `npm e2e` script:
https://github.com/angular/angular-cli/blob/master/addon/ng2/tasks/e2e.ts#L12

that means, I must keep the script.e2e in package.json to invoke protractor, and must without any parameters.

the above all, cause that if I use `ng e2e` command, then I cant run `npm run e2e` directly.
if I use `npm run e2e`(by change the package.json), then when I run `ng e2e` there will be an error.

can we change the design, to let user have a way to run them both at the same time?

for example, change the ng2/tasks/e2e.ts, to call `npm run protractor` instead of `npm run e2e`, then we can change script.e2e to  `ng e2e`.

I think that will be better.

**Comment by filipesilva** [comment]
This would be nice, I agree. Would you be open to making a PR?

**Comment by zixia** [comment]
great, I'd like to make this PR.

will start working on it this week end.

**Comment by catull** [comment]
@zixia Did you find a solution ? Is the problem still there ?

**Comment by zixia** [comment]
@catull I still short of time to make this PR yet, hope I can do this before March. 

For a simple solution: I think you can avoid this problem by not modifying `script.e2e` in package.json

**Comment by filipesilva** [comment]
I'm closing this issue as it is mostly a question of script naming in num scripts and at this point we cannot reasonably change the name without breaking a lot of projects.
