### ISSUE TITLE
distribution folder marked as "ignored" in the solution

### ISSUE THREAD

**Issue by GuitarHero1969** [angular/angular-cli#13180]
I have an asp.net core 2.1 web api with the Angular SPA template used to created a ClientApp within the solution.

But in VS 2017 solution explorer, the dist folder under ClientApp is marked as ignore.
This doesn't look good, especially when I come to publish the project.

Angular version = 7.1.2
Incidentally, I'm not sure if this could be related to the issue, but I just created a new angular app using the CLI in a command prompt and ran into the following problem:

Um6ETfVp09E70==) seems to be corrupted. Trying one more time

then a huge list of "no such file" ....\Source\Repos\ngTest\node_modules\.staging\...
and and several modules after "staging" including isstream, jasmine-core, etc, etc,

Other wise the project structure in windows explorer appears to be normal.

**Comment by alan-agius4** [comment]
Closing as it doesn’t follow template.

**Comment by GuitarHero1969** [comment]
What "template" ??

**Comment by alan-agius4** [comment]
When you open an issue, there is a predefined template, which needs to be filled up.

Thanks.
