### ISSUE TITLE
@angular/cli not installing properly on VM's with Windows Server 2008

### ISSUE THREAD

**Issue by arunkkumar2207j** [angular/angular-cli#13185]
We have tried for days to install angular on Windows server VM's using following step

Install Node
npm install @angular/cli
ng new App (This is where the problem exist and i am not able to move ahead)

We also wanted to integrate Angular 6 in .Net projects

Can anybody help us.

Arun

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
