### ISSUE TITLE
Does not support individual feature module deployment

### ISSUE THREAD

**Issue by nitink85** [angular/angular-cli#13190]
### Bug Report or Feature Request (mark with an x)

```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
```

### Versions
node --version = 8.11.3
npm --version = 5.6.0
ng --version = 6.1.1
macOS - High Sierra 10.13.4
Windows 8 and 10

### Repro steps

1. Create 2 feature modules.
2. Create an App.
3. Load 1 feature module statically and other one lazily.
4. Build and deploy the **dist** of app.

### Desired functionality

1. If we found a bug in 1 feature module which is lazily loaded. We want to deploy just this feature module file, instead of building and deploying entire **app**.
2. If we found a bug in 1 feature module which is statically loaded. We want to deploy just this feature module file, instead of building and deploying entire **app**.

### Mention any other details that might be useful

**Thoughts/Concerns on Desired 1**

I still have a workaround to fulfill Desired 1 by following below steps:
1. Build the app with latest package of feature module.
2. Then pick the lazily-loaded-feature-module-ngfactory.js from dist and deploy it to **app** folder residing on server.
3. Does CLI provide any way to fulfill this desire, without any workaround.

**Thoughts/Concerns on Desired 2**

1. All static modules got packed under main.js
2. Our ask is just to deploy 1 feature module where we made changes.
3. Is there a way to create chunks for statically loaded module in prod mode? If we do so, would it have any negative impact?

**Comment by alan-agius4** [comment]
This request is similar to https://github.com/angular/angular-cli/issues/12272 and thus I am going to close this in favor of it.

That said, when having commonChunks enabled changing a lazy loaded module might have an effect on the a common chunk, if a dependency is introduced in a lazy loaded module.
