### ISSUE TITLE
Sass not watched

### ISSUE THREAD

**Issue by agalazis** [angular/angular-cli#1319]
1. Centos 6

2. angular-cli: 0.0.39
node: 5.4.1
os: linux x64

3. App crated with angular cli.
Steps:

- Run npm start or ng-server with broken sass if there is an issue it won't compile getting the error in the output .
- Do a change in your sass file that is  still leaving it broken .  
- The change is taken in to account, everything is compiled except sass and you get a success message.
- exit the server and run ng server. Sass will get compiled and you get the error message you should get if sass was watched properly

**Comment by neilhem** [comment]
Please update to the latest version (`npm i -D angular-cli@1.0.0-beta.9 && npm i -g angular-cli@1.0.0-beta.9)

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.

**Comment by filipesilva** [comment]
To elaborate though, @neilhem is correct in asking you to update as we don't really support older versions and yours is pretty old.
