### ISSUE TITLE
No documentation for SPA template in asp.net core 2.1 using IdentityDbContext

### ISSUE THREAD

**Issue by GuitarHero1969** [angular/angular-cli#13199]
How do I get my landing page to be the register or login as opposed to the index page under ClientApp.
I have followed the docs.microsoft.com tutorial, but there is no tutorial out there on how to configure the start page:

The following two links fail to mention the how, why, what of the *.cshtml (razor view) stuff and the ClientApp integration.  

How do you configure such a project when you want sign-up identity, but the start page is still the router outlet stuff in the angular ClientApp ??

https://docs.microsoft.com/en-us/aspnet/core/client-side/spa/angular?view=aspnetcore-2.2&tabs=visual-studio
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=visual-studio

There is a massive missing piece somewhere out there - please help me find it !!!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
