### ISSUE TITLE
Lazy loading (loadChildren) modules with module mapping

### ISSUE THREAD

**Issue by wescoder** [angular/angular-cli#13191]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
➜ node --version 
v10.11.0
➜ npm --version
6.4.1
➜ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.2
Node: 10.11.0
OS: linux x64
Angular: 7.1.2
... cli, common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.2
@angular-devkit/build-angular     0.11.2
@angular-devkit/build-optimizer   0.11.2
@angular-devkit/build-webpack     0.11.2
@angular-devkit/core              7.1.2
@angular-devkit/schematics        7.1.2
@ngtools/webpack                  7.1.2
@schematics/angular               7.1.2
@schematics/update                0.11.2
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

### Repro steps

Clone the sample repo: [https://github.com/wescoder/angular-lazy-modules](https://github.com/wescoder/angular-lazy-modules/tree/feature/scaffold) [feature/scaffold branch].
Run with `npm start`.
See the console logs.

### The log given by the failure

```
ERROR Error: Uncaught (in promise): Error: Cannot find module '@guni-pages/feed/feed.module'
Error: Cannot find module '@guni-pages/feed/feed.module'
```

### Desired functionality

Using module mapping with typescript should map correctly in lazy loaded modules on angular.

### Mention any other details that might be useful

[https://github.com/wescoder/angular-lazy-modules](https://github.com/wescoder/angular-lazy-modules/tree/feature/scaffold)

**Comment by mgechev** [comment]
Hey @wescoder thanks for the example repo. It doesn't look like an Angular CLI project and it doesn't have `npm start` script in `package.json`. Do you have a CLI example where we can reproduce the problem?

**Comment by wescoder** [comment]
@mgechev sorry, I hadn't made the push with the addition of angular to the project.
I have made it now, thanks for the heads up.

**Comment by alan-agius4** [comment]
Hi @wescoder, I had a look at this and the problem seems to be related to your `main.ts` file.

In your `main.ts`, you have the below;
```ts
import { enableProdMode } from '@angular/core'
import { platformBrowser } from '@angular/platform-browser'
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic'

import { AppModule } from '@guni-app/app.module'
import { environment } from '@guni-env/environment'

if (environment.production) {
    enableProdMode()
    platformBrowser().bootstrapModule(AppModule)
        .catch(err => console.log(err))
} else {
    platformBrowserDynamic().bootstrapModule(AppModule)
        .catch(err => console.log(err))
}
```
In the console while building there is a warning that states that lazy loading discovery is disabled
```
WARNING in Lazy routes discovery is not enabled. Because there is neither an entryModule nor a statically analyzable bootstrap code in the main file.
```

The above code is not necessary as the cli will transform and select the appropriate bootstrapping type based on the compilation type.

```ts
import { enableProdMode } from '@angular/core'
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic'

import { AppModule } from '@guni-app/app.module'
import { environment } from '@guni-env/environment'

if (environment.production) {
    enableProdMode()
}

platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.log(err))
```

**Comment by wescoder** [comment]
This makes a lot of sense.
I've managed to fix this while improving my "env vars" management and happened that I removed the unnecessary condition but didn't understood that this is what caused the issue.

Thanks a lot for your time.
I'm updating my sample repo to include the fix, for future reference for anyone with similar problems.

**Comment by SilvioAmaral** [comment]
Would it be possible to bootstrap a fallback module on the .catch of the platformBrowserDynamic().bootstrapModule(), without running into this issue ?

eg:
platformBrowserDynamic().bootstrapModule(ModuleX).catch(()=>{
  return platformBrowserDynamic().bootstrapModule(ModuleY);
})

I can make the [app ](https://angular-example-module-error-silvio.stackblitz.io/)work , however when compiling I get the error on this thread and the dynamic module resolution won't work (from experience in another app, not this example )

Documentation is unhelpful and still trying to work my way on source code, so  Im reaching out for help. Any ideas are welcome
