### ISSUE TITLE
Karma configuration - Use PhantomJS by default

### ISSUE THREAD

**Issue by Gillespie59** [angular/angular-cli#132]
When we execute for the very first time, Karma is configured to use the Chrome driver. But if the user to not have the right binaries, he will receive an error.

Could you configure Karma to use by default PhantomJS ?

**Comment by jelbourn** [comment]
In the past ng-material tried to use PhantomJS for test running and have had nothing but problems with it, especially with the current incomplete state of v2.

**Comment by Gillespie59** [comment]
How did not know about that.

**Comment by hansl** [comment]
As Jeremy said, there are many problems with Phantom. Closing this; you can install PhantomJS yourself if you want to go down that route.

**Comment by elvirdolic** [comment]
@hansl is this currently possible with changing karma.conf and without touching angular-cli stuff? We have the same problem that our VSTS Hosted Build agent doesn't have chrome installed we need an alternative to run ng test

**Comment by MathieuNls** [comment]
@elvirdolic Did you managed to find an alternative?

**Comment by elvirdolic** [comment]
Yes we are using phantom instead of chrome launcher. You can change it easily in karma.conf
