### ISSUE TITLE
Not Downloading the latest version

### ISSUE THREAD

**Issue by iaakash** [angular/angular-cli#1320]
> ## Please provide us with the following information:
> 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
1. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
       node --version
   And paste the result here.
2. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
3. The log given by the failure. Normally this include a stack trace and some
   more information.
4. Mention any other details that might be useful.
   
   > ---
   > 
   > > Thanks! We'll be in touch soon.

**Comment by iaakash** [comment]
angular-cli: 1.0.0-beta.9
node: 6.3.0
os: darwin x64

**Comment by gelidus** [comment]
To describe this issue, this just happened to me after uninstalling the cli:
```
[gelidus@gelidus ~]$ sudo npm i -g angular-cli@1.0.0-beta.9/usr/lib
└── (empty)

npm ERR! Linux 4.4.8-300.fc23.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "i" "-g" "angular-cli@1.0.0-beta.9"
npm ERR! node v5.11.1
npm ERR! npm  v3.9.2
npm ERR! path /usr/lib/node_modules/.staging/abbrev-08897885
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-08897885' -> '/usr/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/abbrev-08897885' -> '/usr/lib/node_modules/angular-cli/node_modules/npm/node_modules/abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gelidus/npm-debug.log
npm ERR! code 1
```

**Comment by zackarychapple** [comment]
make sure you uninstall the previous version first.

**Comment by iaakash** [comment]
1. Uninstalled
2. Ran npm cache clean
3. Installed again

Same Result

**Comment by hansl** [comment]
Closing this as obsolete.
