### ISSUE TITLE
[help] How to use Angular umd reference like ng.core ?

### ISSUE THREAD

**Issue by 100cm** [angular/angular-cli#13205]
In angular 5, i Can use `ng.core,ng.animations`... and any other umd reference after `ng build.` in browser

for example 

![image](https://user-images.githubusercontent.com/12691638/50064226-05eef700-01eb-11e9-83af-f188c5f9b4bc.png)

But after Angular-cli 7 .

I cant do this any more.

![image](https://user-images.githubusercontent.com/12691638/50064252-274fe300-01eb-11e9-9c60-b5a417ecc500.png)

I checked the angular source code and i found they have provided Umd module. but why after cli building i missed the Umd reference ?

**Comment by mgechev** [comment]
The issue tracker in this repository is reserved for feature requests and bug reports. For support requests, I'd recommend you to check the correct channels:
- StackOverflow with tag Angular and Angular CLI
- Angular's gitter channel

**Comment by mgechev** [comment]
Looks like that when the webpack runtime bootstraps the module, it passes an empty object as the value of `exports`.

Although this seems intentional and interacting with global properties is strongly discouraged, let's reopen the issue in case @hansl, @filipesilva, @alan-agius4 have something to add.

**Comment by 100cm** [comment]
If i  separate import the `core.umd.js` , it could work. So I can't judge whether this is a cli's Bug or some webpack configuration lead to this .

![image](https://user-images.githubusercontent.com/12691638/50066175-3471cf80-01f5-11e9-86dd-df02bafd6b5a.png)

I check the building result. and found this. 

@mgechev Thanks for your patient again.

**Comment by alan-agius4** [comment]
The whole concept behind webpack is to allow more modular development. This means writing isolated modules that are well contained and do not rely on hidden dependencies (eg. globals).

While there are ways to access globals in a webpack build, you’d need to customize your config which will take you off the supported route. See: https://webpack.js.org/guides/shimming if you still want to pursue this.

As @mgechev mentioned, it is highly discouraged interacting with global references.

**Comment by 100cm** [comment]
@alan-agius4 Thanks a lot ! i will think about it.
