### ISSUE TITLE
favicon href would work with deploy-url option

### ISSUE THREAD

**Issue by the1mills** [angular/angular-cli#13201]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
```

### Versions
On Ubuntu, Angular CLI version is 7.1.2

I have this shell script:

```bash
#!/usr/bin/env bash
set -e;
deploy_url="localhost:9080/"
cd "$(dirname $(dirname "$0"))"
cd apps/api-app
ng build --watch --output-hashing none --deploy-url "$deploy_url"
```

It generates an index.html like so:

```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ApiApp</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.js"></script>

</head>
<body>

<app-root></app-root>
<script type="text/javascript" src="localhost:9080/runtime.js"></script>
<script type="text/javascript" src="localhost:9080/polyfills.js"></script>
<script type="text/javascript" src="localhost:9080/styles.js"></script>
<script type="text/javascript" src="localhost:9080/vendor.js"></script>
<script type="text/javascript" src="localhost:9080/main.js"></script>
</body>
</html>


```

But what about the href for favicon?

```html
 <link rel="icon" type="image/x-icon" href="favicon.ico">
```

how can I get that to reference localhost:9080?

in other words, I would like it to have generated:

```html
  <link rel="icon" type="image/x-icon" href="localhost:9080/favicon.ico">
```

**Comment by clydin** [comment]
This is intended behavior.  While the script elements do indeed contain the deploy URL information, the elements are actually fully generated at build time and do not exist within the `index.html` file beforehand.  The link element for the favicon, however, is a static pre-existing element within the file.  Much like any other custom content within the file, it is not modified as there is no definitive way to know the intentions of the developer in regards to which URLs within the file should and should not be modified.

Also of note is that setting the HTML base HREF is in nearly all cases a better alternative than the deploy URL option.  The HTML base HREF is leveraged by the browser to augment all relative URLs within the page; and without the need for the build system to manually modify every URL.  There is also no need to use either option if the files referenced by the relative URLs are deployed alongside the  index HTML.

**Comment by duncandean** [comment]
This is still having an impact in our case, where we use a deploy URL to to point to a transient path in our CDN (changes with each deploy) where all web assets are stored. Only index.html is being served from the actual  app domain, hence all favicons 404. They're definitely something we'd prefer to serve from the CDN.
