### ISSUE TITLE
ENOTSUP: operation not supported on socket, mkdir '/home/foo'ENOTSUP: operation not supported on socket, mkdir '/home/foo'

### ISSUE THREAD

**Issue by btoorenburg** [angular/angular-cli#13200]
I have updated my node, npm and @angular/cli on OSx Mojave.
Now when creating a new Angular app I get this message: 
ENOTSUP: operation not supported on socket, mkdir '/home/foo'

I can't figure it out what the problem seems to be. 

node version: 10.14.2
npm  version: 6.4.1

Angular CLI: 7.1.3
Node: 10.14.2
OS: darwin x64
Angular:
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics   7.1.3
@schematics/angular               7.1.3
@schematics/update              0.11.3
rxjs                                            6.3.3
typescript                                  3.1.6

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by btoorenburg** [comment]
I will do that. 
Thanks for your reply. 
Kind regards Bas
