### ISSUE TITLE
Non-module TS files with only interfaces are not rebuilt on forked type checker

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#13209]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps
- `ng new repro-app && cd repro-app &&  ng serve`
- create `src/my-interfaces.ts` with `interface MyInterface { val: string; }`. No rebuild is triggered.
- add `const mi: MyInterface = {val: 'string'};` to `src/main.ts`. Rebuild is triggered and finishes successfully.
- change `MyInterface` declaration to `interface MyInterface { val: number; }`. No rebuild is triggered.
- change `mi` declaration to `const mi: MyInterface = {val: 1};`. Rebuild is triggered and finishes successfully. Moments later, forked type checker errors out with:
```
ERROR in src/main.ts(15,26): error TS2322: Type 'number' is not assignable to type 'string'.
```

**Comment by alan-agius4** [comment]
Hi @filipesilva, I cannot seem to reproduce this.

Kindly see: https://github.com/angular/angular-cli/pull/13980

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
