### ISSUE TITLE
@ngtools/webpack removes webpack comments

### ISSUE THREAD

**Issue by edusperoni** [angular/angular-cli#13206]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Versions
```
"@ngtools/webpack": "^7.1.2"
```

### Repro steps

Declare this class:
```
export class Test {
    static TESTVAR: string = /* @bar */ "mystring" /* @/bar */;
}
```
and run it through `@ngtools/webpack`. It outputs this:

```
var Test = /** @class */ (function () {
    function Test() {
    }
    Test.TESTVAR = "mystring" /* @/bar */;
}());
```

### Desired functionality

It should not eat the comment, so it'd still be processable by other loaders. Like this:
```
var Test = /** @class */ (function () {
    function Test() {
    }
    Test.TESTVAR = /* @bar */ "mystring" /* @/bar */;
}
```

**Comment by alan-agius4** [comment]
Hi, this doesn't seem to be caused by `@ngtool/webpack`. The same output is consistent even when using directly the TypeScript compiler.
