### ISSUE TITLE
Importing raw html file content

### ISSUE THREAD

**Issue by distributev** [angular/angular-cli#13211]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node 8.11.4
npm 6.4.1
n.g 7.0

### The log given by the failure

error TS2307: Cannot find module './menu.html'

### Desired functionality
In a previous angular.js 1.x app I could do

import menuTemplate from './menu.html';

by configuring myself rollup-plugin-html plugin for rollup.js

If I try to do the same in an angular cli app the result is that I cannot compile.

I know that a similar thing can be done using raw-loader / html-loader plugins from webpack.

But I know that webpack is "bundled and hidden" inside angular 7 so I am not sure if raw-loader is already provided by angular 7 (or angular cli) and, if yes, how to use it? If raw-loader is not provided by angular 7 cli how it can be "activated" using a minimum configuration?

**Comment by mgechev** [comment]
Hey @distributev, this is more of a feature request. We currently don't have support for importing html files and it's out of the scope of the project. I'd recommend you to look at `ngx-build-plus`or `@angular-builders/custom-webpack`. Hope this helps!
