### ISSUE TITLE
Building with --prod fails when same component is part of declarations of two modules

### ISSUE THREAD

**Issue by varadero** [angular/angular-cli#13215]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Versions:
Node: v10.9.0
npm: 6.4.1
Angular CLI version:
Angular CLI: 7.1.3
Node: 10.9.0
OS: win32 x64
Angular: 7.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### Repro steps

- ```ng new build-paths```
- ```Create new file next to app.module.ts, name it app2.module.ts and copy/paste the content of app.module.ts into it```
- ```ng build --prod```

What happens is that ```app2.module.ts``` is not imported/referenced in any other file, but it is still somehow processed by the build system which complains about AppComponent being part of 2 modules' ```declarations``` array.

### The log given by the failure

ERROR in : Type AppComponent in C:/dev/prod-build-error/src/app/app.component.ts is part of the declarations of 2 modules: AppModule in C:/dev/prod-build-error/src/app/app.module.ts and AppModule in C:/dev/prod-build-error/src/app/app2.module.ts! Please consider moving AppComponent in C:/dev/prod-build-error/src/app/app.component.ts to a higher module that imports AppModule in C:/dev/prod-build-error/src/app/app.module.ts and AppModule in C:/dev/prod-build-error/src/app/app2.module.ts. You can also create a new NgModule that exports and includes AppComponent in C:/dev/prod-build-error/src/app/app.component.ts then import that NgModule in AppModule in C:/dev/prod-build-error/src/app/app.module.ts and AppModule in C:/dev/prod-build-error/src/app/app2.module.ts.

### Desired functionality

What would like to see implemented? - I want to point to different start modules which could contain different imports so I can have bundle which contains different modules (most of which shared between possible app build paths)

What is the usecase? - I am trying to have single code base which will differ only with few modules so I get different bundle containing only the modules that are imported. Let's say I have feature-module-1 and feature-module-2 - the former integrates the application with one external system and the latter with another. These two modules can't (or shouldn't) exists in my bundle together.  I want to create different bundles that contain specific integration with these two different external systems so I have a bundle with "feature-module-1" and another one with "feature-module-2" (but avoiding the burden of the router - I don't even use it). I am trying to use Angular CLI projects feature (https://github.com/angular/angular-cli/wiki/stories-multiple-apps).
Sample configuration:
Full list of modules in a sample application:
feature-module-1
feature-module-2
app.module.ts importing feature-module-1 and declaring AppComponent
app2.module.ts importing feature-module-2 and declaring AppComponent

Now I want to create bundles with the following components:
First bundle:
feature-module-1
app.module.ts

Second bundle:
feature-module-2
app2.module.ts

Both bundles will use the shared AppComponent to show content on the screen.

I was hoping Angular CLI "multiple apps" feature (https://github.com/angular/angular-cli/wiki/stories-multiple-apps) is for exactly such scenarios but even if I create new entry like explained in the above link (changing ```architect.build.options.main``` to point to different main.ts / main2.ts that import modules from app.module.ts and app2.module.ts), it still fails with "...is part of the declarations of 2 modules..." error. If I don't specify ```--prod``` in build command line parameters it doesn't fail.

**Comment by mgechev** [comment]
This is the intended behavior. Not a constraint set by the CLI but the Angular compiler.

>What would like to see implemented? - I want to point to different start modules which could contain different imports so I can have bundle which contains different modules (most of which shared between possible app build paths)

Sounds like you may want to take advantage of `loadChildren` that's for a single application.
