### ISSUE TITLE
`ng serve` tsconfig `target` override

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#13216]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

It would be really helpful to have a way to override the tsconfig.json setting, either with a CLI flag or angular.json, so that `ng serve` would output ES2017 while `ng build` uses the configured value of ES5.

The primary reason for this is that stepping through async/await code in the debugger would be way easier than as-is with the ES5 equivalent that TypeScript generates.

### Mention any other details that might be useful

Created this new issue in response to @mgechev closing my original less descriptive one (#6864) with a note to open a new one if the concern were still relevant.

**Comment by alan-agius4** [comment]
You can create 2 tsconfigs, one which is used for `serve` and one which is used for `build`.

**Comment by buu700** [comment]
Ah, that's perfect, thanks!
