### ISSUE TITLE
Changes in LESS files don't trigger live reload.

### ISSUE THREAD

**Issue by EnigmaticCode** [angular/angular-cli#1323]
1. Windows 7

2. angular-cli: 1.0.0-beta.9
node: 6.2.2
os: win32 x64

3. It was generated through the angular CLI app.  Nothing was added except some LESS styling on the app component located at "src/app/app.component.less"

4. NA

5. None

**Comment by gelidus** [comment]
Nor does sass.

**Comment by EnigmaticCode** [comment]
If someone can point me in the right direct,  I might be able to resolve this.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
