### ISSUE TITLE
Proposal: auto increment build budgets

### ISSUE THREAD

**Issue by ben-coble-sp** [angular/angular-cli#13233]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node - 8.12.0
npm - 6.4.1
ng - 7.0.4
macOS - Sierra

### Repro steps

n/a

### The log given by the failure

n/a

### Story

At my job, we have built our own library of shared angular components. We have budget sizes configured in the `angular.json`. As with any active project, the bundle size tends to increase over time. That can cause our automated pull request tests to fail on even a small code change if the change adds enough size to go over the max/min threshold (5% in this example).

```
"budgets": [{
								"type": "bundle",
								"name": "main",
								"baseline": "4020kb",
								"minimumError": "5%",
								"maximumError": "5%"
							},{
								"type": "bundle",
								"name": "styles",
								"baseline": "181kb",
								"minimumError": "5%",
								"maximumError": "5%"
							}]
```

When this happens, the error is easy to identify and remedy (thanks for that!). However, this puts us in a tricky situation. 
> ng build --prod
  
> Date: 2018-12-19T20:13:36.383Z
> Hash: 9ee44adbae1ca37d967f
> Time: 59917ms
> chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
> chunk {1} main.2e3d8a71c52f17d81367.js (main) 1.39 MB [initial] [rendered]
> chunk {2} polyfills.f31412eb35fb595ae0a2.js (polyfills) 147 kB [initial] [rendered]
> chunk {3} styles.c38cc6ec26a52983595d.css (styles) 170 kB [initial] [rendered]
> 
> ERROR in budgets, maximum exceeded for main. Budget 1.4 MB was exceeded by 1.39 kB.

- If we pick a min/max threshold that is **larger**, it increases the chance of introducing a bad import or dependency that dramatically increases the bundle size. 
- If we pick a min/max threshold that is **smaller**, it increases the occurrence of small code changes that push us past our budget.

Budget sizes are known to be a difficult configuration to determine. @jenniferfell has an open item for this topic https://github.com/angular/angular/issues/26106

### Desired functionality

An optional configuration to auto increment your budget sizes would allow developers to set a comfortable max/min amount that their bundle is allowed to change in size. This could be baked into the `build` command or a new command that would ideally be used before `build`. This would allow your budgets to update organically with your project size but large changes (like adding or removing a third party dependency) would require a manual adjustment to the budget baseline.

#### Example use:

An organization has an `angular.json` file with a configuration that allows for auto updating when the difference in bundle size is less than 5%.

```
"budgets": [{
								"type": "bundle",
								"name": "main",
								"baseline": "4020kb",
								"minimumAutoIncrement": "5%",
								"maximumAutoIncrement": "5%",
                                                                   "autoIncrement": "true"
							},{
								"type": "bundle",
								"name": "styles",
								"baseline": "181kb",
								"minimumError": "5%",
								"maximumError": "5%",
                                                                   "autoIncrement": "false" // this would default to false to not break existing usage
							}]
```

User A works and commits their final change. Before pushing a branch up, they run the optional build command (or a new command) `ng build --update-budget` and then commit the updated `angular.json`. When User B reviews the PR, they would notice that the budget baseline value was adjusted to equal the old budget +/- the delta amount of the code change. Budget sizes that exceed the min/max auto increment configuration would still throw an error and maintain their role as a warning to large bundle size changes.

### Mention any other details that might be useful

Incorporating this into version control/continuous integrated environments could be tricky as the Angular-CLI would be modifying versioned files and not the user. 

An individual solution that uses the [Bundle-Budget plugin](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/bundle-budget.ts) to increment the bundle size could be built and added to a company's existing processes.

Figured it was an interesting enough issue to discuss here. Thank you.

**Comment by alan-agius4** [comment]
Hi @ben-coble-sp,

Thanks for this feature request. However, at the moment this is currently not in the Angular CLI roadmap.

Let's re-consider this in the future.

Thanks.
