### ISSUE TITLE
The 'exports is not defined' exception occurs if an application runs in the production environment

### ISSUE THREAD

**Issue by sergey-kanaev** [angular/angular-cli#13232]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Windows 10
npm: 6.4.1
Angular CLI: 7.1.3
Node: 10.13.0
OS: win32 x64
Angular: 7.1.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@angular/cli                      7.1.3
@ngtools/webpack                  7.1.3
@schematics/angular               7.1.3
@schematics/update                0.11.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### Steps to reproduce:
1) Create an empty application using the _'ng new test-app'_ command.
2) Add a **module.js** file with the following content to the **test-app\src** folder:
```
"use strict";
var __extends = "test";
Object.defineProperty(exports, "__esModule", { value: true });

```
3) Update the application **main.ts** file by adding the following code line:
`import './module'`
4) Run the application with the _'ng serve --prod'_ command.

### Current behavior:
```
Uncaught ReferenceError: exports is not defined
    at Module.zUnb (main.7bb79c5c6f13c385da0a.js:1)
    at f (runtime.ec2944dd8b20ec099bf3.js:1)
    at Object.0 (main.7bb79c5c6f13c385da0a.js:1)
    at f (runtime.ec2944dd8b20ec099bf3.js:1)
    at t (runtime.ec2944dd8b20ec099bf3.js:1)
    at Array.r [as push] (runtime.ec2944dd8b20ec099bf3.js:1)
    at main.7bb79c5c6f13c385da0a.js:1
```
 
### Expected behavior:
No errors are thrown.

### Description:
The exception occurs only in production mode. In development mode, the application works correctly.
The issue can be reproduced using the following module built with the typescript compiler (with the _target_ option set to the '_es5_' value):
```
export interface A {}
class ClassA { }
class ClassB extends ClassA { }
```

**Comment by mgechev** [comment]
Hey @sergey-kanaev, this doesn't look like an issue in Angular CLI. You should not rely that the global `exports` object is defined in the browser - it's a commonjs specific.

It's not a good idea to couple the CLI to a module format that you're using in a separate build process.

What was the reason you had to compile the code outside of the CLI? Isn't it possible to use it as part of your application or distribute the assets as an npm module?
