### ISSUE TITLE
how to share node_modules for many projects

### ISSUE THREAD

**Issue by mzamoun** [angular/angular-cli#13251]
Windows10 
Angular7
Cygwin

I want to have this structure of my projects ;
d:/projects/
d:/projects/node_modules/
d:/projects/proj1  with symbolic link node_modules -> d:/projects/node_modules
d:/projects/proj2  with symbolic link node_modules -> d:/projects/node_modules

in d:/projects/proj1
when I run : ng serve 
I have error : You seem to not be depending on "@angular/core" and/or "rxjs". This is an error.

when I run : ng -v 
Error: ENOTDIR: not a directory, scandir 'D:\projects\proj1\node_modules'

Can you Help Me Please ? 

See You Soon .....

**Comment by mgechev** [comment]
Please consider using the issue template.

npm has cache which means that you won't have to download all the modules from the network. Also, having even a small version mismatch between the projects may lead to a completely different directory layout of `node_modules`. I'd strongly discourage that.

What's the use case?
