### ISSUE TITLE
Angular7 compilation fail: npm run hmr

### ISSUE THREAD

**Issue by sukheja-varun** [angular/angular-cli#13252]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

node --version 
v10.12.0

npm --version
6.4.1

ng --version
ngular CLI: 7.0.7
Node: 10.12.0
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

macOS (Mojave)

### Repro steps

1. Follow all the steps as mentioned in the readme of this project.
2. Try to run 'npm run hmr'
you can see  the output as:

> my-memories@0.0.0 hmr /Users/varunsukheja/dev/my-memories
> ng serve --configuration hmr

NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.
The project will still live reload when HMR is enabled,
but to take advantage of HMR additional application code is required'
(not included in an Angular CLI project by default).'
See https://webpack.js.org/guides/hot-module-replacement
for information on working with HMR for Webpack.
To disable this warning use "hmrWarning: false" under "serve" options in "angular.json".
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
                                                                                          
Date: 2018-12-20T20:26:03.215Z
Hash: 8619765c9a6338dfef26
Time: 6067ms
chunk {main} main.js, main.js.map (main) 2.02 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.4 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 31 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 17.9 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 321 kB [initial] [rendered]

ERROR in src/main.ts(16,7): error TS2580: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node`.
src/main.ts(17,18): error TS2580: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node`.

### The log given by the failure

ERROR in src/main.ts(16,7): error TS2580: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node`.
src/main.ts(17,18): error TS2580: Cannot find name 'module'. Do you need to install type definitions for node? Try `npm i @types/node`.

### Desired functionality

To run hmr on my Angular7 project

### Mention any other details that might be useful

even tried `npm i @types/node`, but did not work

**Comment by mgechev** [comment]
Doesn't look like a CLI issue. In `src/tsconfig.app.json` add `"node"` under `types`.

**Comment by alan-agius4** [comment]
Can you kindly share your `main.ts`?

**Comment by sukheja-varun** [comment]
@mgechev Already added, here is my tsconfig.json

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "lib": [
      "es2018",
      "dom"
    ],
    "types": ["node"]
  }
}
`
