### ISSUE TITLE
Generating service generates wrong content

### ISSUE THREAD

**Issue by sinan92** [angular/angular-cli#13267]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

angular-cli@latest and angular-cli@6.2.8

### Repro steps

ng generate service services/wagon

### The log given by the failure

The generated file wagon.service.ts:

{
  "_args": [
    [
      "babel-loader@8.0.4",
      "C:\\Users\\Sinan\\Development\\WebAndMobile\\BulletinBoard\\react-frontend"
  

wagon.service.spec.ts:

{
  "_args": [
    [
      "prop-types@15.6.2",
      "C:\\Users\\Sinan\\Development\\WebAndMobile\\BulletinBoard\\react-frontend"
    ]
  ],
  "_from": "prop-types@15.6.2",
  "_id": "prop-types@15.6.2",
  "_inBundle": false,
  "_integrity": "sha512-3pboPvLiWD7dkI3qf3KbUe6hKFKa52w+AE0VCqECtf+QHAKgOL37tTaNCnuX1nAAQ4ZhyP+kYVKf8r

### More information

The paths shown in the files are oddly paths to another project not the same one.

**Comment by hansl** [comment]
Hi @sinan92,

It seems that you’re using angular-cli package? That package is deprecated. Could you try with the latest @angular/cli package?

If that doesn’t work, please file a new issue and follow the template.
