### ISSUE TITLE
project type library doesn't allow deleteOutputPath option

### ISSUE THREAD

**Issue by jodytate** [angular/angular-cli#13274]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report 
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Node.js v10.14.2
npm v6.4.1
Angular CLI v7.0.7
OS: Windows 7

### Repro steps

Adding the `deleteOutputPath` option to the `angular.json` produces an error when the project's `projectType` is `library`. The documentation states that the options apply to either "an app or a library," but this doesn't appear to be the case.

### The log given by the failure
```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(deleteOutputPath).
```

### Desired functionality

Desired functionality is that the option be available similarly for both apps and libraries or that the documentation be updated with what options are available per project type.

**Comment by alan-agius4** [comment]
This option is not available for libraries.

This is being tracking in https://github.com/angular/angular/issues/26569
