### ISSUE TITLE
Budgets acting strange

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#13270]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

v8.11.2,
6.4.1,

Angular CLI: 7.1.3
Node: 8.11.2
OS: darwin x64
Angular: 7.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.3
@angular-devkit/build-angular     0.11.3
@angular-devkit/build-optimizer   0.11.3
@angular-devkit/build-webpack     0.11.3
@angular-devkit/core              7.1.3
@angular-devkit/schematics        7.1.3
@angular/cdk                      7.1.1
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.1.1
@angular/pwa                      0.10.7
@ngtools/webpack                  7.1.3
@schematics/angular               7.0.7
@schematics/update                0.11.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### Repro steps

adding to angular.json

```
"budgets": [
                {
                  "type": "bundle",
                  "name": "main",
                  "baseline": "1600kb",
                  "error": "200kb"
                }
              ]
```

### The log given by the failure

build output:
`chunk {5} main.js, main.js.map (main) 385 kB [initial] [rendered]`

Budget error:
`ERROR in budgets, maximum exceeded for main. Budget 1.66 MB was exceeded by 52.1 kB.`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by dima-gusyatiner** [comment]
I also stumbled upon this, when running `ng build --prod --vendor-chunk` in a project originated from [angular-ngrx-material-starter](https://github.com/tomastrajan/angular-ngrx-material-starter).
