### ISSUE TITLE
Is Versioning of Resources supported?

### ISSUE THREAD

**Issue by jagadeshpaladugula** [angular/angular-cli#1327]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by efriandika** [comment]
I have same problem with you @jagadeshpaladugula

**Comment by efriandika** [comment]
Hy @jagadeshpaladugula, you can take a look to #1226 and [this article](https://medium.com/@jonnysamps/cache-busting-with-angular-cli-916db52c8db0#.3hhhwmhyl) will help you

**Comment by filipesilva** [comment]
Feature added in #1455.
