### ISSUE TITLE
Error: Target is not defined for this project.

### ISSUE THREAD

**Issue by sumitparakh** [angular/angular-cli#13288]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

**Node -v** 
v10.14.1

**npm -v**
6.4.1

**ng --version**

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.0.6
Node: 10.14.1
OS: win32 x64
Angular: 7.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.6
@angular-devkit/build-angular      0.10.6
@angular-devkit/build-ng-packagr   0.10.6
@angular-devkit/build-optimizer    0.10.6
@angular-devkit/build-webpack      0.10.6
@angular-devkit/core               7.0.6
@angular-devkit/schematics         7.0.6
@angular/cli                       7.0.6
@angular/pwa                       0.10.6
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.6
@schematics/angular                7.0.6
@schematics/update                 0.10.6
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1

### Repro steps

1) create a serviceworker using generate command with a target.

### The log given by the failure

Target is not defined for this project.

### Mention any other details that might be useful

I have tried configuration apart from default **build**, such as **development** but it is failing and giving Target not defined error. My question is, what are the valid targets of service worker schematic in angular? 

Is there any in-built list of targets we can use to generate service worker ? I don't find any such list in https://angular.io/cli/generate#serviceworker

Plz help.

**Comment by alan-agius4** [comment]
A target is a an architect `builder` that is used to build the application which is defined in your `angular.json`.

Unless you have custom builders, this should be the default.

Example of other targets are `build`, `lint`, `serve` etc

**Comment by sumitparakh** [comment]
> A target is a an architect `builder` that is used to build the application which is defined in your `angular.json`.
> 
> Unless you have custom builders, this should be the default.
> 
> Example of other targets are `build`, `lint`, `serve` etc

Thank you.
