### ISSUE TITLE
Module not found: Error: Can't resolve 'fs' while using new MapboxDraw()

### ISSUE THREAD

**Issue by viswanathamsantosh** [angular/angular-cli#13289]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
node : 8.9.4
npm: 6.5.0
ng: 6.0.0
mapbox-gl-js version: 0.52.0
mapbox-gl-draw version: 1.1.1
ubuntu 18 

### Repro steps

    npm i mapbox-gl && npm i @mapbox/mapbox-gl-draw
    Include styles in angular.json and import mapbox using below lines
    import * as mapboxgl from 'mapbox-gl';
    import * as MapboxDraw from '@mapbox/mapbox-gl-draw';
    Initialise MapboxDraw as
    this.draw = new MapboxDraw();

### The log given by the failure
ERROR in ./node_modules/jsonlint-lines/lib/jsonlint.js
Module not found: Error: Can't resolve 'fs' in '/home/Documents/projects/Project_name/node_modules/jsonlint-lines/lib'
ERROR in ./node_modules/jsonlint-lines/lib/jsonlint.js
Module not found: Error: Can't resolve 'path' in '/home/gaian/Documents/projects/Project_name/node_modules/jsonlint-lines/lib

**Comment by alan-agius4** [comment]
We only support building browser apps, and while building browser apps node native imports modules like `fs` are not available.

You can read more about why we disabled these imports in #9827.
