### ISSUE TITLE
Update autocompletion wiki or remove the link from stories

### ISSUE THREAD

**Issue by kartik-budhiraja** [angular/angular-cli#13282]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x ] doc
```
### Desired functionality
According to the [release notes](https://github.com/angular/angular-cli/releases/tag/v6.0.0) and Issue #11043  , ng completion command has been removed but the wiki stories for cli still have a link to Autocompletion which leads to no where, creating a confusion, either the autcompletion  story page should be displayed specifying that it has been removed, or the **Autocompletion** link should be all together removed from the stories.

**Comment by mgechev** [comment]
https://github.com/angular/angular-cli/pull/13280

**Comment by kartik-budhiraja** [comment]
My bad, Pull Request is already there,closing this issue.
