### ISSUE TITLE
include assets from external library

### ISSUE THREAD

**Issue by midhunmohan** [angular/angular-cli#13285]
### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Angular CLI: 6.1.5
Node: 8.9.1
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.9.2

### Repro steps
include assets from external library via `angular.json`
```
{
"assets": [
              "src/favicon.ico",
              "src/assets",
              { "glob": "**/*.png", "input": "./node_modules/<your-node-module>/<possibly-subfolders>/", "output": "./assets/" }
            ]
}
```

### The log given by the failure
during `ng serve`  unable to access the assets included from one of the node_modules  

### Desired functionality
During `ng build`  assets are copied to the desired location and everything works.
But during `ng serve` how we should refer these assets in our code?

**Comment by alan-agius4** [comment]
Duplicate 
https://github.com/angular/angular-cli/issues/11071

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
