### ISSUE TITLE
i want to build my angular7 project using customize version replacing hash chunk,  how to do that?

### ISSUE THREAD

**Issue by 1248664852** [angular/angular-cli#13281]
i want to build my angular7 project using customize version replacing hash chunk,
 how to do that?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
