### ISSUE TITLE
 environment not defined !!!help me

### ISSUE THREAD

**Issue by alanfernando93** [angular/angular-cli#13294]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [x] help
- [ ] version
- [ ] doc
```
Hi.
I have the following code
``` javascript
import { Component, OnInit } from '@angular/core';
import { mobile } from '../../../../environments/environment';

@Component({
  selector: 'ctk-details-advisory',
  // templateUrl: 'details-advisory.component.mobile.html',
  // templateUrl: 'details-advisory.component.html',
  templateUrl: (mobile) ? 'details-advisory.component.mobile.html' : 'details-advisory.component.html',
  styleUrls: ['./details-advisory.component.scss'],
})
export class DetailsAdvisoryComponent implements OnInit {
// ...
```
this helps me control different html, pc and mobile view.
the problem is that when I want to perform unit tests I get the following error
```
Module not found: Error: Can't resolve ' (mobile) ? 'details-advisory.component.mobile.html' : 'details-advisory.component.html'' in '/home/anonymous/criptoanalisis-0.2/frontend/src/app/pages/advisory/details-advisory'
 @ ./src/app/pages/advisory/details-advisory/details-advisory.component.ts 23:22-121
```
would be of much help some solution to this problem
or another way to control different html
the truth is that I'm going a good time trying to solve the problem
I would greatly appreciate any suggestion

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
