### ISSUE TITLE
How to import a standalone javascript file into the application?

### ISSUE THREAD

**Issue by renefs87** [angular/angular-cli#1329]
Hi,

I am trying to migrate an application from Ember-Cli to Angular-Cli and I am stuck in a very basic thing: How to import a simple javascript library into the application?

On Ember, it is as easy as adding: app.import("vendor/path/to/file"); on the ember-cli-build.js file, but there is no documentation about how to do it on Angular-Cli.

On the docs, all the information about importing 3rd party libraries is about NPM libs... probably because it is easy to do it, but in spite of that, I think there should be some documentation about it.

Can someone tell me what is the proper way to do it?

Thanks.

**Comment by web-dave** [comment]
just add your file to the barrel array in the system-config.ts as a thirdparty barrel.


`const barrels: string[] = [
  // Angular specific barrels.
  '@angular/core',
....
 
  // Thirdparty barrels.
  'yourcode.js',
 
  // App specific barrels.
  'app',
  'app/shared',
  /** @cli-barrel */
];`

Dave.

**Comment by renefs87** [comment]
Thanks for the answer web-dave. And where should I put put the file?

Cheers.

**Comment by web-dave** [comment]
The path to "yourcode.js" is relative to system.config.ts.

Dave.

**Comment by renefs87** [comment]
Great! Thanks!
