### ISSUE TITLE
How to resolve this issue please help i am new in angular

### ISSUE THREAD

**Issue by asdhjkahuid** [angular/angular-cli#13293]
![angularerror](https://user-images.githubusercontent.com/46106657/50400197-d1f77100-07aa-11e9-894e-7c9bace70315.PNG)
![angularversion](https://user-images.githubusercontent.com/46106657/50400198-d2900780-07aa-11e9-8c89-51bf63363ea1.PNG)

Please Help !!!!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
