### ISSUE TITLE
Replace karma-jasmine-html-reporter with karma-material-reporter

### ISSUE THREAD

**Issue by ameerthehacker** [angular/angular-cli#13303]
This is a suggestion to make the default reporter better. 
Replace the karma-jasmine-html reporter with karma-material-reporter as may have following advantages

* Realtime test result reporting
* Good automated test coverage for the package itself
* Built with material design

Please take a look at the reporter [https://github.com/ameerthehacker/karma-material-reporter](https://github.com/ameerthehacker/karma-material-reporter)

**Comment by mgechev** [comment]
Let us not update the default reporter at this point. By changing the karma's configuration file it's easy to switch if people need to. Thanks for the suggestion!
