### ISSUE TITLE
how to make my angular library installs it's dependencies when using it ? 

### ISSUE THREAD

**Issue by ghamry** [angular/angular-cli#13312]
### how to make my angular library installs it's deficiencies when using it ? 

now I've made angular library that depends on ngx bootstrab and others 
i don't want the library consumer to install all the dependencies first , but just install my library and that's it 
so i wonder if that is possible to do

**Comment by vinod90angular** [comment]
Hi
   Is It Possible create multiple projects in a single Angular 6 Application?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
