### ISSUE TITLE
Dependency injection for ngrx in Angular library failing with AOT

### ISSUE THREAD

**Issue by l3ender** [angular/angular-cli#13314]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Windows 10

```
    "@angular/cli": "~7.1.3",
    "@ngrx/effects": "^7.0.0",
    "@ngrx/store": "^7.0.0",
```

Angular version:
```
$ ng v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.1.4
Node: 10.13.0
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.4
@angular-devkit/build-angular      0.11.4
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.11.4
@angular-devkit/build-webpack      0.11.4
@angular-devkit/core               7.1.4
@angular-devkit/schematics         7.1.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.4
@schematics/angular                7.1.4
@schematics/update                 0.11.4
ng-packagr                         4.4.5
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.23.1
```

Node version:
```
$ node -v
v10.13.0
```

NPM version:
```
$ npm -v
6.4.1
```

### Repro steps

Clone https://github.com/l3ender/ngrx-aot. Running app without AOT works (`npm run start`). Running with AOT  (`npm run start:prod`) causes bootstrap to fail. It appears that items (action and service) are not injected into the `Effect`.

### The log given by the failure

Firefox error when viewing application:
> TypeError: this.actions$ is undefined

Chrome error when viewing application:
> Uncaught TypeError: Cannot read property 'pipe' of undefined

### Desired functionality

App behavior would be the same with or without AOT.

**Comment by alan-agius4** [comment]
This is because you are not defining any module within the library, thus there is no dependency injection.

You need to create a module in your library something like this;
```ts
...
import { AgreementsEffects, agreementsReducer } from './engines/agreements/index';

@NgModule({
    imports: [
        HttpClientModule,
        StoreModule.forFeature(
            'feat-name',
            agreementsReducer
        ),
        EffectsModule.forFeature([
            AgreementsEffects,
        ]),
    ]
})
export class LibModule { }
```


And within your application you should use the library module ex;
```
```ts
import { LibModule } from "olb-lib";

@NgModule({
    declarations: [
        AppComponent,
    ],
    imports: [
        LibModule,
        EffectsModule.forRoot([]),
        StoreModule.forRoot({}),
        ...
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

Closing, as this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by l3ender** [comment]
@alan-agius4 Thanks for the detail, that is helpful!

I didn't post on SO as I thought it was related to a bug with how AOT works when it's actually a programmatic issue. Could you offer any advice on how to help approach this in the future so that we don't think it's related to AOT?
