### ISSUE TITLE
Mistake in bootstrap integration

### ISSUE THREAD

**Issue by Konlll** [angular/angular-cli#13317]
Hi!

In the wiki, in the bootstrap integration has an issue.
When I imported "../node_modules/bootstrap/dist/css/bootstrap.min.css", when I restarted the ng App it dropped 404 error, because it has a mistake in "../node_modules/bootstrap/dist/css/bootstrap.min.css". 
The correct solution: "node_modules/bootstrap/dist/css/bootstrap.min.css". This solution isn't dropped 404 error.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this, the wiki is deprecated. 

The new documentation is currently in preview 
https://next.angular.io/guide/using-libraries
