### ISSUE TITLE
Allow Port to be null in angular.json

### ISSUE THREAD

**Issue by arangates** [angular/angular-cli#13326]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality

The scenario I am talking about is this:

ng serve --host local-address

and omitting the port completly

i have edited my hosts file for definition of google.dev

Where local-address is on a private network and not accessibly directly from the web. In the above instance, you only need to add host to ng serve and the port is taken care internally by hosts file & nginx.

In this scenario, running the following

ng serve --host google.dev --disable-host-check

will load the page with default port which is not required and can be omitted as it is taken care internally by nginx.

### Mention any other details that might be useful

i have google.dev pointing to localhost in hosts file
`127.0.0.1   google.dev`

and in my nginx i do proxy pass
```
server {
    listen 80;
    server_name google.dev;
    location / {
        proxy_set_header   Host      $http_host;
        proxy_pass         http://127.0.0.1:4200;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
	proxy_connect_timeout       300;
	proxy_send_timeout          300;
	proxy_read_timeout          300;
	send_timeout                300;
    }
}

```

so this can be fixed if the port allowed null in angular.json

```
"projects": {
    "my-cool-project": {
        ... rest of project config omitted
        "architect": {
            "serve": {
                "options": {
                   "host": "google.dev"
                    "port": null // allowing null would load the url without port
                }
            }
        }
    }
}


```

**Comment by mgechev** [comment]
Thanks for reaching out! Angular CLI does not use nginx and it's out of the scope of the project to interoperate with any server in dev mode. 

If I've completely misunderstood your point, please open a new issue, thank you! :)

**Comment by mgechev** [comment]
Just to clarify, to start a server (including the Angular CLI development one) there must be a port specified, that's how the TCP/IP stack works.

By default we're using 4200, using the `--port` flag you can choose a different one.

**Comment by arangates** [comment]
Absolutely!
I'm aware of HOST and PORT but this is special case where the PORTS are sort of not required.
It could be the issue description is misleading, I'll try to explain it differently:

Angular-App is started using `ng serve` listening on http://localhost:4200
but it is accessed  `http://oursite.local/`
(since we have redirected all traffic from http://localhost:4200 to `http://oursite.local/`)

is it not general practice to get rid of ports in localhost to make development easier?

**Comment by istiti** [comment]
No port doesn’t exist! Noport is port 80 behind browser.
Can’t you specify 80 instead null to access google.dev, you can! This couldn’t use 80 « noport » by default IMHO angular is not apache it should absolutly stay 4200 even if we imagine to allow port:null (4200 by default)

**Comment by arangates** [comment]
i understand the port is mandatory and cannot be negelcted.
but i was thinking if by any chance we could specify alternate address to open when the server is started..

something like configurable url to open in browser after the server is started
`ng serve --host=0.0.0.0 --disable-host-check -o --serveUrl="http://oursite.local/"`
