### ISSUE TITLE
Production build fails due to dependency on license-webpack-plugin 2.0.2

### ISSUE THREAD

**Issue by Isenr** [angular/angular-cli#13329]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

npm: 6.5.0

Angular CLI: 7.1.4
Node: 11.4.0
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@angular/cdk                      7.2.0
@angular/material                 7.2.0
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

### The log given by the failure

node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --verbose
77087ms building modules
4ms finish module graph
2ms sealing
2ms basic dependencies optimization
3ms dependencies optimization
1ms advanced dependencies optimization
2ms after dependencies optimization
10ms optimizing
0ms basic module optimization
2ms module optimization
2ms advanced module optimization
1ms after module optimization
2ms basic chunk optimization
1ms chunk optimization
9ms advanced chunk optimization
2ms after chunk optimization
1ms module and chunk tree optimization
1ms after module and chunk tree optimization
1ms basic chunk modules optimization
1ms chunk modules optimization
0ms advanced chunk modules optimization
1ms after chunk modules optimization
1ms module reviving
3ms module order optimization
1ms advanced module order optimization
2ms before module ids
1ms module ids
2ms module id optimization
3ms chunk reviving
2ms chunk order optimization
2ms before chunk ids
2ms chunk id optimization
1ms after chunk id optimization
16ms hashing
1ms after hashing
1ms module assets processing
14ms chunk assets processing
3ms additional chunk assets processing
5ms additional asset processing
8056ms chunk asset optimization
1ms after chunk asset optimization
1ms asset optimization
1ms after asset optimization
1ms after seal
Hash: 0e685913e6d84f00115a
Version: webpack 4.23.1
Time: 85558ms
Built at: 12/29/2018 9:07:48 PM
                                         Asset       Size   Chunks  Chunk Names
                          3rdpartylicenses.txt   4.96 KiB
      bg-striped-dark.4813bab1fb795d1e6ecc.png  191 bytes
           bg-striped.5478a1d76db57d471919.png  176 bytes
    birthday-balloons.b44495accb3cde0a42db.svg   2.08 KiB
                  16484c3d83c249b1142d.svg    254 KiB
                 26f4f99f07ea0253cf53.woff   45.4 KiB
                  6f78a4484e52457177ab.eot   45.5 KiB
                  cae1b6f83a9165f4c559.ttf   45.4 KiB
                color.c7a33805ffda0d32bd2a.png   10.1 KiB
  fontawesome-webfont.674f50d287a8c48dc19b.eot    162 KiB
  fontawesome-webfont.912ec66d7572ff821749.svg    434 KiB
fontawesome-webfont.af7ae505a9eed503f8b8.woff2   75.4 KiB
  fontawesome-webfont.b06871f281fee6b241d6.ttf    162 KiB
 fontawesome-webfont.fee66e712a8a08eef580.woff   95.7 KiB
                  hue.0614c27197fc3ce572e1.png  293 bytes
                 line.567f57385ea3dde2c9ae.gif   12.8 KiB
              loading.8732a6660b528fadfaeb.gif   9.21 KiB
                  main.9868d9b237c3a48c54da.js  128 bytes        1  main
       password-meter.64ca45e5df0f02614317.png   1.53 KiB
             polyfills.85f47f0bf59079cbc23a.js  130 bytes        2  polyfills
               runtime.ec2944dd8b20ec099bf3.js   1.41 KiB        0  runtime
               scripts.76160f3207e5866c6d62.js   82.7 KiB  scripts  scripts
               styles.4ef27c5011e0518e09d6.css    916 KiB        3  styles
Entrypoint main = runtime.ec2944dd8b20ec099bf3.js main.9868d9b237c3a48c54da.js
Entrypoint polyfills = runtime.ec2944dd8b20ec099bf3.js polyfills.85f47f0bf59079cbc23a.js
Entrypoint styles = runtime.ec2944dd8b20ec099bf3.js styles.4ef27c5011e0518e09d6.css
Entrypoint scripts = scripts.76160f3207e5866c6d62.js
chunk    {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 0 bytes ={1}= ={2}= ={3}= [entry] [rendered]
chunk    {1} main.9868d9b237c3a48c54da.js (main) 28 bytes ={0}= [initial] [rendered]
 [0] multi ./src/main.ts 28 bytes {1} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     multi entry
 [zUnb] ./src/main.ts 0 bytes {1} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\src\main.ts [0] multi ./src/main.ts main[0]
chunk    {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 28 bytes ={0}= [initial] [rendered]
 [1] multi ./src/polyfills.ts 28 bytes {2} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     multi entry
 [hN/g] ./src/polyfills.ts 0 bytes {2} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\src\polyfills.ts [1] multi ./src/polyfills.ts polyfills[0]
chunk    {3} styles.4ef27c5011e0518e09d6.css (styles) 1.6 MiB ={0}= [initial] [rendered]
 [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css 124 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     multi entry
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss 2.86 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [+EN/] ./src/styles.scss
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/scss/common.scss 489 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [xarx] ./src/scss/common.scss
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/font-awesome/scss/font-awesome.scss 33.9 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [hRJ5] ./node_modules/font-awesome/scss/font-awesome.scss
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/primeng/resources/primeng.css 102 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [NIap] ./node_modules/primeng/resources/primeng.css
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/primeng/resources/themes/bootstrap/theme.css 57.3 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [o+1Y] ./node_modules/primeng/resources/themes/bootstrap/theme.css
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/quill/dist/quill.snow.css 24.3 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [gJae] ./node_modules/quill/dist/quill.snow.css
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/@progress/kendo-theme-default/scss/all.scss 481 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [duK/] ./node_modules/@progress/kendo-theme-default/scss/all.scss
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/@progress/kendo-theme-material/scss/all.scss 381 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [6+2p] ./node_modules/@progress/kendo-theme-material/scss/all.scss
 [] css ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css 62.6 KiB {3}
     ModuleConcatenation bailout: Module is not an ECMAScript module
     [tNt0] ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css
 [+EN/] ./src/styles.scss 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\src\styles.scss [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[0]
 [6+2p] ./node_modules/@progress/kendo-theme-material/scss/all.scss 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\node_modules\@progress\kendo-theme-material\scss\all.scss [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[7]
 [NIap] ./node_modules/primeng/resources/primeng.css 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\node_modules\primeng\resources\primeng.css [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[3]
 [duK/] ./node_modules/@progress/kendo-theme-default/scss/all.scss 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\node_modules\@progress\kendo-theme-default\scss\all.scss [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[6]
 [gJae] ./node_modules/quill/dist/quill.snow.css 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\node_modules\quill\dist\quill.snow.css [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[5]
 [hRJ5] ./node_modules/font-awesome/scss/font-awesome.scss 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\node_modules\font-awesome\scss\font-awesome.scss [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[2]
 [o+1Y] ./node_modules/primeng/resources/themes/bootstrap/theme.css 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\node_modules\primeng\resources\themes\bootstrap\theme.css [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[4]
 [tNt0] ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\node_modules\@angular\material\prebuilt-themes\deeppurple-amber.css [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss ./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[8]
 [xarx] ./src/scss/common.scss 39 bytes {3} [built]
     ModuleConcatenation bailout: Module is not an ECMAScript module
     single entry C:\dev\   \ClientApp\src\scss\common.scss [2] multi ./src/styles.scss ./src/scss/common.scss ./node_modules/font-awesome/scss/font-awesome.scss
./node_modules/primeng/resources/primeng.css ./node_modules/primeng/resources/themes/bootstrap/theme.css ./node_modules/quill/dist/quill.snow.css ./node_modules/@progress/kendo-theme-default/scss/all.scss ./node_modules/@progress/kendo-theme-material/scss/all.scss ./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css styles[1]
chunk {scripts} scripts.76160f3207e5866c6d62.js (scripts) 0 bytes [rendered]

WARNING in Invalid font values at 11022:4. Ignoring.

WARNING in Invalid font values at 11788:2. Ignoring.

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:717,1]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:1953,4]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:1952,8]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7332,4]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7331,8]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7339,4]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7342,5]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7341,9]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7338,8]

ERROR in EISDIR: illegal operation on a directory, read
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  3.64 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 62.7 KiB [entry] [rendered]
     [Zcv6] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css 62.7 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\@angular\material\prebuilt-themes\deeppurple-amber.css  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/primeng/resources/primeng.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  3.64 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 107 KiB [entry] [rendered]
     [NvHu] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/primeng/resources/primeng.css 107 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\primeng\resources\primeng.css  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/primeng/resources/themes/bootstrap/theme.css:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  2.57 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 59.7 KiB [entry] [rendered]
     [JX2F] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/primeng/resources/themes/bootstrap/theme.css 59.7 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\primeng\resources\themes\bootstrap\theme.css  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/quill/dist/quill.snow.css:
                   Asset     Size  Chunks  Chunk Names
    3rdpartylicenses.txt  1.5 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 25.3 KiB [entry] [rendered]
     [GolL] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/quill/dist/quill.snow.css 25.3 KiB
{0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\quill\dist\quill.snow.css  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!node_modules/@progress/kendo-theme-default/scss/all.scss:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  4.96 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 498 KiB [entry] [rendered]
     [HOaz] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/@progress/kendo-theme-default/scss/all.scss 498 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\sass-loader\lib\loader.js??ref--14-3!C:\dev\   \ClientApp\node_modules\@progress\kendo-theme-default\scss\all.scss  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!node_modules/@progress/kendo-theme-material/scss/all.scss:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  4.31 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 393 KiB [entry] [rendered]
     [AhW+] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/@progress/kendo-theme-material/scss/all.scss 393 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\sass-loader\lib\loader.js??ref--14-3!C:\dev\   \ClientApp\node_modules\@progress\kendo-theme-material\scss\all.scss  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!node_modules/font-awesome/scss/font-awesome.scss:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  3.67 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 36.8 KiB [entry] [rendered]
     [/SHa] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./node_modules/font-awesome/scss/font-awesome.scss 36.8 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\sass-loader\lib\loader.js??ref--14-3!C:\dev\   \ClientApp\node_modules\font-awesome\scss\font-awesome.scss  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!src/scss/common.scss:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  3.67 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 504 KiB [entry] [rendered]
     [eKeX] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/scss/common.scss 504 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\sass-loader\lib\loader.js??ref--14-3!C:\dev\   \ClientApp\src\scss\common.scss  mini-css-extract-plugin
Child mini-css-extract-plugin node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!node_modules/postcss-loader/src/index.js??extracted!node_modules/sass-loader/lib/loader.js??ref--14-3!src/styles.scss:
                   Asset      Size  Chunks  Chunk Names
    3rdpartylicenses.txt  3.64 KiB
    Entrypoint mini-css-extract-plugin = *
    chunk    {0} * (mini-css-extract-plugin) 3.03 KiB [entry] [rendered]
     [/c4r] ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??extracted!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss 3.03 KiB {0} [built]
         ModuleConcatenation bailout: Module is not an ECMAScript module
         single entry !!C:\dev\   \ClientApp\node_modules\@angular-devkit\build-angular\src\angular-cli-files\plugins\raw-css-loader.js!C:\dev\   \ClientApp\node_modules\postcss-loader\src\index.js??extracted!C:\dev\   \ClientApp\node_modules\sass-loader\lib\loader.js??ref--14-3!C:\dev\   \ClientApp\src\styles.scss  mini-css-extract-plugin

WARNING in Invalid font values at 11022:4. Ignoring.

WARNING in Invalid font values at 11788:2. Ignoring.

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:717,1]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:1953,4]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:1952,8]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7332,4]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7331,8]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7339,4]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7342,5]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7341,9]

WARNING in Terser Plugin: Dropping side-effect-free statement [scripts.76160f3207e5866c6d62.js:7338,8]

ERROR in EISDIR: illegal operation on a directory, read

### Mention any other details that might be useful

@angular-devkit/build-angular 0.11.4 is has a fixed dependency on license-webpack-plugin 2.0.2.
license-webpack-plugin 2.0.2 has an issue https://github.com/xz64/license-webpack-plugin/pull/57 that causes the build to fail when if the guessed name is a folder instead of a file.
Issue has since been fixed in license-webpack-plugin as of 2.0.3.

**Comment by alan-agius4** [comment]
Closed via 
https://github.com/angular/angular-cli/pull/13332
