### ISSUE TITLE
ng g service - provideIn configuration

### ISSUE THREAD

**Issue by vitaliy-bobrov** [angular/angular-cli#13335]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
7.1.4

### Repro steps
When user trying to generate a service with `ng g service my-service`, by default it puts `provideIn: 'root'` option without any options

### Desired functionality
Add option for service schematic that will allot users to generate a service without `provideIn` option or specify the target.

### Mention any other details that might be useful
I'd like to suggest 2 possible solutions:
1. Allow user to specify provider target (string), default value should be 'root'. User could specify a module symbol or empty string (will not add option to Injectable decorator).
2. Allow user to disable `provideIn` option during generation with bool option.

If you find this feature useful, I'll be happy to prepare a PR for it ;)

**Comment by vitaliy-bobrov** [comment]
@alan-agius4 , wdyt about possible solutions I've mentioned?

**Comment by alan-agius4** [comment]
A service should always be `Injectable`, in case you don't want to have the `Injectable` decorator, you should use the `class` schematic (https://angular.io/cli/generate#class-command).

Regarding of having something other than `root` as `providedIn` value, this might be an option. However this will need to be discussed with the rest of team in our next team meeting. 

Docs link for future reference https://angular.io/guide/providers#providing-a-service

**Comment by vitaliy-bobrov** [comment]
@alan-agius4, I didn't mean not to add `Injectable` decorator. Could you update the issue after team meeting? So I will work on PR.

**Comment by alan-agius4** [comment]
@vitaliy-bobrov, following the team discussion we decided that we shouldn't provide this feature. As `providedIn: 'root' caters for the 99% of the cases and adding this feature might lead users to use this incorrectly. Similar to the `module` option that was previously available.
