### ISSUE TITLE
Is this possible to change script path after build?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#13343]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
```

### Versions

Output from: 
`node --version` -> `8.11.3`
 `npm --version` -> `5.6.0`
 `ng-cli` -> `7.1.3`
 

### Repro steps
 if you give `ng build` command it create build file inside dist folder.

In this folder index.html file looks like this

>   <app-root></app-root>
>   <script type="text/javascript" src="runtime.js"></script>
> 
>   <script type="text/javascript" src="polyfills.js"></script>
>   <script type="text/javascript" src="styles.js"></script>
>   <script type="text/javascript" src="vendor.js"></script>
>   <script type="text/javascript" src="main.js"></script>
> </body>

### Desired functionality

here i want to change path of this script file like below

>   <app-root></app-root>
>   <script type="text/javascript" src="~/runtime.js"></script>
>   <script type="text/javascript" src="~/polyfills.js"></script>
>   <script type="text/javascript" src="~/styles.js"></script>
>   <script type="text/javascript" src="~/vendor.js"></script>
>   <script type="text/javascript" src="~/main.js"></script>
> </body>
> 

**### old path**: <script type="text/javascript" **src="runtime.js"**></script>
 
**### expected path:** <script type="text/javascript" **src="~/runtime.js"**></script>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
