### ISSUE TITLE
Update from LTS version to LTS version

### ISSUE THREAD

**Issue by tinogo** [angular/angular-cli#13358]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Desired functionality
At our company we want to be able update our Angular apps from LTS version to LTS version.
As it currently stands, this doesn't seem to be possible with `ng update`, as it will always update to the latest available (stable) version of Angular.

It would be great if you could add this functionality in the form of a new option `--lts` (so this will update to the latest available LTS version) or something like that, so that one will be able to update an Angular app from version 5 to version 6 even though version 7 (or later) got already released. :)

**Comment by alan-agius4** [comment]
In the latest versions of the CLI you can specify the npm tag, however I doubt this works in Angular CLI version 1.

Example
```cmd
ng update @angular/cli@v6-lts
ng update @angular/cli@next
```

That said we strongly encourage you to update to the latest stable version instead of the LTS, so you can benefit from performance improvements, bug fixes and new features.

**Comment by clydin** [comment]
It is also important to note that all major versions will receive long term support.  Please see the following for further details: https://angular.io/guide/releases#support-policy-and-schedule
