### ISSUE TITLE
Service worker not getting registered

### ISSUE THREAD

**Issue by jqp5000** [angular/angular-cli#13351]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps
Followed steps in the official doc for setting up the service worker: https://angular.io/guide/service-worker-getting-started

### The log given by the failure

No errors, all goes well but when loading the app in the browser the service worker is not being registered.

### Mention any other details that might be useful
**Temp solution**: manually registering the service worker in the main.ts file solves the issue:
```
platformBrowserDynamic().bootstrapModule(AppModule).then(() => {
  if ('serviceWorker' in navigator && environment.production) {
    navigator.serviceWorker.register('/ngsw-worker.js');
  }
}).catch(err => console.log(err));
```

**Comment by moxival** [comment]
Does it have anything to do with this https://github.com/angular/angular-cli/issues/8779#issuecomment-350737663 ?

We were having the same issue and it turned out we were using intervals from within the zone.

**Comment by alan-agius4** [comment]
Hi, indeed this might be the case that the application doesn't get in a stable state.

However, the issue will be closed since the issue template was not followed. Ie no reproduction, nor details about the versions were provided. 

If the problem persists kindly open a new issue and kindly fill the issue template and ideally provide a reproduction.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by kolkov** [comment]
Tha same issue for me too! 
Angular CLI: 7.2.1
Node: 10.13.0
OS: win32 x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cli                      7.2.1
@angular/pwa                      0.12.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1

**Comment by kolkov** [comment]
> Service workers are only available to "secure origins" (HTTPS sites, basically) in line with a policy to prefer secure origins for powerful new features. However http://localhost is also considered a secure origin, so if you can, developing on localhost is an easy way to avoid this error.

https://www.chromium.org/blink/serviceworker/service-worker-faq

**Comment by JesseZomer** [comment]
I had the same problem but found a fix. 
In app.module.ts the following was added:
```
        ServiceWorkerModule.register('ngsw-worker.js', {
            enabled: environment.production
        })
```
but this needed to be:
```
        ServiceWorkerModule.register('/ngsw-worker.js', {
            enabled: environment.production
        })
```
with the `/` in front of the ngsw-worker.js.

Hope this helps.

**Comment by duard** [comment]
Same issue for me too!

**Comment by DJklimentina** [comment]
I used the temporary solution that is mentioned here and now I have a different problem. Can this cause the service worker to be also working locally(ng serve)? (I know that the service worker shouldn't be working locally but somehow it does)

**Comment by Ettores88** [comment]
+1 We are experiencing the same problem. 

/cc @unsafecode

**Comment by duard** [comment]
Same problem here ... I cant register my service worker :-(

**Comment by maxcl10** [comment]
I have the same issue. Was working before I update to version 7.2.11.
  "@angular/animations": "7.2.11",
    "@angular/common": "7.2.11",
    "@angular/compiler": "7.2.11",
    "@angular/core": "7.2.11",
    "@angular/forms": "7.2.11",
    "@angular/http": "7.2.11",
    "@angular/platform-browser": "7.2.11",
    "@angular/platform-browser-dynamic": "7.2.11",
    "@angular/platform-server": "7.2.11",
    "@angular/pwa": "^0.10.2",
    "@angular/router": "7.2.11",
    "@angular/service-worker": "7.2.11",

**Comment by jamesbarrett95** [comment]
Receiving the same issue. 
    "@angular/animations": "^7.1.1",
    "@angular/cdk": "^6.3.3",
    "@angular/common": "^7.1.1",
    "@angular/compiler": "^7.1.1",
    "@angular/core": "^7.1.1",
    "@angular/flex-layout": "^7.0.0-beta.19",
    "@angular/forms": "^7.1.1",
    "@angular/http": "^7.1.1",
    "@angular/material": "^6.3.3",
    "@angular/material-moment-adapter": "^6.4.6",
    "@angular/platform-browser": "^7.1.1",
    "@angular/platform-browser-dynamic": "^7.1.1",
    "@angular/pwa": "^0.13.7",
    "@angular/router": "^7.1.1",
    "@angular/service-worker": "^7.1.1",

**Comment by C0ZEN** [comment]
+1

**Comment by DenisValcke** [comment]
I have the same issue and the workaround doesn't seem to help either.

**Comment by DenisValcke** [comment]
Why is this issue closed when it hasn't been solved yet?

**Comment by JRafael91** [comment]
same problem, I hope that in angular 8 it is solved

**Comment by C0ZEN** [comment]
I am disappointed that this kind of bug exists and I would love to see it resolved without the need to apply a fix on my own code nevertheless as far as I saw, a developer issue.
I was able in a first time to apply a dirty code to force the service worker to register itself.

**main.ts**
```
if ('serviceWorker' in navigator && isProduction) {
    navigator.serviceWorker.register('./ngsw-worker.js');
}
```
**Note:** the `./` is very important to avoid an error with custom base href.

And after more search, I figured out that the culprit was my code...

These issues helped me:
- https://github.com/angular/angular/issues/20970
- https://github.com/angular/angular-cli/issues/8779

Basically, I made two mistakes while using:
- `fromEvent`
- `SwUpdate`

To fix them, I used `applicationRef.isStable`.

**Example:**
```
this.isStableSubscription = this.applicationRef.isStable.subscribe(isStable => {
    if (isStable) {
        fromEvent(window, 'resize').pipe(
            distinctUntilChanged(),
            debounceTime(30)
        ).subscribe(() => {

            // Do some stuff here
        });
        this.isStableSubscription.unsubscribe();
    }
});
```
**Note:** if `applicationRef` is causing a cyclic dependency, you shloud:
- Use `private injector: Injector` in the constructor
- Create a property and set it `this.applicationRef = this.injector.get(ApplicationRef);`

**Comment by dman777** [comment]
I just hit this bug with Angular 7.3.1. Why is the bug closed?

**Comment by bleuscyther** [comment]
+1

**Comment by bleuscyther** [comment]
This help me : https://github.com/angular/angular-cli/issues/8515#issuecomment-486017106

**Comment by casper5822** [comment]
Same problem for me with angular-cli 7.3.9

**Comment by kolkov** [comment]
And for me with Angular CLI 8.2.0-rc.0

**Comment by casper5822** [comment]
It works if with angular-cli 7.3.9 with this solution:
1) add to main.ts: 
platformBrowserDynamic().bootstrapModule(AppModule).then(() => {
		if ('serviceWorker' in navigator && environment.production) {
			navigator.serviceWorker.register('./ngsw-worker.js');
		}
	})
	.catch(console.error);
2) in the app module set: 
  ServiceWorkerModule.register('./ngsw-worker.js', { enabled: environment.production })

3) in the manifest.json:
   "scope": "/",
  "start_url": "/<the base-href used for the ng-build>/",

**Comment by elgerm** [comment]
Found a solution:

I too had this problem with my project, and spent a whole day trying to figure it out. Yes, starting a clean new project and installing the @angular/pwa works out of the box. But as soon as you start building a bit on your project, it silently fails / just doesn't load ngsw-worker.js.

Finally I downloaded the angular code and looked at the sources. It appears that there is a 'registrationStrategy' which has to do with if angular waits with the registration until your app is 'stable'. Now I have a bunch of stuff I'm loading at the beginning of my project (like oidc client and building websocket connections) and angular apparently thinks my app never is stable.

Fortunately you can override the registrationStrategy like so:

`ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production, registrationStrategy: 'registerImmediately' }),`

See for the documentation [here](https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy)

After this the serviceworker will load, whatever the state of your app. There's also an option to pass an observable, so you can have it loaded whenever you think it's right.

I think this really really needs to be documented somewhere, preferably in the top of the docs with capital letters. Also, when the ngsw-worker doesn't load whenever it isn't stable, it would be VERY helpful to at least log something in the console!

**Comment by kolkov** [comment]
@elgerm thank you very much!
And team, what about main problem? How to debug my application stabilization? Thanks!
