### ISSUE TITLE
Default target should be ES6 in generated tsconfig.json

### ISSUE THREAD

**Issue by fr0** [angular/angular-cli#13352]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 7.1.4
Node: 10.13.0
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

### Desired functionality

The default `"target"` in `tsconfig.json` generated by `ng new` should be `"es6"`, not `"es5"`.

Reasons:
1. Modern browsers are being optimized for ES6 now. ES5 is no longer necessary or optimal.
2. Smaller generated code files.
3. Fewer problems out-of-the box (without having to use flags that new users might not know about), e.g. https://github.com/Microsoft/TypeScript/issues/3164 

I understand this is a judgement call, and there could be reasons I don't know about to keep the default as es5. If so, I'd like to hear what those are, since I believe it is better to move forward. Apps that have to support Internet Explorer already need to include some polyfills, and I think they're in the minority, so the default should cater to the majority -- users that really *should* be targeting ES6, and may not even think to change the settings in their `tsconfig.json` file.

**Comment by mgechev** [comment]
We'll be working on differential bundling so this would be the default behavior. I'll assign the issue to @manfredsteyer.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in version 8.
