### ISSUE TITLE
Please add documentation how to configure the webserver

### ISSUE THREAD

**Issue by aggro80** [angular/angular-cli#1335]
Please add documentation or a link to the documentation how to configure the web server, how to 
1) Set port (without giving it every time)
2) Enable https
3) Set startPath
4) Set redirect rules

Here is an example configuration file for lite-server that provides methods for how to do this on lite-server. 

```
var modRewrite  = require('connect-modrewrite');

module.exports = {
  "port": 3000,
  "server": { "baseDir": "./" },
  "https": true,
  "startPath": '/base/web/static/',
  "middleware": [
               modRewrite([
                   '^/base/web/static/foo(.*)$ https://localhost:3000/index.html [P]',
                   '^/base/web/static/(.*)$ https://localhost:3000/$1 [P]'
               ])
          ]
};
```

**Comment by filipesilva** [comment]
There are a few options to configure, but not necessarily the ones you're looking for. We'll document what we have.

**Comment by hansl** [comment]
Closing this as obsolete.
