### ISSUE TITLE
Angular CLI installation Error - AJV package does not get installed properly

### ISSUE THREAD

**Issue by dlokman** [angular/angular-cli#13350]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ x] version
- [ ] doc
```

### Versions
get error

C:\>ng --version
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module './data'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Danial.Lokman\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\ajv\lib\ajv.js:10:23)

### Repro steps

npm install -g @angular/cli@7.1.2 on a company laptop with local admin priviliges

### The log given by the failure

C:\>npm install -g @angular/cli@7.1.2
npm WARN tar EPERM: operation not permitted, open 'C:\Users\Danial.Lokman\AppData\Roaming\npm\node_modules\.staging\ajv-40a451eb\lib\data.js'

### Desired functionality

Installing Angular cli should install node module package "ajv" properly. I checked github and data.js file exists there. This does not get copied over during installation due to some administrative privileges. I'm a local admin on my company machine.

https://github.com/epoberezkin/ajv/tree/master/lib

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by dlokman** [comment]
so all the Angular CLI node_module packages install correctly except ajv. While installing ajv it tries to create a temporary ./staging folder inside node_modules but it’s unable to copy over data.js file. Do you think it’s an non or node issue rather than Angular CLI issue? GitHub repository for ajv has the data.js file. Rest of the files and folders under ajv install correctly.

**Comment by dlokman** [comment]
When I try to unzip the ajv folder on my work computer I get an admin privilege error for data.js file. Rest of the files unzip properly. What’s so special about data.js file. Won’t this be a Angular CLI AJV package issue? Since I can’t even unzip it?
