### ISSUE TITLE
Enhance build configuration

### ISSUE THREAD

**Issue by danielbradburry** [angular/angular-cli#13360]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Desired functionality
We are attempting to migrate an existing application from Angular 5 to 6+ and have run into a substantial blocker. We understand that support for ejecting projects from the CLI has been removed and we need more robust configuration support from Angular/CLI.

We've been looking at ngx-build-plus, and are concerned that it doesn't provide the granularity of control that an ejected webpack configuration script does. We have a need for the following:

- Edit existing webpack plugins
- Add new plugins (definePlugin)
- Configure variant build processes via inline parameters by setting environment variables and using them in the configuration script
- Configure additional entry/output properties for custom script inclusion

Any assistance that can be provided by the Angular/CLI team or this community would be appreciated.

**Comment by mgechev** [comment]
Hey @danielbradburry, with `ngx-build-plus` you should be able to achieve most of what you mentioned. We believe Angular CLI covers a large amount of use cases; together with `ngx-build-plus` it's even more powerful.

We understand that in some extreme cases this might not be enough; in the same time we need to find the right balance between build encapsulation and flexibility. The two options that you can consider are to use a custom build setup, which may require more maintenance or consider simplifying your build process so you can get close to your desired results by using the CLI and build-plus.

Would be curious to know what's your use case?
