### ISSUE TITLE
unable to run e2e tests with simple project

### ISSUE THREAD

**Issue by peterennis** [angular/angular-cli#13376]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Related: #13113 
PR in the works for #13113 => https://github.com/angular/angular-cli/pull/13272

My error:

```
C:\ae\adaept.com\aeicons-angular>npm run e2e

> aeicons-angular@0.0.1 e2e C:\ae\adaept.com\aeicons-angular
> ng e2e

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2019-01-06T22:23:25.680Z
Hash: 14fa6ee4a7dad803e96e
Time: 13241ms
chunk {main} main.js, main.js.map (main) 10.8 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 223 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.43 MB [initial] [rendered]
i ｢wdm｣: Compiled successfully.
[14:23:26] I/update - chromedriver: file exists C:\ae\adaept.com\aeicons-angular\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.45.zip
[14:23:26] I/update - chromedriver: unzipping chromedriver_2.45.zip
[14:23:26] I/update - chromedriver: chromedriver_2.45.exe up to date
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:742:20)
    at ChildProcess.target.send (internal/child_process.js:626:19)
    at Observable.rxjs_1.Observable.obs [as _subscribe] (C:\ae\adaept.com\aeicons-angular\node_modules\@angular-devkit\build-angular\src\utils\run-module-as-observable-fork.js:57:23)
```

### Repro steps

Repo: https://github.com/peterennis/aeicons-angular

### Desired functionality

No error.

### Mention any other details that might be useful

Dependencies updated from basic project creation.

**Comment by alan-agius4** [comment]
The fix for this has not yet been released. This will be released later on this week.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by omryoz** [comment]
> The fix for this has not yet been released. This will be released later on this week.
> 
> If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

any ETA?

**Comment by alan-agius4** [comment]
This will be released later on this week, probably Wednesday.

**Comment by HardcoreCore** [comment]
+have the same issue

**Comment by Thormod** [comment]
+have the same issue!

**Comment by mateoescobarm** [comment]
+have the same issue!

**Comment by Androsid** [comment]
+ have the same issue

**Comment by Znow** [comment]
Any update on release? still having this issue...

**Comment by arawinters** [comment]
same here. I am absolutely mystified how I can create a brand new project and e2e be broken. like how is that even a thing?!?!

**Comment by ermarkar** [comment]
any solution so far? I am facing the same issue node 10.15.3
cli - 7.3.8
