### ISSUE TITLE
After build, enum is not being imported

### ISSUE THREAD

**Issue by fernandoiwamoto** [angular/angular-cli#13379]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
npm 6.4.1
Angular CLI: 7.1.4
Node: 8.12.0
OS: win32 x64
Angular: 7.1.4

### Repro steps
Create projectA(ng new projectA)
Generate as libraryA(ng generate library libraryA)
Create file enum inside of projects/libraryA(export enum SomeEnum)

`
export enum SomeEnum {
  SOMEVALUE = 'Some value',
  OTHERVALUE = 'Other Value'
}
`

Create projectB(ng new projectB)
Generate as library B(ng generate library libraryB)
Use the libraryA inside of projectB
Inside of projects/libraryB.component.ts, declare variable.
`
readonly enum = SomeEnum.SOMEVALUE ;
`

Then build as library (ng build libraryB)

When you check the compiled libraryB, libraryB.component.ts doesn't have import of SomeEnum.

Another examples to investigate:

`
enum2 = SomeEnum.SomeValue; // does import but doesn't set attribute to value
readonly enum3: SomeEnum = SomeEnum.SomeValue; // does import but doesn't set attribute to value
enum4: SomeEnum = SomeEnum.SomeValue;  // does import but doesn't set attribute to value
`

### The log given by the failure
error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal or literal enum reference.

### Desired functionality
After compiling, the enum should be imported.

**Comment by mgechev** [comment]
Do you need projectA or you can use only libraryA? @fernandoiwamoto would you share a demo on GitHub?

**Comment by alan-agius4** [comment]
Closing as the reporter never got back to us.
