### ISSUE TITLE
Tree type is not supported- error with ng new

### ISSUE THREAD

**Issue by derrichinho** [angular/angular-cli#13380]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X ] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

Angular CLI: 6.2.8
Node: 11.4.0
OS: win32 x64
Angular:
...

| Package 							| Version           
| --------------------------------- |:-------------:
| @angular-devkit/architect      	| 0.10.6
| @angular-devkit/build-angular		| 0.10.6
| @angular-devkit/build-optimizer	| 0.10.6
| @angular-devkit/build-webpack		| 0.10.6
| @angular-devkit/core				| 7.0.6	
| @angular-devkit/schematics		| 7.0.6
| @angular/cli						| 7.0.6
| @ngtools/webpack                  | 7.0.6
| @schematics/angular               | 7.0.6
| @schematics/update                | 0.10.6
| rxjs                              | 6.3.3
| typescript                        | 3.1.6
| webpack                           | 4.19.1  

### Repro steps

I wanted to have two versions of angular on my machine (Angular 6 and 7) and I accidentally remove a file from  the npm-cache folder, I guess that it maybe cause the failure.
So I tried repairing that by uninstalling all the programs needed and installing them again, but when I tried to create an `ng new` project it shows me that the "Tree Type is not supported".

I followed step by step all those issues: 
       -Error "Tree type is not supported." when generating new module in v6.1.1: https://github.com/angular/angular-cli/issues/11683
      -`ng new` error 'Tree type is not supported: https://github.com/angular/angular-cli/issues/11707
      -Schematic - Tree type is not supported: https://github.com/angular/angular-cli/issues/11963
 
But the problem still there.

### The log given by the failure

$ `ng new my-app`
Tree type is not supported.

### Desired functionality

I expected to be able to create a new project without problems.

### Mention any other details that might be useful

When I ran the `npm cache clean` command there's an npm error:

npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead. On the other hand, if you're debugging an issue with the installer, you can use `npm install --cache /tmp/empty-cache` to use a temporary cache instead of nuking the actual one.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this commandwith --force.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dallensm\AppData\Roaming\npm-cache\_logs\2019-01-04T23_55_21_210Z-debug.log

**Comment by mgechev** [comment]
@derrichinho thanks for reaching out, and thank you for the detailed description!

This doesn't look like an issue in the CLI, I'd recommend you to use either StackOverflow or our channel on Gitter.

If it turns out to be a bug in Angular CLI, please feel free to open a new issue. Thanks!
