### ISSUE TITLE
Can not serve library

### ISSUE THREAD

**Issue by vahidvdn** [angular/angular-cli#13411]
In latest versions of Angular cli, we can use `ng g library lib-name` command to create library. As mentioned in the Angular [docs][1] :
  
    ng serve <project>

And:

  [1]: https://angular.io/cli/serve

    <project>	The name of the project to build. Can be an app or a library.

So, we can serve **library**. But when I serve I get the following errors:

    Project 'ngx-tab-component' does not support the 'serve' target.
    Error: Project 'ngx-tab-component' does not support the 'serve' target.
    at ServeCommand.initialize (C:\Users\vahidnajafi\angular\ngx-tab-app\node_modules\@angular\cli\models\architect-command.js:53:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by alan-agius4** [comment]
Hi, `serve` is not supported in libraries.

See https://github.com/angular/angular/issues/26569

**Comment by vahidvdn** [comment]
@alan-agius4 So how is it possible to develop a library without `serve` command?

**Comment by alan-agius4** [comment]
Unit testing togather with an host/test application.

You’d need to build and watch the library and serve the application at the same time.

```
ng build my-lib —watch

ng serve my-app
```
