### ISSUE TITLE
Error: Attempting to watch missing directory: typings

### ISSUE THREAD

**Issue by tdinar** [angular/angular-cli#1341]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
EC2, 	Ubuntu 14.04.4 LTS

2. Versions. Please run `ng --version`. If there's nothing outputted, please
node version: node: 6.3.0
npm version: 3.10.5
angular-cli: 1.0.0-beta.9

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I am running the script below with the command

sudo ./script.txt
------

 npm install npm@latest -g
 npm install angular-cli@latest -g
 ng new imap
 cd ~/imap/node_modules/
 npm install angular-cli@latest
 cd ~/imap/
 ng build
 ng serve

--------
~ 

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.

But I think what happened was that typings didn't run for some reason, which happens a surprising amount of times on CIs... The PR above removes the need for typings.
