### ISSUE TITLE
Dynamic component imports/declarations in prod builds

### ISSUE THREAD

**Issue by pstahmer** [angular/angular-cli#13416]
### Bug Report or Feature Request (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps
Try to do your component imports for your module dynamically off a directory
```
import * as components from 'app/components';

const componentsArray = [];
Object.keys(components).forEach(name => componentsArray.push(components[name]));

@NgModule({
  declarations: [
    AppComponent,
    ...componentsArray
  ],
  imports: [
    BrowserModule,
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }
```

### The log given by the failure

ERROR in : Cannot determine the module for class SampleComponent in /.../projects/example/src/app/components/sample-component/sample.component.ts! Add SampleComponent to the NgModule to fix it.
Cannot determine the module for class OtherSampleComponent in /.../projects/example/src/app/components/other-sample/other-sample.component.ts! Add OtherSampleComponent to the NgModule to fix it.

### Desired functionality
When you have a project with a large count of components it can be a maintenance hazard to have a list of 100 imports. It's an easy step to forget when someone adds a new component, or renames them, or moves them to a different subdirectory. Using index.ts files you can get them all exported to a top-level directory, and then iterate over the import to get them all added to your module. This works fine for development but when I run a prod build it thinks I've never imported the components, even though they clearly are. As near as I can tell the only reason for this is that the names don't show up as an explicit import in the file itself.

I've done some console logging and confirmed that the output of this method is identical to if I just statically add them to the declarations array. There are no stray elements getting in, and every component is listed. 

I assume I'm missing some understanding of how the aot compilation handles index files and how that impacts this approach.

### Mention any other details that might be useful
This approach only seems to fail for components inside prod/aot builds. For non-prod/aot builds it works fine, for adding services to the module's providers it works, for importing ngrx effects it works.

**Comment by mgechev** [comment]
@pstahmer a restriction of the AoT compiler is that the NgModule metadata should bee resolvable at build time. This syntax is quite dynamic and hard, maybe even impossible, to resolve.

I'd recommend you to export an array with your components in the `app/components` module and include them in your declarations.

**Comment by pstahmer** [comment]
I'm not sure I follow. I haven't adjusted the metadata in any way, and the data I provide into the declaration is identical in both cases. The only difference is the dynamic use of index files and import statements. As long as those index files and imports can still be resolved there shouldn't be an issue.

Based on the fact that this does work with services/providers I find it hard to believe that it is somehow not resolvable for components/declarations.

**Comment by mgechev** [comment]
This is not supported by the Ahead-of-Time compiler and it's not a bug in the CLI.

**Comment by pstahmer** [comment]
Alright, I'll give that a shot, thank you!

**Comment by pstahmer** [comment]
That seems unlikely to me that this is a bug elsewhere since it's a build-time error that only occurs with the aot flag enabled. 

Can you be more specific about what part of this is not supported by the AOT compiler? I still find this statement confusing since you can dynamically import services like this with no issue.

**Comment by jamie-pate** [comment]
The error happens in the angular compiler, which needs to be able to statically analyze the list of declaration tokens (component/directive classes, etc) for 'reasons'. The static analysis is not very complicated, so any code that needs to run to evaluate the imports/declarations will cause errors. (this should probably be pointed out in the error message?)
