### ISSUE TITLE
Feature request: default 'test' environment

### ISSUE THREAD

**Issue by rmorrise** [angular/angular-cli#13418]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [x] test
```

### Versions
```
v8.11.2
5.6.0
Angular CLI: 6.2.7
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.7
@angular-devkit/build-angular     0.8.7
@angular-devkit/build-optimizer   0.8.7
@angular-devkit/build-webpack     0.8.7
@angular-devkit/core              0.8.7
@angular-devkit/schematics        0.8.7
@angular/cli                      6.2.7
@ngtools/webpack                  6.2.7
@schematics/angular               0.8.7
@schematics/update                0.8.7
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.16.4

```

### Repro steps

`ng new foo`

### Desired functionality

When the app is generated, generate an `environment.test.ts` in `src/environments`. The test environment should be used when running `ng test`.

### Mention any other details that might be useful

The following comment details the `angular.json` changes required to apply the test environment:
https://github.com/angular/angular-cli/issues/10813#issuecomment-388484179

The `fileReplacements` and `environment` settings should be added to `angular.json` when the project is created.

**Comment by rmorrise** [comment]
This would be useful for unit testing classes which reference properties in the environment. These properties may be different than when running in local development mode - for example, I have a local dev config which doesn't have API keys, but I want to test that my service class is using the API key from my production config.

**Comment by rmorrise** [comment]
The comment I linked above gives a settings change that exactly reproduces the desired behavior. My feature request is to make this setting the default.

**Comment by mgechev** [comment]
This feature is definitely useful in some cases. We should still set boundaries of the scope of the CLI so we can keep it from blowing in complexity.

Let's close the issue for now and reopen/open a new one if this feature becomes in higher demand.

**Comment by rmorrise** [comment]
@mgechev I would expect that unit testing any class that follows angular patterns should be a standard feature of the framework, not an optional configuration.

 If you think there is a simpler solution for unit testing classes which use `environment.ts`, please suggest.
