### ISSUE TITLE
e2e script is created in package.json when --createApplication=false

### ISSUE THREAD

**Issue by Ant59** [angular/angular-cli#13412]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
Node: v10.13.0
NPM: v6.4.1
Angular CLI: v7.1.3

### Repro steps

1. ```ng new --createApplication=false```
2. e2e script is added to package.json

### Desired functionality

The e2e script should not be added to the package.json because no e2e directory or functionality is generated when createApplication flag is false.

**Comment by ahasall** [comment]
Hi @alan-agius4, I can fix this issue if you are okay with it.

**Comment by alan-agius4** [comment]
@shahata, sorry for the delay. You can take this is if you still want. However when adding an application we might want to add this.

**Comment by nadyafebi** [comment]
@alan-agius4 Is there anyone working on this issue? May I take it?

**Comment by ahasall** [comment]
I am not working on the issue and I think no one is. So feel free to take it.

**Comment by alan-agius4** [comment]
@nadyafebi, feel free to take it.
