### ISSUE TITLE
Provide progress reporters for non TTY consoles

### ISSUE THREAD

**Issue by GingerGeek** [angular/angular-cli#13426]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

GitLab CI Runner (Docker Executor: https://docs.gitlab.com/runner/executors/docker.html)
```
$ node -v
v11.6.0
```
```
$ npm -v
6.5.0-next.0
```
```
$ ./node_modules/@angular/cli/bin/ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.2.1
Node: 11.6.0
OS: linux x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.1
@angular-devkit/build-angular      0.12.1
@angular-devkit/build-optimizer    0.12.1
@angular-devkit/build-webpack      0.12.1
@angular-devkit/core               7.2.1
@angular-devkit/schematics         7.2.1
@angular/cdk                       7.2.1
@angular/cli                       7.2.1
@angular/flex-layout               7.0.0-beta.22
@angular/material                  7.2.1
@angular/material-moment-adapter   7.2.1
@ngtools/webpack                   7.2.1
@schematics/angular                7.2.1
@schematics/update                 0.12.1
rxjs                               6.3.3
typescript                         3.2.2
webpack                            4.23.1
```

### Repro steps

Execute a ci command which builds the angular application as part of it's execution. Ensure progress logging is enabled
```
./node_modules/@angular/cli/bin/ng build --progress=true
```
### The log given by the failure

<img width="1032" alt="chrome_9m9dgfxlr1" src="https://user-images.githubusercontent.com/4943487/51078184-8a794c00-16a9-11e9-839f-2b66dfbd21a1.png">

### Desired functionality
Build progress is logged in a format which is readable in CI environments or where the output is not a TTY console.

### Mention any other details that might be useful

Related PR: https://github.com/angular/angular-cli/pull/13405

**Comment by alan-agius4** [comment]
Hi, what is the use case to enable `progress` in a CI environment?

**Comment by GingerGeek** [comment]
> Hi, what is the use case to enable `progress` in a CI environment?

Having comprehensive build logs within a CI/CD pipeline is useful for verification and audit purposes (e.g ensuring uglifying occurs) - additionally in larger projects it's good to be able to see the status of the build rather than have no output until the entire webpack build is complete - which in some circumstances can be quite lengthy.

**Comment by syndicatedshannon** [comment]
> Hi, what is the use case to enable progress in a CI environment?

Azure supports monitoring console via browser during CI builds.

However, more than anything I want the final CI output to be readable, which could be implemented either as part of progress (as suggested by this issue), or as a separate machine output flag (as #6478  more likely implies).

**Comment by alan-agius4** [comment]
In version 11, the progress reporting has been revamped completely which should address this issue.

If the problem persists after updating to version 11. Kindly feel free to open a new issue.
