### ISSUE TITLE
Serve command error despite being in an Angular project

### ISSUE THREAD

**Issue by kwakwaa** [angular/angular-cli#13437]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions
![image](https://user-images.githubusercontent.com/43790012/51138213-66984080-1838-11e9-9223-ef3d7d2ab828.png)

### Repro steps
cd (...)/angular-app
ng serve

### The log given by the failure
The serve command requires to be run in an Angular project, but a project
definition could not be found.

### Mention any other details that might be useful
I've checked similar threads with this error and the consensus seems to be that the angular-cli version and the angular version need to be the same or atleast updated. Well, I've done that and I'm still getting the same error... Thank you for your time!

**Comment by BenjaminHofstetter** [comment]
Maybe your Node Version is to low. 

> Make sure that you have Node 10.9 or later installed. See instructions here. The Angular CLI requires Node 8, but development requires Node 10.

**Comment by mgechev** [comment]
@kwakwaa would you try updating your node version and trying again?

**Comment by alan-agius4** [comment]
Looking at the screenshot above I see some problems. 

1) There is no `@angular-devkit/build-angular` installed
2) TypeScript, RXJS and Angular dependencies are quite old

This makes me think that there is something wrong with the setup and/or environment.
