### ISSUE TITLE
There is a problem with “main.bundle.js” with Production mode build Angular5 - i18n localization

### ISSUE THREAD

**Issue by Sushrutbhosale** [angular/angular-cli#13447]
I have implemented Internationalization/Localization for an Angular5 app referring official documentation (https://angular.io/guide/i18n) and everything works as expected in dev/debug mode. when I create build with "ng build --prod" then in prod build localization is not working at all.

Main.ts
```
``import { enableProdMode, TRANSLATIONS, TRANSLATIONS_FORMAT } from 
'@angular/core';

var translations;
declare const require;

translations = require(`raw-loader!./locale/messages.ja.xlf`);

platformBrowserDynamic(providers).bootstrapModule(AppModule, {
    providers: [
      { provide: TRANSLATIONS, useValue: translations },
      { provide: TRANSLATIONS_FORMAT, useValue: 'xlf' }
    ]
  })
  .catch(err => console.log(err));
```

**Comment by alan-agius4** [comment]
Kindly follow the issue template, when filling issues.

Thank you.
