### ISSUE TITLE
Local IP address

### ISSUE THREAD

**Issue by lucini** [angular/angular-cli#13459]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

All versions.

### Desired functionality

The possibility to add ip address on the --open parameter on serve, actually only open in localhost, but i need open with local ip address. Our project have many microservices and a local gateway manage the call of APIs and redirect the calls to the respective local machine according the ip of request.

**Comment by clydin** [comment]
The open option is intended to be a basic convenience option.  Opening arbitrary addresses is beyond the scope of the feature.
