### ISSUE TITLE
Issue with angular-cli v1.x not compiling during test run but works fine on serve

### ISSUE THREAD

**Issue by parky128** [angular/angular-cli#13451]
I have encountered an odd issue where on trying to run my tests via the angular-cli, and webpack seems to be failing to compile my application. In particular it does not seem to like a node module I am importing into one of my TS source files.

I am using my own node module (not yet published to npm) which has an entry file defined like so:

**index.js**

    const MyModule = require('./src/index.js');
    
    const myModule = new MyModule();
    
    module.exports = {
      doStuff: myModule.doStuff,
      doOtherStuff: myModule.doOtherStuff
    }

In my TS source file (Angular app) I am including the module as follows:

    import MyModule = require('@acme/mymodule');

This works fine for me when running the application and I am able to call function exposed on the module in my code as expected.

When I run tests, I am getting the following error:

    16 01 2019 13:22:11.662:DEBUG [middleware:source-files]: Fetching /_karma_webpack_/main.bundle.js
    16 01 2019 13:22:12.067:DEBUG [phantomjs.launcher]: TypeError: undefined is not an object (evaluating 'modules[moduleId].call')
    
    16 01 2019 13:22:12.067:DEBUG [phantomjs.launcher]:   http://localhost:9876/_karma_webpack_/inline.bundle.js:55 in __webpack_require__
      http://localhost:9876/_karma_webpack_/main.bundle.js:10045 in ../../../../../src/test.ts
      http://localhost:9876/_karma_webpack_/inline.bundle.js:55 in __webpack_require__
      http://localhost:9876/_karma_webpack_/inline.bundle.js:26 in webpackJsonpCallback
    
    PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
      SyntaxError: Expected an identifier but found 'MyModule' instead
      at http://localhost:9876/_karma_webpack_/scripts.bundle.js:327
    PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
      SyntaxError: Expected an identifier but found 'MyModule' instead
      at http://localhost:9876/_karma_webpack_/scripts.bundle.js:327
    
    PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
      SyntaxError: Expected an identifier but found 'MyModule' instead
      at http://localhost:9876/_karma_webpack_/scripts.bundle.js:327
    
    16 01 2019 13:22:12.070:DEBUG [karma]: Run complete, exiting.
    16 01 2019 13:22:12.071:DEBUG [launcher]: Disconnecting all browsers

I wondered if this had anything to do with my usage of `const` and so I changed to `var` and this actually gets my past the error.

I would rather be able to use `const` and `let` throughout my node module source, which I am doing currently, is there something additional I need to configure with karma\webpack for compilation during the test run to allow my mode module to be included? Or could this be something to do with PhantomJS interpreting my usage of `require()` in my TS file?

I tried out using headless chrome for my tests, and I get `require is not defined` errors back from webpack instead.

I am using old angular-cli (v1.7.4) and have an Angular 5.x application thats not yet in a shape to migrate to something newer.

What could I be missing here to enable my app to compile for the test run?

Thanks

**Comment by mgechev** [comment]
@parky128 we're no longer publishing patches for Angular CLI v1.7. What are the blockers in front of you to migrate to a newer version?

For a support request it might be better to reach out to the appropriate channels - gitter or StackOverflow.
