### ISSUE TITLE
Polyfills split legacy and modern browsers

### ISSUE THREAD

**Issue by rickvandermey** [angular/angular-cli#13454]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
```

### Command (mark with an `x`)
```
- [x] new
```

### Desired functionality

When creating an Angular App with the NG command, i would love to see a split between polyfills for modern browsers and legacy browsers. While building the application the legacy browsers should read all scripts and modern browsers should skip the legacy bundle because of the nomodule attr in scripts.

```
<script nomodule src="/polyfills-legacy.js"></script>
<script src="/polyfills.js"></script>
```

For optimization the angular application, this would improve low-end devices with modern browsers. this would be a 35kb vs 13.5kb gzipped difference for modern browsers

**Comment by alan-agius4** [comment]
This has been implemented and already available in the current beta version.

See: https://github.com/angular/angular-cli/pull/13403
