### ISSUE TITLE
Allow glob path matching in schematics url

### ISSUE THREAD

**Issue by nickofthyme** [angular/angular-cli#13464]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [ x ] schematics
```

### Versions
```
@angular-devkit/schematics@latest
```

### Feature request
After using schematics for the first time recently I was trying to move one (or a few files) from one directory to another and found it to be incredibly difficult. It would be nice to be able to create a tree from a [glob pattern](https://docs.python.org/2/library/glob.html) url.

My use case was moving a `package.json` file from one directory to another by using a schematics "factory".

```ts
export function movePackage( _options: Options ): Rule {
  return ( _host: Tree, _context: SchematicContext ) => {
    return mergeWith( apply( url( 'path/to/app/root' ), [
      filter( ( path: Path ) => {
        // This will visit and check EVERY file in the directory
        return path === '/package.json';
      } ),
      move( '.', 'some/destination/path' ),
    ] ) );
  };
}
```

```ts
export function movePackage( _options: Options ): Rule {
  return ( _host: Tree, _context: SchematicContext ) => {
    return mergeWith( apply( url( 'path/to/app/root/*.json' ), [
      filter( ( path: Path ) => {
        // This will visit only .json files in the top level of the directory
        return path === '/package.json';
      } ),
      move( '.', 'some/destination/path' ),
    ] ) );
  };
}
```

The difference is that you are able to pass the `url` function a glob path to build a tree only based on the files that match that pattern. Then I could filter on a subset of files, rather than having schematics look through every file, including `node_modules` just to move the file(s) I want.
```diff
export function movePackage( _options: Options ): Rule {
  return ( _host: Tree, _context: SchematicContext ) => {
-    return mergeWith( apply( url( 'path/to/app/root' ), [
+    return mergeWith( apply( url( 'path/to/app/root/*.json' ), [
      filter( ( path: Path ) =>  path === '/package.json' ),
      move( '.', 'some/destination/path' ),
    ] ) );
  };
}
```

Currently, the `url` function calls the `createSourceFromUrl` method which ignores any glob path and creates a new null host tree. `createSourceFromUrl` could be refactored to return a tree of files only for a given glob path.

https://github.com/angular/angular-cli/blob/c5de8e3b0e5c1499a0a17da0208297cd82b36095/packages/angular_devkit/schematics/src/rules/url.ts#L12-L16

https://github.com/angular/angular-cli/blob/c5de8e3b0e5c1499a0a17da0208297cd82b36095/packages/angular_devkit/schematics/tools/file-system-engine-host-base.ts#L269-L283

> Through my research of this implementation I was unable to find any other way of achieving this. If someone has an idea other than this implementation that is currently supported, I would love to be enlightened. Thanks 👍

**Comment by clydin** [comment]
The filter rule is currently only intended to be used on a “Source”.  And a “Source” is intended to be a generally small set of files included with the schematic.  A node modules directory or other similar large directory structures should not exist in that scenario.

With that said, future additions are in the planning stages that should provide for improved performance and potential support of other use cases.

**Comment by nickofthyme** [comment]
FYI, I was able to achieve a nicer (faster) solution by using `Observable<tree>` based on this [article](https://medium.com/rocket-fuel/angular-schematics-asynchronous-schematics-dc998c0b6fba). Would still be nice to see this feature in the future.

## Example
```ts
function waitingRule(options: any): Rule {
    return (host: Tree) => {
        const observer = new Observable<Tree>((observer) => {
            fetch('someUrl.com/') // any async operation
                .then(res => res.json())
                .then(data => {
                    observer.next(host);
                    observer.complete();
                })
                .catch(function (err: any) {
                    observer.error(err);
                });
        });
        return observer;
    };
}
```

**Comment by mgechev** [comment]
@hansl suggests to use `apply(urls(), [filter()])` for the purpose. Let's close this feature requests since this behavior is already implemented.
