### ISSUE TITLE
ng serve is not working

### ISSUE THREAD

**Issue by js456** [angular/angular-cli#1347]
>ng serve is not working, Please help me to resolve this
> ---------------------------------------------------------------
1. Window 8.1

2. angular-cli: 1.0.0-beta.9
node: 4.4.7
os: win32 x64

3. I have run the following commands
$npm install -g angular-cli
$ng new myapp
$cd myapp
$ng serve

4.  angular-cli successfully installed.  

![serveerror](https://cloud.githubusercontent.com/assets/11023463/16848056/9ad18476-4a11-11e6-899d-5391068535a1.PNG)

**Comment by MrCroft** [comment]
In my case, if I do "npm install" again after "cd myapp" it will work.
Also, I usually update all @angular in package.json to "rc.4" and router to beta.2.
I thought I've seen this in an issue before, but I can't find it. Hopefully this will be fixed soon, so you don't have to "npm install" right after you've already waited 10 minutes for the CLI to finish.

**Comment by hansl** [comment]
It seems like there was a bug when creating the app that skipped the `npm install` step. Could you try with the latest beta (beta.10) and see if that fixes it? I cannot seem to be able to reproduce locally. Thanks.

**Comment by nikhilknoldus** [comment]
I was also facing this but not its resolved:
Put this line in package.json for start:

``` "start": "ng serve --host 0.0.0.0 --port 4201" ```
