### ISSUE TITLE
ng new processing stuck while creating new Angular 7 project

### ISSUE THREAD

**Issue by rajibhalder** [angular/angular-cli#13486]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Angular 7.1.3

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

While i am trying to build new Angular project using ng new command. The process stuck at the below point not proceeding , i waited more than 1 hour but still at the same place no procedding !

C:\Users\rajib>ng new my-app5
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE my-app5/angular.json (3777 bytes)
CREATE my-app5/package.json (1306 bytes)
CREATE my-app5/README.md (1023 bytes)
CREATE my-app5/tsconfig.json (435 bytes)
CREATE my-app5/tslint.json (2824 bytes)
CREATE my-app5/.editorconfig (246 bytes)
CREATE my-app5/.gitignore (587 bytes)
CREATE my-app5/src/favicon.ico (5430 bytes)
CREATE my-app5/src/index.html (293 bytes)
CREATE my-app5/src/main.ts (372 bytes)
CREATE my-app5/src/polyfills.ts (3571 bytes)
CREATE my-app5/src/test.ts (642 bytes)
CREATE my-app5/src/styles.css (80 bytes)
CREATE my-app5/src/browserslist (388 bytes)
CREATE my-app5/src/karma.conf.js (980 bytes)
CREATE my-app5/src/tsconfig.app.json (166 bytes)
CREATE my-app5/src/tsconfig.spec.json (256 bytes)
CREATE my-app5/src/tslint.json (314 bytes)
CREATE my-app5/src/assets/.gitkeep (0 bytes)
CREATE my-app5/src/environments/environment.prod.ts (51 bytes)
CREATE my-app5/src/environments/environment.ts (662 bytes)
CREATE my-app5/src/app/app.module.ts (314 bytes)
CREATE my-app5/src/app/app.component.html (1120 bytes)
CREATE my-app5/src/app/app.component.spec.ts (981 bytes)
CREATE my-app5/src/app/app.component.ts (211 bytes)
CREATE my-app5/src/app/app.component.css (0 bytes)
CREATE my-app5/e2e/protractor.conf.js (752 bytes)
CREATE my-app5/e2e/tsconfig.e2e.json (213 bytes)
CREATE my-app5/e2e/src/app.e2e-spec.ts (619 bytes)
CREATE my-app5/e2e/src/app.po.ts (204 bytes)
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
[            ......] | extract:rxjs: sill extract rxjs@~6.3.3 extracted to C:\Users\rajib\my-app5\node_modules\.staging\rxjs-b3aa93bf (15834ms)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.2.2
Node: 10.15.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.12.2
@angular-devkit/core         7.2.2
@angular-devkit/schematics   7.2.2
@schematics/angular          7.2.2
@schematics/update           0.12.2
rxjs                         6.3.3
typescript                   3.2.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by rajibhalder** [comment]
@alan-agius4 Sir,
Indeed you are right, it is not a problem with **Angular CLI** and i investigated and found not an issue with NPM also. What i found that my installed anti virus was the reason for which the problem was occuring. After disabling the anti virus for sometime, it worked as per expectation.

Thanks, I wanted to let the world know, how i resolved it so that it should save time for some awesome developer.

Happy Coding,
Rajib

**Comment by alan-agius4** [comment]
@rajibhalder, glad to hear that you fixed the issue :)

**Comment by rponline** [comment]
I also ran into this issue (using a different project) when having no internet connection or restricted internet access (e.g. public wifi hotspots or behind university visitors firewalls).

I guess it's connected with:
https://github.com/ReactiveX/rxjs/issues/4456

**Comment by vijaykanta** [comment]
This happens when there's a limited Internet connectivity or an Angular app already running on some port. Stop the app and check Internet connection. If both are good, go ahead and do this.

`ng new app-name`
`ng serve`
