### ISSUE TITLE
angular CLI doesn't install

### ISSUE THREAD

**Issue by ootsaruk** [angular/angular-cli#13498]
The command "npm install -g @angular/cli" stops installation.
Version Node.js 11.7.0 (x64).
The previous version in which this bug was not present was Node.js 11.6.0 on December, 2019.
<img width="678" alt="bug" src="https://user-images.githubusercontent.com/46933171/51549699-8c929600-1e73-11e9-9441-13200cbdfc0d.PNG">
What should i do to make it work?

**Comment by mgechev** [comment]
Looks like the installation passed successfully and now you're using version 7.2.2. If you hit any other issues, please follow the issue template and let us know what's your environment. Thanks!
