### ISSUE TITLE
Feature: Add a way to output lint result to a file

### ISSUE THREAD

**Issue by PodgeHeavin** [angular/angular-cli#13497]
# 🚀 Feature request

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 
ng lint --format=json > issues.json
Worked previously as describe here:  [#4959](https://github.com/angular/angular-cli/issues/4959)
Worked for outputting results to json or any format.

In Angular 7 there was the addition of color to the output of lint results. This has broken the above workaround for outputting to a file.

what was previously like:
```
[
    {
        "endPosition": {
            "character": 144,
            "line": 8,
            "position": 361
        },
        "failure": "Exceeds maximum line length of 140",
        "name": "C:/myProject/src/app/modeling.component.ts",
        "ruleName": "max-line-length",
        "ruleSeverity": "ERROR",
        "startPosition": {
            "character": 0,
            "line": 8,
            "position": 217
        }
    }
]
```

is now like so

```
[37m[
    {
        "endPosition": {
            "character": 144,
            "line": 8,
            "position": 361
        },
        "failure": "Exceeds maximum line length of 140",
        "name": "C:/myProject/src/spp/modeling.component.ts",
        "ruleName": "max-line-length",
        "ruleSeverity": "ERROR",
        "startPosition": {
            "character": 0,
            "line": 8,
            "position": 217
        }
    }
][39m
```

### Solution I would like
 I would like an option added to ng lint to output to a file easily

### Workaround
"ng lint --format=json | sed -r \\"s/\\\x1B\\\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g\\" > issues.json"
Which is ugly but works

**Comment by mgechev** [comment]
I'd approach similarly - just redirect stdout to a file. If you want to have a more "native" feel, I'd recommend you to implement a custom tslint formatter and update your configuration in `tslint.json`.

Although this feature seems useful in some specific scenarios, we need to be careful expanding the scope of the CLI with functionalities which have good pre-existing solutions.

I hope this helps! Thanks :)

**Comment by mgechev** [comment]
@alan-agius4 pointed out that this is a regression; reopening.

**Comment by alan-agius4** [comment]
@PodgeHeavin, I am unable to reproduce the issue.

Can you run `ng --version`?

**Comment by PodgeHeavin** [comment]
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.1.4
Node: 8.11.3
OS: win32 x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

**Comment by alan-agius4** [comment]
Kindly update to the latest version of packages mentioned above and see if you still encounter the issue.

**Comment by PodgeHeavin** [comment]
Issue persists. 

The issue is only present in bash/linux but not in windows CMD.
I am running the commands from git bash window


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 7.2.2
Node: 8.11.3
OS: win32 x64
Angular: 7.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@angular/cli                      7.2.2
@angular/language-service         7.2.0
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

**Comment by alan-agius4** [comment]
Hi, for git bash I suggest you use the `FORCE_COLOR` environment variable.

```cmd
FORCE_COLOR=0 ng lint --format=json > issues.json
```

**Comment by alan-agius4** [comment]
I removed the colors for the info, Git Bash is known to have some issues with colors. Though using `FORCE_COLOR=0` should have solved the issue.

**Comment by PodgeHeavin** [comment]
Thanks for this. Impressed with the turn around.

**Comment by mgechev** [comment]
@PodgeHeavin this should be part of 7.2.3 in an hour or so.
