### ISSUE TITLE
Add relevant css lint to generated project

### ISSUE THREAD

**Issue by kmturley** [angular/angular-cli#13502]
# 🚀 Feature request
### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
When running the command `ng new example-project` the user is prompted to select a css framework type. This is added to your project and you can quickly start development. However it does not add any quality standards/tests for css, scss, sass, less. This means either a project doesn't have consistent css standards or they have to be manually added later.

### Describe the solution you'd like
Automatically add the relevant css linting tool to the package.json

- https://www.npmjs.com/package/csslint
- https://www.npmjs.com/package/sass-lint
- https://www.npmjs.com/package/lesshint

And of course add the relevant command to package.json e.g.
```
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint && sass-lint",
    "e2e": "ng e2e"
  },
```

### Describe alternatives you've considered
Manually installing the library for every new project, or ensuring every developer has it installed in their Code Editor.

**Comment by mgechev** [comment]
@kmturley soon we're going to release new architect API which will let supporting CSS/Sass/Less linting through external plugins.

Although we'd prefer to keep this outside of the CLI, I'd love to collaborate on creating external builders which folks can add to their projects.

Here's the [new API](https://github.com/angular/angular-cli/pull/13463), you can also find sample builders there. Once we merge the PR, feel free to look at how you can create custom builders. If you hit any issues, feel free to reach out to me over email.

**Comment by kmturley** [comment]
sounds good, I think it's smart to allow anyone to make a modifier to angular cli projects. To append, change packages etc.

I wonder whether we can encourage package owners to create them, so that their packages are more easily added to Angular projects?

The reason being that if the base package changes, the modifier will likely need to be updated, so ideally by the same maintainer

**Comment by mgechev** [comment]
Yes, it'll be great if package maintainers have the bandwidth to provide CLI builders. This will definitely grow the popularity of their projects.
