### ISSUE TITLE
`ng g component --module` create component outside module directory

### ISSUE THREAD

**Issue by iget-master** [angular/angular-cli#13503]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No, this behavior occurs since older versions

### Description

When creating a component using generator, passing the module as parameter works, but the component is created outside module directory. IMO, the component should be created inside the module folder instead of app folder.

## 🔬 Minimal Reproduction

> $ ng g module test
> $ ng g component something --module test

This steps will create the following file structure (only new files shown): 

- app
  - test
    - test.module.ts
  - something
    - something.component.ts
    - something.component.html
    - something.component.scss
    - something.component.spec.ts
  

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.4
Node: 8.15.0
OS: linux x64
Angular: 7.1.4
... cli, common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, generated files get output in the current folder. If you want to emit the files in a different folder, you need to specify the path as part of the name example.

```
ng g c test/comp
```
