### ISSUE TITLE
ng-add easy support for libraries

### ISSUE THREAD

**Issue by rjlopezdev** [angular/angular-cli#13505]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

It is very common that when we generate a library, we want to add `ng-add` support, and it is tedious to have to configure it (in addition, __there is no or I have not found documentation__ to carry out the process).

### Describe the solution you'd like

Add a flag `--ng-add` to generate a library with a schematics project (with collection.json) and a default scehamtic `ng-add`.

__Example:__

`ng generate library <lib-name> --ng-add` : it generates a new library with a configuration described in __Describe the solution you'd like__

### Describe alternatives you've considered

If this is not possible, add a __step-by-step guide__ explaining how to configure it to the official documentation.

**Comment by alan-agius4** [comment]
Also relates to https://github.com/ng-packagr/ng-packagr/issues/1180

**Comment by mgechev** [comment]
@alan-agius4 should we keep track of this issue in `ng-packagr` or the CLI is the right place?

**Comment by alan-agius4** [comment]
@mgechev, if eventually ng-packagr supports this, we'd need to do some work in the schematics.

We can either;
1) Close this and when `ng-packagr` supports this feature (if it will) we can implement the schematics from our end.
2) Not dependent on `ng-packagr` to do this. As schematics transpilation can be done outside of ng-packagr.
3) keep this for reference.

**Comment by mgechev** [comment]
Thanks fort he quick follow up! Let's keep it.

**Comment by alan-agius4** [comment]
Hi @rjlopezdev, 

Thanks for this feature request. However, currently this is out of scope of Angular CLI. 

Let's revisit this in the future.
