### ISSUE TITLE
ng-serve wont compile even though file is available. Pseudofix (resave project)

### ISSUE THREAD

**Issue by Sy-D** [angular/angular-cli#13507]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] serve

```

### Is this a regression?

 I didnt test it in previous versions.

### Description
Whenever i reopen my Angular Project and run ng serve on it. My Project fails to compile because a interface couldn´t be located by a component eve when its located in that directory. 
A fix that i found is even though no change or anything else happend, is to save the interface again to force ng serve to recompile the project. This will start the project but still shows the same missing interface in the bash. 

 

## 🔬 Minimal Reproduction

Interface: in src/app/util/interfaces/breadcrumb.ts
<code>
export interface Breadcrumb {
    label: String;
    url: String;
}
</code>

This causes the Error in the Component: in src/app/features/portal/util/breadcrumb/...
VS Code itself is able to jump to the interface. 
<code>
import { Breadcrumb } from 'src/app/util/interfaces/breadcrumb';
</code>

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/features/portal/util/breadcrumb/breadcrumb.component.ts(4,28): error TS2307: Cannot find module 'src/app/util/interfaces/breadcrumb'.

ℹ ｢wdm｣: Failed to compile.
// Cmd+s (saving)
ℹ ｢wdm｣: Compiled successfully.

ERROR in src/app/features/portal/util/breadcrumb/breadcrumb.component.ts(4,28): error TS2307: Cannot find module 'src/app/util/interfaces/breadcrumb'.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.1.1
Node: 10.2.1
OS: darwin x64
Angular: 7.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.1
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.1
@angular-devkit/schematics        7.1.1
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.1
@schematics/update                0.11.1
rxjs                              6.3.3
</code></pre>

**Anything else relevant?**

 No.

**Comment by alan-agius4** [comment]
The import path seems to be incorrect.  You should import the other module relative to the module you are in.

Example 
```ts
// this is not correct still, as I don't don't know your folder structure.
import { Breadcrumb } from '../../../../app/util/interfaces/breadcrumb';
```

**Comment by Sy-D** [comment]
@alan-agius4 The import path is correct. The expected function works in the browser too after re-saving it. But it still shows the error and wont compile first whenever i reopen my project.

**Comment by alan-agius4** [comment]
Feel free to open a new file a with a minimal reproduction, as this might be something related to your folder structure.

Thank you.
