### ISSUE TITLE
CSS calculations do not work for inline animation delay on production build

### ISSUE THREAD

**Issue by mariusvlas** [angular/angular-cli#13518]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 It wasn't working on 7.0.7 either. Below that, I do not know.

### Description

 
When running `ng build --prod` (without the --prod tag it's working fine), css calculations cannot be used for the inline css animation delay, such as: 
`animation: animationName 0.2s calc(0.04s * 3) 1 linear backwards;` 
or
`animation: animationName 0.2s (0.04s * 3) 1 linear backwards;`
If using any of these , the whole line is just ignored and doesn't even appear in the css file that results from the build --prod command.

Setting the delay separately (`animation-delay: calc(0.04s * 3)`) works.

## 🔬 Minimal Reproduction

</code></pre>
@keyframes firstRowsAppear {
  0% {
    transform: translateY(-50px) scale(0.8, 0);
  }
}
some-element {
   display: flex;
  margin-top: 8px;
  animation: firstRowsAppear 0.3s calc(0.04s * 2) linear 1 backwards;

  // This works: 
  // animation: firstRowsAppear 0.3s 0s linear 1 backwards;
  // animation-delay: calc(0.04s * 2);
}
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.2.3
Node: 11.2.0
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.2.3
@angular/cli                      7.2.3
@ngtools/webpack                  7.0.7
@schematics/angular               7.2.3
@schematics/update                0.12.3
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Comment by mgechev** [comment]
Although according to Chrome DevTools `animation: animationName 0.2s calc(0.04s * 3) 1 linear backwards;` is valid.

**Comment by mariusvlas** [comment]
Thanks for the quick response.
I was missing the **direction** and **play-state**, which are optional. But I will try setting them, to see if they have any effect.

**Comment by alan-agius4** [comment]
During the builds it's warning you that this animation is being ignored 

```
WARNING in Invalid animation value at 6:51. Ignoring.
WARNING in Invalid animation value at 5:51. Ignoring.
```

This looks like a bug in cleancss, would you mind reporting it their issue tracker https://github.com/jakubpawlowicz/clean-css?

As a workaround I'd suggest you use the cleancss ignore markers. Ex
```css
  /* clean-css ignore:start */
  animation: firstRowsAppear 0.3s linear calc(0.04s * 3) backwards;
  /* clean-css ignore:end */
```

**Comment by mariusvlas** [comment]
Will report it on the clean-css repo. Thanks!
