### ISSUE TITLE
IE: ERROR TypeError: Uncaught (in promise)

### ISSUE THREAD

**Issue by mohammad-shadmehr** [angular/angular-cli#13519]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
**Versions:**
"@angular/cli": "^1.6.8",
"@angular/compiler-cli": "^5.2.5",
"@angular/animations": "^5.2.5",
"@angular/common": "^5.2.5",
"@angular/compiler": "^5.2.5",
"@angular/core": "^5.2.5",
"@angular/forms": "^5.2.5",
"@angular/http": "^5.2.5",
"@angular/platform-browser": "^5.2.5",
"@angular/platform-browser-dynamic": "^5.2.5",
"@angular/router": "^5.2.5",

### Is this a regression?

 Not quite sure!

### Description

 
I have an Angular 4 project. It used to work work fine in both Chrome and IE (Edge, 10, 11) till I ran the `ng-build --prod` for the first time to deploy it on the server. Since then the app is breaking in all of the IE versions, but still works fine in Chrome. I traced the bug and narrowed it down to the following function:

```
  init(): Promise<boolean> {
        return new Promise<boolean>((resolve, reject) => {
            this._sessionService.getCurrentLoginInformations().toPromise().then((result: GetCurrentLoginInformationsOutput) => {
                this._application = result.application;
                this._user = result.user;
                this._tenant = result.tenant;
                resolve(true);
            }, (err) => {
                reject(err);
            });
        });
    }
```
The issue is that in IE nothing is getting populated for neither of the result variable properties. but again all is good when running it in Chrome! 
Do I need to refactor the above code some how to make it digestible for IE?

Note: In the error below the 'version' is a property for the 'application' property of the 'GetCurrentLoginInformationsOutput'

Not quite sure if it relevants but I also get the following prompt in IE console:

> Could not locate webpack:///(webpack)-dev-server/client* specified in source map 

## 🔥 Exception or Error
<pre><code>

[object Error]: {description: "Uncaught (in promise): TypeError: Unable to get property 'version' of undefined or null reference TypeError: Unable to get property 'version' of undefined or null reference at AccountComponent (eval code:31:9) at createClass (eval code:12653:13) at createDirectiveInstance (eval code:12496:5) at createViewNodes (eval code:13954:21) at createRootView (eval code:13843:5) at callWithDebugContext (eval code:15268:9) at debugCreateRootView (eval code:14551:5) at ComponentFactory_.prototype.create (eval code:11448:9) at ComponentFactoryBoundToModule.prototype.create (eval code:4235:9) at ViewContainerRef_.prototype.createComponent (eval code:11645:9)", message: "Uncaught (in promise): TypeError: Unable to get property 'version' of undefined or null reference TypeError: Unable to get property 'version' of undefined or null reference at AccountComponent (eval code:31:9) at createClass (eval code:12653:13) at createDirectiveInstance (eval code:12496:5) at createViewNodes (eval code:13954:21) at createRootView (eval code:13843:5) at callWithDebugContext (eval code:15268:9) at debugCreateRootView (eval code:14551:5) at ComponentFactory_.prototype.create (eval code:11448:9) at ComponentFactoryBoundToModule.prototype.create (eval code:4235:9) at ViewContainerRef_.prototype.createComponent (eval code:11645:9)", promise: Object, rejection: Object, stack: "Error: Uncaught (in promise): TypeError: Unable to get property 'version' of undefined or null reference TypeError: Unable to get property 'version' of undefined or null reference at AccountComponent (eval code:31:9) at createClass (eval code:12653:13) at createDirectiveInstance (eval code:12496:5) at createViewNodes (eval code:13954:21) at createRootView (eval code:13843:5) at callWithDebugContext (eval code:15268:9) at debugCreateRootView (eval code:14551:5) at ComponentFactory_.prototype.create (eval code:11448:9) at ComponentFactoryBoundToModule.prototype.create (eval code:4235:9) at ViewContainerRef_.prototype.createComponent (eval code:11645:9) at resolvePromise (eval code:824:25) at resolvePromise (eval code:795:17) at Anonymous function (eval code:873:17) at ZoneDelegate.prototype.invokeTask (eval code:423:13) at onInvokeTask (eval code:4952:17) at ZoneDelegate.prototype.invokeTask (eval code:423:13) at Zone.prototype.runTask (eval code:192:21) at drainMicroTaskQueue (eval code:602:25) at ZoneTask.invokeTask (eval code:503:21) at invokeTask (eval code:1540:9)"...}

description: "Uncaught (in promise): TypeError: Unable to get property 'version' of undefined or null reference TypeError: Unable to get property 'version' of undefined or null reference at AccountComponent (eval code:31:9) at createClass (eval code:12653:13) at createDirectiveInstance (eval code:12496:5) at createViewNodes (eval code:13954:21) at createRootView (eval code:13843:5) at callWithDebugContext (eval code:15268:9) at debugCreateRootView (eval code:14551:5) at ComponentFactory_.prototype.create (eval code:11448:9) at ComponentFactoryBoundToModule.prototype.create (eval code:4235:9) at ViewContainerRef_.prototype.createComponent (eval code:11645:9)"
message: "Uncaught (in promise): TypeError: Unable to get property 'version' of undefined or null reference TypeError: Unable to get property 'version' of undefined or null reference at AccountComponent (eval code:31:9) at createClass (eval code:12653:13) at createDirectiveInstance (eval code:12496:5) at createViewNodes (eval code:13954:21) at createRootView (eval code:13843:5) at callWithDebugContext (eval code:15268:9) at debugCreateRootView (eval code:14551:5) at ComponentFactory_.prototype.create (eval code:11448:9) at ComponentFactoryBoundToModule.prototype.create (eval code:4235:9) at ViewContainerRef_.prototype.createComponent (eval code:11645:9)"

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, I am not quite sure where the problem is since we don't have a reproduction.  I also suggest to update to the latest versions of the Angular and Angular CLI to the latest version.

I'm sorry, but we can't reproduce the problem with the instructions you provided. Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue. Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
