### ISSUE TITLE
Issue with including underscore.js using wiki doc

### ISSUE THREAD

**Issue by xcompass** [angular/angular-cli#1352]
Hi,

I was trying to include underscore using the doc on wiki: https://github.com/angular/angular-cli/wiki/3rd-party-libs#adding-underscore-library-to-your-project

I got an exception in console:  ReferenceError: _ is not defined. It was trigger at the place where the underscore function is called.

I traced down the problem that it was due to underscore.js was not loaded into the browser automatically. 

However, if I use 
```
import * as _ from 'underscore';
```
instead of 
```
declare var _;
```
I was able to successfully load underscore.js and use it.

I think import will trigger systemjs auto load library. And when type definition file is available, import should be used. Otherwise, declare can be used but it requires manually load the library itself. Maybe wiki should be updated.

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.9
node: 5.3.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Followed the steps on wiki:  https://github.com/angular/angular-cli/wiki/3rd-party-libs#adding-underscore-library-to-your-project

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
