### ISSUE TITLE
source map flag as generated by beta cli fails to build

### ISSUE THREAD

**Issue by vmasek** [angular/angular-cli#13527]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

Config flag is new to the `7.3.0-beta-0`

### Description

I'm trying the `"sourceMap": false"` option at universal project. 
Problem is that when I add `sourceMap` flag, the `ng build` will fail.

## 🔬 Minimal Reproduction

It also happens on a project generated by CLI 7.3.0-beta.0
`ng new test && ng g universal --clientProject=test`

## 🔥 Exception or Error

```
Schema validation failed with the following errors:
  Data path "['server']" should NOT have additional properties(sourceMap).
```

## 🌍 Your Environment
```
Angular CLI: 7.3.0-rc.0
Node: 10.14.0
OS: linux x64
Angular: 7.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.3
@angular-devkit/build-angular     0.12.3
@angular-devkit/build-optimizer   0.12.3
@angular-devkit/build-webpack     0.12.3
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.3.0-rc.0
@angular/cli                      7.3.0-rc.0
@ngtools/webpack                  7.2.3
@schematics/angular               7.3.0-rc.0
@schematics/update                0.13.0-rc.0
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
```

![angular json-server-sourcemap-flag](https://user-images.githubusercontent.com/7274335/51790782-d9d77600-2199-11e9-9742-64f6c0336cc5.png)

**Comment by alan-agius4** [comment]
Hi, `sourceMap` should be in `options` should be in `options`.
