### ISSUE TITLE
how resolve unchanged chunks angular cli

### ISSUE THREAD

**Issue by jsdiaz19** [angular/angular-cli#13535]
when i run command 'npm start', its dont excetue the lastest changes and the console show this:

7 unchanged chunks
chunk {main} main.js, main.js.map (main) 73.7 kB [initial] [rendered]
i ｢wdm｣: Compiled successfully.

¿what mean unchanged chunks?
with this error, i cant work

**Comment by alan-agius4** [comment]
Closing as it doesn’t follow the template.
