### ISSUE TITLE
Configuration to exclude few modules while building

### ISSUE THREAD

**Issue by Asif905** [angular/angular-cli#13537]
**Versions**
Angular 7

**Observed behavior**
modules are not getting excluded while building

**Desired behavior**
Is there any way to exclude few modules while building the app...?

**Mention any other details that might be useful (optional)**
I tried to conditionally import basic and advanced module, but still I am getting Basic and Advanced module code in the main.js. 

let advanced = [AdvancedModule];

if (environment.name === 'basic') {
  advanced = [];
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    DiagnosticsModule,
    applicationRoutingInformation,
    CoreModule,
    ...advanced
  ],
  providers: [
    { provide: LocationStrategy, useClass: MiPathLocationStrategy }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
