### ISSUE TITLE
Unable to load bootstrap styles

### ISSUE THREAD

**Issue by gayathri-amirineni** [angular/angular-cli#13547]
I have added bootstrap to Angular Project using: 
npm install --popper.js
npm install --jquery.js
npm install --bootstrap
--> It is added in the angular.json file as:
"styles": [
              "src/assets/css/styles.css",
              "./node_modules/bootstrap/dist/css/bootstrap.min.css"
            ]
and also in package.json as:
"dependencies": {
"bootstrap": "^4.2.1"
}

But my bootstrap classes like .btn .btn-primary, .form-group, .form-control are not working. Please help me with this. As our project is complex and needed to be loaded faster, please suggest me a solution that doesn't take longer loading time. (That means without imports/plugins inside the html or css files)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
