### ISSUE TITLE
Uncaught (in promise): TypeError: ctor is not a constructor

### ISSUE THREAD

**Issue by krojew** [angular/angular-cli#13540]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Can't tell.

### Description

When running an application built in prod mode `ng build --prod` _some_ components cannot be instantiated because of `TypeError: ctor is not a constructor`. This is a continuation of https://github.com/angular/angular-cli/issues/9929

## 🔬 Minimal Reproduction

1. Clone https://github.com/krojew/angular-cli-bug-13540
1. run ng build --prod
1. Launch app in the browser and witness the error.

## 🔥 Exception or Error
<pre><code>
TypeError: ctor is not a constructor
    at createClass (core.js.pre-build-optimizer.js:22052)
    at createDirectiveInstance (core.js.pre-build-optimizer.js:21931)
    at createViewNodes (core.js.pre-build-optimizer.js:23157)
    at callViewAction (core.js.pre-build-optimizer.js:23473)
    at execComponentViewsAction (core.js.pre-build-optimizer.js:23392)
    at createViewNodes (core.js.pre-build-optimizer.js:23185)
    at callViewAction (core.js.pre-build-optimizer.js:23473)
    at execComponentViewsAction (core.js.pre-build-optimizer.js:23392)
    at createViewNodes (core.js.pre-build-optimizer.js:23185)
    at createRootView (core.js.pre-build-optimizer.js:23071)
    at resolvePromise (zone.js.pre-build-optimizer.js:831)
    at resolvePromise (zone.js.pre-build-optimizer.js:788)
    at zone.js.pre-build-optimizer.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js.pre-build-optimizer.js:423)
    at Object.onInvokeTask (core.js.pre-build-optimizer.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js.pre-build-optimizer.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js.pre-build-optimizer.js:195)
    at drainMicroTaskQueue (zone.js.pre-build-optimizer.js:601)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.2.2
Node: 10.15.0
OS: linux x64
Angular: 7.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@angular/cli                      7.2.2
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by krojew** [comment]
Unfortunately, I cannot reproduce on a minimal setup. Simple component using this package seems to work, so it might be a combination of some things.

Nevertheless, there definitely is an issue there which prevents building in prod mode.

**Comment by krojew** [comment]
Wrong diagnosis - the issue was with angular-resize-event package in version 0.4.4. Upgrading to 1.0.0 makes the issue go away. Will try to provide a repro repo.

**Comment by krojew** [comment]
Here you go: https://github.com/krojew/angular-cli-bug-13540

1. run `ng build --prod`
1. Launch app in the browser and witness the error.

**Comment by mgechev** [comment]
@krojew thank you for looking into this; it's really helpful! Looking at the [commit log](https://github.com/vdolek/angular-resize-event/commit/6e2a58a6305005e093d682d0dec2bc9995c3ade4) of `angular-resize-event`, looks like 0.4.4 did not support latest Angular.

There are a lot of changes there, hard to trace what exactly fixed the problem, but looks like an issue in `angular-resize-events`.

Again, thanks for looking into this!

**Comment by krojew** [comment]
It would be great if Angular managed to catch these error at build time. It's really confusing to have everything working perfectly when developing, just to have it blow up as soon as prod build gets deployed.

**Comment by suvarna-tammina** [comment]
Still I see the error when I do ng build --prod. All router navigations are working fine but in one component the router navigation is not working and throwing the below error. If anyone could help me please. 
![image](https://user-images.githubusercontent.com/21304003/58015103-0253f900-7b18-11e9-98fb-93ba41cbb929.png)

**Comment by guybi** [comment]
@suvarna-tammina  +1

**Comment by krojew** [comment]
@mgechev I just got hit with a this bug on production. Here you have reproduction scenario: https://github.com/angular/angular-cli/issues/9929#issuecomment-490210407 - can somebody take a look?

**Comment by mgechev** [comment]
@krojew where's the reproduction? I cant find steps in the comment you're pointing to.

**Comment by krojew** [comment]
@mgechev install angular-resize-event 0.4.4 and it will cause this error when used in prod mode.
