### ISSUE TITLE
@ngtools/webpack adds ./ to resource when using additional loader

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular-cli#13559]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No
### Description

 A clear and concise description of the problem...
When you add extra loader to component template like this:
```typescript
@Component({
  templateUrl: 'my-loader!./my.component.html',
})
export class MyComponent {}
```
Webpack build fails because transformer adds ./ in the beginning and webpack cannot resolve "./my-loader!./my.component.html"

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-hgudjb?file=src%2Fapp%2Fapp.component.ts

## 🔥 Exception or Error
<pre><code>Module not found: Error: Can't resolve './raw-loader' in 'my.component.ts'</code></pre>

**Comment by filipesilva** [comment]
I'm sorry but we don't support adding webpack loaders for in `templateUrl`. This isn't a feature we have, and it's not something we intend to add.

If you need to do this I recommend you use https://github.com/manfredsteyer/ngx-build-plus and add extra loaders for html in the webpack configuration instead.
