### ISSUE TITLE
Compiler do not see module / ng-packagr lib

### ISSUE THREAD

**Issue by ZBAGI** [angular/angular-cli#13561]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Previous behavior is unknown to me.

### Description

I have made library with Angular CLI. Everything compiles like it should, all files are visible inside `dist` folder and they even work correctly when imported via lib. name.
```ts
import { ExampleModule, SecondaryModule } from "example-lib-name";
```
But when i trying to import it directly from a folder (just to keep my imports more precised) 
```ts
import { ExampleModule} from "example-lib-name";
import { SecondaryModule } from "example-lib-name/subfolder";
```
i getting error about missing module despite file being where it should. ( detailed message bellow )
Visual Studio doesn't complain about missing files, in fact you can without any problem navigate into it by clicking on import path.

I got the same error when importing that created package via npm. Attempts to include files via `tsconfig` options `include` and `files` also didn't change anything. 

## 🔬 Minimal Reproduction
Generate new project by executing:
```bash
ng new example-lib-app &&
cd example-lib-app &&
ng generate library example-lib-name --prefix=eln &&
cd ./projects/example-lib-name/src/lib &&
ng g module secondaryModule &&
cd .. &&
echo "export * from './lib/secondary-module/secondary-module.module';" >> ./public_api.ts &&
cd ../../../ &&
cd ./src/app &&
npm install typescript@2.8.4 &&
ng build example-lib-name --prod &&
sed "5 i\import { SecondaryModuleModule } from 'example-lib-name/lib/secondary-module/secondary-module.module';" app.module.ts | tee app.module.ts &&
sed "13 i\ , SecondaryModuleModule" app.module.ts | tee app.module.ts &&
ng serve
```
Or clone and `ng serve` project from:
<pre><code>https://github.com/ZBAGI/example-lib-name-bug.git</code></pre>

## 🔥 Error
<pre><code>
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve 'D:\Projects\test\example-lib-app\dist\example-lib-name\lib\secondary-module\secondary-module.module' in 'D:\Projects\test\example-lib-app\src\app'
</code></pre>

## 🌍 Your Environment
Visual Studio Code 1.28.1
```
Angular CLI: 6.1.5
Node: 8.9.2
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.7.5
@angular-devkit/core         0.7.5
@angular-devkit/schematics   0.7.5
@schematics/angular          0.7.5
@schematics/update           0.7.5
rxjs                         6.3.2
typescript                   2.9.2
```
```json
"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0",
    "@angular-devkit/build-ng-packagr": "~0.7.0",
    "@angular/cli": "~6.1.5",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-packagr": "^3.0.0",
    "protractor": "~5.4.0",
    "ts-node": "~5.0.1",
    "tsickle": ">=0.29.0",
    "tslib": "^1.9.0",
    "tslint": "~5.9.1",
    "typescript": "^2.8.4"
  }
```

**Comment by alan-agius4** [comment]
Hi, this is working as intended, as deep imports are not allowed https://github.com/ZBAGI/example-lib-name-bug/blob/master/src/app/app.module.ts#L5 when using a library.

You can only access you library via `import { ... } from 'example-lib-name';` or if you have secondary entrypoint  `import { ... } from 'example-lib-name/secondary';` 

See https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
