### ISSUE TITLE
Difference between ng build and npm run build

### ISSUE THREAD

**Issue by mdufoud1214** [angular/angular-cli#13560]
am using angular 7 and server side using` .net core 2.1`
if i do` npm run build --prod --aot` my dist folder size is around `40mb `and my application working as expected,
 but if i do `ng build --prod --aot `my dist folder size is reducing  to around `9mb` but am not able to run applications some map files are missing getting 404 error(find below screenshot)

i want reduce my bundle size to improve my angular app performance

![image](https://user-images.githubusercontent.com/47215098/52063198-248d2f80-2598-11e9-9662-78ca6d30409d.png)

**Comment by alan-agius4** [comment]
You need to use `—` to pass arguments to npm scripts.
`npm run build — —prod`

**Comment by mdufoud1214** [comment]
@alan-agius4 `npm run build —- —-prod` it is working as expected , it is reducing dist folder size and application is running ,but where to add this in `package.json` file

` "build-watch": "../@angular/cli/bin/ng build --deploy-url=dist/ --output-hashing all --watch",`

**Comment by rakotomandimby** [comment]
Hi, I faced the same issue when having to specify the "base-href" parameter, and the double dash was the solution!
https://mihamina.rktmb.org/2019/04/npm-run-build-base-href.html
