### ISSUE TITLE
ng doc does not open the documentation in the browser.

### ISSUE THREAD

**Issue by DeborahK** [angular/angular-cli#13575]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Typing `ng doc xxx` does not do anything. It does not generate an error and does not open the browser to the documentation.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.2.3
Node: 10.15.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.12.3
@angular-devkit/core         7.2.3
@angular-devkit/schematics   7.2.3
@schematics/angular          7.2.3
@schematics/update           0.12.3
rxjs                         6.3.3
typescript                   3.2.2

</code></pre>

**Anything else relevant?**

**Comment by mgechev** [comment]
FYI https://twitter.com/yurzui/status/1091429457381019648?s=19

**Comment by wKoza** [comment]
@mgechev , indeed, it doesn't work. I'll investigate...

**Comment by wKoza** [comment]
So, Windows seems to be not fast enough for open the browser...
We have to use the `wait: true,` property but, unfortunately, we must define the browser.  Which browser could we take ? Chrome ?
cc @alan-agius4 @mgechev

**Comment by alan-agius4** [comment]
@wKoza, let's take this in the PR that you opened.
