### ISSUE TITLE
angular cli override scss variables with library not work 

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular-cli#13579]
# 🐞 Bug report

### Description
I want to be able to override scss variables that declared in a library from the main project.

I created a new Angular CLI project and then I generate a library called sol-lib.
inside the sol-lib I created a new component TestComponent with some text.
the TestComponent using scss file which gives color to the component text
I'm using this component from the main project and I want to override the color from red to green.

## library SCSS files

styles.scss
```
$primary: red !default;
```
test.component.scss
```
@import "../../styles";
.text{
  color: $primary;
}

```
## main project

styles.scss
```
$primary: green;
@import "../projects/sol-lib/src/styles.scss";
```
the expected behavior 
text color shold be green and not red.

## My Code
[stackblitz exmple](https://stackblitz.com/github/ofirrifo/angular-cli-override-scss-varibales?file=projects%2Fsol-lib%2Fsrc%2Fstyles.scss)

[GitHub code](https://github.com/ofirrifo/angular-cli-override-scss-varibales)

## 🔬 Minimal Reproduction
<!--
Simple steps to reproduce this bug.

Just open the stackblitz example
[stackblitz example](https://stackblitz.com/github/ofirrifo/angular-cli-override-scss-varibales?file=projects%2Fsol-lib%2Fsrc%2Fstyles.scss)

[GitHub code](https://github.com/ofirrifo/angular-cli-override-scss-varibales)

**Comment by ahasall** [comment]
Hi @ofirrifo,

This is not a problem with the Angular CLI.

When you compile your Sass code to CSS, you will have this:
test.component.css
```css
.text {
  color: red;
}
```
styles.css
```css
// empty because, there is not CSS declaration in the files imported.
```

**Comment by alan-agius4** [comment]
That is indeed correct.

Style in libraries gets transformed into CSS when building a library. A library doesn't have context of the application style.

If you want to provide a way for your components to be themed from an application, you need to create mixins. Similar to Angular Material https://github.com/angular/material2/blob/master/src/lib/badge/_badge-theme.scss however, you'd need to take care of bundle the theme file yourself.

see https://github.com/ng-packagr/ng-packagr/issues/273
