### ISSUE TITLE
ng add error

### ISSUE THREAD

**Issue by code-hero** [angular/angular-cli#13586]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

when I use `ng add `   console display error  `The specified command add is invalid. For available options, see `ng help`.`
what should I do?

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Closing as template is not followed.
