### ISSUE TITLE
ng update does not check or update @angular-devkit packages

### ISSUE THREAD

**Issue by rhino5oh** [angular/angular-cli#13581]
I have angular CLI 7.3.0.  According to the release description [here](https://github.com/angular/angular-cli/releases/tag/v7.3.0), This release also involved releasing `@angular-devkit/build-angular 0.13.0`.  

As you can see in my screenshot below, I have @angular-devkit/build-angular, @angular-devkit/architect, @angular-devkit/build-optimizer, @angular-devkit/build-webpack all at version 0.10.2.

I then do an `ng update`, and the CLI tells me that everything is in order.  Why?  Shouldn't it tell me that I need to update all of the previously mentioned packages to 0.13.0?  

Or better yet, shouldn't those packages automatically update when I do an `ng update @angular/cli`?  That is the command I did to update to CLI 7.3.0, and the @angular-devkit packages did not update

![screenshot](https://user-images.githubusercontent.com/4404630/52168085-5ff04100-26f3-11e9-8d44-69bd3bd70d0c.png)

**Comment by dottodot** [comment]
Even if you manually update `@angular-devkit/build-angular` to the lastest version `ng update @angular/cli` removes it and installs `0.10.0`

**Comment by web-dave** [comment]
just ran into this.
I fixed it like this:
```shell
npm i @angular-devkit/build-angular@0.13.5 @angular-devkit/build-ng-packagr@0.13.5
```
and all your apps `"projectType": "application"`
need this config: (`architect.build.options`)
```json
"es5BrowserSupport": true
```

CLI version 7.3.4
