### ISSUE TITLE
conventional-changelog support

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#1358]
I think it would be good to include `conventional-changelog` with generated projects to make generating CHANGELOG.md easy for all things generated with angular-cli. To enforce small components to be versioned, follow angular-style commits and have changelogs.

I can PR this if people feel that it belongs in an angular-cli generated project (although didn't see a Broccoli adapter for it)

**Comment by filipesilva** [comment]
Personally I think it's up to the user to add this, but let's leave the issue open for a bit to see people's opinions.

**Comment by hansl** [comment]
We won't do anything to support it; addons will probably be our answers.
