### ISSUE TITLE
Barrel generation options

### ISSUE THREAD

**Issue by Crackroach** [angular/angular-cli#13590]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
It would be a great feature to have the possibility to add the newly generated component|class|service|... to a barrel file when using the ng generate <c|s|class|...>.

### Describe the solution you'd like
The barrel exportation could be an option that is defaulted to false. The exportation would be in the module of the generated item if any index.ts file is present:
##### The folder diagram
```

o
| --core
|   | --core.module.ts
|   | --index.ts  // core module's barrel
|   | --services
|   `-- models
|-- pages
|   |-- pages.module.ts
|   |-- index.ts // pages module's barrel
|   |-- dashboard
|   |   |-- dashboard.module.ts
|   |   `-- index.ts  // dashboard module's barrel. 
|    | `-- about
|       |-- about.module.ts // This module doesn't have any barrel
|       `-- about // about component folder is exported in index.ts of about module's barrel
    `-- shared // more folder for style
```

##### Generating a module with barrels enabled
```
ng g m pages/about
```
Generate a module without any barrels in it. If the user had specified `-b` an `index.ts` file would have been created.

##### Generating a new service with the shorthand syntax
```
ng generate service core/services/myService -b
```
This generate a new service named MyService and it is exported in the "closest" relative module. That means that the `index.ts` is in the core folder

##### Generating a new component with the long syntax
```
ng generate component pages/dashboard/dash --barrel
```
This generate a new component named DashComponent in the "closest" relative module. That means that the `index.ts` is in the dashboard folder.

##### Generating a new component that has no barrel 
```
ng generate component /pages/about/me -b
```
This still generate the component, but does not add anything to any barrel because the module it belongs to doesn't have one

##### Generating a new component that has no barrel 
```
ng generate component /pages/about/me -b=pages
```
This generate a new component named MeComponent in specified module. That means that the `index.ts` is in the pages folder.

### Describe alternatives you've considered
There is currently a library doing this: https://www.npmjs.com/package/barrelsby, but we have to run a separate command everytime we create a new item, a lot of configuration is needed as well and there is a devDependency.

**Comment by mgechev** [comment]
@Crackroach this sounds like a useful feature, in the same time we should be careful how we increase the scope of the CLI because each new feature means new code to maintain and fix issues in.

In this particular case, since barrel files are no longer part of the style guide, I'd suggest to hold this off for now and revisit in future.

Let's reopen if more folks need such generator.
