### ISSUE TITLE
Add a TSLint config to the default init

### ISSUE THREAD

**Issue by jelbourn** [angular/angular-cli#136]
The default project structure should have a TSLint file. It would probably have a minimal number of rules actually set, though.

**Comment by Gillespie59** [comment]
Do you have any basic TSLint config working fine with angular2 app  ?

**Comment by jelbourn** [comment]
You probably just want the output of `tslint --init` as a starting point and can customize it later as best practices develop.

**Comment by Gillespie59** [comment]
OK I will use this default config

**Comment by Gillespie59** [comment]
And should we add out-of-the-box command defined in package.json ? Or a new CLI command `ng lint` ? or let the user install tslint on his own ?
