### ISSUE TITLE
Access to XMLHttpRequest at 'https://api.github.com/repos/TechBlocksInc/Evaluation/issues' from origin 'http://localhost:4200' has been blocked by CORS policy.

### ISSUE THREAD

**Issue by Shripad03** [angular/angular-cli#13603]
Hi Folks,
   i am trying to add some issue to Github public repository but while adding browser is giving me CORS error. Please suggest the way to handle this.
![error](https://user-images.githubusercontent.com/41938325/52360250-96b2b800-2a61-11e9-9d52-14cb220f0090.png)

**Comment by Shripad03** [comment]
:4200/#/issue-list/add-issue:1 Access to XMLHttpRequest at 'https://api.github.com/repos/TechBlocksInc/Evaluation/issues' from origin 'http://localhost:4200' has been blocked by CORS policy: Request header field access-control-allow-origin is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
