### ISSUE TITLE
Date is converting automatically before hitting web api 

### ISSUE THREAD

**Issue by mdufoud1214** [angular/angular-cli#13601]
am using angular 7, if i save `02/06/2019 `date .till my service.ts file it is going same date after hitting web api it is taking` 02/05/2019` past date . i observed in browser network only it is converted.

am saving Utc date format in database.

while getting i converted utc date to local date in c# but still past date am getting. How to handle this time zone?

**Comment by mdufoud1214** [comment]
am using angular 7, if i save `02/06/2019 `date .till my service.ts file it is going same date after hitting web api it is taking` 02/05/2019` past date . i observed in browser network only it is converted.

am saving Utc date format in database. 

while getting i converted date to Utc format in c# but still past date am getting. How to handle this time zone?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
