### ISSUE TITLE
WARNING in ./src/assets/scss/style.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js 

### ISSUE THREAD

**Issue by karamjeetiron** [angular/angular-cli#13610]
Hi,

I updated the packages and after starting npm i got 2 warning which are follows:

WARNING in ./src/assets/scss/style.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/style.scss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(4278:3) end value has mixed support, consider using flex-end instead

WARNING in ./src/assets/scss/style.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/style.scss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(4283:3) end value has mixed support, consider using flex-end instead

I want fix for this and following is my package.json file

"dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "^7.2.3",
    "@angular/cdk": "^7.3.1",
    "@angular/common": "^7.2.4",
    "@angular/compiler": "^7.2.4",
    "@angular/core": "^7.2.4",
    "@angular/fire": "^5.1.1",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.4",
    "@angular/http": "^7.2.4",
    "@angular/material": "^7.3.1",
    "@angular/platform-browser": "^7.2.4",
    "@angular/platform-browser-dynamic": "^7.2.4",
    "@angular/platform-server": "^7.2.4",
    "@angular/router": "^7.2.4",
    "@nguniversal/express-engine": "^7.1.0",
    "@nguniversal/module-map-ngfactory-loader": "^7.1.0",
    "@ngx-cache/core": "^7.0.0",
    "@ngx-loading-bar/core": "^2.2.0",
    "@ngx-loading-bar/router": "^4.1.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-instantsearch": "^2.1.0",
    "card": "^2.4.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.3",
    "firebase": "^5.8.2",
    "hammerjs": "^2.0.8",
    "jquery": "^3.3.1",
    "ng2-toasty": "^4.0.3",
    "ngx-bar-rating": "^1.1.0",
    "ngx-card": "^0.2.4",
    "ngx-slick-carousel": "^0.4.4",
    "ngx-toasta": "^0.1.0",
    "path": "^0.12.7",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "slick-carousel": "^1.8.1",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.0",
    "@angular/cli": "^7.3.0",
    "@angular/compiler-cli": "^7.2.4",
    "@angular/language-service": "^7.2.4",
    "@types/jasmine": "^3.3.8",
    "@types/jasminewd2": "^2.0.6",
    "@types/jquery": "^3.3.29",
    "@types/node": "^10.12.21",
    "codelyzer": "^4.5.0",
    "copy-webpack-plugin": "^4.6.0",
    "express": "^4.16.4",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.6",
    "ts-loader": "^5.3.3",
    "ts-node": "^8.0.2",
    "tslint": "^5.12.1",
    "typescript": "3.1.1",
    "webpack-cli": "^3.2.3",
    "ws": "^6.1.3",
    "xmlhttprequest": "^1.8.0"
  }

Hope this will help to resolve.

Thanks

**Comment by alan-agius4** [comment]
Kindly see https://github.com/angular/angular-cli/issues/13550

**Comment by karamjeetiron** [comment]
Thanks

**Comment by karamjeetiron** [comment]
Unable to fix this issue. Please help
