### ISSUE TITLE
styles.sass missing

### ISSUE THREAD

**Issue by niwrA** [angular/angular-cli#13612]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] new

### Is this a regression?

I haven't tested choosing sass with older versions

### Description

When creating a new project, and choosing sass for styling, ng server will fail with the message can't find src/styles.sass

## 🔬 Minimal Reproduction
Create new project and choose sass as style option
ng serve

## 🔥 Exception or Error
<pre><code>
ERROR in multi ./src/styles.sass
Module not found: Error: Can't resolve 'C:\someproject\src\styles.sass' in 'C:\someproject'
</code></pre>

## 🌍 Your Environment
I got here just after updating the cli to the latest version. I did an ng add material after the above to see if that worked, but it didn't change anything.

<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.0
@angular-devkit/build-angular     0.13.0
@angular-devkit/build-optimizer   0.13.0
@angular-devkit/build-webpack     0.13.0
@angular-devkit/core              7.3.0
@angular-devkit/schematics        7.3.0
@angular/cdk                      7.3.1
@angular/cli                      7.3.0
@angular/material                 7.3.1
@ngtools/webpack                  7.3.0
@schematics/angular               7.3.0
@schematics/update                0.13.0
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by niwrA** [comment]
The workaround is pretty simple by the way. Just add an empty styles.sass manually. But wanted to mention it regardless.

**Comment by wKoza** [comment]
duplicate #13550 and resolved by #13552
