### ISSUE TITLE
Version resolution issue

### ISSUE THREAD

**Issue by barrychapman** [angular/angular-cli#13617]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [X] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 First time trying

### Description

 
Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "7.0.0".

## 🔬 Minimal Reproduction

Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "7.0.0".
Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "7.0.0".
    at Object.CompilerCliIsSupported (D:\Projects\ecp\node_modules\@ngtools\webpack\src\ngtools_api.js:40:15)
    at new AotPlugin (D:\Projects\ecp\node_modules\@ngtools\webpack\src\plugin.js:28:23)
    at Object.exports.getNonAotConfig (D:\Projects\ecp\node_modules\angular-cli\models\webpack-configs\typescript.js:26:13)
    at new NgCliWebpackConfig (D:\Projects\ecp\node_modules\angular-cli\models\webpack-config.js:24:37)
    at Class.run (D:\Projects\ecp\node_modules\angular-cli\tasks\serve.js:31:29)
    at D:\Projects\ecp\node_modules\angular-cli\commands\serve.run.js:22:22
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

</code></pre>

## 🌍 Your Environment
<pre><code>
                              _                           _  _
  __ _  _ __    __ _  _   _ | |  __ _  _ __         ___ | |(_)
 / _` || '_ \  / _` || | | || | / _` || '__|_____  / __|| || |
| (_| || | | || (_| || |_| || || (_| || |  |_____|| (__ | || |
 \__,_||_| |_| \__, | \__,_||_| \__,_||_|          \___||_||_|
               |___/
angular-cli: 1.0.0-beta.28.3
node: 8.11.3
os: win32 x64
@angular/animations: 7.0.0
@angular/common: 7.0.0
@angular/compiler: 7.0.0
@angular/core: 7.0.0
@angular/forms: 7.0.0
@angular/http: 7.0.0
@angular/platform-browser: 7.0.0
@angular/platform-browser-dynamic: 7.0.0
@angular/platform-server: 7.0.0
@angular/router: 7.0.0
@angular/cli: 7.3.0
@angular/compiler-cli: 7.0.0
@angular/language-service: 7.0.0

</code></pre>

**Anything else relevant?**
No

**Comment by alan-agius4** [comment]
Angular CLI version 1 beta is no longer supported.

Kindly update to the latest version of Angular CLI at the moment `7.3.0` via `npm i @angular/cli`
