### ISSUE TITLE
Angular Material Dialog Styles are not applying automatically  when i do build in production mode

### ISSUE THREAD

**Issue by mdufoud1214** [angular/angular-cli#13624]
am using Angular 7 , am trying to improve my angular app performance , to do this am trying to reduce the bundle size (to reduce vendor js file size) . I followed below references to do this

`https://github.com/angular/angular-cli/issues/9016`

`https://github.com/angular/angular-cli/issues/13560`

after doing npm run build -- --prod  command , it reduced my dist folder size from 39mb to 9mb
and my application working as expected , but issue in material dialogs 

styles are not applying automatically , because of this icons not  showing and alignment also not proper
if i do npm run build -- --prod , html generating like below (dist size is 9 mb)
`<mat-icon _ngcontent-c38="" class="backButton send">close</mat-icon>`

if i do npm run build html generating like below (dist size is 39 mb)
`<mat-icon _ngcontent-c38="" class="backButton  material-icons send" role="img" aria-hidden="true" ng-reflect-klass="backButton" ng-reflect-ng-class="[object Object]">close</mat-icon>`

please help me on this ,
how to apply styles automatically?
and is this valid approach  to improve performance of angular app ?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
