### ISSUE TITLE
es5BrowserSupport add additional polyfill

### ISSUE THREAD

**Issue by fetters5** [angular/angular-cli#13622]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
When setting "es5BrowserSupport": true in angular.json I get errors in IE 11 because it does not recognize .includes()
`TypeError: Object doesn't support property or method 'includes'`

This issue below gave the original workaround, perhaps now that it is in a conditional polyfill we can add it by default.
https://github.com/angular/angular-cli/issues/4128

### Describe the solution you'd like
Add the following polyfill to the Conditional ES5 Browser Polyfill so that .includes() works with IE 11
`import 'core-js/es7/array';`

### Describe alternatives you've considered
I can keep `import 'core-js/es7/array';` in the main polyfill file, but it is not needed by other browsers

**Comment by alan-agius4** [comment]
The `includes`, is not part of the ES6 but ES7 specs. 

Hence some browsers that support ES6 might still need to use this polyfill to function properly.
