### ISSUE TITLE
gh-pages deployement with diffetent repo and project name

### ISSUE THREAD

**Issue by dvh91** [angular/angular-cli#1362]
Mac OSX El Capitan

angular-cli: 1.0.0-beta.8
node: 4.2.4
os: darwin x64

angular cli project name: 'kmeetup'
repo name: 'kmeetups'

run:
ng github-pages:deploy --message "first kmeetup deploy"

got:
Built project successfully. Stored in "dist/".
Deployed! Visit https://dvh91.github.io/kmeetup/

as far as i can tell, the script takes the project name from angular-cli.json project.name
ad it's not necessarily the repo name.

that causes not only the url that printed in ternimal to be wrong but also the base href in index.html to be wrong which fail to load all scripts.

**Comment by neilhem** [comment]
Why you use with gh-pages php?

**Comment by dvh91** [comment]
I dont.
it's a mistake in my bug description.

**Comment by filipesilva** [comment]
This could be improved, yes.

**Comment by ayu15** [comment]
For a quick workaround, change the project name in package.json to match your github repository name. Then it will set the correct base href in index.html to load all your scripts.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
