### ISSUE TITLE
Add support for generating files on secondary entry points (sub packages)

### ISSUE THREAD

**Issue by klauskpm** [angular/angular-cli#13633]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Creating a [secondary entry point](https://github.com/ng-packagr/ng-packagr/blob/master/docs/secondary-entrypoints.md), like testing, by hand isn't an issue on its own, but using the CLI for generating files for it, is. Whenever I try to generate a file for it, I need to be on the folder or write something like `ng g c ../../testing/src/lib/my-comp --project my-lib`.

### Describe the solution you'd like
I've imagined adding a `--project` flag to `ng generate library` to generate a secondary entry point:
`ng g lib testing --project my-lib`

The structure would be something like below:
```
my-lib
├── src
|   └── lib
└── testing
    ├── src
    |   ├── lib
    |   └── public_api.ts
    └── package.json
```

The command would also add a property, like `entries`, on _angular.json_ library configuration, holding the secondary entry point path. We would need this property for when generating other files, like the following:
`ng g c my-comp --project my-lib/testing`

### Describe alternatives you've considered
We could have a new generation schematic for secondary entry points or a property to add the reference path on _angular.json_ manually.

**Comment by mgechev** [comment]
@klauskpm let's keep this outside of the scope of the CLI for now. I can see how it simplifies the path that you need to enter in the generator, and it seems like a great fit for providing an alternative generator.

The right approach would be to create a custom collection and extend `@schematics/angular`.
