### ISSUE TITLE
ng new with sass does not build

### ISSUE THREAD

**Issue by antoinegslight** [angular/angular-cli#13631]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
- [x] build
- [x] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 I don't know

### Description

 When choosing the sass style option when doing an ng new, the project cannot be built, served or tested. The reason is that the angular.json try to read styles.sass(which does not exist) instead of styles.scss.

## 🔬 Minimal Reproduction

1. `ng new`
2. Choose sass
3. `npm install && npm build`

## 🔥 Exception or Error
<pre><code>

ERROR in multi ./src/styles.sass
Module not found: Error: Can't resolve '/Users/antoinegslight/Code/nexapp/efs/cliniciel-lite-boilerplate/src/styles.sass' in '/Users/antoinegslight/Code/nexapp/efs/cliniciel-lite-boilerplate'
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.1
Node: 10.11.0
OS: darwin x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by AJHanekom** [comment]
https://github.com/angular/angular-cli/issues/13550

**Comment by alan-agius4** [comment]
Make sure that your global cli is 7.3.1 aswell and not just the local.
