### ISSUE TITLE
Flag to generate a module and add it to lazyModules in angular.json

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular-cli#13634]
# 🚀 Feature request
Need a flag that can generate the module and add it's path to the angular.json's lazyModules array

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...
Currently I have to generate a module, and manually add the whole path to lazyModules array in the angular.json

### Describe the solution you'd like
ng generate module widget --lazy-module

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
This is something that we @minko is currently working on.

**Comment by mohammedzamakhan** [comment]
Any updates on this @alan-agius4 @mgechev?

**Comment by alan-agius4** [comment]
This feature has been added in Angular CLI version 8.1

More info can be found here: angular.io/guide/lazy-loading-ngmodules
