### ISSUE TITLE
Angular 7.2.4 - Unmet Peer Dependancy

### ISSUE THREAD

**Issue by Adam-Kernig** [angular/angular-cli#13649]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [X ] update
```

### Is this a regression?
Did this behavior use to work in the previous version?
Yes, the previous version in which this bug was not present was: ....

### Description
Okay, As usual im notified on angular updates, I went to run the ng update command as usual to be correctly notified of the 7.2.4 updates (going from 7.2.3)

After installing im notified of peer dependancies missing
**

> npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.4.0

**

## 🔬 Minimal Reproduction
- ng new
- Let node install
- See error: ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

## 🔥 Exception or Error
<pre><code>
ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

</code></pre>

## 🌍 Your Environment
<pre><code>
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.1
@angular-devkit/core         7.3.1
@angular-devkit/schematics   7.3.1
@schematics/angular          7.3.1
@schematics/update           0.13.1
rxjs                         6.3.3
typescript                   3.2.4

</code></pre>

**Anything else relevant?**
Performing npm ls --depth 0 will identify the issues
├── UNMET PEER DEPENDENCY @angular/common@7.2.4
├── UNMET PEER DEPENDENCY @angular/core@7.2.4

If this was an expected dependancy I should think it would be put in dev dependancies instead of installing it after upgrading? It seems odd that out of the box this doesn't come installed.

Hopefully this is enough info to track down.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this. 

This will be fixed by https://github.com/angular/angular-cli/pull/13645

**Comment by Adam-Kernig-RM** [comment]
Thanks @alan-agius4, much appreciated

**Comment by alan-agius4** [comment]
Fixed via https://github.com/angular/angular-cli/pull/13645
