### ISSUE TITLE
[ivy] ng new ivy4ever --experimentalIvy=true doesn't add aot: true option

### ISSUE THREAD

**Issue by wKoza** [angular/angular-cli#13646]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

When I run this command:
```
ng new ivy4ever --experimentalIvy=true
```
~~I notice that the postInstall script isn't added to the package.json file.~~
Futhermore, should not we add the property `aot: true` to angular.json ?

```
"architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "aot": true,
...
```

## 🔬 Minimal Reproduction
```
ng new ivy4ever --experimentalIvy=true
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.2.4
Node: 10.10.0
OS: darwin x64
Angular: 7.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@wKoza, you need to generate the project, using the latest version to the CLI. As the post install feature was introduced in 7.3.0.

With regards to the `aot` option, I am assuming that you want to turn this on, to use the `ngtsc` compiler in dev mode. I'm not sure, if we should do this by default. Maybe @filipesilva knows more about this he is currently working on some Ivy stuff.

**Comment by wKoza** [comment]
arff OK perfect. With regards to the `aot` option, I refer, indeed, to the work of @filipesilva in [this PR](https://github.com/angular/angular/pull/28569) .

**Comment by filipesilva** [comment]
@wKoza we don't yet add `aot: true` here because we've identified a performance regression, but the plan is still to add it for 8.0
