### ISSUE TITLE
Choosing stylesheet format in interactive mode skips options

### ISSUE THREAD

**Issue by CameronEzraJones** [angular/angular-cli#13657]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I don't know if this was working in previous versions or not

### Description

 A clear and concise description of the problem...
When I run the command `ng new angular-app --interactive`, it first shows whether I want to add Angular routing. This is working properly. However, the next question asks me which stylesheet format I would like to use, and this is experiencing the problem.
This bug is occuring in version 7.3.1

## 🔬 Minimal Reproduction

1. run `ng new angular-app --interactive`. The question  The prompt "Would you like to add Angular routing?" appears
2. entery `y` to indicate you want Angular routing. The prompt "Which stylesheet format would you like to use?" appears with these options in order:

- CSS
- Sass   [ http://sass-lang.com   ]
- Less   [ http://lesscss.org     ]
- Stylus [ http://stylus-lang.com ]

The selector is initially on CSS

3. Press the down arrow.

Expected: The selector moves to the Sass option
Actual: The selector moves to the Less option
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.1
Node: 11.9.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.1
@angular-devkit/core         7.3.1
@angular-devkit/schematics   7.3.1
@schematics/angular          7.3.1
@schematics/update           0.13.1
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Anything else relevant?**

**Comment by tieppt** [comment]
also, the list of available options is missing `SCSS`

**Comment by alan-agius4** [comment]
Hi, which terminal are you using?

**Comment by CameronEzraJones** [comment]
This was occuring on both Windows Powershell and the Windows Command Prompt. It doesn't seem to be an issue in Linux, however.

**Comment by alan-agius4** [comment]
@CameronEzraJones, unfortunately I am unable to replicate this from my end. Both on PowerShell and CMD

**Comment by alan-agius4** [comment]
@CameronEzraJones, unfortunately I am unable to replicate this from my end. Both using PowerShell and CMD

@filipesilva can you give it a shot yourself please?

**Comment by filipesilva** [comment]
Tried it myself with gitbash and couldn't see it.

**Comment by robertIsaac** [comment]
this happens with me too in powershell/cmd
in git bash it doesn't ask for routing/style

**Comment by clydin** [comment]
This may be an issue with Node.js itself.  Can you try with either 10.15.3 or 11.11.0?

**Comment by robertIsaac** [comment]
> This may be an issue with Node.js itself. Can you try with either 10.15.3 or 11.11.0?

works with me in node 11.11.0

**Comment by robertIsaac** [comment]
i have a question if someone can nelp
why git bash isn't giving the interactive questions when running `ng new angular-app --interactive`?

**Comment by filipesilva** [comment]
@robertIsaac I can't speak for your specific console setup, but the options in general don't show up the the console does not support interactivity. 

In my setup, the options don't work with ConEmu+gitbash, but they work on the VSCode integrated terminal with gitbash.

**Comment by clydin** [comment]
Closing as this appears to be an issue with older versions of Node.js and not the CLI.
