### ISSUE TITLE
Does angular-cli support creating a project in JavaScript rather than typescript?

### ISSUE THREAD

**Issue by TCourtneyOwen** [angular/angular-cli#13651]
I am trying to create a new Angular project that uses pure JavaScript rather than typescript. I didn’t see anyway to specify that I want a JavaScript project in the CLI documentation. Is this possible? I was hoping that I could specify a param with “ng new”.

Thanks

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

However the answer to your question is no.
