### ISSUE TITLE
gh-pages deployement some vendor files missing

### ISSUE THREAD

**Issue by dvh91** [angular/angular-cli#1366]
Mac OSX El Capitan

angular-cli: 1.0.0-beta.8
node: 4.2.4
os: darwin x64

'ng github-pages:deploy'
deploys the app to gh-pages, but in app fails to load. 
vendor/zone.js/dist/zone.js  & vendor/systemjs/dist/system.src.js returns 404 error.

looking at the gh-pages branch shows that in vendor folder there are 2 folder only (es6-shim, reflect-metadata)

running 'ng build --prod' works as expected and the running http-server from dist folder deliver the app.

looks like there is something wrong with the build process from the gh-pages deployment.

**Comment by juvan** [comment]
+1
Same issue here.

**Comment by filipesilva** [comment]
Closed as issue was made obsolete by #1455.
