### ISSUE TITLE
include watch script by default

### ISSUE THREAD

**Issue by Vandivier** [angular/angular-cli#13664]
# 🚀 Feature request

Who doesn't need a watch command?

Add "watch": "ng build --watch" to the generated package.json

Happy to PR if approved

**Comment by alan-agius4** [comment]
@Vandivier this sounds like a useful feature, in the same time it is trivial to do, and we see that most users use `npm start`

I'd suggest to hold this off for now and revisit in future.

Let's reopen if more folks need such script.
