### ISSUE TITLE
Support custom ElementSchemaRegistry for the AOT compiler

### ISSUE THREAD

**Issue by CSchulz** [angular/angular-cli#13662]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/compiler

### Description
Allow setting the ElementSchemaRegistry for the AOT compiler.

At the moment we can configure a custom ElementSchemaRegistry for JIT using the bootstrap parameter compilerOptions configuring a static provider overwriting the ElementSchemaRegistry provider:
```
bootstrapModule<M>(moduleType: Type<M>, compilerOptions?: (CompilerOptions & BootstrapOptions) | Array<CompilerOptions & BootstrapOptions>): Promise<NgModuleRef<M>>;
```

### Describe the solution you'd like
Setting the wanted ElementSchemaRegistry in the angular.json.

### Describe alternatives you've considered
...

**Comment by alan-agius4** [comment]
Hi, thanks for this. However, compiler features should be logged here: https://github.com/angular/angular/issues

**Comment by CSchulz** [comment]
angular/angular#12045
