### ISSUE TITLE
flat=false has no effect when generating guard

### ISSUE THREAD

**Issue by ShPelles** [angular/angular-cli#13666]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't know.

### Description
When flat=false, guards are generated in my current folder instead of creating a new folder.

## 🔬 Minimal Reproduction
```
ng new testFlat
cd testFlat/src/app
ng g g test --flat=false
```

### expected result
```
CREATE src/app/test/test.guard.spec.ts (346 bytes)
CREATE src/app/test/test.guard.ts (456 bytes)
```

### actual result
```
CREATE src/app/test.guard.spec.ts (346 bytes)
CREATE src/app/test.guard.ts (456 bytes)
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.1
Node: 11.9.0
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by ShPelles** [comment]
And `--skipTests=true` also has no effect. The `.spec` file is still created.

**Comment by wKoza** [comment]
Can you open a new issue for this ?
