### ISSUE TITLE
ERROR in src/app/app.module.ts(15,15): error TS2304: Cannot find name 'ServiceName'

### ISSUE THREAD

**Issue by dhananjaymg** [angular/angular-cli#13675]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular-cli/issues/new/choose

Hi Team, 

I have started learning new angular version, 

I have created a one component and one service, 

Component : testComponent
Service : testService

while adding the service in provider : [] inside app.module.ts getting the error

ERROR in src/app/app.module.ts(15,15): error TS2304: Cannot find name 'testService'.

I have these installed on my machine.

Npm : 6.1.0
Node : v8.9.4
Angular Version : "@angular/core": "~7.2.0",
Typescript : Version 3.1.1

can some one please help me how to get the above error resolve.

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dhananjaymg** [comment]
Hi Alan, I have posted the question in SO.

https://stackoverflow.com/questions/54696477/error-in-src-app-app-module-ts15-15-error-ts2304-cannot-find-name-servicena
