### ISSUE TITLE
Possibility to add customs polyfills to the new es2015-polyfills

### ISSUE THREAD

**Issue by ochezeau** [angular/angular-cli#13673]
# 🚀 Feature request
```
- [x] new
- [x] build

```

### Description
I love the new feature of angular CLI 7.3 that allow to create automaticaly a polyfills for old browser. 
On my project a use Server Sent Events and i need a polyfill for Internet Explorer. 
It would have been cool to be able to import this pollify into a separate file that could finally end up in the  es2015-polyfills file.

### Describe the solution you'd like
Maybe having two files : polyfills.ts and es2015-custom-polyfills.ts. 
Durring the build process the es2015-custom-polyfills.ts can be merged with the auto generated polyfills to create the final es2015-polyfills.js

Thank you for all your fantastic job.

Olivier

**Comment by clydin** [comment]
The `es2015-polyfills` file is specifically intended to provide the ES2015 polyfills required by Angular to support browsers with no ES2015 support.
In the case of Server Sent Events, both IE and Edge (an ES2015 browser) do not have support.  As a result, a polyfill would be required to be executed regardless of the browser's ES2015 support status.

**Comment by ochezeau** [comment]
@clydin : ok, so if i understand correctly the "no module" will do that Edge not loading the file, so in this cas, my SSE will not works in Edge. So what i proposed will not work

**Comment by clydin** [comment]
Correct.  To ensure full browser support, the SSE polyfill would need to be placed in the `polyfills.ts` file and always run.  Optionally (and outside the scope of the Angular CLI), you could add a custom script to the index that would check the browser and then dynamically load the polyfill.  However, the first polyfill I found for SSE ([here](https://github.com/Yaffle/EventSource)) appears to only be ~10kb minified.  So the added complexity of such an option may be unwarranted.

**Comment by ochezeau** [comment]
i'm agree that for 10bk the gain is not worth the effort. The initial idea was to have a global behavior in cas of  custom pollify for es5, but it seems that probably, it will not be really useful.

Thank you for your answers

**Comment by robwormald** [comment]
This is worth considering for DOM / Web Platform APIs as well, particularly Custom Elements / Shadow / Shady DOM, IntersectionObserver/ResizeObserver, etc, as well as fancy new CSS/Houdini features, especially as Edge moves to Chromium...

**Comment by mgechev** [comment]
This seems like a better fit for differential serving rather than differential loading. My suggestion is to keep this feature outside the CLI at this point.

**Comment by alan-agius4** [comment]
We just had a team meeting and as mentioned above by @mgechev, this feature is outside the CLI at this point.
