### ISSUE TITLE
Run fails with es2015

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular-cli#13670]
- [ xx] build

### Is this a regression?
Nope

### Description
So, because of https://github.com/angular/angular-cli/issues/12112 I tried to do a build & serve with tsconfig.json target set to es2015.
The build itself succeeds, the serve also, well quite, because when I browse to it, the browser screen just stays white and in the console:
![image](https://user-images.githubusercontent.com/1098243/52726987-92802080-2fb4-11e9-9930-53d9c4a50223.png)
Authentication is a service class that should normally be injected in the helpers services class.
This works in es5.
The build configuration is:
            "env-t-as-dev": {
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": false,
              "aot": false,
              "extractLicenses": false,
              "vendorChunk": false,
              "buildOptimizer": false,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/env-t-as-dev.ts"
                }
              ]
            },

If you want more info, feel free to ask.

**Comment by alan-agius4** [comment]
closing as doesn't follow template
