### ISSUE TITLE
CORS issue while using Angular proxy to proxy an API with response-type application/vnd.apple.mpegurl

### ISSUE THREAD

**Issue by pedromcunha** [angular/angular-cli#13677]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

 A clear and concise description of the problem...
I'm trying to proxy a request to my backend which has a response-type of **application/vnd.apple.mpegurl**. Here's a sample of what the HTTP request headers looks like without proprietary information.

```
  | GET api/request/to/my/backend/goes=here  HTTP/1.1
-- | --
Host | myserver.com
Connection | keep-alive
Origin | https://localhost:4200
User-Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Accept | */*
Referer | https://localhost:4200/home
Accept-Encoding | gzip, deflate, br
Accept-Language | en-US,en;q=0.9,pt-PT;q=0.8,pt;q=0.7

```

## 🔬 Minimal Reproduction
Reproduction repo is WIP. Will update issue with one.

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.0.7
Node: 11.6.0
OS: darwin x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.2.2
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.4
</code></pre>

**Comment by alan-agius4** [comment]
Can you kindly try to specify `"changeOrigin": true,`?

If the problem persists kindly open a new issue with a minimal reproduction.

**Comment by pedromcunha** [comment]
Sorry I should have included my proxy config:
`
{
  "api/request/to/my/backend/*": {
    "target": "https://myserver.com",
    "secure": true,
    "logLevel": "debug",
    "changeOrigin": true,
    "cookieDomainRewrite": "localhost"
  }
}
`
I was already providing `"changeOrigin": true`.
