### ISSUE TITLE
 'rootDir' is expected to contain all source files ... error in latest CLI

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#13683]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
YES, but not sure what  / who is behind this. 

### Description

After upgrading to latest CLI, ANGULAR, NX I am getting this error 
```
error TS6059: File '/Users/fkolar/Desktop/upgr/libs/rules/src/index.ts' is not under 'rootDir' '/Users/fkolar/Desktop/upgr/libs/ui-lib/src'. 'rootDir' is expected to contain all source files.
```
Where before it was enough to add declaration to the tsconfig, but now it fails again. 

You create a publishable library 
 ` core` and then you create another library e.g. uiLib that has dependency to `core`, importing e.g. Module. 

## 🔬 Minimal Reproduction

```
git clone https://github.com/fkolar/upgr-issue
cd upgr-issue
npm i

ng build rules. // this one represent the core library
ng build ui-lib. // this is child lib that refers back to rules (core lib(
// after you run last command you get the error. 

```

## 🔥 Exception or Error
<pre><code>
error TS6059: File '/Users/fkolar/Desktop/upgr/libs/rules/src/index.ts' is not under 'rootDir' '/Users/fkolar/Desktop/upgr/libs/ui-lib/src'. 'rootDir' is expected to contain all source files.</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.1
Node: 10.9.0
OS: darwin x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.1
@angular-devkit/build-angular      0.13.1
@angular-devkit/build-ng-packagr   0.13.1
@angular-devkit/build-optimizer    0.13.1
@angular-devkit/build-webpack      0.13.1
@angular-devkit/core               7.3.1
@angular-devkit/schematics         7.3.1
@angular/cli                       7.3.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.1
@schematics/angular                7.3.1
@schematics/update                 0.13.1
ng-packagr                         4.7.0
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

**Comment by alan-agius4** [comment]
Closing as it’s a 3rd party issue and is being tracked here https://github.com/ng-packagr/ng-packagr/issues/1210

**Comment by fkolar** [comment]
Great. Thanks for the reference !
