### ISSUE TITLE
ng build -prod does not copy some npm files

### ISSUE THREAD

**Issue by imalhasaranga** [angular/angular-cli#1368]
Here is how my angular-cli-build.js look

`module.exports = function (defaults) {

		return new Angular2App(defaults, {
            vendorNpmFiles: [
               'systemjs/dist/system-polyfills.js',
               'systemjs/dist/system.src.js',
               'zone.js/dist/**/*.+(js|js.map)',
            	'es6-shim/es6-shim.js',
            	'reflect-metadata/**/*.+(ts|js|js.map)',
            	'rxjs/**/*.+(js|js.map)',
            	'@angular/**/*.+(js|js.map)',
            	'ng2-bootstrap/**/*.js',
            	'moment/moment.js',
            	'bootstrap/dist/**',
            	'bootstrap-material-design/dist/**',
            	'jquery/dist/**/*.+(js|js.map)',
            	'arrive/minified/**/*.+(js|js.map)',
            	'font-awesome/**/*.+(css|map|otf|eot|svg|ttf|woff|woff2)',
        	]
    	});
	};`

but for some reason 

`
	'ng2-bootstrap/**/*.js',
	'moment/moment.js',
	'bootstrap/dist/**',
	'bootstrap-material-design/dist/**',
	'jquery/dist/**/*.+(js|js.map)',
	'arrive/minified/**/*.+(js|js.map)',
`

does not get copied to the `dist/vendor` folder with the comment `ng build -prod` but everything is ok with `ng build`

**Comment by griga** [comment]
That's because with `-prod` they are embedded inside `main.js` bundle

In my project I faced same problem when lazy loading vendor libs:  
    in _dev_ mode `System.import` is able to load from `dist/vendor` folder
    but in _prod_ mode files that i'm importing lazily are not present in `dist/vendor`

I came up with following 'angular-cli-build.js' to manage this

```
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

var Funnel = require('angular-cli/node_modules/broccoli-funnel');
var mergeTrees = require('broccoli-merge-trees');

module.exports = function (defaults) {
  var lazyVendorFiles =  [
    'select2/dist/js/select2.min.js',
    'summernote/dist/summernote.min.js',
    'chart.js/dist/Chart.min.js',
    'dropzone/dist/dropzone-amd-module.js',
  ];

  var appTree = new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'symbol-observable/lib/ponyfill.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      '@ngrx/**/*.+(js|js.map)',
      'ng2-bootstrap/**/*.+(js|js.map)',
      'moment/moment.js',
    ].concat(lazyVendorFiles.slice())
  });

  var lazyVendorFilesTree = new Funnel('node_modules', {
    include: lazyVendorFiles.slice(),
    destDir: 'vendor'
  });

  return mergeTrees([lazyVendorFilesTree, appTree], { overwrite: true });
};
```

**Comment by imalhasaranga** [comment]
Super Awesome Dude!!, Thanks it works works...

just correcting a small mistake of yours
`var mergeTrees = require('angular-cli/node_modules/broccoli-merge-trees');`
