### ISSUE TITLE
[Build Optimizer] Initial load fails with enabled --build-optimizer

### ISSUE THREAD

**Issue by riede** [angular/angular-cli#13686]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description
Building my SPA with `ng build --prod` works well. But when I want to load it initially, it crashed. Serving with `--source-map` delivers the following error:
![image](https://user-images.githubusercontent.com/37865880/52875831-9a2afb00-3155-11e9-9b5d-f1384567c9ff.png)

When I do not use the production flag everything works well. `ng build --aot --optimization` works, too - I can load the page and everything is ok. I think there might be a bug in the Build Optimizer.

## 🔥 Exception or Error
<pre><code>
`TypeError: Cannot read property '__source' of undefined`
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.1
Node: 8.11.3
OS: darwin x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.1
@angular-devkit/build-angular     0.13.1
@angular-devkit/build-optimizer   0.13.1
@angular-devkit/build-webpack     0.13.1
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cli                      7.3.1
@ngtools/webpack                  7.3.1
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
Here is my package.json:
<pre><code>
 "dependencies": {
    "@angular/animations": "^7.2.4",
    "@angular/common": "^7.2.4",
    "@angular/compiler": "^7.2.4",
    "@angular/core": "^7.2.4",
    "@angular/forms": "^7.2.4",
    "@angular/http": "^7.2.4",
    "@angular/platform-browser": "^7.2.4",
    "@angular/platform-browser-dynamic": "^7.2.4",
    "@angular/router": "^7.2.4",
    "@ngx-loading-bar/core": "^4.1.1",
    "@ngx-loading-bar/http-client": "^4.1.1",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@swimlane/ngx-charts": "^10.0.0",
    "@types/d3": "^4.10.2",
    "@types/lodash": "^4.14.121",
    "@types/uuid": "^3.4.4",
    "angular-2-local-storage": "^3.0.0",
    "angular-gridster2": "^7.1.0",
    "angular2-ladda": "^2.0.0",
    "bootstrap": "^4.2.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.5",
    "d3": "^4.10.2",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.11",
    "moment": "^2.24.0",
    "ngx-bootstrap": "^3.2.0",
    "ngx-color-picker": "^7.3.1",
    "ngx-infinite-scroll": "^7.0.1",
    "ngx-slimscroll": "^7.1.0",
    "ngx-toastr": "^9.1.2",
    "pretty-checkbox": "^3.0.3",
    "rxjs": "^6.4.0",
    "spinkit": "^1.2.5",
    "tslib": "^1.9.3",
    "uuid": "^3.3.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.1",
    "@angular/cli": "~7.3.1",
    "@angular/compiler-cli": "^7.2.4",
    "@angular/language-service": "^7.2.4",
    "@compodoc/compodoc": "^1.1.8",
    "@types/jasmine": "~3.3.9",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~8.9.5",
    "codelyzer": "~4.5.0",
    "husky": "^0.14.3",
    "jasmine-core": "~3.3.0",
    "jasmine-marbles": "^0.4.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.4",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-parallel": "^0.3.1",
    "lint-staged": "^7.2.0",
    "prettier": "^1.16.4",
    "protractor": "~5.4.2",
    "ts-node": "~7.0.1",
    "tslint": "~5.12.1",
    "typescript": "3.2.4"
  }
</code></pre>

**Comment by mgechev** [comment]
Would you provide a minimal repo where we can reproduce the problem?

**Comment by riede** [comment]
I will try to provide a minimal Repo. But I think it could take a cupple of days.

**Comment by quangquy87** [comment]
Error in angular-2-local-storage, remove or use other library to fix problem

**Comment by riede** [comment]
@quangquy87 Are you sure? We already use angular-2-local-storage since Angular 5. Everything works fine with Angular 7.2.2. Updating to Angular 7.2.3 lets the application crash at runtime with `--prod`

**Comment by quangquy87** [comment]
> @quangquy87 Are you sure? We already use angular-2-local-storage since Angular 5. Everything works fine with Angular 7.2.2. Updating to Angular 7.2.3 lets the application crash at runtime using `--prod`

I am sure, I have encountered the same error and took several days to find the problem

**Comment by riede** [comment]
> I am sure, I have encountered the same error and took several days to find the problem

Thanks. You're right, by using angular-2-local-storage in a minimal repro-app I could reproduce the error. Nevertheless the error has only existed since Angular 7.2.3

**Comment by riede** [comment]
Here is the minimal [Repo](https://github.com/riede/anguluar-2-local-storage-repro-app) that reproduces the error. 

Issue [#63](https://github.com/phenomnomnominal/angular-2-local-storage/issues/63) of the angular-2-local-storage project discusses the same error. I'm not sure if the error lays on the angular side or on the angular-2-local-storage side.

**Comment by riede** [comment]
@quangquy87 I‘ve created a Pull Request to fix the Problem. A new version is already available for angular-2-local-storage. 

So, the Issue can be closed.
