### ISSUE TITLE
Module not found if library is compile outside of app folder

### ISSUE THREAD

**Issue by Akxe** [angular/angular-cli#13695]
# 🐞 Bug report

### Command
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Probably not.

### Description
If you specify output directory outside of app folder, more specifically the one that contains `node_modules` and `@angular` package. You will get errors on build.

## 🔬 Minimal Reproduction

1. Create angular app (ng new)
2. Generate library (ng g library)
3. Change output directory out of folder containing `node_modules`.
4. Use library in your app
5. Build both - You will get error that it tries to include something from unknown module `@angular/core` etc

## 🔥 Exception or Error
<pre><code>
Cannot find module '@angular/core'. (in `test-lib.component.ts` and most of other)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.1.2
Node: 9.11.1
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.11.2
@angular-devkit/build-angular      0.11.2
@angular-devkit/build-ng-packagr   0.11.4
@angular-devkit/build-optimizer    0.11.2
@angular-devkit/build-webpack      0.11.2
@angular-devkit/core               7.1.2
@angular-devkit/schematics         7.1.2
@angular/cli                       7.1.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.1.2
@schematics/angular                7.1.2
@schematics/update                 0.11.2
ng-packagr                         4.7.0
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.23.1
</code></pre>

**Comment by alan-agius4** [comment]
Hi, I am sorry but I am not understanding what you mean by `Change output directory out of folder containing `node_modules`.`?

Can you kindly elaborate or even better create a minimal reproduction. 
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by Akxe** [comment]
Go to generated `ng-package.json`, and prepend `../` to the `dest` parameter.

**Comment by alan-agius4** [comment]
That is expected and the correct behaviour, as you are “breaking” the node module resolution.

What you can do is to use tsconfig paths.

However I’d suggest to repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`. As this tracker is not suitable for support request.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Thanks.

**Comment by Akxe** [comment]
@alan-agius4 I know why this has happened, but as building file into a different directory is fine, I have assumed building a library would too. For this, I had created this issue so that the compiler could insert `tsconfig` file with `typeroot` of the original source.
