### ISSUE TITLE
Svg files in root directory dist/root 

### ISSUE THREAD

**Issue by camphan12993** [angular/angular-cli#13694]
after running "ng build" there are many .svg files in the main directory of the output in the dist folder.
![image](https://user-images.githubusercontent.com/40196295/52935866-23784280-338d-11e9-9778-f99940cbd1bf.png)
May be it's from node_modules/material-icon 
can i somehow specify it that assets like this will not be placed in the root?

**Comment by alan-agius4** [comment]
Closing as template is not followed
