### ISSUE TITLE
NPM Audit Failure - Compiler - v7.2.5

### ISSUE THREAD

**Issue by Adam-Kernig** [angular/angular-cli#13698]
Hey guys,

Im not sure if this is under acceptable circumstances, we have reported an npm audit failure here:
https://github.com/angular/angular/issues/28796

Not sure if you guys are aware of it, tldr:
│ Low           │ Regular Expression Denial of Service                        
│ Package       │ braces                                                 
│ Patched in    │ >=2.3.1                                                    
│ Dependency of │ @angular/compiler-cli [dev]                                
│ Path          │ @angular/compiler-cli > chokidar > anymatch > micromatch > braces                                                       
│ More info     │ https://npmjs.com/advisories/786

**Comment by filipesilva** [comment]
Heya, it sure is important that we are aware of these, so thank you for bringing it up. The main issue we're using to track it is https://github.com/angular/angular/issues/28771 because that package is part of that repository. We have a fix incoming in https://github.com/angular/angular/pull/28797.

**Comment by alan-agius4** [comment]
Closing as the fix for this has been released in `@angular/compiler-cli` v7.2.6
