### ISSUE TITLE
Altering default generated file names

### ISSUE THREAD

**Issue by mickeypuri** [angular/angular-cli#13699]
Is there anyway of configuring so that when generating a new component, the cli does not add .component to the style, html and test files. If we have a fairly small component name, then having .component. added to all 4 files creates a huge amount of visual noise, and since there already is a .component.ts file in the folder, its very clear that these are the html and scss relating to that file.

**Comment by alan-agius4** [comment]
Hi thanks for reporting this. 

However, these file names are based on the style guide https://angular.io/guide/styleguide#file-structure-conventions

Custome file names are outside of the scope of the cli. However, if you wish to have custom file names, this is possible by creating custom schematics.
