### ISSUE TITLE
npm WARN prefer global on node-gyp@3.8.0

### ISSUE THREAD

**Issue by jacopolanzoni-pq** [angular/angular-cli#13696]
When install my Angular app I get a 
   `npm WARN prefer global node-gyp@3.8.0 should be installed with -g`
due to 
   `@angular-devkit/build-angular@0.13.1` ==> `node-sass@4.11.0` ==> `node-gyp@3.8.0`
Is there any way to tackle this warning? I have node-gyp installed globally but the local version is apparently preferred.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
