### ISSUE TITLE
how to install    webpack   angular-cli

### ISSUE THREAD

**Issue by iloveyo123u1** [angular/angular-cli#1369]
https://github.com/angular/angular-cli/tree/webpack

how to install this

**Comment by neilhem** [comment]
Webpack support is coming soon, WIP.

**Comment by TheLarkInn** [comment]
@iloveyo123u1 We have a few more things that need to be completed first. Once the branch is ready to be merged to master, we will document what is required to migrate, etc.

**Comment by filipesilva** [comment]
As @TheLarkInn mentioned, it's still WIP and we will document how to upgrade once it is ready. At the moment it is internal.
