### ISSUE TITLE
ERROR TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by Sammyalhashe** [angular/angular-cli#13693]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
`1.7.3`

### Description

 A clear and concise description of the problem...
When I run `ng build --prod` and serve the app, browser throws this error:
```
main.a45a79f653f8f025a032.js:1 ERROR TypeError: Cannot read property 'name' of null
```

## 🔬 Minimal Reproduction

```
ng build --prod
ts-node -r tsconfig-paths/register src/main.ts
``` 
(I serve the `dist` folder with [NestJS](https://nestjs.com/))
I don't believe this is a problem with how I'm serving the dist folder, because it work when I only run `ng build`.
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.0
Node: 11.8.0
OS: darwin x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.0
@angular/cdk                      7.3.1
@angular/cli                      7.3.0
@angular/fire                     5.1.1
@angular/material                 7.3.1
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.0
@schematics/update                0.13.0
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.8.3
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Sammyalhashe** [comment]
I'm really busy right now, but I'll get you a repro by the end of the day

**Comment by Sammyalhashe** [comment]
Since my app is still in its infancy stages, I'll just post it right now: [Here it is](https://github.com/Sammyalhashe/Website2). 

Is this alright?

**Comment by alan-agius4** [comment]
Hi, thanks for the above. After looking at the code it seems that it's cause by the default export in https://github.com/Sammyalhashe/Website2/blob/master/src/app/app.animations.ts#L53

See: https://github.com/angular/angular/issues/11402
