### ISSUE TITLE
Missing SCSS option

### ISSUE THREAD

**Issue by oleksiipotiekhin** [angular/angular-cli#13708]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Description
Missing SCSS option.

## 🔬 Minimal Reproduction
<pre><code>ng new</code></pre>
![image](https://user-images.githubusercontent.com/30025319/53002300-b0bea400-342c-11e9-92b2-25adc67b8d01.png)

## 🌍 Your Environment
<pre><code>Angular CLI: 7.3.1
Node: 8.15.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.1
@angular-devkit/core         7.3.1
@angular-devkit/schematics   7.3.1
@schematics/angular          7.3.1
@schematics/update           0.13.1
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this. However this is expected as `scss` is not a css pre-processor but a file extension. When choosing `sass` it will create files with a `scss` file extension.
