### ISSUE TITLE
"ng update --all" typescript error!

### ISSUE THREAD

**Issue by pavll05** [angular/angular-cli#13701]
If i run "npm install" in the angular project, i got following error: 
<pre>npm WARN @angular/compiler-cli@7.2.5 requires a peer of @angular/compiler@7.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself. </pre>

An if i run ng update --all i got following:
<pre>Package "@angular/compiler-cli" has an incompatible peer dependency to "typescript" (requires ">=3.1.1 <3.3", would install "3.3.3")</pre>

Can you help me please, because i am not so familiar with npm and nodejs.

**Comment by alan-agius4** [comment]
Related to 
https://github.com/angular/angular-cli/issues/13095
