### ISSUE TITLE
e2e exit codes are always 0 or 1

### ISSUE THREAD

**Issue by dowhiletrue** [angular/angular-cli#13709]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 No

### Description

Failing e2e tests always return exit code 1
Running `ng e2e` should return the correct exit code from protractor to make it possible to distinguish between unmet assertions and other issues such as compilation errors.

## 🔬 Minimal Reproduction
```
ng new my-first-project
cd new my-first-project
# edit e2e/src/app.e2e-spec.ts: change string to make expectation to be falsy
ng e2e
```

## 🔥 Exception or Error
<pre><code>

E/launcher - Process exited with error code 1
An unexpected error occurred: undefined

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.2
Node: 10.14.1
OS: linux x64
Angular: 7.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.2
@angular-devkit/build-angular     0.13.2
@angular-devkit/build-optimizer   0.13.2
@angular-devkit/build-webpack     0.13.2
@angular-devkit/core              7.3.2
@angular-devkit/schematics        7.3.2
@angular/cli                      7.3.2
@ngtools/webpack                  7.3.2
@schematics/angular               7.3.2
@schematics/update                0.13.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, I am sorry but the log above is not caused by the CLI. 

In the above mentioned case, the error code 1, is emitted by protractor itself.
```
E/launcher - Process exited with error code 1
```

If protractor exits with another code, it should print another code. However, this is not caused by the CLI, as these logs are internally handled within protractor library.

**Comment by dowhiletrue** [comment]
Thanks for pointing out, that this is a protractor issue. I'll post the bug there.
