### ISSUE TITLE
Schematics - remove file extensions from acceptable values in `style`

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#13711]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
At the moment, we accept both file extensions and css preprocesssors as a valid value for `style`. However this is causing some confusing as for prompts we only show and accept preprocesssors.

https://angular.io/cli/generate#component-command

### Describe the solution you'd like
Remove file extensions from acceptable values and only accept preprocesssors as a value.

What is proposed here is breaking, and should be done for Version 8

Relates to: https://github.com/angular/angular-cli/pull/13710

**Comment by wKoza** [comment]
when you say "only accept preprocesssors as a value." , you include `css` which is not a preprocessor ?

Another question: If you launch ng g c comp1 --style=sass, Angular CLI will generate a .sass or .scss ? 
IMO, the file extension  is more significant.

**Comment by alan-agius4** [comment]
@wKoza `sass` will generate a file with `scss` as extension. `.sass` is a deprecated.

**Comment by wKoza** [comment]
I'm not sure that .sass is deprecated (old, yes). dart-sass seems support the both.  But you explain that 

> This is causing major confusion as users are not aware that choosing `sass` will generate files with `scss` extension.

So `ng g c comp1 --style=sass` will produce the same confusion. I say that because I think a user want to have a .scss file , He doesn't know (sometime) the name of the framework.

**Comment by alan-agius4** [comment]
Closing this as we are going to reintroduce `sass` as a file extension.
