### ISSUE TITLE
add support for external template/styles in webpack branch

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#1371]
I tried removing the `isMobile` special case from `app.component.ts` and use the standard `templateUrl` and `styleUrls` to see if the new webpack magic would automatically fix the issues with loading external templates, but it still fails. I walked through with @gdi2290 and he proposes that we make the webpack app shell plugin (`addon/ng2/utilities/prerender-webpack-plugin.ts`) run against webpack-already-processed files/bundles, which will have already inlined the template and styles via the `angular2-template-loader`. 

Patrick says he can have it done in 5 minutes from now.

**Comment by gdi2290** [comment]
I got it working in 5 minutes but ran into a problem with importing in different contexts (known problem when working in Node with Angular 2 because Angular's di relies on references. The other problem is Reflect which has the same problem). I just need to isolate the prerendering in a separate process

**Comment by filipesilva** [comment]
I like that idea, it will make mobile much less special-case-y.

I should mention that at the moment we're using a built-in version of https://github.com/angular/universal/pull/464 instead of importing `prerender-webpack-plugin.ts`, but that we should import it once the PR is in.

**Comment by gdi2290** [comment]
it shouldn't be too hard to also prerender other pages with folders using the router config. I got it working if `routes` was exported

**Comment by filipesilva** [comment]
@gdi2290 did you manage to get it working? If you point me in the right direction I can maybe pick it up.

**Comment by hansl** [comment]
Closing this as fixed already.
