### ISSUE TITLE
Typo/missing quotes in vscode extension json template file.

### ISSUE THREAD

**Issue by Destreyf** [angular/angular-cli#13719]
# 🐞 Bug report

I was reading the change log, and happened to see the mention of vscode extensions, being interested in what you might be recommended i went and read through the changes and found a typo/missing quotation on the tslint recommendation.

the file is here: https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/workspace/files/__dot__vscode/extensions.json.template

**Comment by alan-agius4** [comment]
Fixed by https://github.com/angular/angular-cli/pull/13716

**Comment by Destreyf** [comment]
Sorry about that, i guess i didn't look hard enough at the PR's!
