### ISSUE TITLE
Can't resolve 'router.ngfactory'

### ISSUE THREAD

**Issue by artuska** [angular/angular-cli#13721]
```
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '../../node_modules/@angular/router/router.ngfactory' in '/private/var/www/balu/balumates-ru-frontend/src/app'
```

This error throws all the time i run `ng build --configuration=production` with `"aot": true`.

This error throws all the time i run `ng serve --aot`.

Angular — 7.2.5 // any version above 7
Angular CLI — 7.3.2 // any version above 7
TypeScript — 3.2.4

**Comment by artuska** [comment]
Fixed by removing `"aot": true` and adding `--prod` to the `ng build`.

**Comment by artuska** [comment]
Still cannot understand why `"prod": true` does not work in configurations. Throws an error:

```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(prod).
```

Wtf?

**Comment by artuska** [comment]
Well, i cannot turn AOT on production build. So, how do i fix this error without disabling the AOT?

**Comment by alan-agius4** [comment]
Closing as it doesn’t follow template

**Comment by artuska** [comment]
SOLVED!

If you have this type of error probably you have upgraded from Angular 5 to 6 or 7.

Replace `"rootDir": "./src",` in your `tsconfig.json` file to `"rootDir": "./",` or just remove this parameter completely.

**Comment by gatsbyz** [comment]
@artuska This worked for me. VERIFIED!

**Comment by andrewantar** [comment]
@artuska I do not have a rootDir param in my tsconfig.json from angularCLI. Any idea how to fix while still having AOT?

**Comment by AntJanus** [comment]
@andrewantar same issue. Did you find a solution?

**Comment by gatsbyz** [comment]
`Replace "rootDir": "./src", in your tsconfig.json file to "rootDir": "./", or just remove this parameter completely.`

Doesn't work? @AntJanus  @andrewantar

**Comment by AntJanus** [comment]
@gatsbyz nope :/ I tried both. I never had `rootDir` setup in the first place.

**Comment by SuhasParameshwara** [comment]
This happens in

angular - 8.2.2
angular CLI - 8.2.1
