### ISSUE TITLE
es5BrowserSupport add Promise polyfill

### ISSUE THREAD

**Issue by rarmatei** [angular/angular-cli#13735]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

When using the new `--es5BrowserSupport` flag I noticed that **Promise** is not being included.

And I can see it's not part of the list here:
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/es2015-polyfills.js

Hence, when I open my app in IE11 I get "Promise is undefined" error. I can fix this by adding `import 'core-js/es6/promise` in my `polyfills.ts` file, but I am thinking it should be part of the defaults of the new flag?

I can submit a PR - but could somebody confirm please this is a real issue and I'm not just missing something?

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Add `import 'core-js/es6/promise;` to

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/es2015-polyfills.js

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Add `import 'core-js/es6/promise` in my `polyfills.ts` file.

**Comment by alan-agius4** [comment]
I think this makes sense to be added since Angular itself does use promises for example.
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/packages/forms/src/directives/ng_form.ts#L26

**Comment by rarmatei** [comment]
True, thanks for the quick response! Ok, PR incoming!

**Comment by alan-agius4** [comment]
@clydin, what do you reckon?

**Comment by clydin** [comment]
makes sense.  They are present within the framework.
