### ISSUE TITLE
Revert 'fix(@schematics/angular): stop offering SASS option for ng new #13444'

### ISSUE THREAD

**Issue by DGmip** [angular/angular-cli#13739]
I initially thought this was a **bug**!
`ng g c component-name --style=sass` generates  .scss files
`ng new my-project --style=sass` generates .scss files
What is the reason behind this change? 
What about those of us who prefer using the sass indented syntax? It is still supported and they are not dropping it so I don't see any reason to remove it from ng generate and ng new simply because most developers prefer the scss syntax.
This is really causing a problem for my workflow as I am using `let g:angular_cli_stylesheet_format = 'sass'` in my .vimrc so I now have to convert everything to scss and start working with syntax I don't like to use.

 https://github.com/angular/angular-cli/pull/13444

@andyg3

**Comment by alexeagle** [comment]
@nex3 can you give Angular team some guidance about whether Indented Sass (.sass files) should be considered "deprecated"? Should we stop creating new Angular projects using the old syntax?

**Comment by nex3** [comment]
As far as the Sass team is concerned, the indented syntax is fully supported.

**Comment by alexeagle** [comment]
Thanks @nex3! We'll re-introduce support for generating apps in that syntax

**Comment by DGmip** [comment]
Somewhat ironically, and after switching to scss because I was forced to, I now prefer it in some cases
