### ISSUE TITLE
how to install on raspbian

### ISSUE THREAD

**Issue by machine1104** [angular/angular-cli#13745]
hi guys
im trying to figuring out how to install angular/cli on rapbian on my raspberry pi 2
it always says command not found when trying to run "ng"

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
