### ISSUE TITLE
7.3 - xi18n with custom stylePreprocessorOptions / includePaths for SASS fails

### ISSUE THREAD

**Issue by kojilab** [angular/angular-cli#13746]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Do not know

### Description

ng xi18n doesn't like custom SCSS include paths.

## 🔬 Minimal Reproduction
I have custom scss includePaths in angular.json and when I have @import 'mixins' using those include paths, xi18n breaks because it cannot find a reference to that file. 
I tried adding those paths to angular.json / extract-i18n but the schema doesn't allow it.
## 🔥 Exception or Error

ERROR in Module build failed: 
@import "mixins";
^
      File to import not found or unreadable: mixins.
      in /home/osboxes/dev/gravgui/src/app/gw-searches/gw-searches.component.scss (line 1, column 1)

## 🌍 Your Environment
<pre><code>
ERROR in Module build failed: 
@import "mixins";
^
      File to import not found or unreadable: mixins.
      in /home/osboxes/dev/gravgui/src/app/searches/searches.component.scss (line 1, column 1)</code></pre>

**Anything else relevant?**

**Comment by kojilab** [comment]
Looks like --configuration=<config> isn't doing anything. I hacked the @angular-devkit/build-angular/src/extract-i18n/index.js file to look at the browserTargetSpec constant and the configuration was undefined.

**Comment by alftuga** [comment]
I do you have a workaround about this issue?
Thanks!

**Comment by alan-agius4** [comment]
Hi, I tried to replicate this however I am unable. 

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by filipesilva** [comment]
Closing as the original reporter never got back to us.
