### ISSUE TITLE
Angular failed to create a new Prjoekt

### ISSUE THREAD

**Issue by felix20000** [angular/angular-cli#13751]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ x] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

If i create a new Project. Then it failed to install the package @angular-devkit/build-angular
So, i cannot make a serve

## 🔥 Exception or Error
<pre><code>
npm ERR! path C:\Users\felix\Desktop\ATest\test6\node_modules\.staging\levn-59d1dcd2\README.md
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\felix\Desktop\ATest\test6\node_modules\.staging\levn-59d1dcd2\README.md'
npm ERR!  { [Error: EPERM: operation not permitted, unlink 'C:\Users\felix\Desktop\ATest\test6\node_modules\.staging\levn-59d1dcd2\README.md']
npm ERR!   cause:
npm ERR!    { Error: EPERM: operation not permitted, unlink 'C:\Users\felix\Desktop\ATest\test6\node_modules\.staging\levn-59d1dcd2\README.md'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'unlink',
npm ERR!      path:
npm ERR!       'C:\\Users\\felix\\Desktop\\ATest\\test6\\node_modules\\.staging\\levn-59d1dcd2\\README.md' },
npm ERR!   stack:
npm ERR!    'Error: EPERM: operation not permitted, unlink \'C:\\Users\\felix\\Desktop\\ATest\\test6\\node_modules\\.staging\\levn-59d1dcd2\\README.md\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path:
npm ERR!    'C:\\Users\\felix\\Desktop\\ATest\\test6\\node_modules\\.staging\\levn-59d1dcd2\\README.md',
npm ERR!   parent: 'test6' }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.3
Node: 10.15.1
OS: win32 x64
Angular: <error>
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.13.3 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            7.3.3 (cli-only)
@angular-devkit/schematics      7.3.3 (cli-only)
@schematics/angular             7.3.3 (cli-only)
@schematics/update              0.13.3 (cli-only)
rxjs                            6.3.3 (cli-only)
typescript                      3.2.4 (cli-only)

</code></pre>

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
