### ISSUE TITLE
No CSS present on new projects

### ISSUE THREAD

**Issue by b264** [angular/angular-cli#13758]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Unknown, haven't used Angular since version 4

### Description

There is no CSS present in new apps per the `ng new` command

## 🔬 Minimal Reproduction

To reproduce this bug, follow the Quick Start guide at https://angular.io/guide/quickstart

and run `ng new angular-sample` and select SCSS

Add CSS to `app.component.scss`

run `ng serve`

visit `http://localhost:4200` in browser of choice

Observe the browser not attempt to load any CSS files.

Example at https://github.com/b264/angular-sample

## 🔥 Exception or Error
<pre><code>
Browser does not load CSS.  Angular does not compile SCSS.
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.3
Node: 10.15.1
OS: linux x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
Haven't used Angular since version 4.  Brand new virtual machine running Ubuntu 18.

https://github.com/angular/angular-cli/issues/13757 is the same bug

**Comment by alan-agius4** [comment]
Hi, It is expected that no `.css` files are trying to be loaded when using the `ng serve` command. 

During serving css files are not extracted into a separate css file but rather a js file `styles.js`.

Just to clarify, the build pipeline is compiling the scss, and the browser is rendering the css, it's just that on `serve`. The file is a modular `js` file and not `css` file.

You can extract css when using the `ng build` with `-extract-css` option see https://angular.io/cli/build `-extract-css` option is not available on `ng serve` because it is an option related to build, not to serving

**Comment by b264** [comment]
This doesn't solve the problem the the CSS not actually working, either.

If you put

```
* {
  background-color: blue;
}
```
in the `app.component.scss` file, per [the commit in the example code](https://github.com/b264/angular-sample/commit/d049015a06316be24320fe8b8cccaeff886dab14), then it's not actually loaded and doesn't change anything to blue.
