### ISSUE TITLE
No functioning CSS present on new projects

### ISSUE THREAD

**Issue by b264** [angular/angular-cli#13759]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Unknown, haven't used Angular since version 4

### Description

There is no CSS present in new apps per the `ng new` command

## 🔬 Minimal Reproduction

To reproduce this bug, follow the Quick Start guide at https://angular.io/guide/quickstart

and run `ng new angular-sample` and select SCSS

Add CSS to `app.component.scss`

run `ng serve`

visit `http://localhost:4200` in browser of choice

Observe the browser not attempt to load any CSS files.  Observe none of the CSS you typed is applied to the document.

Example at https://github.com/b264/angular-sample

## 🔥 Exception or Error
<pre><code>
Browser does not load CSS.  Angular does not compile SCSS.
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.3
Node: 10.15.1
OS: linux x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
Haven't used Angular since version 4.  Brand new virtual machine running Ubuntu 18.

https://github.com/angular/angular-cli/issues/13757 is the same bug

https://github.com/angular/angular-cli/issues/13758 is the same bug

# Expected behavior

If you put

```
* {
  background-color: blue;
}
```
in the `app.component.scss` file, then stuff is changed to blue.  Literally, anything is changed to blue.  Any thing at all.  See [the commit in the example code](https://github.com/b264/angular-sample/commit/d049015a06316be24320fe8b8cccaeff886dab14).

# Actual behavior

Nothing is changed to blue.  Browser loads no CSS files.  Nothing is styled.

**Comment by b264** [comment]
You keep closing these, but the bug is still present.  This framework isn't useful at all unless it has CSS.  Any new or sample application should have CSS, and it's defective if it doesn't.  I'm assuming by continuing to close these, you are suggesting that we should start making all new projects in React instead of Angular?  Or React Native instead of Ionic?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.

When I open the browser, the styles are rendered and are visible as expected.

<img width="2036" alt="screenshot 2019-02-25 at 12 01 58" src="https://user-images.githubusercontent.com/17563226/53333113-3e9b0300-38f5-11e9-8e4e-8e36ef11479c.png">

**Comment by b264** [comment]
I can no longer reproduce the problem either.  It has something to do with caching I think, but I tried a different browser with no cookies and a cleared cache and it was still happening the other day.  So, I have no idea.  There is no more ROI for me to investigate further, though it's troubling not knowing why.  It could happen again at any time?

**Comment by alan-agius4** [comment]
Unfortunately we cannot fix something that we cannot reproduce.  If the problem happens again, please open a new issue explain what are the steps to reproduce.

Thank you.
