### ISSUE TITLE
Running 3rd party schematics should be possible using both <collection>:<schematics> and --collection <collection> syntax

### ISSUE THREAD

**Issue by tomastrajan** [angular/angular-cli#13753]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Hard to say

### Description

Following the upcoming Angular Schematics guide there seems to be an issue with the support for `--collection` flag when trying to specify 3rd party schematics collection in `ng generate`. 

The command `ng generate my-schematic-name --collection collection-name` should be equivalent to `ng generate collection-name:schematics-name` but only the second works in my case.

To be more specific, I can run `ng g @angular-extensions/model:model feature/user` but if I try to run `ng g model feature/user --collection @angular-extensions/model` then it fails as it doesn't recognize the passed collection and the `@schematics/angular` doesn't contain any `model`...

Any ideas why that could be? I am working on the windows machine ( with cygwin ) could it be paths or ?

## 🔬 Minimal Reproduction

1. `ng add @angular-extensions.model` (or any other 3rd party library which contains schematics, eg: `@angular/material` or `@ngrx/store`)

2. `ng generate model examples/user --collection @angular-extensions/model`

This results in a error where `model` schematics is not found in the `@schematics/angular` which is a default collection in Angular CLI so that means the `--collection` was ignored.

On the other hand, everything works just fine when using `ng generate @angular-extensions/model:model examples/user`.

## 🔥 Exception or Error
<pre><code>
Schematic "model" not found in collection "@schematics/angular".
Error: Schematic "model" not found in collection "@schematics/angular".
    at SchematicEngine.createSchematic (C:\projects\meetup\schematics-example-workspace\node_modules\@angular-devkit\schematics\src\engine\engine.js:232:23)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.3
Node: 10.11.0
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.3
@angular-devkit/build-angular      0.13.3
@angular-devkit/build-ng-packagr   0.13.3
@angular-devkit/build-optimizer    0.13.3
@angular-devkit/build-webpack      0.13.3
@angular-devkit/core               7.3.3
@angular-devkit/schematics         7.3.3
@angular/cdk                       7.3.3
@angular/cli                       7.3.3
@angular/material                  7.3.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.3
@schematics/angular                7.3.3
@schematics/update                 0.13.3
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @tomastrajan,

To provide use a different schematics collection via command line you need you use the `--schematic` option or first positional argument.

```
ng g --schematic @angular-extensions/model:model feature/user
ng g @angular-extensions/model:model feature/user
```

There is no such option called `--collection`, see: https://angular.io/cli/generate#schematic-commands for more information.
