### ISSUE TITLE
Add no-output-named-after-standard-event to tslint.json

### ISSUE THREAD

**Issue by wellwind** [angular/angular-cli#13750]
# 🚀 Feature request

### Command
- [X] new

### Description
There is a rule `no-output-named-after-standard-event` in codelyzer, I think it should be enabled as a default setting because we can not remember ALL the native event name. 

When we use the standard event name, that could be easily causing an unexpected problem. 

So I recommend to enable it when we just start a new project.

### Describe the solution you'd like
Add `"no-output-named-after-standard-event": true` to `tslint.json` as default when using `ng new` to create a new Angular project.

**Comment by alan-agius4** [comment]
Being addressed in https://github.com/angular/angular-cli/pull/13428

**Comment by alan-agius4** [comment]
Closing as it was addressed in #13428
