### ISSUE TITLE
Svg files in root directory dist/root

### ISSUE THREAD

**Issue by camphan12993** [angular/angular-cli#13755]
after running "ng build" there are many .svg files in the main directory of the output in the dist folder.
![52935866-23784280-338d-11e9-9778-f99940cbd1bf](https://user-images.githubusercontent.com/40196295/53309969-4e0e5200-38dd-11e9-8978-06b8c7a14211.png)
May be it's from node_modules/material-icon
can i somehow specify it that assets like this will not be placed in the root?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Kindly see: https://angular.io/cli/build (resourcesOutputPath)
