### ISSUE TITLE
ng new my-app does not have css per QuickStart Guide

### ISSUE THREAD

**Issue by b264** [angular/angular-cli#13757]
Following the new app tutorial https://angular.io/guide/quickstart

Haven't used Angular since Version 4.

When you create a new application exactly per the instructions, there is NO CSS AT ALL.  When you start the development server, no CSS file is even loaded or compiled.

CSS is an absolute must-have for any web application in 2019.  This is a critical issue.  Should we just use react?

To be clear, there is an app.component.scss file but nothing you place in it is used or compiled.

I think it's absolutely reasonable that a new application has working CSS.  It really sets the bar low for the current status of this project.

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

We do support Css and it's one of the stylesheet options that we provide.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by b264** [comment]
@alan-agius4 I have added the requested information

Sample code at https://github.com/b264/angular-sample

Verbatim output of `ng new angular-sample` and then `ng serve` contains no CSS.  There is no blue per https://github.com/b264/angular-sample/commit/d049015a06316be24320fe8b8cccaeff886dab14.  The browser inspector reports no CSS files are loaded or attempted to be loaded.
