### ISSUE TITLE
Disable start-up warnings

### ISSUE THREAD

**Issue by jonahbron** [angular/angular-cli#13765]
# 🚀 Feature request

### Command
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

My application has a couple of settings that are perfectly secure within the context of their use, but which produce (certainly helpful) warnings.  I've configured my app this way intentionally, and I don't want to see these warnings every time I start my application for development.

Here is my command:

    ng serve --host 0.0.0.0 --port 8000 --ssl true --ssl-key localhost.key --ssl-cert localhost.cert

And the warnings:

```
WARNING: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disableHostCheck" if that's the
case.
```

The top one is useful, but I don't need to be reminded, I'm already not using Angular CLI in production.

The second one is of course useful as well, but I'm running this app inside of a Docker container on my dev machine with an port exposed to the host, so that's not an issue in my case either.

### Describe the solution you'd like
A broad flag (or a number of more specific flags) to disable warnings at start time.  I have found another issue requesting something like this here:

https://github.com/angular/angular-cli/issues/11802

However, the answer given to this is to redirect stderr.  This does have the desired effect, but it _also_ disables all compile-time errors, which I _need_ for the development process.

### Describe alternatives you've considered
Either find a configuration that Angular complains about less, or simply ignore the warnings.

**Comment by mgechev** [comment]
We'd prefer to be as explicit as possible about potential security vulnerabilities. We don't believe that allowing the suppression of such warnings would be a good idea.

**Comment by Flachdachs** [comment]
I'd prefer messages that in fact tell me something about problems. But repeated messages about something that is not true in my case doesn't help.

The code that leads to this message tests the host option to be the string 'localhost' or that it *starts* with 127.x.x.x (where x is \d+). It doesn't resolve the name to make a real test to ensure it is a localhost address.

If you are developing more than one project that uses things in the browser like local storage, it is a great mess when all projects are running under localhost:4200. Of course you can change the port number - if you maintain a list which number is assigned to which project. But names are better to remember.

As a workaround you can chose a host option like `127.0.0.0.projectname.test` that can resolve to whatever you want, and `ng serve` keeps silent.

**Comment by gmerabishvili** [comment]
Hi, why does this warning shows up? What am I doing wrong? It started to show up after I updated my app from angular 5 to angular 7. Any help?
