### ISSUE TITLE
Build optimization breaks my library code

### ISSUE THREAD

**Issue by richardlnnr** [angular/angular-cli#13768]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not sure.

### Description

I created a workspace with two projects.

main-app is an application that is responsible for running the library.
domain is a library that has classes and utility methods.

When I build `main-app` in production (`optimization=true`), my utility function in domain library doesn't work.

Apparently, the problem only happens when you export arrow functions.

## 🔬 Minimal Reproduction

I created a [repository](https://github.com/richardlnnr/angular-compiler-issue) in GitHub to reproduce this error.

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.2
Node: 10.15.1
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.2
@angular-devkit/build-angular      0.13.2
@angular-devkit/build-ng-packagr   0.13.2
@angular-devkit/build-optimizer    0.13.2
@angular-devkit/build-webpack      0.13.2
@angular-devkit/core               7.3.2
@angular-devkit/schematics         7.3.2
@angular/cli                       7.3.2
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.2
@schematics/angular                7.3.2
@schematics/update                 0.13.2
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
Heya, can you elaborate on what `doesn't work` means in this context please? Does it return the wrong result, not run at all, or something else?

**Comment by richardlnnr** [comment]
When I export a function using arrow functions, apparently, the compiler ignores the code inside the function.

In the repository, I create the same code using the arrow function and a non-arrow function.
Just running the `ng serve --prod` is possible to see both functions called, and just one working.
