### ISSUE TITLE
ng test fails in VSTS build pipeline

### ISSUE THREAD

**Issue by JoseChella** [angular/angular-cli#13761]
I am deploying an angular application which includes test files in VSTS pipeline. Getting an error "You need to include some adapter that implements __karma__.start method!". Can anyone help to resolve this issue. 
ng test fails in build pipeline.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
