### ISSUE TITLE
Cannot install @angular/cli from Nexus

### ISSUE THREAD

**Issue by mistic100** [angular/angular-cli#13772]
Because of this issue https://github.com/zkat/protoduck/issues/6 (protoduck is a dependency of pacote), @angular/cli cannot be installed anymore from the Nexus NPM Proxy.

I decided to raise attention to this issue to Angular team because I think the fix could be quicker if you take care of it (and it is a total blocker for my company).

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this, however it seems to me that it is something that Nexus NPM Proxy should address.

Since as mentioned, it works fine with the public npm repository.

**Comment by mistic100** [comment]
Cannot you propose a temporary alternative ? I will take weeks before Nexus team fix the issue...

**Comment by ljharb** [comment]
`npm install --registry=https://registry.npmjs.org whatever`?

**Comment by mistic100** [comment]
The point of having Nexus as proxy is to not to call the central registry ;-) plus it has a non negligeable cost when your whole infrastructure is on the cloud.

**Comment by ljharb** [comment]
Sure, but if your proxy is broken you're pretty SOL.

**Comment by ljharb** [comment]
also yes, npm can be configured to switch registry per scope - so if all your own packages are under a scope, you can make only *that* one come from your proxy.

**Comment by mistic100** [comment]
> 
> 
> also yes, npm can be configured to switch registry per scope - so if all your own packages are under a scope, you can make only _that_ one come from your proxy.

That's cool, didn't know this option. But whatever, our admins will never accept to bypass the proxy. For know I overwrote the buggy package in the proxy.

**Comment by turnerguo** [comment]
@mistic100 can you share your solution how to fix Nexus? thanks a lot!

**Comment by mistic100** [comment]
@turnerguo https://github.com/zkat/protoduck/issues/6#issuecomment-467412811

**Comment by mistic100** [comment]
FYI the problem is actually on NPM side https://status.npmjs.org/incidents/06vhhrnp272c
