### ISSUE TITLE
Importing Locally Build Library Inside Another Library Angular v 6

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular-cli#13786]
While Trying to Import Library Into Another Library I get an Error Cannot Find Module where as the Library is there and Build in Dist Folder.

I have Build 1 Library Say Lib1 it is complied properly using ng build lib1.

When i try to Import any file from Lib1 into Lib2 i am getting error cannot Find Module ..

How to reproduce.

Build a Library 1 and then export all the Files of that Lib 1 that are to be exposed into the public_api.ts .

Add the Lib 1 as dep into Lib2 by adding it into tsconfig.lib.json file .

```
  "compilerOptions": {
    ......
    "paths":{
      "lib1": [
        "dist/lib1"
      ]
    }
  },

```

Add the Deps into Module of Lib2 and components where you want to use it . And build the library you will get the following error.

> Cannot find module 'lib1'.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
