### ISSUE TITLE
Unexpected JSON error when installing a new project

### ISSUE THREAD

**Issue by ortund** [angular/angular-cli#13781]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Used to work but I'm not sure what version it used to work on.

### Description

 A clear and concise description of the problem...
When I try to install my project, installation fails with the folliowing error:

> npm ERR! Unexpected end of JSON input while parsing near '...mon-6.0.0-beta.8.tg z"'  
> Package install failed, see above.

## 🔬 Minimal Reproduction

Just trying to install a new project should do it I think. I don't really understand how all of this works so I can't say for sure.

## 🔥 Exception or Error
<pre><code>2216 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...mon-6.0.0-beta.8.tgz"'
2216 verbose stack     at JSON.parse (<anonymous>)
2216 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
2216 verbose stack     at consumeBody.call.then.buffer (C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
2216 verbose stack     at process.internalTickCallback (internal/process/next_tick.js:77:7)
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 7.1.4
Node: 11.6.0
OS: win32 x64
Angular:
...                                                                                                                                                               Package                      Version                                             
------------------------------------------------------                           
@angular-devkit/architect    0.11.4                                              
@angular-devkit/core         7.1.4                                               
@angular-devkit/schematics   7.1.4                                               
@schematics/angular          7.1.4                                               
@schematics/update           0.11.4                                              
rxjs                         6.3.3                                               
typescript                   3.1.6
</code></pre>

**Anything else relevant?**
Probably not.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by ortund** [comment]
Yeah because node just breaks randomly one day with no changes made to the system that its on...
