### ISSUE TITLE
Web pack failed to compile

### ISSUE THREAD

**Issue by olubusade** [angular/angular-cli#13799]
# ERROR in Could not resolve module......
### Command

- ng build
- ng serve 
### Description

 I cloned working angular 4 project. Then upgraded the package.json file to the latest version of Angular 7 .
But when I run ng build or ng serve, It displays series of error. I tried to use relative path for layout-routing.module.ts but the error persists 

Kindly help me on this.
Thanks in advance.
## Minimal Reproduction

Simple steps to reproduce this bug.
ng build
or 
ng serve --host 0.0.0.0 --port 8080 --disableHostCheck
### Error

<pre>
ERROR in Could not resolve module app/optometrists-pool/optometrists-pool.module relative to app/layout/layout-routing.module.ts
ERROR in ./src/assets/css/style.css (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./src/assets/css/style.css)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /home/ubuntu/wicaredev/wicare2/wicare-practice/src/assets/css/style.css:27:13: Can't resolve './../fonts/Apple%20Chancery.eot' in '/home/ubuntu/wicaredev/wicare2/wicare-practice/src/assets/css'

  25 | @font-face {
  26 |   font-family: 'Apple Chancery';
> 27 |   src: url('./../fonts/Apple Chancery.eot');
     |             ^
  28 |   src: url('./../fonts/Apple Chancery.woff2') format('woff2'),
  29 |        url('./../fonts/Apple Chancery.eot?#iefix') format('embedded-opentype');

ERROR in ./src/assets/css/style.css (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./src/assets/css/style.css)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /home/ubuntu/wicaredev/wicare2/wicare-practice/src/assets/css/style.css:28:13: Can't resolve './../fonts/Apple%20Chancery.woff2' in '/home/ubuntu/wicaredev/wicare2/wicare-practice/src/assets/css'

  26 |   font-family: 'Apple Chancery';
  27 |   src: url('./../fonts/Apple Chancery.eot');
> 28 |   src: url('./../fonts/Apple Chancery.woff2') format('woff2'),
     |             ^
  29 |        url('./../fonts/Apple Chancery.eot?#iefix') format('embedded-opentype');
  30 |   font-weight: normal;

ERROR in ./src/assets/css/style.css (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./src/assets/css/style.css)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: /home/ubuntu/wicaredev/wicare2/wicare-practice/src/assets/css/style.css:29:13: Can't resolve './../fonts/Apple%20Chancery.eot' in '/home/ubuntu/wicaredev/wicare2/wicare-practice/src/assets/css'

  27 |   src: url('./../fonts/Apple Chancery.eot');
  28 |   src: url('./../fonts/Apple Chancery.woff2') format('woff2'),
> 29 |        url('./../fonts/Apple Chancery.eot?#iefix') format('embedded-opentype');
     |             ^
  30 |   font-weight: normal;
  31 |   font-style: normal;

ERROR in multi ./assets/css/bootstrap.min.css ./node_modules/font-awesome/css/font-awesome.min.css ./node_modules/primeng/resources/primeng.min.css ./node_modules/primeng/resources/themes/omega/theme.css ./src/assets/css/animate.css ./src/assets/css/style.css ./src/assets/css/dev.css
Module not found: Error: Can't resolve '/home/ubuntu/wicaredev/wicare2/wicare-practice/assets/css/bootstrap.min.css' in '/home/ubuntu/wicaredev/wicare2/wicare-practice'
ℹ ｢wdm｣: Failed to compile.

<code>   
</code></pre>
### Desired Behaviour

Compiled successfully

### ng v

<pre><code>
Angular CLI: 7.3.4
Node: 10.15.1
OS: linux x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.3.4
@angular-devkit/schematics        7.3.4
@angular/cli                      7.3.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6
</code></pre>
### layout-routing.module.ts

<code>
   {
                path: 'optometry-pool',
                loadChildren: 'app/optometrists-pool/optometrists-pool.module#OptometristsPoolModule',
            }
</code>

### tsconfig.app.json

<prev>
<code> 
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "commonjs",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
</code>
</prev>

### Development IDE

AWS Cloud9 IDE

**Comment by alan-agius4** [comment]
Hi, lazy routes to relative source files must start with `./`

See: https://angular.io/guide/lazy-loading-ngmodules

If the problem persists please file a new issue with a minimal repro.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

Thanks

**Comment by olubusade** [comment]
Thank you for your response @alan-agius4. I already tried changing the absolute path to relative path  before submitting the query.
But am gonna give the second suggestion a trial.

**Comment by olubusade** [comment]
Thank you @alan-agius4 as you pointed out that issue might be related to the directory. Got it resolved.
The webpack compilation is almost successful, now displaying this: 
![image](https://user-images.githubusercontent.com/34573458/53751265-d4113680-3ea3-11e9-9700-3bbb5303dd38.png)

Please does that mean I need to downgrade the Angular CLI?
Below is my angular cli  version:
![image](https://user-images.githubusercontent.com/34573458/53751484-43872600-3ea4-11e9-91e0-30127c02c974.png)
