### ISSUE TITLE
Angular is installed in two different places on Mac and calling the out of date version

### ISSUE THREAD

**Issue by franzisk** [angular/angular-cli#13794]
Hi there,

I created a folder on my users's directory to install all npm packages (I have for example, Ionic 4 installed there).

Then I installed Angular Cli 7 and it went to the correct location in: 
`~/.npm-packages/lib/node_modules/@angular/cli/bin`

When I type: `ng --version` I see the version of the one installed in `/usr/local/bin/ng` which is **1.6.0**

I had to put on my `~/.bash_profile` this:
`export PATH=~/.npm-packages/lib/node_modules/@angular/cli/bin:$PATH`

Then every time I start the computer I have to run on the terminal:
`source ~/.bash_profile`

Otherwise it keeps doing everything with that old version.

I would like to remove that old installation and keep only this one inside `.npm-packages`, how can I do that

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
