### ISSUE TITLE
Production build breaks enum string interpolation

### ISSUE THREAD

**Issue by rcketscientist** [angular/angular-cli#13798]
# 🐞 Bug report

### Command (mark with an `x`)

`ng build --prod`
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not sure.

### Description

String interpolation of enum values works in dev build and fails in prod build.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-z6xtso
Save, open locally:
`ng serve`
then
`ng serve --prod`

## 🔥 Exception or Error
No error or exception, the string interpolation for enums is `null` in `--prod`.

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.0.7
Node: 10.14.2
OS: win32 x64
Angular: 7.2.7
... common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This is by design. You cannot use string interpolation in hostbinding as these need to be staticly analysable.

See https://angular.io/guide/aot-compiler for more information about AOT.

**Comment by rcketscientist** [comment]
Why wouldn't this be an error when compiled?

**Comment by alan-agius4** [comment]
Yes it applies to inputs as well, among others.

Yeah I think there should be a form of a buildtime error instead of runtime.

However such request should be filled in https://github.com/angular/angular/issues
