### ISSUE TITLE
Progress reported on multiple lines

### ISSUE THREAD

**Issue by ChristopherKiss** [angular/angular-cli#13800]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, unsure what build

### Description
Running any cli task that outputs progress will show each step on a new line. This was previously working where it would update the current line.

I'm unsure if this is an angular cli problem, a vs code problem or windows problem. To note, the progress works fine on my work desktop, which is running windows 10.

This only seems to affect my home desktop also running Windows 10.

Direction on the culprit would help and I re-create this in the relevant locations repo, if this isn't an angular problem.

## 🔬 Minimal Reproduction
Running ng test, ng e2e or ng build will result in this.

![image](https://user-images.githubusercontent.com/24984762/53664553-debda700-3cbc-11e9-8bb4-56a3ecc32795.png)

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.4
Node: 10.15.1
OS: win32 x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.4
@angular-devkit/build-angular     0.13.4
@angular-devkit/build-optimizer   0.13.4
@angular-devkit/build-webpack     0.13.4
@angular-devkit/core              7.3.4
@angular-devkit/schematics        7.3.4
@angular/cli                      7.3.4
@ngtools/webpack                  7.3.4
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

- VSCode Version: 1.31.1
- OS Version: Windows 10 Version 1809 Build 17763.348

-- Edit
I'm using PowerShell as my terminal, but this occurs in cmd prompt too.

Testing this outside of vs code seems to work fine. Seems like this could be a vs code issue. If anyone can confirm, I'll re-create this over on their repo. Thanks.

![image](https://user-images.githubusercontent.com/24984762/53664940-255fd100-3cbe-11e9-9761-0f40eedc9d42.png)

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this, however I am unable to replicate the issue reported here.

```
PS C:\git\cli-repos\pro> ng build

Date: 2019-03-04T09:00:45.302Z
Hash: 3d3752f2347e81b477a0
Time: 12632ms
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 284 kB [initial] [rendered]
chunk {main} main.js, main.js.map (main) 8.53 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.19 MB [initial] [rendered]
PS C:\git\cli-repos\pro>
```

This might be something with your environment or settings.
