### ISSUE TITLE
ES6 Destructuring Issue with Data from API

### ISSUE THREAD

**Issue by chrisweilacker** [angular/angular-cli#13803]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Unknown

### Description

A Deconstruction Statement in a service subscription stops build of Angular project.  I have spent several hours testing that this code is valid in Repl.it for both JavaScript and TypeScript.

My code without object Deconstruction compiles fine:

```
 this.data.getScore(this.titleUrl).subscribe(data => {
  this.avgRating=data['avgrating'];
  this.numReviews=data['numOfReviews'];
  this.posterUrl = data['posterUrl']'  
``` 
     

My code with either object Deconstruction below throws an error:

```
 this.data.getScore(this.titleUrl).subscribe(data => {
  ({avgrating: this.avgRating, numOfReviews: this.numReviews, posterUrl: this.posterUrl}= data) 
```
     

```
this.data.getMovieInfo(this.titleUrl).subscribe(({id, title, poster_url, backdrop_url}) => {
        this.title=title;
        this.posterUrl=poster_url;
        this.backdropUrl=backdrop_url;
```
The errors I get back are:

ERROR in src/app/app.component.ts(84,11): error TS2459: Type 'Object' has no property 'poster_Url' and no string index signature. 

I have tested this in multiple ways to try a workaround with Destructuring this but all have failed even though almost exact code can be reproduced in Repl.it with either javascript or typescript and it passes.  
 It seems the bug is the fact that the compiler doesn't know what is on the data object as it is coming from my BackEnd API even though I do know what will be on the object and refuses to build.

## 🔬 Minimal Reproduction
To reproduce you must do the following:
1. Create a new service connecting to some api:

```
export class DataService {

  constructor(private http: HttpClient) { }

  getScore(titleUrl) {
    return this.http.get(`${environment.url}cr/score/${titleUrl}`);

  }
```

2. Create a component that accesses that service and try to deconstruct the return value on the object.
import {DataService} from './data.service';

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})

export class AppComponent implements OnInit {
//declaration of variables to display
...
    constructor(private data: DataService) {

    }

   ngOnInit() {
    this.data.getScore(this.titleUrl).subscribe(data => {
   ({avgrating: this.avgRating, numOfReviews: this.numReviews, posterUrl: this.posterUrl}= data) 
   }
     
}
```

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.component.ts(84,11): error TS2459: Type 'Object' has no property 'poster_Url' and no string index signature. 

</code></pre>

**Comment by mgechev** [comment]
@chrisweilacker this is not an issue in the CLI; looks like the type inferred by TypeScript doesn't have `poster_Url` property so you're getting a compile-time error. If you set type `any` (although I wouldn't recommend you to use `any`) of the object that is passed to the callback of `subscribe` you'll make TypeScript happy.
