### ISSUE TITLE
ng github-pages:deploy error message on Browser console "Refused to load the image..." and "Refused to load the font..."

### ISSUE THREAD

**Issue by goldenbearkin** [angular/angular-cli#1380]
1. Mac OSX (EI Capitan)
2. angular-cli: 1.0.0-beta.9
   node: 6.2.2
   os: darwin x64
3. below is my steps:

-> ng new testGitHub
-> after setup github repos
-> ng github-pages:deploy --message "Optional commit message"
1. I just deploy the barebone project on github, the following error message displays on github page console: 

Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIw4ABEAAAABQcAAAQABAAAAAAAAAAAAAAAAAAAAA…hgZiCKVViwAiVhsAFFYyNisAIjRLMJCgMCK7MLEAMCK7MRFgMCK1myBCgGRVJEswsQBAIrAA==' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.

Refused to load the image 'https://xxxxxxxxx.github.io/favicon.ico' because it violates the following Content Security Policy directive: "img-src data:".

**Comment by filipesilva** [comment]
Can you give me the page url and repo so I could look? I can't seem to repro this myself.

**Comment by smitthakkar96** [comment]
I also have the same issue 
my repo github.com/papendong/lendcypher_refined

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
