### ISSUE TITLE
wrong resolving path

### ISSUE THREAD

**Issue by ngiangphong** [angular/angular-cli#13818]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I developed lib which has follow structure
-catalogs
--src
---lib
----components
-----component1
------component1.component.ts
-----component2
------component2.component.ts
-----index.ts
----catalogs.module.ts

index.ts in components groups all components into arrays:
<pre><code>import { Component1 } from "./component1/component1.component";
import { Component2 } from "./component2/component2.component";

export const CatalogsComponents = [ Component1, Component2 ];
</code></pre>

The array is used in catalogs.module.ts:
<pre><code>import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CatalogsComponents } from './components';

@NgModule({
  imports: [
    CommonModule,
    FormsModule
  ],
  declarations: [...CatalogsComponents]
})
export class CatalogsModule { }
</code></pre>

When I try to build a project I Have a follows exception:
projects/catalogs/src/catalogs.ts(7,42): error TS2307: Cannot find module './lib/component1/component1.component'.
projects/catalogs/src/catalogs.ts(8,42): error TS2307: Cannot find module './lib/component2/component2.component'.

I feel it try to find resolve component paths
 "./component1/component1.component"
 "./component2/component2.component"
by location of catalogs.module.ts file, not index.ts file.

## 🔬 Minimal Reproduction
Create a project as in the bug description.

## 🔥 Exception or Error
<pre><code>projects/catalogs/src/catalogs.ts(7,42): error TS2307: Cannot find module './lib/component1/component1.component'.
projects/catalogs/src/catalogs.ts(8,42): error TS2307: Cannot find module './lib/component2/component2.component'.
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 7.1.0
Node: 8.11.3
OS: win32 x64
Angular: 6.1.6
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.6.8
@angular-devkit/build-angular      0.6.8
@angular-devkit/build-ng-packagr   0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core               0.6.8
@angular-devkit/schematics         7.1.0
@angular/cdk                       6.4.6
@angular/cli                       7.1.0
@angular/compiler-cli              7.1.0
@angular/flex-layout               6.0.0-beta.15
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.0.8
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.1.1
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.8.3
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, can you kindly try to update to the latest version `ng-packagr`? 

If the problem persists kindly provide a minimal reproduction, as it seems that the error is occurring from some file that was not provided above.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
