### ISSUE TITLE
Improve name validation with component schematic (and others) 

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular-cli#13824]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

Using dots in component name when using component schematic (might also happen with other schematics) should fail. I.e. `ng generate component a.b.x` should fail.

I noticed that people who are new to Angular tend to use the schematic like this for the first time:
```sh
ng generate component hello-world.component
```
which produces something funky like this:
```ts
export class HelloWorld.ComponentComponent
```

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Use some whitelist regex to check the component's name before.

By the way, why does the component's selector allow dots in the regular expression below?
https://github.com/angular/angular-cli/blob/eca5dc322f11360b82309c31ed6a716a894fc051/packages/schematics/angular/utility/validation.ts#L20

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
```sh
ng generate component hello-world.component
echo D'OH!
git reset --hard
git clean -d -f
ng generate component hello-world
```

Anyway, I am in for a pull request.

**Comment by alan-agius4** [comment]
This also relates to https://github.com/angular/angular-cli/issues/12868

I am not sure why a dot is allowed there, maybe @clydin knows.

**Comment by clydin** [comment]
It's a valid character in an HTML element name.  That regex is technically overly restrictive as well.  unicode characters should be allowed.

**Comment by dgp1130** [comment]
Should we dupe this against #11051? That one has to do with `ng new` while this has to do with `ng generate`, but they are both schematics related and likely have the same root cause?

**Comment by alan-agius4** [comment]
@dgp1130, I think it’s best to keep these separate since this is a separate validate pattern. Unless we want to create a new master issue to track various validation issues.
