### ISSUE TITLE
Build with ng build --prod slow

### ISSUE THREAD

**Issue by sameer05k21a0440** [angular/angular-cli#13828]
# 🐞 Bug report

### https://stackoverflow.com/questions/54995084/how-to-decrease-size-of-bundle-main-js-file-using-angular-6

```
command:  ng build --prod 

1. After deployed application it's too slow than ng serve --prod .
2. I need to increase speed of loading page in production mode.
```

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by sameer05k21a0440** [comment]
https://stackoverflow.com/questions/55015338/ng-build-prod-bundle-too-slow-than-ng-serve-prod

**Comment by alan-agius4** [comment]
Closing as this not following the issue template
