### ISSUE TITLE
Animations are broken on prod AOT build when inheriting styles from base object

### ISSUE THREAD

**Issue by adamduren** [angular/angular-cli#13833]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Not that I'm aware of

### Description

 In an effort to be DRY I have a base style object for some of my more complex animations. Here is a simplified example.

```typescript
const baseStyleRed = {
  backgroundColor: 'red',
};

const baseStyleBlue = {
  backgroundColor: 'blue',
};

export const appAnimations = [
  trigger('boxTransition', [
    state(
      'red',
      style({
      ...baseStyleRed,
      })
    ),

    state(
      'blue',
      style({
        ...baseStyleBlue,
      }),
    ),

    transition('blue <=> red', [animate('250ms ease-out')]),
  ]),
];
```

Essentially AOT breaks the animation because it doesn't spread the base styles into object passed to the style function. I was able to determine this by looking at the AOT output.

I have included a reproduction below. It should switch between a red and blue square and never be green. If it's green then you know the styles for the animation states are not being applied.

The issue disappears if you check out the commit before the latest and run the prod build again

## 🔬 Minimal Reproduction

[Reproduction Repo](https://github.com/adamduren/angular-animation-issue/)
[Commit that introduces the bug](https://github.com/adamduren/angular-animation-issue/commit/6ed5395d08ec9a6db8444fb585ead1e3b2d6ffe5)

```
> git clone git@github.com:adamduren/angular-animation-issue.git
> cd angular-animation-issue
> npm i
> npm run build -- --prod
> cd dist/angular-animation-issue
> npx http-server -p 8000
```

## 🔥 Exception or Error
<pre><code>N/A</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 7.2.4
Node: 10.14.1
OS: darwin x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4</code></pre>

**Anything else relevant?**

Recent discussion / thoughts on: https://github.com/angular/angular-cli/issues/8577

**Comment by adamduren** [comment]
I should have noted in the description that disabling the `aot` flag fixes the issue. Also I checked before with github and couldn't find a similar issue. However searching with Google turned up https://github.com/angular/angular/issues/25317 which I believe to be related.

**Comment by adamduren** [comment]
As a workaround adding `export` to my base styles seems to have fixed the issue. It would be great if the compiler would tell you that and would have saved hours.

**Comment by alan-agius4** [comment]
Closing in favor of https://github.com/angular/angular/issues/25317

As this is not a CLI, but a compiler issue.

Thanks.
