### ISSUE TITLE
How to generate Angular.json file

### ISSUE THREAD

**Issue by AkashSurana** [angular/angular-cli#13831]
My current application was in Angular 4 without Angular CLI. So I never had Angualr.json file or Angular-cli.json file. Now we want to generate that Angular CLI or angular.json file. Because this file is not available it is not taking any of the ng commands like ng serve or ng g c testing

How can I generate the file without using ng new command because ng new will create a new project which I don't want. I want to support my existing project.

Few notes on my project :
1. We are launching multiple application from one folder
2. We are launching each application from the ASPX page without using index.html.

Please see the screen shot attached of the error and the folder structure of my project
<img width="663" alt="error" src="https://user-images.githubusercontent.com/27774371/53883493-263a8f00-403f-11e9-82e9-d8f69daeffc2.PNG">
<img width="519" alt="folder_structure_1" src="https://user-images.githubusercontent.com/27774371/53883496-26d32580-403f-11e9-98de-1e1264db855f.PNG">
<img width="584" alt="folder_structure_2" src="https://user-images.githubusercontent.com/27774371/53883498-26d32580-403f-11e9-88c4-a9b1bd843813.PNG">

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
