### ISSUE TITLE
Publish Builder

### ISSUE THREAD

**Issue by krotscheck** [angular/angular-cli#13836]
# 🚀 Feature request
Implement a Publish builder for multi-project repositories.

### Command (mark with an `x`)
```
- [x] publish
```

### Description
Since.... v6 I think? the Angular CLI supports multiple projects in the same git repository. Publishing these is a bit of a pain, as each project has to have its version manually updated in the `package.json`,  output from `ng build <app|library> --prod` has to be manually zipped, and for each target I have to manually invoke `npm publish <tarball>`.

### Describe the solution you'd like
It'd be nice, if the CLI shipped with an architect target for publishing to npm or an internal repository. I imagine the Schema might look something like this:

```
{
  "$schema": "http://json-schema.org/schema",
  "title": "Publish Target",
  "description": "Package publish target for Architect.",
  "type": "object",
  "properties": {
    "versionStrategy": {
      "type": "string",
      "description": "The versioning strategy to use for generating a new package version. Valid options are 'parent', 'manual', 'conventional-commits'."
    },
    "registry": {
      "type": "string",
      "description": "The NPM registry to publish to."
    },
    "git-commit": {
      "type": "boolean",
      "description": "Should changes to each package.json be committed?"
    },
    "git-tag": {
      "type": "boolean",
      "description": "Should a tag be generated for each package?"
    },
    "git-push": {
      "type": "boolean",
      "description": "Should the generated commit and tags be pushed to master?"
    }
  },
  "additionalProperties": false,
  "required": [
    "versionStrategy"
  ]
}
```

### Describe alternatives you've considered
I've written my own jenkinsfile, gitlab build, etc, to manage this, however updating the versions before release is still a bit annoying.

**Comment by alan-agius4** [comment]
Relates to https://github.com/angular/angular-cli/issues/11486

I'd suggest putting more context in that issue.
