### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by ovione** [angular/angular-cli#13846]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I do a http.post and I proxy it with the proxy.conf.json to a site with https. The site I tried to post to has a self signed certificate. 
When I do a POST then I get a message in my server console

[HPM] Error occurred while trying to proxy request ?_action=logout from localhost:3000 to https://login.dev.data.intra/auth/json/sessions (SELF_SIGNED_CERT_IN_CHAIN) (https://nodejs.org/api/errors.html#errors_common_system_errors)
 

### Describe the solution you'd like
I tries to use ng serve option --ssl true|false
but keep having the error.

### Describe alternatives you've considered
Should a proxy it with some flag or should I install the self singed certificate somewhere ?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
