### ISSUE TITLE
🐞 Unable to write a reference to AppComponent with ng 8.0.0-beta.5

### ISSUE THREAD

**Issue by JustinMindDev** [angular/angular-cli#13844]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: v8.0.0-beta.4

### Description

Any commands above (with or without --prod) doesn't execute completly. (Error output below)

## 🔬 Minimal Reproduction
<pre><code>ng new ivy-bug --enable-ivy</code></pre>

## 🔥 Exception or Error
<pre><code>
ERROR in Unable to write a reference to AppComponent in D:/Projects/Private/unicode-test/src/app/app.component.ts from D:/Projects/Private/unicode-test/src/app/app.module.ts
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.0-beta.5
Node: 10.15.2
OS: win32 x64
Angular: 8.0.0-beta.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.14.0-beta.5
@angular-devkit/build-angular     0.14.0-beta.5
@angular-devkit/build-optimizer   0.14.0-beta.5
@angular-devkit/build-webpack     0.14.0-beta.5
@angular-devkit/core              8.0.0-beta.5
@angular-devkit/schematics        8.0.0-beta.5
@angular/cli                      8.0.0-beta.5
@ngtools/webpack                  8.0.0-beta.5
@schematics/angular               8.0.0-beta.5
@schematics/update                0.14.0-beta.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6
</code></pre>

**Anything else relevant?**
No, its most likely a compiler related issue.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

This is currently being tracked here: https://github.com/angular/angular/issues/29140
