### ISSUE TITLE
servePath not supported in angular.json

### ISSUE THREAD

**Issue by zalintyre** [angular/angular-cli#13845]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I didn't want to use `--serve-path="/path"` on every ng serve, so I tried to specify it in angular.json. The schema.json states this should be correct.

## 🔬 Minimal Reproduction

angular.json (Minimal example):

```json
{
  "$schema": "src/ui/node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ui": {
      "root": "src/ui/src",
      "sourceRoot": "src/ui/src",
      "projectType": "application",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "baseHref": "/path",
            "deployUrl": "/path",
            "servePath": "/path",
            "outputPath": "src/ui/dist",
            "index": "src/ui/src/index.html",
            "main": "src/ui/src/main.ts",
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/ui/src/environments/environment.ts",
                  "with": "src/ui/src/environments/environment.prod.ts"
                }
              ],
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "ui:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "ui:build:production"
            }
          }
        },
      }
    },
  },
  "defaultProject": "ui"
}

```

## 🔥 Exception or Error
<pre><code>
$ ng serve
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(servePath).
</code></pre>

## 🌍 Your Environment
<pre><code>
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.5
Node: 8.10.0
OS: linux x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi. the `servePath` should be under the `serve` and not `build` options.
