### ISSUE TITLE
CleanCss breaks :host-context(selector selector)

### ISSUE THREAD

**Issue by SebastianPodgajny** [angular/angular-cli#13854]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
CleanCss plugin breaks :host-context(selector selector) (space is important)

https://github.com/angular/angular/issues/23034#issue-309249510
#10454

## 🔬 Minimal Reproduction

Use :host-context(something .somethingElse) and run ng build --prod

My current fix is to remove CleanCss plugin with ngx-build-plus
```
cfg.optimization.minimizer = cfg.optimization.minimizer.reduce((acc, minimizer) => {
  return minimizer.constructor.name === 'CleanCssWebpackPlugin' ? acc : [...acc, minimizer];
}, []);
```
without this plugin everything works as expected

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.5
Node: 10.15.1
OS: darwin x64
Angular: 7.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.5
@angular-devkit/build-optimizer   0.13.5
@angular-devkit/build-webpack     0.13.5
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.3.5
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, this looks like a bug in clean-css, hence I'd suggest you open an issue their issue tracker.

As a workaround you should be able to use special comments to make clean-css ignore a block of CSS:

```css
/* clean-css ignore:start */
:host-context(selector selector){
	color: red;
}
/* clean-css ignore:end */
```

**Comment by alan-agius4** [comment]
Just opened a issue in their issue tracker: https://github.com/jakubpawlowicz/clean-css/issues/1062
