### ISSUE TITLE
baseHref breakes html of head

### ISSUE THREAD

**Issue by DzmVasileusky** [angular/angular-cli#13851]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] serve
```

### Is this a regression?

 Haven't noticed

### Description

 When adding baseHref parameter to angular.json config ng serve produce html with broken head layout.

## 🔬 Minimal Reproduction

index.pug
```
doctype html
html(lang="en")
    head(lang="en")
        meta(charset="UTF-8")
    body.no-background.crx-app: crx-app
```
compiles by pug.loader to
`<!DOCTYPE html><html lang="en"><head lang="en"><meta charset="UTF-8"></head><body class="no-background crx-app"><crx-app></crx-app></body></html>`

but served page HTML is
`<!DOCTYPE html><html lang="en"><head lang="en"><<base href="/test/">meta charset="UTF-8"></head><body class="no-background crx-app"><crx-app></crx-app><script type="text/javascript" src="runtime.js"></script><script type="text/javascript" src="polyfills.js"></script><script type="text/javascript" src="styles.js"></script><script type="text/javascript" src="scripts.js"></script><script type="text/javascript" src="vendor.js"></script><script type="text/javascript" src="main.js"></script></body></html>`

`<base href="/test/">` is inserted in `<meta charset="UTF-8">`

part of config
```
"build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
                    "baseHref": "/test/",
          }
}
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.3
Node: 8.11.4
OS: darwin x64
Angular: 7.2.7
</code></pre>

**Comment by skreborn** [comment]
Seems to be inserted [here](https://github.com/angular/angular-cli/blob/af88936ef504836f77838438c8bdbe99f40d197d/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/index-html-webpack-plugin.ts#L201-L204) if it helps with the investigation. In the meantime, can you provide a reproduction, @DzmVasileusky?

**Comment by DzmVasileusky** [comment]
@skreborn I'll try to prepare something
I guess maybe `+1` is excess in `headElement.__location.startTag.endOffset + 1`

**Comment by skreborn** [comment]
I would assume that the `+ 1` is on purpose, as `headElement.__location.startTag.endOffset` should mark the very last character of the opening tag, so that plus one should point at the correct location.

**Comment by DzmVasileusky** [comment]
It depends on how `insert` method is working. 
However the bug can be in `endOffset` calculation as well. I'll try to come with a repo to work further

**Comment by DzmVasileusky** [comment]
@alan-agius4 
You have already noticed it. Cool. 
I just have created simple repo and figured it out also. 
Insertion lacks when it's a single line without spaces and line breakes

**Comment by DzmVasileusky** [comment]
It seems that the issue still reproducable when base href in presented in the html.
It's not a critical issue since this is more like an edge case but still.

<!DOCTYPE html><html lang="en"><head lang="en"><meta charset="UTF-8"><base href="/test/"></head><body class="no-background crx-app"><crx-app></crx-app></body></html>

but served page HTML is
<!DOCTYPE html><html lang="en"><head lang="en"><meta charset="UTF-8"><base href="/lease/">/head><body class="no-background crx-app"><crx-app></crx-app><script type="text/javascript" src="runtime.js"></script><script type="text/javascript" src="polyfills.js"></script><script type="text/javascript" src="styles.js"></script><script type="text/javascript" src="scripts.js"></script><script type="text/javascript" src="vendor.js"></script><script type="text/javascript" src="main.js"></script></body></html>
