### ISSUE TITLE
the library schematic generates a file name which isn't camel-case

### ISSUE THREAD

**Issue by wKoza** [angular/angular-cli#13862]
By convention, files follow the kebab-case convention except (at least) for `public_api.ts`.

https://github.com/angular/angular-cli/blob/0715beb65c037992b5295ec1417f80cfd2fc890c/packages/schematics/angular/library/schema.json#L18-L22

Should not we change it following the kebab-case convention ? Currently, the documentation refers to a file named `index.ts` which is wrong. (PR https://github.com/angular/angular/pull/29200).

cc @gkalpak

**Comment by alan-agius4** [comment]
I think it make sense to change to it kebab case.
