### ISSUE TITLE
resourcesOutputPath ignored during build

### ISSUE THREAD

**Issue by aggiustino** [angular/angular-cli#13863]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Using `resourcesOutputPath` config in angular.json or `--resources-output-path` flag in the command line does not change the "styles" output folder.

### Expected behaviour

Setting `resourcesOutputPath` to any folder name, the generated CSS from the "styles" configuration should be outputted in a subfolder. 

## 🔬 Minimal Reproduction

- Create a new project using the CLI: `ng new test-app`
- add `"resourcesOutputPath": "resources"` in angular.json under architect --> build --> options
- run `ng build --prod`

Same happens running `ng build --prod --resources-output-path=resources`.

## 🌍 Your Environment

<pre><code>
Angular CLI: 7.3.5
Node: 8.15.0
OS: darwin x64
Angular: 7.2.8
</code></pre>

**Comment by alan-agius4** [comment]
Hi, the `resourcesOutputPath` is meant to output the css resources in that directory and not the the css itself.

Such resources are images and fonts that are referenced within a css file.
