### ISSUE TITLE
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[t]:

### ISSUE THREAD

**Issue by Vicky3535** [angular/angular-cli#13873]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [x] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
I'm getting the error, when I'm accessing the web page. There is no build error. I used the below command for production build: 
"ng build --prod"

## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): Error: StaticInjectorError[t]: 
  StaticInjectorError[t]: 
    NullInjectorError: No provider for t!
Error: StaticInjectorError[t]: 
  StaticInjectorError[t]: 
    NullInjectorError: No provider for t!
    at e.get (main.dcb161de36f0da41610d.bundle.js:1)
    at main.dcb161de36f0da41610d.bundle.js:1
    at m (main.dcb161de36f0da41610d.bundle.js:1)
    at e.get (main.dcb161de36f0da41610d.bundle.js:1)
    at main.dcb161de36f0da41610d.bundle.js:1
    at m (main.dcb161de36f0da41610d.bundle.js:1)
    at e.get (main.dcb161de36f0da41610d.bundle.js:1)
    at ht (main.dcb161de36f0da41610d.bundle.js:1)
    at e.get (main.dcb161de36f0da41610d.bundle.js:1)
    at ht (main.dcb161de36f0da41610d.bundle.js:1)
    at o (polyfills.26ffee7268c04b69baf1.bundle.js:1)
    at o (polyfills.26ffee7268c04b69baf1.bundle.js:1)
    at polyfills.26ffee7268c04b69baf1.bundle.js:1
    at t.invokeTask (polyfills.26ffee7268c04b69baf1.bundle.js:1)
    at Object.onInvokeTask (main.dcb161de36f0da41610d.bundle.js:1)
    at t.invokeTask (polyfills.26ffee7268c04b69baf1.bundle.js:1)
    at r.runTask (polyfills.26ffee7268c04b69baf1.bundle.js:1)
    at i (polyfills.26ffee7268c04b69baf1.bundle.js:1)
    at e.invokeTask [as invoke] (polyfills.26ffee7268c04b69baf1.bundle.js:1)
    at d (polyfills.26ffee7268c04b69baf1.bundle.js:1)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.1.2
Node: 10.14.2
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.11.2
@angular-devkit/core         7.1.2
@angular-devkit/schematics   7.1.2
@schematics/angular          7.1.2
@schematics/update           0.11.2
rxjs                         6.3.3
typescript                   3.1.6
</code></pre>

**Anything else relevant?**
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "~5.0.0",
    "@angular/compiler": "~5.0.0",
    "@angular/compiler-cli": "~5.0.0",
    "@angular/core": "~5.0.0",
    "@angular/flex-layout": "^6.0.0-beta.18",
    "@angular/forms": "~5.0.0",
    "@angular/http": "~5.0.0",
    "@angular/platform-browser": "~5.0.0",
    "@angular/platform-browser-dynamic": "~5.0.0",
    "@angular/platform-server": "~5.0.0",
    "@angular/router": "~5.0.0",
    "@angular/upgrade": "~5.0.0",
    "@ngx-loading-bar/core": "^2.0.0",
    "@ngx-loading-bar/router": "^2.0.0",
    "@swimlane/ngx-charts": "^10.1.0",
    "@swimlane/ngx-graph": "^4.1.1",
    "angular-datatables": "^7.0.0",
    "angular-gridster2": "^7.1.0",
    "angular-in-memory-web-api": "~0.5.0",
    "angular-tag-cloud-module": "^2.4.0",
    "angular2-cookie": "^1.2.6",
    "angular2-justgage": "^0.3.0",
    "bootstrap": "^4.0.0-alpha.6",
    "chart.js": "^2.7.2",
    "chartjs-plugin-zoom": "^0.6.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "cronstrue": "^1.1.0",
    "d3": "^5.5.0",
    "d3-array": "^1.2.4",
    "d3-brush": "^1.0.6",
    "d3-color": "^1.2.3",
    "d3-force": "^1.1.2",
    "d3-format": "^1.3.2",
    "d3-hierarchy": "^1.1.8",
    "d3-interpolate": "^1.3.2",
    "d3-scale": "^2.1.2",
    "d3-selection": "^1.3.2",
    "d3-shape": "^1.2.2",
    "d3-time-format": "^2.1.3",
    "d3-transition": "^1.1.3",
    "datatables.net": "^1.10.19",
    "datatables.net-bs4": "^1.10.19",
    "font-awesome": "^4.7.0",
    "install": "^0.10.1",
    "jquery": "^3.2.1",
    "moment": "^2.22.0",
    "ng-org-chart": "^1.2.0",
    "ng-pick-datetime": "^5.0.0-beta.15",
    "ng-sidebar": "^6.0.4",
    "ng2-auto-complete": "^0.12.0",
    "ng2-dnd": "^5.0.2",
    "ng2-drag-drop": "^3.0.2",
    "ng2-popover": "0.0.14",
    "ng2-search-filter": "^0.4.7",
    "ng2-toastr": "^4.1.2",
    "ng2-trim-directive": "^2.1.2",
    "ng2-truncate": "^1.3.11",
    "ngx-breadcrumbs": "0.0.3",
    "ngx-cookie-service": "^1.0.10",
    "ngx-json-viewer": "^2.4.0",
    "ngx-pagination": "^3.0.3",
    "npm": "^5.5.1",
    "package.json": "^2.0.1",
    "rxjs": "^5.5.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@types/chartjs": "0.0.31",
    "@types/datatables.net": "^1.10.15",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "^2.0.3",
    "@types/jquery": "^3.3.29",
    "@types/node": "^6.0.45",
    "jasmine": "~2.4.1",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "lodash": "^4.17.11",
    "phantomjs-prebuilt": "^2.1.7",
    "popper.js": "^1.12.9",
    "protractor": "^5.4.1",
    "ts-node": "^3.3.0",
    "tslint": "^3.15.1",
    "typescript": "2.4.2"
  },

**Comment by alan-agius4** [comment]
I'm sorry, but we cannot fix an issue without being able to reproduce it.

Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
