### ISSUE TITLE
Property 'map' does not exist on type 'Observable<Response>'.

### ISSUE THREAD

**Issue by bkchodi** [angular/angular-cli#13879]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
![Screenshot (4)](https://user-images.githubusercontent.com/20543950/54162274-ed554c80-447a-11e9-9cad-3c756bc01c2a.png)

**Comment by bkchodi** [comment]
import {Observable} from 'rxjs/Rx';
import 'rxjs/add/operator/map';
import 'rxjs/Rx';
not working by the above!! help me!!!
![Screenshot (4)](https://user-images.githubusercontent.com/20543950/54162344-31e0e800-447b-11e9-9e78-bc3efba12784.png)

**Comment by mgechev** [comment]
For support requests, please use StackOverflow or our Gitter channel.
