### ISSUE TITLE
Angular 4.2.4 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by stevenruizhang** [angular/angular-cli#13874]
when run ng build --prod --aot --sourcemaps=false --build-optimizer --vendor-chunk=true get issue below:
<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000010283825879 <JSObject>
    1: visit [00000026AAB822D1 <undefined>:~7317] [pc=000002DC2D142B7C](this=0000010C6862E959 <TreeWalker map = 000003A5A368F149>,node=0000000221697581 <AST_SymbolRef map = 0000003D112043B1>)
    2: arguments adaptor frame: 2->1
    3: _walk [00000026AAB822D1 <undefined>:~479] [pc=000002DC2D5FAD37](this=0000000221697581 <AST_SymbolRef map = 0000003D112043B1>,visitor=0000010C6862E959 <TreeWalke...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::WasmDebugInfo::SetupForTesting
 6: v8::internal::WasmDebugInfo::SetupForTesting
 7: v8::internal::WasmDebugInfo::SetupForTesting
 8: v8::internal::WasmDebugInfo::SetupForTesting
 9: v8::internal::SharedFunctionInfo::SetScript
10: v8::internal::JSReceiver::class_name
11: v8::internal::SourcePositionTableIterator::Advance
12: v8::internal::SourcePositionTableIterator::Advance
13: 000002DC2D0043C1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! caap@0.0.0 build-dev: `ng build --prod --env=ciodev --aot --build-optimizer --vendor-chunk=true`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the caap@0.0.0 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\steven.rui.zhang\AppData\Roaming\npm-cache\_logs\2019-03-11T06_50_53_564Z-debug.log
PS C:\Project\CAPP\Git\Web> [default]
Unable to find type [default].
At line:1 char:1
+ [default]
+ ~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (default:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

but I add configuration --max-old-space-size=8192 in before build and it can work in local. But still get same issue  when build in Azure Pipeline build server, 
![image](https://user-images.githubusercontent.com/13114985/54133893-e108c980-4451-11e9-91c6-d29564abe9c0.png)

![image](https://user-images.githubusercontent.com/13114985/54133968-085f9680-4452-11e9-8770-ce3f00961801.png)

PS C:\Project\CAPP\Git\Web> node -v
v8.11.3
PS C:\Project\CAPP\Git\Web> npm -v
5.6.0
TYpeScript: 3.2.2

**Comment by alan-agius4** [comment]
Hi, kindly try to update to the latest version of the CLI.

If the problem persists, kindly open a new issue and fill in the details requested.

Thanks.

**Comment by stevenruizhang** [comment]
> Hi, kindly try to update to the latest version of the CLI.
> 
> If the problem persists, kindly open a new issue and fill in the details requested.
> 
> Thanks.

which CLI version do u suggest to update? Do i also need to update the Angular to which version?
Beside update CLI, any other way to resolve this issue? Update CLI will impact the current code?

**Comment by alan-agius4** [comment]
I suggest you update to the current latest CLI version is 7.3.x while the current latest angular is 7.2.x.

The versions of Angular you are using are currently out of LTS support as this ended on September 23, 2018. For a full list of current supported versions see; https://angular.io/guide/releases#support-policy-and-schedule.

I can really tell if you need to do any code changes as this really depend on what version of the CLI you are using, in most cases code cases should be minimal if any when updating using [ ng update](https://angular.io/cli/update).
