### ISSUE TITLE
Generate component command working differently for different names

### ISSUE THREAD

**Issue by sahilbabbar** [angular/angular-cli#13883]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Not sure. Never ran into this use-case earlier.

### Description

 A clear and concise description of the problem...

In order to create a new component inside a module, `ng g c` command behaves differently for different component names; which is very weird.

## 🔬 Minimal Reproduction

The following screenshot depicts the simple reproduction flow.

![Screenshot_3](https://user-images.githubusercontent.com/6317330/54177532-8c4c6980-44b8-11e9-836a-582abd4187de.png)

## 🔥 Exception or Error
NA.

## 🌍 Your Environment
<pre><code>
    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.0.8
Node: 10.15.0
OS: win32 x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3
</code></pre>

**Anything else relevant?**

NA.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided. Kindly try to update to the latest version of the CLI.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by sahilbabbar** [comment]
Hi @alan-agius4, I have attached the repository in the above description. 

https://github.com/sahilbabbar/sahilbabbar.com
