### ISSUE TITLE
ng build does not work with library

### ISSUE THREAD

**Issue by jzap71023** [angular/angular-cli#13889]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Created a library using ng g library my-lib
Created a service inside of said library using ng g s logger --project my-lib
Attempted to use ng build my-lib and get the following errors:
ENOENT: no such file or directory, scandir
Error: ENOENT: no such file or directory, scandir 
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries
    at foundBinariesList
    at foundBinaries
    at Object.module.exports.missingBinary
    at module.exports
    at Object.<anonymous>
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
    at Module._compile (module.js:652:30)

(I removed the paths as to protect personal information)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Kindly follow the issue template.


Thanks
