### ISSUE TITLE
I can't create a workspace with  'ng new myworkspace' command.

### ISSUE THREAD

**Issue by alika40** [angular/angular-cli#13887]
When I try like so: 'ng new myapp' it generate the following error below:

![Screenshot (184)](https://user-images.githubusercontent.com/36970557/54196600-c0745a00-44b9-11e9-85ac-63eb23eb52ec.png)

This is my Angular version and my first installation:
![Screenshot (185)](https://user-images.githubusercontent.com/36970557/54196761-177a2f00-44ba-11e9-934e-303b6b347f96.png)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
