### ISSUE TITLE
Unexpected value imported by the module 'AppModule'. Please add an annotation

### ISSUE THREAD

**Issue by KeyStorke** [angular/angular-cli#13890]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I see the issue and that issue looks like a bug. The demo here: https://stackblitz.com/edit/angular-rbzdus

The same problem happens for `ng build --prod` as well.

## 🔬 Minimal Reproduction
You can do it [here](https://stackblitz.com/edit/angular-rbzdus)

`MatSnackBar` used in the [notification.component.ts](https://stackblitz.com/edit/angular-rbzdus?embed=1&file=src/app/notification/notification.component.ts)

## 🔥 Exception or Error
<pre><code>
Unexpected value 'MatSnackBar' imported by the module 'AppModule'. Please add a @NgModule annotation.
</code></pre>

**Anything else relevant?**
 #7409

**Comment by clydin** [comment]
It appears the demo is importing the component and not the module.

**Comment by KeyStorke** [comment]
The issue was resolved.
**Solution**: change `MatSnackBar` to `MatSnackBarModule` in the `module.ts`
