### ISSUE TITLE
Ability to override the port when running "ng test"

### ISSUE THREAD

**Issue by rlove** [angular/angular-cli#13891]
# 🚀 Feature request

Would like to be able to specify an override port on the command line when running `ng test`

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

There is currently no easy way to override the port when running `ng test`
Currently `serve` and `e2e` have the ability to override the port via the cli  `test` is unable to do this, so part of the request is for being consistant with the commands.      My need is for ability to run multiple conccurent tests on the same jenkins node, and they need to avoid port conflicts.

I have not looked at the implmentation of test yet.   But the karma cli command does support overriding the port.

### Describe the solution you'd like
Support `--port <portnumber>`

### Describe alternatives you've considered
Having more than on karma.config.js file and use the --karma-config <file>.   However our file is highly customized and want to try to maintain two files that differ only on port.   So another option is a script to change port in the file before run.

**Comment by alan-agius4** [comment]
Hi @rlove, the port value in karma is actually not the port to use but rather the base port.

If the port provided is currently in use karma will keep incrementing this by 1 value until it finds an available port, which should avoid conflicts.

On another note, you can always set the port value to 0. Port 0 is like a wildcard port that tells the system to find a suitable available port number.

Hence, I unless I am missing something I don't think we should increase the public api surface to add an addition port argument for tests.
