### ISSUE TITLE
Angular universal schematic broken on v7.3.5

### ISSUE THREAD

**Issue by Fattouh92** [angular/angular-cli#13896]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [X] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I see it working in 7.2.4

### Description

 A clear and concise description of the problem...
Running `ng add @nguniversal/express-engine --clientProject [existingProjectName]` only installs `@nguniversal/express-engine@7.1.1` and does not create or change files

## 🔬 Minimal Reproduction

Update to cli v7.3.5
run `ng new new-project`
run `ng add @nguniversal/express-engine --clientProject new-project`
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.5
Node: 8.12.0
OS: darwin x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cli                      7.3.5
@ngtools/webpack                  7.1.4
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.23.1

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@Fattouh92, before running `ng add` are you changing the directory to `new-project`
ie: `cd new-project`?

**Comment by Fattouh92** [comment]
Yes I am changing, my bad I left it out but

**Comment by alan-agius4** [comment]
Can you share the complete output of the console?

**Comment by Fattouh92** [comment]
```
$ ng add @nguniversal/express-engine --clientProject web-client
Installing packages for tooling via npm.
npm WARN @smec/ng-commons@0.4.0 requires a peer of ngx-toastr@^8.10.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.4.0 requires a peer of jasmine-core@>=3.3 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-ellipsis@1.1.3 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-ellipsis@1.1.3 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@7.1.1 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.

+ @nguniversal/express-engine@7.1.1
added 1 package and audited 42491 packages in 8.521s
found 3 vulnerabilities (1 low, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
```

**Comment by alan-agius4** [comment]
Hi, I looked into this and I am still unable to replicate this issue on a newly generated project. 
Unfortunately, if no one is able to replicate this and provide some further info we'll be unable to address this.

**Comment by matheo** [comment]
I was able to use the `ng g universal` schematic with the latest package versions, but now I don't know how to complete the `server` configuration in the `angular.json` to get the whole site built, currently, I'm just getting the `main.js` in the output (I'm evidently quite new to SSR, sorry)

**Comment by alan-agius4** [comment]
Hi @matheo, I suggest to redirect support requests to [StackOverflow](http://stackoverflow.com/) using tag `angular-cli` or gitter.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by stot3** [comment]
I am also having the same problem, when I run the line: 

`@nguniversal/express-engine --clientProject new-project`

I get 
`Tree type not supported`, I'm running @angular@latest and it's at 7.3.5, I at first was getting the missing dependency witht the @angular/platform-browser, then after I installed it with

`npm install @angular/platform-browser@latest` 

I got the `Tree type not supported`, then the installer, will do everything but edit the package.json with the build commands that I need.
