### ISSUE TITLE
"Project name "test" "app" is not a supported name"

### ISSUE THREAD

**Issue by sungdzda** [angular/angular-cli#13904]
okay but WHY

**Comment by sungdzda** [comment]
just WHY

**Comment by alan-agius4** [comment]
Hi, 

In version 8 we will be supporting these names. See https://github.com/angular/angular-cli/pull/13909

The reason being is that historically ember-cli uses the package name if you wanted to use custom plugins and `app` and `test` were not allowed.

Ps: it would be great if next time the issue template is followed when filling an issue.

Thanks.
