### ISSUE TITLE
Pass forked type checker Semantic errors to the output when running build --watch

### ISSUE THREAD

**Issue by Usurer** [angular/angular-cli#13901]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
As described in https://github.com/angular/angular-cli/issues/13870 semantic diagnostic errors from the forked type checker aren't passed to the final diagnostic messages and cannot be read by Webpack plugins. This happens during second and further runs of the `build --watch`.

### Describe the solution you'd like
The straightforward solution would be to add one more option to the `ng build`.
But, since I don't really get why we don't collect semantic diagnostics from the forked type checker for the 2-nd and further runs, I'd say that we could just set `diagMode` in `AngularCompilerPlugin._emit()` to `DiagnosticMode.All`.

### Describe alternatives you've considered
The working solution is to set `forkTypeChecker` build option to `false`. But my assumption is that on the big projects it means slower builds.

**Comment by Usurer** [comment]
Guys, could anyone give any advice regarding the way I should test this feature before making a pull request?

**Comment by alan-agius4** [comment]
This is by design and it is intended that type errors aren't sent to Webpack when using the forked type checker. If they were, and they blocked the compilation, then there's no reason to in having a forked type checker turned on as rebuilds would just take much longer.

See: https://github.com/angular/angular-cli/issues/15887
