### ISSUE TITLE
Way to use webpack flag profile with statsJson flag

### ISSUE THREAD

**Issue by gatimus** [angular/angular-cli#13907]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Running `ng build [app name] --statsJson` outputs a stats.json just like `webpack --json > stats.json` would. The profile flag for the webpack cli adds profile section to modules of the outputted json. Can we get the same output as we would with `webpack --profile --json > stats.json` from `ng build ...`

see https://webpack.js.org/api/stats/
repost of #10028 

### Describe the solution you'd like
Some flag or solution to make `ng build [app name] --statsJson` output stats.json with profile sections like `webpack --profile --json > stats.json` would.

### Describe alternatives you've considered
ejecting to webpack

### ng v
```
Angular CLI: 7.3.4
Node: 10.14.1
OS: win32 x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.3
@angular-devkit/build-angular      0.13.4
@angular-devkit/build-ng-packagr   0.13.3
@angular-devkit/build-webpack      0.13.4
@angular-devkit/core               7.3.3
@angular-devkit/schematics         7.3.4
@angular/cdk                       7.3.3
@angular/cli                       7.3.4
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.3.3
@ngtools/json-schema               1.1.0
@schematics/angular                7.3.4 (cli-only)
@schematics/update                 0.13.4
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0
```

**Comment by alan-agius4** [comment]
Hi @gatimus, we will be enabling this by default when using the `stats-json` flag
