### ISSUE TITLE
Adding schematics short alias to angular.json

### ISSUE THREAD

**Issue by jlguenego** [angular/angular-cli#13918]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

`ng g @someorg/somepackage:some-long-schematic my-name`
This is a long and tedious command.

### Describe the solution you'd like
I propose
`ng g some-schematic my-name`

With a `angular.json` containing:
```
{
   "cli": {
        "schematicsAliases": [{
             "name": "some-schematic",
             "reference": "@someorg/somepackage:some-long-schematic"
        }]
   }
//...
}
```

### Describe alternatives you've considered
List of collections where it is not necessary to provide the package name.
The ng utility would take the first schematic that is encountered in the collection list.
```
{
   "cli": {
        "defaultCollection ": ["@someorg/package1", "@otherorg/package2"]
   }
//...
}
```

**Comment by jgu7man** [comment]
Still no way to do it or alternative?

**Comment by alan-agius4** [comment]
Lets continue tracking this issue https://github.com/angular/angular-cli/issues/12157
