### ISSUE TITLE
[WDS] Disconnected! on firefox but works well in chrome Angular CLI 7.3.5 

### ISSUE THREAD

**Issue by xshiiiidev** [angular/angular-cli#13915]
When running `ng serve` command and opening the http://localhost:4200 in firefox for the first time this error does not appear, but when I reload or refresh the page this error constantly appears. In chrome this error is not showing even how many times I refreshes or reloaded the page.

Angular CLI: 7.3.5
Node: 8.10.0
OS: linux x64
Angular:
...
Package Version

@angular-devkit/architect 0.13.5
@angular-devkit/core 7.3.5
@angular-devkit/schematics 7.3.5
@schematics/angular 7.3.5
@schematics/update 0.13.5
rxjs 6.3.3
typescript 3.2.4

**Comment by xshiiiidev** [comment]
any fast fix for this ?

**Comment by cfremgen** [comment]
No fix, but I've noticed when I switch tabs in chrome while the page is refreshing, I do not get this error. Every time.

Possibly has something to do with many connections happening at once, and Chrome limiting the number of network threads in background tabs.

**Comment by xshiiiidev** [comment]
Have you tried this error on firefox? I never encountered this problem on google chrome.

**Comment by cfremgen** [comment]
I have only had this issue in Chrome, have not reproduced it in FF. I believe FF has similar rate limiting.

**Comment by cfremgen** [comment]
I have only had this issue in Chrome, have not tried to reproduced it in FF. I believe FF has similar rate limiting.

**Comment by xshiiiidev** [comment]
I see, I hope someone gives high priority to this. Have seen this issue from way back Angular 6 up to now.

**Comment by cfremgen** [comment]
Seems turning off live reloading has fixed this issue for me.

`ng serve  --live-reload=false`

**Comment by xshiiiidev** [comment]
@cfremgen thank you for that :) it fix my issue also. Just wondering now if this flag is safe in production mode.

**Comment by cfremgen** [comment]
You shouldn't be using `ng serve` to serve production builds.

**Comment by xshiiiidev** [comment]
Oh thanks again bro I will be closing this thread then :)

**Comment by lfratini** [comment]
Hi all , I've this problem , but only on Firefox, Chrome does not show error . If i did not to use ng serve , which is the correct mode to run angular project in production ??
I've installed pm2 , create ecosystem.js and launch systemd script that launch ng serve . This is not correct ?
Thanks
