### ISSUE TITLE
Issue No 4048

### ISSUE THREAD

**Issue by RajeshPodder00** [angular/angular-cli#1393]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 10 64 bit. 
angular-cli: 1.0.0-beta.10
node: 5.0.0
npm: 3.10.3

Getting Following Error While running npm cache clean

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "cache" "clean"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\Rajeshpodder007\AppData\Roaming\npm-cache
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rmdir

npm ERR! Error: EPERM: operation not permitted, rmdir 'C:\Users\Rajeshpodder007\AppData\Roaming\npm-cache'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rmdir 'C:\Users\Rajeshpodder007\AppData\Roaming\npm-cache'
npm ERR!     at Error (native)
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rmdir',

**Comment by filipesilva** [comment]
That's a problem with npm, not with angular-cli per se. Seems a permissions issue... I'm sorry I can't help more, but I don't see any obvious causes from your log.
