### ISSUE TITLE
Enable custom arguments in serve command

### ISSUE THREAD

**Issue by samithaf** [angular/angular-cli#13937]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Hello, Can you please enable the custom arguments in ng serve command? I was able to pass extra args with 1.7.X builds but with new CLI versions I can't simply because CLI is very restrictive. 

### Describe the solution you'd like
Developers should be able to pass custom arguments to ng serve command. Classic example as follows. Our current project has so many API endpoints like DEV1, DEV2... SIT1, SIT2, SVP to PROD. So with previous NG CLI versions we had our custom proxy conf file which reads an argument like  endpoint and then proxy to the correct API endpoint. But with new limitation we are unable to do that.
E.g. 
`ng serve --ssl true --proxy-config proxy.conf.js --endpoint sit1`

proxy conf.

```
const ENDPOINTS = {
	local: {
		endpoint: 'https://localhost:9443',
		mockEam: true
	},
	dev1: {
		endpoint: 'https:/dev.test.com.au',
                autoRewrite: true,
                changeOrigin: true,
		proxy: false
	},
	sit1: {
		endpoint: 'https://dev.test.com.au',
                autoRewrite: true,
                changeOrigin: true,
                proxy: true
	},
	uat1: {
		endpoint: 'https://uat.test.com.au'
	},
	svp1: {
		endpoint: 'https://svp.test.com.au',
		proxy: true
	}
};
```

### Describe alternatives you've considered
Can't think of any alternatives other than modify the endpoint manually every time which is a poor developer experience.

**Comment by alan-agius4** [comment]
This is feature request is similar to https://github.com/angular/angular-cli/issues/12305

That said, I don't think we'd allow a custom flag to be passed to any builder.

However, there are a couple of things that you can do. 
1) Have multiple proxy configs and use a different files by using the `--proxy-config` flag
2) Have various serve configurations ex: 
```
"configurations": {
  "production": {
     ...
     "proxyConfig": "./proxy.conf.js",
  },
  "dev": {
     ...
     "proxyConfig": "./proxy.conf.dev.js",
  },
  "uat": {
     ...
     "proxyConfig": "./proxy.conf.uat.js",
  }
}
```
3) Setup an NGINX Reverse Proxy

**Comment by samithaf** [comment]
@alan-agius4 thanks for the feedback. But I just wonder what was the reason behind rejecting all the unknown arguments?

**Comment by alan-agius4** [comment]
The main reason is that if one provides an unknown/invalid argument it can have an undefined behaviour and there is a greater room for errors and mistakes. This is undesired in a CI environment especially.

For example something using the following flag `--optimizations` a consumer might think that the build is being optimized but this is not the case as the correct flag is `--optimization`.

**Comment by samithaf** [comment]
fair enough but again while I am totally respecting the design maybe this feature should have kept like in early versions, sending strong message saying it's an unknown option but accepting it. Again thank you for the explanation.
