### ISSUE TITLE
SchemaValidationException errors cannot be confirmed with instanceof

### ISSUE THREAD

**Issue by roydor** [angular/angular-cli#13931]
# 🐞 Bug report
```
- [ ] bug report
- [x] feature request for Schematics
```
### Description
`InvalidInputOptions` and `SchemaValidationException` are difficult to catch due to https://github.com/Microsoft/TypeScript/issues/13965

A solution is outlined in https://github.com/Microsoft/TypeScript/issues/13965#issuecomment-278570200 which would enable us to catch `SchemaValidationExceptions` with the `instanceof` operator and write more robust/intuitive code.

## 🔬 Minimal Reproduction
Attempt to `instanceof schema.SchemaValidationException` an `InvalidInputOptions` exception, and bear witness to the falsey response.

**Comment by alan-agius4** [comment]
@roydor, can you kindly share the output of `ng version`?

```
describe('InvalidInputOptions', () => {
  it('InvalidInputOptions is instanceof SchemaValidationException', () => {
    expect(new InvalidInputOptions({}, []) instanceof schema.SchemaValidationException).toBe(true);
  });
});
```

Running the above tests, does return `true`.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
