### ISSUE TITLE
ng serve giving errors for angular-cli 7.3.6

### ISSUE THREAD

**Issue by hasannaqi9** [angular/angular-cli#13940]
I am getting following error while running npm start or ng serve command:
**No projects support the 'serve' target.
Error: No projects support the 'serve' target.
    at ServeCommand.initialize (D:\MyApp\node_modules\@angular\cli\models\architect-command.js:50:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3**

My package.json:

{
  "name": "MyApp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -port 4200",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "7.2.9",
    "@angular/common": "7.2.9",
    "@angular/compiler": "7.2.9",
    "@angular/compiler-cli": "7.2.9",
    "@angular/core": "7.2.9",
    "@angular/forms": "7.2.9",
    "@angular/http": "7.2.9",
    "@angular/platform-browser": "7.2.9",
    "@angular/platform-browser-dynamic": "7.2.9",
    "@angular/platform-server": "7.2.9",
    "@angular/router": "7.2.9",
    "bootstrap": "3.3.7",
    "core-js": "2.4.x",
    "font-awesome": "4.7.0",
    "jquery": "3.0.0",
	"materialize-css": "^0.100.2",
    "ng2-bootstrap-modal": "^1.0.1",
    "ng2-charts": "1.6.0",
    "ng2-expansion-panels": "0.0.6",
    "ng2-trim-directive": "^2.1.0",
    "ngx-clipboard": "8.0.0",
    "rxjs": "6.4.0",
  },
  "devDependencies": {
    "@angular/cli": "^7.3.6",
    "@angular/language-service": "^7.2.9",
    "@types/jasmine": "2.5.38",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "6.0.x",
    "jasmine-core": "2.5.x",
    "jasmine-spec-reporter": "3.2.x",
    "karma": "3.0.0",
    "karma-chrome-launcher": "2.0.x",
    "karma-cli": "1.0.x",
    "karma-coverage-istanbul-reporter": "0.2.x",
    "karma-jasmine": "1.1.x",
    "karma-jasmine-html-reporter": "0.2.x",
    "protractor": "^5.4.2",
    "ts-node": "2.0.x",
    "tslint": "4.4.x",
    "typescript": "3.2.4",
    "uglify-js": "^2.8.27"
  },
  "description": "This project was generated with [Angular CLI](https://github.com/angular/angular-cli) version 1.3.1.",
  "main": "karma.conf.js",
  "author": ""
}

**Comment by hasannaqi9** [comment]
npm version:
5.6.0
node version:
v8.11.2

**Comment by alan-agius4** [comment]
Can you share your `angular.json` please?

**Comment by hasannaqi9** [comment]
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "project": {
        "name": "MyApp"
    },
    "apps": [
        {
            "root": "src",
            "outDir": "dist",
            "assets": ["assets", "images", "favicon.ico", "web.config"],
            "index": "index.html",
            "main": "main.ts",
            "polyfills": "polyfills.ts",
            "test": "test.ts",
            "tsconfig": "tsconfig.app.json",
            "testTsconfig": "tsconfig.spec.json",
            "prefix": "app",
            "styles": [
                "styles.css",
                "../node_modules/bootstrap/dist/css/bootstrap.css",
                "../node_modules/font-awesome/css/font-awesome.min.css",
                "../node_modules/ag-grid/dist/styles/ag-theme-fresh.css"
            ],
            "scripts": [
                "../node_modules/jquery/dist/jquery.min.js",
                "../node_modules/bootstrap/dist/js/bootstrap.min.js",
                "../node_modules/ng2-charts/charts/charts.js"
            ],
            "environmentSource": "environments/environment.ts",
            "environments": {
                "dev": "environments/environment.ts",
                "prod": "environments/environment.prod.ts"
            }
        }
    ],
    "e2e": {
        "protractor": {
            "config": "./protractor.conf.js"
        }
    },
    "lint": [
        {
            "project": "src/tsconfig.app.json",
            "exclude": "**/node_modules/**"
        },
        {
            "project": "src/tsconfig.spec.json",
            "exclude": "**/node_modules/**"
        },
        {
            "project": "e2e/tsconfig.e2e.json",
            "exclude": "**/node_modules/**"
        }
    ],
    "test": {
        "karma": {
            "config": "./karma.conf.js"
        }
    },
    "defaults": {
        "styleExt": "css",
        "component": {}
    }
}

**Comment by hasannaqi9** [comment]
This is basically .angular-cli.json

**Comment by alan-agius4** [comment]
The config of CLI version 1 is not comparable with version 6+.

You need to migrate the config, kindly see https://update.angular.io/

**Comment by viswanathkk** [comment]
No projects support the 'serve' target.
Error: No projects support the 'serve' target.
    at ServeCommand.initialize (C:\Users\spitta\DailyRollNew\node_modules\@angular\cli\models\architect-command.js:55:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

I too got the same error. Can you please tell me how to resolve this issue ??

**Comment by hasannaqi9** [comment]
@viswanathkk please share you angular.json file
