### ISSUE TITLE
How to integrate rust wasm into angular 7 project?

### ISSUE THREAD

**Issue by mokeyish** [angular/angular-cli#13947]
I tried build Angular 7 with import a [`rust wasm`](https://rustwasm.github.io/docs/book/) project which I wrote  add two number function, but it called an error, it cannot recognize *.wasm file.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dasoncheng** [comment]
@mokeyish have you solve the problem

**Comment by mokeyish** [comment]
@dasoncheng Yeah I've already solved this problem.

**Comment by dasoncheng** [comment]
@mokeyish i have the same problem, try `ngx-build-plus`, but hasn't been solved yet. what's your solution

**Comment by mokeyish** [comment]
@dasoncheng You could check out my repo [sql-editor/src/index.html](https://github.com/mokeyish/n-sql/blob/master/sql-editor/src/index.html).
