### ISSUE TITLE
Call ng [serve | build] with a platform flag

### ISSUE THREAD

**Issue by sebawita** [angular/angular-cli#13959]
# 🚀 Feature request

It would be great to be able to add extensions to `ng serve` and `ng build`, which would allow me to call a custom serve/build mechanism.

This would be very useful with NativeScript where the developers need to use two CLIs, the Angular CLI for generating components, services etc. and the NativeScript to build and deploy the apps.

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

When I am in a NativeScript Angular project (or a code-sharing project web+mobile), it would be great to be able to call something like:
`ng serve --ios` or `ng serve --flag=android`, which would then ask the architect on how to perform the build iOS or Android build and deploy the app.

It would also be great to do the same with `ng build --ios`, which would perform a full mobile build.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

What I am looking after is a mechanism that would allow me to plug into the Angular CLI, and then extend it with additional build options.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Hi @sebawita, Angular CLI builders have no knowledge of NativeScript builders. From what you are describing above it seems that this should be handle by a separate NativeScript builder.

This is similar on how libraries are built, there is a separate build builder for libraries. https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_ng_packagr

You can change the builder for `ng build` in the `angular.json`
