### ISSUE TITLE
raw-loader not working with "aot": true and "buildOptimizer": true

### ISSUE THREAD

**Issue by distributev** [angular/angular-cli#13967]
Currently in my components I have code like 
```
import * as leftMenuTemplate from '!raw-loader!./templates/_left-menu.html';

@Component({
selector: 'my-component',
template: `
    <aside class="main-sidebar">
      <section class="sidebar">${leftMenuTemplate}</section>
    </aside>
   `
})
```
everything works fine if I build with  "aot": false and "buildOptimizer": false but everything fails if I build with "aot": true and "buildOptimizer": true

**_When I try to run with AOT true I get the null string rendered instead of my menu._**

**Comment by alan-agius4** [comment]
Hi, kindly follow the issue template when filling a bug or a feature request. Thanks.

That said, I don’t think this is supported in an AOT build, in general you should use other components to include partial HTML’s
