### ISSUE TITLE
The package @angular/common@2.0.0-rc.4 does not satisfy its siblin...

### ISSUE THREAD

**Issue by WG-Com** [angular/angular-cli#1396]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
```
(node:5476) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 0.0.39
node: 6.0.0
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
```
ng new projectname

ng init

npm install  
```
4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/ccc/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--cache=/Users/ccc/.cnpm" "--registry=https://registry.npm.taobao.org" "--node-gyp=/usr/local/lib/node_modules/cnpm/node_modules/node-gyp/bin/node-gyp.js" "install" "-ddd"
npm ERR! node v6.0.0
npm ERR! npm  v2.14.8
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.1 wants @angular/common@2.0.0-rc.1
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.1 wants @angular/common@2.0.0-rc.1
npm ERR! peerinvalid Peer @angular/router@2.0.0-rc.1 wants @angular/common@2.0.0-rc.1
npm ERR! peerinvalid Peer @angular/testing@0.0.0-0 wants @angular/common@0.0.0-0
npm verb exit [ 1, true ]
```

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by marisveide** [comment]
What was the solution to this issue?
I have the same problem, if I want to add @angular/testing package to my project.
Why it was closed without any resolution?

My dependencies:
`  "dependencies": {
    "@angular/common": "^2.0.0-rc.5",
    "@angular/compiler": "^2.0.0-rc.5",
    "@angular/core": "^2.0.0-rc.5",
    "@angular/http": "^2.0.0-rc.5",
    "@angular/platform-browser": "^2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.5",
    "@angular/router": "^3.0.0-rc.1",
    "@angular/router-deprecated": "^2.0.0-rc.2",
    "@angular/upgrade": "^2.0.0-rc.5",
    "es6-promise": "^3.2.1",
    "es6-shim": "^0.35.1",
    "reflect-metadata": "^0.1.2",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.17"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "eslint": "^3.3.1",
    "eslint-config-google": "^0.6.0",
    "eslint-config-standard": "^6.0.0",
    "eslint-plugin-promise": "^2.0.1",
    "eslint-plugin-standard": "^2.0.0",
    "jasmine-core": "2.4.1",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "lite-server": "^2.2.0",
    "remap-istanbul": "^0.6.4",
    "typescript": "^1.8.10",
    "typings": "^1.0.4"
  }`

Result:
`$ npm install
npm WARN package.json testing-from-twofuckingdevelopers.com@1.0.0 No description
npm WARN package.json testing-from-twofuckingdevelopers.com@1.0.0 No repository field.
npm WARN package.json testing-from-twofuckingdevelopers.com@1.0.0 No README data
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/common@2.0.0-rc.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.5 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/router@3.0.0-rc.1 wants @angular/common@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/router-deprecated@2.0.0-rc.2 wants @angular/common@^2.0.0-rc
npm ERR! peerinvalid Peer @angular/testing@0.0.0-0 wants @angular/common@0.0.0-0`


[npm-debug.log.zip](https://github.com/angular/angular-cli/files/438924/npm-debug.log.zip)

**Comment by WG-Com** [comment]
do not use  proxy

**Comment by centigrade-thomas-becker** [comment]
Please elaborate your answer

**Comment by JanStureNielsen** [comment]
@marisveide -- upgrade to Node 6.5+ and reinstall Angular CLI properly as described in **Updating angular-cli** in [README.md](https://github.com/angular/angular-cli).
