### ISSUE TITLE
fileReplacements cannot replace app.module.ts (ng build --configuration=production)

### ISSUE THREAD

**Issue by Jun711** [angular/angular-cli#13964]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Not sure. hadn't tried this before

### Description

 
fileReplacements cannot replace app.module.ts
command used: ng build --configuration=production 

got this error:

ERROR in : Type AppComponent in /Users/j/Projects/replaceAppModule/src/app/app.component.ts is part of the declarations of 2 modules: AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.ts and AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.prod.ts! Please consider moving AppComponent in /Users/j/Projects/replaceAppModule/src/app/app.component.ts to a higher module that imports AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.ts and AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.prod.ts. You can also create a new NgModule that exports and includes AppComponent in /Users/j/Projects/replaceAppModule/src/app/app.component.ts then import that NgModule in AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.ts and AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.prod.ts.

## 🔬 Minimal Reproduction

Simple steps to reproduce this bug.
1. Create a new project using `ng new`.  
2. Create two components `ng g c app/components/home` `ng g c app/components/feature`.  
3. Make a copy of app.module.ts file and name it app.module.prod.ts file.   
4. Remove `import { FeatureComponent } from './app/components/feature/feature.component';` from app.module.prod.ts.  Reason is feature component is not needed in production.  
5. Run `ng build --configuration=production`

You can clone the following repo and run `ng build --configuration=production`
https://github.com/Jun711/replaceAppModule

## 🔥 Exception or Error
<pre><code>/Users/j/Projects/replaceAppModule/src/app/app.component.ts is part of the declarations of 2 modules: AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.ts and AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.prod.ts! Please consider moving AppComponent in /Users/j/Projects/replaceAppModule/src/app/app.component.ts to a higher module that imports AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.ts and AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.prod.ts. You can also create a new NgModule that exports and includes AppComponent in /Users/j/Projects/replaceAppModule/src/app/app.component.ts then import that NgModule in AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.ts and AppModule in /Users/j/Projects/replaceAppModule/src/app/app.module.prod.ts.</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 7.2.4
Node: 11.0.0
OS: darwin x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.2.4
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
This is actually not related to file replacement.  Typescript compilation follows the behavior of tsc which uses the properties of the tsconfig file to control the source files which will be compiled.  In the default setup all typescript files inside src will be included in the application.  This will result in both of the app modules being compiled.  This behavior is intended and to allow for the situation described,  different tsconfigs will be needed to exclude the appropriate file.

For additional configuration information, please see: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

Also,  since two different tsconfigs would need to be used, Typescript path mapping could be used instead of file replacements if desired. The exclusion/inclusion rules would still be required.

**Comment by Jun711** [comment]
@clydin 
under default configuration(set up via ng new of cli 7), is it true that non Typescript files can be replaced successfully by this fileReplacements function then?

**Comment by clydin** [comment]
Both can be replaced.  TS files need extra care, however, to ensure that they don't conflict with each other as they will both be present in the TypeScript program compilation process.  Only the relevant one will be present in the final output though.

One other area of concern with file replacements is of SCSS files, the Sass preprocessor handles its own IO and the current file replacement process cannot account for that.
