### ISSUE TITLE
Angular Dev Kit 8.x.x: make server and karma builder reusable by external developers

### ISSUE THREAD

**Issue by just-jeb** [angular/angular-cli#13972]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
The new Architect API is almost here and it takes into consideration external developers such as myself (@hansl great job!).  
For instance, there is `transforms` object in [browser](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/browser/index2.ts#L212) and [dev-server](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/dev-server/index2.ts#L77) builders which allows me to easily extend them with custom webpack configuration ([custom-webpack:browser](https://github.com/meltedspark/angular-builders/blob/new-architect-api/packages/custom-webpack/src/browser/index2.ts), [custom-webpack:dev-server](https://github.com/meltedspark/angular-builders/blob/new-architect-api/packages/custom-webpack/src/dev-server/index.ts)).  
It made the transition from 7.x.x to 8.x.x very easy end the API itself is very robust.  
However, this is not the case for karma and server builders (which are must-have to complete the transition).   
The only function I can reuse from [server](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/server/index2.ts) builder is [`buildServerWebpackConfig`](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/server/index2.ts#L107) but even with this reuse I have to copy&modify the rest of the logic.  
When it comes to [karma](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/karma/index2.ts) builder I don't think I can reuse anything from there, meaning I have to copy&modify the whole file.  

### Describe the solution you'd like
Karma and Server builders should provide the same level of flexibility and behave similarly to Browser and Dev-Server builders.  
In particular, take in the `transforms` object, export the logic that can be potentially reused by external developers and use the same way for creating a builder (`createBuilder` function from `'@angular-devkit/architect/src/index2'` and not something custom like [here](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/server/index2.ts#L44)).
### Describe alternatives you've considered
The only alternative I have today is to copy and paste the code from Karma and Server builder and start modifying it.  
I hope we all agree that this is very hard to maintain and can't be a long term option.  
In fact, it would be really great if I didn't have to do it and I could reuse all the necessary logic before the RC is out.  

@clydin @mgechev Guys, @hansl told me that I should ask you for help about the coordination so here I'm asking.  
We can discuss it here, or if you need more details I'm on `#tools-friends` channel at Slack.

Thanks a lot for doing such an amazing job!

**Comment by clydin** [comment]
This is implemented in the current version.
