### ISSUE TITLE
No sourcemap symbols

### ISSUE THREAD

**Issue by tinganho** [angular/angular-cli#13974]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Description

When I build an angular app no source maps symbols are included, which makes debugging really hard.
![image](https://user-images.githubusercontent.com/1324476/54912773-a5f6a380-4ef1-11e9-9907-606cd42a67d7.png)

**Comment by alan-agius4** [comment]
Hi @tinganho, try using `/@` instead.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Thanks.

**Comment by tinganho** [comment]
@alan-agius4 I don't understand what you mean with `/@`?

**Comment by alan-agius4** [comment]
Instead of search using `@` use `/@`

**Comment by tinganho** [comment]
But searching for symbols is with `@`?

**Comment by tinganho** [comment]
I only get files otherwise. 

The problem is that `ng build` doesn't include symbols in the sourcemap.

I also think I provided all the info needed 🤔

**Comment by alan-agius4** [comment]
Hi again, I looked a bit at this quickly.

It seems that the problem is related to the `export` keyword, see below:
![image](https://user-images.githubusercontent.com/17563226/54917125-646af600-4efb-11e9-8c61-d42cd77aa365.png)

I was also able to reproduce the without Angular CLI, hence it seems to be something related to the Browser behaviour.

**Comment by tinganho** [comment]
I don't think it is a browser problem. I have got this to work with other frameworks. 
Angular CLI just need to make sure that the symbol names are included in the generated source map. Notice `slideUp`, `slideDown` etc. below:
```
{
    version: 3,
    file: "script.js.map",
    sources: [
        "app.js",
        "content.js",
        "widget.js"
    ],
    sourceRoot: "/",
    names: ["slideUp", "slideDown", "save"],
    mappings: "AAA0B,kBAAhBA,QAAOC,SACjBD,OAAOC,OAAO..."
}
```
It doesn't matter if it is an export or not. It's still a symbol.

**Comment by tinganho** [comment]
hm, might be TS's fault then. They don't seem to add `names`.
