### ISSUE TITLE
ng generate universal fails on a brand new installation

### ISSUE THREAD

**Issue by alexnoise79** [angular/angular-cli#13988]
# 🐞 Bug report

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: **on my machine 7.3.2**

### Description

 
```
ng generate universal
``` 
is failing on a brand new cli installation

## 🔬 Minimal Reproduction
ng new amazing

cd amazing

ng generate universal

## 🔥 Exception or Error
<pre>
Schematic input does not validate against the Schema: {}
Errors:

  Data path "" should have required property 'clientProject'.<code>

</code></pre>

## 🌍 Your Environment
<pre>

Angular CLI: 7.3.6
Node: 10.9.0
OS: win32 x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cli                      7.3.6
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0<code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alexnoise79** [comment]
For whom will have the same problem, that's how to solve it:
```
ng new amazing
cd amazing
ng generate universal --client-project=amazing
```

Thanks Alan, see you around (we work really close) ;)
