### ISSUE TITLE
[lint] system-config.ts should use simple quotes

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#1398]
In 1.0.0-beta.10, c85b14f5f7d34ee22cfdc8bb94080e85757a5d07 introduced `"use strict"` in `system-config.ts` whereas it should be `'use strict'` to keep the linter happy

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
