### ISSUE TITLE
Provide support for using relative path in image url in css files

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#13998]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
While using releative path in css files, like below

  ```
.template .e-dialog .e-dlg-header-content .e-dlg-header .e-avatar.template-image {
    background-image: url(**./assets**/dialog/images/1.png);
    vertical-align: middle;
    display: inline-block;
    width: 36px;
    height: 36px;
}
```
It throws beloe error while taking prod build:

> Date: 2019-03-27T12:34:10.476Z
Hash: 795cff9aad7f0a5cbeb2
Time: 7626ms
chunk {0} runtime.ec2944dd8b20ec099bf3.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.9868d9b237c3a48c54da.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills.85f47f0bf59079cbc23a.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]

> ERROR in Child compilation failed:
> Module Error (from ./node_modules/postcss-loader/src/index.js):
> (Emitted value instead of an instance of Error) CssSyntaxError: D:\today\checks\src\app\app.component.css:195:27: Can't resolve './assets/dialog/images/1.png' in 'D:\today\checks\src\app'

>   193 | }
>   194 | .template .e-dialog .e-dlg-header-content .e-dlg-header .e-avatar.template-image {

> 195 |     background-image: url(./assets/dialog/images/1.png);
      |                           ^
  196 |     vertical-align: middle;
  197 |     display: inline-block;
:
NonErrorEmittedError: (Emitted value instead of an instance of Error) CssSyntaxError: D:\today\checks\src\app\app.component.css:195:27: Can't resolve './assets/dialog/images/1.png' in 'D:\today\checks\src\app'

### Describe the solution you'd like
I want to use relative path for image-url reference, this will only reason is going to solve solution.

If i use like below i wont throw any error:

  ```
.template .e-dialog .e-dlg-header-content .e-dlg-header .e-avatar.template-image {
    background-image: url(**/assets**/dialog/images/1.png);
    vertical-align: middle;
    display: inline-block;
    width: 36px;
    height: 36px;
}
```
But images are not loading while hosting this using **IIS server** and **live server**

### Describe alternatives you've considered

If i use '~' symbol like below i wont throw any error and image path is refering fine locally but when we host this in online image not get referred:

  ```
.template .e-dialog .e-dlg-header-content .e-dlg-header .e-avatar.template-image {
    background-image: url(**~/assets**/dialog/images/1.png);
    vertical-align: middle;
    display: inline-block;
    width: 36px;
    height: 36px;
}
```

**Comment by alan-agius4** [comment]
Hi, when using relative paths, in css, they are relative to the `.css` files.

Seeing the error above,

> D:\today\checks\src\app\app.component.css:195:27: Can't resolve './assets/dialog/images/1.png' in 'D:\today\checks\src\app'

Relative sources are working as expected, unless you have a file `D:\today\checks\src\app\assets\dialog\images\1.png` which is not being resolved.

From your explaination above however, I think what you want is to use absolute url. Aka, starting with a `/`.

```
background-image: url(/assets/dialog/images/1.png);
```

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,
Thanks for your quick reply,

If i use like below i wont throw any error:

.template .e-dialog .e-dlg-header-content .e-dlg-header .e-avatar.template-image {
  background-image: url(**/assets**/dialog/images/1.png);
  vertical-align: middle;
  display: inline-block;
  width: 36px;
  height: 36px;
}
But images are not loading while hosting this using IIS server and live server

**I have already mentioned this in my question**

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

Can you please update on this?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by kumaresan-subramani** [comment]
@alan-agius4 ,
Anyway thanks for your reply
But i didn't get any solution here.

I have create gulp task which will replace assets path after taking build. it soved my problem
