### ISSUE TITLE
Proposal: migrate to TypeScript

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#14]
Our broccoli plugins in angular/angular are written in TypeScript, because it's a better language for a large team collaborating on a large-scale application, and because Angular is invested in TypeScript.

angular-cli project should probably do the same.

**Comment by rodyhaddad** [comment]
@alexeagle Thank would be great.

How are you planning on doing that, considering the project is in node.

Will you use something like [eknkc/typescript-require](https://github.com/eknkc/typescript-require)?

**Comment by alexeagle** [comment]
In our other projects we just bootstrap the build tool with eg.
gulp-typescript and then transpile the rest of the code before execution.
That's what we do with https://github.com/angular/ts2dart for example (and
angular/angular as well)
I just learned about typescript-require today and I should check that out
too.

**Comment by hansl** [comment]
Outside of the broccoli plugins, the whole tool can now be coded in TypeScript (with some caveat about typings), following https://github.com/angular/angular-cli/pull/291.

I consider this close.
