### ISSUE TITLE
ViewChild not find element when using AoT

### ISSUE THREAD

**Issue by maverick-coder** [angular/angular-cli#14009]
I found a wonderful decorator who wanted to use in my project. But when using AoT, ViewChild does not work correctly. An old problem, dozens of open tickets and things are there.

```
import { ElementRef, ViewChild } from '@angular/core';

/**
 * To get the native element instead of ElementRef.nativeElement
 * Caveats: it won’t work with AOT
 * @param selector Selector. Example: <div #selector></div>
 */
export function NativeElement(selector: string): PropertyDecorator {
  // Create the viewchild decorator with read: ElementRef
  const propDecoratorFn: Function = ViewChild(selector, { read: ElementRef });

  // Target is the component object
  // Property key is the name of the property
  return function(target: Object, propertyKey: string | symbol): void {
    // Somehow this will execute the viewchild process to attach a new property called tempViewChildFor_
    // to the target (component object instance)
    propDecoratorFn(target, `tempViewChildFor_${propertyKey}`);

    // Redefined the property with getter. It will return the tempViewChildFor_ with nativeElement
    Object.defineProperty(target, propertyKey, {
      get: function(): HTMLElement {
        const property = this[`tempViewChildFor_${propertyKey}`];
        if (!property) {
          throw Error(
            'Can not get ElementRef using selector, please check your component view again.'
          );
        }

        return property.nativeElement;
      }
    });
  };
}
```
[Code source](https://medium.com/@toannm4/angular-nativeelement-how-to-read-nativeelement-using-viewchild-cdf4a0970482)

Is there a workaround when AoT is enabled?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
