### ISSUE TITLE
ng build changes the modified date on files it doesn't modify

### ISSUE THREAD

**Issue by BenROhio** [angular/angular-cli#14003]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...
"ng build" changes the modified date on every file that ends up in the dist folder including files it just copies into place without modifying, such as font files and images.   This makes it difficult to copy just things that have changed using robocopy.  Please retain the timestamps on unaltered files.

## 🔬 Minimal Reproduction

Please include: commands run (including args), packages added, related code changes.
1. Create an angular project using that includes images or font files.
2. Notice the modified date timestamp on those files.
3. ng build
4. Check the time stamps of the files from step 1 that now appear in the "dist" build destination directory.  Notice that the modified dates on those files in the dist folder are changed even though the files do not differ from the originals.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 6.2.9
Node: 10.15.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.4.0
typescript                        2.9.2
webpack                           4.16.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @BenROhio, thanks for filling this. 

This seems quite a specific request and at the moment this doesn't fall in the CLI roadmap and we are cautions in increasing the CLI scope.

Most likely this can be down with ngx-build-plus and a a custom webpack plugin.

Let's re-open this if this becomes a popular request.

Thanks for your understanding.

**Comment by clydin** [comment]
Also of note is that https://github.com/webpack-contrib/copy-webpack-plugin performs that actual asset copying and it may be useful to raise an issue at that repository.
