### ISSUE TITLE
Cannot find module '@schematics/angular/utility/dependencies'

### ISSUE THREAD

**Issue by eykar** [angular/angular-cli#14002]
when i run this commande ng add @nguniversal/express-engine --clientProject angular.io-example
i get this result 
![image](https://user-images.githubusercontent.com/48991510/55079436-7506a200-509c-11e9-8809-ccb69aef4715.png)

**Comment by AzriZzz** [comment]
wait? what is the solution for this problem because i'm facing the same situation

`Installing packages for tooling via npm.
Cannot find module '@schematics/angular/utility/dependencies'
Error: Cannot find module '@schematics/angular/utility/dependencies'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/azri/Desktop/Development/lion-dashboard/node_modules/@nguniversal/express-engine/schematics/install/index.js:34:26
    at /Users/azri/Desktop/Development/lion-dashboard/node_modules/@nguniversal/express-engine/schematics/install/index.js:14:17
    at Object.<anonymous> (/Users/azri/Desktop/Development/lion-dashboard/node_modules/@nguniversal/express-engine/schematics/install/index.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)`

**Comment by andrejacksonnola** [comment]
Getting the same issue

**Comment by rajaramtt** [comment]
Still, I am getting the same error.

**Comment by Jalapina** [comment]
Getting the same issue.

**Comment by Jalapina** [comment]
Why was this closed?

**Comment by maseranw** [comment]
same issue hete.

**Comment by greenjellygit** [comment]
@alan-agius4 It would be nice if you wrote **why you close issue**.

**Comment by aleemkhan** [comment]
Getting the same issue? Any help so far or any solution?

**Comment by LOMFM** [comment]
Got the same issue? Any help for the server-side-rendering?

**Comment by draooo** [comment]
i am also getting same issue while doing ssr.

**Comment by alan-agius4** [comment]
Issue was closed as it doesn't follow the issue template. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists in version 8.3, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by irudyi-carecloud** [comment]
`ng add @nguniversal/express-engine@^7.1.0 --clientProject project-name`
if you use angular 7.1.0 that would help to resolve that issue, angular and express-engine versions should be the same.

**Comment by chandima-mdosl** [comment]
please have a try following command.
npm i @nguniversal/express-engine
ng generate universal --client-project <name of your client project>

**Comment by bladimirventura** [comment]
> `ng add @nguniversal/express-engine@^7.1.0 --clientProject project-name`
> if you use angular 7.1.0 that would help to resolve that issue, angular and express-engine versions should be the same.

It works for me.
