### ISSUE TITLE
ng new xxx fails silently

### ISSUE THREAD

**Issue by DaveBGld** [angular/angular-cli#1401]
Developing on Windows 10

Running all commands from cmd with administrator privileges

`ng new xxx-app` gets stuck, and nothing happens.

run `ng new xxx-app --d` and get what seems to be a good list of tasks... But since the first time , I have been unable to run the command and get results. It just gets stuck, but can terminate wit `ctr-C`

run `ng new xxx-app --v` and get the messages attached 

> File attached with results of verbose
> [ngLog2.txt](https://github.com/angular/angular-cli/files/374875/ngLog2.txt)

run `ng -v` and the result is 

> C:\D>ng -v
> angular-cli: 1.0.0-beta.10
> node: 5.7.0
> os: win32 x64

deleted all modules in users npm and npm-cache directories at `C:\Users\XXXXX\AppData\Roaming\npm` and `C:\Users\XXXXX\AppData\Roaming\npm-cache`

 and reinstalled angular-cli, with same behavior.

Sometimes running these commands just get stuck.

**Comment by filipesilva** [comment]
I can't reproduce this myself, but from your log this looks network related. Does that give you any clue?

**Comment by filipesilva** [comment]
Closing as inactive.
