### ISSUE TITLE
Support zone.js 0.9

### ISSUE THREAD

**Issue by acohenOT** [angular/angular-cli#14013]
# 🚀 Feature request

### Description
zone.js 0.9 has been release. angular/core should support zone.js should support it without any warnings. After updating package.json to zone.js 0.9, a warning is presented when running npm install.

npm WARN @angular/core@7.2.11 requires a peer of zone.js@~0.8.26 but none is installed.

### Describe the solution you'd like
No warning when running npm install.

**Comment by Destreyf** [comment]
@acohenOT This would be better submitted to angular/angular instead of angular/angular-cli.

**Comment by acohenOT** [comment]
@Destreyf thanks. Looks like an issue was already submitted there. https://github.com/angular/angular/issues/29570
