### ISSUE TITLE
How to change the folder structure inside the dist folder?

### ISSUE THREAD

**Issue by julianpoemp** [angular/angular-cli#14014]
After building my angular app using --prod parameter angular/cli generates approx. 12 files. I want a structure that is much cleaner (only folders and the index.html). For example I want all generated files moved to a folder called "core".

The structure of my dist folder is that:

    dist/
    dist/assets
    dist/... 12 files ...
    dist/index.html

I would like to have this structure (automatically generated):

    dist/
    dist/assets
    dist/core/... 12 files ...
    dist/index.html

How can I do this?

I'm looking for a solution almost longer than 1 1/2 years and also tried to ask on stackoverflow and on gitter. The stackoverflow question can be found here:
https://stackoverflow.com/questions/46984456/how-to-change-folder-structure-of-dist-in-angular-cli-build?rq=1

**Comment by alan-agius4** [comment]
Hi, this is currently not possible and is out-side of the scope of the CLI.

What is possible is to have css resources in a different sub folder, and can be done using the `resourcesOutputPath` option.

More info: https://angular.io/cli/build

**Comment by julianpoemp** [comment]
@alan-agius4 Thanks for your answer. But when this is currently not possible why do you close this issue? 

If this is outside the scope of the cli, whose scope is it then?

I think this option to change the folder structure could be a very helpful feature, that would be interesting for other people, too.

**Comment by alan-agius4** [comment]
Hi @julianpoemp, 

It isn’t part of the current scope because it doesn’t add addition benefits apart from having a different folder. This also increases the code in our code base that we need to maintain and support.

Surly, if there are more requests to have this feature we’ll re-open and re-consider.

**Comment by julianpoemp** [comment]
@alan-agius4 Thank you. I understand.
