### ISSUE TITLE
Schema validation failed with the following errors:   Data path "" should NOT have additional properties(serve).

### ISSUE THREAD

**Issue by Manzurkds** [angular/angular-cli#14021]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I want to run e2e test, the test works fine, but it keeps on loading the angular server each time, in order to avoid that, I want to run the test without running the serve. Hence wrote this

```
"e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
          },
          "configurations": {
            "staging": {
              "serve": false,
              "devServerTarget": "angular2-express-starter:serve:dev-staging"
            }
          }
        },
```
But after this if I run `ng e2e --configuration=staging` I get the error as 
`
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(serve).
`

## 🔬 Minimal Reproduction
Simple steps to reproduce this bug.

Adding `serve` in options of e2e in `angular.json` file
Then running ng e2e

## 🌍 Environment
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.3
@angular-devkit/build-angular     0.12.3
@angular-devkit/build-optimizer   0.12.3
@angular-devkit/build-webpack     0.12.3
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.3.7
@angular/cli                      7.3.7
@ngtools/webpack                  7.2.3
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

**Comment by yashwp** [comment]
@Manzurkds Thanks for noticing the issue. I'm also facing the same issue.

**Comment by alan-agius4** [comment]
The failure here is expected. `serve` is not a valid options for the E2E builder. With regards to the other issue that you are experiencing. I am unable to replicate it. 

I strongly suggest you update the `@angular-devkit` and CLI packages to the latest version.

If the problem persists, please open a new issue with the steps to re-produce the issue. A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by Manzurkds** [comment]
@alan-agius4 
I had updated my @angular-devkit, but it doesn't change anything. If `serve` is not a valid option, then how do I run e2e test without running `ng serve` inside it.

My use case is, I want to run `ng serve` seperately.

So that any iterations I make to my test cases, I don't have to wait for `ng serve` to load up again and again.

**Comment by CJ42** [comment]
I had a similar issue related to schema validation and gave a solution in issue #14338.
This was based on my findings from two answers on StackOverflow (also related to Schema Validation error) :

- https://stackoverflow.com/a/56537342/8245387
- https://stackoverflow.com/a/56624167/8245387

You have version 0.12.3, but try to change to 0.12.4

 1) Open your `package.json` file at the root of your project :
```
[...]
"devDependencies": {
    "@angular-devkit/build-angular": "~0.800.6",        // <-- Change the version to 0.12.4
    "@angular/cli": "~8.0.6",
    "@angular/compiler-cli": "~8.0.3",
    "@angular/language-service": "~8.0.3",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}
```
 
Change the version 👍 
```
@angular-devkit/build-angular": "^0.800.1"
````

to : 
```
@angular-devkit/build-angular": "^0.12.4"
```

You have version `0.12.3` but try to change it to `0.12.4`. If your error is solved, then this could narrow down the problem.



This fixed
