### ISSUE TITLE
ng new fails: No matching version found for electron-to-chromium@^1.3.122

### ISSUE THREAD

**Issue by cogitaria-admin** [angular/angular-cli#14026]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

Running "ng new foo" fails: 

**No matching version found for electron-to-chromium@^1.3.122**

## 🔥 Exception or Error
<pre><code>

... more successful create messages ...
CREATE foo/e2e/src/app.e2e-spec.ts (632 bytes)
CREATE foo/e2e/src/app.po.ts (251 bytes)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for electron-to-chromium@^1.3.122
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'browserslist'
npm ERR! notarget
</code></pre>

## 🌍 Your Environment
<pre><code>

ng --version

Angular CLI: 7.3.7
Node: 10.15.3
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.7
@angular-devkit/core         7.3.7
@angular-devkit/schematics   7.3.7
@schematics/angular          7.3.7
@schematics/update           0.13.7
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Anything else relevant?**

Running on MacOS Mojave

**Comment by alan-agius4** [comment]
Hi, this must have been an npm intermittent propagation issue.
