### ISSUE TITLE
Error while deploying to github-pages

### ISSUE THREAD

**Issue by dancancro** [angular/angular-cli#1403]
OS?  
```
Mac OSX (El Capitan)
```
Versions. 
```
angular-cli: 1.0.0-beta.10
node: 4.4.0
os: darwin x64
```
Repro steps.

`ng github-pages:deploy --message "First deployment"`

The log given by the failure.
```
Built project successfully. Stored in "dist/".
fs.js:60
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOTEMPTY: directory not empty, rmdir '/Users/Dan/work/bernierebuttals/bernierebuttals/dist/vendor/@angular/platform-browser/src/'
    at Error (native)
```

5. Mention any other details that might be useful.
```
This is my first try at doing this.
I stopped the server before running the command.
```

**Comment by barrymoo** [comment]
Did you try it multiple times? This happened to me yesterday, but running the command a second time worked.

**Comment by dancancro** [comment]
That's odd.

I tried it a couple more times but had the same results.

**Comment by dancancro** [comment]
Hang on... I forgot to stop the server before those couple of times. After I did that, I tried it again and it worked.

**Comment by srivasrk** [comment]
I had to delete the dist folder, stop the server ng serve, and execute the deploy again.
