### ISSUE TITLE
Error when ng build --prod flag :  Uncaught TypeError: t is not a constructor

### ISSUE THREAD

**Issue by mariohmol** [angular/angular-cli#14046]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I cant tell, i can say was working in a previous deploy.
In this deploy i tested without updating using `npm i` and after with a `npm i ` , both same case so probably not.

### Description

This project was working before with `ng build --prod` but seems to not be anymore. 
Running without prod it works `ng build`.
When I run `ng build --prod` this complete the build successfully but when I try to run in the browser I receive an error:

```main.js:1 Uncaught TypeError: t is not a constructor
    at main.js:1
    at Ti (main.js:1)
    at main.js:1
    at new e (main.js:1)
    at Object.nl [as createNgModuleRef] (main.js:1)
    at t.create (main.js:1)
    at main.js:1
    at t.invoke (polyfills.js:1)
    at Object.onInvoke (main.js:1)
    at t.invoke (polyfills.js:1)
```

## 🔬 Minimal Reproduction

These are the dependencies:

```
"dependencies": {
    "@angular/animations": "^7.0.0",
    "@angular/cdk": "^7.0.0",
    "@angular/cli": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/material": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/router": "^7.0.0",
    "@ngx-translate/core": "^10.0.2",
    "ag-grid-angular": "^19.0.0",
    "ag-grid-community": "^19.0.0",
    "angular2-text-mask": "^9.0.0",
    "core-js": "^2.5.7",
    "hammerjs": "^2.0.8",
    "js-brasil": "^1.2.0",
    "ng-brazil": "^0.8.1",
    "ng-currency-format": "^0.1.6",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.0.0-rc.0",
    "typescript": "3.1.3",
    "zone.js": "^0.8.26"
  },
```

## 🔥 Exception or Error
<pre><code>
main.js:1 Uncaught TypeError: t is not a constructor
    at main.js:1
    at Ti (main.js:1)
    at main.js:1
    at new e (main.js:1)
    at Object.nl [as createNgModuleRef] (main.js:1)
    at t.create (main.js:1)
    at main.js:1
    at t.invoke (polyfills.js:1)
    at Object.onInvoke (main.js:1)
    at t.invoke (polyfills.js:1)

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.7
Node: 9.11.2
OS: linux x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@angular/language-service         6.0.9
@angular/material                 7.3.6
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.8.3

</code></pre>

**Anything else relevant?**

This happens in different OS and browsers, so i dont think is a environment error

**Comment by mariohmol** [comment]
Seems to be related with #9929 because it works with `--aot=false --build-optimizer=false` ..
did update ng cli and worked!! thanks!

**Comment by mariohmol** [comment]
If someone ends up here, having this issue again even with newest ng-cli.. 

had to use without aot e optimizer to make it work again

**Comment by kathygit** [comment]
I still have the same issue ... need to help !!
