### ISSUE TITLE
Typescript Support in `ng lint` via `tsnode`

### ISSUE THREAD

**Issue by damienwebdev** [angular/angular-cli#14043]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [x] lint
```

### Description
As a developer, I would like to define custom `tslint` rules in Typescript without requiring subsequent compilation to javascript with `tsc`. Manually compiling to javascript forces another unnecessary step, which just slows down my development process. This is supported in `tslint@5.7.0` with `tsnode`, so I would hope this would be fairly straightforward and may only require a documentation change.

### Describe the solution you'd like
Ideally, I'd be able to write my rule, update my `rulesDirectory` in `tslint.json` and have `tslint` pick up my rule automatically.

**Comment by clydin** [comment]
Thank you for the suggestion.  However, due to the deprecation of TSLint, the CLI will be migrating away from TSLint to ESLint so this is not something we are looking at supporting at this time.
