### ISSUE TITLE
ng build --prod 

### ISSUE THREAD

**Issue by eykar** [angular/angular-cli#14041]
when i run this command :ng build --prod
ERROR in node_modules/@types/jquery/index.d.ts(6103,66): error TS2344: Type '"timeout" | "onreadystatechange" | "responseType" | "withCredentials" | "msCaching"' does not satisfy the constraint '"abort" | "open" | "timeout" | "response" | "onreadystatechange" | "responseType" | "withCredentials" | "readyState" | "responseText" | "responseURL" | "responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.
Type '"msCaching"' is not assignable to type '"abort" | "open" | "timeout" | "response" | "onreadystatechange" | "responseType" | "withCredentials" | "readyState" | "responseText" | "responseURL" | "responseXML" | "status" | ... 21 more ... | "dispatchEvent"'.
how to fix it ?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
