### ISSUE TITLE
npm install node-sass fails: Binary has a problem: 

### ISSUE THREAD

**Issue by madhanmdkm** [angular/angular-cli#14051]
D:\AngularDev\ModelingAsService>npm install --save-dev  --unsafe-perm node-sass

> node-sass@4.11.0 install D:\AngularDev\ModelingAsService\node_modules\node-sas
s
> node scripts/install.js

Cached binary found at C:\Users\755845\AppData\Roaming\npm-cache\node-sass\4.11.
0\win32-x64-64_binding.node

> node-sass@4.11.0 postinstall D:\AngularDev\ModelingAsService\node_modules\node
-sass
> node scripts/build.js

Binary found at D:\AngularDev\ModelingAsService\node_modules\node-sass\vendor\wi
n32-x64-64\binding.node
Testing binary
Binary has a problem: Error: \\?\D:\AngularDev\ModelingAsService\node_modules\no
de-sass\vendor\win32-x64-64\binding.node is not a valid Win32 application.
\\?\D:\AngularDev\ModelingAsService\node_modules\node-sass\vendor\win32-x64-64\b
inding.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports (D:\AngularDev\ModelingAsService\node_modules\node-sass\li
b\binding.js:19:10)
    at Object.<anonymous> (D:\AngularDev\ModelingAsService\node_modules\node-sas
s\lib\index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
Building the binary locally
Building: C:\Program Files\nodejs\node.exe D:\AngularDev\ModelingAsService\node_
modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cfla
gs= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\AngularDev\\ModelingAsService\\node_modules\\node-gyp\\bin\\
node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "C:\Python27\python.exe" in
 the PATH
gyp verb `which` succeeded C:\Python27\python.exe C:\Python27\python.exe
gyp verb check python version `C:\Python27\python.exe -c "import sys; print "2.7
.15
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node v
ersion: 10.15.3
gyp verb command install [ '10.15.3' ]
gyp verb install input version string "10.15.3"
gyp verb install installing version: 10.15.3
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 10.15.3
gyp verb ensuring nodedir is created C:\Users\755845\.node-gyp\10.15.3
gyp verb created nodedir C:\Users\755845\.node-gyp\10.15.3
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.
tar.gz
gyp verb download using proxy url: "http://proxy.cognizant.com:6050/"
gyp WARN install got an error, rolling back install
gyp verb command remove [ '10.15.3' ]
gyp verb remove using node-gyp dir: C:\Users\755845\.node-gyp
gyp verb remove removing target version: 10.15.3
gyp verb remove removing development files for version: 10.15.3
gyp ERR! configure error
gyp ERR! stack Error: tunneling socket could not be established, statusCode=407
gyp ERR! stack     at ClientRequest.onConnect (D:\AngularDev\ModelingAsService\n
ode_modules\tunnel-agent\index.js:166:19)
gyp ERR! stack     at Object.onceWrapper (events.js:277:13)
gyp ERR! stack     at ClientRequest.emit (events.js:189:13)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:475:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at addChunk (_stream_readable.js:284:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:265:11)
gyp ERR! stack     at Socket.Readable.push (_stream_readable.js:220:10)
gyp ERR! stack     at TCP.onStreamRead [as onread] (internal/stream_base_commons
.js:94:17)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\AngularDev\\Modeling
AsService\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--li
bsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\AngularDev\ModelingAsService\node_modules\node-sass
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\755845\AppData\Roaming\npm-cache\_logs\2019-04-02T10_56_53
_728Z-debug.log
Terminate batch job (Y/N)? y

im using node version 
node -v
v10.15.3
npm -v
6.4.1

Please help me out from this

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by sai773** [comment]
C:\SavjeeCoin-master\src> npm install -g ionic
npm ERR! code ERR_OSSL_PEM_NO_START_LINE
npm ERR! error:0909006C:PEM routines:get_name:no start line

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-05-01T09_43_40_957Z-debug.log
can i get aolution for this error and iam usd many comands to recover from this error.

**Comment by osamagill** [comment]
C:\Users\*******>npm i -g @angular/cli
npm ERR! code ERR_OSSL_PEM_NO_START_LINE
npm ERR! error:0909006C:PEM routines:get_name:no start line

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\******\AppData\Roaming\npm-cache\_logs\2019-06-11T19_01_28_744Z-debug.log
