### ISSUE TITLE
[Wiki] Warn user about HMR limitation with lazy routes

### ISSUE THREAD

**Issue by Toub** [angular/angular-cli#14053]
# 🐞 Bug report (wiki documentation)

### Command (mark with an `x`)

```
- [x] serve
```

### Description

This wiki story page explains how to use HMR in your ng-cli application: [stories configure hmr](https://github.com/angular/angular-cli/wiki/stories-configure-hmr)

However, it does not work if you use lazy routes! See [https://github.com/PatrickJS/angular-hmr/issues/76](https://github.com/PatrickJS/angular-hmr/issues/76)

__PROBLEM__: the wiki page should warn the user about this limitation, and provide the link to the issue

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.2.2
Node: 10.15.1
OS: linux x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.4
@angular-devkit/build-angular      0.12.4
@angular-devkit/build-ng-packagr   0.12.4
@angular-devkit/build-optimizer    0.12.4
@angular-devkit/build-webpack      0.12.4
@angular-devkit/core               7.2.4
@angular-devkit/schematics         7.2.2
@angular/cdk                       7.2.2
@angular/cli                       7.2.2
@angular/flex-layout               7.0.0-beta.23
@angular/material                  7.2.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.2.4
@schematics/angular                7.2.2
@schematics/update                 0.12.2
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.28.4
</code></pre>

**Comment by alan-agius4** [comment]
Hi, the wiki pages are deprecated as of version 7, and we no longer accept PRs to improve them.

Their respective content have been moved to http://angular.io or in the case of HMR it should be the responsibility of provider to document on how to integrate the package with the CLI.

Thanks.

**Comment by Toub** [comment]
Ok.

So a warning about the deprecation status would be helpful.
