### ISSUE TITLE
'ember' is replaced with 'ng' a bit too eagerly in log output

### ISSUE THREAD

**Issue by duanemck** [angular/angular-cli#1405]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
**1.0.0-beta.8**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
  * In an existing app, add a file/type that has the word 'ember' in it somewhere.
  * In my case this was teamMember.component.ts
  * All logging around that file as well as typescript errors is output at teamM**_ng_**r
  * The 'ember' part is replaced by 'ng'

4. The log given by the failure. Normally this include a stack trace and some
   more information.
**Types of property 'teamMngs' are incompatible.**

5. Mention any other details that might be useful.

**Comment by mikegeyser** [comment]
I can confirm the same on OSX El Capitan, generating a component called 'september' that was converted to 'septng'.

mikegeyser@mbp ~/Code/random (master #) : ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.9
node: 5.12.0
os: darwin x64
mikegeyser@mbp ~/Code/random (master #) : ng g component september
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing component
  create src/app/septng/septng.component.css
  create src/app/septng/septng.component.html
  create src/app/septng/septng.component.spec.ts
  create src/app/septng/septng.component.ts
  create src/app/septng/index.ts

**Comment by gee-forr** [comment]
This is interesting reading: https://en.wikipedia.org/wiki/Scunthorpe_problem

**Comment by filipesilva** [comment]
Yeap, definitely bug.

**Comment by asnowwolf** [comment]
I met this bug too.
Is there anyone working on it? I've positioned it, it could be assigned to me, I'll try to resolve this

**Comment by filipesilva** [comment]
@asnowwolf feel free to try your hand at it, ping me for a PR review.

**Comment by asnowwolf** [comment]
Ok :-)

It seems that I don't have to get assigned before I start working? I don't know what's your workflow.

**Comment by asnowwolf** [comment]
@filipesilva Done.
