### ISSUE TITLE
High CPU usage during "ng test" idle

### ISSUE THREAD

**Issue by bobrosoft** [angular/angular-cli#1406]
Please provide us with the following information:

1. OS?
MacBook Air on Mac OSX El Capitan 10.11.1
Also tested on MacBook Pro with Mac OSX El Capitan 10.11.4

2. Versions.
angular-cli: 1.0.0-beta.10 (also tested on 1.0.0-beta.6)
node: 4.3.1
os: darwin x64

3. Repro steps.
`ng new testproj`
`cd testproj`
`ng test`

4. The log given by the failure.
All compiles normally, no issues, tests passes.
**But after that angular-cli process starts to consume from 80% to 200% of CPU (depends on project complexity, on empty project it's 80%)**

5. Mention any other details that might be useful.
High CPU usage slows down all things, compilation and dev process.
In the same time **if you run `ng serve`, it not consume CPU while idle.**
Tried with `watchman` installed as well -- same issue.

**Comment by aciccarello** [comment]
FYI, there are people working on redoing the build system so this could change significantly in the near future.

**Comment by bobrosoft** [comment]
@aciccarello yes, but nobody reported that before and that's kinda critical one, want to rise a flag.

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
