### ISSUE TITLE
Ng Build fails, JQueryAjaxSettings not found

### ISSUE THREAD

**Issue by otoomey** [angular/angular-cli#14074]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Running `ng build --base-href` results in a compile failure if references to `JQueryAjaxSettings` exist in project: 
```
error TS2304: Cannot find name 'JQueryAjaxSettings'.
```

This occurs despite the fact that the relevant definition exists in `node_modules/@types/jquery/legacy.d.ts`; and despite the fact that Visual Studio Code recognizes that the class exists within the project scope (`JQueryAjaxSettings` appears in the typing predictions, and is not marked as an error in the editor).

## 🔬 Minimal Reproduction

Either install and reference a dependency that references `JQueryAjaxSettings` (such as @openid/appauth) or add the following to any front-end class in the project:
`
const foo: JQueryAjaxSettings;
`

## 🔥 Exception or Error
Here `private foo: JQueryAjaxSettings;` was added to `app.module.ts` to demonstrate the issue.
<pre><code>

</code>ERROR in node_modules/@openid/appauth/built/node_support/node_requestor.d.ts(6,22): error TS2304: Cannot find name 'JQueryAjaxSettings'.
// ... 4 more in @openid/appauth
src/app/app.module.ts(32,16): error TS2304: Cannot find name 'JQueryAjaxSettings'.
</pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.7
Node: 10.14.1
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.7
@angular-devkit/build-angular     0.13.7
@angular-devkit/build-optimizer   0.13.7
@angular-devkit/build-webpack     0.13.7
@angular-devkit/core              7.3.7
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.6
@angular/cli                      7.3.7
@angular/material                 7.3.6
@ngtools/webpack                  7.3.7
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

No modifications have been made to the `tsconfig.json`, `src/tsconfig.app.json` or `angular.json` .

**Comment by clydin** [comment]
Types for the application need to be explicitly added to the `types` array within `src/tsconfig.app.json`.  This is to ensure that only types required by the application are included and the compiler can catch errors at build time related to including code that would be otherwise unavailable in a browser (node, jasmine, etc.).
