### ISSUE TITLE
Generating module using cli takes long time

### ISSUE THREAD

**Issue by itsmeneartou** [angular/angular-cli#14075]
### Is this a regression?
Maybe it started taking long time after I installed nativescript for the project.
### Description
When I try to create a new module using `ng g m test`. It takes very long time and this waiting is most probably an error because creating 4-5 files should not take this long. The component created using `ng g c my-component` takes almost no time.

## 🔬 Minimal Reproduction
`ng g m test`

## 🌍 Your Environment
Windows 10 core i5 8th Gen 8GB ram, editor:visual studio code, terminal:Integrated terminal

**Comment by alan-agius4** [comment]
Hi, kindly provide the output of `ng version`?

Also, it would be great if you can provide a reproduction on how this becomes slower. As without a reproduction it would be hard to identify and fix the problem.

**Comment by itsmeneartou** [comment]
The reproduction steps are simple.
1) Create new angular app using `ng new moduleCreationBug`.
Optional: try creating a test module and check everything is fine `ng g m test` (In this step module gets created in no time.)
2) Now add nativescript to angular app as taught in [this](https://blog.angular.io/apps-that-work-natively-on-the-web-and-mobile-9b26852495e7) blog using `ng add @nativescript/schematics`

3) Now try creating module again using `ng g m test2` and now it takes forever to create the module, I have never been able to create module after adding nativescript because I stop using ctrl+C because it takes too long.

**Comment by clydin** [comment]
`@nativescript/schematics` sets itself as the default and replaces all the generation schematics.  This issue ideally should be raised on the NativeScript repository.

**Comment by clydin** [comment]
Closing as this appears to be `@nativescript/schematics` issue and not an `@angular/cli` issue.
