### ISSUE TITLE
ng update fail with error Cannot find module '../run-schematic/executor'

### ISSUE THREAD

**Issue by xmlking** [angular/angular-cli#14083]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
trying to updated `8.0.0-beta.10` to `8.0.0-beta.11`
I was hoping `migrations` should  updating `codelyzer` version and update `tslint.json`
 
`ng update @angular/cli --next` throw following error 

```
Cannot find module '../run-schematic/executor'
```

## 🔥 Exception or Error
<pre><code>

ng update @angular/cli --next

Cannot find module '../run-schematic/executor'
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.0-beta.11
Node: 11.13.0
OS: darwin x64
Angular: 8.0.0-beta.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0-beta.11
@angular-devkit/build-angular      0.800.0-beta.11
@angular-devkit/build-ng-packagr   0.800.0-beta.11
@angular-devkit/build-optimizer    0.800.0-beta.11
@angular-devkit/build-webpack      0.800.0-beta.11
@angular-devkit/core               8.0.0-beta.11
@angular-devkit/schematics         8.0.0-beta.11
@angular/cdk                       7.3.6
@angular/flex-layout               7.0.0-beta.24
@angular/material                  7.3.6
@angular/pwa                       0.800.0-beta.11
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0-beta.11
@schematics/angular                8.0.0-beta.11
@schematics/update                 0.800.0-beta.11
ng-packagr                         5.0.1
rxjs                               6.4.0
typescript                         3.3.4000
webpack                            4.29.6

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, would you mind sharing your `package.json` before the update?

I have tried to update from beta.10 to beta.11 and I didnt' get any error
```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0-beta.10
Node: 10.10.0
OS: win32 x64
Angular: 8.0.0-beta.11
... animations, common, compiler, core, forms, language-service
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.10
@angular-devkit/build-angular     0.800.0-beta.10
@angular-devkit/build-optimizer   0.800.0-beta.10
@angular-devkit/build-webpack     0.800.0-beta.10
@angular-devkit/core              8.0.0-beta.10
@angular-devkit/schematics        8.0.0-beta.10
@angular/cli                      8.0.0-beta.10
@angular/compiler-cli             8.0.0-beta.10
@ngtools/webpack                  8.0.0-beta.10
@schematics/angular               8.0.0-beta.10
@schematics/update                0.800.0-beta.10
rxjs                              6.4.0
typescript                        3.3.4000
webpack                           4.29.6


C:\git\cli-repos\beta-foo    master± 
λ ng update @angular/cli --next
Updating package.json with dependency @angular/cli @ "8.0.0-beta.11" (was "8.0.0-beta.10")...
UPDATE package.json (1401 bytes)
```

That said, the migrations at the moment are targeting the stable release.

**Comment by xmlking** [comment]
Did you get all migrations applied besides versions in package.json updates ?
I can able to reproduce by switching to beta.10 and npm install, then try to upgrade again.
My repo is nrwl/nx bssed https://github.com/xmlking/ngx-starter-kit

**Comment by alan-agius4** [comment]
Hi, the migrations won’t be applied as this as targeting the major version for the time being.

See: https://github.com/angular/angular-cli/pull/14088

**Comment by alan-agius4** [comment]
Hi, is this reproducible in version 8 release candidate?

**Comment by alan-agius4** [comment]
Closing as no further feedback provided. 

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by kuncevic** [comment]
Got same issue updating from 8.1.0 to 8.1.1 after removing the node_modules folder seems like all working.
