### ISSUE TITLE
3rdpartylicenses.txt missing licenses for open-iconic 

### ISSUE THREAD

**Issue by bbarry** [angular/angular-cli#14095]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

unknown

### Description

I think I might be doing something wrong (this import rule feels weird), but I'm not sure what or if it is a defect somewhere. I've added the package `open-iconic` and used the css and font in global styles and built... then viewed 3rdpartylicenses.txt and expected the package to be mentioned, but it wasn't.

## 🔬 Minimal Reproduction

1. open prompt in blank directory
2. `ng new license-test`
3. add router
4. choose css
5. `cd license-test`
6. `npm i open-iconic`
7. edit src/styles.css and add `@import url("../node_modules/open-iconic/font/css/open-iconic-bootstrap.css");`
8. `ng build --prod`
9. review dist/3rdpartylicenses.txt

## 🔥 Exception or Error

Expecting licenses from node_modules/open-iconic/FONT-LICENSE and node_modules/open-iconic/ICON-LICENSE to be in 3rdpartylicenses.txt, but they aren't there.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 11.13.0
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by dave-bernstein** [comment]
[CLI](https://github.com/angular/angular-cli/blob/2ee76e73716f8af4efe9ca7f25497179afbae2a2/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/browser.ts#L58-L67) is using license-webpack-plugin to generate 3rdpartylicenses.txt. 

Per the license-webpack-plugin  [readme](https://github.com/xz64/license-webpack-plugin#usage):
>Third party libraries imported via external tools like SASS `@import` may not appear in the output (since webpack does not process `@import`).

**Comment by alan-agius4** [comment]
Hi @bbarry, @dgp1130 and it seems that there is nothing we can do for this issue as it's the expected behaviour.

See below;

> @alan-agius4, I tried out on their repro case and I do see open-iconic in the output. I see it as:
> 
> --------------------------------------------------------------------------------
> open-iconic v1.1.1 - Iconic
> git+https://github.com/iconic/open-iconic.git
> --------------------------------------------------------------------------------
> 
> (MIT License OR SIL OFL 1.1)
> The user said they expected to see that repo's FONT-LICENSE and ICON-LICENSE. I don't think those particular files are picked up, as this seems to come from the package.json. I think that would be expected as those two *-LICENSE names are non-standard. If so, we can probably close that issue as well with this PR.


Thanks.

**Comment by bbarry** [comment]
I think that PR does fix this issue reasonably. Perhaps a future version of open-iconic or license-checker-webpack-plugin will improve it by including the full license file on the first time it matches, but at least it mentions the package now in the output. The previous plugin omits any mention of open-iconic.
