### ISSUE TITLE
Angular-cli "Unknown option: '--sourceMap' when using '--project'

### ISSUE THREAD

**Issue by Ruud-cb** [angular/angular-cli#14094]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Description

 A clear and concise description of the problem...

`ng build --sourceMap --watch` works.
`ng build --project mylib --sourceMap --watch` does not work

## 🔬 Minimal Reproduction

1. Create an app `ng new myapp` (yes routing, SASS)
2. cd to the folder
3. Create a new library `ng generate library my-new-lib`
4. Run `ng build --sourceMap`, this works (I know this is default behavior, put it on false also works).
5. Run `ng build my-new-lib --sourceMap`
6. Get the error: `Unknown option: '--sourceMap'

Also tried all of the similar commands that I know or found on the internet:

`--source-map`
`--vendor-source-map`
`--vendorSourceMap`

## 🔥 Exception or Error
<pre><code>
 Unknown option: '--sourceMap'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.8
Node: 8.9.4
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-ng-packagr   0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.8
@angular/cli                       7.3.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0
</code></pre>

**Anything else relevant?**

A [suggested option](https://stackoverflow.com/a/52534493/2901207) was to change the angular.json and include `"vendorSourceMap" : true` within my-new-lib > architect -> build -> options, but that gives the following error:

<pre><code>
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(vendorSourceMap).
</code></pre>

Another [option](https://stackoverflow.com/a/51491015/2901207) is to change the tsconfig.json. But after doing that, I get the error an application startup `Cannot Get /` (which is btw the best possible error message to debug -.-)

**Comment by alan-agius4** [comment]
Hi, that is because the library builder doesn’t have a sourcemap option. As for libraries sourcemaps are always generated.

Issue is related to: https://github.com/angular/angular/issues/26569

**Comment by Ruud-cb** [comment]
The reason for being after this is because I want to debug (with chrome DevTools) through the code, and not the javascript code. So to my understanding I need the source maps for that, which seem to be not present?

**Comment by alan-agius4** [comment]
You need to enable vendor sourcemaps in your application and not your library.

**Comment by Ruud-cb** [comment]
..aaaaaand how do I do that then..

**Comment by alan-agius4** [comment]
You need to replace the `sourceMap` property in the `angular.json` to

```
sourceMap: {
        scripts: true,
        styles: true,
        vendor: true
}
```

**Comment by Proantagonist** [comment]
That worked for me, except I had to put it in the `serve` target options.

```
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build",
            "sourceMap": {
              "scripts": true,
              "styles": true,
              "vendor": true
            }
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        }
```
