### ISSUE TITLE
Angular scss-loader loads js files from node_modules on serve, not scss

### ISSUE THREAD

**Issue by Random90** [angular/angular-cli#14099]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] serve
```
### Description

 A clear and concise description of the problem...

I want to use include-media scss file from https://github.com/eduardoboucas/include-media using npm. 
File can be located at 'node_modules/include-media/dist/_include-media.scss'.
I receive error when trying to import it using '@import 'include-media', even after adding 'node_modules/include-media/dist' to includePath under stylePreprocessorOptions.
It seems that saas-loader is trying to read index.js file from 'node_modules/include-media' instead of scss file in dist folder

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/app/app.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

    @include media(">phone", "<=tablet") {
            ^
      No mixin named media
      in C:\...\my-website-angular\src\app\app.component.scss (line 20, column 14)
ERROR in ./src/scss/main.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/scss/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

var path = require('path');
var package = require('./package.json');

var entryPoint = require.resolve(package.name);
var distPath = path.join(path.dirname(entryPoint), 'dist');

module.exports = {
    includePath: distPath
};

^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var path = require("
      in C:\..\my-website-angular\node_modules\include-media\index.js (line 1, column 1)
i ｢wdm｣: Failed to compile.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.8
Node: 10.15.3
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/flex-layout              7.0.0-beta.24
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.

Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

**app.component.scss**
```
@import "include-media";

@include media(">phone", "<=tablet") {
	* {
		color: red;
	}
}
```
 **angular.json**
```
"stylePreprocessorOptions": {
  "includePaths": [
    "node_modules/include-media/dist"
  ]
},
```

**Build result**
```
λ ng serve
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

Date: 2019-04-08T08:48:57.487Z
Hash: 85ea93eb56443ae36f9c
Time: 12473ms
chunk {es2015-polyfills} es2015-polyfills.js, es2015-polyfills.js.map (es2015-polyfills) 284 kB [initial] [rendered]
chunk {main} main.js, main.js.map (main) 32.3 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.6 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.52 MB [initial] [rendered]
```
If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
