### ISSUE TITLE
Could not resolve entry .. in my angular-library.js

### ISSUE THREAD

**Issue by AbeerSul** [angular/angular-cli#14101]
# 🐞 Bug report

```
- [ ] new
- [ ✔] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Not sure

### Description
I'm unable to build angular library.
Building my angular library with command `ng build angular-library` shows error:

BUILD ERROR
Could not resolve entry (C:\Users\..\angular-library\dist\esm2015\angular-library.js)
Error: Could not resolve entry (C:\Users\..\angular-library\dist\esm2015\angular-library.js)
    at error (C:\Users\..\node_modules\rollup\dist\rollup.js:3598:30)
    at C:\Users\..\node_modules\rollup\dist\rollup.js:18005:17

I've been struggling for hours, with no avail. I removed all usages of barrels in my library and made sure imports are correct. Error is not clear and doesn't tell me where to search for the issue.

## 🔬 Minimal Reproduction
command `ng build angular-library` 

## 🔥 Exception or Error
<pre><code>
Could not resolve entry (C:\Users\..\angular-library\dist\esm2015\angular-library.js)
Error: Could not resolve entry (C:\Users\..\angular-library\dist\esm2015\angular-library.js)
    at error (C:\Users\..\node_modules\rollup\dist\rollup.js:3598:30)
    at C:\Users\..\node_modules\rollup\dist\rollup.js:18005:17

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.5
Node: 10.15.1
OS: win32 x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.3
@angular-devkit/build-angular      0.13.3
@angular-devkit/build-ng-packagr   0.13.4
@angular-devkit/build-optimizer    0.13.3
@angular-devkit/build-webpack      0.13.3
@angular-devkit/core               7.3.3
@angular-devkit/schematics         7.3.5
@angular/cli                       7.3.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.3
@schematics/angular                7.3.5
@schematics/update                 0.13.5
ng-packagr                         5.0.1
rxjs                               6.4.0
typescript                         3.1.6
webpack                            4.29.0
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by AbeerSul** [comment]
@alan-agius4 I see.
I wish I can create a repo but the library is large enough and I'm not sure where the issue can be.

But here is the directory structure, I hope you can conclude any debugging steps for me.

![angular-library](https://user-images.githubusercontent.com/18706958/55718719-0f53d780-5a05-11e9-81e8-f150f9e97727.PNG)


I doubt its related to circular dependencies that used to show earlier as warnings but never broke the build. But now I'm unable to see them nor fix them.. because the "Could not resolve entry" shows up 😞

**Comment by alan-agius4** [comment]
Hi, I am not sure what the problem might be seeing the folder structure. It might be something related to ng-packagr configuration since your structure is different that the standard CLI folder layout.

Unfortunately, we cannot look into this any further without a reproduction and a clear indication on how to replicate the issue.

Also, it worth mentioning that the error is being thrown by ng-packagr, and such error typically means it can not locate the distributable file. Hopefully it helps you to narrow down the error, and possibly open an issue with ng-packagr with a repro so that a better error message is shown when such case is encountered.

Thanks for your understanding.

**Comment by GeorgeKnap** [comment]
@alan-agius4 
I am getting the same issue when building angular library.
CLI 7.3.8

lib tsconfig: ```{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "module": "esnext",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "types": [],
    "lib": [
      "dom",
      "esnext"
    ]
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "flatModuleId": "AUTOGENERATED",
    "flatModuleOutFile": "AUTOGENERATED"
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```

error: ```Could not resolve entry (c:\Development\sds\core-ui-v1\dist\shared\esm2015\solar-log-shared.js)
Error: Could not resolve entry (c:\Development\sds\core-ui-v1\dist\shared\esm2015\solar-log-shared.js)
    at error (c:\Development\sds\core-ui-v1\node_modules\rollup\dist\rollup.js:3766:30)
    at c:\Development\sds\core-ui-v1\node_modules\rollup\dist\rollup.js:18184:17```

**Comment by victornoel** [comment]
@alan-agius4 I'm having the same problem as @GeorgeKnap : it seems that because one of my module depends on the osfen (it uses an injectable service declared in the other module), the esm2015 folder contains the two modules with src folders as in his screenshot.

I don't think it is meant to happen, and the error is very cryptic here, there is no way to know how to workaround this.

Still using angular 6 btw.

**Comment by victornoel** [comment]
For the record, with ng-packgr 5.3.0 I get this kind of error:
```
error TS6059: File '/home/victor/Codebases/app/projects/mylib/first/src/api.service.ts' is not under 'rootDir' '/home/victor/Codebases/app/projects/mylib/second/src'. 'rootDir' is expected to contain all source files.
```

The import is of the form:
```
import { APIService } from 'mylib/first';
```

ANd is exported in first's `public_api.ts`

**Comment by victornoel** [comment]
My problem was caused by something similar to https://stackoverflow.com/questions/51850063/rootdir-is-expected-to-contain-all-source-files and bumping typescript to 3.1 solved the problem.
