### ISSUE TITLE
The server started by ng e2e does not seem to auto reload changed files

### ISSUE THREAD

**Issue by ancabanca123** [angular/angular-cli#14105]
# 🐞 Bug report

### Command (mark with an `x`)
ng e2e --configuration=my-module-config

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't know wether this is a bug or this is how it's intended to work.

### Description

I am trying to change a content of a json file from one test suite to another, and the file I am changing is not reloading

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
Angular CLI: 7.3.6
Node: 11.0.0
OS: darwin x64
Angular: 7.2.9

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

However E2E doesn't support watch mode. See: https://github.com/angular/angular-cli/issues/2861

**Comment by ancabanca123** [comment]
So you're saying there is no way I can solve my auto reload problem?

**Comment by alan-agius4** [comment]
At the moment, that is not supported.
