### ISSUE TITLE
recompiles with ctrl c

### ISSUE THREAD

**Issue by proronen** [angular/angular-cli#14102]
# 🐞 Bug report

```
- [X ] serve
```

### Is this a regression?

No, i am new to angular-cli

### Description

when running ng-serve it takes time but it complies, but when saving when the angular-cli should recompile sometime he does, and sometimes it needs me to do ctrl c for it to continue with the re-complie.

Has anyone experienced something like this?

## 🔬 Minimal Reproduction

first run ng-serve, and then make a change to a file, 

now when you look at the cli you can sometime see nothing happen so you do CTRL+C and then it continues with the compile and its all ok,

Or 

it gets stuck somewhere in the middle of compile for a long time and you do a CTRL+C and then it continues to work.

## 🔥 Exception or Error
No errors

## 🌍 Your Environment

Angular CLI: 7.3.7
Node: 10.15.3
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.7
@angular-devkit/schematics         7.3.7
@angular/cdk                       7.3.6
@angular/cli                       7.3.7
@angular/compiler-cli              7.2.12
@angular/material                  7.3.6
@angular/material-moment-adapter   7.3.6
@angular/pwa                       0.13.7
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.7
@schematics/update                 0.13.7
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0

i had this issue before working with an old HD, so i switched to SSD and reinstalled everything including windows and still have this issue

**Comment by alan-agius4** [comment]
Hi, I had a quick look at this, and I am unable to reproduce the above mentioned issue with the steps provided.

Can you kindly explain how can I reproduce this? I tried to change, Html, Scss and Ts files and the recompilation happened almost instantly.

Thanks.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
