### ISSUE TITLE
ERROR in AppModule is not an NgModule

### ISSUE THREAD

**Issue by saisandhyalakshmipathy** [angular/angular-cli#14107]
The following error when trying to build with yarn.

[INFO] ERROR in AppModule is not an NgModule
[INFO]
[INFO] ERROR in ./src/main.ts
[INFO] Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\vepatti\IdeaProjects\wom-docflow\src\main\frontend\src'
[INFO] @ ./src/main.ts 4:0-74
[INFO] @ multi ./src/main.ts

yarn version: 1.6
node version: v8.9.1
pom

![image](https://user-images.githubusercontent.com/46493591/55751109-88a1f900-5a0a-11e9-9967-f40acfbaa4e1.png)

package.json

"dependencies": {
"@angular/animations": "4.3.1",
"@angular/common": "4.3.1",
"@angular/compiler": "4.3.1",
"@angular/compiler-cli": "4.3.1",
"@angular/core": "4.3.1",
"@angular/forms": "4.3.1",
"@angular/http": "4.3.1",
"@angular/platform-browser": "4.3.1",
"@angular/platform-browser-dynamic": "4.3.1",
"@angular/platform-server": "4.3.1",
"@angular/router": "4.3.1",
"intl": "^1.2.5",
"ng2-translate": "5.0.0",
"node-sass": "4.10.0",
"primeng": "4.2.2",
"rxjs": "5.1.0",
"typescript": "2.2.2",
"underscore": "1.8.3",
"zone.js": "0.8.5",
"file-saver": "^1.3.3",
"jspdf": "1.4.1",
"html2canvas": "1.0.0-alpha.12"
},

Even If I do yarn install and then ran yarn run build on the command line directly, instead of via this plugin, I got following error
![image](https://user-images.githubusercontent.com/46493591/55751201-c010a580-5a0a-11e9-8eb9-c2ac2ed47d84.png)

Note: Doesn't get this error if i use npm.

**Comment by alan-agius4** [comment]
Closing as it doesn't follow the issue template.
