### ISSUE TITLE
sporadic recompilation

### ISSUE THREAD

**Issue by acohenOT** [angular/angular-cli#14116]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x ] serve
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.0

### Description

When running <code>ng serve</code> sometimes without explicit change in the code the project gets recompiled.

This is related to https://github.com/angular/angular-cli/issues/13861 though the 'kind' error has been resolved with 7.3.8, the sporadic recompilation remains.

## 🔬 Minimal Reproduction

This cannot be reproduced at will though is repeatable multiple times a day during development. Are there any verbose logging settings that can be enabled that can try to help capture the cause?

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.8
Node: 10.15.3
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.6
</code></pre>

**Comment by CSchulz** [comment]
There are no changes of the node_modules? I have encountered the issue if there are file changes.

**Comment by acohenOT** [comment]
@CSchulz  no changes that I'm making, no (perhaps my corporate anti-virus is triggering a change detection, but I cannot disable that). Do you know if there is a way to enable any verbose logging to see what is causing a recompile?

**Comment by acohenOT** [comment]
This appears to be resolved with Angular 8.
