### ISSUE TITLE
Hello, i am using angular 5 .net core 2.0 template for my project. After publishing this project i am getting error as  Error : CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory. Please help

### ISSUE THREAD

**Issue by ashutoshkushawaha** [angular/angular-cli#14111]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
my package.json file is
{
  "name": "ITNepalCRM",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng-high-memory": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng",
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "webpack --config webpack.config.vendor.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@aspnet/signalr": "^1.0.4",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "@ng-select/ng-select": "^1.5.2",
    "@ngtools/webpack": "1.8.0",
    "@progress/kendo-angular-buttons": "^4.0.0",
    "@progress/kendo-angular-dateinputs": "^3.1.0",
    "@progress/kendo-angular-dropdowns": "^2.1.0",
    "@progress/kendo-angular-excel-export": "^1.0.7",
    "@progress/kendo-angular-grid": "^3.1.0",
    "@progress/kendo-angular-inputs": "^3.0.0",
    "@progress/kendo-angular-intl": "^1.4.0",
    "@progress/kendo-angular-l10n": "^1.3.0",
    "@progress/kendo-data-query": "^1.3.0",
    "@progress/kendo-drawing": "^1.5.3",
    "@types/file-saver": "^2.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "@types/webpack-env": "1.13.0",
    "angular-nepali-datepicker": "^0.1.3",
    "angular-tree-component": "^7.0.0",
    "angular2-jwt": "^0.2.3",
    "angular2-router-loader": "^0.3.5",
    "angular2-template-loader": "0.6.2",
    "angularx-social-login": "^1.2.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "3.3.7",
    "codelyzer": "~3.2.0",
    "css": "2.2.1",
    "css-loader": "^0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "file-saver": "^2.0.0",
    "html-loader": "0.4.5",
    "isomorphic-fetch": "2.2.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "jwt-decode": "^2.2.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng2-search-filter": "^0.4.7",
    "ngx-bootstrap": "^2.0.3",
    "ngx-ckeditor": "^0.3.2",
    "ngx-contextmenu": "^4.2.0",
    "ngx-drag-drop": "^1.1.0",
    "ngx-highlight-js": "^1.0.3",
    "ngx-pagination": "^3.2.0",
    "ngx-perfect-scrollbar": "^7.2.0",
    "ngx-slimscroll": "^3.6.1",
    "ngx-toastr": "^8.10.2",
    "ngx-treeview": "^6.0.0",
    "npm": "^6.6.0",
    "preboot": "4.5.2",
    "protractor": "~5.1.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.5.10",
    "to-string-loader": "1.1.5",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "url-loader": "0.5.9",
    "webpack": "^2.7.0",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.0",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/chai": "4.0.1",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/jquery": "^3.3.1",
    "@types/jwt-decode": "^2.2.1",
    "@types/lodash": "^4.14.110",
    "@types/node": "~6.0.60",
    "angular-file": "^0.5.4",
    "chai": "4.0.2",
    "codelyzer": "~3.2.0",
    "cross-env": "^5.0.5",
    "increase-memory-limit": "^1.0.3",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-webpack": "2.0.3",
    "protractor": "~5.1.2",
    "style-loader": "^0.18.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "^2.9.2",
    "webpack-cli": "^3.1.2"
  }
}

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ashutoshkushawaha** [comment]
@alan-agius4 , if you have solution for this , please share .

**Comment by alan-agius4** [comment]
Kindly try to update to the latest version of the CLI.

If the problem persists after updating kindly open an issue following the issue template. Issues which don’t follow the template will be closed.

Thanks.

**Comment by ashutoshkushawaha** [comment]
@alan-agius4  i have just went to editProject.csproj and changed
1.   <Exec Command="node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" /> to   <Exec Command="node --max_old_space_size=10240 node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod" />

2. <Exec Command="node_modules/webpack/bin/webpack.js --env.prod" /> to <Exec Command="node --max_old_space_size=10240 node_modules/webpack/bin/webpack.js --env.prod" />

this work for me.
