### ISSUE TITLE
How to configure Parse Server with MongoDB?

### ISSUE THREAD

**Issue by KarthikeyanGopalan** [angular/angular-cli#14121]
Actually, I have Installed the necessary software but I couldn't able to pass this step!!! Please, anyone, help me with this...
 
Starting a MongoDB deployment to test against...{ [Error: EPERM: operation not permitted, symlink 'C:\Users\Indium Software\.mongodb\versions\mongodb-4.0.8-windows-64' -> 'C:\Users\Indium Software\.mongodb\versions\mongodb-current']
  errno: -4048,
  code: 'EPERM',
  syscall: 'symlink',

This is what the error I have received...

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
