### ISSUE TITLE
Issue with node-sass during project compilation

### ISSUE THREAD

**Issue by krishna-7** [angular/angular-cli#14127]
**Report**
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### **Regression**

Yes, the issue was reported and marked as resolved

### **Description**
While running the command `ng server -o` the system throws error if we choose the scss style sheet.

### **🔬 Minimal Reproduction**

> `ng new project1`
> ? Would you like to add Angular routing? Yes
> ? Which stylesheet format would you like to use? (Use arrow keys)
> > CSS
>   SCSS   [ http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syn
> 
> ? Which stylesheet format would you like to use?
>   CSS
> > SCSS   [ http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syn
> 
> ? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax ]
> `ng serve`

### **Exception or Error**

> > node-sass@4.11.0 install E:\Projects\project1\node_modules\node-sass
> > node scripts/install.js
> 
> Downloading binary from https://github.com/sass/node-sass/releases/downloa
> 1.0/win32-x64-67_binding.node
> Cannot download "https://github.com/sass/node-sass/releases/download/v4.11
> 32-x64-67_binding.node":
> 
> tunneling socket could not be established, cause=connect ECONNREFUSED 127.
> 80
> 
> Hint: If github.com is not accessible in your location
>       try setting a proxy via HTTP_PROXY, e.g.
> 
>       export HTTP_PROXY=http://example.com:1234
> 
> or configure npm proxy via
> 
>       npm config set proxy http://example.com:8080
> 
> > node-sass@4.11.0 postinstall E:\Projects\project1\node_modules\node-sass
> > node scripts/build.js
> 
> Building: C:\Program Files\nodejs\node.exe E:\Projects\project1\node_modul
> e-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= -
> ss_ldflags= --libsass_library=
> gyp info it worked if it ends with ok
> gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
> gyp verb cli   'E:\\Projects\\project1\\node_modules\\node-gyp\\bin\\node-
> ',
> gyp verb cli   'rebuild',
> gyp verb cli   '--verbose',
> gyp verb cli   '--libsass_ext=',
> gyp verb cli   '--libsass_cflags=',
> gyp verb cli   '--libsass_ldflags=',
> gyp verb cli   '--libsass_library=' ]
> gyp info using node-gyp@3.8.0
> gyp info using node@11.13.0 | win32 | x64
> gyp verb command rebuild []
> gyp verb command clean []
> gyp verb clean removing "build" directory
> gyp verb command configure []
> gyp verb check python checking for Python executable "python2" in the PATH
> gyp verb `which` failed Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (E:\Projects\project1\node
> es\which\which.js:13:12)
> gyp verb `which` failed     at F (E:\Projects\project1\node_modules\which\
> js:68:19)
> gyp verb `which` failed     at E (E:\Projects\project1\node_modules\which\
> js:80:29)
> gyp verb `which` failed     at E:\Projects\project1\node_modules\which\whi
> 89:16
> gyp verb `which` failed     at E:\Projects\project1\node_modules\isexe\ind
> 42:5
> gyp verb `which` failed     at E:\Projects\project1\node_modules\isexe\win
> s:36:5
> gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
> gyp verb `which` failed  python2 { Error: not found: python2
> gyp verb `which` failed     at getNotFoundError (E:\Projects\project1\node
> es\which\which.js:13:12)
> gyp verb `which` failed     at F (E:\Projects\project1\node_modules\which\
> js:68:19)
> gyp verb `which` failed     at E (E:\Projects\project1\node_modules\which\
> js:80:29)
> gyp verb `which` failed     at E:\Projects\project1\node_modules\which\whi
> 89:16
> gyp verb `which` failed     at E:\Projects\project1\node_modules\isexe\ind
> 42:5
> gyp verb `which` failed     at E:\Projects\project1\node_modules\isexe\win
> s:36:5
> gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
> gyp verb `which` failed   stack:
> gyp verb `which` failed    'Error: not found: python2\n    at getNotFoundE
> E:\\Projects\\project1\\node_modules\\which\\which.js:13:12)\n    at F (E:
> ects\\project1\\node_modules\\which\\which.js:68:19)\n    at E (E:\\Projec
> oject1\\node_modules\\which\\which.js:80:29)\n    at E:\\Projects\\project
> e_modules\\which\\which.js:89:16\n    at E:\\Projects\\project1\\node_modu
> sexe\\index.js:42:5\n    at E:\\Projects\\project1\\node_modules\\isexe\\w
> .js:36:5\n    at FSReqCallback.oncomplete (fs.js:158:21)',
> gyp verb `which` failed   code: 'ENOENT' }
> gyp verb check python checking for Python executable "python" in the PATH
> gyp verb `which` succeeded python C:\Users\DELL\AppData\Local\Programs\Pyt
> thon37-32\python.EXE
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\DELL\AppData\Local\Programs
> n\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_inf
> 
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:297:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:1001:16)
> gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:4
> 
> gyp ERR! stack     at Socket.emit (events.js:193:13)
> gyp ERR! stack     at Pipe._handle.close (net.js:614:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\Projects\\proj
> node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass
>  "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd E:\Projects\project1\node_modules\node-sass
> gyp ERR! node -v v11.13.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> Build failed with error code: 1
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modul
> vents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fse
> 1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":
> )
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 (node_mod
> ode-sass):
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.11.0 postinsta
> ode scripts/build.js`
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
> 
> added 1014 packages from 1012 contributors and audited 42608 packages in 6
> s
> found 0 vulnerabilities
> 
> warning: LF will be replaced by CRLF in .editorconfig.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in .gitignore.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in README.md.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in angular.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in e2e/protractor.conf.js.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in e2e/src/app.e2e-spec.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in e2e/src/app.po.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in e2e/tsconfig.e2e.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in package-lock.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in package.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/app/app-routing.module.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/app/app.component.html.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/app/app.component.spec.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/app/app.component.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/app/app.module.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/browserslist.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/environments/environment.prod.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/environments/environment.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/index.html.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/karma.conf.js.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/main.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/polyfills.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/styles.scss.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/test.ts.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/tsconfig.app.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/tsconfig.spec.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in src/tslint.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in tsconfig.json.
> The file will have its original line endings in your working directory
> warning: LF will be replaced by CRLF in tslint.json.
> The file will have its original line endings in your working directory
> 
> *** Please tell me who you are.
> 
> Run
> 
>   git config --global user.email "you@example.com"
>   git config --global user.name "Your Name"
> 
> to set your account's default identity.
> Omit --global to set the identity only in this repository.
> 
> fatal: unable to auto-detect email address (got 'DELL@DELL-PC.(none)')

### Your Environment

> Angular CLI: 7.3.8
> Node: 11.13.0
> OS: win32 x64
> Angular: 7.2.12
> ... animations, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
> 
**Package Version**
> -----------------------------------------------------------
> @angular-devkit/architect         0.13.8
> @angular-devkit/build-angular     0.13.8
> @angular-devkit/build-optimizer   0.13.8
> @angular-devkit/build-webpack     0.13.8
> @angular-devkit/core              7.3.8
> @angular-devkit/schematics        7.3.8
> @angular/cli                      7.3.8
> @ngtools/webpack                  7.3.8
> @schematics/angular               7.3.8
> @schematics/update                0.13.8
> rxjs                              6.3.3
> typescript                        3.2.4
> webpack                           4.29.0

More [Screenshots and Pastebin ](https://stackoverflow.com/questions/55611062/issue-with-running-angular-7-projects)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

See also: https://github.com/angular/angular-cli/issues/6848

Thanks

**Comment by krishna-7** [comment]
> 
> 
> This seems like a problem with your node/npm and not with Angular CLI.
> 
> Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
> 
> See also: #6848
> 
> Thanks

Hi Alan, thanks for the reply. I am not sure about this but the only time I have this issue is while trying to go with SCSS option and with angular routing. IF we choose css, sass, less, stylus it works fine and project runs but in case of scss I get the the above error. I have through the links you have provided. I reinstalled node several time and with different versions as well, but not able to resolve this issue. Any help will be greatly appreciated

**Comment by itanex** [comment]
@krishna-7 the error your getting says that NPM could not find the Python2 executable in your path variable. Simply install Python2 and allow it to update the PATH variable.

NOTE: You may have to reopen your command line for it to properly load the updated PATH variable
