### ISSUE TITLE
Add npm-install-webpack-plugin by default in CLI

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#14125]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
https://github.com/webpack-contrib/npm-install-webpack-plugin

**Comment by alan-agius4** [comment]
Hi, thanks for opening this.

The above mentioned plugin doesn't support Webpack version 4 and hence we cannot consider adding this in Angular CLI. 

Apart from that, I have big doubts that such plugin will correctly work in a TypeScript environment.
