### ISSUE TITLE
NPM Audit Failure = @angular-devkit/build-angular

### ISSUE THREAD

**Issue by Adam-Kernig** [angular/angular-cli#14138]
# 🐞 Bug report

### Command (mark with an `x`)
- [ X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
no

### Description
Up to date NG CLI, creating a new project, npm audit strikes


## 🔬 Minimal Reproduction
Up to date NG CLI, creating a new project, npm audit strikes

## 🔥 Exception or Error
<pre><code>
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.4.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @angular-devkit/build-angular [dev]                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @angular-devkit/build-angular > node-sass > node-gyp > tar   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
</code></pre>


## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.8
Node: 10.15.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.8
@angular-devkit/core         7.3.8
@angular-devkit/schematics   7.3.8
@schematics/angular          7.3.8
@schematics/update           0.13.8
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Anything else relevant?**
Nothing further

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this, however this is caused by an upstream package and will be fixed when they release a new version https://github.com/nodejs/node-gyp/issues/1714

**Comment by spp125** [comment]
I am having the same issue.

**Comment by cap-akimrey** [comment]
v4.4.8 was just released.

**Comment by chet-manley** [comment]
Looks like node-gyp already took care of it. 
https://github.com/nodejs/node-gyp/pull/1713

**Comment by Adam-Kernig** [comment]
Im guessing with it now being resolved we can expect this in the next release?

**Comment by HansITChange** [comment]
Building a new app still generates the same error

**Comment by alan-agius4** [comment]
`node-sass` are using an older version of `node-gyp`. hence we are still blocked on this.

See: https://github.com/sass/node-sass/issues/2625

**Comment by ignaciorecuerda** [comment]
This question has already been answered. Can you try this solution https://stackoverflow.com/a/55649551/10961281, it has worked for me

**Comment by Adam-Kernig** [comment]
> This question has already been answered. Can you try this solution https://stackoverflow.com/a/55649551/10961281, it has worked for me

Do NOT manually edit the lock file.

**Comment by gabimladin** [comment]
> > This question has already been answered. Can you try this solution https://stackoverflow.com/a/55649551/10961281, it has worked for me
> 
> Do NOT manually edit the lock file.

Then how should it be done?

**Comment by Adam-Kernig** [comment]
> > > This question has already been answered. Can you try this solution https://stackoverflow.com/a/55649551/10961281, it has worked for me
> > 
> > 
> > Do NOT manually edit the lock file.
> 
> Then how should it be done?

Wait till sass is updated and give the angular chaps time, it's friday (for us anyway) We aren't releasing this weekend.

The Angular guys are extremely quick at resolving issues, patience is key.

**Comment by lenichols** [comment]
+1

**Comment by cbutton01** [comment]
I am also having this issue, any news on an update?

**Comment by michalmotorola** [comment]
I also have this problem. We wait few days with merges.

**Comment by Hallight** [comment]
Any update on this?

**Comment by alan-agius4** [comment]
Hi all, node-sass have yet to fix the issue see: https://github.com/sass/node-sass/issues/2625
At this point we are blocked until they do the fix and cut a release.

**Comment by subhashkonda** [comment]
Our CI pipe lines throwing this vulnerability, so what is ETA of this Issue?

**Comment by grace-grimwood** [comment]
Check out nodejs/node-gyp#1718 for an ETA on the next node-gyp release containing a fix. At this stage, it looks like they're still debating what version number to give it. :expressionless:

**Comment by Toxicable** [comment]
https://github.com/sass/node-sass/pull/2639
node-gyp has been fixed
node-sass is bing updated: 
Once that PR is merged we can bump the node-sass version here

**Comment by jordancue** [comment]
Is it safe to use the CLI to build for production apps while we're waiting on a fix?

**Comment by pl4yradam** [comment]
Any update on this, there has been a cli update but the error is still persisting?

**Comment by MatthiasKunnen** [comment]
@pl4yradam, sass/node-sass#2639 still needs to be merged. See https://github.com/angular/angular-cli/issues/14138#issuecomment-486388458.

**Comment by pl4yradam** [comment]
@MatthiasKunnen thanks for the ref mate, I'll keep an eye out over there

**Comment by nicobytes** [comment]
any update?

**Comment by bestazad** [comment]
The solution of this question solved my problem too, but don't know how safe/recommended is it?

**Comment by STheFox** [comment]
> The solution of this question solved my problem too, but don't know how safe/recommended is it?
> https://stackoverflow.com/questions/55635378/npm-audit-arbitrary-file-overwrite/55649551#55649551

This is not the way to do it. Manually editing the package-lock.json file to fix the dependency version seems like a quick fix but it's not the right fix since the package-lock file will be overwritten when you run a `npm install` again. Guess we should wait on the devs to bump up the dependency version of node-sass and then update this package.

**Comment by pablocid** [comment]
any updates?

**Comment by pablocid** [comment]
any updates?

**Comment by IsAmrish** [comment]
any updates? cannot wait for the right solution.

**Comment by pl4yradam** [comment]
https://github.com/sass/node-sass/pull/2639

**Comment by art3miz18** [comment]
still waiting for an apropriate solution :(

**Comment by subhashkonda** [comment]
Any ETA on this as our CI builds complain about this vulnerability.

**Comment by MacGyver214** [comment]
@subhashkonda @art3miz18 @pl4yradam @IsAmrish @pablocid  I think it's safe to say if you still see the blocked tag on this issue, they are unable to execute work to fix it. Keep an eye on the fixes this work is dependent on, it's all been documented above what is needed for the Angular team to do what they need to do.

**Comment by pl4yradam** [comment]
@MacGyver214 im not sure why I have been tagged as I was providing a link to the issue?

**Comment by franciscojsr** [comment]
Hi! It's gonna be fix this issue soon? Thanks!
Angular message code errors not showing becouse this issue.

**Comment by AlanCrevon** [comment]
For those wondering why fixing this issue takes so long, have a look at https://github.com/npm/node-tar/pull/213 : they are facing a corner case where updating a library might cause more problems than leaving the security breach open.

Let’s hope someone will find a way to solve this. :)

**Comment by michel-jump** [comment]
New version of tar just has been released: 
https://github.com/npm/node-tar/issues/212#issuecomment-492463507

Node-sass: 
https://github.com/sass/node-sass/issues/2625#issuecomment-492464554

**Comment by alan-agius4** [comment]
Closing the issue as this seems to have been fixed upstream without the need to do any changes from our side.

**Comment by pl4yradam** [comment]
Confirmed. I have tried it this morning.

**Comment by franciscojsr** [comment]
Yes! I just do: `npm audit fix ` and solved!

**Comment by subhashkonda** [comment]
Npm audit fix in my local fixed all issues, but I still see in my CI build showing the tar 2.2.2 high vulnerability. Do you the issue is open or is this seems to be my CI Build specific. 
Does anyone facing the same ?

**Comment by ShahanaFarooqui** [comment]
I am also facing the same issue as subhashkonda. Vulnerabilities fixed on my local but githut still shows high vulnerability. Package-lock.json shows that "@angular-devkit/build-angular": "0.13.9" has dependendency on "node-sass": "4.12.0" which is dependent on "node-gyp": "^3.8.0". Finally this node-gyp has dependency on older version of tar ("tar": "^2.0.0"), which is showing up in CI build.

**Comment by ShahanaFarooqui** [comment]
@subhashkonda i am also facing the same issue with github. Veulnerability fixed on my local but Github still shows it vulnerable. They might need some more time to update their audit list :).

**Comment by xaviergxf** [comment]
@alan-agius4 do you know when the dependency will be updated, and a new version of @angular-devkit/build-angular will be released on version 7 (stable)?

**Comment by salah3x** [comment]
@xaviergxf, I don't think they need a new release for this issue since it's been fixed upstream.

**Comment by alan-agius4** [comment]
Indeed no release is needed from our side.

**Comment by weidenhaus** [comment]
*27 May 2019* - Still facing the same issue when creating new Angular project via CLI - ___12___ high vulnerabilities found.

The following solved it for me:
```bash
npm i -D node-sass node-pre-gyp node-gyp tar
```

**Comment by JoaoPortella** [comment]
Hi @weidenhaus !
Where to apply npm command? I'm trying in my project root folder and still facing 12 high vulnerabilities...
Thank you!

**Comment by subhashkonda** [comment]
I still have this same issue in CI Builds but in local it is all fine npm audit gives 0 vulnerabilities, So what can be done here???
