### ISSUE TITLE
ng build ---prod with "optimization: true" throws script error

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#14135]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
```

### Description

While running application using below command  with **"optimization: true"**

> ng build ---prod

**It throws below error:**

`    <ejs-listview id='listview_template' #listviewInstance [dataSource]='dataSource' [cssClass]='cssClass'
[headerTitle]='headerTitle' (actionComplete)='onActionComplete($event)' [showHeader]='true'>

    <ng-template #template let-dataSource="">
    <div class="{{dataSource.category ? 'clearfix desc e-list-wrapper e-list-multi-line e-list-avatar' : 'clearfix e-list-wrapper e-list-multi-line e-list-avatar'}}">
        <span *ngIf="dataSource.imgSrc !== ''" class="e-avatar e-avatar-{{dataSource.imgSrc}}"></span>
        <span class="e-list-item-header">{{dataSource.title}} </span>
        <span class="e-list-content e-text-overflow" [innerHTML]="dataSource.description"></span>
        <div id="list-logo" *ngIf="dataSource.timeStamp !== ''">
            <span class="bookmark"></span>
            <span class="comments"></span>
            <span class="share"></span>
        </div>
        <div class="timeStamp" *ngIf="dataSource.timeStamp !== ''">{{dataSource.timeStamp}}</div>
    </div>
</ng-template>
</ejs-listview>
 `

## 🔥 Exception or Error

`main.9c96b5ab969035321496.js:1 ERROR TypeError: Cannot read property 'viewContainerRef' of undefined
    at main.9c96b5ab969035321496.js:1
    at main.9c96b5ab969035321496.js:1
    at y (main.9c96b5ab969035321496.js:1)
    at o (main.9c96b5ab969035321496.js:1)
    at s (main.9c96b5ab969035321496.js:1)
    at Object.e.createList (main.9c96b5ab969035321496.js:1)
    at t.createList (main.9c96b5ab969035321496.js:1)
    at t.renderList (main.9c96b5ab969035321496.js:1)
    at t.setLocalData (main.9c96b5ab969035321496.js:1)
    at t.render (main.9c96b5ab969035321496.js:1)`

## 🌍 Your Environment
"@angular/cli": "~7.0.3",

**Comment by kumaresan-subramani** [comment]
Any update reg this?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by kumaresan-subramani** [comment]
HI I don't know what further information do you need?

While running my application with my package[generated by ng-packgr] working fine in dev mode

But not runnning  in prod mode

if i disable optimization:false and run in prod mode working fine
