### ISSUE TITLE
Cannot get rid of SASS even if I choose plain CSS instead

### ISSUE THREAD

**Issue by szellcsaba-ge** [angular/angular-cli#14133]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description

Node-sass getting installed however not chosen to be used.

## 🔬 Minimal Reproduction

ng new sampleProject
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? **CSS**

## 🌍 Your Environment
<pre><code>Angular CLI: 7.3.8
Node: 10.9.0
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

Node-sass has several security issues and we need to get rid of it, but cannot exclude from a base angular project.

Windows 10 (updated).

```
C:\project>ng new sass-test-wo
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE sass-test-wo/angular.json (3861 bytes)
  ...
CREATE sass-test-wo/e2e/src/app.po.ts (251 bytes)

> node-sass@4.11.0 install C:\project\sass-test-wo\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\Users\szellcs\AppData\Roaming\npm-cache\node-sass\4.11.0\win32-x64-64_binding.node

> node-sass@4.11.0 postinstall C:\project\sass-test-wo\node_modules\node-sass
> node scripts/build.js

Binary found at C:\project\sass-test-wo\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1075 packages from 1026 contributors and audited 42608 packages in 131.486s
found 0 vulnerabilities

    Successfully initialized git.
```

Why? I've chosen not to use SCSS, but CSS.

**Comment by szellcsaba-ge** [comment]
```npm install --no-optional``` doesn't help.

See also:
https://github.com/angular/angular-cli/issues/13075#issuecomment-481732959

**Comment by szellcsaba-ge** [comment]
```ng new sass-test-wo --style css``` also doesn't help.

**Comment by alan-agius4** [comment]
Hi, thanks for opening this. 

The packages will always be installed irrespective if you choose something other than SCSS as your style format. unless you use it or not. However `node-sass` has been removed in version 8 in favour of `sass` 

See: https://github.com/angular/angular-cli/pull/13950

The issue that you are experiencing seems to be related to this NPM issues https://github.com/npm/npm/issues/17633

**Comment by alan-agius4** [comment]
Closing as this is obsolete in version 8 and the security issue is being tracked here: https://github.com/angular/angular-cli/issues/14138
