### ISSUE TITLE
node_modules not get root index file

### ISSUE THREAD

**Issue by pala1993** [angular/angular-cli#14142]
Failed to load resource: the server responded with a status of 404 (Not Found) jquery.min.js

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>ImageZoom</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
 <script src="../node_modules/jquery/dist/jquery.min.js"></script>
</body>
</html>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
