### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jbeckton** [angular/angular-cli#1415]
I just read that some major changes are coming to the Angular CLI involving Webpack rather than Broccoli. How will this effect the apps we are building currently with SystemJs? 

I have some large projects in play with multiple teams standardizing this CLI and if there are breaking changes coming I guess I need to know now. The roadmap page does not mention anything.

**Comment by filipesilva** [comment]
We'll be providing documentation on how to upgrade a project for the webpack beta. The feedback that we've gotten so far is that the transition is pretty seamless: mostly running `ng init` to get new files and deleting a couple of old ones manually.

**Comment by jbeckton** [comment]
Is there an Alpha release available I can try out?

**Comment by filipesilva** [comment]
Can't say there is, but there is a `webpack` branch at the moment and some people are trying it out in https://github.com/angular/angular-cli/issues/1356.

Caveats apply: work in progress, everything might change, etc. That's the best I can give you for now.

**Comment by tapas4java** [comment]
@jbeckton I have played arround with webpack branch and I can say It works very well and I really like it. The main thing I like about it is the less configuration(mainly config related to systemjs gone) and everything coming up together so nicely.

**Comment by jbeckton** [comment]
Ok sounds reasonable. I also heard that the new Webpack based CLI will have support for creating Angular 2 component libraries, is this true? We use Component libraries to share code across teams and projects via NPM. Currently I am using Gulp tooling for this but would like to stick with one tool for both SPA and Library development.

**Comment by filipesilva** [comment]
I am not aware of lib functionality in the webpack branch, no. That functionality is planned but not part of the feature set of the webpack branch.

**Comment by jbeckton** [comment]
Ok thanks, I can stick with my Gulp tooling for now for Libraries
