### ISSUE TITLE
ng generate doesn't add the component to my module anymore

### ISSUE THREAD

**Issue by RafaelKr** [angular/angular-cli#14157]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, I think it's related to `@angular-devkit/schematics` version `7.3.x`. Version `7.2.4` is working fine. I currently don't have the time to find the exact version at which the problem starts.

### Description
I'm generating my components with the `ng generate` command. First I'm creating a module, then the component. When using version `7.2.4` the component is automatically added to the modules declarations and exports. This doesn't work with `7.3.x` anymore. I also tried to use the `--module` parameter, but I couldn't find a path where it was not saying `File my-component.module does not exist.` (or with a path in front of `my-component.module`).

## 🔬 Minimal Reproduction
```bash
ng g module components/my-component --lint-fix
ng g component components/my-component --export --change-detection OnPush --lint-fix
```

## 🌍 Your Environment
<pre><code>Angular CLI: 7.2.4
Node: 11.9.0
OS: linux x64
Angular: 7.2.13
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.2.4
@ngtools/webpack                  7.3.8
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0
</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.


```
λ ng g module components/my-component --lint-fix
CREATE src/app/components/my-component/my-component.module.ts (195 bytes)

λ ng g component components/my-component --export --change-detection OnPush --lint-fix
CREATE src/app/components/my-component/my-component.component.html (31 bytes)
CREATE src/app/components/my-component/my-component.component.spec.ts (664 bytes)
CREATE src/app/components/my-component/my-component.component.ts (368 bytes)
CREATE src/app/components/my-component/my-component.component.css (0 bytes)
UPDATE src/app/components/my-component/my-component.module.ts (315 bytes)
```
