### ISSUE TITLE
ERROR in : Unexpected value 'null' declared by the module 'AppModule' in 'src/app/app.module.ts'

### ISSUE THREAD

**Issue by amit-techpro** [angular/angular-cli#14150]
**This is happening while creating a production build. I migrated an Angular 5 project to Angular 7. Project is running file in local development server. But I am not able to create production build. 
This project in NOT in lazy load structure.**
Does anyone know about this issue.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
