### ISSUE TITLE
SSR Only renders first page

### ISSUE THREAD

**Issue by mikelsulanjaku** [angular/angular-cli#14152]
Hello,

I have an angular project that contains a Shell module which in turn has a template page with a header, a footer and a main content are with a router-outlet which allows me to load any page within that template. That means I have one router-outlet at the app level and another one at the shell level. I did follow the instructions on the angular universal page and it did successfully generate all the files required for server side rendering. I have a main route also for each extra module I have children routes using the shell template.

**app routing at the app level:**

const routes: Routes = [
  // Fallback when no prior route is matched
  {
    path: '**',
    redirectTo: '',
    pathMatch: 'full'
  }
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, enableTracing:false })
  ],
  exports: [RouterModule],
  providers: []
})
export class AppRoutingModule {}

**At the module level:**

const routes: Routes = [
  Shell.childRoutes([
    {
      path: '',
      component: CheckoutComponent
    },
    {
      path: 'checkout',
      component: CheckoutComponent
    }
  ])
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class CheckoutRoutingModule {}

Shell Service:

_export class Shell {
  /**
   * Creates routes using the shell component and authentication.
   * @param routes The routes to add.
   * @return The new route using shell as the base.
   */
  static childRoutes(routes: Routes): Route {
    return {
      path: '',
      component: ShellComponent,
      children: routes,
      canActivate: [AuthenticationGuard],

      // Reuse ShellComponent instance when navigating between child views
      data: { reuse: true }
    };
  }
}_

**Shell component:**

<header></header>
<div class="main-body">
  <main><router-outlet></router-outlet></main>
</div>
<footer></footer>

Everything is good except that after building and serving the project, when viewing the source on the first page everything is nicely generated in html however, any other route, does render on the browser side but when viewing the source I always see the content of the first page.

How do I make sure that every child route generates html accordingly?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
