### ISSUE TITLE
How would i be able to exclude the public folder in build? and specify specific folder for assets. 

### ISSUE THREAD

**Issue by arvenjadeaguilar** [angular/angular-cli#1416]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu Linux

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.
4.2.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
in our system. the public folder is not available since its been use in the other view of a different application. How can i be able to specify another folder for assets or exclude the public folder in dist.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
There is no log. since it builds successfully but the problem is that it will also added those codes that are not been used in dist which been placed in public folder

5. Mention any other details that might be useful.
> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
There's no such option now, but if you can do a PR we're happy to review it!
