### ISSUE TITLE
Support other directories than `./files` to be templated by mergeWith/apply devkit utilities

### ISSUE THREAD

**Issue by hadrien-toma** [angular/angular-cli#14178]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [?] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
For the moment, I can only templates files under the `./files` directory (`.` being my schematic directory).

### Describe the solution you'd like
I would like to be able to give a template path to my schematic and then fetch/fill these templates inside the schematic.

### Describe alternatives you've considered
Not found any :cry:...

**Comment by alan-agius4** [comment]
Hi @hadrien-toma, I am not quite understanding the issue being reporting here.

The `./files` can be named anything, example something the below should work
```
apply(url('../abc'), [
      apply({
        foo: 'bar',
      }),
      move(),
    ]);
```

**Comment by hadrien-toma** [comment]
@alan-agius4 I tried but it didn't work, with no errors. I close the issue and will create another one with more environment details in case of failure. Thank you for your confirmation that it should work!
