### ISSUE TITLE
pass contents of json file for ng generate from command line

### ISSUE THREAD

**Issue by ruudyroon** [angular/angular-cli#14171]
I'm working with angular schematics, here's what I'm trying to achieve. 

I've a config object that i want to pass from a json file instead of passing directly as string

ng g ang-ang-form --name='ang-schematics' --config=data.json

here I want the config to be passed from data.json, is this possible to do so with cli?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
