### ISSUE TITLE
Build issue during Karma Test execution => index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property

### ISSUE THREAD

**Issue by arun-mano** [angular/angular-cli#14179]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

The ng test command fails with Build issue saying the index.ts is missing from the TypeScript compilation.

I have a App Module and Common Module for some common functions created with Angular 7. Both of these modules are linked through "npm link"

The ng build and ng serve commands are working fine after adding all necessary components to the tsConfig.app.json

Added the same index.ts from common components into the tsConfig.spec.json as well, but the **ng test** command fails in this scenario with "index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property" error message for the Component where I have imported some of the files Common Module. 

 And more over none of the Test cases are getting Executed, If I alter/edit the tsConfig.spec.json file and save it which refreshes build and starts executing the Test Cases as expected.

**Note** : I found another issue nearly similar to my cases - https://github.com/angular/angular-cli/issues/12657 wherein it was mentioned that the fix was available in "@angular-devkit/build-angular": "0.10.3" version but the version I used is "@angular-devkit/build-angular": "0.13.8",

**Error Details**
ERROR in ../../../index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: ......\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (...\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_com
piler_plugin.ts:1029:15)
    at plugin.done.then (.....\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ ./src/app/app.component.ts 4:0-65 21:15-22
 @ ./src/app/app.component.spec.ts
 @ ./src sync \.spec\.ts$
 @ ./src/test.ts
 
**tsConfig.spec.json:**
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "include": [
    "**/*.d.ts",
    "**/*.ts",
    "../node_modules/.../.../index.ts",
  ]
}

**Libraries used are :**
"dependencies": {
    "@angular/animations": "7.2.0",
    "@angular/common": "7.2.0",
    "@angular/compiler": "7.2.0",
    "@angular/core": "7.2.0",
    "@angular/forms": "7.2.0",
    "@angular/platform-browser": "7.2.0",
    "@angular/platform-browser-dynamic": "7.2.0",
    "@angular/router": "7.2.0",
    "@ng-bootstrap/ng-bootstrap": "4.1",
    "@ngrx/effects": "7.3",
    "@ngrx/store": "7.3",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/i18n-polyfill": "1.0.0",
    "bootstrap": "4.3",
    "core-js": "2.5.4",
    "hammerjs": "2.0.8",
    "ngx-logger": "3.3.12",
    "reselect": "3.0.1",
    "rxjs": "6.3.3",
    "rxjs-compat": "6.2.2",
    "tslib": "1.9.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.13.8",
    "@angular/cli": "7.3.7",
    "@angular/compiler-cli": "7.2.0",
    "@angular/language-service": "7.2.0",
    "@types/hammerjs": "2.0.35",
    "@types/jasmine": "2.8.8",
    "@types/jasminewd2": "2.0.3",
    "@types/mocha": "5.2.6",
    "@types/node": "8.9.4",
    "codelyzer": "4.5.0",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.0.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "1.1.2",
    "karma-jasmine-html-reporter": "0.2.2",
    "ngrx-store-freeze": "0.2.4",
    "node-sass": "4.11.0",
    "protractor": "5.4.0",
    "ts-node": "7.0.0",
    "tslint": "5.11.0",
    "typescript": "3.2.2"
  }

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

The path in your include file seems to be incorrect `"../node_modules/.../.../index.ts"`. It should be something along `"../node_modules/my-lib/**/*.ts".`

If the problem persists, can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by arun-mano** [comment]
Hi , I have created a Repo in Github 
https://github.com/arun-mano/commonmodule

Since my issue is replicable only for scenario where- npm link involves, I have created a .bat file which consolidates all steps needed for replicating

Please find Steps to reproduce:
1. Download the project in https://github.com/arun-mano/commonmodule
2. run the npmLink_install_test.bat (does npm link, npm install and ng test in order)

you would see below error :
![image](https://user-images.githubusercontent.com/28147306/56280338-9a308280-6127-11e9-84f5-8c4923810562.png)

3. Edit the JSON content in appmodule/src/tsconfig.spec.json and save the file then the Karma Test cases are running fine

**Comment by alan-agius4** [comment]
Hi, there are a couple of issues here.

1. Since you are using symlinks you need to enable `preserve-symlinks` either via the command line or angular.json `ng test --preserve-symlinks`
2. You need to include all external files in the compilation. Ie: in the `include` option you need to change `"../node_modules/commonmodule/index.ts",` to `"../node_modules/commonmodule/**/*.ts",`
