### ISSUE TITLE
Do not crush on missing configuration

### ISSUE THREAD

**Issue by waterplea** [angular/angular-cli#14184]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I have a workspace with multiple libraries and I would like to create a test config only for some of them, so I can use `ng test -c=my-config` to test only those libraries that implement this config in `angular.json`. However it crashes on those libraries that have "test" architect but missing this particular configuration.

### Describe the solution you'd like
Just skip those libraries

### Describe alternatives you've considered
Perhaps I'm missing something, maybe there is another way to run tests in pre-configured bunches that are library independent?

**Comment by alan-agius4** [comment]
Thanks for this feature request. However, at the moment this is not on the roadmap. Let's reconsider in the future if things change.
