### ISSUE TITLE
Missing App specific barrels 'shared'

### ISSUE THREAD

**Issue by francisoud** [angular/angular-cli#1418]
Was initially created in https://github.com/angular/angular.io/issues/1896 but is an angular-cli error.

I create a sample project from scratch to reproduce the problem:  https://github.com/francisoud/angular.io.issue.1896
I have same problem during runtime (in console log) in `contract-list.component.ts` and for test (as describe above).

You were right the problem is in [system-config.ts](https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/system-config.ts) there are 2 lines that are missing and should have been added during `ng generate` (see command line below)
```
// App specific barrels.
  'app',
  'app/shared',
  'app/contracts',
  **'app/contracts/shared',**
  'app/contracts/contract-list',
  **'app/contracts/contract-list/shared'**
```

I think it's a bug in angular-cli 
I think something is missing during `ng generate component ...` somewhere near this line:
https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/component/index.js#L117

### Errors
[Error at runtime](https://github.com/francisoud/angular.io.issue.1896/blob/master/ERROR_LOG_RUNTIME.md)
[Error in tests](https://github.com/francisoud/angular.io.issue.1896/blob/master/ERROR_LOG_TEST.md)

### index.ts
It seems to me all index.ts are referencing the correct component:
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/shared/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/contracts/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/contracts/contract-list/index.ts
https://github.com/francisoud/angular.io.issue.1896/blob/bug/src/app/contracts/contract-list/shared/index.ts

And they where updated when I created I used `ng generate ...`

### ng generate
```
C:\tmp\myapp>ng generate component contracts
installing component
  create src\app\contracts\contracts.component.css
  create src\app\contracts\contracts.component.html
  create src\app\contracts\contracts.component.spec.ts
  create src\app\contracts\contracts.component.ts
  create src\app\contracts\index.ts
  create src\app\contracts\shared\index.ts

  
C:\tmp\myapp>ng generate component contracts/contract-list
installing component
  create src\app\contracts\contract-list\contract-list.component.css
  create src\app\contracts\contract-list\contract-list.component.html
  create src\app\contracts\contract-list\contract-list.component.spec.ts
  create src\app\contracts\contract-list\contract-list.component.ts
  create src\app\contracts\contract-list\index.ts
  create src\app\contracts\contract-list\shared\index.ts

C:\tmp\myapp>ng generate service contracts/shared/contract
installing service
  create src\app\contracts\shared\contract.service.spec.ts
  create src\app\contracts\shared\contract.service.ts
  
C:\tmp\myapp>tree src
C:\TMP\MYAPP\SRC
└───app
    ├───contracts
    │   ├───contract-list
    │   │   └───shared
    │   └───shared
    └───shared
```

### Sample project
This version with the 2 issues (runtime and test):
https://github.com/francisoud/angular.io.issue.1896/tree/bug

The branch 'workaround': 
https://github.com/francisoud/angular.io.issue.1896/tree/workaround ([diff](https://github.com/francisoud/angular.io.issue.1896/commit/5caf258bdc802a372d0d3150fbcd68615cdec021))

The branch 'fix': 
https://github.com/francisoud/angular.io.issue.1896/tree/fix

### Version
```
C:\tmp\myapp>ng --version
angular-cli: 1.0.0-beta.8
node: 6.2.1
os: win32 x64
```

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455. SystemJS is not used anymore after that PR, so this issue shouldn't happen.

**Comment by rameshyala** [comment]
i am added to three model files to my componnent....one file is not loaded like below show example

import {
Company,
Address, 
Communication
} from '../models/index';

the company is not loaded to my component,i am add it on model/index also.and one more is in root config component this import barrels not working.
