### ISSUE TITLE
ng add --registry=<registryUrl>

### ISSUE THREAD

**Issue by dherges** [angular/angular-cli#14189]
# 🚀 Feature request

### Command (mark with an `x`)

```bash
$ ng add --registry=http://localhost:4873 @foo/bar
```

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

`ng update --registry=<registry>` allows to [update packages from private registry](https://angular.io/cli/update).

However, `ng add` offers no capability to add a package from a private registry. The current workaround is to manually create a `.npmrc` file in the CLI workspace root, adding the registry configuration there. 

### Describe the solution you'd like

- `fetchPackageManifest` and `fetchPackageMetadata` already have option for registry
  - https://github.com/angular/angular-cli/blob/fedda409ed50481d0b295dfd850ba49afbdc05e6/packages/angular/cli/utilities/package-metadata.ts#L210
  - https://github.com/angular/angular-cli/blob/fedda409ed50481d0b295dfd850ba49afbdc05e6/packages/angular/cli/utilities/package-metadata.ts#L160
- add `--registry` argument to ng add command
  - https://github.com/angular/angular-cli/blob/fedda409ed50481d0b295dfd850ba49afbdc05e6/packages/angular/cli/commands/add-impl.ts#L30
- pass `--registry` arguments to install arguments
  - https://github.com/angular/angular-cli/blob/fedda409ed50481d0b295dfd850ba49afbdc05e6/packages/angular/cli/tasks/npm-install.ts#L56

### Describe alternatives you've considered

See above: `.npmrc` file.

**Comment by piraces** [comment]
New contributor here! I would like to contribute on this if you don't mind 😄
