### ISSUE TITLE
Simple bug: Can't resolve '\app-test\src\styles.sass' in '\app-test'

### ISSUE THREAD

**Issue by DmitriyIvanko** [angular/angular-cli#14200]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ x ] new
```

### Description

 
When creating a new project, select the option "Sass [http://sass-lang.com]". Trying to build a project: "ng build --prod",
An error occurs: "Error: Can't resolve '\app-test\src\styles.sass' in '\app-test'"
My opinion it is need to replace angular.json > line 30 > "src/styles.sass" to "src/styles.scss"

## 🔬 Minimal Reproduction

Simple steps to reproduce this bug.
1) ng new test-app
2) Would you like to add Angular routing? Yes
3) Which stylesheet format would you like to use? Sass   [ http://sass-lang.com ]
4) ng build --prod
5) Error: Module not found: Error: Can't resolve 'C:\Projects\demo\app-test\src\styles.sass' in 'C:\Projects\demo\app-test'

## 🔥 Exception or Error
<pre><code>

ERROR in multi ./src/styles.sass
Module not found: Error: Can't resolve 'C:\Projects\demo\app-test\src\styles.sass' in 'C:\Projects\demo\app-test'
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.6
Node: 10.15.3
OS: win32 x64
Angular: 7.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cli                      7.3.6
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, can you try to update your global cli and try again? As this should have been solved some time ago.


```
npm i @angular/cli -g
```

And try to generate the application again.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
