### ISSUE TITLE
Add experimentalImportFactories when migrating to loadChildren import syntax

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#14218]
The https://github.com/angular/angular-cli/pull/14181 migration also needs to add `"experimentalImportFactories": true` to `angular.json` (https://github.com/angular/angular-cli/pull/13948) to make the import syntax supported in VE. 

The tsconfig file should also be updated to use `"module": "esnext"`, and a e2e test should be added to test the update works and an app with lazy routes will be updated and runs properly.

**Comment by filipesilva** [comment]
Part of this is done in https://github.com/angular/angular-cli/pull/14222

**Comment by alexeagle** [comment]
We should add this in the same migration with fix-lazy-routes so if we drop that feature from RC, we also drop the addition of this "experimental" flag

**Comment by alexeagle** [comment]
Don't need this one if we do #14231
