### ISSUE TITLE
generate classes and export it as a default 

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular-cli#14223]
when running the following cmd:
`> ng g class test `

the generated class is
`export default class{..}`
instead of
`export class TestClass{}`
so it is more convenient when importing it
or at least add an option to the command
`> ng g class test --default-export=true `
also applied to components and other ng elements

**Comment by alan-agius4** [comment]
Hi thanks for opening this. 

The AOT compiler doesn't handle export default in some cases which means using `export default` will break the compilation,

See: https://github.com/angular/angular/issues/11402

Let's re-visit this when the compiler has full support for `export default` 

Thanks.
