### ISSUE TITLE
After ng build --prod component name getting changed

### ISSUE THREAD

**Issue by aaqib90** [angular/angular-cli#14224]
`ng build --prod` change the name of Angular component inside chunk file. Is there any way to produce original name of component inside chunk file?

i have below dependencies in my project
    

> "@angular/animations": "^7.1.4",
>     "@angular/cdk": "^7.2.0",
>     "@angular/common": "~7.1.0",
>     "@angular/compiler": "~7.1.0",
>     "@angular/core": "~7.1.0",

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
