### ISSUE TITLE
Does not respect the version of typescript specified in project.json

### ISSUE THREAD

**Issue by matthewdaniel** [angular/angular-cli#1424]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
λ ng --version
(node:18256) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.9
node: 6.3.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
npm install --save-dev typescript@beta
add the following line to a file in app
let foo: string | null = null;
ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.
  c:/Projects/Core/PortalApp/tmp/broccoli_type_script_compiler-input_base_path-gWUfhjh0.tmp/0/src/app/services/edit-list.service.ts (32, 46): Type expected.

5. Mention any other details that might be useful.
it is obviously compiling with 1.8 since the error that you see "type expected" is the error my ide gave me until i made it use a path for ts 2.0 beta.

**Comment by matthewdaniel** [comment]
as a work around I am able to cp the node_modules/typescript into node_modules/angular-cli/node_modules/typescript to get the project to build

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455. Local TS is now used.
