### ISSUE TITLE
Warning occurs when I install the "@angular-devkit/build-angular" latest version 0.13.8

### ISSUE THREAD

**Issue by NikitaPooja** [angular/angular-cli#14243]
WARNING in ./src/assets/scss/style.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/style.scss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(4297:3) end value has mixed support, consider using flex-end instead

WARNING in ./src/assets/scss/style.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/assets/scss/style.scss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(4302:3) end value has mixed support, consider using flex-end instead

Thank you!

**Comment by alan-agius4** [comment]
Closing as it doesn't follow the issue template.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by deepak5627** [comment]
provide exact answer plz , m also got struck in the same problem
