### ISSUE TITLE
SignalR Message Pack Client Library not running in browser when using Angular Cli

### ISSUE THREAD

**Issue by QuinntyneBrown** [angular/angular-cli#14253]
After importing MessagePackHubProtocol from @aspnet/signalr-protocol-msgpack inside of an Angular app using the Angular cli, the application will no longer run in the browser.

You will see the following exception in the console.

![image](https://user-images.githubusercontent.com/1749159/56602015-8757fb00-65ca-11e9-97a6-14e22f7ab75d.png)

### Steps to reproduce the behavior:

Clone and run the following app:
https://github.com/QuinntyneBrown/ng-signalr-protocol-msgpack-issue

or 

1. Create an angular app using the angular cli
2. npm install @aspnet/signalr and @aspnet/signalr-protocol-msgpack
3. In the app component, import HubConnectionBuilder from @aspnet/signalr
4. In the app component, import MessagePackHubProtocolfrom @aspnet/signalr-protocol-msgpack
5. In the app component, add a method called ngOnInit
6. Inside the ngOnInit method, add the following code

    var connection = new HubConnectionBuilder()
    .withUrl("")
    .withHubProtocol(new MessagePackHubProtocol())
    .build();
  
7. run the app with the console open, and you should see the error. The UI will be blank.

### Expected behavior
You should see the standard angular cli default page.

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/angular/angular-cli/issues/8160#issuecomment-386153833

Thanks,

**Comment by QuinntyneBrown** [comment]
Thanks @alan-agius4 

I added the following line to the bottom of polyfills.ts

(window as any).global = window;

I'm getting the following error when I run the app.

![image](https://user-images.githubusercontent.com/1749159/56654058-19a8df00-665d-11e9-9acc-466320db7099.png)

Should I create another issue?

**Comment by alan-agius4** [comment]
Related to the original issue.

See from more context: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814
