### ISSUE TITLE
`tree.commitUpdate` fails after `tree.rename` in real projects, but not in unit tests

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#14255]
While testing the `@angular/cli@beta.17` update we noticed that `tree.commitUpdate` fails after `tree.rename` in real projects, but not in unit tests, and worked around it in https://github.com/angular/angular-cli/pull/14252.

We should circle back and address this problem by reproducing it in isolation and fixing it.

**Comment by dgp1130** [comment]
@filipesilva, is this still an open issue? Not sure there's enough info here to reproduce now. Can we close this, or is there more to do here?

**Comment by filipesilva** [comment]
If the problem still exists, it should be reproducible by using `rename` instead of `create`+`delete` as it was in the diff before https://github.com/angular/angular-cli/pull/14252/files. It didn't happen on tests though, so the migration should be ran manually on a real project.
