### ISSUE TITLE
Running ng test --code-coverage --watch=false but the tests are not running and doesn't create Lcov.info reports file

### ISSUE THREAD

**Issue by 199219921992** [angular/angular-cli#14279]
ng version- 7.3.8

Background- I am running unit test for angular project and collecting the generated unit tests results and publishing them on sonarqube under codecoverage section.

I was able to run ng test --code-coverage which runs the unit tests and doesn't close the Karma browser after the run, which keeps the process active which is causing timeout issue with build.

Found a workaround to add the switch --watch=false and the command which i run is now 'ng test --code-coverage --watch=false'.

Above command doesn't run the test and not creating any unit test coverage results.

Let me know if you need any more information.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

```
 ng test --code-coverage --watch=false
 11% building 10/10 modules 0 active26 04 2019 10:58:20.474:INFO [karma-server]: Karma v4.0.1 server started at http://0.0.0.0:9876/
26 04 2019 10:58:20.483:INFO [launcher]: Launching browsers Chrome with concurrency unlimited                                                                                                              11% building 11/11 modules 0 active26 04 2019 10:58:20.507:INFO [launcher]: Starting browser Chrome                                                                                                                                          26 04 2019 10:58:26.293:INFO [Chrome 73.0.3683 (Windows 10.0.0)]: Connected on socket kCfs22R72lLz4Vo4AAAA with id 84627181
Chrome 73.0.3683 (Windows 10.0.0): Executed 3 of 3 SUCCESS (0.144 secs / 0.188 secs)
TOTAL: 3 SUCCESS

=============================== Coverage summary ===============================
Statements   : 100% ( 7/7 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 1/1 )
Lines        : 100% ( 6/6 )
================================================================================
TOTAL: 3 SUCCESS
TOTAL: 3 SUCCESS
```

```
$ ls coverage\seven-cc-test\lcov.info
'coverage\seven-cc-test\lcov.info'
```

**Comment by 199219921992** [comment]
@alan-agius4 - Below output is observed on run, it opens up browser and closes immediately without running tests.

D:\TFSBuildAgent\Workspace\2\s\Development\WebGUI\Frontend>**ng test --code-coverage --watch=false**
********************************Output*****************************
Your global Angular CLI version (7.3.8) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
 10% building modules 1/1 modules 0 active(node:1712) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
29 04 2019 05:19:53.594:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
29 04 2019 05:19:53.600:INFO [launcher]: Launching browser Chrome with unlimited concurrency
29 04 2019 05:19:53.606:INFO [launcher]: Starting browser Chrome                                                              29 04 2019 05:20:41.905:INFO [Chrome 73.0.3683 (Windows 10.0.0)]: Connected on socket w7t3N7QlINk2u9drAAAA with id 2154554
29 04 2019 05:20:51.909:WARN [Chrome 73.0.3683 (Windows 10.0.0)]: Disconnected (1 times), because no message in 10000 ms.
Chrome 73.0.3683 (Windows 10.0.0) ERROR
  Disconnected, because no message in 10000 ms.
Chrome 73.0.3683 (Windows 10.0.0) ERROR
  Disconnected, because no message in 10000 ms.

Chrome 73.0.3683 (Windows 10.0.0) ERROR
  Disconnected, because no message in 10000 ms.
Chrome 73.0.3683 (Windows 10.0.0) ERROR
  Disconnected, because no message in 10000 ms.

**Comment by 199219921992** [comment]
@alan-agius4  Got the fix!
