### ISSUE TITLE
I always get JavaScript heap out of memory even it 32G

### ISSUE THREAD

**Issue by sokhomhuy** [angular/angular-cli#14275]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewUninitializedFixedArray
 5: v8::internal::WasmDebugInfo::SetupForTesting
 6: v8::internal::interpreter::BytecodeArrayRandomIterator::UpdateOffsetFromIndex
 7: 0000005FA37043C1

I always get this error when i am run development even i change the node cmd to max of memory 32G it still the same sometime it could run sometime cannot run it. 

node --max_old_space_size=32768 node_modules/@angular/cli/bin/ng build client --prod

please help me.

**Comment by filipesilva** [comment]
Heya, do you have a reproduction I can look at? If you can only share it privately that's ok too.
