### ISSUE TITLE
File replacements using `ng serve`

### ISSUE THREAD

**Issue by serlingpa** [angular/angular-cli#14272]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I am trying to swap my `environment.ts` with another file when using `ng serve`, but it seems this is only possible with build configurations, and not serve configurations. I would like to do this so that I can use different languages using the Angular internationalization features while debugging.

I have something like this in my `angular.json`:

```
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "browserTarget": "MyProject:build"
  },
  "configurations": {
    "production": {
      "browserTarget": "MyProject:build:production"
    },
    "fr": {
      "fileReplacements": [
        {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.fr.ts"
        }
      ],
      "browserTarget": "SupplierPortal:build:fr"
    }
}
```
but the compiler complains:
> Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(fileReplacements).

### Describe the solution you'd like
I would like to be able to swap out `environment.ts` when using `ng serve`

### Describe alternatives you've considered
I have considered interrogating the URL in `main.ts` to grab the base href, but this is quite smelly.

**Comment by filipesilva** [comment]
The way to do this is to add a build configuration with the replacement you want, and then add change the `browserTarget` on serve to use that configuration. You can do that with a flag, or with a configuration option.
