### ISSUE TITLE
Tests fail with Angularfire

### ISSUE THREAD

**Issue by chrste90** [angular/angular-cli#14280]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Maybe

### Description

 
When i run ng test i get `Executed 0 of 0 ERROR`

## 🔬 Minimal Reproduction

```
ng new TestApp --defaults
cd TestApp/
npm install --save @angular/fire firebase
```

Replace content of `app.component.ts` with
```
import { Component } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/auth';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'TestApp';

  constructor(private afAuth: AngularFireAuth) {
  }
}
```

and run `ng test`

## 🔥 Exception or Error
<pre><code>

Executed 0 of 0 ERROR 
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.0-rc.0
Node: 10.15.2
OS: darwin x64
Angular: 8.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.0
@angular-devkit/build-angular     0.800.0-rc.0
@angular-devkit/build-optimizer   0.800.0-rc.0
@angular-devkit/build-webpack     0.800.0-rc.0
@angular-devkit/core              8.0.0-rc.0
@angular-devkit/schematics        8.0.0-rc.0
@angular/fire                     5.1.2
@ngtools/webpack                  8.0.0-rc.0
@schematics/angular               8.0.0-rc.0
@schematics/update                0.800.0-rc.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
I think we have some errors being swallowed somewhere.

**Comment by filipesilva** [comment]
Interesting, as far as I can tell something breaks mysteriously as soon as `AngularFireAuth` is included in the compilation. It's enough to add this to `app.component.ts` for instance:

```
import { AngularFireAuth } from '@angular/fire/auth';
console.log(AngularFireAuth)
```

It doesn't affect `ng serve` though. So it's probably not related to the compilation proper, but rather something about the karma/jasmine runtime.

**Comment by filipesilva** [comment]
So this is a fun one. The above is enough to see it on a 8 RC project. 

But not on a new 7.0 project. Not even when the 7.0 project is updated to 8. In fact, it's not reproducible even after replacing every file in the 7 project with the 8 repro.

At that point removing the package-lock.json and node modules, then reinstalling will indeed reproduce it.

So it seems that it's something on an indirect loose, or hoisted, dependency.

**Comment by chrste90** [comment]
Ah good to know, this explains why the error occured only last week and not directly after updating to CLI 8.

Any idea how we can find the root cause for this strange behaviour?

**Comment by filipesilva** [comment]
I don't have a super good way to figure this out to be honest. Mostly trying to change dependencies and isolate where the problem came up.

**Comment by filipesilva** [comment]
It seems to happen with `firebase@>5.10.0`. Pinning to `firebase@5.9.4` is a good workaround for now.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/14334 should fix it. It seems like firebase might be doing something with polyfills starting on that version, and we were erroneously splitting polyfill chunks as well.

**Comment by chrste90** [comment]
Thank you very much for the quick fix @filipesilva 
Everything is working again.
