### ISSUE TITLE
Angular 8 injectable pipe migration schematic produces invalid code

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular-cli#14299]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description
After running the v8 schematic it produces invalid code. It transforms a pipe's imports to be:
```
import import { Pipe, PipeTransform, LOCALE_ID, Inject, Injectable } from '@angular/core'; from '@angular/core';
```

## 🔬 Minimal Reproduction
```
git clone https://github.com/mattlewis92/angular-calendar.git
cd angular-calendar
npm install
ng update @angular/cli @angular/core codelyzer --next --force
git diff projects/angular-calendar/src/modules/common/calendar-date.pipe.ts
```

## 🔥 Exception or Error
N/A it works, just produces invalid code

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.1
Node: 11.13.0
OS: darwin x64
Angular: 8.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0-rc.1
@angular-devkit/build-angular      0.800.0-rc.1
@angular-devkit/build-ng-packagr   0.800.0-rc.1
@angular-devkit/build-optimizer    0.800.0-rc.1
@angular-devkit/build-webpack      0.800.0-rc.1
@angular-devkit/core               8.0.0-rc.1
@angular-devkit/schematics         8.0.0-rc.1
@angular/cdk                       7.3.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0-rc.1
@schematics/angular                8.0.0-rc.1
@schematics/update                 0.800.0-rc.1
ng-packagr                         5.1.0
rxjs                               6.5.1
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**
Nope

**Comment by JoostK** [comment]
Thanks for trying the RC and reporting this issue. A fix for this issue is pending in https://github.com/angular/angular/pull/30170

**Comment by devversion** [comment]
Thanks for reporting these migration issues. That is really helpful. Let's track this issue on the Angular repository where a similar one already exists: https://github.com/angular/angular/issues/30159.

**Comment by mattlewis92** [comment]
Whoops, sorry, didn't realise the angular schematics were part of the main repo, didn't think to check there for similar issues. Thanks for looking into it! 😄

**Comment by devversion** [comment]
Oh yeah that's pretty confusing :smile: Need to check if we can make this somehow more obvious.
