### ISSUE TITLE
e2e respects publilcHost, but serve changes publicHost setting

### ISSUE THREAD

**Issue by qlonik** [angular/angular-cli#14297]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I dont know

### Description

As it is now, e2e command is respecting the `publicHost` setting from serve command, and based on that it sets the baseUrl which is used by tests: https://github.com/angular/angular-cli/blob/76492141d21649e1924a7a84a2af25ceca294be1/packages/angular_devkit/build_angular/src/protractor/index.ts#L123-L131

However, the serve command itself modifies this value, and is getting rid of everything in the path, other than host: https://github.com/angular/angular-cli/blob/76492141d21649e1924a7a84a2af25ceca294be1/packages/angular_devkit/build_angular/src/dev-server/index.ts#L154

Is it possible for the serve command to keep the configuration option intact? This way the `baseUrl` for e2e test run will be created correctly.

Alternatively, the value of `baseUrl` option passed in protractor config could be respected, and concatenated with the calculated host from `publicHost` option. However, this way there is duplicate configuration: base url will be specified both for serve command and for e2e command.

## 🔬 Minimal Reproduction

To reproduce, set the serve configuration options as following:
```json
"options": {
    "browserTarget": "myapp:build",
    "baseHref": "/custom-namespace/",
    "publicHost": "https://localhost/custom-namespace/"
}
```

Then run `ng e2e`. 

## 🔥 Exception or Error

The browser will open with URL: `https://localhost/` instead of `https://localhost/custom-namespace/`

## 🌍 Your Environment

It seems that my environment is older compared to the latest commit in this repository. However, it seems that the behaviour is largely similar, and `publicHost` is modified in the same way in older and newer versions.

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.8
Node: 11.12.0
OS: win32 x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.8
@angular/cdk                       7.3.7
@angular/cli                       7.3.8
@angular/flex-layout               7.0.0-beta.24
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.8
@schematics/update                 0.13.8
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0

</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
@alan-agius4 this is similar to https://github.com/angular/angular-cli/pull/14165 right?

**Comment by alan-agius4** [comment]
Similar but this is a different bug which the above mentioned PR won’t address.

**Comment by alan-agius4** [comment]
I have been looking at this a bit and it seems that it is running as expected.  The `PublicHost`, option won't open the browser on that given, but rather make it available publicly on the network using that host.

Looking at what you are passing as `public-host`, I think that you should use `server-path` instead https://angular.io/cli/serve

That said, the e2e builder is not handling the later option.

**Comment by clydin** [comment]
The issue here appears to be that the dev server's `baseUrl` result property is not being used when available within the protractor builder.  This property provides the full URL to access the configured dev server; including deploy URL, base HREF, and serve path options.

The `publicHost` option is intended to be used to satisfy `HOST` header checks or when the client facing URL is different than the address served by the dev server (reverse proxy, for instance).  In such scenarios, protractor's `baseUrl` option would generally be the option of choice as the E2E process will most likely be run independently and potentially on a different machine or container.
The `publicHost` logic within the protractor builder originated in the 1.x timeframe and should mostly be removed as the `baseUrl` result property is more accurate in combined serve/e2e scenarios.

**Comment by alan-agius4** [comment]
Should have been addressed by https://github.com/angular/angular-cli/pull/14376
