### ISSUE TITLE
Build and Serve should account for module polyfills

### ISSUE THREAD

**Issue by AlexAegis** [angular/angular-cli#14293]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I made a polyfill to extend a feature of a node module (RxJS, I added a setter to make a readonly value writable). When manually editing the source of RxJS inside node_modules the polyfill works as expected. However when building the project (`--prod --aot`), or serving with a clean and fresh node_modules folder, the angular CLI doesn't take my modifications into account and thinks that I'm trying to use something that's not there.

### Describe the solution you'd like
Use the polyfills.ts when serving and building the project

### Describe alternatives you've considered
Not using the polyfill.

  This is the polyfill in question:
```typescript
import { BehaviorSubject } from 'rxjs';
Object.defineProperty(BehaviorSubject.prototype, 'value', {
	set: function(v) {
		return this.next(v);
	}
});
```
And the error is thrown where i'm trying to use it in a template file:
```html
[(value)]="myBehaviorSubject.value"
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
