### ISSUE TITLE
No 8.x.y branch on `cli-builds` repo

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-cli#14296]
There is currently no 8.x.y branch on https://github.com/angular/cli-builds (to publish artifacts from the 8.0.x branch of https://github.com/angular/angular-cli).

We need this branch to update the cli commands docs for the stable branch on angular.io.

**Comment by filipesilva** [comment]
Our snapshot script should make the branch, but it looks like https://circleci.com/gh/angular/workflows/angular-cli/tree/8.0.x is red right now so no snapshot. There was a missing cherry-pick. We'll fix it soon.

**Comment by filipesilva** [comment]
It's published now: https://github.com/angular/cli-builds/tree/8.0.x
