### ISSUE TITLE
Unexpected behaviour in --prod

### ISSUE THREAD

**Issue by KhalidSaud** [angular/angular-cli#14295]
Hello,

First time posting an issue, I'm facing strange issue and I cannot find a solution for it other than doing build without --prod

my issue in steps :-

1- I get some data from the browser local storage (I save data to local storage from a different page).

2- I use IF statement to compare 2 objects with same data from local storage (comparing old object with new object to check changes).

3- I use console log if there is a match or not.

4- In ng serve & ng build it works perfectly.

5- In ng serve --prod & ng serve --prod objects will never be equal.

6- There are no console errors.

Any extra information needed ?

Thank You

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
