### ISSUE TITLE
Valid ES5 code breaks after auto-update to ES2015 target

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#14290]
# 🐞 Bug report
```
at runtime, with and without AOT enabled
```

### Is this a regression?

Yes, before auto-update target to es2015 it was valid es5 code. I think because in es5 when creating new variable without using (var,let,const), the variable is automatically global : 
![image](https://user-images.githubusercontent.com/2789203/56827576-7f64b900-685f-11e9-94ee-e1c5c11d58f7.png)

## 🔬 Minimal Reproduction
Anywhere in your angular app with target:es2015 write:
```
let t = 'b';

switch (t) {
  case 'a':
    let numberMin = 1;
    console.log(numberMin)
    break;

  case 'b':
    numberMin = 2;
    console.log(numberMin)
    break;
}
```

## 🔥 Exception or Error
<pre><code>
ERROR ReferenceError: numberMin is not defined
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-beta.16
Node: 10.10.0
OS: win32 x64
Angular: 8.0.0-beta.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.16
@angular-devkit/build-angular     0.800.0-beta.16
@angular-devkit/build-optimizer   0.800.0-beta.16
@angular-devkit/build-webpack     0.800.0-beta.16
@angular-devkit/core              8.0.0-beta.16
@angular-devkit/schematics        8.0.0-beta.16
@angular/cli                      8.0.0-beta.16
@ngtools/webpack                  8.0.0-beta.16
@schematics/angular               8.0.0-beta.16
@schematics/update                0.800.0-beta.16
rxjs                              6.4.0
typescript                        3.4.4
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

cc @filipesilva 

This kind of code is easy to fix to be es2015 valid. But due to the fact it happens only "at runtime" it is dificult on existing angular project to see where&when it happens.

**Comment by filipesilva** [comment]
This is a problem with TS not identifying that the code should error. It is being tracked in https://github.com/Microsoft/TypeScript/issues/31167 and https://github.com/Microsoft/TypeScript/issues/19503.

**Comment by alexeagle** [comment]
We'll inform users about this in the 8.0 blog post - nothing we can do to fix this on Angular's side
