### ISSUE TITLE
Add a formatter/beautifier command

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#143]
Would be really useful to have a cli command that would format/beautify app code. @jelbourn recommends [clang-format](http://clang.llvm.org/docs/ClangFormat.html).

**Comment by jelbourn** [comment]
Yeah- clang-format is what we use on angular/angular. Team member @mprobst occasionally makes contributions to it.

**Comment by mprobst** [comment]
I think clang-format is the leading brand in JS formatting at this point ;-)

The one drawback is that it doesn't handle missing semicolons well, and support for that would be tricky to add (it uses the semicolons as a signal to split statements and re-sync when formatting syntactically incorrect code).

If there are specific improvements or issues, I'm happy to take a look.
