### ISSUE TITLE
UNMET PEER DEPENDENCY webpack@^4.0.0 on UBUNTU 18 CLI on Windows 10

### ISSUE THREAD

**Issue by sreeaharshkrajan** [angular/angular-cli#14307]
/usr/local/bin/webpack-dev-server -> /usr/local/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js
/usr/local/lib
├── UNMET PEER DEPENDENCY webpack@^4.0.0
└─┬ webpack-dev-server@3.3.1
  ├── ansi-html@0.0.7
  ├─┬ bonjour@3.5.0
  │ ├── array-flatten@2.1.2
  │ ├── deep-equal@1.0.1
  │ ├── dns-equal@1.0.0
  │ ├─┬ dns-txt@2.0.2
  │ │ └── buffer-indexof@1.1.1
  │ ├─┬ multicast-dns@6.2.3
  │ │ ├── dns-packet@1.3.1
  │ │ └── thunky@1.0.3
  │ └── multicast-dns-service-types@1.1.0
  ├─┬ chokidar@2.1.5
  │ ├─┬ anymatch@2.0.0
  │ │ └─┬ normalize-path@2.1.1
  │ │   └── remove-trailing-separator@1.1.0
  │ ├── async-each@1.0.3
  │ ├─┬ braces@2.3.2
  │ │ ├── arr-flatten@1.1.0
  │ │ ├── array-unique@0.3.2
  │ │ ├─┬ extend-shallow@2.0.1
  │ │ │ └── is-extendable@0.1.1
  │ │ ├─┬ fill-range@4.0.0
  │ │ │ ├── extend-shallow@2.0.1
  │ │ │ ├─┬ is-number@3.0.0
  │ │ │ │ └─┬ kind-of@3.2.2
  │ │ │ │   └── is-buffer@1.1.6
  │ │ │ ├── repeat-string@1.6.1
  │ │ │ └── to-regex-range@2.1.1
  │ │ ├── isobject@3.0.1
  │ │ ├── repeat-element@1.1.3
  │ │ ├─┬ snapdragon@0.8.2
  │ │ │ ├─┬ base@0.11.2
  │ │ │ │ ├─┬ cache-base@1.0.1
  │ │ │ │ │ ├─┬ collection-visit@1.0.0
  │ │ │ │ │ │ ├── map-visit@1.0.0
  │ │ │ │ │ │ └── object-visit@1.0.1
  │ │ │ │ │ ├── get-value@2.0.6
  │ │ │ │ │ ├─┬ has-value@1.0.0
  │ │ │ │ │ │ └─┬ has-values@1.0.0
  │ │ │ │ │ │   └── kind-of@4.0.0
  │ │ │ │ │ ├─┬ set-value@2.0.0
  │ │ │ │ │ │ └── extend-shallow@2.0.1
  │ │ │ │ │ ├─┬ to-object-path@0.3.0
  │ │ │ │ │ │ └── kind-of@3.2.2
  │ │ │ │ │ ├─┬ union-value@1.0.0
  │ │ │ │ │ │ └─┬ set-value@0.4.3
  │ │ │ │ │ │   └── extend-shallow@2.0.1
  │ │ │ │ │ └─┬ unset-value@1.0.0
  │ │ │ │ │   └─┬ has-value@0.3.1
  │ │ │ │ │     ├── has-values@0.1.4
  │ │ │ │ │     └── isobject@2.1.0
  │ │ │ │ ├─┬ class-utils@0.3.6
  │ │ │ │ │ ├── arr-union@3.1.0
  │ │ │ │ │ ├── define-property@0.2.5
  │ │ │ │ │ └─┬ static-extend@0.1.2
  │ │ │ │ │   ├── define-property@0.2.5
  │ │ │ │ │   └─┬ object-copy@0.1.0
  │ │ │ │ │     ├── copy-descriptor@0.1.1
  │ │ │ │ │     ├── define-property@0.2.5
  │ │ │ │ │     └── kind-of@3.2.2
  │ │ │ │ ├── component-emitter@1.3.0
  │ │ │ │ ├─┬ define-property@1.0.0
  │ │ │ │ │ └─┬ is-descriptor@1.0.2
  │ │ │ │ │   ├── is-accessor-descriptor@1.0.0
  │ │ │ │ │   └── is-data-descriptor@1.0.0
  │ │ │ │ ├─┬ mixin-deep@1.3.1
  │ │ │ │ │ ├── for-in@1.0.2
  │ │ │ │ │ └── is-extendable@1.0.1
  │ │ │ │ └── pascalcase@0.1.1
  │ │ │ ├── debug@2.6.9
  │ │ │ ├─┬ define-property@0.2.5
  │ │ │ │ └─┬ is-descriptor@0.1.6
  │ │ │ │   ├─┬ is-accessor-descriptor@0.1.6
  │ │ │ │   │ └── kind-of@3.2.2
  │ │ │ │   ├─┬ is-data-descriptor@0.1.4
  │ │ │ │   │ └── kind-of@3.2.2
  │ │ │ │   └── kind-of@5.1.0
  │ │ │ ├── extend-shallow@2.0.1
  │ │ │ ├── map-cache@0.2.2
  │ │ │ ├── source-map@0.5.7
  │ │ │ ├─┬ source-map-resolve@0.5.2
  │ │ │ │ ├── atob@2.1.2
  │ │ │ │ ├── decode-uri-component@0.2.0
  │ │ │ │ ├── resolve-url@0.2.1
  │ │ │ │ ├── source-map-url@0.4.0
  │ │ │ │ └── urix@0.1.0
  │ │ │ └── use@3.1.1
  │ │ ├─┬ snapdragon-node@2.1.1
  │ │ │ ├─┬ define-property@1.0.0
  │ │ │ │ └─┬ is-descriptor@1.0.2
  │ │ │ │   ├── is-accessor-descriptor@1.0.0
  │ │ │ │   └── is-data-descriptor@1.0.0
  │ │ │ └─┬ snapdragon-util@3.0.1
  │ │ │   └── kind-of@3.2.2
  │ │ ├── split-string@3.1.0
  │ │ └─┬ to-regex@3.0.2
  │ │   └─┬ safe-regex@1.1.0
  │ │     └── ret@0.1.15
  │ ├─┬ glob-parent@3.1.0
  │ │ ├── is-glob@3.1.0
  │ │ └── path-dirname@1.0.2
  │ ├── inherits@2.0.3
  │ ├─┬ is-binary-path@1.0.1
  │ │ └── binary-extensions@1.13.1
  │ ├─┬ is-glob@4.0.1
  │ │ └── is-extglob@2.1.1
  │ ├── normalize-path@3.0.0
  │ ├── path-is-absolute@1.0.1
  │ ├─┬ readdirp@2.2.1
  │ │ ├── graceful-fs@4.1.15
  │ │ └─┬ readable-stream@2.3.6
  │ │   ├── core-util-is@1.0.2
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@2.0.0
  │ │   ├── string_decoder@1.1.1
  │ │   └── util-deprecate@1.0.2
  │ └── upath@1.1.2
  ├─┬ compression@1.7.4
  │ ├─┬ accepts@1.3.7
  │ │ └── negotiator@0.6.2
  │ ├── bytes@3.0.0
  │ ├─┬ compressible@2.0.17
  │ │ └── mime-db@1.40.0
  │ ├─┬ debug@2.6.9
  │ │ └── ms@2.0.0
  │ ├── on-headers@1.0.2
  │ ├── safe-buffer@5.1.2
  │ └── vary@1.1.2
  ├── connect-history-api-fallback@1.6.0
  ├─┬ debug@4.1.1
  │ └── ms@2.1.1
  ├─┬ del@4.1.1
  │ ├─┬ @types/glob@7.1.1
  │ │ ├── @types/events@3.0.0
  │ │ ├── @types/minimatch@3.0.3
  │ │ └── @types/node@11.13.8
  │ ├─┬ globby@6.1.0
  │ │ ├─┬ array-union@1.0.2
  │ │ │ └── array-uniq@1.0.3
  │ │ ├─┬ glob@7.1.3
  │ │ │ ├── fs.realpath@1.0.0
  │ │ │ ├─┬ inflight@1.0.6
  │ │ │ │ └── wrappy@1.0.2
  │ │ │ ├─┬ minimatch@3.0.4
  │ │ │ │ └─┬ brace-expansion@1.1.11
  │ │ │ │   ├── balanced-match@1.0.0
  │ │ │ │   └── concat-map@0.0.1
  │ │ │ └── once@1.4.0
  │ │ ├── object-assign@4.1.1
  │ │ ├── pify@2.3.0
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├── is-path-cwd@2.1.0
  │ ├─┬ is-path-in-cwd@2.1.0
  │ │ └─┬ is-path-inside@2.1.0
  │ │   └── path-is-inside@1.0.2
  │ ├── p-map@2.1.0
  │ ├── pify@4.0.1
  │ └── rimraf@2.6.3
  ├─┬ express@4.16.4
  │ ├── array-flatten@1.1.1
  │ ├─┬ body-parser@1.18.3
  │ │ ├── debug@2.6.9
  │ │ ├─┬ iconv-lite@0.4.23
  │ │ │ └── safer-buffer@2.1.2
  │ │ └── raw-body@2.3.3
  │ ├── content-disposition@0.5.2
  │ ├── content-type@1.0.4
  │ ├── cookie@0.3.1
  │ ├── cookie-signature@1.0.6
  │ ├── debug@2.6.9
  │ ├── depd@1.1.2
  │ ├── encodeurl@1.0.2
  │ ├── escape-html@1.0.3
  │ ├── etag@1.8.1
  │ ├─┬ finalhandler@1.1.1
  │ │ ├── debug@2.6.9
  │ │ └── unpipe@1.0.0
  │ ├── fresh@0.5.2
  │ ├── merge-descriptors@1.0.1
  │ ├── methods@1.1.2
  │ ├─┬ on-finished@2.3.0
  │ │ └── ee-first@1.1.1
  │ ├── parseurl@1.3.3
  │ ├── path-to-regexp@0.1.7
  │ ├─┬ proxy-addr@2.0.5
  │ │ └── forwarded@0.1.2
  │ ├── qs@6.5.2
  │ ├── range-parser@1.2.0
  │ ├─┬ send@0.16.2
  │ │ ├── debug@2.6.9
  │ │ ├── destroy@1.0.4
  │ │ └── mime@1.4.1
  │ ├── serve-static@1.13.2
  │ ├── setprototypeof@1.1.0
  │ ├── statuses@1.4.0
  │ ├─┬ type-is@1.6.18
  │ │ └── media-typer@0.3.0
  │ └── utils-merge@1.0.1
  ├── html-entities@1.2.1
  ├─┬ http-proxy-middleware@0.19.1
  │ ├─┬ http-proxy@1.17.0
  │ │ ├── eventemitter3@3.1.1
  │ │ ├─┬ follow-redirects@1.7.0
  │ │ │ └─┬ debug@3.2.6
  │ │ │   └── ms@2.1.1
  │ │ └── requires-port@1.0.0
  │ ├── lodash@4.17.11
  │ └─┬ micromatch@3.1.10
  │   ├── arr-diff@4.0.0
  │   ├─┬ define-property@2.0.2
  │   │ └─┬ is-descriptor@1.0.2
  │   │   ├── is-accessor-descriptor@1.0.0
  │   │   └── is-data-descriptor@1.0.0
  │   ├─┬ extend-shallow@3.0.2
  │   │ ├── assign-symbols@1.0.0
  │   │ └─┬ is-extendable@1.0.1
  │   │   └── is-plain-object@2.0.4
  │   ├─┬ extglob@2.0.4
  │   │ ├─┬ define-property@1.0.0
  │   │ │ └─┬ is-descriptor@1.0.2
  │   │ │   ├── is-accessor-descriptor@1.0.0
  │   │ │   └── is-data-descriptor@1.0.0
  │   │ ├─┬ expand-brackets@2.1.4
  │   │ │ ├── debug@2.6.9
  │   │ │ ├── define-property@0.2.5
  │   │ │ ├── extend-shallow@2.0.1
  │   │ │ └── posix-character-classes@0.1.1
  │   │ └── extend-shallow@2.0.1
  │   ├── fragment-cache@0.2.1
  │   ├── kind-of@6.0.2
  │   ├─┬ nanomatch@1.2.13
  │   │ └── is-windows@1.0.2
  │   ├── object.pick@1.3.0
  │   └── regex-not@1.0.2
  ├─┬ import-local@2.0.0
  │ ├── pkg-dir@3.0.0
  │ └─┬ resolve-cwd@2.0.0
  │   └── resolve-from@3.0.0
  ├─┬ internal-ip@4.3.0
  │ ├─┬ default-gateway@4.2.0
  │ │ ├─┬ execa@1.0.0
  │ │ │ ├─┬ cross-spawn@6.0.5
  │ │ │ │ ├── nice-try@1.0.5
  │ │ │ │ ├── path-key@2.0.1
  │ │ │ │ ├── semver@5.7.0
  │ │ │ │ ├─┬ shebang-command@1.2.0
  │ │ │ │ │ └── shebang-regex@1.0.0
  │ │ │ │ └─┬ which@1.3.1
  │ │ │ │   └── isexe@2.0.0
  │ │ │ ├─┬ get-stream@4.1.0
  │ │ │ │ └─┬ pump@3.0.0
  │ │ │ │   └── end-of-stream@1.4.1
  │ │ │ ├── is-stream@1.1.0
  │ │ │ ├── npm-run-path@2.0.2
  │ │ │ ├── p-finally@1.0.0
  │ │ │ ├── signal-exit@3.0.2
  │ │ │ └── strip-eof@1.0.0
  │ │ └── ip-regex@2.1.0
  │ └── ipaddr.js@1.9.0
  ├── ip@1.1.5
  ├── killable@1.0.1
  ├── loglevel@1.6.1
  ├─┬ opn@5.5.0
  │ └── is-wsl@1.1.0
  ├─┬ portfinder@1.0.20
  │ ├── async@1.5.2
  │ ├── debug@2.6.9
  │ └─┬ mkdirp@0.5.1
  │   └── minimist@0.0.8
  ├─┬ schema-utils@1.0.0
  │ ├─┬ ajv@6.10.0
  │ │ ├── fast-deep-equal@2.0.1
  │ │ ├── fast-json-stable-stringify@2.0.0
  │ │ ├── json-schema-traverse@0.4.1
  │ │ └─┬ uri-js@4.2.2
  │ │   └── punycode@2.1.1
  │ ├── ajv-errors@1.0.1
  │ └── ajv-keywords@3.4.0
  ├─┬ selfsigned@1.10.4
  │ └── node-forge@0.7.5
  ├── semver@6.0.0
  ├─┬ serve-index@1.9.1
  │ ├── batch@0.6.1
  │ ├── debug@2.6.9
  │ ├── http-errors@1.6.3
  │ └── mime-types@2.1.24
  ├─┬ sockjs@0.3.19
  │ ├─┬ faye-websocket@0.10.0
  │ │ └─┬ websocket-driver@0.7.0
  │ │   ├── http-parser-js@0.5.0
  │ │   └── websocket-extensions@0.1.3
  │ └── uuid@3.3.2
  ├─┬ sockjs-client@1.3.0
  │ ├─┬ debug@3.2.6
  │ │ └── ms@2.1.1
  │ ├─┬ eventsource@1.0.7
  │ │ └── original@1.0.2
  │ ├── faye-websocket@0.11.1
  │ ├── json3@3.3.2
  │ └─┬ url-parse@1.4.7
  │   └── querystringify@2.1.1
  ├─┬ spdy@4.0.0
  │ ├── handle-thing@2.0.0
  │ ├── http-deceiver@1.2.7
  │ ├── select-hose@2.0.0
  │ └─┬ spdy-transport@3.0.0
  │   ├── detect-node@2.0.4
  │   ├── hpack.js@2.1.6
  │   ├── obuf@1.1.2
  │   ├── readable-stream@3.3.0
  │   └─┬ wbuf@1.7.3
  │     └── minimalistic-assert@1.0.1
  ├─┬ strip-ansi@3.0.1
  │ └── ansi-regex@2.1.1
  ├─┬ supports-color@6.1.0
  │ └── has-flag@3.0.0
  ├─┬ url@0.11.0
  │ ├── punycode@1.3.2
  │ └── querystring@0.2.0
  ├── UNMET PEER DEPENDENCY webpack@^4.0.0
  ├─┬ webpack-dev-middleware@3.6.2
  │ ├─┬ memory-fs@0.4.1
  │ │ └─┬ errno@0.1.7
  │ │   └── prr@1.0.1
  │ └── mime@2.4.2
  ├─┬ webpack-log@2.0.0
  │ └── ansi-colors@3.2.4
  └─┬ yargs@12.0.5
    ├─┬ cliui@4.1.0
    │ ├─┬ strip-ansi@4.0.0
    │ │ └── ansi-regex@3.0.0
    │ └─┬ wrap-ansi@2.1.0
    │   └─┬ string-width@1.0.2
    │     ├── code-point-at@1.1.0
    │     └─┬ is-fullwidth-code-point@1.0.0
    │       └── number-is-nan@1.0.1
    ├── decamelize@1.2.0
    ├─┬ find-up@3.0.0
    │ └─┬ locate-path@3.0.0
    │   ├─┬ p-locate@3.0.0
    │   │ └─┬ p-limit@2.2.0
    │   │   └── p-try@2.2.0
    │   └── path-exists@3.0.0
    ├── get-caller-file@1.0.3
    ├─┬ os-locale@3.1.0
    │ ├─┬ lcid@2.0.0
    │ │ └── invert-kv@2.0.0
    │ └─┬ mem@4.3.0
    │   ├─┬ map-age-cleaner@0.1.3
    │   │ └── p-defer@1.0.0
    │   ├── mimic-fn@2.1.0
    │   └── p-is-promise@2.1.0
    ├── require-directory@2.1.1
    ├── require-main-filename@1.0.1
    ├── set-blocking@2.0.0
    ├─┬ string-width@2.1.1
    │ ├── is-fullwidth-code-point@2.0.0
    │ └─┬ strip-ansi@4.0.0
    │   └── ansi-regex@3.0.0
    ├── which-module@2.0.0
    ├── y18n@4.0.0
    └─┬ yargs-parser@11.1.1
      └── camelcase@5.3.1

npm WARN optional Skipping failed optional dependency /webpack-dev-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
npm WARN webpack-dev-server@3.3.1 requires a peer of webpack@^4.0.0 but none was installed.
npm WARN webpack-dev-middleware@3.6.2 requires a peer of webpack@^4.0.0 but none was installed.

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
