### ISSUE TITLE
Live reload cannot be disabled in version 8

### ISSUE THREAD

**Issue by pe8ter** [angular/angular-cli#14300]
# 🐞 Bug report

### Command
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: **7.3.8**

### Description

Disabling live reload when serving an app using `ng serve --liveReload=false` fails to disable live reloading.

## 🔬 Minimal Reproduction
1. Create a default application: `ng new my-app`.
2. Serve with live reload disabled: `ng serve --liveReload=false`.
3. Open the page at http://localhost:4200
4. Edit then save any HTML/CSS/TypeScript file.

Observe the page automatically reloading.

## 🔥 Exception or Error
<pre><code>n/a</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 8.0.0-rc.1
Node: 10.15.3
OS: darwin x64
Angular: 8.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.1
@angular-devkit/build-angular     0.800.0-rc.1
@angular-devkit/build-optimizer   0.800.0-rc.1
@angular-devkit/build-webpack     0.800.0-rc.1
@angular-devkit/core              8.0.0-rc.1
@angular-devkit/schematics        8.0.0-rc.1
@ngtools/webpack                  8.0.0-rc.1
@schematics/angular               8.0.0-rc.1
@schematics/update                0.800.0-rc.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0</code></pre>

**Comment by pe8ter** [comment]
I can confirm this now works correctly in version `8.0.0-rc.2`. Thanks!

**Comment by CMohamed** [comment]
The problem was related with Inotify Watches Limit on Linux. To solve the issue, I increased the watches limit to 512K. Run these commands.

```
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl -p --system
```

After that, I restarted my IDE, and after that, the change detection started to work.

Source : [https://stackoverflow.com/questions/40366212/angular-cli-ng-serve-livereload-not-working](url)
