### ISSUE TITLE
CLI does not respect style file extension set in schematic when generating components without specifying the project

### ISSUE THREAD

**Issue by martinfletcher** [angular/angular-cli#14309]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Unknown

### Description
My workspace has 2 projects, 'my-app' (default project) and 'my-lib'

Running 'ng g c my-component' generates with default css file extension
Running 'ng g c my-component --project=my-app' generates with the schematic set scss file

It looks like the generate command is not respecting the schematic when you do not specify the project

## 🔬 Minimal Reproduction
ng new my-app-workspace --createApplication=false --routing --style=scss

ng g application my-app --routing --style=scss

ng g library my-lib --routing --style=scss

ng g c my-component

## 🔥 Exception or Error
The style file extension of the created style file for the new component is 'css', not 'scss'

## 🌍 Your Environment

Angular CLI: 7.3.8
Node: 10.6.0
OS: win32 x64
Angular: 7.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.8
@angular-devkit/build-angular      0.13.8
@angular-devkit/build-ng-packagr   0.13.8
@angular-devkit/build-optimizer    0.13.8
@angular-devkit/build-webpack      0.13.8
@angular-devkit/core               7.3.8
@angular-devkit/schematics         7.3.8
@angular/cli                       7.3.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.8
@schematics/angular                7.3.8
@schematics/update                 0.13.8
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0

**Comment by wdunn001** [comment]
experiencing this is exact same issue out of the blue I can only get the cli to create scss using ng g c _componentName_ --style=scss

**Comment by YealZoy** [comment]
Has this problem been solved?

**Comment by hakimio** [comment]
No, it's still broken with 7.3.9. Had to downgrade to 7.3.5 to get it to work again.

**Comment by admir86** [comment]
same problem in 8.0.0-rc.4

**Comment by wdunn001** [comment]
I hope this helps someone my issue was that we had defined schematics in a much earlier version of the app at the end of our angular.json we had

```
  "cli": {
    "defaultCollection": "@ngrx/schematics"
  }
```
this seems to bork the whole cli generate thing up.

**Comment by clydin** [comment]
This now works as expected with the latest version of the CLI.  If anyone is still encountering problems with the latest version, please open a new issue report.
