### ISSUE TITLE
Disable sourcemaps on @angular-devkit/build-angular:server

### ISSUE THREAD

**Issue by stot3** [angular/angular-cli#14304]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I am not sure. 

### Description

You need to add sourceMap: false to the server builder because including the sourcemaps on each page, causes alot of overhead, Facebook is not able to see past the first MB on a site, and adding an extra 100 KB on top of Material already loading in SSR, is just going to cause bundle sizes to be huge for no reason, I ask that you include this in the angular.json file. 

        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "sourceMap": false,
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }

## 🔬 Minimal Reproduction

Set up a new SSR project using the steps in the angular.io, then take a look at the angular.json

## 🔥 Exception or Error
You will not see an error, 

## 🌍 Your Environment
Angular CLI: 7.3.6
Node: 10.15.3
OS: darwin x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/fire                     5.1.0
@angular/material                 7.3.5
@angular/pwa                      0.13.6
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

This was a very hard issue for me to debug, if you are using SSR, and wondering why certain sites can see your meta tags, and others can't, it's probably because of the inclusion of sourcemaps could be breaking their file size limits.

**Comment by alan-agius4** [comment]
Hi @stot3, production configuration for the server builder already includes `"sourceMaps": false`.

Kindly see: https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/universal/index.ts#L62

I am guessing that the above configuration was not generated recently, right?

**Comment by stot3** [comment]
I haven’t generated the base configuration for SSR I maybe a week or two

**Comment by stot3** [comment]
I appreciate the prompt response I will close this.
