### ISSUE TITLE
run an Angular library in universal mode (SSR & browser)

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular-cli#14319]
I started an Angular universal project, including a library which has some classes that should work in the server (i.e: node environment) and another classes should run in the browser.

and here is a simplified classes from the library 

files.ts
```
//this file should work in the server
import fs from "fs"
export default class{
  read(){ ... }
  write(){ ... }
}
```

myComponent.ts
```
//this file should work in the browser
@component(...)
export class MyComponent{}
```

when I build this library with Angulaar cli (ng build myLibrary), how to tell Angular which file should work in the server and witch one should work in the browser

and this is my [project](https://github.com/xxyyzz2050/eldeebCMS), if you need a close look.

**Comment by thefliik** [comment]
General instructions for SSR can be found on https://angular.io/guide/universal. If you have some code that you only want to run in a specific environment (e.g. the browser or the server), here are two options:

1. Extract the code into a service. Create a default "browser" version of the service and a server version of the service. On the server, override the browser version of the service by injecting the server version of the service in `app.server.module.ts`.
2. Wrap the code in question in a "platform check" i.e. `if (isPlatformBrowser(this.platformId))`.
   - [isPlatformBrowser()](https://angular.io/api/common/isPlatformBrowser)
   - [isPlatformServer()](https://angular.io/api/common/isPlatformServer)
   - [PLATFORM_ID](https://angular.io/api/core/PLATFORM_ID) (usage `@Inject(PLATFORM_ID) private platformID: Object`)

**Comment by xxyyzz2050** [comment]
many thaaaaaaaaaaaaaaanks @thefliik 
I will give a try, at least it is not imposible to develop a cross-platform library

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
