### ISSUE TITLE
Ivy mode with 8.0.0-rc.2: The error message doesn't help at all

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/angular-cli#14326]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I just tried to migrate to Ivy mode: edited _tsconfig.app.json_ ("enableIvy": true, "allowEmptyCodegenFiles": true), and _package.json_ ("postinstall": "ivy-ngcc"), and finally run "_npm install_".

### Description

The Ivy compiler issues an error message which doesn't help at all to localize the error:

## 🔥 Error

```
ERROR in __ng_typecheck__.ts(108,41): error TS2532: Object is possibly 'undefined'.
```

## 🌍 Your Environment

Angular CLI 8.0.0-rc.2, Windows 10 Enterprise

**Comment by alan-agius4** [comment]
Thanks, for reporting this. However this is not caused by Angular CLI as it's a Compiler issue.

Such issues should be filled here: https://github.com/angular/angular

Thanks.
