### ISSUE TITLE
Assets folder resolution: Running an application within a project not picking up assets

### ISSUE THREAD

**Issue by tshowers** [angular/angular-cli#14322]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 
I created an application within an Angular workspace. When running

ng serve [application-name]

Picks up images and files in asset folder fine under application. Now I want to run the workspace with just

ng serve

I would expect through having the application lazy loaded the path would resolve but instead I get

zone.js:3243 GET http://localhost:4200/assets/terms.txt 404 (Not Found)

Can I NOT use the asset folder within an application that is within a workspace?

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
