### ISSUE TITLE
bug(schematics): workspace utility is not available

### ISSUE THREAD

**Issue by ngfelixl** [angular/angular-cli#14336]
# 🐞 Bug report

### Command (mark with an `x`)

This is not related to a particular cli command

### Is this a regression?

I am not sure about that. The likeliest thing I can imagine is that the npm package is behind the 

### Description

I am trying to write custom schematics. The official component schematic uses for example the the `workspace` utility which is not available in the `@schematics/angular` npm module. When trying to import for example `getWorkspace` with

```ts
import {getWorkspace} from '@schematics/angular/utilities/workspace';
```

it does not find the `/workspace`, but almost every other utility from `/packages/schematics/angular/utility` is available.

## 🔬 Minimal Reproduction

- Install `schematics-cli` globally
- Create a new schematics project with `schematics blank schematicName`
- cd to project and run `npm install @schematics/angular`
- open `/src/schematicName/index.ts`
- try to `import {getWorkspace} from '@schematics/angular/utility/workspace';`

## 🌍 Your Environment
<pre><code>Angular CLI: 7.3.8
Node: 10.15.3
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.8 (cli-only)
@angular-devkit/core         7.3.8
@angular-devkit/schematics   7.3.8
@schematics/angular          7.3.8
@schematics/update           0.13.8 (cli-only)
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Comment by clydin** [comment]
That particular set of functions is only present in 8.0+.
Please note though that none of the utility functions include in `@angular/schematics` are intended to be used outside of the package.  These are not considered public APIs and may change or be removed over time.
However, future work is in the planning stages to provide a comprehensive suite of public utility functions for typical and common schematic use cases.
