### ISSUE TITLE
@angular-devkit/build-angular Module not found Can't resolve 'core-js/...' on ng serve

### ISSUE THREAD

**Issue by fan2404** [angular/angular-cli#14347]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, but unable to identify the previous version.

### Description

After updating the project dependencies I can't run my ionic application due to the cli not finding the build-angular module. This also happens if I use the package.json in a regular angular project, therefore I suspect that the problem is not with ionic.
This seems to depend on the installed package versions, however lowering the @angular-devkit/build-angular version did not help. No noticable warnings or errors are shown. Am I missing any issues due to other dependencies?

package.json:
<pre><code>
{
  "name": "UpdateTest",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "https://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^7.2.14",
    "@angular/core": "^7.2.14",
    "@angular/forms": "^7.2.14",
    "@angular/http": "^7.2.14",
    "@angular/platform-browser": "^7.2.14",
    "@angular/platform-browser-dynamic": "^7.2.14",
    "@angular/router": "^7.2.14",
    "@ionic-native/core": "^5.5.1",
    "@ionic-native/splash-screen": "^5.5.1",
    "@ionic-native/status-bar": "^5.5.1",
    "@ionic/angular": "^4.3.1",
    "core-js": "^3.0.1",
    "rxjs": "~6.5.1",
    "tslib": "^1.9.3",
    "zone.js": "^0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.13.8",
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "~7.3.8",
    "@angular/compiler": "~7.2.14",
    "@angular/compiler-cli": "~7.2.14",
    "@angular/language-service": "~7.2.14",
    "@ionic/angular-toolkit": "~1.5.1",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~12.0.0",
    "codelyzer": "~5.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.2",
    "ts-node": "~8.1.0",
    "tslint": "~5.16.0",
    "typescript": "^3.2.2"
  },
  "description": "An Ionic project"
}
</pre></code>

## 🔬 Minimal Reproduction

1. Creating new project via CLI
2. Replace package.json
3. npm i
4. ng serve

## 🔥 Exception or Error
<pre><code>
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/array' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/date' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/function' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/map' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/math' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/number' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/object' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/parse-float' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/parse-int' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-jit-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/reflect' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/regexp' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/set' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/string' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/symbol' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/es2015-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es6/weak-map' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
[ng] ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\Ng\UpdateTest\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.8
Node: 8.14.1
OS: win32 x64
Angular: 7.2.14
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.8
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.5.1
typescript                        3.2.2
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

Reinstalling @angular-devkit/build-angular, deleting node_modules and reinstalling all packages, verifying cache and trying on a different computer did not help.

**Comment by clydin** [comment]
Major versions of dependencies generally have breaking changes.  The dependencies of a new project are setup to ensure compatibility with the system.  The following is problematic item in this case although there may be others:
`"core-js": "^3.0.1",` should be `"core-js": "^2.6.5",`.
