### ISSUE TITLE
ng build -prod app stuck on loading screen

### ISSUE THREAD

**Issue by MadUser** [angular/angular-cli#14346]
I see that this is not a new issue but still none of the answers has helped me.

I just finished upgrade process of a large Angular 5.2 project to Angular 7.2.14
I can load the app on dev mode but on prod mode I am stuck on loading without any errors/warnings on the console or network.
using node 8.11.3

I tried to change href from "/" to "./"
I have many 3rd party library that I use. I can't just remove them and see what happens.

Does anyone has a lead for me?

this is package.json:

{
  "name": "kuku",
  "version": "1.0.0",
  "angular-cli": {},
  "scripts": {
    "compodoc": "./node_modules/.bin/compodoc -p tsconfig.json",
    "start": "node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --poll=2000 --proxy-config proxy.conf.json --host 127.0.0.1 --ssl true --ssl-key 'ssl/server.key'' --ssl-cert 'ssl/server.crt'",
    "start-no-refresh": "ng serve --live-reload false --poll=2000 --proxy-config proxy.conf.json --host 127.0.0.1 --ssl 1 --ssl-key 'ssl/server.key'' --ssl-cert 'ssl/server.crt'",
    "start:prod": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng serve --prod=true --sourceMap=true --optimization=false --progress=true --proxy-config proxy.conf.json --host 127.0.0.1 --ssl true --ssl-key 'ssl/server.key'' --ssl-cert 'ssl/server.crt'",
    "start-no-ssl": "ng serve --proxy-config proxy.conf.json",
    "oldlint": "tslint \"src/**/*.ts\"",
    "test": "ng test --watch=false --progress=true --single-run",
    "test_dev": "ng test --progress=true --code-coverage",
    "oldpree2e": "webdriver-manager update",
    "olde2e": "protractor",
    "build:prod": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod  --progress=true --base-href /kuku/products/",
    "build:devtest": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer=false --progress=true --base-href /kuku/products/",
    "build:dev": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --dev --progress=true --base-href /kuku/products/",
    "ng": "ng",
    "newstart": "ng serve",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "7.2.14",
    "@angular/cdk": "7.3.7",
    "@angular/common": "7.2.14",
    "@angular/compiler": "7.2.14",
    "@angular/core": "7.2.14",
    "@angular/flex-layout": "7.0.0-beta.24",
    "@angular/forms": "7.2.14",
    "@angular/http": "7.2.14",
    "@angular/material": "7.3.7",
    "@angular/platform-browser": "7.2.14",
    "@angular/platform-browser-dynamic": "7.2.14",
    "@angular/router": "7.2.14",
    "@types/file-saver": "1.3.0",
    "@types/hammerjs": "2.0.35",
    "@types/lodash": "4.14.104",
    "angular-tree-component": "7.0.1",
    "angular2gridster": "7.0.2",
    "chart.js": "2.7.2",
    "core-js": "2.5.3",
    "d3": "^5.7.0",
    "enhanced-resolve": "3.4.1",
    "file-saver": "1.3.3",
    "hammerjs": "2.0.8",
    "moment": "2.21.0",
    "moment-es6": "1.0.0",
    "ng2-ace-editor": "0.3.4",
    "ng2-handy-syntax-highlighter": "1.0.12",
    "nodemon": "1.14.11",
    "patternomaly": "1.3.0",
    "primeng": "7.1.2",
    "prismjs": "1.11.0",
    "rxjs": "6.5.1",
    "rxjs-compat": "6.5.1",
    "tslib": "1.9.0",
    "velocity-animate": "1.5.1",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "7.3.8",
    "@angular/compiler-cli": "7.2.14",
    "@compodoc/compodoc": "1.0.8",
    "@types/d3": "^5.0.0",
    "@types/jasmine": "2.8.6",
    "@types/node": "6.0.101",
    "codelyzer": "4.2.1",
    "jasmine-core": "2.99.1",
    "jasmine-spec-reporter": "3.3.0",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.3",
    "karma-firefox-launcher": "1.1.0",
    "karma-ie-launcher": "1.0.0",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-spec-reporter": "0.0.32",
    "node-sass": "4.8.3",
    "nodemon": "1.14.11",
    "phantomjs-prebuilt": "2.1.16",
    "process-nextick-args": "1.0.7",
    "protractor": "5.3.0",
    "source-map-explorer": "^1.5.0",
    "ts-node": "2.1.2",
    "tslint": "5.0.0",
    "typescript": "3.2.4",
    "webdriver-manager": "10.3.0"
  }
}

**Comment by MadUser** [comment]
well, I found an rxjs exception when debugging but nothing in the console.

**Comment by tabuckner** [comment]
@MadUser how did you debug your production builds?
