### ISSUE TITLE
Cannot create a stackblitz repo with ivy

### ISSUE THREAD

**Issue by ocombe** [angular/angular-cli#14353]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
```

### Is this a regression?
No

### Description

I created a new ivy app with the cli rc2 using: `ng new --enable-ivy`, then uploaded the code to GitHub: https://github.com/ocombe/cli-ivy-test
I then imported this repository in Stackblitz using the following url: https://stackblitz.com/github/ocombe/cli-ivy-test

But the app that it created doesn't work, it uses cli v7 instead of v8 (like it was in my package.json) and it's trying to install core-js for some reason and it doesn't work.

## 🔬 Minimal Reproduction
See above ^

## 🔥 Exception or Error
<pre><code>

Can't find package:core-js

</code></pre>

**Comment by filipesilva** [comment]
It's odd that StackBlitz chose to use a different version. CLI v7 shouldn't be used with Angular 8 anyway, we have a same-version policy currently.

I tried forking the stackblitz project and update the versions (https://stackblitz.com/edit/github-2ybfdv?file=package.json) but still see the error. Adding `"core-js": "3.0.1"` to the dependencies doesn't remove the error either.

It might be that StackBlitz hasn't update their setup to match our setup. Or maybe there's something in our setup that's not compatible with StackBlitz.

I'm not well versed in their setup but something's going wrong here and this will probably affect existing docs samples.

**Comment by EricSimons** [comment]
Hey all- we're digging into this on our end right now. Will report back once we've gotten to the bottom of it! 🙏

**Comment by filipesilva** [comment]
Heya @EricSimons! If I had to bet it might be related to how we dynamically add polyfills from `core-js` as a dependency from `@angular-devkit/build-angular`. On a new 8 project `core-js` is located as these deps:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/rc-project (master)
$ npm ls core-js
rc-project@0.0.0 D:\sandbox\rc-project
+-- @angular-devkit/build-angular@0.800.0-rc.2
| +-- core-js@3.0.1
| `-- istanbul-instrumenter-loader@3.0.1
|   `-- istanbul-lib-instrument@1.10.2
|     `-- babel-generator@6.26.1
|       `-- babel-runtime@6.26.0
|         `-- core-js@2.6.5
`-- karma@4.1.0
  `-- core-js@2.6.5
```

I'm not too sure how our setup translates to the StackBlitz setup, but let me know if we can help.

**Comment by EricSimons** [comment]
Thanks a ton for the help @filipesilva! It's indeed related to core-js being nested in node_modules. We're working on a fix & should have it live within the next day or so- will report back once it's live 👍

**Comment by filipesilva** [comment]
Awesome~~ 🚀

**Comment by EricSimons** [comment]
Hey all- just FYI this is fixed on prod! We're going to bump a couple other things but lmk if you run into any other issues 🤗

**Comment by filipesilva** [comment]
@EricSimons can confirm it's working on https://stackblitz.com/github/ocombe/cli-ivy-test and https://stackblitz.com/edit/github-2ybfdv?file=package.json, thanks for the speedy resolution!

**Comment by ocombe** [comment]
Awesome! Thanks!

**Comment by ocombe** [comment]
Actually @EricSimons it runs with view engine, not ivy. The option `enableIvy` in the app config doesn't seem to be picked up?

**Comment by EricSimons** [comment]
Ivy support is currently WIP for SB’s in-browser toolchain- ETA is EOM/June

**Comment by filipesilva** [comment]
@ocombe I think that answers your question. I don't think there's anything else to address in this repo so I'm closing this issue.

**Comment by ocombe** [comment]
@EricSimons any news on that? It looks like it's still not working?
