### ISSUE TITLE
Moving a library into a directory causes issues.

### ISSUE THREAD

**Issue by iqjotsangha** [angular/angular-cli#14361]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Unlikely.

### Description

I had created a "libs" directory in the "projects" folder with the intention of placing my libraries in there. However, when I try to run `ng test libraryName` , the CLI is not using the correct path for the library. Instinctively, I believed I had made an error in specifying the path in the angular.json file, but that was not the case. For some reason, placing libraries inside of a directory causes problems. 

**Default Project Structure (No Errors):**
![image](https://user-images.githubusercontent.com/43549680/57318900-33f8a900-70b0-11e9-8c3f-166c195554e6.png)

**Desired Project Structure (Causes Errors):**
![image](https://user-images.githubusercontent.com/43549680/57318949-4bd02d00-70b0-11e9-9958-8ca8f6123945.png)

## 🔬 Minimal Reproduction

1. Create New Project (`ng new projectName`)
2. Navigate into Project Directory (`cd projectName`)
3. Create Library (`ng generate library libraryName`)
4. Create a directory under "projects" named "libs".
5. Move library into "libs".
6. Modify the paths found for "libraryName" in angular.json to reflect the change made in step 5. (i.e. change path from 'projects/libraryName' to 'projects/**libs**/libraryName'
7. Run `ng test libraryName` (Or `ng build libraryName`/`ng lint libraryName`)
8. Angular CLI will error.

## 🔥 Exception or Error
<pre><code>
error TS5058: The specified path does not exist: 'C:/Users/user/projectName/projects/tsconfig.json'.

Error: error TS5058: The specified path does not exist: 'C:/Users/user/projectName/projects/tsconfig.json'.

</code></pre>
**Note:** The path being used is incorrect. It should be 'C:/Users/user/projectName/projects/**libs**/**libraryName**/librarytsconfig.json' instead of 'C:/Users/user/projectName/projects/tsconfig.json'

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.2.9
Node: 10.15.3
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.9
@angular-devkit/build-angular      0.8.9
@angular-devkit/build-ng-packagr   0.8.9
@angular-devkit/build-optimizer    0.8.9
@angular-devkit/build-webpack      0.8.9
@angular-devkit/core               0.8.9
@angular-devkit/schematics         0.8.9
@angular/cli                       6.2.9
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.2.9
@schematics/angular                0.8.9
@schematics/update                 0.8.9
ng-packagr                         4.7.1
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.16.4

</code></pre>

**Anything else relevant?**

**angular.json:**

<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "angularLibraryGenerateTest": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/angularLibraryGenerateTest",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "angularLibraryGenerateTest:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "angularLibraryGenerateTest:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "angularLibraryGenerateTest:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "angularLibraryGenerateTest-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "angularLibraryGenerateTest:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "angularLibraryGenerateTest:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "libraryName": {
      "root": "projects/libs/libraryName",
      "sourceRoot": "projects/libs/libraryName/src",
      "projectType": "library",
      "prefix": "lib",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/libs/libraryName/tsconfig.lib.json",
            "project": "projects/libs/libraryName/ng-package.json"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/libs/libraryName/src/test.ts",
            "tsConfig": "projects/libs/libraryName/tsconfig.spec.json",
            "karmaConfig": "projects/libs/libraryName/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/libs/libraryName/tsconfig.lib.json",
              "projects/libs/libraryName/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "angularLibraryGenerateTest"
}
</code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

That said, most likely you missed to change the `tsconfig.json` extend path in `tsconfig.lib.json`.
