### ISSUE TITLE
Webpack branch: how should I be loading fonts (from Bootstrap, etc.)

### ISSUE THREAD

**Issue by sunild** [angular/angular-cli#1436]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OS X 10.11.5

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

I'm running the latest commit from the webpack branch of the cli (b8f502e326954b21f40995b7aaad3ad0b3fa7b53):
angular-cli: local (v1.0.0-beta.10, branch: webpack)
node: 4.3.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Added Bootstrap 3 via npm 

4. The log given by the failure. Normally this include a stack trace and some
   more information.

404 errors in browser for the following Bootstrap glyphicon fonts:
http://localhost:4200/fonts/glyphicons-halflings-regular.woff2
http://localhost:4200/fonts/glyphicons-halflings-regular.woff
http://localhost:4200/fonts/glyphicons-halflings-regular.ttf

5. Mention any other details that might be useful.

I know the webpack branch is still in development... I converted a real project from the SystemJS version of the CLI to the Webpack version, and it's working great so far. Happy to share my upgrade notes if it helps (all from memory, so your mileage may vary). 

I'm just wondering if I did something wrong config wise (regarding fonts), or if perhaps if the CLI should have a loader config for fonts files. Or maybe a way to add a custom loader configuration?

> ---------------------------------------------------------------
> > Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Hi @sunild, the webpack branch isn't the official one yet so we don't really want people to be opening issues against it, which is why I am closing this one.

I'll ask you to comment on https://github.com/angular/angular-cli/issues/1356 instead.
