### ISSUE TITLE
CSS is not optimized

### ISSUE THREAD

**Issue by MathewBerg** [angular/angular-cli#14379]
# 🐞 bug report

### Affected Package

 Unsure, I'm guessing @angular/core

### Is this a regression?

 No

### Description

 Scss is not optimized. I've created the following:

<pre><code>:host-context(.light) {
  p {
    font-size: 50px;
  }
}
:host-context(.dark) {
  p {
    font-size: 50px;
  }
}</pre></code>

I added `.dark` class to the my-app component and after inspecting the p tag it seems to not of optimized the scss. I see this under inspection: 

`.light[_nghost-c0] p[_ngcontent-c0], .light [_nghost-c0] p[_ngcontent-c0]`

While I'd expect to see:

`.light[_nghost-c0] p[_ngcontent-c0], .light [_nghost-c0] p[_ngcontent-c0],.dark[_nghost-c0] p[_ngcontent-c0], .dark [_nghost-c0] p[_ngcontent-c0]` 

This happens also on `ng build --prod`. When I inspect the generated files I can see that it is duplicated and not optimized.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-7-master-5mbcjg

## 🔥 Exception or Error
N/A

## 🌍  Your Environment

**Angular Version:**
N/A (any)

**Anything else relevant?**

If this should be filed somewhere else please let me know.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [CleanCss ](https://github.com/jakubpawlowicz/clean-css)project or file an issue on their issue tracker.

**Comment by MathewBerg** [comment]
@alan-agius4 I tried clean css and it did optimize. It turned: 

```
.dark p{
    color: blue;
}
.light p{
    color: blue;
}
```

into

`.dark p,.light p{color:#00f}`

But in angular it still keeps it as separate.

**Comment by MathewBerg** [comment]
@alan-agius4 cleancss did optimize it correctly when I had level 2 optimizations turned on. It was able to convert:

`.dark[some-attribute] p[some-attribute]{
	color:#00f;
}
.light[some-attribute] p[some-attribute]{
	color:#00f;
}

.dark p{
	font-size: 50px;
}
.light p{
	font-size: 50px;
}`

into 

`.dark[some-attribute] p[some-attribute],.light[some-attribute] p[some-attribute]{color:#00f}.dark p,.light p{font-size:50px}`

While angular converted it to this:

`.dark[some-attribute][_ngcontent-c24]   p[some-attribute][_ngcontent-c24]{color:#00f}.light[some-attribute][_ngcontent-c24]   p[some-attribute][_ngcontent-c24]{color:#00f}.dark[_ngcontent-c24]   p[_ngcontent-c24]{font-size:50px}.light[_ngcontent-c24]   p[_ngcontent-c24]{font-size:50px}`

**Comment by alan-agius4** [comment]
Hi @MathewBerg, 

The initial report provided different CSS which was not optimized by CleanCss. 

Looking at the above post, it looks like the CSS is being optimised correctly and injected correctly in the DOM. You are seeing `[_ngcontent-c24]` due to the how Angular does style scoping see https://angular.io/guide/component-styles#style-scope for more info

**Comment by MathewBerg** [comment]
@alan-agius4 I'm not sure what you mean, the above is not optimized correctly. Here is the result beautified

```
.dark[some-attribute][_ngcontent-c24] p[some-attribute][_ngcontent-c24] {
	color: #00f
}

.light[some-attribute][_ngcontent-c24] p[some-attribute][_ngcontent-c24] {
	color: #00f
}

.dark[_ngcontent-c24] p[_ngcontent-c24] {
	font-size: 50px
}

.light[_ngcontent-c24] p[_ngcontent-c24] {
	font-size: 50px
}
```

While I would of expected it to look something like this:

```
.dark[some-attribute][_ngcontent-c24] p[some-attribute][_ngcontent-c24],
.light[some-attribute][_ngcontent-c24] p[some-attribute][_ngcontent-c24] {
	color: #00f
}

.dark[_ngcontent-c24] p[_ngcontent-c24],
.light[_ngcontent-c24] p[_ngcontent-c24] {
	font-size: 50px
}
```

**Comment by alan-agius4** [comment]
Hi @MathewBerg, sorry for the back and forth.

I have tried this again and this might be something related to StackBlitz infrastructure. As trying the above code on a local CLI project does yield the expected result.

<img width="317" alt="Screenshot 2019-05-13 at 18 01 28" src="https://user-images.githubusercontent.com/17563226/57636878-5ad04700-75aa-11e9-835d-4e60d6a92bb8.png">

It might be that StackBlitz hasn't update their setup to match our setup and might be that some dependencies are outdated.

//cc @EricSimons

**Comment by alan-agius4** [comment]
Note: the original issue is still reproducible but that is also reproducible via https://jakubpawlowicz.github.io/clean-css/

Ie: 
```css
:host-context(.light) p {
  font-size: 50px;
}
  
:host-context(.dark) p {
   font-size: 50px;
}
```

Is being outputted as 
```css
:host-context(.light) p{font-size:50px}:host-context(.dark) p{font-size:50px}
```
