### ISSUE TITLE
Angular cli prod build (aot) giving -> Illegal state: Could not load the summary for directive

### ISSUE THREAD

**Issue by parky128** [angular/angular-cli#14400]
I am getting the following error when trying to run `npm run build` on my application:

    ERROR in : Illegal state: Could not load the summary for directive ɵangular_packages_forms_forms_bh in /Users/rparker-admin/Documents/Github/my-app/node_modules/@angular/forms/forms.d.ts.

Works fine for `ng serve` so I guess this is aot related.

How can I track this down and resolve?

Thanks

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
