### ISSUE TITLE
ERROR TypeError: intro_js_intro_js__WEBPACK_IMPORTED_MODULE_3___default(...) is not a function. I am facing this issue while i am using intro.js version 1.1.1 in angular 7 typescript file.

### ISSUE THREAD

**Issue by Vishnu4a7** [angular/angular-cli#14409]
Hi All,

I am facing the mentioned issue when i am importing intro.js(third party library) in typescript file of angular 7 project .

imported as intro.js import IntroJs from 'intro.js/intro.js';
declaring as let intro = IntroJs();  //facing issue at this declaration.

Please help me on this.

Thanks in advance.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
