### ISSUE TITLE
[ngx-datatable] Build breaks with build-optimizer flag on

### ISSUE THREAD

**Issue by avijitpsingh** [angular/angular-cli#14401]
<img width="1440" alt="Screen Shot 2019-05-10 at 11 23 43 PM" src="https://user-images.githubusercontent.com/14877118/57546973-478b6480-737b-11e9-8635-621970466948.png">
### Description

We are using "@swimlane/ngx-datatable": "10.0.5" in our application. Everything works with AoT build. But, if you enable build-optimizer(ng build --prod --build-optimizer --sourcemaps=true), bundle files are getting generated, but while running the application it breaks (Attached screenshot)

**Comment by alan-agius4** [comment]
Closing as it doesn’t follow the issue template.
