### ISSUE TITLE
ng serve is making chrome almost un-usable in angularfire2 application

### ISSUE THREAD

**Issue by lbecker34** [angular/angular-cli#1441]
1. Mac OSX (El Capitan)
2. Versions. v4.4.7
3. Repro steps. 
     -Using visual studio code and git.
     -Created an angularfire2 app. 
     - I've added firebase and angularfire2 to my user configuration.
     - I've created three components, none of which are using angularfire2 yet.
     - I've added routing to the components.
     - In main.ts I've imported angularfire2 with FIREBASE_PROVIDERS and defaultFirebase
     - bootstrapped firebase and my appRouterProviders
    
     - use this documentation on setting up angular cli with angularfire2: https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md

4. Error: @http://localhost:4200/system-config.js:45:5
	Call@http://localhost:4200/vendor/es6-shim/es6-shim.js:289:14
	forEach@http://localhost:4200/vendor/es6-shim/es6-shim.js:1295:14
	@http://localhost:4200/system-config.js:44:1
	Zone</ZoneDelegate</ZoneDelegate.prototype.invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:323:20
	Zone</Zone</Zone.prototype.run@http://localhost:4200/vendor/zone.js/dist/zone.js:216:25
	scheduleResolveOrReject/<@http://localhost:4200/vendor/zone.js/dist/zone.js:571:53
	Zone</ZoneDelegate</ZoneDelegate.prototype.invokeTask@http://localhost:4200/vendor/zone.js/dist/zone.js:356:24
	Zone</Zone</Zone.prototype.runTask@http://localhost:4200/vendor/zone.js/dist/zone.js:256:29
	drainMicroTaskQueue@http://localhost:4200/vendor/zone.js/dist/zone.js:474:26
	ZoneTask/this.invoke@http://localhost:4200/vendor/zone.js/dist/zone.js:426:22
	
	Evaluating http://localhost:4200/system-config.js
	Error loading http://localhost:4200/system-config.js zone.js

5. Sometimes ng serve works and I'm able to pull up the app on localhost:4200. Most of the time if I try to pull it up on localhost:4200 it completely locks down chrome. I haven't been able to pin point exactly what makes it work and what makes it not work. Chrome instantly takes up 100% cpu in activity monitor after opening up localhost:4200.

**Comment by lbecker34** [comment]
An update: when using Firefox, I can watch all of the .js files load very slowly one by one. App compilation seems to be the issue. It eventually loads and I'm able to use my application as expected, so it doesn't seem to be a problem with my code. I've also added an error above that I receive when I refresh the page.

**Comment by filipesilva** [comment]
Closed as this issue was made obsolete by https://github.com/angular/angular-cli/pull/1455.
