### ISSUE TITLE
Is there any planed date to make angular 8.0.0 as stable version

### ISSUE THREAD

**Issue by kamalrajora** [angular/angular-cli#14428]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

We are planing to upgrade from angular 7 to 8 version. Is there any planed date for stable angular 8 version ?
https://github.com/angular/angular-cli/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by skreborn** [comment]
This is not the proper channel to be asking questions. The issue tracker is strictly for what it name clearly implies. Please refer to [Got a Question or Problem?](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for more information.
