### ISSUE TITLE
Display line numbers for errors.

### ISSUE THREAD

**Issue by pauldraper** [angular/angular-cli#14425]
Angular frequently provides errors that are hard to figure out the location.

It will say 

```
ERROR in : Can't bind to 'padding' since it isn't a known property of 'card'. ("
```

and them I will search and search for where it could be coming from.

Rather, Angular should show the line number that the error happens in. Because this is what all other compilers everywhere do.

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this however this seems to be a compiler issue and such issues should be logged here https://github.com/angular/angular

Thanks.
