### ISSUE TITLE
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/angular-cli#14439]
Hello I am using below angular version 

ng build --prod is not working for  me. can you help how to fix this issue

Error

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\gazala\Desktop\GCDB_New_Workspace\GCDB6-Portal\src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts

------------------------------------------------
@angular/cli: 1.0.0-rc.0
node: 8.11.4
os: win32 x64
@angular/common: 2.4.10
@angular/compiler: 2.4.10
@angular/core: 2.4.10
@angular/forms: 2.4.10
@angular/http: 2.4.10
@angular/platform-browser: 2.4.10
@angular/platform-browser-dynamic: 2.4.10
@angular/router: 3.4.10
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 2.4.10

**Comment by alan-agius4** [comment]
Hi, @angular/cli version 1.0.0-rc.0 is no longer supported.

Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by Gajendrasinh** [comment]
I have updated version cli 1.7.4, can this version support ng build --prod,

Expected behavior : ng build --prod  need to work and generate dist folder,

current behavior :  build fail with below error : 

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\gazala\Desktop\GCDB_New_Workspace\GCDB6-Portal\src'
 @ ./src/main.ts 5:0-74
 @ multi ./src/main.ts


Angular CLI: 1.7.4
Node: 8.11.4
OS: win32 x64
Angular: 2.4.10
... common, compiler, compiler-cli, core, forms, http
... platform-browser, platform-browser-dynamic

@angular/cli: 1.7.4
@angular/router: 3.4.10
@angular/tsc-wrapped: 0.5.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.9.2
webpack: 3.11.0
