### ISSUE TITLE
Can't load bootstrapp

### ISSUE THREAD

**Issue by folivi** [angular/angular-cli#14438]
# 🐞 Bug report

```
- [ x] serve
```

Failed to compile

7

### Description

Application fails to load "node_modules/bootstrap/dist/js/bootstrap.min.js"

## 🔬 Minimal Reproduction
Generate a new project with  "angular-cli": "1.0.0-beta.28.3",

npm i --save bootstrap

add node_modules/bootstrap/dist/js/bootstrap.min.js to the scripts in the angular-cli.json

ng serve

You see the following error:

```ERROR in multi script-loader!./src/~/bootstrap/dist/js/bootstrap.min.js ```

**Comment by alan-agius4** [comment]
Hi, @angular/cli version 1.0.0-beta.28.3 is no longer supported.

Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by folivi** [comment]
My bad.
I installed angular cli by typing npm i -g angular-cli which installs 1.0.0-beta.28.3
