### ISSUE TITLE
ng install

### ISSUE THREAD

**Issue by muscaiu** [angular/angular-cli#1443]
Windows 10
angular-cli: 1.0.0-beta.10
node: 5.10.0
os: win32 x64

Installed fresh project with ng new testcli to test the ng-install option that i just noticed on help.

I tried the following commands: 
- ng install firebase
- ng install angularfire2
- ng install angular2-material

I get the same Output: 
The package @angular/common@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!

Is ng install working for anyone or is broken because it's beta?

**Comment by filipesilva** [comment]
There is no `ng install` per se, it's part of ember's addon functionality that doesn't really do much in Angular-CLI.

We once had an `ng install` command that did what you're looking for, but pulled it out because it was mostly reproducing npm behaviour and it was better overall to just use npm.

**Comment by muscaiu** [comment]
What i was hoping for in `ng install` was the automatic adding of all that crap from `angular-cli-build.js`, and specially from `system.config.ts`, which is a total pain for every library that i try to add.  

Something like Meteor and Ionic have and they don't just reproduce npm behaviour. 
I would love to just do `ng install angular2-material` and just use it with no extra pain :)
