### ISSUE TITLE
allowSyntheticDefaultImports/esModuleInterop enabled causes issues with build optimizer in webpack

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular-cli#14442]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

No

### Description

 A clear and concise description of the problem...
I'm building Angular with the latest webpack and for production builds we use `@angular-devkit/build-optimizer/webpack-loader`. Today when I enabled `allowSyntheticDefaultImports `and `esModuleInterop` in my tsconfig I get the following runtime error:
```
vendor.a9bcc57803e630b13a15.js:319 ERROR TypeError: Cannot set property 'component' of undefined
```

## 🔬 Minimal Reproduction
Let me know if you guys can't reproduce and I set up an example whenever I have time.
I'm using ts-node and build with this command:
`webpack --config config/webpack.prod.ts --bail`

From webpack.prod.ts:
```
{
    test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
    use: [
        {
            loader: '@angular-devkit/build-optimizer/webpack-loader',
            options: {
                sourceMap: useSourcemaps
            }
        },
        '@ngtools/webpack'
    ]
},
```

## 🔥 Exception or Error
<pre><code>
vendor.a9bcc57803e630b13a15.js:319 ERROR TypeError: Cannot set property 'component' of undefined
    at initView (vendor.a9bcc57803e630b13a15.js:1019)
    at createViewNodes (vendor.a9bcc57803e630b13a15.js:1019)
    at Object.createEmbeddedView (vendor.a9bcc57803e630b13a15.js:1019)
    at TemplateRef_.createEmbeddedView (vendor.a9bcc57803e630b13a15.js:775)
    at ViewContainerRef_.createEmbeddedView (vendor.a9bcc57803e630b13a15.js:775)
    at vendor.a9bcc57803e630b13a15.js:1202
    at DefaultIterableDiffer.forEachOperation (vendor.a9bcc57803e630b13a15.js:724)
    at NgForOf._applyChanges (vendor.a9bcc57803e630b13a15.js:1202)
    at NgForOf.ngDoCheck (vendor.a9bcc57803e630b13a15.js:1202)
    at checkAndUpdateDirectiveInline (vendor.a9bcc57803e630b13a15.js:1019)

</code></pre>

## 🌍 Your Environment
<pre><code>
@angular/*: 8.0.0-rc.4
@angular/cdk: 8.0.0-rc.1
@angular/material: 8.0.0-rc.1
@angular/http: 8.0.0-beta.10
@angular-devkit/build-optimizer: 0.800.0-rc.4
rxjs: 6.5.2
ts-node: 8.1.0
typescript: 3.4.5
webpack: 4.31.0
webpack-cli: 3.3.2
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by JonWallsten** [comment]
I'll do my best. But it's a complex monorepo. Will take some times to mimic the repo structure and get strip away all the buils tools. Are there any other options?

**Comment by alan-agius4** [comment]
You can try to use `ng new repro-app`

**Comment by JonWallsten** [comment]
@alan-agius4 I managed to recreate the issue with only a few of our components and no sensitive data. Still, I created a private repo just in case, and made you a collaborator: https://github.com/JonWallsten/angular-devkit-bug
Let me know if it doesn't work.

1. npm i
2. npm run serve:build
3. http://localhost:8888

**Comment by alan-agius4** [comment]
Hi @JonWallsten,

Thanks for the reproduction. Seeing the webpack config, the issue seems to be that you are using build-optimizer on ts files


Build optimizer should be using on js files

Can you try the below?
```js
 {
  test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
  use: [
    '@ngtools/webpack'
  ],
  include: helpers.includeTS
},
{
  test: /\.js$/,
  use: [
    {
      loader: '@angular-devkit/build-optimizer/webpack-loader',
      options: {
        sourceMap: useSourcemaps
      }
    },
  ],
},
```

**Comment by JonWallsten** [comment]
@alan-agius4: Thanks! That did the trick! :thumbsup:
