### ISSUE TITLE
Angular Router not working on AWS Server

### ISSUE THREAD

**Issue by WarienX** [angular/angular-cli#14447]
Hello, I am having issue opening Angular Route in AWS Server. 
for e.g https://localhost:4200/home not opening on AWS Server on page Refresh. I have attached an image below
![url error](https://user-images.githubusercontent.com/26925053/57855734-0080f180-7809-11e9-850e-0e944199e1d3.PNG)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
