### ISSUE TITLE
Rollup config error on dynamic import during library build

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular-cli#14444]
# 🐞 Bug report
```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description

Consider building `foo`  library with the command `ng build foo`.
When the library contains a file (service in my case), which uses dynamic import, the build will fail throwing error below. This happens in v7 and also after upgrading to v8.0.0-rc.4

## 🔬 Minimal Reproduction
1. Create a new project. Generate library `ng g library foo`. 
2. Create a service in the library that is using dynamic imports. (example screenshot below)
3. Export service in `public-api.ts`
4. Build library with `ng build shared`
![Capture](https://user-images.githubusercontent.com/11920691/57850973-a9b2f200-77df-11e9-8d2d-39be63451322.PNG)

## 🔥 Exception or Error
<pre><code>

Building Angular Package
Building entry point 'testik'
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
You must set "output.dir" instead of "output.file" when generating multiple chunks.
Error: You must set "output.dir" instead of "output.file" when generating multiple chunks.
    at error (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:3410:30)
    at normalizeOutputOptions (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:17107:13)
    at getOutputOptions (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:16865:24)
    at Object.write (c:\Development\rollup-test\node_modules\rollup\dist\rollup.js:16957:43)
    at Object.<anonymous> (c:\Development\rollup-test\node_modules\ng-packagr\lib\flatten\rollup.js:46:22)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Development\rollup-test\node_modules\ng-packagr\lib\flatten\rollup.js:4:58)

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 10.15.0
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0-rc.4
@angular-devkit/build-angular      0.800.0-rc.4
@angular-devkit/build-ng-packagr   0.800.0-rc.4
@angular-devkit/build-optimizer    0.800.0-rc.4
@angular-devkit/build-webpack      0.800.0-rc.4
@angular-devkit/core               8.0.0-rc.4
@angular-devkit/schematics         8.0.0-rc.4
@angular/cdk                       8.0.0-rc.1
@angular/flex-layout               7.0.0-beta.24
@angular/material                  8.0.0-rc.1
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0-rc.4
@schematics/angular                8.0.0-rc.4
@schematics/update                 0.800.0-rc.4
ng-packagr                         5.1.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [ng-packagr](https://github.com/ng-packagr/ng-packagr) project or file an issue on their issue tracker. 

Note: at the moment this is not supported by ng-packagr.
