### ISSUE TITLE
a path configured in tsconfig.json dosen't work in ./server.ts in Angular universal mode

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular-cli#14456]
I have created an Agular library and puts its path to paths array in tsconfig.json
note that this path refers to 'src' of the library, not 'dist' folder

tsconfig.json:
```
    "paths": {
      "*": ["node_modules/*", "src/types/*"],
      "myLib": ["projects/myLib/src/public-api"],
      "myLib/*": ["projects/myLib/src/lib/*"]
    }
```

server.ts
```
import { example } from "myLib" //cannot resolve myLib, although when I click in this module in my IDE it directly open the correct path i.e public-api.ts file
import { example } from "projects/myLib/src/public-api" //works!
```

**Comment by alan-agius4** [comment]
Hi, most likely you have a ‘baseUrl` In your `tsconfig.server.json`

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
