### ISSUE TITLE
Exception thrown in prod builds probably due to mangling/minification: Template parse errors: Can't bind to 'routerLink' since it isn't a known native property

### ISSUE THREAD

**Issue by balteo** [angular/angular-cli#1446]
- OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

> Max OSX EL Capitan.

  -  Versions:

> angular-cli: 1.0.0-beta.10
> node: 4.4.5
> os: darwin x64

  -  Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc. 

> I just compile my app with the `-prod` switch as follows: `ng build -prod`

 -  The log given by the failure. Normally this include a stack trace and some
   more information.

> Template parse errors: Can't bind to 'routerLink' since it isn't a known native property

  -  Mention any other details that might be useful: I suspect something is **wrong with the minification process** as I don't get any such issue in the `dev` environment. Where is the build process configured anyway in an ng CLI app?

Question opened on SO that describes the issue: http://stackoverflow.com/questions/38577248/

**Comment by balteo** [comment]
Can someone please advise how **to turn off mangling/minification** for **prod** environment builds? The above issue is blocking for me. I need to run an app that has been compiled with the `-prod` switch...

**Comment by filipesilva** [comment]
Closed as this PR was made obsolete by https://github.com/angular/angular-cli/pull/1455.

**Comment by filipesilva** [comment]
#1455 drastically changed our build process. Can you test this again on the upcoming webpack release?

**Comment by balteo** [comment]
I will definitely do so. Thanks.
