### ISSUE TITLE
Provide `outputHashing` option hashing only chunk and script

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular-cli#14463]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 

I have some raw html files for OGP(Open Graph Protocol), not generating by angular.
these raw html files include css file extracted by Angular-CLI such as  `<link href="/static/styles.css" rel="stylesheet" />` to match the look and style with template generated by Angular.
to share hashed css file generated by `ng build --prod`, I must manually modify link tag in raw html files...

now `outputHashing` has 4 options.
so, I need 5th option hashing only chunk and script.

### Describe the solution you'd like

for example, option`scripts` having only chunk and script hash.

```javascript
const hashFormats: { [option: string]: HashFormat } = {
    none:    { chunk: '',                       extract: '',                         file: ''                 , script: '' },
    media:   { chunk: '',                       extract: '',                         file: `.[hash:${length}]`, script: ''  },
    bundles: { chunk: `.[chunkhash:${length}]`, extract: `.[contenthash:${length}]`, file: ''                 , script: `.[hash:${length}]`  },
    all:     { chunk: `.[chunkhash:${length}]`, extract: `.[contenthash:${length}]`, file: `.[hash:${length}]`, script: `.[hash:${length}]`  },
    scripts: { chunk: `.[chunkhash:${length}]`, extract: '',                         file: ''                 , script: `.[hash:${length}]`  },
  };
```

### Describe alternatives you've considered
 
quit preset option. can arbitrarily indicate by key map object.

in angular.json
```json
"outputHashing": {"chunk": true, "extract": false, "file": false, "script": true}
```

**Comment by 0x018** [comment]
+1

**Comment by alan-agius4** [comment]
Hi @studioTeaTwo, 

Thanks for this feature request. 

This feature at the moment doesn't fall in the Angular CLI roadmap. Let's re-consider this in the future if there is a bigger demand for this.
