### ISSUE TITLE
Code generated for webWorker in incorrect file

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular-cli#14467]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Not Sure

### Description

 A clear and concise description of the problem...

Create a new app with routing as Yes
run "ng g webWorker app"

webWorker code is added to app-routing.module.ts file

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

  "@angular/cli": "~8.0.0-rc.3",
"@angular/common": "~8.0.0-rc.4",
</code></pre>

**Anything else relevant?**

**Comment by santoshyadav198613** [comment]
Hi Everyone, I Will raise the PR for this issue.

**Comment by filipesilva** [comment]
Thanks for reporting this @santoshyadav198613, we'll try to fix this before 8 final!

**Comment by santoshyadav198613** [comment]
Thanks, @filipesilva , i have opened the PR let me know if it is correct, I will get the comments addressed today.
