### ISSUE TITLE
installation issue when hyphen added in app name

### ISSUE THREAD

**Issue by rameezrami** [angular/angular-cli#14465]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, in previous versions 
### Description

 A clear and concise description of the problem...
I cant create apps with hyphen included in the name.. please check the attached gif to get a clear understanding.

![angular-install-issue](https://user-images.githubusercontent.com/7924562/57978984-859c1e80-7a34-11e9-98ba-cb304020d600.gif)

## 🔥 Exception or Error
<pre><code>
ng new angular-7-realworld-starter 
</code></pre>

does not works but 

<pre><code>
ng new dsadsd
</code></pre>

works
## Versions
<pre><code>
ubuntu 18
</code></pre>
<pre><code>
$ node --version
v10.15.3
</code></pre>
<pre><code>
$ npm --version
6.4.1
</code></pre>
<pre><code>
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 10.15.3
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.9
@angular-devkit/core         7.3.9
@angular-devkit/schematics   7.3.9
@schematics/angular          7.3.9
@schematics/update           0.13.9
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Comment by alan-agius4** [comment]
Hi, the problem is not the hyphen but the number.

This was not supported in version 7, however it is now supported in version 8.
