### ISSUE TITLE
I have a angular html string with *ngIf & *ngFor response. And how to show it in angular 6.

### ISSUE THREAD

**Issue by JaiKumaresh** [angular/angular-cli#14477]
I have a service response(HTML) like that,
`<div *ngIf="text">{{text}}</div>`
How to show it. angular 1 user $compiler but I not know lastest version.
So plz help.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
