### ISSUE TITLE
ng g component always creates a new directory with the same name as the component.

### ISSUE THREAD

**Issue by jbeckton** [angular/angular-cli#1448]
> Please provide us with the following information:
> ---------------------------------------------------------------
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX (El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please
   run in a Terminal: 
        node --version
   And paste the result here.

angular-cli: 1.0.0-beta.10
node: 6.3.1
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

generated app with the CLI tool.

every time I run ng g component my-ComponentName it generates a new directory. I do not always want a directory per component.

**Comment by filipesilva** [comment]
That is the intended default behaviour. You can use the `-- flat` flag to not create this folder though.

**Comment by tsq** [comment]
<img width="919" alt="screen shot 2019-02-11 at 22 33 32" src="https://user-images.githubusercontent.com/6081537/52566523-51b9c780-2e4d-11e9-9943-c1aa8f2019e5.png">

it's `--flat` *there is no space* 

e.g `ng g c login --flat`
