### ISSUE TITLE
ng build hangs with yarn, with no clue, on Docker

### ISSUE THREAD

**Issue by TcaManager** [angular/angular-cli#14485]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ *] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't know if it's a regression, I'm a angular noob

### Description

When using the following commands on a Docker image, I get the following output and then nothing happens, for hours. I'm behind a proxy, using Yarn and ng, the ng build command is where I get stuck.
```
## Compilation des sources
RUN ng build --watch --configuration=marathon --buildOptimizer=false --output-path=/usr/src/frontend/dist


```
Output:
> Step 23/28 : RUN ng build --watch --configuration=marathon --buildOptimizer=false --output-path=/usr/src/frontend/dist
 > ---> Running in 4e58d0df856d

> Date: 2019-05-21T11:32:55.101Z
> Hash: 0e3dd2f017eadb83484a
> Time: 53505ms
> chunk {0} runtime.2f29e12616932f0ed037.js (runtime) 1.42 kB [entry] [rendered]
> chunk {1} es2015-polyfills.e0376bb9d8eea7d6dd94.js (es2015-polyfills) 56.4 kB [initial] [rendered]
> chunk {2} main.0aec5a6765d0c732387a.js (main) 1.41 MB [initial] [rendered]
> chunk {3} polyfills.662dc2e433e4f8493fad.js (polyfills) 41.2 kB [initial] [rendered]
> chunk {4} styles.5a0089e0c62ddb4df4d1.css (styles) 71.4 kB [initial] [rendered]

## 🔬 Minimal Reproduction

This is the complete DockerFile used.

```

### STAGE 1: Node Build ###

# We label our stage as ‘builder’
FROM node:latest as builder


ENV HTTP_PROXY http://proxy-rie.http.insee.fr:8080
ENV HTTPS_PROXY http://proxy-rie.http.insee.fr:8080
ENV NO_PROXY ".insee.test,.insee.eu,.insee.fr,.intra,.mesos,.thisdcos.directory,.dcos.directory,.zk,127.0.0.1,localhost"

RUN echo 'http_proxy = http://proxy-rie.http.insee.fr:8080' >> /etc/wgetrc
RUN echo 'https_proxy = http://proxy-rie.http.insee.fr:8080' >> /etc/wgetrc
RUN echo 'use_proxy = on' >> /etc/wgetrc

RUN echo 'Acquire::http::Proxy "http://proxy-rie.http.insee.fr:8080";' >> /etc/apt/apt.conf && \
    apt-get update -y && \
    apt-get upgrade -y

RUN yarn config set strict-ssl false
RUN yarn config set registry https://nexus.beta.innovation.insee.eu/repository/npm-public/

COPY package.json yarn.lock ./

## Configuration de Yarn pour ne pas avoir à modifier le PATH
RUN yarn config set prefix /usr/local

## Installation des dépendances pénibles d'Angular
RUN yarn global add node-gyp
RUN mkdir /usr/local/node-sass
RUN wget -P /usr/local/node-sass https://github.com/sass/node-sass/releases/download/v4.12.0/linux-x64-72_binding.node
ENV SASS_BINARY_PATH /usr/local/node-sass/linux-x64-72_binding.node

## Installation d'Angular
RUN yarn global add @angular/cli

## Import des sources dans l'image Docker
RUN mkdir /usr/src/frontend
WORKDIR /usr/src/frontend
COPY . .

## Config du projet pour utiliser Yarn avec Angular
RUN ng config -g cli.packageManager yarn

## Installation des dépendances et compilation
RUN yarn

## Compilation des sources
RUN ng build --watch --configuration=marathon --buildOptimizer=false --output-path=/usr/src/frontend/dist

```

## 🔥 Exception or Error
<pre>
No error, but I don't see the vendor part in compilation, is it the problem? Did I do something wrong?
</pre>

## 🌍 Your Environment
<pre>
Yarn installs the latest version of angular cli
</pre>

**Anything else relevant?**
I had a lot of problems with node-sass, so I installed a local binary and it fixed the problem.

**Comment by TcaManager** [comment]
To reproduce, you have to remove proxy settings and copy the DockerFile, then run it with Docker.

**Comment by alan-agius4** [comment]
Hi, you are using `build` with the `watch` option. Which means that the process will never complete, as it keep a watcher open waiting for file changes.

If you want to run a build that completes after the first run you should remove the `--watch`.

I am going to mark this as resolved as this seems to be a support request. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
