### ISSUE TITLE
RealWorld Angular App w/ ng update fails to update @angular-devkit/core 8.0

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#14489]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
- [x] serve
```

### Is this a regression?
Yes

### Description
It looks like an ng-update fails to update @angular-devkit/core in this project, resulting in build/serve errors after the upate.

Build fails with the error `this._architect.scheduleTarget is not a function`.

## 🔬 Minimal Reproduction
```
git clone git@github.com:gothinkster/angular-realworld-example-app.git
cd angular-realworld-example-app
ng  update @angular/core @angular/cli --next
ng build
```

## 🔥 Exception or Error
<pre><code>

```
$ ng build
this._architect.scheduleTarget is not a function
TypeError: this._architect.scheduleTarget is not a function
    at BuildCommand.runSingleTarget (/usr/local/google/home/stephenfluin/workspace/test/angular-realworld-example-app/node_modules/@angular/cli/models/architect-command.js:193:47)
    at async BuildCommand.runArchitectTarget (/usr/local/google/home/stephenfluin/workspace/test/angular-realworld-example-app/node_modules/@angular/cli/models/architect-command.js:216:24)
    at async BuildCommand.validateAndRun (/usr/local/google/home/stephenfluin/workspace/test/angular-realworld-example-app/node_modules/@angular/cli/models/command.js:137:28)
    at async Object.runCommand (/usr/local/google/home/stephenfluin/workspace/test/angular-realworld-example-app/node_modules/@angular/cli/models/command-runner.js:178:24)
    at async default_1 (/usr/local/google/home/stephenfluin/workspace/test/angular-realworld-example-app/node_modules/@angular/cli/lib/cli/index.js:32:31)
```
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 12.2.0
OS: linux x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              0.6.8
@angular-devkit/schematics        8.0.0-rc.4
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

## Workaround
Manually updating @angular-devkit/core fixes this problem.

**Comment by clydin** [comment]
I am unable to reproduce the issue both with and without a yarn install prior to the ng update.  Without a yarn install after the clone, the global version of the CLI will perform the update.  Could you provide the global version installed at that time?

However, it does appear that `@angular-devkit/core` is erroneously present as a direct dependency of the application: https://github.com/gothinkster/angular-realworld-example-app/blob/master/package.json#L18

Before the update, the following is the list of `@angular-devkit/core` instances within node modules:
```yarn list v1.16.0
├─ @angular-devkit/architect@0.13.1
│  └─ @angular-devkit/core@7.3.1
├─ @angular-devkit/build-angular@0.13.1
│  └─ @angular-devkit/core@7.3.1
├─ @angular-devkit/build-webpack@0.13.1
│  └─ @angular-devkit/core@7.3.1
├─ @angular-devkit/core@0.6.8
├─ @angular-devkit/schematics@7.3.1
│  └─ @angular-devkit/core@7.3.1
├─ @angular/cli@7.3.1
│  └─ @angular-devkit/core@7.3.1
├─ @ngtools/webpack@7.3.1
│  └─ @angular-devkit/core@7.3.1
├─ @schematics/angular@7.3.1
│  └─ @angular-devkit/core@7.3.1
└─ @schematics/update@0.13.1
   └─ @angular-devkit/core@7.3.1
```
By removing the extra `@angular-devkit/core` dependency, yarn outputs the following list:
```
yarn list v1.16.0
└─ @angular-devkit/core@7.3.1
``` 
All the CLI related packages contain their own direct dependency on `@angular-devkit/core`.  It should not be installed directly unless the project itself is directly using it.  However, in that scenario the project is depending on the public API of the core package and updating it without explicit instructions can cause a broken project.

After an update via the command show above, yarn lists the following:
```
yarn list v1.16.0
├─ @angular-devkit/architect@0.800.0-rc.4
│  └─ @angular-devkit/core@8.0.0-rc.4
├─ @angular-devkit/build-angular@0.800.0-rc.4
│  └─ @angular-devkit/core@8.0.0-rc.4
├─ @angular-devkit/build-webpack@0.800.0-rc.4
│  └─ @angular-devkit/core@8.0.0-rc.4
├─ @angular-devkit/core@0.6.8
├─ @angular-devkit/schematics@8.0.0-rc.4
│  └─ @angular-devkit/core@8.0.0-rc.4
├─ @angular/cli@8.0.0-rc.4
│  └─ @angular-devkit/core@8.0.0-rc.4
├─ @ngtools/webpack@8.0.0-rc.4
│  └─ @angular-devkit/core@8.0.0-rc.4
├─ @schematics/angular@8.0.0-rc.4
│  └─ @angular-devkit/core@8.0.0-rc.4
└─ @schematics/update@0.800.0-rc.4
   └─ @angular-devkit/core@8.0.0-rc.4
```
There is also only one `@angular-devkit/architect` installed:
```
yarn list v1.16.0
└─ @angular-devkit/architect@0.800.0-rc.4
```

**Comment by filipesilva** [comment]
@StephenFluin can you provide a commit after the update? That should give us a file lock using the problematic dependencies. Yarn version would also help.

**Comment by StephenFluin** [comment]
https://github.com/StephenFluin/angular-realworld-example-app/commit/fbbfb2b1365dbaabff6d8f14a8754f9b48a6922a commit after update.

Yarn version v1.16.0

Global CLI 8.0.0-rc.4

We can call this mystery solved if the developer added a dependency on core mistakenly, it definitely becomes a nice to have.

**Comment by alan-agius4** [comment]
Hi, I have also tried this myself, and I was unable to replicate it. I even tried doing a `yarn install` prior to updating but I always ended up having a successful build.

**Comment by StephenFluin** [comment]
Closing until we have a better reproduction.

**Comment by walterspieler** [comment]
I experienced the same issue on my CI. I was using NPM on local and yarn for the CI. Switching to NPM instead of yarn on the CI solved the issue. 
The issue might come from package-lock.json and using two different package managers.

**Comment by Axure** [comment]
I encountered the same error. The problem is exactly from the `@angular-devkit/core` package in `package.json`. Running `yarn remove @angular-devkit/core` fixed it for me.

**Comment by milesstanfield** [comment]
same issue `this._architect.scheduleTarget is not a function`
