### ISSUE TITLE
--progress=false flag not working

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular-cli#14498]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
does not work in latest v7 and next v8rc4

### Description
`--progress=false` flag does not work.

## 🔬 Minimal Reproduction
run in your project `ng build --progress=false`
According to docs `--progress=true\|false | Log progress to the console while building.` 
However setting to false does not prevent the  pollution in command line.

![ngbuild](https://user-images.githubusercontent.com/11920691/58163007-7f4fb180-7c83-11e9-8a9c-a15635914562.gif)

## 🌍 Your Environment
<pre><code>
OS: win32 x64
Angular: 8.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0-rc.4
@angular-devkit/build-angular      0.800.0-rc.4
@angular-devkit/build-ng-packagr   0.800.0-rc.4
@angular-devkit/build-optimizer    0.800.0-rc.4
@angular-devkit/build-webpack      0.800.0-rc.4
@angular-devkit/core               8.0.0-rc.4
@angular-devkit/schematics         8.0.0-rc.4
@angular/cdk                       8.0.0-rc.1
@angular/flex-layout               7.0.0-beta.24
@angular/material                  8.0.0-rc.1
@angular/pwa                       0.12.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0-rc.4
@schematics/angular                8.0.0-rc.4
@schematics/update                 0.800.0-rc.4
ng-packagr                         5.1.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Anything else relevant?**
running on windows 10

**Comment by alan-agius4** [comment]
From the super fast logs it doesn't seem to be related to progress. But rather TypeScript trace option.

By any chance do you have `trace` enabled in one of your tsconfigs?

**Comment by GeorgeKnap** [comment]
> From the super fast logs it doesn't seem to be related to progress. But rather TypeScript trace option.
> 
> By any chance do you have `trace` enabled in one of your tsconfigs? If it's enable you should remove it.

I just checked. It's not explicitly defined in any of tsconfigs.

**Comment by alan-agius4** [comment]
Apologies, just noticed the option is not `trace` but `traceResolution`. 
I am only able to replicate the above when using the option.

**Comment by GeorgeKnap** [comment]
> Apologies, just noticed the option is not `trace` but `traceResolution`.
> I am only able to replicate the above when using the option.
@alan-agius4   Indeed I had the `traceResolution` enabled. Must have been there since earlier versions I guess. Removing it helps! Thank you for the solution.
