### ISSUE TITLE
`ng version` should report if you are opted into the Ivy preview

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#14491]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] version
```

### Description
It will be important to know if developers are using Ivy or not when debugging and reproducing issues.

### Describe the solution you'd like
`ng version` should show if the user has opted into the Ivy preview or not.

**Comment by alan-agius4** [comment]
Not sure how this fits in `ng version` since Ivy opt-in is not related to the package version and is project specific not a global flag.

Ie, in a work space one application be compiled using Ivy and another might be using VE.

**Comment by alan-agius4** [comment]
Also, it might be the case that `ng test` run using the VE compiler while `ng build` and `ng serve` using the Ivy compiler. The actual opt-in guide only states how to opt-in for `build` and `serve`, however users can still opt-in to use Ivy in `tests`

**Comment by StephenFluin** [comment]
Makes sense. Perhaps instead we could inform users whenever we do an Ivy compilation instead of a ViewEngine compilation with a log message?

I'd be happy to close this if I'm off base, but I want to make sure developers know what's going on, if for example, another developer on their team opts them into the preview.

**Comment by alan-agius4** [comment]
Yeah I think printing a message makes total sense.
