### ISSUE TITLE
angular with sass not getting compiled in angular V 8.0.0 rc4

### ISSUE THREAD

**Issue by Saranya13** [angular/angular-cli#14497]
I have created angular sample with sass compilation, **Using angular/cli v8.0.0-rc.4**.

### while running this sample, below issue occurs.

**Error message:**
ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--13-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

undefined
 ^
      Top-level selectors may not contain the parent selector "&".
    ╷
219 │ ┌   &.e-bigger .e-switch-wrapper,
220 │ │   &.e-bigger.e-switch-wrapper,
221 │ │   &.e-bigger .e-css.e-switch-wrapper,
222 │ │   &.e-bigger.e-css.e-switch-wrapper {
    │ └────────────────────────────────────^

**Screenshot**
![sass](https://user-images.githubusercontent.com/38315832/58155604-d066a200-7c91-11e9-953f-fad05afed8d0.png)

**My package.json file**
![angular-version](https://user-images.githubusercontent.com/38315832/58155642-e7a58f80-7c91-11e9-9ac0-525bbb4d55f1.png)

### Repo steps:

- download my sample - http://www.syncfusion.com/downloads/support/directtrac/general/ze/angular-with-sass1398210175.zip
- then run "npm run start"

**Comment by alan-agius4** [comment]
Hi, in version 8, we moved away from `node-sass` in favor of `sass` and it has some differences. The main once being https://www.npmjs.com/package/sass#behavioral-differences-from-ruby-sass

From `sass` point of view, this code pattern is considered as a mistake in coding and should produce and error. See: https://github.com/sass/sass/issues/1873

Nonetheless you have the option to use opt-in and use `node-sass` if you manually install it using the below:

```
npm install node-sass --save-dev
```

**Comment by Saranya13** [comment]
As per your answer, can i have to install 

> npm install node-sass --save-dev

Then this issue will get resolved, is it?

**Comment by alan-agius4** [comment]
@Saranya13, Ideally you raise this issue with the library authors of `@syncfusion` as their code is not compatible with `sass`

**Comment by Saranya13** [comment]
HI @alan-agius4 ,

I have checked with them already, but only in latest angular throws this error

how can i raise question to them?

**Comment by alan-agius4** [comment]
Because the error is thrown by [sass](https://www.npmjs.com/package/sass), which Angular CLI uses to build `sass` instead of [node-sass](https://www.npmjs.com/package/node-sass).

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Thanks for your reply
