### ISSUE TITLE
Host should not return a redirect source file from `getSourceFile`

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular-cli#14515]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

Yes and No

### Description

When building the project in watch mode any subsequent  build after the first one generates this error: 
```
ERROR in Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
```

The reason seems to be that TypeScript has a way of identifying identical type definition files from different paths and adds something called redirectInfo. Since TS 2.8 (i think) the compiler throws an error when you add the original file instead instead of it's redirect target, so the build fails.
This is happening in both Angular 7 and when using Ivy in Angular 8.

```
console.log(sf.fileName);
console.log(sf['redirectInfo'].redirectTarget.fileName);
--------------------------
C:/Users/me/repo/web-app-angular/node_modules/@types/webpack/node_modules/source-map/source-map.d.ts
C:/Users/me/repo/web-app-angular/node_modules/@types/uglify-js/node_modules/source-map/source-map.d.ts
--------------------------
```

Source of the problem:
angular/packages/compiler-cli/src/transformers/program.ts
```
tmpProgram.getSourceFiles().forEach(sf => {
    if (this.hostAdapter.isSourceFile(sf.fileName)) {
    	sourceFiles.push(sf.fileName); <!-- When adding a file with a redirectTarget we get an error later on
    }
    if (TS.test(sf.fileName) && !DTS.test(sf.fileName)) {
        tsFiles.push(sf.fileName);
    }
});
```
Possible fix:
```
tmpProgram.getSourceFiles().forEach(sf => {
    if (this.hostAdapter.isSourceFile(sf.fileName)) {
    	// Not sure why there isn't defintions for this
    	if ((sf as any)['redirectInfo']) {
         	sf = (sf as any)['redirectInfo'].redirectTarget;
      	}
    	sourceFiles.push(sf.fileName);
    }
    if (TS.test(sf.fileName) && !DTS.test(sf.fileName)) {
        tsFiles.push(sf.fileName);
    }
});
```

This also happens in:
angular/packages/compiler-cli/src/ngtsc/typecheck/src/context.ts
```
for (const originalSf of originalProgram.getSourceFiles()) {
    const sf = this.transform(originalSf);
    sfMap.set(sf.fileName, sf);
    if (!sf.isDeclarationFile && this.opMap.has(originalSf)) {
        interestingFiles.push(sf);
    }
}
```
Can be fixed by the same strategy:
```
for (const originalSf of originalProgram.getSourceFiles()) {
    const sf = this.transform(originalSf);
	if ((sf as any)['redirectInfo']) {
     	sf = (sf as any)['redirectInfo'].redirectTarget;
  	}
    sfMap.set(sf.fileName, sf);
    if (!sf.isDeclarationFile && this.opMap.has(originalSf)) {
        interestingFiles.push(sf);
    }
}
```

## 🔬 Minimal Reproduction
1. npm i
2. npm run dev
3. Go to http://localhost:8888
4. Change any source code to trigger the watcher to rebuild
5. Profit!
-->

## 🔥 Exception or Error
<pre><code>
ERROR in Debug Failure. False expression: Host should not return a redirect source file from `getSourceFile`
</code></pre>

## 🌍 Your Environment
<pre><code>
@angular/*: 8.0.0-rc.4
@angular/cdk: 8.0.0-rc.1
@angular/material: 8.0.0-rc.1
@angular/http: 8.0.0-beta.10
@angular-devkit/build-optimizer: 0.800.0-rc.4
rxjs: 6.5.2
ts-node: 8.1.0
typescript: 3.4.5
webpack: 4.31.0
webpack-cli: 3.3.2
</code></pre>

**Anything else relevant?**

Duplicate, but without repro steps and in the wrong issue tracker: https://github.com/angular/angular/issues/22524

I've been monkey patching "program.js" for a long time and have not met any problems with the solution suggested above.

**Comment by alan-agius4** [comment]
Hi @JonWallsten, thanks for reporting this however as you mentioned this issue is being tracked in https://github.com/angular/angular/issues/22524, which is the correct issue tracker for compiler and compiler-cli issues.

**Comment by JonWallsten** [comment]
@alan-agius4 Ah, that's too bad, then I guess I'll have to keep monkey patching. No one over at angular/angular seems to care about the issue.
