### ISSUE TITLE
fileReplacements causes duplication of code

### ISSUE THREAD

**Issue by willyboy** [angular/angular-cli#14510]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not that I'm aware of

### Description

If you use fileReplacements to replace one file with a file that already exists, then the file will be effectively imported twice.

## 🔬 Minimal Reproduction

Highcharts has multiple versions. There's the base highcharts.js but then there's also highstock.js and highcharts-more.js. All versions include the original base highcharts.

We have libraries that just need the base highcharts version. However, some apps need more functionality so they import one of the other versions. 

We don't need both the base highcharts and say, highstock. The assumption was that we could use fileReplacements to say "whenever you find highcharts, use highstock instead".

Like:

```
{
      "replace": "./node_modules/highcharts/highcharts.js",
      "with": "./node_modules/highcharts/highstock.js"
}
```

This actually made our bundle size bigger (which was obviously the opposite of the desired effect). Upon investigating, I found that fileReplacements was replacing highcharts with highstock and ignoring the fact that highstock already existed. So now we had 2 copies of highstock.

## 🔥 Exception or Error

N/A

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.1
Node: 10.15.2
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.1
@angular/cdk                      7.3.7
@angular/cli                      7.3.1
@angular/flex-layout              7.0.0-beta.19
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, this is expected because `fileReplacements` will not replace the module identifier (import/require) statements but rather only the file/module content. 

What the above replacements config essentially means is to replace the contents of `./node_modules/highcharts/highcharts.js` with the contents of `./node_modules/highcharts/highstock.js` and not redirect `./node_modules/highcharts/highcharts.js` to `./node_modules/highcharts/highstock.js`.
