### ISSUE TITLE
ng g --list shows the wrong collection

### ISSUE THREAD

**Issue by FrozenPandaz** [angular/angular-cli#14519]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't know but the code makes it seem like it worked once upon a time

### Description

 A clear and concise description of the problem...
Running `ng g --list` in a workspace which has a different default schematic than `@schematics/angular` prints out:

```
[--help stuff]

Available Schematics:
  Collection "@schematics/angular":
    library
    workspace-schematic
```

The schematics listed are indeed the schematics available in the default collection but the default collection is actually `@nrwl/workspace`.

It looks like the source code used to or intends to print out available schematics for all collections. I think this would be the preferred behavior.

## 🔬 Minimal Reproduction
```
npx create-nx-workspace@next ng-bug
cd ng-bug
ng g --list
```

## 🌍 Your Environment
CLI `8.0.0-rc.4` 

**Anything else relevant?**
This affects all Nx users + more?

**Comment by alan-agius4** [comment]
@FrozenPandaz, just a note, `--list` doesn't exists. You are fall backing to `--help`
