### ISSUE TITLE
"System is not defined" dist/index.html + Cordova

### ISSUE THREAD

**Issue by Wancieho** [angular/angular-cli#1451]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please
angular-cli: 1.0.0-beta.10
node: 5.8.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
If I run the dist/index.html without serving it as HTTP I see "System is not defined" in console. This is problematic for doing Cordova builds.

4. The log given by the failure. Normally this include a stack trace and some
ReferenceError: System is not defined
index.html (line 18, col 7)

5. Mention any other details that might be useful.
To me being able to do Cordova builds from the ng build dist folder is essential.

**Comment by filipesilva** [comment]
See my answer to you in the other thread: https://github.com/angular/angular-cli/issues/1231#issuecomment-235302732
