### ISSUE TITLE
ng g Component should accept template option to crearte HTML or SVG template for component

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular-cli#14512]
# 🚀 Feature request

We support SVG as the template now, generate component should accept --template flag to accept SVG so we can generate an SVG file rather than HTML, HTML should be the default option

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

--template option with ng g component command

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by santoshyadav198613** [comment]
I would be happy to open a PR if this is accepted.

**Comment by alan-agius4** [comment]
Hi @santoshyadav198613, since this will expand the public api it’s best to discuss this in one of our weekly team meetings and see if it should be added or not.

Thanks

**Comment by santoshyadav198613** [comment]
> Hi @santoshyadav198613, since this will expand the public api it’s best to discuss this in one of our weekly team meetings and see if it should be added or not.
> 
> Thanks

Thanks @alan-agius4 , 
Is this open for everyone, if yes can you guide me on how to join.

**Comment by alan-agius4** [comment]
@santoshyadav198613, it’s an internal meeting.

**Comment by santoshyadav198613** [comment]
Thanks @alan-agius4

**Comment by filipesilva** [comment]
@mgechev what's devrels perspective on SVG templates? Do we want to encourage SVG as default option, or is it something that's just as well for users to change after the fact?

**Comment by mgechev** [comment]
From what I've seen, SVGs are not very widely used and it might not be worth including yet another option to the generator.
