### ISSUE TITLE
Dotfiles are not included

### ISSUE THREAD

**Issue by grosch** [angular/angular-cli#14523]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Description

 Dotfiles are not being included with `ng build`

## 🔬 Minimal Reproduction

Just doing an `ng build` and then looking in my dist folder none of the dotfiles from the project are being included.  For example, the `assets` folder includes a .gitignore, that's not there.  More importantly the project include an .htaccess file, which i'm explicitly listing in the `angular.json` file to be included but it's not anywhere in the dist folder.

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.9
Node: 12.3.1
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi, @grosch I tried to replicate this however I was unable to do so locally.  

When adding the below configuration, 
```
"assets": [
  "src/favicon.ico",
  "src/assets/.htaccess"
],
```

`.htaccess` was copied successfully to the `dist/assets` folder.

Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by grosch** [comment]
@alan-agius4 Well, in making a sample for you it's working perfectly, so something else is just screwy with my existing project.  I'll work it out locally.  Apologies for the thrash.
