### ISSUE TITLE
Can't apply custom loader for component's 'templateUrl' since version 8

### ISSUE THREAD

**Issue by MateEke** [angular/angular-cli#14534]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: ^7

### Description

In previous versions there was an error if you tried to use any unsupported filetype for templateUrl
<pre><code>
ERROR in Module parse failed: Unexpected token (2:55)
You may need an appropriate loader to handle this file type.
</code></pre>
Since .svg is supported there are no error, but the file is simply loaded with `raw-loader`

## 🔬 Minimal Reproduction

Create a new project with Angular: 8.0.0-rc.5
Try to use [ng-cli-pug-loader](https://github.com/danguilherme/ng-cli-pug-loader) or [custom-webpack builder](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack) for .pug loading.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0-rc.4
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0-rc.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.4
@angular-devkit/build-angular     0.800.0-rc.4
@angular-devkit/build-optimizer   0.800.0-rc.4
@angular-devkit/build-webpack     0.800.0-rc.4
@angular-devkit/core              8.0.0-rc.4
@angular-devkit/schematics        8.0.0-rc.4
@angular/cli                      8.0.0-rc.4
@ngtools/webpack                  8.0.0-rc.4
@schematics/angular               8.0.0-rc.4
@schematics/update                0.800.0-rc.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**
The issue is present since .svg component template is supported - https://github.com/angular/angular-cli/commit/dfb08b95b73f3e75d0f2cd0c61f336dc86d0769a

#https://github.com/danguilherme/ng-cli-pug-loader/issues/20

**Comment by alan-agius4** [comment]
Hi, are you using `directTemplateLoading: false` when invoking the `@ngtools/webpack` plugin?

**Comment by MateEke** [comment]
> Hi, are you using `directTemplateLoading: false` when invoking the `@ngtools/webpack` plugin?

How can I pass `directTemplateLoading: false`?

I have tried this configuration with [meltedspark/custom-webpack](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack), but no success

```
const AngularCompilerPlugin = require('@ngtools/webpack/src');


module.exports = {
  module: {
    rules: [
      {
        test: /.(pug|jade)$/,
        exclude: /.(include|partial).(pug|jade)$/,
        use: [{loader: 'apply-loader'}, {loader: 'pug-loader'}]
      },
      {test: /.(include|partial).(pug|jade)$/, loader: 'pug-loader'}
    ]
  },
  plugins: [
    new AngularCompilerPlugin.AngularCompilerPlugin({
      tsConfigPath: './tsconfig.app.json',
      entryModule: './src/app/app.module#AppModule',
      directTemplateLoading: false
    })
  ]
};
```
`ERROR in : TypeError: Cannot read property 'getTypeChecker' of undefined
`

**Comment by clydin** [comment]
Modification of the Webpack configuration is considered unsupported.  However, one method that may work to alter the options of a plugin is to search for the existing instance within `plugins`, extract the existing options (for `AngularCompilerPlugin`, there's an `_options` property), remove the existing instance, and create a new one using the existing options plus any custom alterations.  Webpack plugins in general are unfortunately complicated to alter.

**Comment by MateEke** [comment]
For testing purposes I have altered `node_modules\@angular-devkit\build-angular\src\angular-cli-files\models\webpack-configs\typescript.js` with `directTemplateLoading: false`.
Now the custom pug loader works properly.
If there is a proper way to set `directTemplateLoading: false` the existing custom pug loaders should work fine.

**Comment by MateEke** [comment]
Here is a workaround based on [meltedspark/custom-webpack](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack) for now:

```
const AngularCompilerPlugin = require('@ngtools/webpack/src');

module.exports = (config) => {
  config.module.rules.unshift({
      test: /.(pug|jade)$/,
      exclude: /.(include|partial).(pug|jade)$/,
      use: [{loader: 'apply-loader'}, {loader: 'pug-loader'}]
    },
    {test: /.(include|partial).(pug|jade)$/, loader: 'pug-loader'});

  const index = config.plugins.findIndex(p => {
    return p instanceof AngularCompilerPlugin.AngularCompilerPlugin
  });
  const oldOptions = config.plugins[index]._options;
  oldOptions.directTemplateLoading = false;
  config.plugins.splice(index);

  config.plugins.push(new AngularCompilerPlugin.AngularCompilerPlugin(oldOptions));

  return config;
};
```

**Comment by clydin** [comment]
Closing as the above method is a necessary step to augment an existing plugin within a webpack configuration.

**Comment by MateEke** [comment]
Almost all property of AngularCompilerPlugin is editable trough tsconfig or angular.json. I think `directTemplateLoading` should be configurable too. The above method seems like a dirty hack.

There are lot of feature request for PUG/JADE support. Since 2016 we got promises for native support https://github.com/angular/angular-cli/issues/40 (PR not merged) or trough addon system https://github.com/angular/angular-cli/issues/1886

Now in Angular 8 it's even more difficult...

**Comment by clydin** [comment]
It's more general than that though.  Any webpack plugin would need the same treatment to augment (TerserPlugin, SourceMapDevToolPlugin, SubresourceIntegrityPlugin, etc.).   The option in question is also only relevant with a custom webpack configuration which while allowed is also unsupported (from within the CLI).
