### ISSUE TITLE
@angular-devkit/build-angular package doesn't reflect master

### ISSUE THREAD

**Issue by crooksey** [angular/angular-cli#14531]
# 🐞 Bug report

### Command (mark with an `x`)

```

- [X] build
- [X] serve

```

### Description

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/jit-polyfills.js 

References
```
import 'core-js/proposals/reflect-metadata';
```
However, my installed version (on a clean node modules) shows
```
import 'core-js/es7/reflect';
```
This code was updated approx 6 weeks ago in master, yet is still not published on a recent release to npm, 

## 🔬 Minimal Reproduction
Install latest package, view installed polyfill

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js
Module not found: Error: Can't resolve 'core-js/es7/reflect' in '/home/luke/nodejs/ecom2/ecom2-frontend/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models'
ℹ ｢wdm｣: Failed to compile.

</code></pre>

## 🌍 Your Environment
<pre><code>
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.1.3
webpack                           4.29.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi, support for core-js version 3+ has been added in version 8 https://github.com/angular/angular-cli/releases/tag/v8.0.0-beta.13  

Also, kindly note that the current master is for version 8.1

Related issue: https://github.com/angular/angular-cli/issues/13954
