### ISSUE TITLE
ng new test-app - failed installing typings

### ISSUE THREAD

**Issue by DarrynR** [angular/angular-cli#1454]
I didn't see any errors running the install command "C:\Source\Angular>npm install -g angular-cli", only when i go to create a new application.

Command:
C:\Source\Angular>ng new test-app

Version:
C:\Source\Angular>ng --version
(node:50692) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.10
node: 6.3.0
os: win32 x64

Logs\Console output:
  create typings.json
/ Installing packages for tooling via npmtypings ERR! message Unable to connect to "https://api.typings.org/entries/dt/angular-protractor/tags/1.5.0%2B20160425143459"
typings ERR! caused by unable to verify the first certificate

typings ERR! cwd C:\Source\Angular\test-app
typings ERR! system Windows_NT 10.0.10586
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Source\\Angular\\test-app\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v6.3.0
-  Installing packages for tooling via npmERR!   <https://github.com/typings/typings/issues>
test-app@0.0.0 postinstall: `typings install`
Exit status 1
Error: test-app@0.0.0 postinstall: `typings install`rror at:
Exit status 1
    at EventEmitter.<anonymous> (C:\Users\TestUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\lifecycle.js:242:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (C:\Users\TestUser\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

Other Details:
I have npm strict-ssl set to false.

if i run the following "C:\Source\Angular>npm install typings" separately i get the following output...

  +-- wordwrap@1.0.0
  `-- xtend@4.0.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Source\Angular\package.json'
npm WARN Angular No description
npm WARN Angular No repository field.
npm WARN Angular No README data
npm WARN Angular No license field.

**Comment by filipesilva** [comment]
Closed as this PR was made obsolete by https://github.com/angular/angular-cli/pull/1455.

On the next version of the CLI typings will not be used anymore.

**Comment by DarrynR** [comment]
I am not sure closing this issue and stating the next version is what i need is a real solution, forcing an upgrade isn't a real life workaround imo, is there not a fix for this in the current version i am trying to use? 

When will this next version be available through npm?

**Comment by filipesilva** [comment]
@DarrynR anything that needs to be corrected in library code requires an upgrade. This is also beta software, we don't yet have any kind of long-term support version. There will be a new release and update instructions very soon.

In your specific case, `typings` is having a problem connecting. It might indicate that your system cannot connect to the typings address. You can try to debug this by using https://github.com/typings/typings separately, but from your error it doesn't seem that it's a CLI issue per se.

**Comment by DarrynR** [comment]
@filipesilva Thank you, I am just very new to this so on a very steep learning curve. I will check the typings repository as you suggest for a solution.

**Comment by patorjk** [comment]
I'm having the same issue, though I'm on an internal network which is why it errors when it tries to connect to "https://api.typings.org/...". I'll keep an eye out for the new version.
