### ISSUE TITLE
Error with core-js after upgrading to Angular 8.0

### ISSUE THREAD

**Issue by mhosman** [angular/angular-cli#14542]
After ng update I upgraded to Angular 8.0. When I try to run my app I get:

```
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es6/reflect'
```

**Comment by mhosman** [comment]
Inside polyfills.ts I updated this line:
import 'core-js/es6/reflect';

To this one:
import 'core-js/es/reflect';

And worked like a charm...

**Comment by sarunint** [comment]
@mhosman Just to inform you, you can remove that line entirely. The polyfills are now handled by Angular CLI itself.

**Comment by adamdport** [comment]
@sarunint I tried it your way (removed the line) and it worked fine with `ng serve`, but after building, I get 

    Uncaught TypeError: Reflect.getMetadata is not a function

Should I write up a bug or are you possibly mistaken?

**Comment by Chinokaiser** [comment]
@sarunint 
I've read over [here](https://blog.ninja-squad.com/2019/05/29/angular-cli-8.0/) too, that states core-js is handled by CLI, so there's no need to add as dependencies.

I've remove core-js from my package.js, and build the project, then serve.
However i'm facing same issue as @adamdport 

I'm not sure if it's my configuration issue, or it's a Bug

**Comment by jimmykane** [comment]
> @mhosman Just to inform you, you can remove that line entirely. The polyfills are now handled by Angular CLI itself.

can we remove all other lines or also that file?

**Comment by shrishti2305** [comment]
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'C:\my-project\src'
 I am getting this error. How can I resolve this?

**Comment by LastDragon-ru** [comment]
https://github.com/angular/angular-cli/issues/14542#issuecomment-496737123 or 
```
// Uncaught TypeError: Reflect.getMetadata is not a function
import 'core-js/proposals/reflect-metadata';
```

depends on what you need

**Comment by sajantalekar** [comment]
ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'core-js/es7/reflect' in 'F:\JSON\angular-json-crud\src'
