### ISSUE TITLE
crash during ng build aot and prod (dev build works)

### ISSUE THREAD

**Issue by tomgruszowski** [angular/angular-cli#14543]
# 🐞 Bug report

```
- [x] build
```

### Is this a regression?
Yes?

### Description

Crash during ng build --aot/--prod after successfully updating to Angular 8 (with appropriate ng update). Works in latest v7 using same node (12.3.1).

## 🔬 Minimal Reproduction
ng build --aot OR ng build --prod
The above probably isn't much help, not sure how else to reproduce this without ripping apart my rather large codebase. Confirmed the issue is not with styles.scss (commented entire file out), the same memory error happens with a TS file.

## 🔥 Exception or Error
<pre><code>

 10% building 4/5 modules 1 active ...local_path_to_app\src\scss\styles.scss
<--- Last few GCs --->

[13668:000001C59F29DB60]    63288 ms: Mark-sweep 1923.7 (2068.8) -> 1914.9 (2070.3) MB, 485.0 / 0.0 ms  (average mu = 0.130, current mu = 0.050) allocation failure scavenge might not succeed
[13668:000001C59F29DB60]    63794 ms: Mark-sweep 1927.1 (2070.3) -> 1918.1 (2072.3) MB, 476.0 / 0.0 ms  (average mu = 0.097, current mu = 0.061) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7BF172C16]
Security context: 0x0287b4e1a2f1 <JSObject>
    1: visitExternalExpr [0000036AAE5F6C89] [C:local_path_to_app\node_modules\@angular\compiler\bundles\compiler.umd.js:~1959] [pc=0000039CE9875D5E](this=0x027858cf4791 <_ApplySourceSpanTransformer map = 000003AB9245E239>,0x007406809c41 <ExternalExpr map = 0000020FA4B95719>,0x03a9641801d9 <null>)
    2: visitExpression [0000036AAE5F34D9]...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7BE62674F napi_wrap+120927
 2: 00007FF7BE5CFE26 uv_loop_fork+44550
 3: 00007FF7BE5D0CC6 uv_loop_fork+48294
 4: 00007FF7BE908BCE v8::internal::Parser::ReportMessageAt+206
 5: 00007FF7BE8DCC4A v8::internal::wasm::StreamingDecoder::Fail+666
 6: 00007FF7BE97309C v8::internal::Heap::CreateFillerObjectAt+2972
 7: 00007FF7BE97AE0F v8::internal::LocalEmbedderHeapTracer::NotifyV8MarkingWorklistWasEmpty+5375
 8: 00007FF7BE971483 v8::internal::Heap::CollectGarbage+1235
 9: 00007FF7BE96FB84 v8::internal::GCTracer::AddScopeSample+1316
10: 00007FF7BE9A87EF v8::internal::Factory::AllocateRawArray+95
11: 00007FF7BE9B0996 v8::internal::Factory::NewFixedArrayWithFiller+86
12: 00007FF7BE9A85A6 v8::internal::Factory::nan_value+3366
13: 00007FF7BE9EDE04 v8::internal::BigInt::Zero+1556
14: 00007FF7BE9EEED5 v8::internal::BigInt::Zero+5861
15: 00007FF7BE9EDBB3 v8::internal::BigInt::Zero+963
16: 00007FF7BE9F9D15 v8::internal::IntToCString+3669
17: 00007FF7BE9F9E65 v8::internal::IntToCString+4005
18: 00007FF7BE9FB967 v8::internal::IntToCString+10919
19: 00007FF7BE9FB700 v8::internal::IntToCString+10304
20: 00007FF7BE9FA60E v8::internal::IntToCString+5966
21: 00007FF7BE9FCAB5 v8::internal::IntToCString+15349
22: 00007FF7BECD1D83 v8::internal::OptimizingCompileDispatcher::Unblock+94083
23: 00007FF7BECD2146 v8::internal::OptimizingCompileDispatcher::Unblock+95046
24: 00007FF7BF172C16 v8::internal::NativesCollection<0>::GetScriptsSource+662454
</code></pre>

## 🌍 Your Environment
<pre>

<code>
Angular CLI: 8.0.0
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

[Maybe same as this issue? https://github.com/angular/angular-cli/issues/14298](https://github.com/angular/angular-cli/issues/14298)

**Comment by wuzhiji37** [comment]
for me:
node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build .....

**Comment by alan-agius4** [comment]
In version 8 we enable differential loading by default which means that we'll do 2 builds under the hood one for es5 and another for es2015. This requires additional memory. Hence, you might need to increase the memory limit as suggested above by @wuzhiji37.

**Comment by filipesilva** [comment]
Using Node 12 will also help, because Node 12 automatically increases the memory limit.

But we probably have a memory leak between the builds. Memory should be freed up from one to the other because they are independent and happen in sequence.

**Comment by galtonova** [comment]
It's not just for differential loading builds either. Even if I target only es5, prod build process now requires a lot more memory compared to Angular 7. While using Angular 7, --max_old_space_size=1500 was enough for my prod builds. Now my Angular 8 prod builds (target es5, same repo) require --max_old_space_size=2100. Maybe Node 12 now requires a lot more memory? Or maybe Angular 8 prod build has memory leaks?

**Comment by filipesilva** [comment]
@galtonova @tomgruszowski are you using sass/scss?

**Comment by galtonova** [comment]
@filipesilva yes, I use scss. And I believe @tomgruszowski also uses scss because first line of his log:

> `10% building 4/5 modules 1 active ...local_path_to_app\src\scss\styles.scss`

**Comment by filipesilva** [comment]
Ok, then I think this is the same as https://github.com/angular/angular-cli/issues/13734#issuecomment-497385979. I'm investigating it there mostly because there's more context, and there's a good repro in https://github.com/angular/angular-cli/issues/13734#issuecomment-497393904. Let's move the discussion there.

**Comment by tomgruszowski** [comment]
> @filipesilva yes, I use scss. And I believe @tomgruszowski also uses scss because first line of his log:
> 
> > `10% building 4/5 modules 1 active ...local_path_to_app\src\scss\styles.scss`

My scss is quite impressive :) (material and bootstrap styling/theming) but I get same error when I remove scss file).
