### ISSUE TITLE
Enable Ivy in ng test

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#14547]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
At the moment https://v8.angular.io/guide/ivy documents how to opt-in into Ivy for builds, however this doesn't document how to opt-in into Ivy for tests. The same thing applies when generating a new Ivy application via the CLI. Ivy is only enabled for builds.

### Describe the solution you'd like
We should enable the Ivy compiler for tests as well, for both JIT and AOT mode, This is needed, because when enabling the `enableIvy` compiler option in JIT mode it will use process the packages with `ngcc` and will use the Ivy engine which also improves runtime speed in JIT mode.

There are 2 ways that I can think of to achieve this. Either by adding `enableIvy: true` to the specs tsconfig, or the specs tsconfig extends the app tsconfig.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/15044, given that tests only run in JIT at the moment.
