### ISSUE TITLE
Migration to v8 breaks the routing modules

### ISSUE THREAD

**Issue by dushkostanoeski** [angular/angular-cli#14551]
# 🐞 Bug report

### Description

The migration messed up my routing modules. This is what the line was before the migration: 
```
{
    path: 'Admin',
    loadChildren: './admin/admin.module#AdminModule',
    canActivate: [AdminGuard]
}
```
and this is what it looks like after the migration
```
{
    path: 'Admin',
    loadChildren: '() => import('./admin/admin.module').then(m => m.AdminModule)
    canActivate: [AdminGuard]
},
```
You can note the misplaced `'` and the missing comma at the end of `loadChildren`

## 🔬 Minimal Reproduction

I am guessing this has something to do with #9712 because `Visual Studio` gave me a warning that the line ending in the file not consistent, something that was happening whit #9712 as well,

**Comment by dushkostanoeski** [comment]
The encoding for both files was `UTF-8` and some of the `@angular/core` migrations broke the code as well in the `UTF-8` encoded files, while the `UTF-8 BOM` encoded files are good.

**Comment by alan-agius4** [comment]
@dushkostanoeski, I am trying to look at this and it seems that the issue is occurring when having a BOM and not the other way round.
