### ISSUE TITLE
Running `ng update @angular/core --from 7 --to 8 --migrate-only` on 8.0.0 does not migrate

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#14565]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes

### Description

Followup to https://github.com/angular/angular-cli/issues/14553#issuecomment-496915624

Running `ng update @angular/core --from 7 --to 8 --migrate-only` on 8.0.0 does not migrate.
But going back to rc.0 will prompt the migration again.

## 🔬 Minimal Reproduction
- setup repository
```
git clone https://github.com/rip222/viewChild-test-ng8
cd viewChild-test-ng8
npm i
```
- try to migrate and it fails
```
kamik@RED-X1C6 MINGW64 /d/sandbox/viewChild-test-ng8 (master)
$ ng update @angular/core --from 7 --to 8 --migrate-only
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
Package "@angular\\core\\schematics\\migrations.json" was found but does not support schematics.
```
- `npm install @angular/cli@8.0.0-rc.0 --save-exact --save-dev`, commit to git
- try to migrate again and it succeeds
```
kamik@RED-X1C6 MINGW64 /d/sandbox/viewChild-test-ng8 (master)
$ ng update @angular/core --from 7 --to 8 --migrate-only
            ------ Static Query Migration ------
            With Angular version 8, developers need to
            explicitly specify the timing of ViewChild and
            ContentChild queries. Read more about this here:
            https://v8.angular.io/guide/static-query-migration
            ------------------------------------------------
UPDATE src/app/app.component.ts (309 bytes)
```

## 🔥 Exception or Error
<pre><code>
$ ng update @angular/core --from 7 --to 8 --migrate-only
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
Package "@angular\\core\\schematics\\migrations.json" was found but does not support schematics.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0
Node: 10.10.0
OS: win32 x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by TunMyintThein1995** [comment]
Hello 
what happen this error
![viewchild](https://user-images.githubusercontent.com/53258730/62280567-37fb5380-b472-11e9-8fc4-ac4a008bca5f.png)

**Comment by PeterAlianza** [comment]
@TunMyintThein1995 That is because the angular team changed the functionality of ViewChild so now you have you change it to something similar to this,
@ViewChild(MatSort, {static: false}) sort: MatSort;
Here is a link to the documentation about the different meta properties that you can now use. 
https://angular.io/api/core/ViewChild
