### ISSUE TITLE
ClassExpression in ES2015 builds produces larger bundles

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#14577]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No, but now it effects more users as differential loading is on by default.

### Description

TypeScript ClassExpression are not being treeshaken away.

Example codes:

```ts
let AggregateColumnDirective = class AggregateColumnDirective {
    constructor(viewContainerRef) {
    }
};
AggregateColumnDirective = __decorate([
    Directive({
        selector: 'ejs-grid>e-aggregates>e-aggregate>e-columns>e-column',
        inputs: input$1,
        outputs: outputs$1,
        queries: {}
    }),
    __metadata("design:paramtypes", [ViewContainerRef])
], AggregateColumnDirective);
```

```ts
let ChipList = class ChipList extends Component {
  constructor(options, element) {
        super(options, element);
    }
};
__decorate$4([
    Property([])
], ChipList.prototype, "chips", void 0);
ChipList = __decorate$4([
    NotifyPropertyChanges
], ChipList);
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0
Node: 11.0.0
OS: win32 x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

https://github.com/angular/angular-cli/pull/14263

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Any update in this?

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 

Can i have to update my @angular-devkit/build-optimizer package to which version?

**Comment by kumaresan-subramani** [comment]
HI 
Any update on this?

**Comment by kumaresan-subramani** [comment]
Thanks 
issue got fixed.

**screenshot**
<img width="597" alt="Screenshot (267)" src="https://user-images.githubusercontent.com/36756050/59193704-33b66680-8ba4-11e9-94dc-6f2942ed545e.png">

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

still facing same issue, tree-shaking not working properly

angular/angular-cli#15396
