### ISSUE TITLE
Cannot find module '@angular-devkit/schematics' on upgrade

### ISSUE THREAD

**Issue by bluebaroncanada** [angular/angular-cli#14570]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ x ] update
```

### Is this a regression?
Yes

### Description
```
git clone git@github.com:aslam2368/angular-6-datatable.git
cd angular-6-datatable
>> ng update @angular/cli @angular/core
Cannot find module '@angular-devkit/schematics'
```

## 🌍 Your Environment
<pre><code>
>> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.8
Node: 10.10.0
OS: win32 x64
Angular: 8.0.0
... common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.8 (cli-only)
@angular-devkit/core         7.3.8 (cli-only)
@angular-devkit/schematics   7.3.8 (cli-only)
@schematics/angular          7.3.8 (cli-only)
@schematics/update           0.13.8 (cli-only)
rxjs                         6.5.2
typescript                   3.4.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi @bluebaroncanada, it seems that your project is not a Angular CLI project and hence you cannot use `ng update`
