### ISSUE TITLE
ng serve with options for node

### ISSUE THREAD

**Issue by sysmat** [angular/angular-cli#14576]
# 🚀 Feature request

ng serve command should accept node flags

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
ng serve accept node flags

### Describe the solution you'd like
Something like proxy-conf.json

`ng serve --node-config=node-conf.json --proxy-config proxy-conf.json`

https://nodejs.org/api/cli.html

```json
{
 "max-http-header-size": 100000,
...
   
}
```
### Describe alternatives you've considered

* recompile node with custom flags, not good idea
* downgrading node

**Comment by filipesilva** [comment]
There's already a pretty decent way of doing that, which is to call node with the path to the ng binary. We recommend doing so for [increasing available memory](https://github.com/angular/angular-cli/issues/5618#issuecomment-450151214) for instance.

In your case I think you could do this:
```
node --max-http-header-size=100000 ./node_modules/@angular/cli/bin/ng serve
```

But you could also use the `NODE_OPTIONS` env var in the link you provided. There's isn't a great usage example there, but https://medium.com/the-node-js-collection/node-options-has-landed-in-8-x-5fba57af703d explains it better. With that, you'd do this instead on Linux:
```
NODE_OPTIONS="--max-http-header-size=100000" ng serve
```

On windows you'd have to use a method for setting env vars that works with your shell (these vary a bit).

Hope this helps.
