### ISSUE TITLE
Error to new install angular/cli@8.x.x with npm

### ISSUE THREAD

**Issue by amoncusir** [angular/angular-cli#14584]
# 🐞 Bug report

### Command (mark with an `x` or write it if not found the right command)

```
[sudo] npm i -g @angular/cli
```

### Is this a regression?

I can install the latest version (7.3.9)

### Description

When try install the last version of `angular-cli` npm package the command output a error and the installation process exited with status `130`.
I tried install with and without `sudo` privileges.

## 🔬 Minimal Reproduction

Run this command: `npm i -g @angular/cli`

## 🔥 Exception or Error

*The npm output when run the install command*:
<pre><code>
[        ..........] \ extract:genfun: sill extract duplexify@3.7.1
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@8.0.0 postinstall /usr/local/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! @angular/cli@8.0.0 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the @angular/cli@8.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/aran/.npm/_logs/2019-05-30T12_29_27_291Z-debug.log
</code></pre>

*And the log that npm create with the error (I've create a github gist because the file is too long)*:
[Gist Log](https://gist.github.com/amoncusir/cad7423723826e23c5a615af6c1f4196)

## 🌍 Your Environment

NPM version: `6.4.1`
OS: `Ubuntu 18.04`

**Anything else relevant?**

...?

**Comment by amoncusir** [comment]
In case it helps I tried to update Nodejs (v12.3.1) and NPM (v6.9.0) and the problem not solve.

**Comment by amoncusir** [comment]
Hey! I finded a fast solution for solve this problem. I one of my attempts to know what happens, I see that if create a new user in the same os environment, the problem nothing happens.

My solution is remove all user data related with npm and angular cli, like .angular-config.json user file, .npm folder, .cache folder and others (I don't remember all files that I removed cry)

That is possible it angular save any state or any others files in user folder? Or that it npm save any state or other think?

Thank's!

**Comment by grandtiger** [comment]
I am having the same exact issue. Tried deleting .angular-config.json, .npm and .cache folders, but it's still not working.

@amoncusir could you check your command history and see what else you deleted? Thanks!

**Comment by jimploof** [comment]
### **Having the exact same issue**

**`[~]# which npm`**
>/bin/npm

**`[~]# npm -v`**
>6.9.0

**`[~]# which node`**
>/bin/node

**`[~]# node -v`**
>v10.16.0

**`[~]# lsb_release -a`**
> LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.6.1810 (Core)
Release:        7.6.1810
Codename:       Core

**`[~]# npm list -g --depth=1`**
> /usr/lib
├─┬ @angular/cli@8.0.1
│ ├── @angular-devkit/architect@0.800.1
│ ├── @angular-devkit/core@8.0.1
│ ├── @angular-devkit/schematics@8.0.1
│ ├── @schematics/angular@8.0.1
│ ├── @schematics/update@0.800.1
│ ├── @yarnpkg/lockfile@1.1.0
│ ├── debug@4.1.1
│ ├── ini@1.3.5
│ ├── inquirer@6.3.1
│ ├── npm-package-arg@6.1.0
│ ├── open@6.2.0
│ ├── pacote@9.5.0
│ ├── read-package-tree@5.2.2
│ ├── semver@6.0.0
│ ├── symbol-observable@1.2.0
│ ├── universal-analytics@0.4.20
│ └── uuid@3.3.2
└─┬ npm@6.9.0
  ├── abbrev@1.1.1
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── aproba@2.0.0
  ├── archy@1.0.0
  ├── bin-links@1.1.2
  ├── bluebird@3.5.3
  ├── byte-size@5.0.1
  ├── cacache@11.3.2
  ├── call-limit@1.1.0
  ├── chownr@1.1.1
  ├── ci-info@2.0.0
  ├── cli-columns@3.1.2
  ├── cli-table3@0.5.1
  ├── cmd-shim@2.0.2
  ├── columnify@1.5.4
  ├── config-chain@1.1.12
  ├── debuglog@1.0.1
  ├── detect-indent@5.0.0
  ├── detect-newline@2.1.0
  ├── dezalgo@1.0.3
  ├── editor@1.0.0
  ├── figgy-pudding@3.5.1
  ├── find-npm-prefix@1.0.2
  ├── fs-vacuum@1.2.10
  ├── fs-write-stream-atomic@1.0.10
  ├── gentle-fs@2.0.1
  ├── glob@7.1.3
  ├── graceful-fs@4.1.15
  ├── has-unicode@2.0.1
  ├── hosted-git-info@2.7.1
  ├── iferr@1.0.2
  ├── imurmurhash@0.1.4
  ├── inflight@1.0.6
  ├── inherits@2.0.3
  ├── ini@1.3.5
  ├── init-package-json@1.10.3
  ├── is-cidr@3.0.0
  ├── json-parse-better-errors@1.0.2
  ├── JSONStream@1.3.5
  ├── lazy-property@1.0.0
  ├── libcipm@3.0.3
  ├── libnpm@2.0.1
  ├── libnpmaccess@3.0.1
  ├── libnpmhook@5.0.2
  ├── libnpmorg@1.0.0
  ├── libnpmsearch@2.0.0
  ├── libnpmteam@1.0.1
  ├── libnpx@10.2.0
  ├── lock-verify@2.1.0
  ├── lockfile@1.0.4
  ├── lodash._baseindexof@3.1.0
  ├── lodash._baseuniq@4.6.0
  ├── lodash._bindcallback@3.0.1
  ├── lodash._cacheindexof@3.0.2
  ├── lodash._createcache@3.1.2
  ├── lodash._getnative@3.9.1
  ├── lodash.clonedeep@4.5.0
  ├── lodash.restparam@3.6.1
  ├── lodash.union@4.6.0
  ├── lodash.uniq@4.5.0
  ├── lodash.without@4.4.0
  ├── lru-cache@4.1.5
  ├── meant@1.0.1
  ├── mississippi@3.0.0
  ├── mkdirp@0.5.1
  ├── move-concurrently@1.0.1
  ├── node-gyp@3.8.0
  ├── nopt@4.0.1
  ├── normalize-package-data@2.5.0
  ├── npm-audit-report@1.3.2
  ├── npm-cache-filename@1.0.2
  ├── npm-install-checks@3.0.0
  ├── npm-lifecycle@2.1.0
  ├── npm-package-arg@6.1.0
  ├── npm-packlist@1.4.1
  ├── npm-pick-manifest@2.2.3
  ├── npm-profile@4.0.1
  ├── npm-registry-fetch@3.9.0
  ├── npm-user-validate@1.0.0
  ├── npmlog@4.1.2
  ├── once@1.4.0
  ├── opener@1.5.1
  ├── osenv@0.1.5
  ├── pacote@9.5.0
  ├── path-is-inside@1.0.2
  ├── promise-inflight@1.0.1
  ├── qrcode-terminal@0.12.0
  ├── query-string@6.2.0
  ├── qw@1.0.1
  ├── read@1.0.7
  ├── read-cmd-shim@1.0.1
  ├── read-installed@4.0.3
  ├── read-package-json@2.0.13
  ├── read-package-tree@5.2.2
  ├── readable-stream@3.1.1
  ├── readdir-scoped-modules@1.0.2
  ├── request@2.88.0
  ├── retry@0.12.0
  ├── rimraf@2.6.3
  ├── safe-buffer@5.1.2
  ├── semver@5.6.0
  ├── sha@2.0.1
  ├── slide@1.1.6
  ├── sorted-object@2.0.1
  ├── sorted-union-stream@2.1.3
  ├── ssri@6.0.1
  ├── stringify-package@1.0.0
  ├── tar@4.4.8
  ├── text-table@0.2.0
  ├── tiny-relative-date@1.3.0
  ├── uid-number@0.0.6
  ├── umask@1.1.0
  ├── unique-filename@1.1.1
  ├── unpipe@1.0.0
  ├── update-notifier@2.5.0
  ├── uuid@3.3.2
  ├── validate-npm-package-license@3.0.4
  ├── validate-npm-package-name@3.0.0
  ├── which@1.3.1
  ├── worker-farm@1.6.0
  └── write-file-atomic@2.4.2

**`[~]npm install -g @angular/cli`**

> /usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng
\> @angular/cli@8.0.1 postinstall /usr/lib/node_modules/@angular/cli
\> node ./bin/postinstall/script.js

>? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
how to change this setting, see http://angular.io/analytics. No
(node:7812) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/root/.angular-config.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at createGlobalSettings (/usr/lib/node_modules/@angular/cli/utilities/config.js:65:10)
    at Object.getWorkspaceRaw (/usr/lib/node_modules/@angular/cli/utilities/config.js:73:26)
    at setAnalyticsConfig (/usr/lib/node_modules/@angular/cli/models/analytics.js:288:43)
    at Object.promptGlobalAnalytics (/usr/lib/node_modules/@angular/cli/models/analytics.js:326:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
\+ @angular/cli@8.0.1
>added 227 packages from 175 contributors in 36.211s

**Comment by renantarouco** [comment]
When installed `node` and `npm` with `snap` I had to run the following command in order to install @angular/cli globally:

`sudo npm install -g @angular/cli --scripts-prepend-node-path`

**Comment by ylorph** [comment]
same here , all build using ng-cli were broken,
(the build do a  local temporary install of node & ng-cli )
added the following in  the build scripts and the issue was solved
 
 `npm config set script-prepend-node-path true `

**Comment by jimploof** [comment]
Nothing mentioned worked for me, additionally, everything I have found says not to install as root, or using sudo.

I followed some official documentation from npm manual and it worked for me.
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by qdouble** [comment]
I just ran into the same issue. Using yarn appears to work just fine until they fix this:

`yarn add global @angular/cli`

**Comment by ionutgrecu** [comment]
Run `npm install -g @angular/cli` without `sudo`. It worked for me.

**Comment by 87CSY** [comment]
Not sure if this helps, none of above mentioned worked for me.
Still getting
```
? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
npm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! @angular/cli@8.0.0 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 130
```
And if I tried with
`yarn add global @angular/cli`

Following error occurs
```
2019/06/14 13:54:54 [~]$ yarn add global @angular/cli
yarn add v1.16.0
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/ubuntu/node_modules/@angular/cli: Command failed.
Exit code: 1
Command: node ./bin/postinstall/script.js
Arguments:
Directory: /home/ubuntu/node_modules/@angular/cli
Output:
/home/ubuntu/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

UnexpectedEndOfInputException [Error]: Unexpected end of file.
    at _readValue (/home/ubuntu/node_modules/@angular-devkit/core/src/json/parser.js:624:19)
    at parseJsonAst (/home/ubuntu/node_modules/@angular-devkit/core/src/json/parser.js:721:17)
    at Object.parseJson (/home/ubuntu/node_modules/@angular-devkit/core/src/json/parser.js:753:16)
    at MapSubscriber.project (/home/ubuntu/node_modules/@angular-devkit/core/src/experimental/workspace/workspace.js:259:175)
    at MapSubscriber._next (/home/ubuntu/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (/home/ubuntu/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MapSubscriber._next (/home/ubuntu/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/ubuntu/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/ubuntu/node_modules/@angular-devkit/core/node/host.js:191:21)
    at Observable._trySubscribe (/home/ubuntu/node_modules/rxjs/internal/Observable.js:44:25)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by gitdisrupt** [comment]
Had the same issue when attempt to install @angular/cli@8.1.0-beta.2:
` UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/Users/MYHOMEDIR/.angular-config.json'`

The following steps in this order, worked for me:
OSX Mojave 10.14.5, Installed node 12.4.0, npm 6.9.0
followed by the following commands:
`sudo chown -R $USER:$(id -gn $USER) /Users/MYHOMEDIR/.config`
`npm config set script-prepend-node-path true` note, without sudo
`sudo npm install -g @angular/cli@v8.1.0-beta.2`

**Comment by lvhellgren** [comment]
My problem was the following:

npm install -g @angular/cli
npm ERR! path /Users/acme/.npm/_cacache/index-v5/48/99
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir
npm ERR! Error: EACCES: permission denied, mkdir '/Users/acme/.npm/_cacache/index-v5/48/99'

As it turned out, user 'acme' was given no permissions to folder '48'. Assigning 'everyone' 'Read & Write' permissions to folder 'index-v5' fixed the problem for now.

**Comment by talent93** [comment]
I got the same problem but I solved mine by running CMD as adminsitrator.
