### ISSUE TITLE
-routing as reserved ending

### ISSUE THREAD

**Issue by nomlast** [angular/angular-cli#14588]
Unable to use the commands due to -routing being reserved
ng g lib feature/xxxRouting --directory=xx
ng g lib feature/xxx-routing --directory=xx
ng g c xx --project=xxx-routing

I cannot see how we can reserve names. There are other companies in the world that have routing definitions.

**Comment by filipesilva** [comment]
Heya, I'm not sure what you're seeing here. The commands you provided don't work in a new project:
```
kamik@RED-X1C6 MINGW64 /d/sandbox/webworkers (master)
$ ng g lib feature/xxx-routing --directory=xx
Unknown option: '--directory'

kamik@RED-X1C6 MINGW64 /d/sandbox/webworkers (master)
$ ng g lib feature/xxxRouting --directory=xx
Unknown option: '--directory'
```

Can you provide detailed steps on how to reproduce what you are seeing?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by nomlast** [comment]
Just run the command but replace xxxx with a name. That is what is causing
the issue Routing is reserved.
