### ISSUE TITLE
Ng 8.0 + ivy + library Error : does not have 'ngModuleDef' property

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular-cli#14594]
# 🐞 bug report

### Is this a regression?
no

### Description
this is a simple test ng 8.0 + ivy + library.  is it ivy supported custom library ? 
this is the error message i get : 
Error: Type MyLibModule does not have 'ngModuleDef' property.
if i turn off ivy, all work fine

## 🔬 Minimal Reproduction
https://github.com/keatkeat87/angular-ivy-library-issue

step : 
ng new library-and-project-issue --enable-ivy
cd library-and-project-issue
ng g library my-lib
ng build my-lib

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { MyLibModule } from 'my-lib'; // add

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    MyLibModule  // add
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
ng serve --open

**Angular Version:**
Angular CLI: 8.0.0
Node: 12.3.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.0
@angular-devkit/core         8.0.0
@angular-devkit/schematics   8.0.0
@schematics/angular          8.0.0
@schematics/update           0.800.0
rxjs                         6.4.0

**Comment by filipesilva** [comment]
I've moved this issue to the CLI repo. We don't yet have good support for Ivy libraries in the CLI.

**Comment by alan-agius4** [comment]
Hi @keatkeat87, yes this is something in the roadmap to add ngcc process on workspace libraries. We are targeting this for 8.1

Thanks

**Comment by vytautas-pranskunas-** [comment]
Checkout

**Comment by alan-agius4** [comment]
Going to re-open this as it's seems that it is not fully resolved

https://github.com/angular/angular-cli/pull/14755
