### ISSUE TITLE
html file replacement doesn't work

### ISSUE THREAD

**Issue by diogen737** [angular/angular-cli#14599]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

After upgrading to Angular 8 file replacement stopped working for html files.

## 🔬 Minimal Reproduction

git clone git@github.com:diogen737/fileReplacement-test.git

### Expexted behavior

since there's html replacement config in `angular.json` after `ng build --prod` I expect to see  
"this is prod index" on top of the page (localhost:8080/tester) which is present in `index.prod.html` and absent in `index.html` from which I conclude that html filre replacement is not working anymore.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0
Node: 12.3.1
OS: linux x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by randysimplist** [comment]
I am having the same exact issue but only appears to surface when targeting es2015 in the tsconfig.json file.

If I target es5 the html file replacement works just fine.

**Comment by alan-agius4** [comment]
Hi, this is because the index file for builds is outside of the webpack compilation. To change the index file, instead of `fileReplacements` the `index` option should be used.

https://angular.io/cli/build

**Comment by diogen737** [comment]
@alan-agius4 

> this is because the index file for builds is outside of the webpack compilation

but it worked on Angular 7, why you had to change it?

**Comment by randysimplist** [comment]
> Hi, this is because the index file for builds is outside of the webpack compilation. To change the index file, instead of `fileReplacements` the `index` option should be used.
> 
> https://angular.io/cli/build

This is not a feasible solution as leveraging the --index argument does not rename the specified file the same way that file replacements does.

This feature was working fine in older versions of webpack. As far as I can see this is a breaking change.

**Comment by dottodot** [comment]
@randysimplist  This really should have been mentioned as a breaking change in the release information

**Comment by dottodot** [comment]
@alan-agius4 Can you explain why you have closed this? Using index is not a like for like option.

**Comment by clydin** [comment]
The file replacements option was never intended to replace files outside of the script bundles.  That it worked previously was more of a defect itself than anything else.
It appears what is needed here is a more flexible “index” option which allows control of the output file name was well as the input.  This has been requested previously and I think it would be a useful addition in general.  The necessary logic is already present.  The configuration options would just need to be expanded to provide the information to the index processing.

**Comment by diogen737** [comment]
@clydin then it should be more documented because fileReplacements documentation does not impose any restrictions on the file type

**Comment by clydin** [comment]
The type actually isn't the relevant aspect.  Only bundled files are affected by the option.  HTML files used as templates are intended to work, for instance.

**Comment by diogen737** [comment]
eventually 
```
ng build --prod --configuration=production --index=src/index.prod.html
mv dist/index.prod.html dist/index.html
```

did the trick for me but I think it's kinda ugly

**Comment by jlnknz** [comment]
When serving the application:

`
$ ng serve --prod
`

instead of  building it only:

`
$ ng build --prod
`

Then file replacements on index.html is done correctly.

**Comment by boban984** [comment]
Updated to Angular 8, production builds not working ... scratching my head :)
A breaking change nobody even mentions 🤦‍♂️
Bravo

**Comment by randysimplist** [comment]
It seems like this is impacting a good number of people and we haven't seen any viable solutions to this problem yet.

Can we please re-open this issue?

**Comment by boban984** [comment]
A solution that worked for me:

Create a folder called 

> index-pages 

with subfolders for each index page you have and update your package.json like so:

`"build-i18n:en": "ng build --configuration production_en --index=./src/index-pages/production/index.html",`

This will replace your index.html with the one in the folder

**Comment by xxyyzz2050** [comment]
even .ts not worked for me

```
//angular.json -> projects.myProject.architect.build.configurations.dev :
//also in architect.server section

"dev": {
              "fileReplacements": [
                {
                  "replace": "src/environments/index.ts",
                  "with": "src/environments/dev.ts"
                }
              ]
            }
```
```
//src/environments/index.ts
console.log("index")
```

```
//src/environments/dev.ts
console.log("dev")
```

`> ng run myProject:build:dev && ng run myProject:server:dev  && npx webpack --config webpack.server.config.js --progress --colors && nodemon dist/server --inspaect --open --watch`

`import env from "../src/environments/index.ts" //<--- should be replaced with dev.ts`

it prints the console.log of index.ts not dev.ts

repo: https://github.com/xxyyzz2050/eldeebCMS

**Comment by bridzius** [comment]
#10992 Would assume that index.html file replacement was actually an expected functionality in 6.1 Angular at least - has the definition changed to only include bundled files?

**Comment by clydin** [comment]
It's always been that case.  It just so happened that it unintentionally worked for the index.html in several previous versions. The `index` option is intended to control the input index.html file and will be receiving improvements within the 8.x timeframe to support input and output path control.

**Comment by abouroubi** [comment]
@clydin unintentional or not, this was the official answer when the feature was asked for. 

Also @alan-agius4 as far as I know we're not on a dictatorship, throwing your answer and closing the issue without even letting the OP, or others that need the feature, answer. 

This change broke a lot of builds.

**Comment by alan-agius4** [comment]
@clydin implemented https://github.com/angular/angular-cli/pull/15010 which offers more control over the index html and is available in the 8.2 beta version.

Apologies for any inconvenience caused.

**Comment by WoNd3RBoY** [comment]
> even .ts not worked for me
> 
> ```
> //angular.json -> projects.myProject.architect.build.configurations.dev :
> //also in architect.server section
> 
> "dev": {
>               "fileReplacements": [
>                 {
>                   "replace": "src/environments/index.ts",
>                   "with": "src/environments/dev.ts"
>                 }
>               ]
>             }
> ```
> 
> ```
> //src/environments/index.ts
> console.log("index")
> ```
> 
> ```
> //src/environments/dev.ts
> console.log("dev")
> ```
> 
> `> ng run myProject:build:dev && ng run myProject:server:dev && npx webpack --config webpack.server.config.js --progress --colors && nodemon dist/server --inspaect --open --watch`
> 
> `import env from "../src/environments/index.ts" //<--- should be replaced with dev.ts`
> 
> it prints the console.log of index.ts not dev.ts
> 
> repo: https://github.com/xxyyzz2050/eldeebCMS

Did you manage to fix this? I am having the same problem.

**Comment by chrispoupart** [comment]
It would be nice if the documentation was updated with this feature, and if someone could provide an example.

**Comment by tomwhite007** [comment]
Yes, the docs on `--index` are distinctly lacking.

**Comment by schankam** [comment]
Had to use @boban984 [https://github.com/angular/angular-cli/issues/14599#issuecomment-499893113 ](answer) to make it work. If you just let the index.prod.html in the root folder, and use it with  --index, it will not be renamed properly... Don't get it, was working fine before and just realized today that our prod file was not the expected one 😫🤬Not cool

**Comment by Nodarii** [comment]
Example of https://github.com/angular/angular-cli/pull/15010 configuration: 
```javascript
"architect":{
  "build": {
    "options": {
     "index": "src/index.html", //non-prod
    },
    "configurations": {
      "production":{
      "index": { //prod index replacement
        "input": "src/index.prod.html",
        "output": "index.html
      }
    }
  }
}
```

**Comment by kettunen** [comment]
I almost pushed our app to production with wrong index.html :(

@Nodarii answer works after deleting $schema -property (which is not nice) from angular.json. Schema seems outdated because it says that index should be a string.
