### ISSUE TITLE
feat(webpack): support env variables for index.html

### ISSUE THREAD

**Issue by dzonatan** [angular/angular-cli#1460]
It would be great to still have some kind of **env variables** or settings for index.html as we had previously with broccoli.
One of the use case would be setting `<base href` for different environments which I need now...

**Comment by filipesilva** [comment]
I don't think we ever supported adding custom variables to index.html, but there is a feature request for the base tag already in https://github.com/angular/angular-cli/issues/1064.

**Comment by dzonatan** [comment]
You did.. At least I was able to use any **env** variable by `{{environment.myVar}}` interpolation.
So in my case it was `<base href="{{environment.baseHref}}">`.

Even originally the new project had some usages:
```
{{#unless environment.production}}
  <script src="/ember-cli-live-reload.js" type="text/javascript"></script>
{{/unless}}
```

So I think it's kinda breaking change after webpack merge.

**Comment by filipesilva** [comment]
Huh, that must have been base functionality of ember-cli that we never really noticed. The best I can do now is to bump the priority of that base href feature, I'll try to work on it soon.
