### ISSUE TITLE
Add support for adding a value provider to a NgModule using schematics

### ISSUE THREAD

**Issue by EdricChan03** [angular/angular-cli#14608]
# 🚀 Feature request

### Description

I'm currently working on a library which is an HTTP wrapper of the YouTube Data v3 API: https://github.com/EdricChan03/ngx-ytd-api

Right now, I'm trying to add the ability for a developer to specify an API key to be used for all of the API classes. So far, I've supported that with an injection token, but I would like to simplify that for the developer with the `ng-add` schematic which would ask for an API key and declare that API key in the injection token accordingly.

However, I can't seem to find any way to import a value provider into the `NgModule` decorator. AFAIK, there's an `addProviderToModule` method in `@schematics/angular/utility/ast-utils`, but it only supports class providers:

https://github.com/angular/angular-cli/blob/6ec09919b5c2695dee784ce0c3accee7f9754bb0/packages/schematics/angular/utility/ast-utils.ts#L506-L513

### Describe the solution you'd like

A custom method which would allow for a value provider to be added to a module.

### Describe alternatives you've considered

* Indicate that developers must specify the injection token manually, or set the API key explicitly for any calls to the API methods
* Implement an internal provider in the module used (aka `forRoot`)

**Comment by alan-agius4** [comment]
Hi, as far as I recall these methods fall under the private API.

That said, we definitely should should provide a set of utility methods.

//cc @clydin please correctly if I am am wrong.

**Comment by FabienDehopre** [comment]
any news on this feature request ?

**Comment by alan-agius4** [comment]
Hi, the above mentioned method is part of the private API and is not intended to be used by 3rd parties.

If used externally, please be aware that they such methods can be removed/break in non major versions.
