### ISSUE TITLE
Cannot read property 'NoopAnalytics' of undefined

### ISSUE THREAD

**Issue by glebmachine** [angular/angular-cli#14616]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [x] generate
- [x] add
- [x] update
- [x] lint
- [x] xi18n
- [x] run
- [x] config
- [x] help
- [x] version
- [x] doc
```

### Is this a regression?
Yes, `ng` command stop working

### Description
on run `ng` i've got:
```
Cannot read property 'NoopAnalytics' of undefined
TypeError: Cannot read property 'NoopAnalytics' of undefined
    at new Command (*/node_modules/@angular/cli/models/command.js:21:68)
    at new ArchitectCommand (*/node_modules/@angular/cli/models/architect-command.js:22:9)
    at new RunCommand (*/node_modules/@angular/cli/commands/run-impl.js:11:1)
    at Object.runCommand (*/node_modules/@angular/cli/models/command-runner.js:172:25)
    at async default_1 (*/node_modules/@angular/cli/lib/cli/index.js:32:31)
```

## 🔬 Minimal Reproduction
updated from 7 to 8

## 🔥 Exception or Error
<pre>Cannot read property 'NoopAnalytics' of undefined
TypeError: Cannot read property 'NoopAnalytics' of undefined
    at new Command (*/node_modules/@angular/cli/models/command.js:21:68)
    at new ArchitectCommand (*/node_modules/@angular/cli/models/architect-command.js:22:9)
    at new RunCommand (*/node_modules/@angular/cli/commands/run-impl.js:11:1)
    at Object.runCommand (*/node_modules/@angular/cli/models/command-runner.js:172:25)
    at async default_1 (*/node_modules/@angular/cli/lib/cli/index.js:32:31)<code>

</code></pre>

## 🌍 Your Environment
<pre>
I can't ng don't work :), so here is my package.json:

  "dependencies": {
    "@nrwl/angular": "8.0.0",
    "@angular/animations": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@angularclass/hmr": "^2.1.3",
    "@betadigitalproduction/ngx-platform-service": "^1.0.7",
    "@ngqp/core": "^1.0.0",
    "@ngrx/effects": "^7.4.0",
    "@ngrx/entity": "^7.4.0",
    "@ngrx/router-store": "^7.4.0",
    "@ngrx/schematics": "^7.4.0",
    "@ngrx/store": "^7.4.0",
    "@ngrx/store-devtools": "^7.4.0",
    "@ngx-pwa/local-storage": "8.0.0",
    "@ngx-translate/core": "11.0.1",
    "@sentry/browser": "5.3.0",
    "core-js": "^3.1.3",
    "date-fns": "^2.0.0-alpha.27",
    "localize-router": "2.0.0-RC.2",
    "ng-svg-icon-sprite": "1.6.0",
    "ng-zorro-antd": "^7.4.1",
    "ngx-build-plus": "8.0.0-rc.3.0.1",
    "nprogress": "^0.2.0",
    "rxjs": "6.5.2",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@nrwl/workspace": "8.0.0",
    "@nrwl/jest": "8.0.0",
    "@nrwl/cypress": "8.0.0",
    "@angular-devkit/build-angular": "~0.800.1",
    "@angular-devkit/build-ng-packagr": "~0.800.1",
    "@angular/cli": "8.0.1",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "^8.0.0",
    "@betalabs/ngx-observable-input": "^0.1.8",
    "@betalabs/ngx-take-until-destroy": "^0.1.9",
    "@biesbjerg/ngx-translate-extract": "2.3.4",
    "@ngrx/store-devtools": "7.4.0",
    "@types/jest": "24.0.13",
    "@types/jquery": "3.3.29",
    "@types/node": "~12.0.4",
    "@types/webpack": "^4.4.31",
    "codelyzer": "^5.0.1",
    "conventional-changelog-cli": "2.0.21",
    "cypress": "3.3.1",
    "cz-conventional-changelog": "2.1.0",
    "dotenv": "8.0.0",
    "jest": "24.8.0",
    "jest-preset-angular": "7.1.1",
    "junit": "^1.4.9",
    "mocha-junit-reporter": "^1.22.0",
    "ng-packagr": "^5.2.0",
    "ngrx-store-freeze": "0.2.4",
    "prettier": "1.17.1",
    "svg-sprite-generator": "0.0.7",
    "ts-jest": "24.0.2",
    "ts-node": "~8.2.0",
    "tsickle": ">=0.34.0",
    "tslib": "^1.9.0",
    "tslint": "~5.17.0",
    "typescript": "3.5.1"
  }

**Comment by clydin** [comment]
Can you check what version the globally installed `@angular/cli` is on your system?

**Comment by glebmachine** [comment]
@clydin  `8.0.1` ofcourse.
Reproduced on my windows pc (first seen on the latest mac)

**Comment by juristr** [comment]
🤔 I just got the same error, happening [here](https://github.com/angular/angular-cli/blob/7a72f2fb1757c02ed7964591d0205b70bbe0c406/packages/angular/cli/models/command-runner.ts#L71). Looks like as if the imported `analytics` object is not defined which is really strange. When I generate a new v7 project and upgrade, the error doesn't happen. Happens when I upgrade my nrwl/nx based project. Maybe NX changes that part of the upgrade process? @FrozenPandaz any insights here?

**Comment by yishain11** [comment]
same issue here, on centos 7

**Comment by SebasG22** [comment]
@juristr @FrozenPandaz same to me. I'm getting stuck with NX migration from 7 to 8.
![image](https://user-images.githubusercontent.com/17608169/58870648-384fbc00-8686-11e9-8e0b-418ec88cb4e3.png)

**Comment by lorenjerickson** [comment]
+1 for being related to nrwl/nx project upgrading from cli@7 to 8.  I don't have @angular-devkit/schematics listed in package.json, but I still see the same error.

**Comment by JoshDSommer** [comment]
I had success getting rid of this message by clearing my node modules folder and re-installing. 
exact steps I took were `rm -rf node_modules` then `yarn` to re-install the deps. yours obviously may be different because of packager etc. 

hope that helps

**Comment by SebasG22** [comment]
thanks @JoshDSommer.
My issue was the a mismatch on the global dependencies installed for `@angular/cli`.
This issue can be closed.

**Comment by mgechev** [comment]
@lorenjerickson @juristr @yishain11 @glebmachine can you confirm if matching versions between local & global CLI resolves the issue?

**Comment by glebmachine** [comment]
Nope!

Also, i've updated to 8.0.3, and error still there : (

**Comment by yishain11** [comment]
@mgechev it didn't solve the issue for me

**Comment by YoeriNijs** [comment]
For us, it helped to remove the local node_modules prior to npm install.

**Comment by Teamop** [comment]
I met this issue also after I upgraded to v8. I debugged a little, seems the v8 cli invokes the `@angular-devkit/core@7`, then it cannot find the `NoopAnalytics`, so I reinstalled the `@angular-devkit/core` again, then this error was gone.

**Comment by mgechev** [comment]
Where was the old version of `@angular-devkit/core`? In the workspace `node_modules` or in a top-level directory?

**Comment by Teamop** [comment]
@mgechev I have the old `@angular/cli@7.x` installed globally, for the workspace, I installed v8 of `@angular/cli` and `@angular/cli`, I don't know why, but when running the cli under the workspace, seems it invokes the v8 cli correctly, but didn't find the v8  `@angular-devkit/core`.
package manager: `yarn`

**Comment by glebmachine** [comment]
Everything is ok now
