### ISSUE TITLE
@ngToolWebpack build failed on Windows

### ISSUE THREAD

**Issue by nguyenmtuanctk35** [angular/angular-cli#14612]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.2.9

### Description
The build has passed on Mac, but on Windows, I got the error as below:
<pre><code>
ERROR in (webpack)/hot/emitter.js
Module not found: Error: Recursion in resolving
Stack:
  resolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) events
  newResolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) events
  parsedResolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) events module
  describedResolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) events module
  resolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) E:\SourceCode\application-portal\client\node_modules\node-libs-browser\node_modules\events\events.js module
  newResolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) E:\SourceCode\application-portal\client\node_modules\node-libs-browser\node_modules\events\events.js module
  parsedResolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) E:\SourceCode\application-portal\client\node_modules\node-libs-browser\node_modules\events\events.js
  describedResolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) E:\SourceCode\application-portal\client\node_modules\node-libs-browser\node_modules\events\events.js
  resolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) E:\SourceCode\application-portal\client\node_modules\node-libs-browser\node_modules\events\events.js
  newResolve: (E:\SourceCode\application-portal\client\node_modules\webpack\hot) E:\SourceCode\application-portal\client\node_modules\node-libs-browser\node_modules\events\events.js
 @ (webpack)/hot/emitter.js 1:19-36
 @ (webpack)/hot/dev-server.js
 @ multi (webpack)-dev-server/client?https://localhost:8080 (webpack)/hot/dev-server.js ./src/polyfills.browser.ts
</code></pre>

## 🌍 Your Environment
<pre><code>
NodeJS: v8.10.0
NPM: 5.6.0

"@ngtools/webpack": "7.3.9"
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by mgechev** [comment]
@nguyenmtuanctk35 any updates?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
