### ISSUE TITLE
ES2015 Class with decorators are not being treeshaken away

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#14610]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
When not using tsickle, TypeScript emits the following code for classes which have property or method decorators

```ts
export class foo {
    bar() {
    }
}
__decorate([
    decorator()
], foo.prototype, "bar", null);
```

The problematic as terser is unable to drop the above code if the Class is unused.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0
Node: 11.0.0
OS: win32 x64
Angular: 8.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

Related to #14577

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

still facing same issue, tree-shaking not working properly

angular/angular-cli#15396
