### ISSUE TITLE
Application Styles not working

### ISSUE THREAD

**Issue by Fercho11** [angular/angular-cli#14615]
Hello.
I started migration to Angular 8 but, at the moment to start local debug, styles don't working, I updated compiler for sass to current version.
This is my package:
Angular CLI: 8.0.0
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                                    Version
--------------------------------------------------------------------
"dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular/animations": "8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/fire": "^5.0.2",
    "@angular/forms": "8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/material-moment-adapter": "^8.0.0",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/platform-server": "8.0.0",
    "@angular/router": "8.0.0",
    "@nguniversal/common": "^6.0.0",
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "@types/crypto-js": "^3.1.43",
    "@types/googlemaps": "^3.30.16",
    "chalk": "^2.4.2",
    "chart.js": "^2.7.3",
    "crypto-js": "^3.1.9-1",
    "docxtemplater": "^3.9.9",
    "express": "latest",
    "express-validator": "^5.3.1",
    "firebase": "^5.5.3",
    "gulp-zip": "^4.2.0",
    "hammerjs": "^2.0.8",
    "html-pdf": "^2.2.0",
    "hummus": "1.0.95",
    "jsdom": "^13.2.0",
    "jszip": "^2.6.1",
    "md5": "^2.2.1",
    "memory-streams": "^0.1.3",
    "morgan": "^1.9.1",
    "ng2-pdf-viewer": "^5.2.4",
    "ngx-image-cropper": "^1.2.2",
    "pdfjs-dist": "^2.0.943",
    "puppeteer": "1.13.0",
    "rb-timepicker": "^2.1.2",
    "remote-exec": "0.0.3",
    "request": "^2.88.0",
    "rxjs": "6.5.2",
    "saturn-datepicker": "^7.2.0",
    "shelljs": "^0.8.3",
    "signature_pad": "^3.0.0-beta.3",
    "swagger-ui-express": "^4.0.2",
    "tslib": "^1.9.0",
    "webpack": "^4.27.1",
    "webshot": "^0.18.0",
    "winston": "^3.2.0",
    "word2pdf-promises": "^1.2.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular-devkit/build-optimizer": "^0.7.5",
    "@angular/cli": "^8.0.0",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "8.0.0",
    "@types/chart.js": "^2.7.42",
    "@types/compression": "0.0.36",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/nconf": "^0.10.0",
    "@types/node": "^6.0.114",
    "browserify": "^16.2.2",
    "codelyzer": "^5.0.1",
    "commander": "^2.18.0",
    "compression": "^1.7.3",
    "gulp": "^4.0.2",
    "gulp-gzip": "^1.4.2",
    "gulp-rename": "^1.4.0",
    "inquirer": "^6.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "nconf": "^0.10.0",
    "node-cmd": "^3.0.0",
    "node-sass": "^4.12.0",
    "nodemailer": "^4.6.8",
    "protractor": "^6.0.0",
    "standard-version": "^4.4.0",
    "ts-loader": "^4.4.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.3.2",
    "typescript": "3.4.5",
    "uglify-js": "^3.4.9",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.1.0",
    "webpack-node-externals": "^1.7.2"
  }

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by destus90** [comment]
Maybe it related to #14587 
Replace the absolute paths by relative in all your scss files.

**Comment by Fercho11** [comment]
Sorry.
I can solve the error, the problem is the new encapsulation for styles.
The solution is add the next line in @Component()
encapsulation: ViewEncapsulation.None

https://angular.io/guide/component-styles#view-encapsulation
