### ISSUE TITLE
Terminal progress on multiple lines if line wraps

### ISSUE THREAD

**Issue by ChristopherKiss** [angular/angular-cli#14623]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I believe this worked fine at one point, maybe around v6 or early v7, but stopped working after, I can't remember exact version.

### Description

Hi guys,

I previously reported this issue #13800, however I didn't know what the cause was. I have recently found a way to reproduce it, VS Code reports that it isn't their issue: https://github.com/microsoft/vscode/issues/74695 in addition I've tried with conpty off and I get the same result.

The issue is that running any command which reports progress, if the width of the terminal is small enough that the line would wrap to the next line, it create a new line instead of overwriting the current line.

## 🔬 Minimal Reproduction

1. Make the width of the terminal small enough that the progress lines will wrap to a new line.
2. Run ng serve
3. Observe that the progress is reported on new lines for any line that would wrap to a new line

![image](https://user-images.githubusercontent.com/24984762/58742867-9bfd9d80-846a-11e9-868a-1cbc5a267d14.png)

4. Make the width of the terminal bigger so that none of the lines would wrap to a new line
5. Run ng serve
6. Observe that progress correctly overwrites the previous line.

![image](https://user-images.githubusercontent.com/24984762/58742869-b33c8b00-846a-11e9-869b-a1523dc09804.png)

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.1
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
This occurs in both VS Code and when running Powershell directly.

Let me know if you need any additional information. Thank you.

**Comment by alan-agius4** [comment]
Hi, @ChristopherKiss, I am still unable to replicate the above issue, even with a small terminal.

![image](https://user-images.githubusercontent.com/17563226/58790288-5ff44500-85f0-11e9-9cb1-3d4414307b8f.png)


Since for the progress reporting we use Webpack [ProgressPlugin](https://webpack.js.org/plugins/progress-plugin/), I suggest that you fill an issue in their issue tracker (https://github.com/webpack/webpack), maybe they have better insights why this is happening to you.

Thanks.

**Comment by ChristopherKiss** [comment]
@alan-agius4,

Thanks for taking the time to look again, I'll keep travelling down the rabbit hole.

I don't know why it's not reproducible, hopefully the webpack guys will know.
