### ISSUE TITLE
Add information about `browerslist` config to the verbose output in v.8 or later

### ISSUE THREAD

**Issue by peterblazejewicz** [angular/angular-cli#14620]
# 🚀 Feature request

### Command `ng build --verbose `

- [x] build

### Description

In v.8 the `browserslist` configuration file(s) is used to create differential loading. As the Angular workspace now supports multiple projects (of different types), it would be useful to see which `browserslist` config file was used during a project build

### Describe the solution you'd like

When I use `--verbose`, I'd like to see additional information poiting me which `browserlists` configuration file has been used during project build, like:

```bash
...
Built at: 05/31/2019 11:40:15 PM
               Asset      Size     Chunks                    Chunk Names
         favicon.ico   5.3 KiB             [emitted]         
         main-es5.js  9.18 KiB       main  [emitted]         main
     main-es5.js.map  5.27 KiB       main  [emitted]         main
    polyfills-es5.js   666 KiB  polyfills  [emitted]  [big]  polyfills
polyfills-es5.js.map   484 KiB  polyfills  [emitted]         polyfills
      runtime-es5.js  6.08 KiB    runtime  [emitted]         runtime
  runtime-es5.js.map  6.07 KiB    runtime  [emitted]         runtime
       styles-es5.js  16.9 KiB     styles  [emitted]         styles
   styles-es5.js.map  19.3 KiB     styles  [emitted]         styles
       vendor-es5.js  3.47 MiB     vendor  [emitted]  [big]  vendor
   vendor-es5.js.map  3.59 MiB     vendor  [emitted]         vendor
browserslist: ./browserslist
and_chr 74
and_ff 66
and_qq 1.2
and_uc 11.8
android 67
android 4.4.3-4.4.4
baidu 7.12
chrome 74
chrome 73
chrome 72
chrome 49
edge 18
edge 17
firefox 66
firefox 65
firefox 60
ie 11
ie_mob 11
ios_saf 12.2
ios_saf 12.0-12.1
ios_saf 11.3-11.4
kaios 2.5
op_mini all
op_mob 46
opera 58
opera 57
safari 12.1
safari 12
samsung 9.2
samsung 8.2
samsung 4
...
```

### Describe alternatives you've considered
n/a

v.8.0.1

Thanks!

**Comment by mgechev** [comment]
Do you think providing information if ES5 browser support is required would provide more value? Currently, you can easily check the browserlist value by `cat browserlist` at any time.

**Comment by alan-agius4** [comment]
Closing as per above answer.
