### ISSUE TITLE
Choose ES target level

### ISSUE THREAD

**Issue by pauldraper** [angular/angular-cli#14639]
It appears that Angular CLI outputs only in ES5.

I would like to be able to choose the ES target, e.g. ES2015.

This can produce **smaller,** **faster,** and more **readable** code.
(And yes, sources maps can account for the readability part, but they have their own sets of disadvantages, including terrible performance for the CLI.)

Compare

```js
class A { example() { return 5 } }
```

and

```js
A = function() {}; A.prototype.example = function() { return 5 }
```

**Comment by clydin** [comment]
The desired output target can be configured via the application's `tsconfig.json`.  All new projects created via 8.0+ default to using ES2015 with differential loading enabled to also generate ES5 bundles for older browsers.

**Comment by williangd** [comment]
@clydin Is it possible to build only for ES2015?

**Comment by istiti** [comment]
@williangd yes it is, to know if cli should build es5 he simply check this page : https://caniuse.com/#feat=es6-module

Inside `tsconfig.ts` you can already target `es2015` **BUT** depending on the content you have inside your `browserslist` file, it will also make another build for `es5` too !

There is two possiblities to build es2015 only:
1. set `tsconfig.ts` target to `es2015` and remove whole content inside your `browserslist` file

2. set `tsconfig.ts` target to `es2015` and put inside your browserslist this content : 
```
Chrome >= 61
Firefox >= 60
Safari >= 11
Opera >= 48
Samsung >= 8
Android >= 67
ChromeAndroid >= 74
FirefoxAndroid >= 66
```

If you visit my [caniuse es6-module support](https://caniuse.com/#feat=es6-module) link you will see all these versions are green.

N.B. **Remove browserslist will not works as empty content !**

**Comment by pauldraper** [comment]
Through trial and error, it seems the `browserslist` file should be in the project root.

Can't find any documentation on this file. :/

**Comment by clydin** [comment]
You can find details regarding the file including query options, file resolution, and alternative configuration locations here: https://github.com/browserslist/browserslist/blob/master/README.md

**Comment by pauldraper** [comment]
Thanks @clydin .

In my defense, something Angular-specific is relevant, because the version 8 upgrade schematic includes move src/browserlist to browserlist. (That code is how I figured out where I should add the file.)

**Comment by LizaVoskanyan** [comment]
@pauldraper thanks a lot. you saved my day. :) But it's crazy that the browserlist file is in the `src/browserlist` when it should be in the root... maybe the angular team needs to fix this.

**Comment by JohnnyDevNull** [comment]
@pauldraper it depends more on the angular.json "root" path of the project.

For example if you have a mono style workspace where your projects are under `projects/my-angular-client` then this is your browserlist file directory.
