### ISSUE TITLE
core-js dependency not removed after updating to v8

### ISSUE THREAD

**Issue by markgoho** [angular/angular-cli#14636]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No.

### Description
Per https://github.com/angular/angular-cli/issues/13954#issuecomment-485822832 - should the project dependency on `core-js` be removed when updating? It isn't present in new v8 projects.

## 🔬 Minimal Reproduction
Run `ng update @angular/cli @angular/core` on a v7 project. See that after the update, `core-js` is still listed as a dependency.

**Comment by destus90** [comment]
I've upgraded my project some days ago and these polyfills were deleted from my `polyfills.ts` file. 
```
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/set';
```

**Comment by alan-agius4** [comment]
Closing as per above comment.
