### ISSUE TITLE
Angular proxy.conf.js uses wrong gateway

### ISSUE THREAD

**Issue by Codehan25** [angular/angular-cli#14642]
I have a large Angular application, in which several gateways must be defined.

I implemented this in my **proxy.con.js** file, adapted my **visual studio code tasks** and the **angular.json** file.

Nevertheless, for a specific API call, a wrong gateway is always used rather than the one defined for it.

**My proxy.conf.js looks like this:**

    var HttpsProxyAgent = require('https-proxy-agent');
    var proxyConfig = [
      {
        context: '/api/**',
        target: process.env.gateway_1,
        changeOrigin: true,
        agent: new HttpsProxyAgent(process.env.http_proxy || process.env.HTTP_PROXY),
        secure: false,
        logLevel: 'debug'
      },
      {
        context: '/resources**',
        target: process.env.gateway_1,
        changeOrigin: true,
        agent: new HttpsProxyAgent(process.env.http_proxy || process.env.HTTP_PROXY),
        secure: false,
        logLevel: 'debug'
      },
      {
        context: '/api/v1/vehicles/**',
        target: process.env.gateway_2,
        changeOrigin: true,
        agent: new HttpsProxyAgent(process.env.http_proxy || process.env.HTTP_PROXY),
        secure: false,
        logLevel: 'debug'
      },
      {
        context: '/api/v1/vehicles**',
        target: process.env.gateway_2,
        changeOrigin: true,
        agent: new HttpsProxyAgent(process.env.http_proxy || process.env.HTTP_PROXY),
        secure: false,
        logLevel: 'debug'
      }
    ];
    
    module.exports = proxyConfig;

**The serve target inside the angular.json looks like this:**

    "serve": {
      "builder": "@angular-devkit/build-angular:dev-server",
      "options": {
        "browserTarget": "my-ui:build",
        "port": 8080,
        "ssl": true,
        "proxyConfig": "src/proxy.conf.js"
      },
     ...

The scripts part of the package.json looks like this:

      "scripts": {
        "ng": "ng",
        "start": "ng serve --base-href=/ui/",
       ...

**And my visual studio code tasks inside the tasks.json looks like this:**

    {
        "version": "2.0.0",
        "options": {
          "env": {
            "gateway_1": "https://gateway1.apps.de1.my-cloud.com",
            "gateway_2": "https://gateway2.apps.de1.my-cloud.com",
            "http_proxy": "http://localhost:3128",
          }
        },
        "tasks": [
          {
            "type": "shell",
            "label": "Start Application",
            "command": "npm run start"
          },
        ....

Only gateway_1 is used. For all calls, which must go over the gateway_2 I receive a 404. The CLI shows me also that the wrong gateway is taken.

> GET /api/v1/vehicles?Size=100&type=xyz ->
> https://gateway**1**.apps.de1.my-cloud.com

Instead of

> GET /api/v1/vehicles?Size=100&type=xyz ->
> https://gateway**2**.apps.de1.my-cloud.com

What am I doing wrong?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
