### ISSUE TITLE
Operate in non-CLI projects - Feature Request

### ISSUE THREAD

**Issue by kylecordes** [angular/angular-cli#1464]
This is a feature request. As an alternative to the message "You have to be inside an angular-cli project", instead CLI could offer a subset of it capabilities even in non-CLI projects.

To do this, CLI would note the absence of CLI configuration files, print message about this, then make assumptions based on defaults and on what files/directories are present.

With these assumptions, CLI could provide a useful subset of its full feature set. It could generate components and most other types. Skip lacing up any aspect which can't be done without full CLI config.

Over time it might be possible to do even more than generate, some other features may be possible in non-CLI projects also.

In addition to offering value to non-CLI projects, this feature could also encourage CLI adoption. It would provide an easy on-ramp: any existing project can start using CLI immediately, but with each use, CLI can print messages about extra things it _could_ have done, if the project was a full CLI project.

**Comment by centigrade-thomas-becker** [comment]
I wanted to use angular-cli as a quick tool to generate components without having to overhaul my project.

**Comment by filipesilva** [comment]
You can currently do this for the most part. The only config items in `angular-cli.json` that are truly necessary is the `apps[0].root` entry, and either `main` or `scripts`.

This is supported and tested for, but not documented as it's fairly low prio atm. See https://github.com/angular/angular-cli/blob/master/tests/e2e/tests/misc/minimal-config.ts for examples.

**Comment by redevill** [comment]
Would also like to leverage CLI, in a non CLI project. Link to examples is broken :(
