### ISSUE TITLE
Service worker is not registered or does not control the start url angular

### ISSUE THREAD

**Issue by shivalipawar** [angular/angular-cli#14645]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [X ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I have tested with v6.2.3 and 8.2.0 , 7.3.9 but none of them seem to solve the error.

### Description

 Once you build angular with PWA and use command,
              http-server -p 8080 -c-1 dist/<project-name>
It generates,

Available on:
  http://10.235.2.151:8081
  http://127.0.0.1:8081             

Service worker is not registered for 1st url but works for 2nd url.

## 🔬 Minimal Reproduction

Followed steps in the official doc for setting up the service worker: https://angular.io/guide/service-worker-getting-started 
 
No errors, all goes well but when loading the app in the browser the service worker is not being registered.

Happens for ng serve as well as for the hosted app,
eg :-

Check  link :- http://pwapushnotification.s3-website-us-east-1.amazonaws.com 

## 🔥 Exception or Error
<pre><code>

Service worker is not registered or does not control the start url angular
</code></pre>

![image](https://user-images.githubusercontent.com/11486549/58796845-ff7afd00-861b-11e9-80f0-fcfbd4e96ead.png) 

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@angular/pwa                      0.800.1
@angular/service-worker           8.0.0
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

It was hosted using HTTP Server and ng serve as well but fails.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by shivalipawar** [comment]
Hey Alan,

Thanks for quick response i have created a github repo which you can clone at your end.
Also use `npm  http-server` to host locally and check difference in both urls given by http-server.

Repo Link :- [PWADemo2](https://github.com/shivalipawar/PWADemo2.git)

**Comment by alan-agius4** [comment]
Hi, I had a look at this, and it seems that the service worker is being registered fine in `http://127.0.0.1:8080` however it is not on `http://192.168.56.24:8080`.

This is expected as Service Workers only work on localhost without HTTPS when deploying the application this needs to be deployed in an HTTPS environment.


We should clarify the docs and state this requirement. For this purpose I opened this issue: https://github.com/angular/angular/issues/30823

**Comment by shivalipawar** [comment]
Hi Alan,

It seems correct whatever you have mentioned as i'm able to get service worker registered on https environment now.
Thank you!
