### ISSUE TITLE
Creating a new Angular 8 project doesn't give me options

### ISSUE THREAD

**Issue by devpato** [angular/angular-cli#14640]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
```

### Is this a regression?
Yes, **Angular 7 CLI**  used to have the functionality
![1_iCOVKdl5WbAo0uoOnEmzEw](https://user-images.githubusercontent.com/11162114/58770539-6046fe80-8564-11e9-8ace-52ec419510fa.png)

### Description
I'm creating a new Angular 8 project and I was trying to set the style sheets to SCSS and create angular routing from the beginning of the project. I know I can do it manually, but it was pretty nice to have the menu of options in the command line.

Now I have to do:  `ng new my-project --style=scss --routing`

## 🔬 Minimal Reproduction

`ng new my-project`

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.1
@angular-devkit/core         8.0.1
@angular-devkit/schematics   8.0.1
@schematics/angular          8.0.1
@schematics/update           0.800.1
rxjs                         6.4.0
</code></pre>

**Comment by alan-agius4** [comment]
Can you try to uninstall the global CLI and try again? I tried this locally and is working as expected.

```cmd
npm unistall @angular/cli -g
npm i  @angular/cli -g
```

Thanks.

**Comment by devpato** [comment]
@alan-agius4  didn't work. 
![Capture](https://user-images.githubusercontent.com/11162114/58930064-cf605680-870e-11e9-9a72-19e87c289a06.JPG)

**Comment by devpato** [comment]
I tried again doing the following:
```

- npm uninstall -g @angular/cli
- npm cache verify
- npm i  @angular/cli -g
```

didn't work either
