### ISSUE TITLE
Cant update angular cli and core

### ISSUE THREAD

**Issue by andrewdaylondon** [angular/angular-cli#14650]
PS D:\_current tutorial\Angular-7-formerly-Angular-2---The-Complete-Guide-master\Codes - 1\S09\services-start\services-start> ng update @angular/cli @angular/core
Your global Angular CLI version (7.3.8) is greater than your local
version (6.0.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
                  Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/platform-browser" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/common" (requires ">=7.0.0-rc.0 <8.0.0||>=2.3.1 <7.0.0||>6.0.0-beta <7.0.0", would install "8.0.0").
Incompatible peer dependencies found. See above.
PS D:\_current tutorial\Angular-7-formerly-Angular-2---The-Complete-Guide-master\Codes - 1\S09\services-start\services-start>

**Comment by andrewdaylondon** [comment]
Shortening the name of all the folders has helped with the malformed part and installing the seperate files to version 8 seems to have done the trick.  And thanks for moving the browser link to the bottom Cheers

**Comment by istiti** [comment]
Hi, it’s not easy to help you like that, if you want feedback from team or community you should highly follow template issue. https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submission-guidelines

**Comment by andrewdaylondon** [comment]
It's fixed, but thanks

**Comment by Ankitacse** [comment]
packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed.
how fixed?

**Comment by Londovir** [comment]
I too have been hit with this, and there's no diagnostic/debugging information I can see. I simply cannot use the expected ng update commands to update cli or core at all. I get hit with about 7 different "malformed metadata" error messages, then get nailed with a codelyzer incompatible peer dependency, and it just gives up at that point.

I'm not thrilled with manually updating every individual cli and core entry in package.json, but I'm afraid at this point my only hope is to use the cli to spin up a new 8.0 "Hello World" project, and then manually diff/correct my project from all of the temp projects values.

**Comment by NRaf** [comment]
Also having issues trying to update.

I'm being the following:

Your global Angular CLI version (7.1.3) is greater than your local
version (7.0.6). The local Angular CLI version is used.

```
To disable this warning use "ng config -g cli.warnings.versionMismatch false".
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
    packageGroup metadata of package @angular/cli is malformed. Ignoring.
Cannot read property 'split' of null
```

**Comment by oorobets** [comment]
> packageGroup metadata of package @angular/cli is malformed. Ignoring.
> packageGroup metadata of package @angular/cli is malformed.
> how fixed?

It was not. Person did not follow template, that's why they closed it. :|

**Comment by andrewdaylondon** [comment]
Oh no I didnt follow the template, I'm such a bad person aaaaaAAAAAAAWWWWWwwwww!
I used angular cli 6.2.8 which worked, thats hope some can fix such a major issue before we all move over to React.

**Comment by oorobets** [comment]
In my case I was updating from Angular 6.1 to angular@latest, which is version 8 right now. Upgrade to version 7.3.9 worked just fine. 

According to https://update.angular.io/
> Warning: We do not recommend moving across multiple major versions.

**Comment by driiftkiing** [comment]
This command is working for me `ng update @angular/cli@~7.0.0`

**Comment by caroso1222** [comment]
Try a hard update: `ng update [pkg] --force`
