### ISSUE TITLE
Super slow build time while updating to v8.0.0

### ISSUE THREAD

**Issue by hugo-marello** [angular/angular-cli#14666]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Previous versions were way faster, last compiled with 7.2.0

 

### Description

 Tryed to update my large angular application to version 8.0.0, but the build takes forever.

## 🔬 Minimal Reproduction
Create a v6 angular app and follow the instructions on https://update.angular.io to update it to v8.0.0 . Build the application with `node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --verbose --no-progress > log.txt`

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.1
Node: 10.15.2
OS: linux x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
My guess is the angular-devkit/build-angular is the culprit, it was known to have caused slowness in the past. I've run the benchmark inside the webpack script, I've posted the first half hour of execution. 
[log.zip](https://github.com/angular/angular-cli/files/3254300/log.zip)

**Comment by alialtun14** [comment]
Hi @hugo-marello. I have the same problem. But the interesting thing is that only two people (according to stockover veya github issue ) have met this problem so far. The problem seems to be related to node12.

https://github.com/angular/angular-cli/issues/14604

**Comment by jocstech** [comment]
I have the same slow-compiling issues here when using angular 8

**Comment by alan-agius4** [comment]
Hi @hugo-marello,

Thanks for the information provided. However, let's keep this in a single thread being https://github.com/angular/angular-cli/issues/13734

Thanks

**Comment by micobarac** [comment]
@alan-agius4, what does this problem have to do with single thread you mentioned? I have the same slow build times with Angular 8, too.

**Comment by julianpoemp** [comment]
@alan-agius4 can you please reopen this issue? There are a lot of people having this problem.

I tried to find a solution, but nothing helps to get the fast building like in Angular 6. With Angular 6 the build --prod time was like 10 seconds and now its 64 seconds. That with this optimizations:

    node --max-old-space-size=8000 ./node_modules/@angular/cli/bin/ng build --prod --aot=false --optimization=true --sourceMap=false --buildOptimizer=false

What can we do to get better build times?

**Comment by mcenkar** [comment]
> What can we do to get better build times?

For me installing node-sass helped a lot

`yarn add node-sass`
