### ISSUE TITLE
browserslist have to be now on project root

### ISSUE THREAD

**Issue by microspa** [angular/angular-cli#14660]
# 🐞 bug report

### Is this a regression?
Yes, the previous version in which this bug was not present was: 7.2.15

### Description
In Angular 8 the file "browserslist" is expected in project root folder.

## 🔬 Minimal Reproduction

- Use the default project structure from Angular 7 or below which was generated by cli. The file browserslist is under src/. 
- Upgrade to Angular 8
- Change browserslist content to:
> 0.5%
last 2 versions
Firefox ESR
not dead
not IE 9-11
not samsung 4
not android 4.4.3-4.4.4
not last 2 ie_mob versions
not last 2 op_mini versions
not last 2 op_mob versions
not last 2 baidu versions
not last 2 kaios versions
not last 2 and_uc versions
not last 2 and_qq versions
not last 2 edge versions
not chrome 49
- Nothing happens on build --prod
- Move browserslist to project root
- Differential loading is now disabled on build because the function [isEs5SupportNeeded](https://github.com/alan-agius4/angular-cli/blob/5b26a39ba83e0358785aab822a63d9e7f0cc2624/packages/angular_devkit/build_angular/src/utils/differential-loading.ts#L26) can now access browserslist and is not using defaults

## 🔥 Exception or Error
Unfortunately no hint or warning

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.1
Node: 12.3.1
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
For me, it was difficult to say that this is really a bug because the solution can be:
- Documentation for it on https://update.angular.io/#7.2:8.0
- `ng update @angular/cli @angular/core` will move the file to project root
- There is an hint or warning on cli prompt
- @angular-devkit/build-angular/src/utils/differential-loading.ts and all other implementations of  browserslist(....) will check src folder too

**Comment by alan-agius4** [comment]
Hi, did you update to angular-cli using the `ng update @angular/cli`? as this should have migrated the file from the `src/` folder to the root folder.

**Comment by alan-agius4** [comment]
Hi, what is the name of your `browserslist ` file? I am seeing that in the above comment you mentioned `browserlist ` however this is not a valid file as it should be `browserslist`.

**Comment by microspa** [comment]
Yeap, sorry I've mistyped. I meant `browserslist` with (s) and the name of my project file was `browserslist` too.

I used `ng update @angular/cli @angular/core` to upgrade my project and under `src` there was the `browserslist` file but it was not moved. 

Strange, I have tried it again on another project. Now it worked fine as you said. The file was moved. I will try the upgrade again with the first project maybe I can reproduce the issue. Thanks for your help!

**Comment by alan-agius4** [comment]
@microspa, thanks for the clarifications. If possible kindly provide a reproduction as otherwise, it's hard to tell what is causing the bug.

Thanks

**Comment by istiti** [comment]
I think this is enough : https://github.com/istiti/update-not-move-browserslist

Remember, my browserslist file is under [src/browserslist](https://github.com/istiti/update-not-move-browserslist/blob/master/src/browserslist), after update it creates new one at root of project but not delete existant

One line repro : 
`repro : npm i && cd update-not-move-browserslist && ng update @angular/cli --from 7.3.6 --to 8 --migrate-only`


Details: 
1. `npm install`
2. `cd update-not-move-browserslist`
3. `ng update @angular/cli --from 7.3.6 --to 8 --migrate-only`
