### ISSUE TITLE
Nested sass imports are no longer working

### ISSUE THREAD

**Issue by rrajewski** [angular/angular-cli#14667]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes, this worked in version 7.3.9 or in version 8 if you have node-sass installed as a dev dependency.

### Description
Overriding sass variables in a nested import no longer works. Instead the last import wins. It works if you copy the contents of the file out and paste in place of the nested import.

## 🔬 Minimal Reproduction
example:
This does not work
```
.light-theme {
  @import 'assets/styles/light';
  @import '~highcharts/css/highcharts';
}

.dark-theme {
  @import 'assets/styles/dark';
  @import '~highcharts/css/highcharts';
}
```

This works
```
.light-theme {
  $neutral-color-3: blue; // contents of @import 'assets/styles/light';
  @import '~highcharts/css/highcharts';
}

.dark-theme {
  $neutral-color-3: black;  // contents of @import 'assets/styles/dark';
  @import '~highcharts/css/highcharts';
}

```
example repo: https://github.com/rrajewski/angularcli-sass-nested-import

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.1
Node: 10.13.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi, I am sorry but I am unable to replicate the issue that you are reporting. I download the reproduction and it seem that it is working fine. If I take a look at `styles.css` I can find the following;


```css
.light-theme .highcharts-null-point {
  fill: blue;
}
...
.dark-theme .highcharts-null-point {
  fill: black;
}
```

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
