### ISSUE TITLE
Hybrid app build fails after upgrade to angular 8

### ISSUE THREAD

**Issue by iyhammad** [angular/angular-cli#14672]
# 🐞 bug report
### Is this a regression?
Yes, the application was working fine till 7.1.x

### Description
I've relatively big hybrid app where angularjs is on a separate route. the app build broken after upgrade to angular 8

## 🔬 Minimal Reproduction
ng build --aot=true

## 🔥 Exception or Error
The below error happens for every html file in the angularjs part of the app.
<pre><code>
ERROR in ./src/ng1/app/main/views/employee/endOfService/endOfService.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <check-permission permission="HRPayroll.EmployeeAppService.EndOfService" show-message="true">
|     <div ng-controller="app.views.employee.endOfService as vm">
|         <form name="endOfServiceForm">
ERROR in ./src/ng1/app/main/views/employee/contract/list/list.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <check-permission permission="HRPayroll.EmployeeContractAppService.GetEmployeeContractsList" show-message="true">
| </check-permission>
| <div ng-controller="app.views.employee.contract as vm">
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.1
Node: 12.3.1
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by alan-agius4** [comment]
Closing as the issue seems to have been solved.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
