### ISSUE TITLE
@angular_devkit/core New workspace API usage in schematics

### ISSUE THREAD

**Issue by Wykks** [angular/angular-cli#14675]
The new workspace api from @angular_devkit/core take a `virtualFs.Host` as a parameters; eg:
`const host = workspaces.createWorkspaceHost(new NodeJsSyncHost());`

But how do you actually use it in a schematics `Rule` ? In a `Rule`, we only have a `Tree`. 

This is confusing, this post say that it's usable in schematics: https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27
"Previously developers using Schematics had to manually open and modify their angular.json to make changes to the workspace configuration. With 8.0, we’re introducing a new API to make it easier to read and modify this file."

**Comment by Wykks** [comment]
Okay got it
https://github.com/angular/angular-cli/blob/c319cd054e4344737e274af41f46ef4d8a1c3aab/packages/schematics/angular/utility/workspace.ts#L11

This function should be exposed

**Comment by clydin** [comment]
It's currently a private API.  A comprehensive schematics utility and rule library is currently in the design phase to provide functionality such as this and more.

While you could deep import the functions, they may change or be removed.  It would be safer to temporarily vendor the code within your schematics project for now.
