### ISSUE TITLE
Add an option to Disable es5 support in Build

### ISSUE THREAD

**Issue by dota2Pro** [angular/angular-cli#14679]
# 🚀 Feature request

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
```

### Description
 with the release of Version 8, Both es5 and es2015 files are generated on ng build. e.g.
`main-es5.js` , `main-es2015.js`. Build time also increased due to running two times.

### Describe the solution you'd like
 Add a build parameter that disables generation of *-es5.js files. For a person using only Chrome ( latest) *-es5.js files aren't required. This will speed up the build and reduce number of files.

### Describe alternatives you've considered
 I can manually everytime delete these tags from html `<script src="*-es5.js" type="module">`

[Stackoverflow post](https://stackoverflow.com/q/56464376/5724889)

**Comment by clydin** [comment]
The `browserslist` file is used to determine which bundle types are required to be built.  If only browsers that support ES2015+ are listed then only ES2015 bundles will be generated.  The intention is for the application's browser requirements to be specified in the file and then the CLI will generated the appropriate set of files.
Changing the file to only include `Chrome 70`, for instance, will result in only one set of bundles.

**Comment by dota2Pro** [comment]
> The `browserslist` file is used to determine which bundle types are required to be built. If only browsers that support ES2015+ are listed then only ES2015 bundles will be generated. The intention is for the application's browser requirements to be specified in the file and then the CLI will generate the appropriate set of files.
> Changing the file to only include `Chrome 70`, for instance, will result in only one set of bundles.

Excellent didn't knew that Thanks

**Comment by snqlby** [comment]
The default configuration with browserslist generates two bundles. When using Service Workers, this has a detrimental effect on the traffic consumed, since with any update both files are always downloaded. I think this should be fixed so that only one bundle is used in the default configuration until it is possible to completely abandon the two bundles in the standard configuration.

**Comment by saiKumarGanji** [comment]
Someone please paste the browser configuration , that would generate only es6 bundles.

**Comment by dota2Pro** [comment]
> Someone please paste the browser configuration , that would generate only es6 bundles.
> @clydin

`Chrome 74`

**Comment by clydin** [comment]
See my comment above.

However, please note that the purpose of the Browserslist file is to represent the required target browsers for the application.  The CLI will then use that list of browsers and generate the proper set and type of bundles as well as prefix and optimize the stylesheets for the application.  This will ensure that the application will work as intended on the browsers that the application is required to support.

**Comment by dota2Pro** [comment]
> Someone please paste the browser configuration , that would generate only es6 bundles.
> @clydin

Use `last 2 Chrome versions`

**Comment by istiti** [comment]
@saiKumarGanji 
If you really want support es2015 only, check  https://github.com/angular/angular-cli/issues/14639#issuecomment-500458409
