### ISSUE TITLE
ENOENT: no such file or directory, stat '/Users/manindersingh/Desktop/webd/src/tsconfig.app.json'

### ISSUE THREAD

**Issue by MANI14011998** [angular/angular-cli#14671]
ENOENT: no such file or directory, stat '/Users/manindersingh/Desktop/webd/src/tsconfig.app.json'
[ng] Error: ENOENT: no such file or directory, stat '/Users/manindersingh/Desktop/webd/src/tsconfig.app.json'
[ng]     at Object.fs.statSync (fs.js:948:11)
[ng]     at AngularCompilerPlugin._setupOptions (/Users/manindersingh/Desktop/webd/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:85:16)
[ng]     at new AngularCompilerPlugin (/Users/manindersingh/Desktop/webd/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:53:14)
[ng]     at _createAotPlugin (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js:37:12)
[ng]     at Object.getNonAotConfig (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js:43:19)
[ng]     at BrowserBuilder.buildWebpackConfig (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/src/browser/index.js:89:37)
[ng]     at DevServerBuilder.buildWebpackConfig (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:108:46)
[ng]     at MergeMapSubscriber.rxjs_1.from.pipe.operators_1.concatMap [as project] (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:36:40)
[ng]     at MergeMapSubscriber._tryNext (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
[ng]     at MergeMapSubscriber._next (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
[ng]     at MergeMapSubscriber.Subscriber.next (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
[ng]     at TapSubscriber._next (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:65:26)
[ng]     at TapSubscriber.Subscriber.next (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
[ng]     at MergeMapSubscriber.notifyNext (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
[ng]     at InnerSubscriber._next (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
[ng]     at InnerSubscriber.Subscriber.next (/Users/manindersingh/Desktop/webd/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)

[ERROR] ng has unexpectedly closed (exit code 1).

**Comment by alan-agius4** [comment]
Kindly follow the issue template.
