### ISSUE TITLE
[ng lint] outputs "All files pass linting" even though linting failed

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/angular-cli#14686]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not sure

### Description

The `ng lint` command outputs "All files pass linting" even though linting failed.

## 🔬 Minimal Reproduction
1. Mimic a lint failure by adding a rule like `"no-var-keyword": true`
2. In your code, add a variable `var thisIsMyVar = '';`
3. Run cli command `ng lint`

## 🔥 Exception or Error
<pre><code>

Linting "my-project"...

ERROR: C:/git/my-project/src/app/layout/topbar/topbar.component.ts[50, 5]: Forbidden 'var' keyword, use 'let' or 'const' instead
ERROR: C:/git/my-project/src/app/layout/topbar/topbar.component.ts[50, 9]: Identifier 'shouldNotAllow' is never reassigned; use 'const' instead of 'var'.

Lint errors found in the listed files.
Linting "my-project-e2e"...

All files pass linting.

</code></pre>

![image](https://user-images.githubusercontent.com/9777763/59027082-f1152700-884f-11e9-8337-b4e03452e36b.png)

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.6                                              
Node: 8.11.4                                                    
OS: win32 x64                                                   
Angular: 7.2.11                                                 
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router                                                      
                                                                
Package                           Version                       
-----------------------------------------------------------     
@angular-devkit/architect         0.13.6                        
@angular-devkit/build-angular     0.13.6                        
@angular-devkit/build-optimizer   0.13.6                        
@angular-devkit/build-webpack     0.13.6                        
@angular-devkit/core              7.3.6                         
@angular-devkit/schematics        7.3.6                         
@angular/cli                      7.3.6                         
@ngtools/webpack                  7.3.6                         
@schematics/angular               7.3.6                         
@schematics/update                0.13.6                        
rxjs                              6.3.3                         
typescript                        3.2.4                         
webpack                           4.29.0                        
</code></pre>

**Anything else relevant?**
N/A

**Comment by alan-agius4** [comment]
Hi, this is expected because that message is referring to the E2E project, when running `ng lint` you are running lint on multiple projects.

See below.

```js
Linting "my-project"...

ERROR: C:/topbar.component.ts[50, 5]: Forbidden 'var' keyword, use 'let' or 'const' instead
ERROR: C://topbar.component.ts[50, 9]: Identifier 'shouldNotAllow' is never reassigned; use 'const' instead of 'var'.

Lint errors found in the listed files. // The message here is for: Linting "my-project" 

Linting "my-project-e2e"...

All files pass linting.  // The message here is for: Linting "my-project-e2e"
```

**Comment by cmacdonnacha** [comment]
Oh, but I only have 1 project?

**Comment by alan-agius4** [comment]
Yes indeed, however in version 8. The E2E are now part of the same project.

**Comment by cmacdonnacha** [comment]
Ah ok great, do you know if the e2e project is merged automatically during the `ng upgrade` or is it only for new projects?
