### ISSUE TITLE
Enable all strict type checking options.

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#14694]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

set compilerOptions `strict:true` in `tsconfig.json`

**Comment by xiaoxiangmoe** [comment]
Are there plans to enable all strict type checking options? @alan-agius4

**Comment by alan-agius4** [comment]
We'll discuss and see if I'd want to enable this for default projects. We'll post the outcome of the discussion here.

**Comment by alan-agius4** [comment]
@xiaoxiangmoe, thanks for opening this. We'll very much like to do this, but at the same time we want to ensure that the generated code by the schematics works with this new option.

**Comment by xiaoxiangmoe** [comment]
@alan-agius4 What do I need to do to help you?

**Comment by alan-agius4** [comment]
Well, you can take this task and implement it :) It's free for grab.

**Comment by dkosasih** [comment]
Anyone mind if I take this one?

**Comment by xiaoxiangmoe** [comment]
@dkosasih https://github.com/angular/angular-cli/pull/14905

**Comment by cyrilletuzi** [comment]
@alan-agius4 I'm very happy this is finally happening. I proposed that a long time ago and did several PRs, but they were never accepted.

Unfortunately, except I'm missing something, the PR is incomplete as the option has not been added in the `ng new` schematics, so `ng new --strict` is failing.

**Comment by cyrilletuzi** [comment]
It's also missing the `strictFunctionTypes` flag.
