### ISSUE TITLE
Migration from Angular 6 to Angular 8 - DOCUMENT import from @angular/platform-browser

### ISSUE THREAD

**Issue by camila-borges** [angular/angular-cli#14695]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by kEpEx** [comment]
I have the same issue. Any clue of how to resolve it?

**Comment by codephobia** [comment]
Ran into this issue as well when upgrading to Angular 8, but also had it importing from @angular/common, so perhaps it has been moved at some point? Switching the imports removed the errors for me.

**Comment by mihavendevelopment** [comment]
@alan-agius4 Why did you close the issue without offering a solution?

**Comment by vinay-akkipet** [comment]
@mihavendevelopment https://github.com/angular/angular/issues/30904

**Comment by kEpEx** [comment]
In my case the issue was caused by importing my Custom Http Client and the http client again in my lazy loaded module. The real issue is imposible to know what is causing the issue until you start removing dependencies from your module, not even --verbose option gives any meaningful clue to the real error
