### ISSUE TITLE
Keeping version numbers in sync in angular library project package.json files

### ISSUE THREAD

**Issue by parky128** [angular/angular-cli#14699]
When building an Angular Library application, is there an automated way to keep the root level package.json and the library application's package.json (e.g. under `projects/my-library`) file versions in sync when using `npm version` commands?

When I use the command, its only incrementing the root level package.json, is there a special command, or any other way to propagate the version number down to the library package.json file?

I have seen some solutions such as running a script after `ng build` to read the root level package.json version number and write that into the library one. Is this a good approach or are there better ways supported with the cli?

Thanks

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
