### ISSUE TITLE
Bug: incorrect load children for lazy module when use typings

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#14690]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

When I use typing and add module as argument

app-routing.module.ts

```ts
 loadChildren: (): Promise<any> =>
       import('./view/auth/auth.module').then((module: any) => module.AuthModule)
```

Build failed

```
WARNING in 
Found 'loadChildren' with a non-string syntax in src/app/app-routing.module.ts but could not transform it.
Make sure it matches the format below:

loadChildren: () => import('IMPORT_STRING').then(M => M.EXPORT_NAME)

Please note that only IMPORT_STRING, M, and EXPORT_NAME can be replaced in this format.

Visit https://v8.angular.io/guide/ivy for more information on using Ivy.

```

but if we change

```ts
 loadChildren: () => import('./view/auth/auth.module').then((m) => m.AuthModule)
```

it's work, but why? This behavior is not obvious enough, I want to specify types forcibly everywhere, but as a result, the parsing does not work correctly! Problem reproduced with only AOT.

## 🌍 Your Environment
<pre><code>
Angular 8.0.1
</code></pre>

**Comment by filipesilva** [comment]
This breaks because we have to rewrite that import to work with AOT. There isn't code in the rewrite logic to account for all the forced typings yet.

**Comment by clydin** [comment]
Also of note is that using “any” disables type checking.  From an error reporting and code quality perspective it’s actually better to let TypeScript infer the types.

**Comment by prnysarker** [comment]
Looks like similar issue I am facing, for 
 For
` loadChildren:()=>import('./camera/camera.module').then(mod=> mod.CameraModule)` 
Works perfectly fine, but if I change any lamda to regular function it dosn't generates any chunk file.

So the bellow code doesn't  work.
```
 loadChildren: function () {
            return import('./camera/camera.module').then(function (module) {
                return module.CameraModule;
            });
        }
```
The error is 

> ERROR Error: Uncaught (in promise): Error: Runtime compiler is not loaded
> Error: Runtime compiler is not loaded
Environment 8.2.2

My concerns ?

1. Is it a bug ?
2. is loadChildren really expecting a function or it is just a spatial token that angular compiler know and parses accordingly ?
3. Is there any change if the behavior will change ?

Thanks for your time.

**Comment by smile2014** [comment]
ERROR Error: Uncaught (in promise): Error: Runtime compiler is not loaded
Error: Runtime compiler is not loaded
    at $v.Mv (main-es2015.f8cb835aabed0f0f97ac.js:1)
    at c.string.he.pipe.e [as project] (main-es2015.f8cb835aabed0f0f97ac.js:1)
    at c._tryNext (main-es2015.f8cb835aabed0f0f97ac.js:1)
    at c._next (main-es2015.f8cb835aabed0f0f97ac.js:1)
    at c.next (main-es2015.f8cb835aabed0f0f97ac.js:1)
    at e.then.e (main-es2015.f8cb835aabed0f0f97ac.js:1)
    at l.invoke (polyfills-es2015.79cfc60b46d0d7fc4d59.js:1)



{ path: 'monitor', loadChildren: () => {
      if (environment.fn) {
        return import('./pages/export-pdf/export-pdf.module').then(m => m.ExportPdfModule);
      } else {
        return import('./pages/monitor/monitor.module').then(m => m.MonitorModule);
      }
    }
 },

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
