### ISSUE TITLE
ng build throws downlevelIteration error targeting es2015

### ISSUE THREAD

**Issue by lppedd** [angular/angular-cli#14697]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 7.3.*

### Description

Building with `ng build` while targeting `es2015` throws `downlevelIteration` error.

## 🔬 Minimal Reproduction

Create a new Angular application and use this code for `app.component.ts`

```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  map = new Map<string, string>();

  ngOnInit(): void {
    this.map.set('key', 'value');

    for (const [k, v] of this.map) {
      console.log(k, v);
    }
  }
}
```

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.component.ts(15,26): error TS2569: Type 'Map<string, string>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.1
Node: 10.11.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

`tsconfig.json`

<pre><code>
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
</code></pre>

**Comment by lppedd** [comment]
@alan-agius4 judging by your commit I suppose I could just add it to the `tsconfig.json` file, and it would be "equivalent". Am I right?
Btw, thanks for the quick response.

**Comment by alan-agius4** [comment]
Yeah you are right 😊
