### ISSUE TITLE
Router : cant use "name", "redirectTo" in @RouteConfig

### ISSUE THREAD

**Issue by minhnguyenwp** [angular/angular-cli#1470]
> ## Please provide us with the following information:
1. OS:  Mac OSX (El Capitan)
2. Versions. Angular Cli : v1.0.0-beta.10 
   ## **Angular 2 RC 4 (A2)**
- I generated some routes: "Home", "Users", "NotFound"
- in AppComponent : 

```
@RouteConfig([
  { path: '/', component: Home, name: 'Home', useAsDefault: true },
  { path: '/users/:userLogin/...', component: Users, name: 'Users' },
  { path: '/**', redirectTo: ['NotFound'] }
])
```
- A2 System doesn't allow me to use "name: 'Home', useAsDefault: true" , redirectTo: ['NotFound'] 
  . Always error.
- Just allow 2 values : **path**: "/..." and **component**: "SomeComp"

**\- How can i use them ?** 
For 404 page, when user type: domain.com/fsdhsdgjhsjhgsd and ENTER
For redirect to some page i need.
Or setting a default route.

![2016-07-28_145006](https://cloud.githubusercontent.com/assets/14305088/17204962/aff1ebfe-54d2-11e6-9d4b-852f8560ac02.jpg)

**Comment by filipesilva** [comment]
This repo is for issues related to the CLI itself, whereas yours is an angular issue. A better place for your question is https://github.com/angular/angular.

**Comment by minhnguyenwp** [comment]
No, i knew how to config a Route. 
But in A CLI, it does not work like the original A2. My buddy. 
So i need to help.

**Comment by filipesilva** [comment]
The CLI is using the latest router, I don't see how it could be different.... What version of the router are you using?

**Comment by minhnguyenwp** [comment]
Hi men.

I'm create project follow angular cli guide **npm install -g angular-cli**, then config in file package.json, router version **"@angular/router": "2.0.0-rc.1"**

In the original A2, router config has name **@RouterConfig**, but angular cli had change name **@Routes**, i know that.

But  in **@Routes**, just config 2 param is **path** & **component**. 

When i add param **useAsDefault: true** or **redirectTo: ['NotFound']**,  system alert error like under picture.

![2016-07-29_101122](https://cloud.githubusercontent.com/assets/14305088/17236682/debd72e4-5574-11e6-8b81-444510cd6bb9.jpg)

![aff1ebfe-54d2-11e6-9d4b-852f8560ac02](https://cloud.githubusercontent.com/assets/14305088/17236574/3fcfdf64-5574-11e6-9b75-5716801835d4.jpg)

I don't add any param into **@Routes**, like under picture
![2016-07-29_102112](https://cloud.githubusercontent.com/assets/14305088/17236824/431fbfac-5576-11e6-8fd2-7d4f48b49049.jpg)

**Comment by filipesilva** [comment]
I think that is the issue. The router now being used is `3.0.0-beta.2` and a lot of the options changed. I think you'll need to update the router to that version. 

The official docs is now updated to that version as well https://angular.io/docs/ts/latest/guide/router.html

**Comment by minhnguyenwp** [comment]
Hi men.

I installed new package, but file package.json still old version. See under
![2016-07-29_111930](https://cloud.githubusercontent.com/assets/14305088/17237645/5c412ab8-557e-11e6-9248-b7b83a6165ea.jpg)

Thanks you for reply.

I looking forward final release for angular cli. Great jobs.

**Comment by rexebin** [comment]
@minhnguyenwp I guess you updated your Angular-cli from an earlier version to beta.10. However you did not update your project generated by the previous version of Angular-cli and therefore your package.json was not changed. 

Please follow [Updating angular-cli](https://github.com/angular/angular-cli#updating-angular-cli) and try run `ng init` to update auto generated files in your project.

If your existing project is only experimental, it may be easier to `ng new` a new project.

The router has been revamped and APIs like `name` is no longer there. Please read [Routing and Navigation](https://angular.io/docs/ts/latest/guide/router.html).

**Comment by hansl** [comment]
Closing this as obsolete.
