### ISSUE TITLE
ng update @angular/cli 8.0.1 => 8.0.2 does not install the 8.0.2 package

### ISSUE THREAD

**Issue by markgoho** [angular/angular-cli#14703]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not sure.

### Description

When running ng update on 8.0.1 everything seems to run, but the 8.0.2 package does not get installed.

## 🔬 Minimal Reproduction
Run `ng update @angular/cli`

Output:
``` bash
Using package manager: 'npm'
Collecting installed dependencies...
Found 42 dependencies.
    ** Executing migrations for package '@angular/cli' **
            Found a modern configuration file. Nothing to be done.
UPDATE package.json (2426 bytes)
UPDATE apps/storefront/src/polyfills.ts (2836 bytes)
UPDATE tslint.json (2103 bytes)
UPDATE tsconfig.json (746 bytes)
UPDATE apps/storefront/tsconfig.app.json (226 bytes)
UPDATE apps/storefront/tsconfig.spec.json (207 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 879557 packages in 7.189s
found 0 vulnerabilities
```
`package-lock.json` after installation:
``` json
"@angular/cli": {
      "version": "8.0.1",
      "resolved": "https://registry.npmjs.org/@angular/cli/-/cli-8.0.1.tgz",
      "integrity": "sha512-V8U4jNE9khQd7ykzewTpGcB7AjRhWIGb3opPfYux5umQsVhlhQqj/jVgGMu+kN9Jl7KkjFzQTjsJws7wODP6MA==",
      "dev": true,
      "requires": {
        "@angular-devkit/architect": "0.800.1",
        "@angular-devkit/core": "8.0.1",
        "@angular-devkit/schematics": "8.0.1",
        "@schematics/angular": "8.0.1",
        "@schematics/update": "0.800.1",
        "@yarnpkg/lockfile": "1.1.0",
        "debug": "^4.1.1",
        "ini": "1.3.5",
        "inquirer": "6.3.1",
        "npm-package-arg": "6.1.0",
        "open": "6.2.0",
        "pacote": "9.5.0",
        "read-package-tree": "5.2.2",
        "semver": "6.0.0",
        "symbol-observable": "1.2.0",
        "universal-analytics": "^0.4.20",
        "uuid": "^3.3.2"
      },
      "dependencies": {
        "@angular-devkit/architect": {
          "version": "0.800.1",
          "resolved": "https://registry.npmjs.org/@angular-devkit/architect/-/architect-0.800.1.tgz",
          "integrity": "sha512-zDueOtGo8q9zAUWL2baLIwc5hlLkNtSr5ud1yTuhS4EmYbXJOvV2BPyXx4d77iL+SK4AMG/FyDsi1ZUxXubHIA==",
          "dev": true,
          "requires": {
            "@angular-devkit/core": "8.0.1",
            "rxjs": "6.4.0"
          }
        },
        "debug": {
          "version": "4.1.1",
          "resolved": "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz",
          "integrity": "sha512-pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==",
          "dev": true,
          "requires": {
            "ms": "^2.1.1"
          }
        },
        "ms": {
          "version": "2.1.1",
          "resolved": "https://registry.npmjs.org/ms/-/ms-2.1.1.tgz",
          "integrity": "sha512-tgp+dl5cGk28utYktBsrFqA7HKgrhgPsg6Z/EfhWI4gl1Hwq8B/GmY/0oXZ6nF8hDVesS/FpnYaD/kOWhYQvyg==",
          "dev": true
        },
        "rxjs": {
          "version": "6.4.0",
          "resolved": "https://registry.npmjs.org/rxjs/-/rxjs-6.4.0.tgz",
          "integrity": "sha512-Z9Yfa11F6B9Sg/BK9MnqnQ+aQYicPLtilXBp2yUtDt2JRCE0h26d33EnfO3ZxoNxG0T92OUucP3Ct7cpfkdFfw==",
          "dev": true,
          "requires": {
            "tslib": "^1.9.0"
          }
        },
        "semver": {
          "version": "6.0.0",
          "resolved": "https://registry.npmjs.org/semver/-/semver-6.0.0.tgz",
          "integrity": "sha512-0UewU+9rFapKFnlbirLi3byoOuhrSsli/z/ihNnvM24vgF+8sNBiI1LZPBSH9wJKUwaUbw+s3hToDLCXkrghrQ==",
          "dev": true
        }
      }
    },
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.1
Node: 10.16.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@angular/pwa                      0.800.2
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Workaround:** use standard installation method for upgrading package (`npm install` or `yarn add`)

**Comment by alan-agius4** [comment]
AFAIK `ng update` shouldn't be used for patch updates.

//cc @clydin

**Comment by clydin** [comment]
Do you happen to have a `.angular-cli.json` or `angular-cli.json` file up the path hierarchy of the project?

**Comment by markgoho** [comment]
No, only the angular.json file in the root. 

I've found the `ng update` syntax to be so friendly that I generally use it as my default way of upgrading dependencies, e.g. `ng update firebase` or `ng update cypress`

**Comment by clydin** [comment]
Sorry.  I meant in any directory above the workspace root.
This line in the log `Found a modern configuration file. Nothing to be done.` appears to indicate that the CLI 1.x special handling mode was triggered which is caused by either of those two files being present.  I have a pending PR to improve that logic but I wanted to confirm first if that was indeed the root cause.

**Comment by brianmcd** [comment]
Wow, I've chased issues with `ng update @angular/cli` for what feels like forever, but haven't been able to find an answer.  I would always see `Found a modern configuration file. Nothing to be done.`, and then update migrations weren't run.  Turns out, I had a `.angular-cli.json` in my home directory.  Deleting that fixed all of my update issues.  Thanks @clydin!
