### ISSUE TITLE
Cannot localize strings in ts file and json file. 

### ISSUE THREAD

**Issue by atmakup1** [angular/angular-cli#14706]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 

No
### Description

 A clear and concise description of the problem...
I have an angular 5 application, which I am able to localize using the angular documentation. But I have few strings that are added in the ts file i.e adding months,days, year to the age after computing the age. I am not finding a way to localize it. Also I get some data from a local json file with id and name property. I need to localize the value in the name property. 

## 🔬 Minimal Reproduction

By running i18n strings in ts file and json file can't be reproduced. There is no way to specify them to localize. 
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
 Angular cli - 1.6.3

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
