### ISSUE TITLE
Issue when I run ng lint in a project which is minimal

### ISSUE THREAD

**Issue by ysmoradi** [angular/angular-cli#14727]
Step 1- Create a project using following command:
```
ng new test-app --enable-ivy=true --minimal=true --prefix=test --routing=true --skipInstall=true --skipTests=true --style=scss
```
Step 2- Run following command
```
ng lint
```

**First issue:** You'll receive the following error:

```
error TS5058: The specified path does not exist: 'test-app\tsconfig.spec.json'.
```

There's no tsconfig.spec.json because --minimal parameter of the first command.
In angular.json, there's a lint section which accepts two tsconfig files instead of one!

**The second issue:**

There is no tslint.json at all!

If you provide it (by copying it from another angular project), you'll see **3rd issue**:

```Could not find custom rule directory: codelyzer```

You've to install it using

```
npm i codelyzer --save-dev
```

You can enjoy using ng lint with a minimally created project.

But it seems that @angular/cli needs some changes related to these issues.

Thanks in advance.

**Comment by alan-agius4** [comment]
Hi,  thanks for opening this. However this is expected as minimal are considered as throw-away projects and only a small subset of features are supported.

That being said, we should not generate the `lint` config for minimal projects.

More context https://github.com/angular/angular-cli/pull/13408 and https://github.com/angular/angular-cli/pull/13354
