### ISSUE TITLE
ng serve doesn't serve valid MIME types

### ISSUE THREAD

**Issue by apollolux** [angular/angular-cli#14724]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I've not tried before v7.

### Description

Local sites served by `ng serve` do not add the correct MIME types to the headers of files it serves, nor does it look like Content-Type is sent at all from dev-server. For my use, most commonly served images and webfonts are listed as `text/plain` in Chrome's dev tools Network tab instead of their correct types. Among other side effects is that when previewing the content in dev tools they're just shown as plain text gibberish of their actual binary contents.

Interestingly enough, the resources seem to embed ok in the various pages of the site, e.g. images display as images and webfonts are used as webfonts instead of broken images or unloaded fonts. Don't know why the disparity between the two interfaces of the same browser.

## 🔬 Minimal Reproduction

Create an Angular app, put an image that gets embedded and a webfont (woff or woff2 format should be fine here) to be used in an assets folder and reference them in a page or component. Then `ng serve` the app and view the results in the browser's dev tools.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.8
Node: 8.11.2
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.8
@angular-devkit/core         7.3.8
@angular-devkit/schematics   7.3.8
@schematics/angular          7.3.8
@schematics/update           0.13.8
rxjs                         6.3.3
typescript                   3.2.4
</code></pre>

**Anything else relevant?**

Currently using Chrome 73, but almost certainly in other browsers.

Windows 7, currently using VSCode 1.34 for development and calling package.json commands

I looked a little bit into what config `ng serve` passes to webpack and noticed nothing related to proper MIME types. My suggestion is ultimately we should be allowed to add a valid config or path to valid config for MIME types in angular.json that gets passed to webpack to use, or maybe even a webpack.config.js in project root that supplements and/or overrides angular.json's webpack config.

**Comment by alan-agius4** [comment]
Hi @appllolux, I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

Font
![image](https://user-images.githubusercontent.com/17563226/59249885-25109380-8c26-11e9-93eb-b0ae94e8c95d.png)

image
![image](https://user-images.githubusercontent.com/17563226/59249911-2fcb2880-8c26-11e9-91b3-861505a5ffd1.png)

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
