### ISSUE TITLE
SSR not working with ng - Webpack minification issue

### ISSUE THREAD

**Issue by tacrawford91** [angular/angular-cli#14739]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [X ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Reopen of Issue #10635
[https://github.com/angular/angular-cli/issues/10635](url)

The webpack minifaction step is causing an issue when building for production with SSR. The only workaround now is to set the `mode` in the `webpack.server.config.js` to `none` or set the `minimize` of the optimization option to` false`. 

## 🔬 Minimal Reproduction
See Issue #10635
[https://github.com/angular/angular-cli/issues/10635](url)

## 🔥 Exception or Error
500 error
## 🌍 Your Environment
<pre><code>

Angular CLI: 6.0.0
Node: 8.11.0
OS: darwin x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
</code></pre>

**Anything else relevant?**
webpack.server.config.js optimization minimize set to `false`
[https://gist.github.com/johnzondr/3d4a361ffcfe89f7ee5199dcc13bf246](url)

webpack.server.config.js mode set to `none`
[https://github.com/snipcart/angular-seo-universal/blob/master/webpack.server.config.js](url)

**Comment by alan-agius4** [comment]
Hi, thanks for opening the issue, however the above mentioned issue was closed as duplicate and not as resolved. 

The original issue is still open #8616.
