### ISSUE TITLE
High CPU usage with cli 8.0

### ISSUE THREAD

**Issue by fetis** [angular/angular-cli#14748]
I've just upgraded to new Angular8 and noticed that CPU usage dramatically increased for `node` process. It wasn't the issue in v7

My environment
```
Angular CLI: 8.0.2
Node: 12.4.0
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cdk                      7.3.7
@angular/cli                      8.0.2
@angular/material                 7.3.7
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

the only process node prcess here is `ng serve` in idle mode, so it's compiling nothing at the moment.
<img width="425" alt="Screen Shot 2019-06-12 at 15 12 13" src="https://user-images.githubusercontent.com/577042/59354028-8b7bdb80-8d24-11e9-9e86-1e1c1f8ac211.png">

the same also true for `ng test`

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by fetis** [comment]
So, I dropped `node_modules` and made a fresh install. It fixed the problem, CPU is quiet and low now :) I belive we can close the issue now.

Note: We use `node-sass` instead of `dart-sass` for compatiblity reasons.
