### ISSUE TITLE
Angular CLI writes wrong information when I want to generate component for a library

### ISSUE THREAD

**Issue by m98** [angular/angular-cli#14744]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I have a monorepo, means I have two applciation beside my main application. I created a library to put some shared codes there, and inside the library, when I try to generate a component for the library, it seems the Angular CLI is working correctly, but when I open it up, I see there are some bash style codes there.

**Here is what I will get inside my component:**
**alert.component.ts**
```
{
  "_args": [
    [
      "cpy-cli@1.0.1",
      "E:\\projects\\main\\web"
    ]
  ],
  "_development": true,
  "_from": "cpy-cli@1.0.1",
  "_id": "cpy-cli@1.0.1",
  "_inBundle": false,
  "_integrity": "sha1-Z/taSi3sKMqKv/N13kuecfanVhw=",
  "_location": "/cpy-
```
**alert.component.html**
```
{
  "_args": [
    [
   

```

## 🔬 Minimal Reproduction
1- Generate an application (main application)
2- Generate two projects beside your main app (monorepo)
3- Generate a library
4- Try to create a component for the library by going into its diractory, and run this command:
`ng g c alert --module=myLibrary.module.ts`

(I'm even not sure the problem happens after the update, or after I added multiple application and library)

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 9.11.1
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-ng-packagr   0.13.9
@angular-devkit/build-optimizer    0.13.9
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
@angular/cdk                       7.3.7
@angular/cli                       7.3.9
@angular/material                  7.3.7
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.9
@schematics/update                 0.13.9
ng-packagr                         4.7.1
rxjs                               6.5.2
typescript                         3.2.4
webpack                            4.29.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi, are you using the standard angular schematics or you have a third party generator?

I was unable to replicate this issue, Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
