### ISSUE TITLE
TerserPlugin - exclude specific module / files

### ISSUE THREAD

**Issue by lppedd** [angular/angular-cli#14750]
I haven't found a way to customize the `TerserPlugin` `exclude` option (and others).  
Do you have any suggestion?

Terser is removing important functions from an external pure JavaScript library ([bpmn-js](https://github.com/bpmn-io/bpmn-js)) and I absolutely need to exclude it, while maintaining the build optimization.

**Comment by clydin** [comment]
In the future, please follow the issue template.  It is quite difficult to provide assistance without the requested information.

The package is marked as being side effect free (https://github.com/bpmn-io/bpmn-js/blob/master/package.json#L38).  If code is being removed, the most likely cause is that the package is not actually side effect free.
This line appears to confirm the suspicion: https://github.com/bpmn-io/bpmn-js/blob/master/lib/Viewer.js#L154

**Comment by lppedd** [comment]
@clydin Sorry about the template. 
And yes, exactly that function is removed. Can I override this behavior?

**Comment by clydin** [comment]
This is actually an issue with the package.  It is advertising itself as being side effect free when it is not.   The CLI is acting appropriately given the information it is being provided by the package.

**Comment by lppedd** [comment]
@clydin yeah, I know, I've been reading issues regarding Terser/UglifyJs behavior.
But what if I cannot modify the external library?

**Comment by clydin** [comment]
If you need a temporary workaround, you can remove the side effects field from the installed package.  This would need to be done every time it is installed.  For completeness, a post install script for the project is a common method to augment errant packages.

If the library is being imported into the application then there is no separate file to exclude.  Only the final bundles are run through the minifier.

**Comment by lppedd** [comment]
@clydin 

> If the package is being imported into the application then there is no separate file to exclude. Only the final bundles are run through the minifier.

Thanks for confirming that. I tought I was doing something wrong while debugging the builder.

> a post install script for the project is a common method to augment errant packages.

I'll give this one a try, as I don't want to hand-edit the file every time.

Last question, if you can answer: the `inherit` function simply uses `Object.create(...)`, what would be a side-effect free alternative?

```
if (typeof Object.create === 'function') {
  // implementation from standard node.js 'util' module
  module.exports = function inherits(ctor, superCtor) {
    ctor.super_ = superCtor
    ctor.prototype = Object.create(superCtor.prototype, {
      constructor: {
        value: ctor,
        enumerable: false,
        writable: true,
        configurable: true
      }
    });
  };
} else {
  // old school shim for old browsers
  module.exports = function inherits(ctor, superCtor) {
    ctor.super_ = superCtor
    var TempCtor = function () {}
    TempCtor.prototype = superCtor.prototype
    ctor.prototype = new TempCtor()
    ctor.prototype.constructor = ctor
  }
}
```

**Comment by clydin** [comment]
It's not actually the content of the function but rather the location of the call.  Since the call is at the module level, importing the module will result in execution and cause some type of _effect_ by simply importing the module.
