### ISSUE TITLE
Do not accept environment variables in angular.json configuration

### ISSUE THREAD

**Issue by bhau2019** [angular/angular-cli#14766]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by bhau2019** [comment]
Hi ,
I am building an angular project through gradle scripts. It is multi project build, which uses five modules in current project and seven modules from platform project developed separately. When I checkout all modules in same folder , it build fine and works great. But when I checkout platform modules in different folder like platformComponentDir , it fails. I could not find any way to pass property through command 'ng build app --someProperty'.  I tried to pass property through environment.ts or some js file inclusion in main.ts. But no success. Json parser fails when it sees some variable. 
![AngularBuild](https://user-images.githubusercontent.com/51802659/59468841-bdf70880-8df8-11e9-95ca-15360f788eab.JPG)

**Comment by alan-agius4** [comment]
Hi, environment variables are not something which is supported. That said you can override known options via the command line.

For example for `ng build` you can override these options found here:
https://angular.io/cli/build

For version 9 we will be looking into way how to create workspace config compositions, so that we can slim down the config when having projects with various configurations.

**Comment by bhau2019** [comment]
It is not about environment variable only. I am trying to find a way to pass some property which can be used in angular.json for build purpose.

I am not sure how to override 'ng build' options. Is there any example on that?
