### ISSUE TITLE
ng add - throws error Cannot find module package.json

### ISSUE THREAD

**Issue by huv1k** [angular/angular-cli#14761]
# 🐞 Bug report

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I have no idea, I tested it with older versions and it shows the same error. CLI builder is a new feature and it wasn't at the old version of Angular.

### Description

Running `ng add` throws an error during installation, that `package.json` module wasn't found, even that it's inside that package. After installing everything works fine, but an error could confuse the user that it wasn't installed properly. 

## 🔬 Minimal Reproduction
To get minimal reproduction add deploy builder for example:
```sh
ng add @zeit/ng-deploy
```

## 🔥 Exception or Error
<pre><code>
Cannot find module '/Users/huvik/Projects/hello-world/node_modules/@zeit/ng-deploy/package.json'
Error: Cannot find module '/Users/huvik/Projects/hello-world/node_modules/@zeit/ng-deploy/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/huvik/Projects/hello-world/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:74:39)
    at NodeModulesEngineHost.createCollectionDescription (/Users/huvik/Projects/hello-world/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:115:27)
    at SchematicEngine._createCollectionDescription (/Users/huvik/Projects/hello-world/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/Users/huvik/Projects/hello-world/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at AddCommand.getCollection (/Users/huvik/Projects/hello-world/node_modules/@angular/cli/models/schematic-command.js:130:35)
    at AddCommand.runSchematic (/Users/huvik/Projects/hello-world/node_modules/@angular/cli/models/schematic-command.js:283:50)
    at AddCommand.executeSchematic (/Users/huvik/Projects/hello-world/node_modules/@angular/cli/commands/add-impl.js:142:31)
    at AddCommand.run (/Users/huvik/Projects/hello-world/node_modules/@angular/cli/commands/add-impl.js:106:21)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.2
Node: 11.13.0
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@ngtools/webpack                  8.0.2
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              <error>
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @huv1k Can you try using the latest version of the CLI? I am unable to replicate the above mention issue.

```
ng add @zeit/ng-deploy
Installing packages for tooling via npm.
npm WARN @zeit/fetch@5.1.0 requires a peer of @types/node-fetch@2 but none is installed. You must install peer dependencies yourself.

+ @zeit/ng-deploy@0.0.12
added 57 packages from 86 contributors and audited 19248 packages in 29.131s
found 0 vulnerabilities

```

**Comment by huv1k** [comment]
I have the same issue with the latest CLI. Is there something special what CLI relies on?

**Comment by alan-agius4** [comment]
@huv1k, not really, I even tried this on another machine and worked as expected.

Does this happen also on:
```
npx @angular/cli new foo --defaults
cd foo
ng add @zeit/ng-deploy
```

**Comment by huv1k** [comment]
The same thing 😢maybe I have a problem with paths or something. 😟

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by adestis-ds** [comment]
I had exactly the same problem (just with another package - the problem seems to be not package related). The problem occured on MAC and on Windows with the following versions:

Angular CLI: 8.1.0

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2


npm: 6.9.0
**node: 11.11**

The solution was to update to the ** latest node version 12.6 **. Now everything works like a charm. It is documented that angular 8 requires a node version 12.x.

**Comment by seranus** [comment]
I got the same problem when executing

`ng add @nguniversal/express-engine --clientProject`

my solution was to downgrade from
`"@angular-devkit/build-angular": "0.802.0",`
to
"@angular-devkit/build-angular": "0.800.0",
