### ISSUE TITLE
Build Optimizer is not wrapping some enums

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#14786]
The follow enum (present in [RxJS](https://github.com/ReactiveX/rxjs/blob/b24d3ea85d33b893e4c020fb4fa9f6fa4d05dc0b/src/internal/Notification.ts#L11-L15)):
```
export enum NotificationKind {
  NEXT = 'N',
  ERROR = 'E',
  COMPLETE = 'C',
}
```

Is transpiled by TS 3.5 to:
```
export var NotificationKind;
(function (NotificationKind) {
    NotificationKind["NEXT"] = "N";
    NotificationKind["ERROR"] = "E";
    NotificationKind["COMPLETE"] = "C";
})(NotificationKind || (NotificationKind = {}));
```

Running it through Build Optimizer leaves it unaltered, but it should be wrapped by https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_optimizer/src/transforms/wrap-enums.ts.

**Comment by alan-agius4** [comment]
@filipesilva, I don't think this is a regression but rather something which was never handled. We never handled string enums in `wrap-enums`.
