### ISSUE TITLE
problem when I want to install angular-cli

### ISSUE THREAD

**Issue by webdev-front** [angular/angular-cli#14795]
i have problem with angular/cli when i try to install ,some help pleas
![Captureissus](https://user-images.githubusercontent.com/51891022/59570101-dda55f80-908a-11e9-9d9f-0d4a54625706.PNG)

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
