### ISSUE TITLE
When serve Angular app using twig library throw error: Can't resolve path node_modules/twig

### ISSUE THREAD

**Issue by yduartep** [angular/angular-cli#14798]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 I don't know. It's the first time I try to integrate angular with twig template engine library.

### Description
I can't integrate twig php template library in my angular project. Every time throw the compilation error: `Can't resolve 'path' in '.../node_modules/twig'`

## 🔬 Minimal Reproduction
- I create a new angular project (version 8.0.1).
- Install the twig and @types/twig library.
- Create an empty component
- In the ngOnInit method include this code:
  `
  const template = twig({ data: 'The {{ baked_good }} is a lie.});
   console.log(template.render({baked_good: 'cupcake'}));
 `
- When I execute the command `ng serve`, I get the error:

ERROR in ./node_modules/twig/twig.js
Module not found: Error: Can't resolve 'path' in '/Users/yduartep/Documents/workspace/www2/node_modules/twig'

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/twig/twig.js
Module not found: Error: Can't resolve 'path' in '.../node_modules/twig'
</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by yduartep** [comment]
At the end, I could make it work adding the library path into the tsconfig.json like this:
`
"paths": {
      "twig": [
        "node_modules/twig/twig.min.js"
      ]
}
`
