### ISSUE TITLE
Deprecate styles and script `lazy` option in favor of a more self descriptive option 

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#14814]
# 🚀 Feature request

### Description
The `lazy` option inside the `script` and `style` option is confusing as this option doesn't lazy load a bundle but rather it doesn't inject/reference the script in the HTML. While this option is an enabler for lazy loading, the users will still need to handle on how how this bundle will be lazy loaded. There are also potential use cases beyond lazy loading for the option.

Deprecate the `lazy` option in favour of a more self descriptive options such as `injected`.

**Comment by alan-agius4** [comment]
@filipesilva any thoughts about the above? We discussed this in our meeting and myself, @mgechev and @clydin all think it's best to deprecate `lazy`.

We didn't yet decide the name of the new option though, May it can be `inject` or `injected`?

**Comment by filipesilva** [comment]
Deprecation+migration on 9 SGTM. I have no opinion on `inject` vs `injected`, I guess it's a consistency thing. 

Looking at `extractCss` and `extractLicenses` it sounds like it should be `inject`. But then we have `optimization` that makes me think `injected` would be better. So maybe we just need to decide what tense we want for options and stick to it.

**Comment by filipesilva** [comment]
Discussed and decided on `inject`.
