### ISSUE TITLE
Remove the config folder

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#1481]
Currently the `./config` folder only contains two files: `karma.conf.js` and `protractor.conf.js`.

Initially this folder contained way more files so it made sense to bundle them up there, but as there are only 2 now I think it makes more sense to take those two files out and get rid of the folder.

**Comment by tapas4java** [comment]
I would like to see this `config` folder to go away

**Comment by delasteve** [comment]
This no longer is a thing. `ng new X` puts these files in the root dir.

**Comment by hansl** [comment]
Closing this as obsolete.
