### ISSUE TITLE
ng s returns 30% building  0 activeKilled 

### ISSUE THREAD

**Issue by hamed6** [angular/angular-cli#14812]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

 A clear and concise description of the problem...
Running angular project in remote server and everytime that a new dependency is added to project optimization error is occured 
**93% after chunk asset optimization SourceMapDevToolPlugin vendor.js generate SourceMapKilled**
then activeKilled 
 **30% building 46/46 modules 0 activeKilled**
                                     
## 🔬 Minimal Reproduction
ng new "something" 
ng g "something"
ng s 
stop 
npm install --save @angular/material @angular/cdk @angular/animations
ng s 
Error: either SourceMapKilled or activeKilled

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
Angular CLI: 8.0.3
Node: 12.4.0
OS: linux x64
Angular: 8.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
<pre><code>

</code></pre>

**Anything else relevant?**
remote server : ubuntu 
1 core cpu 
1gb memory
25 storage

**Comment by hamed6** [comment]
by using --sourceMap=false , I got different error.
 **95% emitting index-html-webpack-pluginKilled**

**Comment by alan-agius4** [comment]
Most likely this is related to this issue: https://github.com/angular/angular-cli/issues/13734

Node 12 does consume more memory. That being said, I highly doubt that 1GB of memory is enough to build all those modules.

**Comment by alan-agius4** [comment]
Closing as per above.
