### ISSUE TITLE
Update to Angular 8 - web-animations-js

### ISSUE THREAD

**Issue by yodi-n** [angular/angular-cli#14826]
# 🐞 Bug report

After updating our projects form Angular 7 to Angular 8, our Jenkins was not able run npm install due to this line in the package.json file
"web-animations-js": "angular/web-animations-js#release_pr208"

The thing is that our Jenkins is behind a corporate proxy that does not allow calls to github.com

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, this did not happen with previous versions of Angular

### Description

When running npm ci, our Jenkins is not able to get the web-animation-js dependency on the angular github for of the original project.

## 🔬 Minimal Reproduction
- Create a project using @angular/cli 7
- Install web-animation-js package
- Add the dependency in the polyfill.ts file
- Update to Angular 8 using ng update @ancular/cli @angular/core

I don't understand why the Angular team did not uploaded this dependency under @angular/web-animation-js or something instead of just pointing to a PR of a for of the original project.

I realise this is not really a bug since it is a feature of NPM to be able to fetch dependencies directly on github, but it is the first time since I'm using Angular that this happens.

**Comment by alan-agius4** [comment]
@yodi-n the dependency uri is incorrect it should be `github:angular/web-animations-js#release_pr208` and not `angular/web-animations-js#release_pr208`

The main reason why it's not an NPM package is that this is a temporary solution which wouldn't ideally be published as a separate NPM package, and also @angular doesn't own `web-animations-js` package and it won't be correct to publish the `web-animations-js` under the angular namespace.

That being said we are still waiting on the `web-animations-js` team to cut an official release containing the fix. 

Some worksarounds would be;
1) Allow the corporate proxy to access github.com
2) Fork the above mentioned PR and host it locally


Lets continue tracking this in: https://github.com/angular/angular-cli/issues/14518

**Comment by clydin** [comment]
Also of note, is that the project may not actually need the polyfill anymore.  It is only needed by Angular if the project is using the AnimationBuilder class.  Declarative animations do not require the polyfill.
