### ISSUE TITLE
Webpack: Getting warning from one npm package when running ng serve 

### ISSUE THREAD

**Issue by 5amfung** [angular/angular-cli#1482]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
 
Mac El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

ng --version
(node:34059) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: local (v1.0.0-beta.10, branch: master)
node: 6.2.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I followed https://github.com/filipesilva/angular-cli/blob/061fc54cb67681c372cc66351c6f9221db9edf51/WEBPACK_UPDATE.md to migrate my project to use webpack.  When I run `ng serve`, everything seems to be ok until at the end.  I'm not sure if this is an issue of the npm package (@vaadin/angular2-polymer) I'm using or if this is something I need to set up in the webpack config to load npm package properly.  Please advise.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

I'm getting this at the end of `ng serve`:

```
WARNING in ./~/@vaadin/angular2-polymer/index.js
Cannot find source file 'index.ts': Error: Can't resolve './index.ts' in '/Users/bbpan/src/infocery-partner-ui/node_modules/@vaadin/angular2-polymer'
 @ ./src/app/app.component.ts 12:0-58
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

WARNING in ./~/@vaadin/angular2-polymer/src/polymer-element.js
Cannot find source file 'polymer-element.ts': Error: Can't resolve './polymer-element.ts' in '/Users/bbpan/src/infocery-partner-ui/node_modules/@vaadin/angular2-polymer/src'
 @ ./~/@vaadin/angular2-polymer/index.js 2:24-56
 @ ./src/app/app.component.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.47 kB       0       
webpack: bundle is now VALID.
```

5. Mention any other details that might be useful.

**Comment by TheLarkInn** [comment]
It looks like there is general issues for this with webpack. It may be worth reading this issue https://github.com/vaadin/angular2-polymer/issues/32

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/1673
