### ISSUE TITLE
ng serve - assets folder with large video files causing heap out of memory, unable to compile

### ISSUE THREAD

**Issue by appsteams** [angular/angular-cli#14821]
ng serve - assets folder with large video files causing heap out of memory, unable to compile

**Comment by alan-agius4** [comment]
The most probable root cause is that during `serve` files are stored in memory.

There are two options here as workaround:
1) Increase the memory limit of the process using `--max_old_space_size`
2) Avoid copying these large files during serve.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/9629
