### ISSUE TITLE
ng test with failing coverage should fail test

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#14832]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] test
```

### Description
Having failing test coverage in Karma does not fail `ng test`.

## 🔬 Minimal Reproduction
ng new my-app (works)
add a threshold to `karma.conf.js: (works)

```
thresholds: {
        emitWarning: false,
        global: { statements: 80 }
      }
```

Add the following untested statements to app.component.ts:
```
  untestedMethod() {
    console.log("this does one thing");
    console.log("this does one thing");
    console.log("this does one thing");
    console.log("this does one thing");
  }
```

ng test --code-coverage

## 🔥 Exception or Error
I expect it to fail, but the test command is succeeding, despite violating the threshold.

## 🌍 Your Environment
Angular CLI: 8.0.3
Node: 12.2.0
OS: linux x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by alan-agius4** [comment]
@StephenFluin let's take this over https://github.com/angular/angular-cli/issues/10940, I am still unable to replicate this as per my comment https://github.com/angular/angular-cli/issues/10940#issuecomment-503901408

Would be great if you can provide the full karma config
