### ISSUE TITLE
Webpack: Where are all the Webpack configs

### ISSUE THREAD

**Issue by joshuawilson** [angular/angular-cli#1483]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Fedora

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: local (v1.0.0-beta.10, branch: master)
node: 6.3.1
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I just ran ng new foo

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

I love what you are doing! I am trying to figure out if I should use angular-cli with webpack or if I should just follow the instructions at https://angular.io/docs/ts/latest/guide/webpack.html. The outcome of the cli is a LOT different then the docs. While I think the cli is great for getting started, I'm trying to decide if it is the right choice for a production system. My question comes more from a lack of understanding then anything else. I'm not saying one way is right over another. I watched the podcast of @Brocco and see a lot of cool things the cli sets up for you. Is all that built-in stuff available if I just setup webpack manually? For example, to add a library you just npm install it and put a require in the file that needs it. Also, the docs show how to set up a 'test' config but that doesn't appear to be available in the cli. 

Once again, I think you all are doing great work. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TheLarkInn** [comment]
So we have not cut a release of the webpack changes that are in master. So if you want to "pilot" these changes the steps are as followed: 

1. `git clone https://github.com/angular/angular.cli`
2. `npm install && npm link`
3. Go to wherever you want to create the new ng app and (`ng new foo --link-cli`).

**Comment by filipesilva** [comment]
Those steps seem right, yes. You'll overall be able to just add just npm install a lib and it works, but if it doesn't come with typings you also have to install them via `npm install @types/libname`.

Regarding configs we don't make the webpack configs available. The idea is that build is a black box, and it can be whatever the CLI chooses.

**Comment by joshuawilson** [comment]
@TheLarkInn I was able to run it just fine. It works for me. That is how I was able to see that there were no configs.

@filipesilva I was seeing the "black box" style and wondering if there would be hooks to change it

Also, I'm not clear on what is built into the black box that is more then what I can do with webpack manually. Does the cli add something extra to just making it easy to use Angular2 and Webpack?

Thanks,
Joshua

**Comment by filipesilva** [comment]
No hooks right now, but we've talked about it for the future. 

Whatever the CLI does you can do yourself overall. The selling point is that you don't have to because here is a project that's doing it for you, and that is being kept up to date with the latest Angular 2 style guide recommendations and feature set. 

Personally I think the generators bring the most value for my workflow, but I think that's because I really like build systems and would jump at the opportunity to make another. Other people have told me that the build system is what really matters for them because, conversely, they don't want to be doing another one from scratch.

We also hope that by making these things a non-option it takes down barriers to making new projects.

**Comment by TheLarkInn** [comment]
You are always welcome to see the configuration details in the src under ./addons/ng2/models/webpack-config.ts this will give you a starting point if you wanted to help contribute with additional features, etc.

**Comment by joshuawilson** [comment]
Thanks, I'll look into that.

And again, I think you all are doing great work!

**Comment by filipesilva** [comment]
Glad you're finding value in it!
