### ISSUE TITLE
Inject new styles instead of reloading

### ISSUE THREAD

**Issue by mensch** [angular/angular-cli#1485]
I'm running the new webpack version for a few days now and it's working splendidly. Webpack has been a great improvement regarding speed and the upgrade process was rather painless. Thank you for all the hard work so far!

I'm not sure if this is possible with LiveReload (this is still used, right?), but when developing for the web I use BrowserSync extensively and [the option](https://www.browsersync.io/docs/options#option-injectChanges) to inject styles when writing CSS or SASS instead of reloading the entire page/app is rather nice, as it doesn't reset the state of the page.

Would something be possible with the current webpack implementation?

**Comment by filipesilva** [comment]
We were looking at using HMR that I *think* also covers this scenario. See https://github.com/angular/angular-cli/issues/893

**Comment by mensch** [comment]
Ah yes, from what I understand HMR would indeed cover my request scenario. I vaguely remember tinkering with some React starter projects supporting hot reloading.
