### ISSUE TITLE
Angular library asset images are not accessible in consumer app production build.

### ISSUE THREAD

**Issue by vishal4799** [angular/angular-cli#14851]
I have an angular library named common-sec in which created assets folder manually under the lib folder. I used images from the assets folder in my library component. named "login".

I have used login component from common-sec library in my main angular app.

By running main app with ng serve, library images of assets folder loading perfectly. But when i build my main app using ng build --prod --base-href /prefix/, none of library images rendedred.

I see it tries to request images at localhost:4200/assets/image.png (return 404)
But i see images are available at ocalhost:4200/prefix/assets/image.png

Is it a bug or it's known issue in angular-cli?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
