### ISSUE TITLE
failed to run ng serve with Bazel's opt-in preview on windows

### ISSUE THREAD

**Issue by chgc** [angular/angular-cli#14867]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No, It's Bazel opt-in preview in Angualr CLI v8.x

### Description
Following the blog post [Try Bazel’s opt-in preview in Angular CLI](https://blog.angular.io/try-bazels-opt-in-preview-in-angular-cli-b9430bd00e82). No problems on `ng new` 、`ng build`, but failed on `ng serve` 

## 🔬 Minimal Reproduction
on windows machine with no Bazel install.
1. `npm install -g @angular/bazel`
2. `ng new ngBazel --collection=@angular/bazel`
3. `cd ngBzel`
4. `ng serve`

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/4550568/59976830-57de6280-95fc-11e9-8417-76b9db1a8d77.png)

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.0.3
Node: 10.15.0
OS: win32 x64
Angular: 8.0.2
... animations, bazel, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@bazel/bazel                      0.26.1
@bazel/ibazel                     0.10.3
@bazel/karma                      0.31.1
@bazel/typescript                 0.31.1
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by istiti** [comment]
Afaik you need install bazel globally first time : `npm i -g @bazel/bazel`  

See https://github.com/bazelbuild/bazel-watcher/issues/252

**Comment by chgc** [comment]
after `npm i -g @bazel/bazel` did fix original problem. but it leads another error

```
λ ng serve
Error getting Bazel info exit status 2
Querying for files to watch...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'query' from e:\practice\appbazel\.bazelrc:
  Inherited 'common' options: --experimental_allow_incremental_repository_updates
ERROR: Unrecognized option: --experimental_allow_incremental_repository_updates
Bazel query failed: exit status 2
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'query' from e:\practice\appbazel\.bazelrc:
  Inherited 'common' options: --experimental_allow_incremental_repository_updates
ERROR: Unrecognized option: --experimental_allow_incremental_repository_updates
Bazel query failed: exit status 2
Runing //src:devserver
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'query' from e:\practice\appbazel\.bazelrc:
  Inherited 'common' options: --experimental_allow_incremental_repository_updates
ERROR: Unrecognized option: --experimental_allow_incremental_repository_updates
Error running Bazel exit status 2
E:\practice\appBazel\node_modules\@bazel\ibazel\bin\windows_amd64\ibazel.exe failed with code 4.
```

**Comment by alan-agius4** [comment]
Looks like it’s a problem with bazel version mismatches.

Try to globally install the same version of Bazel that is needed by your project.

``` 
npm I @bazel/bazel@0.26.1 -g

**Comment by chgc** [comment]
thanks for all the helps.

**Comment by hiepxanh** [comment]
I still got that error @chgc  how can you fix it? 
this is my devDependencies:
```
 "devDependencies": {
        "@angular/bazel": "angular/bazel-builds#8.0.0+762fc28",
        "@angular/cli": "8.0.1",
        "@angular/compiler": "8.0.0",
        "@angular/compiler-cli": "8.0.0",
        "@bazel/bazel": "^0.26.1",
        "@bazel/benchmark-runner": "0.1.0",
        "@bazel/buildifier": "0.25.1",
        "@bazel/ibazel": "0.10.3",
        "@bazel/karma": "~0.31.1",
        "@bazel/typescript": "~0.31.1",
        "@types/jasmine": "3.3.13",
        "@types/node": "6.14.6",
        "clang-format": "1.2.4",
        "core-js": "2.6.8",
        "firebase-tools": "7.0.0",
        "husky": "0.14.3",
        "protractor": "6.0.0",
        "ts-morph": "2.1.2",
        "typescript": "3.4.5"
    },
```
 bazel version: `
Build label: 0.26.0
`
already try `@bazel/bazel@0.26.1` and `@bazel/bazel@latest` nothing work sir
