### ISSUE TITLE
Can't use ng command

### ISSUE THREAD

**Issue by jiaming0708** [angular/angular-cli#1486]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX EI 10.11.6

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
node --version
v6.2.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I created a new project, and built it. I got an error

1.ng new project
2.cd project
3.ng build <== fail

4. The log given by the failure. Normally this include a stack trace and some
   more information.

module.js:442
    throw err;
    ^

Error: Cannot find module 'exists-sync'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/jimmy/Desktop/juice/node_modules/angular-cli/node_modules/ember-cli/lib/models/project.js:11:26)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

5. Mention any other details that might be useful.

I can't use any 'ng' command in this project, always show the error

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
What is the version of the CLI? I remember we had that problem in an older version but it should be fixed now.

**Comment by jiaming0708** [comment]
angular-cli: 1.0.0-beta.8
i could run it at the same step at one week ago.

**Comment by filipesilva** [comment]
Can you update to `1.0.0-beta.10`? I think it's fixed in that version.

**Comment by jiaming0708** [comment]
OK~It's success!!Thanks

**Comment by filipesilva** [comment]
Awesome, glad to hear that!
