### ISSUE TITLE
Generate and improve test/spec generation

### ISSUE THREAD

**Issue by Calidus** [angular/angular-cli#14872]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
There are lots of ~~Enterprise~~ Angular Apps that have really spotty testing. There isn't a way to generate a .spec.ts file for an existing component or service. Wiring up a TestingModule for each component is a slow process by hand if you are not familiar with the code base.

### Describe the solution you'd like
The ability to generate a spec file similar to that which `ng generate component` generates but from an existing component or service.

`ng generate spec app.component.ts`

**Comment by FDIM** [comment]
To add to this, it would be amazing if the spec could be updated later on (if important bits are not changed) as well. 
E.g. if I modify component A, and add B dependency - running the generate spec command would add additional mock in form of `jasmine.createSpy<B>('B', ['methodA'])` (only listing used methods)

The tricky bit I encountered while doing internal lib during hackaton, is to provide an ability to customize on how certain dependencies are mocked. For example, if event bus service is used, generator should add a replay subject for each used event for easy testing and override `of` method with appropriate implementation. 

The last bit is what had most benefits for us - adding 3 lines manually for 1 dependency is a bit annoying, but manageable. Adding >10 lines, x number of reply subjects and some logic in `of` method is an error prone chore. 

I'll investigate schematics and see if I could somehow merge what I did with current implementation.

**Comment by vikerman** [comment]
@FDIM - We discussed this and decided it would be good to just have and option for each of the existing schematics(component, service, class) to have an option to just generate the specs. WDYT?

**Comment by FDIM** [comment]
Okay, sorry for late update but I've got the permission and I have open sourced the library I did at work.

Maybe it could be used as an inspiration for future schematic.

See [jasmine-unit-test-generator](https://www.npmjs.com/package/jasmine-unit-test-generator)

**Comment by alan-agius4** [comment]
Closing in favour of https://github.com/angular/angular-cli/issues/7727
