### ISSUE TITLE
NullInjectorError when running with --prod

### ISSUE THREAD

**Issue by fabioscala** [angular/angular-cli#14878]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes this is a regression in `@angular-devkit/build-angular` starting from `0.800.2` (works with `0.800.1`).

### Description

After building or serving with `--prod` (probably the build optimizer when I look at changes between `0.800.1` and `0.800.2`) I get a `NullInjectorError`

## 🔬 Minimal Reproduction

DI setup:
- App module
- Core module -> NGXS/States
- NGXS bootstraps/initializes the states
- `AuthState` -> (`Store`, `AuthApiService`, `LoggerService`)

The one not found is the `AuthApiService`.
I am aware that this might as well be an issue with NGXS and that this is not really a viable way for you guys to reproduce the issue. But given the very few commits between 0.800.1 and 0.800.2 I though you might be able to still pin down the issue or give me more information on why this issue occurs now.

If not, I might be able to dig deeper and/or figure out if it's an NGXS issue and/or reproduce it minimally. However, it is a regression.

## 🔥 Exception or Error
<pre><code>
core.js.pre-build-optimizer.js:1354 Uncaught NullInjectorError: StaticInjectorError(s)[r -> a]: 
  StaticInjectorError(Platform: core)[r -> a]: 
    NullInjectorError: No provider for a!
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.4
Node: 12.3.1
OS: darwin x64
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cdk                      8.0.1
@angular/cli                      8.0.4
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.1
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by fabioscala** [comment]
Alright was able to figure it out. I was defining a decorated class within a method of a service.
However since I no longer have this issue and this use-case is rather.. special, you can go ahead and close the issue. However it is worth mentioning that it didn't cause any issues before. So it's up to you guys to decide what to do with this issue.

**Background (or: why the hell am I doing something like this)**
It was a small entity which is decorated with deserialization annotations which is why I didn't bother moving it out. But yeah looking at it now it doesn't make too much sense and moving it out of the method solves the problem.

**Reproduction**
Inject following service into a component and `ng serve --prod`
```typescript
import { Injectable } from '@angular/core';


const Decorator = (target: any, key: string): any => {
  return;
};


@Injectable({
  providedIn: 'root',
})
export class FooBarService {
  someMethod() {
    class FooBar {
      @Decorator
      foo: boolean;
    }


    // do something
  }
}
```

**Comment by alan-agius4** [comment]
Hi, thanks for getting back to us. I am going to close this for now unless we see that more people use this pattern.
