### ISSUE TITLE
Angular-cli & Maven

### ISSUE THREAD

**Issue by Chabane** [angular/angular-cli#1488]
Hi,

I want to deploy my angular 2 application into a java web container like Apache Tomcat. How can I do this with Angular-cli and Maven please? Using Broccoli & SystemJS (Without Gulp-war or Webpack-war).

Thank's

Best Regards

**Comment by houssemzaier** [comment]
Hi, just copy the content of your dist folder to the web container. Then redirect all requests that you have used with " angular-router "  to the SPA index.html. 
Buy using this 2 steps you will have Angular2 running into Tomcat or any Java server.

**Comment by filipesilva** [comment]
I can't answer this myself since I don't use the infrastructure you mention, but I will leave it open so people can pitch in solutions.

**Comment by andvasp** [comment]
Hi guys...

@houssemzaier  I am using Tomcat as my java server. Can you explain how to do the second step? "Then redirect all requests that you have used with " angular-router " to the SPA index.html".

Maybe this step is to solve the problem that I have below.

Using the angular-router the strategy, if i try to load directly in the browser one address routed (e.g. http://localost:8000/app/about). It shows to me an error. I need to go to the root and then choose about.

**Comment by houssemzaier** [comment]
Hi andvasp
well I am a spring java backEnd developper . I have always used spring MVC , but I don't use all the mvc staff with SPA. 
I give you a code snippet that you w'ill find it really helpful if you do are using SpringFramework:

/****************************************************/

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller
public class ViewController {

	 
	@RequestMapping({ "/bikes", "/milages", "/gallery", "/tracks", "/tracks/{id:\\w+}", "/location", "/about", "/tests","/tests/new","/tests/**","/questions","/answers" })
	public String index() {
		return "forward:/index.html";
	}

/****************************************************/

I think it is clear for Java Spring developers but you can feel free to ask for more.

**Comment by andvasp** [comment]
Hi @houssemzaier.

Understood! My application backend is built using spring so will not be complicated to do it.

Do you know if it is possible to do it without spring using some configuration in web.xml file?

Thanks!

**Comment by wulfsberg** [comment]
A cheap trick is to simply set your 404 error page to your index.html.
That way, the Java server will do it's thing with all static files and registered servlets, and give you the SPA entry for routes it does not recognize.

Of course, this means that your app is delivered with a status code 404, which, while working, is not pretty. To work around this, you can redirect to a JSP file which sets the status code to 200, and includes the index.html.

So in your web.xml, include
````
<error-page>
    <error-code>404</error-code>
    <location>/index.jsp</location>
</error-page>
````
and create an `index.jsp` with
````
<% response.setStatus(200); %><%@ include file="/index.html" %>
````

**Comment by andvasp** [comment]
Hi @wulfsberg

Pretty good solution too. Thanks!

**Comment by filipesilva** [comment]
Thanks for all the nice solutions you all put up here! I'm considering this issue closed unless someone tells me there's still problems.
