### ISSUE TITLE
"Illegal character in path" when building from character encoded directories

### ISSUE THREAD

**Issue by adamdport** [angular/angular-cli#14894]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
7

### Description

 A clear and concise description of the problem...
If I build from a directory called `angular`, my project builds fine. If the directory is called `angular%2f`, however, `ng build` fails. 

## 🔬 Minimal Reproduction
This problem arose on Jenkins while using CI and the standard git flow naming conventions (eg. `release/2019.6` becoming `release%2f2019.6`)

## 🔥 Exception or Error
<pre><code>

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/load
er.js??ref--13-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Unsupported operation: Illegal character in path: angular/
</code></pre>
Note how it's parsing the directory as `angular/` instead of `angular%2f`.

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.2
Node: 10.16.0
OS: win32 x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.2
@angular-devkit/build-angular     0.800.2
@angular-devkit/build-optimizer   0.800.2
@angular-devkit/build-webpack     0.800.2
@angular-devkit/core              8.0.2
@angular-devkit/schematics        8.0.2
@angular/cli                      8.0.2
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.0.2
@nguniversal/express-engine       7.1.1
@schematics/angular               8.0.2
@schematics/update                0.800.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [dart sass](https://github.com/sass/dart-sass)  project or file an issue on their issue tracker.
