### ISSUE TITLE
Cannot read property 'projectType' of undefined

### ISSUE THREAD

**Issue by ashu8912** [angular/angular-cli#14900]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

 A clear and concise description of the problem...
I have my app bootstrapped with @angular/cli  7.2.4 
Now when i wanted to bring ssr into my app(onto the old code) starting with command 
ng g universal --clientProject {My Project Name Here}....It throws me an error saying 
Cannot read property 'projectType' of undefined
And when i do.....ng add @nguniversal/express-engine --clientProject {My Project Name}
 it says (/src/main.server.ts) not found This is what for i want to do ng g universal coz this 
command generates the required files for me but as it is not working i am stuck now

## 🔥 Exception or Error
<pre><code>

Cannot read property 'projectType' of undefined 
</code></pre>

## 🌍 Your Environment
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cdk                      7.3.7
@angular/cli                      7.2.4
@angular/material                 7.3.7
@ngtools/webpack                  7.2.4
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Can you try to update to a more recent version of the CLI and see if this solved your issue?

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem. 

Thanks,
