### ISSUE TITLE
Source maps does not work

### ISSUE THREAD

**Issue by mmrath** [angular/angular-cli#1490]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX El Captain, Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

latest master

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

https://github.com/mmrath/cli-proxy-test.git 
Keep break points in app.component.ts from chrome. Chrome does not stop on the right place.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
@TheLarkInn should your sourcemap solution have fixed this scenario?

**Comment by TheLarkInn** [comment]
This is a chrome issue I believe @mmrath can you do me a favor and try this in Chrome Canary just to make sure it's the issue I believe it is.

**Comment by mmrath** [comment]
@TheLarkInn I tried it in Chrome Canary, the behaviour is same. It still does not work.

**Comment by mmrath** [comment]
This could be related to https://github.com/webpack/webpack/issues/2145

**Comment by TheLarkInn** [comment]
Yup that was the issue I was looking for. I will be speaking with a few folks from Chrome next week (in the context of that issue and other stuff). I'll make sure to keep track of this and update accordingly.

**Comment by masaanli** [comment]
I can confirm this, having the same issue.

It only debugs if i add a debugger; in my code ;)

**Comment by mmrath** [comment]
@TheLarkInn Does not look like this issue is resolved. I have seen the commit #1659 . I took the latest master and created a new project added material2. Now ng serve is failing. 

If I change to  `'cheap-module-source-map'` from `'source-map'`, `ng serve` is OK, but debugging does not work.

Sample repo to reproduce is at https://github.com/mmrath/test-cli-source-map.git


`ng serve` throws the following error with latest master. I see the same error even on osx

TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (C:\Projects\angular-cli\node_modules\webpack-sources\node_modules\source-map\lib\source-node.js:95:30)
    at Array.forEach (native)
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\Projects\angular-cli\node_modules\webpack-sources\node_modules\source-map\lib\source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (C:\Projects\angular-cli\node_modules\webpack-sources\node_modules\source-map\lib\source-node.js:80:24)
    at SourceMapSource.node (C:\Projects\angular-cli\node_modules\webpack-sources\lib\SourceMapSource.js:42:20)
    at ReplaceSource.node (C:\Projects\angular-cli\node_modules\webpack-sources\lib\ReplaceSource.js:66:29)
    at CachedSource.node (C:\Projects\angular-cli\node_modules\webpack-sources\lib\CachedSource.js:12:23)
    at C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:40:49
    at Array.map (native)
    at ConcatSource.node (C:\Projects\angular-cli\node_modules\webpack-sources\lib\ConcatSource.js:39:60)
    at ConcatSource.proto.sourceAndMap (C:\Projects\angular-cli\node_modules\webpack-sources\lib\SourceAndMapMixin.js:28:18)
    at CachedSource.sourceAndMap (C:\Projects\angular-cli\node_modules\webpack-sources\lib\CachedSource.js:51:28)
    at Compilation.<anonymous> (C:\Projects\angular-cli\node_modules\webpack\lib\SourceMapDevToolPlugin.js:57:32)

**Comment by masaanli** [comment]
Source maps are working after your commit @TheLarkInn  at least at my place.

**Comment by mmrath** [comment]
@masaanli any chance you can try the repo I mentioned in the previous comments. It would be good to if it is just me. I tried in on both my windows and Mac

**Comment by filipesilva** [comment]
Reopening to investigate.

**Comment by ValeryVS** [comment]
@mmrath I have got the same
Cannot read property 'substr' of undefined
error with your repository, and it is appears with material2 
Without material2, "ng serve" works properly.

Also, not all of material2 modules trigger this error. If you import just some of them project will compile.

Also, source maps are wrong with [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap) v1.0.24

But [@ng-bootstrap/ng-bootstrap](https://github.com/ng-bootstrap/ng-bootstrap) 1.0.0-alpha.2 works well.

**Comment by ValeryVS** [comment]
May be this is an issue with precompiled source maps in some material2 and ng2-bootstrap modules.
Or with the way of handling these maps by angular cli

**Comment by filipesilva** [comment]
@mmrath it took me a while to get back to this, apologies. I tried with the latest `angular-cli@webpack` and `angular2-material@alpha.8-1` and I got no errors.

I think this was due to buggy source maps on these libs before. For instance, a while ago all the sourcemaps the CLI generated were themselves broken. In this case, the best we can do is to ignore them since it broken sourcemaps there is no way to accurately debug the source.

**Comment by dancancro** [comment]
I don't know whether it has the same cause but source maps are not working in [my project](https://github.com/dancancro/great-big-angular2-example) either. I'm using angular-cli@1.0.0-beta.18 and @angular/material@2.0.0-alpha.9-3

**Comment by filipesilva** [comment]
@dancancro there was a regression in beta.18 with sourcemaps, upgrading to beta.19-3 should fix it.

**Comment by dancancro** [comment]
Thank you. It looks like that fixed it.

**Comment by doliver3** [comment]
This error is occurring in  "angular-cli": "1.0.0-beta.21"

**Comment by filipesilva** [comment]
@doliver3 can you tell me how you repro'd it?

**Comment by jstaffans** [comment]
I also have this problem running angular-cli 1.0.0-beta.24. It only occurs when running `ng serve` or `ng build` in a Docker container, though.

**Comment by JSMike** [comment]
For docker users. Are your node_modules being shared from the host machine? there may be an issue with how docker follows the sym-links in your mounted directories. Look into installing node_modules with --no-bin-links
