### ISSUE TITLE
TypeError : meta is undefined, @angular-devkit/build-angular: 0.800.3 => 0.800.4 

### ISSUE THREAD

**Issue by cedx** [angular/angular-cli#14910]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes, the previous version in which this bug was not present was:
`@angular-devkit/build-angular: 0.800.3`

### Description
This project : https://github.com/cedx/ngx-core.js
has tests that worked fine until I upgraded `@angular-devkit/build-angular` to version 0.800.4 (i.e. if I revert this package, and only this package, to version 0.800.3, everything is OK).

## 🔬 Minimal Reproduction
I have absolutely no idea how to reproduce this bug. The stack trace is unreadable for me, so I don't know where and how to start investigations.

## 🔥 Exception or Error
<pre><code>
TypeError: meta is undefined in http://localhost:9876/_karma_webpack_/vendor.js (line 38610)
	error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 33603585, rootNodeFlags: 33554433, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 33554433, childFlags: 49152, directChildFlags: 49152, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 1, bindings: [  ], bindingFlags: 0, outputs: [  ], element: Object({ ns: '', name: 'test-component', attrs: [  ], template: null, componentProvider: Object({ nodeIndex: 1, parent: <circular reference: Object>, renderParent: <circular reference: Object>, bindingIndex: 0, outputIndex: 0, checkIndex: 1, flags: 49152, childFlags: 0, directChildFlags: 0, childMatchedQueries: 0, matchedQueries: Object, matchedQueryIds: 0, references: Object, ngContentIndex: -1, childCount: 0, bindings: Array, bindingFlags: 0, outputs: Array ...
	injectArgs@http://localhost:9876/_karma_webpack_/vendor.js:38610:21
	convertInjectableProviderToFactory/<@http://localhost:9876/_karma_webpack_/vendor.js:39201:27
	_callFactory@http://localhost:9876/_karma_webpack_/vendor.js:61211:20
	_createProviderInstance@http://localhost:9876/_karma_webpack_/vendor.js:61154:26
	resolveNgModuleDep@http://localhost:9876/_karma_webpack_/vendor.js:61113:17
	get@http://localhost:9876/_karma_webpack_/vendor.js:62206:16
	resolveDep@http://localhost:9876/_karma_webpack_/vendor.js:62736:45
	createClass@http://localhost:9876/_karma_webpack_/vendor.js:62580:29
	createDirectiveInstance@http://localhost:9876/_karma_webpack_/vendor.js:62400:22
	createViewNodes@http://localhost:9876/_karma_webpack_/vendor.js:73006:38
	createRootView@http://localhost:9876/_karma_webpack_/vendor.js:72878:5
	callWithDebugContext@http://localhost:9876/_karma_webpack_/vendor.js:74407:27
	debugCreateRootView@http://localhost:9876/_karma_webpack_/vendor.js:73644:12
	create@http://localhost:9876/_karma_webpack_/vendor.js:61542:31
	initComponent@http://localhost:9876/_karma_webpack_/vendor.js:78325:51
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116371:26
	./node_modules/zone.js/dist/zone-testing.js/</</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:114629:39
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116370:52
	onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:68904:33
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116370:52
	./node_modules/zone.js/dist/zone.js/</</Zone.prototype.run@http://localhost:9876/_karma_webpack_/vendor.js:116130:43
	run@http://localhost:9876/_karma_webpack_/vendor.js:68769:91
	createComponent@http://localhost:9876/_karma_webpack_/vendor.js:78329:60
	createComponent@http://localhost:9876/_karma_webpack_/vendor.js:77884:40
	./test/directives/document_title_test.ts/</</<@http://localhost:9876/_karma_webpack_/main.js:1636:91
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116371:26
	./node_modules/zone.js/dist/zone-testing.js/</</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:114629:39
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116370:52
	./node_modules/zone.js/dist/zone.js/</</Zone.prototype.run@http://localhost:9876/_karma_webpack_/vendor.js:116130:43
	runInTestZone@http://localhost:9876/_karma_webpack_/vendor.js:114882:34
	wrapTestInZone/<@http://localhost:9876/_karma_webpack_/vendor.js:114897:20
	<Jasmine>
	runInTestZone/</testZoneSpec</<@http://localhost:9876/_karma_webpack_/vendor.js:115203:21
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116371:26
	./node_modules/zone.js/dist/zone-testing.js/</</ProxyZoneSpec.prototype.onInvoke@http://localhost:9876/_karma_webpack_/vendor.js:114629:39
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116370:52
	./node_modules/zone.js/dist/zone.js/</</Zone.prototype.run@http://localhost:9876/_karma_webpack_/vendor.js:116130:43
	runInTestZone/</testZoneSpec<@http://localhost:9876/_karma_webpack_/vendor.js:115202:29
	./node_modules/zone.js/dist/zone-testing.js/</</AsyncTestZoneSpec.prototype._finishCallbackIfDone/</<@http://localhost:9876/_karma_webpack_/vendor.js:115034:31
	./node_modules/zone.js/dist/zone.js/</</ZoneDelegate.prototype.invokeTask@http://localhost:9876/_karma_webpack_/vendor.js:116403:31
	./node_modules/zone.js/dist/zone.js/</</Zone.prototype.runTask@http://localhost:9876/_karma_webpack_/vendor.js:116175:47
	./node_modules/zone.js/dist/zone.js/</</ZoneTask.invokeTask@http://localhost:9876/_karma_webpack_/vendor.js:116478:34
	ZoneTask/this.invoke@http://localhost:9876/_karma_webpack_/vendor.js:116467:48
	timer@http://localhost:9876/_karma_webpack_/vendor.js:119050:29
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.4
Node: 12.4.0
OS: linux x64
Angular: 8.0.2
... common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.4
@angular-devkit/build-angular      0.800.4
@angular-devkit/build-ng-packagr   0.800.4
@angular-devkit/build-optimizer    0.800.4
@angular-devkit/build-webpack      0.800.4
@angular-devkit/core               8.0.4
@angular-devkit/schematics         8.0.4
@angular/cli                       8.0.4
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.4
@schematics/angular                8.0.4
@schematics/update                 0.800.4
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

Using Chrome instead of Firefox does not change anything: the error is still raised.

The tests (https://github.com/cedx/ngx-core.js/blob/master/test/directives/document_title_test.ts) involve a directive (https://github.com/cedx/ngx-core.js/blob/master/src/directives/document_title.ts#L27) that depends on a service (https://github.com/cedx/ngx-core.js/blob/master/src/services/application.ts#L64) that uses the `Meta` service.

I rely on the error message: `meta is undefined`. But again, I have absolutely no idea of the origin of the error.

EDIT : https://travis-ci.com/cedx/ngx-core.js/builds/116878254, if it helps.

**Comment by alan-agius4** [comment]
Possibly related to https://github.com/angular/angular-cli/issues/14888

**Comment by cedx** [comment]
After upgrading to Angular v8.1.0 and `@angular-devkit/build-angular` v0.801.0, the error is gone :smile:
I think we can say that the issue has been fixed.
