### ISSUE TITLE
Invalidating lazy loaded modules

### ISSUE THREAD

**Issue by Enngage** [angular/angular-cli#14919]
Hi!

Hopefully this is the correct repo to ask as I'm not sure if its more related to CLI or angular itself, just as I'm not sure if its intentional or possible bug/feature request, but here we go - I have following setup:

- Differential loading
- Lazy modules
- Angular source files hosted on CDN
- Angular app available on multiple domains

The problem I'm struggling with is that Angular requests all child modules with:

```javascript
https://cdn.net/app/30-es2015.js
https://cdn.net/app/31-es2015.js
```

When deploying new version I need to change the version query string (as can be seen above) as otherwise when angular requests:

```
https://cdn.net/app/30-es2015.js
```
it loads cached version because the `max-age` is set to a year and its cached in the CDN anyways so it wouldn't get latest version.

This would be ok if I could control the query string of lazy loaded modules. Is that possible?

Thank you for any suggestions or help :-)

```
Angular CLI: 8.0.4
Node: 10.13.0
OS: win32 x64
Angular: 8.1.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cdk                      8.0.1
@angular/cli                      8.0.4
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.0.1
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by alan-agius4** [comment]
Hi there,

First Point: I am not quite following the root issue here and how a query string is fixing a CORS problem.

Second Point: regarding cache busting, you should be using `outputHashing` which when set defines the output filename cache-busting hashing mode.

See: https://angular.io/cli/build

**Comment by Enngage** [comment]
Hi @alan-agius4,

Thank you for the response. This is problem with some CDNs as they cache also the origin and so if you request same resource with XHR from multiple domains, all but the one that was cached will fail due to incorrect origin. However, you're right, this was my bad as I just noticed the child modules are not requested with XHR, but are added to DOM as regular `script` tags. 

I'm not sure if I can use `outputHashing` because the core angular files (main.js, polyfills.js, runtime.js) are served by server and that would mean we have to make a new release for the server application just to update hashed files. 

Or would it be possible to use hashing just for lazy modules and keep core files unhashed?

**Comment by alan-agius4** [comment]
@Enngage, no you cannot add hashing to lazy chunks only. Though it's important to point, that unless the file contents changes the file hash will remain the same.

**Comment by Enngage** [comment]
I guess that is fine, but I think there could be a way of telling Angular how the URL of those scripts is constructed as I hope that my scenario is not that far fetched. I'm guessing there is no way to adjust URL currently?

It seems like we will have to move `index.html` to CDN as well in which case outputCaching will work nicely.

**Comment by alan-agius4** [comment]
IMHO, the optimal solution would be that have the entire application being served from CDN. 

I think the original problem here is the absence of  `Vary: Origin`. That being said I don't see why scripts (inc. entry scripts and lazy module scripts) should be different for each domain and should vary between domains since these are not requested via XHR, and should be the same for all.

With version 8.1, we expose an indexHtml transformer which you can use in a custom builder to augment the index content since this seems to be quite an edge case. 

You can take a look at this custom builder on how this is done https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack#index-transform

I hope I was of help :)
