### ISSUE TITLE
bazel should support less loader

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular-cli#14924]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Angular or Angular CLI should support less loader

### Describe the solution you'd like

Angular CLI support ng new with bazel and `less loader` before `@angular/cli@8.0.3`
but there is a bug https://github.com/angular/angular/issues/31209

The less option was removed after `8.1.0-rc.0` with https://github.com/angular/angular/pull/31234

Angular CLI should support `less` when run

`ng new --collection=@angular/bazel`

### Describe alternatives you've considered

Angular CLI should support `less` option with bazel

**Comment by alan-agius4** [comment]
Related to https://github.com/bazelbuild/rules_nodejs/issues/887
