### ISSUE TITLE
Copying build on different OS fails

### ISSUE THREAD

**Issue by ShadabFaiz** [angular/angular-cli#14922]
**Question:** Does the build created on a OS( says Windows ) will work on the different ?
**What I did:**
I build the application on windows and copied the build directory to a linux. Then I used nginx server to point it to the dist directory. The server is not able to load those file. In the console also, there is not error. All nginx show is 404 page (directory path is correct.)

**Comment by alan-agius4** [comment]
The build output is the same and can run on different OS. This seems to be more of an ngnix configuration issue. 

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
