### ISSUE TITLE
Accessing root address will not redirect to base href

### ISSUE THREAD

**Issue by Nitue** [angular/angular-cli#14925]
# 🐞 bug report

### Is this a regression?

Yes, the previous version in which this bug was not present was: 7.2.15

### Description

When you create minimal application, set the base href (e.g. "/test/") and access http://localhost:4200 instead of http://localhost:4200/test/. You are not redirected to http://localhost:4200/test/ but shown white page containing:

<pre><code>Cannot GET /</code></pre>

In Angular 7, setting the base href will redirect you to http://localhost:4200/test/ when you access http://localhost:4200.

## 🔬 Minimal Reproduction
You can reproduce the problem by creating a minimal Angular application with the CLI.

<pre><code>ng new angular-basehref-test --interactive=false
cd angular-basehref-test
ng serve --baseHref=/test/</code></pre>

Then go to http://localhost:4200 instead of http://localhost:4200/test/

Setting "baseHref" in angular.json results in the same out come.

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 8.0.4
Node: 10.16.0
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.4
@angular-devkit/build-angular     0.800.4
@angular-devkit/build-optimizer   0.800.4
@angular-devkit/build-webpack     0.800.4
@angular-devkit/core              8.0.4
@angular-devkit/schematics        8.0.4
@angular/cli                      8.0.4
@ngtools/webpack                  8.0.4
@schematics/angular               8.0.4
@schematics/update                0.800.4
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by clydin** [comment]
This is expected and correct behavior.  The application is being served under the ‘/test/‘ path which is defined as the base of the application.  The “servePath” option is available to alter the path of the application, if desired.

**Comment by ayyash** [comment]
are you saying that if I
```
ng serve --servePath=/test/
```
localhost:4200 will automatically redirect to localhost:4200/test?
Can you please confirm this? (because that is how Angular 7.0 worked)

**Comment by Nitue** [comment]
I could not reproduce the previous behavior with the "servePath" option or with any other options.

**Comment by clydin** [comment]
@ayyash No.  The URL rewriting found within the CLI is specifically intended to support HTML5 path-based routing.  This means that a URL that is within the application's root served path will be redirected to the index HTML contained at the application's root served path (if no actual file is present at that location).

In the situation above, the root of the server is not part of the application and therefore has no bearing on the Application's routing.  Barring a specific rewrite or redirect rule added via a proxy, the URL for the root of the server does not reference anything.
