### ISSUE TITLE
buildRelativePath produces incorrect path

### ISSUE THREAD

**Issue by kahanu** [angular/angular-cli#14928]
# 🐞 Bug report
This is an incorrect result that I'm receiving when creating a custom schematic.  I'm just including a code snippet for the part of the schematics libraries utilities that produce this issue.

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I created an Angular Workspace, then an application (demo-one, and demo-two), and a Library project for this example.

The relative path produced by ```buildRelativePath``` works when working within the same project between folders, but doesn't seem to work when using workspaces, between a library and an application.

Here's the default application structure built by the Angular Cli:

```
projects
  |
  |- demo-two
       |- src
           |- environments
  |...
  |- shared-libs
       |- src
           |- core
               |- interceptors
```

## 🔬 Minimal Reproduction
    const fromPath = '/projects/shared-libs/src/core/interceptors';
    const toPath   = '/projects/demo-two/src/environments';

    const relativePath = buildRelativePath(fromPath, toPath);
    console.log('relative path: ', relativePath);
    
    relativePath returns "../../../demo-two/src/environments"
    
    C:\Users\king\source\repos\Schematics\HostWorkspace\projects\demo-two\src\environments
    C:\Users\king\source\repos\Schematics\HostWorkspace\projects\shared-libs\src\core\interceptors
    
    
    should be "../../../../demo-two/src/environments"

## 🔥 Exception or Error
No error, just an incorrect relative path.

## 🌍 Your Environment
<pre><code>
    Angular CLI: 7.1.4
    Node: 8.11.3
    OS: win32 x64
    Angular: 7.1.4
    npm: 5.6.0
</code></pre>

**Anything else relevant?**

Please let me know if I'm doing something incorrectly.

**Comment by francescodist** [comment]
The problem here is that the `buildRelativePath` function is expecting the path of two SPECIFIC files (with the name of the file included). In fact it is meant to return the path to that specific "to" file. 
So the function works as intended with the following example:
``` javascript
const fromPath = '/projects/shared-libs/src/core/interceptors/file1.js';
const toPath   = '/projects/demo-two/src/environments/file2.js';

const relativePath = buildRelativePath(fromPath, toPath);
console.log(relativePath);

// THIS WILL LOG: '../../../../demo-two/src/environments/file2.js'
```
Now the question is if we want to create a function that will deal with paths that don't point to a specific file. I can open a PR once a decision is taken on that regard.

P.S. For reference I will paste here the relevant code from `buildRelativePath` in `@schematics/utility/find-module.js` (lines 90 to 94)
``` javascript
    const fromParts = from.split('/');
    const toParts = to.split('/');
    // Remove file names (preserving destination)
    fromParts.pop();
    const toFileName = toParts.pop();
```

**Comment by kahanu** [comment]
@francescodist thanks for the info.  I'll check it out and modify my code and let you know if I have any other issues with this.  I'll close this for now.  But it may be a consideration to just point to folders.  In my example I wanted to modify the environments files to include a new property, and figured I could just point to the folder to get a reference to that path and then modify all the files in that folder with the new schematic data.  Just a thought.
