### ISSUE TITLE
Application is throwing error in IE 11 with ng build --watch 

### ISSUE THREAD

**Issue by SathyaChenniappan** [angular/angular-cli#14923]
I am using Angular 8 . Application is throwing error in IE 11 with ng build --watch . But its working fine with ng build --prod command.
![image](https://user-images.githubusercontent.com/40464122/60252809-8902af80-98e8-11e9-956c-42f7729fade1.png)

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/14455

**Comment by alan-agius4** [comment]
And also related to https://github.com/angular/angular-cli/issues/14911#issuecomment-506195391
