### ISSUE TITLE
Document how to map external less files

### ISSUE THREAD

**Issue by thelgevold** [angular/angular-cli#1493]
I am requesting documentation on how to map to imported less files in the webpack version of CLI.

In the previous version there was a hook in angular-cli.builds.js to specify paths for the lessCompiler:

```
lessCompiler: {
      paths: ['node_modules/some-path/less']
    }
```

angular-cli.builds.js is no longer included in the version on master. 

It works to specify less files in styleUrls, but I am not able to import other less files from my component less files.

**Comment by filipesilva** [comment]
Possibly related https://github.com/angular/angular-cli/issues/1465

I don't have an answer for this at the moment. @TheLarkInn can you advise if there's a solution right now?

**Comment by TheLarkInn** [comment]
Yeah its related overall. @thelgevold we need to make essentially a property that allows this for all the preprocessers we support (behind the scenes).

**Comment by thelgevold** [comment]
Thanks @TheLarkInn .
I wonder if there might be a similar issue when dealing with `paths` in tsconfig.json.

`paths` was added in TS 1.9 and is a way to create an alias to avoid long relative import paths.

If I run tsc my code compiles, but during `ng build` I get module not found errors, so I suspect the paths have to be "ferried" into the webpack world somehow?

**Comment by sirajc** [comment]
Maybe, mapping `paths` of tsconfig to `resolve.alias` of webpack

**Comment by clydin** [comment]
@thelgevold The webpack specific method is to prefix the name of the package with  a `~`.
For example, `@import "~some-path/less/file";`
This is probably not the long-term solution, but might get you up and running.

**Comment by TheLarkInn** [comment]
Yeah this is great in webpack land but not user land.

**Comment by clydin** [comment]
For sass/scss, there is https://github.com/lucasmotta/sass-module-importer.  It supports reading a module's `package.json` which allows a simple `@import "<package-name>"`.  This would allow sass/scss to mimic the typescript workflow of `npm install` and `import`.

**Comment by filipesilva** [comment]
Supersedes by https://github.com/angular/angular-cli/issues/1791, work in progress on https://github.com/angular/angular-cli/pull/2747
