### ISSUE TITLE
Bazel opt in : ng add @angular/bazel fails

### ISSUE THREAD

**Issue by hugodes** [angular/angular-cli#14933]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ x ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I followed the steps [here](https://docs.google.com/presentation/d/1CZsABQJDjpBLun5Ewk3lNUTAHX2Y-pUb3-dfLMZ22DE/preview?slide=id.g568f4cb48a_1_7) for using Bazel in out existing application and got this error:

<pre><code>
$ ng add @angular/bazel
Unable to find compatible package.  Using 'latest'.
Installing packages for tooling via npm.
npm WARN @angular/cdk@8.0.1 requires a peer of @angular/core@^8.0.0 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/cdk@8.0.1 requires a peer of @angular/common@^8.0.0 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@8.0.1 requires a peer of @angular/animations@^8.0.0 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@8.0.1 requires a peer of @angular/core@^8.0.0 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@8.0.1 requires a peer of @angular/common@^8.0.0 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material@8.0.1 requires a peer of @angular/forms@^8.0.0 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/material-moment-adapter@8.0.1 requires a peer of @angular/core@^8.0.0 || ^9.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/effects@8.0.1 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngrx/store@8.0.1 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/bazel@8.0.3 requires a peer of @angular/compiler-cli@8.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/bazel@8.0.3 requires a peer of @bazel/typescript@0.* but none is installed. You must install peer dependencies yourself.

+ @angular/bazel@8.0.3
added 32 packages from 85 contributors and audited 26308 packages in 9.563s
found 0 vulnerabilities

Installed packages for tooling via npm.
Invalid JSON character: "]" at 20:11.
</code></pre>

## 🔬 Minimal Reproduction

There is no stack trace so I don't even know which file the error is coming from

## 🔥 Exception or Error
<pre><code>
Invalid JSON character: "]" at 20:11.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.1.0-rc.0
Node: 10.16.0
OS: darwin x64
Angular: 8.1.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.0-rc.0
@angular-devkit/build-angular      0.801.0-rc.0
@angular-devkit/build-optimizer    0.801.0-rc.0
@angular-devkit/build-webpack      0.801.0-rc.0
@angular-devkit/core               8.1.0-rc.0
@angular-devkit/schematics         8.1.0-rc.0
@angular/bazel                     8.0.3
@angular/cdk                       8.0.1
@angular/material                  8.0.1
@angular/material-moment-adapter   8.0.1
@ngtools/webpack                   8.1.0-rc.0
@schematics/angular                8.1.0-rc.0
@schematics/update                 0.801.0-rc.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, can you try to use  `ng add @angular/bazel@next`?

**Comment by hugodes** [comment]
Hi @alan-agius4,

Same thing here

<pre><code>
[...]
+ @angular/bazel@8.1.0-rc.0
added 32 packages from 85 contributors and audited 26308 packages in 9.993s
found 0 vulnerabilities

Installed packages for tooling via npm.
Invalid JSON character: "]" at 20:11.

</code></pre>

**Comment by alan-agius4** [comment]
Is it possible to share a reproduction?

**Comment by hugodes** [comment]
@alan-agius4 I can, but privately.

I would try to reproduce it in a public repo but error doesn't give me any insight as to which file this is coming from.

**Comment by istiti** [comment]
@hugodes  can you share your `angular.json` ?

**Comment by hugodes** [comment]
Hey again @istiti ,

Sure here you go:
[angular.zip](https://github.com/angular/angular-cli/files/3339387/angular.zip)

**Comment by istiti** [comment]
Ok, In your angular.json you have a unnecessary comma at line 20 `"src/assets",`
Even if you remove it it will not compile do to many others comma, please delete theme in line 20, 155, 183, 184, 233

Then retry temporary by running `npm uninstall @angular/bazel` then `ng add @angular/bazel@next`

**Comment by hugodes** [comment]
@istiti thanks !

Do you think it would be a good idea to change the error from:

`Invalid JSON character: "]" at 20:11.`

to

`angular.json: Invalid JSON character: "]" at 20:11.`

?

**Comment by alan-agius4** [comment]
Yeah it is.
