### ISSUE TITLE
ng build fails to copy .htaccess in angular 7

### ISSUE THREAD

**Issue by ozinisle** [angular/angular-cli#14932]
# 🐞 Bug report

### Command (mark with an `x`)
<pre><code>ng build --prod</code></pre>

### Is this a regression?

This used to work in previous versions of Angular(< 7)
 Yes, the previous version in which this bug was not present was: Angular 5

### Description

I am using the following packages
<pre><code>
 "dependencies": {
    "@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@auth0/angular-jwt": "^2.1.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.0.0",
    "@ionic/storage": "^2.2.0",
    "core-js": "^2.5.4",
    "crypto-js": "^3.1.9-1",
    "rxjs": "~6.3.3",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.12.3",
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular-devkit/core": "~7.2.3",
    "@angular-devkit/schematics": "~7.2.3",
    "@angular/cli": "~7.2.3",
    "@angular/compiler": "~7.2.2",
    "@angular/compiler-cli": "~7.2.2",
    "@angular/language-service": "~7.2.2",
    "@ionic/angular-toolkit": "~1.4.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~10.12.0",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~8.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.1.6"
  },
</code></pre>

I have defined the following as my assets to be copied during deployment in my angular.json file
<pre><code>
"assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              },
              {
                "glob": "**/*",
                "input": "src/.htaccess",
                "output": ".htaccess"
              }
            ]
</code></pre>
When I issue the following command on project's root in terminal 

<pre><code>ng build --prod</code></pre>

I see the following error. Note this error appears only when I ask it to deploy ,htaccess file

ERROR in ENOTDIR invalid cwd E:\dev\myapp\src\.htaccess

## 🔬 Minimal Reproduction
On a angular 7 project,

add the following under the assets array in angular.json (both test and build)
<pre><code>
              {
                "glob": "**/*",
                "input": "src/.htaccess",
                "output": ".htaccess"
              }
</code></pre>
add a file named as ".htaccess" with some content as follows to the src folder of your angular 7 project
<pre><code>
RewriteEngine On 
    RewriteCond %{REQUEST_FILENAME} !-f 
    RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.html [L]
</code></pre>

Issue the following angular-cli command in console

<pre><code>ng build --prod</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.2.4
Node: 9.3.0
OS: win32 x64
Angular: 7.2.8
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cli                      7.2.4
@ngtools/webpack                  7.3.8
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.29.0

</code></pre>

**Anything else relevant?**

Operating System: Window 10 64 bit
Deployed to Server in XAMPP
Editor : VSCODE

**Comment by alan-agius4** [comment]
Hi,  the mentioned error `ERROR in ENOTDIR invalid cwd `E:\dev\myapp\src.htaccess` doesn't seem to be related to Angular CLI. 

While I don't know your deploy pipeline the path should be something like: `E:\dev\myapp\dist\<project-name>.htaccess`

**Comment by istiti** [comment]
@ozinisle BTW im not sure your code is correct, considering your code: 
```
"assets": [
              {
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              },
              {
                "glob": "**/*",
                "input": "src/.htaccess",
                "output": ".htaccess"
              }
            ]
```

This last one 
```
 {
                "glob": "**/*",
                "input": "src/.htaccess",
                "output": ".htaccess"
 }           
```
Why do you have `"glob": "**/*",` ? it is not correct, this cosider your input is folder and your glob make selection in this folder....

Instead you should follow exactly same technic as `favicon` is moved so this should works:
```
 {
   "glob": ".htaccess",
   "input": "src",
  "output": "/"
 }    
```
