### ISSUE TITLE
NodeModuleEngineHost tightly coupled to process working directory

### ISSUE THREAD

**Issue by IainAdams** [angular/angular-cli#14935]
# 🚀 Feature request

### Description
This is a request for a minor change.

The schematics_cli and angular_cli assume that they will be called from inside a project directory that contains the installed schematics. 

I have no issue with this, however, if I wanted to build an alternative CLI (or Electron application (which is what I intend to do)) that won't be executed from the directory that contains the schematics but instead references an alternative directory, then I need to rebuilt this entire class (or at least subclass and override the _resolveCollectionPath method).  This has highlighted that this class is tightly coupled to process.cwd and that this should instead be passed as an argument.

**More details**
 
Class NodeModulesEngineHost. Whilst methods _resolvePackageJson, _resolvePath accept a path to be provided, _resolveCollectionPath uses process.cwd() when calling them. This means that this class will always use the processes current working directory to identify schematics.

Instead, in my opinion, the class that creates the NodeModulesEngineHost should provide the baseDir. i.e. add (private path: string) to the constructor and then update the cli implementations to pass the path.

**Comment by clydin** [comment]
This has been resolved via https://github.com/angular/angular-cli/pull/15960 and will be present in 9.0.
