### ISSUE TITLE
Custom compiler(transpiler) options for ngtools/webpack

### ISSUE THREAD

**Issue by ipetrovic11** [angular/angular-cli#14947]
# 🚀 Feature request
Additional compiler(transpiler) options for ngtools/webpack

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Setting different compiler is needed sometimes, especially if we would like to use custom TypeScript transformers. In this particular case the best option is "ttypescript" but there could be other as well. It should only support compilers that have same interface as "typescript".

### Describe the solution you'd like
It would be great if we could set which compiler will be used, as in https://github.com/TypeStrong/ts-loader ```compiler``` option. The perfect location for choosing the compiler in MY opinion would be tsconfig 

### Describe alternatives you've considered
I've tried to use custom loaders and override tsx files compilation, but the issue in this case is that everything that's done in ngtools/webpack will be left out, like including html templates, and probably many other things related to AoT.

**Comment by mgechev** [comment]
@ipetrovic11 currently folks are applying custom transformers using `ngx-build-plus`. @d3lm can give further details.

Let me know if what you want is doable with the current extension points we provide.

**Comment by d3lm** [comment]
@ipetrovic11 If you'd like to run custom TS transformations then you can indeed use [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus). You can define your own plugin and add your transformers to the `_transformers` array of the `AngularCompilerPlugin`. You can decide if you wanna run them before or after any other Angular transformers.

Do you mind elaborating on your specific use case? What are you trying to achieve?

**Comment by mgechev** [comment]
Closing the issue for now. @ipetrovic11 if `ngx-build-plus` cannot resolve your issue, feel free to open a new one with a minimal demo where we can reproduce it.

**Comment by ipetrovic11** [comment]
@mgechev @d3lm thanks for help.
Didn't have time to try it. But will do it soon.

Our case is that we are using using interfaces to define communication both in back between microservices and front. We use [fastest-validator](https://github.com/icebob/fastest-validator) to check issues in runtime. We've built our own transformer to create json schema from TS Interface - [ts-transformer-json-schema](https://github.com/ipetrovic11/ts-transformer-json-schema) .

**Comment by mgechev** [comment]
Sounds like an interesting approach!

**Comment by d3lm** [comment]
Yep, this is a perfect use case where you can leverage `ngx-build-plus`. Just plugin your transformer there as a `platformTransformer`. You have to remove the "current" AngularCompilerPlugin, and instantiate a new one with the same options including your transformers.

Let us know if you are stuck or if this doesn't solve your problem.
