### ISSUE TITLE
Issue deploying to prod missing /vendor files

### ISSUE THREAD

**Issue by tcozzens** [angular/angular-cli#1494]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**mac osx el capitan**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
**angular-cli: 1.0.0-beta.10
node: 6.0.0
os: darwin x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**No changes made, just wanted to test out CLI and deploying to a domain.**

4. The log given by the failure. Normally this include a stack trace and some
   more information.

** This is the Chrome console log: 
- http://dcluxe.com/vendor/reflect-metadata/Reflect.js - Failed to load resource: the server responded with a status of 404 (Not Found)

- http://dcluxe.com/vendor/zone.js/dist/zone.js - Failed to load resource: the server responded with a status of 404 (Not Found)

- http://dcluxe.com/vendor/systemjs/dist/system.src.js - Failed to load resource: the server responded with a status of 404 (Not Found)

- http://dcluxe.com/vendor/es6-shim/es6-shim.js - Failed to load resource: the server responded with a status of 404 (Not Found)

- http://dcluxe.com/vendor/reflect-metadata/Reflect.js - Failed to load resource: the server responded with a status of 404 (Not Found)

- http://dcluxe.com/vendor/systemjs/dist/system.src.js - Failed to load resource: the server responded with a status of 404 (Not Found)

- http://dcluxe.com/vendor/zone.js/dist/zone.js - Failed to load resource: the server responded with a status of 404 (Not Found)

index.html:19 Uncaught ReferenceError: System is not defined**

5. Mention any other details that might be useful.
This works locally. it also works if I run "ng serve -prod". But doesn't work when I deploy. I also see the files that are "missing" on the hosting that I am using.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by tcozzens** [comment]
What I mean by "I also see the files that are "missing" on the hosting that I am using." is that I actually see them on the FTP client.
 I know that if you click the links that this is showing.... 
<img width="591" alt="screenshot 2016-07-29 12 08 37" src="https://cloud.githubusercontent.com/assets/1398573/17255098/ad52aefc-5585-11e6-85dc-dbf802c7bc87.png">

Let me squirrel for a second... I think this may be my fault. I think I am missing something. 

NOW that I am looking at these links... The path should be http://dcluxe.com/**Test/**vendor/zone.js/dist/zone.js

**Comment by lexcaraig** [comment]
Windows: 10
angular-cli: 1.0.0-beta.10
node: 4.4.7
os: win32 x64

Hi Guys! May I know what is happening here when i run the commands `ng build --prod` and `ng serve --prod`. This are the errors I get I can't run the project in production. And I'm planning to actually deploy it using firebase tools, will it work if i deploy it using firebase tools?


![image](https://cloud.githubusercontent.com/assets/15936424/17290341/8f2874f6-5810-11e6-8491-b74038f86964.png)

Thanks a lot!

**Comment by Splaktar** [comment]
@lexcaraig this happens to me a lot. Running the command 2-4 times generally solves it for me. Then I am able to do `firebase deploy` just fine.

**Comment by lexcaraig** [comment]
@Splaktar seems to be working on me sometimes and when i run it again. It shows again the error. Can't find what's wrong.

**Comment by Splaktar** [comment]
It will hopefully go away with the magical webpack migration that should fix everything :)

**Comment by lexcaraig** [comment]
I hope so. Thanks @Splaktar  and Sorry for if it is related to this issue.

**Comment by Mihai-B** [comment]
I also have this problem... But no matter how many times I run the command, it just doesn't export all the files in vendor folder...

**Comment by tcozzens** [comment]
This item can be closed due to user error and the comments are not pertaining to the issue it was created for..
