### ISSUE TITLE
shelljs: Github security warning

### ISSUE THREAD

**Issue by ChristopherKiss** [angular/angular-cli#14945]
# 🐞 Bug report

### Command (mark with an `x`)
N/A

### Is this a regression?
N/A

### Description

I didn't see this reported yet, but Github is reporting a security issue for shelljs.

![image](https://user-images.githubusercontent.com/24984762/60391071-a70b2280-9b29-11e9-9e0e-ec626b876441.png)

Shelljs has a ticket open to address this
https://github.com/shelljs/shelljs/issues/945

* The Angular team should update shelljs once a fix is available.
* The Angular team should review the cli and the usage of shelljs to see if this vulnerability is actually something to cause concern for end users and advise appropriately until a fix is available.

## 🔬 Minimal Reproduction
N/A

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 10.16.0
OS: win32 x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
Running ls to find which package is using shelljs lead here

<pre><code>
npm ls shelljs
`-- @angular/compiler-cli@8.0.3
  `-- shelljs@0.8.3
</code></pre>

Commit that the security report links to: https://github.com/shelljs/shelljs/commit/7a9f8e5b7547132ea3f7e4fa47356a94d1156bb3

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular/issues/31236 and https://github.com/angular/angular/issues/29460
