### ISSUE TITLE
When I start 'ng serve', It dosen't work. Erro 'Cannot GET /'

### ISSUE THREAD

**Issue by tatsuya-takahashi** [angular/angular-cli#14949]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Sorry, I don't know.

### Description
I got an error when I set up Angular, create a new application, and ng serve. Nothing was done except the tutorial steps. I followed the steps of the tutorial in order.
https://angular.io/guide/setup-local
![image](https://user-images.githubusercontent.com/34804215/60417305-085eee80-9c1b-11e9-8eb4-f07826696f54.png)

## 🔬 Minimal Reproduction
import angular 8.0.3, and run ```ng new newapp```,and run ```cd newapp```, and run ```ng serve --open```

## 🔥 Exception or Error
<pre><code>
Refused to load the image 'http://localhost:4200/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

localhost/:1 Failed to load resource: the server responded with a status of 404 (Not Found)
</code></pre>

## 🌍 Your Environment

- PC
macOS Mojave
10.14.5

- Browswer
Google Chrome

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.6
Node: 12.4.0
OS: darwin x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**
Nothing.

**Comment by yusufbasol** [comment]
I have that same problem

**Comment by JossJoestar** [comment]
me too

**Comment by JossJoestar** [comment]
ng serve --aot --o

**Comment by xinthose** [comment]
Same issue.
