### ISSUE TITLE
Report which polyfills might be missing

### ISSUE THREAD

**Issue by zaiddabaeen** [angular/angular-cli#14954]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
It would be great if angular-cli can automatically warn the developer on build if a polyfill is missing which would cause trouble for some browsers.

Of course, a list of targetted browsers should be configured to look for functions that need polyfills for.

Why?

I just added `CustomEvent` to a component, and I hadn't known until I received a Sentry error from a user visiting the website using IE11 that `CustomEvent` does not exist natively.

### Describe the solution you'd like
During the build, check for functions that require polyfills according to the configure targetted browsers. Show a warning while building.

### Describe alternatives you've considered
Set up multi-browser testing.

**Comment by mgechev** [comment]
Hey @zaiddabaeen thanks for the suggestion. Detecting which browser APIs you're using at build time doesn't seem doable in the general case. Imagine the scenario:

```ts
window[localStorage.get('apiName')]
```

Depending on the value associated with the key `apiName`, the user may use a different global.

I still see value for this though. Maybe a lint check can help? Looking at `browserlist`, the imported polyfills, and keeping track which is the current API you use. In the same time it's not clear whether this belongs to the scope of the CLI or not.

**Comment by zaiddabaeen** [comment]
I agree that this could also be done in a lint check (like how PhpStorm alerts about unsupported Regex for different browsers), and probably would be a better choice than for CLI.

Regardless, seems that the issue hasn't been tackled by anyone yet...

Thank you @mgechev.
