### ISSUE TITLE
Angular CLI: 8.0.6

### ISSUE THREAD

**Issue by DanielFrugoni** [angular/angular-cli#14959]
Angular CLI: 8.0.6
Node: 10.13.0
OS: win32 x64
Angular: 8.0.3
... animations, compiler, compiler-cli, core

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cdk                      8.0.1
@angular/cli                      8.0.6
@angular/fire                     5.2.1
@angular/material                 8.0.1
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.5.2
webpack                           4.30.0

get this error, no matter what I try
ERROR in The Angular Compiler requires TypeScript >=3.4.0 and <3.5.0 but 3.5.2 was found instead.

**Comment by alan-agius4** [comment]
Hi, TypeScript 3.5 is not yet supported. Please use Typescript version 3.4
