### ISSUE TITLE
Sass documentation links are out-of-date

### ISSUE THREAD

**Issue by nex3** [angular/angular-cli#14975]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

The [documentation links](https://github.com/angular/angular-cli/blob/fa84505563861ba18fd1af203201b09669ccb677/packages/schematics/angular/ng-new/schema.json#L133-L134) for Sass are out-of-date. The documentation of the difference between the two syntaxes now lives at https://sass-lang.com/documentation/syntax.

## 🔬 Minimal Reproduction

Any invocation of `ng new` will reproduce this.

## 🌍 Your Environment

<pre><code>
Angular CLI: 8.1.0
Node: 12.0.0
OS: linux x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by alan-agius4** [comment]
Thanks @nex3, for bringing this up
