### ISSUE TITLE
--extract-css not working angular cli v1.7.4

### ISSUE THREAD

**Issue by smkrn110** [angular/angular-cli#14983]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [X] build
```

### Is this a regression?

 Have not checked, using angular-cli version 1.7.4:

### Description

 Have apply the flag tried following commands nothing works

`ng build --prod --extrac-css`
`ng build --prod --extrac-css=true`

Tried placing **custom.css** in styles array and also in style.css 
<pre><code>
      "styles": [
        "assets/css/custom.css",
        "../node_modules/videogular2/fonts/videogular.css",
        "styles.css"
      ],
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 1.7.4
Node: 8.10.0
OS: linux x64
Angular: 5.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

@angular/cli: 1.7.4
@angular/language-service: 4.4.7
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.4.2
webpack: 3.11.0

</code></pre>

**Comment by clydin** [comment]
Angular CLI version 1.7.4 is no longer supported.  Please consider upgrading to a more recent supported version.  The latest version is currently 8.1.0.
