### ISSUE TITLE
Importing ICSS modules into ts files does not work

### ISSUE THREAD

**Issue by despian** [angular/angular-cli#14988]
# 🐞 Bug report

### Command
```
- [x] build
- [x] serve
```

### Is this a regression?

I'm not sure. I've only tried with v8.

### Description

When attempting to import an [ICSS module](https://github.com/css-modules/icss) into a ts file the entire file is imported as a string rather than just the objects defined in the `:export` block.

The behaviour is also inconsistent, dependant on whether you're attempting to import from a component `.scss` file or the global `styles.scss`. Component scss files import as strings and the global style file imports as an empty object.

This seems to be something to do with the way the sass loader is configured by the cli since this works as expected in a normal webpack project.

## 🔬 Minimal Reproduction

The following repo contains an example of the issue:

https://github.com/despian/icss-import-test-angular

This repo contains an example of the expected behaviour:

https://github.com/despian/icss-import-test-webpack

## 🌍 Your Environment
<pre><code>Angular CLI: 8.0.6
Node: 10.16.0
OS: darwin x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by mgechev** [comment]
This looks more like a feature request. I don't recall having support for CSS imports in TypeScript files. @clydin and @alan-agius4 would be able to give more details.

**Comment by despian** [comment]
I did consider raising it as a feature request but the basic components used by the CLI do support this. Seems like it's something to do with the way they are configured that breaks support. But yeah, maybe it should be a feature request.

**Comment by alan-agius4** [comment]
Yeah, we don't support this feature yet.

**Comment by alan-agius4** [comment]
Hi @despian,

Thanks for this feature request, it doesn't' appear that there is a great push for this feature from the community and hence currently this doesn't fall in the CLI roadmap.

You can use third party builders such as https://github.com/manfredsteyer/ngx-build-plus which extend the Angular CLI to add this functionality. **NB:** by doing so, you will leave the supported path.
