### ISSUE TITLE
"module" schematic does not respect style setting for "component"

### ISSUE THREAD

**Issue by fmalcher** [angular/angular-cli#14986]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No, because this is about a newly introduced feature.

### Description

When generating a new module with lazy loading by
```
ng g m admin --route admin --module app
```

it will also generate a component within the new module.
However, **the style for this component is always `css`**, even if we have this setting in our `angular.json`:

```
"schematics": {
  "@schematics/angular:component": {
    "style": "scss"
  }
},
```

## 🔬 Minimal Reproduction

```
ng new my-app --style=scss --routing
ng g m admin --route admin --module app
```

Newly generated `AdminComponent` will have a `admin.component.css` instead of `scss`.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.0
Node: 10.15.1
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.0
@angular-devkit/core         8.1.0
@angular-devkit/schematics   8.1.0
@schematics/angular          8.1.0
@schematics/update           0.801.0
rxjs                         6.4.0

</code></pre>

**Comment by JosepAlacid** [comment]
Maybe I should open a new issue, but I think it could be a clue.
generating a component doesn't respect skipTests option on schematics...
