### ISSUE TITLE
404 (not found) for a custom service

### ISSUE THREAD

**Issue by iamisti** [angular/angular-cli#1499]
angular-cli: 1.0.0-beta.10
node: 6.2.1
os: darwin x64
OSX El Capitan

Fighting with the code for 5 hours now... couldn't figure out what I am doing wrong. Please help.

My service (demo/demo.ts):
<img width="955" alt="screen shot 2016-07-30 at 21 36 15" src="https://cloud.githubusercontent.com/assets/4672916/17272696/b5eed504-569d-11e6-88a3-d692906e076c.png">

demo/index.ts:
<img width="939" alt="screen shot 2016-07-30 at 21 38 06" src="https://cloud.githubusercontent.com/assets/4672916/17272709/ee31104e-569d-11e6-9032-2f18d7007cdc.png">

main.ts:
<img width="883" alt="screen shot 2016-07-30 at 21 37 11" src="https://cloud.githubusercontent.com/assets/4672916/17272703/d1a3cb7e-569d-11e6-8ab2-6c6608f4005d.png">

index.html:
<img width="1262" alt="screen shot 2016-07-30 at 21 38 59" src="https://cloud.githubusercontent.com/assets/4672916/17272714/13a17c60-569e-11e6-8b26-2abcfb957fbc.png">

result:
<img width="1205" alt="screen shot 2016-07-30 at 21 38 27" src="https://cloud.githubusercontent.com/assets/4672916/17272713/01da2194-569e-11e6-8593-e5cb38e47781.png">

**Comment by sirajc** [comment]
You should try https://gitter.im/angular/angular instead of raising an issue here. Anyways you should check `system-config.ts`. For further queries on this, I suggest gitter or stackoverflow
