### ISSUE TITLE
ng serve not detecting file changes with aot set to true

### ISSUE THREAD

**Issue by timlouw** [angular/angular-cli#14999]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes, after updating to 8.2.0-next.0

### Description
When you save changes they are not reflected in the browser after ng serve with aot enabled like instructed in the ivy guide. When you disable Aot changes get detected and things work as they should. You have to re-serve to see changes if you leave Aot enabled.

## 🔬 Minimal Reproduction
<pre><code>
angular.json
"build": { "options": { ... "aot": true, 

tsconfig.app.json: 
"angularCompilerOptions": {
    "enableIvy": true,
    "allowEmptyCodegenFiles": true
  },
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.0-rc.0
Node: 10.16.0
OS: 10 win32 x64
Angular: 8.2.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0-rc.0
@angular/cdk                      8.0.2
@angular/cli                      8.1.0-rc.0
@angular/fire                     5.2.0-rc.3
@angular/material                 8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0-rc.0
@schematics/update                0.801.0-rc.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by alan-agius4** [comment]
Let's continue tracking this in https://github.com/angular/angular/issues/31429

Thanks.
