### ISSUE TITLE
Proposal: rename

### ISSUE THREAD

**Issue by alexeagle** [angular/angular-cli#15]
angular-cli suggests a command-line interface. However, we intend this tool will also serve as the backend for IDE/editor frontends which create or update your angular project. This could cause some confusion, or vendors may hesitate to use it for that purpose.

I think we should either:
- pick a neutral name for this project, like 'angular-tool' or something better
- split this project into a thin CLI frontend, and a separate backend which can be reused by vendors

I prefer the latter as it's extra-explicit, but it might cause us more work/releases.

**Comment by alexeagle** [comment]
Happened to discuss with Brad, he agrees and also prefers the latter option

**Comment by PascalPrecht** [comment]
I also agree with the latter option. This is a pretty common pattern in the node world anyways. Having a library module that provides functionality and a dedicated cli module that uses the lib under the hood.

However, I still thing this thing should get a proper name then `angular-tool` sounds a bit too generic to me.

**Comment by cironunes** [comment]
+1 to the latter option.

IMHO `angular-cli` and `angular-backend` would be great names.

**Comment by alexeagle** [comment]
We tentatively decided on angular-toolkit and angular-cli ... Sound good?

**Comment by cironunes** [comment]
Yeah! Pretty good. :smile:

**Comment by PascalPrecht** [comment]
Love it.

**Comment by alexeagle** [comment]
I created the angular-toolkit project on github. Next step is to start some coding there and pull across the implementations, leaving a protocol in the middle for the angular-cli to call.

**Comment by hansl** [comment]
This requires more work and coordination. I'll close this for now, but @alexeagle would you like to meet to discuss this? I'm open to starting contribution to the toolkit after ng-conf (which is a deadline for the CLI).

**Comment by zackarychapple** [comment]
Love the semantic names.
