### ISSUE TITLE
angular schematics can't create .ts file

### ISSUE THREAD

**Issue by ChaoQunPeng** [angular/angular-cli#15001]
I created an Angular Schematics. There are two files in Files folder,fight.html and fight.ts  When I run schematics .: ng-add, terminal display create `fight.html` and `fight.ts`. And I publish it to npm.I'm on a new Angular Project run ng add packagename, the only `fight.html` are generated, no fight fight.ts

Native angular version

    Angular CLI: 8.0.6
    Node: 10.15.3
    OS: win32 x64
    Angular:
    ...
    
    Package                      Version
    ------------------------------------------------------
    @angular-devkit/architect    0.800.6
    @angular-devkit/core         8.0.6
    @angular-devkit/schematics   8.0.6
    @schematics/angular          8.0.6
    @schematics/update           0.800.6
    rxjs                         6.4.0

and [this][1] is my schematics stackblitz and my package name is `new-schematics`

  [1]: https://stackblitz.com/edit/angular-w8qoj7?file=src%2Fng-add%2Findex.ts

**Comment by clydin** [comment]
It appears that only the HTML file is present in the published package.
https://unpkg.com/new-schematics@0.0.5/src/ng-add/files/src/app/fight/
