### ISSUE TITLE
Error when building with AOT enabled when using Amplify

### ISSUE THREAD

**Issue by jeremyputeaux** [angular/angular-cli#15035]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I don't know, I never tried to build before.

### Description
I'm running a basic `ng build --prod` and I'm getting the following error:

## 🔬 Minimal Reproduction
https://github.com/jeremyputeaux/angular8-amplify-aot-build-problem
You just need: `npm i` and `ng build --prod`

## 🔥 Exception or Error
<pre><code>
chunk {0} runtime-es2015.703a23e48ad83c851e49.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.efedd750490b14de3f18.js (main) 128 bytes [initial] [rendered]
chunk {2} polyfills-es2015.66a9e684cc8ebe117187.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} styles.09e2c710755c8867a460.css (styles) 0 bytes [initial] [rendered]
Date: 2019-07-10T16:15:59.194Z - Hash: 4f715dd32629cbb02b90 - Time: 7999ms

ERROR in node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core.d.ts.ConfirmSignInComponentCore.html(7,55): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core.d.ts.ConfirmSignInComponentCore.html(16,11): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core.d.ts.ConfirmSignInComponentCore.html(46,42): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core.d.ts.ConfirmSignInComponentCore.html(5,81): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core.d.ts.ConfirmSignInComponentCore.html(27,16): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.core.d.ts.ConfirmSignInComponentCore.html(37,14): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(68,40): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(8,6): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(11,64): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(19,9): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(25,53): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(34,9): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(37,41): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(41,12): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(50,14): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.core.d.ts.ConfirmSignUpComponentCore.html(60,12): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(25,81): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(30,12): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(41,44): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(47,16): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(61,10): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(5,75): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(13,64): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(22,11): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.core.d.ts.SignInComponentCore.html(38,12): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.d.ts.SignUpComponentCore.html(11,46): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.d.ts.SignUpComponentCore.html(19,13): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.d.ts.SignUpComponentCore.html(40,44): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.d.ts.SignUpComponentCore.html(42,96): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.d.ts.SignUpComponentCore.html(59,42): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.d.ts.SignUpComponentCore.html(8,10): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.core.d.ts.SignUpComponentCore.html(51,12): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.core.d.ts.RequireNewPasswordComponentCore.html(40,38): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.core.d.ts.RequireNewPasswordComponentCore.html(5,84): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.core.d.ts.RequireNewPasswordComponentCore.html(9,55): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.core.d.ts.RequireNewPasswordComponentCore.html(17,7): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.core.d.ts.RequireNewPasswordComponentCore.html(26,10): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.core.d.ts.RequireNewPasswordComponentCore.html(32,10): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/greeting-component/greeting.component.core.d.ts.GreetingComponentCore.html(8,6): : Property 'amplifyService' is protected and only accessible within class 'GreetingComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(8,55): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(11,54): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(20,53): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(27,9): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(32,57): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(40,9): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(50,14): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(56,14): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(66,16): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(74,16): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(85,42): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.core.d.ts.ForgotPasswordComponentCore.html(5,81): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.core.d.ts.UsernameFieldComponentCore.html(4,61): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.core.d.ts.UsernameFieldComponentCore.html(9,13): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.core.d.ts.UsernameFieldComponentCore.html(20,64): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.core.d.ts.UsernameFieldComponentCore.html(26,13): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentCore' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.ionic.d.ts.ConfirmSignInComponentIonic.html(39,42): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.ionic.d.ts.ConfirmSignInComponentIonic.html(7,8): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.ionic.d.ts.ConfirmSignInComponentIonic.html(12,93): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-in-component/confirm-sign-in-component.ionic.d.ts.ConfirmSignInComponentIonic.html(31,10): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(80,42): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(11,8): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(16,93): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(28,94): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(49,12): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(53,40): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(59,12): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(63,40): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/confirm-sign-up-component/confirm-sign-up.component.ionic.d.ts.ConfirmSignUpComponentIonic.html(69,12): : Property 'amplifyService' is protected and only accessible within class 'ConfirmSignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(14,53): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(24,91): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(36,91): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(55,8): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(60,8): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(85,42): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(11,6): : Property 'amplifyService' is protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(63,40): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(65,59): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(69,40): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/forgot-password-component/forgot-password.component.ionic.d.ts.ForgotPasswordComponentIonic.html(75,12): : Property 'amplifyService' is
protected and only accessible within class 'ForgotPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/greeting-component/greeting.component.ionic.d.ts.GreetingComponentIonic.html(11,8): : Property 'amplifyService' is protected and only accessible within class 'GreetingComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.ionic.d.ts.SignInComponentIonic.html(39,72): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.ionic.d.ts.SignInComponentIonic.html(45,14): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.ionic.d.ts.SignInComponentIonic.html(50,110): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.ionic.d.ts.SignInComponentIonic.html(62,42): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.ionic.d.ts.SignInComponentIonic.html(8,73): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.ionic.d.ts.SignInComponentIonic.html(17,82): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-in-component/sign-in.component.ionic.d.ts.SignInComponentIonic.html(35,12): : Property 'amplifyService' is protected and only accessible within class 'SignInComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(15,10): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(26,11): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(56,72): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(62,14): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(72,42): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(8,73): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(47,10): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(50,42): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/sign-up-component/sign-up.component.ionic.d.ts.SignUpComponentIonic.html(52,96): : Property 'amplifyService' is protected and only accessible within class 'SignUpComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.ionic.d.ts.UsernameFieldComponentIonic.html(4,110): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.ionic.d.ts.UsernameFieldComponentIonic.html(9,13): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.ionic.d.ts.UsernameFieldComponentIonic.html(20,113): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/username-field-component/username-field.component.ionic.d.ts.UsernameFieldComponentIonic.html(25,13): : Property 'amplifyService' is protected and only accessible within class 'UsernameFieldComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(11,8): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(16,93): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentIonic' and its subclasses.
node_modules/aws-amplify-angular/dist/src/components/authenticator/require-new-password-component/require-new-password.component.ionic.d.ts.RequireNewPasswordComponentIonic.html(37,10): : Property 'amplifyService' is protected and only accessible within class 'RequireNewPasswordComponentIonic' and its subclasses.
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.0
Node: 10.15.3
OS: linux x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**
I'm using Window 10 and the WSL.

**Comment by clydin** [comment]
Those appear to be legitimate errors within `aws-amplify-angular`.  Properties accessed from a template are currently required to be public.

**Comment by gianlucainnocente** [comment]
Same error..

**Comment by jeremyputeaux** [comment]
We have found a solution. Look here: https://github.com/aws-amplify/amplify-js/issues/3620

**Comment by nward1234** [comment]
More specifically, the fix is here: https://github.com/aws-amplify/amplify-js/issues/3620#issuecomment-510548246

Disabling the 'fullTemplateTypeCheck' in tsconfig.json (or in tsconfig-aot.json or similar depending on your setup)
