### ISSUE TITLE
[bug]: copying from public/ dir

### ISSUE THREAD

**Issue by jkuri** [angular/angular-cli#1503]
When performing `ng build` or `ng serve` files are copied from `public/` dir into `dist/` but they don't preserve the directory structure as it is in `public/` directory.

**Comment by intellix** [comment]
Do you have an example of this as it works fine for me :)

**Comment by jkuri** [comment]
do you use master?

**Comment by filipesilva** [comment]
What part of the dir structure is not kept? Can you give a repro example?

**Comment by jkuri** [comment]
I have for example `public/fonts/foo.bar` and it gets copied to `dist/foo.bar`.

**Comment by filipesilva** [comment]
I see. Needs to be fixed then yeah.
