### ISSUE TITLE
Ionic ERROR in ./node_modules/@ionic/core

### ISSUE THREAD

**Issue by enderkey** [angular/angular-cli#15048]
I am migrating a project 4.0.0-beta.13 to 4.6.0
ionic serve:

`[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/loader.mjs 4:11-19
[ng] Can't import the named export 'a' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/loader.mjs 6:8-21
[ng] Can't import the named export 'b' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/loader.mjs 5:8-15
[ng] Can't import the named export 'g' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/index.mjs 3:0-202
[ng] Can't reexport the named export 'a' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/index.mjs 3:0-202
[ng] Can't reexport the named export 'b' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/index.mjs 3:0-202
[ng] Can't reexport the named export 'c' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/index.mjs 3:0-202
[ng] Can't reexport the named export 'l' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/index.mjs 3:0-202
[ng] Can't reexport the named export 'm' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/index.mjs 3:0-202
[ng] Can't reexport the named export 'p' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/index.mjs 3:0-202
[ng] Can't reexport the named export 't' from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/loader/index.mjs 21:0-47
[ng] Can't reexport the namespace object from non EcmaScript module (only default export is available)
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/polyfills/index.js 15:18
[ng] Module parse failed: Unexpected token (15:18)
[ng] You may need an appropriate loader to handle this file type.
[ng] | 
[ng] |   if (!win.customElements || (win.Element && (!win.Element.prototype.closest || !win.Element.prototype.matches || !win.Element.prototype.remove))) {
[ng] >     promises.push(import('./dom.js'));
[ng] |   }
[ng] | 
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/chunk-d83bfeae.js 172:37
[ng] Module parse failed: Unexpected token (172:37)
[ng] You may need an appropriate loader to handle this file type.
[ng] |                 baseEl.classList.remove('overlay-hidden');
[ng] |                 aniRoot = baseEl.shadowRoot || overlay.el;
[ng] >                 return [4 /*yield*/, import('./index-d9adb105.js').then(function (mod) { return mod.create(animationBuilder, aniRoot, opts); })];
[ng] |             case 1:
[ng] |                 animation = _a.sent();
[ng] ERROR in ./node_modules/@angular/fire/messaging/messaging.js 22:36
[ng] Module parse failed: Unexpected token (22:36)
[ng] You may need an appropriate loader to handle this file type.
[ng] |     function AngularFireMessaging(options, nameOrConfig, platformId, zone) {
[ng] |         var _this = this;
[ng] >         var requireMessaging = from(import('firebase/messaging'));
[ng] |         this.messaging = requireMessaging.pipe(map(function () { return _firebaseAppFactory(options, nameOrConfig); }), map(function (app) { return app.messaging(); }), runOutsideAngular(zone));
[ng] |         if (!isPlatformServer(platformId)) {
[ng] ERROR in ./node_modules/@ionic/core/dist/esm/legacy/chunk-09ec7fc0.js 61:11
[ng] Module parse failed: Unexpected token (61:11)
[ng] You may need an appropriate loader to handle this file type.
[ng] |         return module[exportName];
[ng] |     }
[ng] >     return import(
[ng] |     /* webpackInclude: /\.entry\.js$/ */
[ng] |     /* webpackExclude: /\.system\.entry\.js$/ */
[ng] ℹ ｢wdm｣: Failed to compile.

`

ionic info: 
`SubprocessError: Command error.`

package.json:
```
{
  "name": "myProject",
  "version": "0.2.2",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.14",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "~7.2.14",
    "@angular/core": "~7.2.14",
    "@angular/fire": "^5.1.3",
    "@angular/forms": "~7.2.14",
    "@angular/http": "~7.2.14",
    "@angular/material": "^7.3.7",
    "@angular/material-moment-adapter": "^7.3.7",
    "@angular/platform-browser": "~7.2.14",
    "@angular/platform-browser-dynamic": "~7.2.14",
    "@angular/pwa": "^0.13.8",
    "@angular/router": "~7.2.14",
    "@angular/service-worker": "~7.2.14",
    "@ionic-native/clipboard": "^5.5.1",
    "@ionic-native/core": "5.5.1",
    "@ionic-native/in-app-browser": "^5.5.1",
    "@ionic-native/splash-screen": "5.5.1",
    "@ionic-native/status-bar": "5.5.1",
    "@ionic/angular": "^4.6.2",
    "@ionic/angular-toolkit": "^2.0.0",
    "@ionic/storage": "^2.2.0",
    "@ng-select/ng-select": "^2.19.0",
    "@webcomponents/custom-elements": "^1.2.4",
    "angular-clipboard": "^1.7.0",
    "cordova-clipboard": "1.2.1",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "core-js": "^2.5.7",
    "document-register-element": "^1.13.2",
    "firebase": "^5.11.1",
    "ionic": "^4.6.0",
    "moment": "^2.24.0",
    "ngx-toastr": "^10.0.2",
    "pdfjs-dist": "^2.0.943",
    "plotly.js": "^1.47.4",
    "rxjs": "6.5.1",
    "uuid4": "^1.1.4",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.13.8",
    "@angular-devkit/build-angular": "~0.13.8",
    "@angular-devkit/core": "~7.3.8",
    "@angular-devkit/schematics": "~7.3.8",
    "@angular/cli": "^7.3.8",
    "@angular/compiler": "~7.2.14",
    "@angular/compiler-cli": "~7.2.14",
    "@angular/language-service": "~7.2.14",
    "@ionic/ng-toolkit": "^1.1.0",
    "@ionic/schematics-angular": "^1.0.7",
    "@types/jasmine": "~3.3.12",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "^12.0.0",
    "codelyzer": "~5.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "node-sass": "^4.12.0",
    "protractor": "~5.4.2",
    "ts-node": "~8.1.0",
    "tslint": "~5.16.0",
    "typescript": "~3.1.1"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-clipboard": {},
      "cordova-plugin-inappbrowser": {}
    }
  }
}
```

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
