### ISSUE TITLE
CLI Crash

### ISSUE THREAD

**Issue by santhoshnv** [angular/angular-cli#15047]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Angular cli runs the project for first to times and it compiled successfully. The third time it throws the followning error code in the terminal. `Assertion `!(n > 0) || (ret != nullptr)' failed.` Not able to continue the compilation process. It happened multiple times.

## 🔥 Exception or Error
<pre>Assertion `!(n > 0) || (ret != nullptr)' failed.<code>

</code></pre>

**Comment by elvisbegovic** [comment]
@santhoshnv Hi, can you please fill the issue template to get help https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#submit-issue

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
