### ISSUE TITLE
Feature request: format compile errors by files in src

### ISSUE THREAD

**Issue by matt-erhart** [angular/angular-cli#1504]
When I get a compile error, I typically want to know where the error is in files in src, not the cascade into the libraries. Novices sometimes don't even know there is useful information in the 'ng serve/build' terminal. I think errors could be understood a lot easier if the errors were formatted something like this: 
ng build ->
Typical Error Message: 
...business as usual...

Compile Errors from src files: 
[file_name] [line number] [error message]

I think this would help everyone search out the most useful parts of the message, and help novices discover important information.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1455 made these better, since we use the webpack report format.
