### ISSUE TITLE
ng build --prod fails with Terser error "undefined"

### ISSUE THREAD

**Issue by juliancarrivick** [angular/angular-cli#15057]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I don't know.

### Description
I have been migrating one of our legacy projects from AngularJS to to Angular 8 and hit this issue when building it with a prod build for the first time. It took me a while but I managed to isolate the issue to a single file and then reduce the code which was causing the issue down to the (rather contrived) example below. When compiling the below code with `tsc` and then running it through `terser` the issue did not manifest itself so I can only assume it is either to do with the config AngularCLI uses or with AngularCLI itself.

This isn't a blocker for me as I was able to refactor the code as to not trigger the bug (by replacing the `forEach` with a `map`) but I thought I would submit a bug report in case other people have hit it!

This may be related to #13096 but I do have a reliable repro :) I also am happy if someone might be able to point me in the right direction to reproduce this directly with Terser as I was unable to get it to occur in that case.

## 🔬 Minimal Reproduction
- Create a new application using `ng new`
- Replace the code in `main.ts` with
```
getDecimalGreaterThanHalfRecurse(Math.random());

function getDecimalGreaterThanHalfRecurse(num: number) {
  if (num > 0.5) {
    return num;
  }

  return getDecimalGreaterThanHalf();

  function getDecimalGreaterThanHalf() {
    const childTaskFetchPromises: number[] = [];

    [Math.random()].forEach(makeSureNumberIsHalf);

    return childTaskFetchPromises[0];

    function makeSureNumberIsHalf(numToTry: number) {
      childTaskFetchPromises.push(getDecimalGreaterThanHalfRecurse(numToTry));
    }
  }
}
```
- Run `ng build --prod`

## 🔥 Exception or Error
<pre><code>

chunk {0} runtime-es2015.703a23e48ad83c851e49.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main-es2015.b4bb597dd4b4ece15307.js (main) 789 bytes [initial] [rendered]
chunk {2} polyfills-es2015.5581eb5ca3860a631b8d.js (polyfills) 36.4 kB [initial] [rendered]
chunk {3} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]
Date: 2019-07-12T07:51:43.614Z - Hash: 7ad404b9e683381489f4 - Time: 4844ms

WARNING in Lazy routes discovery is not enabled. Because there is neither an entryModule nor a statically analyzable bootstrap code in the main file.

ERROR in main-es2015.b4bb597dd4b4ece15307.js from Terser
undefined
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.1
Node: 10.15.3
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**
A couple of things I noticed:
- If you remove the initial call to the function the build works. Probably because of the tree shaker removing that code
- If you remove the what seems to be useless function call to `getDecimalGreaterThanHalf()`
 the build works
- If you replace the `forEach` with a `map` (which is the same functionally) then the build works. i.e. replace the body of `getDecimalGreaterThanHalf` with
```
return [Math.random()].map(makeSureNumberIsHalf);

    function makeSureNumberIsHalf(numToTry: number) {
      return getDecimalGreaterThanHalfRecurse(numToTry);
    }
```

**Comment by alan-agius4** [comment]
Hi, I just took a look at this and it seems that it's an issue with terser. Let me explain what I did.

I tried this using the online minifier (https://xem.github.io/terser-online/). The online version fails with a different error though. 

So, what is happening is that when compiled and bundled the output code is wrapped in a function similar to the below:

```js
(function () {
  getDecimalGreaterThanHalfRecurse(Math.random());

  function getDecimalGreaterThanHalfRecurse(num) {
    if (num > 0.5) {
      return num;
    }
    return getDecimalGreaterThanHalf();
    function getDecimalGreaterThanHalf() {
      const childTaskFetchPromises = [];
      [Math.random()].forEach(makeSureNumberIsHalf);
      return childTaskFetchPromises[0];
      function makeSureNumberIsHalf(numToTry) {
        childTaskFetchPromises.push(getDecimalGreaterThanHalfRecurse(numToTry));
      }
    }
  }
})();
```

I grabbed the above code, and pasted it in the online minifier https://xem.github.io/terser-online/, and I got `RangeError: Maximum call stack size exceeded`. 

![image](https://user-images.githubusercontent.com/17563226/61122363-eb8bac00-a4a1-11e9-95ac-4713a4d7f4b7.png)


What I noticed was that the function call was being made prior to the function declaration which gave me an idea to swap the statements. Ie: 

```js
(function () {
  function getDecimalGreaterThanHalfRecurse(num) {
    if (num > 0.5) {
      return num;
    }
    return getDecimalGreaterThanHalf();
    function getDecimalGreaterThanHalf() {
      const childTaskFetchPromises = [];
      [Math.random()].forEach(makeSureNumberIsHalf);
      return childTaskFetchPromises[0];
      function makeSureNumberIsHalf(numToTry) {
        childTaskFetchPromises.push(getDecimalGreaterThanHalfRecurse(numToTry));
      }
    }
  }

  getDecimalGreaterThanHalfRecurse(Math.random());
})();
```

And this produced the JS minified without an error
![image](https://user-images.githubusercontent.com/17563226/61122341-d9117280-a4a1-11e9-8862-425d7079544e.png)

I suggest you fill an an issue with Terser with the above info. Thank you.

**Comment by juliancarrivick** [comment]
Thank you very much for taking the time to do that detective work 🕵 
I will take this information to the Terser team :)

**Comment by JohnGalt1717** [comment]
@juliancarrivick have you got a bug # from Terser? I'm having the same issues with angular 8 all of a sudden.

**Comment by juliancarrivick** [comment]
@JohnGalt1717 Yep, I logged it under terser-js/terser#406
