### ISSUE TITLE
Wrong file exported from index in shared folder

### ISSUE THREAD

**Issue by ritz078** [angular/angular-cli#1505]
1. OS : Mac OS El Capitan

2. v1.0.0-beta.10

3. Repro steps. 

* Go inside shared folder
* Run `ng g pipe helloWorld`
* File created will be `hello-world.pipe.ts` but the file exported from `index.ts` will be `helloWorld.pipe`

**Comment by sirajc** [comment]
Duplicate of #1434

**Comment by ritz078** [comment]
sorry. closing this.
