### ISSUE TITLE
Loading chunk failed

### ISSUE THREAD

**Issue by nileshindexnine** [angular/angular-cli#15060]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular-cli/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by nileshindexnine** [comment]
Loading chunk failed after login in IE browser
Uncaught (in promise): Error: Loading chunk crop-monitoring-crop-monitoring-module failed. (missing: http://localhost:4200/crop-monitoring-crop-monitoring-module.js) Error: Loading chunk crop-monitoring-crop-monitoring-module failed. (missing: http://localhost:4200/crop-monitoring-crop-monitoring-module.js)at Anonymous function (http://localhost:4200/vendor.js:138755:13)at CatchSubscriber.prototype.error (http://localhost:4200/vendor.js:178710:13)at Subscriber.prototype._error (http://localhost:4200/vendor.js:175449:5)at Subscriber.prototype.error (http://localhost:4200/vendor.js:175429:9)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
