### ISSUE TITLE
v8.1.1 ES5 compiles fail

### ISSUE THREAD

**Issue by choosemath** [angular/angular-cli#15075]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 No, I don't think so...this goes along with rxjs upgrade.

### Description

 ES5 builds fail because of how those files import from rxjs 6.5.2

## 🔬 Minimal Reproduction
Created a new project, included rxjs 6.5.2.

## 🔥 Exception or Error
<pre><code>

ERROR in /@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '\@angular\core\@angular'
ERROR in /@angular/http/@angular/http.es5.js
Module not found: Error: Can't resolve 'rxjs/Observable' in '\@angular\http\@angular'
ERROR in /@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/Subject' in '\@angular\core\@angular'
ERROR in /@angular/forms/@angular/forms.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/forkJoin' in '\@angular\forms\@angular'
ERROR in /@angular/forms/@angular/forms.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/fromPromise' in '\@angular\forms\@angular'
ERROR in /@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/observable/merge' in '\@angular\core\@angular'
ERROR in /@angular/forms/@angular/forms.es5.js
Module not found: Error: Can't resolve 'rxjs/operator/map' in '\@angular\forms\@angular'
ERROR in /@angular/core/@angular/core.es5.js
Module not found: Error: Can't resolve 'rxjs/operator/share' in '\@angular\core\@angular'
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.1.1
Node: 10.16.0
OS: win32 x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.1
@angular/cdk                      8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
