### ISSUE TITLE
localhost:4200 not found and Not start ng serve

### ISSUE THREAD

**Issue by rushhit93** [angular/angular-cli#15080]
npm install -g @angular/cli
ng new my-dream-app
cd my-dream-app
ng serve

NOT WORKING

An unhandled exception occurred: argument fn must be a function
See "C:\Users...." for further details.

And http://localhost:4200 not found .

How can i solve ?

**Comment by elvisbegovic** [comment]
@rushhit93 
Hello there, I tried and can't repro. Can you please edit your issue and follow template issue (you can read more about this here https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#submit-issue) because you give minimal info it's hard to consider your environnement

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
