### ISSUE TITLE
Issue in angular7 project

### ISSUE THREAD

**Issue by gurusaini** [angular/angular-cli#15091]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I installed node, angular CLI in C drive. Now I created angular7 project in D drive but project is not loading, it is showing the attached screen... Please suggest do I need to change something in project json file or something else...

![angularIssue](https://user-images.githubusercontent.com/4884820/61277558-0cb90900-a7d0-11e9-9f3c-39c4b7cb99aa.png)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by ruimarques** [comment]
Did you run `npm install` inside the project folder?

**Comment by gurusaini** [comment]
> Did you run `npm install` inside the project folder?

No, I did not

**Comment by gurusaini** [comment]
> Did you run `npm install` inside the project folder?

Thank you Ruimarques...I installed npm inside the project folder. Now its working fine.
