### ISSUE TITLE
mime types are not set with version 8

### ISSUE THREAD

**Issue by fareshan** [angular/angular-cli#15094]
#14468 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I had this issue after upgrading from angular 7 to 8

### Description
In previous version, the generated JS files were indexed in index.html like this:
```
<script type="text/javascript" src="runtime.xxx.js"></script>
```
Now, I am getting it without the mime-types:
```
<script src="runtime.xxx.js"></script>
```

And this is giving this error in the browser:
MIME type ('text/html') is not executable, and strict MIME type checking is enabled

## 🔬 Minimal Reproduction
ng build --prod

## 🔥 Exception or Error
<pre><code>
MIME type ('text/html') is not executable, and strict MIME type checking is enabled
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.1
Node: 10.16.0
OS: darwin x64
Angular: 8.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/http                     7.2.15
@angular/pwa                      0.801.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by mgechev** [comment]
@fareshan this looks related to differential loading and `script[type=module]` that we produce. If your server does not set the correct content-type then your scripts won't be executed by the browser.

Since this is an issue on the server-side, I'd close the bug. Feel free to open a new one if your problem does not get resolved when you update your server config.

**Comment by Ks89** [comment]
@mgechev I'm having exactly the same issue with fonts using express 4 + express.static on server side.

Should I open an issue to express developers about this topic?

thanks

**Comment by Ks89** [comment]
@mgechev 

I forgot to say that I'm including fonts in this way in my SCSS file:

```
@font-face {
  font-family: 'Roboto-Regular';
  font-style: normal;
  font-weight: normal;
  src: local('Roboto'), local('Roboto-Regular'),
       url('/assets/fonts/roboto/Roboto-Regular.ttf') format('truetype');
}
```

I cannot add fonts from external websites, because my webapp should run locally also without internet connection.
Is the same issue or is it something different? If different, should I open another issue?

My environment is:

```
Angular CLI: 8.1.2
Node: 10.16.0
OS: darwin x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.1
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
```

thanks.
