### ISSUE TITLE
"start_url" in manifest file is not updated by a build with --baseHref

### ISSUE THREAD

**Issue by pacoita** [angular/angular-cli#15092]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description

I have a brand new Angular project where I added PWA features via the add schematic `ng add angular/pwa`. In the web manifest file the "start_url" property is set to "/" by default.

If I run a PROD build changing the baseHref (`ng build --prod --baseHref "/myDemo/"`), the asset URLs in the `ngsw.json` file are correctly update, but not the "start_url" property in the manifest file. It must be updated manually. 

## 🔬 Minimal Reproduction

1. Create a new Angular app: `ng new myDemo`
2. Add PWA features: `ng add @angular/pwa`
3. Make a prod build using baseHref option: `ng build --prod --baseHref "/myDemo/"`

## 🔥 Exception or Error

The `manifest.webmanifest` file is copied in the dist folder, but its start_url property does not reflect the value used for the baseHref option.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.1
Node: 12.3.1
OS: darwin x64
Angular: 8.2.0-next.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@angular/cli                      8.1.1
@angular/pwa                      0.801.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Comment by hknoerrer** [comment]
Hi,
i don't use angular/pwa but had the same problem.
Removing the scope attribute (it will be calculated based on start_url) 
and adding the baseHref value in front of my start_url (index.html -> /subdir/index.html) works for me.
But finally i found:
https://stackoverflow.com/questions/57993086/angular-pwa-in-iis-subfolder-not-work-offline/59393706#59393706
and set the attributes to
"scope": ".",
"start_url": "./index.html",
At the moment i don't see any negative side effects.
But this way i'm able to add same app with different base directories to home screen without modifing the build process.

**Comment by cyrilletuzi** [comment]
PR: #17075
