### ISSUE TITLE
:host CSS selector not working on live reload when Ivy enabled

### ISSUE THREAD

**Issue by kaplan81** [angular/angular-cli#15101]
# 🐞 Bug report

### Command
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: when Ivy is not enabled it works as expected.

### Description

I have a shared component in my app that has this kind of template:
```typescript
<div class="wrapper">
  <ng-content></ng-content>
</div>
```

A couple of routed components are using that shared component in a normal way:
```html
<shared-component input="myInput">HTML content here!</shared-component>
```

All components (the shared one and the entry ones) are using `changeDetection: ChangeDetectionStrategy.OnPush`.

The routed components have an extra meta property: `host: { class: 'routed-content' }`.

And also all of them are styling the element that hosts their corresponding component by using the `:host` pseudo-class in the `*.scss` file.

Now, the problem is that when you run `npm start` (**`ng serve`**) it loads all the styles property on the first load but we perform any changes either in the HTML template or in the Sass filed the live reloading is not rendering the app correctly. All styles applied to the host are missing.

## 🔬 Minimal Reproduction

Simply create an Ivy enabled app with a SharedModule imported in the AppModule and set the components as described above.

Then check the missing styles on the reloads.

## 🌍 Your Environment
```bash
Angular CLI: 8.1.1
Node: 10.15.3
OS: darwin x64
Angular: 8.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.1
@angular-devkit/build-angular     0.801.1
@angular-devkit/build-optimizer   0.801.1
@angular-devkit/build-webpack     0.801.1
@angular-devkit/core              8.1.1
@angular-devkit/schematics        8.1.1
@ngtools/webpack                  8.1.1
@schematics/angular               8.1.1
@schematics/update                0.801.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
```

**Comment by alan-agius4** [comment]
I tried this locally and it seems to work.

First load
![image](https://user-images.githubusercontent.com/17563226/61437445-60953080-a93d-11e9-8b21-1a8f8c997b6b.png)


Second load on changing the color
![image](https://user-images.githubusercontent.com/17563226/61437494-84f10d00-a93d-11e9-8f7e-a25540539959.png)

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
