### ISSUE TITLE
Remove the "-target" suffix from the output dist directory

### ISSUE THREAD

**Issue by ChristianCRM** [angular/angular-cli#15104]
I have the requirement to remove the "dash" from the filename of the dist files. The reason is that the system where the app needs to be deployed does not accept "dashes" (very sad, I know), but there is no way around it unfortunately.
Can this be done? I remember older version of angular did not add the -target to the filename and that's where I'm trying to get to.
In Summary:
Instead of having a dist folder with files in the format: main-es2015.js, etc. I would like to have the files named main.js, etc...

Thank you

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
