### ISSUE TITLE
Generate module command adds route path to wrong line

### ISSUE THREAD

**Issue by mehmet-erim** [angular/angular-cli#15117]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Description
`ng generate module ranking --route ranking --module app.module` command is working very well. But if there is a data property to routes in `app-routing.module`. The command add route path to wrong line.

## 🔬 Minimal Reproduction
`ng new example-app --routing`
`ng generate module ranking --route ranking --module app.module`

Add data property to ranking route, then my app-routing.module.ts like below
```ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [
  {
    path: 'ranking',
    loadChildren: () => import('./ranking/ranking.module').then(m => m.RankingModule),
    data: { path: 'test', name: 'Test' },
  },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule],
})
export class AppRoutingModule {}
```

After, run the following command
`ng generate module home --route home --module app.module`

It adds my home route path to the wrong line like below:
```ts
const routes: Routes = [
  {
    path: 'ranking',
    loadChildren: () => import('./ranking/ranking.module').then(m => m.RankingModule),
    data: { path: 'test', name: 'Test' },
    { path: 'home', loadChildren: () => import('./home/home.module').then(m => m.HomeModule) },
  },
];
```

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by mehmet-erim** [comment]
> Can you please provide the output of `ng version`?

Sure,

Angular CLI: 8.1.2
Node: 10.16.0
OS: darwin x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
