### ISSUE TITLE
Change in scss file does trigger recompilation but not reloading

### ISSUE THREAD

**Issue by Alber70g** [angular/angular-cli#1511]
1. OS?  
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

- create new project `ng new sassy-project --style=sass`
- run `ng serve`
- make changes in `app.component.scss`
Expected: reloading page
Actual: not reloading page :smirk:

4. The log given by the failure. Normally this include a stack trace and some
   more information.

No log

5. Mention any other details that might be useful.

![image](https://cloud.githubusercontent.com/assets/516972/17301934/edf3bf14-5819-11e6-9305-531f2035d49b.png)

![image](https://cloud.githubusercontent.com/assets/516972/17301936/efde7940-5819-11e6-99b7-ab91d836a5f1.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sirajc** [comment]
This looks obsolete as coming version of cli will use webpack instead of brocolli, Let us know if this is still reproducible in master

**Comment by Alber70g** [comment]
It is working on `master`. I have another issue with sass but I'll post that in a new issue report.
