### ISSUE TITLE
Getting error while importing js file from assets folder and using in angular component Angular 8.1.2

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular-cli#15118]
I have a external .js file which i downloaded and placed into my assets folder.
After following steps from [here](https://angular.io/guide/using-libraries), still no success.

Steps performed to add js file in angular project;

Adding relative path of js file to script [] in angular.json

Creating typyings.d.ts under src folder
declare var myJs: any;

Import in component
import * as myJs from 'myJs'

Getting error: Cannot find module 'g3'.

![image](https://user-images.githubusercontent.com/4208015/61472146-7d634f80-a9a1-11e9-96d2-c157a5e88ddc.png)

Stakcblitz url: https://stackblitz.com/edit/github-vlhyn3
Github repo: https://github.com/narendrasinghrathore/angular-lollipop-chart

Regards

```
"dependencies": {
    "@angular/animations": "~8.1.2",
    "@angular/common": "~8.1.2",
    "@angular/compiler": "~8.1.2",
    "@angular/core": "~8.1.2",
    "@angular/forms": "~8.1.2",
    "@angular/platform-browser": "~8.1.2",
    "@angular/platform-browser-dynamic": "~8.1.2",
    "@angular/router": "~8.1.2",
    "d3": "^5.9.7",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.2",
    "@angular/cli": "~8.1.2",
    "@angular/compiler-cli": "~8.1.2",
    "@angular/language-service": "~8.1.2",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
```

@alan-agius4

**Comment by alan-agius4** [comment]
Hi, I tried to take a look at your reproduction, however your reproduction doesn't show the above mentioned error, but rather it show a different build error.

Kindly update the reproduction to showcase the error mentioned above thanks.

**Comment by narendrasinghrathore** [comment]
@alan-agius4  It's because of unsuccessful import.
I have updated with image above.

I have try this steps to import js library from https://angular.io/guide/using-libraries

You can share any reference link that help to import js file.
@alan-agius4 

Let me know if more clarification needed.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

That said please see: https://angular.io/guide/using-libraries#defining-typings-for-runtime-global-libraries

**Comment by narendrasinghrathore** [comment]
### **Steps to add external js file that is not download using npm:**

1. Add to folder under your app structure , i prefer to create a js folder under src and place all downloaded .js files there.
2. Open angular.json and add relative path to scripts: ["src/js/your-files-name.js'']
3. Create if not exist,  a typings.d.ts under src folder and add 

> declare var libraryName: any;

4. Don't try to import in component, just use the name declare in typyings.d.ts

Reference: https://angular.io/guide/using-libraries#defining-typings-for-runtime-global-libraries

Regards
