### ISSUE TITLE
synchronize the content of the static hosted website in S3 and the frontend url (aws_content_delivery_url)

### ISSUE THREAD

**Issue by alshazly** [angular/angular-cli#15133]
I'm beginner in angular and aws services. How can I synchronize the content of the static hosted website S3 and the frontend url (aws_content_delivery_url)?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
