### ISSUE TITLE
Passing in data into directives and other inputs present on the directive element

### ISSUE THREAD

**Issue by marwan38** [angular/angular-cli#15136]
# 🐞 Bug report

### Description

Passing in data into directives, or other inputs put on the element which has the directive on it, does not pass through the data.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-neetvx

Console logs out undefined inside the constructor of `d.directive.ts`.

## 🌍 Your Environment
<pre><code>
8.1.0 & 8.1.2
</code></pre>

### **EDIT**: Works fine when running ngOnInit rather then the constructor. I will keep this open in case this is an actual bug.

**Comment by alan-agius4** [comment]
This is actually expected. Input values are not available in the `constructor`.

See lifecycle-hooks documentation for more details https://angular.io/guide/lifecycle-hooks
