### ISSUE TITLE
Invalid rule result: Instance of class Promise on 'ng generate component'

### ISSUE THREAD

**Issue by meyy91** [angular/angular-cli#15131]
While i am creating a new component in angular cli i get the above error as **Invalid rule result: Instance of class Promise**.

Tried deleting the node_modules and installing the dependencies again. Kindly help me on this.

My package.json is as follows:

{
  "name": "client-app",
  "version": "0.0.1-3",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "^7.2.15",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@fortawesome/fontawesome-free": "^5.8.1",
    "@material-extended/mde": "^2.1.1",
    "@ng-bootstrap/ng-bootstrap": "^4.1.1",
    "@types/arcgis-js-api": "^4.11.0",
    "@types/underscore": "^1.8.14",
    "angular-resizable-element": "^3.2.4",
    "angular-user-idle": "^2.1.2",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "devextreme": "^18.2.7",
    "devextreme-angular": "^18.2.7",
    "esri-loader": "^2.9.2",
    "jszip": "^3.2.1",
    "ngx-perfect-scrollbar": "^7.2.1",
    "ngx-spinner": "^7.1.4",
    "ngx-tour-core": "^4.0.1",
    "ngx-tour-md-menu": "^4.0.1",
    "rxjs": "^6.3.3",
    "tslib": "^1.9.0",
    "underscore": "^1.9.1",
    "webpack-bundle-analyzer": "^3.3.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/animations": "^7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/cli": "~7.3.6",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/language-service": "~7.2.0",
    "@angular/material": "^7.3.7",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}

**Comment by mgechev** [comment]
After looking at StackOverflow, I found [this](https://stackoverflow.com/questions/56647865/invalid-rule-result-instance-of-class-promise) answer. Seems like a mismatched schematics version. Would you try the answer and let us know if everything works?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
