### ISSUE TITLE
Webpack: 3rd Party module not found, but functional

### ISSUE THREAD

**Issue by j3ddesign** [angular/angular-cli#1513]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
local (v1.0.0-beta.10, branch: master)

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

- App created with webpack cli built from master.
- Ran `npm install lodash --save`,
-  imported lodash into my component with `import * as _ from 'lodash';`
- proceeded to use lodash functions (_.forIn() in this case)

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`Cannot find module 'lodash' .`

5. Mention any other details that might be useful.
I haven't noticed this with other libs I'm using, including material2 and ngrx/store.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zackarychapple** [comment]
I had better luck with `"@types/lodash": "^4.0.26-alpha"`  and using the same import.

**Comment by j3ddesign** [comment]
Ok so installing `@types/lodash` as well resolved the issue - though If possible a better error message would be nice here.

Something like `Couldn't find types for module 'lodash'`

**Comment by elpddev** [comment]
Same here. I created a custom type  definition for a 3rd party library and then the error was gone. The error message is not clear.
