### ISSUE TITLE
"EMFILE: too many open files" error when ng build --prod with 10000 files in assets

### ISSUE THREAD

**Issue by talebi** [angular/angular-cli#15137]
I have over 10000 files in my assets folder and when I do 'ng build --prod' I get the above error. here's the build log:
>ng build --prod --verbose
>Your global Angular CLI version (7.3.7) is greater than your local
version (7.1.3). The local Angular CLI version is used.

>To disable this warning use "ng config -g cli.warnings.versionMismatch false".
 >10% building modules 3/14 modules 11 active ...m-flags\dist\sprite\famfamfam-flags.cssBrowserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
>40488ms building modules
35ms finish module graph
4ms sealing
1ms basic dependencies optimization
1ms dependencies optimization
0ms advanced dependencies optimization
84ms after dependencies optimization
1ms optimizing
1ms basic module optimization
29ms module optimization
2ms advanced module optimization
1ms after module optimization
66ms basic chunk optimization
1ms chunk optimization
24ms advanced chunk optimization
1ms after chunk optimization
2ms module and chunk tree optimization
0ms after module and chunk tree optimization
1ms basic chunk modules optimization
1ms chunk modules optimization
0ms advanced chunk modules optimization
1ms after chunk modules optimization
1ms module reviving
2ms module order optimization
0ms advanced module order optimization
12ms before module ids
2ms module ids
22ms module id optimization
2ms chunk reviving
4ms chunk order optimization
2ms before chunk ids
1ms chunk id optimization
25ms after chunk id optimization
2ms record modules
6ms record chunks
134ms hashing
1ms after hashing
1ms record hash
1ms module assets processing
194ms chunk assets processing
8ms additional chunk assets processing
1ms recording
13ms additional asset processing
528ms chunk asset optimization
1ms after chunk asset optimization
1ms asset optimization
1ms after asset optimization
2ms after seal
 95% emitting index-html-webpack-pluginEMFILE: too many open files, open 'C:\dev\.....

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

Does this also happen with Angular CLI version 8?

**Comment by talebi** [comment]
>ng version
>Your global Angular CLI version (7.3.7) is greater than your local
>version (7.1.3). The local Angular CLI version is used.

>To disable this warning use "ng config -g cli.warnings.versionMismatch false".

>Angular CLI: 7.1.3
>Node: 10.16.0
>OS: win32 x64
>Angular: 7.1.3
>... cli, common, compiler, compiler-cli, core, forms, http
>... platform-browser, platform-browser-dynamic, router

>Package                           Version
>-----------------------------------------------------------
>@angular-devkit/architect         0.11.3
>@angular-devkit/build-angular     0.11.3
>@angular-devkit/build-optimizer   0.11.3
>@angular-devkit/build-webpack     0.11.3
>@angular-devkit/core              7.1.3
>@angular-devkit/schematics        7.1.3
>@angular/animations               7.1.4
>@angular/cdk                      7.2.0
>@angular/material                 7.2.0
>@ngtools/webpack                  7.1.3
>@schematics/angular               7.1.3
>@schematics/update                0.11.3
>rxjs                              6.2.1
>typescript                        3.1.6
>webpack                           4.23.1

I haven't tested with cli v8 yet

**Comment by alan-agius4** [comment]
Hi, I tried to replicate this with 15,000 files and I didn't hit any errors.

Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
