### ISSUE TITLE
angular8  templateUrl  how to use! 

### ISSUE THREAD

**Issue by savethegreen7** [angular/angular-cli#15149]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [v] build
- [v] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

**In case of raw-loader (> 1.0.0), you need to use require ('url') .default when using angular8 templateUrl because it is exported as default.**

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
At the moment, we require raw-loader 1.x.x.
