### ISSUE TITLE
@angular-devkit/build-angular 0.802.0-next.1 throws ERROR NullInjectorError: StaticInjectorError

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#15145]
# 🐞 Bug report

### Command
- [x] build

### Is this a regression?
It was working fine in `"@angular-devkit/build-angular": "0.802.0-next.0",` and is broken in `"@angular-devkit/build-angular": "0.802.0-next.1",`.

 Yes, the previous version in which this bug was not present was: 
`"@angular-devkit/build-angular": "0.802.0-next.0"`

### Description
After upgrading my application from `"@angular-devkit/build-angular": "0.802.0-next.0",` to `"@angular-devkit/build-angular": "0.802.0-next.1",`. The application is throwing below error:

```
ERROR NullInjectorError: StaticInjectorError(a)[D -> Q]: 
  StaticInjectorError(Platform: core)[D -> Q]: 
    NullInjectorError: No provider for Q!
    at oe.get 

```

With sourcemaps enabled, it points to below code:

```
() => navigator.serviceWorker.register(script, { scope: options.scope })
            .catch((/**
         * @param {?} err
         * @return {?}
         */
        err => console.error('Service worker registration failed with:', err)))));
```

## 🔥 Exception or Error
<pre><code>
ERROR NullInjectorError: StaticInjectorError(a)[D -> Q]: 
  StaticInjectorError(Platform: core)[D -> Q]: 
    NullInjectorError: No provider for Q!
    at oe.get 
</code></pre>

## 🌍 Your Environment
<pre><code>
Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.802.0-next.1
@angular-devkit/build-angular              0.802.0-next.1
@angular-devkit/build-optimizer            0.802.0-next.1
@angular-devkit/build-webpack              0.802.0-next.1
@angular-devkit/core                       8.2.0-next.1
@angular-devkit/schematics                 8.2.0-next.1
@angular/cdk                               8.1.1
@angular/cli                               8.2.0-next.1
@angular/fire                              5.2.1
@angular/flex-layout                       8.0.0-beta.26
@angular/http                              8.0.0-beta.9
@angular/material                          8.1.1
@angular/material-moment-adapter           8.1.1
@angular/pwa                               0.802.0-next.1
@ngtools/webpack                           8.2.0-next.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.2.0-next.1
@schematics/update                         0.802.0-next.1
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.35.3
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

It’s also worth mentioning in the above list of packages `@angular-devkit/build-angular` is not `next-1` but `next-0`.

**Comment by naveedahmed1** [comment]
@alan-agius4 thank you for quick reply. I will share the repo soon. I have updated the issue and have updated the `ng version` output from the affected project.

**Comment by adrogon** [comment]
It might not be the exact same issue, but I end up with the same stacktrace with the simple following reproduction using flex-layout. Please notice it only fails when `buildOptimizer` is enabled.

Please find the repro repo here: https://github.com/adrogon/repro-build-optimizer

You will find 4 branches:

`git checkout works-in-next0-and-aot-only && npm i && ng serve`
initialises the project and shows it works nominally in `0.802.0-next.0` and `aot` enabled.

`git checkout still-works-in-next0-and-build-optimizer && npm i && ng serve`
shows it still works when enabling `buildOptimizer` and not upgrading to `0.802-next.1`.

`git checkout still-works-in-next1-and-aot-only  && npm i && ng serve`
shows it works in `0.802-next.1` when `buildOptimizer` is not enabled.

`git checkout fails-in-next1-and-build-optimizer && npm i && ng serve`
shows it fails in `0.802-next.1` with `buildOptimizer` enabled.

With the following stacktrace:
```
ERROR NullInjectorError: StaticInjectorError(AppModule)[DefaultLayoutAlignDirective -> StyleUtils]: 
  StaticInjectorError(Platform: core)[DefaultLayoutAlignDirective -> StyleUtils]: 
    NullInjectorError: No provider for StyleUtils!
    at NullInjector.get (http://localhost:4200/vendor.js:7869:27)
    at resolveToken (http://localhost:4200/vendor.js:9632:24)
    at tryResolveToken (http://localhost:4200/vendor.js:9558:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:9421:20)
    at resolveToken (http://localhost:4200/vendor.js:9632:24)
    at tryResolveToken (http://localhost:4200/vendor.js:9558:16)
    at StaticInjector.get (http://localhost:4200/vendor.js:9421:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:33973:29)
    at NgModuleRef_.get (http://localhost:4200/vendor.js:35059:16)
    at resolveDep (http://localhost:4200/vendor.js:35586:45)
```

And here is the environment used:
```
Angular CLI: 8.2.0-next.1
Node: 12.4.0
OS: linux x64
Angular: 8.2.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.1
@angular-devkit/build-angular     0.802.0-next.1
@angular-devkit/build-optimizer   0.802.0-next.1
@angular-devkit/build-webpack     0.802.0-next.1
@angular-devkit/core              8.2.0-next.1
@angular-devkit/schematics        8.2.0-next.1
@angular/cdk                      8.1.1
@angular/cli                      8.2.0-next.1
@angular/flex-layout              8.0.0-beta.26
@ngtools/webpack                  8.2.0-next.1
@schematics/angular               8.2.0-next.1
@schematics/update                0.802.0-next.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.3
```

**Comment by adrogon** [comment]
Hello @alan-agius4, is this repro enough for you, or do you need anything else?

**Comment by jeandat** [comment]
Same for me. Disabling `optimization` shows us it seems to happen in projects using `flex-layout` at least:

```
vendor-es2015.c5603c4025760f603c32.js:43009 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[DefaultFlexAlignDirective -> StyleUtils]: 
  StaticInjectorError(Platform: core)[DefaultFlexAlignDirective -> StyleUtils]: 
    NullInjectorError: No provider for StyleUtils!
NullInjectorError: StaticInjectorError(AppModule)[DefaultFlexAlignDirective -> StyleUtils]: 
  StaticInjectorError(Platform: core)[DefaultFlexAlignDirective -> StyleUtils]: 
    NullInjectorError: No provider for StyleUtils!
    at NullInjector.get (vendor-es2015.c5603c4025760f603c32.js:34736)
    at resolveToken (vendor-es2015.c5603c4025760f603c32.js:36499)
    at tryResolveToken (vendor-es2015.c5603c4025760f603c32.js:36425)
    at StaticInjector.get (vendor-es2015.c5603c4025760f603c32.js:36288)
    at resolveToken (vendor-es2015.c5603c4025760f603c32.js:36499)
    at tryResolveToken (vendor-es2015.c5603c4025760f603c32.js:36425)
    at StaticInjector.get (vendor-es2015.c5603c4025760f603c32.js:36288)
    at resolveNgModuleDep (vendor-es2015.c5603c4025760f603c32.js:60840)
    at NgModuleRef_.get (vendor-es2015.c5603c4025760f603c32.js:61926)
    at resolveDep (vendor-es2015.c5603c4025760f603c32.js:62453)
    at resolvePromise (polyfills-es2015.e308c8d63d076a2403a3.js:1085)
    at resolvePromise (polyfills-es2015.e308c8d63d076a2403a3.js:1042)
    at polyfills-es2015.e308c8d63d076a2403a3.js:1146
    at ZoneDelegate.invokeTask (polyfills-es2015.e308c8d63d076a2403a3.js:680)
    at Object.onInvokeTask (vendor-es2015.c5603c4025760f603c32.js:68615)
    at ZoneDelegate.invokeTask (polyfills-es2015.e308c8d63d076a2403a3.js:679)
    at Zone.runTask (polyfills-es2015.e308c8d63d076a2403a3.js:455)
    at drainMicroTaskQueue (polyfills-es2015.e308c8d63d076a2403a3.js:848)
    at ZoneTask.invokeTask [as invoke] (polyfills-es2015.e308c8d63d076a2403a3.js:758)
    at invokeTask (polyfills-es2015.e308c8d63d076a2403a3.js:1889)
```

**Comment by jeandat** [comment]
Shouldn't this issue posted to @angular/flex-layout repo instead?
https://github.com/angular/flex-layout/issues/1107

**Comment by annamajorova0278** [comment]
Ofa 76d40e4

**Comment by annamajorova0278** [comment]
Версия:    5-4-hotfix1

**Comment by annamajorova0278** [comment]
8a7393e
