### ISSUE TITLE
Can't add a script cdn to my html

### ISSUE THREAD

**Issue by rajjejosefsson** [angular/angular-cli#1515]
> Please provide us with the following information:
> ---------------------------------------------------------------

**1. OS**
Mac OSX El Capitan

**2. Versions.**
angular-cli: 1.0.0-beta.9
node: 6.3.0

**3. Repro steps.**
When I add the script:   <script src="https://use.fontawesome.com/xxxxxxxx.js"></script> into the Head of my index.html file, and then later click on on a routerLink, then I wont get redirected until I press it again. this happens on all of my routerlinks.

**Code**

**Index.html**
```
<head>
  <meta charset="utf-8">
  <title>RTvOne</title>
  <base href="/">
  
  {{#unless environment.production}}
  <script src="/ember-cli-live-reload.js" type="text/javascript"></script>
  {{/unless}}
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <script src="https://use.fontawesome.com/ee49865b48.js"></script>
</head>
```

**Routes**

```
export const APP_ROUTES = [
  provideRouter([
    { path: '', redirectTo: '/home', pathMatch: 'full'},
    { path: 'home', component: HomeComponent},
    { path: 'shows', component: ShowsComponent},
    { path: 'movies', component: MoviesComponent},
    { path: 'detail', component: ShowDetailComponent},
    { path: 'watchlist', component: WatchlistComponent},
  ])
];
```

**Navigation bar**

```
 <ul class="nav navbar-nav">
        <li><a [routerLink]="['/shows']">Tv-shows <span class="sr-only">(current)</span></a></li>
        <li><a [routerLink]="['/movies']">Movies</a></li>
        <li><a [routerLink]="['/watchlist']">Your Watchlist</a></li>
 </ul>
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sirajc** [comment]
Can you show some code here what is included in head, what is in routerLink and when it fails

**Comment by rajjejosefsson** [comment]
Sorry, added some more details of the code now.

**Comment by filipesilva** [comment]
I'm not sure this is a CLI problem to be honest. It seems that either the CDN scripts your are adding or the router itself has a problem, but in either way I don't see it as a CLI issue since whatever you put there is being served.
