### ISSUE TITLE
ng serve warning when there is a build

### ISSUE THREAD

**Issue by Meberem** [angular/angular-cli#15161]
# 🐞 Bug report
### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Probably not

### Description
When I run `ng serve` after running `ng build` assets from the build folder are being served instead of the generated ones from `ng serve`.

I ran `ng build` to identify an issue affecting our build server, tweaked a template, all was well. Later when I continued developing `ng serve` I noticed that my changes weren't affecting the page, after much hair pulling I deleted the build folder and all was well again. 

As `ng serve` is for development, could a warning or something be displayed on each incremental build if the output has a chance of being ignored?

## 🔬 Minimal Reproduction
As far as I am aware this is a standard angular project.
https://github.com/Meberem/ng-build-serve-example-app
ng build
visit page
ng serve
visit page

## 🌍 Your Environment
<pre><code>
8.0.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @Meberem, `ng build` output should effect `ng serve` builds in anyway. 

Can you please provide a minimal reproduction?

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

Thanks.

**Comment by Meberem** [comment]
I have copied and stripped the project. Annoyingly lazy loaded routes are broken so I cannot test it. When I have some more time I will take another look at this

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
