### ISSUE TITLE
If we set buildOptimizer and aot to false, apllication throws error?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#15174]
# 🐞 Bug report

I have created an angular with ASP .NET Core sample. when i try to run my angular application only using below command it is working fine

> ng serve --prod

But when i set `buildOptimizer` and `aot` to ` false` application throws error

## 🔥 Exception or Error
![download (1)](https://user-images.githubusercontent.com/36756050/61955652-19600d00-afd9-11e9-8beb-b4da4b913fc9.png)

### My config:

![download](https://user-images.githubusercontent.com/36756050/61955670-254bcf00-afd9-11e9-90a8-cbf230201fe1.png)

## 🔬 Minimal Reproduction

1.  Download [sample](https://www.syncfusion.com/downloads/support/directtrac/general/ze/DemoApp_c12abc05870089545) 

2. goto `ClientApp` folder

3. give `npm i` command

4. then give `ng serve --prod`

You will see reported error in console window

## 🌍 Your Environment
<pre><code>

 "@angular/animations": "6.1.10",
    "@angular/common": "6.1.10",
    "@angular/compiler": "6.1.10",
    "@angular/core": "6.1.10",
    "@angular/forms": "6.1.10",
    "@angular/http": "6.1.10",
    "@angular/platform-browser": "6.1.10",
    "@angular/platform-browser-dynamic": "6.1.10",
    "@angular/platform-server": "6.1.10",
    "@angular/router": "6.1.10",
</code></pre>

**Comment by kumaresan-subramani** [comment]
Hi @alan-agius4 ,

Do you have any idea about this, please share it

**Comment by alan-agius4** [comment]
The problem seems to be that you have `optimization`: true, Most likely there some non side effect code free which being removed.

**Comment by kumaresan-subramani** [comment]
okay @alan-agius4  👍

**Comment by filipesilva** [comment]
If you run `ng serve --prod --source-map` you can see where the error comes from:
![image](https://user-images.githubusercontent.com/4172079/62302462-4e091400-b472-11e9-811e-b45bcbff98c3.png)

That being said, even with that extra information the best I can see is that something breaks inside that library. Maybe it's a bug somewhere... 

Can you try with the latest Angular CLI though? You are using version 6 and a lot of changed since then. Maybe the problem has been fixed.

**Comment by kumaresan-subramani** [comment]
okay @filipesilva , i will try with angular 8.

If there is a bug in my library thenm why it works fine with **optimization** true

**Comment by filipesilva** [comment]
Using `optimization` set to true will try to remove unused code. Maybe the problematic code is removed and thus it doesn't error at runtime.

**Comment by filipesilva** [comment]
Closing as stale. If you're still having this problem with the latest versions let us know with a repro and we can reopen.
