### ISSUE TITLE
From angular-cli 1.0.0-beta 28 to @angular/cli 8.1.2

### ISSUE THREAD

**Issue by treavord** [angular/angular-cli#15181]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by treavord** [comment]
Ok, so I am fairly new to Angular/AngularJS, and I am trying to upgrade from AngularJS to Angular. I have read online, in the Angular documentation, that I would have to upgrade this slowly, for it is not recommended that one upgrade from AngularJS to the latest version of Angular. The problem, however, is that I cannot seem to figure out how to upgrade to even Angular v2. 

Here are the steps that I have taken:
1) npm uninstall -g angular-cli
2) npm cache verify
3) npm install -g @angular/cli (and sometimes I would include version 2 here [or 1.7.x])

Listed below is the error message I receive when I try to do an ng new TestApp 
------------------------------------------------------------------------------------
Schematic input does not validate against the Schema: {"name":"TestApp"}
Errors:

  Data path "" should have required property 'version'.
------------------------------------------------------------------------------------
When I run ng version, I obtain the following information below:
-----------------------------------------------------------------------------------
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.2
Node: 10.16.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.2
@angular-devkit/core         8.1.2
@angular-devkit/schematics   8.1.2
@schematics/angular          8.1.2
@schematics/update           0.801.2
rxjs                         6.4.0
    
Treavor:Health notsure$ ls
Health
Treavor:Health notsure$ ng new TestApp
Schematic input does not validate against the Schema: {"name":"TestApp"}
Errors:

  Data path "" should have required property 'version'.
Treavor:Health notsure$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.2
Node: 10.16.0
OS: darwin x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.2
@angular-devkit/core         8.1.2
@angular-devkit/schematics   8.1.2
@schematics/angular          8.1.2
@schematics/update           0.801.2
rxjs                         6.4.0




Thanks for any help with this!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
