### ISSUE TITLE
angular cli should add a param to indicate the max amount of runtime memory

### ISSUE THREAD

**Issue by rdkmaster** [angular/angular-cli#15184]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

[Jigsaw](https://github.com/rdkmaster/jigsaw) is a very large angular project, which contains nearly about 1000 angular objects (components/services/directives etc.) in 1755 files, so many angular objects makes the progress of compilation needs a lots of memory, specialy the build command will fail to finish when I use `--aot --prod` options. The reason is the default value of `max_old_space_size` of node is only 1Gb, and it is not enough to build [Jigsaw](https://github.com/rdkmaster/jigsaw) with `--aot --prod` options.

To bypass this issue, I need to use the following command 

```
node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build  --aot --prod ...
```

It's working perfectly for now, but I think this is not right, angular cli should give us a param to do this, like: 

```
ng b --max_old_space_size=4096 --aot --prod ...
```

By the way, use the following commands to reproduce the issue:

```
git clone https://github.com/rdkmaster/jigsaw.git
cd jigsaw
npm i
ng b --aot --prod
```

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

angular cli should give us a param to do this, like: 

```
ng b --max_old_space_size=4096 --aot --prod ...
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Hi @rdkmaster, IMHO, I don't think this option should be part of the CLI public API as really this is an Node option which won't do anything to the CLI itself.

I think it's best to leverage the usage Node's `NODE_OPTIONS` via environment variables. 

Example:
```
set "NODE_OPTIONS=--max_old_space_size=4096" && ng build
```

**Comment by alan-agius4** [comment]
Closing as per above answer.
