### ISSUE TITLE
i ｢wds｣: 404s will fallback to //index.html

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#15185]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I don't have any issue in angular 7 with cli 7.3.8 i guess.

 Yes, the previous version in which this bug was not present was: ....

### Description
I just added two routes and angular theme css in my project. Now i encountered to this error when i run ng serve.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
app-routing.module.ts
````
const routes: Routes = [
  {path: '', redirectTo:'/login', pathMatch:'full'},
  {path: 'login', loadChildren: () => import('../auth/auth.module').then(m => m.AuthModule)}
];
````
auth-routing.module.ts
````
const authRoute: Routes = [
    {path:'', component: LoginComponent}
]

````

base href in index.html bydefault
````
 <base href="/">
````

## 🔥 Exception or Error
<pre><code>

ng serve
 10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html
chunk {auth-auth-module} auth-auth-module.js, auth-auth-module.js.map (auth-auth-module) 279 kB  [rendered]
chunk {main} main.js, main.js.map (main) 16.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 251 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 8.94 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.95 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.16 MB [initial] [rendered]
Date: 2019-07-29T05:43:05.908Z - Hash: d30fdab03b1f2a3e4fa3 - Time: 20301ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Compiled successfully.
</code></pre>

## 🌍 Your Environment
<pre><code>

ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.2
Node: 10.16.0
OS: win32 x64
Angular: 8.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cli                      8.1.2
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**

similar issue:
1. https://stackoverflow.com/questions/56954866/can-any-one-help-me-to-understand-this-message-in-cmd-when-run-ng-serve-angular

**Comment by CSchulz** [comment]
This is no bug. It is an automatic created failback, if the url is unknown.

Do you have any issues?

**Comment by alan-agius4** [comment]
Hi @indraraj26, The message you are seeing is for informational purposes as explained in the above linked SO issue.

Thanks.
