### ISSUE TITLE
Angular install beta.10 on windows does not complete

### ISSUE THREAD

**Issue by cintia-baniola** [angular/angular-cli#1518]
Hans@HP-HANS C:\Users\Hans
$ ng --version
angular-cli: 1.0.0-beta.9
node: 4.4.4
os: win32 x64

Hans@HP-HANS C:\Users\Hans
$ npm i -g angular-cli
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
C:\Users\Hans\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Hans\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "angular-cli"
npm ERR! node v4.4.4
npm ERR! npm  v3.7.1
npm ERR! path C:\Users\Hans\AppData\Roaming\npm\node_modules\.staging\abbrev-2fbeb4e3
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Hans\AppData\Roaming\npm\node_modules\.staging\abbrev-2fbeb4e3' -> 'C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Hans\AppData\Roaming\npm\node_modules\.staging\abbrev-2fbeb4e3' -> 'C:\Users\Hans\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Hans\npm-debug.log
npm ERR! code 1

**Comment by jvbianchi** [comment]
+1

**Comment by sirajc** [comment]
Try version .11

**Comment by filipesilva** [comment]
Seems to be an npm problem. What's your NPM version? It needs to be greater than 3.
