### ISSUE TITLE
Tiny potential issue about incorrect '(ngfactory|ngstyle).js$' in Webpack configuration 

### ISSUE THREAD

**Issue by liujingbreak** [angular/angular-cli#15195]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No.
### Description
in https://github.com/angular/angular-cli/blob/607e6f7cfd7b5f16231eae968fbf36e920c169e0/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L419

I think `/(ngfactory|ngstyle).js$/` meant to be `/(ngfactory|ngstyle)\.js$/`.

and https://github.com/angular/angular-cli/blob/607e6f7cfd7b5f16231eae968fbf36e920c169e0/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L406

## 🌍 Your Environment
<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Good point there is also https://github.com/angular/angular-cli/blob/607e6f7cfd7b5f16231eae968fbf36e920c169e0/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L410
