### ISSUE TITLE
Filter Angular proxy routes by HTTP request methods

### ISSUE THREAD

**Issue by hpardess** [angular/angular-cli#15192]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I am working on a project using Spring boot and angular 6. I have setup multiple proxy routes. Everything is working fine but my requirements changed little. The proxy should forward the request to remote server only the proxy route match and its HTTP request method.
For example: If I call "/login", it should not send request to remote server but local routes of angular should be served. when I call "/login" with POST type then it should send request to remote server.

### Describe the solution you'd like
We should have add a property of method to identify which HTTP method of given path should be forwarded.
```
{
  "/login":{
        "http_method": ["POST", "PUT"],
        "target": "http://localhost:8090",
        "secure": false,
        "logLevel": "debug"
    }
}
```
Therefore, a ( GET: /login ) will not be forwarded to "http://localhost:8090" address.

**Comment by alan-agius4** [comment]
Hi, the option name is `methods`.

See: https://github.com/webpack/webpack-dev-middleware for more details and a full list of options.

**Comment by hpardess** [comment]
Here is my proxy configuration:

1. I run this command `ng serve --proxy-config proxy.config.json`

2. Here is my proxy.config.json file content
```
{
    "/api": {
        "target": "http://localhost:8090",
        "secure": false,
        "changeOrigin":true,
        "logLevel": "debug"
    },
    "/logout":{
        "target": "http://localhost:8090",
        "secure": false,
        "logLevel": "debug"
    },
    "/login":{
        "methods": ["POST"],
        "target": "http://localhost:8090",
        "secure": false,
        "logLevel": "debug"
    }
}
```

@alan-agius4, As you have mentioned that add "methods" option will server the purpose and you can see in "login" route.
 Request with GET method is also forwarded. Here is the console log: 
`[HPM] GET /login -> http://localhost:8090`
