### ISSUE TITLE
3rd party libs installer prompts misleading

### ISSUE THREAD

**Issue by wearska** [angular/angular-cli#152]
Great feature this, but there's a bug:

After you install a package, the prompt asks you if you want to automatically inject it. Default answer is "N", but if you hit enter, it says "Done" and doesn't walk you through the rest of the setup.

On a different note, I can't find any documentation / guidelines on how to use it.
Readme needs to be updated to at least say it exists.

**Comment by jkuri** [comment]
Yes, default answer is "N" and I think its not a bug if it doesn't walk you through the rest of the setup if you answer N(o). 
Documentation it will be written soon, even for creating libs to be compatible with this feature.

**Comment by wearska** [comment]
This means I understood wrong?
If the prompt asks me if I want it to do something automatically, then, if I say 'Yes', it should go ahead and do it's job, automatically... If I say 'No', it should start prompting me for details about that specific task. 
Am I not right?

**Comment by jkuri** [comment]
````shell
[bla]$ ng install ng2-jwt
warning: An ember-addon has attempted to override the core command "install". The addon command will be used as the overridding was explicit.
version: 1.13.15
Installing 3rd party package: ng2-jwt...
Package successfully installed.

[?] Would you like to inject the installed packages into your app automatically? (N/y) N

Done.
[bla]$ ng install ng2-jwt
warning: An ember-addon has attempted to override the core command "install". The addon command will be used as the overridding was explicit.
version: 1.13.15
Installing 3rd party package: ng2-jwt...
Package successfully installed.

[?] Would you like to inject the installed packages into your app automatically? (N/y) Y
[?] What is the path to the file which bootstraps your app? (/Users/jan/Desktop/bla/src/app.ts)
.
.
.
````

Is that not right? I cannot repeat your "bug", please tell me the scenario.

**Comment by wearska** [comment]
I believe the first prompt is a tad misleading... 
If you ask me to do something automatically and I say NO, it means I want you to let me do it... That's how I see it.
When you ask me if I want to automatically inject something, and I say 'No', I expect you to let me do it manually, and further prompt me for details.

Don't get me wrong, the above example applies to me as well.. There's no bug installing the libs
But.. I think the prompt should react the other way around.

**Comment by jkuri** [comment]
Maybe you're right. If someone else see it as misleading, we will change the questions or the sequence.

**Comment by jkuri** [comment]
@wearska you were right, prompts is a bit misleading. Also, I found some bugs myself and I will make fixes through the weekend. When you will have time, please provide questions in order (with default answers) how would you initialize the prompt and I will rework the code so.

**Comment by jkuri** [comment]
@wearska please check https://github.com/angular/angular-cli/pull/160. You can test it with ng2-cli-test-lib if you will.
