### ISSUE TITLE
bug(npm): Update karma-webpack when release is cut. Peer Dep issues.

### ISSUE THREAD

**Issue by TheLarkInn** [angular/angular-cli#1520]
You cannot currently shrinkwrap cli on master because of a karma-webpack and webpack@2.1.0-beta.x peer dependency problem. The issue is already fixed by that team, but a release needs to be cut. When @sokra does a release we need to update it in the cli.  

npm ERR! Problems were encountered
> npm ERR! Please correct and try again.
> npm ERR! peer invalid: webpack@^1.4.0, required by karma-webpack@1.7.0

**Comment by ritz078** [comment]
any temporary solution for this ?

**Comment by TheLarkInn** [comment]
I did not receive these warning on latest node if that helps.
