### ISSUE TITLE
Unable to update CLI

### ISSUE THREAD

**Issue by tobieeniafe** [angular/angular-cli#15203]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I don't think so

### Description

 A clear and concise description of the problem...
I've been away from angular for a while so i decide do update my CLI. the thing is, it actually updates but when i check the version it shows the old one. And when i build my app, it builds an angular 4 app.
![Screenshot (3)](https://user-images.githubusercontent.com/18620774/62114115-dbe7d200-b2ad-11e9-9fd9-bfb625a86e25.png)
 

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

@angular/cli: 1.3.2
node: 10.16.0
os: win32 x64

</code></pre>

**Anything else relevant?**

I have tried uninstalling NPM & node, cleared cache but still to no avail

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
