### ISSUE TITLE
generate stats.json file for library analysis

### ISSUE THREAD

**Issue by ydomenjoud** [angular/angular-cli#15205]
# 🐞 Bug report

### Command
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
option --stats-json doesn't work for library 

## 🔬 Minimal Reproduction
create new project, generate library, try to build stats-json file for analyze
```bash
ng new --create-application=false empty-project --routing --style=css
cd empty-project
ng generate library simple-library
ng build simple-library --stats-json
```

## 🔥 Exception or Error
<pre><code>
Unknown option: '--stats-json'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.3
Node: 10.16.0
OS: linux x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.3
@angular-devkit/build-angular      0.801.3
@angular-devkit/build-ng-packagr   0.801.3
@angular-devkit/build-optimizer    0.801.3
@angular-devkit/build-webpack      0.801.3
@angular-devkit/core               8.1.3
@angular-devkit/schematics         8.1.3
@ngtools/webpack                   8.1.3
@schematics/angular                8.1.3
@schematics/update                 0.801.3
ng-packagr                         5.4.3
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.35.2
</code></pre>

**Comment by alan-agius4** [comment]
Hi that is expected please see: https://angular.io/cli/build

> The command can be used to build a project of type "application" or "library". When used to build a library, a different builder is invoked, and only the ts-config, configuration, and watch options are applied. All other options apply only to building applications.

**Comment by ydomenjoud** [comment]
thanks for your time.
How to analyse library build then ?
