### ISSUE TITLE
Updating w/ `ng update` in project previously updated with `--next` version produces version mismatch

### ISSUE THREAD

**Issue by Ploppy3** [angular/angular-cli#15216]
🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not sure if it ever worked at all

### Description

nb: what I call a beta project is a project running the beta versions of angular, which was created or updated with the `--next` argument.

Updating a beta project with `ng update` should show at least a warning as it produces versions mismatch.

Using `ng update` does not seem to update internal packages (devkit) to latest version of the beta branch.

It produces version mismatch which can result in really weird bugs which are tough to find since you need to output the versions using `ng version` to identify the root cause.

You can see the problem here: 
Angular was updated from `0.802.0-next.0` to `8.2.0-next.2` but most of the internal packages were not updated and are still running the `0.802.0-next.0` version.

Check this for more people running into the issue without noticing.
https://github.com/angular/angular/issues/31654

```
Angular CLI: 8.2.0-next.0
Node: 10.15.3
OS: linux x64
Angular: 8.2.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.0
@angular-devkit/build-angular     0.802.0-next.0
@angular-devkit/build-optimizer   0.802.0-next.0
@angular-devkit/build-webpack     0.802.0-next.0
@angular-devkit/core              8.2.0-next.0
@angular-devkit/schematics        8.2.0-next.0
@angular/cdk                      8.1.1
@angular/cli                      8.2.0-next.0
@angular/material                 8.1.1
@ngtools/webpack                  8.2.0-next.0
@schematics/angular               8.2.0-next.0
@schematics/update                0.802.0-next.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.3
```

## 🔬 Minimal Reproduction

- `ng update --next`
- wait for next beta release
- `ng update ` (without --next)

Results in mismatched versions.

## 🔥 Exception or Error

None

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

Updating a beta project with `ng update` should update similarly to the `ng update --next`
or
Updating a beta project with `ng update` should show a warning and not do anything at all

**Comment by alan-agius4** [comment]
Hi @Ploppy3, The above versions seems to be correct.

Not all `@angular-devkit` packages are stable and these have not yet been released as a major version.

> Note About Versioning
You might have noticed some versions have changed since the last release. We always had two channels for our packages; stable and experimental. For example, @angular/cli is stable, while @angular-devkit/build-angular is experimental. So far, we managed those versions independently of each others (7.3.x matches 0.13.x, while 8.0.0 matches 0.14.0).

> From version 8.0.0 and upwards, we will start using the power of Mathematics for choosing the experimental packages versions. The formula is simple; "0." + (major * 100 + minor) + "." + patch. So, for example, the 8.0.0 release becomes the 0.800.0 version for experimental packages.

> This allows us to better manage our experimental packages (they are always monotonic with time), and it allows users to know if they are not matching versions between their packages in their projects, without relying on looking up the npm registry or other sources. If a package version does not match the formula above, you might have mismatching packages.

See here: https://github.com/angular/angular-cli/releases/tag/v8.0.0 and here https://github.com/angular/angular-cli#packages for more details

**Comment by Ploppy3** [comment]
@alan-agius4 I'm pretty sure you are wrong, after updating with `ng update --next` all the devkit packages got updated. 

**Aggressively closing issues is not how you solve problems** and it seems to be quite popular among the Angular devs, I got the same experience with AngularFire's dev.

Did you at least took the time to read the linked issue?

**Comment by alan-agius4** [comment]
Hi @Ploppy3, please accept my apologies and thanks for the feedback. Though I am not quite understanding the problem here.

The below versions that you posted above seems to be aligned.
```
Angular: 8.2.0-next.2
Angular CLI: 8.2.0-next.0
@angular-devkit/package-name: 0.802.0-next.0
@schematics/package-name: 0.802.0-next.0
```
Note: that the `@angular/cli` package is different from other angular packages such as `@angular/core`. While most of the time they are the same version it is not always the case. Since these live in a separate repo and have different release cycles.

Full version
```
Angular CLI: 8.2.0-next.0
Node: 10.15.3
OS: linux x64
Angular: 8.2.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.0-next.0
@angular-devkit/build-angular     0.802.0-next.0
@angular-devkit/build-optimizer   0.802.0-next.0
@angular-devkit/build-webpack     0.802.0-next.0
@angular-devkit/core              8.2.0-next.0
@angular-devkit/schematics        8.2.0-next.0
@angular/cdk                      8.1.1
@angular/cli                      8.2.0-next.0
@angular/material                 8.1.1
@ngtools/webpack                  8.2.0-next.0
@schematics/angular               8.2.0-next.0
@schematics/update                0.802.0-next.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.3
```

Can you please provide the `package.json` before and after the running `ng update`?

**Comment by Ploppy3** [comment]
Something is really weird, I think I'm missing some information or there is something I don't understand. 

![image](https://user-images.githubusercontent.com/7990765/62297888-447fac00-b472-11e9-8ce2-774f2c0134d8.png)

Hope this image can clear things up.

I have a question though, I already knew that @angular/cli had a different version than Angular packages and that devkit packages' versions were on a different format. Though, I thought the devkit packages' versions were tied to the main Angular packages while it seems not to be the case if I understand you. So are the devkit packages tied to the CLI version?

**If the answer is yes, then you can probably close this.**

_Sorry for my English, those sentences are quite tough to make and I'm really tired!_

**Comment by alan-agius4** [comment]
@Ploppy3 yes, the devkit packages are tied to the CLI version and not the frameworks. The devkit packages are situated in the CLI monorepo (https://github.com/angular/angular-cli/tree/master/packages) and get released at the same time. 

If the CLI version is for example `8.2.0-next.1`, the unstable version of a devkit package will be `0.802.0-next.1`

The above versions that you have in your `package.json` look as they should.

Your English is fine :)

**Comment by Ploppy3** [comment]
Thank you for the clarifications.
Have a great day.
