### ISSUE TITLE
ng build --prod --aot failure

### ISSUE THREAD

**Issue by luohong123** [angular/angular-cli#15212]
# 🐞 Bug report

### Command (mark with an `x`)

```

- [ ] build

```

### Is this a regression?
Aot package can not check the package under node_modules, only detect the business code, because my third-party plug-in is not standardized, can not be packaged by aot, but I want to use aot package

 Yes, the previous version in which this bug was not present was: ....
![image](https://user-images.githubusercontent.com/20392340/62198674-a5e14580-b3b4-11e9-9d44-ed5f2e13db1f.png)

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

ERROR in : Unexpected value 'FccoreModule in /project/node_modules/fccore/index.module.d.ts' imported by the module'AppModule in /project/src/app/app.module.ts'. Please add a @NgModule annotation.
</code></pre>

## 🌍 Your Environment
<pre><code>

"devDependencies": {
    "@angular/cli": "1.6.7",
    "@angular/compiler-cli": "^5.1.0",
    "@angular/language-service": "^5.1.0",
    "@types/jasmine": "^2.8.7",
    "@types/jasminewd2": "~2.0.2",
    "@types/lodash": "^4.14.112",
    "@types/node": "^6.0.108",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.9.1",
    "typescript": "~2.5.3"
  }
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Also Angular CLI version 1 and Angular 5 are no longer in LTS https://angular.io/guide/releases.

More information about how to update can be found: https://update.angular.io
