### ISSUE TITLE
@ngtools/webpack not working with HMR after 8.0.0 and IVY enabled

### ISSUE THREAD

**Issue by kukjevov** [angular/angular-cli#15225]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

not using angular cli, but @ngtools/webpack

### Is this a regression?

Yes in version 8.0.1 was working, 8.1.0 or higher is not working.

### Description

When you change anythying in your template and HMR reloads script you will receive error that any directive or component that is used in that template is not known. When you stop HMR and rebuild application and run it again everything is working fine until you change something. I have another project and i cant move from 8.0.1 because this is only working version with Angular IVY, @ngtools/webpack and HMR.

## 🔬 Minimal Reproduction

download this https://github.com/kukjevov/ngtools-error

> `git clone https://github.com/kukjevov/ngtools-error`
> `cd ngtools-error`
> `npm install`
> `npm start`
> open in browser `http://localhost:8888
> add `<div>super</div>` into either `app.component.html` or `navigation.component.html`
> look for error in browser console

## 🔥 Exception or Error

if you change `app.component.html` you will get

<pre><code>
Error: "Export of name 'outlet' not found!"
</code></pre>

if you change `navigation.component.html` you will get

<pre><code>
Error: "Template error: Can't bind to 'routerLinkActiveOptions' since it isn't a known property of 'div'."
</code></pre>

## 🌍 Your Environment

- angular and ngtools: 8.2.0
- node: 10.16.0
- npm: 6.9.0

**Comment by filipesilva** [comment]
Heya, I'm closing because https://github.com/angular/angular/issues/31916#issuecomment-517482988 indicates this is an bug on the Framework repository and there is a fix on the way.
