### ISSUE TITLE
Generate SourceMaps without `sourceMappingURL`s

### ISSUE THREAD

**Issue by EddyP23** [angular/angular-cli#15223]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] build
```

### Description
 A clear and concise description of the problem or missing capability...
Currently, there seems to be a single option to generate source maps (e.g. in `angular.json` by setting `"sourceMap:" true`). But this has a side effect (often desired, but not always) by injecting `sourceMappingURL`s into the `css` and `js` files.

For the cases when source maps are used to debug prod environment, it is not desired to have `sourceMappingURL`s in the `js` and `css` files. E.g. Google Chrome shows a warning in the console when it tries to download the source map and it can't find it.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Ability to configure, whether `sourceMappingURL`s should be injected when generating source maps.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
This can be removed by running some post-build script, but seems to be far from ideal.

**Comment by alan-agius4** [comment]
Hi, this is already possible by using the `hidden` option under `sourceMap`.

More info can be found here: https://angular.io/guide/workspace-config#optimization-and-source-map-configuration
