### ISSUE TITLE
Ng update to 8.2.0 from 8.1.3 failed with JSON parse error

### ISSUE THREAD

**Issue by edocbuhtig** [angular/angular-cli#15228]
# 🐞 bug report

### Affected Package

 The issue is caused by package typescript 3.5.3 (was 3.4.5)

### Is this a regression?

 No

### Description

 ng update stops at typescript package update with below error

Updating package.json with dependency @angular/cli @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/core @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/language-service @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/compiler-cli @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.802.0" (was "0.801.3")...
    Updating package.json with dependency @angular/compiler @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/animations @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/forms @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/platform-browser @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/router @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency @angular/common @ "8.2.0" (was "8.1.3")...
    Updating package.json with dependency typescript @ "3.5.3" (was "3.4.5")...
UPDATE package.json (1470 bytes)
npm ERR! Unexpected end of JSON input while parsing near '...acfd0c64c8af95ec543ec'

## 🔥 Exception or Error
<pre><code>

893 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...fjJbrSff1q1\nvJzk\r\n'

893 verbose stack     at JSON.parse (<anonymous>)

893 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)

893 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50)

893 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

CLI 8.1.3
Node 10.16.0
Angular 8.1.3
NPM 6.10.2
</code></pre>

**Anything else relevant?**

**Comment by 87CSY** [comment]
Similar issue here.

CLI 8.1.2
Node 12.6.0
NPM 6.10.2

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.6.0
4 verbose npm-session 5da19454fa87a69d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/@angular%2fcli 827ms (from cache)
8 silly fetchPackageMetaData error for @angular/cli@latest Unexpected end of JSON input while parsing near '...KK\r\n-----END PGP SI'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 885ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...KK\r\n-----END PGP SI'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (C:\Users\Shunt\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
11 verbose stack     at C:\Users\Shunt\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:85:5)
12 verbose cwd C:\Users\Shunt\Code
13 verbose Windows_NT 10.0.17134
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "@angular/cli"
15 verbose node v12.6.0
16 verbose npm  v6.10.2
17 error Unexpected end of JSON input while parsing near '...KK\r\n-----END PGP SI'
18 verbose exit [ 1, true ]
```

**Comment by alan-agius4** [comment]
Hi, can you try to clean your npm cache before running the command?

```
npm cache clean —force
```

**Comment by edocbuhtig** [comment]
@alan-agius4 No luck same issue, it fails only at typescript everytime.

**Comment by alan-agius4** [comment]
This seems like an npm connection/mirror issue.

Just you try a couple of things please.

```
npm cache clean --force
rm -f package-lock.json
npm i
ng update
```

Thanks.

**Comment by edocbuhtig** [comment]
Final got it working, seems to be NPM issue , had to do a clean nodejs reinstall, and all went well.

Note: if you do npm cache clean --force you may get tarball warning of corrupt files, so avoid doing that.
