### ISSUE TITLE
Angular Builders section does not specify how to create a new builder project

### ISSUE THREAD

**Issue by santoshyadav198613** [angular/angular-cli#15226]
# 📚 Docs or angular.io bug report

### Description

There is a command to create schematics project , but builders docs deos not specify how to create one for builders.

### What's the affected URL?**
https://angular.io/guide/cli-builder

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by clydin** [comment]
The documentation specifies what files to create and what dependencies are needed.  It also discusses multiple design considerations and publishing aspects.

What elements of the documentation do you find lacking?

**Comment by alan-agius4** [comment]
@santoshyadav198613, can you provide more details please? Thanks

**Comment by santoshyadav198613** [comment]
Hi @alan-agius4 and @clydin , 

To create a schematics based project we can do it via CLI, may be I wanted is CLI to create a builder project, as many people are creating custom CLI, currently we need to do it manually or by referring to sample project create by Minko which is included in documentation. Hope it is clear now. And sorry for not getting back earlier on this.

**Comment by mgechev** [comment]
I don't think there's sufficient number of folks developing builders to include scaffolding functionality in the CLI. I'd recommend implementing custom schematics collection.
