### ISSUE TITLE
type `SourceFile` mismatched

### ISSUE THREAD

**Issue by wendzhue** [angular/angular-cli#15230]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

⬆️ not accurate in my situation...

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.1.2.

### Description

 A clear and concise description of the problem...

Some type definitions in the source code just won't match. But since they have the same name, they should match (as in previous versions).

## 🔬 Minimal Reproduction

```ts
import { getProjectFromWorkspace, getProjectMainFile, getSourceFile } from '@angular/cdk/schematics';
import { insertImport } from '@schematics/angular/utility/ast-utils';

insertImport(getSourceFile(host, appModulePath));
```

Editor / IDE would report an error:

<img width="1162" alt="屏幕快照 2019-08-02 下午3 03 37" src="https://user-images.githubusercontent.com/12122021/62350910-bde0d280-b536-11e9-9cbf-f2fa2d524a02.png">

## 🔥 Exception or Error
<pre><code>

schematics/ng-add/setup-project/register-locale.ts:31:20 - error TS2345: Argument of type 'import("/home/travis/build/NG-ZORRO/ng-zorro-antd/node_modules/typescript/lib/typescript").SourceFile' is not assignable to parameter of type 'import("/home/travis/build/NG-ZORRO/ng-zorro-antd/node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript").SourceFile'.

insertImport(moduleSource, appModulePath, 'NZ_I18N',
</code></pre>

You can find the complete log [here](https://travis-ci.org/NG-ZORRO/ng-zorro-antd/jobs/566792178).

## 🌍 Your Environment
<pre><code>

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.6
@angular-devkit/build-angular              0.800.6
@angular-devkit/build-ng-packagr           0.800.6
@angular-devkit/build-optimizer            0.800.6
@angular-devkit/build-webpack              0.800.6
@angular-devkit/core                       8.2.0
@angular-devkit/schematics                 8.2.0
@angular/cdk                               8.1.2
@angular/pwa                               0.800.6
@ngtools/webpack                           8.0.6
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.2.0
@schematics/update                         0.802.0
ng-packagr                                 5.4.3
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.30.0

</code></pre>

**Anything else relevant?**

**Comment by wendzhue** [comment]
<img width="1267" alt="屏幕快照 2019-08-02 下午3 28 00" src="https://user-images.githubusercontent.com/12122021/62352183-21203400-b53a-11e9-93a4-22bb0951da8e.png">

**Comment by alan-agius4** [comment]
That's caused by TypeScript versions mismatch. In the `@schematics/angular` uses TypeScript 3.5 and your local TypeScript is 3.4

**Comment by wendzhue** [comment]
@alan-agius4 Yes. It seems that devkit would load `typescript.d.ts` from GitHub and cause this mismatch? I tried to downgrade devkit but no luck.

**Comment by alan-agius4** [comment]
You need to update your local TypeScript version to 3.5. `@schematics/angular` uses an internal version of TypeScript,

**Comment by wendzhue** [comment]
Thank you!
