### ISSUE TITLE
Can we split Script section in angular-cli.json

### ISSUE THREAD

**Issue by sanmscse** [angular/angular-cli#15235]
Hi,

can we split scripts section in to 
"scripts1": [],
"scripts2":[]

**i'm having an issue with loading more than 6MB script bundle files.
Its not loading when deploy in IIS Express**

@jbogarthyde , @aciccarello , @filipesilva

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
