### ISSUE TITLE
can we reload the chunk files if loading failed?

### ISSUE THREAD

**Issue by sanmscse** [angular/angular-cli#15232]
When deploy application in local server it works fine.

But when deploy it in outside of server the below issue occurs
**Error: Uncaught (in promise): Error: Loading chunk 0 failed**

![image](https://user-images.githubusercontent.com/40461278/62363221-7d845300-b53c-11e9-990f-26a8971f7d55.png)

i've used below in angular-cli.json
```
"scripts": {
    "ng": "ng",
    "start": "ng serve --extract-css",
    "build": "ng build --prod --aot --build-optimizer",
    "build:ssr": "npm run build -- --app=ssr --output-hashing=media",
    "bundle-report": "ng build --prod --stats-json && webpack-bundle-analyzer dist/stats.json",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
