### ISSUE TITLE
No declaration files generated

### ISSUE THREAD

**Issue by ammarlakis** [angular/angular-cli#15234]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Don't know, but don't think so

### Description

`ng build` doesn't generate declarations when setting ` "declaration": true ` in tsconfig.

## 🔬 Minimal Reproduction

- create a new project with `ng new testproject`
- modify the tsconfig.json to generate declarations settings `"declaration": true`
- build using `ng build`
- check dist, no `.d.ts` files generated.

## 🔥 Exception or Error

None

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.0.0
Node: 10.13.0
OS: linux x64
Angular: 8.1.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.0
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.0
@schematics/update                0.800.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

- `angular.json` does contain the reference to `tsconfig.json` in the build task definition.
- building directly with `tsc -b tsconfig.json` generated the definition files, but to the directory defined in the config file which is the expected behavior. Is `ng build` completely overriding tsconfig compilerOptions?

**Comment by alan-agius4** [comment]
Hi, that is expected because applications are non consumables (Not like libraries). As such dts files are unneeded.

What is your use case that you require dts files for applications?

**Comment by ammarlakis** [comment]
Okay. I'm working with Nrwl tools that rely on angular, but I examined the issue and concluded this is related to angular rather than Nrwl as I replicated the same issue in a new angular project.

In my project, I'm generating an sdk library with `@nrwl/workspace:lib`, which should be accompanied with the corresponding typing declarations when built.
This is the `angular.json` entry generated for this library, modified to fit my requirements:

```
    "sdk": {
      "root": "libs/sdk",
      "sourceRoot": "libs/sdk/src",
      "projectType": "library",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@nrwl/node:build",
          "options": {
            "main": "libs/sdk/src/index.ts",
            "outputPath": "dist/sdk",
            "tsConfig": "libs/sdk/tsconfig.json",
            "verbose": true
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "libs/sdk/tsconfig.lib.json",
              "libs/sdk/tsconfig.spec.json"
            ],
            "exclude": ["**/node_modules/**", "!libs/sdk/**"]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "libs/sdk/jest.config.js",
            "tsConfig": "libs/sdk/tsconfig.spec.json"
          }
        }
      }
    }
```

As you see, this is a library type project, and the `tsconfig` referenced here is set to output declarations. Angular builder gives the same result. I feel like I'm missing something here.

**Comment by alan-agius4** [comment]
Hi @ammarlakis, just checked with @FrozenPandaz who’s one of the members of NRWL core team and he confirmed that the builder you are using is not meant to be used to package and publish libraries. 

Therefore, not having dts files is expected. 

Thanks.

**Comment by alan-agius4** [comment]
I suggest you open a feature request with NRWL to add support to publish and package Node libraries.

**Comment by ammarlakis** [comment]
Just for future reference, I found what I was looking for in [angular docs](https://angular.io/guide/creating-libraries), and in the readme of angular-cli, [a builder for npm packages](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_ng_packagr).
