### ISSUE TITLE
"ERROR! .gitignore already exists" with --skipGit==true

### ISSUE THREAD

**Issue by mruizmartinez-stratio** [angular/angular-cli#15247]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 I don't know

### Description

 When you create a new project in current directory, where .gitignore exists, it throws an error, even if you flag it with --skipGit=true

I have read in other issue that maybe .gitignore should be added, even if --skipGit is true. The problem is that, actually, if you create a project with --skipGit==true, it doesn't create a .gitignore file. So it checks whether file exist, without the intention of creating one anyway.

## 🔬 Minimal Reproduction

$ ng new project-name --skipGit=true --directory ./ --commit=false

## 🔥 Exception or Error
<pre><code>
ERROR! .gitignore already exists.
The Schematic workflow failed. See above.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.1.2
Node: 10.16.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.2
@angular-devkit/core         8.1.2
@angular-devkit/schematics   8.1.2
@schematics/angular          8.1.2
@schematics/update           0.801.2
rxjs                         6.4.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
`.gitignore` will always be created even if you specify `skipGit`. 

When using `skipGit` option the actual git repository will not be initiated, but all workspace files will be created including the `.gitignore`.

**Comment by mruizmartinez-stratio** [comment]
> `.gitignore` will always be created even if you specify `skipGit`.
> 
> When using `skipGit` option the actual git repository will not be initiated. All workspace files will be created including the `.gitignore`.

That's the thing: .gitignore is not created when you use --skipGit.

<pre><code>
angular/angular-test$ ng new angular-test --skipGit=true --directory ./

angular/angular-test$ ls -a
.             e2e            node_modules       src                 tslint.json
..            .editorconfig  package.json       tsconfig.app.json
angular.json  .gitignore     package-lock.json  tsconfig.json
browserslist  karma.conf.js  README.md          tsconfig.spec.json


</code></pre>

**Comment by mruizmartinez-stratio** [comment]
> `.gitignore` will always be created even if you specify `skipGit`.
> 
> When using `skipGit` option the actual git repository will not be initiated. All workspace files will be created including the `.gitignore`.

It seems you're right. Is it any way of preventing it?

**Comment by alan-agius4** [comment]
No, and IMHO I think we shouldn't. Because users then will have copy and paste the `.gitignore` file from our schematics into their workspace. Which would be more cumbersome then just removing the original `.gitignore`.

**Comment by mruizmartinez-stratio** [comment]
> No, and IMHO I think we shouldn't. Because users then will have copy and paste the `.gitignore` file from our schematics into their workspace. Which would be more cumbersome then just removing the original `.gitignore`.

I guess you are right. I just found this isses working with repositories which already have a .gitignore.

I'll try to find a better way of installing angular there.

Thanks, I guess I should closse the issue? It's the first time I post one.
