### ISSUE TITLE
Angular CLI adds the route to the wrong line while generating a module

### ISSUE THREAD

**Issue by mehmet-erim** [angular/angular-cli#15255]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description
If routes have a route with `{path: ** ...}` in `app-routing.module`. Angular CLI adds the route to the wrong line while generating a module.

## 🔬 Minimal Reproduction
Create a new application
```bash
ng new issue-test-app --routing --style=css

cs issue-test-app
```

Add a new route in app-routing.module
```ts
const routes: Routes = [
  { path: '**', redirectTo: '/' },
];
```

Generate a module via CLI
```bash
ng generate module dashboard --route dashboard --module app.module
```

CLI added the route to the wrong line.

Edited routes:
```ts
const routes: Routes = [
  { path: '**', redirectTo: '/' },
  { path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule) },
];
```
Now, I can't access `localhost:4200/dashboard`. Angular always redirect me to `/` path.

Routes must be like below
```ts
const routes: Routes = [
  { path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule) },
  { path: '**', redirectTo: '/' },
];
```

## 🌍 My Environment
<pre><code>
Angular CLI: 8.2.0
Node: 10.16.0
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.802.0
@angular-devkit/core         8.2.0
@angular-devkit/schematics   8.2.0
@angular/cli                 8.2.0
@schematics/angular          8.2.0
@schematics/update           0.802.0
rxjs                         6.4.0
</code></pre>

**Comment by w0wka91** [comment]
Is it sufficient if we always add the newly created route to the beginning of the routes array instead of appending it to the end?

**Comment by alan-agius4** [comment]
I think that will suffice @w0wka91.

**Comment by santoshyadav198613** [comment]
Hi @alan-agius4 ,

Are you working on this, if not can I take this issue and work on it.

**Comment by alan-agius4** [comment]
@santoshyadav198613, sure take it, if you need any help let me know.

**Comment by santoshyadav198613** [comment]
oops my bad will raise a PR by tomorrow.
