### ISSUE TITLE
Terser js magle.properties build opens blank page

### ISSUE THREAD

**Issue by yugandhargangu** [angular/angular-cli#15256]
terser js options mangle.properties true will mangle the properties and method names.
But the build gives a blank page.

I don't want to expose component and service names as well its properties and function names.
But angular build exposing it and so I added terser js mangle.properties options.
but the result opens a blank page.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
