### ISSUE TITLE
How to mangle my project componets and services and its properties and function names

### ISSUE THREAD

**Issue by yugandhargangu** [angular/angular-cli#15257]
I am using angular 7 project.

If I use service name as "UserService" and the function name "getUserDetails()" then the production build is not mangling the names. It's clearly exposing the names.
Also component name as "UserComponent" and proertyname as "_userService" then also he production build is not mangling the names.

Is there any way that we could mangle all the properties and function also in production build?

My files:

angular.json 
       "build": {
          "builder": "@angular-devkit/build-angular:browser-custom-terser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": ["src/assets", "src/.htaccess"],
            "styles": ["src/styles.scss"],
            "scripts": [
            ],
            "es5BrowserSupport": true
          },
          "configurations": {
            "production": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.prod.ts"
              }],
              "optimization": true,
              "outputHashing": "none",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": true,
              "budgets": [{
                "type": "initial",
                "maximumWarning": "2mb",
                "maximumError": "5mb"
              }]
            }
          }
        },

**Comment by clydin** [comment]
Within a project using the provided builders (not custom), names are mangled when optimization is set to true within a configuration and that configuration is used to perform the build.  In the above case that would be `ng build --prod`; assuming the officially support browser builder is used.  Please provide the test methodology used to determine that the names are not mangled as well as output samples and a reproduction if possible.

Please also be aware that without the information provided in the issue template (which appears to have been completed removed from the above issue submission as well as the previously closed issue), it is quite difficult to provide assistance.

**Comment by yugandhargangu** [comment]
I used the built-in angular builder only. Not any custom build tools.

One sample output from main.js production file is as below.

ContactListComponent is name of component class name. It is clearly visible in chrome network tool after beautification. _userService, _contactsService are services and those also visible after beatification with same tool. Also find it in attachment image.
![Screenshot from 2019-08-06 18-07-30](https://user-images.githubusercontent.com/13742390/62541254-1554aa80-b877-11e9-8bf0-2ed5cac47112.jpg)


```
t.ContactListComponent = function() {
            function e(e, t, n, l) {
                this._utils = e,
                this._userService = t,
                this._contactsService = n,
                this._authGatewayService = l,
                this.newListFlag = !1,
                this.selectedLists = []
            }
            return e.prototype.ngOnInit = function() {
                this.isCurrentUserAdmin() && this.getUsers()
            }
            ,
            e.prototype.isCurrentUserAdmin = function() {
                return this._authGatewayService.user.userType == l.Roles.ADMIN
            }
            ,
            e.prototype.ngAfterViewInit = function() {
                $(document).on("click", ".panel-open", function(e) {
                    e.preventDefault(),
                    $(".slide-panel").addClass("is-visible")
                }),
                $(document).on("click", ".slide-panel", function(e) {
                    ($(e.target).is(".slide-panel") || $(e.target).is(".panel-close")) && ($(".slide-panel").removeClass("is-visible"),
                    e.preventDefault())
                })
            }
            ,
            e.prototype.toggleNewListFLag = function() {
                this.newListFlag = !this.newListFlag
            }
            ,
            e.prototype.onContactsListsChange = function(e) {
                -1 === this.selectedLists.indexOf(e.id) ? this.selectedLists.push(e.id) : this.removeListFromSelected(e)
            }
            ,
            e.prototype.removeListFromSelected = function(e) {
                this.selectedLists.splice(this.selectedLists.indexOf(e.id), 1)
            }
            ,
            e.prototype.assignListsToUser = function(e) {
                var t = this;
                this._utils.showConfirm("Are you sure?", "You are assigning multiple contact lists to user", function() {
                    t._utils.showLoading(),
                    t._contactsService.assignMultipleListsToUser({
                        userid: e
                    }, t.selectedLists).subscribe(function(e) {
                        t._utils.hideLoading(),
                        null != e && (t.getUsers(),
                        t._utils.success("Lists Assigned to User", "Success"))
                    }, function(e) {
                        t._utils.hideLoading(),
                        t._utils.error("Unable to assign,Please Try again", "Error")
                    })
                }, function() {
                    return ""
                })
            }
            ,
            e.prototype.getUsers = function() {
                var e = this;
                this._userService.getSubUsers().subscribe(function(t) {
                    e.users = t
                }, function(e) {})
            }
            ,
            e
        }()
    }
```

**Comment by clydin** [comment]
`@angular-devkit/build-angular:browser-custom-terser` is not the built-in Angular browser builder.

Also please provide the information requested in the issue template.  The output of `ng version` is critical as is repeatable reproduction steps (or please provide a minimal reproduction).  Without this information further assistance will not be possible.

**Comment by yugandhargangu** [comment]
Sorry,

That was my mistake.
Here is the original angular.json content.

angular.json
"build": {
"builder": "@angular-devkit/build-angular:browser",
"options": {
"outputPath": "dist",
"index": "src/index.html",
"main": "src/main.ts",
"polyfills": "src/polyfills.ts",
"tsConfig": "src/tsconfig.app.json",
"assets": ["src/assets", "src/.htaccess"],
"styles": ["src/styles.scss"],
"scripts": [
],
"es5BrowserSupport": true
},
"configurations": {
"production": {
"fileReplacements": [{
"replace": "src/environments/environment.ts",
"with": "src/environments/environment.prod.ts"
}],
"optimization": true,
"outputHashing": "none",
"sourceMap": false,
"extractCss": true,
"namedChunks": false,
"aot": true,
"extractLicenses": true,
"vendorChunk": true,
"buildOptimizer": true,
"budgets": [{
"type": "initial",
"maximumWarning": "2mb",
"maximumError": "5mb"
}]
}
}
}


ng version output:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 10.16.0
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0

**Comment by alan-agius4** [comment]
Hi @yugandhargangu, I am still unable to reproduce the issue. I am seeing quite a number of mismatches between your production configuration and the screenshot provided above.

Such as, `outputHashing` is set to `none`, but in your screenshot outputs are hashed, `vendorChunk` is set to `true`, but no vendor chunk is present.

Hence, at this point I cannot say which configuration you are using.  Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

Thanks

**Comment by clydin** [comment]
Also of note is that if the only elements that are not mangled are properties of objects (and without a reproduction this cannot be confirmed), then the behavior is intended.
The `mangle.properties` [terser option](https://github.com/terser-js/terser#cli-mangling-property-names---mangle-props) is considered a dangerous and code-breaking option and should only be used on tightly controlled and audited code (i.e., not third-party libraries).  To perform effective minification of an application it must be performed on the final output code bundles of the application and therefore this makes the use of the above option impossible.

**Comment by yugandhargangu** [comment]
I have created one sample in github and link as below.
https://github.com/yugandhargangu/ng-mangle-sample

![Screenshot from 2019-08-09 21-20-08](https://user-images.githubusercontent.com/13742390/62791780-7f758580-baeb-11e9-9599-af163beadbda.png)

I have created component with 
_indexService which is injectable of IndexService,
users is a variable in component ,
getTitle() is a method in component. 

But these all are not mangled as it is in screenshot.
I want these all are should mangle so it can not be readable in the browser.

**Comment by alan-agius4** [comment]
Hi, from your reproduction it seems that only properties are not being mangled which as @clydin explained above is expected as mangling of property names can be dangerous as it might break the application. 

Most likely you can enable properties mangling by extending the build config using 3rd party builders which provide you with the option to extend the webpack configuration that the CLI provides. However, it is important to point out that this will put you on the unsupported path.

**Comment by yugandhargangu** [comment]
Hi @alan-agius4,

Thank you for your great explanation.
I will try custom build for that. But I need to mangle all component properties and methods to secure my code. My understanding is that the angular default build is not doing that for me.
In the least case, I may have to switch to React or Vue to achieve it.

**Comment by clydin** [comment]
Please note that the intended goal of mangling is to reduce file size and not to secure code.  If there is logic that should not be accessible to a client then it may be better placed behind a server-side API.

Both [Vue.js](https://github.com/vuejs/vue-cli/blob/master/packages/@vue/cli-service/lib/config/terserOptions.js) and [React](https://github.com/facebook/create-react-app/blob/efaee65e9068277dbf71c4b28811d80736996f2b/packages/react-scripts/config/webpack.config.js#L234) do not enable this option either.  The option has a high probability of causing a broken application.
