### ISSUE TITLE
build --watch on library does not include import of String.prototype.func when rebuilding

### ISSUE THREAD

**Issue by sameerbk** [angular/angular-cli#15261]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 
Yes, the previous version in which this bug was not present was: 7.2.13

### Description

 
When running a 'build --watch' on a library project, the **rebuild** of the library project on any change does not import the string extension method e.g. String.prototype.func from another file. 

Initial build properly imports the function from the file and it works well. 
The function is only lost on the rebuild of the library project. 

## 🔬 Minimal Reproduction

The github repo contains an angular workspace with a library `test-lib` and an application that uses the library. The library has file [string-extension.ts](https://github.com/sameerbk/angular-lib-extn-method/blob/master/projects/test-lib/src/lib/string-extension.ts) with an interface and the string extension method defined.
```
interface String {
    beginsWithOne: () => boolean;
}
String.prototype.beginsWithOne = function(): boolean {
...
};
```

The function is imported by [test-lib.component.ts](https://github.com/sameerbk/angular-lib-extn-method/blob/master/projects/test-lib/src/lib/test-lib.component.ts) library component by

`import './string-extension';`

and later used in the component. 
On initial build of the library, this function is included in the `dist\test-lib\fesm2015\test-lib.js` and other files, Then on the rebuild of the library, this function is not imported, causing the error below.

**Steps to reproduce this bug.**

1.  Clone the repo from https://github.com/sameerbk/angular-lib-extn-method.git
2.  Install the required packages by running `npm install`
3.  Build the library using watch : `ng build test-lib --watch`
4.  On another command prompt in the same folder,  serve the application to consume the library `npm start`
5.  Type `1222 ` in the text box, observe that `Result : false` changes to `Result : true`
6.  Observe that no errors are reported in the console.
7.  Now make a small modification in the library code to cause a rebuild of the library. e.g. remove the `!` from the line 7 of [test-lib.component.ts](https://github.com/sameerbk/angular-lib-extn-method/blob/master/projects/test-lib/src/lib/test-lib.component.ts#L7) 
8.  Observe that the library and the application is rebuilt and loaded in the browser.
9. Type `1222 ` in the text box, observe that `Result : false` does not change
10. Observe error is reported in the console.
11. Stopping and restarting the 'ng build --watch' and ng serve from step 3 and 4, resolves the error.

## 🔥 Exception or Error

The function beginsWithOne() is defined in the string-extension.ts file imported in test-lib.component.ts. 
<pre><code>

ERROR TypeError: value.beginsWithOne is not a function
    at TestLibComponent.onKey (test-lib.js:21)
    at Object.eval [as handleEvent] (TestLibComponent.html:4)
    at handleEvent (core.js:36798)
    at callWithDebugContext (core.js:38416)
    at Object.debugHandleEvent [as handleEvent] (core.js:38052)
    at dispatchEvent (core.js:24366)
    at core.js:35730
    at HTMLInputElement.<anonymous> (platform-browser.js:1790)
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:32874)
View_TestLibComponent_0 @ TestLibComponent.html:4
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.2.0
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-next.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.0
@angular-devkit/build-angular      0.802.0
@angular-devkit/build-ng-packagr   0.802.0
@angular-devkit/build-optimizer    0.802.0
@angular-devkit/build-webpack      0.802.0
@angular-devkit/core               8.2.0
@angular-devkit/schematics         8.2.0
@angular/cli                       8.2.0
@ngtools/webpack                   8.2.0
@schematics/angular                8.2.0
@schematics/update                 0.802.0
ng-packagr                         5.4.3
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.38.0
</code></pre>
**Anything else relevant?**

This issue happens on angular cli ver 8.1.3 as well.

**Comment by sameerbk** [comment]
On comparing the good build and the bad rebuild, I see that the files `dist\test-lib\bundles\test-lib.umd.js ` and `dist\test-lib\fesm5\test-lib.js` are missing the function `String.prototype.beginsWithOne` in the bad rebuild

**Comment by alan-agius4** [comment]
Hi, I'm sorry, but this issue is not caused by Angular CLI. But it is caused by `ng-packagr`. I open a new issue with the contents of this issue in their issue tracker.

https://github.com/ng-packagr/ng-packagr/issues/1367

Thanks.
