### ISSUE TITLE
Conflicting build chunk size

### ISSUE THREAD

**Issue by KishoreBarik** [angular/angular-cli#15267]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
Facing issue with main.js bundle chunk size. Particularly rxjs. (Relates to #9069 )

![image](https://user-images.githubusercontent.com/13726932/62603510-ada06d00-b913-11e9-9774-6cfdb2014c23.png)

Environment:

![image](https://user-images.githubusercontent.com/13726932/62603543-c3159700-b913-11e9-9bbc-acab3e8583a3.png)

**Note**
Earlier I was seeing the left panel (900+ KB) was occupied by polyfills(at that time Size of Rx was nearly 53KB). So to solve [this](https://github.com/angular/angular/pull/16805) I found out I had to mention `"es5BrowserSupport": true` in angular.json and commented all imports in polyfills.ts except `import "zone.js/dist/zone";`. 
Now I am seeing similar amount of size is being taken by RxJs. If I uncomment the polyfill imports the RxJs is back to around 53 KB but polyfills take 900+KB.
![image](https://user-images.githubusercontent.com/13726932/62605210-38369b80-b917-11e9-9d1e-55d68b619626.png)

**Comment by KishoreBarik** [comment]
RxJs when polyfills are addded back.

![image](https://user-images.githubusercontent.com/13726932/62647591-7f9c4680-b96e-11e9-9e61-4979e65125f2.png)

**Comment by alan-agius4** [comment]
Hi @KishoreBarik, does the issue persist when updating to the latest versions of Angular CLI (8.2.x)?

Also, can you kindly provide a reproduction that we can look at? A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by KishoreBarik** [comment]
Hi @alan-agius4 
I tried updating Angular CLI  to 8.2.x, but build was failing and found out following the error that angular core also needs to be updated to 8.x. Our team is not in a position to upgrade the project to 8.x.  So I tried to create a [repo](https://github.com/KishoreBarik/ng-build-chunk/) to reproduce the error.

Reproduce steps are little different now. Pollyfills has been via angular.json (The actual project was upgraded from older angular, so polyfills were being added in main.ts).   Please follow the Readme of the repo for reproduce steps.
Feel free to commit fixes. 
Thanks.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
