### ISSUE TITLE
build hangs then crashed  when webworker creates new instances of itself 

### ISSUE THREAD

**Issue by myrddraall** [angular/angular-cli#15268]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
N/A

### Description

 A clear and concise description of the problem...
When a webworker creates a new worker of the same file the compiler get suck when compiling that file(presumably its suck in an infinite loop)

## 🔬 Minimal Reproduction

create a new cli project and generate a webworker named 'webworker-test'
In the webworker add the code below then try to build or serve the project

<pre><code>

class WorkerTest{
  spawn(){
    const worker = new Worker('./webworker-test.worker', { type: 'module' });
  }
}
</code></pre>

## 🔥 Exception or Error
<pre><code>

30% building 44/45 modules 1 active ...\src\app\webworker-test.worker.ts
<--- Last few GCs --->

[22620:0000022F26191F00]   222583 ms: Scavenge 1322.9 (1424.4) -> 1322.4 (1424.4) MB, 3.3 / 0.0 ms  (average mu = 0.305, current mu = 0.327) allocation failure
[22620:0000022F26191F00]   222597 ms: Scavenge 1322.9 (1424.4) -> 1322.4 (1424.9) MB, 3.9 / 0.0 ms  (average mu = 0.305, current mu = 0.327) allocation failure
[22620:0000022F26191F00]   222616 ms: Scavenge 1323.4 (1424.9) -> 1322.5 (1425.4) MB, 3.4 / 0.0 ms  (average mu = 0.305, current mu = 0.327) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000033EE3CDC5C1]
Security context: 0x03431bc1e6e9 <JSObject>
    1: checkFunctionOrConstructorSymbol(aka checkFunctionOrConstructorSymbol) [00000028B12180E9] [...\node_modules\typescript\lib\typescript.js:~53807] [pc=0000033EE524DA5D](this=0x03dc00f826f1 <undefined>,symbol=0x02db5a428ec1 <SymbolObject map = 0000030AC7483541>)
    2: checkFunctionOrMethodDeclaration(aka checkF...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF69C2BC6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF69C297416 node::MakeCallback+4534
 3: 00007FF69C297D90 node_module_register+2032
 4: 00007FF69C5B189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF69C5B17CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF69C797F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF69C78EF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF69C78D5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF69C796317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF69C796396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF69C8C0637 v8::internal::Factory::NewFillerObject+55
12: 00007FF69C93D826 v8::internal::operator<<+73494
13: 0000033EE3CDC5C1
</code></pre>

## 🌍 Your Environment
<pre><code>

  _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.2
Node: 10.16.0
OS: win32 x64
Angular: 8.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.2
@angular-devkit/build-angular      0.801.2
@angular-devkit/build-ng-packagr   0.801.2
@angular-devkit/build-optimizer    0.801.2
@angular-devkit/build-webpack      0.801.2
@angular-devkit/core               8.1.2
@angular-devkit/schematics         8.1.2
@angular/cdk                       8.1.1
@angular/material                  8.1.1
@angular/platform-webworker        8.1.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.2
@schematics/angular                8.1.2
@schematics/update                 0.801.2
ng-packagr                         5.3.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.35.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
