### ISSUE TITLE
Angular compiler option preserveWhitespaces: true does not work in version 8.1.1

### ISSUE THREAD

**Issue by suhailkc** [angular/angular-cli#15271]
**`"preserveWhitespaces": true`  is not working in version 8.1.1**

(Bootstrap button have no spacing)

Angular CLI: 8.1.1
Node: 12.2.0

tsconfig.app.json
`"angularCompilerOptions": {
  "preserveWhitespaces": true
},`

main.ts
`platformBrowserDynamic().bootstrapModule(AppModule, {
  preserveWhitespaces: true
})
.catch(err => console.log(err));`

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by alan-agius4** [comment]
Hi thanks for reporting this, however please also be aware that without the information requested in the issue template, it is quite difficult to provide assistance.

I suggest that you open and new issue and provide all the requested information together with a minimal reproduction.

Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Thanks.
