### ISSUE TITLE
Error accessing https://stats.pagefair.com/stats/page_view_event from polyfills-es2015

### ISSUE THREAD

**Issue by CFHoo** [angular/angular-cli#15279]
# 🐞 bug report

### Affected Package
CLI generated polyfills-es2015.js

### Is this a regression?

 No

### Description

 Two errors can be viewed from Chrome Browser Console
polyfills-es2015.js:1 GET https://stats.pagefair.com/stats/page_view_event/19D89FBE4AB144C4/a.js?wl_div_hid_t0=0&div_hid_t0=0&wl_i_blk=0&s_blk=0&i_blk=0&is_ab=0&is_wl=1&_=1565144920455 503 (Service Unavailable: Back-end server is at capacity)
k @ polyfills-es2015.js:1

(index):1 Access to XMLHttpRequest at 'https://stats.pagefair.com/stats/page_view_event/19D89FBE4AB144C4/a.js?wl_div_hid_t0=0&div_hid_t0=0&wl_i_blk=0&s_blk=0&i_blk=0&is_ab=0&is_wl=1&_=1565144920455' from origin 'https://www.monster.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

## 🔬 Minimal Reproduction

 Browse to https://www.monster.com/company/profiles/1-800-GOT-JUNK-Pittsburgh/
Open browser console to view error

## 🔥 Exception or Error
<pre><code>

polyfills-es2015.js:1 GET https://stats.pagefair.com/stats/page_view_event/19D89FBE4AB144C4/a.js?wl_div_hid_t0=0&div_hid_t0=0&wl_i_blk=0&s_blk=0&i_blk=0&is_ab=0&is_wl=1&_=1565144920455 503 (Service Unavailable: Back-end server is at capacity)
k @ polyfills-es2015.js:1

(index):1 Access to XMLHttpRequest at 'https://stats.pagefair.com/stats/page_view_event/19D89FBE4AB144C4/a.js?wl_div_hid_t0=0&div_hid_t0=0&wl_i_blk=0&s_blk=0&i_blk=0&is_ab=0&is_wl=1&_=1565144920455' from origin 'https://www.monster.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.2
Node: 10.15.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.2
@angular-devkit/core         8.0.2
@angular-devkit/schematics   8.0.2
@schematics/angular          8.0.2
@schematics/update           0.800.2
rxjs                         6.4.0
</code></pre>

**Anything else relevant?**

Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
