### ISSUE TITLE
Angular 8 routing with serve-path and deploy-url is broken on refresh

### ISSUE THREAD

**Issue by eplatzek** [angular/angular-cli#15295]
# 🐞 bug report

### Affected Package
angular/*@8.0.6

### Is this a regression?
This used to work in:
angular/*@7.2.4

### Description

When using the "serve-path" and "deploy-url" with ng serve, the live reload is broken for routing upon a reload.

## 🔬 Minimal Reproduction
Repository here:
https://github.com/eplatzek/ng8reloadbug/

Steps to reproduce (using new projects): Using angular/cli @ 8.0.6
ng new ng8
ng g c my-component  

update app.component.ts to:
```
constructor(private router: Router) {
  this.router.navigate(['my-route']);
}
```

  update app-routing.module.ts to: 
```
 const routes: Routes = [
  {
    path: 'my-route',
    component: MyComponentComponent
  }
];

@NgModule({
  imports: [RouterModule.forRoot(routes, { useHash: true })],
  exports: [RouterModule]
})
```

update package.json:

 ```”start": "ng serve --aot --serve-path /my-app/ --deploy-url /my-app/“,```

Run Yarn start.
Navigate to:  http://localhost:4200/my-app. The user is redirected to: http://localhost:4200/#/my-route by the app component.
  On page reload at http://localhost:4200/#/my-route, the page displays “Cannot GET /“.
 The network tab of the dev tools shows a 404 for http://localhost:4200/.

Doing the same exact steps for angular/cli @ 7.2.4 will produce a working page refresh.

## 🔥 Exception or Error
<pre><code>
“Cannot GET /“
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.6
Node: 10.12.0
OS: darwin x64
Angular: 8.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.0.6
@angular/cli                      8.0.6
@ngtools/webpack                  8.0.6
@schematics/angular               8.0.6
@schematics/update                0.800.6
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Comment by clydin** [comment]
The behavior described in the original post is intended.  With the options specified, the application is being served from `http://localhost:4200/my-app/`.  There is nothing being served from `/`.  Redirect rules for path based routing are based on the serving path of the application in 8.0+.

Also of note is that the serve path defaults to a combination of the `base-href` and `deploy-url` options based on whether they are relative, root relative, or absolute.  In this case, for instance, `--serve-path /my-app/ --deploy-url /my-app/` is equivalent to `--deploy-url /my-app/`.

The reason this worked previously is that the path based routing redirection was redirecting everything back to the serve path of the application which is incorrect.  Only URLs that are within the application should be redirected up to the root of the application (the serve path).

This is also in fact related to routing in that the HTML base HREF is used to configure the routing base of the application.  The router will prepared the base HREF to the route to ensure that the URL is within the scope of the application.

For development, it is generally easier to avoid use of any of these options and serve/access the application from the root of localhost (`http://localhost:4000/`).  These options are mainly intended to allow the built application to adapt to deployment server infrastructure and configuration.

**Comment by MarcelNeu** [comment]
@clydin thank you for clarifying. 
Then i keep my changes as solution not as workaround.

**Comment by alan-agius4** [comment]
Closed as it seems to have been resolved.
