### ISSUE TITLE
CLI Webpack release transition guide urls

### ISSUE THREAD

**Issue by jbeckton** [angular/angular-cli#1529]
FYI...

The urls that come up when there is an error are invalid.

https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition

**Comment by juristr** [comment]
Seems to be some remains from the [Ember CLI](https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md)

**Comment by filipesilva** [comment]
Can you give more details? I don't understand what the problem is and your link is broken.

**Comment by juristr** [comment]
That's exactly the issue, namely that the link reported by @jbeckton pops up in the console, and that link is broken.

**Comment by jbeckton** [comment]
Correct... I saw that link in the terminal window while using the CLI tool. I think I got an error or something using the webpack branch.

**Comment by filipesilva** [comment]
Ok, I understand it better now. When does this link show up? Can you give me repro steps?

**Comment by hansl** [comment]
Closing this as obsolete.
