### ISSUE TITLE
Invalid rule result: Instance of class Promise. ng add @angular/pwa

### ISSUE THREAD

**Issue by dcolakchile** [angular/angular-cli#15290]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [X] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No idea.

### Description

Unable to add PWA to a clean project made from scratch.

## 🔬 Minimal Reproduction

ng new appname
cd appname
ng add @angular/pwa

## 🔥 Exception or Error
<pre><code>
Installing packages for tooling via npm.
npm WARN ajv-keywords@3.4.1 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

+ @angular/pwa@0.802.1
added 10 packages from 9 contributors and audited 40817 packages in 6.241s
found 3 vulnerabilities (2 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
Invalid rule result: Instance of class Promise.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.1.4
Node: 10.16.2
OS: darwin x64
Angular: 8.2.1
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.11.4
@angular-devkit/build-angular       0.11.4
@angular-devkit/build-optimizer     0.11.4
@angular-devkit/build-webpack       0.11.4
@angular-devkit/core                7.1.4
@angular-devkit/schematics          7.1.4
@angular/animations                 7.1.4
@angular/cdk                        8.1.2
@angular/cli                        7.1.4
@angular/common                     7.1.4
@angular/compiler                   7.1.4
@angular/compiler-cli               7.1.4
@angular/forms                      7.1.4
@angular/language-service           7.1.4
@angular/material                   8.1.2
@angular/platform-browser           7.1.4
@angular/platform-browser-dynamic   7.1.4
@angular/pwa                        0.802.1
@angular/router                     7.1.4
@ngtools/webpack                    7.1.4
@schematics/angular                 7.1.4
@schematics/update                  0.11.4
rxjs                                6.3.3
typescript                          3.1.6
webpack                             4.23.1

</code></pre>

**Anything else relevant?**

This is RIDICULOUS, CLEAN SLATE, PROJECT FROM ZERO and your system fights itself.

**Comment by alan-agius4** [comment]
Hi, you seem to be using an older version of the CLI.

Before running the above commands, kindly update the global CLI.

```
npm install @angular/cli -g
```

**Comment by alan-agius4** [comment]
Closing as no further feedback was provided from the issue reporter.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem.
