### ISSUE TITLE
@angular-devkit/build-angular removes custom library decorators from another libraries on production build

### ISSUE THREAD

**Issue by abadakhshan** [angular/angular-cli#15301]
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

I define  some decorators on one of my libraries  and use them a lot on other libraries.
When I build my application with --prod  Angular compiler removes using of them in generated code.

This problem occurs with **@angular-devkit/build-angular@0.802.0** and I have  no problem with **@angular-devkit/build-angular@0.801.3**

**Comment by abadakhshan** [comment]
I created a repository for demo

https://github.com/abadakhshan/test-build-angular

I have a decorator on "narik-core"  (@NarikInject). 
every @NarikInject used in "test-build-angular" source, works fine but those that used in libraries
(for example in "narik-core" and "narik-app-code") do not work at all.

If I change  **"@angular-devkit/build-angular" to "0.801.3"** and **"typescript" to  "3.4.5"** everything is OK.

This happens on `ng build --prod` and there is no problem on `"ng serve"`

**Comment by alan-agius4** [comment]
Similar things have also been reported here: https://github.com/ng-packagr/ng-packagr/issues/1307
