### ISSUE TITLE
De-Optimize bundle size when needed. Lazy Loading, common.js

### ISSUE THREAD

**Issue by andreElrico** [angular/angular-cli#15307]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] build
```

my feature request would be a regression of this feature: https://github.com/angular/angular-cli/issues/6204

When I declare "stuff" (pipes, directives, components, services) in **AT LEAST TWO** lazy loaded modules a optimization takes places and the "stuff" ends up in **common.js** bundle.

That's desired in most cases, but ...

### Description

Lets take this architecture:

```
root.module

lazy1.module
    secretComponent
    secretDirective

lazy2.module
    secretComponent
    secretDirective
```

this will result in

```
common.js
    secretComponent
    secretDirective
```

my **desired outcome** would be redundant code duplication:

```
no secrets in common.js

lazy1.chunk.js
    secretComponent
    secretDirective

lazy2.chunk.js
    secretComponent
    secretDirective
```

The trivia behind this is that my webserver can block the serving of lazyModules based on auth. and I don't want unauth. users to get the sources for `secret.* "stuff"`.

How can I control what "stuff" lands inside common.js.

### Describe the solution you'd like

My first reaction would be an additional parameter in the modules decorator:

```
. . .
  declarations: [ 
    secretComponent
    secretDirective],
  imports: [MaterialModule],
  providers: [
    secretService
  ],
  bootstrap: [secretComponent],

  keepInModule: [
    secretComponent,
    secretDirective,
    secretService,
  ]
. . .
```

Code declarations that are always added to `keepInModule` will not end up in common.js but will be duplicated to the lazyModulesChunks.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Not sure how to archive this with angular-cli

### Some thoughs :boom: 

Since we could provide a service `secretService` solely in let say "secretComponent" we probably need something like `keepInComponent` ... not sure how to handle this case ...

**Comment by clydin** [comment]
The option to turn off deduplication of modules is `--commonChunk=false`.  Note that scripts may be significantly larger, `instanceof` may give false negatives, and there may be multiple instances of services originating from the same code.

Also, this is completely outside of the scope of Angular itself as it is the bundler (in this case webpack) that makes the code-splitting decisions.  Be aware that differing versions of the bundler and configuration thereof may place modules in differing output scripts regardless of the above setting.

**Comment by andreElrico** [comment]
Hey @clydin im using the angular cli. There is `--commonChunk=true|false` for the cli. Is that doing what you are proposing above? I have no experience with custom webpack configs. Not even sure how i can do this with an CLI app.

**Comment by clydin** [comment]
That would be the option to control the use of the common chunk.  It can be used via the command line or added to the application's build options in `angular.json`.  Please be aware that module placement cannot be guaranteed across versions.  SPAs by definition send the application code to the client.  If logic should remain hidden from clients then placing the logic on a server-side access controlled API may be an option.  This is however outside the scope of Angular and the CLI.
