### ISSUE TITLE
Angular 8.0.3 / Angular CLI 8.0.3 unit tests work but since Angular CLI 8.0.4 they failed

### ISSUE THREAD

**Issue by bougnat12** [angular/angular-cli#15308]
After migrating to Angular 8.2.1 / CLI 8.2.1 to my unit tests suite failed with:

`An error was thrown in afterAll TypeError: Object prototype may only be an Object or null: undefined
`
I created my app a long time ago with Angular 2 and I never add any problem with migrations.

What has changed between Angular CLI 8.0.3 and 8.0.4 that could explain this issue please?

I talked with Cédric Exbrayat (because I'm French like him ;-)) and he thought it's in the webpack tool but he is not sure.

The dev and prod code work well. Only some tests failed. For example all my Angular 8 widgets and pipes tests are OK.

Any help is welcome. I already opened a question in Stackoverflow but nobody has helped me yet.

I have this issue even if I used the xdescribe() so I think the issue came only from the global import context but why I cannot trap (and where?) the afterAll issue to ignore it if it's the only workaround.

Regards

**Comment by alan-agius4** [comment]
Hi @bougnat12,

Unfortunately without a reproduction it's hard to tell what's happening.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by bougnat12** [comment]
@alan-agius4 

I reduced our big app to a minimal one to reproduce the issue.

As I work with gitlab, I just extract a minimal zip file. I hope it will be sufficient...

[repro-app.zip](https://github.com/angular/angular-cli/files/3493479/repro-app.zip)

**Comment by alan-agius4** [comment]
Hi @bougnat12,

I just had a look at this, and it seems that in some places you are trying to access `Model` before it's initialisation.

Tip: if you update the compilation target to ES2015, you should get more meaningful errors.

Closing as this doesn't appear to be an Angular CLI bug.
