### ISSUE TITLE
Enable specifying detailed options for statsJson

### ISSUE THREAD

**Issue by kimamula** [angular/angular-cli#15302]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Currently Angular CLI only accepts `true` or `false` for the `statsJson` option, which results in a very large (verbose) `stats.json` when it is set to `true`.
However, sometimes only a part of the stats is needed.
It would be nice if one can specify detailed options for `statsJson` like as written in https://webpack.js.org/configuration/stats/.

**Comment by alan-agius4** [comment]
Hi @kimamula, 

Thanks for this feature request. 

Exposing Webpack specific options is not in scope of the Angular CLI. The fact that the Angular CLI uses Webpack is an implementation detail.
