### ISSUE TITLE
AsyncTestZoneSpec is needed for the async() test helper

### ISSUE THREAD

**Issue by BenRacicot** [angular/angular-cli#15315]
# 🐞 Bug report
Running a single unit test with: `ng test --main src/app/any.component.spec.ts` causes an unexpected error where running all tests with `ng test` runs without error.

### Command (mark with an `x`)
```
- [x] test
```

### Is this a regression?
Yes, running single .spec files with `--main` typically ran the tests within that file.

## 🔬 Minimal Reproduction
create a new project (Angular 8.2.1) with `ng new project`
run `ng test --main src/app/app.component.spec.ts`

## 🔥 Exception or Error

> Error: AsyncTestZoneSpec is needed for the async() test helper but could not be found. Please make sure that your environment includes zone.js/dist/async-test.js

## 🌍 Your Environment
Chrome 76
MacOS 10.14.6
Angular CLI: 8.2.1
Node: 12.8.0
OS: darwin x64
Angular: 8.2.1

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0

**Anything else relevant?**
I created a [StackOverflow](https://stackoverflow.com/q/57465921/1440240) question after finding nothing on this error. A few hours later I realize that this should be running the single test with expected pass/fail results.

**Comment by alan-agius4** [comment]
Hi, the failure is expected as the `main` option is not intended to be used to run a single spec file. But rather the name of the entrypoint file which must contain the testing setup.

To run a single spec file you need to use the `--include` option.

More info here: https://angular.io/cli/test

Thanks.

**Comment by brunojcm** [comment]
Some projects generated a long time ago might present this error even with plain `ng test` due to the `import 'zone.js/dist/zone-testing'` missing in the `src/test.ts` file.
Please check [this answer in SO](https://stackoverflow.com/questions/52535504/test-generated-by-angular-cli-fails-if-in-a-specific-folder/57524041#57524041) if you found this issue with such a problem.
