### ISSUE TITLE
Tests are not running with Angular Module specific providedIn-Dependency mechanism

### ISSUE THREAD

**Issue by ENM1989** [angular/angular-cli#15310]
Copied from https://github.com/karma-runner/karma/issues/3350

### Expected behaviour
Tests should run.

### Actual behaviour
Tests are not running.

### Environment Details
- Karma version: 4.2.0

### Steps to reproduce the behaviour
1. Provide a service within a specific Module `@Injectable({providedIn: MyModule})`
2. Run the tests with "ng test"
3. Karma will not run any further than "[middleware:source-files]: Fetching /_karma_webpack_/vendor.js"

4. Try the same with `@Injectable({providedIn: 'root'})` and the tests will run.

**Comment by alan-agius4** [comment]
Hi, @ENM1989,

Are you registering the module in your spec file example?
```ts
  beforeEach(() => TestBed.configureTestingModule({
    imports: [
      MyModule
    ]
  }));
```

I quickly tried to reproduce this and I am unable to;

Here's my code.

foo.service.ts
```ts
import { Injectable, NgModule } from '@angular/core';

@NgModule()
export class MyModule {
}

@Injectable({
  providedIn: MyModule
})
export class FooService {
  constructor() {}
}
```

foo.service.spec.ts
```ts
import { TestBed } from '@angular/core/testing';

import { FooService, MyModule } from './foo.service';

describe('FooService', () => {
  beforeEach(() => TestBed.configureTestingModule({
    imports: [
      MyModule
    ]
  }));

  it('should be created', () => {
    const service: FooService = TestBed.get(FooService);
    expect(service).toBeTruthy();
  });
});
```

If the problem persists, please provide a reproduction. A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
