### ISSUE TITLE
Running tests for "lib" and "src" in one command.

### ISSUE THREAD

**Issue by shashankvivek** [angular/angular-cli#15312]
# 🚀 To run entire angular `spec` tests in one go.

- [X] test

I have project structure with `lib` in it something like : 

```
workspace
 - projects
   - library-name
     - src
       - lib
         - component.ts
         - component.spec.ts
       - test.ts
     - karma.config.ts
 - src
   - app
     - app.component.ts
     - app.component.spec.ts
   - karma.config.ts
 - angular.json
```

### The solution I'd like

I am unable to run both spec files (`app.component.spec.ts` and `component.spec.ts`)  with below commands:

`ng test && ng test example-ng6-lib` 

It runs only `app.component.spec.ts`

`ng test example-ng6-lib && ng test`

It runs only `component.spec.ts`

**Comment by alan-agius4** [comment]
Hi, that is because by default the `test` command is run in watch mode and the first process will never terminate to continue to the second one.

The command that you are looking for is;
```
ng test --no-watch
```

**Comment by shashankvivek** [comment]
@alan-agius4 : I tried `ng test --no-watch` , i got below error:

```
Architect commands with multiple targets cannot specify overrides.'test' would be run on the following projects: example-ng6-lib-app,example-ng6-lib
Error: Architect commands with multiple targets cannot specify overrides.'test' would be run on the following projects: example-ng6-lib-app,example-ng6-lib
```

Then I ran, 

 `   ng test example-ng6-lib-app example-ng6-lib --no-watch`

which just runs `app.component.spec.ts` .

**Comment by alan-agius4** [comment]
Most likely you are using a version which didn't support the first command.

Try

```
ng test example-ng6-lib-app --no-watch && ng test example-ng6-lib --no-watch
```

**Comment by shashankvivek** [comment]
@alan-agius4 : It worked. Thanks 👍
