### ISSUE TITLE
Error reporting for angular8 and other versions running in the yarn environment，Uncaught Error: Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by BerQin** [angular/angular-cli#15317]
# 🐞 Bug report

### Command (mark with an `x`)
The ng server's post-run page error, is to use lerna bootstrap under the jar package management, will report Uncaught Error: Expected 'styles' to be an array of strings.
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
Yarn allows the runtime to report an error in the browser: ``compiler.js:5476 Uncaught Error: Expected 'styles' to be an array of strings.``

## 🔬 Minimal Reproduction
1、ng new project --style=scss
2、yarn 
3、ng server
4、Browser error: compiler.js:5476 Uncaught Error: Expected 'styles' to be an array of strings.

## 🔥 Exception or Error
<pre><code>
compiler.js:5476 Uncaught Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (compiler.js:5476)
    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:20772)
    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata (compiler.js:21418)
    at compiler.js:21077
    at Array.map (<anonymous>)
    at CompileMetadataResolver.push.../../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (compiler.js:21077)
    at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (compiler.js:27117)
    at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:27098)
    at JitCompiler.push.../../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync (compiler.js:27058)
    at CompilerImpl.push.../../node_modules/@angular/platform-browser-dynamic/fesm5/platform-browser-dynamic.js.CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:143)
</code></pre>

## 🌍 Your Environment
angular environment:
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.3
Node: 10.15.3
OS: win32 x64
Angular: <error>
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          <error>
@angular-devkit/build-angular      <error>
@angular-devkit/build-ng-packagr   <error>
@angular-devkit/core               <error>
@angular-devkit/schematics         <error>
@schematics/angular                <error>
@schematics/update                 <error>
ng-packagr                         <error>
rxjs                               6.5.2 (cli-only)
typescript                         <error>
</code></pre>

yarn version:
<pre><code>
$yarn -v
1.17.3
</code></pre>

npm and node version:
<pre><code>
$node -v
v10.15.3
$npm -v
6.2.0
</code></pre>

lerna version:
<pre><code>
"devDependencies": {
    "@commitlint/cli": "^8.1.0",
    "@commitlint/config-conventional": "^8.1.0",
    "@commitlint/config-lerna-scopes": "^8.1.0",
    "commitizen": "^4.0.3",
    "cz-lerna-changelog": "^2.0.2",
    "husky": "^3.0.2",
    "lerna": "^3.16.4"
  },
</code></pre>

project package.json
<pre><code>
{
  "name": "angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:lib": "ng build ng-clair-design",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.1.3",
    "@angular/common": "~8.1.3",
    "@angular/compiler": "~8.1.3",
    "@angular/core": "~8.1.3",
    "@angular/forms": "~8.1.3",
    "@angular/platform-browser": "~8.1.3",
    "@angular/platform-browser-dynamic": "~8.1.3",
    "@angular/router": "~8.1.3",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.3",
    "@angular-devkit/build-ng-packagr": "~0.801.3",
    "@angular/cli": "~8.1.3",
    "@angular/compiler-cli": "~8.1.3",
    "@angular/language-service": "~8.1.3",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "^5.1.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.35.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

</code></pre>

**Anything else relevant?**
I've tried other versions of angular, and it's still the same mistake
Tried versions:
v7.3.8
v8.2.1
v8.1.3

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.

Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by BerQin** [comment]
> I'm sorry, but we can't reproduce the problem following the instructions you provided.
> 
> Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.


Thank you for your reply, I found the problem, about the version of @angular-devkit/build-angular and @angular-devkit/build-ng-packagr, I can upgrade the version to 0.802.1. Thank you for your answer

**Comment by BerQin** [comment]
> I'm sorry, but we can't reproduce the problem following the instructions you provided.
> 
> Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.


Really build directly without error, I have learn environment package management, but my project can not be released, sorry
