### ISSUE TITLE
Angular Service Worker are broken with two contexts

### ISSUE THREAD

**Issue by vmagalhaes** [angular/angular-cli#15323]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes

### Description

 A clear and concise description of the problem...

My application is running in two contexts example.com/multi and example.com/box, in my nginx when the user uses "/" the nginx redirects to "/multi", then the application does its job to redirect to Right server. The problem presented is in relation to ngsw-worker.js, because after I made all the changes I found about the base href problem the only solution was to update the application to Angular 8 and set 'registrationStrategy:' registerWithDelay: 5000 ', but with this this error happens: **Mixed Content: The page at' https://example.com/multi/ngsw-worker.js 'was loaded over HTTPS, but requested an insecure resource' http: // example.com/multi/ '. This request has been blocked; the content must be served over HTTPS.** What can I do with it? I really don't know what to do anymore.

NGINX

```
server {
    listen       8080;
    server_name  localhost;
    rewrite_log on;
    port_in_redirect off;

    location / {
      rewrite / /multi last;
    }

    location /cloud/multi {
      rewrite /cloud/multi /multi last;
    }

    location /cloud/caixa {
      rewrite /cloud/caixa /caixa permanent;
    }

    location /multi {
        alias  /app;
        index  index.html /index.html;
        try_files $uri $uri/ /index.html;
        if (-d $request_filename) {
            rewrite [^/]$ $scheme://$http_host$uri/ permanent;
        }
    }

    location /caixa {
        alias  /app;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
        if (-d $request_filename) {
            rewrite [^/]$ $scheme://$http_host$uri/ permanent;
        }
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /app;
    }
}

```

## 🔥 Exception or Error
<pre><code>

**Mixed Content: The page at' https://example.com/multi/ngsw-worker.js 'was loaded over HTTPS, but requested an insecure resource' http: // example.com/multi/ '. This request has been blocked; the content must be served over HTTPS.** 
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.2.1
Node: 10.16.0
OS: linux x64
Angular: 8.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@angular/cdk                      7.3.2
@angular/cli                      8.2.1
@angular/flex-layout              7.0.0-beta.19
@angular/material                 7.3.2
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
