### ISSUE TITLE
Incorrect generate library

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#15336]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

When I generate my library

```
$ ng g library @ngxs/data
```

I see in angular.json

![image](https://user-images.githubusercontent.com/12021443/63055376-6c4d2600-beee-11e9-86f4-5897bbc7eb1b.png)

Property is not allowed and it turns out that my project was generated in the wrong place `~./my-app/projects/ngxs/data`

**Comment by alan-agius4** [comment]
Hi @splincode, the project seems to be generated in the correct folder. Why do you believe it’s not?

**Comment by splincode** [comment]
I think it would be great to create a directory `@ngxs/data` instead directory ngxs with sub directory data

**Comment by alan-agius4** [comment]
@splincode, a directory with `/` cannot be created as it's not a valid directory. 

I would also say that typically users wouldn't want to have `@` as part of their folder name in their mono repo.
