### ISSUE TITLE
Add the possibility to instrument generated code for coverage  during "build" as it is already done for "test"

### ISSUE THREAD

**Issue by ochezeau** [angular/angular-cli#15333]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I have Java based Junit Selenium integration tests that perform global test for my backend and my Angular application.
I wish I could extract code coverage from the execution of my Java tests.
It seems that the "codeCoverage" option of the test command allows to instrument the code to then generate a coverage report.
I can easily extract the value provided by "window .__ coverage__" at the end of the execution of my Java tests, so I would be able to generate a report for the cover of my typescript file.

So if the command "build" could have the option "codeCoverage" as for the command "test" I should be able to generate my reports.

Maybe I am completely wrong in my understanding of the option "codeCoverage" and in the use of instanbul, in this case sorry for the inconvenience

### Describe the solution you'd like
Add the "codeCoverage" option to the "build" command to enable to instrument the code and be able to use the code coverage result in other tools.

### Describe alternatives you've considered
I have tried to instrument the generated code using method described on the following repository :
https://github.com/skylock/cypress-angular-coverage-example

My code seems to be properly instrumented, I can extract the "json" results from the execution of my tests, and i was able to generate a report.
Moreover, my angular project have the followingf structure :

root\
---- projects\
-------- app1
-------- app2
-------- shared-lib
                      
My "shared-lib" library project uses the builder "@angular-devkit/build-ng-packagr:build " and i whasn't able to instrument the code.
(https://github.com/manfredsteyer/ngx-build-plus/issues/68 -> https://github.com/shlomiassaf/ng-cli-packagr-tasks)

**Comment by alastair-todd** [comment]
It is possible to include an angular shared library in the code-coverage with the following config
```

module.exports = {
  module: {
    rules: [
      {
        test: /\.(js|ts)$/,
        loader: 'coverage-istanbul-loader',
        options: { esModules: true },
        enforce: 'post',
        include: [
          require('path').join(__dirname, '..', '..', 'projects/patterns/src/app'),
          require('path').join(__dirname, '..', '..', 'dist/shared-modules')
        ],
        exclude: [/\.(e2e|spec)\.ts$/, /node_modules/, /(ngfactory|ngstyle)\.js/]
      }
    ]
  }
};

```

ensure tsconfig `"sourceMap": true` is enabled

I had to munge the code-coverage output, but this has been fixed in the latest cli 

```
/**
 *
 * @type {module:replace-in-file}
 * replaces ng-packagr (library builder) webpack source maps urls, prefixed with ng://, with the real file paths
 * this ensures files can be found by the nyc code coverage report builder
 */
const replace = require('replace-in-file');
const options = {
  files: '.nyc_output/out.json',
  from: /ng:\/\/shared-modules\/lib/g,
  to: '../../../projects/shared-modules/src/lib'
};
replace.sync(options);
```

**Comment by alan-agius4** [comment]
Closing as this is doesn't fall in the Angular CLI roadmap. 

Let's revisit this in the future if we see there is a stronger interest for this.
