### ISSUE TITLE
Build process with AoT converts variable calls to null on source code

### ISSUE THREAD

**Issue by almogyehuda** [angular/angular-cli#15341]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I build a sub module (Logger module) that implements the forRoot static method, and required an object
structured like this:

export interface LoggerOptions {
    loggerType: LoggerType; << Enum
    data: any;
    environment: any;
}

on AppModule,
I'm importing the sub module and calling the forRoot function and passing the required
object, while using the values below:
loggerType - hard coded value from the enum
data - object (**type: any**) from pre initiated config data
environment - string (tried to wrap as object as well, **type: any**) from pre initiated config data

**THE ISSUE:**

After opening the app again, the sub module always pass to it's services null
on the environment field.

I couldn't figure out what was the problem - because when I'm building on development mode it's fine.

So I looked into the main.js file, and then I saw a weird behavior that I don't think
I can expect from the compiler:

{data:Re,environment:null,loggerType:"hspLogger"}

for some reason, the AoT compiler convert the variable call to null value inside the main.js 
source code.

I first thought that it might be related to the variable is a string and it's not initialized
on the build procedure - so it converts it to null value, but I tried to change the 
environment property to object as well and it's still converts it to null
on the source code.

**what's the difference between environment and data?**
**why data variable is staying as is and doesn't get this behavior as well?**

## 🔬 Minimal Reproduction

1.  create a simple project (angular cli ^7.2.1, angular compiler-cli 7.2.0)
2.  create sub module that implements forRoot static method and requires an object
like mine:

export interface LoggerOptions {
    loggerType: LoggerType; << Enum
    data: any;
    environment: any;
}

3.  import the module to AppModule and call the forRoot static method, pass it
an object with dynamic variables (not pre-initialized with values)

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.1
Node: 8.9.4
OS: win32 x64
Angular: 7.2.0
... common, compiler, core, forms, http, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.1
@angular/cdk                      7.3.7
@angular/cli                      7.3.1
@angular/compiler-cli             7.2.15
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.3
</code></pre>

**Comment by almogyehuda** [comment]
**UPDATE:** when providing the same LoggerOptions object in the providers the AoT compiles it well, but only in the forRoot I see this weird behavior with the null.

**Comment by alan-agius4** [comment]
@almogyehuda, can you kindly set up a minimal reproduction?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Hi @almogyehuda, AOT compiler requires code which can be statically analysable. 

For this reason, you cannot dynamically inject state at runtime with AOT unless you provide the dynamic values as a function.

```js
export function getDynamic() {
  return { ...initialState };
}

@NgModule({
  imports: [
    myModule.forRoot( dynamic: getDynamic })
  ]
})
```

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alan-agius4** [comment]
Also see: https://angular.io/guide/aot-compiler#only-initialized-variables-and-constants

**Comment by almogyehuda** [comment]
> Hi @almogyehuda, AOT compiler requires code which can be statically analysable.
> 
> For this reason, you cannot dynamically inject state at runtime with AOT unless you provide the dynamic values as a function.
> 
> ```js
> export function getDynamic() {
>   return { ...dynamic };
> }
> 
> @NgModule({
>   imports: [
>     myModule.forRoot({dynamic: getDynamic })
>   ]
> })
> ```
> 
> This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**already opened:** https://stackoverflow.com/questions/57496546/angular-aot-build-convert-dynamic-variable-value-to-null
