### ISSUE TITLE
Changes in partial scss files are not respected when using ng serve --aot on Windows

### ISSUE THREAD

**Issue by rosen-vladimirov** [angular/angular-cli#15340]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.1

### Description
When partial scss files are used (`scss` files which names start with `_`), `ng serve --aot` on Windows does not detect changes in them. This is not happening when `--aot` is not passed. Also everything works fine on macOS and Linux.

## 🔬 Minimal Reproduction

You can find a sample project reproducing the issue here: https://github.com/rosen-vladimirov/angular-scss-windows-aot-issue

The project was created with `ng new --style scss`, without router. After that I've included the partial scss file and used it in `app.component`. 
Run `ng serve --aot` **on Windows** and apply a change in the partial scss file. Nothing happens.

## 🔥 Exception or Error
No error, just the changes are not detected and they are not applied.

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.2.2
Node: 10.15.1
OS: win32 x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0
</code></pre>

**Anything else relevant?**
Issue is reproducible only on Windows.
NOTE: It breaks syncing of partial scss files in NativeScript Angular projects as well (`tns run android --env.aot` is not working on Windows when changing partial scss).

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/16068 should fix this issue too.
