### ISSUE TITLE
@angular-devkit/build-angular@0.803.0-rc.0 causes __importDefault is not defined

### ISSUE THREAD

**Issue by Dj-jom2x** [angular/angular-cli#15355]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [x] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.803.0-next.1

### Description

 I just love updating and see whats new. Today I update again.

    Updating package.json with dependency @angular/cli @ "8.3.0-rc.0" (was "8.3.0-next.1")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.803.0-rc.0" (was "0.803.0-next.1")...

then executing `ng serve`.. no error.. but when i go to `http://localhost:4200`
at console i saw this error ```__importDefault is not defined``` the error is poiting at 
` templateUrl: './app.component.html',`

I reverted to 8.3.0-next.1 and the error is gone.

## 🔥 Exception or Error
<pre>

__importDefault is not defined
<code>

</code></pre>

## 🌍 Your Environment
<pre>
All set to @next 
Update using `ng update @angular/cli@next @angular/core@next`
Windows Sub Linux

<code>

</code></pre>

**Anything else relevant?**

Nope

**Comment by alan-agius4** [comment]
Hi @Dj-jom2x, this might be an issue when `importHelpers` Is not enabled. As a work around you can enable the `importHelpers` flag in the root tsconfig.

**Comment by Dj-jom2x** [comment]
🤔 I think its my fault.. but hear me out ... 

I know that I should stay at 3.5.x typescript.. but ```@angular-devkit/build-angular@0.803.0-next.1``` is working pretty fine at ```typescript@3.7.0-dev.20190816``` aka next version of ts, I'm also playing with both updates.. ( angular & typescript ) 

0.803.0-next.2 and 0.803.0-rc.0 where that error shows up.. 


```
sudo npm -g install @angular/cli@next
ng new sample
cd sample
sudo ng update @angular/cli@next @angular/core@next --force --allow-dirty
sudo npm install @angular/cli@8.3.0-rc.0 --save-dev
sudo npm install @angular-devkit/build-angular@8.3.0-rc.0 --save-dev
sudo npm install typescript@3.7.0-dev.20190816 --save-dev
ng serve
``` 

change that to ```sudo npm install @angular-devkit/0.803.0-next.1 --save-dev``` will work..

**Comment by alan-agius4** [comment]
Can you confirm that there is no issue with `0.803.0-rc.0` and Ts 3.5?

**Comment by Dj-jom2x** [comment]
yes there's no error @3.5.3 🧐

**Comment by alan-agius4** [comment]
@Dj-jom2x, in that case I will close this since you are using an unsupported version of TypeScript. Moreover the very version you are using is not stable and might contain bugs which will be fixed when it will be released as stable version.

Thanks.

**Comment by FiringBlanks** [comment]
_Disabling_ `importHelpers` from the root tsconfig worked for me.
