### ISSUE TITLE
ng upgrade V7->V8: missing peer dependency error for project including @ngtools/webpack

### ISSUE THREAD

**Issue by devin5885** [angular/angular-cli#15357]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
n/a

 Yes, the previous version in which this bug was not present was: ....

### Description
 A clear and concise description of the problem...
When attempting to upgrade a project from V7 to V8, if the project includes '@ngtools/webpack' but not the peer dependency 'webpack' the upgrade fails.

## 🔬 Minimal Reproduction

1. Create a new project Angular V7 project using 'ngNew'
2. Add '@ngtools/webpack' using 'npm install @ngtools/webpack'  
3. Attempt to update the project using 'ng update @angular/cli @angular/core'. You will get an error:
Package "@ngtools/webpack" has an incompatible peer dependency to "typescript" (requires ">=2.4.0 < 3.3", would install "3.5.3").
4. So add @ngtools/webpack to the command line (i.e.) ng update @angular/cli @angular/core @ngtools/webpack
5. You will get the error:
Package "@ngtools/webpack" has a missing peer dependency of "webpack" @ "^4.0.0".

Adding webpack using 'npm install webpack' before upgrading causes the upgrade to be successful.

Removing 'webpack' using 'npm uninstall webpack' after the upgrade removes it from the project.json and node_modules and causes ng serve to show the following error:
An unhandled exception occurred: Cannot find module 'webpack'

Note also that 'webpack' appears to be in the node_modules by default even if not listed explicitly in the package.json (unless removed as described above in which case npm install does not seem to restore it).

## 🔥 Exception or Error
<pre><code>

Package "@ngtools/webpack" has a missing peer dependency of "webpack" @ "^4.0.0".
</code></pre>

## 🌍 Your Environment
<pre><code>

Before upgrade:

Angular CLI: 7.3.9
Node: 10.16.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

After upgrade (webpack removed)
Angular CLI: 8.2.2
Node: 10.16.3
OS: win32 x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.2
typescript                        3.5.3
</code></pre>

**Anything else relevant?**

n/a

This is Windows 10
Using the CLI from a Powershell Window (Non-admin).

**Comment by clydin** [comment]
Peer dependencies are intended to be explicitly satisfied.  The project worked previously because the package manager _happened_ to hoist Webpack into a position within node modules that allowed the peer dependency of `@ngtools/webpack` to be satisfied.  Package hoisting itself is not guaranteed nor is the version which will be hoisted.  Explicitly providing the necessary version of a peer dependency along side the package guarantees the availability of said version for the package with the peer dependency.

**Comment by alan-agius4** [comment]
Also, I'd like to point out that unless you are using `@ngtools/webpack` directly such as a custom build pipeline, you don't need to install `@ngtools/webpack` in your project as this is already a dependency of `@angular-devkit/build-angular`.

**Comment by devin5885** [comment]
OK, so I guess I need to add webpack or @ngtools/webpack from the project.json before upgrading. 
Thanks,
Devin
