### ISSUE TITLE
CLI File Naming Options

### ISSUE THREAD

**Issue by Vandivier** [angular/angular-cli#15351]
# 🚀 feature request

### Relevant Package
angular CLI

### Description
 A clear and concise description of the problem or missing capability...
currently when a component is generated it might be called x.component.ts and a service like y.service.ts

This has a few negative effects in my book:
1 - sorting by name does not group components and services together.
2 - Hungarian-like naming becomes awkward, eg `ServiceAnalyticsService`. Service is prepended in the hungarian-like system I like, but it also has to be appended to comply with angular convention.
3 - it doesn't seem possible to programmatically or humanly know whether a folder under app refers to a component, service, module...by looking at the folder name when generating a non-flat entity.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
1 - An option to have the files generated with flipped naming like component.x.ts and service.y.ts
2 - A different option to allow type to be added to the folder name without redundancy. So normal mode is `x-component/x.component.ts` and flipped is `component-x/component.x.ts`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
I'm personally OK with the redundant naming but my team isn't. So a key workaround would be having a component called ComponentThingComponent or ServiceSomeService.

ref: https://github.com/angular/angular/issues/32158

**Comment by alan-agius4** [comment]
Hi, thanks for opening this. 

At this point I think that this is outside of the scope of the CLI since the suggested namings don’t conform with the Angular style guide (https://angular.io/guide/styleguide#naming)

An option from your end would be to create custom schematics that extents the Angular schematics.

**Comment by Vandivier** [comment]
@alan-agius4 I'd like this re-opened as the style guide only touches on one of the two proposals I mentioned. I've also made a PR to the docs to request that be changed there as well:
https://github.com/angular/angular/pull/32168

Currently, the docs recommend `feature.types.ts`. Fair enough, although I hope to see it changed.

On the other hand, the docs do not officially recommend `--flat=true` nor `--flat=false`. Indeed, their examples in the section near naming assumes it is true, but the CLI also supports false.

So an enhancement request in this regard which is compliant with the existing style guidelines would be to allow the type to also be in the folder but not redundant.

Suppose either implementation:
1 - CLI has a flag `--typed-folder=true` then `ng g c hello --typed-folder=true`, with or without possibly implicit `--flat=false`, creates `/hello-component/hello.component.ts`.
2 - CLI detects type keyword within generated entity name and automatically dedupes. So `ng g c hello-component` with `--flat=false` creates `/hello-component/hello.component.ts` and not current `/hello-component/hello-component.component.ts`

**Comment by Vandivier** [comment]
meh nvm looks like no support for this

**Comment by alan-agius4** [comment]
Hi @Vandivier, what you explained in your second point is already possible today. 

You can use the below command;

```bash
ng generate component foo-component/foo --flat
```

**Comment by Vandivier** [comment]
ah thanks! I didn't realize `foo-component/foo` was possible

I appreciate your opinion about folders, but of course I disagree or I wouldn't be bringing this up. I could mention a number of benefits but I'll be concise and just mention one: Type information in the folder name allows me to have hero-component as a sibling of hero-service instead of having to make up random names to disambiguate them.

Vertical modularization is irrelevant here. You can still have vertical modularization with both feature and type in the folder name. In fact, module nesting is more transparent with `x-module/y-module` than it is with `x/y`. With feature-only naming you are going to ambiguate components, services, modules, and whetever else you might have related to that feature, at least in social conversation, and indeed you add technical complexity during file system operations and so on,.

The idea that removing a feature is easier without type information in the folder name simply isn't true. Remember, I'm advocating "feature and type" folder name, not "type without feature" folder name.
