### ISSUE TITLE
Stuck in Angular CLI when creating project

### ISSUE THREAD

**Issue by rlalbario** [angular/angular-cli#15350]
Hello Mam/Sir,

I'm creating to create a project using Angular CLI, however, Its stuck on creating a project. I'm using the latest version of Angular CLI and I'm using Asus X441BA Laptop. 

![AngularStuck](https://user-images.githubusercontent.com/52766455/63138850-8da53380-c00e-11e9-9c0e-47d87e97ab90.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this m, but this seems like a problem with your npm/internet connectivity and not with Angular CLI.

**Comment by rlalbario** [comment]
> Thanks for reporting this m, but this seems like a problem with your npm/internet connectivity and not with Angular CLI.

I'm pretty sure my internet connection is good. May I know how to fix the npm? Also, I'll try to re-install the Angular CLI and let you know if the issue still persist.

**Comment by alan-agius4** [comment]
Hi, try to create a project without installing the projects dependencies and try to install the dependencies using another package manage if with npm the problem still persists.

```
ng new project --skip-install
cd project
yarn install or  npm install
```

For npm common issues and how to resolve them you can check https://docs.npmjs.com/common-errors
