### ISSUE TITLE
Feature Request: Ability to load default scss partials

### ISSUE THREAD

**Issue by AltekkeE** [angular/angular-cli#1536]
I would like to be able to load an scss file that contains default variables for the entire app. 

Like color pallet for example.

**Comment by vultix** [comment]
I agree, I also feel this would be a useful feature.

**Comment by ValeryVS** [comment]
It works now. At least with master branch at fa7a927d3e27b630692f2a41181979ff79b22138
I have `src/styles/_variables.sass`
And able to import it from
`src/app/my-module/my-component.component.sass`
with
`@import ../../styles/variables`

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/4003 adds something similar, where you can say a certain path is part of sass/stylus paths, and then you only need to do `@import variables`.

**Comment by rossanmol** [comment]
@filipesilva This does not work with angulat universal (ngc & aot)
