### ISSUE TITLE
ng serve Port 4200 is already in use

### ISSUE THREAD

**Issue by korzh17** [angular/angular-cli#15369]
# 🐞 Bug report

### Command (mark with an `x`)
**ng serve --open --port XXXX** says error:
Port XXXX is already in use. Use '--port' to specify a different port.
in cmd "netstats" that ports are not used.

### Description
Using Intellij Idea. 
Its just simple AngularCLI application without additional code.
Just starting **npm install -g @angular/cli@1.7.4**
and **ng new angularclient**
Trying to make application _Spring Boot + Angular_ - https://www.baeldung.com/spring-boot-angular-web

After i tried to make another Angular project without backend, just used **WebStorm** -> **AngularCLI** -> **node v10.16.3.** I have got the same error

## 🔥 Exception or Error
<pre><code>

> frontend@0.0.0 start C:\Users\korzh\Programming\Java\Study\Spring\FullStack\frontend
> ng serve

Port 4200 is already in use. Use '--port' to specify a different port.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\korzh\AppData\Roaming\npm-cache\_logs\2019-08-18T18_40_28_465Z-debug.log

</code></pre>

my project structure first time(when i Did Angular and Spring in 1 project).
-angularclient: e2e, node_modules, src, angular-clie.json, other files...   
-src: main->java, resources->static, templates, application.properties; test
pom.xml

When i did it in Intellij in Spring project, my .angular-cli-json -> "$schema": "./node_modules/@angular/cli/lib/config/schema.json", was saying "node_modules not found", 
deleted "./", alt+enter on node_modules and its creating package in src/main/resources/static/node_modules. When i tried to move all my angularclient project to "static"  - not working.
</code></pre>
If it securaly i can share what is in C:\Users\korzh\AppData\Roaming\npm-cache\_logs\2019-08-18T18_40_28_465Z-debug.log
**Anything else relevant?**

**Comment by harounchebbi** [comment]
Did you try killing the port??

**Comment by michalstepien** [comment]
It is bug in portfinder

**Comment by michalstepien** [comment]
@angular\cli\utilities check-port.js

**Comment by korzh17** [comment]
> Did you try killing the port??

did you reas that i have no potrs  to kill?

**Comment by michalstepien** [comment]
@korzh17 do you have webpack-dev-server in package.json?

**Comment by michalstepien** [comment]
I've added to my packege.json portfinder": "~1.0.20" and change package-lock.json portfinder to ,
"portfinder": {
      "version": "1.0.20",
      "resolved": "https://registry.npmjs.org/portfinder/-/portfinder-1.0.20.tgz",
      "integrity": "sha512-Yxe4mTyDzTd59PZJY4ojZR8F+E5e97iq2ZOHPz3HDgSvYC5siNad2tLooQ5y5QHyQhc3xVqvyk/eNA3wuoa7Sw==",
      "requires": {
        "async": "^1.5.2",
        "debug": "^2.2.0",
        "mkdirp": "0.5.x"
      }
    },

and works

**Comment by hoacodai000** [comment]
Reason: node-portfinder > v1.0.22.
Fix: in package.json
add => "portfinder": "1.0.20"
"dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "~7.2.15",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "core-js": "^3.1.4",
    "rxjs": "~6.5.2",
    "zone.js": "~0.10.1",
    "portfinder": "1.0.20"
  }

**Comment by korzh17** [comment]
> @korzh17 do you have webpack-dev-server in package.json?

{
  "name": "spring-react",
  "version": "1.0.0",
  "description": "My webpack project",
  "main": "./src/main/js/app.js",
  "keywords": [
    "spring",
    "react"
  ],
  "author": "Korzhov",
  "license": "ISC",
  "dependencies": {
    "@webpack-cli/init": "^0.2.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "rest": "^1.3.1"
  },
  "scripts": {
    "watch": "webpack --watch -d",
    "build": "webpack",
    "start": "webpack-dev-server"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-syntax-dynamic-import": "^6.18.0",
    "css-loader": "^3.0.0",
    "html-webpack-plugin": "^3.2.0",
    "style-loader": "^0.23.1",
    "webpack": "^4.39.2",
    "webpack-cli": "^3.3.6",
    "webpack-dev-server": "^3.8.0"
  }
}

**Comment by clydin** [comment]
Version 1.7.4 is no longer supported.  Please update to a newer version (8.2.2 is the latest stable version). If the problem persists please file a new issue.

**Comment by korzh17** [comment]
thanks

**Comment by jebali-f** [comment]
I had the same problem, all ports are refused.
Here are the steps to fix it:
- add portfinder in the devDependencies block
"devDependencies": {
    "portfinder": "1.0.20",
}
- Remove node_modules
- clear the cache
- run npm install
