### ISSUE TITLE
ng-serve: cannot load application

### ISSUE THREAD

**Issue by ahnpnl** [angular/angular-cli#15368]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not so sure

### Description

After running `ng serve`, application can't be loaded at `localhost:4200`.

## 🔬 Minimal Reproduction
- Configure global Angular CLI config to use `yarn` as package manager.
- Generate a new project by `ng new <project_name>`.
- Choose `n` when command asks to configure routing.
- Chose `css` when command asks to configure css extension.
- Wait for project generation and dependencies installation to be finished, then run `yarn start`.
- Go to `http://localhost:4200` and application doesn't load.

Example repo: https://github.com/ahnpnl/cli-serve-issue

## 🔥 Exception or Error
- First time go to `http://localhost:4200`
<pre><code>
chunk {main} main.js, main.js.map (main) 9.86 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 278 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 16.3 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.82 MB [initial] [rendered]
Date: 2019-08-18T17:11:03.022Z - Hash: 352004b2e1d9ef04e4a8 - Time: 5829ms
** Angular Live Development Server is listening on localhost:undefined, open your browser on http://localhost/ **
ℹ ｢wdm｣: Compiled successfully.
</code></pre>
- Hit refresh button on the  browser
<pre><code>
ℹ ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.2.2
Node: 10.16.3
OS: darwin x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0

</code></pre>

**Anything else relevant?**
- Operating system: MacOS Mojave 10.14.6
- Package manager: yarn
- Angular CLI, yarn were installed via `Homebrew`.
- I observe this doesn't happen to a newly generated project on Windows.

**Comment by alan-agius4** [comment]
Hi @ahnpnl, I cloned your repo and it seems to be working fine on OSX and Google Chrome.

Which browser and version are you using? Note by default `serve` will only work for browsers which support ES6 modules.

See: https://angular.io/guide/deployment#local-development-in-older-browsers

**Comment by ahnpnl** [comment]
hi, I used latest Google Chrome on OSX.  Do you think it's related to Angular CLI installed via `Homebrew` vs Angular CLI installed via `yarn` or `npm` ?

**Comment by clydin** [comment]
Official versions of the Angular CLI are only published to NPM’s package registry.  Any variant found on homebrew is not provided by the Angular team.

**Comment by ahnpnl** [comment]
According to [forumula](https://github.com/Homebrew/homebrew-core/blob/c7fbfd0d446507eb386a93d27a4defbf33364504/Formula/angular-cli.rb#L6) homebrew pulls from npm, so I think it should work the same, shouldn't it ?

**Comment by alan-agius4** [comment]
What I am seeing rather strange is the console message that you provided above.
```
** Angular Live Development Server is listening on localhost:undefined, open your browser on http://localhost/ **
```

Notice the `localhost:undefined`.

**Comment by mgechev** [comment]
Interesting. I tried to install the CLI via homebrew and everything worked as expected. Notice that homebrew installs `node` as dependency of the CLI:

```
~ brew install angular-cli
==> Installing dependencies for angular-cli: node
==> Installing angular-cli dependency: node
==> Downloading https://homebrew.bintray.com/bottles/node-12.8.1.mojave.bottle.t
==> Downloading from https://akamai.bintray.com/bd/bd309bcdeeda287dfae43f38f7ed7
######################################################################## 100.0%
==> Pouring node-12.8.1.mojave.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/node/12.8.1: 4,629 files, 53.1MB
==> Installing angular-cli
==> Downloading https://homebrew.bintray.com/bottles/angular-cli-8.2.2.mojave.bo
==> Downloading from https://akamai.bintray.com/0a/0a9d92ee2092b9e498a4697cc2491
######################################################################## 100.0%
==> Pouring angular-cli-8.2.2.mojave.bottle.tar.gz
```

**Comment by ahnpnl** [comment]
Hi,

Here is the screenshot of the command line
![image](https://user-images.githubusercontent.com/27772165/63302277-fb867f00-c2dc-11e9-973b-9c0760f79306.png)

I added a `console.log` to print out [options](https://github.com/angular/angular-cli/blob/c1523d220abfef4cb652e1445b3e813b62ba07fb/packages/angular_devkit/build_angular/src/dev-server/index.ts#L253)

I saw port is filled with `4200` but no idea why the [Angular Live Development Server text](https://github.com/angular/angular-cli/blob/c1523d220abfef4cb652e1445b3e813b62ba07fb/packages/angular_devkit/build_angular/src/dev-server/index.ts#L258) shows undefined.

Another thing I observed is when the console showed `Compiled successfully`, it took a few seconds then the next 3 lines were printed, quite weird. But if I wait for those 3 lines to be printed, then I can use `localhost:4200` normally.

**Comment by mgechev** [comment]
Would you verify if you have the same behavior when you install the CLI with npm?

**Comment by ahnpnl** [comment]
hi @mgechev , I tried couples of things:
- Remove completely `node`, `yarn`, `angular-cli` which were installed by Homebrew.
- Reinstall `node` via pkg file downloaded from website
- Reinstall `yarn` via curl
- Regenerate the project

The result is still the same as with Homebrew.

**Comment by alan-agius4** [comment]
A reason why the port is undefined, might be because the server didn't start listening and didn't trigger this code

https://github.com/angular/angular-cli/blob/4986577f8a301a52083bb3ad0b00ffd87eae8522/packages/angular_devkit/build_webpack/src/webpack-dev-server/index.ts#L71-L87

**Comment by ahnpnl** [comment]
I suspect so, but I don't know why v8 has this localhost:undefined behavior. I didn't see it in v7. 

Besides, localhost:undefined console log happened in windows as well, but it's quickly overriden by localhost:4200 after that.

The behavior I observed is:
- MacOS: compilation finished > print out localhost:undefined > a few sec later > print out 404s will fall back to //index.html
- Windows: compilation happening > print out localhost:undefined > print out 404s will fall back to //index.html > compilation continues and finishes > print out app is served at localhost:4200

**Comment by ahnpnl** [comment]
@alan-agius4 I don't see the issue anymore on my Mac with CLI 8.3.5 . Maybe this issue can be closed ?

**Comment by alan-agius4** [comment]
@ahnpnl, thanks for getting back in touch.

Glad that the issue is solved 😊
