### ISSUE TITLE
Googles analytics question prevents automated installation

### ISSUE THREAD

**Issue by NCC1701M** [angular/angular-cli#15373]
# 🐞 Bug report

### Description

When trying to install angluar-cli automated by script it won't finish because suddenly the postinstall script asks you if you would like to share data with Google Analytics. Remove it

## 🔬 Minimal Reproduction
Run `sudo npm i -g @angular/cli`

## 🔥 Exception or Error
After finishing installation it asks:

```
? Would you like to share anonymous usage data with the Angular Team at Google under
Google’s Privacy Policy at https://policies.google.com/privacy? For more details and
how to change this setting, see http://angular.io/analytics.
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.2.2
Node: 10.16.3
OS: linux x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.802.2
@angular-devkit/core         8.2.2
@angular-devkit/schematics   8.2.2
@schematics/angular          8.2.2
@schematics/update           0.802.2
rxjs                         6.4.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi @NCC1701M, there are a couple of ways you can disable analytics if you are running a script in a TTY console.

- Using `ng analytics off` or changing the global configuration file yourself. This is the same as answering "No" to the prompt.

- Set `NG_CLI_ANALYTICS` environment variable to "false" to disable analytics for this run.

**Comment by NCC1701M** [comment]
Hi @alan-agius4, thank you for your answer but the first one wouldn't work because there is no angular-cli installed before I call `sudo npm i -g @angular-cli`.

What's about the second option, would it work when the cli is newly installed?

**Comment by alan-agius4** [comment]
Hi, you can create a global configuration file yourself, if you don't have the CLI available. Alternatively you can use `npx`.

```
npx @angular/cli@latest analytics off
```

Yeah, the second option would work on new installations if the environment variable is provided via the automated script.

**Comment by NCC1701M** [comment]
Setting the environment variable works fine. Thanks @alan-agius4
