### ISSUE TITLE
Angular 4 home page loading issue

### ISSUE THREAD

**Issue by rajeshlatitude** [angular/angular-cli#15399]
I have to use Angular 4 with lazy loading But home page load very slow in the mobile 
This is my site URL: https://jobrizer.com. so please help me what's wrong.

Packages
"dependencies": {
"@angular/animations": "^4.2.4",
"@angular/cli": "^1.7.4",
"@angular/common": "^4.2.4",
"@angular/compiler": "^4.2.4",
"@angular/core": "^4.2.4",
"@angular/forms": "^4.2.4",
"@angular/http": "^4.2.4",
"@angular/platform-browser": "^4.2.4",
"@angular/platform-browser-dynamic": "^4.2.4",
"@angular/router": "^4.2.4",
"@bugsnag/js": "^6.0.0",
"@bugsnag/plugin-angular": "^6.0.0",
"@ngrx/core": "^1.2.0",
"@ngrx/effects": "^4.0.5",
"@ngrx/router-store": "^4.0.4",
"@ngrx/store": "^4.0.3",
"@ngrx/store-devtools": "^4.0.0",
"@types/html2canvas": "0.0.35",
"@types/jspdf": "^1.2.2",
"@types/node": "^6.0.88",
"@types/socket.io-client": "^1.4.32",
"angular2-google-login": "^1.0.9",
"angular2-google-maps": "^0.17.0",
"angular2-highcharts": "^0.5.5",
"angular2-modal": "^3.0.3",
"angular2-qrcode": "^2.0.1",
"angular2-social-login": "^3.1.1",
"angular2-text-mask": "^9.0.0",
"bootstrap": "^3.3.7",
"classlist.js": "^1.1.20150312",
"enhanced-resolve": "^3.3.0",
"html2canvas": "^1.0.0-alpha.12",
"intl": "^1.2.5",
"jquery": "^3.2.1",
"jspdf": "^1.5.3",
"ng-block-ui": "^1.0.0-beta.15",
"ng2-ckeditor": "^1.2.1",
"ng2-completer": "^1.6.1",
"ng2-date-picker": "^2.3.1",
"ng2-device-detector": "^1.0.0",
"ng2-google-place-autocomplete": "^1.4.2",
"ng2-select": "^2.0.0",
"ngx-facebook": "^2.4.0",
"ngx-mydatepicker": "^2.1.0",
"ngx-pagination": "^3.0.1",
"ngx-read-more": "^1.0.0",
"ngx-tooltip": "0.0.9",
"node-sass": "^4.9.2",
"rxjs": "^5.5.12",
"text-mask-addons": "^3.8.0",
"zone.js": "^0.8.14"
},
"devDependencies": {
"@angular/cli": "1.4.1",
"@angular/compiler-cli": "^4.2.4",
"@angular/language-service": "^4.2.4",
"@types/highcharts": "^5.0.5",
"@types/jasmine": "~2.5.53",
"@types/jasminewd2": "~2.0.2",
"@types/node": "^6.0.88",
"@types/socket.io": "^1.4.38",
"codelyzer": "~3.1.1",
"jasmine-core": "~2.6.2",
"jasmine-spec-reporter": "~4.1.0",
"karma": "~1.7.0",
"karma-chrome-launcher": "~2.1.1",
"karma-cli": "~1.0.1",
"karma-coverage-istanbul-reporter": "^1.2.1",
"karma-jasmine": "~1.1.0",
"karma-jasmine-html-reporter": "^0.2.2",
"protractor": "~5.1.2",
"source-map-explorer": "^1.6.0",
"ts-node": "~3.2.0",
"tslint": "~5.3.2",
"typescript": "~2.3.3",
"webpack-bugsnag-plugins": "^1.4.0",
"webpack-bundle-analyzer": "^3.4.1"
}

after creating build chunk, vendor  & main 
chunk {27} 27.7fcb137e466fae85c0b0.chunk.js () 250 kB [rendered]
chunk {scripts} scripts.5984a010faf2be61fd5d.bundle.js (scripts) 429 kB [initial] [rendered]
chunk {0} 0.7ff5308ada214157976f.chunk.js (common) 1.33 MB [rendered]
chunk {1} 1.c7b1c4e8022cf2263181.chunk.js () 1.5 MB [rendered]
chunk {2} 2.f8960fbfffbc7e2e7d3d.chunk.js () 125 kB [rendered]
chunk {3} 3.8c9d91903fb703f7d18e.chunk.js () 37.1 kB [rendered]
chunk {4} 4.df71e8f3b4ac652d6c4a.chunk.js () 204 kB [rendered]
chunk {5} 5.dd5a56565e6bc7fc74ff.chunk.js () 9.09 kB [rendered]
chunk {6} 6.b1b91152140f94736d4f.chunk.js () 395 kB [rendered]
chunk {7} 7.1284e8096d6fe7ae2bd3.chunk.js () 327 kB [rendered]
chunk {8} 8.86be1120cba28b2126ba.chunk.js () 56.8 kB [rendered]
chunk {9} 9.f6926651ed99e927c585.chunk.js () 542 kB [rendered]
chunk {10} 10.6c9becaea1b62104dce3.chunk.js () 637 kB [rendered]
chunk {11} 11.903d268dd52c03022f6c.chunk.js () 44.5 kB [rendered]
chunk {12} 12.d4e92e8e82e2a7b86bef.chunk.js () 42.8 kB [rendered]
chunk {13} 13.e6516c1e29dbc90f6bd7.chunk.js () 311 kB [rendered]
chunk {14} 14.71c99c1c7c7618be6197.chunk.js () 53 kB [rendered]
chunk {15} 15.52e29e49cba372f3952c.chunk.js () 18.1 kB [rendered]
chunk {16} 16.95748c218dff1ca960ca.chunk.js () 122 kB [rendered]
chunk {17} 17.ac235fec1ebcb1cc99bc.chunk.js () 43.7 kB [rendered]
chunk {18} 18.22dfb66f018a0d315c3e.chunk.js () 15.2 kB [rendered]
chunk {19} 19.bc5b2ea43f40be4d7ed9.chunk.js () 280 kB [rendered]
chunk {20} 20.bbb485b6110e098accab.chunk.js () 182 kB [rendered]
chunk {21} 21.682860259d98e746ee44.chunk.js () 525 kB [rendered]
chunk {22} 22.55b728d88fbf6d169d53.chunk.js () 134 kB [rendered]
chunk {23} 23.b1f602ec2b8f3bf46c44.chunk.js () 50.5 kB [rendered]
chunk {24} 24.e9569078d31016d8e642.chunk.js () 283 kB [rendered]
chunk {25} 25.1a0cbf8a2ab0d5feeb70.chunk.js () 196 kB [rendered]
chunk {26} 26.e335e72a9ba6f9ec995f.chunk.js () 321 kB [rendered]
chunk {28} 28.db4a8549180f354c1d3e.chunk.js () 87.4 kB [rendered]
chunk {29} 29.834ac2d9a29276331d74.chunk.js () 46.2 kB [rendered]
chunk {30} 30.d134eb318793e0b98d5a.chunk.js () 58 kB [rendered]
chunk {31} 31.6312e0d755b65d4010f3.chunk.js () 60.5 kB [rendered]
chunk {32} 32.820af4310ca2f56a9f41.chunk.js () 97.8 kB [rendered]
chunk {33} 33.c1423d05224f27e03043.chunk.js () 25.8 kB [rendered]
chunk {34} 34.eb365b11d1d11b3dd57f.chunk.js () 28.9 kB [rendered]
chunk {35} 35.ce8230a7509ff4242ae2.chunk.js () 18.2 kB [rendered]
chunk {36} 36.7f5965261fbe611b2cb8.chunk.js () 113 kB [rendered]
chunk {37} 37.0db0cf7f632bcff332e3.chunk.js () 11.8 kB [rendered]
chunk {38} 38.113803c04566d37cc8cc.chunk.js () 33.9 kB [rendered]
chunk {39} 39.06ee10f6933e9918985c.chunk.js () 309 kB [rendered]
chunk {40} 40.d511b78731af628e6170.chunk.js () 117 kB [rendered]
chunk {41} 41.d0da93045efc75877008.chunk.js () 125 kB [rendered]
chunk {42} 42.4d827dafa1bac0739a18.chunk.js () 2.78 MB [rendered]
chunk {43} 43.777f95b6ababa512d604.chunk.js () 23.2 kB [rendered]
chunk {44} 44.1865eaa07b669f2ad0f5.chunk.js () 306 kB [rendered]
chunk {45} 45.3e2ac0a14759eaf99031.chunk.js () 9.96 kB [rendered]
chunk {46} 46.5d37b1ee0b3a71eff761.chunk.js () 11.8 kB [rendered]
chunk {47} 47.391d0a479eb6a4b72a7b.chunk.js () 16.4 kB [rendered]
chunk {48} polyfills.62d51a9cef3f946b47a9.bundle.js (polyfills) 181 kB [initial] [rendered]
chunk {49} main.c27bb38325d264eae881.bundle.js (main) 749 kB [initial] [rendered]
chunk {50} styles.0fb769f8fd87ebc79ece.bundle.css (styles) 139 kB [initial] [rendered]
chunk {51} vendor.7b6db0cbe241bbd7a0d8.bundle.js (vendor) 1.62 MB [initial] [rendered]
chunk {52} inline.8a50cc421a10bb91dd5b.bundle.js (inline) 2.61 kB [entry] [rendered]

Thank you.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
