### ISSUE TITLE
Improve --include option to handle empty value for unit tests

### ISSUE THREAD

**Issue by EugeneSnihovsky** [angular/angular-cli#15398]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
For now `--include` option is not developer friendly. My package script is
```
"test": "ng test --watch=false --code-coverage"
```
And I can't use any of following bash commands
```
# ignores include option and check all tests
npm test --include=**/auth-api.service.spec.ts

# Unknown option: '**/auth-api.service.spec.ts'
npm test --include **/auth-api.service.spec.ts
```
To use this option I should always modify package script
```
"test": "ng test --watch=false --code-coverage--include **/auth-api.service.spec.ts"
```
This action take some time and there is a possibility to forget to remove this changes before commit

### Describe the solution you'd like

Possible fast and simple solution is to pass argument to script from bash like this
```
"test": "ng test --watch=false --code-coverage --include $spec"
```
Then use it in bash as
```
npm test **/auth-api.service.spec.ts
```
And this is works every time except argument is empty. Following bash command will fail
```
npm test
```
Probably **--include** option can't handle empty values. If it possible, please add this logic

**Comment by clydin** [comment]
This is not actually a CLI issue.  NPM (unlike yarn) requires that a double dash be used before any additional arguments are passed.

**Comment by EugeneSnihovsky** [comment]
@clydin the problem is that **--include** option can't handle empty values and following script will fail
```
"test": "ng test --watch=false --code-coverage --include"
```
But it is insignificant due to [this solution](https://github.com/angular/angular-cli/issues/3603#issuecomment-523794137)

**Comment by clydin** [comment]
Assuming a package script of the following:
```"test": "ng test --watch=false --code-coverage"```

The command
```npm test --include=**/auth-api.service.spec.ts```
 is the equivalent to 
```ng test --watch=false --code-coverage```

If you want npm to pass on additional arguments, a double dash is needed.
The command
```npm test -- --include=**/auth-api.service.spec.ts```
will execute
```ng test --watch=false --code-coverage --include=**/auth-api.service.spec.ts```

**Comment by EugeneSnihovsky** [comment]
@clydin Thanks for new knowledge about double dashes. I understand and agree with your point about  result in false positives/negatives for a test suite.

I'm too lazy to write every time following code :)
```
npm test -- --include=**/auth-api.service.spec.ts
```
So I will use my solution above and write
```
npm test **/auth-api.service.spec.ts
```

Thanks again and sorry for your time lost.
