### ISSUE TITLE
Use custom error reporter

### ISSUE THREAD

**Issue by Franziskus1988** [angular/angular-cli#15408]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
In our company we build the angular applications with Teamcity. Teamcity has a special [format ](https://www.jetbrains.com/help/teamcity/build-script-interaction-with-teamcity.html#BuildScriptInteractionwithTeamCity-ServiceMessages) for build/compile logging. Because angular-cli always logs errors in it's "console format" the errors are not reported nicely in teamcity.

### Describe the solution you'd like
Provide an API where custom error loggers / reporters can be hooked in. I'm thinking about an approach similar to the approach Karma uses, where you can use e.g. the [teamcity reporter](https://github.com/karma-runner/karma-teamcity-reporter).

Problem is that I don't know if this is possible, because I don't know if webpack offers the possibility to do something like this. 

### Other solution
Optionally provide build output in some machine readable format like JSON or XML.

**Comment by mgechev** [comment]
@Franziskus1988 could you pipe stderr and transform the output instead? This seems like a rare use case which, although useful, might not get wide adoption.

**Comment by alan-agius4** [comment]
Sometime ago @clydin, was working on something related to this for Angular Console a build event protocol (BEP). But I am not sure of the status of that.

**Comment by Franziskus1988** [comment]
@mgechev I can of course pipe the stderr. 
The problem is that the error messages are shown in a complete unstandardized way. When I have e.g. 2 errors in a ts file it's printed like this:
`Error in src/some/file.ts:12:12 - error TS1234: Bla bla`
`src/some/file.ts:13:13 - error TS1234: Bla bla`

When I have an error in an HTML template the error message looks like this:
`ERROR in src/projects/cool-project/src/some/CoolComponent.html(25,108): Property 'cose' does not exist on type 'CoolComponent'. Did you mean 'close'?`

So I have tsc error with "Error in", without and HTML template errors. Additionally the paths of tsc errors are relative to the tsconfig.app.json. The HTML template error paths are relative to angular.json.

The problem of unstandardized messages is also a problem for IDEs. I'm for example really suprised that it seems that nobody so far complained about the fact that there is no "[probem matcher](https://code.visualstudio.com/Docs/editor/tasks#_processing-task-output-with-problem-matchers)" for angular-cli in VSCode. 

And as already mentioned: Karma has reporters. And e.g. TsLint has [formatters ](https://palantir.github.io/tslint/formatters/), EsLint has formatters, too...

The solution for me now would be to write a set of RegExps, but who want's to do this?  😄 

And in my opinion it's not a rare use case that somebody has to parse the output of a compiler into a certain format: IDEs + build management servers.

**Comment by alan-agius4** [comment]
Hi @Franziskus1988, thanks for your feature request. But, currently this doesn't fall in the Angular CLI roadmap. Let's revisit this in the future if there is more interest in the feature.
