### ISSUE TITLE
[ng add]: support for dev dependencies

### ISSUE THREAD

**Issue by dirkluijk** [angular/angular-cli#15409]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [X] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
For our library, we want to provide schematics for the `ng add` command. However, this automatically installs our library as `dependency`. Shouldn't there be a way to install it to the `devDependencies`?

We do add our library to the `devDependencies` our selves (using schematics), but that results in the following warning:

```
Installed packages for tooling via npm.
    ✅️ Added "foo" into devDependencies
    🔍 Installing packages...
UPDATE package.json (980 bytes)
npm WARN The package foo is included as both a dev and production dependency.
```

### Describe the solution you'd like
* Support for an additional `dev` option: `ng add mylib --dev`.
* Update the `npmInstall()` task with an additional `dev: boolean` argument.

This could be done in a backwards compatible way.

### Alternative solution

* Let `ng add` perform an `npm install --no-save`
* Change the `package.json` ourselves

This might be breaking.

**Comment by mgechev** [comment]
This feature makes sense to me. Especially with `ng deploy` there could be more and more dev dependencies that folks want to add to their projects.

Thanks for the PR as well!

**Comment by dirkluijk** [comment]
There are several articles about how to write your own ng-add schematic, but what I understand is that you don't need to run the `addPackageJsonDependency()` yourself? At least not for the package that is installed right?

**Comment by alan-agius4** [comment]
Hi all, this has been addressed via https://github.com/angular/angular-cli/pull/15815

**Comment by alan-agius4** [comment]
You don't need to run `addPackageJsonDependency()` because it will be added to the dependencies via https://github.com/angular/angular-cli/blob/master/packages/angular/cli/tasks/npm-install.ts
