### ISSUE TITLE
Error installing @angular/cli version 8

### ISSUE THREAD

**Issue by munozfj** [angular/angular-cli#15415]
![2019-08-21 18_11_15-Símbolo del sistema error](https://user-images.githubusercontent.com/1012018/63551713-33273e00-c50c-11e9-9233-d7c7a8c5ac94.png)
I am having an issue when I try to install Angular CLI. 
When I write this command on the cmd prompt on Windows 10:

**`npm install -g @angular/cli`**

I get the following error:

> C:\Users\munoz_ps>npm install -g @angular/cli
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit
> (node:18420) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added to [TLSSocket]. Use emitter.setMaxListeners() to increase limit

I'm using the following environment

**Node: 12.9.0
NPM: 6.11.1
OS: MS Windows 10.0.17763.678**

**Comment by mgechev** [comment]
Doesn't seem like an Angular CLI issue. Check this https://github.com/nodejs/node/issues/29239.
