### ISSUE TITLE
Support for user defined bundles

### ISSUE THREAD

**Issue by adamduren** [angular/angular-cli#1541]
Is it possible to define additional bundles in an angular-cli project? I thought it may be possible by defining a second app in the `angular-cli.json` file but this does not appear to be the case. Currently to achieve this I have an external `webpack.config.js` file and I'm running `webpack` to create the separate bundles alongside what angular-cli produces. The end goal would be to be able to create them all with just one command.

**Comment by FraserKillip** [comment]
I would also like a way to add my own plugins to the build process also. For example I would like to add a plugin that will write a .htaccess file to configure HTTP/2 push.

**Comment by adamduren** [comment]
In my particular use case I am building a browser extension. The extension consists on a popup when clicking the extension button which opens an angular application. It also uses injected scripts to enhance the current web page the user is viewing. I would like to use Typescript and have code reuse with the popup window. Currently I am accomplishing it with the separate webpack/gulp script but this requires another command-line and additional tools to be running.

**Comment by iamyojimbo** [comment]
+1

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1633 allows adding more files to be compiled.
