### ISSUE TITLE
Self referencing component doesn't work in Angular 8

### ISSUE THREAD

**Issue by deftomat** [angular/angular-cli#15429]
We just upgrade from v7 to v8.2.3 and now we have the following error:

`Can't resolve all parameters for SectionComponent: (?).`

Component's code:
```
@Component({
  selector: 'section',
  template: '<ng-content></ng-content>'
})
export class SectionComponent {
  constructor(
    @SkipSelf()
    @Optional()
    private parent: SectionComponent | null
  ) {}

  get level(): number {
    return this.parent ? this.parent.level + 1 : 1;
  }
}
```

It worked flawlessly in v7. We are using this component across the whole app as a multiple components depends on level to know how they should render itself.

**Comment by alan-agius4** [comment]
Following a convo with @clydin, unfortunately Typescript doesn’t expose the necessary functionality to make union types work.

**Comment by deftomat** [comment]
@alan-agius4 THANKS! It works.
