### ISSUE TITLE
ng generate library adds tsickle 0.36.0 dependency, incompatible to typescript 3.5

### ISSUE THREAD

**Issue by mscudlik** [angular/angular-cli#15428]
# 🐞 Bug report

### Description

@angular/cli@8.3.0

ng new creates a project for an app, with a dependency to typescript 3.5
ng generate library adds a dependency to tsickle 0.36.0, which is incompatible to typescript 3.5.

as a consequence library providers cannot use typescript 3.5.
Removing the dependency to tsickle will brake ng build my-lib

So either tsickle should be made compatible to typescript 3.5, or the dependency to tsickle should be removed.

also see https://github.com/angular/tsickle/issues/1048

## 🔬 Minimal Reproduction

```shell
ng new lib-test
cd lib-test
ng generate library my-lib
```

![image](https://user-images.githubusercontent.com/545229/63589454-81d6e580-c5a9-11e9-8fb4-8e21b617022a.png)

## 🔥 Exception or Error

If i remove tsickle manually, ng build will not run anymore:

![image](https://user-images.githubusercontent.com/545229/63589673-0cb7e000-c5aa-11e9-9ba7-0f01ed497f27.png)

## 🌍 Your Environment
```shell
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.0
Node: 10.15.0
OS: win32 x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.0
@angular-devkit/build-angular      0.803.0
@angular-devkit/build-ng-packagr   0.803.0
@angular-devkit/build-optimizer    0.803.0
@angular-devkit/build-webpack      0.803.0
@angular-devkit/core               8.3.0
@angular-devkit/schematics         8.3.0
@angular/cli                       8.3.0
@ngtools/webpack                   8.3.0
@schematics/angular                8.3.0
@schematics/update                 0.803.0
ng-packagr                         5.5.0
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
```

**Comment by alan-agius4** [comment]
@mscudlik, if you remove tsickle from your dependencies, you'd need to disable it's usage by setting `annotateForClosureCompiler` to `false` in tsconfig of your library.

**Comment by mscudlik** [comment]
thanks a lot! :)
