### ISSUE TITLE
Is there an easy way to do absolute imports (avoid ../../../) with the default generated project?

### ISSUE THREAD

**Issue by 281330** [angular/angular-cli#1543]
1. OS?  Windows 8.1

2. Versions. angular-cli: 1.0.0-beta.10, node: v6

My src folder has the following structure:

> app
> --feature1
> --feature2
> ----shared
> ------components
> --------uniqueComponent1
> --shared
> ----components
> ------sharedComponent1
> ----services
> main.ts
> system-config.ts
> tsconfig.json
> typings.d.ts

If I am in feature2/shared/components/uniqueComponent1, and I want to import sharedComponent1,

is there a way I can do this without having to do ../../../ many times and instead do something like

`import { SharedComponent1 } from 'app/shared/components/sharedComponent1';`

Please let me know.

**Comment by clydin** [comment]
There will be.  See here: #1465

**Comment by 281330** [comment]
@clydin does the typescript paths only work in typescript 2?

**Comment by filipesilva** [comment]
This issue is being tracked in #1465.
