### ISSUE TITLE
ERROR! package.json already exists

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#15440]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

## Description

Is it normal that I try to initialize the application in the current directory if I have an empty package.json?

## 🔬 Minimal Reproduction

```
$ mkdir ivy && cd ivy
$ npm init
$ npm i @angular/cli@next
$ npx ng new ivy --directory ./
ERROR! package.json already exists.
The Schematic workflow failed. See above.
```

## 🔥 Exception or Error
<pre><code>ERROR! package.json already exists.
The Schematic workflow failed. See above.
</code></pre>

## 🌍 Your Environment
<pre><code>Angular 9 Beta
</code></pre>

I think it would be possible to suggest to the user to replace the current with a new one or merge the files?

**Comment by alan-agius4** [comment]
Hi @splincode this is expected outcome. 

When using `ng new` it is recommended to use a empty directory otherwise you need to make sure that you don't create files which will later be created by the schematic. The schematic itself will not try to merge file contents.
