### ISSUE TITLE
support lazy loading for ng components by default.

### ISSUE THREAD

**Issue by aliabuthahir** [angular/angular-cli#15442]
# 🚀 feature request

### Relevant Package
Angular Components
 This feature request is for @angular/CLI

### Description
It would be better if Angular provides lazy loading of angular components by default.

Reason:
As the total number of components/modules to load in the main angular app increases,
it definitely produces a performance penalty, making the application slower and sluggish.
This happens even for smaller ng apps, when used in conjunction with angular material.  
 
### Describe the solution you'd like
Using the following command:

ng generate component [component-name] 
(or)
ng g c  [component-name]

1. should produce a "module" and the "component" for the given [component-name].
2. The "module" should have pre-configured reference to the "component",  to facilitate lazy loading the component.
3. a corresponding route mapping in the "app routing module" should be generated with a path referring to the  [component-name].

Note: Hope this should provide some productivity improvement, when it comes to coding/dev work. 
* 
### Describe alternatives you've considered
None.

**Comment by alan-agius4** [comment]
Hi @aliabuthahir,

I think what you are looking for already exists in the below form.
```
ng generate module foo --route foo --module app.module
```

**Comment by alan-agius4** [comment]
Closing as the above command does what is requested in the feature request.

In case you had something else in mind, or the above mentioned command doesn't fulfil your needs please fill free to open a new feature request.

Thanks
