### ISSUE TITLE
Module not found: Error: Recursion in resolving

### ISSUE THREAD

**Issue by sorcerb** [angular/angular-cli#15452]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve - (ng serve --aot)
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
This error throw after update to "@angular/cli": "^8.3.0"
All was good with - "@angular/cli": "^7.3.4",
>

### Description
Can't serve project.

## 🔬 Minimal Reproduction
Build work after "ng update codelyzer" with another npm:
devDependencies:
```
codelyzer ~4.2.1->~5.1.0
tslint ~5.9.1" -> ~5.19.0
typescript ~3.2.4 -> 3.5.3
@angular/compiler-cli ^7.2.2 -> ^8.2.3
@angular/language-service ^7.2.2 -> 8.2.3
```

dependencies:
```
@angular/animations ^7.2.7 -> ^8.2.3
@angular/common ^7.2.7 -> ^8.2.3
@angular/compiler ^7.2.7 -> ^8.2.3
@angular/core ^7.2.7 -> ^8.2.3
@angular/forms ^7.2.7 -> ^8.2.3
@angular/platform-browser ^7.2.7 -> ^8.2.3
@angular/platform-browser-dynamic ^7.2.7 -> ^8.2.3
@angular/router ^7.2.7 -> ^8.2.3
zone.js ^0.8.29 -> ^0.9.1
```

And error throw after "ng update @angular/cli @angular/core" 
```
@angular-devkit/build-angular ^7.3.4 -> ~0.803.0
@angular/cli ^7.3.4 -> ^8.3.0
```

I try to update all package to latest version with npm-check-updates, but didn't help to me.

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/@auth0/angular-jwt/src/jwt.interceptor.js
Module not found: Error: Recursion in resolving
Stack:
  resolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) url
  newResolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) url
  parsedResolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) url module
  describedResolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) url module
  resolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) C:\Git\proj\node_modules\url\url.js module
  newResolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) C:\Git\proj\node_modules\url\url.js module
  parsedResolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) C:\Git\proj\node_modules\url\url.js
  describedResolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) C:\Git\proj\node_modules\url\url.js
  resolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) C:\Git\proj\node_modules\url\url.js
  newResolve: (C:\Git\proj\node_modules\@auth0\angular-jwt\src) C:\Git\proj\node_modules\url\url.js

ERROR in (webpack)-dev-server/client/utils/createSocketUrl.js
Module not found: Error: Recursion in resolving
Stack:
  resolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) querystring
  newResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) querystring
  parsedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) querystring module
  describedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) querystring module
  resolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\querystring-es3\index.js module
  newResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\querystring-es3\index.js module
  parsedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\querystring-es3\index.js
  describedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\querystring-es3\index.js
  resolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\querystring-es3\index.js
  newResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\querystring-es3\index.js

ERROR in (webpack)-dev-server/client/utils/createSocketUrl.js
Module not found: Error: Recursion in resolving
Stack:
  resolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) url
  newResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) url
  parsedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) url module
  describedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) url module
  resolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\url\url.js module
  newResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\url\url.js module
  parsedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\url\url.js
  describedResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\url\url.js
  resolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\url\url.js
  newResolve: (C:\Git\proj\node_modules\webpack-dev-server\client\utils) C:\Git\proj\node_modules\url\url.js

ERROR in (webpack)/hot/emitter.js
Module not found: Error: Recursion in resolving
Stack:
  resolve: (C:\Git\proj\node_modules\webpack\hot) events
  newResolve: (C:\Git\proj\node_modules\webpack\hot) events
  parsedResolve: (C:\Git\proj\node_modules\webpack\hot) events module
  describedResolve: (C:\Git\proj\node_modules\webpack\hot) events module
  resolve: (C:\Git\proj\node_modules\webpack\hot) C:\Git\proj\node_modules\webpack\node_modules\events\events.js module
  newResolve: (C:\Git\proj\node_modules\webpack\hot) C:\Git\proj\node_modules\webpack\node_modules\events\events.js module
  parsedResolve: (C:\Git\proj\node_modules\webpack\hot) C:\Git\proj\node_modules\webpack\node_modules\events\events.js
  describedResolve: (C:\Git\proj\node_modules\webpack\hot) C:\Git\proj\node_modules\webpack\node_modules\events\events.js
  resolve: (C:\Git\proj\node_modules\webpack\hot) C:\Git\proj\node_modules\webpack\node_modules\events\events.js
  newResolve: (C:\Git\proj\node_modules\webpack\hot) C:\Git\proj\node_modules\webpack\node_modules\events\events.js
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sorcerb** [comment]
I think in new repo all will be ok without this packages: @auth0, webpack-dev-server and webpack.
I try create repo with this npm.

but, I think problem with tsconfig files:

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "module": "esnext",
    "strict": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "baseUrl": "src",
    "paths": {
      "*": [
        "*",
        "app/*",
        "environments/*"
      ]
    }
  }
}
```

src/tsconfig.app.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "module": "es2015",
    "types": []
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

src/tsconfig.spec.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by sorcerb** [comment]
After test with "new repro-app" the problem is repeated after added to tscondig.json this:
```
    "paths": {
      "*": [
        "*",
        "app/*",
        "environments/*"
      ]
    }
```
