### ISSUE TITLE
'Uncaught ReferenceError: System is not defined' when deploying the /dist contents in a web server

### ISSUE THREAD

**Issue by shijumon** [angular/angular-cli#1545]
> Please provide us with the following information:
> ---------------------------------------------------------------

### 1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
    Windows 10

### 2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular CLI :1.0.0-beta.10
node: 4.4.7
### 3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Created a new app using ng new app2
cd app2
ng build --prod

Created a new application in IIS under Default web sites. 
Set alias name of the application 'testwebapp'
set the physical path to \dist folder generated using ng build command.
Type localhost://testwebapp/index.html in the browser address bar.

It is displaying a 'loading ' message in the browser.
I expected a message 'app works' if the application is deployed correctly.

Console windows shows an error message "Uncaught ReferenceError: System is not defined"

App Created using ng new command.
nothing changed in the code

### 4. The log given by the failure. Normally this include a stack trace and some
   more information.

Uncaught ReferenceError: System is not defined displayed in the console.

### 5. Mention any other details that might be useful.

created a sample application using ng new command.
And deployed the \dist folder in a jetty server.
Same error message appeared when trying to access the http://localhost/testapp/index.html
![system is not defined](https://cloud.githubusercontent.com/assets/7480983/17392208/6ecad00c-5a39-11e6-8b21-78163bbc9695.PNG)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Sounds like a base tag issue to me. When you deploy an app to a server that's not using root, you have to update the base tag to whatever you're serving it from. In your case, that seems to be `/app/`.

**Comment by AlwinZamorins** [comment]
Thanks buddy...... it works :+1: 
Need to change the base url with respect to the path
My baseurl for localhost is:  **href="/"** and for my server is: **href="/testinCode/"**
