### ISSUE TITLE
How to apply tslint.json at generate command

### ISSUE THREAD

**Issue by sculove** [angular/angular-cli#1546]
1. Mac OSX (El Capitan)
2. env 
- angular-cli: 0.0.39
- node: 5.6.0
- os: darwin x64

I changed tslint.json file. 
example. I change indent from `spaces` to `tabs`
```js
"indent": [
      true,
      "tabs" // this code
]
```

and then,
I generate component or service,....
I expect created codes are applied `tab` indent.
but, angular-cli makes files as `spaces` indent.

What should I do this?

**Comment by sculove** [comment]
I solved it.
I thought maybe angular-cli uses `tslint.json` file in `generate` command.
However, angular-cli would seems to refer `.clang-format` file.
I append to `.clang-format` file like this.
```
Language:        JavaScript
BasedOnStyle:    Google
ColumnLimit:     100
IndentWidth: 4
TabWidth: 4
UseTab: ForIndentation
```

Is this right?
Should I synchronize both `tslint.json` and `.clang-format` files?

**Comment by filipesilva** [comment]
None of those files affect file generation. They only affect `tslint` and `clang-format` tooling support as they are configuration files for those tools.
