### ISSUE TITLE
Bootstrap 4 & Angular 8 : not loading bootstrap css

### ISSUE THREAD

**Issue by SubratBarik** [angular/angular-cli#15476]
Hi,

I am using bootstrap 4  and angular 8 and it seems the bootstrap css & js are not loading. Previously, I have easily configured a setup by using bootstrap 3.3.7 and angular 7, it worked like charm but now it is not working with latest versions.

Can you please suggest what I must do to fix the issues.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information .A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by SubratBarik** [comment]
Thank you very much Alan,

I am a newbie to github and angular but I will try my best to provide the related details as much as possible.

I am still working on it and will let you know the updates soon.
