### ISSUE TITLE
Cant find async pipe in library built with cli with ivy enabled

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular-cli#15488]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

The library works with enableIvy: false in the client application, and fails with enableIvy: true,
 

### Description

 A clear and concise description of the problem...
1) Create a library using ng new & ng generate library.  
2) Use async pipe in library.
3) Package library using yarn pack (I assume the same with npm)

4) Create client app using ng new --enableIvy true
5) Add library node module created above
6) Add pipe containing component to app component
5) ng serve & ng build in the client app both work without error, but the app fails in the browser with the following error in the console:

<pre><code>
core.js:6014 ERROR Error: The pipe 'async' could not be found!
    at getPipeDef$1 (core.js:35089)
    at Module.ɵɵpipe (core.js:35055)
    at TestLibComponent_Template (test-lib.js:32)
    at executeTemplate (core.js:12177)
    at checkView (core.js:13615)
    at componentRefresh (core.js:13359)
    at refreshChildComponents (core.js:11858)
    at refreshDescendantViews (core.js:11757)
    at checkView (core.js:13616)
    at componentRefresh (core.js:13359)
defaultErrorLogger	@	core.js:6014
Promise.then (async)		
scheduleMicroTask	@	zone-evergreen.js:542
scheduleTask	@	zone-evergreen.js:381
scheduleTask	@	zone-evergreen.js:211
scheduleMicroTask	@	zone-evergreen.js:231
scheduleResolveOrReject	@	zone-evergreen.js:845
then	@	zone-evergreen.js:955
bootstrapModule	@	core.js:40609
./src/main.ts	@	main.ts:11
__webpack_require__	@	bootstrap:79
0	@	main.ts:12
__webpack_require__	@	bootstrap:79
checkDeferredModules	@	bootstrap:45
webpackJsonpCallback	@	bootstrap:32
(anonymous)	@	main.js:1
</code></pre>

## 🔬 Minimal Reproduction

https://github.com/james-schwartzkopf/ng8-issues/tree/lib-async-pipe-issue

To duplicate clone and run:

```
cd lib-workspace
yarn
ng build test-lib
cd dist/test-lib
yarn pack

cd ../app-workspace
yarn
ng serve

```

Visit the app-workspace page: http://localhost:4200/ and you should see the above error in the browser console (tested in chrome).

## 🔥 Exception or Error
See description

## 🌍 Your Environment
<pre><code>

$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.2.2
Node: 10.15.1
OS: win32 x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.2
@angular-devkit/build-angular      0.802.2
@angular-devkit/build-ng-packagr   0.802.2
@angular-devkit/build-optimizer    0.802.2
@angular-devkit/build-webpack      0.802.2
@angular-devkit/core               8.2.2
@angular-devkit/schematics         8.2.2
@angular/cli                       8.2.2
@ngtools/webpack                   8.2.2
@schematics/angular                8.2.2
@schematics/update                 0.802.2
ng-packagr                         5.5.0
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.38.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi @james-schwartzkopf can you try using Angular 9.0.0-next.4?

**Comment by alan-agius4** [comment]
Hi @@james-schwartzkopf, did it work?

**Comment by james-schwartzkopf** [comment]
Sorry, haven't had a chance to try yet.  I'll try to get around to it today or tomorrow.

**Comment by alan-agius4** [comment]
Closing as per above.
