### ISSUE TITLE
ng lint param for parallel execution for fast CI builds

### ISSUE THREAD

**Issue by BenjaminDiscoVergy** [angular/angular-cli#15482]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
On a CI environment we often have machines with lots of cores. 
The Lint without project argument runs the jobs sequentially in one thread. 
This makes the whole process unnecessarily long. 
In our application we can get the lint time down to a third if we run them in paralel with a wait command at the end. 

### Describe the solution you'd like
A parameter '--parallel' on ng lint that runs all available parts like the parameterless version but in parallel with a wait at the end. 
For each individual job the outputs should be pushed once the job is done so the different jobs don' write across one another. 
Alternatively it could always be launched silently wihout outputs except success/failure at the end. 

### Describe alternatives you've considered
Handcrafting a job that explicitly calls all individual lints and joins them with a wait.

**Comment by alan-agius4** [comment]
Closing since the TSLint builder is deprecated as part of the TSLint deprecation.

More info https://blog.angular.io/version-11-of-angular-now-available-74721b7952f7
