### ISSUE TITLE
Dynamic Lazy Loading using imports with dynamic path is not supported

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/angular-cli#15497]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

I want to use dynamic path in the imports, as follows,

```ts
const Theme = (theme) => {
  return import(`./themes/theme${theme}/theme${theme}.module`).then(mod => mod.ThemeModule);
};
```

Webpack does understand dynamic path in imports, but its not working with Angular CLI. It does identify all the modules correctly, as I get this error when I use this,

 ```
WARNING in ./src/app/themes/theme1/theme1.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/Zama/Desktop/loadable-test/src/app/themes/theme1/theme1.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at /Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

WARNING in ./src/app/themes/theme2/theme2.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/Zama/Desktop/loadable-test/src/app/themes/theme2/theme2.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at /Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

WARNING in ./src/app/themes/theme3/theme3.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/Zama/Desktop/loadable-test/src/app/themes/theme3/theme3.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at /Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

## 🔥 Exception or Error
<pre><code>

WARNING in ./src/app/themes/theme1/theme1.module.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/Zama/Desktop/loadable-test/src/app/themes/theme1/theme1.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:913:23)
    at /Users/Zama/Desktop/loadable-test/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-next.0
Node: 12.8.0
OS: darwin x64
Angular: 9.0.0-next.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.0
@angular-devkit/build-angular     0.900.0-next.0
@angular-devkit/build-optimizer   0.900.0-next.0
@angular-devkit/build-webpack     0.900.0-next.0
@angular-devkit/core              9.0.0-next.0
@angular-devkit/schematics        9.0.0-next.0
@angular/cli                      9.0.0-next.0
@angular/fire                     5.2.1
@ngtools/webpack                  9.0.0-next.0
@schematics/angular               9.0.0-next.0
@schematics/update                0.900.0-next.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I don't think that the above will work for all scenarios since the above above cannot be statically analysed which is needed for the AOT compiler. 

But the problem you are seeing is that those files are not in the compilation. What you need to do is add the theme files, in the include paths of your application's tsconfig.

I am closing this as it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mohammedzamakhan** [comment]
This is something which is possible in Vue CLI applications, check @TheLarkInn presentation https://youtu.be/rn97hCNQsKI?t=509

This would be a great feature in Angular CLI @alan-agius4
