### ISSUE TITLE
Cannot install angular-cli@webpack - proxy reports malware

### ISSUE THREAD

**Issue by tobang** [angular/angular-cli#1549]
I am trying to install angular-cli@webpack, using the following command:

npm install -g angular-cli@webpack

But the installation stops with a 403, when trying to fetch path-case, error code:

npm ERR! fetch failed https://registry.npmjs.org/path-case/-/path-case-2.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 403
loadDep:upper-case-first 

I investigated the problem, and found out that the request is being stopped by our proxy server, because of malware. Here is the proxy server error:

"Based on your corporate access policies, this web site ( http://registry.npmjs.org/path-case/-/path-case-2.1.0.tgz ) has been blocked because it has been determined to be a security threat to your computer or the corporate network. Malware threat iOpus Starr in the category Commercial System Monitor has been found on this site."

Is it malware, or is it false alarm?

Running on Windows 7
Node version: v4.4.7

**Comment by filipesilva** [comment]
You'll have to check that with the repo itself: https://github.com/blakeembrey/path-case
