### ISSUE TITLE
Fix for 2 years old issue StaticInjectorError error when `--bundle-dependencies=all` 

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#15498]
# 🐞 Bug report

This is about the issue reported at https://github.com/angular/angular-cli/issues/8616 .

Its a 2 years old issue with still no fix from Angular team. Since that issue has been closed, I am creating a new issue.

When we set `"bundleDependencies": "all",` in `angular.json` file, which we normally do for SSR/Universal apps (specifically for .net/.net core applications its required), and also have `"optimization": true,`. The generated bundle throws below error:

```
NodeInvocationException: StaticInjectorError(AppServerModule)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object
TypeError: StaticInjectorError(AppServerModule)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object
```

I believe the reason of this is the compress and mangle option of `terser` plugin.

If we set `--keep-fnames` for `terser` plugin for server bundles or when using `"bundleDependencies": "all"`, this issue can be resolved.

> `--keep-fnames`  Do not mangle/drop function names.  Useful for code relying on Function.prototype.name.

I have verified this and it works as mentioned here https://github.com/angular/angular-cli/issues/8616#issuecomment-526843717

**Comment by alan-agius4** [comment]
Thanks @naveedahmed1, I'll be looking at this today or tomorrow!

**Comment by naveedahmed1** [comment]
@alan-agius4  a fix for this issue should also close these issues:

https://github.com/angular/angular-cli/issues/12273
https://github.com/angular/angular-cli/issues/8616
https://github.com/angular/angular-cli/issues/7200

**Comment by alan-agius4** [comment]
Hi @naveedahmed1, the linked issues don’t seem related to
optimization.
