### ISSUE TITLE
Feature request to expose makeTransform and 

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/angular-cli#15500]
Hello,

AngularCompilerPlugin allows users to create custom TypeScript transformers. Here is options: https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/interfaces.ts#L66

I was playing with transformers and approach that plugin uses internally looks very handy.

I think it would be nice to expose this API to users.

I mean exposing: 

```
makeTransform
AddNodeOperation
RemoveNodeOperation
ReplaceNodeOperation
StandardTransform
```

If you don't mind, I can make a PR.

**Comment by alan-agius4** [comment]
Hi @sharikovvladislav, thanks for your interest. I'll put this up for discussion in our next team meeting.

**Comment by sharikovvladislav** [comment]
@alan-agius4 Thank you very much!

**Comment by sharikovvladislav** [comment]
Hm. Actually... Only `platformTransformers` are public API. Not transformers.

Is there any reason for it? Like you don't really want framework users to use transformers or something?

**Comment by vikerman** [comment]
Sorry - These methods are not polished enough to be public and it's difficult to maintain them without breaking. They probably will also go away in the next release. So we are not able to make these public.

**Comment by sharikovvladislav** [comment]
Thank you @vikerman
