### ISSUE TITLE
Can't login on Ubuntu while a terminal is running with ng serve

### ISSUE THREAD

**Issue by Leemonn** [angular/angular-cli#15508]
As title says, If my computer goes to log in screen (because of inactivity) while I have a terminal running "ng serve" it won't let me log in, authentication will fail all the time.

Ubuntu version: 18.04
Angular: 6
Command used: "sudo ng serve"

Thanks in advance.

**Comment by alan-agius4** [comment]
Hi @Leemonn, this doesn't seem to bit a bug within the Angular CLI.

I suggest you to repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli` for support.

Also, I would strongly suggest not to invoke `ng` or any other command with `sudo`.
