### ISSUE TITLE
ng serve doesn't support apps that use routes that don't begin with deployUrl

### ISSUE THREAD

**Issue by slavoroi** [angular/angular-cli#15506]
# 🐞 Bug report
In case you want to serve your static files with a prefix, and use deployUrl in the serve.options.deployUrl section and route to a route that doesn't begin with this deployUrl the index.html isn't served.

### Description
We want to serve all of our static files in the index.html with a certain prefix (to distinguish micro frontend apps with our proxy), for example:
'user-management'. We use deployUrl:'user-management' and reroute to localhost:8095://check/user-management/auth for example and the index.html isn't served (the route is registered as well)
In case you delete ** rewrites** attribute from historyApiFallback in node_modules/@angular-devkit/build-angular/src/dev-server/index.js it works.
Playing with regex servePath didn't help.

## 🔬 Minimal Reproduction
https://github.com/slavoroi/angular-cli-historyapifallback-rewrites-issue
1) npm i
2) ng serve
3) go to 'http://localhost:8095/check/user-management/auth' and index.html isn't served.
4) If you delete those lines it works.

**Comment by alan-agius4** [comment]
Hi @slavoroi, the outcome you are seeing is expected as the deployUrl is set to `user-management` so during development your application is served on `http://localhost:8095/user-management`. 

Incoming requests to the dev server will need to need to match the above servePath. Any requests which don't follow this will be 404'd. So trying to access `http://localhost:8095/check/user-management/auth` is correctly giving you a 404.

Two possible solutions.

1. Set the correct deployUrl ie `check/user-management`
2 If you want to reroute from `http://localhost:8095/check/user-management/auth` to `http://localhost:8095/user-management/auth` set up a proxy to do so. (See: https://angular.io/guide/build#rewrite-the-url-path)

**Comment by slavoroi** [comment]
Our problem that it is not flexible, configurable, our url might be dynamic, for example:
localhost:8095/one/:dynamic/appName.
I was able to configure everything with webpack and now our flexibility is gone.
I know that if we have a certain app like 'user-management' one, best practice is for all url's to begin with it, but we have older apps that don't work like that.
Maybe it's a feature request, but if we could make the historyApiFallback and output publicPath for example more configurable it would be great.
 Or maybe support for regex with deployUrl/baseHref/servePath.

**Comment by alan-agius4** [comment]
@slavoroi, to be quite honest, I think that you were leveraging a bug and what you were doing should not have worked. I don't see how `localhost:8095/one/:dynamic/appName.` will work without a proxy.

You can do something like;
```js
pathRewrite: (path, req) => path.replace('/api', '/base/api');
```

I don't think that we'd like to increase our API surface to allow historyApiFallback configuration. 

Let me chime in @clydin who is more aware of this part of the code.

**Comment by slavoroi** [comment]
We do have a proxy. 
This is a regex for example:
(/user-management/.*|/one/user-management/.*|/one/[^/]+/user-management/.*) 
that redirects to a certain port.
It works with Angularjs and webpack (for example)  just you add in Angular cli (build angular dev server):
```
historyApiFallback:  
**rewrites**: [
                {
                    from: new RegExp(`^(?!${servePath})/.*`),
                    to: context => url.format(context.parsedUrl),
                },
            ],
``` 
It can be configurable to be turned off.

**Comment by clydin** [comment]
Please note that `ng serve` is a development server and intended to be used for local development only.  It does contain a small set of convenience features for simulating some common and basic deployment scenarios but it is not meant to be used to fully mimic an application's deployed state.  There are too many complex and varying scenarios for that to be possible.  The ability to define a custom proxy configuration (`proxyConfig` option) or use a standalone proxy server are intended for more complex scenarios and are quite commonly used.

The `serve-path` option is also available to override the default behavior of setting the serving path to a combination of the deploy URL and base HREF options.  This is used quite frequently for more complex proxy/deploy URL setups.  Also, the history API fallback is solely enabled to support path based routing. Based on the serving path above, `/` is outside the scope of the application and will not be redirected as it cannot be an application route (just as `http://localhost:4200/my-other-app/` would not be but in previous versions it would still be erroneously rewritten).

However, for local development, the primary goal is to develop and test the application itself and in that scenario the usage of a deploy URL or base HREF should ideally not be used.  The settings realisitically only complicate the development process of the actual application and are intended to allow a _built_ application to adapt to its deployment infrastructure. `create-react-app`, for instance, doesn't even allow a public path/deploy URL in development mode.
