### ISSUE TITLE
JIT code not being tree shaken with Ivy and a vendor chunk

### ISSUE THREAD

**Issue by crisbeto** [angular/angular-cli#15505]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Description
When both Ivy and the `vendorChunk` options are turned on, some JIT code isn't being tree shaken from production bundles. The code gets removed correctly if the `vendorChunk` option is turned off.

## 🔬 Minimal Reproduction
To reproduce the issue  and run `ng build --prod`. Once the build is finished, go to the `dist` directory and open the `vendor` bundle.

1. [Clone this repo](https://github.com/crisbeto/ivy-tree-shaking-bug).
2. Run `npm install`.
3. Run `ng build --prod`.
4. Go into the `dist` directory and open the `vendor` bundle file. It should be called something like `vendor-es5.e7633243d6659fd2e6e7.js`.
5. Prettify the file so it's more readable.

At this point try doing a code search for `ng:///`. You should get some code that looks like this:

```js
Object.defineProperty(t, ie, {
configurable: !0,
get: function () {
    return null === i && (i = It().compileNgModule(_p, "ng:///" + t.name + "/ngModuleDef.js", {
    type: t,
    bootstrap: qt(e.bootstrap || bp).map(gt),
    declarations: r.map(gt),
    imports: qt(e.imports || bp).map(gt).map(Sp),
    exports: qt(e.exports || bp).map(gt).map(Sp),
    emitInline: !0,
    schemas: e.schemas ? qt(e.schemas) : null,
    id: e.id || null
    })), i
}
});
```

Since the code is mangled it's a little hard to tell, but these `ng:///` strings come from some JIT-specific code in `@angular/core` that is originally here: https://github.com/angular/angular/blob/master/packages/core/src/render3/jit/directive.ts#L108. This code is only relevant in JIT mode and it shouldn't be in the AOT-compiled production bundle. 

To illustrate the point that the `vendorChunk` option is causing the code to be retained, you can turn off the `vendorChunk` flag in the `angular.json`, run the build again and observe that the code isn't there anymore.

Also this project was created by running `ng new` and then changing the `vendorChunk` option in the `angular.json`.

## 🌍 Your Environment
<pre><code>
@angular-devkit/architect         0.900.0-next.2
@angular-devkit/build-angular     0.900.0-next.2
@angular-devkit/build-optimizer   0.900.0-next.2
@angular-devkit/build-webpack     0.900.0-next.2
@angular-devkit/core              9.0.0-next.2
@angular-devkit/schematics        9.0.0-next.2
@angular/cli                      9.0.0-next.2
@ngtools/webpack                  9.0.0-next.2
@schematics/angular               9.0.0-next.2
@schematics/update                0.900.0-next.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.3

</code></pre>

**Comment by clydin** [comment]
Tree shaking via webpack requires that the modules be within the same bundle.  The vendor chunk option is intended to only be used during development to reduce rebuild roundtrip time.  It should not be used in a production mode.

**Comment by alan-agius4** [comment]
Closing as per above.
