### ISSUE TITLE
Libraries / modules not loaded when editing component template

### ISSUE THREAD

**Issue by rcarjan** [angular/angular-cli#15504]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No (not sure?)

### Description

Hello,
I am having an issue when editing a component inside my project. It appears that the external / third party libraries used in that component are not working anymore after angular recompiles and live-reloads the application. It only appears to happen when editing that specific component.
This affects both `ngx-scrollbar` and `ng-bootstrap`. In order for them to work I have to stop `ng serve` and start it again. 

## 🔬 Minimal Reproduction
I have uploaded the project, which is accessible via the following link:
https://drive.google.com/open?id=12wjnjGc3j633v3S8fZQXkHr-a429umus

The component on which I tested this is `src/app/layouts/partials/sidebar-left`

## 🔥 Exception or Error
No exceptions or errors are thrown, the output from `ng serve`  is normal, even when re building and reloading the page, however neither the scrollbar nor the bootstrap elements (in my case the dropdown) seem to work anymore.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.2
Node: 11.15.0
OS: linux x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cdk                      8.1.4
@angular/cli                      8.3.2
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
@rcarjan I tried downloading your example but I can't seem to be able to. Google drive just sits in "Loading..." after I click the blue "Download" button.

When you say "live-reload" do you actually mean HMR (hot module reloading)? Not all modules are compatible with HMR, and that might be the problem you are seeing.

**Comment by seanmavley** [comment]
also experiencing this along the lines of what's described by @rcarjan. It's weird, to say the least.

`ng serve` gives me this at the moment

![with fresh ng serve](https://user-images.githubusercontent.com/5289083/68078368-b26aa500-fdcc-11e9-87b6-d67c88925a4a.jpg)

Then let's say I add 'hello' to the text in the chip, when live reload comes back, it shows like this:

![with live reload](https://user-images.githubusercontent.com/5289083/68078372-d0d0a080-fdcc-11e9-9158-adbf7c7fc84e.jpg)

**Comment by seanmavley** [comment]
Definitely has something to do with Ivy. I started the project with `enable-ivy`. 

Going in the tsconfigs to disable ivy fixes the weirdness on reload.

Sadly, I'm yet to have a single success story with Ivy, after all the hypes, and at least 3 attempts at using it at different time intervals along its development. Sigh

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
