### ISSUE TITLE
ng build throws Cannot read property 'startTag' of null exception

### ISSUE THREAD

**Issue by procidis** [angular/angular-cli#15503]
I want to publish my Angular 8 app to IIS. Then I've started to follow the deployment instructions. When I build my project on prod mode with base-href, operation throws an error. If I build in development mode(just ng build), there is no error but I have to build in production mode. --base-href causes the error. What can I do now?

Here is error:

> Cannot read property 'startTag' of null TypeError: Cannot read property 'startTag' of null at Object.augmentIndexHtml (D:\ReklamUssuProjects\DevBranch\RULink\RULink.UI\Angular\node_modules@angular-devkit\build-angular\src\angular-cli-files\utilities\index-file\augment-index-html.js:126:55) at compiler.hooks.emit.tapPromise (D:\ReklamUssuProjects\DevBranch\RULink\RULink.UI\Angular\node_modules@angular-devkit\build-angular\src\angular-cli-files\plugins\index-html-webpack-plugin.js:70:60)

I've opened the same issue on stackoverflow link below:
[https://stackoverflow.com/questions/57754746/ng-build-throws-cannot-read-property-starttag-of-null-exception?noredirect=1#comment101946252_57754746](url)

![image](https://user-images.githubusercontent.com/7013177/64110000-94130980-cd89-11e9-8b42-7d86f07c8bcf.png)

**Comment by alan-agius4** [comment]
Can you please share the contents of your index.html?

**Comment by procidis** [comment]
It's an MVC app, so index.html file is empty. But I can share index.cshtml which is under DashboardController
`@{
	ViewBag.Title = "Index";
}
@Styles.Render("~/Content/Angular")

<app-my-app>
	<div class="loader">
		<svg class="circular" viewBox="25 25 50 50">
			<circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
		</svg>
	</div>
</app-my-app>
@Scripts.Render("~/bundles/Angular")

<script>
	//document.addEventListener('wheel', (event, args) => {
	//	//debugger;
	//}, "passive");
</script>`

**Comment by alan-agius4** [comment]
An index file that contains a minimum of html, head and body tags is required.

This issue is also related to https://github.com/angular/angular-cli/issues/11816

**Comment by procidis** [comment]
Man... Thank you very much. Build is now successful and the problem is so easy...

![image](https://user-images.githubusercontent.com/7013177/64111206-c2461880-cd8c-11e9-8f5b-0e4c2486f176.png)
