### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for ItzosTreeSelectionService: (?) after upgrade from 0.803.0 to 0.803.1 or 0.803.2

### ISSUE THREAD

**Issue by Anderman** [angular/angular-cli#15515]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build @angular-devkit/build-angular 0.803.2
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version in which this bug was not present was: @angular-devkit/build-angular 0.803.0
build with --prod give no problems

### Description
class decorated with @Injectable({ providedIn: 'root' }) can't be injected in second class

## 🔬 Minimal Reproduction
I have a component with two classes.
```
@Component({
  selector: 'itzos-tree',
  templateUrl: './tree.component.html',
  styleUrls: ['./tree.component.scss'],
  providers: [ItzosTreeSelectionService, ItzosTreeManageService]
})
```
```
import { SelectionModel } from '@angular/cdk/collections';
import { ItzosTreeManageService, ItzosFlatNode } from './Itzos-tree-manage.service';
import { EventEmitter } from '@angular/core';

export class ItzosTreeSelectionService<TItem> {
  constructor(public manager: ItzosTreeManageService<TItem, any>) { }
```

```
import { MatTreeFlattener, MatTreeFlatDataSource } from '@angular/material/tree';
import { FlatTreeControl } from '@angular/cdk/tree';
import { Injectable } from '@angular/core';

@Injectable({ providedIn: 'root' })
export class ItzosTreeManageService<TItem, T extends IHNode<TItem>> {
  constructor() {

```

## 🔥 Exception or Error
<pre><code>

compiler.js:2175 Uncaught Error: Can't resolve all parameters for ItzosTreeSelectionService: (?).
    at syntaxError (compiler.js:2175)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:20399)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:20294)
    at CompileMetadataResolver._getInjectableTypeMetadata (compiler.js:20512)
    at CompileMetadataResolver.getProviderMetadata (compiler.js:20521)
    at compiler.js:20459
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (compiler.js:20419)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:19910)
    at CompileMetadataResolver.loadDirectiveMetadata (compiler.js:19786)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.2
Node: 10.16.0
OS: win32 x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cdk                      8.1.4
@angular/cli                      8.3.2
@angular/material                 8.1.4
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by alan-agius4** [comment]
@Anderman, from looking at the code above, the issue seems to be that `ItzosTreeSelectionService` is not marked with `@Injectable()`

**Comment by Anderman** [comment]
It wasn't needed in 0.803.0. The component uses 
`providers: [ItzosTreeSelectionService, ItzosTreeManageService]`  And I think the errors is that is about that `ItzosTreeManageService` is not found. That service is marked with `@Injectable()`

**Comment by Anderman** [comment]
I added  `@Injectable()` to the `ItzosTreeSelectionService` and the problem was solved.
It is not clear to me why this is needed but it worked.
@alan-agius4 thx
