### ISSUE TITLE
Update 3rd party libs wiki page with new webpack build

### ISSUE THREAD

**Issue by ghpabs** [angular/angular-cli#1551]
**Versions**
angular-cli: 1.0.0-beta.11-webpack
node: 5.3.0
os: win32 x64

---

[3rd party libs](https://github.com/angular/angular-cli/wiki/3rd-party-libs) content is outdated. It should describe the process of adding 3rd party libs using webpack instead of broccoli.

**Comment by efriandika** [comment]
Help us @filipesilva 💃

**Comment by TheLarkInn** [comment]
I can give some insight if needed. If the third party module can be imported via `npm install`, AND the 3rd party lib is of one of the following JS Module format: (es6, commonjs, commonjs2, amd, typescript), then you can simply import the file into your app (as long as you have valid ambient or global typings for it).

**Comment by TheLarkInn** [comment]
However if you have a `var`, `global` style 3rd party module, you will not be able to include the library. (unless hacking a bit at it). This is going to be feature we add here in the near future.

**Comment by masaanli** [comment]
@TheLarkInn I can confirm this, it is working. I used 'ng-bootstrap' as example form the Angular UI Team.

Now going to try the other libraries I want to use.
Waiting for the guide how to hack a bit hehe.

**Comment by filipesilva** [comment]
I've updated the README to reflect usage of third party libs on the webpack branch. It's way, way easier than before, but as @TheLarkInn mentioned the globals bit of it is still not working.

https://github.com/angular/angular-cli/pull/1633 addresses loading of global CSS as well.
