### ISSUE TITLE
call function object javascript with import on component not working

### ISSUE THREAD

**Issue by jindovu** [angular/angular-cli#15514]
Hi Team,
      I call a function javascript on component typescript file, but it not working, Please help me resolve this issue

Component
```
import '../../../assets/js/gantt/ganttMaster.js';
export class TaskComponent implements OnInit {

  constructor() {}

  ngOnInit() {
    var r = new GanttMaster();
  }
}
```

Error: 
![image](https://user-images.githubusercontent.com/19401173/64226053-11fd1f00-cf08-11e9-8a09-245c9b71f3cb.png)

Thank you.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
