### ISSUE TITLE
Error related 'ember-cli-live-reload.js' is missing (not loading) while using Express server

### ISSUE THREAD

**Issue by Headcult** [angular/angular-cli#1552]
Hi, I'm getting the following error while using Express server to serve content generated by the Angular-CLI sample app.:

`http://localhost:4200/ember-cli-live-reload.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)
`

OS:  Windows 7

Versions:

- angular-cli: 1.0.0-beta.10
- node: 5.11.1
- os: win32 x64
- express: 4.13.4

Repro steps:

After accessing the URL after starting the app using `ng serve` or `node server.js`, this error appears in the Chrome Developer Toolbar:
``http://localhost:4200/ember-cli-live-reload.js Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

This exception in the console:
`TypeError: res.status is not a function
    at C:\xxxx\server.js:43:7
    at Layer.handle [as handle_request] (C:\xxxx\node_modules\express\li
b\router\layer.js:95:5)
    at trim_prefix (C:\xxxx\node_modules\express\lib\router\index.js:312
:13)
    at C:\xxxx\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\xxxx\node_modules\express\lib\router\
index.js:330:12)
    at next (C:\xxxx\node_modules\express\lib\router\index.js:271:10)
    at SendStream.error (C:\xxxx\node_modules\serve-static\index.js:121:`

Any workaround or a fix for this issue? Has anyone tried using Express on the Angular-CLI?

**Comment by filipesilva** [comment]
If you want to use another server other than the ones provided by `angular-cli`, you'll need to first do `ng build` and then server the resulting app from `dist/`. Otherwise you're serving the source files and not a built application.
