### ISSUE TITLE
Compile production copy with different themes, depending on parameter

### ISSUE THREAD

**Issue by nickykapur** [angular/angular-cli#15521]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 the problem is, that there should be a way to send parameters to the build, serve command to know which themes to use when building a pack for production.

### Describe the solution you'd like
 It would be nice the common CSS file should be able to support multiple css files, and while building the application ng build .. --prod [ParameterA or ParameterB or ...], not only for CSS even for specific images or logos on the site.

depending the parameter it will build with a different CSS file. This will be useful when creating a single product for multiple clients, give them a personalized experience and theme

**Comment by alan-agius4** [comment]
Hi @nickykapur, I think what you are looking already existing and can be achieved by having different build configurations.

Here is a simple extract of how you can do it.

Example
```json
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
      ...
  },
  "configurations": {
    "production": {
      ...
    },
    "theme-1": {
      ...
      "assets": [
            "src/favicon.ico",
            "src/theme-1"
       ]
      },
    "theme-2": {
       ...
       "assets": [
          "src/favicon.ico",
          "src/theme-2"
        ]
      }
  }
}
```

```cmd
ng build --configuration theme-2
ng build --configuration theme-1
```

**Comment by nickykapur** [comment]
Thanks, I think it correctly describes my issue!
