### ISSUE TITLE
Begin automatically locking inactive closed issues

### ISSUE THREAD

**Issue by josephperrott** [angular/angular-cli#15532]
As part of a larger effort across the Angular organization, we will begin locking issues which are closed and have not been interacted with in the last 30 days.

You can [read more about our automatic conversation locking policy](https://github.com/angular/angular/blob/67d80f/docs/GITHUB_PROCESS.md#conversation-locking).

**Comment by devoto13** [comment]
Is it possible to mute the bot? It was extremely annoying sending dozens of useless notifications per day.

**Comment by clydin** [comment]
Unfortunately, not that I am aware.  You can, however, setup an email filtering rule to immediately delete the emails.

The good news is the backfilling is almost complete for this repository.
