### ISSUE TITLE
tsconfig update schematics break lazy loaded module compilation for old configs

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#15539]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] update
```

### Is this a regression?
Yes

### Description
When I update from 8.3.0.next to 9.0.0-next.3, schematics are run that break the compilation of my lazy loaded modules.

I believe this is caused by a CLI generated tsconfig that was `ng new`ed before the tsconfig.app.json split.

## 🔬 Minimal Reproduction
```
git clone git@github.com:StephenFluin/fluin.io.git
cd fluin.io
git checkout 1b79500152670ea75587feac592400e7be57099d
yarn
ng update @angular/core@next @angular/cli@next
```

This adds `files` to my `src/tsconfig.json`, which prevents the compilation of my lazy loaded modules.

You can see that the lazy module is not built with `ng build --prod`

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.3
Node: 10.11.0
OS: linux x64
Angular: 9.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.3
@angular-devkit/build-angular     0.900.0-next.3
@angular-devkit/build-optimizer   0.900.0-next.3
@angular-devkit/build-webpack     0.900.0-next.3
@angular-devkit/core              9.0.0-next.3
@angular-devkit/schematics        9.0.0-next.3
@angular/cdk                      8.1.1
@angular/cli                      9.0.0-next.3
@angular/fire                     5.2.1
@angular/material                 8.1.1
@ngtools/webpack                  9.0.0-next.3
@schematics/angular               9.0.0-next.3
@schematics/update                0.900.0-next.3
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.3

</code></pre>

**Comment by alan-agius4** [comment]
Hi @StephenFluin, that is expected since at the moment with Ivy we only support the new syntax of lazy loading aka using the `import()`

Maybe we should re-run the migration for lazy loading in version 9 as well?

**Comment by StephenFluin** [comment]
Hrm, you are right that I'm using the legacy loadChildren, this is
unexpected. I have no idea how I got to v9 without this being automatically
fixed. (I update and downgrade versions a lot while testing new releases,
so that might be the cause specific to me).

If there is a possible path that doesn't apply this schematic (because I
exclusively use ng update), is there any downside to re-running that
schematic?

**Comment by alan-agius4** [comment]
@StephenFluin, the only downside of rerunning the schematic is that ng update will take some more time to execute. Other than that there isn’t.
