### ISSUE TITLE
Enviroment.ts not overwritten in Webpack anymore

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#1553]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: local (v1.0.0-beta.10, branch: master)                                                                                                                                                       
node: 6.2.2                                                                                                                                                                                               
os: win32 x64   
(webpack branch)

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Added an option to the Enviroment files called apiUrl and then just tried 'ng serve' or 'ng build --prod'.

Nothing changes inside the enviroment.ts file.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
You shouldn't see the file itself change, since webpack always bundles it with your app. If you open `main.bundle.js` you should see its contents there.

**Comment by masaanli** [comment]
@filipesilva I don't know what you mean, but if i build for production or development the ApiURl which i used in the enviroment file isn't replaced. It always stays the same. 

But I have 2 different Api Urls for Development and Production :+1:

**Comment by filipesilva** [comment]
Can you provide me with a repo where this happens so I can debug?

**Comment by masaanli** [comment]
@filipesilva it's just very easy, 

use the webpack.1 or webpack.2 version.

ng new projectname

change enviroment.dev.ts with an apiUrl or change the production boolean to true.

Do ng build or ng serve.

Then the enviroment.ts is not overwritten, just tested it.

**Comment by filipesilva** [comment]
The `environments.ts` file is never overwritten, instead during build time we use the other ones. Nothing in your `src` folder changes when you do `ng build`. Instead, a build application is created on the `dist` folder.

You can open `dist/main.bundle.ts` and see that your whole app is bundled in that file. If you search for `apiUrl` you should find it there.
