### ISSUE TITLE
Where are the Typings

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#1554]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
**angular-cli: local (v1.0.0-beta.10, branch: master)                                                                                                                                                       
node: 6.2.2                                                                                                                                                                                               
os: win32 x64   
(webpack branch)**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**1. I'm not seeing a Typings folder anymore? How is AngularJS comes now with intellisesnse, because I see that it has intellisense?**
**2. What about third party libraries with Typings? How to do that then?**
**3. What does the @ before a package mean? Has this something to do with it or importing?**

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
look in your package.json file.
```
"@types/jasmine": "^2.2.30",
"@types/protractor": "^1.5.16",
```
To add new typings using npm as the manager. 
For example to install moment typings
```
npm install --save-dev @types/moment
```

**Comment by masaanli** [comment]
@deebloo ok thanks.

Q: At the imports of Angular I'm seeing @ in front, what does that mean?

**Comment by AlexDede** [comment]
@masaanli https://docs.npmjs.com/misc/scope

**Comment by masaanli** [comment]
@alexeagle  So if you install Lodash you're installing it normal or also as a @?

**Comment by AlexDede** [comment]
@masaanli  You must install Lodash without @
`npm install --save lodash`

**Comment by deebloo** [comment]
@masaanli it doesn't have anything to do with angular or the cli. it is a way of having scoped npm packages

**Comment by filipesilva** [comment]
We've recently updated the readme to reflect the new third party lib journey in the webpack branch: https://github.com/angular/angular-cli#3rd-party-library-installation

That, together with the excellent replies so far in this thread, seem to answer your questions so I am closing the issue.

**Comment by arunvelsriram** [comment]
@filipesilva new link is here: [https://github.com/angular/angular-cli/wiki/stories-third-party-lib]()

**Comment by sandeepselenia** [comment]
jkj
