### ISSUE TITLE
EEXIST: file already exists on ng build

### ISSUE THREAD

**Issue by 360disrupt** [angular/angular-cli#15544]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?

The problem occurred after updating `angular` and `angular-cli` (don't know the prev version).

### Description

Angular-cli complains about an already existing file in the node_modules cache. The problem can be (temporarily) solved by deleting `.cache` with `rm -rf node_modules/.cache` but reoccurs one build later again.

## 🔬 Minimal Reproduction

-  ng build --prod --extra-webpack-config webpack.extra.js

The project is on:
https://github.com/grassberry-high/grow-frontend

## 🔥 Exception or Error
<pre><code>

An unhandled exception occurred: EEXIST: file already exists, copyfile '/Users/user/Projekte/1-NODEJS/some-project/some-pi/frontend/node_modules/.cache/angular-build-dl/content-v2/sha512/36/86/afb82f76da09848c154ccb79a5213dc67698763412e526216fbce17a94bd0b1762da3627677b3ee97a05cdc837739fdc4dbdc08b13fbd50cbb0fb9a0b512' -> '/Users/user/Projekte/1-NODEJS/some-project/some-pi/frontend/dist/gh-frontend/runtime.24b02acc1f369d9b9f37.js'
See "/private/var/folders/q_/dr0933813977s5p6g5l754cc0000gn/T/ng-KwQpJ9/angular-errors.log" for further details.

</code></pre>

angular-errors.log

<pre><code>
    [error] Error: EEXIST: file already exists, copyfile '/Users/user/Projekte/1-NODEJS/some-project/some-pi/frontend/node_modules/.cache/angular-build-dl/content-v2/sha512/36/86/afb82f76da09848c154ccb79a5213dc67698763412e526216fbce17a94bd0b1762da3627677b3ee97a05cdc837739fdc4dbdc08b13fbd50cbb0fb9a0b512' -> '/Users/user/Projekte/1-NODEJS/some-project/some-pi/frontend/dist/gh-frontend/runtime.24b02acc1f369d9b9f37.js'
at Object.copyFileSync (fs.js:1743:3)
at SwitchMapSubscriber.rxjs_1.from.pipe.operators_1.switchMap [as project] (/Users/user/Projekte/1-NODEJS/some-project/some-pi/frontend/node_modules/@angular-devkit/build-angular/src/browser/index.js:332:28)
</code></pre>

## 🌍 Your Environment
<pre><code>
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cdk                      7.2.0
@angular/cli                      8.3.0
@angular/material                 7.2.0
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

Mac OSX

**Comment by alan-agius4** [comment]
Hi, which Node version are you using? Can you try to update to `@angular-devkit/build-angular     0.803.3`?

**Comment by 360disrupt** [comment]
Node version: `v11.15.0`
Updated the package, but the error persists.

**Comment by alan-agius4** [comment]
Can you try to below steps please?

```
rm -rf dist
npm i @angular-devkit/build-angular@0.803.3 --save-dev
ng build --prod --extra-webpack-config webpack.extra.js
```

Thanks

**Comment by clydin** [comment]
Please be aware that Node.js v11 is EOL and is no longer supported.  Can you try with v10.16.0+ or v12.0.0+?  There is a known defect with file copying with MacOS on version less than those.

**Comment by 360disrupt** [comment]
@alan-agius4 these steps trigger the same problem. 
@clydin I'll try to upgrade everything the next days, I had some problems recently with upgrading/or I'll use a diff. node version for backend/frontend. I'll come back.
