### ISSUE TITLE
Registering lazy routes (dynamic import) at runtime

### ISSUE THREAD

**Issue by mbinic** [angular/angular-cli#15556]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
With the [string loadChildren syntax deprecated](https://angular.io/api/router/DeprecatedLoadChildren) in Angular 8, in favor of the [dynamic import syntax](https://angular.io/api/router/LoadChildrenCallback), it seems it will no longer be possible to register lazy routes at runtime.

Please note that by adding lazy routes at runtime, I'm not referring to loading modules completely unknown to Webpack. These modules would be part of libs that are compiled together with the application, so the chunks would be known to Webpack, but routes would only be added to the router config as a result of a Web API call.

### Describe the solution you'd like
Basically, I'd like to be able to do the following (from a component or e.g. a ngrx effect), and successfully navigate to the new route and its children, while using JIT, AOT and with Ivy (AOT):

```javascript
this._router.config.unshift({
  path: 'dynamic',
  loadChildren: () => import(modulePathReceivedFromServer).then(m => m[moduleNameReceivedFromServer])
});
this._router.resetConfig(this._router.config);
```

With dynamic imports working this way, one could also easily load lazy modules on demand/without routing to them (currently possible with the [deprecated SystemJsNgModuleLoader](https://angular.io/api/core/SystemJsNgModuleLoader)).

### Describe alternatives you've considered
The only alternative I can think of is a Webpack plugin doing something similar to what the `AngularCompilerPlugin` does in `contextModuleFactory.afterResolve`.
You can see my detailed analysis, with a simple demo app and the solutions I could think of here: https://github.com/mbinic/dynamic-lazy-routes#dynamic-lazy-routes-experiment. The last few commits show the code using JIT, AOT and Ivy (AOT), route adding code being almost identical for all cases.

Constructive criticism from the experts is the best way to learn, so I'd love to get your input even if you think this is a bad idea or just plain nonsense. And I'd gladly make a PR if this is something you'd support, to angular-cli and webpack :)

**Comment by alan-agius4** [comment]
Hi @mbinic, thanks for opening the issue and looking at alternatives and possible fixes.

With dynamic imports the CLI doesn't need to analyze them anymore and we'd very much like to keep it this way. Webpack still needs to know what could be imported so it can bundle as needed. You can possible use magic comments for your use case https://webpack.js.org/api/module-methods/#magic-comments

**Comment by mbinic** [comment]
Hi @alan-agius4, I understand, makes sense.
Does this mean that the `lazyModules` property of `architect.build.options` is also going away from angular.json? Looks like it won't be needed, cause Webpack will be able to create the chunks just based on the (constant string) path given to `import`...

**Comment by alan-agius4** [comment]
@mbinic, yes indeed.
