### ISSUE TITLE
Angular Live Development Server is not working

### ISSUE THREAD

**Issue by VicenteT** [angular/angular-cli#15564]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 I don't think so, It's the first time I see this.

### Description

 Basically, I run the command `ng serve` and the output in console is correct but when I try to enter in the web site "http://localhost:4200/" It keeps waiting for localhost response forever. There are not message in console and the screen is white. It's strange because five days ago It was working.

I have try to reinstall node and angular-cli. Furthermore I have mysql and PHP in localhost running without problems.

## 🔬 Minimal Reproduction

Just run `ng serve`.

## 🔥 Exception or Error
<pre><code>

There is not exception warnings.

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.3.9
Node: 10.16.3
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.1.6
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

This issue is occurring in all browsers.

**Comment by alan-agius4** [comment]
Hi, in order to determine if this is an issue caused by the CLI. We’d require a bit of more details.

Such as what changed between when it was working until it stopped working? Are you
using any proxies or have proxy settings in the browser?

Does this happen on a newly generated application? `npm @angular/cli@latest new test-project`

**Comment by VicenteT** [comment]
Hello @alan-agius4 , I can't detect exactly what happened to crash, last week was working. I don't have proxies.

Sorry, I forgot to say that I have tried in other app and generating a new one too. I fact I just try again with a new project and nothing...

**Comment by VicenteT** [comment]
False alarm, It was in conflict with the antivirus. Thanks.
