### ISSUE TITLE
How to debug

### ISSUE THREAD

**Issue by vivdkool** [angular/angular-cli#1556]
almost fed up not able to debug cli generated code tried webstorm, vscode, augury no sucess can any one help me..... 

Augury also not even getting component.

augury screenshot...

![image](https://cloud.githubusercontent.com/assets/10462445/17426843/598923cc-5af9-11e6-8d28-a1da543a430d.png)

**Comment by filipesilva** [comment]
You'll have to check with those tools directly. We don't have any kind of direct integration with them, and since the apps run in the browser I have to assume it's an issue with debugger config.
