### ISSUE TITLE
New sass-loader doesn't use stylePreprocessorOptions.includePaths

### ISSUE THREAD

**Issue by ca136** [angular/angular-cli#15588]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, it looks like this was introduced in ` "@angular-devkit/build-angular": "0.900.0-next.4"` or with this change: https://github.com/angular/angular-cli/pull/15487

### Description

The new build doesn't respect the `stylePreprocessorOptions.includePaths` options in the angular.json file. It looks like sass-loader may have changed how it handled includePaths:
https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#features

## 🔬 Minimal Reproduction
1. set up a new project that uses sass or use an existing project
2. add a path to a sass global file in your angular.json stylePreprocessorOptions.includePaths list
3. try to import that path in another scss file
4. run a build
 

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/scss/main.scss
Module build failed (from /project/node_modules/@angular-devkit/build-angular/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from /project/node_modules/sass-loader/lib/loader.js):

@import 'abstracts';
^
      File to import not found or unreadable: abstracts.
      in /project/apps/site/src/scss/main.scss (line 2, column 1)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.4
Node: 10.16.3
OS: darwin x64
Angular: 9.0.0-next.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.1
@angular-devkit/build-angular              0.900.0-next.4
@angular-devkit/build-optimizer            0.900.0-next.4
@angular-devkit/build-webpack              0.801.1
@angular-devkit/core                       8.1.1
@angular-devkit/schematics                 8.1.1
@angular/cdk                               8.2.0
@angular/cli                               9.0.0-next.4
@angular/elements                          8.2.6
@angular/http                              7.2.15
@angular/localize                          9.0.0-next.5
@angular/material                          8.2.0
@ngtools/webpack                           9.0.0-next.4
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.3
@schematics/update                         0.900.0-next.4
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.35.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by kumaresan-subramani** [comment]
For me,

it is working fine in angular version - 8.3.4

**Comment by mstawick** [comment]
`ng update` bump sass-loader to version `^8.0.0`, and that's what breaks the build - it seems they've changed options interface. For me, it works to revert sass-loader version to `^7.2.0`

**Comment by clydin** [comment]
I am unable to replicate this with a newly created project using the latest prerelease version of the CLI (9.0.0-next.5).  Can you please provide a minimal reproduction that demonstrates the problem?

From the version output, it also appears that there are a variety of different Angular package major versions present (7,8, and 9 prerelease).  This is not recommended and may be the source of some of the errors.

**Comment by ca136** [comment]
The fix for me was to manually install `sass-loader@8` 

`@nrwl/angular` was requiring `sass-loader@7` which led to the error above 🤦‍♂
