### ISSUE TITLE
@angular-devkit/build-angular:v0.803.4 build fails for differential loading with optimization=true

### ISSUE THREAD

**Issue by loremaps** [angular/angular-cli#15580]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
`@angular-devkit/build-angular:v0.803.3`

### Description

 A clear and concise description of the problem...

Build fails with the latest `@angular-devkit/build-angular:v0.803.4` if `optimization` is enabled i.e.
`ng build --optimization=true`

## 🔬 Minimal Reproduction

I tried to create a new app to reproduce it without success yet and I am afraid I cannot share the repo either.
But I did some digging and it seems related to fix 7a75c4cd215f06986b31afd85018ba918533a38d and differential loading. If I set my `browserlist` to `last 1 Chrome versions` the build is OK. 

## 🔥 Exception or Error
<pre><code>

[error] SyntaxError: /home/panos/ui/dist/vendor-es2015.js: Unexpected reserved word 'arguments' (1:2704314)

[0m[31m[1m>[22m[39m[90m 1 | [39m(window[33m.[39mwebpackJsonp[33m=[39mwindow[33m.[39mwebpackJsonp[33m||[39m[])[33m.[39mpush([[[35m21[39m][33m,[39m{[32m"/Co4"[39m[33m:[39m[36mfunction[39m(module[33m,[39m__webpack_exports__[33m,[39m__webpack_require__){[32m"use strict"[39m[33m;[39m__webpack_require__[33m.[39md(__webpack_exports__[33m,[39m[32m"a"[39m[33m,[39m[36mfunction[39m(){[36mreturn[39m [33mMatAutocomplete[39m})[33m,[39m__webpack_require__[33m.[39md(__webpack_exports__[33m,[39m[32m"b"[39m[33m,[39m[36mfunction[39m(){[36mreturn[39m [33mMatAutocompleteModule[39m})[33m,[39m__webpack_require__[33m.[39md(__webpack_exports__[33m,[39m[32m"c"[39m[33m,[39m[36mfunction[39m(){[36mreturn[39m [33mMatAutocompleteTrigger[39m})[33m;[39m[36mvar[39m _angular_cdk_a11y__WEBPACK_IMPORTED_MODULE_0__[33m=[39m__webpack_require__([32m"5GAg"[39m)[33m,[39m_angular_cdk_coercion__WEBPACK_IMPORTED_MODULE_1__[33m=[39m__webpack_require__([32m"KCVW"[39m)[33m,[39m_angular_core__WEBPACK_IMPORTED_MODULE_2__[33m=[39m__webpack_require__([32m"8Y7J"[39m)[33m,[39m_angular_material_core__WEBPACK_IMPORTED_MODULE_3__[33m=[39m__webpack_require__([32m"Xd0L"[39m)[33m,[39m_angular_cdk_bidi__WEBPACK_IMPORTED_MODULE_4__[33m=[39m__webpack_require__([32m"IP0z"[39m)[33m,[39m_angular_cdk_keycodes__WEBPACK_IMPORTED_MODULE_5__[33m=[39m__webpack_require__([32m"dvZr"[39m)[33m,[39m_angular_cdk_overlay__WEBPACK_IMPORTED_MODULE_6__[33m=[39m__webpack_require__([32m"QQfA"[39m)[33m,[39m_angular_cdk_platform__WEBPACK_IMPORTED_MODULE_7__[33m=[39m__webpack_require__([32m"/HVE"[39m)[33m,[39m_angular_cdk_portal__WEBPACK_IMPORTED_MODULE_8__[33m=[39m__webpack_require__([32m"zMNK"[39m)[33m,[39m_angular_cdk_scrolling__WEBPACK_IMPORTED_MODULE_9__[33m=[39m__webpack_require__([32m"hOhj"[39m)[33m,[39m_angular_common__WEBPACK_IMPORTED_MODULE_10__[33m=[39m__webpack_require__([32m"SVse"[39m)[33m,[39m_angular_forms__WEBPACK_IMPORTED_MODULE_11__[33m=[39m__webpack_require__([32m"s7LF"[39m)[33m,[39m_angular_material_form_field__WEBPACK_IMPORTED_MODULE_12__[33m=[39m__webpack_require__([32m"HsOI"[39m)[33m,
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.4
Node: 12.10.0
OS: linux x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.0
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by timurso** [comment]
I have just updated build-angular too and it fails with the same message (also it is printing the whole minified string main.js bundle in the console - one gigantic string - which is not useful at all).
We are using Heap and Smartlook analytics, and it's their official init scripts in our index.html files that are failing because they do use "arguments" keyword.

**Comment by lazar-vuckovic** [comment]
Having the same issue with our application after finally upgrading it from Angular 7 to 8.
When I changed the lines in `common.js` to `ecma: 5`, per @clydin comment, the build executed without any errors.

**Comment by wwarby** [comment]
I'm still hitting this problem in v0.803.5 and no later version appears to be available on NPM - is that expected? For now I've just rolled back to v0.803.3.

**Comment by clydin** [comment]
Patch releases are generally released every Wednesday.  This will be in .6.
