### ISSUE TITLE
Vertical scroll bar in default page

### ISSUE THREAD

**Issue by bhanu2507** [angular/angular-cli#15596]
![ng8](https://user-images.githubusercontent.com/6113406/64857776-2dbc9f80-d643-11e9-9db1-fa9293440a9c.png)

ng CLI Version : 8.3.4

**Comment by alan-agius4** [comment]
Which browser are you using?

**Comment by alan-agius4** [comment]
//cc @sjtrimble

**Comment by bhanu2507** [comment]
chrome 76
