### ISSUE TITLE
warning 'Option "vendorSourceMap" is deprecated.' is not actionable

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular-cli#15599]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I ran:

```
ng build  --vendor-source-map
```
and got the following warning: `Option "vendorSourceMap" is deprecated.`

I looked around but couldn't find any information about this deprecation, primarily what should I use instead to generate source maps that take vendor source maps into consideration.

## 🔬 Minimal Reproduction

```
ng build  --vendor-source-map
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-next.4
Node: 10.13.0
OS: darwin x64
Angular: 9.0.0-next.6+52.sha-8415460
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.4
@angular-devkit/build-angular     0.900.0-next.4
@angular-devkit/build-optimizer   0.900.0-next.4
@angular-devkit/build-webpack     0.900.0-next.4
@angular-devkit/core              9.0.0-next.4
@angular-devkit/schematics        9.0.0-next.4
@angular/cdk                      8.0.0
@angular/cli                      9.0.0-next.4
@angular/material                 8.0.0
@ngtools/webpack                  9.0.0-next.4
@schematics/angular               9.0.0-next.4
@schematics/update                0.900.0-next.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.3
</code></pre>

**Anything else relevant?**

**Comment by rbirkgit** [comment]
I am wondering as well. I keep using this flag and luckily it seems to still work. Maybe the deprecation 
 warning should be removed if there are no alternatives?

**Comment by alastair-todd** [comment]
So the question on everyone's lips is how to replicate the "advanced" `sourceMap `option from `angular.json` config on the command line?

```
 "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "sourceMap": {
              "scripts": true,
              "styles": true,
              "vendor": true
            },
```

**Comment by kyliau** [comment]
As suggested in https://github.com/angular/angular-cli/pull/17511, the new option is `sourceMap.vendor`.
