### ISSUE TITLE
Separate/Fork Schematics from Angular

### ISSUE THREAD

**Issue by cafesanu** [angular/angular-cli#15601]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] none
```

### Description
Hi there!

I've been using Angular for years and have been an Angular fan since the beginning! Sadly, my company switched to React (sigh...)

Having been in ng-conf, I learned about Nrwl and their nx tool. Because of it, we are starting to use React for FE and have a Nest application as well. All of it generated by the Nrwl nx tool. Nrwl uses schematics under the hood to upgrade the React app as well as the Nest app, in the same way `ng update` does it for Angular. If I take a look at the `node_modules`, of course `@angular` is there. So, even if I use React and Nest, I'm using `@angular` under the hood 🤔...

So, my question is... Have you folks think about separating/forking schematics from Angular and make it its own beast?

Schematics is an awesome tool that in reality has nothing to do with the Angular framework. The whole community could benefit from it regardless of whether they use Angular.

React, Vue, Angular, Ember, Svelte, Nest, Express... you name it... They all could be using it if the use TS! Maybe even another languages other than TS could be using it by providing their own tree parser???... the sky is the limit!

### Describe the solution you'd like
In my opinion, Schematics is bigger than Angular and deserves recognition by itself! It could be simply named Google Schematics! Just another awesome open source project made by Google.

Opinions??

Thanks folks!!! Already missing Angular 😢

**Comment by mgechev** [comment]
Hey @cafesanu, you can use schematics completely independently from the Angular framework itself. Schematics offers a collection of APIs that allow you to transform files and it doesn't have to do anything with how Angular, a framework for the development of user interface, works. In other words, if you're using schematics:
- Your application does not depend on Angular (i.e., the framework is not part of your app bundle)
- You don't have to understand any of the concepts that the framework offers

We're hosting schematics under a devkit scoped package (`@angular-devkit/schematics`). Distributing the package under a different name will increase the maintenance cost without offering any benefits. The functionality is already framework agnostic and you can use it with your technology of choice.

I'm delight that you're finding packages from our ecosystem useful! You can rely on us that we'll maintain the high standards you expect :).
