### ISSUE TITLE
CSS selector :not(:read-only) has no effect with configuration production

### ISSUE THREAD

**Issue by mab** [angular/angular-cli#15618]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [x] build
- [x] serve
```

### Is this a regression?

I don't know. The issue is present in Angular 7.3.9 and 8.3.4

### Description

Using a `&:not(:read-only)` selector works fine using `ng serve` but does not work using `ng serve --prod`. Same is true for `ng build`.

## 🔬 Minimal Reproduction

* Minimal example Angular 7.3.9: https://github.com/mab/readonly
* Minimal example Angular 8.3.4: https://github.com/mab/readonly8

### Manual steps to reproduce

1. `ng new readonly8 --style=scss`
2. Adapt `app.component.html`
```
Readonly
<input type="text" name="my-read-only-field" value="a read-only value" readonly><br />
Writable
<input type="text" name="my-writable-field">
```
3. Adapt `app.component.scss`
```
input[type='text'] {
	&:read-only {
		border: none;
	}
	
	&:not(:read-only) {
		border: 1px solid red;
	}
}
```
4. Run `ng serve` -> result as expected
![image](https://user-images.githubusercontent.com/207018/65036909-d2452700-d94c-11e9-839b-b925f3630511.png)
5. Run `ng serve --prod` -> `:not` selector does not work
![image](https://user-images.githubusercontent.com/207018/65036992-0c162d80-d94d-11e9-9503-0d9ed10cd01f.png)

## 🔥 Exception or Error

There are no exceptions or errors. The behavior between `ng serve` and `ng serve --prod` is unexpectedly different.

## 🌍 Your Environment
<pre><code>Angular CLI: 8.3.4
Node: 12.10.0
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cli                      8.3.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

## Releated Issues:

#8577

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [clean-css](https://github.com/jakubpawlowicz/clean-css) project or file an issue on their issue tracker.

As a workaround you can disable optimisation for the problematic part using the `clean-css ignore` comments.

```css
input[type='text'] {
    color: blue;

    &:read-only {
        border: none;
    }

    /* clean-css ignore:start */
    &:not(:read-only) {
        border: 1px solid red;
    }
}
/* clean-css ignore:end */
```
