### ISSUE TITLE
Windows 10 @angular/cli install problem

### ISSUE THREAD

**Issue by zebalu** [angular/angular-cli#15615]
# 🐞 Bug report
npm install fails on windows 10

### Description

    npm install -g @angular/cli

the above command fails with the following output:

    C:\Users\zebal\scoop\persist\nodejs\bin\ng -> C:\Users\zebal\scoop\persist\nodejs\bin\node_modules\@angular\cli\bin\ng
    
    > @angular/cli@8.3.4 postinstall C:\Users\zebal\scoop\persist\nodejs\bin\node_modules\@angular\cli
    > node ./bin/postinstall/script.js
    
    C:\Users\zebal\scoop\persist\nodejs\bin\node_modules\@angular\cli\bin\postinstall\analytics-prompt.js:8
    (async () => {
           ^
    SyntaxError: Unexpected token (
        at createScript (vm.js:56:10)
        at Object.runInThisContext (vm.js:97:10)
        at Module._compile (module.js:542:28)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (C:\Users\zebal\scoop\persist\nodejs\bin\node_modules\@angular\cli\bin\postinstall\script.js:5:1)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @angular/cli@8.3.4 postinstall: `node ./bin/postinstall/script.js`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the @angular/cli@8.3.4 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    
    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\zebal\scoop\persist\nodejs\cache\_logs\2019-09-17T05_00_22_275Z-debug.log
    

## 🌍 Your Environment
npm version: 6.10.3
nodejs version: 12.10.0
windows10 version: 1909

**Comment by clydin** [comment]
This is an error that would be received if an old version of Node.js was used.  Please ensure that Node.js 12 is actually being used during the install and also please provide the contents of the log file indicated.

**Comment by clydin** [comment]
The post install scripts were updated to only use ES5 features.  In the event of an older version of Node.js, this error will no longer occur.
