### ISSUE TITLE
Angular 8.0 -> 8.2.3 -- build optimizer is now broken [Uncaught ReferenceError: exports is not defined]

### ISSUE THREAD

**Issue by claygifford** [angular/angular-cli#15628]
Building with these settings
"buildOptimizer": true,
"optimization": true,
﻿
main.9cadd90….js:1 Uncaught ReferenceError: exports is not defined
    at Module.89D/ (main.9cadd90….js:1)
    at l (runtime.69aad17….js:1)
    at Object.1 (main.9cadd90….js:1)
    at l (runtime.69aad17….js:1)
    at t (runtime.69aad17….js:1)
    at Array.r [as push] (runtime.69aad17….js:1)
    at main.9cadd90….js:1

Angular 8.0 -- Works
    "@angular-devkit/build-angular": "0.800.1",
    "@angular-devkit/build-ng-packagr": "0.800.1",
    "@angular/cli": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/compiler-cli": "8.0.0",

Angular 8.2.3 -- Broken
    "@angular-devkit/build-angular": "0.802.2",
    "@angular-devkit/build-ng-packagr": "0.802.2",
    "@angular/cli": "8.2.2",
    "@angular/compiler": "8.2.3",
    "@angular/compiler-cli": "8.2.3",

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
