### ISSUE TITLE
[error] TypeError: Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by bitores** [angular/angular-cli#15623]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
> ng build xxx 
```js
[error] TypeError: Cannot read property 'module' of undefined
    at MetadataBundler.convertSymbol (/Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:324:61)
    at createReference (/Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:461:27)
    at MetadataBundler.convertReference (/Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:509:28)
    at MetadataBundler.convertExpression (/Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:438:37)
    at MetadataBundler.convertValue (/Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:419:29)
    at /Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:422:62
    at Array.map (<anonymous>)
    at MetadataBundler.convertValue (/Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:422:30)
    at MetadataBundler.convertValue (/Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:428:36)
    at /Users/~~~/ng-antd-super-form/node_modules/@angular/compiler-cli/src/metadata/bundler.js:422:62
```
![image](https://user-images.githubusercontent.com/17512181/65129018-1c9dd500-da2d-11e9-9e22-928ffde0ea56.png)

![image](https://user-images.githubusercontent.com/17512181/65128945-f841f880-da2c-11e9-8ba1-e6ced3043ecd.png)

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.4
Node: 10.15.3
OS: darwin x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.4
@angular-devkit/build-angular      0.803.4
@angular-devkit/build-ng-packagr   0.803.4
@angular-devkit/build-optimizer    0.803.4
@angular-devkit/build-webpack      0.803.4
@angular-devkit/core               8.3.4
@angular-devkit/schematics         8.3.4
@angular/cdk                       8.2.0
@angular/cli                       8.3.4
@angular/http                      7.2.15
@ngtools/webpack                   8.3.4
@schematics/angular                8.3.4
@schematics/update                 0.803.4
ng-packagr                         5.5.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by bitores** [comment]
@alan-agius4 
https://github.com/bitores/ng-antd-super-form
ng build super-form

**Comment by bitores** [comment]
![image](https://user-images.githubusercontent.com/17512181/65192745-d8511a00-daaa-11e9-8d3c-568445d2952e.png)
I may have solved that problem , but i don`t know why. I just changed the relative path to the absolute path when build the project. @alan-agius4
