### ISSUE TITLE
Invalid Host/Origin header [WDS] Disconnected!

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#15624]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes it was working fine in 7.3.x

 Yes, the previous version in which this bug was not present was: ....

### Description

 Whenever i make any changes in file and then see web browser console. it is spamming continuously with client:169 Invalid Host/Origin header 
client:172 [WDS] Disconnected!

## 🔥 Exception or Error
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.

WebSocket connection to 'ws://localhost:4200/sockjs-node/945/n4o3fu34/websocket' failed: WebSocket is closed before the connection is established.
client:169 Invalid Host/Origin header
client:172 [WDS] Disconnected!
[WDS] Live Reloading enabled.
```

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.1.2
Node: 10.16.0
OS: win32 x64
Angular: 8.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.2
@angular-devkit/build-angular     0.801.2
@angular-devkit/build-optimizer   0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core              8.1.2
@angular-devkit/schematics        8.1.2
@angular/cdk                      8.1.1
@angular/cli                      8.1.2
@angular/material                 8.1.1
@ngtools/webpack                  8.1.2
@schematics/angular               8.1.2
@schematics/update                0.801.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**

![image](https://user-images.githubusercontent.com/23274631/65137826-a185f000-da27-11e9-802c-373e9d7b188b.png)

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by indraraj26** [comment]
Hi, I don't find this error in brand new project, but still i am facing in one of project. I have no idea which are things to copy from that project to brand new project in order to reproduce, it is really complex app. I have copied some of content from that project to new brand project but there is no error in web console when i am making any changes in file.

You can close this if it is not possible to resolve without reproduce.

**Comment by indraraj26** [comment]
#closing failed to reproduce.
