### ISSUE TITLE
generated DIST is not working in S3 or local htdocs

### ISSUE THREAD

**Issue by anees-tricon** [angular/angular-cli#1563]
- OS: On all OS
- Version: beta.9 and beta.10

Hi folks,

   after doing `ng build --prod`, i copy the contents of the dist folder and paste it inside a folder called `ng2` in my `htdocs` .
 Now when i run `localhost/ng2` , the index.html is loaded but all the CSS, JS files which am including using the relative url is giving me 404.

`<link rel="stylesheet" href="style.css">` should be ideally fetching `localhost/ng2/style.css` but it is trying to fetch `localhost/style.css` which results in 404.

Same happens for all the JS files and even the fonts am trying to access within the CSS.

If i paste the contents of the dist folder directly inside `htdocs` , then when i try to access `localhost/index.html` everything works fine.

Same happens with S3 as well. When i upload the contents directly into the bucket, it works, but when i try to upload the contents into a folder inside the bucket it gives me 404. 

Am sure its not an issue from my end because i tried the same approach with the skeleton app created using `ng new <project_name>` and the same issue happened

**Comment by kylecordes** [comment]
I think you are seeing normal HTML asset loading behavior, nothing specific to Annular nor CLI.

Try this. If you decide to upload the files somewhere other than the "root" web serving location, edit the BASE tag in the index.html file appropriately. Change that base URL from "/" to "/ng2/" for example in the case you describe above.

**Comment by wulfsberg** [comment]
The `<base href="...">` is the key when moving between folders like this.
It would, however, be convenient to have a way to have the dev server serve the app on such a sub-path, to mimic how it will ultimately be deployed.

**Comment by anees-tricon** [comment]
Thanks guys. setting the base href to "/ng2/" fixed the issue. Now all the resources are loading fine without 404s however, the fonts and images i have in my "assets" folder are giving 404s. 

It seems the base href is not being added to the url after the root folder. I know beta.10 is giving a fix for a similar issue related to js files. Will beta.10 fix fonts and css as well in the assets folder?

**Comment by wulfsberg** [comment]
Again, that is simply how the base works. You are most likely referencing your assets with a prefixed slash. That drops you to the _server_ root no matter what your base href - which sets the entry point for relative paths - says.
If you want to be able to move your deployment between different subfolders, you need to always use relative paths.

This is, by the way, exactly the situation I would like to catch by having the test server serve on a sub-path. It is far too easy to accidentally use an absolute path which seems to work, and have it break in the actual deployment.

**Comment by anees-tricon** [comment]
Thanks @kylecordes and @wulfsberg . My issue is resolved now. I'll go ahead and close this one.

**Comment by filipesilva** [comment]
Thanks @kylecordes and @wulfsberg for the spot on solution!
