### ISSUE TITLE
ng serve not watching for html changes with dynamic template URL

### ISSUE THREAD

**Issue by betterhermin** [angular/angular-cli#15634]
When I execute ng serve using dynamic templateurl, and modify the Html file, I can't automatically compile and update the web page。There is the same problem [here.](https://github.com/angular/angular-cli/issues/9133#issue-286820167) I would like to know if there is a solution?

**Comment by filipesilva** [comment]
This functionality is not something we officially support. It might work under some limited circumstances, such as extremely simple path concatenations. But it work only incidentally by virtue of how webpack interprets dynamic requires and how AOT compilation interprets annotations.
