### ISSUE TITLE
deployUrl only changes index.html

### ISSUE THREAD

**Issue by tommiv** [angular/angular-cli#15643]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No

### Description

Set `angular.json => projects.name.architect.build.options.deployUrl = "/build/"`. My expectation is 1) all entries of .js/.css files build are changed to /build/ prefix. 2) all built .js/.css files are moved into %build_root%/build/ folder. The point 1) is true; the point 2) however, is false, all scripts are left in %build_root% folder. Basically, this breaks the app since it will try to load scripts from void.

## 🔬 Minimal Reproduction

Just set deployUrl to something meaningful in angular.json. Then build the project `ng build --prod` and check the result – paths in index.html are changed, but files are left in the build root.

## 🔥 Exception or Error
<pre><code>
No errors thrown.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.5
Node: 10.16.0
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cdk                      8.2.0
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
The purpose of the deploy URL option is to adjust the text of the paths that are generated within the application itself.  This is to support more complex deployment scenarios (CDNs for asset storage, for instance) and is not at all related to the on disk output structure of the application.
