### ISSUE TITLE
Angular 8 prod build with aot asks sudo password

### ISSUE THREAD

**Issue by akvaliya** [angular/angular-cli#15641]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [x] build
```
### Description

In linux server when we were doing build without aot (setting aot, buildOtpimizer to false) build was generating fine. 
After we set aot & buildOptimizer & generate build it asks for sudo password after compilation & it stays only for several seconds. If we fail to enter pwd in this time it exits.

## 🔬 Minimal Reproduction

It happened on linux server. I am not sure why build process is changing files permission after creating it.

```
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "gzipper": "gzipper",
    "build:prod": "node --max_old_space_size=2048 node_modules/@angular/cli/bin/ng build --prod && gzipper ./dist",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  }
```
User is using `npm run build:prod` to generate build.

## 🔥 Error

Below is screenshot when process exit before we could enter password.

![image](https://user-images.githubusercontent.com/25152577/65320305-30794080-dbbf-11e9-85fa-1ba832a7633a.png)

And this is when i was able to password and enter

![image (1)](https://user-images.githubusercontent.com/25152577/65320374-5272c300-dbbf-11e9-8272-676cafd1c007.png)

## 🌍 Your Environment
```
 "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.2",
    "@angular/cli": "~8.3.2",
    "@angular/compiler-cli": "~8.2.4",
    "@angular/language-service": "~8.2.4"
}
```
This is compiler & build versions used in project.

**Comment by clydin** [comment]
This is not related to the Angular CLI but rather it appears to be related to custom addition of the “gzipper” command to the npm script.
