### ISSUE TITLE
after update to ver7.3.9，why the images in output directory when i builded

### ISSUE THREAD

**Issue by gtjyj** [angular/angular-cli#15642]
first，i'am sorry about my english, it's not very good, but i need your help. 

 today i update angular/cli from 6.x-->7.3.9, it's work，but when i run commond"ng build --prod", some changes be discovered, the images in my css/scss files be package to output root directory. however i can't find it in version 6.x, that images be resolve base64 string in HTML file. those file just about  1KB。

i need  compile the small size images to base64 in HTML or CSS file  ，i want know how can i do？

thanks very match!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by gtjyj** [comment]
> 
> 
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

thank you
