### ISSUE TITLE
"ng serve" shows compilation successful but browser does not show angular app

### ISSUE THREAD

**Issue by meDeepakJain** [angular/angular-cli#15644]
I am using AWS EC2 ubuntu server, have installed a fresh angular app, run the `ng serve` command on putty from my Windows 7 PC.
**Result on CLI (in putty):** Compilation is successful.
**Problem:** URL is not accessible via browser whether I type it manually with ip and port 8080 as I used in my app or use `-o` with my command. Even if I add `--host 0.0.0.0` or `port` with my `ng serve` command. Neither approach worked out.

**Approaches tried:** 
- Added `--host 0.0.0.0` with `ng serve` command.
- I've checked firewall settings to enable access to node and putty.
- Updated host to "0.0.0.0" in my package.json file.

Please suggest what error there could be? If you have any question further or need any clarification or screenshot, I may also clarify/attach as per request/requirement.

Kindly respond with your solutions/suggestions..

**Edit (Sept 20, 2019, 22:44): **
I've checked out the following threads but neither have any solution devised. 
[https://github.com/angular/angular-cli/issues/7119](https://github.com/angular/angular-cli/issues/7119)
[https://github.com/angular/angular-cli/issues/6779](https://github.com/angular/angular-cli/issues/6779)

@alan-agius4 @filipesilva @mgechev @filipemelo  any thoughts from your side?

**Comment by alan-agius4** [comment]
Might be related to https://github.com/angular/angular-cli/issues/15368

Kindly provide the output of `ng version`

**Comment by clydin** [comment]
Please also note that “ng serve” is a development server that is intended only for local development.  It should not be made accessible to a public network.

**Comment by meDeepakJain** [comment]
I got the solution. It was not the issue from CLI instead my aws server was unable to handle the request, needed resource upgradation. Thanks guys for responding.
