### ISSUE TITLE
--deploy-url stop working after upgrading to Angular v8.x

### ISSUE THREAD

**Issue by Gil-Epshtain** [angular/angular-cli#15665]
###  Bug report

I have a project, that was upgraded from Angular v7.x to v8.x.
After the upgrade the build flag --deploy-url stop working

Steps to reproduce:
- I've tested this scenario on 2 new projects, one with Ng7 and 2nd with Ng8 and this bug happen on Ng8

1. Create new angular project:
`ng new hello`

2. Create new component:
`ng g c hello`

3. At the bottom of your **app.component.html** paste this line: (inject the newly created component):
`<app-hello></app-hello>`

4. Edit the **hello** component:
- css file:
`.demo{ background-image: url("/assets/hello.jpg"); }`
- html file:
`<p class="demo">hello works!</p>`

5. Paste this script to your package.json:
```
  "scripts": {
    "prod": "ng build --prod --base-href=./ --deploy-url=/myapp/",
    ...
  },...
```

6. Run this command:
`npm run prod`

7. Search in the dist/ folder (search in text) the value: "/assets/hello.jpg"

### Result:
- Angular v7 (Result ok) - The search result is located in this line (notice the **myapp**):
`{background-image:url(/myapp/assets/hello.jpg)`

- Angular v8 (Result Bug) - The search result is located in this line (missing **myapp**):
`{background-image:url(/assets/hello.jpg)`

###Conclusion:
It looks like the build flag `--deploy-url` stop working. This flag should edit my css files and add the folder (in the example case: 'myapp') to the path of the asset.

### Your Environment
Windows: 10
Node: 12.8.1
Angular-Cli: 8.2.2

#### If this isn't a bug, but my incorrect use of this feature, please let me know so I could close this issue.

**Comment by alan-agius4** [comment]
Hi @Gil-Epshtain, this is expected.

Kindly see: https://github.com/angular/angular-cli/issues/14587

**Comment by Gil-Epshtain** [comment]
Hi @alan-agius4 , I didn't understand you. You write that this is "expected", but you have linked a 2nd issue ,which is similar, but on anther build flag: `--base-url`. Are you saying that my issue is a duplication? or are you saying that this behavior is the new Angular 8 way? if so how should I reference my assets from my styles files???

**Comment by alan-agius4** [comment]
@Gil-Epshtain, this is expected and will be the default in future versions of the CLI. For the time being until you transition all resources path you can use the `rebaseRootRelativeCssUrls` flag.

From https://github.com/angular/angular-cli/issues/14587#issuecomment-497368020
> Root relative URLs are a standardized method to reference a resource path from the root of a host. The previous behavior of the Angular CLI prevented this from occuring and resulted in an inability to reference stylesheet assets in this manner. The initial reason for this behavior is no longer present in the internal implementation of the Angular CLI. Therefore, this now unnecessary and non-standard behavior is being phased out. If an application currently relies on this behavior, a compatibility option rebaseRootRelativeCssUrls has been provided for the 8.x release cycle to facilitate transition away from this non-standard and limiting behavior. The recommended method to transition is to use relative paths within the source stylesheet. This allows the build system to process and generate a full URL for the asset.

To reference images in your stylesheet you need to use relative paths, which such paths the build system will be able to process and manage the resource. Since the build system is now managing the resource, it will process the file as needed and add it to the output of the application and it will also hash the filename.

**Comment by alan-agius4** [comment]
See also: https://github.com/angular/angular-cli/pull/13684

**Comment by Gil-Epshtain** [comment]
@alan-agius4 , Your solution - of using relative path isn't valid!!
 Not only that the path itself look like this: `./../../../../../assets/images/my-img.jpg` this isn't readable code.
But that's not the problem, I can live with unreadable code, however the problem is that in production the relative path is differ (it's one folder dipper), So each time I'm publishing a production version I need to go over all of my scss files on manual edit all the references! that's can't be!!
