### ISSUE TITLE
Build incorrectly including Component from file

### ISSUE THREAD

**Issue by sam-s4s** [angular/angular-cli#15667]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Not sure

### Description

I have an angular workspace with 5 projects inside. Each project has its own module, which includes all `@Component`s for that module, etc.

If I have a project `A` with a file in it, containing both an interface and an `@Component`, when I import ONLY the interface into project `B`, the build for project `B` gives me the following error:

```
ERROR in Cannot determine the module for class BlahComponent in path/angular/A/app/blah.ts! Add BlahComponent to the NgModule to fix it.
```

This is obviously inappropriate as I am not using the `@Component` from within project `B`, so it should not be imported during the build.

## 🔬 Minimal Reproduction

Create a workspace with 2 projects, A and B.
Create a file in project A containing an interface and a Component (added into the module for A but not B).
Import and reference the interface in B (and not the Component).
Build project B.

## 🔥 Exception or Error
<pre><code>

ERROR in Cannot determine the module for class BlahComponent in path/angular/A/app/blah.ts! Add BlahComponent to the NgModule to fix it.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.5
Node: 10.15.1
OS: win32 x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.5
@angular-devkit/build-angular     0.803.5
@angular-devkit/build-optimizer   0.803.5
@angular-devkit/build-webpack     0.803.5
@angular-devkit/core              8.3.5
@angular-devkit/schematics        8.3.5
@angular/cli                      8.3.5
@ngtools/webpack                  8.3.5
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by alan-agius4** [comment]
Hi @sam-s4s, this is expected because when adding a component in the compilation it needs to be imported in a module, when importing the file that contains model and component, you are essentially adding the orphanage component in the compilation without it being referencing in any module.

It is also important to point out that an application shouldn't dependent on files which are in another application. This is an anti-pattern IMHO. A library should be created if you wish to have common logic to you want to share in several applications.

That being said, you can possible create a file which contains models only.

**Comment by sam-s4s** [comment]
Hmmm this seems very counter-intuitive though - why would the compiler try to read anything that's not either imported directly or referenced in the module? Surely this is a bug / problem... I can't see how that could possibly considered "safe" behaviour.

**Comment by clydin** [comment]
The file is imported which makes it part of the TypeScript program.  This is actually TypeScript behavior (a necessity for full type-checking) and not particular to Angular.

**Comment by sam-s4s** [comment]
However Angular should not ask you to add the `@Component` to your app.module if you're not actually using it in your project, surely... it's a false positive error.

**Comment by sam-s4s** [comment]
I'd like to push on this a bit - I still feel like it's easily classified as incorrect cli behaviour...

(importing an interface from a file should not generate an error asking you to add the component to the module, given you are not using the component)
