### ISSUE TITLE
An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-angular:browser

### ISSUE THREAD

**Issue by program-om** [angular/angular-cli#15676]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes, it used to work with the same angular version.

 Yes, the previous version in which this bug was not present was: ....

### Description
I am trying to deploy my angular application to heroku and I get an error during angular build process. here is the command that run on heroku server `> ng build --aot --prod` 

## 🔥 Exception or Error
<pre><code>

remote:        Installing any new modules (package.json)
remote:        
remote:        > web-app-hub@0.0.0 postinstall /tmp/build_f3ffa2a4a54ad5d81a799b2fe133eeab
remote:        > ng build --aot --prod
remote:        
remote:        An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-angular:browser
remote:        See "/tmp/ng-lJmGwF/angular-errors.log" for further details.
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! web-app-hub@0.0.0 postinstall: `ng build --aot --prod`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR! 
remote:        npm ERR! Failed at the web-app-hub@0.0.0 postinstall script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:        
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.q3bHD/_logs/2019-09-25T18_15_08_236Z-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        Some possible problems:
remote:        
remote:        - node_modules checked into source control
remote:          https://blog.heroku.com/node-habits-2016#9-only-git-the-important-bits
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to web-app-hub-frontend.
remote: 
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 6.2.9
Node: 10.16.3
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.12.4
@angular-devkit/build-optimizer   0.12.4
@angular-devkit/build-webpack     0.12.4
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cdk                      6.4.7
@angular/cli                      6.2.9
@angular/compiler-cli             7.2.15
@ngtools/webpack                  7.2.4
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.5.3
typescript                        3.1.6
webpack                           4.28.4
</code></pre>

here is `package.json`
```
{
  "name": "ang-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "postinstall": "ng build --aot --prod"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^0.12.4",
    "@angular/animations": "^6.0.3",
    "@angular/cdk": "^6.4.7",
    "@angular/cli": "^6.2.9",
    "@angular/common": "^6.0.3",
    "@angular/compiler": "^6.0.3",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/core": "^6.0.3",
    "@angular/forms": "^6.0.3",
    "@angular/http": "^6.0.3",
    "@angular/platform-browser": "^6.0.3",
    "@angular/platform-browser-dynamic": "^6.0.3",
    "@angular/router": "^6.0.3",
    "@fortawesome/angular-fontawesome": "^0.2.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@ngx-share/button": "^6.0.1",
    "@ngx-share/buttons": "^6.0.1",
    "@ngx-share/core": "^6.0.1",
    "core-js": "^2.6.9",
    "express": "^4.17.1",
    "jquery": "^3.4.1",
    "nodemailer": "^6.3.0",
    "rxjs": "^6.5.3",
    "typescript": "3.1.6",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/language-service": "^6.0.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.3.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.2",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1"
  },
  "engines": {
    "node": "10.16.3",
    "npm": "6.9.0"
  }
}

```

**Anything else relevant?**

this is what i have in `.gitignore`
```
node_modules
npm-debug.log

```
I checked out these issues https://github.com/angular/angular-cli/issues/15063 and https://github.com/angular/angular-cli/issues/14546 but they did not help.

I am running my angular project locally on macOS v. 10.14.6

**Comment by alan-agius4** [comment]
Hi, for CLI version 6.x the `@angular-devkit/build-angular` package should be `^0.8.9`.
