### ISSUE TITLE
8.3.x ES5 build broken for spread operator on set

### ISSUE THREAD

**Issue by readme42** [angular/angular-cli#15673]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [x] build
```

### Is this a regression?
No, its broken since the optimized creation of es5 out of es2015 builds were introduced in 8.3. In 8.2.x, when both builds were created on their own, everything was fine.

### Description
Since updating `angular/cli` to 8.3.x it turns our that our ES5 builds are broken - exceptions are thrown during runtime. 

What I found out so far: 

ES2015 builds are fine. 
ES5 builds, created with `NG_BUILD_DIFFERENTIAL_FULL=true` are fine.
ES5 builds, created without `NG_BUILD_DIFFERENTIAL_FULL=true` are broken.

It turns out, that the following line creates `undefined` in es5 builds whereas it creates an array of strings in es2015 builds:

<pre><code>
// Make demand ids in day unique
cardDataByDay[ key ] = [ ...new Set(cardDataByDay[ key ]) ];
</code></pre>

Happens in any browser in which you load the es5 build. 

## 🔬 Minimal Reproduction / 🔥 Exception or Error

~~As its quite some effort due to the size to extract it and you maybe already 
know what and where to fix it, I will create a test repo when you really need it. 
Just drop a comment in this case.~~

Edit: You can find the repo here: https://github.com/readme42/repro-angular-cli83-es5-15673

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.3.5
Node: 12.6.0
OS: darwin x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.5
@angular/cdk                      8.2.1
@angular/cli                      8.3.5
@angular/material                 8.2.1
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.5
@schematics/update                0.803.5
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Comment by alan-agius4** [comment]
@readme42, can you please provide the full code snippet that is needed to generate the error? 

Thanks.

**Comment by readme42** [comment]
@alan-agius4 sure - will deliver in the next hours.

**Comment by readme42** [comment]
Here we go. You can find the repo here: https://github.com/readme42/repro-angular-cli83-es5-15673

Just clone it and run `npm start`

The ES2015 build shows: 
```
 {
  "shouldContainer1234": [
    1,
    2,
    3,
    4
  ],
  "shouldContainen567": [
    5,
    6,
    7
  ]
} 
```

Ths ES5 build shows: 
```
 {
  "shouldContainer1234": [
    {}
  ],
  "shouldContainen567": [
    {}
  ]
} 
```
