### ISSUE TITLE
ng update fail at postinstall script with error Cannot find module '../run-schematic/executor'

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular-cli#15686]
# 🐞 Bug report

### Command

```
- [x] update
```

### Is this a regression?

Sometimes CLI update without error, sometimes next error appear.

### Description

After `update` command, CLI throw `Cannot find module '../run-schematic/executor'` at `/bin/postinstall/script.js`

## 🔬 Minimal Reproduction

1) Files before update : 
[myproject/package.json](https://gist.github.com/elvisbegovic/3d3ea1854c3e4f33f24d590b4306f7ab)
[myproject/tsconfig.json](https://gist.github.com/elvisbegovic/6e792b037aa05404236c2c07d1bf08e0)
[myproject/tsconfig.app.json](https://gist.github.com/elvisbegovic/a06dce259ec2c3d743afdfe499ce78e5)
[myproject/angular.json](https://gist.github.com/elvisbegovic/70e3f86668bc0661b40728eab57f4575)

2) run command `ng update --next --all --force`

## 🔥 Error

Repro until error in GIF (some useless images intentionally deleted)
![cli-update-run-schematic-executor](https://user-images.githubusercontent.com/2789203/65688743-eb945480-e06b-11e9-8415-373e5fe6aac9.gif)

[See whole update process in text format](https://gist.github.com/elvisbegovic/b3097d9384816c7724c2a8be3667d9d8)

## 🌍 Environment

<details><summary>See Environment BEFORE update</summary>

```
Angular CLI: 9.0.0-next.2
Node: 12.9.1
OS: win32 x64
Angular: 9.0.0-next.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.2
@angular-devkit/build-angular     0.900.0-next.2
@angular-devkit/build-optimizer   0.900.0-next.2
@angular-devkit/build-webpack     0.900.0-next.2
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cdk                      8.2.1
@angular/cli                      9.0.0-next.2
@angular/material                 8.2.1
@angular/pwa                      0.803.6
@ngtools/webpack                  9.0.0-next.2
@schematics/angular               8.3.6
@schematics/update                0.900.0-next.2
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.3
```

</details>

<details><summary>See Environment AFTER update</summary>

```
Angular CLI: 9.0.0-next.6
Node: 12.9.1
OS: win32 x64
Angular: 9.0.0-next.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.6
@angular-devkit/build-angular     0.900.0-next.6
@angular-devkit/build-optimizer   0.900.0-next.6
@angular-devkit/build-webpack     0.900.0-next.6
@angular-devkit/core              9.0.0-next.6
@angular-devkit/schematics        9.0.0-next.6
@angular/cdk                      8.2.1
@angular/cli                      9.0.0-next.6
@angular/material                 8.2.1
@angular/pwa                      0.900.0-next.6
@ngtools/webpack                  9.0.0-next.6
@schematics/angular               9.0.0-next.6
@schematics/update                0.900.0-next.6
rxjs                              7.0.0-alpha.0
typescript                        3.7.0-dev.20190926
webpack                           4.41.0
```

</details>

**Anything else relevant?**
Note that typescript was `~3.5.3` and due to "--next --force" falgs it becomes `~3.7.0-dev.20190926`

(further feedback of/might be related to https://github.com/angular/angular-cli/issues/14083)

**Comment by fastAstortoise** [comment]
late to the party but I had the same issue and found out that  I was missing two deps.
`npm i -D @angular-devkit/core @angular-devkit/schematics`
Installing above deps fixed the issue for me.

**Comment by guest73** [comment]
I have the same problem while migrating from Angular 7 to Angular 8. Installing npm i -D @angular-devkit/core @angular-devkit/schematics as @fastAstortoise suggested did not help :(

**Comment by guest73** [comment]
Ok. What helped was
1) Remove node_modules, remove package-lock.json
2) npm run ng update @angular/cli@8 @angular/core@8

**Comment by KaranTrivedi** [comment]
This didnt work, guest73 ..

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
