### ISSUE TITLE
ng build git path is prefixed to -base-href

### ISSUE THREAD

**Issue by crtl** [angular/angular-cli#15699]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Ive create an app using `ng serve` and wanted to build it and set the base href using the following command:
`ng build --base-href "/app/" `<br/>

Output in the resulting `index.html` is:

```
<base href="C:/Program Files/Git/app/">
```

Ive also tried:
- `ng build --base-href="/app/" `
- `ng build --base-href "./app/" `

This only occures when using git bash on windows.
When using windows shell it works.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.6
Node: 10.16.3
OS: win32 x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by clydin** [comment]
This is unfortunately an issue with the shell and not the Angular CLI.  The shell is modifying the arguments before they are provided to the CLI.
