### ISSUE TITLE
ng command not found on Mac

### ISSUE THREAD

**Issue by dinobu** [angular/angular-cli#15692]
# 🐞 Bug report

### Command (mark with an `x`)

No, this is issue with installation on Macbook Pro
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I dont know, I am new to angular

### Description
STEPS
1. sudo npm uninstall -g angular-cli
2. sudo npm uninstall -g @angular/cli
3. sudo npm cache clean --force
4. sudo npm install -g @angular/cli
5. sudo npm link @angular/cli
6. ng -v results in -bash: ng: command not found
7. Under my /Users/dinob/ there is no directory .npm-global

PROBLEM: ng command is not found

## 🔬 Minimal Reproduction
STEPS
1. sudo npm uninstall -g angular-cli
2. sudo npm uninstall -g @angular/cli
3. sudo npm cache clean --force
4. sudo npm install -g @angular/cli
5. sudo npm link @angular/cli
6. ng -v results in -bash: ng: command not found
7. Under my /Users/dinob/ there is no directory .npm-global

## 🔥 Exception or Error
-bash: ng: command not found

## 🌍 Your Environment
ng version returns ng command not found
npm -v 6.9.0
node -v 10.16.0

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by dinobu** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Seriously!  Do you think I came here without checking it all over the net including SO about this first?  What are github issues for if not for bug issues?  
Why are you assuming it is not a bug?  
Why not provide exact steps or comment on my steps and identify if something in them is wrong (which I doubt and which are by the way coming from SO based on my research of this bug before landing on your page to report it)

**Comment by dinob68** [comment]
Thanks for being useless Angular team

Here is the solution to your problem

https://stackoverflow.com/questions/58138138/angular-cli-ng-command-not-found-on-mac-os/58207895#58207895
