### ISSUE TITLE
--output-path not working anymore in 1.0.0-beta.11-webpack

### ISSUE THREAD

**Issue by dlizarra** [angular/angular-cli#1569]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan 10.11.4

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack
node: 6.3.0
npm: 3.10.6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Run `ng build --output-path=mydir` but the output directory for the build was `dist`. With previous CLI versions it would have been `mydir`.

As an alternative, while not officially supported but working fine in previous CLI versions I added a `.ember-cli` file with this content: 

    {
        "output-path": "mydir"
    }

The output directory was `dist` once again. 

Is this an issue or now there's another way to configure the output dir?

**Comment by benoit-ponsero** [comment]
Hi,

The output path seem to be hardcoded in webpack-build-common.ts and other webpack config files.

https://github.com/angular/angular-cli/blob/master/addon/ng2/models/webpack-build-common.ts#L21

https://github.com/angular/angular-cli/blob/master/addon/ng2/models/webpack-build-development.ts#L9

**Comment by dlizarra** [comment]
@benoit-ponsero Yes, you are right. The build process actually uses the `--output-path` to remove the directory before running `webpack` but the option is not used in `NgCliWebpackConfig` like some of the other `ServeTaskOptions`.

https://github.com/angular/angular-cli/blob/master/addon/ng2/tasks/build-webpack.ts#L18

**Comment by not-only-code** [comment]
I just solved this issue, pending for some review here: https://github.com/angular/angular-cli/pull/1595 .

**Comment by dlizarra** [comment]
@not-only-code Great!

**Comment by not-only-code** [comment]
It seems the tests are failing in both `master` and `webpack` branhces. So you can use my branch temporally until we solve the `tests`fails.

**Comment by not-only-code** [comment]
Merged ;:^)  #1595

**Comment by dlizarra** [comment]
Closing the issue as solved then.

Gràcies Carlos!

**Comment by not-only-code** [comment]
This is still pending for `master` merge review https://github.com/angular/angular-cli/pull/1627, so do not close this issue yet.

**Comment by not-only-code** [comment]
PR closed https://github.com/angular/angular-cli/pull/1627.
