### ISSUE TITLE
Issue while installing angular js

### ISSUE THREAD

**Issue by mahendra-gaur** [angular/angular-cli#15697]
.
.
.
.
.
.
loadDep:is-fullwidth-code - |#################################-------------------------------------------------------------------------------|
loadDep:ansi-regex -> net | |#################################-------------------------------------------------------------------------------|
loadDep:tunnel-agent -> c | |#########################################-----------------------------------------------------------------------|
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@8.3.6 postinstall /usr/local/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

sh: 1: node: not found
npm ERR! Linux 4.15.0-64-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli@latest"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! @angular/cli@8.3.6 postinstall: `node ./bin/postinstall/script.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @angular/cli@8.3.6 postinstall script 'node ./bin/postinstall/script.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @angular/cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/postinstall/script.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @angular/cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @angular/cli
npm ERR! There is likely additional logging output above.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

There seems to be already a StackOverflow issue https://stackoverflow.com/questions/42064643/npm-install-g-angular-cli-sh-1-node-not-found/42064712
