### ISSUE TITLE
ng command not found in macOS

### ISSUE THREAD

**Issue by kjkrupal** [angular/angular-cli#15708]
I installed angular using npm install -g @angular/cli. It was installed successfully, however, i am getting ng command not found error upon running. How do I solve this issue?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
