### ISSUE TITLE
Getting error on running  build --prod complied angular 6 app(Error: No NgModule metadata found for 'jL'.).

### ISSUE THREAD

**Issue by prashantparihar63** [angular/angular-cli#15700]
Hello every one, Thank you in advance.
I am getting an error on running my angular app. If I compilied it with ng build and publish it on server it works fine but if I compilied it with ng build --prod and publish it on server it shows error.
![image](https://user-images.githubusercontent.com/40241178/65764911-69c42a00-e144-11e9-82b4-b672e36aa97e.png)

My angular cli is 

Angular CLI: 6.0.0
Node: 8.11.4
OS: win32 x64
Angular: 6.1.8
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.3
@angular-devkit/build-angular     0.8.3
@angular-devkit/build-optimizer   0.8.3
@angular-devkit/build-webpack     0.8.3
@angular-devkit/core              0.8.3
@angular-devkit/schematics        0.6.0
@angular/animations               7.0.3
@angular/cdk                      7.0.3
@angular/cli                      6.0.0
@angular/material                 6.4.7
@ngtools/webpack                  6.2.3
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.0

**Comment by alan-agius4** [comment]
Hi @prashantparihar63, does this work in the latest versions of Angular CLI?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
