### ISSUE TITLE
--statsJson not producing stats-es5.json on > 

### ISSUE THREAD

**Issue by s-tyler-smith** [angular/angular-cli#15719]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular-devkit/build-angular: 0.802.x

### Description

 When upgrading to @angular-devkit/build-angular:0.803.x from 0.802.x the `--statsJson` build flag no longer produces `stats-es5.json` it only produces `stats-es2015.json`

## 🔬 Minimal Reproduction

- run `ng new test-app`
- `cd test-app`
- run `ng build --statsJson`
- dist/test-app no longer includes stats-es5.json

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.6
Node: 10.16.0
OS: darwin x64
Angular: 8.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
    
</code></pre>

**Anything else relevant?**

**Comment by s-tyler-smith** [comment]
should i used the `NG_BUILD_DIFFERENTIAL_FULL` ENV variable to retain this functionality based on https://github.com/angular/angular-cli/pull/15246 ?

**Comment by clydin** [comment]
It is intentional that it is not present.  There is only one webpack build on version 8.3+.  The content of the ES5 files are based on the ES2015 files.  Is there a reason you need this stats file?

**Comment by s-tyler-smith** [comment]
since we target legacy browsers (gotta love IE 11) we liked being about to use webpack-bundle-analyzer to show/compare the performance/size between the 2 builds.

BTW great job reducing the build time with this feature bump!

**Comment by s-tyler-smith** [comment]
@clydin so it sounds like this functionality if no longer going to be supported?

**Comment by clydin** [comment]
Yes.  Outside polyfills, the modules contained in each variant are the same.  The size differences (i.e., larger ES5 files) are a result of the increased structural elements necessary to represent the same set of functionality with ES5 code.

**Comment by s-tyler-smith** [comment]
ok in that case we can close this issue.
