### ISSUE TITLE
referenceError, even when using "if"

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular-cli#15715]
in JS we can do:
`if(x){doSomething()} //if 'x' is not defined, this line is ignored, but will not give a referenceError`

but in angular schematics, it gives a referenceError `x is not defined`

`<% if(x){x} %>`

it is difficult to define all variables before passing it to the template using template({...})

**Comment by clydin** [comment]
A non-existent variable will throw a reference error.  Note that this is very different than a variable with a value of undefined.  And also different than accessing a non-existing property on an object.  Both of which will not throw reference errors.

This is standard JavaScript behavior not specific to schematics or the CLI.

**Comment by xxyyzz2050** [comment]
thank you @clydin 
I passed the object itself instead of destructing it and it worked
