### ISSUE TITLE
Schema validation failed with the following errors:   Data path "" should have required property 'main'

### ISSUE THREAD

**Issue by nesmrten** [angular/angular-cli#15712]
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Oh hi there! 😄

After update to latest version of angular 8, i have this error
Schema validation failed with the following errors:
  Data path "" should have required property 'main'

my angular.json:
{ 
  "$schema":"./node_modules/@angular/cli/lib/config/schema.json",
  "version":1,
  "newProjectRoot":"",
  "projects":{ 
     "studio":{ 
        "root":"apps/studio/",
        "sourceRoot":"apps/studio/src",
        "projectType":"application",
        "prefix":"studio",
        "schematics":{ 
           "@schematics/angular:component":{ 
              "styleext":"scss"
           }
        },
        "architect":{ 
           "build":{ 
              "builder":"@angular-devkit/build-angular:browser",
              "options":{ 
                 "outputPath":"dist/apps/studio",
                 "index":"apps/studio/src/index.html",
                 "main":"apps/studio/src/main.ts",
                 "polyfills":"apps/studio/src/polyfills.ts",
                 "tsConfig":"apps/studio/tsconfig.app.json",
                 "assets":[ 
                    "apps/studio/src/favicon.ico",
                    "apps/studio/src/assets"
                 ],
                 "styles":[ 
                    "node_modules/bootstrap/dist/css/bootstrap.min.css",
                    "node_modules/froala-editor/css/froala_editor.pkgd.min.css",
                    "node_modules/froala-editor/css/froala_style.min.css",
                    "node_modules/bootstrap-select/dist/css/bootstrap-select.min.css",
                    "node_modules/flag-icon-css/css/flag-icon.min.css",
                    "node_modules/@ng-select/ng-select/themes/default.theme.css",
                    "node_modules/angular-calendar/css/angular-calendar.css",
                    "node_modules/flatpickr/dist/flatpickr.css",
                    "node_modules/primeicons/primeicons.css",
                    "node_modules/primeng/resources/themes/nova-light/theme.css",
                    "node_modules/primeng/resources/primeng.min.css",
                    "apps/studio/src/styles.css"
                 ],
                 "scripts":[ 
                    "node_modules/jquery/dist/jquery.min.js",
                    "node_modules/popper.js/dist/umd/popper.min.js",
                    "node_modules/bootstrap/dist/js/bootstrap.min.js",
                    "node_modules/froala-editor/js/froala_editor.pkgd.min.js",
                    "node_modules/bootstrap-select/dist/js/bootstrap-select.js",
                    "node_modules/chart.js/dist/Chart.min.js"
                 ]
              },
              "configurations":{ 
                 "production":{ 
                    "fileReplacements":[ 
                       { 
                          "replace":"apps/studio/src/environments/environment.ts",
                          "with":"apps/studio/src/environments/environment.prod.ts"
                       }
                    ],
                    "optimization":true,
                    "outputHashing":"all",
                    "sourceMap":false,
                    "extractCss":true,
                    "namedChunks":false,
                    "aot":true,
                    "extractLicenses":true,
                    "vendorChunk":false,
                    "buildOptimizer":true,
                    "budgets":[ 
                       { 
                          "type":"initial",
                          "maximumWarning":"2mb",
                          "maximumError":"5mb"
                       }
                    ]
                 }
              }
           },
           "serve":{ 
              "builder":"@angular-devkit/build-angular:dev-server",
              "options":{ 
                 "browserTarget":"studio:build"
              },
              "configurations":{ 
                 "production":{ 
                    "browserTarget":"studio:build:production"
                 }
              }
           },
           "extract-i18n":{ 
              "builder":"@angular-devkit/build-angular:extract-i18n",
              "options":{ 
                 "browserTarget":"studio:build"
              }
           },
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "apps/studio/tsconfig.app.json",
                    "apps/studio/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@angular-devkit/build-angular:karma",
              "options":{ 
                 "tsConfig":"apps/studio/tsconfig.spec.json"
              }
           }
        }
     },
     "studio-e2e":{ 
        "root":"apps/studio-e2e",
        "projectType":"application",
        "prefix":"",
        "architect":{ 
           "e2e":{ 
              "builder":"@nrwl/builders:cypress",
              "options":{ 
                 "cypressConfig":"apps/studio-e2e/cypress.json",
                 "tsConfig":"apps/studio-e2e/tsconfig.e2e.json",
                 "devServerTarget":"studio:serve"
              },
              "configurations":{ 
                 "production":{ 
                    "devServerTarget":"studio:serve:production"
                 }
              }
           },
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":"e2e/tsconfig.e2e.json",
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           }
        }
     },
     "display":{ 
        "root":"apps/display/",
        "sourceRoot":"apps/display/src",
        "projectType":"application",
        "prefix":"display",
        "schematics":{ 
           "@schematics/angular:component":{ 
              "styleext":"scss"
           }
        },
        "architect":{ 
           "build":{ 
              "builder":"@angular-devkit/build-angular:browser",
              "options":{ 
                 "outputPath":"dist/apps/display",
                 "index":"apps/display/src/index.html",
                 "main":"apps/display/src/main.ts",
                 "polyfills":"apps/display/src/polyfills.ts",
                 "tsConfig":"apps/display/tsconfig.app.json",
                 "assets":[ 
                    "apps/display/src/favicon.ico",
                    "apps/display/src/assets",
                    "apps/display/src/manifest.json"
                 ],
                 "scripts":[ 

                 ]
              },
              "configurations":{ 
                 "production":{ 
                    "fileReplacements":[ 
                       { 
                          "replace":"apps/display/src/environments/environment.ts",
                          "with":"apps/display/src/environments/environment.prod.ts"
                       }
                    ],
                    "optimization":true,
                    "outputHashing":"all",
                    "sourceMap":false,
                    "extractCss":true,
                    "namedChunks":true,
                    "aot":true,
                    "extractLicenses":true,
                    "vendorChunk":false,
                    "buildOptimizer":true,
                    "budgets":[ 
                       { 
                          "type":"initial",
                          "maximumWarning":"2mb",
                          "maximumError":"5mb"
                       }
                    ],
                    "serviceWorker":true
                 }
              }
           },
           "serve":{ 
              "builder":"@angular-devkit/build-angular:dev-server",
              "options":{ 
                 "browserTarget":"display:build"
              },
              "configurations":{ 
                 "production":{ 
                    "browserTarget":"display:build:production"
                 }
              }
           },
           "extract-i18n":{ 
              "builder":"@angular-devkit/build-angular:extract-i18n",
              "options":{ 
                 "browserTarget":"display:build"
              }
           },
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "apps/display/tsconfig.app.json",
                    "apps/display/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@angular-devkit/build-angular:karma",
              "options":{ 
                 "tsConfig":"apps/display/tsconfig.spec.json",
                 "assets":[ 
                    "apps/display/src/manifest.json"
                 ]
              }
           }
        }
     },
     "display-e2e":{ 
        "root":"apps/display-e2e",
        "projectType":"application",
        "prefix":"",
        "architect":{ 
           "e2e":{ 
              "builder":"@nrwl/builders:cypress",
              "options":{ 
                 "cypressConfig":"apps/display-e2e/cypress.json",
                 "tsConfig":"apps/display-e2e/tsconfig.e2e.json",
                 "devServerTarget":"display:serve"
              },
              "configurations":{ 
                 "production":{ 
                    "devServerTarget":"display:serve:production"
                 }
              }
           },
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":"e2e/tsconfig.e2e.json",
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           }
        }
     },
     "editor":{ 
        "root":"libs/editor",
        "sourceRoot":"libs/editor/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "test":{ 
              "builder":"@angular-devkit/build-angular:karma",
              "options":{ 
                 "main":"libs/editor/src/test.ts",
                 "tsConfig":"libs/editor/tsconfig.spec.json",
                 "karmaConfig":"libs/editor/karma.conf.js"
              }
           },
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/editor/tsconfig.lib.json",
                    "libs/editor/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           }
        }
     },
     "login":{ 
        "root":"libs/login",
        "sourceRoot":"libs/login/src",
        "projectType":"library",
        "prefix":"",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/login/tsconfig.lib.json",
                    "libs/login/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/login/jest.config.js",
                 "tsConfig":"libs/login/tsconfig.spec.json",
                 "setupFile":"libs/login/src/test-setup.ts"
              }
           }
        }
     },
     "register":{ 
        "root":"libs/register",
        "sourceRoot":"libs/register/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/register/tsconfig.lib.json",
                    "libs/register/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/register/jest.config.js",
                 "tsConfig":"libs/register/tsconfig.spec.json",
                 "setupFile":"libs/register/src/test-setup.ts"
              }
           }
        }
     },
     "reset-password":{ 
        "root":"libs/reset-password",
        "sourceRoot":"libs/reset-password/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/reset-password/tsconfig.lib.json",
                    "libs/reset-password/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/reset-password/jest.config.js",
                 "tsConfig":"libs/reset-password/tsconfig.spec.json",
                 "setupFile":"libs/reset-password/src/test-setup.ts"
              }
           }
        }
     },
     "forgotten-password":{ 
        "root":"libs/forgotten-password",
        "sourceRoot":"libs/forgotten-password/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/forgotten-password/tsconfig.lib.json",
                    "libs/forgotten-password/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/forgotten-password/jest.config.js",
                 "tsConfig":"libs/forgotten-password/tsconfig.spec.json",
                 "setupFile":"libs/forgotten-password/src/test-setup.ts"
              }
           }
        }
     },
     "search-displays":{ 
        "root":"libs/search-displays",
        "sourceRoot":"libs/search-displays/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/search-displays/tsconfig.lib.json",
                    "libs/search-displays/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/search-displays/jest.config.js",
                 "tsConfig":"libs/search-displays/tsconfig.spec.json",
                 "setupFile":"libs/search-displays/src/test-setup.ts"
              }
           }
        }
     },
     "models":{ 
        "root":"libs/models",
        "sourceRoot":"libs/models/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/models/tsconfig.lib.json",
                    "libs/models/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/models/jest.config.js",
                 "tsConfig":"libs/models/tsconfig.spec.json"
              }
           }
        }
     },
     "authentication":{ 
        "root":"libs/authentication",
        "sourceRoot":"libs/authentication/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/authentication/tsconfig.lib.json",
                    "libs/authentication/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/authentication/jest.config.js",
                 "tsConfig":"libs/authentication/tsconfig.spec.json",
                 "setupFile":"libs/authentication/src/test-setup.ts"
              }
           }
        }
     },
     "utilities":{ 
        "root":"libs/utilities",
        "sourceRoot":"libs/utilities/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/utilities/tsconfig.lib.json",
                    "libs/utilities/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/utilities/jest.config.js",
                 "tsConfig":"libs/utilities/tsconfig.spec.json",
                 "setupFile":"libs/utilities/src/test-setup.ts"
              }
           }
        }
     },
     "router":{ 
        "root":"libs/router",
        "sourceRoot":"libs/router/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/router/tsconfig.lib.json",
                    "libs/router/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/router/jest.config.js",
                 "tsConfig":"libs/router/tsconfig.spec.json",
                 "setupFile":"libs/router/src/test-setup.ts"
              }
           }
        }
     },
     "user-settings":{ 
        "root":"libs/user-settings",
        "sourceRoot":"libs/user-settings/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/user-settings/tsconfig.lib.json",
                    "libs/user-settings/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/user-settings/jest.config.js",
                 "tsConfig":"libs/user-settings/tsconfig.spec.json",
                 "setupFile":"libs/user-settings/src/test-setup.ts"
              }
           }
        }
     },
     "toolbar":{ 
        "root":"libs/toolbar",
        "sourceRoot":"libs/toolbar/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/toolbar/tsconfig.lib.json",
                    "libs/toolbar/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/toolbar/jest.config.js",
                 "tsConfig":"libs/toolbar/tsconfig.spec.json",
                 "setupFile":"libs/toolbar/src/test-setup.ts"
              }
           }
        }
     },
     "sidebar":{ 
        "root":"libs/sidebar",
        "sourceRoot":"libs/sidebar/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/sidebar/tsconfig.lib.json",
                    "libs/sidebar/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/sidebar/jest.config.js",
                 "tsConfig":"libs/sidebar/tsconfig.spec.json",
                 "setupFile":"libs/sidebar/src/test-setup.ts"
              }
           }
        }
     },
     "content-viewer":{ 
        "root":"libs/content-viewer",
        "sourceRoot":"libs/content-viewer/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/content-viewer/tsconfig.lib.json",
                    "libs/content-viewer/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/content-viewer/jest.config.js",
                 "tsConfig":"libs/content-viewer/tsconfig.spec.json",
                 "setupFile":"libs/content-viewer/src/test-setup.ts"
              }
           }
        }
     },
     "fullscreen":{ 
        "root":"libs/fullscreen",
        "sourceRoot":"libs/fullscreen/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/fullscreen/tsconfig.lib.json",
                    "libs/fullscreen/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/fullscreen/jest.config.js",
                 "tsConfig":"libs/fullscreen/tsconfig.spec.json",
                 "setupFile":"libs/fullscreen/src/test-setup.ts"
              }
           }
        }
     },
     "command-center":{ 
        "root":"libs/command-center",
        "sourceRoot":"libs/command-center/src",
        "projectType":"library",
        "prefix":"studio",
        "architect":{ 
           "lint":{ 
              "builder":"@angular-devkit/build-angular:tslint",
              "options":{ 
                 "tsConfig":[ 
                    "libs/command-center/tsconfig.lib.json",
                    "libs/command-center/tsconfig.spec.json"
                 ],
                 "exclude":[ 
                    "**/node_modules/**"
                 ]
              }
           },
           "test":{ 
              "builder":"@nrwl/builders:jest",
              "options":{ 
                 "jestConfig":"libs/command-center/jest.config.js",
                 "tsConfig":"libs/command-center/tsconfig.spec.json",
                 "setupFile":"libs/command-center/src/test-setup.ts"
              }
           }
        }
     }
  },
  "cli":{ 
     "warnings":{ 
        "typescriptMismatch":false,
        "versionMismatch":false
     },
     "defaultCollection":"@nrwl/schematics",
     "packageManager":"yarn"
  },
  "defaultProject":"studio"
}
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

my package.json: 
{
  "name": "pcpro-panel-server",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "concurrently \"ng serve --o\" \"node cors.server.js\" \"ng serve display --o --port 3600\" \"tsc -w -p server\" \"nodemon dist/server/app.js\"",
    "start:studio": "ng serve --o",
    "start:studio:prod": "ng serve --prod --o",
    "start:display": "ng serve display --o",
    "start:display:prod": "ng serve display --prod --o",
    "start:server": "node dist/server/app.js",
    "build": "ng build",
    "build:studio": "ng build --prod",
    "build:display": "ng build display --prod",
    "build:server": "tsc -p server && npm run copy",
    "build:deploy": "npm run build:studio && npm run build:server",
    "serve:display": "npm run build:display && lite-server --baseDir=\"./dist/apps/display/\"",
    "analyze:display": "webpack-bundle-analyzer dist/apps/display/stats.json",
    "copy": "cpx ./server/views/*.* ./dist/server/views",
    "pwa": "ng add @angular/pwa@0.8.7 --project display",
    "test": "ng test",
    "lint": "./node_modules/.bin/nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "./node_modules/.bin/nx affected:apps",
    "affected:libs": "./node_modules/.bin/nx affected:libs",
    "affected:build": "./node_modules/.bin/nx affected:build",
    "affected:e2e": "./node_modules/.bin/nx affected:e2e",
    "affected:test": "./node_modules/.bin/nx affected:test",
    "affected:lint": "./node_modules/.bin/nx affected:lint",
    "affected:dep-graph": "./node_modules/.bin/nx affected:dep-graph",
    "format": "./node_modules/.bin/nx format:write",
    "format:write": "./node_modules/.bin/nx format:write",
    "format:check": "./node_modules/.bin/nx format:check",
    "update": "ng update @nrwl/schematics",
    "update:check": "ng update",
    "workspace-schematic": "./node_modules/.bin/nx workspace-schematic",
    "dep-graph": "./node_modules/.bin/nx dep-graph",
    "help": "./node_modules/.bin/nx help",
    "build:modern:display": "ng build --project display --prod",
    "build:modern:studio": "ng build --project studio --prod",
    "dev:modern:studio": "ng build --project studio",
    "http:display": "light-server -s dist/apps/display -p 3500",
    "http:studio": "light-server -s dist/apps/studio -p 4200"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "^0.803.6",
    "@angular-devkit/build-webpack": "^0.803.6",
    "@angular/animations": "^8.2.8",
    "@angular/cdk": "^8.2.1",
    "@angular/common": "^8.2.8",
    "@angular/compiler": "^8.2.7",
    "@angular/core": "8.2.8",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "^8.2.8",
    "@angular/material": "^7.0.0",
    "@angular/platform-browser": "^8.2.8",
    "@angular/platform-browser-dynamic": "^8.2.8",
    "@angular/pwa": "^0.803.6",
    "@angular/router": "^8.2.8",
    "@angular/service-worker": "^8.2.8",
    "@auth0/angular-jwt": "^3.0.0",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-free": "^5.11.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-regular-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@ng-bootstrap/ng-bootstrap": "^5.1.1",
    "@ng-select/ng-select": "^3.0.7",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@ngxs-labs/dispatch-decorator": "^2.1.0",
    "@ngxs-labs/emitter": "^2.0.0",
    "@ngxs/router-plugin": "^3.5.1",
    "@ngxs/storage-plugin": "^3.5.1",
    "@ngxs/store": "^3.5.0",
    "@ngxs/websocket-plugin": "^3.5.1",
    "@nrwl/nx": "7.6.0",
    "@nrwl/schematics": "^8.5.2",
    "@schematics/angular": "^8.3.6",
    "angular-calendar": "^0.26.4",
    "angular-froala-wysiwyg": "^3.0.5",
    "angularx-flatpickr": "^6.1.1",
    "bcryptjs": "^2.4.3",
    "bootstrap": "^4.3.1",
    "bootstrap-select": "^1.13.11",
    "braintree": "^2.20.0",
    "chart.js": "^2.8.0",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "cors-anywhere": "^0.4.1",
    "date-fns": "^1.29.0",
    "dotenv": "^8.1.0",
    "express": "^4.17.1",
    "express-mailer": "^0.3.1",
    "flag-icon-css": "^3.4.0",
    "flatpickr": "^4.6.3",
    "htmlspecialchars": "^1.0.5",
    "jquery": "^3.4.1",
    "jsonwebtoken": "^8.5.1",
    "make-dir": "^3.0.0",
    "mongoose": "^5.7.1",
    "morgan": "^1.9.1",
    "ng2-charts": "^2.3.0",
    "ngx-braintree": "^8.0.0",
    "ngx-paypal": "^4.0.0",
    "ngx-youtube-player": "^7.1.1",
    "popper.js": "^1.15.0",
    "primeicons": "^2.0.0",
    "primeng": "^8.0.3",
    "pug": "^2.0.4",
    "pug-cli": "^1.0.0-alpha6",
    "quill": "^1.3.7",
    "rss-parser": "^3.7.2",
    "rxjs": "~6.5.3",
    "scandir": "^0.1.2",
    "socket.io": "^2.3.0",
    "socket.io-client": "^2.3.0",
    "uuid": "^3.3.3",
    "validator": "^11.1.0",
    "videogular2": "^7.0.1",
    "yarn": "^1.19.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.803.6",
    "@angular/cli": "^8.3.6",
    "@angular/compiler-cli": "^8.2.8",
    "@angular/language-service": "^8.2.8",
    "@ngxs/devtools-plugin": "^3.5.1",
    "@ngxs/logger-plugin": "^3.5.1",
    "@nrwl/builders": "7.8.7",
    "@types/core-js": "^2.5.2",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^23.0.0",
    "@types/mocha": "^5.2.5",
    "@types/node": "^10.12.5",
    "@types/socket.io": "^2.1.2",
    "@types/socket.io-client": "^1.4.32",
    "codelyzer": "^5.1.2",
    "concurrently": "^4.0.1",
    "cpx": "^1.5.0",
    "cypress": "^3.4.1",
    "jasmine-core": "~2.99.1",
    "jasmine-marbles": "0.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.9.0",
    "jest-preset-angular": "^7.1.1",
    "karma": "^4.3.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "light-server": "^2.6.4",
    "lite-server": "^2.5.4",
    "nodemon": "^1.19.2",
    "prettier": "1.18.2",
    "protractor": "~5.4.0",
    "tslint": "^5.20.0",
    "typescript": "~3.5.3"
  }
}
<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅
my ng --version:

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.3
@angular/cdk                      8.2.1
@angular/cli                      8.3.6
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@angular/pwa                      0.803.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

please help. Best regards from Slovenia

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
