### ISSUE TITLE
When do ng new <project> --minimal, it should include tslint.json file as well.

### ISSUE THREAD

**Issue by chgc** [angular/angular-cli#15711]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...
When doing new new project with `--minimal`, it doesn't include `tslint.json` file. It will make vscode complain a lot.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Include `tslint.json` file even with minimal project creation.

**Comment by alan-agius4** [comment]
Hi, can you please elaborate on the warning you are seeing in vacode? Having a tslint.json is strictly optional and you shouldn’t see any warnings when not having one.

**Comment by chgc** [comment]
![image](https://user-images.githubusercontent.com/4550568/65851934-260d3280-e387-11e9-941e-4c1ca192005a.png)
![image](https://user-images.githubusercontent.com/4550568/65851956-3ae9c600-e387-11e9-9cd4-4fb231f2927f.png)
There is no tslint.json file created.

Here are what my VSC is complain about
![image](https://user-images.githubusercontent.com/4550568/65852052-8f8d4100-e387-11e9-85e0-1e1486646626.png)
![image](https://user-images.githubusercontent.com/4550568/65852076-a338a780-e387-11e9-9b28-9b8b1fc8a5d8.png)

and I didn't change any tslint setting, everything is by default.

**Comment by filipesilva** [comment]
Heya, I just tried following your repro steps on VSCode and I don't see any warnings:
![image](https://user-images.githubusercontent.com/4172079/65969954-91c1cf00-e45d-11e9-8a76-56f0e1609dec.png)

I'm not sure what we could be doing to prevent your editor from showing these warnings when we don't include a `tslint.json` at all to begin with. Perhaps you have a `tslint.json` somewhere up the directory tree that gets picked up automatically by the editor?

**Comment by chgc** [comment]
after more dig around, I found `tslint.json` file in my user profile folder (in %USERPROFILE% folder). and that tslint.json is there since 2016. case close,  Thanks for the help.
