### ISSUE TITLE
Custom style file not added by build

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#1573]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Windows 10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
**6.2.2**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

**I added a file in /src/assets/scss/main.css. and added the file in index.html.**

**When i run ng build --prod** the file isn't copied to the dist the for example?

**What is the way to include a custom scss file? which is used for generic design? so it is bundles?**

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
Try putting the CSS file in `public` instead.

**Comment by filipesilva** [comment]
The functionality as you were trying to use it does not exist, but https://github.com/angular/angular-cli/pull/1633 adds an implementation that allows this use.
