### ISSUE TITLE
passing a Tree & Rules between schematics

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular-cli#15739]
if I have two (or more) schematics that must be executed in sequence, 
I want to create the initial Tree and pass it to the first schematic which returns a Rule,
and I want to pass the modified Tree (after applying the returned Rule from schematic #1) to the next schematic in sequence, ..and so on

so I need to get the last updated Tree after applying all Rules (in sequence) via all schematics and then execute schematics on the final Tree via node.js (not schematics cli)

**Comment by alan-agius4** [comment]
Hi @xxyyzz2050, you can use `chain` to run schematics and rules in sequence that alter the same tree

Example:
```ts
    return chain([
      externalSchematic('@schematics/angular', 'universal', options),
      addScriptsRule(options),
      updateServerTsConfigRule(options),
    ]);
```

**Comment by xxyyzz2050** [comment]
from where can I get a reference to these API functions?

@alan-agius4

**Comment by alan-agius4** [comment]
The main package for schematics is `@angular-devkit/schematics`.

**Comment by alan-agius4** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/15779 in terms of providing more docs in for this package.
