### ISSUE TITLE
 Angular 8 does not load the scripts and styles described in angular.json

### ISSUE THREAD

**Issue by GonzagaNeto** [angular/angular-cli#15730]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I need to use bootstrap4 with Angular8, but when mapping style files and scripts in angular.json, when running the server, the files are not loaded. I know you could put the link directly in index.html, but if the oriented form is in angular.json it should be working. How to solve this issue of angular.json?

## 🔬 Minimal Reproduction
- npm install bootstrap jquery popper.js --save (Install libs)
- Configure angular.json
```
"styles": [
  "node_modules/bootstrap/dist/css/bootstrap.css",
  "src/styles.scss"
],

"scripts": [
  "node_modules/jquery/dist/jquery.js",
  "node_modules/popper.js/dist/umd/popper.js",
  "node_modules/bootstrap/dist/js/bootstrap.js"
]
```
- Insert a component boostrap in app.component.html to test;
```
<div class="alert alert-primary" role="alert">
  A simple primary alert—check it out!
</div>
```
- run ng serve

## 🔥 Exception or Error
<pre>There is no exception, the scripts and style simply do not load.<code>

</code>

</pre>

## 🌍 Your Environment
<pre>
Angular CLI: 8.3.6
Node: 12.9.1
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.6
@angular-devkit/core         8.3.6
@angular-devkit/schematics   8.3.6
@schematics/angular          8.3.6
@schematics/update           0.803.6
rxjs                         6.4.0
<code>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, it doesn’t seem that you are dependent on `@angular-devkit/build-angular`, are you using custom builders to build you application?

**Comment by GonzagaNeto** [comment]
No, Alan, I don't use custom builder. The installation is standard. I use "npm install -g @ angular / cli", just that to install Angular8. I haven't changed anything, nor added anything else besides the Bootstrap4, jquery and popper.js libraries.

**Comment by alan-agius4** [comment]
Hi @GonzagaNeto, I tried to replicate the issue, however I am unable too.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by GonzagaNeto** [comment]
I managed to solve the problem, although I did not identify the cause. Redo the installation of Node and Angular, then bootstrap along with jquery and popper.js, according to the same procedure described above. It worked, it was probably something connected to the Node or Angular installation.
