### ISSUE TITLE
ng serve not reporting error after rebuild

### ISSUE THREAD

**Issue by berenyibalazs** [angular/angular-cli#15747]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Dont know i am a newbie.

### Description

'ng serve' says compiled successfully when there are compile errors.

## 🔬 Minimal Reproduction
1 create two compile time errors in two different files
2 start ng serve
3 after compile fails
    fix one error in one file 
4 ng serve rebuilds and reports:
- remaining error
- compile successful
<pre><code>
chunk {main} main.js, main.js.map (main) 2 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 122 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 9.71 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2019-10-03T10:04:30.586Z - Hash: 982975623bf1aaebc770 - Time: 8387ms

ERROR in src/app/c1/c1.component.ts:13:4 - error TS2322: Type '"1"' is not assignable to type 'number'.

13    this.a = '1';
      ~~~~~~
src/app/c2/c2.component.ts:13:4 - error TS2322: Type '"asdf"' is not assignable to type 'number'.

13    this.a = 'asdf';
      ~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
i ｢wdm｣: Compiling...
95% emitting CopyPlugin
    ERROR in src/app/c2/c2.component.ts(13,4): error TS2322: Type '"asdf"' is not assignable to type 'number'.

Date: 2019-10-03T10:04:52.355Z - Hash: f8f9752b170e82ac3b00
2 unchanged chunks
chunk {main} main.js, main.js.map (main) 55 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 264 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.08 MB [initial] [rendered]
Time: 9185ms
i ｢wdm｣: Compiled successfully.
</code></pre>
- browser reloads without reporting compile time error

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.7
Node: 12.6.0
OS: win32 x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.7
@angular-devkit/build-angular     0.803.7
@angular-devkit/build-optimizer   0.803.7
@angular-devkit/build-webpack     0.803.7
@angular-devkit/core              8.3.7
@angular-devkit/schematics        8.3.7
@angular/cli                      8.3.7
@ngtools/webpack                  8.3.7
@schematics/angular               8.3.7
@schematics/update                0.803.7
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, this is intended that type errors aren't sent to Webpacl when using the forked type checker, which is turned on by default. 

If they were, they would blocked the compilation, then there's no point in having a forked type checker as rebuilds would just take longer.

**Comment by alan-agius4** [comment]
Closing as this is the indented behaviour.
