### ISSUE TITLE
normalize angular project layouts

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#15741]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] update
- [x] lint
```

### Description
We have made changes to the "standard" Angular project config (tsconfig.json -> tsconfig.app.json for example) throughout the evolution of the CLI. Due to the power of `angular.json`, old projects keep working, but don't look like newer projects.

### Describe the solution you'd like
Although old projects keep working, it would be better to standardize what we create as `ng new` as official/canonical/expected/normal by adding update schematics to move the various files to match our latest expectations.

This will also make writing future schematics easier because we can make more assumptions about the Angular workspace layout.

See a discussion about some of this on Material here: angular/material.angular.io#641

**Comment by vikerman** [comment]
This is really complicated. I don't think we can do this in a way where we can actually be successful.

https://github.com/cexbrayat/angular-cli-diff catalogs all the changes and also shows the magnitude of the problem.

We have gotten more aggressive with the migrations in the later version of the CLI(since ng update has been available) - wherever we can find an exact match.

**Comment by Splaktar** [comment]
Updated link to the discussion (broken link in OP): https://github.com/angular/material.angular.io/pull/641#discussion_r330673934

**Comment by vikerman** [comment]
@StephenFluin

**Comment by alan-agius4** [comment]
We try our best to normalize project layouts and configuration between major versions. In some cases we also provide opt-in migrations such as production by default https://github.com/angular/angular-cli/pull/20233 were a migration is risky. 

In some cases though the risk of breaking a working project is too big to provide such migrations.
