### ISSUE TITLE
Switching to es2015 compile target dropped code coverage

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#15742]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

Switching to es2015 compile target in tsconfig.json dropped our code coverage by ~10%. We are uploading lvoc report to sonarqube. 

Does anyone else discovered this by switching to diffrential loading

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.3
Node: 12.3.1
OS: win32 x64
Angular: 8.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker 

Package                            Version------------------------------------------------------------
@angular-devkit/architect          0.803.3
@angular-devkit/build-angular      0.803.5
@angular-devkit/build-optimizer    0.803.5
@angular-devkit/build-webpack      0.803.5
@angular-devkit/core               8.3.3
@angular-devkit/schematics         8.3.3
@angular/cdk                       8.1.2
@angular/cli                       8.3.3
@angular/flex-layout               8.0.0-beta.26
@angular/material                  8.1.3
@angular/material-moment-adapter   8.1.3
@angular/pwa                       0.801.3
@ngtools/webpack                   8.3.5
@schematics/angular                8.3.3
@schematics/update                 0.803.3
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2 

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, do you have some code that can demonstrate the difference in code coverage metric between es5 and es2015?

**Comment by elvirdolic** [comment]
@alan-agius4 

here is a simple pipe and the lcov report

![image](https://user-images.githubusercontent.com/17769458/66401417-6d2ca080-e9e3-11e9-96a0-551f0feb86b3.png)

Left is before es6 and right is es6 change

here is the code:

```typescript
import { Pipe, PipeTransform } from '@angular/core';

/**
 * Returns color string based on remaining value.
 * Example: value = 10;max = 100; => 90% => red
 */
@Pipe({
  name: 'indicator'
})
export class IndicatorPipe implements PipeTransform {
  transform(percentage: number, treshhold?: number[]): string {
    if (!treshhold) {
      treshhold = [60, 90]; // default treshhold
    } else if (treshhold.length !== 2) {
      throw new Error('Treshold parameter should be array of two numbers');
    }
    if (percentage !== undefined) {
      if (percentage >= treshhold[1]) {
        return 'red';
      } else if (treshhold[0] <= percentage && percentage < treshhold[1]) {
        return 'orange';
      } else {
        return 'gray';
      }
    } else {
      return 'gray';
    }
  }
}
```

**Spec file**

```typescript
import { TestBed } from '@angular/core/testing';
import { configureTestSuite } from 'ng-bullet';
import { IndicatorPipe } from './indicator.pipe';

describe('IndicatorPipe', () => {
  let pipe: IndicatorPipe;

  configureTestSuite(() => {
    TestBed.configureTestingModule({
      providers: [IndicatorPipe]
    });
  });

  beforeEach(() => {
    pipe = TestBed.get(IndicatorPipe) as IndicatorPipe;
  });

  it('should mark as red everything above 90%', () => {
    expect(pipe.transform(100)).toEqual('red');
    expect(pipe.transform(92)).toEqual('red');
    expect(pipe.transform(90)).toEqual('red');
  });

  it('should mark as gray if value is negative', () => {
    expect(pipe.transform(-8)).toEqual('gray');
  });

  it('should mark as red if value is greater than max', () => {
    expect(pipe.transform(888)).toEqual('red');
  });

  it('should mark as orange everything above 60% and below 90%', () => {
    expect(pipe.transform(88)).toEqual('orange');
    expect(pipe.transform(60)).toEqual('orange');
  });

  it('should mark as gray everything below 60%', () => {
    expect(pipe.transform(59)).toEqual('gray');
    expect(pipe.transform(0)).toEqual('gray');
  });

  it('should set correct values based on custom treshold', () => {
    expect(pipe.transform(15, [20, 80])).toEqual('gray');
    expect(pipe.transform(20, [20, 80])).toEqual('orange');
    expect(pipe.transform(79, [20, 80])).toEqual('orange');
    expect(pipe.transform(80, [20, 80])).toEqual('red');
  });
});

```

**Comment by FDIM** [comment]
I've observed the same after moving to es2015 module type and only using import/export syntax. 

We lost around 5% code coverage and 15% in size when compared to a build with commonjs.

I am not entirely sure but I think that code coverage metrics are calculated based on javascript file and not typescript, hence if output is different - metrics will be different.

**Comment by oleg-vasilyev** [comment]
same issue for me
any updates?

**Comment by alan-agius4** [comment]
I had a quick look at this, and indeed it seems to be caused by what @FDIM described as the transpilled code which is later instrumented is different.

Left ES5, Right ES2015
![image](https://user-images.githubusercontent.com/17563226/76629897-629ca700-653f-11ea-9784-d287ad6545d7.png)

**Comment by elvirdolic** [comment]
I think we can close this issue now as we have found out what's the reason.
