### ISSUE TITLE
ng serve recompile time very slow

### ISSUE THREAD

**Issue by sodepr** [angular/angular-cli#15746]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] serve
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
ng serve recompile time very slow. It spend about 10s to recompile althought I only change one space on css ~~

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code>
Angular CLI: 8.3.3
Node: 10.16.3
OS: win32 x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms   
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------   
@angular-devkit/architect         0.803.3
@angular-devkit/build-angular     0.803.3
@angular-devkit/build-optimizer   0.803.3
@angular-devkit/build-webpack     0.803.3
@angular-devkit/core              8.3.3
@angular-devkit/schematics        8.3.3
@angular/cli                      8.3.3
@ngtools/webpack                  8.3.3
@schematics/angular               8.3.3
@schematics/update                0.803.3
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @sodepr. thanks for opening the issue. Is there a way you can share your project or a reproduction so that we can take a look at?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. 

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sodepr** [comment]
This is my repos
https://github.com/letanloc1998/GFood-Angular.git

It spend about 5s - 20s when i change something (simple change as add space, add new line,...)
![image](https://user-images.githubusercontent.com/55951715/66152694-3a318800-e644-11e9-925e-029a4aec4bbc.png)

**Comment by sodepr** [comment]
![image](https://user-images.githubusercontent.com/55951715/66152856-8f6d9980-e644-11e9-8cf5-87777a36da8c.png)

**Comment by sodepr** [comment]
I updates new version node, npm but nothing is change ~~
</code>
Angular CLI: 8.3.7
Node: 12.11.1
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.7
@angular-devkit/core         8.3.7
@angular-devkit/schematics   8.3.7
@schematics/angular          8.3.7
@schematics/update           0.803.7
rxjs                         6.4.0
</pre>

**Comment by sodepr** [comment]
Configuration my laptop:
I5 3340M
8GB ram
Samsung ssd 860 evo 512GB

**Comment by sodepr** [comment]
I see same issue but bot auto clock ~~
https://github.com/angular/angular-cli/issues/6103

**Comment by clydin** [comment]
Looks like the large amount of assets is causing the slowdown.  Can you remove non-essential files from the assets directory?

**Comment by sodepr** [comment]
> Looks like the large amount of assets is causing the slowdown. Can you remove non-essential files from the assets directory?

I did it, but it doesn't reduce recompile time.
You can see this commit I move file assets but nothing is change: https://github.com/letanloc1998/GFood-Angular/tree/227f63a29e003758e6e07056b561a7314137143e

**Comment by clydin** [comment]
There's still over 1500 files and 22 MB in the assets folder.  This is going to take some time to copy.

**Comment by sodepr** [comment]
> There's still over 1500 files and 22 MB in the assets folder. This is going to take some time to copy.

I return it to asset because it doesn't reduce recompile time
In localhost, I move **all file** in assets

**Comment by sodepr** [comment]
![image](https://user-images.githubusercontent.com/55951715/66174665-5fdc8280-e680-11e9-800a-34617dddc72b.png)
5s recompile when i delete one line html (and abou 3s reload page)
You can see no file in assets folder:
![image](https://user-images.githubusercontent.com/55951715/66174706-99ad8900-e680-11e9-87f3-eb2a1f6edfa8.png)

**Comment by clydin** [comment]
I'm unable to replicate the behavior you are seeing.  First change below is a TS file, second a CSS file, and third an HTML file.

```
chunk {main} main.js, main.js.map (main) 160 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 263 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 11.5 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.44 MB [initial] [rendered]
Date: 2019-10-04T01:30:12.616Z - Hash: 6f221bb7fb4e9a120bb3 - Time: 7640ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

Date: 2019-10-04T01:30:21.546Z - Hash: 6f221bb7fb4e9a120bb3
5 unchanged chunks

Time: 615ms
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

Date: 2019-10-04T01:30:36.442Z - Hash: 7914e96ba922047d0d49
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 160 kB [initial] [rendered]
Time: 573ms
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

Date: 2019-10-04T01:30:48.431Z - Hash: f8f4000a17dce840bd77
4 unchanged chunks
chunk {main} main.js, main.js.map (main) 160 kB [initial] [rendered]
Time: 634ms
ℹ ｢wdm｣: Compiled successfully.
```

**Comment by sodepr** [comment]
> I'm unable to replicate the behavior you are seeing. First change below is a TS file, second a CSS file, and third an HTML file.
> 
> ```
> chunk {main} main.js, main.js.map (main) 160 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 263 kB [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 11.5 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 4.44 MB [initial] [rendered]
> Date: 2019-10-04T01:30:12.616Z - Hash: 6f221bb7fb4e9a120bb3 - Time: 7640ms
> ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
> ℹ ｢wdm｣: Compiled successfully.
> ℹ ｢wdm｣: Compiling...
> 
> Date: 2019-10-04T01:30:21.546Z - Hash: 6f221bb7fb4e9a120bb3
> 5 unchanged chunks
> 
> Time: 615ms
> ℹ ｢wdm｣: Compiled successfully.
> ℹ ｢wdm｣: Compiling...
> 
> Date: 2019-10-04T01:30:36.442Z - Hash: 7914e96ba922047d0d49
> 4 unchanged chunks
> chunk {main} main.js, main.js.map (main) 160 kB [initial] [rendered]
> Time: 573ms
> ℹ ｢wdm｣: Compiled successfully.
> ℹ ｢wdm｣: Compiling...
> 
> Date: 2019-10-04T01:30:48.431Z - Hash: f8f4000a17dce840bd77
> 4 unchanged chunks
> chunk {main} main.js, main.js.map (main) 160 kB [initial] [rendered]
> Time: 634ms
> ℹ ｢wdm｣: Compiled successfully.
> ```

It time same as project of my friend, I think nodejs or something wrong in my lap. I will install windows and run it to check. Thank you very much

Huh, What configuration of you laptop/pc?

**Comment by alan-agius4** [comment]
@sodepr, you might also have an anti-virus that is scanning files when being accessed and is slowing the compilation.

I tried your reproduction and here's the timings
```
chunk {main} main.js, main.js.map (main) 156 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 263 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 11.4 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 4.44 MB [initial] [rendered]
Date: 2019-10-04T15:14:29.033Z - Hash: 608727f408d623de243c - Time: 12199ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...

Date: 2019-10-04T15:14:38.354Z - Hash: bc598b1bc970015bfcf4
4 unchanged chunks
chunk {styles} styles.js, styles.js.map (styles) 11.4 kB [initial] [rendered]
Time: 877ms
ℹ ｢wdm｣: Compiled successfully.
```

Also, having the entire `fontawesome` as part of the your assets doesn't seem right as it includes files that will never be used by your application and are copied redundantly.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by hiepxanh** [comment]
@alan-agius4 are you using Mac OS? I see significant build speed between Window and Mac.

**Comment by letanloc1998** [comment]
I've fix this problem (sodepr also my github nick)
I update lasted version of Node (I remeber this is version 12.x in that time). Before I use Node LTS (May be version 10.x). ~~
Angular not working well in old Node version.

**Comment by letanloc1998** [comment]
Thank you very much. This is other account so now I've receive notification. 

> @sodepr, you might also have an anti-virus that is scanning files when being accessed and is slowing the compilation.
> 
> I tried your reproduction and here's the timings
> 
> ```
> chunk {main} main.js, main.js.map (main) 156 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 263 kB [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 11.4 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 4.44 MB [initial] [rendered]
> Date: 2019-10-04T15:14:29.033Z - Hash: 608727f408d623de243c - Time: 12199ms
> ** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
> ℹ ｢wdm｣: Compiled successfully.
> ℹ ｢wdm｣: Compiling...
> 
> Date: 2019-10-04T15:14:38.354Z - Hash: bc598b1bc970015bfcf4
> 4 unchanged chunks
> chunk {styles} styles.js, styles.js.map (styles) 11.4 kB [initial] [rendered]
> Time: 877ms
> ℹ ｢wdm｣: Compiled successfully.
> ```
> 
> Also, having the entire `fontawesome` as part of the your assets doesn't seem right as it includes files that will never be used by your application and are copied redundantly.
