### ISSUE TITLE
ng serve --aot recompiles when source file is opened

### ISSUE THREAD

**Issue by markus-heinisch** [angular/angular-cli#15750]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, no problem with Angular 7

### Description
When I run `ng serve --aot` the application is recompiled everytime  I open a source file in an editor like notepad or vs code for the first time. A second opening of the same source file does not result in a recompile! 

## 🔬 Minimal Reproduction
1.) `ng new myApp`
2.) `ng serve --aot`
3.) Open a HTML or TS file of the application
==> ng recompiles the app
`ng serve` without option `--aot` works as expected 

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.5
Node: 10.16.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.5
@angular-devkit/core         8.3.5
@angular-devkit/schematics   8.3.5
@schematics/angular          8.3.5
@schematics/update           0.803.5
rxjs                         6.4.0
</code></pre>

**Comment by clydin** [comment]
The CLI watches for file changes on disk by asking the OS when something changes.  If your IDE or OS (virus scanners on windows, for instance) are doing anything with that file on load then it could trigger a recompile.  I also cannot replicated this using VSCode or vi on MacOS.

**Comment by markus-heinisch** [comment]
Thanks @clydin, I have the issue since I have migrated my application from Angular 7 to Angular 8 a week ago. Therefore, I guess it has something to do with Angular 8.

**Comment by alan-agius4** [comment]
I also tried this locally, and I was unable to replicate the issue.

**Comment by alan-agius4** [comment]
Is this still reproducible?

**Comment by markus-heinisch** [comment]
Still reproducible with current version :-(
```
Angular CLI: 8.3.20
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```
