### ISSUE TITLE
excluding source maps with the new webpack mode

### ISSUE THREAD

**Issue by DxCx** [angular/angular-cli#1575]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux (Arch)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack
node: 6.3.1
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
this is abit tricky, i've found the issue because i've installed @ngrx/store,
however, it is more general one.
at the moment, with the new webpack mode, one cannot exclude sourcemaps,
and not all node_modules have sourcemaps with them.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
WARNING in ./~/@ngrx/router/hooks.js
Cannot find source file '../../lib/hooks.ts': Error: Can't resolve '../../lib/hooks.ts' in '/home/hagai/a2z/gits/anipo/anipo-io/node_modules/@ngrx/router'
 @ ./~/@ngrx/router/router-instruction.js 35:14-32
 @ ./~/@ngrx/router/index.js
 @ ./src/app/app.routes.ts
 @ ./src/main.ts
 @ multi main

WARNING in ./~/@ngrx/router/match-pattern.js
Cannot find source file '../../lib/match-pattern.ts': Error: Can't resolve '../../lib/match-pattern.ts' in '/home/hagai/a2z/gits/anipo/anipo-io/node_modules/@ngrx/router'
 @ ./~/@ngrx/router/redirect.js 19:22-48
 @ ./~/@ngrx/router/index.js
 @ ./src/app/app.routes.ts
 @ ./src/main.ts
 @ multi main

WARNING in ./~/@ngrx/core/add/operator/enterZone.js
Cannot find source file '../../../../lib/add/operator/enterZone.ts': Error: Can't resolve '../../../../lib/add/operator/enterZone.ts' in '/home/hagai/a2z/gits/anipo/anipo-io/node_modules/@ngr
x/core/add/operator'
 @ ./~/@ngrx/router/router-instruction.js 29:0-44
 @ ./~/@ngrx/router/index.js
 @ ./src/app/app.routes.ts
 @ ./src/main.ts
 @ multi main

WARNING in ./~/@ngrx/core/compose.js
Cannot find source file '../../lib/compose.ts': Error: Can't resolve '../../lib/compose.ts' in '/home/hagai/a2z/gits/anipo/anipo-io/node_modules/@ngrx/core'
 @ ./~/@ngrx/store-log-monitor/json-tree/types.js 2:16-45
 @ ./~/@ngrx/store-log-monitor/json-tree/json-tree.js
 @ ./~/@ngrx/store-log-monitor/log-monitor/log-monitor-entry.js
 @ ./~/@ngrx/store-log-monitor/log-monitor/log-monitor.js
 @ ./~/@ngrx/store-log-monitor/store-log-monitor.js
 @ ./~/@ngrx/store-log-monitor/index.js
 @ ./src/main.ts
 @ multi main

WARNING in ./~/@ngrx/core/operator/enterZone.js
Cannot find source file '../../../lib/operator/enterZone.ts': Error: Can't resolve '../../../lib/operator/enterZone.ts' in '/home/hagai/a2z/gits/anipo/anipo-io/node_modules/@ngrx/core/operato
r'
 @ ./~/@ngrx/core/add/operator/enterZone.js 3:18-53
 @ ./~/@ngrx/router/router-instruction.js
 @ ./~/@ngrx/router/index.js
 @ ./src/app/app.routes.ts
 @ ./src/main.ts
 @ multi main

5. Mention any other details that might be useful.
as i'm familiar with webpack, i was able to find the config quickly and make a W/O
in models/webpack-build-common.ts file (getWebpackCommonConfig)
i've added "path.resolve(projectRoot, 'node_modules/@ngrx'),"
under loader source-map (line 32 here).

but i've opened the ticket because i think this is not proper,
the source map exclude should be controlled from the project itself.
(maybe add it to some config - not sure)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mb-jenks** [comment]
@DxCx could you explain how you patched this issue?

**Comment by TheLarkInn** [comment]
Related to #1578.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/1673
