### ISSUE TITLE
fail with library use angular8 loadChildren format

### ISSUE THREAD

**Issue by yozman** [angular/angular-cli#15757]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No, it's just come up with angular8 new loadChildren format

### Description

 A clear and concise description of the problem...
when I try to use `import(...)` to lazyload route in library, it come up with error, I think the reason is rollup configuration for library doesn't support multiple chunk, when I change to use old loadChildren format like `loadChildren: './admin-user-login.module#AdminUserLoginModule'` it's works well

## 🔬 Minimal Reproduction

1. generate a route as a library
```s
ng g library admin-user-login
```
2. add route define for module
```ts
// projects/admin-user-login/src/lib/admin-user-login.route.ts

import { Route, Routes } from '@angular/router';
import { AdminUserLoginComponent } from './admin-user-login.component';

export const AdminUserLoginRouteEntry: Route = {
  path: 'login',
  // loadChildren: './admin-user-login.module#AdminUserLoginModule', // works well
  async loadChildren() {
    const { AdminUserLoginModule } = await import('./admin-user-login'); // error, because import make multiple chunks.
    return AdminUserLoginModule;
  },
}

export const AdminUserLoginRouteChildren: Routes = [
  {
    path: '',
    component: AdminUserLoginComponent,
  }
]

// projects/admin-user-login/src/lib/admin-user-login.module.ts

import { NgModule } from '@angular/core';
import { AdminUserLoginComponent } from './admin-user-login.component';
import { RouterModule } from '@angular/router';
import { AdminUserLoginRouteChildren } from './admin-user-login.route';

@NgModule({
  declarations: [AdminUserLoginComponent],
  imports: [
    RouterModule.forChild(AdminUserLoginRouteChildren),
  ],
  exports: [AdminUserLoginComponent]
})
export class AdminUserLoginModule { }

// projects/admin-user-login/src/public-api.ts

/*
 * Public API Surface of admin-user-login
 */

export * from './lib/admin-user-login.service';
export * from './lib/admin-user-login.component';
export * from './lib/admin-user-login.module';
export * from './lib/admin-user-login.route';
```
3. run build
```s
ng build admin-user-login
```

## 🔥 Exception or Error
<pre><code>

ERROR: You must set "output.dir" instead of "output.file" when generating multiple chunks.
An unhandled exception occurred: You must set "output.dir" instead of "output.file" when generating multiple chunks.
See "/private/var/folders/gn/mbh35twj2yl1cbb9dszc7sm40000gn/T/ng-G9tuPy/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.7
Node: 12.11.0
OS: darwin x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.7
@angular-devkit/build-angular      0.803.7
@angular-devkit/build-ng-packagr   0.803.7
@angular-devkit/build-optimizer    0.803.7
@angular-devkit/build-webpack      0.803.7
@angular-devkit/core               8.3.7
@angular-devkit/schematics         8.3.7
@angular/cli                       8.3.7
@ngtools/webpack                   8.3.7
@schematics/angular                8.3.7
@schematics/update                 0.803.7
ng-packagr                         5.5.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

I thinks it's come up with wrong rollup configuration

**Comment by yozman** [comment]
now my hack solution is 
1. use yarn workspace feature
2. set `lib/public-api.ts` as main in library `package.json` file
3. skip build library and direct build main application

**Comment by alan-agius4** [comment]
Hi, lazy loading is only supported at an application and not a library level.

See:https://github.com/angular/angular-cli/issues/6373#issuecomment-533204545 and https://github.com/angular/angular/issues/31893#issuecomment-516615243
