### ISSUE TITLE
Issue with `fullTemplateTypeCheck` and `ng serve`

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-cli#15762]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I don't know.

### Description

When having `fullTemplateTypeCheck` enabled in `tsconfig.json` and running `ng serve` everything runs fine initially. I might, for example, get nice error messages about my template type-check issues (with colors and everything :smiley:):

```
ERROR in src/app/app.component.html:38:66 - error TS2322: Type 'SearchResults | null' is not assignable to type 'SearchResults | undefined'.
  Type 'null' is not assignable to type 'SearchResults | undefined'.

38 <aio-search-results #searchResultsView *ngIf="showSearchResults" [searchResults]="searchResults | async" (resultSelected)="hideSearchResults()"></aio-search-results>
                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:23:16
    23   templateUrl: './app.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.
```

Then on re-compiling (e.g. after editing a file and saving), I get the following error:

```
ERROR in ./src/main.ts
    at plugin.done.then ([...]\angular\aio\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: [...]\angular\aio\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile ([...]\angular\aio\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:918:23)
    at plugin.done.then ([...]\angular\aio\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
i ｢wdm｣: Failed to compile.
```

I might then get some error template type-check errors, but not as nicely formatted (or colorful) as before:

```
ERROR in src/app/app.component.html(38,66): error TS2322: Type 'SearchResults | null' is not assignable to type 'SearchResults | undefined'.
      Type 'null' is not assignable to type 'SearchResults | undefined'.
    src/app/app.component.html(47,63): error TS2322: Type 'NavigationNode[]' is not assignable to type 'Option[]'.
      Type 'NavigationNode' is not assignable to type 'Option'.
        Types of property 'title' are incompatible.
          Type 'string | undefined' is not assignable to type 'string'.
            Type 'undefined' is not assignable to type 'string'.
    src/app/app.component.html(47,87): error TS2322: Type 'NavigationNode' is not assignable to type 'Option'.
    src/app/custom-elements/api/api-list.component.html(24,8): error TS2322: Type 'ApiSection[] | null' is not assignable to type 'ApiSection[] | Iterable<ApiSection> | undefined'.
...
```

After this first error, the app is not re-compiled when I make changes (I have to stop the process and run `ng serve` anew).

(NOTE: The error seems only (or much more often) happen when there _are_ template type-check errors.)

## 🔬 Minimal Reproduction

It started happening for me in PR angular/angular#32980. To reproduce, you could:

1. Check out the PR.
2. Reset to the commit before ``build(docs-infra): enable `fullTemplateTypeCheck` (and fix failures)`` (currently https://github.com/angular/angular/pull/32980/commits/3f228a626).
3. Add `fullTemplateTypeCheck: true` in `aio/tsconfig.json > angularCompilerOptions`.
4. Run `yarn --cwd=aio && yarn --cwd=aio start`. _(You should see some nice template type-check error messages.)_
5. Open `aio/src/app/app.component.ts`, make a change and save it. _(You should see the error.)_

(NOTE: If that reproduction isn't helpful, I can try to create a minimal one with a new app.)

## 🌍 Your Environment

(NOTE: I am on 9.0.0-next.8 now, but this happened with 9.0.0-next.6 as well.)

<pre><code>
Angular CLI: 9.0.0-next.8
Node: 10.16.3
OS: win32 x64
Angular: 9.0.0-next.9
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.8
@angular-devkit/build-angular     0.900.0-next.8
@angular-devkit/build-optimizer   0.900.0-next.8
@angular-devkit/build-webpack     0.900.0-next.8
@angular-devkit/core              9.0.0-next.8
@angular-devkit/schematics        9.0.0-next.8
@angular/cdk                      9.0.0-next.0
@angular/cli                      9.0.0-next.8
@angular/material                 9.0.0-next.0
@ngtools/webpack                  9.0.0-next.8
@schematics/angular               9.0.0-next.8
@schematics/update                0.900.0-next.8
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0
</code></pre>

**Comment by gkalpak** [comment]
cc @filipesilva

**Comment by filipesilva** [comment]
I think the errors being formatted different on rebuilds is due to https://github.com/angular/angular/issues/32213.

The `Module build failed` error on the first rebuild is https://github.com/angular/angular/issues/32214 I believe. I tried introducing a simple template type error as shows in [the docs](https://angular.io/guide/aot-compiler#phase-3-template-type-checking) and, and saw that it will show the `Module build failed` errors only if the `ng serve` starts with the error. If I introduce the error after the first build, everything is fine.
