### ISSUE TITLE
Object doesn't support property or method 'padStart' with differential loading in IE11

### ISSUE THREAD

**Issue by Totati** [angular/angular-cli#15763]
# 🐞 Bug report

### Command (mark with an `x`)

 
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

  I want to use es2017 features like padStart or es2019 feature like flatMap in one of my projects that has to be compatible with IE11, but these functions are not patched by the CLI.

## 🔬 Minimal Reproduction

<pre><code>
git clone https://github.com/Totati/differential-loading-ie11-issue.git
cd differential-loading-ie11-issue
npm install
ng build --prod
http-server .\dist\differential-loading-ie11-issue\
</code></pre>
open in IE11  http://127.0.0.1:8080/index.html

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: Object doesn't support property or method 'padStart'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.8
Node: 12.4.0
OS: win32 x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.8
@angular-devkit/build-angular     0.803.8
@angular-devkit/build-optimizer   0.803.8
@angular-devkit/build-webpack     0.803.8
@angular-devkit/core              8.3.8
@angular-devkit/schematics        8.3.8
@angular/cli                      8.3.8
@ngtools/webpack                  8.3.8
@schematics/angular               8.3.8
@schematics/update                0.803.8
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by clydin** [comment]
That is an ES2017 feature and will require a polyfill to use.
https://www.ecma-international.org/ecma-262/8.0/#sec-string.prototype.padstart

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by Totati** [comment]
@clydin Just for beeing clear. So features newer than es2015 are not polyfilled automatically by the CLI, and I have to import the ones I need in the polyfills.ts - it's okay to load them for core.js -, and willl be bundled for both es5 and es2015 builds?! 🙃

**Comment by clydin** [comment]
That is correct.  The Angular CLI currently does not perform automatic polyfilling except for the set of ES2015 features required by Angular.

By including any polyfills in the application’s polyfills file, the polyfill will be available to both application variants.
