### ISSUE TITLE
Include @angular/pwa in ng update

### ISSUE THREAD

**Issue by sebaherrera** [angular/angular-cli#15764]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Update @angular/pwa via `ng update`

### Describe the solution you'd like
 
Hi. Since @angular/pwa is updated frequently alongside @angular/cli, it would be very useful to update both packages via `ng update`, which also increments consistency with another packages behavior. Thanks.

### Describe alternatives you've considered
 
Alternative is to update @angular/cli and then run `npm update` for @angular/pwa

**Comment by alan-agius4** [comment]
Strictly speaking `@angular/pwa` is not needed as a dependency. This is because the pwa package is a schematic and is only used once when generating adding pwa capabilities to your application. After that, this package is not used.

**Comment by sebaherrera** [comment]
Interesting. I didn't know that. Thank you.
