### ISSUE TITLE
Ivy CSS @import requires exact file names

### ISSUE THREAD

**Issue by jkyoutsey** [angular/angular-cli#15772]
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, works pre-Ivy

### Description

9.0.0-next.6 CSS/SCSS @import statements do not resolve file names unless they are exact.
For example, pre-Ivy I could import the file `_variables.scss` with `@import './variables';`. In Ivy it must be `./_variables.scss`.

## 🔬 Minimal Reproduction

Migrate a project from version 8 to 9.0.0-next.6 that has CSS imports that omit *.scss or _'s from the import statements.

## 🔥 Exception or Error
```
This migration uses the Angular compiler internally and therefore projects that no longer build
successfully after the update cannot run the migration. Please ensure there are no AOT compilation
errors and rerun the migration.. The following project failed: src/tsconfig.app.json
            
            Error: error TS100: Couldn't resolve resource ../../assets/scss/common/component.common
from /.../src/app/common/app-header.component.scss
Migration can be rerun with: "ng update @angular/core --from 8.0.0 --to 9.0.0 --migrate-only"
            Successfully migrated all found undecorated classes
            that use dependency injection.
```

## 🌍 Your Environment
No longer available. Bug created after the fact on request of @Splaktar 

**Anything else relevant?**

**Comment by clydin** [comment]
This was actually an issue with the migrations present within “@angular/core” itself and not the Angular CLI.

However, this has been corrected on master and will be present within the next release.
https://github.com/angular/angular/commit/6f5f481fdae03f1d8db36284b64c7b82d9519d85#diff-2b010121275022321194b4cff2d113e3
