### ISSUE TITLE
make angular-automatic-lock-bot lock issues only on activity

### ISSUE THREAD

**Issue by tobias74** [angular/angular-cli#15771]
Every time the "angular-automatic-lock-bot" locks an issue that I was involved with, I receive a notification. This might be considered useless/annoying since it does not add any new information concerning the original issue. 

I understand of course that locking an issue is important in order to prevent people from "out-of-scope-discussing" (and notifying others) on an old issue. Nevertheless, notifying people about that fact that they will not be receiving any more notifications is somewhat undermining the original purpose. 

**Proposal: The issue should be kept open and only be locked after someone comments on it and a notification was sent out anyway.**

**Comment by clydin** [comment]
Only closed issues with 30 days of inactivity are locked.  The purpose is to proactively assist users who are trying to get help and prevent them from spending resources commenting on an issues that may be unmonitored or completely out of date in regards to their issue.  A reactive approach as suggested only allows for the hopeful mitigation of the errant comment and only guides the user to the correct path after they have proceeded on the incorrect path.
