### ISSUE TITLE
angular 7: Almost empty AppModule is producing huge main.js (= 367kb)

### ISSUE THREAD

**Issue by goodmite** [angular/angular-cli#15787]
# 🐞 bug report
I have an app with almost empty `AppModule`. After `ng build --prod` I am getting `main.js` size  = 367kb. Expected is around 100kb.

### Is this a regression?
No

### Description
I have an Angular 7 application consisting of 150+ components. I am trying to reduce first load time of this app by reducing the size of` main.js`. I removed all declarations and imports from `AppModule `except `AppComponent `and served the app. This gave me a main.js of size 367kb.
I tried using `webpack-bundle-analyser` and here is the results for `main.js`

<img width="960" alt="github" src="https://user-images.githubusercontent.com/16303528/65390882-2e121480-dd80-11e9-8327-9a7d97d49586.png">

I have been struggling with this issue with the last 10 months. I have wasted countless hours and tried and given up many times. I have posted on Reddit about it but no help. So I am posting it here.

## 🔬 Minimal Reproduction
Git hub repo: https://github.com/goodmite/angular-hello-world-size-too-big
To serve: `ng s`
visualize using `webpack-bundle-analyser`:  `npm run bundle-report`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 10.16.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.2
@angular-devkit/build-angular     0.10.2
@angular-devkit/build-optimizer   0.10.2
@angular-devkit/build-webpack     0.10.2
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@angular/pwa                      0.7.5
@ngtools/webpack                  7.0.2
@schematics/angular               0.7.5
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Comment by alxhub** [comment]
I'm transferring this issue to the Angular CLI repo, because this is a function of the bundler and tree-shaker, not the core framework.

**Comment by gmerabishvili** [comment]
@trotyl So, you say that if I keep my app.module super clean and if I import e.g third party lib  modules only in  lazy loaded modules that won't keep my initial bundle size? (main.js) very small?

**Comment by kyliau** [comment]
> > Since TestModule is not imported in AppModule in any way, adding or removing modules in TestModule should have no impact on main.js file size
> 
> That's totally wrong assumption, code splitting is based on module, not value, so that `@angular/core` can only exist in one bundle, in this case `main.js`. Any lazy bundle could increase the non-tree-shakable parts of `@angular/core`, resulting in bigger `@angular/core` remaining, thus bigger `main.js` bundle size.
> 
> As long as your lazy module make any additional usage of `@angular/core`, `@angular/common` or `rxjs`, size of `main.js` would certainly increased, and the stats seems expected so far.

That's correct. Splitting a module into smaller chunks is known as "cross module code motion" and afaik only Closure Compiler supports it. Until such feature is supported by Webpack, there's no open source Javascript tooling out there that could perform such advanced optimization.

That said, the explanation above does a great job explaining the current state of JS tooling in Angular CLI, and there's nothing that we could do at the moment to address this, so I'm closing this issue. Thanks.

**Comment by ilprima** [comment]
I have a similar problem. I use lazy loaded modules but my main.js size is big. It contains all the libraries i imported in my package.json file also if i dont use them in app.module but in lazy loaded modules and i dont import those moduels on app.module. Why are they in main.js?
