### ISSUE TITLE
Use cli generate library, then consume this library, all dependency injection failed

### ISSUE THREAD

**Issue by YouQingnzfintech** [angular/angular-cli#15789]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No idea, first time use.

### Description

I am create a library by angular cli, and want to reuse this library in other projects
The dependency in constructor will throw a "ERROR ReferenceError: HttpClient is not defined" 

## 🔬 Minimal Reproduction
1. create a new solution, then generate a library

`ng new CrankAngularComponents --createApplication=false`
`ng generate library crank-angular-components --prefix=crank`

2. modify the example code, 
add a Service in the component constructor
add a HttpClient in the service constructor

( detail can be check in the demo)
https://github.com/YouQingnzfintech/angular-custom-library-di-fail-demo
https://github.com/YouQingnzfintech/angular-custom-library-di-fail-demo/blob/master/projects/crank-angular-components/src/lib/crank-angular-components.component.ts
https://github.com/YouQingnzfintech/angular-custom-library-di-fail-demo/blob/master/projects/crank-angular-components/src/lib/crank-angular-components.service.ts

## 🔥 Exception or Error
<pre><code>

ERROR ReferenceError: HttpClient is not defined
    at push.../../Crank.NodePackages/CrankAngularComponents/dist/crank-angular-components/fesm2015/crank-angular-components.js.CrankAngularComponentsService.ctorParameters (crank-angular-components.js:24)
    at ReflectionCapabilities._ownParameters (core.js:15897)
    at ReflectionCapabilities.parameters (core.js:15922)
    at JitReflector.parameters (platform-browser-dynamic.js:48)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:20341)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:20294)
    at CompileMetadataResolver._getInjectableTypeMetadata (compiler.js:20512)
    at CompileMetadataResolver.getProviderMetadata (compiler.js:20521)
    at compiler.js:20459
    at Array.forEach (<anonymous>)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.8
Node: 10.15.3
OS: win32 x64
Angular: 8.2.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.8
@angular-devkit/build-angular      0.803.8
@angular-devkit/build-ng-packagr   0.803.8
@angular-devkit/build-optimizer    0.803.8
@angular-devkit/build-webpack      0.803.8
@angular-devkit/core               8.3.8
@angular-devkit/schematics         8.3.8
@angular/cli                       8.3.8
@ngtools/webpack                   8.3.8
@schematics/angular                8.3.8
@schematics/update                 0.803.8
ng-packagr                         5.6.0
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Should be fixed in ng-packagr version 5.6.1
