### ISSUE TITLE
feat-fix(appsScript): builds do not support appsscript deployment

### ISSUE THREAD

**Issue by AmitMY** [angular/angular-cli#15799]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
I would like to host an angular project as a web interface for a Google Suite plugin. To do so, I need to host the code on Google Appsscript.

To try and do that, I created an angular project, ran:
```bash
ng build  --prod --output-hashing none
mkdir appsscript
cd appsscript
clasp login # Login to your Google account
clasp create "angular"
cp -a ../dist/. . # Copy dist files to appsscript project
clasp push
```

And I get errors from appsscript like:
> Syntax error: Missing ; before statement. line: 1 file: appsscript/main-es2015

or
> Syntax error: Property "useDeprecatedSynchronousErrorHandling" already defined in this object literal. line: 1 file: appsscript/main-es5

Which as far as I understand, means that appsscript thinks this compiled code is not strict enough.

### Describe the solution you'd like
A build option with "strict" output code

### Describe alternatives you've considered
I've tried to compile to ES3, which is a JS version that appsscript should be able to analyze (although I'm running this in the browser eventually), 
But I get:
>  'Syntax error: Invalid property ID. line: 133 file: sheets/main',

which refers to this part of the code:
![image](https://user-images.githubusercontent.com/5757359/66480565-a29ac200-eaa7-11e9-9106-b8b49420021b.png)

**Comment by mgechev** [comment]
Hey @AmitMY, looks like Apps Script runs on the v8 runtime since Feb 5 2020. This means that you'd no longer have to set the compilation target to `es3`.

Feel free to give it a try and open another issue if you hit another blocker on our side.
