### ISSUE TITLE
NPM Installation Issues

### ISSUE THREAD

**Issue by hooloom** [angular/angular-cli#15802]
I'm not behind a proxy - I've tried a multiplicity of things.  Including setting the proxy to null, and completely uninstalling Angular CLI.  Didn't help now stuck.  It appears that this IP address has a degraded status.
- [X ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes needed to do an update after macOS Catalina install and move to ZSH.
### Description

The package times out at different intervals - I can ping the IP address associated to the NPM package without issue.  I am not behind a firewall or proxy.

## 🔬 Minimal Reproduction
npm install @angular/cli -g -verbose
npm install @angular/cli@latest -g -verbose


## 🔥 Exception or Error
this error appears at different points of the package installation
<pre><code>
FetchError: request to http://registry.npmjs.org/parallel-transform failed, reason: connect ETIMEDOUT 104.16.18.35:80

</code></pre>
<pre><code>
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 1053628ms
npm verb type system
npm verb stack FetchError: request to http://registry.npmjs.org/parallel-transform failed, reason: connect ETIMEDOUT 104.16.18.35:80
npm verb stack     at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
npm verb stack     at ClientRequest.emit (events.js:198:13)
npm verb stack     at Socket.socketErrorListener (_http_client.js:392:9)
npm verb stack     at Socket.emit (events.js:198:13)
npm verb stack     at emitErrorNT (internal/streams/destroy.js:91:8)
npm verb stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:63:19)
npm verb cwd /Users/chrisburd/Workspace/one
npm verb Darwin 19.0.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "@angular/cli" "-verbose"
npm verb node v10.16.3
npm verb npm  v6.9.0
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! network request to http://registry.npmjs.org/parallel-transform failed, reason: connect ETIMEDOUT 104.16.18.35:80
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm verb exit [ 1, true ]
npm timing npm Completed in 1054041ms
</code></pre>

## 🌍 Your Environment
this is what started the uninstall and reinstall process after upgrading to zsh ng command not found.
<pre><code>
zsh: command not found: ng
</code></pre>

**Anything else relevant?**
the switch to ZSH on the MacOS Terminal - but I don't believe the two are related.  Since there is a timeout coming from the repository this is more likely an issue with the end host where the package is located.  I am able to connect to other sites and can ping normally.  As well I can use my VPN service and have tried an alternative route to the package.  All end up in the same result.

**Comment by clydin** [comment]
This seems like a problem with node/npm and not with Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm support forum](https://npm.community), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by hooloom** [comment]
> This seems like a problem with node/npm and not with Angular CLI.
> 
> Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm support forum](https://npm.community), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

I clearly said I already did this - stop passing the buck.  I'm so tired of Google and it's lack of actually taking ownership of its issues.

**Comment by mgechev** [comment]
All the communication in the repositories in the Angular organization should follow our [code of conduct](https://github.com/angular/code-of-conduct). I'm locking the issue since it's too heated, lacks details to help us resolve a potential issue, and does not provide an opportunity for a constructive discussion.
