### ISSUE TITLE
Enum scaffolding filename is incorrect in index.ts

### ISSUE THREAD

**Issue by tzachov** [angular/angular-cli#1581]
When creating enum using ng g enum my-enum, the path in the relevant index.ts is incorrect.
The generated filename is "my-enum.enum.ts" but the export statement is missing the ".enum".

Current:
export * from './enums/my-enum';

Should be:
export * from './enums/my-enum**.enum**';

Windows 10
angular-cli: 1.0.0-beta.11-webpack
node: 6.3.0
os: win32 x64

**Comment by filipesilva** [comment]
This was fixed, in a way, in https://github.com/angular/angular-cli/pull/1658. We no longer have barrels.
