### ISSUE TITLE
Angular CLI 9.0.0-next.9 throws error : Unable to copy assets: EPERM: operation not permitted

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#15816]
# 🐞 Bug report
After upgrading to Angular CLI 9.0.0-next.9 `ng build` throws below error

`Unable to copy assets: EPERM: operation not permitted, copyfile 'D:\MyProject\ClientApp\src\assets\fonts' -> 'D:\MyProject\ClientApp\src\assets\fonts
`

Downgrading back to Angular CLI 9.0.0-next.8 fixes the issue, so it seems that the issue is with the `Angular CLI 9.0.0-next.9`

### Command (mark with an `x`)

```
- [x ] build
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular CLI 9.0.0-next.8

## 🔥 Exception or Error
<pre><code>
Unable to copy assets: EPERM: operation not permitted, copyfile 'D:\MyProject\ClientApp\src\assets\fonts' -> 'D:\MyProject\ClientApp\src\assets\fonts'

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.9
Node: 10.16.3
OS: win32 x64
Angular: 9.0.0-next.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.0-next.9
@angular-devkit/build-angular              0.900.0-next.9
@angular-devkit/build-optimizer            0.900.0-next.9
@angular-devkit/build-webpack              0.900.0-next.9
@angular-devkit/core                       9.0.0-next.8
@angular-devkit/schematics                 9.0.0-next.8
@angular/cdk                               9.0.0-next.0
@angular/cli                               9.0.0-next.9
@angular/fire                              5.2.1
@angular/material                          9.0.0-next.0
@angular/pwa                               0.900.0-next.8
@ngtools/webpack                           9.0.0-next.9
@nguniversal/module-map-ngfactory-loader   9.0.0-next.2
@schematics/angular                        9.0.0-next.8
@schematics/update                         0.900.0-next.9
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.41.0
</code></pre>

**Comment by gurezo** [comment]
I also encountered a similar error

```
Unable to copy assets: ENOTSUP: operation not supported on socket, copyfile '/Users/lifewood/work/portfolio/src/assets/imgaes' -> '/Users//lifewood/work/portfolio/dist/assets/imgaes'
```

**Comment by clydin** [comment]
Thank you for reporting the issue. A fix is currently pending in the referenced PR and will be in the next release.

Please be aware that this release is not yet stable and defects may be present.
The team thanks you for giving the next release a try and helping to provide a more robust final product.

**Comment by vgb1993** [comment]
I had the same problem, glad it's closed

**Comment by kolkov** [comment]
Still present in next.10 :(
https://github.com/angular/angular/issues/33122

**Comment by kolkov** [comment]
Sorry, `cli` have only `next.9` version at moment...

**Comment by gurezo** [comment]
one more information
Even after updating to 9.0.0.next.9 and returning to 9.0.0.next.8 and installing npm, 9.0.0.next.8 is not installed and 9.0.0.next.9 is installed. It was.

**Comment by kolkov** [comment]
@gurezo downgrade build-angular too.

**Comment by gurezo** [comment]
@kolkov 
did not resolve.
make issue #15829
