### ISSUE TITLE
Error missing dependence on ng build --prod

### ISSUE THREAD

**Issue by Toso82** [angular/angular-cli#15814]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I think YES

### Description

 A clear and concise description of the problem...

When use:

``` powershell
  ng build --prod 
```

## 🔬 Minimal Reproduction

It is difficult to reproduce.  Work well it is a big project. I think not pack correct jquery-ui with optimization.

This is my angular.json

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "forMca": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/forTest",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.json"
            ],
            "styles": [
              "./node_modules/jquery-ui/themes/base/all.css",
              
              "./node_modules/select2/select2.css",
              "src/MyTheme.scss",
              "src/styles.css"
              
            ],
            "scripts": [
              "./node_modules/jquery/dist/jquery.min.js",
              "./node_modules/jquery-ui/ui/widgets/datepicker.js",
              "./node_modules/jquery-ui/ui/i18n/datepicker-it.js",
              "./node_modules/select2/select2.js",
              "./node_modules/select2/select2_locale_it.js",
              
              "./node_modules/jquery-ui/ui/effect.js",
              "./node_modules/jquery-ui/ui/widget.js",
              "./node_modules/jquery-ui/ui/unique-id.js",
              "./node_modules/jquery-ui/ui/widgets/mouse.js",
              "./node_modules/jquery-ui/ui/widgets/slider.js",
              "./node_modules/jquery-ui/ui/widgets/button.js",
              "./node_modules/jquery-ui/ui/widgets/tabs.js",
              {
                "input": "node_modules/document-register-element/build/document-register-element.js"
              },
              {
                "input": "node_modules/document-register-element/build/document-register-element.js"
              },
              {
                "input": "node_modules/document-register-element/build/document-register-element.js"
              }
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "serviceWorker": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "forMca:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "forMca:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "forMca:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "styles.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.json"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "forMca-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "forMca:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "forTest",
  "cli": {
    "warnings": {
      "typescriptMismatch": true
    }
  }
}
```

## 🔥 Exception or Error
<pre><code>
VM57:1 Uncaught TypeError: Cannot read property 'locales' of undefined
    at <anonymous>:1:185436
    at <anonymous>:1:185986
    at _ (scripts.d5368eaf5dd883f643fe.js:1)
    at Function.globalEval (scripts.d5368eaf5dd883f643fe.js:1)
    at Object.dataFilter (scripts.d5368eaf5dd883f643fe.js:1)
    at scripts.d5368eaf5dd883f643fe.js:1
    at C (scripts.d5368eaf5dd883f643fe.js:1)
    at XMLHttpRequest.<anonymous> (scripts.d5368eaf5dd883f643fe.js:1)
    at XMLHttpRequest.P (polyfills.77b91ca388296e8772a5.js:1)
    at e.invokeTask (polyfills.77b91ca388296e8772a5.js:1)
(anonymous) @ VM57:1
(anonymous) @ VM57:1
_ @ scripts.d5368eaf5dd883f643fe.js:1
globalEval @ scripts.d5368eaf5dd883f643fe.js:1
dataFilter @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
C @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
P @ polyfills.77b91ca388296e8772a5.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
onInvokeTask @ main.1e19b8fc04c0111ea540.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
t.runTask @ polyfills.77b91ca388296e8772a5.js:1
t.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
b @ polyfills.77b91ca388296e8772a5.js:1
m @ polyfills.77b91ca388296e8772a5.js:1
(anonymous) @ polyfills.77b91ca388296e8772a5.js:1
I.i.<computed> @ polyfills.77b91ca388296e8772a5.js:1
send @ scripts.d5368eaf5dd883f643fe.js:1
ajax @ scripts.d5368eaf5dd883f643fe.js:1
w._evalUrl @ scripts.d5368eaf5dd883f643fe.js:1
Rt @ scripts.d5368eaf5dd883f643fe.js:1
append @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
U @ scripts.d5368eaf5dd883f643fe.js:1
html @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
onInvokeTask @ main.1e19b8fc04c0111ea540.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
t.runTask @ polyfills.77b91ca388296e8772a5.js:1
t.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
invoke @ polyfills.77b91ca388296e8772a5.js:1
n.args.<computed> @ polyfills.77b91ca388296e8772a5.js:1
load (async)
z @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
onScheduleTask @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleEventTask @ polyfills.77b91ca388296e8772a5.js:1
(anonymous) @ polyfills.77b91ca388296e8772a5.js:1
D.i.set @ polyfills.77b91ca388296e8772a5.js:1
send @ scripts.d5368eaf5dd883f643fe.js:1
ajax @ scripts.d5368eaf5dd883f643fe.js:1
w._evalUrl @ scripts.d5368eaf5dd883f643fe.js:1
Rt @ scripts.d5368eaf5dd883f643fe.js:1
append @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
U @ scripts.d5368eaf5dd883f643fe.js:1
html @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
onInvokeTask @ main.1e19b8fc04c0111ea540.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
t.runTask @ polyfills.77b91ca388296e8772a5.js:1
t.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
invoke @ polyfills.77b91ca388296e8772a5.js:1
n.args.<computed> @ polyfills.77b91ca388296e8772a5.js:1
setTimeout (async)
c @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
onScheduleTask @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleMacroTask @ polyfills.77b91ca388296e8772a5.js:1
v @ polyfills.77b91ca388296e8772a5.js:1
(anonymous) @ polyfills.77b91ca388296e8772a5.js:1
I.i.<computed> @ polyfills.77b91ca388296e8772a5.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
h @ scripts.d5368eaf5dd883f643fe.js:1
fireWith @ scripts.d5368eaf5dd883f643fe.js:1
C @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
P @ polyfills.77b91ca388296e8772a5.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
onInvokeTask @ main.1e19b8fc04c0111ea540.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
t.runTask @ polyfills.77b91ca388296e8772a5.js:1
t.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
b @ polyfills.77b91ca388296e8772a5.js:1
m @ polyfills.77b91ca388296e8772a5.js:1
load (async)
z @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
onScheduleTask @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleEventTask @ polyfills.77b91ca388296e8772a5.js:1
(anonymous) @ polyfills.77b91ca388296e8772a5.js:1
D.i.set @ polyfills.77b91ca388296e8772a5.js:1
send @ scripts.d5368eaf5dd883f643fe.js:1
ajax @ scripts.d5368eaf5dd883f643fe.js:1
load @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
_create @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
_createWidget @ scripts.d5368eaf5dd883f643fe.js:1
t.<computed>.<computed> @ scripts.d5368eaf5dd883f643fe.js:1
(anonymous) @ scripts.d5368eaf5dd883f643fe.js:1
each @ scripts.d5368eaf5dd883f643fe.js:1
each @ scripts.d5368eaf5dd883f643fe.js:1
t.fn.<computed> @ scripts.d5368eaf5dd883f643fe.js:1
l.addInfoWindow @ main.1e19b8fc04c0111ea540.js:1
l @ main.1e19b8fc04c0111ea540.js:1
t.ngAfterViewInit @ main.1e19b8fc04c0111ea540.js:1
ki @ main.1e19b8fc04c0111ea540.js:1
Ti @ main.1e19b8fc04c0111ea540.js:1
Ii @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
Na @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
ka @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
Na @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
ka @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
ka @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
Na @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
ka @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
Oa @ main.1e19b8fc04c0111ea540.js:1
ka @ main.1e19b8fc04c0111ea540.js:1
xa @ main.1e19b8fc04c0111ea540.js:1
t.detectChanges @ main.1e19b8fc04c0111ea540.js:1
t.tick @ main.1e19b8fc04c0111ea540.js:1
t._loadComponent @ main.1e19b8fc04c0111ea540.js:1
t.bootstrap @ main.1e19b8fc04c0111ea540.js:1
(anonymous) @ main.1e19b8fc04c0111ea540.js:1
t._moduleDoBootstrap @ main.1e19b8fc04c0111ea540.js:1
(anonymous) @ main.1e19b8fc04c0111ea540.js:1
e.invoke @ polyfills.77b91ca388296e8772a5.js:1
onInvoke @ main.1e19b8fc04c0111ea540.js:1
e.invoke @ polyfills.77b91ca388296e8772a5.js:1
t.run @ polyfills.77b91ca388296e8772a5.js:1
(anonymous) @ polyfills.77b91ca388296e8772a5.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
onInvokeTask @ main.1e19b8fc04c0111ea540.js:1
e.invokeTask @ polyfills.77b91ca388296e8772a5.js:1
t.runTask @ polyfills.77b91ca388296e8772a5.js:1
b @ polyfills.77b91ca388296e8772a5.js:1
Promise.then (async)
g @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
onScheduleTask @ polyfills.77b91ca388296e8772a5.js:1
e.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleTask @ polyfills.77b91ca388296e8772a5.js:1
t.scheduleMicroTask @ polyfills.77b91ca388296e8772a5.js:1
R @ polyfills.77b91ca388296e8772a5.js:1
e.then @ polyfills.77b91ca388296e8772a5.js:1
t.appInitializer @ main.1e19b8fc04c0111ea540.js:1
t.runInitializers @ main.1e19b8fc04c0111ea540.js:1
(anonymous) @ main.1e19b8fc04c0111ea540.js:1
(anonymous) @ main.1e19b8fc04c0111ea540.js:1
e.invoke @ polyfills.77b91ca388296e8772a5.js:1
onInvoke @ main.1e19b8fc04c0111ea540.js:1
e.invoke @ polyfills.77b91ca388296e8772a5.js:1
t.run @ polyfills.77b91ca388296e8772a5.js:1
t.run @ main.1e19b8fc04c0111ea540.js:1
t.bootstrapModuleFactory @ main.1e19b8fc04c0111ea540.js:1
zUnb @ main.1e19b8fc04c0111ea540.js:1
l @ runtime.1720a40670866f12654e.js:1
0 @ main.1e19b8fc04c0111ea540.js:1
l @ runtime.1720a40670866f12654e.js:1
t @ runtime.1720a40670866f12654e.js:1
r @ runtime.1720a40670866f12654e.js:1
(anonymous) @ main.1e19b8fc04c0111ea540.js:1
Show 72 more frames
main.1e19b8fc04c0111ea540.js:1 ERROR TypeError: $(...).tabs is not a function
    at l.addInfoWindow (main.1e19b8fc04c0111ea540.js:1)
    at new l (main.1e19b8fc04c0111ea540.js:1)
    at t.ngAfterViewInit (main.1e19b8fc04c0111ea540.js:1)
    at ki (main.1e19b8fc04c0111ea540.js:1)
    at Ti (main.1e19b8fc04c0111ea540.js:1)
    at Ii (main.1e19b8fc04c0111ea540.js:1)
    at xa (main.1e19b8fc04c0111ea540.js:1)
    at Oa (main.1e19b8fc04c0111ea540.js:1)
    at Na (main.1e19b8fc04c0111ea540.js:1)
    at xa (main.1e19b8fc04c0111ea540.js:1)

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.9
Node: 12.10.0
OS: win32 x64
Angular: 8.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.9
@angular-devkit/build-angular     0.803.9
@angular-devkit/build-optimizer   0.803.9
@angular-devkit/build-webpack     0.803.9
@angular-devkit/core              8.3.8
@angular-devkit/schematics        8.3.8
@angular/cdk                      8.2.3
@angular/cli                      8.3.9
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.2.3
@angular/pwa                      0.803.8
@ngtools/webpack                  8.3.9
@schematics/angular               8.3.8
@schematics/update                0.803.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Toso82** [comment]
@alan-agius4  I publish a small example. 

https://github.com/Toso82/NgServeErro

This is a bit complex to reproduce or isolate problem i have a angular project end inside a peace of program do in js use jquery and jquery-ui inside. I think there is something in optimizer.
But where is the bast way to use jquery an jquery-ui in Angular?

**Comment by alan-agius4** [comment]
@Toso82 kindly take a look at this documentation: https://angular.io/guide/using-libraries#adding-a-library-to-the-runtime-global-scope

**Comment by Toso82** [comment]
@alan-agius4  I read this and i correct without import but first time compile with ng serve do error the same in:


```powershell
PS E:\Angular\NgServeErro> ng build --prod

ERROR in src/app/app.component.ts:19:5 - error TS2592: Cannot find name '$'. Do you need to install type definitions for jQuery? Try `npm i @types/jquery` and then add `jquery` to the types field in your tsconfig.
19     $('#tabs').tabs();
       ~
```

**Comment by Toso82** [comment]
Hi @alan-agius4 sorry if i disturbe. There is any news of my problem?

**Comment by alan-agius4** [comment]
Hi @Toso82, the problem is that in your `types` setting in your `tsconfig.app.json` https://github.com/Toso82/NgServeErro/blob/09d52d20366ab5a91cdaa38a5187c080d3385c5f/tsconfig.app.json#L5 you have an empty array which disables automatic inclusion of `@types` packages.

See: https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types for more info.

So the installed `@types` packages are not being included and hence the typescript compiler is failing.

To fix the above you need to change:
```json
"types": []
```

to
```json
"types": ["jquery", "jqueryui"]
```

**Comment by Toso82** [comment]
Hi @alan-agius4 

Thanks for your explain with this correction now work. But why new project not start without 

`"types":[]`

so work in automatic base on your types? Or it is better to define manualy. 
Good to know, but not solve my old problem.

**Comment by alan-agius4** [comment]
> Thanks for your explain with this correction now work. But why new project not start without
"types":[]

That is because removing the above line will include all `@types` packages that are installed, ideally you only include what's needed as otherwise you might end up having conflicting type definitions. See: http://www.typescriptlang.org/docs/handbook/tsconfig-json.html#types-typeroots-and-types

I tried to reproduce the other error mentioned. However, I was unable to do so with the reproduction provided above.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
