### ISSUE TITLE
Angular CLI 9.0.0-next.9 install again

### ISSUE THREAD

**Issue by gurezo** [angular/angular-cli#15829]
Even after updating to 9.0.0.next.9 and returning to 9.0.0.next.8 and installing npm,   
9.0.0.next.8 is not installed and **`9.0.0.next.9 is installed`** . 
It was.

The reason is that even if the version of package.json is next.8, the version of @angular/cli will be installed with 9.0.0-next.9.

# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc
```

### Is this a regression?
package.json
```
    "@angular-devkit/build-angular": "~0.900.0-next.8",
    "@angular/cli": "^9.0.0-next.8",
```

#### The bug occurred in the following procedure
- npm uninstall -g @angular/cli
- npm install -g @angular/cli@9.0.0-next.9
- cd work/porfolio
- ng update @angular/cli@9.0.0-next.9 --force
- package.json
  ```
      "@angular-devkit/build-angular": "~0.900.0-next.8", ==> 0.900.0-next.9
      "@angular/cli": "^9.0.0-next.8", ==> 9.0.0-next.9
  ```
- npm run build
  - build error => https://github.com/angular/angular-cli/issues/15816#issuecomment-541168963
- cd ~
- npm uninstall -g @angular/cli
- npm cache clean --force
- npm cache verify
- npm install -g @angular/cli@9.0.0-next.8
- cd work/porfolio
- package.json manual edit
  ```
      "@angular-devkit/build-angular": "~0.900.0-next.9", ==> 0.900.0-next.8
      "@angular/cli": "^9.0.0-next.9", ==> 9.0.0-next.8
  ```
- rm -rf node_modules
- npm install
- npm run build
  - build error => https://github.com/angular/angular-cli/issues/15816#issuecomment-541168963
- checking project package.json
  <img width="890" alt="project-package" src="https://user-images.githubusercontent.com/7631567/66700749-3df19880-ed2f-11e9-90cf-5be4ced8cd75.png">

- checking node_modules/@angular-devkit/build-angular package.json
  <img width="1233" alt="devkit" src="https://user-images.githubusercontent.com/7631567/66700758-6c6f7380-ed2f-11e9-9865-d92324a9ff5d.png">

## 🔥 Exception or Error
https://github.com/angular/angular-cli/issues/15816#issuecomment-541168963
<pre><code>
➜  portfolio git:(master) ✗ npm i
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> fsevents@1.2.9 install /Users/lifewood/work/portfolio/node_modules/@angular/compiler-cli/node_modules/fsevents
> node install
　：
　：
　：
> @angular/cli@9.0.0-next.9 postinstall /Users/lifewood/work/portfolio/node_modules/@angular/cli
> node ./bin/postinstall/script.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @ngx-translate/core@11.0.1 requires a peer of @angular/core@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ngx-translate/http-loader@4.0.0 requires a peer of @angular/common@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.0 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-subresource-integrity@1.3.4 requires a peer of html-webpack-plugin@^2.21.0 || ~3 || >=4.0.0-alpha.2 <5 but none is installed. You must install peer dependencies yourself.

added 1517 packages from 1221 contributors and audited 17106 packages in 113.97s
found 0 vulnerabilities

➜  portfolio git:(master) ✗ npm run build

</code></pre>

## 🌍 Your Environment
<pre><code>
macOS 10.15 Catalina

### global Environment
Angular CLI: 9.0.0-next.8
Node: 10.16.3
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-next.8
@angular-devkit/core         9.0.0-next.8
@angular-devkit/schematics   9.0.0-next.8
@schematics/angular          9.0.0-next.8
@schematics/update           0.900.0-next.8
rxjs                         6.5.3

### project Environment
Angular CLI: 9.0.0-next.9
Node: 10.16.3
OS: darwin x64
Angular: 9.0.0-next.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.9
@angular-devkit/build-angular     0.900.0-next.9
@angular-devkit/build-optimizer   0.900.0-next.9
@angular-devkit/build-webpack     0.900.0-next.9
@angular-devkit/core              9.0.0-next.9
@angular-devkit/schematics        9.0.0-next.9
@angular/cdk                      9.0.0-next.0
@angular/cli                      9.0.0-next.9
@angular/material                 9.0.0-next.0
@ngtools/webpack                  9.0.0-next.9
@schematics/angular               9.0.0-next.9
@schematics/update                0.900.0-next.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0
</code></pre>

**Anything else relevant?**
https://github.com/angular/angular-cli/issues/15816
https://github.com/angular/angular-cli/pull/15817
https://github.com/angular/angular-cli/issues/15818

**Comment by clydin** [comment]
What is being described is how npm functions and is expected behavior.

If you want npm to always use a specific version of a package than you must specify only the exact version and not a range of versions.  Carets and tildes are range specifiers. For more information on semantic version specifiers please see https://docs.npmjs.com/misc/semver#tilde-ranges-123-12-1
