### ISSUE TITLE
Angular app giving error after ng-build --prod

### ISSUE THREAD

**Issue by SabirHossain** [angular/angular-cli#15821]
The app working fine without any error or warning but when I do ng build --prod, the production version giving me the following error in main.js, and I'm unable findout as chrome hanging on clicking the error line. I also tried with ```--build-optimization=false``` but it's same.
 
 
``` 
- [ 7.3.1] version 
```

`ERROR TypeError: "You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable."
    subscribeTo http://localhost:62111/main.a0b317b76904825e3413.js:1
    subscribeToResult http://localhost:62111/main.a0b317b76904825e3413.js:1
    call http://localhost:62111/main.a0b317b76904825e3413.js:1
    subscribe http://localhost:62111/main.a0b317b76904825e3413.js:1
    ngOnInit http://localhost:62111/main.a0b317b76904825e3413.js:1
    Kr http://localhost:62111/main.a0b317b76904825e3413.js:1
    Kr http://localhost:62111/main.a0b317b76904825e3413.js:1
    Kr http://localhost:62111/main.a0b317b76904825e3413.js:1
    xa http://localhost:62111/main.a0b317b76904825e3413.js:1
    tj http://localhost:62111/main.a0b317b76904825e3413.js:1
    updateDirectives http://localhost:62111/main.a0b317b76904825e3413.js:1
    Zr http://localhost:62111/main.a0b317b76904825e3413.js:1
    ia http://localhost:62111/main.a0b317b76904825e3413.js:1
    oa http://localhost:62111/main.a0b317b76904825e3413.js:1
    Zr http://localhost:62111/main.a0b317b76904825e3413.js:1
    ia http://localhost:62111/main.a0b317b76904825e3413.js:1
    oa http://localhost:62111/main.a0b317b76904825e3413.js:1
    Zr http://localhost:62111/main.a0b317b76904825e3413.js:1
    ia http://localhost:62111/main.a0b317b76904825e3413.js:1
    oa http://localhost:62111/main.a0b317b76904825e3413.js:1 `

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
