### ISSUE TITLE
Extending webpack config

### ISSUE THREAD

**Issue by iamyojimbo** [angular/angular-cli#1583]
# OS?

`OSX v 10.11.4`

# Versions

```
angular-cli: 1.0.0-beta.11-webpack
node: 6.2.2
os: darwin x64

```

# Repro steps. 

* App created with CLI (webpack).
* I am trying to use a package `lokijs`. I ran `npm install --save lokijs`.
* In my code, I then do: `var loki = require("lokijs");`
* I receive this error on `ng build`:
```
ERROR in ./~/fs/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/Users/savvas/code/tlbiolabs/node_modules/fs/index.js'
    at Error (native)
 @ ./~/lokijs/src/lokijs.js 1141:16-29
 @ ./src/app/shared/services/data-sync/pouch-loki-sync.ts
 @ ./src/app/shared/services/data-sync/index.ts
 @ ./src/app/shared/services/data.service.ts
 @ ./src/main.ts
 @ multi main
```
* This is a known issue with `lokijs` and `webpack`, reported [here](https://github.com/techfort/LokiJS/issues/449) and even with another package, `plugjs`, [here](https://github.com/pugjs/pug-loader/issues/8).
* The solution is to add `fs: 'empty'` to `webpack.config.js`
* I can't see any way to extend the internal config of the CLI. Is this possible?

# The log given by the failure

(as above)

**Comment by TheLarkInn** [comment]
I think that's more than doable. @iamyojimbo would you like to submit a PR?

**Comment by iamyojimbo** [comment]
@TheLarkInn I would love to. Can you point me in the right direction on how to get this done technically as I'm only 4 days into angular-cli at the moment?

We would have a `webpack.config.js` at the root, and literally any property you put in there would override whatever is in the defaults in CLI? So we would built the `defaults` webpack object, then pass it through something which blindly overrides with the custom config?

Too simplistic? Are there any other considerations?

**Comment by gelidus** [comment]
This could be a good inspiration. https://github.com/AngularClass/angular2-webpack-starter
