### ISSUE TITLE
HMR The missing documentation

### ISSUE THREAD

**Issue by hhsissi** [angular/angular-cli#15849]
Hi,

Today, the only docs available for using the Hot Module Replacement with Angular are:
1- https://github.com/PatrickJS/angular-hmr (Last commit from Aug 2018) (thanks to the guy for his great job by the way).
2- Really not helpful => 

ng serve --hmr
NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.
The project will still live reload when HMR is enabled,
but to take advantage of HMR additional application code is required'
(not included in an Angular CLI project by default).'
See https://webpack.js.org/guides/hot-module-replacement
for information on working with HMR for Webpack.
To disable this warning use "hmrWarning: false" under "serve" options in "angular.json".

The problem here is => Webpack documentation show you how to configure your webpack to use HMR, and not how to configure Angular to get HMR working.

If someone could provide a sample code for HMR integration with Angular, Please do so, I would really be grateful (and a bunch of people I believe).

**Comment by magnattic** [comment]
Try this guide: https://github.com/angular/angular-cli/wiki/stories-configure-hmr

**Comment by alan-agius4** [comment]
Closing as per above. 

In addition `angular-hmr` is not a first party package and thus I believe such documentation should be provided by the package author.

Thanks for using Angular.
