### ISSUE TITLE
npm i @angular-devkit/build-angular --> No matching version found for @angular-devkit/core@8.3.10

### ISSUE THREAD

**Issue by dilrajsingh** [angular/angular-cli#15858]
## Description

I cannot successfully install @angular-devkit/build-angular anymore please help.

## 🔬 Minimal Reproduction
Just run "**npm i @angular-devkit/build-angular**"
Same with if you run "**ng new my_project**"

<pre><code>
npm i @angular-devkit/build-angular

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/core@8.3.10
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular-devkit/build-angular'

</code></pre>

**Comment by alan-agius4** [comment]
Hi, probably you were trying to do an installation while it was being released. 

This shouldn’t be a problem anymore now.
