### ISSUE TITLE
"ng serve" doesn't react on changes in d.ts files.

### ISSUE THREAD

**Issue by VlasovSergey** [angular/angular-cli#15856]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I found a bug https://github.com/angular/angular-cli/issues/7638
According to [this](https://github.com/angular/angular-cli/issues/7638#issuecomment-344724819) looks like it worked in angular 5

### Description
"ng serve" doesn't react on changes in d.ts files.

### Precondition:
1. Clone repository: https://github.com/VlasovSergey/angular-ng-serbe-ignores-dts.git
2. run `npm install`
3. run `ng serve`
4. comment `func: () => void;` in file `src\typings.ts`
*Expected:*  'ng serve' runs build and shows an error because `module.ts` uses function func.
*Actual:* 'ng serve' do nothing.

5. re-run `ng serve` (it shows error).
6. make any change in main.ts but don't fix the error (`ng serve` rebuild project and show error correctly)
7. uncomment `func: () => void;` in file `src\typings.ts`

*Expected:* `ng serve` rebuilds the project and the error disappears.
*Actual:* 'ng serve' do nothing. Moreover, if I trigger `ng serve` again (by changing main.ts) the error will be still here.

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.9
Node: 10.15.1
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.9
@angular-devkit/build-angular     0.803.9
@angular-devkit/build-optimizer   0.803.9
@angular-devkit/build-webpack     0.803.9
@angular-devkit/core              8.3.9
@angular-devkit/schematics        8.3.9
@angular/cli                      8.3.9
@ngtools/webpack                  8.3.9
@schematics/angular               8.3.9
@schematics/update                0.803.9
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by filipesilva** [comment]
Just a note about this bug: it should be limited to global definitions. When importing the interface from the `.d.ts` file, rebuilds should still be triggered properly.
