### ISSUE TITLE
AppServerModuleNgFactory not exported for VE with version 9 approach

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#15851]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes

### Description
Currently in `ngtools` we rely on `isMainPath`, `getEntryModule` to run the `export_ngfactory` transformer, however in version 9 the main will be pointing to `server.ts` rather than `main.server.ts`. 

This causes the transformer to run on the wrong file in VE.

## 🔬 Minimal Reproduction

- npx i @angular/cli@9.0.0-next.9 new universal-test
- cd universal-test
- ng add @nguniversal/express-engine@9.0.0-next.5
- disable ivy
- in `server.ts` change `AppServerModule` to `AppServerModuleNgFactory` to use AOT as otherwise you will use the JIT version of the code.
-  npm run build:ssr

## 🔥 Exception or Error
<pre><code>
ERROR in server.ts:7:10 - error TS2305: Module '"C:/git/cli-repos/terser/src/main.server"' has no exported member 'AppServerModuleNgFactory'.

7 import { AppServerModuleNgFactory } from './src/main.server';
           ~~~~~~~~~~~~~~~~~~~~~~~~
</code></pre>


## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-next.9
Node: 12.10.0
OS: win32 x64
Angular: 9.0.0-next.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.9
@angular-devkit/build-angular     0.900.0-next.9
@angular-devkit/build-optimizer   0.900.0-next.9
@angular-devkit/build-webpack     0.900.0-next.9
@angular-devkit/core              9.0.0-next.9
@angular-devkit/schematics        9.0.0-next.9
@angular/cli                      9.0.0-next.9
@angular/platform-server          9.0.0-next.11
@ngtools/webpack                  9.0.0-next.9
@nguniversal/common               9.0.0-next.5
@nguniversal/express-engine       9.0.0-next.5
@schematics/angular               9.0.0-next.9
@schematics/update                0.900.0-next.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0
</code></pre>

**Anything else relevant?**
As a workaround users need to manually add the below export in `main.server.ts`

```ts
export { AppServerModuleNgFactory } from './app/app.server.module.ngfactory';
```

**Comment by vikerman** [comment]
Part of Ivy opt out story for ssr.

**Comment by vikerman** [comment]
For opting out let's ask the users to 

```ts
import { AppServerModuleNgFactory } from './app/app.server.module.ngfactory';
```

**Comment by alan-agius4** [comment]
Being addressed in https://github.com/angular/angular/pull/33616

**Comment by alan-agius4** [comment]
Docs PR merged.
