### ISSUE TITLE
ng serve warning: WARNING in Circular dependency detected

### ISSUE THREAD

**Issue by linwrui** [angular/angular-cli#15860]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
"@angular-devkit/build-angular": "~0.801.2",
"@angular/cli": "~8.1.2",

### Description

 
I upgrade angular with command 'ng update @angular/core @angular/cli',and the angular package all upgrade automatically.After upgrade success,I run command 'ng serve'.And the console log many wanings like ' WARNING in Circular dependency detected'.But angular.json only provide 'showCircularDependencies' on ng-build options.So how can I ignore the circular warning when I run 'ng serve'?
I think this is a bug cause it dosen't happened on angluar/cli v8.1.2.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

    "@angular/animations": "~8.2.11",
    "@angular/cdk": "~8.1.1",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/compiler-cli": "~8.2.11",
    "@angular/core": "~8.2.11",
    "@angular/flex-layout": "^8.0.0-beta.26",
    "@angular/forms": "~8.2.11",
    "@angular/platform-browser": "~8.2.11",
    "@angular/platform-browser-dynamic": "~8.2.11",
    "@angular/platform-server": "~8.2.11",
    "@angular/router": "~8.2.11",
    "@angular-builders/custom-webpack": "^8.1.0",
    "@angular-builders/dev-server": "~7.3.1",
    "@angular-builders/jest": "^8.0.4",
    "@angular-devkit/build-angular": "~0.803.10",
    "@angular/cli": "~8.3.10",
    "typescript": "~3.4.5",
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
In `serve` the `showCircularDependencies` setting value is inherit for `build` configuration. So if you have a circular dependency it is the correct behaviour that this is displayed during `serve`.

To display it you'd need to create either a separate configuration, or disable it for non `production` configuration.

**Comment by linwrui** [comment]
> In `serve` the `showCircularDependencies` setting value is inherit for `build` configuration. So if you have a circular dependency it is the correct behaviour that this is displayed during `serve`.
> 
> To display it you'd need to create either a separate configuration, or disable it for non `production` configuration.

Thanks, it resolved after I remove production configuration options.
Before:
`"serve": {
                    "builder": "@angular-builders/custom-webpack:dev-server",
                    "options": {
                        "browserTarget": "app:build",
                        "port": 8000
                    },
                    "configurations": {
                        "production": {
                            "browserTarget": "data-explorer-web:build:production"
                        }
                    }
                },`
After:
`"serve": {
                    "builder": "@angular-builders/custom-webpack:dev-server",
                    "options": {
                        "browserTarget": "app:build",
                        "port": 8000
                    }
                },`

**Comment by linwrui** [comment]
> In `serve` the `showCircularDependencies` setting value is inherit for `build` configuration. So if you have a circular dependency it is the correct behaviour that this is displayed during `serve`.
> 
> To display it you'd need to create either a separate configuration, or disable it for non `production` configuration.

I have set `showCircularDependencies : false` in build configuration.But it also warning on `ng serve`.So how can I resolve the problem?

**Comment by alan-agius4** [comment]
Hi @linwrui. I tried this and I am unable to replicate the bug reported above.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by linwrui** [comment]
> minimal repro

[https://github.com/linwrui/circularWarning](url)
And I find that it's happend because of 
![image](https://user-images.githubusercontent.com/22316156/67203840-b1d22600-f43e-11e9-80f9-b1cccb239a8b.png)
It's right with :
![image](https://user-images.githubusercontent.com/22316156/67203881-d29a7b80-f43e-11e9-9a8f-1cb302998ef9.png)

**Comment by alan-agius4** [comment]
Hi, In that case, I am closing the issue since `@angular-devkit/custom-webpack` is not an official and supported package by the Angular Tooling Team. 

Kindly file an issue with the author of the package.

Thanks.

**Comment by linwrui** [comment]
> Hi, In that case, I am closing the issue since `@angular-devkit/custom-webpack` is not an official and supported package by the Angular Tooling Team.
> 
> Kindly file an issue with the author of the package.
> 
> Thanks.

Thanks.But I want to use custom webpack configuration.How can I do with official package?
