### ISSUE TITLE
ng build - option to specify cache directory

### ISSUE THREAD

**Issue by okeydoky** [angular/angular-cli#15865]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
In our development environment setup, we have individual developer's node_modules link to project's node_modules which is controlled by architects who decides what packages should be used in the project.

However, when individual developers tried to build their own instance, we encounter this error:
`
[exec] Generating ES5 bundles for differential loading...

[exec] An unhandled exception occurred: EPERM: operation not permitted, lchown '....../node_modules/.cache/angular-build-dl/content-v2/sha512/d4/20'`

It appears during the build, ng will create some temporary files under node_modules/.cache and even perform chown operation on it. 

The build fails because individual developer does not have sufficient permission to operate on project's node_modules directory.

### Describe the solution you'd like
 
I wonder whether it's possible to have a build option that allow changing default cache directory. So we can set it to individual developer's own environment where they have sufficient permission.

**Comment by kylecordes** [comment]
@vikerman @alan-agius4  I encourage this to be changed, not only in an option, but always.

I think `node_modules` is semantically an input, not an output, to running anything other than NPM install/update/etc., so writing to `node_modules` should generally be forbidden.

(Incidentally I encountered this unexpected behavior while running a CLI build inside a sandboxfs inside Bazel.)

**Comment by DavidHofs** [comment]
For future reference: If you build under NFS this may be an issue (see e.g. [here](https://serverfault.com/questions/212178/chown-on-a-mounted-nfs-partition-gives-operation-not-permitted))
