### ISSUE TITLE
Resource files, where?

### ISSUE THREAD

**Issue by rajjejosefsson** [angular/angular-cli#1586]
> Please provide us with the following information:
> ---------------------------------------------------------------

**1. OS?**
OSX El Capitan

**2. Versions**

angular-cli: 1.0.0-beta.9
node: 6.3.0
os: darwin x64

**3. Repro steps.**

```
background:
          linear-gradient(
          rgba(0, 0, 0, 0.5), 
          rgba(0, 0, 0, 0.5)), url(../../resources/cinema-min-600.jpg);

```

* resources folder is currently inside the SRC
* have tried to use the public folder but same issue 

This happens when deploying to my github.

**4. The log given by the failure.** 

`Failed to load resource: the server responded with a status of 404 (Not Found)
`

**Comment by deebloo** [comment]
Put it in public. so if your put your images in ```public/resources/cinema-min-600.jpg``` you would access like this ```<img src="resources/cinema-min-600.jpg>"```

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1633 should allow you to do this.
