### ISSUE TITLE
Allow directTemplateLoading to be set from angular.json

### ISSUE THREAD

**Issue by reduckted** [angular/angular-cli#15861]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

The `AngularCompilerPlugin` allows templates to be [loaded directly](https://github.com/angular/angular-cli/blob/e8cdfa6020b8856498f9ea86b1fbbddb3f767975/packages/ngtools/webpack/src/interfaces.ts#L46), bypassing any loaders configured in the webpack config. The [default value](https://github.com/angular/angular-cli/blob/e8cdfa6020b8856498f9ea86b1fbbddb3f767975/packages/ngtools/webpack/src/compiler_host.ts#L48) of this option is `false`.

The Angular CLI creates an instance of the `AngularCompilerPlugin` and sets this option to `true`, with no way of overriding this behavior.
https://github.com/angular/angular-cli/blob/e8cdfa6020b8856498f9ea86b1fbbddb3f767975/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts#L94

Setting this to `true` made sense when there was no way to customize the webpack config. However, now that CLI Builders are [officially supported](https://blog.angular.io/introducing-cli-builders-d012d4489f1b), it will become more common for builders like [`@angular-builders/custom-webpack`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack) to be used to customize the webpack configuration. But with `directTemplateLoading` being hard-coded to `true`, there is no way to customize the webpack configuration to allow a loader to manipulate a component's template.

### Describe the solution you'd like

Let the `directTemplateLoading` option be set in the `angular.json` file. For example:

```json
"architect": {
  "build": {
    "builder": "@angular-builders/custom-webpack:browser",
    "options": {
      "directTemplateLoading": false,
      "customWebpackConfig": {
        "path": "./webpack.config.js"
      },
      "etc": "etc"
```

### Describe alternatives you've considered

This idea has been raised before in a couple of issues, but both were closed with workarounds or hacks. Since CLI Builders are now officially supported, I feel that a proper solution is required.

#### Use `template` and inline loaders

https://github.com/angular/angular-cli/issues/14855#issuecomment-510592634 suggests using `template` and specifying the loaders in the require statement instead of using `templateUrl`.

> Hi all, we had a chat around this, and we think that if you want to use webpack specific stuff you can use [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) or otherwise you can update the require statements to include the raw-loader import syntax ie: `require('!raw-loader!./path-to-template.html')` as suggested above.

Manually specifying the same loaders for _every_ component template is not maintainable.

#### Hack the webpack config

https://github.com/angular/angular-cli/issues/14534#issuecomment-496666971 states that a hack is required to set `directTemplateLoading`:

> Closing as the above method is a necessary step to augment an existing plugin within a webpack configuration.

The "above method" is to search through the plugins in the webpack config and find the `AngularCompilerPlugin`, get it's options, change the `directTemplateLoading` value to false, create a new instance of the plugin with the modified options and replace the original plugin in the webpack config. Very hacky.

#### Use `template` with loaders in the webpack config

Similar to the outcome of #14855, you can:

1. Install `@types/node`.
2. Add `"node"` to the `types` property of the tsconfig file.
3. Change `templateUrl: './foo.component.html` to `template: require('./foo.component.html')`

and the custom loaders specified in the webpack config will be used. _But_ this requires you to make changes to the way the component's template is specified by default, which is easy to forget to do. That's just asking for problems because forgetting to change `templateUrl` to `template` means it won't be passed through the custom loaders.

In addition to that, the Angular Language Service complains that _"Component 'FooComponent' must have a template or templateUrl"_.  

Given the choice between this and hacking the webpack config to recreate the `AngularCompilerPlugin`, I'd choose hacking the webpack config. 😁

**Comment by vikerman** [comment]
This should be an option in the custom webpack builder and not the CLI.

**Comment by clydin** [comment]
The `@ngtools/webpack` plugin is part of the default webpack configuration.  This allows any custom builder to modify the options of the plugin if using the webpack configuration generated by the official builder.  If a custom builder is generating a webpack configuration from scratch it would also have the opportunity to modify the plugin settings.  In either case, this would allow a custom builder to provide the suggested higher level boolean option to the user of the custom builder.

**Comment by reduckted** [comment]
> @vikerman This should be an option in the custom webpack builder and not the CLI.

That's a good point. If you're not using a custom builder, then setting it to false would only cause the build to fail. :+1:

> @clydin This allows any custom builder to modify the options of the plugin if using the webpack configuration generated by the official builder.

I'm having a hard time working out how that's currently possible.

In `angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js`, the `_createAotPlugin()` function sets `directTemplateLoading` to a hard-coded value of true. 

https://github.com/angular/angular-cli/blob/95776fed6713c3d911c876272cdb25c4e8fd3599/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts#L94-L99

It also adds the `options` that were passed to that function, so that's a potential way of overriding the value of true. _But_, the two callers of `_createAotPlugin()` both pass in hard-coded options (the options are the second parameter).

`getNonAotConfig`:
https://github.com/angular/angular-cli/blob/95776fed6713c3d911c876272cdb25c4e8fd3599/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts#L109

`getAotConfig`:
https://github.com/angular/angular-cli/blob/95776fed6713c3d911c876272cdb25c4e8fd3599/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/typescript.ts#L128

`_pluginOptionsOverrides()` is another potential place where the plugin's options could be customized, but it only changes `hostReplacementPaths` and `compilerOptions`.

I'm not too familiar with the codebase, so perhaps I've missed something. Would you be able to show an example of how to modify the options for `AngularCompilerPlugin` before the plugin is created?

**Comment by reduckted** [comment]
@clydin Are you able to provide an example of how to modify the options for `AngularCompilerPlugin` before the plugin is created?
