### ISSUE TITLE
"Machine-In-The-Middle" Vulnerability Caused by https-proxy-agent Dependency

### ISSUE THREAD

**Issue by JaxonWright** [angular/angular-cli#15878]
This was an NPM advisory that was [published earlier today](https://npmjs.com/advisories/1184). Running `npm audit fix` does not solve the problem. Seems like the fix is as simple as updating this dependency for angular-cli.

````bash
                       === npm audit security report ===                        
                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           


  High            Machine-In-The-Middle                                         

  Package         https-proxy-agent                                             

  Patched in      >=3.0.0                                                       

  Dependency of   @angular/cli [dev]                                            

  Path            @angular/cli > @schematics/update > pacote >                  
                  make-fetch-happen > https-proxy-agent                         

  More info       https://npmjs.com/advisories/1184                             
````
<details><summary>View More</summary>

`````bash 
 High            Machine-In-The-Middle                                         

  Package         https-proxy-agent                                             

  Patched in      >=3.0.0                                                       

  Dependency of   @angular/cli [dev]                                            

  Path            @angular/cli > pacote > make-fetch-happen >                   
                  https-proxy-agent                                             

  More info       https://npmjs.com/advisories/1184                             


  High            Machine-In-The-Middle                                         

  Package         https-proxy-agent                                             

  Patched in      >=3.0.0                                                       

  Dependency of   @angular/cli [dev]                                            

  Path            @angular/cli > @schematics/update > pacote >                  
                  npm-registry-fetch > make-fetch-happen > https-proxy-agent    

  More info       https://npmjs.com/advisories/1184                             


  High            Machine-In-The-Middle                                         

  Package         https-proxy-agent                                             

  Patched in      >=3.0.0                                                       

  Dependency of   @angular/cli [dev]                                            

  Path            @angular/cli > pacote > npm-registry-fetch >                  
                  make-fetch-happen > https-proxy-agent                         

  More info       https://npmjs.com/advisories/1184

**Comment by UrinStone** [comment]
Same here.  Happened after installing firebase-tools.

**Comment by fcilurzo** [comment]
So what I need to do exactly to fix this?

**Comment by stabback** [comment]
https://github.com/TooTallNate/node-https-proxy-agent/issues/84#issuecomment-543884972

**Comment by uloga** [comment]
AOT also stopped compiling, imports are broken. What a shit show! Undependable, moving on!

**Comment by uloga** [comment]
Permanent workaround STOP USING NODE JS. Move to go or Dart! I am!

**Comment by alan-agius4** [comment]
Related issue: https://github.com/npm/make-fetch-happen/issues/5 and fix: https://github.com/npm/make-fetch-happen/pull/6 from upstream package.

**Comment by nikhilkapoorephesoft** [comment]
When can we expect a permanent fix on this?

**Comment by alan-agius4** [comment]
@nikhilkapoorephesoft this is currently marked as `blocked` as we are waiting on an upstream fix https://github.com/npm/make-fetch-happen/pull/6

**Comment by Yorer** [comment]
Thanks stabback your temporary solution resolved my temporary problem

**Comment by Yorer** [comment]
I've tried stabback's workaround, it seemed like working, but I've got back the same issue.

**Comment by shaozi** [comment]
Does this vulnerability impact production build? Seems only dev?

**Comment by Eonasdan** [comment]
version 2.2.3 was release with the 3.0 patch for this per issue 84

**Comment by trotyl** [comment]
> Does this vulnerability impact production build? Seems only dev?

Technically speaking there doesn't seem to be real vulnerability impact, but only developer experience issue caused by the warning. `pacote` is used by `ng add` and `ng update` to retrieve latest package metadata info for checking compatibility, equivalent to some calls like http://unpkg.com/@angular/core/package.json, I don't think intercepting that could cause some security issue, except for letting others know you're using Angular.

**Comment by Lagombi** [comment]
To anyone as clueless as me, `npm audit fix` now resolves this issue.

**Comment by clydin** [comment]
This can now be fixed with an update to the package in question to 2.2.3 or via an `npm audit fix`.

**Comment by danger89** [comment]
Thank god.

**Comment by danger89** [comment]
Uhm actually I still get after I run `npm audit fix`: 
```
fixed 0 of 21 vulnerabilities in 29087 scanned packages
  21 vulnerabilities required manual review and could not be updated
```

**Comment by clydin** [comment]
That appears to be an npm issue.  The dependency within `make-fetch-happen` allows for the use of 2.2.3: https://github.com/npm/make-fetch-happen/blob/052b5b7c36116f01de1aca080acd3a592d14acfa/package.json#L40

If npm is not cooperating, there is also the option to remove both the node modules folder and the lock file and install again.

**Comment by danger89** [comment]
@clydin I tried removing the lock file and node_modules directory. I don't get npm to install the latest version, still causing issues with npm audit.

**Comment by homestar9** [comment]
@danger89 Were you able to get `npm audit fix` to work? I also am having a similar issue even after removing the `package-lock.json` and purging `node_modules`.

**Comment by danger89** [comment]
No I'm not! Than we are facing the same problem... :(

**Comment by Jaked222** [comment]
Same 21 vulnerabilities in my React app. Are there any other threads tracking this issue? Seems like npm won't update the latest version of https-proxy-agent. I am able to repro after deleting node_modules and package-lock.json, and running npm install -> npm audit fix (vulnerabilities are not resolved) -> npm audit

**Comment by w5922xd** [comment]
This is the only thread I've seen. 

Same issue for me. 21 vulnerabilities requiring manual review. No clear way to resolve the problem.

**Comment by homestar9** [comment]
This might be random, but do you have "npm" listed as a dependency in your package.json file? 
Example: `"npm": "^6.12.0"`

Try removing it, delete your `node_modules` folder, and then type `npm install`.  Does that work?
I'm not sure why "npm" was in my list of dependencies, but removing it fixed the problem for me.

**Comment by w5922xd** [comment]
@homestar9 I was looking at that yesterday trying to figure out why I had that same version `"npm": "^6.12.0"`. Followed your suggestion - deleted `node_modules` and ran `npm install`. No issues with security vulnerabilities now. 

Thanks for your help!

**Comment by Jaked222** [comment]
Yep, this solved it for me too. 

Not only is including npm as a dependency unnecessary, it probably bloats the package size and (i believe?) prevents the included npm package from updating its dependencies to major versions (with possible breaking changes)

Thanks @homestar9

**Comment by JaxonWright** [comment]
I see no reason why you would ever want to include npm in your package. I'm kind of surprised that npm does not warn you about that.

**Comment by danger89** [comment]
> Try removing npm from the dependency list, delete your `node_modules` folder, and then type `npm install`. Does that work?
> I'm not sure why "npm" was in my list of dependencies, but removing it fixed the problem for me.

Yep that worked. I have no idea why this actually solved the problem. Since that means that there IS a security problem within npm package itself. Correct me if I'm wrong.

**Comment by shim-sao** [comment]
Here is my solution with `npm`:

1 - Remove `npm` from `dependencies` or `devDependencies`

2- Add it to the `engines`, its place is there.
For example:
```json
"engines": {
    "node": ">=10.0.0",
    "npm": ">=6.0.0"
  }
```
3 - Run `npm prune` to clean up  the modules of the project
```sh
removed 430 packages and audited 749 packages in 14.787s
found 0 vulnerabilities
```
