### ISSUE TITLE
Could not require 'angular-cli-build.js - clean setup

### ISSUE THREAD

**Issue by eikooc** [angular/angular-cli#1588]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

  Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

  ```cmd
$ ng --version
(node:15292) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.10
node: 6.2.2
os: win32 x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

  1. `ng new app`
  2. `cd app`
  3. `ng serve`

4. The log given by the failure. Normally this include a stack trace and some
   more information.

  ```
$ ng serve
(node:16180) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

Running without elevated rights. Running Ember CLI "as Administrator" increases performance significantly.
See ember-cli.com/user-guide/#windows for details.

Could not require 'angular-cli-build.js': Cannot find module 'angular-cli/lib/broccoli/angular2-app'
Error: Could not require 'angular-cli-build.js': Cannot find module 'angular-cli/lib/broccoli/angular2-app'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jamie\Documents\Gitlab\flyvesteder-webapp\angular-cli-build.js:7:19)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

5. Mention any other details that might be useful.

When I switch to opening a prompt with _administrator_ rights almost the same error is displayed. Just without the _Ember CLI_ note

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by lucacox** [comment]
see issue #1600

**Comment by filipesilva** [comment]
@eikooc are you trying to use the webpack version?

**Comment by eikooc** [comment]
I don't think so. Did a regular `npm install -g angular-cli`

**Comment by filipesilva** [comment]
Hm... what is your NPM version?

**Comment by eikooc** [comment]
3.10.3

**Comment by filipesilva** [comment]
Odd. It kinda seems like a bad install. Can you reinstall the global and local angular-cli?

**Comment by eikooc** [comment]
Sorry I don't have time as of now. You can close it if there is no need for the issue

**Comment by filipesilva** [comment]
Roger, closing.
