### ISSUE TITLE
Unable to create Angular 8 project

### ISSUE THREAD

**Issue by REVANTHMUPPANA** [angular/angular-cli#15882]
Hi all, I am unable to create angular project, since it failed to load chokidar package. can someone please suggest a solution to proceed further 

C:\Users\Revanth Manu>ng new package
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE package/angular.json (3601 bytes)
CREATE package/package.json (1293 bytes)
CREATE package/README.md (1025 bytes)
CREATE package/tsconfig.json (543 bytes)
CREATE package/tslint.json (1953 bytes)
CREATE package/.editorconfig (246 bytes)
CREATE package/.gitignore (631 bytes)
CREATE package/browserslist (429 bytes)
CREATE package/karma.conf.js (1019 bytes)
CREATE package/tsconfig.app.json (270 bytes)
CREATE package/tsconfig.spec.json (270 bytes)
CREATE package/src/favicon.ico (948 bytes)
CREATE package/src/index.html (293 bytes)
CREATE package/src/main.ts (372 bytes)
CREATE package/src/polyfills.ts (2838 bytes)
CREATE package/src/styles.css (80 bytes)
CREATE package/src/test.ts (642 bytes)
CREATE package/src/assets/.gitkeep (0 bytes)
CREATE package/src/environments/environment.prod.ts (51 bytes)
CREATE package/src/environments/environment.ts (662 bytes)
CREATE package/src/app/app.module.ts (314 bytes)
CREATE package/src/app/app.component.html (25498 bytes)
CREATE package/src/app/app.component.spec.ts (984 bytes)
CREATE package/src/app/app.component.ts (211 bytes)
CREATE package/src/app/app.component.css (0 bytes)
CREATE package/e2e/protractor.conf.js (808 bytes)
CREATE package/e2e/tsconfig.json (214 bytes)
CREATE package/e2e/src/app.e2e-spec.ts (640 bytes)
CREATE package/e2e/src/app.po.ts (262 bytes)
[    ..............] - fetchMetadata: sill resolveWithNewModule chokidar@2.1.8 checking installable status

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
