### ISSUE TITLE
"Can't resolve all parameters for" in @angular-devkit/build-angular 0.803.1+ for extended components

### ISSUE THREAD

**Issue by evgeniyefimov** [angular/angular-cli#15892]
# 🐞 Bug report

### Command (mark with an `x`)

Error occurs at runtime (no problems reported from the compiler).
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 0.803.0

### Description

 A clear and concise description of the problem...
After upgrade to @angular-devkit/build-angular: 0.803.12 from 0.802.2 "Can't resolve all parameters for" exceptions in runtime are happened. Exceptions are related to assigned constructors from base to derived classes, see code below. Also this exception is described in the anuglar repo [https://github.com/angular/angular/issues/24414#issuecomment-535451121](https://github.com/angular/angular/issues/24414#issuecomment-535451121)

## 🔬 Minimal Reproduction

We have an abstract base class which looks like that:
```
export abstract class CommunicationFormComponent {
  constructor(
    private readonly changeDetectorRef: ChangeDetectorRef,
  ) { }
}
```

From this class the following class is derived:
```
@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{
    multi: true,
    provide: CommunicationFormComponent,
    useExisting: forwardRef(() => PhoneFormComponent),
  }],
  selector: "tt-phone-form",
  styleUrls: ["./communication-form.component.scss"],
  templateUrl: "./communication-form.component.html",
  viewProviders: [
    {
      provide: ControlContainer,
      useExisting: FormGroupDirective,
    },
  ],
})
export class PhoneFormComponent extends CommunicationFormComponent { }
```

If add constructor to class with @Component decorator, it works fine.

## 🔥 Exception or Error
<pre><code>

compiler.js:2175 Uncaught Error: Can't resolve all parameters for PhoneFormComponent: (?).
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.12
Node: 12.4.0
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.12
@angular-devkit/build-angular     0.803.1
@angular-devkit/build-optimizer   0.803.1
@angular-devkit/build-webpack     0.803.1
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.3.12
@angular/cdk                      8.2.3
@angular/cli                      8.3.12
@angular/material                 8.2.3
@ngtools/webpack                  8.3.1
@schematics/angular               8.2.2
@schematics/update                0.803.12
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This is related to this fix https://github.com/angular/angular-cli/issues/15404

In a nutshell, undecorated classes  will not have DI available as they will be treated as plain classes.

With Ivy, bases classes for Components and Directives will also need to be decorated and such fixes will be applied automatically using a migration script.

To fix this, you can add a decorator to the base class.
from 
```ts
export abstract class CommunicationFormComponent {
```

to 
```ts
@Directive()
export abstract class CommunicationFormComponent {
```

**Comment by alan-agius4** [comment]
Closing as the above should fix the issue encountered. If the problem persists please create a new issue.

Thanks
