### ISSUE TITLE
Parse tsconfig error

### ISSUE THREAD

**Issue by murac** [angular/angular-cli#1589]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack
node: 6.3.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

this is a clean install of angular-cli@webpack. followed the instructions and installed locally after "ng new [name]" then opened up webstorm and find the error

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Error:Error: Parse tsconfig error [{"messageText":"Unknown compiler option 'lib'.","category":1,"code":5023},{"messageText":"Unknown compiler option 'typeRoots'.","category":1,"code":5023},{"messageText":"Unknown compiler option 'types'.","category":1,"code":5023}]

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by monojack** [comment]
You don't have typescript 2.0.0 installed.

**Comment by murac** [comment]
I ran npm i typescript@2.0.0 -g and also reran npm install (because 2.0.0 is in package.json) I went into settings and set the compiler to the version in my local node_modules/typescript/lib and webstorm is happy now

**Comment by QCCS** [comment]
tsc -v
Version 2.1.5;

Error:Cannot start compiler process:  Error: Parse tsconfig error [{"messageText":"Unknown compiler option 'lib'.","category":1,"code":5023}]
