### ISSUE TITLE
How to compare two Mhtml files

### ISSUE THREAD

**Issue by vairamuthuR** [angular/angular-cli#15891]
Hi Team,

How to read mhtml file in e2e testing using protractor (angular 7) and 

 how to compare two mhtml files

Regards,
Vairamuthu R

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
