### ISSUE TITLE
Add angular library to project

### ISSUE THREAD

**Issue by LunicLynx** [angular/angular-cli#1590]
1. OS
Windows 10

2. Versions. 
angular-cli: local (v1.0.0-beta.11-webpack)
node: 4.4.7
os: win32 x64

3. Repro steps
created a Library using https://github.com/jvandemo/generator-angular2-library
updated that library to rc4
npm link-ed that library to an newly create project using (ng new)

Everything works except that the source for angular2 is included twice in main.bundle.js which results in failing instanceof checks -> not able to use parts (directives, components, pipes) of the library.

I have absolutly no idea how to fix that. My final conclusion is that angular-cli is nice for demos but not for primetime use. especially since it changed from one technology to another before a stable release. Please don't see this as an offense, i was stocked about angular-cli. But to this moment i invested some like 3 days just to figure out basic stuff like referencing a library or creating one for that matter. Creating a library seems almost impossible now with webpack and previous to webpack typings where not emitted in the root.

Maybe i overlooked something, or maybe my expectations of, what the angular-cli should be, a wrong, anyway. Please let me know.

**Comment by hansl** [comment]
Hi,

It seems that when you (e.g.) `import { ... } from '@angular/core` **from the library** in your library you're not using the same `node_module/@angular/core` files than the ones in your application. This is not the fault of webpack or the CLI; it sees both imports as importing different libraries. Try installing the package instead of linking it, and make sure there's only 1 `@angular/*` in your `node_modules`.

Hope this helps.

**Comment by hansl** [comment]
Also make sure they're the same files' content. If you keep the old angular around you might have 2 copies of the library in your node modules. If your files are the same content they'd be extracted to be the same library. Webpack is smart enough to see that.

**Comment by TheLarkInn** [comment]
Also what format is the library that you are importing. CommonJs, UMD?

**Comment by LunicLynx** [comment]
@hansl i updated the package.json of both projects to use the same version. Did "npm install" afterwards on both. Am I missing something?
Also does that mean "npm link" is not supported? e.g. If i want to keep the lib private i have to use my own local npm repository (sinopia for example)?

@TheLarkInn Both projects are commonJs, but i'm not sure how much that matters with webpack in the loop.
