### ISSUE TITLE
Support for Closure Compiler in Angular CLI

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#15901]
# 🚀 Feature request
This is based on the issue https://github.com/angular/angular-cli/issues/2981

Here's a request to please add support for closure compiler in Angular CLI. 

### Command (mark with an `x`)

```
- [x ] build
```

### Description
Since the bundles produced by Angular compiler are compatible with Closure compiler, therefore I believe it would be great if we could have the ability to compile our Angular applications using Closure compiler in Angular CLI.

### Describe the solution you'd like
Some flag in `angular.json` file that could allow us to use Closure compiler with `ng build` command.

### Describe alternatives you've considered
Though I haven't tried it, but below post shows how this can be achieved using angular cli:

https://dev.to/steveblue/build-angular-like-an-architect-part-1-3ph2

What I am suggesting is ability to compile Angular applications using Closure Compiler with minimum efforts using Angular CLI.

**Comment by matthewjh** [comment]
hi @alan-agius4. just wondering whether this is on the roadmap in any form?

**Comment by alan-agius4** [comment]
Let's keep tracking this as part of https://github.com/angular/angular/issues/37234 since the NPM packages of the Angular framework no longer support Closure Compiler ADVANCED_OPTIMIZATIONS.
