### ISSUE TITLE
main-content-tab.component.html 1:0 Module parse failed: Unexpected token (1:0) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file

### ISSUE THREAD

**Issue by Kopleman** [angular/angular-cli#15908]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Description

I've updated my Angular 7 app to Angular 8. It used the old Angular way dynamic imports.
i've ran ng update @angular/cli @angular/core, everything was updated properly and it was using the new standard for dynamic imports, but app cannot now be opened. 

## 🔬 Minimal Reproduction
Updated to Angular 8 from 7.1.

## 🔥 Exception or Error
<pre><code>

WARNING in ./src/app/core/main-content/tab/main-content-tab.component.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.12
Node: 12.13.0
OS: linux x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.12
@angular-devkit/build-angular     0.803.12
@angular-devkit/build-optimizer   0.803.12
@angular-devkit/build-webpack     0.803.12
@angular-devkit/core              8.3.12
@angular-devkit/schematics        8.3.12
@angular/cdk                      7.3.7
@angular/cli                      8.3.12
@angular/material                 7.3.7
@ngtools/webpack                  8.3.12
@schematics/angular               8.3.12
@schematics/update                0.803.12
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by alan-agius4** [comment]
I remember we had this issue in the past, it was related to module hoisting.

Can you try to do the following;

```
rm -rf node_modules
rm -f package-lock.json
npm i
