### ISSUE TITLE
Angular Library produced NPM package that offers imports from public-api and lib

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [angular/angular-cli#15936]
# 🐞 bug report

### Description
After creating a new Angular library using the cli, and adding one exported class within the lib folder, which public-api.ts file exports, consuming applications are able to reference public-apit.ts as well as the lib folder as import locations.

![image](https://user-images.githubusercontent.com/41204890/67415795-917ca580-f5bd-11e9-8998-e36e8bb18756.png)

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 7.3.9
Node: 8.11.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-ng-packagr   0.13.9
@angular-devkit/build-optimizer    0.13.9
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.9
@angular/cli                       7.3.9
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.9
@schematics/update                 0.13.9
ng-packagr                         4.7.1
rxjs                               6.3.3
typescript                         3.2.4
webpack                            4.29.0<code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, this should be be fixed by https://github.com/angular/angular-cli/pull/1634

For existing projects, you can remove the wildcard path mapping from your workspace tsconfig.

Example from:
```json
"foo": [
  "dist/foo"
],
"foo/*": [
  "dist/foo/*"
]
```

to 

```json
"foo": [
  "dist/foo"
],
```
