### ISSUE TITLE
Retry chunk load-plugin

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#15947]
# 🚀 Feature request

It would be great to add support for module re-requests.
https://github.com/mattlewis92/webpack-retry-chunk-load-plugin

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Hi @splincode, 

This is currently not in scope of the Angular CLI. 

If you wish to include this plugin you can do so by using a custom builder that extends the Angular CLI build pipeline such as `ngx-build-plus`.

Thanks.
