### ISSUE TITLE
Asset hashing is not handled correctly in Universal

### ISSUE THREAD

**Issue by drdreo** [angular/angular-cli#15953]
# Bug Report

#### What is the expected behavior?
When using output-hashing universal gets the information of the assets and can use those from the client to prevent loading the same asset twice.

#### What is the current behavior?
When using output-hashing it tries to access the image from the served apps folder without hashes. Therefore, it can't load the image when serving the server version. Only when the client app takes over, the images are rendered.

#### What modules are related to this issue?
```
- [x] common
- [x] express-engine
```

#### Minimal reproduction with instructions:
https://github.com/drdreo/ng-universal-hashing-demo

#### What is the use-case or motivation for changing an existing behavior?
This might has to do something with the universal server setup which could be more detailed for such use-cases where you have a folder structure like.
```
dist
    -app
          -en
               -assets
          -fr
               -assets
    -server
```

#### Environment:
**@nguniversal versions**
 "@nguniversal/common": "^8.1.1",
    "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^8.1.1",
```
Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.14
@angular-devkit/build-angular              0.803.14
@angular-devkit/build-optimizer            0.803.14
@angular-devkit/build-webpack              0.803.14
@angular-devkit/core                       8.3.14
@angular-devkit/schematics                 8.3.14
@angular/cli                               8.3.14
@ngtools/webpack                           8.3.14
@nguniversal/common                        8.1.1
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.14
@schematics/update                         0.803.14
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.39.2
```

#### Is there anything else we should know?

It only affects assets via css like: fonts or background images etc.

I have 3 locale apps with different output hashing settings for testing purpose:
- fr : "outputHashing": "all"
- en: "outputHashing": "bundles"
- it: "outputHashing": "none"

en & it apps can handle the background-image because the server app requests the image without a hash. But the fr version can not render the image and requests the image twice. One not hashed & one hashed as seen in the video. The sun.jpg should be the background.
![video](https://i.imgur.com/qcffB2q.gif)

**Comment by alan-agius4** [comment]
In case your client bundles use outputHashing you should set `outputHashing` to `media` option to the the server builder.

**Comment by drdreo** [comment]
Oh well, that fixed it. Worth an entry in the documentation i guess.

**Comment by alan-agius4** [comment]
Strictly speaking it shouldn't be included in the server output, as the server should re-use the browser assets.

Related issue: https://github.com/angular/angular-cli/issues/12878
