### ISSUE TITLE
Module not found: Error: Can't resolve 'd3' in '/my-proj/node_modules/my-lib/fesm5'

### ISSUE THREAD

**Issue by JosephSKh** [angular/angular-cli#15958]
# 🐞 bug report

### Affected Package

 None

### Is this a regression?

 No

### Description

 I'm creating an Angular library by using `ng generate library my-lib`, this library uses d3 to draw some charts, when I npm install the library to my main project, it gives me..
`Module not found: Error: Can't resolve 'd3' in '/my-proj/node_modules/my-lib/fesm5'`
I'm also using `"preserveSymlinks": true` in my `build` options in `angular.json` ,.. so for some reason `d3` is not shipped with my library and my main project can't resolve `d3`

## 🔬 Minimal Reproduction

 I will update this

## 🔥 Exception or Error
<pre><code>

Module not found: Error: Can't resolve 'd3' in '/my-proj/node_modules/my-lib/fesm5'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular-devkit/build-ng-packagr": "~0.10.0",
    "@angular/cli": "~7.0.6",
    "@angular/compiler-cli": "~7.0.0",
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @JosephSKh, it looks like the problem that you are describing is related to the CLI and/or configuration of the project, so I've transferred this ticket to Angular CLI repository. Thank you.

**Comment by alan-agius4** [comment]
Hi @JosephSKh, most likely your are not adding d3 as a dependency in your application. Typically libraries should not contain direct dependencies. peerDependencies should be preferred. 

See the following for more information: https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md

Closing as this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
