### ISSUE TITLE
[schematics] use objects with file names

### ISSUE THREAD

**Issue by xxyyzz2050** [angular/angular-cli#15959]
example:

```
apply(url("./files"),[
  template(options, name: options.name)),  
 move("/app")
]
)
```

files/__options.name__ //will not work

files/__name__ //will work

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
