### ISSUE TITLE
devserver changeOrigin does not work when I set --host flag

### ISSUE THREAD

**Issue by kooritea** [angular/angular-cli#15967]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

i don't  know,
I only used 8.3.6

### Description

 A clear and concise description of the problem...
devserver changeOrigin is not work when I set --host flag

## 🔬 Minimal Reproduction
```javascript
// proxy.conf.js
module.exports = {
  "/": {
    "target": "https://api.example.com/",
    "changeOrigin": true,
    "secure": false,
    bypass: function (req, res, proxyOptions) {
      // do filter
    }
  }
}
```
```bash
ng serve --host 192.168.1.233 --open
```
but the http header origin is not change,I can find the origin is "http://192.168.1.233" on my remote api server

```bash
ng serve --open
```
all is well

**Comment by alan-agius4** [comment]
Hi, is this still reproducible using `@angular-devkit/build-angular` version `0.803.15`?

**Comment by kooritea** [comment]
> Hi, is this still reproducible using `@angular-devkit/build-angular` version `0.803.15`?

yes,just now I rm my node_modules and install "@angular-devkit/build-angular": "~0.803.15" again
```json
"devDependencies": {
    "@angular-devkit/build-angular": "~0.803.15",
}
```
but the problem remains.

**Comment by alan-agius4** [comment]
Hi @kooritea, 

I had a look at this and it is working as expected.

`changeOrigin` doesn't effect the value of the `Origin` header, but rather the `host` header.

From https://github.com/http-party/node-http-proxy/blob/d05624167ce75e860770c13afeacec2ce0f67add/README.md
> changeOrigin: true/false, Default: false - changes the origin of the host header to the target URL
