### ISSUE TITLE
ng build --prod differential loading scripts.xxx.js overwrite one another

### ISSUE THREAD

**Issue by dgoudie** [angular/angular-cli#15969]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

I'm not sure

### Description

When running ng build --prod on an app with differential loading enabled, and an item exists inside angular.json > projects > your_project > architect > build > options > scripts, the scripts.xxx.js transpiled file is being created twice during the build process, but with the same file name, causing which ever one was compiled first to be overwritten.

I am not sure what causes es5 build or es2015 build to be done first, but I have seen it occur in both orders. In each case, whichever one is _last_ will influence the final scripts.xxx.js file. As seen here, you can notice  the file names are the same. ->

![image](https://user-images.githubusercontent.com/34222208/67775703-4df6c100-fa2d-11e9-9f28-441a9b49c473.png)

Upon close inspection, during the build process, I can verify that, in the case pictured above, the first script generated _was_ indeed transpiled to es2015, and the second script was transpiled to es5. My verification of this ->

The first build, which is deleted as soon as the second one completes -> 

![image](https://user-images.githubusercontent.com/34222208/67776218-0886c380-fa2e-11e9-8cdb-4e1c354cf547.png)

The second build, the one that is present at the end of the build command ->

![image](https://user-images.githubusercontent.com/34222208/67776020-b9d92980-fa2d-11e9-9943-bd029cde2ad6.png)

## 🔬 Minimal Reproduction

1. ng new project
2. (for example) npm install tiff.js
3. add "./node_modules/tiff.js/tiff.min.js" to scripts: [] in build in angular.json
4. ng build --prod
5. observe the script.xxx.js file in dist

## 🔥 Exception or Error
<pre><code>

n/a
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.1.3
Node: 12.3.1
OS: win32 x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Numerous defects and performance improvements have been incorporated into the 8.x version of the CLI since 8.1.3.  Can you please try updating to the latest 8.x version (currently 8.3.15).

**Comment by dgoudie** [comment]
![image](https://user-images.githubusercontent.com/34222208/67780622-5acae300-fa34-11e9-81b1-c18ea915341d.png)

It appears that only one file was built this time, and it is an es5 file. Considering this is what I would expect (this will allow for IE to understand it), this can be closed. Thanks for your help.
