### ISSUE TITLE
ng serve: no cookies send to https server (chrome 78)

### ISSUE THREAD

**Issue by runner78** [angular/angular-cli#15970]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Its may be a problem of google chrome, but if that is normal behavior for chrome now, it would be a problem.

After update to google chrome to 78, my project no longer send cookies from localhost to my website with https. iI have also used ng serve with ssl command. But it works with Firefox 70.

**Comment by runner78** [comment]
Angular CLI: 8.3.15
Node: 10.16.0
OS: darwin x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.15
@angular-devkit/build-angular     0.803.15
@angular-devkit/build-optimizer   0.803.15
@angular-devkit/build-webpack     0.803.15
@angular-devkit/core              8.3.15
@angular-devkit/schematics        8.3.15
@angular/cdk                      8.2.3
@angular/cli                      8.3.15
@angular/material                 8.2.3
@ngtools/webpack                  8.3.15
@schematics/angular               8.3.15
@schematics/update                0.803.15
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

**Comment by alan-agius4** [comment]
Is this still reproducible? If, yes, can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Closing as the author didn't communication any further.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
