### ISSUE TITLE
Integrate Parcel 📦🚀

### ISSUE THREAD

**Issue by tatsujb** [angular/angular-cli#15981]
# 🚀 Feature request
Intergrate PARCEL : [parceljs.org](https://parceljs.org/)

### Command 
```
- [ ] new
- [x ] build
- [x ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Webpack being replaced with parcel or some other bundler. 

Webpack is old 

- On a frequent basis webpack gets out of sync with the current state of the project and will fall behind 1 or N (yes it really can be unlimited in how far back) builds. You're then coding while working with a "phantom build" or "ghost build" a served state of the app which is 1 or N compiles behind what you currently have on disk / in your IDE. this is impossible to flag/debug. You must be aware this can happen and remember to think about it constantly when something iffy is happening (old state of the code clearly on page / not expected behavior) and react by killing all npm instances on your PC and compiling from scratch.

Worst part about this is that it can sometimes be chimeric : a little of the current state a little of an old state. which leads to truly aberrant behavior.
You can waste a lot of time debugging your code over this when in reality your code was 100% correct.
- Speaking of time, webpack is very slow. If you use rollup, parcel or another solution on your angular cli project, initial compilation will be super-fast by comparison and the following re-compilations even more so.
- Webpack has loads of complicated config. Parcel for one has NO config. with that being a possibility why are we trudging on with a dated config-heavy solution?

### Describe the solution you'd like

Parcel would do nicely but I would also be happy with [rollup](https://rollupjs.org/guide/en/) or [pika](https://www.pika.dev/about/)

**Comment by clydin** [comment]
Duplicated of #8804

**Comment by tatsujb** [comment]
which is also closed.....
