### ISSUE TITLE
@ngtools/webpack build do not wait until AngularCompilerPlugin._make finish like in angular-cli

### ISSUE THREAD

**Issue by mmikirtumov** [angular/angular-cli#15987]
🚀 Feature request

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

We have big Angular application which is building based on webpack and @ngtools/webpack.  Build takes a lot of time. During some research I found that before starting actually build of files @ngtools/webpack run the following steps

```
AngularCompilerPlugin._setupOptions: 656.320ms
AngularCompilerPlugin._createOrUpdateProgram.ts.createProgram: 25064.073ms
AngularCompilerPlugin._make.resolveEntryModuleFromMain: 17.954ms
AngularCompilerPlugin._listLazyRoutesFromProgram.createProgram: 1.900ms
AngularCompilerPlugin._listLazyRoutesFromProgram.listLazyRoutes: 7292.047ms
AngularCompilerPlugin._emit.ts.getOptionsDiagnostics: 0.349ms
AngularCompilerPlugin._emit.ts.gatherDiagnostics.ts.getSyntacticDiagnostics: 4.739ms
AngularCompilerPlugin._emit.ts.gatherDiagnostics.ts.getSemanticDiagnostics: 18770.113ms
AngularCompilerPlugin._emit: 34101.066ms
AngularCompilerPlugin._update._emit: 34101.871ms
AngularCompilerPlugin._update: 67271.220ms
AngularCompilerPlugin._make: 67271.619ms

ngcLoader+main.ts+.ngcLoader.AngularCompilerPlugin: 15.984ms
ngcLoader+main.ts+: 45.086ms
running other build files
```
As you see it takes more than one minutes to start building and it wait to finish the command `AngularCompilerPlugin._make`

I tried to run other project using Angular-CLI and the picture is the following

```
AngularCompilerPlugin._setupOptions: 21.142ms
 10% building modules 3/3 modules 0 activeAngularCompilerPlugin._createOrUpdateProgram.ts.createProgram: 4751.113ms
AngularCompilerPlugin._make.resolveEntryModuleFromMain: 7.353ms
AngularCompilerPlugin._getLazyRoutesFromNgtools: 392.109ms
AngularCompilerPlugin._emit.ts.getOptionsDiagnostics: 0.327ms
AngularCompilerPlugin._emit.ts.gatherDiagnostics.ts.getSyntacticDiagnostics: 0.527ms
AngularCompilerPlugin._emit.ts.gatherDiagnostics.ts.getSemanticDiagnostics: 4462.985ms
AngularCompilerPlugin._emit.ts+environment.ts+.emit: 29.307ms
AngularCompilerPlugin._emit.ts+main.ts+.emit: 12.554ms
...... some other files emit
AngularCompilerPlugin._emit: 6090.988ms
AngularCompilerPlugin._update._emit: 6091.611ms
AngularCompilerPlugin._update: 11278.420ms
AngularCompilerPlugin._make: 11298.618ms
ngcLoader+main.ts+: 10.050ms
```
As you can see in Angular-CLI after command `AngularCompilerPlugin._emit.ts.gatherDiagnostics.ts.getSemanticDiagnostics`  it shows me all emit files and time which is taking for this operation. In @ngtools/webpack is it still emit all files or just blocked? If it is emitting is it possible to see all files?

I think it takes a lot of time for the step
AngularCompilerPlugin._make: 67271.619ms. 
Do you have any idea how can we improve this time? 
Is it possible to add more logs to see what actually consuming AngularCompilerPlugin?

### Describe the solution you'd like
Add more logs for AngularCompilerPlugin initial step to find which task takes more time.

**Comment by clydin** [comment]
The `AngularCompilerPlugin` is an integral part of the Angular CLI and performs Angular's Ahead-of-Time (AOT) compilation as well as transpiling the TypeScript code into JavaScript.  The TypeScript aspect also involves full type-checking with accompanying diagnostic reporting (`getSemanticDiagnostics`).
For a large project this will take time and is expected to do so.  If using Angular 8.x or earlier, AOT mode is not recommended for development purposes but rather production builds.  Angular 9.0+ (currently in RC) provides a new AOT compiler that will be the default for both production and development scenarios; and is also integrated into the `AngularCompilerPlugin`.

It is also recommended to use the Angular CLI to create and build an Angular project whenever possible.  The CLI handles the complexities of the Webpack and TypeScript configuration as well as automatically adjusting the configurations at build-time based on the needs of the project and managing the versions of critical dependencies.  The `AngularCompilerPlugin` is also only one part of the CLI which provides numerous additional features such as differential loading, localization, and Angular specific optimizations.

Unfortunately, custom Webpack configuration development and troubleshooting is not officially supported by the Angular CLI.  However, please consider asking for assistance in these areas on a site such as [StackOverflow](http://stackoverflow.com/).
