### ISSUE TITLE
8.3.x Used terser breaks bundle when using option mangle.keep_fnames 

### ISSUE THREAD

**Issue by beskit** [angular/angular-cli#15996]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes. Was working in 7.3.9.

### Description

After upgrading @angular/cli from version 7.3.9 to 8.3.15, it became impossible to use terser option mangle.keep_fnames when overriding webpack configuration. 
This seems to be due to a known tercer problem that was fixed in version terser@4.3.9. 
https://github.com/terser/terser/blob/master/CHANGELOG.md#v439

Versions of related packages are already updated in master branch. 
https://github.com/angular/angular-cli/pull/15871 and https://github.com/angular/angular-cli/pull/15920
Is it possible to apply these changes also to branch 8.3.x?

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.15
Node: 10.15.3
OS: win32 x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.16
@angular-devkit/build-angular     0.803.16
@angular-devkit/build-optimizer   0.803.16
@angular-devkit/build-webpack     0.803.16
@angular-devkit/core              8.3.16
@angular-devkit/schematics        8.3.15
@angular/cdk                      8.2.3
@angular/cli                      8.3.15
@angular/material                 8.2.3
@ngtools/webpack                  8.3.16
@schematics/angular               8.3.15
@schematics/update                0.803.15
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/commit/882954b5275f0bf40634ed160704f718a5d41ebc

**Comment by beskit** [comment]
@alan-agius4, 
terser-webpack-plugin@1.4.1 also has a tercer@4.3.8 dependency.

So users who override terser-webpack-plugin may also have issue if they do not add correct version of plugin to their package.json.
Some projects are not able to add new dependencies to their package.json.

Could you please update also terser-webpack-plugin to 2.2.1 as part of this issue?
It has also already updated in master https://github.com/angular/angular-cli/pull/15920 
This will also avoid multiple versions of the same library.

**Comment by clydin** [comment]
The terser webpack plugin has a dependency for terser of “^4.1.2” which is a range that includes the latest version of 4.x. 

https://github.com/webpack-contrib/terser-webpack-plugin/blob/aa12914c34f3eac7280052dad3de465a163630d7/package.json#L46


As a result no changes are necessary to the CLI for terser 4.3.9 or newer to be used.

**Comment by beskit** [comment]
@clydin you're right. Version 4.8.9 will be used. I think it will cover almost all common cases
