### ISSUE TITLE
Does @angular-devkit/build-ng-packagr:build have any configurable options?

### ISSUE THREAD

**Issue by wyan-all** [angular/angular-cli#15994]
I'm using the Angular CLI to build/package my component library, and I wanted to include the third party from the root of the project.
So I wanted to see if the builder had any configuration options, but there aren't any published on the wiki.
I want to add options to my angular.json for building the library.
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "library/tsconfig.lib.json",
            "project": "library/ng-package.json",
            // add options here!
            //“assets”：[ ],
            //"styles":  [ ],
            //"scripts": [ ],
   
          }
        },
but,there are some erros: data path "" should not have additional properties(assets).

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
