### ISSUE TITLE
Question: are you planning to build angular-cli on top of ember-cli?

### ISSUE THREAD

**Issue by cironunes** [angular/angular-cli#16]
I've forked, cloned and played around a bit with angular-cli. One thing that surprised me is that it uses ember-cli. As far as I saw, it's not that extensible (we gotta follow they API) and there are bugs like #12.

**Comment by QuantumInformation** [comment]
Would be cool if it keeps building off ember-cli.

**Comment by cironunes** [comment]
@rodyhaddad explained that the reason why is pretty much because of its addon and generation system.
