### ISSUE TITLE
New project with webpack

### ISSUE THREAD

**Issue by mrfuxi** [angular/angular-cli#1600]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 14.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.11-webpack
node: 6.3.1
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

``` bash
$ ng new webtest
$ cd webtest
$ ng serve
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
Error: No angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.
    at Class.module.exports.Task.extend.setupBroccoliBuilder (PATH/webtest/node_modules/angular-cli/lib/models/builder.js:57:13)
    at Class.module.exports.Task.extend.init (PATH/webtest/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (PATH/webtest/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (PATH/webtest/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at PATH/webtest/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (PATH/webtest/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (PATH/webtest/node_modules/rsvp/dist/rsvp.js:1048:17)
    at PATH/webtest/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (PATH/webtest/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
```

5. Mention any other details that might be useful.

Running this solved the issue:
```bash
rm -rf node_modules dist tmp typings
npm install --save-dev angular-cli@webpack
npm install
```

Is that really necessary for brand new project? Did I missed anything?

**Comment by Namek** [comment]
What I experience is:
```
ERROR in [default] C:\Users\Kamil\.babun\cygwin\home\Kamil\_nshop-frontend\test_webpack_cli\src\app\app.component.ts:5:12
Cannot find name 'require'.

ERROR in [default] C:\Users\Kamil\.babun\cygwin\home\Kamil\_nshop-frontend\test_webpack_cli\src\app\app.component.ts:6:11
Cannot find name 'require'.
```

But it works. Seems like `typings.d.ts` is not linked.

**Comment by cexbrayat** [comment]
@mrfuxi You did not miss anything :). 

It has been fixed a while ago, but not yet released https://github.com/angular/angular-cli/commit/f1808c3b8010687dd62e464350ac5373dc964f91

You can probably close the issue

**Comment by hansl** [comment]
Closing this as fixed. The next release today or tomorrow will have this.
