### ISSUE TITLE
Analytics question prevents update to v9

### ISSUE THREAD

**Issue by DeborahK** [angular/angular-cli#16012]
# 🐞 bug report

### Description

 When selecting "yes" OR "no" for sharing anonymous usage data, it modifies the angular.json file, adding an analytics entry. This dirties the repository, preventing the update from continuing.

## 🔬 Minimal Reproduction

 
1) ng update @angular/cli @angular/core --next

2) Answer Y to " Would you like to share anonymous usage data..."

3) Result:

"Thank you for sharing anonymous usage data. Would you change your mind, the following
command will disable this feature entirely:

    ng analytics project off

Repository is not clean. Please commit or stash any changes before updating."

## 🔥 Exception or Error
<pre><code>

Repository is not clean. Please commit or stash any changes before updating. 
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8.1.3

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you please provide the full output of `ng version` prior to running `ng update`?

Thanks
