### ISSUE TITLE
Not saving update to latest CLI version 8 makes repeat attempts error-prone

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#16021]
This issue impacts 9.0.0-rc.0 and happened while updating https://github.com/vmware/clarity.

In https://next.angular.io/guide/updating-to-version-9 the suggested update procedure is to follow these commands:
```
npm install --no-save @angular/cli@^8.3.15
ng update @angular/cli @angular/core --next
```

When the update procedure fails, a user will need to manually revert their repository to before the update (as described in https://github.com/angular/angular-cli/issues/16020) and attempt to update again.

If the user forgets to run `npm install --no-save @angular/cli@^8.3.15`, they will end up an incorrect update.

It would be better to instruct users to save and commit their update to `@angular/cli@^8.3.15` before proceeding in order to reduce mistakes in subsequent update attempts.

cc @StephenFluin @mgechev

**Comment by StephenFluin** [comment]
Is there any reason we aren't just asking people to `ng update @angular/core@8 @angular/cli@8` prior to updating, rather than doing the no-save bump of the CLI?

**Comment by filipesilva** [comment]
Discussed it with @clydin, we could do that but there wouldn't be any real benefit over just doing `npm install` and committing the changes.

On the other hand, it'd take longer, and we don't really test `ng update` on minors. Everything should be ok, but it doesn't sound wise to try right now. 

So I think `npm install @angular/cli@^8.3.15` followed by committing the update to git is the best approach.

**Comment by clydin** [comment]
Fully supporting and testing `ng update` for all update scenarios is something that I think we should definitely be doing moving forward.

Also, if there is a strong preference for only referencing `ng update` in the instructions, it is a possibility.  Thinking about it some more and I do agree there is a elegance to the suggestion.

**Comment by StephenFluin** [comment]
I prefer only referencing `ng update` as this command is more error-proof. Any time you go back to npm installs, you might miss a version or update (what if you were on 7 and you tried these instructions?), whereas ng update will work to keep the world in sync.

**Comment by vikerman** [comment]
Doc change. Needs to be tried out.

**Comment by filipesilva** [comment]
Still needs StephenFluin/angular-update-guide#40 before we can close.

**Comment by alan-agius4** [comment]
Closing as the above mentioned PR was merged.
