### ISSUE TITLE
Build fails with "Unexpected token ] in JSON" after updating to version 9

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#16024]
This issue impacts 9.0.0-rc.0 and happened while updating https://github.com/SAP/cloud-commerce-spartacus-storefront.

After updating successfully to version 9, but build fails with `Unexpected token ] in JSON at position 195` after seeming to finish successfully.

```
kamik@RED-X1C6 MINGW64 /d/sandbox/cloud-commerce-spartacus-storefront (update-9)
$ yarn build
yarn run v1.17.3
$ ng build storefrontapp --prod
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.

chunk {0} runtime-es2015.52756d3ab8e6582f0541.js (runtime) 1.45 kB [entry] [rendered]
chunk {0} runtime-es5.52756d3ab8e6582f0541.js (runtime) 1.45 kB [entry] [rendered]
chunk {2} polyfills-es2015.9d25e173e20e35a89c7c.js (polyfills) 49.4 kB [initial] [rendered]
chunk {3} polyfills-es5.c526f8e419af7aac625d.js (polyfills-es5) 138 kB [initial] [rendered]
chunk {1} main-es2015.229b1ef42e6e191943e4.js (main) 1.29 MB [initial] [rendered]
chunk {1} main-es5.229b1ef42e6e191943e4.js (main) 1.5 MB [initial] [rendered]
chunk {4} styles.da4c41d41cbf7725e5f1.css (styles) 350 kB [initial] [rendered]
Date: 2019-11-01T18:08:48.998Z - Hash: 2dc34f91b4b37faf77fa - Time: 120820ms
Unexpected token ] in JSON at position 195
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alan-agius4** [comment]
The root cause of the issue seems to be the same as https://github.com/angular/angular-cli/issues/15462 to be more precise the `appendValueInAstArray` https://github.com/angular/angular-cli/blob/07780b9272d985606d318da16d732dd28a41d592/packages/schematics/angular/utility/json-utils.ts#L152 method.

The failing part here is the SW generation and the error is coming from when trying to parse the ngsw config.

**Comment by alan-agius4** [comment]
Also related https://github.com/angular/angular-cli/issues/14776
