### ISSUE TITLE
Support XDG Base Directory Specfication

### ISSUE THREAD

**Issue by muradm** [angular/angular-cli#16049]
# 🚀 Feature request

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ X ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
There is a [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which supports keeping home directory in linux environments tidy. Currently, `@angular/cli` keeps its global configuration in `$HOME/.angular-config.json` which is poluting user's home directory. According to mentioned above specification, it is advised to keep configuration under `$HOME/.config` directory by default.

### Describe the solution you'd like
Non intrusive solution is provided with #16034 PR. Basically it makes everything working as it is now, until user decides to move current `$HOME/.angular-config.json` to `$XDG_CONFIG_HOME/angular/.angular-config.json`. Then `@angular/cli` will continue using `.angular-config.json` from new location. Where `$XDG_CONFIG_HOME` as per specification: if provided in the environment new location will be `$XDG_CONFIG_HOME/angular/.angular-config.json` other wise `$HOME/.config/angular/.angular-config.json`. This way it does not break other non XDG users like people under Windows.

### Describe alternatives you've considered
No alternatives.

**Comment by clydin** [comment]
Closing as https://github.com/angular/angular-cli/pull/16034 appears to have been merged.
