### ISSUE TITLE
Error on erroring in @angular-devkit/build-angular

### ISSUE THREAD

**Issue by joshcomley** [angular/angular-cli#16043]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Unsure, only just started trying to use `@angular-devkit/build-angular`, however the error happens with both `0.900.0-rc.0` and `0.803.17`.

### Description

When I run `ng build` and it errors, an attempt to print the error fails with an error printing the error.

## 🔬 Minimal Reproduction
Configure an `angular.json` webpack extension file with the following contents:

	module.exports = (env, argv) => {
		return {

		};
	};

## 🔥 Exception or Error
	D:\Code\Playgrounds\ng9test\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\stats.js:43
		const colors = statsConfig.colors;
								   ^

	TypeError: Cannot read property 'colors' of undefined
		at Object.statsToString (D:\Code\Playgrounds\ng9test\node_modules\@angular-devkit\build-angular\src\angular-cli-files\utilities\stats.js:43:32)
		at D:\Code\Playgrounds\ng9test\node_modules\@angular-devkit\build-angular\src\browser\index.js:43:33
		at callback (D:\Code\Playgrounds\ng9test\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:26:13)
		at finalCallback (D:\Code\Playgrounds\ng9test\node_modules\webpack\lib\Compiler.js:257:39)
		at D:\Code\Playgrounds\ng9test\node_modules\webpack\lib\Compiler.js:273:13
		at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Code\Playgrounds\ng9test\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
		at AsyncSeriesHook.lazyCompileHook (D:\Code\Playgrounds\ng9test\node_modules\tapable\lib\Hook.js:154:20)
		at onCompiled (D:\Code\Playgrounds\ng9test\node_modules\webpack\lib\Compiler.js:271:21)
		at D:\Code\Playgrounds\ng9test\node_modules\webpack\lib\Compiler.js:681:15
		at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Code\Playgrounds\ng9test\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
		at AsyncSeriesHook.lazyCompileHook (D:\Code\Playgrounds\ng9test\node_modules\tapable\lib\Hook.js:154:20)
		at D:\Code\Playgrounds\ng9test\node_modules\webpack\lib\Compiler.js:678:31
		at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Code\Playgrounds\ng9test\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
		at AsyncSeriesHook.lazyCompileHook (D:\Code\Playgrounds\ng9test\node_modules\tapable\lib\Hook.js:154:20)
		at D:\Code\Playgrounds\ng9test\node_modules\webpack\lib\Compilation.js:1423:35
		at AsyncSeriesHook.eval [as callAsync] (eval at create (D:\Code\Playgrounds\ng9test\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)

The problem is these lines in `@angular-devkit/build-angular/src/angular-cli-files/utilities/stats`:

    const colors = statsConfig.colors;

I can fix it and get the correct output by changing the lines like above to:

    const colors = statsConfig ? statsConfig.colors : null;

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.0
Node: 12.12.0
OS: win32 x64
Angular: 9.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@angular/cdk                      8.2.3
@angular/material                 8.2.3
@bazel/typescript                 0.39.1
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Comment by clydin** [comment]
Can you provide further details on what you are attempting?
Within the CLI, Webpack is used as the internal bundler implementation and is not exposed to the user.

**Comment by joshcomley** [comment]
I'm using a custom builder to inject some machine based environment variables using this in `angular.json`:

      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "extra-webpack.config.js"
            }, ...
        }
      }

If my `extra-webpack.config.js` looks like this, it's fine:

    module.exports = { ... };

But if I try to do this, it breaks, but the breaking also breaks:

    module.exports = (env, args) => { ... };

**Comment by clydin** [comment]
Thank you for the additional information.  Unfortunately, custom builders are not supported by the Angular team. Only the official builder packages (e.g., `@angular-devkit/build-angular` and `@angular-devkit/build-ng-packagr`) are maintained and supported by the Angular team.

For assistance with a custom builder, please consider creating an issue at the custom builder's project.  In this case, you can find the project issue page here: https://github.com/just-jeb/angular-builders/issues

**Comment by joshcomley** [comment]
Ah, OK, thank you.

I followed a blog post on how to set this up, didn't even realise I was using non-Angular core features, so I apologise for that.

Perhaps there is another way to achieve what I need. I'll ask on StackOverflow if it is possible to inject machine based information into the environment variables somehow instead of doing this with `DefinePlugin`.

Thanks for the quick responses and apologies again!

**Comment by clydin** [comment]
No need to apologize and best of luck on finding a solution.
