### ISSUE TITLE
i18n-locale should inject dir attribute

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#16047]
# 🚀 Feature request
Add dir="rtl" for rtl locales

### Command (mark with an `x`)

```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...
Angular pages are always LTR, even when specifying an rtl language in `i18n-locale` parameter

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
When running build with `i18n-locale` set to an RTL language such as Hebrew or Arabic, add `dir="rtl"` to html or body tags in index.html.
I know that the cli can modify the html, because `base-href` parameter does it

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Manually setting the dir tag, but then what happens if I want to support different build configs for rtl, and ltr locales? I will have to manually change the dir tag before every build.

**Comment by Talb2005** [comment]
Any progress with this issue?

**Comment by GabrielGil** [comment]
It would be great to have this in place, or some clarification on what's the best approach to serve an index.html that can have different `dir` attribute values.
