### ISSUE TITLE
Error comes while Adding LazyLoading in routes for Custom Library

### ISSUE THREAD

**Issue by shivamvarshney** [angular/angular-cli#16052]
I am creating a angular library, having routes as well module specific structure which are having their own routing, as we creates in App/SRC.
Below is the code description:- 
Library Code:-
ProjectNameModuleRoutingFile:-
const routes: Routes = [ { path: '', redirectTo: 'role', pathMatch: 'full' }, { path:'new', component:CoreUserManagementComponent }, { path: 'role',loadChildren:'./role-management/role.module#RoleModule' } ]
@NgModule({ imports: [RouterModule.forChild(routes)], exports: [RouterModule] })

Applicarion Src :-
AppRoutingFile :-
const routes: Routes = [ { path:'test', loadChildren: () => import('project-name').then((res) => res.ProjectNameModule) } ]
@NgModule({ imports: [RouterModule.forRoot(routes)], exports: [RouterModule] })

Here while creating build of the library, no error comes, also no error comes while running ng serve for the application after adding the library. But while accessing the route from the browser, for which i have added library, it throws error like:- 
"core.js:15723 ERROR Error: Uncaught (in promise): Error: Cannot find module './role-management/role.module'"

Thanks

**Comment by alan-agius4** [comment]
Lazy loading should happen at an application and not a library level.

See the last 2 post in https://github.com/angular/angular-cli/issues/6373#issuecomment-453006158 for more context.

**Comment by shivamvarshney** [comment]
So Is there no substitute available for such type of scenario? 
Like can we mention something library path in projects/project-name/ng-package.json, so that It can we use, something like this. So that this error can be removed "Error: Cannot find module".
