### ISSUE TITLE
CLI Migrations that make commits should print to the screen while doing so

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular-cli#16060]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] update
```

### Description
When the CLI makes a commit to my repository, it should also print to the screen that is doing so.

CC @vikerman

**Comment by dgp1130** [comment]
What do we want this to look like? Is this as simple as displaying:

```
Committing migration step: "<commit message>"
```

or is there more information we want to display here?

Also, do we support only Git, or are there other source control systems we will need to account for and might want to display different information for?

**Comment by clydin** [comment]
The CLI only supports git at this time.  I think the above message should be good to start; maybe add the short hash as well.  The commit message itself may be multiple lines so it may be a good to truncate it at the first newline character.

**Comment by dgp1130** [comment]
Ok, good idea to include the hash and truncate at the newline. So it would look something like:

```
Committing migration step (<short hash>): <commit message>
```
