### ISSUE TITLE
angular libraries not honoring base-href or deploy-url

### ISSUE THREAD

**Issue by rupamroy** [angular/angular-cli#16075]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Not sure

### Description
I have an angular library `my-lib` which makes a api call in using `http.get('/api/products')`. This library is built using `ng build my-lib`. 

There is the app `my-app` which is using the `my-lib` library, my app itself makes an api call using `http.get('/api/orders')`. 

`my-app` is built using

`ng build --prod --base-href=/mib2b/ --deploy-url=/mib2b/`

Now the issue is that when the app run the following api calls are initiated 
```
localhost:4200/mib2b/api/orders
localhost:4200/api/products
```
As we can see the call from within the library is not honoring the base-href. 
Is there a reason why this is like that and i believe it should be fixed.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.3
Node: 10.16.3
OS: linux x64
Angular: 8.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.3
@angular-devkit/build-angular     0.801.3
@angular-devkit/build-optimizer   0.801.3
@angular-devkit/build-webpack     0.801.3
@angular-devkit/core              8.1.3
@angular-devkit/schematics        8.1.3
@angular/http                     7.2.15
@ngtools/webpack                  8.1.3
@schematics/angular               8.1.3
@schematics/update                0.801.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.35.2

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
The behavior you are experiencing is the standardized behavior of the HTML base HREF.  Web browsers only use the base HREF for relative URLs.  The example URLs included above are not relative and will not be altered by the browser.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by rupamroy** [comment]
The calls are being initiated using 
http.get('/api/products') and http.get('/api/orders') 

and they are relative urls. And also why is it that one is being altered and another is not. 

Please re-open this issue.

**Comment by clydin** [comment]
Root-relative URLs are a class of absolute URLs and are not considered relative by the HTML specification.  This is the behavior of the web browser itself and not related to Angular or the Angular CLI.
