### ISSUE TITLE
ng build --prod --base-href (wont correctly access the assets folder)

### ISSUE THREAD

**Issue by yandiro** [angular/angular-cli#16076]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Not sure

### Description
Angular looks for image assets in root folder, not the folder specified with --base-href '/folder/'

## 🔬 Minimal Reproduction

'ng new' to start a new project

create an 'img' folder inside assets folder.

use '<img>' in view to display this image.

watch everything work fine with 'ng s'

'ng b --prod --base-href '**/acta/**'' to build the project for production inside subfolder named 'acta'.

'http-server' inside dist folder
(I served the project inside dist folder using http-server {https://www.npmjs.com/package/http-server}, but the error happens also in host {goDaddy running windows} )

## 🔥 Exception or Error
Chrome inspector shows errors reporting 'localhost:8080/assets/img/filename.png' was not found, but the file is at 'localhost:8080/**acta**/assets/img/filename.png' 

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.8
Node: 10.9.0
OS: linux x64
Angular: 8.2.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.8
@angular-devkit/build-angular     0.803.8
@angular-devkit/build-optimizer   0.803.8
@angular-devkit/build-webpack     0.803.8
@angular-devkit/core              8.3.8
@angular-devkit/schematics        8.3.8
@angular/cli                      8.3.8
@angular/fire                     5.2.1
@ngtools/webpack                  8.3.8
@schematics/angular               8.3.8
@schematics/update                0.803.8
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**
Not sure if this is relevant, but I fixed this by uploading the 'assets' folder to the root directory, so the images are found.

**Comment by alan-agius4** [comment]
Hi, can you please provide a bit of information on how you are referencing the image?

Thanks.

**Comment by yandiro** [comment]
Of course! My bad.

`<img src="../../assets/img/logo_acta.jpeg" class="img-fluid" alt="">`

**Comment by clydin** [comment]
The browser will combine the base HREF with the URL which will result in `/acta/../../assets/img/logo_acta.jpeg`.  Normalizing that would then result in `/assets/img/logo_acta.jpeg`.
A URL of `./assets/img/logo_acta.jpeg` should provide the desired behavior.

**Comment by yandiro** [comment]
Shoot!

Sorry for opening a bug report because of this.

Túlio Sandoval
