### ISSUE TITLE
Appropriate loader missing for dynamic imports from combined path

### ISSUE THREAD

**Issue by joachim-heck** [angular/angular-cli#16088]
# 🐞 Bug report

I'm still struggeling with the webpack  related warnings: `Module parse failed: Unexpected token (8:28) You may need an appropriate loader to handle this file type`.  during ng serve after updating to Angular 8. The referred solutions of [#14566] (https://github.com/angular/angular-cli/issues/14566) didn't work for us. 

### Command
```
- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

## 🔬 Minimal Reproduction
Updating a solution that uses dynamic import() **with a dynamically combined path** during runtime to angular 8.

## 🔬 More detailed explanation:
I'm using import of a module which is specified using a modulePath and moduleName variable. The modulepath and name are resolved dynamically during runtime <= which seems to be the problem. Regarding the following issue: https://github.com/webpack/webpack/issues/4292

<pre><code>
` import('../../' + modulePath).then(result => {
          this.compiler.compileModuleAsync(result[moduleName]).then(moduleFactory => {
           // Handle modulefactory
          });
</code></pre>

**The warning is thrown for each component of the loaded module.**

## 🔥 Exception or Error
```
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
> <my-component>
| </my-component>

```

## 🌍 Your Environment
<pre><code>Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.17
@angular-devkit/build-angular      0.803.17
@angular-devkit/build-ng-packagr   0.803.17
@angular-devkit/build-optimizer    0.803.17
@angular-devkit/build-webpack      0.803.17
@angular-devkit/core               8.3.17
@angular-devkit/schematics         8.3.17
@angular/cdk                       8.2.3
@angular/cli                       8.3.0
@angular/compiler-cli              8.2.3
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/pwa                       0.803.17
@ngtools/webpack                   8.3.17
@schematics/angular                8.3.17
@schematics/update                 0.803.0
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Comment by clydin** [comment]
Could you provide more details on what you are attempting to achieve?

**Comment by joachim-heck** [comment]
Hopefully I can break it down understandable...

I'm using the `NgModuleFactory` to dynamically create a `ModuleFactory` which finally will be used to create a `ComponentFactory` to create a component of a specific not yet loaded module. Therefore I'm using the `import` function and the returning promise to create the needed ComponentFactory using the `compileModuleAsync` function.

```
import('../../admin/admin.module').then(result => {
          this.compiler.compileModuleAsync(result['AdminModule']).then(moduleFactory => {
            subject.next(moduleFactory);
            subject.complete();
          });
```
It seems like the import function is throwing the warnings in the console.warn log.
The warnings disappear in the production build.

**Comment by alan-agius4** [comment]
Can you please provide the output of `npm ls acorn`? thanks

**Comment by joachim-heck** [comment]
Here it comes, thanks for the support:

```
+-- @angular-devkit/build-angular@0.803.17
| `-- webpack@4.39.2
|   `-- acorn@6.3.0
+-- acorn@6.3.0
+-- ng-packagr@5.7.1
| `-- rollup@1.25.2
|   `-- acorn@7.1.0
+-- pdfmake@0.1.61
| +-- linebreak@1.0.2
| | `-- brfs@2.0.2
| |   `-- static-module@3.0.3
| |     `-- acorn-node@1.8.2
| |       `-- acorn@7.1.0
| `-- pdfkit@0.10.0
|   `-- fontkit@1.8.0
|     `-- brfs@1.6.1
|       `-- static-module@2.2.5
|         `-- falafel@2.1.0
|           `-- acorn@5.7.3
`-- webpack-bundle-analyzer@3.6.0
  `-- acorn@6.3.0
```

**Comment by filipesilva** [comment]
I'm not really sure what's wrong but a repro would really help us debug it.

**Comment by joachim-heck** [comment]
Ok, I think I figured it out - the issue seems to be related to webpack: https://github.com/webpack/webpack/issues/4292 

because of we are using a dynamic creation of the import path (which I didn't mentioned in the above shown example) like:

```
import('../../' + modulePath).then(result => {
          this.compiler.compileModuleAsync(result[moduleName]).then(moduleFactory => {
           // Handle modulefactory
          });
```
The problem doesn't occure when using fixed path declarations like 

```
import('../../admin/admin.module').then(result => {
          this.compiler.compileModuleAsync(AdminModule).then(moduleFactory => {
           // Handle modulefactory
          });
```

**Comment by filipesilva** [comment]
Are you using Ivy? With Ivy those more involved cases should work better.

**Comment by joachim-heck** [comment]
> Are you using Ivy? With Ivy those more involved cases should work better.

Unfortunately I'm currently not able to switch to Ivy due to its throwing an: `ERROR in Unsupported binary operator: FirstAssignment` ERROR during compilation and doesn't show up with any more information on this - also the site isn't loading.

**Comment by kyliau** [comment]
Closing this, since issue stems from upstream webpack behavior and is resolved in https://github.com/angular/angular-cli/issues/16088#issuecomment-553276941
