### ISSUE TITLE
Browser loading cached version of index.html - angular 7

### ISSUE THREAD

**Issue by KrishnaAnanthi** [angular/angular-cli#16081]
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

I have an angular 7 application running on python server, using angular-cli we are building project files. While building i am setting up cache bursting option using the below command.

ng build --prod --build-optimizer --aot --output-hashing=all

output-hashing=all will take care of cache bursting as per angular documentation. Though i provided this flag, after deploying our app files name are appended with hashed value(styles.a5169d3732258e921e2c.css, main.8dc0644c88c4fbf67797.js) but index.html file is always showing cached version.

Becoz of this i need to clear cache in client side every time after deployment to see the latest changes.

I want to cache all files in client side except index.html. How will i do this?

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>
 Angular cli - 7.2.7
**Anything else relevant?**

**Comment by clydin** [comment]
This is caused by the web servers cache control configuration.  The index should never be instructed to be cached.
For more information on caching, please see https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching
