### ISSUE TITLE
Add migration to change ts module to esnext

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular-cli#16094]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

In version 9 we are running the lazy-loading syntax migration to change the string based lazy-loading with `import()`. 

We however don't have a migration to ensure that that in the workspace tsconfig the module is set to `esnext` and this will failures at build time.

## 🔥 Exception or Error

```
ERROR in app/routing.module.ts:7:38 - error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.

7   {path: 'grid', loadChildren: () => import('./grid/grid.module').then(m => m.DocsGridModule)},
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/routing.module.ts:8:38 - error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.

8   {path: 'docs', loadChildren: () => import('./layout/layout.module').then(m => m.DocsLayoutModule)},
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/routing.module.ts:9:44 - error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.

9   {path: 'responsive', loadChildren: () => import('./responsive/responsive.module').then(m => m.DocsResponsiveModule)},
                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/routing.module.ts:10:40 - error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.

10   {path: 'issues', loadChildren: () => import('./github-issues/github-issues.module').then(m => m.DocsGithubIssuesModule)},
                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
app/routing.module.ts:13:25 - error TS1323: Dynamic import is only supported when '--module' flag is 'commonjs' or 'esNext'.

13     loadChildren: () => import('./stack-overflow/stack-overflow.module').then(m => m.DocsStackOverflowModule)
```

**Comment by filipesilva** [comment]
We did those things in the migration to 8 I believe:
https://github.com/angular/angular-cli/blob/7d1247b9e58571e218acc55d295a4ef0b9066383/packages/schematics/angular/migrations/update-8/differential-loading.ts#L154-L158

https://github.com/angular/angular-cli/blob/7d1247b9e58571e218acc55d295a4ef0b9066383/packages/schematics/angular/migrations/update-8/update-lazy-module-paths.ts#L55

**Comment by alan-agius4** [comment]
Yeah, but in v9 we are re-trigger the `update-lazy-module-paths.ts` since string based lazy loading doesn't work with Ivy. However, we are not re-trigger the Dl migration. 

I have a PR, to address this; https://github.com/angular/angular-cli/pull/16097
