### ISSUE TITLE
Generate new app fails on OS X 10.11.3

### ISSUE THREAD

**Issue by billsaysthis** [angular/angular-cli#161]
```bash
~/Sites/ng-events» node -v
v5.5.0
~/Sites/ng-events» npm -v
3.5.3

npm ERR! ng-core-addons@0.0.9 postinstall: `node ./node_modules/fs-concatenate -i content -o snippets.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng-core-addons@0.0.9 postinstall script 'node ./node_modules/fs-concatenate -i content -o snippets.js'.
```

Similar error if I try to install ng-core-addons separately.

**Comment by filipesilva** [comment]
Hi! What command were you running when you ran into this issue?

**Comment by billsaysthis** [comment]
ng new <appname>

**Comment by jkuri** [comment]
Hi @billsaysthis looks like you are not using the right cli (first Google result for ng-core-addons). Please try `npm install angular-cli` and then run `ng new`. It should be working fine on os x.

**Comment by billsaysthis** [comment]
@jkuri You are (of course) correct, thanks.
