### ISSUE TITLE
No matching version found for @angular-devkit/core@8.3.18

### ISSUE THREAD

**Issue by acim** [angular/angular-cli#16109]
# 🐞 Bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.3.17

### Description

 A clear and concise description of the problem...
npm install -g @angular/cli gives the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/core@8.3.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-07T21_33_36_072Z-debug.log
``` 

npm install -g @angular/cli@8.3.17

works fine.

## 🔬 Minimal Reproduction

npm install -g @angular/cli@8.3.18

## 🔥 Exception or Error
<pre><code>

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/core@8.3.18.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-07T21_33_36_072Z-debug.log
</code></pre>

## 🌍 Your Environment
<pre><code>

Docker image node:12-alpine
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
As per the npm registry, the version 8.3.18 is published and available as the latest tag: https://www.npmjs.com/package/@angular-devkit/core/v/8.3.18

As this has recently been published, the registry may take some time to propagate packages through its system.  If using a proxy, this also may not yet have synchronized with the registry.

**Comment by acim** [comment]
Yes, it works now, thank you. I am backend guy, this just broke my build pipeline so I reacted :smile:
