### ISSUE TITLE
ivy + Support XTB load translations parser in v9

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular-cli#16100]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [x] build
- [x] serve
```

### Description
With IVY add  support [xtb_translation_parser](https://github.com/angular/angular/blob/master/packages/localize/src/tools/src/translate/translation_files/translation_parsers/xtb_translation_parser.ts) 

### Describe the solution you'd like
I think ? in [xtb_translation_parser.ts#L62](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/utils/load-translations.ts#L62) add:

```
xtb: new (await Promise.resolve().then(() => require(
// @ts-ignore
// tslint:disable-next-line:trailing-comma
'@angular/localize/src/tools/src/translate/translation_files/translation_parsers/xtb_translation_parser'))).XtbTranslationParser()
```

**Anything else relevant?**
Maybe at the moment xtb parser is not ready (@petebacondarwin ?) Because after hack locally and after my app build finish, I get warnings that almost all translations with interpolations are not translated:
![xtb](https://user-images.githubusercontent.com/2789203/68393216-df6fdc80-016b-11ea-9054-dee17403e647.gif)

A lot of them are duplicated

/cc @filipesilva

**Comment by petebacondarwin** [comment]
The i18Format needs to line up because we use a legacy mode if xliff that converts ids to xliff, which might be causing the misses...
