### ISSUE TITLE
when i want to create my fisrt app, the message: workspace config file cannot be loaded, invalid JSON character:

### ISSUE THREAD

**Issue by emazzu** [angular/angular-cli#16118]
# 🐞 Bug report

I have the version 8.3.18

![image](https://user-images.githubusercontent.com/6100546/68483310-14d30380-021a-11ea-9bf6-6d1f7a8fcfae.png)

### Command (mark with an `x`)

```
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

when I want yo create ng new my-app01

### Description

 an unhandled exception occurred: workspace config file cannot loaded: invalid JSON character: \u0000 at 0:0.
c:\users\emazzu\.angular-config.json

![image](https://user-images.githubusercontent.com/6100546/68483338-21575c00-021a-11ea-9aeb-9bc6c8bd71a6.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
It seems that in the pointed file you have a `null` character.

Kindly open the file, locate the character and remove it.
