### ISSUE TITLE
commands with ng serve

### ISSUE THREAD

**Issue by tailot** [angular/angular-cli#16120]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generat
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
Ability to launch commands during development (during ng serve). The world is ruining ctrl + c keys :-)

**Comment by clydin** [comment]
Multiple shells can be opened during development.   It is quite common for a developer to have at least several different shells open at any given time.

If using a `sh`/`bash` type shell, the process can also be executed in the background: `ng serve &`.

As there are multiple existing options available to facilitate the request, there are no plans to add such a feature to `ng serve` at this time.
