### ISSUE TITLE
new command ui

### ISSUE THREAD

**Issue by tailot** [angular/angular-cli#16121]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] ui (a new command)
```

### Description
should launch an ui that facilitates the configuration of the application.

**Comment by alan-agius4** [comment]
I think this is out of the current scope of the Angular tooling team.

A GUI version of the Angular CLI can be found: https://angularconsole.com
