### ISSUE TITLE
CSS Variables are lost when running ng build --prod

### ISSUE THREAD

**Issue by neofuture** [angular/angular-cli#16123]
When running ng build --prod in release candidate of Angular 9 the CSS variables are removed from some elements please see screenshots  these are originally in styles.css

Development Mode
<img width="2226" alt="Screenshot 2019-11-04 at 11 08 27" src="https://user-images.githubusercontent.com/11268634/68116879-cc52d780-fef3-11e9-8263-58a3185a7f04.png">

Production Mode
<img width="2226" alt="Screenshot 2019-11-04 at 11 08 55" src="https://user-images.githubusercontent.com/11268634/68116906-d83e9980-fef3-11e9-95db-c91981cde41e.png">

**Comment by clydin** [comment]
I believe you are encountering the following defect from the CSS optimizer: https://github.com/jakubpawlowicz/clean-css/issues/1060

As a workaround until the defect has been corrected, the section in question can be altered to add ignore comments ([reference](https://github.com/jakubpawlowicz/clean-css#how-to-keep-a-css-fragment-intact)) to prevent the optimizer from altering the rule.  As an example using the provided reproduction code:
```
/* clean-css ignore:start */
.border-box {
  border:1px solid var(--red) !important;
}
/* clean-css ignore:end */
:root {
  --red: #ff0000;
}
```
