### ISSUE TITLE
Angular app with library fails on prod build

### ISSUE THREAD

**Issue by JGH153** [angular/angular-cli#16147]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Unsure, as this is the first time building a library.

### Description
Running `ng build --prod` fails with `Module not found error`, but every `ng build` (without prod) works.
The bug is present every time we build for prod on either Windows, Mac or Ubuntu.

## 🔬 Minimal Reproduction
1. Clone https://github.com/hafslundnett/hal-components/tree/build-prod-error
2. `yarn` 
3. `yarn build-hal`
4. `ng build --prod`

The library is small, but let me know if you want a more stripped down version.

## 🔥 Exception or Error
The total error message is really long, here is the first 50 lines. Let me know if you need the rest.
<pre><code>
ERROR in ./dist/hal-components/hafslundnett-hal-components.ngfactory.js
Module not found: Error: Can't resolve '@hafslundnett/hal-components' in 'C:\Users\jgh\Documents\hal-components\dist\hal-components'
resolve '@hafslundnett/hal-components' in 'C:\Users\jgh\Documents\hal-components\dist\hal-components'
  Parsed request is a module
  using description file: C:\Users\jgh\Documents\hal-components\dist\hal-components\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Users/jgh/Documents/hal-components/
        using description file: C:\Users\jgh\Documents\hal-components\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\jgh\Documents\hal-components\package.json (relative path: ./@hafslundnett/hal-components)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.js doesn't exist
            as directory
              C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components doesn't exist
      C:\Users\jgh\Documents\hal-components\dist\hal-components\node_modules doesn't exist or is not a directory
      C:\Users\jgh\Documents\hal-components\dist\node_modules doesn't exist or is not a directory
      C:\Users\jgh\Documents\node_modules doesn't exist or is not a directory
      C:\Users\jgh\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\jgh\Documents\hal-components\node_modules
        using description file: C:\Users\jgh\Documents\hal-components\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\jgh\Documents\hal-components\package.json (relative path: ./node_modules/@hafslundnett/hal-components)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\node_modules\@hafslundnett\hal-components doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\node_modules\@hafslundnett\hal-components.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\node_modules\@hafslundnett\hal-components.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\node_modules\@hafslundnett\hal-components.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\jgh\Documents\hal-components\node_modules\@hafslundnett\hal-components.js doesn't exist
            as directory
              C:\Users\jgh\Documents\hal-components\node_modules\@hafslundnett\hal-components doesn't exist
[C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components]
[C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.ts]
[C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.tsx]
[C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.mjs]
[C:\Users\jgh\Documents\hal-components\@hafslundnett\hal-components.js]
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.17
Node: 10.16.0
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.17
@angular-devkit/build-angular      0.803.17
@angular-devkit/build-ng-packagr   0.803.17
@angular-devkit/build-optimizer    0.803.17
@angular-devkit/build-webpack      0.803.17
@angular-devkit/core               8.3.17
@angular-devkit/schematics         8.3.17
@angular/cdk                       8.2.3
@angular/cli                       8.3.17
@angular/language-service          8.1.3
@angular/material                  8.2.3
@ngtools/webpack                   8.3.17
@schematics/angular                8.3.17
@schematics/update                 0.803.17
ng-packagr                         5.7.1
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**
Present on Windows, Mac and Ubuntu

**Comment by alan-agius4** [comment]
Hi, the problem is that your library is named ```https://github.com/hafslundnett/hal-components/blob/860da33c19a15fabdc9e7812392684e5bc70946b/projects/hal-components/package.json#L2

However you are importing this via `hal-components` https://github.com/hafslundnett/hal-components/blob/b42ed822b82c07739227c23b1f5dafc92c408b68/src/app/shell/shell.component.ts#L3

There are two things here;
- rename your library to `hal-components`

or

- Change the imports from `hal-components` to `@hafslundnett/hal-components` 
- Change also the path mappings in https://github.com/hafslundnett/hal-components/blob/b42ed822b82c07739227c23b1f5dafc92c408b68/tsconfig.json#L23-L29 to 
```json
      "@hafslundnett/hal-components": [
        "dist/hal-components"
      ],
      "@hafslundnett/hal-components/*": [
        "dist/hal-components/*"
      ]
```

**Comment by JGH153** [comment]
Didn't know the name in the package file in the library impacted the build process. Using @hafslundnett there so it's published to that organisation on NPM when publishing. Updated the imports and the tsconfig file and it compiles now. Thanks a lot for your help!

**Comment by JGH153** [comment]
It inconsistent that is only fails with the prod flag, given that the name and imports are wrong in both cases. Any chance this will be fixed with Angular 9 and Ivy?

**Comment by alan-agius4** [comment]
Hi @JGH153, the reason why this fails with `prod` only is that in prod mode the AOT compiler is used instead of the JIT compiler.

While this is valid in JIT, it is not for AOT because of metadata symbols. In version 9 under Ivy both AOT will be enabled for both development and production builds.
