### ISSUE TITLE
proxy configuration is not working in angular universe-server side rendering

### ISSUE THREAD

**Issue by mithunvikram** [angular/angular-cli#16140]
In my project i have file proxy.conf.ts with content like this

```
const BACKEND_URL = process.env.BACKEND_URL || 'localhost';
const BACKEND_PORT = process.env.BACKEND_PORT || '3013';
const PROXY_CONFIG = {
    '/proxy/*': {
        target: `http://${BACKEND_URL}:${BACKEND_PORT}`,
        secure: false,
        pathRewrite: {
         '^/proxy': ''
        },
        changeOrigin: true,
        logLevel: 'debug'
    }
};
```
I have added `"proxyConfig":"proxy.conf.ts"` in angular.json its working only when i use `ng serve` but while using `npm run build:ssr` and `npm run serve:ssr` i got
`error: SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>)
Http failure during parsing for http://localhost:4000/proxy/generate`.

This is my package.json,
```
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test",
    "lint": "tslint ./src/**/*.ts -t verbose",
    "e2e": "ng e2e",
    "build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
    "serve:ssr": "node dist/server.js",
    "build:client-and-server-bundles": "ng build --prod && ng run angular.io-example:server",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors"
}
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
