### ISSUE TITLE
Angular CLI 9 RC1: CLI fails to run ngcc after using ng add

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular-cli#16163]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Using Angular CLI 9 RC1, Node 12, and yarn 1.19.0

1. ng new myworkspace && cd myworkspace
2. ng add @ngrx/entity
3. Note the error

## 🔥 Exception or Error
<pre><code>

```
brandons-mbp-2:cli9rc11 robertsbt$ ng add @ngrx/entity
Installing packages for tooling via yarn.
An unhandled exception occurred: warning @angular-devkit/build-angular@0.900.0-rc.1: The engine "pnpm" appears to be invalid.
warning @angular-devkit/architect@0.900.0-rc.1: The engine "pnpm" appears to be invalid.
warning @angular-devkit/build-optimizer@0.900.0-rc.1: The engine "pnpm" appears to be invalid.
warning @angular-devkit/build-webpack@0.900.0-rc.1: The engine "pnpm" appears to be invalid.
warning @angular-devkit/core@9.0.0-rc.1: The engine "pnpm" appears to be invalid.
warning @ngtools/webpack@9.0.0-rc.1: The engine "pnpm" appears to be invalid.
warning @angular/cli@9.0.0-rc.1: The engine "pnpm" appears to be invalid.
warning @angular-devkit/schematics@9.0.0-rc.1: The engine "pnpm" appears to be invalid.
warning @schematics/angular@9.0.0-rc.1: The engine "pnpm" appears to be invalid.
warning @schematics/update@0.900.0-rc.1: The engine "pnpm" appears to be invalid.
warning " > @ngrx/effects@8.5.0" has incorrect peer dependency "@angular/core@^8.0.0".
warning " > @ngrx/store@8.5.0" has incorrect peer dependency "@angular/core@^8.0.0".
warning " > @ngrx/entity@8.5.0" has incorrect peer dependency "@angular/core@^8.0.0".
/bin/sh: ngcc: command not found
```

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-rc.1
Node: 12.10.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.1
@angular-devkit/build-angular     0.900.0-rc.1
@angular-devkit/build-optimizer   0.900.0-rc.1
@angular-devkit/build-webpack     0.900.0-rc.1
@angular-devkit/core              9.0.0-rc.1
@angular-devkit/schematics        9.0.0-rc.1
@ngtools/webpack                  9.0.0-rc.1
@schematics/angular               9.0.0-rc.1
@schematics/update                0.900.0-rc.1
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Should be fixed by https://github.com/angular/angular-cli/pull/16143
