### ISSUE TITLE
App shell gives an SCSS import error when using 'stylePreprocessorOptions' in angular.json

### ISSUE THREAD

**Issue by Matthbo** [angular/angular-cli#16161]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 This problem also occurs on angular 7

### Description

 I get a scss import error when I try to run "my-app:app-shell", it seems like it doesn't use the "stylePreprocessorOptions->includePaths" option from "angular.json->...->build->options", this problem doesn't occur when running "ng build --prod" or "ng serve"

## 🔬 Minimal Reproduction

Create a new project called my-app, make sure to use scss
```
ng new my-app --routing
cd my-app
```

Generate the app-shell required files & component
```
ng generate app-shell --client-project my-app --universal-project server-app
```

Create "src/sass/test.scss" file to be imported
```
* {
  font-size: 64px;
}
```

Add "src/sass" to "angular.json"
```
  "projects": {
    "my-app": {
      "architect": {
        "build": {
          "options": {
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/sass"
              ]
            },
          }
        },
        "test": {
          "options": {
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/sass"
              ]
            },
          }
        }
      }
    } 
  }
```

Import the test.scss file into "app.component.scss"
```
@import 'test';
```

Run "my-app:app-shell"
```
ng run my-app:app-shell
```

## 🔥 Exception or Error
<pre><code>

ERROR in Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'test';
       ^
      Can't find stylesheet to import.
  ╷
1 │ @import 'test';
  │         ^^^^^^
  ╵
  stdin 1:9  root stylesheet
      in D:\Projects\Nodejs\my-app\src\app\app.component.scss (line 1, column 9)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.18
Node: 10.17.0
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.18
@angular-devkit/build-angular     0.803.18
@angular-devkit/build-optimizer   0.803.18
@angular-devkit/build-webpack     0.803.18
@angular-devkit/core              8.3.18
@angular-devkit/schematics        8.3.18
@angular/cli                      8.3.18
@ngtools/webpack                  8.3.18
@schematics/angular               8.3.18
@schematics/update                0.803.18
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

I tried to follow https://angular.io/guide/app-shell

I first got the error in an angular 7 project, but I get the same error when testing it in a new angular 8 project. This error only occurs when running the "ng run my-app:app-shell" command

**Comment by alan-agius4** [comment]
Hi, for app-shell, you also need to specify the `stylePreprocessorOptions` in the `server` target in your `angular.json`

**Comment by Matthbo** [comment]
Yes that fixes it, thanks
