### ISSUE TITLE
ng build --aot generate some unnormal chunks

### ISSUE THREAD

**Issue by bmwz110** [angular/angular-cli#16187]
Hello, everyone👋
my purpose is to split main.js into some small module and use lazy load,
I try to code according to Angular offical example(https://angular.cn/guide/lazy-loading-ngmodules).
then, I run following code: 
```
ng build
```
（I know ng build is ng uild --jit）
the result show:
```
chunk {m_module1} m_module1.js, m_module1.js.map (m_module1) 174 kB  [rendered]
chunk {m_module2} m_module2.js, m_module2.js.map (m_module2) 123.3 kB  [rendered]
chunk {m_module3} m_module3.js, m_module3.js.map (m_module3) 262.7 kB  [rendered]
chunk {m_module4} m_module4.js, m_module4.js.map (m_module4) 39.58 kB  [rendered]
chunk {m_module5} m_module5.js, m_module5.js.map (m_module5) 133.9 kB  [rendered]
chunk {m_module6} m_module6.js, m_module6.js.map (m_module6) 251.2 kB  [rendered]
chunk {m_module7} m_module7.js, m_module7.js.map (m_module7) 235 kB  [rendered]
chunk {m_module8} m_module8.js, m_module8.js.map (m_module8) 480 kB  [rendered]
chunk {m_module9} m_module9.js, m_module9.js.map (m_module9) 167.7 kB  [rendered]
chunk {m_module10} m_module10.js, m_module10.js.map (m_module10) 1.35 MB  [rendered]
chunk {main} main.js, main.js.map (main) 1.04 MB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 454 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.22 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 278 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 9.7 MB [initial] [rendered]
```

everything is good. this is the result I want.!!

but, if I run 
```
ng build --aot
```

the result as follows:

```
chunk {0} runtime.eb5e416411352923048b.js (runtime) 2.5 kB [entry] [rendered]
chunk {1} m_module1.4f69f5a0e823765c491e.js (m_module1) 186 bytes  [rendered]
chunk {2} m_module2.fe777c11596e75233cfc.js (m_module2) 186 bytes  [rendered]
chunk {3} m_module3.29b33f24136402591486.js (m_module3) 188 bytes  [rendered]
chunk {4} m_module4.1bacf5caf7a86634f413.js (m_module4) 185 bytes  [rendered]
chunk {5} m_module5.dd4668f43bf3f6aee20f.js (m_module5) 186 bytes  [rendered]
chunk {6} m_module6.5b7050e81606139e4fce.js (m_module6) 187 bytes  [rendered]
chunk {7} m_module7.ddd8edf24959d1fba105.js (m_module7) 186 bytes  [rendered]
chunk {8} m_module8.23cb4bc14fc867a1354a.js (m_module8) 189 bytes  [rendered]
chunk {9} m_module9.61d4ffedcf7195526fad.js (m_module9) 189 bytes  [rendered]
chunk {10} m_module10.3a44de56180fa7e92958.js (m_module10) 186 bytes  [rendered]
chunk {11} main.7415d34e53126270f79f.js (main) 3.35 MB [initial] [rendered]
chunk {12} polyfills.39be82b4d257d8d4ca21.js (polyfills) 105 kB [initial] [rendered]
chunk {13} styles.265b75156ea2402ea292.css (styles) 81.1 kB [initial] [rendered]
```
The content of chunk {10}  as follows:
(window.webpackJsonp=window.webpackJsonp||[]).push([[10],{wS5z:function(n,o,t){"use strict";t.r(o),t.d(o,"module10Module",function(){return u});var u=function(){return function(){}}()}}]);% 

Q: Why the chunk become very small when I use --aot. only 180+ bytes,

How can I operate to get it back to normal chunk size?

Thanks!!!

**Comment by bmwz110** [comment]
keep attention

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version` please? Also is there a way to give us a reproduction?

Thanks

**Comment by bmwz110** [comment]
> Can you please provide the output of `ng version` please? Also is there a way to give us a reproduction?
> 
> Thanks

First thank you！

The result of running `ng version` is :
-------------------------------------
Your global Angular CLI version (8.1.1) is greater than your local
version (7.3.9). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Angular CLI: 7.3.9
Node: 10.16.0
OS: darwin x64
Angular: 7.0.0
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/compiler-cli             7.2.15
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.3
typescript                        3.1.3
webpack                           4.29.0

---------------------------------------------

It's worth noting that my app.module.ts provides DatePipe, TranslateModule, and entryComponents that include some common DialogComponents.

Other places follow the standards provided by the angular example.

**Comment by bmwz110** [comment]
> Can you please provide the output of `ng version` please? Also is there a way to give us a reproduction?
> 
> Thanks

Based on your reminder, I tried to use `loadChildren: './module1.module#Module1Module'` instead of `loadChildren: () => import('./module1,module').then(mod => mod.Module1Module)`, then run `ng build -aot`, and got a seemingly correct result.

chunk module1 size looks normal.

Is the problem really caused by the angular version of the grammar?

**Comment by clydin** [comment]
7.x does not support dynamic import syntax with AOT.  Angular CLI 8.x or newer is required.

**Comment by bmwz110** [comment]
> 7.x does not support dynamic import syntax with AOT. Angular CLI 8.x or newer is required.

Thank u very much! this indeed the reason
