### ISSUE TITLE
@angular-devkit/build-ng-packagr:build incompatible with Bazel

### ISSUE THREAD

**Issue by mrmeku** [angular/angular-cli#16182]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Nope

### Description
The `@angular-devkit/build-ng-packagr:build` builder is incompatible with Bazel's directory requirements. 

Bazel requires that the output artifacts of an executable be placed in the same directory (or child directory) of the build target that invoked the executable.

`@angular-devkit/build-angular:browser` supports this paradigm by accepting an `outputPath` flag (see Alex's example repo
https://github.com/alexeagle/prototype_bazel_architect/blob/master/BUILD.bazel#L5 )

Ideally, we'd have a corresponding flag within `@angular-devkit/build-ng-packagr:build` so that bazel can set the output path rather than it being hard coded to a config file.

Additionally, invoking the builder results in an error in trying to resolve `tslib`. It is unclear what is trying to resolve the module and why `rules_nodejs`s linker is not being used to give it the right path information. When I manually provide `tslib` within my local node modules directory to the build target, it continues to try to resolve node modules within my workspace rather than within `@npm`

## 🔬 Minimal Reproduction

I've made an example repo with a build target which invokes the ng-packager builder here: https://github.com/mrmeku/prototype-nx-bazel/blob/master/libs/shared-buildable-lib/BUILD.bazel#L51

Clone the repo and run `bazel build //libs/shared-buildable-lib:build` to reproduce the error.

## 🔥 Exception or Error
<pre><code>
ERROR: EPERM: operation not permitted, open '/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/2/execroot/prototype_nx_bazel/node_modules/tslib/package.json'
An unhandled exception occurred: EPERM: operation not permitted, open '/private/var/tmp/_bazel_mrmeku/2862b1b0ca0f4fada19488b52142c2e3/sandbox/darwin-sandbox/2/execroot/prototype_nx_bazel/node_modules/tslib/package.json'
See "/var/folders/y4/35jxk5nx0tb9lnx7863fx2v80000gn/T/ng-8xnE0A/angular-errors.log" for further details.
</code></pre>

**Comment by alan-agius4** [comment]
@mrmeku, I tried this and it works for me, I wonder if it is a sandboxing issue on Mac

```
yarn run v1.19.1
$ /workspace/prototype-nx-bazel/node_modules/.bin/bazel build //libs/shared-buildable-lib:build
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/gitpod/.cache/bazel/_bazel_gitpod/56afa451bee06ded8b0d2070fc56ad14/command.profile.gz'
INFO: Analyzed target //libs/shared-buildable-lib:build (1394 packages loaded, 105122 targets configured).
INFO: Found 1 target...
INFO: From Action libs/shared-buildable-lib/build:
(node:2709) ExperimentalWarning: The fs.promises API is experimental
(node:2700) ExperimentalWarning: The fs.promises API is experimental
Building Angular Package

** It is not recommended to publish Ivy libraries to NPM repositories **

------------------------------------------------------------------------------
Building entry point '@prototype-nx-bazel/shared-buildable-lib'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @prototype-nx-bazel/shared-buildable-lib

------------------------------------------------------------------------------
Built Angular Package!
 - from: /home/gitpod/.cache/bazel/_bazel_gitpod/56afa451bee06ded8b0d2070fc56ad14/sandbox/processwrapper-sandbox/1/execroot/prototype_nx_bazel/libs/shared-buildable-lib
 - to:   /home/gitpod/.cache/bazel/_bazel_gitpod/56afa451bee06ded8b0d2070fc56ad14/sandbox/processwrapper-sandbox/1/execroot/prototype_nx_bazel/bazel-out/darwin-fastbuild/bin/libs/shared-buildable-lib/build
------------------------------------------------------------------------------
Target //libs/shared-buildable-lib:build up-to-date:
  dist/bin/libs/shared-buildable-lib/build
INFO: Elapsed time: 82.899s, Critical Path: 20.95s
INFO: 1 process: 1 processwrapper-sandbox.
INFO: Build completed successfully, 7 total actions
```

**Comment by alan-agius4** [comment]
Let's take this in #bazel-web-team

**Comment by mrmeku** [comment]
Fixed now!
