### ISSUE TITLE
ng serve not function in determined file

### ISSUE THREAD

**Issue by Mark0liveira** [angular/angular-cli#16183]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

I am debugging my project, but the file I am changing is not recompiling.

It seems that he does not hear the change that occurred in the file

This is happening only in a specific folder, in the rest of the files the command works normally.

## 🔬 Minimal Reproduction

I open my project, and run the ng command, change the file and save, nothing happens.

![image](https://user-images.githubusercontent.com/47141652/68799419-e2b90b80-0636-11ea-944c-26e36974e878.png)

But I change any other file outside the "vehicles" folder and compilation starts normally.

![image](https://user-images.githubusercontent.com/47141652/68799499-0a0fd880-0637-11ea-8501-332a800954fa.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Your global Angular CLI version (8.3.18) is greater than your local
version (6.2.9). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.2.9
Node: 12.13.0
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.12.4
@angular-devkit/build-angular      0.12.4
@angular-devkit/build-optimizer    0.12.4
@angular-devkit/build-webpack      0.12.4
@angular-devkit/core               7.2.4
@angular-devkit/schematics         0.8.9
@angular/cdk                       6.4.7
@angular/cli                       6.2.9
@angular/fire                      5.2.1
@angular/flex-layout               6.0.0-beta.18
@angular/material                  6.4.7
@angular/material-moment-adapter   6.4.7
@ngtools/webpack                   7.2.4
@schematics/angular                0.8.9
@schematics/update                 0.8.9
rxjs                               6.5.3
typescript                         2.9.2
webpack                            4.28.4

</code></pre>

**Anything else relevant?**

IDE VS CODE

**Comment by clydin** [comment]
Angular 6.x is no longer supported. Please consider updating to a more recent version.  Instructions can be found at https://update.angular.io.  If the issue still persists after updating, please open a new issue detailing the problem.

**Comment by Mark0liveira** [comment]
Did not understand, how so no longer supported? It was working until yesterday ...
The global CLI version is the latest ...

**Comment by clydin** [comment]
The Angular support policy can be found here: https://angular.io/guide/releases#support-policy-and-schedule

Older versions can continue to be used but please be aware that support will no longer be provided.
If you are encountering a problem, the issue may have already been corrected in a newer version and it is recommended to update projects when and where possible.
