### ISSUE TITLE
Clarify the purpose of polyfills.ts

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#1618]
https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/ng2/files/__path__/polyfills.ts#L1

The comment right now has no meaning. Explain what this file does and in what case people would want to read/change this file.

**Comment by kylecordes** [comment]
I suspect the comment is just some leftover bit; but it would be nice to get a sense of why the polyfills file is generated in to the project, while many other pieces of machinery are internal to the CLI.

**Comment by filipesilva** [comment]
@kylecordes it's reasonable to want to change these polyfills according to your intended browser environment. You might also use more polyfills for certain environments. 

https://github.com/angular/angular-cli/pull/1633 expands on the `polyfills.ts` file to make it more explicit. You could even remove it and delete the config entry.

**Comment by kylecordes** [comment]
@filipesilva  I suggest documenting that in the README, and it would be a much more useful comment to include at the top of the polyfill file than the current "// Prefer CoreJS over the polyfills above".
