### ISSUE TITLE
tsconfig not respecting paths configuration

### ISSUE THREAD

**Issue by danielfcastro** [angular/angular-cli#16197]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x]serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Probably yes because there is this issue (https://github.com/angular/angular-cli/pull/3831) about the same problem.

### Description

 A clear and concise description of the problem...
I have a tsconfig.json like that
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "@app/*": ["src/app/*"],
      "@environments/*": ["src/environments/*"]
    }    
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

C:\Users\daniel_ferreira\Documents\angular\carrinho_frontend>ng serve
10% building 3/3 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {main} main.js, main.js.map (main) 2.05 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 122 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.09 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
Date: 2019-11-14T17:32:50.117Z - Hash: f19f53d3934423c0c8de - Time: 9762ms

ERROR in src/app/_helpers/fake-backend.ts:6:10 - error TS2305: Module '"C:/Users/daniel_ferreira/Documents/angular/carrinho_frontend/src/app/_models"' has no exported member 'User'.

6 import { User } from '@app/_models';
           ~~~~
src/app/_services/auth_user.service.ts:5:10 - error TS2305: Module '"C:/Users/daniel_ferreira/Documents/angular/carrinho_frontend/src/app/_models"' has no exported member 'User'.

5 import { User } from '@app/_models';
           ~~~~
src/app/_services/authentication.service.ts:7:10 - error TS2305: Module '"C:/Users/daniel_ferreira/Documents/angular/carrinho_frontend/src/app/_models"' has no exported member 'User'.

7 import { User } from '@app/_models';
           ~~~~
src/app/app.module.ts:57:10 - error TS2724: Module '"C:/Users/daniel_ferreira/Documents/angular/carrinho_frontend/src/app/app-routing.module"' has no exported member 'AppRoutingModule'. Did you mean 'appRoutingModule'?

57 import { AppRoutingModule } from './app-routing.module';
            ~~~~~~~~~~~~~~~~

  src/app/app-routing.module.ts:46:14
    46 export const appRoutingModule = RouterModule.forRoot(routes);
                    ~~~~~~~~~~~~~~~~
    'appRoutingModule' is declared here.
src/app/app.module.ts:68:9 - error TS2304: Cannot find name 'appRoutingModule'.

68         appRoutingModule
           ~~~~~~~~~~~~~~~~
src/app/home/home.component.ts:4:10 - error TS2305: Module '"C:/Users/daniel_ferreira/Documents/angular/carrinho_frontend/src/app/_models"' has no exported member 'User'.

4 import { User } from '@app/_models';
           ~~~~
src/app/home/home.component.ts:5:10 - error TS2305: Module '"C:/Users/daniel_ferreira/Documents/angular/carrinho_frontend/src/app/_services"' has no exported member 'UserService'.

5 import { UserService, AuthenticationService } from '@app/_services';
           ~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
![angular-version](https://user-images.githubusercontent.com/4406372/68885116-4b65be00-06f3-11ea-91e3-32a85280e279.PNG)

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by clydin** [comment]
From the error log it also appears that the path mapping is working.
`'@app/_models'` is being turned into `"C:/Users/daniel_ferreira/Documents/angular/carrinho_frontend/src/app/_models"`

**Comment by alan-agius4** [comment]
Closing as this doesn't look like a bug in the CLI.
