### ISSUE TITLE
Option to skip component styles for test build

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular-cli#16192]
# 🚀 Feature request

Provide a way to skip component style processing for unit test builds. 

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

By far our biggest obstacle with Angular is atrocious testing performance. It is **incredibly** slow to build and run all our tests, and anything and everything that could be done to improve the situation would be welcome.

To that end, a flag to skip component style loading for test building would be very welcome. For unit testing, the contents of component styles are irrelevant, but the test build still appears to be running each component's `.scss` file through the style loader.

### Describe the solution you'd like

Add a new flag in `angular.json` build configuration called something like `noComponentStyles` that replaces the standard CLI style loader with a [null loader](https://webpack.js.org/loaders/null-loader/). 

### Describe alternatives you've considered

Switching to React, as our Jest-based testing for React projects runs about 10x faster. I really can't emphasise enough how utterly poisonous the experience of testing is when we try to introduce developers used to other frameworks to our Angular projects.

**Comment by kyliau** [comment]
@jonrimmer Have you got a chance to try out Ivy?

Testing is now much faster under Ivy, and this is an excerpt from the announcement [blog post](https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3):

> Previously, TestBed would recompile all components between the running of each test, regardless of whether there were any changes made to components (for example, through overrides).
> In Ivy, TestBed doesn’t recompile components between tests unless a component has been manually overridden, which allows it to avoid recompilation between the grand majority of tests.
> With this change, the framework’s core acceptance tests are about 40% faster. We would expect users to see their own application test speeds to be around 40–50% faster.

**Comment by jonrimmer** [comment]
No, I am doing 100% React development nowadays. Maybe if Ivy had been delivered three years ago it would have been a game-changer, but as it is... 🤷‍♂️

**Comment by kyliau** [comment]
Closing this, since testing performance has largely been addressed in Ivy as explained in https://github.com/angular/angular-cli/issues/16192#issuecomment-635636217.
