### ISSUE TITLE
Console errors on new projects

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#162]
A couple of console errors seem to be appearing on new projects now:

![image](https://cloud.githubusercontent.com/assets/4172079/12702430/283f0554-c821-11e5-98f9-99537603e726.png)

@jkuri the second one seems to be related to the functionality you were working on, can you have a look?

**Comment by jkuri** [comment]
@filipesilva actually its related to other merge that was made today, me and @cironunes just working on it.. you can join chat on gitter if you have time.
