### ISSUE TITLE
Install angular cli

### ISSUE THREAD

**Issue by halmeida** [angular/angular-cli#16208]
I got an error when install angular cli

Node Version: v10.17.0
NPM Version: 6.13.0

OS Details: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

Error during installation:
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@8.3.19 postinstall /usr/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/@angular/cli/bin/postinstall/script.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @angular/cli@8.3.19 postinstall: `node ./bin/postinstall/script.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @angular/cli@8.3.19 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by filipesilva** [comment]
That's an odd error.... the closest I've seen is permissions related errors as described in https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally. Maybe it's related though. Can you try that?

**Comment by Alterock13** [comment]
I have the same exact error after trying to install angular cli @8.3.19 and I must admit I don't know what could cause this.

**Comment by halmeida** [comment]
> That's an odd error.... the closest I've seen is permissions related errors as described in https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally. Maybe it's related though. Can you try that?

I just tried and run npm install -g @angular/cli
and I think it works!!! Thanks @filipesilva 
---------------
_/home/halmeida/.npm-global/bin/ng -> /home/halmeida/.npm-global/lib/node_modules/@angular/cli/bin/ng_

_> @angular/cli@8.3.19 postinstall /home/halmeida/.npm-global/lib/node_modules/@angular/cli_
_> node ./bin/postinstall/script.js_

_+ @angular/cli@8.3.19_
_added 250 packages from 186 contributors in 6.509s__
----------------------


However when I run **ng --help** (see result below).
_Command "ng" not found, but can be installed with:_

_apt install ng-common_
_Please ask your administrator._

Then run **sudo apt install ng-common** (see result below).
_Reading package lists... Done_
_Building dependency tree_       
_Reading state information... Done_
_ng-common is already the newest version (1.5~beta1-4)._
_0 upgraded, 0 newly installed, 0 to remove and 66 not upgraded._

And run againg **ng--help**, still  command 'ng' not found, but can.....

**Comment by clydin** [comment]
Errors such as those generally indicate either a misconfigured PATH environment variable or a permission/ownership issue related to the Node.js install.  This is common when mixing installation and use between root and a user account.

**Comment by halmeida** [comment]
at last, I found the solutions.

See steps below:
1. Install nodejs and npm, follow the steps provided in the link:  https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/
2. Install angular cli by executing this command: **_npm install -g @angular/cli_**
2.1 Run **ng --version** - Disregard suggested steps below after running it.
------------------------
_Command "ng" not found, but can be installed with:_

_apt install ng-common_
_Please ask your administrator._
------------------------

INSTEAD run this command: **_alias ng="~/.npm-global/lib/node_modules/@angular/cli/bin/ng"_**
Here is the ng directory in my case. So kindly check where the ng located in your local.

Then run **_ng -- version_**
