### ISSUE TITLE
Unable to copy assets: ENOENT: no such file or directory, mkdir 'c:\xxx\assets\i18n'

### ISSUE THREAD

**Issue by Marcelh1983** [angular/angular-cli#16202]
- [x] build

### Description
If the assets folder has subdirectory, the build fails
## 🔬 Minimal Reproduction
`ng new test`
add a json file to assets\i18n
`ng build --prod`
## 🔥 Exception or Error
<pre><code>
Unable to copy assets: ENOENT: no such file or directory, mkdir 'c:\xxx\assets\i18n'
</code></pre>

## 🌍 Your Environment
Windows
@angular/cli rc.2

**Comment by clydin** [comment]
Can you provide your Node.js version?  10.13 or higher is required.

**Comment by Marcelh1983** [comment]
I had version 10.10 installed. Updating node.js solved the issue. Thanks for the quick support!
