### ISSUE TITLE
Json schema validation does not fail when it should

### ISSUE THREAD

**Issue by ZachJW34** [angular/angular-cli#16217]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] schematic

### Is this a regression?

No

### Description

Schematic schema validation should match [json schema documentation](https://json-schema.org/understanding-json-schema/reference/conditionals.html). Creating a schematic with a similar schema structure as the example and passing in `{street_address: "24 Sussex Drive", country: "Canada", postal_code: "10000"}` should fail with error:
```
"Invalid: data.postal_code should match pattern \"[A-Z][0-9…A-Z] [0-9][A-Z][0-9]\", data should match \"else\" schema"
```

## 🔬 Minimal Reproduction
* `schematics blank --name=hello-world`
* `cd hello-world`
* `npm i`
* `touch src/hello-world/schema.json` and copy:
   ```
   {
     "$schema": "http://json-schema.org/schema",
     "id": "hello-world",
     "type": "object",
     "properties": {
       "street_address": {
         "type": "string"
       },
       "country": {
         "enum": ["United States of America", "Canada"]
       }
     },
     "if": {
       "properties": { "country": { "const": "United States of America" } }
     },
     "then": {
       "properties": { "postal_code": { "pattern": "[0-9]{5}(-[0-9]{4})?" } }
     },
     "else": {
       "properties": { "postal_code": { "pattern": "[A-Z][0-9][A-Z] [0-9][A-Z][0-9]" } }
     }
   }
   ```
* `npm run build`
* `schematics .:hello-world --street_address "24 Sussex Drive" --country Canada --postal_code 10000`

## 🌍 Your Environment
Angular CLI: 7.3.9
Node: 10.16.3
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.13.9 (cli-only)
@angular-devkit/core         8.3.19
@angular-devkit/schematics   8.3.19
@schematics/angular          7.3.9 (cli-only)
@schematics/update           0.13.9 (cli-only)
rxjs                         6.4.0
typescript                   3.5.3

**Comment by alan-agius4** [comment]
Hi @ZachJW34,

The problem seems to be that in your `collection.json` the schema is not referenced in the `collections.json`

``` json
{
  "$schema": "../node_modules/@angular-devkit/schematics/collection-schema.json",
  "schematics": {
    "hello-world": {
      "schema": "./hello-world/schema.json",
      "description": "A blank schematic.",
      "factory": "./hello-world/index#helloWorld"
    }
  }
}
```
