### ISSUE TITLE
WebPack: jquery + bootstrap-sass

### ISSUE THREAD

**Issue by Daredzik** [angular/angular-cli#1622]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Debian 8.5

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.11-webpack
node: 6.2.2
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

> npm install --save jquery
> npm install --save bootstrap-sass

now in pollyfils.ts add:

>     import 'jquery';
>     import 'bootstrap-sass/assets/javascripts/bootstrap';

`ng serve`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
in bundled js, i can find jquery lib, but in console i get `'Error: Bootstrap's JavaScript requires jQuery'`

5. Mention any other details that might be useful.
i try the way to add in main.ts 
`import $ from 'jquery';` or `import * as jQuery from 'jquery';` but nothing change.

Any ideas ?

**Comment by choucry13** [comment]
@Daredzik  try this : 
npm install --save @types/jquery
npm install --save jquery
use import * as jQuery from 'jquery' in your typescript file. @types works with the typescript@2.0

**Comment by Daredzik** [comment]
@choucry13 
nope didn't work.

For now i include jquery in index.html file and store it in public dir.

**Comment by lbecker34** [comment]
@Daredzik  Not sure what your reason is for using the bootstrap/jquery combination. This angular2 package has everything you need to use bootstrap with Angular2. https://github.com/valor-software/ng2-bootstrap

**Comment by filipesilva** [comment]
@Daredzik the ability to add global javascript (like jquery) is currently missing. This is something we're actively working on and probably the biggest priority at the moment.

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/1717, which better captures this feature.
