### ISSUE TITLE
ng lint succeeds when tslint fails, and other default linting misconfiguration (vscode)

### ISSUE THREAD

**Issue by Masterxilo** [angular/angular-cli#16231]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No, this never worked AFAIK.

### Description
tslint and ng lint should behave the same.

In general, ng build and ng serve should fail when code that tslint shall consider as {"severity": "error"} is encountered.

I lost 3 hours first isolating a bug caused by a shadowed variable, then trying to make my build always fail and my IDE report "no-shadowed-variable" as an error.

After I put the line
```
"no-shadowed-variable": {"severity": "error"}
```
in the ./tsconfig.json file, all my tools should recognize and report this error always.

Currently they don't. ng lint is one of them

## 🔬 Minimal Reproduction
<pre><code>
ng new tslint-errors-ng-vscode
</code></pre>
Then append to app.component.ts the following
<pre><code>
function f(key: string) {
    const o = {hello: 0};
    Object.keys(o).forEach((key: string) => {console.log(key)});
}

f("world")
</code></pre>

This code demonstrates shadowing. Does it do what we want? We should probably have used a different variable name.
Let's assume we had a bug caused by shadowing.
Now we want to make sure that never happens again, so we want the build to fail if we ever rely on shadowing anywhere.

So we put in tslint.json under rules:

```
"no-shadowed-variable": {"severity": "error"}
```

But damn it:
Our IDE still shows it as a warning:
![image](https://user-images.githubusercontent.com/2378665/69176436-0207db00-0b06-11ea-8cc4-0eb7d439e684.png)
aha, the vscode team messed up: https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/122
so we configure in settings json "tslint.alwaysShowRuleFailuresAsWarnings": false

F*** now everything is an error:
![image](https://user-images.githubusercontent.com/2378665/69176505-1e0b7c80-0b06-11ea-927d-20fcf80f030f.png)

Aha, the angular team messed up: The didn't put any "defaultSeverity" in ./tslint.json so let's do that:

```
"defaultSeverity": "warning"
```

After restarting the IDE (because we live in the fantastic time where some changes have immediate effect and some require a restart and no one know which require a restart...) it behaves properly
![image](https://user-images.githubusercontent.com/2378665/69176641-6460db80-0b06-11ea-99d2-bb71ef71704b.png)
Now lets see the CLI:

```
tslint --project . --quiet
```
properly reports only the ERRORs
![image](https://user-images.githubusercontent.com/2378665/69176711-8b1f1200-0b06-11ea-96cc-6fcc69788a72.png)

```
ng lint
```
detects the error, but happily reports that "All files pass linting.". **Clearly a BUG.**
![image](https://user-images.githubusercontent.com/2378665/69176820-bc97dd80-0b06-11ea-8e33-d1bf75f99cc7.png)

ng serve succeeds - **arguably it should treat linting errors just as much as errors as typechecking errors!**

**ng build succeeds - yay, "errors" in tslint.json officially means nothing to angular :(**

## 🔥 Exception or Error
<pre><code>
All files pass linting.
</code></pre>
When there is  a linting ERROR.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.19
Node: 11.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.19
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cdk                       8.2.3
@angular/cli                       8.3.19
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.19
@schematics/update                 0.803.19
rxjs                               6.5.2
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**
Related Issues:
* https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/122
* https://github.com/angular/angular-cli/issues/9750
* https://github.com/angular/angular-cli/issues/10013
* https://github.com/angular/angular-cli/issues/7185

**Comment by clydin** [comment]
The workspace shown above has two projects:
* `tslint-errors-ng-vscode` -- this is failing with the variable shadow error
* `tslint-errors-ng-vscode-e2e` -- this is passing

The standalone E2E project is an artifact from an earlier version of the CLI and a project generated by 8.3.19 will not have a standalone E2E project.  The E2E testing has been incorporated into the main project.

**Comment by alan-agius4** [comment]
With regards to your point that lint errors should fail `ng serve` and `ng build`, IMHO Is not desirable as during development, a developer will usually make “style” related errors especially during debugging and experimenting and those should be totally acceptable and failing a build for lint/style related errors would be a bad developer experience apart from reducing developer productivity as they will need to go back and forth to fix style related errors.

IMO,  Lint should be used as a precommit step or/and as a CI check which if that fails will make the PR unmergable.

**Comment by Masterxilo** [comment]
I kindly disagree. tslint has severities warning and error. If desired, a developer or automated tooling could set the linting severities to warning instead of error during development. But at least ng lint should fail when there are errors. 

Otherwise ng lint is not useful as an automateable cli tool, there would be no place in having it integrated into ng in the firat place.

Linting *errors* should be strictly distinguished from linting *warnings*

**Comment by Masterxilo** [comment]
In an effort to make the most out of tooling and automated best practice enforcement, many good developers treat all warnings as error and only very carefully ignore them

**Comment by alan-agius4** [comment]
>But at least ng lint should fail when there are errors.

It does, ng lint will exit with a non zero error code when there is a lint error.

> Linting errors should be strictly distinguished from linting warnings

When there are no errors, ng lint is not exited with a non zero error code but will when there is a lint error.

**Comment by clydin** [comment]
As mentioned above, the lint command will run against each project within the workspace and provide a separate output for each project.  In the output provided in the screenshot, the `tslint-errors-ng-vscode` project is indeed failing and being reported as such.  The second (and last) project, however, is succeeding hence the line indicating the files passed.  The error code for the command will also represent the total success or failure of the command for all projects checked.  The error code is useful as well if it is indeed desired to not build if lint fails (`ng lint && ng build`).

**Comment by alan-agius4** [comment]
Closing as per above, as it doesn't seem to be a bug here.

**Comment by IgorMinar** [comment]
@Masterxilo I just wanted to follow up on your original issue description and point out that it reflects a lot of frustration and is borderline aggressive.

This might not have been your intention, but I wanted to let you know that that's how it was received. In the future please try to stay away from using profanity, verbal attacks, or negative comments directed at individuals or groups of people.

The issue tracker is a place for collection of factual information. Your messages are read by many people, some of which might feel negatively affected by your choice of words, and in return might be less willing to help you with your issue.

Lastly, please keep in mind that just as many of our other communication channels, the GitHub issue tracker is governed by our code of conduct policy: https://github.com/angular/code-of-conduct

Thanks for understanding!
