### ISSUE TITLE
Extremely slow es5 generation adding ~40min to a 2min es2015 build with 8.x

### ISSUE THREAD

**Issue by CaselIT** [angular/angular-cli#16238]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Is this a regression?

I've updated from angular cli 8.2.2 to 8.3.19. I'm experiencing extremely slow es5 generation, more than 40min, on a 2min es2015 build project.
The command is the default `ng build --prod`
Before:
es2015: Date: 2019-11-19T15:25:55.426Z - Hash: 6c35a01295520babc484 - Time: 148057ms
es5: Date: 2019-11-19T15:28:43.552Z - Hash: 0fd8da57b70a110eb175 - Time: 167641ms
<details>
<summary> Output of ng --version </summary>

```
$ ng --version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    
Angular CLI: 8.2.2
Node: 10.16.3
OS: linux x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.1.3
@angular/cli                      8.2.2
@angular/material                 8.1.3
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.38.0
```
</details>
After:
Date: 2019-11-19T16:28:22.217Z - Hash: 5d634a67585b345c8c54 - Time: 2624975ms
<details>
<summary> Output of ng --version </summary>

```
$ ng --version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    
Angular CLI: 8.3.19
Node: 10.16.3
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cdk                      8.2.3
@angular/cli                      8.3.19
@angular/material                 8.2.3
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

</details>

### Description

I've tried disabling the es5 generation, by changing the `browserslist` file and the compilation time comparable with the previous version
Date: 2019-11-19T20:25:10.213Z - Hash: fbbc4140d56be9279818 - Time: 147941ms

Also visually the compilation of the es2015 build finishes, the files as generated in about 2 minutes, then it sits in `Generating ES5 bundles for differential loading...` for about to 40 minutes.
I don't think it's a node memory related problem since the process that takes 40 minutes uses about 100MB of ram

## 🔬 Minimal Reproduction

I cannot share the project code, these are the dependencies I'm using.
<details>
<summary> Dependencies </summary>

```json
  "dependencies": {
    "@amcharts/amcharts4": "^4.7.10",
    "@amcharts/amcharts4-geodata": "^4.1.9",
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "amcharts3": "^3.21.15",
    "apollo-angular": "^1.8.0",
    "apollo-angular-link-http": "^1.9.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "canvas": "^2.0.0",
    "d3": "^5.14.1",
    "graphql": "^14.5.8",
    "graphql-tag": "^2.10.1",
    "hammerjs": "^2.0.8",
    "jsdom": "^13.0.0",
    "json5": "^2.1.1",
    "numeral": "^2.0.6",
    "rxjs": "~6.5.3",
    "tslib": "^1.10.0",
    "xmldom": "^0.1.27",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.19",
    "@angular/cli": "~8.3.19",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/amcharts": "^3.21.2",
    "@types/d3": "^5.7.2",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/json5": "0.0.30",
    "@types/node": "~12.12.9",
    "@types/numeral": "^0.0.26",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ts-node": "~7.0.1",
    "tslint": "~5.20.1",
    "typescript": "~3.5.3"
  }
```

</details>

## 🌍 Your Environment
<pre><code>
$ ng --version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    
Angular CLI: 8.3.19
Node: 10.16.3
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cdk                      8.2.3
@angular/cli                      8.3.19
@angular/material                 8.2.3
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

I'm not sure if the build command can output some diagnostic information that I can share which would help.

**Comment by CaselIT** [comment]
I've tried re installing angular-cli 8.2.2 leaving all the other packages the same and the times are as expected.
Date: 2019-11-20T11:06:33.607Z - Hash: 4e1c703c5105bd008a68 - Time: 141814ms
<details>
<summary> Output of ng --version </summary>

```
$ ng --version
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    
Angular CLI: 8.2.2
Node: 12.13.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.802.2
@angular-devkit/build-optimizer   0.802.2
@angular-devkit/build-webpack     0.802.2
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.2.3
@angular/cli                      8.2.2
@angular/material                 8.2.3
@ngtools/webpack                  8.2.2
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.38.0
```

</details>

Is there a way to enable the old build mode in angular 8.3.x ?

**Comment by alan-agius4** [comment]
Hi @CaselIT, do you have a reproduction that we can take a look at?

Couple of other questions;
- Is this issue still persistent with `"@angular/cli": "^9.0.0-rc.2",` and `"@angular-devkit/build-angular" : "~0.900.0-rc.2"`?
- Do you have sourcemaps enabled?

**Comment by CaselIT** [comment]
Sadly I do not have a reproduction repository that I can share at this time.
- I do not have source maps enabled in the production build.
- I have tried v9, but the build fails since it requires some changes to the current code to make material and typescript.

is there any other way that I can help you with, other than creating a reproduction that I can share?




the cn

**Comment by alan-agius4** [comment]
Can you kindly disable sourcemaps? In version 8, there was a bug which caused sourcemaps to be processed multiple times.

This has been fixed in version 9 via https://github.com/angular/angular-cli/pull/16126

**Comment by CaselIT** [comment]
They are already disabled in the production build.
I can attach the angular.json confuratuon if it helps

**Comment by alan-agius4** [comment]
Apologies I misread your previous comment.

To opt out of the new behaviour you can do as described here https://github.com/angular/angular-cli/issues/16225#issuecomment-555525767

Sharing the angular.json won’t be of much help in this case.

For version 9 there are several performance improvements related to differential loading and downleveling however without a reproduction without say for sure that the problem you are experiencing has been tackled.

**Comment by CaselIT** [comment]
Thanks, I'll try to opt out of the new behaviour for now and try to find a way to generate a reproducible example.

Thank you for your support so far

**Comment by alan-agius4** [comment]
@CaselIT, you are welcome

I am going to close this issue for now. 

If you manage to create a reproduction and the issue persists after updating to Angular 9. Kindly feel free to open a new one :)

**Comment by CaselIT** [comment]
Ok, will do.

I've tried and the workaround seems to work.

**Comment by CaselIT** [comment]
I've just retried after a couple of weeks and the issue seems to have resolved itself.
I made some changes to the used packages, not related with this issue and now it seems to work.

The angular packages and cli are the same
