### ISSUE TITLE
ERROR in Illegal state: Could not load the summary for directive CdkAccordion 

### ISSUE THREAD

**Issue by booleanVirus** [angular/angular-cli#16249]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Not able to build application and it's libraries

## 🔬 Minimal Reproduction

ng build --prod

## 🔥 Exception or Error
<pre><code>

C:\J\NodeJS\node.exe C:\J\NodeJS\node_modules\npm\bin\npm-cli.js run build --scripts-prepend-node-path=auto

> axa-dep-fe-angular@1.5.2 build C:\Users\DYKI724\Projects\idfeweb
> ng build --prod

WARNING in Invalid animation value at 4092:34. Ignoring.

WARNING in Invalid animation value at 4091:34. Ignoring.

ERROR in Illegal state: Could not load the summary for directive CdkAccordion in C:/Users/DYKI724/Projects/idfeweb/node_modules/@angular/cdk/accordion/typings/index.d.ts.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! axa-dep-fe-angular@1.5.2 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the axa-dep-fe-angular@1.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DYKI724\AppData\Roaming\npm-cache\_logs\2019-11-21T10_50_29_874Z-debug.log

Process finished with exit code 1

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.19
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.19
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cdk                       8.2.3
@angular/cli                       8.3.19
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.19
@schematics/update                 0.803.19
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by marinvirdol** [comment]
I am experiencing the same issue.

What I noticed is that it appears after I run the following command `ng update @angular/material`

**Comment by booleanVirus** [comment]
Issue fixed after consulting the Angular update guide.

> Instead of importing from @angular/material, you should import deeply from the specific component. E.g. @angular/material/button. ng update will do this automatically for you

Changing this "import { MatDialog} from '@angular/material" to this "import { MatDialog} from '@angular/material/dialog" fixed it.
