### ISSUE TITLE
Support for builder before/after hooks

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#16247]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ x] build
- [x ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Maybe somebody already asked this but are there any plans in terms of extensibility of CLI build tasks? 

1. I understand right now the recomended way to extend cli is to write schematics to create some custom generate command. Or even override existing ones like some of the cli are doing it.
2. You are also able to use `builder API` to really change behavior or create new for the existing commands (build, serve, test,..)
3. if I want to extends existing build process, then I can extends `browser build` `export default createBuilder` where I can call existinb fn `buildWebpackBrowser as executeBrowserBuilder`, and then do some my own logic

- But what I am strugling with or I dont see a solution, how do I easily extend and alter building process of existing application that might already be using some builder API. 

Current solution does not scale, as you can extend `builder API` and replace application's configuration for your builder, but this would not work if they are already using some custom builder API. So replace is not really an option. 

What you need some Injection points, to be able to register your tasks before, after each task. I know ngx-build-plus is trying to do something similar, but again if we use ngx-build-plus and project has already some builder it will not work. 

Like Maven, Gradle,....

Any pointers ?

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by filipesilva** [comment]
It's true that builders don't compose very well right now. We've talked in the past about having before/after hooks, and others of that kind. But it's not something that has gained much traction yet and we have no concrete plans for an implementation.

**Comment by fkolar** [comment]
I am sure whoever works in enterprise have these needs and right now people have different workarounds  or use 3th-party projects like the one from the @manfredsteyer.

All comes down to extensibility. And I understand if there is no real demand, you have no urgency to take this to the next level. Can we keep this open until you guys decide, "No we dont want to support it. " ;-)

**Comment by filipesilva** [comment]
Sure, let me just change the title to mention the hooks.

**Comment by alan-agius4** [comment]
This seems to be related to https://github.com/angular/angular-cli/issues/11787. 

Let's continue tracking it over there.
