### ISSUE TITLE
build-angular not working on ubuntu due to outdated node-sass dependency

### ISSUE THREAD

**Issue by sabahang** [angular/angular-cli#16257]
On Ubuntu I'm not able to use @angular-devkit/build-angular dependency because of an outdated nested dependency as per the following issue report:
https://github.com/sass/libsass/issues/2883

**Comment by clydin** [comment]
As of version 8.0, the Angular CLI no longer uses node-sass and removes the potential of this issue from occurring.

Please considering updating to the latest version of the CLI (currently 8.3.19).

**Comment by sabahang** [comment]
Problem is that using latest version gave me another error:
https://stackoverflow.com/questions/56393158/errors-data-path-buildersapp-shell-should-have-required-property-class

but I got rid of it using [this ](https://stackoverflow.com/a/56428110/1075499) answer using version 0.13.9
