### ISSUE TITLE
passing an absolute path to url(..) causes an error

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#16251]
```
...
return (tree,context){
 var source = url( __dirname + "/files" ); //using full path here causes an Error,
 var template = apply( source , [...] )

  return schematics.chain([
    schematics.branchAndMerge(
      schematics.chain([schematics.mergeWith(template, strategy)])
    )
  ]);

//->Error: Unknown Protocol on url "[object Object]".
}
```

note that I don't like to use a relative path, because I want to use a function witch imported from another file  to create the template, so the relative path will refer to a wrong location.

**Comment by alan-agius4** [comment]
Thanks for opening this issue. However this is not supported right now and overall we do not see how this would be useful in general.

Can you please provide us with a more concrete use-case maybe with some code snippets of what you are trying to do?

Thanks.

**Comment by alan-agius4** [comment]
Closing as the author of the issue never came back to us.

if the problem persists please feel free to open a new issue.
