### ISSUE TITLE
Live Reload not working with --basehref

### ISSUE THREAD

**Issue by mucbits** [angular/angular-cli#16266]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] lint
- [ ] update
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 0.803.13

### Description
Live Reload stopped working after this change:
https://github.com/angular/angular-cli/commit/5260bbb9a3d17aefb90bcf1b660e252996cf68df#diff-6c0b312b8bd33db747e50549a66f7ab1

`https://localhost:xxxx/admin/sockjs-node/info` returns 404

while `https://localhost:xxxx/admin/admin/sockjs-node/info` exists.

## 🔬 Minimal Reproduction
ng serve app --base-href /admin/  --deploy-url /admin/

## 🔥 Exception or Error
`https://localhost:xxxx/admin/sockjs-node/info` returns 404

**Comment by clydin** [comment]
I am unable to replicate the issue.  Tried with a new project using the latest version of 8.x (8.3.19)
```
npx @angular/cli@8 new livereload-basehref
cd livereload-basehref
ng serve --base-href /admin/ --deploy-url /admin/
```

**Comment by mucbits** [comment]
I'm using a .Net Core backend with UseAngularCliServer for development, the project I'm working on is rather large with 3 Angular app. Anyway, in the end it does only run 3 times ng serve in the background and proxy all requests to the right instance.

For the root App Live Reload is working fine, the other two apps with the additional path mapping it is not working anymore.

I'll try to reproduce it on a smaller test project.
