### ISSUE TITLE
I am using proxy config to connect my spring backend api... its working fine when in localhost:4200 but its not calling when deploying it  in server ...

### ISSUE THREAD

**Issue by GiridharanGAVS** [angular/angular-cli#16264]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Material issues at: https://github.com/angular/material2/issues/new

For the time being, we keep Angular Material issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by GiridharanGAVS** [comment]
why it is closed? @alan-agius4

**Comment by alan-agius4** [comment]
Kindly fill the issue description.
