### ISSUE TITLE
Error: The "@ngtools/webpack" package installed is not compatible with this version of "ngc-webpack"

### ISSUE THREAD

**Issue by khteh** [angular/angular-cli#16278]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
I have the following in package.json:
```
"dependencies": {
    "@ngtools/webpack": "^8.3.19",
},
"devDependencies": {
    "@angular/cli": "^8.3.19",
    "ngc-webpack": "^4.1.2"
}
```
During build, I get the following error:
## 🔥 Exception or Error
<pre><code>

Error: The "@ngtools/webpack" package installed is not compatible with this version of "ngc-webpack"
</code></pre>

## 🌍 Your Environment
<pre><code>

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.19
Node: 13.0.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.7.2
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by khteh** [comment]
https://github.com/shlomiassaf/ngc-webpack/issues/50

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI.
