### ISSUE TITLE
Spec (tests) maintenance aid

### ISSUE THREAD

**Issue by gparlakov** [angular/angular-cli#16288]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 The CLI has scaffolding spec file capability and along with that is missing the functionality to:
 * **create** spec for an existing component 
 * **update** existing spec file ("read" deps out of class-under-test and scaffold test deps in the spec file)

### Describe the solution you'd like
Creating and maintaining tests is a chore. And it seems that gives one more reason people not to do it. But we can help alleviate some of that and have people writing the tests and not the boilerplate.

Given the class under test file CLI could : (`ng g spec components/my.component.ts`)
 * read the dependencies - using Typescript and getting names and types of deps
 * generate spec file - using schematics 
 * update existing spec files - using a mixture of the above two

An implementation can be found here https://github.com/gparlakov/scuri (VS Code extension https://github.com/gparlakov/scuri-code). It supports: 
 * create spec for existing Typescript class
 * update existing spec  (including CLI generated spec)
 * generate autospy function to aid in mocks - [here](https://github.com/gparlakov/scuri/blob/master/src/autospy/files/jasmine/auto-spy.ts.template)

### Describe alternatives you've considered
After talking with @mgechev among other people, I'd like to start a discussion and see:
 * is this is as big of a problem as I see it?
 * do we fix it "inside" of CLI or "outside"?

**Comment by alan-agius4** [comment]
Hi @gparlakov, this is somewhat related to the following https://github.com/angular/angular-cli/issues/14872

I suggest that we close this issue and continue the discussion over there. Maybe even adding the details you mentioned here.

Thanks.

**Comment by mgechev** [comment]
I can see this feature valuable. My concern is that it may not work 100% of the time. It's not trivial finding the exact location where we need to insert the new dependencies for any arbitrary app. At the same time, we already a have similar situation around the lazy route generator. So far we haven't heard any complaints.

There's some overlap with #14872. If we are going to move the discussion there we should probably rename the issue to something more abstract so more people can find the discussion.

**Comment by gparlakov** [comment]
@mgechev Indeed having it work for 100% of cases is a rabbit hole. It seems that handling the 90% case would help a lot of people writing boilerplate.

IDE-feature-wise - agree 100% - hence the VS Code plugin - https://marketplace.visualstudio.com/items?itemName=gparlakov.scuri-code

**Comment by FDIM** [comment]
@gparlakov I completely agree that handling 90% of the cases is more than enough.
I've done a separate [npm package](https://www.npmjs.com/package/jasmine-unit-test-generator) that creates a spec file based on typescript class and mocks all dependencies. This alone is a huge time saver for the people I work with. But most importantly ability to extend on how individual dependencies are mocked, a bit messy but you only have to do this job once :D

After having it and actively using it for at least half a year, we in the team kind of agree that update would be nice to have, but not really needed. Technically it's doable as long as the "header" is not changed too much.

As for CLI versus IDE, I'd argue that CLI would be a bit better place. At least this way it could be documented as defacto standard when developing with Angular. Aside of that we have a 50/50 split between vscode and webstorm, so vscode plugin only solves the issue to half the people

**Comment by kyliau** [comment]
This has been discussion quite extensively in https://github.com/angular/angular-cli/issues/14872 and https://github.com/angular/angular-cli/issues/7727, and the conclusion made in https://github.com/angular/angular-cli/issues/7727#issuecomment-580424412 is that such feature could easily be implemented in third party schematics / IDE extension, and does not have to be in Angular CLI.
