### ISSUE TITLE
Using build works, build --prod fails with intl-messageformat

### ISSUE THREAD

**Issue by moodyjmz** [angular/angular-cli#16289]
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

I've added intl-messageformat to the project and copied and pasted their example code. serve and build work fine. Build --prod works fine with Chrome, however build --prod with the `optimisation: true` fails in IE (and in Chrome if forced to use the es5 files).

I have added `commonChunk: false` to the angular.json build config. And added the intl-pluralrules polyfill to the polyfills file.

```
    "intl-messageformat": "^7.6.0",
    "intl-pluralrules": "^1.1.1"
```
I've created a repo here 

https://stackblitz.com/edit/angular-p1cyli

## 🔬 Minimal Reproduction

`ng build --prod`

serve the dist project in IE11 and look for the error in the console.

## 🔥 Exception or Error

IE11
<pre><code>
SCRIPT5007: Object expected
main-es5.a51589e5bc4634a245a6.js (1,3570)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.19
Node: 12.13.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by moodyjmz** [comment]
Looking further at this, including the @formatjs libs directly from their dist builds correctly.

From 

```js
import IntlMessageFormat from "intl-messageformat";
import { supportedLocales } from '@formatjs/intl-utils';
```

to

```
import IntlMessageFormat from "intl-messageformat/dist/core.js";
import supportedLocales from '@formatjs/intl-utils/dist/resolve-locale.js';
```

I will mention this on @formatjs.

I'll levea

**Comment by alan-agius4** [comment]
Can you check if this is still reproducible with version 9?

You can update using;
```
ng update @angular/core @angualar/cli --next
```

**Comment by moodyjmz** [comment]
Yes, it is still an issue

```
main-es5.607632b5ecce60f3d54d.js:1 Uncaught TypeError: Sf is not a function
    at main-es5.607632b5ecce60f3d54d.js:1
    at Module.zUnb (main-es5.607632b5ecce60f3d54d.js:1)
    at a (runtime-es5.06dc6a1139ed7db15522.js:1)
    at Object.0 (main-es5.607632b5ecce60f3d54d.js:1)
    at a (runtime-es5.06dc6a1139ed7db15522.js:1)
    at t (runtime-es5.06dc6a1139ed7db15522.js:1)
    at Array.r [as push] (runtime-es5.06dc6a1139ed7db15522.js:1)
    at main-es5.607632b5ecce60f3d54d.js:1
(anonymous) @ main-es5.607632b5ecce60f3d54d.js:1
zUnb @ main-es5.607632b5ecce60f3d54d.js:1
a @ runtime-es5.06dc6a1139ed7db15522.js:1
0 @ main-es5.607632b5ecce60f3d54d.js:1
a @ runtime-es5.06dc6a1139ed7db15522.js:1
t @ runtime-es5.06dc6a1139ed7db15522.js:1
r @ runtime-es5.06dc6a1139ed7db15522.js:1
(anonymous) @ main-es5.607632b5ecce60f3d54d.js:1
```

**Comment by moodyjmz** [comment]
just wondering if there is any movement on this?

**Comment by moodyjmz** [comment]
NG is now using [webpack 4.41.4](https://github.com/webpack/webpack/releases/tag/v4.41.4) since [NG CLI  8.3.21](https://github.com/angular/angular-cli/releases/tag/v8.3.21) and changes some module handling, this issues appears resolved for me so I will close it.
