### ISSUE TITLE
support multiple i18n under the same build pipeline

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular-cli#16292]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 A clear and concise description of the problem or missing capability...

When supporting multiple languages in angular, we have to build multiple times, it would cost quite a long time with middle size applications.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Could we build multiple langs at the same time with the latest cli now? since the translation part was moved to the end of the build pipeline, and there is a new configuration in angular.json, according to the integration test here

`ng build --configuration production,fr`

https://github.com/angular/angular/tree/master/integration/cli-hello-world-ivy-i18n

### Describe alternatives you've considered

support some commands like `ng build --configuration production,fr,de`

**Comment by elvisbegovic** [comment]
hmm if i understand...  this is already possible afaik, by adding new configuration like :
`"myTranslateConfig": {"localize": ["fr","de","en","it"]}` 
And run `ng build --prod --c production,myTranslateConfig` 

- `production` should output build with `$localize` tags

- `myTranslateConfig` should translate all your locales from files you specify except `sourceLocal` which simply remove `$localize` from default build. 

fyi: I consider you are on rc3 and already run `ng update @angular/cli --migrateOnly --from=8` to get  new i18n object config in `angular.json` under your project: 
```
"i18n": {
  "sourceLocale": "fr",
    "locales": {
      "de": "./locale/de.xtb", 
      "en": "./locale/en.xtb", 
      "it": "./locale/it.xtb"
  }
},
```

> If you try rc3 right now, there is some bugs regarding new i18n you should manually fix, I recommend wait next release to get

@clydin can correct me if im wrong

**Comment by clydin** [comment]
That is correct.  Thank you @elvisbegovic.

Also of note is once you setup the `i18n` configuration for a project you can run `ng build --prod --localize` to generate outputs for all the defined locales without the need to add the configuration.
Documentation for this is currently in review and will be available for the final 9.0 release.

**Comment by clydin** [comment]
Additionally, the `--configuration production,fr,de` option syntax is to support configuration composition.  This essentially merges the options of each of the specified configurations.  The later specified configurations take priority over the earlier.

**Comment by clydin** [comment]
Several documentation updates have now landed and the update guide can be found here: https://v9.angular.io/guide/i18n

Suggestions and comments for improvement are welcome.
