### ISSUE TITLE
Add a command argument to disable the analytics prompt

### ISSUE THREAD

**Issue by BenDevelopment** [angular/angular-cli#16295]
# 🚀 Feature request

### Description
It would be very nice to have a command parameter to disable ng analytics prompt. In Microsoft Visual Studio Team Foundation Server there is no way to define environment variable relative to npm install command scope. I've now no solution to setup CI for my Angular project in Microsoft Visual Studio Team Foundation Server.

#### What I've tried:
[Official solution](https://github.com/angular/angular-cli/blob/f8fe4b0ee82d880396119a2594f3cee8dadb2947/docs/design/analytics.md#disabling-usage-analytics): 
 * using ng analytics off (or changing the global configuration file yourself). This is the same as answering "No" to the prompt.
> I cannot use ng analytics off command since ng is not installed on my CI environment.
 * There is an NG_CLI_ANALYTICS environment variable that overrides the global configuration. That flag is a string that represents the User ID. If the string "false" is used it will disable analytics for this run. If the string "ci" is used it will show up as a CI run (see below).
> I can set NG_CLI_ANALYTICS to `'false'` on my server but in Microsoft Visual Studio Team Foundation Server, the npm install task seems to be in another environment scope.

### Describe the solution you'd like
It would be nice to add a command argument to disable this prompt, or maybe to remove this prompt and add a variable in angular settings to enable ng analytics.
At this point, I'm hard stuck. I cannot setup my CI environment and it bothering my client.

### Describe alternatives you've considered
I have no alternative at this point.

**Comment by alan-agius4** [comment]
H @BenDevelopment,  You can use `ng analytics project off` or `ng analytics project on` locally and commit the changes in `angular.json`

**Comment by BenDevelopment** [comment]
Thank you @alan-agius4 . It seems to work ! (It's missing in the doc btw)
