### ISSUE TITLE
HMR not working properly

### ISSUE THREAD

**Issue by RomuloDevelop** [angular/angular-cli#16298]
I follow the steps listed in this doc https://github.com/angular/angular-cli/wiki/stories-configure-hmr but when i run the project the following warning appears:
```
NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.The project will still live reload when HMR is enabled,
but to take advantage of HMR additional application code is required'
(not included in an Angular CLI project by default).'
See https://webpack.js.org/guides/hot-module-replacement
for information on working with HMR for Webpack.
```
It tells that HMR is enable but the project still going to use Live Reload and i can confirm that when i edit a file while project is running. It redirects me to a webpack tutorial but i dont know how exactly apply those changes in my project.

### Versions
```
Angular CLI: 7.3.8
Node: 12.8.0
OS: win32 x64
```

**Comment by alan-agius4** [comment]
To disable this warning use "hmrWarning: false" under "serve" options in "angular.json".

**Comment by RomuloDevelop** [comment]
The problem i see is that HMR is not working, hiding the warning won't do any difference

**Comment by alan-agius4** [comment]
Can you kindly share a reproduction please? As it might be related to misconfiguration.

Thanks

**Comment by raphael22** [comment]
@RomuloDevelop I think your HMR is working fine.
But the best '@angularclass/hmr' can do is destroy your app elements and recreate it.
So you will see a blink but you stay in the same browser session making it slighty faster. (4sec against 6sec reloading time in my case).

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
