### ISSUE TITLE
ng update does not update @angular-devkit/schematics

### ISSUE THREAD

**Issue by florian-kittel** [angular/angular-cli#16307]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] update

### Is this a regression?

 Not working in previous versions as well.

### Description

 I have a library project and @angular-devkit/schematics was installed automatically by ng generate library <name>. When I perform an ng update, all Angular related packages are updated beside @angular-devkit/schematics.

## 🔬 Minimal Reproduction

In a default project with:
<pre><code>"devDependencies": {
    "@angular-devkit/build-angular": "0.803.19",
    "@angular-devkit/schematics": "8.3.17",
    "@angular/cli": "8.3.19",
    "@angular/compiler-cli": "8.2.14",
    "@angular/language-service": "8.2.14",
...</code></pre>

I perform an update and the result is:
<pre><code>"devDependencies": {
    "@angular-devkit/build-angular": "0.803.20",
    "@angular-devkit/schematics": "8.3.17",
    "@angular/cli": "8.3.20",
    "@angular/compiler-cli": "8.2.14",
    "@angular/language-service": "8.2.14",
...</code></pre>

I have to update to @angular-devkit/schematics to 8.3.20 manually. As you can see, this update was also not performed when I did the 8.3.19 update from 8.3.17.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.20
Node: 10.14.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.17
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/flex-layout              8.0.0-beta.27
@angular/http                     7.2.15
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by alan-agius4** [comment]
Hi, 
> I have a library project and @angular-devkit/schematics was installed automatically by ng generate library . 

Can you explain this a bit more please?

**Comment by alan-agius4** [comment]
Following a convo with @clydin. the listed packages are intentionally left out. As the only reason they would be present is if the user was using them directly.  And in that case, updating them would most likely break their code.

**Comment by florian-kittel** [comment]
> Hi,
> 
> > I have a library project and @angular-devkit/schematics was installed automatically by ng generate library .
> 
> Can you explain this a bit more please? `ng generate library` doesn't add this dependency, is it a custom schematic?

Was my fault, schematics is not present because of library build. It was manually added to use schematics for custom schematics in our project.

**Comment by florian-kittel** [comment]
> Following a convo with @clydin. the listed packages are intentionally left out. As the only reason they would be present is if the user was using them directly. And in that case, updating them would most likely break their code.

I don't get the point. Wasn't the intention of Angular to have a consistent version number over all packages? When I update all packages and let an old schematics version in the project, then I will have more trouble or not?

**Comment by florian-kittel** [comment]
It isn't needed to update automatically, but it would be good if ng update could list this project with a new version.

**Comment by alan-agius4** [comment]
@florian-kittel if you run `ng update` without any parameter it will show you the packages that needs to be updated.

**Comment by alan-agius4** [comment]
@florian-kittel does the above comment answer your query?

**Comment by florian-kittel** [comment]
Hi @alan-agius4, that is what I meant. We always use ng-update since it is present in the cli . So I moved back with the setup posted initially
```
"devDependencies": {
    "@angular-devkit/build-angular": "0.803.19",
    "@angular-devkit/schematics": "8.3.17",
    "@angular/cli": "8.3.19",
    "@angular/compiler-cli": "8.2.14",
    "@angular/language-service": "8.2.14",
...
```

I run `ng update`:
```
+ @angular/cli@8.3.20
added 251 packages from 186 contributors in 66.398s
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 75 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       8.3.19 -> 8.3.20         ng update @angular/cli
```
Nothing more is listed.

After running `ng update @angular/cli`

```
  "devDependencies": {
    "@angular-devkit/build-angular": "0.803.20",
    "@angular-devkit/schematics": "8.3.17",
    "@angular/cli": "8.3.20",
    "@angular/compiler-cli": "8.2.14",
    "@angular/language-service": "8.2.14",
```

As you see, the `@angular-devkit/schematics` was not listed and not update with the other dev-kit stuff. The package ` "@angular-devkit/build-angular": "0.803.20",` and the cli itself `"@angular/cli": "8.3.20",` are updated with the cli update.

That was the intention of this issue report. So I need to check "by hand" if there is a new version for `@angular-devkit/schematics` and of course there is also `8.3.20`. That was the reason why we had `"@angular-devkit/schematics": "8.3.17",` already when we updated form ` "@angular/cli": "8.3.19"` to ` "@angular/cli": "8.3.20"`.

**Comment by florian-kittel** [comment]
I'm currently updating another project as well and in this I saw the same for `"@angular-devkit/core": "^8.3.4",` -> not listed in `ng update` and not auto updated with cli or angular update.

```
"dependencies": {
    "@angular/animations": "^8.2.6",
    "@angular/common": "^8.2.6",
    "@angular/compiler": "^8.2.6",
    "@angular/core": "^8.2.6",
    "@angular/forms": "^8.2.6",
    "@angular/platform-browser": "^8.2.6",
    "@angular/platform-browser-dynamic": "^8.2.6",
    "@angular/router": "^8.2.6",
...
    "classlist.js": "1.1.x",
    "rxjs": "~6.5.3",
    "zone.js": "~0.9.1"
  },
 "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.4",
    "@angular-devkit/build-ng-packagr": "^0.803.4",
    "@angular-devkit/core": "^8.3.4",
    "@angular/cli": "^8.3.4",
    "@angular/compiler-cli": "^8.2.6",
...
```

using `ng update` give me:

```
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cli                       8.3.4 -> 8.3.20          ng update @angular/cli
      @angular/core                      8.2.6 -> 8.2.14          ng update @angular/core
```

after the update with `ng update @angular/cli @angular/core`

```
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
...
    "classlist.js": "1.1.x",
    "rxjs": "~6.5.3",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.20",
    "@angular-devkit/build-ng-packagr": "^0.803.20",
    "@angular-devkit/core": "^8.3.4",
    "@angular/cli": "^8.3.20",
    "@angular/compiler-cli": "^8.2.14",
...
```

As you see `"@angular-devkit/core": "^8.3.4",` stayed on 8.3.4. The other are updated in the package.json.

**Comment by alan-agius4** [comment]
Similarly to `@angular-devkit/schematics`, `@angular-devkit/core` is also intentionally left out. I am going to mark this for `need further discussion`, and discuss this further during our next meeting.

**Comment by vikerman** [comment]
This needs a redesign of schematics so that running a custom schematics does not need dependency on @angular-devkit packages.

Using this issue for tracking that.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
