### ISSUE TITLE
Unable to launch the Angular 8 project After AOT Build 

### ISSUE THREAD

**Issue by PraisyA** [angular/angular-cli#16303]
Hello all,

i have an issue While launching the product from Azure . Here is the issue 
I got an exception like " unexpected end of input " in console (see attached pic ) .
![BizsightLoderror](https://user-images.githubusercontent.com/30825040/69777490-84f3fa00-11c6-11ea-994f-32ddb2875ff4.png)
    I have cleared the Browser ( I used Chrome and IE) then reload the product then i got anther issue " Uncaught SyntaxError: missing ) after argument list "
![Missingissue](https://user-images.githubusercontent.com/30825040/69777557-d00e0d00-11c6-11ea-943f-c6ccdecfb743.png)

I have cleared and reload the project many times  it finally launched after 20 mins .  Can you please help this , i have already lost few customers because of this issue .

Here is my Work Environment 
1. Angular 8 
2. Typescript 3.4.5
3. Visual Studio 2019 
4. .Net Core 2.0
 and AOT build Query is :    node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod

Thanks
Praisy Athoti.

**Comment by alan-agius4** [comment]
Hi, can you update to latest version of the CLI and see if the problem persists lease submit a reproduction.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by PraisyA** [comment]
Hello  alan-agius4,
Thank you for your response, In my project we are using Telerik Kendoui Controllers and this project size 350 MB.  My self i have tested with few files that time it launching correctly , if i use all my apps then it give that error . 
Is there a way to build AOT without using " --max_old_space_size=8192 " .


Thanks
Victor Athoti

**Comment by alan-agius4** [comment]
`max_old_space_size` is needed is your project is large. This error occurs when the memory allocated for the execution build is less than the required memory when run the build.

**Comment by alan-agius4** [comment]
The problem reported though is a runtime error which is not related to the `max_old_space_size` flag. Can you setup a minimal repro please to replicate the runtime error?

Thanks.

**Comment by PraisyA** [comment]
Hello alan-agius4,
I will create  a  Repro-app  and will provide the github link .


Thanks

**Comment by filipesilva** [comment]
This looks like a network problem. Your server might not be serving the full .js files, which would give those errors.

**Comment by PraisyA** [comment]
Hello filipesilva ,
Thank you for your reply , May be it is network issue , but  we have Good bandwidth like 25 Mega Bytes speed and other sites loading very quickly.

**Comment by PraisyA** [comment]
Hello **alan-agius4**,
I have create a Repro-app with specific files , but this is loading ( did not get any issue ). i am trying to add more files one by one , when ever I get exception then I will upload to GitHub and will provide the link.


Thanks

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
