### ISSUE TITLE
Cannot find module './app-routing.module'

### ISSUE THREAD

**Issue by viniciussanchez** [angular/angular-cli#16300]
# 🐞 Bug report

### Command

- [X] new

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.3.10

### Description

When executing the command "ng new my-project" it does not create all necessary files (app-routing.module.ts, app.component.css). When executing the command "ng serve" does not find the files that were not created. The problem occurs in version 8.3.19, 8.3.18 and finally I tested in version 8.3.10 which worked perfectly.

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/16382981/69754839-9d680400-1135-11ea-86af-cc491f75faa2.png)

**Comment by alan-agius4** [comment]
Hi @viniciussanchez, I tried to replicate the issue that you are reporting however I didn't manage.

I tried both with routing enabled and disabled and the files were always generated as expected.

Are you using another schematic collection instead of `@schematics/angular` by any chance?


Can you please provide the output of;
```
ng version
ng config --g
```

Thanks.

**Comment by viniciussanchez** [comment]
Hi, 

Version 8.3.10 of ng works, while version 8.3.19 and 8.3.18 does not work.

This is the client configuration in version 8.3.10 which works.

![image](https://user-images.githubusercontent.com/16382981/69801030-2d995e00-11b5-11ea-80fc-22d0b52d84ed.png)

$ npm -v
6.13.1

$ node -v
v12.13.1

Install latest version (with error)
$ npm i -g @angular/cli

Install correct version
$ npm i -g @angular/cli@8.3.10

**Comment by alan-agius4** [comment]
Hi again, I am still unable to reproduce the issue you are reporting. 

Can you please provide the full output of;
```
ng version
```

Also, can you provide the exact command you are running, and the exact values that you are providing to the prompts?

Thanks.

**Comment by alan-agius4** [comment]
Can you also try to use version 9 of the CLI.

```
npm i -g @angular/cli@next
```
