### ISSUE TITLE
use cypress as the default e2e tool

### ISSUE THREAD

**Issue by vthinkxie** [angular/angular-cli#16311]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
protractor is good, but cypress provides a much better user experience than protractor in e2e testing

### Describe the solution you'd like

replace the e2e testing tools with cypress in angular cli

There is a schematic provided by https://www.npmjs.com/package/@briebug/cypress-schematic, but it would be better to make it the default one since angular cli should provide a better experience out of the box.

### Describe alternatives you've considered

a related issue in https://github.com/angular/angular-cli/issues/8013 2 years ago

**Comment by alan-agius4** [comment]
Hi @vthinkxie,

Thanks for this feature request. It is not currently in the roadmap to replace the default E2E framework with Cypress.

While, indeed I agree we should provide a better experience out of the box, there are other alternatives to Cypress. This, however is a huge multi-step effort as we also need to migrate existing users to a new E2E testing framework. 

Besides, we'll also need to evaluate if want to diverge from what's used internally in Google.
