### ISSUE TITLE
Risky cryptographic hashing function 

### ISSUE THREAD

**Issue by nishant4nishu** [angular/angular-cli#16313]
Hi Angular team,

We have Coverity SCA tool integrated with our angular application.Below are the issues reported by tool for node modules files and categorized as "Risky cryptographic hashing function". Is the below issue still open from your end or fixes are already given in some of your angular releases? Please suggest. Used Angular version 4.x

1)**Filename** :-->  /node_modules/webpack/lib/ModuleFilenameHelpers.js 
 function name :-> getHash

2)**Filename** :--> /node_modules/webpack/lib/NormalModule.js 
 **function name** :-> NormalModule.prototype.source
3) **Filename** :-->/node_modules/typescript/lib/typescript.js 
 **function name** :->nodeSystem.createHash
4)**Filename** :-->/node_modules/ts-node/dist/index.js  <anonymous>
5)**Filename** :-->/node_modules/ts-node/dist/index.js   <anonymous>
6)**Filename** :-->/node_modules/istanbul-api/node_modules/istanbul-lib-instrument/dist/constants.js  <script>
7)**Filename** :-->/node_modules/ts-node/dist/index.js   <script>
8)**Filename** :-->/node_modules/istanbul/lib/instrumenter.js 
 **function name** :->generateTrackerVar
9)**Filename** :-->/node_modules/postcss-url/index.js 
 **function name** :->  processCopy
10)**Filename** :-->/node_modules/ts-node/dist/index.js 
 **function name** :->load

**Comment by filipesilva** [comment]
Hi there,

Angular version 4 is an older version that we don't directly support anymore, but we still use some of the dependencies you mention. A better place to report any problems with those dependencies is their repository though.
