### ISSUE TITLE
Multiple applications Angular

### ISSUE THREAD

**Issue by Denschik** [angular/angular-cli#16318]
I faced problem with using several (independent) Angular-Apps on one page (project using several independent mirco-apps).

I read about Angular Elements, creating projects, libraries, but this not right for me.

Reviews about using iframes for Angular-apps - only negative (i think using iframes - an extreme measure).

This option suits me best: https://medium.com/swlh/multiple-angular-apps-on-a-single-page-9f49bc863177

But I get error:
`Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten`

Yep, Zone.js has global instance and several Angular-apps using own zone.js

Is it really so difficult to use several independent Angular-applications on one page?

I tryid only one Zone.js ( https://medium.com/angular-in-depth/do-you-still-think-that-ngzone-zone-js-is-required-for-change-detection-in-angular-16f7a575afef ), but this don't work for me.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
