### ISSUE TITLE
Description for "@angular-devkit/build-angular"

### ISSUE THREAD

**Issue by madoar** [angular/angular-cli#16319]
I'm trying to cleanup my project dependencies. Therefore I'm looking at all the descriptions of my used dependencies on npm and Github. Sadly it seems like some dependencies don't provide a description or I'm just unable to find it.

One such dependency is `@angular-devkit/build-angular` when I search for it on [npm](https://www.npmjs.com/package/@angular-devkit/build-angular) I am shown the description text: `WIP`. It would be nice if a more descriptive text could be added for the angular dependencies especially if they are downloaded by over a million people every week.

**Comment by filipesilva** [comment]
We really should do this.

**Comment by adrenadine33** [comment]
> master

**Comment by alan-agius4** [comment]
Closing as this has been addressed.
