### ISSUE TITLE
9.0.0-rc.4 build - createWebpack(...).pipe is not a function

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#16316]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem...
ng build --prod gives a `createWebpack(...).pipe` error when trying to build after: `ng update @angular/cli @angular/core --force`. Serving the project works perfectly fine.

## 🔬 Minimal Reproduction

ng build --prod

## 🔥 Exception or Error
<pre><code>[error] TypeError: createWebpack(...).pipe is not a function
    at Object.runWebpack (/Users/dom/Projects/fe/node_modules/@angular-devkit/build-angular/node_modules/@angular-devkit/build-webpack/src/webpack/index.js:20:34)
    at SwitchMapSubscriber.project (/Users/dom/Projects/fe/node_modules/@angular-devkit/build-angular/src/browser/index.js:128:32)
    at SwitchMapSubscriber._next (/Users/dom/Projects/fe/node_modules/rxjs/internal/operators/switchMap.js:49:27)
    at SwitchMapSubscriber.Subscriber.next (/Users/dom/Projects/fe/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /Users/dom/Projects/fe/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 9.0.0-rc.4
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.14
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              8.3.14
@angular-devkit/schematics        8.3.14
@angular/cdk                      8.2.3
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.4
@nguniversal/common               8.1.1
@nguniversal/express-engine       8.1.1
@schematics/angular               8.3.14
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

I'm not sure if you have enough to debug here. Didn't find any related issue so am creating this with all the info I have. I can debug further with some guidance.

**Comment by clydin** [comment]
Are you using nx within the workspace?

**Comment by intellix** [comment]
yes. Sorry I forgot to mention that :S

**Comment by filipesilva** [comment]
This might be similar to https://github.com/angular/angular-cli/issues/16207

**Comment by FrozenPandaz** [comment]
Hey @intellix,

I think you may have `@angular-devkit/architect` in your `package.json`. I recommend removing it if possible or making sure that version is updated as well to match the version used by other packages (`@angular-devkit/build-angular` and `@nrwl/node`)

You should also update `@nrwl/` dependencies via `ng update @nrwl/workspace --next`

**Comment by intellix** [comment]
@angular-devkit/architect wasn't in our package.json but we updated @nrwl to latest and it got us a step further. Now it's just:
```
ERROR in Cannot read property 'length' of undefined
```

Tried to inspect and break on errors. Got errors like the "object could not be cloned" with a reference to a part of our angular.json file:

<img width="305" alt="Screenshot 2019-12-05 at 16 35 57" src="https://user-images.githubusercontent.com/1162531/70250081-a54f2600-177d-11ea-88c8-6bcfe7c7b4f1.png">

Not sure if it's related to the build error but

**Comment by filipesilva** [comment]
Did you get a stack trace for the error?

**Comment by intellix** [comment]
nope unfortunately not. I'll try and get more information

**Comment by clydin** [comment]
@intellix Have you tried with the latest `next` version of nx?  The recently published version updates the Angular dependencies to rc.5.

**Comment by intellix** [comment]
If I do an `ng build --prod --verbose` I get a bunch of stuff and the last part is:
```
➜  lambda-gaming git:(9-ivy) ng build --prod --verbose
<w> [webpack.Progress] 4135ms building
<i> [webpack.Progress] 12ms chunk assets processing
<w> [webpack.Progress] 2250ms chunk asset optimization

WARNING in Terser Plugin: Condition always true [polyfills-es5.2ba581e8d87bcbff9df5.js:1381,3]

WARNING in Terser Plugin: Side effects in initialization of unused variable core_js_es_symbol__WEBPACK_IMPORTED_MODULE_0__ [polyfills-es5.2ba581e8d87bcbff9df5.js:6146,25]

....... (loads more of the same stuff)

WARNING in Terser Plugin: Dropping duplicated definition of variable result [polyfills-es5.2ba581e8d87bcbff9df5.js:9148,16]

WARNING in Terser Plugin: Dropping duplicated definition of variable result [polyfills-es5.2ba581e8d87bcbff9df5.js:9164,16]

WARNING in Terser Plugin: Condition always true [polyfills-es5.2ba581e8d87bcbff9df5.js:8800,5]

ERROR in Cannot read property 'length' of undefined
```

Currently:
```
Angular CLI: 9.0.0-rc.5
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@angular/cdk                      8.2.3
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.5
@nguniversal/common               8.1.1
@nguniversal/express-engine       8.1.1
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by alan-agius4** [comment]
@intellix is this still a problem?

**Comment by intellix** [comment]
Aw hi, I'll close it
