### ISSUE TITLE
9.0.0-rc.4 build - ng serve - freeze

### ISSUE THREAD

**Issue by igorroman777** [angular/angular-cli#16326]
# 🐞 Bug report

### 
ng  serve

### Description
92% additional asset processing scripts-webpack-plugin

###
Angular CLI: 9.0.0-rc.4
Node: 12.13.1
OS: linux x64

Angular: 9.0.0-rc.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by alan-agius4** [comment]
Hi, would you kindly be able to provide a reproduction? Which `scripts` do you have configured?

**Comment by igorroman777** [comment]
Hi,
I have updated my project from Angular 8 to 9. It worked before. But now I do:
ng serve and stay with the message:
92% additional asset processing scripts-webpack-plugin

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by igorroman777** [comment]
Hi Alan,
my repro-project for bug is hier:
https://github.com/igorroman777/angular-9-ng-bug.git

 After "ng -serve" I come, I get this "92% additional asset processing scripts-webpack-plugin"
 and nothing else happens. :(
Thanks

**Comment by b-johnse** [comment]
I have a similar issue, but hangs at "93% after chunk asset optimization SourceMapDevToolPlugin"

When I do an ng v, I can see that `ng update @angular/cli@next` did not upgrade all the angular-devkit dependencies from 8.3.14 to the rc4 versions

**Comment by igorroman777** [comment]
Hi Brandon @b-johnse,
but I've updated everything:

Angular CLI: 9.0.0-rc.4
Node: 12.13.1
OS: linux x64

Angular: 9.0.0-rc.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.4
@angular-devkit/build-angular     0.900.0-rc.4
@angular-devkit/build-optimizer   0.900.0-rc.4
@angular-devkit/build-webpack     0.900.0-rc.4
@angular-devkit/core              9.0.0-rc.4
@angular-devkit/schematics        9.0.0-rc.4
@ngtools/webpack                  9.0.0-rc.4
@schematics/angular               9.0.0-rc.4
@schematics/update                0.900.0-rc.4
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by clydin** [comment]
When I tried to perform a build (`ng build --prod`), I receive an error:
```
ENOENT: no such file or directory, open '/Users/chuck/Documents/scratch/angular-9-ng-bug/node_modules/hammerjs/hammer.min.js'
```
Manually verifying the file existence resulted in the same conclusion.  The package also appears to not present in the project's `package.json`.

**Comment by igorroman777** [comment]
Hi @clydin ,
Thanks for the guy. I installed hammerjs and I'm **running** it, I'm getting other problems:

WARNING in Conflict: Multiple assets emit different content to the same filename 3rdpartylicenses.txt

ERROR in multi ./src/styles-app-loading.scss ./node_modules/ng-uikit-pro-standard/assets/scss/bootstrap/bootstrap.scss ./node_modules/ng-uikit-pro-standard/assets/scss/mdb.scss ./src/styles.scss ./node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss ./node_modules/@fortawesome/fontawesome-free/scss/regular.scss ./node_modules/@fortawesome/fontawesome-free/scss/solid.scss ./node_modules/@fortawesome/fontawesome-free/scss/brands.scss ./src/unicorn-dark-theme.scss
Module not found: Error: Can't resolve '/home/igor/workspace-mars/angular-9-ng-bug/ng-bug/node_modules/ng-uikit-pro-standard/assets/scss/bootstrap/bootstrap.scss' in '/home/igor/workspace-mars/angular-9-ng-bug/ng-bug'

**Comment by clydin** [comment]
That appears to be a similar issue in that `node_modules/ng-uikit-pro-standard/assets/scss/bootstrap/bootstrap.scss` is not found.
It is important to ensure that all required dependencies for application code are present prior to attempting a build.

Closing the issue as this doesn't appear to be a defect in the Angular CLI itself.
