### ISSUE TITLE
Allow `ng e2e` accept `--base-url` with `--dev-server-target`

### ISSUE THREAD

**Issue by ikedam** [angular/angular-cli#16325]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

I want to use `--base-url` with `--dev-server-target` in `ng e2e`, but it results a following error:

```
The 'baseUrl' option cannot be used with 'devServerTarget'.
```

I want to use them together in the following case:

* Let `ng e2e`  launch the server (`--serve`) and then run protractor.
    * `--serve` feature is really useful as protractor starts after the server gets ready.
* protractor controls a browser in another host with webdriver protocol.

In that case, the browser have to access the server not with http://localhost:4200/ which is automatically configured with `ng e2e --dev-app-server`, but with http://(appropriate host name):4200/. 

I created a demonstration project to explain what I want: https://github.com/ikedam/angular-e2e-base-url-demo

### Describe the solution you'd like

I want to use `--base-url` to specify that host name.

Relates: #13611, #13614

### Describe alternatives you've considered

Accepting `--public-host` in `ng e2e` can resolve this issue.
(It results `Unknown option: '--public-host'` for now)

Relates: #9242

**Comment by alan-agius4** [comment]
Hi @ikedam, it looks to me that the problem is that the command you are running is 
```
```

**Comment by ikedam** [comment]
@alan-agius4 You're right.
Specifying a host name in `--host` instead of `0.0.0.0` resolves my issue: https://github.com/ikedam/angular-e2e-base-url-demo/commit/ffcf1d8fe9b7fc7de257c3df18d630f37ff59947
(You also need to set up the environment to allow angular resolve the host name to IP address)

Thanks a lot!
