### ISSUE TITLE
Schematics move function does not work in v9.rc4

### ISSUE THREAD

**Issue by jorgeucano** [angular/angular-cli#16321]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
no

### Description
Update my schematics to Angular 9rc4 and the move function does nothing. It's as if I pass it by, the other functions work fine, but when I use move, I don't copy any files

## 🔬 Minimal Reproduction

Create a schematic with the Schematics CLI and add this 
<pre>
import {
  apply, mergeWith, move, Rule, SchematicContext, Tree, url
} from '@angular-devkit/schematics';
import {Schema} from './schema';
export default function(options: Schema): Rule {
  return (host: Tree, context: SchematicContext) => {
    const templateSource2 = apply(
      url('./files'),
      [
        move('/test')
      ],
    );
    return mergeWith(templateSource2);
  };
}
</pre>
Build and run 

## 🔥 Exception or Error
No error or exceptions just `Nothing to be done.`

## 🌍 Your Environment
<pre><code>
λ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.0-rc.4
Node: 10.16.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.4
@angular-devkit/core         9.0.0-rc.4
@angular-devkit/schematics   9.0.0-rc.4
@schematics/angular          9.0.0-rc.4
@schematics/update           0.900.0-rc.4
rxjs                         6.5.3
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @jorgeucano, I tried to replicate the above issue however I didn't manage.

```
schematics ..\hello-world:hello-world
CREATE /test/text.txt (1 bytes)
```

Would you be able to provide a reproduction?

**Comment by jorgeucano** [comment]
@alan-agius4 I'm using `windows 10` my terminal is `Cmder` ... 
This is my repo example with video https://github.com/jorgeucano/schematics-error

**Comment by alan-agius4** [comment]
The problem is that `url('./files'),` should be `url('../files'),` since the files are located in a directory outside of the `test` folder which contains the schematic

**Comment by jorgeucano** [comment]
thanks @alan-agius4 ... thanks @alan-agius 4 ... How i can help to improve better documentation?
