### ISSUE TITLE
Support the latest RxJS 6.5.3 in the latest Angular CLI 8.3.20

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular-cli#16338]
# 🚀 Feature request

### Description
Update to the latest RxJS package in Angular CLI 8 line.

### Describe the solution you'd like
If there are no breaking changes (not aware of any), update RxJS to the latest 6.5.3 version in the Angular CLI 8 line, actually in 8.3.20.

**Comment by clydin** [comment]
RxJS 6.4.x is the recommended version to use with 8.x.  Angular 9.0 (currently in release candidate stage) will use 6.5.x as the minimum version.
