### ISSUE TITLE
ng serve should watch i18n messages files

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#16341]
# 🚀 Feature request

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

When using the new i18n support with CLI v9 (rc.4 at the time of writing), it is possible to run:
    
    ng serve --configuration=fr

with `fr`:
```json
"i18n": {
  "locales": {
    "fr": "src/locale/messages.fr.xlf"
  }
},
"fr": {
  "localize": ["fr"]
}
```

This works great, but does not pick up translation changes in `messages.fr.xlf`, requiring a stop and restart of `ng serve`.

### Describe the solution you'd like

It would be nice to have `ng serve` watch the files defined in the `locales` configuration.

### Describe alternatives you've considered

It is possible to stop and restart the server to have the up-to-date translations.

**Comment by fetis** [comment]
it's still an issue with v10 :(

I would also re-qualify it from `feature` to `bug/regression` because it worked fine in v8

**Comment by montogeek** [comment]
I have to restart my dev server when changing anything in the .xlf files to see the change reflected in the server. Is this issue related?

**Comment by dev054** [comment]
@clydin sorry to bother you, but I see that you have a PR that address this issue... so allow me to kindly ask: is there a plan to merge this before v13 comes out? Thanks.

**Comment by bbarry** [comment]
Is anyone else having an issue with this change now giving a warning every time you save a file that every message in your translation file is a duplicate?

```

WARNING [src/locale/messages.fr.xlf]: Duplicate translations for message 'bd56617283412e79a0b08b6cf2a9409c548ac187' when merging

WARNING [src/locale/messages.fr.xlf]: Duplicate translations for message 'ngb.alert.close' when merging

WARNING [src/locale/messages.fr.xlf]: Duplicate translations for message 'ngb.carousel.next' when merging

WARNING [src/locale/messages.fr.xlf]: Duplicate translations for message 'ngb.carousel.previous' when merging

WARNING [src/locale/messages.fr.xlf]: Duplicate translations for message 'ngb.carousel.slide-number' when merging

WARNING [src/locale/messages.fr.xlf]: Duplicate translations for message 'ngb.datepicker.next-month' when merging

WARNING [src/locale/messages.fr.xlf]: Duplicate translations for message 'ngb.datepicker.previous-month' when merging
```

every time I save a file while running `ng serve` now I get a few hundred of these if I have translations in use.

**Comment by dgp1130** [comment]
@bbarry, I think https://github.com/angular/angular-cli/pull/22209 should add an option to suppress these warnings, though they typically do point to a real issue, so it might be worth investigating why there are duplicate translations.

**Comment by bbarry** [comment]
Yes I don't like the idea of suppressing the warning; my concern isn't seeing the warnings, it is that they only appear after a watched file rebuilds.

I am not getting the warnings on the initial builds. It seems like the variable isn't being properly re-initialized.
