### ISSUE TITLE
Pass-though of build parameters to ng serve

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#16347]
# 🚀 Feature request
Command line parameters for ng serve to pass in build configuration settings without a configuration in angular.json

### Command
```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
When building a multilingual application we need a build configuration for each language.
For the actual build we can avoid having multiple configurations in angular.json by simply using the parameters of ng build.

By doing so I have a custom build script that reads out a json file and automatically builds all languages configured in that file. (xliffmerge.json for ngx-i18nsupport) My script (below if someone wants it) is maybe not optimal, but it works fine and I need only 1 production config for all languages.

But when it comes to ng serve, I still need a build configuration for every language in order to set the locale and xlf file.

```json
    "en": {
              "aot": true,
              "i18nLocale": "en"
            },
            "de": {
              "aot": true,
              "i18nFile": "locale/messages.de.xlf",
              "i18nFormat": "xlf",
              "i18nLocale": "de",
              "i18nMissingTranslation": "warning"
            }
```

In my case I also need to pass port, baseHref and publicHost to ng serve as I run ng serve behind an asp.net spa proxy that serves all the languages at once. This parameters can be passed in using the ng serve parameters or by angular.json.

My build script:

```js
'use strict';

const fs = require('fs');
const {execSync} = require('child_process');

var execOptions = {
  encoding: 'utf8'
};

// Get languages from xliffmergeOptions
let rawdata = fs.readFileSync('../appsettings.json');
let xliffmergeOptions = JSON.parse(rawdata).xliffmergeOptions;
let defaultLanguage = xliffmergeOptions.defaultLanguage;
let additionalLanguages = xliffmergeOptions.languages;
let languages = [defaultLanguage, ...xliffmergeOptions.languages];

// Some console info
console.info('Build started for: ', languages);

// Run i18n-extract & merge xliff files
console.log(execSync('npm run i18n', execOptions));

// Build default language
console.log(execSync(`npm run ng build -- -c production --outputPath=dist/${defaultLanguage} --baseHref=/${defaultLanguage}/app/ --i18nLocale=${defaultLanguage}`, execOptions));

// Build additional languagses
for (const language of additionalLanguages) {
  console.log(execSync(`npm run ng build -- -c production --outputPath=dist/${language} --baseHref=/${language}/app/ --i18nLocale=${language} --i18nFile=locale/messages.${language}.xlf --i18nFormat=xlf --i18nMissingTranslation=warning`, execOptions));
}

// Some console info
console.info('Build finished for: ', languages);
```

### Describe the solution you'd like
I would like to have parameters for ng-serve, that i can use to change the build configuration options that are related to i18n. Maybe something like:

ng serve --build:i18nlocale=de --build:i18nFile=....

By that one could simply create a script that can serve any language configured in some config file similar to my bild script. So when adding a new language you would simply add that language to your config file.

### Describe alternatives you've considered
For the moment I have a build and serve config for each language and one npm script per language. I also thought about using ng config in a script to change the prod configuration before launching ng serve and then change it back, but that feels somehow bad.

**Comment by filipesilva** [comment]
I agree that pass-through configs are a good idea but it's also a bit more complicated... the pass-though can be to something many levels deeps. We'd need some concept of selectors.

I will say though, that in version 9 with Ivy the i18n options are much more ergonomic and project wide. You can also declare multiple configurations (e.g. `ng serve -c production,something-else`). We think these two things together will help reduce the complexity of i18n configs, which today grow pretty big.

**Comment by alan-agius4** [comment]
Hi @mbeckenbach,

The above should no longer be needed since Angular CLI version 9. The localization story has been overhauled in version 9, where you no longer need to have multiple builds and configurations for each locale to build your application in multiple locales.

You can use the below command to build your application in all the locales.
```
ng build --localize
```


More info: https://angular.io/guide/i18n
