### ISSUE TITLE
How to organise Protractor tests

### ISSUE THREAD

**Issue by jculverwell** [angular/angular-cli#1635]
Do anyone have a any recommendations on how to organize protractor tests inside the folder structure that angular-cli produces?

I am assuming that unit tests typically go in a spec file called componentname.component.spec.ts which sit at the same level as the componentname.component.ts file.

For e2e tests I am assuming that people are putting them in the e2e folder with a folder structure mirroring their app/component folder layout?

One thing I am unclear on is how protractor knows where to find e2e tests.

Any pointers greatly appreaciated.

**Comment by jculverwell** [comment]
I don't know how I missed this before but Protractor is configured here \config\protractor.conf.js and it looks for files ending with **.e2e-spec.ts**  in the 'e2e' directory and its subdirectories.  

This makes complete sense now.

**Comment by gh0st** [comment]
I thought this was a good question. Especially if you start filling out your angular project with handfuls of components. Have you found that it's better to put a sub-directory in e2e/ for each component you have? Each subdirectory being named after the component it corresponds to, and in each subdirectory being a component-name.e2e-spec.ts and component-name.po.ts? So for example.

```
e2e/
    my-component/
        my-component.e2e-spec.ts
        my-component.po.ts
    my-other-component/
        my-other-component.e2e-spec.ts
        my-other-component.po.ts
```
