### ISSUE TITLE
@schematics/shematics:schematic missing files

### ISSUE THREAD

**Issue by julianobrasil** [angular/angular-cli#16365]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] schematics

### Is this a regression?

No

### Description

Although all the template files are present in https://github.com/angular/angular-cli/tree/master/packages/schematics/schematics/schematic/files, when I try to create a simple project based on `@shematics/schematics:schematic`, a lot of files are missing on the created project folder.

I'm using windows 10 powershell.

### First, I've installed a bunch of packages globally:

![image](https://user-images.githubusercontent.com/25405143/70243938-56d86200-1752-11ea-829f-d3f874d62807.png)

### Then I've created a project (notice that only six files are created):

```
schematics @schematics/schematics:schematic --name schematics-debugged
```

This is the result:

![image](https://user-images.githubusercontent.com/25405143/70244073-85563d00-1752-11ea-9948-c2ed60438fb7.png)

## 🔥 Exception or Error

There's no error message (or warning or any message at all)

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.20
Node: 12.12.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.20
@angular-devkit/core         8.3.20
@angular-devkit/schematics   8.3.20
@schematics/angular          8.3.20
@schematics/update           0.803.20
rxjs                         6.4.0
</code></pre>

**Anything else relevant?**

If I run the other schematic in the same project (`blank` schematic):

```
schematics @schematics/schematics:blank --name schematics-debugged
```

The expected files are present on the created project (`tsconfig.json` etc...)

**Comment by alan-agius4** [comment]
Can you try to install the latest prerelease version of `@angular-devkit/schematics-cli`?

```
npm i @angular-devkit/schematics-cli@next-g
```

**Comment by julianobrasil** [comment]
Thank you, @alan-agius4, it's working with `@angular-devkit/schematics-cli@0.900.0-rc.5`.

I'm closing this as it's fixed with the new cli.
