### ISSUE TITLE
Support for `paths` option in tsconfig.lib.json?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#16367]
I described the issue in this SO post:

https://stackoverflow.com/questions/59201598/using-tsconfig-paths-with-angular-libraries

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [ng-packagr](https://github.com/ng-packagr/ng-packagr) project or file an issue on their issue tracker.
