### ISSUE TITLE
Generate components with UTF8-BOM encoding - messing up layout because of &#65279 ;

### ISSUE THREAD

**Issue by corleymanz** [angular/angular-cli#16362]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, this is the first time i see this behaviour

### Description

My html files are encoded as UTF8-BOM and production build is different then a non-production build

On a production build there is a special character (&#65279 ;) on every html component. I dont want to see this character in the html because the browser renders this as a white space. and this is messing up the lay-out.

## 🔬 Minimal Reproduction
make a new website
mark a html file as UTF8-BOM
ng build --prod

start website and inspect the html component. at start of component you see (&#65279 ;)

## 🔥 Exception or Error
No error, just unexpected behauviour
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI : 7.2.2
Node : 13.2.0
OS : win32 x64
Angular : 7.2.1

package   Version
----------------
@angular-devkit/architect                      0.12.2
@angular-devkit/build-angular                      0.13.8
@angular-devkit/build-optimizer                   0.13.8   
@angular-devkit/build-webpack                      0.13.8
@angular-devkit/core                      7.2.2
@angular-devkit/schematics                   7.2.2   
@angular/cdk                      7.3.7
@angular/cli                      7.2.2
@angular/compiler-cli               7.2.12       
@angular/material                      7.3.7
@ngtools/webpack                      7.3.8
@schematics/angular                      7.2.2
@schematics/update                      0.12.2
rxjs                      6.3.3
typescript                   3.2.4   
webpack                      4.29.0

</code></pre>

**Comment by filipesilva** [comment]
Heya, does this still happen with the latest versions of CLI and framework? I remember we did some work regarding BOM already, but it's the sort of thing that isn't likely to be backported to previous majors.

**Comment by corleymanz** [comment]
Thans. I have to check. I will let you know

**Comment by corleymanz** [comment]
With angular 8 this is no issue. And production build is oke

**Comment by filipesilva** [comment]
Awesome, thanks for letting us know!
