### ISSUE TITLE
Build: production build output isn't correct with app shell and scss

### ISSUE THREAD

**Issue by ahnpnl** [angular/angular-cli#16363]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Not sure

### Description
When importing an scss file into any scss files in app, build app shell doesn't generate correct outputs anymore. 

## 🔬 Minimal Reproduction
1. Clone example [repo](https://github.com/ahnpnl/ng-app-shell-bug-scss)
2. Install dependencies with `yarn`
3. Open `app.component.scss` and notice that there is an scss import `@import "color-palette";`
4. Run `ng run my-app:app-shell:production` and observe an error in the console.
5. Open `dist` folder and observe that there is only one folder `my-app`.
6. Delete `@import "color-palette";` in `app.component.scss`.
7. Run `ng run my-app:app-shell:production` and observe no error in the console.
8. Open `dist` folder and observe that there are 2 folders `my-app` and `my-app-server`.

## 🔥 Exception or Error
Screenshot of error in console in step 4
![image](https://user-images.githubusercontent.com/27772165/70234247-8726fd00-1760-11ea-8957-d450b3647635.png)

Screenshot of build output in step 5
![image](https://user-images.githubusercontent.com/27772165/70234269-98700980-1760-11ea-8ba6-5615b726f809.png)

Screenshot of build output in step 8
![image](https://user-images.githubusercontent.com/27772165/70234292-a1f97180-1760-11ea-9505-37f4b2b6f0f9.png)

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.20
Node: 10.17.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
**N.A.**

**Comment by alan-agius4** [comment]
Hi, most likely the issue is that in your `server` target you don't have the `stylePreprocessorOptions` defined like you have in your `build` builder.

In `angular.json` try adding the below to `projects` -> `architect` -> `server` -> `options`:
```
"stylePreprocessorOptions": {
  "includePaths": [
    "src/assets/scss/base"
  ]
}
```

**Comment by ahnpnl** [comment]
hi @alan-agius4 , my reproduce repo does have the [option](https://github.com/ahnpnl/ng-app-shell-bug-scss/blob/09e3e1c129ac76b9b79faf99387ceb07679bba4c/angular.json#L34) you mentioned

**Comment by alan-agius4** [comment]
Hi @ahnpnl, in your reproduction it is only in the `build` target and is missing in the `server` target

https://github.com/ahnpnl/ng-app-shell-bug-scss/blob/09e3e1c129ac76b9b79faf99387ceb07679bba4c/angular.json#L131-L153

**Comment by ahnpnl** [comment]
thanks @alan-agius4 , it works now with the solution you provided. So I assume anything related to `stylePreprocessorOptions` the project has in `projects` -> `architect` -> `build` -> `options` has to be copied to `projects` -> `architect` -> `server` -> `options` ?

**Comment by alan-agius4** [comment]
Depends, only if the include paths are used for component style sheets.

**Comment by ahnpnl** [comment]
👍 thanks, I will close the issue.
