### ISSUE TITLE
IE11 error when build with production option

### ISSUE THREAD

**Issue by liffeyd** [angular/angular-cli#16372]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not tested in previous versions

### Description

https://github.com/angular/angular-cli/issues/14777 is said to have been fixed by https://github.com/angular/angular-cli/pull/14951. Unfortunately I am having the same problem as #14777.

If I use ng serve -c es5 the app displays as expected in IE 11 However, I am unable to get the app to run in IE 11 under IIS.

**References:**
[https://stackoverflow.com/questions/56379067/how-do-i-support-internet-explorer-in-an-angular-8-application](url)
[https://social.msdn.microsoft.com/Forums/en-US/42683470-1d97-4fc1-8248-7cd030bf84e8/how-to-let-angular-8-app-work-in-internet-explorer-11?forum=iewebdevelopment](url)

I have followed steps found elsewhere to add a file named tsconfig-es5.app.json containing:

**tsconfig-es5.app.json**
<pre>
<code>
{ 
  "extends": "./tsconfig.app.json",
   "compilerOptions": {     
       "target": "es5"  
    }
}
</code>
</pre>

**browserlist** to target IE 11:
<pre>
<code>
> 0.5%
last 2 versions
Firefox ESR
not dead
IE 9-11 # For IE 9-11 support, remove 'not'.
</pre>
</code>

## 🔬 Minimal Reproduction

Simple steps to reproduce this bug.

- Create a new app.
- Modify browserslist to allow IE 9-11
- Moify angular.json to include es5 reference
- add file tsconfig-es5.app.json

**angular.json**
<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "testProjectOne": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/testProjectOne",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss",
              "node_modules/@fortawesome/fontawesome-free/scss/solid.scss",
              "node_modules/@fortawesome/fontawesome-free/scss/regular.scss",
              "node_modules/@fortawesome/fontawesome-free/scss/brands.scss",
              "node_modules/ng-uikit-pro-standard/assets/scss/bootstrap/bootstrap.scss",
              "node_modules/ng-uikit-pro-standard/assets/scss/mdb.scss",
              "node_modules/animate.css/animate.css",
              "src/styles.scss"
            ],
            "scripts": [
              "node_modules/chart.js/dist/Chart.js",
              "node_modules/easy-pie-chart/dist/easypiechart.js",
              "node_modules/screenfull/dist/screenfull.js",
              "node_modules/hammerjs/hammer.min.js"
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            },
            **"es5": {
              "tsConfig": "./tsconfig-es5.app.json"
            }**
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "testProjectOne:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "testProjectOne:build:production"
            },
            **"es5": {
              "browserTarget": "testProjectOne:build:es5"
            }**
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "testProjectOne:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "testProjectOne:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "testProjectOne:serve:production"
            }
          }
        }
      }
    }},
  "defaultProject": "testProjectOne"
}
</code></pre>
## 🔥 Exception or Error

<pre><code>
SCRIPT438: Object doesn't support property or method 'bind'
runtime-es5.js (143,11)

SCRIPT1010: Expected identifier
polyfills-es5.js (9673,24)

SCRIPT1028: Expected identifier, string or number
scripts.js (6481,5)

SCRIPT1028: Expected identifier, string or number
vendor-es5.js (199,13)

SCRIPT1010: Expected identifier
main-es5.js (348,24)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.20
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.803.18
@angular-devkit/build-angular       0.803.18
@angular-devkit/build-optimizer     0.803.18
@angular-devkit/build-webpack       0.803.18
@angular-devkit/core                8.3.18
@angular-devkit/schematics          8.3.20
@angular/animations                 8.2.13
@angular/cli                        8.3.20
@angular/common                     8.2.13
@angular/compiler                   8.2.13
@angular/compiler-cli               8.2.13
@angular/forms                      8.2.13
@angular/language-service           8.2.13
@angular/platform-browser           8.2.13
@angular/platform-browser-dynamic   8.2.13
@angular/router                     8.2.13
@ngtools/webpack                    8.3.18
@schematics/angular                 8.3.20
@schematics/update                  0.803.20
rxjs                                6.4.0
typescript                          3.5.3
webpack                             4.39.2

</code></pre>

**Anything else relevant?**
Error on IE 11.476.18362.0

Using 
**ng serve -c es5** 

will show the app in FF, Chrome, IE 11, Edge 
at http://localhost:4200

Using 
**ng serve**
will show the app in FF, Chrome, Edge but **NOT** in IE 11
at http://localhost:4200
Console shows no error.

**Test IIS site**
http://angulartest/

ng build --prod

This produces, in the dist folder, the following:

-a----       06/12/2019     14:58            916 index.html
-a----       06/12/2019     14:58          56588 main-es2015.js
-a----       06/12/2019     14:58          50463 main-es2015.js.map
-a----       06/12/2019     12:08           6346 runtime-es5.js
-a----       06/12/2019     12:08           6286 runtime-es5.js.map
-a----       06/12/2019     14:58         393984 scripts.js
-a----       06/12/2019     14:58         507929 scripts.js.map
-a----       06/12/2019     14:58        3114412 styles-es2015.js
-a----       06/12/2019     14:58        3292961 styles-es2015.js.map
-a----       06/12/2019     12:08        3121153 styles-es5.js
-a----       06/12/2019     12:08          13253 styles-es5.js.map
-a----       06/12/2019     14:58        5963666 vendor-es2015.js
-a----       06/12/2019     14:58        7040238 vendor-es2015.js.map
-a----       06/12/2019     14:58        8215396 vendor-es5.js
-a----       06/12/2019     14:58        3518737 vendor-es5.js.map

IIS is mapped to D:\Angular\testProjectOne\dist\testProjectOne

The app works fine in Chrome and Firefox
5 errors shown above display in IE 11 console
Edge complains it cannot reach the page!

**Comment by clydin** [comment]
To support IE11 the only change needed for a newly generated project (using 8.x+) is to adjust the browserslist.  The build command will then generate a compatible build by leveraging differential loading.  The serve command intentionally does not support differential loading.  Its primary purpose is development activity typically with a browser containing modern development tools as well as a focus on rebuild performance.

The output for a production build shown above also appears to be incorrect for a new project (as well as for the configuration file given above).  The output of a new project is as follows:
```
15536   Dec  6 11:00 3rdpartylicenses.txt
948     Dec  6 11:00 favicon.ico
803     Dec  6 11:00 index.html
173260  Dec  6 11:00 main-es2015.c43e792866e118b69de1.js
194226  Dec  6 11:00 main-es5.c43e792866e118b69de1.js
37293   Dec  6 11:00 polyfills-es2015.2987770fde9daa1d8a2e.js
125675  Dec  6 11:00 polyfills-es5.6696c533341b95a3d617.js
1485    Dec  6 11:00 runtime-es2015.edb2fcf2778e7bf1d426.js
1485    Dec  6 11:00 runtime-es5.edb2fcf2778e7bf1d426.js
0       Dec  6 11:00 styles.3ff695c00d717f2d2a11.css
```

**Comment by liffeyd** [comment]
Clydin, thanks for replying.  I have seen file names similar to those you show. In the last build before my post they were as listed. However, I had been trying different things along the way. I will create another new project soon and test.

**Comment by liffeyd** [comment]
Clydin,

I have done a clean test and initially it failed. It seems that I was caught out by **IE11 Document mode defaults to IE7**: 
[https://stackoverflow.com/questions/27272454/ie11-document-mode-defaults-to-ie7-how-to-reset](url)

Once I realised my mistake, all is good.

Thank you :)

**Comment by filipesilva** [comment]
Glad to hear it's sorted, let us know if there's still something odd going on.
