### ISSUE TITLE
ng xi18n isn't extracting localized messages when using $localize inside component ts files

### ISSUE THREAD

**Issue by josuerios** [angular/angular-cli#16375]
# 🐞 Bug report / 🚀Feature request

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [X] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

``ng xi18n`` isn't extracting localized messages when using ``$localize`` inside component ts files.

## 🔬 Minimal Reproduction
1. Create a Angular v9 Ivy enabled application.
2. Add `@angular/localize` (`ng add @angular/localize`)
3. Add a localized message in a component HTML template using `i18n` attribute (`<h2 i18n="@@works">This works</h2>`). 
4. Add a localized message in a component ts file using `$localize` (```this.message = $localize`:@@anId:a basic message`;```)
5. Execute ``ng xi18n``. 
6. Only the HTML template messages are being extracted.

Manually adding the non extracted translations and building the application works as expected but running ``ng xi18n`` again will erase them.

I've created a minimal GitHub repository with the reproduction of the issue : [ivy-xi18n-issue](https://github.com/josuerios/ivy-xi18n-issue)

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.5
Node: 10.17.0
OS: darwin x64

Angular: 9.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.5
@angular-devkit/build-angular     0.900.0-rc.5
@angular-devkit/build-optimizer   0.900.0-rc.5
@angular-devkit/build-webpack     0.900.0-rc.5
@angular-devkit/core              9.0.0-rc.5
@angular-devkit/schematics        9.0.0-rc.5
@ngtools/webpack                  9.0.0-rc.5
@schematics/angular               9.0.0-rc.5
@schematics/update                0.900.0-rc.5
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Comment by clydin** [comment]
Using localize directly is not currently supported by the framework.  It is being evaluated for future inclusion within the framework.  However, for 9.0 the attribute usage is the recommended and supported localization method.

**Comment by josuerios** [comment]
Thanks for the info @clydin. Are there any plans for including it in a minor release of 9.x?

**Comment by petebacondarwin** [comment]
The plan is to release a new message "extractor" for 9.1.0 - there is already a PR in the works here https://github.com/angular/angular/pull/32912

In the meantime (for 9.0.0) you can assume that `$localize` is an internal implementation thingy.

That being said, you can still use `$localize` in your application code, it is just that you would have to work out the message id from the warnings that you get during translation. (Just don't tell anyone I said that)

**Comment by josuerios** [comment]
Good news! Thanks @petebacondarwin, I'll close this issue now.

**Comment by mstawick** [comment]
If someone bumps into this issue, this might be helpful.

What I did is I've created a `TranslationComponent`, in which I'll declare all the code translations, ex.:

`<span i18n>Some translation</span>`

Then when in code I write:
```
$localize`Some translation`
```

everything works "out of the box" because ID is the same.
