### ISSUE TITLE
"ng build --prod" generates two same chunks

### ISSUE THREAD

**Issue by ddydeveloper** [angular/angular-cli#16373]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem...
![image](https://user-images.githubusercontent.com/28873881/70333193-16f9a380-1854-11ea-892d-acab4a75d07b.png)

BTW: If I remove node_modules folder, call **yarn install** and **ng build --prod** all works fine.

## 🔬 Minimal Reproduction

1. yarn install
2. ng build --prod (all chunks created as expected)
3. clean **dist** directory
4. ng build --prod 

## 🌍 Your Environment
```
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

**Anything else relevant?**
tsconfig.json:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2018",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
```

**Comment by clydin** [comment]
The latest version of the CLI (8.3.20) should help with this issue.

However, please also note that anything above a target of ES2015 is not officially supported and will dramatically reduce the set of browsers that the application can use.  Even the latest browsers may not fully implement the complete ES2018 standard or can contain defects related to some of the features.  Native async/await is also not supported with Zone.js and has the potential of causing application errors and/or incorrect behavior at runtime.

**Comment by ddydeveloper** [comment]
@clydin thank you. As you said CLI (8.3.20) works in a proper way. 

BTW I wasn't aware of all the stuff above target ES2015 is not oficially supported, good point thank you
