### ISSUE TITLE
Can't build library importing uuid

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#16378]
This is a description of the problem along with the variations attempted:

https://stackoverflow.com/questions/59221867/angular-build-results-in-error-cannot-call-a-namespace-v1

This is the repository containing the code:
https://github.com/fireflysemantics/slice/tree/angular-package-format/angular-package-format-workspace

The library is `projects/slice` .  If I try this import:

```
import * as v1 from "uuid/v1";
```

The tests run but Angular will not build the package.  The error logged is:

> Error: Cannot call a namespace ('v1')

**Comment by fireflysemantics** [comment]
So I decided to refactor my own library to confirm to the APF ... but these compiler restrictions on software that was working fine in all demoes seem a bit excessive ...

**Comment by alan-agius4** [comment]
@fireflysemantics, `uuid` exports a `v1` from the primary entrypoint. https://github.com/kelektiv/node-uuid/blob/master/index.js

Using the below statement should fix the problem;

```ts
import { v1 } from "uuid";
```

With the following import `import * as v1 from "uuid/v1";` `v1` is a namespace  and rollup doesn't allow this to be invoked.

https://rollupjs.org/repl/?version=1.27.8&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMHYxJTIwZnJvbSUyMCU1QyUyMnV1aWQlMkZ2MSU1QyUyMiUzQiU1Q252MSgpJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=
