### ISSUE TITLE
How to prevent build with there are tslint errors?

### ISSUE THREAD

**Issue by hmendezm** [angular/angular-cli#16391]
Question
Hi everyone,

I am working in an angular 8 app that has tslint rules defined. The rules are working very nice when developers are coding but the problem that I have is the ng serve and ng build allow developers to build the app although there are TSlint errors. is there a way to force Tslint rules when the project is building so developers have to fix the TSlint errors before they can see in the browser?

best
Hmendezm

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
