### ISSUE TITLE
"Cannot read property 'loadChildren' of undefined" error on first compilation only

### ISSUE THREAD

**Issue by benjamincombes** [angular/angular-cli#16399]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9rc1

### Description

When compiling project since Angular 9 rc2 & Angular 8 lastest releases, first ```ng serve``` or ```ng build``` always fail.
But there's a fix: for ```ng serve```, when commenting any code line, error disappear by itself and all next compilations work, even after restoring commented code.
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

I only managed to reproduce this bug in a real life project. It did work with first versions of Angular 9 rc, and started having this bugs with rc2. Now the problem also occurs with angular 8.3.20.
This is the only error message, no clearer description from Angular CLI, so I have absolutely no idea where the error comes from...

## 🔥 Exception or Error
<pre><code>

ERROR in Cannot read property 'loadChildren' of undefined
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.20
Node: 10.15.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/fire                     5.2.3
@angular/http                     7.2.15
@angular/material                 8.2.3
@ngtools/webpack                  8.3.20
@schematics/angular               8.0.0
@schematics/update                0.803.20
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

I know minimal reproduction should be included: however I could'nt see what makes this happen, and was unable to reproduce the bug with a simple project. I have nothing more than this error message that disappears by itself after first compilation...

**Comment by alan-agius4** [comment]
Hi @benjamincombes, thanks for opening an issue. Unfortunately without a minimal reproduction we will be unable to look at this.

**Comment by benjamincombes** [comment]
Hi, I know and I am sorry not to be able to provide one, but in this case, as explained above, I could not reproduce it on a simple project, and as the error is absolutely vague, I have no error of what part of the application cause the error (my project has 700+ classes and was working fine)...
Is there anything else I could do, like giving advanced logs, sending screencasts, or any other thing...? I have absolutely no clue of how to fit in your standards for such a case that only occurs in a real-life project, and with no precise error message.
But the fact that I get an error message, that it disappears when commenting / uncommenting any part of my code, and that it finally works on the same code that was failing at first, makes it really really look like it comes from the cli, and not the code itself. Thanks for your help!

**Comment by alan-agius4** [comment]
@benjamincombes, for starters, can you share the code the you are commenting to make your build work?

**Comment by benjamincombes** [comment]
Hi @alan-agius4, in fact I can comment any line of code, it does the same! When using ```ng serve```, I can comment a console.log for example, or any part of the code in any .ts file, and the second and next compilations work perfectly fine! So that's the workaground I have for ```ng serve```, comment anything, then uncomment, and everything works fine. But I can't apply it to ```ng build```.

**Comment by nadavsinai** [comment]
from my experience you can get much better error messages for such if your run with --aot
it's usually a missing dependency

**Comment by benjamincombes** [comment]
Hi @nadavsinai , thanks for your help; however, last rc released just fixed the issue, so I'll stay with it and close the issue for now!
