### ISSUE TITLE
how to remove unused code form js files build by angular?

### ISSUE THREAD

**Issue by RabiRanaEF** [angular/angular-cli#16398]
how i can remove unused code in main.js and vendor.js
![Screenshot (200)](https://user-images.githubusercontent.com/55832523/70434493-2a03b200-1aa6-11ea-8d14-bf490d8aded1.png)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
