### ISSUE TITLE
3rd party libs docs

### ISSUE THREAD

**Issue by jkuri** [angular/angular-cli#164]
We should write documentation how to use `ng install` and `ng uninstall` commands and also how to prepare library to be compatible with. 
Note that as of TypeScript 1.8.0 bundler script won't be needed anymore http://blogs.msdn.com/b/typescript/archive/2016/01/28/announcing-typescript-1-8-beta.aspx. 
@NathanWalker I hope you will soon have time to help work on it.

**Comment by filipesilva** [comment]
I saw that bundling feature for 1.8. *Very* nice.

**Comment by NathanWalker** [comment]
Lets take the conversation to Skype... I see your message there :+1:
