### ISSUE TITLE
 Function calls are not supported in decorators

### ISSUE THREAD

**Issue by varuncrat** [angular/angular-cli#16408]
I am getting ' Function calls are not supported in decorators but 'ɵmakeDecorator' was called' when I ma running the following command on command prompt:
ng build --prod --aot

Please provide the solution or reason to resolve this issue.
Thank you!

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
