### ISSUE TITLE
Make "ng new" use RC5

### ISSUE THREAD

**Issue by wtfuii** [angular/angular-cli#1640]
When running "ng new", the newly generated package.json will include RC4 dependencies. These should be bumped to RC5, right?

My environment:
Windows 7 32bit
angular-cli: 1.0.0-beta.10
node: 6.3.1
os: win32 ia32

**Comment by neilhem** [comment]
update angular-cli with `npm install --global angular-cli@1.0.0-beta.11-webpack.2`

**Comment by masaanli** [comment]
@neilhem  ah webpack.2 is RC5 :)

**Comment by wtfuii** [comment]
Yup, that's working, but it should be part of the default `npm install angular-cli` command.

**Comment by rickysullivan** [comment]
I think that's because it's in beta @wtfuii

**Comment by aciccarello** [comment]
@wtfuii Yeah, once the webpack build is out of beta, it will become the default.

**Comment by kylecordes** [comment]
I've always found this a bit confusing, though by always I mean, for the last months. CLI itself is beta. But it seems like for now the webpack variant, which is obviously the primary development path (it is in master, it is not even a branch anymore) is a kind of "beta of a beta". So are we waiting for the webpack variant to be out of "beta beta", so it can become CLI beta.12 or whatever? Or are we going to be stuck with this install "@webpack"  all the way until CLI itself is out of beta?

**Comment by aciccarello** [comment]
I agree that the beta of a beta terminology it is confusing, I should have described it differently. My understanding of the team's intentions is that the webpack version will become the default within a release or two. Because it's a big change they wanted some extra testing.

**Comment by steven-fernandez** [comment]
So, what's the ETA for RC5 to be default?

**Comment by ibnzbssrckr** [comment]
FYI, I had to `npm uninstall -g angular-cli` prior to running the above command to avoid errors.

**Comment by tiagomatosweb** [comment]
Hi Guys, sorry for the dump question.
Does the command angular-cli@1.0.0-beta.11-webpack.2, mean that Angular Cli will get the package from another source, or it is a new version of Angular Cli itself?

**Comment by SenthilKumaranC** [comment]
I have unstalled old angular cliand cleared npm cache  and then installed the above mentioned version npm install --global angular-cli@1.0.0-beta.11-webpack.2 . But unable to run ng new command it is thorwing error saying that **cannot find module 'portfinder'**

**Comment by neilhem** [comment]
@SenthilKumaranC try repeat installing again & check that you use node 4+

**Comment by SenthilKumaranC** [comment]
@neilhem  Yes I am using Node 4+ only. I have tried again, but still not working

**Comment by SenthilKumaranC** [comment]
![image](https://cloud.githubusercontent.com/assets/6176707/17697277/7be9a596-63d1-11e6-807c-5985080bcf6b.png)

**Comment by SenthilKumaranC** [comment]
Do I need to install any specific version of typescript?

**Comment by neilhem** [comment]
Have you tried to uninstall global angular-cli with `npm uninstall -g angular-cli`?

**Comment by SenthilKumaranC** [comment]
Yes. I have used that command only. Also i have used npm cache clean

**Comment by SenthilKumaranC** [comment]
Uninstall , Cache Clean , Initiate installation
------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/6176707/17699389/0c15aad2-63de-11e6-94c8-f245f574b2ac.png)

Errors during Installation
------------------------

![image](https://cloud.githubusercontent.com/assets/6176707/17699524/d027a4fc-63de-11e6-9b93-79f9e820db06.png)

Error during ng new command
------------------------------------

![image](https://cloud.githubusercontent.com/assets/6176707/17699533/e35e65ba-63de-11e6-8a10-b808460cd3ab.png)

**Comment by istiti** [comment]
I installed 

npm install --global angular-cli@1.0.0-beta.11-webpack.2

to have rc.5 but is it normal when I tried to build it into dist folder, or when I tried to do 
ng serve

I have no /dist folder of my app to production?

**Comment by mattheffernan** [comment]
@SenthilKumaranC, make sure you have npm v3 installed. I had the same issue with npm v2.x

**Comment by SenthilKumaranC** [comment]
I am trying to upgrade to npm3... here also i am getting the same error...

![image](https://cloud.githubusercontent.com/assets/6176707/17727540/9866e016-6477-11e6-8ba7-5c7f8d1ca9a7.png)

**Comment by neilhem** [comment]
@SenthilKumaranC you do it wrong `npm i -g npm@latest`

**Comment by SenthilKumaranC** [comment]
Buddy Still it is working for me now..  thanks a lot

I have given elevated priviliges to command prompt....

npm install -g npm3
npm3 install -g angular-cli@webpack worked for me...

thanks a lot @neilhem

**Comment by SenthilKumaranC** [comment]
Thanks again worked with npm@latest

**Comment by bisubus** [comment]
It is unnecessary to update NPM to 3 to resolve `portfinder` issue.

 `portfinder` can be installed manually in `angular-cli` directory after installation. Or be installed globally with `npm i -g portfinder`.

See also #1770.

**Comment by filipesilva** [comment]
The new webpack versions default to RC5. There will be a release soon that will make the the latest available version of `angular-cli` on npm, but currently they are under test.

**Comment by aggarwalankush** [comment]
@filipesilva I'm using the current angular-cli: 1.0.0-beta.11-webpack.2
I see many merged pull requiest resolving lot of issues such as global libraries, loadChildren...
Do you have any time estimate on next angular cli release?

**Comment by prsolucoes** [comment]
I need delete all my files to use the angular-cli with webpack and RC5? Or have any command to update my packages and other files?

**Comment by srivasrk** [comment]
Anyone still getting an error after deploying on github-pages? 
I get error: `Can't bind to 'my-item' since it isn't a known property of 'my-main-item'`. 
However, this works fine with ng serve. Only an issue when I deployed using "ng github-pages:deploy"

**Comment by neilhem** [comment]
Seems like deploy to github pages runs production build command `ng build -prod` which breakes custom element selectors

**Comment by filipesilva** [comment]
No estimate, but as soon as we can manage it.

@prsolucoes upgrade instructions can be found in https://github.com/angular/angular-cli#webpack-preview-release-update

There is an issue with github pages deploy though, which will only be fixed in the next webpack release.

**Comment by buminda** [comment]
npm install --global angular-cli@1.0.0-beta.11-webpack.2 worked for me as @neilhem  mentioned, it worked.

**Comment by guruh19** [comment]
@buminda Does the github pages deploy work for you?

**Comment by wlafrance** [comment]
after reading all of the above comments, I think I will wait until it is out of beta.

**Comment by rickysullivan** [comment]
It's out of RC as of last week. http://angularjs.blogspot.com.au/2016/09/angular2-final.html?m=1

**Comment by dhakshinait** [comment]
Hi, I have below version

angular-cli: 1.0.0-beta.2-mobile.4
node: 5.1.0
os: win32 x64

still, new app show '2.0.0-rc.1' only. can you please tell me what is wrong?

**Comment by neilhem** [comment]
@dhakshinait are you talking about angular or angular-cli?

**Comment by dhakshinait** [comment]
I am talking about angular version. I have latest angular-cli but I tried to create new app using angular cli command 'ng new APPNAME', it shows '2.0.0-rc.1' only and it is not creating angular app with latest version. can you please tell me what is the problem?. thanks.

**Comment by dhakshinait** [comment]
In angular package.json file:

   "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/http": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1",
    "@angular/router": "2.0.0-rc.1",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "^0.6.12"

**Comment by neilhem** [comment]
check global version of angular-cli, not local via `ng --version` outside of angular-cli project

**Comment by dhakshinait** [comment]
@neilhem , I have uninstalled the angular-cli and I have updated my npm, then I installed angular-cli once again below version

```
angular-cli: 1.0.0-beta.12-1
node: 5.1.0
os: win32 x64
```

now, 'ng new' create new app with below version

```
 "@angular/common": "2.0.0-rc.7",
    "@angular/compiler": "2.0.0-rc.7",
    "@angular/core": "2.0.0-rc.7",
    "@angular/forms": "2.0.0-rc.7",
    "@angular/http": "2.0.0-rc.7",
    "@angular/platform-browser": "2.0.0-rc.7",
    "@angular/platform-browser-dynamic": "2.0.0-rc.7"
```

I hope it is latest version right now. thanks for your help.

**Comment by neilhem** [comment]
@dhakshinait try to explicitly define version `npm install --global angular-cli@1.0.0-beta.16`

**Comment by dhakshinait** [comment]
@neilhem , thanks,. I have installed the latest version (1.0.0-beta.16) and now I am getting latest angular 2 version. 
    "@angular/core": "^2.0.0",

Thanks once again.

**Comment by berdon** [comment]
Can this information be put in the README? This is very confusing coming in as a new developer looking to use the generator only to find it's defaulting to rc1.
