### ISSUE TITLE
Broccoli cannot compile tests after upgrade to RC5

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#1641]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSx El Capitan 11.6

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 5.11.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
After updating to RC5 tests are not running by Broccoli

4. The log given by the failure. Normally this include a stack trace and some
   more information.
>Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Projects/WebApp/tmp/broccoli_type_script_compiler-input_base_path-ZIaFMlDP.tmp/0/src/app/+login/beta-stats/beta-stats.component.spec.ts (7, 3): Module '"/Projects/WebApp/node_modules/@angular/core/testing"' has no exported mng 'beforeEach'.
  /Projects/WebApp/tmp/broccoli_type_script_compiler-input_base_path-ZIaFMlDP.tmp/0/src/app/+login/beta-stats/beta-stats.component.spec.ts (7, 15): Module '"/Projects/WebApp/node_modules/@angular/core/testing"' has no exported mng 'beforeEachProviders'.
  /Projects/WebApp/tmp/broccoli_type_script_compiler-input_base_path-ZIaFMlDP.tmp/0/src/app/+login/beta-stats/beta-stats.component.spec.ts (8, 3): Module '"/Projects/WebApp/node_modules/@angular/core/testing"' has no exported mng 'describe'.
  /Projects/WebApp/tmp/broccoli_type_script_compiler-input_base_path-ZIaFMlDP.tmp/0/src/app/+login/beta-stats/beta-stats.component.spec.ts (8, 13): Module '"/Projects/WebApp/node_modules/@angular/core/testing"' has no exported mng 'xdescribe'.
  /Projects/WebApp/tmp/broccoli_type_script_compiler-input_base_path-ZIaFMlDP.tmp/0/src/app/+login/beta-stats/beta-stats.component.spec.ts (9, 3): Module '"/Projects/WebApp/node_modules/@angular/core/testing"' has no exported mng 'expect'....

**Comment by mithun-daa** [comment]
The jasmine methods are no longer part of the testing module. I fixed this by removing the import statements and making sure that the `jasmine` typings have been installed. The only other error you will run into after that is the `beforeEachProviders`. This has been deprecated and can be fixed as follows:
Before:
```
import {beforeEachProviders, it, describe, inject} from '@angular/core/testing';

describe('my code', () => {
  beforeEachProviders(() => [MyService]);

  it('does stuff', inject([MyService], (service) => {
    // actual test
  });
});
```
After:
```
import {addProviders, inject} from '@angular/core/testing';

describe('my code', () => {
  beforeEach(() => {
    addProviders([MyService]);
  });

  it('does stuff', inject([MyService], (service) => {
    // actual test
  });
});
```

More details here https://github.com/angular/angular/blob/master/CHANGELOG.md

**Comment by vapits** [comment]
Thank you @mithun-daa ,

I tried to solve it differently by moving to webpack and latest version of everything (angular-cli & angular). Tests are now working but router doesn't.

So I'm moving to this SO issue and closing this.
http://stackoverflow.com/questions/38896349/angular-2-rc5-angular-router-3-0-0-rc-1-invalid-configuration-or-a-bug

Thanks
