### ISSUE TITLE
Npm security alert with ng8

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular-cli#16421]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] e2e
- [ ] generate
- [ ] test
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 I am using the latest version of ng-cli. When I created a new app I get security alert

> found 3 moderate severity vulnerabilities

npm audit shows me this:

>  Moderate        Cross-Site Scripting
> Package         serialize-javascript
> Patched in      >=2.1.1
> Dependency of   @angular-devkit/build-angular [dev]
> Path            @angular-devkit/build-angular > terser-webpack-plugin >
                  serialize-javascript
> More info       https://nodesecurity.io/advisories/1426

## 🔬 Minimal Reproduction

Run the command: ng new app

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/16414
