### ISSUE TITLE
Terminal progress on multiple lines if line wraps

### ISSUE THREAD

**Issue by capc0** [angular/angular-cli#16445]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

not sure

### Description

follow up issue to https://github.com/angular/angular-cli/issues/14623
I am experiencing the same problem with line wrapping

## 🔬 Minimal Reproduction
Open VS Code embedded GIT Bash terminal and split the terminal 4 times (so that you have 4 very small terminals side-by-side).
Run e.g. ng serve

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.9
Node: 10.16.0     
OS: win32 x64     
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
I have had this issue since multiple months but never cared too much about it. But now I noticed that the line wrapping stuff drastically decreases performance (ng serve takes twice as long with this bug)

**Comment by ChristopherKiss** [comment]
@capc0 ,

As per on #14623 I was advised to report this on webpack github which I did.

https://github.com/webpack/webpack/issues/9221

This was fixed in commit: https://github.com/webpack/webpack/pull/9225/commits/7aefa64b0aa6092ea2446865d96a7459fe018cd2

Released in v4.35.0 of wepack, if you look at your webpack version you are on v4.29.0.

You can update angular to a new version which has an updated webpack or update webpack manually and see if it doesn't break anything.

FYI @alan-agius4

**Comment by alan-agius4** [comment]
@capc0 , can you kindly confirm that this is no longer reproducible in version 9? 

Thanks.

**Comment by capc0** [comment]
Yes, I can confirm that. It also is fixed with angular 8.1.0 which uses webpack 4.35.2
