### ISSUE TITLE
ng build --prod not displaying angular material UI

### ISSUE THREAD

**Issue by Maulik009** [angular/angular-cli#16457]
# 🐞 Bug report

### Command (mark with an `x`)

ng build --prod

- [ ] new
- [X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Don't know

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
install angular material and run command ng build --prod. So you can see that dist is generated but on localhost: 4200, the angular material UI getting disturbs 

## 🔥 Exception or Error
<pre><code>

ERROR TypeError: ctor is not a constructor
    at createClass (main.720046d….js:37458)
    at createDirectiveInstance (main.720046d….js:37341)
    at createViewNodes (main.720046d….js:38558)
    at Object.createEmbeddedView (main.720046d….js:38466)
    at TemplateRef_.push../node_modules/@angular/core/fesm5/core.js.TemplateRef_.createEmbeddedView (main.720046d….js:37051)
    at ViewContainerRef_.push../node_modules/@angular/core/fesm5/core.js.ViewContainerRef_.createEmbeddedView (main.720046d….js:36917)
    at NgIf.push../node_modules/@angular/common/fesm5/common.js.NgIf._updateView (main.720046d….js:23677)
    at NgIf.set [as ngIf] (main.720046d….js:23645)
    at updateProp (main.720046d….js:37613)

</code></pre>

## 🌍 Your Environment
<pre><code>

 Angular CLI: 6.2.9
Node: 8.5.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.8.9
@angular-devkit/build-angular      0.8.9
@angular-devkit/build-optimizer    0.8.9
@angular-devkit/build-webpack      0.8.9
@angular-devkit/core               0.8.9
@angular-devkit/schematics         0.8.9
@angular/cdk                       6.4.7
@angular/cli                       6.2.9
@angular/fire                      5.2.3
@angular/material                  6.4.7
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   6.2.9
@schematics/angular                0.8.9
@schematics/update                 0.8.9
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.16.4
 

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @Maulik009, you seem to be using an older version of the CLI since than a lot of bug have been fixed. Can you please update to version 8 and try again?

**Comment by Maulik009** [comment]
@alan-agius4 my entire project is built on angular 6 and related dependencies. Is it going to impact on dependencies if I update my angular cli version ?

**Comment by alan-agius4** [comment]
@Maulik009, yeah you’d need to update other dependencies as well

**Comment by Maulik009** [comment]
For now I managed by using following command : 
ng build --prod --aot=false --build-optimizer=false

But anyhow angular team needs to be resolve this for version 6

**Comment by clydin** [comment]
While Angular 6 can still be used, it is no longer a supported version.  For further information, please see: https://angular.io/guide/releases

 Information regarding the update process can be found here: https://update.angular.io/

**Comment by alan-agius4** [comment]
Closing as per above
