### ISSUE TITLE
Object is possibly 'null' when strict + using getComputedStyle

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular-cli#16451]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] serve

### Is this a regression?
don't know

### Description
Error "Object is possibly 'null'"
when ng serve and using getComputedStyle in code.

## 🔬 Minimal Reproduction
ng new project --strict

replace AppComponent to below 

```
export class AppComponent implements OnInit {
  title = 'test';

  ngOnInit() {
    const el = document.getElementById('test');
    if (el !== null) {
      // const paddingTop1 = window.getComputedStyle(el).paddingTop!; // this can work
      const paddingTop1 = window.getComputedStyle(el).paddingTop; // this can't work
      const paddingTopNumber1 = +paddingTop1; // TS2531: Object is possibly 'null'
      console.log(paddingTopNumber1);
    }
  }
}
```

ng serve --open

error will show

![image](https://user-images.githubusercontent.com/8691013/70858746-d29c9080-1f42-11ea-9e3a-dd9086b2bf46.png)

  

## 🌍 Your Environment
Angular CLI: 9.0.0-rc.6
Node: 12.3.1
OS: win32 x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.6
@angular-devkit/build-angular     0.900.0-rc.6
@angular-devkit/build-optimizer   0.900.0-rc.6
@angular-devkit/build-webpack     0.900.0-rc.6
@angular-devkit/core              9.0.0-rc.6
@angular-devkit/schematics        9.0.0-rc.6
@ngtools/webpack                  9.0.0-rc.6
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

**Comment by clydin** [comment]
This is expected behavior.  The project's version of TypeScript (3.6.4) considers the `paddingTop` property of `CSSStyleDeclaration` to be either a string or null.  ([code reference](https://github.com/microsoft/TypeScript/blob/d0340313982fe15561f7ca7ca16c7141e658bc6a/lib/lib.dom.d.ts#L3004))
