### ISSUE TITLE
[RC.5] Missing component when building/serving production version. WEIRD!

### ISSUE THREAD

**Issue by dzonatan** [angular/angular-cli#1645]
```
angular-cli: 1.0.0-beta.11-webpack.2
node: 5.11.1
os: win32 x64

angular version: rc.5
```

## Just read/do repro steps
1.Create fresh project with `ng new`.
2.Add `anything.component.ts` in `src/app/shared` folder with the following content:
```js
import { Component } from '@angular/core';

@Component({
  selector: 'anything',
  template: 'Kim Jong-un'
})
export class AnythingComponent{ }
```
3.Add it to `app.module.ts` declarations:
```js
...
import { AppComponent } from './app.component';
import { AnythingComponent } from './shared/anything.component'; // <--- HERE

@NgModule({
  declarations: [
    AppComponent,
    AnythingComponent // <---- AND HERE
  ],
...
```
4.Add `anything` element to `app.component.html`:
```html
<h1>
  {{title}}
  <anything></anything> <!-- HERE -->
</h1>
```
5.Run `ng serve`. You should see `app works! Kim Jong-un`. Great!
6.Now the fun part. Run production version with `ng serve --prod`.  You will only see `app works!`. 

WHOOT? NO ERRORS! WHERE IS MY KIM??

**Comment by kylecordes** [comment]
I think this is the same problem as #1644 from a few minutes ago... which is the same also as https://github.com/angular/angular/issues/10618

**Comment by dzonatan** [comment]
Oh! You are right Kyle! Switching `AppComponent` with `AnythingComponent` solved the issue.
I'm closing this issue.

**Comment by abner** [comment]
The solution proposed in #1644 worked for me:

```
...
mangle: { screw_ie8 : true, keep_fnames: true }, //prod
```
