### ISSUE TITLE
How to refer local packages in angular-cli?

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#16472]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I want refer my local packages which has placed one directory in my computer and i want to refer this packages  in angular application

I have referred like below:

### package directory - `D:\today\dist`

```
"dependencies": {
    "@syncfusion/ej2-angular-buttons": "file:../dist"
  },
```

### angular-cli application directory - `D:\today\asdf`

When i try to give`npm i` packages get installed and also duplicate node_modules get installed inside my local packages. and throws below compilation error:
![AA](https://user-images.githubusercontent.com/36756050/71170014-52e32e80-2280-11ea-9073-83862affd70b.PNG)

## 🔬 Minimal Reproduction

1. download below sample
  
[sample.zip](https://github.com/angular/angular-cli/files/3983330/sample.zip)

2. paste below packages outside sample
[package.zip](https://github.com/angular/angular-cli/files/3983333/package.zip)

3. map this packages path  in angular application

```
"dependencies": {
    "@syncfusion/ej2-angular-buttons": "file:../package"
  },
```

4. then give `ng serve` command

## 🌍 Your Environment
<pre><code>
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
</code></pre>

**Comment by kumaresan-subramani** [comment]
when use `npm pack` for my package and  give that path application works fine

```
"dependencies": {
    "@syncfusion/ej2-angular-buttons": "file:../package/syncfusion-ej2-angular-buttons-17.2.48.tgz"
  },
```

**Comment by kumaresan-subramani** [comment]
https://stackoverflow.com/questions/14381898/local-dependency-in-package-json

**Comment by alan-agius4** [comment]
Kindly see: https://angular.io/guide/creating-libraries#linked-libraries

**Comment by kumaresan-subramani** [comment]
@alan-agius4 , still i didn't get it. Can you please explain it...!

**Comment by kumaresan-subramani** [comment]
@alan-agius4 , Can you update on this?
