### ISSUE TITLE
Question: SASS in WebPack version

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#1647]
it's not a feature or a bug but it;s a question because based on opened issues and docs I'm not sure if i have understand correctly.

I upgraded my project to angular-cli@webpack version that already includes lots and lots of styling (SASS). 
So until now the only thing that I had to change was the file name from `.css` to `.sass` and everything was there ready. But know I'm not sure how to proceed.

First of all all my styleUrls I change 'em to `.sass` otherwise Webpack was giving errors. But now there is almost no styling there (still some parts are styled thought.

What is the correct procedure for this with the webpack version?

**UPDATE**
It seems only :host elements are styled and not the childs.

**Comment by neilhem** [comment]
Have you set default extension to Sass via `ng set defaults.styleExt sass`?

**Comment by vapits** [comment]
Yes, I don't get error bu styling even for angular-material stuff that is already there is not working correctly.

**Comment by vapits** [comment]
If you want to use SASS you have to se encapsulation to none.

For example:
```
@Component({
  selector: 'app-root',
  encapsulation: ViewEncapsulation.None,
  templateUrl: 'app.component.html',
  styleUrls: ['../assets/styles/index.sass']
})
```
