### ISSUE TITLE
Auto restarting the application on proxy config change

### ISSUE THREAD

**Issue by jonuojha** [angular/angular-cli#16481]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
 Currently if I make any change to the proxy configuration file, I need to manually restart the application.

### Describe the solution you'd like
 If it's possible that the **ng serve** can detect the changes in proxy config file and restart itself automatically.

### Describe alternatives you've considered
 As of now, we have only one option "restarting the application manually".

**Comment by alan-agius4** [comment]
Hi, thanks for opening this feature request.

When changing any configuration file such as `angular.json`, `tsconfig.json` etc... `ng serve` or any other process needs to be restarted manually.

At this time, this out of the scope of the Angular CLI. We are very cautions which features to add as apart from the development time, this will incure support and maintenance time.

Let's re-consider this if we see if there is a bigger demand for this.
