### ISSUE TITLE
CSS Problem on --prod build when use custom-webpack

### ISSUE THREAD

**Issue by lihuabest** [angular/angular-cli#16485]
use @angular-builders/custom-webpack to export webpack.config.js hook，src/styles.css can't build with `ng build --prod`. @angular/cli version is `@angular/cli": "~8.2.2`, even i test latest.

![20191221093528](https://user-images.githubusercontent.com/1559817/71301107-656f7c00-23d6-11ea-8cbb-df6a58847f1b.png)

styles has no name and no file. this is simple code of webpack.config.js
`
    const path = require('path');

   module.exports = (config, options) => {
      config.plugins.push(spritePlugin);

      config.module.rules = config.module.rules.filter(
        rule => rule.test.toString() !== '/\\.css$/'
    );

    // CSS Module support
    config.module.rules.push({
        test: /\.(css)$/,
        use: [
            'style-loader',
            'css-loader',
        ],
    });

    return config
  };

`

code can't run with `ng build --prod`，to fix the problem i use `ng build --extract-css=false`， but lose some of performance. export webpack config, we can do more things like use postcss...

**Comment by clydin** [comment]
Third party builders are not supported by the Angular team.  If you are encountering issues while using one please contact the author of the builder.  In this case, the project can be found here: https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack
