### ISSUE TITLE
Error TypeError : s is not a function (In production build)

### ISSUE THREAD

**Issue by arcteezy** [angular/angular-cli#16487]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ x ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add 
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
I have created a local library which uses d3 for rendering different kinds of charts. It works in development server perfectly and triggers this error on production (both `ng serve --prod` and `ng build --prod`). I found it working when the build optimizer is disabled (`--build-optimizer=false`) but isn't a practical soultion.

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: s is not a function
    at n (main.b84455bd40b508af4917.js:1)
    at main.b84455bd40b508af4917.js:1
    at n.render (main.b84455bd40b508af4917.js:1)
    at n.ngAfterViewInit (main.b84455bd40b508af4917.js:1)
    at Vo (main.b84455bd40b508af4917.js:1)
    at Go (main.b84455bd40b508af4917.js:1)
    at Ko (main.b84455bd40b508af4917.js:1)
    at hu (main.b84455bd40b508af4917.js:1)
    at _u (main.b84455bd40b508af4917.js:1)
    at bu (main.b84455bd40b508af4917.js:1)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 6.2.9
Node: 12.13.1
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.16.4
</code></pre>

**package.json** (Application) : 
<pre><code>
{
  "name": "client",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "am-charts": "file:path_to_chart_lib/dist/am-charts/am-charts-0.0.1.tgz",
    "core-js": "^2.5.4",
    "d3": "^5.12.0",
    "d3-cloud": "^1.2.5",
    "rxjs": "~6.2.0",
    "topojson-client": "^3.1.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.8.0",
    "@angular/cli": "~6.2.5",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}
</code></pre>

**package.json** (Chart Library) :
<pre><code>
{
  "name": "am-charts",
  "version": "0.0.1",
  "peerDependencies": {
    "@angular/common": "^6.0.0-rc.0 || ^6.0.0",
    "@angular/core": "^6.0.0-rc.0 || ^6.0.0"
  },
  "dependencies": {
    "d3": "^5.12.0",
    "d3-cloud": "^1.2.5",
    "topojson-client": "^3.1.0"
  }
}
</code></pre>

**ng-package.json** (Chart Library) :
<pre><code>
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/am-charts",
  "whitelistedNonPeerDependencies": ["."],
  "lib": {
    "entryFile": "src/public_api.ts"
  }
}
</code></pre>

**Comment by alan-agius4** [comment]
Hi can you try to update to the latest stable version (8.3.20) and see if this is still reproducible?

While Angular 6 can still be used, it is no longer a supported version. For further information, please see: https://angular.io/guide/releases

Information regarding the update process can be found here: https://update.angular.io

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by arcteezy** [comment]
@alan-agius4  Do I have to update both the main application and the chart workspace? Or just the application is enough?

**Comment by alan-agius4** [comment]
If you have multiple workspaces, updating pplications’s workspace will suffice.
