### ISSUE TITLE
 Cannot find module '@angular/compiler-cli/ngcc'

### ISSUE THREAD

**Issue by mayurtikundi12** [angular/angular-cli#16498]
my package.json

{
  "name": "new-course",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.2.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.21",
    "@angular/cli": "~8.3.21",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.3.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~2.9.2"
  }
}

my angular version
Angular CLI: 8.3.21
Node: 13.5.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cli                      8.3.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.39.2

gives following error on ng serve

An unhandled exception occurred: Cannot find module '@angular/compiler-cli/ngcc'
Require stack:
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@ngtools/webpack/src/ngcc_processor.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@ngtools/webpack/src/index.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/typescript.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/index.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular-devkit/build-angular/src/browser/index.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular-devkit/build-angular/src/dev-server/index.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular/cli/models/architect-command.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular/cli/commands/serve-impl.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular-devkit/schematics/tools/index.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular/cli/utilities/json-schema.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular/cli/models/command-runner.js
- /home/ruyam/projects/secretprojects/courseman/newCourse/node_modules/@angular/cli/lib/cli/index.js
- /usr/lib/node_modules/@angular/cli/lib/init.js
- /usr/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-cmygeo/angular-errors.log" for further details.

**Comment by alan-agius4** [comment]
Angular CLI 8 is only compatible with Angular version 8.

For more info on how to update see: http://update.angular.io
