### ISSUE TITLE
[9.0.0-rc.7] Package install failed

### ISSUE THREAD

**Issue by olilutz** [angular/angular-cli#16492]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [x] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Works in lastest v8 (ubuntu/windows) and in v9 rc in windows

### Description

I installed @angular/cli@next in Ubuntu 19.10 and with every ng command that does package installation it fails with:
'Package install failed, see above. The Schematic workflow failed. See above.'

## 🔬 Minimal Reproduction

Install nodejs 12 from snap
Install <code>sudo npm i -g @angular/cli@next</code> also required  --scripts-prepend-node-path despite I set this true globally before.
Make a new angular project with ng new. Or ng g app or lib or ng add package or ng update package.
It always fails on package installation.

## 🔥 Exception or Error
<pre><code>
ng g app new-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [https://sass-lang.com/documentation/syntax#scss]
CREATE projects/new-app/browserslist (429 bytes)
CREATE projects/new-app/karma.conf.js (1023 bytes)
CREATE projects/new-app/tsconfig.app.json (218 bytes)
CREATE projects/new-app/tsconfig.spec.json (278 bytes)
CREATE projects/new-app/tslint.json (247 bytes)
CREATE projects/new-app/src/favicon.ico (948 bytes)
CREATE projects/new-app/src/index.html (292 bytes)
CREATE projects/new-app/src/main.ts (372 bytes)
CREATE projects/new-app/src/polyfills.ts (2838 bytes)
CREATE projects/new-app/src/styles.scss (80 bytes)
CREATE projects/new-app/src/test.ts (642 bytes)
CREATE projects/new-app/src/assets/.gitkeep (0 bytes)
CREATE projects/new-app/src/environments/environment.prod.ts (51 bytes)
CREATE projects/new-app/src/environments/environment.ts (662 bytes)
CREATE projects/new-app/src/app/app-routing.module.ts (246 bytes)
CREATE projects/new-app/src/app/app.module.ts (393 bytes)
CREATE projects/new-app/src/app/app.component.scss (0 bytes)
CREATE projects/new-app/src/app/app.component.html (25705 bytes)
CREATE projects/new-app/src/app/app.component.spec.ts (1062 bytes)
CREATE projects/new-app/src/app/app.component.ts (212 bytes)
CREATE projects/new-app/e2e/protractor.conf.js (808 bytes)
CREATE projects/new-app/e2e/tsconfig.json (226 bytes)
CREATE projects/new-app/e2e/src/app.e2e-spec.ts (640 bytes)
CREATE projects/new-app/e2e/src/app.po.ts (262 bytes)
UPDATE angular.json (7532 bytes)
✖ Package install failed, see above.
The Schematic workflow failed. See above.

</code></pre>

## 🌍 Your Environment
Ubuntu 19.10 wayland session
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 12.14.0
OS: linux x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
I think the problem occurs only with nodejs as snap. The cli install was the only one that needed 
--scripts-prepend-node-path explicitly set as option, other packages worked out of the box.

**Comment by KristijanZic** [comment]
I also face this issue is there a workaround?

**Comment by sunkanmii** [comment]
I ran into the same issue, but found out I had the cli(v8.0.0) installed locally. 

For Windows
If you have it installed locally, here are the steps I used to solve the generated error.
1. Run **npm uninstall -g @angular/cli** and **npm uninstall @angular/cli**.
2. Run **npm cache verify**
3. Reopen the editor and reinstall the angular cli using **npm install -g @angular/cli**.

It should work for windows (I haven't tried it for Linux, but I think it's still the same workaround).
The npm cache verify command took too long to finish for me while I had the cli version 8.0.0 installed in my local directory, but was quick when I uninstalled it on my locally.

Also, make sure you verify the cache for garbage collection of unneeded data, verification of contents in cache folder, and verifying the integrity of the cache index, and all cached data. 

Helpful Links
https://github.com/angular/angular-cli/issues/11366
https://docs.npmjs.com/cli-commands/cache.html

**Comment by talha281** [comment]
I have tried this but same issue occurs any one who knows some different ways to tackle this problem then  please help me!! 
I want to start my angular learning as soon as possible please!!!

**Comment by talha281** [comment]
> I also face this issue is there a workaround?

bro did you get your problem fixed or you are having same problem now  also.

**Comment by aliounefall96** [comment]
![angular](https://user-images.githubusercontent.com/53535264/78094149-5c258080-73c3-11ea-8ad4-9076572defe7.JPG)

Pourquoi a chaque fois je rencontre ce problème lorsque je veut débuté un projet angular

**Comment by bhargava-9963** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/40258982/78423753-4693ad80-7686-11ea-9f83-fdc8fa23d6d7.png)

**Comment by bommojuvishu** [comment]
I am also facing the same issue. I tried all the angular cli versions 7 ,8,9, none of them was able to create a new project .tried to change the node versions also 
presently i am using the v10.21.0.
Angular team should fix it ASAP

**Comment by bommojuvishu** [comment]
I also tried force clean the cache of the npm also

**Comment by kronosinc** [comment]
I also have the same issue currently trying to do a project with Angular.
My Angular version 10.0.8
Nodejs version 14.9.0

Help me fix!

![Screenshot from 2020-08-31 21-30-36](https://user-images.githubusercontent.com/26027292/91754133-980e7d00-ebd1-11ea-9c83-c4e6d4bdc154.png)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
