### ISSUE TITLE
Prod build process rebuilds multi-value CSS involving 'unset' into an invalid CSS.

### ISSUE THREAD

**Issue by totoguy** [angular/angular-cli#16497]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Possibly, not sure.

### Description

 Prod build process rebuilds multi-value CSS involving 'unset' into an invalid CSS, which is ignored by the browser.

## 🔬 Minimal Reproduction
Create a class with the following properties:
```
padding: unset;
padding-right: 30px;
```
After doing 'ng build --prod', the following invalid CSS is produced:
```
padding: unset 30px unset unset;
```

## 🔥 Exception or Error
Chrome rejects the CSS with an "invalid property value" error.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.19
Node: 12.13.0      
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.19
@angular-devkit/build-angular      0.803.19
@angular-devkit/build-optimizer    0.803.19
@angular-devkit/build-webpack      0.803.19
@angular-devkit/core               8.3.19
@angular-devkit/schematics         8.3.19
@angular/cdk                       7.1.1
@angular/cli                       8.3.19
@angular/flex-layout               7.0.0-beta.21
@angular/http                      7.1.3
@angular/material                  7.1.1
@angular/material-moment-adapter   7.1.1
@ngtools/webpack                   8.3.19
@schematics/angular                8.3.19
@schematics/update                 0.803.19
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

No.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. It's a defect from the CSS optimizer [ clean-css](https://github.com/jakubpawlowicz/clean-css). Please report this issue in their issue tracker.

As a workaround until the bug has been addressed, the section in question can be altered to add ignore comments to prevent the optimizer from modifying the rule. 

Example;

```css
/* clean-css ignore:start */
.foo {
  padding: unset;
  padding-right: 30px;
}
/* clean-css ignore:end */
```

**Comment by totoguy** [comment]
Thanks, I'll open an issue there. Although it looks like clean-css hasn't had a new version release for more than a year, so I'm not too optimistic on getting a fix any time soon...

**Comment by totoguy** [comment]
@alan-agius4 
I see my sentiments were already raised a year ago by an Angular Tools core member in #12408:
https://github.com/angular/angular-cli/issues/12408#issuecomment-426590146

Maybe it is time to consider switching to a new, actively maintained minifier?

**Comment by alan-agius4** [comment]
@totoguy, we are currently looking into the possibility in replacing the CSS minifier. unfortunately the choice is pretty limited and most of the projects are either looking for new owners or un-maintained.
