### ISSUE TITLE
ERROR in Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/mini-css-extract-plugin/dist/loader.js): TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by tharinduvindula** [angular/angular-cli#16502]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>
ERROR in Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/mini-css-extract-plugin/dist/loader.js):       
TypeError: Cannot read property 'replace' of undefined
    at normalizeBackSlashDirection (C:\project\tea supply chain mangement system\test2\node_modules\webpack\lib\RequestShortener.js:16:17)  
    at new RequestShortener (C:\project\tea supply chain mangement system\test2\node_modules\webpack\lib\RequestShortener.js:26:15)
    at new Compiler (C:\project\tea supply chain mangement system\test2\node_modules\webpack\lib\Compiler.js:195:27)
    at Compiler.createChildCompiler (C:\project\tea supply chain mangement system\test2\node_modules\webpack\lib\Compiler.js:548:25)        
    at Compilation.createChildCompiler (C:\project\tea supply chain mangement system\test2\node_modules\webpack\lib\Compilation.js:2100:24) 
    at Object.pitch (C:\project\tea supply chain mangement system\test2\node_modules\@angular-devkit\build-angular\node_modules\mini-css-extract-plugin\dist\loader.js:89:43)

</code></pre>

## 🌍 Your Environment
<pre><code>
"dependencies": {
    "@agm/core": "^1.0.0",
    "@angular/animations": "8.2.14",
    "@angular/cdk": "7.0.2",
    "@angular/common": "8.2.14",
    "@angular/compiler": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/http": "7.0.2",
    "@angular/material": "7.0.2",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/platform-server": "8.2.14",
    "@angular/router": "8.2.14",
    "@ngrx/effects": "^7.0.1",
    "@ngrx/entity": "^7.0.1",
    "@ngrx/router-store": "^7.0.1",
    "@ngrx/store": "^7.0.1",
    "@ngrx/store-devtools": "^7.0.1",
    "@types/base-64": "^0.1.3",
    "@types/jquery": "^3.3.31",
    "@types/utf8": "^2.1.6",
    "ajv": "6.4.0",
    "arrive": "2.4.1",
    "base-64": "^0.1.0",
    "bluebird": "^3.7.2",
    "bootstrap": "4.3.1",
    "bootstrap-material-design": "4.1.1",
    "bootstrap-notify": "3.1.3",
    "chartist": "0.11.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "ethereumjs-tx": "^1.3.7",
    "express": "4.16.3",
    "flag-icon-css": "^3.4.5",
    "fusioncharts": "^3.15.0",
    "fusionmaps": "^3.15.0",
    "googleapis": "^46.0.0",
    "hammerjs": "2.0.8",
    "intl": "^1.2.5",
    "jquery": "^3.4.1",
    "moment": "2.22.1",
    "ngx-uploadcare-widget": "^1.2.5",
    "node-pre-gyp": "^0.13.0",
    "npm-packlist": "^1.4.6",
    "nyc": "^14.1.1",
    "perfect-scrollbar": "^1.4.0",
    "popper.js": "1.14.3",
    "react-images-uploader": "^1.2.0-rc1",
    "rxjs": "6.5.3",
    "rxjs-compat": "6.3.3",
    "truffle-contract": "^4.0.4",
    "ts-type": "^1.2.9",
    "utf8": "^3.0.0",
    "web-animations-js": "2.3.1",
    "web3": "^1.2.2",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^8.4.1",
    "@angular-builders/dev-server": "^7.3.1",
    "@angular-devkit/architect": "^0.803.21",
    "@angular-devkit/build-angular": "^0.803.21",
    "@angular/cli": "^8.3.21",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "8.2.14",
    "@types/bootstrap": "3.3.32",
    "@types/chartist": "0.9.34",
    "@types/googlemaps": "3.30.8",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.14.9",
    "babel-cli": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "bip32": "^2.0.4",
    "bootstrap": "^4.1.0",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "chai-bignumber": "^3.0.0",
    "codelyzer": "4.2.1",
    "dotenv": "^8.2.0",
    "ganache-cli": "^6.1.8",
    "jasmine-core": "3.1.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.4.2",
    "karma-jasmine": "1.1.1",
    "lite-server": "^2.3.0",
    "mini-css-extract-plugin": "^0.9.0",
    "nodemon": "^1.19.4",
    "protractor": "^6.0.0",
    "solidity-coverage": "^0.6.7",
    "ts-node": "5.0.1",
    "tslint": "5.9.1",
    "typescript": "3.5.3",
    "webpack-merge": "^4.2.2"
  }

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, thanks for reporting this.

Please be aware that custom webpack configurations are not supported by the Angular tooling team. If the problem persists when not using a custom webpack configuration, please file a new issue and ensure you provide a minimal reproduction when filling out the issue template.

Thanks.
