### ISSUE TITLE
Javascript heap out of memory

### ISSUE THREAD

**Issue by abhayfrontend** [angular/angular-cli#16501]
![Selection_055](https://user-images.githubusercontent.com/46017583/71467937-5f203c00-27ea-11ea-984c-ce427034f5d0.png)
I am not being able to build with ng build --prod , javascript heap allocation issue

**Comment by George35mk** [comment]
I get the same issue

Make sure you update the node.js to the latest version
```cmd
node --version
v12.13.1
```


Then

Add update your `package.json` file

```json
"dependencies": {...
},
"devDependencies": {...
},
"resolutions": {
    "serialize-javascript": "^2.1.1"
}
```

and in your scripts section add this script

```json
"scripts": {
    "preinstall": "npx npm-force-resolutions"
}
```

> Run: **npm install**

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
