### ISSUE TITLE
cannot match any routes url Segments Visual Studio 2015

### ISSUE THREAD

**Issue by vickykrbu** [angular/angular-cli#16503]
I am running one MVC Project where i added Angular 8 Components. Now the scenario here is in MVC Project we used layout.cshtml page which applied to all views.

For testing purpose i added <app-root></app-root> in one of my view. When i am calling that view then i can see the title which i defined in app.component.html file is loaded but i can see also in that view have some console error which is present in attached screen shot.
![AngularError](https://user-images.githubusercontent.com/16345701/71479140-382d2e80-2819-11ea-82e8-1e703a66dbea.png)

Issue 1 is this console error and 2nd issue is my project is User session associated but when i refresh this view then the session is getting time out.
Below is angular.json file content:

`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "AngularData": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "./scripts/libs",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
              //"budgets": [
              //  {
              //    "type": "initial",
              //    "maximumWarning": "2mb",
              //    "maximumError": "5mb"
              //  },
              //  {
              //    "type": "anyComponentStyle",
              //    "maximumWarning": "6kb",
              //    "maximumError": "10kb"
              //  }
              //]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "AngularData:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "AngularData:build"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "AngularData:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "AngularData:serve"
          }
          //"configurations": {
          //  "production": {
          //    "devServerTarget": "AngularData:serve"
          //  }
          //}
        }
      }
    }},
  "defaultProject": "AngularData"
}`

Below is tsconfig.json file content:

`{
  "compileOnSave": false,
  "include": [
    "./src"
  ],
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./scripts/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}
`
Please let me know If you have any concern on above.
Thanks,
Vicky

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
