### ISSUE TITLE
ng build does not merge translations for interpolated strings

### ISSUE THREAD

**Issue by jaska45** [angular/angular-cli#16516]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. Translations for interpolated strings are not used any more.

### Description

If I have a string that uses string interpolation ng build does not use the translations when building the application.

I will get a warning
No translation found for "8370306245983482136" ("Hello {$INTERPOLATION}!").

The id in the warning is something that does not exist in the extracted XLIFF file. It seems that ng build calculates the id in a different way than xi18n.

## 🔬 Minimal Reproduction

Use any interpolation. For example

`<p i18n>Hello {{name}}!</p>`

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.7
Node: 12.2.0
OS: win32 x64
</code></pre>

**Comment by petebacondarwin** [comment]
Please check what versions of Angular  compiler and compiler-cli are. They need to match.

**Comment by jaska45** [comment]
They are both 9.0.0-rc.7

```
"@angular/compiler": "~9.0.0-rc.7",
"@angular/compiler-cli": "~9.0.0-rc.7",
```

**Comment by jaska45** [comment]
I made an experiment. I manually changed the id in the translated XLIFF to match the one the ng build marked "Not translation found" and now it worked.

**Comment by jaska45** [comment]
It was the @angular/localize version that was mismatching.

`"@angular/localize": "^9.0.0-rc.0",`

changed to 

`"@angular/localize": "^9.0.0-rc.7",`

Now translations work!

**Comment by clydin** [comment]
Since it appears you were able to get this sorted, I'm going to close the issue.  If you still run into any problems, please re-open.
