### ISSUE TITLE
ng generate can't support unknown options

### ISSUE THREAD

**Issue by cipchk** [angular/angular-cli#16510]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description

Due merge of #13480, `ng g` no longer support unknown options. In fact, `ng g` support unknown options, which helps us provide users with more customizable operations, such as:

```
ng g ng-alain:tpl <name> --swaggerPath=/my/pet
```

The `swaggerPath` is a parameter required by the user, but it's not a fixed value and can't be defined in the Schema.

**Comment by alan-agius4** [comment]
Hi @cipchk,

How would such “unknown” parameter be used in the schematic?

Can you please describe a use case?

**Comment by cipchk** [comment]
Hi @alan-agius4,

ng-alain provides users with a set of Schematics for generating business templates, one of which is the ability of the end-user developer to customize some templates for generation component.

For example, the developer would execute the following command:

```
ng g ng-alain:tpl <custom template name> <name> --myName=asdf --myAge=27
```

End-user developers need to write their own templates:

```html
<h1>My Component</h1>
Name: <%= extraArgs.myName %>
Age: <%= extraArgs.myAge %>
```

Reuse:

```html
<h1>My Component</h1>
Name: asdf
Age: 27
```

Where `extraArgs` equivalent to `args['--']` value, and the template is passed as is using` template() `.

This is just a very simple example. In fact, the way of using unknown options can be used in a `js` file, providing end-user developers with a more interesting development experience, such as: converting the Swagger API to Angular Service, etc.

**Comment by alan-agius4** [comment]
I think in such case we should handle `additionalProperties` when defined in the user schema. Similar to how it is done for the architect commands https://github.com/angular/angular-cli/blob/d9d233e39aac6c732eaddd92b324a7c32d659318/packages/angular/cli/models/architect-command.ts#L243
