### ISSUE TITLE
process index in i18n

### ISSUE THREAD

**Issue by ch4mpy** [angular/angular-cli#16514]
# 🚀 Feature request

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [X] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Description
index file is not yet processed by `i18n`. It could be useful to process a file such as:
```html
<!doctype html>
<html i18n-lang="language@@index-lang" lang="fr">
<head>
  <base i18n-href="baseHref@@base-href" href="/fr/">
  <meta charset="utf-8">
  <title i18n="index title@@index-title">Localized Title</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>
<body>
  <app-root></app-root>
</body>
</html>
```

### Describe the solution you'd like
process file referenced as `index` as any template in  

### Describe alternatives you've considered
I currently use an index file per locale

**Comment by clydin** [comment]
Both the `lang` and `baseHref` attribute are injected when localizing; with the later being fully configurable per locale.  This leaves the title.  An approach for dynamic titles is to use the [Title Service](https://angular.io/guide/set-document-title).  This allows the title to reflect the content present at any given application route.
For both server side rendered and many backend server setups, the index is also dynamically generated per request and may not exist on disk at all.  This would also be a potential solution as it allows for maximum configurability of the HTML sent to the client.

The index is a static HTML file and not an Angular template (which leverages HTML but is not strictly HTML and is more akin to code).  Angular templates are compiled and bundled into the application JavaScript at build time.  Whereas the index has no knowledge of the compilation process and nor does the Angular compiler have knowledge of the index.

Thank you for the feature request, however, this is not something the Angular Team is considering at this time.  However, adding a per locale option to customize the index title may be a worthwhile addition and will be considered for future inclusion.
