### ISSUE TITLE
Backend proxy mechanism breaks when adding line to 'assets' section in angular.json

### ISSUE THREAD

**Issue by berkon** [angular/angular-cli#16519]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Unknown

### Description
I'm using the proxying mechanism described here:

https://angular.io/guide/build#proxying-to-a-backend-server

in order to deflect PHP requests to a XAMPP server while using **ng serve -o** in my dev environment. This works fine until I'm adding this line:

`{ "glob": "*.php", "input": "src/php/", "output": "/" }`

like this:
```
"assets": [
    "src/favicon.ico",
    "src/assets",
    { "glob": "*.php", "input": "src/php/", "output": "/" }
],
```
to **angular.json** in order to have my php files copied automatically to **dist** folder at production.

## 🔬 Minimal Reproduction
* Setup a XAMPP server (e.g. Apache) on localhost on different port than 4200 (e.g. 80)
* Setup proxing like described in the link above
* Add line above to **angular.json**
* Run **ng serve -o**

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/28842661/71618890-0e318e80-2bc2-11ea-843a-65441fe2545f.png)
The strange thing is, that I'm only using **ng serve -o** for development. So adding that line which, from my understanding, should act only when running **ng build --prod**, should not have any impact on **ng serve -o**.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.21
Node: 12.14.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cdk                      8.2.3
@angular/cli                      8.3.21
@angular/material                 8.2.3
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
I'm running the XAMPP (Apache) server on port 80. Even though the screenshot shows that it is trying to connect to localhost:4200 in order to get the status.php output, this seems not to be a problem, because in "good case" as well, it connects to localhost:4200 and then probably get's re-directed internally to localhost:80

**Comment by berkon** [comment]
I was able to make it work when using "/php" (or any other directory name) instead of "/" as "output" in the assets array. Looks like the issue only shows up when trying to copy files to root folder!

**Comment by alan-agius4** [comment]
This is caused because webpack-dev-server will not proxy for existing paths. When copying the php files you are making sure these files exist.

As a workaround you should not copy the php files during development.

I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of https://github.com/webpack/webpack-dev-server project or file an issue on their issue tracker.

**Comment by berkon** [comment]
Thanks for your quick reply @alan-agius4, that's interesting to know.

I whish you a happy new year! :-)

**Comment by alan-agius4** [comment]
Thanks same to you 😀
