### ISSUE TITLE
apply templates to the current tree at a certain point

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#16532]
check the following example to understand the required feature.

```
return (tree, context) => {
  //we want to immediately apply this template to the current tree, so the tree itself contains the files that generated via templates, and tree.exists('files form templates') == true
   apply(url(`./files`), [template({})]);

 console.log(tree.exists('./templateFile.txt')) //this should outputs true;  `templateFile.txt` created by applying template into the current tree

 tree.create('anotherFile.txt','---')
 return tree; // now tree contains `templateFile.txt`

}
```
this can be useful if you want to use external functions (not included in collection.json) that return rules, and you want to apply these rules to your tree before dealing with it.

these functions are not included in collection.json, so we cannot use` externalSchematic()` nor `schematic()`

chaining the rules is not useful, because you may want to check some files from the previous applied rules before applying new rules.

**Comment by clydin** [comment]
Schematics are fundamentally a chain of rules.  A schematic itself is just a rule factory.  Rules can also be chained and nested to an arbitrary depth.  This allows for the behavior as described including using imported rules (or functions that create rules) and conditionally chaining rules based on prior behavior or supplied options.  The official Angular schematics apply these methods and can be used as examples.  They can be found here: https://github.com/angular/angular-cli/tree/master/packages/schematics/angular

**Comment by eng-dibo** [comment]
Thank you @clydin for your response, it will be nice from you if you mentioned me a guide how can I achieve this target.
