### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by suri66** [angular/angular-cli#16540]
### Description

 I tried to use extension .htm instead of .html, but it won't allowing.

WHY?

Below is my code.
```
@Component({
  selector: 'app-root',
  templateUrl: './app.component.htm',
  styleUrls: ['./app.component.less']
})

```
### I am getting this error

```
ERROR in ./app.component.htm 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
<p>
  app component works!
</p>
｢wdm｣: Failed to compile. 

```

**Angular Version:**
<pre><code>

Angular 7

</code></pre>

**Comment by alan-agius4** [comment]
What is the reason why you want to use `htm` instead of `html`?

**Comment by suri66** [comment]
> What is the reason why you want to use `htm` instead of `html`?
> 
> htm was mainly used in the old times when there was a compatibility issue with an OS that does not takes a four-letter extension file name.

Now I am not using .htm extension. My only concern is that it should allow to use .htm as well.

**Comment by alan-agius4** [comment]
Thanks for your request however, I don’t think we should support legacy file extensions (Pre Windows 98) unless there is a valid reason.

**Comment by dgp1130** [comment]
This pulls the thread on supporting a lot of different aspects (as one example generated files would need to use consistent extensions, etc.). Unless there is a major use case for this, we aren't planning to support this.
