### ISSUE TITLE
Angular2 cli webpack : difficult to troubleshoot issues

### ISSUE THREAD

**Issue by susandy** [angular/angular-cli#1655]
> Please provide us with the following information:
Hi, my angular2 cli:webpack application always create minification hence console errors are not at all helpful to troubleshoot issues. Is there any easy way that debugge shows me actual file instead of  main.bundle.js?
 
1.  Mac OSX - Yosemite

2. angular-cli: 1.0.0-beta.11-webpack
node: 6.2.2

4. The log given by the failure. Normally this include a stack trace and some
   more information.
--EXCEPTION: TypeError: jQuery(...).tooltip is not a function
main.bundle.js:74958 EXCEPTION: TypeError: jQuery(...).tooltip is not a functionBrowserDomAdapter.logError @ main.bundle.js:74958BrowserDomAdapter.logGroup @ main.bundle.js:74968ExceptionHandler.call @ main.bundle.js:69765(anonymous function) @ main.bundle.js:43429schedulerFn @ main.bundle.js:16513SafeSubscriber.__tryOrUnsub @ main.bundle.js:5591SafeSubscriber.next @ main.bundle.js:5540Subscriber._next @ main.bundle.js:5490Subscriber.next @ main.bundle.js:5454Subject._finalNext @ main.bundle.js:7459Subject._next @ main.bundle.js:7451Subject.next @ main.bundle.js:7408EventEmitter.emit @ main.bundle.js:16501onError @ main.bundle.js:46138onHandleError @ main.bundle.js:73134ZoneDelegate.handleError @ polyfills.bundle.js:3606Zone.runTask @ polyfills.bundle.js:3538ZoneTask.invoke @ polyfills.bundle.js:3702
main.bundle.js:74958 STACKTRACE:BrowserDomAdapter.logError @ main.bundle.js:74958ExceptionHandler.call @ main.bundle.js:69767(anonymous function) @ main.bundle.js:43429schedulerFn @ main.bundle.js:16513SafeSubscriber.__tryOrUnsub @ main.bundle.js:5591SafeSubscriber.next @ main.bundle.js:5540Subscriber._next @ main.bundle.js:5490Subscriber.next @ main.bundle.js:5454Subject._finalNext @ main.bundle.js:7459Subject._next @ main.bundle.js:7451Subject.next @ main.bundle.js:7408EventEmitter.emit @ main.bundle.js:16501onError @ main.bundle.js:46138onHandleError @ main.bundle.js:73134ZoneDelegate.handleError @ polyfills.bundle.js:3606Zone.runTask @ polyfills.bundle.js:3538ZoneTask.invoke @ polyfills.bundle.js:3702

**Comment by fhdk** [comment]
`ng serve --help`

```
--environment (String) (Default: development)
  aliases: -e <value>, -dev (--environment=development), -prod (--environment=production)
```
so you could try `ng serve -dev`

**Comment by susandy** [comment]
I tried taht as well but still same result. In angular cli previous version, I used to get all files in dist folder in development mode. Looks like, its removed in current version.

**Comment by filipesilva** [comment]
The problem here was that the sourcemaps were broken. We fixed that in https://github.com/angular/angular-cli/pull/1659.
