### ISSUE TITLE
Feature request: support .mjs output in Angular Package Format

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#16552]
use `.mjs` output in Angular Package Format rather than `.js`

**Comment by clydin** [comment]
The `.mjs` extension is a Node.js specific concept created to attempt to workaround module loading concerns within Node.js' experimental ES module support (which required a specific feature flag until recently in 13.2).  With the feature flag removed, the support of the extension has remained.  However, it is no longer necessary.   Package types (potentially nested) as well as package export definitions provide a far more comprehensive approach to defining a package's behavior when executing within Node.js.  This is also especially relevant when considering that commonJS support will eventually be removed from Node.js and then `.js` files will only be ES modules.

The Angular Package Format is also primary intended to describe a browser library (with only ES module code; optional UMD bundles withstanding) and not a Node.js library.  Browsers and Node.js both leverage JavaScript but they are fundamentally two different platforms.

**Comment by xiaoxiangmoe** [comment]
> optional UMD bundles withstanding

Can we use ng-packager to build library without UMD bundles? this will help a lot for electron angular library.

**Comment by alan-agius4** [comment]
@xiaoxiangmoe, ng-packagr strictly follows APF.

**Comment by clydin** [comment]
@xiaoxiangmoe can you provide some additional information regarding your concerns with APF in relation to electron?

**Comment by xiaoxiangmoe** [comment]
@clydin I filled out a more detailed issue explaining the problem, see https://github.com/angular/angular-cli/issues/16552
