### ISSUE TITLE
({}).toString.call(null) returns [object Window] for ES6 only builds

### ISSUE THREAD

**Issue by juliancarrivick** [angular/angular-cli#16557]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Unsure.

### Description
On a project with a `browserslist` that only ends up targeting ES6 browsers, the result of `({}).toString.call(null)` is `"[object Window]"`, not `"[object Null]"` as expected.

I came across this bug as our project only targets ES6 and we recently upgraded to Bootstrap 4.4 which uses this method for checking the type of parameters. In https://github.com/twbs/bootstrap/pull/29251 an new option was added which has a default value of `null`, which returns a type of `window` in their type checker which causes an error with this CLI configuration.

## 🔬 Minimal Reproduction
- `ng new toStringRepo`
- `ng serve`
- Open console of served app
- Execute `({}).toString.call(null)` and observe that it returns `"[object Null]"` 
- Stop serving
- Change content of `browserslist` to `last 2 Chrome versions`
- `ng serve`
- Open console of served app
- Execute `({}).toString.call(null)` and observe that it returns `"[object Window]"` 

## 🔥 Exception or Error
None

## 🌍 Your Environment
<pre><code>$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.21
Node: 10.15.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.21
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              8.3.21
@angular-devkit/schematics        8.3.21
@angular/cli                      8.3.21
@ngtools/webpack                  8.3.21
@schematics/angular               8.3.21
@schematics/update                0.803.21
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**
Upgrading the test project to Angular 9 with `ng update @angular/core @angular/cli --next` resolves the issue.

**Comment by alan-agius4** [comment]
This seems to be cause by `zone.js` version `0.9.x`,  Angular 9 uses `zone.js` `0.10.x` where the issue was solved.

Please update to `zone.js` version `0.10.2`.
