### ISSUE TITLE
ERROR: Error: Browserslist: caniuse-lite is outdated. Please run next command `npm update`

### ISSUE THREAD

**Issue by phani17c** [angular/angular-cli#16560]
# 🐞 Bug report

### Command (mark with an `x`)

ng build

- [ ] new
- [x ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
When I run build universal, I am getting this error 
"ERROR: Error: Browserslist: caniuse-lite is outdated. Please run next command `npm update`"

Here is the analysis I did, I think the issue is really coming with dependency @babel/preset-env": "7.7.6" which use "browserslist": "^4.6.0" which uses "caniuse-lite": "1.0.30000967". So it throws the above error. Currently my script logic is synchronous run commands. So it breaks with this message.

## 🔥 Exception or Error
<pre><code>

"ERROR: Error: Browserslist: caniuse-lite is outdated. Please run next command `npm update`"
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.20
Node: 10.14.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.20
@angular-devkit/build-angular              0.803.21
@angular-devkit/build-optimizer            0.803.21
@angular-devkit/build-webpack              0.803.21
@angular-devkit/core                       8.3.20
@angular-devkit/schematics                 8.3.20
@angular-devkit/schematics-cli             0.13.8
@angular/cdk                               8.2.3
@angular/cli                               8.3.20
@angular/material                          8.2.3
@ngtools/webpack                           8.3.21
@nguniversal/common                        8.2.6
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.20
@schematics/schematics                     0.13.8
@schematics/update                         0.803.20
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@phani17c which command is throwing this error? Typically this is just a “warning”.

**Comment by krokofant** [comment]
We encountered this today with ng test, no issue with building. We changed the caniuse-lite version in package-lock.json @angular-devkit/build-angular to 1.0.30001016 from 1.0.30000989.

The @angular-devkit/build-angular was on version 0.803.20 (0.803.21 is the latest).

**Comment by Shoe2** [comment]
NG build command is also complaining about this to me, should just require a package.json update right? Fast fix?  It is indeed just a warning, but it's somewhat surprising to my back end guys who dont know what it means.

**Comment by phani17c** [comment]
@alan-agius4 Will this be a new npm version after fix happen?

**Comment by phani17c** [comment]
And @alan-agius4  you are right, I have custom script to run some npm scripts combined

**Comment by weilinzung** [comment]
please the `autoprefixer` dependency to latest one.

**Comment by alan-agius4** [comment]
@phani17c, a new version will be released in the coming days.

**Comment by phani17c** [comment]
Thanks @alan-agius4  I am closing this issue.
