### ISSUE TITLE
Feature request: remove umd warning in ng-packager and allow `.mjs` format

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#16581]
### Description

if we use angular to build angular electron app library:

```
WARNING: No name was provided for external module 'electron' in output.globals – guessing 'electron'
WARNING: No name was provided for external module 'path' in output.globals – guessing 'path__default'
WARNING: No name was provided for external module 'fs' in output.globals – guessing 'fs__default'
WARNING: No name was provided for external module 'os' in output.globals – guessing 'os__default'
```

These warning are useless, because electron app does not use amd or browser globals, only commonjs and esmodule. 

At the same time, we also hope to have mjs support. Maybe in the future, we will execute the js code of es module in node. 
But apf only supports `.js` esm code and commonjs code supported in umd bundle, not `.mjs`

### Describe the solution you'd like

* remove umd bundle warning for output.globals (users will not use umd bundle if we use angular cli, users will not use umd bundle browser globals in commonjs)
* (optional) build lib with `.mjs` for future nodejs esm usage

**Comment by alan-agius4** [comment]
Hi @xiaoxiangmoe, as a library author you'd need to configure the modules IDs.
See: https://github.com/ng-packagr/ng-packagr/blob/master/docs/dependencies.md#resolving-umd-module-identifiers

There are multiple use cases where globals are required when building a library with the CLI, usage of a library build with Angular CLI is not restricted to only Angular CLI users.
