### ISSUE TITLE
Unable to build library with AngularCompilerPlugin, no declarations created in the output

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular-cli#16588]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
I haven't tried it before

### Description

 A clear and concise description of the problem...
Since this is still not working: https://github.com/angular/angular/issues/34027
I'm trying to build an Angular Library with our current Webpack setup.
When using AngularCompilerPlugin with Webpack declaration files are not generated.
So I'm unable to import the built library.
From webpack.config
```
new AngularCompilerPlugin({
    tsConfigPath: helpers.rootPath('tsconfig.build.json'),
    mainPath: helpers.rootPath('src/index.ts')
}),
```
From tsconfig.build.json
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "strictNullChecks": true,
    "noImplicitReturns": true,
    "rootDir": "./src",
    "declaration": true,
    "declarationMap": true,
    "declarationDir": "./dist",
    "outDir": "./dist"
  },
  "files": [
    "./src/index.ts"
  ]
}
```

From tsconfig.json
```
{
  "compilerOptions": {
    "rootDir": ".",
    "baseUrl": ".",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noEmitHelpers": true,
    "noEmitOnError": false,
    "importHelpers": true,
    "noImplicitAny": false,
    "strictNullChecks": false,
    "strictPropertyInitialization": false,
    "pretty": true,
    "sourceMap": true,
    "declaration": false,
    "preserveConstEnums": true,
    "downlevelIteration": true,
    "lib": [
        "dom",
        "es2015",
        "es2017.object",
        "es2017.string"
    ],
    "typeRoots": [
        "./typings/",
        "./node_modules/@types"
    ],
    "paths": {
      "@oas/web-lib-core": ["./packages/web-lib-core/dist"],
      "@oas/web-lib-common": ["./packages/web-lib-common/dist"],
      "@oas/web-lib-angular-js": ["./packages/web-lib-angular-js/dist"],
      "@oas/web-lib-angular": ["./packages/web-lib-angular/src"],
      "@oas/web-lib-angular-2": ["./packages/web-lib-angular-2/dist"],
      "@oas/internal-lib-e2e": ["./packages/internal-lib-e2e/dist"],
      "rxjs/*": ["./node_modules/rxjs/*"],
      "zone.js/*": ["./node_modules/zone.js/*"],
      "@angular/*": ["node_modules/@angular/*"]
    }
  },
  "compileOnSave": false,
  "buildOnSave": false
}
```

## 🔬 Minimal Reproduction

https://github.com/JonWallsten/monorepo-new (might contain sensitive data from our organisation, so please ask to be a collaborator)

Follow the instructions in the monorepo root ReadMe and check dist folder for packages/web-lib-angular-2

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-rc.7
Node: 12.14.0
OS: win32 x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7 (cli-only)
@angular-devkit/schematics        9.0.0-rc.7 (cli-only)
@angular/cdk                      9.0.0-rc.6
@angular/http                     8.0.0-beta.10
@angular/material                 9.0.0-rc.6
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7 (cli-only)
@schematics/update                0.900.0-rc.7 (cli-only)
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.4
</code></pre>

**Comment by JonWallsten** [comment]
Oh, you're supposed to use ng-packagr for creating Angular Libraries?

**Comment by alan-agius4** [comment]
`AngularCompilerPlugin` is meant to be used to bundle application which don’t need typescript deceleration files.

For libraries, you need to use ng-packagr or if you use the CLI you can you the `@angular-devkit/build-ng-packagr`.

To generate a new library within the cli use: 
`ng g lib <library-name>.

More info can be found: https://angular.io/guide/libraries
