### ISSUE TITLE
In app.module place the app.component import last 

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#16598]
In order to make it easier to cut and paste component imports in the router module, Instead of:

```
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { StepperComponent } from './stepper/stepper.component';

```

Do 

```
import { AppRoutingModule } from './app-routing.module';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { StepperComponent } from './stepper/stepper.component';
import { AppComponent } from './app.component';



```

**Comment by filipesilva** [comment]
I think that makes sense. I'd even move the non-local imports all the way to the top. 

Would you like to implement this change?

**Comment by zadokdaniel** [comment]
hey,
I would like to give it a go.
As a new contributor I would need some guidance if possible :)

> I think that makes sense. I'd even move the non-local imports all the way to the top.
> 
> Would you like to implement this change?

**Comment by filipesilva** [comment]
Heya @zadokdaniel, thanks for taking a look!

So this happens on a generator, and generators are relatively easy to test which makes it easier to work on. All generators are in https://github.com/angular/angular-cli/tree/master/packages/schematics, and have unit tests. The unit tests can be ran with `yarn test`.

The first thing is to figure out which generator does it and reproduce the problem. The issue report didn't actually include that. 

@fireflysemantics what was the command you used when you saw this happening? Can you also provide the result of `ng version` please?

**Comment by krishnaanaril** [comment]
@filipesilva Hello, What are trying to solve here? In the original issue only app.component is mentioned. Are we trying to move all non-local imports to top?

**Comment by filipesilva** [comment]
@krishnaanaril yes, that is the idea. The way we add these imports is by reading the source file AST and inserting new imports in the appropriate place. So the algorithm we use to do that would need to handle local/non-local better. 

I'm still not sure in what situations this occurs so it's also important to isolate the problematic insertions.

**Comment by memark** [comment]
Is anyone working on this?

**Comment by taylorhutchison** [comment]
I have not encountered this being an issue with other developers. Am I reading this right that this to to make copy/paste easier?

**Comment by fireflysemantics** [comment]
Hi - Sorry for the late reply - Just saw the other comments now.  

After having done a few more project I've started to always just delete the routing module and place the routes directly into the app module.

This is easier because the app module has to have all the components for declaration anyways, so it's just easier to define the routes there too.

I wonder if creating a separate routing module should be an option on the `new` command, so that users that want that get that, otherwise the routing will just be generated right into the `app.module`?

**Comment by vinay-9** [comment]
--------answer 
yes you can do it by using the command as -ng new <your-project-name> --routing 
->it will create a new project with a separate routing module 
I hope that this was your problem, if not then sorry i am just new to github community

**Comment by vinay-9** [comment]
> --------answer
> yes you can do it by using the command as -ng new --routing
> ->it will create a new project with a separate routing module
> I hope that this was your problem, if not then sorry i am just new to github community

it is ng new <project-name> --routing
i don't now how it got removed from my comment

**Comment by vinay-9** [comment]
> --------answer
> yes you can do it by using the command as -ng new --routing
> ->it will create a new project with a separate routing module
> I hope that this was your problem, if not then sorry i am just new to github community
it is ng new project_name --routing
i dont now how it got removed from my comment

**Comment by profanis** [comment]
As a new contributor, it seems to be a good point to start with. 

I gave it a try and the first thing was to figure out which schematic is responsible for the `app.module` file generation. I found out that it's the [application scematic](https://github.com/angular/angular-cli/tree/master/packages/schematics/angular/application), and generates the `app.module` based on this [template](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/application/other-files/app.module.ts.template).

If my findings are correct, then it seems that this issue has already been resolved.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
