### ISSUE TITLE
Router outlet broken

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#166]
The last two commits (https://github.com/angular/angular-cli/commit/e2c879580a1ffaee96a36f4dfdb0b8fdacec23bb and https://github.com/angular/angular-cli/commit/2efc9a150fe84a38d479ed062e6454f3e3a14970) seem to have broken the router. Somehow, `ngOnInit` events on child routes are not firing.

Undoing these commits causes them to fire again. I suspect [this](https://github.com/angular/angular-cli/blob/master/lib/broccoli/angular2-app.js#L59) might be the issue, in that dependencies are loaded out of order ( [previous order](https://github.com/angular/angular-cli/blob/019514681d990a54acfa6e1f46f7b6001a7674a8/addon/ng2/blueprints/ng2/files/src/index.html) ) and thus cause parts of angular to not have the required dependencies.

/cc @cironunes @jkuri

**Comment by jkuri** [comment]
Hi, do you maybe have any example ready to test with?

**Comment by jkuri** [comment]
Maybe just Rx should be loaded before angular2, can you check please?

**Comment by filipesilva** [comment]
I ran into this with routes generated via https://github.com/angular/angular-cli/pull/139. The `ngOnInit` on `hero-detail.component.ts` and `hero-list.component.ts` (assuming you use `ng generate route hero`) do not work with those two commits.

I am unsure of how to just load Rx before the rest with broccoli though, how do I do it?

**Comment by jkuri** [comment]
Just add [this](https://github.com/angular/angular-cli/blob/master/lib/broccoli/angular2-app.js#L68) line before `**/angular2.dev.js`. Then try to generate routes again.

**Comment by filipesilva** [comment]
That did not work. 

I used the [order on the quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#add-the-index-html-) and it works:

```
      inputFiles: [
        // '**/es6-shim.js',
        '**/system-polyfills.js',
        '**/angular2-polyfills.js',
        '**/system.src.js',
        '**/Rx.js',
        '**/angular2.dev.js',
        '**/http.dev.js',
        '**/router.dev.js',
        '**/upgrade.dev.js'
      ],
```

...except that the es6-shim errors. If I take it out it's fine. 

I can't see why it would error though, since its whole purpose is the be the very first think so it can shim missing functionality.

**Comment by jkuri** [comment]
Okay, then just add this fix to your PR. I will check about es6-shim errors
asap.

**Comment by filipesilva** [comment]
Tried adding the shim separately, outside `vendor.js` and it works fine.

I'd prefer not to change up that order from within my PR because it's not related to routes per se, but rather to dependency loading.

I'll gladly open up a new PR for it though, but might as well also fix the shim thing.

**Comment by jkuri** [comment]
Hi @filipesilva. Is this working now?

**Comment by filipesilva** [comment]
No, still has the problem with the shim being loaded via broccolli. I haven't had time to look into it more.

**Comment by jkuri** [comment]
Please try the following order, if it works for you;
````javascript
inputFiles: [
  '**/angular2-polyfills.js',
  '**/system.src.js',
  '**/system-polyfills.js',
  '**/es6-shim.js',
  '**/Rx.js',
  '**/angular2.dev.js',
  '**/http.dev.js',
  '**/router.dev.js',
  '**/upgrade.dev.js',
],
````
if its okay please provide PR with the fix, otherwise please tell me how to reproduce an error.

**Comment by cironunes** [comment]
any news?

**Comment by filipesilva** [comment]
@jkuri just tried the order you said, still does not work. 

We have to follow the order in the guides though: `es6-shim.js` needs to be the first one, `system-polyfills.js` before `system`, etc. Otherwise those files aren't doing anything.

To reproduce, do the following:

```
ng new testproj
cd testproj
npm link angular-cli
ng g route hero
// follow the instructions on readme, line 95 to add the route
ng serve
// open browser on http://localhost:4200/hero
```

This is what appears:

![image](https://cloud.githubusercontent.com/assets/4172079/12765393/593f0e52-c9f6-11e5-9f38-1b6532a07d53.png)

Now open `angular-cli/lib/broccoli/angular2-app.js` and change lines 59-69 to have the order indicated in the quickstart:

```
      inputFiles: [ //TODO: figure out how to make it a glob that maintains the order of the files
        '**/es6-shim.js',
        '**/system-polyfills.js',
        '**/angular2-polyfills.js',
        '**/system.src.js',
        '**/Rx.js',
        '**/angular2.dev.js',
        '**/http.dev.js',
        '**/router.dev.js',
        '**/upgrade.dev.js'
      ],
```

Stop and restart `ng serve`. Browser should have an error:

![image](https://cloud.githubusercontent.com/assets/4172079/12765541/04a0c7e0-c9f7-11e5-9376-4f6d113911fe.png)

Comment out the `es6-shim.js` line, stop and restart `ng serve`. Browser will show the correct result:

![image](https://cloud.githubusercontent.com/assets/4172079/12765583/360aea7c-c9f7-11e5-9aa1-71f820b05bdb.png)

**Comment by jkuri** [comment]
@filipesilva thanks for helping with reproduce, I got same errors. 
Solved it with this order; 

````javascript
'**/angular2-polyfills.js',
'**/es6-shim.js',
'**/system-polyfills.js',
'**/system.src.js',
'**/Rx.js',
'**/angular2.dev.js',
'**/http.dev.js',
'**/router.dev.js',
'**/upgrade.dev.js'
````
I think adding  `'**/angular2-polyfills.js'` before all others is the key. Please check.

**Comment by filipesilva** [comment]
@jkuri that order doesn't fix it for me... are you sure you didn't do something else? I tried using that order on a fresh copy of master. I've notice that if you restart `ng-serve` but don't refresh the browser, sometimes it works. I don't understand why.

I made a #170 where `es6-shim.js` is loaded separately from the rest of the libs, and it seems to fix this issue. But I don't see why loading it separately should change anything.

**Comment by jkuri** [comment]
Hm, guess I ran into that case you mention. I don't understand neither. Maybe some broccolli concat issue? Don't know.

**Comment by filipesilva** [comment]
I even thought it might be related to the ember-cli auto reload somehow and changed the order of that with no results. Really weird issue....

**Comment by jkuri** [comment]
I gave this issue one more shot, I found order which works properly with `ng g route hero` command (always). @filipesilva please check, I think this one is better than https://github.com/angular/angular-cli/pull/170 as it not includes es6-shim.js separately.

**Comment by filipesilva** [comment]
@jkuri I tested your PR and it works. I also agree it's better because of what you said.

There's still something fishy going on with broccolli and importing the `es6-shim` but I have no clue as to what it is right now.

**Comment by erdemildiz** [comment]
http://stackoverflow.com/questions/38998085/error-cannot-match-any-routes-in-angular-2-rc5-with-angular-cli/40330190#40330190

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20782714/60f05eaa-b7c9-11e6-9006-f7beb8bef322.png)
