### ISSUE TITLE
ng serve --crossOrigin

### ISSUE THREAD

**Issue by franko553** [angular/angular-cli#16602]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
`ng serve` creates script tags for main.js, etc. with the `type="module"` attribute.  This prevents browsers from sending cookies with requests for these files.  Certain environment require cookies to be sent with all requests.  In production environments, Angular CLI's `ng build` command offers an option `--crossOrigin use-credentials` which applies a `crossorigin="use-credentials"` attribute to the script tag, causing headers to be sent.  In a development environment, though, `ng serve` does not offer the same options, so Angular CLI projects cannot be previewed.

### Describe the solution you'd like
Please enable the same `--crossOrigin` functionality for `ng serve` as exists in `ng build`.

**Comment by alan-agius4** [comment]
Hi, if you configure `crossOrigin`, in the `build` section `options`, the `dev-server` target will inherit this option.

Ex:
```json
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "crossOrigin": "use-credentials",
            "outputPath": "dist/ponyracer",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
```

**Comment by filipesilva** [comment]
Closing as answered.
