### ISSUE TITLE
Shared folder isn't generated with component

### ISSUE THREAD

**Issue by leogout** [angular/angular-cli#1661]
1. Ubuntu 14.04

2. angular-cli: 1.0.0-beta.10
node: 5.4.0
os: linux x64

3. I started a project with `ng new myproject`, then `cd myproject` and finally `ng g component mycompo`.

4. No errors occured, this is the output :
```
installing component
  create src/app/mycompo/mycompo.component.css
  create src/app/mycompo/mycompo.component.html
  create src/app/mycompo/mycompo.component.spec.ts
  create src/app/mycompo/mycompo.component.ts
  create src/app/mycompo/index.ts
```

When i run tree :
```
>tree src/app/mycompo/
  src/app/mycompo/
  ├── index.ts
  ├── mycompo.component.css
  ├── mycompo.component.html
  ├── mycompo.component.spec.ts
  └── mycompo.component.ts

0 directories, 5 files
```

In my system-config.ts :
```js
  ...
  // App specific barrels.
  'app',
  'app/shared',
  'app/mycompo',
  /** @cli-barrel */
];
```
As you can see, no `app/mycompo/shared` folder is created, and no `app/mycompo/shared` is added to system-config.ts (`app/mycompo` is added).

Hope I don't miss something, but as I saw in #1418, my shared folder should be here.

**Comment by fhdk** [comment]
Try adding `--route` to your component generation

I am using beta.11-webpack.2 and with `ng generate component mycompo --route` the `app/mycompo/shared` is generated. If I leave the `--route` parameter out - no shared folder

**Comment by leogout** [comment]
Ok that solved it thanks ! But is this a normal behavior ?

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1658 removed barrels so this won't happen on the next release.

**Comment by gandra** [comment]
I have the same issue with 
```
angular-cli: 1.0.0-beta.25.5
node: 6.9.4
os: win32 x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3
```

I am just starting to learn angular2 and nagular-cli so I am not sure if this is intended behavior or bug?
