### ISSUE TITLE
`ng new` does not add up to date dependencies

### ISSUE THREAD

**Issue by jessorlisa** [angular/angular-cli#16611]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Running `ng update`directly after creating a new project lists an outdated version of rxjs. I would expect that a newly created project is already up to date

## 🔬 Minimal Reproduction

- Run `ng new myApp` (and accept defaults with Enter)
- `cd myApp`
- `ng update`

## 🔥 Error
<pre><code>
ng update
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      rxjs                               6.4.0 -> 6.5.4           ng update rxjs
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.22
Node: 10.18.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by alan-agius4** [comment]
Related to https://github.com/angular/angular-cli/issues/14603

**Comment by alan-agius4** [comment]
Hi, since this is partially related to https://github.com/angular/angular-cli/issues/14603, let's continue tracking this there.
