### ISSUE TITLE
node-sass build failure in 7.x

### ISSUE THREAD

**Issue by ocket8888** [angular/angular-cli#16638]
# 🐞 Bug report

### Command
- [x] update
- [x] install

### Is this a regression?
Yes, I believe this has been fixed before in 7.0 and even 7.1 as new versions of node-sass continually shatter as the packages hit the floor.

### Description
both @angular/core@7.2.16 and @angular/core@7.1.4 fail to build its node-sass dependency when I try to `ng update` from 7.1.4 - or just try to `npm install` that version. The problem seems to be the versioning compatibility with my node version (13.5.0) and/or node-gyp version (6.0.1). It seems to be trying to install node-sass version 4.11.0, which fails.

I've confirmed that I can manually build node-sass version 4.12.x, so recommend switching to at least that version.

## 🔬 Minimal Reproduction
1. Have node version 13.5.0 and node-gyp 6.0.1
1. `npm install --global @angular/cli@7`

## 🔥 Exception or Error
<details>
<summary><code>g++</code> command and errors/output</summary>
<pre>
g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node -I/home/MY_HOME_DIR/.node-gyp/13.5.0/src -I/home/MY_HOME_DIR/.node-gyp/13.5.0/deps/openssl/config -I/home/MY_HOME_DIR/.node-gyp/13.5.0/deps/openssl/openssl/include -I/home/MY_HOME_DIR/.node-gyp/13.5.0/deps/uv/include -I/home/MY_HOME_DIR/.node-gyp/13.5.0/deps/zlib -I/home/MY_HOME_DIR/.node-gyp/13.5.0/deps/v8/include -I../../../../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from ../../../../../nan/nan_converters.h:67,
                 from ../../../../../nan/nan.h:222,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
../../../../../nan/nan_converters_43_inl.h:18:49: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \
      |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                 |
      |                                                 v8::Local<v8::Context>
../../../../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
   22 | X(Boolean)
      | ^
In file included from /home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node.h:63,
                 from ../../../../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h:2762:37: note:   initializing argument 1 of ‘v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const’
 2762 |   Local<Boolean> ToBoolean(Isolate* isolate) const;
      |                            ~~~~~~~~~^~~~~~~
In file included from ../../../../../nan/nan_converters.h:67,
                 from ../../../../../nan/nan.h:222,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
../../../../../nan/nan_converters_43_inl.h:37:55: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
   37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                       |
      |                                                       v8::Local<v8::Context>
../../../../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
   40 | X(bool, Boolean)
      | ^
In file included from /home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node.h:63,
                 from ../../../../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h:2771:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
 2771 |   bool BooleanValue(Isolate* isolate) const;
      |                     ~~~~~~~~~^~~~~~~
In file included from ../../../../../nan/nan_new.h:189,
                 from ../../../../../nan/nan.h:223,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../../../../nan/nan_implementation_12_inl.h:356:37: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
  356 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                     ^
In file included from /home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node.h:63,
                 from ../../../../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h:5688:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
 5688 |   static Local<Value> New(Isolate* isolate, Local<String> value);
      |                       ^~~
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h:5688:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../../../../nan/nan_new.h:189,
                 from ../../../../../nan/nan.h:223,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_implementation_12_inl.h:356:58: error: expected primary-expression before ‘>’ token
  356 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                          ^
../../../../../nan/nan_implementation_12_inl.h:356:60: error: expected primary-expression before ‘)’ token
  356 |   return v8::StringObject::New(value).As<v8::StringObject>();
      |                                                            ^
In file included from ../src/binding.cpp:1:
../../../../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
../../../../../nan/nan.h:2232:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
 2232 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
      |                                                              ^
In file included from /usr/include/c++/9.2.0/cassert:44,
                 from /home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node_object_wrap.h:26,
                 from ../../../../../nan/nan.h:55,
                 from ../src/binding.cpp:1:
../../../../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
../../../../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
   24 |     assert(persistent().IsNearDeath());
      |                         ^~~~~~~~~~~
../../../../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
../../../../../nan/nan_object_wrap.h:127:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
  127 |     assert(wrap->handle_.IsNearDeath());
      |                          ^~~~~~~~~~~
../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cpp:284:98: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  284 |     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
      |                                                                                                  ^~~~~~~~~~~~
../src/binding.cpp: In function ‘Nan::NAN_METHOD_RETURN_TYPE render_file(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/binding.cpp:320:98: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
  320 |     int status = uv_queue_work(uv_default_loop(), &ctx_w->request, compile_it, (uv_after_work_cb)MakeCallback);
      |                                                                                                  ^~~~~~~~~~~~
In file included from ../../../../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
../src/binding.cpp: At global scope:
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node.h:611:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  611 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node.h:645:3: note: in expansion of macro ‘NODE_MODULE_X’
  645 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/binding.cpp:358:1: note: in expansion of macro ‘NODE_MODULE’
  358 | NODE_MODULE(binding, RegisterModule);
      | ^~~~~~~~~~~
In file included from /home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node.h:63,
                 from ../../../../../nan/nan.h:53,
                 from ../src/binding.cpp:1:
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/node_object_wrap.h:84:78:   required from here
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10400 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../../../../nan/nan_object_wrap.h:66:61:   required from here
/home/MY_HOME_DIR/.node-gyp/13.5.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [binding.target.mk:125: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/MY_HOME_DIR/path/to/my/project/node_modules/@angular-devkit/build-angular/node_modules/node-sass/build'
</pre>
</details>

## 🌍 Your Environment
<pre><code>
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.1.4
Node: 13.5.0
OS: linux x64
Angular: 7.2.16
... core

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.11.4
@angular-devkit/build-angular       0.13.6
@angular-devkit/build-optimizer     0.13.6
@angular-devkit/build-webpack       0.13.6
@angular-devkit/core                7.1.4
@angular-devkit/schematics          7.1.4
@angular/animations                 8.2.14
@angular/cli                        7.1.4
@angular/common                     8.2.14
@angular/compiler                   8.2.14
@angular/compiler-cli               8.2.14
@angular/forms                      8.2.14
@angular/http                       7.1.4
@angular/language-service           8.2.14
@angular/platform-browser           8.2.14
@angular/platform-browser-dynamic   8.2.14
@angular/platform-server            8.2.14
@angular/router                     8.2.14
@ngtools/webpack                    7.3.6
@schematics/angular                 7.1.4
@schematics/update                  0.11.4
rxjs                                6.5.4
typescript                          3.5.3
webpack                             4.29.0
</code></pre>

^ this was run after I failed to update from 7.1.4 to 7.2.16 ^

**Anything else relevant?**
OS is Manjaro - up-to-date
npm version 6.13.4

**Comment by clydin** [comment]
Angular 7.x is currently under long-term support (LTS) and only receives critical fixes (essentially security fixes).  It also does not officially support Node.js 13.  Please consider updating to 8.x.  Version 8.x also no longer uses node-sass by default and will avoid the native compilation issue.
For information regarding an update from 7.x to 8.x, please see: https://update.angular.io

**Comment by ocket8888** [comment]
I have the same issue with `ng update --to @angular/core@8`.

Where can I find information on which versions of angular support which versions of Node?
