### ISSUE TITLE
Ivy compiler cannot find deep imports from ES6 peer dependency of library

### ISSUE THREAD

**Issue by wulfsberg** [angular/angular-cli#16635]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Works under non-Ivy compiler

### Description

Some ES6 imports in a library causes a compile error when a project using the library is compiled with Ivy.

## 🔬 Minimal Reproduction
I have a project structure with an app (`my-app`) depending on an (private) npm-deployed Angular library (`map-ui-lib`), which in turn has a peer dependency to OpenLayers, which is a pure ES6 project with typings in DefinitelyTyped.

`map-ui-lib` uses deep imports like `import { WMTS } from 'ol/source';` from OpenLayers.

If `map-ui-lib` is compiled with `--prod` to disable Ivy, as recommended for libraries by https://next.angular.io/guide/ivy#maintaining-library-compatibility, attempting to use the library in `my-app` results in 

    ERROR in The target entry-point "map-ui-lib" has missing dependencies:
     - ol/source

If I disable Ivy in `my-app`, the application compiles and works.

Correspondingly, if I compile `map-ui-lib` with Ivy and deploy (as a file reference to a tarball, to circumvent the prohibition on publishing Ivy-based libraries), and compile `my-app` with Ivy, it works.

(Compiling `my-app` with Ivy disabled while attempting to use the Ivy-based library unsurprisingly yields a factory error).

In short: A library using deep ES6 imports compiled as non-Ivy fails when used in an Ivy project, and Ivy-based libraries are explicitly prohibited.

## 🔥 Exception or Error
<pre><code>ERROR in The target entry-point "map-ui-lib" has missing dependencies:
 - ol/source
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-rc.8
Node: 12.13.1
OS: win32 x64

Angular: 9.0.0-rc.8
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.8
@ngtools/webpack                  9.0.0-rc.8
@schematics/angular               9.0.0-rc.8
@schematics/update                0.900.0-rc.8
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
Will the ban on publishing Ivy libraries be lifted once v9 is released? If so, this behavior is not a problem for me, as I will simply embrace Ivy fully in the projects using this library, but if not, this will be a problem.
I am not sure if I can do some configuration to fix this, but the fact that it works under non-Ivy compilations makes it look more like a bug than a configuration error.

**Comment by petebacondarwin** [comment]
This is a known issue and should be fixed by https://github.com/angular/angular/pull/34695

**Comment by wulfsberg** [comment]
Oh, nice! I couldn't find an existing report, but I didn't think to look in open pull requests :-D

**Comment by petebacondarwin** [comment]
Thanks for the report though! Keep us on our toes :-)

**Comment by wulfsberg** [comment]
Crosslinking with https://github.com/angular/angular/issues/34720 for reference. It *was* in fact reported; I just didn't find it.
