### ISSUE TITLE
The Case for Globally Namespaced Class Names in Angular Post Optimization

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#16637]
Did a write up here:
https://medium.com/@ole.ersoy/the-case-for-globally-namespaced-class-names-in-angular-post-optimization-3461162e712f

It is related to this issue:
https://github.com/angular/angular-cli/issues/16553

**Comment by clydin** [comment]
Thank you for your interest in this issue.  However, as discussed in the referenced issue, class identifiers are not guaranteed to be globally unique regardless of any optimization transformations.
Even if this were not the case, a single application can span hundreds of output JavaScript files and the optimization pipeline is both multi-threaded and multi-process.  Implementing such behavior within the optimization pipeline would be highly non-trivial, add a large amount of complexity, and create the potential for both build-time performance and output file size regressions.
