### ISSUE TITLE
New NG Generate Option: Spec

### ISSUE THREAD

**Issue by chopswil15** [angular/angular-cli#16645]
# 🚀 Feature request
Create a new Generate Option called spec
i have a big  project where someone didn't create specs for unit testing and i don't want to do this manually

### Command (mark with an `x`)
- [X ] generate

### Description
this new generate option would 
1) loop through all files in a folder
2) for given file name of component, module, service, etc. it would check to see if a spec file exits
3) if not then auto generate one

### Describe the solution you'd like
in description

### Describe alternatives you've considered
manually doing this would "work" but that sucks

**Comment by chopswil15** [comment]
oh, and for newly generated spec files add a comment in file file like "TODO: empty spec file" so i can easily find all these empty shell spec files

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/7727
