### ISSUE TITLE
Jasmine html runner

### ISSUE THREAD

**Issue by hakonamatata** [angular/angular-cli#1664]
Hi

I just moved to Angular-Cli Webpack from the Broccoli. This works a lot better in terms of compressing files, creating a bundle and reduces my loading time. 

But I used to have jasmine-html-runner with a nice looking page for all my unit tests. Is there a way to set up this with webpack?

```
<!DOCTYPE html>
<html>

<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
	<title>Unit Tests</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<script src="https://google.github.io/traceur-compiler/bin/traceur.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/jasmine-html.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jasmine/2.4.1/boot.min.js"></script>
	<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</head>
<body>
	<script type="text/javascript">
		describe("A suite", function() {
			it("contains spec with an expectation", function() {
				expect(true).toBe(false);
			});
		});
	</script>
	<script type="text/javascript" src="./app/_pipes/nice-number.pipe.spec.ts"></script>
</body>
</html>
```

This is the basic setup, but how do I load all the spec files from the main.bundle.js?

-------------------------------------------
Windows 10
angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.7
os: win32 x64

**Comment by filipesilva** [comment]
I have no idea to be honest. Karma is now compiling the spec files via webpack, and it's all in memory so no disk output.

Going over http://karma-runner.github.io/1.0/config/configuration-file.html, I see there's a `customContextFile` property. Haven't tested it myself, but it looks like it's what you need.

Leaving the question open in case someone else can weight in.

**Comment by hakonamatata** [comment]
I have given up on this for now. Using mocha reporter gives a similar view in the command line and is significantly faster.

**Comment by filipesilva** [comment]
Alright, closing then.
