### ISSUE TITLE
Disable cache configuration

### ISSUE THREAD

**Issue by Toxicable** [angular/angular-cli#16649]
# 🚀 Feature request

### Command (mark with an `x`)
- [x] build

### Description
Under bazel build-angular is running in a read only fs, so it cant write undeclared files to disk, such as cache files.

### Describe the solution you'd like
A config option to allow for disabling this cache.
or
A config option to allow for pointing the cache to another dir (needs discussion)

### Describe alternatives you've considered
`NG_BUILD_CACHE` - but that also disables mangling.

**Comment by alan-agius4** [comment]
Closing as per offline convo.
