### ISSUE TITLE
No functioning CSS present on component in Angular Cli version 8.2.14

### ISSUE THREAD

**Issue by mariniello** [angular/angular-cli#16658]
I have a .css file in the component, but none of the styles on the web page work.

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent{
}

The component dont load any styles in the file **.css. This issues is intermittent, same moments when i restart the aplication it work, but mostly dont work.

I use Unbuntu 18.04 version

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Please file a new issue and ensure you provide all of the required information when filling out the issue template.
