### ISSUE TITLE
a weird error:  Cannot read property 'path' of null

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#16665]
I made a matcher function for a routing module, but I got a weird error:  Cannot read property 'path' of null, even if I check for the object existence.

```
export function contentMatcher(url) {
  //for simplifying, assume that all checks returned true
  return  {
        consumed: url,
        posParams: {
          type: new UrlSegment(url[0].path, {}),
          item: url[1] ? new UrlSegment(url[1].path, {}) : null //<------ Cannot read property 'path' of null
        }
      }   
}
```
```
const routes: Routes = [
  {  
    matcher: contentMatcher,
    component: ContentComponent
  }
]
```

I know that I must export the matcher function, because aot doesn't support function expression.
but I don't know if it is required also with posParams, and even so, how can I pass 'url' to it

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
