### ISSUE TITLE
ng update does not warn version mismatches or removed packages

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#16668]
# 🚀 Feature request

- [x] update

### Description
 A clear and concise description of the problem or missing capability...
When performing an update from `8.0.0.rc3` to `8.2.4` on the way to `9.0.0` I noticed a couple of opportunities to add warnings / messages to the update flow.  

After running `ng update`  I found my `http` package was still on `7.2.13`. Which I understand why since I only did an update command on Core and CLI, however this can cause some undesired side effect for users. It may be helpful 

Additionally when I went from `8.2.4` to `9.0.0-rc.8` I noticed `http` wasn't updated again. I ran the update command for `@angular/http --next` and it only went to `8.0.0.beta.10`. It would be helpful during the 8->9 update that http is either removed from `package.json` or there is a message to do so.

**Comment by clydin** [comment]
There actually is a migration that removes the `@angular/http` package.  However, it was added in `8.0.0-beta.14`.  Since the starting point of the project was `8.0.0-rc.3`, the migration was not executed as it was higher than the migration threshold.  One possible solution would be to normalize all prerelease migration thresholds to the final major version upon release.

**Comment by dgp1130** [comment]
We should check if upgrading from a prerelease and show a warning that some migrations might be missed with instructions to manually run those migrations. A proper fix is a little more complicated and will be included in greater `ng update` changes we are planning in the future.

NPM should already show `@angular/http` as deprecated, so I don't think we need an additional warning there.

**Comment by dgp1130** [comment]
Doesn't seem like there's any action to take until the full `ng update` redesign.
