### ISSUE TITLE
High severity vulnerabilities (thrown by npm)

### ISSUE THREAD

**Issue by nicorivat** [angular/angular-cli#16669]
Hi,

Npm is currently throwing me 2 high severity vulnerabilities (see screenshot). Is it possible to update the tree-kill library to 1.2.2. This version is a minor update containing the security fix.

![image](https://user-images.githubusercontent.com/15010744/72442881-9a8ca580-37ad-11ea-98f4-e18f7354f3d2.png)

current angular-cli version : 8.3.22

Thank you.

**Comment by clydin** [comment]
Duplicate of #16629
