### ISSUE TITLE
postcss-loader: Cannot resolve relative paths in url() compile-time

### ISSUE THREAD

**Issue by cyrilfr** [angular/angular-cli#16667]
## Bug description

The `url()` resolution doesn't work with relative paths at `build --prod`. It should be able to resolve the paths from the app source root at compile-time as it is correct at runtime (inline bundle).

## Minimal Reproduction

I the Angular project, I have a `src/variables.scss` file defining the assets:

```
$font-family-sans-serif: "Open Sans", sans-serif !default;
$font-family-cond:       "Open Sans Condensed", sans-serif !default;
$font-family-monospace:  monospace !default;

$primary: #CD2628;
$secondary: #727272;
$color-a: #CD2628; // red
$color-b: #727272; // dark gray
$color-c: #D0D0CE; // light gray
$color-d: white;   // ...
$color-e: #FF9900; // orange
$color-f: #00A627; // green
$color-g: #FAE9E9; // light red
$color-h: #286090; // blue

$translucent-a: rgba(0, 0, 0, 0.05); // black light
$translucent-b: rgba(0, 0, 0, 0.25); // black medium
$translucent-c: rgba(0, 0, 0, 0.85); // black dark
$translucent-d: rgba(78, 78, 78, 0.1); // gray
$translucent-e: rgba(255, 255, 255, 0.95); // white

$body-background-color: white;
$body-background-image: url('assets/images/bg-hexa-red-flat.png');
$body-background-position: top left;
$body-background-repeat: repeat;
```
then in my `src/app/components/sidepanel/sidepanel.component.scss` file it is imported:

    @import 'variables.scss';

    .sidepanel {
      background-color: $body-background-color;
      background-image: $body-background-image;
      background-position: $body-background-position;
      background-repeat: $body-background-repeat;
      font-family: $font-family-sans-serif;
    }

the import works because I set the `stylePreprocessorOptions` option in my `angular.json` file:

```
"architect": {
   "build": {
     "builder": "@angular-devkit/build-angular:browser",
       "options": {
         "outputPath": "dist",
         "index": "src/index.html",
         "main": "src/main.ts",
         "polyfills": "src/polyfills.ts",
         "tsConfig": "src/tsconfig.app.json",
         "aot": false,
         "assets": [
           "src/assets"
         ],
         "styles": [
           "src/styles.scss"
         ],
         "stylePreprocessorOptions": {
           "includePaths": [
              "src"
           ]
         }
       }
       ...
```

## Expected Behavior

Pass the compile-time check of `url('assets/images/bg-hexa-red-flat.png');` relative to the app source root.

## Screenshots

![screen](https://i.ibb.co/GphfK0q/Screenshot-from-2020-01-15-10-06-40.png)

## Environment

Libs
- @angular/core: ~8.2.14
- @angular-devkit/build-angular: ^0.803.22

For Tooling issues:
- @angular/cli: ^8.3.22
- Platform:  Linux

## Additional Context

The project is based on [angular-electron](https://github.com/maximegris/angular-electron) starter.

**Comment by alan-agius4** [comment]
Hi, this is expected. Kindly see the following issue https://github.com/angular/angular-cli/issues/12797 for more details and workarounds.

**Comment by cyrilfr** [comment]
None of the workarounds are options for production. Using an absolute path cannot be resolved in a filesystem protocol for instance.

**Comment by cyrilfr** [comment]
I found a [real workaroud](https://github.com/maximegris/angular-electron/issues/432#issuecomment-574672653) to be able to set the asset path.
