### ISSUE TITLE
node-sass Denial of service

### ISSUE THREAD

**Issue by whereskeem** [angular/angular-cli#16664]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
Using "@angular-devkit/build-angular": "^0.12.4" as  dev dependency in our Ionic Angular application ("ionic-angular": "3.9.2") I get this warning during npm audit

`Low             Denial of Service

  Package         node-sass

  Patched in      No patch available

  Dependency of   @angular-devkit/build-angular [dev]

  Path            @angular-devkit/build-angular > node-sass

  More info       https://nodesecurity.io/advisories/961`

We run "npm audit" as part of our build process so the project won't complete the build unless this vulnerability is resolved. Any suggestions on a work around? Can node-sass be replaced as a dependency of @angular-devkit/build-angular? Any suggestions are greatly appreciated.

Here's a list of the dependencies from our package.json

`"dependencies": {
        "@angular/common": "5.1.0",
        "@angular/compiler": "5.1.0",
        "@angular/compiler-cli": "5.1.0",
        "@angular/core": "5.1.0",
        "@angular/forms": "5.1.0",
        "@angular/platform-browser": "5.1.0",
        "@angular/platform-browser-dynamic": "5.1.0",
        "@ionic/storage": "2.1.3",
        "@ngx-translate/core": "^9.1.1",
        "@ngx-translate/http-loader": "^2.0.1",
        "chart.js": "^2.7.2",
        "html2canvas": "^1.0.0-alpha.12",
        "ion2-calendar": "^2.1.7",
        "ionic-angular": "3.9.2",
        "ionicons": "3.0.0",
        "libphonenumber-js": "^1.2.18",
        "moment": "^2.22.2",
        "ng2-charts": "^1.6.0",
        "ng2-dragula": "^1.5.0",
        "ng2-pdf-viewer": "^5.1.1",
        "ngx-device-detector": "^1.2.2",
        "rxjs": "5.5.2",
        "webpack": "^4.41.5",
        "xlsx": "^0.14.0",
        "zone.js": "0.8.20"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.12.4",
        "@angular/cli": "^7.0.6",
        "@angular/router": "5.1.0",
        "@ionic/app-scripts": "3.1.8",
        "@types/jasmine": "2.8.4",
        "@types/node": "^10.12.7",
        "ionic-mocks": "^1.3.0",
        "jasmine-core": "2.8.0",
        "jasmine-spec-reporter": "2.3.0",
        "karma": "^3.1.1",
        "karma-chrome-launcher": "^2.2.0",
        "karma-cli": "^1.0.1",
        "karma-coverage-istanbul-reporter": "^2.0.4",
        "karma-jasmine": "1.1.1",
        "karma-jasmine-html-reporter": "0.2.2",
        "karma-junit-reporter": "^1.2.0",
        "puppeteer": "^1.15.0",
        "typescript": "2.4.2"
    }`

**Comment by alan-agius4** [comment]
Hi, thanks for the issue, but node-sass is no longer a dependency of `@angular-devour/build-angular`.

Kindly update to the latest version.
