### ISSUE TITLE
css minification eating single quotes in production - breaking grid

### ISSUE THREAD

**Issue by nppasousa** [angular/angular-cli#16674]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
The CSS minifier used in --prod building eats the apostrophes rendering broken css.

## 🔬 Minimal Reproduction

Minimal reproduction
`ng new something` - pick css

app.component.css
<pre><code>.my-grid {
    grid: 'test' 'test2';
}
.my-grid2 {
    grid: 'test'
          'test2';
}
.my-grid3 {
    grid: 'test' 1fr
          'test2' 1fr / 1fr;
}
@media screen and (max-width: 500px){
    .my-grid {
        grid: 'test test2' / 1fr 2fr;
  
  }
}`
</code></pre>
Using 
<pre><code>ng build --prod</pre></code>

## 🔥 Exception or Error
The above app.component.css gets rendered in the main*.js to:
<pre>
`[".my-grid[_ngcontent-%COMP%], .my-g
    rid2[_ngcontent-%COMP%]{grid:test test2}.my-grid3[_ngcontent-%COMP%]{grid:test 1fr test2 
    1fr / 1fr}@media screen and (max-width:500px){.my-grid[_ngcontent-%COMP%]{grid:'test tes
    t2' / 1fr 2fr}}"]`
</pre>

Notice that some of the apostrophes get removed and some don't.
The grid statements without the quotes (apostrophes) are not rendered by the browser, yelding layouts that work fine in development but not in production.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.22
Node: 12.13.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
    

</code></pre>

**Anything else relevant?**

This is clearly a bug with clean-css package. But as it took me a long time to debug my code until I was sure it was angular compilation, and then using  /* clean-css ignore:start*/ ... /* clean-css ignore:end*/ to make sure it was clean-css and because I couldn't fight nothing on this on google or stackoverflow I thought it might post this to help if others are suffering from this problem.

The /* clean-css ignore:start*/ ... /* clean-css ignore:end*/  work as a temp fix if you install clean-css ^=4.2

**Comment by alan-agius4** [comment]
Hi @nppasousa, thanks for the issue. This should be solved in the next RC (rc.9) of version 9 as we replaced the `clean-css` with `css nano` which doesn't seem to be effected by this bug.
