### ISSUE TITLE
Ability to overwrite files while copying through assets array / Copying files in order

### ISSUE THREAD

**Issue by FabianGosebrink** [angular/angular-cli#16670]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
In an Angular CLI workspace with multiple apps you may also want to share multiple assets like images, favicons, etc across the multiple apps existing in the workspace. In the `assets` array of the `angular.json` the path to the shared files and folders can be given and the files are being copied in the concrete build of the separate apps. 

If one app now wants to have it's own file - e.g. an own different favicon or logo - the path to the `app/assets` can be provided in the `assets` array of the `angular.json` as well _after_ the shared files path. Unfortunately the order of the paths is not respected and the concrete apps asset files are not overwriting the shared assets during the build/copying pahse, although they have the same name.

```
"assets": [
	{
		"glob": "**/*.*",
		"input": "libs/shared/assets",
		"output": "/"
	}, 
	{
		"glob": "**/*.*",
		"input": "app/assets",
		"output": "/"
	},
],
```

### Describe the solution you'd like
It would be nice if the order of the array would be respected and files would get overwritten if the filename and the output folder are the same.

### Describe alternatives you've considered
The only workaround I have seen so far is to point at the files explicitly. This worked in my tests:

```
"assets": [
	{
		"glob": "**/*.*", // <-- contains a logo.png
		"input": "libs/shared/assets",
		"output": "/"
	}, 
	{
		"glob": "logo.png",
		"input": "app/assets",
		"output": "/logo.png"
	},
],
```

But doing this for multiple files results in an unhandy and very difficult `angular.json` assets array.

**Comment by FabianGosebrink** [comment]
Found out that this is _not_ related to the angular cli but may be an nx workspace issue. https://github.com/nrwl/nx/issues/2327

**Comment by alan-agius4** [comment]
Closing based on the above, it’s not actionable by us.
