### ISSUE TITLE
[RFC][PostCSS] Ability to configure PostCSS using config

### ISSUE THREAD

**Issue by vitaliy-bobrov** [angular/angular-cli#16681]
# 🚀 Feature request - Ability to configure PostCSS using config

### Command (mark with an `x`)

- [x] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc

### Description
There a bunch of requests regarding ability to configure PostCSS plugins:
#15766
#8427 
#10076

My proposal more practical and I could prepare PRs for it.

CLI uses PostCSS via `postcss-loader` it has a configuration [here](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts), however plugins list is encapsulated in a function and then applied to multiple loaders (global styles, component styles with/without preprocessors). [`postcss-loader`](https://github.com/postcss/postcss-loader) has a `config` parameter that allows to specify the path to look for PostCSS configuration files (internally it uses [`postcss-load-config`](https://github.com/michael-ciniawsky/postcss-load-config)) and optional context objects to pass to js config files. If CLI will use config configuration for `postcss-loader` it will give the ability to extend/replace plugins, parser, etc. even more it will allow overriding config for specific project/ library/ any folder.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
File: `packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/styles.ts`

PostCSS loader could look like this

```ts
{
  loader: require.resolve('postcss-loader'),
  options: {
      ident: buildOptions.extractCss ? 'extracted' : 'embedded',
      // Config that replaces plugins param
     config: {
         path: root, // root folder path provided by BuilderContext
         ctx: {
           angularCliPlugins: // Here we could pass CLI specific plugins condigs or plugins itself
         }
     },
      sourceMap:
          cssSourceMap && !buildOptions.extractCss && !buildOptions.sourceMap.hidden
              ? 'inline'
               : cssSourceMap,
    },
 },
```

In the root we will have a `postcss.config,js` (it couls be `.postcssrc.js` as well) file:

```js
module.exports = (ctx) => ({
  parser: ctx.parser ? 'sugarss' : false,
  plugins: {
    'postcss-import': ctx.angularCliPlugins.postcssImportOptions,
    'custom-angular-cli-plugin': ctx.angularCliPlugins.otherOptions,
    'autoprefixer': true, // users could opt-out, ex. if postcss-preset-env used
    'postcss-plugin': ctx.options.plugin
  }
})
```

Users will get full control of PostCSS with that configuration, could make it dynamic with `ctx`, etc.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Another option is to pass configuration from `angular.json`, but IMO not the best idea as it will make it more complex + CLI exposes configs for `browserslist`, `tslint`, etc. with defaults but users can customize them.

[`ngx-build-plus`](https://github.com/manfredsteyer/ngx-build-plus) could replace part of webpack config, but you might need to hook up into few places (global styles, preprocessor styles loaders and rely on that exact structure of `webpack` config) and you have no control over plugins provided by CLI since they are created with a function call.

[`angular-builders/custom-webpack`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack) has pretty same limitations and open issues related to PostCSS, [see](https://github.com/just-jeb/angular-builders/issues/634)

**Comment by ahnpnl** [comment]
This will be similar to how Babel config is used too.

**Comment by filipesilva** [comment]
Heya, we appreciate that you're interested in working on this feature, but we've been discussing whether to have it with first party support and decided against it for the reasons listed in https://github.com/angular/angular-cli/issues/8427#issuecomment-576234801.
