### ISSUE TITLE
`ng e2e --debug`

### ISSUE THREAD

**Issue by dgp1130** [angular/angular-cli#16683]
# 🚀 Feature request

### Command (mark with an `x`)
- [X] e2e

### Description
I've been looking for means to debug faulty e2e Protractor tests, however I don't see a means of accomplishing this in the Angular CLI, or a documented solution.

### Describe the solution you'd like

Ideally, I'd like to see some kind of `ng e2e --debug` or `ng e2e --inspect` which builds/runs the application, starts Protractor, and opens up a debugging port. If there is a way to break after test files are loaded, so I can set breakpoints without manually adding a `debugger;` statement, that would be great too.

### Describe alternatives you've considered

Most of the material I've found online tells me to call Protractor directly, via something like `node --inspect node_modules/.bin/protractor e2e/protractor.conf.js`. This has a couple problems to me:

1. This is a leaky abstraction.
    * We can do every other execution necessary via the CLI, but not debug e2e tests. As a tangential example, take a look at this [`package.json` scripts configuration](https://github.com/dgp1130/chatter/blob/ng/services/ng-frontend/package.json#L4) I have, all of which just uses `ng` directly, **except** for debugging e2e tests.
    * We do seem to leak Protractor in a few other places (such as the configuration file).
    * Subtle implementation changes in `ng e2e` could cause the debug command to need to be changed. For instance, should I update `webdriver-manager` before running?
1. I don't see any official documentation or stance on how to debug e2e tests; everything I've found is community built.
1. Running Protractor directly also does not boot up the actual application, so a separate `ng serve` command is necessary.
    * I didn't realize this and lost a lot of time debugging, confused why it worked previously and suddenly stopped today. Turns out I had the server running the background last time and didn't realize that was a dependency!

**Comment by filipesilva** [comment]
We do have the `--element-explorer` flag that passes on that flag for usage as described in https://github.com/angular/protractor/blob/master/docs/debugging.md. 

But I just saw this note there:
> Note: Protractor debugger and element explorer cannot be used for Node.js 8+

And since we don't even support node 8 anymore it doesn't sound right to propose using it.

**Comment by dgp1130** [comment]
I was just doing a little more digging and found that Protractor does [explicitly tell users to use `node --inspect` to debug](http://www.protractortest.org/#/debugging). I either didn't find this earlier, didn't realize it was an official source, or was looking for a greater Angular solution rather than a Protractor solution.

Considering that's the official answer to the question of "how to debug Protractor tests", I think we would need to build on top of that somehow. The simplest solution might be to just add the `--inspect` flag to the Node process running Protractor. We'd also want to document this as the officially supported means of debugging Protractor tests in Angular apps.

In our discussion today, someone mentioned that scripting Protractor is difficult because it kills the spawned process in an awkward fashion. We can probably file specific bugs about that any other pieces which make it difficult for us to work with. Are there other issues which make this difficult to work with?

**Comment by filipesilva** [comment]
The issue for user protractor as a lib is https://github.com/angular/protractor/issues/4160, and I've left a comment there about the `process.exit` bits.

If the intended debugging approach is to use node's `--inspect`, then it is better to launch Protractor as a separate process. This way `--inspect` applies only to protractor and not to the calling code.

**Comment by dgp1130** [comment]
Agreed that a separate process makes more sense. We wouldn't want to use it as a library if we're going to be adding Node options. Sounds like it's a matter of making the launcher a public API and generally making things more testable by calling back to us instead of killing itself.

We could probably still do unit tests by mocking Protractor, but we wouldn't be able to write effective e2e tests of our e2e functionality.

**Comment by miohtama** [comment]
Here some feedback for those who currently need workarounds for this

To debug tests

- Turn on the debugger auto attach in Visual Studio Code through the command palette, or your favorite IDE/debugger
- Start `ng serve` in one terminal to have Angular frontend running 
- In another terminal, run `node --inspect-brk node_modules/.bin/protractor e2e/protractor.conf.js`
  and now Visual Studio Code will stop in breakpoints set in the E2E test files
- You can use Web Console Inspector in Protractor's Chrome instance to figure out state of the forms and buttons for the e2e tests

What does not work

- `node --inspect-brk node_modules/.bin/ng`: For some reason `--inspect-brk` get ignored if `ng e2e` is run directly
- Running Protractor without starting a frontend manually: `ng e2e` is responsible for doing Angular setup

**Comment by alan-agius4** [comment]
Closing as this is not in the Angular CLI roadmap, since Protractor is being deprecated https://github.com/angular/protractor/issues/5502
