### ISSUE TITLE
trying to generate directive throws unknown blueprint

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#167]
Installed angular-cli today and it is throwing issues 

```bash
ng g directive my-new-directive
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Unknown blueprint: directive
```

I currently have the following version installed globally:

```bash
├─┬ angular-cli@0.0.20
```

**Comment by filipesilva** [comment]
You're absolutely right. Just tested it myself and this isn't happening on the current dev setup but is happening in the latest npm version.

Will look into it and try to get a fix soon!

**Comment by filipesilva** [comment]
@IgorMinar this should be fixed after a new version is up.

**Comment by cironunes** [comment]
Closing as it's fixed on current master

**Comment by zackarychapple** [comment]
So this is closed but a new tag was not cut so the only way to get the working version is to build it myself?  Can someone cut a tag please.

**Comment by filipesilva** [comment]
A tag should be done soon, but meanwhile you can also install the latest master directly from the repo via `npm install https://github.com/angular/angular-cli.git`.
