### ISSUE TITLE
Angular-cli not reflecting the changes made in the code

### ISSUE THREAD

**Issue by hamzahamidi** [angular/angular-cli#16707]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Previously whenever I made a change in the code ( in html for example) I had the changes reflected in the browser immediately.

### Description
create a new project: $ ng new app
start the application $ npm start
make a change in a component
the changes doesn't reflect in browser. **You need to restart the application to reflect the changes.**

## 🔬 Minimal Reproduction
create a new project: $ ng new app
start the application $ npm start
make a change in a component
the changes doesn't reflect in browser. **You need to restart the application to reflect the changes.**
here's my package.json:
```
{
  "name": "demo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod --base-href ./",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.22",
    "@angular/cli": "~8.3.22",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.37.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.22
Node: 12.14.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

I disabled the cache in the browser but it didn't help. I suspect it's an issue with webpack --watch

**Comment by clydin** [comment]
Can you provide the console output of the CLI including the time period when the changes were being made?

This was also not reproducible given only the instructions shown above.  The issue may be related to the operating system's file watching capabilities.  Some systems will require the use of polling to probably watch the file system.  This is nearly always necessary when the file watching takes place instead a container (docker, for instance).

**Comment by hamzahamidi** [comment]
It's an OS issue. I had to increase the max capacity to watch changes to the filesystem.
The limit can be increased to its maximum by editing `/etc/sysctl.conf` and adding this line to the end of the file:
```
fs.inotify.max_user_watches=524288
```
The new value can then be loaded in by running `sudo sysctl -p`
