### ISSUE TITLE
Regression problem in tsconfig.json outDir that cause VSCode showing errors in all import from libs pointed with paths under /dist/...

### ISSUE THREAD

**Issue by dmorosinotto** [angular/angular-cli#16708]
# 🐞 Bug report

### Command

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.3.23

### Description

The root tsconfig.json used in the new v9.0.0-rc* template point `"outDir": "./dist"`
That caused annoying problem in VSCode when you rebuild libs referred by `"paths"` 
all the code  `imports {...} from lib` is marked as Errors by TS because they are build under `/dist/...`

## 🔬 Minimal Reproduction
Run those commands:
```
npx @angular/cli@next new --createApplication=false my-workspace

cd my-workspace
npm run ng -- generate library my-lib
npm run ng -- generate application my-app
```
The above commands are needed to setup the workspace for the repro with an application and a library pointed in the tsconfig.json ```"paths": { "my-lib": ["dist/my-lib"] }```

then add this line to app.module.ts to use the library inside the application:
```
// app.module.ts
import { MyLibModule } from 'my-lib';
```

and then run the compilation of the my-lib project in watch mode:
```
npm run ng -- build project=my-lib --watch
```

You will see in VSCode that all imports pointing to the my-lib will be signal as TS Errors 2307

## 🔥 Exception or Error
<pre><code>
Can't find module 'my-lib' ts(2307)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.9
Node: 12.14.1
OS: darwin x64

Angular: 9.0.0-rc.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.9
@angular-devkit/build-angular      0.900.0-rc.9
@angular-devkit/build-ng-packagr   0.900.0-rc.9
@angular-devkit/build-optimizer    0.900.0-rc.9
@angular-devkit/build-webpack      0.900.0-rc.9
@angular-devkit/core               9.0.0-rc.9
@angular-devkit/schematics         9.0.0-rc.9
@ngtools/webpack                   9.0.0-rc.9
@schematics/angular                9.0.0-rc.9
@schematics/update                 0.900.0-rc.9
ng-packagr                         9.0.0-rc.7
rxjs                               6.5.4
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
I tested this issue using VSCode and it is related to **latest CLI v9.0.0-rc**, but the same behaviour is CORRETLY WORKING without any issue in the previous CLI v8 (tested and works on ~8.2.23)

**Comment by damianog** [comment]
Hi, here the video that I realized with @dmorosinotto  to demonstrate de issues

![outDir](https://user-images.githubusercontent.com/2786682/72684602-4aca1900-3ae2-11ea-80c5-b865e0f07eeb.gif)
