### ISSUE TITLE
Add dynamic list as additional input type for x-promt (schematic)

### ISSUE THREAD

**Issue by ntziolis** [angular/angular-cli#16705]
# 🚀 Feature request

### Command (mark with an `x`)
- [x] generate

This feature request is actually about extending the functionality of schematics themselves. `ng generate` is just involved as the requested feature would be accessed through the command.

### Description
Today schematic promts are limited to a fixed set of compile time response values. To allow more advanced scaffolding use cases we also need the ability to dynamically (runtime) generated valid response values.

### Describe the solution you'd like
- Add new promt input type `dynamic-list` or similar
- Provide standardized way of filling the dynamic lists from within schematic code

### Describe alternatives you've considered
Open to any suggestions.

**Comment by Harpush** [comment]
This can be very powerful! Prompt questions based on the code structure can be great

**Comment by ntziolis** [comment]
@Harpush  that’s exactly the us case I had in mind. Both code structure as well as typescript „reflection“ etc.

**Comment by yonathanaaman** [comment]
Any news concerning this?

**Comment by Harpush** [comment]
Any news concerning this?

**Comment by PKSpeleo** [comment]
Yeah, it is exactly what I am looking for right now=)

**Comment by dgp1130** [comment]
This seems like a specific use case which would benefit from more dynamic schematics option support.
