### ISSUE TITLE
bash: ng: command not found

### ISSUE THREAD

**Issue by SabeloSH** [angular/angular-cli#16710]
Hi guys,

I keep getting this error no matter what I do I have tried running 
npm uninstall -g @angular/cli
npm clean cache
npm install -g @angular/cli

as well as npm link @angular/cli yet nothing is helping, please assist.

![Issue101](https://user-images.githubusercontent.com/45584767/72708312-1e0e1400-3b6b-11ea-82a4-e29eb49415df.PNG)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
