### ISSUE TITLE
Inconsistent use of exported bundles for an ES5 build vs an ES2015 build with differential loading

### ISSUE THREAD

**Issue by CarstenLeue** [angular/angular-cli#16712]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

unsure

### Description

The angular build features differential loading (awesome!), i.e. the build optionally generates two copies of the app, one for es2015 and one for es5.

The es5 code however seems to be the es2015 version of the full application build transpiled to es5.

I think that this is incorrect, the build should pick up the dedicated es5 exports from libraries it uses. In its current form it assumes that the es5 exports of all libraries are transpiled versions of their es2015 exports. 

This is not necessarily true. A library could decide to use hand-optimized version for es5 and es2015.

If I configure the Angular application build to use es5 as a target, then the build process would use the es5 exports of the libraries.

The Angular package format documentation clearly documents different es5 and es2015 entry points into libraries. I would expect them to be used consistently.

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-rc.9
Node: 10.17.0
OS: win32 x64

Angular: 9.0.0-rc.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.9
@angular-devkit/build-angular     0.900.0-rc.9
@angular-devkit/build-optimizer   0.900.0-rc.9
@angular-devkit/build-webpack     0.900.0-rc.9
@angular-devkit/core              9.0.0-rc.9
@angular-devkit/schematics        9.0.0-rc.9
@ngtools/webpack                  9.0.0-rc.9
@schematics/angular               9.0.0-rc.9
@schematics/update                0.900.0-rc.9
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @CarstenLeue, this is by design in the second iteration of differential loading as now we downlevel the ES2015 bundles to ES5 which improves the build times drastically.

The ES5 versions of the APF are currently in deprecation phase and will be removed in the near future, ES5 version is will be used as a fallbacking entrypoint if the ES2015 entrypoint doesn't exist.

See: https://next.angular.io/guide/deprecations#esm5-and-fesm5-code-formats-in-angular-npm-packages

**Comment by CarstenLeue** [comment]
@alan-agius4 thanks for the pointer. 

One of the main reasons for me to create a ES5 version of the app is support for the Google Crawler. Last time I checked the crawler would not crawl code that contains any extensions to  the ES5 language.

When cross compiling from ES2015 to ES5, can you really make sure to generate code that is a valid source for the Google Crawler? 

**Example:**
Last I checked the JS engine of the Google crawler would not understand `map` or `reduce` on an array. The babel transpilation process also does not rewrite such calls.
The solution so far was to generate an explicit ES5 bundle that uses helper functions and an ES2015 bundle for a more efficient (and smaller) browser version.

**Comment by alan-agius4** [comment]
Google crawler is a ever green. See: https://webmasters.googleblog.com/2019/05/the-new-evergreen-googlebot.html

With regards to the reduce and map. These methods among other gets polyfilled for older browsers.

**Comment by CarstenLeue** [comment]
Thanks so much for that pointer
