### ISSUE TITLE
ng add @angular/pwa doesn't enable pwa.

### ISSUE THREAD

**Issue by calidion** [angular/angular-cli#16713]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Don't know.

### Description

 

pwa not enabled and no `ngsw-worker.js` found according to this article:

https://multi-programming.com/blog/creating-progressive-web-apps-using-angular

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@angular/pwa                      0.803.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by calidion** [comment]
I can verify this is a bug.
I created a new angular project and executed `ng add @angular/pwa`.
then tested with `lighthouse`, I got passed with pwa enabled.
But the same process failed for my more sophisticated angular project.

**Comment by calidion** [comment]
This bug seems caused by upgrading from angular 7 to 8.

**Comment by alan-agius4** [comment]
@calidion, if the problem persist please open a new issue with a minimal reproduction.

Thanks
