### ISSUE TITLE
command not working

### ISSUE THREAD

**Issue by calidion** [angular/angular-cli#16714]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

don't know

### Description

according to doc :

https://angular.io/guide/app-shell#step-2-create-the-app-shell

this command should work:

```
ng generate app-shell --client-project my-app --universal-project server-app
```

but i got the error message:

```
A client project type of "application" is required.

```

## 🔬 Minimal Reproduction

```
ng generate app-shell --client-project my-app --universal-project server-app
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

@angular-devkit/architect         0.803.22
@angular-devkit/build-angular     0.803.22
@angular-devkit/build-optimizer   0.803.22
@angular-devkit/build-webpack     0.803.22
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      8.3.22
@angular/pwa                      0.803.22
@ngtools/webpack                  8.3.22
@schematics/angular               8.3.22
@schematics/update                0.803.22
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@calidion, is your application project named `my-app`? that value should be replaced with the name of the application project name that you wish to add the app-shell too.
