### ISSUE TITLE
[ng] Module not found: Error: Can't resolve 'core-js/proposals/reflect-metadata' since last update

### ISSUE THREAD

**Issue by daganM** [angular/angular-cli#16725]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Maybe. In the previous version, I did not had the problem. Actually, I used npm audit fix because of the security issue in tree-kill. So I went from 8.3.21 to 8.3.23.

### Description

Following my npm audit fix, I cannot run ionic serve anymore. I have this issue :
` ERROR in ./node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/jit-polyfills.js
[ng] Module not found: Error: Can't resolve 'core-js/proposals/reflect-metadata' in 'project\node_modules\@angular-devkit\build-angular\src\angular-cli-files\models'`

## 🌍 Your Environment
I'm using Angular with Ionic 5.4.9, npm 6.1.10 and node 12.14.0.

**Comment by clydin** [comment]
`core-js` is a direct dependency of the `@angular-devkit\build-angular`.
Can you provide the output of `npm ls core-js`?
The following is the output of the above command on a newly created 8.3.23 project:
```
├─┬ @angular-devkit/build-angular@0.803.23
│ └── core-js@3.2.1
└─┬ karma@4.1.0
  └── core-js@2.6.11
```

The `npm audit fix` execution may have unintentionally broken the node modules directory layout.

**Comment by daganM** [comment]
Here's what I get

+-- @angular-devkit/build-angular@0.803.21
| +-- core-js@3.2.1
| -- istanbul-instrumenter-loader@3.0.1
|  `-- istanbul-lib-instrument@1.10.2
|     -- babel-generator@6.26.1
|       -- babel-runtime@6.26.0
|         -- core-js@2.6.9  deduped

+-- core-js@2.6.9
-- karma@4.1.0
  -- core-js@2.6.9  deduped

Sorry for formatting, I doesn't want to add spaces at the beginning of lines.

**Comment by clydin** [comment]
npm may have hoisted some of the dependencies into positions that are causing the wrong version of core-js to be picked up.
Do you have core-js as a direct dependency of the project (in the project's `package.json`)?  If so, can you try updating that to 3.2.1 or greater?  You also may be able to remove it completely if the project is not using any polyfills directly in the `polyfills.ts` file for the project.  Angular 8+ will automatically include the Angular required polyfills.

**Comment by daganM** [comment]
Sorry again, I rolled back my version to continue working.
Here's the real output of npm ls core-js after running about `npm audit fix`

+-- @angular-devkit/build-angular@0.803.23
| -- core-js@3.2.1
+-- core-js@2.6.9
-- karma@4.1.0
  -- core-js@2.6.9  deduped


And there, don't know why, but it seems it's now working fine...

Seems like there was no real issue. Sorry for inconvenience!
