### ISSUE TITLE
[lint] TSLint 6.0 support

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#16733]
# 🚀 Feature request

### Command (mark with an `x`)
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

TSLint released a v6.0 version (marked as deprecated, and containing a few breaking changes).
The `ng lint` command only accepts a version up to v5.x so trying to bumpt TSLint results in `[error] Error: TSLint must be version 5.5 or higher.` (as mentioned in this TSLint issue https://github.com/palantir/tslint/issues/4910)

I already fixed this in #16058 but this was merged in v9, and not v8. It might be enough though.

### Describe the solution you'd like

I think that it would be nice to:
- [ ] allow users to upgrade to TSLint v6 and be able to use it, which implies fixing the check (done in v9 but not in v8, is it important?).
- [ ] change the version used in the schematics for `ng new`
- [ ] change the deault configuration in the schematics as well, as v6.0 includes a few breaking changes in `tslint:recommended` that we extend (see https://github.com/palantir/tslint/pull/4871/files and https://github.com/palantir/tslint/pull/4312/files)

**Comment by cexbrayat** [comment]
ping @filipesilva as requested to have your input.

**Comment by dgp1130** [comment]
After discussion: We can relax the warning so it allows 6.0, but it doesn't make sense to start new projects on 6.0 because it is deprecated. We're likely to transition to ESLint anyways, so this will be obsoleted by that.

**Comment by dgp1130** [comment]
Since this is a minor PR, we can cherry pick this into v8.

**Comment by snebjorn** [comment]
TSLint v6 is now out and I was just hit by this. The fix is merged but not released?

**Comment by dgp1130** [comment]
This needs to be cherry picked into v8, I think this slipped through the tracks.

@mgechev (caretaker), can you merge #16058 to 8.3.x when you get the chance?

**Comment by joshuambg** [comment]
Please and thank you.

**Comment by Splaktar** [comment]
I had a little trouble tracking down the commits for this to verify where it got fixed, so I'm linking them here:

- [v8.3.24](https://github.com/angular/angular-cli/commit/25b4d93b52cb257ca9636179c222659897827d35)
- [v9.0.0](https://github.com/angular/angular-cli/commit/31127eb050839790ec6e4201fd82b7b58aa84120)
- [v9.1.0-next.0](https://github.com/angular/angular-cli/commit/4bf175ca3a7cc201baf74c654ddd2a6cf484b25e)
