### ISSUE TITLE
How could i change the angular cli date to local time zone?

### ISSUE THREAD

**Issue by WashingtonGuedes** [angular/angular-cli#16741]
# 🚀 Feature request
https://stackoverflow.com/questions/52027181/how-could-i-change-the-angular-cli-date-to-local-time-zone

### Command (mark with an `x`)
- [x] serve

### Description
When compiling it currently displays dates in ISO formats.

### Describe the solution you'd like
When compiling I'd like to see local Date formats.

### Describe alternatives you've considered
Changing `.toISOString()` to `.toLocaleString()`.

**Comment by clydin** [comment]
The use of UTC for timestamps is intentional.  Consistent formatting of logging output is an important requirement.  This is especially relevant for CI/deployment environments which can have varying locations.
