### ISSUE TITLE
Debugging EventEmitter subscription crashes Chrome

### ISSUE THREAD

**Issue by ghost** [angular/angular-cli#16747]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [X ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 I do not know. I have not debugged EventEmitter<any> subscriber functions in other versions of Angular.

### Description

 An inherited implementation component (mypage.component.ts implements base) with a child component (searchbar.component.ts) crashes Chrome if a debug breakpoint is set inside the parent's subscriber function (where the emitted value is received). 

## 🔬 Minimal Reproduction

I have a base component (base.component.ts), an inherited implementation component (mypage.component.ts implements base). The implementation contains a child component (searchbar.component.ts). The child component contains a SELECT element. The SELECT element emits a value on its (change) function. The emitted value is caught by the parent component's subscriber function and printed to the console. No problem. However, using Visual Studio Code v1.41.1 (2019Dec18) to debug the subscriber function while running Chrome 76.0.3809.146 as the runtime environment, a breakpoint set anywhere inside the parent's subscriber function will stop the code and allow inspection of values. However, when F5 (continue) is activated, Chrome immediately crashes.

## 🔥 Exception or Error
<pre><code>

If "Aww, Snap" is an error code from Chrome then this is what I get :)
</code></pre>

## 🌍 Your Environment
<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.6
@angular-devkit/build-angular     0.803.6
@angular-devkit/build-optimizer   0.803.6
@angular-devkit/build-webpack     0.803.6
@angular-devkit/core              8.3.6
@angular-devkit/schematics        8.3.6
@angular/cli                      8.3.6
@ngtools/webpack                  8.3.6
@schematics/angular               8.3.6
@schematics/update                0.803.6
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
node (npm) version     6.9.0
</code></pre>

**Anything else relevant?**

Could not get an Edge debug runtime up and going in short order for testing

Windows 10

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Katydude** [comment]
Sure. Let me find some time in the next couple of days to do this.

**Comment by lexstarwind** [comment]
I believe I am experiencing the same problem. I put together a test project to reproduce the issue. The code works fine in Chrome when no breakpoints are set. Setting a breakpoint in master.component.ts on line 29 is enough to cause a crash. The repo is located here [Angular8EventEmitterCrashExample](https://github.com/lexstarwind/Angular8EventEmitterCrashExample.git). I'm still pretty new to Angular, so please let me know if I'm just doing something dumb.

**Comment by Katydude** [comment]
I will tell you, I just had this happen to me in an AngularJS project using Visual Studio Community 2017. Hit a breakpoint, hit continue, Chrome crash. They definitely changed something in Chrome that's wonked up debugging.

**Comment by alan-agius4** [comment]
Closing as this is no longer reproducible.
