### ISSUE TITLE
ng serve is not working on ec2 server

### ISSUE THREAD

**Issue by meerismail** [angular/angular-cli#16752]
**ng serve --host x.x.x.x** throwing error given bellow while I am running on ec2 ubuntu server of aws.

**An unhandled exception occurred: listen EADDRNOTAVAIL: address not available x.x.x.x:4200
See "/tmp/ng-kPN48h/angular-errors.log" for further details.**

Using Angular: **angular/cli@8.3.23**

Can anyone guide me to solve this?
Thanx in advance.

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
