### ISSUE TITLE
child component not get display while using router-outlet active event to get child component instance

### ISSUE THREAD

**Issue by kumaresan-subramani** [angular/angular-cli#16762]
While using router-outlet, i have used “**active**” event ton take child component instance.

> A router outlet will emit an activate event any time a new component
> is being instantiated, and a deactivate event when it is being
> destroyed.

**Sample** - https://stackblitz.com/edit/angular-router-basic-example-a9jpsd?file=app/app.component.ts

Example code –

> App.component.html

    <div class="container">
        <router-outlet (activate)="onActivate($event)"></router-outlet>
      </div>

> App.component.ts

    public onRouterOutletActivate(event : any) {
        console.log(event);
    }

But child component not get displayed at initial loading, but element is in DOM.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
