### ISSUE TITLE
Visual Studio Code debugger broken because of upgrade to core-js 3.2.1 via @angular-devkit/core: 8.3.23

### ISSUE THREAD

**Issue by MichaelDimmitt** [angular/angular-cli#16769]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

  Yes, this is a regression.

Previous version in which this bug was not present was: 
  "@angular-devkit/core": "8.1.3",

### Description

Breakpoints will not set on Visual Studio Code Debugger because angular-devkit/core 8.3.23 required more recent version of core-js: 3.2.1 .

related to #16715 

#### When checking all exception breakpoints:

1st error: core-js/internals/check-correctness-of-iteration.js
```
20: Array.from(iteratorWithReturn, function () { throw 2; });
```

2nd error: 
![image](https://user-images.githubusercontent.com/11463275/73203521-39e55d00-410b-11ea-8bd9-3cea2da2c86c.png)

3rd error:
@angular/compiler/fesm2015/compiler.js
![image](https://user-images.githubusercontent.com/11463275/73203743-a7918900-410b-11ea-9877-82df2e1d6d97.png)

#### When ignoring all exception breakpoints and putting a breakpoint on the code:
O - Breakpoint set but not yet bound.

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.23
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.23
@angular-devkit/build-angular     0.803.23
@angular-devkit/build-optimizer   0.803.23
@angular-devkit/build-webpack     0.803.23
@angular-devkit/core              8.3.23
@angular-devkit/schematics        8.3.23
@angular/cli                      8.3.23
@angular/http                     7.2.16
@ngtools/webpack                  8.3.23
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.41.5

</code></pre>

IDE: Visual Studio Code.
Operating System: Windows

changes in package-lock worth mentioning.
#### not working:
```
   "@angular-devkit/core": "8.3.23",
   
   "required": {
    "core-js": "3.2.1",
   }
```
#### working: 
```
  "@angular-devkit/core": "8.1.3",
  "required": {
    "core-js": "3.1.4"
  }
```
#### devkit/core 8.1.3 had babel runtime but 8.3.23 did not.
```
 "babel-runtime": {
      "version": "6.26.0",
      "resolved": "https://registry.npmjs.org/babel-runtime/-/babel-runtime-6.26.0.tgz",
      "integrity": "sha1-llxwWGaOgrVde/4E/yM3vItWR/4=",
      "dev": true,
      "requires": {
        "core-js": "^2.4.0",
        "regenerator-runtime": "^0.11.0"
      },
      "dependencies": {
        "core-js": {
          "version": "2.6.11",
      }
}
```
related to #16715 

package.json condensed for readability.
```
{
  "name": "condensedjson",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -o",
    "build": "sh -c 'NODE_OPTIONS=--max-old-space-size=8192 npm run build-prod'",
    "build-prod": "ng build --prod && cp web.config ./dist/smartgistics2",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/http": "^7.2.16",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@azure/msal-angular": "^0.1.4",
    "angular": "^1.7.9",
    "angular-bootstrap-md": "^7.5.1",
    "angular-font-awesome": "^3.1.2",
    "angular-org-chart": "^1.0.3",
    "angular-tree-component": "^8.4.0",
    "angularx-social-login": "^1.2.6",
    "bootstrap": "^4.3.1",
    "bootstrap-social": "^5.1.1",
    "c": "^0.1.0",
    "chartist": "^0.11.4",
    "classie": "^1.0.0",
    "core-js": "^3.5.0",
    "dexie": "^2.0.4",
    "file-saver": "^2.0.2",
    "font-awesome": "^4.7.0",
    "fs": "0.0.1-security",
    "hammerjs": "^2.0.8",
    "help": "^3.0.2",
    "jquery": "^3.4.1",
    "moment-timezone": "^0.5.26",
    "ng-chartist": "^4.1.0",
    "ngx-bootstrap": "^4.1.1",
    "ngx-logger": "^3.3.13",
    "nnjson": "^1.0.1",
    "npm-check-updates": "^3.1.9",
    "path": "^0.12.7",
    "popper.js": "^1.16.1",
    "rxjs": "~6.5.4",
    "rxjs-compat": "^6.0.0",
    "tether": "^1.4.6",
    "traverse": "^0.6.6",
    "xlsx": "^0.14.3",
    "yarn": "^1.15.2",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.801.3",
    "@angular/cli": "^8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/chartist": "^0.9.47",
    "@types/file-saver": "^2.0.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^24.9.0",
    "@types/node": "^10.14.20",
    "angular2-template-loader": "^0.6.2",
    "codelyzer": "~4.5.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.2.0",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.18.0",
    "eslint-plugin-react-hooks": "^1.6.0",
    "html-webpack-plugin": "^3.2.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.9.0",
    "jest-preset-angular": "^8.0.0",
    "prettier": "1.17.1",
    "protractor": "~5.4.0",
    "raw-loader": "^1.0.0",
    "ts-loader": "^5.2.2",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "3.4.5",
    "webpack": "^4.37.0",
    "webpack-cli": "^3.3.6",
    "webpack-dev-server": "^3.7.2"
  }
}
```

**Comment by MichaelDimmitt** [comment]
src/polyfills.js
```

/***************************************************************************************************
 * Zone JS is required by default for Angular itself.
 */
import 'zone.js/dist/zone';  // Included with Angular CLI.

/* Required for Stackblitz */
import 'core-js/proposals/reflect-metadata';

/***************************************************************************************************
 * APPLICATION IMPORTS
 */

 /*  JNW: added to get around error:  
 global is not defined at chartist.js:1173
 ref:  https://stackoverflow.com/questions/50264344/aws-sdk-crash-after-updating-from-angular5-to-angular6 */
(window as any).global = window;
```

**Comment by alan-agius4** [comment]
@MichaelDimmitt, can you please open an issue with core-js? Thanks.

**Comment by dgp1130** [comment]
Hi @MichaelDimmitt, just took a quick drive-by pass at this for an issue triage effort going on right now.

Regarding each of the problems you mentioned:
(1) and (2) appear to be errors intended to be thrown (and caught) by core-js, so it is reasonable for the debugger to break on that error. I think you might be confusing "break on exception" with "break on _uncaught_ exception".
(3) Is a break point in vendor code, which you may not have sourcemaps for as I don't think they are enabled by default (see [this article for an example](https://medium.com/@dSebastien/configuring-sourcemaps-with-the-angular-cli-3224e899d948)).

Are you still having issues with this on the latest version of the CLI?

**Comment by alan-agius4** [comment]
Closing as no further information has been provided.
