### ISSUE TITLE
Any plans to upgrade to Protractor 4 which has typescript support?

### ISSUE THREAD

**Issue by jculverwell** [angular/angular-cli#1676]
If you do it maybe worth reminding VSCode users that they need to add the entry below to their File>Preferences>Workspace Settings for intellisense to work 

{
   "typescript.tsdk":  "<YOURPROJECTPATH>/node_modules/typescript/lib"
}

More info on Protractor 4 here https://github.com/angular/protractor/tree/master/exampleTypescript

**Comment by filipesilva** [comment]
I was thinking about updating, yeah. Can't say I'm in a big rush to do it though, it's not very high priority.

Have you tried it? How was your experience with it?

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1778 updates to protractor4, and about the warning... it's editor specific so I can't say I agree with putting it up, Every editor has a different way of loading TS2.0 but soon it'll be the official latest release anyway.
