### ISSUE TITLE
@angular/cli@6.0.4 might be removed from npm registry

### ISSUE THREAD

**Issue by doggy8088** [angular/angular-cli#16789]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

`@angular/cli@6.0.4` unable to do the `ng new` by any way. This version might be able to remove from npm registry.

![image](https://user-images.githubusercontent.com/88981/73361329-b6c93000-42df-11ea-9daa-0bae78e9eb29.png)

## 🔬 Minimal Reproduction

```sh
docker run -it --rm node:lts bash
```

```log
npm install -g @angular/cli@6.0.4
ng new demo1
```

## 🔥 Exception or Error

```log
root@ffe6702d758b:/# npm install -g @angular/cli@6.0.4
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@6.0.4 postinstall /usr/local/lib/node_modules/@angular/cli
> node ./bin/ng-update-message.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/@angular/cli/node_modules/fsevents):     npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ @angular/cli@6.0.4
added 240 packages from 192 contributors in 6.616s
root@ffe6702d758b:/# ng new demo1
Schematic input does not validate against the Schema: {"dryRun":false,"version":"6.0.4","skipGit":false,"skipInstall":false,"linkCli":false,"commit":true,"newProjectRoot":"projects","inlineStyle":false,"inlineTemplate":false,"routing":false,"prefix":"app","style":"css","skipTests":false}
Errors:

  Data path "" should NOT have additional properties(dryRun).
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 6.0.4
Node: 12.14.1
OS: linux x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.4
@angular-devkit/core         0.6.4
@angular-devkit/schematics   0.6.4
@schematics/angular          0.6.4
@schematics/update           0.6.4
rxjs                         6.5.4
typescript                   2.7.2
</code></pre>

**Anything else relevant?**

There are still some versions removed from npm registry.  Such as `6.0.6` and `6.0.9`.

**Comment by alan-agius4** [comment]
@doggy8088, Angular CLI version 6 is no longer in LTS: https://angular.io/guide/releases

While, you cannot create a new application it doesn’t mean it should be removed from npm as it can break users which might be using it for other user journeys such as running a a build.

**Comment by doggy8088** [comment]
It's okay.  Never mind.

I just found a related issue: https://github.com/angular/angular-cli/issues/11006#issuecomment-392150605
