### ISSUE TITLE
Can't resolve paramaters After Webpack upgrade

### ISSUE THREAD

**Issue by ihachani** [angular/angular-cli#1678]
> Please provide us with the following information:
> ---------------------------------------------------------------

Ubuntu 16.04

angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.7
os: linux x64
Angular: 2.0.0.RC-5

I created an app using beta.10 it worked fine but after upgrade to beta.11-webpack.2 I get this error:

`Can't resolve all parameters for ServerAddressResolverService: (?).`
```
ServerAddressResolverService{
  public constructor(window: Window) {...}
}
```
And inside AppModule:
```
providers: [
    {provide: Window, useValue: window}
  ]
```
Log:
`metadata_resolver.js:551Uncaught Can't resolve all parameters for ServerAddressResolverService: (?).CompileMetadataResolver.getDependenciesMetadata @ metadata_resolver.js:551CompileMetadataResolver.getTypeMetadata @ metadata_resolver.js:448(anonymous function) @ metadata_resolver.js:594CompileMetadataResolver.getProvidersMetadata @ metadata_resolver.js:575CompileMetadataResolver.getDirectiveMetadata @ metadata_resolver.js:188(anonymous function) @ metadata_resolver.js:291CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:285RuntimeCompiler._compileComponents @ runtime_compiler.js:150RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:72RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:49PlatformRef_._bootstrapModuleWithZone @ application_ref.js:368PlatformRef_.bootstrapModule @ application_ref.js:361(anonymous function) @ main.ts:17__webpack_require__ @ bootstrap f82fca1…:52(anonymous function) @ ws (ignored):1__webpack_require__ @ bootstrap f82fca1…:52webpackJsonpCallback @ bootstrap f82fca1…:23(anonymous function) @ main.bundle.js:1`

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
This doesn't seem to be an Angular-CLI issue per se, but an Angular 2 issue. See https://github.com/angular/angular/issues/10309.

Not sure why it was working before though...
