### ISSUE TITLE
Unknown option: '--cross-origin' when passing cross-origin parameter to ng build

### ISSUE THREAD

**Issue by webilend** [angular/angular-cli#16793]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 I don't know..

### Description

 
Cannot compile specifying a cross origin option

## 🔬 Minimal Reproduction
<pre><code>
ng build --prod --aot --cross-origin=use-credentials
</code></pre>

## 🔥 Exception or Error
<pre><code>Unknown option: '--cross-origin'
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.23
Node: 10.16.3
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.6
@angular-devkit/build-angular     0.800.6
@angular-devkit/build-optimizer   0.800.6
@angular-devkit/build-webpack     0.800.6
@angular-devkit/core              8.0.6
@angular-devkit/schematics        8.3.23
@angular/cdk                      8.2.3
@angular/cli                      8.3.23
@angular/language-service         8.0.0
@ngtools/webpack                  8.0.6
@schematics/angular               8.3.23
@schematics/update                0.803.23
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**
Even passing this option in the angular.json the project won't compile, giving this exception:
<pre><code>
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(crossOrigin).
</code></pre>

**Comment by clydin** [comment]
The project's `@angular-devkit/build-angular` package appears to be out of date.  Please update it to the latest stable version (`0.803.23`).

**Comment by webilend** [comment]
> The project's `@angular-devkit/build-angular` package appears to be out of date. Please update it to the latest stable version (`0.803.23`).

I've updated `@angular-devkit/build-angular` to the latest version and it works. Thank you!
