### ISSUE TITLE
ionic serve "error unexpectedly closed (exit code 127)"

### ISSUE THREAD

**Issue by enggrohit89** [angular/angular-cli#16792]
hey, 
I am new on ionic can anyone please solve this. what should I do to run my first app on local server.

i checked "$ ionic info" it shows...

![Untitled2](https://user-images.githubusercontent.com/60439392/73374623-87ff8980-42e0-11ea-9549-84f7cc0d5ede.jpg)

and when i try to run "$ ionic serve" it shows...

![Untitled](https://user-images.githubusercontent.com/60439392/73373933-6651d280-42df-11ea-8d73-6873c99bb3fc.jpg)

thank you

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
