### ISSUE TITLE
Production build breaks in rc.11 & 12

### ISSUE THREAD

**Issue by tonivj5** [angular/angular-cli#16808]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: rc.10

### Description

Production build breaks in rc11 and 12, if I disable optimization in `angular-cli.json` it goes away. It builds in rc10.

## 🔬 Minimal Reproduction
I have tried to reproduce it using `ng new` but the build doesn't emit the same metadata (`design:type`)

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/7110786/73532498-16792580-441d-11ea-8834-b1a7e4a3f5ad.png)
![image](https://user-images.githubusercontent.com/7110786/73532517-22fd7e00-441d-11ea-86f1-908cb307a669.png)
<pre><code>
main-es2015.429909d094036241356a.js:6 Uncaught ReferenceError: Observable is not defined
    at main-es2015.429909d094036241356a.js:6
    at Object.6djU (main-es2015.429909d094036241356a.js:6)
    at i (runtime-es2015.4f2dc2db4ea44dd7357a.js:1)
    at Module.zUnb (main-es2015.429909d094036241356a.js:10)
    at i (runtime-es2015.4f2dc2db4ea44dd7357a.js:1)
    at Object.0 (main-es2015.429909d094036241356a.js:6)
    at i (runtime-es2015.4f2dc2db4ea44dd7357a.js:1)
    at t (runtime-es2015.4f2dc2db4ea44dd7357a.js:1)
    at Array.r [as push] (runtime-es2015.4f2dc2db4ea44dd7357a.js:1)
    at main-es2015.429909d094036241356a.js:1
</code></pre>

If I disable optimization it works, and Observable is imported from webpack imports instead of as a global variable.
![image](https://user-images.githubusercontent.com/7110786/73533841-06af1080-4420-11ea-97c5-8d613b32db7b.png)

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.12
Node: 13.7.0
OS: linux x64

Angular: 9.0.0-rc.11
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.12
@angular-devkit/build-angular     0.900.0-rc.12
@angular-devkit/build-optimizer   0.900.0-rc.12
@angular-devkit/build-webpack     0.900.0-rc.12
@angular-devkit/core              8.3.24
@angular-devkit/schematics        8.3.24
@angular/cdk                      8.2.3
@angular/cli                      9.0.0-rc.12
@angular/language-service         9.0.0-rc.12
@ngtools/webpack                  9.0.0-rc.12
@schematics/angular               9.0.0-rc.12
@schematics/update                0.900.0-rc.12
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
    
Done in 0.44s.

</code></pre>

**Anything else relevant?**

**Comment by mallen** [comment]
Same issue here - works with optimization disabled

![image](https://user-images.githubusercontent.com/107556/73549121-e68c4b00-4439-11ea-9c97-919f21247d2c.png)

**Comment by alan-agius4** [comment]
Hi, can confirm that build optimizer is enabled?  It's strange that design metadata are being retained. 

We'd need some more details to determine from where the regression came;
1) Can you update Angular FW and CLI/Build-Angular individually and confirm which update causes the regression?
2) Can you kindly share the one of the classes that is causing the error?

**Comment by mallen** [comment]
Hi,

Updating individually gives the following results
- Angular FW rc.10 and CLI/Build-Angular rc.10 works
- Angular FW rc.11 and CLI/Build-Angular rc.10 works
- Angular FW rc.11 and CLI/Build-Angular rc.11 fails

![image](https://user-images.githubusercontent.com/107556/73575484-3259e700-4470-11ea-8943-ad053ac7210f.png)

or with --source-map

![image](https://user-images.githubusercontent.com/107556/73575326-d8f1b800-446f-11ea-8b80-636f1964401b.png)

Possibly `@Select` from ngxs is causing the issue


Class is

```
import { Component, Input, OnInit } from '@angular/core';
import { Select, Store } from '@ngxs/store';
import { AppState } from '../app.state';
import { Observable, throwError } from 'rxjs';
import { MenuItem, ParentMenuItem, PlanMenuItem, StandardMenuItem } from '../menu/menu-item';
import { RemovePlanMenuItem } from '../menu/menu.actions';
import { catchError, debounceTime, first, take } from 'rxjs/operators';
import { ContextState } from '../shared/services/context.state';
import { User } from '../shared/user';
import { ContextService } from '../shared/services/context.service';
import { BackgroundType, SettingsService } from '../settings/settings.service';
import { environment } from '../../environments/environment';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Meta } from '@angular/platform-browser';

@Component({
               selector: 'app-navigation',
               templateUrl: './navigation.component.html',
               styleUrls: ['./navigation.component.scss']
           })
export class NavigationComponent implements OnInit {
    @Select(AppState.standardMenuItems) standardMenuItems$: Observable<StandardMenuItem[]>;
    @Select(AppState.parentMenuItems) parentMenuItems$: Observable<ParentMenuItem[]>;
    @Select(AppState.planMenuItems) planMenuItems$: Observable<PlanMenuItem[]>;
    user: User;
    logoSource = 'assets/images/logo_dark.svg';
    @Input() title: string;
    logoutDisabled = false;
    showThemeMenu = false;
    private logoutUrl: string;

    constructor(private store: Store,
                public context: ContextService,
                private settingsService: SettingsService,
                private http: HttpClient,
                private meta: Meta) {
    }

    ngOnInit() {
        this.settingsService.backgroundType$
            .subscribe((bt: BackgroundType) => {
                this.logoSource = bt === 'dark' ? 'assets/images/logo_dark.svg' : 'assets/images/logo_light.svg';
            });

        this.store.select(ContextState.user)
            .pipe(first(user => !!user))
            .subscribe((user => {
                    this.user = user;
                    this.settingsService.setTheme(user, this.settingsService.getThemeFromLocalStorage(user));
            }));

        this.logoutUrl = this.meta.getTag('name=_casLogoutUrl').content;

        if (Storage) {
            this.showThemeMenu = true;
        }
    }

    close(item: MenuItem) {
        if (item instanceof PlanMenuItem) {
            return this.store.dispatch(new RemovePlanMenuItem(item.id));
        }
    }

    logOutClick() {
    }
}

```

**Comment by lVlyke** [comment]
Hi,

I'm seeing the same issue on my end with `@angular-devkit/build-angular` rc.11 and rc.12. I maintain the [@lithiumjs/angular](https://github.com/lVlyke/lithium-angular) library, which is decorator-based like NGXS. I maintain an [example app](https://github.com/lVlyke/lithium-angular-example-app) for the library that also makes use of NGXS. I'm seeing the same behavior when running `ng serve --prod` with `@angular-devkit/build-angular` rc.12:

![Annotation 2020-01-31 181918](https://user-images.githubusercontent.com/33110145/73583229-113cca80-445f-11ea-9bfb-95a5dc60f203.png)

The issue appears to happen with `@Select` from NGXS, and decorators like `@StateEmitter` and `@EventSource` from Lithium. As mentioned, setting `optimization: false` fixes the problem, but is not ideal of course. After enabling sourcemaps, I can see the error happens in the [`SessionUtils`](https://github.com/lVlyke/lithium-angular-example-app/blob/4.0.0/src/app/utils/session-utils.service.ts) service on the following line:

![Annotation 2020-01-31 190754](https://user-images.githubusercontent.com/33110145/73583252-2fa2c600-445f-11ea-957a-aff2ef00defb.png)

[Branch 4.0.0](https://github.com/lVlyke/lithium-angular-example-app/tree/4.0.0) of my example app project, which uses `@angular-devkit/build-angular`  **rc.10**, works fine with `ng serve --prod`. I created [another branch](https://github.com/lVlyke/lithium-angular-example-app/tree/4.0.0-%40angular-devkit/build-angular-rc.12) which simply updates the devkit version to **rc.12**, and that causes the above build issue with `ng serve --prod`.

Hopefully this helps. Thanks.

**Comment by clydin** [comment]
It appears that the common element is that all the projects have the `emitDecoratorMetadata` option enabled.  This option has not been required by Angular since version 8.0.4 and newly created projects no longer contain the option.  Unless a third-party library or the application code specifically require the presence of the option, it can be safely removed.  The need for this option is generally uncommon.  Also of note is that the option generates code ([more details](https://github.com/microsoft/TypeScript/issues/27519)) that has the potential to cause runtime errors.
However, for the cases where the option is required, a fix is currently being investigated.

**Comment by lVlyke** [comment]
@clydin Interesting, thanks for the info. Removing the use of ES7 reflection and `emitDecoratorMetadata` from the project does indeed resolve the issue with rc.12.

**Comment by Timebutt** [comment]
Wow thanks guys, removing `emitDecoratorMetadata = true` fixed the issue for me too! I was looking everywhere to try and fix this issue until finding this issue 🙌. I can only imagine plenty of other people will also face this cryptic issue, so the `v9-blockers` milestone is definitely warranted 💪
