### ISSUE TITLE
TONS of errors after using "npm install" from Verson 8.3.23, but application was developed with 7.0.5

### ISSUE THREAD

**Issue by martijintro** [angular/angular-cli#16809]
Im not sure it's an `npm` or `angular` issue (or maybe a `node-sass` one??):

https://github.com/npm/cli/issues/752

Thank you for your feedbacks.

Regards, Jan

**Comment by alan-agius4** [comment]
Angular CLI 8 no longer requires `node-sass` by default as it uses dart `sass`.

We also reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by martijintro** [comment]
ok thx
