### ISSUE TITLE
Allow generation of suffix-free file and symbol names

### ISSUE THREAD

**Issue by mgechev** [angular/angular-cli#16811]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...

During style guide meetings we discussed that although recommended for most projects, suffixes in names of components, directives, and services in particular could be redundant for some projects.

We'd not change the official style guide recommendation, but we'd want to enable folks with advanced use cases to drop the suffixes when needed.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

This proposal is for a global CLI flag per project which disables the current default behavior. When this flag is enabled it'll not suffix any of the generated files, nor the declared symbols inside of them.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Drop suffixes completely, which is bad for most projects.

**Comment by sacgrover** [comment]
@mgechev I have started working on it.

**Comment by alan-agius4** [comment]
This has been addressed via https://github.com/angular/angular-cli/pull/17040
