### ISSUE TITLE
support rootDirs in typescript

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#16814]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#virtual-directories-with-rootdirs

**Comment by alan-agius4** [comment]
Can you elaborate the usage case and what is the current behaviour when using `rootDirs` with `ngtools`?

Thanks.

**Comment by alan-agius4** [comment]
Closing as no further information has been provided
