### ISSUE TITLE
ng e2e port option does not work

### ISSUE THREAD

**Issue by mattmbrightside** [angular/angular-cli#16820]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
If I attempt to set a port for the ng e2e command to pass through to the ng serve, I get an error message Unknown option: '--port'
According to the angular cli docs, this should be a valid option:
https://angular.io/cli/e2e

--port | The port to use to serve the application.

## 🔬 Minimal Reproduction
Create an angular application
run $ ng e2e --port=5300

## 🔥 Exception or Error
<pre><code>
Unknown option: '--port'

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.14
Node: 10.10.0
OS: darwin x64
Angular: 8.2.14
Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.14
@angular-devkit/build-angular      0.803.21
@angular-devkit/build-ng-packagr   0.803.22
@angular-devkit/build-optimizer    0.803.21
@angular-devkit/build-webpack      0.803.21
@angular-devkit/core               8.3.14
@angular-devkit/schematics         8.3.14
@angular/cli                       8.3.14
@angular/fire                      5.3.0
@ngtools/webpack                   8.3.21
@schematics/angular                8.3.14
@schematics/update                 0.803.14
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @mattmbrightside, I tried this locally and cannot replicate the issue locally.

 Are you using a different builder for the default once? Can you share your `angular.json` please?

**Comment by mattmbrightside** [comment]
I generated the angular.json using the Nx monorepo tool
I came up with a workaround for my issue by adding a serve configuration of
"e2e": {
              "port": 5300
            }
and then pointing the e2e project devServerTarget to the new config
"devServerTarget": "myproj:serve:e2e"

[angular.json.txt](https://github.com/angular/angular-cli/files/4150078/angular.json.txt)

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the NX project or file an issue on their issue tracker.
