### ISSUE TITLE
Alias for ng doc as d not working 

### ISSUE THREAD

**Issue by OmarioHasan** [angular/angular-cli#16825]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

it assume that i will make a deploy but in documentation it says ng d <keyword> [options] for openinig documentation

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
![image](https://user-images.githubusercontent.com/8146344/73709828-d959af80-470a-11ea-86cc-991d2cb153d5.png)
![image](https://user-images.githubusercontent.com/8146344/73709851-e5de0800-470a-11ea-9801-463e18e14863.png)

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/16826
