### ISSUE TITLE
live-reloading broken (again): misunderstandings about webpack's sockPath

### ISSUE THREAD

**Issue by flensrocker** [angular/angular-cli#16836]
# 🐞 Bug report

Follow up from #16410 and #15883 

### Command (mark with an `x`)
- [x] serve

### Is this a regression?

Kind of... I think there are competing setups of different development environments.

### Description

There seem to be different interpretations where the `sockjs-node` endpoint of the webpack development server should be reachable.

My usecase:

I have an Asp.Net Core project with multiple angular-apps on the client side. Each Angular dev-server runs on a different port (configured in angular.json in `projects.appX.architect.serve.port`.
In `projects.appX.architect.build.deployUrl` is the `/appX/ `, because every request under that url is redirected either to the static files of the built app (in production mode) or proxied to the dev-server (in development mode).

The url of the Asp.Net Core project is given as `public-host` to `ng serve`, so each live-reload client knows, where to reach its server (something like `https://localhost:44733/appX`, all apps get the same url obviously). Every request on the baseHref of each app is proxied to the right port of the corresponding dev-server (which is configured within the Asp.Net Core project).

The Asp.Net Core backend doesn't change the request path on these request, so a request heading to `public-host/appX/sockjs-node/info` will be proxied to `http://localhost:4500/appX/sockjs-node/info`. Unfortunatly webpack was listening on `http://localhost:4500/sockjs-node/info` so live-reloading didn't work.

Commit 5260bbb added the missing webpack option so everything worked fine. But this seem to break other people's setup, because they configured their reverse proxies in a different way, so all requests to `public-host/appX/sockjs-node` are forwarded to `http://localhost:4500/sockjs-node/info`.

Is there any kind of configuration option, so I can serve the `sockjs-node` endpoint under the baseHref? Maybe I'm missing something, but the documentation is not very clear about the topic, how baseHref, deployUrl, servePath and publicHost are meant to work together.

Does any option of these have an effect on webpack?

**Comment by alan-agius4** [comment]
Hi @flensrocker, 

When `servePath` is not specified the `baseHref`/`deployUrl` are prepended out-of-the-box when to the `sockjs-node` endpoint, unless it's an absolute url. In which case a warning will be issued. when a `serverPath` is specified, you'd need to include the `baseHref` to this path manually.

When you're proxying dev-server, the live reload script does not always know where to connect to. While will try to guess the URL based on `window.location` in some cases this might not work. Hence, you can use the `publicHost` to override this. Example: if the dev-server is proxied and available on `public-host:8080`, you can set `publicHost` to the same value.

If the problem persists kindly let me know and I'll re-open the issue.

**Comment by flensrocker** [comment]
I try my best to explain the problem.

I use `--publicHost=https://localhost:44364/app-material/` which is pointing to my Asp.Net Core service.

The webpack dev-server is listening on the right port and URL:
```
** Angular Live Development Server is listening on localhost:4500, open your browser on http://localhost:4500/app-material **
```

The Asp.Net Core service redirects every request on `https://localhost:44364/app-material/` to `http://localhost:4500/app-material/` with its method [`UseProxyToSpaDevelopmentServer`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.spaproxyingextensions.useproxytospadevelopmentserver?view=aspnetcore-3.0).

The Angular App tries to connect to the live-reload-server with the URL `https://localhost:44364/app-material/sockjs-node/info?t=1603290877691` as expected which will be redirected by the Asp.Net Core service to `http://localhost:4500/app-material/sockjs-node/info?t=1603290877691`

But webpack is listening on `http://localhost:4500/sockjs-node/info`

All other files are served under `http://localhost:4500/app-material/` except the `sockjs-node/info` endpoint.

I tried the `servePath` in angular.json, but that is not fixing the problem.

As a workaround I rewrite the request path on the sockjs-node URL in my Asp.Net Core service like
```
app.UseWhen(context => context.Request.Path.Value.StartsWith($"/app-material/sockjs-node"), spaApp =>
{
  spaApp.UseRewriter(new RewriteOptions()
    .AddRewrite("^app-material/(.+)", "$1", true));
  spaApp.UseSpa(spa => spa.UseProxyToSpaDevelopmentServer("http://localhost:4500"));
});
```

The commit 5260bbb fixed the URL on which webpack is listening with its `sockjs-node` endpoint, but that was reverted, perhaps because many developers already use something like my rewrite rule on their setups and so their setup broke.

So my question is: how can I configure webpack, that the `sockjs-node` endpoint is reachable under the path, where everything else is served?
It seems a bit awkward to have to rewrite only the requests on that endpoint.

**Comment by alan-agius4** [comment]
@flensrocker, I believe that this should no longer be an issue in upcoming version of the Angular CLI.

Here's a quick test that I did.
```
ng serve --publicHost=http://localhost:44364/app-material/ --baseHref=/app-material/
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/app-material **

curl http://localhost:4200/app-material/sockjs-node/info\?t\=1603290877691
{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":1033180931}%
```

Same thing works if a baseHref is not specified.
```
ng serve --publicHost=http://localhost:44364/app-material/
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200 **

curl http://localhost:4200/app-material/sockjs-node/info\?t\=1603290877691
{"websocket":true,"origins":["*:*"],"cookie_needed":false,"entropy":1033180931}%
```

**Comment by flensrocker** [comment]
Ok, thanks, I will test when it's released. Angular 11 or a minor release? I'm on 10.1.1

**Comment by alan-agius4** [comment]
@flensrocker, following a convo @clydin he mentioned that the second case above is actually a breaking change and should be fixed via (https://github.com/angular/angular-cli/pull/19174).

The `publicHost` option shouldn't not have any effect on `sockjs-node`. However, `baseHref`, `deployUrl`, `servePath` will be prepended to the `sockjs-node` path (https://github.com/angular/angular-cli/pull/19174).

This will be available on in Angular 11+,  you can try to use this by updating using `ng update @angular/cli @angular/core ---next`. The fix will be in the RC that should be cut later on today.

**Comment by flensrocker** [comment]
Great news, thanks!
