### ISSUE TITLE
when i try to print a page in angular 8.2.5, print area popup and suddenly closed at the same time, but before in angular 6 version it was working fine

### ISSUE THREAD

**Issue by mjunaid1990** [angular/angular-cli#16845]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by mjunaid1990** [comment]
package json detail,
{
  "name": "aoa-cli8",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.5",
    "@angular/cdk": "^8.1.4",
    "@angular/common": "~8.2.4",
    "@angular/compiler": "~8.2.4",
    "@angular/core": "~8.2.4",
    "@angular/forms": "~8.2.4",
    "@angular/material": "^8.1.4",
    "@angular/platform-browser": "~8.2.4",
    "@angular/platform-browser-dynamic": "~8.2.4",
    "@angular/pwa": "^0.803.3",
    "@angular/router": "~8.2.4",
    "@angular/service-worker": "~8.2.4",
    "@swimlane/ngx-datatable": "^16.0.2",
    "angular2-signaturepad": "^2.9.0",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "core-js": "^3.2.1",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "ng-connection-service": "^1.0.4",
    "ngx-barcode": "^0.2.4",
    "ngx-dropzone-wrapper": "^8.0.0",
    "ngx-localstorage": "^2.4.0",
    "ngx-onsenui": "^7.0.0",
    "ngx-spinner": "^8.0.3",
    "onsenui": "^2.10.10",
    "popper": "^1.0.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.3",
    "@angular/cli": "^8.3.3",
    "@angular/compiler-cli": "~8.2.4",
    "@angular/language-service": "~8.2.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "electron-packager": "^14.0.5",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by mjunaid1990** [comment]
Thanks for your reply alan,
it is a large app and it will take so much time to create it again.


but i can show you which code i m using for this purpose.

setTimeout(() => {
			let printContents, popupWin;
			printContents = document.getElementById('level-'+id).innerHTML;
			popupWin = window.open('', '_blank', 'top=0,left=0,height=100%,width=auto');
			popupWin.document.open();
			popupWin.document.write(`
				  <html>
					  <head>
					  <title>Print tab</title>
						<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
					  <style>
					  //........Customized style.......
					  </style>
					  </head>
				  <body onload="window.print();window.close()">${printContents}</body>
				  </html>`
			);
			window.onfocus = function () { setTimeout(function () { popupWin.document.close(); }, 500); }
			
			this.is_print = false;
		  }, 1000);

**Comment by clydin** [comment]
Unfortunately, without a reproduction there is not much that can be done to investigate this issue.
If the problem is still occurring on the latest version of Angular, please try to provide a minimal reproduction so that it can be further investigated.
