### ISSUE TITLE
Error in installation .

### ISSUE THREAD

**Issue by goriunov** [angular/angular-cli#1684]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
node v4.4.7
angular-cli 1.0.0-beta.11-webpack.2 

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Nothing 

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Can not install last
233632 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
233633 verbose cwd /Users/goriunov
233634 error Darwin 15.6.0
233635 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "angular-cli@1.0.0-beta.11-webpack.2"
233636 error node v4.4.7
233637 error npm  v2.15.8
233638 error code EPEERINVALID
233639 error peerinvalid The package typescript@2.0.0 does not satisfy its siblings' peerDependencies requirements!
233639 error peerinvalid Peer @angular/tsc-wrapped@0.2.2 wants typescript@^1.9.0-dev
233639 error peerinvalid Peer ts-helpers@1.1.1 wants typescript@>=1.8.0 || >=1.9.0-dev
233639 error peerinvalid Peer tslint@3.14.0 wants typescript@>=1.7.3
233640 verbose exit [ 1, true ]

5. Mention any other details that might be useful.
I just installed new OS and installed node after i run installation of Angular CLI and i could not do it 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jasedwards** [comment]
same issue here.  the little info I found on errors like this said you could ignore them but that does not seem to be correct as npm install stops at that point.  when I ran ng new it immediately errored out stating could not find portfinder and am unable to run npm install on angular-cli as I get the error mentioned in the original post.

**Comment by davinkevin** [comment]
Same problem solved by using NPM3 for me

**Comment by 0917** [comment]
I had the same problem trying to upgrade from angular-cli: 1.0.0-beta.10 to angular-cli@webpack

My environment: node v4.5.0, npm 2.15.9, Ubuntu 14.04.

Resolved when upgraded to node v6.4.0, npm 3.10.3.

After successful installation I've seen only following text in red:
  ├── UNMET PEER DEPENDENCY typescript@2.0.0

So loosely related to #1737 and #1046.

**Comment by amellnik** [comment]
@davinkevin's method worked for me -- I used the npm3 package and it installed as admin under Windows x64.

**Comment by filipesilva** [comment]
The problem is that NPM3 is needed, yes. It's not currently mentioned on the readme but https://github.com/angular/angular-cli/pull/1748 adds that.

**Comment by akashgill1687** [comment]
how to use npm3 ?
could you please provide some steps ?

**Comment by amellnik** [comment]
@akashgill1687 `npm install -g npm3` and then use `npm3` in place of `npm` to install or just update npm to the latest version.

**Comment by akashgill1687** [comment]
cool it worked . i updated my npm . now can i upgrade my new project created with angular cli to to rlc5 ? and use rlc5 features ? if yes could you please jot down some steps for that please ? Thanks a lot

**Comment by akashgill1687** [comment]
i would like to add rlc5 features like aot ?

**Comment by filipesilva** [comment]
We don't currently support AOT but are working to get that into the CLI. To update NPM, see http://stackoverflow.com/a/6237400/2116927

**Comment by akashgill1687** [comment]
alright but can i use this compiler with cli@webpack : https://github.com/angular/angular/tree/master/modules/%40angular/compiler-cli

**Comment by akashgill1687** [comment]
i ended up this issue :  
ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:51:25
Cannot find name 'DateConstructor'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:56:51
Cannot find name 'String'.
sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:59:54
Cannot find name 'Object'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:63:49
Cannot find name 'Date'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:67:58
Cannot find name 'Map'.

ERROR in [default] sampleApp/node_modules/@angular/core/src/facade/lang.d.ts:72:36
Cannot find name 'RegExp'.

Angular 2 rlc5 with angular-cli errors while ng serve

**Comment by filipesilva** [comment]
We don't currently support it so I don't think that'll work.

**Comment by davidrensh** [comment]
install node v6.4.0 manually from https://nodejs.org/en/  @19390917 is right.

**Comment by davidrensh** [comment]
It shows cli beta.10 not 11-webpack.2
![image](https://cloud.githubusercontent.com/assets/14281421/17937111/3ebab6d4-69de-11e6-9bb6-ba509d3dcfc4.png)
