### ISSUE TITLE
Wrong request for ng doc -s

### ISSUE THREAD

**Issue by OmarioHasan** [angular/angular-cli#16840]
When i run ng doc component it works well but when i try to use -s for all searches option it gives wrong value 

![image](https://user-images.githubusercontent.com/8146344/73709472-ddd19880-4709-11ea-8c22-33c8c429fb2f.png)

**Comment by santoshyadav198613** [comment]
Let me know @gkalpak i will take this once, we have final call on changes.

**Comment by gkalpak** [comment]
As discussed "offline", we will go with the second approach (changing to URL to `https://v8.angular.io/?search=<some-term>`). Given that the search will be for a single term, the results should be fine.

**Comment by santoshyadav198613** [comment]
Cool @gkalpak I will make the changes.

**Comment by santoshyadav198613** [comment]
Just an question here @gkalpak , it will be only for -s option right.
