### ISSUE TITLE
CLI not respecting default schematics

### ISSUE THREAD

**Issue by gabrieltaets** [angular/angular-cli#16857]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 8

### A clear and concise description of the problem...
 On Angular 9, even though I have my default schematics set to use .scss and not generate spec files, when using ng generate, the CLI ignores my preferences.
This used to work fine on Angular 8.

![image](https://user-images.githubusercontent.com/22807067/73983346-f9f55580-4914-11ea-8680-1afe5f37abef.png)

![image](https://user-images.githubusercontent.com/22807067/73983492-5789a200-4915-11ea-81e4-a8cb939963a8.png)

## 🔬 Minimal Reproduction
Set a schematics for styleext on angular.json and run ng generate.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.10
Node: 10.16.3
OS: linux x64

Angular: 9.0.0-rc.10
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.10
@angular-devkit/build-angular     0.900.0-rc.10
@angular-devkit/build-optimizer   0.900.0-rc.10
@angular-devkit/build-webpack     0.900.0-rc.10
@angular-devkit/core              9.0.0-rc.10
@angular-devkit/schematics        9.0.0-rc.10
@angular/cdk                      8.2.3
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  9.0.0-rc.10
@schematics/angular               9.0.0-rc.10
@schematics/update                0.900.0-rc.10
rxjs                              6.5.3
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by gabrieltaets** [comment]
explicitly stating the collection does not seem to help:
![image](https://user-images.githubusercontent.com/22807067/73985179-493d8500-4919-11ea-9538-2f3169d379ce.png)

**Comment by sacgrover** [comment]
@gabrieltaets 
In Angular 9, Deprecated schematics options have been removed.

**Old way:**

```
 "@schematics/angular:component": {
          "styleext": "scss",
          "spec": true
        }
```

**New way:**

```
 "@schematics/angular:component": {
          "style": "scss",
          "skipTests": true
        }
```

You can get more details from here : https://angular.io/cli/generate#component-command

**Comment by sacgrover** [comment]
@filipesilva @mgechev Although, ng update from 8 to 9 should take care of it.  It should replace deprecated/removed options to new corresponding options. Currently, It's not doing it.

**Comment by gabrieltaets** [comment]
> @gabrieltaets
> In Angular 9, Deprecated schematics options have been removed.
> 
> **Old way:**
> 
> ```
>  "@schematics/angular:component": {
>           "styleext": "scss",
>           "spec": true
>         }
> ```
> 
> **New way:**
> 
> ```
>  "@schematics/angular:component": {
>           "style": "scss",
>           "skipTests": true
>         }
> ```
> 
> You can get more details from here : https://angular.io/cli/generate#component-command

Yup, that did the trick. Thanks, I spent quite some time trying to figure this out. Maybe a warning on the CLI for deprecated/unknown options in angular.json could be helpful, I had no idea these were deprecated and removed.

**Comment by kmjungersen** [comment]
Confirming `ng update` is not updating this.

Also it's important to note that the boolean logic has flipped for `spec` vs. `skipTests`:

```js

"@schematics/angular:component": {
    // true => DO generate spec files, false => DON'T generate them
    "spec": false    
}

"@schematics/angular:component": {
    // true => DON'T generate spec files, false => DO generate them
    "skipTests": true    
}
```

**Comment by benjamin-wilson** [comment]
Bump, just upgraded to v9 and had to change"styleext" to "style" for component generation to work as expected
