### ISSUE TITLE
ng new --style=compass not working

### ISSUE THREAD

**Issue by johndouglascm** [angular/angular-cli#1685]
os: darwin x64
angular cli: 1.0.0-beta11-webpack.2
node: 4.2.1

To reproduce:
1) ng new fooproj --style=compass
2) ng build
3) ng serve

=> runtime error: (page fails to render)
Uncaught Error: Expected 'styles' to be an array of strings.  (assertions.js 20)

Notes:

1) --style=sass works as expected
2) ng get defaults => "styleExt":"compass"
3) Flailing around: tried npm install --save-dev angular-cli@webpack & ng init to no benefit.
4) #784   https://github.com/angular/angular-cli/issues/784 and #1162  https://github.com/angular/angular-cli/issues/1162 were closed with #1455 webpack merge.

**Comment by filipesilva** [comment]
As far as I can tell, we've actually dropped support for compass per se. I'll update the README.

**Comment by saulshanabrook** [comment]
Do you have any advise for this bug for `scss`?

**Comment by filipesilva** [comment]
@saulshanabrook `scss` should work out of the box. See https://github.com/angular/angular-cli#css-preprocessor-integration for information. If it doesn't please do open a new issue for it so we can fix.

**Comment by neha-s16** [comment]
I@filipesilva I need to use css sprites (svg and png with angular-cli) any options for that?

**Comment by filipesilva** [comment]
@neha-s16 it should work out of the box really. Let me know if it doesn't

**Comment by neha-s16** [comment]
@filipesilva Thanks for prompt response. Which folder should I keep the svgs / images in for it to work and create sprites? I need to know the out folder as well since i would need to include it in styles.scss file.

**Comment by filipesilva** [comment]
@neha-s16 if you're referencing them from css/sass files you can keep them wherever you feel like. The build system will pull them up and rename them and it should just work.

If you need to link them from elsewhere or use it in html `img` tags, then put it in `src/assets`. It will be copied over to `dist/assets` so it shouldn't make a difference in your relative path. If you need more folders to be copied over, open `angular-cli.json` and add it to the `assets/` array.

**Comment by neha-s16** [comment]
Doesn't look like its working. My images are in assets/images/common/normal and assets/images/common/retina. I used ng build to build the project and it copied all images in dist/ folders but did not generate the normal.png and retina.png sprites as I expected.

**Comment by filipesilva** [comment]
I might be misunderstanding the issue then. Can you open a new issue with a repro so I can test please?

**Comment by neha-s16** [comment]
#4054 New Issue.
