### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by Toso82** [angular/angular-cli#16868]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] xi18n
- [ ] lint
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 
Update my project from angular cli 8.3.25 to latest version

## 🔬 Minimal Reproduction

ng update @angular/cli @angular/core

## 🔥 Exception or Error
<pre><code>

[error] Error: Cannot find module '@angular-devkit/core'
Require stack:
- C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js
- C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\migrations\move-document\index.js
- C:\Users\Giacomo\AppData\Local\Temp\.ng-temp-packages-4EE2gk\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\Giacomo\AppData\Local\Temp\.ng-temp-packages-4EE2gk\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\Giacomo\AppData\Local\Temp\.ng-temp-packages-4EE2gk\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\Giacomo\AppData\Local\Temp\.ng-temp-packages-4EE2gk\node_modules\@angular\cli\models\command-runner.js
- C:\Users\Giacomo\AppData\Local\Temp\.ng-temp-packages-4EE2gk\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Giacomo\AppData\Local\Temp\.ng-temp-packages-4EE2gk\node_modules\@angular\cli\lib\init.js
- C:\Users\Giacomo\AppData\Local\Temp\.ng-temp-packages-4EE2gk\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:19:20
    at C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:10:17
    at Object.<anonymous> (C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\utils\project_tsconfig_paths.js:16:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\migrations\move-document\index.js:22:38
    at C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\migrations\move-document\index.js:10:17
    at Object.<anonymous> (C:\Users\Giacomo\Documents\Progetti\Angular\forMca\node_modules\@angular\core\schematics\migrations\move-document\index.js:16:3)
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 13.7.0
OS: win32 x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               9.0.1 (cli-only)
@angular-devkit/schematics         9.0.1
@angular/cdk                       8.2.3
@angular/cli                       9.0.1
@angular/flex-layout               8.0.0-beta.27
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@angular/pwa                       <error>
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1 (cli-only)
@schematics/update                 0.900.1
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
Bit of odd version info, I wasn't expecting the two `9.0.1 (cli-only)` listed there. Do you have `@angular-devkit/core ` listed in your package.json?

Can you also show me the result of `npm list @angular-devkit/core` and `npm list @schematics/angular` please?

**Comment by Toso82** [comment]
<code><pre>
for-mca@1.0.12 C:\Users\Giacomo\Documents\Progetti\Angular\forMca
+-- UNMET DEPENDENCY @angular-devkit/schematics@8.3.25
| `-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
+-- UNMET DEPENDENCY @angular/cli@8.3.25
| +-- UNMET DEPENDENCY @angular-devkit/architect@0.803.25
| | `-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
| +-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
| +-- UNMET DEPENDENCY @angular-devkit/schematics@8.3.25
| | `-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
| +-- UNMET DEPENDENCY @schematics/angular@8.3.25
| | `-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
| `-- UNMET DEPENDENCY @schematics/update@0.803.25
|   +-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
|   `-- UNMET DEPENDENCY @angular-devkit/schematics@8.3.25
|     `-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
`-- UNMET DEPENDENCY @angular/pwa@0.803.25
  +-- UNMET DEPENDENCY @angular-devkit/core@8.3.25
  `-- UNMET DEPENDENCY @schematics/angular@8.3.25
    `-- UNMET DEPENDENCY @angular-devkit/core@8.3.25

npm ERR! missing: @angular-devkit/schematics@8.3.25, required by for-mca@1.0.12
npm ERR! missing: @angular/cli@8.3.25, required by for-mca@1.0.12
npm ERR! missing: @angular/pwa@0.803.25, required by for-mca@1.0.12
npm ERR! missing: @angular-devkit/core@8.3.25, required by @angular-devkit/schematics@8.3.25
npm ERR! missing: @angular-devkit/architect@0.803.25, required by @angular/cli@8.3.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @angular/cli@8.3.25
npm ERR! missing: @angular-devkit/schematics@8.3.25, required by @angular/cli@8.3.25
npm ERR! missing: @schematics/angular@8.3.25, required by @angular/cli@8.3.25
npm ERR! missing: @schematics/update@0.803.25, required by @angular/cli@8.3.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @angular-devkit/architect@0.803.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @angular-devkit/schematics@8.3.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @schematics/angular@8.3.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @schematics/update@0.803.25
npm ERR! missing: @angular-devkit/schematics@8.3.25, required by @schematics/update@0.803.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @angular-devkit/schematics@8.3.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @angular/pwa@0.803.25
npm ERR! missing: @schematics/angular@8.3.25, required by @angular/pwa@0.803.25
npm ERR! missing: @angular-devkit/core@8.3.25, required by @schematics/angular@8.3.25
</code></pre>

<code><pre>
PS C:\Users\Giacomo\Documents\Progetti\Angular\forMca> npm list @schematics/angular
for-mca@1.0.12 C:\Users\Giacomo\Documents\Progetti\Angular\forMca
+-- UNMET DEPENDENCY @angular/cli@8.3.25
| `-- UNMET DEPENDENCY @schematics/angular@8.3.25
`-- UNMET DEPENDENCY @angular/pwa@0.803.25
  `-- UNMET DEPENDENCY @schematics/angular@8.3.25

npm ERR! missing: @angular/cli@8.3.25, required by for-mca@1.0.12
npm ERR! missing: @angular/pwa@0.803.25, required by for-mca@1.0.12
npm ERR! missing: @schematics/angular@8.3.25, required by @angular/cli@8.3.25
npm ERR! missing: @schematics/angular@8.3.25, required by @angular/pwa@0.803.25
</code></pre>

**Comment by filipesilva** [comment]
That's a lot of missing deps, things shouldn't even run like that... are you using yarn in your project maybe? If so, can you use `yarn list` instead of `npm list` please?

**Comment by Toso82** [comment]
Sorry  i'm not use npm install before i have recovery project. This is before update:

<code><pre>
PS C:\Users\Giacomo\Documents\Progetti\Angular\forMca> npm list @schematics/angular
for-mca@1.0.12 C:\Users\Giacomo\Documents\Progetti\Angular\forMca
+-- @angular/cli@8.3.25
| `-- @schematics/angular@8.3.25
`-- @angular/pwa@0.803.25
  `-- @schematics/angular@8.3.25
</code></pre>

<code><pre>
PS C:\Users\Giacomo\Documents\Progetti\Angular\forMca> npm list @angular-devkit/core
for-mca@1.0.12 C:\Users\Giacomo\Documents\Progetti\Angular\forMca
+-- @angular-devkit/build-angular@0.803.25
| +-- @angular-devkit/architect@0.803.25
| | `-- @angular-devkit/core@8.3.25
| +-- @angular-devkit/build-webpack@0.803.25
| | `-- @angular-devkit/core@8.3.25
| +-- @angular-devkit/core@8.3.25
| `-- @ngtools/webpack@8.3.25
|   `-- @angular-devkit/core@8.3.25
+-- @angular-devkit/schematics@8.3.25
| `-- @angular-devkit/core@8.3.25
+-- @angular/cli@8.3.25
| +-- @angular-devkit/core@8.3.25
| +-- @angular-devkit/schematics@8.3.25
| | `-- @angular-devkit/core@8.3.25  deduped
| +-- @schematics/angular@8.3.25
| | `-- @angular-devkit/core@8.3.25  deduped
| `-- @schematics/update@0.803.25
|   +-- @angular-devkit/core@8.3.25
|   `-- @angular-devkit/schematics@8.3.25
|     `-- @angular-devkit/core@8.3.25  deduped
`-- @angular/pwa@0.803.25
  +-- @angular-devkit/core@8.3.25
  `-- @schematics/angular@8.3.25
    `-- @angular-devkit/core@8.3.25  deduped
</code></pre>

**Comment by filipesilva** [comment]
Can you show me the dependencies and devDependencies in your package.json please?

**Comment by Toso82** [comment]
```json
"dependencies": {
    "@angular-devkit/schematics": "^8.3.25",
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/cli": "^8.3.25",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/material-moment-adapter": "^8.2.3",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/pwa": "^0.803.25",
    "@angular/router": "^8.2.14",
    "@angular/service-worker": "^8.2.14",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-free": "^5.12.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.27",
    "@fortawesome/free-regular-svg-icons": "^5.12.1",
    "@fortawesome/free-solid-svg-icons": "^5.12.1",
    "@geoman-io/leaflet-geoman-free": "^2.3.0",
    "@ng-select/ng-select": "^3.7.2",
    "@progress/kendo-angular-common": "^1.2.1",
    "@progress/kendo-angular-pdf-export": "^2.0.2",
    "@progress/kendo-drawing": "^1.6.0",
    "@types/jspdf": "^1.3.3",
    "algebra.js": "^0.2.6",
    "bootstrap": "^4.4.1",
    "core-js": "^3.6.4",
    "datatables.net-dt": "^1.10.20",
    "datatables.net-responsive-dt": "^2.2.3",
    "default-passive-events": "^1.0.10",
    "document-register-element": "^1.14.3",
    "file-saver": "^2.0.2",
    "hammerjs": "^2.0.8",
    "html2canvas": "^1.0.0-rc.5",
    "html2pdf": "0.0.11",
    "imagesloaded": "^4.1.4",
    "imask": "^5.2.1",
    "jquery": "^3.4.1",
    "jquery-ui": "^1.12.1",
    "jspdf": "^1.5.3",
    "leaflet": "^1.6.0",
    "lity": "^2.4.0",
    "mathjs": "^6.6.0",
    "ml-matrix": "^6.4.1",
    "moment": "^2.24.0",
    "n2words": "^1.3.1",
    "node-sass": "^4.13.1",
    "owl.carousel": "^2.3.4",
    "popper.js": "^1.16.1",
    "qrcode": "^1.4.4",
    "rxjs": "^6.5.4",
    "select2": "^3.5.1",
    "uuid": "^3.4.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.25",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@types/file-saver": "^2.0.1",
    "@types/googlemaps": "^3.39.2",
    "@types/jasmine": "^3.5.3",
    "@types/jasminewd2": "^2.0.8",
    "@types/jquery": "^3.3.32",
    "@types/jqueryui": "^1.12.10",
    "@types/leaflet": "^1.5.8",
    "@types/node": "^12.12.25",
    "@types/proj4": "^2.5.0",
    "@types/uuid": "^3.4.7",
    "codelyzer": "^5.2.1",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "^3.1.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^3.1.0",
    "karma-jasmine-html-reporter": "^1.5.2",
    "protractor": "^6.0.0",
    "rxjs-watcher": "^1.1.3",
    "ts-node": "^8.6.2",
    "tslint": "^5.20.1",
    "typescript": "^3.5.3"
  }
```

**Comment by clydin** [comment]
It appears that the package manager is placing some of the dependencies required by the migrations within `@angular/core` (and potentially `@angular/material) in locations that are not resolvable to these migrations.

As a first step to attempt to remedy the situation, can you try the following:
1) Remove `@angular-devkit/schematics` from the `package.json`
2) Delete the `node_modules` directory and any associated lock files (`package-lock.json` or `yarn.lock`)
3) reinstall (`npm install` or equivalent for your package manager)
4) commit the new lock file and try the update

If this does not work then you may need to temporarily install the latest versions of `@schematics/angular`, `@angular-devkit/core`, and `@angular-devkit/schematics` prior to the update.  And then remove them afterwards. (`npm install -D @schematics/angular`/`npm install -D @angular-devkit/core`/`npm install -D @angular-devkit/schematics`).

**Comment by KingDarBoja** [comment]
Got similar issue but related to `@angular-devkit/schematics`

```console
An unhandled exception occurred: Cannot find module '@angular-devkit/schematics'
```

@clydin suggestion solves this issue.

**Comment by Toso82** [comment]
@clydin  I solve with second solution:

**- Install temporany latest version**

`npm install -D @schematics/angular @angular-devkit/core @angular-devkit/schematics` 

**-  Update angular**

` ng update @angular/cli @angular/core`

**- Remove  package**

`npm uninstall  @angular-devkit/schematics @schematics/angular @angular-devkit/core`

But i don't know what happen cold be something in global installation angular?

**Comment by fredjeck** [comment]
Had the same issue than @KingDarBoja with schematics.
Manually installing the packages and then deleting them as stated by @Toso82  solved my issue

**Comment by elizabethpayllo** [comment]
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\ELI\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\ELI\AppData\Local\Temp\ng-zTY9Wo\angular-errors.log" for further details.

**Comment by firegbn** [comment]
just use   npm update and try again

**Comment by SangeethaC-PEC** [comment]
> just use npm update and try again

got solved thanks @firegbn

**Comment by Nikhilbansal777** [comment]
i didnt got the solution @firegbn please tell me the correct solution

**Comment by Nikhilbansal777** [comment]
its comming after ng serve --o

**Comment by gmcfarlane** [comment]
Had this issue today after doing an update.  Solution suggested by Toso82 worked.TY.

**Comment by ProgrammerRomero** [comment]
I had this issue:
Error: Cannot find module '@angular-devkit/build-angular/package.json'
Just typing:

npm cache clean --force

npm install

It works.

**Comment by poonam-byte** [comment]
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\admin\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\admin\AppData\Local\Temp\ng-d6DRYF\angular-errors.log" for further details.

E:\angular_project\app1>ng serve --open

**Comment by samipjain** [comment]
I am also having this same problem as I started following Get Started guide from angular.io

**Comment by parikshit223933** [comment]
I have found a solution after 4 hours of brainstorming research on this issue.
Node Package Manager does not install **devDependencies**, whenever you run `npm install`. Rather what it does is that it installs all the **dependencies**. So you just have to copy the contents of **DevDependencies** to **Dependencies** in **package.json**, which will force the manager to install those libraries. After copying all the DevDependencies to Dependencies, just run the command `npm install`, then proceed with `ng serve` and BOOM its up and running!!!
I hope it helps.
Thank you 😄

**Comment by wagimalick** [comment]
issue solved TY toso82 unistalling and updating pakage did the trick for me

**Comment by srnaik** [comment]
@firegbn : **npm update** saved my day. Thank you!

**Comment by MohamedA-M-Hassan** [comment]
In my case 2 commands helped:

`npm install --save-dev @angular-devkit/build-angular`

`npm install --save-dev @angular-devkit/core`

**Comment by quizdeveloper** [comment]
You can run the command below

`npm install --save-dev @angular-devkit/build-angular `

OR check other answers from [an unhandled exception occurred: cannot find module '@angular-devkit/build-angular/package.json'](https://quizdeveloper.com/faq/resolved-an-unhandled-exception-occurred-cannot-find-module-angular-devkitbuild-angularpackagedotjson-aid62)

**Comment by CodeRegimeTechnologies** [comment]
An unhandled exception occurred: Cannot find module 'typescript'
Require stack:
- C:\Users\demo\light-bootstrap-dashboard-angular2-master\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\commands\serve-impl.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\demo\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\demo\AppData\Local\Temp\ng-TU4Mm9\angular-errors.log" for further details.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by MrCroft** [comment]
Just got the same issue, upgrading from version **10.0.8** to latest **11.0.2**
@clydin 's solution worked (the second one: `npm install --save-dev @schematics/angular @angular-devkit/core @angular-devkit/schematics`, then doing the `ng update @angular/cli @angular/core`, and then uninstalling those 3 above)

And now I get more files updated by the migration (in my case: all the spec files and the main/root routing config - it adds `relativeLinkResolution: 'legacy'`).
Before, with the error, it was only updating tsconfig files of apps and libs and the angular.json file
