### ISSUE TITLE
angular 9: '__importDefault is not defined' error if aot is not explicitly on

### ISSUE THREAD

**Issue by brunojcm** [angular/angular-cli#16877]
# 🐞 bug report

### Affected Package

```
"@angular/cli": "^9.0.1"
"@angular/compiler": "^9.0.0"
"@angular/core": "^9.0.0"
```

### Is this a regression?

Yes (maybe not if Ivy won't support that)

### Description

I have an angular workspace with multiple apps, and after updating to Angular 9 (I started trying with rc.11, same behaviour since then) 2 of those apps were having the following problem right after opening then in the browser: `Uncaught ReferenceError: __importDefault is not defined`

Configuration file was as below:
```
        "one-plan-dashboard-app": {
            "projectType": "application",
            "schematics": {
                "@schematics/angular:component": {
                    "style": "scss"
                }
            },
            "root": "projects/one-plan-dashboard-app",
            "sourceRoot": "projects/one-plan-dashboard-app/src",
            "prefix": "dash-op",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        "outputPath": "dist/one-plan-dashboard-app",
                        "index": "projects/one-plan-dashboard-app/src/index.html",
                        "main": "projects/one-plan-dashboard-app/src/main.ts",
                        "polyfills": "projects/one-plan-dashboard-app/src/polyfills.ts",
                        "tsConfig": "projects/one-plan-dashboard-app/tsconfig.app.json",
                        "aot": false,
                        "assets": [
                            "projects/one-plan-dashboard-app/src/favicon.ico",
                            "projects/one-plan-dashboard-app/src/web.config",
                            "projects/one-plan-dashboard-app/src/assets"
                        ],
                        "styles": [
                            "projects/one-plan-dashboard-app/src/styles.scss"
                        ],
                        "scripts": []
                    },
                    ...
                },
                ...
            }
        },
```

Same error happens removing `"aot": false`, but having it as `"aot": true` does not trigger the issue.

## 🔬 Minimal Reproduction

EDIT: Please see https://github.com/angular/angular/issues/35208#issuecomment-583259763, it seems to be very hard to find a sequence of steps that reproduce the bug, if possible at all.

I compared a new workspace with mine and realised that `"aot": true` prevents the issue, but still could not reproduce the issue in an new workspace and changing `"aot": false`. I'm still working on that as it seems that something else is needed to trigger the problem.

## 🔥 Exception or Error
<pre><code>
app.component.ts:7 Uncaught ReferenceError: __importDefault is not defined
    at Module../src/app/app.component.ts (app.component.ts:7)
    at __webpack_require__ (bootstrap:79)
    at Module../src/app/app.module.ts (app.component.ts:10)
    at __webpack_require__ (bootstrap:79)
    at Module../src/main.ts (environment.ts:19)
    at __webpack_require__ (bootstrap:79)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:79)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 12.15.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.20
@angular-devkit/build-angular      0.803.20
@angular-devkit/build-ng-packagr   0.803.20
@angular-devkit/build-optimizer    0.803.20
@angular-devkit/build-webpack      0.803.20
@angular-devkit/core               8.3.20
@angular-devkit/schematics         9.0.1
@angular/cli                       9.0.1
@ngtools/webpack                   8.3.20
@schematics/angular                9.0.1
@schematics/update                 0.900.1
ng-packagr                         5.7.1
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.39.2
</code></pre>

**Node version:**
<pre><code>
node --version
v12.15.0
</code></pre>

**OS:**
Windows 10 Enterprise

**Comment by clydin** [comment]
It appears that the broken builds where due to the manual package updates which doesn't allow the migrations to execute.  This also appears to have been corrected though by manually executing the necessary migrations.

The remaining item would be the freezing during update bootstrapping.  Any additional information regarding the circumstances would be helpful.  Did this happen with 9.0 final or one of the prerelease versions?  Is it consistently reproducible on your machine?  Or any other information that may seem relevant.

**Comment by brunojcm** [comment]
Thanks everyone for the attention to the problem, I really appreciate it.

> @brunojcm we are looking are more `ng update` improvements for v10. Some of them focus on recovering from bad states, like you are suggesting.

Just clarifying one thing, in the end my suggestion was just an improvement in the message when bootstrapping is necessary, in case it fails, not necessarily any inconsistent state recovery. It would be nice to have, though, good to hear you are working on that for v10. 

> The remaining item would be the freezing during update bootstrapping. Any additional information regarding the circumstances would be helpful. Did this happen with 9.0 final or one of the prerelease versions?

I started testing on rc.12, but my last try was with CLI 9.0.1 a few hours ago. Bootstrapping process froze in all my tries. 

> Is it consistently reproducible on your machine? Or any other information that may seem relevant.

Yes, it happened almost tens of times. I can easily reset my git to a revision before the update and run it again with any debug flags you may find useful, if you think it's worth porsuing that. Just let me know what should I run. Only problem is that I live in Australia, so the week is gone (I will be out for the weekend), so I'll only be able to test on Monday.

**Comment by brunojcm** [comment]
Ready to run anything here, if you need/want, just let me know what.

**Comment by brunojcm** [comment]
I've been upgrading some other projects to Angular 9 recently, everything worked fine when de CLI is updated properly. Despite getting a few upvotes [here](https://stackoverflow.com/a/60108710/187148) (which means some people are having similar problems), I don't think there is something broken with Angular. As I'm the reporter, and also won't have time to create a repro in the only computer I'm experiencing this problem, I'm closing this issue.

If any maintainer disagree, please re-open it and let me know how I can help.
