### ISSUE TITLE
Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular-cli#16873]
# 🐞 Bug report
This is probably a feature and not a bug. But I can't find any useful information on how to fix it. I get no relevant hits on the error message itself, so I guess it's fairly new ur really uncommon. 

### Command (mark with an `x`)

- [x] build

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.0-rc.7

### Description

 A clear and concise description of the problem...
I'm building my app with Webpack and AngularCompilerPlugin. After compilation is done and I load the URL where the app is served I'm met with blank page the the following error:
```
Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

I've been using this code since Angular 5 or 6. So I have never been forced to understand what it actually does. Since I'm building with AngularCompilerPlugin it is to my understanding AOT and not JIT. So what does "Consider AOT mode instead." mean in this case?

## 🔬 Minimal Reproduction
Since this is not an open source project it would take a lot of time to create a repro. I will gladly do this if it cannot be solved any other way. Just let me know.

**main.ts**
```
platformBrowserDynamic().bootstrapModule(AppModule)
    .then(module => {
        if (!environment.production) {
            const applicationRef = module.injector.get(ApplicationRef);
            const appComponent = applicationRef.components[0];
            enableDebugTools(appComponent);
        }
    })
    .catch(err => console.error(err));
```

**webpack.config.ts**
```
new AngularCompilerPlugin({
    tsConfigPath: helpers.rootPath('tsconfig.build.json'),
    mainPath: helpers.rootPath('src/main.ts'),
    sourceMap: true
}),
```
## 🔥 Exception or Error
<pre><code>
angular.js:24565 Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (angular.js:24565)
    at Function.get (angular.js:49779)
    at registerNgModuleType (angular.js:48055)
    at angular.js:48066
    at Array.forEach (<anonymous>)
    at registerNgModuleType (angular.js:48066)
    at new NgModuleFactory (angular.js:48173)
    at compileNgModuleFactory__POST_R3__ (angular.js:51698)
    at PlatformRef.push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.PlatformRef.bootstrapModule (angular.js:51921)
    at eval (main.ts:19)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.14.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/http                     8.0.0-beta.10
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.5
</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
I believe this error is a symptom that the Angular decorators (e.g. `@Component` etc) were not removed from the source code by the AOT compilation correctly...

This could be in your application source - or perhaps an ngcc failure in one of your dependencies?

Can you build the app and look in the generated output to see if that is the case?

**Comment by JonWallsten** [comment]
@petebacondarwin: I'll check. Give me a few minutes.

**Comment by JonWallsten** [comment]
@petebacondarwin: I'll fix that repro.

**Comment by petebacondarwin** [comment]
If you could make a self-standing repro then I can look into it.

**Comment by JonWallsten** [comment]
> If you could make a self-standing repro then I can look into it.

I couldn't reproduce it myself in the skeleton-repo I've made before. The only big difference between that one and our current is that I've created an internal lib with ng-packagr. Is there something I would have to do in the ng-packagr settings to make it work?

**Comment by petebacondarwin** [comment]
Does this internal lib have secondary entry-points? Is it related to  #35188?

**Comment by JonWallsten** [comment]
@petebacondarwin Not that I know of. And I just updated our skeleton-repo to also include building the lib. It still works. So it's some other dependency causing this.
Probably related to https://github.com/angular/angular/issues/35045.

But how do I figure out which one? I'm prepared to do the digging. But what am I looking for?

**Comment by JonWallsten** [comment]
I think I get it now:
`"ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"` 
needs to be 
`"ngcc --properties es5 browser module main --first-only --create-ivy-entry-points"`

After I did that I got bit further down the line. Now it stopped on:
![image](https://user-images.githubusercontent.com/5993909/74034002-a9830400-49b7-11ea-995a-64f26942d209.png)

And when I check there's no `divider.js` or `divider.js.map` in the `fesm5` folder. But there is one in the `fesm2015` folder. So it looks like the ngcc just skipped it.

**Comment by petebacondarwin** [comment]
Can you try including both `es2015` and `es5`?
I suspect that you have some packages that only have one or the other. So by not including them both, you end up with at least one unprocessed package.

**Comment by petebacondarwin** [comment]
Actually I'll try...

**Comment by JonWallsten** [comment]
> Can you try including both `es2015` and `es5`?
> I suspect that you have some packages that only have one or the other. So by not including them both, you end up with at least one unprocessed package.

I did run them one after the other, so they should both be there. I just got home. But I'll answer any questions you have about the repro incase you get into any trouble. It's a bit complex setup due to legacy stuff.

**Comment by JonWallsten** [comment]
`@petebacondarwin: The error goes away when I remove `@oas/web-lib-angular` from the imports in app.component.ts. So I guess it has something to do with ng-packagr and my internal lib.

**Comment by petebacondarwin** [comment]
I am struggling even to get the initial build to complete. :-(

**Comment by JonWallsten** [comment]
> I am struggling even to get the initial build to complete. :-(

Whats the error? I'll help put.

**Comment by petebacondarwin** [comment]
> Note: You will get an error because web-app-edit is compiling at the same time as web-lib-angular. To fix this just change anything in app.component.ts after initial compiling is done. You'll understand when you see the error.

This bit :-)

**Comment by petebacondarwin** [comment]
Even when I modify `app.component.ts` I still get:

```
 | ERROR in packages/web-app-edit/src/app/app.module.ts
 | Module not found: Error: Can't resolve '@oas/web-lib-angular' in '/Users/pete/dev/angular/tmp/monorepo-new/packages/web-app-edit/src/app'
 |  @ packages/web-app-edit/src/app/app.module.ts 13:24-55
 |  @ packages/web-app-edit/src/main.ts
 |  @ multi (webpack)-dev-server/client?http://localhost:3060 packages/web-app-edit/(webpack)/hot/dev-server.js ./src/main.ts
 | 
 | ERROR in packages/web-app-edit/src/app/app.component.ts
 | Module not found: Error: Can't resolve '@oas/web-lib-angular' in '/Users/pete/dev/angular/tmp/monorepo-new/packages/web-app-edit/src/app'
 |  @ packages/web-app-edit/src/app/app.component.ts 10:24-55
 |  @ packages/web-app-edit/src/app/app.module.ts
 |  @ packages/web-app-edit/src/main.ts
 |  @ multi (webpack)-dev-server/client?http://localhost:3060 packages/web-app-edit/(webpack)/hot/dev-server.js ./src/main.ts
```

**Comment by JonWallsten** [comment]
> > Note: You will get an error because web-app-edit is compiling at the same time as web-lib-angular. To fix this just change anything in app.component.ts after initial compiling is done. You'll understand when you see the error.
> 
> This bit :-)

Just add `const test = 1;` in `packages/web-app-edit/src/app/app.component.ts` and save. Then remove it as save again.

**Comment by petebacondarwin** [comment]
OK that works!

**Comment by petebacondarwin** [comment]
This is very complex setup :-) I think ... that these subproject are built with ivy turned on, right? If so it might be worth compiling then with ivy disabled and then ngcc can do its thing. We don't really support external packages that are built directly with ivy yet. For sure ngcc is not doing anything to the `web-lib-angular` project. Also I wonder if you could try moving all the `dist` folders out from under their respective `projects` folders? It might be that the `package.json` that is one level up from each `dist` folder affects things?

**Comment by JonWallsten** [comment]
> This is very complex setup :-) I think ... that these subproject are built with ivy turned on, right? If so it might be worth compiling then with ivy disabled and then ngcc can do its thing. We don't really support external packages that are built directly with ivy yet. For sure ngcc is not doing anything to the `web-lib-angular` project. Also I wonder if you could try moving all the `dist` folders out from under their respective `projects` folders? It might be that the `package.json` that is one level up from each `dist` folder affects things?

I can try to compile web-lib-angular without ivy. But since I have multiple apps using it I would have a risk of conflict when these apps would try compile it at the same time, right?

I could try that, but it complicates stuff with our CI. I'll take a look tomorrow. 

Here's the result from turning of IVY for the lib in question:
```
ERROR: C:/Users/jway52/repo/monorepo-new/packages/web-lib-angular/src/services/debug.service.ts:3:1: Error encountered in metadata generated for exported symbol 'DebugService':
 C:/Users/jway52/repo/monorepo-new/packages/web-lib-angular/src/services/debug.service.ts:14:24: Metadata collected contains an error that will be reported at runtime: Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler.
  {"__symbolic":"error","message":"Variable not initialized","line":13,"character":23}
```

**Comment by petebacondarwin** [comment]
I note that the webpack copy of `app.module.ts` does not appear to have been AOT compiled:

```
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = __webpack_require__(/*! tslib */ "../../node_modules/tslib/tslib.es6.js");
var core_1 = __webpack_require__(/*! @angular/core */ "../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js");
var platform_browser_1 = __webpack_require__(/*! @angular/platform-browser */ "../../node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/platform-browser.js");
var router_1 = __webpack_require__(/*! @angular/router */ "../../node_modules/@angular/router/__ivy_ngcc__/fesm5/router.js");
var forms_1 = __webpack_require__(/*! @angular/forms */ "../../node_modules/@angular/forms/__ivy_ngcc__/fesm5/forms.js");
var animations_1 = __webpack_require__(/*! @angular/platform-browser/animations */ "../../node_modules/@angular/platform-browser/__ivy_ngcc__/fesm5/animations.js");
var angular_fontawesome_1 = __webpack_require__(/*! @fortawesome/angular-fontawesome */ "../../node_modules/@fortawesome/angular-fontawesome/__ivy_ngcc__/fesm5/angular-fontawesome.js");
var free_solid_svg_icons_1 = __webpack_require__(/*! @fortawesome/free-solid-svg-icons */ "../../node_modules/@fortawesome/free-solid-svg-icons/index.es.js");
var app_routes_1 = __webpack_require__(/*! ./app.routes */ "./src/app/app.routes.ts");
var app_component_1 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var web_lib_angular_1 = __webpack_require__(/*! @oas/web-lib-angular */ "../web-lib-angular/dist/fesm5/oas-web-lib-angular.js");
var http_1 = __webpack_require__(/*! @angular/common/http */ "../../node_modules/@angular/common/__ivy_ngcc__/fesm5/http.js");
var start_component_1 = __webpack_require__(/*! ./components/start/start.component */ "./src/app/components/start/start.component.ts");
var AppModule = /** @class */ (function () {
    function AppModule(library) {
        library.addIcons(free_solid_svg_icons_1.faCog);
        library.addIcons(free_solid_svg_icons_1.faSearch);
        library.addIcons(free_solid_svg_icons_1.faTimes);
        library.addIcons(free_solid_svg_icons_1.faBars);
    }
    AppModule = tslib_1.__decorate([
        core_1.NgModule({
            imports: [
                router_1.RouterModule.forRoot(app_routes_1.appRoutes, {
                    enableTracing: false,
                    useHash: true
                }),
                forms_1.FormsModule,
                forms_1.ReactiveFormsModule,
                animations_1.BrowserAnimationsModule,
                platform_browser_1.BrowserModule,
                angular_fontawesome_1.FontAwesomeModule,
                http_1.HttpClientModule,
                web_lib_angular_1.WebLibAngularModule,
                web_lib_angular_1.MaterialDesignModule
            ],
            declarations: [
                app_component_1.AppComponent,
                start_component_1.StartComponent
            ],
            providers: [
                web_lib_angular_1.DialogService
            ],
            bootstrap: [app_component_1.AppComponent]
        }),
        tslib_1.__metadata("design:paramtypes", [angular_fontawesome_1.FaIconLibrary])
    ], AppModule);
    return AppModule;
}());
exports.AppModule = AppModule;
```

I am not sure why this is...

**Comment by JonWallsten** [comment]
How is that possible? I thought the AngularCompilerPlugin did this automatically?

**Comment by petebacondarwin** [comment]
Yeah that is confusing me...

**Comment by petebacondarwin** [comment]
I'm going to ask @alxhub to take a look. Are you able to give him access to the repo?

**Comment by JonWallsten** [comment]
He should already have access. He's looked at it before when I had trouble compiling the repo because web-lib-angular wasn't packages by ng-packagr.

**Comment by petebacondarwin** [comment]
Cool. I asked because he is not online yet and I will shortly be going offline :-)

**Comment by JonWallsten** [comment]
Great! I got the lib to build without ivy now! Didn't do any differens though. Still issues with
`Uncaught TypeError: Cannot read property 'id' of undefined` in `registerNgModuleType`

**Comment by alxhub** [comment]
@JonWallsten hello again! Firstly, thanks for taking the time to put together the reproduction and work with us to track down the problem.

I don't think this is an issue with Angular, actually. I ran the "build:edit" and "build:prod" tasks, and both seem to produce an Ivy application which works in the browser, no JIT mode needed.

It's only when running the `dev:edit` task (which has a lot of race conditions up front) that the problem shows up. So something is up with the devserver setup that's resulting in the app itself not being compiled with AOT. Unfortunately this build path descends into `build-tools/run-all` which appears to be a custom build system of sorts, and I wasn't able to easily figure out how `webpack` was being invoked or with what configuration.

I think with the given reproduction, we've investigated this as best as we can. The issue is that in dev:edit mode, the build system does not use AOT to compile the `AppModule`, hence the message about the JIT compiler needing to be loaded at runtime. I'm guessing if you look into this, you'll find that the webpack devserver isn't being invoked with the right set of plugins or something. Based on that, I'm going to resolve this issue.

If you still feel like this is an issue with Angular, we'd of course be happy to help investigate. To do this though, we'll need a reproduction without a complex custom build system. Ideally, this would be a shell script (a `build.sh`) that compiles each library, in sequence, and then the main application with a direct `webpack` invocation, where we can clearly see the build steps involved and their inputs and outputs.

**Comment by JonWallsten** [comment]
@alxhub: Thanks for looking into it! 
I just now tested to build edit from the application root instead of the monorepo root and it does indeed work. I never tested that. Was so focused on getting the whole repo to work. 
However, I did the corresponding script for `dev:edit` but with a production build instead of starting the dev server. And this does work as well from the monorepo root. So the `build-tools/run-all` doesn't seem to be the issue here. It basically just runs the same npm script in each package with the package as workign directory. 
My guess is that since all packages builds at the same time in dev-mode (I can't to stages since the watch never finish up), the app is being compiled before the library is packaged with ng-packagr initially. When the package then is complete, and the app notices this and rebuilds, it seems to be to late. 

I did just now test to start each lib with watch on, but one at a time, and then the application last. I also tried to change something in the lib to trigger a rebuild of the app. And this did work as well. So I'm fairly certain the issue is that the app is started before the library is initially packages, and that the app can't figure it out on the next rebuild for some reason.

So I'll have to look at how I can them in stages even though we're in watch mode and the task never technically finishes. 
At least now I know what do to. So thanks again for that. And thanks @petebacondarwin for looking into this as well! I guess this was just one of those days when you tested exactly the one thing that didn't work out of all scenarios that did. Have a great weekend both of you!

**Comment by JonWallsten** [comment]
@alxhub: So, I did the same test on our project just now to make sure it worked the same. Unfortunately I get the same error: 
```
Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
```

Since we have excluded the build tools (at least for the simple test) I guess it has to be content. Do you have any idea of what could cause this, so I know where to investigate? Is there some package/module that isn't compiled into IVY that is the issue?

**Comment by JonWallsten** [comment]
@alxhub / @petebacondarwin: So the weird thing is that the files are actually not generated when compiling the modules. 
It complains about the missing BrowserModuleAnimation. And the file is actually not there:
![image](https://user-images.githubusercontent.com/5993909/74065303-db668b80-49f4-11ea-98a2-0ef42bfeb242.png)
**Compare with fesm2015:**
![image](https://user-images.githubusercontent.com/5993909/74065383-0fda4780-49f5-11ea-8e81-c63d31071a80.png)

**Comment by JonWallsten** [comment]
This time I got really far. Stopped six levels down in the MaterialDesignModule on something called BidiModule:
![image](https://user-images.githubusercontent.com/5993909/74066050-99d6e000-49f6-11ea-8dcc-dcdcda4d66a8.png)

There really seems to be an issue with generating these ivy/ngcc files.

**Comment by alxhub** [comment]
Glad to hear you got it figured out! Parallel building like that is decently tricky!

**Comment by Teknyc** [comment]
@JonWallsten did you end up using as your postinstall script? and also, did you do anything different to your main.ts file? any chance you can write a step by step what you ended up doing to fix this problem?

**Comment by JonWallsten** [comment]
@Teknyc: Yes. I added this:
```
"postinstall": "ngcc --properties es5 browser module main --first-only --create-ivy-entry-points && ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
```
We need both es5 and es2015. Not sure about your needs. The main.ts file can stay the same as before. I the script above doesn't work. 

Make sure you remove the node_modules/@angular folder before installning again. If they are already installed and faulty, they will stay that way.

If it still doesn't work you need to use DevTools (or similar) to understand which module isn't wokring. They easiest way to do this is to set a breakpoint at the actual JIT error and just use the callstack to go up a few levels until you see anything related to a module. It will have the module name.  In my example I wen't to getNgModuleDef and from there I could figure out which modules caused the issue.

**Comment by Teemo-the-troll** [comment]
This also occurs when you import only HttpClient instead of HttpClientModule, but it seems like this isn't the case

**Comment by speedy32** [comment]
In my case I had this kind of problem because someone in project did reference to Injectable like below:
import { Injectable } from '../../../../../../node_modules/@angular/core';

**Comment by genuineyehuo** [comment]
> In my case I had this kind of problem because someone in project did reference to Injectable like below:
> import { Injectable } from '../../../../../../node_modules/@angular/core';

same problem，

**Comment by abhishekssd** [comment]
> # 🐞 Bug report
> This is probably a feature and not a bug. But I can't find any useful information on how to fix it. I get no relevant hits on the error message itself, so I guess it's fairly new ur really uncommon.
> 
> ### Command (mark with an `x`)
> * [x]  build
> 
> ### Is this a regression?
> Yes, the previous version in which this bug was not present was: 9.0.0-rc.7
> ### Description
> A clear and concise description of the problem...
> I'm building my app with Webpack and AngularCompilerPlugin. After compilation is done and I load the URL where the app is served I'm met with blank page the the following error:
> 
> ```
> Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
>   - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
>   - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
>   - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
> ```
> 
> I've been using this code since Angular 5 or 6. So I have never been forced to understand what it actually does. Since I'm building with AngularCompilerPlugin it is to my understanding AOT and not JIT. So what does "Consider AOT mode instead." mean in this case?
> 
> ## 🔬 Minimal Reproduction
> Since this is not an open source project it would take a lot of time to create a repro. I will gladly do this if it cannot be solved any other way. Just let me know.
> 
> **main.ts**
> 
> ```
> platformBrowserDynamic().bootstrapModule(AppModule)
>     .then(module => {
>         if (!environment.production) {
>             const applicationRef = module.injector.get(ApplicationRef);
>             const appComponent = applicationRef.components[0];
>             enableDebugTools(appComponent);
>         }
>     })
>     .catch(err => console.error(err));
> ```
> 
> **webpack.config.ts**
> 
> ```
> new AngularCompilerPlugin({
>     tsConfigPath: helpers.rootPath('tsconfig.build.json'),
>     mainPath: helpers.rootPath('src/main.ts'),
>     sourceMap: true
> }),
> ```
> 
> ## 🔥 Exception or Error
> ```
> 
> angular.js:24565 Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
>   - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
>   - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
>   - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
>     at getCompilerFacade (angular.js:24565)
>     at Function.get (angular.js:49779)
>     at registerNgModuleType (angular.js:48055)
>     at angular.js:48066
>     at Array.forEach ()
>     at registerNgModuleType (angular.js:48066)
>     at new NgModuleFactory (angular.js:48173)
>     at compileNgModuleFactory__POST_R3__ (angular.js:51698)
>     at PlatformRef.push.../../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.PlatformRef.bootstrapModule (angular.js:51921)
>     at eval (main.ts:19)
> ```
> 
> ## 🌍 Your Environment
> ```
> 
> Angular CLI: 9.0.1
> Node: 12.14.0
> OS: win32 x64
> 
> Angular: 9.0.0
> ... animations, cdk, common, compiler, compiler-cli, core, forms
> ... material, platform-browser, platform-browser-dynamic, router
> Ivy Workspace: Yes
> 
> Package                           Version
> -----------------------------------------------------------
> @angular-devkit/architect         0.900.1
> @angular-devkit/build-optimizer   0.900.1
> @angular-devkit/core              9.0.1
> @angular-devkit/schematics        9.0.1
> @angular/cli                      9.0.1
> @angular/http                     8.0.0-beta.10
> @ngtools/webpack                  9.0.1
> @schematics/angular               9.0.1
> @schematics/update                0.900.1
> rxjs                              6.5.4
> typescript                        3.7.5
> webpack                           4.41.5
> ```
> 
> **Anything else relevant?**

HI @JonWallsten i did not get any solution for this issue so far can you help if you found the solution

**Comment by JonWallsten** [comment]
@abhishekssd Yes, you need to use Chrome DevTools to investigate which module it has issue with and then figure out how to fix that. There's no easy what that I know of.

**Comment by petebacondarwin** [comment]
Have you tried running ngcc directly over the whole of node_modules?
 You might get some useful warnings about some of the entry-points. E.g. `ngcc -l debug`

**Comment by JACrazy** [comment]
I'm getting this issue but only after upgrading from angular 9.0.6 to 9.0.7, if I revert the issue goes away.

**Comment by submarines-and** [comment]
Same here, no other changes made.

**Comment by abdelrahman-haridy01** [comment]
Turn off the AOT by changing "aot": true to "aot: false in angular.json file.

**Comment by ezalivadnyi** [comment]
In my case I've just reload application and all works.

**Comment by Frotty** [comment]
> In my case I've just reload application and all works.

Thanks. Indeed by AOT being default with angular 9, you cannot change dependencies while serving.

**Comment by sampath0606** [comment]
I am facing the the following issues when i try to do 'ng serve' after upgrading to 9.0.7.

NG8001: 'mat-select' is not a known element:
1. If 'mat-select' is an Angular component and it has 'disabled' input, then verify that it is part of this module.
2. If 'mat-select' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.


error NG8001: 'mat-form-field' is not a known element:
1. If 'mat-form-field' is an Angular component, then verify that it is part of this module.
2. If 'mat-form-field' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

 error NG8002: Can't bind to 'ngModel' since it isn't a known property of 'input'.
<input matInput #input class="form-control" placeholder="XXX" [(ngModel)]="XX.yy"

If i update aot:false ng serve is working fine , but on building for prod i', again facing the above mentioned issues.

Everything was working completely fine with 9.0.6. Could some body help me out?

My Package File:

{
  "name": "nol-ui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.7",
    "@angular/cdk": "~9.2.0",
    "@angular/common": "~9.0.7",
    "@angular/compiler": "~9.0.7",
    "@angular/core": "~9.0.7",
    "@angular/forms": "~9.0.7",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "~9.0.7",
    "@angular/platform-browser-dynamic": "~9.0.7",
    "@angular/router": "~9.0.7",
    "classlist.js": "^1.1.20150312",
    "handlebars": "^4.7.3",
    "kind-of": "^6.0.3",
    "lodash": "^4.17.15",
    "rxjs": "~6.5.4",
    "serialize-javascript": "^2.1.2",
    "tree-kill": "^1.2.2",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.7",
    "@angular/cli": "~9.0.7",
    "@angular/compiler-cli": "~9.0.7",
    "@angular/language-service": "~9.0.7",
    "@types/jasmine": "^3.3.16",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^12.12.34",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.6",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "^5.4.3",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }
}

**Comment by JACrazy** [comment]
Anyone with this issue after 9.0.7 see this thread https://github.com/angular/angular/issues/35788#issuecomment-606455043

There's a workaround fix commented, but they also said they'll look into having an update probably next week that will help support packages with ESM5 format.
