### ISSUE TITLE
Could not create new project "ng new"

### ISSUE THREAD

**Issue by ragavanrandy** [angular/angular-cli#16876]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 create new project using angular cli 8.3.9

## 🔬 Minimal Reproduction
1. ng new test 2. npm install

## 🔥 Exception or Error
<pre><code>
1. ng new test

E:\Projects\angular\others>ng new test
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
 ]
CREATE test/angular.json (3665 bytes)
CREATE test/package.json (1278 bytes)
CREATE test/README.md (1021 bytes)
CREATE test/tsconfig.json (543 bytes)
CREATE test/tslint.json (1953 bytes)
CREATE test/.editorconfig (246 bytes)
CREATE test/.gitignore (631 bytes)
CREATE test/browserslist (429 bytes)
CREATE test/karma.conf.js (1016 bytes)
CREATE test/tsconfig.app.json (270 bytes)
CREATE test/tsconfig.spec.json (270 bytes)
CREATE test/src/favicon.ico (948 bytes)
CREATE test/src/index.html (290 bytes)
CREATE test/src/main.ts (372 bytes)
CREATE test/src/polyfills.ts (2838 bytes)
CREATE test/src/styles.scss (80 bytes)
CREATE test/src/test.ts (642 bytes)
CREATE test/src/assets/.gitkeep (0 bytes)
CREATE test/src/environments/environment.prod.ts (51 bytes)
CREATE test/src/environments/environment.ts (662 bytes)
CREATE test/src/app/app-routing.module.ts (246 bytes)
CREATE test/src/app/app.module.ts (393 bytes)
CREATE test/src/app/app.component.html (25530 bytes)
CREATE test/src/app/app.component.spec.ts (1092 bytes)
CREATE test/src/app/app.component.ts (209 bytes)
CREATE test/src/app/app.component.scss (0 bytes)
CREATE test/e2e/protractor.conf.js (810 bytes)
CREATE test/e2e/tsconfig.json (214 bytes)
CREATE test/e2e/src/app.e2e-spec.ts (637 bytes)
CREATE test/e2e/src/app.po.ts (262 bytes)
npm ERR! Unexpected end of JSON input while parsing near '...8d55f807e799df128af91'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2020-02-07T14_22_30_242Z-debug.log
Package install failed, see above.

2. npm install

E:\Projects\angular\others\test>npm install
npm ERR! Unexpected end of JSON input while parsing near '...eafac5a8658ca2d5d9b95'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2020-02-07T14_29_20_942Z-debug.log
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 8.3.9
Node: 10.16.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.9
@angular-devkit/core         8.3.9
@angular-devkit/schematics   8.3.9
@schematics/angular          8.3.9
@schematics/update           0.803.9
rxjs                         6.4.0
</code></pre>

**Anything else relevant?**

**Comment by filipesilva** [comment]
@ragavanrandy not really sure what's happening, but can you try using the latest CLI version please? That would be 9.0.1.

**Comment by clydin** [comment]
This also appears to be an npm error.  If this is still reproducible with the latest CLI, can you provide the contents of the npm error log file mentioned in the console?

**Comment by ragavanrandy** [comment]
@filipesilva , i have updated to latest CLI (9.0.0). still errors are exist. 'ng new' setup projects files only and throw error as follows:

`E:\Projects\angular\others>ng new test
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
 ]
CREATE test/angular.json (3639 bytes)
CREATE test/package.json (1281 bytes)
CREATE test/README.md (1021 bytes)
CREATE test/tsconfig.json (543 bytes)
CREATE test/tslint.json (1953 bytes)
CREATE test/.editorconfig (246 bytes)
CREATE test/.gitignore (631 bytes)
CREATE test/browserslist (429 bytes)
CREATE test/karma.conf.js (1016 bytes)
CREATE test/tsconfig.app.json (210 bytes)
CREATE test/tsconfig.spec.json (270 bytes)
CREATE test/src/favicon.ico (948 bytes)
CREATE test/src/index.html (290 bytes)
CREATE test/src/main.ts (372 bytes)
CREATE test/src/polyfills.ts (2838 bytes)
CREATE test/src/styles.scss (80 bytes)
CREATE test/src/test.ts (753 bytes)
CREATE test/src/assets/.gitkeep (0 bytes)
CREATE test/src/environments/environment.prod.ts (51 bytes)
CREATE test/src/environments/environment.ts (662 bytes)
CREATE test/src/app/app-routing.module.ts (246 bytes)
CREATE test/src/app/app.module.ts (393 bytes)
CREATE test/src/app/app.component.html (25705 bytes)
CREATE test/src/app/app.component.spec.ts (1053 bytes)
CREATE test/src/app/app.component.ts (209 bytes)
CREATE test/src/app/app.component.scss (0 bytes)
CREATE test/e2e/protractor.conf.js (808 bytes)
CREATE test/e2e/tsconfig.json (214 bytes)
CREATE test/e2e/src/app.e2e-spec.ts (637 bytes)
CREATE test/e2e/src/app.po.ts (301 bytes)
\ Installing packages...npm ERR! Unexpected end of JSON input while parsing near '...BAEBCAAQBQJcgEZwCRA9T'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2020-02-10T06_31_20_886Z-debug.log
× Package install failed, see above.`

and the content of log file is,

[2020-02-10T06_31_20_886Z-debug.log](https://github.com/angular/angular-cli/files/4179300/2020-02-10T06_31_20_886Z-debug.log)

**Comment by ragavanrandy** [comment]
Also tried in following environment:

```
Angular CLI: 9.0.0
Node: 12.15.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0
@angular-devkit/core         9.0.0
@angular-devkit/schematics   9.0.0
@schematics/angular          9.0.0
@schematics/update           0.900.0
rxjs                         6.5.3
```

Even though, i got errors as follows:

```
E:\Projects\angular\others>ng new test-pr
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
 ]
CREATE test-pr/angular.json (3663 bytes)
CREATE test-pr/package.json (1284 bytes)
CREATE test-pr/README.md (1023 bytes)
CREATE test-pr/tsconfig.json (543 bytes)
CREATE test-pr/tslint.json (1953 bytes)
CREATE test-pr/.editorconfig (246 bytes)
CREATE test-pr/.gitignore (631 bytes)
CREATE test-pr/browserslist (429 bytes)
CREATE test-pr/karma.conf.js (1019 bytes)
CREATE test-pr/tsconfig.app.json (210 bytes)
CREATE test-pr/tsconfig.spec.json (270 bytes)
CREATE test-pr/src/favicon.ico (948 bytes)
CREATE test-pr/src/index.html (292 bytes)
CREATE test-pr/src/main.ts (372 bytes)
CREATE test-pr/src/polyfills.ts (2838 bytes)
CREATE test-pr/src/styles.scss (80 bytes)
CREATE test-pr/src/test.ts (753 bytes)
CREATE test-pr/src/assets/.gitkeep (0 bytes)
CREATE test-pr/src/environments/environment.prod.ts (51 bytes)
CREATE test-pr/src/environments/environment.ts (662 bytes)
CREATE test-pr/src/app/app-routing.module.ts (246 bytes)
CREATE test-pr/src/app/app.module.ts (393 bytes)
CREATE test-pr/src/app/app.component.html (25705 bytes)
CREATE test-pr/src/app/app.component.spec.ts (1062 bytes)
CREATE test-pr/src/app/app.component.ts (212 bytes)
CREATE test-pr/src/app/app.component.scss (0 bytes)
CREATE test-pr/e2e/protractor.conf.js (808 bytes)
CREATE test-pr/e2e/tsconfig.json (214 bytes)
CREATE test-pr/e2e/src/app.e2e-spec.ts (640 bytes)
CREATE test-pr/e2e/src/app.po.ts (301 bytes)
| Installing packages...npm ERR! Unexpected end of JSON input while parsing near '...0"},"devDependencies"'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user1\AppData\Roaming\npm-cache\_logs\2020-02-10T11_46_31_298Z-debug.log

× Package install failed, see above.
The Schematic workflow failed. See above.
```
the log file,

[2020-02-10T11_46_31_298Z-debug.log](https://github.com/angular/angular-cli/files/4180597/2020-02-10T11_46_31_298Z-debug.log)

**Comment by filipesilva** [comment]
@ragavanrandy are you using a npm proxy or something of the sort? I'm not really sure what we can do here, this is a npm error and not something we have direct control over.

You can try going into the created folder and running `npm install` there but I imagine the result is the same. Maybe it's a bug with your version of npm.

**Comment by alan-agius4** [comment]
Closing as no further information was provided.

If the problem persist please file a new issue. Thanks

**Comment by ricoom** [comment]
i'm having the same problem now i have tried to reinstall npm in vein

**Comment by ricoom** [comment]
![image](https://user-images.githubusercontent.com/47127588/78829675-74168900-79ef-11ea-8ebe-594000bcc39d.png)
