### ISSUE TITLE
CLI command to list all routes

### ISSUE THREAD

**Issue by MintPlayer** [angular/angular-cli#16874]
# 🚀 Feature request

### Command (mark with an `x`)

New command

### Description
 A clear and concise description of the problem or missing capability...
I feel the need to list all routes through a CLI command

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
`ng route list --depth=3`

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Manually go through all my modules to see if there is somehow a mismatch in a route, causing the wrong angular component to be rendered.

**Comment by mgechev** [comment]
@MintPlayer I'd suggest to keep this outside of the CLI's scope. For the purpose you can already use the [`guess-parser`](https://www.npmjs.com/package/guess-parser). You can achieve this with:

```ts
import { parseAngularRoutes } from 'guess-parser';

console.log(parseAngularRoutes('tsconfig.app.json'));
```
