### ISSUE TITLE
Angular CLI 9.0.1 - Universal build is not generating server.js

### ISSUE THREAD

**Issue by seanmcalinden** [angular/angular-cli#16898]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
Yes, the previous version in which this bug was not present was: < 9.0.0

### Description

 A clear and concise description of the problem...

Upon build:ssr - the server.js file is **not** created in the dist folder.
The server and browser directories are built correctly though.

## 🔬 Minimal Reproduction

ng new TestSsrApp --routing --style=scss

cd TestSsrApp 

ng add @nguniversal/express-engine

npm run build:ssr

Once this has completed the browser and server directories have been created however with no server.js.

I've done this a few times now and always the same result.

The app itself works locally when running commands such as npm run dev:ssr so it looks like just the server.js not being created is the issue.

You can read more about issue submission guidelines here: https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue
-->

## 🔥 Exception or Error
There are no errors shown

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.1
Node: 10.16.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.1
@angular-devkit/core         9.0.1
@angular-devkit/schematics   9.0.1
@schematics/angular          9.0.1
@schematics/update           0.900.1
rxjs    
</code></pre>

This is the generated package file :

<pre><code>
{
  "name": "test-ssr-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run TestSsrApp:serve-ssr",
    "serve:ssr": "node dist/TestSsrApp/server/main.js",
    "build:ssr": "ng build --prod && ng run TestSsrApp:server:production",
    "prerender": "ng run TestSsrApp:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/platform-server": "~9.0.0",
    "@angular/router": "~9.0.0",
    "@nguniversal/express-engine": "^9.0.0",
    "express": "^4.15.2",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "~9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@nguniversal/builders": "^9.0.0",
    "@types/express": "^4.17.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }
}

</code>
</pre>

**Comment by alan-agius4** [comment]
Hi, the server bundle is named `main.js` and is located under the server folder.

**Comment by seanmcalinden** [comment]
hi Alan,
I know the main.js is there as it was before, just previous to v.9 it also generated the server.js - has this been deprecated?
Cheers,
Sean.

**Comment by seanmcalinden** [comment]
ah I see the issue - on the angular website (https://angular.io/guide/universal) there is an example project (https://angular.io/generated/zips/universal/universal.zip) which is out of date but looking at, there is an extra config file that generates the server.js so it's not part of the CLI.

**Comment by alan-agius4** [comment]
The demo applicate seems to be out of date. I opened an issue here: https://github.com/angular/angular/issues/35289

The `server.js` is no longer needed as the `main.js` file does contain the server code. Thus you can spawn the server using the `main.js` bundle example: `node dist/app/server/main.js `
