### ISSUE TITLE
error ng serve - ERROR in   TypeError: Cannot read property '0' of undefined - Angular RC5, Router v3.0.0-rc.1

### ISSUE THREAD

**Issue by jvbianchi** [angular/angular-cli#1689]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: darwin x6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.

`ERROR in   TypeError: Cannot read property '0' of undefined

  - ExternalModuleFactoryPlugin.js:18 ExternalModuleFactoryPlugin.<anonymous>
    [dolarsoft]/[webpack]/lib/ExternalModuleFactoryPlugin.js:18:38

  - NormalModuleFactory.js:174
    [dolarsoft]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:174:3

  - Tapable.js:123 NormalModuleFactory.applyPluginsAsyncWaterfall
    [dolarsoft]/[tapable]/lib/Tapable.js:123:70

  - NormalModuleFactory.js:158 NormalModuleFactory.create
    [dolarsoft]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:158:8

  - Compilation.js:349 Compilation.process [as _addModuleChain]
    [dolarsoft]/[angular-cli]/[webpack]/lib/Compilation.js:349:16

  - Compilation.js:417 Compilation.process [as addEntry]
    [dolarsoft]/[angular-cli]/[webpack]/lib/Compilation.js:417:7

  - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
    [dolarsoft]/[webpack]/lib/SingleEntryPlugin.js:22:15

  - Tapable.js:156 Compiler.applyPluginsParallel
    [dolarsoft]/[tapable]/lib/Tapable.js:156:14

  - Compiler.js:431 Compiler.compile
    [dolarsoft]/[angular-cli]/[webpack]/lib/Compiler.js:431:7

  - Compiler.js:237 Compiler.runAsChild
    [dolarsoft]/[angular-cli]/[webpack]/lib/Compiler.js:237:7

  - compiler.js:70
    [dolarsoft]/[html-webpack-plugin]/lib/compiler.js:70:19

  - debuggability.js:272 Promise._execute
    [dolarsoft]/[bluebird]/js/release/debuggability.js:272:9

  - promise.js:475 Promise._resolveFromExecutor
    [dolarsoft]/[bluebird]/js/release/promise.js:475:18

  - promise.js:77 new Promise
    [dolarsoft]/[bluebird]/js/release/promise.js:77:14

  - compiler.js:69 Object.compileTemplate
    [dolarsoft]/[html-webpack-plugin]/lib/compiler.js:69:10

  - index.js:47 Compiler.<anonymous>
    [dolarsoft]/[html-webpack-plugin]/index.js:47:40

  - Tapable.js:156 Compiler.applyPluginsParallel
    [dolarsoft]/[tapable]/lib/Tapable.js:156:14

  - Compiler.js:431 Compiler.compile
    [dolarsoft]/[angular-cli]/[webpack]/lib/Compiler.js:431:7

  - Compiler.js:47 Watching.<anonymous>
    [dolarsoft]/[angular-cli]/[webpack]/lib/Compiler.js:47:17

  - Tapable.js:81 next
    [dolarsoft]/[tapable]/lib/Tapable.js:81:11

  - instance.ts:370 Compiler.<anonymous>
    [dolarsoft]/[awesome-typescript-loader]/src/instance.ts:370:13

  - Tapable.js:83 next
    [dolarsoft]/[tapable]/lib/Tapable.js:83:14`

**Comment by jvbianchi** [comment]
problem was solved updating cli, cloning master.

please close this issue

**Comment by LeonardPauli** [comment]
Any details of what caused the issue? Having the same problem but with different setup.
