### ISSUE TITLE
ng update fails when using local dependency

### ISSUE THREAD

**Issue by SergeyCherman** [angular/angular-cli#16897]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes: ng update worked from Angular 6 to 7.

### Description
ng update errors out on a local dependency that is added in my package.json via: "file:./......."
as it trys to get details from npmjs even though is a purely local dependency.

<pre><code>ng update @angular/cli@8 @angular/core@8 </code></pre>

Seems to be related to https://github.com/angular/angular-cli/issues/13059

## 🔥 Exception or Error
<pre><code>404 Not Found - GET https://registry.npmjs.org/DEPENDENCY-NAME - Not found
Cannot read property '1.8.2' of undefined</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 7.3.8
Node: 10.14.0
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.9
@angular-devkit/build-angular      0.13.9
@angular-devkit/build-optimizer    0.13.9
@angular-devkit/build-webpack      0.13.9
@angular-devkit/core               7.3.9
@angular-devkit/schematics         7.3.8
@angular/cdk                       7.3.6
@angular/cli                       7.3.8
@angular/material                  7.3.6
@angular/material-moment-adapter   7.3.6
@ngtools/webpack                   7.3.9
@schematics/angular                7.3.8
@schematics/update                 0.13.8
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0</code></pre>

**Comment by alan-agius4** [comment]
Hi, this should no longer be an issue when updating from version 8 to 9.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
