### ISSUE TITLE
Unable to execute npm run build with angular 8

### ISSUE THREAD

**Issue by johnjosephtigris** [angular/angular-cli#16893]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Unable to execute npm run build

node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod
This version of CLI is only compatible with Angular versions 0.0.0 || ^9.0.0-beta || >=9.0.0 <10.0.0,
but Angular version 8.0.0 was found instead.

Please visit the link below to find instructions on how to update Angular.
https://update.angular.io/

npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! fuse@8.0.0 build: node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the fuse@8.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/sreekanthvr/.npm/_logs/2020-02-09T02_58_55_672Z-debug.log

debug log mentioned below.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.13.4
3 info using node@v12.15.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle fuse@8.0.0prebuild: fuse@8.0.0
6 info lifecycle fuse@8.0.0build: fuse@8.0.0
7 verbose lifecycle fuse@8.0.0build: unsafe-perm in lifecycle true
8 verbose lifecycle fuse@8.0.0build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sreekanthvr/Downloads/MemberManagement/membershipWeb/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/sreekanthvr/Documents/Development/tools/flutter/bin:/Users/sreekanthvr/Documents/Development/tools/flutter/bin
9 verbose lifecycle fuse@8.0.0build: CWD: /Users/sreekanthvr/Downloads/MemberManagement/membershipWeb
10 silly lifecycle fuse@8.0.0build: Args: [
10 silly lifecycle '-c',
10 silly lifecycle 'node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod'
10 silly lifecycle ]
11 silly lifecycle fuse@8.0.0build: Returned: code: 3 signal: null
12 info lifecycle fuse@8.0.0~build: Failed to exec build script
13 verbose stack Error: fuse@8.0.0 build: node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod
13 verbose stack Exit status 3
13 verbose stack at EventEmitter. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:223:5)
13 verbose stack at ChildProcess. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:223:5)
13 verbose stack at maybeClose (internal/child_process.js:1021:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid fuse@8.0.0
15 verbose cwd /Users/sreekanthvr/Downloads/MemberManagement/membershipWeb
16 verbose Darwin 19.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.15.0
19 verbose npm v6.13.4
20 error code ELIFECYCLE
21 error errno 3
22 error fuse@8.0.0 build: node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod
22 error Exit status 3
23 error Failed at the fuse@8.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
As per the error message shown above the cli version that you are using is incompatible with Angular 8

> node --max_old_space_size=6144 ./node_modules/@angular/cli/bin/ng build --prod
This version of CLI is only compatible with Angular versions 0.0.0 || ^9.0.0-beta || >=9.0.0 <10.0.0,
but Angular version 8.0.0 was found instead.

Please visit the link below to find instructions on how to update Angular.
https://update.angular.io/
