### ISSUE TITLE
How to create a module just like app module?

### ISSUE THREAD

**Issue by imbichitra** [angular/angular-cli#16903]
Hi 
i want to  create a module that must contain all thing mentioned below

> admin-layout.component.html
admin-layout.component.css
admin-layout.component.spec.ts
admin-layout.component.ts
admin-layout.module.ts
admin-layout.routing.ts

just like app module.
but when i use below command it just create `admin-layout.module.ts` and `admin-layout.routing.ts`
commad : `ng generate module admin-layout --module app --flat --routing`
so please help me to generate all file mentioned above.

**Comment by sacgrover** [comment]
@imbichitra You can do it  by : ng generate module <name> [options]

For more details : https://angular.io/cli/generate#module

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
