### ISSUE TITLE
How to reference angular2-material (alpha7) with 1.0.0-beta.11-Webpack.2

### ISSUE THREAD

**Issue by kjartanvalur** [angular/angular-cli#1690]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
1.0.0-beta.11-webpack.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
    1. Added packages @angular2-material/core and @angular2-material/slider  version 2.0.0-alpha.7
    2. In app.module.ts
        import { MdCoreModule } from '@angular2-material/core';
        import { MdSliderModule } from '@angular2-material/slider';
imports: [
     ...
    MdCoreModule,
    MdSliderModule
  ],

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ERROR in [default] C:\xxx\node_modules\@angular2-material\core\gestures\MdGestureConfig.d.ts:4:39 
Cannot find name 'HammerManager'.

ERROR in [default] C:\xxx\node_modules\@angular2-material\slider\slider.d.ts:50:19
Cannot find name 'HammerInput'.

ERROR in [default] C:\xxx\node_modules\@angular2-material\slider\slider.d.ts:52:24
Cannot find name 'HammerInput'.

5. Mention any other details that might be useful.
I´m just trying to use the slider component from angular2-material framework

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JSMike** [comment]
see: https://github.com/angular/material2/issues/1049

**Comment by JSMike** [comment]
I'm also having an issue with material icons not appearing, i'm not sure if this is a windows/webpack issue or a material2 issue.

1. OS: Windows 10
2. version: 
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: win32 x64
material2: 2.0.0-alpha.7-2
3. createnew cli project with beta.11-webpack.2  
npm install latest material2 components  
Add MdIcon directive and MdIconRegistry to your component  
Add `<md-icon>menu</md-icon>` to template
You'll see the word "menu" appear instead of the icon.

**Comment by kjartanvalur** [comment]
@JSMike How do you reference HammerJs?

**Comment by JSMike** [comment]
@kjartanvalur you add the code snippet above to your src/main.ts

https://github.com/angular/material2/issues/977#issuecomment-238946558

**Comment by kjartanvalur** [comment]
Yes that code snippet got me through the HammerInput error but now I have this one:

`browser_adapter.js:84EXCEPTION: Error in ./AppComponent class AppComponent - inline template:4:37BrowserDomAdapter.logError @ browser_adapter.js:84BrowserDomAdapter.logGroup @ browser_adapter.js:94ExceptionHandler.call @ exception_handler.js:65(anonymous function) @ application_ref.js:267ZoneDelegate.invoke @ zone.js:323onInvoke @ ng_zone_impl.js:53ZoneDelegate.invoke @ zone.js:322Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356onInvokeTask @ ng_zone_impl.js:44ZoneDelegate.invokeTask @ zone.js:355Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474
browser_adapter.js:84ORIGINAL EXCEPTION: Hammer.js is not loaded, can not bind slide eventBrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:74(anonymous function) @ application_ref.js:267ZoneDelegate.invoke @ zone.js:323onInvoke @ ng_zone_impl.js:53ZoneDelegate.invoke @ zone.js:322Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356onInvokeTask @ ng_zone_impl.js:44ZoneDelegate.invokeTask @ zone.js:355Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474
browser_adapter.js:84ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:77(anonymous function) @ application_ref.js:267ZoneDelegate.invoke @ zone.js:323onInvoke @ ng_zone_impl.js:53ZoneDelegate.invoke @ zone.js:322Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356onInvokeTask @ ng_zone_impl.js:44ZoneDelegate.invokeTask @ zone.js:355Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474
browser_adapter.js:84Error: Hammer.js is not loaded, can not bind slide event
    at new BaseException (exceptions.js:27)
    at HammerGesturesPlugin.supports (hammer_gestures.js:56)
    at EventManager._findPluginFor (event_manager.js:37)
    at EventManager.addEventListener (event_manager.js:24)
    at DomRenderer.listen (dom_renderer.js:161)
    at DebugDomRenderer.listen (debug_renderer.js:90)
    at DebugAppView._View_AppComponent0.createInternal (AppComponent.ngfactory.js:34)
    at DebugAppView.AppView.create (view.js:102)
    at DebugAppView.create (view.js:315)
    at DebugAppView._View_AppComponent_Host0.createInternal (AppComponent.ngfactory.js:18)`

**Comment by kjartanvalur** [comment]
ok, just needed this in polyfills.js. Now it works :)
import 'hammerjs/hammer';

**Comment by kjartanvalur** [comment]
thanks for the help @JSMike

**Comment by uncledlm** [comment]
Try installing @types/hammerjs : npm i --save-dev @types/hammerjs

Then edit tsconfig.json file and add hammerjs to the types section.

"types": [
      "jasmine", "hammerjs"
    ]
