### ISSUE TITLE
ng update should detect typings files and added it to the appropriate tsconfig file

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#16923]
# 🚀 Feature request

I have a typings.d.ts file that no longer is included in the compilation/build. I was getting errors about not being able to find my ambient types that were in that files. I noticed the tsconfig.app.json was updated to only compile the main.ts and the polyfills. Once I added the typings.d.ts explictly, it worked.

Yes, it's likely not a common scenario. But It might be good to include this scenario in the `ng update` process to v9. 

It would be nice if the ng update process noticed if there was a typings file and added it to the config.

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

**Comment by alan-agius4** [comment]
We should add the following https://github.com/angular/angular-cli/blob/e5061ef2524d2ce8caa9b0d91698fc158f7954ee/packages/schematics/angular/application/files/tsconfig.app.json.template#L11

**Comment by alan-agius4** [comment]
Hi @johnpapa, can you share the contents of tsconfig prior to the update?

**Comment by alan-agius4** [comment]
Info provided offline.
