### ISSUE TITLE
need a way to glob files to get copied by webpack version of CLI

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#1693]
Using the new webpack version of the cli npm installed from `"angular-cli": "https://github.com/angular/angular-cli.git#master",` I noticed that the image assets, style assets, and json objects that use to get copied via the broccoli build are no longer copied.   We need a way to add globs to pick up these files or have them picked up automatically.

**Comment by iamyojimbo** [comment]
@zackarychapple don'y you just need to put them in the `public` directory?

**Comment by albanx** [comment]
I have the same problem with some json files in the src/app/shared dir. Their are not being copied. Is there a way to customize the webpack configuration?

**Comment by kylecordes** [comment]
@albanx  Webpack configuration discussion appears prominently in some other issues; the summary is: for the moment web pack is considered an internal tool use behind the scenes by the CLI, extension mechanisms are being considered, if you're looking to do web pack level configuration the path to do that is to pick up one of the web pack "seed" projects.

For your JSON files, I believe the current (and likely future) answer is that if you want some files to be copied over to the output, you put them in the ```public``` directory. (However, I suspect that if you want these files to be compiled in you could probably refer to them with a require() and most likely it will work.)

**Comment by albanx** [comment]
@kylecordes 
Questions: Can I use any seed project with webpack and angluar cli?
The `public` dir in my project is always empty, and I got the desire effect only by copying in the `dist` folder, and by the way is always empty. Where are the build files?

Where can I insert a require for this files ? 

Thank you

**Comment by MrCroft** [comment]
I'm perfectly fine with having files in the `public` folder. That's where I put my assets anyway.
BUT on `ng build` it doesn't copy everything from the `public` folder.
For example I have a `.htaccess` file (I use apache for local development). That file isn't copied over to the dist folder. I'm guessing it's a filename issue? It doesn't actually have a name, just an extension.

O.S.: Windows

**Comment by kylecordes** [comment]
It sounds like the actual bug report here is:

On Windows, ng build fails to copy .htaccess, and possibly other similarly named files, to the output.

...and the fix is to fix that bug, not to add additional configuration or other settings.

**Comment by MrCroft** [comment]
@kylecordes yes, of course. I've just searched for issues related to copying files and that got me here first. I'll search some more to see if this bug isn't already issued. If not, I'll open one myself.

**Comment by filipesilva** [comment]
@zackarychapple the mechanism for this sort of functionality is to use the `./public/` (in the next release `./src/assets/`) folder. What is the case where this functionality is not sufficient?

@MrCroft please do open up a new issue for the problem you are having, the title suggestion by @kylecordes is a good one.

**Comment by zackarychapple** [comment]
@filipesilva I'm going to close this issue since changes have been made to the `angular-cli.json` to allow for this.
