### ISSUE TITLE
"ng new" throws an error while installing dependencies,  dependency "error-ex" not found 

### ISSUE THREAD

**Issue by akmalnawfer** [angular/angular-cli#16944]
I installed angular 9 cli, my node.js is on latest version. While I try to create a new angular project im getting the following error.

/ Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-02-12T04_52_40_200Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by EMProduct** [comment]
facing the same problem

**Comment by AbdelAbdelAli** [comment]
> I installed angular 9 cli, my node.js is on latest version. While I try to create a new angular project im getting the following error.
> 
> / Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142)
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
> npm ERR! 404
> npm ERR! 404 'error-ex@^1.3.1' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 It was specified as a dependency of 'parse-json'
> npm ERR! 404
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! C:\Users\user\AppData\Roaming\npm-cache_logs\2020-02-12T04_52_40_200Z-debug.log
> × Package install failed, see above.
> The Schematic workflow failed. See above.

i got the same error 
if you fixed the problem please help

**Comment by petebacondarwin** [comment]
Note this line in your log:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
```

Try going to that URL and see if you can access it. For me the request does not 404. If it does then there is some problem with you npm registry connection.

**Comment by AbdelAbdelAli** [comment]
the request does error 404
i just updated my npm and node and angular cli

**Comment by EMProduct** [comment]
the url get 404
i installed the npm an angular cli and same problem
can't access the url page

**Comment by rassasamine** [comment]
as a temporary fix you can manually install "error-ex" module directly from GitHub then install your dependencies as mentioned here https://github.com/facebook/create-react-app/issues/8465#issuecomment-585135338

$ npm i https://github.com/Qix-/node-error-ex
$ npm i

**Comment by Buddikawidu** [comment]
refer mentioned thread,
https://github.com/facebook/create-react-app/issues/8465

**Comment by otundokelvin1991** [comment]
I had a similar problem. It appears to be an npm problem. Then I changed my package manager for Angular by running ng config -g cli.packageManager yarn. I literally shouted, "Thank you Yarn"
