### ISSUE TITLE
Add ng xi18n support for source code strings

### ISSUE THREAD

**Issue by jaska45** [angular/angular-cli#16943]
# 🚀 Feature request

ng xi18n should also extract strings from the source code files.

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Currently xi18n extracts strings only from templates, not from .ts file. Starting from Angular 9 you can now localize source code string using $localize. However without the extraction support this feature is pretty useless.

### Describe the solution you'd like
When I run ng xi18n, it should extract strings from templates and .ts files.

**Comment by alan-agius4** [comment]
//cc @petebacondarwin

**Comment by elvisbegovic** [comment]
Maybe duplication of feat req https://github.com/angular/angular/issues/11405 and discussion about it/answer is here too https://github.com/angular/angular/issues/16477#issuecomment-552635614

**Comment by alan-agius4** [comment]
Thanks @elvisbegovic you are correct.
