### ISSUE TITLE
ivy: Not transpiling correctly on ES5 code

### ISSUE THREAD

**Issue by WLun001** [angular/angular-cli#16948]
ivy does not transpiling correctly on ES5 code, it broke on IE 11. 

Error on `const is not initailised before being use`
Where the const if transpiling from `map` to `for(const i of arr)`

```sh
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.0.1
Node: 12.12.0
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.1
@angular-devkit/core         9.0.1
@angular-devkit/schematics   9.0.1
@schematics/angular          9.0.1
@schematics/update           0.900.1
rxjs                         6.5.3
```

**Comment by WLun001** [comment]
This happened due to the library, `swimlane/ngx-charts`, it has dependency on `d3-scale`, which does not transpile correctly.  Refer to https://github.com/swimlane/ngx-charts/issues/1369

Is this cause by ivy?

**Comment by alan-agius4** [comment]
This seems to be an issue with d3-scale where they are shipping only es5 syntax, which is not compatible with IE.

Closing as this is not an issue with Angular-CLI

**Comment by petebacondarwin** [comment]
I have added additional information and a potential workaround here https://github.com/swimlane/ngx-charts/issues/1369#issuecomment-585089077
