### ISSUE TITLE
Generate component with cli don't care about schematics.@schematics/angular:component.styleext value

### ISSUE THREAD

**Issue by DefeninMaxime** [angular/angular-cli#16949]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.X

### Description

 A clear and concise description of the problem...
After migrate my project from 8 to 9, when I use `ng g c helloworld`, generated files don't match with angular options.

In my `angular.json`,  I have : 
```
     "schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      }
```
But, angular cli generate a `helloworld.component.css` file.

## 🔬 Minimal Reproduction

- Generate a new project in angular@8
- Migrate it to angular@9
- Run `ng g c helloworld`
- Bad file is generated

## 🔥 Exception or Error
<pre><code>
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.3.1
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by mstawick** [comment]
@DefeninMaxime I've also bumped into this. It seems the property has been renamed to `style`.

**Comment by DefeninMaxime** [comment]
In this case `ng update` change conf with a bad value

**Comment by DefeninMaxime** [comment]
Change 
```
"schematics": {
        "@schematics/angular:component": {
          "styleext": "scss"
        }
      }
```
to
```
"schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      }
```

Please fix the migration system to handle `style` instead of `styleext`

**Comment by alan-agius4** [comment]
A migration has been added to address this https://github.com/angular/angular-cli/pull/16924

The new migration will run on the next path version 9.0.2
