### ISSUE TITLE
logger.info() messages should not be sent to stderr

### ISSUE THREAD

**Issue by fcrwx** [angular/angular-cli#16940]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

logger.info() statements from ngcc are sent to stderr causing the informational messages to be displayed (in red) as ERRORs under a maven build. Please see the rejected PR at https://github.com/angular/angular/pull/35310 which documents the incorrect behavior. The ngcc team believes this should be fixed in the cli.

## 🔬 Minimal Reproduction

In maven's pom.xml:
<pre><code>
  ...
  &lt;execution>
    &lt;id>npm angular build&lt;/id>
      &lt;goals>
        &lt;goal>npm&lt;/goal>
      &lt;/goals>
      &lt;configuration>
        &lt;arguments>run build-dev&lt;/arguments>
      &lt;/configuration>
  &lt;/execution>
  ...

</code></pre>

In package.json:
<pre><code>
    "scripts": {
        ...
        "build-dev": "ng build",
        ...
    },
</code></pre>

## 🔥 Exception or Error
Output from maven build:

<pre><code>
[INFO] > ng build
[INFO]
[ERROR]
[ERROR] Compiling @angular/core : module as esm5
[ERROR]
[ERROR] Compiling @angular/common : module as esm5
[ERROR]
[ERROR] Compiling @angular/platform-browser : module as esm5
[ERROR]
[ERROR] Compiling @angular/platform-browser-dynamic : module as esm5
[ERROR]
...
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.1
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Progress, diagnostic and status messages should be written to stderr. stdout should only be used for logs intended to be piped to another command.

//cc @clydin as he definitely has more stronger arguments why it should be stderr.

**Comment by alan-agius4** [comment]
Most likely we should offer a way to silence these, maybe hide this logs when using the `no-progress` or only show them in `verbose` mode. 

Related to https://github.com/angular/angular-cli/issues/16899

**Comment by clydin** [comment]
Is `frontend-maven-plugin` being used in that maven pom?  If so, than version 1.8.0+ ([changelog](https://github.com/eirslett/frontend-maven-plugin/blob/master/CHANGELOG.md#180) & [related issue](https://github.com/eirslett/frontend-maven-plugin/issues/833)) appears to contain a fix so that it does not assume that anything written to stderr is an error.

**Comment by fcrwx** [comment]
@clydin - Thank you! Upgrading `frontend-maven-plugin` from 1.7.6 to 1.8.0 resolves the issue:
```
[INFO] --- frontend-maven-plugin:1.8.0:npm (npm angular build) @ newton-frontend ---
[INFO] Running 'npm run build-dev' in /Users/kolson/dev/Newton/webapps/newton-frontend
[INFO]
[INFO] > newton-webapp@1.0.0-SNAPSHOT build-dev /Users/kolson/dev/Newton/webapps/newton-frontend
[INFO] > ng build
[INFO]
[INFO]
[INFO] Compiling @angular/core : module as esm5
[INFO]
[INFO] Compiling @angular/common : module as esm5
[INFO]
[INFO] Compiling @angular/platform-browser : module as esm5
[INFO]
[INFO] Compiling @angular/platform-browser-dynamic : module as esm5
[INFO]
[INFO] Compiling @angular/upgrade/static : module as esm5
...
```

**Comment by clydin** [comment]
Good to hear.  Since the issue appears to be resolved, I'm going to close.
