### ISSUE TITLE
Syntax error when compiling clearInterval inside setInterval with optimization=true

### ISSUE THREAD

**Issue by slockwoo** [angular/angular-cli#16956]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
Unknown.

### Description

 
Given the code:

<pre><code>
let name = setInterval(() => {
    clearInterval(name);
}, time);
</code></pre>

Building or serving with optimization=true will result in a syntax error, and building or serving with optimization=false results in no such error.

Changing "let" to "var" will fix the issue but I feel the functionality should be consistent with or without optimization.

I speculate this issue may apply to anytime an anonymous function is used as a parameter in any function, and the anonymous function attempts to access the variable referencing the enclosing function, but I have no evidence to back that up.

## 🌍 Your Environment
<pre><code>

Angular CLI: 7.3.8
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                                            Version
---------------------------------------------------------
@angular-devkit/architect               0.6.8
@angular-devkit/build-angular       0.6.8
@angular-devkit/build-optimizer    0.6.8
@angular-devkit/core                      0.6.8
@angular-devkit/schematics            7.3.8
@angular/cdk                                   7.3.7
@angular/cli                                     7.3.8
@angular/material                           7.3.7
@ngtools/webpack                          6.0.8
@schematics/angular                       7.3.7
@schematics/update                        0.13.8
rxjs                                                    6.5.1
typescript                                          3.2.2
webpack                                           4.8.3

</code></pre>
Sorry for the formatting for copy-paste can't be performed.

**Comment by alan-agius4** [comment]
Hi, is this still reproducible in version 9?

**Comment by alan-agius4** [comment]
Closing as no further feedback provided by the issue author.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
