### ISSUE TITLE
Injector error after Deployment

### ISSUE THREAD

**Issue by nikhildhar1992** [angular/angular-cli#16954]
**After deploying the code to server getting below error:**

main-es2015.98751e51d90270e0470e.js:1 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(c)[I -> e]:
StaticInjectorError(Platform: core)[I -> e]:
NullInjectorError: No provider for e!
NullInjectorError: StaticInjectorError(c)[I -> e]:
StaticInjectorError(Platform: core)[I -> e]:
NullInjectorError: No provider for e!
at ce.get (main-es2015.98751e51d90270e0470e.js:1)
at main-es2015.98751e51d90270e0470e.js:1
at e (main-es2015.98751e51d90270e0470e.js:1)
at Qa.get (main-es2015.98751e51d90270e0470e.js:1)
at main-es2015.98751e51d90270e0470e.js:1
at e (main-es2015.98751e51d90270e0470e.js:1)
at Qa.get (main-es2015.98751e51d90270e0470e.js:1)
at xd (main-es2015.98751e51d90270e0470e.js:1)
at main-es2015.98751e51d90270e0470e.js:1
at Id (main-es2015.98751e51d90270e0470e.js:1)
at v (polyfills-es2015.5b10b8fd823b6392f1fd.js:1)
at v (polyfills-es2015.5b10b8fd823b6392f1fd.js:1)
at polyfills-es2015.5b10b8fd823b6392f1fd.js:1
at a.invokeTask (polyfills-es2015.5b10b8fd823b6392f1fd.js:1)
at Object.onInvokeTask (main-es2015.98751e51d90270e0470e.js:1)
at a.invokeTask (polyfills-es2015.5b10b8fd823b6392f1fd.js:1)
at s.runTask (polyfills-es2015.5b10b8fd823b6392f1fd.js:1)
at _ (polyfills-es2015.5b10b8fd823b6392f1fd.js:1)

**Angular Dependencies**

"@angular/animations": "~8.2.14",
"@angular/common": "~8.2.14",
"@angular/compiler": "~8.2.14",
"@angular/core": "~8.2.14",
"@angular/forms": "~8.2.14",
"@angular/platform-browser": "~8.2.14",
"@angular/platform-browser-dynamic": "~8.2.14",
"@angular/router": "~8.2.14",
"@azure/msal-angular": "^0.1.4",
"ag-grid-angular": "^22.1.1",
"ag-grid-community": "^22.1.1",
"ag-grid-enterprise": "^22.1.1",
"bootstrap": "^4.4.1",
"ngx-toastr": "^12.0.0",
"rxjs": "^6.5.4",
"rxjs-compat": "^6.5.3",
"tslib": "^1.10.0",
"xlsx": "^0.15.5",
"zone.js": "~0.9.1"

**Comment by alan-agius4** [comment]
Thanks for opening the issue. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by nikhildhar1992** [comment]
Sure @alan-agius4 give me some time I will upload

**Comment by nikhildhar1992** [comment]
Please checkout this https://github.com/nikhildhar1992/angular-cli/tree/nikhildhar1992-patch-1

**Comment by nikhildhar1992** [comment]
I have one question why  its working on local but not on server? we cannot even test this error until we upload it to server . Its totally waste of time . Or is it like angular is not able to detect such error?

**Comment by filipesilva** [comment]
@nikhildhar1992 I checked the branch you linked and it doesn't have any application files. Can you make the reproduction in a separate repository and include all files needed please?

**Comment by filipesilva** [comment]
I don't why your app might be working locally but not on your server. That might be related to how you set up the server.

**Comment by nikhildhar1992** [comment]
@filipesilva  that issue is resolved 
I have build the application like **ng build --prod --build-optimizer=false --base-href ./**
