### ISSUE TITLE
Couldn't find package "error-ex" on the "npm" registry.

### ISSUE THREAD

**Issue by diinushkaaa** [angular/angular-cli#16957]
# 🐞 Bug report

| Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/error-ex
npm ERR! 404
npm ERR! 404  'error-ex@^1.3.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-json'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Asus F560\AppData\Roaming\npm-cache\_logs\2020-02-12T14_38_41_997Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

Why this happening i tried changing the Node version and upgraded to the latest version help

**Comment by myrddraall** [comment]
having the same issue 

`ng new project-name`

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 10.16.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.1
@angular-devkit/core         9.0.1
@angular-devkit/schematics   9.0.1
@schematics/angular          9.0.1
@schematics/update           0.900.1
rxjs                         6.5.3
```

```
/ Installing packages...warning @angular-devkit/build-angular > less > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error Couldn't find package "error-ex" on the "npm" registry.
× Package install failed, see above.
The Schematic workflow failed. See above.
```

**Comment by myrddraall** [comment]
Looks like its an issue with npm

[https://status.npmjs.org/](https://status.npmjs.org/)
```
We are currently investigating issues with installing certain packages.

Some of the packages known to be affected are: 3d-view, error-ex ,42-cent-base, 8base-cli.
```

**Comment by alan-agius4** [comment]
Closing as issue seems to have been resolved by NPM.
