### ISSUE TITLE
ENDLOCAL EXIT /b 3 when updating lib to Angular 9

### ISSUE THREAD

**Issue by kolkov** [angular/angular-cli#16975]
I try to update my lib to Angular 9 and got an error at end of procedure. Is this correct?
https://github.com/kolkov/ngx-dadata
`ng update @angular/cli`
![image](https://user-images.githubusercontent.com/3740898/74523269-d8582780-4f2d-11ea-870d-185591490764.png)

![image](https://user-images.githubusercontent.com/3740898/74522875-1f91e880-4f2d-11ea-92ba-556867ebd4a1.png)

Thanks!

**Comment by alan-agius4** [comment]
@kolkov, you are not using the latest 8.x version. Please update to the latest 8.x version of the CLI prior to update to version 9.

Kindly follow https://update.angular.io/#8.0:9.0

**Comment by kolkov** [comment]
Thanks!
