### ISSUE TITLE
New Angular project is not created

### ISSUE THREAD

**Issue by VarshneyNaupada** [angular/angular-cli#16977]
Hi Team,

I am trying to create a new Angular project, but it is giving errors. I am using the latest angular/CLI i.e. v9
ng new app01

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

Also please report cli issues in cli's repo https://github.com/angular/angular-cli respecting the issue template :+1:

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.Thanks for reporting this issue. HoweverPlease check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by VarshneyNaupada** [comment]
ng new app02
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE app02/angular.json (3559 bytes)
CREATE app02/package.json (1282 bytes)
CREATE app02/README.md (1022 bytes)
CREATE app02/tsconfig.json (543 bytes)
CREATE app02/tslint.json (1953 bytes)
CREATE app02/.editorconfig (246 bytes)
CREATE app02/.gitignore (631 bytes)
CREATE app02/browserslist (429 bytes)
CREATE app02/karma.conf.js (1017 bytes)
CREATE app02/tsconfig.app.json (210 bytes)
CREATE app02/tsconfig.spec.json (270 bytes)
CREATE app02/src/favicon.ico (948 bytes)
CREATE app02/src/index.html (291 bytes)
CREATE app02/src/main.ts (372 bytes)
CREATE app02/src/polyfills.ts (2835 bytes)
CREATE app02/src/styles.css (80 bytes)
CREATE app02/src/test.ts (753 bytes)
CREATE app02/src/assets/.gitkeep (0 bytes)
CREATE app02/src/environments/environment.prod.ts (51 bytes)
CREATE app02/src/environments/environment.ts (662 bytes)
CREATE app02/src/app/app-routing.module.ts (246 bytes)
CREATE app02/src/app/app.module.ts (393 bytes)
CREATE app02/src/app/app.component.html (25705 bytes)
CREATE app02/src/app/app.component.spec.ts (1056 bytes)
CREATE app02/src/app/app.component.ts (209 bytes)
CREATE app02/src/app/app.component.css (0 bytes)
CREATE app02/e2e/protractor.conf.js (808 bytes)
CREATE app02/e2e/tsconfig.json (214 bytes)
CREATE app02/e2e/src/app.e2e-spec.ts (638 bytes)
CREATE app02/e2e/src/app.po.ts (301 bytes)
\ Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '...D7m2C266B6VnM8C20jivf'
