### ISSUE TITLE
Make @angular-devkit/core/node/resolve independent of node_modules resolution

### ISSUE THREAD

**Issue by bgotink** [angular/angular-cli#16981]
# 🚀 Feature request

### Description

The custom resolution provided by `@angular-devkit/core/node/resolve` reimplements the node_module resolution algorithm, which doesn't work for package manages that don't use node_modules (yarn 2 with plug'n'play, npm tink if that gets revived).

### Describe the solution you'd like

Replace the custom node_modules implementation with calls to either `require.resolve` with the `paths` option or to a `require` function created using [`createRequire`](https://nodejs.org/api/modules.html#modules_module_createrequire_filename). 
These functions work regardless of the used package manager (yarn 1, yarn 2 with pnp, npm, pnpm, &hellip;)

### Describe alternatives you've considered

- Override the resolution, using either
  - `setResolveHook`
  - [a patch](https://github.com/bgotink/yarn-plugin-angular/blob/master/patches/%40angular-devkit/core.patch) applied to the `@angular-devkit/core` package via yarn 2's `patch` protocol or via a yarn plugin
- Explicitly query the yarn PnP API, but that would require plug'n'play-specific logic in the resolution file.

**Comment by clydin** [comment]
That code is currently deprecated and unused by the CLI.  Based on the deprecation process, it should be eligible for removal by the next major release.

**Comment by bgotink** [comment]
I did some digging and it turns out I had one dependency still on version 0.803, updating that to 0.900 fixed it the issues.
Thanks!
