### ISSUE TITLE
deploy-url trailing slash does not appear in the message 'open your browser on {url}'

### ISSUE THREAD

**Issue by reda-alaoui** [angular/angular-cli#16984]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know.

### Description

I serve an angular application with `ng serve --host 0.0.0.0 --disable-host-check --deploy-url=/my-app/`. 
On startup, the CLI prints the following message:
```
 Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/my-app 
```
As you can see the trailing slash disappears.
The message should be:
```
 Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/my-app/
```

## 🔬 Minimal Reproduction

Run `ng serve --host 0.0.0.0 --disable-host-check --deploy-url=/my-app/`. 

## 🔥 Exception or Error

None

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.2
Node: 10.13.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

It seems that the trailing slash is removed at https://github.com/angular/angular-cli/blob/1dbcd8dccd05de377d02bd75ba2464434a2e7212/packages/angular_devkit/build_angular/src/dev-server/index.ts#L530

**Comment by dgp1130** [comment]
This issue just seems to be about the URL displayed to the user, I don't see any functional difference from using this URL?

There is a subtle difference in browsers between a page hosted at `/foo` and at `/foo/`. A relative URL to `bar` will be resolved as either `/bar` or `/foo/bar` respectively, but Angular applications always include a `<base />` tag which should override that behavior.

Since there is no functional difference, which URL to display is purely subjective. After a quick discussion, we'd rather not make promises about which format will be displayed for a particular debugging output like this. If the difference in URL causes an actual observable difference in page behavior, then we can re-evaluate. Otherwise this isn't something to over-specify for purely aesthetic reasons.

**Comment by reda-alaoui** [comment]
This is not for aesthetic reason.
There is a functional difference. Without the slash, it just does not work.

**Comment by dgp1130** [comment]
Can you elaborate on what doesn't work? Can you provide a minimal reproduction where the URL printed out is not usable (running `ng new` and then tweaking it to reproduce the error is an easy way of doing this).

**Comment by reda-alaoui** [comment]
This does not work when the server is Tomcat.
Tomcat is a servlet container that can serve multiple webapps. Each webapp has a context.
If Tomcat runs on http://localhost:8080/, application having context `app` will be exposed at `http://localhost:8080/app/`. If the last `/` is missing, Tomcat fails to serve the app.

**Comment by reda-alaoui** [comment]
You can have the same probleme when behind a httpd proxy. I don't have a reproduction case available, the ticket is very old. I can assure you that it didn't work in my case and that the `/` at the end can have meaning.

**Comment by reda-alaoui** [comment]
Frankly, I don't remember the exact setup that lead to this error. I just tried `ng new` plus `ng serve --host 0.0.0.0 --disable-host-check --deploy-url=/my-app/`, it works. There was something in addition I think. I will comment this ticket if I stumble on the issue again.

**Comment by dgp1130** [comment]
If you're able to reproduce on the latest Angular CLI then we can take a look further to see what's going wrong.
