### ISSUE TITLE
Issue with " ng new " -- Not able to create a new project.

### ISSUE THREAD

**Issue by VarshneyNaupada** [angular/angular-cli#16987]
🐞 Bug report

### Command (mark with an `x`)

- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

< Description>
 Unable to use " ng new " to create new angular project.

Logs:

ng new app02
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE app02/angular.json (3559 bytes)
CREATE app02/package.json (1282 bytes)
CREATE app02/README.md (1022 bytes)
CREATE app02/tsconfig.json (543 bytes)
CREATE app02/tslint.json (1953 bytes)
CREATE app02/.editorconfig (246 bytes)
CREATE app02/.gitignore (631 bytes)
CREATE app02/browserslist (429 bytes)
CREATE app02/karma.conf.js (1017 bytes)
CREATE app02/tsconfig.app.json (210 bytes)
CREATE app02/tsconfig.spec.json (270 bytes)
CREATE app02/src/favicon.ico (948 bytes)
CREATE app02/src/index.html (291 bytes)
CREATE app02/src/main.ts (372 bytes)
CREATE app02/src/polyfills.ts (2835 bytes)
CREATE app02/src/styles.css (80 bytes)
CREATE app02/src/test.ts (753 bytes)
CREATE app02/src/assets/.gitkeep (0 bytes)
CREATE app02/src/environments/environment.prod.ts (51 bytes)
CREATE app02/src/environments/environment.ts (662 bytes)
CREATE app02/src/app/app-routing.module.ts (246 bytes)
CREATE app02/src/app/app.module.ts (393 bytes)
CREATE app02/src/app/app.component.html (25705 bytes)
CREATE app02/src/app/app.component.spec.ts (1056 bytes)
CREATE app02/src/app/app.component.ts (209 bytes)
CREATE app02/src/app/app.component.css (0 bytes)
CREATE app02/e2e/protractor.conf.js (808 bytes)
CREATE app02/e2e/tsconfig.json (214 bytes)
CREATE app02/e2e/src/app.e2e-spec.ts (638 bytes)
CREATE app02/e2e/src/app.po.ts (301 bytes)
\ Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '...D7m2C266B6VnM8C20jivf'

< Issue Replication>

Just try to create a new angular project through command prompt.

ng new app01

It is not installing properly and node_modules also missing.

<My version>

I am using Angular v9.0.2

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.2
Node: 12.13.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.2
@angular-devkit/core         9.0.2
@angular-devkit/schematics   9.0.2
@schematics/angular          9.0.2
@schematics/update           0.900.2
rxjs                         6.5.3

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by babtsoualiaksandr** [comment]
Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '....js","ng-xi18n":"./sr'

Angular CLI: 9.0.6
Node: 12.13.1
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.6
@angular-devkit/core         9.0.6
@angular-devkit/schematics   9.0.6
@schematics/angular          9.0.6
@schematics/update           0.900.6
rxjs                         6.5.3
