### ISSUE TITLE
Proxy to a backend

### ISSUE THREAD

**Issue by seklyza** [angular/angular-cli#1698]
OS: Windows 7

Version: 1.0.0-beta.11-webpack.2 (node:  6.3.1)

I'm upgraded to the webpack version of the CLI, and I used to create an .ember-cli file which defines a proxy to a backend.

But the CLI doesn't point anything to the backend (port 3000).

It also doesn't work when I type `ng serve --proxy <proxy>`

Thanks,

**Comment by mmrath** [comment]
See: https://github.com/angular/angular-cli/pull/1487

**Comment by mmrath** [comment]
Duplicate of #889

**Comment by filipesilva** [comment]
As @mmrath said, dupe of #889 and closed by https://github.com/angular/angular-cli/pull/1487
