### ISSUE TITLE
Add --flat back as a flag for ng new

### ISSUE THREAD

**Issue by johnpapa** [angular/angular-cli#16986]
# 🚀 Feature request

Add back the `--flat` flag for `ng new` so we can tell the CLI to always create components where they are instead of in a nested folder.

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

**Comment by alan-agius4** [comment]
Hi @johnpapa, I don't remember `flat` was ever an option to `ng new`. 

Maybe you had a global config that sets this flag?

**Comment by johnpapa** [comment]
Maybe I am mistaken. But this would be helpful globally. So I change my request to add this flag. 

Otherwise I currently have to use it every time I make a component.

**Comment by alan-agius4** [comment]
Actually like any other schematic option, you don't need to specify the `flat` option every time. As you can config it to always be flat.

Example
Project wide setting
```
ng config "projects.<project name>.schematics.@schematics/angular:component.flat" true
```

Workspace wide setting
```
ng config "schematics.@schematics/angular:component.flat" true
```

Global setting
```
ng config -g "schematics.@schematics/angular:component.flat" true
```

**Comment by johnpapa** [comment]
Good point. I always forget about the `ng config` commands. I set mine up and then ... forgot :)

I'll do that for now.
