### ISSUE TITLE
Angular 9 build writes info logs on stderr instead of stdout

### ISSUE THREAD

**Issue by sergiubologa** [angular/angular-cli#16994]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
...

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 8

### Description
After upgrading my app to Angular 9 the build fails on CI (Azure DevOps) because there is an info log written on stderr. The error message is the following:

`##[error]Compiling @angular/core/testing : module as esm5`

and the error message at the end of the build process is the following one:

`##[error]Process completed with exit code 0 and had 1 error(s) written to the error stream.`

Unfortunately, I can't configure my CI to not fail if the exit code is 0 and currently fails on anything that's written on the stderr stream.

## 🔬 Minimal Reproduction

1. Create a new Angular 9 project
2. Run an `ng build --prod` command in the Azure Devops CI
3. The build should fail because the `Compiling @angular/core/testing : module as esm5` messages are written to stderr stream.

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.2
Node: 12.4.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-ng-packagr   0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/build-webpack      0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cdk                       9.0.0
@angular/cli                       9.0.2
@angular/material                  9.0.0
@ngtools/webpack                   9.0.2
@schematics/angular                9.0.2
@schematics/update                 0.900.2
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Comment by clydin** [comment]
This appears to be a defect with Azure DevOps and not the Angular CLI.  A write to stderr does not necessarily signify an error (especially when the exit code is zero).  It is rather a channel for general diagnostic information (progress for instance).

Similar issue regarding a different tool which was solved via a fix to the tool: https://github.com/angular/angular-cli/issues/16940

**Comment by clydin** [comment]
On further review of the Azure DevOps documentation, this does not appear to be a defect but rather a configuration issue.  From the documentation found [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/command-line?view=azure-devops&tabs=yaml), the `failOnStderr` option should not be enabled.  This option appears to only be needed for applications that do not properly return a non-zero exit code when an error occurs.

**Comment by sergiubologa** [comment]
Thanks @clydin, for the explanations. You are right, it's an issue with AzureDevops. Actually that config `failOnStderr` doesn't really work, there's an issue opened in their repo too: https://github.com/microsoft/azure-pipelines-yaml/issues/306

Anyway, what's the reasoning of writing info messages on stderr stream and not on the stdout?
