### ISSUE TITLE
Cannot find module '@angular-devkit/schematics' when adding @angular/material

### ISSUE THREAD

**Issue by nmorado** [angular/angular-cli#17000]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This issue occurs on a new fresh app created on latest angular cli 9.0.2.

### Description
Create a new app using 9.0.2 CLI. cd to the app, and add @angular/material:

`ng add @angular/material`

Fails with the below errors:

`
[error] Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
`

## 🔬 Minimal Reproduction
`ng new myapp`
`cd myapp`
`ng add @angular/material`

## 🔥 Exception or Error
<pre><code>
[error] Error: Cannot find module '@angular-devkit/schematics'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.2
Node: 10.13.0
OS: darwin x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by sacgrover** [comment]
Not able to reproduce with above mentioned steps.

**Comment by nmorado** [comment]
did you have the same exact environment above?

**Comment by sacgrover** [comment]
Yes, I have same mentioned environment.

**Comment by alan-agius4** [comment]
I am also unable to reproduce the above.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
