### ISSUE TITLE
AOT Optimizer with Ivy enabled for a hybrid Angular/AngularJS app doesn't include all the necessary components

### ISSUE THREAD

**Issue by maximecarlier** [angular/angular-cli#17011]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, it used to work with the 8.x versions because Ivy was not enabled by default.
However, it still works correctly with Ivy disabled, so it's not a critical regression.

### Description

For a hybrid Angular/AngularJS application, having Ivy, AOT and the Optimizer enabled will prevent the production bundle to contain all the necessary components.

Disabling any of those 3 (Ivy, AOT, or the Optimizer) will allow the builder to include all the used components.

This issue seems to be related to the fact that AngularJS is in charge of the routing and the missing components are only used in AngularJS templates.

## 🔬 Minimal Reproduction

1. You can checkout this project: https://github.com/maximecarlier/angular-hybrid-ivy-bug
2. Run `npm i`
3. Run `ng serve` and see that the string "Angular/AngularJS Hybrid" is displayed
4. Run `ng serve --prod`  and see that that's not the case anymore
5. Possible actions with the same result:
  *  Disable Ivy (in `tsconfig.json`, set `angularCompilerOptions.enableIvy` to false)
  *  Disable AOT (in `angular.json`, set `projects.angular-test.architect.build.options.aot` to false)
  *  Disable the scripts optimization (in `angular.json`, set `projects.angular-test.architect.build.configurations.production.optimization.scripts` to false)
6. Run `ng serve --prod`  and see that the string appears again

## 🔥 Exception or Error

No exception or error, the components are just not part of the bundle file for production.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.2
Node: 12.13.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, I think this has the same root cause as https://github.com/angular/angular-cli/issues/15809. See the following comment https://github.com/angular/angular-cli/issues/15809#issuecomment-543281509 for way on how to make this work.
