### ISSUE TITLE
Build in docker fails due to out of memory and using node options never completes.

### ISSUE THREAD

**Issue by kumargauravin** [angular/angular-cli#17023]
Build in docker fails due to out of memory and using node options never completes.

> ng build "--prod" "--progress=true"

 92% chunk asset optimization TerserPlugin                                         
<--- Last few GCs --->

[32:0x55750ca30ec0]   313564 ms: Mark-sweep 972.8 (1006.8) -> 967.9 (1007.5) MB, 812.4 / 0.0 ms  (average mu = 0.210, current mu = 0.216) allocation failure scavenge might not succeed
[32:0x55750ca30ec0]   314924 ms: Mark-sweep 973.6 (1007.5) -> 969.5 (1009.3) MB, 1281.0 / 0.0 ms  (average
mu = 0.126, current mu = 0.058) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x55750af970b9]
Security context: 0x2685964808d1 <JSObject>
    1: p(aka p) [0x1571324b4cd9] [/usr/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:~1] [pc=0x1a17a757e82c](this=0x2f0af8ac04b1 <undefined>,0x264b0c916511 <String[#4]: punc>,0x341c46d75b91 <String[#1]: )>)
    2: _(aka _) [0x2034432cc639] [/usr/node_modules/terser-webpack-plugin/node_modules/terser/dist/bundle.min.js:1] [bytecode...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
npm ERR! code ELIFECYCLE

**Comment by kumargauravin** [comment]
Angular 8 
> ngx-admin@4.0.1 build:prod /usr
> node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --progress=true

 92% chunk asset optimization TerserPlugin ---> 8b5d23fd1857                       
Removing intermediate container 3ca233880653
Step 6/7 : EXPOSE '8000'
 ---> Running in b65dbdc9ff96
 ---> 6792d28a6a97
Removing intermediate container b65dbdc9ff96

passes the build but does not create dist directory.

**Comment by Zwartpet** [comment]
@kumargauravin https://github.com/angular/angular-cli/pull/17028

**Comment by alan-agius4** [comment]
@kumargauravin can you please provide the full output of `ng version`?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
