### ISSUE TITLE
Windows specific warning message in chrome console: "(webpack)/buildin/module.js There are multiple modules with names that only differ in casing...."

### ISSUE THREAD

**Issue by rexebin** [angular/angular-cli#1702]
1. Environment: Windows,  use `npm link angular-cli` to the master branch of `Angular-cli` repository, apply to any projects created with CLI.

2.  Warning message in Chrome's console window:
```
(webpack)/buildin/module.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* c:\Projects\angular-cli\node_modules\source-map-loader\index.js!C:\Projects\angular-cli\node_modules\webpack\buildin\module.js
    Used by 1 module(s), i. e.
    c:\Projects\angular-cli\node_modules\source-map-loader\index.js!C:\Projects\github-client\node_modules\rxjs\util\root.js
* c:\Projects\angular-cli\node_modules\source-map-loader\index.js!c:\Projects\angular-cli\node_modules\webpack\buildin\module.js
    Used by 2 module(s), i. e.
    c:\Projects\angular-cli\node_modules\source-map-loader\index.js!c:\Projects\angular-cli\node_modules\punycode\punycode.js
```
3. Discussed with @filipesilva who noticed that `C:` is different than`c:`. The command line tool on windows use capital C in default. I tried to use `cd c:\project` to change the path with lower case `c:` and the warning message was gone.

**Comment by filipesilva** [comment]
Definitely a weird issue. I don't think it's a CLI issue per se, but perhaps a node issue. I'm closing for now as a workaround has been reached and it doesn't seem to be a widespread thing, but will reopen if more reports arrive.

**Comment by asadsahi** [comment]
Having exactly same issue with cli version: "1.0.0-beta.11-webpack.2", on windows 10 with node 6.3.1.

```
WARNING in (webpack)/buildin/module.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Users\asad\ng2fb-material\node_modules\source-map-loader\index.js!C:\Users\asad\ng2fb-material\node_modules\webpack\buildin\module.js
    Used by 2 module(s), i. e.
    C:\Users\asad\ng2fb-material\node_modules\source-map-loader\index.js!C:\Users\asad\ng2fb-material\node_modules\punycode\punycode.js
* C:\Users\asad\ng2fb-material\node_modules\source-map-loader\index.js!c:\Users\asad\ng2fb-material\node_modules\webpack\buildin\module.js
    Used by 1 module(s), i. e.
    c:\Users\asad\ng2fb-material\node_modules\rxjs\util\root.js
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  2.41 kB       0       
webpack: bundle is now VALID.
```

**Comment by filipesilva** [comment]
If there's an updated webpack version that addresses this issue we're happy to use it!

**Comment by andvasp** [comment]
Hy Guys,

This happened with me too. I figure out what causes the problem. The driver letter where I was running the application was not in capital letter e.g.
**c**:\Project> instead of **C**:\Project>. 

This happend because i switched from one directory to other using the command 

> cd /d **c**:\project 

because i was in H:\>.
