### ISSUE TITLE
Why does prerendering create NamedChunks?

### ISSUE THREAD

**Issue by scurk1415** [angular/angular-cli#17021]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [X] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

I don't know cause i was not using the previous version

### Description

Prerendering always creates named chunks. If i run `ng run app:build:production` everything builds correctly https://prnt.sc/r2dytb , but if i run it with `ng run app:prerender:production` the lazy loaded modules are still named based on the module name https://prnt.sc/r2dzp1

## 🔬 Minimal Reproduction

1. Create angular app (v9)
2. `ng add @nguniversal/express-engine`
3. create a module to lazy load
4. run `ng run app:prerender:production`

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.2
Node: 12.14.1
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by Mr-Plutus** [comment]
Now in prerender there is only dev assembly, and it is needed only for production

**Comment by scurk1415** [comment]
So any update on this?

**Comment by s2young** [comment]
Same issue.  Also ngsw-worker.js isn't getting built during prerender, where it is within ng build.

**Comment by Exocomp** [comment]
Running into the same issue, appears it is generating a dev build for some reason. My work around, although very ugly is to build for prerender then build for prod and copy over the prerender html files over to the prod build. Then update the bundle paths in the html files for prod. Very ugly but only work around I could think of for right now just to get it to work.

**Comment by skyquartam** [comment]
Whatching on this beacuse this makes impossible to use ng service worker with prerender (So bad) @Exocomp please can you post some snippets on how to do your workaround?

**Comment by Exocomp** [comment]
@skyquartam 

It's pretty ugly (I stress it again) but here is the general idea, however, I recommend just waiting for an actual fix:

*Build for prerender
**Afterwards rename the dist folder else (ex. dist_prerender)
*Build for prod
**Afterwards copy the .html files from dist_prerender over to dist
**For each .html file modify the previous bundle paths to the prod bundle paths

Since you're working with a service worker you probably will have to update the service worker json file  (ngsw.json) with the new file hashes or I think it will break how sw works.

**Comment by trympet** [comment]
Quick and dirty workaround if your dev workflow doesn't depend on named chunks:

1. Open "node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/named-chunks-plugin.js"
2. Comment out "dependency.block.chunkName = Template.toPath(dependency.request);" (line 26)

This will prevent the named chunks plugin from renaming dependencies.

**Comment by neo** [comment]
I think having named chunks is just the surface of the problem where the root problem is like @alan-agius4 mentioned that `context.scheduleTarget` isn't doing what it's supposed to do when building with a configuration target.

**Comment by scurk1415** [comment]
Common guys this has been opened for 2 months now, Universal prerendering is practically useless since it was released

**Comment by neo** [comment]
Let's try to be nice and respectful to the people who work very hard on the tools we love 😀 

But it is an issue in the milestone of 9.0.x... Maybe re-pinging @clydin and @alan-agius4 could help?

🙏 Thank you all!!

**Comment by alan-agius4** [comment]
Hi all, we didn't forget about this issue. 

It's just that it taking more time to find the root cause of the problem.

**Comment by neo** [comment]
Thank you for the update!!
We really appreciate it and all your hard work!!

**Comment by mostlymark** [comment]
@alan-agius4 Alan, I rebuilt the 9.1.2 release with your fix and I'm able to produce a prerender build without the maps. Thank you!

**Comment by scurk1415** [comment]
Thank you guys ♥

**Comment by denisyilmaz** [comment]
is this already released? I updated to Angular CLI 9.1.2 but still get the maps and named chunks with the prerender

**Comment by alan-agius4** [comment]
No, this will be released in version 9.1.3.

**Comment by denisyilmaz** [comment]
Ah, I see. Thanks a lot

**Comment by neo** [comment]
And it just got released! What a speedy release 😆 
(cc @denisyilmaz)

**Comment by d2kx** [comment]
Can confirm it works!! <3

Nice desu ne
