### ISSUE TITLE
ng-add doesn't install the latest version correctly

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-cli#17024]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. With `@angular/cli@8` doesn't cause that error.

### Description

In a project created by `@angular/cli@latest`, `ng add` command seems not working correctly. 
Executing `ng add @ngrx/store`, it throws an error.

```
$ ng add @ngrx/store
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
error Command failed with exit code 1.
```

But adding `@latest` to the `@ngrx/store`, it installs and runs schematics of `@ngrx/store`. 

```
ng add @ngrx/store@latest
Package has unmet peer dependencies. Adding the package may not succeed.
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
CREATE src/app/reducers/index.ts (359 bytes)
UPDATE src/app/app.module.ts (715 bytes)
UPDATE package.json (1349 bytes)
✔ Packages installed successfully.
✨  Done in 6.67s.
```

It seems Angular CLI's bug in `ng add` command. 

## 🔬 Minimal Reproduction

1. Create new project with the latest CLI (`npx @angular/cli@latest new my-app`)
2. Execute `ng add @ngrx/store` in the project.

## 🔥 Exception or Error
<pre><code>
$ ng add @ngrx/store
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
error Command failed with exit code 1.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.3
Node: 12.13.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
    

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @lacolaco, the problem seems to be that `@ngrx/store` version 8 is not compatible with Angular 9. This is due that the peerDependencies for this package are the following;

```json
"peerDependencies": {
   @angular/core": "^8.0.0",
  "rxjs": "^6.4.0"
},
``` 

`ng-add` will try to find a compatible version and version `1.2.1` has no `peerDependencies` which is making it the package valid to be used.

//cc @brandonroberts

**Comment by lacolaco** [comment]
@alan-agius4 Thank you for clarifying. IMO, `peerDependencies` is not an absolute restriction always. In fact Angular CLI allows TypeScript version mismatch with a warning. 
I think the CLI always should try installing the `@latest` version because developers perhaps expect `ng add` is a wrapper of `npm install` or `yarn add`. Following their default version resolution is intuitive.  
If it is not compatible with peerDeps, the CLI can warn.

**Comment by Brian611** [comment]
Facing a similar issue with a current project on v9. Any update?

**Comment by clydin** [comment]
@Brian611 This is a problem with the `@ngrx/store` package.  It does not currently support Angular version 9.

**Comment by brandonroberts** [comment]
For others trying to use Angular v9 with NgRx v8, use the `@latest` tag when using `ng add` to get the latest released version according to npm. The Angular CLI tries to figure out the version to install, taking into account the peer dependencies. This is why NgRx 1.2.1 is being chosen without using the `@latest` tag. This issue is not present if you are installing NgRx v9 after it goes final.

```
ng add @ngrx/store@latest
```

**Comment by Brian611** [comment]
@brandonroberts  Yes i noticed and upgraded but would've hoped this would be a fix rather than waiting on ngrx v9 cause now we running prod project on an rc version of ngrx which is not ideal.

**Comment by brandonroberts** [comment]
@Brian611 there's nothing preventing you from running NgRx v8 with Angular v9. There's only the peer dependency warning. NgRx v9 will be out soon

**Comment by Brian611** [comment]
@brandonroberts  ohk cool.

**Comment by alan-agius4** [comment]
Closing as this is working as expected.
