### ISSUE TITLE
ng generate component [name] --type use to work on 9.0.1 now disappear on 9.0.3

### ISSUE THREAD

**Issue by hiepxanh** [angular/angular-cli#17037]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] generate

### Is this a regression?

 Yes, the previous version in which this bug was not present was: `"@angular/cli": "^9.0.1",`
I love this feature so much
### Description
when I generate component, I can use --type to decide the extension of component. for example:
`ng g c home --type=page` could generate `home.page.ts` used to work on angular CLI 9@beta, @9.0.1, now it is disappear on @9.0.3

![image](https://user-images.githubusercontent.com/16970990/75004160-d0a00200-549c-11ea-96d4-14753529cabc.png)

as document said, it should be there
![image](https://user-images.githubusercontent.com/16970990/75004507-f8439a00-549d-11ea-9e0c-66ec619ab499.png)

**Comment by alan-agius4** [comment]
@hiepxanh, can you run `ng version` and `npm ls @schematics/angular` please? 

In the first screenshot, I am seeing options which are no longer available since version 9.0.0, I am thinking you are experiencing package hoisting issues.

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/75014323-95133100-54b8-11ea-90f4-353f8d0ef148.png)
you are correct, I can't understand the left project was use `ng update --all` but seem look like it not work correctly, thank you to point this out. I'm closing this issue
