### ISSUE TITLE
[I18n] New locale codes not supported by angular.json

### ISSUE THREAD

**Issue by floreks** [angular/angular-cli#17032]
According to [I18n documentation](https://angular.io/guide/i18n#setting-up-the-locale-of-your-app), language code such as `zh-Hant-HK` should be supported. Documentation also points you to the list of all [supported locales](https://github.com/angular/angular/tree/master/packages/common/locales) on the angular repo.

It seems however that those codes are blocked by the regular expression defined in the schema.

https://github.com/angular/angular-cli/blob/c9a5f3ced6689feac9cc0ccbd15b0fed6f454d6e/packages/angular/cli/lib/config/schema.json#L416-L420

![Zrzut ekranu z 2020-02-20 16-27-55](https://user-images.githubusercontent.com/2285385/74949420-080ba180-53fe-11ea-99b8-6dc5ca9c6984.png)

**Comment by clydin** [comment]
Thank you for pointing this out.  It was actually updated above that line but this instance appears to have been missed.  A fix will be available in the next patch release.
