### ISSUE TITLE
The transpiled es5 prod build drops static method call

### ISSUE THREAD

**Issue by rrajewski** [angular/angular-cli#17049]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes, worked prior to angular 9.

### Description

 A clear and concise description of the problem...
The trans-piled es5 build drops calls to a static method on a class.

## 🔬 Minimal Reproduction

Full Example at: https://github.com/rrajewski/es5TranspileIssue with compiled dist directory

1. Create a typescript class with a static method that modifies a passed in object
2. Call the static method 
3. Generate a prod build ng build --prod
4. The es5 prod bundle does not contain the static method call, while the es2015 version does.

<pre><code>
export class ExampleWithStaticMethod {
  static modifyObject(obj: any) {
    obj.test = "TODO";
  }
}
...
export class AppComponent implements OnInit {
  example = {};

  ngOnInit(): void {
    ExampleWithStaticMethod.modifyObject(this.example);
   
   // after ng build --prod this.example.test will not exist in the es5 version only
  }
}
</pre></code>

## 🔥 Exception or Error
Example in IE 11: 
![image](https://user-images.githubusercontent.com/3542486/75055335-6be3a800-549a-11ea-8477-bd259bd6f9c6.png)

Example in Chrome: 
![image](https://user-images.githubusercontent.com/3542486/75055248-4787cb80-549a-11ea-8e25-0645b3549c45.png)

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.3
Node: 10.16.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
So look at this briefly and what is happening is that when running the ES2015 build he generated output will look like;

```ts
class t {
    constructor() {
        this.example = {};
    }
    ngOnInit() {
        (class {
            static modifyObject(t) {
                t.test = "TODO";
            }
        }).modifyObject(this.example);
    }
}
```

When the above gets downlevelled, Babel will add a PURE comment to that class and mark it as side-effect and when running terser this will be dropped. However, in this case it will cause a runtime issue as your code is non side-effect free.

```js
function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

function _defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } }

function _createClass(Constructor, protoProps, staticProps) { if (protoProps) _defineProperties(Constructor.prototype, protoProps); if (staticProps) _defineProperties(Constructor, staticProps); return Constructor; }

var t =
/*#__PURE__*/
function () {
  "use strict";

  function t() {
    _classCallCheck(this, t);

    this.example = {};
  }

  _createClass(t, [{
    key: "ngOnInit",
    value: function ngOnInit() {
      /*#__PURE__*/
      (function () {
        function _class() {
          _classCallCheck(this, _class);
        }

        _createClass(_class, null, [{
          key: "modifyObject",
          value: function modifyObject(t) {
            t.test = "TODO";
          }
        }]);

        return _class;
      })().modifyObject(this.example);
    }
  }]);

  return t;
}();
```

My recommendation is to write non side-effect code and use the immutability pattern. Which in your code can be achieved easily. 

Have immutable objects is important as otherwise you will end up with a sync problems between the models and the views, since during Angular's life detection cycle only the object references are matched.


Example: 
```ts
export class ExampleWithStaticMethod {
  static modifyObject(obj: any) {
    return {...obj, test: 'TODO'};
  }
}

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent implements OnInit {
  example = {};

  ngOnInit(): void {
    this.example = ExampleWithStaticMethod.modifyObject(this.example);
  }
}
```

**Comment by rrajewski** [comment]
Thanks for the detailed write up @alan-agius4. In my case however, the static method calls a series of 3rd party library methods that actually perform the modifications.

**Comment by alan-agius4** [comment]
Blocking as it's a bug in Babel and is un-actionable from our end until until this has been solved. 

Important to point out is that this happens when a class get inlined because it's used only once, using the same class multiple times, should also solve the issue.

**Comment by alan-agius4** [comment]
Closing as this is not actionable by the Angular CLI. 

Please file an issue in https://github.com/babel/babel.

Thanks
