### ISSUE TITLE
Suggestion: Add blueprint for modules

### ISSUE THREAD

**Issue by yusijs** [angular/angular-cli#1704]
Specifically:
`ng g module feature-module`

Should create a folder similar to how components did. This way, all other ng generate commands ran under this folder would be added to the feature module instead of the app.module.ts file. 

Example:
`ng g module fancyFeature`

creates:

> fancy-feature/fancy-feature.module.ts

`ng g component fancy-feature/funky-component`

then creates the component as it normally would, but adds the import etc to fancy-feature.module.ts instead of app.module.ts

This would make the application structure easier to follow, and follows the information outlined @ [developer guide](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#feature-modules)

Thank you for your consideration :3

**Comment by filipesilva** [comment]
Closed by https://github.com/angular/angular-cli/pull/1650

**Comment by yusijs** [comment]
<3
