### ISSUE TITLE
Issue when migrating the angular project from V7 to V9

### ISSUE THREAD

**Issue by NishantITRE** [angular/angular-cli#17044]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

i have used the command **ng update --all** 
dependencies have been updated.
then i have tried to run the application using **ng serve** and got the below error in terminal

> An unhandled exception occurred: Could not find the implementation for builder @angular-builders/dev-server:generic        
> See "C:\Users\Admin\AppData\Local\Temp\ng-jHLb5b\angular-errors.log" for further details.

can any one help me to get out of this?

**Comment by alan-agius4** [comment]
`@angular-builders/dev-server:generic` generic is not an official Angular builder. Kindly file an issue in their repo. Thanks.

**Comment by NishanthRE** [comment]
> `@angular-builders/dev-server:generic` generic is not an official Angular builder. Kindly file an issue in their repo. Thanks.

Thanks alan
