### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by mukund720** [angular/angular-cli#17054]
Bug : bug is reported here : https://gitlab.com/gitlab-org/gitlab/issues/207621

![image](https://user-images.githubusercontent.com/11161480/75110108-d4c05100-564f-11ea-8548-778f4a2e95f1.png)

Full Details:

[0KRunning with gitlab-runner 12.8.0-rc1 (12a489c4)
[0;m[0K  on docker-auto-scale 0277ea0f
[0;msection_start:1582450333:prepare_executor
[0K[0KUsing Docker executor with image registry.gitlab.com/tyaitadmin/sample-angular/node_angular_cli ...
[0;m[0KAuthenticating with credentials from job payload (GitLab Registry)
[0;m[0KPulling docker image registry.gitlab.com/tyaitadmin/sample-angular/node_angular_cli ...
[0;m[0KUsing docker image sha256:19d54d18ada1a2efc8abef47d4ba703f62c9a89719a440b9e9902176eec8bbb7 for registry.gitlab.com/tyaitadmin/sample-angular/node_angular_cli ...
[0;msection_end:1582450378:prepare_executor
[0Ksection_start:1582450378:prepare_script
[0KRunning on runner-0277ea0f-project-16168063-concurrent-0 via runner-0277ea0f-srm-1582450274-641b716c...
section_end:1582450382:prepare_script
[0Ksection_start:1582450382:get_sources
[0K[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 50...[0;m
Initialized empty Git repository in /builds/mukundonline/tya-operation/.git/
[32;1mCreated fresh repository.[0;m
From https://gitlab.com/mukundonline/tya-operation
 * [new ref]         refs/pipelines/120279983 -> refs/pipelines/120279983
 * [new branch]      feature/mukund_mt        -> origin/feature/mukund_mt
[32;1mChecking out 47490a6c as feature/mukund_mt...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1582450385:get_sources
[0Ksection_start:1582450385:restore_cache
[0Ksection_end:1582450387:restore_cache
[0Ksection_start:1582450387:download_artifacts
[0Ksection_end:1582450388:download_artifacts
[0Ksection_start:1582450388:build_script
[0K[0KAuthenticating with credentials from job payload (GitLab Registry)
[0;m[32;1m$ unset CI[0;m
[32;1m$ npm install --progress=false[0;m

> uws@9.14.0 install /builds/mukundonline/tya-operation/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> node-sass@4.13.0 install /builds/mukundonline/tya-operation/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.13.0/linux-x64-79_binding.node
Download complete
Binary saved to /builds/mukundonline/tya-operation/node_modules/node-sass/vendor/linux-x64-79/binding.node
Caching binary to /root/.npm/node-sass/4.13.0/linux-x64-79_binding.node

> uglifyjs-webpack-plugin@0.4.6 postinstall /builds/mukundonline/tya-operation/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.13.0 postinstall /builds/mukundonline/tya-operation/node_modules/node-sass
> node scripts/build.js

Binary found at /builds/mukundonline/tya-operation/node_modules/node-sass/vendor/linux-x64-79/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1626 packages from 1366 contributors and audited 10298 packages in 59.2s
found 176 vulnerabilities (8 low, 18 moderate, 149 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
[32;1m$ ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /[0;m
Your global Angular CLI version (8.3.20) is greater than your local
version (1.6.8). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The option '--sourceMap' is not registered with the build command. Run `ng build --help` for a list of supported options.
Node#moveTo was deprecated. Use Container#append.

<--- Last few GCs --->

[260:0x47807b0]   126991 ms: Mark-sweep 1776.9 (1872.4) -> 1768.2 (1874.7) MB, 3206.8 / 0.1 ms  (average mu = 0.110, current mu = 0.055) allocation failure scavenge might not succeed
[260:0x47807b0]   130337 ms: Mark-sweep 1779.0 (1874.7) -> 1771.6 (1879.7) MB, 3189.2 / 0.1 ms  (average mu = 0.079, current mu = 0.047) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13a1179]
    1: StubFrame [pc: 0x1334001]
Security context: 0x08c1b9440921 <JSObject>
    2: /* anonymous */ [0x133a3030a0e9] [/builds/mukundonline/tya-operation/node_modules/@angular/compiler/bundles/compiler.umd.js:~18211] [pc=0x1c8177552917](this=0x3a95d91690e1 <_ApplySourceSpanTransformer map = 0x3a1ce4133341>,0x3a95d9168f59 <LiteralArrayExpr map = 0x12a6bcf1cd71>,0x0f242d4c01c1 <null>)
    3: /* anonymous */ [...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200223.093625.260.0.001.json
Node.js report completed
 1: 0x9f0390 node::Abort() [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 2: 0x9f25e2 node::OnFatalError(char const*, char const*) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 3: 0xb4c04e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 4: 0xb4c3c9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 5: 0xcf9ee5  [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 6: 0xcfa576 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 7: 0xd0978f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 8: 0xd0a615 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
 9: 0xd0d0ac v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
10: 0xcd3b94 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
11: 0x1020cce v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
12: 0x13a1179  [ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /]
/bin/bash: line 102:   260 Aborted                 (core dumped) ng build --prod --aot --sourceMap=false --output-hashing=all --base-href /
section_end:1582450641:build_script
[0Ksection_start:1582450641:after_script
[0Ksection_end:1582450643:after_script
[0Ksection_start:1582450643:upload_artifacts_on_failure
[0Ksection_end:1582450645:upload_artifacts_on_failure
[0K[31;1mERROR: Job failed: exit code 1
[0;m

**Comment by clydin** [comment]
From the log output it appears that the project is using Angular CLI version 1.6.8.
>Your global Angular CLI version (8.3.20) is greater than your local
version (1.6.8). The local Angular CLI version is used.

This version is no longer supported. Please consider updating to a supported version (9.0 being the latest).  If the problem persists after an update, please open a new issue with details from the newer version's failure.

**Comment by mukund720** [comment]
after updating angular cli getting issue The serve command requires to be run in an Angular project, but a project definition could not be found.

> From the log output it appears that the project is using Angular CLI version 1.6.8.
> 
> > Your global Angular CLI version (8.3.20) is greater than your local
> > version (1.6.8). The local Angular CLI version is used.
> 
> This version is no longer supported. Please consider updating to a supported version (9.0 being the latest). If the problem persists after an update, please open a new issue with details from the newer version's failure.

**Comment by mukund720** [comment]
> In My Local System I'm able to make build ... 

> this issue is coming only on GitLab with ci cd process

**Comment by clydin** [comment]
For update guidance please see the following site: https://update.angular.io/#5.0:9.0

**Comment by mukund720** [comment]
> Hey @clydin  issue not resolved after update also ....
>   its not version issue ... 
same build issue coming in my local system also ..after that 
i updated my ng.cmd file 

=====================================
`@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe" --max_old_space_size=8192 "%~dp0\node_modules\@angular\cli\bin\ng" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node --max_old_space_size=8192 "%~dp0\node_modules\@angular\cli\bin\ng" %*
)`
