### ISSUE TITLE
Custom Prefix for Directives

### ISSUE THREAD

**Issue by aggarwalankush** [angular/angular-cli#1706]
Hi, 

Is there any way to use prefix defined in angular-cli.json with directives?
It's recommended in [Angular 2 guidelines](https://angular.io/styleguide#!#02-08)

System details:

- OS
 `Max OSX El Capitan`

- Versions. 
```
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.1.0
os: darwin x64
```
- Repro steps 
`ng g d myDirective`

-Thanks

**Comment by filipesilva** [comment]
We try to be styleguide compliant so this should be addressed.

**Comment by filipesilva** [comment]
@Brocco can you have a look?

**Comment by Brocco** [comment]
Thoughts on whether this prefix should be the same as the one being used for component selectors?

**Comment by filipesilva** [comment]
Good point actually. The style shows a component selector as `toh-hero`, but a directive as `tohValidate`. Core stuff like `ngIf` are also camelCase, so I'd say the prefix should be the same as components but the selector should be camelCase instead.

**Comment by Brocco** [comment]
Directive names do not get "case changed" if a user specifies a name of `myDiReCtIvE` then it currently spits out a selector of `[myDiReCtIvE]` but with this change for this issue they would get `[tohmyDiReCtIvE]` as the selector

**Comment by filipesilva** [comment]
ugh, that is problematic, yes... I don't have a good solution to that tbh :/

**Comment by aggarwalankush** [comment]
@Brocco may be let user specify a flag to not prefix(--np). Also, this flag can be quite useful, User not want to prefix some of the components or directives.
