### ISSUE TITLE
Treeshaking not working as expected in angular 9 when NgModule from a library built using angular 8 is used

### ISSUE THREAD

**Issue by siddiq-rehman** [angular/angular-cli#17062]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

The bug is related to tree shaking unused modules form a custom library in angular 9

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...
I have created a custom library which exports two modules namely First Module and SecondModule, which have one component each FirstComponent and SecondComponent respectively.

I am building the library and installing it in my application. Inside the app module, I have imported the FirstModule and the I am using the first component out of it.

So, Now If I do an AOT build on the sources, I can see the code factories for both the FirstModule, secondModule and their components inside main.js files. Attaching source code for library and application.

[Application.zip](https://github.com/angular/angular/files/4243920/Application.zip)

[Library_sidTest.zip](https://github.com/angular/angular/files/4243911/Library_sidTest.zip)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

Download application, install node_modules, then install sidTest nodemodule present in the same directory using "npm i ./sidTest"

Then do a build "npx ng build --aot". Check the resultant main-es2015.js file.

## 🔥 Exception or Error
<pre><code>

  In main.js file, I could see code for secondModule from the library, even though I have never imported that.
</code>
</pre>

## 🌍  Your Environment

<pre>
**Angular Version:* 9
Library version: Angular 8
<code>

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Can you try adding `"sideEffects": false` to the package.json for the generated library?

For additional information please see: https://angular.io/guide/ivy-compatibility#payload-size-debugging

**Comment by alan-agius4** [comment]
Closing as no further feedback was provided.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
