### ISSUE TITLE
Update from Angular 8 to 9 leads to “ReferenceError: SomeAbstractModelClass is not defined” for production build

### ISSUE THREAD

**Issue by BuZZ-dEE** [angular/angular-cli#17079]
# 🐞 bug report

### Affected Package

 The issue is caused by package: I don't know.

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.0.2

### Description

I have updated an [Angular 8 app to Angular 9][1]. Everything runs fine, if I start the application using `ng serve`, but if I start the app using `ng serve --prod`, I get the following error at runtime.:

## 🔬 Minimal Reproduction

I don't know how to reproduce this issue.

## 🔥 Exception or Error
<pre><code>
ReferenceError: SomeAbstractModelClass is not defined
    at http://localhost:4200/main.js:1:330907
    at Module.zUnb (http://localhost:4200/main.js:1:331001)
    at l (http://localhost:4200/runtime.js:1:552)
    at Object.0 (http://localhost:4200/main.js:1:96)
    at l (http://localhost:4200/runtime.js:1:552)
    at t (http://localhost:4200/runtime.js:1:421)
    at Array.r [as push] (http://localhost:4200/runtime.js:1:293)
    at http://localhost:4200/main.js:1:47
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.1
Node: 10.15.0
OS: linux x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-ng-packagr   0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               9.0.1
@angular-devkit/schematics         9.0.1
@angular/cli                       9.0.1
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1
@schematics/update                 0.900.1
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

https://stackoverflow.com/questions/60174263/update-from-angular-8-to-9-leads-to-referenceerror-someabstractmodelclass-is-n

  [1]: https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by dennisameling** [comment]
Can confirm setting `"emitDecoratorMetadata": false` in tsconfig.json works. Thanks!! 😄

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
