### ISSUE TITLE
ng new error

### ISSUE THREAD

**Issue by MartinM25** [angular/angular-cli#17076]
ENOENT: no such file or directory, mkdir error shown when  i try to create a new angular project

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
