### ISSUE TITLE
Global css file from css preprocessors

### ISSUE THREAD

**Issue by zackporter92** [angular/angular-cli#1707]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OS X El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.2
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I created an application using the webpack cli and used it to convert an application that I made using an older version of the cli.  Previously we had a main.less file that was compiled into a main.css file that we referenced directly in the main index file like so 

<link href="main.css" rel="stylesheet" type="text/css">

Some of that less file is important to the loading screen.  Also some of the routes don't load properly because that css file isn't loaded when they are created.  Is there a way we can have this functionality back in the webpack cli version?

**Comment by delasteve** [comment]
This is probably relevant: https://github.com/angular/angular-cli/pull/1633

Specifically: https://github.com/angular/angular-cli/pull/1633/files#diff-a3cadaef4a5589b80d9986b7dbbdb166R1

**Comment by wceolin** [comment]
@delasteve I've added the following to `angular-cli.json` but it's not working:

```
"additionalEntries": [
  "src/styles.css"
 ]
```

Is there something else I should do?

**Comment by filipesilva** [comment]
Correct, https://github.com/angular/angular-cli/pull/1633 fixes this issue.
