### ISSUE TITLE
Difficulty adding a new route Angular CLI v1.0.0-beta.10

### ISSUE THREAD

**Issue by IpaliboWhyte** [angular/angular-cli#1708]
Below is my package.json 
```
  "dependencies": {
    "@angular/common": "2.0.0-rc.2",
    "@angular/compiler": "2.0.0-rc.2",
    "@angular/core": "2.0.0-rc.2",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.2",
    "@angular/platform-browser": "2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "2.0.0-rc.2",
    "@angular/router": "3.0.0-rc.1",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.26",
    "zone.js": "0.6.12"
  },
```

I am having a lot of issues just creating one new route using my `auth` component generated from ``ng generate component auth``

From the docs, I see that generating a route has been disabled, so i had to do this manually!

Here is my app.component.ts

```
import { Component } from '@angular/core';
import { AuthComponent } from './auth/auth.component';
import { Routes , ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from '@angular/router';

@Component({
  moduleId: module.id,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css'],
  directives: [ROUTER_DIRECTIVES],
  providers: [ROUTER_PROVIDERS]
})
@Routes([
  {path: '/login', component: AuthComponent}
])
export class AppComponent {
  title = 'app works!';
}
```

I keep getting `has no exported mng 'ROUTER_PROVIDERS'` error. Which im guessing has something to do with the router version ?

I have spent quite a lot of time on this already, any ideas ?

Thanks!

**Comment by cre8** [comment]
The router changed, you don't use the `@Routes` notation with 3.0 any more. Check the official docs for the best result:
[Angular Router](https://angular.io/docs/ts/latest/guide/router.html)

**Comment by filipesilva** [comment]
@cre8 is correct, the new router has a different syntax than the one you are using.
