### ISSUE TITLE
Angular 9 build hangs / freezes in production environment on heroku

### ISSUE THREAD

**Issue by PhilippMeissner** [angular/angular-cli#17081]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.x

### Description
When running the following script, the build behaves in three different scenarios, two of which cause the build (and thus deployment) to fail.

1) Everything works just fine (Output of my local machine: https://gist.github.com/PhilippMeissner/ac901fae1022c46859fe08b01b41c5fa)

2) It just stops right before compiling the packages inside `node_modules` (Output of heroku: https://gist.github.com/PhilippMeissner/4a719870ac1dfb91776e4d728c528e69)

2) It stops after compiling the last package inside `node_modules`, then never proceeds (Output of heroku: https://gist.github.com/PhilippMeissner/21e387c544873c4381e74d56338c5c1b)

## 🔬 Minimal Reproduction
Unfortunately I was not able to reproduce this at all, other than on Heroku.
Besides, sometimes it tends to _just work_ on Heroku, but that's like 1 in 50 attempts and so far I can not see any differences in the times it works vs. when it does not work
I tried to disable Ivy along with the AOT build, nothing changed the build-output/outcome.

## 🔥 Exception or Error
No error, it just hangs/freezes.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.3
Node: 10.19.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      9.1.0
@angular/cli                      9.0.3
@angular/http                     7.2.16
@angular/material                 9.1.0
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
Here's my `angular.json`, in case it is relevant (a gist, due to long output): https://gist.github.com/PhilippMeissner/c4c8a5fda397bc54d46cc180df715e2e

tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "importHelpers": true,
    "module": "commonjs",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types",
      "src/lib/types"
    ],
    "paths": {
      "moment": [
        "src/lib/moment/moment"
      ],
      "moment-timezone": [
        "node_modules/moment-timezone/builds/moment-timezone-with-data-2012-2022"
      ]
    },
    "types": [
      "node",
      "webpack-env"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

tsconfig.app.json
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "strict": true,
    "types": [
      "webpack-env"
    ]
  },
  "exclude": [
    "src/test.ts",
    "src/app/testing/**/*.ts",
    "**/*.spec.ts"
  ],
  "files": [
    "main.ts",
    "polyfills.ts"
  ]
}
```

Script to start the build:
```
#!/bin/bash

set -e

cd frontend

# See https://github.com/angular/angular-cli/issues/5618
export NODE_OPTIONS=--max_old_space_size=8192

yarn --pure-lockfile --production=false

yarn run build:heroku
```

If anything else is missing, hit me up.

**Comment by clydin** [comment]
Can you try updating to Node.js 12?  There are significant performance improvements present in newer versions.

**Comment by PhilippMeissner** [comment]
Thanks for the suggestion. There have been issues that prevented us from updating to Node 12, but apparently that's been solved. I updated Node to 12.16.1, unfortunately that did not change the problem at all.

It still keeps hanging right after `[...] Compiling angular-animations : module as esm5`.

**Comment by clydin** [comment]
Can you provide the output of `node -e "console.log(require('os').cpus().length)"` on Heroku?
Also can you try running a build with the `--verbose` flag?

**Comment by PhilippMeissner** [comment]
At some point the build (+ deployment) worked out yesterday once (https://gist.github.com/PhilippMeissner/51039a605dc105e5da2cb9996e91dfa6), so now I can provide a log output after the `node_modules` successfully compiled and were cached: https://gist.github.com/PhilippMeissner/77183ba12088f514658f9a99bc0cb2fc
(Also includes `--verbose --progress=true` flag).

Unfortunately there's still times the build does not finish. This is the output when this happens. Basically it hangs at `92% chunk asset optimization TerserPlugin`. Here's the full log output:
https://gist.github.com/PhilippMeissner/6bd2f7292bd826b1aee25201515685c0
(Also includes `--verbose --progress=true`).

The output of `node -e "console.log(require('os').cpus().length)"` was `2` (Wow, I really thought the machine would be a little more powerful).

**Comment by PhilippMeissner** [comment]
For some reason I can not reproduce this anymore. Thanks for all your input 👍
