### ISSUE TITLE
sass-loader interface is changed, but devkit/build-angular does not pass proper options

### ISSUE THREAD

**Issue by Toktik** [angular/angular-cli#17093]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, the previous version was Angular CLI 8. The issue happens with Angular CLI 9.

### Description
```
"stylePreprocessorOptions": {
  "includePaths": ["libs/common/scss"]
},
```
This will not work anymore, because sass-loader changed the interface, it should look like this: 
```
"stylePreprocessorOptions": {
   "sassOptions": {
      "includePaths": ["libs/common/scss"]
  }
},
```

Please look here: https://github.com/webpack-contrib/sass-loader#sassoptions

Currently, we can't upgrade our app because of this.

**Comment by clydin** [comment]
The loader interface changes were included in the upgrade to sass-loader 8.  Please see the relevant commit for more details: https://github.com/angular/angular-cli/commit/2c8b12f45c6f3cd779e860c809db03059b5754b5

**Comment by Toktik** [comment]
@clydin this is the output of ng version
```
$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.0.3
Node: 10.16.0
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       8.0.1
@angular/cli                       9.0.3
@angular/material                  8.0.1
@angular/material-moment-adapter   8.0.1
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
```

The issue happens when you have configuration as in the first post, and you import something like `@import 'mixins';`

Error is:
```
SassError: Can't find stylesheet to import.
  ╷
1 │ @import 'mixins';
```

It seems related to the webpackImporter from sass-loader.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.  Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
