### ISSUE TITLE
angular.json schema validation broken for styles in Angular CLI 9

### ISSUE THREAD

**Issue by JoeFirebaugh** [angular/angular-cli#17095]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
Yes, this worked with Angular CLI 8.2.3

### Description

 
```
 "styles": [
              "src/styles.scss",
              "./node_modules/codemirror/lib/codemirror.css",
              "./node_modules/codemirror/theme/ambiance.css",
              {
                "input": "src/themes/light/LightTheme.scss",
                "inject": false,
                "bundleName": "LightTheme",
              },
              {
                "input": "src/themes/slate/SlateTheme.scss",
                "inject": false,
                "bundleName": "SlateTheme",
              }
            ],
```
Using the above for styles I get the following error:
`Data path ".styles[3]" should NOT have additional properties(inject).`

The schema says that is valid (and incidentally Webstorm confirms):
```
"extraEntryPoint": {
              "oneOf": [
                {
                  "type": "object",
                  "properties": {
                    "input": {
                      "type": "string",
                      "description": "The file to include."
                    },
                    "bundleName": {
                      "type": "string",
                      "description": "The bundle name for this extra entry point."
                    },
                    "lazy": {
                      "type": "boolean",
                      "description": "If the bundle will be lazy loaded.",
                      "default": false
                    },
                    "inject": {
                      "type": "boolean",
                      "description": "If the bundle will be referenced in the HTML file.",
                      "default": true
                    }
                  },
                  "additionalProperties": false,
                  "required": [
                    "input"
                  ]
                },
                {
                  "type": "string",
                  "description": "The file to include."
                }
              ]
            },
```

Also interestingly enough the `lazy: true` option works and seems to be a workaround for me at the moment.

## 🔬 Minimal Reproduction

Just build any project that uses `inject: false` for any of the styles using the object syntax.

## 🔥 Exception or Error
<pre><code>
Data path ".styles[3]" should NOT have additional properties(inject).
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.3
Node: 13.3.0
OS: darwin x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       8.2.3
@angular/cli                       9.0.3
@angular/material                  8.2.3
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         9.0.2
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.6
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@JoeFirebaugh, thanks for opening the issue. However I am unable to reproduce this locally. Are you using a custom builder by any chance?

If not, can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by JoeFirebaugh** [comment]
Alan, I owe you a couple of apologies.  One, for taking so long to respond... And two, for realizing you are correct.  I am using `ngx-build-plus` in order to turn on `WebpackBuildNotifierPlugin`.   I bet that's the source of the issue and I'll open up a trouble ticket with them.

**Comment by alan-agius4** [comment]
@JoeFirebaugh, no worries 😃
