### ISSUE TITLE
ng update not removing hammer.js from test configuration of angular.json

### ISSUE THREAD

**Issue by naingaungphyo** [angular/angular-cli#17103]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...
ng update is not removing hammer.js from test configuration of angular.json.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
ng update removes this below line from test configuration of angular.json.

> "scripts": ["./node_modules/hammerjs/hammer.min.js"],

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Everything was ok with ng update command, the only problem I had was that I had to remove hammer.js manually from test configuration of angular.json

**Comment by naingaungphyo** [comment]
I think that importing hammer.js inside angular.json is not good (recommended way), but it will be nice if ng update can print out warning about it or informing to delete it manually.

**Comment by alan-agius4** [comment]
@naingaungphyo, hammer.js can be used as described above.


Can you share a minimal reproduction of the error you are seeing?

**Comment by naingaungphyo** [comment]
@alan-agius4 
The error message was 
"An unhandled exception occurred: Script file ./node_modules/hammerjs/hammer.min.js does not exist."

But never mind, I found that migration script of removing hammerjs is not supported for test configuration. It is described [here.](https://github.com/angular/components/blob/master/guides/v9-hammerjs-migration.md#how-does-the-schematic-remove-hammerjs) and [here](https://github.com/angular/components/blob/master/guides/v9-hammerjs-migration.md#how-to-migrate-my-tests) in details.
