### ISSUE TITLE
Use latest typescript (3.8.2)

### ISSUE THREAD

**Issue by andzejsw** [angular/angular-cli#17104]
`ERROR in The Angular Compiler requires TypeScript >=3.6.4 and <3.8.0 but 3.8.2 was found instead.`
I would like, that angular 9 supported latest typescript version, which one now is 3.8.2

**Comment by genuineyehuo** [comment]
@angular-devkit/build-angular this package not compatible with 3.8.2, after the version is forcibly reduced, the project will display this prompt, // error : Can't resolve all parameters for ProfileState: (?).

**Comment by KingDarBoja** [comment]
This is not possible as stated by this [comment](https://github.com/angular/angular/issues/35204#issuecomment-583539606) about how Angular handles TypeScript major versions.

Run ` npm install --save-dev typescript@3.7.5` instead.

**Comment by alan-agius4** [comment]
TypeScript 3.8 support has been added in version 9.1 which is currently available as a pre-release version.

https://github.com/angular/angular-cli/releases/tag/v9.1.0-next.2
