### ISSUE TITLE
angularcli webpack 2 for RC5 unable to run ng new command

### ISSUE THREAD

**Issue by SenthilKumaranC** [angular/angular-cli#1711]
angularcli for RC5 

unable to run ng new command

I am getting this error unable to find porter module.

Cannot find module porter

http://stackoverflow.com/questions/38976107/angular2-need-to-create-angular2-folder-structure-using-latest-angularcli-webp

Please help me,

**Comment by filipesilva** [comment]
You are using NPM2, please upgrade to NPM3 to fix that error.
