### ISSUE TITLE
Undefined ng variable and augury problems when using specific configuration file flag

### ISSUE THREAD

**Issue by Drevoed** [angular/angular-cli#17116]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Previous versions of angular did not have a global `ng` variable available for debugging.

### Description

When serving via `ng serve` the default config file is used and everything is okay, augury detects that angular is running in dev mode and `ng` global variable is available. On the other hand, if I serve the project with specifying configuration file `ng serve --prod=false --configuration=xxxconf --aot=true` augury can't detect that project is in dev mode and `ng` variable is undefined, even though ```isDevMode()``` returns ```true```.

## 🔬 Minimal Reproduction

Run `ng serve` with specifiying a configuration and try to access global `ng` variable.

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.4
Node: 10.15.2
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.4
@angular-devkit/build-angular              0.900.4
@angular-devkit/build-optimizer            0.900.4
@angular-devkit/build-webpack              0.900.4
@angular-devkit/core                       7.3.9
@angular-devkit/schematics                 7.3.9
@angular/cdk                               9.0.1
@ngtools/webpack                           9.0.4
@nguniversal/builders                      9.0.1
@nguniversal/common                        9.0.1
@nguniversal/express-engine                9.0.1
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        7.3.9
@schematics/update                         0.900.4
rxjs                                       6.5.4
typescript                                 3.7.5
webpack                                    4.41.6
</code></pre>

**Comment by Drevoed** [comment]
bump?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

![Screenshot 2020-05-25 at 08 59 24](https://user-images.githubusercontent.com/17563226/82787315-71b8a300-9e66-11ea-98a1-bc575456c4fc.png)
