### ISSUE TITLE
ng update on yarn workspace with migrations

### ISSUE THREAD

**Issue by c-jasonk** [angular/angular-cli#17118]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 Migrations work great for libraries hosted in an npm repository. In a monorepo that uses yarn workspaces, there doesn't seem to be a great way to leverage them. If a shared library provides migrations but that library is consumed via yarn workspaces, that library never shows up in `ng update`. However, migrations can still be run `ng update my-shared-lib --from=1.0.0 --to=2.0.0 --migrate-only`. This is helpful for running shared migrations, but currently requires each migration run in this manner to be manually documented somewhere. If I were to run that in a given workspace, and then someone else later wanted to verify that the migration had been run, there wouldn't be any direct evidence of it. Additionally, when the next version of the shared library is "released" (in this case, version bumped as a result of new migrations being added), there isn't a good way to know what the next --from value should be unless someone else had previously documented the last --to value they used.

### Describe the solution you'd like
 For libraries consumed via yarn workspaces, or possibly for any library whose migrations are run via `--from=x.x.x --to=y.y.y --migrate-only`, it would be great if the most recent --to value was persisted in some manner and then compared against the latest version available. In the scenario above, after running `ng update my-shared-lib --from=1.0.0 --to=2.0.0 --migrate-only` and then updating my-shared-lib to 3.0.0, the result of a subsequent `ng update` might look like:
```
We analyzed your package.json, there are some packages to update:

  Name                               Version                  Command to update
 --------------------------------------------------------------------------------
  my-shared-lib                      2.0.0 -> 3.0.0           ng update my-shared-lib --from=2.0.0 --to=3.0.0 --migrate-only
```

**Comment by alan-agius4** [comment]
Hi, this has the same root cause as https://github.com/angular/angular-cli/issues/14841

Let’s keep tracking it over there.
