### ISSUE TITLE
Broken app: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by MDzyga** [angular/angular-cli#17120]
# 🐞 Bug report

### Command (mark with an `x`)
Command `ng` doesn't work!!!

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] run
- [ ] config
- [x] version

### Is this a regression?
Yes, in version 8.3.25 & 9.0.0 it worked & application was stable.

### Description
My application doesn't work on Azure after upgrading to the latest version of Angular.

## 🔬 Minimal Reproduction
Try to see a login page on my website https://traceabilit-webapp-stage.azurewebsites.net/login.

I build my application on Jenkins executing this script:
`npm run test:ci && sudo node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --configuration dev --deploy-url /manage/ --base-href /manage/`

## 🔥 Exception or Error
<pre><code>
TypeError: Cannot convert undefined or null to object
    at getPrototypeOf (<anonymous>)
    at t.value (Subject.js:81)
    at t.value (Observable.js:28)
    at t.value (core.js:36931)
    at new e (core.js:42527)
    at Object.a [as factory] (core.js:17023)
    at e.value (core.js:16837)
    at e.value (core.js:16598)
    at ue (core.js:905)
    at he (core.js:915)
</code></pre>

## 🌍 Your Environment
Azure Web App - Node 12.3.0
"@angular/animations": "^9.0.4",
"@angular/cdk": "^9.1.0",
"@angular/cli": "^9.0.4",
"@angular/compiler-cli": "^9.0.4",

**Comment by MDzyga** [comment]
After downgrading cli & compiler-cli to 9.0.0 app works

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by MDzyga** [comment]
It can be a bit difficult, because problem exists only on Azure, application locally is working fine. I will try to prepare some repo

**Comment by MDzyga** [comment]
@alan-agius4 
I think I found a bug, I had 1 place with:
`loadChildren: './path/someModule#SomeModule'`
instead of
`loadChildren: import('./path/someModule').then(m => mSomeModule)`

I will let you know when I publish my changes on Azure

**Comment by MDzyga** [comment]
it looks like I resolved my issue.
After publishing on Azure app works fine & stable
