### ISSUE TITLE
Build generates ES5 bundles even though "es5BrowserSupport" is set to false

### ISSUE THREAD

**Issue by dave0688** [angular/angular-cli#17128]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No, because "es5BrowserSupport" didn't exist before.

### Description
I've disabled `es5BrowserSupport` in my `angular.json` file (in `architect.build.options` section of the file), but when I run `ng build --prod` I still see the message in the console while building:

`Generating ES5 bundles for differential loading...`

Also, in my `/dist` folder there's some js-files which indicate that `es5` files are generated (i.e. `polyfilles-es5.sf24fa3d.js`, `main-es5.sdlfjhsfhlecy34.js`.

## 🔬 Minimal Reproduction

run `ng build --prod` with `es5BrowserSupport: false` in `angular.json`.

## 🔥 Exception or Error
Console outputs:

`Generating ES5 bundles for differential loading...`

It should **not** generate `es5` related files.

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.1
Node: 12.7.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/http                     7.2.16
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.8.2
webpack                           4.41.2
</code>
</pre>

**Comment by clydin** [comment]
The `es5BrowserSupport` option is a deprecated option that controls whether ES5 targeted builds will include a separate conditionally loaded polyfill for older browsers.  It was the precursor to full differential loading support.

The Browserslist file is now used to control the behavior of the CLI.  The CLI uses the set of browsers listed in the file to automatically build the appropriate application output that will execute  on the specified browsers.  This allows the support requirements of the application to be used directly when configuring the application.

An example module script only browserslist file (please adjust for application requirements):
```
last 2 Chrome major versions
last 2 iOS major versions
last 2 Safari major versions
```
