### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by M0H3N** [angular/angular-cli#1713]
Hi 
this is my config :
  angular-cli: 1.0.0-beta.10
  node: 4.4.7
  os: win32 x64
during install these errors happened:

 ` ERR! message Unable to read typings for "angular-protractor". You should c
heck the entry paths in "angular-protractor.d.ts" are up to date
typings ERR! caused by Unable to connect to "https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/f9c44651705f
574f6d4258fe5e1c335462bdcc19/angular-protractor/angular-protractor.d.ts"
typings ERR! caused by connect ECONNREFUSED 10.10.34.36:443

typings ERR! cwd D:\project\WebProgramming\MyWorks\angualr.js\app\FirstApp
typings ERR! system Windows_NT 6.3.9600
typings ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\project\\WebProgramming\\MyWorks\\angualr.js\\app\\FisrtApp\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v4.4.7
typings ERR! typings -v 1.3.1

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
FisrtApp@0.0.0 postinstall: `typings install`
Exit status 1`
and after running ng serve this error happened :
The Broccoli Plugin: [Funnel] failed with:

What is the problem ?

**Comment by filipesilva** [comment]
Problem seems to be your connection to some part of typings. We've replaced typings with `@types` in the webpack branch as well, see https://github.com/angular/angular-cli#webpack-preview-release-update for updating instructions.
