### ISSUE TITLE
Empty source map with localization and --watch

### ISSUE THREAD

**Issue by richtems** [angular/angular-cli#17131]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.2

### Description

 When using @angular/localization and building with --watch, the main.js source map is empty.

## 🔬 Minimal Reproduction

```
ng new TestApp
cd .\TestApp\
ng add @angular/localize
```

Add i18n to project in angular.json:

<pre><code>
"projects": {
  ...
  "TestApp": {
    ...
    <i><b>"i18n": {
      "sourceLocale": "en-US",
      "locales": {
        "fr": "src/locale/messages.fr.xlf"
      }
    }</b></i>
    ...
    "architect": {
      "build": {
          ...
          "options": {
            ...
            <i><b>"localize": ["fr"],</b></i>

</code></pre>

`ng xi18n`
copy messages.xlf to "src/locale/messages.fr.xlf"
`ng build --watch`

Now the content of dist/TestApp/fr/main.js.map is:
`{}`

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.4
Node: 10.15.1
OS: win32 x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.4
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              9.0.4
@angular-devkit/schematics        9.0.4
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Might be related to #16526 ?

**Comment by HitkoDev** [comment]
This also happens without `--watch`, as long as `localize` option is enabled. However, chunks without any localized content still have the correct source map. I believe https://github.com/angular/angular/pull/33123 was supposed to solve this, but it's been closed and there's not yet an alternative proposed.
