### ISSUE TITLE
Need a way to build smaller javascript files / to set maximum size for generated js files

### ISSUE THREAD

**Issue by realharry** [angular/angular-cli#17135]
# 🚀 Feature request

It'll be nice to be able to control maximum size of the generated javascript files in some way, e.g., via a command line flag.

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I'm currently trying to set up an Angular SSR app on AWS Lambda + ALB. Unfortunately, there is a response size limit of 1Mb between ALB and Lambda. (https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html). Except for a trivial app, all my apps include at least one JS file that are larger than 1Mb. Sometimes it's `main-...js` files or it's `vendor-...js` files depending on the `--vendor-chunk`.

This is somewhat related to https://github.com/angular/angular-cli/issues/16866, but this is a request independent of any other problems. (I'm currently using cli v9.0.4, and enableIvy:false setting doesn't make much difference.) I never knew there was 1Mb limit when I started building for ALB+Lambda, and there will be many situations (currently unknown) that would prevent successful deployment of Angular apps in many different production environments.

At this point, there seems to be no workaround.

### Describe the solution you'd like

Something like `--max-js-size = 516k` will be nice to control the maximum size of the generated JS files. Instead of generating 1 main or 1 vendor files, they should be divided into multiple files, each no bigger than 516k, for instance.

### Describe alternatives you've considered

Or, alternatively, if we can control the number of generated JS files, that'll be useful as well. For example, `--main-js-files=3` will divide the main js files into 3 files instead of one.

**Comment by clydin** [comment]
Thank you for the feature request.  However, this is not something the Angular CLI is considering for inclusion at this time.
In production mode for a new application, the main file is roughly ~220KB uncompressed (vendor is combined into main for production).  If the main file starts to approach 1MB, the recommended practice is to introduce lazy routing to break the application into smaller functional segments.
Also of potential use in the above situation is to leverage compression before sending the file.  Brotli would be preferred but gzip would also be a solid option.  Both of these now have wide browser support: gzip (everywhere) & brotli (https://caniuse.com/#feat=brotli).  The main file for a new project compressed with brotli is ~57KB.
