### ISSUE TITLE
ng commands should warn (or fail) on package.json and node_modules mismatch

### ISSUE THREAD

**Issue by bjowes** [angular/angular-cli#17132]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
(might apply to other commands too)

### Description
When multiple developers are working on the same application, it commonly occurs that one developer adds or updates a npm package used by the application and pushes the change. When another developer pulls that change, package.json is updated but node_modules is not. To fix this, the second developer should run `npm install` but this is often forgotten. This can lead to unexpected behavior when using `ng test` or `ng serve` - sometimes the error is quickly identified but sometimes it 'kind of works' and the second developer loses a lot of time tracking it down. 

### Describe the solution you'd like
When executing a ng command (in particular the ones marked above), ng should check if package.json matches node_modules. If not, it should output a clear warning, or fail the command.

### Describe alternatives you've considered
An alternative could be setting up an alias for ng that does the above check, but it would be much more user friendly if this was built in.

**Comment by alan-agius4** [comment]
Hi @bjowes, thanks for opening this feature request. 

This request currently doesn’t fall in scope of the CLI.

We are very cautious on which features we add as we’d need to support and maintain them after they get developed.
