### ISSUE TITLE
Add baseHref setting to the sourceLocale

### ISSUE THREAD

**Issue by santhony7** [angular/angular-cli#17144]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 I don't think this is possible now or I have not found a good solution. You added the ability to specify a baseHref in each locale during i18n but no way to specify the baseHref for the sourceLocale. Not sure how else to specifiy a baseHref="/" for en. Compiler always makes it '/en/'.

### Describe the solution you'd like
 Change the schema to allow an object for sourceLocal that has a property of baseHref.

### Describe alternatives you've considered
 The only workaround I have found it to create two builds: One for english and one for all other locales.

**Comment by clydin** [comment]
This is currently supported with v9.  As an example:
```
      "i18n": {
        "sourceLocale": {
          "baseHref": "/my-base-href/",
          "code": "en"
        }
      },
```
The schema can be found here: https://github.com/angular/angular-cli/blob/6f3ee0a9029efbb02d0450505c37367b2831b115/packages/angular/cli/lib/config/schema.json#L393

**Comment by santhony7** [comment]
Thank you! I swear I couldn't find that anywhere. Great job guys!
