### ISSUE TITLE
ng-update exceeds peerDependency bounds

### ISSUE THREAD

**Issue by rcketscientist** [angular/angular-cli#17143]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
We did not have issues while lagging behind 6/7/8 releases.

### Description

 A clear and concise description of the problem...
packageA depends on ng8 and material8.
If I `ng update packageA` it will attempt to update Angular to 9.  I can avoid this by temporarily removing material as a dependency.  Something about material flushes out a bug in ng-cli.  I've submitted a bug in the material repo, but they make a convincing argument that the bug is actually in cli:
https://github.com/angular/components/issues/18536?email_source=notifications&email_token=AA6W5LUTQN4ZVQYEQLHDJYTRFASJJA5CNFSM4KXKGJNKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENF5OLA#issuecomment-592172844

## 🔬 Minimal Reproduction

packageA depends on ng8 and material8.
`ng update packageA`

## 🔥 Exception or Error
<pre><code>

                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/common" (requires "^8.1.1", would install "9.0.1")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/core" (requires "^8.1.1", would install "9.0.1")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/cdk" (requires "^8.2.3", would install "9.0.0")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/material" (requires "^8.2.3", would install "9.0.0")
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/cdk" (requires "^8.2.3", would install "9.0.0").
                  Package "@keysight/alloy" has an incompatible peer dependency to "@angular/material" (requires "^8.2.3", would install "9.0.0").
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires ">=3.1 < 3.6", would install "3.7.5").

Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.24
Node: 12.16.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.24
@angular-devkit/build-angular      0.803.24
@angular-devkit/build-ng-packagr   0.803.24
@angular-devkit/build-optimizer    0.803.24
@angular-devkit/build-webpack      0.803.24
@angular-devkit/core               8.3.24
@angular-devkit/schematics         8.3.24
@angular/cdk                       8.2.3
@angular/cli                       8.3.24
@angular/material                  8.2.3
@ngtools/webpack                   8.3.24
@schematics/angular                8.3.24
@schematics/update                 0.803.24
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

**Comment by rcketscientist** [comment]
Any update on this one?  We're adopting schematics in more and more projects and workarounds for this oddity are really reducing the convenience of schematics.

**Comment by celesteking** [comment]
This basically means `ng update` is broken (for several years) when you're using @angular/material in your project.

**Comment by rcketscientist** [comment]
I'm no longer with that team (or working with angular), but IIRC what I did was remove `@angular/material` as a _schematic  group_? (forget the actual package.json key) which effectively stops the ng-update schematic cascade during `ng update`.  It puts the onus downstream on updating material itself, but it got our schematics working again.  Hopefully, that's helpful.

The reason we were tightly coupled to begin with was that the library consisted mostly of material extensions, so it made sense to cascade the ng-update ourselves (until we hit the bug).

Sorry, thought I had posted an update about that, but no longer have that code base to confirm.

**Comment by celesteking** [comment]
There's no `"schematics"` in my angular.json or package.json, so I guess it's something else. I'm more interested in angular/material migration , not in package update per se, as I can do that myself manually with npm.

**Comment by alan-agius4** [comment]
@celesteking, you can use the `—-migrate-only` option if you already installed the correct version of the package.

Ex:

```
ng update @angular/material —-migrate-only —-from 6  -—to 7
```

**Comment by celesteking** [comment]
I'm not sure it would work as I expect it to. It's still trying to pull latest version.
```
$ ng update @angular/material  --from 6  --to 7
                  Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/cdk" (requires "^7.0.0-rc.0", would install "10.2.5").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/compiler" (requires ">=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0" (extended), would install "11.0.0-rc.0").
                  Package "@angular/flex-layout" has an incompatible peer dependency to "@angular/common" (requires ">=7.0.0-rc.0", would install "11.0.0-rc.0").
                  Package "codelyzer" has an incompatible peer dependency to "@angular/core" (requires ">=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0" (extended), would install "11.0.0-rc.0").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/animations" (requires "7.x" (extended), would install "11.0.0-rc.0").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "zone.js" (requires "^0.8.26", would install "0.10.3").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/forms" (requires "7.x" (extended), would install "11.0.0-rc.0").
                  Package "@swimlane/ngx-charts" has an incompatible peer dependency to "@angular/platform-browser-dynamic" (requires "7.x" (extended), would install "11.0.0-rc.0").
                  Package "@angular/http" has an incompatible peer dependency to "@angular/platform-browser" (requires "7.2.15" (extended), would install "11.0.0-rc.0").
Incompatible peer dependencies found. See above.
$ ng update  @angular/material --migrate-only  --from 6  --to 7

  ✓  Angular Material update complete

  ⚠  Please check the output above for any issues that were detected but could not be automatically fixed.
$
```
Had it run migrations 6>7 or 6>latest(10)? I have no idea and no log was provided.

**Comment by alan-agius4** [comment]
`ng update` should no longer exceed `peerDependency` since version 9.
