### ISSUE TITLE
@types, VSCode and Typescript Code Completion

### ISSUE THREAD

**Issue by origin1tech** [angular/angular-cli#1715]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**El Capitan**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
**angular-cli: 1.0.0-beta.11-webpack.2                                                                                         
node: 4.4.4** 

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**None**

4. The log given by the failure. Normally this include a stack trace and some
   more information.
**None**

5. Mention any other details that might be useful.

Code completion for @types seems to be hit or miss within VSCode. For example moment works fine and is recognized when imported and you get full code completion of methods etc. Whereas lodash does not. 

The tsconfig.json seems to be defined correctly with the **typeRoots** and if you create a reference inline within the file typescript resolves it fine and you get code completion/intellisense.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by origin1tech** [comment]
going to move this to typescript issues. Not sure why I posted it here Pressure this is a VSCode typescript issue and has little to do with the CLI. 

Perhaps it should be left open  resolution via issue over at typescript then post link to that issue. Leave it up to you. Close if you see fit...

**Comment by filipesilva** [comment]
This is a VSCode issue, yes. The best I can do is to refer you to https://github.com/Microsoft/vscode/issues/9232.

**Comment by origin1tech** [comment]
@filipesilva right why on earth I posted it here is beyond me...just wasn't thinking.

+1 on the link was actually headed that way thx.
