### ISSUE TITLE
Can you add [(ngModel)]support back into reactive forms? 

### ISSUE THREAD

**Issue by mfduar8766** [angular/angular-cli#17155]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular-cli/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hi @mfduar8766, this should still work. If you are experiencing an issue kindly file a new in https://github.com/angular/angular with a minimal reproduction that shows the problem.

Thanks.

**Comment by mfduar8766** [comment]
> Hi @mfduar8766, this should still work. If you are experiencing an issue kindly file a new in https://github.com/angular/angular with a minimal reproduction that shows the problem.
> 
> Thanks.

@alan-agius4 Hi, thanks for the reply. I am asking this bc I keep getting warning in my app saying that ngmodel is deprecated for v7+ so I’m not sure if I can use this in my forms.

**Comment by alan-agius4** [comment]
You can read
https://angular.io/api/forms/FormControlName on alternatives to the
deprecated behaviour.
