### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vicevini** [angular/angular-cli#17151]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I have this problem 

 npm install -g @angular/cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
C:\Users\vicev\AppData\Roaming\npm\ng -> C:\Users\vicev\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng

> @angular/cli@9.0.4 postinstall C:\Users\vicev\AppData\Roaming\npm\node_modules\@angular\cli
> node ./bin/postinstall/script.js

+ @angular/cli@9.0.4
updated 1 package in 9.576s

![image](https://user-images.githubusercontent.com/48629758/75920515-4c576280-5e3e-11ea-992e-9e6629e065de.png)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
