### ISSUE TITLE
How can I generate other files while calling new components in Angular CLI

### ISSUE THREAD

**Issue by h4mit** [angular/angular-cli#17167]
How can I generate any files except the base files while generating new components? For example:

```ng generate component my-component```

Routinely the following files would be generated:

```my-component.component.html

my-component.component.scss

my-component.component.ts

my-component.component.spec.ts
```

But I want to generate other files, too. For example:

```my-component.component.html

my-component.component.scss

my-component.component.ts

my-component.component.spec.ts

i18n(folder)
    en.json
    es.json

**Comment by alan-agius4** [comment]
Hi @h4mit, to generate addition files, you'd need to extend the default schematic. Something similar to https://github.com/angular/angular-cli/blob/ad9d73d0d223fddfef5ff5795bef595ff8f3225d/packages/schematics/angular/application/index.ts#L362-L386

Closing as this is a support request. 

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
