### ISSUE TITLE
Cannot find app.module.ts file in project generated by CLI

### ISSUE THREAD

**Issue by NathanLawrence** [angular/angular-cli#1716]
I can't believe I'm going to be _that guy_ that drives everyone nuts and posts a question in the issues, but I've done absolutely everything I can think of and still can't find the app.module.ts file for my project -- in fact, I can't find any files at all in the project that contain an import for NgModule at all!

I know I'm being stupid about this -- in fact, I know I'm being so stupid about this that the reason I haven't found anything is that nothing else has been stupid enough for there to be a searchable record of an issue like this. Does anybody have a second to explain my mistake?

angular-cli: 0.0.39
node: 5.3.0
os: darwin x64 (OS X 10.11.6)

**Comment by TheLarkInn** [comment]
Now I noticed that you have 0.0.39 reported in your version. (Thank you this was very helpful to potentially identify your issue). I would recommend that you update the angular-cli to the latest version `npm install angular-cli@webpack -g` 

You can refer to our [WEBPACK UPGRADE docs](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md) to properly migrate. 

Also if you create a new app you will find the app.module.ts located in the `app` folder of your src.
