### ISSUE TITLE
terminal progress on multiple lines on small terminal width

### ISSUE THREAD

**Issue by capc0** [angular/angular-cli#17169]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes. Worked with Angular 8.1.0

### Description

 A clear and concise description of the problem...

regression of https://github.com/angular/angular-cli/issues/14623

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.5
Node: 10.16.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      7.3.7
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI as we use Webpack's ProgressPlugin. Please contact the author(s) of the Webpack project or file an issue on their issue tracker. This might be related related to https://github.com/webpack/webpack/issues/9221

Thanks.
