### ISSUE TITLE
Node.js version 11.3 not supported by Angular 9 

### ISSUE THREAD

**Issue by thomasoreilly** [angular/angular-cli#17162]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [x] generate
- [x] add
- [x] update
- [x] lint
- [x] xi18n
- [x] run
- [x] config
- [x] help
- [x] version
- [x] doc

### Is this a regression?

I'm not sure if there is an issue with Angular versions prior to 9.

### Description

Fails to run ng commands.

## 🔬 Minimal Reproduction

1. Install node.js 11.3.
2. Install Angular CLI 9
3. Try to create a new application. 

## 🔥 Exception or Error
<pre><code>

Node.js version v11.3.0 detected.
The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
</code></pre>

## 🌍 Your Environment
Note: ng version doesn't work on node.js 11.3. The below output is from downgrading to node.js 10.15
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 10.15.0
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.1
@angular-devkit/build-angular      0.900.1
@angular-devkit/build-ng-packagr   0.900.1
@angular-devkit/build-optimizer    0.900.1
@angular-devkit/build-webpack      0.900.1
@angular-devkit/core               9.0.1
@angular-devkit/schematics         9.0.1
@angular/cdk                       8.2.3
@angular/cli                       9.0.1
@ngtools/webpack                   9.0.1
@schematics/angular                9.0.1
@schematics/update                 0.900.1
ng-packagr                         9.0.0
rxjs                               6.5.3
typescript                         3.7.5
webpack                            4.41.6

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @thomasoreilly, that is indeed correct and expected.

Angular CLI requires a current, active LTS, or maintenance LTS version of Node (https://angular.io/guide/setup-local#nodejs).  which version 11 isn't. 

Node.JS 11 is no longer supported by the Node.Js team as after six months, odd-numbered releases (9, 11, etc.) becomes unsupported. More info: https://nodejs.org/en/about/releases

I recommend you update to Node 12+

**Comment by thomasoreilly** [comment]
Odd versioning on node.js part. Thanks for the update @alan-agius4.
