### ISSUE TITLE
Allow globally loaded javascript libs

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#1717]
Some javascript libraries need to be loaded on the global scope, especially older ones. A great, common example is bootstrap, which needs jquery to be globally available.

Different build systems have different ways to allow this. Webpack has [several alternatives](https://webpack.github.io/docs/shimming-modules.html#importing) to shimming modules, and [so does SystemJS](https://github.com/systemjs/systemjs/blob/master/docs/module-formats.md#custom-globals).

Angular-CLI needs to provide a way to load these files in order to provide interop with the simplest way of loading javascript files.

**Comment by iamyojimbo** [comment]
In case anyone really needs this NOW, in Webpack, the solution is to do:

`window['jQuery'] = require('jquery')`

I don't know if this works with SystemJS too.

**Comment by filipesilva** [comment]
@iamyojimbo very good advice, thank you!

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1747 adds instructions on how to use libs that need global scope using @iamyojimbo's technique.

It should be enough for now but if people start having more problems with libs, we can add more functionality to address global scripts.

**Comment by filipesilva** [comment]
We looked into it a bit more and decided to take another approach to the global libs issue. We decided to provide a config item to specify javascript files that should be loaded outside of the module ecosystem, as if they were in a script tag.

We feel this should make it easier for people to add libs since they won't have to poke around for the exports, and also make it more compatible with all kinds of libs.

**Comment by iamyojimbo** [comment]
@filipesilva by, "poke around the the exports", what do you mean exactly?

**Comment by filipesilva** [comment]
Using your method, you need to know the exact names of the needed exports. For `jquery` this is `jQuery` and `$`. These are well known enough but for many libraries that isn't so clear, so a user would have to look into the source to figure out what exports they should put in `window`.
