### ISSUE TITLE
Use command "ng g component com1" but generate file is empty

### ISSUE THREAD

**Issue by itning** [angular/angular-cli#17183]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
When I use ``ng g component com1`` command and then 
```shell
G:\ProjectData\WebstormProjects\AngularTest>ng g component com1
CREATE src/app/com1/com1.component.html (19 bytes)
CREATE src/app/com1/com1.component.spec.ts (614 bytes)
CREATE src/app/com1/com1.component.ts (267 bytes)
CREATE src/app/com1/com1.component.css (0 bytes)
UPDATE src/app/app.module.ts (472 bytes)
```
But something went wrong when I open ``com1.component.ts`` file.

![bug1](https://raw.githubusercontent.com/itning/FilePool/master/images/angular_20200310_1.png)

And file property：

![bug2](https://raw.githubusercontent.com/itning/FilePool/master/images/angular_20200310_2.png)

**Using other component names does not cause this state**

## 🌍 Your Environment
```shell
"@angular/cli": "~9.0.5",
```

**Comment by alan-agius4** [comment]
It seems that your environment is not configured properly, as the `.ts` are trying to be opened by media player instead of an editor. This happens because windows just interprets the `.ts` extension as `MPEG-2 TS`.

Changing your `Open with` setting to open `ts` files to an editor will fix the problem.

**Comment by itning** [comment]
> It seems that your environment is not configured properly, as the `.ts` are trying to be opened by media player instead of an editor. This happens because windows just interprets the `.ts` extension as `MPEG-2 TS`.
> 
> Changing your `Open with` setting to open `ts` files to an editor will fix the problem.

No.I use text editor tool to open it.

**Comment by itning** [comment]
You see this file size is 0

**Comment by itning** [comment]
> It seems that your environment is not configured properly, as the `.ts` are trying to be opened by media player instead of an editor. This happens because windows just interprets the `.ts` extension as `MPEG-2 TS`.
> 
> Changing your `Open with` setting to open `ts` files to an editor will fix the problem.

![gif](https://raw.githubusercontent.com/itning/FilePool/master/images/20200310_174012.gif)

**Comment by alan-agius4** [comment]
Can you please provide the full output of `ng version`?

**Comment by itning** [comment]
> Can you please provide the full output of `ng version`?

```shell
G:\ProjectData\WebstormProjects\AngularTest>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 12.14.1
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
```

**Comment by alan-agius4** [comment]
Also, taking a look at the video again, in the file explorer it shows that the file is `1kb` However, upon checking the properties it states that it's `0 bytes`.

Can you kindly share your project on github and link it here? Thanks.

**Comment by itning** [comment]
> Also, taking a look at the video again, in the file explorer it shows that the file is `1kb` However, upon checking the properties it states that it's `0 bytes`.
> 
> Can you kindly share your project on github and link it here? Thanks.

**I can not add generate files to git.**

```shell
G:\ProjectData\WebstormProjects\AngularTest>git add src/app/com1
warning: could not open directory 'src/app/com1/': No such file or directory
```
You can see this gif.
Generate files all empty when I create component with name "comxxx" 
But generate other name component such as ``bbb`` it work（normal）.
![gif2](https://raw.githubusercontent.com/itning/FilePool/master/images/20200310_183408.gif)

**Comment by itning** [comment]
> Also, taking a look at the video again, in the file explorer it shows that the file is `1kb` However, upon checking the properties it states that it's `0 bytes`.
> 
> Can you kindly share your project on github and link it here? Thanks.

I test ``ng g`` command
```shell
ng g component com1 --> not work
ng g component com1 --> not work
ng g component com1 --> not work
ng g component com1 --> not work
ng g component com1 --> not work
ng g component com1 --> not work
ng g component com1 --> not work
```

**Comment by itning** [comment]
I test ``ng g component``
```shell
ng g component com0 --> it work
ng g component com1 --> not work
ng g component com2 --> not work
ng g component com3 --> not work
ng g component com4 --> not work
ng g component com5 --> not work
ng g component com6 --> not work
ng g component com7 --> not work
ng g component com8 --> not work
ng g component com9 --> not work
ng g component com10 --> it work
ng g component coma --> it work
ng g component comaa --> it work
ng g component aaa0 --> it work
ng g component a0 --> it work
```

**Comment by alan-agius4** [comment]
Hi @itning, in Windows  `COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9` among others are reserved.

More info here: https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN

Closing as this is not a CLI bug but an OS restriction.

**Comment by itning** [comment]
> Hi @itning, in Windows `COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9` among others are reserved.
> 
> More info here: https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN
> 
> Closing as this is not a CLI bug but an OS restriction.

I see, thank you for answering my questions
