### ISSUE TITLE
angular-cli@1.0.0-bata.11-webpack.2 unable to create sub-component correctly on Windows

### ISSUE THREAD

**Issue by doggy8088** [angular/angular-cli#1719]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
> angular-cli: 1.0.0-beta.11-webpack.2
> node: 6.2.2
> os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
> `ng g c aa`
> `ng g c aa/bb`

  > The `app.module.ts` will produce a error syntax on BbComponent module path. 

  > ![image](https://cloud.githubusercontent.com/assets/88981/17722813/b728ed7e-6467-11e6-8d7c-9e610e86cf33.png)

4. The log given by the failure. Normally this include a stack trace and some
   more information.
> unable to build.

5. Mention any other details that might be useful.
> ![image](https://cloud.githubusercontent.com/assets/88981/17722875/119e2fb2-6468-11e6-8964-bb6ebc455e0e.png)
> ![image](https://cloud.githubusercontent.com/assets/88981/17722901/5354e2f2-6468-11e6-86e8-7d4f860ab367.png)

**Comment by filipesilva** [comment]
Thank you for the very detailed report! We'll get on this bug asap.

**Comment by shairez** [comment]
@hansl please it to me, I'll have a go

**Comment by shairez** [comment]
@hansl well bummer, just finished writing a fix and then I saw this one - 
https://github.com/angular/angular-cli/pull/1961

I wrote the replace on the actual blueprint, but the above PR fixes the issue in a better place
:)

**Comment by hansl** [comment]
@shairez If the author of that PR does not answer to my comments before next week (say, Monday afternoon), you're welcome to make a PR of your own. That PR has a bug and I cannot let it in.

**Comment by shairez** [comment]
@hansl I'm sure he'll answer soon, if not, I'm on it.
