### ISSUE TITLE
Angular 7 - ng build (or ng build --prod) In Linux Environment, the styles are not getting detected by import command

### ISSUE THREAD

**Issue by kishoreaoe** [angular/angular-cli#17195]
Dear Team,
I am running a Angular 7.3.9 version of Angular and My project structure is as given below:

![image](https://user-images.githubusercontent.com/6896519/76401901-ae125200-6393-11ea-85dd-a6073790000e.png)

When i run ng build in LINUX environment, i am getting below errors (compiler is not able to resolve the import path given in the project components) :

ERROR in ./src/styles.scss (./node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/lib/loader.js??ref--14-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import "~./../../utilities/variables";
^
      File to import not found or unreadable: ~./../../utilities/variables.
      in /var/lib/jenkins/foldername/projectname/src/styles/ccm-theme/_global.scss (line 1, column 1)

In the component, i am using variables.scss by importing like this.

@import "../../styles/utilities/_variables";

So the variables (_variables.scss) is not getting resovled in LINUX environment but working fine in windows.

After various searching thru blogs, have added below code but no luck.

 "stylePreprocessorOptions": {
              "includePaths": ["src/styles.scss"]
            },

Thanks and Regards,
Kishore Kumar. K

**Comment by alan-agius4** [comment]
Hi, seems to me that the import in `_global.scss` is incorrect and it should be `@import "../utilities/variables";`

If the problem persists, can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
