### ISSUE TITLE
Unknown options 'loglevel', 'package-lock'

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#17193]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know

### Description

I had tried to add PWA to my NG app. Following [the docs](https://angular.io/guide/service-worker-getting-started#adding-a-service-worker-to-your-project) I should simply run one command but this fails.

## 🔬 Minimal Reproduction

1. `ng new ise-app --package-manager pnpm --style scss --viewEncapsulation ShadowDom --routing --strict`
2. `ng add @angular/pwa --verbose`

## 🔥 Exception or Error

```
❯ ng add @angular/pwa --verbose
Locating potential npmrc files:
Trying '/Users/marvinheilemann/.nvm/versions/node/v12.16.1/etc/npmrc'...not found.
Trying '/Users/marvinheilemann/.npmrc'...found.
Trying '/Users/.npmrc'...not found.
Trying '/Users/marvinheilemann/.npmrc'...found.
Trying '/Users/marvinheilemann/Development/.npmrc'...not found.
Trying '/Users/marvinheilemann/Development/Additive/.npmrc'...not found.
Trying '/Users/marvinheilemann/Development/Additive/Kunden/.npmrc'...not found.
Trying '/Users/marvinheilemann/Development/Additive/Kunden/Frauenhofer/.npmrc'...not found.
Trying '/Users/marvinheilemann/Development/Additive/Kunden/Frauenhofer/ise-app/.npmrc'...not found.
Installing packages for tooling via pnpm.
An unhandled exception occurred: ERROR  Unknown options 'loglevel', 'package-lock'
Package install failed, see above.
See "/private/var/folders/yz/pntm5xh11mjb3ckzvf10ql180000gn/T/ng-znp5Jg/angular-errors.log" for further details.
```

## 🌍 Your Environment

```
Angular CLI: 9.0.5
Node: 12.16.1
OS: darwin x64

Angular: 9.0.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       <error>
@angular-devkit/build-angular   0.900.5
@angular-devkit/core            <error>
@angular-devkit/schematics      <error>
@angular/cli                    9.0.5
@schematics/angular             <error>
@schematics/update              <error>
rxjs                            6.5.4
typescript                      3.7.5
```

**Anything else relevant?**

**Comment by lucas-labs** [comment]
I'm having this error too, trying to add @angular/localize in a project with pnpm as its package manager. It throws the following error: "Unknown option 'loglevel'"

```
$ ng add @angular/localize --verbose
Locating potential npmrc files:
Trying 'C:\Program Files\nodejs\etc\npmrc'...not found.
Trying 'C:\Users\lucas\.npmrc'...found.
Trying 'C:\Users\.npmrc'...not found.
Trying 'C:\Users\lucas\.npmrc'...found.
Trying 'C:\Users\lucas\Desktop\.npmrc'...not found.
Trying 'C:\Users\lucas\Desktop\devprojects\.npmrc'...not found.
Trying 'C:\Users\lucas\Desktop\devprojects\angular\.npmrc'...not found.
Trying 'C:\Users\lucas\Desktop\devprojects\angular\my-project\.npmrc'...not found.
Installing packages for tooling via pnpm.
An unhandled exception occurred: ERROR  Unknown option 'loglevel'
Package install failed, see above.
See "c:\tmp\ng-gKpuxp\angular-errors.log" for further details.
````

@muuvmuuv did you find any workaround?

**Comment by muuvmuuv** [comment]
No net yet @lucas-labs. I just skipped this package for now because I have other stuff that also needs to be done. I have also switched back to npm because of several issue I had with pnpm in Angular. Try that too and see if that works. I guess Angular-Cli needs better pnpm support.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
