### ISSUE TITLE
The Schematic workflow failed. See above.

### ISSUE THREAD

**Issue by csrahulram** [angular/angular-cli#17198]
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.3.25

### Description

I have ubuntu system and the configuration as follows
OS Version : Ubuntu 18.04.4 LTS
Memory      : 7.5 GiB
Processor   : Intel® Core™ i5-6200U CPU @ 2.30GHz × 4
Graphics     : Intel® HD Graphics 520 (Skylake GT2)
GNOME      : 3.28.2
OS Type      : 64-bit
Disk             : 983.4 GB

## 🔬 Minimal Reproduction

Its a fresh system
1. Install NodeJS from ubuntu app store 
2. Select the stable version of node - v12.16.1 - stable
3. Install 'npm i -g @angular/cli@latest'
4. Run 'ng new my-app'
5. The code creates the folder and stops after few mins with below error. Tried several times the issue persist.

## 🔥 Exception or Error
<pre><code>
<pre>sudo ng new my-app
<font color="#4E9A06">?</font> <b>Would you like to add Angular routing?</b> <font color="#06989A">Yes</font>
<font color="#4E9A06">?</font> <b>Which stylesheet format would you like to use?</b> <font color="#06989A">SCSS   [ https://sass-lang.com/</font>
<font color="#06989A">documentation/syntax#scss                ]</font>
<font color="#4E9A06">CREATE</font> formbuilder-web/README.md (1031 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/.editorconfig (246 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/.gitignore (631 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/angular.json (3727 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/package.json (1292 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/tsconfig.json (489 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/tslint.json (1953 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/browserslist (429 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/karma.conf.js (1027 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/tsconfig.app.json (210 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/tsconfig.spec.json (270 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/favicon.ico (948 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/index.html (300 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/main.ts (372 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/polyfills.ts (2835 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/styles.scss (80 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/test.ts (753 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/assets/.gitkeep (0 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/environments/environment.prod.ts (51 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/environments/environment.ts (662 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/app/app-routing.module.ts (246 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/app/app.module.ts (393 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/app/app.component.scss (0 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/app/app.component.html (25755 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/app/app.component.spec.ts (1086 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/src/app/app.component.ts (220 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/e2e/protractor.conf.js (808 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/e2e/tsconfig.json (214 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/e2e/src/app.e2e-spec.ts (648 bytes)
<font color="#4E9A06">CREATE</font> formbuilder-web/e2e/src/app.po.ts (301 bytes)
<font color="#CC0000">✖</font> Package install failed, see above.
<font color="#EF2929"><b>The Schematic workflow failed. See above.</b></font>
</pre></code></pre>

## 🌍 Your Environment
<pre><code>

<pre>
<font color="#CC0000">     _                      _                 ____ _     ___</font>
<font color="#CC0000">    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|</font>
<font color="#CC0000">   / △ \ | &apos;_ \ / _` | | | | |/ _` | &apos;__|   | |   | |    | |</font>
<font color="#CC0000">  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |</font>
<font color="#CC0000"> /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|</font>
<font color="#CC0000">                |___/</font>
<font color="#CC0000">    </font>

Angular CLI: 9.0.5
Node: 12.16.1
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.5
@angular-devkit/core         9.0.5
@angular-devkit/schematics   9.0.5
@schematics/angular          9.0.5
@schematics/update           0.900.5
rxjs                         6.5.3
    
</pre>

</code></pre>

**Anything else relevant?**

Using default Terminal.

**Comment by JayChase** [comment]
I don't think this is angular-cli specific it is being caused by the sass package. I'm running `ng n test` on windows which give a verbose error:

`2701 http fetch GET 304 https://registry.npmjs.org/sass 55ms (from cache)
2702 silly fetchPackageMetaData error for sass@1.23.3 Unexpected end of JSON input while parsing near '...\ncwmoW47aRoIrxuhYgKu'`

I get the same error in an empty node project. It looks like npm has a problem with the json returned from https://registry.npmjs.org/sass. I was on npm v 6.13.4 and updated to 6.14.2 to see if it fixed the issue but no luck. 

`ncwmoW47aRoIrxuhYgKu` is part of the dist.npm-signature.

**Comment by JayChase** [comment]
`npm cache clean --force
npm i -g @angular/cli`

has fixed the issue for me.

**Comment by csrahulram** [comment]
Hey JayChase,

I have tried your solution but didn't helped me. I found the OS is blocking the Schematic workflow due to some permission level for my user account. Will try to reset the OS and try again as root user.

Thanks for your reply.

**Comment by csrahulram** [comment]
This issue is with the Hard Ware of my PC. Not Angular CLI issue. Thanks for the help.

**Comment by Ewaoche** [comment]
hello guys, please am having same issue -- not able to install angular/cli

**Comment by clydin** [comment]
If the package installation failed (which is done by executing the system's node package manager: npm, yarn, etc.), then you can try to run `ng new my-app --skip-install` to generate the application without that step.  From there you can attempt to manually run the package manager (`npm install`/`yarn`/etc.) from within the new project.  For assistance with any failures at that point, please direct inquiries to the package manager's project.
npm: https://github.com/npm/cli/issues
yarn: https://github.com/yarnpkg/yarn/issues

**Comment by doanchungtu95** [comment]
I'm a newbie. I'm trying to create my first angular app and I got this problem too.
the error in log file: "error Unexpected end of JSON input while parsing near '...f1rUtt/W63ltUP8dva/XP'"
latest node version, latest npm version, latest angular cli version, when "ng new myapp", I choose options: add router, cscc.
I try to "npm cache clear --force", reinstall angular cli, etc, but it doesn't work. Still got the error message:
"The Schematic workflow failed. See above."
"npm ERR! Unexpected end of JSON input while parsing near '...f1rUtt/W63ltUP8dva/XP'"
Does somebody have solution ?

**Comment by vijaynt** [comment]
I also have same issue. Any fix?

**Comment by bhargava-9963** [comment]
CREATE bhar/e2e/src/app.po.ts (301 bytes)
| Installing packages...warning @angular-devkit/build-angular > less > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @angular-devkit/build-angular > stylus > css-parse > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @angular-devkit/build-angular > stylus > css-parse > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @angular-devkit/build-angular > stylus > css-parse > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @angular/cli > universal-analytics > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning protractor > webdriver-manager > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
error An unexpected error occurred: "https://registry.yarnpkg.com/@angular/core/-/core-9.1.0.tgz: unexpected end of file".
× Package install failed, see above.
The Schematic workflow failed. See above.

**Comment by grajsb** [comment]
> This issue is with the Hard Ware of my PC. Not Angular CLI issue. Thanks for the help.

Were you by any chance able to fix the issue, I understand you mentioned it's a hardware issue but I am curious to know more as I have the same issue and multiple re-installations isn't helping me. Any response is highly appreciated. Thank you in advance.

**Comment by michelrisucci** [comment]
@csrahulram same issue here **using SNAP distribution of node/npm** (tested using channels for versions 12 and 13). **Switched to debian standard apt node/npm 12 LTS distribution (via apt - https://github.com/nodesource/distributions/blob/master/README.md#debinstall)** and the error has gone.

**Comment by RobbManganelly** [comment]
have the same issue.....any help??? I've tried all the previous solutions. i can't create a new app. I'm using Ubuntu 18.04 and node 12.16.1 and angular 9.1.1 and npm 6.14.4

**Comment by doanchungtu95** [comment]
> I'm a newbie. I'm trying to create my first angular app and I got this problem too.
> the error in log file: "error Unexpected end of JSON input while parsing near '...f1rUtt/W63ltUP8dva/XP'"
> latest node version, latest npm version, latest angular cli version, when "ng new myapp", I choose options: add router, cscc.
> I try to "npm cache clear --force", reinstall angular cli, etc, but it doesn't work. Still got the error message:
> "The Schematic workflow failed. See above."
> "npm ERR! Unexpected end of JSON input while parsing near '...f1rUtt/W63ltUP8dva/XP'"
> Does somebody have solution ?

after clean uninstall node, npm, angular
rm -rf /usr/local/bin/npm /usr/local/lib/dtrace/node.d;
rm -rf ~/.npm;
rm -rf /usr/local/bin/node;
rm -rf /usr/local/lib/node_modules/npm/;
and install all again by homebrew (not use node installer), I don't get above error anymore
brew install node;
export NODE_PATH='/usr/local/lib/node_modules'
brew install angular-cli
but after that I get new error 
"error Response timeout while trying to fetch"
Maybe I have some network error...but I can access the link by browser. I don't know why, but try again with some differences
I remove project and create again but skip install like these
1. ng new angular --skip-install
2. cd angular
3. npm i
everything's fine. And try
ng serve
The angular app start successfully!
--------
Hope these things can help :D

**Comment by devajitgupta** [comment]
Have same issue Its working try it 

ng new angular --skip-install
cd angular
npm i
everything's fine. And try
ng serve
The angular app start successfully!

**Comment by devajitgupta** [comment]
ng new angular --skip-install
cd angular
npm i
everything's fine. And try
ng serve
The angular app start successfully!
Thanx to everyone

**Comment by candevelops** [comment]
same issue "The Schematic workflow failed."

**Comment by OhiraKyou** [comment]
I also encountered this issue.

### Solutions attempted

- `npm cache clean --force`
- `ng new my-app --skip-install` followed by `npm i`
- changing the codelyzer dependency from `^5.1.2` to `5.2.1` as suggested [here](https://stackoverflow.com/questions/60692589/angular-9-cant-create-a-new-project).

### Versions

- `node -v`: v12.16.1
- `npm -v`: 6.13.4
- **OS**: Windows 10 64-bit

I use nvm to manage npm installations.

**Comment by LordKenzo** [comment]
> `npm cache clean --force`
> `npm i -g @angular/cli`
> 
> has fixed the issue for me.

worked for me! 
Tahnks

**Comment by griosb** [comment]
I use, the last versions components Angular, i had the similarity problem, i solve with increment space HD disk, "21370 error nospc ENOSPC: no space left on device, mkdir 'C:\Proyectos\angular\angular-crud\node_modules\.staging\toidentifier-ff0bcd7f'" thanks everyone

**Comment by amiruln** [comment]
> `npm cache clean --force`
> `npm i -g @angular/cli`
> 
> has fixed the issue for me.

Thank you this is helpful :)

**Comment by Flave1** [comment]
devajitgupta 



> > I'm a newbie. I'm trying to create my first angular app and I got this problem too.
> > the error in log file: "error Unexpected end of JSON input while parsing near '...f1rUtt/W63ltUP8dva/XP'"
> > latest node version, latest npm version, latest angular cli version, when "ng new myapp", I choose options: add router, cscc.
> > I try to "npm cache clear --force", reinstall angular cli, etc, but it doesn't work. Still got the error message:
> > "The Schematic workflow failed. See above."
> > "npm ERR! Unexpected end of JSON input while parsing near '...f1rUtt/W63ltUP8dva/XP'"
> > Does somebody have solution ?
> 
> after clean uninstall node, npm, angular
> rm -rf /usr/local/bin/npm /usr/local/lib/dtrace/node.d;
> rm -rf ~/.npm;
> rm -rf /usr/local/bin/node;
> rm -rf /usr/local/lib/node_modules/npm/;
> and install all again by homebrew (not use node installer), I don't get above error anymore
> brew install node;
> export NODE_PATH='/usr/local/lib/node_modules'
> brew install angular-cli
> but after that I get new error
> "error Response timeout while trying to fetch"
> Maybe I have some network error...but I can access the link by browser. I don't know why, but try again with some differences
> I remove project and create again but skip install like these
> 
> 1. ng new angular --skip-install
> 2. cd angular
> 3. npm i
>    everything's fine. And try
>    ng serve
>    The angular app start successfully!
> 
> Hope these things can help :D

Does it resolve total or do i have to still go through the procedure to create new Angular App

**Comment by michaellee8** [comment]
> @csrahulram same issue here **using Ubuntu SNAP distribution of node/npm** (tested using channels for versions 12 and 13). **Switched to debian standard apt node/npm 12 LTS distribution (via apt - https://github.com/nodesource/distributions/blob/master/README.md#debinstall)** and the error has gone.

I also got this issue and solved by your way. Probably because of the snap permissions issue.

**Comment by Akhi1** [comment]
For those who tried everything including 
```
npm cache clean --force
npm install -g @angular/cli
ng new <project-name> --skip-install
cd <project-name>
npm install
```

I have tried everything found online and nothing worked except the following
```
npm cache clean --force
npm update
ng new <project-name>
```


Thank!

**Comment by bhaskarreddy463** [comment]
npm cache clean --force
npm uninstall -g @angular/cli
remove the files from %temp% and temp and prefetch and restart the system and then install the 
npm install -g @angular/cli
ng new <project-name>
it worked from me............

Thanks

**Comment by RamCse39** [comment]
Eventually it works.
npm cache clean --force
npm i -g @angular/cli

**Comment by rodolfocoding** [comment]
> `npm cache clean --force`
> `npm i -g @angular/cli`
> 
> corrigiu o problema para mim.

Obrigado. Essa funcionou perfeitamente pra mim.

**Comment by DivanVanZyl** [comment]
> `npm cache clean --force`
> `npm i -g @angular/cli`
> 
> has fixed the issue for me.

This worked for me. But does anyone know WHY this works?

**Comment by clydin** [comment]
When you see npm errors similar to the following (copied from above),
```
Unexpected end of JSON input while parsing near '...\ncwmoW47aRoIrxuhYgKu'
```
it generally means npm either downloaded something incorrectly or npm's cache was somehow corrupted.  By forcing the cache to be cleaned, you are emptying the cache so that a new download will occur next time the package is installed.
These errors are not Angular CLI specific and are rather related to the npm command line utility.

**Comment by prakashharvani** [comment]
> `npm cache clean --force`
> `npm i -g @angular/cli`
> 
> has fixed the issue for me.

Its also Worked For Me..

**Comment by irfanit93** [comment]
> `npm cache clean --force`
> `npm i -g @angular/cli`
> 
> has fixed the issue for me.

Worked Windows  OS

> `npm cache clean --force`
> `npm i -g @angular/cli`
> 
> has fixed the issue for me.

Worked in WIndows OS
