### ISSUE TITLE
img in html has no hash

### ISSUE THREAD

**Issue by lihuabest** [angular/angular-cli#17214]
![微信截图_20200313161123](https://user-images.githubusercontent.com/1559817/76602344-aeeae580-6545-11ea-8f3f-3168f6d5122e.png)

only image in scss as background can has hash, img in html load from assets/image absolute has no hash, but how to get hash?

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/3415
