### ISSUE TITLE
The Array.includes polyfill is not added to the polyfills-es5.ts file

### ISSUE THREAD

**Issue by giri7io** [angular/angular-cli#17217]
This is duplicate of https://github.com/angular/angular-cli/issues/14815

The fix isn't provided by cli yet.

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

The previous versions don't have the Differential Loading concept

### Description

When updating from 7 to 8:
The angular schematic that does the migration drops all polyfills of array functions

https://github.com/angular/angular-cli/blob/9c4da54b63ed2fe526355c937952aaba3b888497/packages/schematics/angular/migrations/update-8/drop-es6-polyfills.ts#L33

but the angular 8 cli polyfills doesn't include the polyfill
`import 'core-js/modules/es.array.includes';`

https://github.com/angular/angular-cli/blob/9c4da54b63ed2fe526355c937952aaba3b888497/packages/angular_devkit/build_angular/src/angular-cli-files/models/es5-polyfills.js#L37

the workaround is manually adding the missing polyfill to polyfills.ts.

looking for a fix from angular team.

**Comment by clydin** [comment]
`array.includes` is not part of ES6 (ES2015) and was not previously nor currently polyfilled by the CLI.  It is rather part of ES2016 as defined [here](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-array.prototype.includes).  For core-js 2.x, it was located at `core-js/es7/array` which is not in the list to drop and should have been retained when migrating.

**Comment by giri7io** [comment]
@clydin thanks for the explanation. :)
