### ISSUE TITLE
ERROR in ./src/app/app.module.ngfactory.js Module not found: Error: Can't resolve '@angular/cdk/a11y' in <Path -to-the-main-application>\src\app resolve '@angular/cdk/a11y' Parsed request is a module

### ISSUE THREAD

**Issue by shikha-ai** [angular/angular-cli#17219]
Angular CLI: 9.0.3
Node: 10.13.0     
OS: win32 ia32    

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic    
... router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------        
@angular-devkit/architect          0.900.3
@angular-devkit/build-angular      0.900.3
@angular-devkit/build-ng-packagr   0.900.3
@angular-devkit/build-optimizer    0.900.3
@angular-devkit/build-webpack      0.900.3
@angular-devkit/core               9.0.3
@angular-devkit/schematics         9.0.3
@angular/cdk                       9.1.0
@angular/cli                       9.0.3
@angular/material                  9.1.0
@ngtools/webpack                   9.0.3
@schematics/angular                9.0.3
@schematics/update                 0.900.3
ng-packagr                         9.0.1
rxjs                               6.5.3
typescript                         3.7.5
webpack                            4.41.2

I get the above error on installing and building the Angular library with aot flag in an Angular application. I initially thought it's an issue with Angular material, but I get the same set of errors while building another Angular library in another Angular application for angular/fontawesome library.
I have created a prototype of this application.  
github.com/shikha-ai/angular is where I have pushed my Angular library code and 
github.com/shikha-ai/testapplication is where I have pushed my main application code.

**Comment by alan-agius4** [comment]
Hi @shikha-ai, is this still an issue?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
