### ISSUE TITLE
ng new use more than 10 minutes (windows 10, terminal run as administrator)

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#1721]
Hi,

1. OS?  windows 10

2. Versions: 
angular-cli: 1.0.0-beta.11-webpack.2 (I think with other version too)
node: 5.4.0
os: win32 x64

5. Detail: 
ng new first-app finish after 11 minutes, is this normal ?
I run WebStorm as administrator (nothing change)
I also run windows10 terminal as administrator and to new project with ng new... it's same ! 
Very very long until finish, I calculate time: exactly 11mn
reasonable pc, reasonable internet connexion, only chrome and webstorm are running, idea? Maybe windows10 ?

**Comment by gelidus** [comment]
That is because all npm dependencies are being downloaded.

**Comment by istiti** [comment]
thanks but I know that, I think new project did with ng init produce very poor and very litle package file, so I think this have to be more faster than 11min. Am i wrong ? 

I remember : **I think, I have reasonable pc, reasonable internet connexion, only chrome and webstorm are running, idea? Maybe windows10 ?**

**Comment by monojack** [comment]
you can use `-lc` flag to link to the `angular-cli` global package and skip downloading it again. This will probably reduce the amount of time to ~5min

**Comment by istiti** [comment]
@monojack thanks it taks 1m30'' hehe
