### ISSUE TITLE
ng new <project_name> issue

### ISSUE THREAD

**Issue by sujitrs** [angular/angular-cli#17225]
### Command (mark with an `x`)

- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Not sure

### Description

 A clear and concise description of the problem...
when ng new <project_name> is executed, it displays below error

npm ERR! Unexpected end of JSON input while parsing near '...qBaKrHcp0BI39s21+YtEW'
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sujeets\AppData\Roaming\npm-cache\_logs\2020-03-15T13_16_33_333Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

Content of log file
============

2585 silly saveTree +-- tslint@5.18.0
2585 silly saveTree +-- typescript@3.7.5
2585 silly saveTree `-- zone.js@0.10.2
2586 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...qBaKrHcp0BI39s21+YtEW'
2586 verbose stack     at JSON.parse (<anonymous>)
2586 verbose stack     at parseJson (D:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
2586 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
2586 verbose stack     at runMicrotasks (<anonymous>)
2586 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2587 verbose cwd E:\_angular\_practise\project\my-new-project-four
2588 verbose Windows_NT 10.0.15063
2589 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--quiet"
2590 verbose node v12.16.1
2591 verbose npm  v6.13.4
2592 error Unexpected end of JSON input while parsing near '...qBaKrHcp0BI39s21+YtEW'
2593 verbose exit [ 1, true ]

## 🔬 Minimal Reproduction
ng new my-app

## 🔥 Exception or Error
<pre><code>
npm ERR! Unexpected end of JSON input while parsing near '...qBaKrHcp0BI39s21+YtEW'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sujeets\AppData\Roaming\npm-cache\_logs\2020-03-15T13_16_33_333Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

Content of log file
============

2585 silly saveTree +-- tslint@5.18.0
2585 silly saveTree +-- typescript@3.7.5
2585 silly saveTree `-- zone.js@0.10.2
2586 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...qBaKrHcp0BI39s21+YtEW'
2586 verbose stack     at JSON.parse (<anonymous>)
2586 verbose stack     at parseJson (D:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
2586 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
2586 verbose stack     at runMicrotasks (<anonymous>)
2586 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2587 verbose cwd E:\_angular\_practise\project\my-new-project-four
2588 verbose Windows_NT 10.0.15063
2589 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--quiet"
2590 verbose node v12.16.1
2591 verbose npm  v6.13.4
2592 error Unexpected end of JSON input while parsing near '...qBaKrHcp0BI39s21+YtEW'
2593 verbose exit [ 1, true ]
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.6
Node: 12.16.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.6
@angular-devkit/core         9.0.6
@angular-devkit/schematics   9.0.6
@schematics/angular          9.0.6
@schematics/update           0.900.6
rxjs                         6.5.3
</code></pre>

**Comment by clydin** [comment]
This appears to be problem with npm and not with the Angular CLI. 

Please have a look at the [fixing npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm CLI issue tracker](https://github.com/npm/cli/issues), or open a new issue in that issue tracker if the problem you are experiencing is not known.
