### ISSUE TITLE
Component inside another component is not rendered using webpack CLI production packaging

### ISSUE THREAD

**Issue by nhenneaux** [angular/angular-cli#1722]
Hi,

When I include a component in another component, the `ng serve` command renders the sub-component while `ng serve --prod` does not render it. The same problem occurs when using the bundle created by command `ng build --prod`.

1. OS? Windows 7

2. Versions. 
(node:4412) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: win32 x64

3. how to reproduce ?
The Angular CLI base application (using ng new) can be used with the following changes.

Change app.component.ts with the following content.

```
import { Component } from '@angular/core';
import { SubComponent } from './sub.component';

@Component({
directives: [
        SubComponent
    ],
  selector: 'app-root',
  template: `
<h1>
  {{title}}
</h1>
<sub></sub>`
})
export class AppComponent {
  title = 'app works!';
}
```
Create a new file sub.component.ts with the following content.

```
import { Component } from '@angular/core';

@Component({
  selector: 'sub',
 template: '<div>This is not render using --prod flag</div>'
})
export class SubComponent {
}
```
Then run `ng serve` and then `ng serve --prod`, the first one render SubComponent while the second one does not render it.
I have created a GitHub repository with the file to reproduce ([here](https://github.com/nhenneaux/ng2-cli-webpack-subcomponent)).

I tried to ask if I am missing something on [stackoverflow](https://stackoverflow.com/questions/38974848/angular2-component-inside-another-component-is-not-rendered-using-cli-production) but it seems it is a problem with cli ?

**Comment by kylecordes** [comment]
This problem is already fixed (or rather, worked around) in CLI master. You can follow the instructions in the README to work with the in-development code if you need -prod working again now, or wait for the next NPM-published version.

(There are various other issues here and angular/angular about the underlying problem.)

**Comment by nhenneaux** [comment]
It works using master.

Thanks for your comment.

**Comment by BikashDas19** [comment]
Hi, 
I have the similar issue.
Could you please provide me the solution for this.

Regards,
Bikash
