### ISSUE TITLE
Generated library does not support use of directives (*ngFor) in template

### ISSUE THREAD

**Issue by seanthomastima** [angular/angular-cli#17227]
# 🐞 Bug report

- [x] generate

### Is this a regression?
Based on Github search this issue has been causing problems since at least version 6.

### Description
Cannot use directives such as *ngFor in template in library.
## 🔬 Minimal Reproduction
ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib

Modify template code in my-lib.component.ts to:
```
template: `
    <div *ngFor="let item of items">
      my-lib works!
    </div>
  `,
```

component:
```
items: string[] = [];
```
## 🔥 Exception or Error
No directive is matched on attribute ngFor

## 🌍 Your Environment
Angular CLI: 8.3.25
Node: 12.14.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.25
@angular-devkit/build-angular      0.803.25
@angular-devkit/build-ng-packagr   0.803.25
@angular-devkit/build-optimizer    0.803.25
@angular-devkit/build-webpack      0.803.25
@angular-devkit/core               8.3.25
@angular-devkit/schematics         8.3.25
@angular/cli                       8.3.25
@ngtools/webpack                   8.3.25
@schematics/angular                8.3.25
@schematics/update                 0.803.25
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**
There several solutions mentioned on GitHub, I have not found one that works for me. The expectation is that a generated library should work after generation.

**Comment by petebacondarwin** [comment]
Note that the `ngFor` directive is exported from the `CommonModule` found in `@angular/common`. You must import this into the generated library's `MyLibModule`:

```
@NgModule({
  declarations: [MyLibComponent],
  imports: [
    CommonModule
  ],
  exports: [MyLibComponent]
})
export class MyLibModule { }
```

The skeleton generated by `ng generate library ...` does not include this by default.

**Comment by petebacondarwin** [comment]
Closing as this works as expected.

**Comment by seanthomastima** [comment]
Hi Pete
Thank you for the suggestion. This does not work for me. When I add CommonModule I receive the error: Class CommonModule is not an Angular module 
I look forward to hearing your suggestion.
Kind Regards
Sean

**Comment by seanthomastima** [comment]
After playing some more and ignoring the errors I now have a build that works. I still have errors, but these may be IDE (Webstorm) related.
Thank you for your help.
