### ISSUE TITLE
Error while using typescript 3.8 export aliases

### ISSUE THREAD

**Issue by TomTomB** [angular/angular-cli#17231]
# 🐞 bug report

### Description

Using typescript 3.8 export aliases produces an error while building.
Happens with ivy enabled as well as disabled.

## 🔬 Minimal Reproduction
1. Clone the error repo https://github.com/TomTomB/named-exports-issue
2. Run `npm i` 
3. Run `ng serve`
4. Look inside the terminal output

## 🔥 Exception or Error
<pre><code>ERROR in ./src/app/stuff/index.ts 1:9
Module parse failed: Unexpected token (1:9)
File was processed with these loaders:
 * ./node_modules/@ngtools/webpack/src/index.js
You may need an additional loader to handle the result of these loaders.
> export * as fromFoo from './foo';
</code></pre>

## 🌍  Your Environment
Angular CLI: 9.1.0-next.3
Node: 12.13.0
OS: win32 x64

Angular: 9.1.0-next.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0-next.3
@angular-devkit/build-angular     0.901.0-next.3
@angular-devkit/build-optimizer   0.901.0-next.3
@angular-devkit/build-webpack     0.901.0-next.3
@angular-devkit/core              9.1.0-next.3
@angular-devkit/schematics        9.1.0-next.3
@angular/cli                      9.1.0-next.3
@ngtools/webpack                  9.1.0-next.3
@schematics/angular               9.1.0-next.3
@schematics/update                0.901.0-next.3
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by troywweber7** [comment]
Is there a workaround for this?

**Comment by KingDarBoja** [comment]
Habing same issue as author, setting the module flag as `"ES2015"` will fix it if not using lazy loading, which does break with this change :/ Subscribing to this issue to know when it is fixed.

**Comment by brianpooe** [comment]
Any news yet on this?

**Comment by alan-agius4** [comment]
This should be fixed in Webpack 5 (https://github.com/webpack/webpack/pull/11117), which is currently in opt-in preview in Angular CLI 11. 

See #18820 for more information on how to opt-in Webpack 5.
