### ISSUE TITLE
LazyLoading External Angular Cli application into the new Angular cli application(Shell Application)

### ISSUE THREAD

**Issue by NishanthRE** [angular/angular-cli#17238]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hi guys,
            I have stucked in one task which is need to lazy load the external angular cli application into other angular cli application. i have lookinto microfront end architecture but it is not suitable for me. Because i need to handle routing from the shell application. 

please share your ideas for my queries:

          1. External application should get builded and i need to import this module in shell application. Is there any ways to acheive this?
          2. how to handle routing from the shell application?

Am waiting for your response.

Thanks in advance.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
