### ISSUE TITLE
Cant find promise + typings is not installed + configure ngrx errors

### ISSUE THREAD

**Issue by stavalfi** [angular/angular-cli#1723]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**win 7 64 bit**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

**angular-cli 1.0.0-beta 11-webpack.2
node: 4.4.7
npm : 3.10.3
os:win32 x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

First I installed angular cli : 'npm install -g angular-cli@webpack' and then I created the project using 'ng new app-name'.

5. Mention any other details that might be useful.

**# I post a very detailed question on stackoverflow with all the errors and what I tyied to do.
http://stackoverflow.com/questions/38980180/how-to-configure-angular-cli-project-for-rc5**

I can't develope anything with all those errors. 
Any help will be great!

**Comment by deebloo** [comment]
@stavalfi what version of npm are you using?

**Comment by stavalfi** [comment]
npm: 3.10.3

**Comment by clydin** [comment]
`typings` is no longer used.  types are install via `npm install @types/<library_name>`.  Until the next release of the CLI, you'll also need to add the library name to the `types` array in `tsconfig.json`.

Also, the CLI uses typescript 2.0 features and I'm not sure if webstorm has support yet.

**Comment by stavalfi** [comment]
Thank for the quick repley clydin.

1. I don't have much experience with most of the configurations so I'm not familiar with 'types'. Can you specify what should I do excatly so the errors will go away?
2. Webstorm supports typescript : https://blog.jetbrains.com/webstorm/2016/07/webstorm-2016-2/

Many thanks,
stav.

**Comment by deebloo** [comment]
@types is used instead of typings, and yes webstorm supports typescript but which version? for example in vscode you have to edit your workspace settings to point to the locally installed version of TS

**Comment by deebloo** [comment]
also the ngrx issue may be tied to sourcemaps in the ngrx projects. I am using it in mine and I get a warning but the app compiles and works fine

**Comment by stavalfi** [comment]
@deebloo  Can you tell what do add or to upload your initial project?

**Comment by filipesilva** [comment]
There's two parts to this issue:
- The errors you are seeing in webstorm are due to the CLI using `typescript@2.0.0`, while we Webstorm is still using `typescript@1.8.x`. The errors will go away once you update the version of typescript that Webstorm uses, but I can't help you there since I don't use Webstorm.
- The errors you are getting in `ngrx` are due to a sourcemap issue. It was solved by https://github.com/angular/angular-cli/pull/1673.
