### ISSUE TITLE
Styles Property: node_modules not taken in account with pnpm 

### ISSUE THREAD

**Issue by frederikdekegel** [angular/angular-cli#17239]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
I do not know

### Description
When using pnpm as a packagemanager on a Windows 10 machine, paths to node_modules in the styles property of the buildoptions are missing from the result of the build or serve.

## 🔬 Minimal Reproduction
An Angular project that uses pnpm as a packagemanager. Add a lib like font-awesome
 and link the styles file of that lib in Styles property of the app
<pre><code>
    "my-app": {
      "projectType": "application",
...
      "architect": {
        "build": {
..
          "options": {
...
            "styles": [
...
              "node_modules/font-awesome/css/font-awesome.min.css",
...
            ]
          }
        }
      }
    }
</code></pre>

## 🔥 Exception or Error
In the example above, i would expect font-awesome.min.css to the included in the styles.css outputfile.

## Cause
When using ngx-build-plus, I was able to find out that when doing a require.resolve() of the related paths of the styles property in webpack config solves the problem.

Ex.
require.resolve(C:\my-project\node_modules\font-awesome\css\font-awesome.min.css)

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.25
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.23
@angular-devkit/build-angular      0.803.25
@angular-devkit/build-ng-packagr   0.803.25
@angular-devkit/build-optimizer    0.803.25
@angular-devkit/build-webpack      0.803.25
@angular-devkit/core               8.3.23
@angular-devkit/schematics         8.3.23
@angular/cli                       8.3.25
@ngtools/webpack                   8.3.25
@schematics/angular                8.3.23
@schematics/update                 0.803.25
ng-packagr                         5.7.1
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

**Anything else relevant?**
Packagemanager: pnpm
OS: windows 10

**Comment by nokutu** [comment]
I'm also able to reproduce it on Linux and MacOS.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
