### ISSUE TITLE
Update migrations do not respect tab spacing

### ISSUE THREAD

**Issue by ericis** [angular/angular-cli#17240]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

Project tab spacing was not respected when upgrading from version `8.x` to `9.x` using the command:
`ng update @angular/core @angular/cli`

## 🔬 Minimal Reproduction

1. Create an angular project using version `8.x`
2. Format your project with preferred tab spacing (e.g. configure `.editorconfig` or install Prettier and configure `.prettierrc`)
3. Format files to use the configuration (e.g. 4 indent spaces)
4. Run `ng update @angular/core @angular/cli` to upgrade to version `9.x`
5. Notice that modified files have changed the tab spacing back to 2 spaces

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.6
Node: 12.11.1
OS: win32 x64

Angular: 9.0.6
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@ngtools/webpack                  9.0.6
@schematics/angular               8.3.25
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

- Using [VS Code](http://code.visualstudio.com/) editor
- Using `indent_size = 4` in [`.editorconfig`](https://editorconfig.org/)
- Using `"tabWidth": 4,` in [`.prettierrc`](https://prettier.io/docs/en/configuration.html)

**Comment by ericis** [comment]
Related to, but different from issue #10777

**Comment by alan-agius4** [comment]
Hi @ericis, let's continue tracking this feature request here #10777. Currently the `.editorconfig` is not used by the CLI and formatting is currently at the discretion of the developer.
