### ISSUE TITLE
`ng update` says "project has been updated to v9" even if already on v9

### ISSUE THREAD

**Issue by gkalpak** [angular/angular-cli#17256]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No idea.

### Description

While updating [angular.io][1] from Angular 9.0.0 to 9.1.0-next.5 (as part of angular/angular#36145), using `ng update @angular/core --next`, I got the following message at the end (which is a little confusing -and likely unintended- since I was already on v9):

> Your project has been updated to Angular version 9!
> For more info, please see: https://v9.angular.io/guide/updating-to-version-9

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0-next.4
Node: 12.15.0
OS: win32 x64

Angular: 9.1.0-next.5
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0-next.4
@angular-devkit/build-angular     0.901.0-next.4
@angular-devkit/build-optimizer   0.901.0-next.4
@angular-devkit/build-webpack     0.901.0-next.4
@angular-devkit/core              9.1.0-next.4
@angular-devkit/schematics        9.1.0-next.4
@angular/cdk                      9.1.3
@angular/cli                      9.1.0-next.4
@angular/material                 9.1.3
@ngtools/webpack                  9.1.0-next.4
@schematics/angular               9.1.0-next.4
@schematics/update                0.901.0-next.4
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

[1]: https://github.com/angular/angular/tree/fb92f5de1adc8dccbb947a09b34cb1bcc6b41e7f/aio

**Comment by gkalpak** [comment]
cc @filipesilva

**Comment by dgp1130** [comment]
Alan looked into this recently, should have the necessary context.
