### ISSUE TITLE
ng new in angular 9.0.6 takes forever

### ISSUE THREAD

**Issue by ashokbohra2012** [angular/angular-cli#17252]
installed node 10.19.0 and angular cli 9.0.6. and tried building a project with ng new <bla bla>. It has been showing installing packages for last 2 hours. 
Before this I had already tried the same with node 12 as well with all options suggested like --skip-git etc. It was giving error for incomplete json parsing near anonymous... so downgraded node as suggested in some other thread.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
