### ISSUE TITLE
Base href overridden by locale config

### ISSUE THREAD

**Issue by floreks** [angular/angular-cli#17260]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This is a potential regression, as the issue occurred after migration from angular v8 to angular v9. There might be however a way to configure i18n framework somehow to omit it.

### Description

Prior to angular v9, localization did not impact the `baseHref`. Currently, such a tag is always added to the `index.html`. 
```html
<base href="..."/>
```
Previously we did not use it at all to easily allow deploying the application on sub-paths, such as `example.com/kubernetes-dashboard`. This worked without any issues. Right now it will not work due to this tag which we cannot omit.

We want the localized build to be selected by the backend based on `Accept-Language` header instead of `/<locale-code>` path. That's why our requirement is to have all requests coming from the same base path.

This is our [angular.json](https://github.com/kubernetes/dashboard/blob/master/angular.json#L11). Right now, it has to define `/` as `baseHref` to avoid `/<locale-code>` path logic.

Configuring dynamic `baseHref` based on a path is not an option right now as any changes to `base` tag in `index.html` are overridden during the build.

Is there any way to avoid adding `base` tag during the build, but still build localized version of the application, or somehow make `baseHref` build final path as a relative path and not as an absolute path?

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.6
Node: 12.6.0
OS: linux x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.1
@angular/cli                      9.0.6
@angular/flex-layout              9.0.0-beta.29
@angular/http                     8.0.0-beta.10+1.sha-a28b3e3
@angular/language-service         9.0.6
@angular/localize                 9.0.6
@angular/material                 9.1.1
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by clydin** [comment]
You can specify an HTML base href for each locale if the common default behavior does not meet the project specific requirements.  In this case, it appears that an empty base HREF is desired.

```
        "locales": {
          "fr": {
            "translation": "i18n/fr/messages.fr.xlf",
            "baseHref": ""
          }
        }
```

**Comment by floreks** [comment]
@clydin This seems to do the trick. Thanks!

 `<base>` tag is gone from `index.html`. Is it documented somewhere in the i18n framework? I could not find any information about that. It is kind of tricky.

/close
