### ISSUE TITLE
Allow directTemplateLoading to be set from angular.json or webpack configuration

### ISSUE THREAD

**Issue by aquark** [angular/angular-cli#17265]
Reopening https://github.com/angular/angular-cli/issues/15861
# 🚀 Feature request

Command (mark with an x)
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

## Description
The AngularCompilerPlugin allows templates to be loaded directly, bypassing any loaders configured in the webpack config. The default value of this option is false.

The Angular CLI creates an instance of the AngularCompilerPlugin and sets this option to true, with no way of overriding this behavior.

Setting this to true made sense when there was no way to customize the webpack config. However, now that CLI Builders are officially supported, it will become more common for builders like @angular-builders/custom-webpack to be used to customize the webpack configuration. But with directTemplateLoading being hard-coded to true, there is no way to customize the webpack configuration to allow a loader to manipulate a component's template.

## Describe the solution you'd like
Let the directTemplateLoading option be set in the angular.json file. For example:

"architect": {
  "build": {
    "builder": "@angular-builders/custom-webpack:browser",
    "options": {
      "directTemplateLoading": false,
      "customWebpackConfig": {
        "path": "./webpack.config.js"
      },
      "etc": "etc"

## Describe alternatives you've considered

These are outlined in https://github.com/angular/angular-cli/issues/15861

**Comment by clydin** [comment]
This is a duplicated of #15861

If you are modifying the webpack configuration (which can be done but not officially supported), then existing plugins may need to be modified or replaced as well.

The option described above would only be applicable to a builder that allows user modification of the internal webpack configuration.  The official builders do not allow for this type of behavior.  However, the `@angular-builders/custom-webpack:browser` builder does and it could offer such an option.  Please consider opening a feature request with the maintainer of the `angular-builders` project.
