### ISSUE TITLE
missing config files in project 

### ISSUE THREAD

**Issue by mangopop** [angular/angular-cli#1726]
angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.3
os: win32 x64 windows 10

In the wiki it mentions system-config.ts and angular-cli-build.js to configure when installing third party libraries. I cannot find these files? Are they meat to be there by default?

**Comment by LunicLynx** [comment]
This is intentional, the angular cli is now webpack based.
See: https://github.com/angular/angular-cli/blob/master/CHANGELOG.md
And the migration document: https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md

**Comment by mangopop** [comment]
Thanks
