### ISSUE TITLE
help me understand and fix 'ERROR in Cannot read property 'map' of undefined' error am getting where is run/serve or build my app

### ISSUE THREAD

**Issue by aminemshady2080** [angular/angular-cli#17271]
hey guys please help me understand and fix 'ERROR in Cannot read property 'map' of undefined' error am getting where is run/serve or build my app (ionic4 angular project ) and doesnt say where & in which file the error is occuring. 
this is my environment version after running `ng versrion` command

![v](https://user-images.githubusercontent.com/6911823/77230701-ac6c3980-6b9e-11ea-9395-8e64a601da8c.PNG)

**Comment by alan-agius4** [comment]
Hi @aminemshady2080, can you please the log file contents / trace please?

Also, can you kindly update to version 9 and see it the problem persists? 

Thanks.

**Comment by aminemshady2080** [comment]
i ended up deleting the whole project and over cause i couldn't find solution due to incatibilities of angular packages once i run npm update  many packages werent compatible with new angular version now i moved back to 8.3.25 atleast things were going well for a while until now am getting 
this error 

`ERROR in ../nodes/rxjs/src/internal/scheduled/scheduled.ts:5:60 - error TS2307: Cannot find module 'rxjs'.
[ng] 5 import { ObservableInput, SchedulerLike, Observable } from 'rxjs';`

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/angular/angular-cli/issues/17326#issuecomment-605297902

If the problem persists kindly file a new issue with a minimal reproduction.

Thanks.
