### ISSUE TITLE
Unable to upgrade to RC5 using angular-cli

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [angular/angular-cli#1727]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
MAC OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
The version installed after I typed:
npm install angular-cli @angular/tsc-wrapped --save-dev

As per the instructions in [RC4 TO RC5 MIGRATION](https://angular.io/docs/ts/latest/cookbook/rc4-to-rc5.html)

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
After executing the step on item 2 above I started getting NPM conflicts between tslint and typescript.
````bash
npm install angular-cli @angular/tsc-wrapped --save-dev
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
diq-conversation@0.0.0 /Users/silveir/Projects/dlabs/diq-conversation
├─┬ @angular/tsc-wrapped@0.2.2 
│ └─┬ tsickle@0.1.6 
│   ├── minimist@1.2.0 
│   ├── source-map@0.4.4 
│   └─┬ source-map-support@0.3.3 
│     └── source-map@0.1.32 
├── angular-cli@1.0.0-beta.10 
└── UNMET PEER DEPENDENCY typescript@1.8.10
````

Also this:
````bash
npm install typescript@^1.9.0-dev -save-dev
diq-conversation@0.0.0 /Users/silveir/Projects/dlabs/diq-conversation
└── UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160627-1.0

npm WARN tslint@3.11.0 requires a peer of typescript@>=1.7.3 but none was installed.
npm ERR! code 1

````
Also this:
````bash
npm install tslint@latest --save-dev
diq-conversation@0.0.0 /Users/silveir/Projects/dlabs/diq-conversation
├── tslint@3.14.0 
└── UNMET PEER DEPENDENCY typescript@1.9.0-dev.20160627-1.0
````

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
It is true that there are peer dependency warnings, but that should not prevent your upgrade from going through. Are you using NPM3?

**Comment by dematic-rodrigo-silveira** [comment]
Hell Filipe - I'm using NPM3:
````bash
silveir@US3430NB:~$ node --version
v6.2.1
silveir@US3430NB:~$ npm --version
3.10.6
````

I have been able to upgrade to RC5 using the older version of angular-cli, with the only drawback being:
* the creation of new projects - package.json is still showing rc4 and older versions of other dependencies
* the creation of components, pipes, directives, services - they have to be re-factored (minor work) to function as fully grown RC5 citizens.

Regards
Rodrigo

**Comment by filipesilva** [comment]
The webpack versions of the CLI should include RC5 support. See https://github.com/angular/angular-cli#webpack-preview-release-update for instructions.

If you're happy with the upgrade so far, can you close the issue?

**Comment by dematic-rodrigo-silveira** [comment]
I'm using the System.js version; do you have plans to fix it for the System.js version? Do you recommend I move to the Webpack version? 

You can close this issue, as you respond to the two questions above.

Thanks for your help.

Regards
Rodrigo

**Comment by filipesilva** [comment]
I recommend switching to the webpack version. It's not tagged as latest because we're still fixing some bugs, but the CLI will be using webpack for the foreseeable future and personally I think the current webpack preview is already better than beta.10.

Try it out first, as your mileage may vary depending on what your project currently needs.
