### ISSUE TITLE
Capability of seeding unique hash values for aot compilations 

### ISSUE THREAD

**Issue by nealyip** [angular/angular-cli#17289]
as far as I know, the hash values in the filenames are based on the file content itself.
However, I have recently came across an issue that our font files were cached with incorrect content-types. It's more unfortunate that those files were set a year max age of public cache headers.
so normally our users can't simply reload the font files with correct content-type headers by refreshing the page specifically our mobile users. 

From the angular cli itself, there seems not be no options seeding the filename hash so it's not an easy task to change the built filenames as basically the font itself will rarely change.

**Comment by alan-agius4** [comment]
Hi @nealyip, this seems to be similar to an old PR https://github.com/angular/angular-cli/pull/6500 which was closed and un-merged.

Let's me take this with the rest of the team to fully understand why it was closed as it seems that there is no explanation in the linked PR.

**Comment by filipesilva** [comment]
Heya @nealyip, I understand that it looks like it would be rather straightforward to address the cache mishap by changing the cache algorithm on the build system. 

This isn't a feature we're thinking of adding though. We considered it in https://github.com/angular/angular-cli/issues/6513 (the original issue for #6500), but that use case wasn't compelling enough. I don't think the particular use case in this issue lends more weight to the argument either. For us, we'd incur the cost of developing and maintaining a feature that doesn't seem to be a significant value add. 

But it also sounds like it could be addressed on the project side by changing the content of the font files, or removing hashing from the media files. Another approach is to customize the build setup with https://github.com/manfredsteyer/ngx-build-plus. These approach might have pitfalls, and there might be better approaches, but we'd need a more compelling use case to consider adding the feature to Angular CLI itself.
