### ISSUE TITLE
Need to document that it has dependency on Python 2.7

### ISSUE THREAD

**Issue by CoronaOpenSource** [angular/angular-cli#17284]
# 🐞 Bug report

### Command (mark with an `x`)
Installation with `yarn`

### Is this a regression?

Don't know.  Never got it working yet.

### Description

It errors on installation.

## 🔬 Minimal Reproduction

`yarn`

## 🔥 Exception or Error
<pre><code>
warning Error running install script for optional dependency: "/Users/___/projects/angular-cli/node_modules/watchpack/node_modules/fsevents, /Users/___/projects/angular-cli/node_modules/webpack-dev-server/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/___/projects/angular-cli/node_modules/watchpack/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/bin/python -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack   File \"<string>\", line 1
gyp ERR! stack     import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Darwin 17.7.0
gyp ERR! command \"/Users/___/.nvm/versions/node/v10.15.0/bin/node\" \"/Users/___/.nvm/versions/node/v10.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/___/projects/angular-cli/node_modules/watchpack/node_modules/fsevents
warning Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.22.0".
✨  Done in 138.76s.
</code></pre>

## 🌍 Your Environment
<pre><code>
No install yet
</code></pre>

**Anything else relevant?**
Python is version 3.7

**Comment by CoronaOpenSource** [comment]
Fixed python in path to use 2.7.  But rerunning `yarn` doesn't fix install.

**Comment by devoto13** [comment]
Looks like this is happening because of https://github.com/fsevents/fsevents/issues/301. This dependency is coming from `webpack` and `webpack-dev-server` trees. I would suggest to use https://github.com/fsevents/fsevents/issues/301#issuecomment-589152186 as a temporary workaround, but not sure how to apply it to global package installs.

**Comment by alan-agius4** [comment]
Closing as per above explanation. 

Thanks @devoto13.
