### ISSUE TITLE
Do not include system-polyfills.js

### ISSUE THREAD

**Issue by vsavkin** [angular/angular-cli#1729]
Currently, the generated karma configuration file has system-polyfills.js included after zone.js. 
This is a problem: 
1.  zone.js patches promises
2. system-polyfill patched them again

The result is that the async and fakeAsync helpers do not work in tests.

I don't think system-polyfill is even required. At least when I remove it from the configuration, my tests still run. I think we should either remove the polyfill or at least include it before zone.js

**Comment by hansl** [comment]
This has already been fixed in the Webpack branch; we don't use `system-polyfills.js` anymore. You should switch to that branch.
