### ISSUE TITLE
Core update schematic should update Typescript

### ISSUE THREAD

**Issue by danieldiazastudillo** [angular/angular-cli#17305]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Update schematic should update TypeScript dependency too. Changelog for current Angular Core says that TypeScript was updated to version 3.8 but the schematic is not taking care of that.

![image](https://user-images.githubusercontent.com/14895873/77565535-205e5880-6ea3-11ea-9c4d-ba522740b1c3.png)

### Describe the solution you'd like
Angular core schematic should update Typescript for the required version, update `package.json` and notify in update log. I don't know if the same approach for RxJS update it's better or not, something like: `ng update typescript`.

### Describe alternatives you've considered
The only workaround is to update via `npm` but that could lead to some issues.

**Comment by alan-agius4** [comment]
Using TypeScript 3.8 with Angular 9.1 is opt-in for existing projects.

In some cases update TypeScript to a different minor might cause a previously working project to break. This would not be ideal especially when updating from one minor to another of the Angular framework.

Angular 9.1 still supports TypeScript 3.7, so not updating TypeScript in this case is the better approach IMHO.

**Comment by alan-agius4** [comment]
Closing as per above.
