### ISSUE TITLE
Upgrade to angular 9.1 with TSLint 6.1 error "Cannot find migration 'tslint-version-6' in '@angular/cli'."

### ISSUE THREAD

**Issue by hiepxanh** [angular/angular-cli#17308]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] update

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

ng update @angular/cli --migrate-only tslint-version-6
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 66 dependencies.
Cannot find migration 'tslint-version-6' in '@angular/cli'.
![image](https://user-images.githubusercontent.com/16970990/77604112-4ab42280-6f44-11ea-9791-795126b23cfa.png)

## 🔬 Minimal Reproduction
ng update @angular/cli --migrate-only tslint-version-6

## 🔥 Exception or Error
it shoud be clear

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.6
Node: 12.16.1
OS: win32 x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      9.1.3
@angular/fire                     6.0.0-rc.1
@angular/flex-layout              9.0.0-beta.29
@angular/http                     8.0.0-beta.10
@angular/material                 9.1.3
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

**Comment by hiepxanh** [comment]
Solution: `npm i @angular/cli@latest -g -s` before update make error disappear 
![image](https://user-images.githubusercontent.com/16970990/77604578-71bf2400-6f45-11ea-9ed6-9a5e0c166774.png)

$ ng update @angular/cli --migrate-only tslint-version-6
Using package manager: 'npm'
Collecting installed dependencies...
Found 66 dependencies.
** Executing 'tslint-version-6' of package '@angular/cli' **

> Update tslint to version 6.
UPDATE tslint.json (3162 bytes)
  Migration completed.

**Comment by AceVentura** [comment]
@hiepxanh did not work for me
![image](https://user-images.githubusercontent.com/3084589/77659735-57e70680-6f70-11ea-8059-ff32bf7584fa.png)

**Comment by mburger81** [comment]
Same for me!

**Comment by clydin** [comment]
The migration is available in the Angular CLI starting with version 9.1.0.  The project must be updated before the migration can be executed.

Please try executing the following within the project to update: 
`ng update @angular/cli @angular/core`

**Comment by hiepxanh** [comment]
@clydin  should I close issue or not? I resoved mine but other didn't sir.

**Comment by mburger81** [comment]
Yes I figured it out yesterday. Firstly we have to run the update and then the migration too.

**Comment by mburger81** [comment]
> For additional information regarding the release of Angular 9.1 please see: https://blog.angular.io/version-9-1-of-angular-now-available-typescript-3-8-faster-builds-and-more-eb292f989428

In my opinion this is not clear from reading  the article. But it could also be it's a language problem of mine.
Also it is strange, it is talking first about the migration and then how to update. It would be better if first we have the distribution about how to do the update, and then what to do if you also would like to migrate to tslint6.1
thx

**Comment by alan-agius4** [comment]
I pinged @StephenFluin to update the blog post to make it clearer.

**Comment by hiepxanh** [comment]
@alan-agius4  do you want me to close this issue or just wait the PR?

**Comment by alan-agius4** [comment]
Closing as the blog post has been fixed.

**Comment by francovp** [comment]
The blog post HAS NOT been fixed. I get the same error because of that and got to this issue
