### ISSUE TITLE
output the ngcc debug logs when in verbose mode

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular-cli#17303]
🚀 Feature request

To help with diagnosing ngcc issues it would be really useful to be able to see the debug output from ngcc. Could we expose these logs, perhaps when the CLI is in `--verbose` mode?

### Command
- [x] build
- [x] serve
- [x] test
- [x] e2e

**Comment by dgp1130** [comment]
`--verbose` is the best hook right now to attach this to, so this is a pretty reasonable implementation.

**Comment by petebacondarwin** [comment]
On the ngcc team, we recently discussed the idea of just reading an environment variable from within ngcc, which could allow us to turn on and off various kinds of debugging tools (including logging). This would mean the CLI would not need to worry about this...

**Comment by alan-agius4** [comment]
As per convo with @petebacondarwin, we can close this for now and revisit if needed in the future.
