### ISSUE TITLE
Tslint migration does not consider an extends property containing an array

### ISSUE THREAD

**Issue by sfabriece** [angular/angular-cli#17311]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Running `ng update @angular/cli --migrate-only tslint-version-6`

with a tslint config like this:
```
{
  "extends": [
    "tslint:recommended",
    "tslint-plugin-prettier",
    "tslint-config-prettier"
  ],
....
```

fails with 
```
 tslint configuration does not extend "tslint:recommended".
    Migration will terminate as some rules might conflict.
```

The following file implements the migration.
`https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/migrations/update-10/update-tslint.ts`

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Hi, thanks for the issues. Actually the problem here is the error message, as the migration will be executed only and only if extending `tslint:recommended`

**Comment by sfabriece** [comment]
Can I contribute the fix to this @alan-agius4 ?

**Comment by alan-agius4** [comment]
@sfabriece, there is already a PR for this: https://github.com/angular/angular-cli/pull/17323

**Comment by francovp** [comment]
For me, I don't have the "extends" array and got the warning message bot the migration completes  

```
Using package manager: 'npm'
Collecting installed dependencies...
Found 67 dependencies.
** Executing 'tslint-version-6' of package '@angular/cli' **

> Update tslint to version 6.
    tslint configuration does not extend "tslint:recommended".
    Migration will terminate as some rules might conflict.
UPDATE package.json (3375 bytes)
UPDATE tslint.json (3099 bytes)
  Migration completed.
```
