### ISSUE TITLE
externalSchematic('@schematics/update', 'update') doesn't respect order in chain() for migration

### ISSUE THREAD

**Issue by psmul** [angular/angular-cli#17317]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update (schematics)
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Only tested with ^0.900.0

### Description
For given snippet:
<pre><code>export function migrate(): Rule {
  return chain([
    externalSchematic('@schematics/update', 'update', {
      packages: ['@nguniversal/express-engine'],
      from: '8.0.0',
      to: '9.0.0',
    }),
    removeImportsInMainServerFile(),
  ]);
}
</code></pre>

Both functions are invoked almost immediately, as provided in the screenshot below. If I understand correctly, chain() method containing externalSchematics with @schematics/update should respect the order and finish migration and then invoke another function in order. Tried approach with translating tree to observable in the second function, however, the outcome is the same. Looks like @schematics/update performs this asynchronously, causing the next functions to be invoked immediately. **I haven't noticed this behavior for other migrations or schematics from Angular collections (like creating an app, component, service etc.).**

## 🔬 Minimal Reproduction
Create simple migration containing externalSchematic('@schematics/update', 'update') for any given library.

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/10993491/77640869-60811200-6f5b-11ea-9917-9ee18e2bb813.png)

The red highlighted area is separate function that should be invoked after @schematics/update for the library has been completed.

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.7
Node: 10.16.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.7
@angular-devkit/build-angular      0.900.7
@angular-devkit/build-ng-packagr   0.900.7
@angular-devkit/build-optimizer    0.900.7
@angular-devkit/build-webpack      0.900.7
@angular-devkit/core               9.0.7
@angular-devkit/schematics         9.0.7
@ngtools/webpack                   9.0.7
@nguniversal/builders              9.0.2
@nguniversal/common                9.0.2
@nguniversal/express-engine        9.0.2
@schematics/angular                9.0.7
@schematics/update                 0.900.7
ng-packagr                         9.0.3
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Anything else relevant?**

**Comment by iKrishnaSahu** [comment]
@psmul I think you should avoid using @schematics/update package. 
Check [this ](https://github.com/angular/angular-cli/issues/22391#issuecomment-995704552) out.

BTW did you find any other package to run update via schematic like @schematic/update?

**Comment by psmul** [comment]
@iKrishnaSahu Appreciate mentioning me to this thread! Sadly we haven't found another solution, so we decided to do things other way. At least we know we shouldn't wait for any update in this case.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
