### ISSUE TITLE
[proposal] auto polyfilling support via `@babel/preset-env`

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#17318]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

According to [Official Document](https://angular.io/guide/browser-support#polyfills), `polyfills` can only be included manually.

Sometimes we somehow use ESNext features like `Array.prototype.flatMap` but forget adding its polyfill into `polyfills.ts`, it accidentally breaks on some browsers.

### Describe the solution you'd like

In @alauda, we are using [@alauda/custom-webpack](https://www.npmjs.com/package/@alauda/custom-webpack) which pipes `babel-loader` after `@ngtools/webpack` in webpack config, so that we get _auto polyfilling_ successfully via `@babel/preset-env`.

So I'm suggesting to add `auto polyfilling` support into `@angular/cli`.

### Describe alternatives you've considered

If we can build all `.ts` via `@ngtools/webpack` with targeting `esnext`, then we can use `babel` to compiling all ES syntaxes totally but are able to get types metadata still at the same time.

---

Related: We can add `esnext` entry support for APF.

https://github.com/ng-packagr/ng-packagr/issues/1542

**Comment by alan-agius4** [comment]
Hi @JounQin, 

Thanks for this feature request. This currently is not in-scope of the Angular CLI.

**Comment by JounQin** [comment]
Can you explain in details? Why we can't do it? It's very easy AFAIK. And ng-cli is using some babel plugins already like https://github.com/angular/angular-cli/issues/21196.
