### ISSUE TITLE
bug(moment-adapter): "_rollupMoment__default is not defined"

### ISSUE THREAD

**Issue by kaito3desuyo** [angular/angular-cli#17320]
(related with https://github.com/angular/angular/issues/36248)

#### Reproduction

https://github.com/kaito3desuyo/angular-test

Steps to reproduce:
1. clone this repository
2. ``ng build --prod``
3. ``npm i -g http-server``
4. move root directory to ``dist/angular-test`` Folder
5. ``http-server``
6. open ``http://localhost:8080``

This issue only occurs with production builds.
 
#### Expected Behavior

Screen is displayed correctly

#### Actual Behavior

Screen goes blank with console error

#### Environment

- Angular: 9.1.0
- CDK/Material: 9.2.0
- Browser(s): Chrome 80.0.3987.149
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 x64 1909 18363.720

**Comment by marsc** [comment]
Same problem here in production build  only with "@angular-devkit/build-angular": "~0.901.0". Downgraded for now.

**Comment by ArtemeeSenin** [comment]
Have the same problem but with 
`main-es2015.8a5dc9b260c775d8aa4b.js:1 Uncaught ReferenceError: dragulaExpt__default is not defined`

**Comment by TheParad0X** [comment]
Same problem here after an update from Angular 9.0.5 to the latest

**Comment by mikejunt** [comment]
Yep, also seeing this issue with moment after upgrading

**Comment by atlesj** [comment]
Same

**Comment by fpmk** [comment]
any news?

**Comment by pabloxn** [comment]
Same problem

**Comment by deepakgonda** [comment]
Same problem with the production build.

**Comment by acherniak** [comment]
Any good news?

**Comment by jasoninrapid** [comment]
We're seeing the same problem on an Angular 8 to Angular 9 upgrade we did on March 26.  Details:

- ng2-dragular module got  transpiled with the same bad "dragulaExpt__default" referenced above.
- Downgrading angular devkit fix it for us.  Our (fixed) entry in the dev dependencies in package.json looks like: "@angular-devkit/build-angular": "0.900.7"

**Comment by spock123** [comment]
I think most of us are stuck on 9.0.x for now. I can't risk workarounds or downgraded dependencies. Better to wait until this gets sorted out - at least for me.

**Comment by demisx** [comment]
Same issue after upgrading Angular to the latest. Had to downgrade `@angular-devkit/build-angular` to `v0.900.7` to get rid of the same error as @ArtemeeSenin's.

**Comment by albert-asin** [comment]
same here

**Comment by alinaresz** [comment]
Same problem after upgrading to "@angular-devkit/build-angular": "^0.901.0"
The workaround by @jnfaerch to downgrade to "^0.900.7", worked for me.

**Comment by neaptolem** [comment]
Same problem as @jasoninrapid 
Thank you for any updates.

**Comment by showjefb** [comment]
Took a while to track down (wish I had visited here first), but I have the same scenario as many. **0.900.7** works while **0.901.0** breaks  my build versions.

**Comment by Fzwael** [comment]
Lost one day looking for this 😢

**Comment by blogcraft** [comment]
Bad integration Testing from Angular Team 😑

**Comment by blogcraft** [comment]
> > ISSUE RESOLVED
> 
> Issue is not resolved, this is a workaround. We should'nt have to downgrade or change moment import.

Actually, that's how Angular Material docs recomends using moment:
https://material.angular.io/components/datepicker/overview

> // Depending on whether rollup is used, moment needs to be imported differently.
// Since Moment.js doesn't have a default export, we normally need to import using the `* as`
// syntax. However, rollup creates a synthetic default module and we thus need to import it using
// the `default as` syntax.
import * as _moment from 'moment';
// tslint:disable-next-line:no-duplicate-imports
import {default as _rollupMoment, Moment} from 'moment';
> 
> const moment = _rollupMoment || _moment;

**Comment by demisx** [comment]
Please note that this issue breaks the prod build even for those who don't use `Moment.js ` and ` _rollupMoment `. Some regression has been introduced going from `0.900.7` to `0.901.0`.

**Comment by ViieeS** [comment]
The new `@angular-devkit/build-angular` has a problem compiling `@angular/material-moment-adapter`:

![image](https://user-images.githubusercontent.com/8194543/78113796-f2c86080-7408-11ea-943e-cb51fd1c1267.png)

Possible workaround is just to add this to `polyfills.ts`:
window['_rollupMoment__default'] = null;

**Comment by gwidonw** [comment]
Please note that this is not only problem with Moment - I'm getting the same error with ng2-dragula lib 
![Zrzut ekranu 2020-03-31 o 12 57 20](https://user-images.githubusercontent.com/8656036/78114262-48007400-7401-11ea-8de4-eba33b9d0176.png)

**Comment by mduft** [comment]
Same here with ng2-dragula after updating from 9.0.0 to 9.1.0..

**Comment by 4typen** [comment]
> 
> 
> The new `@angular-devkit/build-angular` has a problem compiling `@angular/material-moment-adapter`:
> 
> ![image](https://user-images.githubusercontent.com/8194543/78113796-f2c86080-7408-11ea-943e-cb51fd1c1267.png)
> 
> Possible workaround is just to add this to `polyfills.ts`:
> 
> `window['_rollupMoment__default'] = null;`

This is probably the better workaround instead of downgrading the angular-devkit.

I have btw. the same issue with "getAngularJSGlobal" and "_rollupMoment__default" in our AngularJS/Angular 9.1 Hybrid App.

**Comment by mucbits** [comment]
Thank you @4typen, I was just trying to fix that and your workaround is much better!

**Comment by sebrojas14** [comment]
I tried to upgra to Angular 9.1.0 and a lot of libraries broken with errors like this.

**Comment by JosepAlacid** [comment]
I just don't understand how to apply @mgechev fix or I don't understand why this issue is closed.

**Comment by mgechev** [comment]
@JosepAlacid the issue is fixed by this PR https://github.com/angular/angular-cli/pull/17364. We'll release the fix on Wednesday.

**Comment by danielehrhardt** [comment]
![image](https://user-images.githubusercontent.com/19570043/78605777-772d4000-785c-11ea-9d64-fe65ba44c3e0.png)

**Comment by spock123** [comment]
@danielehrhardt Is that with @mgechev 's fix or?

**Comment by danielehrhardt** [comment]
> @danielehrhardt Is that with @mgechev 's fix or? 

Yes

**Comment by mgechev** [comment]
The fix is not our yet. @danielehrhardt did you build the CLI from source?

**Comment by mtpultz** [comment]
Downgrading the devkit has problems if you run `npm audit fix` in your deployments.  This seemed to fix it until a couple days ago and now we're getting an error

```
An unhandled exception occurred: Cannot find module 'webpack-dev-server
```

So we've switched to the solution of adding `window['_rollupMoment__default'] = null;` to polyfills.ts

**Comment by gultyaev** [comment]
> @JosepAlacid the issue is fixed by this PR #17364. We'll release the fix on Wednesday.

Still not working. Just updated my deps to the latest ones and still same error.

**Comment by cedricduffournet** [comment]
I think this is because angular-cli has not been released yet, still in v9.1.0.

**Comment by OckePocke** [comment]
I tried the new version 9.1.1, that has been released today, and it solved the issue for me.

**Comment by mgechev** [comment]
As @OckePocke mentioned, we released CLI [9.1.1 today](https://github.com/angular/angular-cli/releases/tag/v9.1.1). If the problem still persist for you, feel free to open a new issue linking this one.

**Comment by Rajarml** [comment]
The 9.1.1 CLI release seems to have fixed the same issue.
No more `window['_rollupMoment__default'] = null;`-in-`polyfills.ts` workaround needed.

**Comment by skonx** [comment]
No more `window['_rollupMoment__default'] = null;` but `Moment` imports should be updated like there  : https://stackblitz.com/angular/qrmxxmanejy?file=src%2Fapp%2Fdatepicker-views-selection-example.ts

**Comment by JosepAlacid** [comment]
And don't forget to add 
`"allowSyntheticDefaultImports": true,`
at compilerOptins in tsconfig.json

**Comment by skonx** [comment]
> And don't forget to add
> `"allowSyntheticDefaultImports": true,`
> at compilerOptins in tsconfig.json

@JosepAlacid indeed 😉

**Comment by hamfastgamgee** [comment]
This fix made my "ng test" configuration use Typescript 3.6, meaning that any files using the safe navigation (Elvis) operator don't compile correctly.  Is there something special I need to do (angular.json edits, etc.) so that only build optimization is impacted?

**Comment by mgechev** [comment]
@hamfastgamgee optional chaining (safe navigation, elvis, etc.) is part of TypeScript 3.7.

**Comment by hamfastgamgee** [comment]
@mgechev Right, and Angular 9.1.x supports 3.8. But after this fix to use 3.6 in the build optimizer, "ng test" is running as 3.6 for me, meaning that code is not working if it uses 3.7 or 3.8 features. I'm trying to figure out if it's something wrong in my config that's causing "ng test" to use the wrong TS version, or if this effectively causes TS 3.7+ to be unsupported again and should have been documented more explicitly.

**Comment by JACrazy** [comment]
Sad to see we're back to 3.6, was really liking optional chaining

**Comment by mgechev** [comment]
@JACrazy no need to go back to 3.6. We fixed this issue and released the CLI.

**Comment by JACrazy** [comment]
> @JACrazy no need to go back to 3.6. We fixed this issue and published the fix on npm.

Great to hear!
