### ISSUE TITLE
Ng new is not successfully installing

### ISSUE THREAD

**Issue by obumnwabude** [angular/angular-cli#17328]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
I just updated @angualr/cli today to version 9.1, then I ran `ng new`. It created the necessary files but it did not install the packages successfully. I tried again and again but it kept happening. The error from the command line is as on the error section

## 🔥 Exception or Error
<pre><code>

| Installing packages...npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkd
irp are no longer supported. Please update to mkdirp 1.x. (Note that the API sur
face has changed to use Promises in 1.x.)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://git
hub.com/request/request/issues/3142
npm ERR! Unexpected end of JSON input while parsing near '...arball":"https://re
gi'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Obum Nwabude\AppData\Roaming\npm-cache\_logs\2020-03-28T08
_33_46_573Z-debug.log
x Package install failed, see above.
The Schematic workflow failed. See above.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.0
Node: 12.16.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.0
@angular-devkit/core         9.1.0
@angular-devkit/schematics   9.1.0
@schematics/angular          9.1.0
@schematics/update           0.901.0
rxjs                         6.5.4
</code></pre>

**Anything else relevant?**

The link to the above 2020-03-28T08_33_46_573Z-debug.log file in Google Drive is at https://drive.google.com/open?id=1AyEHtc6-NU12blA-jhloQu7gyRNVfNsF

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by obumnwabude** [comment]
Ok thank you
