### ISSUE TITLE
help fixing ERROR in ../nodes/rxjs/src/internal/scheduled/scheduled.ts:5:60 - error TS2307: Cannot find module 'rxjs'

### ISSUE THREAD

**Issue by aminemshady2080** [angular/angular-cli#17326]
hey guys,
can anyone please help me understanding what is happening here am running ANGULAR 8.2.14 and ANGULAR CLI 8.3.25 my ionic / angular app
when i run ng serve or ionic serve i get this error for nodes rxjs saying there is a wrong import 
the log says
`ERROR in ../nodes/rxjs/src/internal/scheduled/scheduled.ts:5:60 - error TS2307: Cannot find module 'rxjs'.
[ng] 5 import { ObservableInput, SchedulerLike, Observable } from 'rxjs';`

and errors on instances of ScheduleLike saying about incompatibility of rxjs 

`Argument of type 'import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/src/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/src/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/internal/types").SchedulerAction<T>' is not assignable to type 'import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/src/internal/types").SchedulerAction<T>'.
            The types returned by 'schedule(...)' are incompatible between these types.
              Type 'import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type 'import("d:/XAMPP/htdocs/ionic_angular/pharmacy/node_modules/rxjs/src/internal/Subscription").Subscription'.
                Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.ts(2345)
Peek Problem
No quick fixes available
`
am running Angular 8.2.14 beacuase when i nmp udated angular to ANGULAR 9 it messed up with a lot of dependent packages so i i went back to Angular 8.

Expected resolution is:
help me find a way to fix it or what can i install or uninstall to get my app running again.

this is my environment versions

`Angular CLI: 8.3.25
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.803.25
@angular-devkit/build-optimizer   0.803.25
@angular-devkit/build-webpack     0.803.25
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cli                      8.3.25
@angular/pwa                      0.900.7
@ngtools/webpack                  8.3.25
@schematics/angular               8.3.25
@schematics/update                0.803.25
rxjs                              6.5.4
typescript                        3.4.5
webpack                           4.39.2

`

thx

**Comment by alan-agius4** [comment]
Most likely you are using an incompatible rxjs version try to downgrade to 6.4.X.

Closing as this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
