### ISSUE TITLE
Allow/Enable configurations for `ng deploy` commands

### ISSUE THREAD

**Issue by george43g** [angular/angular-cli#17332]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] deploy
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Probably not

### Description

Not sure if this is a bug or a feature request. 

Allow specifying a `--configuration='production'` for `ng deploy` commands.
This should simply read from the corresponding configuration and apply those settings on top of settings found in `options` under the `deploy` config.

According to docs, this should work for other types of tasks such as build/serve/lint: https://angular.io/guide/cli-builder#target-configuration

## 🔬 Minimal Reproduction
```json
"deploy": {
          "builder": "@angular/fire:deploy",
          "options": {
            "buildTarget": "my-project:build",
            "firebaseProject": "dev"
          },
          "configurations": {
            "production": {
              "buildTarget": "my-project:build:production",
              "firebaseProject": "prod"
            }
          }
        }
```

This command works:
`ng deploy myProject`

This command does not work, even with correct configuration:
`ng deploy myProject --configuration production`

## 🔥 Exception or Error
```
Unknown option: '--configuration'
Unknown option: 'production'
```

## 🌍 Your Environment
Angular CLI 9

**Comment by alan-agius4** [comment]
@george43g, thanks for reporting this. 

Indeed this is a bug which should be trivial to fix. I’ll take a look at it tomorrow!

**Comment by george43g** [comment]
Awesome! I'll let some package maintainers know about this. Should result in some cleaner code/setups. Hopefully, the pull request will be merged in soon.
