### ISSUE TITLE
Custom path in tsconfig for multiple project stop work as should after upgrade to Angular 9 

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular-cli#17338]
# 🐞 bug report

### Is this a regression?
With Angular 8 it work as should
Now after I upgrade it not work

### Description
I'm using angular cli with multiple project.
After I follow the Angular Update Guide I start to get `ts2307 cannot find module '@app....'`

My tsconfig.json (projects/portal/tsconfig.app.json)

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "../../out-tsc/app",
    "types": [],
    "paths": {
      "@app/*": [
        "app/*"
      ],
      "@env/*": [
        "environments/*"
      ],
      "@sol/*": [
        "../../shared-lib/src/lib/*"
      ]
    }
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "projects/admin-portal/src/**/*.d.ts"
  ]
}

```

It used to work before the upgrade.
Please let me know how to handle it.
Thanks :)

## 🔥 Exception or Error
<pre><code>
For all the imports that I'm using with shortened path prefix '@app/...'
Im geting this error:
ts2307 cannot find module '@app....'
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.1.0
Node: 12.3.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular-devkit/schematics-cli    0.803.25
@angular/cdk                      9.2.0
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@nguniversal/express-engine       8.2.6
@schematics/angular               9.1.0
@schematics/schematics            0.803.25
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by alan-agius4** [comment]
@ofirrifo, can you try to update your baseUrl from `src` to `./src`?

**Comment by ofirrifo** [comment]
I did set ./src but still the error display.
Is there additional things I can share with you so we can solve that issue ? 
be aware that I can't share this project as it private.

Thanks

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please? A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
@ofirrifo, you are seeing the error during built or in the IDE?, As if the latter, it is expected since for the IDE to pick up the paths settings they need to be in a file named `tsconfig.json`. which is related to https://github.com/angular/angular-cli/issues/8138

**Comment by ofirrifo** [comment]
@alan-agius4  only in the ide

**Comment by alan-agius4** [comment]
In that case let's continue tracking this in #8138.

As a workaround you can copy `projects/portal/tsconfig.app.json`  and name it `projects/portal/tsconfig.json`.

**Comment by ofirrifo** [comment]
@alan-agius4  replacing the **tsconfig.app.json** to **tsconfig.json** 
WORK :)

I will need to revert this change after it will be fixed?
