### ISSUE TITLE
how to get server.js file created by ng serve?

### ISSUE THREAD

**Issue by eshwarmore1993** [angular/angular-cli#1733]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by LunicLynx** [comment]
Can you elaborate?

**Comment by eshwarmore1993** [comment]
i need internal script of ng serve.
so that on Amazon aws ec2 Ubuntu machine i can paste dist folder and host
it.. coz can't use directng serve on cloud as it also listen for livereload
on different port

**Comment by LunicLynx** [comment]
After an ng build --prod you don't need ng serve anymore. You can use a static file server to host your application.
I don't think ng serve is meant as a hosting strategy for production.

**Comment by eshwarmore1993** [comment]
i did host the web on statistic container... but its not supporting the
routed path URL... ex www.book.com/login is not giving me login page...
it's only working when am doing ng serve
.. that's why am asking ng client might me writting node.js file to host
the web internally... i hope u got my point

On 18-Aug-2016 3:29 PM, "LunicLynx" <notifications@github.com> wrote:

After an ng build --prod you don't need ng serve anymore. You can use a
static file server to host your application.
I don't think ng serve is meant as a hosting strategy for production.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angular-cli/issues/1733#issuecomment-240678676>,
or mute the thread

**Comment by LunicLynx** [comment]
You need to configure your webserver to ignore the relative path of the URL. What happens is that the webserver is looking for an index.html document inside the login folder. Which is not what you want. That part of the URL you want to be handled by the angular router.

For apache this could be helpful
http://httpd.apache.org/docs/2.0/misc/rewriteguide.html

**Comment by eshwarmore1993** [comment]
that's my question, how ng serve does it and which server it uses... in aws
ec2 Ubuntu am using live-server not apache

**Comment by LunicLynx** [comment]
Maybe this does help?
http://zanon.io/posts/angularjs-with-pretty-urls-removing-the-in-amazon-s3

**Comment by eshwarmore1993** [comment]
it's not about only aws... when i move to dist folder and do live-server
then on local also am not able to route directly to that page... but
loading index and then clicking button works

**Comment by LunicLynx** [comment]
Then you need to figure out how todo url rewriting on live-server.  

In short: You need to instruct your hosting-system to rewrite all urls to the base url.

Eg. my-server/login should actually got to my-server/index.html. The angular router will the look at the url and use JavaScript to display the right component.

The cli can't help you here.

**Comment by deebloo** [comment]
This is because the router uses the history API. Do a quick Google search on server for single page apps and you should find some example of what to do.

**Comment by deebloo** [comment]
Here is a sample SPA server in node.
```
var fallback = require('express-history-api-fallback');
var express = require('express');

var app = express();
var root = __dirname + '/dist';

app.use(express.static(root));
app.use(fallback('index.html', { root: root }));

app.listen(8080);
```

**Comment by filipesilva** [comment]
How you deploy to your server is pretty much up to you, but you must rewrite the URLs. The easiest way I know of is using apache: https://ngmilk.rocks/2015/03/09/angularjs-html5-mode-or-pretty-urls-on-apache-using-htaccess/

You can find more solutions to this by searching not for Angular 2 or the CLI, but for a similar router functionality that existed in Angular 1. Google `aws angular html5mode` and you will find quite a few results.
