### ISSUE TITLE
Webpack AngularCompilerPlugin and Ivy not working with translations

### ISSUE THREAD

**Issue by helderjsm** [angular/angular-cli#17342]
# 🐞 Bug report

### Is this a regression?

 No, this started with Ivy

### Description

 When switching to Ivy translations are lost when using webpack.
Also tried adding  import '@angular/localize/init'; to polyfills but no success.
Looked through documentation but it looks like there's not much more that I can configure using the AngularCompilerPlugin.

Command used to run is:
"start": "cross-env AUTHENTICATION_ENABLED=true CLIENT_APP_SETTINGS_URL=/api/ClientAppSettingsLocal.json BASE_API_URL=http://localhost:59180 webpack-dev-server --inline --hot --progress --port 8080 --history-api-fallback",

#### webpack.config.dev.js:
<pre><code>
   new AngularCompilerPlugin({
      mainPath: helpers.root("client-src/main.ts"),
      locale: "en",
      platform: PLATFORM.Browser,
      sourceMap: true,
      tsConfigPath: helpers.root('tsconfig.json'),
      compilerOptions: {
        enableIvy: true,
        i18nInLocale: "en-GB",
        enableI18nLegacyMessageIdFormat: true
      },
      exclude: [],
      skipCodeGeneration: false,
      i18nInFile: helpers.root("client-src/locale/messages.xlf"),
      i18nInFormat: "xlf",
      enableIvy: true,
      missingTranslation: "error"
    }),
</code></pre>
#### tsconfig.json
<pre><code>
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "target": "es2015",
    "module": "esnext",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "declaration": false,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "baseUrl": "./",
    "paths": {
      "@appsrc/*": [ "client-src/*" ],
      "@appservice/*": [ "client-src/app/services/*" ],
      "@appmodule/*": [ "client-src/app/modules/*" ],
      "@appentities/*": [ "client-src/app/entities/*" ],
      "@appguards/*": [ "client-src/app/guards/*" ]
    }
  },
  "angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck":  true
  },
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
</code></pre>

## 🌍 Your Environment
<pre><code>
    "@angular/animations": "^9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "^9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/material-moment-adapter": "^9.2.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/router": "^9.1.0",
    "@angular/localize": "9.1.0",

"devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "^9.1.0",
    "@angular/compiler-cli": "^9.1.0",
    "@angular/language-service": "^9.1.0",
</code></pre>

**Comment by alan-agius4** [comment]
i18n under Ivy is a post build step and no longer part of the TypeScript compilation.

Maybe @clydin can chime in on this?

**Comment by clydin** [comment]
As @alan-agius4 mentioned, the AOT compiler for Ivy does not perform translations.  Translation is instead now a post-build step.  This change provides for greatly improved build-time performance (only one full build of the application is required instead of one per locale).  It also is an enabler for potential future runtime localization support.

If not using the Angular CLI to perform the application build, the `@angular/localize` package has a standalone utility (`localize-translate`) that can be used to perform the post-build translation of the application.

**Comment by helderjsm** [comment]
First of all thank you @clydin and @alan-agius4 .
After your explanation it was easier to find the issue.
Maybe I didn't research properly but I didn't find any information in angular.io that we also needed to: have a loadTranslations({}) call. Only after searching for the utility localize-translate I could find some websites explaining this.

I'm still a bit confused though as the extract tools provided by angular cli do not extract as json while the loadTranslations method seems to accept json. Maybe I'm missing something here?!
For now I will try changing my extraction process to use tool this one: https://github.com/loclapp/locl.
