### ISSUE TITLE
Add 'Access-Control-Allow-Headers': '*' to headers of DevServer configuration

### ISSUE THREAD

**Issue by kristofdegrave** [angular/angular-cli#17343]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

### Description

 
I'm currently building a micro front-end solution. In this I am loading files from one dev server in an other dev server using XHR. This works, but when I am adding `applicationInisighs.js`, this wants to add the `request-id` header to the CORS calls. This results into a CORS Error.

## 🔥 Exception or Error
<pre><code>

Access to XMLHttpRequest at 'http://localhost:9010/assets/i18n/en.json' from origin 'http://localhost:9009' has been blocked by CORS policy: Request header field request-id is not allowed by Access-Control-Allow-Headers in preflight response.
</code></pre>

## 🌍 Your Environment
<pre><code>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.1.3
@angular/material                  9.1.3
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         9.1.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

Adding `'Access-Control-Allow-Headers': '*'` to the following line would fix the problem. 

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/dev-server/index.ts#L457

**Comment by alan-agius4** [comment]
In version 11, a new `headers` option was added which can be used to add custom headers.

See: https://github.com/angular/angular-cli/pull/19015
