### ISSUE TITLE
Upgrade to angular 9.1 with TSLint 6.1 error "Cannot find migration 'tslint-version-6' in '@angular/cli'."

### ISSUE THREAD

**Issue by francovp** [angular/angular-cli#17340]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] update

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0.7

### Description

 A clear and concise description of the problem...

```
ng update @angular/cli --migrate-only tslint-version-6
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 67 dependencies.
Cannot find migration 'tslint-version-6' in '@angular/cli'.
```

## 🔬 Minimal Reproduction

`ng update @angular/cli --migrate-only tslint-version-6`

## 🔥 Exception or Error
<pre><code>
Cannot find migration 'tslint-version-6' in '@angular/cli'.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.7
Node: 12.16.1
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.0.1
@angular/cdk-experimental         9.0.1
@angular/fire                     5.4.2
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.0.1
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

Opened this because #17308 was closed and the problem was not fixed as [the blog still has the confusing problem](https://blog.angular.io/version-9-1-of-angular-now-available-typescript-3-8-faster-builds-and-more-eb292f989428) (at least in my end)

**Comment by alan-agius4** [comment]
Hi @francovp, which part of the below you find it is not clear? You need to update to 9.1 prior to trying to running the migration.

> TSLint 6.1 by default
Newly created projects will now use TSLint 6.1 by default. If you want to migrate to the latest version, make sure you are on version 9.1 first, then you can opt-in via:
```
ng update @angular/cli --migrate-only tslint-version-6
```
> We do not run this migration automatically because there are some minor breaking changes in TSLint 6.1.

**Comment by francovp** [comment]
Hmm, i did't saw that, sorry. My fault :/

Closing this.

**Comment by francovp** [comment]
Just to clarify something, so the `The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.``` was not working as intended?

**Comment by alan-agius4** [comment]
No, that is expected and working as intended as you are not on the latest version of the CLI.

**Comment by francovp** [comment]
Right, but that was supposed to install a temporary updated Angular CLI version to make the migration/update so the `Cannot find migration 'tslint-version-6' in '@angular/cli'.` error should not trigger. 

That was supposed to avoid the "temporary Angular CLI installation" or not?

**Comment by alan-agius4** [comment]
No, the temporary Angular CLI installation is used so that during the `ng update` the latest "orchestrator" is used. `--migrate-only` only perform a migration, does not update the installed version of the package in the user workspace. Thus, running `--migrate-only`, the workspace should already be updated and installed. Either updated their dependencies via `package.json` or `ng update <package-name>`

You can use the below 2 commands in case you didn't update Angular CLI to version 9.1 yet.

```
ng update @angular/cli 
ng update @angular/cli --migrate-only tslint-version-6
```

The first command will update the Angular CLI package to the latest stable version which is currently 9.1, the second command will run the tslint version 6 migration from the installed package.
