### ISSUE TITLE
92% chunk asset optimization terserpluginkilled

### ISSUE THREAD

**Issue by thanhtuyenpkk** [angular/angular-cli#17354]
Hello every body,
I use thi command to buil my application 
` node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod`
but it not build success it return this message 
`92% chunk asset optimization terserpluginkilled`
How to fix it? 
And what is max_old_space_size?
Thanks you

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
