### ISSUE TITLE
No chunks for lazy-loaded modules generated

### ISSUE THREAD

**Issue by dtslvr** [angular/angular-cli#17350]
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

Angular CLI does not create chunks for lazy-loaded modules defined in `app-router.module.ts`:

<pre>
<code>
const routes: Routes = [
  {
    path: 'home',
    loadChildren: () =>
      import('./app/page/home/home.module').then((m) => m.SmdHomeModule)
  },
  {
    path: 'test',
    loadChildren: () =>
      import('./app/page/test/test.module').then((m) => m.SmdTestModule)
  }
];
</code>
</pre>

## 🔬 Minimal Reproduction

1. Checkout the repository with the test app: https://github.com/dtslvr/angular-9-test-app
2. Run `yarn` to install the dependencies
3. Run `yarn start` to start the test app

## 🔥 Exception or Error
<pre>
<code>
chunk {main} main.js, main.js.map (main) 20.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 141 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 2.99 MB [initial] [rendered]
</code>
</pre>

But there are no chunks for `home` or `test`.

## 🌍 Your Environment
<pre>
<code>
Angular CLI: 9.1.0
Node: 13.3.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code>
</pre>

**Anything else relevant?**
No.

**Comment by alan-agius4** [comment]
Hi, the problem seems to be that you are setting the `module` as `commonjs`. 
https://github.com/dtslvr/angular-9-test-app/blob/7d5826d8bd0bb6c3cc9b059ad5a2191e68b3526f/tsconfig.app.json#L5

For this syntax to work it should be `esnext`.
