### ISSUE TITLE
"types" not used as a synonym for "typings" in package.json

### ISSUE THREAD

**Issue by benbotto** [angular/angular-cli#17353]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No, at least not that I'm aware of.

### Description
I'm using a third-party module and that module's package.json file has a "types" attribute instead of "typings."  When I do a production build, `ng build --prod`, I get a module resolution error: "Field 'browser' doesn't contain a valid alias configuration."  If I manually change "types" to "typings" in the module's package.json, per the [Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview#heading=h.k0mh3o8u5hx) then the error goes away.

The [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) states that "the 'typings' field is synonymous with 'types.'"

## 🔬 Minimal Reproduction
I've created a StackBlitz that reproduces the issue.  I've added one third-party dependency, @stripe/stripe-js, and exposed that modules `loadStripe` method as a provider in `app.module.ts`.

- Download the following project from StackBlitz: https://stackblitz.com/edit/angular-kezmsy?file=src%2Fapp%2Fapp.module.ts
- Extract the zip file: `unzip angular-kezmsy.zip`
- Install dependencies: `npm i`
- Do a production build: `npm run build -- --prod`

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@stripe/stripe-js/types/index' in '/home/<redacted>/Downloads/angular-kezmsy/src/app'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.0.7
Node: 10.16.3
OS: linux x64
Angular: 8.2.14
... common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.0.4
@angular/language-service         7.0.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.5.4
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**
The error also goes away if I remove the `loadStripe` provider that I've added in `app.module.ts`, but that makes it difficult to test.

The error did not surface during development, i.e. while service the app via `ng serve`.

The error does not crop up during a non-prod build--`npm run build` works fine--so I suspect it has to do with aot.

The module that I'm using is @stripe/stripe-js.  Here's the package.json file: https://github.com/stripe/stripe-js/blob/v1.2.0/package.json#L8  Note that on line 8 "types" is used instead of "typings."

I asked a question about this on SO and it has some additional context: https://stackoverflow.com/questions/60940657/angular-8-and-stripe-js-v3s-loadstripe-module-not-found-error-cant-resolve

**Comment by alan-agius4** [comment]
Hi @benbotto, this should no longer be a problem in Angular CLI version 9.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
