### ISSUE TITLE
ng build --prod does not generate consistent hashes on different machines when run with same code base

### ISSUE THREAD

**Issue by naraklearn** [angular/angular-cli#17351]
### Versions
angular : 8.2 & 9.1
angular-cli: 8.3 & 9.1
OS: windows 7 & 10 64bit

### Repro steps
Create a site with ng new
Add a lazy path with loadChildren
ng build --prod
Use same source code in differnt machine
ng build --prod
compare these two dist with same source code(no change)

### Observed behavior
Same issue occurred in angular V8.2 & 9.1 versions(attached screenshot of differences in hashes for same source code). Currently production build is in angular 8.2
1)	When run in different drives in same machine with same source code, Every time production build happens the hashes in the chunks does not change as no change in the source code – working as expected
2)	when run in different computer machine with same source code, production build happens the hashes in the chunks changes when comparing between dist in windows 7 and dist in windows 9 though there is no changes in source code.

### Desired behavior
when run in different computer machine with same source code, Every --prod build should not change the hashes in the chunks  because no change made in existing code base.

what is recommended way to achieve desired behavior? 

if customizing the angular-cli/webpack package is alternate approach, what is the recommended options?
angular 8.2 dist comparison:
![image](https://user-images.githubusercontent.com/62874238/78031638-7179bb00-7381-11ea-8693-269b8b6225c1.png)
Angular 9.1 dist comparison:
![image](https://user-images.githubusercontent.com/62874238/78031684-822a3100-7381-11ea-95f3-7fab35d60cad.png)

**Comment by alan-agius4** [comment]
Hi @naraklearn, 

Are both machines using the same Node version? Can you please share the output of `ng version` from both machines?

**Comment by naraklearn** [comment]
Angular: 8.2
Environment : Windows 10
Node : v10.17.0
![ng_version_windows_10](https://user-images.githubusercontent.com/62874238/78245279-d7db1680-7504-11ea-81d7-fa63eee0a84c.PNG)

Environment : Windows 7
Node: v10.15.3
![ng_version_windows_7](https://user-images.githubusercontent.com/62874238/78245283-d9a4da00-7504-11ea-8803-913648056abd.png)

Angular: 9.1
Environment: Mac
Node: v10.16.3
![ng_version_mac_angular9](https://user-images.githubusercontent.com/62874238/78254816-16c49880-7514-11ea-9631-95f5908d4a3c.png)
Environment: Windows
Node: v10.15.3
![ng_version_windows7_angular9](https://user-images.githubusercontent.com/62874238/78254865-26dc7800-7514-11ea-88d4-b0fb9415b379.png)


What might be the root cause for this issue?

**Comment by alan-agius4** [comment]
I am seeing that the node version and the packages installed are not the same version, those 2 can cause different file hashes.

1. Use same node and package versions
2. Use a package manager lock file and install using frozen mode (`npm ci` or `yarn frozen-lockfile`)
3. Hashes will be different between Windows and Mac, unless you configure your line endings to be LF and not CRLF on Windows. See: https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by naraklearn** [comment]
@alan-agius4 Thanks! above mentioned solutions worked for us.
