### ISSUE TITLE
proxy.config.json support parameters

### ISSUE THREAD

**Issue by DaniloPineda** [angular/angular-cli#17362]
Good morning.
After configuring the proxy, I  was able to succesfully call the api.
the request loos like this:  http://mydomain/jsonresponse.json
However there's another endpoint I'd like to call but it has a parameter like this:
http://mydomain/{id}/jsonresponse.json

My configurations looks like this:
{    
    "/current/*": {
      "target": "https://newdomain.com/",
      "secure": false,
      "pathRewrite": {       
        "^/current": "/jsonresponse.json",
        "^/id": "/jsonresponse.json"
      },
        "changeOrigin": true
      }      
  }

the call from the service:
    var url = `/${id}/id`;
    this.http.get<ModelResponse>(url);   

As I mentioned the first request works but the second one doesn't.
I appreciate any help or guidance, since I haven't been able to find support for it.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
