### ISSUE TITLE
UNMET PEER DEPENDENCY typescript@2.0.0

### ISSUE THREAD

**Issue by 281330** [angular/angular-cli#1737]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
 Linux Mint

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
1.0.0-beta.11-webpack.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
This is an app created using angular-cli.  All I am doing is running `npm install`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`UNMET PEER DEPENDENCY typescript@2.0.0`
5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Here's the result of `npm list typescript`

```
├─┬ angular-cli@1.0.0-beta.11-webpack.2
│ └─┬ typedoc@0.4.4
│   └── typescript@1.8.10 
└── UNMET PEER DEPENDENCY typescript@2.0.0

npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
```

**Comment by mangopop** [comment]
I'm getting the same

**Comment by neilhem** [comment]
So something does not work?

**Comment by mangopop** [comment]
Just done some testing and the app does seem to run ok.

**Comment by kylecordes** [comment]
I think this is a spurious message because of unfixed messiness in the various underlying libraries. Once the versions stabilize (i.e.. the various libraries are updated and reconciled to agree on what TypeScript version they want), these messages should go away. In the meantime, I've been using TypeScript 2.0.0 and getting good results, while ignoring messages that complain about an UNMET PEER DEPENDENCY for something that is sitting right there...

**Comment by alo** [comment]
+1

**Comment by filipesilva** [comment]
Peer dependency warning will be around for a bit while the ecosystem adapts to the new Typescript and Node versions.

They should be warnings however, not errors - try updating to NPM3 and they should be listed as warnings.

**Comment by lindsaymarkward** [comment]
I have npm3 but these show as ERRors not warnings:
```
➜  ng-challenge git:(master) ✗ npm --version
3.10.6
➜  ng-challenge git:(master) ✗ npm list typescript
ng-challenge@0.0.0 /Users/sci-lmw1/Documents/dev/ng-challenge
├─┬ angular-cli@1.0.0-beta.11-webpack.2
│ └─┬ typedoc@0.4.5
│   └── typescript@1.8.10 
└── UNMET PEER DEPENDENCY typescript@2.0.0

npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
```
Am I missing something, or do I still just ignore this?

**Comment by iBasit** [comment]
same here...

**Comment by neilhem** [comment]
Try to update to the latest version `angular-cli@1.0.0-beta.11-webpack.8`
