### ISSUE TITLE
IE Edge uses es2015 instead of es5 bundle

### ISSUE THREAD

**Issue by sandrooco** [angular/angular-cli#17377]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
probably not

### Description
IE Edge uses the es2015 bundle, which doesn't work.
For example `n={...i}` will throw SCRIPT1028: Expected identifier, string or number.

I expect Edge to use the es5 bundle. Is this configurable?

## 🔬 Minimal Reproduction
Build any angular project, target 2015, and browserslist like this (equals the [guide](https://angular.io/guide/deployment#differential-loading)):
> 0.5%
last 2 versions
Firefox ESR
not dead
not IE 9-11 # For IE 9-11 support, remove 'not'.

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.7
Node: 10.16.3
OS: darwin x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.1.3
@angular/material                 9.1.3
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
We tried Edge versions 42 and 44, although I think more are affected.

**Comment by clydin** [comment]
Both of those versions of Edge support ES2015.  However, spread operators in an object literal (`n={...i}`) are an ES2018 feature.

Can you ensure that the application is targeting ES2015 within the tsconfig file for the application?
Also if possible can you provide a minimal reproduction that is generating the above code.

**Comment by sandrooco** [comment]
Thanks for your feedback @clydin!
The tsconfig.json has the following target: ` "target": "es2015",` the one for es5 has ` "target": "es5",`.

Lib is like this, if it helps: `"lib": ["es2018", "dom"],`

Unfortunately I can't find out what causes the use of the spread operators in the object - it's just minified code (and pretty certainly not a service/component from me). So I can't provide a repro snippet, sorry.

Differential loading itself works for Internet Explorer - there it takes the correct (es5) bundle.
Do I understand it right, that target "es2015" should also make sure that es2018 features work?

**Comment by clydin** [comment]
The tsconfig target will ensure that all application code is ES2015.  However, this does not apply to libraries which are bundled directly for the ES2015 output files since they are JS and not TS files.  If a library is using newer ES features than this could be the source of the problem.  Are you using any third-party libraries/packages that could be doing this?

**Comment by sandrooco** [comment]
I just found that code:
`const filterItems = this.filterables.reduce(
      (acc, nextItem) => ({ ...acc, [nextItem.formControlName]: [] }),
      {}
    );`

I suppose this causes the problem. According to your explanation this should be handled properly, right?

**Comment by alan-agius4** [comment]
@sandrooco, is the above part of your application code or provided by a library?

**Comment by sandrooco** [comment]
@alan-agius4 Sorry, forgot to mention that! This snippet is in one of my own components.

**Comment by alan-agius4** [comment]
@sandrooco, I tried this locally and wasn't able to reproduce the output.

Also, pasting the above code in the TypeScript playground yields the expected result 
https://www.typescriptlang.org/play?downlevelIteration=true&esModuleInterop=false&declaration=false&emitDecoratorMetadata=false&target=2#code/MYewdgzgLgBAZgSwDZQKYCcCSaC2EYC8MUAFghAHSIoYCGARkqpeqgCYCuwqAFAFAxBMHrWDAANDDCoAHlGyocASkIA+YQG8YFHaIkwA2tLkKcVEOhwBhcFHQgkAOVo5UAXQBchtzAC+S8QEhDV8+JQBuIA

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by sandrooco** [comment]
@alan-agius4 I could find out in the mean time that it wasn't the snippet I posted above. The issues originated in a library with some strange `eval` usage. (We threw it out, it was not the best library anyways, obviously.)

I'm really sorry for wasting your time.
