### ISSUE TITLE
XRegExp pattern fails when using IE11 (polyfills-es5)

### ISSUE THREAD

**Issue by psmyrdek** [angular/angular-cli#17375]
# 🐞 bug report

### Affected Package

@angular/core

### Is this a regression?
Yes - works fine on 8.x

## 🔬 Minimal Reproduction

Create a fresh project (Angular 9.1) and replace main.ts with the following content:
https://gist.github.com/psmyrdek/a32ed781830f1c69472c0580123330ef

It works on Chrome, Firefox, etc. but it doesn't work on IE11. Everything is fine if we're on 8.x

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/6187417/78266758-7d42ba00-7506-11ea-8a9e-97fac8e63160.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 12.16.1
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>
we're also relying on `xregexp@4.3.0`

**Comment by psmyrdek** [comment]
Testing the same pattern using `"@angular/cli": "8.0.6"` () and `"@angular/cli": "9.1.0"` and for sure there are some changes in RegExp polyfill.

In both cases, I'm trying to translate the same pattern and I see a different output in console:  

`"@angular/cli": "8.0.6"`:
![image](https://user-images.githubusercontent.com/6187417/79111986-d835a600-7d7d-11ea-8d22-f2eb00ce41e1.png)

`"@angular/cli": "9.1.6"`:
![image](https://user-images.githubusercontent.com/6187417/79111972-d4a21f00-7d7d-11ea-8ad7-e8e72c55a68c.png)

And the base is:
```js
XRegExp('(^((?=[uuuuuuuuu\\sxxxxxxxxx\\p{L}\\p{N}\\p{P}\\p{S}\\p{M}/])[^;\\\\<>{}])*$)|(^$)')
```

**Comment by alan-agius4** [comment]
Closing as this is ok it actionable by the Angular tooling team.

We’ll consume the fix once the core-ha team addressed the problem.
