### ISSUE TITLE
error TS2554: Expected 0 arguments, but got 1.  18     String.toLocaleUpperCase(locale);

### ISSUE THREAD

**Issue by cmlbrnc** [angular/angular-cli#17387]
String.toLocaleUpperCase(locale); 

I am getting an error on build.
Here are the versions
 "devDependencies": {
    "@angular-devkit/architect": "<0.900 || ^0.900.0-0 || ^9.0.0-0",
    "@angular-devkit/build-angular": "^0.900.6",
    "@angular/cli": "~9.0.6",
    "@angular/compiler-cli": "~9.0.6",
    "@angular/language-service": "~9.0.6",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/lodash": "^4.14.149",
    "@types/node": "^8.10.59",
    "@types/sortablejs": "^1.10.2",
    "@types/stripe-checkout": "^1.0.3",
    "@types/stripe-v3": "^3.1.17",
    "codelyzer": "^5.0.0",
    "firebase-tools": "^6.10.0",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.6.5"
  }

**Comment by cmlbrnc** [comment]
Solve the problem external Js function in angular  like; 

` constructor(private constS:ConstantsService) {
     const locale =constS.locale;
    this.usefulLink= toCapitilaze(($localize`:@@useful:Useful Link` as String),locale);
    this.contactInfo = toCapitilaze(($localize`:@@contactinfo:Contact Information` as String),locale);
    this.securePayment = toCapitilaze(($localize`:@@securePayment:Secure Payment` as String),locale)
    
   }

  ngOnInit(): void {
  }

}
 function toCapitilaze(value,locale) {


  return value.toLocaleUpperCase(locale)

}`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by cmlbrnc** [comment]
Hello, I couldnt build the javascript function String.toLocaleUpperCase(locale) with the locale param on angular component.  So put out the code of angular component. It works fine for me.
