### ISSUE TITLE
Since angular 9 webpack hooks can no longer indicate the end of localized build process

### ISSUE THREAD

**Issue by kamilchlebek** [angular/angular-cli#17381]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular v8

### Description

When building angular application using new `--localize` flag, the build process consists of two phases. First one is the webpack compilation and second is the post processing. Because of that after first phase output files land in `/tmp` directory instead of target destination. 

The problem is, that I've been using a `sentry` plugin that relies on webpack hook - `afterEmit`. Previously that hook allowed the plugin to read target (ex. `dist`) directory and access emitted files. Right now at the time when hook is executed `dist` directory remains empty until post-processing is completed.  

Of course I could (and I will) write custom node script that will be executed manually (or as a combined npm script) just after `ng build`. 

Are there plans to put that post processing back to webpack compilation process, or it's going to stay this way? 

## 🔬 Minimal Reproduction

Let me know if you need a reproduction. It's more conceptual issue

## 🌍 Your Environment
<pre><code>Angular CLI: 9.1.0
Node: 10.16.0
OS: linux x64
</code></pre>

**Comment by alan-agius4** [comment]
Hi @kamilchlebek,

Sorry for the inconvenience caused. 

There are no plans in moving localization pipeline back into Webpack. If anything, most likely in the future we'll move more parts of the build pipeline outside of the Webpack.

It's important to point out, that using any Webpack specific feature might break in future.

**Comment by kamilchlebek** [comment]
@alan-agius4 Thank you for clarification! 

This is what I supposed, but I just wanted to make sure.
