### ISSUE TITLE
ERROR ISSUES IN ANGULAR ABOUT PRIVATE VARIABLE.

### ISSUE THREAD

**Issue by MogilicharlaAkhilaja** [angular/angular-cli#17395]
![error](https://user-images.githubusercontent.com/60478730/78508429-8bae0180-77a4-11ea-84a6-3d5990d1503a.png) Am getting this error issue. My variable is in private in menu component.ts but when am declaring it in menu.component.html . Am facing problem through this error..
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Docs or angular.io issues at: https://github.com/angular/angular/issues/new/choose

For the time being, we keep Angular AIO issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hi @MogilicharlaAkhilaja, private members are not accessible from the template.

**Comment by MogilicharlaAkhilaja** [comment]
> Hi @MogilicharlaAkhilaja, private members are not accessible from the template.

But in the udemy explanation he got the output without any error. But for me its not coming?

**Comment by petebacondarwin** [comment]
Either the udemy course is very old or it was taking advantage of an old bug in the compiler (perhaps in JIT mode)?

**Comment by MogilicharlaAkhilaja** [comment]
> Either the udemy course is very old or it was taking advantage of an old bug in the compiler (perhaps in JIT mode)?
sir,
Then what should i do now ? Because of this error am struggling

**Comment by alan-agius4** [comment]
There are two things that you can do 

1) Remove the `private` annotations from the used members
2) As a temporary workaround until you fix all the issues turn off `fullTemplateTypeCheck` from your `tsconfig.json`. (You should turn back on eventually after fixing all template related errors.)

**Comment by MogilicharlaAkhilaja** [comment]
> There are two things that you can do
> 
> 1. Remove the `private` annotations from the used members
> 2. As a temporary workaround until you fix all the issues turn off `fullTemplateTypeCheck` from your `tsconfig.json`. (You should turn back on eventually after fixing all template related errors.)

ok thank you sir.. I kept fulltemplateCheck in comments.

**Comment by MogilicharlaAkhilaja** [comment]
> > There are two things that you can do
> > 
> > 1. Remove the `private` annotations from the used members
> > 2. As a temporary workaround until you fix all the issues turn off `fullTemplateTypeCheck` from your `tsconfig.json`. (You should turn back on eventually after fixing all template related errors.)
> 
> ok thank you sir.. I kept fulltemplateCheck in comments.
If i remove private member . Again getting error.

![privaterror](https://user-images.githubusercontent.com/60478730/78547420-b176ed00-781c-11ea-919d-73f2a2f783df.png)

**Comment by alan-agius4** [comment]
You shouldn't need to remove the private member, but rather just the private annotation. 

Ex: 

Before:
```ts
private foo(): string {}
```

After
```ts
foo(): string {}
```
