### ISSUE TITLE
Failed to list lazy routes 

### ISSUE THREAD

**Issue by hasannaqi9** [angular/angular-cli#17394]
I updated my angular CLI to latest and I am facing following issue while serving app.
![image](https://user-images.githubusercontent.com/11630678/78507510-fdcf1800-779d-11ea-99ba-fbe39b64a553.png)

My Package.json file:
![image](https://user-images.githubusercontent.com/11630678/78507526-163f3280-779e-11ea-9a69-051f31f62225.png)

**Comment by alan-agius4** [comment]
@hasannaqi9, your `@angular/cli` version is quite old `7.3.x`. Please update `@angular/cli` to the latest stable version `9.1.x` using `ng update`. 

```cmd
ng update @angular/cli
```

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem.
