### ISSUE TITLE
Duplicate files in dist folder after ng build

### ISSUE THREAD

**Issue by Belouccio** [angular/angular-cli#17399]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 Hi. When i run ng build several times, the files in dist folder start duplicates (you can see that in the screenshot beyond). If I set deleteOutputPath = true, my website is not enabled (cause the dist folder is clear) until by build finished. In 5 version of angular it works fine. How can I fix that? Thank you!

## 🔬 Minimal Reproduction
run `ng build `several times
![image](https://user-images.githubusercontent.com/25301055/78542015-39e69500-77ff-11ea-8d13-c317f52c70f8.png)

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.22
Node: 10.15.0
OS: linux x64
Angular: 8.2.14

</code></pre>

**Comment by alan-agius4** [comment]
Hi @Belouccio, this if you since you are not using `deleteOutputPath` the files will not be deleted and thus you will be responsible for the clean up of files.

> my website is not enabled (cause the dist folder is clear) until by build finished.

This seems more of a setup/deployment pipeline issue. From the explanation above, I am getting that your web server is pointing to the `dist` folder, and you re-build to deploy an update version of the application.

**Comment by Belouccio** [comment]
I think no. If I update my app several times a day I need to change my nginx config file each time and restart nginx?

**Comment by Belouccio** [comment]
why answer is closed?

**Comment by alan-agius4** [comment]
> In 5 version of angular it was work pretty fine

There wasn't ever an angular CLI version 5.

@Belouccio, the issue has been closed as it's working as expected and this issue tracker is not suitable for support requests. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alan-agius4** [comment]
Ps, yeah: `ng build: node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng build --prod=true && find ./public -name .js -type f -mmin +10 -delete` should do you want.
