### ISSUE TITLE
ng version should display the version of this module

### ISSUE THREAD

**Issue by Gillespie59** [angular/angular-cli#174]
I have just tried an `ng -v` and the result is the following one : 

```
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 5.0.0
npm: 2.14.10
os: linux x64
```

But the latest Git tag of the angular-cli projet is 0.20.0. We should have this version as result of the previous command.

**Comment by jkuri** [comment]
Hi. This is a version of `ember-cli` and it is not displayed anymore, you can test it with cloning master and then npm linking. See readme for more info about linking.
