### ISSUE TITLE
Inline import of raw-loader in Angular 9 throws an error during compliation

### ISSUE THREAD

**Issue by iamebuka** [angular/angular-cli#17403]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.x.x

### Description

 I recently update my Angular project from 8.X.X to Angular 9 and whenever I tried to build, I always get a compilation error. Before the update code works for previous version of Angular. 

## 🔬 Minimal Reproduction

- Update Angular project from 8.X.X to 9.X.X using Angular official documentation.
- Load file using inline raw-loader 

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/components/breadcrumb/index.ts:1:27 - error TS2307: Cannot find module 'raw-loader!./routes'.

1 import * as routesTs from '!raw-loader!./routes';
                            ~~~~~~~~~~~~~~~~~~~~~
src/app/components/spinner/index.ts:1:26 - error TS2307: Cannot find module '!raw-loader!./spinner-basic/spinner-basic.component'.

</code></pre>


## 🌍 Your Environment
<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 10.18.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         9.1.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.41.5

</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->
Using commonjs `require` works.
<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by alan-agius4** [comment]
Hi @iamebuka,

Sorry for the inconvenience caused but this isn't something we've ever explicitly supported. Instead, Webpack, which we use, supports it, and we don't prevent its usage. 

We don't encourage or support using non-standard and webpack specific features directly in user source code, because we don't want to commit to supporting them in case we change to other build setups.

In this case changing your import and allow the file to be loaded as part of the TypeScript compilation without using raw-loader.
