### ISSUE TITLE
What's the replacement for system-conf.js in angular-cli@webpack ?

### ISSUE THREAD

**Issue by myAoyue** [angular/angular-cli#1740]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>
**Mac OSX EI Capitan**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
>
**angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.0
os: darwin x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
>
I used to install third-part library with configuring **system-conf.ts** & **angular-cli-build.js** before updating to angular-cli@webpack.
>
**system-conf.ts**
>
<img width="707" alt="2016-08-18 2 39 45" src="https://cloud.githubusercontent.com/assets/8954054/17764610/f6f72722-6552-11e6-8790-959a51ca569c.png">
>
**angular-cli-build.js.js**
>
<img width="535" alt="2016-08-18 2 48 01" src="https://cloud.githubusercontent.com/assets/8954054/17764623/02bc87a0-6553-11e6-87df-4627d04d43c9.png">
>
Everything is good working.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
>
Now, I want to know what's the replacement for system-conf.js in angular-cli@webpack ?
Since, I couldn't import any library normally such as:
`npm install jquery --save`
`import * as jQuery from 'jquery';`
>
Error: Cannot find module 'jquery'
>
Because, it seems that no related configuration file to define the module.

5. Mention any other details that might be useful.
>
But, I found that moment.js can work correctly.
You just need to：
`npm install moment --save`
`import * as moment from 'moment';`
>
Umm.... how

**Comment by deebloo** [comment]
there is no replacement. It is no longer needed. Moment works correctly out of the box because it includes type definitions and jquery does not. so try ```npm install @types/jquery``` and then see if ```import * as jQuery from 'jquery';``` works for you.
