### ISSUE TITLE
Ability to generate multiple index.html files

### ISSUE THREAD

**Issue by nandhaaas** [angular/angular-cli#17409]
# 🚀 Feature request
Ability to build multiple index.html

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...
I am working on solution for multi branding app where every branch requires a unique theme with some brand specific configuration. Now in order to support this there is a brand specific environment configuration in place and a separate build needs to be triggered. This is all going good but the problem is as the number of brand grows maintaining branch specific environment and build is getting tedious considering the fact that every brand will also require dev,qa,prod specific configuration. 

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
The solution that i am looking for is to be able to generate multiple index.html files for each brand from the build with the respective theme reference. I can then use this output in a webserver where i can route it respective index.html based on the domain 

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
I can achieve this by extending the web pack configuration or using gulp but it will be more of workaround rather than a solution as i have to make copies of index.html and also replace the references. It will be nicer to have this feature come from angular cli

**Comment by scurk1415** [comment]
Why dont you just load the configuration for a different brand on APP_INITIALIZER?

I have a similar requirement as you and i solved it with:

- loading the brand config on APP_INITIALIZER
- theming with css variables
- different css with lazy loading them

So far we separate the brand on nginx (where we set a cookie and read it on the FE), but we will probably have to improve this part somehow.

One deployment multiple brands.

**Comment by nandhaaas** [comment]
> Why dont you just load the configuration for a different brand on APP_INITIALIZER?
> 
> I have a similar requirement as you and i solved it with:
> 
> * loading the brand config on APP_INITIALIZER
> * theming with css variables
> * different css with lazy loading them
> 
> So far we separate the brand on nginx (where we set a cookie and read it on the FE), but we will probably have to improve this part somehow.
> 
> One deployment multiple brands.

Thanks for the reply. 

I am currently working on your first two recommendations as i have seen them in some forums. Could you please shed some light on the third one (different css with lazy loading them).

In my case, brands are hosted separately so i don't want them to be loaded with all the themes and the assets which are not relevant.

**Comment by scurk1415** [comment]
Something like this https://juristr.com/blog/2019/08/dynamically-load-css-angular-cli/

**Comment by alan-agius4** [comment]
Hi @nandhaaas, thanks for opening this feature request. However, this is currently out-of-scope of the Angular CLI. 

As suggested you can achieve this via lazy loading CSS at runtime or extend the Angular CLI build builder using a 3rd party custom builder ex: https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#index-transform

Note: while the Angular CLI does allow customising your build pipeline, we, the Angular tooling team don't provide support for this.
