### ISSUE TITLE
How to avoid duplication in configuration?

### ISSUE THREAD

**Issue by shabinpshams** [angular/angular-cli#17402]
I am using Angular version 9 using nx workspace.
I have 5 different projects along with 11 different configurations per project.

How can I eliminate the reusable configurations like aot:true

![image](https://user-images.githubusercontent.com/10242450/78560001-ffd8bb80-781d-11ea-89ff-f1be6b9b1cef.png)

**Comment by alan-agius4** [comment]
You can achieve this by providing multiple configurations.

```js
"configurations": {
  "feature": {
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.feature.ts"
      }
    ],
   },
  "production": {
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.prod.ts"
      }
    ],
    "optimization": true,
    "outputHashing": "all",
    "sourceMap": false,
    "extractCss": true,
    "namedChunks": false,
    "aot": true,
    "extractLicenses": true,
    "vendorChunk": false,
    "buildOptimizer": true
  }
}
```

Example `ng build --configuration=production,feature`


See: https://angular.io/guide/workspace-config#alternate-build-configurations

**Comment by shabinpshams** [comment]
> You can achieve this by providing multiple configurations.
> 
> ```js
> "configurations": {
>   "feature": {
>     "fileReplacements": [
>       {
>         "replace": "src/environments/environment.ts",
>         "with": "src/environments/environment.feature.ts"
>       }
>     ],
>    },
>   "production": {
>     "fileReplacements": [
>       {
>         "replace": "src/environments/environment.ts",
>         "with": "src/environments/environment.prod.ts"
>       }
>     ],
>     "optimization": true,
>     "outputHashing": "all",
>     "sourceMap": false,
>     "extractCss": true,
>     "namedChunks": false,
>     "aot": true,
>     "extractLicenses": true,
>     "vendorChunk": false,
>     "buildOptimizer": true
>   }
> }
> ```
> 
> Example `ng build --configuration=production,feature`
> 
> See: https://angular.io/guide/workspace-config#alternate-build-configurations

Thanks for your response.

What I asked is how to eliminate 

    "optimization": true,
    "outputHashing": "all",
    "sourceMap": false,
    "extractCss": true,
    "namedChunks": false,
    "aot": true,
    "extractLicenses": true,
    "vendorChunk": false,
    "buildOptimizer": true

In all the configuration.
Since I have more that 5 production deployments.

**Comment by alan-agius4** [comment]
Hi @shabinpshams, as shown in the above example.

By listing common options in configuration named`production` in this case and overridden options in another configuration named `feature`.

Then provide multiple comma-separated configurations in the `configuration` CLI option.

Ex:
``` 
ng build --configuration=production,feature
ng build --configuration=production,feature-foo
```

The command parses the named configurations from left to right. If multiple configurations change the same setting, the last-set value is the final one.

**Comment by shabinpshams** [comment]
> Hi @shabinpshams, as shown in the above example.
> 
> By listing common options in configuration named`production` in this case and overridden options in another configuration named `feature`.
> 
> Then provide multiple comma-separated configurations in the `configuration` CLI option.
> 
> Ex:
> 
> ```
> ng build --configuration=production,feature
> ng build --configuration=production,feature-foo
> ```
> 
> The command parses the named configurations from left to right. If multiple configurations change the same setting, the last-set value is the final one.

Thanks again

But it showing error like 

![image](https://user-images.githubusercontent.com/10242450/79349140-943dcf00-7f3e-11ea-8367-3a71f3d4c9bf.png)

And I am using ngx-build-plus to build.
