### ISSUE TITLE
[error] Error: EPERM: operation not permitted after upgrade from 8 to 9

### ISSUE THREAD

**Issue by jindovu** [angular/angular-cli#17412]
I have just upgrade my project from 8 to 9 but it throught an exception
      can't build my project, please help me resolve this issue
![image](https://user-images.githubusercontent.com/19401173/78656110-1dc32080-78f1-11ea-8145-c81509d06f4d.png)
my dependencies 
![image](https://user-images.githubusercontent.com/19401173/78656293-5f53cb80-78f1-11ea-916f-ce7dd95db328.png)

Thank you so much.

**Comment by alan-agius4** [comment]
@jindovu, as @petebacondarwin mentioned, it seems that the current user doesn't have permissions to read `angular.json`.

Can you please verify your the permissions settings?

**Comment by jindovu** [comment]
I follow this guidline [link](https://update.angular.io/#8.2:9.0l2), But when run it's throw exception and I don't know why, I try to run project angular 8 it's still working fine

**Comment by jindovu** [comment]
I gant permission for project, it's working fine now
Thanks both of you.
