### ISSUE TITLE
Load semantic ui as global css in the application

### ISSUE THREAD

**Issue by rkusuma** [angular/angular-cli#1741]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 8.1

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
This app created using the CLI.
I'm trying to using semantic ui for the css. I'm using their less plugin
```
npm install --save semantic-ui-less
```
How can i use the semantic ui less for global css in my application?
I'm trying to load it in app.component.ts with failure.
```
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styles: [
    require('../../node_modules/semantic-ui-less/semantic.less')
  ],
  encapsulation: ViewEncapsulation.None
})
export class AppComponent {
  title = 'app works!';
}
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
ERROR in ./~/semantic-ui-less/semantic.less
Module build failed: Can't resolve '../../theme.config' in '[PATH]\node_modules\semantic-ui-less\definitions\modules'
 @ [PATH]\node_modules\semantic-ui-less\definitions\modules\transition.less (line 19, column 0)
 near lines:
   
   @import (multiple) '../../theme.config';
   
 @ ./src/app/app.component.ts 20:16-76
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

```

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/1633

**Comment by ozelen** [comment]
having same issue at 1.0.0-beta.28.3
@filipesilva , how did it fix it? any additional configs needed?

**Comment by filipesilva** [comment]
@ozelen you can use the global CSS config to add it. See https://github.com/angular/angular-cli/wiki/overview#global-styles for more info.

**Comment by ozelen** [comment]
Thank you much @filipesilva , it does work! Didn't work for LESS which is quite more customizable...

**Comment by filipesilva** [comment]
It should work for css and less (and the others).

Can you open a new issue with the problem you're having?
