### ISSUE TITLE
Following the upgrade guide from 7 to 8 fails on Windows 

### ISSUE THREAD

**Issue by un33k** [angular/angular-cli#17432]
🐞 Bug report

### Command 

- [ x ] update

### Is this a regression?

No

### Description

Was unable to find an existing issue for the bug I am reporting.  `is:issue, is:open, is:close`.
Following the online `update` [guideline](https://update.angular.io/#7.2:8.2l3), and yet unable to move forward with a simple `ng update`.  

## 🔬 Minimal Reproduction
Private "corporate code" unable to reproduce on a minimal version.  However, I am attaching an image to show the anomaly. 

## 🔥 Exception or Error
<pre><code>
$ ng update @angular/core@8.2.14
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
Using package manager: 'yarn'
Collecting installed dependencies...
Found 0 dependencies.
Package '@angular/core' is not a dependency.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.26
Node: 10.16.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cdk                      7.3.2
@angular/cli                      8.3.26
@angular/flex-layout              7.0.0-beta.24
@angular/http                     7.2.16
@angular/material                 7.3.2
@ngtools/webpack                  7.3.9
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.5.4
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
Windows 10, The plan is to update from 7 to 9, via 8.

![Ng7to8](https://user-images.githubusercontent.com/407537/78918417-66e4b300-7a5e-11ea-80e3-0380ca4f70d9.PNG)

**Comment by alan-agius4** [comment]
Hi @un33k, thanks for reporting this issue. 

However, we will need a reproduction to look into this, the screenshots alone don’t provide enough information to reproduce the problem.

Thanks.

**Comment by un33k** [comment]
Ok, I think I have figured out the steps ... and it may be repo independent. 

1.  Create a repo with ng/cli 7.x.x (& npm install)
2. Run:  node --max_old_space_size=2000 /usr/local/bin/ng update @angular/cli@8 @angular/core@8 --force (We want to simulated a out of heap memory)
3.  Verify that the above command makes node command run out of heap memory
4. Run: node --max_old_space_size=12000 /usr/local/bin/ng update @angular/cli@8 @angular/core@8 --force (Give it plenty of memory)
5. Verify that the command now fails right away with `Package '@angular/core' is not a dependency.` 
6. Remove and reinstall `node_modules`
7. Run: node --max_old_space_size=12000 /usr/local/bin/ng update @angular/cli@8 @angular/core@8 --force
8. Verify it no longer fails with `Package '@angular/core' is not a dependency.` 

So, the proper fix would be to not fail with `Package '@angular/core' is not a dependency.` if we run the command right after a heap memory error.

**Comment by clydin** [comment]
Since the first update command failed, the node_modules directory will most likely be corrupt.  The update process checks the node_modules directory for dependencies.  If it cannot find it there or it is corrupt  then it will present the error message as shown above.
Future improvements to the update command will also support updating without a node modules directory present.  This is being tracked here: https://github.com/angular/angular-cli/issues/17599 & https://github.com/angular/angular-cli/issues/16020
