### ISSUE TITLE
Make sure all assets are managed by Webpack, even when Differential Loading is used

### ISSUE THREAD

**Issue by dirkgroenen** [angular/angular-cli#17430]
# 🚀 Feature request
_I guess it's debatable if we should consider this a bug or a feature request_

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
For one of my clients projects I'm using the `assets` output generated by Webpack's Compilations object to generate a manifest file containing all required assets/sources including an integrity hash. This works great and is very useful for things like 'hot code updating' on Ionic, or offline caching on Progressive Web Apps.

Unfortunately it seems like Differential Loading breaks this feature since it's taking over control over assets outside Webpack.  (At least, that's what I'm thinking based on [this comment](https://github.com/angular/angular-cli/blob/3c771d1b56f369cd5385b911023e4a134b2a1da8/packages/angular_devkit/build_angular/src/utils/webpack-browser-config.ts#L82)). As soon as Differential Loading kicks in we're no longer seeing any of our configured assets appear in Webpack's compilation object. This results in our manifest file being incomplete, breaking the offline/update feature.

### Describe the solution you'd like
I'm not familiar enough with the CLI's code-base to drop a ready-to-use solution. 

### Describe alternatives you've considered
For now a workaround is to prevent differential loading compilation to take place by either using ES5 as our target, or excluding ES5 browsers from `browserslist`. This works, but it would obviously be great to get access to all emitted assets, even when using diff loading. 

I can imagine this request will lose its value while time passes. As soon as Angular drops support for ES5 bundles we would no longer need the diff-loading feature and thus everything would work as expected. That said, until that happens it would be great to have Webpack's assets properly reflect all application assets.

**Comment by alan-agius4** [comment]
Hi @dirkgroenen,

Webpack specific functionality, API's and custom webpack pipelines are not supported and may break in the future.

Since version 8, we have moved a number of phases outside of Webpack such as:
- Downlevelling ES2015 code to ES5
- Localization (i18n)
- Copying of assets

In the future we see more parts of the build to be moved outside of Webpack. Any reason why you don't use `@angular/pwa`?

**Comment by alan-agius4** [comment]
Closing as per above explanation.
