### ISSUE TITLE
Building the CLI from source fails.

### ISSUE THREAD

**Issue by manekinekko** [angular/angular-cli#17437]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

NONE of the above. This issue is related to building the CLI from source

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
When running the `yarn build --local` to build the CLI from source, I got this error:

## 🔬 Minimal Reproduction

0. If you haven't done it already, make a fork of this repo.
0. Clone to your local computer using git.
0. Make sure that you have Node 10.13 or later installed. See instructions here.
0. Make sure that you have yarn installed; see instructions here.
0. Run yarn (no arguments) from the root of your clone of this project to install dependencies.
0. To make a local build: `yarn build --local`

## 🔥 Exception or Error
<pre><code>
fatal: No tags can describe '346172494d91f686ee5f4e1bb8071c8ea2c6f582'.
Try --always, or create some tags.
Error: Command failed: git describe --match v[0-9]*.[0-9]*.[0-9]* --abbrev=7 --tags
fatal: No tags can describe '346172494d91f686ee5f4e1bb8071c8ea2c6f582'.
Try --always, or create some tags.

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at _exec (/Users/wassimchegham/oss/@manekinekko/angular-cli/lib/packages.ts:96:28)
    at _getVersionFromGit (/Users/wassimchegham/oss/@manekinekko/angular-cli/lib/packages.ts:112:30)
    at Object.get version [as version] (/Users/wassimchegham/oss/@manekinekko/angular-cli/lib/packages.ts:170:20)
    at Object.default_1 [as default] (/Users/wassimchegham/oss/@manekinekko/angular-cli/scripts/build.ts:296:29)
error Command failed with exit code 99.
</code></pre>

## 🌍 Your Environment
<pre><code>

git version 2.21.0 (Apple Git-122.2)
Angular CLI: 9.1.0-rc.0
Node: 12.13.0
OS: darwin x64

Angular: 9.1.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.0.0
@angular-devkit/architect-cli      0.0.0
@angular-devkit/benchmark          0.0.0
@angular-devkit/build-angular      0.0.0
@angular-devkit/build-ng-packagr   0.0.0
@angular-devkit/build-optimizer    0.0.0
@angular-devkit/build-webpack      0.0.0
@angular-devkit/core               0.0.0
@angular-devkit/schematics         0.0.0
@angular-devkit/schematics-cli     0.0.0
@angular/cdk                       9.2.0
@angular/cli                       0.0.0
@angular/material                  9.2.0
@angular/pwa                       0.0.0
@bazel/bazel                       2.1.0
@bazel/bazel-darwin_x64            2.1.0
@bazel/buildifier                  0.29.0
@bazel/buildifier-darwin_x64       0.29.0
@bazel/hide-bazel-files            1.5.0
@bazel/jasmine                     1.3.0
@bazel/karma                       1.3.0
@bazel/labs                        1.3.0
@bazel/typescript                  1.3.0
@ngtools/webpack                   0.0.0
@schematics/angular                0.0.0
@schematics/schematics             0.0.0
@schematics/update                 0.0.0
ng-packagr                         9.1.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Did you try to fetch by any chance?

**Comment by manekinekko** [comment]
yes. I tried `git fetch upstream`. With no success.

**Comment by clydin** [comment]
Can you try with a fresh clone?
I just tried and had no issue doing an `yarn build --local`.

**Comment by manekinekko** [comment]
Hi, so I just did a fresh clone, in `/tmp`and I still have the issue

![image](https://user-images.githubusercontent.com/1699357/83527308-eb483500-a4e7-11ea-963a-56dcb2c13795.png)


<details>
  <summary>Full logs</summary>
  <pre>
/tmp/angular-cli on  master is 📦 v0.0.0 via ⬢ v12.13.1 and 🅰️  10.0.0-rc.0 on 🐳 v19.03.8 took 19s
➜ yarn build --local
yarn run v1.22.4
$ node ./bin/devkit-admin build --local
Cleaning...
  Removing dist/...
Removing dist-schema/...
Generating JSON Schema....
Building...
Moving packages to dist/
    @_/benchmark
    @angular-devkit/build-optimizer
    @angular-devkit/core
    @angular-devkit/architect
    @angular-devkit/architect-cli
    @angular-devkit/build-webpack
    @angular-devkit/build-ng-packagr
    @angular-devkit/benchmark
    @angular-devkit/schematics
    devkit
    @ngtools/webpack
    @angular-devkit/build-angular
    @schematics/angular
    @angular/pwa
    @schematics/schematics
    @angular-devkit/schematics-cli
    @schematics/update
    @angular/cli
Merging bazel-bin/ with dist/
    @angular-devkit/architect
    @angular-devkit/build-webpack
    @angular-devkit/build-ng-packagr
    @angular-devkit/schematics
    devkit
    @angular-devkit/build-angular
    @schematics/angular
    @angular/pwa
    @schematics/schematics
    @schematics/update
    @angular/cli
Copying resources...
    @_/benchmark
            3 files total...
            1 resources...
    @angular-devkit/build-optimizer
            27 files total...
            8 resources...
    @angular-devkit/core
            264 files total...
            52 resources...
    @angular-devkit/architect
            31 files total...
            12 resources...
    @angular-devkit/architect-cli
            4 files total...
            1 resources...
    @angular-devkit/build-webpack
            33 files total...
            5 resources...
    @angular-devkit/build-ng-packagr
            31 files total...
            6 resources...
    @angular-devkit/benchmark
            48 files total...
            8 resources...
    @angular-devkit/schematics
            98 files total...
            9 resources...
    devkit
            7 files total...
            6 resources...
    @ngtools/webpack
            63 files total...
            3 resources...
    @angular-devkit/build-angular
            4456 files total...
            20 resources...
    @schematics/angular
            224 files total...
            98 resources...
    @angular/pwa
            15 files total...
            12 resources...
    @schematics/schematics
            30 files total...
            27 resources...
    @angular-devkit/schematics-cli
            4 files total...
            1 resources...
    @schematics/update
            248 files total...
            5 resources...
    @angular/cli
            369 files total...
            41 resources...
Copying extra resources...
Removing spec files...
    @angular-devkit/build-optimizer
      11 spec files found...
    @angular-devkit/core
      62 spec files found...
    @angular-devkit/architect
      4 spec files found...
    @angular-devkit/build-webpack
      4 spec files found...
    @angular-devkit/build-ng-packagr
      2 spec files found...
    @angular-devkit/benchmark
      6 spec files found...
    @angular-devkit/schematics
      42 spec files found...
    @ngtools/webpack
      28 spec files found...
    @angular-devkit/build-angular
      130 spec files found...
    @schematics/angular
      107 spec files found...
    @angular/pwa
      2 spec files found...
    @angular-devkit/schematics-cli
      2 spec files found...
    @schematics/update
      4 spec files found...
    @angular/cli
      4 spec files found...
Building ejs templates...
Setting versions...
    @_/benchmark
fatal: No names found, cannot describe anything.
Error: Command failed: git describe --match v[0-9]*.[0-9]*.[0-9]* --abbrev=7 --tags
fatal: No names found, cannot describe anything.

    at checkExecSyncError (child_process.js:621:11)
    at Object.execSync (child_process.js:657:15)
    at _exec (/private/tmp/angular-cli/lib/packages.ts:97:28)
    at _getVersionFromGit (/private/tmp/angular-cli/lib/packages.ts:113:30)
    at Object.get version [as version] (/private/tmp/angular-cli/lib/packages.ts:171:20)
    at Object.default_1 [as default] (/private/tmp/angular-cli/scripts/build.ts:300:29)
error Command failed with exit code 99.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

/tmp/angular-cli on  master is 📦 v0.0.0 via ⬢ v12.13.1 and 🅰️  10.0.0-rc.0 on 🐳 v19.03.8 took 17s

</pre>
<details>

**Comment by alan-agius4** [comment]
@manekinekko, are you still experiencing this issue? it doesn't appear that anyone else is.

**Comment by manekinekko** [comment]
I can't reproduce this issue with the latest `12.0.0-rc.1`. I am closing this issue.

Thanks for the ping 😉
