### ISSUE TITLE
Bootstrap issue

### ISSUE THREAD

**Issue by MogilicharlaAkhilaja** [angular/angular-cli#17449]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

My content is not staying at the top , when am using data-aos. i.e animate on scroll properties.. i added AOS.init and also some other related links.. It is just scrolling up and disappearing and not staying on the page..
![fade2](https://user-images.githubusercontent.com/60478730/79075016-9836da80-7d0d-11ea-94db-667d1bdef881.png)
![fadeerror](https://user-images.githubusercontent.com/60478730/79075018-9a009e00-7d0d-11ea-9e21-5c2d93451267.PNG)

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular-cli/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
