### ISSUE TITLE
npm ERR! Unexpected token e in JSON at position 4166 while parsing near '...ependencies":{"@an:"e66fa6028d42a26dac47...'

### ISSUE THREAD

**Issue by AnasKamali** [angular/angular-cli#17447]
ng new angularProject 
gives these error
- Installing packages...npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! Unexpected token e in JSON at position 4166 while parsing near '...ependencies":{"@an:"e66fa6028d42a26dac47...'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HOME\AppData\Roaming\npm-cache\_logs\2020-04-11T13_00_11_081Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.
[2020-04-11T13_00_11_081Z-debug.log](https://github.com/angular/angular-cli/files/4464639/2020-04-11T13_00_11_081Z-debug.log)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by ThePCSahu** [comment]
I'm also getting the same error

**Comment by shanjathurshan** [comment]
I'm also getting this error ANyone can you help me ?

**Comment by Amounaim** [comment]
also the same

**Comment by Amounaim** [comment]
Have same issue  Its working try it
npm cache clean --force
npm i -g @angular/cli

**Comment by shanjathurshan** [comment]
Hey, guys Finally I find the solution.
first of all, uninstall node js and npm Also Angular.
npm uninstall -g @angular/cli
npm cache clean --force
npm install -g @angular/cli@8.0.0
 then update angular latest version It will work
