### ISSUE TITLE
Very strange messages when update CLI

### ISSUE THREAD

**Issue by kolkov** [angular/angular-cli#17450]
I think that there is some kind of illogical action ...
![image](https://user-images.githubusercontent.com/3740898/79077487-d1218000-7d0a-11ea-81e2-e4b9f9e3b96c.png)

**Comment by destus90** [comment]
This behavior was described here https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3

> Always use the latest CLI. Starting with 8.3.19 of the CLI, we now use the CLI from the destination version during updates. This means that going forward, updates will take advantage of newer update features automatically.

**Comment by alan-agius4** [comment]
Closing as indeed this is expected and is as per described in the above comment.

**Comment by kolkov** [comment]
No, I'm interested in something completely different.  We already have a new global version, the latest.  We say that it is newer than the installed local one, check the installed local version, find out that it is older than necessary, and begin to download the new version, although we have the global version of the desired version.

**Comment by alan-agius4** [comment]
@kolkov, the local CLI is always preferred over the global. 

The main usage of the global CLI is to have `ng` in global path, so that you can run `ng` commands directly, without the need of `yarn` or `npx`
