### ISSUE TITLE
typings issues in angular-cli 1.0.0-beta.11-webpack.2

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular-cli#1745]
**1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)**
`El Capitan 10.11.6`

**2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:**
```
(node:69005) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: darwin x64
```

**3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.**

It is a whole new project, just did
```
npm install -g angular-cli@webpack
ng new my-project
npm install --save-dev angular-cli@webpack
```

**4. The log given by the failure. Normally this include a stack trace and some
   more information.**

The app runs well, but seems having some typings issues (red parts, my IDE is WebStorm 2016.2.2). And seems only happening with RC5 new things:
**app.module.ts**
![image](https://cloud.githubusercontent.com/assets/3375461/17785616/7a6f2fe0-654f-11e6-97fe-afd9bd4d5134.png)
**main.ts**
![image](https://cloud.githubusercontent.com/assets/3375461/17785626/872df518-654f-11e6-9038-7fbe8abe2728.png)

**Comment by mmrath** [comment]
Looks like an ide glitch. I use idea (same as WS) and types work fine. Did you try reimporting your project. Look like it did not index the RC5 dependencies

**Comment by Hongbo-Miao** [comment]
Thanks, @mmrath.

This morning I got an update from WebStorm.
After updating from 162.1628.21 to 162.1628.41. The issue seems gone!

**Comment by stefanaerts** [comment]
I have the same issue when i installed angular-cli@1.0.0-beta.11-webpack.2
--------------------------------
my output of ng--version:
--------------------------------
ng --version
(node:4132) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.1
os: darwin x64

-----------------------------
my output of of ng new emptyApp:
-----------------------------
ng new emptyApp
(node:4087) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing ng2
  create .editorconfig
  create README.md
  create src/app/app.component.css
....
-------------------------------

this is the output of my global npm packages installed:
npm list -g -depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.11-webpack.2
├── bower@1.7.9
├── firebase-tools@3.0.7
├── npm@3.10.6
├── npm-check-updates@2.8.0
├── peerflix@0.35.1
├── polymer-cli@0.14.0
└── typings@1.3.2

npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6

**Comment by filipesilva** [comment]
@stefanaerts I don't see how what you posted is related to this issue. Please open a new issue if you're experiencing problems

**Comment by stefanaerts** [comment]
???  The issue is that the deploy does not work
Op 23 aug. 2016 17:12 schreef "Filipe Silva" <notifications@github.com>:

**Comment by filipesilva** [comment]
@stefanaerts there is nothing about deploy in your comment on this issue. I have to reiterate: please open a new issue if you are still having problems, this issue is already closed with a resolution.

**Comment by stefanaerts** [comment]
Sry, i dont know how i got on this tread. But the issue was indeed closed and "they say with a solution" but the solution didnt work.
