### ISSUE TITLE
"ng new" not working, says there is a syntax error

### ISSUE THREAD

**Issue by tylerchasefranklin** [angular/angular-cli#17462]
I am trying to start a new Angular project and have used Angular CLI before and it worked, however I cannot get "ng new" to work now. I have uninstalled and reinstalled angular cli, and I have the most up to date versions of node and npm. 

When I try to use "ng new angular-project" now this is what I get:

/usr/local/lib/node_modules/@angular/cli/bin/ng:23
  );
  ^
SyntaxError: Unexpected token )
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

Not sure what else I am missing. Any help is appreciated!

**Comment by clydin** [comment]
Can you provide the output of `node --version` from the same location the `ng new` was attempted?

**Comment by tylerchasefranklin** [comment]
node --version

v7.4.0

**Comment by clydin** [comment]
The Angular CLI requires a minimum Node.js version of v10.13 with v12 recommended for optimal performance.
Can you try updating the [Node.js](https://nodejs.org/) version to see if that resolves the problem?

**Comment by tylerchasefranklin** [comment]
That fixed it. I apologize, I had run command line functions to update, but
I guess I did something wrong on that part. Sorry for wasting your time,
but thank you for the help!

-Chase

**Comment by clydin** [comment]
No problem at all.  I'm glad it's working now.
I put together a [fix](https://github.com/angular/angular-cli/pull/17463) so that users should get a message instead of a syntax error in the future.
