### ISSUE TITLE
TypeScript constructor.name not working in ng build --prod code

### ISSUE THREAD

**Issue by OisinNolan** [angular/angular-cli#17460]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

TypeScript class.constructor.name working fine locally but when used in 'ng build --prod' version it was not returning correct name

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
As mentioned in the above comment this is expected, as during production builds class names get mangled.

If you wish to not mange class names, you can you use a custom builder to provide custom terser options. That being said, it’s important to point out that custom builders are not supported by the Angular tooling team.
