### ISSUE TITLE
How to install bootstrap + jQuery

### ISSUE THREAD

**Issue by StevePavlin** [angular/angular-cli#1746]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.4
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
None required.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
None required.

5. Mention any other details that might be useful.

Right now, I'm using the following code to include bootstrap CSS into my project:

```
@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css', 'shared/bootstrap.min.css'],
  encapsulation: ViewEncapsulation.None
})
```

As you can see, I am basically injecting the stylesheet globally in AppComponent. 

This works fine and the bootstrap CSS is injected into the main.bundle and I can reference the classes (ng2-bootstrap), but some of the javascript does not work since it needs the bootstrap.min.js (eg. opening and closing a modal).

I'm wondering, how do I solve this issue and have libraries I need injected without referencing them in index.html? I don't see a webpack config file to use, so I was wondering the way to do it properly.

**Comment by filipesilva** [comment]
I actually just added a PR to explain this. See https://github.com/angular/angular-cli/pull/1747.

It doesn't work *right now* since it depends on https://github.com/angular/angular-cli/pull/1633 for the global styles support.
