### ISSUE TITLE
Auto generate port 

### ISSUE THREAD

**Issue by symphony2014** [angular/angular-cli#17464]
# 🚀 Feature request
-  1.We both know the default port is 4200, but if  the 4200 is already used, the error was throw :
```An unhandled exception occurred: Port 4200 is already in use. Use '--port' to specify a different --port```, why not auto generate a port without conflicting existing port?
-  2.When debug multi angular application, it was inconvenient to auto assign new port without conflict with existing port.But for now it was really annoying assign a not-conflicting port.

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

**Comment by alan-agius4** [comment]
Hi, in such case you can use port `0` which is a wildcard port.

More info about port 0 https://www.lifewire.com/port-0-in-tcp-and-udp-818145
