### ISSUE TITLE
StackBlitz - error when downloading project

### ISSUE THREAD

**Issue by JenWilson82653** [angular/angular-cli#17474]
When you download the project from [this link](https://stackblitz.com/angular/odpeknvxnlq?file=src%2Fapp%2Fapp.component.ts) 
and unzip into a folder and run ng serve 
.
.
.
.
.
does it run?
.
.
.
.
.
.
.

What error do you get?

Is it the same one reported two years ago?

Will I see it two years from now?

Four years?

**Comment by alan-agius4** [comment]
Hi @@JenWilson82653, thanks for reporting this. 

Unfortunately, this issue is not caused by Angular, but rather StackBlitz as their project structure is slightly different from that of the standard `ng new` and has invalid configuration in `angular.json`.

We'll try to reach out to StackBlitz to get this sorted. Apologies for the inconvenience.

**Comment by EricSimons** [comment]
Hey all- I'm digging into this now, will circle back once I've ID'd the root issue. Should be able to get a fix in shortly

**Comment by alan-agius4** [comment]
Thanks for your quick action. Feel free to ping me on slack if you need any help @EricSimons.

**Comment by EricSimons** [comment]
Awesome, thanks @alan-agius4!

I spent the past hour or so investigating and I think I've figured out the core issue- seems like it's a bug in our project scaffolding/downloading logic. I'm going to put together a fix first thing tomorrow, test on staging and then deploy to prod. Will circle back here once it's live to confirm all looks good on your end 👍

**Comment by EricSimons** [comment]
This is now live on prod and should be good to close! 💥

**Comment by alan-agius4** [comment]
Thanks @EricSimons for the quick turnaround. I tried this and it seems to be working great.
