### ISSUE TITLE
exclude file for ng build --prod

### ISSUE THREAD

**Issue by foxjazz** [angular/angular-cli#17471]
As part of my angular project I have a config file /src/config/config.json which is deployed to all the servers.  During build of this file I ant to exclude. I thought filereplacements would have a remove function, it does not.  Do I need to write into the script to remove that after the fact?
It would be cleaner if there was an option.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
