### ISSUE TITLE
Differential loading with es5 support enabled doesn't inject es5 bundles in the extra html files generated through @angular-builders/custom-webpack

### ISSUE THREAD

**Issue by Balaji-Arulvanan** [angular/angular-cli#17481]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem...
Recently we updated our project to Angular9.1.0 from Angularv7.3.8. 
We use @angular-builders/custom-webpack to generate index files for higher environments. After migration, i enabled Differential loading with es5 support enabled(With browserslist for IE11).
After build, i can see that the generated htmls through custom webpack builder doesn't have es5 builds injected in it. It has all the es2015 bundles and polyfills-es5. Since it doesn't have other es bundles in it, it will fail in IE. 

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-kzvnyl

## 🌍 Your Environment
Angular cli 9.1.1
Nod 10.15.3
Os: Win32

"@angular/animations": "^9.1.0",
"@angular/common": "^9.1.0",
"@angular/compiler": "^9.1.0",
"@angular/core": "^9.1.0",
"@angular/forms": "^9.1.0",
"@angular/platform-browser": "^9.1.0",
"@angular/platform-browser-dynamic": "^9.1.0",
"@angular/platform-server": "^9.1.0",
"@angular/router": "^9.1.0",
"@angular/cli": "^9.1.0",
"@angular/compiler-cli": "^9.1.0",
"@angular/language-service": "^9.1.0",
"@angular-builders/custom-webpack": "^9.0.0",
"@angular-builders/dev-server": "^7.3.1",
"@angular-devkit/build-angular": "~0.901.0",

**Comment by alan-agius4** [comment]
Hi @Balaji-Arulvanan,

This seems like an issue in `@angular-builders/custom-webpack` which is not supported by the Angular team.

Please file an issue on their issue tracker.

**Comment by Balaji-Arulvanan** [comment]
Thanks for that @alan-agius4...I will raise a request in that repo
