### ISSUE TITLE
VSCode: Debug breakpoints not working for ng test

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#17488]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure

### Description

Breakpoints are not hit when debugging unit tests inside an angular workspace.

## 🔬 Minimal Reproduction

- `> npx @angular/cli new applications --createApplication=false --strict=true`
- `> cd applications`
- `> yarn ng generate application admin-console --defaults=true`
- `> mkdir .vscode && touch .vscode/launch.json`

Add this snippet to `.vscode/launch.json`

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Test",
      "url": "http://localhost:9876/debug.html",
      "webRoot": "${workspaceFolder}"
    }
  ]
}
```

- Open `applications` folder in Visual Studio Code and add breakpoints to any test case inside `projects/admin-console/src/app/app.component.spec.ts`
- Start debugging (This should launch a new chrome window)
- You will notice that the breakpoints are not hit
  <img width="1240" alt="test_workspace" src="https://user-images.githubusercontent.com/13006107/79496878-cc9fe480-7ff4-11ea-8754-7aecc502f879.png">

## 🔥 Exception or Error

After setting `"trace": "verbose"` in `launch.json`, this is what I saw in `/var/folders/d_/3l10r4h12g10trnbxjkcl__h0000gn/T/vscode-chrome-debug.txt`

<pre><code>
[19:15:59.739 UTC] SourceMaps.setBP: /Users/p/applications/projects/admin-console/src/app/app.component.spec.ts can't be resolved to a loaded script. It may just not be loaded yet.
[19:15:59.739 UTC] Paths.setBP: No target url cached yet for client path: /Users/p/applications/projects/admin-console/src/app/app.component.spec.ts.
</code></pre>

## 🌍 Your Environment

<pre><code>
yarn run v1.22.4
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 13.13.0
OS: darwin x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
    
Done in 1.00s.

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @prabh-62,

Firstly, thanks for the excellent reproduction steps.

Can you please try the below;
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Test",
            "url": "http://localhost:9876/debug.html",
            "webRoot": "${workspaceFolder}/projects/admin-console",
            "sourceMaps": true,
            "sourceMapPathOverrides": {
              "webpack:/*": "${webRoot}/*",
              "/./*": "${webRoot}/*",
              "/src/*": "${webRoot}/*",
              "./*": "${webRoot}/*",
              "_karma_webpack_/*": "${webRoot}/*",
              "/./~/*": "${workspaceFolder}/node_modules/*"
            }
        }
    ]
}
```

Can read more about this here: https://github.com/microsoft/vscode-recipes/tree/master/Angular-CLI

**Comment by prabh-62** [comment]
Thank you 🤗

I am able to debug now.
