### ISSUE TITLE
[ng9.1.1] stuck on 95% emitting index-html-webpack-plugin

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#17492]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.2

### Description
When i am using this package https://github.com/akserg/ng2-slim-loading-bar
It has old rxjs import path after altering that in __ivy__ngcc/src/slim-loading-bar.service,js it will always stuck at 95%
 

## 🔥 Exception or Error
<pre><code>

ERROR in ./node_modules/ng2-slim-loading-bar/__ivy_ngcc__/src/slim-loading-bar.service.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'D:\project\node_modules\ng2-slim-loading-bar\__ivy_ngc

i changed import path there it will always stuck at 95%
</code></pre>

## 🌍 Your Environment
<pre><code>

ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 10.16.3
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cdk                      9.2.0
@angular/cli                      9.1.1
@angular/material                 9.2.0
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by indraraj26** [comment]
even if i changed rxjs import path before ivy compiling then also its stuck on 95%

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by indraraj26** [comment]
now even after removing that package still it is stuck on 95%, yesterday night everything was working perfectly.

**Comment by alan-agius4** [comment]
@indraraj26, I am not sure what's going on here. I suggest to revert any changes done and go back to a working state. If you added a new node package, remove it from the `package.json`, remove node_modules and do a fresh install.

After that try to create minimal reproduction show casing the issue. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by indraraj26** [comment]
Hi @alan-agius4 , yes if i rollback to old commits which was merged by other guy in morning then it is working fine. If i checked his merge changes there is no extra package installed.

**Comment by alan-agius4** [comment]
In that case, it must have been something which is related to the code. 

If you can determine what piece of code resulted in the un-actionable error it would be great so we can determine if we can do anything from our end. 

Thanks.

**Comment by indraraj26** [comment]
Hi @alan-agius4 , Thank you for your instant support. 
What i have done its working now btw i am not able to reproduce 😞 
```
git reset --hard oldcommit
git merge featureBranch
npm start
```
