### ISSUE TITLE
Ng build stuck at 11% 13/13 modules - node maxing out CPU

### ISSUE THREAD

**Issue by jossmt** [angular/angular-cli#17498]
I upgraded node version and updated Developer Tools on my macbook and when trying to build my angular project it is getting stuck at 11% 13/13 modules and cpu usage is upwards of 150%...

Mac details:
MacBook Pro (16-inch, 2019)
Mac OS Catalina 10.15.3 

Can anyone help? I have provided by package.json below:

{
  "name": "collaborate-ui",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.2",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "~9.1.2",
    "@angular/compiler": "~9.1.2",
    "@angular/core": "~9.1.2",
    "@angular/forms": "~9.1.2",
    "@angular/localize": "^9.0.7",
    "@angular/material": "^9.2.0",
    "@angular/platform-browser": "~9.1.2",
    "@angular/platform-browser-dynamic": "~9.1.2",
    "@angular/router": "~9.1.2",
    "@ng-bootstrap/ng-bootstrap": "^6.0.1",
    "bootstrap": "^4.4.1",
    "jquery": "^3.4.1",
    "popper": "^1.0.1",
    "popper.js": "^1.16.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.900.7",
    "@angular/cli": "~9.1.1",
    "@angular/compiler-cli": "~9.1.2",
    "@angular/language-service": "~9.1.2",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "node-gyp": "^6.1.0",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5"
  }
}

Things I have tried:
Reinstalling node/npm
Reinstalling angular/cli angular/core etc.
Removing all node modules and reinstalling
Updating fsevents
Updating node-gyp
Restarting altogether

I have heard mention of fsevents needing to be a certain version. When running npm ls fsevents i get:

├─┬ @angular-devkit/build-angular@0.900.7
│ ├─┬ webpack@4.41.2
│ │ └─┬ watchpack@1.6.1
│ │   └─┬ chokidar@2.1.8
│ │     └── fsevents@1.2.12 
│ └─┬ webpack-dev-server@3.9.0
│   └─┬ chokidar@2.1.8
│     └── fsevents@1.2.12 
├─┬ @angular/compiler-cli@9.1.2
│ └─┬ chokidar@3.3.1
│   └── fsevents@2.1.2 
└─┬ popper@1.0.1
  ├─┬ mocha@7.1.1
  │ └─┬ chokidar@3.3.0
  │   └── fsevents@2.1.2  deduped
  └─┬ rijs.resdir@1.4.4
    └─┬ chokidar@1.7.0
      └── fsevents@1.2.12 

Evidently I cannot update fsevents version for chokidar - what is the workaround here? 
Any help much appreciated!

**Comment by alan-agius4** [comment]
Can you please share the output of `ng version`?

**Comment by jossmt** [comment]
After running ng version:

@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@angular/cdk                      9.2.1
@angular/localize                 9.1.2
@angular/material                 9.2.1
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

**Comment by julmot** [comment]
I also have the problem of a stuck `ng serve` since today.

**Comment by julmot** [comment]
Update: In my case it seems to be caused by node-sass. Unfortunately the log of `ng serve` will not output anything before it gets stuck with `--verbose=true` so I still don't know the reason. But I've found the reason in my app: It was caused by an import of mixins/variables but with no CSS class inside that file. So the only content was that import. When removing that, it's no longer stuck.

**Comment by elucidsoft** [comment]
I have also seen this behavior constantly with the latest versions of everything installed. I NEVER saw this behavior before I updated everything to the latest versions.  This is 100% a bug of some sort, it happens ALL the time to me for no apparent reason.  It happens in different locations, just now it got stuck hashing 88% and just sat there...

**Comment by alan-agius4** [comment]
Hi, is it possible to share a reproduction of some sort even privately?

Unfortunately, without a reproduction there is not much that we can do.

Thanks.

**Comment by elucidsoft** [comment]
This is an odd one, I deleted my node_modules and ran npm i to get a fresh update and it hasn't happened in several days.  Very odd.

**Comment by Maksiemens** [comment]
same problem when I updated project from angular 9.1.9 to 9.1.11.
compiling freeze with file in cmd dist\cjs.js??ref--13-3. Than my pc out of memory. I had to downgrade project

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
