### ISSUE TITLE
`ng build my-lib` does not take correct ecma target for Typescript 3.8 private fields

### ISSUE THREAD

**Issue by kaplan81** [angular/angular-cli#17501]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

I am trying to use a new Typescript feature introduced in 3.8 version: ECMAScript Private Fields.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#ecmascript-private-fields

```ts
@Injectable({
  providedIn: 'root',
})
export class MyConfigFileService {
  #configs: any;

  get configs(): any {
    return this.#configs;
  }

  set configs(configs: any) {
    this.#configs = configs;
  }
}
```

## 🔬 Minimal Reproduction

I am using the code above in a library but most likely it also happens anywhere else.

I try to build by running:

```bash
ng build my-lib
```

## 🔥 Exception or Error

And I get this error:

<pre><code>
Compiling TypeScript sources through ngc
ERROR: projects/@mcm/ngx-services/src/lib/config-file/config-file.service.ts:19:3 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

19   #configs: any;
     ~~~~~~~~

An unhandled exception occurred: projects/@mcm/ngx-services/src/lib/config-file/config-file.service.ts:19:3 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

19   #configs: any;
     ~~~~~~~~
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.1
Node: 12.13.1
OS: darwin x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.1
@angular-devkit/build-angular      0.901.1
@angular-devkit/build-ng-packagr   0.901.1
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.1
@angular-devkit/core               9.1.1
@angular-devkit/schematics         9.1.1
@angular/cli                       9.1.1
@ngtools/webpack                   9.1.1
@schematics/angular                9.1.1
@schematics/update                 0.901.1
ng-packagr                         9.1.1
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @kaplan81, this is expected because a library is built in 2 modes, ES2015 and ES5, thus you cannot use features which work only for ES2015+.

More information: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs

**Comment by kaplan81** [comment]
@alan-agius4 is there any way to disable that? The project platform is only the latest Chrome browser.
