### ISSUE TITLE
If someone deleted the e2e folder is there a way of regenerating it?

### ISSUE THREAD

**Issue by b-anani** [angular/angular-cli#17503]
Someone deleted the e2e folder from our repository and I was wondering if there was a CLI tool to regenerate the e2e folder and it's files?

**Comment by alan-agius4** [comment]
You can use git to restore a previous version.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
