### ISSUE TITLE
Localize build option does not update asset paths correctly

### ISSUE THREAD

**Issue by a88zach** [angular/angular-cli#17514]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli

### Is this a regression?

 I'm not sure if this is regression as we just started using this option

### Description

 When you build a localized version of the application, the style urls are not updated correctly with the language path

## 🔬 Minimal Reproduction

 
 Steps to reproduce:
clone:  https://github.com/a88zach/36735-angular-bug
<pre><code>
$ npm i
$ npx ng build --configuration=production --baseHref=/foo/ --localize
</code></pre>

After the build is complete, open up the styles.xxx.css file in the en or es folder and notice that only the baseHref of /foo/ was added to the asset url's.  However, the base element in the index.html files have been updated correctly with the baseHref and language path

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 12.14.1
OS: darwin x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by a88zach** [comment]
Any update on this one?  The bug prevents us from building with the localize option and causes us to have to build once for each locale

**Comment by clydin** [comment]
The defect in this case is that the base HREF is present in the CSS and is not related to localization.  An HTML base HREF is applied at runtime to all relative URLs by the browser and is not intended to be embedded (and hard coded) into the application code by the build system.  The reason this was happening was because of the use of the Webpack specific tilde usage in the URL combined with improper accounting of the tilde within the build system.  Please note that Webpack specific features should be used with caution and are not officially supported.  Webpack is considered an internal implementation detail of the build system and its use and configuration may change overtime.

**Comment by alan-agius4** [comment]
Closing as per above explanation.

**Comment by a88zach** [comment]
This should not be closed as the comment above does not fix the defect.  I even attached a example that reproduces the issue.  This example uses the documentation from the Angular website.   Please reopen this ticket and look at the example I created

**Comment by alan-agius4** [comment]
Hi @a88zach, as explained above what is happening is when using the `~/` the baseHref will be included hard coded in the CSS output file. `~/` is a Webpack specific features and as all Webpack specific features should be used with caution and at own risk as they are not officially supported.

In your case, you can use a relative url ex: `assets/images/Homer_Simpson_2006.png`, where with this approach the image will get hashed and copied out of the box and thus you don't need to specify it in the `assets` array.
