### ISSUE TITLE
ng new should pickup my structure

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#17513]
Hi Team,

Is there any way to modify ng new to pick up my structure so that when other developer will start any project they will have same core structure.

I have feature module with some sort of basic component in it like @core, @auth @shared that should generate automatically. When someone is trying to create new project.

Thank you.

**Comment by alan-agius4** [comment]
Hi @indraraj26, you'd need to create a custom schematic that extends the default `ng new` schematic.

More info about schematics can be found here: https://angular.io/guide/schematics

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
