### ISSUE TITLE
While creating the new project using command: "ng new first-project" it takes infinite time in installing and creating it. 

### ISSUE THREAD

**Issue by Adi-11** [angular/angular-cli#17512]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Material issues at: https://github.com/angular/material2/issues/new

For the time being, we keep Angular Material issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Most likely is caused by either your internet connection, proxy or NPM pop might be experiencing some issues.

Unfortunately, this is un-actionable from our end.
