### ISSUE TITLE
expose Angular-CLI VERSION as part of API

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#17527]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Currently, I can can to the following with the Angular API, but not with the Angular-CLI API:
```typescript
import { Component, VERSION as ngVersion } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  angularVersion = ngVersion.full;
}
```
And the corresponding HTML:
```html
<h1>Angular version: {{ angularVersion }}</h1>
````

### Describe the solution you'd like
I would like to be able to do the following in addition to what is shown above:
```typescript
import { VERSION as cliVersion } from '@angular/cli';

angularCliVersion = cliVersion.full;
```
and the corresponding HTML:
```html
<h2>Angular-CLI version: {{ angularCliVersion }}</h2>
````

### Describe alternatives you've considered
Hard-coding the Angular-CLI version number in the component.ts file.

**Comment by alan-agius4** [comment]
Hi @fmorriso,
`@angular/cli` is a Node.js application and shouldn’t be imported and used in a browser application.

**Comment by alan-agius4** [comment]
Hi @fmorriso, thanks for this request.

None-the-less, the above use-case doesn’t justify why version should be added as part of the public API.
