### ISSUE TITLE
ng serve not using environment.dev.ts

### ISSUE THREAD

**Issue by aggarwalankush** [angular/angular-cli#1752]
1. OS - `Mac OSX El Capitan`

2. Versions:
```
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: darwin x64

```
3. Repro: None of the following using `environment.dev.ts`
```
ng serve
ng serve --dev
ng serve --env=dev

```
It works with `ng build --dev`

**Comment by filipesilva** [comment]
I've just tested this on latest master and as far as I can tell works. I think I inadvertently fixed this issue in https://github.com/angular/angular-cli/pull/1633.
