### ISSUE TITLE
ng serve not working 

### ISSUE THREAD

**Issue by Ekscelencja** [angular/angular-cli#17529]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

Today I started working on a new project. Got all my files setup with "npm i" etc. When I'm trying to serve the app with "ng s" command I'm stopped by this error:
**An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-angular:dev-server
See "C:\Users\Eksce\AppData\Local\Temp\ng-7tSsY3\angular-errors.log" for further details.**

## 🔬 Minimal Reproduction

npm i --only=dev

ng s

## 🔥 Exception or Error
<pre><code>
An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-angular:dev-server
See "C:\Users\Eksce\AppData\Local\Temp\ng-7tSsY3\angular-errors.log" for further details.

</code></pre>

**angular-errors.log contents**

<pre><code>
[error] Error: Could not find the implementation for builder @angular-devkit/build-angular:dev-server
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Users\Eksce\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js:56:19)
    at ServeCommand.initialize (C:\Users\Eksce\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:134:55)
    at async ServeCommand.validateAndRun (C:\Users\Eksce\AppData\Roaming\npm\node_modules\@angular\cli\models\command.js:124:9)
    at async Object.runCommand (C:\Users\Eksce\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:201:24)
    at async default_1 (C:\Users\Eksce\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js:62:31)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.2
Node: 12.16.2
OS: win32 x64

Angular: <error>
... animations, cdk, common, compiler, core, forms, material
... platform-browser, platform-browser-dynamic, pwa, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              9.1.2 (cli-only)
@angular-devkit/schematics        9.1.2 (cli-only)
@angular/cli                      7.3.9
@angular/compiler-cli             7.2.15
@angular/language-service         7.2.15
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.4 (cli-only)
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, not quick sure how you ending up in the above state. I am seeing a lot of version mismatches.

My recommendation would be to start fresh.

```
npm i -g @angular/cli@latest
ng new
```

**Comment by Ekscelencja** [comment]
> 
> 
> Hi, not quick sure how you ending up in the above state. I am seeing a lot of version mismatches.
> 
> My recommendation would be to start fresh.
> 
> ```
> npm i -g @angular/cli@latest
> ng new
> ```

The project is downloaded (just started working today in a new company). So I cloned the files from the bitbucket, got to downloaded folder with command prompt, npm i --only=dev (otherwise the @angular-devkit/build-angular wouldnt be installed) and im stuck in that exact point

**Comment by alan-agius4** [comment]
Hi @Ekscelencja, 

Unfortunately this seems to be related to your project and how it was setup.

`npm i --only=dev`, will leak to installing only development dependencies, but during development we need both dev and prod dependencies. Thus, you need to run `npm i`.
