### ISSUE TITLE
inlineStyle and inlineTemplate should have precedence when used with minimal

### ISSUE THREAD

**Issue by EatonZ** [angular/angular-cli#17528]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
PR https://github.com/angular/angular-cli/pull/16988 has changed project generation in a way that prevents external styles and templates from being generated when using the `minimal` flag with `ng new`.

### Describe the solution you'd like
If you prefer this behavior by default, that is fine, but can you please make it so that when `inlineStyle=true` and `inlineTemplate=true` with `minimal=true`, it will actually generate the external files? Right now, those settings are ignored when used with minimal, and I don't believe they should be.

### Describe alternatives you've considered
I just regenerate the app component once the project has spun up (after removing inlineTemplate and inlineStyle from angular.json). That sets everything up the way I want, but it's still an extra step I'd like to avoid.

**Comment by alan-agius4** [comment]
Hi,

The mentioned PR aligned components generated after the initial app scaffolding to always be inlined, as minimal always generated the app component with inline templates and styles.

Possible we can remove the “feature” to auto inline styles and templates when using ‘minimal`.

That said, it’s important to point that minimal projects are considered to be “throw away” and only used for quick testing and prototyping.

//cc @clydin thoughts?

**Comment by EatonZ** [comment]
Hi @alan-agius4, it didn't always do that. I have an older project from the version 7 days where inline styles & templates were not forced with minimal. I could be mistaken, though.

I have reviewed several issues where you have brought up those points about minimal. The issues appear to be around linting and testing. Are there any other notable issues that could surface when using minimal?

**Comment by alan-agius4** [comment]
> I have reviewed several issues where you have brought up those points about minimal. The issues appear to be around linting and testing. Are there any other notable issues that could surface when using minimal?

Yes, in most cases the effected areas are linting and testing, but there might also be broken journeys such as incorrect/extra files being generated when using other schematics such as generating a library.

**Comment by EatonZ** [comment]
@alan-agius4 Thanks for clarifying. I'll limit my time with these project types.
Still, I think my suggestion makes sense and should be implemented.
