### ISSUE TITLE
After upgrade buil-angular > 0.901.1, Error: Failed to execute 'send' on 'XMLHttpRequest'

### ISSUE THREAD

**Issue by KrakenTyio** [angular/angular-cli#17532]
# 🐞 Bug report

When i upgrade yesterday and today `@angular-devkit/build-angular` to bigger version than `0.901.1` unit tests throw many issues, no matter if is on docker selenium standalone chorme or local chrome

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I need to mention i use `@angular-builders/custom-webpack` but there is probably no problem
Important is, tests are started, few of them are pass. On local testing all tests are reported as succes, but errors are present in terminal console.

<pre>Chrome 81.0.4044.113 (Linux x86_64) ERROR
  Uncaught NetworkError: Failed to execute &apos;send&apos; on &apos;XMLHttpRequest&apos;: Failed to load &apos;ng:///SidebarAbstract/%C9%B5dir.js&apos;.
  at http://localhost:9876/_karma_webpack_/polyfills.js:11719:39
  
  Error: Failed to execute &apos;send&apos; on &apos;XMLHttpRequest&apos;: Failed to load &apos;ng:///SidebarAbstract/%C9%B5dir.js&apos;.
      at http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:2874:1
      at XMLHttpRequest.proto.&lt;computed&gt; [as send] (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:1449:1)
      at Array.&lt;anonymous&gt; (node_modules/source-map-support/browser-source-map-support.js:107:134)
      at node_modules/source-map-support/browser-source-map-support.js:101:106
      at Array.&lt;anonymous&gt; (node_modules/source-map-support/browser-source-map-support.js:107:501)
      at node_modules/source-map-support/browser-source-map-support.js:101:106
      at a (node_modules/source-map-support/browser-source-map-support.js:101:312)
      at b (node_modules/source-map-support/browser-source-map-support.js:104:356)
      at node_modules/source-map-support/browser-source-map-support.js:105:245
      at Array.map (&lt;anonymous&gt;)
      at Function.f [as prepareStackTrace] (node_modules/source-map-support/browser-source-map-support.js:105:211)
      at Object.onHandleError (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-testing.js:139:1)
      at ZoneDelegate.handleError (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:368:1)
      at Object.onHandleError (http://localhost:9876/_karma_webpack_/node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:41820:1)
      at ZoneDelegate.handleError (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:368:1)
      at Zone.runTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:170:1)
      at invokeTask (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:480:1)
      at ZoneTask.invoke (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:469:1)
      at timer (http://localhost:9876/_karma_webpack_/node_modules/zone.js/dist/zone-evergreen.js:2552:1)
</pre>

when i revert back to 0.901.1 evething works
all deps are latests

```js
# karma.conf.js
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html
const webdriver = require('selenium-webdriver');

module.exports = function (config) {
    const { isDocker } = require('./core/src/helpers/is-docker');

    // Get local IP for selenium runner
    const address = require('./builder/helpers').getMyIPAddress(false);

    const configuration = {
        basePath: '',
        frameworks: ['jasmine', '@angular-devkit/build-angular'],
        plugins: [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-selenium-webdriver-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage-istanbul-reporter'),
            require('karma-junit-reporter'),
            require('karma-mocha-reporter'),
            require('@angular-devkit/build-angular/plugins/karma'),
            { 'reporter:jasmine-seed': ['type', JasmineSeedReporter] }
        ],

        reporters: ['mocha', 'coverage-istanbul', 'kjhtml', 'junit', 'jasmine-seed'],

        coverageIstanbulReporter: {
            reports: ['html', 'text-summary', 'lcovonly', 'json'],
            dir: './coverage',
            fixWebpackSourcePaths: true,
            'report-config': {
                html: {
                    subdir: 'html'
                },
                json: {
                    file: 'coverage.json'
                }
            }
        },

        // the default configuration
        junitReporter: {
            outputDir: './coverage',
            outputFile: './karma-junit.xml',
            suite: 'Crossuite Karma Unit',
            useBrowserName: false,
            nameFormatter: (browser, result) => {
                return result.description;
            },
            classNameFormatter: (browser, result) => {
                return result.suite[0];
            }
            // properties: {}
        },

        port: 9876,
        colors: true,
        logLevel: config.LOG_WARN,
        // autoWatch: true, // already in parent config
        browsers: [ /*'ChromeTravisCi'*/ 'Chrome'],
        // singleRun: false,  // already in parent config
        client: {
            clearContext: false, // leave Jasmine Spec Runner output visible in browser
            jasmine: {
                random: true,
                seed: ''
            }
        },
        browserNoActivityTimeout: 60000 * 100,
        restartOnFileChange: true,

        hostname: isDocker() && address && address.length ? address[0] : 'localhost',
        customLaunchers: {
            ChromeTravisCi: {
                base: 'ChromeHeadless',
                browserName: 'Chrome',
                flags: [
                    '--no-sandbox',
                    '--headless',
                    '--disable-gpu',
                    '--disable-web-security',
                    '--disable-translate',
                    '--disable-extensions',
                    '--disable-dev-shm-usage',
                    '--hide-scrollbars',
                    '--mute-audio'
                    // '--remote-debugging-port=9223'
                ]
            },
            ChromeSelenium: {
                base: 'SeleniumWebdriver',
                browserName: 'Chrome',
                flags: [
                    '--no-sandbox',
                    '--headless',
                    '--disable-gpu',
                    '--disable-web-security',
                    '--disable-translate',
                    '--disable-extensions',
                    '--disable-dev-shm-usage',
                    '--hide-scrollbars',
                    '--mute-audio'
                    // '--remote-debugging-port=9223'
                ],
                getDriver: function () {
                    return new webdriver.Builder()
                        .forBrowser('chrome')
                        .usingServer('http://selenium-chrome:4444/wd/hub')
                        .build();
                }
            }
        }
    };

    if (process.env.TRAVIS || config.browsers.includes('ChromeTravisCi') || config.browsers.includes('ChromeSelenium')) {
        if (config.browsers.includes('ChromeSelenium')) {
            configuration.browsers = [
                'ChromeSelenium'
            ];
        } else {
            configuration.browsers = [
                'ChromeTravisCi'
            ];
        }
    }

    if (configuration.browsers.includes('ChromeTravisCi') || configuration.browsers.includes('ChromeSelenium')) {
        const kjhtml = configuration.reporters.indexOf('kjhtml');
        if (kjhtml > -1) {
            configuration.reporters.splice(kjhtml, 1);
        }

        const chrome = configuration.browsers.indexOf('Chrome');
        if (chrome > -1) {
            configuration.browsers.splice(chrome, 1);
        }
    }

    config.set(configuration);
};

// Helpers
function JasmineSeedReporter(baseReporterDecorator) {
    baseReporterDecorator(this);

    this.onBrowserComplete = (browser, result) => {
        const seed = result.order && result.order.random && result.order.seed;
        if (seed) this.write(`${browser}: Randomized with seed ${seed}.\n`);
    };

    this.onRunComplete = () => undefined;
}
```

ENV
<pre>Angular CLI: 9.1.3
Node: 13.13.0
OS: linux x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0</pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by KrakenTyio** [comment]
Hard to create simple example, bc. it need to pass first 10-20 complex tests

**Comment by alan-agius4** [comment]
Hi @KrakenTyio, will leave it open for a couple of days and hope for someone to provide a reproduction otherwise we'll have to close the issue as we cannot investigate this further.

Thanks.

**Comment by KrakenTyio** [comment]
Hi @alan-agius4 upgrade to latest angular and  `"@angular-devkit/build-angular": "0.901.4",` not helping

But when im insert deps in my package.json `"source-map-support": "~0.5.19",` its work
tested on docker node-v13 also local node-v14 + latest selenium-chrome-standalone / local chrome 81

**Comment by alan-agius4** [comment]
Closing as the issue seems to have been solved.
