### ISSUE TITLE
Quick new project command

### ISSUE THREAD

**Issue by shammelburg** [angular/angular-cli#1754]
Would it be possible to add a quick start option like `ng new PROJECT_NAME --quick` and for it to install the bare minimum files as in the first "Get Started" tutorial on [angular.io](https://angular.io/docs/ts/latest/quickstart.html)

angular2-quickstart
app
        |  --app.component.ts
        |  --app.module.ts
        |  --main.ts
node_modules ...
typings ...
index.html
package.json
styles.css
systemjs.config.js
tsconfig.json
typings.json

I like building apps from scratch and I find all the other files unnecessary.

**Comment by aciccarello** [comment]
Maybe `--minimal`? I like the idea of a quick setup. My only question is how do you communicate that the minimal setup doesn't follow style recommendations?

**Comment by filipesilva** [comment]
We already install the minimal number of files for a CLI generated project to work. It is true this minimum is fairly big, but that is being tracked in https://github.com/angular/angular-cli/issues/1263.

angular.io uses https://github.com/angular/quickstart as the base for all it's examples, so perhaps that is what you are actually looking for.
