### ISSUE TITLE
is-promise error with ng update

### ISSUE THREAD

**Issue by dalu** [angular/angular-cli#17549]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
It's a regression in the underlying lib or rather angular didn't catch up with changes with the underlying lib.

### Description

 A clear and concise description of the problem...

`ng update` fails because of npm package is-promise had an update and probably the update command didn't take versioning into consideration.

## 🔬 Minimal Reproduction

- have an angular 8 project
- try upgrading with `ng update`

## 🔥 Exception or Error
<pre><code>

</code></pre>
```
ng update                                   
Your global Angular CLI version (9.1.3) is greater than your local
version (8.3.20). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Unknown error: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/index.js
require() of ES modules is not supported.
require() of /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/index.js from /tmp/.ng-temp-packages-l4NeIR/node_modules/run-async/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /tmp/.ng-temp-packages-l4NeIR/node_modules/is-promise/package.json.
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.20
Node: 12.16.1
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

https://github.com/then/is-promise/issues/18
or rather
https://github.com/then/is-promise/issues/12
PR in is-promise
https://github.com/then/is-promise/pull/15

It will probably resolve itself but version pinning in ng update should be desirable

**Comment by SamaelR** [comment]
broken here as well, uninstalled and reinstalled npm, node, angular cli, vscode - all with no success

**Comment by cstamas** [comment]
broken here as well, `ng` is simply dead, but am (and was) on Angular 9.1.2. First could not update to @angular/cli 9.1.3 (due this error), and then `ng` rendered unusable as I installed `@angular/fire@6.0.0`:

``
cstamas@Albert ~/Worx/matesze/search01  (master *)$ node -v
v14.0.0
cstamas@Albert ~/Worx/matesze/search01  (master *)$ npm -v
6.14.4
cstamas@Albert ~/Worx/matesze/search01  (master *)$ npm ls -g --depth 0
/home/linuxbrew/.linuxbrew/lib
├── @angular/cli@9.1.2
├── npm@6.14.4
└── yarn@1.22.4

cstamas@Albert ~/Worx/matesze/search01  (master *)$ npm ls --depth 0
search01@0.0.0 /home/cstamas/Worx/matesze/search01
├── @angular-devkit/architect@0.900.7
├── @angular-devkit/build-angular@0.901.2
├── @angular/animations@9.1.3
├── @angular/cdk@9.2.1
├── @angular/cli@9.1.2
├── @angular/common@9.1.3
├── @angular/compiler@9.1.3
├── @angular/compiler-cli@9.1.3
├── @angular/core@9.1.3
├── @angular/fire@6.0.0
├── @angular/forms@9.1.3
├── @angular/language-service@9.1.3
├── @angular/localize@9.1.3
├── @angular/material@9.2.1
├── @angular/platform-browser@9.1.3
├── @angular/platform-browser-dynamic@9.1.3
├── @angular/router@9.1.3
├── @types/jasmine@3.5.10
├── @types/jasminewd2@2.0.8
├── @types/node@13.13.2
├── codelyzer@5.2.2
├── firebase@7.14.2
├── firebase-tools@8.1.1
├── fuzzy@0.1.3
├── inquirer@6.5.2
├── inquirer-autocomplete-prompt@1.0.2
├── jasmine-core@3.5.0
├── jasmine-spec-reporter@5.0.1
├── karma@5.0.2
├── karma-chrome-launcher@3.1.0
├── karma-coverage-istanbul-reporter@2.1.1
├── karma-jasmine@3.1.1
├── karma-jasmine-html-reporter@1.5.3
├── protractor@5.4.4
├── rxjs@6.5.5
├── ts-node@8.8.2
├── tslib@1.11.1
├── tslint@6.1.1
├── typescript@3.8.3
└── zone.js@0.10.3

cstamas@Albert ~/Worx/matesze/search01  (master *)$ ng version
Unknown error: Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /home/linuxbrew/.linuxbrew/lib/node_modules/@angular/cli/node_modules/is-promise/package.json
cstamas@Albert ~/Worx/matesze/search01  (master *)$ 

```

This seems related to node, as I used (wrongly) Linuxbrew so far, and it pushed me to 14.0.0. Will downgrade node to 13.x and try again.

**Comment by cstamas** [comment]
Nope, am wrong. After downgrading to Node 13.3.0, same error:

```
cstamas@Albert ~/Worx/matesze/search01  (master *)$ nvm ls
->     v13.13.0
         system
default -> 13 (-> v13.13.0)
node -> stable (-> v13.13.0) (default)
stable -> 13.13 (-> v13.13.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/erbium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.20.1 (-> N/A)
lts/erbium -> v12.16.2 (-> N/A)
cstamas@Albert ~/Worx/matesze/search01  (master *)$ node -v
v13.13.0
cstamas@Albert ~/Worx/matesze/search01  (master *)$ npm -v
6.14.4
cstamas@Albert ~/Worx/matesze/search01  (master *)$ npm ls -g --depth 0
/home/cstamas/.nvm/versions/node/v13.13.0/lib
├── @angular/cli@9.1.2
└── npm@6.14.4

cstamas@Albert ~/Worx/matesze/search01  (master *)$ ng version
Unknown error: Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "index.js" defined in the package config /home/cstamas/.nvm/versions/node/v13.13.0/lib/node_modules/@angular/cli/node_modules/is-promise/package.json
cstamas@Albert ~/Worx/matesze/search01  (master *)$ 
```

**Comment by Jordan-Hall** [comment]
Issue now resolved

**Comment by alan-agius4** [comment]
`is-promise` just a released 2.2.1, that should solve this issue.

**Comment by cstamas** [comment]
Comfirmed, `ng` CLI is back now. Tx

**Comment by dalu** [comment]
The take away from this is, version pinning.

**Comment by clydin** [comment]
The Angular CLI currently pins direct dependencies.  However, transitive dependencies are out of the control of the main package (the CLI in this case).  This is a fundamental limitation of the node package ecosystem.

There is also the semver element to this situation.  In that, there is intended to be a guarantee that minor and patch versions do not introduce breaking changes.  However, this requires cooperation from all parties and mistakes sometimes do happen.
