### ISSUE TITLE
NO EFFECT with ng serve --live-reload false 

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#1755]
1. win10

2. angular-cli: 1.0.0-beta.11-webpack.2

4. I wan't disable livereload when I do ng serve but --live-reload false doen't work, is this actually normal ?

Thanks!

**Comment by DxCx** [comment]
I've confirm this issue exists on 1.0.0-beta.11-webpack as well.
also, looking at the code, livereload flag is not being used.
looks like unimplemented feature.

**Comment by istiti** [comment]
DAMMAGE

**Comment by filipesilva** [comment]
This flag is not implemented in the webpack version. It should be removed in https://github.com/angular/angular-cli/issues/1807.

**Comment by maxbellec** [comment]
on version `1.0.0-beta.14`, flag is present but still does not work

**Comment by trezero** [comment]
If this flag is not implemented, does it mean there is no way to stop the constant unwanted reloading of an app while developing something that involves uploads and downloads?

**Comment by scottmas** [comment]
For reals? The flag hasn't worked for since August and it still exists in the --help command? At the very least this should be removed.

**Comment by laurentnovacomm** [comment]
Hello, I have the reversed problem, I would like to have live reload working with angular-cli 1.0.0-beta.22-1, but I cannot figure out why it does not work, however it works with lite-server but I would like to be able to start a project with -cli. 

Maybe have you an idea about what I could check in JSON file or other ?

Thanks in advance

**Comment by wellno14** [comment]
i'm using version  1.0.0-beta.24 and the flag is not working for me also...

**Comment by chist13** [comment]
So am I.
version 1.0.0-beta.24 - not working reloading (even with new project)
ubuntu 16.04

**Comment by lestard** [comment]
Are there any updates on this? It would be great if we could disable live-reloading. 
It makes my workflow less efficient.

**Comment by dimaShin** [comment]
angular-cli: 1.0.0-beta.26
node: 7.4.0
os: darwin x64

**Comment by Bretto** [comment]
How do we stop this ?

**Comment by mp3por** [comment]
I would also like to be able to switch off live-reload and live-recompile ... it get extremely frustrating when I have to make a big change ( possible in multiple files ) and on every save it recompiles the whole project and outputs 19238129038 errors. I want to be able to manually tell it when to recompile and reload all modules.

**Comment by filipesilva** [comment]
@clydin is working on adding these options back in https://github.com/angular/angular-cli/pull/3952

**Comment by dhasilva** [comment]
Using version 1.4.9 and it does not prevent live reload.

**Comment by leonardothibes** [comment]
@lestard You need to use: _ng serve --live-reload=false_
