### ISSUE TITLE
Can't find type definitions for external module

### ISSUE THREAD

**Issue by GDreyV** [angular/angular-cli#17558]
Commands I used:
```
ng new test
npm i --save vss-web-extension-sdk 
```
After that I added into tsconfig.json:
```
"types": [ "vss-web-extension-sdk" ]
```
and updated angular.json with:
```
"scripts": [ "node_modules/vss-web-extension-sdk/lib/VSS.SDK.js" ]
```
per documentation at https://angular.io/guide/using-libraries#library-typings and https://angular.io/guide/typescript-configuration#typescript-typings that's all I have to do to make it work. So I just add usage like `VSS.init({});` into app.component.ts. But when I build it with
```
ng build
```
I'm facing an error:
```
src/app/app.component.ts:11:5 - error TS2304: Cannot find name 'VSS'.
11     VSS.init({});
```
I see that type definitions are presented in the module but ignored buy builder. I believe it's relaged to the [ambient module declaration](https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules) within vss-web-extension-sdk but not sure about that.
Angular CLI: 9.1.3
Node: 10.16.0
OS: win32 x64

**Comment by alan-agius4** [comment]
Hi @GDreyV, `"types": [ "vss-web-extension-sdk" ]` needs to be added in the `tsconfig.json` which is used by the application build, in default projects this is named `tsconfig.app.json`.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by GDreyV** [comment]
Ah, I got it. My fault. Well, then it looks pretty bad idea to override by default generated code `types` from `tsconfig.json` with `tsconfig.app.json` where `types` is just empty collection, doesn't it?

**Comment by alan-agius4** [comment]
Hey @GDreyV, I am not quite sure I am understanding your question/statement.

**Comment by GDreyV** [comment]
When I generate empty application with `ng new appName` or project with `ng g application appName` it creates `tsconfig.json` along with `tsconfig.app.json` and `tsconfig.spec.json`. `tsconfig.app.json` extends `tsconfig.json` to specify entry point and outDir and by some reason overrides `types` with empty value.
In most documentations it's required to updates `types` in `tsconfig.json` (what I did) but it doesn't work for angular. So my concern is why `tsconfig.app.json` overrides `types` with empty value?
