### ISSUE TITLE
node-sass dependency not install with node-12 and cli-9

### ISSUE THREAD

**Issue by avinash-wissen** [angular/angular-cli#17551]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

unable to install package.json as angular has dependency on node-sass-4 which is not working with cli-9 and node-12

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hi @avinash-wissen,

Since version 8, Angular CLI doesn’t depend on node-sass. 

You might have node-sass installed directly in your project or it’s being installed transitively via another dependency.
