### ISSUE TITLE
Webpack 5 support

### ISSUE THREAD

**Issue by felipeplets** [angular/angular-cli#17555]
# Support Webpack 5

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
There is a WIP PR #16371 to implement Webpack 5 but I could not find an issue tracking it and I'm opening this one so that implementation and timeline can be discussed and followed by the community. 

### Describe the solution you'd like
Support Webpack 5 once released. (currently it's in beta)

### Describe alternatives you've considered
no alternative considered

**Comment by alfaproject** [comment]
@alan-agius4 out of curiosity, do you guys have a timeline to try out the beta? I suppose it would be good to validate that webpack 5 is in a good shape for Angular CLI while it's still in beta

**Comment by OysteinAmundsen** [comment]
Will this issue also include the module federation as discussed in https://github.com/sokra/slides/blob/master/content/ModuleFederationWebpack5.md?
If this is the case, then I'm very exited! The work that's been put into this will in my opinion revolutionize how we build frontend applications.

**Comment by felipeplets** [comment]
As support to Webpack 5 and support to Module Federation are two different streams that will probably not be implemented in the same PR we are tracking Module Federation support on issue #17556

**Comment by david2tm** [comment]
@alan-agius4 is there a fork somewhere where a development is done? may be community can contribute.

**Comment by alan-agius4** [comment]
Unfortunately, Webpack 5 has a lot of breaking changes and therefore adding support for it is not trivial feat.

@clydin is working on this and has already landed a number of small PRs to make this happen gradually.

Can you use the current “master” branch if you are interested in contributing in any way.

**Comment by alan-agius4** [comment]
Experimental opt-in support for Webpack version 5 have been added in v11.0.0-next.3.

See https://github.com/angular/angular-cli/pull/18820 for more information.

**Comment by tatsujb** [comment]
Webpack 5 is needed for Angular-Cli to work on Mac and other Unix once again. as per :   https://github.com/webpack/webpack-dev-server/issues/2754

**Comment by tatsujb** [comment]
> Experimental opt-in support for Webpack version 5 have been added in v11.0.0-next.3.
> 
> See #18820 for more information.

when will it be available in a mainline npm version? pointing to github is sometimes entirely impossible behind corporate proxy. and in a corporate context pointing to non official versions as a whole is discouraged.

**Comment by alan-agius4** [comment]
Version 11 prerelease versions are already on NPM, and you can update your application to try out the prerelease versions by running

```cmd
ng update @angular/cli --next
```
