### ISSUE TITLE
feat(generate): generate resolver

### ISSUE THREAD

**Issue by michael-letcher** [angular/angular-cli#17569]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

#6016 

This feature has already been created and a PR made. But all of a sudden, the ticket and PR was closed with no explanation. I don't understand why as I believe this is a valid feature request.

@hansl any chance we can get an explanation?

### Describe the solution you'd like
ng g r [name]

### Describe alternatives you've considered
Can always make the file manually.

**Comment by nutza249949** [comment]
x
