### ISSUE TITLE
why home page took more than 2 seconds to load?

### ISSUE THREAD

**Issue by finalxcode** [angular/angular-cli#1756]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
win10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 4.4.7
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
i used CLI to create my app. and use commend "ng g component test" to create a new component test, then add a route to redirect.
    app.component.html
    `<h1>{{title}}</h1><router-outlet></router-outlet> `

    test.routes.ts
    ` import { RouterConfig }          from '@angular/router';
    import { TestComponent } from './test.component';

    export const testRoutes: RouterConfig = [
      {
        path: 'member/loginReg',
        component: TestComponent
      }
    ]; `

    app.routes.ts
     `import { provideRouter, RouterConfig } from '@angular/router';

    import {testRoutes} from './test/test.routes';

    const routes:RouterConfig = [
      {
        path: '',
        redirectTo: 'member/loginReg',
        pathMatch: 'full'
      },
      { path: '**', redirectTo: 'member/loginReg' }, 
      ...testRoutes
    ]

    export const appRouterProviders = [
      provideRouter(routes)
    ];`
    this is file structure:
    
![qq 20160819173202](https://cloud.githubusercontent.com/assets/6211616/17805740/82497650-6633-11e6-9fac-965080995efc.png)

   

4. The log given by the failure. Normally this include a stack trace and some
   more information.
![yy](https://cloud.githubusercontent.com/assets/6211616/17805773/b897c860-6633-11e6-8dc3-18ab30cff26f.png)

5. Mention any other details that might be useful.
i use ng build --prod to create dist, then use apache and nginx to access dist. home page all take more than 2 seconds to load. can you explain why home page takes more than 2 seconds to load? what can i do to speed up the response?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kylecordes** [comment]
I have not compared your page load time above two page load times I typically see; but nonetheless I think the answer to this is:

There is work in progress, hopefully coming soon, to make CLI use the shiny new template precompiler, automatically and trivially for production bundling output. This will reduce both bundle size (for small and medium programs anyway) and startup time significantly.

**Comment by hansl** [comment]
It looks like you're not loading the right files. There's a gzipped one, and you need to configure your nginx to prioritize that file instead of the non-gzipped version.

**Comment by finalxcode** [comment]
@hansl thanks for your response, my nginx has enabled gzip module, but the result remains the same。
![qq 20160822100243](https://cloud.githubusercontent.com/assets/6211616/17841870/b154358e-684f-11e6-83d6-96ff14ada301.png)

**Comment by finalxcode** [comment]
@kylecordes thanks a lot, i will continue to pay attention to your progress.

**Comment by filipesilva** [comment]
If it happens after you deploy, but not on `ng serve --prod`, then that indicates an issue on your server setup. 

You can also use the webpack preview version, which should show some speed up: https://github.com/angular/angular-cli#webpack-preview-release-update

**Comment by finalxcode** [comment]
@filipesilva niceee :heart_eyes: thanks! now i use angular-cli@webpack to build, the response has speeded up, home page took 1 second around to load.
