### ISSUE TITLE
Support multiple configurations in Angular CLI 8.3.x

### ISSUE THREAD

**Issue by Roman-Lo** [angular/angular-cli#17568]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

As what mentioned in [#10612 Mixing configurations](https://github.com/angular/angular-cli/issues/10612) and the pr [#15819 Support multiple configurations in commands and target strings](https://github.com/angular/angular-cli/pull/15819), but it seems that these useful features are not provided in cli 8.3.x. So is there any chance that multiple configurations can be added in? 

### Describe the solution you'd like

[#15819 Support multiple configurations in commands and target strings](https://github.com/angular/angular-cli/pull/15819)

**Comment by alan-agius4** [comment]
Hi @Roman-Lo, thanks for taking interest in the new features of Angular CLI. Features and non critical bug fixes cannot be back-ported to version 8, as this is currently in LTS support, meaning that only critical and security issues will be fixed.

To benefit from new features and bug fixes please update to the latest version of the Angular CLI. This, can be done automatically using the `ng update` command. More info: https://update.angular.io/#8.0:9.0
