### ISSUE TITLE
Errors in child compilers not reported, process exits without info

### ISSUE THREAD

**Issue by nadavsinai** [angular/angular-cli#17565]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

no
### Description
If a compilation includes child compilations as is the case when using worker-loader for example (or many other webpack loaders/plugins) the build process can fail and exit without providing any info but the exit code being 1.

## 🔬 Minimal Reproduction
 clone [this](https://github.com/nadavsinai/angular-child-compiler-error),  run ng build, no errors will be shown except of  non-0 exit code or "failed to compile" in serve mode.
anything with a child compiler emits errors into it's own errors object.
you code in [createBrowserLoggingCallback](https://github.com/angular/angular-cli/blob/8.2.x/packages/angular_devkit/build_angular/src/browser/index.ts#L71)
which delegates to (stats.hasErrors() does not take into account the possibility of errors in child compilers.

## 🔥 Exception or Error
<pre><code>

the problem is the the error is not shown ;-)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.23
Node: 12.16.2
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.23
@angular-devkit/build-angular      0.803.23
@angular-devkit/build-ng-packagr   0.803.26
@angular-devkit/build-optimizer    0.803.23
@angular-devkit/core               8.3.23
@angular-devkit/schematics         8.3.23
@angular/cdk                       8.2.3
@angular/cli                       8.3.23
@angular/flex-layout               8.0.0-beta.27
@schematics/angular                8.3.23
@schematics/update                 0.803.23
ng-packagr                         5.7.1
rxjs                               6.5.5
typescript                         3.5.3
webpack                            4.29.6

</code></pre>

**Comment by ramimohammad** [comment]
Hi support team,

Any update please on this issue , we're also facing the same problem , please heeeeelp.

Kind regards
