### ISSUE TITLE
Webpack watch (like systemjs)

### ISSUE THREAD

**Issue by urosjarc** [angular/angular-cli#1757]
1. linux debian

2. 1.0.0-beta.11-webpack.2

3. Angular cli webpack version does not updates webpack when changes are made on the source files. I would expect the same functionality like in system.js version of CLI. Is this implemented?

**Comment by hansl** [comment]
It is, it should, we need more information. Are you running `ng serve` or `ng build --watch`?

**Comment by urosjarc** [comment]
Uf its so fast that I didn't see the console log changes, my mistake! :100:
