### ISSUE TITLE
Schematics update operation does not work. Change is not reflected.

### ISSUE THREAD

**Issue by raul1991** [angular/angular-cli#17578]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure about this as I am using it for the first time.

### Description

I am using angular schematics to add a declaration to my module file. Even though the output says the ```UPDATE /path/to/file.ts``` I still can't see the update.

## 🔬 Minimal Reproduction

```
const declarationChanges = addDeclarationToModule(sourceFile, newLocal, `List${strings.classify(_options.name)}Component`, `./components/general-configuration/${dasherize(_options.name)}/list/list-${dasherize(_options.name)}.component`);
    const declarationRecorder = tree.beginUpdate(newLocal);
    for (const change of declarationChanges) {
        if (change instanceof InsertChange) { // This if statement is evaluating to false, may be that is why
            _context.logger.info(change.toAdd);
            declarationRecorder.insertLeft(change.pos, change.toAdd);
        }
    }
    tree.commitUpdate(declarationRecorder);
    return chain([
      mergeWith(createTemplate(tree, _options, templates.services, '/services')),
      mergeWith(createTemplate(tree, _options, templates.models, '/models')),
      mergeWith(createTemplate(tree, _options, templates.components.create, `/components/general-configuration/${dasherize(_options.name)}/create`)),
      mergeWith(createTemplate(tree, _options, templates.components.list, `/components/general-configuration/${dasherize(_options.name)}/list`)),
      mergeWith(createTemplate(tree, _options, templates.constants, '/constants')),
    ]);
```
## 🔥 Exception or Error
<pre><code>
I get no error but the update is not reflected either.
CREATE src/coba/services/fossil-fuels.service.ts (1252 bytes)
CREATE src/coba/models/fossil-fuels.create-fossil-fuels.model.ts (807 bytes)
CREATE src/coba/components/general-configuration/fossil-fuels/create/fossil-fuels.create-fossil-fuels.component.scss (0 bytes)
CREATE src/coba/components/general-configuration/fossil-fuels/create/fossil-fuels.create-fossil-fuels.component.ts (8259 bytes)
CREATE src/coba/components/general-configuration/fossil-fuels/list/fossil-fuels.list-fossil-fuels.component.scss (0 bytes)
CREATE src/coba/components/general-configuration/fossil-fuels/list/fossil-fuels.list-fossil-fuels.component.ts (6995 bytes)
CREATE src/coba/constants/serverurl.constants.ts (70129 bytes)
**UPDATE src/coba/coba.module.ts (1959 bytes)**   <- This is not reflected in the actual file. All of the above operations are.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.2.0
Node: 12.13.1
OS: linux x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.802.0
@angular-devkit/build-angular      0.800.6
@angular-devkit/build-ng-packagr   0.800.6
@angular-devkit/build-optimizer    0.800.6
@angular-devkit/build-webpack      0.800.6
@angular-devkit/core               8.2.0
@angular-devkit/schematics         8.2.0 (cli-only)
@ngtools/webpack                   8.0.6
@schematics/angular                8.2.0
@schematics/update                 0.802.0
ng-packagr                         5.7.1
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.30.0

</code></pre>

**Anything else relevant?**

I created a schematics project and everything new changes is going to the file properly but the UPDATE operation is not. I am running the following command

```ng g ../coba-schematics/src/collection.json:entities FossilFuels --create-page-title "Fossils" --force```

**Comment by raul1991** [comment]
Found the error

Even though the change was of type InsertChange, the if condition was failing.

I debugged the change object and here is the output

```
InsertChange {
  path: 'src/coba/coba.module.ts',
  pos: 1643,
  toAdd: ',\n    ListFossilFuelsComponent',
  description: 'Inserted ,\n' +
    '    ListFossilFuelsComponent into position 1643 of src/coba/coba.module.ts',
  order: 1643
}
InsertChange {
  path: 'src/coba/coba.module.ts',
  pos: 1248,
  toAdd: ';\n' +
    "import { ListFossilFuelsComponent } from './components/general-configuration/fossil-fuels/list/list-fossil-fuels.component'",
  description: 'Inserted ;\n' +
    "import { ListFossilFuelsComponent } from './components/general-configuration/fossil-fuels/list/list-fossil-fuels.component' into position 1248 of src/coba/coba.module.ts",
  order: 1248
}

So I casted the change into InsertChange myself to make this happen.


If anyone else stuck on this maybe this can help.
```

**Comment by raul1991** [comment]
Here is how it should look like

declarationRecorder.insertLeft((<InsertChange>change).pos, (<InsertChange>change).toAdd);

**Comment by SchnWalter** [comment]
Can you please check if this can be reproduced in the latest stable version and provide a repository that contains the issue.

You are using Angular v8 is in LTS, and this version only receives fixes for critical bugs and security pages, see: [Angular versioning and releases - Support policy and schedule](https://angular.io/guide/releases#support-policy-and-schedule).

Thanks.

**Comment by clydin** [comment]
The root cause here appears to be that two different versions of the JavaScript module containing `InsertChange` are being used in the schematic.  `instanceof` will be false in this case since the objects are technically from different sources.  Ensuring that all usage of `InsertChange` originate from the same JavaScript module should resolve the issue.

Additionally, if `InsertChange` is being deep imported from `@schematics/angular`, please also note that all deep imports into this package are considered internal, private APIs and may be removed or changed in the future.
