### ISSUE TITLE
Weird type issue

### ISSUE THREAD

**Issue by hassanasad** [angular/angular-cli#1760]
1. OS: Mac OSX El Capitan

2. Versions. 
angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.7
os: darwin x64

I have an object with several other objects each containing array of objects ( i know its a mouth full so i have added an example data ):

```
data = {
  3: [{id: 11}, {id:22}, {id:33}],
  4: [{id: 12}, {id:23}, {id:34}],
  5: [{id: 13}, {id:24}, {id:35}],
}
```

Now i just want to go through this object array and match the `id` to a value and then add a flag to it. When i traverse this object, and try to access the `id` it gives this weird message:

```
[default] /path/to/code/my.component.ts:98:81 
Property 'id' does not exist on type 'string'.    client:49
```

If i dont try to access the `id` of the object i dont get any error. Doing a console log even spits out these `id` values but then at the end throws the error mentioned above.

Can someone please let me know how to access the `id` value in nested loops.

My code logic is:
```
for( let index in data ) {
	for ( let item of data[index] ) {
		console.log('ID: ', item.id);
		console.log('TYPES: ', typeof item, typeof item.id);
	}
}
```

In console i get 
```
ID: 11
TYPES: object number
ID: 22
TYPES: object number
ID: 33
TYPES: object number
...
```

**Comment by mmrath** [comment]
What about item['id']?

**Comment by hassanasad** [comment]
Oh man - you are a life saver, it does work that way! Thanks!

One small follow up question too [if you dont mind] :)

Is there a way i can add a new property `checked: true` to the original `data` object array if an `id` is matched in that loop?

**Comment by mmrath** [comment]
data['checked']=true; 

You could also use dot notation by using an interface for data. More of TS question than cli. You may please close the issue?

**Comment by hassanasad** [comment]
`data['checked']` wont do it as its in nested loops.

Thanks - i will close the issue.
