### ISSUE TITLE
include --proxy configuration in 'ng new'

### ISSUE THREAD

**Issue by jordaofranca** [angular/angular-cli#1761]
I'm working in a corp wich is using proxy over the network. Every time when I create a new project, I need to include .ember-cli and .typingsrc with proxy configuration. I came here with the proprosal to include proxy config in the 'ng new' command, with something like 'ng new <projectname> --proxy=http://10.0.0.0'. Thanks for the awsome tool you all made. Good work!

**Comment by mmrath** [comment]
I think you should be configuring npm to use proxy. The cli in turn uses npm to download dependencies. 

.typingsrc is not required because cli does not use typings.

**Comment by filipesilva** [comment]
There is no such functionality currently, no. It's more of a npm/typings configuration item, like @mmrath says. You can do `ng new project --skip-npm` to not do `npm install` automatically and add some configuration manually. 

The webpack preview version also does not use `typings` anymore, so if that the only bit that needs a proxy you might consider updating.
