### ISSUE TITLE
ES2018 event though target is `es5` in `tsconfig.json`

### ISSUE THREAD

**Issue by zaiddabaeen** [angular/angular-cli#17626]
#🐞 Bug report

`ng build` is outputting ES2018 syntax (Spread in object literals) even though the target is set to `es5` in tsconfig.json.

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No. Issue just happened after upgrading to Angular 9.1.4 from 8.x

### Description

After upgrading to Angular 9.1.4, the output in `dist/main.*.js` contains spread in object literals such as `this.options={...c,...t}` as seen in the snippet below:

```
function O(e,t){t.score=e.score}const P=[];class M{constructor(e,t={},n=null)
{this.options={...c,...t},this._processKeys(this.options.keys),this.setCollection(e,n)}
setCollection(e,t=null){this.list=e,this.listIsStringArray=o(e[0]),
this.setIndex(t||this._createIndex())
```

The spread in object literals is causing older browsers to be unable to load the application.

The `tsconfig.json` has target set to `es5`

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "allowJs": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ],
    "paths": {
      "@shared/*": ["app/shared/*"],
      "@assets/*": ["assets/*"]
    }
  }
}
```

`tsconfig.app.json`:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "baseUrl": "./",
    "target": "es5",
    "types": []
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.d.ts"
  ]
}
```

`tsconfig.spec.json`:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "target": "es5",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

`.browserlistrc`:

```
defaults
IE 10
IE 9
safari 10
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.4
Node: 12.13.1
OS: darwin x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @zackarychapple, is the above code `this.options={...c,...t}` from one of the libraries or it's part of your application code?

This seems to be similar to https://github.com/angular/angular-cli/issues/17377 which turned out to be a problem in a library.

**Comment by zaiddabaeen** [comment]
You are right, it is from Fuse.js library, where I imported it directly as
```
import Fuse from 'fuse.js';
```

Rather than using the typings
```
import Fuse from 'fuse.js/dist/fuse';
```
