### ISSUE TITLE
CSS is not loading properly when refreshing page in Angular 8

### ISSUE THREAD

**Issue by Anshu8405** [angular/angular-cli#17655]
In my angular application, I have 2 routes -` /login and /dashboard.`

If I navigate from `login` to `dashboard` route CSS is loading properly in the dashboard screen.
![image](https://user-images.githubusercontent.com/46955191/81254841-d9d74e80-9049-11ea-9f1d-f83bf361b41a.png)

If I do refresh in the `dashboard` (or directly opens `dashboard` route) some of the CSS is not loading properly.

![image](https://user-images.githubusercontent.com/46955191/81254800-c3c98e00-9049-11ea-98f1-b935e02f6d56.png)

I checked in `Console and Network `tabs. I didn't get any errors and warnings.

I need your help to resolve this issue.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
