### ISSUE TITLE
The pacote dependency should be re-evaluated

### ISSUE THREAD

**Issue by SchnWalter** [angular/angular-cli#17677]
I'm not sure exactly how to put it, but the `@angular/cli` and `@schematics/update` packages depend on [pacote](https://www.npmjs.com/package/pacote), a JavaScript Package Handler that has ~2M weekly downloads and only 8 peoples watching the [project on GitHub](https://github.com/npm/pacote), now there are 9.

This looks like a recipe for a left-pad scale disaster, but with big security implications. I would like to to invite some of the Angular contributors to start watching this project and maybe evaluate if it's really needed.

P.S. For comparison, the `@angular/core` package is downloaded 1.5M times a week.

**Comment by devoto13** [comment]
This is one of the core dependencies of NPM CLI, so if something happens to it, the ecosystem will have much bigger problems than `ng update` not working 😉

**Comment by SchnWalter** [comment]
Don't you think that is a very good reason to start monitoring that packages? I feel that more of us should monitor the changes. Better safe than sorry.

**Comment by devoto13** [comment]
Totally agree with it. I just wanted to point out that despite small amount of watchers this is one of the key packages for the ecosystem and what NPM CLI uses to download packages, so if it breaks Angular will be a tiny fraction of the problem. 

Also if Angular CLI wants to handle package installation similar to NPM it is likely needed.

**Comment by alan-agius4** [comment]
Hi, In general `watches` and `stars` should be taken with a pinch of salt as they don’t truly represent how healthy a project is. They are packages which have hundreds of `watches` and thousands of `stars` and are unmaintained. 

Back to pacote, this package is developed by NPM Inc and is the backbone of NPM CLI and receives updates on a weekly basis. 

Pacote is used by many users transitively without them even knowing it exists and what it does. Few users use it directly, so I wouldn’t expect a lot of people staring or watching it.

We do evaluate dependencies from time to time. But at this point on time, there is no reason to do so for Pacote.

**Comment by alan-agius4** [comment]
Closing as per the above explanation.
