### ISSUE TITLE
@types/moment seems to be removed.

### ISSUE THREAD

**Issue by myAoyue** [angular/angular-cli#1767]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>
Mac OSX

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
>
angular-cli: 1.0.0-beta.11-webpack.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
>
`npm install @types/moment --save-dev`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
>
The @types/moment file didn't exist definition file (moment.d.ts)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by clydin** [comment]
This really isn't a CLI issue.  `@types` is managed by Microsoft.  (FYI, you can search for types at https://aka.ms/types)

`@types/moment` is a stub for the already included types in the `moment` package itself.

**Comment by myAoyue** [comment]
Okay, I know. I just think that taking `npm install @types/moment --save-dev` be example isn't a good choose.

**Comment by clydin** [comment]
Good point.  An example using a library without included type definitions would probably be more appropriate.

**Comment by deebloo** [comment]
@myAoyue if there isn't a problem I would say we can close this issue.

**Comment by filipesilva** [comment]
Good point really, I didn't know types already had typings in at the time. I'll update it.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1813 updates the example to use `d3`, which does not package typings.
