### ISSUE TITLE
Error: Can't resolve 'crypto' after upgrade from v8.2.14 to v9.1.5

### ISSUE THREAD

**Issue by sudhakar-sekar** [angular/angular-cli#17681]
I'm using @angular version 9.1.5

and I cannot compile the project, I got the below error,

> ERROR in ./node_modules/crypto-random-string/index.js
Module not found: Error: Can't resolve 'crypto' in 'my-app\node_modules\crypto-random-string

with Angular v8.2.14 works fine. Actually I am upgrading from v7 to v9.
When I upgrade to v8.2.14 works fine.
But after upgrade from v8 to v9.1.5 facing compilation issue.

my package.json is below,

> "dependencies": {
        "@angular/animations": "^9.1.5",
        "@angular/cdk": "^9.2.2",
        "@angular/common": "^9.1.5",
        "@angular/compiler": "^9.1.5",
        "@angular/core": "^9.1.5",
        "@angular/flex-layout": "^9.0.0-beta.29",
        "@angular/forms": "^9.1.5",
        "@angular/material": "^9.2.2",
        "@angular/platform-browser": "^9.1.5",
        "@angular/platform-browser-dynamic": "^9.1.5",
        "@angular/router": "^9.1.5",
        "@types/node": "^13.13.5",
        "mermaid": "^8.4.5",
        "rxjs": "^6.5.5",
        "rxjs-compat": "^6.4.0",
        "tslib": "^1.9.0",
        "zone.js": "~0.10.3"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.901.4",
        "@angular-devkit/build-optimizer": "0.901.4",
        "@angular/cli": "^9.1.4",
        "@angular/compiler-cli": "^9.1.5",
        "@angular/language-service": "^9.1.5",
        "@types/jasmine": "^3.3.8",
        "jasmine-core": "^3.3.0",
        "jasmine-spec-reporter": "^5.0.2",
        "karma": "^5.0.5",
        "karma-chrome-launcher": "^3.1.0",
        "karma-cli": "^2.0.0",
        "karma-coverage": "^2.0.2",
        "karma-coverage-istanbul-reporter": "3.0.2",
        "karma-jasmine": "^3.1.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "karma-junit-reporter": "^2.0.1",
        "karma-typescript": "^5.0.2",
        "protractor": "^5.4.2",
        "rxjs-tslint": "^0.1.6",
        "ts-node": "8.10.1",
        "tslint": "^5.0.0",
        "typescript": "3.8.3"
    }

I tried with v9.1.6 also, but no luck.

can anyone help me ASAP to resolve the above issue.

Thanks,
Sudhakar Chandrasekaran.

**Comment by alan-agius4** [comment]
`crypto` is a Node.Js specific API, but in this case it’s being used in a browser application which is incorrect. One of your dependencies `mermaid` has a dependency on `crypto-random-string`. This library is using `crypto` which does not exist in a browser and as a result is not a browser compatible library.

While you can import shims for crypto and other Node specific API’s, It is also important to note that enabling any of the Webpack node shims/polyfills is considered unsupported behavior.

**Comment by sudhakar-sekar** [comment]
@petebacondarwin ,

When I tried the below solution works for me,
[https://github.com/tensorflow/tfjs/issues/494#issuecomment-434913391](url)

I dont want to modify any of the angular core files. I tried with below solution also,
[https://github.com/tensorflow/tfjs/issues/494#issuecomment-481636128](url)

How can I resolve this issue?
