### ISSUE TITLE
ERROR in Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js): TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ashwingairola** [angular/angular-cli#17687]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
I am working on a project using Angular CLI v9.1.5 and Tailwind CSS v1.4.6. Tailwind CSS requires me to use PostCSS for compilation.

However, I am unable to compile the app while running `ng serve`. The mini-css-extract-plugin throws the error provided below.

If you wish to see the Webpack config of my app, see this StackOverflow link:
https://stackoverflow.com/questions/61693217/angular-9-with-tailwind-css-postcss-scss-and-minicssextractplugin-not-compilin

The minimum reproduction repo:
https://github.com/ashwingairola/angular-postcss-mini-css-extract-plugin-error-repro

**`webpack.config.js`**
```javascript
const MiniCssExtractPlugin = require("mini-css-extract-plugin");

module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: "css-loader",
            options: {
              importLoaders: 2,
              sourceMap: true,
            },
          },
          {
            loader: "postcss-loader",
            options: {
              ident: "postcss",
              syntax: "postcss-scss",
              plugins: () => [
                require("postcss-import"),
                require("tailwindcss"),
                require("autoprefixer"),
              ],
              sourceMap: true,
            },
          },
          {
            loader: "sass-loader",
            options: {
              sourceMap: true,
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: "[name].[contenthash].css",
      chunkFilename: "[id].[contenthash].css",
    }),
  ],
};
```
**`package.json`**
```json
{
  "name": "mini-css-extract-plugin-error-repro",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "rxjs": "~6.5.4",
    "tailwindcss": "^1.4.6",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^9.1.0",
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "autoprefixer": "^9.7.6",
    "codelyzer": "^5.1.2",
    "css-loader": "^3.5.3",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "mini-css-extract-plugin": "^0.9.0",
    "postcss-import": "^12.0.1",
    "postcss-loader": "^3.0.0",
    "postcss-scss": "^2.0.0",
    "protractor": "~5.4.3",
    "sass-loader": "^8.0.2",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
```

## 🔬 Minimal Reproduction
Just run `ng serve`. The Webpack and Angular configs are already in place.

## 🔥 Exception or Error
The error I am getting on `ng serve` is as follows:
<pre><code>ERROR in Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: Cannot read property 'replace' of undefined
    at normalizeBackSlashDirection (F:\Workspace\mini-css-extract-plugin-error-repro\node_modules\webpack\lib\RequestShortener.js:16:17)
    at new RequestShortener (F:\Workspace\mini-css-extract-plugin-error-repro\node_modules\webpack\lib\RequestShortener.js:26:15)
    at new Compiler (F:\Workspace\mini-css-extract-plugin-error-repro\node_modules\webpack\lib\Compiler.js:195:27)
    at Compiler.createChildCompiler (F:\Workspace\mini-css-extract-plugin-error-repro\node_modules\webpack\lib\Compiler.js:558:25)
    at Compilation.createChildCompiler (F:\Workspace\mini-css-extract-plugin-error-repro\node_modules\webpack\lib\Compilation.js:2243:24)
    at Object.pitch (F:\Workspace\mini-css-extract-plugin-error-repro\node_modules\mini-css-extract-plugin\dist\loader.js:89:43)
</code></pre>

## 🌍 My Environment
<pre><code>Angular CLI: 9.1.5
Node: 14.2.0
OS: win32 x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.5
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0</code></pre>

**Comment by alan-agius4** [comment]
Hi @ashwingairola, I am sorry that you are facing an issue however while custom Webpack configuration are allowed, they are not supported by the Angular tooling team.

Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
