### ISSUE TITLE
angular undefined

### ISSUE THREAD

**Issue by hossein647** [angular/angular-cli#17683]
After installing cli-angular and checking that it is installed on the command prompt, I see the following two things:

**1- Angular: undefined**
...
**2- Ivy Workspace: <error>
-**-------------------------------------------------------
Angular CLI: 9.1.5
Node: 10.15.1
OS: x64

Angular: undefined
...
Ivy Workspace: <error>

Package Version
---------------------------------------------------------- ----
@ angular-devkit / architect 0.901.5 (cli-only)
@ angular-devkit / core 9.1.5 (cli-only)
@ angular-devkit / schematics 9.1.5 (cli-only)
@ schematics / angular 9.1.5 (cli-only)
@ schematics / update 0.901.5 (cli-only)

Why is Angular not defined and Ivy wrong?

**Comment by petebacondarwin** [comment]
This is the expected output when you run `ng version` outside an Angular project folder.
You need to be in a folder that contains the `angular.json` and `package.json` files to get information about the versions of Angular framework installed in that project.
