### ISSUE TITLE
The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0

### ISSUE THREAD

**Issue by madcowtuning** [angular/angular-cli#17685]
I have windows 10. I updated angular-cli to the laest recommended version trough npm. When i run "ng serve" in my project I get this error: 
"Node.js version v11.13.0 detected.
The Angular CLI requires a minimum Node.js version of either v10.13 or v12.0.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions."
I downloaded and installed the latest node.js version 12.6.3
When I run "node -v" I get 12.6.3 but when I run "ng serve" I still get the same error and angular clames that node.js v.11.3.0 has been detected.
There is probably something in the project that I need to change.

**Comment by madcowtuning** [comment]
It is working if I create a new project and copy "app" folder from the old project.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
