### ISSUE TITLE
Angular 9 ng test --include returns unknown option

### ISSUE THREAD

**Issue by rmcsharry** [angular/angular-cli#17689]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I have no idea, never used it before, but it seems to have worked based on what others have posted.

### Description

ng test --include <folder or filename> returns an error:

```
Unknown option: '--include'
```

## 🔬 Minimal Reproduction

Run the command with '--include'

## 🔥 Exception or Error
<pre><code>
Unknown option: '--include'
</code></pre>

## 🌍 Your Environment
<pre><code>
Your global Angular CLI version (9.1.4) is greater than your local
version (9.1.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.0
Node: 14.1.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/fire                     6.0.0
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.2.0
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.1.0
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
<img width="896" alt="Screenshot 2020-05-10 at 18 54 00" src="https://user-images.githubusercontent.com/1156100/81505616-e0d3ba80-92f0-11ea-9248-a2fee110a39c.png">

**Comment by alan-agius4** [comment]
Hi @rmcsharry, are you using custom builders? Can you please share the `test` section of your `angular.json`?

Thanks.

**Comment by rmcsharry** [comment]
@alan-agius4 Thanks for the quick response. Here it is:

```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {}
        },
```

**Comment by rmcsharry** [comment]
@alan-agius4 Ok, I just figured out that I can do:

`ng test -f HomeComponent`

to just run the tests for that component.

But I am still wondering why `--include` does not work.

**Comment by alan-agius4** [comment]
> But I am still wondering why `--include` does not work.  

You are using a custom non official builder `@angular-builders/jest:run` which doesn't support `--include` option, this option is provided by the supported test builder `@angular-devkit/builder-angular/karma`
