### ISSUE TITLE
Adding custom CopyPlugin pattern will overwrite assets to copy defined in angular.json

### ISSUE THREAD

**Issue by dsnoeck** [angular/angular-cli#17697]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When using the webpack CopyPlugin in custom webpack configuration for building app, it overwrite the assets defined in angular.json (/projects/production-orders-web-client/architect/build/options/assets)

## 🔬 Minimal Reproduction

1. Create a fresh app: `ng new <my-app>`
2. Add dependency for Angular 8: `npm i @angular-builders/custom-webpack@8 -D`
3. Add at the root a custom-webpack.config.js file with:
```
const path = require('path');
const CopyPlugin = require('copy-webpack-plugin');

module.exports = {
  plugins: [new CopyPlugin(
    [{
      from: path.join(__dirname, 'src', 'test-0.txt'),
      to: 'test-0.txt'
    }]
  )]
};
```
4. Add in angular.json, in /projects/test-copy/architect/build/options
```
"customWebpackConfig": {
  "path": "./custom-webpack.config.js"
}
```
5. Add test file to copy in src: `touch src/test-0.txt`
6. Add test file to copy in assets: `touch src/assets/test-1.txt`
7. Run: `ng build`

Expected copied file dist:
```
- assets/test-1.txt
- favicon.ico
- test-0.txt
```
Actual copied file dist:
```
- assets/test-1.txt
- test-0.txt
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.26
Node: 12.13.0
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cli                      8.3.26
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

I'm using this CopyPlugin to have more flexibility when building the app, like transforming the content of the file. I know this might not be supported at the moment, but will it be possible to **merge** with other Webpack Copy instead of overwriting ?

**Comment by alan-agius4** [comment]
Hi @dsnoeck,

This seems like an issue for `@angular-builders/custom-webpack`. While we do allow custom Webpack configurations via custom builders, they are not supported by the Angular tooling team.
