### ISSUE TITLE
ng serve with multiple configurations

### ISSUE THREAD

**Issue by kedevked** [angular/angular-cli#17696]
# 🚀 Feature request
Following this [PR](https://github.com/angular/angular-cli/pull/15819) it is now possible to extend build configuration.
Could it not possible to extends `serve` as well ? Additionnallly, `ng serve ` always searches for entries under ng-serve. Could it not be possible that if those entries are not present it uses values directly under `build` ?
### Description
 if we suppose that we have 2 build environment and 3 localize entries, we will need 6 entries under `serve` to test it locally.
```js
{
  "configurations": {
    "production": {
      "fileReplacements": [
        {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.prod.ts"
        }
      ]
    },
    "production2": {
      "fileReplacements": [
        {
          "replace": "src/environments/environment.ts",
          "with": "src/environments/environment.prod2.ts"
        }
      ]
    },
    "li18n1": {},
    "li18n2": {},
    "li18n3": {}
  }
}
```
If we are to use all these configs values under serve, we will need 6 entries. I wonder if it cannot be possible to run ng serve -c="i18n1, production1" and to directly use both configs

**Comment by SchnWalter** [comment]
It seems to work for me. I've added extra `build` configurations and matching `serve` configurations, and then I tested both the serve command and the build command with multiple configurations, and they work just fine:

```
ng build -c production,uat-one
ng build -c production,uat-two
ng serve -c production,uat-one
ng serve -c production,uat-two
```

Here's the repository/branch in which I've tested this:
> https://github.com/SchnWalter/repo-for-reproducing-angular-issues/tree/17696-ng-serve-with-multiple-configurations

---  

P.S I've just noticed that you've used this command:
```
ng serve -c="i18n1, production1"
```
I think that you've been using the command wrong. The options are applied from right to left. So in your example, I think that you should use:
```
ng serve -c="production1, i18n1"
```
Here's a quote from the MR that you've linked:
> They [configurations] will be applied from left to right. If --prod is also present, it will be considered to be the first configuration and thus able to be overriden.

**Comment by SchnWalter** [comment]
Those are just 3 lines per `dev-server` configuration entry, that's 18 extra lines for your 6 configurations, that's not much, you don't have hundreds of extra lines. Alternatively, you could use a script to generate a brand new `angular.json` from a template, and you could do this whenever you need to build for a certain brand or environment.

**Comment by kedevked** [comment]
The point is valid. But if we can avoid generating a script because it can be provided out of the box, that will be better

**Comment by alan-agius4** [comment]
@kedevked, that is not need see https://github.com/angular/angular-cli/issues/17473#issuecomment-641078028

**Comment by kedevked** [comment]
That's great, did not know about it. Thanks for sharing

**Comment by kyliau** [comment]
To add on to @alan-agius4's reply, documentation for `--browser-target` is under works.
Meanwhile, @filipesilva wrote an excellent explanation of the flag in https://github.com/angular/angular-cli/issues/16572#issuecomment-574130614.
