### ISSUE TITLE
Changing to Sass on an existing project does not work

### ISSUE THREAD

**Issue by PerfectPixel** [angular/angular-cli#1769]
According to the docs you may change our css preprocessor on an existing project (see [here](https://github.com/angular/angular-cli#css-preprocessor-integration).

However this will not work at least for Sass as the **node-sass** dev-dependency is missing on existing projects.

This affects at least version 1.0.0-beta.10. I did not check the webpack-branch.

Installing node-sass as a dev-dependency resolves the issue.

**Comment by caroso1222** [comment]
Don't know why has it been downvoted. I was having the same issue, css files were not being generated from .scss. `npm install node-sass --save-dev` did the trick. How could it be solved when changing an existing project to sass with `ng set defaults.styleExt scss`?

**Comment by calbear47** [comment]
@caroso1222 How did you you fix this exactly? 

I am trying to convert an existing project over to sass. CLI is still looking for css files that are not being compiled from my scss files in my components. 

I did the NPM install as you mentioned, but what other configuring did you do..if any? Thanks! 

angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.0
os: win32 x64

**Comment by filipesilva** [comment]
This is a problem with our README. It's listing instructions for the latest webpack version but that is not the latest in npm. To install the webpack version, see https://github.com/angular/angular-cli#webpack-preview-release-update
