### ISSUE TITLE
upgrading from angular 8 to angular 9

### ISSUE THREAD

**Issue by vishnuramero** [angular/angular-cli#17695]
![error_mc](https://user-images.githubusercontent.com/14331629/81559742-9a906100-93ad-11ea-8032-9fe2549a9a45.PNG)
unable to run the project after upgrade, any idea what might be the issue?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
