### ISSUE TITLE
Extending defaut `project:build,newconfig` throws errror 

### ISSUE THREAD

**Issue by kedevked** [angular/angular-cli#17704]
# 🐞 Bug report
Part of angular.json will look like the following
```js

"serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "options": {
                       ...
                       "browserTarget": "project:build",
                    },
                    "configurations": {
                        
                        "conf": {
                            "browserTarget": "project:build,conf"
                        },
                    }}
```
Default ng serve uses the `browerTarget: project:build`.
`ng serve` will work; there is no problem there. 
If this browserTarget configuration is to be extended as `project:build,conf`, the following error is thrown when running `ng serve -c=conf`
>An unhandled exception occurred: Invalid target: {"project":"project","target":"build,conf"}

If we are to use the default value and override it with conf, we rather need to use

``` js
  "conf": {
                "browserTarget": "project:build:conf"
             },
```
Should not both be possibly accepted as this second way of writing makes it less obvious that the default config is being overriden ?

**Comment by alan-agius4** [comment]
Hi @kedevked,

`project:build,conf` is not valid indeed. The following are the valid patterns:
```
project:target
project:target:configuration
project:target:configuration-1,configuration-2
```

https://angular.io/guide/workspace-config#alternate-build-configurations

**Comment by kedevked** [comment]
Thanks @alan-agius4 for your comment. I find it to be a bit conter-intuitive since we are overriding the default target by another configuration.

`project:target:configuration-1,configuration-2 `  configuration-2 overrides configuration-1

To carry on on this logic, I thought that 
`project:target, configuration-1` would be the way to override default config `project:target`

 But maybe that's just how it is supposed to be

**Comment by alan-agius4** [comment]
With the following pattern `project:target` in terms of the command runner you are not specifying any configuration, you are using the default specified options (If any). There are 4 level of option settings when you use a single configuration:

1. builder default options in `schema.json`
2. builder options via `options` section  in `angular.json`
3. builder configuration via the `configurations` section in `angular.json`
4. argument via command line

If the same setting is set multiple times, the last-set value is the final one.
