### ISSUE TITLE
Using ivy, method-decorators without parenthesis do not provide the third argument (propertyDescriptor)

### ISSUE THREAD

**Issue by christoph-hue** [angular/angular-cli#17703]
Under settings, just tick/untick "Enable Ivy". In console, you will see that the third - and very important - argument is missing when Ivy is used:

https://stackblitz.com/edit/angular-48pukl

**Comment by alan-agius4** [comment]
@christoph-hue, I was only to replicate this problem on StackBlitz, putting the same component in an `ng new` application, I get the expected outcome

```
with ivy, there is no propertyDescriptor-argument 
Array(3)
0: {constructor: ƒ, blubb: ƒ}
1: "blubb"
2: {writable: true, enumerable: false, configurable: true, value: ƒ}
length: 3
__proto__: Array(0)
```

Mind opening an issue on their tracker https://github.com/stackblitz/core/issues?
