### ISSUE TITLE
calling custom schematics that uses filter rule throws Error: A merge conflicted on path "/angular.json"

### ISSUE THREAD

**Issue by alyahmedaly** [angular/angular-cli#17714]
We have a schematic which call's another 2 schematics using `externalSchematic` like this

```
    externalSchematic('@blabla/schematics-app', 'app', options),
    externalSchematic('@blabla/schematics-widget', 'widget',options),
```

and both schematics app and widget updating same file, but the implementation of the widget one has

```
import { filter } from '@angular-devkit/schematics';
...
export const widgetRule = (host)=>{return filter(path=>path !== "blabla")}
```

the problem is when schematics try to merge the tree back it has this condition
https://github.com/angular/angular-cli/blob/6e03adb9e2f161a9ba9f8826537bd13047981e79/packages/angular_devkit/schematics/src/tree/host-tree.ts#L166

which check if the tree instance of HostTree and not consider FilteredHost tree
not sure the fix will to make filter return a Tree or to handle FilteredHost tree in this check

here is my versions

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 8.0.0
Node: 10.15.3
OS: darwin x64
Angular: undefined
...

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.0.0
@angular-devkit/schematics-cli    0.800.0
@angular/cli                      8.0.0
@angular/compiler                 8.0.0
@angular/compiler-cli             8.0.0
@ngtools/json-schema              1.1.0
@ngtools/webpack                  8.0.0
@schematics/angular               8.0.0
@schematics/schematics            0.800.0
@schematics/update                0.800.0
ng-packagr                        5.2.0
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
