### ISSUE TITLE
public folder is always empty

### ISSUE THREAD

**Issue by iBasit** [angular/angular-cli#1771]
I have latest angular-cil@webpack release.

each time I `ng build` with dev or prod mode, the `public` folder is always empty and `dist` folder is created.

everything works fine in `dist` folder, but then what is the purpose of `public` folder?

also If I wanted to change the location of `dist` folder to some other folder, how can I do that?

**Comment by deebloo** [comment]
@iBasit the public folder is to put static assets in. (Images, css, etc). It is then copied over to the dist folder. In master currently this has been deprecated and instead there is an "assets" directory under the src dir

**Comment by filipesilva** [comment]
@deebloo explained it very well. https://github.com/angular/angular-cli/pull/1633 also allows you to define the `outDir`.

**Comment by iBasit** [comment]
`outDir` does not really work, I have tried changing it, but result is always same

**Comment by filipesilva** [comment]
That PR is not part of a release yet, mind you. On the next release it should work.

**Comment by mafo5** [comment]
@deebloo in `webpack.8` the copy of assets like an `img` folder from the `public` folder is not working with `ng build --prod`. How do I get my static assets into my `dist` folder?

**Comment by deebloo** [comment]
@mafo5 the public folder has been changed to be under src/assets. you can configure that in the angular-cli.json at apps[0].assets

**Comment by mafo5** [comment]
@deebloo awesome answer -.-
First of all [I wrote](https://github.com/angular/angular-cli/issues/1771#issuecomment-244079974) that I tried the `src/assets` folder without any success.
Second I also tried `public` and extend the `apps[0].assets` configuration entry by my `img` entry. Nothing works so far.
Third sorry for my mean answer by I really getting frustrated by the lack of documentation but just deactivating code ([I just beleave you](https://github.com/angular/angular-cli/issues/1771#issuecomment-241291835))  and remove [readme entries](https://github.com/angular/angular-cli#adding-extra-files-to-the-build) without any replacement.
