### ISSUE TITLE
Similar issue to #17674 : The new v9.1.6 does not fix the issue completely 

### ISSUE THREAD

**Issue by kalkutti** [angular/angular-cli#17720]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

<Similar issue to #17674> A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

vagrant@ubuntu-bionic:~/dev_CBMI/dev_angular$ ng new testapp2
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE testapp2/README.md (1025 bytes)
CREATE testapp2/.editorconfig (274 bytes)
CREATE testapp2/.gitignore (631 bytes)
CREATE testapp2/angular.json (3582 bytes)
CREATE testapp2/package.json (1241 bytes)
CREATE testapp2/tsconfig.json (489 bytes)
CREATE testapp2/tslint.json (3125 bytes)
CREATE testapp2/browserslist (429 bytes)
CREATE testapp2/karma.conf.js (1020 bytes)
CREATE testapp2/tsconfig.app.json (210 bytes)
CREATE testapp2/tsconfig.spec.json (270 bytes)
CREATE testapp2/src/favicon.ico (948 bytes)
CREATE testapp2/src/index.html (294 bytes)
CREATE testapp2/src/main.ts (372 bytes)
CREATE testapp2/src/polyfills.ts (2835 bytes)
CREATE testapp2/src/styles.css (80 bytes)
CREATE testapp2/src/test.ts (753 bytes)
CREATE testapp2/src/assets/.gitkeep (0 bytes)
CREATE testapp2/src/environments/environment.prod.ts (51 bytes)
CREATE testapp2/src/environments/environment.ts (662 bytes)
CREATE testapp2/src/app/app.module.ts (314 bytes)
CREATE testapp2/src/app/app.component.css (0 bytes)
CREATE testapp2/src/app/app.component.html (25725 bytes)
CREATE testapp2/src/app/app.component.spec.ts (948 bytes)
CREATE testapp2/src/app/app.component.ts (212 bytes)
CREATE testapp2/e2e/protractor.conf.js (808 bytes)
CREATE testapp2/e2e/tsconfig.json (214 bytes)
CREATE testapp2/e2e/src/app.e2e-spec.ts (641 bytes)
CREATE testapp2/e2e/src/app.po.ts (301 bytes)
⠸ Installing packages...npm WARN deprecated tslint@6.1.2: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/rollup/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/dev_CBMI/dev_angular/testapp2/node_modules/yargs/node_modules/find-up/package.json.2413099119
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/dev_CBMI/dev_angular/testapp2/node_modules/yargs/node_modules/find-up/package.json.2413099119'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-05-13T23_49_34_720Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.6
Node: 14.2.0
OS: linux x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.6
@angular-devkit/core         9.1.6
@angular-devkit/schematics   9.1.6
@schematics/angular          9.1.6
@schematics/update           0.901.6
rxjs                         6.5.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by kalkutti** [comment]
When the local version is older, I have no problem with 'ng serve'. I cannot use the 'ng new' to create a new test app using v9.1.5 or v9.1.6. According to your suggestion, I will reinstall both node/npm to see if anything change.
