### ISSUE TITLE
'ng build' dist directory - need the ability to nest .js files in defined directory

### ISSUE THREAD

**Issue by cport1** [angular/angular-cli#1772]
I understand you can place directories in the public folder to be moved over to the dist directory.

However, for my deployment environment I need the ability to nest .js files(polyfills.bundle.js, main.bundle.js, and inline.js)  in their own /js/ directory. Where can this be defined?

**Comment by iBasit** [comment]
+1

**Comment by filipesilva** [comment]
There isn't a way to define a subfolder where bundles are generated. I suppose you can do `ng build` and then process the result to put them in a folder, and change the script tags.

**Comment by FrankGoortani** [comment]
Did you find any solutions for this?

**Comment by cport1** [comment]
This is really old.. In today's cli you can define what gets copied to the dist directory within your "assets" assray within you angular-cli.json.

{
  "project": {
    "name": "yourApp"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
....
   }
}

**Comment by Fatslug** [comment]
So how do we modify this config to copy production bundle files (generated from ng build --prod) to an "assets/js" folder?

**Comment by Yogeshwar1992** [comment]
what is the status for this issue?. I have been facing the this issue with me since 4 hours. Please post working steps and  make me happy
