### ISSUE TITLE
Schematic workflow failed error while creating new angular project

### ISSUE THREAD

**Issue by Sachin7878** [angular/angular-cli#17733]
I was encountering this error from yesterday after trying all cache clear, uninstall reinstall angular and node both, i decided to reset my laptop, installed node again and tried, the first time it worked, but now i that I am trying again, it is giving me same error. I am end of my wits now, please help.
find logs here - https://hastebin.com/efuyiyefuy.sql

got same error when I uninstalled the latest angular cli and installed version 8.0.0, here is the log - https://hastebin.com/kuworokori.sql

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by Sachin7878** [comment]
how is it npm error when the problem is being occurred due to ng command? also how do i post this issue with npm when the repo is read only now?
