### ISSUE TITLE
'let' instead of 'var' in ES5 bundles

### ISSUE THREAD

**Issue by javiermarinros** [angular/angular-cli#17735]
The Angular CLI generated ES5 bundles fails in old ES5 browsers because it's using `let` instead of `var` in source code areas related to localization and i18n using Angular + Angular CLI 9.1.7

Steps to reproduce:

> ng new test
> ng add @angular/localize
> set `"localize": true` in `angular.json`
> ng build
> check generated `vendor-es5.js ` file and look for the string `let`

**Comment by petebacondarwin** [comment]
This should have been fixed by https://github.com/angular/angular-cli/pull/17625

**Comment by petebacondarwin** [comment]
But it only landed on `master` so will only take effect in v10.0.0...

**Comment by petebacondarwin** [comment]
Perhaps you could try updating CLI to v10.0.0-next.5?

**Comment by javiermarinros** [comment]
For now I'm manually replacing 'let' with 'var' before deploying to production and it works, I'll try CLI v10

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/17749
