### ISSUE TITLE
How to Install Electron typings ?

### ISSUE THREAD

**Issue by Nishanth2** [angular/angular-cli#1774]
1. OS?  Windows 10.
2. Versions. angular-cli webpack v.2

 I am just a Newbie here ,
is there any way to install electron typings for  new webpack cli ? because  , in electron docs says use  target:'electron-renderer'  in webpack-config.js  ,  
 
But I can't find Webpack-config.js  file !..

**Comment by deebloo** [comment]
@Nishanth2 webpack isn't exposed to the user of the cli.

**Comment by Nishanth2** [comment]
thanks @deebloo  ..     Can you suggest me is there any other Way to use Electron with Anuglar2 and Angularfire2 ? or maybe In the future Angular cli supports desktop platform too ?

**Comment by deebloo** [comment]
I don't have any experience with Elector so I cannot say for sure. https://github.com/NathanWalker/angular2-seed-advanced This seed says it has set up for electron so maybe you can look there.

**Comment by deebloo** [comment]
also try taking a look here. https://github.com/angular/angular-electron

**Comment by Nishanth2** [comment]
@deebloo  Thank You .. i will Check it out :)  :+1:

**Comment by filipesilva** [comment]
The CLI is mostly aimed at webapps, so I don't think there'll be configurable electron support anytime soon. The resources @deebloo linked should help you get set up though.

**Comment by Kaffiend** [comment]
> The CLI is mostly aimed at webapps, so I don't think there'll be configurable electron support anytime soon. 

I know this is closed and somewhat dated, but I have to disagree or at least express discontent on that fact that the angular CLI is mostly aimed at web apps when angular prides itself on "One Framework Mobile & Desktop" and the majority players like electron for desktop become 2nd class citizens.
