### ISSUE TITLE
cannot install angular cli

### ISSUE THREAD

**Issue by tnlthanzeel** [angular/angular-cli#17744]
when i try to install angular cli using npm i get 

Unexpected end of JSON input while parsing near '...":{"name":"@schematic'

node version: 12.16.3
npm version: 6.14
OS: windows 10

**Comment by tnlthanzeel** [comment]
re installing node with chocolatey fixed the problem. i dont understand why

**Comment by alan-agius4** [comment]
The above error generally signifies that the NPM got corrupted.

Try to clean the cache by using `npm cache clean --force`

Closing as this is not caused by the Angular CLI.
