### ISSUE TITLE
Update to tslib v2

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular-cli#17753]
# 🐞 bug report

### Description
According to the upgrade to TypeScript 3.9 in last v10 beta, Angular should upgrade to tslib v2 ([releases notes](https://github.com/microsoft/tslib/releases)) and requires v2 as minimum peerDependency.

This is especially important in `ng g library` schematics, to avoid library authors to have to support multiple tslib versions, with potentially unexpected issues.

Related issue in Angular repo: angular/angular#37188

**Comment by alan-agius4** [comment]
Hi @cyrilletuzi,

We are aware of this and we are working on this. Tslib update to version 2 breaking and requires a number of changes across the board.

This is currently being tracked in TOOL-1374
