### ISSUE TITLE
Use Solution Style tsconfig.json Files

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#17758]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Current, we can use `describe`, `it`, `test`, `expect` in app. Because we use `"types": ["jasmine","node"]` in tsconfig.json. And this is for `tsconfig.spec.json`, not for `tsconfig.app.json`.

In order to get a better IDE experience, we can use  [“Solution Style” tsconfig.json Files](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-9.html#support-for-solution-style-tsconfigjson-files) in TypeScript 3.9

```jsonc
// tsconfig.json
{
  "files": [],
  "references": [
    { "path": "./tsconfig.app.json" },
    { "path": "./tsconfig.spec.json" },
  ]
}
```

```jsonc
{
  // tsconfig.app.json
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ],
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

```jsonc
{
  //tsconfig.spec.json
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "src/test.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}

**Comment by alan-agius4** [comment]
Hi @xiaoxiangmoe, 

Kindly search for open issues and PRs.

There is already a PR for this https://github.com/angular/angular-cli/pull/17586 and is very close to get landed.

Thanks.
