### ISSUE TITLE
Route not found after deployed to GitHub Page

### ISSUE THREAD

**Issue by funnytao** [angular/angular-cli#1775]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Win 10
1. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:

node: 4.4.6
os: win32 x64
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Everything went smooth.
1. The log given by the failure. Normally this include a stack trace and some
   more information.

EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: 'angular2-dashboard'
('angular2-dashboard' is the name of the project repository)
1. Mention any other details that might be useful.

I was trying to deploy my Angular 2 app to my GitHub Page with Angular Cli, but I got router problem saying that the route was not found. I think there should be some settings I haven't made properly but I fail to figure it out. Can anyone having experience deploying project to GitHub Page help me with it? Thank you so much.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Can you give me a repo that I can use to deploy and reproduce this? I'll try to debug what's happening.

**Comment by funnytao** [comment]
Hi @filipesilva , here is the repo: https://github.com/funnytao/angular2-dashboard. I think angular cli is supposed to handle that. Thank you so much.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
