### ISSUE TITLE
"ng d component <component name>" is not deleting the component reference from app.module.ts and the component folder

### ISSUE THREAD

**Issue by kranthiv** [angular/angular-cli#1776]
1. OS
Linux -Ubuntu 16.04

2. Versions. 
**angular-cli**  : 1.0.0-beta.11-webpack.2
**node**          : 6.4.0
**os**              : linux x64

3. Deleting component using `ng d component <component_name>` is not deleting component reference from **app.module.ts** and the folder which containing the deleted component.
 ![selection_003](https://cloud.githubusercontent.com/assets/5454320/17832156/c18224f2-6719-11e6-908c-72d9914eac5a.png)
![selection_004](https://cloud.githubusercontent.com/assets/5454320/17832164/2ef3fc18-671a-11e6-9726-fd81bda0093b.png)

**Comment by filipesilva** [comment]
We don't support destroying generated files. This will be removed from `ng help` in https://github.com/angular/angular-cli/issues/1807.

**Comment by usama520** [comment]
@filipesilva Please tell how to delete a component.

**Comment by filipesilva** [comment]
@usama520 you delete the fine manually, and delete all references to it.

**Comment by Neutrino-Sunset** [comment]
That's not very useful. Either the ng cli should support developing components by adding in the creation and deletion of them, or it should not. But just doing half a job seems pointless, it serves only to demonstrate how it would be useful to have such a tool, and then leaves the user to have to write the tool themselves.

**Comment by samfortunato** [comment]
Why does Angular support generating a component from the CLI, but not deleting one?
