### ISSUE TITLE
--extra-webpack-config is generating index.html twice

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#17783]
# 🐞 Bug report

### Command (mark with an `x`)
- [x ] build

### Is this a regression?

 Not sure

### Description
I am trying to integrate `async-css-plugin` (https://www.npmjs.com/package/async-css-plugin) in to my Angular app and for this I am using `--extra-webpack-config` and have created below `custom-webpack.config` file

```
const HtmlWebpackPlugin = require('html-webpack-plugin')
const AsyncCssPlugin = require("async-css-plugin");
var path = require('path');
module.exports = {
  output: {
    path: path.resolve(__dirname, './dist')
  },
  plugins: [
    new HtmlWebpackPlugin(),
    new AsyncCssPlugin({ logLevel: "info" })
  ]
};
```

Actually what this plugin does is convert the `stylesheet` link in `index.html` file to `async` link for example:

`<link href="styles.416c0915740365a586ba.css" rel=stylesheet media="print" onload="this.media='all'">`

Now, when I run `ng build --prod --extra-webpack-config custom-webpack.config.js` it doesn't make any changes to the `index.html`, I thought that the plugin isn't working, I opened the issue on plugin's author github repo and also asked question on stackoverflow (https://stackoverflow.com/questions/61965344/angular-running-custom-plugin-after-build/) but couldn't found any solution.

While troubleshooting, I generated a new Angular project and set the `"outputPath": "dist/mustakbil",` in `angular.json`.

This time, when I run the build command `ng build --prod --extra-webpack-config custom-webpack.config.js`, it actually produced two index.html files one in `dist` folder and another in a folder under `dist` folder.

The file in `dist` folder was modified by the plugin after build whereas the file in `dist/mustakbil` wasn't modified.

This makes me belief that when I set `"outputPath": "dist",` below is what Angular CLI is doing:

1. Angular CLI generates, `index.html`
2. Plugin modifies the style tag in index.html
3. Angular CLI re-generates the `index.html` file, while discarding changes made by the plugin.

## 🔬 Minimal Reproduction
Here's the reproduction repo https://github.com/andreashuber69/async-css-angular-example

## 🔥 Exception or Error
<pre><code>
Angular CLI is generating index.html twice.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.0-rc.0
Node: 12.16.2
OS: win32 x64

Angular: 10.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0-rc.0
@angular-devkit/build-angular     0.1000.0-rc.0
@angular-devkit/build-optimizer   0.1000.0-rc.0
@angular-devkit/build-webpack     0.1000.0-rc.0
@angular-devkit/core              10.0.0-rc.0
@angular-devkit/schematics        10.0.0-rc.0
@ngtools/webpack                  10.0.0-rc.0
@schematics/angular               10.0.0-rc.0
@schematics/update                0.1000.0-rc.0
rxjs                              6.5.5
typescript                        3.9.3
webpack                           4.43.0
</code></pre>

The same is reproducible with Angular 9.x.

**Comment by SchnWalter** [comment]
The Angular CLI builder, `@angular-devkit/build-angular`, doesn't have an `extraWebpackConfig` configuration option, you are probably using a 3rd party builder like like `ngx-build-plus`. You should report this in their issue queue.

**Comment by naveedahmed1** [comment]
Thank you so much @SchnWalter I am using `ngx-build-plus` for my main repo. I will report it there and update this issue if they say it has something to do with Angular.

**Comment by alan-agius4** [comment]
Hi @naveedahmed1, in the CLI the index.html generation happens outside of the Webpack build pipeline.

As @SchnWalter mentioned, the first party supported builder `@angular-devkit/build-angular` doesn't allow changing the Webpack configuration. While we do allow customizing Webpack configurations via 3rd party builders. Custom webpack configurations and related issues are not supported by the Angular tooling team.

Thanks

**Comment by alan-agius4** [comment]
PS: this is also related to https://github.com/angular/angular-cli/issues/11816
