### ISSUE TITLE
Cannot run ts-node inside root folder of Angular project

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#17788]
Cannot run `ts-node` inside Angular project root folder.

This error happens:

```
import { parse } from 'papaparse';
       ^

SyntaxError: Unexpected token {
```

It's something with the `tsconfig.json` file most likely.  I already reported the same issue against ng-packagr.

Outside of Angular the code runs fine, even with any `tsconfig` at all.

**Comment by alan-agius4** [comment]
Hi @fireflysemantics, as @petebacondarwin explained this is working as expected.

ES modules are not supported by default in Node versions < 14, thus you'd need to create a new tsconfig that uses `CommonJS` as `module` and provide it to ts-node via the `--project` option.
