### ISSUE TITLE
Unable to install Angular CLI

### ISSUE THREAD

**Issue by Manshi27** [angular/angular-cli#17790]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I tried to install using the command: npm install -g @angular/cli
but it is showing this:
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by SamsonUteh** [comment]
> 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
> 
> I tried to install using the command: npm install -g @angular/cli
> but it is showing this:
> npm WARN deprecated request@2.88.2: request has been deprecated, see [request/request#3142](https://github.com/request/request/issues/3142)
> 🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Good evening. Have you found a solution to this?
