### ISSUE TITLE
How to run test

### ISSUE THREAD

**Issue by stephanec1** [angular/angular-cli#178]
Hi,
By following your doc I don't get how to run a unitTest with the angular-cli config. Can you help me for that please?
Thanks.

**Comment by jkuri** [comment]
Hi. First build your app with `ng build` then run `karma start`.

**Comment by Brocco** [comment]
Running tests will be simpler in the future by just running `ng test` and you can track the progress in issue #70

Until that time you can follow the instructions in the above comment and find more information in the README.md

**Comment by stephanec1** [comment]
I always have this error when I run 
`karma start`

> 04 02 2016 21:37:01.677:WARN [watcher]: Pattern 
> "/Users/steph/Project/node_modules/angular2/bundles/testing.js" does not match any file.
> 04 02 2016 21:37:01.706:WARN [watcher]: Pattern "/Users/steph/Project/dist/**/*.css" does not match any file.
> 04 02 2016 21:37:01.737:WARN [karma]: No captured browser, open http://localhost:9876/
> 04 02 2016 21:37:01.747:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
> 04 02 2016 21:37:01.753:INFO [launcher]: Starting browser Chrome
> 04 02 2016 21:37:03.434:INFO [Chrome 48.0.2564 (Mac OS X 10.11.2)]: Connected on socket /#g6JpnEvQqb0ummP6AAAA with id 80857190
> 04 02 2016 21:37:03.780:WARN [web-server]: 404: /rxjs/Subject
> 04 02 2016 21:37:03.782:WARN [web-server]: 404: /rxjs/observable/fromPromise
> 04 02 2016 21:37:03.782:WARN [web-server]: 404: /rxjs/operator/toPromise
> 04 02 2016 21:37:03.783:WARN [web-server]: 404: /rxjs/Observable
> Chrome 48.0.2564 (Mac OS X 10.11.2) ERROR
>   Error: XHR error (404 Not Found) loading http://localhost:9876/rxjs/Subject
>       at error (/Users/steph/Project/node_modules/systemjs/dist/system.src.js:1028:16)
>       at XMLHttpRequest.xhr.onreadystatechange (/Users/steph/Project/node_modules/systemjs/dist/system.src.js:1036:13)

**Comment by jkuri** [comment]
Are you using the master?

**Comment by stephanec1** [comment]
I don't really know, I installed angular-cli via npm

**Comment by jkuri** [comment]
You are not using master then. Please see the readme how to use it.

**Comment by stephanec1** [comment]
Ok thank you for your help jkuri :+1:

**Comment by filipesilva** [comment]
@stephanec1 the latest version on npm is a bit out of date in regards to master, sorry you had trouble!
