### ISSUE TITLE
I've been using the `ng build my-lib --watch` for some time now but I 've been unhappy  with the rebuild time.

### ISSUE THREAD

**Issue by sunildarji811** [angular/angular-cli#17801]
I've been using the `ng build my-lib --watch` for some time now but I 've been unhappy  with the rebuild time.
Today I changed the default path mapping in main project's tsconfig to point to lib's public_api:

```
"paths": {
      "users": [
        "projects/users/src/public_api"
      ],
      "shared": [
        "projects/shared/src/public_api"
      ]
    }
```
now the libraries are built by `ng serve` command, changes propagates super fast and also the Chrome devtools are able to debug raw typescript files.
Sounds too good to be true but really works.

_Originally posted by @GeorgeKnap in https://github.com/angular/angular-cli/issues/10643#issuecomment-423935700_

**How to use one library project with another**

After this changes how to resolve dependency if "shared" library is used inside "users" library.

Getting below error while `ng build users`

`error TS6059: File '....projects/shared/src/lib/com-model.component.ts' is not under 'rootDir' '...\projects\users\src'. 'rootDir' is expected to contain all source files. 
`

**Comment by alan-agius4** [comment]
Hi @sunildarji811, I am sorry to hear that you are unhappy with the rebuild times.

Can you please provide the output of `ng version` and also share the timings of the rebuilds? It would be also great if you can share a reproduction even privately to see where is the bottleneck.

With regards to the path mappings to TypeScript source files, we don't recommend, nor official support that pattern. See: https://angular.io/guide/creating-libraries#building-and-rebuilding-your-library for more context about why.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
