### ISSUE TITLE
--outputHashing is not working 

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#17814]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: no idea

### Description
Still browser is able to cache my JS changes in production too. You will have to clear cache with ctrl + shift + r.
angular.json
```
"production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            },
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

ng version
Your global Angular CLI version (9.1.1) is greater than your local
version (9.0.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 10.16.3
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      8.2.3
@angular/cli                      9.0.3
@angular/material                 8.2.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @indraraj26, my two cents would be that the `index.html` is cached which in such case is more of a server configuration rather than an Angular CLI issue.

Unfortunately, there isn’t much information in this issue to validate if this is any the real issue or not.

**Comment by indraraj26** [comment]
I will share website link tmrw it is hosted on aws s3 bucket. btw from where i can start to troubleshoot. how to can i blame server team, it is an server side issue.

**Comment by alan-agius4** [comment]
Let's not play the blame game 😁.

You can try to checking what the response for the `index.html` is and verify if that's the cached version or not.

**Comment by clydin** [comment]
For additional information on server cache settings, this article may be useful: https://web.dev/http-cache/

The `Cache-Control` header should typically be set to `no-cache` for the `index.html`.  This can be checked in the dev tool's network tab for the browser.

**Comment by indraraj26** [comment]
Thank Alan and clydin for quick response on this. I will check this in morning

**Comment by andreidiaconescu** [comment]
Hello,
Since Angular 7 i get this error: Unknown option: '--output-hashing'

What would be the right way to use this option ?

Thank you

**Comment by alan-agius4** [comment]
> Hello,
> Since Angular 7 i get this error: Unknown option: '--output-hashing'
> 
> What would be the right way to use this option ?
> 
> Thank you

`—-output-hashing` is a build option. See: https://angular.io/cli/build

**Comment by indraraj26** [comment]
Thank you for patience and i am really sorry for late response on this. yes i am closing since server team is looking into that.
