### ISSUE TITLE
Deploy app on gh-pages on a custom domain

### ISSUE THREAD

**Issue by rishabhsethi** [angular/angular-cli#1781]
1. OS: Ubuntu (15.10)
2. Versions: 1.0.0-beta.10
3. Repro steps:
   ng new app-name
   git add --all
   git remote add origin https://github.com/USERNAME/PROJECT_NAME.git
   git commit -m "message"
   git push origin master
   ng github-pages:deploy
4. The app is deployed at https://username.github.io/app-name but I wish to deploy this app with a custom domain name. On the custom domain name, it is just showing "Loading...".
   I tried adding a CNAME file as well as setting the custom domain in the github repo settings.

Thanks!

**Comment by filipesilva** [comment]
We don't have this functionality yet, unfortunately.

**Comment by austin94** [comment]
I don't see any open PR's for this yet so I will take a look at this as long as it is still a community item?

**Comment by camccar** [comment]
+1. Would really like this functionality added

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
