### ISSUE TITLE
while generating appShell option appDir is ignored

### ISSUE THREAD

**Issue by santoshyadavdev** [angular/angular-cli#17813]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

We have an application with universal, where the app.server.module.ts file is not in app folder, when I tried to use ng generate appShell --appDir='path' it ignores it throws exception 

Specified module 'app.server.module.ts' does not exist.
Looked in the following directories:
    /src/app/app.server.module.ts
    /src/app/app-shell
    /src/app
    /src

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

Specified module 'app.server.module.ts' does not exist.
Looked in the following directories:
/src/app/app.server.module.ts
/src/app/app-shell
/src/app
/src
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.5
Node: 12.14.1
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@ngtools/webpack                  9.0.5
@nguniversal/builders             9.0.1
@nguniversal/common               9.0.1
@nguniversal/express-engine       9.0.1
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by santoshyadav198613** [comment]
Hi @alan-agius4 will take it.

**Comment by abadi003** [comment]
is this still open?

**Comment by alan-agius4** [comment]
Closing as `appDir` is no longer available.
