### ISSUE TITLE
ng build and ng build -prod

### ISSUE THREAD

**Issue by parura** [angular/angular-cli#17825]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Framework issues at: https://github.com/angular/angular/issues/new/choose

For the time being, we keep Angular issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by parura** [comment]
I have created two projects 
One is weapi and angular app @angular/cli": "~9.1.1", version using in this app.

it is working fine.

Issue is with the ng build and ng build  --prod

After using those commands app was able to create the js file and style sheet file.

When I try to use api url to run the project it was saying that 

style file or js files not found 404 error.

Can any tell any file path do i need to set

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
