### ISSUE TITLE
Ng Build vs Ng Build --prod

### ISSUE THREAD

**Issue by parura** [angular/angular-cli#17824]
HI,

When I run the ng build it is successfully created the files and can able to run ,
I use 👍 http://localhost:5000/
but if i run the  ng build --prod it is successfully created the files but when run the apllciaion 
http://localhost:5000/

Those files are sitting in the wwwroot build folder

These are errors i got [
![fileerro1](https://user-images.githubusercontent.com/65385762/83320431-dfac0280-a28a-11ea-8145-9174be1c178a.PNG)
](url)

Could any one help on this?

**Comment by parura** [comment]
I have used this command too
ng build --prod --base-href ./
 but got the same error

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
