### ISSUE TITLE
Angular 9 Lazy Loading with arrow functions no chunks and big main.js

### ISSUE THREAD

**Issue by ilprima** [angular/angular-cli#17826]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

Building on aot with the new arrow functions to import lazy loading modules seems breaking the lazy loading and main.js contains all of them.

## 🔬 Minimal Reproduction

Just create a new project with the last angular-cli version (9.1.7) and implements a lazy loading module with arrow function type importing.

## 🔥 Exception or Error

Build stats using arrow functions:
![100805853_3230499480313869_7761146830338916352_o](https://user-images.githubusercontent.com/18414951/83326109-900d0d00-a271-11ea-9153-ab8045926484.jpg)

Build stats using # style import:

![100825619_3235026263194524_805670628471341056_o](https://user-images.githubusercontent.com/18414951/83326120-a1eeb000-a271-11ea-85d0-7348746a7a43.jpg)

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.7
Node: 10.16.3
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/http                     7.2.2
@ngtools/webpack                  9.1.7
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               8.3.26
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

Here my build production configuration:

```
"production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "none",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": true,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "5mb",
                  "maximumError": "20mb"
                }
              ]
            },
```

**Comment by alan-agius4** [comment]
What’s the `module` value in `tsconfig.app.json` and `tsconfig.json`?

**Comment by karser** [comment]
Same here. I just created a new project using `ng new app --commit=false` and chunks are not created.
```
Angular CLI: 9.1.7
Node: 12.0.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.7
@angular-devkit/core         9.1.7
@angular-devkit/schematics   9.1.7
@schematics/angular          9.1.7
@schematics/update           0.901.7
rxjs                         6.5.4
```

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

tsconfig.app.json
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "files": [
    "src/main.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.d.ts"
  ]
}
```

**Comment by alan-agius4** [comment]
@karser, how are you creating the lazy chunks? I am unable to reproduce this issue.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by karser** [comment]
Here is the reproducer https://github.com/karser/angular-9-lazy-loading-issue
```
npm install
ng serve
```
There are no chunks for lazy loading modules
![image](https://user-images.githubusercontent.com/1675033/83390234-29672b00-a3fa-11ea-98f7-75350d180b63.png)

**Comment by alan-agius4** [comment]
@karser, in your case the problem is that in `app.module.ts` you are statically referencing the lazy loaded modules.

|https://github.com/karser/angular-9-lazy-loading-issue/blob/4d92c7e4019b85bffd886f7daac89c4334f6464e/src/app/app.module.ts#L15-L16

The result is, that these modules will no longer be treated as lazy chunks.

**Comment by karser** [comment]
Thank you @alan-agius4, I removed these modules from AppModule and lazy loading started working for me.

**Comment by alan-agius4** [comment]
@ilprima, any update?

**Comment by ilprima** [comment]
I fixed it just downloading my project again from git. Maybe it was a build cache problem
