### ISSUE TITLE
Production Build

### ISSUE THREAD

**Issue by ChhaiSoriya** [angular/angular-cli#17832]
Build chunk file in production not work. When I build as production, all components and library was included in main.js file that make it big size 5-6 MB, which make first loading time so long.
Please help!

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
