### ISSUE TITLE
Cannot find name 'chrome'. How to provide global externals?

### ISSUE THREAD

**Issue by vsDizzy** [angular/angular-cli#17849]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

When it was possible to `eject` config this could be solved by adding
```js
externals: {chrome: 'chrome'}
```

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
I'm writing a chrome extension.
I added `@types/chrome` and I'm referencing `chrome` global variable.

```js
    chrome.runtime.sendMessage('test');
```

https://github.com/vsDizzy/ng-app/blob/304ec119d9217b34639c9cda81d0d62f9065cab6/src/app/app.component.ts#L11-L13

`ng build` produce error:
```
ERROR in src/app/app.component.ts:12:5 - error TS2304: Cannot find name 'chrome'.
```

## 🔬 Minimal Reproduction

Steps:
1. `ng new ng-app`
2. `npm i -D @types/node`
3. reference `chrome` in code
4. `ng build`

Minimal repo:
https://github.com/vsDizzy/ng-app

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/app.component.ts:12:5 - error TS2304: Cannot find name 'chrome'.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.7
Node: 14.4.0
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

Chrome 
Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by SchnWalter** [comment]
This is not an Angular CLI issue, it's a TypeScript configuration issue. You should read the [Module Resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html) handbook, it will show you how to configure your workspace to use these types. If you need more help, you should check [Got a Question or Problem?](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vsDizzy** [comment]
Thanks for the response! I'm able to compile similar code with `tsc` without configuring anything. Just by installing `@chrome/types`:

![image](https://user-images.githubusercontent.com/5798340/83699550-02347780-a60d-11ea-8ac6-a67a5514aef5.png)

Sample repo:
https://github.com/vsDizzy/node-app/tree/chrome-ext

I've read the 'module resolution` but still having the problem.

I tried to set `paths` in `tsconfig.json`
```json
    "paths": {
      "chrome": ["node_modules/@types/chrome"]
    }
```
When i do
![image](https://user-images.githubusercontent.com/5798340/83700318-24c79000-a60f-11ea-844d-8be13cd79bc1.png)
it fails with
![image](https://user-images.githubusercontent.com/5798340/83700334-39a42380-a60f-11ea-955c-51a268777a28.png)

When i do
![image](https://user-images.githubusercontent.com/5798340/83700404-6c4e1c00-a60f-11ea-997f-c3bc2c5da424.png)
it fails with
![image](https://user-images.githubusercontent.com/5798340/83700456-9273bc00-a60f-11ea-8500-c0fc3edc3100.png)

Maybe I'm missing something obvious. Please help.

**Comment by SchnWalter** [comment]
As I said in my previous comment: "This is not an Angular CLI issue".

The `"chrome": ["node_modules/@types/chrome"]` path alias points to the type definitions of that library, not the `chrome` "library" code. And the path alias is invalid, because instead of pointing to some code, it's points to the type definitions.

P.S. Assuming that you are trying to work with the [Google Chrome Extensions API](https://developer.chrome.com/extensions), the repository that you've linked doesn't include any code for creating chrome extensions, you need to fix that first, you should search for tutorials online or you should take this question to a forum. https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#question

**Comment by vsDizzy** [comment]
Thanks again. Yes I agree this is not an issue with CLI.
The solution is to use `/// <reference types="chrome"/>`in `.ts` file
Or better add `types: [chrome]` to `tsconfig.app.json` under the `compilerOptions`

P.S. My problem was me changing `types` in `tsconfig.json` instead of `tsconfig.**app**.json`.

Thanks a lot for the help!
