### ISSUE TITLE
Angular CLI 10.0.0-rc.2 breaks SSR bundleDependencies and generates multiple bundles

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#17840]
# 🐞 Bug report

### Command (mark with an `x`)
- [x ] build

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.0.0-rc.0

### Description

After updating my project to Angular CLI 10.0.0-rc.2, it seems that its not honoring the `"bundleDependencies":true` and generating multiple files.

Here's my `angular.json`

```
"server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist-server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "media",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "bundleDependencies": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }
```

Here's my tsconfig

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": false,
    "declaration": false,
    "module": "es2020",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "./typings",
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}

```

and here's `tsconfig.server`

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./",
    "target": "es2016"
},
  "angularCompilerOptions": {
    "entryModule": "app/app.module.server#AppServerModule",
    "enableIvy": true
  },
  "exclude": [
    "main.ts",
    "app/app.module.browser.ts",
    "app/app.component.ts",
    "app/push-notification.component.ts",
    "app/push-notification.module.ts",
    "app/app-routing.module.ts",
    "./**/*.browser.ts",
    "firebase-messaging-sw.ts",
    "polyfills.ts",
...
....
  ]
}
```

**Before the update,** 

This was my `tsconfig` file:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": false,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "./typings",
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}

```

And `tsconfig.server` before update

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "baseUrl": "./",
    "module": "commonjs"
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.module.server#AppServerModule",
    "enableIvy": true
  },
  "exclude": [
    "main.ts",
    "app/app.module.browser.ts",
    "app/app.component.ts",
    "app/push-notification.component.ts",
    "app/push-notification.module.ts",
    "app/app-routing.module.ts",
    "./**/*.browser.ts",
    "firebase-messaging-sw.ts",
    "polyfills.ts",
...
....
  ]
}

```

Downgrading to Angular CLI version `10.0.0-rc.0`, fixes the issue.

**Comment by alan-agius4** [comment]
Hi @naveedahmed1, I am not understanding the issue that you are reporting. 

You are stating:
>After updating my project to Angular CLI 10.0.0-rc.2, it seems that its not honoring the "bundleDependencies":true and generating multiple files.

`bundleDependencies` controls is the dependencies are bundled/embedded in the bundle or not. it has no effect on the number of files emitted.

**Comment by naveedahmed1** [comment]
Thank you @alan-agius4. Before Angular CLI 10.0.0-rc.2, the build command was generating just one file `main.js`. After the update, its generating `main.js` and many other files like `1.js`, `2.js`, `3.js` etc.

.Net core applications, requires angular applications to be bundled as a single file.  If I update `tsconfig.server`  file and set `"module": "commonjs"`, it starts working and generates single bundle `main.js` but with `"target": "es2016"` its not wokring and generating multiple files.

**Comment by alan-agius4** [comment]
The `target` setting doesn't effect the above, it's the module which does.

What you are seeing are lazy loaded chunks being generated for the server, When setting the `module` to `commonjs` lazy-loading chunks are not generated because the bundler is unable to create these chunks.

Thus, if you want to disable lazy-loaded at a server level because your server doesn't work with lazy-loading you should set `commonjs` as the module for your server builds.

**Comment by alan-agius4** [comment]
That said, is the .NET core application failing with the server side lazy loaded modules?

**Comment by naveedahmed1** [comment]
I see, thanks for explaining this. Actually I just noticed that running `ng update` command updates my server tsconfig from:

```
 "compilerOptions": {
    "baseUrl": "./",
    "module": "commonjs"
  },
```
to

```
 "compilerOptions": {
    "baseUrl": "./",
    "target": "es2016"
},
```

i.e. removing `"module": "commonjs"` and adding `"target": "es2016"`

> That said, is the .NET core application failing with the server side lazy loaded modules?

Yes for Angular SSR/Universal app running with .Net /.Net Core we require a single js bundle, this has been discussed in past here https://github.com/angular/angular-cli/issues/8616.

**Comment by clydin** [comment]
The reasoning for bundling in that issue (#8616) was that the node modules directory was massive both in depth and breadth.  This can lead to triggering windows path limitations.  This can also be problematic for deployment on such systems since the entire node modules directory needed to be deployed.

With the lazy chunks neither should be an issue since there is no additional directory depth and the number of files is limited (especially in comparisons to the potential thousands of files in the node modules directory).

**Comment by naveedahmed1** [comment]
But in my case its throwing below error when Angular CLI generates lazy chunks:

`NodeInvocationException: Cannot destructure property 'AppServerModule' of 'module.exports' as it is undefined. TypeError: Cannot destructure property 'AppServerModule' of 'module.exports' as it is undefined. at D:\MyProject\dist-server\main.js:1:1147658 at D:\MyProject\dist-server\main.js:1:1324967 at D:\MyProject\dist-server\main.js:1:3274951 at bound (domain.js:428:14) at runBound (domain.js:439:12) at Object.R9RV.exports.run (D:\MyProject\dist-server\main.js:1:1225676) at Object.R9RV.exports.runInNewDomain (D:\MyProject\dist-server\main.js:1:1226153) at Object.run (D:\MyProject\dist-server\main.js:1:3274742) at resultFunc (D:\MyProject\dist-server\main.js:1:1324538) at renderToStringImpl (C:\Users\User Name\AppData\Local\Temp\v3zf11y1.swy:127:32)`

**Comment by alan-agius4** [comment]
@naveedahmed1, can you please share a reproduction on how we can reproduce the above error? Thanks.

**Comment by naveedahmed1** [comment]
@alan-agius4 would you be able to run .Net core app? It will require Visual Studio at least, if you have it installed, I can add you to a private repo.

**Comment by alan-agius4** [comment]
@naveedahmed1, in this case ideally it’s preferred if you can share a minimal reproduction that contains the bare minimum of code needed to reproduce the issue.

**Comment by naveedahmed1** [comment]
Here's my `main.server.ts`

```
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import { renderModule, renderModuleFactory } from '@angular/platform-server';
import { APP_BASE_HREF } from '@angular/common';
import { enableProdMode } from '@angular/core';
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
import { createServerRenderer } from 'aspnet-prerendering';
export { AppServerModule } from './app/app.module.server';

import * as myGlobals from './app/globals';

enableProdMode();

export default createServerRenderer(params => {
  const { AppServerModule, AppServerModuleNgFactory, LAZY_MODULE_MAP } = (module as any).exports;
  const options = {
    document: params.data.originalHtml,
    url: params.url,
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP),
      { provide: APP_BASE_HREF, useValue: params.baseUrl },
      { provide: 'BASE_URL', useValue: params.origin + params.baseUrl },
      { provide: 'origin', useValue: params.origin }
    ]
  };

  const renderPromise = AppServerModuleNgFactory
    ? /* AoT */ renderModuleFactory(AppServerModuleNgFactory, options)
    : /* dev */ renderModule(AppServerModule, options);

  return renderPromise.then((html) => {

    let statusCode = 200;
    if (myGlobals.response.statusCode === 404) {
      statusCode = 404;
      //reset status code to 200 for next request
      myGlobals.response.statusCode = 200;
    }

    return {
      html: statusCode === 404 ? '<!DOCTYPE html><html lang="en"><head><title>404 Page Not Found</title><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"></head><body style="font-family:Verdana;font-size:12px;background: url(https://www.mustakbil.com/content/images/header-pattern.png) #f9f9f9;padding:100px;"><div style="max-width:620px;min-height:200px;margin:auto;padding:50px;box-shadow:15px;box-shadow: 0 3px 1px -2px rgba(0,0,0,.2), 0 2px 2px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0,.12);"><p style="text-align:center"><a href="https://www.mustakbil.com"><img src="https://www.mustakbil.com/content/images/logo-round.png" border="0" width="120" /></a></p><br /><h1 style="font-size:14px;text-align:center;">Sorry Page Not Found!</h1><p style="text-align:center">It seems that the page you are looking for doesn\'t exist, or it has been removed.  <br /><br /><br /><a href="https://www.mustakbil.com" style="border:0;padding:7px 20px;text-transform:uppercase;outline:none;color:white;text-decoration:none;background-color:#4d5ec1">Click here to Continue</a></p></div></body></html>' : html, StatusCode: statusCode
    }

  });
});
```
And in my `app.module.server.ts` I import `ModuleMapLoaderModule` from `import { ModuleMapLoaderModule } from '@nguniversal/module-map-ngfactory-loader';`

Can this be a problem?

**Comment by alan-agius4** [comment]
Hi @naveedahmed1, the problem is actually this piece of code

```ts
export { AppServerModule } from './app/app.module.server'
const { AppServerModule, AppServerModuleNgFactory, LAZY_MODULE_MAP } = (module as any).exports;
```

The above is not valid, in non `commonjs` module format since `module.export` will always be undefined.

Use ES6 imports instead:
```ts
import { AppServerModule } from './app/app.module.server';
```

Also, `AppServerModuleNgFactory` and `LAZY_MODULE_MAP` are no longer required for Ivy.

**Comment by naveedahmed1** [comment]
Thank you so much @alan-agius4 .

I have replaced 
`export { AppServerModule } from './app/app.module.server';`

with 
`import { AppServerModule } from './app/app.module.server';`


removed this line from `createServerRenderer`.

`const { AppServerModule, AppServerModuleNgFactory } = (module as any).exports;`

Can you please also guide what changes should I make to this piece of code:

```
  const renderPromise = AppServerModuleNgFactory
    ? /* AoT */ renderModuleFactory(AppServerModuleNgFactory, options)
    : /* dev */ renderModule(AppServerModule, options);
```

**Comment by alan-agius4** [comment]
```ts
  const renderPromise = AppServerModuleNgFactory
    ? /* AoT */ renderModuleFactory(AppServerModuleNgFactory, options)
    : /* dev */ renderModule(AppServerModule, options);
```
Should be changed to 

```ts
  const renderPromise = renderModule(AppServerModule, options);
```

**Comment by naveedahmed1** [comment]
Thank you so much @alan-agius4 you have always been very helpful :)
