### ISSUE TITLE
angular-router RC1

### ISSUE THREAD

**Issue by hartjo** [angular/angular-cli#1784]
when you release angular-router RC1 right now the router is still in beta.2...

**Comment by neilhem** [comment]
Can you elaborate your issue with angular-cli? Route generation is disabled right now

**Comment by hartjo** [comment]
i cant use the new Routing and navigation from angular.io documentation

import { Routes, RouterModule }   from '@angular/router';

can't import Routes and Routermodule

**Comment by hartjo** [comment]
i solve the issue by reinstalling angular-cli into angular-cli@webpack thankyou :)
