### ISSUE TITLE
Styles are not applied after adding Material to module without restarting CLI

### ISSUE THREAD

**Issue by alvipeo** [angular/angular-cli#17852]
When I work on my app I use CLI as follows:

> ng serve --ssl --watch --aot

The app uses Material and has multiple modules. One of those modules does not have anything from Material, so I decided to add it - I import MatToolbarModule, for example to the `some.module.ts`. The app works, no compilation errors. But when I run it in a browser styles are not applied to this module's pages.

I wasted quite some time to find out I need to **restart** the CLI so it picks up Material in that module!

**Comment by SchnWalter** [comment]
I wasn't able to reporduce this in:
<details>
<summary>$ npx ng version  // click for details</summary>
<pre>
Angular CLI: 9.1.7
Node: 12.16.1
OS: linux x64
Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/material                 9.2.4
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</pre>
</details>


These are the steps that I've followed:

* Created new repository using `ng new my-app`
* Updated most dependnecies to latest version using `ncu`
* Added angular material using `ng add @angular/material`
* Added a couple of modules and components using the Angular CLI. One of them included a material component.
* Started `ng serve`
* Added `mat-toolbar` to the other module and the toolbar had the proper styles, without the need to "restart" `ng serve`.

<details>
<summary>$ git diff  // click for details</summary>
<pre>
diff --git a/src/app/second/another-page/another-page.component.html b/src/app/second/another-page/another-page.component.html
index 8e7638b..a941a4b 100644
--- a/src/app/second/another-page/another-page.component.html
+++ b/src/app/second/another-page/another-page.component.html
@@ -1,3 +1,4 @@
+&lt;mat-toolbar&gt;Second Page&lt;/mat-toolbar&gt;
 &lt;p&gt;another-page works!&lt;/p&gt;
 
 &lt;p&gt;
diff --git a/src/app/second/second.module.ts b/src/app/second/second.module.ts
index fa9876a..1052b23 100644
--- a/src/app/second/second.module.ts
+++ b/src/app/second/second.module.ts
@@ -1,5 +1,6 @@
 import { CommonModule } from &apos;@angular/common&apos;;
 import { NgModule } from &apos;@angular/core&apos;;
+import { MatToolbarModule } from &apos;@angular/material/toolbar&apos;;
 import { AnotherPageComponent } from &apos;./another-page/another-page.component&apos;;
 
 import { SecondRoutingModule } from &apos;./second-routing.module&apos;;
@@ -9,6 +10,7 @@ import { SecondRoutingModule } from &apos;./second-routing.module&apos;;
   imports: [
     CommonModule,
     SecondRoutingModule,
+    MatToolbarModule,
   ],
 })
 export class SecondModule {
</pre>
</details>

**Comment by alvipeo** [comment]
ok, I'm going to close it for now. I'll reopen it when I got the sample project. Thanks!
