### ISSUE TITLE
Security issue serialize-javascript prior to 3.1.0 allows remote attackers

### ISSUE THREAD

**Issue by lsrael-BGx** [angular/angular-cli#17858]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

@angular-devkit/build-angular/0.901.7 » copy-webpack-plugin/5.1.1
» serialize-javascript/2.1.2

serialize-javascript prior to 3.1.0 allows remote attackers to inject arbitrary code via the function "deleteFunctions" within "index.js".

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by vikramdadwal** [comment]
We are facing this issue too, any ETA ?
