### ISSUE TITLE
ng serve doesn't respect inheritance of ng build settings for a configuration in angular.json

### ISSUE THREAD

**Issue by mark-studer** [angular/angular-cli#17850]
#17720 🐞 Bug report

### Command (mark with an `x`)
- [x] serve

### Is this a regression?
Not sure.  Haven't seen this work correctly yet.

### Description
When using build configurations for ng build you can overwrite the default build options.  For example you set the optimization option to 'true' in the default section and overwrite it to 'false' for a local testing configuration.  Ng build works fine and you get what you would expect.  When you use ng serve and specify that configuration you end up getting a mix of the default values and the configuration values.  Specifically, you seem to get the default values set in the ng build section for options that match naming of options that exist in ng serve.  I.E.  The optimization setting when using ng serve is now 'true' instead of getting 'false'.  If you simply remove the default setting in ng build it now correctly picks up the configuration setting.

## 🔬 Minimal Reproduction
Here is a sample angular.json stripped down to just the necessary bits.
<pre><code>
{
    "projects": {
        "test": {
            "architect": {
                "build": {
                    "options": {
                        "optimization": true
                    },
                    "configurations": {
                        "local": {
                            "optimization": false
                        }
                    }
                },
                "serve": {
                    "options": {
                        "browserTarget": "test:build"
                    },
                    "configurations": {
                        "local": {
                            "browserTarget": "test:build:local"
                        }
                    }
                }
            }
        }
    }
}
</code></pre>

When running `ng serve -c local` you end up with optimization set to true.  If you remove the default value it picks up the value in the configuration.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0
Node: 12.16.2     
OS: win32 x64     

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.0
@angular-devkit/build-angular      0.901.0
@angular-devkit/build-ng-packagr   0.901.0
@angular-devkit/build-optimizer    0.901.0
@angular-devkit/build-webpack      0.901.0
@angular-devkit/core               9.1.0
@angular-devkit/schematics         9.1.0
@angular/cdk                       9.2.0
@ngtools/webpack                   9.1.0
@schematics/angular                9.1.0
@schematics/update                 0.901.0
ng-packagr                         9.1.0
rxjs                               6.5.4
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**
I believe the inheritance only fails to work on properties that have a similar name for both ng serve and ng build.  For example the optimization option is available for both.

**Current workaround**
To address the issue and still allow me to have a default i'm currently setting those properties in both the build and serve section.
<pre><code>
{
    "projects": {
        "test": {
            "architect": {
                "build": {
                    "options": {
                        "optimization": true
                    },
                    "configurations": {
                        "local": {
                            "optimization": false
                        }
                    }
                },
                "serve": {
                    "options": {
                        "browserTarget": "test:build"
                    },
                    "configurations": {
                        "local": {
                            "browserTarget": "test:build:local",
                            "optimization": false
                        }
                    }
                }
            }
        }
    }
}
</code></pre>

**Comment by SchnWalter** [comment]
I've tested this with the `outputHashing` configuration and it works just fine. I think that the `webpack-dev-server` and the module reload has something to do with the `optimization` and I'm not sure if this can ever work properly. Maybe we should display a warning when `ng serve` is used with this options (and others that might not work),  similar to the one for the `--prod` flag.

Here's a repo where you test `ng serve` and `ng serve -c local` and you will see that the example changes that you provided work just fine:
> https://github.com/SchnWalter/repo-for-repoducing-angular-issues/tree/17850-ng-serve-config-inheritance-issue

**Comment by alan-agius4** [comment]
Hi @mark-studer, this issue should be solved in version 9.1.3 via https://github.com/angular/angular-cli/pull/17515. 

Kindly update to the latest version of  the Angular CLI.

**Comment by mark-studer** [comment]
@alan-agius4 - Thanks for the information and link.  You are correct it now works as expected in 9.1.9 (what I tested).  I believe I had tested updating the angular CLI package, but not the angular/core.  Anyways after updating all of the angular packages it worked great.  Thanks again!
