### ISSUE TITLE
styles not working in app.component.ts @beta.11-webpack.2

### ISSUE THREAD

**Issue by PiusNyakoojo** [angular/angular-cli#1786]
## Bug Report
styles and styleUrls not working in the default app.component.ts

## Expected Behavior
- When 'styles' property is set in Component metadata, the application should be styled appropriately.

`styles: ['body { background-color: red }'] // should make the application's background red`

- When styleUrls is set using .css file name, the application should be styled appropriately.

`styleUrls: ['app.component.css'] // should work`

- Should work with .scss file as well. I used: ng set defaults.styleExt scss

`styleUrls: ['app.component.scss']`

## Actual Behavior
The application isn't styled from app.component.ts.

## Reproduction
- Create project

`ng new project-name --prefix pn`

- Add .scss support

`ng set defaults.styleExt scss`

- Add to app.component.ts

```
import { Component } from '@angular/core';

@Component({
    selector: 'pn-root',
    templateUrl: 'app.component.html',
    styleUrls: ['app.component.scss']
})

export class AppComponent {   }
```

- Add to app.component.scss
```
@import './app.style'

body {
    background-color: $bg-color;
}
```

- Add to app.style.scss

`$bg-color: red;`

- serve

`ng serve`

## Version details:
OS: Windows 10
node: 6.3.1
angular-cli@1.0.0-beta.11-webpack.2

**Comment by cport1** [comment]
try adding this to your @Component({ ..., encapsulation: ViewEncapsulation.None })

**Comment by deebloo** [comment]
@PiusNyakoojo it looks like you are trying to style the body tag from inside a component. By default all angular styles are scoped to their component so that won't work.

**Comment by josepcrespo** [comment]
What @deebloo said should explicitly said in the official Angular.io tutorial, it saved my day!
