### ISSUE TITLE
check if a file created by template

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#17892]
if I have a rule that applies a template,  how can I make the next rule to check if the file created?

```
return (tree, context){
   
//this step should create a file called 'test.txt'
   let rule = apply(url(..), [template(..)]
   branchAndMerge(mergeWith(rule));

  //how should I check for a file that is recently created by the previous step?
  console.log(tree.exists('test.txt'))

}
```

**Comment by alan-agius4** [comment]
Hi @eng-dibo, 

You'll need to create a new Rule (which can be inlined) and access the tree.
```ts
chain([
      branchAndMerge(mergeWith(rule)),
      tree => console.log(tree.exists('test.txt'))
])
```

Closing as this doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
