### ISSUE TITLE
Sourcemaps problem on @beta.11-webpack.2

### ISSUE THREAD

**Issue by Nick0n** [angular/angular-cli#1790]
Sourcemaps seem to be broken now. I can't debug TS files because all the set breakpoints hit very badly.

- Angular 2 RC5
- Angular-CLI 1.0.0-beta.11-webpack.2

**Comment by agaripian** [comment]
I am having the same issue as well.

**Comment by kjartanvalur** [comment]
Same here

**Comment by bartlomiejborzucki** [comment]
+1

**Comment by ValeryVS** [comment]
This was probably related to #1490 
and was fixed with #1659 

I saw typescript source map issue in 1.0.0-beta.11-webpack.2, but, for me, this was fixed in master branch.

**Comment by Nick0n** [comment]
Thanks for information!
