### ISSUE TITLE
Bug: loadChildren with a non-string syntax

### ISSUE THREAD

**Issue by QBIRGAENTZLE** [angular/angular-cli#17908]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I want to lazy load a module with a specific configuration

app-routing-module.ts

```
  {
    path: 'mcs',
    loadChildren: () =>
      import('ng-multi-criteria-search').then(mcs => {
        mcs.MultiCriteriaSearchModule.config = FPS_MCSConfig;
        return mcs.MultiCriteriaSearchModule;
      })
  },
```

But build failed : 

```
WARNING in 
Found 'loadChildren' with a non-string syntax in /home/MyHome/www/MyProject/client/src/app/app-routing.module.ts but could not transform it.
Make sure it matches the format below:

loadChildren: () => import('IMPORT_STRING').then(M => M.EXPORT_NAME)

Please note that only IMPORT_STRING, M, and EXPORT_NAME can be replaced in this format.
```

I found I should use this specific format : 

`import('ng-multi-criteria-search').then(mcs => mcs.MultiCriteriaSearchModule)` (which works)

But in my case, I need to initalize `mcs.MultiCriteriaSearchModule.config` before returning it. I don't find the correct syntax or config to pass the build (everything works fine in serve mode)

I use the same method on an Angular 9 project and the app is building, try to use the same thing on this Angular 8 project, but it failed.

## 🌍 Your Environment
<pre><code>
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cdk                      8.2.3
@angular/cli                      8.3.26
@angular/flex-layout              8.0.0-beta.27
@ngtools/webpack                  8.3.26
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.5.5
typescript                        3.4.5
webpack                           4.39.2
</code></pre>

**Comment by alan-agius4** [comment]
Indeed @QBIRGAENTZLE, the above works with version 9 and Ivy.

Closing since this works in version 9. Version 8 is currently in LTS and thus only critical security fixes are applied.

See: https://angular.io/guide/releases
