### ISSUE TITLE
How to trigger runtime config in Angular?

### ISSUE THREAD

**Issue by rotirk20** [angular/angular-cli#17907]
Hello, I have implemented runtime config in Angular (found here: [link](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1403)) and I want to know how can I build once and change values in config.json without building again. I can't get it how to trigger that runtime config.

Thanks

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
