### ISSUE TITLE
ng serve - add special header to some files in assets (proxy)

### ISSUE THREAD

**Issue by kamil-kielczewski** [angular/angular-cli#17910]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know - but probably yes according to [this](https://stackoverflow.com/questions/59266224/angular-add-custom-http-response-headers-to-dev-ng-serve).

### Description

I need to add some header to file `/assets/unity/webgl.wasm` e.g. `my-header: some-token-value` - this file will not works without this header - so it is important.

## 🔬 Minimal Reproduction

I try solutions described on internet: in `angular.json`  I set key `projects.my-project.serve.options.proxyConfig: "proxy.config.js"`

Then I create "proxy.config.js"

```javascript
const PROXY_CONFIG = {
  // "/assets/unity/webgl.wasm": {       // I try many combinations of PATH
  // "/assets/*": {
  // "/assets": {
  // "/": {
  // "/*": {
  // "*": {
  "/assets/unity/*.wasm": {
       // "target": "http://my-project:3002/assets",
      "secure": false,
      //"logLevel": "debug",
      "selfHandleResponse": true,
      "onProxyRes": function (proxyRes, req, res) {      
          console.log('PRRRRROOOXXXXYYYY RUN');
          proxyRes.headers['Content-Type'] = 'application/json';
          res.headers["X-KKCustom-Header"] = "yes";
        },
      // "bypass": function (req, res, proxyOptions) {
      //   console.log('PRRRRROOOXXXXYYYY RUN');
      //   proxyRes.headers['Content-Type'] = 'application/json';
      //   res.headers["X-KKCustom-Header"] = "yes";
      // },
    },
};

console.log('PRRRRROOOXXXXYYYY INIT');
module.exports = PROXY_CONFIG;
```
And try run it in many configurations - but not works. After run server I only see  
> 'PRRRRROOOXXXXYYYY INIT'
> ..
> [HPM] Subscribed to http-proxy events:  [ 'proxyRes', 'error', 'close' ]
(if I use `bypass` I don't see 'proxyRes')

## 🔥 Exception or Error

Just not works - header is not included to serwer response (and on server console I DON'T see 'PRRRRROOOXXXXYYYY RUN' so I guess onProxyRes/bypass function is never  triggered). I try many combinations of paths, and PROXY_CONFIG fields.

## 🌍 Your Environment

> Angular CLI: 8.0.2
> Node: 12.11.1
> OS: linux x64
> Angular: 8.0.0

I run angular on MacOs High Sierra using inside [docker node](https://hub.docker.com/_/node/) by:

`ng serve --host 0.0.0.0 --port 3002 --disable-host-check --poll 1`

and outside docker in browser application works on http://my-project.local:3002

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @kamil-kielczewski,

You need to add the new header to `proxyRes` and not `res`.

See: https://github.com/angular/angular-cli/issues/15095#issuecomment-511967756

**Comment by kamil-kielczewski** [comment]
@alan-agius4 In above code I use both but I also try with `proxyRes`, and `res` separatley - not works (the onProxyRes function is never executed at all)

**Comment by alan-agius4** [comment]
Hi @kamil-kielczewski,

I had a bit of a look at this and it seems that the middleware proxy in `webpack-dev-server` is used as fallbacking when a request is not resolved.

You can opt to add this header to all responses using the `headers` option (https://webpack.js.org/configuration/dev-server/#devserverheaders-) by extending the default Webpack configuration. This can be done using a 3rd party builders such as https://github.com/manfredsteyer/ngx-build-plus or https://github.com/just-jeb/angular-builders

**Comment by alan-agius4** [comment]
Closing as this is not actionable from our end.

Kindly let me know if you have any further queries.

Thanks.
