### ISSUE TITLE
Security issue serialize-javascript prior to 3.1.0 allows remote attackers

### ISSUE THREAD

**Issue by marinaua** [angular/angular-cli#17912]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

@angular-devkit/build-angular/0.901.8 » terser-webpack-plugin/2.3.5
» serialize-javascript/2.1.2

serialize-javascript prior to 3.1.0 allows remote attackers to inject arbitrary code via the function "deleteFunctions" within "index.js".

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/17918
