### ISSUE TITLE
angular-devkit/build-angular "0.901.8" Bug

### ISSUE THREAD

**Issue by kion-admin** [angular/angular-cli#17925]
after update angular-devkit/build-angular from "0.901.7" to "0.901.8" my project throw code 137 (memory error) and not complate build (ng build --prod) in my docker (on ubuntu) pipeline

**Comment by clydin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by TreatDarren** [comment]
@clydin  For what it is worth, we also have seen this. Upon building projects with 0.901.8 there is a massive spike in memory use in prod builds that causes npm to eventually hit memory limits. 

On our end, while this bug ticket does not match the requirements, this is an extremely serious breaking issue that forced us to revert. In our large project we saw 16GB ram used on `.8` but 2GB on `.7`. Something is very, very wrong.

**Comment by wesselvdv** [comment]
I am having the same issue from what it seems, my builds aren't even completing anymore. Stuck for atleast an hour when running with @angular-devkit/build-angular > 0.901.7, while running with 0.901.7 it completes with 9 minutes.

**Comment by wesselvdv** [comment]
My gut feeling is that it has something to do with copy-webpack-plugin which had a major update. I can see some issues with files being copied/moved too much in their repositories, but I have no idea how to verify this.
