### ISSUE TITLE
Is this still reproducible with Angular CLI version 9?

### ISSUE THREAD

**Issue by MichaelOdumosu57** [angular/angular-cli#17957]
Is this still reproducible with Angular CLI version 9?

_Originally posted by @alan-agius4 in https://github.com/angular/angular-cli/issues/9338#issuecomment-561108893_

its being reproduced here check out this issue
https://github.com/waysact/webpack-subresource-integrity/issues/124

**Comment by alan-agius4** [comment]
@MichaelOdumosu57, kindly follow the issue template and provide a minimal reproduction.

Unfortunately, you didn’t provide enough information that we can reproduce the issue. Also, the linked issue appears to be unrelated to inconsistent file hashing. 

Thanks.
