### ISSUE TITLE
Eliminate render-blocking resources

### ISSUE THREAD

**Issue by geetika-kathuria** [angular/angular-cli#17966]
Team,

I'm getting the following recommendation using lighthouse 
<img width="1004" alt="Screen Shot 2020-06-19 at 1 14 42 pm" src="https://user-images.githubusercontent.com/19775166/85093259-185a4e80-b22f-11ea-8936-9b4a35969e49.png">

Even for a base application with no content, its complaining about styles.css
After adding my own code, I'm sure it will reduce the performance score even further.

So the question is either is it a known bug and if yes, can you please point me to the issue tracker/expected fix? Or are there any best practices that I'm totally missing?

Apologies if its a basic question but I can really appreciate some help.

Thanks,
Geetika.

**Comment by geetika-kathuria** [comment]
Team, any update on this issue?

**Comment by alan-agius4** [comment]
Hi @geetika-kathuria, we are currently liaising with the Chrome team to find a solution for this.

**Comment by geetika-kathuria** [comment]
@alan-agius4 Thank you for your prompt response.

**Comment by djouf007** [comment]
Any update for this ?

**Comment by alan-agius4** [comment]
We have created an RFC for this, kindly see: https://github.com/angular/angular-cli/issues/18730

**Comment by stephengardner** [comment]
Using the latest build of @angular/cli ~0.1101.0-next.3 with configuration 
    
              "optimization": {
                "scripts": true,
                "fonts": {
                  "inline": true
                },
                "styles": {
                  "minify": true,
                  "inlineCritical": true
                }
              },
And ng serve --prod on  a Hello World angular application does not pass the PageSpeed Insights critical CSS measurement.

Is this intended to be solved on the latest prerelease of the CLI yet?
