### ISSUE TITLE
Make ng-serve Also Serve 3rdpartylicenses.txt

### ISSUE THREAD

**Issue by SethiPandi** [angular/angular-cli#17965]
# 🚀 Feature request
### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Currently `ng build` can generate the `3rdpartylicenses.txt`, which is great, but `ng serve` isn't able to serve the `3rdpartylicenses.txt`. This is a bit inconvenient as a website may wish to use the file on a `/licenses` page to display all third-party licenses that were used. Everything is there to make this for production, but not a simple means to test it in development without hosting a mock `3rdpartylicenses.txt` somewhere and loading that instead.

### Describe the solution you'd like
 Could an option be provided to generate and serve the 3rd party licenses files along with the rest of the application in `ng serve`.

**Comment by alan-agius4** [comment]
Hi @SethiPandi, 

This is already possible. `ng serve` also uses the options in the build target. Hence, you need to add `"extractLicenses": true` under `build` options in `angular.json`.

**Comment by SethiPandi** [comment]
Ahh, sorry about that.
Thanks for the heads up!
