### ISSUE TITLE
Webpack: setting custom paths.

### ISSUE THREAD

**Issue by urosjarc** [angular/angular-cli#1796]
It would be really nice if in webpack version of angular-cli you could set custom path for coverage report, dist, public path, ...etc. I would really like webpack settings would be more customizable.

```javascript
      new CopyWebpackPlugin([{
        context: path.resolve(projectRoot, './public'),
        from: '**/*',
        to: path.resolve(projectRoot, './dist')
      }])
```

**Comment by deebloo** [comment]
in master there are more configuration options in the angular-cli.json file. So those should be coming soonish?
![screen shot 2016-08-22 at 9 00 54 am](https://cloud.githubusercontent.com/assets/6563621/17855505/fddf65c6-6846-11e6-8cc5-d48b7610ad0b.png)

as for the coverage report you can change the destination by updating the following in karma config.
![screen shot 2016-08-22 at 9 02 29 am](https://cloud.githubusercontent.com/assets/6563621/17855533/337da13e-6847-11e6-83ae-092e4f3c14b9.png)

**Comment by deebloo** [comment]
The idea with this I believe is to abstract the actual build process away from the end user so that in the future if the build needs to change it won't require changes on your end.

**Comment by filipesilva** [comment]
@deebloo is correct. https://github.com/angular/angular-cli/pull/1633 added a lot of configurable items.
