### ISSUE TITLE
Don't strip out crypto

### ISSUE THREAD

**Issue by johannesjo** [angular/angular-cli#17964]
With all major browsers having support for the crypto api (https://caniuse.com/#feat=cryptography) #1548 should imho finally be taken care of. This might have slipped under the radar, but it bit me time and time again.

**Comment by clydin** [comment]
Besides performing similar functions, the [Web Cryptography API]( https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) and the [Node.js crypto builtin module](https://nodejs.org/api/crypto.html#crypto_crypto) are not related.  They existing on different platforms (browsers and Node.js, respectively).
The Web Cryptography API can be used currently and its use is not affected by the Angular CLI.
