### ISSUE TITLE
Routes and RouterModule not being exported by @angular/router

### ISSUE THREAD

**Issue by rjcoupe** [angular/angular-cli#1797]
- OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
*Ubuntu 16.04*

- Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.10
node: 6.3.0
os: linux x64
```

- Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
*App was created using angular-cli, angular-cli has been updated to the most recent version since then and `ng init` has been run to update files. I have also updated package.json to use Angular2 rc5.*

- The log given by the failure. Normally this include a stack trace and some
   more information.
```
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /home/rjcoupe/Projects/NewsHub/frontend/tmp/broccoli_type_script_compiler-input_base_path-QiI91S9Z.tmp/0/src/app/app.module.ts (3, 10): Module '"/home/rjcoupe/Projects/NewsHub/frontend/node_modules/@angular/router/index"' has no exported mng 'RouterModule'.
  /home/rjcoupe/Projects/NewsHub/frontend/tmp/broccoli_type_script_compiler-input_base_path-QiI91S9Z.tmp/0/src/app/app.routes.ts (1, 10): Module '"/home/rjcoupe/Projects/NewsHub/frontend/node_modules/@angular/router/index"' has no exported mng 'Routes'.
```

*These errors are triggered by files that include the following lines:*

`import { Routes } from '@angular/router';`
`import { RouterModule } from '@angular/router';`

- Mention any other details that might be useful.

*I'm trying to follow the documentation found at https://angular.io/docs/ts/latest/tutorial/toh-pt5.html*

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yusijs** [comment]
Did you follow the update guide? Your local install is outdated.

**Comment by rjcoupe** [comment]
I'm on angular-cli@latest, rather than the webpack beta.

**Comment by yusijs** [comment]
Check what version of the angular router you're on maybe? Could be that's outdated.

**Comment by rjcoupe** [comment]
`"@angular/router": "3.0.0-beta.2"`

That's what package.json includes; AFAIK that's up to date but I'm very open to correction.

**Comment by yusijs** [comment]
The router is on rc.1 now - try upgrading to that, and you should be good! :)

**Comment by rjcoupe** [comment]
Perfect; thank you!

**Comment by yusijs** [comment]
No worries, glad it worked out! ☺
