### ISSUE TITLE
buildRelativePath for package name

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#17971]
if a package name passed to `buildRelativePath()` instead of a fs path, it should return the package name as it.

```
buildRelativePath("app.module.ts", "./file.ts")
//returns  ../../file.ts

buildRelativePath("app.module.ts", "@scope/package-name")
//returns @scope/package-name

buildRelativePath("app.module.ts", "package-name")
//returns package-name
//should be treated as a package name and not an absolute or relative path unless it starts with `/` or './`
```

this issue is related to angular schematics and located in `@schematics/angular/utility/find-module`

**Comment by alan-agius4** [comment]
Those utils are part of the private API.

I don’t see any of our schematics to be effected, if indeed this effects one of our schematics please follow the issue template and provide a reproduction.
