### ISSUE TITLE
v10.0.0-rc.5 ng add @angular/material error

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular-cli#17977]
step: 
ng new simple-test
ng add @angular/material
error 

![image](https://user-images.githubusercontent.com/8691013/85220436-f652fe80-b3dd-11ea-9e49-73891ce53474.png)

Angular CLI: 10.0.0-rc.5
Node: 12.18.0
OS: win32 x64

Angular: 10.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0-rc.5
@angular-devkit/build-angular     0.1000.0-rc.5
@angular-devkit/build-optimizer   0.1000.0-rc.5
@angular-devkit/build-webpack     0.1000.0-rc.5
@angular-devkit/core              10.0.0-rc.5
@angular-devkit/schematics        10.0.0-rc.5
@angular/cdk                      7.3.7
@angular/cli                      10.0.0-rc.5
@angular/material                 7.3.7
@ngtools/webpack                  10.0.0-rc.5
@schematics/angular               10.0.0-rc.5
@schematics/update                0.1000.0-rc.5
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

note : 
the cdk and material version is 7.3.7, this is very suspicious.
for workaround, can separate 2 command, 
ng add @angular/cdk first then ng update --next 
after that ng add @angular/material and ng update --next

**Comment by alan-agius4** [comment]
Hi, 

Since you are using a prerelease version of Angular? you should also use a prerelease version of @angular/material.

```
ng add @angular/material@next
```
