### ISSUE TITLE
`ng add` installs old package versions in 10.0.0-rc.5

### ISSUE THREAD

**Issue by tsvetomir** [angular/angular-cli#17983]
# 🐞 Bug report

### Command
- [x] add

### Is this a regression?
Yes, the previous version in which this bug was not present was v9.1.9

### Description

`ng add` installs old versions instead of `latest`. Managed to reproduce it with both `@kendo-angular-buttons` (installs v0.10.1) and `@angular/material` (installs v7.3.7).

## 🔬 Minimal Reproduction
1. `npm install -g @angular/cli@next`
1. `ng new ng10-project --defaults --skip-git`
1. `cd ng10-project`
1. `ng add @progress/kendo-angular-buttons`

The problem **does not occur** if we specify a version to be installed, e.g.
`ng add @progress/kendo-angular-buttons@latest`

## 🔥 Exception or Error
<pre><code>
The package that you are trying to add does not support schematics. You can try using a different version of the package or contact the package author to add ng-add support.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.0-rc.5
Node: 10.14.0
OS: linux x64

Angular: 10.0.0-rc.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0-rc.5
@angular-devkit/build-angular     0.1000.0-rc.5
@angular-devkit/build-optimizer   0.1000.0-rc.5
@angular-devkit/build-webpack     0.1000.0-rc.5
@angular-devkit/core              10.0.0-rc.5
@angular-devkit/schematics        10.0.0-rc.5
@angular/cli                      10.0.0-rc.5
@angular/platform-server          2.0.0
@ngtools/webpack                  10.0.0-rc.5
@schematics/angular               10.0.0-rc.5
@schematics/update                0.1000.0-rc.5
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
This is because `@progress/kendo-angular-buttons` latest version doesn't support Angular 10. See: https://unpkg.com/browse/@progress/kendo-angular-buttons@5.4.2/package.json. Since this is an incompatible version, `ng update` will try to find a version which doesn't have this constraint and is "compatible".

This doesn't happen when using a version tag `@latest` because you are forcefully installing that particular version.

**Comment by tsvetomir** [comment]
Thanks, we'll update the version range to include 10.

Is this a new behavior in v10? Seems convenient, once you know how it works :)
An information message about the chosen version would be nice.

**Comment by alan-agius4** [comment]
@tsvetomir, no it’s not new, it’s been around for a couple of majors now.

Agreed that an info message would be good in this case.

**Comment by shaharkazaz** [comment]
@alan-agius4 I just experienced the same issue with version 10+, but I wasn't able to reproduce in lower versions (tried `v9.1.10` & `v8.3.19`)
