### ISSUE TITLE
ng serve returns 200 for non-existent files in the assets folder instead of 404 - user gets redirected to the default route

### ISSUE THREAD

**Issue by owlyowl** [angular/angular-cli#17989]
# 🐞 Bug report

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Y - Was fixed as part of https://github.com/angular/angular-cli/issues/2989
Currently running Angular CLI 6.1.5 for an Angular 6 project and experiencing the same issues

### Description

When running ng serve if an image file doesn't exist eg http://localhost:4200/assets/img/filedoesnotexist.jpg instead of returning a 404 response the @angular-devkit/build-angular:dev-server returns a 200 response and redirects to the '' route

I think I need to use a custom builder or if there's another fix I'd love to know but at present it is like the webpack dev server doesn't serve anything in the assets as a static file so it runs through routing

The fix appears to force accept HTML headers option to webpack dev server.

https://github.com/angular/angular-cli/issues/2989

I have the exact issue where if I request a missing image instead of 404ing it returns 200 and tries to redirect to index.html

I was wondering how to use this in my angular.json I'm using angular 6 and CLI version 6.1.5

Or if someone knows of a fix

I'd love someone to run up a quick sample project with a few routes and some images and have some assets return 404

## 🔬 Minimal Reproduction
To test open the ng-test.zip file:
https://www.dropbox.com/s/5f9putxrny4kfrk/ng-test.zip?dl=0

1. Run npm i
2. Run ng serve
3. Navigate to http://localhost:4200/assets/icons/trafficlight.png

4. You'll see the image served
5. Navigate to http://localhost:4200/assets/icons/nonexistentfile.png

6. Instead of a 404 you get routed to the home screen

## 🌍 Your Environment
<pre><code>
Angular CLI 6.1.5

Can also reproduce in Angular CLI: 9.1.9 and subsequent latest packages
</code></pre>

**Anything else relevant?**
Running "builder": "@angular-devkit/build-angular:dev-server", in angular.json

I don't know if the intention of the team is to have people run a custom dev-server instead?

I couldn't find anything in the 200 headers returned for a missing asset file to indicate an error or anything it just looks like a normal 200

![image](https://user-images.githubusercontent.com/1916426/85363814-2d075100-b565-11ea-9dfd-9a8565878281.png)

Here's an example of the fact the dev server a non-existent jpg file as html and returns a 200

**Comment by alan-agius4** [comment]
Hi @owlyowl following a chat @clydin, this is a caused by another fix #2168. This fixed an issue were valid routes with dots would return 404.

Unfortunately, there is nothing that we can from our end, since by fixing this issue we'll break something else.
