### ISSUE TITLE
I'm using a custom builder to inject some machine based environment variables using this in `angular.json`:

### ISSUE THREAD

**Issue by nsejim** [angular/angular-cli#17981]
I'm using a custom builder to inject some machine based environment variables using this in `angular.json`:

      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "extra-webpack.config.js"
          }, ...
        }
      }

If my `extra-webpack.config.js` looks like this, it's fine:

    module.exports = { ... };

But if I try to do this, it breaks, but the breaking also breaks:

    module.exports = (env, args) => { ... };

_Originally posted by @joshcomley in https://github.com/angular/angular-cli/issues/16043#issuecomment-549063875_

**Comment by nsejim** [comment]
Hi @joshcomley.

You just have to define the stats property inside the returned object

module.exports = (env, args) => { 
    ....
   return {
      ....,
     stats: 'verbose',
    ....
   }
};

For more info about the available options for "stats", check https://webpack.js.org/configuration/stats/

**Comment by alan-agius4** [comment]
Hi @nsejim,  thanks for reporting the issue but custom builders are not support by the Angular tooling team.
