### ISSUE TITLE
Differential builds

### ISSUE THREAD

**Issue by gidon-handler** [angular/angular-cli#17987]
Hello
According to the Docs there is a way to disable Differential builds.
By disable I mean build only new ES2015 and newer bundles.
I do not need to support older browsers.
I tried all possible combinations in browserlist file and tsconfig.json but to no avail.

Please advise on the correct way to configure this result.

Thank you

**Comment by alan-agius4** [comment]
@gidon-handler, in your browserslist configuration list the browsers that you want to support.

If non of the listed browsers require ES5 support, differential loading will be disabled.

Ex: https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/application/files/.browserslistrc.template

**Comment by gidon-handler** [comment]
Hi Alan
Tried that example. Doesn't compile.
Event if I do just "last 1 Chrome version" in browserlist I'm still getting es5 bundles.
p.s. I'm on Angular 9.1.0

Thank you

**Comment by alan-agius4** [comment]
Are you setting the syntax target to es2015 in your tsconfig.json file?

**Comment by gidon-handler** [comment]
Yes, of course, even tried es2018, as it says in the Docs that higher than es2015 differential builders are also disabled. But nothing helps. I'm always getting es5 as well.

**Comment by alan-agius4** [comment]
@gidon-handler, without providing a reproduction its hard to tell what’s happening.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by gidon-handler** [comment]
Will test this issue in a clean project.

**Comment by gidon-handler** [comment]
Hi Alan.
Found the problem. browserlist had to be moved one directory up.
As we started this project in Angular 6, browserlist was in src.
We are now in latest version and for some reason the right place for browser list is in the root.
Do this make sense?

**Comment by alan-agius4** [comment]
`browserslist` should be in the `sourceRoot`

**Comment by gidon-handler** [comment]
I just ran ng new and double checked....browserlist is most definitely not in src. Its one  up, In the root directory.
global cli = 9.1.7

**Comment by alan-agius4** [comment]
@gitter-badger, you are right, sorry about that.

**Comment by gidon-handler** [comment]
👍
