### ISSUE TITLE
Error when running schematics unit test

### ISSUE THREAD

**Issue by michaelfaith** [angular/angular-cli#17986]
This is my first time working in the world of schematics, so it's quite possible I just don't have this set up correctly.  But I've been following the guide on angular.io and some additional blog walkthroughs.  I'm wanting to package ng-add and ng-update schematics into a component library, that I already have setup and running well.  After setting up the initial plumbing for the ng-add one, I wrote a simple unit test just to validate the setup and as soon as it hits the call to new SchematicTestRunner, it blows up with a ton of Module not found errors, including child_process and fs.  In fact i commented out everything in the unit test except the creation of the test runner, just to identify the breaking point.  And the schematic itself isn't doing anything yet except returning the tree as-is.  Interestingly, the "blank" schematics project doesn't use ng test at all, but instead uses jasmine directly.  But with this being in an existing Angular Library with full test suite, i wanted to test in the same way.  Any help with this, would be much appreciated!

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure.  First time doing this.

## 🔥 Exception or Error
<pre><code>
ERROR in C:/Users/<username>/src/fabric/ui/node_modules/@angular-devkit/schematics/tasks/node-package/executor.js
Module not found: Error: Can't resolve 'child_process' in 'C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\tasks\node-package'
resolve 'child_process' in 'C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\tasks\node-package'
  Parsed request is a module
  using description file: C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\package.json (relative path: ./tasks/node-package)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Users/<username>/src/fabric/ui
        using description file: C:\Users\<username>\src\fabric\ui\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\<username>\src\fabric\ui\package.json (relative path: ./child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\child_process.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\child_process.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\child_process.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\child_process.js doesn't exist
            as directory
              C:\Users\<username>\src\fabric\ui\child_process doesn't exist
      C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\tasks\node-package\node_modules doesn't exist or is not a directory
      C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\tasks\node_modules doesn't exist or is not a directory
      C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\node_modules doesn't exist or is not a directory
      C:\Users\<username>\src\fabric\ui\node_modules\node_modules doesn't exist or is not a directory
      C:\Users\<username>\src\fabric\node_modules doesn't exist or is not a directory
      C:\Users\<username>\src\node_modules doesn't exist or is not a directory
      C:\Users\<username>\node_modules doesn't exist or is not a directory
      C:\Users\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules
        using description file: C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in C:\Users\<username>\src\fabric\ui\node_modules
        using description file: C:\Users\<username>\src\fabric\ui\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: C:\Users\<username>\src\fabric\ui\package.json (relative path: ./node_modules/child_process)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\child_process doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\child_process.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\child_process.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\child_process.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.js doesn't exist
            as directory
              C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process doesn't exist
              C:\Users\<username>\src\fabric\ui\node_modules\child_process.js doesn't exist
            as directory
              C:\Users\<username>\src\fabric\ui\node_modules\child_process doesn't exist
[C:\Users\<username>\src\fabric\ui\child_process]
[C:\Users\<username>\src\fabric\ui\child_process.ts]
[C:\Users\<username>\src\fabric\ui\child_process.tsx]
[C:\Users\<username>\src\fabric\ui\child_process.mjs]
[C:\Users\<username>\src\fabric\ui\child_process.js]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\tasks\node-package\node_modules]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\tasks\node_modules]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\node_modules]
[C:\Users\<username>\src\fabric\ui\node_modules\node_modules]
[C:\Users\<username>\src\fabric\node_modules]
[C:\Users\<username>\src\node_modules]
[C:\Users\<username>\node_modules]
[C:\Users\node_modules]
[C:\node_modules]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process]
[C:\Users\<username>\src\fabric\ui\node_modules\child_process]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.ts]
[C:\Users\<username>\src\fabric\ui\node_modules\child_process.ts]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.tsx]
[C:\Users\<username>\src\fabric\ui\node_modules\child_process.tsx]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.mjs]
[C:\Users\<username>\src\fabric\ui\node_modules\child_process.mjs]
[C:\Users\<username>\src\fabric\ui\node_modules\@angular-devkit\schematics\node_modules\child_process.js]
[C:\Users\<username>\src\fabric\ui\node_modules\child_process.js]
 @ C:/Users/<username>/src/fabric/ui/node_modules/@angular-devkit/schematics/tasks/node-package/executor.js 11:24-48
 @ C:/Users/<username>/src/fabric/ui/node_modules/@angular-devkit/schematics/tasks/node/index.js
 @ C:/Users/<username>/src/fabric/ui/node_modules/@angular-devkit/schematics/testing/schematic-test-runner.js
 @ C:/Users/<username>/src/fabric/ui/node_modules/@angular-devkit/schematics/testing/index.js
 @ ./schematics/ng-add/index.spec.ts
 @ . sync \.spec\.ts$
 @ ./test.ts
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.7
Node: 12.13.0
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cdk                       9.2.4
@angular/cli                       9.1.7
@angular/flex-layout               9.0.0-beta.31
@angular/material                  9.2.4
@ngtools/webpack                   9.1.7
@schematics/angular                9.1.9
@schematics/update                 0.901.7
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0

</code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by michaelfaith** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

I understand.  I'll try stackoverflow.  I guess, if anything, this is feedback that the documentation around schematic unit testing could use some coverage. 😅

**Comment by Brudus** [comment]
@alan-agius4 I understand that you can't help with support requests. I also just started out with schematics but face exactly the same issue. That said, it is maybe really just an error on the user side. The interesting part is though, that the problem occurs even when you add the SchematicTestRunner to a fresh installed Angular app. It's pretty easy to reproduce. 

So it seems to be unrelated to libraries or any specific setup. I even tested it on a completely new device, installed Angular, `ng new project-name`. Without the `SchematicTestRunner`, `ng test` simply tests all files. As soon as the `SchematicTestRunner` is created the test won't build anymore with hundreds of these errors. This is what I added to the fresh project in the file app.component.spec.ts: 

`const runner = new SchematicTestRunner('test', '..');`

That 1 line of code (two with the import) is enough to make the whole test setup fail. So it may not be an error. But it should then be somehow and somewhere documented how to use the SchematicTestRunner in a default project setup with Karma and Jasmine.

Anyway, just my two cents that it's unrelated to a specific setup or the library context.

**Comment by alan-agius4** [comment]
Oh I see what you are doing! 

Schematics building/bundling/testing cannot be performed using the `ng` commands. This is because `ng test`, `ng build` etc.. are meant to be used for Angular browser application and libraries.

Take a look at https://angular.io/guide/schematics-authoring which explains and shows how to create a new blank schematics projects using the Schematics CLI.

In the blank schematics project you'll have a handful of useful scripts to build and test your schematics https://github.com/angular/angular-cli/blob/3134a7390b9ff7c908bbc5465ba373447202e480/packages/schematics/schematics/blank/project-files/package.json.template#L6-L7

In case you want to add the schematics in your application/library directory, just copy the generated the generated files, add the dependencies and scripts to the root `package.json`.

**Comment by Brudus** [comment]
Ah, that makes sense! I will try it out. Thank you very much!

**Comment by michaelfaith** [comment]
@alan-agius4 @Brudus Thanks for helping to get to the bottom of this.  I wasn't aware `ng test` wasn't what you used for these.  And since i was using the .spec naming convention for the spec files, rather than _spec, the default karma/spec configuration was picking them up as part of the regular component library testing and throwing those errors.  Since i'm wanting to have these live alongside the library (similar to how Angular Material has theirs), what's the recommended way to segment the testing so that component testing with `ng test` won't run the schematics tests and vice versa?

**Comment by michaelfaith** [comment]
So, based on the discussion, i was able to segment the schematics testing in a way that works for my library.  One thing i did when i first set up the library, before schematics came into the picture, was flatten the structure a bit, and remove the src folder.  Much like the angular material library folder, everything under projects/<project-name> are just the folders of my reusable components along with the package.json, ng-package, etc.  So putting a schematics folder among the others (like material), is the way i organized it.  So then the problem becomes how to run the schematics tests independently.  

Here is the way i tackled it for my case, in case it helps others.

- I updated my tsconfig.spec.json in the lib folder to exclude ./schematics:

```
"exclude": [
    "./schematics/**/*"
  ]
```
- Added dedicated tsconfig.schematics.ts to the schematics folder, using settings from the "blank" schematics project and from angular materials tsconfig.  Outdir, though, i set to ./dist/schematics, instead of building the files in place.
 - Updated the test.ts file to exclude the schematics folder from `ng test` runs
`const context = require.context('./', true, /^(?!.*(?:schematics)).*\.spec\.ts$/);`

- Added four scripts to package.json
```
"full-lib:build": "npm run components:build && npm run schm:build && npm run schm:copy",
"schm:build": "tsc -p projects/fabric-components/schematics/tsconfig.schematics.json && cpx projects/fabric-components/schematics/**/{collection.json,schema.json,files/**} dist/schematics",
"schm:copy": "cpx \"dist/schematics/**/!(*.spec.*|test-utils.*)\" dist/fabric-components/schematics",
"schm:test": "npm run schm:build && jasmine dist/schematics/**/*.spec.js",
```
Notice the schm:copy script excludes the test files generated by the schematics build, so they aren't packaged into my library.
