### ISSUE TITLE
Production Build Breaks Code

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#17999]
I can't be very helpful with this bug report other than to say that it works fine when running the AOT build, and breaks when compiling with `--prod`.  

I have multiple modules that are package with the Angular Package Format and the module that breaks with the production build is a pretty advanced forecasting package with AI etc. so nailing down exactly what breaks is hard.

More notes here:
https://stackoverflow.com/questions/62546996/debugging-uncaught-typeerror-cannot-read-property-iteration-of-undefined

If I get a better grip on it in the future I'll post back.  Once I get the app deployed without optimization, I could probably deploy another in parallel just to show whats happening.

**Comment by alan-agius4** [comment]
Kindly follow the issue template. The issue template is there to help us triage and fix issues faster.

Thanks

**Comment by fireflysemantics** [comment]
Yeah I just wanted to put it on your radar.  I wonder if the web workers are being compiled to the same name ... Just something to look out for.
