### ISSUE TITLE
Copy Images / Specific Directories to Dist from node_modules

### ISSUE THREAD

**Issue by sqwk** [angular/angular-cli#1801]
In the old system.js cli version, there was an option to copy files from `node_modules` to the `dist/vendor` directory using the `vendorNpmFiles` array.

    module.exports = function(defaults) {
        return new Angular2App(defaults, {
            vendorNpmFiles: [
            '...',
            'font-awesome/fonts/**/*',
            '...'
            ]
        });
    };

Where has this functionality gone in the new webpack based cli?

EDIT: Has this been solved by #1633?

**Comment by filipesilva** [comment]
For fonts and other CSS referenced thing yes, it should be solved in #1633.

**Comment by Dinistro** [comment]
@filipesilva I'm sorry to disturb you, but I don't see how I can use something like `vendorNpmFiles`. I'm trying to load some images from the `node_modules`. I added them in the `assets` array, but it looks like the relative path to `node_modules` breaks the copy process.

```
"assets": [
        "assets",
        "../node_modules/oblique-ui/dist/images/favicon.ico",
        "../node_modules/oblique-ui/dist/images/logo.svg"
      ],
```

Can you elaborate how this was fixed in #1633?

**Comment by filipesilva** [comment]
@Dinistro the assets array does not yet support copying over files from other directories, that is being requested in https://github.com/angular/angular-cli/issues/3555.

If you need that functionality right now, I suggest you copy over the icon and logo onto `assets/` for now.

**Comment by Dinistro** [comment]
@filipesilva Thank you for the quick reply. I will take a look at the mentioned Issue.
