### ISSUE TITLE
 ERROR Exceeded maximum budget for scss files on upgrade to v0.901.9 of @angular-devkit/build-angular

### ISSUE THREAD

**Issue by MySolSo** [angular/angular-cli#18010]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
0.901.8

### Description

 A clear and concise description of the problem...

When using "ng build --prod" budget "anyComponentStyle" throws exception for scss files.

## 🔬 Minimal Reproduction

Upgrade "@angular-devkit/build-angular": "0.900.3", to
"@angular-devkit/build-angular": "0.901.9",

Then run ng build --prod

## 🔥 Exception or Error
<pre><code>

ERROR in Exceeded maximum budget for [filePath] Budget 10
kB was not met by 27.4 kB with a total of 37.4 kB.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.3
Node: 12.16.2
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.901.9
@angular-devkit/build-optimizer   0.901.9
@angular-devkit/build-webpack     0.901.9
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cdk                      8.2.3
@angular/cli                      9.0.3
@angular/material                 8.2.3
@ngtools/webpack                  9.1.9
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @MySolSo, what’s the actual size of that file compiled and minified?

Can you please provide a reproduction if it’s not the reported size?

Thanks.

**Comment by fkamming** [comment]
We're facing the same issue after @angular-devkit/build-angular was updated from 0.900.4 to 0.900.7. The error is reported for almost all our scss files. I verified the actual file sizes and they're all very small and well below 6kB.

Our work-around for now is removing anyComponentStyle budget from angular.json.

```
Angular CLI: 9.0.7
Node: 12.16.1
OS: linux x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.9
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.1.9
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2

```

**Comment by fkamming** [comment]
Might this be related to #17672?

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
