### ISSUE TITLE
ng build fails with cannot find module error

### ISSUE THREAD

**Issue by tgotthard** [angular/angular-cli#18022]
I wanted to build my angular project automatically on a different CentOS 7 machine.

Following Versions are used:
Angular CLI: 8.3.23
Node: 13.14.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.23
@angular-devkit/build-angular      0.803.25
@angular-devkit/build-ng-packagr   0.803.23
@angular-devkit/build-optimizer    0.803.25
@angular-devkit/build-webpack      0.803.25
@angular-devkit/core               8.3.23
@angular-devkit/schematics         8.3.23
@angular/cdk                       8.2.3
@angular/cli                       8.3.23
@angular/http                      7.2.16
@angular/material                  8.2.3
@ngtools/webpack                   8.3.25
@schematics/angular                8.3.23
@schematics/update                 0.803.23
rxjs                               6.5.5
typescript                         3.4.5
webpack                            4.39.2

Also Node version 12 doesn't change anything. 

The Build Errors:
chunk {main} main.js, main.js.map (main) 655 bytes [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 127 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 463 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 43.9 kB [initial] [rendered]
Date: 2020-06-25T10:35:22.517Z - Hash: 82d7bfce3451c02dfe5f - Time: 11782ms

ERROR in app/interfaces/ISharepoint.ts:5:22 - error TS2307: Cannot find module './IQuota'.

5 import {IQuota} from './IQuota';
app/interfaces/ISharepointUser.ts:4:22 - error TS2307: Cannot find module './IQuota'.

4 import {IQuota} from "./IQuota";
app/interfaces/isharepointnetwork.ts:3:22 - error TS2307: Cannot find module '../interfaces/IQuota'.

3 import {IQuota} from "../interfaces/IQuota";
app/sharepoints/InitializeSharepointProperties.ts:7:34 - error TS2307: Cannot find module '../interfaces/ISharepointNetwork'.

7 import {ISharepointNetwork} from '../interfaces/ISharepointNetwork';
app/sharepoints/sharepoints.component.ts:32:22 - error TS2307: Cannot find module '../interfaces/IQuota'.

32 import {IQuota} from '../interfaces/IQuota';

How can I fix this issue?

Thanks

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
