### ISSUE TITLE
ng update ... what is it doing?

### ISSUE THREAD

**Issue by bbarry** [angular/angular-cli#18029]
# 🚀 feature request

### Relevant Package

 I suppose this is a request for @angular/cli or maybe for certain upgrade schematics?

### Description
 

`ng update @angular/cli @angular/core --verbose=true`

Gets to "Installing packages..." and sits there for an hour. I can hear my computer clearly doing something but there are no indications to what it is doing other than "Installing packages..." 

### Describe the solution you'd like
 I would like to see the output of whatever npm command is running in its highest level of verbosity. 

### Describe alternatives you've considered
 Not using angular CLI.

I have really bad internet connectivity. `npm install` routinely fails and forces me to force clean my npm cache because it gets corrupt. I have `verdaccio` installed to help alleviate the issue some but I still get errors in my log and occasionally see errors running `npm install`. Several of my dependencies require me to have `ngcc` in a `postinstall` task. I suspect this is what it is doing most of the time when it is successfully installing packages but other times I am pretty certain it has failed in the download and I will need to restart and try again.

**Comment by alan-agius4** [comment]
@bbarry, can you try to remove the `ngcc` postinstall hook? `ng update` will download and install a a large number of npm packages, thus a bad internet connection might cause undefined behaviours.

**Comment by bbarry** [comment]
Yes, removing it for the update lets the update work when it works. I have to add it back when I am done and then run it because my tests fail. 

It doesn't fix the problem that I have no insight into what is happening when `installing packages` is on the screen. Sometimes I'll notice either timeout errors or connection reset errors in my verdaccio log but otherwise I have no idea if I have to take some action or not. 

Another reason it could be slow is that sometimes I trigger the corporate AV and PII scanners and it devolves to a slow path making additional network requests to my vpn with every file touched in my node_modules directory. When that happens the install generally succeeds but takes a frustrating amount of time (if I catch it early I can cancel the command, restart my computer and do it again and finish faster).

**Comment by alan-agius4** [comment]
Hi @bbarry, 

`installing packages` essentially is a silent version of `npm/yarn install`. I don't think that there is anything actionable from our end considering;

1. You have a poor internet connection
2. You have several scanners running on `node_modules` during each installations.

Feel free to comment again.

**Comment by bbarry** [comment]
I would just like it to not be silent when I specify an appropriate verbose flag. 

The flag right now seems almost completely useless.
