### ISSUE TITLE
tsconfig.base.json does not exist error when using ng update on a new project

### ISSUE THREAD

**Issue by BenRacicot** [angular/angular-cli#18027]
### Description and Replication

Run `ng new testing` to create an Angular 8.2.0 project
Run `ng update @angular/core @angular/cli` to update

### Output and error:

testing git:(master) ng update @angular/core @angular/cli
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cli @ "10.0.0" (was "8.2.2")...
    Updating package.json with dependency @angular/core @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1000.0" (was "0.802.2")...
    Updating package.json with dependency @angular/language-service @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/animations @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/compiler-cli @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/common @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency rxjs @ "6.5.5" (was "6.4.0")...
    Updating package.json with dependency zone.js @ "0.10.3" (was "0.9.1")...
    Updating package.json with dependency @angular/forms @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/router @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/compiler @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-browser @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency typescript @ "3.9.5" (was "3.5.3")...
UPDATE package.json (1293 bytes)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> core-js@3.6.4 postinstall /Users/bracicot/dev/testing/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> @angular/cli@10.0.0 postinstall /Users/bracicot/dev/testing/node_modules/@angular/cli
> node ./bin/postinstall/script.js

npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.0","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN codelyzer@5.2.2 requires a peer of @angular/compiler@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@5.2.2 requires a peer of @angular/core@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.5.4 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.

added 417 packages from 179 contributors, removed 54 packages, updated 134 packages, moved 6 packages and audited 1473 packages in 24.239s

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
    ** Executing migrations for package '@angular/core' **
    ** Executing migrations for package '@angular/cli' **

**ERROR! tsconfig.base.json does not exist..
The Schematic workflow failed. See above.**

**Comment by alan-agius4** [comment]
Hi @BenRacicot, 

I tried to reproduce this locally on new project with Angular CLI version  8. However, I wasn't able.

```
ng update @angular/core @angular/cli
Your global Angular CLI version (10.0.0-rc.0) is greater than your local
version (8.3.28). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 30 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cli @ "10.0.0" (was "8.3.28")...
    Updating package.json with dependency @angular/core @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1000.0" (was "0.803.28")...
    Updating package.json with dependency @angular/compiler @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/language-service @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/animations @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency rxjs @ "6.5.5" (was "6.4.0")...
    Updating package.json with dependency @angular/router @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/forms @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-browser @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency zone.js @ "0.10.3" (was "0.9.1")...
    Updating package.json with dependency @angular/common @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency @angular/compiler-cli @ "10.0.0" (was "8.2.14")...
    Updating package.json with dependency typescript @ "3.9.5" (was "3.5.3")...
UPDATE package.json (1295 bytes)
✔ Packages installed successfully.
** Executing migrations of package '@angular/cli' **

❯ Angular Workspace migration.
  Update an Angular CLI workspace to version 9.
UPDATE angular.json (3589 bytes)
UPDATE tsconfig.app.json (272 bytes)
UPDATE package.json (1297 bytes)
✔ Packages installed successfully.
  Migration completed.

❯ Lazy loading syntax migration.
  Update lazy loading syntax to use dynamic imports.
  Migration completed.

❯ Replace deprecated 'styleext' and 'spec' Angular schematic options.
  Migration completed.

❯ Update Browserslist configuration file name to '.browserslistrc' from deprecated 'browserslist'.
RENAME browserslist => .browserslistrc
  Migration completed.

❯ Update tslint to version 6 and adjust rules to maintain existing behavior.
UPDATE package.json (1296 bytes)
UPDATE tslint.json (3348 bytes)
  Migration completed.

❯ Remove deprecated 'es5BrowserSupport' browser builder option.
  The inclusion for ES5 polyfills will be determined from the browsers listed in the browserslist configuration.
  Migration completed.

❯ Replace deprecated and removed 'styleext' and 'spec' Angular schematic options with 'style' and 'skipTests', respectively.
  Migration completed.

❯ Remove deprecated options from 'angular.json' that are no longer present in v10.
  Migration completed.

❯ Add "Solution Style" TypeScript configuration file support.
  This improves developer experience using editors powered by TypeScript’s language server.
  Read more about this here: https://v10.angular.io/guide/migration-solution-style-tsconfig
RENAME tsconfig.json => tsconfig.base.json
CREATE tsconfig.json (427 bytes)
UPDATE tsconfig.app.json (277 bytes)
UPDATE tsconfig.spec.json (275 bytes)
UPDATE e2e/tsconfig.json (219 bytes)
  Migration completed.

❯ Add the tslint deprecation rule to tslint JSON configuration files.
  Migration completed.

❯ Update library projects to use tslib version 2 as a direct dependency.
  Read more about this here: https://v10.angular.io/guide/migration-update-libraries-tslib
  Migration completed.

❯ Update 'module' and 'target' TypeScript compiler options.
  Read more about this here: https://v10.angular.io/guide/migration-update-module-and-target-compiler-options
UPDATE e2e/tsconfig.json (222 bytes)
  Migration completed.

❯ Update workspace dependencies to match a new v10 project.
UPDATE package.json (1296 bytes)
✔ Packages installed successfully.
  Migration completed.

** Executing migrations of package '@angular/core' **

❯ Static flag migration.
  Removes the `static` flag from dynamic queries.
  As of Angular 9, the "static" flag defaults to false and is no longer required for your view and content queries.
  Read more about this here: https://v9.angular.io/guide/migration-dynamic-flag
  Migration completed.

❯ Renderer to Renderer2 migration.
  As of Angular 9, the Renderer class is no longer available.
  Renderer2 should be used instead.
  Read more about this here: https://v9.angular.io/guide/migration-renderer
  Migration completed.

❯ Undecorated classes with DI migration.
  As of Angular 9, it is no longer supported to use Angular DI on a class that does not have an Angular decorator.
  Read more about this here: https://v9.angular.io/guide/migration-undecorated-classes
  Migration completed.

❯ Missing @Injectable and incomplete provider definition migration.
  As of Angular 9, enforcement of @Injectable decorators for DI is a bit stricter and incomplete provider definitions behave differently.
  Read more about this here: https://v9.angular.io/guide/migration-injectable
  Migration completed.

❯ ModuleWithProviders migration.
  As of Angular 10, the ModuleWithProviders type requires a generic.
  This migration adds the generic where it is missing.
  Read more about this here: https://v10.angular.io/guide/migration-module-with-providers
  Migration completed.

❯ Undecorated classes with Angular features migration.
  In version 10, classes that use Angular features and do not have an Angular decorator are no longer supported.
  Read more about this here: https://v10.angular.io/guide/migration-undecorated-classes
  Migration completed.
```

At which point of the migration you are seeing the `ERROR! tsconfig.base.json does not exist..` error? Are you able to provide a reproduction?

**Comment by clydin** [comment]
When updating from the Angular CLI 8.2 or earlier, it is recommended to first update to the latest version of 8 first (`ng update @angular/core@8 @angular/cli@8`).
For additional details on the recommended update process, please see https://update.angular.io/#8.2:10.0

**Comment by BenRacicot** [comment]
Thank you @alan-agius4 and @clydin. I do see now that update.angular.io explains to update one major version at a time.

I believe the difference between your replay(s) above and my own is that my `ng new project`s version matched my globally installed Angular versions @angular/cli = 8.2.14. From there updating to v10 succeeds but the error is shown at the end of the process. 

Just thought I'd report.
