### ISSUE TITLE
Angular 10. Failed to parse SourceMap ... URL is not supported

### ISSUE THREAD

**Issue by alekcey0211** [angular/angular-cli#18024]
After update to angular 10. I got very much warnings about "Failed to parse SourceMap ... URL is not supported"

Example 
WARNING in .../node_modules/ngx-mask/fesm2015/ngx-mask.js
Module Warning (from .../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: "ng:/ngx-mask/lib/ngx-mask.module.ts" URL is not supported

How i can disable this warning or fix this problem.

**Comment by alan-agius4** [comment]
Hi @alexkpek,  Kindly follow the issue template and provide all the required information together with a minimal reproduction.

Thanks

**Comment by crh225** [comment]
FWIW I got this as well after upgrading to angular 10 using ng update @angular/core @angular/cli
