### ISSUE TITLE
Angular 10 update and compilation

### ISSUE THREAD

**Issue by hugoebarboza** [angular/angular-cli#18035]
Hi, 

Everything worked fine in angular 9, but today after angular update to 10 following this [guide](https://update.angular.io/#9.0:10.0l3), I get the below issue.

Please, I will appreciate any help.

1) I build with the command: npm run prod
"prod": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --aot --prod --buildOptimizer",

2) I test with the command: http-server dist/appname

3) Deploy app in the web browser (Chrome).

4)  I get the below error and I can´t see the main page.
Uncaught TypeError: J.Subject is not a constructor
    at Object.vWu4 (main-es2018.9d50cc8a848ad80b5f19.js:1)
    at n (runtime-es2018.00867754be924725b97e.js:1)
    at Module.zUnb (main-es2018.9d50cc8a848ad80b5f19.js:1)
    at n (runtime-es2018.00867754be924725b97e.js:1)
    at Object.1 (main-es2018.9d50cc8a848ad80b5f19.js:1)
    at n (runtime-es2018.00867754be924725b97e.js:1)
    at r (runtime-es2018.00867754be924725b97e.js:1)
    at Array.a [as push] (runtime-es2018.00867754be924725b97e.js:1)
    at main-es2018.9d50cc8a848ad80b5f19.js:1

5) Package
"dependencies": {
    "@agm/core": "^1.1.0",
    "@amcharts/amcharts4": "^4.9.27",
    "@angular-devkit/build-angular": "^0.1000.0",
    "@angular-devkit/schematics": "^10.0.0",
    "@angular/animations": "^10.0.0",
    "@angular/cdk": "^10.0.0",
    "@angular/common": "^10.0.0",
    "@angular/compiler": "^10.0.0",
    "@angular/core": "^10.0.0",
    "@angular/elements": "^10.0.0",
    "@angular/fire": "^6.0.2",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^10.0.0",
    "@angular/http": "^7.2.16",
    "@angular/localize": "^10.0.0",
    "@angular/material": "^10.0.0",
    "@angular/material-moment-adapter": "^10.0.0",
    "@angular/platform-browser": "^10.0.0",
    "@angular/platform-browser-dynamic": "^10.0.0",
    "@angular/platform-server": "^10.0.0",
    "@angular/router": "^10.0.0",
    "@angular/service-worker": "^10.0.0",
    "@firebase/firestore": "^1.15.4",
    "@firebase/messaging": "^0.6.18",
    "@ng-bootstrap/ng-bootstrap": "^6.1.0",
    "@ng-select/ng-select": "^4.0.1",
    "@ngneat/until-destroy": "^7.3.0",
    "@ngrx/store": "^9.2.0",
    "@ngrx/store-devtools": "^9.2.0",
    "@nguniversal/express-engine": "^10.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^8.2.6",
    "@ngx-loading-bar/core": "^5.0.0",
    "@ngx-progressbar/core": "^5.3.2",
    "@ngx-progressbar/http": "^5.3.2",
    "@ngx-progressbar/router": "^5.3.2",
    "@swimlane/ngx-charts": "^14.0.0",
    "agm-direction": "^0.8.0",
    "angular": "^1.8.0",
    "angular-calendar": "^0.28.16",
    "angular-split": "^3.0.3",
    "angular-vertical-timeline": "^0.6.0",
    "angularfire2": "^5.4.2",
    "bootstrap": "^4.5.0",
    "core-js": "^3.6.5",
    "date-fns": "^2.14.0",
    "express": "^4.17.1",
    "file-saver": "^2.0.2",
    "firebase": "^7.15.4",
    "html2canvas": "^1.0.0-rc.5",
    "jquery": "^3.5.1",
    "jspdf": "^1.5.3",
    "jspdf-autotable": "^3.5.6",
    "jspdf-customfonts": "0.0.4",
    "mat-progress-buttons": "^9.1.1",
    "material-design-icons": "^3.0.1",
    "material-design-lite": "^1.3.0",
    "moment": "^2.27.0",
    "moment-timezone": "^0.5.31",
    "ng-pick-datetime": "^7.0.0",
    "ng2-search-filter": "^0.5.1",
    "ng5-slider": "^1.2.4",
    "ngx-cacheable": "^1.4.2",
    "ngx-captcha": "^8.0.1",
    "ngx-loadable": "^2.1.1",
    "ngx-markdown": "^9.1.1",
    "ngx-mat-select-search": "^3.0.0",
    "ngx-quicklink": "^0.2.3",
    "ngx-socket-io": "^3.0.1",
    "ngx-toastr": "^12.1.0",
    "normalize.css": "^8.0.1",
    "npm-check-updates": "^7.0.1",
    "path": "^0.12.7",
    "popper.js": "^1.16.1",
    "primeicons": "^4.0.0",
    "primeng": "^9.1.0",
    "rxjs": "^6.5.5",
    "rxjs-compat": "^6.5.5",
    "selenium-webdriver": "^4.0.0-alpha.7",
    "sweetalert2": "^9.15.2",
    "tslib": "^2.0.0",
    "typescript": "^3.9.5",
    "webpack-dev-server": "^3.11.0",
    "webpack-sources": "^1.4.3",
    "xlsx": "^0.16.2",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.1000.0",
    "@angular/cli": "^10.0.0",
    "@angular/compiler-cli": "^10.0.0",
    "@angular/language-service": "^10.0.0",
    "@nguniversal/builders": "^10.0.0",
    "@types/express": "^4.17.6",
    "@types/googlemaps": "^3.39.8",
    "@types/jasmine": "^3.5.11",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^14.0.14",
    "codelyzer": "^5.2.2",
    "cross-env": "^7.0.2",
    "enhanced-resolve": "^4.2.0",
    "firebase-tools": "^8.4.3",
    "first-input-delay": "^0.1.3",
    "fuzzy": "^0.1.3",
    "increase-memory-limit": "^1.0.7",
    "inquirer": "^7.2.0",
    "inquirer-autocomplete-prompt": "^1.0.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.2",
    "karma": "^5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "~3.3.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "ngx-daterangepicker-material": "^3.0.1",
    "protractor": "^7.0.0",
    "source-map-explorer": "^2.4.2",
    "ts-node": "^8.10.2",
    "tslint": "~6.1.2",
    "webpack-bundle-analyzer": "^3.8.0"
  },
  "engines": {
    "node": "10.13.0",
    "npm": "6.10.2"
  },
  "bit": {
    "env": {
      "compiler": "bit.envs/angular@0.1.9"
    },
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm"
  }

Sincerely,
Hugo

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by hugoebarboza** [comment]
> optimization

@qstarin thanks very much for your help, it works.

@alan-agius4 how you expect to provide more information if I don't know what is the issue, I just had updated to angular 10 and the issue appears.

**Comment by alan-agius4** [comment]
@hugoebarboza, by following and not deleting the issue template and trying to reproduce it in a new fresh `ng new` project?

Nb: Disable optimization is not a solution and shouldn’t be done, as you will opt-out of all sort of optimizations such as dead code elimination, tree-shaking and minification.

**Comment by hugoebarboza** [comment]
Hi,

@alan-agius4 I understand that disable optimization is not the best practice and solution, but what else I can do to solve it ? I have not found any information about the issue on the net.

Also, everything worked fine in angular 9, but after angular 10 updates, I get the above issue.

Sincerely,
Hugo

**Comment by qstarin** [comment]
@hugoebarboza @alan-agius4 I've created a repro and filed a bug report here: https://github.com/angular/angular-cli/issues/18045

My apologies, I just realized I maybe should have filed it under @angular/angular

**Comment by hugoebarboza** [comment]
> @hugoebarboza @alan-agius4 I've created a repro and filed a bug report here: #18045
> 
> My apologies, I just realized I maybe should have filed it under @angular/angular

Hi @qstarin @alan-agius4 thanks for your help, by the way, sorry for my English, I do my best. Please If I don´t explain something well let me know.

About the issue, I build my apps with the following command.

[+] command: npm start
1) "start": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng serve"
2) I see the app in the browser.
3) Everything worked fine.


[+] command: npm run prod
1) "prod": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --aot --prod --buildOptimizer"
2) I don´t see the app in the browser, and I see the following issue in chrome console.

Uncaught TypeError: J.Subject is not a constructor
at Object.vWu4 (main-es2018.9d50cc8a848ad80b5f19.js:1)
at n (runtime-es2018.00867754be924725b97e.js:1)
at Module.zUnb (main-es2018.9d50cc8a848ad80b5f19.js:1)
at n (runtime-es2018.00867754be924725b97e.js:1)
at Object.1 (main-es2018.9d50cc8a848ad80b5f19.js:1)
at n (runtime-es2018.00867754be924725b97e.js:1)
at r (runtime-es2018.00867754be924725b97e.js:1)
at Array.a [as push] (runtime-es2018.00867754be924725b97e.js:1)
at main-es2018.9d50cc8a848ad80b5f19.js:1


[+] command: npm run prod
1) Disable buildOptimizer ("optimization": false in angular.json) 
2) "prod": "node --max-old-space-size=12192 ./node_modules/@angular/cli/bin/ng build --aot --prod"
3) that works - I see the app in the browser.


Best regards,
Hugo

**Comment by florianjung** [comment]
@hugoebarboza I experienced the very same error. After removing "rxjs-compat" from package.json, for me the error was gone. But before removing "rxjs-compat" you have to ensure that you use rxjs the version 6 way, which in turn allows for removing the compat-package.

I am sorry that I don't have the time to trim this down to a minimal project. At least you can try it out and give feedback. This might give others an idea where to search for. At least you don't have to disable build optimizations.

**Comment by hugoebarboza** [comment]
> @hugoebarboza I experienced the very same error. After removing "rxjs-compat" from package.json, for me the error was gone. But before removing "rxjs-compat" you have to ensure that you use rxjs the version 6 way, which in turn allows for removing the compat-package.
> 
> I am sorry that I don't have the time to trim this down to a minimal project. At least you can try it out and give feedback. This might give others an idea where to search for. At least you don't have to disable build optimizations.

Hi @florianjung thanks for your help and your time.

I have "rxjs-compat": "^6.5.5". What rxjs-compat versions works ?

Sincerely,
Hugo Barboza

**Comment by qstarin** [comment]
> I have "rxjs-compat": "^6.5.5". What rxjs-compat versions works ?

@hugoebarboza None do. 

The issue I created and linked above clearly reproduces the problem with `rxjs-compat` so hopefully someone capable of rooting out the cause will pick it up.

**Comment by hugoebarboza** [comment]
Hi @qstarin, thank you for your help, hope you are doing well.

From case notes, I understand that right now there is no solution for my issue and we should wait for someone from angular team to solve it, am I correct ?

Sincerely,
Hugo Barboza

**Comment by florianjung** [comment]
@hugoebarboza If your application relies on rxjs-compat then you have to wait for a resolution or workaround. In my case I had to migrate about 160 files (mainly import declarations) so that I can remove the compat-package. This would be a valid solution and from a long-term maintenance perspective, maybe not the worst one.

**Comment by hugoebarboza** [comment]
Hi @florianjung thanks for your help, hope you are doing well. In my case, my application relies on rxjs-compact.

Today I see the below warning in many libraries, no just rxjs-compact. From your experience, they are issues or they might be a future problem ?

For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
WARNING in /tmp/build_66bdd62db65cfed95e5a83d42d0ee4c4/node_modules/rxjs/ReplaySubject.js depends on rxjs-compat/ReplaySubject. CommonJS or AMD dependencies can cause optimization bailouts.


Best regards,
Hugo Barboza

**Comment by kwhjvdkamp** [comment]
I do face the very same error
1) Development environment works fine!
2) Firebase server (and obviously also Firebase deploy) 2x => **TypeError: gI.BehaviorSubject is not a constructor** 
It appears directly after upgrading to version 10 (version works fine!)
3) Removed 'rxjs-compact' from package.json => NO SUCCESS even after building (ng build --prod --aot), optimization true & fase
4) Finally, checked Google's console in what file this annoying error elevates => it turned out it elavated on a method I used to check if the token (Firebase exist!) and logging out if a user hits F5
5) Commenting-out this specific method still firebase would NOT do 'Firebase serve' (even after rebuilding ng build --prod --aot)
6) ...then surprisingly my eye catched the 'number' of 'main-es5.xxxxrepxxxxx' did NOT match with the one in the ~\dist\<my-folder>\ 
7) ...cleared the cache on google's console => IT's WORKING! Another thing to keep an eye on!

**Comment by hugoebarboza** [comment]
Hi @kwhjvdkamp, please check #[18045 ](https://github.com/angular/angular-cli/issues/18045)

I solved doing this: "You'll have to switch any places using old-style RxJs imports and chained functions to use new-style imports and functions passed to the .pipe etc. and stop using rxjs-compat".

Firebase example: 
Issue: this.filesCollection.snapshotChanges().map() 

Resolution: this.filesCollection.snapshotChanges().pipe(map())

Have a great day !!!
Hugo

**Comment by brendanalexdr** [comment]
Refactored my ng app to comply with all rxjs-no-compat rules and this problem was solved for me.  thanks @kwhjvdkamp
