### ISSUE TITLE
ExperimentalWarning when running ng serve

### ISSUE THREAD

**Issue by crfrolik** [angular/angular-cli#18033]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v9.1.11

### Description

```
(node:29064) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
```

It is just a warning and not an error, but the fact that it shows up in red scares me every time I see it.

## 🔬 Minimal Reproduction

```
ng new angular-test
cd angular-test
ng serve
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.0
Node: 13.9.0
OS: win32 x64

Angular: 10.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi, this is related to this Node.js issue: https://github.com/nodejs/modules/issues/485

To remove this warning please downgrade to Node 12, or upgrade to Node 14. 

Node 13 is not supported by the Angular CLI as it is it past it’s life time. See: https://nodejs.org/en/about/releases
