### ISSUE TITLE
I have read hmr docs but it only explain about ng server not for build 

### ISSUE THREAD

**Issue by tahir-jamil** [angular/angular-cli#18047]
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/configure-hmr.md
How can i build my angular project with production + hmr.
Right now its just fails when i refresh the page in build project 
![Screenshot 2020-06-27 at 9 49 46 AM](https://user-images.githubusercontent.com/40952630/85914861-b49dda00-b85b-11ea-81a7-08ea87f2a4bc.png)

saleOrder.routes
```
import { Routes } from '@angular/router';
import { SaleOrderComponent } from './sale-order.component';
import { OrderAdjustmentTypeResolverService } from '@tu/order/orderAdjustmentType-resolver.service';
import { OrderRoleTypeResolver, OrderStatusTypeResolver } from '@tu/order/order-resolver.service';
import { SaleTypeResolver } from './services';
import { PaymentTypeResolver } from '@tu/payment/services/payment-resolver.service';
import { LoggedInPartyResolver, ContactMechanismTypeResolver, PartyRoleTypeResolver,
  PartyRelationshipTypeResolver } from '@tu/party/services';
import { InvoiceResolver } from '@tu/invoice/services';

const orderResolves = {
  orderAdjustmentTypes: OrderAdjustmentTypeResolverService,
  orderRoleTypes: OrderRoleTypeResolver,
  orderStatusTypes: OrderStatusTypeResolver,
  saleTypes: SaleTypeResolver,
  invoiceItemTypes: InvoiceResolver,
  paymentTypes: PaymentTypeResolver,
  contactMechanismTypes: ContactMechanismTypeResolver,
  partyRoleTypes: PartyRoleTypeResolver,
  partyRelationshipTypes: PartyRelationshipTypeResolver,
  loggedInParty: LoggedInPartyResolver,
}

export const routes: Routes = [

  { path: '', component: SaleOrderComponent, resolve: orderResolves },
];

```
Please guide me.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
