### ISSUE TITLE
Multiple Entrypoints, Main Files

### ISSUE THREAD

**Issue by sqwk** [angular/angular-cli#1804]
In `angular-cli.json` there is an `apps` entry. Does this mean that the cli supports multiple entry points like so?

    "apps": [
        {
            "main": "src/main.ts",
            "tsconfig": "src/tsconfig.json",
            "mobile": false
        },
        {
            "main": "src/secondary.ts",
            "tsconfig": "src/tsconfig.json",
            "mobile": false
        }
    ]

This would be incredibly useful for (electron/nwjs) apps that live in seperate windows and communicate via ipc or localstorage events.

**Comment by filipesilva** [comment]
We plan on supporting multiple apps, but we do not at the moment.

**Comment by sqwk** [comment]
Is there a way to achieve this another way at the moment?

**Comment by filipesilva** [comment]
No, unfortunately there is not. We have `apps[0]` hardcoded on purpose until we properly design the multi-app functionality. That's a post 1.0 release thing though.

**Comment by sqwk** [comment]
Can we reopen this for post 1.0?

**Comment by ovidius72** [comment]
Subscribed since I'm also  interested in this feature.

**Comment by leocaseiro** [comment]
Check https://github.com/angular/angular-cli/pull/5737
