### ISSUE TITLE
Upgrade from 9.17 to 10 is failed

### ISSUE THREAD

**Issue by callmeblessed** [angular/angular-cli#18051]
Hi

I tried to upgrade my current project from 9.1.7 to 10 (latest) but it failed when I tried to run  
`ng update @angular/cli @angular/core `

the errror was unclear to me
```
Your global Angular CLI version (10.0.0) is greater than your local
version (9.1.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Unknown error: Error: No valid exports main found for 'D:\WinTemp\angular-cli-packages-iP1Jzb\node_modules\@angular\cli\node_modules\uuid'
```

Could you tell me what I should do ?
I have trying to install angular cli 10  globaly as well.

I delete node_modules, npm install again and then ng update .. but it still produce unknown error

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by callmeblessed** [comment]
Your global Angular CLI version (10.0.0) is greater than your local
version (9.1.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 9.1.7
Node: 13.6.0
OS: win32 x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.42.0

**Comment by alan-agius4** [comment]
@callmeblessed, can you try using a supported Node.js version 12 or 14?

Node.js 13 is past it’s life time and is no longer supported by the Angular or the NodeJs team
See: https://nodejs.org/en/about/releases

**Comment by callmeblessed** [comment]
ah yes it work not. I just update my node to 14.4 and it works . thank you.
