### ISSUE TITLE
LazyLoading - Common.js have all shared modules compiled

### ISSUE THREAD

**Issue by Spawnrad** [angular/angular-cli#18066]
# 🐞 bug report

### Affected Package
Angular 8.2.14
Angular 9

### Is this a regression?
I didn't checked on other versions.

### Description
When i have multiple lazy loading (deep lazyloading), all shared module is compiled at the first lazy loading page (first lazy loading with shared module ). They are 'compiled shared module' that i don't use and didn't declare in that page. This thing occurs for all imports module that is use in multiple lazy module. ( For example in my project : effects, shared module...)

All is compiled in the file common.js or common-es2015... in production.

## 🔬 Minimal Reproduction

Go to the Auth Page with the debug mode to see the file common.js

https://github.com/Spawnrad/Angular-CommonJs

## 🔥 Exception or Error
common.js have all compiled shared module ( all modules shared in multiple "lazymodules" ) at the first lazyloading page show.

https://imgur.com/A8FAKDb.png

## 🌍  Your Environment

**Angular Version:**
Github reproduction : 9.0.0-rc.7
My Project on stage: 9.1.11
My Project on Production: 8.2.14

</code></pre>

**Anything else relevant?**
I figured out that when the sharedModule is declare on the parent module it's not compiled.
In my repository example you can see that SharedToNotShareModule is not in the compiled file.

**Comment by Spawnrad** [comment]
@petebacondarwin Hi, Thank you for your answer.

I did a reproduction repository : https://github.com/Spawnrad/Angular-CommonJs

Those pages are lazy loaded (and with canLoad)
Login
Dashboard

And in the Dashboard Module, I have 2 other lazy loading module :
Admin
Customer

When i import share modules on Login and this share modules is imported too on Customer module.
All modules imported on Customer module is compiled ( even though is not declare on Login Module )

In the repository, you can see that when you navigate to Login Page.
In common.js i have modules that is imported in Login module + all other module that is declare on Customer.
Just because i have one module who is shared to Login and Customer module, all other module declare on Customer is compiled too.

If you need more information let me know. Thanks a lot.

**Comment by Spawnrad** [comment]
more information for :  "+ all other module that is declare on Admin"

All other modules shared with Customer Module.

For example when i go to Auth Page we have SharedLayoutModule imported on AdminModule and AuthModule
but SharedUserModule is compiled in this file and is not in Auth Module. 
SharedUserModule is in AdminModule and CustomerModule.

I simplified the github repo.

**Comment by alan-agius4** [comment]
Hi @Spawnrad, thanks for the reproduction. Unfortunately, it's still not clear to me what is the current vs expected behaviour.

**Comment by Spawnrad** [comment]
Hi @alan-agius4 

Thank you very for your answer.

Currently in the example you can see that SharedUserModule is compiled when i go to the Auth Page but it's not in the import of the AuthModule.

**Comment by alan-agius4** [comment]
Hi @Spawnrad,  I think what you are looking for in your case is to disable `commonChunk`.

**Comment by Spawnrad** [comment]
Thank you @alan-agius4 i learned a new thing by you <3
