### ISSUE TITLE
Better control over sourcemap generation for test

### ISSUE THREAD

**Issue by StefanKern** [angular/angular-cli#18060]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [X] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [x] doc

### Description
Currently the karama schema definition allows the following options for generating souremaps. 
```
export declare type SourceMapUnion = boolean | SourceMapClass;
export interface SourceMapClass {
    /**
     * Output sourcemaps for all scripts.
     */
    scripts?: boolean;
    /**
     * Output sourcemaps for all styles.
     */
    styles?: boolean;
    /**
     * Resolve vendor packages sourcemaps.
     */
    vendor?: boolean;
}
```
however the option for vendor is highly misleading, because setting it to true, actually disables the sourcemaps for all unit tests, See screenshot:
![grafik](https://user-images.githubusercontent.com/2032760/86006078-c1fec400-ba15-11ea-9ac0-22992e6b5be0.png)

Since we have a very large application, where the unminified test files are very, very large, this slows down the testing significantly. (the vendor.js has a total of 36MB in its unminified state, 15 without sourcemaps).

### Describe the solution you'd like
A more fine granular solution to control the souremap generation for unit tests would be helpful. I suggest defining  them like this: 
```
export declare type SourceMapUnion = boolean | SourceMapClass;
export interface SourceMapClass {
    /**
     * Output sourcemaps for all scripts.
     */
    scripts?: boolean;
    /**
     * Output sourcemaps for all styles.
     */
    styles?: boolean;
    /**
     * Resolve vendor packages sourcemaps.
     */
    vendor?: boolean;
    /**
     * Resolve application sourcemaps (main.js and all lazyloaded modules).
     */
    application?: boolean;
    /**
     * Resolve test file sourcemaps.
     */
    test?: boolean;
}
```

### Describe alternatives you've considered
I tried modifying the karma.config.js and tsconfig.spec.ts to control the sourcemap generation, but to no avail

**Comment by alan-agius4** [comment]
Hi @StefanKern, 

It's un-clear from the reporting issue what are the values of the other options when you are setting `vendor: true`.

Vendor soucemaps indeed takes a lot of time and resources to process and that is one reason why that they are on opt-in bases and mainly is intended to be used for debugging purposes and not during normal development workflow.

The proposed new options seems to overlap with the current default behaviour. That when using `ng build` or `ng serve` you will get the sourcemaps of the application bundles, and when running `ng test` you will get the sourcemaps of the testing bundles.

**Comment by StefanKern** [comment]
Hi @alan-agius4 ,

thank you for your fast replay. I based my example on a freshly created angular 10 application. The only value I changed was setting `"sourceMap": { "vendor": false }`. This had the effect that no sourcemaps where generated for vendor, main and the tests.

> Vendor soucemaps indeed takes a lot of time and resources to process and that is one reason why that they are on opt-in bases and mainly is intended to be used for debugging purposes and not during normal development workflow.
So you mean that vendor sourcemaps are not generated for library projects during normal builds? Because I don't think that is the case, because as I was debugging the unit tests, the debugger showed me the actuall Typescript lines for my tests and application. In the vendor.js file I also found the following references to souremaps:
![grafik](https://user-images.githubusercontent.com/2032760/86014540-c1b7f600-ba20-11ea-8fe1-6695fb4816b6.png)
 
So the browser even has to load the full sourcemap, because it is inlined in the vendor.js, which is already 8.9 MB in a fresh hello world project:
![grafik](https://user-images.githubusercontent.com/2032760/86014807-152a4400-ba21-11ea-9ae1-2e5f22cfb549.png)

Thanks for your help, maybe I just got something wrong :)

**Comment by alan-agius4** [comment]
By setting `"sourceMap": { "vendor": false }`, you are disabling all form of sourcemaps, because by default value for `scripts` and `styles` is false.

To enable sourcemaps you can use one of the below:

Enables local JS and CSS sourcemaps
```json
"sourceMap": true
```
or 
```json
"sourceMap": {
  "scripts": true,
  "styles": true
},
```

The below enables local and vendor sourcemaps for JS and CSS.
```json
"sourceMap": {
  "scripts": true,
  "styles": true,
 "vendor" true,
},
```

**Comment by StefanKern** [comment]
Yes, but sadtly no combination solves my issue. I want to disable the sorucemaps for the huge vendor.js but enable them for my test and application code.
Setting `"sourceMap": { "scripts": true, "styles": true,"vendor": false }` had quite a strange effect, because then the souremaps for vendor.js, the application and the tests where generated too. I would have expected that just the script.js has souremaps then
![grafik](https://user-images.githubusercontent.com/2032760/86017806-c7afd600-ba24-11ea-9436-06070b30aec1.png)

However this, nor any other combination I tried out solved my issue that I don't want the sourcemaps for the applicaiton and test but not the vendor.js. Also the inlined souremaps doesn't look good, because you have trouble opening the file in the network tab.

**Comment by alan-agius4** [comment]
I think I see what is the problem. The vendor sourcemap is still being generated, but in fact this is not that that useful because it's doesn't contain all the information from all the `node_modules`.

In the screenshot above I see 2 requests for the `vendor.js` files (see: #16160) and non for the sourcemaps and I am also see that the application and tests code have been properly mapped back to the sourcemaps.

**Comment by StefanKern** [comment]
@alan-agius4 thanks for taking a look at it, I already see there are some commits to it.

**Comment by alan-agius4** [comment]
@StefanKern, yeah, since this can potentially be a breaking change since the `vendor.js.map` will not longer be generated. We have decided that this should go in the next major which will be v11.
