### ISSUE TITLE
Not Installing 

### ISSUE THREAD

**Issue by sureshdevaramani** [angular/angular-cli#18079]
CREATE my-app1/angular.json (3574 bytes)
CREATE my-app1/package.json (1283 bytes)
CREATE my-app1/README.md (1023 bytes)
CREATE my-app1/tsconfig.json (489 bytes)
CREATE my-app1/tslint.json (3125 bytes)
CREATE my-app1/.editorconfig (274 bytes)
CREATE my-app1/.gitignore (631 bytes)
CREATE my-app1/browserslist (429 bytes)
CREATE my-app1/karma.conf.js (1019 bytes)
CREATE my-app1/tsconfig.app.json (210 bytes)
CREATE my-app1/tsconfig.spec.json (270 bytes)
CREATE my-app1/src/favicon.ico (948 bytes)
CREATE my-app1/src/index.html (292 bytes)
CREATE my-app1/src/main.ts (372 bytes)
CREATE my-app1/src/polyfills.ts (2835 bytes)
CREATE my-app1/src/styles.css (80 bytes)
CREATE my-app1/src/test.ts (753 bytes)
CREATE my-app1/src/assets/.gitkeep (0 bytes)
CREATE my-app1/src/environments/environment.prod.ts (51 bytes)
CREATE my-app1/src/environments/environment.ts (662 bytes)
CREATE my-app1/src/app/app-routing.module.ts (246 bytes)
CREATE my-app1/src/app/app.module.ts (393 bytes)
CREATE my-app1/src/app/app.component.html (25757 bytes)
CREATE my-app1/src/app/app.component.spec.ts (1062 bytes)
CREATE my-app1/src/app/app.component.ts (211 bytes)
CREATE my-app1/src/app/app.component.css (0 bytes)
CREATE my-app1/e2e/protractor.conf.js (808 bytes)
CREATE my-app1/e2e/tsconfig.json (214 bytes)
CREATE my-app1/e2e/src/app.e2e-spec.ts (640 bytes)
CREATE my-app1/e2e/src/app.po.ts (301 bytes)
- Installing packages...

i waited for hours but did not get installed. What might be the problem?

**Comment by alan-agius4** [comment]
This might be several reasons why it's being stuck at `install packages...`, Poor internet connection, virus scanner scanning` `node_modules`, corrupted package manager cache, etc..

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
