### ISSUE TITLE
angular cli 8.0.3 , nodejs 12.16.1

### ISSUE THREAD

**Issue by ramimohammad** [angular/angular-cli#18078]
[Container] 2020/06/30 08:33:42 Command did not exit successfully node --max-old-space-size=4096 node_modules/@angular/cli/bin/ng build --prod exit status 1
--
270 | [Container] 2020/06/30 08:33:42 Phase complete: BUILD State: FAILED
271 | [Container] 2020/06/30 08:33:42 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: node --max-old-space-size=4096 node_modules/@angular/cli/bin/ng build --prod. Reason: exit status 1

**Comment by ramimohammad** [comment]
package.json

{
  "name": "ureed-angular",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.0.2",
    "@angular/cdk": "^8.0.1",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/material": "^8.0.1",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/pwa": "^0.901.6",
    "@angular/router": "~8.0.0",
    "@angular/service-worker": "~8.0.0",
    "@auth0/angular-jwt": "^2.1.0",
    "@fortawesome/angular-fontawesome": "^0.5.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@ng-bootstrap/ng-bootstrap": "5.3.0",
    "@ngx-progressbar/core": "^5.3.2",
    "@ngx-share/button": "^7.1.2",
    "@ngx-share/buttons": "^7.1.2",
    "@ngx-share/core": "^7.1.2",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/intro.js": "^2.4.4",
    "@types/swiper": "^4.4.5",
    "angular-bootstrap-md": "8.10.1",
    "angular-svg-round-progressbar": "^3.0.1",
    "angular2-websocket": "^0.9.8",
    "bootstrap": "^4.5.0",
    "chart.js": "^2.9.3",
    "crypto-js": "^3.1.9-1",
    "flag-icon-css": "^3.4.6",
    "hammerjs": "^2.0.8",
    "intro.js": "^2.9.3",
    "jquery": "^3.4.1",
    "libphonenumber-js": "^1.7.47",
    "localize-router": "^2.0.0-RC.3",
    "localize-router-http-loader": "^1.0.2",
    "lodash": "^4.17.15",
    "lottie-web": "^5.6.10",
    "mat-video": "^2.7.2",
    "moment": "^2.24.0",
    "ng-circle-progress": "^1.5.1",
    "ng-intercom": "^8.0.2",
    "ng-lazyload-image": "^7.0.1",
    "ng2-file-upload": "^1.3.0",
    "ng2-page-scroll": "^4.0.0-beta.12",
    "ng2-trim-directive": "^2.3.3",
    "ngx-bootstrap": "^5.1.0",
    "ngx-build-plus": "^9.0.4",
    "ngx-clipboard": "^12.3.1",
    "ngx-lottie": "^6.1.1",
    "ngx-moment": "^3.4.0",
    "ngx-owl-carousel": "^2.0.7",
    "ngx-swiper-wrapper": "^8.0.2",
    "ngx-useful-swiper": "^8.0.1",
    "postcss-import": "^12.0.1",
    "primeflex": "^1.1.1",
    "primeicons": "^4.0.0-rc.2",
    "primeng": "^8.0.0",
    "quill": "^1.3.7",
    "rxjs": "~6.4.0",
    "swiper": "^5.0.3",
    "tailwindcss": "^1.4.6",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/cli": "~8.0.2",
    "@angular/compiler-cli": "~8.0.0",
    "@angular/language-service": "~8.0.0",
    "@types/chart.js": "^2.9.18",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }
}

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
