### ISSUE TITLE
Skeleton app is broken during testing

### ISSUE THREAD

**Issue by bampakoa** [angular/angular-cli#18071]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not applicable

### Description

When I run `ng test` in a newly created Angular application, the `title` binding and the **Terminal** commands are not displayed. However, tests are passing. 

## 🔬 Minimal Reproduction

- `ng new my-app`
- Do not enable routing
- Select CSS styles
- `ng test`

## 🔥 Exception or Error
<pre><code>

</code></pre>
![image](https://user-images.githubusercontent.com/7170892/86061091-c0151f00-ba6e-11ea-827b-33f27be6cc83.png)

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.0
Node: 12.18.0
OS: win32 x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
After refreshing the browser a couple of times, they are finally appear on the screen.

**Comment by alan-agius4** [comment]
@bampakoa, which browser and it's version are you using? I tried this a couple of times locally and I cannot replicate this behaviour.

**Comment by bampakoa** [comment]
@alan-agius4 Google Chrome  83.0.4103.116 (64-bit) and Windows 10 as OS. I have also tried it multiple times, even with a fresh new Angular CLI project, and I get the same behavior.

**Comment by bampakoa** [comment]
@alan-agius4 thanks very much for the explanation. I find it a bit confusing especially for a newcomer in Angular because it may be tempting to think that something is wrong. 
Would you consider adding the `detectChanges` method in the `beforeEach` statement? I remember that it was there in older versions of the Angular CLI. Bear in mind also that according to the testing guide in angular.io, calling `detectChanges` method is not harm if called multiple times. 🙂

**Comment by alan-agius4** [comment]
@bampakoa, adding detect changes here is not harmful but redundant for those particular tests since we are not testing the template. So adding it doesn’t add any value and might confuse new comers on why is it needed in the first place.

In the browser spawned by karma, you will always see the view of the component of the last test. You will actually never see he entire application as per the scaffolded project. This is because for the scaffolded projects all contents of the app are in 1 large view. This is to make it easier for users to remove the default layout and styling of the `ng new app`.

**Comment by bampakoa** [comment]
Sure @alan-agius4 Thanks for the insights 👌
