### ISSUE TITLE
Error with AOT compilation and filereplacement

### ISSUE THREAD

**Issue by soyjuanmedina** [angular/angular-cli#18085]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 I don't know, I have this problem after some changes, but I did I lot and don't know exactly when stars

(by the way, I have open other similar issue in STOF 

https://stackoverflow.com/questions/62590862/differences-between-angular-compilations

### Description

 AOT compilation do a lot of checks I don't know if are mandatory but made imposible to reduce the size of the app

## 🔬 Minimal Reproduction

In `angular.json` I hava a filereplacemente

```
{
  "replace": "src/app/pages/bookappointments/bookappointments.page.ts",
  "with": "src/app/customizations/database/bookappointments.page-database.ts"
},
```
but when try to compile with aot have this error:

## 🔥 Exception or Error
<pre><code>`ERROR in : Couldn't resolve resource ./bookappointments.page.scss relative to D:/desarrollos/PatientPortal/front/src/app/customizations/database/bookappointments.page-database.ts`

</code></pre>
And it's true, relative to this file I don't have the bookappointments.page.scss, but I have relative to the one wich replace, src/app/pages/bookappointments/bookappointments.page.ts

## 🌍 Your Environment

"@angular/cli": "^8.0.1",

**Anything else relevant?**

I want to understand it well because I preffer to use it to compile, but with this errors I can't, and in this case I think my code is ok and I don't want to duplicate it.

I ask too this in STOF

https://stackoverflow.com/questions/62636616/aot-compilation-and-filereplacement

but I really thing is a bug. Sorry if not

**Comment by alan-agius4** [comment]
This is expected and working as intended.

When using `fileReplacements` only the contents of the file is replaced. Think of it as a copy and paste.

To get around this, you need to update the `templateUrl` and `styleUrl‘ to be relative from `bookappointments.page.ts`. In general, I wouldn’t recommend in replacing a component file. This functionality is mainly intended to replace configuration files.
