### ISSUE TITLE
Wrong html lang with ng serve

### ISSUE THREAD

**Issue by TinyMan** [angular/angular-cli#18094]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

no

### Description

 A clear and concise description of the problem...
When using `ng serve`, the html `lang` attribute is not set to the correct locale.

## 🔬 Minimal Reproduction

https://github.com/TinyMan/serve-wrong-locale-id

`ng serve -c fr`
We can see in browser that the html starts with : 
```html
<!doctype html>
<html lang="en">
```
## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.0
Node: 12.18.1
OS: win32 x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@angular/cli                      10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

**Comment by r-shakeri** [comment]
is there any future plan to fix this issue?

**Comment by pburkindine** [comment]
Upvote, we have css selectors based on the lang attribute so this is an important regression for us, we are working around it with an app initializer
