### ISSUE TITLE
ng route gives compile error

### ISSUE THREAD

**Issue by JasonGoemaat** [angular/angular-cli#181]
I tried `ng generate route Login` and got this log:

    C:\git\test\AngularCLI\Angular2Facebook>ng generate route Login
    version: 1.13.13
    installing route
      create app\routes\login.js
      create app\templates\login.hbs
    ENOENT: no such file or directory, open 'C:\git\test\AngularCLI\Angular2Facebook\app\router.js'
    Error: ENOENT: no such file or directory, open 'C:\git\test\AngularCLI\Angular2Facebook\app\router.js'

**Comment by jkuri** [comment]
You are not using master, npm package is outdated and we hope it will be republished soon. 
Please see readme how to use the master.

**Comment by deepakgd** [comment]
same issue here. If i use master, while ng server following error occurs
Build error

[DiffingTSCompiler]: Typescript found the following errors:
  /home/dinesh/new-angular-cli-generator/foo/src/typings.d.ts (1, 1): File '/home/dinesh/new-angular-cli-generator/foo/typings/browser.d.ts' not found.
  app/foo.spec.ts (8, 32): Property 'toBe' does not exist on type 'NgMatchers'.
  app/foo.spec.ts (13, 35): Property 'toBe' does not exist on type 'NgMatchers'.
  app/foo.spec.ts (14, 37): Property 'toBe' does not exist on type 'NgMatchers'.
  node_modules/angular2/src/core/change_detection/parser/locals.d.ts (3, 14): Cannot find name 'Map'.
  node_modules/angular2/src/core/change_detection/parser/locals.d.ts (4, 42): Cannot find name 'Map'.
  node_modules/angular2/src/core/debug/debug_node.d.ts (14, 13): Cannot find name 'Map'.
  node_modules/angular2/src/core/debug/debug_node.d.ts (24, 17): Cannot find name 'Map'.
  node_modules/angular2/src/core/debug/debug_node.d.ts (25, 17): Cannot find name 'Map'.
  node_modules/angular2/src/core/di/provider.d.ts (436, 103): Cannot find name 'Map'.
  node_modules/angular2/src/core/di/provider.d.ts (436, 135): Cannot find name 'Map'.
  node_modules/angular2/src/core/render/api.d.ts (13, 13): Cannot find name 'Map'.
  node_modules/angular2/src/core/render/api.d.ts (14, 84): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (1, 25): Cannot find name 'MapConstructor'.
  node_modules/angular2/src/facade/collection.d.ts (2, 25): Cannot find name 'SetConstructor'.
  node_modules/angular2/src/facade/collection.d.ts (4, 27): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (4, 39): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (7, 9): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (8, 30): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (11, 43): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (12, 27): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (14, 23): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (15, 25): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (95, 41): Cannot find name 'Set'.
  node_modules/angular2/src/facade/collection.d.ts (96, 22): Cannot find name 'Set'.
  node_modules/angular2/src/facade/collection.d.ts (97, 25): Cannot find name 'Set'.
  node_modules/angular2/src/facade/lang.d.ts (13, 17): Cannot find name 'Map'.
  node_modules/angular2/src/facade/lang.d.ts (14, 17): Cannot find name 'Set'.
  node_modules/angular2/src/facade/lang.d.ts (78, 59): Cannot find name 'Map'.
  node_modules/angular2/src/facade/promise.d.ts (1, 10): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (3, 14): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (8, 32): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (9, 38): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (10, 35): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (10, 93): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (11, 34): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (12, 32): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (12, 149): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (13, 43): Cannot find name 'Promise'.
  node_modules/angular2/src/platform/browser/browser_adapter.d.ts (75, 33): Cannot find name 'Map'.
  node_modules/angular2/src/platform/dom/dom_adapter.d.ts (85, 42): Cannot find name 'Map'.
  node_modules/angular2/src/testing/matchers.d.ts (4, 37): Cannot find namespace 'jasmine'.
  node_modules/rxjs/CoreOperators.d.ts (22, 67): Cannot find name 'Promise'.
  node_modules/rxjs/CoreOperators.d.ts (72, 67): Cannot find name 'Promise'.
  node_modules/rxjs/CoreOperators.d.ts (77, 31): Cannot find name 'PromiseConstructor'.
  node_modules/rxjs/CoreOperators.d.ts (77, 54): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (65, 67): Cannot find name 'PromiseConstructor'.
  node_modules/rxjs/Observable.d.ts (65, 88): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (72, 84): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (77, 38): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (100, 66): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (154, 66): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (159, 31): Cannot find name 'PromiseConstructor'.
  node_modules/rxjs/Observable.d.ts (159, 54): Cannot find name 'Promise'.
Error: [DiffingTSCompiler]: Typescript found the following errors:
  /home/dinesh/new-angular-cli-generator/foo/src/typings.d.ts (1, 1): File '/home/dinesh/new-angular-cli-generator/foo/typings/browser.d.ts' not found.
  app/foo.spec.ts (8, 32): Property 'toBe' does not exist on type 'NgMatchers'.
  app/foo.spec.ts (13, 35): Property 'toBe' does not exist on type 'NgMatchers'.
  app/foo.spec.ts (14, 37): Property 'toBe' does not exist on type 'NgMatchers'.
  node_modules/angular2/src/core/change_detection/parser/locals.d.ts (3, 14): Cannot find name 'Map'.
  node_modules/angular2/src/core/change_detection/parser/locals.d.ts (4, 42): Cannot find name 'Map'.
  node_modules/angular2/src/core/debug/debug_node.d.ts (14, 13): Cannot find name 'Map'.
  node_modules/angular2/src/core/debug/debug_node.d.ts (24, 17): Cannot find name 'Map'.
  node_modules/angular2/src/core/debug/debug_node.d.ts (25, 17): Cannot find name 'Map'.
  node_modules/angular2/src/core/di/provider.d.ts (436, 103): Cannot find name 'Map'.
  node_modules/angular2/src/core/di/provider.d.ts (436, 135): Cannot find name 'Map'.
  node_modules/angular2/src/core/render/api.d.ts (13, 13): Cannot find name 'Map'.
  node_modules/angular2/src/core/render/api.d.ts (14, 84): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (1, 25): Cannot find name 'MapConstructor'.
  node_modules/angular2/src/facade/collection.d.ts (2, 25): Cannot find name 'SetConstructor'.
  node_modules/angular2/src/facade/collection.d.ts (4, 27): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (4, 39): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (7, 9): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (8, 30): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (11, 43): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (12, 27): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (14, 23): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (15, 25): Cannot find name 'Map'.
  node_modules/angular2/src/facade/collection.d.ts (95, 41): Cannot find name 'Set'.
  node_modules/angular2/src/facade/collection.d.ts (96, 22): Cannot find name 'Set'.
  node_modules/angular2/src/facade/collection.d.ts (97, 25): Cannot find name 'Set'.
  node_modules/angular2/src/facade/lang.d.ts (13, 17): Cannot find name 'Map'.
  node_modules/angular2/src/facade/lang.d.ts (14, 17): Cannot find name 'Set'.
  node_modules/angular2/src/facade/lang.d.ts (78, 59): Cannot find name 'Map'.
  node_modules/angular2/src/facade/promise.d.ts (1, 10): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (3, 14): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (8, 32): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (9, 38): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (10, 35): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (10, 93): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (11, 34): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (12, 32): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (12, 149): Cannot find name 'Promise'.
  node_modules/angular2/src/facade/promise.d.ts (13, 43): Cannot find name 'Promise'.
  node_modules/angular2/src/platform/browser/browser_adapter.d.ts (75, 33): Cannot find name 'Map'.
  node_modules/angular2/src/platform/dom/dom_adapter.d.ts (85, 42): Cannot find name 'Map'.
  node_modules/angular2/src/testing/matchers.d.ts (4, 37): Cannot find namespace 'jasmine'.
  node_modules/rxjs/CoreOperators.d.ts (22, 67): Cannot find name 'Promise'.
  node_modules/rxjs/CoreOperators.d.ts (72, 67): Cannot find name 'Promise'.
  node_modules/rxjs/CoreOperators.d.ts (77, 31): Cannot find name 'PromiseConstructor'.
  node_modules/rxjs/CoreOperators.d.ts (77, 54): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (65, 67): Cannot find name 'PromiseConstructor'.
  node_modules/rxjs/Observable.d.ts (65, 88): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (72, 84): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (77, 38): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (100, 66): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (154, 66): Cannot find name 'Promise'.
  node_modules/rxjs/Observable.d.ts (159, 31): Cannot find name 'PromiseConstructor'.
  node_modules/rxjs/Observable.d.ts (159, 54): Cannot find name 'Promise'.
    at DiffingTSCompiler.doFullBuild (/home/dinesh/new-angular-cli-generator/angular-cli/lib/broccoli/broccoli-typescript.js:202:29)
    at DiffingTSCompiler.rebuild (/home/dinesh/new-angular-cli-generator/angular-cli/lib/broccoli/broccoli-typescript.js:101:18)
    at DiffingPluginWrapper.rebuild (/home/dinesh/new-angular-cli-generator/angular-cli/lib/broccoli/diffing-broccoli-plugin.js:87:45)
    at /home/dinesh/new-angular-cli-generator/angular-cli/node_modules/ember-cli/node_modules/broccoli/lib/api_compat.js:42:21
    at lib$rsvp$$internal$$tryCatch (/home/dinesh/new-angular-cli-generator/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/home/dinesh/new-angular-cli-generator/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /home/dinesh/new-angular-cli-generator/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/home/dinesh/new-angular-cli-generator/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

**Comment by filipesilva** [comment]
I think it's the same issue. You need to use the latest master at the moment, the typings problem has been fixed in it.

See https://github.com/angular/angular-cli#working-with-master

I'm closing but please reopen if you still have the issue. It's just that it's a problem that has come up a few times last week and I believe this to be the solution.

**Comment by deepakgd** [comment]
I did,
1. git clone https://github.com/angular/angular-cli.git
2. cd angular-cli
3. npm link
4. ng new foo
5. cd foo
6. npm link angular-cli
7. ng server

same issue exists

**Comment by filipesilva** [comment]
Roger. Will investigate.

**Comment by filipesilva** [comment]
@deepakgd I wasn't able to reproduce. See [here](https://gist.github.com/filipesilva/2db690d6e481df14df56) for the console log I got for the commands you provided.

Is there anything I missed?

**Comment by deepakgd** [comment]
ya same i did

**Comment by filipesilva** [comment]
Can you show me your log for these commands?

**Comment by deepakgd** [comment]
sure. I will post it on Monday. I started my travel now

**Comment by filipesilva** [comment]
:+1:

**Comment by deepakgd** [comment]
ng server is working fine after restarting system. thanks

**Comment by Brocco** [comment]
Thanks for the feedback @deepakgd 

Are you still having issues @JasonGoemaat ? If so, please let us know if not we will close this issue.

**Comment by hansl** [comment]
This works and we now have e2e tests on Windows, so I'm pretty sure these use cases are passing the tests right now. Clsoing this.
