### ISSUE TITLE
same issue(ng github-pages:deploy Missing angular-cli-build.js in 1.0.0-beta.11-webpack)  why is it closed?

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#1810]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OS X 
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.4.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
i created app with ng new

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
i explained everything at the bottom of the same issue that has been closed
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by stefanaerts** [comment]
same problem for me with angular-cli@1.0.0-beta.11-webpack.2
--steps ---------------
1) ng new 'projectname' ,
2) create repo on github 
3) git commit -m 'initial commit with angular-cli generated code' 
4) git push -u origin master

5) ng github-pages:deploy

ng github-pages:deploy throws the error: "no angular cli-build.js found"
 @stefanaerts
     
stefanaerts commented 8 minutes ago
and i did all of it, install angular-cli local puts ^ in front but that doesnt work.
Then i changed the local package.json again with ^ removed, but still the same error.
i did npm install and repeated all the steps again, still the same error.
So it would be very nice if somebody of the angular-cli developers can explain whats going on. Thx.

**Comment by serhiisol** [comment]
this bug was already fixed I just installed application with latest version, it works. Check your local and global modules

**Comment by stefanaerts** [comment]
what is the latest version then that i can install with npm?

**Comment by serhiisol** [comment]
1.0.0-beta.11-webpack.2

**Comment by stefanaerts** [comment]
i have installed local and global angular-cli@1.0.0-beta.11-webpack.2

**Comment by stefanaerts** [comment]
ncu says i am up to date

**Comment by stefanaerts** [comment]
so i am up to date, and i have the error.
Please read the steps i did

**Comment by stefanaerts** [comment]
other global packages installed,i guess that cannot influence?
These are my global packages installed
$ sudo npm list -g --depth=0
/usr/local/lib
├── angular-cli@1.0.0-beta.11-webpack.2
├── bower@1.7.9
├── firebase-tools@3.0.7
├── n@2.1.4
├── npm@3.10.6
├── npm-check-updates@2.8.0
├── polymer-cli@0.14.0
├── typescript@2.0.0
└── typings@1.3.2

**Comment by stefanaerts** [comment]
these are the dependencies within node_modules/angular-cli package.json file
  "dependencies": {
    "@angular/tsc-wrapped": "^0.2.2",
    "@types/lodash": "^4.0.25-alpha",
    "@types/rimraf": "0.0.25-alpha",
    "@types/webpack": "^1.12.22-alpha",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^2.1.1",
    "chalk": "^1.1.3",
    "compression-webpack-plugin": "^0.3.1",
    "copy-webpack-plugin": "^3.0.1",
    "core-js": "^2.4.0",
    "css-loader": "^0.23.1",
    "ember-cli": "2.5.0",
    "ember-cli-string-utils": "^1.0.0",
    "enhanced-resolve": "^2.2.2",
    "exit": "^0.1.2",
    "exports-loader": "^0.6.3",
    "expose-loader": "^0.7.1",
    "file-loader": "^0.8.5",
    "fs-extra": "^0.30.0",
    "glob": "^7.0.3",
    "handlebars": "^4.0.5",
    "html-webpack-plugin": "^2.19.0",
    "istanbul-instrumenter-loader": "^0.2.0",
    "json-loader": "^0.5.4",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "leek": "0.0.21",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "lodash": "^4.11.1",
    "node-sass": "^3.7.0",
    "npm": "3.10.2",
    "offline-plugin": "^3.4.1",
    "opn": "4.0.1",
    "parse5": "^2.1.5",
    "phantomjs-polyfill": "0.0.2",
    "phantomjs-prebuilt": "^2.1.7",
    "postcss-loader": "^0.9.1",
    "protractor": "^3.3.0",
    "raw-loader": "^0.5.1",
    "remap-istanbul": "^0.6.4",
    "resolve": "^1.1.7",
    "rimraf": "^2.5.3",
    "rxjs": "^5.0.0-beta.11",
    "sass-loader": "^3.2.0",
    "shelljs": "^0.7.0",
    "silent-error": "^1.0.0",
    "source-map-loader": "^0.1.5",
    "sourcemap-istanbul-instrumenter-loader": "^0.2.0",
    "style-loader": "^0.13.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.1.0",
    "symlink-or-copy": "^1.0.3",
    "ts-helpers": "^1.1.1",
    "ts-loader": "^0.8.2",
    "tslint": "^3.11.0",
    "tslint-loader": "^2.1.4",
    "typedoc": "^0.4.2",
    "typescript": "^2.0.0",
    "url-loader": "^0.5.7",
    "webpack": "2.1.0-beta.18",
    "webpack-dev-server": "2.1.0-beta.0",
    "webpack-md5-hash": "0.0.5",
    "webpack-merge": "^0.14.0"
  },

**Comment by serhiisol** [comment]
try to clean cache, uninstall old angular-cli, install again latest, create new project

**Comment by songpa** [comment]
delete all directory in /node_modules
and try 'npm install'.

**Comment by serhiisol** [comment]
Also I tried to create project with ```--skip-npm``` and then ```npm install```

**Comment by stefanaerts** [comment]
ok, my project is created with the default generated code.In there i see in node_modules the angular-cli with in package.json "raw": "angular-cli@1.0.0-beta.11-webpack.2",
I have added this project to github.
So i guess i can run ng github-pages:deploy now?

**Comment by stefanaerts** [comment]
so to be clear, i removed the global package angular-cli@1.0.0-beta.11-webpack.2,i did npm clean cache, reinstalled angular-cli@1.0.0-beta.11-webpack.2.
Then i created a project with ng new, added it to github.
So i did not do npm install now, i just go try ng github-pages:deploy now?

**Comment by stefanaerts** [comment]
same problem still, i have to go now.

**Comment by filipesilva** [comment]
It's fixed on master but still pending a release.
