### ISSUE TITLE
ERROR Error: Uncaught (in promise): TypeError: Cannot call a class as a function

### ISSUE THREAD

**Issue by SathishKumarRajendran** [angular/angular-cli#18125]
### Description

While serving the sample getting console error in angular 10

### Error Screen shot

![image](https://user-images.githubusercontent.com/53341125/86424762-008bcb80-bd01-11ea-93d2-86cb4a48463b.png)

### Is this a regression?

Its working fine in angular 9

### Repro Steps

**Sample:**

https://github.com/SathishKumarRajendran/AngularSampleIssue

- npm i
- npm run start

**note:** If you get error like below image error while serving, Please install latest typescript and replace in the node_modules to resolve that issue. And again run the command 'npm run start'

![image](https://user-images.githubusercontent.com/53341125/86425527-0edae700-bd03-11ea-97d2-7c08aed48f71.png)
  

## 🌍 Environment
<pre><code>
Angular CLI: 10.0.1
Node: 10.15.1
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@angular/http                     6.1.10
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0

</code></pre>

If I try to individual sample its working fine.

**Comment by SathishKumarRajendran** [comment]
hi team,

Any update on this?

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Can you please suggest on this since this breaks our entire application.

**Comment by alan-agius4** [comment]
@kumaresan-subramani, the reproduction is far from minimal and thus it will take us more time to investigate and find the root cause.

We have limited resources and issue with minimal reproductions and a higher frequency takes precedence.

If you can create a minimal reproduction without any 3rd party code it will help us diagnostic the issue quicker.

**Comment by kumaresan-subramani** [comment]
@alan-agius4 , Thanks for the reply.

@SathishKumarRajendran , please share the issue reproducing sample only with one sample so that he can easily validate and update

**Comment by SathishKumarRajendran** [comment]
@alan-agius4 , Please find the minimal issue reproduced sample below,

**Sample:**

https://github.com/SathishKumarRajendran/AngularSampleIssue

**Repro Steps:**

- npm i
- npm run start

**Comment by alan-agius4** [comment]
Hi, 

I had a look at this reproduction and the error seems to appear in some cases when `baseClass.isFormBase` is truthy in the below mixin. 

```ts
export function applyMixins(derivedClass, baseClass) {
    baseClass.forEach(function (baseClass) {
        Object.getOwnPropertyNames(baseClass.prototype).forEach(function (name) {
            if (!derivedClass.prototype.hasOwnProperty(name) || baseClass.isFormBase) {
                derivedClass.prototype[name] = baseClass.prototype[name];
            }
        });
    });
}
```

In version 10, the ES5 version is being down-levelled with Babel which is some cases is stricter and more compliant with the specs.

Unfortunately, the reproduction is still very far from minimal and we don't have enough knowledge to debug and fully understanding all the use cases. From the initial investigation it does however appear that this is not an Angular/Angular CLI issue but likely a issue in the sync fusion libraries.

Feel free to open a new issue with a minimal reproduction in the case I am wrong.

Thanks.

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Thanks for your details,

But from your validation, you mentioned issue occurs due to mixin so  have tried to remove that condition like below stll i am facing same issue

```
export function applyMixins(derivedClass, baseClass) {
    baseClass.forEach(function (baseClass) {
        Object.getOwnPropertyNames(baseClass.prototype).forEach(function (name) {
                derivedClass.prototype[name] = baseClass.prototype[name];
        });
    });
}
```

## findings
`baseClass.forEach(function (baseClass) {` due to this reported issue occurs.i think we can't use mixin in angular 10

**Comment by alan-agius4** [comment]
If you remove the logical statement indeed the error will appear. Try to remove only ` || baseClass.isFormBase`.

It's like to point out that this mixin pattern doesn't rely that much on the the compiler, but more on the developer to ensure both runtime and type-system are correctly kept in sync. Therefore, errors will be reported during runtime.

I am sorry but the reproduction again is far from minimal and we cannot possible debug entire application or libraries. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the **minimum** possible code to show the problem ideally without any addition 3rd party library

**Comment by kumaresan-subramani** [comment]
HI @alan-agius4 ,

Thanks, i will share issue repro sample.

Even if remove above mentioned[`|| baseClass.isFormBase`], still facing same issue

![image](https://user-images.githubusercontent.com/36756050/89995994-e05c0e80-dca7-11ea-8f9c-95406688950c.png)
