### ISSUE TITLE
Question: Embed my css, images, fonts, js and more

### ISSUE THREAD

**Issue by prsolucoes** [angular/angular-cli#1812]
Hi,

In my project GoCI, im migrating my web app to a web app with ng2. Everything is working before i migrate to angular-cli.

I have installed angular-cli, create the project, put my source files, bla bla bla.

When i run "ng serve", it is loading and working. But all css, bootstrap files, jquery, are not loaded:

My project and files:
https://github.com/prsolucoes/goci/tree/support-angular2/web-app

Screenshot of the result from "ng build":
https://www.dropbox.com/s/kjop1kv3d4gq6wx/Screenshot%202016-08-23%2011.41.14.png?dl=0

My index.html that i tried load my css/js rom bootstrap 3, jqury, toatr, ...:
https://github.com/prsolucoes/goci/blob/support-angular2/web-app/src/index.html

My angular-cli.json file:
https://github.com/prsolucoes/goci/blob/support-angular2/web-app/angular-cli.json

Can anyone help me?

Thanks.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/1633 and https://github.com/angular/angular-cli/pull/1747 address your needs, but the webpack version hasn't had a release yet that includes support for global styles and scripts. It should be available to install soon.
