### ISSUE TITLE
ng build in docker failing after migrating from Angular 7 to 8

### ISSUE THREAD

**Issue by gentaliti** [angular/angular-cli#18121]
We upgraded Angular from 7 to 8.

But while building the docker image this step is failing:

```
ng "build" "--prod" "--configuration" "development" "--output-path=docs" "--serviceWorker=true" "--verbose" "--progress=true"
```

Is getting stucked at 11% with this stacktrace:

```
[webpack.Progress] 11% building 11/12 modules 1 active /app-ui/node_modules/mini-css-extract-plugin/dist/loader.js!/app-ui/node_modules/@angular-devkit/build-angular/src/angular-cli-files/plugins/raw-css-loader.js!/app-ui/node_modules/postcss-loader/src/index.js??extracted!/app-ui/node_modules/sass-loader/lib/loader.js??ref--15-3!/app-ui/src/styles.scss
Removing intermediate container e45e8a69a2aa
```

Then failed to copy a directory in docker:

```
Step 14/16 : COPY --from=0 /app-ui/docs /usr/share/nginx/html
COPY failed: stat /var/lib/docker/overlay2/***/merged/app-ui/docs: no such file or directory
```

Here's my Dockerfile:

```
FROM node:12.10.0-alpine

ENV LC_ALL C

ARG env=production

RUN apk update && apk upgrade && apk add --no-cache make git && rm -rf /var/cache/apk/* /tmp/*

ADD . /app-ui
WORKDIR /app-ui

RUN npm install
RUN npm run ng build -- --prod --configuration $env --output-path=docs --serviceWorker=true --verbose --progress=true

FROM nginx:alpine

RUN apk update && apk upgrade && rm -rf /var/cache/apk/* /tmp/*
RUN rm -rf /usr/share/nginx/html/*
COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=0 /app-ui/docs /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
```

**Comment by alan-agius4** [comment]
Hi @gentaliti, does the same issue happen outside of docker? Since version 8 a lot of things have changed in the build pipeline. Can you try to see if the problem persists with version 10?

Thanks.

**Comment by gentaliti** [comment]
Hi @alan-agius4, it only happens in docker and when limiting it's memory to 8GB. 

Unfortunately we have a limited size of memory in Bitbucket pipelines (using CircleCi) and we can't afford having more than 8GB of memory for our projects' builds.

Looks like a memory issue but yet we don't have any more logs... 

It always fails with @angular-devkit while compiling scss to css. Could it be something with @angular-devkit version?

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?  I am not seeing any OOM exceptions from the error above, so I don't think you are reaching the memory limit.

Regarding logs, also note that it's not recommended to use `--verbose` and `--progress` together, the `verbose` option works best when `progress` is disabled.

Since Angular CLI version 8, a lot has changed in `@angular-devkit` and it's dependencies so I won't be surprised that the issue you are experiencing has been fixed in the mean time.

**Comment by gentaliti** [comment]
Thanks @alan-agius4. We fixed the issue by upgrading to Angular 10.

**Comment by alan-agius4** [comment]
Glad to hear that.
