### ISSUE TITLE
ng serve --open Application not found

### ISSUE THREAD

**Issue by RonaldFernandoChica** [angular/angular-cli#18143]
Im getting the following message after running ng serve -o in my aplicattion after updating my application from angular 8 to angular 9.1.1

![image](https://user-images.githubusercontent.com/48487055/86496092-69933380-bd41-11ea-85d5-3b252ea129d5.png)

**Comment by alan-agius4** [comment]
@RonaldFernandoChica, what happens if you click on the hyperlink in the terminal?

**Comment by RonaldFernandoChica** [comment]
The Aplicattion start with no problem if i click the link or type the localhost in the browser but get that exception every time i run the ng serve -o command

**Comment by alan-agius4** [comment]
What’s the configured default browser? Typically that Windows errors is shown when a default browser is not configured.

Can you also try to replicate this with the latest version of the CLI please?

```
npx @angular/cli@latest new testing —-defaults —-no-interactive
cd testing
ng serve -o
```

**Comment by RonaldFernandoChica** [comment]
the problem was the default browser i had brave as my default browser change it to firefox developer and worked, thanks
