### ISSUE TITLE
Non-pluralized Entry for Safari in .browserslistrc

### ISSUE THREAD

**Issue by simonua** [angular/angular-cli#18140]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
I am not positive whether this is a regression.

### Description
The generated _.browserslistsrc_ file does not pluralize the entry for Safari: `last 2 Safari major version`
It appears inconsequential whether it's singular or plural, but the entry is inconsistent when compared to the properly-pluralized ones for Edge and iOS.

## 🔬 Minimal Reproduction
1) Run `ng new repro-app`, accepting all defaults.
1) Switch to _repro-app_ directory.
1) Run `browserslist` to see this output:

```
chrome 83
edge 83
edge 81
firefox 78
firefox 77
firefox 68
ios_saf 13.4-13.5
ios_saf 13.3
ios_saf 13.2
ios_saf 13.0-13.1
ios_saf 12.2-12.4
ios_saf 12.0-12.1
safari 13.1
safari 13
safari 12.1
safari 12
```

1) Edit _,browserslistrc_.
1) Change `last 2 Safari major version` to `last 2 Safari major versions`.
1) Run `browserslist` to see this same output:

```
chrome 83
edge 83
edge 81
firefox 78
firefox 77
firefox 68
ios_saf 13.4-13.5
ios_saf 13.3
ios_saf 13.2
ios_saf 13.0-13.1
ios_saf 12.2-12.4
ios_saf 12.0-12.1
safari 13.1
safari 13
safari 12.1
safari 12
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.1
Node: 14.5.0
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
`version` and `versions‘ are interchangeable.

Though we should fix this, to avoid confusion.
