### ISSUE TITLE
[library] dist folder unlink error

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#18154]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
When you build library for the second time when there is already dist you will end up with this error and manually you will have to delete dist folder
```
> ng build ion-camera

Building Angular Package
ERROR: EPERM: operation not permitted, unlink 'D:\ionic\camera\projects\ion-camera\dist\src'
An unhandled exception occurred: EPERM: operation not permitted, unlink 'D:\ionic\camera\projects\ion-camera\dist\src'
See "C:\Users\indra26\AppData\Local\Temp\ng-wHTEMP\angular-errors.log" for further details.
```

## 🔬 Minimal Reproduction

Repo: https://github.com/indraraj26/ion-camera
step 1: clone
step 2: npm i && npm run lib

## 🔥 Exception or Error
<pre><code>

> ng build ion-camera

Building Angular Package
ERROR: EPERM: operation not permitted, unlink 'D:\ionic\camera\projects\ion-camera\dist\src'
An unhandled exception occurred: EPERM: operation not permitted, unlink 'D:\ionic\camera\projects\ion-camera\dist\src'
See "C:\Users\indra26\AppData\Local\Temp\ng-wHTEMP\angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.7
Node: 10.16.3
OS: win32 x64

Angular: 9.1.9
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.7
@angular-devkit/build-angular      0.901.7
@angular-devkit/build-ng-packagr   0.901.7
@angular-devkit/build-optimizer    0.901.7
@angular-devkit/build-webpack      0.901.7
@angular-devkit/core               9.1.7
@angular-devkit/schematics         9.1.7
@angular/cli                       9.1.7
@ngtools/webpack                   9.1.7
@schematics/angular                9.1.7
@schematics/update                 0.901.7
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @indraraj26, I tried to replicate the error using your reproduction but I wasn't able. In the log file which path is part of the error message you should have some more details about the failure.

`EPERM: operation not permitted` typically means that the file is either in use or you don't have any permissions to perform the operation.

Closing as this doesn't appear to be an issue in the Angular CLI.

**Comment by indraraj26** [comment]
I dont know whats wrong here as D drive isn;t my system drive

this is what i get in error log
![image](https://user-images.githubusercontent.com/23274631/86594529-cfd3bc80-bfb4-11ea-850a-29a8990927d2.png)
