### ISSUE TITLE
Schematics does not prompt for input from user in git bash.

### ISSUE THREAD

**Issue by darpankumar** [angular/angular-cli#18163]
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
-  [x] add for custom Schematics
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No
 No
 Yes, the previous version in which this bug was not present was: ....

### Description
Either it is custom Schematics or angular Schematics, when I try to run this in git bash it does not prompt for values and runs the whole workflow with default values and if no default value is set it either fail if require flag is true otherwise set the empty value for the input.
even though somebody previously raised this issue 
https://github.com/angular/angular-cli/issues/14938
But it was marked closed
I see this as a bug because it behaves differently in a different terminal. the behaviour should be the same across all the terminal. otherwise, some information must be given BCS of which it is happening.

One observation if you create schematics and test it locally by 
npm link path to schematics
and then try to run the schematics with command
schematics path:schematic-name 
then it works in git bash as well.
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

ng new appName
It works fine in command prompt
on mac terminal 
vs code terminal
but with git bash it causes problem it do not ask for user input and run the whole workflow with default values

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.6
Node: 12.16.1
OS: win32 x64
Angular:
...
Ivy Workspace:
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.6
@angular-devkit/core         9.0.6
@angular-devkit/schematics   9.0.6
@schematics/angular          9.0.6
@schematics/update           0.900.6
rxjs                         6.5.3
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Git Bash is a non-interactive terminal which means our prompt library doesn't work with it. 

See: SBoudrias/Inquirer.js#570

**Comment by darpankumar** [comment]
Why does it work when i run it with schematics path:schematic-name @alan-agius4

**Comment by alan-agius4** [comment]
That is an interesting deal.

**Comment by alan-agius4** [comment]
That is an interesting detail. Will need to investigate this a bit more.

**Comment by clydin** [comment]
What version of windows is being used?

**Comment by darpankumar** [comment]
> What version of Windows is being used?

Its window 7 enterprise

**Comment by darpankumar** [comment]
<img width="586" alt="Screenshot 2020-07-06 at 11 14 20 PM" src="https://user-images.githubusercontent.com/21257218/86721661-d52c1800-c043-11ea-8753-dd597eac3465.png">
@alan-agius4 you can have a look at the screenshot attached

**Comment by alan-agius4** [comment]
In the Schematics CLI, the prompts are being displayed because unlike in the Angular CLI we are not checking whether the terminal is TTY.

Schematics CLI
https://github.com/angular/angular-cli/blob/111e9cc38372620656685752a392b46fa1b68336/packages/angular_devkit/schematics_cli/bin/schematics.ts#L272-L273

NG CLI
https://github.com/angular/angular-cli/blob/f4127b5b4356b7966a058b118335b7857922d613/packages/angular/cli/models/schematic-command.ts#L321-L322.

Can you try to run  `node --eval "console.log({stdin: process.stdin.isTTY, stdout: process.stdout.isTTY})"`?

**Comment by darpankumar** [comment]
<img width="575" alt="Screenshot 2020-07-07 at 5 07 39 PM" src="https://user-images.githubusercontent.com/21257218/86774708-6a470500-c074-11ea-8c42-fd741350c7a7.png">
Here is the output @alan-agius4

**Comment by alan-agius4** [comment]
Hi @darpankumar, myself and @clydin had a chat around the issue that you are experiencing and unfortunately this is not something that we can easily replicate as this would require some debugging on your system.

I am going to leave the issue open for a couple of days maybe someone else can replicate this debug and be able to find the root cause of the problem.

**Comment by mrednic** [comment]
Hello,
I have the same problem in `git bash` on Windows 10 Enterprise Edition, with a custom schematics I have.
There is an interesting behavior I have seen. 
If I run `yarn ng generate @my/generator:component` the promt does  not appear and the schema validation fails on the properties that should have been completed in the prompt.
If I run ` node ./node_modules/@angular/cli/bin/ng generate @my/generator:component` the promt appears and everything works as expected.

**Comment by alan-agius4** [comment]
This is working as expected. 

See: https://github.com/nodejs/node/issues/39673
