### ISSUE TITLE
Angular 10.0.1 build vendor.js SourceMap out of memory

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#18161]
>93% after chunk asset optimization SourceMapDevToolPlugin vendor.js generate SourceMap
<--- Last few GCs --->

[60676:000001F618968520]   112934 ms: Mark-sweep (reduce) 4060.6 (4101.4) -> 4059.6 (4101.7) MB, 1496.4 / 0.0 ms  (average mu = 0.147, current mu = 0.002) allocation failure scavenge might not succeed
[60676:000001F618968520]   114892 ms: Mark-sweep (reduce) 4060.8 (4101.7) -> 4059.9 (4101.9) MB, 1955.8 / 0.0 ms  (average mu = 0.080, current mu = 0.001) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF61AF5E87F v8::internal::wasm::DisjointAllocationPool::~DisjointAllocationPool+76303
 2: 00007FF61AF05B66 v8::base::OS::ActivationFrameAlignment+33350
 4: 00007FF61B7A6CAE v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF61B78BC4D v8::SharedArrayBuffer::Externalize+781
 6: 00007FF61B64A80C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1500
 7: 00007FF61B655D5A v8::internal::Heap::ProtectUnprotectedMemoryChunks+1258
 8: 00007FF61B652D51 v8::internal::Heap::PageFlagsAreConsistent+3313
 9: 00007FF61B647C65 v8::internal::Heap::CollectGarbage+1493
10: 00007FF61B6462A5 v8::internal::Heap::AllocateExternalBackingStore+1365
11: 00007FF61B665ACF v8::internal::Factory::NewFillerObject+191
12: 00007FF61B39A2A1 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1409
13: 00007FF61B82FC0D v8::internal::SetupIsolateDelegate::SetupHeap+466637

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
