### ISSUE TITLE
360 visor problem

### ISSUE THREAD

**Issue by RonaldFernandoChica** [angular/angular-cli#18165]
I'm getting the following error after updating from Angular 8 to Angular 9.1.1 in the following package:

[Angular Three Sixty](https://www.npmjs.com/package/@mediaman/angular-three-sixty)

![image](https://user-images.githubusercontent.com/48487055/86622166-0d205600-bf85-11ea-9f31-88a83e07b9bb.png)

and i need to use this package i dont know about another 360 visor for Angular i aprecciate your help thanks.

**Comment by clydin** [comment]
The linked package is based off of Angular 5 which is no longer supported (Angular 10 is the current stable release).  It also appears that the last published version is 2 years old (version 0.0.8) and the package repository has been archived.  Based on this it is unfortunately most likely that the package is no longer supported.

**Comment by RonaldFernandoChica** [comment]
what can i do now?

**Comment by petebacondarwin** [comment]
You could try contacting the original author and see if they would update it to the latest Angular. Otherwise you could fork their project and update it yourself.

**Comment by alan-agius4** [comment]
Closing as this is not actionable by the Angular tooling team.
