### ISSUE TITLE
Add ability to specify failOnError flag for Circular Dependency Plugin

### ISSUE THREAD

**Issue by BruLex** [angular/angular-cli#18179]
# 🚀 Feature request

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
After migration from webpack usage to angular CLI it became impossible to fail our builds which contain Circular Dependencies  in our CI system.

Could you please consider adding ability to specify failOnError flag.
Thanks.

**Comment by alan-agius4** [comment]
Hi @BruLex, this can be achieve by using https://github.com/manfredsteyer/ngx-build-plus or https://github.com/just-jeb/angular-builders

**Comment by BruLex** [comment]
Hi @alan-agius4, I see that  [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) can help my team, we will try to use it if other solutions wont work. But what about introducing such thing(failOnError flag or extending showCircularDependencies with config, where anyone could specify level of warning and other things e.g. allowAsyncCycles flag and additional exclude paths) on angular CLI? Could you please consider to introduce it. If i not mistaken there it just require to bind one flag from config to plugin definition.

**Comment by alan-agius4** [comment]
Hi @BruLex,

Proving a way to pass options directly to Circular Dependency Plugin doesn't align with the Angular CLI vision. The reason being, is that the the build system implementation is hidden from the user, this means that we can replace the current plugin used or replace the entire Webpack build pipeline without causing any breaking changes.
