### ISSUE TITLE
Issues with importing interfaces created with export interface in Angular and TypeScript 3.9.6

### ISSUE THREAD

**Issue by stiezinger** [angular/angular-cli#18170]
### Description

Recently I switched from Angular 9 to 10. On a new project I have issues to import interfaces automatically. For example I want to import this interface to my app.component.ts:
<pre><code>
export interface TestInterface {
    string: name;
}
</code></pre>
It is located in src/app/testInterface.ts. When i try to import it in my app.component.ts:
<pre><code>
test: testInterface;
</code></pre>
I am using VSC and IntelliSense is not showing me the option to autoimport/import the interface anymore. When i press Ctrl+. for Quick Fix I receive the message: No code actions available. In Angular 9 with Typescript 3.8.3 everything works fine, IntelliSense shows me the autoimport option or I can import the interface with Ctrl+. Key Binding. If I manually add the import it works:
<pre><code>
import { testInterface } from 'src/app/testInterface';
</code></pre>

## 🔬 Reproduction
To reproduce this issue try to install the latest angular/cli (at the moment of writing v10.0.1):
<pre><code>
npm i @angular/cli@10.0.1 -g
</code></pre>

Then create a new project:
<pre><code>
ng new
</code></pre>
Name it as you wish, I have enabled routing and choosen CSS for stylesheets.

When you install Angular 9 and create an project:
<pre><code>
npm i @angular/cli@9.1.10 -g
</code></pre>
<pre><code>
ng new
</code></pre>

Everything works as it should

## 🌍 Environment
My Environment is:
<pre><code>
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.1
Node: 12.18.0
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cdk                      10.0.1
@angular/cli                      10.0.1
@angular/material                 10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0

Visual Studio Code Version 1.46.1
</code></pre>

**Comment by alan-agius4** [comment]
This is related to #18040
