### ISSUE TITLE
Upgrading to Angular 9/10 with ng update leads to installing deprecated tslint 6.1.0

### ISSUE THREAD

**Issue by tachojelev** [angular/angular-cli#18178]
## Description

Upgrading to Angular 9/10 with ng update leads to installing the deprecated version **6.1.0 of [tslint](https://www.npmjs.com/package/tslint)**, is this expected?
https://www.npmjs.com/package/tslint

**Comment by alan-agius4** [comment]
Hi @tachojelev, yes that is expected.

For more information related to ESLint migration kindly see: https://github.com/angular/angular-cli/issues/13732
