### ISSUE TITLE
Build/bundle angular core and other vendor libraries (e.g., angular-material) separately

### ISSUE THREAD

**Issue by realharry** [angular/angular-cli#18188]
# 🚀 Feature request

It'll be nice if we can (optionally) bundle angular core framework and angular-material components separately.

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...

Not entirely sure what the build/bundle process logic is during `ng build`, but I notice that angular-material components are always bundled together with the angular core libraries. I couldn't figure out how to separate them. Angular Material includes many small components, but when you use angular material you end up using many of the common components, and they add up quickly (often resulting in bigger contribution from the material than the core in the main bundle). I'm having issues with large main bundle size (excluding the lazy loaded modules) with angular material-enabled apps.

It'll be great if we can build angular material components into a separate downloadable bundle.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

Similar to `vendor-chunk` option, maybe we can add `material-chunk` option?

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Setting `vendor-chunk` or `common-chunk` could separately build angular-material bundle.

**Comment by realharry** [comment]
An example app (with some (mostly empty) modules and components, but with no real application logic). `vendor-chunk` not set:
![stats-json-1](https://user-images.githubusercontent.com/28793852/86884274-31c11e80-c0a8-11ea-8859-0670cd904628.png)

The same example app with `vendor-chunk` set:
![stats-json-2](https://user-images.githubusercontent.com/28793852/86884289-37b6ff80-c0a8-11ea-95aa-e0fd4c819f3e.png)

**Comment by alan-agius4** [comment]
Hi @realharry,

Thanks for this feature request. Adding an extra chunk is not in scope of the Angular CLI and it might cause increased in overall bundle sizes. Tree shaking in Webpack requires that modules are within the same bundle, so there is the possibility that if you create more chunks some unused code will be retained.

It's important to point that the vendor chunk option is not intended to be used for production, it is be used during development to reduce rebuild roundtrip time.

That said, if you really want to create a separate chunk for material, while it's not recommended you can use ngx-build-plus, which is a 3rd party extension of the CLI.
