### ISSUE TITLE
library upgrade didn't change tsConfig property to tsconfig.base.json

### ISSUE THREAD

**Issue by crfrolik** [angular/angular-cli#18180]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, it only applies to v10 migration

### Description

If you create a library using v9, and then upgrade to v10, you'll run into a problem.

The `angular.json` file post-upgrade looks like this (snippet):

```
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "tsconfig.json",
            "project": "ng-package.json"
          }
        },
```

But the `tsconfig.json` file is now a "solution-style" config. Using `ng build` causes an error:

```
Compiling TypeScript sources through ngc
ERROR: The "path" argument must be of type string. Received undefined
An unhandled exception occurred: The "path" argument must be of type string. Received undefined
See "/tmp/ng-tBIQqE/angular-errors.log" for further details.
error Command failed with exit code 127.
```

The contents of this `angular-errors.log` file look like this:

```
[error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Object.dirname (path.js:1128:5)
    at NgccProcessor.findNodeModulesDirectory (/home/crfrolik/source/repo/node_modules/ng-packagr/lib/ngc/ngcc-processor.js:80:21)
    at new NgccProcessor (/home/crfrolik/source/repo/node_modules/ng-packagr/lib/ngc/ngcc-processor.js:17:43)
    at /home/crfrolik/source/repo/node_modules/ng-packagr/lib/ng-package/entry-point/compile-ngc.transform.js:33:56
    at Generator.next (<anonymous>)
    at /home/crfrolik/source/repo/node_modules/ng-packagr/lib/ng-package/entry-point/compile-ngc.transform.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/crfrolik/source/repo/node_modules/ng-packagr/lib/ng-package/entry-point/compile-ngc.transform.js:4:12)
    at /home/crfrolik/source/repo/node_modules/ng-packagr/lib/ng-package/entry-point/compile-ngc.transform.js:22:75
```

Diving into this strack trace reveals that it's looking on the `compilerOptions` which doesn't exist anymore in `tsconfig.json`.

The workaround is to change the `angular.json` to point to `tsconfig.base.json` instead.

## 🔬 Minimal Reproduction

1. Create an Angular 9 repo and add a library
2. Upgrade to Angular 10 via `ng update`
3. `ng build`

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.1
Node: 12.18.2
OS: linux x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.1
@angular-devkit/build-angular      0.1000.1
@angular-devkit/build-ng-packagr   0.1000.1
@angular-devkit/build-optimizer    0.1000.1
@angular-devkit/build-webpack      0.1000.1
@angular-devkit/core               10.0.1
@angular-devkit/schematics         10.0.1
@angular/cli                       10.0.1
@ngtools/webpack                   10.0.1
@schematics/angular                10.0.1
@schematics/update                 0.1000.1
ng-packagr                         10.0.0
rxjs                               6.6.0
typescript                         3.9.6
webpack                            4.43.0

</code></pre>

**Comment by alan-agius4** [comment]
@crfrolik, the problem here is that you are using the base tsconfig as your library tsconfig ie: ` "tsConfig": "tsconfig.json"`. Typically the library has a dedicated tsconfig which is created under the library project. This file extends the base configuration.

While we can fix this for this particular migration, using the base typescript configuration directly for the compilation there are some considerations to be done here.

1. Might not be worth fixing the migration from our end since this is “non-standard”. I doubt that a lot of people are using the base tsconfig as their compilation tsconfig. 
2. Using this pattern might cause undefined and broken behaviours in future updates. In general the base tsconfig has the common options for all compilations in the workspace. Ex: apps, specs, libraries, server, workers etc.

**Comment by crfrolik** [comment]
I understand what you're saying. I am not sure it is worth fixing the migration if my config is non-standard.

I think I'd prefer if `ng-packagr` threw a better error message if the tsconfig isn't meeting its needs (e.g. missing `compilerOptions`), rather than spending time on a migration that most people won't need. Does that make sense?

Thanks for the quick response.

**Comment by alan-agius4** [comment]
@crfrolik, yeah that makes sense. Mind opening an issue in their issue tracker? Thanks.
