### ISSUE TITLE
"Native support" of content compression (gzip and/or br)

### ISSUE THREAD

**Issue by realharry** [angular/angular-cli#18187]
# 🚀 Feature request

It'll be nice if we can serve compressed content directly from angular build.

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

SPA apps like Angular are often served from static website/file servers without a real web server. It'll be great if we can directly serve the compressed files without needing a web server. (Furthermore, some cloud app platforms do not seem to provide an easy way compress files on the fly. For example, aws application load balancer (level 7) does not seem to have such a functionality. At least, I couldn't figure out how to do it.)

I've been using Angular on and off for some time now. One of the recurring problems for me has been the large bundle size of angular apps. In certain situations, 700~900kb framework size (uncompressed, including angular material) is just too big, and it makes angular unusable. I've been often struggling (without much success) to fit my whole application logic into a few hundred kilobytes. (I'm only talking about the main bundle size here, excluding lazy loaded modules.)

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

I haven't seen any client side framework doing this and I haven't really tried it, but I don't see why it cannot be easily done (at least, in theory).

First, during the build process, create compressed doppelgangers for all content files (primarily, js files). For example, for `main-abc.js`, we create `main-abc.js.gz` (or something like that).

When an angular app requests js files from a browser, add a content encoding header (gzip or br).  Then, the compressed doppelganger is served instead of the original js file. Not sure exactly how, at this point, though.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

Another solution might be instead of using js, simply use js.gzip or other compressed/binary files in the framework. The app simply downloads compressed js files and uncompress them before using them. This will require some kind of bootstrap.js to be loaded first so that it can download and uncompress, say, main.js.gz, etc. Again, I'm not entirely sure what the implications of doing this is. But, I cannot think of a reason why it cannot be done at this point.

**Comment by alan-agius4** [comment]
Hi @realharry,

Thanks for this feature request. However, after discussing this with our DevRel team. We feel that this is outside of the scope of the Angular CLI.

Thanks for your understanding.

**Comment by realharry** [comment]
Oh well. I thought it was a brilliant idea. :) Thanks for following up, alan.
