### ISSUE TITLE
ng new creates massive node_modules folder

### ISSUE THREAD

**Issue by RedFour** [angular/angular-cli#1819]
Currently using angular-cli@webpack version. When I create a new project it creates this massive node_modules folder with hundreds of things I don't need. This is even more problematic when I delete the node_modules folder and do a npm install, I get errors ng build on dependencies I didn't know I had.

[node modules folder screen on imgur](http://imgur.com/muIgVFI)

**Comment by filipesilva** [comment]
Part of that is the deduping behaviour of npm3. The other part of that is that our install is currently very big. Second bit is being tracked in https://github.com/angular/angular-cli/issues/1263
