### ISSUE TITLE
ERROR: EEXIST: file already exists during ng build command

### ISSUE THREAD

**Issue by nordine2017gitHub** [angular/angular-cli#18198]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

After linking the project with a custom library (my_custom_lib), I tried in vain to compile the project without success. On each attempt I have the error displayed below despite manual removal of the dist directory.

Thanks for our help.
Best Regards

## 🔬 Minimal Reproduction

npm i
npm link my_custom_lib
ng build

## 🔥 Exception or Error
<pre><code>

Copying assets
ERROR: EEXIST: file already exists, mkdir 'C:\Users\me\ANGULAR\pci-2011-ts-demo-master\dist\pci-ts-demo\src\assets_dmo\images'
An unhandled exception occurred: EEXIST: file already exists, mkdir 'C:\Users\me\ANGULAR\pci-2011-ts-demo-master\dist\pci-ts-demo\src\assets_dmo\images'
See "C:\Users\ME~1\AppData\Local\Temp\ng-oZYljU\angular-errors.log" for further details.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.7
Node: 12.18.2
OS: win32 x64

Angular: 9.1.11
... core, localize
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.901.7
@angular-devkit/build-angular       0.901.7
@angular-devkit/build-ng-packagr    0.901.7
@angular-devkit/build-optimizer     0.901.7
@angular-devkit/build-webpack       0.901.7
@angular-devkit/core                9.1.7
@angular-devkit/schematics          9.1.7
@angular/animations                 9.1.10
@angular/cli                        9.1.7
@angular/common                     9.1.10
@angular/compiler                   9.1.10
@angular/compiler-cli               9.1.10
@angular/forms                      9.1.10
@angular/platform-browser           9.1.10
@angular/platform-browser-dynamic   9.1.10
@angular/router                     9.1.10
@ngtools/webpack                    9.1.7
@schematics/angular                 9.1.7
@schematics/update                  0.901.7
ng-packagr                          9.1.5
rxjs                                6.5.5
typescript                          3.8.3
webpack                             4.42.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@nordine2017gitHub, can you please provide the contents of the log file?

**Comment by alan-agius4** [comment]
Will be solved in ng-packagr 10.0.1
