### ISSUE TITLE
Angular update from 9 to 10 does not add e2e/tsconfig.json to /tsconfig.json's references

### ISSUE THREAD

**Issue by ManuelRauber** [angular/angular-cli#18190]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

If you use `ng update` to update a project from Angular 9 to Angular 10 as described on update.angular.io, it will perform some transformations regarding the tsconfig files.

It will create a new `tsconfig.json` in the root of the project, containing a `references` object:

```
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ]
}
```

However, if you create a new Angular 10 project with the CLI, the root `tsconfig.json` also includes a references to the `e2e/tsconfig.json`:

```diff
{
  "files": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
-    }
+    },
+    {
+      "path": "./e2e/tsconfig.json"
+    }
+  ]
}
```

I would expect, that the upgrade process also adds the `e2e/tsconfig.json` to the root `tconfig.json`.

## 🔬 Minimal Reproduction

1. Create a new Angular 9 project with Angular CLI
2. Update the Angular 9 project to Angular 10 with Angular CLI according to update.angular.io (just run `ng update @angular/cli @angular/core`)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Angular 9 Project

<pre><code>
Angular CLI: 9.1.10
Node: 14.5.0
OS: darwin x64

Angular: 9.1.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.10
@angular-devkit/build-angular     0.901.10
@angular-devkit/build-optimizer   0.901.10
@angular-devkit/build-webpack     0.901.10
@angular-devkit/core              9.1.10
@angular-devkit/schematics        9.1.10
@angular/cli                      9.1.10
@ngtools/webpack                  9.1.10
@schematics/angular               9.1.10
@schematics/update                0.901.10
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

### Angular 10 Project
<pre><code>
Angular CLI: 10.0.1
Node: 14.5.0
OS: darwin x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@ManuelRauber, thanks for bringing this up. 

Actually since, the tsconfig of the e2e is named `tsconfig.json` there is no reason why it should be included in the solutions typescript configuration file.

Thus, this should be fixed for new projects.
