### ISSUE TITLE
A lot of warnings with `*.ngtypecheck.ts` files after ng10 upgrade

### ISSUE THREAD

**Issue by C0ZEN** [angular/angular-cli#18202]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No problem at all with the latest Angular 9 version.

### Description

I have this kind of warnings during `ng serve` command since I upgraded my project to Angular 10:

```
WARNING in S:\documents\manager-portal\src\hmr.ngtypecheck.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

### TSconfig files

**tsconfig.base.json:**

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noFallthroughCasesInSwitch": true,
    "strictNullChecks": false,
    "baseUrl": "./",
    "downlevelIteration": true,
    "importHelpers": true,
    "module": "es2020",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "resolveJsonModule": true,
    "strict": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "types": [
      "jasmine",
      "jasminewd2",
      "node",
      "googlemaps"
    ],
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "plugins": [
      {
        "name": "@angular/language-service"
      }
    ],
    "paths": {
      "@environment": [
        "src/environments/environment.ts"
      ],
      "@app/component": [
        "src/app/app.component.ts"
      ],
      "@app/routes": [
        "src/app/app.routes.ts"
      ],
      "@animations/*": [
        "src/app/animations/*"
      ],
      "@app-shell/*": [
        "src/app/app-shell/*"
      ],
      "@components/*": [
        "src/app/components/*"
      ],
      "@enums/*": [
        "src/app/enums/*"
      ],
      "@factories/*": [
        "src/app/factories/*"
      ],
      "@features/*": [
        "src/app/features/*"
      ],
      "@functions/*": [
        "src/app/functions/*"
      ],
      "@guards/*": [
        "src/app/guards/*"
      ],
      "@initializers/*": [
        "src/app/initializers/*"
      ],
      "@models/*": [
        "src/app/models/*"
      ],
      "@pages/*": [
        "src/app/pages/*"
      ],
      "@pipes/*": [
        "src/app/pipes/*"
      ],
      "@providers/*": [
        "src/app/providers/*"
      ],
      "@resolvers/*": [
        "src/app/resolvers/*"
      ],
      "@services/*": [
        "src/app/services/*"
      ],
      "@environments/*": [
        "src/environments/*"
      ]
    }
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "enableResourceInlining": false,
    "skipMetadataEmit": false,
    "strictMetadataEmit": true,
    "skipTemplateCodegen": false,
    "strictInjectionParameters": true,
    "generateCodeForLibraries": true,
    "fullTemplateTypeCheck": true,
    "trace": true,
    "enableIvy": true,
    "strictTemplates": true,
    "strictInputTypes": true
  }
}
```

**tconfig.json:**

```
{
  "files": [],
  "references": [
    {
      "path": "./src/tsconfig.app.json"
    },
    {
      "path": "./src/tsconfig.spec.json"
    }
  ]
}
```

**tconfig.app.json:**

```
{
  "extends": "../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app"
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.d.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts",
    "**/*.mock.ts"
  ]
}
```

## 🔥 Exception or Error
<pre><code>
WARNING in S:\documents\manager-portal\src\hmr.ngtypecheck.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
</code></pre>

## 🌍 Your Environment
<pre><code>
@angular-devkit/architect          0.901.10
@angular-devkit/build-angular      0.1000.1
@angular-devkit/build-optimizer    0.901.10
@angular-devkit/build-webpack      0.901.10
@angular-devkit/core               10.0.1
@angular-devkit/schematics         10.0.1
@angular/cdk                       10.0.1
@angular/cli                       10.0.1
@angular/material                  10.0.1
@angular/material-moment-adapter   10.0.1
@angular/pwa                       0.1000.1
@ngtools/webpack                   9.1.10
@schematics/angular                10.0.1
@schematics/update                 0.1000.1
rxjs                               6.5.5
typescript                         3.9.6
webpack                            4.41.0

</code></pre>

## Related issue

I saw this #17649 mentioning `*.ngtypecheck.ts` files but it seems already released.

**Comment by alan-agius4** [comment]
Hi @C0ZEN, I am seeing a lot of packages which have not been updated example `@angular-devkit/**` and `@ngtools/webpack` are still on version 9.

This typically indicates that you are using a custom Angular builder which doesn't support Angular 10, or you have these packages listed in your `devDepedencies`.

**Comment by C0ZEN** [comment]
@alan-agius4 I updated all I could to the latest versions so if those are causing the warnings then I should wait for an upgrade then.
This is not a mistake I use indeed custom builders.
Thank you for the fast response.
