### ISSUE TITLE
Error building sass files

### ISSUE THREAD

**Issue by dphung20** [angular/angular-cli#1820]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSx El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.4.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new app --style=sass
modify app.component.sass and add (with new line)
h1 {
 color: red
}

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ERROR in ./src/app/app.component.sass
Module build failed:
}
^
      Invalid CSS after "}": expected 1 selector or at-rule, was "{}"
      in /opt/drones/src/app/app.component.sass (line 2, column 2)
 @ ./src/app/app.component.ts 19:21-52
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

5. Mention any other details that might be useful.
seems to work when sass is on a single line without return (h1 { color: red})) 
but when there is a new line then the build will fail

**Comment by TimMurphy** [comment]
Experiencing same issue on Windows 10.

**Comment by TimMurphy** [comment]
We are using SASS incorrectly. SASS relies on indentation instead of {...}. See https://github.com/sass/sass/issues/216 & http://sass-lang.com/guide.

**Comment by mxii** [comment]
You want to use SCSS, another `SASS-Style`.

**Comment by dphung20** [comment]
thanks!!! scss is working as expected.

**Comment by Reza88** [comment]
Thanks for this!
