### ISSUE TITLE
latest ver of npm is incorrect. It's 9.1.11 instead of 10.0.2

### ISSUE THREAD

**Issue by eun-choi** [angular/angular-cli#18207]
latest ver of npm is incorrect. It's 9.1.11 instead of 10.0.2

```
@angular/cli
9.1.11 • Public • Published 4 hours ago
Tip: Click on a version number to view a previous version's package page
Current Tags
9.1.11
latest
10.1.0-next.0
next
6.2.9
v6-lts
8.3.28
v8-lts
7.3.10
v7-lts
9.1.10
v9-lts
Version History

9.1.11
4 hours ago
10.0.2
4 hours ago
10.1.0-next.0
4 hours ago
9.1.10
8 days ago
10.0.1
8 days ago
```

**Comment by Splaktar** [comment]
Right, the `latest` tag on NPM should point to `10.0.2`.

![Screen Shot 2020-07-09 at 21 20 42](https://user-images.githubusercontent.com/3506071/87106135-bf2c7c00-c22a-11ea-9c82-1e41c763257b.png)

**Comment by changhuixu** [comment]
ng update command doesn't update to v10 now...

**Comment by napei** [comment]
Can concur. `yarn global add @angular/cli` installs `9.1.11`

**Comment by daniloff200** [comment]
Yeah, I've got errors now, when try to build with the latest version, like

```
This version of CLI is only compatible with Angular versions 0.0.0 || ^9.0.0-beta || >=9.0.0 <10.0.0,
but Angular version 10.0.3 was found instead.
```

**Comment by miguellira** [comment]
@daniloff200 `10.0.3`? I was expecting a release of both `9.1.12` and `10.0.3` with a proper latest tag but neither been published to NPM. What version of Angular are your referencing in your `package.json`?

**Comment by daniloff200** [comment]
@miguellira I'm not specifically referencing 10+ version, but, have some jobs on my ci, which install latest & next versions of angular, to make sure, that library will work correct with them

in the Latest case, it was like

```
@angular/animations@10.0.3
+ @angular/compiler@10.0.3
+ @angular/core@10.0.3
+ @angular/common@10.0.3
+ @angular/forms@10.0.3
+ @angular/compiler-cli@10.0.3
+ @angular/cli@9.1.11
+ @angular/language-service@10.0.3
+ typescript@3.9.6
+ @angular/platform-browser@10.0.3
+ @angular/router@10.0.3
+ @angular/platform-browser-dynamic@10.0.3
+ @angular/platform-server@10.0.3
+ @schematics/angular@9.1.11
+ @angular/service-worker@10.0.3
```

**Comment by alan-agius4** [comment]
Hi all, we aware of the issue and will be addressed once a Googler in the US will be available to update tags of the packages. (Currently it's still 4:33am).

Points of action:
- Update `latest` tag to point to `v10.0.2`
- Update `v9-lts` tag to point to `v9.1.10`

```
$ for pkg in @angular/{cli,pwa} @angular-devkit/{architect,architect-cli,build-optimizer,build-ng-packagr,build-angular,build-webpack,core,schematics,schematics-cli} @ngtools/webpack @schematics/{angular,schematics,update}; do echo "\n$pkg"; npm dist-tag ls $pkg; done

@angular/cli
latest: 9.1.11
next: 10.1.0-next.0
v6-lts: 6.2.9
v7-lts: 7.3.10
v8-lts: 8.3.28
v9-lts: 9.1.10

@angular/pwa
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@angular-devkit/architect
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@angular-devkit/architect-cli
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@angular-devkit/build-optimizer
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@angular-devkit/build-ng-packagr
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@angular-devkit/build-angular
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@angular-devkit/build-webpack
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@angular-devkit/core
latest: 9.1.11
next: 10.1.0-next.0
v6-lts: 0.8.9
v7-lts: 7.3.10
v8-lts: 8.3.28
v9-lts: 9.1.10

@angular-devkit/schematics
latest: 9.1.11
next: 10.1.0-next.0
v6-lts: 0.8.9
v7-lts: 7.3.10
v8-lts: 8.3.28
v9-lts: 9.1.10

@angular-devkit/schematics-cli
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@ngtools/webpack
latest: 9.1.11
next: 10.1.0-next.0
v6-lts: 6.2.9
v7-lts: 7.3.10
v8-lts: 8.3.28
v9-lts: 9.1.10

@schematics/angular
latest: 9.1.11
next: 10.1.0-next.0
v6-lts: 0.8.9
v7-lts: 7.3.10
v8-lts: 8.3.28
v9-lts: 9.1.10

@schematics/schematics
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10

@schematics/update
latest: 0.901.11
next: 0.1001.0-next.0
v6-lts: 0.8.9
v7-lts: 0.13.10
v8-lts: 0.803.28
v9-lts: 0.901.10
```

**Comment by miguellira** [comment]
@daniloff200 Got it. Looks like the `latest` NPM tag of other Angular libraries are valid where as the `@angular/cli` NPM tags were not bumped when `10.0.3` and `9.1.12` was released. For now I've pegged everything to `10.0.2`. Hoping this gets resolved soon. Thanks.

**Comment by daniloff200** [comment]
@alan-agius4 heeey!
Thanks for your info!

I also saw, that the same issue with the version happened with @angular-devkit/core, @angular-devkit/schematics and @schematics/angular. Should I create a separate issue, to track that, or, it's the all the same part of already reported one?

**Comment by alan-agius4** [comment]
> I also saw, that the same issue with the version happened with @angular-devkit/core, @angular-devkit/schematics and @schematics/angular. Should I create a separate issue, to track that, or, it's the all the same part of already reported one?

All Angular CLI packages are effected by this, this includes `@schematics/*` and `@angular-devkit/` etc.. so no need to open a new issue.

**Comment by StephenFluin** [comment]
One of the workarounds if you are trying to `ng update` right now is to run `ng update @angular/core@10 @angular/cli@10`

**Comment by adhivenkatesh** [comment]
> One of the workarounds if you are trying to `ng update` right now is to run `ng update @angular/core@10 @angular/cli@10`

 But after updating unable to run ng serve --o getting below error :

An unhandled exception occurred: NGCC failed.
See "C:\Users\Admin\AppData\Local\Temp\ng-2cVol4\angular-errors.log" for further details.

**Comment by kyliau** [comment]
Sorry about this! I've retagged all CLI packages, with latest = v10.0.2.

```bash
$ ./bin/devkit-admin dist-tag --version 10.0.2 --tag latest
+latest: @angular/cli@10.0.2
+latest: @angular/pwa@0.1000.2
+latest: @angular-devkit/architect@0.1000.2
+latest: @angular-devkit/architect-cli@0.1000.2
+latest: @angular-devkit/build-angular@0.1000.2
+latest: @angular-devkit/build-ng-packagr@0.1000.2
+latest: @angular-devkit/build-optimizer@0.1000.2
+latest: @angular-devkit/build-webpack@0.1000.2
+latest: @angular-devkit/core@10.0.2
+latest: @angular-devkit/schematics@10.0.2
+latest: @angular-devkit/schematics-cli@0.1000.2
+latest: @ngtools/webpack@10.0.2
+latest: @schematics/angular@10.0.2
+latest: @schematics/schematics@0.1000.2
+latest: @schematics/update@0.1000.2
```

**Comment by adhivenkatesh** [comment]
Yes got resolved by  putting the below items in to  .src/tsconfig.json   

thanks for the response.

"angularCompilerOptions": {
    "enableIvy": false
},

**Comment by kyliau** [comment]
I've also retagged `v9-lts` to point to `v9.1.11`

```bash
$ ./bin/devkit-admin dist-tag --version 9.1.11 --tag v9-lts
+v9-lts: @angular/cli@9.1.11
+v9-lts: @angular/pwa@0.901.11
+v9-lts: @angular-devkit/architect@0.901.11
+v9-lts: @angular-devkit/architect-cli@0.901.11
+v9-lts: @angular-devkit/build-angular@0.901.11
+v9-lts: @angular-devkit/build-ng-packagr@0.901.11
+v9-lts: @angular-devkit/build-optimizer@0.901.11
+v9-lts: @angular-devkit/build-webpack@0.901.11
+v9-lts: @angular-devkit/core@9.1.11
+v9-lts: @angular-devkit/schematics@9.1.11
+v9-lts: @angular-devkit/schematics-cli@0.901.11
+v9-lts: @ngtools/webpack@9.1.11
+v9-lts: @schematics/angular@9.1.11
+v9-lts: @schematics/schematics@0.901.11
+v9-lts: @schematics/update@0.901.11
```
