### ISSUE TITLE
--prod breaks app by removing RXJS operators  (specifically optimization: true)

### ISSUE THREAD

**Issue by samdoeswork** [angular/angular-cli#18213]
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, this worked prior to Angular 10.

### Description

When building with --prod or anything else that has optimization: true, we get e.g. "this.$rawChange.startWith is not a function"
This is the same for all RXJS operators when trying to apply them to EventEmitters.

When building without --prod (or with optimization: false in the prod config) this works fine.

## 🔬 Minimal Reproduction
Define an observable via. e.g. `new EventEmitter<string>()`; then try and use .startWith or any other operator.
This runs fine with optimizations disabled, and fails with optimizations enabled.

export class MyComponent implements OnInit {
$rawChange = new EventEmitter<string>();

ngOnInit() {
this.filteredOptions = this.$rawChange
      .startWith(startingWith || null)
      .map(valueChange => valueChange ? this.filter(valueChange) : this.options.slice());
}
}

## 🔥 Exception or Error
<pre><code>
this.$rawChange.startWith is not a function
</code></pre>

## 🌍 Your Environment
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cdk                      10.0.1
@angular/cli                      10.0.1
@angular/flex-layout              9.0.0-beta.31
@angular/http                     7.2.16
@angular/material                 10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.6.0
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
@samdoeswork, are you using rxjs-compat?

**Comment by samdoeswork** [comment]
Thank you for picking this up so quickly. I'm not using rxjs-compat (at least not explicitly, it's in my package.json but I think that's added automatically). I searched the code and found no references

**Comment by alan-agius4** [comment]
Edit: looking at your snippet again indeed using rxjs-compat. Thus, this is expected, see: https://github.com/angular/angular-cli/issues/18045#issuecomment-651141100

**Comment by samdoeswork** [comment]
Hi, thank you for your quick reply. Could you explain why you think I'm using rxjs compat (I have tried researching directly, but if you could point me in the right direction).

I'm importing like this:

import { Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges, AfterViewChecked } from "@angular/core";
import { startWith } from "rxjs/operators";

**Comment by alan-agius4** [comment]
Because you are not using pipeable operators.
See: https://auth0.com/blog/whats-new-in-rxjs-6/

**Comment by samdoeswork** [comment]
Thanks! This has been incredibly helpful

[cid:image001.png@01D656D9.CE5642E0]<http://www.instant.marketing/>
Launching 2 new channels LIVE: Join the webinar - "Eloqua on TEN Channels" – 21st July
Sign up and more info<https://bit.ly/3edUl4j>

Please note: Just Add Features is now Instant Marketing ⚡
www.instant.marketing<http://www.instant.marketing/>
