### ISSUE TITLE
@angular/cli 10.0.0 polyfills not importing "polyfills" files when build to prod

### ISSUE THREAD

**Issue by javierdpt** [angular/angular-cli#18216]
# 🐞 Bug report

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.1.11

### Description

I have multiple polyfills files I import in the polyfills.ts file. While using ng serve this works fine but when I build the application to prod it doesn't. The work around I found was adding the code block inline but is working fine in the previous version of angular, this stopped working when I created a new app with angular 10.

## 🔬 Minimal Reproduction

I have this file: string.polyfills.ts
`
interface String {
    contains(search: string): boolean;
}
if (!String.prototype.hasOwnProperty('contains')) {
    String.prototype.contains = function (search: string): boolean {
        return this.indexOf(search) !== -1;
    };
}
`

and in the src/polyfills.ts line 55 I have the following
`import './path/to/string.extension';`

If I do ng serve I can do in the browser's console 'test'.contains(es);
But with ng serve --prod (for example) the string.contains is undefined.

If I add all the content of the file (string.polyfills.ts) in the polyfills.ts it works but I would like to know what it stoped working in angular 10.

## 🌍 Environment
Angular CLI: 10.0.0
Node: 14.4.0
OS: win32 x64

Angular: 10.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.0
@angular-devkit/build-angular     0.1000.0
@angular-devkit/build-optimizer   0.1000.0
@angular-devkit/build-webpack     0.1000.0
@angular-devkit/core              10.0.0
@angular-devkit/schematics        10.0.0
@ngtools/webpack                  10.0.0
@schematics/angular               10.0.0
@schematics/update                0.1000.0
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

Thanks for looking at this and awesome work 👏👏👏👏

**Comment by clydin** [comment]
The [`includes` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) is guaranteed to be available in all Angular CLI built applications.  It is the ECMAScript equivalent of the above custom `contains` method.

I tried to reproduce on a new v10 project but was unable.  Are there any `package.json` files within the project that contain `"sideEffects": false`?

**Comment by javierdpt** [comment]
Hi @clydin, thanks for your quick response, appreciated you looking at this. Yes it does have a file package.json with `sideEffects: false`. That came with it when I created the app. great catch. I moved the polyfills outside that folder and now is working as expected. Thank you very much!
