### ISSUE TITLE
[app-shell] Cannot read property 'initializer' of undefined

### ISSUE THREAD

**Issue by IsaacHub** [angular/angular-cli#18215]
I have done this in my existing project
I executed `ng add @angular/pwa` and it went all good, next I executed `ng generate app-shell` then I got the following error:
`Cannot read property 'initializer' of undefined`

Do you know how to resolve this?

```
Angular CLI: 10.0.0
Node: 14.4.0
OS: win32 x64

Angular: 10.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

```

**Comment by IsaacHub** [comment]
Do I need to convert my project to an Universal app before executing app-shell?

**Comment by alan-agius4** [comment]
@IsaacHub, no you don't need to add Universal prior to adding an App-shell. Universal is added automatically when adding the App-Shell.

I tried to replicate the above, but I didn't manage. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
