### ISSUE TITLE
Symlinked scss not triggering recompile on change

### ISSUE THREAD

**Issue by LoaderB0T** [angular/angular-cli#18229]
# 🐞 Bug report

### Command

- [ ] new
- [x] build (with --watch)
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Imagine the following filesystem structure:
<pre>
testFolder/
├── realFolder1/
│   └── style1.scss
├── realFolder2/
│   └── style2.scss
└── ngApp/
    ├── src/
    │   ├── styles.scss
    │   ├── link1
    │   └── link2
    └── .....
</pre>
link1 & link2 are symbolic links, linking to realFolder1 and realFolder2, respectively.
The styles.scss in the actual angular app imports the style1.scss from the linked folder link1.
The style1.scss imports the style2.scss from the linked folder link2.
styles.scss contains actual style definitions.

Now when serving (or building with --watch) everything gets compiled correctly, but changes to the styles2.scss are ignored and not rebuild. Only when triggering a change in a different file the changes from style2.scss are *sometimes* also recompiled.
Actually in my repro app this is even true for changes to style1.scss! However, on my "real" project where I discovered this, the issue only occurs on the second level of symlinked references...

## 🔬 Minimal Reproduction

To reproduce this issue you can do the following:
Either you recreate the above structure or you clone [my example app](https://github.com/LoaderB0T/scssSymlinkWatchBug) for this issue. In this example app for whatever reason symlinked scss files, do not trigger a recompile at all. In the real app this definitely works on some occasions where it is just one symlinked file, but fails when configured as above.

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.2
Node: 12.18.0
OS: win32 x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        10.0.2
@angular/cli                      10.0.2
@ngtools/webpack                  10.0.2
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
Reproducible with Windows 10 and WSL

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
