### ISSUE TITLE
Lint Issue: Angular CLI generate  `app-routing.module.ts` with consecutive blank lines  

### ISSUE THREAD

**Issue by kumaran-is** [angular/angular-cli#18220]
# 🐞 Bug report

### Command (mark with an `x`)
`app-routing.module.ts` generated by `Angular-cli v9`  has consecutive blank lines( line 3 & 4 in below screenshot) , causing lint issue. This was not happening in `Angular-cli v8`.

![Screen Shot 2020-07-10 at 3 50 59 PM](https://user-images.githubusercontent.com/6869139/87207410-d4141880-c2d9-11ea-9d56-09fd79c4c62f.png)

with tslint.json configuration, 

"rules": {
    "no-consecutive-blank-lines":true
}

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [X] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This was not happening in `Angular-cli v8`.

### Description

As mentioned above. 

## 🔬 Minimal Reproduction

- Install angular cli 9.1  `npm install -g @angular/cli@9`
- Create a new project `ng new my-app`  with route 
- Update your tslint.json configuration with below rule

"rules": {
    "no-consecutive-blank-lines": true
}

- Run. `ng lint`

- Lint fails with below error

/Users/work/Angular9/my-app/src/app/app-routing.module.ts:4:1
ERROR: 4:1  no-consecutive-blank-lines  Consecutive blank lines are forbidden

Lint errors found in the listed files.
npm ERR! code ELIFECYCLE
npm ERR! errno 1

## 🌍 Your Environment
Angular CLI: 9.1.11
Node: 12.13.0
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.11
@angular-devkit/core         9.1.11
@angular-devkit/schematics   9.1.11
@schematics/angular          9.1.11
@schematics/update           0.901.11
rxjs                         6.5.4

**Comment by sacgrover** [comment]
Please assign to me
