### ISSUE TITLE
missing typescript upgrade  when update v10

### ISSUE THREAD

**Issue by muhammedMoussa** [angular/angular-cli#18236]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 no

### Description
as [upgrade guide](https://update.angular.io/#9.0:10.0l3)

**During the Update**

- [ ]   Angular now requires tslint v6, tslib v2, and TypeScript 3.9. ng update will migrate you automatically.

so, have to manually upgrade.
upgrading successfully, but get compiler requires typescript missing upgrade also error.

## 🔬 Minimal Reproduction
```shell
 ng update @angular/core @angular/cli
```

before uprgade dependencies:

```json
 "dependencies": {
    "@angular/animations": "^9.1.3",
    "@angular/cdk": "^9.1.2",
    "@angular/common": "~9.1.2",
    "@angular/compiler": "~9.1.2",
    "@angular/core": "~9.1.2",
    "@angular/forms": "~9.1.2",
    "@angular/platform-browser": "~9.1.2",
    "@angular/platform-browser-dynamic": "~9.1.2",
    "@angular/router": "~9.1.2"
}

  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.9",
    "@angular/cli": "^9.1.1",
    "@angular/compiler-cli": "~9.1.2",
    "@angular/language-service": "~9.1.2"
}
```

after: 

```json
  "dependencies": {
    "@angular/animations": "^10.0.3",
    "@angular/cdk": "^9.1.2",
    "@angular/common": "~10.0.3",
    "@angular/compiler": "~10.0.3",
    "@angular/core": "~10.0.3",
    "@angular/forms": "~10.0.3",
    "@angular/platform-browser": "~10.0.3",
    "@angular/platform-browser-dynamic": "~10.0.3",
    "@angular/router": "~10.0.3"
}

  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.2",
    "@angular/cli": "^10.0.2",
    "@angular/compiler-cli": "~10.0.3",
    "@angular/language-service": "~10.0.3",
}
```

```shell
 ng s
```

## 🔥 Exception or Error
<pre><code>
ERROR in The Angular Compiler requires TypeScript >=3.9.2 and <4.0.0 but 3.8.3 was found instead.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.2
Node: 12.15.0
OS: win32 x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      9.2.1
@angular/cli                      10.0.2
@ngtools/webpack                  10.0.2
@schematics/angular               8.3.26
@schematics/update                0.1000.2
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
Can you please provide the full contents of the package.json?

**Comment by muhammedMoussa** [comment]
I mentioned only updated packages. but it's okay:

```json
{
  "name": "",
  "version": "1.1.7",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "npx jest",
    "clear-jest": "npx jest --clearCache",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "stage": "ng build --prod",
    "ng-high-memory": "node --max_old_space_size=6000 ./node_modules/@angular/cli/bin/ng",
    "compodoc": "compodoc -p tsconfig.json -s --theme laravel",
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^10.0.3",
    "@angular/cdk": "^9.1.2",
    "@angular/common": "~10.0.3",
    "@angular/compiler": "~10.0.3",
    "@angular/core": "~10.0.3",
    "@angular/forms": "~10.0.3",
    "@angular/platform-browser": "~10.0.3",
    "@angular/platform-browser-dynamic": "~10.0.3",
    "@angular/router": "~10.0.3",
    "@aspnet/signalr": "^1.1.2",
    "@devexpress/analytics-core": "^19.2.7",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^9.1.0",
    "@ngrx/store": "^9.1.0",
    "@ngrx/store-devtools": "^9.1.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "angular-auth-oidc-client": "^10.0.15",
    "angular2-uuid": "^1.1.1",
    "browserslist": "^4.11.1",
    "color": "^3.1.2",
    "devexpress-dashboard": "^19.2.7",
    "devextreme": "^19.2.7",
    "devextreme-angular": "19.2.7",
    "globalize": "^1.5.0",
    "jest-html-reporter": "^3.0.0",
    "moment": "^2.24.0",
    "ng-zorro-antd": "^9.0.2",
    "oidc-client": "^1.10.1",
    "paix": "^1.0.0",
    "rxjs": "~6.5.5",
    "subsink": "^1.0.1",
    "tslib": "^1.11.1",
    "xlsx": "^0.15.6",
    "zone.js": "~0.10.3"
  },
  "browsers": [
    "last 2 version"
  ],
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1000.2",
    "@angular/cli": "^10.0.2",
    "@angular/compiler-cli": "~10.0.3",
    "@angular/language-service": "~10.0.3",
    "@compodoc/compodoc": "^1.1.11",
    "@types/jest": "^25.2.1",
    "@types/node": "~13.13.0",
    "codelyzer": "^5.2.2",
    "devextreme-cli": "latest",
    "devextreme-themebuilder": "latest",
    "jest": "^25.4.0",
    "jest-preset-angular": "^8.1.3",
    "ts-node": "~8.8.2",
    "tslint": "~6.1.1",
    "typescript": "^3.8.3",
    "typescript-tslint-plugin": "^0.5.5"
  }
}


```

**Comment by alan-agius4** [comment]
Hi @muhammedMoussa, the problem here is that in your `package.json`, your `typescript` version is `^3.8.3`. Semantically it does match what the `@angular/compiler-cli` requires which is `3.9.x`, and thus the update will not be performed.

The problem here likely is that while the version is `^3.8.3` which current would install `3.9.6`, you have a lock file which is unmaintained and typescript is still locked to a `3.8.x` version.

In general it's recommend to use `~` for typescript versions, because minor versions can contain breaking changes and the Angular framework only support newer TypeScript versions in majors and minors.

This would also resolve the issue you are experiencing.
