### ISSUE TITLE
preloadingStrategy  not working

### ISSUE THREAD

**Issue by akshata456** [angular/angular-cli#18230]
🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
I used preloadingStrategy in app-routes.like this way
 imports: [RouterModule.forRoot(routes, { preloadingStrategy: AppCustomPreloader })]
but it not works.

## 🔬 Minimal Reproduction
add preloadingStrategy in app routes under imports

## 🔥 Exception or Error
No modules get preloaded.

## 🌍 Your Environment
Angular CLI: 7.2.0
Node: 10.21.0
OS: win32 x64
Angular: 7.1.4

**Comment by alan-agius4** [comment]
Hi, @akshata456, 

it’s unclear what `AppCustomPreloader` consists off. 

Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

Note: Angular 7 is no longer supported see: https://angular.io/guide/releases#support-policy-and-schedule

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
