### ISSUE TITLE
firebase error angular 10

### ISSUE THREAD

**Issue by Suhabavan** [angular/angular-cli#18249]
Please help me to resolve this issue :

WARNING in E:\AngularUI\chatbot\src\app\login\login.component.ts depends on 'firebase'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in E:\AngularUI\chatbot\src\app\app.component.ts depends on 'firebase/app'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in E:\AngularUI\chatbot\node_modules\firebase\dist\index.cjs.js depends on '@firebase/remote-config'. CommonJS or AMD dependencies 
can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in E:\AngularUI\chatbot\node_modules\firebase\dist\index.cjs.js depends on '@firebase/app'. CommonJS or AMD dependencies can cause 
optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in E:\AngularUI\chatbot\node_modules\firebase\dist\index.cjs.js depends on '@firebase/performance'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in E:\AngularUI\chatbot\node_modules\firebase\dist\index.cjs.js depends on '@firebase/functions'. CommonJS or AMD dependencies can 
cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in E:\AngularUI\chatbot\node_modules\firebase\dist\index.cjs.js depends on '@firebase/firestore'. CommonJS or AMD dependencies can 
cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in E:\AngularUI\chatbot\node_modules\firebase\dist\index.cjs.js depends on '@firebase/database'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.

**Comment by alan-agius4** [comment]
The problem here is that `firebase` species the `browser` field, however this is pointed to the CJS version of the library instead of ESM.  The `browser` field takes precedence over the `module` field. 

To suppress the warning you can read the guide linked in the warning message itself, however the proper fix would be to raise the issue with the Firebase team to change the `browser` field to use `ESM`.
