### ISSUE TITLE
Using "--prod" with "--environment=xxx" doesn't bundle

### ISSUE THREAD

**Issue by Kizmar** [angular/angular-cli#1824]
Is there a way to force a non-prod environment to bundle?

When I use "ng serve --prod", the browser's network tab shows that it's downloading a small handful of bundled files - works as I'd expect. 

If I try "ng serve --prod --environment=dev" for the env variables, it's not bundling (downloads many many files).

[Edit] I guess what I'm really looking for is bundling and the "uglifying and tree-shaking functionality". I'd like to optionally apply that when building any environment.

**Comment by deebloo** [comment]
did you try this? ```ng build --target=production --environment=dev``` not sure if that will give you different results or not. also what version of the cli are you using?

**Comment by filipesilva** [comment]
@Kizmar please answer the questions in the new issue template. It's hard to help you without that information.

**Comment by hansl** [comment]
Closing this as obsolete.
