### ISSUE TITLE
karma dependency not found - Cannot find name 'sinon'.

### ISSUE THREAD

**Issue by delasteve** [angular/angular-cli#1825]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OS X El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Used `npm link` and hash `0cdd3c3a7`
```
angular-cli: local (v1.0.0-beta.11-webpack.2, branch: master)
node: 6.4.0
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Create app via CLI

`npm install sinon@next karma-sinon --save-dev`

`npm install @types/sinon --save-dev`

Code changes:
`karma.conf.js`:
```js
    frameworks: [
      ...
      'sinon'
    ],
    plugins: [
      ...
      require('karma-sinon')
    ],
```

`bar.component.spec.ts`
```typescript
describe('Component: Bar', () => {
  const foo = sinon.stub();
  console.log(foo.threw()); // false (works!)
});
```

4. The log given by the failure. Normally this include a stack trace and some more information.
```
ERROR in [default] /Users/stephencavaliere/Development/foo/src/app/+bar/bar.component.spec.ts:16:14
Cannot find name 'sinon'.
```

5. Mention any other details that might be useful.

`sinon` is actually found in tests and works just fine. A warning appears before the karma run when I type `ng test`.

Using VSCode 1.4.0

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Odd, having @types/sinon should be enough. I'll look into it.

**Comment by ShawInnes** [comment]
I had the same problem which I solved by adding the following to my tests.js.  It's a bit of a workaround at least, sinve the @types/sinon should work.

```
// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare var __karma__: any;

// Workaround for Sinon typing not working
declare var sinon: any;
```

**Comment by delasteve** [comment]
@ShawInnes: Yeah that's what I did to get rid of the warnings for now. Hopefully, @filipesilva and gang find a better long term solution.

**Comment by filipesilva** [comment]
Hm... I looked into it and I think it's an issue with the Sinon typings actually: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/sinon/sinon.d.ts

If you check them out, you'll see there's no `declare var sinon` (lowercase) or anything of the sort. Thus it's true that even with these typings, the name `sinon` cannot be found. 

What seems to work instead is to just do `import { stub } from 'sinon';`. I fooled around with the typings and could verify that they were being used for the import. You can test it yourself by changing

```
    interface SinonStatic {
        stub: SinonStubStatic;
    }
```

to 

```
    interface SinonStatic {
        stub: SinonStubStatic;
        superStub: SinonStubStatic;
    }
```

Now  `import { stub } from 'sinon';` shows no TS error, but if you remove `superStub: SinonStubStatic;` then you get squiggly red lines in your editor.

Much more than that I can't say tbh, I don't use sinon.

**Comment by filipesilva** [comment]
Here's some more info about how these kind of typings work: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-umd-module-definitions

**Comment by filipesilva** [comment]
@cnishina pointed me the right way - you should just do this instead:
```
import * as sinon from 'sinon';
const foo = sinon.stub();
```

It's much easier to follow `sinon` usage this way.
