### ISSUE TITLE
Error encountered using happypack

### ISSUE THREAD

**Issue by webxmsj** [angular/angular-cli#18260]
I want to use happypack to improve the compilation speed. I encountered the following error conditions. Is there any relevant solution?

![image](https://user-images.githubusercontent.com/40289489/87514976-b403a100-c6ad-11ea-83c4-1df22f7fd5ef.png)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
