### ISSUE TITLE
A library is packaged in a way a service part of the injected module in a library is added after the module.

### ISSUE THREAD

**Issue by smlee** [angular/angular-cli#18262]
# 🐞 bug report

### Is this a regression?

No it was fine in the past. It was fine with Angular 7 and 8. This is happening since updating to Angular 9.

### Description

Getting: Cannot access 'someService' before initialization error when I the updated library.

I went and checked the build file and I am able to get it running with no issue when I moved the service anywhere before the module that is injected to.

I moved around the order of the services since it was only affecting the providers. Once I re-build the library it's another provider that gets added at the end of the package file. 

Is this an issue with ng-packagr?

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.9
Node: 10.18.0
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.9
@angular-devkit/core         9.1.9
@angular-devkit/schematics   9.1.9
@schematics/angular          9.1.9
@schematics/update           0.901.9
rxjs                         6.5.4
</code></pre>

ng-packagr 9.1.5

**Comment by alan-agius4** [comment]
Hi @smlee, without a reproduction it would be hard to identify the issue. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by smlee** [comment]
I think I fixed the building issue by refactoring the services that were considered circular to have their own entry points.

**Comment by alan-agius4** [comment]
Closing as it seems that the issue has been resolved by the user.
