### ISSUE TITLE
I need to run the ng app into a /vdir. How do I configure that?

### ISSUE THREAD

**Issue by lnaie** [angular/angular-cli#1826]
Hi,
My ng app will be hosted into a virtual dir in production. Also I want to run it the same in the dev environment.
I'm seeing the header script dependencies (injected into index.html) are being magically generated. Probably the answer is related to that. How do I get to configure that plugin (HtmlWebpackPlugin)?

I haven't seen anything about that, please advise.

**Comment by filipesilva** [comment]
What is it exactly that you want to configure?

**Comment by lnaie** [comment]
I want the scripts that are being injected magically by webpack in the index.html to be prefixed with "/vdir/"
How do I achieve that? :)

**Comment by filipesilva** [comment]
Likely it would be enough to set the base tag. See https://github.com/angular/angular-cli#base-tag-handling-in-indexhtml.

We use this for github pages deployment, for instance, which is a similar scenario.
