### ISSUE TITLE
I encountered an error when using happypack，TypeError: Cannot read property ‘_ngToolsWebpackPluginInstance’ of undefined

### ISSUE THREAD

**Issue by webxmsj** [angular/angular-cli#18268]
I encountered an error when using happypack，TypeError: Cannot read property ‘_ngToolsWebpackPluginInstance’ of undefined

**Comment by alan-agius4** [comment]
Hi @webxmsj, 

Happypack is not officially supported by the Angular tooling team and there are no plans to support it, even more considering it is in maintenance mode.

Please be aware that the Angular tooling team doesn't provide support for custom Webpack configuration or setups. Support requests should be posted on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
