### ISSUE TITLE
ng serve should not rebuild / recompile when only add / remove / modify comments that not change the code logic and references.

### ISSUE THREAD

**Issue by x-strong** [angular/angular-cli#18277]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
ng serve should not rebuild / recompile when add / remove / modify comments that not change the code logic and references.

### Describe the solution you'd like
ng serve should rebuild / recompile only if the file change makes code logic or references change.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
Not yet.

**Comment by alan-agius4** [comment]
Hi @x-strong, 

Thanks for this feature request. I don't think that Angular CLI should handle changes in comments in any differently. Here are some reasons why:

- To identify if the change effects only a comment AST parsing would still needs to be performed.
- Some comments do change the outputted code. Certain tools use special magic comments, such as Autoprefixer and Terser.
- As a developer one would expect that any all changes are reflected in the final bundle, thus for correctness it should also be updated.
- If something like this had to be implemented, it should probably be at a higher bundler level.
