### ISSUE TITLE
Cannot find module '@schematics/angular/utility/project'

### ISSUE THREAD

**Issue by oneclickwebstudio** [angular/angular-cli#18298]
Hello!

Catching error while running command `ng g component example`

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Working well

## 🔬 Minimal Reproduction

 
After updating to `"@schematics/angular": "^10.0.3"`  command `ng g component example` breaks
in `"@schematics/angular": "^9.1.11"` everything is OK.

## 🔥 Exception or Error
<pre><code>An unhandled exception occurred: Cannot find module '@schematics/angular/utility/project'
Require stack:
- .../node_modules/@ionic/angular-toolkit/schematics/component/index.js
- .../node_modules/@angular-devkit/schematics/tools/export-ref.js
- .../node_modules/@angular-devkit/schematics/tools/index.js
- .../node_modules/@angular/cli/utilities/json-schema.js
- .../node_modules/@angular/cli/models/command-runner.js
- .../node_modules/@angular/cli/lib/cli/index.js
- .../.npm-global/lib/node_modules/@angular/cli/lib/init.js
- .../.npm-global/lib/node_modules/@angular/cli/bin/ng
See "/private/var/folders/2k/vlq4_8v57_98l_9rvxwmj1km0000gn/T/ng-aqdfcZ/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 10.0.3
Node: 12.16.3
OS: darwin x64

Angular: 10.0.4
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1000.3 (cli-only)
@angular-devkit/build-angular   0.1000.3
@angular-devkit/core            10.0.3
@angular-devkit/schematics      10.0.3
@angular/cli                    10.0.3
@schematics/angular             10.0.3
@schematics/update              0.1000.3 (cli-only)
rxjs                            6.6.0
typescript                      3.9.7

ionic -v
6.10.1
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, this seems a problem with `@ionic/angular-toolkit`. In version 10, the project utils private APIs have been removed.

Kindly file an issue in ionic’s issue tracker.
