### ISSUE TITLE
`ng test` should accept argument for karma configuration file

### ISSUE THREAD

**Issue by traviskaufman** [angular/angular-cli#183]
As discussed with @hansl, currently there is no way to specify the location of `karma.conf.js` when running `ng test`. We should allow this to be specified so that angular-cli can be used with projects that do not place config files in their default locations.

**Comment by hansl** [comment]
Actually the solution would not be argument but a metadata with sensible default. I'll work on this.

**Comment by Brocco** [comment]
Does this make a lot of sense given that the file is generated by the CLI and will therefore be in a consistent location?

**Comment by hansl** [comment]
Projects might want to move it (e.g. Material2 has it in `test/`). There should be a way to set its location in the `package.json`.

**Comment by Brocco** [comment]
Point taken.
Then I agree we should store the location within `package.json`
Is there a scenario where we would need to support multiple configuration files? I'd prefer to cover all those scenarios up front rather than have multiple ways to store the config info.

**Comment by hansl** [comment]
Yeah I'm not 100% sure about multiple test files, but we can revisit.

**Comment by riscie** [comment]
The option `--config-file` seems to already be there. Or is it not yet implemented?

` --config-file (String)
    aliases: -c <value>, -cf <value>`

**Comment by wadewalker25** [comment]
Although, riscie, those aliases/options do not appear to work.

**Comment by krotscheck** [comment]
An example scenario for multiple test configs:
- karma.conf.js - Regular unit tests, run in Phantom or whatever browsers are passed in.
- karma.browserstack.conf.js - CI-run automated tests against all browsers in our preflight and postflight jobs.

**Comment by Brocco** [comment]
This is something I can take a look at over the next few days.

**Comment by FJLopezGarcia** [comment]
Any update?

**Comment by PascalPrecht** [comment]
@hansl @Brocco I'm also all for possible multiple config files. I know, I'm always coming up with very specific use cases, but that's all I have :D 

As we're using angular-cli in our trainings, we want to be able to run tests normally using

```
$ ng test
```

But then there's another testsuite for us training that we want to run to verify our labs are working. So then something like
```
$ ng test --config-file=foo.config.ts
```
Would be really need.

@krotscheck 's scenario also seems very valid to me.

**Comment by lohiarahul** [comment]
> An example scenario for multiple test configs:
> 
> karma.conf.js - Regular unit tests, run in Phantom or whatever browsers are passed in.
> karma.browserstack.conf.js - CI-run automated tests against all browsers in our preflight and postflight jobs.

Is this possible still?

**Comment by kuncevic** [comment]
@lohiarahul `ng t --config configname.js`

**Comment by lohiarahul** [comment]
> @lohiarahul ng t --config configname.js

the build doesn't bundle up the "Alternative Config File"  and the CI process fails. Any way to include the other file in the bundle?

**Comment by kuncevic** [comment]
@lohiarahul why want to bundle karma config ?

**Comment by AngularTx** [comment]
i have 2 featured modules, which I would like to unit test seperately . 

I am using angular-cli , angular 5. 

The build will be one , where 2 applications will be shown via the lazy loading . 

I want to have seperate testing for these modules. Can some one guide me how to do it ?
