### ISSUE TITLE
Request upgrade ajv version: Synk Failing - Prototype Pollution - High Severity

### ISSUE THREAD

**Issue by samuelkavin** [angular/angular-cli#18308]
Currently, we are having some security warning in synk. It's requesting upgrade ajv version of angular-devkit to **6.12.3** from **6.12.0**

Current ajv version by angular-devkit
https://github.com/angular/angular-cli/blob/d5847623d9ebc7f4f7d116370baf06c74b50e56e/package.json#L126

Error message

@angular-devkit/core@9.0.1
Prototype Pollution [High Severity][https://snyk.io/vuln/SNYK-JS-AJV-584908] in ajv@6.10.2

introduced by @angular-devkit/core@9.0.7 > ajv@6.10.2 and 1 other path(s)

This issue was fixed in versions: 6.12.3

**Comment by alan-agius4** [comment]
Closed via the above referenced PRs.
