### ISSUE TITLE
styles.sass:1:0: Unknown word

### ISSUE THREAD

**Issue by jegesh** [angular/angular-cli#18309]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

It seems to be. This bug was initially reported in [#13550](https://github.com/angular/angular-cli/issues/13550), but was later resolved.  I started using the cli at v10.0.3 and immediately experienced this issue.

### Description

See [#13550](https://github.com/angular/angular-cli/issues/13550)

## 🔬 Minimal Reproduction
Starting a new angular project with `ng new ...` command and chosing the SASS option reproduces this issue.

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/styles.sass (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--13-3!./node_modules/sass-loader/dist/cjs.js??ref--13-4!./src/styles.sass)
Module build failed (from ./node_modules/resolve-url-loader/index.js):
Error: resolve-url-loader: CSS error
  file:///Users/yaakov/Development/workspace/telespam/telespam-frontend/tg4u-ng/src/styles.sass:1:0: Unknown word
You tried to parse Sass with the standard CSS parser; try again with the postcss-sass parser
  You tried to parse Sass with the standard CSS parser; try again with the postcss-sass parser
    at encodeError (/Users/yaakov/Development/workspace/telespam/telespam-frontend/tg4u-ng/node_modules/resolve-url-loader/index.js:219:12)
    at onFailure (/Users/yaakov/Development/workspace/telespam/telespam-frontend/tg4u-ng/node_modules/resolve-url-loader/index.js:176:14)

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.3
Node: 12.18.2
OS: darwin x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.3
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cli                      10.0.3
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
@jegesh, the reported error doesn't seem to be related to #13550. I tried to reproduce this locally, however I didn't manage to replicate this on an `ng new` application.

Can you setup a minimal repro please? Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by jegesh** [comment]
Sorry I didn't have time to set up the reproduction
