### ISSUE TITLE
error Unexpected end of JSON input while parsing near '...^6.0.0"},"dist":{"int' on ng add @ng-bootstrap/schematics 

### ISSUE THREAD

**Issue by prashant-sinha** [angular/angular-cli#18300]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular-cli/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by prashant-sinha** [comment]
While adding Bootstrap, 
Command: ng add @ng-bootstrap/schematics

Error: An unhandled exception occurred: npm ERR! Unexpected end of JSON input while parsing near '...^6.0.0"},"dist":{"int'

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
