### ISSUE TITLE
Production build doesn't hook up JS and JS.MAP files

### ISSUE THREAD

**Issue by slavaspirit** [angular/angular-cli#1832]
Tried to build prod version with `ng build --prod` but faced with an issue - it hooked up `css` and `css.map` files, that wrote in my `angular-cli-build.js`, but ignored `.js` and `.js.map` files at all exept defaults, such as `zone.js`, etc. 
When I execute `ng build` - all works fine. It hooked up all files, include `js` and `js.map`.

My `angular-cli-build.js`:

```
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(ts|js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      'intl/**/*.+(js|js.map)',
      'list.js/dist/list.min.js',
      'moment/moment.js',
      'pikaday/pikaday.js',
      'pikaday/css/*.+(css)',
      'material-design-lite/*.+(css|js|js.map|css.map)'
    ]
  });
};
```

**Comment by filipesilva** [comment]
Prod mode bundles according to your SystemJS config. If there are missing files there, it's probably because there's not listed in that config as a global library.

The difficulty in correctly configuring everything for bundling was part of the reason that lead us to move to webpack (#1455). You can upgrade using these instructions: https://github.com/angular/angular-cli#webpack-preview-release-update

Bear in mind though, that the latest webpack release doesn't yet allow you to import global libraries but will soon.

**Comment by textbook** [comment]
@filipesilva until it *does* allow you to import global libraries, what's the fix for this? We are seeing JS files being left out of `dist` despite including them in `angular-cli-build.js`:

```
var Angular2App = require('angular-cli/lib/broccoli/angular2-app');

module.exports = function(defaults) {
  return new Angular2App(defaults, {
    vendorNpmFiles: [
      ...,
      'primeng/**/*.+(js|js.map)',
      'primeui/**/*.+(min.js|css|png)'
    ]
  });
};
```

and `system-config.js` (both `map` and `packages`):

```
/***********************************************************************************************
 * User Configuration.
 **********************************************************************************************/
/** Map relative paths to URLs. */
const map: any = {
  'primeng': 'vendor/primeng',
  'primeui': 'vendor/primeui'
};

/** User packages configuration. */
const packages: any = {
  'primeng': { defaultExtension: 'js' },
  'primeui': { defaultExtension: 'js' }
};
```

**Comment by filipesilva** [comment]
We've now released webpack to latest, including this functionality. See https://github.com/angular/angular-cli#webpack-update to update.
