### ISSUE TITLE
Observed the slowness while using --profile option with prod build.

### ISSUE THREAD

**Issue by rahultokase** [angular/angular-cli#18329]
# 🐞 Bug report
Hi I have observed the performance issue while using --profile option. The --profile is taking more time for me while using with ngbuild --prod option.
I coudl see internally we are using SMP plugin for profiling. 
When  I run the command without --profile it executes faster.
### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @rahultokase, some form of slowness is expected when profiling, Profiling doesn't come free.

Can you please fill in the template and provide the output of `ng version`, and also more details such as by how much is the build slower?

Thanks.

**Comment by alan-agius4** [comment]
Closing as reporter didn’t get back to us.

If the problem persist please file a new issue. Than you.
