### ISSUE TITLE
Removing hash from Webpack bundle

### ISSUE THREAD

**Issue by Trevald** [angular/angular-cli#1833]
Is there a way to modify settings for the webpack bundles to remove the hash from the js-files and the script-tags generated in index.html?

**Comment by robertbaker** [comment]
those are used for cache breaking. You should set the headers to have long cache times and keep the hashes :)

**Comment by Trevald** [comment]
I know, and I would love to keep 'em. But I'm delivering my bundle to a back-end developer who doesn't use the generated index.html but rather only wants to replace the old bundle with a new one without needing to change the hash.

**Comment by deebloo** [comment]
Could you just write a script to do that for you?

**Comment by Trevald** [comment]
@deebloo You could probably write a gulp-script that does that but it seems to me that that would be having two steps in the process that could be reduced to zero steps, adding hash and removing has. Instead of just not adding hash.

Thanks for the tip but the question remains, even though apparently badly put, is it possible to change the bundle process to not adding hash rather than is there a way to remvove hash.

I like the simplicity of the bundle process with CLI, I need to do absolutely nothing. But here I am in a situation wanting to do something and it just seems to me that this little change should be an ever so simple task.

**Comment by filipesilva** [comment]
If you use `ng build` without the `--prod` flag you shouldn't get any hashes.

**Comment by bryanjjohnson** [comment]
Does --prod only add the hash and use the environments.prod file? If not, then this isn't a good solution, because they would want the other advantages of using --prod

**Comment by kiddy2910** [comment]
Any idea or option to remove hash? I have the same issue.

**Comment by bryanjjohnson** [comment]
We ended up adding these to our build script:
ng build -prod
mv dist/main.*.bundle.js dist/main.bundle.js
mv dist/main.*.bundle.js.gz dist/main.bundle.js.gz
mv dist/styles.*.bundle.js dist/styles.bundle.js
mv dist/styles.*.bundle.js.gz dist/styles.bundle.js.gz

**Comment by Krisa** [comment]
Thanks, that's helpful @bryanjjohnson . 

@filipesilva / @deebloo : removing `--prod` has for sure not the same effect... We all have a specific and valid reason why we want to make a prod bundling, but don't want the hash. That shall be definitely an option in the angular-cli. Or maybe you shall allow to provide a Webpack config which could overwrite some default option. I see other issues which are raised, simply because the current configuration possibilities are to strict. Which is a paradox, because Webpack is actually extremely flexible in itself.

Please reopen the issue and consider this feature request.

**Comment by filipesilva** [comment]
Hash removal option being tracked in https://github.com/angular/angular-cli/issues/1833

**Comment by HCNOX** [comment]
Any update on if this will be implemented? I would also need to prevent the hash generation in the name for similar reasons

**Comment by FerGabPereira** [comment]
any updates?

**Comment by filipesilva** [comment]
Sorry I linked the wrong issue, here is where it's being tracked: https://github.com/angular/angular-cli/issues/2774

**Comment by dmesa** [comment]
Closed on https://github.com/angular/angular-cli/pull/3885
try using:
ng build --prod --output-hashing none

**Comment by SSAT** [comment]
ng build --prod -output-hasing media/none/bundles

**output-hashing**
--output-hashing (aliases: -oh)

Define the output filename cache-busting hashing mode.

Values: none, all, media, bundles

[https://github.com/angular/angular-cli/wiki/build](url)

**Comment by WebStew** [comment]
Is it possible to add the hashing value as a url parameter? eg :

<script src="main.bundle.js?v=8ce0183eeaa599bafb462"></script>

That way the cache busting stays intact we have the benefit of static named files?
