### ISSUE TITLE
Update from version 9.1 to 10.0 fails on migrations (angular.json)

### ISSUE THREAD

**Issue by woznyp** [angular/angular-cli#18330]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure. Previously I was able to migrate my project from v8 to v9 without problems.

### Description

While running ng update @angular/core @angular/cli process fails on migrations.

In migration-collection.json I've noticed that there are 5 migrations left:
![image](https://user-images.githubusercontent.com/4609997/88156440-b7e17700-cc09-11ea-9c12-5e227feb566c.png)

Below I pasted powershell output:
<pre><code>
> ng "update" "@angular/core" "@angular/cli"

The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Using package manager: 'npm'
Collecting installed dependencies...
Found 60 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular/cli @ "10.0.3" (was "9.1.8")...
    Updating package.json with dependency @angular/core @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1000.3" (was "0.901.8")...
    Updating package.json with dependency @angular/language-service @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/compiler-cli @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/localize @ "10.0.4" (was "9.1.12")...
    Updating package.json with dependency @angular/animations @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/compiler @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/common @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/forms @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/router @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/platform-browser @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "10.0.4" (was "9.1.11")...
    Updating package.json with dependency typescript @ "3.9.7" (was "3.8.3")...
UPDATE package.json (5207 bytes)
√ Packages installed successfully.
** Executing migrations of package '@angular/cli' **

> Update Browserslist configuration file name to '.browserslistrc' from deprecated 'browserslist'.
RENAME browserslist => .browserslistrc
  Migration completed.

> Update tslint to version 6 and adjust rules to maintain existing behavior.
UPDATE package.json (5208 bytes)
UPDATE tslint.json (3130 bytes)
  Migration completed.

> Remove deprecated 'es5BrowserSupport' browser builder option.
  The inclusion for ES5 polyfills will be determined from the browsers listed in the browserslist configuration.
UPDATE angular.json (12484 bytes)
  Migration completed.

> Replace deprecated and removed 'styleext' and 'spec' Angular schematic options with 'style' and 'skipTests', respectively.
  Migration completed.

> Remove deprecated options from 'angular.json' that are no longer present in v10.
× Migration failed: Cannot read property 'startsWith' of undefined
  See "C:\*********\angular-errors.log" for further details.
</code></pre>

update-angular-config.js fails in line 26
![image](https://user-images.githubusercontent.com/4609997/88155986-1b1ed980-cc09-11ea-921a-fc9182657b25.png)

## 🔬 Minimal Reproduction
Run update from version 9.1 to version 10.

angular.json

<pre><code>
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "newProjectRoot": "projects",
    "projects": {
      "wep": {
        "root": "",
        "sourceRoot": "src",
        "projectType": "application",
        "prefix": "wep",
        "schematics": {
          "@schematics/angular:component": {
            "style": "scss",
            "changeDetection": "OnPush"
          }
        },
        "architect": {
          "build": {
            "builder": "@angular-devkit/build-angular:browser",
            "options": {
              "aot": true,
              "extractLicenses": true,
              "outputPath": "dist/wep",
              "index": "src/index.html",
              "main": "src/main.ts",
              "polyfills": "src/polyfills.ts",
              "tsConfig": "tsconfig.app.json",
              "assets": [
                "src/favicon.ico",
                "src/assets"
              ],
              "styles": [
                "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
                "src/styles/styles.scss",
                "src/styles/theming.scss"
              ],
              "scripts": [],
              "es5BrowserSupport": true,
              "stylePreprocessorOptions": {
                "includePaths": [
                  "src/styles"
                ]
              }
            },
            "configurations": {
              "dev": {
                "fileReplacements": [
                  {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.dev.ts"
                  }
                ],
                "optimization": true,
                "outputHashing": "all",
                "sourceMap": false,
                "extractCss": true,
                "namedChunks": false,
                "aot": true,
                "extractLicenses": true,
                "vendorChunk": false,
                "buildOptimizer": true,
                "budgets": [
                  {
                    "type": "initial",
                    "maximumWarning": "2mb",
                    "maximumError": "5mb"
                  },
                  {
                    "type": "anyComponentStyle",
                    "maximumWarning": "6kb"
                  }
                ]
              },
              "dev-local": {
                "fileReplacements": [
                  {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.dev-local.ts"
                  }
                ]
              },
              "dev-remote": {
                "fileReplacements": [
                  {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.dev-remote.ts"
                  }
                ]
              },
              "production": {
                "fileReplacements": [
                  {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.prod.ts"
                  },
                  {
                    "replace": "src/assets/CKFinderScripts/config.js",
                    "with": "src/assets/CKFinderScripts/envs/config.prd.js"
                  }
                ],
                "optimization": true,
                "outputHashing": "all",
                "sourceMap": false,
                "extractCss": true,
                "namedChunks": false,
                "aot": true,
                "extractLicenses": true,
                "vendorChunk": false,
                "buildOptimizer": true,
                "budgets": [
                  {
                    "type": "initial",
                    "maximumWarning": "2mb",
                    "maximumError": "5mb"
                  },
                  {
                    "type": "anyComponentStyle",
                    "maximumWarning": "6kb"
                  }
                ]
              },
              "production-local": {
                "fileReplacements": [
                  {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.prod-local.ts"
                  },
                  {
                    "replace": "src/assets/CKFinderScripts/config.js",
                    "with": "src/assets/CKFinderScripts/envs/config.prd.js"
                  }
                ]
              },
              "production-remote": {
                "fileReplacements": [
                  {
                    "replace": "src/environments/environment.ts",
                    "with": "src/environments/environment.prod-remote.ts"
                  },
                  {
                    "replace": "src/assets/CKFinderScripts/config.js",
                    "with": "src/assets/CKFinderScripts/envs/config.prd.js"
                  }
                ]
              }
            }
          },
          "serve": {
            "builder": "@angular-devkit/build-angular:dev-server",
            "options": {
              "browserTarget": "wep:build",
              "proxyConfig": "src/proxy/proxy-local.conf.js",
              "open": true
            },
            "configurations": {
              "dev": {
                "browserTarget": "wep:build:dev"
              },
              "dev-local": {
                "browserTarget": "wep:build:dev-local",
                "proxyConfig": "src/proxy/proxy-local.conf.js"
              },
              "dev-remote": {
                "browserTarget": "wep:build:dev-remote"
              },
              "production": {
                "browserTarget": "wep:build:production"
              },
              "production-local": {
                "browserTarget": "wep:build:production-local",
                "proxyConfig": "src/proxy/proxy-local.conf.js"
              },
              "production-remote": {
                "browserTarget": "wep:build:production-remote"
              }
            }
          },
          "extract-i18n": {
            "builder": "@angular-devkit/build-angular:extract-i18n",
            "options": {
              "browserTarget": "wep:build"
            }
          },
          "test": {
            "builder": "@angular-devkit/build-angular:karma",
            "options": {
              "main": "src/test.ts",
              "polyfills": "src/polyfills.ts",
              "tsConfig": "tsconfig.spec.json",
              "karmaConfig": "karma.conf.js",
              "styles": [
                "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
                "src/styles/styles.scss",
                "src/styles/theming.scss"
              ],
              "scripts": [],
              "assets": [
                "src/favicon.ico",
                "src/assets"
              ],
              "stylePreprocessorOptions": {
                "includePaths": [
                  "src/styles"
                ]
              }
            }
          },
          "lint": {
            "builder": "@angular-devkit/build-angular:tslint",
            "options": {
              "tsConfig": [
                "tsconfig.app.json",
                "tsconfig.spec.json"
              ],
              "exclude": [
                "**/node_modules/**"
              ]
            }
          }
        }
      },
      "wep-e2e": {
        "root": "e2e/",
        "projectType": "application",
        "prefix": "",
        "architect": {
          "e2e": {
            "options": {},
            "configurations": {}
          },
          "lint": {
            "builder": "@angular-devkit/build-angular:tslint",
            "options": {
              "tsConfig": "e2e/cypress/tsconfig.json",
              "exclude": [
                "**/node_modules/**"
              ]
            }
          }
        }
      }
    },
    "defaultProject": "wep"
  }
  
</code></pre>

I cannot publish package.json - private project.

## 🔥 Exception or Error
<pre><code>
Migration failed: Cannot read property 'startsWith' of undefined

</code></pre>

## 🌍 Your Environment
<pre><code>
node 12.18.2
Windows 10
powershell
</code></pre>

**Comment by alan-agius4** [comment]
@woznyp, the problem here is that in your `e2e` section of the `wep-e2e` application, you are not defining a `builder`.

From the contents of this section, I am guessing you don’t have a `wep-e2e` in your project, in which case you can delete the entire section.

**Comment by woznyp** [comment]
@alan-agius4 you were right, thank you; it seems that was a leftover; 

I wonder if there is a way to validate angular.json file any time (before starting the update, because otherwise rollback is needed)?

**Comment by alan-agius4** [comment]
@woznyp, yes,. in future we should be validating the `angular.json` when reading.
