### ISSUE TITLE
Missing/Bad Dependency for @angular/pwa 0.901.12

### ISSUE THREAD

**Issue by TenFourTechnologies** [angular/angular-cli#18334]
#17613 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes, 0.901.03 (or possibly newer - leveraging semantic versioning)

### Description

package.json Excerpt:
 "@angular/pwa": "^0.901.03",

Semantic versioning leveraging 0.901.12 (LTS)

Build yields following error:
npm ERR! notarget No matching version found for @schematics/angular@9.1.12
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

## 🔬 Minimal Reproduction
include  "@angular/pwa": "^0.901.03" in package.json angular project.

## 🔥 Exception or Error
npm ERR! notarget No matching version found for @schematics/angular@9.1.12
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.20
Node: 10.15.3
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cdk                      8.2.3
@angular/cli                      8.3.20
@angular/material                 8.2.3
@angular/pwa                      0.901.3
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.5.4
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Most likely this was an interment problem while releasing the new version.

From the NPM page we can see that the mentioned version is available https://www.npmjs.com/package/@schematics/angular/v/9.1.12
