### ISSUE TITLE
Stop leaking pathnames in generated files

### ISSUE THREAD

**Issue by h908714124** [angular/angular-cli#18363]
After `ng build`, some of the generated files contain folder names from my computer.
Something like this:

````js
module.exports = __webpack_require__(/*! /home/my/username/my/projects/something/src/main.ts */"./src/main.ts");
````

I've noticed this in the following files:

* styles.js
* polyfill.js
* main.js

For developers that wish to remain anonymous, this can be an important issue. Is there some flag to prevent this? Also it would be nice to either have this off by default, or have a hint in the generated comment about how to turn it off.

**Comment by alan-agius4** [comment]
@h908714124 these should only be included during development, which shouldn’t be of a concern.

Are you seeing something different?

**Comment by h908714124** [comment]
@alan-agius4 I see, it doesn't happen with `ng build --prod`. Nevertheless I wouldn't want this as a default setting.

**Comment by alan-agius4** [comment]
Hi @h908714124, 

This is also the default experience offered by Webpack which is used under the hood. See: https://webpack.js.org/configuration/output/#outputpathinfo.

As mentioned previously the paths are only visible during development builds which shouldn't result in any security concern, and hence there are no plans to add the option to disable the paths are part of our public API.

If you still wish to disable this durning development, you can use a 3rd party builder which extends the Angular CLI such as https://github.com/just-jeb/angular-builders and https://github.com/manfredsteyer/ngx-build-plus.

**Comment by h908714124** [comment]
How would one disable this in webpack, so that it is disabled even in dev profile?

**Comment by alan-agius4** [comment]
You can read more here: https://webpack.js.org/configuration/output/#outputpathinfo.

**Comment by h908714124** [comment]
I've added a file called `webpack.config.js` in the root folder, with the following contents:
````json
module.exports = {
  output: {
    pathinfo: true
  }
};
````
However that had no effect. You've posted a link and then closed the ticket, but I still don't  know how to disable the leaking of path names in "development builds" (which are the default builds that you get with a simple `ng build`).

**Comment by alan-agius4** [comment]
@h908714124, you need to use a 3rd party builder which is not supported by the Angular tooling team.

There are several builders out there, In my previous comment I linked 2 of the most popular. Each of which have different installation and configuration process, kindly follow their readme documentation as they do explain how to extend the Angular CLI webpack configuration.

**Comment by h908714124** [comment]
Sorry to keep nagging, but you said that Webpack was used under the hood, which seems to support this. But then shouldn't it be possible to make this configurable, without having to install third-party software?

**Comment by alan-agius4** [comment]
Hi @h908714124, we only expose essential functionality of the bundler, in this case Webpack. This gives us more flexibility and have the possibility of changing the bundler without breaking the API.
