### ISSUE TITLE
Angular multiple projects

### ISSUE THREAD

**Issue by nijakanthan** [angular/angular-cli#18379]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Hi,
Is it possible to generate multiple angular project in below folder structure

> my-workspace
> > |---- prjojects
> > > |---- my-parent-pject
> > > |---- layouts
> > > > |---- my-first-layout
> > > > |---- my-second-layout
...

Tried the below command to generate
`ng g application layouts/abc`
but getting an error

```
### Project name "layouts/abc" is not valid. New project names must start with a letter, and must contain only alphanumeric characters or dashes. When adding a dash the segment after the dash must also start with a letter.
layouts/abc
```

Help me to achieve this.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hi @nijakanthan,

The above mentioned folder structure is not possible via the default Angular CLI schematics. To achieve the above, you'd need to create a custom schematics which extend the default one.

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
