### ISSUE TITLE
Build with baseHref removes opening tag of the next HTML element

### ISSUE THREAD

**Issue by zygimantas** [angular/angular-cli#18381]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure.

### Description

ng build produces invalid HTML

## 🔬 Minimal Reproduction

1. Add `<base href="/" /></head>` to index.html. **There should be no space between closing and opening tags** (I run HTML minification before the build step)
2. Use i18n (I am not sure if this is necessary)
3. Run `ng build --localize`

## 🔥 Exception or Error
<pre>

Updated index.html has: &lt;base href="/app/en/">/head>
instead of &lt;base href="/app/en/">&lt;/head>
</pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.4
Node: 14.4.0
OS: win32 x64

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cli                      10.0.4
@angular/pwa                      0.1000.4
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.6.0
typescript                        3.9.7
webpack                           4.44.0
</code></pre>

**Anything else relevant?**

**Comment by Ayudh** [comment]
@alan-agius4 raised a PR for this. https://github.com/angular/angular-cli/pull/18607
