### ISSUE TITLE
Error: Invalid JSON character when running ng update 

### ISSUE THREAD

**Issue by Hich2013** [angular/angular-cli#18382]
## Versions
<pre><code>

Angular CLI: 9.0.0
Node: 13.7.0
OS: win32 x64

Angular: <error>
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.28
@angular-devkit/build-angular      0.803.29
@angular-devkit/build-ng-packagr   0.803.28
@angular-devkit/build-optimizer    0.803.29
@angular-devkit/build-webpack      0.803.29
@angular-devkit/core               8.3.28
@angular-devkit/schematics         10.0.4
@angular/cdk                       8.2.3
@ngtools/webpack                   8.3.29
@schematics/angular                9.0.0 (cli-only)
@schematics/update                 0.900.0 (cli-only)
ng-packagr                         5.7.0
rxjs                               6.5.4
typescript                         3.5.3
webpack                            4.39.2

</code></pre>

## Reproduce steps
  * ng update @angular/core@9 @angular/cli@9

## Observed Behavior
`> Angular Workspace migration.
  Update an Angular CLI workspace to version 9.
├ù Migration failed: Invalid JSON character: "┬á" at 2:26.
  See "C:\Users\HR56764\AppData\Local\Temp\1\ng-fTBjUV\angular-errors.log" for further details`

In angular-errors.log I get the following at the top of the stack:
`Invalid JSON character: " " at 2:26.`

## 🔥 Exception or Error
<pre><code>
[error] Error: Invalid JSON character: " " at 2:26.
 at _readValue (C:\***\node_modules\@schematics\angular\node_modules\@angular-devkit\core\src\json\parser.js:677:19)
 at _readProperty (C:\***\node_modules\@schematics\angular\node_modules\@angular-devkit\core\src\json\parser.js:491:19)
 at _readObject (C:\***\node_modules\@schematics\angular\node_modules\@angular-devkit\core\src\json\parser.js:524:30)
 at _readValue (C:\***\node_modules\@schematics\angular\node_modules\@angular-devkit\core\src\json\parser.js:674:22)
</code></pre>

## 🌍 Details that might be useful
The file that is responsible for this error turns out to be the following: tsconfig.app.json
<pre><code>
{
  "extends": "../tsconfig.json",
  "experimentalDecorators": true,
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "types": [
      "jest"
    ]
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts",
    "wallabyTest.ts"
  ]
}
</code></pre>

I do not see any formatting issue with this file however, and its encoding is UTF8.

**Comment by alan-agius4** [comment]
Hi @Hich2013, can you try using a support Node.Js version? Either 10.13+, 12+ or 14+? If the problem persists can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
