### ISSUE TITLE
SourceMap broken for Angular 2 Source

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#1838]
This is similar issue like ##1790. #1790 fixed my problem with debuging of application sourcing, but when I try to debug Angular sources, I see there is no sourceMap at all. As angular ~/ are just javascript files. 

Any idea? Do I need to turn of something to get AngularJS TS into my chrome so I can debug ?

Thanks, 
Frank

**Comment by filipesilva** [comment]
@TheLarkInn this seems related to us disabling source maps for node_modules. Can you confirm?

**Comment by TheLarkInn** [comment]
Yeah we are ignoring any node modules source maps for now. When we add the ability to access the webpack config from the add on system they can customize this

**Comment by filipesilva** [comment]
Closing as there isn't much to do here for now.

**Comment by deli6z** [comment]
are there plans to support source maps for angular2 source files so typescript can be actually debugged in the browser console ?

**Comment by deli6z** [comment]
Any update on this?
