### ISSUE TITLE
Use esbuild for ts/js bundling

### ISSUE THREAD

**Issue by sp90** [angular/angular-cli#18395]
# 🚀 feature request

### Relevant Package
This would be relevant for all packages and projects since it's +100x faster than webpack so the whole community would benefit from this improvement

### Description
Many angular applications grow in the very big codebases and many teams spend days in improving the build, but there is a limitation with the current build tools for angular. Using a faster bundler we could save so much time for all the teams using angular.

**A conservative example of improvement impact**
```
// Developers using angular
X = 5

// Builds per day 
Y = 50     

// Current average build time
Z1 = 5      

// Potential average build time
Z2 = 0.5  

X * Y * Z1 = 1250s/day - (+250000s/year = ~70 hours/year)
X * Y * Z2 = 125s/day - (+25000s/year = ~7 hours/year)

Saved time per year: ~63 hours

This would save a common frontend team 63 hours a year, given they work 200 days a year where many teams work way more.
```

### Describe the solution you'd like
Replace webpack with esbuild

### Describe alternatives you've considered
Using webpack in collaboration with esbuild this could be an option since esbuild don't have the same feature set

**Comment by sod** [comment]
Yes. I tested https://github.com/vitejs/vite - which uses esbuild - and the build speed is astonishing.

But the angular compiler uses the typescript diagnostics for dependency injection and Annotations for code generation. So it's not just transpiling from typescript to javascript.

Maybe esbuild could replace terser & babel for the production builds. But that would only attack a fraction of the actual build time. So in the grand scheme not a order magnitude improvement sadly.

**Comment by alan-agius4** [comment]
Hi @sod and @sp90,

Thanks for the request and interest in this.

We are following closely the development of ESBuild, Rollup, Webpack and other bundlers. 

That being said, we are not planning to move away from Webpack yet. At least not in the near future. In fact currently we actively working on adding support for the next major version of Webpack. 

Let’s come back to this in the future.

Thanks again 😊
