### ISSUE TITLE
npm audit fix wrong version to @angular-devkit/build-angular angular 9

### ISSUE THREAD

**Issue by FilipeMazzon** [angular/angular-cli#18390]
angular 9. 

### Description

when you use npm audit fix, using angular 9, you should go to version 0.901.10 instead they go to 0.1000.4 which it's only compatible with angular 10. 

## 🔬 Minimal Reproduction
example use npm audit fix when version are ~0.901.2 will to 0.1000.4 instead of 0.901.10

**Comment by clydin** [comment]
This is unfortunately a defect within npm itself.  The issue can be tracked here: https://github.com/npm/cli/issues/726

**Comment by alan-agius4** [comment]
Closing as this is not actionable by the Angular tooling team.
