### ISSUE TITLE
Migration from v5 to v6 does not work as stated in the Angular update guide

### ISSUE THREAD

**Issue by alcon678** [angular/angular-cli#18404]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
It could be

### Description
Following the guide (https://update.angular.io/#5.2:6.1) the command ng update @angular/cli@6 only updates the package.json (it does not migrate the schema nor anything else).

The only output is UPDATE package.json (xxxx bytes) and the install logs 

## 🔬 Minimal Reproduction
npm i -g @angular/cli@1.7.1
ng new test-update
cd test-update
npm install @angular/cli@6
ng update @angular/cli@6

## 🔥 Exception or Error
<pre><code>

None
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 1.7.4
Node: 10.16.0
OS: win32 x64
Angular: 5.1.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.3
@angular/cli: 1.7.4
@angular/material-moment-adapter: 5.2.4
@angular/material: 5.2.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 10.0.4
@angular-devkit/schematics: 10.0.4
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
@schematics/update: 0.1000.4
typescript: 2.5.3
webpack-concat-plugin: 2.4.2
webpack-dev-server: 2.10.0
webpack-zip-files-plugin: 1.0.0
webpack: 3.11.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @alcon678, 

Can you try the following:
```
npm i @angular/cli@latest --no-save
ng update @angular/cli --migrate-only --from=1 --to=6
```

Kindly note that Angular 5 and 6 are no longer supported. For a comprehensive list of supported Angular versions please see: https://angular.io/guide/releases#support-policy-and-schedule

**Comment by alcon678** [comment]
Hi @alan-agius4 
Thank you for your help, following those steps made it work!
Now we can update all the way up to Angular 10

Thanks! ☺
