### ISSUE TITLE
What does --suppress-sizes do? 

### ISSUE THREAD

**Issue by hisham** [angular/angular-cli#1841]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
El Capitan 10.11.6 

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.4.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng build --suppress-sizes=true

5. Mention any other details that might be useful.

The resulting build from 'ng build --prod' produces unknown provider errors for me. 'ng build' as is works but the resulting main.bundle.js is 3mb in size. Trying to reduce this size so saw --suppress-sizes option but this option doesn't seem to make a difference in the size of main.bundle.js.

**Comment by filipesilva** [comment]
That's an unsupported option that still appears listed in some placed. https://github.com/angular/angular-cli/issues/1807 is tracking the cleaning of these unsupported commands.
