### ISSUE TITLE
ERROR in Cannot read property 'isFile' of undefined

### ISSUE THREAD

**Issue by oappiaha** [angular/angular-cli#18426]
Running my angular project and after updating to the latest version I am getting this error: 

ERROR in Cannot read property 'isFile' of undefined

In the terminal we see:

Refused to load the image 'http://localhost:4200/favicon.ico' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

I've deleted favicon.ico but still get this error. Any suggestions?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
