### ISSUE TITLE
Cannot find module 'serve-static'

### ISSUE THREAD

**Issue by haniDjebbi** [angular/angular-cli#18423]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [x] serve

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.2

### Description

 i tried to ceate a new project using ng new command then i run it by ng serve --open but i got this problem about the serve-static module i dont know why but what am sure about that  my old projects still working fine i tried to fix it by changing the package.json file and it didnt work is this problem caused by my env or its a bug because its an empty project i did 0 changes on it 

## 🔬 Minimal Reproduction

ng new app 
ng serve --open

## 🔥 Exception or Error
<pre><code>

An unhandled exception occurred: Cannot find module 'serve-static'
Require stack:
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\express\lib\express.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\express\index.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\webpack-dev-server\lib\Server.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular-devkit\build-webpack\src\index.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular-devkit\architect\node\index.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular\cli\models\architect-command.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular\cli\commands\serve-impl.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular-devkit\schematics\tools\export-ref.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular-devkit\schematics\tools\index.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular\cli\utilities\json-schema.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular\cli\models\command-runner.js
- D:\MyWorkSpace\AngularFullCalendar\AngCalendar\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\Lenovo\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\Lenovo\AppData\Local\Temp\ng-JYTliC\angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.5
Node: 12.13.1
Angular: 10.0.7
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@haniDjebbi, which packager manager are you using? I wasn't able to reproduce this issue.

**Comment by haniDjebbi** [comment]
@alan-agius4 ,am using npm V6.14.6

**Comment by alan-agius4** [comment]
Hi @haniDjebbi, 

This doesn't like a bug in Angular CLI, likely it's more of a local issue.

I suggest to try to cleanup the NPM cache, removing the node_modules and lock file and try again.
```
npm cache clean --force
rm -rf node_modules package-lock.json
npm i
```

If you are using an NPM proxy, try to disable it.
