### ISSUE TITLE
Webpack release not addressing unit test?

### ISSUE THREAD

**Issue by EnigmaticCode** [angular/angular-cli#1842]
1. Windows 7

2. 
Angular CLI
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.2
os: win32 x64

Node
v6.2.2

3. Just do "ng test"

4. Uncaught ReferenceError: System is not defined
at C:/apex2/config/karma-test-shim.js:33

**Comment by deebloo** [comment]
can you post the code for your test entry? also did you follow the full guide for transitioning to the new webpack based cli?

**Comment by EnigmaticCode** [comment]
You can actually reproduce this with an entirely new project.  Just do ng new then ng test.

**Comment by EnigmaticCode** [comment]
Unable to reproduce now.
