### ISSUE TITLE
Not able to create new angular project on ppc64le

### ISSUE THREAD

**Issue by narkhedek3** [angular/angular-cli#18436]
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 
I am trying to create a new angular project but while installing packages it gives segmentation fault.
# version details:
Angular CLI: 10.0.5
Node: 12.18.3
NPM: 6.14.6
OS: linux ppc64

## 🔬 Minimal Reproduction

 ng new my-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE my-app/README.md (1023 bytes)
CREATE my-app/.editorconfig (274 bytes)
CREATE my-app/.gitignore (631 bytes)
CREATE my-app/angular.json (3566 bytes)
CREATE my-app/package.json (1249 bytes)
CREATE my-app/tsconfig.base.json (458 bytes)
CREATE my-app/tsconfig.json (426 bytes)
CREATE my-app/tslint.json (3184 bytes)
CREATE my-app/.browserslistrc (853 bytes)
CREATE my-app/karma.conf.js (1018 bytes)
CREATE my-app/tsconfig.app.json (292 bytes)
CREATE my-app/tsconfig.spec.json (338 bytes)
CREATE my-app/src/favicon.ico (948 bytes)
CREATE my-app/src/index.html (291 bytes)
CREATE my-app/src/main.ts (372 bytes)
CREATE my-app/src/polyfills.ts (2835 bytes)
CREATE my-app/src/styles.css (80 bytes)
CREATE my-app/src/test.ts (753 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (662 bytes)
CREATE my-app/src/app/app-routing.module.ts (245 bytes)
CREATE my-app/src/app/app.module.ts (393 bytes)
CREATE my-app/src/app/app.component.css (0 bytes)
CREATE my-app/src/app/app.component.html (25757 bytes)
CREATE my-app/src/app/app.component.spec.ts (1059 bytes)
CREATE my-app/src/app/app.component.ts (210 bytes)
CREATE my-app/e2e/protractor.conf.js (869 bytes)
CREATE my-app/e2e/tsconfig.json (299 bytes)
CREATE my-app/e2e/src/app.e2e-spec.ts (639 bytes)
CREATE my-app/e2e/src/app.po.ts (301 bytes)
⠼ Installing packages...Segmentation fault (core dumped)

## 🔥 Exception or Error
<pre><code>
Segmentation fault (core dumped)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.5
Node: 12.18.3
OS: linux ppc64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.5
@angular-devkit/core         10.0.5
@angular-devkit/schematics   10.0.5
@schematics/angular          10.0.5
@schematics/update           0.1000.5
rxjs                         6.5.5

</code></pre>

**Anything else relevant?**

The issue is related to ppc64le architecture. On linux x86 architecture it is creating a new angular project.

**Comment by alan-agius4** [comment]
Hi @narkhedek3, 

It seems that the `npm install` is failing. If you try to run `npm install` in that directory does it fail in the same way?

Might be useful: https://stackoverflow.com/questions/56050531/after-upgrading-node-segmentation-fault-core-dumped-error-shows-up-how-can

**Comment by narkhedek3** [comment]
Hi @alan-agius4 
Thank you for the quick response.

I have tried npm install in project directory it is giving the same error [segmentation fault].

And I have tried to copy an angular project created on x86 architecture to ppc64le then the project is not running continuously on the server. After some time server is closing because of segmentation fault

**Comment by alan-agius4** [comment]
> I have tried npm install in project directory it is giving the same error [segmentation fault]. 
This can be either an NPM issue or something with your setup. 

With regards to the error during the build, can you please provide a more detail logs? Unfortunately without logs we cannot investigate this issue.

Thanks.

**Comment by narkhedek3** [comment]
hi @alan-agius4 
Sorry for the inconvenience. Please see the following logs.


Following error is coming executing ng build:
``` properties
my-app]$ ng build
? Would you like to share anonymous usage data about this project with the Angular Team at
Google under Google’s Privacy Policy at https://policies.google.com/privacy? For more
details and how to change this setting, see http://angular.io/analytics. Yes

Thank you for sharing anonymous usage data. Would you change your mind, the following
command will disable this feature entirely:

    ng analytics project off

An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'
Require stack:
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/index.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/models/architect-command.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/commands/build-impl.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/node_modules/@angular-devkit/schematics/tools/index.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/utilities/json-schema.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/models/command-runner.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/lib/cli/index.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/lib/init.js
- /home/parade/node/node-v12.18.3-linux-ppc64le/lib/node_modules/@angular/cli/bin/ng
See "/tmp/ng-SEe9Iv/angular-errors.log" for further details.
```
According to me, this error is because installing packages is failed
and @angular-devkit//build-angular is not installed.
So I have tried the following:
```properties
my-app]$ npm i @angular-devkit/build-angular
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
Segmentation fault (core dumped)ind-of: sill extract iferr@0.1.5
```

# 
```properties
my-app]$ npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
Segmentation fault (core dumped)ostcss-convert-values: sill tarball trying deep-equal@^1.0.1 by hash: sha512-y
```

**Comment by alan-agius4** [comment]
Hi again,

The first error is indeed because the package is not installed. However, seeing the errors afterwards it looks like `npm install` is always failing with the same error `Segmentation fault`. 

Unfortunately, at this stage it looks like more of an environment/NPM issue rather than an Angular CLI bug, which StackOverflow is in general a better place for such issues.
