### ISSUE TITLE
fix: tslint 

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#1844]
1. OS
  OS X 10.11.6 (El Capitan), but it is platform-independent

2. Versions.
  From master after issue #1823 was committed

3. Repro steps.
  If "no-shadowed-variable": true is added to tsconfig.json's rules.
  Run `npm run tslint`

4. The log given by the failure.

```log
addon/ng2/utilities/get-dependent-files.ts[50, 13]: Shadowed variable: 'node'
addon/ng2/utilities/get-dependent-files.ts[51, 11]: Shadowed variable: 'node'
packages/ast-tools/src/node.ts[24, 43]: Shadowed variable: 'node'
packages/ast-tools/src/route-utils.spec.ts[465, 13]: Shadowed variable: 'editedFile'
packages/ast-tools/src/route-utils.spec.ts[497, 13]: Shadowed variable: 'editedFile'
```

5. Mention any other details that might be useful.
IMHO, shadowed variables are an invitation for subtle bugs to come see us and remain invisible.

I vote for non-shadowed variable to be true rather than false.

**Comment by catull** [comment]
This can be fixed by either disabling tslint, or by renaming
  node         -> aNode
  editedFile -> editedFile2 (occurence in line 465)
  editedFile -> editedFile3 (occurence in line 497)

**Comment by filipesilva** [comment]
We talked about this internally when adding TS linting, and at the time decided that adding that rule wasn't really worth making the code less readable since we overall use a lot of function shorthand.
