### ISSUE TITLE
@angular-devkit/architect@0.1000.5' is not in the npm registry

### ISSUE THREAD

**Issue by idenisovs** [angular/angular-cli#18460]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] npm install @angular/cli
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

Every time I try to run `ng new app` or `npm install @angular/cli` I got the same error from NPM:

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@angular-devkit%2farchitect - Not found
```

## 🔬 Minimal Reproduction

Just run `ng new app` or `npm install @angular/cli`

## 🔥 Exception or Error
<pre><code>
$ sudo npm i @angular/cli -g
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@angular-devkit%2farchitect - Not found
npm ERR! 404
npm ERR! 404  '@angular-devkit/architect@0.1000.5' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@angular/cli'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.12
Node: 13.7.0
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.12
@angular-devkit/core         9.1.12
@angular-devkit/schematics   9.1.12
@schematics/angular          9.1.12
@schematics/update           0.901.12
rxjs                         6.5.4
</code></pre>

Tried also in dedicated server, located in different country, with the same result.

**Comment by cfi2017** [comment]
I'm running into the same issue: #18459

**Comment by idenisovs** [comment]
@cfi2017 Should I close mine? Made mine with 1 second difference. 😄

**Comment by cfi2017** [comment]
I think it's easier if we track the issue on one page. I'll close mine :)

**Comment by haep1** [comment]
Same issue here! :(

**Comment by ojemuyiwa** [comment]
Yeah, just broke my build as well. Will revert to older version for now

**Comment by maxamorim** [comment]
Same here, it broke my build a few minutes ago.

**Comment by haep1** [comment]
> Yeah, just broke my build as well. Will revert to older version for now
Do the older versions still work?

**Comment by cfi2017** [comment]
> > Yeah, just broke my build as well. Will revert to older version for now
> Do the older versions still work?
Angular CLI 9.1.12 fails to install for me - missing a different package. Same thing for v8.3.29.

**Comment by rafiek** [comment]
> > Yeah, just broke my build as well. Will revert to older version for now
> 
> Do the older versions still work?

I tried older versions, they don't work. Seems like the entire registry entries are removed.

**Comment by ojemuyiwa** [comment]
> > Yeah, just broke my build as well. Will revert to older version for now
> 
> Do the older versions still work?

naaa, something weird is going on hmmm...

**Comment by ipsjolly** [comment]
ng cli showing 404 for packages

now showing 

Not Found - GET https://registry.npmjs.org/@jsdevtools%2fcoverage-istanbul-loader - Not found

**Comment by cfi2017** [comment]
This might be an npm issue rather than an angular issue. Trying to install dependencies to build from source but @protobufjs/aspromise is now also missing.

**Comment by ojemuyiwa** [comment]
> This might be an npm issue rather than an angular issue. Trying to install dependencies to build from source but @protobufjs/aspromise is now also missing.

seems like it is, rxjs isn't being found either. we probably just need to wait till they resolve

**Comment by maxamorim** [comment]
https://github.com/npm/cli/issues/1624

> This might be an npm issue rather than an angular issue. Trying to install dependencies to build from source but @protobufjs/aspromise is now also missing.
> 
> https://status.npmjs.org/

Most likely: https://github.com/npm/cli/issues/1624

**Comment by DerPauli** [comment]
Is there any other public (safe) registry that you know of that hosts this package + dependencies ?

**Comment by neetsingh** [comment]
I am also facing the same issue getting error, while installing @angular/cli
![image](https://user-images.githubusercontent.com/16643679/89521452-296e1780-d7fd-11ea-9054-b6987fc329db.png)

**Comment by SaeedSoltoon** [comment]
> I am also facing the same issue getting error, while installing @angular/cli
> ![image](https://user-images.githubusercontent.com/16643679/89521452-296e1780-d7fd-11ea-9054-b6987fc329db.png)

same issue here.
![Screenshot from 2020-08-06 14-58-25](https://user-images.githubusercontent.com/4473680/89521814-6fbf7880-d7f5-11ea-97e8-747c19e85f62.png)

**Comment by ojemuyiwa** [comment]
resolved... all seems fine now

**Comment by SaeedSoltoon** [comment]
> resolved... all seems fine now

new issue with @yarnpkg/lockfile
![Screenshot from 2020-08-06 15-18-46](https://user-images.githubusercontent.com/4473680/89523523-3e947780-d7f8-11ea-9f94-856bb5060f10.png)

**Comment by neetsingh** [comment]
> > resolved... all seems fine now
> 
> new issue with @yarnpkg/lockfile
> ![Screenshot from 2020-08-06 15-18-46](https://user-images.githubusercontent.com/4473680/89523523-3e947780-d7f8-11ea-9f94-856bb5060f10.png)

![image](https://user-images.githubusercontent.com/16643679/89524101-9683ac00-d801-11ea-95e1-334bd56b773b.png)
Same issue here

**Comment by LucasMM85** [comment]
> > > resolved... all seems fine now
> > 
> > 
> > new issue with @yarnpkg/lockfile
> > ![Screenshot from 2020-08-06 15-18-46](https://user-images.githubusercontent.com/4473680/89523523-3e947780-d7f8-11ea-9f94-856bb5060f10.png)
> 
> ![image](https://user-images.githubusercontent.com/16643679/89524101-9683ac00-d801-11ea-95e1-334bd56b773b.png)
> Same issue here

Facing the same issue :(

**Comment by alan-agius4** [comment]
As it is mentioned above this is not an Angular issue, but rather NPM.

See: https://status.npmjs.org/

**Comment by neetsingh** [comment]
seems like issue 

> > > resolved... all seems fine now
> > 
> > 
> > new issue with @yarnpkg/lockfile
> > ![Screenshot from 2020-08-06 15-18-46](https://user-images.githubusercontent.com/4473680/89523523-3e947780-d7f8-11ea-9f94-856bb5060f10.png)
> 
> ![image](https://user-images.githubusercontent.com/16643679/89524101-9683ac00-d801-11ea-95e1-334bd56b773b.png)
> Same issue here

Seems like issue is resolved but getting another issue now , 

![image](https://user-images.githubusercontent.com/16643679/89526346-32fb7d80-d805-11ea-888b-1c5b96ccccfb.png)

**Comment by neetsingh** [comment]
> seems like issue
> 
> > > > resolved... all seems fine now
> > > 
> > > 
> > > new issue with @yarnpkg/lockfile
> > > ![Screenshot from 2020-08-06 15-18-46](https://user-images.githubusercontent.com/4473680/89523523-3e947780-d7f8-11ea-9f94-856bb5060f10.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16643679/89524101-9683ac00-d801-11ea-95e1-334bd56b773b.png)
> > Same issue here
> 
> Seems like issue is resolved but getting another issue now ,
> 
> ![image](https://user-images.githubusercontent.com/16643679/89526346-32fb7d80-d805-11ea-888b-1c5b96ccccfb.png)

Issue is fixed, successfully installed angular 
![image](https://user-images.githubusercontent.com/16643679/89526933-24fa2c80-d806-11ea-9de7-09fabc4364c9.png)

**Comment by ccit-spence** [comment]
Was able to install CLI successfully just now.  Appears NPM may be getting close to a fix.

**Comment by vasilevvasko** [comment]
<img width="603" alt="Screen Shot 2020-08-06 at 13 37 45" src="https://user-images.githubusercontent.com/48380280/89527768-2a497e00-d7ea-11ea-8f04-df678256e148.png">
 Try to install now, issue might be resolved.

**Comment by alan-agius4** [comment]
Issue appears to have been solved. https://status.npmjs.org
