### ISSUE TITLE
es6-shim.js:2350 Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by borntodesign** [angular/angular-cli#1849]
Mac OSX - Yosemite
ng --version

angular-cli: 1.0.0-beta.10
node: 6.1.0
os: darwin x64

I just updated to the new version of the CLI and when I launch the server the console logs this error and does not load the app.

Stack Trace

Uncaught RangeError: Maximum call stack size exceededPromise @ es6-shim.js:2350PromiseCapability @ es6-shim.js:2116resolve @ es6-shim.js:2506scheduleQueueDrain @ zone.js:447scheduleMicroTask @ zone.js:455ZoneDelegate.scheduleTask @ zone.js:339Zone.scheduleMicroTask @ zone.js:270scheduleResolveOrReject @ zone.js:569ZoneAwarePromise.then @ zone.js:644(anonymous function) @ es6-shim.js:2154
embed.js:22 Uncaught TypeError: Cannot read property 'appendChild' of nullk @ embed.js:22l @ embed.js:22h.toJSON @ embed.js:22b.loadEmbed @ embed.js:23(anonymous function) @ embed.js:23

**Comment by filipesilva** [comment]
Hm, really can't tell without looking at your app tbh. We're moving away from the build system in beta.10 to a new one in the webpack preview version, maybe that will help. See https://github.com/angular/angular-cli#webpack-preview-release-update

**Comment by borntodesign** [comment]
I updated to the latest version an I am having more problems than before. Is there any guides on switching from SystemJS to Webpack regarding angular-cli. I have so many errors now

**Comment by filipesilva** [comment]
@borntodesign there's a complete one now, see https://github.com/angular/angular-cli#webpack-update
