### ISSUE TITLE
Property 'baseHref' does not exist on type 'BrowserBuilderOptions'

### ISSUE THREAD

**Issue by artaommahe** [angular/angular-cli#18492]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Dunno

### Description

`BrowserBuilderOptions` interface does not contain `baseHref` option, so trying to set this field in schematic leads to an error.
https://github.com/angular/angular-cli/blob/c8915f42055b7fcefbafbcd64b06bbc6aecf778a/packages/schematics/angular/utility/workspace-models.ts#L48

## 🔬 Minimal Reproduction

In schematic code
```ts
import { ProjectType, WorkspaceProject } from '@schematics/angular/utility/workspace-models';

let someProject: WorkspaceProject<ProjectType.Application>;

someProject.architect.build.options.baseHref = `/smth/`;
```

## 🔥 Exception or Error
<pre><code>Property 'baseHref' does not exist on type 'BrowserBuilderOptions'.ts(2339)
</code></pre>

## 🌍 Your Environment
<pre><code>
PS D:\projects\skyeng\skyeng-frontend\tools> yarn ng version
yarn run v1.16.0
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0-next.4
Node: 12.18.1
OS: win32 x64

Angular: 9.1.12
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.0-next.4
@angular-devkit/build-optimizer   0.901.0-next.4
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.1.3
@angular/cli                      9.1.0-next.4
@angular/material                 9.1.3
@ngtools/webpack                  9.1.0-next.4
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0-next.4
@schematics/update                0.901.0-next.4
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @artaommahe, 

For the reporting this issue, however those are private APIs (hence you needed to deep-import) and are only meant to be used internally. 

To update the workspace configuration using the public API you need use the workspace reader and writer.

Example
```ts

import { virtualFs, workspaces } from '@angular-devkit/core';
import { Rule, Tree } from '@angular-devkit/schematics';

function createHost(tree: Tree): workspaces.WorkspaceHost {
  return {
    async readFile(path: string): Promise<string> {
      const data = tree.read(path);
      if (!data) {
        throw new Error('File not found.');
      }

      return virtualFs.fileBufferToString(data);
    },
    async writeFile(path: string, data: string): Promise<void> {
      return tree.overwrite(path, data);
    },
    async isDirectory(path: string): Promise<boolean> {
      // Approximate a directory check
      return !tree.exists(path) && tree.getDir(path).subfiles.length > 0;
    },
    async isFile(path: string): Promise<boolean> {
      return tree.exists(path);
    },
  };
}

function addBaseHrefRule(): Rule {
  return async tree => {
    const host = createHost(tree);
    const { workspace } = await workspaces.readWorkspace('/', host);

    const project = workspace.projects.get('my-app');
    if (!project) {
      throw new Error('my-app does not exist.');
    }

    const buildTarget = project.targets.get('build');
    if (!buildTarget) {
      throw new Error('build target does not exist.');
    }

    if (!buildTarget.options) {
      throw new Error('build target does have any options.');
    }

    buildTarget.options.baseHref = '/smth/';
    await workspaces.writeWorkspace(workspace, host);
  };
}
```
