### ISSUE TITLE
Fresh Install: Getting error: PKG was unexpected at this time. and then getDirectories() not implemented

### ISSUE THREAD

**Issue by jennyraj** [angular/angular-cli#1852]
1 OS? Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 10

2 Versions. Please run ng --version. If there's nothing outputted, please run
in a Terminal: node --version and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2

3 Repro steps. Was this an app that wasn't created using the CLI? What change did you
do on your code? etc.
got the latest version: 
"D:\Program Files (x86)\JetBrains\WebStorm 2016.2.2\bin\runnerw.exe" "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run-script build

angular-cli@1.0.0-beta.11-webpack.2 build E:\Temp_delete\angular-cli
*## > for PKG in packages/; do echo Building $PKG...; tsc -P $PKG; done

**## PKG was unexpected at this time.****

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run-script" "build"
npm ERR! node v6.4.0
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular-cli@1.0.0-beta.11-webpack.2 build: for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-cli@1.0.0-beta.11-webpack.2 build script 'for PKG in packages/; do echo Building $PKG...; tsc -P $PKG; done'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! for PKG in packages/; do echo Building $PKG...; tsc -P $PKG; done
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs angular-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls angular-cli
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR! E:\Temp_delete\angular-cli\npm-debug.log

Process finished with exit code 1

The log given by the failure. Normally this include a stack trace and some

more information.

So, switched to packages/ast-tools directory and ran "tsc -p ."
xx\angular-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.d.ts

Got an error about getDirectories()

## **Added getDirectories() like this,,
export declare abstract class DelegatingHost implements ts.CompilerHost {**
....
getDirectories(path: string): string[];

now it built successfully, I did a npm link and using it to generate project successfully.

5 Mention any other details that might be useful.

So, switched to packages/ast-tools directory and ran "tsc -p ."
xx\angular-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.d.ts

Got an error about getDirectories

Added getDirectories() like this,,
export declare abstract class DelegatingHost implements ts.CompilerHost {
....
getDirectories(path: string): string[];

**Comment by jjarrell50** [comment]
After I did change to the apps[0] business in angular-cli.json I get the same error on `ng build`. It was a working configuration.

**Comment by filipesilva** [comment]
Can't do anything with just a log and a short description. Please answer the questions in `Please provide us with the following information:`.

**Comment by jennyraj** [comment]
1. OS? Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
 windows 10

2. Versions. Please run ng --version. If there's nothing outputted, please run
in a Terminal: node --version and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
do on your code? etc.
 got the latest version: 
"D:\Program Files (x86)\JetBrains\WebStorm 2016.2.2\bin\runnerw.exe" "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run-script build

> angular-cli@1.0.0-beta.11-webpack.2 build E:\Temp_delete\angular-cli
**## > for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done
# 
**PKG was unexpected at this time.****
=============================
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "build"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular-cli@1.0.0-beta.11-webpack.2 build: `for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-cli@1.0.0-beta.11-webpack.2 build script 'for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Temp_delete\angular-cli\npm-debug.log

Process finished with exit code 1

The log given by the failure. Normally this include a stack trace and some
more information.
======================
So, switched to packages/ast-tools directory and ran "tsc -p ."
xx\angular-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.d.ts

Got an error about getDirectories

Added getDirectories() like this,,
export declare abstract class DelegatingHost implements ts.CompilerHost {
 ....
 getDirectories(path: string): string[];

now it built successfully, I did a npm link and using it to generate project successfully.

5 Mention any other details that might be useful.

So, switched to packages/ast-tools directory and ran "tsc -p ."
xx\angular-cli\node_modules\@angular\tsc-wrapped\src\compiler_host.d.ts

Got an error about getDirectories
============================

Added getDirectories() like this,,
export declare abstract class DelegatingHost implements ts.CompilerHost {
 ....
 getDirectories(path: string): string[];

**Comment by jennyraj** [comment]
After getting version .8  and some hacking, it is working now. 

Thanks!
