### ISSUE TITLE
Recent checkout from master (8c566caee55341bfd15e3cda764da5fcd434e941) does not build

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#1853]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?
   OS X 10.11.6 (El Capitan), this is platform-independent

2. Versions.
  build problem, not ng problem

3. Repro steps.
```shell
   git clone git@github.com:angular/angular-cli.git angular-cli.git
   cd angular-cli.git
   git log -n 1
   npm install
   npm run build
```

4. The log given by the failure. Normally this include a stack trace and some
```log
commit 8c566caee55341bfd15e3cda764da5fcd434e941
Author: Filipe Silva <filipematossilva@gmail.com>
Date:   Fri Aug 26 02:28:55 2016 +0100

    fix(build): copy dot files in assets

    Close #1758
    Close #1847

> angular-cli@1.0.0-beta.11-webpack.2 build angular-cli.git
> for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done

Building packages/ast-tools...
node_modules/@angular/tsc-wrapped/src/compiler_host.d.ts(6,31): error TS2420: Class 'DelegatingHost' incorrectly implements interface 'CompilerHost'.
  Property 'getDirectories' is missing in type 'DelegatingHost'.

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! angular-cli@1.0.0-beta.11-webpack.2 build: `for PKG in packages/*; do echo Building $PKG...; tsc -P $PKG; done`
npm ERR! Exit status 1
```

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by catull** [comment]
The problem is still there, after commit id 7f70095b7219de1071ce51044d402856bb1025c9.

**Comment by catull** [comment]
Upgrading to a more recent tsc-wrapper solves the problem temporarily.
This did the trick:

`npm` install https://github.com/angular/tsc-wrapped-builds/tarball/2.0.0-af63378 --save
`npm` run build

**Comment by catull** [comment]
Any idea when your fellow colleagues stabilise @angular/tsc-wrapped ?

**Comment by filipesilva** [comment]
Closing as obsolete (a lot has changed in the last 22 days).
