### ISSUE TITLE
Consider moving rxjs to patch version specification to allow significant deduplication in node_modules

### ISSUE THREAD

**Issue by msbit** [angular/angular-cli#18536]
# 🚀 Feature request

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When creating a new Angular app, the dependency spec for `rxjs` in the app's `package.json` is not exact (`~6.5.4` for `9.1.12` at this time). However, the dependency spec for `rxjs` for some Angular dependencies is exact (`6.5.4`) for at least:

  * `@angular-devkit/architect`
  * `@angular-devkit/build-webpack`
  * `@angular-devkit/core`
  * `@angular-devkit/schematics`
  * `@ngtools/webpack`
  * `@schematics/update`

This results in a situation where, due to NPM's conservation de-duplication, many copies of `rxjs` are installed into the `node_modules`. This is illustrated below:
 
```
$ ng --version
...
Angular CLI: 9.1.12
Node: 14.8.0
OS: darwin x64
...
$ ng new --routing false --style css new-app
...
✔ Packages installed successfully.
...
$ pushd new-app
...
$ npm ls rxjs
new-app@0.0.0 ...
├─┬ @angular-devkit/build-angular@0.901.12
│ ├─┬ @angular-devkit/architect@0.901.12
│ │ └── rxjs@6.5.4 
│ ├─┬ @angular-devkit/build-webpack@0.901.12
│ │ └── rxjs@6.5.4 
│ ├─┬ @angular-devkit/core@9.1.12
│ │ └── rxjs@6.5.4 
│ ├─┬ @ngtools/webpack@9.1.12
│ │ └── rxjs@6.5.4 
│ └── rxjs@6.5.4 
├─┬ @angular/cli@9.1.12
│ ├─┬ @angular-devkit/schematics@9.1.12
│ │ └── rxjs@6.5.4 
│ ├─┬ @schematics/update@0.901.12
│ │ └── rxjs@6.5.4 
│ └─┬ inquirer@7.1.0
│   └── rxjs@6.5.5  deduped
└── rxjs@6.5.5
$ find node_modules -name rxjs -type d | xargs du -sh
 17M	node_modules/@angular-devkit/core/node_modules/rxjs
 17M	node_modules/@angular-devkit/build-angular/node_modules/rxjs
 17M	node_modules/@angular-devkit/architect/node_modules/rxjs
 17M	node_modules/@angular-devkit/build-webpack/node_modules/rxjs
 17M	node_modules/@angular-devkit/schematics/node_modules/rxjs
 17M	node_modules/@schematics/update/node_modules/rxjs
 17M	node_modules/@ngtools/webpack/node_modules/rxjs
 17M	node_modules/rxjs
...
```

### Describe the solution you'd like

Change the `rxjs` dependency spec from `6.x.y` to `~6.x.y` in:

* https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/architect/package.json
* https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_webpack/package.json
* https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/package.json
* https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/schematics/package.json
* https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/package.json
* https://github.com/angular/angular-cli/blob/master/packages/schematics/update/package.json

etc

### Describe alternatives you've considered

Changing the dependency spec in the apps's`package.json` to an exact version (eg `6.5.4` in for `9.1.12`) allows the deduplication, but has the downside of not allowing `rxjs` to be upgraded with bugfixes etc:

```
$ npm ls rxjs
new-app@0.0.0 ...
├─┬ @angular-devkit/build-angular@0.901.12
│ ├─┬ @angular-devkit/architect@0.901.12
│ │ └── rxjs@6.5.4  deduped
│ ├─┬ @angular-devkit/build-webpack@0.901.12
│ │ └── rxjs@6.5.4  deduped
│ ├─┬ @angular-devkit/core@9.1.12
│ │ └── rxjs@6.5.4  deduped
│ ├─┬ @ngtools/webpack@9.1.12
│ │ └── rxjs@6.5.4  deduped
│ └── rxjs@6.5.4  deduped
├─┬ @angular/cli@9.1.12
│ ├─┬ @angular-devkit/schematics@9.1.12
│ │ └── rxjs@6.5.4  deduped
│ ├─┬ @schematics/update@0.901.12
│ │ └── rxjs@6.5.4  deduped
│ └─┬ inquirer@7.1.0
│   └── rxjs@6.5.4  deduped
└── rxjs@6.5.4
$ find node_modules -name rxjs -type d | xargs du -sh
 17M	node_modules/rxjs
...
```

**Comment by dgp1130** [comment]
In 10.1 (releasing soon), two of the packages you mentioned have RxJS removed:

* @ngtools/webpack
* @schematics/update

So that alone will remove up to 34MB of size.

Beyond that, the CLI dev dependency on RxJS is not intended to necessarily match the runtime dependency (which is user controlled anyways via a peer dep). These could be different versions or even different majors. These semvers just _happen_ to align a lot of the time, since every Angular minor will generally update to the latest RxJS. If you stay updated, misalignment should be rare.

From 10.0 (with `yarn`), there are three instances of RxJS, but only one from Angular itself:

```
yarn list v1.22.4
├─ codelyzer@6.0.0
│  └─ rxjs@6.6.2
├─ inquirer@7.1.0
│  └─ rxjs@6.6.2
└─ rxjs@6.5.5
```

From 10.1 (with `yarn`), there is actually just one RxJS:

```
├─┬ @angular-devkit/build-angular@0.1001.0-next.5
│ ├─┬ @angular-devkit/architect@0.1001.0-next.5
│ │ └── rxjs@6.6.2  deduped
│ ├─┬ @angular-devkit/build-webpack@0.1001.0-next.5
│ │ └── rxjs@6.6.2  deduped
│ ├─┬ @angular-devkit/core@10.1.0-next.5
│ │ └── rxjs@6.6.2  deduped
│ ├─┬ @ngtools/webpack@10.1.0-next.5
│ │ └── rxjs@6.6.2  deduped
│ └── rxjs@6.6.2  deduped
├─┬ @angular/cli@10.1.0-next.5
│ ├─┬ @angular-devkit/schematics@10.1.0-next.5
│ │ └── rxjs@6.6.2  deduped
│ ├─┬ @schematics/update@0.1001.0-next.5
│ │ └── rxjs@6.6.2  deduped
│ └─┬ inquirer@7.3.3
│   └── rxjs@6.6.2  deduped
├─┬ codelyzer@6.0.0
│ └── rxjs@6.6.2  deduped
└── rxjs@6.6.2
```

The duplication you're seeing is because RxJS has been updated since the version of Angular you are using `9.1`. Staying up to date with Angular is best way of staying consistent with dependencies like RxJS.

Since the CLI dependency and the application dependency represent two distinct uses, we don't think it makes sense to force the two semvers to be the same. They will likely diverge and then remerge over time, so there's nothing too actionable here.

**Comment by msbit** [comment]
Thanks for the update @dgp1130 

> In 10.1 (releasing soon), two of the packages you mentioned have RxJS removed

That will definitely help this case, so that's good to see.

> From 10.0 (with yarn)
> From 10.1 (with yarn)

A small point but the reason I'm bumping into this is due to our use of `npm`, which appears to have a more conservative de-duplication algorithm.

> From 10.1 (with yarn), there is actually just one RxJS

That's the case currently, but on release of `rxjs` `6.6.3` (or greater) these will diverge. As you made the point, these versions just happen to align at this point.

> Since the CLI dependency and the application dependency represent two distinct uses, we don't think it makes sense to force the two semvers to be the same.

I probably didn't make it clear, what I was proposing was modifying the dependency specification for the released packages (in particular `@angular-devkit/architect`, `@angular-devkit/build-webpack`, `@angular-devkit/core` and `@angular-devkit/schematics`) to allow `rxjs` to be resolved to a compatible patch version. So, with the specific example of `@angular-devkit/architect` at current `master` applying this kind of diff:

```
diff --git a/packages/angular_devkit/architect/package.json b/packages/angular_devkit/architect/package.json
index 09a54a5c3..9bf127a1e 100644
--- a/packages/angular_devkit/architect/package.json
+++ b/packages/angular_devkit/architect/package.json
@@ -7,7 +7,7 @@
   "typings": "src/index.d.ts",
   "dependencies": {
     "@angular-devkit/core": "0.0.0",
-    "rxjs": "6.6.2"
+    "rxjs": "~6.6.2"
   },
   "builders": "./builders/builders.json"
 }
```

With this, if the application provides a dependency spec for `rxjs` at the top-level that is resolvably compatible, there is a greater chance that this would be de-duplicated. If the application provides a incompatible dependency spec (eg `~6.5.0` vs the `~6.6.2` in this diff) then that's a decision they've made so additional copies of `rxjs` would be unavoidable and not surprising.

As I'm putting this together, and looking through the history for these files, I'm wondering whether all the exact direct dependencies could be modified to patch compatible semver specifications (in spirit reverting https://github.com/angular/angular-cli/commit/b8b36ba339534732cb951ea08446087b2fae25a3). As I see it, the trade-off is:

* additional copies of each dependency that can't be de-duplicated (across a lot of angular installs, so many additional copies in aggregate!)

vs

* the chance that a patch version update for one of these dependencies introduces a breaking change or bug (also across a lot of angular installs, but only when updating some packages manually)
