### ISSUE TITLE
Fails to find library aliases in unit tests after upgrading to Angular 10

### ISSUE THREAD

**Issue by hammadaries** [angular/angular-cli#18533]
Hi,
After upgrading to Angular 10, I am having issues running the libraries' unit tests.

I have two project libraries. For example
LibTest1
HeroTest2

HeroTest2 consumes LibTest1

Project tsconfig.json contains
```
{
    .......
    "baseUrl": "./",
     .....
    "paths": {
      "LibtTest1": [
        "dist/LibTest1"
      ],
      "LibTest1/*": [
        "dist/LibTest1/*"
      ],
      "HeroTest2": [
        "dist/HeroTest2"
      ],
      "HeroTest2/*": [
        "dist/HeroTest2/*"
      ]
    }
  }
}
```

Project library HeroTest2 tsconfig.lib.json contains
```
"
{
   extends": "../../tsconfig.json",
   .....
}
```

Project library HeroTest2 tsconfig.spec.json contains
```
"
{
   extends": "../../tsconfig.json",
   .....
}
```

Project library HeroTest2 package.json contains
```
{
   "name": "HeroTest2",
   .....
   "dependencies": {
    "LibTest1": "*",
    "tslib": "^2.0.0"
  },
  .....
}
```

I am importing LibTest1 exported modules in HeroTest2 as 
```
import {someModuleFromLibTest1} from 'LibTest1';
```

There are no issues when I build the libraries and run the app. HeroTest2 recognizes LibTest1 and builds fine. 

In unit tests of HeroTest2 , I have added the module from LibTest1
```
import {someModuleFromLibTest1} from 'LibTest1';
.....
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ .... ],
      imports: [...., someModuleFromLibTest1, ...]
    })
    .compileComponents();
  }));
....
```

Getting the following error when I run unit tests for HeroTest2 

```
Error: Unexpected value 'someModuleFromLibTest1' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
```

Any help would be appreciated.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
