### ISSUE TITLE
'Collection "@schematics/angular" cannot be resolved.' error on --list-schematics

### ISSUE THREAD

**Issue by appimpact** [angular/angular-cli#18548]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] schematics 

### Is this a regression?

This is the first time we are using this CLI.

### Description

--list-schematics is returning an error when trying to list all schematics available in @schematics/angular or @angular/material package.

However, schematics are working as expected when we use ng generate, i.e.:
ng g c test-component => generates new blank component
ng g @angular/material:table --name test-table => generates new material design table

Schematics CLI is installed globally with the following command:
npm install @angular-devkit/schematics-cli -g

## 🔥 Exception or Error
<pre><code>

C:\Tests\Schematics\app>schematics @schematics/angular: --list-schematics
Collection "@schematics/angular" cannot be resolved.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.6
Node: 14.5.0
OS: win32 x64

Angular: 10.0.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cdk                      10.1.3
@angular/cli                      10.0.6
@angular/flex-layout              10.0.0-beta.32
@angular/material                 10.1.3
@ngtools/webpack                  10.0.6
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Do you have `node_modules` installed in `C:\Tests\Schematics\app`?

Also, any reason why you are using both the Angular CLI and Schematics CLI?

**Comment by appimpact** [comment]
![image](https://user-images.githubusercontent.com/34662138/90332253-a0ed3500-dfbb-11ea-8589-bfef257f1e30.png)

All packages are installed.
ng generate is working correctly, so it is only --list-schematics that is not working.

Schematics CLI was installed to be able to use "schematics" from command prompt.
