### ISSUE TITLE
Deploying to Github Pages using CLI command fails  (1.0.0-beta.11-webpack.2)

### ISSUE THREAD

**Issue by gmanojisaac** [angular/angular-cli#1854]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
1.0.0-beta.11-webpack.2

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Created using CLI- ng new projectname

4. The log given by the failure. Normally this include a stack trace and some
   more information.
PS > ng github-pages:deploy
BuildingNo angular-cli-build.js found. Please see the transition guide: https://github.com/angular-cli/angular-cli/blob/master/TRANSITION.md#user-content-brocfile-transition.

5. Mention any other details that might be useful.
ng new projectname, cd projectname, npm install, ng build
git remote add origin https://github.com/gmanojisaac/angularrc5.git
ng github-pages:deploy
 shows the above error message.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by msaradjuk** [comment]
as a workaround you can try the following:
`ng build -prod`
`ng github-pages:deploy --skip-build`

**Comment by gmanojisaac** [comment]
For deploying :
Go to github.com, login and create a repository-testrepo
ng new project
cd project
npm install
ng build --prod
git status
git remote -v
git remote add origin https://github.com/gmanojisaac/testrepo.git
ng github-pages:deploy --skip-build
Logged in with github username/password.
Shows : Deployed! Visit https://gmanojisaac.github.io/myconsent/
But it is not deployed when i accessed the link.- shows **404 site not found**

**Comment by msaradjuk** [comment]
The script changes the `<base href"">` of your index.html. Therefore the name in your package.json must be the same as the name of your github project.

Try to change `"name": "myconsent"` to `"name": "testrepo"` in your package.json and then run `ng-build --prod`

The github-pages deploy command should then show you the link:
[https://gmanojisaac.github.io/testrepo/](url) 
which is the correct url to visit your github-page

**Comment by gmanojisaac** [comment]
Thanks msaradjuk,
I made sure Name in the package.json === name of git hub repository as mentioned by you.
And the application was deployed correctly in github and i was able to access the app using the deployed link now.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/1633/files#diff-a7ba0adbb6fe6918c418062849f4f412

**Comment by kksrini89** [comment]
@gmanojisaac I used the same commands as you did but one difference is that,

`> ng github-pages:deploy`

Now I am able to see my changes alive.
[kksrini89.github.io/ng2website](url)
