### ISSUE TITLE
Don't generate spec files by default?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#18560]
I'm pretty sure that if it were studied, 95% of Angular generated projects don't use the spec files and either end up deleting them manually or turning spec generation off.

Perhaps do a poll or something and see.  Personally I think it would be nice if these files were not generated by default.

**Comment by alan-agius4** [comment]
Hi @fireflysemantics,

Thanks for your request. We want to enable best practices by default and therefore to not generating spec files should be on opt-out bases.
