### ISSUE TITLE
Server side broken after upgrade from 1.0.0-beta.10 to 1.0.0-beta.11-webpack.2

### ISSUE THREAD

**Issue by eoodin** [angular/angular-cli#1857]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04.1 LTS

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
When using 1.0.0-beta.10, server side code is created by  ng generate sever xx, it worked well.
After upgrade to 1.0.0-beta.11-webpack.2, seems folder /server is no longer be read when running 'ng serve'

4. The log given by the failure. Normally this include a stack trace and some
   more information.

➜  shelf git:(master) ✗ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
 10% building modules 1/1 modules 0 active           
*
*
 NG Live Development Server is running on http://localhost:4200.
*
8558ms building modules                                                                   
48ms sealing
0ms optimizing 
0ms basic module optimization 
32ms module optimization
0ms advanced module optimization 
9ms basic chunk optimization        
1ms chunk optimization 
0ms advanced chunk optimization 
0ms module and chunk tree optimization 
91ms module reviving
2ms module order optimization 
4ms module id optimization 
5ms chunk reviving 
0ms chunk order optimization 
21ms chunk id optimization
30ms hashing
0ms module assets processing 
83ms chunk assets processing
5ms additional chunk assets processing 
0ms recording 
0ms additional asset processing 
211ms chunk asset optimization
1374ms asset optimization
63ms emitting
Hash: 3f11b18fa225fb8dc532
Version: webpack 2.1.0-beta.18
Time: 10554ms
              Asset     Size  Chunks             Chunk Names
     main.bundle.js  4.52 MB    0, 2  [emitted]  main
polyfills.bundle.js   233 kB    1, 2  [emitted]  polyfills
          inline.js  4.96 kB       2  [emitted]  inline
           main.map  5.24 MB    0, 2  [emitted]  main
      polyfills.map   291 kB    1, 2  [emitted]  polyfills
         inline.map  5.13 kB       2  [emitted]  inline
         index.html  1.66 kB          [emitted]  
    css-spinner.css  1.41 kB          [emitted]  
        favicon.ico    17 kB          [emitted]  
           spin.gif  31.6 kB          [emitted]  
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  3.63 kB       0       
webpack: bundle is now VALID.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We never really supported `ng generate server xx` in `angular-cli`, I suppose it was a `ember-cli` command that just kinda worked in `beta.10`. We do not support it anymore starting `beta.12`.

The best I can do is direct you to the proxy documentation PR: https://github.com/angular/angular-cli/pull/1896
