### ISSUE TITLE
resolve-url-loader in styles processing

### ISSUE THREAD

**Issue by MiroslavKral** [angular/angular-cli#18579]
# 🐞 Bug report

### Is this a regression?

In Angular CLI 10 resolve-url-loader was added into webpack styles processing pipeline which completely break resolution of relative paths from root directory. In Angular CLI 9 everythnig works as expected.

### Description

Webpack loaders in Angular CLI 9:
`[style-loader, css-loader, postcss-loader, stylus-loader]`

In our header component style file which is on path:
`app/components/header/header.component.styl`

This works in Angular CLI 9:

`background-image url('./assets/images/icons/logo.png')`

And assets folder is in standard Angular CLI location.

Webpack loaders in Angular CLI 10:
 `[style-loader, css-loader, postcss-loader, resolve-url-loader, stylus-loader]`

Error in Angular CLI 10:

ERROR in ./src/styles.styl (./node_modules/css-loader/dist/cjs.js??ref--16-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--16-3!./node_modules/s
tylus-loader??ref--16-4!./src/styles.styl)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: test-project\src\styles.styl:19595:26: Can't resolve './app/components/header/assets/images/icons/logo.png' in 'test-project\src'

## 🔬 Minimal Reproduction
Generate new project wiht Angular CLI 9 and Angular CLI 10 and use realtive url from project root in style file.

## 🔥 Exception or Error
<pre><code>
ERROR in ./src/styles.styl (./node_modules/css-loader/dist/cjs.js??ref--16-1!./node_modules/postcss-loader/src??embedded!./node_modules/resolve-url-loader??ref--16-3!./node_modules/s
tylus-loader??ref--16-4!./src/styles.styl)
Module Error (from ./node_modules/postcss-loader/src/index.js):
(Emitted value instead of an instance of Error) CssSyntaxError: test-project\src\styles.styl:19595:26: Can't resolve './app/components/header/assets/images/icons/logo.png' in 'test-project\src'
</code></pre>

## 🌍 Your Environment

**Anything else relevant?**
What is the best way, to use images in style files? It is not possible for us to change all URLs because we have hunders of images in our app. And it is not possible to use relative paths for our images because it is really frustrating.

There is no mention about this breaking change in Angular CLI 10 release: https://github.com/angular/angular-cli/releases/tag/v10.0.0

**Comment by alan-agius4** [comment]
Please see #18115, #18013, #18041 and #18043 for details and steps to resolve the issue.
