### ISSUE TITLE
Ivy workspace: <error>

### ISSUE THREAD

**Issue by almogyehuda** [angular/angular-cli#18587]
# 🐞 Bug report

- [ ] new
- [X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

After upgrading from Angular 7 to 8, 9, and finally 10 - ivy doesn't work in browser (trying to use the ng option etc)

and it gives me an error on `ng --version`

any idea?

Thanks.

![image](https://user-images.githubusercontent.com/48723217/90769125-67d4fd80-e2f8-11ea-8049-527da37cedda.png)

EDIT:

Same project, on version 9 (before the upgrade to 10)

![image](https://user-images.githubusercontent.com/48723217/90772072-d1efa180-e2fc-11ea-8f52-48790c6a996b.png)

**Comment by alan-agius4** [comment]
Likely one or more migrations didn’t run. Did you update using `ng update @angular/cli`?

Since you already update the node_modules, you can try `ng update @angular/cli -—migrateOnly —-from=9 -—to=10`

**Comment by almogyehuda** [comment]
> Likely one or more migrations didn’t run. Did you update using `ng update @angular/cli`?
> 
> Since you already update the node_modules, you can try `ng update @angular/cli -—migrateOnly —-from=9 -—to=10`

`Invalid tag name "—-from=9": Tags may not have any characters that encodeURIComponent encodes`

**Comment by almogyehuda** [comment]
> Likely one or more migrations didn’t run. Did you update using `ng update @angular/cli`?
> 
> Since you already update the node_modules, you can try `ng update @angular/cli -—migrateOnly —-from=9 -—to=10`

Thank you.
Seems like this step was missing in the original ng update that I ran.

But still, it looks like Ivy doesn't act the same as it was in angular 9 in dev mode.

![image](https://user-images.githubusercontent.com/48723217/90778798-be950400-e305-11ea-89b1-6f1e1fcbbebc.png)

**Comment by petebacondarwin** [comment]
It might be worth completely removing the `node_modules` folder and reinstalling. There is a chance that the packages need to be reprocessed by ngcc.

**Comment by almogyehuda** [comment]
> It might be worth completely removing the `node_modules` folder and reinstalling. There is a chance that the packages need to be reprocessed by ngcc.

Hey,
Thank you for your response.

I just finished this process by deleting the node_modules, npm i and build again - no luck.

still the same:

![image](https://user-images.githubusercontent.com/48723217/90787774-c062c580-e30d-11ea-8d34-8e8e095ce095.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by almogyehuda** [comment]
> Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
> 
> If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

Hey,
Invite you as collaborator to the minimal repro.

Please run 
`npm run start`
On browser, open localhost:4200/dist and try to call `ng` on console.
You will see that there's no access to the ng object with all Ivy options

Thanks.

**Comment by almogyehuda** [comment]
While playing with the repro, I found that when I set "optimization" to false, the ng object is working as expected with all the properties again:
![image](https://user-images.githubusercontent.com/48723217/91859818-8f6e8300-ec73-11ea-8f0e-0f7cc1ff114f.png)

But why is that? @alan-agius4 

Thanks.

**Comment by alan-agius4** [comment]
That’s because certain debugging features are removed when not in DevMode.

**Comment by almogyehuda** [comment]
> That’s because certain debugging features are removed when not in DevMode.
> […](#)

Running optimization without calling enableProd() state as dev mode?

**Comment by alan-agius4** [comment]
When enabling optimization the dev utils and deadcode will be removed. This is not related nor effected by `enableProd`.
