### ISSUE TITLE
CLI v10 Failed to decode downloaded font (OTS parsing error: incorrect entrySelector for table directory) 

### ISSUE THREAD

**Issue by billyjov** [angular/angular-cli#18580]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.1.0

### Description

 

Angular CLI 10 doest not parse custom font correctly.

## 🔬 Minimal Reproduction

- `ng new appTest --style=scss`
- import fonts into style.scss 
- `ng serve`

and see developer tool

Minimal repo for reproduction: https://github.com/billyjov/ng-bug-font-decode

## 🔥 Exception or Error
<pre><code>

localhost/:1 Failed to decode downloaded font: http://localhost:4200/MaterialIcons-Regular.woff2
localhost/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
localhost/:1 Failed to decode downloaded font: http://localhost:4200/MaterialIcons-Regular.woff
localhost/:1 OTS parsing error: incorrect file size in WOFF header
localhost/:1 Failed to decode downloaded font: http://localhost:4200/MaterialIcons-Regular.ttf
localhost/:1 OTS parsing error: incorrect entrySelector for table directory
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular Core: 10.0.9
Angular CLI: 10.0.6
OS: Windows 10
Browsers: Chrome latest & Firefox latest

</code></pre>

![2020-08-19 12_04_33-MINGW64__d_bugs_ngFontBug](https://user-images.githubusercontent.com/18737653/90621725-63cfaf80-e214-11ea-987e-2c92dc632794.png)

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @billyjov, 

Thanks for reporting this issue, however this is not caused by the Angular CLI. Loading the fonts in a plan CSS and HTMl without the Angular CLI yields the same results. It's likely that your font is corrupted.

**Comment by billyjov** [comment]
Hi @alan-agius4 Thanks. You're right. my files was corrupted due to automtatic files migrations. Thanks!
