### ISSUE TITLE
Live Reload not working with WSL 2

### ISSUE THREAD

**Issue by mfish0005** [angular/angular-cli#18600]
#18002 🐞 Bug report

### Command

- [x] serve
### Is this a regression?

No

### Description

I recently "upgraded" my Windows Subsystem for Linux from v1 to v2.  I now have two major problems that only occur in my WSL shell.
1. Live reload no longer works.  I imagine this has something to do with the new Linux kernel they added in v2.  
2. `ng serve` takes approx. 10 to 15 times longer than it did with WSL 1.

This may be an issue that belongs in the WSL repo but I figured it was worth bringing up here.

## 🔬 Minimal Reproduction

Simple steps to reproduce this bug.
1. Install WSL 2.
2. Create a new Angular project.
3.  From your bash shell run `ng serve` or `npm start`.
4. Change a file and notice the CLI doesn't recompile and the browser doesn't reload.

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.4
Node: 12.18.3
OS: linux x64 (WSL 2 Ubuntu)

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.4
@angular-devkit/build-angular     0.1000.4
@angular-devkit/build-optimizer   0.1000.4
@angular-devkit/build-webpack     0.1000.4
@angular-devkit/core              10.0.4
@angular-devkit/schematics        10.0.4
@angular/cdk                      10.1.0
@angular/cli                      10.0.4
@angular/material                 10.1.0
@ngtools/webpack                  10.0.4
@schematics/angular               10.0.4
@schematics/update                0.1000.4
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
@mfish0005, this seems to be a bug in WSL. See: https://github.com/microsoft/WSL/issues/4064

 Closing as this in actionable from our end.

**Comment by mfish0005** [comment]
@alan-agius4  For clarity if other people find this thread: I don't think the issue you linked is related to this one because it's referring to WSL 1.  

But regardless I do agree that it's most likely a problem with WSL and not Angular.
