### ISSUE TITLE
I am getting many warnings as i given in below

### ISSUE THREAD

**Issue by Rasool-triquetra** [angular/angular-cli#18609]
Hi i had created an angular project with DevExtreme libraries to create DevExtreme table. While buliding the code i am getting many warnings as shown below.

WARNING in /home/rasool/Desktop/repo/node_modules/devextreme-angular/__ivy_ngcc__/fesm2015/devextreme-angular-ui-data-grid.js depends on 'devextreme/ui/data_grid'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
