### ISSUE TITLE
Errors after deploying to Github Pages

### ISSUE THREAD

**Issue by ztrayner** [angular/angular-cli#1860]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 4.4.5
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Created using CLI. 

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Console errors when loading the homepage after deploying:
`(index):21 GET http://www.zachtrayner.com/zachtrayner/vendor/es6-shim/es6-shim.js 
(index):14 GET http://www.zachtrayner.com/zachtrayner/style.css 
(index):22 GET http://www.zachtrayner.com/zachtrayner/vendor/reflect-metadata/Reflect.js 
(index):24 GET http://www.zachtrayner.com/zachtrayner/vendor/zone.js/dist/zone.js 
(index):23 GET http://www.zachtrayner.com/zachtrayner/vendor/systemjs/dist/system.src.js 
(index):24 GET http://www.zachtrayner.com/zachtrayner/vendor/zone.js/dist/zone.js 
(index):26 Uncaught ReferenceError: System is not defined`

5. Mention any other details that might be useful.
Setup as a user github page. The command to deploy wasn't working so I used ng github-pages:deploy and basically copied the branch over to master so I could use it as a user site. I also specified a CNAME with my domain (www.zachtrayner.com). The repo is public.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
You have to set the `<base href="/zachtrayner/">` manually if the deploy command failed for you and you did it manually. 

I'm not sure how it failed for you, and would appreciate an issue so I can fix it, but would ask you to try and file the issue using `beta.15`.
