### ISSUE TITLE
Uncaught TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by andzejsw** [angular/angular-cli#18608]
Build config `"buildOptimizer": true` when `"optimization": true` in angular.json file breaks my project on production build while using angular 10. On Angular 9 everything works perfect. Also if it is set to false, production build is working as it should.
Stacktrace in browser after opening project: 
```
main.143e43602909445d220b.js:1 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at i (main.143e43602909445d220b.js:1)
    at r (main.143e43602909445d220b.js:1)
    at main.143e43602909445d220b.js:1
    at Object.l0Em (main.143e43602909445d220b.js:1)
    at l (runtime.c51bd5b1c616d9ffddc1.js:1)
    at Object.6oLr (main.143e43602909445d220b.js:1)
    at l (runtime.c51bd5b1c616d9ffddc1.js:1)
    at Module.zUnb (main.143e43602909445d220b.js:1)
    at l (runtime.c51bd5b1c616d9ffddc1.js:1)
```
As far as i see, i am not first with this issue: https://stackoverflow.com/questions/55533630/angular-cli-buildoptimizer-destroys-the-production-build

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
