### ISSUE TITLE
Update to 10.1.0-next.7 throws error ERROR in Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#18615]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build
- [x] serve

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.1.0-next.5

### Description

After upgrading to 10.1.0-next.7 from version 10.1.0-next.5, the `ng build` and `ng serve` commands are now throwing below error:

`ERROR in Cannot read property 'kind' of undefined`

Below is my package.json

```
{
  "name": "myApp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "ng-high-memory": "node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng",
    "start": "echo hello && node --max_old_space_size=10000 ./node_modules/@angular/cli/bin/ng serve",
    "build": "node --max_old_space_size=10000 ./node_modules/@angular/cli/bin/ng build --configuration=production --project=MyProjectl",
    "build:ssr_ignore_dash_dash_watch_from_AngularCliBuilderDotCS": "ng run MyProject:server:production ",
    "build:ssr": "npm run build:ssr_ignore_dash_dash_watch_from_AngularCliBuilderDotCS",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "10.1.0-next.8",
    "@angular/cdk": "10.1.3",
    "@angular/common": "10.1.0-next.8",
    "@angular/compiler": "10.1.0-next.8",
    "@angular/core": "10.1.0-next.8",
    "@angular/fire": "6.0.2",
    "@angular/forms": "10.1.0-next.8",
    "@angular/google-maps": "10.1.3",
    "@angular/material": "10.1.3",
    "@angular/platform-browser": "10.1.0-next.8",
    "@angular/platform-browser-dynamic": "10.1.0-next.8",
    "@angular/platform-server": "10.1.0-next.8",
    "@angular/pwa": "0.1001.0-next.5",
    "@angular/router": "10.1.0-next.8",
    "@angular/service-worker": "10.1.0-next.8",
    "@ngx-lite/json-ld": "0.6.2",
    "@ngx-pwa/local-storage": "10.0.1",
    "@swimlane/ngx-charts": "14.0.0",
    "@trademe/ng-defer-load": "8.2.1",
    "aspnet-prerendering": "3.0.1",
    "core-js": "3.6.5",
    "d3-shape": "1.3.7",
    "dayjs": "^1.8.29",
    "file-saver": "2.0.2",
    "firebase": "7.17.1",
    "hammerjs": "2.0.8",
    "moment": "2.27.0",
    "ng2-adsense": "8.0.1",
    "ng2-ckeditor": "1.2.9",
    "ngx-build-plus": "10.1.1",
    "ngx-img-cropper": "9.0.1",
    "ngx-infinite-scroll": "9.0.0",
    "preboot": "^7.0.0",
    "rxjs": "~6.6.0",
    "screenfull": "5.0.2",
    "smoothscroll-polyfill": "0.4.4",
    "tslib": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "10.0.0",
    "@angular-devkit/build-angular": "0.1001.0-next.7",
    "@angular/cli": "10.1.0-next.7",
    "@angular/compiler-cli": "10.1.0-next.8",
    "@angular/language-service": "10.1.0-next.8",
    "@types/jasmine": "~3.5.11",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^14.0.24",
    "@types/webappsec-credential-management": "^0.5.1",
    "codelyzer": "^6.0.0",
    "concat": "3.0.0",
    "guess-parser": "0.4.19",
    "guess-webpack": "0.4.19",
    "html-minifier": "^4.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~7.0.0",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.0",
    "typescript": "^3.9.7",
    "webpack-bundle-analyzer": "^3.3.2"
  }
}

```

## 🔥 Exception or Error
<pre><code>
ERROR in Cannot read property 'kind' of undefined
</code></pre>

## 🌍 Your Environment
<pre><code>

Included package.json file contents.
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by naveedahmed1** [comment]
Thank you so much @alan-agius4 for your reply. I have added you to a private repository. If you could please just replace the contents of package.json file with the package.json file mentioned in issue, restore packages and then try ng serve.

**Comment by alan-agius4** [comment]
@naveedahmed1, I didn't receive any invitation.

**Comment by naveedahmed1** [comment]
You were already added, I removed you and added again. Can you please check it now?

**Comment by alan-agius4** [comment]
Got it, thanks

**Comment by alan-agius4** [comment]
Hi @naveedahmed1, 

Seems to be a module hoisting issue caused by NMP lock file.

Removing the node_modules and lock files should solve the problem

```
rm -rf node_modules package-lock.json
npm i
```

**Comment by naveedahmed1** [comment]
I already tried deleting node_modules and package-lock.json file but it didn't work.

**Comment by alan-agius4** [comment]
Hi @naveedahmed1, 

Yeah I forgot to run `ng update`.
Seems to be a module hoisting issue caused by the presence of `@angular-builders/custom-webpack`, because `@angular-builders/custom-webpack` has a direct dependency on `@angular-devkit/build-angular`.

```cmd
npm uninstall @angular-builders/custom-webpack
rm -rf node_modules package-lock.json
npm i
```

**Comment by naveedahmed1** [comment]
Thank you so much @alan-agius4 . I can confirm the issue is with `@angular-builders/custom-webpack`.

Following your suggestions, I uninstalled `@angular-builders/custom-webpack`, then removed `node_modules package-lock.json`, reinstalled packages and then installed `@angular-builders/custom-webpack` and it worked.
