### ISSUE TITLE
SCSS sourcemaps for component scss fail in Safari

### ISSUE THREAD

**Issue by smlombardi** [angular/angular-cli#18614]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Safari does not correctly use SCSS source maps

## 🔬 Minimal Reproduction

Simple steps to reproduce this bug.

1. Create a new project with `new new` and scss. 
2. Add styles to  `styles.scss`
3. import another scss partial into `styles.scss`, 
3. generate a component and add style rules to the component's scss file.

You can find a simple project with only this here: https://github.com/smlombardi/scss-cli-test

4. run the project.  
5. Inspect the three headers in dev tools in Chrome.  You can see the originating scss file where each rule lives, as expected

![chrome styles scss](https://user-images.githubusercontent.com/835148/91228147-c1249e80-e6f5-11ea-959c-eb30dd5d0788.jpg)
![chrome include scss](https://user-images.githubusercontent.com/835148/91228165-c8e44300-e6f5-11ea-9897-69cd77854828.jpg)
![chrome component scss](https://user-images.githubusercontent.com/835148/91228173-cc77ca00-e6f5-11ea-8f17-6f3272ac6b3b.jpg)

6. Try the same inspection in Safari.  The component SCSS is not identified:
![safari styles scss](https://user-images.githubusercontent.com/835148/91228382-24163580-e6f6-11ea-8b18-355165fb0f12.jpg)
![safari include scss](https://user-images.githubusercontent.com/835148/91228386-25476280-e6f6-11ea-8fb7-03de0db91cf0.jpg)
![safari component scss](https://user-images.githubusercontent.com/835148/91228391-27112600-e6f6-11ea-8bf6-c31c511c4dfe.jpg)

This has been like this as long as I can remember, I keep hoping newer versions of the CLI will fix this so I can use Safari for scss development.

You can see my angular.json config at the repo or directly here: https://github.com/smlombardi/scss-cli-test/blob/master/angular.json

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.0.7
Node: 12.18.1
OS: darwin x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**
Safari Version 13.1.2 (15609.3.5.1.3)
Safari Technology Preview Release 112 (Safari 14.0, WebKit 15610.1.25.5.1)
MacOS 10.15.6 (19G2021)

**Comment by alan-agius4** [comment]
Hi @smlombardi,

It looks that Safari 13 is ignoring sourcemaps which are inlined in the `style` tag such as: 
```html
<style>
.test[_ngcontent-yer-c11] {
  color: #c89bf1;
}

/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvdGVzdC90ZXN0LmNvbXBvbmVudC5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0VBQ0UsY0FBQTtBQUNGIiwiZmlsZSI6InNyYy9hcHAvdGVzdC90ZXN0LmNvbXBvbmVudC5zY3NzIiwic291cmNlc0NvbnRlbnQiOlsiLnRlc3Qge1xuICBjb2xvcjogbGlnaHRlbigkY29sb3I6Ymx1ZXZpb2xldCwgJGFtb3VudDogMjUpO1xufVxuIl19 */
<style>
```

When placing the above CSS & sourcemap in an `.css` file. Safari does point to the correct source, therefore it's excluded that the generated source map is malformed or corrupted.

From the above observations, I am going this issue as this isn't actionable by the Angular tooling team.

**Comment by smlombardi** [comment]
@alan-agius4 Is there anything I can do in setup to remedy this, or is it just a Safari thing?

**Comment by alan-agius4** [comment]
I don’t think there is anything that you can do.

**Comment by smlombardi** [comment]
I reported this to Apple.
