### ISSUE TITLE
Minify index.html on build --prod

### ISSUE THREAD

**Issue by robertbaker** [angular/angular-cli#1861]
1. Any project, run  `ng build --prod`

It does not minify `index.html`

**Comment by Fajkowsky** [comment]
Is there chance to minify html?

**Comment by e-oz** [comment]
Please add an option to turn off HTML minification. Or, at least, whitespace collapsing.

**Comment by ciesielskico** [comment]
Does this minify all angular templates or just `index.html`?

**Comment by filipesilva** [comment]
@e-oz is this change breaking something in your project? Can you open a new issue with a description of what's happening please?

@ciesielskico just index.html minification.

**Comment by e-oz** [comment]
if it's only for index.html - no, nothing critical :)

**Comment by ryanmccormick** [comment]
We are injecting some corporate scripts post build in our ci process and because of some of the methods used, this is now breaking our deployments. Is there anyway to disable index.html minification?

**Comment by jkevingutierrez** [comment]
Is there any option to minify index.html?

**Comment by odahcam** [comment]
It was closed because of this commit https://github.com/angular/angular-cli/commit/75311c2a4541cd498b5376e1a5e79f515a8c7d79

**Comment by RinMinase** [comment]
@odahcam This feature was removed on Angular 6+ based on the comments noted on the commit you  have linked.

So `index.html` file in Angular 6+ is still not minified. I am currently using Angular `v7.2.4`, and `index.html` on `--prod` does not minify it.

**Comment by odahcam** [comment]
Absolutely right, I read the comments too, I just wanted to give a direct and simple answer to the previous comment. Maybe this issue should be reopened.

**Comment by alaboudi** [comment]
@odahcam I agree. It should be.

@filipesilva thoughts?

**Comment by MilesBHuff** [comment]
This issue is for the same thing, and it's still open:  #11360

**Comment by milanobrenovic** [comment]
Any updates on this?
