### ISSUE TITLE
Referenced projects must have the new composite setting enabled

### ISSUE THREAD

**Issue by vbraun** [angular/angular-cli#18625]
## Command (mark with an `x`)
- [x] new
- [x] generate

### Description

The typescript docs say (https://www.typescriptlang.org/docs/handbook/project-references.html):

> Referenced projects must have the new composite setting enabled.

and the solutions-style project generated by angular-cli does not have the composite setting enabled.

The documentation might be wrong, idk, but **must** is pretty unambiguous. It seems that tsc does compile, but it might have other impacts (performance, ide features not working, just guessing at that point)

## 🔬 Minimal Reproduction

```
npx ng new superduper
cd superduper
npx ng generate library foo
egrep -r composite *json projects/foo/*json
```

## 🌍 Your Environment

<pre><code>
$ npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.7
Node: 12.18.3
OS: linux x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.7
@angular-devkit/build-angular      0.1000.7
@angular-devkit/build-ng-packagr   0.1000.7
@angular-devkit/core               10.0.7
@angular-devkit/schematics         10.0.7 (cli-only)
@angular/cli                       10.0.7
@schematics/angular                10.0.7 (cli-only)
@schematics/update                 0.1000.7 (cli-only)
ng-packagr                         10.0.4
rxjs                               6.5.5
typescript                         3.9.7
</code></pre>

**Comment by alan-agius4** [comment]
Hi @vbraun, 

The `composite` compiler option is not needed for solution style tsconfig, it is needed when you using the `project references` to build one or more projects at the same time. Looks to me that the documentation is not up to date.

Also, it's important to note that in version 10.1, we'll be removing solutions style tsconfig see: #18478
