### ISSUE TITLE
Cannot find module 'tslint' when generating component Angular 10

### ISSUE THREAD

**Issue by frunjik** [angular/angular-cli#18622]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: ~8

### Description
Error on generating a component: 
*Cannot find module 'tslint'*

## 🔬 Minimal Reproduction
ng g c components/terminal-tester/terminal-tester --skip-import

## 🔥 Exception or Error
<pre><code>
Cannot find module 'tslint'
Require stack:
- c:\WRK\locuswms-terminal\node_modules\@nativescript\schematics\src\convert-relative-imports\index.js
- c:\WRK\locuswms-terminal\node_modules\@angular-devkit\schematics\tools\export-ref.js
- c:\WRK\locuswms-terminal\node_modules\@angular-devkit\schematics\tools\index.js
- c:\WRK\locuswms-terminal\node_modules\@angular\cli\utilities\json-schema.js
- c:\WRK\locuswms-terminal\node_modules\@angular\cli\models\command-runner.js
- c:\WRK\locuswms-terminal\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\jhilst\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\jhilst\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 10.0.7
Node: 12.18.1
OS: win32 x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cdk                      10.1.3
@angular/cli                      10.0.7
@angular/material                 10.1.3
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Anything else relevant?**
<pre><code>
npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 1698 scanned packages
</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the https://github.com/NativeScript/nativescript-schematics project or file an issue on their issue tracker.
