### ISSUE TITLE
Angular 7>10 image url conversion changed

### ISSUE THREAD

**Issue by almogyehuda** [angular/angular-cli#18648]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Upon upgrading from angular 7 to 10,
The build process doesn't convert image urls to  inline base64 anymore.
That's really not a problem if the default now is to the image url stay as is, but the documentation doesn't show any option in angular.json / ng build flags to turn this feature on again.

Example:

`body.login-page:not(.dashboard-pages) {
    background-image: url(/images/atc-crowd.png) <- This one to base64;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    width: 650px;
    margin: 7% auto;

}`

This feature is really important to us and hold the angular upgrade, hope there's a configuration to enable this again.

Thanks

## 🌍 Your Environment
Angular cli 10.0.6
Angular/core 10.0.6

**Comment by alan-agius4** [comment]
Hi @almogyehuda,

This feature was removed completely and is was one of the breaking changes in version 8. See: https://github.com/angular/angular-cli/pull/12027 and https://github.com/angular/angular-cli/pull/11826#issuecomment-416260575

If you want to inline assets you will need to use a custom CLI builder such as https://www.npmjs.com/package/ngx-build-plus  and configure this in a custom webpack configuration. 

Please be aware that custom webpack configurations are not supported by the Angular tooling team.
