### ISSUE TITLE
ng new fails with 10.1.0-rc.0: The package @angular/compiler@10.1.0-rc.0 does not satisfy its siblings' peerDependencies

### ISSUE THREAD

**Issue by vbraun** [angular/angular-cli#18646]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new

### Description

ng new seems to be broken in 10.1.0-rc.0.

## 🔬 Minimal Reproduction

```
$ npx ng new superduper
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss          ]
[...]
npm ERR! node v12.18.3
npm ERR! npm  v2.14.21
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/compiler@10.1.0-rc.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@10.1.0-rc.0 wants @angular/compiler@10.1.0-rc.0
npm ERR! peerinvalid Peer codelyzer@6.0.0 wants @angular/compiler@>=2.3.1 <11.0.0 || >9.0.0-beta <11.0.0 || >9.1.0-beta <11.0.0 || >9.2.0-beta <11.0.0
npm ERR! peerinvalid Peer @angular/compiler-cli@10.1.0-rc.0 wants @angular/compiler@10.1.0-rc.0
npm ERR! peerinvalid Peer @angular/localize@10.1.0-rc.0 wants @angular/compiler@10.1.0-rc.0
npm ERR! peerinvalid Peer ng-packagr@10.1.0 wants @angular/compiler@^10.0.0

npm ERR! Please include the following file with any support request:
npm ERR!     /var/tmp/angular/duple/npm-debug.log
✖ Package install failed, see above.
```

Clearly `ng-packagr@10.1.0 wants @angular/compiler@^10.0.0` is the issue here.

## 🌍 Your Environment
<pre><code>
$ npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.0-rc.0
Node: 12.18.3
OS: linux x64

Angular: undefined
... 
Ivy Workspace: <error>

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.0-rc.0
@angular-devkit/core         10.1.0-rc.0
@angular-devkit/schematics   10.1.0-rc.0
@angular/cli                 10.1.0-rc.0
@schematics/angular          10.1.0-rc.0
@schematics/update           0.1001.0-rc.0
rxjs                         6.6.2
typescript                   1.8.10
</code></pre>

**Comment by alan-agius4** [comment]
@vbraun, it seems that your NPM is treating warnings are errors this was a problem in older NPM versions. 

It appears that you are using NPM v2.14.21 which is rather outdated. Please update to NPM v6+
