### ISSUE TITLE
hmr not working

### ISSUE THREAD

**Issue by Y2zz** [angular/angular-cli#18649]
Why can such a problem exist for so long and cannot be solved?

I haven't got HMR to work normally since angular 4

The steps to reproduce are simple

1. You only need to create a new project, `ng new test`
2. Change the script in package.json: `"start": "ng serve"` to `"start":"ng serve --hmr"`
3. Run `npm start`
4. Change the content in app.component.html and observe whether hmr takes effect in the developer tools

**Comment by alan-agius4** [comment]
@Y2zz, hmr will not work out of the box, as per warning during the build you’d need to configure it yourself as it does need some changes in the application code. See: https://webpack.js.org/guides/hot-module-replacement for more info.
