### ISSUE TITLE
CSS optimization breaks when :host-context is included

### ISSUE THREAD

**Issue by mcalmus** [angular/angular-cli#18672]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
I have a CSS file that is shared between two components, one that uses default encapsulation and one that uses NONE. I have two lines in the CSS as follows:

```
.darkMode .myLogo {
  color: white;
}
:host-context(.darkMode) .myLogo {
  color: white;
}
```

This works fine with dev/unoptimized builds. However, when done with a prod/optimized build the resulting CSS combines the two selectors:

``` .darkMode .myLogo,:host-context(.darkMode) .myLogo{color:white}```

The selector is essentially ignored by the browser.

For the component using default encapsulation it similarly works fine regardless of whether optimized or not.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.8
node: 10.16.3
OS: win32 x64
Angular: 10.0.14

</code></pre>

**Anything else relevant?**

All that I've tried exhibit same issue.

no.

**Comment by alan-agius4** [comment]
Caused by https://github.com/cssnano/cssnano/issues/730

**Comment by nomeaning777** [comment]
I faced the same issue. Workaround is adding an important comment to the :host-context.
```
.darkMode .myLogo {
    color: white;
}
:host-context(.darkMode) .myLogo {
    /*! Dummy comment to avoid merge host-context and other by cssnano */
    color: white;
}
```

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. 

See: cssnano/cssnano#730

**Comment by mcalmus** [comment]
@alan-agius4 With all due respect, just because an issue is caused by the use of a third-party library, it doesn't make it not an issue. The project <chose> to use that third-party library.

This is broken again in (at least 11.2.11 & 11.2.12) such that the trick @nomeaning777 suggested no longer works.
