### ISSUE TITLE
fileReplacements does not work on angular v10

### ISSUE THREAD

**Issue by anselmhou** [angular/angular-cli#18671]
# 🐞 Bug report

### Command (mark with an `x`)
ng build --configuration=development

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
1.  Create a brand new project using `ng new sample2`
2.  Build the project with configuration=production: `ng build --configuration=production`
3.  Check the src\environments\environment.ts , open environment.ts and the file content has no changes at all.

## 🔥 Exception or Error
None

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.8
Node: 14.7.0
OS: win32 x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

OS: win 10

**Comment by alan-agius4** [comment]
> Check the src\environments\environment.ts , open environment.ts and the file content has no changes at all.

This is expected, `fileReplacement` work on the emitted code and not on source code.
