### ISSUE TITLE
Creation of workspace failed

### ISSUE THREAD

**Issue by MarkusAGSchmidt** [angular/angular-cli#18680]
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I only tried Angular CLI 10.0.8.

### Description

After I had created a new VM with Ubuntu 18.04, I also installed

1.  node 12.18.3
2.  npm 6.14.6
3.  angular CLI 10.0.8

I followed the instructions on the official site (https://angular.io/guide/setup-local), but the execution of `ng new my-app` failed every time!
After some minutes of downloading some packages the error message was always the following:

## 🔬 Minimal Reproduction

Take a plain Ubuntu 18.04 VM and install 
1.  node 12.18.3
2.  npm 6.14.6
3.  angular CLI 10.0.8

After this was successful just type `ng new my-app` and wait for the error.

<pre><code>
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /development/my-app/node_modules/copy-webpack-plugin/node_modules/cacache/package.json.3367901514
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/development/my-app/node_modules/copy-webpack-plugin/node_modules/cacache/package.json.3367901514'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
</code></pre>

I have done this 4 times with a fresh VM and the result was always the same.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment

Output of `ng version`:

<pre><code>
Angular CLI: 10.0.8
Node: 12.18.3
OS: linux x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1000.8
@angular-devkit/core         10.0.8
@angular-devkit/schematics   10.0.8
@schematics/angular          10.0.8
@schematics/update           0.1000.8
rxjs                         6.5.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
