### ISSUE TITLE
Migration to Angular 10.1 doesn't update TypeScript version to 4

### ISSUE THREAD

**Issue by destus90** [angular/angular-cli#18695]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure if this is a regression or not.

### Description

When you update to 10.1 version, your TypeScript version won't be updated. It retains as `~3.9.5"`. As I know, Angular 10.1 supports TypeScript@4, due to https://github.com/angular/angular-cli/pull/18319

## 🔬 Minimal Reproduction
1. clone it https://github.com/destus90/angular-ts-update-issue
2. run `npm ci`
3. run `ng update @angular/core @angular/cli`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @destus90, 

This is working as intended.

Angular 10.1 still supports TypeScript 3.9.x, and therefore TypeScript 3.9.x is still within the supported range, therefore `ng update @angular/core` will not update the TypeScript version automatically. If you want to use TypeScript 4.0 in an existing application you'll need to opt-in manually by either running `ng update typescript` or updating the package.json.

The main reason for this is that TypeScript minor versions are breaking and it's likely that updating the TypeScript 4.0.2 will cause compilation errors, which is not ideal when updating between minor.
