### ISSUE TITLE
ng new logs a warning about entryComponents being deprecated

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular-cli#18692]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: v10.0.x

### Description

When running `ng new`, a warning about `entryComponents` is logged

## 🔥 Exception or Error
<pre><code>
> ng new entry-comp-warning --defaults
Option "entryComponent" is deprecated: Since version 9.0.0 with Ivy, entryComponents is no longer necessary.
CREATE entry-comp-warning/README.md (1034 bytes)
CREATE entry-comp-warning/.editorconfig (274 bytes)
CREATE entry-comp-warning/.gitignore (631 bytes)
CREATE entry-comp-warning/angular.json (3662 bytes)
CREATE entry-comp-warning/package.json (1261 bytes)
...
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.0
Node: 14.6.0
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.0
@angular-devkit/core         10.1.0
@angular-devkit/schematics   10.1.0
@schematics/angular          10.1.0
@schematics/update           0.1001.0
rxjs                         6.6.2
</code></pre>

**Anything else relevant?**

`npx @angular/cli@10.0.8 new entry-comp-warning --defaults` does not raise this warning.

**Comment by alan-agius4** [comment]
Ummm, this is an interesting one!

**Comment by prabh-62** [comment]
`> npx @angular/cli@11.0.0-next.6 new admin-console --strict true --routing true --style css`
outputs zero warnings

`> npx @angular/cli@11.0.0-next.6 new admin-console --strict true --defaults true`
spawns few warnings

<img width="1342" alt="ng_new_11" src="https://user-images.githubusercontent.com/13006107/95597104-389b5c80-0a1c-11eb-9071-4d2a320ab556.png">
