### ISSUE TITLE
Ng Compiler cannot resolve absolute path. Getting 'Cannot find module' error.

### ISSUE THREAD

**Issue by Praveenjana20** [angular/angular-cli#18698]
Getting **error TS2307: Cannot find module 'src/app/shared/module.service'.** after copy paste of a same angular project in a different folder.  Both source code are same except the folder name. 

Original project getting complied with no issues whereas the copied project throws error for absolute path import

**tsconfig.json**

{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}

**Comment by alan-agius4** [comment]
Kindly follow the issue template. Thanks.

**Comment by Praveenjana20** [comment]
Found the cause of the issue anyway. 
I thought it would be good to post it here,

**The absolute path contained an invisible special character.**

**src/app/shared/data-services/​function-room-groups.data.service**

between data-services & function-room

Thanks.
