### ISSUE TITLE
Please add support for the awesome, awesome jspm

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#187]
After using webpack for a few months I moved the popular angular2 boilerplate project http://ng2.javascriptninja.io away from webpack and into jspm and I will never look back.

I am posting this in hopes ng cli will support jspm as this is superior to any other packaging blunder available today.

I am not sure if the ng2 team has reviewed jspm and if not, I highly recommend they do.

First, it is as close to the metal as possible which is a must for debugging, you are working with the non bundled files and so often errors are more accurate and if you are lucky you get a reference to the file name, something you will never get with a blunder.

 Also, it is just in time transpiling of TS which is OMG amazing.. the workflow is fast and reliable. And it supports multi registries, github, npm, private and more.

and for production, you can even mix bundling with lazy loading... 

Not to mention it supports multi versioning for modules.. sweeet....

all in all it is the ultimate package manager and I am sure many developers will move to it and so I hope this project will adopt it.

FYI I am not a contributor to jspm so no strings attached, just a HAPPY customer,

regards - http://jspm.io/

Sean

**Comment by filipesilva** [comment]
Hi @born2net! 

The stance on JSPM is similar to the one on webpack: there isn't any plan *right now* to move to it, but I wouldn't say that won't happen in the future. Right now we're mostly focused on getting a few usage patterns fully working, customization comes after that.

Speaking for myself, I'd like to eventually have a clear set of instructions to have CLI users move projects to a different build system if they so wish, after the initial setup.

**Comment by born2net** [comment]
ok great, looking fwd to contributing jspm kitchen sink when need be,
regards

**Comment by filipesilva** [comment]
Glad to hear, cheers!

**Comment by DavidKDeutsch** [comment]
While I am usually loathe to add a "me too! +1!" kind of comment, I've got to say that I **love** SystemJS/JSPM. Granted, part of this may be due to the fact that it is easier to use out of the box (I'm rather new to the various solutions out there), but in my case I have an application composed of various widgets whose existence may not be known at build time, so the fact that SystemJS makes it easy to transparently load a module either from an existing (separate) bundle or "a la carte" has been awesome.
