### ISSUE TITLE
Ng Generate Library Fails on 10.1.0

### ISSUE THREAD

**Issue by idwebmedia** [angular/angular-cli#18709]
# 🐞 Bug report

### Command

- [x] generate

### Is this a regression?

Yes

### Description

Updating the Angular Cli to version 10.1.0 breaks library schematic

## 🔬 Minimal Reproduction
<pre>
ng new test --skipInstall=true
cd test
</pre>

Update package.json using latest @angular version 10.1.0 (see environment below) and install

<pre>
npm install
</pre>

Generate library

<pre>
ng g library lib-test
</pre>

I tried a few other schematics (app, component, directive, service) and they seem to be working as expected. Looks to just be library but may want to do a full regression on the rest.

## 🔥 Exception or Error
<pre>
Cannot read property 'paths' of undefined
</pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.0
Node: 10.16.3
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.5.5
typescript                        4.0.2
webpack                           4.44.1
</code></pre>

**Comment by alan-agius4** [comment]
Can you try updating your global cli version?

Nb: Updating the `@angular` packages directly in your package.json without using `ng update‘ might cause undefined behaviours, this is because migrations will not be executed.

**Comment by idwebmedia** [comment]
You are correct. Updating the global fixed the issue. Thank you.
