### ISSUE TITLE
Uncaught ReferenceError: __NG_CLI_RESOURCE__1 is not defined

### ISSUE THREAD

**Issue by hrueger** [angular/angular-cli#18705]
# 🐞 bug report

### Description

When running `ng serve` I get the following error: `Uncaught ReferenceError: __NG_CLI_RESOURCE__1 is not defined`. Everything is working fine when I use `ng build --prod`.

![grafik](https://user-images.githubusercontent.com/18656830/92308965-aaa5ff00-efa1-11ea-92bf-a80c15bcc8e7.png)

Probably something in my `tsconfig.json` is wrong, but a more descriptive error message would be really helpful.
The compilation process by the way succeeds without any errors / warnings.

## 🔬 Minimal Reproduction
I can't create a minimal reproduction repo for this, because the issue does not happen in a new project.
Please use this repo: https://github.com/hrueger/AGBooks/tree/master/backend and run the Angular App **in the `backend` directory** using `ng serve`.

## 🔥 Exception or Error
<pre><code>
Uncaught ReferenceError: __NG_CLI_RESOURCE__1 is not defined
    StatisticsComponent statistics.component.ts:8
    YP90 statistics.component.ts:87
    Webpack 10
        __webpack_require__
        ZAI4
        __webpack_require__
        zUnb
        __webpack_require__
        0
        __webpack_require__
        checkDeferredModules
        webpackJsonpCallback
        <anonymous>
</code></pre>

The error is not caused by any of my code in the `StatisticsComponent`, because if I remove this component from the declarations list in the `AppModule`, I get the same error with another component. In line 8 the templateUrl is specified.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.0
Node: 13.7.0
OS: win32 x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms       
... localize, platform-browser, platform-browser-dynamic, router       
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.6.2
typescript                        3.9.7
webpack                           4.44.1
</code></pre>

**Anything else relevant?**
It is a NativeScript Angular shared project.

**Comment by JoostK** [comment]
Possibly related to #18555

**Comment by alan-agius4** [comment]
It’s is indeed related to the above, while I cannot access the reproduction provided above probably due to a wrong link.  It’s likely that the problem is that you are using `commonjs` as `module`.

**Comment by hrueger** [comment]
@alan-agius4 Thanks for the quick reply. Sorry for the 404 link, I updated it above. Here it is again: https://github.com/hrueger/AGBooks/tree/master/backend

I will check tomorrow if I am using `commonjs`.

**Comment by alan-agius4** [comment]
Changing https://github.com/hrueger/AGBooks/blob/fe84a1e34df8772c74f45799f02e6badfd675f59/backend/src/tsconfig.app.json#L19 to es2020 should get rid of the error.

**Comment by hrueger** [comment]
@alan-agius4 Yes, that fixed the error. Thanks a lot!
