### ISSUE TITLE
ng new "Projekt" ==> always @babel\parser :: errno -4058

### ISSUE THREAD

**Issue by ErrorInApplication** [angular/angular-cli#18712]
i get allways an error at creating a new angular project:

new installation of NPM
Cleaning npm cache
verify npm cache
install -g @angular/cli
ng new mytestprojekt

>> Angular CLI: 10.1.0
Node: 14.9.0
OS: win32 x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.0
@angular-devkit/core         10.1.0
@angular-devkit/schematics   10.1.0
@schematics/angular          10.1.0
@schematics/update           0.1001.0
rxjs                         6.6.2

F:\Code\Angular>npm -version
6.14.8

npm WARN tar EINVAL: invalid argument, futime
npm WARN tar EINVAL: invalid argument, futime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\rollup\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.9.0","npm":"6.14.8"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path F:\Code\Angular\mytest\node_modules\@babel\parser
npm ERR! dest F:\Code\Angular\mytest\node_modules\@babel\.parser.DELETE
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, rename 'F:\Code\Angular\mytest\node_modules\@babel\parser' -> 'F:\Code\Angular\mytest\node_modules\@babel\.parser.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Frank\AppData\Roaming\npm-cache\_logs\2020-09-07T07_44_19_990Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

F:\Code\Angular>ng --version
[2020-09-07T07_44_19_990Z-debug.log](https://github.com/angular/angular-cli/files/5182087/2020-09-07T07_44_19_990Z-debug.log)

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by ErrorInApplication** [comment]
Hi,
At first time im update my existing Project -> Project does not run any more ...
**I try three day's** with install diffrent NPM-Versions (LTS/Current Version)
I try installing (global) angular/cli in versions in diffrent Versions 10.0.8 ... current Version

At generating a new Project with "ng new xxx" i always see the problem ...
I cant see where the problem with npm exists ... the loaded package seems not in the correct version ... OR??? I'm so wrong???

24475 silly saveTree +-- typescript@4.0.2
24475 silly saveTree `-- zone.js@0.10.3
24476 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\rollup\node_modules\fsevents):

clear npm installation and deleteing cache doesn't help ...

I think there is someting diffrent wrong with the package ...

BR
Frank
