### ISSUE TITLE
angular-cli@webpack Cannot load a custom webpack config.

### ISSUE THREAD

**Issue by martinbelanger** [angular/angular-cli#1871]
Hi. My issue is about webpack version of the cli. I need my custom webpack config to load external libraries from CDN instead of bundle in my bundle.js. It seems that angular-cli hide the webpack config with his default value and I cannot add my own configuration.

Can you gave the opportunity to add our own webpack.config with the angular-cli ?

Thanks.

**Comment by Kunepro** [comment]
I think this was already answered here:
https://github.com/angular/angular-cli/issues/1656#issuecomment-240171375

**Comment by martinbelanger** [comment]
Yep, this is exactly my case.
Thanks @Kunepro.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1656, please see that issue instead.

**Comment by muralib91dotnet** [comment]
Waiting for the CLI team to make way for add-on OR extending the CLI hidden webpack config
