### ISSUE TITLE
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed

### ISSUE THREAD

**Issue by gbrigens** [angular/angular-cli#1872]
Mac OSX (El Capitan)
angular-cli: 1.0.0-beta.10
node: 6.3.1
os: darwin x64

All the app I created using CLI, only when I was services module that where this issue started.

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with: Error: Typescript found the following errors: /Users/gbrigens/Projects/angular/myFirstApp/tmp/broccoli_type_script_compiler-input_base_path-K42Wrw0E.tmp/0/src/app/todos/todos.component.spec.ts (10, 21): Supplied parameters do not match any signature of call target. at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:120:19) at BroccoliTypeScriptCompiler.build (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10) at /Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:152:21 at lib$rsvp$$internal$$tryCatch (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16) at lib$rsvp$$internal$$invokeCallback (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17) at lib$rsvp$$internal$$publish (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1019:11) at lib$rsvp$asap$$flush (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9) at _combinedTickCallback (internal/process/next_tick.js:67:7) at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: at BroccoliTypeScriptCompiler.Plugin (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/broccoli-plugin/index.js:10:31) at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/broccoli-caching-writer/index.js:21:10) at BroccoliTypeScriptCompiler (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5) at Angular2App._getTsTree (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/lib/broccoli/angular2-app.js:331:18) at Angular2App._buildTree (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/lib/broccoli/angular2-app.js:124:23) at new Angular2App (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/lib/broccoli/angular2-app.js:53:23) at module.exports (/Users/gbrigens/Projects/angular/myFirstApp/angular-cli-build.js:10:10) at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:55:19) at Class.module.exports.Task.extend.init (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/angular-cli/lib/models/builder.js:89:10) at new Class (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/core-object/core-object.js:18:12) at Class.module.exports.Task.extend.run (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/angular-cli/lib/tasks/serve.js:15:19) at /Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/angular-cli/lib/commands/serve.js:64:24 at lib$rsvp$$internal$$tryCatch (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16) at lib$rsvp$$internal$$invokeCallback (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17) at /Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11 at lib$rsvp$asap$$flush (/Users/gbrigens/Projects/angular/myFirstApp/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

I have tried "ng init" but still run on the same error.

**Comment by filipesilva** [comment]
This seems to be the real error:
```
src/app/todos/todos.component.spec.ts (10, 21): Supplied parameters do not match any signature of call target. 
```

You must have changed your component but not edited it's `.spec.ts` file. You should either update or delete it.

I also recommend updating to the latest version of the CLI since we've since moved to a webpack based build system. See https://github.com/angular/angular-cli#webpack-update for instructions.
