### ISSUE TITLE
ng new with older @angular/cli version generates an Angular 10 project

### ISSUE THREAD

**Issue by Waterstraal** [angular/angular-cli#18731]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, it used to work in an older version. I'm not sure when I last ran this command, but my best guess is around Angular 6. 

### Description

Installing a new Angular project using npx and specifying an older @angular/cli@9 version generates an Angular 10 project. 
 
## 🔬 Minimal Reproduction

Run `npx -p @angular/cli@9 ng new ng9-app --interactive=false`

Open `package.json` and see that it installed Angular 10 dependencies: 
```
  "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
```
I would expect to see dependencies on version 9.x 

## 🌍 Your Environment
Windows 10
Node.js 12.4.0

**Comment by alan-agius4** [comment]
Can you try `npx @angular/cli@9 new ng9-app --interactive=false`

**Comment by Waterstraal** [comment]
same result:
```
  "dependencies": {
    "@angular/animations": "~10.1.0",
    "@angular/common": "~10.1.0",
    "@angular/compiler": "~10.1.0",
    "@angular/core": "~10.1.0",
    "@angular/forms": "~10.1.0",
    "@angular/platform-browser": "~10.1.0",
    "@angular/platform-browser-dynamic": "~10.1.0",
    "@angular/router": "~10.1.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
```

**Comment by clydin** [comment]
The `-p` option will cause the version specifier to not be used.  However, the command suggested above (`npx @angular/cli@9 new ng9-app --interactive=false`) should work.  If this does not, then one likely cause is that a version of the CLI is installed in the directory hierarchy above the current directory.  Could you check if there is an installed instance of the CLI (or potentially a `node_modules` directory in or above the current directory)?

**Comment by Waterstraal** [comment]
Thanks for the information. I did some extra tests:

- When I run `npx @angular/cli@9 new ng9-app --interactive=false` in an empty directory it installs the expected **v9**. 
- When I run `npx @angular/cli@9 new ng9-app --interactive=false` in a directory with other angular projects next to it, it installs **v10**. There is no `node_modules` or `package.json` in any parent directories, but there are projects and node_modules in sibling directories. Could that affect the version used as well?

In any case I would expect v9 to be installed with above command, or is this logic flawed somehow?

**Comment by alan-agius4** [comment]
What's happenig here is that at the moment the Angular CLI initialization code will always defer to the "local"
 installed version in case there is one.

When you use `npx` you are essentially install a temporary global version of `@angular/cli`, but since you have another "local"  `@angular/cli` in the directory hierarchy above the current directory the command will be deferred to the latter version.
