### ISSUE TITLE
ng new with cli v10.1 creates a project with TSLint, which has been deprecated.

### ISSUE THREAD

**Issue by AndrewPomorski** [angular/angular-cli#18738]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

As per title, running `ng new` creates a project using deprecated linter. 

## 🔬 Minimal Reproduction

`ng new test-project`

`cd test-project`

`grep tslint package.json`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.0
Node: 14.9.0
OS: darwin x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.0
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.1001.0
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@ngtools/webpack                  10.1.0
@schematics/angular               10.1.0
@schematics/update                0.1001.0
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.44.1
</code></pre>

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/angular/angular-cli/issues/13732
