### ISSUE TITLE
Support npm linked libraries

### ISSUE THREAD

**Issue by ert78gb** [angular/angular-cli#1875]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
El Capitan 10.11.6

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.3.1
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

- checkout git repository
- cd into directory
- npm link
- go to main project
- npm install 'linked package'
- ng build

If I commit the changes and npm install directly from github repo. everything is working

4. The log given by the failure. Normally this include a stack trace and some
   more information.
null pointer exception when loading RC5 module. 

5. Mention any other details that might be useful.
https://webpack.github.io/docs/troubleshooting.html
- npm linked modules don’t find their dependencies

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ghidoz** [comment]
Same for me. The solution should be add these lines to the webpack config:
```
module.exports = {
  resolve: { fallback: path.join(__dirname, "node_modules") },
  resolveLoader: { fallback: path.join(__dirname, "node_modules") }
};
```
But there is no webpack config that we can edit!

**Comment by filipesilva** [comment]
Would you be willing to submit a PR to add those options?

@TheLarkInn can you have a look at this solution? It's the one listed in http://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-doesn-t-find-their-dependencies

**Comment by serhiisol** [comment]
I've found solution for that and I'll make a pull request ;) hold on guys :)
