### ISSUE TITLE
angular/cli install error

### ISSUE THREAD

**Issue by phileinSophos** [angular/angular-cli#18757]
while trying to install angular/cli, i am getting the following error:
`npm ERR! Unexpected end of JSON input while parsing near '...AQBQJbymRHCRA9TVsSAnZ'`

i have node version 14.10.1
and npm version 6.14.8

**Comment by geromegrignon** [comment]
try to clean your npm cache with : `npm cache clean --force` and retry the angular/cli installation.

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
