### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by catull** [angular/angular-cli#1876]
1. OS?
   Not an OS-specific problem

2. Versions.
  `npm` --version is 3.10.6
  `node` --version v6.4.0

3. Repro steps.
  `npm` run build

4. The log given by the failure.
```log
> angular-cli@1.0.0-beta.11-webpack.2 build /Users/carlo/workspace/javascript/ng/angular-cli.git
> npm-run-all -c build:main build:packages


> angular-cli@1.0.0-beta.11-webpack.2 build:main /Users/carlo/workspace/javascript/ng/angular-cli.git
> tsc -p addon/ng2

addon/ng2/commands/init.ts(58,9): error TS7005: Variable 'gitInit' implicitly has an 'any' type.
addon/ng2/commands/init.ts(66,9): error TS7005: Variable 'linkCli' implicitly has an 'any' type.
addon/ng2/commands/init.ts(75,9): error TS7005: Variable 'npmInstall' implicitly has an 'any' type.
addon/ng2/commands/init.ts(84,9): error TS7005: Variable 'bowerInstall' implicitly has an 'any' type.
  ...
```

I am surprised this is not caught automatically.
tsconfig.json, line 10, states

```json
....
    "noImplicitAny": true,
```

**Comment by catull** [comment]
In order to get here, you have to first implement the suggested "fix" mentioned in issue #1853.

**Comment by catull** [comment]
There is an alternative.

Since tsc is instructed not to allow _implicit_ `any`, make the explicit.
This works.

**Comment by filipesilva** [comment]
I think this has since been addressed. If that's not the case, please tell me and I will reopen.
