### ISSUE TITLE
ERROR in Cannot read property 'kind' of undefined - Angular 10.1.1

### ISSUE THREAD

**Issue by bhanna1693** [angular/angular-cli#18764]
# 🐞 bug report

### Description
After bumping my Angular version from 10.0.5 to 10.1.1, I am receiving the following error when trying to compile my project using ng serve or ng build: `Error in Cannot read propery 'kind' of undefined`

Other threads suggest to downgrade typescript. Others say it has to do with multiple stylesheets in the styleUrls array of the components. While others just say to re-run ng serve:
-  [1 github issue](https://github.com/microsoft/TypeScript/issues/28810l)
-  [2 stackoverflow](https://stackoverflow.com/questions/57891605/angular-cli-build-prod-typeerror-cannot-read-property-kind-of-undefined)
-  [3 stackoverflow](https://stackoverflow.com/questions/57891605/angular-cli-build-prod-typeerror-cannot-read-property-kind-of-undefined)

In each of these case, however, this would mean a regression. And none of their solutions seem to work for our project

## 🔬 Minimal Reproduction
(company code)

## 🔥 Exception or Error
`ERROR in Cannot read property 'kind' of undefined`

The error shows up in the terminal at the end of the compilation process and prevents the app from rendering in the browser:
![image](https://user-images.githubusercontent.com/41653741/92954231-18827880-f431-11ea-8af0-b42d5d8f92ad.png)
![image](https://user-images.githubusercontent.com/41653741/92954318-394ace00-f431-11ea-9a41-304d8a0329f2.png)

## 🌍  Your Environment

**Angular Version:**
![image](https://user-images.githubusercontent.com/41653741/92953994-add13d00-f430-11ea-89fd-90d548498357.png)

**Anything else relevant?**
Please help me understand this error!

**Comment by alan-agius4** [comment]
Likely it’s related to https://github.com/angular/angular-cli/issues/18722

Are you using custom Angular builders? If so please make sure to update to the latest version.

Also try to remove node_modules and the lock file and run a fresh install.

```
rm -rf node_modules package-lock.json
npm i
```

**Comment by bhanna1693** [comment]
> Likely it’s related to #18722
> 
> Are you using custom Angular builders? If so please make sure to update to the latest version.

I am using a custom angular builder. It is used only to remove excess moment.js code: 
```
'use strict';

const webpack = require('webpack');

// https://webpack.js.org/plugins/context-replacement-plugin/
module.exports = {
  plugins: [new webpack.ContextReplacementPlugin(/moment[/\\]locale$/, /en-us/)]
};
```

and implemented in angular.json like so:
```
"builder": "@angular-builders/custom-webpack:browser",
"options": {
  "customWebpackConfig": {
      "path": "./extra-webpack.config.js",
      "replaceDuplicatePlugins": true,
      "mergeStrategies": {
          "externals": "prepend"
      }
}
```

-----------------------------------------------

I have updated my dependencies to the most recent version (I believe these to be up to date based on a fresh `ng new project` comparison). Here are my relevant devDependencies:
```
"devDependencies": {
    "@angular-builders/custom-webpack": "^10.0.1",
    "@angular-devkit/build-angular": "~0.1001.1",
    "@angular-devkit/core": "^10.0.3",
    "@angular/cli": "~10.1.1",
    "@angular/compiler-cli": "~10.1.1",
    "@angular/language-service": "10.1.1",
    "ts-loader": "^7.0.1",
    "ts-node": "~8.10.1",
    "tslint": "~6.1.0",
    "typescript": "~3.9.7",
    "webpack": "^4.44.1",
  }
```

--------------------------------------------------
> Also try to remove node_modules and the lock file and run a fresh install.
> 
> ```
> rm -rf node_modules package-lock.json
> npm i
> ```

^^^ I have tried this several times lol

**Comment by alan-agius4** [comment]
Can you run `npm ls typescript`?

**Comment by bhanna1693** [comment]
> Can you run `npm ls typescript`?

```
C:\Users\BrianHanna\IdeaProjects\mymfg-spring-agents\src\main\webapp>npm ls typescript
ng@0.0.0 C:\Users\BrianHanna\IdeaProjects\mymfg-spring-agents\src\main\webapp
+-- @angular-devkit/build-angular@0.1001.1
| `-- @angular-devkit/build-optimizer@0.1001.1
|   `-- typescript@4.0.2
+-- @angular-devkit/build-optimizer@0.1001.1
| `-- typescript@4.0.2
`-- typescript@3.9.7
```

**Comment by bhanna1693** [comment]
Current devDep:
```
"devDependencies": {
    "@angular-builders/custom-webpack": "^10.0.1",
    "@angular-devkit/build-angular": "~0.1001.1",
    "@angular-devkit/core": "^10.0.3",
    "@angular/cli": "~10.1.1",
    "@angular/compiler-cli": "~10.1.1",
    "@angular/language-service": "10.1.1",
    "@types/node": "^14.0.1",
    "codelyzer": "^6.0.0",
    "ts-loader": "^7.0.1",
    "ts-node": "~8.10.1",
    "tslint": "~6.1.0",
    "typescript": "~3.9.7",
    "webpack": "^4.44.1",
  }
```

npm ls typescript
```
C:\Users\BrianHanna\IdeaProjects\mymfg-spring-agents\src\main\webapp>npm ls typescript
ng@0.0.0 C:\Users\BrianHanna\IdeaProjects\mymfg-spring-agents\src\main\webapp
+-- @angular-devkit/build-angular@0.1001.1
| `-- @angular-devkit/build-optimizer@0.1001.1
|   `-- typescript@4.0.2
`-- typescript@3.9.7
```

**Comment by bhanna1693** [comment]
@alan-agius4 nvm! Its working now! Not sure what I changed specifically, but heres the final devDep for reference if anyone finds this thread:
```
 "devDependencies": {
    "@angular-builders/custom-webpack": "^10.0.1",
    "@angular-devkit/build-angular": "~0.1001.1",
    "@angular-devkit/core": "^10.0.3",
    "@angular/cli": "~10.1.1",
    "@angular/compiler-cli": "~10.1.1",
    "@angular/language-service": "10.1.1",
    "@types/node": "^14.0.1",
    "codelyzer": "^6.0.0",
    "ts-loader": "^7.0.1",
    "ts-node": "~8.10.1",
    "tslint": "~6.1.0",
    "typescript": "~3.9.7",
    "webpack": "^4.44.1",
  }
```
