### ISSUE TITLE
angular-cli@webpack option --proxy does not work

### ISSUE THREAD

**Issue by wz2b** [angular/angular-cli#1877]
The '--proxy' option does not work - or at least does not work the same as it did with the systemjs version.  For example, I can run:

ng serve --proxy http://example.com

and request using Http:

    http.get("/api/xyzzy").suscribe( xxxx );

and I can see it makes a request of the local server but the local server returns the application entry page (index.html).

This version of angular-cli calls out:

    "ember-cli": "2.5.0"

which calls out:

    "http-proxy": "^1.9.0",

and I have verified that both these are present at those versions.

Linux - Ubuntu 14,04
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.1
os: linux x64

**Comment by zsfarkas** [comment]
It seems to be [closed.] #1487 -> I am hoping to get it soon...

And there is a hack if you want to use the latest beta (webpack.2): #1712

**Comment by jandsu** [comment]
It seems Angular CLI 1.0.0-beta.11-webpack.9-4 is mixing up --proxy and --proxy-config options:

```
$ ng serve --proxy https://foo.bar.com
Proxy config file /home/me/code/app/https:/foo.bar.com does not exist.
```

**Comment by filipesilva** [comment]
It doesn't work in the same way, no. You can see some documentation in https://github.com/angular/angular-cli/pull/1896, it's going to be merged soon.
