### ISSUE TITLE
ng update @angular/core @angular/cli gives error 'Package '@angluar/core' is not a dependency.', but it most certainly is.

### ISSUE THREAD

**Issue by jasonburrows** [angular/angular-cli#18785]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, in that I used ng update to move from v8 to v9 without this issue.

### Description

I have an Angular project at v9.1.5.  I want to move to v10.  When I run the command `ng update @angular/core @angular/cli` I get the error "Package '@angluar/core' is not a dependency.'", but it most certainly is a dependancy.

## 🔬 Minimal Reproduction
1. Take an existing angular application at version 9.1.5
2. Ensure `npm install` has been run so the packages are installed.
3. Run `ng update @angular/core @angular/cli`.

## 🔥 Exception or Error
<pre><code>
  ng:analytics getGlobalAnalytics +0ms
  ng:analytics Client Analytics config found: false +33ms
  ng:analytics Analytics disabled. Ignoring all analytics. +1ms
  ng:analytics getSharedAnalytics +0ms
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
  ng:analytics getGlobalAnalytics +0ms
  ng:analytics NG_CLI_ANALYTICS is false +1ms
  ng:analytics getSharedAnalytics +0ms
Using package manager: 'npm'
Collecting installed dependencies...
Found 88 dependencies.
Package '@angluar/core' is not a dependency.

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.5
Node: 12.16.2
OS: darwin x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cdk                      9.2.3
@angular/cli                      9.1.5
@angular/material                 9.2.3
@ngtools/webpack                  9.1.5
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Can you share your package.json?

**Comment by jasonburrows** [comment]
Sure ('***' are items I wanted to hide, but if I've hidden information you really require let me know).


```
{
  "name": "***",
  "version": "***",
  "license": "***",
  "scripts": {
***
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^9.1.5",
    "@angular/cdk": "^9.2.2",
    "@angular/common": "^9.1.5",
    "@angular/compiler": "^9.1.5",
    "@angular/core": "^9.1.5",
    "@angular/forms": "^9.1.5",
    "@angular/material": "^9.2.2",
    "@angular/platform-browser": "^9.1.5",
    "@angular/platform-browser-dynamic": "^9.1.5",
    "@angular/platform-server": "^9.1.5",
    "@angular/router": "^9.1.5",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fullcalendar/core": "^4.4.0",
    "@ngui/auto-complete": "^3.0.0",
    "@nguniversal/express-engine": "^9.1.0",
    "ngx-sharebuttons": "^8.0.0",
    "@nicky-lenaers/ngx-scroll-to": "^3.0.1",
    "ajv": "^6.12.1",
    "angular2-chartjs": "^0.5.1",
    "angulartics2": "^9.0.0",
    "chart.js": "^2.9.3",
    "component-emitter": "^1.3.0",
    "compression": "^1.7.4",
    "core-js": "^3.6.5",
    "debug": "~4.1.1",
    "domino": "^2.1.5",
    "express": "^4.17.1",
    "font-awesome": "^4.7.0",
    "forever": "^2.0.0",
    "json-size": "1.0.0",
    "keycharm": "^0.3.1",
    "masonry-layout": "^4.2.2",
    "moment": "~2.24.0",
    "ng2-pdf-viewer": "^6.2.0",
    "ngx-clipboard": "^13.0.0",
    "ngx-color-picker": "^9.1.0",
    "ngx-google-places-autocomplete": "^2.0.4",
    "ngx-image2dataurl": "^8.0.0",
    "ngx-lightbox": "^2.1.2",
    "ngx-masonry": "^9.1.1",
    "ngx-pagination": "^5.0.0",
    "numeral": "^2.0.6",
    "primeicons": "^2.0.0",
    "primeng": "^9.0.5",
    "propagating-hammerjs": "^1.4.7",
    "quill": "^1.3.7",
    "randomcolor": "^0.5.4",
    "rxjs": "^6.5.5",
    "rxjs-compat": "^6.5.5",
    "serve-favicon": "~2.5.0",
    "tslib": "^1.10.0",
    "uuid": "^7.0.3",
    "vis-data": "^6.5.1",
    "vis-timeline": "^7.3.4",
    "vis-util": "^4.0.0",
    "zone.js": "^0.10.3"
  },
  "optionalDependencies": {
    "fsevents": "^2.1.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.4",
    "@angular-devkit/core": "^9.1.4",
    "@angular-devkit/schematics": "^9.1.4",
    "@angular/cli": "^9.1.4",
    "@angular/compiler-cli": "^9.1.5",
    "@types/express-serve-static-core": "^4.17.7",
    "@angular/language-service": "^9.1.5",
    "@nguniversal/builders": "^9.1.0",
    "@types/express": "^4.17.0",
    "@types/gapi": "0.0.36",
    "@types/gapi.auth2": "0.0.51",
    "@types/jasmine": "^3.5.10",
    "@types/node": "^13.13.0",
    "codelyzer": "^5.2.2",
    "eslint": "^6.8.0",
    "jasmine-core": "^3.5.0",
    "jasmine-spec-reporter": "^5.0.1",
    "karma": "^5.0.2",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "^3.1.1",
    "karma-jasmine-html-reporter": "^1.5.3",
    "protractor": "^5.4.4",
    "rxjs-tslint": "^0.1.8",
    "ts-loader": "^7.0.0",
    "ts-node": "^8.8.2",
    "typescript": "^3.8.3",
    "webpack-cli": "^3.3.6"
  }
}
```

**Comment by alan-agius4** [comment]
Is the above `package.json` at the root level of the workspace?

**Comment by jasonburrows** [comment]
Yes, and the official upgrade procedure has been used on this project for at least the last 4 versions of Angular.

**Comment by alan-agius4** [comment]
@jasonburrows, is there a way to share a reproduction or the project privately? I tried to replicate the above issue with no success.

**Comment by geromegrignon** [comment]
@jasonburrows it sounds like you made a typo when typing the command as your error message is about `@angluar/core` and not `@angular/core`.

I can reproduce it with the typo : 

```
ng update @angluar/core @angular/cli
Using package manager: 'npm'
Collecting installed dependencies...
Found 29 dependencies.
Package '@angluar/core' is not a dependency.
```

**Comment by alan-agius4** [comment]
@gregmagolan, great hawk eyes 👀 .

Indeed that is the problem.

**Comment by jasonburrows** [comment]
My bad !! Sorry.
