### ISSUE TITLE
Iam using Angular 6 .. while build ng build works and not ng build --prod ... can you help me with these 

### ISSUE THREAD

**Issue by rakeshrio** [angular/angular-cli#18789]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

ERROR in : Type FooterProfileComponent in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/footer-profile/footer-profile.component.ts is part of the declarations of 2 modules: UserprofileModule in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/userprofile/userprofile.module.ts and LazyModule in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/lazy/lazy.module.ts! Please consider moving FooterProfileComponent in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/footer-profile/footer-profile.component.ts to a higher module that imports UserprofileModule in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/userprofile/userprofile.module.ts and LazyModule in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/lazy/lazy.module.ts. You can also create a new NgModule that exports and includes FooterProfileComponent in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/footer-profile/footer-profile.component.ts then import that NgModule in UserprofileModule in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/userprofile/userprofile.module.ts and LazyModule in C:/Users/RAKESH S/Desktop/bikex compression/ontrack/src/app/lazy/lazy.module.ts.

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular-cli/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
