### ISSUE TITLE
No Asset replacement in ng serve

### ISSUE THREAD

**Issue by soyjuanmedina** [angular/angular-cli#18787]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 In the previous version works with the filereplacment option

### Description

 
I update to Angular 10 and have an Issue with the filereplacement in the assets.

I find this bug report

https://github.com/angular/angular-cli/issues/16779

That says it's not a bug and give an alternative, to configure different assets for each environment.

It's works for me, but only when I run ng build, but when run ng serve, the assets not be replace

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.2
Node: 12.18.0
OS: win32 x64

Angular: 10.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic    
... platform-server, router, service-worker
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        10.0.2
@angular/cdk                      10.0.2
@angular/cli                      10.0.2
@angular/fire                     5.4.2
@angular/material                 10.0.2
@ngtools/webpack                  10.0.2
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.6.0
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @soyjuanmedina, can you please provide the reproduction steps? Thanks.

**Comment by soyjuanmedina** [comment]
Hi, thanks.

I'm trying to do it, but I can't achivement.

I create a new proyect:

`ng new testApp`

Then, in the angular.json I add

"production": {...,
              "assets": [
                "src/assets",
                {
                  "input": "src/app/customizations/assets/fav/",
                  "output": "assets/fav/",
                  "glob": "*.ico"
                }
              ],

And create this new favicon in src/app/customizations/assets/fav/

Then I run 

`ng build --prod`

and I expect in dist/testApp/assets/fav have this new favicon (in my project some similar works) but I still have the old one.

My problem in the main app when I run `ng build --prod` works ok, but no when I run `ng serve --prod`

**Comment by spwin** [comment]
Created repo replicating the issue:
https://github.com/spwin/angular-assets-issue-replicate

It looks like `ng serve` and `ng build` are respecting different order when for assets in `angular.json`

**Comment by spwin** [comment]
Temporary solution for me was creating assets sandwich with overriding assets both above and below with the same order:
```
             "assets": [
               {
                 "glob": "**/*",
                 "input": "src/second-override-assets/",
                 "output": "/assets/"
               },
               {
                 "glob": "**/*",
                 "input": "src/first-override-assets/",
                 "output": "/assets/"
               },
               "src/favicon.ico",
               "src/assets",
               {
                 "glob": "**/*",
                 "input": "src/first-override-assets/",
                 "output": "/assets/"
               },
               {
                 "glob": "**/*",
                 "input": "src/second-override-assets/",
                 "output": "/assets/"
               },
             ],
```

Grim but works
