### ISSUE TITLE
This.debug error 

### ISSUE THREAD

**Issue by rnkpareek** [angular/angular-cli#18782]
i was using Angular 7 and then i updated my project to 9.
i added universal to my project by running this command "ng add @nguniversal/express-engine"

all the required files and script were added.

But i am getting error in server.js 
import { existsSync } from 'fs'; (cannot find module fs)
import { APP_BASE_HREF } from '@angular/common';
import { ngExpressEngine } from '@nguniversal/express-engine';
 const distFolder = join(process.cwd(), 'dist/demo/browser');
declare const __non_webpack_require__: NodeRequire;
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {

AND while runnig the commad " npm run dev:ssr" iam getting this.debug is not a function

this.debug is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular.io-example@0.0.0 dev:ssr: `ng run angular.io-example:serve-ssr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular.io-example@0.0.0 dev:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ronak.pandia\AppData\Roaming\npm-cache\_logs\2020-09-14T11_46_47_660Z-debug.log

******THIS IS MY angular.json file *******
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "DEMO": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "aot": true,
            "outputPath": "dist/DEMO/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "./node_modules/@fortawesome/fontawesome-free/css/all.css",
              "./node_modules/bootstrap/dist/css/bootstrap.min.css",
              "./node_modules/ngx-bootstrap/datepicker/bs-datepicker.css",
              "src/styles.scss"
            ],
            "scripts": [
              "src/assets/thenBy.min.js",            
              "node_modules/jquery/dist/jquery.min.js"
             
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            },
            "uat": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.uat.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "DEMO:build",
            "hmrWarning": false
          },
          "configurations": {
            "production": {
              "browserTarget": "DEMO:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "DEMO:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "./node_modules/bootstrap/dist/css/bootstrap.min.css",
              "./node_modules/ngx-bootstrap/datepicker/bs-datepicker.css",
              "src/styles.scss"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/DEMO/server",
            "main": "server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "outputHashing": "media",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "sourceMap": false,
              "optimization": true
            }
          }
        },
        "serve-ssr": {
          "builder": "@nguniversal/builders:ssr-dev-server",
          "options": {
            "browserTarget": "DEMO:build",
            "serverTarget": "DEMO:server"
          },
          "configurations": {
            "production": {
              "browserTarget": "DEMO:build:production",
              "serverTarget": "DEMO:server:production"
            }
          }
        },
        "prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "browserTarget": "DEMO:build:production",
            "serverTarget": "DEMO:server:production",
            "routes": [
              "/"
            ]
          },
          "configurations": {
            "production": {}
          }
        }
      }
    },
    "DEMO-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "DEMO:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "DEMO:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "DEMO"
}
*****PACKAGE.JSON FILE
{
  "name": "demo",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --aot --ssl --hmr",
    "build": "ng build",
    "build-prod": "ng build --prod",
    "build-uat": "ng build --configuration=uat",
    "test": "ng test",
    "lint": "ng lint --typeCheck=true --fix=true",
    "e2e": "ng e2e",
    "dev:ssr": "ng run DEMO:serve-ssr",
    "serve:ssr": "node dist/DEMO/server/main.js",
    "build:ssr": "ng build --prod && ng run DEMO:server:production",
    "prerender": "ng run DEMO:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "9.1.12",
    "@angular/cdk": "9.2.0",
    "@angular/common": "9.1.12",
    "@angular/compiler": "9.1.12",
    "@angular/core": "9.1.12",
    "@angular/forms": "9.1.12",
    "@angular/localize": "^9.1.12",
    "@angular/platform-browser": "9.1.12",
    "@angular/platform-browser-dynamic": "9.1.12",
    "@angular/platform-server": "9.1.12",
    "@angular/router": "9.1.12",
    "@fortawesome/angular-fontawesome": "^0.6.1",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-brands-svg-icons": "^5.13.0",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@ng-bootstrap/ng-bootstrap": "^4.2.2",
    "@nguniversal/express-engine": "^9.1.1",
    "angular-in-memory-web-api": "^0.8.0",
    "bn-ng-idle": "^1.0.1",
    "bootstrap": "^4.5.2",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.4",
    "cors": "^2.8.5",
    "crypto-js": "^3.1.9-1",
    "express": "^4.15.2",
    "file-saver": "^2.0.1",
    "jquery": "^3.5.1",
    "msal": "^0.2.4",
    "ng-block-ui": "^2.1.3",
    "ng2-search-filter": "^0.5.1",
    "ngx-bootstrap": "^5.6.1",
    "ngx-cookie-service": "^2.1.0",
    "ngx-spinner": "^9.0.2",
    "ngx-ui-loader": "^9.1.1",
    "pako": "^1.0.10",
    "primeicons": "^1.0.0",
    "primeng": "^7.1.2",
    "rxjs": "~6.6.3",
    "rxjs-compat": "^6.3.3",
    "save": "^2.4.0",
    "share-buttons": "^1.6.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.12",
    "@angular/cli": "~9.1.12",
    "@angular/compiler-cli": "~9.1.12",
    "@angular/language-service": "~9.1.12",
    "@angularclass/hmr": "^2.1.3",
    "@fortawesome/fontawesome-free": "^5.8.2",
    "@nguniversal/builders": "^9.1.1",
    "@types/express": "^4.17.0",
    "@types/file-saver": "^2.0.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.12.58",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.13.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.12.0",
    "typescript": "~3.8.3"
  }
}

**Comment by alan-agius4** [comment]
Hi @rnkpareek, thanks for opening the issue. However kindly follow the issue template, as this help us triage and tackle issues quicker.

Also, we’d require a minimal reproduction to investigate the issue. You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
