### ISSUE TITLE
This.debug error

### ISSUE THREAD

**Issue by rnkpareek** [angular/angular-cli#18780]
i updated my current project from  angular7 to 9  and iam using node 12.0.0
my project is running fine but when i running the command "ng run dev:ssr", iam getting a error .i.e
this.debug is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
