### ISSUE TITLE
Object.emitResolver.isReferencedAliasDescription

### ISSUE THREAD

**Issue by bendg25** [angular/angular-cli#18792]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, 10.0.8 it was fine

### Description

Upgraded to latest 10.1.1 and can no longer build.

## 🔬 Minimal Reproduction

ng serve

## 🔥 Exception or Error
<pre><code>

ERROR in RangeError: Maximum call stack size exceeded
    at Object.emitResolver.isReferencedAliasDeclaration (/Users/ben/dev/ui-crm-angular/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:79:62)
    at Object.emitResolver.isReferencedAliasDeclaration (/Users/ben/dev/ui-crm-angular/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)
    at Object.emitResolver.isReferencedAliasDeclaration (/Users/ben/dev/ui-crm-angular/node_modules/@angular/compiler-cli/src/transformers/patch_alias_reference_resolution.js:87:53)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.0.0-next.1
Node: 14.7.0
OS: darwin x64

Angular: 11.0.0-next.1
... cli, core
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1001.1
@angular-devkit/build-angular       0.1001.1
@angular-devkit/build-optimizer     0.1001.1
@angular-devkit/build-webpack       0.1001.1
@angular-devkit/core                10.1.1
@angular-devkit/schematics          10.1.1
@angular/animations                 10.1.1
@angular/cdk                        10.2.1
@angular/common                     10.1.1
@angular/compiler                   10.1.1
@angular/compiler-cli               10.1.1
@angular/flex-layout                10.0.0-beta.32
@angular/forms                      10.1.1
@angular/google-maps                10.0.2
@angular/language-service           10.1.1
@angular/localize                   10.1.1
@angular/material                   10.2.1
@angular/material-moment-adapter    10.2.1
@angular/platform-browser           10.1.1
@angular/platform-browser-dynamic   10.1.1
@angular/pwa                        0.1001.1
@angular/router                     10.1.1
@angular/service-worker             10.1.1
@ngtools/webpack                    10.1.1
@schematics/angular                 10.1.1
@schematics/update                  0.1100.0-next.1
rxjs                                6.6.3
typescript                          4.0.2
webpack                             4.44.1

</code></pre>

**Comment by clydin** [comment]
From the version output, it appears that the project has a mixture of versions 10.1 and 11.0 prerelease.  Can you provide the `package.json` for the project?  Also, if possible can you try with version 10.1 of `@angular/cli` and `@angular/core` to see if that solves the problem.

**Comment by bendg25** [comment]
I downgraded all to 10.1.1 and same error occurs:

How best can we debug this sort of issue?


<pre><code>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.1
@angular-devkit/build-angular      0.1001.1
@angular-devkit/build-optimizer    0.1001.1
@angular-devkit/build-webpack      0.1001.1
@angular-devkit/core               10.1.1
@angular-devkit/schematics         10.1.1
@angular/cdk                       10.2.1
@angular/flex-layout               10.0.0-beta.32
@angular/google-maps               10.0.2
@angular/material                  10.2.1
@angular/material-moment-adapter   10.2.1
@angular/pwa                       0.1001.1
@ngtools/webpack                   10.1.1
@schematics/angular                10.1.1
@schematics/update                 0.1001.1
rxjs                               6.6.3
typescript                         4.0.2
webpack                            4.44.1
</code></pre>



package.json


<pre><code>

"dependencies": {
    "@agm/core": "^3.0.0-beta.0",
    "@angular/animations": "^10.1.1",
    "@angular/cdk": "^10.2.1",
    "@angular/cli": "^10.1.1",
    "@angular/common": "10.1.1",
    "@angular/compiler": "10.1.1",
    "@angular/core": "^10.1.1",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^10.1.1",
    "@angular/google-maps": "^10.0.2",
    "@angular/localize": "^10.1.1",
    "@angular/material": "^10.2.1",
    "@angular/material-moment-adapter": "10.2.1",
    "@angular/platform-browser": "10.1.1",
    "@angular/platform-browser-dynamic": "10.1.1",
    "@angular/pwa": "^0.1001.1",
    "@angular/router": "10.1.1",
    "@angular/service-worker": "^10.1.1",
    "@asymmetrik/ngx-leaflet": "^7.0.1",
    "@ng-bootstrap/ng-bootstrap": "^7.0.0",
    "@ngx-loading-bar/core": "^5.1.0",
    "@ngx-loading-bar/router": "^5.1.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@schematics/angular": "^10.1.1",
    "@sentry/browser": "^5.19.2",
    "@stripe/stripe-js": "^1.8.0",
    "@swimlane/ngx-datatable": "^17.1.0",
    "@types/file-saver": "^2.0.1",
    "angular-calendar": "^0.28.16",
    "angular2-image-upload": "^1.0.0-rc.2",
    "angularx-social-login": "^3.2.0",
    "bootstrap": "^4.5.2",
    "browserify-zlib": "^0.2.0",
    "chart.js": "2.9.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "3.6.5",
    "d3": "5.16.0",
    "date-fns": "^2.14.0",
    "deploy-aws-s3-cloudfront": "^3.2.3",
    "deploy-aws-s3-cloudfront-with-cache-contol": "0.0.2",
    "dragula": "3.7.2",
    "easily-gtm": "^1.0.4",
    "exif-js": "^2.3.0",
    "file-saver": "^2.0.2",
    "hammerjs": "2.0.8",
    "image-compressor.js": "^1.1.4",
    "intl": "1.2.5",
    "intl-tel-input": "^17.0.3",
    "json2typescript": "^1.4.1",
    "jstz": "^2.0.0",
    "leaflet": "^1.6.0",
    "lodash": "^4.17.19",
    "moment": "2.27.0",
    "ng-gapi": "0.0.93",
    "ng-intercom": "^8.0.2",
    "ng-knife": "^0.2.8",
    "ng-pick-datetime": "^7.0.0",
    "ng2-charts": "2.3.2",
    "ng2-dragula": "^2.1.1",
    "ng2-file-upload": "1.4.0",
    "ng2-pdf-viewer": "^6.3.2",
    "ng2-right-click-menu": "^1.1.3",
    "ng2-tel-input": "^2.3.0",
    "ng2-timezone-selector": "^0.2.4",
    "ng2-validation": "4.2.0",
    "ngx-avatar": "^4.0.0",
    "ngx-clipboard": "^13.0.1",
    "ngx-color-picker": "^9.1.0",
    "ngx-cookie-service": "^3.0.4",
    "ngx-country-picker": "^2.1.0",
    "ngx-device-detector": "^1.4.5",
    "ngx-file-drop": "^9.0.1",
    "ngx-perfect-scrollbar": "^9.0.0",
    "ngx-quill": "^12.0.1",
    "ngx-social-button": "^1.0.4",
    "ngx-stripe": "^10.1.2",
    "node-sass": "^4.14.1",
    "quill": "^1.3.7",
    "rxjs": "^6.6.3",
    "screenfull": "5.0.2",
    "stacktrace-js": "^2.0.1",
    "stripe-angular": "^1.1.0",
    "web-animations-js": "^2.3.2",
    "webpack": "^4.44.1",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1001.1",
    "@angular/compiler-cli": "^10.1.1",
    "@angular/language-service": "10.1.1",
    "@types/googlemaps": "^3.39.13",
    "@types/jasmine": "~3.5.14",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.10.2",
    "@types/swiper": "^5.4.0",
    "codelyzer": "~6.0.0",
    "cross-env": "^7.0.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "source-map-explorer": "^2.5.0",
    "terser": "5.3.1",
    "ts-node": "~9.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.0.2",
    "webpack-bundle-analyzer": "^3.8.0"
  }


</code></pre>

**Comment by bendg25** [comment]
So whilst not finding the specific root cause.  A bunch of openapi generated typescript files caused the above error.  Once this had been removed, it worked fine.

**Comment by jaidsondantas** [comment]
I have the same problem, after renaming a component, an issue that never happened. where did the cli generate these files?
