### ISSUE TITLE
fix(install): ng install should work with local npm package archives

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#188]
In order to test packages locally, it'd be nice to run: `ng install some-local-package.tar.gz`. Though npm install succeeds with this method, the install process is treating "some-local-package.tar.gz" as the package name, which causes later steps of ng install to fail. Instead, `ng install` should parse the name from package.json after the package is installed.

**Comment by hansl** [comment]
We're going to use `npm` directly in `ng install`. Closing this as this will be addressed. Once `ng install` is done we can revisit this.
