### ISSUE TITLE
Source maps not generated when running with configuration and --watch

### ISSUE THREAD

**Issue by arulprakash88** [angular/angular-cli#18803]
DevTools failed to load SourceMap: Could not parse content.  Project Angular CLI version 9.0.0, also tried this in 10.0.0 by upgrading.

The source maps are not generated while running using the configurations from angular.json file.
main.js.map & vendor.js.map are empty.

ng build --project=myproject --aot --configuration=en --watch

In angular json, I have set it as below. This is to inject the Locale_ID, so that i can read it like @Inject(LOCALE_ID) protected localeId: string .

When running using the configuration, source maps are not generated, but without configuration it works fine.

"en": {
              "aot": true,
              "outputPath": "dist1",
              "i18nLocale": "en"
            },
            "cy": {
              "aot": true,
              "outputPath": "dist2",
              "i18nLocale": "cy"
            }

**Comment by alan-agius4** [comment]
I tried to replicate the above, but I wasn't able. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by arulprakash88** [comment]
I can replicate the issue in 9.0.0 and upgrading to 9.1.12 fix this issue. Thanks
