### ISSUE TITLE
ENOENT: no such file or directory, chmod - while 'ng new'

### ISSUE THREAD

**Issue by Arth95** [angular/angular-cli#1880]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 8.1 with Vagrant Ubuntu 16.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 6.4.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I use Vagrant with bento/ubuntu-16.04 Box
This is my ssh script for installing my env:
`sudo apt-get install -y curl;
sudo apt-get update;
sudo apt-get install -y build-essential;
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -;
sudo apt-get install -y nodejs;
sudo apt-get install -y npm;
npm config set registry http://registry.npmjs.org/;
sudo npm install -g npm;`
After that I install angular-cli without problems, but when it comes to create project with ng new testApp I get error.  I  run vagrant with administrator permissions.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
`ENOENT: no such file or directory, chmod '/vagrant/testApp/node_modules/angular-cli/node_mo
dules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node_module
s/sshpk/bin/sshpk-sign'
Error: ENOENT: no such file or directory, chmod '/vagrant/testApp/node_modules/angular-cli/
node_modules/angular-cli/node_modules/npm/node_modules/request/node_modules/http-signature/node
_modules/sshpk/bin/sshpk-sign'
    at Error (native)`

**Comment by filipesilva** [comment]
I can't really say, this seems like it may be a vagrant specific issue, on a depdendency of a dependency of a dependency.

If I had to bet... maybe something regarding `npm` itself. Not sure to be honest.

**Comment by filipesilva** [comment]
I looked around a bit and it seems to be this: https://github.com/npm/npm/issues/9633#issuecomment-192328724

Closing here then.
