### ISSUE TITLE
error running yarn start with Bazel in Angular app

### ISSUE THREAD

**Issue by sohinim98** [angular/angular-cli#18805]
I was trying to use Bazel to build an Angular app. Here are the things I did -

`yarn ng add @angular/bazel`
`yarn global add @angular/bazel`
`yarn add @bazel/bazelisk`
`yarn global add @bazel/bazel@2.1.0`
`yarn global add @bazel/bazelisk@^1.6.1`
( Because the `package.json` file had those versions) I still get the error -

```
iBazel [3:32PM]: Error getting Bazel info exit status 2
iBazel [3:32PM]: Querying for files to watch...
INFO: Reading rc options for 'query' from /Users/sohinimukherjee/frontend/question-ingestion/.bazelrc:
  Inherited 'common' options: --experimental_allow_incremental_repository_updates
ERROR: --experimental_allow_incremental_repository_updates :: Unrecognized option: --experimental_allow_incremental_repository_updates
```
when I run yarn start which basically runs node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve

**Comment by alan-agius4** [comment]
Hi @serhiisol,

Opting in Bazel with `@angular/bazel` Is no longer supported by the Angular tooling team.

If you want to build Angular using Bazel, read: https://dev.to/bazel/angular-bazel-leaving-angular-labs-51jaRe

**Comment by sohinim98** [comment]
@alan-agius4 I see - the link is broken btw.

**Comment by alan-agius4** [comment]
Linking updated
