### ISSUE TITLE
Add the ability to skip dependencies with ng update 

### ISSUE THREAD

**Issue by pavankjadda** [angular/angular-cli#18813]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
At present when I do `ng update --all`, the command fails when it finds incompatible dependencies(Attached image). I force update all dependencies and revert back incompatible dependencies through a shell script

<img width="1114" alt="Screen Shot 2020-09-17 at 4 46 35 PM" src="https://user-images.githubusercontent.com/17564080/93526467-7e757100-f905-11ea-9db3-31eb00fa1b09.png">

### Describe the solution you'd like
Provide the ability to skip dependencies through flag like below
```
ng update --all --skip "zone.js"
```

### Describe alternatives you've considered
I have a script that force updates the all dependencies and reverts incompatible dependencies 
```
### Update all dependencies
ng update --all --force

### Install compatible zone.js version
npm i zone.js@0.10.3 --save

```

**Comment by alan-agius4** [comment]
Also related to https://github.com/angular/angular-cli/issues/15296

**Comment by pavankjadda** [comment]
@alan-agius4 Does this mean we have to use `npm update` command from now on? When will this change be pushed to CLI npm package?

**Comment by alan-agius4** [comment]
@pavankjadda, yes. For packages which do not support`ng update` will only work for packages that support `ng update`.
