### ISSUE TITLE
ng command no found

### ISSUE THREAD

**Issue by hmuschett** [angular/angular-cli#1881]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
node -6.2.1

Installed angular-cli globally using (npm install -g angular-cli) but when I'm trying to create project using ng new my-project it is throwing error (ng: command not found) and try --help and some say 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alexverdaguer** [comment]
Same here

**Comment by catull** [comment]
Freshly installed globally, `ng --version` gives me

```log
➜  npm install -g angular-cli

[ ... ]
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
[ ... ]

➜  ng --version

angular-cli: 1.0.0-beta.10
node: 6.4.0
os: darwin x64
```

**Comment by hmuschett** [comment]
hi @catull how to chenge de path in windows??

**Comment by catull** [comment]
You do not change anything, the line above ist just to show that `npm install` creates a symbolic link.  I am afraid I cannot advise you with a Windows installation of nodeJS and npm.

**Comment by hmuschett** [comment]
ng --sersion nir ng --help nither work for me and at /usr/local/lib/node_modules i have all pakages of angular-cli  i do not know work  the CLI

**Comment by SeekingMonkey** [comment]
Installing node 6.5 resolved this for me.

**Comment by hmuschett** [comment]
@SeekingMonkey i install  node  6.5 nothing and nothing remains the same errror not ng command not found

**Comment by filipesilva** [comment]
This seems to be roughly the same issue as https://github.com/angular/angular-cli/issues/1930. Basically, the solution is to uninstall node and reinstall 6.5. 

It seems due to a node/npm problem.

**Comment by invious** [comment]
I am on Mac OSX Sierra and I installed Node using the installer on the site because I thought that brew was giving me the issues -- turns out ng isn't installing with either method.

```
Aymons-MacBook-Air:MyProjects aymon$ npm list -g --depth=0
/Users/aymon/.npm-packages/lib
├── angular-cli@1.0.0-beta.22-1
├── portfinder@1.0.10
└── reflect-metadata@0.1.8

Aymons-MacBook-Air:MyProjects aymon$ npm -v
3.10.9
Aymons-MacBook-Air:MyProjects aymon$ ng --version
-bash: ng: command not found
Aymons-MacBook-Air:MyProjects aymon$
```

**Comment by moussazy** [comment]
@vitalizis you can add to path of system, export PATH="$PATH:$HOME/npm/bin". To changes work better add this export in your ~/.bashrc
--

**Comment by moussazy** [comment]
I solved it using ===> export PATH="$PATH:$HOME/npm/bin"
