### ISSUE TITLE
How to dynamically create/modify sitemap.xml file in angular 9 project structure at runtime?

### ISSUE THREAD

**Issue by Topiya** [angular/angular-cli#18824]
How to create dynamic sitemap.xml file in Angular 9 project structure ? I can get data using HTTP get request from node API but using this data how can I update local xml file from angular project at runtime ? 

In my case, angular project and node project are on different server(different domain). And It is possible to create xml file in node project but I am not able to access that file  as xml file in angular project root . 

Can anyone please suggest me how to use node xml in angular project OR is it possible to create/modify dynamic sitemap.xml using api call in Angular 9?

Any help would be greatly appreciated.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
