### ISSUE TITLE
ng update fails on zone.js

### ISSUE THREAD

**Issue by christian-steinmeyer** [angular/angular-cli#18825]
# 🐞 Bug report

### Command (mark with an `x`)

<pre><code>
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
</code></pre>

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Updating from version 8.2.14 fails with an incompatible peer dependency on zone.js. When using the `--force` flag, the new project fails with out of memory errors.

## 🔬 Minimal Reproduction

`ng update --all=true`

## 🔥 Exception or Error
<pre><code>
Package "@angular/core" has an incompatible peer dependency to "zone.js" (requires "~0.10.3", would install "0.11.1")
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.2
Node: 12.18.4
OS: win32 x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@angular/cdk                    10.2.1
@angular/fire                   6.0.2
@angular/material               10.2.1
@schematics/angular             10.1.2
@schematics/update              0.1001.2
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

I saw #15296 and other issues related, but they usually refer to typescript, not zone.js. Perhaps someone knows the last compatible version of zone.js?

**Comment by alan-agius4** [comment]
Related to https://github.com/angular/angular-cli/issues/18813 and #15296 (The original issue is actually mentions this same error.)

The last compatible version of zone.js is 10.3.
