### ISSUE TITLE
feat(app.component): Move default boilerplate styles into their own css-file

### ISSUE THREAD

**Issue by KariNarhi** [angular/angular-cli#18829]
#### Feature Description

When creating a new boilerplate app with `ng new`, the default styles are put at the top of **app.component.html**, even though the command also creates **app.component.css**, but leaves it empty. This forces the user to move and / or remove the default style from **app.component.html**.

The feature I am suggesting is to generate the default boilerplate app so that the default **app.component** styles are put inside the intended css-file.

#### Use cases

Lessen the amount of boilerplate cleaning inside app.component.html

**Comment by alan-agius4** [comment]
Hi @KariNarhi, Having everything in `app.component.html` is actually intended to lessen the amount of files the user needs to modify when removing the boilerplate code.

**Comment by alan-agius4** [comment]
There is more context in this PR https://github.com/angular/angular-cli/pull/14403
