### ISSUE TITLE
Remove baseUrl in tsconfig.json

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#18834]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/

> paths without baseUrl
> Using path-mapping is fairly common – often it’s to have nicer imports, often it’s to simulate monorepo linking behavior.
> 
> Unfortunately, specifying paths to enable path-mapping required also specifying an option called baseUrl, which allows bare specifier paths to be reached relative to the baseUrl too. This also often caused poor paths to be used by auto-imports.
> 
> In TypeScript 4.1, the paths option can be used without baseUrl. This helps avoid some of these issues.

We can remove baseUrl in tsconfig now!

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/7964

**Comment by xiaoxiangmoe** [comment]
Can we remove baseUrl in tsconfig.json？
WebStorm and VSCode support it now.

**Comment by xiaoxiangmoe** [comment]
Can we remove baseUrl in tsconfig.json？
WebStorm and VSCode support it now.

**Comment by Gaghyta** [comment]
Hola, gente. Estoy teniendo muchas dudas (y encontrando muy poca información) sobre el contenido del json de tsconfig. Especialemente se me presentó la duda con el **baseUrl del tsconfig.json**. Una compañera decidió dejar esos archivos y cada vez que uno se baja cambios se terminan generando conflictos. Miré las diferencias y me encuentro con que su tsconfig.json tiene como baseUrl el valor **"./"**, mientras que yo obtengo la compilación correcta con mi archivo que tiene baseUrl con valor **""** (vacío) No sé a qué se debe esta diferencia en la baseUrl y estaba buscando información sobre los usos y consecuencias de la misma.
Agradezco cualquier información que puedan compartir o experiencias personales.

También vi que hay un tema de diferencia en la creación de componentes, en algunos casos se hace automáticamente con  el import del Component, y en otros casos con el NgInit. Lo mismo replicado dentro de la class export, en algunos casos está vacía, en otros predeterminada dentro, incluyendo el constructor vacío, el NgInit y el tipo void 

Al momento, y habiendo iniciado a utilizar Angular hace nada de tiempo, no llego a entender las diferencias de estas configuraciones a nivel de proyecto y si son un tema del cambio de versión de Angular, o si realmente esto de alguna forma afectaría.

Saludos
