### ISSUE TITLE
Consider removing protractor as the default E2E tool

### ISSUE THREAD

**Issue by rooby** [angular/angular-cli#18844]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The default E2E tool that is provided is protractor, which appears to be effectively unmaintained and doesn't seem to have any kind of road map or any communications from the maintainers that would make me think that's going to change any time soon.

I think that there is a high chance that new users will either just use the provided tool by default and not think twice about it, or they would give extra weight to the provided solution when weighing up options (I know I have done that in the past) and then go on to possibly regret that choice (or resent the default they didn't realise they could change).

I think we should stop steering people in that direction.

### Describe the solution you'd like

I think it would be preferable to either ship with a tool that is actively maintained or to ship without a default tool at all and just provide documentation on how to configure the tool of their choice (just the Angular specific docs, they can get tool specific docs from the tool they choose).

### Describe alternatives you've considered

If I'm wrong about the maintenance status of protractor, then a possible alternative is that it becomes an actively maintained, 
 user friendly solution that's worthy of the default tool status.

**Comment by Brandinga** [comment]
https://angular.io/guide/roadmap#update-our-e2e-testing-strategy

**Comment by rooby** [comment]
> https://angular.io/guide/roadmap#update-our-e2e-testing-strategy

I've seen that, however that doesn't really mean anything by itself. It's too vague.
There is no timeline, no github issues to track the progress or decision making conversation, and there's no date for when that was written so you don't know if it's a recent thing and we still need to give people time to work things out or if it's been in that list for a long time and progress has stalled.

**Comment by ChristopherKiss** [comment]
As a side note, there are also no docs on how to even write e2e tests or use Protractor (as apposed to their fantastic unit test section which is incredibly detailed).

I requested more info almost 2 years ago: https://github.com/angular/angular/issues/28968

Which didn't see any progress from the looks of it. Would be great to get official direction on the state of e2e with Angular.

**Comment by rooby** [comment]
There still seems to have been no progress on development or documentation for the Protractor project.
The protractor release version mismatch between github and npm also hasn't been addressed.
The issues in the Protractor issue queue seem to generally go unanswered.

Please can we stop encouraging users to use this approach for E2E?
