### ISSUE TITLE
ng generate interceptor - no schematic "interceptor" found.

### ISSUE THREAD

**Issue by AndrewPomorski** [angular/angular-cli#18840]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

It seems like this has worked previously.

### Description

Not able to generate an interceptor from schematic in ng cli 10.1.2

## 🔬 Minimal Reproduction

run `ng g interceptor <interceptor-name>`

## 🔥 Exception or Error
<pre><code>
An unhandled exception occurred: Schematic "interceptor" not found in collection "@schematics/angular".
See "/private/var/folders/q2/xny4d6016zz_0pdpg8cjybcr0000gn/T/ng-rA8whv/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.2
Node: 14.9.0
OS: darwin x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            8.0.0
@angular-devkit/schematics      8.0.0
@schematics/angular             8.0.0
@schematics/update              0.1001.2
rxjs                            6.5.5
typescript                      3.9.7
webpack                         4.44.2
</code></pre>

**Comment by alan-agius4** [comment]
Hi @AndrewPomorski,

It looks like you have several outdated versions of `@angular-devkit` and `@schematics` packages. 

Do you have those packages listed as dev dependencies/dependencies in your package.json?

**Comment by AndrewPomorski** [comment]
Hi @alan-agius4 thanks for replying. 

Indeed, I do have `@angular-devkit/build-angular` in my devDependencies. However, no packages related to `@schematics`.

<details>
<summary>my package.json</summary>
<p>

```
"devDependencies": {
    "@angular-builders/custom-webpack": "^10.0.0",
    "@angular-builders/dev-server": "^7.3.1",
    "@angular-devkit/build-angular": "^0.1001.0",
    "@angular-extensions/lint-rules": "^1.2.0",
    "@angular/cli": "~10.1.0",
    "@angular/compiler-cli": "~10.1.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.12.54",
    ...
}

```

</p>
</details>

**Comment by alan-agius4** [comment]
This is likely caused by module hoisting .

Try to remove node_modules, lock file and do a fresh install.
```
rm -rf node_modules package-lock.json
npm i 
```

If the problem persists, kindly provide the output of 

```
npm ls @schematics/angular 
```

**Comment by AndrewPomorski** [comment]
I've tried reinstalling my node_modules already, but to no effect. 

`npm ls @schematics/angular` prints

```
├─┬ @angular/cli@10.1.2
│ └── @schematics/angular@10.1.2 
└─┬ ngx-build-plus@10.1.1
  └── @schematics/angular@8.0.0 
```
