### ISSUE TITLE
No tsconfig.base.json in newly created projects

### ISSUE THREAD

**Issue by synec** [angular/angular-cli#18859]
Hi there!

Today I tried to update some projects to angular 10.x. Unfortunately it did not work at all, because I always run into the issue mentioned in #18130

To investigate the issue and get an idea I tried to create a completely new project using `ng new`. 

Surprisingly a newly created project also does not include a `tsconfig.base.json` file. 

# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Don't know.

### Description

Newly created project does not include `tsconfig.base.json`

## 🔬 Minimal Reproduction

I started from scratch with a newly installed node 12.18.4 (with `nvm`) without any global module installed.

Then I installed `@angular/cli` via 
<pre><code>npm i -g @angular/cli</code></pre>

Next, I created new project with CLI:
<pre><code>ng new test --routing --style scss</code></pre>

I project gets created without errors. It contains `tsconfig.app.json`, `tsconfig.json` and `tsconfig.spec.json`, but no `tsconfig.base.json`.

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.2
Node: 12.18.4
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.2 (cli-only)
@angular-devkit/core         10.1.2 (cli-only)
@angular-devkit/schematics   10.1.2 (cli-only)
@schematics/angular          10.1.2 (cli-only)
@schematics/update           0.1001.2 (cli-only)
</code></pre>

**Comment by clydin** [comment]
In version 10.0, the `tsconfig.base.json` file was used to implement TypeScript's solution style configuration.  Version 10.1 removed usage of TypeScript's solution style configuration and the `tsconfig.base.json` file was removed as a result.
For further details on this change and why it happened, please see the following pull request: https://github.com/angular/angular-cli/pull/18478.

**Comment by synec** [comment]
@clydin Thanks for the quick reply!
I expected to see an `tsconfig.base.json` because https://update.angular.io/?l=3&v=9.1-10.0 shows the following in the *During the update* section:

> Angular now recommends the use of a tsconfig.base.json to help organize the various typings contexts (shared, unit tests, end to end tests, application, etc). ng update will migrate you automatically.

I hope it will be removed for 10.1.x to avoid confusion.

**Comment by synec** [comment]
@clydin gave an explanation and @alan-agius4 updated the docs. Thanks guys!
