### ISSUE TITLE
Importing styles with inline loaders leads to commonjs dependencies warning

### ISSUE THREAD

**Issue by artaommahe** [angular/angular-cli#18858]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ng9

### Description

Import e.g. some global styles via inline loaders in component's file
```ts
import '!style-loader!css-loader!./some-global-styles.css';
```
start server or build and see a commonjs dependencies  usage warning

```
WARNING in D:\projects\issues\angular-cli-styles-require-common-js-warning\src\app\app.component.ts depends on '!style-loader!css-loader!./some-global-styles.css'. CommonJS or AMD 
dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

## 🔬 Minimal Reproduction

- clone https://github.com/artaommahe/angular-cli-styles-require-common-js-warning
- run server `yarn start`
- see warning

## 🔥 Exception or Error
<pre><code>
WARNING in D:\projects\issues\angular-cli-styles-require-common-js-warning\src\app\app.component.ts depends on '!style-loader!css-loader!./some-global-styles.css'. CommonJS or AMD 
dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
</code></pre>

## 🌍 Your Environment
<pre><code>
PS D:\projects\issues\angular-cli-styles-require-common-js-warning> yarn ng version
yarn run v1.16.0
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.2
Node: 12.18.1
OS: win32 x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@schematics/angular             10.1.2
@schematics/update              0.1001.2
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
This is expected as the `style-loader` generates `commonjs` code by default.  The `style-loader` has an `esModule` option ([documentation](https://webpack.js.org/loaders/style-loader/#esmodule)) which enables module code usage.  For information regarding specifying loader options with the inline syntax, please see: https://webpack.js.org/concepts/loaders/#inline

Also please note that while usage of Webpack specific features is possible, it is not officially supported.
