### ISSUE TITLE
Problem when create a project with ng new

### ISSUE THREAD

**Issue by albert10001** [angular/angular-cli#18862]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

I can not create an angular 10 project. Whe I try the cmd show:
npm ERR! Unexpected end of JSON input while parsing near '...XqFMMAvHk\nsaa5Fimz0d'.
OS: Windows 10. 64bits
node version: 12.18.4
NPM version: 6.14.8
I have tried with: 
npm cache clean --force
npm cache verify
Below You can see an image with the issue.
**Postdata**: I am behind a proxy and I use a vpn.
![Captura](https://user-images.githubusercontent.com/71787482/94056103-dc91d080-fdab-11ea-8925-d3ec8fed6ea5.PNG)
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by albert10001** [comment]
> 
> 
> This seems like a problem with your node/npm and not with Angular CLI.
> 
> Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

Hello alan-agius4. I tried at home without proxy and vpn and that was ok. The thing I don´t understand is why angular is installed at work ok but I can not create a project?

**Comment by alan-agius4** [comment]
@albert10001, I don’t know you what type of proxy and environment you have. Might be that your proxy is also caching node packages and they got corrupted at that level or maybe some bytes are being lost over the wire during download.

The above errors though typically indicate a form of corruption.
