### ISSUE TITLE
Add i18n locales for different languages dynamically in angular.json

### ISSUE THREAD

**Issue by bobKasbi** [angular/angular-cli#18861]
# 🚀 feature request

### Relevant Package
@angular/cli

### Description
I would like to add multiple XLF translation files as much as I need in: `/assets/i18n` folder based on the languages I want to support. But I don't want to be forced to edit `angular.json` file and add the specific path for these languages manually in `angular.json`. The path for those files should be added dynamically to `angular.json`.
```
"i18n": {
     "locales": {
           "en": "src/assets/i18n/messages.en.xlf",
            "it": "src/assets/i18n/messages.it.xlf",
            "es": "src/assets/i18n/messages.es.xlf",
            "xx": "src/assets/i18n/messages.xx.xlf",
            "xx": "src/assets/i18n/messages.xx.xlf",
            ...,
            ...
    }
}
```

### Describe the solution you'd like
May be a kind of property in env file (An array of objects - Key/value pair as language and its path) 

### Describe alternatives you've considered
Same as in the description

Have been searching but unfortunately didn't find any significant solution or hint. Thanks!

**Comment by alan-agius4** [comment]
Hi @bobKasbi,

Indeed locales needs to be defined in `angular.json` and adding dynamic entries to `angular.json` is not in scope of the Angular CLI.

Some side notes:
1) Translations files can be located anywhere within the workspace and reused by multiple projects.
2) Multiple translations files can be merged together. Ex:
```json
"i18n": {
  "locales": {
    "en": [
      "src/i18n/messages.en-0.xlf",
      "src/i18n/messages.en-1.xlf",
    ]
  }
}
```

Mind if I ask you what's the use-case of wanting to add these dynamically?

**Comment by bobKasbi** [comment]
Sure. The background is that I do have a customer who has an access to `/assets/i18n` folder so, that he/she just need/want to load the XFL files for languages they want to support, and the app should be translatable into these languages on the fly without that I  - as a developer - have to add the references extra in `angular.json`. Otherwise, as I said,  I have to be contacted and have to edit `angular.json` each time once the customer adds a new language.

**Comment by alan-agius4** [comment]
Hi @bobKasbi, thanks for the explanation. This is quite a particular use-case which doesn't fall in scope of the Angular CLI.

> should be translatable into these languages on the fly

For your use-case runtime localization is a better fit, so that you don't need to re-build and re-deploy on every change. At the moment we don't have a good story or documentation about this topic. While this is totally doable at the moment, you'll be venturing off the beaten track. See: https://github.com/angular/angular/issues/38953

You can also opt to use a 3rd party library such as https://github.com/loclapp/locl/tree/master/libs/core to achieve this.

**Comment by bobKasbi** [comment]
We actually avoid to use 3rd party libraries (couple of issues related to dependencies and upgrades etc. ) as much as possible, and also violating the angular concept implementing some crazy workarounds is not a part of our vision.
