### ISSUE TITLE
Upgrading to 10.1.3 from 10.0.6; ng test not running anymore

### ISSUE THREAD

**Issue by jkainth** [angular/angular-cli#18878]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Worked in 10.0.6

### Description
node v12

ng build works on 10.1.3; app works just fine
ng test gets stuck indefinitely; 

Turning log level in karma to debug, seems like it gets stuck here:
....
24 09 2020 17:44:07.880:DEBUG [plugin]: Loading inlined plugin (defining reporter:kjhtml).
24 09 2020 17:44:07.880:DEBUG [plugin]: Loading inlined plugin (defining reporter:coverage-istanbul).
24 09 2020 17:44:07.881:DEBUG [plugin]: Loading inlined plugin (defining framework:@angular-devkit/build-angular, reporter:@angular-devkit/build-angular--sourcemap-reporter, reporter:@angular-devkit/build-angular--event-reporter, middleware:@angular-devkit/build-angular--blocker, middleware:@angular-devkit/build-angular--fallback).

## 🔬 Minimal Reproduction

Not sure how to:
Tried ng new with same version of cli.
ng test works.

Compared my project package.json, karma.config - they are all the same.
Cannot explain

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.3
Node: 12.18.4
OS: win32 x64

Angular: 10.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, upgrade
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.3
@angular-devkit/build-angular      0.1001.3
@angular-devkit/build-ng-packagr   0.1001.3
@angular-devkit/core               10.1.3
@angular-devkit/schematics         10.1.3
@angular/cdk                       10.1.1
@schematics/angular                10.1.3
@schematics/update                 0.1001.3
ng-packagr                         10.0.3
rxjs                               6.5.5
typescript                         3.9.7

</code></pre>

**Comment by alan-agius4** [comment]
Hi @jkainth, unfortunately without a reproduction it's close to impossible to find the problem.

Try to remove package-lock.json and node_modules and see if that helps.

```
rm -rf package-lock.json node_modules
npm i
```

**Comment by jkainth** [comment]
I forgot to mention in my issue description:

Tried deleting package-lock, deleting node_modules and npm install  = no luck
Tried upgrading to node 14 + above packaga-lock deletion ect = no luck

FYI my library projects under the same angular application - they all run well with ng test 'lib-name'
Just my default main app - thats the one getting stuck.

For context - the next step after where its getting stuck in karma - is Angular initiating compilation;
So either one of the middlewares is busted - not sure. Need more logging to figure what is actually happening

**Comment by jkainth** [comment]
@alan-agius4  I turned karma logger to be on debug to see more details.
Any other secret command line flags etc in angular cli to see what is happening, some where to see error logs etc?

**Comment by jkainth** [comment]
Ok never mind.... 

I let the **ng test mainApp** run and go for coffee.
Came back after **20 mins** and then it just continued.
The next run ran immediately. 

Seems like its heavily caching or building something for the first time.
PS doing a normal **ng build mainApp** even on first run is immediate.

Its a nuisance it took that long with no feedback - i almost rolled back. 
But its a one time pain we can live with
