### ISSUE TITLE
SchematicContext.addTask add task with reversed order

### ISSUE THREAD

**Issue by BorjaFTW** [angular/angular-cli#18886]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know.

### Description

I'm coding a custom Schematic, when I try to add multiple tasks with SchematicContext.addTask, they executed with reversed order. I think that it should be executed at natural order. I mean, tasks should be a queue not a stack.

## 🔬 Minimal Reproduction

Create an 'example' blank schematic and just write a console.log.
Execute the next schematic at blank Angular project.

<pre><code>
import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { RunSchematicTask } from '@angular-devkit/schematics/tasks';

// You don't have to export the function as default. You can also have more than one rule factory
// per file.
export function base(_options: any): Rule {
  return (tree: Tree, _context: SchematicContext) => {

      _context.addTask(new RunSchematicTask('@angular/material', 'ng-add', {
          ..._options,
      theme: "custom",
      typography: true,
      animations: true
    }));
    _context.addTask(new RunSchematicTask('example', _options));
    
    return tree;
  };
}
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.0
Node: 12.18.3
OS: win32 x64

Angular: undefined
...
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.0 (cli-only)
@angular-devkit/core         10.1.0
@angular-devkit/schematics   10.1.0
@angular/cdk                 10.2.2
@schematics/angular          10.1.0
@schematics/update           0.1001.0 (cli-only)
rxjs                         6.6.2
typescript                   4.0.2
</code></pre>

**Comment by clydin** [comment]
Task execution order is indeterminate if the task has no dependencies.  The tasks can also potentially be executed in parallel as well.  For tasks that have the have a defined order of execution, dependencies should be passed when `addTask` is called.  
For an example, please see the Angular ng-new schematic where the git initialization is dependent on the package manager task(s): https://github.com/angular/angular-cli/blob/c6aeb60f4d6c393d101612b017c780d634bf591f/packages/schematics/angular/ng-new/index.ts#L79-L105

**Comment by alan-agius4** [comment]
Closing as answered in the above comment.
