### ISSUE TITLE
command completion is invalid with 1.0.0-beta.11-webpack.8 

### ISSUE THREAD

**Issue by goorockey** [angular/angular-cli#1889]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

    Ubuntu latest 16.04 LTS

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

    angular-cli: local (v1.0.0-beta.11-webpack.8, branch: master)
    node: 6.5.0
    os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

    git clone https://github.com/angular/angular-cli.git
    cd angular-cli
    npm link
    ng completion

4. The log given by the failure. Normally this include a stack trace and some
   more information.

    $ ng completion
    The specified command completion is invalid. For available options, see `ng help`.

5. Mention any other details that might be useful.

    After  looking around the source code in `addon/ng2/index.js`, I think the problem is that    `command/completion` has not `default` exports. 
    It should work after refactoring `completion.js` to `completion.ts` and having default export according to other commands.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by goorockey** [comment]
BTW, `make-thie-awesome` is also invalid with the same reason.

**Comment by catull** [comment]
`make-this-awesome` explicitly only works in a project directory generated by `ng new`.
The behaviour you describe manifests if you execute the command outside of such a directory.

**Comment by goorockey** [comment]
@catull `make-this-awesome` doesn't work in project directory with the lastest version `1.0.0-beta.11-webpack.8`.
It's because of commit 8be7096bf6f3ff58cf011962c644b2bdc259e5e1, which does not published to npm registry.

**Comment by catull** [comment]
Sorry about that, your issue title does not reflect you tried it with that constellation.
Neither do you state it up until now.

**Comment by goorockey** [comment]
@catull My fault and the title is updated. :smile:

**Comment by catull** [comment]
The project has not been building for a while.
The reason is in my opinion due to a broken '@angular/tsc-wrapped' dependency.
Currently, that module's version 0.2.2 barfs up, see issue #1853.

If you locally replace node_modules/@angular/tsc-wrapped with a more recent release from https://github.com/angular/tsc-wrapped-builds/releases, then the project builds again.
