### ISSUE TITLE
Webpack 5 warning

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular-cli#18895]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

```
(node:60756) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:60756) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
Warning: Circular dependency detected:
src/styles.scss -> src/styles.scss
```

## 🔬 Minimal Reproduction

```
yarn global add @angular/cli@next
ng new test-webpack5 
cd test-webpack5 
add `"resolutions": { "webpack":"5.0.0-rc.0" }` in package.json
yarn install
yarn start
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.3
@angular-devkit/build-angular   0.1100.0-next.3
@angular-devkit/core            11.0.0-next.3
@angular-devkit/schematics      11.0.0-next.3
@schematics/angular             11.0.0-next.3
@schematics/update              0.1100.0-next.3
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

**Comment by valorkin** [comment]
hello, all deprecation warning are listed here https://github.com/angular/angular-cli/pull/18873#issuecomment-699852827
there are will be 5 PRs to fix those, and one is one the way https://github.com/angular/angular-cli/pull/18911
