### ISSUE TITLE
fix(install): ng install should not require bundles

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#189]
I couldn't find an issue for this already, but I think there's already a goal for the install process to not require bundles to be included in the installed package. Ideally the `main` file from a package.json could be used as an entry point to grab the lib's modules and include them in build artifacts.

**Comment by jkuri** [comment]
Is this possible? `node_modules` directory is not accessible from the `dist/` dir.

**Comment by jkuri** [comment]
Also, bundles will not be needed anymore as of TS 1.8.

**Comment by jeffbcross** [comment]
> Is this possible? node_modules directory is not accessible from the dist/ dir.

I meant that the process that currently builds/moves files to `dist` should be able to move the correct files from `node_modules/some_package` to `dist/some_package`, or bring the required files into the app bundle using systemjs-builder.

**Comment by jkuri** [comment]
Okay, that makes sense.

**Comment by hansl** [comment]
We removed the `install` feature temporarily, while working on a design doc. So closing this.
