### ISSUE TITLE
The worker-plugin upgrade to 5.0.0 for angular-cli 9

### ISSUE THREAD

**Issue by PolanZ** [angular/angular-cli#18901]
# 🚀 Feature request
worker-plugin @4.0.3 may throw warning
`WARNING in new Worker() will only be bundled if passed a String.`

maybe upgrade to `5.0.0` Solved.
https://github.com/GoogleChromeLabs/worker-plugin/pull/73

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

**Comment by alan-agius4** [comment]
Hi @PolanZ,

Angular CLI version 9 is currently LTS and only critical and security fixes are merged in LTS versions.

More info: https://angular.io/guide/releases#lts-fixes
