### ISSUE TITLE
Why not provide an off option? ---> " CommonJS or AMD dependencies can cause optimization bailouts."

### ISSUE THREAD

**Issue by sguot** [angular/angular-cli#18916]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] serve
- [ ] new
- [ ] build
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Provide a configuration to turn it off，ingore warning！

```
WARNING in .... depends on 'core-js/modules/es.regexp.to-string'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in .... depends on 'core-js/modules/es.function.name'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

WARNING in .... depends on 'core-js/modules/es.array.slice'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
....
```

### Describe the solution you'd like
```
"allowedCommonJsDependencies": "ture"
```

### Describe alternatives you've considered
Provide a wildcard。

```
allowedCommonJsDependencies:['file-saver',"core-js/*"]
```

**Comment by alan-agius4** [comment]
Hi @sguot, 

You can use the module ID, to allow the entire CJS module to be used.

Example:

```json
allowedCommonJsDependencies":["core-js"]
```

The reason why it is not possible to turn off this feature entirely is so that users don't accidentally introduce new CJS modules in their application.

**Comment by sguot** [comment]
> Hi @sguot,
> 
> You can use the module ID, to allow the entire CJS module to be used.
> 
> Example:
> 
> ```json
> allowedCommonJsDependencies":["core-js"]
> ```
> 
> The reason why it is not possible to turn off this feature entirely is so that users don't accidentally introduce new CJS modules in their application.

I tried and failed before, but now I can, thank you!
