### ISSUE TITLE
cannot create the new project

### ISSUE THREAD

**Issue by ashutosh-gole** [angular/angular-cli#18954]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
![Screenshot from 2020-10-02 13-56-59](https://user-images.githubusercontent.com/42404803/94903324-40587f80-04b7-11eb-99b3-c37bbe661ec0.png)

Angular CLI: 10.1.4
Node: 12.18.4
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.4 (cli-only)
@angular-devkit/core         10.1.4 (cli-only)
@angular-devkit/schematics   10.1.4 (cli-only)
@schematics/angular          10.1.4 (cli-only)
@schematics/update           0.1001.4 (cli-only)

[🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑](url)

**Comment by ashutosh-gole** [comment]
**Installing packages ....** messages show from 1 hour but not create node_modules folder in the project.

**Comment by ohois** [comment]
Check if you've got the  npm cache folder.

It should be located under ~/.npm

Remove it and try again.

If the problem still exists try

ng new test --skip-install
cd ./test
npm i

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
