### ISSUE TITLE
Curly brace positioned incorrectly in new angular.json file

### ISSUE THREAD

**Issue by EatonZ** [angular/angular-cli#18968]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Perhaps, but not recent.

### Description

When creating a new project, the very end of `angular.json` has 2 curly braces on the same line next to each other. The second one should be indented on the next line.

## 🔬 Minimal Reproduction

Create a new project with `ng new`, scroll to the very bottom of the created `angular.json` file, and notice the 2 curly braces right above `defaultProject`.

## 🌍 Your Environment
<pre>Angular CLI: 10.1.4
Node: 14.13.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.4 (cli-only)
@angular-devkit/core         10.1.4 (cli-only)
@angular-devkit/schematics   10.1.4 (cli-only)
@schematics/angular          10.1.4 (cli-only)
@schematics/update           0.1001.4 (cli-only)</pre>

**Anything else relevant?**

How it looks now:

![Bug](https://user-images.githubusercontent.com/3020941/95007374-f7025000-05dc-11eb-9385-ac8c7fb5a868.png)

How it should look:

![Fixed](https://user-images.githubusercontent.com/3020941/95007377-fec1f480-05dc-11eb-815f-a72fd5017360.png)

**Comment by alan-agius4** [comment]
Should be fixed in version 11 via https://github.com/angular/angular-cli/pull/18708
