### ISSUE TITLE
Inline SourceMap Option

### ISSUE THREAD

**Issue by infacto** [angular/angular-cli#18975]
# 🚀 Feature request

Related issue: https://github.com/angular/angular-cli/issues/13543

### Command 

- [X] build
- [X] serve

### Description

Please consider a inline source map option again. It's just one more option. It's easy to implement in the Angular webpack config. It's just one attribute. See [docs](https://angular.io/cli/build).

### Describe the solution you'd like

 I suggest option `sourceMapType` or a new value.
Why not? Just add `devtool: 'inline-source-map'` to the `webpack.config.js` if this option is set.

### Describe alternatives you've considered

I don't want additional dependencies, plugins or hacks. Just an official option in the build CLI. Please 🙏 
Btw. `ngx-build-plus` does not work. I don't want to rely on these 3rd party libs. Another risky build breaker.
It's really just a minor change in Angular CLI, or not?

**Comment by alan-agius4** [comment]
Hi @infacto, what is the use-case that requires to use inline sourcemaps?.

**Comment by infacto** [comment]
In my case, I use Cordova and inspect with Chrome. The DevTools failed to load source maps.

```text
DevTools failed to load SourceMap: Could not load content for http://localhost/runtime-es2015.js.map: Connection error: net::ERR_CONNECTION_REFUSED
```

But I think regardless of the use case, it's not the worst idea to have this option. It's just a tiny addition to the Webpack config. 

```js
module.exports = {
  /* ... */
  mode: 'production',
  // mode: 'development',
  // devtool: 'inline-source-map',
  /* ... */
  /* Can be in ternary or if-condition to extend the object. */
};
```

It's much more effort for the Angular app developer to achieve this. And not really nice and dependent on a non-official build tool, which can be a pain.

**Comment by alan-agius4** [comment]
Hi @infacto, 

We have discussed this briefly and we still stand by the decision not to add another option to inline sourcemaps. Adding another option is not as trivial as it may look as this option to interacts with a bunch of others as well.

For a better Cordova DX, Ionic extension of the CLI should be better fit as it's more geared towards building an application which is wrapped using Cordova. See:  https://github.com/ionic-team/angular-toolkit/blob/master/builders/cordova-build

**Comment by alan-agius4** [comment]
Hi @infacto, 

We have discussed this briefly and we still stand by the decision not to add another option to inline sourcemaps. Adding another option is not as trivial as it may look as this option to interacts with a bunch of others as well.

For a better Cordova DX, Ionic extension of the CLI should be better fit as it's more geared towards building an application which is wrapped using Cordova. See:  https://github.com/ionic-team/angular-toolkit/blob/master/builders/cordova-build
