### ISSUE TITLE
Angular cli doc does not mention how budget is calculated.

### ISSUE THREAD

**Issue by akashsolanki** [angular/angular-cli#18989]
I recently came across a [Stackoverflow question](https://stackoverflow.com/q/59246888/3503019) about `Angular budgets throw error but files do not reach size`. After some research I found that `angular cli` uses chunks size, not assets size to issue budget error or warnings. Look at [this](https://stackoverflow.com/a/64188214/3503019) answer in the same question. If that's true, the angular cli document should make it clear -

**Update [this doc](https://angular.io/guide/build#configuring-size-budgets) with below details** -

1. How angular cli calculates bundle size? Is it before the optimization is done?
2. If yes, why it does not consider final assets that get generated in `dist` folder?

**Comment by alan-agius4** [comment]
Hi @akashsolanki,

This was a bug in older versions of the CLI. See issue #15792 which was fixed by #16268.

The bundle sizes are calculated post optimization given optimization is enabled.
