### ISSUE TITLE
Unmet Peer Dependencies with Bootstrap/ zone.js and typescript 2 with latest web pack

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#1899]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 (anniversary)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

npm install bootstrap

results in
+-- bootstrap@3.3.7
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11
`-- UNMET PEER DEPENDENCY typescript@2.0.0

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

bootstrap is not installed.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We've eliminated most of these peerdeps warnings, but still consider them to be warnings and not errors. When stuff is out of beta they should go away.
