### ISSUE TITLE
Error when trying to "ng serve"

### ISSUE THREAD

**Issue by shairez** [angular/angular-cli#190]
Happened on - 
Windows 7
node 0.12.7
npm 2.11.3

Steps to reproduce: 

1. `npm install -g angular-cli`
2. `ng new myproject`
3. `ng serve`

This is the error I'm getting - 

```{r, engine='bash', count_lines}
D:\myproject\node_modules\angular-cli-github-pages\lib\commands\deploy.js:50
     return runCommand('git status --porcelain', execOptions).then(stdout => {
                                                                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Class.module.exports.includedCommands (D:\myproject\node_modules\angular-cli-github-pages\index.js:9:30)
    at D:\myproject\node_modules\angular-cli\node_modules\ember-cli\lib\models\project.js:393:61
    at Array.forEach (native)

```

**Comment by Brocco** [comment]
The build currently out on npm is old and there are some issues.

Can you try running by cloning the latest master branch?

**Comment by shairez** [comment]
Tested it with the repo clone

same error

**Comment by tapas4java** [comment]
Please update your node to 4+....it doesn't understand arrow function on
your current setup.

**Comment by shairez** [comment]
right, missed it in the prerequisites

maybe a good place to put this warning is right before the `npm install -g angular-cli` line.

That's where usually developers scan to see what their first step should be

Should I submit a PR for this improvement? or do you disagree?

**Comment by Brocco** [comment]
I don't think it makes sense to move the prerequisites. If they were moved right above the installation section then they're below the table of contents and someone could just totally miss them.

I nice alternative could be to put a link to the prerequisites in the installation section referring to the prerequisites to be more explicit?

Closing this issue as you've solved your problem. A PR or another issue to update the README is fine
