### ISSUE TITLE
Referencing 'assets' folder images in published web app

### ISSUE THREAD

**Issue by alexandis** [angular/angular-cli#19000]
Hi,

i've read a lot of reported issues regarding '**assets**' folder, but still can't figure out, how to make it work in my simple case.

So, I publish _Angular 10_ app using the following command:
**ng build --configuration azuredev --base-href /CentralTools/ --deploy-url /CentralTools/**
onto _IIS_ into '**CentralTools**' folder accessible as corresponding _web application_.

And my logo, that is referenced by 3rd party CSS as follows:
**:root{--logo:url(/assets/images/logo/logo-light.png)**

is of course not found, because '**CentralTools**' is ignored - it looks for the image in root folder of _IIS_ server:
**.....azure.com/assets/images/logo/logo-light.png 404**

**Comment by alan-agius4** [comment]
Hi @alexandis,

See https://github.com/angular/angular-cli/issues/14587#issuecomment-497368020 for more context.

Closing as this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
