### ISSUE TITLE
ERROR in [default] \node_modules\rxjs\Observable.d.ts:10:65 Cannot find name 'Promise'

### ISSUE THREAD

**Issue by rakibler** [angular/angular-cli#1901]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
1.0.0-beta.11-webpack.8

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Create a brand new app using the CLI, run ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\dom\events\hammer_gestures.d.ts:35:71
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\dom\events\hammer_gestures.d.ts:35:82
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:1:24
Cannot find name 'MapConstructor'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:2:24
Cannot find name 'SetConstructor'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:4:26
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:4:38
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:7:8
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:8:29
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:11:42
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:12:26
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:14:22
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:15:24
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:93:28
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:94:27
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:94:45
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:97:70
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:98:54
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:100:40
Cannot find name 'Set'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:101:21
Cannot find name 'Set'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\collection.d.ts:102:24
Cannot find name 'Set'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:9:19
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:10:18
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:11:16
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:12:16
Cannot find name 'Set'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:13:10
Cannot find name 'DateConstructor'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:14:12
Cannot find name 'RegExpConstructor'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:15:17
Cannot find name 'JSON'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:19:27
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:20:32
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:21:31
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:22:26
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:23:16
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:24:18
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:25:17
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:26:19
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:27:15
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:29:46
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:40:25
Cannot find name 'FunctionConstructor'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:41:30
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:47:9
A rest parameter must be of an array type.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:51:25
Cannot find name 'DateConstructor'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:56:51
Cannot find name 'String'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:59:54
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:63:49
Cannot find name 'Date'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:67:58
Cannot find name 'Map'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:72:36
Cannot find name 'RegExp'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:77:39
Cannot find name 'RegExp'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:79:45
Cannot find name 'RegExp'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:89:46
Cannot find name 'Error'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:106:27
Cannot find name 'RegExpConstructor'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:108:21
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:109:20
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:109:43
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:113:44
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:116:35
Cannot find name 'Error'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:116:43
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:117:34
Cannot find name 'Error'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:117:42
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:119:29
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:120:27
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:123:137
Cannot find name 'Date'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:124:39
Cannot find name 'Date'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:125:35
Cannot find name 'Date'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:126:26
Cannot find name 'Date'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:127:18
Cannot find name 'Date'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:128:24
Cannot find name 'Date'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\facade\lang.d.ts:136:46
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\web_workers\shared\client_message_broker.d.ts:32:64
Cannot find name 'Promise'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\web_workers\shared\client_message_broker.d.ts:40:55
Cannot find name 'Promise'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\web_workers\shared\serializer.d.ts:10:36
Cannot find name 'Object'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\web_workers\shared\service_message_broker.d.ts:27:75
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\web_workers\shared\service_message_broker.d.ts:35:67
A rest parameter must be of an array type.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\web_workers\shared\service_message_broker.d.ts:35:83
Cannot find name 'Promise'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\web_workers\worker\location_providers.d.ts:21:85
Cannot find name 'Promise'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\worker_app.d.ts:6:52
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\worker_app.d.ts:13:55
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\worker_render.d.ts:35:52
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\worker_render.d.ts:40:51
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\@angular\platform-browser\src\worker_render.d.ts:44:54
Cannot find name 'Array'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\rxjs\Observable.d.ts:10:65
Cannot find name 'Promise'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\rxjs\Observable.d.ts:11:68
Cannot find name 'ArrayLike'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\rxjs\Observable.d.ts:38:19
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\rxjs\Observable.d.ts:66:59
Cannot find name 'Promise'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\rxjs\Observable.d.ts:66:69
Cannot find name 'Promise'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\rxjs\Subject.d.ts:23:19
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\rxjs\Subscription.d.ts:4:60
Cannot find name 'Function'.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:17:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.core.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:18:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.collection.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:19:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.generator.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:20:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.iterable.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:21:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.promise.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:22:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.proxy.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:23:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.reflect.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:24:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.symbol.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:25:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts' not found.

ERROR in [default] C:\Users\rakibler\Projects\efile\node_modules\typescript\lib\lib.es2015.d.ts:26:0
File 'C:/Users/rakibler/Projects/efile/node_modules/typescript/lib/lib.es5.d.ts' not found.

5. Mention any other details that might be useful.
It might be important to note that I don't have admin access, plus we have a decrypting firewall which has caused issues before.  I dunno if this is related though. 
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by drejohnson** [comment]
Same here

**Comment by jianliao** [comment]
typescript upgraded to 2.0.2. lock the version to 2.0.0 should fix the problem.

**Comment by TopDuke** [comment]
tsc -v
version 2.0.2
Same here

**Comment by traneHead** [comment]
Same errors with typescript version 1.8.10 (OSX El Capitan), node version 6.3.1 (via brew).
Upgraded to node 6.5.0, same thing.
Upgraded typescript to 2.0.0. Errors gone.
Upgraded typescript to 2.0.2. Errors back.

**Comment by matpulis** [comment]
Have same issue did anyone manage to find a fix ?

**Comment by borysn** [comment]
@matpulis typings are being phased out in favor of the new `@types`, you can see an example here for adding new types

[tsconfig.json](https://github.com/borysn/spring-boot-angular2/blob/master/frontend/tsconfig.json)
[package.json](https://github.com/borysn/spring-boot-angular2/blob/master/frontend/package.json)

**Comment by borysn** [comment]
@traneHead can confirm, for both node 6.5 and 6.1

**Comment by aszechlicki** [comment]
@traneHead in my case errors were gone after reverting typescript to 2.0.0 (i mean both global and local package) and upgrading node to 6.5.0 and npm to 3.10.6

**Comment by JohannesHoppe** [comment]
Bug confirmed on a fresh system with latest node.js and
```
npm i -g typescript angular-cli@webpack
ng new
```

**Comment by SeekingMonkey** [comment]
Sorry if this sounds dense, I upgraded typescript to latest (npm install -g typescript@next), but i am having trouble rolling back to 2.0.0. Are you using npm shrinkwrap?

**Comment by aszechlicki** [comment]
@SeekingMonkey 
`npm uninstall typescript -g
npm cache clean
npm install typescript@2.0.0 -g`
should do the trick

**Comment by vapits** [comment]
Same issues in new projects here.

**Comment by tobang** [comment]
Experiencing the same problem. 
Win 7
Node 6.5.0
Npm 3.10.6
Typescript 2.0.0

**Comment by gpcrawford** [comment]
Experiencing same problem. 

node 6.2.2
npm 3.10.6

Rollback to typescript 2.0.0 provides a temporary fix.

**Comment by JiriBalcar** [comment]
I am experiencing the same problem while installing angular-cli@webpack globaly.
Unfortunately rollbacking to Typescript 2.0.0 didn't fix the problem form me.

**Comment by kylecordes** [comment]
CLI team: a couple of days ago we got a .3, .4, .5., .6, .7., .8 to quickly work through an irritating dependency problem. Now we have another one, this time with Typescript. How about shipping .9 today with an updated TS dependency? Otherwise I expect a few dups each day of this issue, and needlessly irritated users, in the meantime.

**Comment by kylecordes** [comment]
Also, regarding a comment earlier, I have experimentally confirmed that there is **no need at all** to discard your NPM cache ("npm cache clean") to work around this. NPM is highly capable of understanding two different versions of a package in its cache, in a sense that is its main purpose in existence.

**Comment by linus1412** [comment]
I'm one of those users ;(

**Comment by jasonswett** [comment]
I was able to get it working but only after much fiddling. I'm using Node 6.5.0, npm 3.10.6 and TypeScript 2.0.0 (local, not global). It also seemed not to work for me until I blew away my project directory and ran `ng new` again. So I can confirm that configuring your libraries to those versions _can_ work. If it doesn't work for you, maybe try creating a fresh new project to see if you can do an error-free `ng build` there.

**Comment by BernhardRode** [comment]
I can confirm 
changing
"typescript": "^2.0.0"
to
"typescript": "2.0.0"

is a valid workaround for the issue.

So is it a typescript thing or angular-cli ;)

**Comment by dematic-rodrigo-silveira** [comment]
This did not work for me. See [issue 1887](https://github.com/angular/angular-cli/issues/1887) for more details.

**Comment by dematic-rodrigo-silveira** [comment]
Having similar problem. See [issue 1887](https://github.com/angular/angular-cli/issues/1887) for more details.

**Comment by LeonardoChavesCavalcante** [comment]
I have the same problem with  angular-cli@webpack , 
I tried with typescript 1.8.0, 2.0.0, windows 7, windows 8, node 5.8, 6.5. nothing work

**Comment by dematic-rodrigo-silveira** [comment]
I was able to solve this problem with the following configuration:

### Upgrade imy tools
````bash
 node --version
v6.5.0
$ npm --version
3.10.3
$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64

$ npm list -g
/usr/local/lib
├─┬ angular-cli@1.0.0-beta.11-webpack.8
│ ├── @angular-cli/ast-tools@1.0.0

...

├── typescript@2.0.0

....
````

### Changed "typescript": "^2.0.0"` to ` "typescript": "2.0.0"` in my `packages.json`

### Executed the folling commands on my project root
````bash
$ rm -rf node_modules dist tmp typings
$ npm install --save-dev angular-cli@webpack
````

**Comment by rakibler** [comment]
RC6 came out and has a dependency on TS 2.0.2.  Can't upgrade until the CLI supports it :(

**Comment by billdwhite** [comment]
Yep, blocked until CLI has 2.0.2 support

**Comment by ghsyeung** [comment]
Seems to be an issue in awesome-typescript-loader, see https://github.com/Microsoft/TypeScript/issues/10633

**Comment by HamidHabib** [comment]
I guess I found the solution, i tried it in two different machines and it worked:
Downgrade globally to Typescript 2.0.0   &   change
` "typescript": "^2.0.0"to "typescript": "2.0.0"in mypackages.json`

**Comment by aderbas** [comment]
I'm a little disappointed with the CLI. I spent the day trying to solve packages incompatibility.  I managed to install everything and now this failure. The worst that there are many people with the same problem and no solution.

`$ ng --version`
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: linux x64

**Comment by ShadowManu** [comment]
Just to guide a little on a real fix. Aggresively adding libs to the `tsconfig` removed the errors. Mine actually looks like this:

```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es5",
      "es6",
      "dom",
      "es2015.core",
      "es2015.collection",
      "es2015.generator",
      "es2015.iterable",
      "es2015.promise",
      "es2015.proxy",
      "es2015.reflect",
      "es2015.symbol",
      "es2015.symbol.wellknown"
    ],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}
```

**Comment by bdinsmor** [comment]
I realize there are a lot of moving parts, but has there ever been a thought to hold back releases of individual parts until they can release an entire ecosystem update?  In the grand scheme of things a stagger of a few days or weeks doesn't matter, but wow is it frustrating...
Just a thought - other companies (Elastic is great at this IMHO), wait to release Elasticsearch or Kibana until they are all compatible with one another.  It would be nice to see a release package that would include:
angular-cli
angular2
angular2-material

I wouldn't mind waiting another week to get RC6 or RC7 if it meant that everything just worked.

**Comment by aszechlicki** [comment]
@bdinsmor but there are many people using angular2 without angular-cli, and even more using it without angular2-material
that would mean making all those people wait for something they don't care about

**Comment by bdinsmor** [comment]
I understand what you are saying but if we are talking about waiting a week
to avoid 1000 GitHub issues, I would think it would be worth the wait and
forced coordination between Google teams.

**Comment by dematic-rodrigo-silveira** [comment]
Hello - My understanding of a version appended with Beta it that is has been made available to the user community for usability validation and, unless something goes radically wrong - like an explosion on the test platform like SPACE-X this part week, a few usability issues might be addressed before the the final version is released, and that the final version will be 100% compatible with the Beta versions. My understanding of a version appended with RC means that it is ready for market, that the final version is around the corner, and it will be 100% with the RC versions.

The recent series of releases by Google and angular-cli suggest that we all are operating from a different perception of the meaning of these terms.

The lessons learned suggest that our friends at Google and angular-cli owe their user community a good discussion for us to develop a common understanding of the meaning of these terms, particularly in terms of their responsibilities in appending them to their releases and then, once this is in place, do a better job sticking to what has been agreed.

**Comment by shairez** [comment]
Upgrading to the latest CLI version should solve this issue

**Comment by prajapati-parth** [comment]
I don't understand whether using "^" or "~" or locking to specific version in package.json is the best practice. Spent 3 hours trying to solve the same issue today, before I found this thread.

**Comment by JohannesHoppe** [comment]
This issue is not any longer active. Generally deps are pretty stable now. The CLI supports YARN, too!

**Comment by wavemeetu** [comment]
delete "node_modules" and reinstall using 
`$ npm install `
