### ISSUE TITLE
Rules for AsyncFileOperator

### ISSUE THREAD

**Issue by samuelfernandez** [angular/angular-cli#19012]
# 🚀 Feature request

### Command (mark with an `x`)

API of  `@angular-devkit/schematics`

### Description

In the public API there is an interface `AsyncFileOperator` which is not currently being implemented by any rule in a similar way as there are for `FileOperator`. 

### Describe the solution you'd like
It'd be wonderful that `forEach` and `when` rules could handle that.

### Describe alternatives you've considered

I've came up with this code that implements the requested feature, could be brought into the library as is or merged with current methods:

```ts
interface FileVisit {
  path: Path;
  entry?: Readonly<FileEntry> | null;
}

export function forEachAsync(operator: AsyncFileOperator): Rule {
  return (tree: Tree, _context: SchematicContext): Observable<Tree> => {
    const paths: FileVisit[] = [];
    tree.visit((path, entry) => {
      paths.push({ path, entry });
    });

    return from(paths).pipe(
      concatMap(({ entry, path }) =>
        entry == null
          ? of(tree)
          : operator(entry).pipe(
              tap((newEntry) => {
                if (newEntry === entry) {
                  return;
                }
                if (newEntry === null) {
                  tree.delete(path);
                  return;
                }
                if (newEntry.path !== path) {
                  tree.rename(path, newEntry.path);
                }
                if (!newEntry.content.equals(entry.content)) {
                  tree.overwrite(newEntry.path, newEntry.content);
                }
              }),
              map(() => tree),
              first()
            )
      ),
      last()
    );
  };
}
```

```ts
export function whenAsync(predicate: FilePredicate<boolean>, operator: AsyncFileOperator): AsyncFileOperator {
  return (entry: FileEntry): Observable<FileEntry | null> => {
    if (predicate(entry.path, entry)) {
      return operator(entry);
    } else {
      return of(entry);
    }
  };
```

**Comment by alan-agius4** [comment]
Hi @samuelfernandez,

Thanks for the feature request. At this point in time, we don't want to add addition items to be Schematics API unless they are absolutely necessary. The reason being is that we'd like to review and evaluate the entire public API, which potentially would also impact the `AsyncFileOperator` and `FileOperator` types.

Related to: https://github.com/angular/angular-cli/issues/15335

Thanks again.
