### ISSUE TITLE
ng generate guard prompts twice

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#19027]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

### Description
Using angular CLI to generate a guard prompts twice for 
`? Which interfaces would you like to implement? CanActivate`
`? Which interfaces would you like to implement? CanActivate`

## 🔬 Minimal Reproduction
- `> npx @angular/cli@11.0.0-next.6 new admin-console --strict true --routing true --style css`
- `> cd admin-console`
- `> yarn ng generate guard guards/oauth/auth-oauth`
![guard_twcie](https://user-images.githubusercontent.com/13006107/95595557-48b23c80-0a1a-11eb-8b2a-90445fc645da.gif)

## 🔥 Exception or Error
No exception

## 🌍 Your Environment
<pre><code>
$ ng version
Angular CLI: 11.0.0-next.6
Node: 14.13.1
OS: darwin x64

Angular: 11.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.6
@angular-devkit/build-angular   0.1100.0-next.6
@angular-devkit/core            11.0.0-next.6
@angular-devkit/schematics      11.0.0-next.6
@angular/cli                    11.0.0-next.6
@schematics/angular             11.0.0-next.6
@schematics/update              0.1100.0-next.6
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

**Comment by prabh-62** [comment]
Interesting that uppercase `CanLoad` works
`> yarn ng generate guard guards/oauth/auth-saml --implements CanLoad`

but lowercase `canLoad` errors out
`> yarn ng generate guard guards/oauth/auth-saml --implements canLoad`

<img width="1339" alt="canLoad_error" src="https://user-images.githubusercontent.com/13006107/95596091-f58cb980-0a1a-11eb-9abc-00eb809de202.png">

**Comment by prabh-62** [comment]
Not sure, how to pass multiples here
`> yarn ng generate guard guards/oauth/auth-saml --implements CanActivate,CanLoad`

<img width="1342" alt="canLoad_multiple" src="https://user-images.githubusercontent.com/13006107/95596412-5a481400-0a1b-11eb-8a28-6d846dee227e.png">

**Comment by alan-agius4** [comment]
@prabh-62  try `yarn ng generate guard guards/oauth/auth-saml --implements CanActivate --implements CanLoad`
