### ISSUE TITLE
ng error: Unknown error: SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by dumitru-h** [angular/angular-cli#19022]
Hello,
I installed cli with command:
`sudo npm install -g @angular/cli@10.1.6`
which is the last release at this moment.

I tried **ng new angularclient**

and I had this error: 
> Unknown error: SyntaxError: Unexpected token 'export'

I tried just **ng** and had the same error.

I try to discover Angular so this is a big stop for me in discovering Angular ;)

Here is the package info:
> `>` sudo npm info @angular/cli dist-tags
>{
>  latest: '10.1.6',
>  next: '11.0.0-next.6',
>  'v6-lts': '6.2.9',
>  'v8-lts': '8.3.29',
>  'v7-lts': '7.3.10',
>  'v9-lts': '9.1.12'

> `>` node -v
v12.19.0

**Comment by alan-agius4** [comment]
Hi @dumitru-h, 

I cannot replicate the error with the steps provided.

**Comment by dumitru-h** [comment]
Here is my OS info maybe this can help:
I am on Xubuntu:
> `>` lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

> `>` uname -a 
Linux my_host 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I uninstalled, re-installed. Nothing helps.

**Comment by alan-agius4** [comment]
So just to get this right, when executing the `ng new angularclient` command you are getting `Unknown error: SyntaxError: Unexpected token 'export'` error?

**Comment by dumitru-h** [comment]
> So just to get this right, when executing the `ng new angularclient` command you are getting `Unknown error: SyntaxError: Unexpected token 'export'` error?

Even without arguments the error is the same.

**Comment by alan-agius4** [comment]
Seems like there is this SO issue 
https://stackoverflow.com/questions/64051509/unknown-error-syntaxerror-unexpected-token-export-on-ng-command

Which indicates that this is not an Angular CLI issue, therefore closing this as it's unactionable from our end.

**Comment by dumitru-h** [comment]
The stackoverflow proposed solution worked for me.
