### ISSUE TITLE
ng lint failure in projects created by cli

### ISSUE THREAD

**Issue by ramsrib** [angular/angular-cli#1903]
> Issue details:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
All OS

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
```
$ ng new ng-test
$ cd ng-test
$ ng lint
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
$ ng lint
> ng-test1@0.0.0 lint /private/tmp/ng-test1/ng-test1
> tslint "src/**/*.ts"

src/main.ts[1, 8]: " should be '

```
Lint errors found in the listed files.

5. Mention any other details that might be useful.

> main.ts in the ng blueprint is having the issue.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/1904
