### ISSUE TITLE
Export build-schema script in @angular-devkit/schematics

### ISSUE THREAD

**Issue by biolauri** [angular/angular-cli#19046]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The script `build-schema.ts` in _scripts/_ is very handy for generating the necessary TypeScript interfaces for the schematic function from the corresponding `schema.json`. Currently, it's not exported, so for own/custom schematics, one has to write the type theirself and keep it in sync with the schema.

### Describe the solution you'd like

I'd like request to provide the `build-schema.ts` file/default exported function as a public API in `@angular-devkit/schematics` to be able to use it in custom written schematics.

### Describe alternatives you've considered

Currently, we've got only these two solutions:
* Re-write the logic of `build-schema.ts` ourselves
* Manually write the type/interface ourselves and add some checkers to guarantee it's in sync with the corresponding schema

**Comment by clydin** [comment]
The `build-schema.ts` file is a repository infrastructure script that is specific to the structure of the Angular CLI repository.
However, it uses [quicktype](https://quicktype.io) to generate the TypeScript files from the JSON schemas.  quicktype has a standalone CLI which can be used directly.  In addition it has an API if more complex transformations or workflows are needed.

**Comment by biolauri** [comment]
Oh, sorry for the confusion. I didn't mean to just add a simple export to the script itself. I thought more of moving the core functionality (using quicktype with some good defaults and wrapping the file creation) into some place where it can be re-used (by your `build-schema` script as well as by others).

While it's possible to use quicktype via CLI (or `quicktype-core` via node), the possibility to compile all JSON files with a `$schema` to corresponding files within the same directory isn't shipped by quicktype. The CLI does concatenate the generated output into one file within the current working directory and for node, we have to write the loop, checks and file handling ourselves. It's the same for `appendDeprecatedDescription` which is very helpful. So the request is more like a request to export these few bits of functionality around quicktype.
