### ISSUE TITLE
Breakpoints do not work with Multi-Project Workspace

### ISSUE THREAD

**Issue by grant77** [angular/angular-cli#19043]
# 🐞 Bug report

### Description

Breakpoints do not work when using the "Multi-Project Workspace" setup.  I am familiar with the "sourceMapPathOverrides" that I discovered from https://github.com/angular/angular-cli/issues/2453.  Unfortunately, this hack can only be used with "VSCode + Chrome + msjsdiag.debugger-for-chrome extension".  

If you are not using this environment, you are screwed.  Even if you are using that environment, you should not have to do this. 
 The paths should be correct to begin with.  I came up with a custom workaround, but I would rather not have to mess with webpack via @angular-builders/custom-webpack.  My workaround is at bottom of this report (scroll down a little).

## 🔬 Minimal Reproduction

1. ng new my-workspace --createApplication=false
2. cd my-workspace
3. ng g application my-app --routing=false --style=scss
4. ng serve
5. Open my-workspace folder with VSCode (or anything else).
6. Set breakpoint anywhere. 
7. Run
8. Breakpoint does not get hit 😡 

## 🌍 Your Environment
<pre><code>Angular CLI: 10.1.6
Node: 13.10.1
OS: win32 x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.0.3</code></pre>

## 🤘  Workaround

1. npm i @angular-builders/custom-webpack --save-dev
2. Add a webpack.config.js file in the root of workspace that looks like this:
```
module.exports = {
    context: __dirname
}
```
3. Open angular.json
4. Find "projects/my-app/architect/build" and replace the builder with "@angular-builders/custom-webpack:browser" and add a "customWebpackConfig" option that looks like this:
```
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./webpack.config.js"
            },
            ...
```
5. Replace value of "projects/my-app/architect/serve/builder" from "@angular-devkit/build-angular:dev-server" to "@angular-builders/custom-webpack:dev-server".
6. ng serve
7. Now breakpoints work!!  😄

**Comment by clydin** [comment]
The upcoming version 11 provides several improvements to source maps and the debugging experience (including the above change to the Webpack context to be the workspace root).  For more information, please see: https://github.com/angular/angular-cli/pull/18377

You can try the version 11 prerelease by using `ng update @angular/cli @angular/core --next`.
