### ISSUE TITLE
Change URL to access main.ts, polyfill.ts, and other JS files to pass ELB Filter

### ISSUE THREAD

**Issue by Abhishek150995** [angular/angular-cli#19059]
When I run my Angular Application all the JS Files are loaded using URL

main.ts ->http://localhost:49488/main.js
polyfill.ts ->http://localhost:49488/polyfills.js

But I want to change the accessing the URLs as

main.ts ->http://localhost:49488**/Dash/**main.js
polyfill.ts ->http://localhost:49488**/Dash/**polyfills.js

Please suggest a way for the same.

Thanks in advance

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Abhishek150995** [comment]
https://stackoverflow.com/questions/64335112/change-url-to-access-main-ts-polyfill-ts-and-other-js-files-to-pass-elb-filter

Please suggest a way for the below issue
