### ISSUE TITLE
Differential Loading generating ES5 bundles instead of correct browserlist settings

### ISSUE THREAD

**Issue by Adam-Michalski** [angular/angular-cli#19060]
Recently we have migrated from Angular 7 to 8 and from the begining we are experiencing issues with our builds in cause of redundant build for es5 which is created against browserlist setting to last two wersions.

As described in https://caniuse.com/es6-module last 2 versions supports it

and our configuration includes changes like

tsconfig.json
```
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es2015",
```

package.json
```
  "browserslist": [
    "last 2 Chrome versions",
    "last 2 Firefox versions"
  ]
```

So my question is why we are experiencing this issue, or in other words, why does cli ignore our browserlist settings?

Also it would be nice to have information why this build for es5 is running when it clearly should not run.
Info like 
`Generating ES5 bundles for not suported versions Chrome 80, Firefox 80,  etc`

**Comment by clydin** [comment]
In addition, some potential areas to investigate are the presence of any browserslist files (`.browserslistrc`/`browserslist`) and if there is a `target` option in the application's TypeScript configuration (default is `tsconfig.app.json`).

**Comment by Adam-Michalski** [comment]
`angular.json` `root` and `sourceRoot` for every application is set to 
```
  "projects": {
    "app": {
      "root": "projects/app/",
      "sourceRoot": "projects/app/src",
      ...
```
`tsconfig.json`
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "module": "esnext",
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "types": ["node", "jasmine"],
    "baseUrl": "./",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "esnext", "dom"]
  },
  "exclude": ["sc", "e2e", "test.ts", "**/*.spec.ts", "**/*.po.ts", "node_modules"]
}
```
all apps extend `tsconfig.json` in `tsconfig.app.json`
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/app",
    "types": []
  },
  "exclude": ["test.ts", "**/*.spec.ts"],
  "include": ["../../config.d.ts", "./src/main.ts", "./src/polyfills.ts"]
}
```

Within migration all `browserlist` files were removed and this setting was added to package.json

Our structure looks a little bit different but builds, paths and everything else works fine for every app after restructurization

![image](https://user-images.githubusercontent.com/5684123/95960899-a244ad80-0e04-11eb-9b0a-a486ed0458fa.png)

**Comment by alan-agius4** [comment]
Hi @Adam-Michalski,

A migration in version 10 indeed removed the `browserslist` file, but it was just renamed to `.browserslistrc`. 

Looking at your structure the problem is that the `browserslist` setting is defined in the `package.json` which is outside of the project root `projects/app/`.

To fix create a `.browserslistrc` under `projects/app/` containing:
```
last 2 Chrome versions
last 2 Firefox versions
```

**Comment by Adam-Michalski** [comment]
It does not work for Us.

Is there a possibility that one of the libraries we are using causes build to es5? We have few libs which probably should be updated.

**Comment by Adam-Michalski** [comment]
Further investigation leads me to initial project where once installed with npm and configured towards 2 last versions of Chrome and FireFox it works and another time installed with yarn does not.

We use yarn and it was problematic to check but if you generate new project for ng 8 you will spot it too.

[Prepared repo for reproduction](https://github.com/Adam-Michalski/test-es2015)

There are two scenarios

A. Build generates files only for es2015 for
   1. `npm i`
   1. `ng build administration`

B. Build generates files for es5 and es2015 for
   1. `yarn`
   1. `ng build administration`

**Comment by alan-agius4** [comment]
Hi @Adam-Michalski, 

The reproduction doesn't seem complete. I do remember a number of differential loading bugs which where solved in version 9, which where produce by different module resolutions by NPM and Yarn.

Please be aware that Angular version 8 is currently in LTS until November 28, 2020, during LTS periods only critical and security patches are done.

For more information on this, please see https://angular.io/guide/releases#support-policy-and-schedule

**Comment by Adam-Michalski** [comment]
Thx for support.

We foundout that adding to `package.json` solves problem for yarn in both starter project and our projects
```
  "resolutions": {
    "caniuse-lite": "1.0.30001148"
  },
```
I added also `^` to version but for now I do not see difference cause as docs for yarn specify we need to update this as often as we can xD
