### ISSUE TITLE
Will systemJs version be updated to rc5?

### ISSUE THREAD

**Issue by toddhickerson** [angular/angular-cli#1906]
**Is the SystemJS version (using Broccoli verses Webpack) going to be maintained going forward and get updated as angular gets updated?  Or is the Webpack version going to be the only one maintained going forward? Some of us use the Angular-CLI to integrate Polymer, which for now is best supported in Bower (not NPM i.e. Webpack).** 

It would be great to get an RC5 update to the systemJS version of the CLI.

This statement on the README.md seems to indicate there will no longer be a systemJS version: "We're updating the build system in Angular-CLI to use webpack instead of Broccoli."

Thank you.

**Comment by filipesilva** [comment]
`beta.10` was the last SystemJS based version of the CLI, we're focusing on webpack from now on.

**Comment by filipesilva** [comment]
I can't speak for the specific usecase of polymer, but perhaps https://github.com/angular/angular-cli#global-styles would help. You could even ignore the bower directory, as webpack will bundle these globals as well.
