### ISSUE TITLE
Live reloading failure after update to angular 10 and workaround

### ISSUE THREAD

**Issue by nppasousa** [angular/angular-cli#19063]
### Command (mark with an `x`)

ng serve , ng build --watch

- [ ] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

 Yes, the previous version in which this bug was not present was: 9.1

### Description
After ng update, editing a template inside a lazy loading module, creates errors in the component. If a mistake is made in a template (example: <div </div> (missing greater than sign in the tag opening).

Fixing the mistake make sthe error disapear regarding the template, but the component is still broken. 

Either stopping live reloading by Ctrl-C and running ng serve again, or editing the component provide a successful compilation. (even if you add a blank line to the component.ts)

## 🔬 Minimal Reproduction

Reproduction, https://github.com/nppasousa/testLiveReloading.git
or
ng new [with routing] [with CSS]
ng g m a --route A --module app.module
add a mistake to src/a/a.component.html [ you get compilation errors on both a.component.html and a.component.ts]
fix mistake on src/a/a.component.html [ you still get compilation errors on a.component.ts]
add blank line to src/a/a.component.html [ good compilation]

## 🔥 Exception or Error
<pre><code>

ERROR in src/app/a/a.component.html:2:4 - error NG5002: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags
    
    2 <di</div>
         ~~~~~~
    
      src/app/a/a.component.ts:6:16
        6   templateUrl: './a.component.html',
                         ~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component AComponent.
    src/app/a/a.module.ts:9:18 - error NG6001: The class 'AComponent' is listed in the declarations of the NgModule 'AModule', but is not a directive, a component, or a pipe. Either remove it from the NgModule's declarations, or add an appropriate Angular decorator.
    
    9   declarations: [AComponent],
                       ~~~~~~~~~~
    
      src/app/a/a.component.ts:9:14
        9 export class AComponent implements OnInit {
                       ~~~~~~~~~~
        'AComponent' is declared here.
    

Date: 2020-10-14T04:40:07.061Z - Hash: cbb87ac155be7c615aca
5 unchanged chunks
chunk {a-a-module} a-a-module.js, a-a-module.js.map (a-a-module) 6.21 kB  [rendered]
Time: 75ms
    
    ERROR in src/app/a/a.module.ts:9:18 - error NG6001: The class 'AComponent' is listed in the declarations of the NgModule 'AModule', but is not a directive, a component, or a pipe. Either remove it from the NgModule's declarations, or add an appropriate Angular decorator.
    
    9   declarations: [AComponent],
                       ~~~~~~~~~~
    
      src/app/a/a.component.ts:9:14
        9 export class AComponent implements OnInit {
                       ~~~~~~~~~~
        'AComponent' is declared here.

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.1.6
Node: 12.16.1
OS: linux x64

Angular: 10.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.6
@angular-devkit/build-angular   0.1001.6
@angular-devkit/core            10.1.6
@angular-devkit/schematics      10.1.6
@angular/cli                    10.1.6
@schematics/angular             10.1.6
@schematics/update              0.1001.6
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @nppasousa, this has the same root cause as https://github.com/angular/angular-cli/issues/18707
