### ISSUE TITLE
TSLint to ESlint migration tool REQUEST

### ISSUE THREAD

**Issue by LewisMorgans** [angular/angular-cli#19075]
Is Angular working on a migration tool for moving from the deprecated TSlint to ESlint?

I'm having trouble with ES not checking angular related components such as the template files and modules.

Thanks.

**Comment by mgechev** [comment]
Hey @LewisMorgans, the Angular and angular-eslint teams would be working together to ensure a smooth integration with the CLI.

There's a migration path from the authors of [angular-eslint](https://github.com/angular-eslint) and  [tslint-to-eslint-config](https://github.com/typescript-eslint/tslint-to-eslint-config).

@JamesHenry implemented support for parsing of Angular templates in angular-eslint, so linting templates should be available. There's still [some work](https://github.com/angular-eslint/angular-eslint/issues/86) until 1.0, but you should be ready to try everything out today.
