### ISSUE TITLE
Warning of unused files during ng build. Even with the proposed configuration. Which also deactivates autocompletion.

### ISSUE THREAD

**Issue by infacto** [angular/angular-cli#19082]
# 🐞 Bug report

I know there are some similar issues. I searched this repo and the web. And nothing helped. I think it's not a duplicate. Because in short: I followed the recommended config (no ts-files in "include", entry "files" only). But this does not fully work and also disables intellisense. ...

### Command

- [x] build
- [x] serve

### Is this a regression?

I think this is since Angular 9, 10, 11.

### Description

I get some warnings about unused ts-files. Even if I remove all "included" of ts-files and only use entry "files".
And over this, I need the includes for the autocompletion / auto-import suggestion / IntelliSense.

Without `**/*.ts` in `include` of `ts.config`, there are less warnings. But for some files like the prod.ts the problem persists.
And without this include, I have no autocomplete anymore. This is no solution for me.

What is this warning? What's the problem to have this "unused" files. Those files are included in the build?
Anyway, I cannot remove all warnings about it and cannot use autocomplete if includes are not set. ...

## 🔬 Minimal Reproduction

1. Build a monorepo (in my case).
2. Call `ng build`.
3. Get the warning/s about unused ts-files.
4. Checkout the `tsconfig` files. Ensure the there is no `**/*.ts` as suggested. Use entry `files` only.
5. Go to `apps\demo-app\src\app\pages\dashboard\dashboard.page.ts` and  test the autocompletion with `sayHello`.
6. Find out that the autocompletion only works when `src/**/*.ts` and `../../shared/**/*.ts` are set in `tsconfig.app.ts`.

It does not matter if the include of ts-files is correct or not:
1. You cannot remove all warnings with this suggestion config.
2. You drop the autocompletion if you follow the suggestion.

**[Download Demo-Project](https://github.com/angular/angular-cli/files/5383307/test-demo.zip)**

## 🔥 Exception or Error
<pre><code>
Warning: ...\test-demo\apps\demo-app\src\environments\environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
</code></pre>

The file `environment.prod.ts` is not the only one in the warnings, on a more complex project.

**tsconfig.json**

```json
{
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*d.ts", "../../shared/**/*d.ts"],
  "exclude": ["src/**/*.spec.ts", "../../shared/**/*.spec.ts"]
}
```
Down-side: No autocompletion. To enable it, I have to include the ts-files: 

```json
{
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*.ts", "src/**/*d.ts", "../../shared/**/*.ts", "../../shared/**/*d.ts"],
  "exclude": ["src/**/*.spec.ts", "../../shared/**/*.spec.ts"]
}
```

How to disable this warning? (If nothing helps)

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.0-next.7
Node: 10.22.0
OS: win32 x64

Angular: 11.0.0-next.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.7
@angular-devkit/build-angular   0.1100.0-next.7
@angular-devkit/core            11.0.0-next.7
@angular-devkit/schematics      11.0.0-next.7
@angular/cli                    11.0.0-next.7
@schematics/angular             11.0.0-next.7
@schematics/update              0.1100.0-next.7
rxjs                            6.6.3
typescript                      3.9.7
</code></pre>

**Comment by alan-agius4** [comment]
Hi @infacto,

The problem here looks like it is caused because you updated from 10.0.x to 11.0.0-next.x or from 10.0.x to 10.1.x without using `ng update`. This means that migrations have not been executed during the update, which leaves you in a "broken" state.

In this case you'll need to run the the migrations using the below command. 

```
ng update @angular/cli --migrate-only --from 10 --to 11
```

it also appears the the globs you added in `tsconfig.app.json` are not doing what you expect, which infant rightfully are causing the warnings mentioned above.

The below glob will not include only type definitions, but also will include any file which ends with `d.ts`, ex: `environment.prod.ts`

```js
  "include": [
    "src/**/*d.ts",
    "../../shared/**/*d.ts"
  ],
```

The above should be updated to:
```js
  "include": [
    "src/**/*.d.ts",
    "../../shared/**/*.d.ts"
  ],
```

**Comment by infacto** [comment]
@alan-agius4 Argh, I missed the dot. 🤦‍♂️ Thanks, the migration worked. Down-side now: Now you can import stuff from every app. For example, in AppA you can import a class from AppB. It's suggested in IntelliSense. This is a unwanted behavior. 
Because `tsconfig.app.json` is not uses by VS Code. Therefore is the `references` array in `tsconfig.json`. Otherwise the config inside `tsconfig.app.json` like alias `paths`, `excludes`, etc. only works for Angular, but not the IDE. But with this references-config, it's impossible to include other folders like "shared". The initial issue. A dilemma. I have no perfect solution yet. Just fyi, but I would be glad if you have a spontaneous idea.

Expected behavior:
- In "shared", you can only import stuff from "shared".
- In an app, you can only import stuff from this app and "shared".

Current behavior:
- You can import anything criss-cross.
- Settings in `tsconfig.app.ts` has no effect. Until `references` is set in `tsconfig.json`. But then you cannot include anything because the Warning in Anglular (see initial post).

**Comment by alan-agius4** [comment]
Hi @infacto, 

Unfortunately, the above is expected since in version 10.1 following a meeting with the TypeScript team we removed solutions style tsconfig from Angular projects (ie: tsconfigs with `references`) due to a number of reasons. 

More information: https://github.com/microsoft/TypeScript/issues/39632
