### ISSUE TITLE
Hot Module Replacement isn't working

### ISSUE THREAD

**Issue by Quraian** [angular/angular-cli#19099]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Serving the app with hmr enabled doesn't work

## 🔬 Minimal Reproduction
ng serve --hmr 

## 🔥 Exception or Error
<pre><code>
NOTICE: Hot Module Replacement (HMR) is enabled for the dev server.
See https://webpack.js.org/guides/hot-module-replacement for information on working with HMR for Webpack.

Initial Chunk Files       | Names                  | Size  
main.js                   | main                   | 478 kB
polyfills.js              | polyfills              | 147 kB
runtime.js                | runtime                | 36.3 kB
styles.css, styles.js     | styles                 | 309 kB
vendor.js                 | vendor                 | 4.91 MB

Lazy Chunk Files          | Names                  | Size
app-admin-admin-module.js | app-admin-admin-module | 45.9 kB
app-form-form-module.js   | app-form-form-module   | 140 kB

Build at: 2020-10-16T12:55:01.004Z - Hash: 1c3aa2da2e98e6d21f2a - Time: 15424ms

Error: ./src/main.ts
Module not found: Error: Can't resolve 'C:CodeDawryatsrcWebClientApp
ode_modules@angular-devkiuild-angularsrcwebpackpluginshmrhmr-accept.js' in 'C:\Code\Dawryat\src\Web\ClientApp\src'

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.0-next.7
Node: 14.13.1
OS: win32 x64

Angular: 11.0.0-next.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.7
@angular-devkit/build-angular   0.1100.0-next.7
@angular-devkit/core            11.0.0-next.7
@angular-devkit/schematics      11.0.0-next.7
@angular/cdk                    11.0.0-next.1
@angular/cli                    11.0.0-next.7
@schematics/angular             11.0.0-next.7
@schematics/update              0.1100.0-next.7
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**
Probably Windows related as it was pointed out by an Angular team member on Twitter.

**Comment by alan-agius4** [comment]
Hi @Quraian, thanks for opening this. I have landed a PR to address this https://github.com/angular/angular-cli/pull/19097
