### ISSUE TITLE
Arguments inconnus : use-program-dependencies, useProgramDependencies An unhandled exception occurred: NGCC failed.

### ISSUE THREAD

**Issue by frohlichcortezh** [angular/angular-cli#19100]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

ng build throws this error. But I cannot find arguments anywhere in the projet.

Please include: commands run (including args), packages added, related code changes.
```
{
  "name": "portail-web",
  "version": "4.7.1",
  "private": true,
  "license": "MIT",
  "scripts": {
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor",
    "hmr": "ng serve --host 0.0.0.0 --port 4200 --hmr",
    "lint": "tslint --force --project src/tsconfig.json src/**/*.ts -t verbose",
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --port 4200",
    "test": "ng test"
  },
  "dependencies": {
    "@angular/animations": "^9.1.4",
    "@angular/common": "^9.1.4",
    "@angular/compiler": "^9.1.4",
    "@angular/core": "^9.1.4",
    "@angular/forms": "^9.1.4",
    "@angular/platform-browser": "^9.1.4",
    "@angular/platform-browser-dynamic": "^9.1.4",
    "@angular/router": "^9.1.4",
    "@aspnet/signalr": "^1.1.4",
    "@fortawesome/fontawesome-free": "^5.13.0",
    "abp-ng2-module": "^6.2.0",
    "abp-web-resources": "^5.3.0",
    "admin-lte-css-only": "^3.0.4",
    "core-js": "^3.2.1",
    "famfamfam-flags": "^1.0.0",
    "lodash-es": "^4.17.15",
    "moment": "^2.24.0",
    "moment-timezone": "^0.5.28",
    "ng2-file-upload": "^1.4.0",
    "ngx-bootstrap": "^5.6.1",
    "ngx-pagination": "^5.0.0",
    "push.js": "1.0.12",
    "rxjs": "^6.6.3",
    "sweetalert2": "^9.10.12",
    "ts-helpers": "^1.1.2",
    "tslib": "^1.14.1",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1001.7",
    "@angular/cli": "^9.1.4",
    "@angular/compiler-cli": "^9.1.4",
    "@angularclass/hmr": "^2.1.3",
    "@types/jasmine": "^3.4.0",
    "@types/lodash-es": "^4.17.3",
    "@types/moment-timezone": "^0.5.12",
    "@types/node": "^13.13.4",
    "codelyzer": "^5.1.2",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^5.0.2",
    "karma": "^5.0.4",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^3.0.0",
    "karma-jasmine": "^3.1.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nswag": "^13.4.2",
    "protractor": "^5.4.4",
    "ts-node": "^8.10.1",
    "tslint": "^6.1.2",
    "typescript": "3.8.3",
    "webpack-bundle-analyzer": "^3.7.0"
  },
  "angular-cli": {}
}
```

## 🌍 Your Environment
Your global Angular CLI version (10.1.6) is greater than your local
version (9.1.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Angular CLI: 9.1.4
Node: 12.18.3
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.7
@angular-devkit/build-angular     0.1001.7
@angular-devkit/build-optimizer   0.1001.7
@angular-devkit/build-webpack     0.1001.7
@angular-devkit/core              10.1.7
@angular-devkit/schematics        9.1.4
@ngtools/webpack                  10.1.7
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.6.3
typescript                        3.8.3
webpack                           4.44.1

**Comment by frohlichcortezh** [comment]
[error] Error: NGCC failed.
    at NgccProcessor.process (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@ngtools\webpack\src\ngcc_processor.js:119:19)
    at C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:590:31
    at SyncHook.eval [as call] (eval at create (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\tapable\lib\Hook.js:154:20)
    at Object.webpack [as webpackFactory] (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\webpack\lib\webpack.js:55:30)
    at createWebpack (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:20:36)
    at Object.runWebpack (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@angular-devkit\build-webpack\src\webpack\index.js:34:12)
    at SwitchMapSubscriber.project (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@angular-devkit\build-angular\src\browser\index.js:142:32)
    at SwitchMapSubscriber._next (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\operators\switchMap.js:47:27)
    at SwitchMapSubscriber.Subscriber.next (C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\Subscriber.js:66:18)
    at C:\fchector\code\SAMARO\Samaro.PortailWeb\angular\node_modules\@angular-devkit\build-angular\node_modules\rxjs\internal\util\subscribeToPromise.js:7:24

**Comment by frohlichcortezh** [comment]
Manually removing the argument from "node_modules@ngtools\webpack\src\ngcc_processor.js" solved my problem. But I guess is not a solution.

Any help is appreciated.

Thank you

**Comment by alan-agius4** [comment]
Hi @frohlichcortezh, 

From your `ng version` output It looks like you are using Angular version 9 with Angular CLI version 10.1.

Both Angular CLI and Angular need to be on the same major version.
