### ISSUE TITLE
uri.match is not a function after webpack update

### ISSUE THREAD

**Issue by RicardoVaranda** [angular/angular-cli#1910]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.3.1
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Updated from beta 10 to angular-cli webpack 3
ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Browser console error:
Uncaught TypeError: uri.match is not a function

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by terencewhitenz** [comment]
I had the same issue. I'll see if I can find the original source for this and link it in, but you can edit the file `node_modules/@angular/compiler/src/metadata_resolver.js` and change the following line
```
var scheme = url_resolver_1.getUrlScheme(moduleId);
```
to
```
var scheme = url_resolver_1.getUrlScheme(moduleId.toString());
```
until the fix comes through.

**Comment by RicardoVaranda** [comment]
Fixed by removing moduleID from all components.

**Comment by terencewhitenz** [comment]
Original source https://github.com/angular/angular-cli/issues/1665#issuecomment-239478773

The problem with removing moduleID is that you can only really do it for _your_ components, not for externals, and you may have to add your own back in when the fix is through.
