### ISSUE TITLE
Application from Angular 8.2 to Angular 10 upgrade 

### ISSUE THREAD

**Issue by SrinivasKothapalli** [angular/angular-cli#19110]
**Error :** 

ng Serve

Unhandled Promise rejection: Component Component1 is not part of any NgModule or the module has not been imported into your module.
Component Component2 is not part of any NgModule or the module has not been imported into your module.

all Componenets are not getting included or identified

Inclueded all into Modules and every thing was working as expected in Angular 8,2, But once after upgrade getting above issue while loading in Browser but not on Build

Please help

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
