### ISSUE TITLE
Update README: Requires Node 6.5

### ISSUE THREAD

**Issue by SeekingMonkey** [angular/angular-cli#1912]
> Please provide us with the following information:
> ---------------------------------------------------------------
OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

`ng --version` returns an error without Node 6.5

Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

n/a

The log given by the failure. Normally this include a stack trace and some
   more information.

> "Error while running script "C:\Program Files\nodejs\node_modules\angular-cli\addon\ng2\models\config\config.ts":
> SyntaxError: Unexpected token ..."

Mention any other details that might be useful.

Issue is outlined in a few other issues.  Updating the README would save people some time.
I downloaded an MSI here: https://nodejs.org/en/download/package-manager/
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by SeekingMonkey** [comment]
There also seems to be an issue with Typescript.  You need 2.0 to make things work, but the generated package.json calls for "^2.0.0", so if you have 2.1.0 installed it throws all these crazy errors.  It's a simple fix after the fact, but altering the generated file to read "2.0.0" (without the ^) would save some headaches and confusion for people trying to adopt the new cli.  Thank you for all your work!

**Comment by mwawrusch** [comment]
Can't believe that people still think using ^ when referencing packages is a good idea...

**Comment by filipesilva** [comment]
This was fixed with the new build step.

**Comment by kylecordes** [comment]
@filipesilva Excellent, much appreciated, I run in to lots of users who need Node 4 because they work on projects that specify Node 4... this removes the need to juggle Node versions.
