### ISSUE TITLE
Build failure with Webpack 5 dependency

### ISSUE THREAD

**Issue by zygimantas** [angular/angular-cli#19124]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

### Description

My application package.json contains webpack 5.x dependency.
This line of code imports file from webpack from `node_modules`:

https://github.com/angular/angular-cli/blob/ae94245131d883b5b060e8d6b6d05628bc448ea0/packages/ngtools/webpack/src/virtual_file_system_decorator.ts#L15-L16 

Webpack from `node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/node/NodeWatchFileSystem` should be used instead, if the file exists, otherwise fallback to `node_modules/webpack/lib/node/NodeWatchFileSystem`

## 🔬 Minimal Reproduction

Run `npm install --save-dev webpack`

## 🔥 Exception or Error
<pre><code>

ERROR in Cannot read property 'tapAsync' of undefined

C:\Projects\project1\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:129
            callback(err, filesModified.map(value => reverseReplacements.get(value) || value), contextModified.map(value => reverseReplacements.get(value) || value), missingModified.map(value => reverseReplacements.get(value) || value), reverseTimestamps(fileTimestamps), reverseTimestamps(contextTimestamps));
                                        ^
TypeError: filesModified.map is not a function
    at newCallback (C:\Projects\project1\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:129:41)
    at Watchpack.<anonymous> (C:\Projects\project1\node_modules\webpack\lib\node\NodeWatchFileSystem.js:81:4)
    at Object.onceWrapper (events.js:422:26)
    at Watchpack.emit (events.js:315:20)
    at Watchpack._onTimeout (C:\Projects\project1\node_modules\webpack\node_modules\watchpack\lib\watchpack.js:371:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.1.7
Node: 14.4.0
OS: win32 x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.3
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@angular/pwa                    0.1001.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.3
webpack                         5.1.3

</code></pre>

**Anything else relevant?**

1. Installed Webpack 5 package should not be used by Angular CLI.
2. There may be more of `require('webpack/lib` in other places.

**Comment by clydin** [comment]
This is unfortunately an issue the package manager used by the project and not the Angular CLI.  The @ngtools/webpack package has a peer dependency on Webpack ^4.0.0.  The package manager should not be hoisting the package into a position that would cause it to use an incompatible version of Webpack.

To attempt to get the package manager to rearrange the packages in a more compatible structure, you could try removing both the node modules directory and any lock files and then reinstalling.

**Comment by zygimantas** [comment]
Thanks @clydin You are right, I've got a different project structure with another package manager and the error is gone.
