### ISSUE TITLE
1.0.0-beta.11-webpack.8 errors with npm install

### ISSUE THREAD

**Issue by webmobiles** [angular/angular-cli#1913]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?   El Capitan OS

2. Versions.  
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64

3. Repro steps. 

first i've create the new project with: ng new myroject
then in the folder i execute  npm install, i get t errors:

── UNMET PEER DEPENDENCY typescript@2.0.2
└── zone.js@0.6.12 

npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server@^2.0.0-rc.5 but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.

**Comment by SeekingMonkey** [comment]
Have you checked what version of typescript you are running?
tsc -v will give you your current version.  You need to be on 2.0. There are other issues that come up if you are on 2.2, so make sure you are on 2.0.

**Comment by SeekingMonkey** [comment]
Scratch my previous comment. Read the comments on https://github.com/angular/angular-cli/issues/1901#issuecomment-243670283 for a clearer explanation.

**Comment by webmobiles** [comment]
sorry I had to leave angular-cli, is not well documented and very unstable. I prefer to do things with an starter or by hand

**Comment by filipesilva** [comment]
These are not errors, but rather warnings. They are not problematic.
