### ISSUE TITLE
Vulnerability of a dependency of @angular-devkit/build-angular

### ISSUE THREAD

**Issue by rossmawd** [angular/angular-cli#19155]
Apologies if this is the wrong place to raise this. The dependency tree is:

`-- @angular-devkit/build-angular@0.1000.8
  `-- resolve-url-loader@3.1.1
    `-- adjust-sourcemap-loader@2.0.0
      `-- object-path@0.11.4

https://npmjs.com/advisories/1573

**Comment by mrsegen** [comment]
Duplicate of #19139
