### ISSUE TITLE
Sass Partials Broken

### ISSUE THREAD

**Issue by eyedol** [angular/angular-cli#1915]
> Please provide us with the following information:
> ---------------------------------------------------------------

> OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

`El Capitan`

> Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.4.0`
os: darwin x64
```
> Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

After upgrade to `1.0.0-beta.11-webpack.8` which gave me global css loading capabilities, my sass - `styles.scss` doesn't compile cleanly. I noticed scss partials - `_variables.scss` are being compiled individually instead of being imported into the common styles file -  `styles.scss` file. This is causing fonts and images referenced relatively in the partials to break. This was working perfectly with `system.js` build system. I was able to exclude partials from being compiled via a config file. Not sure how to achieve the same with the webpack based build system.

> The log given by the failure. Normally this include a stack trace and some
   more information.
snippet of the stack trace.

```javascript
ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../font/roboto/Roboto-Thin.eot' in '/webapp/src'
@ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:180229-180270 6:180293-180334
@ ./src/styles.scss
@ multi styles
```

> Mention any other details that might be useful.

Inside `src` I have

```
.
├── app
│   ├── app.component.css
│   ├── app.component.html
│   ├── app.component.scss
│   ├── app.component.spec.ts
│   ├── app.component.ts
│   ├── app.module.ts
│   ├── app.routes.ts
│   ├── index.ts
│   └── shared
│       ├── components
│       ├── directives
│       ├── index.ts
│       ├── models
│       ├── pipes
│       └── services
├── assets
│   ├── README.txt
│   ├── font
│   │   └── roboto
│   ├── img
│   │   ├── google-play-badge.png
│   │   ├── ic_launcher.svg
│   │   ├── lightbox
│   │   └── overlays
│   ├── js
│   │   └── mdb.min.js
│   └── sass
│       ├── README.txt
│       ├── mdb
│       └── mdb.scss
├── environments
│   ├── environment.dev.ts
│   ├── environment.prod.ts
│   └── environment.ts
├── favicon.ico
├── index.html
├── main.ts
├── polyfills.ts
├── styles.scss
├── test.ts
├── tsconfig.json
└── typings.d.ts
```

Snippet of content of `styles.scss`

```
/* You can add global styles to this file, and also import other style files */
@import "../node_modules/bootstrap/scss/bootstrap-flex";
@import "./assets/sass/mdb";

/* TEMPLATE STYLES */
/** Layout STYLES */
main {
  margin-top: 6rem; }

main .card {
  margin-bottom: 2rem; }

mark {
  color: white;
  padding-left: 5px;
  padding-right: 5px; }
```

In `angular-cli.json` I have `styleExt` set to `scss`

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by monojack** [comment]
define your font-face source urls like this:

`
@font-face {
    ...
    src: url('assets/fonts/Roboto.eot') format('eot');
    ...
}
`

**Comment by eyedol** [comment]
@monojack You're right. My directory wasn't well structured to resolve the fonts and images relative locations. My mistake.
