### ISSUE TITLE
--dry-run option missing from ng update

### ISSUE THREAD

**Issue by celesteking** [angular/angular-cli#19156]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] update

### Is this a regression?

YES

### Description

`--dry-run` was removed from `ng update`. How am I supposed to know which packages are outdated without doing the changes? It was working fine in v6.

```
$ ng  update  @angular/material@7.3.7 --dry-run
    Package not installed: "--dry-run". Skipping.
$ ng  update --dry-run  @angular/material@7.3.7 
    Package not installed: "--dry-run". Skipping.
^C
$ ng --dry-run  update   @angular/material@7.3.7 
    Package not installed: "--dry-run". Skipping.
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.10
Node: 10.19.0
OS: linux x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.10
@angular-devkit/build-angular     0.13.10
@angular-devkit/build-optimizer   0.13.10
@angular-devkit/build-webpack     0.13.10
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      6.4.7
@angular/cli                      7.3.10
@angular/flex-layout              6.0.0-beta.18
@angular/http                     6.1.10
@angular/material                 6.4.7
@ngtools/webpack                  7.3.10
@schematics/angular               7.3.10
@schematics/update                0.13.10
rxjs                              6.6.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

Same with v10, I guess. Should I just be using `npm outdated` or what? Is this documented on `ng update` page anywhere?

**Comment by alan-agius4** [comment]
The dryRun option was removed, because when running `ng update` with a package, the package needs to be downloaded and installs, which breaks the dry run concept.

To list of all packages that support `ng update` you can run `ng update` without any argument. For packages which don't support `ng update`, you need to use your package managers update/outdated command ex: `npm outdated`.

`ng update` options are documented in https://angular.io/cli/update

**Comment by celesteking** [comment]
Google search reveals tons of issues associated with `ng update`, you should really make it clear what is possible and what is not and it should be thoroughly documented. Either in faq, wiki, or on that `ng update`. State right on the page that you can run `ng update` without args and it will print the update path.
