### ISSUE TITLE
object-path package causing npm audit to return High severity vulnerability

### ISSUE THREAD

**Issue by lucascrandle** [angular/angular-cli#19160]
`
$ npm audit

                       === npm audit security report ===                        

                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           

	  High            Prototype Pollution                                           

	  Package         object-path                                                   

	  Patched in      >=0.11.5                                                      

	  Dependency of   @angular-devkit/build-angular [dev]                           

	  Path            @angular-devkit/build-angular > resolve-url-loader >          
					  adjust-sourcemap-loader > object-path                         

	  More info       https://npmjs.com/advisories/1573                             

	found 1 high severity vulnerability in 1648 scanned packages
	  1 vulnerability requires manual review. See the full report for details.      
`

Looks like this was reported on the 19th: https://www.npmjs.com/advisories/1573

It would be great to get an updated version of angular that uses the updated object-path package

**Comment by alan-agius4** [comment]
Duplicate of #19139
