### ISSUE TITLE
can't use `ng new` to create a different project

### ISSUE THREAD

**Issue by celesteking** [angular/angular-cli#19175]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] new

### Description
It's impossible to create a new project outside the "main project". It's impossible to create a new project inside the "main project". This practically means `ng new` is unusable in its current state. See below.

```
32ef113d4404:/home/frdev/frontend/xx$ ../node_modules/.bin/ng new shit
The new command requires to be run outside of a project, but a project definition was found at "/home/frdev/frontend/angular.json".
32ef113d4404:/home/frdev/frontend/xx$ cd ../../tmp/
32ef113d4404:/home/frdev/tmp$ ../frontend/node_modules/.bin/ng new blah
An invalid configuration file was found ['/home/frdev/frontend/angular.json']. Please delete the file before running the command.
```

It used to work just fine several releases back. Why would it care of angular.json in main project's dir? It's not of its business, it should've just created a new project dir and pulled the deps via `npm`.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.12
Node: 10.19.0
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/flex-layout              9.0.0-beta.31
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.6.3
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by alan-agius4** [comment]
This is working as intended, `ng new`, is used to initialize a workspace and optionally include an application.

To create new projects in the workspace use
`ng generate application` or `ng generate library`
