### ISSUE TITLE
Unable to hot reload angular application behind reverse proxy

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#19196]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, hot reloading ng app behind reverse proxy works in Angular CLI v10

### Description
I am able to serve angular applications behind a reverse proxy however hot reload option doesn't work after making any changes to source code. Therefore, I have to manually reload app in the browser. 

## 🔬 Minimal Reproduction
```bash
> npx @angular/cli@v11.0.0-rc.0 new web-applications --create-application=false --strict
> cd web-applications
> yarn ng generate application support-panel --routing --style css
> yarn ng generate application admin-dashboard --routing --style css
```
- Edit `angular.json` such that app `support-panel` should be ng served over `http://localhost:4201/support/` and app `admin-dashboard` over `http://localhost:4202/admin/`. These angular applications will be served behind a reverse-proxy and all traffic will be directed like this so other team members don't have to fiddle with any network ports
	- `https://localhost/support/` -> `http://localhost:4201/support/`
	- `https://localhost/admin/` -> `http://localhost:4202/admin/`
- Now, add some scripts in `package.json`
```json
"scripts": {
    "start:support": "ng serve --project support-panel --port 4201 --base-href /support/ --deploy-url /support/  --publicHost https://localhost/support/",
    "start:admin": "ng serve --project admin-dashboard --port 4202 --base-href /admin/ --deploy-url /admin/  --publicHost=https://localhost/admin/",
}
```
- Run `yarn start:support` and verify application is running on [http://localhost:4201/support/](http://localhost:4201/support/)
- Run `yarn start:admin` and verify application is running on [http://localhost:4202/admin/](http://localhost:4202/admin/)

- Create a reverse proxy and navigate to [https://localhost/support/](https://localhost/support/)
- We will notice if we make any changes to application source code, app doesn't reload. The real issue here is that the websocket connections are not on correct address
<img width="1419" alt="websocket_404" src="https://user-images.githubusercontent.com/13006107/97066775-13fbc480-1586-11eb-96c1-95633050bbb6.png">

## 🔥 Exception or Error
<pre><code>
Cannot GET /sockjs-node/info
</code></pre>

## 🌍 Your Environment
<pre><code>
$ ng version  
Angular CLI: 11.0.0-rc.0
Node: 15.0.1
OS: darwin x64

Angular: 11.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-rc.0
@angular-devkit/build-angular   0.1100.0-rc.0
@angular-devkit/core            11.0.0-rc.0
@angular-devkit/schematics      11.0.0-rc.0
@schematics/angular             11.0.0-rc.0
@schematics/update              0.1100.0-rc.0
rxjs                            6.6.3
typescript                      4.0.3
    
Done in 0.73s.

</code></pre>

**Anything else relevant?**

**Comment by prabh-62** [comment]
I created a simple repo with the instructions: https://github.com/prabh-62/angular-reverse-proxy

Downgrading to angular 10 resolves the hot reloading issue

**Comment by prabh-62** [comment]
I read the [release notes for Angular CLI v11 RC.0](https://github.com/angular/angular-cli/releases/tag/v11.0.0-rc.0) and found out that option `--publicHost` has been replaced with `--servePath`.
<img width="1029" alt="servePath_added" src="https://user-images.githubusercontent.com/13006107/97068120-b621a980-1592-11eb-87ae-292d7f264344.png">

I replaced `publicHost` with `servePath` in `yarn start:support` script, however with that, CLI even fails to serve the app correctly.
```json
"start:support": "ng serve --project support-panel --port 4201 --base-href /support/ --deploy-url /support/  --servePath https://localhost/support/"
```
<img width="1433" alt="serverPath_localhost_error" src="https://user-images.githubusercontent.com/13006107/97068143-ee28ec80-1592-11eb-9729-a941cda6f84f.png">

**Comment by alan-agius4** [comment]
The publicHost option has not been removed, it’s was removed from being considered in the sockPath. (This was a regression in a previous pre-release version) Your original setup should still continue to work without any changes.

 I haven’t look into this yet, but I suspect the problem might be the sock path contain a double leading slash which causes the sock server to be available at `http://localhost:4201//support/sockjs-node/info` instead of `http://localhost:4201/support/sockjs-node/info`. That’s my 2 cents for now, I’ll download and try the reproduction on Monday.

**Comment by alan-agius4** [comment]
Okay, I wasn't quite right in the above. 

So, it looks like the reverse proxy is not proxing `https://localhost/support/sockjs-node/info?t=1603533817197` to `http://localhost:4201/support/sockjs-node/info?t=1603533817197`. 

Taking a look at the routes defined in your .NET application, the culprit seems to be the special handling of the sockjs-node.

```c#
// Only in development
if (true)
{
    var uiLiveReloadRoutes = webApplications.Select(app => new ProxyRoute
    {
        RouteId = $"{app.Name}LiveReloadRoute",
        ClusterId = app.Name,
        Match = { Path = $"{app.Prefix.TrimEnd('/')}/sockjs-node/{{*remainder}}" },
        Transforms = new List<IDictionary<string, string>> {
        new Dictionary<string, string> {{"PathPattern", "/sockjs-node/{remainder}"}}
    }
    }).ToList();
    proxyRoutes.AddRange(uiLiveReloadRoutes);
}
```

The above should not longer be needed.

**Comment by prabh-62** [comment]
Thank you for the correction, Alan. I removed that code you mentioned and hot reloading works behind a reverse proxy now.
BTW, Do I need `publicHost` or `servePath` option when serving app behind a proxy since these options don't affect anything?

**Comment by alan-agius4** [comment]
In your case you don’t need to use any of those options.
