### ISSUE TITLE
Option "baseHref" is deprecated: Use the "baseHref" option in the browser builder instead.

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#19195]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Redundant warnings from Angular CLI when trying to start angular application in dev mode.

## 🔬 Minimal Reproduction
```bash
> npx @angular/cli@v11.0.0-rc.0 new web-applications --create-application=false --strict
> cd web-applications
> yarn ng generate application support-panel --routing --style css
```
- Edit `angular.json` and add values for `baseHref`, `deployUrl` under `ng serve`(not `ng build`) so that the app is served over `http://localhost:4200/support/` and not `http://localhost:4200/`
```json
    "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "support-panel:build",
            "baseHref": "/support/",
            "deployUrl": "/support/"
          },
```
<img width="759" alt="baseHref_angular" src="https://user-images.githubusercontent.com/13006107/97064836-1acf0b00-1577-11eb-93f6-9a73f0a0215b.png">

- `> yarn ng serve --project support-panel`
<img width="1118" alt="warnings_cli_baseHref" src="https://user-images.githubusercontent.com/13006107/97064870-6d102c00-1577-11eb-8611-bcb2abe7cac5.png">

## 🔥 Exception or Error
<pre><code>
Option "baseHref" is deprecated: Use the "baseHref" option in the browser builder instead.
Option "deployUrl" is deprecated: Use the "deployUrl" option in the browser builder instead.
</code></pre>

## 🌍 Your Environment
<pre><code>
$ ng version

Angular CLI: 11.0.0-rc.0
Node: 15.0.1
OS: darwin x64

Angular: 11.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-rc.0
@angular-devkit/build-angular   0.1100.0-rc.0
@angular-devkit/core            11.0.0-rc.0
@angular-devkit/schematics      11.0.0-rc.0
@schematics/angular             11.0.0-rc.0
@schematics/update              0.1100.0-rc.0
rxjs                            6.6.3
typescript                      4.0.3
    
Done in 1.00s.
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This is indented as these options have been deprecated in the dev-server (serve) builder.

Configure the options under the the browser (build) builder instead.

`baseHref` and `deployUrl` are build and dev-server settings and therefore should be configured in the build builder.
