### ISSUE TITLE
ng serve wont work if index.html has base href other than /

### ISSUE THREAD

**Issue by Akxe** [angular/angular-cli#19206]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

When a user decides to change in `index.html`, then the `ng serve` won't take that into account and will not serve any of the compiled JS files.

## 🔬 Minimal Reproduction

* create a new project npx @angular/cli new my-project
* modify `<base>` tag to `<base href="/folder/">` or similar...
* run `ng serve`
* open given URL
* the page opened will show error that `runtime.js` returned 404 errror

## 🔥 Exception or Error

404 for all of compiled files, as browser ask for `/folder/script.js` rather than typical `/script.js`

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.1
Node: 12.16.1
OS: win32 x64

Angular: 10.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error> // I am using nx

Package                           Version
-----------------------------------------------------------     
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1001.1
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

I am using NX. I have 4 apps one is served from "/", but others are served from subdirectories (`/admin/`, `/shop/`...)

**Comment by alan-agius4** [comment]
Hi @Akxe,

Instead of setting the base href manually in the html file set in in the browser builder options in your `angular.json`.

See: https://angular.io/cli/build
