### ISSUE TITLE
[Yarn2] Installing temporary version of `@angular/cli` fails

### ISSUE THREAD

**Issue by andreialecu** [angular/angular-cli#19209]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] update

### Is this a regression?

No

### Description

When using Yarn 2 these flags are not supported:
https://github.com/angular/angular-cli/blob/b7890b6afcf08036c1f67274e61db2ccc02a021d/packages/angular/cli/utilities/install-package.ts#L168-L174

This results in an error installing the `@angular/cli` when the locally installed version is not the latest.

A workaround is to run `yarn add @angular/cli@latest` to manually update the cli version prior to invoking `ng update`

Also see: https://github.com/angular/angular-cli/issues/16980

## 🔬 Minimal Reproduction

```
cd /tmp
ng new --skip-install ngupdate-repro
cd ngupdate-repro

yarn set version 2
yarn config set nodeLinker node-modules
yarn install

yarn ng update
```

## 🔥 Exception or Error

```
yarn ng update
(node:7598) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via yarn.
An unhandled exception occurred: Unknown Syntax Error: Command not found; did you mean one of:

  0. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] ...
  1. yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] ...

While running add @angular/cli@latest --silent --modules-folder=/tmp/angular-cli-packages-41IvHp/node_modules --no-lockfile
Package install failed, see above.
See "/tmp/ng-pACkYq/angular-errors.log" for further details.
```

![image](https://user-images.githubusercontent.com/697707/97083678-6c7ca180-161a-11eb-88b6-40c0df203bb5.png)

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.2.0
Node: 13.7.0
OS: linux x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cli                    10.2.0
@angular/material               8.2.3
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Comment by pongells** [comment]
I am getting the same error trying to update to angular 12. Workaround works, thanks.

**Comment by clydin** [comment]
This has been corrected in version 14.  Invalid options for Yarn 2+ will no longer be used when installing the temporary version during update.  If the issue is still being encountered with the latest version of the Angular CLI, please open a new issue with updated project information.
