### ISSUE TITLE
Unable to get bootstrap working with cli@webpack

### ISSUE THREAD

**Issue by fkolar** [angular/angular-cli#1920]
Hi guys, 

while Looking at the #630, I can not seems to find  any similarities with the new @webpack version. I tried to include bootstrap. 
When I add node_modules/.../bootstrap/***/.sass file, it does not complain when you try to build the project it is just during a runtime it cannot find the styles. 

Is there anything else which needs to be done ? 

1. I have to bootstrap installed under my npm package modules
2. I included the scss files

Thanks so much for any guidence. 

Frank

**Comment by fkolar** [comment]
this is my angular-cli.json


 ```
 "project": {
    "version": "1.0.0-beta.11-webpack.2",
    "name": "angular-meta-ui"
  },
  "apps": [
    {
      "main": "src/main.ts",
      "tsconfig": "src/tsconfig.json",
      "mobile": false,
      "styles": [
        "src/main.scss",
        "./node_modules/bootstrap/scss/bootstrap-flex.scss"
      ]
    }
  ],
```

I should not need to @import all the styles right? when I am not doing it inside my project. I guess webpack takes all the scss files and combine them togher ?

I would need this main.scss as well to define some global variables and even this one is not picked up.

**Comment by ankitSaroch** [comment]
Is the below `defaults.styleExt` set to `scss` in angular-cli.json
    "defaults": {
        "styleExt": "scss",
        ...
      }

**Comment by Richard87** [comment]
Where do I find the new webpack versions? I can only see webpack.2 on the tag-list?

**Comment by filipesilva** [comment]
@fkolar @Richard87 the latest version, `beta.15` should allow you to import global css and js. See https://github.com/angular/angular-cli#global-library-installation for detailed instructions on how to use bootstrap.
