### ISSUE TITLE
i18n - implement `duplicateMessageHandling` in message extraction

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular-cli#19207]
The extractor supports an option to report warnings/errors if there are messages with the same id but different message text.

See https://github.com/angular/angular/blob/79620f5139c80f1b3b38168744ca99a224c7e5cd/packages/localize/src/tools/src/extract/main.ts#L89-L95

Exposing this via the CLI integration would help to avoid confusing issues like https://github.com/angular/angular/issues/39227.

**Comment by AndrewKushnir** [comment]
I think it'd be great to set the default value to "warning" (as we have it on the framework side), so that we surface this error to users without the need to configure it.
