### ISSUE TITLE
Wrong separator from import in app.module.ts when generate component

### ISSUE THREAD

**Issue by rlouissidney** [angular/angular-cli#1921]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

 ng generate component shared/toolbar

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Not work when  running, and see  in app.module.ts :
import { ToolbarComponent } from './shared\toolbar/toolbar.component';

5. Mention any other details that might be useful.
 Minor bug
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by niklas-dahl** [comment]
They are already aware of this bug: https://github.com/angular/angular-cli/issues/1719

**Comment by rlouissidney** [comment]
Ok ! I made a search but not with the good word.
Thank you !
