### ISSUE TITLE
ng serve --charset=iso-8859-1

### ISSUE THREAD

**Issue by deveras** [angular/angular-cli#19210]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description and minimal reproduction

.editorconfig chatset is correctly set to: charset=iso-8859-1,
Index.html has the charset correctly set to <meta charset="ISO-8859-1"/>
ng serve sends content as: Content-Type: ; charset=UTF-8

It would be nice to have a flat allowing the specification on charset or a configuration file detailing each charset per file type.

##  Environment
<pre><code>
Angular CLI: 10.1.7
Node: 14.13.1
OS: darwin x64

Angular: 10.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cli                    10.1.7
@schematics/angular             10.1.7
@schematics/update              0.1001.7
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Comment by alan-agius4** [comment]
HI @deveras,

`Webpack` only emits assets in UTF-8, Hence, `webpack-dev-server` will serve all assets as UTF-8. To use non UTF-8 encoding you must set the appropriate charset like so:

```json
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "browserTarget": "testing:build",
    "headers": {
      "Content-Type": "text/html; charset=iso-8859-1"
    }
  },
},
```

Note: that the above requires using Angular CLI 11, which is currently in RC.

**Comment by deveras** [comment]
Thank you for the reply @alan-agius4,
I've tried the setup you described but got the following command line error:

$ ng serve --open --port=1978
Schema validation failed with the following errors:
Data path "" should NOT have additional properties(headers).

Then tried:

"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
    "options": {
      "browserTarget": "Blog:build"
     },
    "configurations": {
       "production": {
         "browserTarget": "Blog:build:production",
         "headers": {
           "Content-Type": "text/html; charset=iso-8859-1"
         }
      }
    }
},

It builds, but still serves UTF-8, I'll reconfirm now if all files are ISO-8859-1 (in case one isn't and perhaps that will make the header fail).

**Comment by deveras** [comment]
I've also tried with application/javascript; but no luck

**Comment by alan-agius4** [comment]
Are you using Angular CLI 11.0.0-rc.0?

**Comment by deveras** [comment]
Angular CLI: 10.1.7, I can try that and report back

**Comment by alan-agius4** [comment]
```cmd
➜   curl -v -s localhost:4200/index.html 1> /dev/null *   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 4200 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4200 (#0)
> GET /index.html HTTP/1.1
> Host: localhost:4200
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: text/html; charset=iso-8859-1
< Accept-Ranges: bytes
< Content-Length: 492
< ETag: W/"1ec-UHRDBFptwajdoMyDJK/LrROowlY"
< Date: Mon, 26 Oct 2020 13:10:36 GMT
< Connection: keep-alive

```

Note: the above setting does have the drawback of adding that header to all responses.

**Comment by deveras** [comment]
$  curl -v -s localhost:1978/index.html 1> /dev/null
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1978 (#0)
> GET /index.html HTTP/1.1
> Host: localhost:1978
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Accept-Ranges: bytes
< Content-Type: text/html; charset=UTF-8
< Content-Length: 3185
< ETag: W/"c71-QDTB3cfd4a1aY92eOeUX5U46g0k"
< Date: Mon, 26 Oct 2020 14:42:51 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
{ [3185 bytes data]
* Connection #0 to host localhost left intact
* Closing connection 0

No such luck
