### ISSUE TITLE
How to custom node in @angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js

### ISSUE THREAD

**Issue by MrHOY** [angular/angular-cli#19229]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

When I use "@angular-devkit/build-angular": "~0.901.12" my project work well.
But when I upgrade "@angular-devkit/build-angular": "~0.1001.1" my project not run with many errors below:
![image](https://user-images.githubusercontent.com/20653706/97286976-9cc07c00-1876-11eb-9373-d0fb88a8ca8d.png)

I try to find out what different and I know the problem

@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/browser.js 
**node: false**

I need to set **node: {crypto: true, stream: true}**, then my project work well

Of course, I can do manually, but that is unprofessional and will be difficult for other programmers
I want to ask have any way to custom node like that automatically ?

**Comment by alan-agius4** [comment]
Hi, it looks like you are using Node.js libraries in your browser application. This is not something which is supported out of the box of the CLI.

You can add use 3rd party builders to do this change like https://github.com/manfredsteyer/ngx-build-plus.

**_NB: While modifying build settings as the above are possible, such changes and issues that they may causes are not supported by the Angular tooling team._**
