### ISSUE TITLE
Warning about ES2017+ target does not show when using Webpack plugin

### ISSUE THREAD

**Issue by thw0rted** [angular/angular-cli#19226]
# 🐞 Bug report

### Component
`@ngtools/webpack` (`AngularCompilerPlugin`)

### Is this a regression?

No

### Description

https://github.com/angular/angular-cli/pull/13643 added a warning message when the TS compiler is configured to emit ES2017 or higher, due to https://github.com/angular/angular-cli/issues/13477.  This warning is not displayed when the project is built via Webpack using `AngularCompilerPlugin`.  I asked on https://github.com/angular/angular/issues/31730 and it sounds like we need a separate ticket to track this since the linked PR and issue are both auto-closed.  It doesn't look like there's a path forward on the Zone issue so this is going to keep biting people for a good while, I think.

## 🔬 Minimal Reproduction

Pick any project you have lying around that uses `AngularCompilerPlugin`, change `compilerOptions.target` in the `tsconfig.json` to `ES2017`, and build.  If you were building it with the CLI you'd see `Warning: Zone.js does not support native async/await in ES2017` on the console, but not with the plugin.

## 🌍 Your Environment

`@ngtools-webpack` 10.1.2, but I don't see any relevant changes in the recent 11+ builds.

**Comment by thw0rted** [comment]
@alan-agius4 is "freq1" really appropriate?  The plugin has 1.5M weekly downloads on NPM, and while I'm sure that ES2015 is the most popular emit target by a wide margin, in late 2020 we have broad browser support for the full ES2017 feature set, including async/await.

I started my project with a lower emit years ago, but at some point I raised it to ES2018 (I do have the luxury of running in a known environment) and it seemed to "just work", so I left it that way.  It wasn't until I spent 2+ days tracking down a mysterious inability to test some async code that I found the linked Zone issue.  If it happened to me, it's happening to a nontrivial percentage of your users, and even 1% of 1.5M users is hardly "only a handful, who observe it rarely".

**Comment by alan-agius4** [comment]
Hi @thw0rted,

Most of the package downloads comes from `@angular/cli` users. Approximately 8% of the users use `@ngtools/webpack` without Angular CLI. That 8% goes down even more when taking into account users that target only ES2017+.

That said, I do have a PR in flight for this https://github.com/angular/angular-cli/pull/19228

**Comment by thw0rted** [comment]
Sorry, Alan, I was going by [the NPM page](https://www.npmjs.com/package/@ngtools/webpack) -- I didn't realize those numbers reflected usage other than via Webpack.  (Or, I guess, the CLI uses Webpack under the hood?)  Anyway, it looks like this was a quick fix, which is great news.  Thanks!

**Comment by alan-agius4** [comment]
No worries @thw0rted, yes the CLI does use Webpack under the hood.
