### ISSUE TITLE
Source map error with RC version update

### ISSUE THREAD

**Issue by JSmithOner** [angular/angular-cli#19236]
# 🐞 Bug report

### Command (mark with an `x`)

- [X] serve
- [X] update

### Is this a regression?

Yes

### Description

 A clear and concise description of the problem...

when connecting to `http://localhost:4200` after `ng serve` I get a blank screen page and an error

## 🔬 Minimal Reproduction

Maybe not the best idea I had but I've runned the following command
all of the following packages where on 8 version

`ng update @angular/cdk @angular/cli @angular/core @angular/material rxjs --allowDirty --next --force`

now my `angular.json` looks like that:

```
  "dependencies": {
    "@angular/animations": "^11.0.0-rc.0",
    "@angular/cdk": "^11.0.0-rc.0",
    "@angular/common": "^11.0.0-rc.0",
    "@angular/compiler": "^11.0.0-rc.0",
    "@angular/core": "^11.0.0-rc.0",
    "@angular/fire": "^6.0.2",
    "@angular/forms": "^11.0.0-rc.0",
    "@angular/material": "^11.0.0-rc.0",
    "@angular/platform-browser": "^11.0.0-rc.0",
    "@angular/platform-browser-dynamic": "^11.0.0-rc.0",
    "@angular/router": "^11.0.0-rc.0",
    "@types/fabric": "^3.0.0",
    "bootstrap": "^4.3.1",
    "color": "^3.1.2",
    "core-js": "^2.5.4",
    "fabric": "^3.3.2",
    "fabric-with-gestures": "^4.0.0-rc.1",
    "firebase": "^7.19.1",
    "jquery": "^1.9.1",
    "popper.js": "^1.14.7",
    "rxjs": "^7.0.0-beta.8",
    "tslib": "^1.9.0",
    "zone.js": "^0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1100.0-rc.0",
    "@angular/cli": "~11.0.0-rc.0",
    "@angular/compiler-cli": "~11.0.0-rc.0",
    "@angular/language-service": "~11.0.0-rc.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jquery": "^3.3.31",
    "@types/node": "^8.9.5",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslib": "^1.9.0",
    "tslint": "~6.1.3",
    "typescript": "~4.0.5"
  }
```

## 🔥 Exception or Error
<pre>
  <code>
    Error: request failed with status 404
    ressource URL: http://localhost:4200/vendor.js
    URL source link: startWith.js.map
  </code>
</pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.0-rc.0
Node: 14.5.0
OS: darwin x64

Angular: 11.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-rc.0
@angular-devkit/build-angular   0.1100.0-rc.0
@angular-devkit/core            11.0.0-rc.0
@angular-devkit/schematics      11.0.0-rc.0
@angular/fire                   6.0.2
@schematics/angular             11.0.0-rc.0
@schematics/update              0.1100.0-rc.0
rxjs                            7.0.0-beta.8
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

The error message used to show on Chrome but the one I gave you is a translation of Firefox and don't show on Chrome anymore.
Firefox 82.0.1
Chrome 86.0.4240.111

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
In a nutshell what is happening here is that.

In version 11, we no longer process vendor sourcemaps unless the `vendor` option is enabled which improves build time, ~3 seconds on an `ng new` application. The drawback of this that `//# sourceMappingURL` comment is not removed from the source file of the libraries. Hence, a warning will be issued in the console because the sourcemap cannot be loaded.

**Comment by JSmithOner** [comment]
@alan-agius4 Sorry I din't gave you an example but the project is quite big and I assumed I gave you sufficent infos to reproduce the basic case (which is updating an existing project) as when I downgraded back to the latest 10th version of angular everything went back to normal. Thanks again for your time

**Comment by alan-agius4** [comment]
@JSmithOner, I was able to replicate the reported issue.
