### ISSUE TITLE
liveReload does not detect changes and rebuild [MacOS Catalina]

### ISSUE THREAD

**Issue by mixuala** [angular/angular-cli#19230]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

YES. the same code works fine in MacOS 10.13.6 HighSierra 

### Description

ng serve is not rebuild/reloading after code changes. This problem occurs on a MacOS system that was recently upgraded to MacOS 10.15.7-Catalina, but does NOT occur on an older mac running MacOS 10.13.6 HighSierra 

## 🔬 Minimal Reproduction
```
npm install -g @ionic/cli
ionic start --type=angular myApp tabs
# choose No for Capacitor
cd ./myApp
# ionic serve uses the Angular CLI. Use ng serve --help to list all Angular CLI options for serving your app. See the ng serve docs for explanations
ng serve
# change HTML markup on ./src/app/tab1/tab1.page.html
```

## 🔥 Exception or Error
<pre><code>
n/a
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.0.8
Node: 12.16.1
OS: darwin x64

Angular: 10.0.14
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.8
@angular-devkit/build-angular     0.1000.8
@angular-devkit/build-optimizer   0.1000.8
@angular-devkit/build-webpack     0.1000.8
@angular-devkit/core              10.0.8
@angular-devkit/schematics        10.0.8
@angular/cli                      10.0.8
@ngtools/webpack                  10.0.8
@schematics/angular               10.0.8
@schematics/update                0.1000.8
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

Ionic:

   Ionic CLI                     : 6.12.0 (/Users/m/.nvm/versions/node/v12.16.1/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.4.1
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.16.1 (/Users/m/.nvm/versions/node/v12.16.1/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina

</code></pre>

**Anything else relevant?**

Works on an older mac running MacOS 10.13.6 HighSierra 
does NOT work on MacOS 10.15.7-Catalina

**Comment by alan-agius4** [comment]
Hi @mixuala, 

I unfortunately am unable to replicate the issue using the steps provided above locally on `macOS Catalina version 10.15.7`.

**Comment by alan-agius4** [comment]
I'm sorry, but unfortunately  we can't reproduce the problem following the instructions and the same version of operating system you provided, hence it might be related to your local environment.

Feel free to open a new issue if you discover something else that points to be an Angular CLI issue.

Thanks.

**Comment by mixuala** [comment]
Thanks for your tip. It helped me find the problem:

`liveReload` does not seem to work with [MacOS] `synthetic.conf`. I tested with a folder in the home directory and everything works as expected

references:
- https://stackoverflow.com/questions/58396821/what-is-the-proper-way-to-create-a-root-sym-link-in-catalina
- https://github.com/livereload/livereload-site/blob/master/livereload.com/_articles/troubleshooting/os-x-fsevents-bug-may-prevent-monitoring-of-certain-folders.md
