### ISSUE TITLE
connect ETIMEDOUT 172.217.13.234:443 - Even after analytics are off

### ISSUE THREAD

**Issue by vjangari** [angular/angular-cli#19259]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

ng build --prod -> build trying to connect google server despite of switch off analytics
ng analytics off 
also we tried angular.json file

connect ETIMEDOUT 172.217.13.234:443

**Comment by alan-agius4** [comment]
@vjangari,

Can you please provide the output of `ng version`?

**Comment by vjangari** [comment]
![image](https://user-images.githubusercontent.com/19578189/97635333-8d276b80-1a0d-11eb-92b8-a55ad521945d.png)

**Comment by vjangari** [comment]
ng build is working fine. However ng build --prod is failing on CI server

**Comment by alan-agius4** [comment]
Likely this is related to the new fonts optimizations which requires internet access during the build. Can you confirm that you are referencing Google fonts and/or icons in your html file?

We should be showing a more actionable error in this case

**Comment by vjangari** [comment]
Yes I am using below link
 <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

Same build is working fine with below dev dependencies. But not with rc1 versions

 "@angular-devkit/build-angular": "0.1100.0-next.5",
    "@angular/cli": "11.0.0-next.5",
    "@angular/compiler-cli": "11.0.0-next.5",

**Comment by alan-agius4** [comment]
In case your build server don't have access to internet, you'd want to disable the inline fonts optimization.

This can be done by via the `optimization` option in your browser builder configuration.

``` diff
- "optimization": true,
+ "optimization": {
+   "styles": true,
+   "scripts": true,
+   "fonts": {
+     "initial": false
+   }
+ },
```

**Comment by vjangari** [comment]
Schema validation failed with the following errors:
  Data path ".optimization" should be boolean.

**Comment by alan-agius4** [comment]
Can you share the `build` section of your angular.json?

**Comment by vjangari** [comment]
`"production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
              "extraWebpackConfig": "webpack.prod.config.js"              
            },
`

**Comment by alan-agius4** [comment]
Looks like you are not using an official Angular CLI builder.

Kindly open an issue in the issue tracker of 3rd party builder.

**Comment by vjangari** [comment]
ok. Sure. I am trying Module Federation with webpack 5 support. I will open ticket in corresponding repo.  When can we expect official support for webpack 5 in angular cli?

**Comment by alan-agius4** [comment]
Experimental opt-in support for Webpack version 5 have been added since v11.0.0-next.3.

See #18820 for more information.

For module federation support kindly subscribe to  https://github.com/angular/angular-cli/issues/17556
