### ISSUE TITLE
Installing 1.0.0-beta.11-webpack.8 actually installs 1.0.0-beta.10 instead

### ISSUE THREAD

**Issue by batchu** [angular/angular-cli#1926]
Installing 1.0.0-beta.11-webpack.8 actually installs 1.0.0-beta.10 instead on Windows 7. I"m going crazy

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
Want 1.0.0-beta.11 but instead it installs beta.10

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Run:
npm i -g angular-cli@1.0.0-beta.11-webpack.8
Now run
C:\Windows\system32>ng -v
(node:7820) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
angular-cli: 1.0.0-beta.10
node: 6.5.0
os: win32 x64

**Comment by neilhem** [comment]
Clean your cache `npm cache clean` & try to install again `npm i -g angular-cli@1.0.0-beta.11-webpack.8`

**Comment by batchu** [comment]
This is getting so weird. I tried a clean and install. I now see a mobile version of angular-cli as installed when I do an ng -version

Here's the [output](https://shrib.com/VEQXsXa47fJ0obS?v=nc)

**Comment by wjke** [comment]
try `npm cache clean` and npm install angular-cli@webpack then check version in new instance of cmd or manually `%APPDATA%\npm\node_modules\angular-cli\package.json`

**Comment by mwawrusch** [comment]
I can confirm the same problem on os.x . Cleaning multiple times and reinstalling did not help

**Comment by niklas-dahl** [comment]
`ng --version` shows the locally installed version if you are in a folder with the cli installed, otherwise it shows the globally installed version.

**Comment by batchu** [comment]
@niklas-dahl  I ran that command outside of an existing angular2 cli project

**Comment by bradygossett** [comment]
Im experiencing the same problem. After following install/ update directions my version remains: angular-cli: 1.0.0-beta.10

**Comment by filipesilva** [comment]
Does this still happen with latest with the latest version (`beta.15`)?

**Comment by filipesilva** [comment]
I believe this is just what @niklas-dahl said to be honest - the difference in version from inside and outside a project.
