### ISSUE TITLE
Pipe error after updated to RC6

### ISSUE THREAD

**Issue by lednhatkhanh** [angular/angular-cli#1929]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 64bit

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8                                                                                           
node: 6.4.0                                                                                                                    
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Update the package.json to RC6:
`"dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "core-js": "^2.4.1",
    "ng-semantic": "^1.1.1",
    "rxjs": "5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.17"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.11-webpack.8",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "^1.2.0",
    "karma-chrome-launcher": "^0.2.3",
    "karma-jasmine": "^0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.0"
  }`
- Delete the node_modules folder
- Run npm install
- Run ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
ERROR in [default] c:\Users\lednh\Documents\ng2\angular2-simple-todos\src\app\app.component.ts:17:2                            
Argument of type '{ selector: string; template: any; styles: any[]; providers: typeof TodoService[]; pipes: typeof ...' is not 
assignable to parameter of type 'ComponentMetadataType'.                                                                       
  Object literal may only specify known properties, and 'pipes' does not exist in type 'ComponentMetadataType'.

```
5. Mention any other details that might be useful.

app.component.ts

`@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [ TodoService ],
  pipes: [TodoPipe] // Error in this line!
})`

todo.pipe.ts

`import { Pipe, PipeTransform } from '@angular/core';
import { Todo } from './todo';

@Pipe({
  name: 'todoFilter'
})
export class TodoPipe implements PipeTransform {

  transform(allTodos: Todo[], args?: boolean) {
    if (!allTodos) {
      return null;
    }
    return allTodos.filter(todo => todo.isCompleted === args);
  }

}`
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
@lednhatkhanh as of rc6 all deprecated apis were removed from angular2, including providers your pipes, providers, and components in other components. Do all of that in NgModule

**Comment by lednhatkhanh** [comment]
Thank you, I remove the import and pipes and everything's working fine now
