### ISSUE TITLE
Option to specify schematics to install and run during new project creation

### ISSUE THREAD

**Issue by avatsaev** [angular/angular-cli#19302]
# 🚀 Feature request

Ability to specify schematics to install and run during new project creation with `ng new`

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Use case example: I want to start a new project and have angular material, cdk, and ngrx installed and setup right after the project been bootstrapped.

### Describe the solution you'd like

```
ng new my-project --schematics=@angular/material,@angular/cdk,@ngrx/store
```

If the schematics have interactive setup scripts after installation, run the interactive installation scripts in the order defined in the `--schematics` option (the name for the options might not be appropriate, maybe pick a more explicit name for the option?)

**Comment by alan-agius4** [comment]
Hi @avatsaev,

Thanks for opening this feature request.

This currently can be done by using `ng add` after the generation of the application.

```
ng new my-app
cd my-app
ng add @angular/material 
ng add @ngrx/store
```

Or you can concatenate the commands as follows:

```
ng new my-app && cd my-app && ng add @angular/material && ng add @ngrx/store
```

Seeing that this is possible by running an additional command and creating an application is not something which is done that often, this request doesn’t currently fall in the CLI roadmap.

If you do create applications with the above often, it is possible to extend the default `ng-new` schematic to add the desired functionality. Alternatively you can also create a small Shell or Node script that does the above for you.
