### ISSUE TITLE
ng update --all --force fails

### ISSUE THREAD

**Issue by pavankjadda** [angular/angular-cli#19311]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, it used to work on Angular CLI version 10.2.0 

### Description
When I run `ng update --all --force` in my project I get following error
```
    Updating package.json with dependency primeng @ "10.0.3" (was "10.0.2")...
    Updating package.json with dependency tslib @ "2.0.3" (was "2.0.1")...
    Updating package.json with dependency zone.js @ "0.11.3" (was "0.10.3")...
UPDATE package.json (2083 bytes)
⠦ Installing packages...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: eshopping-ui@3.3.1
npm ERR! Found: zone.js@0.11.3
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"^0.11.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@10.2.2
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^10.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/pjadda/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pjadda/.npm/_logs/2020-11-06T02_43_04_031Z-debug.log
✖ Package install failed, see above.
✖ Migration failed. See above for further details.


```

## 🔬 Minimal Reproduction
Clone the [repo](https://github.com/pavankjadda/eShopping-UI) and run the `ng update --all --force` command

## 🔥 Exception or Error
<pre><code>
    Updating package.json with dependency primeng @ "10.0.3" (was "10.0.2")...
    Updating package.json with dependency tslib @ "2.0.3" (was "2.0.1")...
    Updating package.json with dependency zone.js @ "0.11.3" (was "0.10.3")...
UPDATE package.json (2083 bytes)
⠦ Installing packages...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: eshopping-ui@3.3.1
npm ERR! Found: zone.js@0.11.3
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"^0.11.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.10.3" from @angular/core@10.2.2
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^10.2.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/pjadda/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pjadda/.npm/_logs/2020-11-06T02_43_04_031Z-debug.log
✖ Package install failed, see above.
✖ Migration failed. See above for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.4
Node: 15.0.0
OS: darwin x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    10.2.3
@angular/material               10.2.3
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by pavankjadda** [comment]
Thanks, it looks like Node 14 and 15 versions mixed up. Deleting version 14 fixed the issue

**Comment by ashutoshphalke** [comment]
How to delete Node 14 to fix this issue?
