### ISSUE TITLE
ng serve with a relative deploy-url OR "Cannot GET /" 

### ISSUE THREAD

**Issue by andreElrico** [angular/angular-cli#19316]
# 🐞 Bug report

### Command (mark with an `x`)

- [ X ] serve

### Is this a regression?

Yes, its a regression.

### Description

There is quite alot on this topic. Nothing however solved this problem for me. It just used to work, now its doesnt. (Havent used `ng serve` for quite sometime and today I found it just does not work as it used to be).

## 🔬 Minimal Reproduction

1. in angular.json

```
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "deployUrl": "./",
```
2. `ng serve MY_TARGET_PROJECT -o`

3. browser cant resolve and find anything => `Cannot GET /`

interessting: navigating to url  `http://localhost:4200/index.html` will at least give the html and will then fail with all JS imports etc...

## Connected issues
#10736 , #6289

## PLEASE READ THIS !!!
I fail to see how this issue gets closed over and over? With `"deployUrl": "./",` and `ng serve` it should work as it always used to.

the only way how I could start developing was by adding

```
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "deployUrl": "/",
```

then my assets wont work because there relative as well. I fail to see whats the problem here :/

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.12
Node: 13.8.0
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.901.12
@angular-devkit/build-ng-packagr   0.901.12
@angular-devkit/build-optimizer    0.901.12
@angular-devkit/build-webpack      0.901.12
@angular-devkit/core               9.1.12
@angular-devkit/schematics         9.1.12
@angular/cdk                       9.2.4
@angular/flex-layout               9.0.0-beta.31
@angular/material                  9.2.4
@ngtools/webpack                   9.1.12
@schematics/angular                9.1.12
@schematics/update                 0.901.12
ng-packagr                         9.1.5
rxjs                               6.6.3
typescript                         3.8.3
webpack                            4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @andreElrico,

You can use the `servePath` option to adjust the serving path https://angular.io/cli/serve
```
ng serve --deployUrl='./' --servePath='/'
```
