### ISSUE TITLE
Applying Typescript Transforms Before the @ngtools/webpack Loader

### ISSUE THREAD

**Issue by benwinding** [angular/angular-cli#19328]
## Goal
So I'm trying to apply a typescript transform to angular files _BEFORE_ the webpack plugin `AngularCompilerPlugin` touches them.

## Problems
- It seems that the webpack loader `@ngtools/webpack` ignores all previous loaders _(The @ngtools/webpack loader does not fully support loader chaining)_ as mentioned in [this comment](https://github.com/angular/angular-cli/issues/16544#issuecomment-571245469)
- It seems that the `AngularCompilerPlugin` directly touches the filesystem instead of using webpack's virtual filesystem as explained in [this comment](https://github.com/angular/angular-cli/issues/9089#issuecomment-355558260)
- It seems custom typescript transforms are not on the road map :disappointed:  https://github.com/angular/angular/issues/22434#issuecomment-594074902

## Possible Solution
-  In a few blog posts and tutorials I've seen ([like this one](https://indepth.dev/having-fun-with-angular-and-typescript-transformers)), it seems like I might be able to use the `AngularCompilerPlugin`'s private api `_transformers` or  `_platformTransformers`, but adding a transformer doesn't seem to transform the typescript **_BEFORE_** the `AngularCompilerPlugin` processes the typescript.

Does anyone have any suggestions? Is this even possible?

Lastly big thanks to all the contributors! :+1: 

## Related Issues
- Support custom TypeScript transformers #22434
- Add possibility to use webpack with an alternative file system #9089
- @ngtools/webpack: Misleading documentation & Config Refactor Proposal #9063
- Angular CLI does not apply custom webpack loader #18474
- Ordering issue between @ngtools/webpack + other loader #16544
- Custom typescript transformer source file changes are not applied #16250

**Comment by alan-agius4** [comment]
@benwinding, can you please explain what you are trying to achieve and what are the problem you are facing when using TypeScript transformers?

**Comment by benwinding** [comment]
Hi @alan-agius4,
Thanks for the quick response. I'd basically like to insert my own typescript transformer plugin into the webpack build pipeline. Like this: 

![image](https://user-images.githubusercontent.com/11782590/98644457-6576c280-2380-11eb-9965-d3cbd8e3db09.png)

This transformer would convert my own type of decorators and generate **_angular_** decorators (`@NgModule` and `@Component`), and pass it to the angular compiler, which will proceed with the rest of the build. Like this:

![image](https://user-images.githubusercontent.com/11782590/98645351-bcc96280-2381-11eb-8966-cb249249f1ea.png)

Any ideas or suggestions on how to accomplish this goal?

Thanks for any help you can offer,
Ben

**Comment by alan-agius4** [comment]
Hi @benwinding,

That is something which is not possible and is not in the roadmap to support. See @alxhub comment in https://github.com/angular/angular/issues/22434#issuecomment-594074902. As Alex highlighted, TypeScript transformers run before emit, hence using a typescript transformer in this case is already too late as the analysis phase would have already been finalized.

This above pattern also has the drawback that it breaks `ng update` code migrations because these expect that `@NgModule`, `@Component` and other Angular decorators are present in code. This would result in having to apply and fix breaking changes manually instead of using the automated code migrations offered by Angular.

**Comment by benwinding** [comment]
Hi @alan-agius4,

Thanks for the response, I can understand the current limitations. 

> This above pattern also has the drawback that it breaks `ng update` code migrations because these expect that @NgModule, @Component and other Angular decorators are present in code. This would result in having to apply and fix breaking changes manually instead of using the automated code migrations offered by Angular.

See I don't believe this is a drawback. The code migrations will still work as existing `@NgModule`'s and `@Component`'s in the application source code will still be detected and migrated with `ng update`.

The generated transformed `@NgModules` by _MyTransformerPlugin_ will only exist in memory during the build. Any migrations that are necessary are simply implemented in the _transformer library_.... so no manual migration, right? This would mean that the library would need to be versioned with angular 8.x, 9.x etc... but pretty much all angular libraries need that anyway.

Anyway, I really want to _alter_ the Angular build process, rather than abstracting around the entire process, but it seems this is not possible _yet_... anyway I appreciate your quick responses and help with the matter.

Cheers,
Ben
