### ISSUE TITLE
I cant creat Image in SV with Docker using Angular app, Terminal will be reused by tasks, press any key to close it.

### ISSUE THREAD

**Issue by Royjonespi** [angular/angular-cli#19329]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

> Executing task: docker build --pull --rm -f "angular-app/dockerfile" -t angular-app:tesv1 "angular-app" <

[+] Building 235.6s (13/13) FINISHED                                                                                                                                    
 => [internal] load .dockerignore                                                                                                                                  0.1s
 => => transferring context: 2B                                                                                                                                    0.1s
 => [internal] load build definition from dockerfile                                                                                                               0.2s
 => => transferring dockerfile: 234B                                                                                                                               0.1s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                                                    2.1s
 => [internal] load metadata for docker.io/library/node:latest                                                                                                     2.0s
 => [stage-1 1/2] FROM docker.io/library/nginx:alpine@sha256:9b22bb6d703d52b079ae4262081f3b850009e80cd2fc53cdcb8795f3a7b452ee                                      0.0s
 => [internal] load build context                                                                                                                                 11.3s
 => => transferring context: 5.48MB                                                                                                                               10.5s
 => [node 1/5] FROM docker.io/library/node:latest@sha256:8ebfdeee577821f6c9caf672f3cb99fc2de39a9cb1d09a80a33d157c1452030f                                          0.0s
 => CACHED [node 2/5] WORKDIR /app                                                                                                                                 0.0s
 => [node 3/5] COPY . .                                                                                                                                           86.6s
 => [node 4/5] RUN npm install                                                                                                                                    22.4s
 => [node 5/5] RUN npm run build --prod                                                                                                                          112.5s
 => CACHED [stage-1 2/2] COPY --from=node /app/dist/angular-app /usr/share/nginx/html                                                                              0.0s
 => exporting to image                                                                                                                                             0.0s
 => => exporting layers                                                                                                                                            0.0s
 => => writing image sha256:53a5cbbe38f04406390f7a34c818a5c648b00827d13d8bce052d547e38c4b5ce                                                                       0.0s
 => => naming to docker.io/library/angular-app:tesv1                                                                                                               0.0s

Terminal will be reused by tasks, press any key to close it.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
dockerfile

# stage 1
FROM node:latest as node
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

# stage 2
FROM nginx:alpine
COPY --from=node /app/dist/angular-app /usr/share/nginx/html

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
