### ISSUE TITLE
webpack.3 or webpack.8

### ISSUE THREAD

**Issue by paulogr** [angular/angular-cli#1933]
Wich one is the latest version? Changelog says is webpack.3 but when update my cli it goes to webpack.8

Thanks!

**Comment by manuelxtrem** [comment]
I have similar question.

> Changelog says is webpack.3 but when update my cli it goes to webpack.8

**Comment by aszechlicki** [comment]
webpack.8 is the latest - my guess is that changelog is outdated

**Comment by paulogr** [comment]
Ok, sounds reasonable. Thank you!
