### ISSUE TITLE
Show Module Name on Lazy Chunk Files Build Output

### ISSUE THREAD

**Issue by apiweb** [angular/angular-cli#19345]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
I think it would be interesting if the output of Angular, in the Lazy Chunk Files section, in the Names column, displayed the name of the module corresponding to the file.
That way we would have a clearer output.

### Describe the solution you'd like
![image](https://user-images.githubusercontent.com/5881027/98884765-74886e00-246f-11eb-9b3c-72182f48b24e.png)

**Comment by eneajaho** [comment]
Hello, you can get your lazy chunk file names if you enable **namedChunks** in production configs in **angular.json**
`"namedChunks": true`

**Comment by alan-agius4** [comment]
Thanks for chiming in @eneajaho. Indeed you need to enable `namedChunks`.
