### ISSUE TITLE
Angular 11 ngbuild --prod Font are Bold

### ISSUE THREAD

**Issue by StoRmtec500** [angular/angular-cli#19354]
Hello

I have Update my Project to Angular 11.
When i take an build --prod and i show it in the Browser then are the Fonts all Bold.

Have you an Idea?

Thx

Angular 10
<img width="305" alt="2020-11-12 11_33_34-Aubaun´s PV Übersicht" src="https://user-images.githubusercontent.com/3178395/98930137-805e4980-24dc-11eb-9aee-d17987e3571d.png">

Angular 11
<img width="416" alt="2020-11-12 11_38_46-Aubaun´s PV Übersicht" src="https://user-images.githubusercontent.com/3178395/98930144-818f7680-24dc-11eb-95e3-87a4c2420a6b.png">

**Comment by alan-agius4** [comment]
@StoRmtec500, can you please provide the contents of the index HTML?

**Comment by StoRmtec500** [comment]
Hello

Her is the Code

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <title>Aubaun´s PV Übersicht</title>
  <base href="/" />
  <meta name="viewport"
    content="user-scalable=no, initial-scale=1, minimum-scale=1, maximum-scale=1, width=device-width" />
  <meta name="apple-mobile-web-app-capable" content="yes">
  <link rel="apple-touch-icon" href="assets/logo.png">
  <link href="assets/splashscreens/iphone5_splash.png"
    media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)"
    rel="apple-touch-startup-image" />
  <link href="assets/splashscreens/iphone6_splash.png"
    media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
    rel="apple-touch-startup-image" />
  <link href="assets/splashscreens/iphoneplus_splash.png"
    media="(device-width: 621px) and (device-height: 1104px) and (-webkit-device-pixel-ratio: 3)"
    rel="apple-touch-startup-image" />
  <link href="assets/splashscreens/iphonex_splash.png"
    media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
    rel="apple-touch-startup-image" />
  <link href="assets/splashscreens/ipad_splash.png"
    media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
    rel="apple-touch-startup-image" />
  <link href="assets/splashscreens/ipadpro1_splash.png"
    media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)"
    rel="apple-touch-startup-image" />
  <link href="assets/splashscreens/ipadpro2_splash.png"
    media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)"
    rel="apple-touch-startup-image" />
  <link rel="icon" type="image/x-icon" href="favicon.ico" />
  <link rel="manifest" href="manifest.webmanifest.json">
  <meta name="theme-color" content="#4d4d4d">
  <meta name="theme-title-bar" content="#4d4d4d">
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body style=>
  <pv-root>
    <div style="
      display: inline-block;
      position: fixed;
      color: #000;
      font-size: 14px;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      width: 300px;
      height: 100px;
      margin: auto; text-align: center;
      font-family: 'Roboto Condensed',Roboto,sans-serif;">
      <div class="spinner-border" style="width: 5rem; height: 5rem;">

      </div>
      <br><br><br>
      <span>Aubaun´s PV-Übersicht wird geladen ...</span>
    </div>
  </pv-root>
  <noscript>Please enable JavaScript to continue using this application.</noscript>
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
  integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
  integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
  integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

**Comment by alan-agius4** [comment]
Confirmed the it has the same root cause of  #19350
