### ISSUE TITLE
Development websocket failing with complex build environment

### ISSUE THREAD

**Issue by derekkite** [angular/angular-cli#19365]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: < v11. V11 changed in some way that it doesn't work

### Description

ng serve directly from the source folder serves and the dev websocket connects without issue.

I have a docker image that installs @angular/cli, then is configures in docker-compose:

angular:
    container_name: angular
    build:
      context: .
      dockerfile: Dockerfile.angular
    ports:
      - "4200"
    volumes:
      - .:/usr/src/app
    command: ng serve  --host 0.0.0.0

Then my nginx configuration for  the / path

location / {
        auth_request /oauth2/auth;
      	error_page 401 = /oauth2/sign_in;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_pass http://angular_cli;
    }

http://angular_cli being
 upstream angular_cli {
             server angular:4200;
        }

Which has worked very well up to v11. Now I am getting [WDS] Disconnected! error in the browser console.

Any idea what has changed?

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.0.0
Node: 14.5.0
OS: linux x64

Angular: 11.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.7
@angular-devkit/build-angular      0.1100.0
@angular-devkit/core               11.0.0
@angular-devkit/schematics         11.0.0
@angular/cdk                       10.2.7
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.2.7
@angular/material-moment-adapter   10.2.7
@schematics/angular                10.1.7
@schematics/update                 0.1100.0
rxjs                               6.6.3
typescript                         4.0.3

</code></pre>

**Anything else relevant?**

uname -a
Linux 122a6c848caa 5.9.0-1-amd64 #1 SMP Debian 5.9.1-1 (2020-10-17) x86_64 GNU/Linux

hosted on Debian linux.

**Comment by alan-agius4** [comment]
Are you seeing any requests with a 404 response in your browser console?

**Comment by derekkite** [comment]
No. Everything else works as normal. 

I'm proxying to node servers, they work fine, I have a websocket in my app that is communicating as expected. I'll try running directly off the docker image to see if that works.

**Comment by alan-agius4** [comment]
Thanks for digging into this. Will try to replicate it tomorrow although it might not be trivial to replicate your setup and issue.

If you can create a minimal reproduction it would definitely be helpful even just using Node.JS proxies. Having a reproduction would definitely be helpful to tackle this as quick as possible.

Also can you confirm that you don’t have any addition dev-server related setting in angular.json?

**Comment by derekkite** [comment]
It works on a simple docker serve. 

"serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "triggers:build",
            "proxyConfig": "apps/triggers/proxy.conf.json"
          },
          "configurations": {
            "production": {
              "browserTarget": "triggers:build:production"
            },
            "aot": true,
          }
        },

I'll set up an nginx to ngserve and see. It might be the auth proxy not forwarding something.

**Comment by derekkite** [comment]
I set up a simple nginx configuration and it works fine. It must be the auth proxy.

**Comment by alan-agius4** [comment]
Hi @derekkite, 

I think the problem here might be that the `--public-host` option is not used (More info: https://angular.io/cli/serve
).

Can you please try the below:
```
ng serve --host 0.0.0.0 --public-host http://my-public-host
```


**NB:** `http://my-public-host` is the URL you enter to access the application in your browser including port number is any.

**Comment by alan-agius4** [comment]
Just saw your post on Discord and it does look like you have a 404 request.

Which makes me think that using public-host option should solve the issue you are encountering.

**Comment by derekkite** [comment]
command: ng serve  --host 0.0.0.0 --public-host http://localhost 

This worked. Thanks for the help

**Comment by derekkite** [comment]
It was a configuration issue. Now running
command: ng serve  --host 0.0.0.0 --public-host http://localhost in the docker-compose configuration, and all is well.
