### ISSUE TITLE
Minor: ng update don't update everything (compared with a CLI generated project)

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular-cli#19364]
# 🐞 bug report (minor)

### Description
Everytime I update [my project](https://github.com/DavideViolante/Angular-Full-Stack) using `ng update @angular/core @angular/cli` everything goes fine but the project [is not fully aligned](https://github.com/DavideViolante/Angular-Full-Stack/commit/8902b63c63d4f487ce7527c3a63fc9989c0bdaae) with a new project generated with the Angular CLI.
I'm not sure if this is intended or not, but I'd like to see these files being updated too.
What I do as a workaround is to copy files from a new cli project into my project and check for changes (usually in config files and similar like the commit above).

## 🌍  Your Environment

**Angular Version:** v11 (it's irrelevant, it happens at any upgrade)

**Comment by alan-agius4** [comment]
Hi @DavideViolante,

Thanks for the feedback, while we do our utmost to update existing projects to have the same layout as the new projects however there are some exceptions in this process.

Here's some examples:
- Certain changes such as updating the `.browserslistrc` will cause changes to which browsers the application supports. Hence, it's safer if this file is handcrafted and maintained by the engineers developing the application.

- Changing karma/protractor configuration might result in breaking the current test pipelines. It's likely that users over the time also updated these which might result in the "new" settings not being compatible with their setup.

- Doing any content changes to non TypeScript and JSON file is risky, hence unless absolutely necessary we tend to avoid doing such updates.

- Formatting or other style related changes don't offer any value, hence they are not applied.

**Comment by DavideViolante** [comment]
Thanks for the reply!

Maybe a good thing would be adding to the ng update final output the list of the files changed (very similar to what already happens) since last major release, without actually changing those risky/breaking files, but just telling the user "hey, FYI, those files changed too".

**Comment by alan-agius4** [comment]
Hi, I think in future we should explore "patching" of other file types when we re-design `ng update`, which is in the roadmap.

While listing of files that changed overtime seems trivial, this will incurring a lot of maintenance burden and cost as the list of changed files will need to be updated and up-to-date, which will result in more PR conflicts and so on...

**Comment by alan-agius4** [comment]
@DavideViolante, I am going to close this for the time being, since this is not something that is actionable right now.

Feel free to keep the discussion open.
