### ISSUE TITLE
ng deploy fails after update to 11.0.0

### ISSUE THREAD

**Issue by jasefisher** [angular/angular-cli#19366]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] deploy
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.2.0

### Description

 ng deploy worked correctly to build and deploy directly to firebase before today's version update, and now it fails before building.

## 🔬 Minimal Reproduction
* with Angular CLI 10.20.0, set up an Angular application to utilize the new-ish deploy command
* wire it up to a Firebase hosting account
* verify that it builds and deploys correctly to Firebase Hosting with a simple `ng deploy` command
* update to CLI 11.0.0
* get the following error when running `ng deploy`

## 🔥 Exception or Error
<pre><code>
[error] TypeError: Cannot read property 'Workspace' of undefined
    at c:\node\project\node_modules\@angular\fire\schematics\deploy\builder.js:19:57
    at Generator.next (<anonymous>)
    at c:\node\project\node_modules\@angular\fire\schematics\deploy\builder.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\node\project\node_modules\@angular\fire\schematics\deploy\builder.js:4:12)
    at c:\node\project\node_modules\@angular\fire\schematics\deploy\builder.js:17:67
    at onInput (c:\node\project\node_modules\@angular-devkit\architect\src\create-builder.js:151:30)
    at SafeSubscriber._next (c:\node\project\node_modules\@angular-devkit\architect\src\create-builder.js:65:29)
    at SafeSubscriber.__tryOrUnsub (c:\node\project\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (c:\node\project\node_modules\rxjs\internal\Subscriber.js:143:22)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.0
Node: 14.15.0
OS: win32 x64

Angular: 11.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0
@angular-devkit/build-angular   0.1100.0
@angular-devkit/core            11.0.0
@angular-devkit/schematics      11.0.0
@angular/fire                   6.0.5
@schematics/angular             11.0.0
@schematics/update              0.1100.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the https://github.com/angular/angularfire/issues project or file an issue on their issue tracker.

**Comment by clydin** [comment]
`@angular/fire` 6.1 (currently in release candidate stage) is required when using Angular 11+.  The error shown above was fixed via https://github.com/angular/angularfire/pull/2643
