### ISSUE TITLE
beta.11-webpack.8 visual studio code debug

### ISSUE THREAD

**Issue by tamasfoldi** [angular/angular-cli#1936]
Hi!

I'm trying to debug my angular-cli@beta.11-webpack.8 generated project with [Visual Studio Code Debugger for Chrome](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome) on Windows 7, but I'm not able to hit any breakpoint. The debugger connects to the browser but, does not hit the breakpoint. 
I have found [this solution](https://github.com/AngularClass/angular2-webpack-starter/issues/144#issuecomment-198265242) for webpack but how can I configure it with angular-cli?

Thanks for the replies!

**Comment by santoshsas** [comment]
+1 
Have generated angular 2 project using angular-cli@webpack
Can someone please let know without webpack.conf how do i configure Vscode to debug with chrome extension on windows 10.
@tamasfoldi have u figured it out?

**Comment by tamasfoldi** [comment]
@santoshsas No I was not able to solve it, hope there will be a solution cause it is frustrating a little bit.

**Comment by santoshsas** [comment]
@tamasfoldi yep it is but i believe u can debug in chrome developer tool itself only not in VsCode

**Comment by tamasfoldi** [comment]
Yes I can but finding the correct .ts is not easy. Maybe something with the source map or I don't know but by default chrome gives me the bundles even in development build. I don't think this is the way it should work. Or am I missing something?

**Comment by jzoss** [comment]
+1.. Yes I just discovered this issue as well.

**Comment by ajrauen** [comment]
+1

**Comment by jsmucr** [comment]
+1

**Comment by yuri1969** [comment]
+1

**Comment by gitonworld** [comment]
+1

**Comment by daverupp** [comment]
same issue, I am not able to attach the debugger from visual studio code. Please have a look into it - I would really appreciate to use angular-cli to work with, but without IDE support in breakpoints, it is a little bit cumbersome.

thanks for help

**Comment by tamasfoldi** [comment]
maybe it relates to this @filipesilva  https://github.com/angular/angular-cli/issues/1798 (i hope because that means it is going to be fixed)

**Comment by yuri1969** [comment]
I've just solved this issue after an hour of experimenting. It might be useful for you too: #2453

**Comment by tamasfoldi** [comment]
Thanks it is working! Should I keep it open so they can do with this something or it is not a bug and this is the proper way how we should configure vs code?

**Comment by yuri1969** [comment]
@tamasfoldi The current solution seems a bit hardcodish to me. I'm not sure if changes are required in _angular-cli_ or [vscode-chrome-debug](https://github.com/Microsoft/vscode-chrome-debug) VSCode plugin.

**Comment by tamasfoldi** [comment]
@yuri1969 Ok then I will not close it. Thanks again for your workaround

**Comment by filipesilva** [comment]
I'm going to close this issue in favor of https://github.com/angular/angular-cli/issues/2453 because it contains some more investigation and a couple of solutions.
