### ISSUE TITLE
fileReplacements no longer allow for non js/ts files in Angular 11

### ISSUE THREAD

**Issue by J4cku** [angular/angular-cli#19377]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] build

### Is this a regression?
Worked fine with 10.0.7

### Description
In our angular.json we had section that replaced files:
```
"fileReplacements": [
								{
									"replace": "src/assets/client-config.json",
									"with": "src/environments/client-config.qa.json"
								},
								{
									"replace": "src/environments/environment.ts",
									"with": "src/environments/environment.prod.ts"
								},
								{
									"replace": "src/index.html",
									"with": "src/index.build.html"
								}
							],
```
After update to 11 it does not allow for anything other than .ts/.js files

## 🔬 Minimal Reproduction
As above - just try to replace file different than .ts/.js

## 🔥 Exception or Error
<pre><code>
Schema validation failed with the following errors:
  Data path ".fileReplacements[0]" should NOT have additional properties(replace).
  Data path ".fileReplacements[0].replace" should match pattern "\.([cm]?j|t)sx?$".
  Data path ".fileReplacements[0]" should match exactly one schema in oneOf.
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.1
Node: 12.18.3
OS: darwin x64

Angular: 11.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
ng-packagr                      11.0.2
rxjs                            6.6.3
typescript                      4.0.5
webpack                         4.44.1

</code></pre>

**Comment by alan-agius4** [comment]
Hi @J4cku, this has been the cases since version Angular CLI version 9. Previously however the offending file replacements were silently ignored. In version 11, we now issue an error which is more actionable when we find invalid entries listed in `fileReplacements`.

See https://github.com/angular/angular-cli/issues/16779 for more context.
