### ISSUE TITLE
Angular 11 Web workers build warning "*.worker.ts is part of the TypeScript compilation but it's unused."

### ISSUE THREAD

**Issue by glued** [angular/angular-cli#19372]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/cli ? 

### Is this a regression?

 Yes, the previous version in which this bug was not present was 10

### Description
After upgrading to Angular 11 all of our web workers are reporting this warning.... 
Same issue when generating a new worker via `ng g web-worker foo`
```
Warning: /angular-app/src/app/database/workers/offline-diff.worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

`tsconfig.worker.json` exists in project directory:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/worker",
    "lib": ["es2018", "webworker"],
    "types": []
  },
  "include": ["src/**/*.worker.ts"]
}
```

angular.json points to it
```
 "webWorkerTsConfig": "tsconfig.worker.json"
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.0
Node: 14.5.0
OS: darwin x64

Angular: 11.0.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0
@angular-devkit/build-angular   0.1100.0
@angular-devkit/core            11.0.0
@angular-devkit/schematics      11.0.0
@angular/cdk                    10.2.7
@angular/fire                   6.0.5
@angular/material               10.2.7
@schematics/angular             11.0.0
@schematics/update              0.1100.0
ng-packagr                      11.0.1
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you kindly share you `tsconfig.app.json`?

I was only able to replicate this on application which previously didn't have web-workers.

**Comment by glued** [comment]
tsconfig.app.json
```
{
  "extends": "../tsconfig.json",
  "files": ["main.ts", "polyfills.ts"]
}
```
tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./",
    "declaration": false,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "lib": ["es2020", "dom"],
    "module": "es2020",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "outDir": "./dist/out-tsc",
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceMap": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "target": "es2015",
    "paths": {
      "cd-interfaces": ["dist/cd-interfaces"],
      "cd-definitions": ["dist/cd-definitions"],
      "cd-definitions/*": ["dist/cd-definitions/*"],
      "cd-common": ["dist/cd-common"],
      "cd-common/*": ["dist/cd-common/*"],
      "cd-metadata": ["dist/cd-metadata"],
      "cd-metadata/*": ["dist/cd-metadata/*"],
      "cd-themes": ["dist/cd-themes"],
      "cd-themes/*": ["dist/cd-themes/*"],
      "cd-utils": ["dist/cd-utils"],
      "cd-utils/*": ["dist/cd-utils/*"]
    }
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictAttributeTypes": true,
    "strictContextGenerics": true,
    "strictDomEventTypes": true,
    "strictDomLocalRefTypes": true,
    "strictInjectionParameters": true,
    "strictLiteralTypes": true,
    "strictNullInputTypes": true,
    "strictInputTypes": false,
    "strictSafeNavigationTypes": false
  },
  "exclude": [
    "lib/**"
  ]
}
```

**Comment by alan-agius4** [comment]
It looks like you don't exclude worker files from the application tsconfig.json.

Adding the exclude should solve the issue.
```json
{
  "extends": "../tsconfig.json",
  "files": ["main.ts", "polyfills.ts"],
  "exclude": ["**/*.worker.ts"]
}
```

**Comment by glued** [comment]
still seeing warnings

**Comment by alan-agius4** [comment]
@glued, in that case we'd need a reproduction to investigate this issue further.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
