### ISSUE TITLE
Lazy loading modules from Angular library does not work correctly

### ISSUE THREAD

**Issue by jonathanlie** [angular/angular-cli#19370]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Before Ivy (v8), the components are included in the lazy loaded chunks.

### Description
Lazy loading does not work with feature modules exported from the same library project. Any additions to the feature module result in increase in main.js bundle size, instead of the lazy loaded feature module.

## 🔬 Minimal Reproduction

Clone this repo: https://github.com/jonathanlie/repro-lazy-loading-issue

1. `npm install`
2. Run `ng build some-lib --watch` on a tab
3. Run `ng serve some-app` on a separate tab after
4. Verify app is working on `localhost:4200`
5. Remove / add content to `listing.component.scss` in `projects/some-lib/src/lib/lazy/components/listing/listing.component.scss`, and what happens is that the main.js bundle size is the one reduced instead.

```
Build at: 2020-11-13T06:22:30.373Z - Hash: c12a866456896e242a74 - Time: 2012ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names |     Size
main.js             | main  | 16.81 kB

5 unchanged chunks

Build at: 2020-11-13T06:22:39.887Z - Hash: a02cce926638fc0cef6b - Time: 151ms

✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names |     Size
main.js             | main  | 17.19 kB
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.1
Node: 12.14.0
OS: darwin x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
ng-packagr                      11.0.2
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by alan-agius4** [comment]
Same root cause of https://github.com/angular/angular-cli/issues/13635

**Comment by jonathanlie** [comment]
apologies, could you direct me to a specific comment on the issue?

**Comment by alan-agius4** [comment]
https://github.com/angular/angular-cli/issues/13635#issuecomment-462358854
