### ISSUE TITLE
Module blueprint do not generate routes file.

### ISSUE THREAD

**Issue by paulogr** [angular/angular-cli#1939]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

`OSX El Capitan`

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64
v6.5.0
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

`Just created using angular-cli webpack.8`

4. The log given by the failure. Normally this include a stack trace and some
   more information.

`No logs`

5. Mention any other details that might be useful.

When using the new blueprint to create a module, the file `<name>.routes.ts` aren't generated.

I don't know if it was intentional or not, but that is it.

Thank you!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
@paulogr I imagine this is intentional since when you are creating a new module you are not necessarily defining new routes, just components and the like. Think of a Utils module for example.

**Comment by paulogr** [comment]
Make sense, but there is an import inside module file that points to the missing routes file.

**Comment by deebloo** [comment]
@paulogr oh I see! I just tried it out and can confirm. This is certainly a bug.

**Comment by filipesilva** [comment]
Fixed on master currently.
