### ISSUE TITLE
Angular.json's fileReplacements no longer accept .html replacements in Angular 11

### ISSUE THREAD

**Issue by ChristopherHoffman** [angular/angular-cli#19390]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/cli: "~11.0.1",

### Is this a regression?

Yes, the previous version in which this bug was not present was "@angular/cli": "^10.2.0",

### Description

Angular 11's `angular.json` no longer allows fileReplacements with .html files, as the @angular/cli schema says .html files are invalid. `ng build --prod` also errors when trying to run with html in fileReplacements

angular.json
```
...
      "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                },
                {
                  "replace": "src/index.html",
                  "with": "src/index.prod.html"
                }
              ],
...
```

Running `ng build --prod` exits with error:
```
> ng build --prod

Schema validation failed with the following errors:
  Data path ".fileReplacements[1]" should NOT have additional properties(replace).
  Data path ".fileReplacements[1].replace" should match pattern "\.([cm]?j|t)sx?$".
  Data path ".fileReplacements[1]" should match exactly one schema in oneOf.
```

vscode also gives a linting warning with `String does not match the pattern of "\.([cm]?j|t)sx?$".` for the two .html lines.

### Expectation
Expect that `.html` fileReplacements replacements are allowed, since it is useful to have different meta tags and other analytics scripts stored in the `index.html` file for different build configurations.

## 🔬 Minimal Reproduction
Example repo here: https://github.com/ChristopherHoffman/Angular11-Html-File-Replacement-Broken/tags

Tag "Working" is a fresh app using the Angular 10 cli, with just a `index.prod.html` to the angular.json's production configuration. `ng build --prod` works as expected. 

Tag "Broken" is just after updating to Angular 11, and `ng build --prod` no longer works because of that `.html`.

## 🔥 Exception or Error
<pre><code>
> ng build --prod

Schema validation failed with the following errors:
  Data path ".fileReplacements[1]" should NOT have additional properties(replace).
  Data path ".fileReplacements[1].replace" should match pattern "\.([cm]?j|t)sx?$".
  Data path ".fileReplacements[1]" should match exactly one schema in oneOf.

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.1
Node: 14.5.0
OS: win32 x64

Angular: 11.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by alan-agius4** [comment]
Hi @ChristopherHoffman, this has been the cases since version Angular CLI version 9. Previously however the offending file replacements were silently ignored. In version 11, we now issue an error which is more actionable when we find invalid entries listed in fileReplacements.

See #16779 and #16439 for more context.

**Comment by dougamos** [comment]
Is there a workaround to achieve the above use case? ie. " to have different meta tags and other analytics scripts stored in the index.html file for different build configurations."

We do something similar and cannot upgrade to angular 11 because of this restriction.

**Comment by alan-agius4** [comment]
@dougamos, file replacements on html didn't work since Angular version 9.

To correctly replace an HTML, you can use the `index` option. See https://github.com/angular/angular-cli/issues/14599#issuecomment-527131237 for an example.

**Comment by chumbalum** [comment]
> @dougamos, file replacements on html didn't work since Angular version 9.

I use fileReplacements for several HTML files with angular 10.2.0 currently, which does work. This change prevents me from updating.

Is there another way to exchange template Files for components?

**Comment by Gayashani95** [comment]
Has anyone found a solution for above issue? Even I'm using fileReplacements for several HTML files to override some functionalities in sub projects,, Due to this restriction, I couldn't update my project to Angular 11 yet. 
Hence, If someone suggests a solution for that, it'd be a big help for me at this moment :(

**Comment by PhilippMeissner** [comment]
> Has anyone found a solution for above issue? Even I'm using fileReplacements for several HTML files to override some functionalities in sub projects,, Due to this restriction, I couldn't update my project to Angular 11 yet.
> Hence, If someone suggests a solution for that, it'd be a big help for me at this moment :(

Yes, you can try what @alan-agius4 suggested - This worked just fine for me.

**Comment by Lexa950609** [comment]
> > Has anyone found a solution for above issue? Even I'm using fileReplacements for several HTML files to override some functionalities in sub projects,, Due to this restriction, I couldn't update my project to Angular 11 yet.
> > Hence, If someone suggests a solution for that, it'd be a big help for me at this moment :(
> 
> Yes, you can try what @alan-agius4 suggested - This worked just fine for me.

"index" option only works for replacing index.html isn't it??

**Comment by PhilippMeissner** [comment]
> > > Has anyone found a solution for above issue? Even I'm using fileReplacements for several HTML files to override some functionalities in sub projects,, Due to this restriction, I couldn't update my project to Angular 11 yet.
> > > Hence, If someone suggests a solution for that, it'd be a big help for me at this moment :(
> > 
> > 
> > Yes, you can try what @alan-agius4 suggested - This worked just fine for me.
> 
> "index" option only works for replacing index.html isn't it??

Ah yes, you are right. Sorry, my bad :/
Couldn't you switch to a custom script that does the heavy lifting maybe?
