### ISSUE TITLE
Angular 11: Live reload not working behind reverse proxy

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#19406]
# 🐞 Bug report

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes. Live reload worked behind a reverse proxy in Angular v10

### Description

Live reload is not working for Angular 11 apps when served behind reverse-proxy

## 🔬 Minimal Reproduction
- git clone https://github.com/prabh-62/angular-reverse-proxy
- Run the proxy and angular web apps as per the Readme
- Navigate to [https://localhost/support](https://localhost/support). You will notice errors in Chrome DevTools - **Console** tab 

## 🔥 Exception or Error
<pre><code>
zone-evergreen.js:2845 GET https://localhost:4202/admin/sockjs-node/info?t=1605577113479 net::ERR_SSL_PROTOCOL_ERROR
</code></pre>
<img width="681" alt="angular_11_proxy_error_ssl" src="https://user-images.githubusercontent.com/13006107/99329508-65793580-284c-11eb-940d-919e844229b9.png">

## 🌍 Your Environment
<pre><code>
$ ng version
Angular CLI: 11.0.1
Node: 15.2.0
OS: darwin x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This shares the same root cause of https://github.com/angular/angular-cli/issues/19403. 

Let's continue tracking this there.

Thanks.
