### ISSUE TITLE
Inlining fonts behind HTTP proxy

### ISSUE THREAD

**Issue by Eddman** [angular/angular-cli#19401]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
Since 11.0.0 there is the new feature to inline fonts. The problem is that it does not work behind HTTP proxy. We have correctly set `HTTP_PROXY`/`http_proxy` and `NO_PROXY`/`no_proxy` environment variables, but it is ignored.

## 🔬 Minimal Reproduction
There is no support for proxy: https://github.com/angular/angular-cli/blob/871dd6a434fdd9674905bde307b5ad79d5d59603/packages/angular_devkit/build_angular/src/utils/index-file/inline-fonts.ts#L107

There is not really a reproduction scenario. It fails only when running behind HTTP proxy.

## 🔥 Exception or Error
<pre><code>
✖ Index html generation failed.
Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/icon?family=Material+Icons over the internet.
connect ETIMEDOUT 172.217.16.202:443

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.1
Node: 14.15.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.1 (cli-only)
@angular-devkit/core         11.0.1 (cli-only)
@angular-devkit/schematics   11.0.1 (cli-only)
@schematics/angular          11.0.1 (cli-only)
@schematics/update           0.1100.1 (cli-only)

</code></pre>

**Anything else relevant?**

**Comment by michaelfaith** [comment]
This is affecting me as well.  Our build servers don't have access outside our firewalls.  Is there a way to disable inline fonts?

**Comment by alan-agius4** [comment]
On how to disable it, see https://angular.io/guide/workspace-config#optimization-and-source-map-configuration

**Comment by nico151999** [comment]
Had the same issue behind a corporate proxy. Thought of using an index.html referencing the google fonts in dev config and replacing the index.html with a prod version referencing a local copy of the fonts that would be made in the build procedure of my docker image in my pipeline. However, this would have required additional scripting for the woff2 files referenced in the css files. I ended up using [fontsource](https://github.com/fontsource). This way `ng build` does not need to reach fonts.googleapis.com.

**Comment by michaelfaith** [comment]
> Had the same issue behind a corporate proxy. Thought of using an index.html referencing the google fonts in dev config and replacing the index.html with a prod version referencing a local copy of the fonts that would be made in the build procedure of my docker image in my pipeline. However, this would have required additional scripting for the woff2 files referenced in the css files. I ended up using [fontsource](https://github.com/fontsource). This way `ng build` does not need to reach fonts.googleapis.com.

Why not just disable font optimization?

**Comment by austi10** [comment]
I am facing the same problem. While changing the font optimization under angular.json for production from
`"optimization" : true`
to
```
"optimization": {
    "font": false
}
```
gives me schema validation failed error.

The suggestion in the link: https://angular.io/guide/workspace-config#optimization-and-source-map-configuration
does not work and seems to have not been updated.

Is there any fix for this problem ?

**Comment by austi10** [comment]
If I set **ONLY** fonts optimization to false
```
"optimization": {
    "fonts": false
}  
```
are **_scripts_** and **_styles_** property set to false or are they still true by default ? 

I am not able to find any info on this. Could someone help ?

**Comment by alan-agius4** [comment]
@austi10,

They are `true`, by default. See https://angular.io/guide/workspace-config#optimization-configuration

**Comment by michaelfaith** [comment]
Yeah, if you think about the code behind that property, the type is likely a simple boolean or some optimization option interface.  Defining it as a simple boolean is the equivalent of setting it with an option that has all properties as true.  So if you want to just turn off one, provide an object that has all true, but the one(s) you want turned off as false.  Seems pretty straightforward.

**Comment by alexaka1** [comment]
This is the new error I get with the patch. I have tried with hardcoding my proxy credentials into %HTTP_PROXY% too, but still no luck.

```console
× Index html generation failed.
Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap over the internet.
Socket is closed
```

🌍 Your Environment
```console
Angular CLI: 11.1.2
Node: 14.15.1
OS: win32 x64

Angular: 11.1.1
...
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.0.5
```

**Comment by alan-agius4** [comment]
@alexaka1, are you using a rotating proxy?, If so, can you try using Node.js 12?
Note: only the `HTTPS_PROXY` environment variable.

**Comment by alexaka1** [comment]
@alan-agius4 No we don't have rotating proxy, but still I have installed nvm4w, and got Node 12.20.1 installed, and building with that no cmd error is given, however, the final `index.html` doesn't have the font css, instead it has this inside `<style type="text/css">` tag. (I have formatted it for readability.)

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <!-- FileName:index.html     Language:[en]--><!--Head--><head>
    <meta content="text/html;charset=UTF-8" http-equiv="Content-Type" />
    <meta http-equiv="X-UA-Compatible" content="IE=7" />
    <title>McAfee Web Gateway - Notification</title>
    <script
      src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js"
      type="text/javascript"
    ></script>
    <link
      rel="stylesheet"
      href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css"
    /></head
  ><!--/Head--><!--Body-->
  <body onload="swOnLoad();">
    <table class="bodyTable">
      <tr>
        <td
          class="bodyData"
          background="/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif"
        >
          <!--Logo-->
          <table class="logoTable">
            <tr>
              <td class="logoData">
                <a href="http://www.mcafee.com">
                  <img
                    src="/mwg-internal/de5fs23hu73ds/files/default/img/logo_mwg.png"
                /></a>
              </td>
            </tr>
          </table>
          <!--/Logo--><!--Contents--><!-- FileName:authenticationrequired.html     Language:[en]--><!--Title-->
          <table
            class="titleTable"
            background="/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg"
          >
            <tr>
              <td class="titleData">Authentication Required</td>
            </tr>
          </table>
          <!--/Title--><!--Content-->
          <table class="contentTable">
            <tr>
              <td class="contentData">
                You must be authenticated to access this URL.
              </td>
            </tr>
          </table>
          <script language="javascript" type="text/javascript">
            urlprotocol = "https";
            statuscode = 407;
            if (statuscode == 401 && urlprotocol == "ftp") {
              document.write('<form name="ftpform" method="get" action="">');
              document.write('<table class="contentData">');
              document.write(
                '<tr><td class="contentData" colspan=2>Please enter your credentials in the form below and click "Access FTP" button if your browser doesn\'t present authentication promt for FTP sites.</td></tr>'
              );
              document.write(
                '<tr><td class="contentData">Username:</td><td><input type="text" id="ftpUsername" name="ftpUsername" size=40 /></td></tr>'
              );
              document.write(
                '<tr><td class="contentData">Password:</td><td><input type="password" id="ftpPassword" name="ftpPassword" size=40 /></td></tr>'
              );
              document.write(
                '<tr><td class="contentData" colspan=2 align=center><input type="button" onclick="redirectToFTP();" value="Access FTP" /></td></tr>'
              );
              document.write("</table>");
              document.write("</form>");
            }
            function redirectToFTP() {
              var username = escape(
                document.getElementById("ftpUsername").value
              );
              var password = escape(
                document.getElementById("ftpPassword").value
              );
              location.href =
                "ftp://" +
                username +
                ":" +
                password +
                "@fonts.googleapis.com:443";
            }
          </script>
          <!--/Content--><!--Info-->
          <table class="infoTable">
            <tr>
              <td class="infoData">
                <b>URL:</b>
                <script type="text/javascript">
                  break_line("https://fonts.googleapis.com");
                </script>
                <br />
              </td>
            </tr>
          </table>
          <!--/Info--><!--/Contents--><!--Policy-->
          <table class="policyTable">
            <tr>
              <td class="policyHeading">
                <hr />
                Company Acceptable Use Policy
              </td>
            </tr>
            <tr>
              <td class="policyData"></td>
            </tr>
          </table>
          <!--/Policy--><!--Foot-->
          <table class="footTable">
            <tr>
              <td
                class="helpDeskData"
                background="/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg"
              >
                For assistance, please contact your system administrator.
              </td>
            </tr>
            <tr>
              <td class="footData">
                generated <span id="time">2021-02-01 15:52:39</span> by
                webgateway1 <br />
                <br />
                #Authentication with Kerberos and NTLM Fallback / Perform
                Authentication
              </td>
            </tr>
          </table>
          <!--/Foot-->
        </td>
      </tr>
    </table>
  </body>
  <!--/Body-->
</html>
```

**Comment by alan-agius4** [comment]
@alexaka1, it appears that the authentication is failing, are you providing the credentials as part of the proxy uri specified in `HTTPS_PROXY`?

From the HTML page above, it appears that the proxy returned a 407, which indicates that proxy authentication is required. 

I have a fix, so that such errors thrown in the terminal.

**Comment by alexaka1** [comment]
@alan-agius4 Yes I have tried providing credentials in `HTTPS_PROXY` variable, with the `http://username:pwd@proxydns:port` format. I have also tried using the IP address instead of the dns name, but that shouldn't make a difference, I don't think at least. 
However we're in a domain (AD), and my password contains special characters. I have read elsewhere that if I were to provide this to say npm, I would need to url-encode it. Do I have to do that here? Also do I include the domain too? Like `http://domain\username:pwd@proxydns:port`, or do I escape the backslash with another so `http://domain\\username:pwd@proxydns:port`, or do I use the url-encoded `%5C`? Also our proxy is only http, not https, not sure, if this matters.

**Comment by alan-agius4** [comment]
HTTPS over HTTP proxy shouldn't be a problem at all. That is a common case. If you are using AD, you do need to provide the domain name of the authentication server, in the following format.

```
https_proxy=http://DOMAIN\\USERNAME:PASSWORD@SERVER:PORT
```

If you do have special characters in your password, indeed most likely you do need to use encoding, both HEX or URL encode should do the trick.

**Comment by alexaka1** [comment]
@alan-agius4 I have tried the above, and I get strange behaviour. When I add a domain, even npm breaks, and it can't reach the registry. ng build gives this error:

```console
× Index html generation failed.
Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap over the internet.
getaddrinfo ENOTFOUND mydomain
```
`mydomain` is the domain I give, and it's always in lowercase here, regardless of the env variable casing. I thought maybe the domain is case sensitive, but doesn't seem to make a difference.

If I don't add a domain, but change my password to a wrong one, then npm works fine.

**Comment by alan-agius4** [comment]
- `ENOTFOUND` error typically indicates that the `mydomain` cannot be found in the host. 
- `ECONNREFUSED` indicates that the connection was refused by the server. Typically reasons for this error are; wrong IP address or port number or a firewall is blocking the connection.

**Comment by alexaka1** [comment]
@alan-agius4 I ended up using [@fontsource](https://github.com/fontsource/fontsource) too to host the fonts locally.
Thx for the help btw!
