### ISSUE TITLE
ng g c generates a test file using async instead of waitForAsync

### ISSUE THREAD

**Issue by Yohandah** [angular/angular-cli#19427]
### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

no

### Description

`async` was deprecated replaced by `waitForAsync` but `ng generate component` uses async instead of waitForAsync

## 🔬 Minimal Reproduction
* ng g c MyComponent
* open the spec file

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.1
Node: 12.13.1
OS: win32 x64

Angular: 11.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.801.3
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@angular/pwa                    0.901.12
@schematics/angular             9.1.12
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

Yes I actually have a question, why does it generates a test file that is like this :

```
beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [ MyComponent ],
      imports: [IonicModule.forRoot()]
    }).compileComponents();

    fixture = TestBed.createComponent(YohanComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  }));
```

When the docs (https://angular.io/guide/testing-components-scenarios#calling-compilecomponents) specifies you should do this (wrap into a then) :

```
beforeEach(waitForAsync(() => {
  TestBed
      .configureTestingModule({
        declarations: [BannerComponent],
      })
      .compileComponents()
      .then(() => {
        fixture = TestBed.createComponent(BannerComponent);
        component = fixture.componentInstance;
      });
}));
```

**Comment by alan-agius4** [comment]
The async keyword there is the JavaScript native `async` and is not to be confused with the deprecated `async` Angular helper.

**Comment by Yohandah** [comment]
@alan-agius4 no it does generate the test file with the async helper !

![Sans titre](https://user-images.githubusercontent.com/15921402/99555909-23bdcb80-29c1-11eb-8f0a-4c9d1f517591.png)

**Comment by alan-agius4** [comment]
Looks like some of your workspace dependencies are miss aligned and outdated.

```
@schematics/angular             9.1.12
@angular-devkit/architect       0.801.3
@angular/pwa                    0.901.12
```

The root cause of the above is that either you are directly depending on the above packages when you shouldn’t of a 3rd party dependency is causing this behaviour.

**Comment by Yohandah** [comment]
Indeed. Thanks for pointing that out. I will close this issue and try to figure that out.

I do have the following in my package.json ... 
```
"@angular-devkit/architect": "~0.801.2",
    "@angular-devkit/build-angular": "~0.1100.1",
    "@angular-devkit/core": "~11.0.1",
    "@angular-devkit/schematics": "~11.0.1",
```

**Comment by alan-agius4** [comment]
Typically only `@angular-devkit/build-angular` should be added as a dependency.

That is unless you are developing custom builders and schematics.

**Comment by Yohandah** [comment]
@alan-agius4 

I use this in angular.json because otherwise it generates using simple quotes while my project uses double quotes.

```
"schematics": {
    "@ionic/angular-toolkit:component": {
      "prefix": "app",
      "styleext": "scss",
      "lintFix": true
    },
    "@ionic/angular-toolkit:page": {
      "styleext": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "app",
      "lintFix": true
    },
    "@schematics/angular:pipe": {
      "lintFix": true
    },
    "@schematics/angular:class": {
      "lintFix": true
    },
    "@schematics/angular:module": {
      "lintFix": true
    },
    "@schematics/angular:service": {
      "lintFix": true
    }
  }
```

I'm going to try and look why my project uses schematics v9 even if it's specified to 11.0 in my package.json
