### ISSUE TITLE
Dead code not eliminated in vendor.js during production build

### ISSUE THREAD

**Issue by afriedma** [angular/angular-cli#19428]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Don't know
### Description

 A clear and concise description of the problem...
I am building an Angular 10 PWA application.  I am running it through the lighthouse to get a high Performance score.
My current issue is that vendor.js has a ton of dead code, even though I am applying all the available optimizations.

I am attaching 2 screen shots.

![image](https://user-images.githubusercontent.com/22999195/99576597-2fe95f00-29a8-11eb-82b0-10dd96943a56.png)

![image](https://user-images.githubusercontent.com/22999195/99576755-61622a80-29a8-11eb-8d71-695da24b5870.png)

## 🔬 Minimal Reproduction

Add pwa, material, firebase, fire latest packages
ng build --prod

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": true,
              "extractCss": true,
              "namedChunks": true,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": true,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ],
              "serviceWorker": true,
              "ngswConfigPath": "ngsw-config.json"
            }
          }

  "dependencies": {
    "@angular/animations": "~10.2.0",
    "@angular/cdk": "^10.2.5",
    "@angular/common": "~10.2.0",
    "@angular/compiler": "~10.2.0",
    "@angular/core": "~10.2.0",
    "@angular/fire": "^6.1.0",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "~10.2.0",
    "@angular/material": "^10.2.5",
    "@angular/platform-browser": "~10.2.0",
    "@angular/platform-browser-dynamic": "~10.2.0",
    "@angular/router": "~10.2.0",
    "@angular/service-worker": "~10.2.0",
    "firebase": "^8.0.2",
    "ng-navigator-share": "^1.0.4",
    "ngx-bottom-nav": "^0.5.0",
    "pwacompat": "^2.0.17",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": ">= 0.900 < 0.1100",
    "@angular-devkit/build-angular": "~0.1002.0",
    "@angular-devkit/build-optimizer": "^0.1100.1",
    "@angular/cli": "~10.2.0",
    "@angular/compiler-cli": "~10.2.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "colors": "^1.4.0",
    "dotenv": "^8.2.0",
    "firebase-tools": "^8.0.0",
    "fuzzy": "^0.1.3",
    "gulp": "^4.0.2",
    "gulp-load-plugins": "^2.0.5",
    "gulp-purifycss": "^0.2.0",
    "gulp-responsive": "^3.0.1",
    "gzipper": "^4.3.0",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "open": "^7.0.3",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @afriedma, 

`vendorChunk` is not recommended for production environments this will cause all vendor packages to be included in the same chunk, which causes a number de-optimizations and also causes bad performance because all of the vendor packages will need to be used downloaded and parsed at startup even when used in a lazy route.

The `Unused JavaScript` matrix doesn't indicate deadcode, it highlights that there is a considerable amount of unused JavaScript for the visited route. It is inevitable that some subset of JavaScript will be unused when use a vendor library. This matrix in no way impacts the Lighthouse score (https://web.dev/performance-scoring/?utm_source=lighthouse&utm_medium=devtools), although it does provide information to improve performance. 

From dead-code side, It is also important to point out, that unused members of a used class are not removed.

Example
```js
class Foo {
  bar() {}
  buz() {}
}

new Foo().bar();
```
The `buz` member will still be present in the bundle, as [terser](https://github.com/terser/terser) is unable to remove these.

**Comment by afriedma** [comment]
Hi @alan-agius4 ,

Thank you so much for reply.  I rebuild and re-deployed with vendorChunk set to false, but cannot get the audit past 64.  Any further recommendations, would be very mu appretiated.

![image](https://user-images.githubusercontent.com/22999195/99685273-67134b00-2a50-11eb-847b-590da3012069.png)

**Comment by alan-agius4** [comment]
This also depends on your application.

You think you might want to consider are;
- lazy loading
- web workers
- app shell

**Comment by afriedma** [comment]
Thank you, I will investigate.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
