### ISSUE TITLE
Empty directories in assets are not copied when packaging application

### ISSUE THREAD

**Issue by FlorentP42** [angular/angular-cli#19425]
### Command (mark with an `x`)

- [x] build

### Is this a regression?

Probably never worked.

### Description

I am using the builder option to embed some assets inside my application:
```
"architect": {
	"build": {
		"options": {
			"outputPath": "dist",
			"assets": [
				"src/favicon.ico",
				"src/assets"
			]
		}
	}
}
```

This was working flawlessly to copy all the file and folder hierarchy of `src/assets` into `dist` until I needed to add an empty sub-directory to the assets: `src/assets/EmptyDir`. Now everything else in `src/assets` is still copied properly, but `src/assets/EmptyDir` is not.

I need this empty directory to be embedded in the application as well and I couldn't find a syntax to make it work so far, even adding the path to the exmpty folder explicitly didn't work, it is still ignored:
```
"options": {
	"outputPath": "dist",
	"assets": [
		"src/favicon.ico",
		"src/assets",
                "src/assets/EmptyDir"
	]
}
```

## 🔬 Minimal Reproduction

- Make a project with an empty directory in `src/assets/EmptyDir` and the build configuration above.
- Run `ng build --prod`
- Notice that `EmptyDir` is not copied in `dist`.

## 🔥 Exception or Error

No error that I could see.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.26
Node: 12.3.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.26
@angular-devkit/build-angular      0.803.26
@angular-devkit/build-ng-packagr   0.803.28
@angular-devkit/build-optimizer    0.803.26
@angular-devkit/build-webpack      0.803.26
@angular-devkit/core               8.3.26
@angular-devkit/schematics         8.3.26
@angular/cli                       8.3.26
@ngtools/webpack                   8.3.26
@schematics/angular                8.3.26
@schematics/update                 0.803.26
ng-packagr                         5.7.1
rxjs                               6.5.5
typescript                         3.5.3
webpack                            4.39.2
</code></pre>

**Anything else relevant?**

A few things I am wondering:
1. Is this normal bahavior? (to ignore empty folders).
2. Is there a way to prevent it from being ignored?
3. If this is intended behavior and there is no way to prevent it, could at least an option be added to change that behavior?

So far my workaround is to add a dummy file `src/assets/EmptyDir/Dummy.txt` to force it to copy the directory, but this is not a satisfying solution.

**Comment by alan-agius4** [comment]
Hi @FlorentP42, Thanks for this report. 

This is working as intended. This also ensures that the behaviour is consistent between `ng build` and `ng serve`. Where the underlying dev-server and bundler used for `ng serve` cannot have empty directories.

Hence, if you want to create an empty directory the best options would be to create a dummy file in the "empty directory" or create the empty directory via a Shell script post build.

Related issue https://github.com/webpack-contrib/copy-webpack-plugin/issues/101
