### ISSUE TITLE
CLI output in dev mode contains duplicate sections in some cases

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular-cli#19429]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] serve

### Is this a regression?

No

### Description

I’ve created an app using CLI and when I run `ng serve` I see that some sections are present twice and the browser URL link is in between these two sections, see below:

```
$ ng serve
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.69 MB
polyfills.js        | polyfills     | 127.62 kB
main.js             | main          |  11.04 kB
runtime.js          | runtime       |   6.15 kB
styles.css          | styles        | 119 bytes

                    | Initial Total |   2.83 MB

Build at: 2020-11-19T02:23:46.612Z - Hash: 9fb7ec77fd4e6c1c2a59 - Time: 5175ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
✔ Browser application bundle generation complete.

Initial Chunk Files | Names  |      Size
styles.css          | styles | 119 bytes

4 unchanged chunks

Build at: 2020-11-19T02:23:47.083Z - Hash: 5caf5f7e7e9c85a1f24a - Time: 208ms

✔ Compiled successfully.
```

The "Browser application bundle generation complete." and "Compiled successfully." are also present twice.

If both build operations are needed, I think it'd be great to group them and provide more info on each one and have the "Angular Live Development Server is listening on localhost:4200..." message underneath it.

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.1
Node: 12.14.1
OS: darwin x64

Angular: 11.0.0
... animations, common, compiler, compiler-cli, core
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@angular/forms                  11.0.1
@angular/language-service       7.0.4
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by AndrewKushnir** [comment]
Quick update: the problem seems to happen only when packages are re-compiled, i.e. here is what I did to reproduce it:
- change a version of any package (I tested with forms) in `package.json`
- run `yarn`
- run `ng serve`

After that if I just run `ng serve`, everything works as expected (no second build action).

**Comment by alan-agius4** [comment]
Hi @AndrewKushnir,

Thanks for opening this issue and looking at this. 

The problem here is that when running NGCC, NGCC will change the "input" during mid-build, this will cause a partial re-compilation right after the 1st build is finished. Therefore, these are not duplicate but rather logs of the 1st build and the 2nd incremental build.

NGCC integration in the CLI is far not optimal and unfortunately there is no much we can do here to action this issue.

**Comment by alan-agius4** [comment]
Closing as per above, feel free to continue the discussion.

**Comment by AndrewKushnir** [comment]
Ok, thanks for the reply @alan-agius4.
