### ISSUE TITLE
Revive ng update all.

### ISSUE THREAD

**Issue by infacto** [angular/angular-cli#19431]
# 🚀 Feature request

### Command
- [x] update

### Description

Following the [docs](https://angular.io/cli/update), the command flag `--all` is **deprecated**. But why? 

### Describe the solution you'd like
I don't want to upgrade every single package. I created the app with one command and I want to update with one command.
`ng update --all` should update **all Angular packages** (only).  

### Describe alternatives you've considered
I don't know how `--all` works before. I just expected such command. I'm currently on `v11-next` and want to update the whole Angular deps to the stable `v11`. The CLI could collect all Angular scoped packages and ask for a batch of update all packages.

**Comment by alan-agius4** [comment]
Hi @infacto,

Thanks for the feedback. 

`--all` was removed following in depth discussions with the entire tooling team. Updating multiple packages at once was something that we always advise against. 

The `all` functionality also provided far from optimal experience which in many cases caused confusion, undefined behaviour and version mismatches errors. All in all, the chance of success of using `--all` without `--force` was pretty slim.

If you really want to update multiple packages at once which you can provide the package names as addition positional arguments when running `ng update`.

Ex:
```cmd
ng update @angular/core @ngrx/store @angular/fire
```

To update `@angular` only packages, you can run:
```cmd
ng update @angular/cli @angular/core @angular/material
```

Seeing that the desired functionality is trivial to do, `ng update` is not used that frequently and it can also be achieved using a terminal alias. I don't see any reason why an additional option should be included. In addition to that explicitly listing the packages you want to update seems like a reasonable thing to do.

Thanks.
