### ISSUE TITLE
Template error causes diagnostic failure on re-compilation after error is fixed

### ISSUE THREAD

**Issue by JumBay** [angular/angular-cli#19432]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: I guess Angular 9

### Description

If you do a mistake in your code, here by not closing a html element with its right closing tag, you'll get the error `NG0303: Can't bind to 'XXXX' since it isn't a known property of YYYYYY`

## 🔬 Minimal Reproduction

1. Start a new Angular project or clone mine: https://github.com/JumBay/angularNG0303
2. Start the server `npm start`
3. Navigate to http://localhost:4200, everything works fine 
4. Do a mistake in your code, ie in `app.component.ts` replace `<h2>Resources</h2>` by `<h1>Resources</h2>`
5. On your browser you get an error `Angular JIT compilation failed` which is normal
6. Fix the error, replace `<h1>Resources</h2>` by `<h2>Resources</h2>`
7. Now on your browser you have new error `NG0303: Can't bind to 'XXXX' since it isn't a known property of YYYYYY` and the app is broken even if there is no more issue in your code. If you restart the server you'll see there is no issue and now the app works again.

Here you can see the error in video https://www.youtube.com/watch?v=UkoUEAWNWhM

## 🔥 Exception or Error
<pre><code>NG0303: Can't bind to 'XXXX' since it isn't a known property of YYYYYY
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 11.0.2
Node: 12.16.2
OS: darwin x64

Angular: 11.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cli                    11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This issue is pretty similar to #18707. The problem here is that when a HTML template is updated, we are not deleting the component TypeScript source file from the cache.

Note: This also effects the Ivy plugin.

**Comment by alan-agius4** [comment]
So @JoostK highlighted that this is a compiler bug which is being tracked here https://github.com/angular/angular/issues/39147
