### ISSUE TITLE
Doesn´t recognize the class when there's a template error

### ISSUE THREAD

**Issue by danielc1015** [angular/angular-cli#19433]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When i have a template error, the compiler says that the component class is listed in the declarations of the NgModule, but is not a directive, a component, or a pipe.

To solve it, before i realized the error was mine, i had to save again the component class (.ts), and when it recompiled, it compiled correctly. If i didn't do that, still throw a compiling error.

## 🔬 Minimal Reproduction
The error i had in the template was the next:

`<p>{{ meeting.name ' - ' }}</p>` (missing concatenator)

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.module.ts:16:5 - error NG6001: The class 'ReunionListaComponent' is listed in the declarations of the NgModule 'AppModule', but is not a directive, a component, or a pipe. Either remove it from the NgModule's declarations, or add an appropriate Angular decorator.
    
    16     ReunionListaComponent,
           ~~~~~~~~~~~~~~~~~~~~~
    
      src/app/reunion/reunion-lista/reunion-lista.component.ts:10:14
        10 export class ReunionListaComponent implements OnInit {
                        ~~~~~~~~~~~~~~~~~~~~~
        'ReunionListaComponent' is declared here.

</code></pre>
<img width="565" alt="Captura de Pantalla 2020-11-19 a la(s) 06 38 37" src="https://user-images.githubusercontent.com/43119386/99648486-dc235800-2a31-11eb-8466-b91fdbdf544b.png">

## 🌍 Your Environment
<pre><code>
 Angular CLI: 10.2.0
Node: 10.15.0
OS: darwin x64

Angular: 10.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cli                    10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by alan-agius4** [comment]
This issue is pretty similar to https://github.com/angular/angular-cli/issues/18707. The problem here is that when a HTML template is updated, we are not deleting the component TypeScript source file from the cache.

Note: This also effects the Ivy plugin.

**Comment by alan-agius4** [comment]
Let's track this https://github.com/angular/angular-cli/issues/19432 since it has the same root cause.

**Comment by alan-agius4** [comment]
@JoostK highlighted that this is a compiler bug which is being tracked here https://github.com/angular/angular/issues/39147
