### ISSUE TITLE
Make @ character removal optional when generating scoped libraries

### ISSUE THREAD

**Issue by djflex68** [angular/angular-cli#19439]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

While running ng generate library with a scoped package, let's say `@ui/mylib`, the generated folder is` ui/mylib`.
An explanation for this behavior was given here : [#646](https://github.com/angular/devkit/pull/646#issuecomment-380136599)
Unfortunately this breaks the behavior of much monorepo tools like lerna or oao. In a big project, you'll have several libraries that have dependencies on other ones in the same monorepo. To rebuild them all in order, you'll want to automatize launching `ng build` task on each library, by respecting the dependency graph (starting by the leaves).
Tools like lerna can do this, but will fail when looking at a folder that has the same name as the dependency in the package.json => @ui/mylib
Therefore these tools become unusable.

### Describe the solution you'd like
Make optional the removal of "@" character in the folder name, using a setting in angular.json for example ?

### Describe alternatives you've considered
No workaround found yet, unless I would consider redevelop a graph building system like lerna, just because of this folder glitch.

**Comment by alan-agius4** [comment]
Hi @djflex68,

**Lerna**

Not having `@` shouldn't be a blocker from using Lerna at all. Adding the below should be sufficient. The directory name is meaningless  as it uses the name field from the `package.json` manifest.

```json
{
  "packages": [
    "projects/ui/*"
  ],
  "version": "0.0.0"
}
```

```
$ yarn lerna ls --toposort --long
@ui/mylib  v0.0.1 projects/ui/mylib
@ui/mylib2 v0.0.1 projects/ui/mylib2
@ui/mylib1 v0.0.1 projects/ui/random-folder-name
```

**oao**
SInce `oao` uses `Yarn` workspaces not having `@` isn't a problem at all, as again the directory name doesn't matter. 

Adding the below to the root level `package.json` should be sufficient. 
```json
  "workspaces": [
    "projects/ui/*"
  ],
```

**Comment by djflex68** [comment]
@alan-agius4  I finally get this to work, following your suggestions. My problem was a bad usage of the lerna --scope flag in combination with a wrong configuration file.
Many thanks for pointing me in the right direction !

**Comment by alan-agius4** [comment]
Glad to hear that it worked for you 😀
