### ISSUE TITLE
are we supposed to install now via npm install -g angular-cli@webpack

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#1945]
npm install -g angular-cli@webpack ?
please update readme.md if so

regards

**Comment by christiandreher** [comment]
angular-cli@webpack is in testing. It will eventually be merged, but for now you can either use the @webpack pre-release or the latent 'stable' version, which is (at least when writing this comment) @1.0.0-beta.10
I hope I understood your question right

**Comment by born2net** [comment]
perfect, tx !!!
