### ISSUE TITLE
Components using JSX does not trigger application rebuild when running ng serve and AOT

### ISSUE THREAD

**Issue by jsantha** [angular/angular-cli#19461]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.3.29 (maybe related to Ivy or AOT enabled while serving?)

### Description

When an Angular component uses JSX syntax and thus is defined with `.tsx` extension instead of just `.ts` then compiler does not detect changes in Angular component related files `templateUrl` and `styleUrls`. Seems to work well when AOT is disabled.

## 🔬 Minimal Reproduction

Example application representing the issue:
https://github.com/jsantha/angular-cli-tsx-component-not-rebuilding

Reproduction:
1. Create a new Angular workspace and run `ng serve`
2. Create a new Angular component
3. Change component extension from `.ts` to `.tsx` (might need to enable jsx in tsconfig.json)
4. Make any change in component referenced files `templateUrl` or `styleUrls`
5. App does not pick up changes and not trigger rebuild

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.2
Node: 14.15.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.2 (cli-only)
@angular-devkit/core         11.0.2 (cli-only)
@angular-devkit/schematics   11.0.2 (cli-only)
@schematics/angular          11.0.2 (cli-only)
@schematics/update           0.1100.2 (cli-only)

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @jsantha,

This should no longer be an issue in the upcoming Angular CLI version 11.1. You can try the pre-release using the below command. 

```
ng update @angular/cli --next
```

**Comment by jsantha** [comment]
Hi @alan-agius4 

I have updated the reproduction repo to the 11.1. The problem is still here. The only thing that changed is that the stylesheet file triggers the rebuild now but changes are not reflected in the browser. Template changes are still being ignored.

https://github.com/jsantha/angular-cli-tsx-component-not-rebuilding

```
Angular CLI: 11.1.0-next.0
Node: 14.15.0
OS: win32 x64

Angular: 11.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0-next.0
@angular-devkit/build-angular   0.1101.0-next.0
@angular-devkit/core            11.1.0-next.0
@angular-devkit/schematics      11.1.0-next.0
@angular/cli                    11.1.0-next.0
@schematics/angular             11.1.0-next.0
@schematics/update              0.1101.0-next.0
rxjs                            6.6.3
typescript                      4.0.5
```

**Comment by alan-agius4** [comment]
@jsantha, I am unable to replicate this with the latest reproduction you provided, maybe it's a Windows thing.

Can you please try something?

in `node_modules/@ngtools/webpack/src/ivy/plugin.js`

Can you chnage line 271 
```diff
- return dependencies;
```

**Comment by jsantha** [comment]
@alan-agius4, provided change makes rebuild trigger for templates now.

However, another thing I have noticed in 11.1. Even tough rebuild is run for template or stylesheet changes, no changes in those files are actually propagated to the browser. This obviously was not a problem in 11.0. (performed clean install, tried on 2 independent Windows machines).

![showcase](https://user-images.githubusercontent.com/5988563/99953868-2f730e80-2d82-11eb-8b23-d8e8f03e5df7.gif)

**Comment by alan-agius4** [comment]
@jsantha, looks like the new Ivy Plugin has are a couple of issues on Windows. Will be looked at them soon.
