### ISSUE TITLE
Webpack 5 & false circular dependency warning on .graphql custom compile step

### ISSUE THREAD

**Issue by qortex** [angular/angular-cli#19466]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, my custom build step works flawlessly in Angular v10.

### Description

I just switched to Webpack 5 (Angular 11) and I now get 1 warning per .graphql file:

```
Warning: Circular dependency detected:
src/app/backbone/identity/person.graphql -> src/app/backbone/identity/person.graphql
```

Nothing fancy with my setup I think, just this webpack extra config:

```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader',
      },
    ],
  },
};
```

My graphql files don't import themselves or other files. Just simple graphql queries & mutations.

The warnings are there, but the app works well nonetheless.

Cross-posted here: https://github.com/apollographql/graphql-tag/issues/326

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.2
Node: 14.4.0
OS: linux x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.0
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.0
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
webpack                         5.6.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @qortex,

Thanks for opening the issue. 

Please be advised that while we do not disallow extending and customizing the Webpack configurations these are not supported by the Angular tooling team.

This is also unlikely to be caused by the Angular CLI as we don't have any handling of graphql files. Please feel free to re-open the issue if you discover otherwise. 

Thanks.
