### ISSUE TITLE
@ngtools/webpack: skipCodeGeneration option not replace componment's templateUrl with inline template.

### ISSUE THREAD

**Issue by enneid** [angular/angular-cli#19483]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Don't know

### Description

 I am using angular 11 + webpack 4.44 , and I am trying to put html templates inline. I have tried few combination of compilation options and AngularCompilerPlugin, but I could't force replacing templateUrl with  template in component.

## 🔬 Minimal Reproduction

Simple angular app using templateUrl:

**webpack.config.js**
<pre>
const path = require('path');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const ngtools = require('@ngtools/webpack')
const angctx = new ngtools.AngularCompilerPlugin({
    tsConfigPath: path.resolve(__dirname, './tsconfig.json'),
    entryModule: path.resolve(__dirname, './src/app.module#AppModule'),
    skipCodeGeneration: true,
    directTemplateLoading: true,
    sourceMap: true
})

module.exports = {
    entry: {
        // vendor: './src/vendor.ts',
        polyfills: './src/polyfills.ts',
        app: './src/app.ts'
    },
    mode: 'development',
    devtool: 'nosources-source-map',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'Public/javascripts/[name].bundle.js'
    },
    module: {

        rules: [
            // {
            //     test: /\.(html|htm)$/,
            //     use:  'html-loader',
            //},
            {test: /\.ts$/, use: 'ts-loader'}
        ]
    },
    plugins: [
        angctx,
    ],
    resolve: {
        extensions: ['.ts', '.js', '.html'],
        plugins: [new TsconfigPathsPlugin({
            configFile: path.resolve(__dirname, "./tsconfig.json")
        })],
    }
};
</pre>

**app.module.ts**
<pre><code>
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: 'views/main.component.html',
})
export class AppComponent {
  title = 'templates';
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
</code></pre>

**app.ts**
<pre><code>
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app.module';
import { enableProdMode } from '@angular/core';
//enableProdMode();
document.addEventListener('DOMContentLoaded', () => {
    platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err));
});
</code></pre>

## 🔥 Exception or Error
Fragment of  compiled bundle
<pre><code>
var AppComponent = /** @class */ (function () {
    function AppComponent() {
        this.title = 'templates';
    }
    AppComponent = __decorate([
        Object(_angular_core__WEBPACK_IMPORTED_MODULE_1__["Component"])({
            selector: 'app-root',
            templateUrl: 'views/main.component.html',
        })
    ], AppComponent);
    return AppComponent;
}());

</code></pre>

## 🌍 Your Environment
package
<pre><code>
{
	"name": "ownworld-angular",
	"private": true,
	"dependencies": {
		"@types/core-js": "~2.5",
		"@types/node": "~10.12",
	    "@angular/common": "^11.0.2",
		"@angular/compiler": "^11.0.2",
		"@angular/compiler-cli": "^11.0.2",
		"@angular/cli": "^11.0.2",
		"@angular/core": "^11.0.2",
		"@angular/forms": "^11.0.2",
		"@angular/platform-browser": "^11.0.2",
		"@angular/platform-browser-dynamic": "^11.0.2",
		"@ngtools/webpack": "^11.0.2",
		"rxjs": "^6.6.3",
		"typescript": "~4.0",
		"webpack": "^4.44.2",
		"webpack-cli":  "^4.2.0",
		"sass-loader": "^10.1.0",
		"css-loader": "^5.0.1",
		"node-sass": "^5.0.0",
		"ts-loader": "^8.0.11",
		"html-loader": "^1.3.2",
		"mini-css-extract-plugin": "^1.3.1",
		"tsconfig-paths-webpack-plugin": "^3.2.0",
		"zone.js": "~0.10.2",
		"core-js": "^3.7.0",
		"chokidar": "^3.4.3"
	},
	"scripts": {
		"webpack": "./node_modules/.bin/webpack"
	}
}
</code></pre>

tsconfig.json
<pre><code>
{
  "compilerOptions": {
    "baseUrl": ".",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "module": "es6",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "**/*.spec.ts",
    "node_modules",
    "vendor",
    "public"
  ],
  "compileOnSave": false,
  "angularCompilerOptions": {
   // "genDir": "aot",
    //"skipMetadataEmit": true,
    "enableResourceInlining": true,
    //"enableIvy": false
  }
}

</code></pre>
**Anything else relevant?**

**Comment by clydin** [comment]
The `enableResourceInlining` option is only used when compiling libraries directly with the `ngc` command line utility within the `@angular/compiler-cli` package.  It has no effect on applications where AOT compilation is recommended.  It also appears that the listed webpack configuration is not using the Angular loader.  The loader should be paired with the plugin for it to function effectively.  In addition, the plugin provides TypeScript path mapping support so the `tsconfig-paths-webpack-plugin` should not be needed as well.

The Angular CLI will automatically configure and setup Webpack internally as part of its build process. If the application does not have any unique requirements that would prevent the use of the Angular CLI, please consider its use for the project.

**Comment by enneid** [comment]
Thanks for reply, and describing few mismatches. Problem was associated with angular-loader
