### ISSUE TITLE
karma-coverage-istanbul-reporter inaccurate coverage when source-map is false

### ISSUE THREAD

**Issue by argelj289** [angular/angular-cli#19502]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

I'm not sure. because this is the first time I do this.

### Description

when I am executing `ng test --code-coverage=true` I get all the coverage when I call the function I need to test
but when I `ng test --code-coverage=true --source-map=false` some part of the code in the function I am calling is not getting covered and it seems very inaccurate at highlighting the uncovered tests

## 🔬 Minimal Reproduction
already stated in the description

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**
I use Chrome browser

**Comment by alan-agius4** [comment]
This is expected as source maps are required for code coverage to work properly.

Also note that since version 11 support for karma-coverage-istanbul-reporter has been deprecated in favour of karma-coverage.
