### ISSUE TITLE
Webpack optimizes to aggressively

### ISSUE THREAD

**Issue by mwawrusch** [angular/angular-cli#1950]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   Mac OSX
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:

webpack 2.1.0-beta.21
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Basically, when I import a service and reference that in the constructor (like importing a service) but that service is not used in that file then I end up with  a runtime error, in this case 'module ../logger.service' not found. The moment I reference it in code - like loggerService.log('something') all works.

``` code
import { LoggerService } from '../logger.service';
@Injectable()
export class UserPoolRegistrationService {
  constructor( private loggerService: LoggerService) {
}
}
```
1. The log given by the failure. Normally this include a stack trace and some
   more information.
2. Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by 5amfung** [comment]
If there's a way to change the optimization, that would be nice.  In my situation, when I build with `ng build --prod`, I found one component is completely missing and not getting instantiated at all.  I could only get it to work using `ng serve` or build with the `--dev` flag.

**Comment by kylecordes** [comment]
I have seen similar difficulties also, but I do not think the solution is to make the production bill plus optimized. Rather, it will be good to get more complete warnings about whatever situation causes your missing component. The last time I saw this, the problem was that the component in question was not included in any NgModule. I wonder if a future CLI update to detect and warn of that situation.

**Comment by TheLarkInn** [comment]
Is this as of RC6? I wonder if its related to the ESM builds now.

**Comment by 5amfung** [comment]
@TheLarkInn I was still on RC5.

**Comment by 5amfung** [comment]
@kylecordes Totally agreed, if there's warning about what's getting removed, that would help troubleshooting.  Right now the warning isn't very helpful to have any action.

When I ran into my issue, I immediately made sure I didn't forget including the components in my NgModule.  The app runs fine with `ng serve` or build with `ng build --dev`.  It doesn't work with `ng build --prod` only.  That's where I guess the only difference between `--dev` and `--prod` is the optimization and uglify.

**Comment by sondreb** [comment]
Is there a way to configure the uglify processing to be less aggresive in angular-cli?

We are dependent on class names for certain functionality, and those gets mangled into e.g. "e" when running --target=production.

I would really like to use production build, as that generates unique hashes for bundle files that are included and other optimizations, but I need to maintain the class names for some types. Is there a way to override?

**Comment by RicardoVaranda** [comment]
@sondreb This is currently not available but will be available once the addon system is implemented.

Here is a comment from Hansl that will explain a little better why this isn't possible:
[https://github.com/angular/angular-cli/issues/1656#issuecomment-240171375](url)

**Comment by filipesilva** [comment]
@delasteve tried to repro and it doesn't seem the original issue happens anymore, so I'm closing it as fixed.
