### ISSUE TITLE
Improve ng build --localize argument to accept locales instead of a boolean

### ISSUE THREAD

**Issue by kbarendrecht** [angular/angular-cli#19510]
# 🚀 feature request

### Relevant Package
This feature request is for `@angular/cli` and possibly `@angular/compiler-cli` `@angular/compiler` `@angular/localize`.

### Description
 The `--localize` argument for the `ng build` command currenty only accepts `true` or `false` which sets the locales from predefined configurations in the `angular.json` file.

### Describe the solution you'd like
Allow to set one or multiple locales through `ng build --localize=en` `ng build --localize=en,fr`. 

### Describe alternatives you've considered
The alternatives I found are;
- predefining each locale (and locale combination !) as a different configuration.
- building every locale

I believe both these alternatives do not fully benefit from the merits of the new faster way of making multiple localized builds.

**Comment by alan-agius4** [comment]
This is already possible.

https://github.com/angular/angular-cli/blob/1f42e071b4ae3ddee8b2eee1d27e8b6ad41e0cb0/packages/angular_devkit/build_angular/src/browser/schema.json#L212

**Comment by kbarendrecht** [comment]
@alan-agius4 , I'm receiving the following error. Perhaps I've made a mistake?
```
root:/[omitted]/resources/script [13:20]> yarn ng build --localize=fr
yarn run v1.22.5
$ /[omitted]/resources/script/node_modules/.bin/ng build --localize=fr
Cannot parse arguments. See below for the reasons.
    Argument --localize could not be parsed using value "fr".Valid type(s) is: boolean
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by alan-agius4** [comment]
It looks like passing a non boolean is not working as expected when used via the CLI, but it does work when set in `angular.json`.

As a workaround you can use something like;
```js
"configurations": {
  "fr-de": {
    "localize": ["fr", "de"]
  },
  "production": {
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.prod.ts"
      }
    ],
    "optimization": true,
    "outputHashing": "all",
    "sourceMap": false,
    "extractCss": true,
    "namedChunks": false,
    "extractLicenses": true,
    "vendorChunk": false,
    "buildOptimizer": true,
    "budgets": [
      {
        "type": "initial",
        "maximumWarning": "2mb",
        "maximumError": "5mb"
      },
      {
        "type": "anyComponentStyle",
        "maximumWarning": "6kb",
        "maximumError": "10kb"
      }
    ]
  }
}
```

Which you can then execute using `ng build --configuration=production fr-de`
