### ISSUE TITLE
Show marked message from the code as warning in the terminal

### ISSUE THREAD

**Issue by shral** [angular/angular-cli#19511]
# 🚀 Feature request
I would suggest a feature that would make it possible to show a marked line or message from the code as a warning in the build terminal. 
With that, you would have for example the possibility to mark an important place in the code that could be easily forgotten but is important to change before going into production.

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

**Comment by alan-agius4** [comment]
Hi @shral, Thanks for this feature request. However, this feature is out of the scope Angular CLI.

You can extend the browser builder to include the desired functionality.
