### ISSUE TITLE
Angular 11 update removes tsconfig.base.json

### ISSUE THREAD

**Issue by ikonezg** [angular/angular-cli#19523]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
After the update to Angular 11 tsconfig.base.json was deleted. I checked it in my project git repo. 

## 🔬 Minimal Reproduction

ng update @angular/cli @angular/core 

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
In version 10.0, the `tsconfig.base.json` file was used to implement TypeScript's solution style configuration. In version 10.1 removed usage of TypeScript's solution style configuration and the `tsconfig.base.json` file was removed as a result.

For more information please see: https://github.com/angular/angular-cli/pull/18478.
