### ISSUE TITLE
Support for WorkspaceProject and WorkspaceSchema interfaces

### ISSUE THREAD

**Issue by victorsc** [angular/angular-cli#19525]
# 🚀 Feature request
Hello,
Starting Angular 11, the experimental workspace API [has been removed](https://github.com/angular/angular-cli/pull/18642).
On our projects, we were relying on the `WorkspaceProject` and `WorkspaceSchema` interfaces for our internal builders and schematics.

Do you have any recommendations of what we could use instead? 
[WorkspaceSchema](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/utility/workspace-models.ts#L134) doesn't have all the missing properties the experimental API had.

Thank you,
Victor 

### Command (mark with an `x`) 

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Described above.

### Describe the solution you'd like
N/A

### Describe alternatives you've considered
N/A

**Comment by Jack-WangZhe** [comment]
Same concern 😄 Can anyone support this issue? 

Thanks!
Jack

**Comment by alan-agius4** [comment]
Hi,

The linked [WorkspaceSchema](https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/utility/workspace-models.ts#L134) in `@schematics/angular` is a private interface.

The new API has different interfaces, you can use the following instead.
`WorkspaceSchema` -> `WorkspaceDefinition`
`WorkspaceProject`  -> `ProjectDefinition`

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/src/workspace/definitions.ts
