### ISSUE TITLE
Upgrade Angular-cli@webpack and ng build fail

### ISSUE THREAD

**Issue by mavericks065** [angular/angular-cli#1953]
1. OS El Capitan

2. angular-cli: 1.0.0-beta.11-webpack.8
node: 5.6.0
os: darwin x64

3. My app was created using angular-cli then moved to _angular-cli: 1.0.0-beta.11-webpack.2_
I tried to upgrade angular-cli@webpack so I uninstalled it, cleaned and re-installed. 
When I ran ng build I got the following stack trace:

> ng build
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
The "defaults.prefix" and "defaults.sourceDir" properties of angular-cli.json are deprecated in favor of "apps[0].root" and "apps[0].prefix". Please update in order to avoid errors in future versions of angular-cli.
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.getWebpackCommonConfig (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/angular-cli/addon/ng2/models/webpack-build-common.ts:23:25)
    at new NgCliWebpackConfig (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/angular-cli/addon/ng2/models/webpack-config.ts:13:30)
    at Class.exports.default.Task.extend.run (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/angular-cli/addon/ng2/tasks/build-webpack.ts:16:22)
    at Class.Command.extend.run (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/angular-cli/addon/ng2/commands/build.ts:49:26)
    at Class.<anonymous> (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/angular-cli/lib/models/command.js:152:17)
    at lib$rsvp$$internal$$tryCatch (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/rsvp/dist/rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)

> 

Here is my angular-cli.json: (the version of my project is 1.0.0-beta.11-webpack.2 but I don't understand since I followed the procedure I read [here](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md) )

{
  "project": {
    "version": "1.0.0-beta.11-webpack.2",
    "name": "***************"
  },
  "apps": [
    {
      "main": "src/main.ts",
      "tsconfig": "src/tsconfig.json",
      "mobile": false
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "config/protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "config/karma.conf.js"
    }
  },
  "defaults": {
    "prefix": "app",
    "sourceDir": "src",
    "styleExt": "scss",
    "prefixInterfaces": false,
    "lazyRoutePrefix": "+"
  }
}

Thank you for your help.

**Comment by christiandreher** [comment]
The error message is clear. `defaults.prefix` and `defaults.sourceDir` was removed and moved to `app`. Make `ng init` and view the diff

**Comment by mavericks065** [comment]
@christiandreher I did it but I got in angular-cli.json exactly the same: 

```
{
  "project": {
    "version": "1.0.0-beta.11-webpack.2",
    "name": "poiuytreza"
  },
  "apps": [
    {
      "main": "src/main.ts",
      "tsconfig": "src/tsconfig.json",
      "mobile": false
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "config/protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "config/karma.conf.js"
    }
  },
  "defaults": {
    "prefix": "app",
    "sourceDir": "src",
    "styleExt": "css",
    "prefixInterfaces": false,
    "lazyRoutePrefix": "+"
  }
}
```

**Comment by christiandreher** [comment]
What is the output if you run the following commands from your project root?

1. `npm ls --depth 0 | grep angular-cli`
2. `npm ls -g --depth 0 | grep angular-cli`

**Comment by mavericks065** [comment]
@christiandreher 

1- 
> npm ls --depth 0 | grep angular-cli
├── angular-cli@1.0.0-beta.11-webpack.8
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
...

2- 
> npm ls -g --depth 0 | grep angular-cli
├── angular-cli@1.0.0-beta.11-webpack.8
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: webpack@1.x.x || 2.x.x, required by string-replace-loader@1.0.3

Yes I read this notice. however i did not run it on the new project, so I re-created a new project and ran it and it did not change anything: same angular-cli.json

**Comment by kethan** [comment]
me too getting the same error 
+-- angular-cli@1.0.0-beta.11-webpack.8
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: webpack@1.x.x || 2.x.x, required by string-replace-loader@1.0.3
npm ERR! peer dep missing: @angular/platform-server@^2.0.0-rc.5, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: zone.js@^0.6.17, required by @angular/core@2.0.0-rc.6
npm ERR! peer dep missing: tslint@^3.0.0, required by tslint-loader@2.1.5
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6
npm ERR! extraneous: async-some@1.0.2 /usr/local/lib/node_modules/npm/node_modules/async-some
npm ERR! extraneous: lodash._setcache@4.1.0 /usr/local/lib/node_modules/npm/node_modules/lodash._baseuniq/node_modules/lodash._setcache
npm ERR! extraneous: lodash._setcache@4.1.1 /usr/local/lib/node_modules/npm/node_modules/lodash.without/node_modules/lodash._basedifference/node_modules/lodash._setcache
npm ERR! extraneous: lodash.repeat@4.0.0 /usr/local/lib/node_modules/npm/node_modules/npmlog/node_modules/gauge/node_modules/lodash.repeat
npm ERR! extraneous: is-absolute@0.1.7 /usr/local/lib/node_modules/npm/node_modules/which/node_modules/is-absolute

**Comment by bingneef** [comment]
@mavericks065 I have had the same issue (the length of undefined), but I believe it was fixed by adding environments to your angular-cli.json (especially the source index). Hopefully this would work for you too.

{
  "project": {
    "version": "1.0.0-beta.11-webpack.8",
    "name": "application_name"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": "assets",
      "index": "index.html",
      "main": "main.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "dev": "environments/environment.dev.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "sass",
    "prefixInterfaces": false,
    "lazyRoutePrefix": "+"
  }
}

**Comment by mavericks065** [comment]
@bingneef thanks. I think we made some progress. 

However when it is building I get errors like: (I don't copy paste all of them because there are too many of them just the firsts). I thought I could solve them with this issue #1901 but did not work.

> ERROR in [default] 
Cannot find global type 'Array'.

ERROR in [default] 
Cannot find global type 'Boolean'.

ERROR in [default] 
Cannot find global type 'Function'.

ERROR in [default] 
Cannot find global type 'IArguments'.

ERROR in [default] 
Cannot find global type 'Number'.

ERROR in [default] 
Cannot find global type 'Object'.

ERROR in [default] 
Cannot find global type 'RegExp'.

ERROR in [default] 
Cannot find global type 'String'.

ERROR in [default] /Users/mba/Business/workspace/angular-ionic/iSecretVault_webapp_ng2/node_modules/@angular/common/src/directives/ng_class.d.ts:81:33 
Cannot find name 'Set'.

**Comment by christiandreher** [comment]
Are you sure that `npm ls --depth 0 | grep typescript` returns `2.0.0` as version for typescript? Maybe you have installed it globally?

**Comment by iceinsidefire** [comment]
I am facing same problem as @mavericks065.

npm ls --depth 0 | grep typescript
├── typescript@2.0.2
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/compiler-cli@0.5.0
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: webpack@1.x.x || 2.x.x, required by string-replace-loader@1.0.3
npm ERR! peer dep missing: typescript@^1.9.0-dev, required by @angular/tsc-wrapped@0.2.2
npm ERR! peer dep missing: typescript@^1.8.0 || ^1.9.0-dev, required by tsickle@0.1.6

**Comment by christiandreher** [comment]
Try fixing the version of typescript to `2.0.0`. In your `package.json`, change this line:

`"typescript": "^2.0.0",`

to
 
`"typescript": "2.0.0",`

**Comment by mavericks065** [comment]
@christiandreher When I followed bingneef recommendation I got the new errors. Then I changed my typescript version to 

> "typescript": "2.0.0"

as it was recommended but completely forgot to run 

> npm install

now the build works and I get : 

> npm ls --depth 0 | grep typescript
> ├── UNMET PEER DEPENDENCY typescript@2.0.0

Thanks for your help guys.

**Comment by iceinsidefire** [comment]
It worked. But got issue as mentioned in [Issue 19481](https://github.com/angular/angular-cli/issues/1948l).
Thanks

**Comment by mindruptive** [comment]
The problem still exists with

- angular release (2.0.0)
- npm 3.10.8
- node 6.5.0
- angular cli 1.0.0-beta.16
- typescript 2.0.3
- webpack 2.1.0-beta.22

It can be solved by @christiandreher (thanks!) hint to pin the typescript version to 2.0.0.  
It's good to have a solution but in order to avoid future problems I'd like to understand the exact reason why those "cannot find global..." happen.

Any help is appreciated, thanks
