### ISSUE TITLE
ng serve cannot resolve new modules imported after it was launched

### ISSUE THREAD

**Issue by jooleeanh** [angular/angular-cli#19534]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This was happening to me on a previous version of angular-cli, which I sadly cannot retrieve.

### Description

Once `ng serve` is running, adding any module to the app.module.ts imports gives errors about the newly added module. I believe this to be a bug since the various video tutorials I have followed did not show this behaviour.
Stopping the server and relaunching it solves the problem. But this obviously becomes tedious if it has to be repeated every time a new module is imported.

## 🔬 Minimal Reproduction

1. Create new project `ng new serve-import-bug` with default settings
1. Launch the angular server with `ng serve`
1. Add a new module in app.module.ts, for example `FormsModule`
1. Look at terminal executing the `ng serve` command

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/@angular/forms/forms.d.ts:2553:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (@angular/forms) which declares FormsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    2553 export declare class FormsModule {
                              ~~~~~~~~~~~


</code></pre>


## 🌍 Your Environment
<pre><code>

Angular CLI: 10.2.0
Node: 12.16.1
OS: win32 x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cli                    10.2.0
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by alan-agius4** [comment]
Hi @jooleeanh,

This should no longer be an issue in version 11.1.
You can try this version using `ng update @angular/cli --next`.
