### ISSUE TITLE
Append generated Component to the closest NgModule

### ISSUE THREAD

**Issue by gfrSE** [angular/angular-cli#1954]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.8
node: 6.2.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

- Change directory to a NgModule
- `ng g c anyComponentName`
--> This Component will be added to the app.module.ts instead of the closest NgModule!

4. The log given by the failure. Normally this include a stack trace and some
   more information.

-/-

5. Mention any other details that might be useful.

Would be nice to get that generated Component into the right NgModule.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mxii** [comment]
#1966

**Comment by mxii** [comment]
#1966

**Comment by mxii** [comment]
#1966
