### ISSUE TITLE
Angular 11: Builds ES5 bundle even though it did not in Angular 10

### ISSUE THREAD

**Issue by criskrzysiu** [angular/angular-cli#19558]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes, there was no ES5 bundle build with Angular 10

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
.browserslist.rc
```
last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major version
last 2 iOS major versions
Firefox ESR
not IE 9-11 # For IE 9-11 support, remove 'not'.
```

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
`.browserslist.rc` is not a valid configuration for browserslist.

Kindly rename it to `.browserslistrc`.

**Comment by criskrzysiu** [comment]
My bad, It is .browserslistrc

W dniu pon., 7.12.2020 o 15:41 Alan Agius <notifications@github.com>
napisał(a):

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
