### ISSUE TITLE
Can we Replace scss file in component of angular with css file while generating new component?

### ISSUE THREAD

**Issue by suryatejaj97** [angular/angular-cli#19559]
A quick question? While generating new components in Angular CLI, can we generate the component with CSS file instead of SCSS file as the global style of the angular project is SCSS. Is there any possibility, if it's there how can we implement it?

#8988 #6381

**Comment by devoto13** [comment]
Check `--style` option of https://angular.io/cli/generate#component-command.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
