### ISSUE TITLE
fileReplacements for environments

### ISSUE THREAD

**Issue by MaTo04** [angular/angular-cli#19555]
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Since Angular 11 the fileReplacements in the angular.json is deprecated and cant be used. For the index replacement i found a solution (https://github.com/angular/angular-cli/issues/14599) but how to replace the enviroments without fileReplacements in Angular 11.

## 🔬 Minimal Reproduction
<pre>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "MyProjectName": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "aot": true,
            "outputPath": "Application",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/assets",
              "src/assets/logo.png",
              "src/style/"
            ],
            "styles": [
              "src/style/_fontawesome.scss",
              "src/styles.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/style/"
              ]
            },
            "scripts": [],
            "allowedCommonJsDependencies": [
              "@angular/common/locales/de",
              "@angular/common/locales/en",
              "rxjs/Subject",
              "rxjs/operators",
              "rxjs/Subscription",
              "lodash/cloneDeep",
              "chart.js",
              "mathjs",
              "rbush",
              "qrcode"
            ]
          },

          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                },
                {
                  "replace": "src/index.html",
                  "with": "src/redirect.html"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "MyProjectName:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "MyProjectName:build:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "MyProjectName:build:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "assets": [
              "src/assets",
              "src/assets/logo.png",
              "src/style/"
            ],
            "styles": [
              "node_modules/@fortawesome/fontawesome-pro/css/all.css",
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "MyProjectName",
  "schematics": {
    "@schematics/angular:component": {
      "style": "scss"
    }
  }
}
<code>

## 🔥 Exception or Error
<pre>
Schema validation failed with the following errors:
  Data path ".fileReplacements[1]" should NOT have additional properties(replace).
  Data path ".fileReplacements[1].replace" should match pattern "\.(([cm]?j|t)sx?|json)$".
  Data path ".fileReplacements[1]" should match exactly one schema in oneOf.
<code>

## 🌍 Your Environment
</code>
Angular CLI: 11.0.2
Node: 12.16.1
OS: win32 x64

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.2
@angular-devkit/build-angular      0.1100.2
@angular-devkit/core               11.0.2
@angular-devkit/schematics         11.0.2
@angular/cdk                       11.0.1
@angular/material                  11.0.1
@angular/material-moment-adapter   11.0.1
@schematics/angular                11.0.2
@schematics/update                 0.1100.2
rxjs                               6.5.4
typescript                         4.0.5
</pre>

**Comment by alan-agius4** [comment]
`fileReplacements` is not deprecated and can still be used to replace environment files.

In v11, we issue an error for files extensions which are not supported, where previously these used to fail silently.

**Comment by MaTo04** [comment]
Always a typescript file is used in examples and blog posts. I have a solution for everyone who has the same "problem".

Change your typescript file to an environment.json & environment.prod.json:

**Development environment**
`{
  "environment": {
    "production": false,
    "apiUrl": "http://localhost:4200"
  }
}`

**Production environment**
`{
  "environment": {
    "production": true,
    "apiUrl": ".."
  }
}`

In the angular.json you could replace it like before:

<pre>
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.json",
                  "with": "src/environments/environment.prod.json"
                }
              ],
              "index": {
                "input": "src/redirect.html",
                "output": "index.html"
              }
<code>

In the service you have to import the environment.json:
`import { environment } from './environments/environment.json';`

**Comment by alan-agius4** [comment]
`.ts` files are fully supported in `fileReplacements`.

**Comment by MaTo04** [comment]
Ok, thanks it was only the problem with the index.html
