### ISSUE TITLE
Move @angular-devkit/build-angular to the dependencies object when running ng new

### ISSUE THREAD

**Issue by RogierdeRuijter** [angular/angular-cli#19565]
# 🚀 Feature request

Move @angular-devkit/build-angular in the package.json from `devDependencies` to the `dependencies` object. 

### Command (mark with an `x`)
- [ x ] new

### Description
After generating a new project and running `npm install --prod` or `yarn install --prod` you are unable to run `ng build` because the @angular-devkit/build-angular is not available. 

What I would like to have is a way to install the minimal amount of packages that are needed for me to build the angular application. By utilizing `--prod` from package managers we can do this. But how the package.json dependencies objects are structured now `--prod` is unusable. Now we have to do a full install with all the development dependencies (protractor, linter, etc..) to build angular.

### Describe the solution you'd like
Move the @angular-devkit/build-angular to the dependencies object.

### Describe alternatives you've considered
Doesn't apply

**Comment by alan-agius4** [comment]
Hi @RogierdeRuijter,

Thanks for this request. 

Just moving `@angular-devkit/build-angular` will not be enough to build the application, there are other `devDependencies` that required for a successful build such as `@types/`, `typescript`, `@angular/compiler-cli`, `@angular/cli` etc...

`--prod` is typically used to install the needed dependencies for the application to run on a production server, such case are when using SSR.  `@angular-devkit/build-angular` is listed as a dev dependency as this package is not needed for an application to run. 

While, no one is stopping you from moving these packages from `devDependencies` to `dependencies`, moving these packages as the default isn't the correct pattern.
