### ISSUE TITLE
`regeneratorRuntime` callment generated for `monaco-editor` workers incorrectly

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#19566]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 10.*

### Description

 

![image](https://user-images.githubusercontent.com/8336744/101439972-b7dfda80-3950-11eb-81c5-7774eb6cfa6a.png)

In a clean webpack project without angular/angular-cli, there is no `regeneratorRuntime` generated at all in the output `.worker.js` files.

## 🔬 Minimal Reproduction

https://github.com/JounQin/test/tree/monaco_editor

Branch monaco_editor

## 🔥 Exception or Error

```js
Uncaught ReferenceError: regeneratorRuntime is not defined
```

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.0.3
Node: 12.20.0
OS: darwin x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.3
@angular-devkit/core         11.0.3
@angular-devkit/schematics   11.0.3
@schematics/angular          11.0.3
@schematics/update           0.1100.3
rxjs                         6.6.3
typescript                   4.1.2
</code></pre>

**Anything else relevant?**

I don't know whether it's related to https://github.com/angular/angular-cli/pull/19049

**Comment by JounQin** [comment]
Besides, `monaco-editor/esm/vs/editor/editor.api` is actually an ESM, but `CommonJsUsageWarnPluginOptions` reports it incorrectly.

**Comment by alan-agius4** [comment]
Hi @JounQin,

I downloaded your reproduction and I wasn't able to reproduce the error.
![Screenshot 2020-12-08 at 08 49 15](https://user-images.githubusercontent.com/17563226/101459573-b5718680-3938-11eb-9d5d-9a9de3e4dcb3.png)

With regards to the common js usage warnings, it seems that `MonacoEditorWebpackPlugin` is augmenting the source of Monaco Editor and adding CJS modules. https://github.com/microsoft/monaco-editor-webpack-plugin/blob/master/src/loaders/include.ts

Please be aware to custom webpack configurations are not supported by the Angular CLI team.

**Comment by JounQin** [comment]
@alan-agius4 

> I downloaded your reproduction and I wasn't able to reproduce the error.

That's very strange, I can always reproduce it locally, and I tried to remove `node_modules`. Does your browser support web-worker? The error is thrown from the web worker.

> Please be aware to custom webpack configurations are not supported by the Angular CLI team.

I understand your position, but it just works well without `angular-cli`, so it must be somewhere related to `angular-cli`, do you have any idea which part of `angular-cli`'s default webpack configuration could be affected? So that I can debug it more specifically.

**Comment by JounQin** [comment]
Update: it seems it load incorrect `editor.worker.js` from service worker somehow... I will try to debug more carefully.
