### ISSUE TITLE
ng lint with eslint Unknown option: '--files'

### ISSUE THREAD

**Issue by koenig-dominik** [angular/angular-cli#19563]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: tslint ~6.1.0 / codelyzer ^6.0.0

### Description

with the new recommended linting library [eslint](https://github.com/angular-eslint/angular-eslint) the --files option of ng lint is not recognized

## 🔬 Minimal Reproduction

1. create a new project with `ng new foo`
2. install the recommended eslint linter with `ng add @angular-eslint/schematics` and `ng g @angular-eslint/schematics:convert-tslint-to-eslint foo`
3. run the linter with the --files option `ng lint --files="src/app/app.module.ts" `

## 🔥 Exception or Error
<pre><code>Unknown option: '--files'
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 11.0.3
Node: 10.22.1
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the angular-eslint project or file an issue on their issue tracker.
