### ISSUE TITLE
11.0.x does not support Node 13 due to terser version

### ISSUE THREAD

**Issue by cjcrandall** [angular/angular-cli#19560]
Sorry, this didn't seem to fit neatly into any categories, but it should be pretty simple to fix.

11.0.x specifies terser 5.3.7 as a dependency for build-angular:

https://github.com/angular/angular-cli/blob/34cd0e0a8b048e4964d2b38b4ce5d25b96535a08/packages/angular_devkit/build_angular/package.json#L68

This version of terser does not support Node 13. Please upgrade terser to at least 5.3.8 on 11.0.x (the only change in 5.3.8 was fixing Node 13 support, see https://github.com/terser/terser/pull/861).

I also see that the same terser version is listed as a dev dependency in the main package.json file, but the dependency in build-angular is what's causing an error for me.

**Comment by alan-agius4** [comment]
Node.js 13 is indeed not supported. It’s also currently no longer supported by the Node.JS team. Odd versions of Node.JS become unsupported after 6 months. See: https://nodejs.org/en/about/releases/ 

Please downgrade or update to a supported version. (10, 12, 14 or 15)

**Comment by cjcrandall** [comment]
I mean, `terser` didn't support Node 13 for all of 3 days. I saw a discussion on https://github.com/angular/angular-cli/issues/19470 to the effect of intending to give a _warning_ for unsupported versions, but the current issue makes `yarn install` fail outright for a non-obvious reason.

**Comment by alan-agius4** [comment]
`terser` has been update in 11.1 https://github.com/angular/angular-cli/blob/eb30a92e8ad4bf27461010b1917d1fcffd10ff31/packages/angular_devkit/build_angular/package.json#L69

Although I do recommand that you switch to a supported Node.JS version.
