### ISSUE TITLE
Use lint-staged for ng lint

### ISSUE THREAD

**Issue by vahidvdn** [angular/angular-cli#19570]
There are some issues with `ng lint`. Linting for source code is a good idea. But in some cases that's not. There should be an option to lint only staged files. Here is two reason:

1- linting the whole project needs more time. (Although there is an option to select files, but selecting files when there are a lot of changed files is not a good idea)

 2- Here is the scenario
```json
"husky": {
  "hooks": {
    "pre-commit": "ng lint --fix=true"
  }
}
```

If there is a lint error, it prevents from being committed. Here is the scenario:

 1. Developer writes wrong code (e.g. `x==y` which should be `x===y` from lint point of view)
 2. He uses these commands: `git add .` and `git commit -m "msg here"` which fails. Because lint fails.
 3. He corrects the source code. But instead of doing `git add .` again, he uses this command: `git commit -m "msg here"`. This time lint doesn't fail, because in source code everything is fine, and `ng lint` succeeds. But actually, he is committing the previous version which has been added before.

**Comment by alan-agius4** [comment]
@vahidvdn, there are 3rd party solutions for linting only changed file that can be used in with `ng lint` such as https://github.com/okonet/lint-staged.

Consider the default lint builder which is currently used in the CLI is deprecated as part of the TSLint deprecation, I think we shouldn’t add any additional features.

This topic has been discussed in https://github.com/angular/angular-cli/issues/7612 as well.
