### ISSUE TITLE
new angular project  compile with tsc

### ISSUE THREAD

**Issue by Nagendracv** [angular/angular-cli#19581]
# 🐞 Bug report
- [x ] new

### Is this a regression?
No. Don't know if it worked before...

### Description
My current typescript version is 4.0.5 nodejs version returns below information
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@schematics/angular             11.0.3
@schematics/update              0.1100.3
rxjs                            6.6.3
typescript                      4.0.5

Below are the steps I followed on an empty folder
ng new angproject
cd angproject
ng serve <- works fine
tsc  <- fails with 26 errors like below

../../node_modules/@types/es6-shim/ts3.1/index.d.ts:1:11 - error TS2300: Duplicate identifier 'IteratorResult'.
1 interface IteratorResult<T> {
            ~~~~~~~~~~~~~~
  ../../../../../../../../../Users/c_v_n/AppData/Roaming/npm/node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
../../node_modules/@types/es6-shim/ts3.1/index.d.ts:240:5 - error TS2687: All declarations of 'EPSILON' must have identical modifiers.
240     EPSILON: number;
        ~~~~~~~
../../node_modules/@types/es6-shim/ts3.1/index.d.ts:275:5 - error TS2687: All declarations of 'MAX_SAFE_INTEGER' must have identical modifiers.
275     MAX_SAFE_INTEGER: number;
        ~~~~~~~~~~~~~~~~
../../node_modules/@types/es6-shim/ts3.1/index.d.ts:282:5 - error TS2687: All declarations of 'MIN_SAFE_INTEGER' must have identical modifiers.
282     MIN_SAFE_INTEGER: number;
        ~~~~~~~~~~~~~~~~
../../node_modules/@types/es6-shim/ts3.1/index.d.ts:338:5 - error TS2687: All declarations of 'flags' must have identical modifiers.
338     flags: string;
        ~~~~~
../../node_modules/@types/es6-shim/ts3.1/index.d.ts:490:5 - error TS2687: All declarations of 'prototype' must have identical modifiers.
490     prototype: Promise<any>;
        ~~~~~~~~~
../../node_modules/@types/es6-shim/ts3.1/index.d.ts:553:5 - error TS2687: All declarations of 'size' must have identical modifiers.

**Comment by alan-agius4** [comment]
This is expected because the tsc will pick the root level tsconfi. This tsconfig is not meant to be used for a compilation, as it's the a base tsconfig which is also used for the IDE.

To compile the application using `tsc` you need to pass the correct tsconfig file using `-p/--project` argument. https://www.typescriptlang.org/docs/handbook/compiler-options.html
```
tsc -p tsconfig.app.json
```
