### ISSUE TITLE
Option to disable the table view on ng serve, as it block the terminal with super long list of files

### ISSUE THREAD

**Issue by WLun001** [angular/angular-cli#19584]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
option to disable the table view on ng serve, `--verbose=false` seems like not working.

### Describe the solution you'd like
`--verboase=false` to disable it

### Describe alternatives you've considered
No workaround

**Comment by alan-agius4** [comment]
Hi @WLun001, 

It is expected that `--verbose=false`, doesn't disable the list of files that have been outputted.

I'd like to understanding how to replicate the issue you are encountering, "block the terminal", however I am unable to replicate this on my local environment even when the table contains 500 items.

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by WLun001** [comment]
HI @alan-agius4, `block the terminal` i meant the list so long, that it the terminal unable to scroll up to see the initial logs

**Comment by alan-agius4** [comment]
It very likely that in your terminal you have set a scroll limit, it you have a lot of files, you may want to increase this. It is not clear which terminal you are using. But by default ZSH allows scrolling back 1000 lines.

This can also be combined with https://github.com/angular/angular-cli/issues/19567.

**Comment by WLun001** [comment]
@alan-agius4 thanks, I have set my terminal to unlimited scroll. Yes can be combined
