### ISSUE TITLE
Allow configurable use of untyped transpileModule()

### ISSUE THREAD

**Issue by pauldraper** [angular/angular-cli#19587]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x]  build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Angular CLI is slow (particularly to start up). A lot of this has to do with the time to typecheck TypeScript.

### Describe the solution you'd like

An --transpileModules or --untyped option to skip typechecking.

### Describe alternatives you've considered

Using webpack + babel-typescript instead. However, this misses out on the simplicity of using Angular CLI and is inconvenient to configure.

**Comment by alan-agius4** [comment]
Hi @pauldraper,

Thanks for this feature request.

This is related to an issue you commented on https://github.com/angular/angular/issues/37585 where the Angular compiler doesn't provide a way to transpile a single module. Therefore, AOT compilation wouldn't be possible, which is the default mode in development mode.

In addition to that, this also doesn't align with the goal of the Angular CLI to having stricter type-checking rules by default. Without stricter type-checking rules a lot of TypeScript's benefits are lost, together with the possibility of earlier feedback on potential bugs using the type-checker.

NB: You can use 3rd party Angular builds and extend the Webpack configuration to replace the Angular compiler plugin with Babel TypeScript.

**Comment by pauldraper** [comment]
> Therefore, AOT compilation wouldn't be possible

Naturally. But Angular CLI works with both `"aot": true` and `"aot": false` (I've observed the latter to be far faster for dev).

> In addition to that, this also doesn't align with the goal of the Angular CLI to having stricter type-checking rules by default.

Is that the goal?

Because Angular requires flipping two flags `"fullTemplateTypeCheck": true` and `"strictTemplates": true` to get even close to acceptable type-checking.

> NB: You can use 3rd party Angular builds and extend the Webpack configuration to replace the Angular compiler plugin with Babel TypeScript.

Will this work with `@Component` styles/styleUrls?

**Comment by alan-agius4** [comment]
Hi,

> Naturally. But Angular CLI works with both "aot": true and "aot": false (I've observed the latter to be far faster for dev).

 JIT mode is of course faster, because there is less work for the TypeScript compiler to do. This is because in AOT mode there are Angular specific type-checks and transformations. 

> Because Angular requires flipping two flags "fullTemplateTypeCheck": true and "strictTemplates": true to get even close to acceptable type-checking.

Stricter type-checking in terms of not just Angular, but also TypeScripts such example of such options are: `noImplicitReturns`, `forceConsistentCasingInFileNames`, `strict` etc.. Note: `strictTemplates` is actually a super set of `fullTemplateTypeCheck`.

> Will this work with @Component styles/styleUrls?
For that you'll need a transformer, which requires type-checking.
