### ISSUE TITLE
Can't use Material2 with angular-cli@webpack because of moduleId

### ISSUE THREAD

**Issue by chosroes** [angular/angular-cli#1958]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.04

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Added Material2

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Uncaught TypeError: uri.match is not a function

5. Mention any other details that might be useful.

> ---------------------------------------------------------------

Can we have something like [that](https://github.com/AngularClass/angular2-seed/commit/84aacc18682bbe38631cd3c457d9e90944d6fd0e) in the webpack configuration ?

**Comment by christiandreher** [comment]
This was also discussed here: https://github.com/angular/material2/issues/1151

In [a comment](https://github.com/angular/material2/issues/1151#issuecomment-244182267) @fxck claims that there is a plugin already included in webpack2 to get rid of this:

> You can use NamedModulesPlugin(included in webpack2) **[...]**

**Comment by filipesilva** [comment]
Does this still happen with `beta.15`? I think it's been fixed since.

**Comment by JanStureNielsen** [comment]
It does not, @filipesilva -- I'm successfully running `beta.15` with most of the `2.0.0-alpha.8-2` components of `@angular2-material`:

    angular-cli: 1.0.0-beta.15
    node: 6.5.0
    os: linux x64

dependencies:

```
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23",
    "@angular2-material/button": "2.0.0-alpha.8-2",
    "@angular2-material/button-toggle": "2.0.0-alpha.8-2",
    "@angular2-material/card": "2.0.0-alpha.8-2",
    "@angular2-material/checkbox": "2.0.0-alpha.8-2",
    "@angular2-material/core": "2.0.0-alpha.8-2",
    "@angular2-material/grid-list": "2.0.0-alpha.8-2",
    "@angular2-material/icon": "2.0.0-alpha.8-2",
    "@angular2-material/input": "2.0.0-alpha.8-2",
    "@angular2-material/list": "2.0.0-alpha.8-2",
    "@angular2-material/menu": "2.0.0-alpha.8-2",
    "@angular2-material/progress-bar": "2.0.0-alpha.8-2",
    "@angular2-material/progress-circle": "2.0.0-alpha.8-2",
    "@angular2-material/radio": "2.0.0-alpha.8-2",
    "@angular2-material/sidenav": "2.0.0-alpha.8-2",
    "@angular2-material/slide-toggle": "2.0.0-alpha.8-2",
    "@angular2-material/slider": "2.0.0-alpha.8-2",
    "@angular2-material/tabs": "2.0.0-alpha.8-2",
    "@angular2-material/toolbar": "2.0.0-alpha.8-2",
    "@angular2-material/tooltip": "2.0.0-alpha.8-2"
  },
```
and development dependencies:
```
   "devDependencies": {
    "@types/hammerjs": "2.0.32",
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.14",
    "codelyzer": "~0.0.26",
    "hammerjs": "2.0.8",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.5",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
```

**Comment by filipesilva** [comment]
@JanStureNielsen awesome, glad to hear!
