### ISSUE TITLE
Unable To Create New Angular Project

### ISSUE THREAD

**Issue by WarienX** [angular/angular-cli#19590]
Hello everyone, I just purchased a new laptop and installed Node JS on it. I was creating my Angular 7 project but am unable to do so using the cli. Need assistance at the earliest. I will share screenshots of the issue below.
![scr1](https://user-images.githubusercontent.com/26925053/101872630-975f8c80-3bab-11eb-80ab-2ce0adc68e8c.PNG)
![scr2](https://user-images.githubusercontent.com/26925053/101872633-99295000-3bab-11eb-8458-389ae6746fb6.PNG)
![scr3](https://user-images.githubusercontent.com/26925053/101872645-9c244080-3bab-11eb-9cea-09ec214b197b.PNG)

Kindly help me resolve this issue.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
