### ISSUE TITLE
Control what gets generated - Transpilation/Compilation Time version of *ngIf

### ISSUE THREAD

**Issue by blasco** [angular/angular-cli#19593]
# 🚀 Feature request

I haven't find a way to control how to disable part of the generated code with angular. Here a more in depth description of the feature that I'm looking for:

https://stackoverflow.com/questions/65020209/control-what-gets-generated-transpilation-compilation-time-version-of-ngif

### Description

To sum up, this is what I'm looking for:

```
#define version admin

User stuff

#if version==admin

   Admin stuff
   <div (click)="adminFunction()"></div>

#endif
```

So from the same code bases I can generate two different apps. This is also useful for testing and there are more usecases.

Maybe there is away to already achieve this, but I haven't been able to find it. Is this something interesting to add in the future?

**Comment by alan-agius4** [comment]
Hi @blasco,

Thanks for opening this request.  Removing "dead-code" in HTML is currently not possible and currently not in roadmap of the Angular CLI to add this feature.

Let's re-consider this in the future.

Thanks.
