### ISSUE TITLE
Can't find name error when using ng serve

### ISSUE THREAD

**Issue by seklyza** [angular/angular-cli#1959]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 10

2. Versions. angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.1
os: win32 x64

3. Repro steps. The app is created using the CLI. I ran `ng init` and then when it finishes installing I ran `ng serve`, and I get some errors like `can't find name xxx`.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:26:29
Cannot find name 'Function'.

ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:31:25
Cannot find name 'Function'.

ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:35:21
Cannot find name 'Error'.

ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:40:35
Cannot find name 'Function'.

ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:52:50
Cannot find name 'Function'.

ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:60:33
Cannot find name 'RegExp'.

ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:110:24
Cannot find name 'Date'.

ERROR in [default] C:\Users\HOME\Desktop\newProj\node_modules\@types\jasmine\index.d.ts:123:52
Cannot find name 'Array'.
```

You got it... There are 491 errors like this.

5. Mention any other details that might be useful.

The application works fine. (I think, not sure, only has 1 component with `title = "app works!"`)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment]
Current solution is to downgrade to TypeScript 2.0.0 both globally and locally. See #1901 and #1917

To downgrade if you have TypeScript installed globally:
1. `npm uninstall -g typescript`
2. `npm install -g typescript@2.0.0`

To downgrade locally:
1. `npm uninstall typescript`
2. `npm install --save-dev typescript@2.0.0`

**Comment by seklyza** [comment]
Ok👌. Thank you. I will check if that works when I will be back home.

**Comment by seklyza** [comment]
@gelliott181, thank you very much you solved my problem.
