### ISSUE TITLE
Failing e2e tests are ignored

### ISSUE THREAD

**Issue by hansl** [angular/angular-cli#196]
For some reason if it doesn't build properly the build is still green.

**Comment by Brocco** [comment]
Agreed, this is a result of the expect inside the running of `ng build` only checking to see if the `dist` directory exists.

Well at least that's the main one right now

**Comment by filipesilva** [comment]
I think it runs a little bit more deep than that actually. For instance, here:

```
  it('Can run `ng build` in created project', function() {
    this.timeout(10000);

    return ng([
      'build',
      '--silent'
    ]).then(function() {
      expect(fs.existsSync(path.join(process.cwd(), 'dist')));
    });
  });
```

There should probably be a catch that failed the test, since it is possible for the build command to fail. I'm not completely sure that's how it works though...

**Comment by filipesilva** [comment]
I believe this is not fixed with the inclusion of `ng test` PR. Please reopen if this is inaccurate.

**Comment by Brocco** [comment]
There 2 things in play here...

- This particular test expectations have not been modified to fail if the build command fails.
- The scenario of the build failing is captured by the fact that the unit tests will fail

With that being said the answer that is needed to determine if this is an issue or not is how valid is the test which tests the build command?

Based on that answer we should take one of the following actions

- Delete the test
- Update the test to have appropriate expectations

**Reopening to decide on a direction**

**Comment by hansl** [comment]
If the build command fails, the promise should be failing. I'm testing this in a PR and will report.
