### ISSUE TITLE
Angular build no longer compiles nested scss while serve does

### ISSUE THREAD

**Issue by phenric** [angular/angular-cli#19612]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: I added new components and I wanted to build it as usual but it does not works as expected.

I noticed _@angular-devkit/build-angular_ was updated from ^0.1001.0 to ^0.1100.3 but even when I downgrade it nothing changes.

### Description

 As explained I added new components and I tested them with _ng serve_ (npm run start cfr. stackblitz) and all the nested scss were successfully compiled. Then I ran a new build (npm run build-i18n cfr. stackblitz) but unlike before and the serve, the nested scss were not compiled (they are not present in the browser developer console).

## 🔬 Minimal Reproduction

Please find as a minimal reproduction a [StackBlitz](https://stackblitz.com/edit/angular-ivy-a4bwgr) which works (StackBlitz logically uses serve?).

## 🌍 Your Environment
<pre><code>

Angular CLI: 10.2.0
Node: 12.18.3
OS: darwin x64

Angular: 10.1.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.0
@angular-devkit/build-angular      0.1100.4
@angular-devkit/core               10.1.0
@angular-devkit/schematics         10.2.0
@angular/cdk                       10.2.0
@angular/cli                       10.2.0
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.2.0
@angular/material-moment-adapter   10.2.0
@nguniversal/builders              10.1.0
@nguniversal/express-engine        10.1.0
@schematics/angular                10.2.0
@schematics/update                 0.1002.0
rxjs                               6.6.3
typescript                         4.0.2
webpack                            4.44.1
</code></pre>

I hope to be clear enough otherwise tell me ;)
Thank you!

**Comment by alan-agius4** [comment]
Hi @phenric,

I downloaded the stackblitz project you provided and was unable to replicate the reported issue.

I run the below
```
ng update @angular/cli --force
npm run build-i18n
// Had to add the locale files manually because it was not provided with the reproduction.
npx http-server dist
```

![Uploading Screenshot 2020-12-14 at 09.47.10.png…]()

**Comment by phenric** [comment]
Hi @alan-agius4,

Thank you for your answer!
I'm sorry for the locale files. I tried to understand why it works on your setup and not on mine and why serve works and build not.

Apparently, when Angular serves the project it manages the scss files differently than it does during the build. How does it really works? Are the scss files transformed to JS during the build?

My issue is solved, I adapted the scss files and now it works as expected.

Thanks again

**Comment by alan-agius4** [comment]
Hi @phenric,

Glad to hear you fixed the issue.

> Apparently, when Angular serves the project it manages the scss files differently than it does during the build. How does it really works? Are the scss files transformed to JS during the build?

The SCSS pipeline is shared between build and serve and hence there shouldn't be any differences. Yes, SCSS files are transformed into JS files after compilation into CSS. This is because Webpack only understands JavaScript input.
