### ISSUE TITLE
Unable to lint some specific files using ng lint --files 

### ISSUE THREAD

**Issue by dawood76** [angular/angular-cli#19623]
Hi,
I want to run lint only on some specific files and not the complete directory. 

I used this command to run ng lint on a specific file. 
npm run lint --files server.js

It lints all the files and not just server.js

Scripts in package.json:
![image](https://user-images.githubusercontent.com/73113095/102115262-221ae280-3e5d-11eb-8a9e-90a2b8fc1549.png)

The project is currently on angular 4.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
