### ISSUE TITLE
An unhandled exception occurred: UNKNOWN: unknown error, open/rmdir

### ISSUE THREAD

**Issue by pe2mbs** [angular/angular-cli#19636]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No, the previous version this bug was also present 6.x.x, but not reported

### Description
When executing ng build [--watch|--prod] this occurs regularly some times just one, or some times multiple times. With the error "An unhandled exception occurred: UNKNOWN: unknown error, open"
or "An unhandled exception occurred: ENOTEMPTY: directory not empty, rmdir"

## 🔬 Minimal Reproduction
On Windows 7 
In a small project it doesn't occur, i have a smaller project, only in my large project.  

## 🔥 Exception or Error
<pre><code>
[error] Error: ENOTEMPTY: directory not empty, rmdir 'C:\src\python\testrun-web\frontend-v8\dist\angular-testrun\assets\monaco\vs'
    at Object.rmdirSync (fs.js:684:3)
    at Observable.rxjs_1.Observable [as _subscribe] (C:\src\python\testrun-web\frontend-v8\node_modules\@angular-devkit\core\node\host.js:207:28)
    at Observable._trySubscribe (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\Observable.js:30:22)
    at C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
    at MergeMapSubscriber._next (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\Observable.js:30:22)
    at MergeMapOperator.call (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\operators\mergeMap.js:39:23)
    at Observable.subscribe (C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\Observable.js:25:31)
    at C:\src\python\testrun-web\frontend-v8\node_modules\rxjs\internal\util\subscribeTo.js:22:31
</code></pre>
OR 
<pre><code>
[error] Error: UNKNOWN: unknown error, open 'C:\src\python\testrun-web\frontend-v8\dist\angular-testrun\assets\python-powered-h.svg'
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.29
Node: 10.22.1
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.28
@angular-devkit/build-angular     0.803.28
@angular-devkit/build-optimizer   0.803.28
@angular-devkit/build-webpack     0.803.28
@angular-devkit/core              8.3.28
@angular-devkit/schematics        8.3.29
@angular/cdk                      8.2.3
@angular/cli                      8.3.29
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.28
@schematics/angular               8.3.29
@schematics/update                0.803.29
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
angular.json
<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "testrun-web": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "./dist/angular-testrun",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-monaco-editor/assets/monaco",
                "output": "/assets/monaco/"
              },
              {
                "glob": "**/*",
                "input": "node_modules/monaco-editor/min-maps",
                "output": "/assets/min-maps/"
              }
            ],
            "styles": [
              "src/styles.scss",
              "src/equensworldline.scss",
              "src/font.scss",
              "./node_modules/material-design-icons/iconfont/material-icons.css",
              "./node_modules/primeng/resources/themes/nova-light/theme.css",
              "./node_modules/primeng/resources/primeng.min.css",
              "./node_modules/primeicons/primeicons.css",
              "node_modules/prismjs/themes/prism-okaidia.css"
            ],
            "scripts": [
              "node_modules/ngx-monaco-editor/assets/monaco/vs/loader.js",
              "node_modules/marked/lib/marked.js",
              "node_modules/prismjs/prism.js",
              "node_modules/prismjs/components/prism-css.min.js"
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "6mb",
                  "maximumError": "8mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "512Kb",
                  "maximumError": "1Mb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "angular-testrun:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "angular-testrun:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "angular-testrun:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
                "src/styles.scss",
                "src/equensworldline.scss",
                "src/font.scss",
                "./node_modules/material-design-icons/iconfont/material-icons.css",
                "./node_modules/primeng/resources/themes/nova-light/theme.css",
                "./node_modules/primeng/resources/primeng.min.css",
                "./node_modules/primeicons/primeicons.css"
            ],
            "scripts": [
                "node_modules/ngx-monaco-editor/assets/monaco/vs/loader.js"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "angular-testrun:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "angular-testrun:serve:production"
            }
          }
        }
      }
    }},
  "defaultProject": "testrun-web"
}
</code></pre>

**Comment by alan-agius4** [comment]
Hi @pe2mbs,

Thanks for reporting this issue. Angular version 8 is no longer under support.  Please update to the most recent Angular CLI version currently being version 11.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by pe2mbs** [comment]
Hi alan-agius4,

No thanks for throwing it directly in trashcan, We have upgraded at the beginning of 2020 to Angular 8 and that quite the hassle, therefore upgrading to 11 just to find out if this silly bug is still there, is not worth the effort. 

I start to suspect that these exceptions are timing related, as the Windows instance runs on a VM-Ware farm, and as i stated before; it doesn't occur on a small project, as i tried already, it only happens on the large project.
