### ISSUE TITLE
ng version gives incorrect output

### ISSUE THREAD

**Issue by merrickfox** [angular/angular-cli#1963]
OS:  El Capitan
Cli version: angular-cli: 1.0.0-beta.11-webpack.8
Node version: v6.5.0

Running `ng version` in the project root of a project scaffolded with another version gives that version as it's output. This seems weird, as soon as you cd out you get the actual version.

I've spent the last 10 minutes wondering why I can't upgrade when actually it worked first time.

**Comment by hassanasad** [comment]
There are usually two angular-cli's installed.

One as global (npm install -g angular-cli) and the other one local in the project folder it self.

If you are upgrading, you will need to consider both.

**Comment by filipesilva** [comment]
Dupe https://github.com/angular/angular-cli/issues/1926, but @hassanasad is correct.
