### ISSUE TITLE
Security Vulnerability Issue

### ISSUE THREAD

**Issue by iadibar** [angular/angular-cli#19634]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Description

Im using `@angular/cli` package that dependent on `@schematics/update`. `@schematics/update` dependent on 
`ini version 1.3.5`.
when I scan my app (with Veracode sca) I getting Command Injection Vulnerability from `ini version 1.3.5`,
They suggest updating `ini` to version 1.3.6, so that it is not vulnerable version, but I can not do it in my code because the dependencies are inside your code so I'll be happy if you can update your `ini` version to 1.3.6 version (inside angular-`cli/integration/angular_cli/yarn.lock` && `@schematics/update -> ini`
dependency).

## 🔥 Exception or Error
<pre><code>
Prototype Pollution
ini is vulnerable to prototype pollution. An attacker is able to inject properties into existing construct prototypes and modify attributes such as `__proto__`, `constructor` and `prototype`.
</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**
screen shout from Veracode sca security scan:
you can see that they recommend to update `ini` version to fix this issue
![Image 16-12-2020 at 10 04](https://user-images.githubusercontent.com/36728277/102321249-0fe89380-3f86-11eb-8b4d-77bfa888f97a.jpg)

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/19594

The fix will be published on NPM in the coming days.

**Comment by iadibar** [comment]
@alan-agius4 thanks, there is an estimate date for the fix?

**Comment by iadibar** [comment]
@alan-agius4 I will just need to run `ng update @angular/core @angular/cli`?

**Comment by alan-agius4** [comment]
> @alan-agius4 I will just need to run ng update @angular/core @angular/cli?

Yes.

> @alan-agius4 thanks, there is an estimate date for the fix?

The release should happen later on today.

**Comment by shivanagendrakakumanu** [comment]
@alan-agius4 Any update on this. Im using Angular CLI: 9.1.1

**Comment by alan-agius4** [comment]
And LTS release for version 9 will be released later on today.

**Comment by shivanagendrakakumanu** [comment]
Thanks for the update, what are steps to update this for LTS v9.

**Comment by shivanagendrakakumanu** [comment]
Yeah i got,  i need to run command>  ng update @angular/cli@^9.1.1 @angular/core@^9.1.1 ?

**Comment by alan-agius4** [comment]
You can simply run 

`ng update @angular/cli@9 @angular/core@9`

**Comment by shivanagendrakakumanu** [comment]
Where can i see the updated status, whether it is released or not?

**Comment by alan-agius4** [comment]
You can check here: https://www.npmjs.com/package/@angular/cli and https://github.com/angular/angular-cli/releases

**Comment by iadibar** [comment]
@alan-agius4 any update about the new release with the fix?
