### ISSUE TITLE
Update CLI documentation for ng lint with eslint

### ISSUE THREAD

**Issue by tomhughes-invento** [angular/angular-cli#19638]
# 📚 Docs or angular.io bug report

### Description

After migrating a project from TSLint to ESLint (as the CLI now recommends on the latest version if you run `ng lint`, the options for the command are now slightly different. The docs for this needs updating to reflect the changes, as personally it took me much longer than it should have to find out that after migrating, `--files` no longer exists, and `--lint-file-patterns` must be used in its place.

## 🔬 Minimal Reproduction

Set up a project & follow the migration steps from the angular-eslint package for migrating

### Expected vs Actual Behavior**
Expected behavior:
The docs should either be changed to reflect the options available via ESLint, or the docs should have a new section for options when using ESLint

Actual Behavior:
The docs only show information for the command if you are using TSLint

## 🌍  Your Environment
MacOS High Sierra
Angular 11.0.3
Angular CLI 11.0.3

**Comment by alan-agius4** [comment]
`ng lint` is currently showing the options of the 1st party lint builder for TSlint.  angular-eslint builder is a 3rd party solution and users can choose to either use that or another. Hence, in this case I think we should update the docs to be in similar to [`ng deploy` ]( https://angular.io/cli/deploy)

Let me mark this for further discussion with the reset of the team.
