### ISSUE TITLE
CLI Doesn't Run

### ISSUE THREAD

**Issue by thatcort** [angular/angular-cli#19647]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [x] generate
- [x] add
- [x] update
- [x] lint
- [x] extract-i18n
- [x] run
- [x] config
- [x] help
- [x] version
- [x] doc

### Is this a regression?

Yes

### Description

I get the following error message when trying to run any CLI command: `Error: Cannot find module './debug'`

## 🔬 Minimal Reproduction

1. Uninstall any old version of the angular cli: `npm uninstall -g @angular/cli`
2. Install the angular cli: `npm i -g @angular/cli`
3. Attempt to create a new project: `ng new ngtest`

## 🔥 Exception or Error
<pre><code>
% npm uninstall -g @angular/cli
removed 254 packages in 2.482s
% npm i -g @angular/cli
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/briancort/.nvm/versions/node/v14.13.0/bin/ng -> /Users/briancort/.nvm/versions/node/v14.13.0/lib/node_modules/@angular/cli/bin/ng

> @angular/cli@11.0.5 postinstall /Users/briancort/.nvm/versions/node/v14.13.0/lib/node_modules/@angular/cli
> node ./bin/postinstall/script.js

+ @angular/cli@11.0.5
added 254 packages from 201 contributors in 8.359s
% ng new ngtest
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './debug'
Require stack:
- /usr/local/lib/node_modules/@angular/cli/node_modules/debug/src/node.js
- /usr/local/lib/node_modules/@angular/cli/node_modules/debug/src/index.js
- /usr/local/lib/node_modules/@angular/cli/node_modules/silent-error/index.js
- /usr/local/lib/node_modules/@angular/cli/utilities/app-utils.js
- /usr/local/lib/node_modules/@angular/cli/commands/build.js
- /usr/local/lib/node_modules/@angular/cli/lib/cli/index.js
- /usr/local/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:747:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@angular/cli/node_modules/debug/src/node.js:14:28)
    at Module._compile (internal/modules/cjs/loader.js:1085:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:791:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/@angular/cli/node_modules/debug/src/node.js',
    '/usr/local/lib/node_modules/@angular/cli/node_modules/debug/src/index.js',
    '/usr/local/lib/node_modules/@angular/cli/node_modules/silent-error/index.js',
    '/usr/local/lib/node_modules/@angular/cli/utilities/app-utils.js',
    '/usr/local/lib/node_modules/@angular/cli/commands/build.js',
    '/usr/local/lib/node_modules/@angular/cli/lib/cli/index.js',
    '/usr/local/lib/node_modules/@angular/cli/bin/ng'
  ]
}
</code></pre>

## 🌍 Your Environment
`ng version` generates the same error message as above. From the output you can see that it installed 11.0.5.

**Anything else relevant?**
I'm running Node v14.13.0, npm 6.14.8, MacOS 10.15.7

**Comment by clydin** [comment]
From the above log output, `npm` appears to have installed Angular CLI 11.0.5 into `/Users/briancort/.nvm/versions/node/v14.13.0/lib/node_modules/@angular/cli`.  However, the shell appears to have run `/usr/local/lib/node_modules/@angular/cli/bin/ng`.  The file `@angular/cli/utilities/app-utils.js` was present version 1.x and older version of the CLI.
What may be happening is that the `PATH` environment variable contains a referenced to the wrong Node.js installation.

**Comment by thatcort** [comment]
Thank you. I deleted a bunch of leftover global files and now things are working again.
