### ISSUE TITLE
Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by a0309nkita** [angular/angular-cli#19654]
Hi , 

I am trying to post some data to a server from my angular UI(6), but while calling that server I’m getting CORS error as 'Access to XMLHttpRequest at 'https://login.microsoftonline.com/********/oauth2/v2.0/token' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.'

Please provide any help on that and if more more data required I can provide that too.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
