### ISSUE TITLE
test won't end when npm test

### ISSUE THREAD

**Issue by calidion** [angular/angular-cli#19655]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 npm test won't end

## 🔬 Minimal Reproduction

ng new project-name
npm test/ ng test

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 12.19.0
OS: linux x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

![2020-12-21 15-15-47屏幕截图](https://user-images.githubusercontent.com/131776/102750045-1ae55e80-43a0-11eb-9ae8-3f7a5a72ac68.png)
![2020-12-21 15-21-52屏幕截图](https://user-images.githubusercontent.com/131776/102750147-48caa300-43a0-11eb-9a35-e66fdf323939.png)

**Comment by alan-agius4** [comment]
By default tests run in watch mode.

to disable watch mode, you can use the `—no-watch` command line argument.

More info about all the options can be found here: https://angular.io/cli/test

**Comment by calidion** [comment]
@alan-agius4 

you may help update the page, there is no option called `--no-watch`
in [https://angular.io/cli/test](https://angular.io/cli/test)

But the command line executed successfully with the option.

**Comment by alan-agius4** [comment]
You can use the`—no` prefix on any Boolean option to negate its value.

Ex: instead instead of `—-watch false` you can use `—-no-watch`

**Comment by calidion** [comment]
It is good to have the usage,  better if it is documented and best with examples.

**Comment by alan-agius4** [comment]
It is briefly mentioned here:
https://angular.io/cli#boolean-and-enumerated-options

**Comment by calidion** [comment]
It is `--noWatch` not `--no-watch`:)
