### ISSUE TITLE
`ng e2e` fetch the wrong webdriver

### ISSUE THREAD

**Issue by calidion** [angular/angular-cli#19671]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

`ng e2e` fails to run

## 🔬 Minimal Reproduction

ng new project-name
cd project-name
npm install
npm e2e/ ng e2e

## 🔥 Exception or Error
<pre><code>

[17:09:10] I/launcher - Running 1 instances of WebDriver
[17:09:10] I/direct - Using ChromeDriver directly...
[17:09:13] E/runner - Unable to start a WebDriver session.
[17:09:13] E/launcher - Error: SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 85.0.4183.83 with binary path /usr/bin/google-chrome
  (Driver info: chromedriver=87.0.4280.88 (89e2380a3e36c3464b5dd1302349b1382549290d-refs/branch-heads/4280@{#1761}),platform=Linux 5.4.0-47-generic x86_64)
    at Object.checkLegacyResponse (/home/eric/Sites/github.com/electron-angular/angular/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/eric/Sites/github.com/electron-angular/angular/node_modules/selenium-webdriver/lib/http.js:509:13)
    at /home/eric/Sites/github.com/electron-angular/angular/node_modules/selenium-webdriver/lib/http.js:441:30
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[17:09:13] E/launcher - Process exited with error code 100

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.5
Node: 12.19.0
OS: linux x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by jnizet** [comment]
AFAIU, the problem is not that the CLI fetches the wrong web driver, but rather than you're trying to test with an old version of Chrome. Upgrade your Chrome version.

**Comment by calidion** [comment]
what if the chrome can not be upgraded ?

**Comment by jnizet** [comment]
You would then test using another browser, or test inside a container where the latest Chrome can be installed. As a web developer, aren't you supposed to be able to install the latest version of Chrome, though? That seems like something you should be able to do.

**Comment by calidion** [comment]
Are you supposed to make a broken release?

**Comment by calidion** [comment]
I think you should have the ability to fix problems, instead of ignoring them and criticizing those who find them.

**Comment by jnizet** [comment]
@calidion I'm sorry and I apologize if you feel you've been criticized. 

I'm just a volunteer here, not part of the Google team which maintains the CLI. And my intention was not to ignore the issue, on the contrary: I answered it, by explaining you that you should upgrade your old Chrome version to be able to run your tests.

**Comment by calidion** [comment]
This issue is not about upgrading my chrome, but the release is inconsistent on it own.
The strategy to fetch the newest version instead of fetching the one matching the running environment makes it fail.
And the travis ci seems not support chrome by specific version.

**Comment by alan-agius4** [comment]
Hi @calidion, if you are not using the latest Chrome version (Which officially is not supported, https://angular.io/guide/browser-support), you'd need to disable to webdriver update when running the e2e and run webdriver-manager update manually specifying the chrome version that you use.

Example:
```
npx webdriver-manager update --gecko false --standalone false --versions.chrome 87.0.4280.20
ng e2e --no-webdriver-update
```

For more information run `npx webdriver-manager update help`

**Comment by calidion** [comment]
I think it is not a duty of users to keep the integrity of a tool which is granted all the privileges to auto generate very thing it can.
Users can adjust to what ever they want and responsible for what they have changed.
It can reject generating anything if the environmental conditions are not satisfied.
