### ISSUE TITLE
Improve favicon

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular-cli#19678]
# 🚀 Feature request
Update new angular app with proper favicon support

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
See link for details
https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

### Describe the solution you'd like
Generate application with multiple favicons to show proper way for the brand new apps

**Comment by alan-agius4** [comment]
Let's continue tracking this here: https://github.com/angular/angular-cli/issues/11275

> ### Description
> See link for details
> https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs
> 
> ### Describe the solution you'd like
> Generate application with multiple favicons to show proper way for the brand new apps
