### ISSUE TITLE
defaultProject field in angular.json doesnt seem to do it's job when running `ng g c xyz`

### ISSUE THREAD

**Issue by ORESoftware** [angular/angular-cli#19679]
# 🐞 Bug report

### Command (mark with an `x`)

ng generate

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure if it worked prior.

### Description

![Screen Shot 2020-12-24 at 8 52 53 PM](https://user-images.githubusercontent.com/11139560/103119881-2fd52280-462a-11eb-8cbb-d49ad057f4fc.png)

I get:

```
The generate command requires to be run in an Angular project, but a project definition could not be found.
```

however:

```
"defaultProject": "desktop-main"
```

is set in angular.json

## 🔥 Exception or Error
<pre><code>
The generate command requires to be run in an Angular project, but a project definition could not be found.

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.4
Node: 15.3.0
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.4 (cli-only)
@angular-devkit/core         11.0.4 (cli-only)
@angular-devkit/schematics   11.0.4 (cli-only)
@schematics/angular          11.0.4 (cli-only)
@schematics/update           0.1100.4 (cli-only)
    

</code></pre>

**Comment by alan-agius4** [comment]
It appears that you are running the generated command outside of the Angular workspace directory.

Kindly run the generate command in the workspace directory.
