### ISSUE TITLE
Angular: undefined ... Ivy Workspace: <error>

### ISSUE THREAD

**Issue by DenuwanG** [angular/angular-cli#19687]
Angular CLI: 11.0.5
Node: 15.5.0
OS: win32 x64

Angular: undefined                 
**Why is something like this happening? and how can I fix it?**
...
Ivy Workspace: <error>

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.5 (cli-only)
@angular-devkit/core         11.0.5 (cli-only)
@angular-devkit/schematics   11.0.5 (cli-only)
@schematics/angular          11.0.5 (cli-only)
@schematics/update           0.1100.5 (cli-only)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
