### ISSUE TITLE
Unknown error: Error: EPERM: operation not permitted, read

### ISSUE THREAD

**Issue by hellojt9040** [angular/angular-cli#19682]
Unable to run any ng commands. Reinstalled node , angular cli but getting the same issue.
I have also followed some threads but the issue is still there

![image](https://user-images.githubusercontent.com/41210284/103126615-dd8d1380-46b4-11eb-885e-fad156859706.png)

It's not even  npm err:,  it's just unknown.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
