### ISSUE TITLE
ng serve needs to be restarted after syntax error

### ISSUE THREAD

**Issue by dsl400** [angular/angular-cli#19683]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 do not know

### Description

saving a template with a syntax error will result in an unrecoverable error 
after correcting the syntax error a simple reload of the page is not enough and the server needs to be restarted

## 🔬 Minimal Reproduction

delete one curly bracket inside one template and save the file `{someVar}} `
put curly bracket back and save. 
it seams to happen only on templates that use pipes `*ngFor="let foo of {'a':1,'b':2'} | keyvalue" `
## 🔥 Exception or Error
<pre><code>

core.js:5973 ERROR Error: NG0302: The pipe 'keyvalue' could not be found!
    at getPipeDef$1 (core.js:25451)
    at Module.ɵɵpipe (core.js:25408)
    at SysmapExplorerComponent_Template (sysmap-explorer.component.html:16)
    at executeTemplate (core.js:9269)
    at renderView (core.js:9076)
    at renderComponent (core.js:10338)
    at renderChildComponents (core.js:8941)
    at renderView (core.js:9101)
    at TemplateRef.createEmbeddedView (core.js:22678)
    at ViewContainerRef.createEmbeddedView (core.js:22809)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.0.2
Node: 14.15.0
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.1
@angular/fire                   6.1.3
@angular/flex-layout            11.0.0-beta.33
@angular/material               11.0.1
@angular/service-worker         11.0.3
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem. See https://github.com/angular/angular/issues/39147#issuecomment-739094822

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
