### ISSUE TITLE
Error: Target is not defined for this project.

### ISSUE THREAD

**Issue by Sid13Kulat** [angular/angular-cli#19689]
Hello Everyone,

I am trying to create the "Web-Worker" in my angular project using angular-cli, but on cli it is giving me an error that "Target is not defined for this project".

Please check the below,

### Versions
**Node -v**
v12.16.1

**npm -v**
6.13.4

**ng version**

Angular CLI: 9.0.4
Node: 12.16.1
OS: win32 x64

**Angular: 9.0.4**
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

### Package Version
@angular-devkit/architect 0.900.4 (cli-only)
@angular-devkit/build-angular 0.900.4
@angular-devkit/build-optimizer 0.900.4
@angular-devkit/build-webpack 0.900.4
@angular-devkit/core 9.0.4 (cli-only)
@angular-devkit/schematics 9.0.4 (cli-only)
@angular/cdk 9.1.0
@angular/http 7.2.16
@angular/localize 9.0.5
@angular/material 9.1.0
@ngtools/webpack 9.0.4
@schematics/angular 9.0.4 (cli-only)
@schematics/update 0.900.4 (cli-only)
rxjs 6.5.4
typescript 3.7.5
webpack 4.41.2

### Steps to reproduce
Create a web worker using generate command,
**ng generate webWorker my-worker**

The log given by the failure
**Target is not defined for this project.**

Could anyone please tell me the solution about this? I am not getting the meaning of "Target".

Thank you.

**Comment by alan-agius4** [comment]
A target is an architect builder target that is used to build the application which is defined in your `angular.json`.

The default target value is `build` See: https://angular.io/cli/generate#web-worker, hence it means that in your project there is no build target.

Example of other targets are `build`, `lint`, `serve` etc.

**Comment by Sid13Kulat** [comment]
Hello @alan-agius4,

Thank you for the solution. I have generated the web-worker using following command with option "--project".

### **ng generate web-worker testworker --project=my-web-app

**CREATE e2e/tsconfig.worker.json (214 bytes)
CREATE src/app/testworker.worker.ts (157 bytes)
UPDATE src/tsconfig.app.json (233 bytes)
UPDATE angular.json (3853 bytes)****

Thank a lot. 👍
