### ISSUE TITLE
AngularJS => Angular migration and ng-annotate

### ISSUE THREAD

**Issue by dwilches** [angular/angular-cli#19692]
# 🚀 Feature request

### Description

Pretty much these other issues explain the motivations for my feature request: https://github.com/angular/angular-cli/issues/6873 by @yjaaidi and https://github.com/angular/angular-cli/issues/3722 by @Itrulia

I'm migrating an app from AngularJs to Angular, and even when building for production I'm needing to specify `--optimization=false` because otherwise, the AngularJs parts of my app won't work. The reason is when using Angular CLI there is no way of including `ng-annotate` as part of the pipeline for the AngularJs bits.

What is the 2021 way of using ng-annotate for hybrid applications?

Thanks.

### Describe the solution you'd like
I would like a "plugins" section where I could specify "ng-annotate" and only for files that match a regex (the AngularJs files).

### Describe alternatives you've considered
I've considered:
1. **Ejecting the configuration and not using ng-cli.** I don't like this solution as I want to use Angular CLI and reduce customizations (so upcoming upgrades are smoother).
1. **Running ng-annotate on each of the Angular files by hand, and permanently replacing the original files.** But it's rather involved, I'd need to write a script that:
    - Removes the imports from the top of my files (because ng-annotate doesn't like "imports/exports" in non-module files).
    - Runs ng-annotate in each one, redirecting the output to a file, then swapping the files.
1. **Continuing to use the non-optimized version of my product in production**. My company's product is quite large, and it is taking several seconds to download and bootstrap, so this is exactly what I want to avoid.
1. **Using a custom webpack config prepended to ng-cli's one.** I found it [here](https://stackoverflow.com/questions/59302237/how-to-use-ng-annotate-with-hybrid-app-based-on-angular-cli).

So far it looks like number 4 is what I'm going to try, otherwise doing number 2. Unless there is already a better solution I have not considered.

**Comment by dwilches** [comment]
After looking around, I found the best solution for me was to use [babel-plugin-angularjs-annotate](https://www.npmjs.com/package/babel-plugin-angularjs-annotate), which does something similar to what I mentioned before in option 2, but better:

- Create a new project
- Install babel and babel-plugin-angularjs-annotate
- Execute `npx babel src -d output`

That's it, it will take the files from `src`, add the annotations, and put the result in the folder `output`.

For others needing the complete solution, this is what I exeucted:

- `mkdir babel-setup-with-babel-cli && cd babel-setup-with-babel-cli`
- `npm init -y`
- `npm install -D babel-cli babel-plugin-angularjs-annotate`
- Add this to `.babelrc`:
```
{
  "presets": [],
  "plugins": [ "angularjs-annotate" ]
}
```
- `npx babel src -d build`

**Comment by alan-agius4** [comment]
Hi, 

You can use 3rd party solutions such as https://github.com/manfredsteyer/ngx-build-plus and https://www.npmjs.com/package/@angular-builders/custom-webpack to extend the Angular CLI and add custom Babel and Webpack plugins in the build pipeline. 

While, we extending the CLI is allowed, this is not supported by the Angular tooling team.
