### ISSUE TITLE
Resolve ~ to node_modules universally (Also in ng-packagr)?

### ISSUE THREAD

**Issue by fireflysemantics** [angular/angular-cli#19703]
In sass we can do this:

```
@import ~/somepackage.css
```

Instead of:

```
@import ../../../../../../somepackage.css
```

But we can't do this (For example):

```
  styleUrls: ['~@fireflysemantics/help-center-css/components/topic-meta.component.css']

```

We have to do this:

```
  styleUrls: ['../../../../node_modules/@fireflysemantics/help-center-css/components/topic-meta.component.css']
```

It would be nice if we could use `~` throughout as something that just points to `node_modules` ...

**Comment by alan-agius4** [comment]
Hi @fireflysemantics,

Thanks for this feature request.

I don't see that this will bring a lot of added value for the community as typically component stylesheets are not shipped as seperate CSS files in `node_modules`.

It is also worth mentioning that the tilda resolve `~/` is a Webpack feature which is non standard resolution behaviour.

Let's reconsider this in the future if we see a bigger demand for this feature.

Thanks for your understanding.
