### ISSUE TITLE
Display TimeSpan type Data in Angular

### ISSUE THREAD

**Issue by slm-w** [angular/angular-cli#19718]
Trying to show time in table but it shows me time in this format { "ticks": 690680000000, "days": 0, "hours": 19, "milliseconds": 0, "minutes": 11, "seconds": 8, "totalDays": 0.7993981481481481, "totalHours": 19.185555555555556, "totalMilliseconds": 69068000, "totalMinutes": 1151.1333333333334, "totalSeconds": 69068 } while i want it to be displayed in this format "10:15:20" 
Html
  <ng-container matColumnDef="debutJour">
        <th mat-header-cell *matHeaderCellDef mat-sort-header>
          {{'::DebutJour' | abpLocalization}}
        </th>
        <td mat-cell *matCellDef="let element">
          {{ element.debutJour|json }}
        </td>
      </ng-container>
      <ng-container matColumnDef="duree">
        <th mat-header-cell *matHeaderCellDef mat-sort-header>
          {{'::Duree' | abpLocalization}}
        </th>
        <td mat-cell *matCellDef="let element">
          {{ element.duree|json }}
        </td>
      </ng-container>

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
