### ISSUE TITLE
Css variable in dev mode become shortened

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular-cli#19712]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build
- [x] serve

### Description
I'm using css variables for colors.
for example:
```
:root {
--s1-N-0-color: #FFFFFF;
}
```

in prod mode it become shortened; 
```
:root {
--s1-N-0-color: #fff;
}
```

In dev mode is work as expected and it keep the hex as is.

## 🔬 Minimal Reproduction
1. Create a new angular cli project 
2. Add to styles.scss 
```
:root {
--s1-N-0-color: #FFFFFF;
}
```

3. server the project in dev mode 
4. open the browser and in the dev tools you can see the hex color changed to #fff

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.0.5
Node: 12.3.1
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/material               11.0.3
@nguniversal/express-engine     10.1.0
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by alan-agius4** [comment]
This is expected since when using the "optimization" option CSS is compressed and one these compressions is to shorthand colors to remove redundant characters.

 `#FFFFFF` is the same as `#fff`

**Comment by ofirrifo** [comment]
@alan-agius4 the issue with this is we using this js code 
```
getComputedStyle(document.documentElement).getPropertyValue(colorName)
```

and pass to a third party the hex color which is throw exception when we pass the  shorthand color 

can I use the optimization with a flag that tell the cli not to include color shorthand?

**Comment by alan-agius4** [comment]
> can I use the optimization with a flag that tell the cli not to include color shorthand?

The only way to do it is to disable style optimizations completely. See: https://next.angular.io/guide/workspace-config#optimization-configuration

I suggest to open an issue with the author of the 3rd party library since it doesn't handle valid shorthand colors.
