### ISSUE TITLE
Support custom chunks for webpack / separate chunks for in-house libraries

### ISSUE THREAD

**Issue by arobinson** [angular/angular-cli#19721]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
 A clear and concise description of the problem or missing capability...
We do most of our component development in an Angular library. That library is linked via package.json (local file reference as it is in a mono-repo style git repository). This library is quite large and it takes time for webpack to re-pack it. The contents get put into `vendor.js` as we have `vendorChunk` set to true. It would be nice to be able to have our library be able to be put in its own chunk file so that the vendor chunk rarely ever changes during a release (it is uncommon for us to change other packages during a release).

While this may be possibly using tools like `@angular-builders/custom-webpack:browser` it would be nice to have greater customization of the chunks that are created via the core builder and angular.json.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
New `additionalChunks` section of angular.json configuration for the `@angular-devkit/build-angular:browser` builder.
It would allow glob matching to customize the chunks.

```
"additionalChunks": {
    "myLib": [ "node_modules/myLib/**" ]
}
```

This would package the "myLib" Angular library as "myLib.[hash].js" in the output of ng build (and a separate file for serve)

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
`@angular-builders/custom-webpack:browser`

**Comment by alan-agius4** [comment]
Hi @arobinson,

Thanks for this feature request. That said in this case using 3rd party extension that enhances the Angular CLI seems to be the reasonable thing to do.

It's also important to highlight that `vendorChunk` is meant to be used only during development, as using this for production build will cause optimization bailouts especially when using lazy-loading.

Thanks.
