### ISSUE TITLE
ng test  gives 0 coverage (not all the time)

### ISSUE THREAD

**Issue by Shashidharpatil96** [angular/angular-cli#19739]
# 🐞 Bug report

- [x] test
- [ ] config

### Description

I can see this kind of result after every 4 builds in the jenkin.

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================

## 🔥 Exception or Error
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: "",
    frameworks: ["jasmine", "@angular-devkit/build-angular"],
    plugins: [
      require("karma-jasmine"),
      require("karma-coverage"),
      require("karma-junit-reporter"),
      require("karma-chrome-launcher"),
      require("karma-jasmine-html-reporter"),
      require("karma-coverage-istanbul-reporter"),
      require("@angular-devkit/build-angular/plugins/karma"),
	  require("karma-sonarqube-unit-reporter"),
    ],
    client: {
      clearContext: false, // leave Jasmine Spec Runner output visible in browser
    },
	sonarQubeUnitReporter: {
      sonarQubeVersion: "LATEST",
      outputFile: "./coverage/reports/ut_report.xml",
      overrideTestDescription: true,
      testPaths: ["./src"],
      testFilePattern: ".spec.ts",
      useBrowserName: false,
    },
    customLaunchers: {
      ChromeHeadlessNoSandbox: {
        base: "ChromeHeadless",
        flags: ["--no-sandbox"],
      },
    },
    coverageIstanbulReporter: {
      dir: require("path").join(__dirname, "./coverage/oscare-idm-frontend"),
      reports: ["html", "lcovonly", "cobertura", "text-summary"],
      "report-config": {
        cobertura: {
          file: "cobertura.xml",
        },
      },
      fixWebpackSourcePaths: true,
    },
    reporters: ["sonarqubeUnit"],
    junitReporter: {
      outputDir: "test-results",
      outputFile: "unit-test-results.xml",
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ["ChromeHeadlessNoSandbox"],
    singleRun: true,
    restartOnFileChange: true,
  });
};

## 🌍 Your Environment

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.28
Node: 10.16.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.28
@angular-devkit/build-angular              0.803.28
@angular-devkit/build-optimizer            0.803.28
@angular-devkit/build-webpack              0.803.28
@angular-devkit/core                       8.3.28
@angular-devkit/schematics                 8.3.28
@angular/cdk                               8.2.3
@angular/cli                               8.3.28
@angular/http                              7.2.16
@angular/material                          8.2.3
@ngtools/webpack                           8.3.28
@nguniversal/common                        8.2.6
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.28
@schematics/update                         0.803.28
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2

**Comment by alan-agius4** [comment]
Hi @Shashidharpatil96,

Thanks for opening this issue. However, Angular CLI version 8 is no longer supported. Please update to the most recent version.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
