### ISSUE TITLE
No component or global styling works after porting components from ng 8 to ng 11 and converting components from css -> scss

### ISSUE THREAD

**Issue by jpcarnes** [angular/angular-cli#19748]
# 🐞 Bug report

### Command

- [`x`] serve

### Is this a regression?

Project components and styling worked on a previous angular 8 repo with the same components but problem started happening after updating cli and core to latest (11).

### Description

Had an ng 8 repo with existing components that were using global and component level css for styling. Needed to add these same components to a monorepo (ng11 and nativecript 7) that by default was set to use .scss for all styles.

I manually ported over the files by adding new folders/files in the code base and set the extension for all component styling files to be .scss then copy and pasted over the css from my ng 8 project.

After doing all this and running ng serve in my monorepo none of my component or global styles are showing up when I compile. I am using reset.scss in the code base as well.

Another dev on my team has pulled down my same branch and compiled with no issues and all his styling at the component and global levels are working correctly, which lead us to believe it is an issue with my local machine. 

Possibly something with cli and the fact that I previously was working in .css projects then switched to .scss?

## 🔬 Minimal Reproduction

Create a .css ng 8 project and add some basic styling. Then port over that styling to a separate new ng11/ns monorepo project that uses .scss by manually creating the component folders and files then copy and pasting .css from ng 8 project in and run ng serve.

## 🌍 Your Environment
<pre><code>

Node: 15.4.0
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@angular/cdk                    11.0.3
@angular/fire                   6.1.4
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

Below is my angular.json and package.json files:

**angular.json:**

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "project-sandobox": {
      "projectType": "application",
      "schematics": {},
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/project-sandobox",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "project-sandobox:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "project-sandobox:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "project-sandobox:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "project-sandobox:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "project-sandobox:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "project-sandobox",
  "cli": {
    "defaultCollection": "@nativescript/schematics"
  }
}

-----------------------------------------------------------------------------------------------------------------------

**package.json:**

{
  "name": "project-sandbox",
  "version": "0.0.1",
  "private": true,
  "main": "main.tns.js",
  "scripts": {
    "android": "ns run android --no-hmr",
    "build": "ng build",
    "e2e": "ng e2e",
    "ios": "ns run ios --no-hmr",
    "lint": "ng lint",
    "mobile": "ns run",
    "ng": "ng",
    "start": "ng serve",
    "test": "ng test"
  },
  "dependencies": {
    "@angular/animations": "~11.0.5",
    "@angular/cdk": "~11.0.3",
    "@angular/common": "~11.0.5",
    "@angular/compiler": "~11.0.5",
    "@angular/core": "~11.0.5",
    "@angular/fire": "^6.1.4",
    "@angular/forms": "~11.0.5",
    "@angular/material": "^11.0.3",
    "@angular/platform-browser": "~11.0.5",
    "@angular/platform-browser-dynamic": "~11.0.5",
    "@angular/router": "~11.0.5",
    "@mapbox/mapbox-sdk": "^0.10.0",
    "@nativescript/angular": "~10.1.0",
    "@nativescript/camera": "^5.0.2",
    "@nativescript/core": "~7.0.11",
    "@nativescript/firebase": "^11.0.0",
    "@nativescript/geolocation": "^7.0.0",
    "@nativescript/imagepicker": "^1.0.0",
    "@nativescript/iqkeyboardmanager": "^2.0.0",
    "@nativescript/secure-storage": "^3.0.0",
    "@nativescript/theme": "^2.5.0",
    "@nstudio/nativescript-pulltorefresh": "^3.0.1",
    "@nstudio/nativescript-snackbar": "^2.1.0",
    "@turf/bbox": "^6.0.1",
    "@turf/turf": "^5.1.6",
    "@types/intro.js": "^2.4.6",
    "@types/jquery": "^3.3.34",
    "aws-sdk": "^2.623.0",
    "base64-img": "^1.0.4",
    "chart.js": "^2.9.3",
    "exceljs": "^4.2.0",
    "exifr": "^5.0.3",
    "file-saver": "^2.0.2",
    "firebase": "^7.14.0",
    "firebase-tools": "^8.2.0",
    "hammerjs": "^2.0.8",
    "intro.js": "^2.9.3",
    "jquery": "^3.5.1",
    "jspdf": "^2.1.0",
    "madge": "^3.12.0",
    "mapbox-gl": "^1.10.0",
    "nativescript": "^7.0.8",
    "nativescript-drop-down": "^5.0.6",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-modal-datetimepicker-ns-7": "^12.0.1",
    "nativescript-ngx-fonticon": "^7.0.0",
    "nativescript-numeric-keyboard": "^5.0.0",
    "nativescript-ui-listview": "^9.0.2",
    "ng2-charts": "^2.3.0",
    "ng2-opd-popup": "^1.1.21",
    "ngx-mapbox-gl": "^4.5.0",
    "node-sass": "^5.0.0",
    "pdfmake": "^0.1.69",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.6.0",
    "rxjs-compat": "^6.6.3",
    "save": "^2.4.0",
    "tslib": "^2.0.0",
    "turf-extent": "^1.0.4",
    "underscore": "^1.10.2",
    "xlsx": "^0.16.1",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.5",
    "@angular/cli": "^11.0.5",
    "@angular/compiler-cli": "~11.0.5",
    "@angular/language-service": "~11.0.5",
    "@nativescript/ios": "7.0.6",
    "@nativescript/schematics": "^10.1.0",
    "@nativescript/tslint-rules": "~0.0.5",
    "@nativescript/webpack": "~3.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/mapbox-gl": "^0.51.10",
    "@types/node": "^12.19.11",
    "codelyzer": "^6.0.0",
    "file-system": "^2.2.2",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "prettier": "2.2.1",
    "protractor": "~7.0.0",
    "sass": "^1.27.1",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "tslint-config-prettier": "^1.14.0",
    "tslint-loader": "^3.6.0",
    "tslint-plugin-prettier": "^1.3.0",
    "typescript": "~4.0.2"
  }
}

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
