### ISSUE TITLE
visitJsonSchema bugs lead to unflattened JSON Schema

### ISSUE THREAD

**Issue by bgotink** [angular/angular-cli#19751]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, this code hasn't been changed in at least a year.

### Description

There are two issues in the `visitJsonSchema` function:

- The `visitJsonSchema` function incorrectly handles `'items'` property as a part of `propsKeywords` while it should be `keywords`. It's already present in `keywords`, but overruled due to `propsKeywords`.
  https://github.com/angular/angular-cli/blob/b3ed8aa4ad6736130bd9603ebf681b229c16f2b2/packages/angular_devkit/core/src/json/schema/visitor.ts#L169-L176
  https://github.com/angular/angular-cli/blob/b3ed8aa4ad6736130bd9603ebf681b229c16f2b2/packages/angular_devkit/core/src/json/schema/visitor.ts#L153-L156
- The visitor passes the grandparent schema object rather than the parent schema when visiting any of the `propsKeywords` values (`sch` vs. `schema` at line 197).
  https://github.com/angular/angular-cli/blob/b3ed8aa4ad6736130bd9603ebf681b229c16f2b2/packages/angular_devkit/core/src/json/schema/visitor.ts#L189-L201
  This breaks the visitor in flatten as it tries to replace a `$ref` with the value it references:
  https://github.com/angular/angular-cli/blob/b3ed8aa4ad6736130bd9603ebf681b229c16f2b2/packages/angular_devkit/core/src/json/schema/registry.ts#L288

These two bugs each lead to `CoreSchemaRegistry#flatten` not actually flattening properties inside items.

## 🔬 Minimal Reproduction

Executing the following file will print `{ '$ref': '#/definitions/pattern' }`

<details><summary>Toggle file</summary>

```js
const {json} = require('@angular-devkit/core');

const registry = new json.schema.CoreSchemaRegistry();

registry
  .flatten({
    type: 'object',
    properties: {
      assets: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            include: {
              $ref: '#/definitions/pattern',
            },
            exclude: {
              $ref: '#/definitions/pattern',
            },
          },
        },
      },
    },
    definitions: {
      pattern: {
        oneOf: [
          {
            type: 'string',
          },
          {
            type: 'array',
            items: {
              type: 'string',
            },
          },
        ],
      },
    },
  })
  .subscribe(flattened => {
    console.log(flattened.properties.assets.items.properties.include);
  });
```

## 🔥 Exception or Error

ø

## 🌍 Your Environment

Present on master, tested on 11.0.5.

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @bgotink,

Thanks for great investigation. 

The `flatten` schema method has been deprecated without replacement, as producing a flatten schema document does not in all cases produce a schema with identical behavior to the original.

See: https://json-schema.org/draft/2019-09/json-schema-core.html#rfc.appendix.B.2
