### ISSUE TITLE
PWA manifest 404

### ISSUE THREAD

**Issue by rudyhadoux** [angular/angular-cli#19763]
Hi,

There is a 404 problem with manifest.

GET http://localhost:4200/manifest.webmanifest 404 (Not Found).

When :
ng new app && cd app && ng add @angular/pwa --project app && ng s

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by rudyhadoux** [comment]
No thanks. I have put all the necessary information for this problem.

**Comment by alan-agius4** [comment]
I am unable to reproduce with the step provided.

**Comment by rudyhadoux** [comment]
It is easy.
ng new app && cd app && ng add @angular/pwa --project app && ng s

**Comment by rudyhadoux** [comment]
Sorry this is my mistake.
It is just that PWA is not available with "ng serve".

**Comment by alan-agius4** [comment]
That is expected.

Kindly see this feature request https://github.com/angular/angular-cli/issues/9869

**Comment by rudyhadoux** [comment]
This feature would be a good thing.
