### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@angular/compiler-cli/src/tooling'

### ISSUE THREAD

**Issue by naman-cmd** [angular/angular-cli#19776]
I have an issue while compiling angular code.

An unhandled exception occurred: Cannot find module '@angular/compiler-cli/src/tooling'
Require stack:
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\node_modules\@ngtools\webpack\src\index.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\src\webpack\configs\typescript.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\src\webpack\configs\index.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\src\utils\package-chunk-sort.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\src\utils\index-file\write-index-html.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\architect\node\index.js
- C:\LRSUI\lrs-ui\node_modules\@angular\cli\models\architect-command.js
- C:\LRSUI\lrs-ui\node_modules\@angular\cli\commands\serve-impl.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\LRSUI\lrs-ui\node_modules\@angular-devkit\schematics\tools\index.js
- C:\LRSUI\lrs-ui\node_modules\@angular\cli\utilities\json-schema.js
- C:\LRSUI\lrs-ui\node_modules\@angular\cli\models\command-runner.js
- C:\LRSUI\lrs-ui\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\nsharm13\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\nsharm13\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\nsharm13\AppData\Local\Temp\ng-fTiDHV\angular-errors.log" for further details.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
