### ISSUE TITLE
ng serve --port 8081 stopper working

### ISSUE THREAD

**Issue by darxx** [angular/angular-cli#19775]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
Version 11.0.0
Start noticing this in angular 11.0.1

From error logs what I can see:
npm-cache\_logs starter from 2021-01-05 - 2021-01-12 and it happens 3/5 times a day.

### Description

 A clear and concise description of the problem...
After working for a long time on a project that has around 66k of code
38k TypeScript
21k HTML
6.8k CSS - SASS

## 🔬 Minimal Reproduction
<pre>
<code>
ng serve --port 8081 |
ng test --code-coverage --source-map=false 
npx ng run aca:eslint && stylelint "src/**/*.scss" --syntax scss && htmlhint "src" --config .htmlhintrc 
</code></pre>
  was working side by side.
And I was writing unit test. Running Lint. And fixing bugs. 

## 🔥 Exception or Error
<pre>
<--- Last few GCs --->

[6572:000002552161DB90]  9758552 ms: Mark-sweep 2025.9 (2051.5) -> 2024.9 (2051.5) MB, 800.3 / 0.1 ms  (average mu = 0.134, current mu = 0.036) allocation failure scavenge might not succeed
[6572:000002552161DB90]  9759678 ms: Mark-sweep 2027.1 (2052.8) -> 2025.5 (2052.0) MB, 1121.9 / 0.1 ms  (average mu = 0.073, current mu = 0.003) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF75C14B49D]
Security context: 0x01388fd408d1 <JSObject>
    1: /* anonymous */ [0000021FB7221A31] [C:\www\ca-ang\node_modules\webpack\node_modules\source-map\lib\source-node.js:~342] [pc=000002DA489A6EA9](this=0x00ab25ebfc61 <GlobalObject Object map = 000000AEF0AD2B89>,0x0340d68f0799 <String[3]:  = >,0x00aaf48a7179 <Obje
ct map = 0000039A05233519>)
    2: SourceNode_walk [0000023C38599859] [C:\www\ca-ang\node_mo...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF75B535F0F napi_wrap+114095
 2: 00007FF75B4E0B96 v8::base::CPU::has_sse+66998
 3: 00007FF75B4E1996 v8::base::CPU::has_sse+70582
 4: 00007FF75BCF6E9E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF75BCDEF71 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF75BBAB1DC v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF75BBB6410 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF75BBB2F34 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF75BBA8733 v8::internal::Heap::CollectGarbage+1283
10: 00007FF75BBA6DA4 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF75BBC80ED v8::internal::Factory::NewFillerObject+61
12: 00007FF75B92E231 v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1665
13: 00007FF75C14B49D v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 000002DA489A6EA9
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! aca@2.11.0 heficed: `ng serve --port 8081`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the aca@2.11.0 heficed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\darius.l\AppData\Roaming\npm-cache\_logs\2021-01-05T13_25_36_084Z-debug.log

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.2
Node: 12.18.4
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@angular/cdk                    11.0.1
@angular/material               11.0.1
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

npm-cache\_logs
2021-01-12T11_10_06_784Z-debug.log from other day.
<pre>
<code>
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\darius.l\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.18.4
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle aca@2.11.0~prelint: aca@2.11.0
6 info lifecycle aca@2.11.0~lint: aca@2.11.0
7 verbose lifecycle aca@2.11.0~lint: unsafe-perm in lifecycle true
8 verbose lifecycle aca@2.11.0~lint: PATH: C:\Users\darius.l\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\www\ca-ang\node_modules\.bin;C:\www\ca-ang\node_modules\.bin;C:\Python38\Scripts\;C:\Python38\;C:\Python27\;C:\Python27\Scripts;C:\Program Files\AdoptOpenJDK\jre-11.0.3.7-hotspot\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\PuTTY\;C:\sonar-scanner\sonar-scanner-3.3.0.1492-windows\bin;C:\Program Files (x86)\WinMerge;C:\Program Files\OpenVPN\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\darius.l\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PhpStorm 2019.1.1\bin;;C:\Users\darius.l\AppData\Local\Gource\cmd;C:\ProgramData\chocolatey\lib\msys2;C:\tools\msys64;C:\Users\darius.l\AppData\Local\Programs\Fiddler;C:\Users\darius.l\AppData\Local\Microsoft\WindowsApps;C:\Users\darius.l\AppData\Roaming\npm
9 verbose lifecycle aca@2.11.0~lint: CWD: C:\www\ca-ang
10 silly lifecycle aca@2.11.0~lint: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npx ng run aca:eslint && stylelint "src/**/*.scss" --syntax scss && htmlhint "src" --config .htmlhintrc'
10 silly lifecycle ]
11 silly lifecycle aca@2.11.0~lint: Returned: code: 1  signal: null
12 info lifecycle aca@2.11.0~lint: Failed to exec lint script
13 verbose stack Error: aca@2.11.0 lint: `npx ng run aca:eslint && stylelint "src/**/*.scss" --syntax scss && htmlhint "src" --config .htmlhintrc`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\darius.l\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\darius.l\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid aca@2.11.0
15 verbose cwd C:\www\ca-ang
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\darius.l\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
18 verbose node v12.18.4
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error aca@2.11.0 lint: `npx ng run aca:eslint && stylelint "src/**/*.scss" --syntax scss && htmlhint "src" --config .htmlhintrc`
22 error Exit status 1
23 error Failed at the aca@2.11.0 lint script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

</code>
</pre>
If I can provide some debug information. Please let me know. After staring ng serve. For now I just restart service. And can work.

**Comment by alan-agius4** [comment]
As the application grows so does the memory requirements. By default Node.js has a default max memory usage of less than 2GB on some 64bit systems. 

It's possible to adjust the max memory ceiling using a command line flag passed into node:

```
node --max_old_space_size= 4096 node_modules/@angular/cli/bin/ng serve
```

That said, in order for us to investigate any potential leak. We'd require a reproduction.

**Comment by darxx** [comment]
For production build we already using 
<pre><core>
node --max-old-space-size=12096 ./node_modules/@angular/cli/bin/ng ...
</code></pre>

As I understand solution is to run 
<pre><core>
node --max_old_space_size= 12096 node_modules/@angular/cli/bin/ng serve ....
</code></pre>
on local environment also.

Thank You.

If I can provide debugging data let me know.

**Comment by alan-agius4** [comment]
@darxx, without a reproduction it’s hard to see what is happening.

if you want to debug yourself, you can try to take memory heap snapshots and see where the extra memory usage is being consumed/retained.

**Comment by darxx** [comment]
Thank You. This issue can be close.
