### ISSUE TITLE
Serving application with bazel run doesn't build dependent library

### ISSUE THREAD

**Issue by templth** [angular/angular-cli#19779]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I have a monorepo containing an Angular application (called `app`) and an Angular library (called `lib`). Bazel is configured and we can build the application using the following command:

```
$ bazel build angular/app:build
(...)
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

However, serving the application with the following command fails because the library can't be resolved:

```
$ bazel run angular/app:serve
(...)
INFO: Analyzed target //angular/app:serve (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //angular/app:serve up-to-date:
  bazel-bin/angular/app/serve.sh
  bazel-bin/angular/app/serve_loader.js
  bazel-bin/angular/app/serve_require_patch.js
INFO: Elapsed time: 0.564s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
```

The errors correspond to imports of elements contained in the library `lib` the application relies on.

```
app:serve: 
ERROR in angular/app/src/app/core/components/app/app.component.ts:2:45 - error TS2307: Cannot find module 'lib' or its corresponding type declarations.

2 import { InternationalizationService } from 'lib';
                                              ~~~~~
angular/app/src/app/core/components/auth/confirm-email/confirm-email.component.ts:3:29 - error TS2307: Cannot find module 'lib' or its corresponding type declarations.

(...)
```

Our Bazel configuration is based on the one in this project: https://github.com/bazelbuild/rules_nodejs/blob/master/examples/angular_bazel_architect/BUILD.bazel#L13

## 🌍 Your Environment

<pre><code>
$ ng version

Angular CLI: 10.2.1
Node: 12.19.1
OS: linux x64

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1002.1
@angular-devkit/architect-cli      0.1002.1
@angular-devkit/build-angular      0.1002.1
@angular-devkit/core               10.2.1
@angular-devkit/schematics         10.2.1
@angular/cdk                       10.2.7
@angular/cli                       10.2.1
@angular/material                  10.2.7
@angular/material-moment-adapter   10.2.7
@bazel/bazelisk                    1.7.3
@bazel/ibazel                      v0.14.0
@bazel/rollup                      3.0.0
@bazel/typescript                  3.0.0
@bazel/worker                      3.0.0
@schematics/angular                10.2.1
@schematics/update                 0.1002.1
ng-packagr                         10.1.2
rxjs                               6.6.3
typescript                         4.0.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi, Angular bazel is no longer supported by the Angular tooling team. Please see: https://dev.to/bazel/angular-bazel-leaving-angular-labs-51ja

Kindly open an issue in https://github.com/bazelbuild/rules_nodejs

**Comment by templth** [comment]
@alan-agius4 thanks very much for your answer!
