### ISSUE TITLE
extract-i18n error with @ngtools/webpack & webpack5

### ISSUE THREAD

**Issue by nbyavuz** [angular/angular-cli#19774]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: webpack4 & angular9-10

### Description
When I tried to extract-i18n with angular11 & webpack5, it gives that errors.

## 🔥 Exception or Error
<pre><code>

node_modules/@ngtools/webpack/src/angular_compiler_plugin.d.ts:62:29 - error TS2503: Cannot find namespace 'compilation'.

62         parentCompilation?: compilation.Compilation;
                               ~~~~~~~~~~~
node_modules/@ngtools/webpack/src/loader.d.ts:1:10 - error TS2305: Module '"../../../webpack/types"' has no exported member 'loader'.

1 import { loader } from 'webpack';
           ~~~~~~
node_modules/@ngtools/webpack/src/ngcc_processor.d.ts:9:10 - error TS2305: Module '"../../../webpack/types"' has no exported member 'InputFileSystem'.

9 import { InputFileSystem } from 'webpack';
           ~~~~~~~~~~~~~~~
node_modules/@ngtools/webpack/src/webpack.d.ts:8:10 - error TS2305: Module '"../../../webpack/types"' has no exported member 'InputFileSystem'.

8 import { InputFileSystem } from 'webpack';
           ~~~~~~~~~~~~~~~
node_modules/@ngtools/webpack/src/virtual_file_system_decorator.d.ts:11:10 - error TS2305: Module '"../../../webpack/types"' has no exported member 'InputFileSystem'.

11 import { InputFileSystem } from 'webpack';


</code></pre>


## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.5
Node: 12.14.1
OS: linux x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/fire                   6.1.4
@ngtools/webpack                11.0.5 // same on 11.0.6
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
webpack                         5.13.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi, 

Are you using a custom build pipeline or using `@ngtools/webpack` directly? If not, those errors make me think that build related files are incorrectly being included as part of the application compilation. 

 Possible root causes: 
- Incorrect settings in tsconfig files
- An incorrect import in the application code
