### ISSUE TITLE
Lint xml output is still invalid

### ISSUE THREAD

**Issue by OrangeDog** [angular/angular-cli#19777]
#14659 was closed and locked because tslint was removed, but exactly the same thing happens with eslint
<pre><code>Angular CLI: 11.0.5
Node: 14.15.0
OS: win32 x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/material               11.0.3
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi @OrangeDog,

The ESLint builder is not supported by the Angular tooling team. 
Please file an issue in their issue tracker https://github.com/angular-eslint/angular-eslint

Thanks.

**Comment by OrangeDog** [comment]
I see, thanks. https://github.com/angular-eslint/angular-eslint/issues/289

**Comment by OrangeDog** [comment]
You (pl) already concluded this was for you to fix: https://github.com/angular/angular-cli/issues/14659#issuecomment-501499440
It's not specific to any one builder.
