### ISSUE TITLE
E2E Tests incorrect in default project

### ISSUE THREAD

**Issue by PooperPig** [angular/angular-cli#1977]
1. El Capitan

2. bash-3.2$ ng --version                                                                          
Could not start watchman; falling back to NodeWatcher for file system events.                   
Visit http://ember-cli.com/user-guide/#watchman for more info.                                  
angular-cli: 1.0.0-beta.11-webpack.8                                                            
node: 6.5.0                                                                                     
os: darwin x64  

3. Create an app using ng new
change the e2e test from
```
  it('should display message saying app works', () => {
    page.navigateTo();
    expect(page.getParagraphText()).toEqual('app works!');
  });
```
to 
```
  it('should **NOT** display message saying app works', () => {
    page.navigateTo();
    expect(page.getParagraphText()).toEqual('app **doesnt** works!');
  });

```
then run ng e2e
output is:
`bash-3.2$ ng e2e                                                                                
Could not start watchman; falling back to NodeWatcher for file system events.                   
Visit http://ember-cli.com/user-guide/#watchman for more info.                                  
                                                                                                
> cli-test@0.0.0 pree2e /Users/pooperpig/projects/Angular 2 Projects/cliTest                        
> webdriver-manager update                                                                      
                                                                                                
[13:56:58] I/update - chromedriver: file exists /Users/pooperpig/projects/Angular 2 Projects/cliTest
/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.22mac32.zip     
[13:56:58] I/update - chromedriver: unzipping chromedriver_2.22mac32.zip                        
[13:56:58] I/update - chromedriver: setting permissions to 0755 for /Users/pooperpig/projects/Angula
r 2 Projects/cliTest/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedrive
r_2.22                                                                                          
[13:56:58] I/update - chromedriver: v2.22 up to date                                            
[13:56:58] I/update - selenium standalone: file exists /Users/pooperpig/projects/Angular 2 Projects/
cliTest/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalo
ne-2.53.1.jar                                                                                   
[13:56:58] I/update - selenium standalone: v2.53.1 up to date                                   
                                                                                                
> cli-test@0.0.0 e2e /Users/pooperpig/projects/Angular 2 Projects/cliTest                           
> protractor "./protractor.conf.js"                                                             
                                                                                                
[13:56:59] I/direct - Using ChromeDriver directly...                                            
[13:56:59] I/launcher - Running 1 instances of WebDriver                                        
Spec started                                                                                    
                                                                                                
  cli-test App                                                                                  
    ✓ should NOT display message saying app works                                               
                                                                                                
Executed 1 of 1 spec SUCCESS in 0.02 sec.                                                       
[13:57:00] I/launcher - 0 instance(s) of WebDriver still running                                
[13:57:00] I/launcher - chrome #01 passed                                                       
                                                                                                
All end-to-end tests pass.         `

4. Whatever I try, I cannot get the test to fail!

5. I have tried ngBuild in between changes etc. The text of the test changes ( so it is picking up the changed source) but the tests themselves don't fail.

Appreciate this isn't necessarily an angular-cli issue per se, but its my first port of call!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by stefanaerts** [comment]
for me the same. i am using the webpack 1.0.0-beta.11-webpack.8 version.
ng test works
ng e2e does not work, i see in a flits the word data; in the browser url bar and then i always get the result test passed.

**Comment by evanrooijen** [comment]
+1

**Comment by christiandreher** [comment]
https://github.com/angular/protractor/issues/3505

**Comment by stefanaerts** [comment]
https://github.com/angular/angular-cli/issues/1981#issuecomment-246112106
