### ISSUE TITLE
Cannot use option "--module project" with ng generate.

### ISSUE THREAD

**Issue by msieurtoph** [angular/angular-cli#19796]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I dont know.

### Description

"ng generate" supplies the --module option to add a module name, in order to import/declare the generated item into this module.
If your module is named ProjectModule, it does not work. 

## 🔬 Minimal Reproduction

Let's have this architecture :

```
$ ng g m models
CREATE xxxxxxxx/models/models.module.ts (193 bytes)

$ ng g m models/project
CREATE xxxxxxxx/models/project/project.module.ts (193 bytes)



/models
    /project
         project.module.ts
         ....
    models.module.ts
    ....

```
Let's see the return of following "ng generate" :

```
$ ng g m models/project/contact -m models -d
CREATE xxxxx/models/project/contact/contact.module.ts (193 bytes)
UPDATE xxxxx/models/models.module.ts (600 bytes)
==> If I specified ModelsModule, it works ...

NOTE: The "dryRun" flag means no changes were made.

------------

$ ng g m models/project/contact -m project -d
CREATE xxxxx/models/project/contact/contact.module.ts (193 bytes)                 

NOTE: The "dryRun" flag means no changes were made.
==>  ProjectModule is not updated with -m project (I tried with quotes, =, --module ... it never worked)

------------

$ ng g m models/project/contact -d
CREATE xxxxx/models/project/contact/contact.module.ts (193 bytes)               

NOTE: The "dryRun" flag means no changes were made.
==>  Same result when skipping the option

------------

$ ng g c models/project/contact -d -m=project
CREATE xxxxx/models/project/contact/contact.component.html (22 bytes)
CREATE xxxxx/models/project/contact/contact.component.ts (280 bytes)
CREATE xxxxx/models/project/contact/contact.component.scss (0 bytes) 

NOTE: The "dryRun" flag means no changes were made.
==> Tried with a component, it's not updated either

------------

$ ng g c models/project/contact -d
CREATE xxxxx/models/project/contact/contact.component.html (22 bytes)
CREATE xxxxx/models/project/contact/contact.component.ts (280 bytes)
CREATE xxxxx/models/project/contact/contact.component.scss (0 bytes)
UPDATE xxxxx/models/project/project.module.ts (191 bytes)

NOTE: The "dryRun" flag means no changes were made.
==> BUT if you generate a component AND skipping the option, it is well updated.

```
I also tried with a sibling Module : 

```
$ ng g m models/project/test --flat
CREATE xxxxx/models/project/test.module.ts (190 bytes)
==> I created a sibing module near to ProjectModule

$ ng g m models/project/contact --module test -d
CREATE xxxxxxxx/models/project/contact/contact.module.ts (193 bytes)
UPDATE xxxxxxxx/models/project/test.module.ts (267 bytes)

NOTE: The "dryRun" flag means no changes were made.
==> It seems to work perfectly with another moduleName....
----------------

$ ng g m models/project/contact --module project -d
CREATE xxxxxxxx/models/project/contact/contact.module.ts (193 bytes)

NOTE: The "dryRun" flag means no changes were made.
==> But still impossible to get ProjectModule updated
----------------

```
 

## 🔥 Exception or Error
None

## 🌍 Your Environment
<pre><code>

$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.0.2
Node: 14.15.1
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.2
@angular-devkit/build-angular      0.1100.2
@angular-devkit/core               11.0.2
@angular-devkit/schematics         11.0.2
@angular/cdk                       11.0.0
@angular/material                  11.0.0
@angular/material-moment-adapter   11.0.0
@schematics/angular                11.0.2
@schematics/update                 0.1100.2
rxjs                               6.6.3
typescript                         4.0.5

</code></pre>

**Anything else relevant?**

It looks like if "project" was some kind of reserved keyword which has a specific treatment inside the ng cli generate. Maybe it's relative to the --project option.
But I don't get why ProjectModule is still not updated when generating module while skipping the --module option 
... and neither why it is updated when generating a component.

If I can help, do not hesitate...

**Comment by alan-agius4** [comment]
Hi @msieurtoph,

I tied to replicate this above issue without success.

```
➜  ng g m models/project
CREATE projects/testing/models/project/project.module.ts (193 bytes)
➜  ng g m models/project/contact -m project -d
CREATE projects/testing/models/project/contact/contact.module.ts (193 bytes)
UPDATE projects/testing/models/project/project.module.ts (270 bytes)

NOTE: The "dryRun" flag means no changes were made.

➜  ng g m models/project/contact -d
CREATE projects/testing/models/project/contact/contact.module.ts (193 bytes)

NOTE: The "dryRun" flag means no changes were made.
➜  ng g c models/project/contact -d -m=project
CREATE projects/testing/models/project/contact/contact.component.css (0 bytes)
CREATE projects/testing/models/project/contact/contact.component.html (22 bytes)
CREATE projects/testing/models/project/contact/contact.component.ts (336 bytes)
CREATE projects/testing/models/project/contact/contact.component.spec.ts (839 bytes)
UPDATE projects/testing/models/project/project.module.ts (273 bytes)
```


- Are you using some 3rd party schematics? 
- Can you reproduce this on a new project?

**Comment by msieurtoph** [comment]
You're right ! 
I do not reproduce the behavior on a new project.
:(

However, before opening the issue, I tried to delete the existing ProjectModule and recreate it. 
It still was not updated.

I don't get it.


Sorry for having wasted your time.
I close the issue.
