### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory  1: 003806CE node::MakeCallback+3982  2: 007AA9D2 v8::internal::Heap::MaxHeapGrowingFactor+8194  3: 007A1BB1 v8::internal::ScavengeJob::operator=+14993  4: 007A930E v8::internal::Heap::MaxHeapGrowingFactor+2366

### ISSUE THREAD

**Issue by jimishah514** [angular/angular-cli#19797]
# 🐞 Bug report

### Description
After upgrade ag-grid version from 21.2.2 - > 23.0.0  and npm i

## 🌍 Environment
<pre><code>

Angular CLI: 9.1.13
Node: 10.16.3
OS: win32 ia32

Angular: 9.1.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.13
@angular-devkit/build-angular     0.901.13
@angular-devkit/build-optimizer   0.901.13
@angular-devkit/build-webpack     0.901.13
@angular-devkit/core              11.0.7
@angular-devkit/schematics        11.0.7
@angular/cdk                      8.2.2
@angular/fire                     5.4.2
@angular/pwa                      0.803.29
@ngtools/webpack                  9.1.13
@schematics/angular               11.0.7
@schematics/update                0.901.13
rxjs                              6.6.3
typescript                        3.7.5
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
