### ISSUE TITLE
v11 removed schematics/angular/utility/json-utils.ts

### ISSUE THREAD

**Issue by gkamperis** [angular/angular-cli#19793]
Hi

The below file 

https://github.com/angular/angular-cli/blob/10.2.x/packages/schematics/angular/utility/json-utils.ts

disappeared from v11.

There were no deprecation or easy to find alternatives.

Can someone pls clarify what happened and/or alternatives for these?

Thanks

**Comment by alan-agius4** [comment]
Anything under /utils is considered as private APIs and therefore can be changed or  removed without warning in any version.

You can use https://www.npmjs.com/package/jsonc-parser instead.

**Comment by gkamperis** [comment]
@alan-agius4 thanks for the quick reply.

I take it that these were also used internally. 

Any examples on how you internally replaced their usage?

**Comment by alan-agius4** [comment]
You can see https://github.com/angular/angular-cli/blob/master/packages/schematics/angular/utility/json-file.ts for an example.
