### ISSUE TITLE
Build breaks if tsickle is removed from dev dependencies

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#19804]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
New projects are not supposed to have a dependency on tsickle. However, my project fails if I try to remove it.

### Description

 A clear and concise description of the problem...
Please follow the ticket over on tsickle's issue page for more details
https://github.com/angular/tsickle/issues/1190

**Comment by alan-agius4** [comment]
Hi @bjornharvold, 

- What is the error you are receiving?
- Did you run ng update when updating Angular CLI? We do have migrations that remove tsickle and the related settings. 
- Do you have some left over `annotateForClosureCompiler` settings in your tsconfig file?

**Comment by bjornharvold** [comment]
Hi @alan-agius4 

- The error is on the tsickle issue. 
- Yes, I do run ng update on every major version update
- Yes, I do have this in my libraries:

```
"angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "enableResourceInlining": true
  }
```

**Comment by bjornharvold** [comment]
I've updated these settings with the new ones:

```
"angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  },
```

Re-compiling all 100+ libraries in monorepo now without tsickle dependency to see if that does the trick. Will close this ticket upon success.

**Comment by bjornharvold** [comment]
That did the trick. Thank you for pointing out that compiler option @alan-agius4
