### ISSUE TITLE
Error with Karma 6: No provider for "customFileHandlers"

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#19815]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] test

### Is this a regression?

Yes, the previous version in which this bug was not present was: with karma 5.x

### Description

In Karma version 6 `customFileHandlers` is deprecated in favour of the [middleware](https://karma-runner.github.io/6.0/config/configuration-file.html#middleware) functionality.

See: https://github.com/karma-runner/karma/releases/tag/v6.0.0

## 🔥 Exception or Error
<pre><code>
19 01 2021 09:14:56.495:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "customFileHandlers"! (Resolving: framework:@angular-devkit/build-angular -> customFileHandlers)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.7
Node: 14.15.4
OS: darwin x64

Angular: 11.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.7
@angular/cdk                    11.0.4
@angular/cli                    11.0.7
@angular/material               11.0.4
@schematics/angular             11.0.7
@schematics/update              0.1100.7
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

I am using https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack to add a custom webpack to my tests.

**Comment by alan-agius4** [comment]
This is expected as Karma 6 is not supported by in Angular CLI 11.0. 


It will be supported in Angular CLI 11.1. See: 
See: https://github.com/angular/angular-cli/pull/19784

You can try using the prerelease version by running:

```
ng update @angular/cli --next
```
