### ISSUE TITLE
e2e test in latest wepack version not working

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#1981]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
created default app and added typescript to the package.json and changed the rxjs version to 5.0.0-beta.06 instead 11

4. The log given by the failure. Normally this include a stack trace and some
   more information.
my package.json:
"name": "temp-app",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "^2.4.0",
    "rxjs": "5.0.0-beta.06",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.12",
    "typescript": "2.0.0"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.11-webpack.8",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.0"
  }
}

5. Mention any other details that might be useful.
ng test works,
ng e2e not, i see in a flits the word "data;" in the browser url bar before it closes.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by stefanaerts** [comment]
ng e2e gives always succeeded even if you change the test to "api works" for example

**Comment by evanrooijen** [comment]
+1

**Comment by duncanhunter** [comment]
I temporarily fixed this issues by rolling back the version of protractor to 3.3.0.

Possibly related to this issue https://github.com/angular/protractor/issues/3511

**Comment by stefanaerts** [comment]
changing it to version 3.3.0 doesnt work with this version of CLI using webpack
![image](https://cloud.githubusercontent.com/assets/3684599/18342968/9b60b288-75b1-11e6-9813-e301c07dbd96.png)

**Comment by stefanaerts** [comment]
but at least the test failed this way (-)

**Comment by duncanhunter** [comment]
@stefanaerts you are right it does not work with protractor 3.03 on a new cli generated app with 1.0.0-beta.11-webpack.8, but my migrated project to 1.0.0-beta.11-webpack.8 this worked for me. 

I did, however, run a quick test on this newly generated app and updated my protractor to protractor 4.0.5 and it worked. First I deleted my node_modules and did a clean npm install and it started failing my tests I wanted to fail.

Not sure why my migrated app is different than a new one?

**Comment by stefanaerts** [comment]
what is in your package.json?
Does your app.po.ts does this
import { browser, element, by } from 'protractor/globals';

**Comment by duncanhunter** [comment]
Here is a link to a repo I just pushed to, look at initial commits 1 and 2. https://github.com/duncanhunter/ngrx-demo

### I took the following steps
1. Check cli version is 1.0.0-beta.11-webpack.8
``` ng -v```
2. Delete node_modeules
``` rm -rf node_modules```
3. Update protractor in package.json
```  "protractor": "4.0.5" ```
4. npm install
``` npm i ```
5. change app.e2e-spec.ts to fail not pass
``` expect(page.getParagraphText()).toEqual('app work!'); ````

**Comment by stefanaerts** [comment]
it works for me also now, but not like that.
i did several things,maybe some of them do not matter,but i give them all:
updates to package.json:
1) removed angular/compiler-cli 
2) add "@angular/platform-server": "2.0.0-rc.5",
3) add   "@types/webpack": "^1.12.33",
4) add  "reflect-metadata": "0.1.8",
5) changed    "karma-remap-istanbul": "0.2.1" back to    "karma-remap-istanbul": "^0.2.1",
6) add  "protractor": "4.0.5",

my types dependencies contain now
![image](https://cloud.githubusercontent.com/assets/3684599/18350645/1eb9d2a2-75d7-11e6-87eb-1152e14cdc88.png)

i changed typings.d.ts to this picture because of errors in console when i run ng serve or build:
![image](https://cloud.githubusercontent.com/assets/3684599/18350678/41895abe-75d7-11e6-88b4-36400f42b582.png)

now both test options work, ng test and ng e2e work like they should work.
i changed one line in typings.d.ts back for require to be of type any because test.ts "require.context" complained "context" does not exist on NodeRequire.

![image](https://cloud.githubusercontent.com/assets/3684599/18351379/42523580-75da-11e6-872b-1128d5dfa661.png)

now everything still works but I only get an error in the console when i run ng test:

ERROR in [default] /Users/stefanaerts/tmp/testcliwebpack/src/typings.d.ts:7:12 
Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'any'.

BUT the tests work, so for me this can be closed

**Comment by stefanaerts** [comment]
Well i changed it better:
![image](https://cloud.githubusercontent.com/assets/3684599/18352563/33e62d4e-75df-11e6-9a61-1ae7de674031.png)

and did a cast in the test.ts:
![image](https://cloud.githubusercontent.com/assets/3684599/18352579/46674142-75df-11e6-89d8-204248e029e2.png)

i added more tests to components in separated directories and and test.ts found them all, so the script works fine this way.

**Comment by christiandreher** [comment]
Here's some background: https://github.com/angular/protractor/issues/3505

**Comment by stefanaerts** [comment]
please read christian, its solved

**Comment by christiandreher** [comment]
Like I said, I just wanted to give some background regardless of whether it's solved or not.
