### ISSUE TITLE
Warning in webpack-subresource-integrity

### ISSUE THREAD

**Issue by lukaskurz** [angular/angular-cli#19829]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Nope, don't think so.

### Description

 
When i try to do a build with angular it throws this warning at the end of it:

```
chunk {} runtime.39e440ffc58a0c5ea137.js (runtime) 2.62 kB [entry] [rendered]
chunk {1} main.f0787a89e56367a0d4ae.js (main) 111 kB [initial] [rendered]
chunk {2} polyfills.45adc7f91fa71ef6f425.js (polyfills) 166 kB [initial] [rendered]
chunk {3} polyfills-es5.834fe503d6f9b3377e74.js (polyfills-es5) 249 kB [initial] [rendered]
chunk {4} styles.3dd4681c5b97bbeabdf5.css (styles) 569 kB [initial] [rendered]
chunk {5} vendor.b4bbba3e16bf4652debe.js (vendor) 1.46 MB [initial] [rendered]
chunk {6} 6.8e8c786becf994378b6c.js () 1.07 MB  [rendered]
chunk {7} 7.6b6ed83ee281f7c77918.js () 34.4 kB  [rendered]
chunk {8} 8.7cf7cb03827a25cd0afb.js () 43.1 kB  [rendered]
chunk {scripts} scripts.0022afdcd9fa76f58a28.js (scripts) 324 kB [entry] [rendered]
Date: 2020-10-29T02:38:20.143Z - Hash: 14cc2dc96fe0ed82f9cc - Time: 52396ms

WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.0022afdcd9fa76f58a28.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new
```

While it seems to have to detrimental effect on the finished build, I would still like to not have a warning in my build process :sweat_smile: 

I've opened an issue over at the waysact/webpack-subresource-integrity:

https://github.com/waysact/webpack-subresource-integrity/issues/133

Where someone took a look at it and referred me to discuss this issue with you folks furthermore.

## 🔬 Minimal Reproduction

https://github.com/lukaskurz/sri_warning_demo

All you have to do is run `make` to get the warning.

## 🔥 Exception or Error
<pre><code>
WARNING in webpack-subresource-integrity: Cannot determine asset for chunk scripts, computed="undefined", available=scripts.0022afdcd9fa76f58a28.js. Please report this full error message along with your Webpack configuration at https://github.com/waysact/webpack-subresource-integrity/issues/new
</code></pre>

## 🌍 Your Environment
<pre><code>
 ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.1
Node: 14.15.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1100.1 (cli-only)
@angular-devkit/core         11.0.1 (cli-only)
@angular-devkit/schematics   11.0.1 (cli-only)
@schematics/angular          11.0.1 (cli-only)
@schematics/update           0.1100.1 (cli-only)

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
It appears that the version output shown above is from a global install of the Angular CLI.  Could you provide the output of `ng version` executed from within the project?

**Comment by alan-agius4** [comment]
I was able to replicate this even with the latest version of the CLI.

**Comment by lukaskurz** [comment]
@clydin Sorry, totally forgot that `ng` is globally installed. Here is the version of the local install:

```
npx ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.5
Node: 14.15.0
OS: linux x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/cdk                      9.1.1
@angular/http                     7.2.16
@angular/material                 9.1.1
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.2
typescript                        3.7.5
webpack                           4.41.2
```

I think this should be a it.
