### ISSUE TITLE
Strange behavior at Angular CLI Gitter channel

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular-cli#19842]
# 🐞 Bug report

- [x] others ...

### Gitter channel

Can anybody with admin access look at what is happening on the Gitter Angular CLI channel?

![image](https://user-images.githubusercontent.com/5693835/105406481-c9452380-5c2c-11eb-9563-0f76934a389e.png)

**Comment by IgorMinar** [comment]
it seems that this was just a transient issue with gitter.im. Both @mgechev and I checked and the chat room looks good now. I'll go ahead and close this issue, but please file a new one if the issue reappears. Thanks

**Comment by mlc-mlapis** [comment]
@IgorMinar It looks that the same problem is repeating. It seems that it discourages all user activity there.

**Comment by mgechev** [comment]
Just reached out to the Gitter team. They are working on a fix which should land soon.
