### ISSUE TITLE
Comment in tsconfig.lib.json.template produces invalid tsconfig.lib.json

### ISSUE THREAD

**Issue by cluen** [angular/angular-cli#19845]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, introduced with this commit: 
https://github.com/angular/angular-cli/commit/76f525cec2f2397f01ed26edf9902eb3649bb42e
Pull Request: #17906

### Description

The generated tsconfig.lib.json from tsconfig.lib.json.template is invalid due to the comments in first line:
`/* To learn more about this file see: https://angular.io/config/tsconfig. */`

JSON doesn't support comments.

Maybe it's an option to use the [`"$schema"` - keyword](https://json-schema.org/understanding-json-schema/reference/schema.html), like GitVersioning in their version.json:
`"$schema": "https://raw.githubusercontent.com/dotnet/Nerdbank.GitVersioning/master/src/NerdBank.GitVersioning/version.schema.json",`

## 🔬 Minimal Reproduction
`ng g library my-library`

## 🔥 Exception or Error
While reading in / parsing the json file with 
`JSON.parse`

it will throw an error:
`SyntaxError: Unexpected token / in JSON at position 0`

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.7
Node: 12.16.1
OS: win32 x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1001.7
@angular-devkit/build-angular      0.1001.7
@angular-devkit/build-ng-packagr   0.1001.7
@angular-devkit/core               10.1.7
@angular-devkit/schematics         10.1.7
@angular/cdk                       10.2.7
@angular/cli                       10.1.7
@angular/flex-layout               10.0.0-beta.32
@angular/localize                  10.1.6
@angular/material                  10.2.7
@schematics/angular                10.1.7
@schematics/update                 0.1001.7
ng-packagr                         10.1.2
rxjs                               6.5.5
typescript                         4.0.3

</code></pre>

**Anything else relevant?**
We've an internal tool to analyse our dependencies between libraries. For this check we're analyzing our code base and need to exclude files listed in "exclude"-list of tsconfig.lib.json. So we've to read the json file.

**Comment by alan-agius4** [comment]
Hi,

TypeScript, among other tools use a superset of JSON which does allow comments. Some supersets of JSON that do allow comments are JSON5 and JSONC.

**More information**
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#allow-comments-in-tsconfigjson
https://spec.json5.org/#comments
https://code.visualstudio.com/docs/languages/json#_json-with-comments

If your tool is not able to handle these supersets, feel free to remove these comments manually.

**Comment by cluen** [comment]
Thank you for your clarification. We'll try to change our read / parse method.
