### ISSUE TITLE
ng github-pages:deploy pushes entire project, not just dist/

### ISSUE THREAD

**Issue by JimTheMan** [angular/angular-cli#1984]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   Mac 10.11.4
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli: 1.0.0-beta.10
   node: 5.11.1
   os: darwin x64
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
4. The log given by the failure. Normally this include a stack trace and some
   more information.
   no failure
5. Mention any other details that might be useful.

I run this command:
SafeFoods (master) ♔   ng github-pages:deploy --message "Optional commit message"

output:
Built project successfully. Stored in "dist/".

But this pushes the entire project to gh-pages, not just the contents of dist/
You can check the repo here:
[(https://github.com/JimTheMan/Safe-Foods/tree/gh-pages)](https://github.com/JimTheMan/Safe-Foods/tree/gh-pages)

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by beeman** [comment]
@JimTheMan the latest version of angular-cli (1.0.0-beta.24) does seem to have this issue anymore, I can successfully deploy to github as expected (only the dist folder, not the whole repo).

Example: https://beeman.github.io/angular-cli-sweetalert2-demo/

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
