### ISSUE TITLE
Can't Load Resources When Deployed

### ISSUE THREAD

**Issue by JimTheMan** [angular/angular-cli#1985]
OS? Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac 10.11.4

Versions. Please run ng --version. If there's nothing outputted, please run
in a Terminal: node --version and paste the result here:
angular-cli: 1.0.0-beta.10
node: 5.11.1
os: darwin x64

Repro steps. Was this an app that wasn't created using the CLI? What change did you
do on your code? etc.

The application works fine when running 'ng serve --prod', but when I run 'ng build --prod' and then publish live, I can a ton of errors that resources can't be found.

![safefoods_and_safefoods_ _-bash_ _114x24_and_more-trash_ _-bash_ _81x24](https://cloud.githubusercontent.com/assets/5354163/18252828/ac6942b6-735e-11e6-9f64-5921c1198254.png)

There is a lot of "magic" for loading these resources in index.html so I'm not sure what to do to fix this....

[https://github.com/JimTheMan/Safe-Foods/tree/gh-pages](https://github.com/JimTheMan/Safe-Foods/tree/gh-pages)

My project is named "SafeFoods". The correct path for, for example es6-shim.js, should be: 
https://jimtheman.github.io/Safe-Foods/vendor/es6-shim/es6-shim.js
when it is actually:
https://jimtheman.github.io/vendor/es6-shim/es6-shim.js

The ng build task creates it like this every time so I'm not sure how to tell it the proper path...

**Comment by JimTheMan** [comment]
Note: I also tried updating angular-cli to the newest version and using '--base-href', but that doesn't seem to be functioning correctly:

`SafeFoods (gh-pages) ♔ ng build --prod --base-href /Safe-Foods/`

`The option '--base-href' is not registered with the build command. Run `ng build --help` for a list of supported options.`

**Comment by filipesilva** [comment]
@jimthedev the `--base-href` flag was part of the new webpack release, and should work with the latest `beta.14` version.

Bear in mind though, you'll need to upgrade your project if you want to use it. You can find more information here: https://github.com/angular/angular-cli#webpack-update

If updating is not an option for you right now, then you can manually edit the base tag prior to uploading your app.
