### ISSUE TITLE
Where's this @TheLarkInn  #1465 talks about creating a module for app like `@app`, which is like configuring an alias in resolve of webpack config. How will this help in bundling and loading css/scss.

### ISSUE THREAD

**Issue by 929496959** [angular/angular-cli#19859]
@TheLarkInn  #1465 talks about creating a module for app like `@app`, which is like configuring an alias in resolve of webpack config. How will this help in bundling and loading css/scss.

_Originally posted by @sirajc in https://github.com/angular/angular-cli/issues/1459#issuecomment-236009735_

**Comment by 929496959** [comment]
How to use

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
