### ISSUE TITLE
`ng serve --hmr` should apply changes in component styles without reinitialization of the whole app

### ISSUE THREAD

**Issue by th0r** [angular/angular-cli#19867]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Currently during `ng serve --hmr` any change in component styles triggers reinitialization of the whole app. This behavior is far from ideal as route components in most of the apps need to load data asynchronously and their reinitialization triggers this process again, so applying a change in component's styles can't be reviewed immediately (as it should and as it's done in other frameworks like Vue or React).

I've created a [reproduction repo](https://github.com/th0r/ng-hmr-for-component-styles):
1. Clone it, run `npm ci && npm start` and open `localhost:4200`
2. You'll see `Initializing page...` and then `Page ready`. `TestPageComponent` simulates data loading in it's `ngOnInit` method.
3. Change [this line](https://github.com/th0r/ng-hmr-for-component-styles/blob/e6a6fd1094f7754b4e4ecc254a30ca7699eaaf29/src/app/test-page/test-page.component.scss#L11) to something like `background-color: blue`.
4. `TestPageComponent` will be reinitialized and you'll be able to review the change only after 3 seconds.

### Describe the solution you'd like
I expect changes in component styles to be applied immediately without reinitialization of the host component.

By the way, changes in global styles are applied immediately, as they should.

**Comment by alan-agius4** [comment]
I did look into a way to achieve this in the past.

This is a non-trivial problem to solve, I will do some investigation but i think the the Framework needs to provide an API. See: https://github.com/angular/angular/issues/39367

**Comment by mtuzinskiy** [comment]
One addition: I can see that only the lazy component module is being reloaded in Network tab, but still *the whole app reinitializes*, which basically makes HMR useless. 
In other words, HMR still doesn't work in Angular 11.1.1.

**Comment by Y2zz** [comment]
I am very helpless, which means that Angular is not suitable for building large applications

**Comment by sebastian-zarzycki-es** [comment]
I am also a bit flummoxed, how hot reloading is still a problem for Angular. Current solution seems very heavy handed, as it reloads whole module. For single-module applications, or applications with bigger modules, that does almost nothing.

**Comment by mtuzinskiy** [comment]
Any hopes that this will be addressed any time soon?

**Comment by mtuzinskiy** [comment]
Any updates on this important issue?

**Comment by ronen009** [comment]
i just saw this post, wish i saw it earlier. onNgInit being initialized each time using hmr. thus ajax service function inside onNgInit  being called. and i lose data. 
now i undersatnd that its not working as needed. i hate this framework.

**Comment by sebastian-zarzycki-es** [comment]
In all fairness, this is actually expected, the framework needs to instantiate the component again, because its internal code could change (i.e. things added to ngOnInit). Not sure why you would lose data, if you're actually calling for them during ngOnInit.

**Comment by mtuzinskiy** [comment]
Yes, the component re-intialization is fine. Actually @ronen009  the fact that you do an HTTP call inside of your component is a sign of bad architecture: the component should be "thin" and care only about the UI logic.  
Extract the method with HTTP call in a separate service, make it `providedIn: 'root'`, and then HMR wouldn't re-create it if the service code doesn't change.  
I mean, it SHOULDN'T :slightly_smiling_face:  Currently HMR sucks so much that it reloads _everything_ even on CSS change, so...  
But at least this will be fair now @sebastian-zarzycki-es  right?

**Comment by mtuzinskiy** [comment]
Btw here's my workaround for now, guys:  I use Nrwl Nx with Storybook,  and HMR for Storybook works just perfectly! Because it has it's own Webpack configuration. Just try it out it's amazing! If I change CSS, it reloads only CSS portion. Same goes for HTML and TS.

**Comment by sebastian-zarzycki-es** [comment]
The call has to originate from somewhere, though, even if it's implementation is abstracted into separate service. Memoizing the result and adding your own HMR-related code just to "make it snappier" seems like a completely wrong way to go to me. There should be no HMR-related code at all.

In such cases, there's just simply no way of overcoming this. If you change something in a component that initiates a call, every reload would cause that call to happen. That's ok, it's just a consequence of what this particular component does.

**Comment by mtuzinskiy** [comment]
@sebastian-zarzycki-es  Well in my (large) project, I have a whole "dev cache" made with HTTP interceptor, that caches all the responses in a local DB. + I made a Devtools panel to control that.  When your HTTP request takes seconds, and when you have tons of HTTP requests per module,  tricks to "make it snappier" start make sense

**Comment by sebastian-zarzycki-es** [comment]
I would argue that if you need many costly calls to reload a single page, then it's a sign that something should be redesigned there. But, yeah, it's IT, corner cases happen all the time. It can be helpful for a specific situation like yours, but it shouldn't be a prerequisite for HMR to work efficiently, as other technologies show us that it is entirely possible for HMR to work way way better.

**Comment by mtuzinskiy** [comment]
:handshake: To sum up, it's an expected behavior, it's OK, and it's not related to this current issue

**Comment by alan-agius4** [comment]
Let's keep tracking this issue here https://github.com/angular/angular/issues/39367 since this is not possible without changes in the framework. 


Please thumbs up the mentioned issue, if you'd like this feature to be added.

**Comment by mtuzinskiy** [comment]
@alan-agius4   It's NOT related to CSS only (read this thread please)

**Comment by alan-agius4** [comment]
Any changes to a component or module at the moment will need a full application re-initialization. 

As per https://github.com/angular/angular/issues/39367#issuecomment-249961139 without an API from the framework we cannot patch updates to component templates, styles and so on… and hence the why we are tracking this issue in https://github.com/angular/angular/issues/39367

**Comment by sebastian-zarzycki-es** [comment]
This framework is being rewritten and then rewritten and then rewritten again ad nauseam, while important development features like this linger for, apparently, 5 years.
