### ISSUE TITLE
export 'ɵisSubscribable' was not found in '@angular/core

### ISSUE THREAD

**Issue by Anasalkhalil** [angular/angular-cli#19864]
failer accurs bei build Image auf  Jenkins:  
**[INFO] Error: ./node_modules/@angular/common/fesm2015/common.js 3299:16-31
[INFO] "export 'ɵisSubscribable' was not found in '@angular/core'**
[INFO]     at HarmonyImportSpecifierDependency._getErrors (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
[INFO]     at HarmonyImportSpecifierDependency.getErrors (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:68:16)
[INFO]     at Compilation.reportDependencyErrorsAndWarnings (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/Compilation.js:1463:22)
[INFO]     at /var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/Compilation.js:1258:10
[INFO]     at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:53:1)
[INFO]     at AsyncSeriesHook.lazyCompileHook (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
[INFO]     at Compilation.finish (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/Compilation.js:1253:28)
[INFO]     at /var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/Compiler.js:672:17
[INFO]     at _done (eval at create (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
[INFO]     at eval (eval at create (/var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:72:22)
[INFO]     at /var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/Compilation.js:1185:12
[INFO]     at /var/lib/jenkins/workspace/ui-server_development-JY3DGBRAUS4ZBPODV6RUEKH2KPXSALQFE3HCLVJFOJCTZBRWPVSQ/ui-client/node_modules/webpack/lib/Compilation.js:1097:9
[INFO]     at processTicksAndRejections (internal/process/task_queues.js:75:11)
[INFO]  @ ./projects/vjd/src/personas/browse/browse-persona/services/switch-css-to-browse-persona.service.ts
[INFO]  @ ./projects/vjd/src/personas/browse/browse-persona/browse-persona.module.ts
[INFO]  @ ./projects/vjd/src/app/app.module.ts
[INFO]  @ ./projects/vjd/src/main.ts
[INFO]  @ multi ./projects/vjd/src/main.ts
[INFO] 
[INFO] 
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! ui-client@0.0.0 build-spring: `ng build --prod --build-optimizer --output-path ../ui-server/target/classes/static/`
[INFO] npm ERR! Exit status 1
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the ui-client@0.0.0 build-spring script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

dependencies: 
    "@angular-mdc/web": "5.1.1",
    "@angular/animations": "~11.0.3",
    "@angular/cdk": "^11.0.1",
    "@angular/common": "^11.0.3",
    "@angular/compiler": "11.0.3",
    "@angular/core": "11.0.3",
    "@angular/forms": "~11.0.3",
    "@angular/localize": "^11.0.3",
    "@angular/material": "^11.0.1",
    "@angular/platform-browser": "~11.0.3",
    "@angular/platform-browser-dynamic": "~11.0.3",
    "@angular/router": "~11.0.3",
    "@babel/compat-data": "7.8.0",
    "@stomp/stompjs": "^5.2.0",
    "ajv": "^6.0.0",
    "class-transformer": "^0.2.0",
    "core-js": "^3.2.1",
    "material-components-web": "^2.3.1",
    "ng-inline-svg": "^9.0.1",
    "no": "0.0.1",
    "optional": "^0.1.4",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "typescript-logging": "^0.6.3",
    "uuid": "^3.3.2",
    "zone.js": "~0.10.2"

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
