### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined thrown

### ISSUE THREAD

**Issue by kurubavinodkumar** [angular/angular-cli#19873]
Angular test is throw Uncaught TypeError: Cannot read property 'toLowerCase' of undefined thrown

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
