### ISSUE TITLE
Wrong path for eslintrc extendable main file when generating new library

### ISSUE THREAD

**Issue by ghaschel** [angular/angular-cli#19870]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, this bug is related to the eslint integration

### Description

When generating a new library using a composed name (eg: @company/package), the "extends" property in the eslintrc.json file becomes `../../.eslintrc.json` instead of `../../../eslintrc.json`.

## 🔬 Minimal Reproduction

Create a new project using `ng new --collection=@angular-eslint/schematics --strict=true`, generate a new library using `ng g library @company/package`

## 🔥 Exception or Error
<pre><code>

Linting "@sb/file-upload"...
An unhandled exception occurred: Failed to load config "../../.eslintrc.json" to extend from.
Referenced from: /home/guilherme/projects/bibliotecas/projects/sb/file-upload/.eslintrc.json
See "/tmp/ng-ck7Pfb/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.1.1
Node: 12.18.3
OS: linux x64

Angular: 11.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1101.1
@angular-devkit/build-angular      0.1101.1
@angular-devkit/build-ng-packagr   0.1002.0
@angular-devkit/core               11.1.1
@angular-devkit/schematics         11.1.1
@angular/cli                       11.1.1
@schematics/angular                11.1.1
@schematics/update                 0.1101.1
ng-packagr                         11.1.2
rxjs                               6.6.3
typescript                         4.1.3
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [@angular-eslint/schematics](https://github.com/angular-eslint/angular-eslint) project or file an issue on their issue tracker.
