### ISSUE TITLE
Project won't compile after adding webworker to Angular 11

### ISSUE THREAD

**Issue by ezforw** [angular/angular-cli#19884]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular-devkit/build-angular/src/babel/webpack-loader.js

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v10

### Description
Added web worker to an existing Angular 11 project, then the project won't compile anymore.

The error was gone when `"webWorkerTsConfig": "tsconfig.worker.json"` was removed from `angular.json`

## 🔬 Minimal Reproduction
1. Checkout https://github.com/ezforw/angular-11-webworker-sample
2. `npm install`
3. `npm start`

## 🔥 Exception or Error
<pre><code>
Error: ./node_modules/@auth0/auth0-spa-js/dist/auth0-spa-js.production.esm.js
Module parse failed: Cannot read property 'length' of undefined
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.1.0
Node: 12.6.0
OS: darwin x64

Angular: 11.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.0
@angular-devkit/build-angular   0.1101.0
@angular-devkit/core            11.1.0
@angular-devkit/schematics      11.1.0
@schematics/angular             11.1.0
@schematics/update              0.1101.0
rxjs                            6.6.3
typescript                      4.1.3

</code></pre>

**Comment by alan-agius4** [comment]
As @petebacondarwin mentioned It does appear that this is a bug in the [worker-plugin](https://github.com/GoogleChromeLabs/worker-plugin) where it doesn't handle providing the options via a defined variable `Identifier`. 

Unfortunately, this is not actionable from our end. Kindly file an issue https://github.com/GoogleChromeLabs/worker-plugin.
