### ISSUE TITLE
0.1101.1 Return errors when trying to build app-shell with custom webpack.

### ISSUE THREAD

**Issue by JordyRoelofs** [angular/angular-cli#19886]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] build

### Is this a regression?

Yes, the previous version in which this bug was not present was: ....

0.1100.7

### Description

 A clear and concise description of the problem...

When trying to run app-shell build inside an angular application, it returns the following errors:

"Schema validation failed with the following errors:
  Data path ".optimization.styles" should be boolean.
  Data path ".optimization" should be boolean.
  Data path ".optimization" should match exactly one schema in oneOf."

## 🔬 Minimal Reproduction
run the following "app-shell" entry from the angular.json file.

## 🔥 Exception or Error
<pre><code>

"Schema validation failed with the following errors:
  Data path ".optimization.styles" should be boolean.
  Data path ".optimization" should be boolean.
  Data path ".optimization" should match exactly one schema in oneOf."

</code></pre>

## 🌍 Your Environment

package.json
<pre><code>
"dependencies": {
    "@angular/animations": "11.1.0",
    "@angular/cdk": "11.1.0",
    "@angular/common": "11.1.0",
    "@angular/compiler": "11.1.0",
    "@angular/core": "11.1.0",
    "@angular/forms": "11.1.0",
    "@angular/material": "11.1.0",
    "@angular/platform-browser": "11.1.0",
    "@angular/platform-browser-dynamic": "11.1.0",
    "@angular/platform-server": "11.1.0",
    "@angular/router": "11.1.0",
    "@angular/service-worker": "11.1.0",
    "moment": "2.29.1",
    "rxjs": "6.6.3",
    "tslib": "2.1.0",
    "zone.js": "0.11.3"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "11.0.0",
    "@angular-devkit/build-angular": "0.1100.7",
    "@angular-eslint/builder": "1.1.0",
    "@angular-eslint/eslint-plugin": "1.1.0",
    "@angular-eslint/eslint-plugin-template": "1.1.0",
    "@angular-eslint/schematics": "1.1.0",
    "@angular-eslint/template-parser": "1.1.0",
    "@angular/cli": "11.1.1",
    "@angular/compiler-cli": "11.1.0",
    "@types/jasmine": "3.6.3",
    "@types/node": "14.14.22",
    "@typescript-eslint/eslint-plugin": "4.14.1",
    "@typescript-eslint/parser": "4.14.1",
    "@tailwindcss/aspect-ratio": "0.2.0",
    "@tailwindcss/forms": "0.2.1",
    "@tailwindcss/line-clamp": "0.2.0",
    "@tailwindcss/typography": "0.4.0",
    "codelyzer": "6.0.1",
    "eslint": "7.18.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "31.3.3",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "http-server": "0.12.3",
    "jasmine-core": "3.6.0",
    "jasmine-spec-reporter": "6.0.0",
    "karma": "6.0.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage": "2.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "postcss-import": "14.0.0",
    "postcss-loader": "4.2.0",
    "postcss-scss": "3.0.4",
    "protractor": "7.0.0",
    "tailwindcss": "2.0.2",
    "ts-node": "9.1.1",
    "typescript": "4.1.3"
  }
</pre></code>

Angular.json
<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "MijnHvaStudent": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "webpack.config.js"
            },
            "outputPath": "dist/MijnHvaStudent/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest"
            ],
            "styles": [
              "src/assets/theme/custom-theme.scss",
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb",
                  "maximumError": "10kb"
                }
              ],
              "serviceWorker": true,
              "ngswConfigPath": "ngsw-config.json"
            }
          }
        },
        "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "MijnHvaStudent:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "MijnHvaStudent:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-builders/custom-webpack:extract-i18n",
          "options": {
            "browserTarget": "MijnHvaStudent:build"
          }
        },
        "test": {
          "builder": "@angular-builders/custom-webpack:karma",
          "options": {
            "customWebpackConfig": {
              "path": "webpack.config.js"
            },
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "codeCoverage": true,
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-builders/custom-webpack:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "MijnHvaStudent:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "MijnHvaStudent:serve:production"
            }
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/MijnHvaStudent/server",
            "main": "src/main.server.ts",
            "tsConfig": "tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "outputHashing": "media",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "sourceMap": false,
              "optimization": true
            }
          }
        },
        "app-shell": {
          "builder": "@angular-devkit/build-angular:app-shell",
          "options": {
            "browserTarget": "MijnHvaStudent:build",
            "serverTarget": "MijnHvaStudent:server",
            "route": "shell"
          },
          "configurations": {
            "production": {
              "browserTarget": "MijnHvaStudent:build:production",
              "serverTarget": "MijnHvaStudent:server:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "MijnHvaStudent",
  "cli": {
    "analytics": "b6e2fd77-8580-43ff-952f-0092ab51f96a"
  }
}

</code></pre>

webpack.config.js
<pre><code>
module.exports = {
  module: {
    rules: [
      {
        test: /\.scss$/,
        loader: 'postcss-loader',
        options: {
          postcssOptions: {
            ident: 'postcss',
            syntax: 'postcss-scss',
            plugins: ['postcss-import', 'tailwindcss', 'autoprefixer'],
          },
        },
      },
    ],
  },
}

</code></pre>

**Anything else relevant?**

We are using tailwind scss.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the  @angular-builders/custom-webpack project or file an issue on their issue tracker.

**Comment by JordyRoelofs** [comment]
> 
> 
> I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the @angular-builders/custom-webpack project or file an issue on their issue tracker.

Alright, sorry! my mistake
