### ISSUE TITLE
@schematics/angular ast-utils references embedded typescript which leads to version conflicts

### ISSUE THREAD

**Issue by OysteinAmundsen** [angular/angular-cli#19885]
# 🐞 @schematics/angular ast-utils references embedded typescript which leads to version conflicts

I hope this is the right repository. When searching for @schematics/angular, this was referenced by npm. If not, please direct me to the appropriate location for bug reports. 

### Is this a regression?

 I'm not sure if this is a regression or if I just got lucky in a previous version where my local typescript dependency and the referenced embedded typescript version was the same.

### Description

 Given the following code:
```typescript
import * as ts from 'typescript';
import { strings } from '@angular-devkit/core';
import { buildRelativePath} from '@schematics/angular/utility/find-module';
import { addImportToModule } from '@schematics/angular/utility/ast-utils';

export function updateModule(options: Schema): Rule {
  return (host: Tree, context: SchematicContext) => {
    const modulePath = options.module;
    const sourceText = host.read(modulePath).toString('utf-8');
    const source = ts.createSourceFile(modulePath, sourceText, ts.ScriptTarget.Latest, true);

    const widgetPath =
      `/${options.path}/` + (strings.dasherize(options.name) + '/') + strings.dasherize(options.name) + '.module';
    const relativePath = buildRelativePath(modulePath, widgetPath);
    const classifiedName = strings.classify(`${options.name}Module`);
   
    // --> This is where the error happens. The `source` object is incompatible with what `addImportToModule` expects
    const declarationChanges = addImportToModule(source, modulePath, classifiedName, relativePath);

    const declarationRecorder = host.beginUpdate(modulePath);
    for (const change of declarationChanges) {
      if (change instanceof InsertChange) {
        declarationRecorder.insertLeft(change.pos, change.toAdd);
      }
    }
    host.commitUpdate(declarationRecorder);
    return host;
  };
}
```

## 🔥 Exception or Error
<pre><code>tools/generators/widget/index.ts:44:50 - error TS2345: Argument of type 'import("~/node_modules/typescript/lib/typescript").SourceFile' is not assignable to parameter of type 'import("~/node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript").SourceFile'.
  Types of property 'kind' are incompatible.
    Type 'import("~/node_modules/typescript/lib/typescript").SyntaxKind.SourceFile' is not assignable to type 'import("~/node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript").SyntaxKind.SourceFile'.

44     const declarationChanges = addImportToModule(source, modulePath, classifiedName, relativePath);
                                                    ~~~~~~

Found 1 error.
</code></pre>

## Possible workaround:

Following the `addImportToModule` function, I find @schematics/angular/utility/ast-utils.d.ts having the following import:
```typescript
import * as ts from '../third_party/github.com/Microsoft/TypeScript/lib/typescript';
```
instead of what I was expecting (and what is used elsewhere in the schematics framework):
```typescript
import * as ts from 'typescript';
```

I got my custom schematics working by importing the two versions of typescript side-by-side:
```typescript
import * as schema_ts from '@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript';
import * as ts from 'typescript';

...
    const source = schema_ts.createSourceFile(modulePath, sourceText, schema_ts.ScriptTarget.Latest, true);
...
    const declarationChanges = addImportToModule(source, modulePath, classifiedName, relativePath);
```

But this is kind of messy... 


## 🌍 Your Environment
<pre><code>Angular CLI: 11.1.1
Node: 12.16.1
OS: win32 x64

Angular: 11.1.0
... animations, cdk, cdk-experimental, common, compiler
... compiler-cli, core, forms, google-maps, language-service
... material, platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.1.1
@schematics/angular             11.0.6
@schematics/update              0.1101.1
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Anything else relevant?**
<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by alan-agius4** [comment]
Hi @OysteinAmundsen,

Thanks for opening this request. However, the root cause of the problem is that you are using private APIs which are not intended to be used by 3rd parties.

Anything which requires a deep import, ie: anything which cannot be imported from `@schematics/angular` is to be considered as private API.

**Comment by OysteinAmundsen** [comment]
Hmm.. 🤔I really need these functions from @schematics/angular/utility:
* `addImportToModule`
* `buildRelativePath`
* `findModuleFromOptions`
* `getWorkspace`
* `parseName`

Is anything with similar functionality exposed in any included public api? Is there like a common library I can use which can give me this functionality or is this perhaps something which is planned to be released in the future? I would rather reuse something existing than implement this functionality from scratch. 

The usefulness of the schematics generator is really limited if the use-case is just to script executions of existing schematics, and navigating source code is hard and already implemented here...

**Comment by alan-agius4** [comment]
There is a plan to have a public API which include helpful utils but there is no ETA for this https://github.com/angular/angular-cli/issues/15335

At the point, the best option would be to copy the function that you need in your project. As those options are private and can be changed or removed in any version.

**Comment by OysteinAmundsen** [comment]
Thank you for your help. :-)
