### ISSUE TITLE
angular cli 11.1.1 hmr still does not work

### ISSUE THREAD

**Issue by Y2zz** [angular/angular-cli#19887]
I created a demo project with cli and added the antd component library. When I entered the code in `modal.component.html`, hmr did not work properly and the modal was closed.

https://github.com/Y2zz/test-angular-hmr

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.1
Node: 12.20.1
OS: win32 x64

Angular: 11.1.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@angular/cli                    11.1.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Comment by Y2zz** [comment]
@alan-agius4 Hope to get your attention

**Comment by alan-agius4** [comment]
Hi @Y2zz,

This is the expected behaviour. Since the modal, is stateless. The root cause of this is the same as #19867 and also related to angular/angular#39367. The reason why this is happening is, that for every change in a component including styles and templates a reinitialization of the entire application is being done.

I suggest you subscribe to the above mentioned issues.

Thanks.

**Comment by Y2zz** [comment]
Ok
