### ISSUE TITLE
ETA updated files corresponding to docs

### ISSUE THREAD

**Issue by goowikns** [angular/angular-cli#1989]
Hi,

I know this is still beta, but following docs with incorrect information is quite difficult :)

Last issue I'm having was the configuration of scss #1780 

@filipesilva mentioned there would be an update soon adding the styles.css file and I suppose also the updated webpack so unit test would work again (instead of going through commands to update it).

So is there any way to get an ETA on this update he is talking about in #1780 ?

As I'm anxious to start my project.

Thanks in advance

**Comment by avatsaev** [comment]
+1

**Comment by ajrauen** [comment]
+2

**Comment by filipesilva** [comment]
It's out now as `beta.14`. It took a while yeah :/
