### ISSUE TITLE
Does Angular 2 or Angular 2 CLI have (or plan to have) an addon system similar to Ember CLI's?

### ISSUE THREAD

**Issue by jettaprime** [angular/angular-cli#199]
I'm not sure if it's specified or obscurely mentioned in any docs somewhere, but does Angular 2 or Angular 2 CLI have or plan to have an addon system similar to that of Ember CLI?

I'm curious about the idea of shareable Angular 2 components, Angular 1/2 directives, services, etc. that can be imported into your Angular 2 app.

**Comment by filipesilva** [comment]
It does currently, on master!

See here https://github.com/angular/angular-cli#installing-a-3rd-party-library
