### ISSUE TITLE
ng build --prod not compiling manually included  type definitions (.d.ts) files

### ISSUE THREAD

**Issue by amirgc** [angular/angular-cli#19904]
- [ ] new
- [x] build
- [ ] serve
- [ ] test

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.3.28

### Description

I have a angular library which has the description files *.d.ts. in a below structure
```

            ├projects 
            ├     ├my-lib
            │     │    ├ src
            │     │    │  ├ lib
            │     │    │  │   ├ my-typedef.d.ts
            │     │    │  │      
            │     │    │  │
            │     │    │  └public_apit.ts
            │     │    │  
            │     └    └ tsconfig.lib.json
            └src
```

On tsconfig.lib.json i have include it like below:

```
"include": [
    "src/lib/my-typedef.d.ts"
  ],
```
```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "declaration": true,
    "declarationMap": true,
    "inlineSources": true,
    "types": [],
    "lib": [
      "dom",
      "es2018"
    ]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  },
  "include": [
    "src/lib/my-typedef.d.ts"
  ],
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}

```
Before upgrading to 10 it was set to angular 8. This files were compiled in the final build package, but after Angular 10. I am facing this issue. though other files are there but my-typedef.d.ts .

I see on angular upgrade guidelines that we need to add manually but not sure what is the correct way.

> We have updated the tsconfig.app.json to limit the files compiled. If you rely on other files being included in the compilation, such as a typings.d.ts file, you need to manually add it to the compilation.

## 🔬 Minimal Reproduction

repo to the issue: https://github.com/amirgc/angular10-ng-build.git
1. Download the repo.
2. npm install
3. ng build --prod
## 🔬 Expectation

build package should include the file my-typedef.d.ts.

**Comment by alan-agius4** [comment]
This is expected as per TypeScript behaviour, where type definitions are not emitted.

To emit the `.d.ts` you can use the `assets` option, or alternatively change the file to a `.ts` extensions.

See https://github.com/ng-packagr/ng-packagr/issues/1727 for more information.
