### ISSUE TITLE
Feature Request: generate responsive CSS template every time ng g c is being called

### ISSUE THREAD

**Issue by danhadzami** [angular/angular-cli#19901]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Hi Angular CLI Team,

As the title says, I think it would be great to have a responsive CSS template included every time a command of `ng g c component` is called.

### Describe the solution you'd like
The CSS template could be as simple as this:

```
@media only screen and (max-width : 1200px) {

}
@media only screen and (max-width : 992px) {

}
@media only screen and (max-width : 768px) {
    
}
@media only screen and (max-width : 480px) {

}
```

Thank you

**Comment by alan-agius4** [comment]
@danhadzami,

Thanks for this request. Adding these changes is not in the roadmap of the Angular CLI.

This change will cause extra code that needs to be removed by users who don’t want to use this pattern. I can also see, that users using SCSS or other CSS preprocessors, the breakpoint values will be coming from preconfigured variables or even the entire `@media` block is generated with a mixin. Like such: https://dev.to/heytulsiprasad/easy-to-write-media-queries-using-sass-mixins-1p2f

Hence, for this use-case, it is recommended to extend the component schematic with the desired differences.
