### ISSUE TITLE
Providing exact repositories for package.json and Python Installation Guide

### ISSUE THREAD

**Issue by ryananthonyandal** [angular/angular-cli#1990]
Issue creating new project under **angular-cli 1.0.0-beta.11-webpack.8**:

INSTRUCTIONS
Upon creating new project using command
-_ng new PROJECT_NAME_

Run
-_cd PROJECT_DIRECTORY_
-_npm install_

**Error Messages**
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Releas
e/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.
3.0 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\JavaEE\Angular Project\Angular-Web\node_m
odules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\JavaEE\Angular Project\Angular-Web\node_modules\node-gy
p\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 6.1.7601

**Warning Messages**
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp inst
all --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.14
npm WARN enoent ENOENT: no such file or directory, open 'C:\JavaEE\Angular Proje
ct\Angular-Web\node_modules\@angular\compiler-cli\package.json'
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but
 none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev bu
t none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server
@^2.0.0-rc.5 but none was installed.
npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x b
ut none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but no
ne was installed.

**Current Set-up** (Default generated set-up, replace rc5 -> rc6)
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "core-js": "^2.4.0",
    "rxjs": "5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.11-webpack.8",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "^2.0.0"
  }
}

**Suggestions**
-Please provide exact version under package.json
-Also please provide instructions for Python Installation

**Comment by filipesilva** [comment]
`node-pre-gyp ERR!` and `gyp ERR!` are not not NPM errors. As long as your `npm install` does not end with `npm ERR` then the installation was successful and you can use Angular CLI.

These errors appear because of some third party dependencies. When/if https://github.com/webpack/compression-webpack-plugin/pull/34 is merged then we can update and not have these messages.
