### ISSUE TITLE
App not using es5 transpiled library

### ISSUE THREAD

**Issue by andreaslarssen** [angular/angular-cli#19909]
### Description

I'm following the guide at https://angular.io/guide/creating-libraries to create a library. I build it using this config: 
```
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es5",
    "declaration": true,
    "inlineSources": true,
    "types": [],
    "lib": [
      "dom",
      "es2018"
    ]
  },
  "angularCompilerOptions": {
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "enableResourceInlining": true
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}
```

The only thing I've changed from what's included out of the box, is that I've changed the target from es2015 to es5.
After publishing it to npm, and installing it in my app, I try to run my app (Angular 8) using `ng serve --configuration es5`.

The es5 configuration says:

```
 "configurations": {
    "es5": {
      "tsConfig": "./tsconfig.es5.json"
    }
}
```

tsconfig.es5.json:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "target": "ES5",
  }
}
```

tsconfig.json:
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "ESNext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "ES2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "ES2018",
      "DOM"
    ],
    "paths": {
      "@config/*": ["app/config/*"],
      "@core/*": ["app/core/*"],
      "@environments/*": ["environments/*"],
      "@modules/*": ["app/modules/*"],
      "@requests/*": ["app/core/request-interfaces/*"],
      "@responses/*": ["app/core/response-interfaces/*"],
      "@shared/*": ["app/shared/*"]
    }
  },
  "angularCompilerOptions": {
    "enableIvy": false
  }
}
```

When running my app as described, I'm getting this error from the imported library:
`Uncaught TypeError: Class constructor PackageClass cannot be invoked without 'new'`

It's triggered by me extending a class from the package:
`export class MyClass extends PackageClass {} `

I understand that this error is triggered by es2015 not supporting the class keyword, but shouldn't building the library with es5 target prevent my app from using it like this? I can't find anything in the library documentation saying anything about supporting es5 browsers.

### Reproduction Steps**
See above

### Expected vs Actual Behavior**
My app should use the provided es5 scripts, but seems to use the es2015 scripts?

## 🔥 Exception or Error
<pre><code>
Uncaught TypeError: Class constructor PackageClass cannot be invoked without 'new'
    at new PackageClass (package.config.ts:6)
    at _createClass (core.js:20277)
    at _createProviderInstance (core.js:20251)
    at initNgModule (core.js:20184)
    at new NgModuleRef_ (core.js:20893)
    at createNgModuleRef (core.js:20882)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (core.js:29847)
    at NgModuleFactory_.push../node_modules/@angular/core/fesm5/core.js.NgModuleFactory_.create (core.js:30555)
    at core.js:26748
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
</code></pre>

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

If the library and application are not within the same repo, please do so for both.

**Comment by andreaslarssen** [comment]
# App:
```
Angular CLI: 8.2.2
Node: 10.16.3
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.2
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular/cdk                      8.2.3
@angular/cli                      8.2.2
@angular/http                     7.2.16
@ngtools/webpack                  8.3.29
@schematics/angular               8.2.2
@schematics/update                0.802.2
rxjs                              6.6.3
typescript                        3.5.3
webpack                           4.39.2
```

# Library:
```
Angular CLI: 10.0.8
Node: 10.19.0
OS: linux x64

Angular: 10.0.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.8
@angular-devkit/build-angular      0.1000.8
@angular-devkit/build-ng-packagr   0.1000.8
@angular-devkit/build-optimizer    0.1000.8
@angular-devkit/build-webpack      0.1000.8
@angular-devkit/core               10.0.8
@angular-devkit/schematics         10.0.8
@angular/cli                       10.0.8
@ngtools/webpack                   10.0.8
@schematics/angular                10.0.8
@schematics/update                 0.1000.8
ng-packagr                         10.1.2
rxjs                               6.5.5
typescript                         3.9.7
webpack                            4.43.0
```

**Comment by alan-agius4** [comment]
Hi @andreaslarssen,

Libraries are not backward compatible, they are only forward compatible. In this case you are experiencing one of the incompatablitles. Since Angular version 10, ES5 bundles are no longer built and distributed in NPM packages. When your application targets ES5 the Angular CLI will downlevel the distributed ES2015 code to ES5.

More info: 
[Changelog](https://github.com/angular/angular/blob/10.0.x/CHANGELOG.md#breaking-changes)
[Angular Package Format](https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/preview)

**Comment by andreaslarssen** [comment]
@alan-agius4 Aha. Good to know. Should probably be mentioned at https://angular.io/guide/creating-libraries? It says that it's not recommended to publish Ivy libraries to NPM, but my Angular 10 library has this config:

```
"angularCompilerOptions": {
    "enableIvy": false
}
```

... which led me to think that it was taken care of.

Regarding:

> When your application targets ES5 the Angular CLI will downlevel the distributed ES2015 code to ES5.

Could you please clarify what you mean? I interpret that as that my app would downlevel any third party es2015 scripts to es5, but that's not the case, is it?

**Comment by alan-agius4** [comment]
> Could you please clarify what you mean? I interpret that as that my app would downlevel any third party es2015 scripts to es5, but that's not the case, is it?

Indeed this is not the case, because this was introduced in Angular CLI 10+

The fact that libraries are not backward compatible, is not related to Ivy, but rather it was always the case. We should probably indeed mention it in https://angular.io/guide/creating-libraries

**Comment by andreaslarssen** [comment]
@alan-agius4 Downleveling third party scripts to es5 is part of Angular10+? Sorry about the questions, I'm sure I could find that elsewhere.

I'll add an PR to the docs when I find the time. Thanks for your help!

**Comment by alan-agius4** [comment]
> Downleveling third party scripts to es5 is part of Angular10+

Yes.
