### ISSUE TITLE
The `doc` command never exits

### ISSUE THREAD

**Issue by d3lm** [angular/angular-cli#19912]
When you for instance run `ng doc router`, then it does open the URL as expected, but then command never exits. You have to manually kill the process (e.g. CTRL-C). The reason for this is that it's using `open` internally and wraps it in a promise. However, the promise is never resolved, so the process will stay alive. Here's the code:

https://github.com/angular/angular-cli/blob/efb97c87f023497dc59a2f4fa3825a2ca78606da/packages/angular/cli/commands/doc-impl.ts#L54-L58

I am not sure if I am missing something, but the promise should be resolved pretty much immediately, because `open` is also instructed to not wait.

I am happy to fix this in a PR.

**Comment by alan-agius4** [comment]
@d3lm, I the proposed fix does make sense. Please feel free to open a PR.

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/19915
