### ISSUE TITLE
@ngtools/webpack _setupOptions basePath detection might use wrong path

### ISSUE THREAD

**Issue by kroeder** [angular/angular-cli#19913]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build - **I assume it's build, I'm using the `AngularCompilerPlugin` as webpack plugin**

### Description

While I was debugging the `AngularCompilerPlugin` for https://github.com/storybookjs/storybook/issues/13768 I noticed that the selection order of the `basePath` might be wrong in `_setupOptions`. (https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L169)

I need to use the webpack plugin directly for the above-mentioned issue. 

**Webpack configuration**

```typescript
      new AngularCompilerPlugin({
        tsConfigPath: tsLoaderOptions.configFile, // ./some-dir/.storybook/tsconfig.json
        basePath: path.resolve(configDir, '../'), // ./some-dir/
        // ...
      }),
```

**What the basePath code does**

All my comments refer to the paths I set above in the webpack configuration

```typescript
// https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/angular_compiler_plugin.ts#L169

/*
        AngularCompilerPlugin Webpack Input
        tsConfigPath: './some-dir/.storybook/tsconfig.json'
        basePath: './some-dir/'
 */

this._tsConfigPath = forwardSlashPath(options.tsConfigPath);

// Check the base path.
const maybeBasePath = path.resolve(process.cwd(), this._tsConfigPath);
let basePath = maybeBasePath;
if (fs.statSync(maybeBasePath).isFile()) {
  basePath = path.dirname(basePath); 
}

/*** basePath === '/some-absolute-path/some-dir/.storybook ***/

if (options.basePath !== undefined) {
  basePath = path.resolve(process.cwd(), options.basePath);
}

/*** basePath === '/some-absolute-path/some-dir/ ***/

// Parse the tsconfig contents.
const config = readConfiguration(this._tsConfigPath);
if (config.errors && config.errors.length) {
  throw new Error(formatDiagnostics(config.errors));
}

this._rootNames = config.rootNames;
this._compilerOptions = { ...config.options, ...options.compilerOptions };
this._basePath = config.options.basePath || basePath || ''; // <--- probably wrong order

/*** 
this._basePath favors the tsconfig basePath of the project over the basePath 
that was passed in via the AngularCompilerPlugin 
***/
```

The code that does that is this: https://github.com/angular/angular/blob/master/packages/compiler-cli/src/perform_compile.ts#L124

It returns the TS project directory of the passed in `tsConfigPath` in the Webpack configuration. I might be wrong but this means I cannot overwrite the basePath of the TS project by passing in a `basePath` property in the `AngularCompilerPlugin` 

```typescript
      new AngularCompilerPlugin({
        tsConfigPath: tsLoaderOptions.configFile,
        basePath: path.resolve(configDir, '../'), // this cannot be used alongside with tsConfigPath 
        // ...
      }),
```

**Expectation**

```typescript
// change the selection order from 
//     this._basePath = config.options.basePath || basePath || '';
// to 
this._basePath = basePath || config.options.basePath || '';
```

## 🔬 Minimal Reproduction

I tried to reproduce this with a new angular project + a custom Webpack configuration but ran into different errors during the setup. If my above-mentioned assumptions aren't enough I'll try to provide a minimal reproduction or try to write a test using this repo.

## 🔥 Exception or Error

It favors the `tsConfigPath` TS project basePath over the `basePath` option of the `AngularCompilerPlugin`

## 🌍 Your Environment

```
    "@angular-devkit/build-angular": "~0.1100.1",
    "@angular-devkit/core": "^11.0.6",
    "@angular/common": "^11.0.9",
    "@angular/compiler": "^11.0.9",
    "@angular/compiler-cli": "^11.0.9",
    "@angular/core": "^11.0.9",
    "@angular/forms": "^11.0.9",
    "@angular/platform-browser": "^11.0.9",
    "@angular/platform-browser-dynamic": "^11.0.9",
    "@ngtools/webpack": "^11.0.7",
```

**Comment by alan-agius4** [comment]
Hi @kroeder, 

Indeed the `basePath` here is only used as a fallback. The order is as follows, (First one wins)

1) `basePath` defined in Angular Plugin `compilerOptions` option
1) `basePath` defined in TypeScript configuration file
2) `basePath` returned by TypeScript
2) `basePath` defined as Angular Plugin option
3) TypeScript configuration directory path

Mostly the `basePath` option is there for legacy behaviour and in the new experimental plugin, this is no longer available.  https://github.com/angular/angular-cli/blob/aae0083b77f34e70e84b70a5c5ca42940d5aef68/packages/ngtools/webpack/src/ivy/plugin.ts#L38-L47

For the current stable versions you can override the basePath as follows;
```ts
new AngularCompilerPlugin({
  compilerOptions: {
    basePath: '',
  }
}),
```

**Note:** changing the `basePath` might break several features such as path mappings, file replacements and NGCC.

**Comment by alan-agius4** [comment]
@kroeder, I am closing this since there is nothing actionable here. 

Feel free to reply here if you feel otherwise.
