### ISSUE TITLE
"BrowserslistError: Unknown version 88 of edge" when building library project

### ISSUE THREAD

**Issue by jgbpercy** [angular/angular-cli#19937]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes this project built with 11.0.x

### Description

Library package fails to build with 11.1.x with the following error:

<pre><code>
------------------------------------------------------------------------------
Building entry point '@capp/angular'
------------------------------------------------------------------------------
× Compiling TypeScript sources through NGC
ERROR: Unknown version 88 of edge
An unhandled exception occurred: Unknown version 88 of edge
</code></pre>

#### Trace from log
<pre><code>
[error] BrowserslistError: Unknown version 88 of edge
    at Function.select (C:\Source\CAPP.SharedAngular\node_modules\browserslist\index.js:1102:17)
    at C:\Source\CAPP.SharedAngular\node_modules\browserslist\index.js:336:33
    at Array.reduce (<anonymous>)
    at resolve (C:\Source\CAPP.SharedAngular\node_modules\browserslist\index.js:318:18)
    at browserslist (C:\Source\CAPP.SharedAngular\node_modules\browserslist\index.js:444:21)
    at Browsers.parse (C:\Source\CAPP.SharedAngular\node_modules\autoprefixer\lib\browsers.js:63:12)
    at new Browsers (C:\Source\CAPP.SharedAngular\node_modules\autoprefixer\lib\browsers.js:46:26)
    at loadPrefixes (C:\Source\CAPP.SharedAngular\node_modules\autoprefixer\lib\autoprefixer.js:98:20)
    at plugin (C:\Source\CAPP.SharedAngular\node_modules\autoprefixer\lib\autoprefixer.js:109:20)
    at LazyResult.run (C:\Source\CAPP.SharedAngular\node_modules\ng-packagr\node_modules\postcss\lib\lazy-result.js:288:14)
</code></pre>

## 🔬 Minimal Reproduction

Not sure I can create a minimal repro, but if needed I can probably share the code where this happens via a private repo tomorrow (UK time)

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.1.2
Node: 14.15.1
OS: win32 x64

Angular: 11.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             11.1.2
@schematics/update              0.1101.2
ng-packagr                      11.1.2
rxjs                            6.6.3
typescript                      4.0.2

</code></pre>

Also tried and had same issue with 11.1.1.

### Other Info

Application projects in the same repo seem to build ok.

Have tried clearing node_modules and re-running `npm i`.

Also tried copying the .browserlist file from the application project in to the library project to see if that made a difference.

**Comment by alan-agius4** [comment]
Have to tried to removing the lock file after removing `node_modules`?

**Comment by jgbpercy** [comment]
Eugh, yep, sorry it'd been so long since I had to nuke node_modules that I forgot about the lock file...

Thanks!
