### ISSUE TITLE
Multiple web workers results in unavoidable "...is part of the TypeScript compilation but it's unused." warning.

### ISSUE THREAD

**Issue by jamespearce2006** [angular/angular-cli#19938]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: @angular/cli@10.0.1
(This is the last version we used before updating to 11)

### Description

An Angular project that contains two or more web workers, which run different code, will generate the following warnings, which can not be resolved or disabled:

`
Warning: filename is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
`

This is because there is a single tsconfig.worker.json, regardless of how many workers there are defined. For example, if I have two workers defined, each with their own code, each importing different modules, I'll get warnings because the modules are getting compiled for the bundles for both workers.

### Create a new project:
```ng new webwrkr```

### Add two workers
```
ng generate web-worker worker-1
ng generate web-worker worker-2
```

### Modify the app.component.ts to create the workers:
```
  ngOnInit() {
    let worker1 = new Worker('./worker-1.worker', { name: "worker-1", type: "module" });
    let worker2 = new Worker('./worker-2.worker', { name: "worker-2", type: "module" });
  }
```

### Create something for the workers to import:
worker-1.import.ts
```
export class Worker1Stuff {
    public doSomething() {
        console.log("Hello from worker 1");
    }
}
```

worker-2.import.ts
```
export class Worker2Stuff {
    public doSomething() {
        console.log("Hello from worker 2");
    }
}
```

### Modify the workers to import and use the above classes:
worker-1.worker.ts:
```
/// <reference lib="webworker" />
import { Worker1Stuff } from './worker-1.import';

addEventListener('message', ({ data }) => {
  const response = `worker response to ${data}`;
  postMessage(response);

  let worker1Stuff = new Worker1Stuff();
  worker1Stuff.doSomething();
});
```

worker-2.worker.ts
```
/// <reference lib="webworker" />
import { Worker2Stuff } from './worker-2.import';

addEventListener('message', ({ data }) => {
  const response = `worker response to ${data}`;
  postMessage(response);

  let worker2Stuff = new Worker2Stuff();
  worker2Stuff.doSomething();
});
```

## 🔥 Exception or Error
Running "ng build" results in the following output, with the given warnings:
```
√ Browser application bundle generation complete.
√ Copying assets complete.
√ Index html generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.09 MB
polyfills.js        | polyfills     | 127.65 kB
main.js             | main          |  56.61 kB
runtime.js          | runtime       |   6.15 kB
styles.css          | styles        | 118 bytes

                    | Initial Total |   2.28 MB

Build at: 2021-02-02T19:35:15.270Z - Hash: 52377778ecf6aa486b1c - Time: 6077ms

Warning: C:/TEMP/temp-proj/webwkr/src/app/worker-2.import.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/TEMP/temp-proj/webwkr/src/app/worker-2.worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/TEMP/temp-proj/webwkr/src/app/worker-1.import.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: C:/TEMP/temp-proj/webwkr/src/app/worker-1.worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```

The warnings are caused by this line in tsconfig.worker.json:
```
  "include": [
    "src/**/*.worker.ts"
  ]
```

Attempting to remove this include results in an error. Ideally, there should be a way of disabling these warnings, or specifying different tsconfig files for each worker.

## 🌍 Your Environment
```
Angular CLI: 11.1.2
Node: 12.13.1
OS: win32 x64

Angular: 11.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
```

**Comment by glued** [comment]
I'm still seeing this issue as reported earlier
https://github.com/angular/angular-cli/issues/19372

**Comment by PadraigGalvin** [comment]
After upgrading from Angular 10 to 12 I was seeing this issue with files containing only one interface that are used by both the app and the worker.

I was able to fix the issue by updating the way the worker is registered:
 
```patch
- const worker = new Worker('./sync.worker', { type: 'module' });
+ const worker = new Worker(new URL('./sync.worker', import.meta.url));
```

Hope that helps anyone else having this issue!

**Comment by clydin** [comment]
@PadraigGalvin when update to v12, was `ng update` used?  It contains a migration that should automatically adjust the Worker code as shown.

**Comment by PadraigGalvin** [comment]
@clydin, yes, I used `ng  update` to upgrade to version 11 and then version 12. Other migrations seem to have been applied correctly.

**Comment by jamespearce2006** [comment]
@clydin @PadraigGalvin , I just upgraded to Angular 12, and I can see that the "new Worker()" statements have been updated, and previous warnings are no longer emitted.

However, My unit tests now fail - 
```
./my/path/source-file.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: c:\my\path\worker-file.worker.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at c:\my\path\node_modules\@ngtools\webpack\src\ivy\loader.js:43:26
```
Have either of you seen this?

If I revert the code to the old way of calling the Worker constructor, I get the warnings back, but at least my unit tests run.

**Comment by PadraigGalvin** [comment]
@jamespearce2006, I haven't come across that issue.

I would suggest generating a new Angular project, adding a worker with `ng generate web-worker [name]` and comparing the `tsonfig.*.json` and `angular.json` files with those in your project to see if there are any differences.

**Comment by alan-agius4** [comment]
Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
