### ISSUE TITLE
is it possible to extract some commonjs library to a seperate chunk when building?

### ISSUE THREAD

**Issue by steve3d** [angular/angular-cli#19939]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
I have a big site which use a lot of things, like I need `three.js` to create a webgl view, and also I'm using libraries like `anychart`. I know there are a lot of chart library to choose, but we use anychart for the gantt chart.

so when I build the app, angular simply bundles `three.module.js`  and `anychart-bundle.min.js` directly into the chunks. I'm using the lazy load module to separate these, but not all pages in that module use these things, so I'm wondering if there is a way to separate these commonjs bundle into another lazy load chunk, and ignore these chunk when optimizing code? I hope these would increase the building time.

### Describe the solution you'd like
provide an option to extract some commonjs library into a separate lazyload chunk.

### Describe alternatives you've considered
I've tried to use webpack magic comment and use dynamic `import`, when using `dynamic import`, I have to loose all the type hint of that library, which is a huge pain when coding.

**Comment by alan-agius4** [comment]
Hi @steve3d, 

You can use 3rd party builders to extend the Angular CLI, and fine-grain your build to do just what you described above. 

Some of the most popular non official builders are;
- https://github.com/manfredsteyer/ngx-build-plus
- https://github.com/just-jeb/angular-builders

**Important:**
- Custom Webpack configurations are not supported by the Angular tooling team.
- Webpack specific features, including magic comments are not supported by the Angular CLI and might break in future versions.
