### ISSUE TITLE
Several "Property not allowed" messages in angular.json

### ISSUE THREAD

**Issue by chrisleyva** [angular/angular-cli#19969]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [x] config
- [ ] run
- [ ] help
- [ ] version
- [ ] doc

### Description

My `angular.json` file contains several properties which are "not allowed". In the screenshot below, every underlined property states that it is not allowed.

![image](https://user-images.githubusercontent.com/1437143/106943530-8aff3800-66f3-11eb-8de6-8078165340f3.png)

## 🔥 Exception or Error
<pre><code>
Property _____ is not allowed.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular Versions
------
Angular CLI: 10.2.1
Node: 12.16.1
OS: darwin x64  **macOS Catalina 10.15.7** 

Angular: 10.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.7
@angular-devkit/build-angular     0.1001.7
@angular-devkit/build-optimizer   0.1001.7
@angular-devkit/build-webpack     0.1001.7
@angular-devkit/core              10.2.1
@angular-devkit/schematics        10.2.1
@angular/cdk                      10.2.7
@angular/cli                      10.2.1
@angular/flex-layout              10.0.0-beta.32
@angular/material                 10.2.7
@ngtools/webpack                  10.2.1
@schematics/angular               10.2.1
@schematics/update                0.1001.7
rxjs                              6.6.3
typescript                        3.9.7
webpack                           4.46.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi, 

Those options are intended to be used with the browser builder and not supported by the protractor builder.

See below for more information 
https://angular.io/cli/build
https://angular.io/cli/e2e
