### ISSUE TITLE
i.QueueScheduler is not a constructor

### ISSUE THREAD

**Issue by theunreal** [angular/angular-cli#1998]
I'm using Angular 2 Rc.5 with angular-cli 1.0.0-beta.11-webpack.8

When I'm trying to use the ng build --prod command everything works, but when I upload the files in `dist` to my web server, I get the following error when the app loads:

`i.QueueScheduler is not a constructor`

Why I get no errors in my local build or in my prod build but I get this error in my production runtime?

**Comment by filipesilva** [comment]
I have no idea really. If you can get me some repro steps or a github repo I can use, I can try to debug it.

**Comment by mattlanham** [comment]
I had this issue also, not 100% sure what solved it, but I added a gitignore for the dist folder locally, and that's when it started happening. So I removed that, and also set enableProdMode() and now the error has gone, hope that helps @theunreal
