### ISSUE TITLE
ng add angular/material fails even after back-leveling to npm 6

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#19985]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was 10.x

### Description

Attempting to ng add angular/material to a minimal Angular application results in an error during the ng add attempt.

## 🔬 Minimal Reproduction

1. verify that npm is at level 6.x, not 7.x
2. verify that Angular/CLI is at level 11.1.3
3. create a new Angular application via ng new
4. cd to the newly created Angular application.
5. Verify that the newly created app builds clean and can be served clean, especially with the --prod switch.
6. Attempt to ng add angular/material

## 🔥 Exception or Error
ps>ng add angular/material
Installing packages for tooling via npm.
An unhandled exception occurred: npx: installed 5 in 2.849s
ENOENT: no such file or directory, open './package-lock.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-material-source@1.2.2 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-material-source@1.2.2 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<snip>\AppData\Roaming\npm-cache\_logs\2021-02-05T13_49_04_705Z-debug.log
Package install failed, see above.
See "C:\Users\<snip>\AppData\Local\Temp\ng-RaZVNz\angular-errors.log" for further details.

</code></pre>

## 🌍 Your Environment
<pre><code>
ps>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.1.3
Node: 14.15.4
OS: win32 x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.3
@angular-devkit/build-angular   0.1101.3
@angular-devkit/core            11.1.3
@angular-devkit/schematics      11.1.3
@angular/cli                    11.1.3
@schematics/angular             11.1.3
@schematics/update              0.1101.3
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Anything else relevant?**
<pre><code>
ps>npm -version
6.14.11
</code></pre>

**Comment by alan-agius4** [comment]
It does appear that you are trying to install the wrong package. Note the missing`@`.

Can you try again using
```
ng add @angular/material
```

**Comment by fmorriso** [comment]
Closing.
