### ISSUE TITLE
[FEATURE REQUEST]  inbuilt system for acceptance tests.

### ISSUE THREAD

**Issue by QuantumInformation** [angular/angular-cli#2]
Hi there, I was wondering if you plan to have a inbuilt system for acceptance tests similar to ember-cli?

I am interesting in automatically recording stub tests too for this platform if this is the case, I am the author of a similar feature for ember: https://github.com/QuantumInformation/ember-cli-test-recorder

**Comment by filipesilva** [comment]
I am unsure of what you mean. Can you explain it a bit for me please?

**Comment by hansl** [comment]
This feature is really nice, but I don't think we'll support it natively. I'll close this and we can revisit it as part of a third party library. It seems like it's a server-side thing (with a client side script).
