### ISSUE TITLE
Angular 10 not supporting xliffmerge

### ISSUE THREAD

**Issue by coder123er** [angular/angular-cli#20006]
Earlier we were using Angular 7 for our project and the following command worked for us for Localization

"extract-i18n": "ng xi18n projectName --i18n-format xlf --output-path src/locale --i18n-locale en && ng run projectName:xliffmerge"

The above command generated xlf file and also merged it with other localized files.

But now We have upgraded to Angular version 10 and on executing above command the terminal gives us error.

What is the new approach in Angular 10 to generate and merge localized files.

If there is some workaround, Please let me know.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
