### ISSUE TITLE
public folder not serving global assets in webpack.8

### ISSUE THREAD

**Issue by Abubarrett** [angular/angular-cli#2001]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Just updated to the lastest @webpack and the public folder stoped serving global assets. Did the public folder change?

**Comment by LMFinney** [comment]
See #1942

**Comment by Abubarrett** [comment]
thank you :)
