### ISSUE TITLE
Getting PostCSS errors after upgrading from Angular 10 to Angular 11

### ISSUE THREAD

**Issue by wendellestradairely** [angular/angular-cli#20059]
# 🐞 bug report

After upgrading to Angular 11, errors are occurring when running ng serve:

`Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''`

## 🔥 Exception or Error
`
Error: ./src/app/admin/admin.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\admin\admin.component.scss)

Error: ./src/app/admin/dashboard/dashboard.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\admin\dashboard\dashboard.component.scss)

Error: ./src/app/admin/settings/settings.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\admin\settings\settings.component.scss)

Error: ./src/app/admin/tenant/tenant-detail/tenant-detail.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\admin\tenant\tenant-detail\tenant-detail.component.scss)

Error: ./src/app/admin/tenant/tenant-form/tenant-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
[91mLoading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\admin\tenant\tenant-form\tenant-form.component.scss)

Error: ./src/app/admin/tenant/tenant.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\admin\tenant\tenant.component.scss)

Error: ./src/app/app.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\app.component.scss)

Error: ./src/app/authentication/login/login.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\authentication\login\login.component.scss)

Error: ./src/app/hr/departments/department-form/department-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\departments\department-form\department-form.component.scss)

Error: ./src/app/hr/employees/employee-detail/employee-detail.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\employees\employee-detail\employee-detail.component.scss)

Error: ./src/app/hr/employees/employee-detail/job-details/employee-job-details.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\employees\employee-detail\job-details\employee-job-details.component.scss)

Error: ./src/app/hr/employees/employee-detail/job-history/job-history.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\employees\employee-detail\job-history\job-history.component.scss)

Error: ./src/app/hr/employees/employee-detail/personal-info/employee-personal-info.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\employees\employee-detail\personal-info\employee-personal-info.component.scss)     

Error: ./src/app/hr/employees/employee-detail/timesheet/employee-timesheet.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\employees\employee-detail\timesheet\employee-timesheet.component.scss)

Error: ./src/app/hr/employees/employee-detail/timesheet/leave-balances/leave-balances.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\employees\employee-detail\timesheet\leave-balances\leave-balances.component.scss)  

Error: ./src/app/hr/employees/employee-form/employee-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\employees\employee-form\employee-form.component.scss)

Error: ./src/app/hr/positions/position-form/position-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\positions\position-form\position-form.component.scss)

Error: ./src/app/hr/time-off-request-approvers/time-off-request-approver-form/time-off-request-approver-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\hr\time-off-request-approvers\time-off-request-approver-form\time-off-request-approver-form.component.scss)

Error: ./src/app/shared/components/calendar/calendar.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\calendar\calendar.component.scss)

Error: ./src/app/shared/components/calendar/week-view/calendar.week-view.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\calendar\week-view\calendar.week-view.component.scss)

Error: ./src/app/shared/components/dynamic-list/dynamic-list.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\dynamic-list\dynamic-list.scss)

Error: ./src/app/shared/components/notifications-center/notifications-center.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\notifications-center\notifications-center.component.scss)

Error: ./src/app/shared/components/page-not-found/page-not-found.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\page-not-found\page-not-found.component.scss)

Error: ./src/app/shared/components/rich-editor/rich-editor-toolbar.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\rich-editor\rich-editor-toolbar.component.scss)

Error: ./src/app/shared/components/rich-editor/rich-editor.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
mLoading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\rich-editor\rich-editor.component.scss)

Error: ./src/app/shared/components/search-box/search-box.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\shared\components\search-box\search-box.component.scss)

Error: ./src/app/time-management/time-logs/time-log-form/time-log-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\time-management\time-logs\time-log-form\time-log-form.component.scss)

Error: ./src/app/time-management/time-off-requests/time-off-request-form/time-off-request-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\time-management\time-off-requests\time-off-request-form\time-off-request-form.component.scss)

Error: ./src/app/time-management/timesheets/timesheet-details/timesheet-details.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\time-management\timesheets\timesheet-details\timesheet-details.component.scss)        

Error: ./src/app/time-management/timesheets/timesheet-form/timesheet-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\time-management\timesheets\timesheet-form\timesheet-form.component.scss)

Error: ./src/app/time-management/timesheets/timesheets.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\time-management\timesheets\timesheets.component.scss)

Error: ./src/app/welcome/welcome.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\welcome\welcome.component.scss)

Error: ./src/app/workspace/administration/locations/location-form/location-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\administration\locations\location-form\location-form.component.scss)        

Error: ./src/app/workspace/administration/number-sequences/number-sequence-form/number-sequence-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\administration\number-sequences\number-sequence-form\number-sequence-form.component.scss)

Error: ./src/app/workspace/home/getting-started/getting-started.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\home\getting-started\getting-started.component.scss)

Error: ./src/app/workspace/home/home.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\home\home.component.scss)

Error: ./src/app/workspace/security/permissions/permissions.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\security\permissions\permissions.component.scss)

Error: ./src/app/workspace/security/roles/role-form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\security\roles\role-form.component.scss)

Error: ./src/app/workspace/security/security.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\security\security.component.scss)

Error: ./src/app/workspace/security/users/user.form.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\security\users\user.form.component.scss)

Error: ./src/app/workspace/workspace.component.scss
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\app\workspace\workspace.component.scss)

Error: ./node_modules/@clr/icons/clr-icons.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@clr\icons\clr-icons.min.css)
    at Object.emitError (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\webpack\lib\NormalModule.js:173:6)
    at getPostcssOptions (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\utils.js:237:21)
    at Object.loader (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\index.js:65:36)

Error: ./node_modules/@clr/ui/clr-ui.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\@clr\ui\clr-ui.css)
    at Object.emitError (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\webpack\lib\NormalModule.js:173:6)
    at getPostcssOptions (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\utils.js:237:21)
    at Object.loader (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\index.js:65:36)

Error: ./src/assets/themes/clarity-light.min.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\assets\themes\clarity-light.min.css)
    at Object.emitError (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\webpack\lib\NormalModule.js:173:6)
    at getPostcssOptions (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\utils.js:237:21)
    at Object.loader (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\index.js:65:36)

Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "" parser failed: The argument 'id' must be a non-empty string. Received ''

(@C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\src\styles.scss)
    at Object.emitError (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\webpack\lib\NormalModule.js:173:6)
    at getPostcssOptions (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\utils.js:237:21)
    at Object.loader (C:\Projects\HordeflowNg9\HordeFlow\src\Hris\ClientApp\hordeflow\node_modules\postcss-loader\dist\index.js:65:36)
`

**Comment by alan-agius4** [comment]
Hi @wendellestradairely, 

Can you try to remove the node modules and package lock file and install the packages again?

```
rm -rf node_modules package-lock.json
npm i 
```

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by wendellestradairely** [comment]
@alan-agius4 I've figured out why I'm getting those errors. It turned out that postcss config doesn't work in Angular 11. I wasn't having this issue in Angular 10. In v11, I just deleted the postcss config file and the errors are gone.

![image](https://user-images.githubusercontent.com/50942719/107948845-592d8180-6fcf-11eb-97a8-1b48de222ada.png)

**Comment by alan-agius4** [comment]
The Angular CLI already provides autoprefixer out-of-the-box, hence I am not sure why the needed for the above.

Please note that custom Webpack configurations are not supported by the Angular tooling team.
