### ISSUE TITLE
assets mentioned in angular.json are not getting compressed using compression webpack plugin while using @angular-builders/custom-webpack:browser

### ISSUE THREAD

**Issue by aniket7824** [angular/angular-cli#20067]
# 🐞 Bug report

### Command (mark with an `x`)
ng build --prod

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

The issue is introduced once we have migrated to Angular CLI - 11.0.4
It was working fine in Angular CLI - 9.1.12

### Description

While using `@angular-builders/custom-webpack:browser` as a build architect, the assets (mentioned in `assets` array of `angular.json`) are not getting compressed using `compression-webpack-plugin`. On debugging it further, I found that `CompressionPlugin` taps on emit hook (`compiler.hooks.emit.tapPromise`) of webpack 
Pointing the section from the code of compression plugin.
```    
compiler.hooks.emit.tapPromise({
      name: 'CompressionPlugin'
    }, async compilation => {
      const {
        assets
      } = compilation;
```
Now till v9 of Angular CLI all the assets were showing up in `compilation.assets`. But starting from Angular 11, files inside assets are not coming here. And hence `CompressionPlugin` is not able to take up these files for further processing.

Issues that don't have enough info and can't be reproduced will be closed.

## 🌍 Your Environment
Angular CLI - 11.0.4
Webpack - 4.46.0
Compression-webpack-plugin - 4.0.1

**Comment by alan-agius4** [comment]
Hi @aniket7824,

This is expected because since version 10, the copying of assets has been moved outside of Webpack.

Webpack is an implementation detail and using a custom Webpack configuration or specific Webpack features are not supported by the Angular tooling team.

The best resolution would be to compress the assets pre-build and commit them.
