### ISSUE TITLE
Angular.json couldn't found

### ISSUE THREAD

**Issue by kanth233** [angular/angular-cli#20064]
i am deploying a docker image for ionic project so when i running the steps  in dockerfile it is throwing this error like " Local workspace file ('angular.json') could not be found." so i have uninstalled npm and installed latest but doesn't work. so i am attaching some info see if you can help me out.
![angular](https://user-images.githubusercontent.com/57978185/108060625-1fb34f80-707d-11eb-91d2-aba9ce03144a.png)
![angular-cli](https://user-images.githubusercontent.com/57978185/108060686-3a85c400-707d-11eb-8225-fa04c9ee276c.png)
![dockerfile](https://user-images.githubusercontent.com/57978185/108060807-6a34cc00-707d-11eb-801e-34d66ff5d26b.png)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
