### ISSUE TITLE
Not able to set outDir to "../www/"

### ISSUE THREAD

**Issue by crebuh** [angular/angular-cli#2006]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux, Ubuntu 14.04.

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.2
node: 4.4.4
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Update apps.outDir to "../www/" in angular.cli.json and execute ng build prod

> ---------------------------------------------------------------

As described above I'm trying to update the output directory when building the app. I have wrapped a cordova project around the ng2-application so it would be nice to build inside the www-folder (which worked before upgrading to webpack). 

Now the build is always played into a dist folder. In addition the www-folder is always deleted, when I start ng build.

Any advice?

**edit**:

I found an entry in the .ember-cli-file called "output-path" and also set it to "../www/" without success ..

**Comment by robertbaker** [comment]
Upgrade your node to 6.5+, your version is no longer supported.

Having the build output to folder above the project root is not ideal and should not be supported.

You can solve your issue with a copy or move command, or by using an npm script.

**Comment by crebuh** [comment]
@robertbaker 

thanks for you answer. I will solve it with a npm script in the meanwhile.

Why having the build output above the project root is not ideal?

**Comment by kylecordes** [comment]
@robertbaker I am also interested in thoughts on why this "should not be supported". In our projects we often have a client project parallel to a server project - server project might be another Node project or might be 0% JavaScript.

A fully flexible Outdir would make it easy for the client project to emit the bundled output into the server project's web asset directory. Lack that we use an extra NPM script (with a file copying utility), as you described. But it feels superflous, like it is papering over an arbitrary limitation.

**Comment by crebuh** [comment]
What is also very interesting is the fact, that when I copy the dist folder manually one level higher to the root of my project and name it www (so that cordova recognizes the folder as a cordova project) this folder is deleted the next time I'm build the project.

**Comment by swaechter** [comment]
Same problem here: We embed an angular-cli in our Spring boot application:

Source:  src/<projectname>/src/main/angular/
Current build path: src/<project>/src/main/angular/dist
Prefered build path: src/yproject>/src/main/resources/public
Required static resources path for Spring Boot: src/<project>/src/main/resources/public

So, I am looking forward for such a feature. Of course you can copy the dist directory via npm, but what if you run ng in watch mode? Run another script that brute copies the dist directory every time it changes?

**Comment by swaechter** [comment]
@crebuh  ng build -prod --output-path ../resources/public works for me. No .ember-cli file, outDir is "dist" (Dummy value) with 1.0.0-beta.11-webpack.9-4

**Comment by Meligy** [comment]
Note: The specific outcome of this issue has changed as tested in recent versions (beta-15).

No ember related artifacts caused by it.

Also, as mostly mentioned in #2230:

- `../folder`, `.folder`, and `folder` all are the same
- No notable outcome at all that shows anyone is looking at this config key
- It's not OS specific, as it's the same on macOS and Windows
- as mentioned here, `ng build  -o any-path-from-pre-point` still works with all cases from 1st point

**Comment by AurelieV** [comment]
Facing the issue, it seems that the bug is in ember-cli
* packages/angular-cli/models/webpack-build-common.ts => outDir has the correct value in appConfig, but it is overwritted by the options who always has the default value, even if not is provided

**Comment by Microsmsm** [comment]
I tried 
`"outDir": "./../public",` not working 
But in terminal I used
`ng build -op ./../public` it's working 

is it still a bug?
