### ISSUE TITLE
ng e2e does not propagate error exit code anymore

### ISSUE THREAD

**Issue by SebastianSchmidtInovex** [angular/angular-cli#20074]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] e2e

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.1.0
The problem was first seen with version 11.1.4 and confirmed with version 11.2.0

### Description

A (headless) execution of cypress with failing tests no longer returns the error exit code (1 in this case).
This leads to CI pipelines not failing.

## 🔬 Minimal Reproduction
Setup Angular project with cypress (v6.4.0) as e2e tool (architect.e2e.builder: "@nrwl/cypress:cypress" in angular.json) and a failing spec.

run "ng e2e --browser chrome --headless --watch=false"

## 🔥 Exception or Error

The exit code after running the failing test is 0.
Please see attached file "wrong_exit_code.txt"

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.0
Node: 12.13.0
OS: win32 x64

Angular: 11.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@angular/cdk                    11.1.2
@angular/material               11.1.2
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.0.5
[correct_exit_code.txt](https://github.com/angular/angular-cli/files/5996051/correct_exit_code.txt)
[wrong_exit_code.txt](https://github.com/angular/angular-cli/files/5996052/wrong_exit_code.txt)

</code></pre>

**Anything else relevant?**
The output of the correct behaviour is shown in attachment "correct_exit_code.txt".

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the NRWL project or file an issue on their issue tracker.

**Comment by SebastianSchmidtInovex** [comment]
Ah. Thank you for the directions to the right project.
