### ISSUE TITLE
Production build broken since RC6 upgrade.

### ISSUE THREAD

**Issue by asadsahi** [angular/angular-cli#2007]
production build is erroring because of an undefined script

![image](https://cloud.githubusercontent.com/assets/3470892/18305111/e0e7aff2-74dd-11e6-8dc1-062117074df7.png)

When running ng build --prod, it ended up in following error:

![image](https://cloud.githubusercontent.com/assets/3470892/18305228/7b11318e-74de-11e6-8a96-f23ae08f3ee4.png)

Upgraded to Angular 2 RC6 with following environment details:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.3.1
os: win32 x64

**Comment by billdwhite** [comment]
Same here

**Comment by hassanasad** [comment]
Same here.

However i noticed that `ng build --env=prod` does work. I believe it doesn't minify the code though. I researched the error and seems to be a webpack issue.

**Comment by asadsahi** [comment]
@hassanasad its strange that --env=prod doesn't create production build :). 
ng build --env=prod doesn't seem to be a valid command, docs have following as production commands:

ng build --target=production --environment=prod
ng build --prod --env=prod
ng build --prod

ng build createst the same build, so I am not sure if --env=prod is a valid flag or there is some issue with cli.

**Comment by splintercode** [comment]
I believe this was an issue with webpack that has been resolved. This should be fixed with the next update.
https://github.com/angular/angular-cli/pull/2011

**Comment by hansl** [comment]
You're misinterpretting two concepts: `env` and `target`. What `ng build --prod` does is equivalent to `ng build --env=prod --target=prod`. The `--env` only dictates which `environment` file it's using. This allows you to build and debug development code with prod environment.

I'm looking at this. Never seen it before. Is it an open source projet I could repro with?

**Comment by asadsahi** [comment]
@hansl  I have upgraded it to RC7, but I think you should be able to replicate this issue from [one of my repo](https://github.com/asadsahi/ng2fb-bootstrap).

**Comment by hansl** [comment]
There's something wrong with your global / local versions of Angular CLI. I got it working locally the first try; literally just `git clone`, `npm install` then `ng serve`.

**Comment by hansl** [comment]
Actually nevermind, just found the error when running prod. Investigating.

**Comment by hansl** [comment]
Okay found the bug. This is already fixed by #1937.
