### ISSUE TITLE
404 Loading main map - weird url

### ISSUE THREAD

**Issue by Jonesie** [angular/angular-cli#20085]
# 🐞 bug report

### Affected Package
??

### Is this a regression?
NG 10 was ok I think.

### Description
The FireFox browser console shows errors like:

XHR GET https://test.barxui.com/__tryOrUnsub@https://test.barxui.com/main-es2015.a9bb1bb8eb67a9f41008.js.map [HTTP/2 404]

This happens during app load / refreshing the browser.  Does not effect normal operation.
Works fine in Chrome.

## 🔬 Minimal Reproduction

Very hard to create a repro as I have no idea where to start looking for the cause so here is my test site:

https://test.barxui.com/

## 🔥 Exception or Error
<pre><code>
XHR GET https://test.barxui.com/__tryOrUnsub@https://test.barxui.com/main-es2015.a9bb1bb8eb67a9f41008.js.map [HTTP/2 404]

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.2.0
Node: 12.18.0
OS: win32 x64

Angular: 11.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.0
@angular-devkit/build-angular   0.1102.0
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             11.2.0
@schematics/update              0.1102.0
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**
Firefox 85.0.2 (64-bit) on Windows 10.

**Comment by Jonesie** [comment]
> 
> 
> This sounds like your build is not providing the source-maps. So this might be a CLI issue. Transferring to that repository.

No, the maps are there.  The url is mangled somehow.

**Comment by alan-agius4** [comment]
It appears that the map is being loaded by the browser as you'd expect but rather application via an XHR request, I tracked it down to a `_getSourceMap` method, which comes from `ngx-logger.js`. 

![Screenshot 2021-02-19 at 12 55 50](https://user-images.githubusercontent.com/17563226/108501639-e3b50000-72b1-11eb-98be-6a6e7338b703.png)

The bug appears to be in `getCallerDetails` method of the mentioned library.

Note: Typically you wouldn't want to request the sourcemap via an XHR request  as this tends to be several hundreds of megabytes in size and for production you'd want to make these hidden from the user.

**Comment by Jonesie** [comment]
@alan-agius4 Thank you so much.  I'll pass this back to the ngx-logger authors.
