### ISSUE TITLE
Uncaught reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by Chabane** [angular/angular-cli#2008]
Hi,

I have this error after migrating to webpack.8 : 
Uncaught reflect-metadata shim is required when using class decoratorscheckReflect

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Window 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.3.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
It's worked fine with angular-cli@webpack.2. After I upgrated to angular-cli@webpack.8. I got the errors below.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

> decorators.js:173Uncaught reflect-metadata shim is required when using class decoratorscheckReflect @ decorators.js:173(anonymous function) @ decorators.js:175__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ decorators.js:9__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ opaque_token.js:9__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ di.js:16__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ metadata.js:9__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ index.js:17__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ lexer.js:9__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ i18n_parser.js:21__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ extractor_merger.js:24__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ message_bundle.js:22__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ main.bundle.js:76909__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ index.js:17__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ index.js:21__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ simulation.routing.ts:7__webpack_require__ @ bootstrap b71fb3d…:52(anonymous function) @ main.ts:3(anonymous function) @ webcomponents-lite.min.js:12
> client?93b6:71 [WDS] Disconnected!sock.onclose @ client?93b6:71EventTarget.dispatchEvent @ eventtarget.js:51(anonymous function) @ main.js:356

**Comment by Nick0n** [comment]
Getting exactly the same error.

**Comment by deebloo** [comment]
make sure you import the polyfills.ts file in your main.ts file. 
![screen shot 2016-09-07 at 12 11 36 pm](https://cloud.githubusercontent.com/assets/6563621/18319579/4a77a1dc-74f4-11e6-8d81-fcb647b2fc9c.png)

**Comment by spongessuck** [comment]
Shouldn't webpack produce a `polyfills.js` file that gets injected into the page?

**Comment by tonymedrano** [comment]
Hi there, my experimental solution in Windows for now is:
-Got to directory: C:\Users\"Your User"\AppData\Roaming\npm\node_modules\angular-cli

    npm install reflect-metadata
    npm install portfinder

It´s working for me and apply for any platform if you can access the final path as above.
Hope this help.

**Comment by sergio8016** [comment]
Worked on MAC too. Thank you Tony

**Comment by gajerajatin31** [comment]
Thanks @tonymedrano  it's work....

**Comment by Dipesh-Jayswal** [comment]
Thank You Much  @tonymedrano

**Comment by henokbekele** [comment]
terminate and run it again, it will package it
