### ISSUE TITLE
build less, Operation on an invalid type,   No errors in lower version

### ISSUE THREAD

**Issue by billpeace** [angular/angular-cli#20088]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
"@angular-devkit/build-angular": "~0.1100.7",
    "@angular/cli": "~11.1.4",
    "@angular/compiler-cli": "~11.1.2",

no error

"@angular-devkit/build-angular": "^0.1102.1",
    "@angular/cli": "^11.2.1",
    "@angular/compiler-cli": "^11.2.1",

have error

### Is this a regression?

 

"@angular-devkit/build-angular": "~0.1100.7",

build no error

"@angular-devkit/build-angular": "^0.1102.1", 

build have error：Operation on an invalid type

### Description

Error: ./src/styles.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

// ================================================================
.table-size(~'middle', @table-padding-vertical-md, @table-padding-horizontal-md, @table-font-size-md);
^
Operation on an invalid type
      Error in E:\Project\testproject1\node_modules\ng-zorro-antd\table\style\size.less (line 53, column 0)
    at E:\Project\testproject1\node_modules\webpack\lib\NormalModule.js:316:20

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Note: it’s likely this is cause by https://www.npmjs.com/package/less

**Comment by alan-agius4** [comment]
Probably related to https://github.com/angular/angular-cli/commit/cc51432661eb4ab4b6a35513279044adaf9ec4dd

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/20097
