### ISSUE TITLE
ERROR Error: Angular JIT compilation failed: '@angular/compiler' not loaded!

### ISSUE THREAD

**Issue by ponsakthianand** [angular/angular-cli#20115]
The Error I got suddenly while running my app in a development environment using VSCode,

<pre><code>
main.js:7740 ERROR Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (vendor.js:20189)
    at Function.get (vendor.js:33871)
    at getInjectableDef (vendor.js:19941)
    at resolveNgModuleDep (vendor.js:47812)
    at NgModuleRef_.get (vendor.js:48688)
    at resolveDep (vendor.js:49213)
    at createClass (vendor.js:49071)
    at createDirectiveInstance (vendor.js:48882)
    at createViewNodes (vendor.js:60498)
    at callViewAction (vendor.js:60948)

</code></pre>

Also got an error  saying 

<pre><code>Angular extension might not work correctly because ngcc operation failed. Try to invoke ngcc manually by running 'npm/yarn run ngcc'. Please see the extension output for more information.</code></pre>

Package.json contains below
<pre><code>
{
  "name": "dxfsuite",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve -o --proxy-config proxy.conf.json --port 4200",
    "build": "ng build",
    "build-prod": "ng build --prod --stats-json --source-map=false",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/schematics-cli": "^0.901.14",
    "@angular/animations": "~9.0.0",
    "@angular/cdk": "^9.1.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/forms": "~9.0.0",
    "@angular/localize": "^9.1.13",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/router": "~9.0.0",
    "@elastic/apm-rum-angular": "^0.5.0",
    "@fullcalendar/angular": "^4.4.5-beta",
    "@fullcalendar/core": "^4.4.0",
    "@fullcalendar/daygrid": "^4.4.0",
    "@fullcalendar/timegrid": "^4.4.0",
    "@ionic/angular": "^5.5.4",
    "@ng-bootstrap/ng-bootstrap": "^6.0.0",
    "@ng-select/ng-select": "^3.7.2",
    "@swimlane/ngx-charts": "^13.0.2",
    "@types/jquery": "^3.5.5",
    "angular-feather": "^6.1.0",
    "apexcharts": "^3.25.0",
    "bootstrap": "^4.6.0",
    "bootstrap-daterangepicker": "^3.0.5",
    "bootstrap-tagsinput": "^0.7.1",
    "daterangepicker": "^3.0.5",
    "install-peers": "^1.0.3",
    "jquery": "^3.4.1",
    "jqueryui": "^1.11.1",
    "loadash": "^1.0.0",
    "lodash": "^4.17.15",
    "moment": "^2.26.0",
    "moment-timezone": "^0.5.33",
    "ng-apexcharts": "^1.5.8",
    "ng-zorro-antd": "^9.0.0-beta.0",
    "ng2-daterangepicker": "^2.0.12",
    "ngx-filesize": "^2.0.13",
    "ngx-perfect-scrollbar": "^8.0.0",
    "ngx-sortablejs": "^3.1.4",
    "ngx-spinner": "^10.0.1",
    "peity": "^3.3.0",
    "popper.js": "^1.16.1",
    "ramda": "^0.26.1",
    "rxjs": "^6.5.4",
    "service-worker": "0.0.0",
    "sortablejs": "^1.13.0",
    "tslib": "^1.10.0",
    "videogular2": "^7.0.2",
    "vivus": "^0.4.5",
    "web-push": "^3.4.3",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "~9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@ionic/angular-toolkit": "^3.1.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.20.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.7.5"
  }
}

</code></pre>

and itsconfig.json 
<pre><code>
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
</pre></code>

Searched many forums to get this resolved. But nothing is helpful for me.

please help

**Comment by alan-agius4** [comment]
Hi @ponsakthianand, 

Without a reproduction it's hard to tell what's happening. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by ponsakthianand** [comment]
While creating a new app getting some warning

<pre><code>
warning: LF will be replaced by CRLF in .browserslistrc.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .editorconfig.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .gitignore.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in angular.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in e2e/protractor.conf.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in e2e/src/app.e2e-spec.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in e2e/src/app.po.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in e2e/tsconfig.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in karma.conf.js.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package-lock.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app-routing.module.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.component.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.component.spec.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.component.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.module.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/environments/environment.prod.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/environments/environment.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/index.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/main.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/polyfills.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/styles.scss.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/test.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tsconfig.app.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tsconfig.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tsconfig.spec.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tslint.json.
The file will have its original line endings in your working directory
    Successfully initialized git.
</code></pre>

**Comment by ponsakthianand** [comment]
https://github.com/ponsakthianand/issue-Angular-JIT

this is the code with abpve problem

**Comment by alan-agius4** [comment]
Hi @ponsakthianand, 

Can you explain step by step how to replicate the problem? I cloned the reproduction and both `ng serve` and `ng serve --prod` didn't show the above mentioned `Angular JIT compilation failed: '@angular/compiler' not loaded! ` error.

Regarding the NGCC error, I do see an error when this is trying to compile angular-feather, it appears that the version of angular-feather you are using is compatible with Angular 11+ https://github.com/michaelbazos/angular-feather/blob/0d29ff1ee28f4185448a0aefc5db55b0e6e06141/projects/angular-feather/package.json#L26-L29

There also a number of packages which are not in sync with the Angular version you are using, see below;
```
npm WARN @elastic/apm-rum-angular@0.5.1 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @elastic/apm-rum-angular@0.5.1 requires a peer of @angular/router@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular-toolkit@3.1.0 requires a peer of @angular-devkit/architect@^0.1101.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular-toolkit@3.1.0 requires a peer of @angular-devkit/build-angular@^0.1101.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular-toolkit@3.1.0 requires a peer of @angular-devkit/core@^11.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ionic/angular-toolkit@3.1.0 requires a peer of @angular-devkit/schematics@^11.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-select/ng-select@3.7.3 requires a peer of @angular/common@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-select/ng-select@3.7.3 requires a peer of @angular/core@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-select/ng-select@3.7.3 requires a peer of @angular/forms@>=8.0.0 <9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-feather@6.1.0 requires a peer of @angular/common@^11.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN angular-feather@6.1.0 requires a peer of @angular/core@^11.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN karma-jasmine-html-reporter@1.5.4 requires a peer of jasmine-core@>=3.5 but none is installed. You must install peer dependencies yourself.
npm WARN ng-zorro-antd@9.3.0 requires a peer of rxjs@~6.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-sortablejs@3.1.4 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-sortablejs@3.1.4 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-spinner@10.0.1 requires a peer of @angular/common@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-spinner@10.0.1 requires a peer of @angular/core@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN videogular2@7.0.2 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.
```

All, in all, I do see however a number of problems with the reproduction you submitted.
1. `enableIvy` is set to false in your application however, you are using `ngcc` postinstall hook. Using `ngcc` binrary directly is only needed for edge and advanced use cases when using Ivy. I recommand that this is removed and let the Angular CLI process the packages on demand as needed.
2. You are using a number of libraries that are not compatible with the Angular version you are using, some of which are using no longer supported Angular versions.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).
