### ISSUE TITLE
setTimeout is not defined

### ISSUE THREAD

**Issue by renaultyang** [angular/angular-cli#20125]
**the environment of nodeJS and python  is  OK;**
![DE572OCP(N{@{2MH(}_0)9J](https://user-images.githubusercontent.com/73808741/108875938-a85f5c00-7638-11eb-8b8b-b27114f1b10f.png)

**but when I start one project, it did go wrong way**
![setTimeout](https://user-images.githubusercontent.com/73808741/108875459-2c651400-7638-11eb-8324-330bb76f1cd1.png)

what's the hell 'setTimeout'? I've answered  these 3 questions above,but it seem that it didn't work; should I install a lower version cli?

**Comment by alan-agius4** [comment]
`setTimeout` is a Node.JS global. I recommand you re install Node.JS

 This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
