### ISSUE TITLE
Option to turn off progress logging

### ISSUE THREAD

**Issue by NickClark** [angular/angular-cli#2012]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   Any
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   1.0.0-beta.11-webpack.8
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   Stock CLI app. Run `ng build`. See progress.
4. The log given by the failure. Normally this include a stack trace and some
   more information.
5. Mention any other details that might be useful.
   This is mostly for running builds as part of a CI. Logging makes a mess and doesn't work properly when displayed outside of a terminal. Normally when using straight webpack, you'd just pass along the `--no-progress` option.
   
   > ---
   > 
   > Thanks! We'll be in touch soon.

**Comment by victornoel** [comment]
+1 because it is really bothering when ng build is run in continuous integration
