### ISSUE TITLE
Build fail on ERROR

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular-cli#2014]
Hy,

is it somehow possible to make a complete build fail if there is a error during the build?

My situation is the following: I have a CI setup that builds my project, wraps it into a docker and publishes it into a docker repo. If I then want to publish a the new version I use docker to pull the new image and run it. Recently I did exactly that to then discover that the app doesn't work. Looking trough the CI server logs I found out that the production build of angular-cli (beta webpack 8) had an ERROR message, but it did not fail the build. If it would have than no new docker image would have been published and I would have noticed before I published the new version.

Thanks and Greetings

**Comment by filipesilva** [comment]
This is a bug actually. We should have a non-zero exit code for failed builds.

**Comment by Blasz** [comment]
This would be great, I just experienced the same thing. Are there any workarounds we can do ourselves in the meantime?

**Comment by filipesilva** [comment]
Seems related to https://github.com/webpack/webpack/issues/708
