### ISSUE TITLE
Error `Module Build Failed` when using top-level await.

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#20150]
# 🐞 bug report

### Description
When I enable top-level await in Tyoescrpt. (setting module do `esnext`  and set target to `es2017` (or higher)  TS and JS support using top-level await. 

That means that this becomes valid:
```typescript
  const { BrowserModule } = await import('@angular/platform-browser');
  const { NgModule } = await import('@angular/core');

  const { AppRoutingModule } = await import('./app-routing.module');
  const { AppComponent } = await import('./app.component');
  const { HomeComponent } = await import('./home/home.component');
  const { HttpClientModule } = await import('@angular/common/http');

  @NgModule({
    declarations: [AppComponent, HomeComponent],
    imports: [BrowserModule, AppRoutingModule, HttpClientModule],
    providers: [],
    bootstrap: [AppComponent],
  })
  export class AppModule {}
```

This is now valid typescript, which translates into valid modules.
However, When I try to use this with the CLI, I'm facing a syntax error?
![image](https://user-images.githubusercontent.com/1249083/109251988-c40b6380-77ec-11eb-96b6-c10e39139580.png)

This is not a syntax error from typescript. Where does it come from, and why is it there?

When this would work, it enables a way more fine-grained control over lazy-loading, and would cut down bundle-size in a huge way.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.2
Node: 14.15.5
OS: linux x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cli                    11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
This is caused by Webpack 4 which doesn't support top level await. With Webpack 5 it is possible to enable top-level await but it's still in experimental mode.

@clydin thoughts about enabling this experimental feature?

**Comment by clydin** [comment]
Top-level await is currently in stage 3 and changes are still being made to the spec based on issues found during implementation.  Correct implementation of the spec is also complex and defects can result in hard to troubleshoot problems within applications.  Once the Webpack considers its implementation stable and spec compliant, the Angular CLI should be able to enable it by default (assuming Webpack does not enabled it by default first).

Something else to also consider is that top level await usage is recommended to be evaluated from a total application performance perspective.  This is especially relevant in that its usage can cause tasks that can be parallelized to be execute serially and not just in the containing module but also indirectly in parent modules as well.  Combined with the code splitting behavior of bundlers, there can be additional overhead regarding more module loading/parsing/evaluation as well.  The spec overview has several sections discussing this topic: https://github.com/tc39/proposal-top-level-await#will-top-level-await-cause-developers-to-make-their-code-block-longer-than-it-should

**Comment by alan-agius4** [comment]
Following a convo with @clydin. Let’s revisit top level await when Webpack’s implementation in non experimental and spec compliant, likely when this happen we won’t have to do any changes from our end anyways to support this.
