### ISSUE TITLE
suggestion: restructure dist directory

### ISSUE THREAD

**Issue by asnowwolf** [angular/angular-cli#2016]
Currently the dist folder is flatten, I think a nested folder could be better:

- index.html
- js
- css
- images

it's more easier to manage files and better for CDN

**Comment by filipesilva** [comment]
I don't think the CDNs care much about the directory structure overall, nor do I see a reasonable benefit for users. Whatever is in dist is auto-generated, and between bundles, hashes and auto-generated files by webpack there isn't a lot in that dir that's under direct user control.

**Comment by phillip-haydon** [comment]
@filipesilva makes versioning deployments a lot more difficult.
