### ISSUE TITLE
suggestion: generate document automatically?

### ISSUE THREAD

**Issue by eriyu** [angular/angular-cli#2017]
I found I can use [typedoc](https://github.com/TypeStrong/typedoc) to generate 'JSDOC style comment' into document .

![](https://i.imgur.com/FW4uH0Q.png)

If I can use `ng doc` to generate document automatically.

I think it must be better!

**Comment by dtesta** [comment]
Related #102

**Comment by filipesilva** [comment]
@dtesta is right, this one is a dupe of https://github.com/angular/angular-cli/issues/102.
