### ISSUE TITLE
Locally linked UMD bundles break runtime when producing source maps

### ISSUE THREAD

**Issue by smasala** [angular/angular-cli#20182]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Breaking change: https://github.com/angular/angular-cli/commit/d71ee210bf6adcf35b51375de44061fc045421e0#diff-f3bcbd6f6b0756d2178dd69396750fa742093fb7f4668ab284463c0ca348b032R370

### Description

List a local `js/umd` built package in the `package.json` and run `npm i` so it creates a symbolic link in `node_modules` and not a copy.

Causes chunks to be generated with `undefinedundefinedundefinedundefined` inserted into the bottom of the build output which obviously break the whole thing on runtime.

## Workarounds

1. Disable source map generation (i.e production mode)

2. (Best option) `npm pack` the module and list the tar in the `package.json` instead so that the module is copied and not linked.

3. Other fix (by far not recommended):

```javascript
// adding vendorSourceMap in @angular-devkit/build-angular/src/webpack/configs/common.js fixes it
if ((scriptsSourceMap || stylesSourceMap) && vendorSourceMap) {
// --- OR ---
// add the origin folder (in this case 'vendor') to exclude regex
exclude: vendorSourceMap
                ? /(ngfactory|ngstyle)\.js$/
                : [/[\\\/]node_modules[\\\/]/, /[\\\/]vendor[\\\/]/, /(ngfactory|ngstyle)\.js$/],
```

## 🔬 Minimal Reproduction

Apart from a zoom call, can't really reproduce as it's a purchased commercial module in use.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

Also, ideally we’d have a minimal reproduction that we can look at to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by smasala** [comment]
Thanks @alan-agius4 - yea I totally understand why it's needed. I'll try and get another umd module to behave in the same manner. 

One question to you in the meantime, how does the build know at this [point](d71ee21#diff-f3bcbd6f6b0756d2178dd69396750fa742093fb7f4668ab284463c0ca348b032R370) whether it's a `vendor` source map or not?

Option 3 above is exactly that, it's not recognising it as a vendor because the import to a node module is a symbolic link which origin lies outside of `node_modules`.

**Comment by smasala** [comment]
P.s @alan-agius4 setting the build option `"preserveSymlinks": true` does the job too. I assume because of: https://github.com/angular/angular-cli/blob/7d57dd2f3e7d36cc4ed2c356f79139486790cbfa/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L439-L446

**Comment by alan-agius4** [comment]
> how does the build know at this point whether it's a vendor source map or not?

Modules which are located in node_modules.

**Comment by smasala** [comment]
Ah ok, so as simple as that. I saw somewhere that there's also a regex to exclude "thrid_party" folder from complications but wasn't what I was looking for. 

Is there a way to extend the regex to add other folders other than "node_modules" as well?

**Comment by alan-agius4** [comment]
@smasala, you can use a 3rd party builder to do that, such as https://github.com/manfredsteyer/ngx-build-plus. 

However, it's important to point out that that while we do allow extending the Angular CLI and the Webpack configurations these are not supported by the Angular tooling team.

**Comment by smasala** [comment]
@alan-agius4 I tried replicating it with jquery and adding source maps. Seems to work fine. If you'd like to zoom I can show you. I assume that the commercial package we use fails because the source maps are massive (multiple MBs) and the new fast merge is now mandatory with the same cli build version too.

**Comment by alan-agius4** [comment]
I doubt this has anything to do with the size of the sourcemaps.  We can do a zoom/hangouts, although without an actual hands on project to debug it would be hard to address this problem. 

In the mean time can you please provide the full output of `ng version`?

**Comment by smasala** [comment]
@matsbryntse are you able to provide a copy of your gantt build 4.0.8 for @alan-agius4

**Comment by smasala** [comment]
@alan-agius4 

```
Angular CLI: 11.2.2
Node: 14.16.0
OS: darwin x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cli                    11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.6.3
typescript                      4.0.7
```

**Comment by amnporter** [comment]
We've been running into the same issues. We are trying to build a component library parallel to our main app. We are building our library with --prod and --watch to disable Ivy on that side of things. In the main app, I've tried with/without ivy compiling. We've had `"preserveSymlinks": true` set for a number of months. Running `npm link` has only started becoming a problem for us when we upgraded our main app to NG11 from NG6. Prior to that, `npm link` has been working seamlessly.

**Comment by alan-agius4** [comment]
@amnporter, it appears that you are reporting something different from the original here, as this issue is related to sourcemaps. Please file a new issue with a reproduction/full details.

That said, not that NGCC doesn’t support symlinks. Hence it you are linking a library make sure it’s not compiled with View Engine.

**Comment by alan-agius4** [comment]
Any updates about providing a copy of the problematic library?

**Comment by smasala** [comment]
@matsbryntse are you able to assist here please?

**Comment by matsbryntse** [comment]
@alan-agius4 You can email me directly and I'll provide access to our UMD build. mats at bryntum dot com

**Comment by jsakalos** [comment]
> P.s @alan-agius4 setting the build option `"preserveSymlinks": true` does the job too.

FYI: We at Bryntum had to set `preserveSymlinks:true` for all our demos; otherwise they wouldn't build. 

FYI 2: `preserveSymlinks:true` won't be needed for Bryntum components in the future as we are switching from locally linked packages to repository hosted packages (starting from version 4.1.x).

**Comment by alan-agius4** [comment]
Hi @smasala,

As suggested by @matsbryntse, I got my hands on `bryntum-gantt` by registering for a trial. That said, I am not able to replicate the issue you mentioned above. 

```
➜  taskeditor ng build
    'node-sass' usage is deprecated and will be removed in a future major version. To opt-out of the deprecated behaviour and start using 'sass' uninstall 'node-sass'.
✔ Browser application bundle generation complete.
✔ ES5 bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files | Names                |      Size
main-es5.js         | main                 |   9.05 MB
main-es2015.js      | main                 |   5.54 MB
vendor-es5.js       | vendor               |   2.50 MB
vendor-es2015.js    | vendor               |   2.06 MB
polyfills-es5.js    | polyfills-es5        | 632.07 kB
polyfills-es2015.js | polyfills            | 128.66 kB
runtime-es2015.js   | runtime              |   6.16 kB
runtime-es5.js      | runtime              |   6.16 kB
styles.css          | styles               | 151 bytes

                    | Initial ES5 Total    |  12.18 MB
                    | Initial ES2015 Total |   7.73 MB

Build at: 2021-03-17T10:59:26.563Z - Hash: c742c15d3350e0d4b594 - Time: 15123ms

Warning: /Users/alanagius/cli-reproductions/gunt-trial/examples/angular/taskeditor/src/app/ganttConfig.ts depends on 'bryntum-gantt/gantt.lite.umd.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

➜  taskeditor grep -r undefinedundefined dist/taskeditor/
➜  taskeditor 
➜  taskeditor ng v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.4
Node: 12.20.2
OS: darwin x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.1.5
    
```

**Comment by smasala** [comment]
@alan-agius4 did you serve the application and check the console?

**Comment by alan-agius4** [comment]
Yeah, no errors.

**Comment by smasala** [comment]
@alan-agius4 nor can I now and we replicated this on multiple machines originally 🙈

**Comment by smasala** [comment]
Got it. Something has changed in the background - maybe I had the new cli locally already. To replicate:

`npm ci` so that the exact versions are used:

```
"dependencies": {
    "@angular/animations": "11.2.3",
    "@angular/common": "11.2.3",
    "@angular/compiler": "11.2.3",
    "@angular/core": "11.2.3",
    "@angular/elements": "^11.1.2",
    "@angular/forms": "11.2.3",
    "@angular/platform-browser": "11.2.3",
    "@angular/platform-browser-dynamic": "11.2.3",
    "@angular/router": "11.2.3",
    "@ngrx/component-store": "11.0.0",
    "@nrwl/angular": "11.4.0",
    "@nrwl/nx-cloud": "^11.1.4",
    "rxjs": "~6.6.3",
    "tslib": "^2.0.0",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1102.2",
    "@angular-eslint/eslint-plugin": "~1.2.0",
    "@angular-eslint/eslint-plugin-template": "~1.2.0",
    "@angular-eslint/template-parser": "~1.2.0",
    "@angular/cli": "11.2.2",
    "@angular/compiler-cli": "11.2.3",
    "@angular/language-service": "11.2.3",
    "@jscutlery/semver": "^1.3.2",
    "@nrwl/cli": "11.4.0",
    "@nrwl/cypress": "11.4.0",
    "@nrwl/eslint-plugin-nx": "11.4.0",
    "@nrwl/jest": "11.4.0",
    "@nrwl/linter": "11.4.0",
    "@nrwl/storybook": "11.4.0",
    "@nrwl/tao": "11.4.0",
    "@nrwl/workspace": "11.4.0",
    "@percy/cypress": "^2.3.4",
    "@storybook/addon-knobs": "^6.1.11",
    "@storybook/angular": "^6.1.11",
    "@types/jest": "26.0.8",
    "@types/node": "^12.12.38",
    "@types/webpack": "4.41.21",
    "@typescript-eslint/eslint-plugin": "4.15.2",
    "@typescript-eslint/parser": "4.15.2",
    "bryntum-gantt": "file:vendor/bryntum-gantt/4.0.8/build",
    "cypress": "^6.0.1",
    "dotenv": "6.2.0",
    "eslint": "7.10.0",
    "eslint-config-prettier": "6.0.0",
    "eslint-plugin-cypress": "^2.10.3",
    "fs-extra": "^9.1.0",
    "jest": "26.2.2",
    "jest-preset-angular": "8.3.2",
    "prettier": "2.2.1",
    "ts-jest": "26.4.0",
    "ts-node": "^9.1.1",
    "typescript": "~4.0.3"
  }
```

Update: `vendor/bryntum-gantt/4.0.8/build/package.json` with `"types": "gantt.d.ts"`

Use import as: `import { Gantt, ProjectModel, Panel } from 'bryntum-gantt';`

**Comment by smasala** [comment]
@alan-agius4 also happens with `import { Gantt, ProjectModel, Panel } from 'bryntum-gantt/gantt.umd.js';` and `"@angular-devkit/build-angular": "0.1102.4",` and without `"types": "gantt.d.ts"`

**Comment by alan-agius4** [comment]
@smasala, can you create a reproduction using `ng new` please? 
You can omit the source of `bryntum-gantt` from the GitHub repo since I have a local copy. Thanks.

**Comment by smasala** [comment]
@alan-agius4 https://github.com/smasala/ng-gantt-cli-source-map-bug -> `npm i` and `ng serve`

**Comment by alan-agius4** [comment]
Hi @smasala, 

I am still unable to replicate.

![Screenshot 2021-03-18 at 08 28 02](https://user-images.githubusercontent.com/17563226/111588572-07416c80-87c4-11eb-9af9-259684f470f4.png)

**Comment by smasala** [comment]
@alan-agius4 did you try with `npm ci`?

**Comment by alan-agius4** [comment]
In this case `npm ci` isn't any different from `npm i`.

**Comment by smasala** [comment]
@alan-agius4 how strange. I can replicate it with exactly that package and I'm not the only developer with the issue. 

Oh well, thanks very much for your help.
