### ISSUE TITLE
Comments in tsconfig.json

### ISSUE THREAD

**Issue by kmursk** [angular/angular-cli#20183]
# 🚀 Feature request

### Command (mark with an `x`)
- [X ] new

### Description
Very appreciate your care about informing consumers how to use product, but placing comments in json-files (**tsconfig.json**, **tsconfig.lib.json** and etc) prevents editing them with json-parsers.

### Describe the solution you'd like
Suggest to move hint _/* To learn more about this file see: https://angular.io/config/tsconfig. */_ from the beginning of the file into json body. For example, change 
```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
...

```
to

```
{ 
  "greeting": "To learn more about this file see: https://angular.io/config/tsconfig",
  "compileOnSave": false,
  "compilerOptions": {
...
```

**Comment by alan-agius4** [comment]
Hi,

Thanks for this request, but TypeScript, among other tools use a superset of JSON which does allow comments and trailing commas among other things. Some supersets of JSON that do allow comments are JSON5 and JSONC.

**More information**
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-8.html#allow-comments-in-tsconfigjson
- https://spec.json5.org/#comments
- https://code.visualstudio.com/docs/languages/json#_json-with-comments

If your tool is not able to handle these type of JSON supersets, feel free to remove these comments and trailing commas (if any)  manually or use a json-parser that support these types of supersets such as https://www.npmjs.com/package/jsonc-parser
