### ISSUE TITLE
Handle custom script with --subresource-integrity option

### ISSUE THREAD

**Issue by ferdiesletering** [angular/angular-cli#20189]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When using a custom script tag, the integrity property is not added.

## 🔬 Minimal Reproduction

index.html

```
<head>
 <script src="custom.js"></script>
</head>
```

angular.json

```
 "scripts": [
  {
    "inject": false,
    "input": "projects/register/src/custom-script.js",
    "bundleName": "custom"
}
```

run `ng build --prod --subresource-integrity`

## 🔥 Exception or Error

```
<head>
 <script src="custom.js"></script>
 <link rel="stylesheet" href="styles.9bce2029799551780e24.css" crossorigin="anonymous" integrity="sha384-iTQfOyaDDakiIWyo0m57roHiA4Mo2KLPSZf0jb+jR+YdOrQv9ZAUTLSVdtoxkCzM">
</head>	
```

The custom.js script tag does not contain an integrity tag.	

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.1.1
Node: 10.15.3
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@angular/cdk                    11.1.1
@angular/cli                    11.1.1
@angular/material               11.1.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
ng-packagr                      11.1.2
rxjs                            6.6.3
typescript                      4.1.3

</code></pre>

**Comment by alan-agius4** [comment]
Hi @ferdiesletering,

Thanks for reaching out, however this is working expected. since you are using `"inject": false`. When using this option the developer has full control on how the script is injected or loaded.

If you want to SRI attribute to be added, remove the script from the `index.html` and let the build system inject the script which will include the SRI attribute.

```json
"scripts": [{
    "input": "projects/register/src/custom-script.js",
    "bundleName": "custom"
}]
```

**Comment by ferdiesletering** [comment]
@alan-agius4 thank your for helping out.

The `"inject:false"` will push the script to the bottom of the page. I want to preserve the script inside the `<head>`.
