### ISSUE TITLE
ng new app failing with 'npm ERR! cb() never called!' error

### ISSUE THREAD

**Issue by sandeepdussa** [angular/angular-cli#20191]
# 🐞 Bug report

### Command
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e

### Description

ng new my-first-project is failing with below error:

npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AppData\Roaming\npm-cache\_logs\2021-03-03T19_24_37_504Z-debug.log

## 🔬 Minimal Reproduction
Try creating a new project using latest angular cli on Node 14.16.0 and NPM 6.14.11

## 🔥 Exception or Error
<pre><code>
npm ERR! cb() never called!
npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.2
Node: 14.16.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.2 (cli-only)
@angular-devkit/core         11.2.2 (cli-only)
@angular-devkit/schematics   11.2.2 (cli-only)
@schematics/angular          11.2.2 (cli-only)
@schematics/update           0.1102.2 (cli-only)

</code></pre>

**Comment by alan-agius4** [comment]
As indicated by the error message this seems like a problem with NPM and not with Angular CLI.

Please have a look at https://npm.community/t/npm-err-cb-never-called/486

I suggest to downgrade/upgrade NPM or use an alternative package manage.

**Comment by sandeepdussa** [comment]
Ok upgrading NPM to 7.6.0 fixed this issue for me. But I hope NPM team permanently fixes this issue for everyone.
