### ISSUE TITLE
Unhandled exception with "ng build", no error with "ng serve"

### ISSUE THREAD

**Issue by ensnared** [angular/angular-cli#20198]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

This is the first time I encounter this issue.

### Description

When running ng build, the process fails with an error:
An unhandled exception occurred: /my/project/dir/main-es2015.d5a4846a555b79c79b3e.js: Cannot read property 'split' of undefined

Running "ng serve" does not result in any errors whatsoever.

## 🔬 Minimal Reproduction
ng build --prod

I have no idea which parts of my project might be the root cause for the error since "ng serve" works as normal.

## 🔥 Exception or Error
This is the error:
<pre><code>✔ Browser application bundle generation complete.
⠹ Generating ES5 bundles for differential loading...An unhandled exception occurred: /my/project/dir/main-es2015.d5a4846a555b79c79b3e.js: Cannot read property 'split' of undefined
See "/tmp/ng-hy43Cv/angular-errors.log" for further details.
 </code></pre>
This is the contents of the logfile from the error.
<pre><code>
</code>[error] TypeError: /my/project/dir/main-es2015.d5a4846a555b79c79b3e.js: Cannot read property 'split' of undefined
    at NodePath.get (/my/project/dir/node_modules/@babel/traverse/lib/path/family.js:185:21)
    at BlockScoping.wrapClosure (/my/project/dir/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:534:29)
    at BlockScoping.run (/my/project/dir/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:360:12)
    at PluginPass.BlockStatement|SwitchStatement|Program (/my/project/dir/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:89:24)
    at newFn (/my/project/dir/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/my/project/dir/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/my/project/dir/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/my/project/dir/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/my/project/dir/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/my/project/dir/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/my/project/dir/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/my/project/dir/node_modules/@babel/traverse/lib/index.js:82:17)
    at NodePath.visit (/my/project/dir/node_modules/@babel/traverse/lib/path/context.js:99:18)
    at TraversalContext.visitQueue (/my/project/dir/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/my/project/dir/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/my/project/dir/node_modules/@babel/traverse/lib/context.js:144:19)
</pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.2.3
Node: 15.11.0
OS: linux x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.3
@angular-devkit/build-angular      0.1102.3
@angular-devkit/core               11.2.3
@angular-devkit/schematics         11.2.3
@angular/cdk                       11.2.3
@angular/cli                       11.2.3
@angular/google-maps               11.2.3
@angular/material                  11.2.3
@angular/material-moment-adapter   11.2.3
@schematics/angular                11.2.3
@schematics/update                 0.1102.3
rxjs                               6.6.6
typescript                         4.1.5

</code></pre>

**Anything else relevant?**
I've tried building on different computers, and I've deleted node_modules and reinstalled everything, but the error persists.

This is my project dependencies, but I have not added any new ones that weren't there the last time I successfully built. These are my current versions, but I've tried to downgrade to the versions I had on the last successful build (only minor version differences, no major versions), but that did not help either.
<pre><code>"dependencies": {
    "@angular-material-components/datetime-picker": "^5.1.0",
    "@angular-material-components/moment-adapter": "^5.0.0",
    "@angular/animations": "~11.2.4",
    "@angular/cdk": "^11.2.3",
    "@angular/common": "~11.2.4",
    "@angular/compiler": "~11.2.4",
    "@angular/core": "~11.2.4",
    "@angular/forms": "~11.2.4",
    "@angular/google-maps": "^11.2.3",
    "@angular/localize": "^11.2.4",
    "@angular/material": "^11.2.3",
    "@angular/material-moment-adapter": "^11.2.3",
    "@angular/platform-browser": "~11.2.4",
    "@angular/platform-browser-dynamic": "~11.2.4",
    "@angular/router": "~11.2.4",
    "@fortawesome/angular-fontawesome": "^0.8.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.34",
    "@fortawesome/free-brands-svg-icons": "^5.15.2",
    "@fortawesome/free-regular-svg-icons": "^5.15.2",
    "@fortawesome/free-solid-svg-icons": "^5.15.2",
    "@ngrx/data": "^11.0.1",
    "@ngrx/effects": "^11.0.1",
    "@ngrx/entity": "^11.0.1",
    "@ngrx/router-store": "^11.0.1",
    "@ngrx/store": "^11.0.1",
    "bootstrap": "^4.6.0",
    "exceljs": "^4.2.0",
    "file-icon-vectors": "^1.0.0",
    "file-saver": "^2.0.5",
    "jspdf": "^2.3.0",
    "jspdf-autotable": "^3.5.14",
    "lodash-es": "^4.17.21",
    "luxon": "^1.26.0",
    "moment": "^2.29.1",
    "ngx-material-timepicker": "^5.5.3",
    "primeicons": "^4.1.0",
    "primeng": "^10.0.3",
    "rxjs": "~6.6.6",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.3",
    "@angular-eslint/builder": "1.2.0",
    "@angular-eslint/eslint-plugin": "1.2.0",
    "@angular-eslint/eslint-plugin-template": "1.2.0",
    "@angular-eslint/schematics": "^1.2.0",
    "@angular-eslint/template-parser": "1.2.0",
    "@angular/cli": "~11.2.3",
    "@angular/compiler-cli": "~11.2.4",
    "@angular/language-service": "~11.2.4",
    "@ngrx/store-devtools": "^11.0.1",
    "@types/file-saver": "^2.0.1",
    "@types/googlemaps": "3.43.3",
    "@types/jasmine": "^3.6.4",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "^14.14.31",
    "@typescript-eslint/eslint-plugin": "4.16.1",
    "@typescript-eslint/parser": "4.16.1",
    "codelyzer": "^6.0.1",
    "eslint": "^7.21.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "32.2.0",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.1.5"
  }</code></pre>

**Comment by developerhb** [comment]
It seems like the object on which you are using `split` method is not defined. This might help ->https://stackoverflow.com/questions/39102998/typeerror-cannot-read-property-split-of-undefined-in-nodejs/39103127 . Read the comments.

**Comment by alan-agius4** [comment]
Hi @ensnared, 

Differential loading is only done during `ng build` and hence why the error doesn't manifest durning `ng serve`.

Based on the stacktrace, it appears that is causing by `Babel` when a `switch` statement is being downlevelled. You can try to debug the `wrapClosure` method in `@babel/plugin-transform-block-scoping` which should give you more details on where the problem is. 

When which syntax is causing the problem, Kindly create a minimal reproduction and open an issue in https://github.com/babel/babel

Thanks.

**Comment by ensnared** [comment]
@developerhb No, _I_ am not using ```split``` on an undefined object. The file that throws the error is in the babel module, not my code.

@alan-agius4 Thank you, I have no idea how you can see that it is caused by a switch-statement (although now that you've pointed it out I can guess I can see it too...) But that really helps a lot, I don't use many switch-statements, so if that's the case it should be relatively trivial to hunt it down.

**Comment by alan-agius4** [comment]
@ensnared, note that the switch statement can also be in a library. That said, it the node_modules have not been changed this should be caused by a change in your code. 

I tracked it down that it is caused by a `switch` from the stacktrace, to be more precise 
```
at BlockScoping.wrapClosure (/my/project/dir/node_modules/@babel/plugin-transform-block-scoping/lib/index.js:534:29)
```

That part is only invoked when the `block` is a `switch` statement https://unpkg.com/browse/@babel/plugin-transform-block-scoping@7.12.13/lib/index.js#L534, adding a debugger here, would give you valuable information on which code block is the problem.

**Comment by ensnared** [comment]
@alan-agius4, I found the statement using the not-so-sophisticated method of commenting out my switch-statements one by one and retrying the build after each one (I only have about a dozen in total, and only a couple of them were new since the last successful build). I did try looking at it with a debugger afterwards to see how it works as I've not really used a debugger that much before, but I guess it's a good idea to start learning ;) I found the name of the method containing the switch statement there, so if I ever get a similar error again later I at least now know how to start investigating it.

Thank you very much again, you've been very helpful :)
