### ISSUE TITLE
Webpack & sortablejs

### ISSUE THREAD

**Issue by Namek** [angular/angular-cli#2019]
# Version:
**1.0.0-beta.11-webpack.8**

# Issue

(somewhat copying the https://github.com/RubaXa/Sortable/issues/951)

I can't import [sortablejs](https://github.com/RubaXa/Sortable/) - with typings or without.

# Issue details

This:
```
typings install dt~sortablejs --global --save # or alternatively: npm install --save @types/sortablejs
npm i --save sortablejs
```
with this: `import Sortable from 'sortablejs'` 
results in:
`Module ''sortablejs'' resolves to a non-module entity and cannot be imported using this construct.`

and this import: `import * as Sortable from 'sortablejs'`
results in: `Module ''sortablejs'' has no default export.`

Previously this worked for me (before webpack) but now it doesn't:
`import Sortable = require('sortablejs')` 
because:
```
Import assignment cannot be used when targeting ECMAScript 2015 modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
```

Adding
```
 "scripts": [
    "../node_modules/sortablejs/Sortable.js"
  ],
```
into `angular-cli.json` also didn't help - neither with `typings` or `@types`.

# Side note

I'd like to note I made a fresh project using `ng new` with webpack CLI to `tsconfig.json` or other configs are rather default.

**Comment by a5hik** [comment]
I too facing the same error.

> angular-cli: 1.0.0-beta.11-webpack.8
node: 6.2.1
os: darwin x64

`resolves to a non-module entity and cannot be imported using this construct.`

**Comment by Namek** [comment]
What I did was to NOT use `import` instruction, specify the dist file directly from `node_modules` in `angular-cli.json -> scripts` and used typings. It compiled but I didn't yet confirm that it works since I was upgrading rc4->rc6 while going to webpack CLI and had lots of dependencies to care about.

**Comment by a5hik** [comment]
To workaround I did added the below in `typings.d.ts`

`declare module 'sortablejs' {
  let exportAs: any;
  export = exportAs;
}`

and imported as `import * as Sortable from 'sortablejs';`

It works but, wanted to avoid the entry in `typings.d.ts` as the angular-cli doc claims to work without that.

PS: You don't need an entry in `angular-cli.json` as the `scripts` entry there is meant for global entries.

**Comment by Namek** [comment]
wow, nice one, thanks. I'll try it out when I'll be near the project.

**Comment by filipesilva** [comment]
I know this is a frustrating answer, but this seems like a problem user `SortableJS` with TypeScript instead of a CLI problem. I'm leaving it open and flagging it for community help but might be a while before I come around and try to help, since there are other more pressing issues directly related to CLI bugs.

**Comment by Namek** [comment]
As I said before, this worked for me:
I did NOT use `import` instruction, instaed have specified the dist file directly from `node_modules` in `angular-cli.json` -> `scripts` and used typings.

Note: This way the library is somewhat global due to `Sortable` variable.
