### ISSUE TITLE
v12.0.0-next.3 ng update failed

### ISSUE THREAD

**Issue by gurezo** [angular/angular-cli#20208]
# 🐞 Bug report

when ng update excuted, but update is failed

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
v12.0.0-next.2 did'nt happend

### Description
```
➜  portfolio git:(feature/next) ng update @angular/cli@12.0.0-next.3 --force
Using package manager: 'npm'
Collecting installed dependencies...
Found 51 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/architect @ "0.1200.0-next.3" (was "0.1200.0-next.2")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1200.0-next.3" (was "0.1200.0-next.2")...
    Updating package.json with dependency @angular/cli @ "12.0.0-next.3" (was "12.0.0-next.2")...
  UPDATE package.json (2559 bytes)
⠏ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1200.0-next.2
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@12.0.0-next.3
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^12.0.0-next" from @angular-devkit/build-angular@0.1200.0-next.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/akihiko.kigure/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akihiko.kigure/.npm/_logs/2021-03-06T06_16_57_067Z-debug.log
✖ Package install failed, see above.
✖ Migration failed. See above for further details.

➜  portfolio git:(feature/next) ✗ rm -rf node_modules
➜  portfolio git:(feature/next) ✗ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1200.0-next.2
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@12.0.0-next.3
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^12.0.0-next" from @angular-devkit/build-angular@0.1200.0-next.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/akihiko.kigure/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akihiko.kigure/.npm/_logs/2021-03-06T06_18_36_505Z-debug.log
➜  portfolio git:(feature/next) ✗
```

## 🔬 Minimal Reproduction
```
$ ng update @angular/cli@12.0.0-next.3 --force
$ rm -rf node_modules
$ npm i
```

## 🔥 Exception or Error
when excuting ng update @angular/cli@12.0.0-next.3 --force
<pre><code>
when excuting ng update @angular/cli@12.0.0-next.3 --force
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1200.0-next.2
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@12.0.0-next.3
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^12.0.0-next" from @angular-devkit/build-angular@0.1200.0-next.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/akihiko.kigure/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akihiko.kigure/.npm/_logs/2021-03-06T06_16_57_067Z-debug.log
✖ Package install failed, see above.
✖ Migration failed. See above for further details.

------

when remove node_modules, npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1200.0-next.2
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@12.0.0-next.3
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^12.0.0-next" from @angular-devkit/build-angular@0.1200.0-next.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1200.0-next.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/akihiko.kigure/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akihiko.kigure/.npm/_logs/2021-03-06T06_18_36_505Z-debug.log
</code></pre>

## 🌍 Your Environment
<pre><code>
macOS Catalina 10.15.7
➜  ~ npm -v
7.6.1
➜  ~ node -v
v12.20.2
➜  ~ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0-next.3
Node: 12.20.2
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0-next.3 (cli-only)
@angular-devkit/core         12.0.0-next.3 (cli-only)
@angular-devkit/schematics   12.0.0-next.3 (cli-only)
@schematics/angular          12.0.0-next.3 (cli-only)
@schematics/update           0.1200.0-next.3 (cli-only)

➜  ~

</code></pre>

**Anything else relevant?**
may be nothing

**Comment by gurezo** [comment]
add information
same error v11.2.2 => v11.2.3
```
➜  app git:(main) ng update @angular/cli@11.2.3 --force
Using package manager: 'npm'
Collecting installed dependencies...
Found 32 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/architect @ "0.1102.3" (was "0.1102.2")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.1102.3" (was "0.1102.2")...
    Updating package.json with dependency @angular/cli @ "11.2.3" (was "11.2.2")...
  UPDATE package.json (1370 bytes)
⠙ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1102.2
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1102.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1102.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@11.2.4
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1102.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/akihiko.kigure/.npm/eresolve-report.txt for a full report.
➜  app git:(main) ✗ rm -rf node_modules
➜  app git:(main) ✗ npm cache verify
Cache verified and compressed (~/.npm/_cacache)
Content verified: 3559 (363438747 bytes)
Content garbage-collected: 88 (103220010 bytes)
Index entries: 3982
Finished in 6.856s
➜  app git:(main) ✗ npm cache clean --force
npm WARN using --force Recommended protections disabled.
➜  app git:(main) ✗ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1102.2
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1102.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1102.3" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@11.2.4
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.3
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1102.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/akihiko.kigure/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akihiko.kigure/.npm/_logs/2021-03-06T06_44_49_352Z-debug.log
```

**Comment by clydin** [comment]
This appears to be a defect with npm 7's dependency resolution.  The SemVer range of `@angular/localize@"^11.0.0 || ^11.2.0-next"` is satisfied by `@angular/localize@11.2.4`.  There should be no version conflict.

**Comment by gurezo** [comment]
@clydin 
Thank you for your advice
I solved it by lowering the version of npm.

follwing resolved npm, node versions
```
➜  ~ node -v
v12.21.0
➜  ~ npm -v
6.14.11
```
