### ISSUE TITLE
Slow incremental build performance v 11.1.0

### ISSUE THREAD

**Issue by thekip** [angular/angular-cli#20202]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, previously it was 3-4s now it 18-25s 

### Description

Just usual change cause a rebuild wich takes up to 25s
The same behaviour when you change scss file or ts. 

## 🔬 Minimal Reproduction
The project in Private repo, but i can share it with some of angular team members if needed. 
I created a [CPU profile](https://github.com/angular/angular-cli/files/6089880/incremental.build.ng.11.cpuprofile.zip) using instructions from here https://github.com/angular/angular-cli/issues/8259

From the profile, I see that typescript do a lot of work after every change, despite that only one line was changed. 

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.1
Node: 14.15.4
OS: darwin x64

Angular: 11.2.1
... cdk, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.1
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.2.1
@angular-devkit/schematics      11.2.0
@schematics/angular             11.2.1
@schematics/update              0.1102.1
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Comment by petebacondarwin** [comment]
This is being tracked here: https://github.com/angular/angular/issues/40728
