### ISSUE TITLE
inlineCritical optimization can cause duplicate font downloads

### ISSUE THREAD

**Issue by mattdistefano** [angular/angular-cli#20206]
# inlineCritical optimization can cause duplicate font downloads

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not exactly - see below.

### Description

With latest version of the CLI and the inlineCritical flag true, it looks like the critters config is set to inline font-faces but *not* prune the inlined code out of the external CSS file. See https://github.com/angular/angular-cli/blob/11b1d9c2d1fb75df968fa31b5fcdeeb072f87b52/packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts#L37

This produces duplicate `@font-face` rules - one in the inlined CSS, one still in the external CSS - which in turn - in Chrome, anyway - seems to cause the referenced font files to be downloaded twice. 

Would be nice to make the pruning configurable through the CLI. I'm guessing it's disabled by default in case users are pre-rendering multiple routes, but I'd assume it'd be safe to enable if you're just using a single app-shell route?

## 🔬 Minimal Reproduction

I'll try to put together a repo with a repro, but in the meantime, the repro should be just enabling inlineCritical while having a `@font-face` at-rule that gets inlined.

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.3
Node: 12.16.1
OS: darwin x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.0
@angular-devkit/schematics      11.2.0
@angular/cli                    11.2.3
@schematics/angular             11.2.0
@schematics/update              0.1102.3
ng-packagr                      11.2.4
rxjs                            6.6.6
typescript                      4.0.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi @mattdistefano,

I am unable to replicate this in Google Chrome, I only see a single request.

![Screenshot 2021-03-05 at 20 21 57](https://user-images.githubusercontent.com/17563226/110163614-8d3adc00-7df0-11eb-8004-c91bbd3d34bd.png)

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

Enabling pruning is something that we'd like to explore in the future but there are definitely a couple of issues that this will cause some problems such as SRI and sourcemaps, that said it's unlikely that we make this configurable.

**Comment by mattdistefano** [comment]
Yeah I should clarify, you'll only see it when using an app shell and serving off a real HTTP server. 

https://github.com/mattdistefano/angular-cli-20206-repro has the repro.

**Comment by alan-agius4** [comment]
Hi @mattdistefano, thanks for the reproduction. I’ll take a look at it in the coming days.

From the screenshot in the reproduction, I did notice that there are 2 requests for the `.css` file, which might very well be the reason of the duplicate requests.

**Comment by mattdistefano** [comment]
Oh! You are correct about that. 

The issue actually seems to be that Chrome is downloading the initial `media="print"` *and* downloading again when the onload handler flips the media type. I will double-check I'm on latest Chrome and see if it still repros there.

**Comment by alan-agius4** [comment]
Glad to hear it was an easy fix 😀
