### ISSUE TITLE
ng lint with --format=json generates invalid JSON after migrating tslint to eslint

### ISSUE THREAD

**Issue by rfonascimento** [angular/angular-cli#20217]
Hi, after migrating tslint to eslint the lint report given by the command`ng lint --format=json > report.json` generates invalid JSON file.

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Following the upgrade of Angular to the current latest `11.2.4`, the migration from tslint to eslint was also required.
Previously with tslint, the command `ng lint --force=true --format=json > report.json` was used to generate a JSON report.
Now, with eslint, the same command (or even with `--silent=true` to hide a string) is generating an invalid JSON as showed below:

```
[
   filePath: '..',
   ...
]
[
   filePath: '..',
   ...
]
```

## 🔬 Minimal Reproduction

1. `ng new eslint-report` - create a new angular project
2. Add invalid code in different files so it can be capture by eslint
3. ng lint --force=true --silent=true --format=json > report.json
4. Open report.json to see invalid JSON

## 🔥 Exception or Error
**report.json**
<pre><code>
[
  {
    "filePath": "***/app.component.ts",
    "messages": [
      {
        "ruleId": "@typescript-eslint/naming-convention",
        "severity": 1,
        "message": "Method name `Fun` must have a leading underscore.",
        "line": 11,
        "column": 11,
        "nodeType": "Identifier",
        "messageId": "missingUnderscore",
        "endLine": 11,
        "endColumn": 14
      },
      {
        "ruleId": "@typescript-eslint/naming-convention",
        "severity": 1,
        "message": "Enum name `example` must match one of the following formats: PascalCase",
        "line": 17,
        "column": 13,
        "nodeType": "Identifier",
        "messageId": "doesNotMatchFormat",
        "endLine": 17,
        "endColumn": 20
      },
      {
        "ruleId": "@typescript-eslint/naming-convention",
        "severity": 1,
        "message": "Enum Member name `something` must match one of the following formats: PascalCase",
        "line": 18,
        "column": 3,
        "nodeType": "Identifier",
        "messageId": "doesNotMatchFormat",
        "endLine": 18,
        "endColumn": 12
      }
    ],
    "errorCount": 0,
    "warningCount": 3,
    "fixableErrorCount": 0,
    "fixableWarningCount": 0,
    "source": "import {Component} from '@angular/core';\n\n@Component({\n  selector: 'app-root',\n  templateUrl: './app.component.html',\n  styleUrls: ['./app.component.scss']\n})\nexport class AppComponent {\n  title = 'eslint-report';\n\n  private Fun() {\n    let title = '';\n    const title = '';\n  }\n}\n\nexport enum example {\n  something\n}\n",
    "usedDeprecatedRules": []
  }
]
[
  {
    "filePath": "***/foo/foo.component.ts",
    "messages": [
      {
        "ruleId": "@typescript-eslint/naming-convention",
        "severity": 1,
        "message": "Method name `Fun2` must match one of the following formats: camelCase",
        "line": 20,
        "column": 10,
        "nodeType": "Identifier",
        "messageId": "doesNotMatchFormat",
        "endLine": 20,
        "endColumn": 14
      }
    ],
    "errorCount": 0,
    "warningCount": 1,
    "fixableErrorCount": 0,
    "fixableWarningCount": 0,
    "source": "import {Component, OnInit} from '@angular/core';\n\n@Component({\n  selector: 'app-foo',\n  templateUrl: './foo.component.html',\n  styleUrls: ['./foo.component.scss']\n})\nexport class FooComponent implements OnInit {\n\n  public foo = 'foo';\n\n  constructor() {\n  }\n\n  ngOnInit(): void {\n    let foo = 'foo';\n    const foo = '';\n  }\n\n  public Fun2() {\n  }\n\n}\n",
    "usedDeprecatedRules": []
  }
]

</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.3
Node: 13.12.0
OS: darwin x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Comment by danizep** [comment]
Would be nice if the Angular Cli could provide a `--output-file` flag to specify the output file and avoid the workaround `ng lint --format=json > report.json`.

**Comment by alan-agius4** [comment]
ESLint builder is not part of the first party Angular CLI builders which are provided and supported Angular tooling team.

Please file an issue an issue in the [angular-eslint]( https://github.com/angular-eslint/angular-eslint) issue tracker.
