### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by masaanli** [angular/angular-cli#2023]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 Anniversary

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
6.5.0

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Is it possible to include middleware as example that is possible using BrowserSync?
So we can include a stubbed WebApi as middleware? (for example Swagger)?
So the calls are not made to a real Back-End but just a stubbed server.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.
-
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
There currently is no way to do this, but that will change with the upcoming addon functionality.
