### ISSUE TITLE
Cant' find name 'Promise'

### ISSUE THREAD

**Issue by AnasSharif** [angular/angular-cli#2024]
> Please provide us with the following information:
> ---------------------------------------------------------------
npm v3 
node 6 
and angular cli webpack 8
when i make the promise the IDE says can't find name 'Promise
IDE VSC
![capture7](https://cloud.githubusercontent.com/assets/20491569/18361217/de11c37a-75b5-11e6-8db5-dbbde20482ca.PNG)
'

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by osmanm786** [comment]
in your settings.json point to ts here is mine:

{

   "typescript.tsdk":   "./node_modules/typescript/lib"
}

**Comment by filipesilva** [comment]
You need to update the TS your editor is using, such as @osmanm786 suggested.
