### ISSUE TITLE
rebuild time depends on assets 

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#20244]
Versions:
 ```
"@angular/animations": "^11.0.4",
    "@angular/cdk": "^11.0.2",
    "@angular/common": "^11.0.4",
    "@angular/compiler": "^11.0.4",
    "@angular/core": "^11.0.4",
    "@angular/forms": "^11.0.4",
    "@angular/localize": "^11.0.4",
    "@angular/platform-browser": "^11.0.4",
    "@angular/platform-browser-dynamic": "^11.0.4",
    "@angular/router": "^11.0.4"
   "@angular-devkit/build-angular": "^0.1100.4",
    "@angular-eslint/eslint-plugin": "0.8.0-beta.5",
    "@angular-eslint/eslint-plugin-template": "0.8.0-beta.5",
    "@angular-eslint/template-parser": "0.8.0-beta.5",
    "@angular/cli": "^11.0.4",
    "@angular/compiler-cli": "^11.0.4",
    "@angular/language-service": "^11.0.4",

```
Rebuild time is somehow affected by assets in angular.json - here are table with times with and without assets:
```
   "assets": [
              "apps/edhance/src/favicon.ico",
              "apps/edhance/src/assets",
              "apps/edhance/src/config.json",
              {
                "glob": "**/*",
                "input": "apps/edhance/configs",
                "output": "./configs/"
              }
            ],
```

![image](https://user-images.githubusercontent.com/10418323/110776087-f478e600-825f-11eb-86a6-2ce4d0142e1d.png)

Difference in first build is comprehensible (to copy static - immutable assets to serve folder), however, why is so big difference in rebuild time when i change typescript file? 

![image](https://user-images.githubusercontent.com/10418323/110776841-c7790300-8260-11eb-86ff-4ba3d91e3b52.png)

(another project) 
![image](https://user-images.githubusercontent.com/10418323/110780265-cd70e300-8264-11eb-8521-b73cd6ec714c.png)

**Comment by alan-agius4** [comment]
This is unfortunately is how https://webpack.js.org/plugins/copy-webpack-plugin works with Webpack 4. With every re-build the assets patterns are re-processed and copied over and over again. 

With Webpack 5 & cached enabled this should get better eventually as this plugin use caching to reduce IO calls https://github.com/webpack-contrib/copy-webpack-plugin/blob/01fa91b09d3b4fdc4552b520bb90918fc7f34e54/src/index.js#L604

**Comment by montella1507** [comment]
:-( So it may be possible to  try performance boost with:

```
"resolutions": {
    "webpack": "^5.0.0"
}
```

right?

**Comment by alan-agius4** [comment]
yes
