### ISSUE TITLE
Security Vulnerability still not fixed after 3 months for Angular v8 (ini 1.3.5)

### ISSUE THREAD

**Issue by hareharey** [angular/angular-cli#20254]
Hi, there is a vulnerability with the "ini" js library for version 1.3.5.  See https://snyk.io/vuln/SNYK-JS-INI-1048974

The angular cli imports this dependency through its dependency on `@schematics/update`. 

This issue has been raised before in #19634 and #19594 but it seems the fix was never applied for the Angular 8 cli. I have imported the latest version of the CLI as of this writing (`v8.3.29`) and I can still see in my yarn.lock file that there is a dependency on `ini v1.3.5`.

This is causing our vulnerability scans to fail for our application which is preventing us from deploying our Angular application. Please remedy this vulnerability so that it is no longer an issue.

(Vulnerability was published on 2020-12-10)

**Comment by alan-agius4** [comment]
Hi @hareharey,

Angular 8 Is not longer support and its LTS ended on Nov 28, 2020 and hence the fix was not back ported.

Kindly see https://angular.io/guide/releases#lts-fixes for more information about supported Angular versions.

**Comment by hareharey** [comment]
Ah ok I didn't realize that; thanks for clarifying. I fixed it for the time being using the `resolutions` feature of yarn for package.json:

```
"resolutions": {
  "ini" : "1.3.6",
}
```
