### ISSUE TITLE
Deleting node_modules then npm install causes ng build to use webpack@2.1.0-beta.21 instead of beta.22

### ISSUE THREAD

**Issue by RedFour** [angular/angular-cli#2025]
Deleting the node_modules folder and then running npm install causes ng build to use webpack@2.1.0-beta.21. Which then causes issues that were resolved when the version was updated to 22.

**Comment by richavyas** [comment]
Did you find any solution? I am also struggling with the same issue.

**Comment by RedFour** [comment]
No, I'm just making sure I don't need to delete node_modules at the moment. I'm assuming something will get updated eventually so that npm install will use the newer webpack version.

**Comment by filipesilva** [comment]
This should be fixed in `beta.14`
