### ISSUE TITLE
Again ng deploy: is not working with a specified configuration  ng deploy --configuration <conf-name>

### ISSUE THREAD

**Issue by MahdiMaarouf2016** [angular/angular-cli#20265]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] deploy 

### Is this a regression?

This issue was supposedly fixed in #17613 

### Description

I have set my app deployment configuration in 2 names "local" and "Heroku".then I add all configurations to my package.json as following : 
angular.json : 
<pre><code>
"deploy": {
 ...
          "configurations": {
            "heroku": {
              "outputPath": "dist/phonizyadmin-heroku",
              "optimization": {
                "scripts": true,
                "styles": true
              },
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.dev.ts",
                  "with": "src/environments/environment.heroku.ts"
                }
              ]
            },
            "local": {
              "outputPath": "dist/phonizyadmin-local",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.dev.ts",
                  "with": "src/environments/environment.local.ts"
                }
              ]
            }
          }
        }

</code></pre>
package.json scripts: 
<pre><code>
"deploy:heroku": "ng deploy --configuration heroku",
"deploy:local": "ng deploy --configuration local",
</code></pre>

## 🔬 Minimal Reproduction

>ng deploy --configuration <conf-name>

## 🔥 Exception or Error
when i run my every one of them i see this problem:

<pre><code>
> ng deploy --configuration heroku
Unknown option: '--configuration'
Unknown option: 'heroku'
</code></pre>

## 🌍 Your Environment
<pre><code>
@angular/cli                      8.3.29
</code></pre>

**Anything else relevant?**
VS code, the R.I.P Windows 7.

**Comment by alan-agius4** [comment]
Hi @MahdiMaarouf2016,

The above issue has been fixed in 9.1.x, please update to this version or later.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
