### ISSUE TITLE
Warning: app.component.scss exceeded maximum budget - DOES NOT give any clue why its exceeded

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular-cli#20269]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Ng build in my application produce following warning
Warning: frontend/apps/vo/src/app/app.component.scss exceeded maximum budget. Budget 6.00 kB was not met by 274 bytes with a total of 6.27 kB.

But visually this scss file is pretty small and actually I do not see any generated css exceeding this budget. 

### Describe the solution you'd like
Add possibility to view generated css

**Comment by alan-agius4** [comment]
@Lonli-Lokli,

Thanks for this feature request.

Similar to other budgets we don't show the contents of the file when a budget is not met as the content can be rather large and at this stage the CSS is minified thus whitespaces and formatting are completely removed and hence dumping a bunch of compressed CSS in the terminal might not be very helpful, it would also cause a lot of chum when multiple budgets are not met.

If you are uncertain what failed the failure, the best course of action is to analyze the generated bundle itself. Similar to how you'd do if another type of budget is not met.

**Comment by Lonli-Lokli** [comment]
@alan-agius4 may I kindly ask you to explain how it can be analyzed? webpack-bundle-analyzer do not give content of css, while all other parts with JS are listed.

Honestly speaking this warning is meaningess for develper as there is no explanation how to fix it.
