### ISSUE TITLE
unable make remote request even when proxy is used.

### ISSUE THREAD

**Issue by calidion** [angular/angular-cli#20261]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 No.

### Description

proxy.conf.json

```json
{
  "/getinfo": {
    "target": "https://rpc.vigcoin.org",
    "secure": false,
    "changeOrigin": true
  },
  "/json_rpc": {
    "target": "https://rpc.vigcoin.org",
    "secure": false,
    "changeOrigin": true
  }
}
```
run :

```sh
ng serve --proxy-config proxy.conf.json
```

## 🔬 Minimal Reproduction

 Unable to reproduction with website only

## 🔥 Exception or Error
<pre><code>

ERROR DOMException: The operation is insecure.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.3
Node: 12.19.0
OS: linux x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cli                    11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.0.7

</code></pre>

**Anything else relevant?**

**Comment by calidion** [comment]
@alan-agius4 

This is not a cli problem, but an angular http module problem.

https://explorer.vigcoin.org/

the jQuery Ajax can request properly without any proxy.

while angular http can not!

**Comment by alan-agius4** [comment]
Hi @calidion, 

I tried your reproduction and the first thing I noticed was `core.js:6157 ERROR DOMException: Failed to set the 'domain' property on 'Document': 'vigcoin.org' is not a suffix of 'localhost'.` which is caused by `document.domain = "vigcoin.org";` `document.domain` is deprecated and using this should be avoided. More information about this can be found in the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/domain)

The `SecurityError`, is most certainly being thrown by using the `document.domain` setter. From the mentioned MDN page:

> 
> ## Failures
> The setter will throw a "SecurityError" DOMException in several cases:
> 
> - The document-domain Feature-Policy is enabled
> - The document is inside a sandboxed <iframe>
> - The document has no browsing context
> - The document's effective domain is null
> - The given value is neither the same as the page's current hostname, nor a parent domain of it
> - As an example of this last failure case, trying to set document.domain to "example.org" when on https://example.com/ will throw.
> 
> Additionally, as part of its deprecation, it will do nothing when combined with certain modern isolation features:
> 
> - If used on a cross-origin isolated page, i.e. one that uses the appropriate values for the Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy HTTP headers
> - If used on an origin-isolated page, i.e. one that uses the Origin-Isolation HTTP header
> Finally, setting document.domain does not change the origin used for origin-checks by some Web APIs, preventing sub-domain access via this mechanism. Affected APIs include (but are not limited to): Window.localStorage, IndexedDB_API, BroadcastChannel, SharedWorker .


I removed the `document.domain`, opened the application and didn't manage to replicate the mentioned error, and response was returned successfully.

```json
{
    "already_generated_coins": 8626141935313515,
    "alt_blocks_count": 0,
    "block_major_version": 1,
    "block_minor_version": 0,
    "difficulty": 80755,
    "grey_peerlist_size": 65,
    "height": 467211,
    "incoming_connections_count": 1,
    "last_block_difficulty": 80266,
    "last_known_block_index": 467210,
    "min_tx_fee": 100,
    "outgoing_connections_count": 1,
    "status": "OK",
    "tx_count": 164341,
    "tx_pool_size": 0,
    "version": "1.2.0.1()",
    "white_peerlist_size": 2
}
```

```json
{
    "error": {
        "code": -5,
        "message": "Internal error: can't get block by height. Height = 467211."
    },
    "id": "test",
    "jsonrpc": "2.0"
}
```

**Comment by calidion** [comment]
@alan-agius4 

even remove “document.domain = "vigcoin.org""
angular can not make a request from localhost to remote server directly, while jquery can.
remote access from localhost should be easier than adding proxy.

**Comment by alan-agius4** [comment]
If you take a look at the network tab you can see that the error is caused by a CORS error which in the majority of cases indicate a problem with the configuration of the server. 

Also, this is not Angular specific, in fact you can replicate this using jQuery. 

```js
 jQuery.ajax({
  url: "https://rpc.vigcoin.org/json_rpc",
  method: "POST",
  headers : {
    'Content-Type': 'application/json'
  },
  data: JSON.stringify({
    jsonrpc: "2.0",
    id: "test",
    method: "f_block_json",
    params: {
      //hash: urlParam('hash')
    }
  }),
  dataType: 'json',
  cache: 'false',
  success: function (data) {
    console.log(data)
  }
});
```

NB: The custom headers are needed so that a preflight (OPTION) request is performed.

**Comment by calidion** [comment]
jQuery object has no ajax method within angular.

**Comment by alan-agius4** [comment]
> jQuery object has no ajax method within angular.

Fixed

**Comment by calidion** [comment]
@alan-agius4 

Could you make a pull request for me?
if you fixed the remote requesting problem?
I have temporary commented `this.url` for remote requesting.
But it will make the production and test code different.

**Comment by alan-agius4** [comment]
> @alan-agius4
> 
> Could you make a pull request for me?
> if you fixed the remote requesting problem?
> I have temporary commented `this.url` for remote requesting.
> But it will make the production and test code different.

This is a problem with the API server configuration and not the code.

**Comment by calidion** [comment]
I don't think so.
clone this code:

https://github.com/vigcoin/explorer.vigcoin.org.git

and server it with `http-server` locally.

It can request remotely with the url `rpc.vigcoin.org`.

It is the angular losing the ability to request properly with remote url locally.

**Comment by alan-agius4** [comment]
You can replicate the CORS error quite easily by using jQuery 
```html
<!DOCTYPE html>
<html></head>
<body>
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script>
    $.get('https://rpc.vigcoin.org/getinfo', function (data) {
      $.ajax({
        url: 'https://rpc.vigcoin.org/json_rpc',
        method: "POST",
        data: JSON.stringify({ "jsonrpc": "2.0", "id": "test", "method": "f_blocks_list_json", "params": { "height": 467340 } }),
        headers: {
          'Content-Type': 'application/json'
        },
        cache: 'false',
        success: function (data) {
          console.log(data)
        }
      });
    });
  </script>
</body>
</html>
```

**Comment by calidion** [comment]
@alan-agius4 
But it would working under angular.
