### ISSUE TITLE
node-zopfli@1.4.0 ACCESS DENIED

### ISSUE THREAD

**Issue by flegros** [angular/angular-cli#2027]
Hi,
I've launched the angular-cli installation with those commands:
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@webpack

After getting all npm modules properly, i receives the following errors:
- the first on execsync v1.0.2 but the process continue...
- the second on node-zopfli@1.4.0 give me an access denied error
- after that, it try to build manually the extension but is not the goal... The download of https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz should work I think...

Does anyone have a solution ?

System Windows_NT 6.1.7601
ng --version
module.js:457
    throw err;
    ^
Error: Cannot find module 'c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\bin\ng'

node --version && npm --version && node-gyp --version && python --version
v6.5.0
3.10.6
v3.4.0
Python 2.7.12

The stack:
...(all npm http request GET)...
c:\jsdev\tools\nodejs\npm-prefix\ng -> c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\bin\ng
> execSync@1.0.2 install c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ Error: spawn node-gyp ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.

> node-zopfli@1.4.0 install c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.5.0 (node-v48 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http tunneling socket could not be established, statusCode=407
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Project file contains ToolsVersion="14.0". This toolset may be unknown or missing, in which case you may be able to resolve this by installing the appropriate version of MSBuild, or the build may have been forced to a particular ToolsVersion for policy reasons. Treating the project as if it had ToolsVersion="4.0". For more information, please see http://go.microsoft.com/fwlink/?LinkId=291333.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.targets(44,5): error MSB8020: The builds tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, either click the Project menu or right-click the solution, and then select "Update VC++ Projects...". Install v140 to build using the v140 build tools. [c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-zopfli\build\zopfli.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\jsdev\\tools\\nodejs\\node.exe" "c:\\jsdev\\tools\\nodejs\\npm-prefix\\node_modules\\angular-cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=c:\\jsdev\\tools\\nodejs\\npm-prefix\\node_modules\\angular-cli\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=c:\\jsdev\\tools\\nodejs\\npm-prefix\\node_modules\\angular-cli\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-zopfli
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\jsdev\tools\nodejs\node.exe c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\jsdev\\tools\\nodejs\\node.exe" "c:\\jsdev\\tools\\nodejs\\npm-prefix\\node_modules\\angular-cli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd c:\jsdev\tools\nodejs\npm-prefix\node_modules\angular-cli\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
...

**Comment by dskatz** [comment]
I can also confirm this bug on CentOS 7.

The issue seems to be an AWS S3 Access Denied error on the tarball this installation is attempting to download:

https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-linux-x64.tar.gz

**Comment by TSkrebe** [comment]
Same problem Ubuntu 16.04

**Comment by DmitryEfimenko** [comment]
this now happens with the latest release: **1.0.0-beta.14**
I'm on Windows 10. Tried on two different computers.

**Comment by DmitryEfimenko** [comment]
I resolved an issue on Windows by installing [Visual Studio Express Desktop Edition](https://go.microsoft.com/fwlink/?LinkId=691984&clcid=0x409) as per this [suggestion on StackOverflow](http://stackoverflow.com/a/17934330/894273).

**Comment by SwagMuffinMcYoloPants** [comment]
@DmitryEfimenko I tried installing Visual Studio Express Desktop Edition and it didn't work.  I did find another [issue](https://github.com/nodejs/node-gyp/issues/307#issuecomment-240556824)

All you have to do is run power shell with admin rights and execute the following command
```npm install --global --production windows-build-tools```

**Comment by echo-sean** [comment]
I have the same issue on Mac.
A suggestion on SO to install node-gyp globally doesn't help.

OSX: 10.11.6
node: v6.5.0
npm: 3.10.3
node-gyp: v3.4.0
python: 2.7.10

**Comment by xyzlast** [comment]
Same problem Ubuntu 16.04

node: v6.6.0

**Comment by jorgeas80** [comment]
Same here. Ubuntu 16.04, Node v5.12.0, npm 3.8.6

**Comment by mblua** [comment]
Same in Windows 7 Professional. Node 6.2.2, npm 3.9.5 =/

**Comment by jorgeas80** [comment]
Solved reinstalling angular-cli. Din't have to use Node v6, finally

**Comment by flegros** [comment]
Hi,
I've tried it again :)
**npm install -g angular-cli@webpack**
and obtained the following error:

_npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\jsdev\\tools\\nodejs\\node.exe" "c:\\jsdev\\tools\\nodejs\\np
m-prefix\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@webpac
k"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7

npm ERR! No compatible version found: angular-cli@webpack
npm ERR! Valid install targets:
npm ERR! 1.0.0-beta.2-mobile.4, 1.0.0-beta.2-mobile.3, 1.0.0-beta.2-mobile.2, 1.
0.0-beta.2-mobile.1, 1.0.0-beta.2-mobile, 1.0.0-beta.12-1, 1.0.0-beta.11-webpack
.9-4, 1.0.0-beta.11-webpack.9-3, 1.0.0-beta.11-webpack.9-2, 1.0.0-beta.11-webpac
k.9-1, 1.0.0-beta.11-webpack.9, 1.0.0-beta.11-webpack.8, 1.0.0-beta.11-webpack.7
, 1.0.0-beta.11-webpack.6, 1.0.0-beta.11-webpack.5, 1.0.0-beta.11-webpack.4, 1.0
.0-beta.11-webpack.3, 1.0.0-beta.11-webpack.2, 1.0.0-beta.11-webpack, 1.0.0-beta
.16, 1.0.0-beta.15, 1.0.0-beta.14, 1.0.0-beta.12, 1.0.0-beta.10, 1.0.0-beta.9, 1
.0.0-beta.8, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.1, 1.0.0-beta.
0, 0.1.0, 0.0.39, 0.0.37, 0.0.34, 0.0.33, 0.0.31, 0.0.30, 0.0.29, 0.0.28, 0.0.27
, 0.0.26, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16
, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.
0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1, 0.0.0_

So, after uninstall angular-cli, clean the cache and try the last version:
**npm install -g angular-cli@1.0.0-beta.16**
I receives the following:

_3007 error Windows_NT 6.1.7601
3008 error argv "C:\\jsdev\\tools\\nodejs\\node.exe" "c:\\jsdev\\tools\\nodejs\\npm-prefix\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@1.0.0-beta.16"
3009 error node v6.5.0
3010 error npm  v3.10.7
3011 error code 128
3012 error Command failed: git -c core.longpaths=true clone --template=c:\jsdev\tools\nodejs\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git c:\jsdev\tools\nodejs\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5
3012 error Cloning into bare repository 'c:\jsdev\tools\nodejs\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
3012 error ssh: connect to host github.com port 22: Connection timed out
3012 error fatal: Could not read from remote repository._

I works under a corporate proxy that prevent me to checkout git repository from Internet ^^
Have you a proper solution ?
and why the version @webpack is no longer known ?

**Comment by filipesilva** [comment]
Dupe, see https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794
