### ISSUE TITLE
Bundling a index.cshtml that's containing generics doesn't work

### ISSUE THREAD

**Issue by EmilNordling** [angular/angular-cli#20276]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.0.7

### Description
 Upgrading from v9 to v11 changed the way webpack transplies HTML. The issue we're having is by changing the `index.html` target to a `index.cshtml` containing generics, the outputted bundled `index.cshtml` will have changed the generic casing to all lowercase (instead of preserving PascalCase). 

It seems like it's parsing open and close <> as an HTML tag, and runs some lower casing on it?

## 🔬 Minimal Reproduction
I've made a repo containing the issue: https://github.com/EmilNordling/angular-razor-bug

Installing node modules and running the build script is sufficient.

## 🔥 Exception or Error
```razor
// Expects that this should be preserved
@inject Microsoft.Extensions.Options.IOptions<MyPascalCaseGeneric> myValue

// Rather than getting outputted as:
@inject Microsoft.Extensions.Options.IOptions<mypascalcasegeneric> myValue
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.4
Node: 15.10.0
OS: win32 x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.1.5

</code></pre>

**Anything else relevant?**
No! :)

**Comment by alan-agius4** [comment]
Hi @EmilNordling, 

Angular CLI uses [parse5-html-rewriting-stream](https://github.com/inikulin/parse5), which is not handling the sort of syntax you are writing in the HTML file.

Unfortunately, this is not actionable from our end.
