### ISSUE TITLE
add webpack-dev-server gzip support

### ISSUE THREAD

**Issue by xpyanchong** [angular/angular-cli#2028]
By default config,Use `ng serve -prod` ,The bundle file too big.
## Before
![image](https://cloud.githubusercontent.com/assets/18358979/18388202/5398d4b2-76d3-11e6-8d44-ae230b90eb45.png)
![image](https://cloud.githubusercontent.com/assets/18358979/18388208/563648ee-76d3-11e6-8075-c4199b5ccbc2.png)
## After
![image](https://cloud.githubusercontent.com/assets/18358979/18388215/5ba9f01e-76d3-11e6-9d2b-5bde3bac7baa.png)
![image](https://cloud.githubusercontent.com/assets/18358979/18388245/740cf1ce-76d3-11e6-9321-9043622dab95.png)

# Need Change
I think this issue is important,Others maybe think the quality of this project is poor.
File `addon/ng2/tasks/serve-webpack.ts` need add gzip support;
In line 58 Insert `,compress:true`

**Comment by deebloo** [comment]
@xpyanchong I am curious what your reason for needing gzip in a dev server since it is not the serve you would use in production.

**Comment by xpyanchong** [comment]
In production i have other webserver.
I mean when developer use `ng server -prod`,server should be gzip.
Otherwise, why use ng server with prod,just need build then publish to production.
Most seed project prod mode default open gzip，Include old angular-cli version.

**Comment by mrgoos** [comment]
True, I was just about to ask how can I serve a gzipped bundle to prod. I have tried adding `,compress:true` (it's line 44 now and under `/node_modules/angular-cli/tasks/serve-webpack.js`) and it worked but I would want to know how can I pre configure it...? Is it possible? I thought it should be gzipped by default, won't it?

**Comment by achimha** [comment]
I think this is more than a nice to have, especially considering how simple a change it is. I am often on slow connections with a remote `angular-cli` and it makes a tremendous difference.

**Comment by TheLarkInn** [comment]
Doesn't this defeat the purpose of a dev environment? Plus also, it is not recommended to use `ng serve` with --prod node because these files are being transferred and stored in memory. Consider the havshing we put in file names and how that new a problem with an in-memory fs.

**Comment by achimha** [comment]
I agree that `ng serve --prod` doesn't make a lot of sense but in my opinion having the source code and build environment on a remote machine with SSH and view the web frontend from another devices does make a lot of sense. Think testing on tablets etc. 

In my current app, patching `serve-webpack-js` to enable gzip compression decreases load times by factor 2-3.

**Comment by achimha** [comment]
Thanks for the commit. However, I believe combining it with `--prod` isn't the best solution. First all we already concluded that `ng serve --prod` isn't really a major use case and secondly once spends most of the time in development mode and there major performance gains can be observed by using compression -- in a remote browser scenario.

I opt for making this a user configurable setting in `angular-cli.json`.
