### ISSUE TITLE
Error: TypeError: Cannot read property 'createStringLiteral' of undefined

### ISSUE THREAD

**Issue by light8822** [angular/angular-cli#20283]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X ] build
- [X ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

I was using the command ionic build and this error came:

### Description

Error: TypeError: Cannot read property 'createStringLiteral' of undefined
    at replacementVisitor (C:\ionic5_capacitor\node_modules\@ngtools\webpack\src\transformers\import_factory.js:186:31)
    at visitNodes (C:\ionic5_capacitor\node_modules\typescript\lib\typescript.js:73088:48)
    at Object.visitEachChild (C:\ionic5_capacitor\node_modules\typescript\lib\typescript.js:73266:156)

 A clear and concise description of the problem...

The Ionic App using Angular CLI doesn't compile

## 🔥 Exception or Error
<pre><code>

Error: TypeError: Cannot read property 'createStringLiteral' of undefined
    at replacementVisitor (C:\ionic5_capacitor\node_modules\@ngtools\webpack\src\transformers\import_factory.js:186:31)
    at visitNodes (C:\ionic5_capacitor\node_modules\typescript\lib\typescript.js:73088:48)
    at Object.visitEachChild (C:\ionic5_capacitor\node_modules\typescript\lib\typescript.js:73266:156)
</code></pre>

## 🌍 Your Environment
<pre><code>

Ionic:

   Ionic CLI                     : 5.0.0 (C:\Users\Usuario\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 5.1.1
   @angular-devkit/build-angular : 0.1102.4
   @angular-devkit/schematics    : 9.1.6
   @angular/cli                  : 9.1.6
   @ionic/angular-toolkit        : 2.3.3

Capacitor:

   Capacitor CLI   : 2.4.7
   @capacitor/core : 2.4.7

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : not available
   Cordova Plugins   : not available

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v14.16.0 (C:\Program Files\nodejs\node.exe)
   npm    : 6.14.8
   OS     : Windows 10

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, 

It looks like you are using `@angular-devkit/build-angular@0.1102.4` which is only compatible with Angular and Angular CLI 11. Please downgrade this package to `0.901.15`

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template including a minimal reproduction. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by light8822** [comment]
Thank You it worked perfectly
