### ISSUE TITLE
Can't run ng test anymore

### ISSUE THREAD

**Issue by stijn26** [angular/angular-cli#2029]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX 10.11.6

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.2.0
os: darwin x64
angular: rc6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Upgrade from RC5 to RC6 and run ng test

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
09 09 2016 15:47:41.897:WARN [karma]: No captured browser, open http://localhost:9876/
09 09 2016 15:47:41.903:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
09 09 2016 15:47:41.903:INFO [launcher]: Launching browser Chrome with unlimited concurrency
09 09 2016 15:47:41.960:INFO [launcher]: Starting browser Chrome
09 09 2016 15:47:42.676:INFO [Chrome 53.0.2785 (Mac OS X 10.11.6)]: Connected on socket /#4IYi9UAs5a77vXSQAAAA with id 12444273
Chrome 53.0.2785 (Mac OS X 10.11.6) ERROR

Chrome 53.0.2785 (Mac OS X 10.11.6) ERROR

5. Mention any other details that might be useful.

test.ts:

import 'core-js/es6';
import 'core-js/es7/reflect';

// Typescript emit helpers polyfill
import 'ts-helpers';

import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import 'zone.js/dist/sync-test';

// RxJS
import 'rxjs/Rx';

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare var __karma__: any;
declare var $: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () {};

Promise.all([
  System.import('@angular/core/testing'),
  System.import('@angular/platform-browser-dynamic/testing')
])
  // First, initialize the Angular testing environment.
  .then(([testing, testingBrowser]) => {
    testing.setBaseTestProviders(
      testingBrowser.TEST_BROWSER_DYNAMIC_PLATFORM_PROVIDERS,
      testingBrowser.TEST_BROWSER_DYNAMIC_APPLICATION_PROVIDERS
    );
  })
  // Then we find all the tests.
  .then(() => require.context('./', true, /\.specc\.ts/))
  // And load the modules.
  .then(context => context.keys().map(context))
  // Finally, start Karma to run the tests.
  .then(__karma__.start, __karma__.error);

karma.conf.js
// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: './',
    frameworks: ['jasmine', 'angular-cli'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-remap-istanbul'),
      require('angular-cli/plugins/karma')
    ],
    files: [
      { pattern: './src/test.ts', watched: false }
    ],
    preprocessors: {
      './src/test.ts': ['angular-cli']
    },
    remapIstanbulReporter: {
      reports: {
        html: 'coverage',
        lcovonly: './coverage/coverage.lcov'
      }
    },
    angularCliConfig: './angular-cli.json',
    reporters: ['progress', 'karma-remap-istanbul'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};

**Comment by lotusboy** [comment]
@stijn26 I am getting the exact same error as this. Did you find a solution?

**Comment by stijn26** [comment]
I generated a new project and compared the files (like angular-cli.json, karma.conf.js). There were some differences and after I updated them, the error was gone.

Good luck!
