### ISSUE TITLE
Symlinked Images are not served in v11 (worked in v10)

### ISSUE THREAD

**Issue by s4m0r4m4** [angular/angular-cli#20293]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes. This bug was not present in v10.0.9 and 10.1.3.

### Description
An image that is symlinked from another location into the assets directory is not properly served with `ng serve`.

## 🔬 Minimal Reproduction
Repro here: https://github.com/s4m0r4m4/ng-test-proj

This commit, on v10, works: af00cde66fac9e1d12e90aac41455545dd95c9ba
This commit, after upgrading to v11, does not work: a4de17b5ea23483d6583fd0d3b08a2c8fa2371d7

## 🔥 Exception or Error
None

## 🌍 Your Environment
<pre><code>
Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1102.4
@angular-devkit/build-angular    0.1102.4
@angular-devkit/core             11.2.4
@angular-devkit/schematics       11.2.0
@angular-devkit/schematics-cli   0.1001.7
@angular/cdk                     11.2.4
@angular/material                11.2.4
@schematics/angular              11.2.0
@schematics/update               0.1102.0
rxjs                             6.6.6
typescript                       4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi @s4m0r4m4,

You need to use  the `followSymlinks`, to allow glob patterns to follow symlink directories. This option now defaults to `false`.

```diff
             "assets": [
               "src/favicon.ico",
-              "src/assets"
+              {
+                "followSymlinks": true,
+                "input": "src/assets",
+                "glob": "**/*",
+                "output": "/assets/"
+              }
             ],
```

**Comment by s4m0r4m4** [comment]
Thanks! Should the upgrade guide be updated to include this step?
