### ISSUE TITLE
Invalid URL in version output

### ISSUE THREAD

**Issue by mmrath** [angular/angular-cli#203]
When I execute 'ng --version' the output contains http://www.angular-cli.com/user-guide/#watchman which does not exists.

```
$ng --version
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.angular-cli.com/user-guide/#watchman for more info.
node: 5.3.0
npm: 2.14.10
os: darwin x64
```

**Comment by jkuri** [comment]
This is related to `ember-cli` branding leaks as all outputs are changed from ember-cli to angular-cli. We will fix this. The url you want is http://www.ember-cli.com/user-guide/#watchman.

**Comment by mmrath** [comment]
@jkuri  Thanks
