### ISSUE TITLE
Cannot find module '@angular-devkit/core' error after installing angular cli in offline machine from npm-cache

### ISSUE THREAD

**Issue by pavitrag123** [angular/angular-cli#20302]
I'm trying to install angular-cli in an offline machine with below steps

1. In Windows10 online machine, installed node js (12.21) and angular (11.2.4). Zipped npm-cache folder
2. In windows 7 ultimate Offline machine, copied the above zipped npm-cache folder and unarchived, Pasted in appData/Roaming
3. In offline machine, ran below command. It ran for 3hrs and completed successfully
 **_'npm i @angular/cli -g --cache MY_CACHE_FOLDER --cache-min 999999999 --no-shrinkwrap'_**

But executing ng command threw error '**_can not find module '@angular-devkit/core'._**
Executing npm list -g threw **_invalid name error for multiple packages (like @angular-cli, @angular-devkit/core')_**.
Even executed permanent cache settings below but still ng command didn't succeed

1. npm config set cache PATH_TO_CACHE_FOLDER
2. npm config set cache min 999999999
3. npm config shrinkwrap false

Any help on how to make ng command work would be much appreciated.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
