### ISSUE TITLE
Rebuild is slow in version 11.2.5

### ISSUE THREAD

**Issue by jlabaj** [angular/angular-cli#20319]
even after the update to 11.2.5 it still takes 40s instead of 5 for example, without the env. variable: NG_BUILD_IVY_LEGACY=1

No maps no aot, "showCircularDependencies": false, I also updated the typescript to 4.1

with the variable it takes 5s

here is my config:
```
"customWebpackConfig": {
                "path": "./webpack-custom.config.js"
              },
              "allowedCommonJsDependencies": ["rxjs", "rxjs-compat", "inputmask", "quill-emoji", "pixi.js", "jodit"],
              "outputPath": "dist",
              "index": "src/index.html",
              "main": "src/main.ts",
              "polyfills": "src/polyfills.ts",
              "deleteOutputPath": false,
              "outputHashing": "none",
              "tsConfig": "tsconfig.app.json",
              "namedChunks": false,
              "showCircularDependencies": false,
              "extractLicenses": false,
              "statsJson": false,
              "progress": true,
              "sourceMap": false,
              "buildOptimizer": false,
              "aot": false,
              "preserveSymlinks": false,
              "optimization": false,
              "vendorChunk": true,
              "commonChunk": true,
              "assets": ["src/img"],
              "styles": [],
              "scripts": [
                "node_modules/jquery/dist/jquery.min.js",
                "node_modules/underscore/underscore-min.js",
                "libs-manual/modernizr/modernizr.js",
                "node_modules/moment/moment.js",
                "node_modules/angular/angular.js",
                "node_modules/angular-resource/angular-resource.js",
                "node_modules/angular-bindonce/bindonce.js",
                "node_modules/pixi.js/dist/pixi.js",
                "node_modules/signalr/jquery.signalR.js"
              ],
              "fileReplacements": [
                {
                  "replace": "/apps/shared/src/environments/environment.ts",
                  "with": "/apps/shared/src/environments/environment.devNoStyles.ts"
                }
              ]
environment.devNoStyles.ts:

export const environment = {
  production: false,
  optimizeTerser: true,
};
there is also a terser minimizer in the custom webpack:

optimization: {
    concatenateModules: false,
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          keep_classnames: environment.optimizeTerser ? true : false,
          keep_fnames: environment.optimizeTerser ? true : false,
        },
      }),
    ],
  },
  ```
also we have downgraded components

![image](https://user-images.githubusercontent.com/5179937/111615808-711c3f00-87e1-11eb-8baf-003536f1375d.png)

[package.zip](https://github.com/angular/angular-cli/files/6163496/package.zip)

**Comment by alan-agius4** [comment]
I suspect that the lock file is unmaintained, and hence you are using an older version of devkit packages.

Since you are using `@angular-builders/custom-webpack`, The pulled versions of `@angular-devkit/build-angular` and `@ngtools/webpack` by this dependency are used to build your application and not the once defined in your workspace `package.json`.

I suggest to clean the lock file and re-generate it.

```
rm -rf node_modules package-lock.json
npm i
```


If the problem persist after the above, please provide the output of 
```
npm ls @ngtools/webpack
```

Also, as @clydin mentioned in the other issue there are several packages which are not compatible with each other defined in your `package.json`. Also looking at your `package.json` it appears that you have a number of dependencies which might not be needed in the first place like `@angular-devkit/build-webpack`, `@angular-devkit/build-optimizer`, `@angular-devkit/architect`, `webpack-cli` , `webpack` and many others.

**Comment by jlabaj** [comment]
@alan-agius4 reinstalling the @angular-builders/custom-webpack@11.0.0 helped, updating to @angular-builders/custom-webpack@11.1.1 continued to work.

The build time with sourcemaps still did not improve however, still 40s.

...yeah I need to clean those up

**Comment by alan-agius4** [comment]
Can you please provide the output of the above mentioned command? Thanks.

**Comment by jlabaj** [comment]
@alan-agius4 it works also with the maps. the prolonged build time was probably because of the css.
the name of the script is NoCssNoMap but I set the sourceMaps:true so it works.

![image](https://user-images.githubusercontent.com/5179937/111626018-ccecc500-87ed-11eb-9173-f72d013e4d78.png)

**Comment by alan-agius4** [comment]
@jlabaj, so Is the issue solved?

**Comment by jlabaj** [comment]
@alan-agius4 I'd say yes
