### ISSUE TITLE
 "BrowserslistError: Unknown version 87 of edge" when building library project

### ISSUE THREAD

**Issue by sinanasiriamirbande** [angular/angular-cli#20324]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [1 ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ~9.1.9

### Description
i'm using angular 11.1.0 and im trying to add a library to my project.
when i make a compoenent in library and build library i got this error: 
✖ Compiling TypeScript sources through NGC
ERROR: Unknown version 87 of edge
An unhandled exception occurred: Unknown version 87 of edge
and when i removes just my component scss file from styleURls everything is ok and build is successfull.

## 🔥 Exception or Error
✖ Compiling TypeScript sources through NGC
ERROR: Unknown version 87 of edge
An unhandled exception occurred: Unknown version 87 of edge
See "/tmp/ng-akmxlF/angular-errors.log" for further details.

</code></pre>

## 🌍 Your Environment
    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.1
Node: 14.16.0
OS: linux x64

Angular: 11.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@angular/cli                    11.1.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
ng-packagr                      11.1.2
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you try to clean the `node_modules` and do a fresh reinstallation?

```
rm -rf node_modules package-lock.json
npm i 
```

**Comment by sinanasiriamirbande** [comment]
> Can you try to clean the `node_modules` and do a fresh reinstallation?
> 
> ```
> rm -rf node_modules package-lock.json
> npm i 
> ```

i tried but i got 

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web@0.0.0
npm ERR! Found: @angular/compiler@11.2.6
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"^11.1.0" from the root project
npm ERR!   peer @angular/compiler@"^11.0.0" from ng-packagr@11.2.4
npm ERR!   node_modules/ng-packagr
npm ERR!     dev ng-packagr@"^11.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"11.1.2" from @angular/compiler-cli@11.1.2
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~11.1.0" from the root project
npm ERR!   peer @angular/compiler-cli@"^11.0.0" from ng-packagr@11.2.4
npm ERR!   node_modules/ng-packagr
npm ERR!     dev ng-packagr@"^11.1.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/sina/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sina/.npm/_logs/2021-03-19T08_56_41_012Z-debug.log
`

**Comment by alan-agius4** [comment]
Looks like you are using NPM 7, versions prior to 7.6 had a defect when in resolving peer dependencies. Kindly update to the latest version of NPM and try again.

**Comment by sinanasiriamirbande** [comment]
i updated npm to 7.6.3 and npm i --legacy-peer-deps
i just got:
 8728 timing build:link:node_modules/terser Completed in 23ms
8729 timing build:link:node_modules/tree-kill Completed in 23ms
8730 timing build:link:node_modules/ts-node Completed in 23ms
8731 timing build:link:node_modules/tslint Completed in 23ms
8732 timing build:link:node_modules/typescript Completed in 23ms
8733 timing build:link:node_modules/uuid Completed in 23ms
8734 timing build:link:node_modules/webpack Completed in 23ms
8735 timing build:link:node_modules/webpack-dev-server Completed in 23ms
8736 timing build:link:node_modules/which Completed in 23ms
8737 timing build:link:node_modules/@angular-devkit/build-optimizer/node_modules/typescript Completed in 23ms
8738 timing build:link:node_modules/copy-concurrently/node_modules/rimraf Completed in 23ms
8739 timing build:link:node_modules/less/node_modules/semver Completed in 23ms
8740 timing build:link:node_modules/move-concurrently/node_modules/rimraf Completed in 22ms
8741 timing build:link:node_modules/ng-packagr/node_modules/rollup Completed in 22ms
8742 timing build:link:node_modules/ng-packagr/node_modules/sass Completed in 22ms
8743 timing build:link:node_modules/tslint/node_modules/semver Completed in 22ms
8744 timing build:link:node_modules/webdriver-manager/node_modules/semver Completed in 22ms
8745 timing build:link:node_modules/webpack-dev-server/node_modules/semver Completed in 21ms
8746 timing build:link:node_modules/webpack/node_modules/mkdirp Completed in 21ms
8747 timing build:link:node_modules/webpack/node_modules/rimraf Completed in 21ms
8748 timing build:link:node_modules/webpack/node_modules/terser Completed in 21ms
8749 timing build:link:node_modules/webpack/node_modules/semver Completed in 21ms
8750 timing build:link Completed in 26ms
8751 info run @angular/cli@11.1.2 postinstall node_modules/@angular/cli node ./bin/postinstall/script.js
8752 info run core-js@3.8.2 postinstall node_modules/core-js node -e "try{require('./postinstall')}catch(e){}"
8753 info run core-js@3.8.2 postinstall { code: 0, signal: null }
8754 timing build:run:postinstall:node_modules/core-js Completed in 135ms
8755 info run @angular/cli@11.1.2 postinstall { code: 0, signal: null }
8756 timing build:run:postinstall:node_modules/@angular/cli Completed in 492ms
8757 timing build:run:postinstall Completed in 493ms
8758 timing build:deps Completed in 562ms
8759 timing build Completed in 563ms
8760 timing reify:build Completed in 569ms
8761 timing reify:trash Completed in 3ms
8762 timing reify:save Completed in 276ms
8763 timing reify Completed in 108777ms
8764 timing command:i Completed in 114362ms
8765 verbose stack Error: command failed
8765 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
8765 verbose stack     at ChildProcess.emit (events.js:315:20)
8765 verbose stack     at maybeClose (internal/child_process.js:1048:16)
8765 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
8766 verbose pkgid web@0.0.0
8767 verbose cwd /home/sina/Documents/Projects/pipes-new-layout
8768 verbose Linux 5.8.0-45-generic
8769 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--legacy-peer-deps"
8770 verbose node v14.16.0
8771 verbose npm  v7.6.3
8772 error code 1
8773 error path/myproj
8774 error command failed
8775 error command sh -c ngcc
8776 verbose exit 1

**Comment by alan-agius4** [comment]
Are you using `ngcc` as a post install hook? If so can you please remove it.

**Comment by sinanasiriamirbande** [comment]
I removed   "postinstall": "ngcc" from my package.json scripts,
but when am build my npm it works.
but when i am building my library i got same error:
⠙ Compiling TypeScript sources through NGCCompiling @angular/core : es2015 as esm2015
Error: Error on worker #1: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at __read (/myproj/node_modules/tslib/tslib.js:174:50)
    at Object.__spread (/myproj/node_modules/tslib/tslib.js:193:28)
    at Renderer.renderAdjacentStatements (/myproj/node_modules/@angular/compiler-cli/ngcc/src/rendering/renderer.js:159:63)
    at /home/sina/Documents/Projects/pipes-new-layout/node_modules/@angular/compiler-cli/ngcc/src/rendering/renderer.js:80:52
    at Array.forEach (<anonymous>)
    at Renderer.renderFile (/myprojt/node_modules/@angular/compiler-cli/ngcc/src/rendering/renderer.js:76:46)
    at /myproj/node_modules/@angular/compiler-cli/ngcc/src/rendering/renderer.js:53:84
    at Array.forEach (<anonymous>)
    at Renderer.renderProgram (myproj/node_modules/@angular/compiler-cli/ngcc/src/rendering/renderer.js:48:54)
    at Transformer.transform (/myproj/node_modules/@angular/compiler-cli/ngcc/src/packages/transformer.js:84:42)
    at ClusterMaster.onWorkerMessage (/myproj/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /myproj/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/myproj/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/my-proj/node_modules/tslib/tslib.js:143:27)
    at Object.next (/my-proj/node_modules/tslib/tslib.js:124:57)
    at /myproj/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/myproj/node_modules/tslib/tslib.js:113:16)
    at EventEmitter.<anonymous> (myproj/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
✖ Compiling TypeScript sources through NGC
ERROR: NGCC failed.
An unhandled exception occurred: NGCC failed.
See "/tmp/ng-U5bdo8/angular-errors.log" for further details.

**Comment by sinanasiriamirbande** [comment]
> Can you re-run `ng version` please?

Angular CLI: 11.1.2
Node: 14.16.0
OS: linux x64

Angular: 11.2.6
... animations, common, compiler, core, forms, localize
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cdk                    11.2.5
@angular/cli                    11.1.2
@angular/compiler-cli           11.1.2
@angular/material               11.2.5
@schematics/angular             11.1.2
@schematics/update              0.1101.2
ng-packagr                      11.2.4
rxjs                            6.6.6
typescript                      4.0.7

**Comment by alan-agius4** [comment]
The problem most likely is due to mixing `@angular` versions.

Example:
@angular/compiler-cli 11.1.2
@angular/core 11.2.6

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
