### ISSUE TITLE
Question:  Where is the webpack configuration is kept?

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#2032]
My question:  Where is the webpack configuration is kept for default project and how I would go about changing it from project to project using the CLI?

Meaning I created 2 projects and I want the webpack configuration to be different for each project.  How I would go about that?

**Comment by deebloo** [comment]
@daBishMan there has been lengthy discussion about exposing the webpack config. you can view it here. https://github.com/angular/angular-cli/issues/1656

**Comment by daBishMan** [comment]
Thank you so much, search is your friend.

**Comment by deebloo** [comment]
@daBishMan if your question is answered would you mind closing this issue?
