### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Chinna2405** [angular/angular-cli#20335]
Hi ,

I am running my application in two different instances. For load balancing I am mapping a new instance to point the existing two instances. But I am getting the below error.

![image](https://user-images.githubusercontent.com/53597153/111778450-ac4e6900-88da-11eb-9555-2e4f2cfcd24c.png)

Thanks in Advance.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
