### ISSUE TITLE
Build error because of license-webpack-plugin with webpack 5, ModuleFederation plugin.

### ISSUE THREAD

**Issue by ikalyakin** [angular/angular-cli#20356]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, error happens after this [commit](https://github.com/angular/angular-cli/commit/ea02b6e94710d43ab9c2738765c17d234dce353e#diff-5b54a4601b5d50cc0617712190a902a19f4ea2d044c836e98d5cf8e9e6c4a6f3)

### Description

New clean project with webpack 5 and ModuleFederation plugin: ng build fails if `extractLicenses` is `true`.
A package `@angular-devkit/build-angular` (0.1102.5) has dependency `license-webpack-plugin` (2.3.11) which has an issue has been solved in this [commit](https://github.com/xz64/license-webpack-plugin/commit/a22b4a64f94de1edcde83f2c745ffa0201eee244#diff-5a5c513f0d9f5557331f013846e996727746302e89b394c0b705c1e7affd65b1). This fix is available from version 2.3.13 of `license-webpack-plugin`.
Versions of `@angular-devkit/build-angular` 0.1200.x has `license-webpack-plugin` with 2.3.15 version which hasn't this issue. This version update could be brought to 0.1102.x. 

## 🔬 Minimal Reproduction

Minimal reproduction is available [here](https://github.com/ikalyakin/angular-mf-example). Important: install dependencies using `yarn` (because of `resolutions` section in `package.json`)
Also you can follow this steps:
- generate new project with `ng new angular-mf-example --skip-tests --package-manager=yarn` 
- define `"webpack": "^5.4.0"` in `resolutions` section of `package.json`
- change `architect.build.builder` to `ngx-build-plus:browser`
- define `architect.build.builder.options.extraWebpackConfig` as `webpack.config.js`
- create `webpack.config.js` with this [content](https://github.com/ikalyakin/angular-mf-example/blob/main/webpack.config.js)
- create `src/bootstrap.ts` with this [content](https://github.com/ikalyakin/angular-mf-example/blob/main/src/bootstrap.ts)
- update `src/main.ts` with this [content](https://github.com/ikalyakin/angular-mf-example/blob/main/src/main.ts)
- run `ng build --prod`
- get error `ENOENT: no such file or directory`

## 🔥 Exception or Error
<pre><code>
An unhandled exception occurred: ENOENT: no such file or directory, open '\package.json'
See "C:\Temp\ng-CN9MLQ\angular-errors.log" for further details.
error Command failed with exit code 127
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.5
Node: 14.15.4
OS: win32 x64

Angular: 11.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1102.5
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.5
@angular/cli                    11.2.5
@schematics/angular             11.2.5
@schematics/update              0.1102.5
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @ikalyakin, 

Thanks for opening the issue.  Please be aware that Webpack 5 support in version 11 is still experimental and is not deemed as stable and shouldn't be used for production environments. 

There are a couple of things you can do here; 
- Opt out from using `extractLicenses` to restore the behaviour prior to https://github.com/angular/angular-cli/commit/ea02b6e94710d43ab9c2738765c17d234dce353e#diff-5b54a4601b5d50cc0617712190a902a19f4ea2d044c836e98d5cf8e9e6c4a6f3
- Add a resolution for `license-webpack-plugin` to `2.3.11`
- Update to Angular CLI pre-release, using `ng update @angular/cli --next` which has better Webpack 5 support.

It is important to mention that while we do allow customizing the Webpack configuration, by doing so you are venturing in unsupported territory.
