### ISSUE TITLE
3rd party libs not being pulled into global css or js 

### ISSUE THREAD

**Issue by jspenc72** [angular/angular-cli#2035]
> Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```bash
$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.11-webpack.2
node: 4.2.2
os: darwin x64
$ 
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
- Create new project with angular-cli@webpack

4. The log given by the failure. Normally this include a stack trace and some
   more information.
no errors are output

5. Mention any other details that might be useful.

```json

{
  "project": {
    "version": "1.0.0-beta.11-webpack.2",
    "name": "ready-med"
  },
  "apps": [
    {
      "main": "src/main.ts",
      "tsconfig": "src/tsconfig.json",
      "mobile": false,
      "styles" : [
        "styles.scss",
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ],
      "scripts" : [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/tether/dist/js/tether.js",
        "../node_modules/bootstrap/dist/js/bootstrap.js"        
      ]
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "config/protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "config/karma.conf.js"
    }
  },
  "defaults": {
    "prefix": "app",
    "sourceDir": "src",
    "styleExt": "scss",
    "prefixInterfaces": false,
    "lazyRoutePrefix": "+"
  }
}
  
```
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by aszechlicki** [comment]
update angular-cli
this issue is fixed in 1.0.0-beta.11-webpack.8

**Comment by jspenc72** [comment]
Updating resolved the issue

**Comment by jspenc72** [comment]
Thank you!

**Comment by jaimehrubiks** [comment]
It isn't working for me using latest update. At least bootstrap isn't.
I will check again tomorrow but I am pretty sure I used latest version and performed same steps op did.

**Comment by aszechlicki** [comment]
@jaimehrubiks double-check paths, I lost a lot of time before I noticed that I had mine wrong
paths in global scripts and styles are relative to your apps[0].root directory

unfortunately, angular-cli doesn't give any error/warning if it cannot find specified files

**Comment by ewoutreinders** [comment]
What OS do you use? I also noticed something strange in term of using angular-cli.

On Windows 7, I used a cli file like you (in terms of the bootstrap path in the styles property) and it seemed to work fine. If I use the exact same file on a build server in a linux environment, it didn't worked. What I did is that I placed the bootstrap path as an import in the global styles.css like below:
@import '../node_modules/bootstrap/dist/css/bootstrap.css';

After this change, it worked fine on both environments, so it seems to be that there is some different behaviour in terms of OS. I am also not sure what the difference is between the property styles and the global styles.css. Should external stylesheets from a different package be loaded using the global styles.css, using the cli config file or both should be supported?

**Comment by aszechlicki** [comment]
global styles.css file is meant for your custom css that you want applied to the whole application  
styles in apps[0].styles are third-party styles that you want to load

**Comment by jspenc72** [comment]
@jaimehrubiks try generating a new project with ```ng new``` 
Then verify that the angular-cli.json have webpack 8 in the version.

**Comment by keithmichelson** [comment]
Doesn't work for me, I get a generic "Error" on ng serve that's it. i'm on 1.0.0-beta.11-webpack.8 but using scss as the default.

**Comment by jaimehrubiks** [comment]
It is working.

My problem seems to be related to bootstrap, somehow it does not work correctly when following the guide on this repo (on osx). But I downloaded it manually (instead of npm) and put it on assets folder and linked on styles[0] and it works perfect.

**Comment by filipesilva** [comment]
This functionality was only present starting `1.0.0-beta.11-webpack.8`. The current latest `1.0.0-beta.14` also fully supports this.
