### ISSUE TITLE
Uncaught Error: Missing: SyncTestZoneSpec

### ISSUE THREAD

**Issue by zackporter92** [angular/angular-cli#2036]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac El capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.2.2
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I created this app using the webpack 2 version.  Since rc6 was released I upgraded to rc6 and modified all the tests to match the new way of doing them with TestBed instead of addProviders.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Chrome 52.0.2743 (Mac OS X 10.11.6) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at /Users/porteraz/workspace/travel/travel-client/src/test.ts:59883 <- webpack:///Users/porteraz/workspace/travel/travel-client/~/zone.js/dist/jasmine-patch.js:66:0

Chrome 52.0.2743 (Mac OS X 10.11.6) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at /Users/porteraz/workspace/travel/travel-client/src/test.ts:59883 <- webpack:///Users/porteraz/workspace/travel/travel-client/~/zone.js/dist/jasmine-patch.js:66:0

5. Mention any other details that might be useful.

According to this github issue in zone.js:
https://github.com/angular/zone.js/issues/404

We need to add the following to the config/karma-test-shim.js (or config/spec-bundle.js):

require('zone.js/dist/proxy'); // since zone.js 0.6.15
require('zone.js/dist/jasmine-patch'); // put here since zone.js 0.6.14

But I can't find a karma-test-shim.js to update. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hschoefer** [comment]
I have the same problem with Ubuntu 16.04 LTS after changing from angular-cli@1.0.0-beta.10 to the angular-cli@webpack.

angular-cli: git master
node: 6.2.1
os: Ubuntu 16.04 LTS 64 Bit

@zackporter92 The [official instruction](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md) for the change says that some file not needed anymore. One of this file is _karma-test-shim.js_.

**Comment by hschoefer** [comment]
As far as I can see I found the problem. I took a look into angular-cli template file and ended at _test.ts_ (1) file. This file has one import more than my _test.ts_ file and the order of the imports were different.

(1) https://github.com/angular/angular-cli/blob/master/addon/ng2/blueprints/ng2/files/__path__/test.ts#L3-L8

Now I'm getting an other error which says that a provider for a component can't be found. I think this indicates that the original problem is solved.

**Comment by filipesilva** [comment]
This is currently added in `beta.14`, under `src/test.ts`.

**Comment by Angelmmiguel** [comment]
The location of that file has been changed: https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng2/files/__path__/test.ts

**Comment by Hirse** [comment]
Location changed again:
https://github.com/angular/angular-cli/blob/master/packages/@angular/cli/blueprints/ng/files/__path__/test.ts

**Comment by RoestVrijStaal** [comment]
Thanks for the person who deleted the blueprints directory :rage: :rage: :rage:
