### ISSUE TITLE
ssri ReDOS vulnerability

### ISSUE THREAD

**Issue by Synectron** [angular/angular-cli#20373]
I'm using angular 11 with @angular-devkit/build-angular :"^0.1102.0". It is using ssri version "6.0.1" as dependency which is vulnerable to ReDos as stated by synk.io as well as black duck scan. What needs to be done to remedy it? I even updated it to version "0.1102.6" which was published 7 hours ago, but to no avail.

**Comment by clydin** [comment]
Duplicate of #20285
