### ISSUE TITLE
Updating from 11.2.5 to 11.2.6 throws an error

### ISSUE THREAD

**Issue by catapop84** [angular/angular-cli#20375]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present

### Description
 A clear and concise description of the problem...
When I tried to update from 11.2.5 to 11.2.6 with `ng update @angular/cli` , I receive an error.

## 🔬 Minimal Reproduction
`ng update @angular/cli`

## 🔥 Exception or Error
```
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: @angular-devkit/build-angular@0.1102.5
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"~0.1102.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! dev @angular-devkit/build-angular@"~0.1102.6" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/localize@11.2.7
npm ERR! node_modules/@angular/localize
npm ERR!   peerOptional @angular/localize@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.6
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1102.6" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.2.5
Node: 15.10.0
OS: win32 x64

Angular: 11.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.5
@angular-devkit/build-angular   0.1102.5
@angular-devkit/core            11.2.5
@angular-devkit/schematics      11.2.5
@angular/cdk                    11.2.5
@angular/cli                    11.2.5
@angular/material               11.2.5
@schematics/angular             11.2.5
@schematics/update              0.1102.5
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Comment by jfai** [comment]
Same issue here.

**Comment by MarcusRiemer** [comment]
Can confirm that it is also broken when coming from 11.2.5 with npm 7 and node 14.16. I get the exact same error message.

```
ngular CLI: 11.2.4
Node: 14.16.0
OS: linux x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cdk                    11.2.4
@angular/cli                    11.2.4
@angular/material               11.2.4
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.2.1
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.1.3
```

**Comment by clydin** [comment]
This is unfortunately an issue with npm 7 and its new peer dependency resolution process.
`@angular/localize@11.2.7` satisfies the SemVer range of `@angular/localize@"^11.0.0 || ^11.2.0-next"` but npm 7 is treating it as a failure.

**Comment by MarcusRiemer** [comment]
So maybe passing `--legacy-peer-deps` to npm on npm 7 could help? But I don't see an option to tell `ng update` to pass any flags to `npm`.

**Comment by clydin** [comment]
That, unfortunately, would most likely require every invocation of `npm` to use the flag.
As a temporary solution, there are two potential options: 1. use npm 6; 2. add an `.npmrc` file to the project that sets the `--legacy-peer-deps` flag.  Neither of which are an ideal long-term solution as the new npm behavior is intended to catch legitimate package version errors.

**Comment by alan-agius4** [comment]
Let's continue tracking this issue in npm/cli#3152 since this is not actionable by Angular.
