### ISSUE TITLE
Hi I tried to install angular cli through the command : npm install -g @angular/cli

### ISSUE THREAD

**Issue by Hema-Sasank** [angular/angular-cli#20379]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Description
not able to execute the command ng --version eventhough the node versions and npm versions are is the range.

I followed these steps:

sudo apt update
sudo apt install build-essential apt-transport-https lsb-release ca-certificates curl

curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

sudo apt install nodejs

## 🔬 Minimal Reproduction
ng --version

## 🔥 Exception or Error
Unknown error: SyntaxError: Unexpected token 'export'

## 🌍 Your Environment
node -v
v12.21.0

npm -v
6.14.11

cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"

**Comment by COAB1** [comment]
Did you try this?
$ npm cache clean --force
$ npm install -g @angular/cli

**Comment by clydin** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
