### ISSUE TITLE
Bug Report: Problems creating new library

### ISSUE THREAD

**Issue by SiddharthShyniben** [angular/angular-cli#20383]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Don't know, first time using this feature.

### Description

I was trying to create an angular library. I followed all the commands given in the documentation but after I ran the `ng generate library name` command I got an error while installing packages. My guess is that the cli was trying to install a nonexistent library though I'm not sure. See below for error message

## 🔬 Minimal Reproduction

Run the following commands:
* `ng new my-lib --create-application=false`
* `cd my-lib`
* `ng generate library my-lib`

At this point you should get an error while installing packages

## 🔥 Exception or Error
<pre><code>
⠏ Installing packages (npm)...npm WARN ERESOLVE overriding peer dependency
npm WARN Found: postcss@undefined
npm WARN node_modules/ng-packagr/node_modules/postcss
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer postcss@"^8.0.0" from postcss-url@10.1.3
npm WARN node_modules/ng-packagr/node_modules/postcss-url
npm WARN   postcss-url@"^10.1.1" from ng-packagr@11.2.4
npm WARN   node_modules/ng-packagr
npm ERR! code ETARGET
npm ERR! notarget No matching version found for autoprefixer@^10.2.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2021-03-26T11_16_20_754Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.0.6
Node: 14.15.1
OS: darwin x64

Angular: 11.0.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.6
@angular-devkit/build-angular   <error>
@angular-devkit/core            11.0.6
@angular-devkit/schematics      11.0.6
@angular/cli                    11.0.6
@schematics/angular             11.0.6
@schematics/update              0.1100.6
ng-packagr                      <error>
rxjs                            6.6.3
typescript                      4.0.5
</code></pre>

**Anything else relevant?**

No

**Comment by clydin** [comment]
From the output log, it appears than npm 7 is in use.  Please try update to the latest version of npm 7 as earlier versions contained defects that would prevent package installation in a variety of cases.

**Comment by SiddharthShyniben** [comment]
I'm having some trouble installing v7.7.5 of npm. When I fix that I will see

**Comment by alan-agius4** [comment]
Hi @SiddharthShyniben, 
I am unable to replicate the above using NPM 7.10.
