### ISSUE TITLE
option minimal not working

### ISSUE THREAD

**Issue by vkuehn** [angular/angular-cli#20395]
# 🐞 Bug report

ng new --help

shows
....
  --minimal 
    Create a workspace without any testing frameworks. (Use for learning purposes only.)
...

but 

ng new newApp –-minimal 

shows 
Unknown option: '–-minimal'

### Is this a regression?

I have searched for issues mentioning that but they all has been closed by the bot. Seem to have worked in much older versions

### Description

this happens in cli command
ng new newApp –-minimal

## 🔬 Minimal Reproduction
ng new newApp –-minimal

## 🔥 Exception or Error
Unknown option: '–-minimal'

## 🌍 Your Environment
Angular CLI: 11.2.6
Node: 14.16.0
OS: linux x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.6 (cli-only)
@angular-devkit/core         11.2.6 (cli-only)
@angular-devkit/schematics   11.2.6 (cli-only)
@schematics/angular          11.2.6 (cli-only)
@schematics/update           0.1102.6 (cli-only)

**Comment by alan-agius4** [comment]
The first character in the command argument doesn’t look like a dash.

**Comment by vkuehn** [comment]
these are two dashes as mentioned for all parameters from ng new --help

**Comment by clydin** [comment]
@alan-agius4 is referring to the first character in this sequence from above: "–-minimal".  "–" and "-" are different characters with the later being a dash.

**Comment by vkuehn** [comment]
very well spotted ! 
thought it is a copy paste error from some webblogs.

ng new newApp --minimal

works fine !
