### ISSUE TITLE
[Question] Windows support and build times

### ISSUE THREAD

**Issue by mmrath** [angular/angular-cli#204]
Hi, is angular-cli is really going to be official tool around angular2?
I know ember-cli had pretty bad performance on Windows. I think most of the corporate users will be on windows and many of them won't have admin right on the workstation. Are there any plans for addressing this in the short term(few months)? 

I have noticed that even on Mac the initial build is taking too long.

**Comment by jkuri** [comment]
Windows performance issues are resolved with https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/windows-admin.js and https://github.com/ember-cli/ember-cli/blob/master/lib/commands/serve.js#L69, but you are right, if you don't have admin permissions it's not working okay. 

Initial build in my opinion takes long as all vendor files being copied, afterwards it works flawlessly.

**Comment by filipesilva** [comment]
*Right now* it isn't a big priority, no. That might change in the future, but I wouldn't expect such improvement short-term.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/905 should allow non-admin user usage.
