### ISSUE TITLE
ng build is slow, runs out of memory after angular upgrade from 10 to 11 with notus-angular template

### ISSUE THREAD

**Issue by iantv** [angular/angular-cli#20406]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Initially I used this version of 'notus-angular' template:  https://github.com/creativetimofficial/notus-angular/commit/923b9de2f994a16ca1e0d4902e7c8d8ac2dc59f9
It requires angular 10.2.1 and `ng serve` command is fast (few seconds)

The repo of my project https://github.com/array-team/argo-platform/commit/d9f52145ec91ba18a8ab7c80d0c8fb536a1073ed

### Description
I tried update most of all packages using `ncu` and package.json of my project became
```
  "dependencies": {
    "@angular/animations": "11.2.7",
    "@angular/common": "11.2.7",
    "@angular/compiler": "11.2.7",
    "@angular/core": "11.2.7",
    "@angular/forms": "11.2.7",
    "@angular/platform-browser": "11.2.7",
    "@angular/platform-browser-dynamic": "11.2.7",
    "@angular/router": "11.2.7",
    "@fortawesome/fontawesome-free": "5.15.3",
    "@popperjs/core": "2.9.1",
    "@tailwindcss/forms": "0.2.1",
    "@types/popper.js": "^1.11.0",
    "@types/three": "^0.126.2",
    "chart.js": "2.9.4",
    "popper": "^1.0.1",
    "rxjs": "6.6.7",
    "tailwindcss": "2.0.4",
    "three": "^0.126.1",
    "treejs": "^0.6.2",
    "tslib": "2.1.0",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1102.6",
    "@angular/cli": "11.2.6",
    "@angular/compiler-cli": "11.2.7",
    "@angular/language-service": "11.2.7",
    "@types/jasmine": "3.6.9",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "14.14.37",
    "codelyzer": "6.0.1",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "6.0.0",
    "karma": "6.3.2",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "3.0.3",
    "karma-jasmine": "4.0.1",
    "karma-jasmine-html-reporter": "1.5.4",
    "protractor": "7.0.0",
    "ts-node": "9.1.1",
    "tslint": "6.1.3",
    "typescript": "^4.1.5"
```

after that I ran command:
`rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm run build:tailwind && npm start`
I got
<details>
  <summary>`ng serve`: log to terminal</summary>  
> ng serve

Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
⠼ Generating browser application bundles (phase: building)...
<--- Last few GCs --->

[76566:0x104679000]   336659 ms: Scavenge (reduce) 2027.9 (2066.6) -> 2027.9 (2066.6) MB, 2.7 / 0.0 ms  (average mu = 0.446, current mu = 0.297) allocation failure 
[76566:0x104679000]   336735 ms: Scavenge (reduce) 2029.2 (2067.8) -> 2029.2 (2067.8) MB, 3.7 / 0.0 ms  (average mu = 0.446, current mu = 0.297) allocation failure 
[76566:0x104679000]   337355 ms: Scavenge (reduce) 2031.7 (2070.3) -> 2031.7 (2070.3) MB, 6.8 / 0.0 ms  (average mu = 0.446, current mu = 0.297) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0x1000af220 node::Abort() [/usr/local/bin/node]
 2: 0x1000af396 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001ecccd v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x1001ecc77 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10033157f v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x10036b2d4 v8::internal::EvacuateNewSpaceVisitor::Visit(v8::internal::HeapObject, int) [/usr/local/bin/node]
 7: 0x10035ade9 void v8::internal::LiveObjectVisitor::VisitBlackObjectsNoFail<v8::internal::EvacuateNewSpaceVisitor, v8::internal::MajorNonAtomicMarkingState>(v8::internal::MemoryChunk*, v8::internal::MajorNonAtomicMarkingState*, v8::internal::EvacuateNewSpaceVisitor*, v8::internal::LiveObjectVisitor::IterationMode) [/usr/local/bin/node]
 8: 0x10035a9d7 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/usr/local/bin/node]
 9: 0x10035a6e6 v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/usr/local/bin/node]
10: 0x10036e045 v8::internal::PageEvacuationTask::ProcessItems() [/usr/local/bin/node]
11: 0x10036dfe0 v8::internal::PageEvacuationTask::RunInParallel(v8::internal::ItemParallelJob::Task::Runner) [/usr/local/bin/node]
12: 0x10034394c v8::internal::ItemParallelJob::Task::RunInternal() [/usr/local/bin/node]
13: 0x100343cd2 v8::internal::ItemParallelJob::Run() [/usr/local/bin/node]
14: 0x10035c36d void v8::internal::MarkCompactCollectorBase::CreateAndExecuteEvacuationTasks<v8::internal::FullEvacuator, v8::internal::MarkCompactCollector>(v8::internal::MarkCompactCollector*, v8::internal::ItemParallelJob*, v8::internal::MigrationObserver*, long) [/usr/local/bin/node]
15: 0x10035c14a v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/usr/local/bin/node]
16: 0x10034fb9a v8::internal::MarkCompactCollector::Evacuate() [/usr/local/bin/node]
17: 0x10034da42 v8::internal::MarkCompactCollector::CollectGarbage() [/usr/local/bin/node]
18: 0x100331b01 v8::internal::Heap::MarkCompact() [/usr/local/bin/node]
19: 0x10032fdad v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]
20: 0x10032e673 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
21: 0x100337442 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
22: 0x10033749a v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
23: 0x1003146ed v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
24: 0x10059a72a v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
25: 0x10083d119 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
sh: line 1: 76565 Abort trap: 6           npm start
</details> 

Later I saw that original repository of the notus-angular template has updated dependencies 
https://github.com/creativetimofficial/notus-angular/releases/tag/1.1.0
I tried run `ng serve` for updated version of the template and it was build and run, but required ~ 7-8 minutes for 
`generating browser application bundles (phase: building)`.
It looks like a bug too. But I don't understand where. Recall that the older version of the template with command `ng serve` ran much faster.

## 🔬 Minimal Reproduction
I couldn't reproduce crash with new repo, but the slowdown is reproducible using repo of the template of different versions
Faster version: https://github.com/creativetimofficial/notus-angular/commit/923b9de2f994a16ca1e0d4902e7c8d8ac2dc59f9
Slower version: https://github.com/creativetimofficial/notus-angular/commit/2057723e3c2a405d8c08b5e970b38fb19eb4cad0

Simple steps to reproduce this bug.
`npm run install:clean`

## 🌍 Your Environment
In a local directory of the notus-angular template after updating packages:
```
Angular CLI: 11.2.4
Node: 15.12.0
OS: darwin x64

Angular: 11.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.4
@angular-devkit/build-angular   0.1102.4
@angular-devkit/core            11.2.4
@angular-devkit/schematics      11.2.4
@angular/cli                    11.2.4
@schematics/angular             11.2.4
@schematics/update              0.1102.4
rxjs                            6.6.6
typescript                      4.1.5
```
before upgrading: 
```
Angular CLI: 10.1.2
Node: 15.12.0
OS: darwin x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@schematics/angular             10.1.2
@schematics/update              0.1001.2
rxjs                            6.6.3
typescript                      4.0.3
```

**Comment by alan-agius4** [comment]
In Angular CLI version 11.2 we introduced the opt-in feature to process tailwind CSS (https://github.com/angular/angular-cli/pull/19935) as part of the build. 

In the mentioned project, the tailwind CSS configuration is configured to purge unused CSS https://github.com/creativetimofficial/notus-angular/blob/2057723e3c2a405d8c08b5e970b38fb19eb4cad0/tailwind.config.js#L6, even during development, which is not recommended as take a considerable amount of time and resources.

| Matric        | Duration |
|---------------|----------|
| With tailwind CSS processing with purge CSS | 149589ms |
| With tailwind CSS processing without purge CSS | 9267ms |
| Without tailwind CSS processing | 7599ms |

Please file an issue with https://github.com/creativetimofficial/notus-angular
