### ISSUE TITLE
Extract CSS when using ViewEncapsulation.None

### ISSUE THREAD

**Issue by HeathJared** [angular/angular-cli#20408]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When using `ViewEncapsulation.None` styles are still in-lined into the component JavaScript. This can lead to unnecessarily bloated file sizes and loading times on large applications (especially when including multiple themes).

### Describe the solution you'd like

In our situation, it would be preferred to have all of these "global" component styles compiled into a separate CSS file (single or multiple files). Order of the styles does not matter for our use case.

(Optional) Additionally, it may be nice to have the CSS files lazy loaded along side lazy loaded modules.

### Describe alternatives you've considered

Keeping component styles in the local `component.scss` file to maintain a logical folder structure, but commenting it out in the `component.ts` file and manually importing each component style into the main `style.scss` file.

**Comment by AleksanderBodurri** [comment]
@HeathJared If you move forward with refactoring out theme styles from component styles but still want lazy loadable theme css you can do the following:
1. Specify theme scss in the `styles` array inside `angular.json` with the `inject: false` flag to prevent it from being injected into `index.html`. See [this](https://github.com/angular/material.angular.io/blob/master/angular.json#L53) for an example.
2. Load in the style sheet at runtime by injecting a `<link>` tag into the DOM when the theme is requested by the client. See [this](https://github.com/angular/material.angular.io/blob/1c9b4f6032f474354262e767da7605ef17cf55d6/src/app/shared/style-manager/style-manager.ts) for an example.

This is how https://material.angular.io/ handles lazy loading themes. You can also look at a PR I have open for https://angular.io/ that implements similar functionality lazy loading a dark mode theme: https://github.com/angular/angular/pull/41129.

Feel free to reach out if anything is unclear 😃

**Comment by HeathJared** [comment]
@AleksanderBodurri thanks that is something we were looking into.

@alan-agius4 After discussing this internally, I am not completely satisfied closing the issue.

What we specifically don't want to do is manually maintain (or include) each global component style or theme in a large master file(s). Also, it would be preferred to keep styles and themes adjacent to the component files within the folder structure and compile them as needed.

Using other tools (webpack, gulp, etc) we would be able to compile these files by targeting `**/*.some-thing.scss` or whatever the use case may need.

Similar to the [example](https://github.com/angular/material.angular.io/blob/master/angular.json#L53) that was linked above, it would probably solve our concerns if we could specify globs for bundled styles as we needed depending on the situation.

```
              {
                "inject": true | false,
                "glob": "**/*.some-thing.scss",
                "input": "src",
                "bundleName": "some-thing"
              }
```

or 

```
              {
                "inject": true | false,
                "input": "src/**/*.some-thing.scss",
                "bundleName": "some-thing"
              }
```

Maybe even going as far as being able to specify a specific `_variables.scss` file or a source scss file (to which the globs would be appended) prior to bundling the styles.

Another alternative would be support something similar to the [gulp-sass-glob](https://www.npmjs.com/package/gulp-sass-glob) package which would allow us to handle this within the sass files instead.

Is there a way to achieve this (or anything similar) using angular-cli/angular.json?

Thanks for your feedback.
