### ISSUE TITLE
Issue with scss processing on @media queries with multiple 'and' logic

### ISSUE THREAD

**Issue by jpduckwo** [angular/angular-cli#20424]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] build
- [x] serve

### Is this a regression?
Unsure

### Description
The following media queries (in SCSS files) get compiled into incorrect media rules which break the targeting. I have verified this is not coming from SASS and seems to be coming from PostCSS autoprefixer.

```
@media screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm) {
  .something {
    color: red;
  }
}
```
It compiles to:
```
@media screen and (-webkit-min-device-pixel-ratio: 0) and (-webkit-min-device-pixel-ratio: 0), screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm)
.something {
    color: red;
}
```
As a workaround it is possible to stop this behaviour by using `/* autoprefixer: off */` in the file

## 🔬 Minimal Reproduction

- `ng new` select scss as the style format
- Edit src/styles.scss and add the following content
<pre><code>
@media screen and (-webkit-min-device-pixel-ratio: 0) and (min-resolution: 0.001dpcm) {
  .something {
    color: red;
  }
}
</code></pre>
- `ng build`
- Inspect the output of dist/\<project\>/styles.css

## 🔥 Exception or Error
NA

## 🌍 Your Environment
Using version 
<pre><code>
Angular CLI: 11.2.6
Node: 14.15.1
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.6
@angular-devkit/build-angular   0.1102.6
@angular-devkit/core            11.2.6
@angular-devkit/schematics      11.2.6
@angular/cli                    11.2.6
@schematics/angular             11.2.6
@schematics/update              0.1102.6
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
Indeed @jpduckwo, this does appear to be an issue with autoprefixer.

Please contact the author(s) of the [autoprefixer](https://github.com/postcss/autoprefixer) or file an issue on their issue tracker.
