### ISSUE TITLE
Module Federation emits zero-sized files

### ISSUE THREAD

**Issue by glebmachine** [angular/angular-cli#20428]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
It's early version bug

### Description
It's report about early support of webpack 5 and module federation.
When internal library added as shared dependency, cli emits zero-sized files
![image](https://user-images.githubusercontent.com/1610882/113196020-a86ffe80-926b-11eb-9f9e-05c51aae3808.png)
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Repro:
1. `git clone git@github.com:glebmachine/module-federation-zero-sized-bundle.git `
2. `yarn`
2. `./node_modules/.bin/ng run shell:serve`

Step to `repair build`:
1. Open `projects\shell\webpack.config.js`
2. Comment 8 line:
![image](https://user-images.githubusercontent.com/1610882/113196190-e0774180-926b-11eb-830b-9bce17ec0bfc.png)

## 🔥 Exception or Error
See picture above

## 🌍 Your Environment
<pre>Angular CLI: 12.0.0-next.6
Node: 12.14.1
OS: win32 x64

Angular: 12.0.0-next.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0-next.6
@angular-devkit/build-angular   0.1200.0-next.6
@angular-devkit/core            12.0.0-next.6
@angular-devkit/schematics      12.0.0-next.6
@schematics/angular             12.0.0-next.6
@schematics/update              0.1200.0-next.6
ng-packagr                      11.2.4
rxjs                            6.6.6
typescript                      4.2.3<code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @glebmachine, 

Thanks for opening this issue. While the Angular CLI allows extending the Webpack configuration by doing so you are venturing on the unsupported path as Angular tooling team doesn't provide support for builds using custom Webpack configurations.

I suggest that you file an issue https://github.com/angular-architects/module-federation-plugin and raise an issue with the author of this package. My initial though here are that they need to provide a custom logging function that handles the information provided by Webpack when using Module Federation.

**Comment by glebmachine** [comment]
@alan-agius4 here is a [repro](https://github.com/glebmachine/module-federation-build-stuck/tree/repro-zero-sized) without manfred's plugin.
Unfortunately It is angular-cli bug

Please reopen

**Comment by BenRacicot** [comment]
I messaged you on Twitter @glebmachine. Perhaps you can open this issue in the CLI repo? I'd like to help you get this going. [@BenRacicot](https://twitter.com/BenRacicot)
