### ISSUE TITLE
ENOENT on ng serve

### ISSUE THREAD

**Issue by Enivile** [angular/angular-cli#20452]
I am using VS Code I encountered the same error once before searched for it but didn't find any solution so I uninstalled the VS code and reinstalled. Which got me rid of the error but I rebooted my pc and hv the same error again.

When I run 'ng serve' this error occurs.

---------------------------------------------------------------------------------------------------------------------------
An unhandled exception occurred: ENOENT: no such file or directory, lstat 'D:\NUML lectures\Final Year Project\FYP Project\Project\Eventier\https:'
See "C:\PROGRA~1\KMSpico\temp\ng-950dms\angular-errors.log" for further details.
---------------------------------------------------------------------------------------------------------------------------

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
