### ISSUE TITLE
No angular-cli-build.js file in angular-cli: 1.0.0-beta.11-webpack.8

### ISSUE THREAD

**Issue by FernandoSousaX** [angular/angular-cli#2045]
I am using Windows 8.1and i have installed angular-cli globally.

```
ng --version
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.3.1
os: win32 x64
```

I am not sure if this is an angular-cli or personal issue but i cant find the angular-cli-build.js file like in old versions and because of that i am not being able to build an app using material 2.

**Comment by aszechlicki** [comment]
this file was removed from when angular-cli migrated to webpack
[This](https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md) post explains how to migrate your project to webpack

**Comment by FernandoSousaX** [comment]
According with the next paragraph the file is no longer necessary so how could i bundle material 2 packages to the dist folder? 
```
Lastly, you can delete these files as they are not needed anymore.

./config/karma-test-shim.js
./config/environment.js
./src/system-config.ts
./angular-cli-build.js
./typings.json
./.clang-format (if present)
```

**Comment by aszechlicki** [comment]
it's explained in [README](https://github.com/angular/angular-cli#global-library-installation)

**Comment by mtzfactory** [comment]
Hi, the Readme neither the post mentioned above explain how to migrate third party libs, how can install the libs as the wiki says...

https://github.com/angular/angular-cli/wiki/3rd-party-libs

**Comment by aszechlicki** [comment]
It is in the README: https://github.com/angular/angular-cli#3rd-party-library-installation

**Comment by filipesilva** [comment]
Hi @mtzfactory, with `beta.14` we've updated our instructions, you can find them here: https://github.com/angular/angular-cli#webpack-update

You shouldn't need any special config to use material2 now.

**Comment by mtzfactory** [comment]
Thanks a lot!
