### ISSUE TITLE
Could I get the HASH string after build production bundles

### ISSUE THREAD

**Issue by suaha** [angular/angular-cli#20469]
I need these hash strings to generate the index.html in my java code.

Initial Chunk Files               | Names         |      Size
main.**70df7733771e68066b57**.js      | main          |   4.55 MB
styles.**41bc9911eb161ff94665**.css   | styles        |   1.04 MB
scripts.**ac85873ce067d825827c**.js   | scripts       | 583.31 kB
polyfills.**1491555983653285c3fa**.js | polyfills     |  36.06 kB
runtime.**132ac416050ca4a9fa28**.js   | runtime       |   2.33 kB

**Comment by alan-agius4** [comment]
The easiest approach would be to disable file hashing altogether using the `outputHash` option. Alternatively, you would need to build a script that parses the file names which you can then inject in your Java application.

Closing as this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
