### ISSUE TITLE
Getting error: You may need an additional loader

### ISSUE THREAD

**Issue by csname1910** [angular/angular-cli#20471]
I am getting the following error.

You can reproduce it with this minimal GitHub repository:

https://github.com/csname1910/errordemo

    Error: ./node_modules/pdfjs-dist/build/pdf.js 2413:45
    Module parse failed: Unexpected token (2413:45)
    File was processed with these loaders:
     * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
     * ./node_modules/@ngtools/webpack/src/ivy/index.js
    You may need an additional loader to handle the result of these loaders.
    |         intent: renderingIntent,
    |         renderInteractiveForms: renderInteractiveForms === true,
    >         annotationStorage: annotationStorage?.getAll() || null
    |       });
    |     }

**Comment by JoostK** [comment]
Heya, the optional chaining syntax is not supported by Webpack 4, see webpack/webpack#10227, and that is used in the Angular CLI. Support for Webpack 5 is currently experimental in Angular CLI 11.

**Comment by alan-agius4** [comment]
Indeed as @JoostK mentioned the optional chaining is not support by Webpack 4 which is used in the Angular CLI 11, to opt-in using experimental support for Webpack 5 which is not recommended to be used for production. See: https://github.com/angular/angular-cli/pull/18820.

In version 12, the Angular CLI will use Webpack 5 which does support the mentioned syntax see: https://github.com/angular/angular-cli/pull/20466
