### ISSUE TITLE
Differential loading puts ES2015 code into ES5 bundle

### ISSUE THREAD

**Issue by bogdan-panteleev** [angular/angular-cli#20486]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Seems yes. 
It was ok in version `0.802.2` of `@angular-devkit/build-angular` package, but in all further versions it is broken.

### Description

While using differential loading two bundles should be created. One of es2015 and one of es5 and they are created, but the code from 'esm2015' directory of npm packages is bundled into both es5 and es2015 bundles. And the code from 'esm5' directory is ignored. As a result we have es2015 code inside bundle meant to be used in IE..
When talking about directories I mean paths specified in `package.json` file in fields `module` - for es5 and `es2015` - for es2015.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

1. load the code from https://github.com/bogdan-panteleev/angular-issue-demo
2. run `npm ci`
3. run `ng build --prod` (actually, the flag is not important here)
4. open `main-es5.*.js` file inside `dist` folder.
5. search for `esm2015` substring. You will find a lot of libraries taken from `node_modules/*/_esm2015`.
But the file we are in now is es5. So we have es2015 code inside es5 bundle. **This is bug**

## 🔥 Exception or Error

You will find a lot of libraries taken from `node_modules/*/_esm2015`.
But the file we are in now is es5. So we have es2015 code inside es5 bundle. **This is bug**

</code></pre>

## 🌍 Your Environment

![image](https://user-images.githubusercontent.com/43281834/114192461-2b711300-9956-11eb-9529-356d1d955fb7.png)

**Comment by clydin** [comment]
The differential loading process works by performing a single full ES2015 build of the application and then transforming the bundled ES2015 application code into ES5 code bundles.  Angular libraries no longer ship ES5 specific code.  Webpack's generated code comments referencing `esm2015` entry points is the expected behavior with the aforementioned build process.

**Comment by bogdan-panteleev** [comment]
ok, thanks a lot

**Comment by bogdan-panteleev** [comment]
@clydin , is it documented anywhere?

**Comment by alan-agius4** [comment]
Differential loading docs:
https://angular.io/guide/deployment#differential-loading

Angular Package Format docs: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs

**Comment by alan-agius4** [comment]
Closing as per above.
