### ISSUE TITLE
Builded Project Not Working (webpack)

### ISSUE THREAD

**Issue by vapits** [angular/angular-cli#2050]
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.11-webpack.2
node: 6.4.0
os: linux x64
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng build`

5. Mention any other details that might be useful.
The app runs normally with `ng serve` but when I'm building it it's simply not working. Ignore the missing fonts errors in console and try to click anywhere on the left menu. All routes exists but it seems it's just a static html file nothing else.
Try it here: http://maestro.pixelnet.gr

Also in the `dist` folder there is only the `index.html` file and the 3 builded `js` files. Shouldn't be there also the templates/components etc??

**Comment by vapits** [comment]
@deebloo there was a nginx issue.
Though, if I use `ng build -prod` command instead of `ng build` after the uglify application is not working. It seems that all the Components from App Module are not loaded in the app.

**Comment by nyabwana** [comment]
has this been sorted?

**Comment by vapits** [comment]
No still.
Updated to webpack.8 and rc.7 and still the `-prod` project not working.

**Comment by filipesilva** [comment]
@vapits does `ng serve -prod` work?

**Comment by vapits** [comment]
@filipesilva 
> The option '--prob' is not registered with the serve command. Run `ng serve --help` for a list of supported options.

**Comment by JanStureNielsen** [comment]
@vapits -- it's `ng serve -prod`  with a "d" not "b" as in "production".

**Comment by vapits** [comment]
@JanStureNielsen lol :D

**Comment by vapits** [comment]
@filipesilva yes `ng serve --prod` works even that I get on terminal like a hundreds of warning and drops, but the build still (it builds everything but the result is not working in browser.

**Comment by JanStureNielsen** [comment]
@vapits -- do you see any console warnings or errors when you run with `ng serve`? Can you make your project available somewhere?

**Comment by vapits** [comment]
@JanStureNielsen on `ng serve` no, on `ng serve -prod` the same that I pasted above. Unfortunately I cannot make the project available :/

**Comment by SuryaSaraiya** [comment]
@vapits did you manage to fix this issue? or know of any workarounds (if there a way I can not uglify during ng build -prod)?

**Comment by vapits** [comment]
@SuryaSaraiya yes sorry forgot to close this. Actually last version fixed everything. Still don't know though what was the reason for this issue.
