### ISSUE TITLE
ESModule import is not tree-shaked

### ISSUE THREAD

**Issue by GeorgeTailor** [angular/angular-cli#20525]
# 🐞 bug report

### Affected Package
I'm not sure which exactly package is responsible for building the app. Probably, `@angular-devkit/build-angular`.

### Is this a regression?

No.

### Description

I have an external ESModule with named exports, now when I import only some of the named exports I expect webpack to tree-shake unused code in the final bundle. However, when I import only a couple of exports like this:
```
import { Input, Label } from  '../../node_modules/@zooplus/zoo-web-components/dist/esm/zoo-web-components.js';
```
All exports are being put into the final bundle instead of imported two classes.

## 🔬 Minimal Reproduction

https://github.com/GeorgeTailor/angular-webpack-esmodule-import

```
git clone https://github.com/GeorgeTailor/angular-webpack-esmodule-import.git
cd angular-webpack-esmodule-import
npm i
npm start
```

in the code inside the project I use the following to import only two components:
```
import { Input, Label } from  '../../node_modules/@zooplus/zoo-web-components/dist/esm/zoo-web-components.js';
new Input(); // constructor call so that it's not removed by webpack
new Label(); // constructor call so that it's not removed by webpack
```

## 🔥 Exception or Error

The whole bundle is imported, along with buttons, selects and other components.
I would expect webpack to import only `Input` and `Label` along with any chained dependencies, but not the whole bundle.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.2.8
Node: 14.15.1
OS: darwin x64

Angular: 11.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.8
@angular-devkit/build-angular   0.1102.8
@angular-devkit/core            11.2.8
@angular-devkit/schematics      11.2.8
@angular/cli                    11.2.8
@schematics/angular             11.2.8
@schematics/update              0.1102.8
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Comment by alan-agius4** [comment]
Treeshaking and dead code elimination is only enabled for production builds. The reason for this is because both optimization steps takes a considerable amount of time and resources which is undesired during a development build. 



```
ng serve --prod
ng build --prod
```

That being said the problem here is that some of the mentioned code in 


Nit: you don't need `../../node_modules/` in the import path.

**Comment by alan-agius4** [comment]
Treeshaking and dead code elimination is only enabled for production builds. The reason for this is because both optimization steps takes a considerable amount of time and resources which is undesired during a development build. 

```
ng serve --prod
ng build --prod
```

That being said the problem here is that some of the mentioned code in mentioned library cannot be removed when used.

Example
```ts
class Checkbox extends e {
    constructor() {
        super(), this.attachShadow(
            { mode: "open" }).innerHTML = '<style>.checkbox,svg{box-sizing:border-box}:host{display:flex;flex-direction:column;width:100%;font-size:14px;line-height:20px;position:relative;--border:0;--check-color:var(--primary-mid)}:host([disabled]){--check-color:#767676}:host([highlighted]){--border:1px solid var(--check-color)}:host([invalid]){--check-color:var(--warning-mid);--border:2px solid var(--warning-mid)}::slotted(input){width:100%;height:100%;top:0;left:0;position:absolute;display:flex;align-self:flex-start;-webkit-appearance:none;appearance:none;cursor:pointer;margin:0;border-radius:3px;border:var(--border)}svg{border:1px solid var(--check-color);fill:var(--check-color);border-radius:3px;pointer-events:none;min-width:24px;z-index:1;padding:1px}.indeterminate,svg path{display:none}:host([checked]) svg path{display:flex}:host([checked][indeterminate]) .indeterminate{display:flex}:host([checked][indeterminate]) .checked{display:none}:host(:focus-within) svg{border-width:2px}::slotted(input:focus){border-width:2px}:host([checked]) ::slotted(input){border-width:2px}:host([disabled]) svg{background:#f2f3f4}.checkbox{display:flex;width:100%;cursor:pointer;align-items:baseline;position:relative}:host([highlighted]) .checkbox{padding:11px 15px}::slotted(label){display:flex;align-self:center;cursor:pointer;margin-left:5px;z-index:1}::slotted(input:disabled),:host([disabled]) ::slotted(label){cursor:not-allowed}</style><div class="checkbox"><slot name="checkbox"></slot><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" class="checked"><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/></svg> <svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" class="indeterminate"><path d="M19 3H5a2 2 0 00-2 2v14c0 1.1.9 2 2 2h14a2 2 0 002-2V5a2 2 0 00-2-2zm-2 10H7v-2h10v2z"/></svg><slot name="label"></slot></div><zoo-info role="status"><slot name="info"></slot></zoo-info><zoo-info role="alert"><slot name="error"></slot></zoo-info>', this.observer = new MutationObserver((e => { for (let t of e) t.target.disabled ? this.setAttribute("disabled", "") : this.removeAttribute("disabled"), t.target.hasAttribute("indeterminate") ? this.setAttribute("indeterminate", "") : this.removeAttribute("indeterminate") })), this.shadowRoot.querySelector('slot[name="checkbox"]').addEventListener("slotchange", (e => { let t = [...e.target.assignedElements()].find((e => "INPUT" === e.tagName)); t && (t.addEventListener("change", (() => { t.checked ? this.setAttribute("checked", "") : this.removeAttribute("checked") })), this.registerElementForValidation(t), t.disabled && this.setAttribute("disabled", ""), t.checked && this.setAttribute("checked", ""), t.hasAttribute("indeterminate") && this.setAttribute("indeterminate", ""), this.observer.observe(t, { attributes: !0, attributeFilter: ["disabled", "indeterminate"] })) }))
    } disconnectedCallback() { this.observer.disconnect() }
}

window.customElements.define("zoo-checkbox", Checkbox);
export { Checkbox };
```

The expression statement `window.customElements.define("zoo-checkbox", Checkbox);` which in it's call expression is referencing `Checkbox` class declaration will cause the class to be marked as used and therefore will not be tree-shaken.



Nit: you don't need `../../node_modules/` in the import path.

**Comment by GeorgeTailor** [comment]
Hello @alan-agius4 , thanks for your reply,
but in this case the structure is a bit different.
The file that I'm importing (@zooplus/zoo-web-components/dist/esm/zoo-web-components.js) only holds reexports, for example:

```
export {InfoMessage} from "./zoo-modules/form-modules/info-module/info.js";
export {Label} from "./zoo-modules/form-modules/label-module/label.js";
export {Input} from "./zoo-modules/form-modules/input-module/input.js";
```

Since I only import the reexported components, why does webpack goes further into the package, discovers `window.customElements.define("zoo-checkbox", Checkbox);` and marks that piece of code as being used?

**Comment by clydin** [comment]
The referenced modules may contain module-level side effects that are required for the library to function.  As a result they cannot be safely removed without specifically defining the library (or aspects of the library) as side effect free.  However, in this case, the modules do actually have side effects.  For additional information, please see https://webpack.js.org/guides/tree-shaking/

**Comment by GeorgeTailor** [comment]
Hello @clydin 

From the documentation you've linked:
```
A "side effect" is defined as code that performs a special behavior when imported, other than exposing one or more exports. An example of this are polyfills, which affect the global scope and usually do not provide an export.
```
Since I have a module that only reexports some modules it can be marked as side effect free, because it does not perform any special behavior, other than exposing one or more exports.
These side effects (in this case affecting global scope) only happen in the next layer on exports, in the component itself. The top-level module does not have that.

**Comment by clydin** [comment]
That is with the assumption that the custom elements are not expected to be automatically registered by importing the library which may be unexpected for users of the library.

**Comment by GeorgeTailor** [comment]
Yes, that's true, because of that the library has named exports to separate each component.
If I would like to import the whole library I would write:
```
import '@zooplus/zoo-web-components/dist/esm/zoo-web-components.js' // I guess this is specific to typescript
``` 
or
```
import * as zooComponents from '@zooplus/zoo-web-components/dist/esm/zoo-web-components.js'
```

but when I want only a subset of components I would write:
```
import { Input, Label } from  '@zooplus/zoo-web-components/dist/esm/zoo-web-components.js';
```

does that make sense?

**Comment by clydin** [comment]
If `@zooplus/zoo-web-components/dist/esm/zoo-web-components.js` is marked as side effect free, Webpack should remove  it in the first (assuming `@zooplus/zoo-web-components` maps to that file) and second cases (assuming `zooComponents`  is otherwise unused).
Another option is to use secondary entry points for each of the components.  The components would then be individually imported if needed and the main entry point would be available to register all the components.
With the complexity of tree-shaking, tests with these different scenarios would probably be the best option for finding the optimal configuration.

**Comment by clydin** [comment]
Closing as this is not really a defect or feature request for the Angular CLI.
Webpack's issue tracker may be a more effective location if there are further questions or concerns.
