### ISSUE TITLE
[Feat] Add error message when build fails to resolve global styles/scripts paths

### ISSUE THREAD

**Issue by aszechlicki** [angular/angular-cli#2052]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   Windows 10
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli: 1.0.0-beta.11-webpack.8
   node: 6.5.0
   os: win32 x64
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   updated from 1.0.0-beta.11-webpack.2
4. The log given by the failure. Normally this include a stack trace and some
   more information.
5. Mention any other details that might be useful.

Currently there is no feedback when build fails to resolve files included in apps[0].scripts and styles, which makes it difficult to troubleshoot, see #2035 

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by catull** [comment]
@aszechlicki Is this still a problem for you ?  Did you resolve the issue in the meantime ?

**Comment by filipesilva** [comment]
Closing as abandoned.
