### ISSUE TITLE
"Unhandled Promise rejection: SyntaxError: Unexpected token import"

### ISSUE THREAD

**Issue by javascriptonian** [angular/angular-cli#2053]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   os: win10 x64
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli: 1.0.0-beta.10
   node: 6.5.0
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   initi project using angular-cli and follow instructions on 3rd library installation instructions given on the angular-cli github page to set up material 2 components, and trying using any of the material 2 directives in a component. In my case:

```
import { Component } from '@angular/core';
import { MdButton } from '@angular2-material/button';

@Component({
  moduleId: module.id,
  selector: 'app-navbar',
  templateUrl: 'navbar.component.html',
  styleUrls: ['navbar.component.css'],
  directives: [MdButton]
})
export class NavbarComponent {
  navItems : Array<string> = [
    'About',
    'Services',
    'Policies',
    'Fees',
    'Contact'
  ]
}
```
1. The log given by the failure. Normally this include a stack trace and some
   more information.

```
zone.js:461 Unhandled Promise rejection: SyntaxError: Unexpected token import
        at Object.eval (http://localhost:3000/app/navbar/navbar.component.js:12:16)
        at eval (http://localhost:3000/app/navbar/navbar.component.js:37:4)
        at eval (http://localhost:3000/app/navbar/navbar.component.js:38:3)
    Evaluating http://localhost:3000/vendor/@angular2-material/button/button.js
    Evaluating http://localhost:3000/app/navbar/navbar.component.js
    Evaluating http://localhost:3000/app/app.component.js
    Evaluating http://localhost:3000/app/index.js
    Evaluating http://localhost:3000/main.js
    Error loading http://localhost:3000/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: SyntaxError: Unexpected token import(…)consoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Error: SyntaxError: Unexpected token import(…)
```

**Comment by pablocid** [comment]
I have the same issue !

**Comment by filipesilva** [comment]
Can you upgrade to beta.15 using https://github.com/angular/angular-cli#webpack-update and tell me if you still have these problems?

**Comment by filipesilva** [comment]
Closing as inactive.

**Comment by Dawitsharecare** [comment]
I have the same problem too.
