### ISSUE TITLE
Produce update/migration report after job is done

### ISSUE THREAD

**Issue by duluca** [angular/angular-cli#20546]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
For new and/or inexperienced developers or developers who accidentally close the terminal after an upgrade, it's easy to miss or lose the console output of the update/migration process. For better DX and make sure developers don't lose any guidance provided by the migration process or remain aware/communicate what changed and new things to watch out for, it'd be great to produce a report after the job is done.

### Describe the solution you'd like
Write console output from the migration/update process to an `html` file and open the file in default system browser after the job is done.

This greatly increases visibility of all the work that the migration/update process did for us. This also prevents accidental loss of the information provided in console. Optionally the file can be checked in to repo by team members, so other team members are aware or can reference specific items, suggestions, recommendations that the migration process creates.

This creates future opportunities to provide links to docs for specific migration/update items.

A flag to disable this behavior can be introduced for experts.

### Describe alternatives you've considered
The simplest solution would be to replicate console output in a `txt` file.

**Comment by clydin** [comment]
The `--create-commits`/`-C` option will generate individual commits for each update step that will also include the migration descriptions shown on the console.  This can be used to create a permanent record of the update process.  It also offers the opportunity to more selectively adjust and/or revert individual migrations.

In addition, a report is currently being considered as one of the changes that will be introduced in upcoming update improvements.
