### ISSUE TITLE
Change default behavior of `ng update` to update common and core for better DX

### ISSUE THREAD

**Issue by duluca** [angular/angular-cli#20545]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
For new or developers inexperienced with CLI commands knowing what to do with the `ng update` command is confusing. It is not apparent that `cli` and `core` packages should be updated first, and often updated at the same time.

There's also a wasted opportunity to encourage developers to update their other packages after `ng update @angular/core @angular/cli` is executed. 

### Describe the solution you'd like
If the default behavior of `ng update` is changed, so that it goes ahead and updates `cli` and `core`, I think it'll result in better DX for new and inexperienced developers.

Along with this change, if after running any update command the list of available updates are printed, it will inform developers there are more packages to update and if  `cli` and `core` packages are already up-to-date the current behavior will be preserved without introducing special cases.  

Case 1. CLI and/or Core is out of date
  - Update CLI and Core
  - Print list of other available updates, if any

Case 2. CLI and Core is up-to-date
  - Print list of other available updates, if any

### Describe alternatives you've considered
Currently developers are expected read the docs or blog posts. I think the process should be made as foolproof as possible to encourage updates.

Alternatives:
- On `build` or `serve` the tool can complain that `cli` and `core` packages are out-of-date.
- Provide more guidance in the built in `help` command, rather than sending users to docs.

**Comment by alan-agius4** [comment]
Running `ng update` without any argument will list the commands that need to be execute to update the packages.

**Comment by duluca** [comment]
> Running `ng update` without any argument will list the commands that need to be executed to update the packages.

I'm asking so that it first updates `core` and `cli` before it prints out the list of packages that can be updated. I think this would be a huge help to new/inexperienced developers.

And then when they do run the command, at the end of it, print the list of packages that can be updated to provide next steps.

But yes, I do agree `ng update` is pretty good as is. Just highlighting a potential way where we can improve the DX to be more action oriented or leads to more action. i.e. After printing the list of available packages, offer a Yes/No question if they want to update the next package in the correct order (cli, core, cdk, material, etc).

**Comment by alan-agius4** [comment]
Thanks for your  feedback!

> I'm asking so that it first updates core and cli before it prints out the list of packages that can be updated. I think this would be a huge help to new/inexperienced developers.

`ng update` shouldn’t force updating any Angular framework or CLI packages.

> After printing the list of available packages, offer a Yes/No question if they want to update the next package in the correct order (cli, core, cdk, material, etc).

Typically we don’t recommend updating unnecessary  packages at once, Updating a single package at once is the recommended approach. This because if you have a runtime or build error it might be harder to track down. This also helps keeping your git commit history cleaner in case you need to revert a change or find why a dependency was update etc...

**Comment by alan-agius4** [comment]
Closing as per above discussion.
