### ISSUE TITLE
Template errors not shown after rebuild

### ISSUE THREAD

**Issue by eachirei** [angular/angular-cli#20558]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/cli (maybe?)

### Is this a regression?

 Not sure.

### Description

 While serving an angular project, on the first build template errors are shown. Subsequent builds after changing files don't show all the errors anymore, only errors for the modified files.

## 🔬 Minimal Reproduction

 Enable strictTemplates and aot.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

➜ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.6
Node: 14.16.0
OS: darwin x64

Angular: 11.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.6
@angular-devkit/build-angular      0.1102.6
@angular-devkit/core               11.2.6
@angular-devkit/schematics         11.2.6
@angular/cdk                       11.2.6
@angular/cli                       11.2.6
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.6
@angular/material-moment-adapter   11.2.6
@schematics/angular                11.2.6
@schematics/update                 0.1102.6
rxjs                               6.6.3
typescript                         4.0.7

</code></pre>

**Comment by eachirei** [comment]
Will this be fixed in 11 or should we wait for the 12 release?

**Comment by clydin** [comment]
This should be addressed in the next 11.2.x patch release.
