### ISSUE TITLE
High cpu load on ng serve: webpack 2.1.0-beta.21

### ISSUE THREAD

**Issue by rvaliev** [angular/angular-cli#2055]
Just installed angular-cli webpack 2.1.0-beta.21 on my mac and started a new clean test project. 
After 'ng serve' got message  "webpack: bundle is now VALID." but got a high (80-110%) cpu load. 

OS: Mac OS X, El Capitan
Versions:
* angular-cli: 1.0.0-beta.11-webpack.8
* node: 6.2.1
* os: darwin x64

**Comment by bobrosoft** [comment]
Possibly related to #1956, but for me it happens only on `ng test`. `ng serve` is ok for me, no high CPU load.

**Comment by rvaliev** [comment]
I don't know how, but 'npm install' resolved the problem

**Comment by davyzhang** [comment]
install fsevent can solve the cpu problem even till the version 1.7.1
