### ISSUE TITLE
Out of the Box Compatability with Web3 / Crypto, @angular-devkit

### ISSUE THREAD

**Issue by karthedew** [angular/angular-cli#20566]
This is a FEATURE REQUEST to implement the out of box capability to run an Angular application that utilizes web3 for creating decentralized applications. 

When the web3.js package is included and used within an Angular app, the Angular build produces the error:

```Module not found: Error: Can't resolve 'crypto' in ...```  which may also include ```Can't resolve 'stream' in ...```

The proposed solution is changing the **browser.js** file in *@angular-devkit/build-angular/src/webpack/configs/* on line 119 from ```node: false``` to ```node: { crypto: true, stream: true }```.

**Comment by alan-agius4** [comment]
Hi @karthedew,

`crypto` and `stream` are Node.JS build-in APIs, what's relevant here is that we are building an application to serve it in the browser were this APIs don't exist. In addition, `web3` is written in CommonJS which is a typically module format used for Node.JS applications, when used with Webpack this can cause several optimization bailouts which results in increase in bundle size.

The fact that Webpack allows polyfilling Node APIs is an implementation detail which may not be supported by a different bundler. In general I'd advice against using libraries which are designed to be used in a Node.JS environment the browser.
