### ISSUE TITLE
TerserPluginOptions incompatible with webpack 5

### ISSUE THREAD

**Issue by smasala** [angular/angular-cli#20571]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Build angular project with webpack 5: `ng build myProject --optimization=true`.

When using webpack 5 and the latest TerserPlugin, the options passed have changed and cause the Terser plugin validator to exit with an error.

The angular builder TerserOptions (`sourceMap` and `cache`):
https://github.com/angular/angular-cli/blob/076ab0f11fe63cdac4271733af03c7844860ebff/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L380

The TerserPlugin webpack 5 options no longer have `sourceMap` and `cache`

sourceMap removed:
https://github.com/webpack-contrib/terser-webpack-plugin/commit/393f249f341e66fd7acc06d558d58c3d2953e4c9#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L41

Cache removed:
https://github.com/webpack-contrib/terser-webpack-plugin/commit/ddff508ceeaf65e69cb43543aa640eb76a75394d#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556

If you hook into the plugin and remove the two keys from the options before it's validated, the app builds fine and is optimised accordingly.

## 🔬 Minimal Reproduction

Package.json:
```
"resolutions": {
    "**/@angular-devkit/build-angular/webpack": "^5.0.0",
    "**/@angular-devkit/build-angular/css-loader": "^5.0.0",
    "**/@angular-devkit/build-angular/dotenv-webpack": "^6.0.0",
    "**/@angular-devkit/build-angular/html-webpack-plugin": "^5.0.0",
    "**/@angular-devkit/build-angular/style-loader": "^2.0.0",
    "**/@angular-devkit/build-angular/terser-webpack-plugin": "^5.0.0",
    "**/@angular-devkit/build-angular/webpack-dev-middleware": "^4.1.0",
    "**/@angular-devkit/build-angular/webpack-virtual-modules": "^0.4.2",
    "@storybook/builder-webpack4/webpack": "4.44.2"
  },
```

## 🔥 Exception or Error
<pre><code>
Invalid options object. Terser Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'sourceMap'. These properties are valid:
   object { test?, include?, exclude?, terserOptions?, extractComments?, parallel?, minify? }
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.2.2
Node: 14.16.0
OS: darwin x64

Angular: 11.2.3
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cli                    11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.1.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @smasala,

This is expected behaviour since you are using the `yarn` `resolutions` to override Webpack plugins. We only support the set of plugins and exact version that are defined as dependencies in `@angular-devkit/build-angular`.

While `resolutions` is needed to opt-in experimental preview of Webpack 5, it shouldn't be used to override other dependencies.

**Comment by smasala** [comment]
@alan-agius4 understand. The reason I have to override terser is so that storybook e2e test applications that run against angular libraries still work. Storybook is just too unstable with webpack 5. So I have storybook running on webpack 4 and angular on webpack 5 🤕 

Do you have any ideas how I could manipulate the terser options the devkit sends so that the validator doesn't throw an error?

I use the `@angular-architects/module-federation` plugin so that I can enable MF in angular 11 but the webpack config it exposes is evaluated after terser is called by the devkit.

**Comment by alan-agius4** [comment]
> Do you have any ideas how I could manipulate the terser options the devkit sends so that the validator doesn't throw an error?

You can use a 3rd party Angular builder such as https://github.com/manfredsteyer/ngx-build-plus.

**Note**: by modifying the Webpack configuration you are leaving the happy path and venturing into unsupported territory.

**Comment by smasala** [comment]
Of course 🤦  I'm already using the plugin "indirectly" because of the Module Federation which allows the `extra` config, but I'm not using the `partial` webpack part.

I'll have to look if I can just remove those two keys from the options - this way it won't be breaking change as angular already builds entirely with webpack 5 dependencies. I'm already in unsupported territory... but fairly happy 😂

**Comment by smasala** [comment]
@alan-agius4 no, as I feared this is the plugin. `@angular-architects/module-federation` is dependent on https://github.com/manfredsteyer/ngx-build-plus (same author) and uses the `ngx-build-plus` mechanism which was the issue I mentioned above... that the extra config is evaluated after the angular cli calls the `TerserPlugin` 🤔

**Comment by smasala** [comment]
For the record: this can't work as the cli call the constructor directly: https://github.com/angular/angular-cli/blob/076ab0f11fe63cdac4271733af03c7844860ebff/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L389 whilst building the configuration.
