### ISSUE TITLE
ng new fails due to @babel/traverse

### ISSUE THREAD

**Issue by jtneal** [angular/angular-cli#20583]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, it worked yesterday with 11.2.9 but today it does not using the same version.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

```sh
docker run --rm -it node:lts bash
npm install -g @angular/cli
ng new test --strict --routing --style scss
```

## 🔥 Exception or Error
<pre><code>npm ERR! code ETARGET
npm ERR! notarget No matching version found for @babel/traverse@^7.13.17.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@babel/helpers'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-21T02_07_30_591Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.</code></pre>

The error would make you think maybe a version of this package was removed from the node repository. However, when I checked it still seems to be there, and if I try to install it alone, it works just fine:

```sh
npm install @babel/traverse@^7.13.17
```

> \+ @babel/traverse@7.13.17
> added 25 packages from 46 contributors and audited 25 packages in 2.078s
> found 0 vulnerabilities

## 🌍 Your Environment
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by jtneal** [comment]
I am having a hard time understanding why this is failing because the version does exist. I do see changes pushed to this project 3 hours ago, so I imagine those changes has to have something to do with this issue. I was wondering if maybe a version got removed from the NPM repo after it was already added but the version exists from 3 hours ago, maybe it's just a cache. I see the failure on my mac native node, as well as in Docker, but when I just ran `ng new` from my other machine (a Windows PC) it seems to have worked fine.

Changes for reference: https://github.com/babel/babel/commit/006e2c93936373935bf1602d6ae4006d290f2d7b

**Comment by jtneal** [comment]
Okay, this problem seems to have resolved itself when I test in Docker. It's still failing on my Mac, but because it's working in Windows and Docker, I can only assume at this point my machine has some invalid cached state that is causing the issue to persist longer than it should. I'd still wager something was truly wrong here, perhaps a package was removed from NPM and re-added, but at this point I think it will clear itself up, so I will close this to reduce the noise.

**Comment by jtneal** [comment]
For the record, without me making any changes on my machine, it now works on my Mac. *Something* definitely happened here that negatively impacted angular-cli, but it was fixed and seems to be clearing up with time.

**Comment by JoeKyy** [comment]
same bug here...
