### ISSUE TITLE
ng serve with NodeJS 16 gives DeprecationWarning

### ISSUE THREAD

**Issue by Waterstraal** [angular/angular-cli#20587]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, all worked fine on NodeJs 15

## 🔬 Minimal Reproduction

1. Upgrade NodeJs to 16
2. ng add NodeJs16App
3. ng serve

## 🔥 Exception or Error
<pre><code>
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
\ Generating browser application bundles (phase: building)...(node:1408) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolu
tion of the package at C:\Sandboxes\Experiments\NodeJs16App2\node_modules\postcss\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
√ Browser application bundle generation complete.

Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   2.69 MB
polyfills.js          | polyfills     | 475.01 kB
styles.css, styles.js | styles        | 347.06 kB
main.js               | main          |  57.37 kB
runtime.js            | runtime       |   6.15 kB

                      | Initial Total |   3.55 MB
</code></pre>

## 🌍 Your Environment
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.9
Node: 16.0.0
OS: win32 x64

Angular: 11.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.9
@angular-devkit/schematics      11.2.9
@angular/cli                    11.2.9
@schematics/angular             11.2.9
@schematics/update              0.1102.9
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. 

See: https://github.com/postcss/postcss/issues/1558
