### ISSUE TITLE
Angular CLI Error: The Schematic workflow failed. See above. NPM 7.9.0

### ISSUE THREAD

**Issue by edocbuhtig** [angular/angular-cli#20592]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new

### Is this a regression?

No

### Description

Try to create a new app with CLI command ```ng new <demoapp> ``` the process is paused in between with below error

## 🔬 Minimal Reproduction
Try to create a new app with CLI command ```ng new <demoapp> ``` the process is paused in between with below error

## 🔥 Exception or Error
<pre><code>
ng new client 
? Do you want to enforce stricter type checking and stricter bundle budgets in t
he workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict No
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/
documentation/syntax#scss                ]
CREATE client/README.md (1015 bytes)
CREATE client/.editorconfig (274 bytes)
CREATE client/.gitignore (631 bytes)
CREATE client/angular.json (3623 bytes)
CREATE client/package.json (1196 bytes)
CREATE client/tsconfig.json (538 bytes)
CREATE client/tslint.json (3185 bytes)
CREATE client/.browserslistrc (703 bytes)
CREATE client/karma.conf.js (1423 bytes)
CREATE client/tsconfig.app.json (287 bytes)
CREATE client/tsconfig.spec.json (333 bytes)
CREATE client/src/favicon.ico (948 bytes)
CREATE client/src/index.html (292 bytes)
CREATE client/src/main.ts (372 bytes)
CREATE client/src/polyfills.ts (2830 bytes)
CREATE client/src/styles.scss (80 bytes)
CREATE client/src/test.ts (753 bytes)
CREATE client/src/assets/.gitkeep (0 bytes)
CREATE client/src/environments/environment.prod.ts (51 bytes)
CREATE client/src/environments/environment.ts (662 bytes)
CREATE client/src/app/app-routing.module.ts (245 bytes)
CREATE client/src/app/app.module.ts (393 bytes)
CREATE client/src/app/app.component.scss (0 bytes)
CREATE client/src/app/app.component.html (24955 bytes)
CREATE client/src/app/app.component.spec.ts (1057 bytes)
CREATE client/src/app/app.component.ts (211 bytes)
CREATE client/e2e/protractor.conf.js (904 bytes)
CREATE client/e2e/tsconfig.json (274 bytes)
CREATE client/e2e/src/app.e2e-spec.ts (657 bytes)
CREATE client/e2e/src/app.po.ts (274 bytes)
⠸ Installing packages (npm)...npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
✖ Package install failed, see above.
The Schematic workflow failed. See above.
</code></pre>

## 🌍 Your Environment
<pre><code>
NPM: 7.9.0
Angular CLI: 11.2.8
Node: 14.16.1
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.8 (cli-only)
@angular-devkit/core         11.2.8 (cli-only)
@angular-devkit/schematics   11.2.8 (cli-only)
@schematics/angular          11.2.8 (cli-only)
@schematics/update           0.1102.8 (cli-only)

</code></pre>

**Comment by alan-agius4** [comment]
@edocbuhtig, can you try using the latest version of NPM please? I am unable to replicate the problem.

```
➜  cli-reproductions npm -v
7.10.0
➜  cli-reproductions ng new my-app
? Do you want to enforce stricter type checking and stricter bundle budgets in the workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict Yes
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
CREATE my-app/README.md (1014 bytes)
CREATE my-app/.editorconfig (274 bytes)
CREATE my-app/.gitignore (631 bytes)
CREATE my-app/angular.json (3705 bytes)
CREATE my-app/package.json (1205 bytes)
CREATE my-app/tsconfig.json (783 bytes)
CREATE my-app/tslint.json (3185 bytes)
CREATE my-app/.browserslistrc (703 bytes)
CREATE my-app/karma.conf.js (1423 bytes)
CREATE my-app/tsconfig.app.json (287 bytes)
CREATE my-app/tsconfig.spec.json (333 bytes)
CREATE my-app/src/favicon.ico (948 bytes)
CREATE my-app/src/index.html (291 bytes)
CREATE my-app/src/main.ts (372 bytes)
CREATE my-app/src/polyfills.ts (2830 bytes)
CREATE my-app/src/styles.scss (80 bytes)
CREATE my-app/src/test.ts (753 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (662 bytes)
CREATE my-app/src/app/app-routing.module.ts (245 bytes)
CREATE my-app/src/app/app.module.ts (393 bytes)
CREATE my-app/src/app/app.component.scss (0 bytes)
CREATE my-app/src/app/app.component.html (24955 bytes)
CREATE my-app/src/app/app.component.spec.ts (1057 bytes)
CREATE my-app/src/app/app.component.ts (211 bytes)
CREATE my-app/e2e/protractor.conf.js (904 bytes)
CREATE my-app/e2e/tsconfig.json (274 bytes)
CREATE my-app/e2e/src/app.e2e-spec.ts (657 bytes)
CREATE my-app/e2e/src/app.po.ts (274 bytes)
✔ Packages installed successfully.
    Successfully initialized git.
```

**Comment by edocbuhtig** [comment]
Yup its working as expected now, with latest NPM, Thanks @alan-agius4
