### ISSUE TITLE
Automatic documentation for component generation

### ISSUE THREAD

**Issue by mikgross** [angular/angular-cli#20610]
# 🚀 Feature request

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Upon creating components with `ng generate component_name`, ng creates a .ts, .css, .html, and .spec.ts.
As a user of `compodoc` to generate documentation and app description, I have read that `Compodoc search for a default xxx.component.md file inside the root folder of each component`.

### Describe the solution you'd like
It would be great if `ng generate component_name` maybe with a flag `--doc` would generate a .md file with basic information such as `component_name`, path from `app/`.

### Describe alternatives you've considered
N/A

**Comment by alan-agius4** [comment]
This looks like an excellent opportunity for the community to extend the Angular schematics to include additional functionality such as this one. 

That said, let's leave this issue open for a short while to see if there is enough interest to add this in the official Angular schematics.

**Comment by alan-agius4** [comment]
Thanks for this feature request. 

However, I am going to close this as is currently not in the Angular CLI roadmap. It is also trivial for the community to extend the default component schematic to include this feature. 
 
 Let's reconsider this in the future if there is a bigger demand for this feature.
