### ISSUE TITLE
"--open" flag is not working

### ISSUE THREAD

**Issue by Venom-dell** [angular/angular-cli#20626]
Whenever I use the "--open" flag it doesn't work I have to open the browser through the link.

Versions
Angular CLI: 11.2.10
Node: - 14.16.1
OS: win32 x64
Angular: 11.2.11
npm: 6.14.12

... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                                        Version
@angular-devkit/architect           0.1102.10
@angular-devkit/build-angular   0.1102.10
@angular-devkit/core                 11.2.10
@angular-devkit/schematics      11.2.10
@angular/cli                               11.2.10
@schematics/angular                 11.2.10
@schematics/update                  0.1102.10
rxjs                                              6.6.7
typescript                                    4.1.5

The code compiles successfully but it doesn't open in the browser.  It does not throw any error or exception.
At first it worked a couple of times but then stopped working.

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version‘?

**Comment by Rhydderchc** [comment]
The issue #12551 also has something of the same sort. You can check if you are in the same circumstance.

**Comment by alan-agius4** [comment]
@Venom-dell, 

Can you try using version 12 of the Angular CLI and see if the problem persists?

You can update using the below command
```
ng update @angular/cli --next
```

**Comment by Venom-dell** [comment]
@alan-agius4,
I update the Angular CLI, but still it's not working

**Comment by alan-agius4** [comment]
@Venom-dell, at this point I am pretty sure that this is not caused by the Angular CLI as we just invoke `open`. https://github.com/angular/angular-cli/blob/7521a8727c2586bafd2b0fd725545fb1458e30b4/packages/angular_devkit/build_angular/src/dev-server/index.ts#L363-L364
Kindly file an issue in https://github.com/sindresorhus/open
