### ISSUE TITLE
Skip ngcc when `npm install` is ran

### ISSUE THREAD

**Issue by tomardern** [angular/angular-cli#20648]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] doc
- [ ] help
- [ ] version
- [X] Other - `npm install`

### Description
When running `npm install` in a project, there are cases which we do not want the `ngcc` to execute. Eg running other commands in the same project on a CI.

### Describe the solution you'd like
Ideally to skip the ngcc compilation stage when `npm install`. Cypress has a similar feature which is set via an environment variable. https://docs.cypress.io/guides/getting-started/installing-cypress#Install-binary

My suggestion would be something like this

`NG_SKIP_GCC=true npm install`

Followed by a message eg:
`Skipping Angular Compiler (ngcc) as NG_SKIP_GCC is set to true`

### Describe alternatives you've considered
Skipping any npm scripts (via npm install --ignore-scripts), but this can only be done at a project level .

**Comment by clydin** [comment]
The Angular CLI currently does not add `ngcc` to a project's `postinstall` hook and it is typically not recommended. The Angular CLI will selectively execute ngcc with optimized options based on a project's configuration and dependencies at build time.

**Comment by tomardern** [comment]
@clydin Sorry, I've just noticed, that we actually had it in our own package.json file! 🤦
