### ISSUE TITLE
untraceable error message

### ISSUE THREAD

**Issue by daddyschmack** [angular/angular-cli#20652]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

not relevant

### Description

 A clear and concise description of the problem...
When running ng serve, the following error appears, and I have NO idea how to find it.. I think it's related css.

Every error should be traceable

## 🔥 Exception or Error
<pre><code>

Error: Unexpected '/'. Escaping Social characters with \ may help
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 12.0.0-rc.0
Node: 12.18.2
OS win32 x64

@angular-devkit/architect   0.1200.-rc.0
@angular-devkit/core         12.0.0-rc.0
@angular-devkit/build-angular    12.0.0-rc.0
@angular-devkit/schematics   12.0.0-rc.0
@schematics/angular           12.0.0-rc.0
rxjs        6.6.7
typescript      4.2.4
</code></pre>

**Anything else relevant?**

I  don't believe any of those items matter

**Comment by daddyschmack** [comment]
If it's helpful, the error does not occur in  the build process.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [postcss-selector-parser](https://www.npmjs.com/package/postcss-selector-parser) project or file an issue on their issue tracker.

**Comment by daddyschmack** [comment]
@alan-agius4 , sorry if this is a silly question, dos the parser run in the build process too?

**Comment by alan-agius4** [comment]
> @alan-agius4 , sorry if this is a silly question, dos the parser run in the build process too? Also, did you change the parser in ng 12? This error did not occur in ng 9, nor did it occur in build 8 of this ng-12. I mean, it just started flagging valid scss comments. (`//` marked as invalid)

That is not a silly question, the CSS processing pipeline is the same for build and serve. A lot has changed since version 9 both directly in the Angular CLI and indirectly via 3rd party dependencies. Without a reproduction, it's hard to tell what is happening.

**Comment by daddyschmack** [comment]
thank you .  
I am saying that the valid comments were not being flagged in build 8, and are not being flagged in rc1.. So the change had to be in way it's called, or a flag it's called with, right?

**Comment by daddyschmack** [comment]
@alan-agius4 , I'd like to reopen this ticket as I have more information.

I am  rerunning this entire upgrade process, and I'm getting this error in RC1 `ng serve`, on a file named: v3.5.scss:
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser

It is flagging valid comments: `\\`

This is not happening on ng build

**Comment by alan-agius4** [comment]
.Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by daddyschmack** [comment]
@alan-agius4 , 
yep, trying to trigger the error in a new repo.

**Comment by daddyschmack** [comment]
Please close this.. found a completely different approach
