### ISSUE TITLE
add : @angular/pwa error " No matching version found for @angular-devkit/core@11.2.11."

### ISSUE THREAD

**Issue by lionel-meunier** [angular/angular-cli#20658]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was 11.1

### Description

When add @angular/pwa i have this error message 
<pre><code>
× Package installation failed: npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/core@11.2.11.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular/pwa'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lmeunier\AppData\Roaming\npm-cache\_logs\2021-04-29T11_19_01_863Z-debug.log
Package install failed, see above.
</code></pre>

**Comment by clydin** [comment]
The package version is published and available via npm: https://www.npmjs.com/package/@angular-devkit/core/v/11.2.11
Please ensure that npm is configured appropriately locally and that any intermediate npm caches and/or proxies are up-to-date.

**Comment by alan-agius4** [comment]
Closing as per above.
