### ISSUE TITLE
angular-cli: 1.0.0-beta.11-webpack.8: Uncaught TypeError: Cannot read property 'Emulated' of undefined in `config.js:15`

### ISSUE THREAD

**Issue by richavyas** [angular/angular-cli#2065]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX (Yosemite)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.1.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   Router upgraded to rc.6
   Followed this doc https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md
   to upgrade my current project to use angular-cli@webpack to run the app.
   ng serve

4. The log given by the failure. Normally this include a stack trace and some more information.
   Version: webpack 2.1.0-beta.21
   webpack: bundle is now VALID.
   Browser @ http://localhost:4200/ shows `Uncaught TypeError: Cannot read property 'Emulated' of        
   undefined` in `config.js:15`

5. Mention any other details that might be useful.
    I did this upgrade last night so assuming it should pick the latest which was pushed to master 4 days back. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ShadowManu** [comment]
The fix was reported to be using webpack beta.22. Guess there's your answer.

**Comment by richavyas** [comment]
According to official doc, I run `npm install -g angular-cli@webpack` and it installs 
`"angular-cli": "^1.0.0-beta.11-webpack.8"`, doesn't matter what version of webpack it's using. Not sure if we should install a specific version of `webpack` first and then install `angular-cli`

**Comment by ShadowManu** [comment]
For now you must. The fix for it is only available on master (yet to be released on `npm`)

**Comment by richavyas** [comment]
So I tried this: 
- updated local `package.json`
- uninstalled Webpack
- reinstalled webpack `beta 22`
- updated complete `Node Modules`

But, when I run ng serve, it eventually shows Webpack version as `Version: webpack 2.1.0-beta.21`, doesn't matter my local package.json and even npm list include `"webpack": "2.1.0-beta.22"`. 

Absolutely clueless what to do.

**Comment by richavyas** [comment]
Finally got the `ng serve` working by doing this:

- go to node_modules/angular-cli
- npm install webpack@2.1.0-beta.22 --save 

this will update webpack installation in angular-cli and angular-cli will stop picking beta 21 internally.

**Comment by jtsom** [comment]
Why is it insisting on installing beta.21?? The package.json file in the angular-cli folder specifies beta.22? Why should I have to fix their code?
