### ISSUE TITLE
Cannot install cli as root user

### ISSUE THREAD

**Issue by yanngit** [angular/angular-cli#20668]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Probably ... I haven't seen this issue before.

### Description

Trying to install angular CLI as root user, using the command `npm install -g --unsafe-perm @angular/cli` is giving me a permission denied error ... 

## 🔬 Minimal Reproduction

- login as root
- run `npm install -g --unsafe-perm @angular/cli`

## 🔥 Exception or Error

<pre><code>
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 127
npm ERR! path /root/.nvm/versions/node/v15.14.0/lib/node_modules/@angular/cli
npm ERR! command failed
npm ERR! command sh -c node ./bin/postinstall/script.js
npm ERR! sh: 1: node: Permission denied

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-30T09_25_36_551Z-debug.log
</code></pre>

## 🌍 Your Environment

Ubuntu 20.04 with node 15.14.0 and npm 7.7.6

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
