### ISSUE TITLE
`--base-href your-url` does not change base tag in index.html

### ISSUE THREAD

**Issue by MW3000** [angular/angular-cli#2067]
When running `ng build` with `--base-href your-url` I was expecting the base tag in index.html in the dist folder modified accordingly. But it remains unchanged: `<base href="/">`.

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OS X El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 5.12.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I did not change anything after `ng new PROJECT_NAME` and just ran `ng build --bh /myURL/`

**Comment by dzonatan** [comment]
You need to have at least [1.0.0-beta.11-webpack.3](https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#100-beta11-webpack3-2016-08-29) version.

For me works as expected. Try to update your angular-cli version.

**Comment by MW3000** [comment]
OK. I tried the latest release, 1.0.0-beta.11-webpack.8, and it works as expected.
