### ISSUE TITLE
Angular Update fails: Package "@angular/common" has an incompatible peer dependency to "rxjs" (requires "^6.5.3", would install "7.0.0").

### ISSUE THREAD

**Issue by 9034725985** [angular/angular-cli#20672]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Yes, ng update fails. It should not fail.

### Description

 A clear and concise description of the problem...

I have a "canary" project that updates to the latest version of angular automatically. 
https://github.com/mycanary/mycanary/runs/2477376254?check_suite_focus=true

## 🔥 Exception or Error

<pre><code>

yarn run ng update @angular/core @angular/cli @angular/cdk @angular/material @angular/localize rxjs;
  shell: /usr/bin/bash -e {0}
yarn run v1.22.10
$ ng update @angular/core @angular/cli @angular/cdk @angular/material @angular/localize rxjs
Using package manager: 'yarn'
Collecting installed dependencies...
Found 35 dependencies.
Fetching dependency metadata from registry...
Package '@angular/core' is already up to date.
Package '@angular/cli' is already up to date.
Package '@angular/cdk' is already up to date.
Package '@angular/material' is already up to date.
Package '@angular/localize' is already up to date.
                  Package "@angular/common" has an incompatible peer dependency to "rxjs" (requires "^6.5.3", would install "7.0.0").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-C1kNhl/angular-errors.log" for further details.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
</code></pre>

## 🌍 Your Environment

Github Actions
<pre><code>

{
  "name": "mycanary",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.12",
    "@angular/cdk": "^11.2.11",
    "@angular/common": "~11.2.12",
    "@angular/compiler": "~11.2.12",
    "@angular/core": "~11.2.12",
    "@angular/forms": "~11.2.12",
    "@angular/localize": "^11.2.12",
    "@angular/material": "^11.2.11",
    "@angular/platform-browser": "~11.2.12",
    "@angular/platform-browser-dynamic": "~11.2.12",
    "@angular/router": "~11.2.12",
    "@angular/service-worker": "~11.2.12",
    "karma-firefox-launcher": "^1.3.0",
    "karma-spec-reporter": "^0.0.32",
    "rxjs": "~6.6.7",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.11",
    "@angular/cli": "~11.2.11",
    "@angular/compiler-cli": "~11.2.12",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.3",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
</code></pre>

**Anything else relevant?**

This is automated sandbox environment. 

<pre><code>
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update angular

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn run ng update;
    - run: yarn run ng update @angular/core @angular/cli @angular/cdk @angular/material @angular/localize rxjs;
    - run: git config user.name "Linus Torvalds";
      if: always()
    - run: git config user.email "torvalds@linux-foundation.org";
      if: always()
    - run: git add .;
      if: always()
    - run: git commit -m "update angular" -m "angular {cli, cdk, material, localize}, and rxjs";
      if: always()
    - run: git pull --rebase --strategy-option=theirs;
      if: always()
    - run: git push origin master;
      if: always()
</code></pre>

**Comment by alan-agius4** [comment]
Hi,

it looks like you are forcing update of rxjs via the below command 

```
yarn run ng update @angular/core @angular/cli @angular/cdk @angular/material @angular/localize rxjs
```

Can you see if it works if you remove rxjs from the above command?

**Comment by 9034725985** [comment]
Thank you for your reply. how do I stay up to date with the latest recommeded rxjs from the angular team? do I need to run `ng update` and if it shows rxjs only then I should run `ng update rxjs`? 

I think it would be nice if `ng update` knew what version of rxjs is supported and didn't show an error if that condition is satisfied. Is it possible?

**Comment by clydin** [comment]
Running `ng update @angular/cli @angular/core @angular/material` will update and install the recommended and compatible versions of the frameworks dependencies including all peer dependencies of those dependencies.
For additional information regarding the recommended update process, please see https://update.angular.io
