### ISSUE TITLE
[schematics-cli] support run command without relative path

### ISSUE THREAD

**Issue by ishowman** [angular/angular-cli#20679]
# 🚀 Feature request

I'm using `@angular-devkit/schematics-cli` to generate code of Vue, and want to publish as a package so that I can use it at any project. Here is the [code](https://github.com/ishowman/schematics) provide with `hello` command.
When I want to generate codes in other project, schematics command `schematics <relativePath>:hello` requires me  to tell schematics the relative path(such as `schematics ../src:hello`). My expectation is that if I install the lib  as a dependency，I can generate find where to find the `hello` .

### Description

 `@angular-devkit/schematics-cli`  be able to run command once the project have installed lib with collection, without specifying relative path.

### Describe the solution you'd like

 For example,the structure of a project like:
```
ProjectA
|-- node_modules
|    |-- schematics-lib-with-hello-collection
|-- src
|-- package.json
```
Once I've installed `@angular-devkit/schematics-cli` and  running `schematics hello` at the rootPath of ProjectA, it'll find the hello from the rootPath of ProjectA first.
For the rootPath of ProjectA do not have hello collection, it'll find it at `node_modules` next. For `schematics-lib-with-hello-collection` have provided `hello` collection, it'll generate code.

Be grateful for reading.

**Comment by alan-agius4** [comment]
Hi @ishowman, 

This is already supported. You need to provide the library module name as collection name. The collection name, is resolved using node module resolution.

Example: 
```
schematics schematics-lib-with-hello-collection:hello
```

**Comment by ishowman** [comment]
> Hi @ishowman,
> 
> This is already supported. You need to provide the library module name as collection name. The collection name, is resolved using node module resolution.
> 
> Example:
> 
> ```
> schematics schematics-lib-with-hello-collection:hello
> ```
Is the library module name the same as name field of `package.json`

**Comment by alan-agius4** [comment]
Yes it is.

**Comment by ishowman** [comment]
> Yes it is.

Thanks.Have a good day!
