### ISSUE TITLE
InlineCriticalCssProcessOptions expose pruneSource to optimizations config

### ISSUE THREAD

**Issue by elennaro** [angular/angular-cli#20701]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Recently the brilliant feature of inlineCritical CSS during Angular build was added. Thank you for this!

For now when enabling inlineCritical in angular.json `build.optimization.styles.inlineCritical` the `pruneSource` property of underlying [critters](https://www.npmjs.com/package/critters) critical css inlining solution is hardcoded to `false': https://github.com/angular/angular-cli/blob/a6761d31ed03ff3760f3f8f20fad174884518fe2/packages/angular_devkit/build_angular/src/utils/index-file/inline-critical-css.ts#L41

That leads to duplication of inlined classes in generated CSS files.

### Describe the solution you'd like

Could it be possible to expose the `pruneSource` property to optimizations config of angular.json somehow, or add another possibility to change this value for the build?

**Comment by alan-agius4** [comment]
Hi @elennaro, 

Thanks for this feature request. 

There hasn't been much activity from the community on this request and hence it will currently not in scope of the Angular CLI. 

Pruning inlined CSS here, will have little to no performance improvement, but it will complicate the the build quite a bit when taking into consideration SRI's.

Let's revisit this in the future, if we see more interest from the community. 

Thanks again.
