### ISSUE TITLE
Custom decorator ignored in AoT prod

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#20702]
Consider the folllowing code:

Module A:

```typescript
const REGISTRY: { [name: string]: any } = {};

export function MyComp (name: string) {
  return function (compType: any) {
    REGISTRY[name] = compType;
  }
}

export function regLog() { return Object.keys(REGISTRY).length }
```
Module B:

```typescript
@MyComp('myComp')
@Component({template: '!'})
export class MyComp implements OnInit {
  ngOnInit() { 
    console.log(regLog());
  }
}
```

Building with angular.json aot: false works, while building with AoT does not. Setting the buildOptimizer to false, works for declarations in module A but ignore module B.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by zehavibarak** [comment]
> Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
> 
> If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

This issue was reported before, yet no one on Angular side managed to resolve it. Custom decorators are stripped in AoT. This is a setback.
