### ISSUE TITLE
Override port when running "ng test"

### ISSUE THREAD

**Issue by TheBird956** [angular/angular-cli#20715]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

It is currently impossible to easily specify a port when running `ng test`.
Even with the current ability of `ng test` to automatically increment the port number when a port is already in use when you run multiple test process in Docker containers, there is no way to forward the port of the container and have it be consistent with the port shown in the console when starting the process.

### Describe the solution you'd like

Make it possible to override the port being used by `ng test` with a parameter similar to `--port 9877`.

### Describe alternatives you've considered

Another way to address this would be to add the ability to edit the text shown when the command starts. However, this is far from ideal.

**Comment by alan-agius4** [comment]
Hi, 

Can you please elaborate and explain how the port used is not being disabled in the console?
```
```

**Comment by TheBird956** [comment]
The port being used is correctly displayed in the console. The problem is with how we run tests.

We run each of our commands in separate docker containers and we run two separate tests suites. One for integrated tests and another one for unit tests. We need a different port for each of those test commands.

Those two suites of tests are started using the same `karma.conf.js` but with different `tsconfig.json` files (so we can select different files) and are both running at the same time in different Docker containers. With this setup, both test suites use the same port since we cannot specify the port when launching the command.

I tried using the environment variable but it does not change the port displayed in the console:

```
$ npm run test-unit-dev-watcher
> web-application@0.0.0 test-unit-dev-watcher /home/jstebenne/Projects/web-application
> KARMA_PORT=9998 ng test --configuration=test-unit-dev --watch

10% building 2/2 modules 0 active10 05 2021 16:50:06.570:WARN [karma]: No captured browser, open http://localhost:9876/
10 05 2021 16:50:06.586:INFO [karma-server]: Karma v4.4.1 server started at http://0.0.0.0:9876/
10 05 2021 16:50:06.586:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
10 05 2021 16:50:06.601:INFO [launcher]: Starting browser ChromeHeadless

Finished in NaN secs / NaN secs @ 16:50:08 GMT+0000 (Coordinated Universal Time)
```
This example is with the variable set in `package.json` before running ng (I don't know if its supposed to work), but I also tried with setting the `--env` argument when launching the container and I have the same result.

**Comment by alan-agius4** [comment]
I realised that you are using an old Karma version (4.4.1) which is likely the root cause of the problem.

See below;
```
ng test
WARN [karma]: No captured browser, open http://localhost:9876/
10 05 2021 21:34:26.197:INFO [karma-server]: Karma v6.1.2 server started at http://localhost:9876/
```

Port in use
```
ng test
WARN [karma]: No captured browser, open http://localhost:9877/
10 05 2021 21:36:35.432:WARN:INFO [karma-server]: Karma v6.1.2 server started at http://localhost:9877/
```


Please update to a more recent Karma version, if the problem persists please file a new issue with a minimal reproduction. Thanks.
