### ISSUE TITLE
ng build ignores locale.baseHref

### ISSUE THREAD

**Issue by e-oz** [angular/angular-cli#20712]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Looks so

### Description

With this config:
```json
      "i18n": {
        "sourceLocale": {
          "code": "en-US",
          "baseHref": ""
        },
        "locales": {
          "de": {
            "baseHref": "",
            "translation": "projects/project_name/src/i18n/messages.de.xlf"
          }
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "configurations": {
            "production": {
              "localize": ["de"],
```

`ng build` ignores "baseHref" of the locale and always adds "de".
If configurations.production.localize set to "true", then it will add "de" for some files an "en-US" for others.

Would be awesome if empty baseHref had effect, described here: https://stackoverflow.com/a/61384524/680786 (not adding any prefix)

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.0-rc.2
Package Manager: npm 7.11.2

Angular: 12.0.0-rc.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0-rc.2
@angular-devkit/build-angular   12.0.0-rc.2
@angular-devkit/core            12.0.0-rc.2
@angular-devkit/schematics      12.0.0-rc.2
@schematics/angular             12.0.0-rc.2
ng-packagr                      12.0.0-rc.1
rxjs                            7.0.0
typescript                      4.2.4
</code></pre>

Reproduced on Linux and Windows.

**Comment by clydin** [comment]
I am unable to replicate this using `12.0.0-rc.2` with the above configuration.
The output index HTML for the `de` locale appears to contain the correct base HREF (in both cases `de`/`true`):
```
<!DOCTYPE html><html lang="de"><head>
  <meta charset="utf-8">
  <title>LocalizeBasehref</title>
  <base href="/">
```
The `en-US` output as well appears correct:
```
<!DOCTYPE html><html lang="en-US"><head>
  <meta charset="utf-8">
  <title>LocalizeBasehref</title>
  <base href="/">
```

**Comment by e-oz** [comment]
I was talking about the path inside the 'dist' folder.
Looks like I had wrong expectations :) Sorry.
Thanks for help.

**Comment by clydin** [comment]
No problem at all.
The CLI will generate a directory per defined locale.  Once built, the output can then be staged, deployed, and/or served as needed based on any project specific requirements.

**Comment by e-oz** [comment]
But wait. If baseHref is "/", then path in the "dist" folder should not contain "de".
So it's a bug.

**Comment by clydin** [comment]
A change to the base HREF is generally due to specific requirements for the project's staging, deployment or server configuration.  The built output of the CLI is orthogonal to how a client will eventually access the files.

**Comment by clydin** [comment]
As an example, if a host name approach was used for serving the localized applications (e.g., `en.example.com`/ `de.example.com`), then the base HREF as configured above would be the correct configuration.

**Comment by e-oz** [comment]
I hope nobody uses this ugly approach. Otherwise, people from Germany would share links to their french friends and they would not understand a word. But it's just a rhetoric question ;)
