### ISSUE TITLE
Angular CLI Use ngModule Configuration when I use ng new ProjectName ?

### ISSUE THREAD

**Issue by suresh191** [angular/angular-cli#2071]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
@suresh191 what version of the CLI are you using? be sure to answer the questions given in the issue template so all the information is provided. the latest version of the webpack build uses NgModule

**Comment by suresh191** [comment]
Thanks Deebloo for your reply. This is the version information I have in my local.
angular-cli: 1.0.0-beta.10
node: 6.4.0
os: win32 x64

I have created a new project with this version of CLI but I am not finding ngModule.

**Comment by aspeight** [comment]
I'm having the same problem.
$ ng --version
angular-cli: 1.0.0-beta.10
node: 4.5.0
os: win32 x64

**Comment by deebloo** [comment]
The latest webpack release is the only one that is being updated and will eventually be the default version. Try npm install -g angular-cli@webpack

**Comment by suresh191** [comment]
I just uninstalled existing version, clear cache and re-installed cli@webpack. I now see ngModule configurations in the project. Thank you very much.

**Comment by deebloo** [comment]
Glad you got it worked out!

**Comment by SparK-Cruz** [comment]
I've tried it.
First had to install webpack globally, then hit this issue: #1930
workaround fixed, even though issue is for windows os and I'm on a ubuntu based distro.

Not so smooth transition to webpack :P

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli#webpack-update contains up to date instructions on how to update beta.14 projects now.
