### ISSUE TITLE
webpack-dev-server creates unnecessary file watchers

### ISSUE THREAD

**Issue by blidblid** [angular/angular-cli#20711]
# 🐞 Bug report

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

The webpack-dev-server sets up a lot of unnecessary watchers that have no impact on the emitted code.

I'm not sure if this should be an improvement in webpack or more configuration in Angular CLI. The number of unnecessary watchers can be greatly reduced by configuring `devServer.watcherOptions.ignore`. 

## 🔬 Minimal Reproduction

> ng new project

Add logging to `createFsWatchInstance` in chokidar: 

```
function createFsWatchInstance(path, options, listener, errHandler, emitRaw) {
  // ...
  try {
    console.log(path);
    return fs.watch(path, options, handleEvent);
  }
// ...
}
```
> ng s

## 🔥 Exception or Error

Chokidar, through webpack, sets up lots of unnecessary watchers on things like:

* Unused code
* LICENSE-files
* Markdown
* /dist
* /.git
* etc

In large projects, this will cause chokidar to throw an exception:

> System limit for number of file watchers reached.

## 🌍 Your Environment

<pre><code>
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.12
Node: 14.16.0
OS: win32 x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.12
@angular-devkit/build-angular   0.1102.12
@angular-devkit/core            11.2.12
@angular-devkit/schematics      11.2.12
@angular/cli                    11.2.12
@schematics/angular             11.2.12
@schematics/update              0.1102.12
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Anything else relevant?**
**This does not happen on Mac.**

**Comment by clydin** [comment]
If possible, could you try updating to version 12?  Version 12 uses Webpack 5 which has a completely rewritten file watching subsystem.

**Comment by blidblid** [comment]
@clydin I cannot repro on Angular 12.

**Comment by alan-agius4** [comment]
@blidblid in that case I am closing the issue as it's no longer a problem in version 12.
