### ISSUE TITLE
Expose Webpack Configuration

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular-cli#20731]
# 🚀 Feature request

### Description

In order to integrate Angular with some external tooling like [Cypress Component Testing](https://docs.cypress.io/guides/component-testing/introduction), it is necessary to provide a webpack (or any other building tool) configuration. 
While `AngularCompilerPlugin` is a really good start, it doesn't cover the whole magic happening under the hood of `@angular-devkit/build-angular`. This needs us to create a custom webpack config using the `AngularCompilerPlugin`.

### Describe the solution you'd like

Even though Webpack is kind of an Angular implementation detail, it would be a dream come true to expose a function like `ɵresolveWebpackConfig({target: 'my-app'})` that could be inspired from:
https://github.com/angular/angular-cli/blob/f6135a20d1f3fd8afe85ba10906afb1fb7e91dea/packages/angular_devkit/build_angular/src/dev-server/index.ts#L99-L104

I understand that this would considerably extend the public API's surface and that is why I am totally alright if we could start some experiments with a non-public function (hence the `ɵ`).
https://github.com/jscutlery/test-utils/blob/ec422695e9de3ecfa560143098bda6198756e860/packages/cypress-mount-integration/src/plugins/index.js#L6-L40

### Describe alternatives you've considered

Creating a public library exposing a webpack config that mimics `@angular-devkit/build-angular` behavior.

If you are OK with the idea, I'd be happy to help.

**Comment by yjaaidi** [comment]
Cc. @kyliau

**Comment by alan-agius4** [comment]
Hi @yjaaidi, 

Any reason why not use the architect API to build the application?, Example: https://github.com/angular/angular-cli/blob/b34ed5c4007f9ef08b370219081b4d23f9f24fb8/packages/angular_devkit/build_angular/src/protractor/index.ts#L107-L108

I think realistically exposing the entire Webpack configuration will not be ideal. Here are some reasons.

- The structure of the Webpack configuration changes quite a bit sometimes even in patches. 
- The Webpack configuration is very dynamic and is generated based on a large set of options.
- I think having it as a public API, will be a limiting factor on the CLI as we couldn't easily amend it without causes breakages downstream.

**Comment by yjaaidi** [comment]
Hey @alan-agius4, thanks for this ⚡️ lightning-fast feedback ⚡️.

The main reason for this situation is that the way cypress component testing works is using all spec files as entry points that it lazy loads one by one depending on the tests you want to run.

Here is the `startDevServer` function that overrides the given webpack config: 
https://github.com/cypress-io/cypress/blob/56234e52d6d1cbd292acdfd5f5d547f0c4706b51/npm/webpack-dev-server/src/startServer.ts#L17-L25

I can only see 3 options:
1. exposing the webpack config
2. custom webpack config (as mentioned before)
3. passing lots of new options to the target (e.g. entry points)

Am I missing any better option?

Concerning the first option, I don't think that the function has to be part of the public API. It should be used with the following condition: **the webpack configuration returned by the function will only be compatible with the exact same version defined here https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/package.json**

The main purpose of this function is to provide an easy way of hacking the configuration for extreme use cases like this one.

In general, I'd rather use a "use at yɵur ɵwn risk" piece of API than mimic the webpack config as it seems to be the only option.

**Comment by leonelvsc** [comment]
We also have the need of using a custom webpack config because of deprecated polyfills on webpack 5, searching on github we come across this library that it's currently working on adding support for ag12 https://github.com/just-jeb/angular-builders#readme , it allows to pass custom configuration to the angular webpack config.

Current problem

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

```

simple solution at the moment none

**Comment by clydin** [comment]
These Node.js shims can be provided via TypeScript path mappings if needed in a project.
Please note, however, that libraries should ideally be providing web compatible variants of their libraries that use native browser APIs where possible.

Example path mapping configuration within the applications TypeScript configuration file: 
```
    "paths": {
      "crypto": ["./node_modules/crypto-browserify"],
      "stream": ["./node_modules/stream-browserify"]
    }
```
The `crypto-browserify` and `stream-browserify` packages will also need to be installed within the project.

**Comment by lmiller1990** [comment]
Hi, I work on component testing at Cypress. Happy to answer any questions or do any work that might help move this forward.

Ideally we want to use the exact same configuration used for development (via `ng serve`, for example) when testing component in Cypress. Most of our other integrations do something similar - we grab the webpack config for Next.js, CRA, etc. 

Much like Angular, Next.js's webpack config is dynamic and changes a lot, and not officially "public" (eg, it's not documented) so it's "use at your own risk". I think something similar might work for Angular.

**Comment by leonelvsc** [comment]
> These Node.js shims can be provided via TypeScript path mappings if needed in a project.
> Please note, however, that libraries should ideally be providing web compatible variants of their libraries that use native browser APIs where possible.
> 
> Example path mapping configuration within the application's TypeScript configuration file:
> 
> ```
>     "paths": {
>       "crypto": ["./node_modules/crypto-browserify"],
>       "stream": ["./node_modules/stream-browserify"]
>     }
> ```
> 
> The `crypto-browserify` and `stream-browserify` packages will need to be installed within the project.
> 
> This issue is also asking for the output of the Webpack configuration generation to be provided so that it can be used independently. Not to be able to modify the existing configuration in-place which is what would be needed based on the Webpack error shown above for the Node.js shim.



> These Node.js shims can be provided via TypeScript path mappings if needed in a project.
> Please note, however, that libraries should ideally be providing web compatible variants of their libraries that use native browser APIs where possible.
> 
> Example path mapping configuration within the application's TypeScript configuration file:
> 
> ```
>     "paths": {
>       "crypto": ["./node_modules/crypto-browserify"],
>       "stream": ["./node_modules/stream-browserify"]
>     }
> ```
> 
> The `crypto-browserify` and `stream-browserify` packages will need to be installed within the project.
> 
> This issue is also asking for the output of the Webpack configuration generation to be provided so that it can be used independently. Not to be able to modify the existing configuration in-place which is what would be needed based on the Webpack error shown above for the Node.js shim.


@clydin  I didn't knew of the existanse of the "paths" property in tsconfig, thank you so much, but it didn't resolve the issue because the problems is within the library `libsodium`

```
./node_modules/libsodium/dist/modules/libsodium.js:1:4669-4686 - Warning: Module not found: Error: Can't resolve 'crypto' in '/project/node_modules/libsodium/dist/modules'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }

```

**Comment by ocombe** [comment]
> Ideally I'd like to test my Angular components with Cypress using the exact same configuration used by Angular CLI (via `ng serve`, for example). We do something similar for our other integrations - we grab the webpack config for Next.js, CRA, etc.

I work on the Angular integration for bit.dev and we need the same thing, being able to programmatically run the angular dev server (which means that we can't really use the CLI and builders).
If there is no other alternative I will try to recreate the angular webpack config, we can probably make that in a public repository so that it helps other people as well. Any help would be appreciated because it's probably going to be a lot of maintenance.

**Comment by yjaaidi** [comment]
For those who are interested, we (@jscutlery) managed to hack our way like this:
https://github.com/jscutlery/test-utils/blob/main/packages/cypress-angular-dev-server/src/lib/create-angular-webpack-config.ts#L13-L69

We could expose this function through a library if lots of people show interest.

It's not perfect but IMHO, it's way better than writing and maintaining an Angular webpack config from scratch.

As mentioned here https://github.com/jscutlery/test-utils/issues/51, we are planning to add a `target` option which defaults to the default project's `build` in order to grab settings from `angular.json` or Nx `workspace.json` (e.g. styles, polyfills, etc...).

cc. @ocombe @edbzn

**Comment by lmiller1990** [comment]
Nice job! This seems like a good enough work around for now - definitely better than maintaining a separately and fairly complex webpack config. 

I think a lot of people would appreciate a little helper library they can use for this! Just need to make sure there is a disclaimer that this uses undocumented internals, etc.

**Comment by alan-agius4** [comment]
Hi all, 

Thanks for all your input. We have discussed this issue in depth during yesterday team meeting and we feel that exposing the Webpack configuration is something that we don't want and want to keep this as private as possible.

There are a number of reasons why we think that exposing the webpack config is not a good idea, below are some of these;
- We don’t provide semver guarantees and this config might break/change in any version include patches.
- We don't guarantee that we stay on Webpack forever. The fact that we use Webpack is an implementation detail.
- Replacing Webpack should cause little no friction to ECO system and using Angular CLI directly or indirectly.
- To generate a Webpack configuration, a large set of options needs to be providing including the builder context.
- Webpack specific features are not supported.

Therefore we feel that;
- if you or your tool uses Webpack directly, the best course of action is to create your own configuration and tailor it to your needs.
- Implement logic similar to `ng e2e` for Cypress https://github.com/cypress-io/cypress/tree/master/npm/cypress-schematic and using the Architect API spin up the dev-server.
