### ISSUE TITLE
Support for Webpack5 ?

### ISSUE THREAD

**Issue by sangaiah** [angular/angular-cli#20739]
Dear Angular Team Members,

Need your suggestion on below requirement:

We have identified one of a feature "Module Federation Plugin" which is part of WebPack 5 will solve our problems. Though there is an opt-in option to use Webpack 5,we are little skeptical to use since Angular is not yet supported. Is there any reason why it is not supported? It would be helpful for us if you provide any information regarding this matter.

Thanks

**Comment by alan-agius4** [comment]
Angular CLI version 12 which will be released tomorrow only supports Webpack 5. That being said Module Federation is not supported.

Please follow  https://github.com/angular/angular-cli/issues/17556 for microfrontend support.
