### ISSUE TITLE
Allow devs to run tests for just modified files

### ISSUE THREAD

**Issue by Jhonatangiraldo** [angular/angular-cli#20741]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...
In order to keep high quality in the software we are developing, we run unit tests when we are about to push changes to a pull request or merge request. Waiting for 1k tests to run might be a waste of time.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
I am looking out for something similar to what jest does with react, it allows devs to run tests related to just modified files. The flags I'm looking for are: **--onlyChanged**, **--findRelatedTests**, and **--changedSince**

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?
I've been thinking in using git and bash to realize what the tests should the cli run, all those that are directly or indirectly related to the modified files

**Comment by alan-agius4** [comment]
Thanks for this feature request, however adding this feature to the Karms builder is currently not in scope.
