### ISSUE TITLE
Angluar CLI  installation on Visual Studio Code require Admin Rights

### ISSUE THREAD

**Issue by Tapan1684** [angular/angular-cli#20743]
Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

We are using AngularCLI on MS Visual Studio Code for devops but as per our security policy users should not have Admin rights on the VDI/workstation. Without admin rights users are not able to install the extension of angluarCLI.  Would like to know how we can allow AngularCLI without Admin rights to Users to use it.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
