### ISSUE TITLE
Error in new project

### ISSUE THREAD

**Issue by developerctba** [angular/angular-cli#20745]
**I have the following problem when creating a new project**
![image](https://user-images.githubusercontent.com/35763536/118004275-b19ac380-b31f-11eb-9ebe-a894d51af5e1.png)

**My config**
![image](https://user-images.githubusercontent.com/35763536/118004313-ba8b9500-b31f-11eb-9dfb-c81d8952e7ac.png)

Am I doing something wrong?
Versions <= 10 working perfectly.

I already deleted the node_modules folder and then npm install and it didn't work for me.
I also tried ng serve --prod, but to no avail.

**Comment by alan-agius4** [comment]
Can you run `ng v` instead the `web‘ directory?

**Comment by developerctba** [comment]
Hey @alan-agius4 
For some reason, the angular path did not exist in the windows environment variables. I added it manually and it went back to work.
![image](https://user-images.githubusercontent.com/35763536/118021194-58d42680-b331-11eb-8264-2efc7d1f8c7b.png)
