### ISSUE TITLE
npm install EBADENGINE warnings

### ISSUE THREAD

**Issue by willydee** [angular/angular-cli#20757]
# 🐞 Bug report

### ✍️ Description

Upon installation, warnings are issued about node version.

## 🔬 Minimal Reproduction
```
$ sudo npm install -g @angular/cli
```

## 🔥 Exception or Error

<pre><code>
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular/cli@12.0.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || ^14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.12.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/architect@0.1200.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || ^14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.12.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/core@12.0.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || ^14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.12.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@angular-devkit/schematics@12.0.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || ^14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.12.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@schematics/angular@12.0.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12.14.1 || ^14.0.0',
npm WARN EBADENGINE     npm: '^6.11.0 || ^7.5.6',
npm WARN EBADENGINE     yarn: '>= 1.13.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v16.1.0', npm: '7.12.1' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
</code></pre>

## 🌍 Your Environment

<pre><code>
$ archey3
               +                OS: Arch Linux x86_64
               #                Hostname: htpc
              ###               Kernel Release: 5.12.1-arch1-1
             #####              Uptime: 2 days, 13:47
             ######             WM: None
            ; #####;            DE: GNOME
           +##.#####            Packages: 1145
          +##########           RAM: 4573 MB / 16017 MB
         #############;         Processor Type: AMD Ryzen 5 1600 Six-Core Processor
        ###############+        $EDITOR: /usr/bin/vim
       #######   #######        Root: 270G / 440G (61%) (ext4)
     .######;     ;###;`".      
    .#######;     ;#####.       
    #########.   .########`     
   ######'           '######    
  ;####                 ####;   
  ##'                     '##   
 #'                         `#  

$ node --version
v16.1.0

$ npm --version
7.12.1
</code></pre>

**Comment by willydee** [comment]
Related issues: #19957 #20590

**Comment by clydin** [comment]
Node.js v16 is not yet officially supported with Angular.  Only stable Node.js releases are considered officially support. As per Node.js version guidelines, only LTS releases of Node.js are considered production-ready.  For additional information, please see https://nodejs.org/en/about/releases/ and https://angular.io/guide/setup-local#prerequisites

If it is preferred to use specific Node.js version regardless of its status, the `--ignore-engines` npm flag can be used.  However, this may result in unexpected behavior while using the Angular CLI.
