### ISSUE TITLE
ng generate to specific file path not working

### ISSUE THREAD

**Issue by adamstephensen** [angular/angular-cli#2076]
## OS?  

OSX El Capitan (10.11.13)

## Versions. 

angular-cli: 1.0.0-beta.11-webpack.8
node: 6.2.0
os: darwin x64

## Repro steps. 

Trying to run `ng g component mycomp\thiscomp` as per the [CLI Reference](https://cli.angular.io/reference.pdf) 

```
ng g component <path/to/component-name>  
```

I have tried several permutations, but the path gets ignored and the generated output gets put into the root of the project.

For example

```
ng g component mycomp\thiscomp
installing component
  create src/app/mycompthiscomp/mycompthiscomp.component.css
  create src/app/mycompthiscomp/mycompthiscomp.component.html
  create src/app/mycompthiscomp/mycompthiscomp.component.spec.ts
  create src/app/mycompthiscomp/mycompthiscomp.component.ts
```

Thanks for checking this out !

**Comment by adamstephensen** [comment]
my bad. 

The issue is that I was using the wrong slash.

This will work: 

```
ng g component mycomp/thiscomp
```

**Comment by Anitha-Hexaware** [comment]
how to generate only one component file in angular, only one file 
ex:  name-parent.component.ts

**Comment by Charius** [comment]
@Anitha-Hexaware use command flags like `--inline-template` `--inline-style` etc

[here is more info](https://github.com/angular/angular-cli/wiki/generate-component)
