### ISSUE TITLE
add lint option for new projects

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular-cli#20769]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

now be default Angular project ship without a linter, which means people will have missing IDE features that relay on linters and many developer might not even notice it and that will lead to worse code everywhere in long term

### Describe the solution you'd like

my solution is simply to ask when people are generating a new project if they want to add linter, just like you do with routing

### Describe alternatives you've considered

right not it seems you only offer `ng add @angular-eslint/schematics` as a suggestion when I use ng lint that's why i said to make it yes/no question
but if there are multiple options in the future you can make it like styles preprocessing (none, SCSS, LESS), you ask which linter do you want to use with options (none, @angular-eslint/schematics or x-linter)

**Comment by alan-agius4** [comment]
Hi @robertIsaac, 

Thanks for this feature request.

We did discuss this multiple times over the last months, and we decided that for the time being we should not add a prompt in `ng-new` to add a linter or E2E testing framework. The main reasons for this is that we want to keep the prompts to a minium and adding a linter/E2E framework is a matter of running one command.

Let's revisit this in the future.
