### ISSUE TITLE
Error: Cannot find module 'ajv/dist/compile/codegen

### ISSUE THREAD

**Issue by richie50** [angular/angular-cli#20770]
```ng build  -c production``` fails on  angularv12 on node version 16.1.0

```node:internal/modules/cjs/loader:944
  throw err;
  ^

Error: Cannot find module 'ajv/dist/compile/codegen'
Require stack:```
```code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/node_modules/ajv-formats/dist/limit.js',
    '/node_modules/ajv-formats/dist/index.js',
    '/node_modules/@angular-devkit/core/src/json/schema/registry.js',
    '/node_modules/@angular-devkit/core/src/json/schema/index.js',
    '/node_modules/@angular-devkit/core/src/json/index.js',
    '/node_modules/@angular-devkit/core/src/experimental/jobs/simple-registry.js',
    '/node_modules/@angular-devkit/core/src/experimental/jobs/index.js',
    '/node_modules/@angular-devkit/core/src/experimental.js',
    '/node_modules/@angular-devkit/core/src/index.js',
    '/node_modules/@angular/cli/utilities/config.js',
    '/node_modules/@angular/cli/lib/init.js',
    'node_modules/@angular/cli/bin/ng'
  ] ```

**Comment by alan-agius4** [comment]
@richie50, 

Can you please provide the output of `ng v` and `npm ls ajv`? 

Thanks.

**Comment by richie50** [comment]
@alan-agius4 
![image](https://user-images.githubusercontent.com/7333599/118161875-1a507180-b3ee-11eb-9b2b-2555a0b11cba.png)

![image](https://user-images.githubusercontent.com/7333599/118162008-41a73e80-b3ee-11eb-8c0e-b82863c8ab9c.png)

**Comment by alan-agius4** [comment]
Looks like you are using an incompatible version of `@angular-devkit/build-angular`.

Have you used `ng update` to update to Angular 12?

**Comment by richie50** [comment]
Yes @alan-agius4 

``` $ ng update
Using package manager: 'npm'
Collecting installed dependencies...
Found 64 dependencies.
    We analyzed your package.json and everything seems to be in order. Good work```

**Comment by alan-agius4** [comment]
Can you kindly share your `package.json`?

**Comment by richie50** [comment]
@alan-agius4 . Managed to fix it by reinstall node_modules with ``` npm install --save --legacy-peer-deps```
Thanks for the help. :)

**Comment by richie50** [comment]
@alan-agius4 FYI

![image](https://user-images.githubusercontent.com/7333599/118165265-1aeb0700-b3f2-11eb-8b4f-318e55bf7808.png)
