### ISSUE TITLE
Angular 8 production error: Unexpected end of input error

### ISSUE THREAD

**Issue by abbymrs** [angular/angular-cli#20779]
Our project use Angular 8, and it works perfect before, but the application crashed this week with the error "` Uncaught SyntaxError: Unexpected end of input  main-es2015.57d70ce7c62e56f343e2.js:1`" .

Command for build: ng build --prod --base-href=./

tsconfig.json, we use the default one which is generated by angular-cli.

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Comment by alan-agius4** [comment]
Hi @abbymrs,

Angular 8 is no longer under support. Please update to a more recent version of Angular.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

For more information about Support policy and schedule see https://angular.io/guide/releases#support-policy-and-schedule
