### ISSUE TITLE
build error: Error: webpack_1.util.cleverMerge is not a function

### ISSUE THREAD

**Issue by rajeev-john** [angular/angular-cli#20772]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ X] build
- [ X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No, the previous version in which this bug was not present was: 11.X.X

### Description

 A clear and concise description of the problem...

Migrated the existing Angular project on 11.X to 12.X using the the steps at https://update.angular.io/. After the successful completion of this task when using the commands ng build or ng serve the following error is shown in the console.

Error: webpack_1.util.cleverMerge is not a function

## 🔥 Exception or Error

<pre><code>

Error: webpack_1.util.cleverMerge is not a function
</code></pre>

## 🌍 Your Environment

<pre><code>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            11.2.12
@angular-devkit/schematics      11.2.12
@schematics/angular             11.2.12
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

package.json
{
  "name": "<Project Name>",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "nx": "nx",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "nx workspace-lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "12.0.0",
    "@angular/cdk": "12.0.0",
    "@angular/common": "12.0.0",
    "@angular/compiler": "12.0.0",
    "@angular/core": "12.0.0",
    "@angular/forms": "12.0.0",
    "@angular/material": "12.0.0",
    "@angular/platform-browser": "12.0.0",
    "@angular/platform-browser-dynamic": "12.0.0",
    "@angular/router": "12.0.0",
    "@fortawesome/angular-fontawesome": "^0.8.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.35",
    "@fortawesome/free-brands-svg-icons": "^5.15.3",
    "@fortawesome/free-regular-svg-icons": "^5.15.3",
    "@fortawesome/free-solid-svg-icons": "^5.15.3",
    "@ng-select/ng-select": "^6.1.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@nrwl/angular": "12.2.0",
    "@popperjs/core": "^2.9.2",
    "@swimlane/ngx-datatable": "^19.0.0",
    "@types/jquery": "^3.5.5",
    "bootstrap": "^4.6.0",
    "flag-icon-css": "^3.5.0",
    "jquery": "^3.6.0",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "ngx-bootstrap": "^6.2.0",
    "protobufjs": "~6.11.2",
    "rxjs": "~6.6.7",
    "simple-line-icons": "^2.5.5",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.0.0",
    "@angular-eslint/eslint-plugin": "~4.3.0",
    "@angular-eslint/eslint-plugin-template": "~4.3.0",
    "@angular-eslint/template-parser": "~4.3.0",
    "@angular/cli": "12.0.0",
    "@angular/compiler-cli": "12.0.0",
    "@angular/elements": "12.0.0",
    "@angular/language-service": "12.0.0",
    "@compodoc/compodoc": "^1.1.11",
    "@nrwl/cli": "12.2.0",
    "@nrwl/cypress": "12.2.0",
    "@nrwl/eslint-plugin-nx": "12.2.0",
    "@nrwl/jest": "12.2.0",
    "@nrwl/linter": "12.2.0",
    "@nrwl/storybook": "12.2.0",
    "@nrwl/tao": "12.2.0",
    "@nrwl/workspace": "12.2.0",
    "@storybook/addon-docs": "^6.2.9",
    "@storybook/addon-essentials": "^6.2.9",
    "@storybook/angular": "^6.2.9",
    "@twittwer/compodoc": "^1.5.1",
    "@types/jest": "26.0.23",
    "@types/node": "15.0.3",
    "@types/webpack": "4.41.28",
    "@typescript-eslint/eslint-plugin": "4.23.0",
    "@typescript-eslint/parser": "4.23.0",
    "@webcomponents/custom-elements": "^1.4.3",
    "codelyzer": "6.0.2",
    "cypress": "^7.3.0",
    "dotenv": "9.0.2",
    "eslint": "7.26.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-cypress": "^2.11.3",
    "jest": "26.6.3",
    "jest-preset-angular": "8.4.0",
    "prettier": "2.3.0",
    "ts-jest": "26.5.6",
    "ts-node": "~9.1.1",
    "tslint": "~6.1.3",
    "typescript": "4.2.4"
  }
}

**Comment by alan-agius4** [comment]
Can you please run `npm ls webpack` and `npm ls @ngtools/webpack`?

**Comment by rajeev-john** [comment]
npm ls webpack Output.

+-- @angular-devkit/build-angular@12.0.0
| `-- UNMET PEER DEPENDENCY webpack@5.36.2
+-- @storybook/addon-docs@6.2.9
| +-- @storybook/builder-webpack4@6.2.9
| | `-- webpack@4.44.2  deduped
| `-- @storybook/core@6.2.9
|   `-- @storybook/core-server@6.2.9
|     `-- webpack@4.44.2  deduped
+-- @storybook/angular@6.2.9
| +-- @storybook/core-common@6.2.9
| | `-- webpack@4.44.2  deduped
| `-- webpack@4.44.2
`-- @types/webpack@5.28.0
  `-- webpack@5.37.0

npm ERR! peer dep missing: webpack@^5.30.0, required by @angular-devkit/build-webpack@0.1200.0
npm ERR! peer dep missing: webpack@^5.30.0, required by @ngtools/webpack@12.0.0
npm ERR! peer dep missing: webpack@^5.1.0, required by copy-webpack-plugin@8.1.1
npm ERR! peer dep missing: webpack@^5.0.0, required by less-loader@8.1.1
npm ERR! peer dep missing: webpack@^5.0.0, required by source-map-loader@2.0.1
npm ERR! peer dep missing: webpack@^5.0.0, required by stylus-loader@5.0.0

npm ls @ngtools/webpack

`-- @angular-devkit/build-angular@12.0.0
  `-- @ngtools/webpack@12.0.0

Looks like the upgrade did not update the required web pack.

**Comment by clydin** [comment]
Webpack is a direct dependency of `@angular-devkit/build-angular@12.0.0` and does not get updated separately.
The problem appears to be the package manager which hoisted packages into incompatible locations when installing.
storybook also appears to be directly depending on Webpack 4.x which will most likely cause it to fail.

Can you try deleting the package lock file and the node modules directory and then reinstalling?

**Comment by rajeev-john** [comment]
Thank you all for the valuable suggestion.. I was able to over this issue after updating my web pack to the required version.
