### ISSUE TITLE
ng update in v12 causing the wrong imports in 'tests.ts' file

### ISSUE THREAD

**Issue by kuncevic** [angular/angular-cli#20782]
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] test

### Is this a regression?

no

### Description

I am running an `ng update` on my project. As a side effect I am getting imports changed in `test.ts`, which breaking `the npm run test` command

-import 'zone.js/dist/zone';
-import 'zone.js/dist/zone-testing';
+import 'zone.js';
+import 'zone.js/testing';

## 🔬 Minimal Reproduction

just run `ng update @angular/cli @angular/core` on existing project

## 🔥 Exception or Error
```
Error: Module not found: Error: Can't resolve 'zone.js/testing' in '/Volumes/Work/Work/Projects/rx-service/projects/rx-service/src'

Error: node_modules/zone.js/dist/zone.js.d.ts:600:21 - error TS2503: Cannot find namespace 'NodeJS'.

600 declare var global: NodeJS.Global;
```
## 🌍 Your Environment

```
Angular CLI: 12.0.0
Node: 12.18.4
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.0
... cli, common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

Other:
In order to fix the issue I had to rollback the imports in `test.ts` file

**Comment by alan-agius4** [comment]
Hi @kuncevic,

The migration seems to be doing the right job as it replaces the old imports with the new once which is also inline with the content of new projects https://github.com/angular/angular-cli/blob/1fdd0bdd92516932d6f8edba8534d40bae88768c/packages/schematics/angular/library/files/src/test.ts.template#L3-L4

Can you please share your `spec` tsconfig file?

**Comment by kuncevic** [comment]
Oh, yeah I should of shared the repo. Here is the one https://github.com/kuncevic/rx-service 
I hope you can all needed info there. That is the commit right before the update https://github.com/kuncevic/rx-service/commit/e91e6fa27c215a55cabb078b79696a9b606e5751

**Comment by kuncevic** [comment]
Just a side note, the zones version there is `0.10.3` but even if I update to the latest one which is `0.11.4` the new imports still won't work, still have to use the old way to import zones in `test.ts` otherwise getting error:

```
./projects/rx-service/src/test.ts:2:0-22 - Error: Module not found: Error: Can't resolve 'zone.js/zone' in '/Volumes/Work/Work/Projects/rx-service/projects/rx-service/src'

./projects/rx-service/src/test.ts:3:0-30 - Error: Module not found: Error: Can't resolve 'zone.js/zone-testing' in '/Volumes/Work/Work/Projects/rx-service/projects/rx-service/src'
```

**Comment by alan-agius4** [comment]
The problem appears that you don't have zone.js as a dependency.

**Comment by kuncevic** [comment]
That is the error I've got by doing it as per previous comment https://github.com/angular/angular-cli/issues/20782#issuecomment-841050760

Does it work on your machine? 🤔

**Comment by alan-agius4** [comment]
@kuncevic, it does. Did you add the missing dependency on `zone.js`?

```
➜  rx-service git:(master) ✗ ng t
⠙ Generating browser application bundles (phase: building)...14 05 2021 10:01:32.134:WARN [karma]: No captured browser, open http://localhost:9876/
14 05 2021 10:01:32.139:INFO [karma-server]: Karma v6.3.2 server started at http://localhost:9876/
14 05 2021 10:01:32.140:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
14 05 2021 10:01:32.143:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
14 05 2021 10:01:36.666:WARN [karma]: No captured browser, open http://localhost:9876/
14 05 2021 10:01:36.748:INFO [Chrome 90.0.4430.212 (Mac OS 10.15.7)]: Connected on socket HZ-_aRJOlgB50yk-AAAB with id 57467110
Chrome 90.0.4430.212 (Mac OS 10.15.7): Executed 10 of 10 SUCCESS (0.048 secs / 0.031 secs)
TOTAL: 10 SUCCESS
TOTAL: 10 SUCCESS
✔ Browser application bundle generation complete.
```

**Comment by kuncevic** [comment]
Yeah, I did and committed. If I am removing the `dist` from the paths it won't work for me

**Comment by alan-agius4** [comment]
@kuncevic, 

Can you try to run the below
```
rm -rf node_modules
yarn
```

**Comment by kuncevic** [comment]
yeah, I did that too many times. Now event trying another PC, same thing: `Module not found: Error: Can't resolve 'zone.js/zone'

**Comment by alan-agius4** [comment]
Based on the last errors, it seems that the imports are different from the imports done by the migration.

Note the imports should be 

```ts
import 'zone.js'; 
import 'zone.js/testing';
```

and not 
```ts
Import 'zone.js/zone'; 
import 'zone.js/zone-testing';
```
