### ISSUE TITLE
[Angular 12]: Cannot read property 'push' of undefined at self.webpackHotUpdate

### ISSUE THREAD

**Issue by MichalK6677** [angular/angular-cli#20793]
I still have this issue in Angular 12: https://github.com/angular/angular-cli/issues/20288
![image](https://user-images.githubusercontent.com/3100059/118275852-41c73d00-b4c7-11eb-9176-c660d627ae63.png)

`
jsonp chunk loading:85 Uncaught TypeError: Cannot read property 'push' of undefined
    at self.webpackHotUpdateartifex (jsonp chunk loading:85)
    at runtime.a68b6eb738297c2768b7.hot-update.js:1
`

`
jsonp chunk loading:81 Uncaught TypeError: Cannot set property '1458' of undefined
    at self.webpackHotUpdateartifex (jsonp chunk loading:81)
    at main.a68b6eb738297c2768b7.hot-update.js:1
`

Is the fix part of Angular 12?

**Comment by alan-agius4** [comment]
@MichalK6677, kindly follow the issue template when opening an issue.

They provide required information.
