### ISSUE TITLE
ng serve does not generate webpack bundle for debugging in the browser.

### ISSUE THREAD

**Issue by richie50** [angular/angular-cli#20797]
**Recently update my application to angular v12 and webpack folder is not generated in the browser**
![image](https://user-images.githubusercontent.com/7333599/118317834-8e5e4880-b4c6-11eb-9015-49fbee3d9afb.png)

**I have the same application running angular v11.0.0 and the webpack bundle can be seen.**

![image](https://user-images.githubusercontent.com/7333599/118317901-a8982680-b4c6-11eb-9b6c-4131f1ac8dc7.png)

It's this because of webpack 5 or a configuration issue? I use ```*.ts``` files generated by the webpack bundle for debugging purposes.

Any insights will be appreciated.

Note:# Same application different angular versions running in parallel

**Comment by clydin** [comment]
Unfortunately, I am unable to reproduce the issue with a newly created v12 project.
Can you provide the output of `ng version` as well as the build options used for the project shown above?

**Comment by alan-agius4** [comment]
From the screenshots it looks like the first one is for a production build which doesn’t contain sourcemaps.

Can you share the build section of your `angular.json`?

**Comment by richie50** [comment]
Build 
![image](https://user-images.githubusercontent.com/7333599/118369457-742d7480-b571-11eb-8595-8b9ae9a04463.png)

Serve
![image](https://user-images.githubusercontent.com/7333599/118369482-8c9d8f00-b571-11eb-9a24-2632fb6dccc5.png)

I also get this warning
![image](https://user-images.githubusercontent.com/7333599/118369513-a9d25d80-b571-11eb-8658-efb644aeb5b1.png)

ng version
![image](https://user-images.githubusercontent.com/7333599/118369557-d2f2ee00-b571-11eb-9299-6bd0533e5f0e.png)

**Comment by richie50** [comment]
> Unfortunately, I am unable to reproduce the issue with a newly created v12 project.
> Can you provide the output of `ng version` as well as the build options used for the project shown above?

@clydin this was an existing project on v11 migrated to v12

**Comment by clydin** [comment]
The goal of attempting to reproduce with a newly generated v12 project was to isolate whether this was a systemic issue with v12 or a project specific issue.  As this appears to be project specific, it may be caused by the build options for the project.
From the above options, it appears that source maps and other development mode options are not present.  Was `ng update` used to migrate the project to v12?
The following build options should be present after migrating (with `outputPath` differing based on the project):
```
          "options": {
            "outputPath": "dist/v12update-from11",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "vendorChunk": true,
            "extractLicenses": false,
            "buildOptimizer": false,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true
          },
```
The important aspect are these options:
```            "vendorChunk": true,
            "extractLicenses": false,
            "buildOptimizer": false,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true
```

**Comment by richie50** [comment]
@clydin yes the project was updated with ```ng udpate```. I tried the above config , still the same issue.

**Comment by alan-agius4** [comment]
@richie50, can you please re-share your configuration with the amended options? Kindly share this is text format and not screenshots.

**Comment by richie50** [comment]
[angular.txt](https://github.com/angular/angular-cli/files/6497684/angular.txt)

**Comment by richie50** [comment]
![image](https://user-images.githubusercontent.com/7333599/118668199-a681e080-b7c2-11eb-95ec-9101d57405a2.png)

@alan-agius4  this was another project from angular v11.2.4 to v12.0.0. Similar issue

Downgraded my node version.

![image](https://user-images.githubusercontent.com/7333599/118665062-ff9c4500-b7bf-11eb-87ce-588e8610737e.png)

**Comment by alan-agius4** [comment]
Hi @richie50, 

it appears that the project configuration was not migrated properly. Was `ng-update` invoked multiple times?

Kindly try using the below config
```js
{
  ...
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "outputPath": "dist/questionnaire-app",
      "index": "projects/questionnaire-app/src/index.html",
      "main": "projects/questionnaire-app/src/main.ts",
      "polyfills": "projects/questionnaire-app/src/polyfills.ts",
      "tsConfig": "projects/questionnaire-app/tsconfig.app.json",
      "optimization": false,
      "sourceMap": true,
      "namedChunks": true,
      "extractLicenses": false,
      "vendorChunk": false,
      "buildOptimizer": false,
      "assets": [
        "projects/questionnaire-app/src/favicon.ico",
        "projects/questionnaire-app/src/assets"
      ],
      "styles": [
        "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
        "projects/questionnaire-app/src/styles.scss"
      ],
      "scripts": []
    },
    "configurations": {
      "production": {
        "fileReplacements": [
          {
            "replace": "projects/questionnaire-app/src/environments/environment.ts",
            "with": "projects/questionnaire-app/src/environments/environment.prod.ts"
          }
        ],
        "outputHashing": "all",
        "optimization": true,
        "sourceMap": false,
        "namedChunks": false,
        "extractLicenses": true,
        "vendorChunk": false,
        "buildOptimizer": true,
        "budgets": [
          {
            "type": "initial",
            "maximumWarning": "5mb",
            "maximumError": "10mb"
          },
          {
            "type": "anyComponentStyle",
            "maximumWarning": "70kb",
            "maximumError": "100kb"
          }
        ]
      }
    }
  }
}

```

**Comment by richie50** [comment]
@alan-agius4  it works.  :)
![image](https://user-images.githubusercontent.com/7333599/118743264-0490e100-b820-11eb-9ef6-39a6b4750fd8.png)
 line 134 to 139 is never there for angular v11 and under. It's this something that should be documented for folks migrating from whatever version to v12. Seems to me its a v12 upgrade issue.

**Comment by alan-agius4** [comment]
> `line 134 to 139` is never there for angular v11 and under. It's this something that should be documented for folks migrating from whatever version to v12. Seems to me its a v12 upgrade issue where if this is missing it default to production build.

The configuration is amended as per above when using `ng update @angular/cli`. Did you run `ng update @angular/cli`?

**Comment by richie50** [comment]
@alan-agius4  Yeah i did use the ```ng update @angular/cli```.  We can close it this though. Can be a future reference for anyone with similar issue.

**Comment by JounQin** [comment]
@alan-agius4 It seems `webpack.mode` is set to be `production` in v12 even with `ng serve`.

I'm using `@angular-builders/custom-webpack@12.0.0-beta.0`, and confirm this behavior by debugging.

**Comment by alan-agius4** [comment]
If you are using third party builders, you need to either update your angular configuration and apply the breaking changes manually or run an update schematic provided by the mentioned builder.

**Comment by JounQin** [comment]
@alan-agius4 After debugging, it seems `optimization: false` is required now for running on `development` mode for `ng serve` now, may I ask is this expected? I didn't find any related documentation.

**Comment by alan-agius4** [comment]
Yeah it is expected see the changelog: https://github.com/angular/angular-cli/releases/tag/v12.0.0
