### ISSUE TITLE
ng build not working after v12 upgrade

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular-cli#20790]
# Bug Report

### Affected Package
@angular/cli

### Is this a regression?
yes

### Description
ng build fails with error below

## Minimal Reproduction

 https://stackblitz.com/...

## Exception or Error
```
c:\development\SDS\core-ui-v3>ng build
"BuildCustomWebpackBrowserSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
√ Browser application bundle generation complete.

Error: ./apps/enerest-v4/src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ multi ./apps/enerest-v4/src/main.ts main[0]

Error: ./apps/enerest-v4/src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ multi ./apps/enerest-v4/src/polyfills.ts polyfills[0]

Error: ./apps/enerest-v4/src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./apps/enerest-v4/src/main.ts

Error: ./apps/enerest-v4/src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
TypeError: angularCompiler.getNextProgram is not a function
    at c:\development\SDS\core-ui-v3\node_modules\@ngtools\webpack\src\ivy\plugin.js:390:61
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
 @ ./apps/enerest-v4/src/polyfills.ts

```

## Your Environment

**Angular Version:**
<pre><code>

c:\development\SDS\core-ui-v3>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            11.2.2
@angular-devkit/schematics      12.0.0
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             12.0.0
rxjs                            6.6.3
typescript                      4.2.4

</code></pre>

**Anything else relevant?**
upgrade was made successfully by nrwl NX migrate tool.

**Comment by JoostK** [comment]
As this is the same error as #20778 let's track it there.
