### ISSUE TITLE
Index html generation failed on ng build in Angular 12

### ISSUE THREAD

**Issue by anuj9196** [angular/angular-cli#20804]
# Bug Report

### Affected Package

Not sure which package is causing this error, here are the packages in use
```
{
  "name": "quiz-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.0.0",
    "@angular/cdk": "^12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "~12.0.0",
    "@angular/flex-layout": "^11.0.0-beta.33",
    "@angular/forms": "~12.0.0",
    "@angular/material": "^12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@types/prismjs": "^1.16.5",
    "express": "^4.17.1",
    "lodash": "^4.17.21",
    "moment": "^2.29.1",
    "ngx-cookie-service": "^11.0.2",
    "path": "^0.12.7",
    "perfect-scrollbar": "^1.5.1",
    "prismjs": "^1.23.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.0.0",
    "@angular/cli": "~12.0.0",
    "@angular/compiler-cli": "~12.0.0",
    "@types/jasmine": "~3.6.0",
    "@types/lodash": "^4.14.169",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "~4.2.3"
  },
  "engines": {
    "node": "14.17.0",
    "npm": "6.14.13"
  }
}
```

### Description
While running the build using `ng build` command, the build fails to generate the Index HTML file with the following error
![Screenshot 2021-05-15 at 12 46 41 PM](https://user-images.githubusercontent.com/6560085/118351801-9deb9900-b57b-11eb-8141-a33d7ed96ee2.png)

## Minimal Reproduction

Check the build log: https://github.com/anuj9196/quiz-app/runs/2589355739?check_suite_focus=true#step:7:56

To reproduce
* take a clone of the repository
* Install dependencies `npm install`
* Build the project `ng build`

## Exception or Error
<pre><code>
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✖ Index html generation failed.
undefined:4:720308: missing '}'
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**
Setting `"optimization": false` in the **build > options** builds the project file but the build budget size is 2 MB more.

```
"architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/quiz-app",
            "optimization": false,
            ...
         }
     }
}
```

**Comment by alan-agius4** [comment]
Likely related to #20760, will need to take a look later to confirm if it’s the same root cause with data URIs.

As a workaround you can disable critical CSS inlining https://angular.io/guide/workspace-config#optimization-configuration.

**Comment by inexuscore** [comment]
@alan-agius4 Thank you, resolved. I can't believe how many hours I've wasted on this LMAO! inline styles and data URIs in particular (base64 images, etc.) break Angular 12's production build, wow.

**Comment by alan-agius4** [comment]
@anuj9196,

It appears that in your case the problem is that the CSS optimizer is incorrectly optimising media queries which is causing the CSS parser to fail 

Opening `style.css` and navigating to the line and column indicated in the error message we find the below which is invalid CSS as the media query has no feature value instead of `@media all`.

```css
@media{.page-break-after,.page-break-before{display:none}}
```

See: https://github.com/cssnano/cssnano/issues/1105

**Comment by rolfback** [comment]
> @anuj9196,
> 
> It appears that in your case the problem is that the CSS optimizer is incorrectly optimising media queries which is causing the CSS parser to fail.
> 
> Opening `style.css` and navigating to the line and column indicated in the error message we find the below which is invalid CSS as the media query has no feature value instead of `@media all`.
> 
> ```css
> @media{.page-break-after,.page-break-before{display:none}}
> ```
> 
> Let's continue tracking this [cssnano/cssnano#1105](https://github.com/cssnano/cssnano/issues/1105)

I have had this problem as well and it made no difference if I set Optimization to false. It turned out as you mentioned that in the compiled .css I had a bad css row at the position the error was telling me: `list-style-image: url("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");` of which I just needed to remove the quotationmarks to have it working again. Thank you for the clue!

**Comment by benardbees** [comment]
"rxjs" caused me the same problem, upgrade to "rxjs": "7.1.0", and fix errors, worked for me

**Comment by tfrijsewijk** [comment]
I know the issue is closed, but I was unable to reproduce an error with cssnano.

I'm maintaining a component library which produces `dso.css`. Angular 12 is unable to bundle the CSS from `angular.json`. The problem was a `<style>` with `@keyframes` within an inline SVG for `background-image`.

My solution was to decoded`%7B` to `{` and `%7D` to `}` within the `<style>`. The build passes but reports a warning:

```
npm run build

> angular12-test@0.0.0 build
> ng build

√ Browser application bundle generation complete.
√ Copying assets complete.
- Generating index html...1 rules skipped due to selector errors:
  100%25 -> Unmatched selector: %25
√ Index html generation complete.

Initial Chunk Files               | Names         |      Size
main.041503e2fd30c014fe9e.js      | main          | 212.34 kB
styles.a6563f3b5786fb7a36de.css   | styles        | 193.30 kB
polyfills.a4477f231111cac02cf0.js | polyfills     |  35.95 kB
runtime.e3d82d92b74a9840998d.js   | runtime       |   1.01 kB

                                  | Initial Total | 442.61 kB

Build at: 2021-05-28T11:51:27.159Z - Hash: f75e1905401770074415 - Time: 15522ms
```

The application works fine except for the animation which is now broken in IE11.

For more information see https://github.com/dso-toolkit/dso-toolkit/issues/1152

**Comment by mtinnes** [comment]
disabling inlineCritical style optimization allows the build to succeed. The following config works for me however I'd like to now exactly why:

**Comment by inexuscore** [comment]
@mtinnes yup, that fixes the problem. I had the same issue when upgrading some projects from Angular 11 to 12. In my case, the problem was base64 images. disabling **inlineCritical** or replacing **data-uri** images with image files resolved the issue.

**Comment by slavede** [comment]
It works for me too (upgrade from ng11 to ng12). Can you explain in short what does this does in the end?

**Comment by aipirvu** [comment]
> "optimization": { "scripts": true, "fonts": { "inline": true }, "styles": { "minify": true, "inlineCritical": false } },

Worked for me. This seems to be the best compromise; not disabling the optimization for all of them.

> It works for me too (upgrade from ng11 to ng12). Can you explain in short what does this do in the end?

It only disables optimization for "inlineCritical", as per [angular documentation](https://angular.io/guide/workspace-config): _"Extract and inline critical CSS definitions to improve First Contentful Paint."_. [Here](https://web.dev/extract-critical-css/) is an article explaining this in more detail.

**Comment by restfulhead** [comment]
I got `undefined:3:xxx: @font-face missing '}'` after upgrading from 11 to 12. Setting `inlineCritical` to false as suggested above fixed it.

**Comment by Exop63** [comment]
Index html generation failed.
undefined:1:111091: property missing ':'

fix: inlineCritical :false

**Comment by zaerl** [comment]
My build failed with the same error. And it was because of https://github.com/cssnano/cssnano/issues/1105

The CSS:

```SCSS
@media all {
    .page-break-after,
    .page-break-before {
        display: none;
    }
}
```
The `all` is removed by cssnano.

**Comment by Schiepek** [comment]
I had the error:

`
Ã Index html generation failed.
undefined:268:50133: @media missing '}'
`


Disabling 'inlineCritial' optimization works, but it's not a good solution cause it increases initial page load time.

`"optimization": { "scripts": true, "fonts": { "inline": true }, "styles": { "minify": true, "inlineCritical": false } },`

After hours of searching, I found the line in my CSS which caused the trouble.

```
@media (min-width: 992px) {
  .nav-account .nav-account__item.has-children::after {
    content: "";
    display: inline-block;
    margin-left: 9px;
    width: 6px;
    height: 4px;
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 6 4'%3E%3Cpath transform='translate(-586.156 -1047.28)' fill='%23fff' d='M586.171,1048l0.708-.71,2.828,2.83-0.707.71Zm4.95-.71,0.707,0.71L589,1050.83l-0.707-.71Z'/%3E%3C/svg%3E");
    background-size: 6px 4px;
    background-repeat: no-repeat;
    background-position: center center;
    top: -2px;
    position: relative;
  }
}
```


I had to remove the line with the background image: (url..)  to make it work

**Comment by tfrijsewijk** [comment]
@Schiepek your problem looks a bit like [mine](https://github.com/angular/angular-cli/issues/20804#issuecomment-850364379): background-image with data url to an SVG, but without a `<style>` element inside the SVG..

**Comment by huan** [comment]
@tfrijsewijk @Schiepek Thanks for the tips, I run this issue today and your solution helps me fix the problem.

**Comment by danielehrhardt** [comment]
If i add the Adyen CSS File:
`@import "@adyen/adyen-web/dist/adyen.css";`
The Build does have this Issue.

**Comment by jewkesy** [comment]
Getting the same issue using ClarityUI

**Comment by maxima120** [comment]
I have same issue (with missing ':'). The switching inline critical off works. however I dont see why is it happening. I dont have @media all.. only reference to @media is:

```
@media (min-width: 768px) {
  html {
    font-size: 16.1px;
  }
}
```

it appears in 2 different css files and it hasnt been changed and worked in Angular 10 but not 12.

**Comment by DavidMarquezF** [comment]
Why is this issue closed? It doesn't appear to be fixed. 

For me it also happens with `@media all`, it removes the all. However, in the css nano issue https://github.com/cssnano/cssnano/issues/1105#issuecomment-869493549 is said that this is the expected behavior of the tools that angular uses. 

Apparently `@media` without anything behind defaults to `@media all`, thus it gets removed in order to save space.

**Comment by slavede** [comment]
I agree with @DavidMarquezF , at least leave it opened with the link to cssnano issue...

**Comment by maxima120** [comment]
this game can be played by two :) perhaps we should just open a new issue

**Comment by gaeldupont44** [comment]
Hello ! :)
Somebody could publish a npm version of the lib with the @alan-agius4 please ?

**Comment by BobNovas** [comment]
I got the following error on ng build, with Angular 12 and Clarity 5.4.1:
`>ng build
√ Browser application bundle generation complete.
√ Copying assets complete.
× Index html generation failed.
undefined:10:275198: property missing ':'`

I fixed this by removing the double quotes from 10 lines in a copy of clr-ui.css (and using the copy)

background-image: url("lots-o-characters")

to

background-image: url(lots-o-characters)


The double quotes appear to blow up the parser/optimizer or some part of the ng build, and removing the
double quotes fixes that problem and doesn't appear to cause any others.

**Comment by kkoo95** [comment]
@alan-agius4 thanks for the fix, but there is still the same issue with @page, as in:

> ✖ Index html generation failed.
> undefined:7:215671: @page missing '}'

I don't know if you'll be able to add another workaround for that or if i must use the `optimization` one:

> "optimization": { "scripts": true, "fonts": { "inline": true }, "styles": { "minify": true, "inlineCritical": false } },
