### ISSUE TITLE
Using Master insists on using Webpack beta 21

### ISSUE THREAD

**Issue by jtsom** [angular/angular-cli#2080]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.11-webpack.8                                                                                                          
node: 6.5.0                                                                                                                                   
os: win32 x64 
```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

git clone the angular-cli repo
npm link

use it in a project - npm new something --link-cli (or npm link angular-cli)
start the project with ng serve

Note using Beta 21 of webpack, even though the package.json in the angular-cli repo specifies beta.22

```
Hash: 96443330dda7707156d3                                                                                                                    
Version: webpack 2.1.0-beta.21                                                                                                                
Time: 18617ms                                                                                                                                 
            Asset       Size  Chunks             Chunk Names                                                                                  
   main.bundle.js    2.82 MB    0, 2  [emitted]  main                                                                                         
 styles.bundle.js    10.2 kB    1, 2  [emitted]  styles                                                                                       
        inline.js    5.53 kB       2  [emitted]  inline                                                                                       
         main.map    2.86 MB    0, 2  [emitted]  main                                                                                         
       styles.map    13.9 kB    1, 2  [emitted]  styles                                                                                       
       inline.map    5.59 kB       2  [emitted]  inline                                                                                       
       index.html  495 bytes          [emitted]                                                                                               
assets/.gitignore    0 bytes          [emitted]                                                                                               
Child html-webpack-plugin for "index.html":                                                                                                   
         Asset     Size  Chunks       Chunk Names                                                                                             
    index.html  2.85 kB       0                            
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
Try running `npm install` in the directory where you cloned the CLI itself.

To be completely safe, delete the `node_modules` folder in the cloned CLI and run `npm cache clear` before that.

**Comment by jtsom** [comment]
I think I just fixed - or should I say worked around this - by making sure I did a `npm link angular-cli` in the project, to make sure that the project is using the cloned master version of angular-cli (as trying to use the regular version is a mess...an updated release would be real nice)

**Comment by filipesilva** [comment]
>`beta.14` should have this issue fixed.
