### ISSUE TITLE
37 moderate severity vulnerabilities in v12

### ISSUE THREAD

**Issue by iamart** [angular/angular-cli#20803]
After updating to angular 12 there are 37 moderate severity vulnerabilities in the project.

#### Reproduction

Steps to reproduce:
1. (npx) ng new ang12
2. (npx) ng add @angular/material
3. npm audit
  
#### Environment

- Angular: 12
- CDK/Material: 12
- Browser(s): n/a
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

log of the audit:

> # npm audit report
> 
> postcss  7.0.0 - 8.2.9
> Severity: moderate
> Regular Expression Denial of Service - https://npmjs.com/advisories/1693
> fix available via `npm audit fix --force`
> Will install @angular-devkit/build-angular@0.1102.13, which is a breaking change
> node_modules/autoprefixer/node_modules/postcss
> node_modules/css-blank-pseudo/node_modules/postcss
> node_modules/css-has-pseudo/node_modules/postcss
> node_modules/css-prefers-color-scheme/node_modules/postcss
> node_modules/postcss-attribute-case-insensitive/node_modules/postcss
> node_modules/postcss-color-functional-notation/node_modules/postcss
> node_modules/postcss-color-gray/node_modules/postcss
> node_modules/postcss-color-hex-alpha/node_modules/postcss
> node_modules/postcss-color-mod-function/node_modules/postcss
> node_modules/postcss-color-rebeccapurple/node_modules/postcss
> node_modules/postcss-custom-media/node_modules/postcss
> node_modules/postcss-custom-properties/node_modules/postcss
> node_modules/postcss-custom-selectors/node_modules/postcss
> node_modules/postcss-dir-pseudo-class/node_modules/postcss
> node_modules/postcss-double-position-gradients/node_modules/postcss
> node_modules/postcss-env-function/node_modules/postcss
> node_modules/postcss-focus-visible/node_modules/postcss
> node_modules/postcss-focus-within/node_modules/postcss
> node_modules/postcss-font-variant/node_modules/postcss
> node_modules/postcss-gap-properties/node_modules/postcss
> node_modules/postcss-image-set-function/node_modules/postcss
> node_modules/postcss-initial/node_modules/postcss
> node_modules/postcss-lab-function/node_modules/postcss
> node_modules/postcss-logical/node_modules/postcss
> node_modules/postcss-media-minmax/node_modules/postcss
> node_modules/postcss-nesting/node_modules/postcss
> node_modules/postcss-overflow-shorthand/node_modules/postcss
> node_modules/postcss-page-break/node_modules/postcss
> node_modules/postcss-place/node_modules/postcss
> node_modules/postcss-preset-env/node_modules/postcss
> node_modules/postcss-pseudo-class-any-link/node_modules/postcss
> node_modules/postcss-replace-overflow-wrap/node_modules/postcss
> node_modules/postcss-selector-matches/node_modules/postcss
> node_modules/postcss-selector-not/node_modules/postcss
> node_modules/resolve-url-loader/node_modules/postcss
>   autoprefixer  9.0.0 - 9.8.6
>   Depends on vulnerable versions of postcss
>   node_modules/autoprefixer
>   css-blank-pseudo  *
>   Depends on vulnerable versions of postcss
>   node_modules/css-blank-pseudo
>     postcss-preset-env  >=6.0.0
>     Depends on vulnerable versions of css-blank-pseudo
>     Depends on vulnerable versions of css-prefers-color-scheme
>     Depends on vulnerable versions of postcss
>     Depends on vulnerable versions of postcss-color-gray
>     Depends on vulnerable versions of postcss-double-position-gradients
>     node_modules/postcss-preset-env
>       @angular-devkit/build-angular  >=0.1000.0-next.0
>       Depends on vulnerable versions of postcss-preset-env
>       Depends on vulnerable versions of resolve-url-loader
>       node_modules/@angular-devkit/build-angular
>   css-has-pseudo  *
>   Depends on vulnerable versions of postcss
>   node_modules/css-has-pseudo
>   css-prefers-color-scheme  *
>   Depends on vulnerable versions of postcss
>   node_modules/css-prefers-color-scheme
>   postcss-attribute-case-insensitive  4.0.0 - 4.0.2
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-attribute-case-insensitive
>   postcss-color-functional-notation  >=2.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-color-functional-notation
>   postcss-color-gray  >=5.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-color-gray
>   postcss-color-hex-alpha  4.0.0 - 6.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-color-hex-alpha
>   postcss-color-mod-function  >=3.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-color-mod-function
>   postcss-color-rebeccapurple  >=4.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-color-rebeccapurple
>   postcss-custom-media  7.0.0 - 7.0.8
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-custom-media
>   postcss-custom-properties  8.0.0 - 10.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-custom-properties
>   postcss-custom-selectors  5.0.0 - 5.1.2
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-custom-selectors
>   postcss-dir-pseudo-class  >=5.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-dir-pseudo-class
>   postcss-double-position-gradients  *
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-double-position-gradients
>   postcss-env-function  >=2.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-env-function
>   postcss-focus-visible  >=4.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-focus-visible
>   postcss-focus-within  >=3.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-focus-within
>   postcss-font-variant  4.0.0 - 4.0.1
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-font-variant
>   postcss-gap-properties  >=2.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-gap-properties
>   postcss-image-set-function  >=3.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-image-set-function
>   postcss-initial  3.0.0 - 3.0.4
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-initial
>   postcss-lab-function  >=2.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-lab-function
>   postcss-logical  >=2.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-logical
>   postcss-media-minmax  4.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-media-minmax
>   postcss-nesting  7.0.0 - 7.0.1
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-nesting
>   postcss-overflow-shorthand  >=2.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-overflow-shorthand
>   postcss-page-break  2.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-page-break
>   postcss-place  >=4.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-place
>   postcss-pseudo-class-any-link  >=6.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-pseudo-class-any-link
>   postcss-replace-overflow-wrap  3.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-replace-overflow-wrap
>   postcss-selector-matches  >=4.0.0
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-selector-matches
>   postcss-selector-not  4.0.0 - 4.0.1
>   Depends on vulnerable versions of postcss
>   node_modules/postcss-selector-not
>   resolve-url-loader  >=3.0.0-alpha.1
>   Depends on vulnerable versions of postcss
>   node_modules/resolve-url-loader
> 
> 37 moderate severity vulnerabilities
> 
> To address issues that do not require attention, run:
>   npm audit fix
> 
> To address all issues (including breaking changes), run:
>   npm audit fix --force

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/20795
