### ISSUE TITLE
Data path "" must NOT have additional properties(skipTests). Angular 12.0.0

### ISSUE THREAD

**Issue by inidaname** [angular/angular-cli#20811]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] generate

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11 ....

### Description

 A clear and concise description of the problem...
I initiated a new angular project in which I had `--skip-tests` flag for the application on running the module generate command I got this error

## 🔬 Minimal Reproduction

generate new project `ng new appName --skip-tests`
generate new module `ng generate module shared`

## 🔥 Exception or Error
```
Schematic input does not validate against the Schema: {"skipTests":true,"name":"shared","project":"search"}
Errors:

  Data path "" must NOT have additional properties(skipTests).

```

</code></pre>

## 🌍 Your Environment

```
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 14.15.1
Package Manager: npm 6.14.8
OS: linux x64

Angular: 12.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

```
</code></pre>

**Anything else relevant?**

**Comment by inidaname** [comment]
Checked and identified that cli set the module schematics on angular.json to `skipTests: true` this will always pass error as module initial does not produce any test files, will be happy to send in a PR to fix this.

on line 28 of my angular.json
```
        "@schematics/angular:module": {
          "skipTests": true
        },
```

**Comment by alan-agius4** [comment]
A PR is welcome.

**Comment by patil2097** [comment]
Hi @alan-agius4 , I am new to this project. I would love to contribute. Can you guide me a little on how I can close this issue ?

**Comment by alan-agius4** [comment]
@patil2097, the fix should be pretty straight forward. You need to remove the linked line https://github.com/angular/angular-cli/blob/f5f41ea929444102cede1a6aef8bd75937c45a6e/packages/schematics/angular/application/index.ts#L100

You can read our contribution guidelines here: https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md
