### ISSUE TITLE
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.

### ISSUE THREAD

**Issue by wdunn001** [angular/angular-cli#20819]
# Bug Report

### Affected Package
Angular/Core 12.0.0

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.x.x

### Description
You now receive an error while building an angular application regarding node polyfills and Webpack 5
https://i.stack.imgur.com/SpjFk.png

this is because of the following breaking change in Webpack 5
https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed

This breaking change didn't exist in previous versions of angular. We use node class libraries shared across the front and backend.

## Minimal Reproduction

https://github.com/wdunn001/polyfill-example

## Exception or Error
<pre><code>
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
12.0.0

</code></pre>

While this is a known breaking change and is easy to fix with Webpack 5 separately as far as I know it requires third party NPM libraries to fix in Angular which might not be an option for me.

**Comment by alan-agius4** [comment]
Hi,

While it is not adviced to use libraries that use Node.JS modules in a browser application, you can use tsconfig path mappings to point the a custom polyfill.

Example

```json
  "compilerOptions": {
    ..
    "paths": {
      "assert": [
        "./assert.ts"
      ]
    }
  },
```

**Comment by hugoebarboza** [comment]
If I don't want to include a polyfill, which file do I need to update in order to resolve the problem ?
resolve.fallback: { "assert": false }

**Comment by damogallagher** [comment]
I have the following error in my console since upgrading to angular 12 and also upgrading all other libraries
`./node_modules/aws-amplify-angular/__ivy_ngcc__/dist/src/components/interactions/chatbot/chatbot.component.core.js:118:0-35 - Error: Module not found: Error: Can't resolve 'util' in '/Users/damiengallagher/Development/sourceControl/c-research/grievance-platform/frontend/node_modules/aws-amplify-angular/__ivy_ngcc__/dist/src/components/interactions/chatbot'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }`

Can anyone provide any guidance on how to solve this? Similar to @hugoebarboza - what files need to be updated

**Comment by clydin** [comment]
@damogallagher That appears to be more of an issue with the `aws-amplify-angular` package that Webpack 5 is now exposing.  `aws-amplify-angular` seems to be importing a Node.js builtin module inside an Angular component file ([location](https://github.com/aws-amplify/amplify-js/blob/edf2b71a4ca3058883d27067fb6c87a9f3b339cb/packages/aws-amplify-angular/src/components/interactions/chatbot/chatbot.component.core.ts#L26)).  The import is also for the `isUndefined` function which has been deprecated in Node.js since v4.0 (https://nodejs.org/api/util.html#util_util_isundefined_object)

**Comment by PowerKiKi** [comment]
A different solution for a different package. In my case `crypto-js` was the cause of the error.

I migrated my code from `crypto-js` to `crypto-es` . It was straightforward because `crypto-es` is a fork, but with the advantages of not using node crypto, including typings, and being ESM (so potential tree shaking).

**Comment by LewandowskiJan** [comment]
In my case, it was enough to remove 'jasmine' from types array in tsconfig.spec.json

`
 "types": [      "jasmine"    ],
`

**Comment by damogallagher** [comment]
Thanks for the suggestions guys - I tried all of these as well as updating my tsconfig files to match the latest files in a new Angular 12 project but no joy
I still get these exceptions
`BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
        - install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "util": false }`

Any other suggestions available?

**Comment by damogallagher** [comment]
My issue was fixed by following instructions [here](https://github.com/ghiscoding/Angular-Slickgrid/issues/769)

**Comment by patrikmojzis** [comment]
> Can anyone provide any guidance on how to solve this? Similar to @hugoebarboza - what files need to be updated

Try to edit `./node_modules/@angular-devkit/build-angular/src/webpack/configs/browser.js`

And under `resolve` add `fallback`:
```
resolve: {
    ***
    fallback: {
        "util": require.resolve("util/")
    }
},
```

Don't forget install util:
`npm i util`

**Comment by clydin** [comment]
@damogallagher The `aws-amplify-angular` has a legitimate issue that should ideally be corrected which would avoid that workaround.

**Comment by damogallagher** [comment]
Yes I hope to revert what I needed to do once that package is updated

**Comment by hugoebarboza** [comment]
Hello @damogallagher , @patrikmojzis  Thank you all...

**Comment by luismendes070** [comment]
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "resolve":{
      "fallback":{
        "http": require.resolve("stream-http"),
        "https": require.resolve("https-browserify")
      }

    },
          "paths": {
      "assert": [
        "./assert.ts"
      ]
    },
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": true,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2020",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

**Comment by raman-nbg** [comment]
Why is this issue closed? It is not clear how to solve this. Shouldn't angular-cli bring the required polyfills to run `ng test`?

**Comment by wdunn001** [comment]
I also feel like this is still a regression. I didn't close the issue myself.

**Comment by raman-nbg** [comment]
In my case the error only occurred runnin `ng test`. The error only happens if you have `import "jasmine";" in your `*.spec.ts` files. Removing the import solved the issue for me.

**Comment by boeckMt** [comment]
I had the following Error.

```bash
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
```

Fixed it with:
npm i path-browserify -D

```json
// tsconfig.json

"compilerOptions": {
...
    "paths": {
      "path": [
        "./node_modules/path-browserify"
      ]
    }
```

**Comment by ryuseikurata** [comment]
if you got above the error, maybe you wrongly import 'protractor'.

**Comment by ps2goat** [comment]
> My issue was fixed by following instructions [here](https://github.com/ghiscoding/Angular-Slickgrid/issues/769)

That's funny because that issue points back here as being the answer ☜(ﾟヮﾟ☜)

**Comment by LingVuDev** [comment]
Installing `assert` and `buffer` did for me the trick:
```
npm install assert buffer --save-dev
```

**Comment by vaerilius** [comment]
npm i path-browserify
and add  webpack.config.js =>
  
  resolve: {
      extensions: [".tsx", ".ts", ".js", ".json"],
      fallback: { path: require.resolve("path-browserify") },
    },

**Comment by nhhockeyplayer** [comment]
it seems a group of developers across the ecosystem require a severe dope slap for wiping out the ecosystem
I have yet to build since June still cant see a solution I want to work into my elite codeebase as of yet I not stooping down to these low levels of development hack

and all we find are workarounds forcing unwanted packages paths and more dysfunctional webpack javascript hack

no one wants webpack.... same for javascript its unwanted not needed and a pestilence to the ecosystem

**Comment by AlaaEl-DinAhmed** [comment]
I solved this issue by installing util

`npm i util`

**Comment by fausrguez** [comment]
In my case, the issue was related with importing `environment` from the server and that wasn't available in the browser.

`import { environment } from 'main.server';` -> `import { environment } from 'environments/environment';`

**Comment by roanvanstaveren** [comment]
I have read every single comment in this discussion, have tried every possible solution and still am without luck. 
![image](https://user-images.githubusercontent.com/38979087/129672192-57b118d0-a15f-48fe-8502-ef0c949b1280.png)
I am quite new to Angular and Front-End development in general, what am I doing wrong?

**Comment by raman-nbg** [comment]
@roanvanstaveren the error could be in the imports any code file.

One option could be to remove all code files from your project and then add them again step by step. After each file (or at least component) you should try to build your project.

Then you can figure out from which file/import the error is coming.

This isn't a straightforward solution but maybe this helps...

**Comment by raman-nbg** [comment]
@alan-agius4 I think we should reopen this issue and find an appropriate solution.

**Comment by mMohamed451** [comment]
any solution?

**Comment by alan-agius4** [comment]
In a nutshell the problem here happens when web application depends on libraries which are not meant to run in Web environments.

For legacy compatibility reasons Webpack 4 polyfilled Node.js core modules by default which resulted in an undefined and sometimes broken behaviour. Webpack 5 stopped automatically polyfilling Node.js core modules and focuses more on web compatible modules.

As per example above (https://github.com/angular/angular-cli/issues/20819#issuecomment-900259393), you can configure the polyfills using TypeScript path mappings.  That being said, this should used as a workaround as ideally whenever possible one should move away from using libraries in Web applications that were not intended to run in a browser environment.

**Comment by BaamAadmi** [comment]
`"paths": {
      "path": [
        "./node_modules/path-browserify"
      ]
    },`

Adding the above to the tsconfig fixed my issue.  You don't need to install anything if you already have browserify.

**Comment by themizzi** [comment]
Removing the package that had node dependencies removed the error for me. Thanks, @alan-agius4.

**Comment by hermanwhyd** [comment]
> I had the following Error.
> 
> ```shell
> BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
> This is no longer the case. Verify if you need this module and configure a polyfill for it.
> 
> If you want to include a polyfill, you need to:
>         - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
>         - install 'path-browserify'
> If you don't want to include a polyfill, you can use an empty module like this:
>         resolve.fallback: { "path": false }
> ```
> 
> Fixed it with:
> npm i path-browserify -D
> 
> ```json
> // tsconfig.json
> 
> "compilerOptions": {
> ...
>     "paths": {
>       "path": [
>         "./node_modules/path-browserify"
>       ]
>     }
> ```

Thanks, this solution is working for me:

`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "allowSyntheticDefaultImports": true,
    // "strictFunctionTypes": true,
    // "noImplicitReturns": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "path": [
        "./node_modules/path-browserify"
      ]
    }
  },
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
`

tips: is you using a extends, just make sure you put on the super class.

**Comment by KostaD02** [comment]
Have almost same error , does anoyone got fix ? 
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }

**Comment by mlbiche** [comment]
I had this issue when running Angular tests only because I was using `By` keyword (as mentioned in [Angular Testing documentation](https://angular.io/guide/testing-attribute-directives)) and I imported it from `protractor` instead of `@angular/platform-browser`, if it can help anyone 🙂

**Comment by seth-church** [comment]
When upgrading our angular app to version 12, we ran into this issue as well. After doing an `npm i util`, our build worked, but we stil had this console error on app load:
```
util.js:109 Uncaught ReferenceError: process is not defined
    at Object.94655 (util.js:109)
```
We fixed this by adding the following to our polyfill.ts file:
```
(window as any).process = {
  env: { DEBUG: undefined },
};
```
according to [these instructions](https://stackoverflow.com/questions/68646434/after-updating-angular-we-get-a-process-is-not-defined).

**Comment by doughlass** [comment]
> When upgrading our angular app to version 12, we ran into this issue as well. After doing an `npm i util`, our build worked, but we stil had this console error on app load:
> 
> ```
> util.js:109 Uncaught ReferenceError: process is not defined
>     at Object.94655 (util.js:109)
> ```
> 
> We fixed this by adding the following to our polyfill.ts file:
> 
> ```
> (window as any).process = {
>   env: { DEBUG: undefined },
> };
> ```
> 
> according to [these instructions](https://stackoverflow.com/questions/68646434/after-updating-angular-we-get-a-process-is-not-defined).

Spent the past 24 hours trying to figure this out and the docs say to use webpack.config.js which doesn't work. but this snippet you added works great!

**Comment by RouR** [comment]
https://stackoverflow.com/questions/67572355/webpack-5-angular-polyfill-for-node-js-crypto-js

**Comment by ftanrisevdi** [comment]
Hi all,
I just want to share our solution to cypress+cucumber+webpack5 issue that has been occured after angular 12 update
first we got the error below;

```
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { path: require.resolve('path-browserify') }'
        - install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "assert": false }

```
To solve this, install path-browserify and add your webpack.config.js the line below;

```
resolve: {
    ......
    fallback: { path: require.resolve('path-browserify') }
  },
```
Then we got this error from cypress

```
The following error originated from your test code, not from Cypress.

  > process is not defined

```
To solve this, install node-polyfill-webpack-plugin and add to your webpack.config.js as a plugin

```
const NodePolyfillPlugin = require('node-polyfill-webpack-plugin');
...
plugins: [new NodePolyfillPlugin()],
```
Cheers
