### ISSUE TITLE
Angular 7 i18n support  translate typescript file

### ISSUE THREAD

**Issue by datnd-miagi** [angular/angular-cli#20817]
**Versions.**
```
    "@angular/animations": "7.2.2",
    "@angular/cdk": "7.2.2",
    "@angular/common": "7.2.6",
    "@angular/compiler": "7.2.6",
    "@angular/core": "7.2.6",
    "@angular/forms": "7.2.6",
    "@angular/material": "7.2.2",
    "@angular/platform-browser": "7.2.6",
    "@angular/platform-browser-dynamic": "7.2.6",
    "@angular/router": "7.2.6",
```
**This is a support request:**
I started internationalizing my application, and I met the following problem: when generating the bundle for the Japanese locale (for example), with using i18n for .html file perfectly used but i can not using with .ts file. As far as I find out there are two ways, **ngx-translate** and **@angular/localize**. 
Ngx-translate not suitable for my project, @angular/localize using start with angular 9 but i using angular 7.
Is there any way translate typescript file with angular 7 ? Or do I really have to upgrade to angular 9 to use @angular/localize

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
