### ISSUE TITLE
build-optimizer to exclude packages

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#20828]
# 🚀 Feature request

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The build `build-optimizer` may omit scripts that are required at runtime. 

### Proposed solution

Have angular.json file `build-optimizer` accept options:

```json
"buildOptimizer": {
  "exclude": ["my-package"]
}
```

**Comment by alan-agius4** [comment]
Hi @zehavibarak,

Thanks for this feature request.

We have discussed this and we feel that this is a rare case and not completing enough to have it added to our public API.

You can use a third party builder like https://github.com/manfredsteyer/ngx-build-plus were you can add a module rule that excludes the mentioned.

NB: while the Angular CLI allows extending the Webpack configuration, doing so is not supported by the Angular tooling team.
