### ISSUE TITLE
Unexpected warning: Generating index html...2 rules skipped due to selector errors

### ISSUE THREAD

**Issue by mlc-mlapis** [angular/angular-cli#20839]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.2.3

### Description

After upgrade to Angular 12 and CLI 12 the following warning appeared:

✔ Browser application bundle generation complete.
✔ Copying assets complete.
⠋ Generating index html...2 rules skipped due to selector errors:
  0 @@ .ui-grid -> Unmatched selector: @@ .ui-grid
✔ Index html generation complete.

## 🔬 Minimal Reproduction

It's unclear if it's possible to reproduce this behavior on a simple project.
Maybe related to https://github.com/angular/angular-cli/issues/20031?

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.0
Nx CLI: 12.3.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1200.0
@angular-devkit/architect-cli    0.1200.0
@angular-devkit/build-angular    12.0.0
@angular-devkit/core             12.0.0
@angular-devkit/schematics       12.0.0
@angular-devkit/schematics-cli   12.0.0
@schematics/angular              12.0.0
rxjs                             6.6.7
typescript                       4.2.4</code></pre>

**Comment by alan-agius4** [comment]
@mlc-mlapis, it appears something related to `ui-grid`, can you try to setup a minimal project using `ui-grid` and see if that reproduces the problem?


You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by mlc-mlapis** [comment]
@alan-agius4 Thanks. After a deeper exploration, we found some problems in the dependency package PrimeNG and its styles. After removing it, the warning disappeared.
