### ISSUE TITLE
Minify "all" distribution files

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#20834]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...

I am part of a team developing an enterprise application where we are at a point to optimize things  using tools like webpack bundle analyser etc. During that, I just noticed that some files in the distribution folder are not minified at all. Because we have a strict timeline I just developed a post-runner for each build that run right after a `ng build` which minifies files based on its extension in the `dist` folder. In our case this reduced the overall `dist` size by ~50 MB. Most of them aren't Angular specific but some are. Seen below I request a feature to minify all files or as in #11787 add some hooks we could use to process files directly.

```
> File index.html (5.24 kB -> 4.92 kB)
> File ngsw-worker.js (144 kB -> 38.9 kB)
> File worker-basic.min.js (519 B -> 247 B)
> File safety-worker.js (519 B -> 247 B)
> File manifest.webmanifest (532 B -> 353 B)
> File ngsw.json (17.5 kB -> 15.2 kB)
```

### Describe the solution you'd like

Minify _all_ Angular produced files or provide a hook, so we can do it ourselves during the build process.

### Describe alternatives you've considered

None

> A not always up-to-date post minifier that you can run after `ng build`: https://gist.github.com/muuvmuuv/3f8fae0c12cc0859195c1be981c88a19

**Comment by alan-agius4** [comment]
Hi,

- SW files kindly subscribe to: https://github.com/angular/angular/issues/27490
- HTML kindly subscribe to: https://github.com/angular/angular-cli/issues/11360 
- JSON and manifest.webmanifest files I don't see much benefit into compressing this type since they compress particular well using GZIP and Brotli

**Comment by muuvmuuv** [comment]
Oh, sorry, did not find the first one and already subscribed to it, can't remember when I did that. Will close as dup. I agree with the JSON case, I simply forget the compression factor.
