### ISSUE TITLE
Angular 12 crash with `ng serve`

### ISSUE THREAD

**Issue by cesco69** [angular/angular-cli#20835]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present

### Description

Angular 12 crash with `ng serve`

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/6096678/118628707-2ad96100-b7cd-11eb-9c2a-6558e67d8b3d.png)

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 12.15.0
Package Manager: npm 6.13.4
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            8.3.29
@angular-devkit/schematics      8.3.29
@schematics/angular             8.3.29
rxjs                            7.0.1
typescript                      4.2.4
</code></pre>

**Comment by alan-agius4** [comment]
Duplicate https://github.com/angular/angular-cli/issues/20801

**Comment by cesco69** [comment]
@alan-agius4 ok, i have addedd the "Allocation failed - JavaScript heap out of memory" maybe can help

**Comment by alan-agius4** [comment]
A memory snapshot or access to be project would be helpful :)

**Comment by nigrosimone** [comment]
Access to the project isn't possibile... How i can produce the Memory snapshot?
