### ISSUE TITLE
cannot find @angular-devkit\build-angular\src\babel\webpack-loader.js, @ngtools\webpack\src\ivy\index.js

### ISSUE THREAD

**Issue by RaphaelNagato** [angular/angular-cli#20841]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 after creating a new angular project,  these errors * cannot find module node_modules/@angular-devkit\build-angular\src\babel\webpack-loader.js *, * cannot find  module node_modules@ngtools\webpack\src\ivy\index.js *, * cannot find module node_modules\mini-css-extract-plugin\dist\loader.js *are shown on my terminal after running ``` ng serve ```

## 🔬 Minimal Reproduction

1. ``` npm install -g @angular/cli ```
2. ``` ng new client ```
3. ``` cd client```
4. ``` ng serve ```
## 🔥 Exception or Error

<pre><code>

../../../../C #client/src/main.ts - Error: Module build failed: Error: Cannot find module 'C:\client\node_modules\@angular-devkit\build-angular\src\babel\webpack-loader.js'  
Require stack:
- C:\client\node_modules\webpack\lib\ProgressPlugin.js
- C:\client\node_modules\webpack\lib\index.js
- C:\client\node_modules\@angular-devkit\build-webpack\src\webpack\index.js 
- C:\client\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\client\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\client\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\client\node_modules\@angular-devkit\architect\node\index.js
- C:\client\node_modules\@angular\cli\models\architect-command.js
- C:\client\node_modules\@angular\cli\commands\serve-impl.js
- C:\client\node_modules\@angular-devkit\schematics\tools\export-ref.js     
- C:\client\node_modules\@angular-devkit\schematics\tools\index.js
- C:\client\node_modules\@angular\cli\utilities\json-schema.js
- C:\client\node_modules\@angular\cli\models\command-runner.js
- C:\client\node_modules\@angular\cli\lib\cli\index.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\lib\init.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\client\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\client\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at NormalModule.doBuild (C:\client\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\client\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\client\node_modules\webpack\lib\Compilation.js:1311:12
    at NormalModule.needBuild (C:\client\node_modules\webpack\lib\NormalModule.js:1146:26)

../../../../C #client/src/polyfills.ts - Error: Module build failed: Error: Cannot find module 'C:\client\node_modules\@ngtools\webpack\src\ivy\index.js'
Require stack:
- C:\client\node_modules\webpack\lib\ProgressPlugin.js
- C:\client\node_modules\webpack\lib\index.js
- C:\client\node_modules\@angular-devkit\build-webpack\src\webpack\index.js 
- C:\client\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\client\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\client\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\client\node_modules\@angular-devkit\architect\node\index.js
- C:\client\node_modules\@angular\cli\models\architect-command.js
- C:\client\node_modules\@angular\cli\commands\serve-impl.js
- C:\client\node_modules\@angular-devkit\schematics\tools\export-ref.js     
- C:\client\node_modules\@angular-devkit\schematics\tools\index.js
- C:\client\node_modules\@angular\cli\utilities\json-schema.js
- C:\client\node_modules\@angular\cli\models\command-runner.js
- C:\client\node_modules\@angular\cli\lib\cli\index.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\lib\init.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\client\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\client\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at NormalModule.doBuild (C:\client\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\client\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\client\node_modules\webpack\lib\Compilation.js:1311:12
    at NormalModule.needBuild (C:\client\node_modules\webpack\lib\NormalModule.js:1146:26)

../../../../C #client/src/styles.scss - Error: Module build failed: Error: Cannot find module 'C:\client\node_modules\mini-css-extract-plugin\dist\loader.js'
Require stack:
- C:\client\node_modules\webpack\lib\ProgressPlugin.js
- C:\client\node_modules\webpack\lib\index.js
- C:\client\node_modules\@angular-devkit\build-webpack\src\webpack\index.js 
- C:\client\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\client\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\client\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\client\node_modules\@angular-devkit\architect\node\index.js
- C:\client\node_modules\@angular\cli\models\architect-command.js
- C:\client\node_modules\@angular\cli\commands\serve-impl.js
- C:\client\node_modules\@angular-devkit\schematics\tools\export-ref.js     
- C:\client\node_modules\@angular-devkit\schematics\tools\index.js
- C:\client\node_modules\@angular\cli\utilities\json-schema.js
- C:\client\node_modules\@angular\cli\models\command-runner.js
- C:\client\node_modules\@angular\cli\lib\cli\index.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\lib\init.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at C:\client\node_modules\webpack\lib\ProgressPlugin.js:412:9
    at Hook.eval [as call] (eval at create (C:\client\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (C:\client\node_modules\tapable\lib\Hook.js:14:14)
    at NormalModule.doBuild (C:\client\node_modules\webpack\lib\NormalModule.js:724:24)
    at NormalModule.build (C:\client\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\client\node_modules\webpack\lib\Compilation.js:1311:12

../../../../C #client/src/app/app.component.scss - Error: Module build failed (from ../../../../C #client/node_modules/raw-loader/dist/cjs.js):
Error: Cannot find module 'C:\client\node_modules\raw-loader\dist\cjs.js'  
Require stack:
- C:\client\node_modules\loader-runner\lib\loadLoader.js
- C:\client\node_modules\loader-runner\lib\LoaderRunner.js
- C:\client\node_modules\webpack\lib\NormalModule.js
- C:\client\node_modules\webpack\lib\NormalModuleFactory.js
- C:\client\node_modules\webpack\lib\Compiler.js
- C:\client\node_modules\webpack\lib\ProgressPlugin.js
- C:\client\node_modules\webpack\lib\index.js
- C:\client\node_modules\@angular-devkit\build-webpack\src\webpack\index.js 
- C:\client\node_modules\@angular-devkit\build-webpack\src\index.js
- C:\client\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\client\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\client\node_modules\@angular-devkit\architect\node\index.js
- C:\client\node_modules\@angular\cli\models\architect-command.js
- C:\client\node_modules\@angular\cli\commands\serve-impl.js
- C:\client\node_modules\@angular-devkit\schematics\tools\export-ref.js     
- C:\client\node_modules\@angular-devkit\schematics\tools\index.js
- C:\client\node_modules\@angular\cli\utilities\json-schema.js
- C:\client\node_modules\@angular\cli\models\command-runner.js
- C:\client\node_modules\@angular\cli\lib\cli\index.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\lib\init.js
- C:\ProgramData\nvm\v14.17.0\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at loadLoader (C:\client\node_modules\loader-runner\lib\loadLoader.js:19:17)
    at iteratePitchingLoaders (C:\client\node_modules\loader-runner\lib\LoaderRunner.js:182:2)
    at runLoaders (C:\client\node_modules\loader-runner\lib\LoaderRunner.js:397:2)
    at NormalModule.doBuild (C:\client\node_modules\webpack\lib\NormalModule.js:729:3)
    at NormalModule.build (C:\client\node_modules\webpack\lib\NormalModule.js:878:15)
    at C:\client\node_modules\webpack\lib\Compilation.js:1311:12

Error: Module not found: Error: Can't resolve 'C:\client\node_modules\webpack-dev-server\client\index.js?http://0.0.0.0:0&sockPath=/sockjs-node' in 'C:\client'

Error: Module not found: Error: Can't resolve 'C:\client\node_modules\webpack-dev-server\client\index.js?http://0.0.0.0:0&sockPath=/sockjs-node' in 'C:\client'

Error: Module not found: Error: Can't resolve 'C:\client\node_modules\webpack-dev-server\client\index.js?http://0.0.0.0:0&sockPath=/sockjs-node' in 'C:\client'

Error: src/app/app-routing.module.ts:10:14 - error NG6002: Appears in the NgModule.imports of AppModule, but itself has errors

10 export class AppRoutingModule { }
                ~~~~~~~~~~~~~~~~




</code></pre>

## 🌍 Your Environment

<pre><code>
<!-- run `ng version` and paste output below -->
<!-- ✍️-->
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0 (cli-only)
@angular-devkit/core         12.0.0 (cli-only)
@angular-devkit/schematics   12.0.0 (cli-only)
@schematics/angular          12.0.0 (cli-only)
</code></pre>

**Anything else relevant?**

<!-- ✍️Is this a browser specific issue? If so, please specify the browser and version. -->

<!-- ✍️Do any of these matter: operating system, IDE, package manager, HTTP server, ...? If so, please mention it below. -->

**Comment by developerctba** [comment]
Hey,

Try removing the # character from the folder path "**../../../../C #client**"

**Comment by alan-agius4** [comment]
Not sure where that `#` is coming from.

**Comment by alan-agius4** [comment]
@petebacondarwin, who has a Windows machine tried to replicate the issue but did manage.
```
C:\>ng new client
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
CREATE client/angular.json (3039 bytes)
CREATE client/package.json (1068 bytes)
CREATE client/README.md (996 bytes)
CREATE client/tsconfig.json (783 bytes)
CREATE client/.editorconfig (274 bytes)
CREATE client/.gitignore (604 bytes)
CREATE client/.browserslistrc (703 bytes)
CREATE client/karma.conf.js (1423 bytes)
CREATE client/tsconfig.app.json (287 bytes)
CREATE client/tsconfig.spec.json (333 bytes)
CREATE client/src/favicon.ico (948 bytes)
CREATE client/src/index.html (292 bytes)
CREATE client/src/main.ts (372 bytes)
CREATE client/src/polyfills.ts (2820 bytes)
CREATE client/src/styles.css (80 bytes)
CREATE client/src/test.ts (743 bytes)
CREATE client/src/assets/.gitkeep (0 bytes)
CREATE client/src/environments/environment.prod.ts (51 bytes)
CREATE client/src/environments/environment.ts (658 bytes)
CREATE client/src/app/app.module.ts (314 bytes)
CREATE client/src/app/app.component.html (23777 bytes)
CREATE client/src/app/app.component.spec.ts (940 bytes)
CREATE client/src/app/app.component.ts (210 bytes)
CREATE client/src/app/app.component.css (0 bytes)
√ Packages installed successfully.
    Successfully initialized git.
C:\>cd client
C:\client>ng serve
- Generating browser application bundles...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
√ Browser application bundle generation complete.
Initial Chunk Files   | Names         |      Size
vendor.js             | vendor        |   2.08 MB
polyfills.js          | polyfills     | 508.81 kB
styles.css, styles.js | styles        | 380.99 kB
main.js               | main          |  52.66 kB
runtime.js            | runtime       |   6.57 kB
                      | Initial Total |   3.00 MB
Build at: 2021-05-19T06:40:37.678Z - Hash: 8d3e7b3ab846183c46f6 - Time: 13274ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
√ Compiled successfully.
√ Browser application bundle generation complete.
5 unchanged chunks
Build at: 2021-05-19T06:40:38.983Z - Hash: 6b5673b371d91eda97d3 - Time: 888ms
√ Compiled successfully.
```

**Comment by RaphaelNagato** [comment]
I don't understand what changed, i created a new folder and ran angular cli again and it compiles

**Comment by alan-agius4** [comment]
@RaphaelNagato, glad it worked!
