### ISSUE TITLE
Schematic input does not validate against the Schema

### ISSUE THREAD

**Issue by cesco69** [angular/angular-cli#20848]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] generate

### Is this a regression?

Yes, it works on Angular 11

## 🔬 Minimal Reproduction

Into _angular.json_ set `skipTests` at `true` to module schematic:

```
{
  ...
  "projects": {
    "frontend": {
     ...
      "schematics": {
        ...
        "@schematics/angular:module": {
          "skipTests": true
        },
        ...
      },
   },
}, 
```

run the command for generate new module:

`ng g m foo`

output

```
Schematic input does not validate against the Schema: {"skipTests":true,"name":"test","project":"frontend"}
Errors:

  Data path "" must NOT have additional properties(skipTests).
```

## 🔥 Exception or Error

<pre><code>
Schematic input does not validate against the Schema: {"skipTests":true,"name":"foo","project":"frontend"}
Errors:

  Data path "" must NOT have additional properties(skipTests).
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0 (cli-only)
@angular-devkit/build-angular   12.0.0 (cli-only)
@angular-devkit/core            12.0.0 (cli-only)
@angular-devkit/schematics      12.0.0 (cli-only)
@angular/cli                    12.0.0 (cli-only)
@schematics/angular             12.0.0 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      4.0.5 (cli-only)

</code></pre>

**Comment by bogacg** [comment]
It's closed but I'm still getting this error. It's not added to version `12.0.1`? Do I need to remove `node_modules` folder and re-install?

**Comment by alan-agius4** [comment]
If you are already on 12.0.1, you can run `ng update @angular/cli —migrate-only —from 12.0.0 —to 12.0.1`

**Comment by bogacg** [comment]
What I did was just upgrading packages from `package.json` , `npm i` and executing `ng g m ...`

Executing command you provide (changing `—` to `-`) gives me this output:
>Using package manager: 'npm'
>Collecting installed dependencies...
>Found 36 dependencies.
>Package '-y' is not a dependency.

Last line being an error.

Creating a clean new project and then executing `ng g m ...` did work there.

On my existing project (initiated initially w. v12.0.0) even after deleting `node_modules` and re-installing I'm still getting error.
