### ISSUE TITLE
Issue during update existing project on Angular 11 to version 12 

### ISSUE THREAD

**Issue by yuriy-donskikh** [angular/angular-cli#20843]
# Bug Report

### Issue
During execution of:
<pre><code>
ng update @angular/core@12 @angular/cli@12
</code></pre>
Get an exception:
<pre><code>
An unhandled exception occurred: The "path" argument must be of type string. Received undefined
See "C:\Users\YX5870~1.DON\AppData\Local\Temp\ng-0ukmwd\angular-errors.log" for further details.
</code></pre>
The context of file:
<pre><code>
[error] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:154:9)
    at isInside (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:192:35)
    at C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:202:28
    at Array.filter (<anonymous>)
    at findProjectByPath (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:202:10)
    at getProjectByCwd (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:231:21)
    at Object.getConfiguredPackageManager (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\config.js:256:25)
    at async Object.getPackageManager (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\package-manager.js:35:27)
    at async UpdateCommand.initialize (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\commands\update-impl.js:46:31)
</code></pre>

### Environment
**Angular version**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: <error>
OS: win32 ia32

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.0.0 (cli-only)
@angular-devkit/schematics      12.0.0 (cli-only)
@angular/cli                    12.0.0 (cli-only)
@schematics/angular             12.0.0 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>
</code></pre>

**package.json**
<pre><code>
{
  "name": "Res",
  "version": "3.1.20",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "increase-version": "node ./build/version-increment.js",
    "post-build": "node ./build/post-build.js",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/schematics": "^11.1.0",
    "@angular/animations": "11.1.0",
    "@angular/cdk": "^11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "11.1.0",
    "@angular/core": "11.1.0",
    "@angular/forms": "11.1.0",
    "@angular/localize": "^11.1.0",
    "@angular/platform-browser": "11.1.0",
    "@angular/platform-browser-dynamic": "11.1.0",
    "@angular/router": "11.1.0",
    "@angularclass/hmr": "^3.0.0",
    "@ng-bootstrap/ng-bootstrap": "^9.0.1",
    "@ng-select/ng-select": "5.1.0",
    "@ngx-progressbar/core": "^5.3.2",
    "@ngx-progressbar/http": "^5.3.2",
    "@ngx-progressbar/router": "^5.3.2",
    "angular-in-memory-web-api": "0.11.0",
    "angular-oauth2-oidc": "10.0.3",
    "bootstrap": "4.6.0",
    "bootstrap-select": "1.13.18",
    "core-js": "3.8.3",
    "hammerjs": "2.0.8",
    "jquery": "3.5.1",
    "jwt-decode": "3.1.2",
    "lodash-es": "^4.17.20",
    "ng-multiselect-dropdown": "^0.2.14",
    "ngx-scrollbar": "^7.5.3",
    "ngx-toastr": "13.2.0",
    "popper.js": "1.16.1",
    "rxjs": "6.6.3",
    "ts-debug": "1.3.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.0",
    "@angular-eslint/builder": "1.1.0",
    "@angular-eslint/eslint-plugin": "1.1.0",
    "@angular-eslint/eslint-plugin-template": "1.1.0",
    "@angular-eslint/schematics": "1.1.0",
    "@angular-eslint/template-parser": "1.1.0",
    "@angular/cli": "^11.1.0",
    "@angular/compiler-cli": "11.1.0",
    "@angular/language-service": "11.1.0",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jwt-decode": "^3.1.0",
    "@types/node": "^14.14.22",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/eslint-plugin-tslint": "^4.14.1",
    "@typescript-eslint/parser": "4.3.0",
    "codelyzer": "^6.0.0",
    "eslint": "^7.6.0",
    "eslint-plugin-deprecation": "^1.2.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "iframe-resizer": "^4.3.1",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.0.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "~2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~9.1.1",
    "typescript": "~4.1.3"
  }
}
</code></pre>

**Comment by alan-agius4** [comment]
Can you kindly shard you `angular.json`? Thanks.

**Comment by yuriy-donskikh** [comment]
> Can you kindly shard you `angular.json`? Thanks.

Sure, here you go:
<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ng-universal": {
      "root": "",
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/OxygenRes",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "aot": true,
            "allowedCommonJsDependencies": [
              "iframe-resizer"
            ],
            "assets": [{
                "glob": "web.config",
                "input": "src",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ],
            "styles": [
              "./node_modules/bootstrap/scss/bootstrap.scss",
              "./node_modules/bootstrap-select/sass/bootstrap-select.scss",
              "./node_modules/ngx-toastr/toastr.css",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/fontawesome.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/light.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/regular.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/solid.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/v4-shims.scss",
              "./src/assets/seatmap/SeatmapPopup.css",
              "./src/styles/styles.scss"
            ],
            "scripts": [
              "./node_modules/iframe-resizer/js/iframeResizer.min.js",
              "./src/assets/seatmap/HitchHiker.SeatMap.global.js"
            ]
          },
          "configurations": {
            "hmr": {
              "budgets": [{
                "type": "anyComponentStyle",
                "maximumWarning": "6kb"
              }],
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.hmr.ts"
              }]
            },
            "production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "docker": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.docker.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,
              "poll": 1000
            },
            "dev": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev1": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev1.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev2": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev2.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev3": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev3.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev4": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev4.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "test": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.test.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "uat": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.uat.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "training": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.training.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "ng-universal:build"
          },
          "configurations": {
            "hmr": {
              "hmr": true,
              "browserTarget": "ng-universal:build:hmr"
            },
            "dev": {
              "browserTarget": "ng-universal:build:dev"
            },
            "dev1": {
              "browserTarget": "ng-universal:build:dev1"
            },
            "test": {
              "browserTarget": "ng-universal:build:test"
            },
            "production": {
              "browserTarget": "ng-universal:build:production"
            }
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/app/server",
            "main": "src/app/ngmodule.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "optimization": true
            }
          }
        },
        "udk": {
          "builder": "udk:udk-builder",
          "options": {
            "main": "src/main.server.ts",
            "browserTarget": "ng-universal:build",
            "serverTarget": "ng-universal:server"
          },
          "configurations": {
            "production": {
              "browserTarget": "ng-universal:build:production",
              "serverTarget": "ng-universal:server:production",
              "verbose": true,
              "fileReplacements": [{
                "src": "src/environments/environment.ts",
                "replaceWith": "src/environments/environment.prod.ts"
              }]
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              {
                "input": "styles.css",
                "inject": true
              }
            ],
            "scripts": [],
            "assets": [
              {
                "glob": "web.config",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        }
      }
    },
    "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "ng-universal:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "ng-universal:serve:production"
            }
          }
    }
  },
  "schematics": {
    "@schematics/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "ng-universal"  
}
</code></pre>

**Comment by alan-agius4** [comment]
Looks that the `e2e` has a missing required `root` option.

**Comment by yuriy-donskikh** [comment]
Thank you very much Alan,

I removed the section completely, now the context of angular.json is following:
<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "ng-universal": {
      "root": "",
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/OxygenRes",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "aot": true,
            "allowedCommonJsDependencies": [
              "iframe-resizer"
            ],
            "assets": [{
                "glob": "web.config",
                "input": "src",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ],
            "styles": [
              "./node_modules/bootstrap/scss/bootstrap.scss",
              "./node_modules/bootstrap-select/sass/bootstrap-select.scss",
              "./node_modules/ngx-toastr/toastr.css",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/fontawesome.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/light.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/regular.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/solid.scss",
              "./src/assets/fontawesome-pro-5.8.2-web/scss/v4-shims.scss",
              "./src/assets/seatmap/SeatmapPopup.css",
              "./src/styles/styles.scss"
            ],
            "scripts": [
              "./node_modules/iframe-resizer/js/iframeResizer.min.js",
              "./src/assets/seatmap/HitchHiker.SeatMap.global.js"
            ]
          },
          "configurations": {
            "hmr": {
              "budgets": [{
                "type": "anyComponentStyle",
                "maximumWarning": "6kb"
              }],
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.hmr.ts"
              }]
            },
            "production": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "docker": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.docker.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false,
              "poll": 1000
            },
            "dev": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev1": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev1.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev2": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev2.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev3": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev3.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "dev4": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.dev4.ts"
                }
              ],
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": false
            },
            "test": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.test.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "uat": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.uat.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            },
            "training": {
              "budgets": [
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.training.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "ng-universal:build"
          },
          "configurations": {
            "hmr": {
              "hmr": true,
              "browserTarget": "ng-universal:build:hmr"
            },
            "dev": {
              "browserTarget": "ng-universal:build:dev"
            },
            "dev1": {
              "browserTarget": "ng-universal:build:dev1"
            },
            "test": {
              "browserTarget": "ng-universal:build:test"
            },
            "production": {
              "browserTarget": "ng-universal:build:production"
            }
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/app/server",
            "main": "src/app/ngmodule.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "optimization": true
            }
          }
        },
        "udk": {
          "builder": "udk:udk-builder",
          "options": {
            "main": "src/main.server.ts",
            "browserTarget": "ng-universal:build",
            "serverTarget": "ng-universal:server"
          },
          "configurations": {
            "production": {
              "browserTarget": "ng-universal:build:production",
              "serverTarget": "ng-universal:server:production",
              "verbose": true,
              "fileReplacements": [{
                "src": "src/environments/environment.ts",
                "replaceWith": "src/environments/environment.prod.ts"
              }]
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              {
                "input": "styles.css",
                "inject": true
              }
            ],
            "scripts": [],
            "assets": [
              {
                "glob": "web.config",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          }
        },
        "lint": {
          "builder": "@angular-eslint/builder:lint",
          "options": {
            "lintFilePatterns": [
              "src/**/*.ts",
              "src/**/*.html"
            ]
          }
        }
      }
    }
  },
  "schematics": {
    "@schematics/angular:component": {
      "style": "scss"
    }
  },
  "defaultProject": "ng-universal"  
} 
</code></pre>

The original issue was resolved but now another one arise:
<pre><code>
PS C:\proj\res-upd>ng update @angular/core@12 @angular/cli@12
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
An unhandled exception occurred: Cannot locate bin for temporary package: @angular/cli.
See "C:\Users\YX5870~1.DON\AppData\Local\Temp\ng-7z0JhQ\angular-errors.log" for further details.
</code></pre>

The context of angular-errors.log:
<pre><code>
[error] Error: Cannot locate bin for temporary package: @angular/cli.
    at Object.runTempPackageBin (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\utilities\install-package.js:116:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UpdateCommand.validateAndRun (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\models\command.js:136:22)
    at async Object.runCommand (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\models\command-runner.js:205:24)
    at async default_1 (C:\Program Files (x86)\nodejs\node_modules\@angular\cli\lib\cli\index.js:70:31)
</code></pre>

**Comment by careywalker** [comment]
I am getting the same error as well. Note, I wasn't getting this error on Saturday last week when I upgraded another project.

```
ng update @angular/core@12 @angular/cli@12
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
√ Package successfully installed.
An unhandled exception occurred: Cannot locate bin for temporary package: @angular/cli.
```

log

```
[error] Error: Cannot locate bin for temporary package: @angular/cli.
    at Object.runTempPackageBin (C:\Users\a\AppData\Roaming\npm\node_modules\@angular\cli\utilities\install-package.js:116:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async UpdateCommand.validateAndRun (C:\Users\a\AppData\Roaming\npm\node_modules\@angular\cli\models\command.js:136:22)
    at async Object.runCommand (C:\Users\a\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:205:24)
    at async default_1 (C:\Users\a\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js:70:31)
```

**Comment by alan-agius4** [comment]
@yuriy-donskikh and @careywalker which versions are you updating from?

**Comment by yuriy-donskikh** [comment]
Hi Alan,

I'm updating from 11.1.0 to 12

**Comment by careywalker** [comment]
Here is my package.json

```
  "dependencies": {
    "@angular/animations": "~11.0.1",
    "@angular/common": "~11.0.1",
    "@angular/compiler": "~11.0.1",
    "@angular/core": "~11.0.1",
    "@angular/forms": "~11.0.1",
    "@angular/platform-browser": "~11.0.1",
    "@angular/platform-browser-dynamic": "~11.0.1",
    "@angular/router": "~11.0.1",
    "ngx-bootstrap": "^5.3.2",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.7",
    "@angular/cli": "~11.0.2",
    "@angular/compiler-cli": "~11.0.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "ng-packagr": "^11.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
```

**Comment by alan-agius4** [comment]
Can you try to update your global cli?

```
ng update @angular/cli -g
```

**Comment by telb99** [comment]
@alan-agius4 

I had the same problem trying to update from 12.0.0.0 to 12.0.0.1 just now.
Didn't have a problem last week updating from latest 11 to 12.0.0.0.
Your suggestion to updating the global cli fixed it for me.

**Comment by yuriy-donskikh** [comment]
Thank you very much @alan-agius4 ,

It helped, issue can be closed.

**Comment by shark-o** [comment]
Is it really necessary to install cli globally? I prefer to keep all deps inside workspace dir.

**Comment by StickNitro** [comment]
Just tried this and getting the same error as above `Error: Cannot locate bin for temporary package: @angular/cli.`.  I am running `ng update` as well as `ng update @angular/cli`.  Already tried deleting node_modules and installing packages, upgraded npm, done an `npm i @angular/cli -g` and nothing has resolved this problem.  I am currently unable to upgrade!!!

**Comment by aksdevac** [comment]
Got similar error (An unhandled exception occurred: Cannot locate bin for temporary package: @angular/cli) today while updating from `12.0.0` to latest `12.x`
