### ISSUE TITLE
Class name of generated service

### ISSUE THREAD

**Issue by TwanoO67** [angular/angular-cli#2085]
Hello,

My env:
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.3.1
os: linux x64 (lubuntu)

It seems to have a naming problem when using "ng g service name"

it creates "name.service.ts" with the export className where className is "Name"
and it create "name.service.ts" with an import of the previous file with the "NameService" as className.

So when running the tests, it has "no exported members" errors 

( I don't know if this is already patched, but I can't find issues about that)

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/533
