### ISSUE TITLE
Angular Cli 12.0.0 dependency issue when running "ng new"

### ISSUE THREAD

**Issue by KianSAlikhani** [angular/angular-cli#20857]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, this worked with @angular/cli version 11

### Description

I upgraded my @angular/cli version from 11 to 12, which required an update for node.js. After finishing the node.js upgrade I run ng new <project_name> and receive a dependency tree error outlined below:

## 🔬 Minimal Reproduction

Using @angular/cli version 12.0.0, create a new angular project by running `ng new <project_name>`. Select yes for angular routing and SCSS stylesheet format and it will throw this error.

## 🔥 Exception or Error

<pre><code>
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss
 ]
CREATE test123/angular.json (3213 bytes)
CREATE test123/package.json (1069 bytes)
CREATE test123/README.md (997 bytes)
CREATE test123/tsconfig.json (783 bytes)
CREATE test123/.editorconfig (274 bytes)
CREATE test123/.gitignore (604 bytes)
CREATE test123/.browserslistrc (703 bytes)
CREATE test123/karma.conf.js (1424 bytes)
CREATE test123/tsconfig.app.json (287 bytes)
CREATE test123/tsconfig.spec.json (333 bytes)
CREATE test123/src/favicon.ico (948 bytes)
CREATE test123/src/index.html (293 bytes)
CREATE test123/src/main.ts (372 bytes)
CREATE test123/src/polyfills.ts (2820 bytes)
CREATE test123/src/styles.scss (80 bytes)
CREATE test123/src/test.ts (743 bytes)
CREATE test123/src/assets/.gitkeep (0 bytes)
CREATE test123/src/environments/environment.prod.ts (51 bytes)
CREATE test123/src/environments/environment.ts (658 bytes)
CREATE test123/src/app/app-routing.module.ts (245 bytes)
CREATE test123/src/app/app.module.ts (393 bytes)
CREATE test123/src/app/app.component.html (23809 bytes)
CREATE test123/src/app/app.component.spec.ts (1060 bytes)
CREATE test123/src/app/app.component.ts (212 bytes)
CREATE test123/src/app/app.component.scss (0 bytes)
- Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: postcss@8.2.14
npm ERR! node_modules/postcss
npm ERR!   postcss@"8.2.14" from @angular-devkit/build-angular@12.0.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~12.0.0" from the root project
npm ERR!   postcss@"^8.2.10" from css-loader@5.2.4
npm ERR!   node_modules/css-loader
npm ERR!     css-loader@"5.2.4" from @angular-devkit/build-angular@12.0.0
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~12.0.0" from the root project
npm ERR!   8 more (cssnano, postcss-import, postcss-loader, icss-utils, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer postcss@"^8.2.15" from cssnano-preset-default@5.1.0
npm ERR! node_modules/cssnano/node_modules/cssnano-preset-default
npm ERR!   cssnano-preset-default@"^5.0.1" from cssnano@5.0.2
npm ERR!   node_modules/cssnano
npm ERR!     cssnano@"5.0.2" from @angular-devkit/build-angular@12.0.0
npm ERR!     node_modules/@angular-devkit/build-angular
npm ERR!       dev @angular-devkit/build-angular@"~12.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Kian\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Kian\AppData\Local\npm-cache\_logs\2021-05-19T20_41_37_932Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 7.13.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0 (cli-only)
@angular-devkit/core         12.0.0 (cli-only)
@angular-devkit/schematics   12.0.0 (cli-only)
@schematics/angular          12.0.0 (cli-only)

</code></pre>

**Anything else relevant?**

**Comment by dltmurphy** [comment]
I'm also having this issue. I've tried with and without Angular routing and both CSS and SCSS but it always fails

**Comment by aaryanporwal** [comment]
I'm having the same issue too! I was so frustrated because I just started learning Angular and this happened ...

node version: 14.16.1
npm version: 7.12.0

Tried thrice uninstalling and installing and even using different node version too (I use nvm)

**Comment by ashblue** [comment]
`--legacy-peer-deps` worked on my system.

```bash
npm i --legacy-peer-deps
```

![image](https://user-images.githubusercontent.com/643307/118890506-09a36e00-b8bc-11eb-9974-afa10fc667ab.png)

**Comment by aaryanporwal** [comment]
> `--legacy-peer-deps` worked on my system.
> 
> ```shell
> npm i --legacy-peer-deps
> ```
> 
> ![image](https://user-images.githubusercontent.com/643307/118890506-09a36e00-b8bc-11eb-9974-afa10fc667ab.png)

Ah I'm sorry I didn't know how to use it.

**Comment by clydin** [comment]
The cssnano packages were recently (several hours ago) released and the patch/minor releases appear to contain a breaking change involving the peer dependency version of `postcss` which triggers npm 7's peer dependency validation.

While a solution is investigated, the current workarounds are to either use npm 6 or use `ng new` with the `--skip-install` option and then manually install with either `npm install --force` or `npm install `--legacy-peer-deps`.

**Comment by KianSAlikhani** [comment]
> While a solution is investigated, the current workarounds are to either use npm 6 or use `ng new` with the `--skip-install` option and then manually install with either `npm install --force` or `npm install --legacy-peer-deps`.
> Using [yarn@1.x](mailto:yarn@1.x) (requires an install if not present on the system) as the package manager is also an option.

`npm install --legacy-peer-deps` seems to have worked for me. I assume the dependency issue will be fixed in future releases so I will close this issue for now.

Thanks!
