### ISSUE TITLE
build & serve immediately quit after update to 12.0.1

### ISSUE THREAD

**Issue by amoscatelli** [angular/angular-cli#20868]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.2.13

### Description

 Even with --verbose, build and serve just quit. No error is prompt.

PS C:\Users\amoscatelli\Documents\Visual Studio Code\optoplus-client-ui> ng build
Node.js version v15.14.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.
Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
PS C:\Users\amoscatelli\Documents\Visual Studio Code\optoplus-client-ui> 

The same applies disabling AOT, build optomization, both in dev or prod enviroments.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

PS C:\Users\amoscatelli\Documents\Visual Studio Code\optoplus-client-ui> ng version
Node.js version v15.14.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.1
Node: 15.14.0
Package Manager: npm 7.6.3
OS: win32 x64

Angular: undefined
...

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/cli                    12.0.1
@angular/compiler-cli           12.0.1
@angular/language-service       12.0.1
@schematics/angular             12.0.1
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
As the error suggests Node.JS 15 is not supported.
Please use a supported Node.JS version. 12.20 or 14.x.x

See: https://github.com/angular/angular/issues/42076
