### ISSUE TITLE
inlineCritical CSS asynchronous loading method breaks with CSP

### ISSUE THREAD

**Issue by jpduckwo** [angular/angular-cli#20864]
# Bug Report

### Affected Package
@angular/cli

### Is this a regression?
Nay

### Description
The method used for inlining critical css and asynchronously loading it, breaks and doesn't load the external stylesheet when you have a content security policy that doesn't include `script-src 'unsafe-inline'`. As the name suggests this isn't a very secure way of operating for various reasons such as script injection.

You can fix by disabling inlineCritical in the optimizations - however maybe there is a better way to load the styles, maybe in a JS file?

`<link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'">`

It's the `onload="this.media='all'"` that breaks it

## Minimal Reproduction
https://github.com/jpduckwo/ng12-csp-issue

run:
ng serve

## Exception or Error
Refused to execute inline event handler because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
![image](https://user-images.githubusercontent.com/13150911/118904857-01037400-b95e-11eb-9e10-5e50d5aac45b.png)

## Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by alan-agius4** [comment]
We can probably solve this by changing the preload strategy of [critters](https://github.com/GoogleChromeLabs/critters#preloadstrategy) from `media` to `default`.

Let me reach out to the Chrome team so see if there are any drawbacks of doing so.

**Comment by developit** [comment]
@alan-agius4 I think the "body" mode could work - it injects styles at the `<link>` location, then adds the `<link rel=stylesheet href=css>` just before `</body>`.

**Comment by alan-agius4** [comment]
@developit, thanks for the input, I had a chat with @janicklas-ralph, and mentioned that the default is idea although in some cases it can break CSS because of different CSS ordering.  I’ll investigate a bit more.

**Comment by ghusta** [comment]
An interesting article with an overview of this concept : 
- [Critical CSS inlining](https://blog.ninja-squad.com/2021/01/21/angular-cli-11.1/#critical-css-inlining)

**Comment by AElmoznino** [comment]
> Found how to disable the inlineCritical styles
> [aa3ea88](https://github.com/angular/angular-cli/commit/aa3ea885ed69cfde0914abae547e15d6d499a908)
> https://angular.io/guide/workspace-config#styles-optimization-options
> In angular.json in the build configuration Instead of
> 
> ```json
> "optimization": true
> ```
> 
> put
> 
> ```json
> "optimization": {
>   "scripts": true,
>   "styles": {
>     "minify": true,
>     "inlineCritical": false
>   },
>   "fonts": true
> },
> ```

I tried @tiberiuzuld's solution but didn't get it working. Any other workarounds?

**Comment by jpduckwo** [comment]
@AElmoznino that is the correct solution to restore the previous behaviour. However there may be multiple `"optimization": true` statements in your angular.json that you need to update. E.g. multiple configs for test / production etc.

**Comment by AElmoznino** [comment]
Thanks @jpduckwo, I didn't notice that 2nd optimization statement, got it working now!

**Comment by mjeffrey** [comment]
The workaround from @tiberiuzuld fixed the issue for me.

It might be a good idea to set up an integration test with a restrictive CSP and a basic app generated from the cli.
In this way this sort of issue could be caught early. Angular should be able to work with this:
```
default-src 'none';script-src 'self';connect-src 'self';style-src 'self';form-action 'self';base-uri 'self';img-src 'self' data:;font-src 'self';
```

**Comment by MaximeMorin-Devolutions** [comment]
We were facing the same issue.  We had 2 optimization flags.  The first build.options.optimization was set to false.  I initially changed the 2nd one with the production configuration.  The workaround didn't work.  I then changed the first one (initially at false) to the workaround and it started working.

```
"build": {
  ...
  "options": {
    ...
	"optimization": {   // Originally set to false.
	  "scripts": true,
	  "styles": {
		"minify": true,
		"inlineCritical": false
	  },
	  "fonts": true
	},
	...
  },
  "configurations": {
	"production": {
		...
	  "optimization": {   // Originally set to true.
		"scripts": true,
		"styles": {
		  "minify": true,
		  "inlineCritical": false
		},
		"fonts": true
	  },
	  ...
    }
  }
```
Not sure if it's a bug, but I would expect optimization false to also implies inlineCritical:false.  At least, it's working now.

**Comment by simonmumenthaler** [comment]
The necessary change, to actually skip the `onload` event listener in the ssr html is to provide the additional `inlineCriticalCss` property when using the `ngExpressEngine`:
```javascript
server.engine('html', ngExpressEngine({ bootstrap: AppServerModule, inlineCriticalCss:false }))
```

**Comment by BenRacicot** [comment]
Just came across this situation with 12.2.7 where it is causing my app's global stylesheet to not be applied.

Despite having no print MQs  the default optimization setting is adding `media=print` to the link. 

<link rel="stylesheet" ... href="styles.css" media="print">

"architect": ...
"build": ...
"configurations": {
  "dev": {
    ...
    "optimization": {
      "scripts": true,
      "styles": {
        "minify": true,
        "inlineCritical": false <--- fix
      },
      "fonts": true
    }

I added this as an answer to an older [StackOverflow](https://stackoverflow.com/a/69336136/1440240) question if you're interested.

**Comment by pacocom** [comment]
I have similar but not equal problem
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
![image](https://user-images.githubusercontent.com/7735329/140295242-633e00b4-0a76-490e-96ab-68894cc4c2ad.png)

**Comment by jpduckwo** [comment]
Hi @pacocom, it looks like the same problem. Maybe you need to apply the fix to other config areas of you angular config. Look for other `"optimization"` settings in your angular.json that are either set to something other than false.

**Comment by pacocom** [comment]
Already work.
Thanks.

**Comment by sander1095** [comment]
@alan-agius4 and maybe others..

What is the status of this issue? What i understand is that we have to disable the inline css feature, OR make our CSP more insecure. Both dont sound like great solutions.

Will there be a good fix to not require us to either sacrifice perf or security? If not, will there be documentation for angular with a CSP guide on how to create a Security performance balance?

**Comment by pauldraper** [comment]
Just disable inline CSS.

External stylesheets worked for dial-up internet, IDK why people insist on complicating the most simple things when speeds are 100x what they were.

**Comment by PapaNappa** [comment]
@sander1095 One work-around is of course to add
`script-src 'unsafe-hashes' 'sha256-MhtPZXr7+LpJUY5qtMutB+qWfQtMaPccfe7QXtCcEYc='`
This is not really more insecure, as it only allows the `this.media='all'` script to execute, which is the culprit of this issue.

**Comment by silvia-giordano** [comment]
Hello, 
I'm on Angular 13.0.2 and I have the same problem as @pacocom. I tried to apply the fix to other config areas of my angular config  (as suggested by @jpduckwo ) but still the same error.
Any ideas?

**Comment by Rugshtyne** [comment]
Can somebody point to the logic which extracts the 'critical css' and then renders it as inline? I mean maybe it's possible to customize that to include CSP nonces you have defined somewhere.

**Comment by rickz21** [comment]
I am trying to apply fix in Angular 13.  Please post angular.json  with fix.  I only  have one "optimization" setting. I changed it as suggested.  But, I still have   
<body style="overflow: auto; position: static; touch-action: auto;"> 
I didn't put that inline style there in the body tag. I guess Angular wants a quick page paint.
Please post angular.json  with fix.

**Comment by jpduckwo** [comment]
@rickz21 try putting the optimizations in the build > options  portion of the JSON

e.g.
```
...
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "assets": [
...
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [],
            "outputHashing": "all",
            "optimization": {
              "scripts": true,
              "styles": {
                "minify": true,
                "inlineCritical": false
              },
              "fonts": true
            },
...
```

**Comment by rickz21** [comment]
@jpduckwo thanks for the help. I will try that on my server in morning.

**Comment by rickz21** [comment]
@jpduckwo thank you trying to help me. I did  paste in the lines you posted within build.options  but it didn't work for me. Angular still inserted a style attribute into my page's body tag.  
body style="overflow: auto; position: static; touch-action: auto;"    
In the CSP report, Chrome  and Edge browsers suggested that I use 
style-src 'self' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=';   
and that does work to avoid that violation. Also, I am depending on  ngx-image-cropper. That package inserts some inline styling as well. That styling seems to change with each page request. So, it doesn't seem possible to use a hash for them. Hopefully, Angular 14 will work better for me. Thanks again.

**Comment by rickz21** [comment]
I read 
https://github.com/angular/angular/issues/6361 
https://github.com/angular/components/issues/24633  
and see that there are different opinions.

**Comment by jdavidhermoso** [comment]
https://0xdbe.github.io/AngularSecurity-DisableInlineCriticalCSS/

**Comment by rickz21** [comment]
@jdavidhermoso  I tried that configuration. It didn't stop Angular from adding inline styling to my body tag.

**Comment by jpduckwo** [comment]
Hey @rickz21 the style tag on the body isn't related to this issue. This one is about angular automatically inlining critical css. It sounds like your styles on the body could be coming from something else. Maybe it's another dependency? Might be worth posting a new issue if you can create minimal reproduction

**Comment by rickz21** [comment]
@jpduckwo  Angular is the only dependency. I will do as you suggest. I will try to create a minimal demonstration.

**Comment by ZenwalkerD** [comment]
Hello All,

In my case, my project uses Angular 13 latest; and this issue was happening only on PROD build. Not on Dev/Staging builds. I searched angular documentation; no where it is mentioned why only production grade build gets affected?

Any clarity would enlighten me on this.

Thanks

**Comment by jpduckwo** [comment]
@ZenwalkerD check your angular.json, your settings for dev/staging will have a different optimization setting than prod. That's my guess :)

**Comment by jprivet-dev** [comment]
Thank's @tiberiuzuld :tada:

I used your solution https://github.com/angular/angular-cli/issues/20864#issuecomment-844823912 for a Chrome extension created with **angular@14.0.2**. I also needed the code generated by the `ng build` command to have no inline script.

I put the following `optimization` configuration in my `angular.json` file:

```json
          "configurations": {
            "production": {
              "...": "...",
              "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": true
              }
            },
            "development": {
              "...": "..."
            }
          },
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. 

See: https://github.com/angular/angular-cli/pull/24903
