### ISSUE TITLE
Consider using swc(-loader) or esbuild(-loader)

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#20873]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

While I can't comment on the maturity/correctness/maintenance of either of these solutions by comparison to `babel-loader` (or any other components they could replace), SWC (Rust) and esbuild (Go) are supposedly much faster than mainstream JS alternatives.

For reference, apparently [SWC improved Parcel's build times by 10x](https://v2.parceljs.org/blog/beta3), and [Replit saw significant gains by adopting esbuild (via Vite)](https://blog.replit.com/vite).

Perhaps either or both could be optional dependencies that are used only when available at run-time.

**Comment by alan-agius4** [comment]
Hi @buu700, 

Thanks for the interest shown and the details provided.

We are aware of these project and we do periodically evaluate them. In fact at the moment, we are evaluating using ESBuild as our minimiser.

When we are confident enough that a the alternative approach doesn't cause regressions both in terms of build speed and output we will provide it out-of-the-box.

Thanks again.

**Comment by buu700** [comment]
Awesome, glad to know that's on your radar. I guess it'd be easier if esbuild ultimately made it a goal to match the outputs of all the tools it replaces, to allow for simpler regression testing.
