### ISSUE TITLE
Can't update to Angular 12.0.1 

### ISSUE THREAD

**Issue by igorosabel** [angular/angular-cli#20872]
# 🐞 Bug report

Hi! Yesterday Angular 12.0.1 was released so today I tried to update and I am getting this error:

```
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
An unhandled exception occurred: Cannot locate bin for temporary package: @angular/cli.
See "/private/var/folders/d8/y1490nv91k7665714lcf4g2w0000gn/T/ng-qdciqz/angular-errors.log" for further details.
```

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, I updated several projects from Angular 11 to 12 without a sweat.

### Description

This problem happens both on Windows 10 and macOS 11. When I try to update the project it says I have an old Angular CLI version, it downloads a temporary one... and then it fails.

## 🔬 Minimal Reproduction

ng update

I have tried with several Angular Projects (like [Cine](https://github.com/igorosabel/Cine) or [Game](https://github.com/igorosabel/Game)

## 🔥 Exception or Error

<pre><code>
% ng update
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
An unhandled exception occurred: Cannot locate bin for temporary package: @angular/cli.
See "/private/var/folders/d8/y1490nv91k7665714lcf4g2w0000gn/T/ng-yFEnkb/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 14.15.0
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

This exact same error happens on a Windows 10 Pro computer.

Thanks.

**Comment by alan-agius4** [comment]
Can you try to update the global CLI please?

```
npm i @angular/cli -g

**Comment by igorosabel** [comment]
Thanks, that worked both on my Windows and my mac systems.

What was the problem? I've been using Angular since v5 and never had this problem...

**Comment by alan-agius4** [comment]
There was a bug in `@angular/cli` version `12.0.0` which caused the temporary CLI needed to run `ng update` not to be found.
