### ISSUE TITLE
Custom path for tailwind.config.js

### ISSUE THREAD

**Issue by danilokorber** [angular/angular-cli#20878]
# Feature Request

### Relevant Package

 This feature request is for @angular/core

### Description
 I want to use a custom path for my tailwind.config.js file with Angular 12. It looks like it needs to be in the "project or workspace root": https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/configs/styles.ts#L125-L135

### Describe the solution you'd like
 A key in angular.json with a custom path (i.e. ./config/tailwind.config.js)

### Describe alternatives you've considered
 I did not find any workaround. Of course keeping it in the project root works fine, but I'd like to keep my files more organized.

**Comment by alan-agius4** [comment]
Hi @danilokorber,

Thanks for this feature request. 

That being said, this feature is not completing to increase our public API surface and add a new option.

Let's re-consider in the future is there is a larger demand from this from the community.
