### ISSUE TITLE
ViewEncapsulation.Native Prevents Global Styles From Being Applied

### ISSUE THREAD

**Issue by sqwk** [angular/angular-cli#2088]
* Mac OS X 10.11.6
 * Chrome 53.0.2785.101
 * ng v1.0.0-beta.11-webpack.8

Using `ViewEncapsulation.Native` prevents global styles from being applied. Using `ViewEncapsulation.Emulated` or `ViewEncapsulation.None` works as expected.

Can the cli prepend something like `/deep/` to global styles?

**Comment by deebloo** [comment]
/deep/ is deprecated with native shadow dom

**Comment by filipesilva** [comment]
We won't automatically change global styles, no. This is a discussion best had in https://github.com/angular/angular though, since it's a general issue.
