### ISSUE TITLE
CLI 12.0.1 No longer builds after updating project from Angular and CLI 8.2

### ISSUE THREAD

**Issue by cosmoKenney** [angular/angular-cli#20880]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11

### Description

ng build --prod=false throws errors then stays at the sealing (Generating browser application bundles (phase: sealing)...) phase for ever.

## 🔥 Exception or Error

<pre><code>
- Generating browser application bundles...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling ngx-popper : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
\ Generating browser application bundles (phase: sealing)...(node:6432) UnhandledPromiseRejectionWarning: TypeError: aSourceMapConsumer.eachMapping is not a function
    at Function.fromStringWithSourceMap (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\source-map\lib\source-node.js:87:24)
    at C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:108:24
    at Array.map (<anonymous>)
    at ConcatSource.node (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:104:19)
    at exports.getSourceAndMap (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\helpers.js:20:27)
    at ConcatSource.sourceAndMap (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:95:10)
    at CachedSource.sourceAndMap (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\CachedSource.js:158:35)
    at C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:106:31
    at Array.map (<anonymous>)
    at ConcatSource.node (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:104:19)
    at exports.getSourceAndMap (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\helpers.js:20:27)
    at ConcatSource.sourceAndMap (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\ConcatSource.js:95:10)
    at CachedSource.sourceAndMap (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\node_modules\webpack-sources\lib\CachedSource.js:158:35)
    at getTaskForFile (C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\lib\SourceMapDevToolPlugin.js:84:30)
    at C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\lib\SourceMapDevToolPlugin.js:272:22
    at C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp\node_modules\webpack\lib\Cache.js:91:34
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
| Generating browser application bundles (phase: sealing)...^C
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 7.14.0
OS: win32 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

## package.json:
<pre><code>
{
	"resolutions": { "webpack": "^5.0.0" },
	"name": "client-app",
	"version": "0.0.0",
	"scripts": {
		"ng": "ng",
		"start": "ng serve",
		"build": "ng build",
		"test": "ng test",
		"lint": "ng lint",
		"e2e": "ng e2e"
	},
	"private": true,
	"dependencies": {
		"@angular/animations": "~12.0.1",
		"@angular/common": "~12.0.1",
		"@angular/compiler": "~12.0.1",
		"@angular/core": "~12.0.1",
		"@angular/forms": "~12.0.1",
		"@angular/platform-browser": "~12.0.1",
		"@angular/platform-browser-dynamic": "~12.0.1",
		"@angular/router": "~12.0.1",
		"jquery": "^3.4.1",
		"jquery-migrate": "^3.1.0",
		"jquery-sticky-table-header": "^1.1.1",
		"jquery-ui-dist": "^1.12.1",
		"jquery-ui-touch-punch": "^0.2.3",
		"jquery-validation": "^1.19.1",
		"jsrender": "^1.0.3",
		"lodash": "^4.17.15",
		"ngx-popper": "^7.0.0",
		"popper.js": "^1.16.1",
		"qtip2": "^3.0.3",
		"rxjs": "~6.6.7",
		"select2": "^4.0.7",
		"tslib": "^2.0.0",
		"urijs": "^1.19.2",
		"zone.js": "~0.11.4"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "~12.0.1",
		"@angular/cli": "~12.0.1",
		"@angular/compiler-cli": "~12.0.1",
		"@angular/language-service": "~12.0.1",
		"@types/jasmine": "~3.6.0",
		"@types/jasminewd2": "~2.0.3",
		"@types/jquery": "^3.3.31",
		"@types/jquery.blockui": "0.0.28",
		"@types/jquery.fileupload": "^9.22.0",
		"@types/jquery.watermark": "^3.1.29",
		"@types/jqueryui": "^1.12.7",
		"@types/jsrender": "1.0.0",
		"@types/node": "^12.11.1",
		"@types/qtip2": "^2.2.29",
		"codelyzer": "^6.0.0",
		"jasmine-core": "~3.6.0",
		"jasmine-spec-reporter": "~5.0.0",
		"karma": "~6.3.2",
		"karma-chrome-launcher": "~3.1.0",
		"karma-coverage-istanbul-reporter": "~3.0.2",
		"karma-jasmine": "~4.0.0",
		"karma-jasmine-html-reporter": "^1.5.0",
		"protractor": "~7.0.0",
		"ts-node": "~7.0.0",
		"tslint": "~6.1.0",
		"typescript": "~4.2.4"
	}
}
</code></pre>

## angular.json:
<pre><code>
{
	"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
	"version": 1,
	"newProjectRoot": "projects",
	"projects": {
		"ClientApp": {
			"projectType": "application",
			"schematics": {
				"@schematics/angular:component": {
					"style": "scss"
				}
			},
			"root": "",
			"sourceRoot": "src",
			"prefix": "cl",
			"architect": {
				"build": {
					"builder": "@angular-devkit/build-angular:browser",
					"options": {
						"allowedCommonJsDependencies": [
							"lodash",
							"inputmask",
							"urijs"
						],
						"baseHref": "/web/",
						"outputPath": "../web/",
						"index": "src/index.html",
						"main": "src/main.ts",
						"polyfills": "src/polyfills.ts",
						"tsConfig": "tsconfig.app.json",
						"assets": [
							"src/favicon.ico",
							"src/assets",
							"src/config"
						],
						"styles": [
							"src/styles.scss",
							"../Home.scss"
						],
						"stylePreprocessorOptions": {
							"includePaths": [
								"src/styles",
								"../pqgrid"
							]
						},
						"scripts": [
							"node_modules/jquery/dist/jquery.min.js",
							"node_modules/jquery-ui-dist/jquery-ui.min.js",
							"node_modules/select2/dist/js/select2.min.js",
							"node_modules/qtip2/dist/jquery.qtip.min.js",
							"../Scripts/jquery.watermark.min.js",
							"../Scripts/popr/popr.min.js"
						],
						"vendorChunk": true,
						"extractLicenses": false,
						"buildOptimizer": false,
						"sourceMap": true,
						"optimization": false,
						"namedChunks": true
					},
					"configurations": {
						"staging": {
							"fileReplacements": [
								{
									"replace": "src/environments/environment.ts",
									"with": "src/environments/environment.staging.ts"
								},
								{
									"replace": "src/config/base-config.js",
									"with": "src/config/base-config.staging.js"
								}
							],
							"optimization": true,
							"outputHashing": "all",
							"namedChunks": false,
							"extractLicenses": true,
							"vendorChunk": false,
							"buildOptimizer": true,
							"budgets": [
								{
									"type": "initial",
									"maximumWarning": "2mb",
									"maximumError": "5mb"
								},
								{
									"type": "anyComponentStyle",
									"maximumWarning": "6kb",
									"maximumError": "10kb"
								}
							]
						},
						"production": {
							"fileReplacements": [
								{
									"replace": "src/environments/environment.ts",
									"with": "src/environments/environment.prod.ts"
								},
								{
									"replace": "src/config/base-config.js",
									"with": "src/config/base-config.prod.js"
								}
							],
							"optimization": true,
							"outputHashing": "all",
							"sourceMap": false,
							"namedChunks": false,
							"extractLicenses": true,
							"vendorChunk": false,
							"buildOptimizer": true,
							"budgets": [
								{
									"type": "initial",
									"maximumWarning": "2mb",
									"maximumError": "5mb"
								},
								{
									"type": "anyComponentStyle",
									"maximumWarning": "6kb",
									"maximumError": "10kb"
								}
							]
						}
					}
				},
				"serve": {
					"builder": "@angular-devkit/build-angular:dev-server",
					"options": {
						"browserTarget": "ClientApp:build"
					},
					"configurations": {
						"production": {
							"browserTarget": "ClientApp:build:production"
						}
					}
				},
				"extract-i18n": {
					"builder": "@angular-devkit/build-angular:extract-i18n",
					"options": {
						"browserTarget": "ClientApp:build"
					}
				},
				"test": {
					"builder": "@angular-devkit/build-angular:karma",
					"options": {
						"main": "src/test.ts",
						"polyfills": "src/polyfills.ts",
						"tsConfig": "tsconfig.spec.json",
						"karmaConfig": "karma.conf.js",
						"assets": [
							"src/favicon.ico",
							"src/assets"
						],
						"styles": [
							"src/styles.scss"
						],
						"scripts": []
					}
				},
				"lint": {
					"builder": "@angular-devkit/build-angular:tslint",
					"options": {
						"tsConfig": [
							"tsconfig.app.json",
							"tsconfig.spec.json",
							"e2e/tsconfig.json"
						],
						"exclude": [
							"**/node_modules/**"
						]
					}
				},
				"e2e": {
					"builder": "@angular-devkit/build-angular:protractor",
					"options": {
						"protractorConfig": "e2e/protractor.conf.js",
						"devServerTarget": "ClientApp:serve"
					},
					"configurations": {
						"production": {
							"devServerTarget": "ClientApp:serve:production"
						}
					}
				}
			}
		}
	},
	"defaultProject": "ClientApp"
}
</code></pre>

I also tried with latest node/npm (16.x).
Removed node_modules and reinstalled. 
Tried with and without `"resolutions": { "webpack": "^5.0.0" },`. 
Rebooted my PC.
I followed the Angular Update Guide (https://update.angular.io/?l=3&v=8.2-12.0) for 8.2 to 12 pretty much to the letter. After each major version upgrade I ran a build and made sure everything was working. But this problem only showed up after 11 -> 12.

**Comment by alan-agius4** [comment]
Hi @cosmoKenney, 

Can you try the following
- `rm -rf node_modules package-lock.json`
- remove `"resolutions": { "webpack": "^5.0.0" }`
- `npm i`

If the problem persists please provide the output of `npm ls source-map`.

**Comment by cosmoKenney** [comment]
@alan-agius4 looks like a version conflict with jquery: I'll dig into it in the morning. 
```
C:\Git\Compline Git\Source\ProvPubs.Compline.Web\ClientApp>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client-app@0.0.0
npm ERR! Found: jquery@3.6.0
npm ERR! node_modules/jquery
npm ERR!   jquery@"^3.4.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jquery@"^1.12.0" from jquery-sticky-table-header@1.1.1
npm ERR! node_modules/jquery-sticky-table-header
npm ERR!   jquery-sticky-table-header@"^1.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\khadd\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\khadd\AppData\Local\npm-cache\_logs\2021-05-21T06_16_38_011Z-debug.log
```

**Comment by alan-agius4** [comment]
The above looks like something unrelated to Angular

**Comment by cosmoKenney** [comment]
Yes, after fixing all the peer dependency issues in NPM the build worked fine. Thanks for the suggestion to remove package-lock.json.
