### ISSUE TITLE
Dependency injection fails silently

### ISSUE THREAD

**Issue by jzabinski** [angular/angular-cli#20898]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
When component dependency injection fails, a blank page appears with no errors, either on the page itself or the console.

## 🔬 Minimal Reproduction
See [this Stackblitz](https://stackblitz.com/edit/dep-injection-fails-silently?file=src/app/app.component.ts)

The important bit in question:
In AppComponent.ts, we have this line:
`constructor(private nonExistentSvc: AppService) {}`

`AppService` is not injected. The Injector documentation makes the impression that the injector should throw an error. Seeing that this is implicit dependency injection, I don't think that developers have a way to catch the error themselves. I think that Angular should catch the Injector error and give us a way to handle the situation.

## 🔥 Exception or Error
None. We enter The Nothing.

</code></pre>

## 🌍 Your Environment
Angular 12, all the way down

**Anything else relevant?**

**Comment by clydin** [comment]
The StackBlitz console from the link above shows the following error:
```
Error: R3InjectorError(AppModule)[AppService -> AppService -> AppService]: 
NullInjectorError: No provider for AppService!
```

**Comment by alan-agius4** [comment]
Closing as per above.
