### ISSUE TITLE
Schema validation failed with the following errors:   Data path "" must NOT have additional properties(inlineStyleLanguage).

### ISSUE THREAD

**Issue by psytonik** [angular/angular-cli#20901]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre>
Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(inlineStyleLanguage).
<code>

</code></pre>

## 🌍 Your Environment

<pre>
Angular CLI: 12.0.1
Node: 14.15.4
Package Manager: npm 7.13.0
OS: darwin x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4

<code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
It’s look like you are using an incompatible version of `@angular-devkit/build-angular`
