### ISSUE TITLE
cannot build SCSS with angular 11

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular-cli#20911]
this is a bad error I spent days on it already
```
Error: /Users/apps/mobile-app/src/app/app.component.scss /Users/apps/mobile-app/src/app/app.component.scss:1:1: Unknown word
You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser
```

I have a file located in project _workspace-utils.scss within a library easily accessible thru path access or lib path access
here is that access
`@import '~@energy/styles/lib/workspace-utils';`
ide browses to it fine 

my app.component.scss has either this
`@import 'workspace-utils';`
    OR
`@import '~@energy/styles/lib/workspace-utils';`

@include 'workspace-utils'

it refuses to compile

NgVersions
```
Angular CLI: 11.2.13
Node: 14.16.1
OS: darwin x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: <error>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cdk                    11.2.13
@angular/cli                    11.2.13
@angular/flex-layout            11.0.0-beta.33
@angular/http                   7.2.16
@angular/material               11.2.13
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.1.3
webpack                         4.46.0
```

Nx Versions 
```
Node : 14.16.1
  OS   : darwin x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : 12.3.4
  @nrwl/cli : 12.3.4
  @nrwl/cypress : 12.3.4
  @nrwl/devkit : 12.3.4
  @nrwl/eslint-plugin-nx : 12.3.4
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.4
  @nrwl/linter : 12.3.4
  @nrwl/nest : 12.3.4
  @nrwl/next : Not Found
  @nrwl/node : 12.3.4
  @nrwl/react : Not Found
  @nrwl/schematics : 8.12.11
  @nrwl/tao : 12.3.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.4
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.1.3
```

**Comment by alan-agius4** [comment]
Hi @nhhockeyplayer, 

By choosing to modify the webpack configuration you opted to no longer be on  the supported path as custom webpack configurations are not supported by the Angular tooling team. 

I suggest to file an issue on Stsckoverflow.

**Comment by nhhockeyplayer** [comment]
well less is better
I would love to ditch webpoack altogether
are you saying I dont need webpack to do anything?
if so that would be awesome

can you elaborate on what I would need to do?

Thanks

**Comment by nhhockeyplayer** [comment]
well I completely eliminated the webpack config
emptied the file out
removed the angular.json setting to run it

error still persists

I cannot even compile if I use a direct dot slash path to it either

Im looking into that other ticket now

**Comment by clydin** [comment]
The Angular CLI itself does not provide an option to use a custom webpack configuration.
If this can be reproduced with an Angular CLI project using official builders, can you try putting together a reproduction?  If not, you may need to open issues with the projects for the third-party builders in use in the project.
