### ISSUE TITLE
Update cssnano dependency to include their z-index fix for angular-cli 11

### ISSUE THREAD

**Issue by Ristaaf** [angular/angular-cli#20918]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.2.10

### Description

Same as have already been discussed and fixed (https://github.com/angular/angular-cli/issues/20905) in angular-cli 12, that does not help anyone stuck on angular-cli 11 though. So please add a fix where cssnano is updated to 5.0.4 instead of 5.0.2 which has this bug for angular-cli 11 too.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
See https://github.com/angular/angular-cli/issues/20870

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.13
Node: 10.24.1
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cdk                    11.2.13
@angular/cli                    11.2.13
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
The issue is caused by a transitive dependency of cssnano.

Please remove your `node_modules` and package lock and run `npm install` again.

**Comment by cesco69** [comment]
My build is make into docker container (gitlab-ci). Node modules are installed fresh every build.

**Comment by dragermrb** [comment]
Hi!

**@angular-devkit/build-angular@0.1102.14** depends on **cssnano@5.0.2**, so I can't install cssnano to 5.0.4 or greater.

```
Angular CLI: 11.2.14
Node: 12.22.1
OS: linux x64

Angular: 11.2.14
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.3
typescript                      4.0.7
```
