### ISSUE TITLE
Error: 'Data path "" must NOT have additional properties(styleext)' when creating a new project

### ISSUE THREAD

**Issue by musabhusaini** [angular/angular-cli#20945]
# 🐞 Bug report

### Command

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: `11.2.13`

### Description

When trying to create a new project with the CLI, an error is generated.

## 🔬 Minimal Reproduction

Create a new project using the CLI:
<pre><code>
$ ng new my-project
? Would you like to add Angular routing? No
? Which stylesheet format would you like to use? CSS
</code></pre>

## 🔥 Exception or Error

<pre><code>

Schematic input does not validate against the Schema: {"styleext":"scss","name":"app","selector":"app-root","flat":true,"path":"/src/app","skipImport":true,"project":"my-project","skipTests":false,"style":"css"}
Errors:

  Data path "" must NOT have additional properties(styleext).
</code></pre>

## 🌍 Your Environment

<pre><code>

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: linux x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... google-maps, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

I am running WSL. The same issue is not encountered on an Ubuntu machine. I managed to create a project on Ubuntu and then copied it to WSL, but `ng generate` runs into the same error.

**Comment by alan-agius4** [comment]
Likely this is caused because you have `styleext` configured In your global configuration.

You can check the global configuration by running

```
ng config -g
```

**Comment by musabhusaini** [comment]
That was it. Clearing it fixed the issue. Thanks!

**Comment by musabhusaini** [comment]
This is a breaking change from previous version. Is it documented somewhere?

**Comment by alan-agius4** [comment]
The option has been removed in version 9 https://github.com/angular/angular-cli/releases/tag/v9.0.0 and a migration was included to remove this properly.

In version 12, we fix an issue where previously additional properties invalid can be present in the configuration file.
