### ISSUE TITLE
ng new installation fails using npm 7

### ISSUE THREAD

**Issue by Ionaru** [angular/angular-cli#20941]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Unknown

 Yes, the previous version in which this bug was not present was: ....

### Description

`ng new angular-tour-of-heroes` results in an NPM error regarding the version of `jasmine-core` Angular wants and the version `karma-jasmine-html-reporter` wants when using npm 7.
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

1. Install npm 7
2. Run `ng new angular-tour-of-heroes` with all default values.

## 🔥 Exception or Error

<pre><code>
⠏ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-tour-of-heroes@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Jeroen\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jeroen\AppData\Local\npm-cache\_logs\2021-05-25T12_22_51_638Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.2.12
Node: 16.1.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.12 (cli-only)
@angular-devkit/core         11.2.12 (cli-only)
@angular-devkit/schematics   11.2.12 (cli-only)
@schematics/angular          11.2.12 (cli-only)
@schematics/update           0.1102.12 (cli-only)
</code></pre>

**Anything else relevant?**
```
npm: 7.11.2
```

Workaround:
1. Run `ng new angular-tour-of-heroes` with all default values.
2. Let the command error
3. Run `cd angular-tour-of-heroes`
4. Run `npm i --legacy-peer-deps`

**Comment by clydin** [comment]
Please update to the latest patch release for v11 (currently 11.2.13). Alternatively, v12 is also available.

**Comment by clydin** [comment]
If you are still encountering this issue after updating, please let us know.
