### ISSUE TITLE
Angular 12 Schematics not working with internal artifact repository

### ISSUE THREAD

**Issue by michaelfaith** [angular/angular-cli#20942]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: pre 12.0

### Description

We use JFrog Artifactory within our corporation for npm artifacts, and have previously made extensive use of schematics, with our internal libraries having both add and update schematics.  After updating to v12, we're now seeing schematics failing, where the cli appears to be looking for a specific file location, which is failing because the file structure is different.

`[error] HttpErrorGeneral: 404 Not Found - GET https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2fcli - not_found`

This is the actual location: `https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2Fcli%2F-%2Fcli-12.0.0.tgz`
Regular npm activities work fine, because the package info in these are correct.  Was there a change in v12 to how the cli fetches artifacts?  If we add proxy settings to our npmrc, it'll work for external libraries, but we can't do this for internally developed libraries, completely defeating our ability to build and run our own schematics internally. 

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.0
Node: 14.17.0
Package Manager: npm 6.14.4
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             12.0.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by clydin** [comment]
All registry access uses the official npm packages (`pacote`).  The first request is a request for retrieving a package's metadata from a registry and should not be generating a 404.  The Angular CLI does not directly request or download the tarball for packages.

**Comment by michaelfaith** [comment]
Looks like `ng new` is working still, but `add `and `update `are failing with that same `not_found `error.  Previously worked pre-12.  Looking at pacote, there's only a minor version change between what was working in 11 and now.  
Error for `ng add`:
`× Unable to load package information from registry: 404 Not Found - GET https://artifactory.gm.com/artifactory/api/npm/javascript/@fabric%2fcomponents - not_found`

**Comment by JoostK** [comment]
The `https://artifactory.gm.com/artifactory/api/npm/javascript/@angular%2fcli` URL looks correct to me, as an Artifactory user myself.

We have had issues with the `%2f` encoding though, because Apache blocks the encoded slashes by default as a security measure resulting in a 404. Please see http://httpd.apache.org/docs/2.0/mod/core.html#allowencodedslashes and npm/npm#11738 and there's a lot more resources on this problem. Maybe you're having a similar problem?

**Comment by michaelfaith** [comment]
@JoostK Thank you for the resources!  I was looking through stuff in the pacote repo but wasn't having luck.  This looks promising.  I'll read through and see if our config got messed up.  Really appreciate the help.
