### ISSUE TITLE
Module parsing failure on 'ng build' for SVG files in "assets"

### ISSUE THREAD

**Issue by ashvini-k123** [angular/angular-cli#20954]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

Yes, the previous version in which this bug was not present was: ^11.0.0

### Description
Build fails, the error message is misleading:

```
./node_modules/qms/core/assets/img/48x48/test.svg:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 
See https://webpack.js.org/concepts#loaders
> <svg id="Image" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 48 48">
|   <defs>
|     <linearGradient id="linear-gradient" x1="8.347" y1="12.268" x2="39.653" y2="43.573" gradientUnits="userSpaceOnUse">
```

## 🔥 Exception or Error

```
./node_modules/qms/core/assets/img/48x48/test.svg:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. 
See https://webpack.js.org/concepts#loaders
> <svg id="Image" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 48 48">
|   <defs>
|     <linearGradient id="linear-gradient" x1="8.347" y1="12.268" x2="39.653" y2="43.573" gradientUnits="userSpaceOnUse">
```

## 🌍 Your Environment

```
Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 7.13.0
OS: win32 x64

Angular: 12.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@schematics/angular             12.0.1
ng-packagr                      12.0.0
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by alan-agius4** [comment]
Is this SVG being `required`?

**Comment by ashvini-k123** [comment]
Sorry I did not follow you? Where is the required field supposed to be present?

**Comment by alan-agius4** [comment]
Is this SVG referenced in the code using `require` or imported as an ES module?

Ex: `const svg = require(‘icon.svg’);`

**Comment by ashvini-k123** [comment]
@alan-agius4 : yes, require is there for each SVG.

**Comment by alan-agius4** [comment]
This is expected see breaking changes in https://github.com/angular/angular-cli/releases/tag/v12.0.0

**Comment by clydin** [comment]
As per SemVer policy, major versions contain breaking changes.  For more information regarding SemVer policy, please see https://semver.org

**Comment by ashvini-k123** [comment]
@clydin 
> As per SemVer policy, major versions contain breaking changes. For more information regarding SemVer policy, please see https://semver.org

So then what is the way to resolve the issue am getting.
