### ISSUE TITLE
Better CLI feedback for e.g. ng serve. 

### ISSUE THREAD

**Issue by infacto** [angular/angular-cli#20957]
# 🚀 Improvement / Bug report / Feature request.

### Command

- [x] [serve](https://angular.io/cli/serve)

### Description

Just a small request: `ng serve` (and maybe all other commands) should print some text instantly after the command is executed.

![demo](https://user-images.githubusercontent.com/60390085/119680453-7cbf5e00-be41-11eb-9fa3-27d00d3dd52e.gif)

You can see that after enter `ng serve` there is a long waiting time without any response. Appears to be dead. Annoying.
I would prefer an initial message directly after the command was entered. Something like: 

```text
ng serve
Builds and serves your app, rebuilding on file changes.
[-] Generating browser bla bla ...
```

This text comes from the [docs](https://angular.io/cli/serve). But we could also just print: `Preparing...` or the joke of the day. 
Seriously, no response feedback on command execution feels weird and seems to be frozen. 

Maybe this should be implemented on all commands?

**Comment by alan-agius4** [comment]
Is the progress option disabled by any chance?

If progress, is enabled feedback should be pretty quick.

**Comment by infacto** [comment]
What exactly do you mean? I cannot find any process option. Where can I find this option? 
But I didn't do anything special. No custom configuration. `@angular/cli` and run `ng serve`. No additional parameters.

**Comment by alan-agius4** [comment]
`progress` not `process`. It’s enabled by default.

https://angular.io/cli/build.

Just want to confirm that you are not turning this

**Comment by infacto** [comment]
Sorry I also meant `progress`. Just a typo.
Now I ran `ng serve --progress`. No difference. Just a warning that "progress" is deprecated.

Following the docs:
> `--progress` Log progress to the console while building.

I already see the building output. If I run with `--progress="false"` the log is blank. See my gif record on the initial post. If `progress` is disabled there is no `Generating browser ...` line. Just the final message `Compiled successfully`.

I mean the waiting between `ng serve` and the first print `Generating browser ...`

![](https://user-images.githubusercontent.com/60390085/119680453-7cbf5e00-be41-11eb-9fa3-27d00d3dd52e.gif)
<sup>Here the same gif as in my initial post. A prove that `progress` is not disabled.</sup>

It would be great if the CLI instantly prints some text like `Preparing...` when a command is executed. Without any (complex / delayed) logic.

**Comment by eneajaho** [comment]
What @infacto is trying to say is that there is a delay between the time we execute `ng serve` and the first text shown on the terminal that something is being generated. (env: Windows)

**Comment by alan-agius4** [comment]
@infacto, I didn’t realise it was an animated GIF 😅

I have some ideas in mind which I am hoping to explore soon to tackle this issue.

**Comment by infacto** [comment]
> I didn’t realise it was an animated GIF 

Haha, exactly this is the problem here. :D
