### ISSUE TITLE
[object Object] is not a PostCSS plugin After updating to Angular 11.2.14

### ISSUE THREAD

**Issue by slavede** [angular/angular-cli#20969]
Exact issue as this one https://github.com/angular/angular-cli/issues/19839 (but it's closed for commenting so reopening it again)

I've upgraded from ng11.0.x to 11.2. and this started to happen

**Comment by alan-agius4** [comment]
Please run  the below 

```
rm -rf node_modules package-lock.json
npm i
```

**Comment by slavede** [comment]
And yeah, this solves it.

tbh, I did see this "solution" on original ticket, but really, I though it was something bigger. Thanks!
