### ISSUE TITLE
npm ERR! Could not resolve dependency: npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0

### ISSUE THREAD

**Issue by PranamBhat** [angular/angular-cli#20966]
# Bug Report

### Affected Package

 The issue is caused by package @angular-devkit/build-angular,  jasmine-core and karma

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 10/11

### Description
 

I'm using Angular version 12 globally. When I try to create a new project using "ng new project-name", it gives me error like this:

npm WARN registry Using stale data from https://lnkd.in/gycqnNB due to a request error during revalidation.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: demo@0.0.0
npm ERR! Found: jasmine-core@3.5.0
npm ERR! node_modules/jasmine-core
npm ERR! dev jasmine-core@"~3.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR! dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!

## Minimal Reproduction

 This issue comes while creating a new project on Angular 12 version.

## Exception or Error
<pre><code>

npm WARN registry Using stale data from https://lnkd.in/gycqnNB due to a request error during revalidation.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: demo@0.0.0
npm ERR! Found: jasmine-core@3.5.0
npm ERR! node_modules/jasmine-core
npm ERR! dev jasmine-core@"~3.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR! dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.2
Node: 12.18.3
Package Manager: npm 7.11.2
OS: win32 x64

Angular: 12.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.5.5
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

NA

This can be fixed replacing the "jasmine-core" and "karma" version on the "package.json" file.

1) Why it is not updating the version globally for #angular12 projects even after trying:

npm install -g karma-jasmine@latest

2) Why we have to update these versions manually?

**Comment by alan-agius4** [comment]
Hi @PranamBhat, 

Something doesn't seem right in your `ng version` output, I can see that you have `@angular-devkit/build-angular` version `0.1102.13` installed but this is not compatible with version 12. 

I am also seeing that during installation you are reiving a warning from NPM about using stale data, `npm WARN registry Using stale data from https://lnkd.in/gycqnNB due to a request error during revalidation.`

I am unable to replicate the problem using `ng new project-name`, that said I am using NPM 7.14.0.

**Comment by PranamBhat** [comment]
Step 1) 

Creating new project and I'm getting this error message:

Indhu@VAIO MINGW64 ~
$ ng new Test-Project
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
y
CREATE Test-Project/angular.json (3614 bytes)
CREATE Test-Project/package.json (1262 bytes)
CREATE Test-Project/README.md (1029 bytes)
CREATE Test-Project/tsconfig.base.json (458 bytes)
CREATE Test-Project/tsconfig.json (475 bytes)
CREATE Test-Project/tslint.json (3184 bytes)
CREATE Test-Project/.editorconfig (274 bytes)
CREATE Test-Project/.gitignore (631 bytes)
CREATE Test-Project/.browserslistrc (648 bytes)
CREATE Test-Project/karma.conf.js (1024 bytes)
CREATE Test-Project/tsconfig.app.json (292 bytes)
CREATE Test-Project/tsconfig.spec.json (338 bytes)
CREATE Test-Project/src/favicon.ico (948 bytes)
CREATE Test-Project/src/index.html (297 bytes)
CREATE Test-Project/src/main.ts (372 bytes)
CREATE Test-Project/src/polyfills.ts (2835 bytes)
CREATE Test-Project/src/styles.css (80 bytes)
CREATE Test-Project/src/test.ts (753 bytes)
CREATE Test-Project/src/assets/.gitkeep (0 bytes)
CREATE Test-Project/src/environments/environment.prod.ts (51 bytes)
CREATE Test-Project/src/environments/environment.ts (662 bytes)
CREATE Test-Project/src/app/app-routing.module.ts (246 bytes)
CREATE Test-Project/src/app/app.module.ts (393 bytes)
CREATE Test-Project/src/app/app.component.html (25757 bytes)
CREATE Test-Project/src/app/app.component.spec.ts (1077 bytes)
CREATE Test-Project/src/app/app.component.ts (216 bytes)
CREATE Test-Project/src/app/app.component.css (0 bytes)
CREATE Test-Project/e2e/protractor.conf.js (869 bytes)
CREATE Test-Project/e2e/tsconfig.json (299 bytes)
CREATE Test-Project/e2e/src/app.e2e-spec.ts (645 bytes)
CREATE Test-Project/e2e/src/app.po.ts (301 bytes)
- Installing packages...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-project@0.0.0
npm ERR! Found: jasmine-core@3.5.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Indhu\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Indhu\AppData\Local\npm-cache\_logs\2021-05-28T03_52_50_650Z-debug.log
× Package install failed, see above.
The Schematic workflow failed. See above.

Indhu@VAIO MINGW64 ~
$

**Comment by PranamBhat** [comment]
Step 2) 

When I try to do "npm install":


Indhu@VAIO MINGW64 ~/Test-Project
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-project@0.0.0
npm ERR! Found: jasmine-core@3.5.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.7.1" from karma-jasmine-html-reporter@1.6.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Indhu\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Indhu\AppData\Local\npm-cache\_logs\2021-05-28T03_55_26_450Z-debug.log

Indhu@VAIO MINGW64 ~/Test-Project
$

**Comment by PranamBhat** [comment]
Step 3)

Indhu@VAIO MINGW64 ~/Test-Project
$ ng update --all --force
The "@angular-devkit/schematics" package cannot be resolved from the workspace root directory. This may be due to an unsupported node modules structure.
Please remove both the "node_modules" directory and the package lock file; and then reinstall.
If this does not correct the problem, please temporarily install the "@angular-devkit/schematics" package within the workspace. It can be removed once the update is complete.

Indhu@VAIO MINGW64 ~/Test-Project
$ ng version
An unhandled exception occurred: ENOENT: no such file or directory, scandir 'C:\Users\Indhu\Test-Project\node_modules'
See "C:\Users\Indhu\AppData\Local\Temp\ng-3lsRgI\angular-errors.log" for further details.

Indhu@VAIO MINGW64 ~/Test-Project
$

**Comment by PranamBhat** [comment]
**Questions:**

1) Can you please tell me how to update all the packages and everything to the latest version globally? Especially the commands.

2) Can you tell me why we have to update jasmine and karma versions manually on "package.json" file? Is there a way to upgrade jasmine and karma to the latest version globally?

**Comment by alan-agius4** [comment]
> **Questions:**
> 
> 1. Can you please tell me how to update all the packages and everything to the latest version globally? Especially the commands.

In general you want to avoid installing unnecessary packages globally. Installing unnecessary packages globally is considered a bad idea for a number of reasons. Some of which are;
1) polluting the global space
2) Installing globally locks you down to a specific version
3) global packages are not declared in any package.json manifest
4) can cause weird undefined behaviour if your application needs a certain version but global you have another.

> 2. Can you tell me why we have to update jasmine and karma versions manually on "package.json" file? Is there a way to upgrade jasmine and karma to the latest version globally?

Having dependencies listed in a `package.json` is the recommended approach. Global packages should be avoided unless necessary as per above.

Regarding the errors, make sure you are using the latest version of NPM 7, older versions of NPM 7 had several issues with peer dependencies resolutions.

More information about the update command can be found in the NPM documentation: https://docs.npmjs.com/cli/v7/commands/npm-update#updating-globally-installed-packages

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by PranamBhat** [comment]
**Issue has not been resolved.** 

Why we have to update **jasmine** and **karma** versions manually on "**package.json**" file rather than updating them to the latest version globally?

**Comment by alan-agius4** [comment]
@PranamBhat, I answered this question above and explained to why using global dependencies in general is a bad idea.


> > **Questions:**
> > 
> > 1. Can you please tell me how to update all the packages and everything to the latest version globally? Especially the commands.
> 
> In general you want to avoid installing unnecessary packages globally. Installing unnecessary packages globally is considered a bad idea for a number of reasons. Some of which are;
> 
> 1. polluting the global space
> 2. Installing globally locks you down to a specific version
> 3. global packages are not declared in any package.json manifest
> 4. can cause weird undefined behaviour if your application needs a certain version but global you have another.
> 
> > 1. Can you tell me why we have to update jasmine and karma versions manually on "package.json" file? Is there a way to upgrade jasmine and karma to the latest version globally?
> 
> Having dependencies listed in a `package.json` is the recommended approach. Global packages should be avoided unless necessary as per above.
> 
> Regarding the errors, make sure you are using the latest version of NPM 7, older versions of NPM 7 had several issues with peer dependencies resolutions.
> 
> More information about the update command can be found in the NPM documentation: https://docs.npmjs.com/cli/v7/commands/npm-update#updating-globally-installed-packages
> 
> This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
