### ISSUE TITLE
1.0.0-beta.11-webpack.9-2 - apps don't run in Microsoft Edge

### ISSUE THREAD

**Issue by slubowsky** [angular/angular-cli#2097]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.9-2
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new test
cd test
ng serve
browse to localhost:4200 in edge

4. The log given by the failure. Normally this include a stack trace and some
   more information.
App never starts. Stays at Loading..
In console:
SCRIPT65535: Argument not optional
main.bundle.js (65036,13)
Which is zone.js line 556
var fetchPromise = global['fetch']();
Don't know if this is the cause or if its an unrelated issue. If debugger tools open in Chrome it stops at that line as well with same problem but after continuing the app loads successfully

5. Mention any other details that might be useful.
Uninstalled old versions of cli and ran npm cache clean first.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by slubowsky** [comment]
Still there in webpack.9-4. Didn't try a non cli app yet but don't see anything edge related in recent issues over at angular repo

**Comment by filipesilva** [comment]
Could repro myself, but it seems to be a reported zone bug: https://github.com/angular/zone.js/issues/436

Closing as there isn't anything we can do here except wait for it to get fixed there.
