### ISSUE TITLE
Option to disable JavaScript filename hashing

### ISSUE THREAD

**Issue by mcandre** [angular/angular-cli#20973]
# Feature Request

### Description

Angular randomizes filenames for the static assets, which presents difficulties for managing assets in terms of CDN's. The original intention was clearly to prevent caching, however the dynamic names make it more difficult to cache correctly and create headaches in terms of removing stale files.

### Describe the solution you'd like

Offer an option to drop hashes from the generated filenames.

Related: https://github.com/Jefiozie/ngx-aws-deploy/issues/104

**Comment by JoostK** [comment]
I think this can already be done using `--output-hashing=none`?

**Comment by alan-agius4** [comment]
Indeed as @JoostK mentioned you can use the `outputHashing` option which can be passed  via the CLI or configured on `angular.json`.

See https://angular.io/cli/build for all the options and allowed values.
