### ISSUE TITLE
Cannot build Angular 11.2.14 project due to dependency on PostCSS 8

### ISSUE THREAD

**Issue by hfournier** [angular/angular-cli#20988]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 11.2.11

### Description

 I can run the app without issue, but building it results in the error shown.

## 🔬 Minimal Reproduction

ng build
## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: PostCSS plugin postcss-discard-comments requires PostCSS 8.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.13
Node: 14.17.0
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cli                    11.2.13
@angular/google-maps            11.2.13
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Anything else relevant?**
```
npm ls postcss-discard-comments

`-- @angular-devkit/build-angular@0.1102.13
  `-- cssnano@5.0.2
    `-- cssnano-preset-default@5.1.1
      `-- postcss-discard-comments@5.0.1
```

```
npm ls postcss

+-- @angular-devkit/build-angular@0.1102.13
| +-- css-loader@5.0.1
| | `-- UNMET PEER DEPENDENCY postcss@8.3.0
| +-- UNMET PEER DEPENDENCY postcss@8.2.14
| `-- resolve-url-loader@4.0.0
|   `-- postcss@7.0.35
+-- netlify-cli@3.31.16
| `-- @netlify/zip-it-and-ship-it@4.2.1
|   `-- precinct@6.3.1
|     `-- detective-postcss@3.0.1
|       `-- postcss@7.0.35
`-- netlify-schematics@3.2.0
  `-- netlify-cli@2.71.0
    `-- @netlify/zip-it-and-ship-it@2.7.1
      `-- precinct@6.3.1
        `-- detective-postcss@3.0.1
          `-- postcss@7.0.35  deduped

npm ERR! peer dep missing: postcss@^8.1.0, required by autoprefixer@10.2.4
npm ERR! peer dep missing: postcss@^8.2.1, required by cssnano@5.0.2
npm ERR! peer dep missing: postcss@^8.0.0, required by postcss-import@14.0.0
npm ERR! peer dep missing: postcss@^8.1.0, required by icss-utils@5.1.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-extract-imports@3.0.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-local-by-default@4.0.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-scope@3.0.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-values@4.0.0
```
As you can see above, resolve-url-loader@4.0.0 is referencing postcss@7.0.35
I've [reported the issue](https://github.com/netlify/zip-it-and-ship-it/issues/477) to @netlify/zip-it-and-ship-it as well

**Comment by clydin** [comment]
Can you provide the package manager (and version) that is being used with the project?

**Comment by hfournier** [comment]
npm: 6.14.7

**Comment by clydin** [comment]
If you haven't already, can you try deleting both the `node_modules` directory and the `package-lock.json` file then reinstalling?

**Comment by hfournier** [comment]
Did that already. Prior to that, I was getting this error:
```
Error: [object Object] is not a PostCSS plugin
```

**Comment by clydin** [comment]
Using npm 6 with a newly created 11.2.13 project, there are no build errors and the output of `npm ls postcss` contains no errors:
```
└─┬ @angular-devkit/build-angular@0.1102.13
  ├─┬ css-loader@5.0.1
  │ └── postcss@8.2.14  deduped
  ├── postcss@8.2.14
  └─┬ resolve-url-loader@4.0.0
    └── postcss@7.0.35
```

Running `ng add netlify-schematics` in the project also did not lead to any build errors and the output of `npm ls postcss` also did not contain any errors:
```
├─┬ @angular-devkit/build-angular@0.1102.13
│ ├─┬ css-loader@5.0.1
│ │ └── postcss@8.2.14  deduped
│ ├── postcss@8.2.14
│ └─┬ resolve-url-loader@4.0.0
│   └── postcss@7.0.35
└─┬ netlify-schematics@3.2.0
  └─┬ netlify-cli@2.71.0
    └─┬ @netlify/zip-it-and-ship-it@2.7.1
      └─┬ precinct@6.3.1
        └─┬ detective-postcss@3.0.1
          └── postcss@7.0.35
```

Then installing the `netlify-cli` package (`npm i -D netlify-cli`), also resulted in no build errors and the output of `npm ls postcss` also did not contain any errors:
```
├─┬ @angular-devkit/build-angular@0.1102.13
│ ├─┬ css-loader@5.0.1
│ │ └── postcss@8.2.14  deduped
│ ├── postcss@8.2.14
│ └─┬ resolve-url-loader@4.0.0
│   └── postcss@7.0.35
├─┬ netlify-cli@3.31.16
│ └─┬ @netlify/zip-it-and-ship-it@4.2.1
│   └─┬ precinct@6.3.1
│     └─┬ detective-postcss@3.0.1
│       └── postcss@7.0.35
└─┬ netlify-schematics@3.2.0
  └─┬ netlify-cli@2.71.0
    └─┬ @netlify/zip-it-and-ship-it@2.7.1
      └─┬ precinct@6.3.1
        └─┬ detective-postcss@3.0.1
          └── postcss@7.0.35
```

This, unfortunately, does not appear reproducible and appears to be a package manager based problem.

**Comment by hfournier** [comment]
Problem solved.

Your steps prompted me to check the package.json file, where I found netlify-cli was under dependencies, instead of devDependencies. I must have missed the -D flag when I updated the package. I moved it and now all is well. 

Thank you.
