### ISSUE TITLE
Update dependency worker-plugin from 5.0.0 to 5.0.1

### ISSUE THREAD

**Issue by AntonyChiossi** [angular/angular-cli#20986]
Hi,
this affects versions <= 10.x.x as the package `@angular-devkit/build-angular` have the `worker-plugin` as dependency.

this cause some problems (with no work around available) as described in comments:
https://github.com/GoogleChromeLabs/worker-plugin/pull/94

Is it possible to have the dependency updated for such versions?

**Comment by alan-agius4** [comment]
Versions 9-11 are currently in LTS and only security fixes are merged.

To avail from the latest features and bug fixes please update to the latest version of Angular CLI.

More information: https://angular.io/guide/releases#lts-fixes
