### ISSUE TITLE
Angular 12 is much slower in compiling (production and watch mode) then Angular 11 

### ISSUE THREAD

**Issue by jcompagner** [angular/angular-cli#20989]
see the difference in numbers on my machine
i uploaded our source, it has package.json and angular.json which are the Angular 11 variants
and besides that i have package_12.json and angular_12.json which are the Angular 12 variants

[testcase.zip](https://github.com/angular/angular-cli/files/6563278/testcase.zip)

if i run first the 11: (after npm install)

"npm run build":
first build:  169988ms, 
second, third: 49566ms , 50352ms

"npm run build_debug" 
fist compile: 47827ms (no second, double compile)
open src\sablo\sablo.service.ts and just touch that file, like adding a new line in the constructor: 6697ms
remove the new line and save: 2796ms

overwrite the 2 files with the 12 variants (maybe in another dir, or delete node_modules and package json to start clean)

"npm run build":
first build : 169705ms
second,third : 103724ms, 102353ms

"npm run build_debug":
first compile:  51265ms (but double compile right after that, that takes: 12821ms)

open src\sablo\sablo.service.ts and just touch that file, like adding a new line in the constructor: 9320ms
remove the new line and save: 8443ms

so it is all really quite a bit slower, production builds more then double! (except for some reason the first compile where ngcc compiles all the packages)
But also for development the watch mode is quite annoying..

**Comment by alan-agius4** [comment]
Hi @jcompagner,

Thanks for reporting these issues, however these are already known issues.

Kindly subscribe to:
https://github.com/angular/angular-cli/issues/20891
https://github.com/angular/angular-cli/issues/20792
