### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by nadirowski** [angular/angular-cli#2099]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  
Windows 10.

2. Versions. 
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.3.1
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Migrated application from previous angular-cli to angular-cli@webpack,
Migrated application from angular2-rc4 to angular-rc5

4. The log given by the failure. Normally this include a stack trace and some
   more information.

`VM627:11Uncaught ReferenceError: require is not defined(anonymous function) @ VM627:11e.exports @ scripts.4c654bc….bundle.js:1460 @ scripts.4c654bc….bundle.js:1__webpack_require__ @ inline.js:1888 @ scripts.4c654bc….bundle.js:1__webpack_require__ @ inline.js:1window.webpackJsonp @ inline.js:1(anonymous function) @ scripts.4c654bc….bundle.js:1`

5. Mention any other details that might be useful.

I'm trying to create a production bundle that will be served by nginx by doing` ng build --env=tst --target=production`
Development environment working fine when using `ng serve`

Snippet from my package.json

```
 "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Can you try migrating your apps following the newer instructions? https://github.com/angular/angular-cli#webpack-update

**Comment by nadirowski** [comment]
I still get the same problem in the log but suprisingly, the app works correctly...
Strange.

**Comment by nponiros** [comment]
From what I understand the angular2-template-loader (a webpack loader) replaces the templateUrl/stylesUrl with template/styles using require to load the needed file. You will notice there is no .css/.html in the build directory other than index.html. Since the TypeScript compiler does not know "require" you get that error.

An easy fix is to install types for node via `npm install --save-dev @types/node`
