### ISSUE TITLE
Angular 12: [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021.

### ISSUE THREAD

**Issue by pcaversaccio** [angular/angular-cli#20995]
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular version `11.0.7`.

### Description

 After building and serving an Angular 12 project via GitLab Pages, I get the following warning in my console:
```
[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
```

## 🔬 Minimal Reproduction
Create a simple new angular application, build it with configuration `production` and serve it on an external server. My current application is hosted (via `http` only) [here](https://swissdlt.appswithlove.site/swissdlt-faucet-frontend/). If further information is required I can make the specific repo public.

## 🌍 Your Environment
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.2
Node: 16.0.0
Package Manager: npm 7.14.0
OS: win32 x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4
```

**Anything else relevant?**
All the common browsers are affected: Microsoft Edge, Brave, Google Chrome.

**Comment by pcaversaccio** [comment]
Temporary solution: Just run `npm update`. However, this broke some other dependencies which are not directly related to the Angular CLI.

**Comment by alan-agius4** [comment]
Hi @pcaversaccio, 

Thanks for reporting this issue, however this is not caused by Angular. Angular framework doesn't use `SharedArrayBuffer`. This is likely caused by one of your 3rd party dependencies which dependent on `SharedArrayBuffer`.
