### ISSUE TITLE
cli not installing in my machine 

### ISSUE THREAD

**Issue by ISMIALKHAN17** [angular/angular-cli#20994]
Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

Getting this error please help

**Comment by alan-agius4** [comment]
The above is warning and shouldn’t cause the installation to fail.

**Comment by joyjoice** [comment]
gfg

**Comment by ISMIALKHAN17** [comment]
Sir how can i solve this error

**Comment by alan-agius4** [comment]
That is a warning, which can be ignored as it's not actionable from your end.

Also, make sure you are using the latest version of the Angular CLI.

```
npm i -g @angular/cli
```

**Comment by ISMIALKHAN17** [comment]
Thank you  sir I am a beginner I just started learning angular

**Comment by NishaWaikar** [comment]
Pls help here.....
npm install -g @angular/cli
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 234 packages, and audited 235 packages in 47s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

This is not working for me as well...
'ng' is not recognized as an internal or external command,
operable program or batch file.

**Comment by b4dm00n** [comment]
same =(

**Comment by fury02** [comment]
Install error ->

npm install -g @angular/cli@12.0.3
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! Unexpected end of JSON input while parsing near '...org\r\n\r\nwsFcBAEBCA'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fury/.npm/_logs/2021-06-06T12_27_27_109Z-debug.log

**Comment by ISMIALKHAN17** [comment]
That is a warning, which can be ignored as it's not actionable from your
end.

Also, make sure you are using the latest version of the Angular CLI.

npm i -g @angular/cli

**Comment by ISMIALKHAN17** [comment]
> Pls help here.....
> npm install -g @angular/cli
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> 
> changed 234 packages, and audited 235 packages in 47s
> 
> 23 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> This is not working for me as well...
> 'ng' is not recognized as an internal or external command,
> operable program or batch file.
> 

That is a warning, which can be ignored as it's not actionable from your end.

Also, make sure you are using the latest version of the Angular CLI.

npm i -g @angular/cli
