### ISSUE TITLE
ng-new <project_name> command is not creating e2e folder

### ISSUE THREAD

**Issue by ashishkumar00071** [angular/angular-cli#20991]
I am trying to setup new angular project.
The package.json has following angular dependencies:
"@angular/animations": "~12.0.1",
    "@angular/common": "~12.0.1",
    "@angular/compiler": "~12.0.1",
    "@angular/core": "~12.0.1",

The project structure does not have e2e folder in it.

**Comment by alan-agius4** [comment]
This is expected, since version 12 we no longer add protractor to newly created  projects.

See: https://github.com/angular/protractor/issues/5502
