### ISSUE TITLE
Angular 12 WebWorker not working it seems

### ISSUE THREAD

**Issue by mrudangit** [angular/angular-cli#20993]
# Bug Report

### Affected Package

angular/cli

### Is this a regression?
Yes works fine in Angular 11 

### Description
Adding webworker ng generate web-worker app
ng serve and use web worker 
WebWorker is not working in network tab  getting 404 for test.worker.ts 

## Minimal Reproduction
https://github.com/mrudangit/Angular12WebWorker

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 12.0.2
Node: 15.2.0
Package Manager: npm 7.0.8
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.2 (cli-only)
@angular-devkit/core         12.0.2 (cli-only)
@angular-devkit/schematics   12.0.2 (cli-only)
@schematics/angular          12.0.2 (cli-only)

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Due to the introduction of Webpack 5 in Angular v12, the syntax for referencing worker files has changed as follows:
Before: `new Worker('./app.worker', ...)`
After: `new Worker(new URL('./app.worker', import.meta.url), ...)`

Please try adjusting the syntax as shown above.

**Comment by mrudangit** [comment]
Thanks @clydin  , works like a charm, I guess Angular docs needs to be updated I checked https://angular.io/guide/web-worker
but it has old documentation. 

Thanks again

**Comment by mrudangit** [comment]
However documentation is correct  I see
if (typeof Worker !== 'undefined') {
  // Create a new
  const worker = new Worker(new URL('./app.worker', import.meta.url));
  worker.onmessage = ({ data }) => {
    console.log(`page got message: ${data}`);
  };
  worker.postMessage('hello');
} else {
  // Web workers are not supported in this environment.
  // You should add a fallback so that your program still executes correctly.
}

After changing  Angular version 


![image](https://user-images.githubusercontent.com/3153622/120118668-ae963480-c161-11eb-8133-3704a24482b5.png)
