### ISSUE TITLE
Angular build not creating dist folder on production

### ISSUE THREAD

**Issue by babarinde** [angular/angular-cli#21004]
# Bug Report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
 A clear and concise description of the problem...
When building an angular app using a Dockerfile,  ng build --configuration production does not always create a dist folder
my output path is defined as "outputPath": "./dist", in angular.json

## Minimal Reproduction

 https://stackblitz.com/...

## Exception or Error
<pre><code>

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.1
Node: 12.16.3
Package Manager: npm 7.15.0
OS: linux x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@schematics/angular             11.2.13
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This is presumably due to #20985.

**Comment by babarinde** [comment]
Downgrading  `"@angular-devkit/build-angular": "12.0.0"`  as suggested [here](https://github.com/nrwl/nx/issues/5729), solves this in the interim

**Comment by alan-agius4** [comment]
Duplicate of #20985.

**Comment by babarinde** [comment]
@alan-agius4, Thanks,
However, that posted downgrade did not work, The problem with this issue is that sometimes the dist folder is created sometimes it is not. coincidentally a  downgrade at that time seemed to be the reason why the dist folder was created, subsequent deployments DID NOT create the dist folder.
Marking this as a duplicates assumes you know what is wrong, but I am honestly clueless about the referred issue. This issue was only created out of our frustrations building and deploying angular to staging and production servers as we could not reliably guarantee that all docker images built and deployed had the dist folder in them.

**Comment by alan-agius4** [comment]
@babarinde, In that case, let me re-open the issue, but we'd require a reproduction to investigate this any further.

**Comment by babarinde** [comment]
Upon further investigations, we noticed that its possible the server building the docker image may have been running out of memory at the point it should have created the dist folder. When we increase memory on server it builds with the dist folder and our deployments are fine.
