### ISSUE TITLE
Copy `ng update` output to clipboard and create a concatenated command option

### ISSUE THREAD

**Issue by twerske** [angular/angular-cli#21014]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The most common action after `ng update` is to copy the commands to the clipboard (and sometimes concatenate them into a single command). It'd be great if the cli could copy the command output to the computer clipboard and concat the commands as a streamlined option for updating.

### Describe the solution you'd like

```
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       11.0.0-rc.0 -> 12.0.2    ng update @angular/cdk
      @angular/cli                       11.0.0-rc.1 -> 12.0.2    ng update @angular/cli
      @angular/core                      11.0.0-rc.1 -> 12.0.2    ng update @angular/core
      @angular/material                  11.0.0-rc.0 -> 12.0.2    ng update @angular/material
     --------------------------------------------------------------------------------
      all                                * -> 12.0.2              ng update @angular/cdk @angular/cli @angular/core @angular/material
    
    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.
```

And `ng update @angular/cdk` OR `ng update @angular/cdk @angular/cli @angular/core @angular/material` is copied to my local clipboard

**Comment by alan-agius4** [comment]
@twerske, updating multiple packages at once is not recommended and should be avoided were possible.

The main reason for this is if there is an build or runtime error it will be harder to identify which update caused it. In addition considering that certain updates perform a large set of code mods it would be hard to go through the changes and validate the changes if needed.

**Comment by alan-agius4** [comment]
Copying to clipboard without an user action would be unexpected and IMHO doesn’t provide a good DX.

Copying to clipboard in node, is also non-trivial considering all OS.

**Comment by twerske** [comment]
> @twerske, updating multiple packages at once is not recommended and should be avoided were possible.
> 
> The main reason for this is if there is an build or runtime error it will be harder to identify which update caused it. In addition considering that certain updates perform a large set of code mods it would be hard to go through the changes and validate the changes if needed.

This makes sense

> Copying to clipboard in node, is also non-trivial considering all OS.

Closing as non trivial and unrecommended
