### ISSUE TITLE
Karma-coverage not generating coverage reports for large projects.

### ISSUE THREAD

**Issue by cklogs** [angular/angular-cli#21015]
Hi there,

I am posting an issue here in the core repo because I have not received feedback from any maintainers on karma-coverage since posting [this issue](https://github.com/karma-runner/karma-coverage/issues/434) earlier this year.

Because of this deprecation warning, teams such as ours with relatively large test suites are nervous that we'll eventually lose coverage reports once karma-coverage-instanbul-reporter is no longer supported. 
![image](https://user-images.githubusercontent.com/10749074/120241095-ec08c980-c216-11eb-8859-aecc38075e9b.png)

Please advise on how to proceed and if this issue can be elevated to the core team's triaging.

**Comment by dgp1130** [comment]
Hey @cklogs, this is a tough situation to be stuck in. Unfortunately this seems like mostly a `karma-coverage` issue, so we hope they are able to give some direction on how to fix your particular problem which would be the ideal solution here.

We are planning to support just `karma-coverage` in the CLI and want to stick with official solutions as best we can. We don't want to continue supporting two test coverage solutions long term and our hope is that `karma-coverage` will be able to provide the necessary user support.

In the mean time, there's nothing actionable on this from the Angular side, so I'm closing this issue.
