### ISSUE TITLE
ng update _resolveFilename error on Windows with CLI 12.0.3

### ISSUE THREAD

**Issue by simeyla** [angular/angular-cli#21027]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

### Description

I updated @angular/core earlier today on Windows to 12.0.3 and just noticed a second update to CLI for the corresponding version.

However, when running `ng update` I get this error:

![image](https://user-images.githubusercontent.com/3656278/120559179-68d1aa00-c3b5-11eb-85c1-de39889e35b5.png)

This is clearly some kind of filename concatanation issue that is affecting Windows paths.

## 🔬 Minimal Reproduction

Just run `ng update`. The project in question is just a stub application generated with `ng new` from 12.0.2.

I deleted `node_modules` and reinstalled just to be sure.

## 🔥 Exception or Error

<pre><code>
PS C:\temp\angular12\angular12> ng update
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
√ Package successfully installed.
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module 'C:\temp\angular12\angular12\'C:\Users\SimonWeaver\AppData\Local\Temp\angular-cli-packages-nLDj0k\node_modules\@angular\cli\bin\ng''
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
PS C:\temp\angular12\angular12>
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.2
Node: 12.16.0
Package Manager: npm 6.10.3
OS: win32 x64

Angular: 12.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4</code></pre>

**Comment by simeyla** [comment]
Running a complete clean fixed the problem:

> npm cache clean --force

  * delete **node_modules**
  * delete **package-lock.json**
     
>npm install

I did not then get the error about needing to install a temporary package manager.

PS S:\tfs\rr\Defender.NG> ng update
Using package manager: 'npm'
Collecting installed dependencies...
Found 118 dependencies.
    We analyzed your package.json and everything seems to be in order. Good work!

I don't however know if there is actuall an issue with the CLI or not, just that this is a workaround. This happened on two projects so maybe there was a regression in 12.0.2 meaning that when it attempted to install 12.0.3 it failed (even though 12.0.3 had no actual code changes in itself).

**Comment by simeyla** [comment]
@alan-agius4 thanks for getting to this so quickly. 

Are you able to offer any insight on what others will have to do to fix this if they encounter it. I didn't get to delve into too much detail myself.

Would it mean that anyone on 12.0.2 on Windows would need to 'clean' out their project to be able to get a new update (including this one). 

Would a better workaround have been just to update my `package.json` manually to 12.0.3 - at which point `ng update` has nothing to update so it succeeds? Thx.

**Comment by alan-agius4** [comment]
As a workaround you can also install the latest version of the CLI globally.

```
npm i -g @angular/cli
```

**Comment by Heatmanofurioso** [comment]
Running a complete clean did not fix the issue on my end

**Comment by elvisbegovic** [comment]
@Heatmanofurioso, & make temp change like @alan-agius4 did in fix ? 
replace `Line 151 .\node_modules\@angular\cli\utilities\install-package.js`
by ```const argv = [`'${binPath}'`, ...args];```

**Comment by Heatmanofurioso** [comment]
@elvisbegovic That seemed to do the trick! Thanks
