### ISSUE TITLE
Web workers not working in a multiple project workspace

### ISSUE THREAD

**Issue by aleGuardiola** [angular/angular-cli#21050]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know

### Description

Using: ng generate web-worker, not working in a multiple project workspace

## 🔬 Minimal Reproduction

ng new my-app --> create a new app
...
cd my-app
ng g application another-app --> create another project
cd projects/another-app --> go inside the new project
ng generate web-worker app --> generate a web worker and adds the configuration
ng build --> build the project

## 🔥 Exception or Error

The web worker bundle is not in the build for the project

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.3
Node: 14.15.5
Package Manager: npm 6.14.11
OS: win32 x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.3
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.3
@angular-devkit/schematics      12.0.3
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by mruffieux** [comment]
Hey @aleGuardiola, it works fine here. You may be missing something. Try to tell the CLI the name of your project using the `--project` flag:

`ng g web-worker --project your-project-name`

You can do it from the root folder, you don't have to go inside the project 👍

**Comment by aleGuardiola** [comment]
Thank you very much, that worked. Closing the issue.
