### ISSUE TITLE
Bad character in module's routing file

### ISSUE THREAD

**Issue by mxii** [angular/angular-cli#2105]
See this comment here: https://github.com/angular/angular-cli/commit/ba668a8862725f894da3f9608871756507096bb9#commitcomment-18977226 from @intellix 

at this line: https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/module/files/__path__/__name__.routing.ts#L5

`RouterModule.forChild(<%= camelizedModuleName %>˝Routes);`

There is this character **˝** to much! :)

**Comment by mxii** [comment]
#2107

**Comment by elvirdolic** [comment]
export const testRouting = RouterModule.forChild(test˝Routes);
results in ng g module test --routing
