### ISSUE TITLE
ng new fails under CLI 12.0.3

### ISSUE THREAD

**Issue by fmorriso** [angular/angular-cli#21072]
# 🐞 Bug report

### Command (mark with an `x`)

- [ x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 12.0.2

### Description

 A clear and concise description of the problem...
ng new using version 12.0.3 results in unresolved dependency which appears to be caused lack of an entry in a JSON file for CLI version 12.0.3
## 🔬 Minimal Reproduction
1. npm i -g @angular/cli   <-- make sure it is 12.0.3
2. ng new aacli-v1203 --routing --style=scss

## 🔥 Exception or Error

<pre><code>

Could not resolve dependency:
peer @angular/compiler-cli@"^12.0.0" from @angular-devkit/build-angular@12.0.3
node_modules/@angular-devkit/build-angular
  dev @angular-devkit/build-angular@"~12.0.3" from the root project
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.3
Node: 14.17.0
Package Manager: npm 7.16.0
OS: win32 x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.3 (cli-only)
@angular-devkit/core         12.0.3 (cli-only)
@angular-devkit/schematics   12.0.3 (cli-only)
@schematics/angular          12.0.3 (cli-only)
  
</code></pre>

**Anything else relevant?**

Windows 10 Pro version 21H1 (OS Build 19043.1023)
[eresolve-report.txt](https://github.com/angular/angular-cli/files/6609428/eresolve-report.txt)

**Comment by alan-agius4** [comment]
Something doesn’t add up, by looking at the log file it appears that the dist-tags and versions are not in sync with the public NPM registry.

```
        "name": "@angular/compiler-cli",
        "distTags": {
          "latest": "12.0.2",
          "v4-lts": "4.4.7",
          "v5-lts": "5.2.11",
          "next": "12.1.0-next.3",
          "v7-lts": "7.2.15",
          "v6-lts": "6.1.10",
          "v9-lts": "9.1.13",
          "v8-lts": "8.2.14",
          "v10-lts": "10.2.5",
          "v11-lts": "11.2.14"
        },

```

Example, 12.0.2 for `@angular/compiler-cli` is marked as latest, but is isn’t correct as 12.0.3 is the latest  https://www.npmjs.com/package/@angular/compiler-cli

If you are using an NPM proxy, make sure that is synced with the public registry.

Closing as this is not actionable by the Angular team.

**Comment by fmorriso** [comment]
On a hunch, I performed the following, which allowed ```ng new``` to work correctly:
```
npm i - g @angular/cli@latest --force
```
