### ISSUE TITLE
Angular CLI not asking for strict mode enable or disable when creating a new project

### ISSUE THREAD

**Issue by lakindu2002** [angular/angular-cli#21077]
After upgrading to Angular 12, the cli doesn't ask me if i should enable strict mode and uses it by default. Is there any way to create a project without using strict mode?

**Comment by alan-agius4** [comment]
You can you the `—no-strict` option.

See: https://angular.io/cli/new

**Comment by lakindu2002** [comment]
Thank you

**Comment by lakindu2002** [comment]
However, the `no-strict` flag is not available on the Angular Documentation. It would be great if it was added to the official docs.
