### ISSUE TITLE
ng build Not Building in Production Mode by Default in Angular 12

### ISSUE THREAD

**Issue by mylifeandcode** [angular/angular-cli#21073]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 In Angular 12, running ng build now defaults to production, but that's not the behavior we're seeing.

### Description

After upgrading to Angular 12, I removed the _--prod_  arguments from custom npm scripts because production is the new default. But later, we found out that running these scripts, or even just _ng build_ was resulting in a _dev_ build, with no replacement of environment.ts with environment.prod.ts, and unminified output.

## 🔬 Minimal Reproduction

- Upgrade an application from Angular 11 to 12. 
- Run _ng build_.
- Observe output in dist folder. For example, there will be a _main.js_ file (instead of one with a hashed filename), and the contents will not be minified. It will also contain values from _environment.ts_ instead of _environment.prod.ts_.

## 🔥 Exception or Error
No exceptions.

## 🌍 Your Environment
<pre><code>

Angular CLI: 12.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/cdk                    8.2.3
@angular/cli                    12.0.1
@angular/http                   7.2.16
@schematics/angular             12.0.1
ng-packagr                      12.0.2
rxjs                            6.6.3
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

Here are the npm scripts from package.json in question (in bold):
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    **"build": "ng build",**
    "watch": "ng build --watch --configuration development",
    **"build-all": "ng build esa-service-lib && ng build esa-ui-lib && ng build",**

I have also attached my angular.json file (renamed _angular.json.txt)._ I needed to add _development_ configuration after the upgrade to allow for non-production builds.
[angular.json.txt](https://github.com/angular/angular-cli/files/6609551/angular.json.txt)

**Comment by clydin** [comment]
Production is the default for newly created projects in v12. However, due to the varying complexity of existing projects and the potentially for breakage of non-trivial build setups, automatic migration to production by default is not performed.
For users that would like to use production by default in existing projects, an opt-in migration is provided which may be executed via `ng update @angular/cli --migrate-only production-by-default` after updating to v12.

**Comment by mylifeandcode** [comment]
Hi @clydin ! Thanks for the quick response. I now notice the optional migration in the upgrade guide. It might be a good idea to make some quick clarifications to these two documents to avoid confusion:

- https://angular.io/guide/updating-to-version-12 : This document states "ng build now produces production bundle by default."
- https://blog.angular.io/angular-v12-is-now-available-32ed51fbfd49 : This document states "Running ng build now defaults to production which saves teams some extra steps and helps to prevent accidental development builds in production!"

Thanks again for getting back to me so quickly. I'll go ahead and close this issue.

**Comment by clydin** [comment]
Good point on the documentation. I'll forward the suggestions on to the documentation team.

**Comment by mylifeandcode** [comment]
Thanks again @clydin for the quick response!

**Comment by wratho** [comment]
thank you for this post. though how has this not been updated yet. it's been a week.... this is bound to cause more harm than anything else. you literally have a compiler warning encouraging people to change their builds. Reading the release notes was more harmful than ever this time...
