### ISSUE TITLE
HookWebpackError: ENOENT: no such file or directory, scandir     at makeWebpackError \node_modules\webpack\lib\HookWebpackError.js

### ISSUE THREAD

**Issue by jneves92** [angular/angular-cli#21087]
```
"dependencies": {
    "@angular/animations": "12.0.2",
    "@angular/cdk": "12.0.2",
    "@angular/common": "12.0.2",
    "@angular/compiler": "12.0.2",
    "@angular/core": "12.0.2",
    "@angular/forms": "12.0.2",
    "@angular/platform-browser": "12.0.2",
    "@angular/platform-browser-dynamic": "12.0.2",
    "@angular/platform-server": "12.0.2",
    "@angular/router": "12.0.2",
    "@auth0/angular-jwt": "5.0.2",
....
...
 },
  "devDependencies": {
    "@angular-devkit/build-angular": "12.0.2",
    "@angular-eslint/builder": "12.1.0",
    "@angular-eslint/eslint-plugin": "12.1.0",
    "@angular-eslint/eslint-plugin-template": "12.1.0",
    "@angular-eslint/schematics": "12.1.0",
    "@angular-eslint/template-parser": "12.1.0",
    "@angular/cli": "12.0.2",
    "@angular/compiler-cli": "12.0.2",
    "@angular/language-service": "12.0.2",
    "@types/node": "15.0.2",
    "@typescript-eslint/eslint-plugin": "4.26.0",
    "@typescript-eslint/parser": "4.26.0",
    "eslint": "7.28.0",
    "eslint-plugin-import": "2.23.4",
    "eslint-plugin-jsdoc": "35.1.3",
    "eslint-plugin-prefer-arrow": "1.2.3",
    "ts-node": "9.1.1",
    "typescript": "4.0.7",
    "webpack-bundle-analyzer": "4.4.2"
  }
```

└─┬ @angular-devkit/build-angular@12.0.2
  ├─┬ @angular-devkit/build-optimizer@0.1200.2
  │ └── webpack@5.36.2 deduped
  ├─┬ @angular-devkit/build-webpack@0.1200.2
  │ └── webpack@5.36.2 deduped
  ├─┬ @ngtools/webpack@12.0.2
  │ └── webpack@5.36.2 deduped
  ├─┬ babel-loader@8.2.2
  │ └── webpack@5.36.2 deduped
  ├─┬ circular-dependency-plugin@5.2.2
  │ └── webpack@5.36.2 deduped
  ├─┬ copy-webpack-plugin@8.1.1
  │ └── webpack@5.36.2 deduped
  ├─┬ css-loader@5.2.4
  │ └── webpack@5.36.2 deduped
  ├─┬ css-minimizer-webpack-plugin@3.0.0
  │ └── webpack@5.36.2 deduped
  ├─┬ less-loader@8.1.1
  │ └── webpack@5.36.2 deduped
  ├─┬ mini-css-extract-plugin@1.5.1
  │ └── webpack@5.36.2 deduped
  ├─┬ postcss-loader@5.2.0
  │ └── webpack@5.36.2 deduped
  ├─┬ raw-loader@4.0.2
  │ └── webpack@5.36.2 deduped
  ├─┬ sass-loader@11.0.1
  │ └── webpack@5.36.2 deduped
  ├─┬ source-map-loader@2.0.1
  │ └── webpack@5.36.2 deduped
  ├─┬ style-loader@2.0.0
  │ └── webpack@5.36.2 deduped
  ├─┬ stylus-loader@5.0.0
  │ └── webpack@5.36.2 deduped
  ├─┬ terser-webpack-plugin@5.1.2
  │ └── webpack@5.36.2 deduped
  ├─┬ webpack-dev-middleware@4.1.0
  │ └── webpack@5.36.2 deduped
  ├─┬ webpack-dev-server@3.11.2
  │ ├─┬ webpack-dev-middleware@3.7.3
  │ │ └── webpack@5.36.2 deduped
  │ └── webpack@5.36.2 deduped
  ├─┬ webpack-subresource-integrity@1.5.2
  │ └── webpack@5.36.2 deduped
  └── webpack@5.36.2

![image](https://user-images.githubusercontent.com/25101766/121223906-ebf47380-c87f-11eb-96bc-836a0ec2aa01.png)

After migrating from angular 11 to 12 started to give this error.

**Comment by alan-agius4** [comment]
Can you please try the following?

```
rm -rf node_modules package-lock.json
npm i
```

if the problem persists please provide a minimal reproduction.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Closing due to lack of feedback from the issue author.
