### ISSUE TITLE
Unable to create a new project with ng new

### ISSUE THREAD

**Issue by Manmay** [angular/angular-cli#2109]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.10
node: 4.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Unable to create a new project with ng new command.
It is failing during the postinstall phase with the following error.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
typings ERR! message https://api.typings.org/entries/dt/jasmine/tags/2.2.0%2B201
60621224255 responded with 409, expected it to equal 200
typings ERR! cwd d:\develop\xxx\angular2\hello-world2
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "c:\\install\\node\\node.exe" "d:\\develop\\xxx\\angu
lar2\\hello-world2\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v4.5.0
typings ERR! typings -v 1.3.1
typings ERR! code EINVALIDSTATUS
typings ERR! If you need help, you may report this error at:

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by suryashekhawat** [comment]
Update your node version and give a try

**Comment by filipesilva** [comment]
Seems to be a connection problem of sorts on `typings`. I suggest upgrading to the latest version, as it doesn't use typings at all.
