### ISSUE TITLE
Found: @angular/cdk@undefined

### ISSUE THREAD

**Issue by seb-mtl** [angular/angular-cli#21136]
# 🐞 Bug report

I am updating to angular `11.2.14` and receive the following error.

## 🔥 Exception or Error

```
npm ERR! Found: @angular/cdk@undefined
npm ERR! node_modules/@angular/cdk
npm ERR!   dev @angular/cdk@"^11.2.14" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/cdk@"^11.0.0" from @angular/flex-layout@11.0.0-beta.33
npm ERR! node_modules/@angular/flex-layout
npm ERR!   dev @angular/flex-layout@"11.0.0-beta.33" from the root project
```

The error was reported once in #10167 but was closed due to the lack of feedback.

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.1.0

### Description

Content of `package.json`:

```
    "@angular-builders/custom-webpack": "11.2.14",
    "@angular-devkit/build-angular": "11.2.14",
    "@angular/animations": "11.2.14",
    "@angular/cdk": "^11.2.14",
    "@angular/cli": "11.2.14",
    "@angular/common": "11.2.14",
    "@angular/compiler": "11.2.14",
    "@angular/compiler-cli": "11.2.14",
    "@angular/core": "11.2.14",
    "@angular/flex-layout": "11.0.0-beta.33",
    "@angular/forms": "11.2.14",
    "@angular/language-service": "11.2.14",
    "@angular/material": "11.2.14",
    "@angular/platform-browser": "11.2.14",
    "@angular/platform-browser-dynamic": "11.2.14",
    "@angular/router": "11.2.14",
```

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.4
Node: 16.2.0
Package Manager: npm 7.15.0
OS: darwin arm64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core
... flex-layout, forms, language-service, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.0.4 (cli-only)
@angular-devkit/schematics      12.0.4 (cli-only)
@angular/cli                    12.0.4 (cli-only)
@schematics/angular             12.0.4 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>
webpack                         <error>
</code></pre>

**Comment by alan-agius4** [comment]
Can you please run `npm ls @angular/cdk`?

**Comment by seb-mtl** [comment]
I deleted the `node_modules` directory and installed the packages from scratch. The issue disappeared
