### ISSUE TITLE
Modifying Webpack Configuration

### ISSUE THREAD

**Issue by mikelunn** [angular/angular-cli#2113]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?) Windows 8

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here: angular-cli: 1.0.0-beta.11-webpack.8

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc. ng build

4. The log given by the failure. Normally this include a stack trace and some
   more information. No failure, just a question

5. Mention any other details that might be useful.

Is there anyway to modify the webpack dev/prod build processes that are running. Basically, html-webpack-plugin step is not needed in the scenario were an applications initial page is being server rendered by a server-side technology like ASP.Net. In my case I would only need to add script references to index.cshtml to the generated bundles. Unfortunately, when running ng build --prod, these references are broken by webpack adding hashes to generated files. I would rely on the server side technology to cache bust. Despite these small short-comings i'm really enjoying the CLI.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alexsorokoletov** [comment]
@mikelunn Did you find a way to modify webpack configs?

**Comment by mikelunn** [comment]
@alexsorokoletov I found another project template that has a pre-configured build process that integrates well with the server-side technology that i'm currently using: 
[ASP.NET/JavascriptServices](https://github.com/aspnet/JavaScriptServices/tree/dev/templates/Angular2Spa)

I wasn't sure if others would have the same need to modify the build process, so I closed the issue. But to answer your question, no I did not find a way to modify the webpack config settings. Do you want me to re-open the issue?

**Comment by alexsorokoletov** [comment]
No, thanks, was just wondering what solution did you use. 


Alex

**Comment by filipesilva** [comment]
Discussion can be found in https://github.com/angular/angular-cli/issues/1656
