### ISSUE TITLE
Problem with obserbales after RC7 update

### ISSUE THREAD

**Issue by gperdomor** [angular/angular-cli#2114]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?
    Mac OSX Sierra

2. Versions.
    angular-cli: 1.0.0-beta.11-webpack.9-4
    node: 6.5.0
    os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
TypeError: this.audio.first is not a function
    at LocalVideoComponent.toggleAudio (local-video.component.ts:38)
    at DebugAppView._View_LocalVideoComponent0._handle_click_18_0 (LocalVideoComponent.ngfactory.js:242)
    at view.js:404
    at dom_renderer.js:249
    at dom_events.js:26
    at ZoneDelegate.invoke (zone.js:192)
    at Object.onInvoke (ng_zone_impl.js:43)
    at ZoneDelegate.invoke (zone.js:191)
    at Zone.runGuarded (zone.js:99)
    at NgZoneImpl.runInnerGuarded (ng_zone_impl.js:72)

5. Mention any other details that might be useful.

I'm using ngrx/store to use redux style programming. I have the following function which works with angular rc5 and angular-cli beta11.webpack.8 but after update to RC7 and webpack.9-4 and run ng init, a got the error described on top.

<pre><code>
toggleAudio() {
    this.audio.first().subscribe(enabled => {
        // do something
        this.store.dispatch(this.localActions.toggleAudio(!enabled));
    });
}
</code></pre>

but this works:

<pre><code>
var source = Observable.range(0, 10).first().subscribe(
    function (x) {
        console.log('Next: %s', x);
    },
    function (err) {
        console.log('Error: %s', err);
    },
    function () {
        console.log('Completed');
    }
);
</code></pre>

In fact, adding this line var source = Observable.range(0, 10).first() inside toggleAudio function, makes that function, work as excepted.

<pre><code>
toggleAudio() {
    source = Observable.range(0, 10).first(); // With this, work.
    this.audio.first().subscribe(enabled => {
        // do something
        this.store.dispatch(this.localActions.toggleAudio(!enabled));
    });
}</code></pre>
</code>
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alanjhonnes** [comment]
You can try importing the first operator:
`import 'rxjs/add/operator/first';`

**Comment by gperdomor** [comment]
@alanjhonnes done!... Thanks
