### ISSUE TITLE
`ng add` not authenticating with internal registry on v12

### ISSUE THREAD

**Issue by pascal-puetz** [angular/angular-cli#21142]
# 🐞 Bug report

After updating to v12, `ng add` breaks when used with our private npm registry.

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [X] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: <= v11

### Description

When running `ng add` while NPM Registry is set to an internal Registry, the internal Registry is used but authentication information seems to be missing. This happens with both, yarn and npm. Running `npm install` or `yarn install` directly does work though.

## 🔬 Minimal Reproduction

Set npm to use a private Registry that needs Basic authentication and run `ng add`. This will fail while running `npm install` or `yarn install` directly does not. 

```
registry=https://some-private-repo.com/repository/
always-auth=true
_auth="<AUTH_TOKEN>"
```

## 🔥 Exception or Error

<pre><code>
ng add @angular/pwa                                                                                                                                                                                                
ℹ Using package manager: yarn
✖ Unable to load package information from registry: Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager"
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.4
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                                        Version
---------------------------------------------------------
@angular-devkit/architect           0.1200.2
@angular-devkit/build-angular   12.0.1
@angular-devkit/core                  12.0.2
@angular-devkit/schematics       12.0.4
@angular/cli                                12.0.4
@schematics/angular                  12.0.4
rxjs                                               6.6.7
typescript                                     4.2.4
webpack                                      5.37.1

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi, 

As a workaround can you try to update the `.npmrc` to below

```ini
//some-private-repo.com/repository:/_auth="<AUTH_TOKEN>"
registry=https://some-private-repo.com/repository/
```

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/21140

**Comment by pascal-puetz** [comment]
Thanks, this works! 
Just a tiny addition for anyone finding this issue:
`//some-private-repo.com/repository:/_auth="<AUTH_TOKEN>"` needs to be
`//some-private-repo.com/repository:_auth="<AUTH_TOKEN>"` (without the / in front of _auth)

**Comment by alan-agius4** [comment]
@pascal-puetz, 

Oops typo, the slash should be before the colon.

```diff
- //some-private-repo.com/repository:/_auth="<AUTH_TOKEN>"
+ //some-private-repo.com/repository/:_auth="<AUTH_TOKEN>"
```
