### ISSUE TITLE
ng build --configuration production not working

### ISSUE THREAD

**Issue by mwave317** [angular/angular-cli#21148]
I've just upgraded the project from 11 to 12. When trying to run ng build --configuration production or ng build --configuration production --watch the build doesn't work. It freezes. I can only get the build to complete if I use ng build. I need to be able to build this in production mode. Any help would be appreciated. I'm not getting any errors, when I control-c.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking 
important information.

Please file a new issue and ensure you provide all of the required information when filling out the issue template including a reproduction or at the very least CPU profile.
