### ISSUE TITLE
Angular 12: Web worker build warning "*.worker.ts is part of the TypeScript compilation but it's unused."

### ISSUE THREAD

**Issue by vladimirbelyayev** [angular/angular-cli#21147]
# 🐞 Bug report

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 10.0.7.

### Description

After upgrading from Angular 10 to Angular 12 we get warnings about unused files related to web worker.

<pre><code>Warning: .../src/app/shared/worker-services/image/image.service.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/worker-services/image/models/index.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/worker-services/image/models/largest-dimension-resize.input-model.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/worker-services/image/models/resize.input-model.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/workers/image-resize/image-resize.worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/workers/image-resize/models/index.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/workers/image-resize/models/resize-on-largest-dimension.worker-input-model.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/workers/image-resize/models/resize.worker-input-model.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Warning: .../src/app/shared/workers/image-resize/models/resize.worker-output-model.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
</code></pre>

## 🔬 Minimal Reproduction

Create new project & run it
<pre><code>ng new angular-web-worker-sample
</code></pre>

<pre><code>cd angular-web-worker-sample
</code></pre>

<pre><code>npm run start
</code></pre>

So far we have no warnings, now add web worker & run again.
<pre><code>ng generate web-worker sample-worker
</code></pre>

<pre><code>npm run start
</code></pre>

Now we get warning about unused worker ts file.

Adding 
```json
  "exclude": ["**/*.worker.ts"]
```
to `tsconfig.app.json` does not help

[Sample repo](https://github.com/vladimirbelyayev/angular12-web-worker-warn) with the warning present.

## 🔥 Exception or Error

<pre><code>Warning: D:/Tests/Angular-sample/angular-web-worker-sample/src/app/sample-worker.worker.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
</code></pre>

## 🌍 Your Environment

<pre><code>Angular CLI: 12.0.4
Node: 12.18.0
Package Manager: npm 6.14.4
OS: win32 x64

Angular: 12.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4
@angular-devkit/build-angular   12.0.4
@angular-devkit/core            12.0.4
@angular-devkit/schematics      12.0.4
@angular/cli                    12.0.4
@schematics/angular             12.0.4
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Anything else relevant?**

No

**Comment by vladimirbelyayev** [comment]
Looks like I found the issue myself.

We were creating worker instance like this in A10 and it did not produce warnings:
```typescript
this.resizeWorker = new Worker('./../../../../shared/workers/image-resize/image-resize.worker', {
    type: 'module'
})
```
		
Once I updated it to this in A12 [based from example](https://angular.io/guide/web-worker#adding-a-web-worker) there was no warning anymore:
```typescript
this.resizeWorker = new Worker(
	new URL('./../../../../shared/workers/image-resize/image-resize.worker', import.meta.url)
)
```

I guess in sample app the warning was produced because there was worker created, but it was not used anywhere? (No `new Worker()`)

**Comment by alan-agius4** [comment]
>  I guess in sample app the warning was produced because there was worker created, but it was not used anywhere? (No new Worker())

Indeed that is correct, when updating from version 10 to 12 using `ng update`, the worker syntax is changed with a migration.
