### ISSUE TITLE
Fetch API cannot load about:blank. URL scheme "about" is not supported.

### ISSUE THREAD

**Issue by iamjohnlong** [angular/angular-cli#2117]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX  El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.9-4
node: 6.5.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

installed the latest cli and started a new app.. run app

4. The log given by the failure. Normally this include a stack trace and some
   more information.

console throws:
`Fetch API cannot load about:blank. URL scheme "about" is not supported.`

thrown from this file `zone.js:556`

Chrome Version 53.0.2785.113 (64-bit)

It's only throwing it in chrome; NOT thrown in safari or firefox.

5. Mention any other details that might be useful.

The app seems to be running fine with the error being thrown.

**Comment by jakehowell** [comment]
I actually had this same issue as well, but just with Angular 2.0 not running angular-cli. Possibly an Angular 2.0 issue?

**Comment by SCDevy** [comment]
+1 @jakehowell, I don't think it's an angular-cli issue. Getting this same error, but with Angular 2 not running angular-cli. Node: 6.5.0 OS: Darwin x64 (El Capitan).

**Comment by iamjohnlong** [comment]
Yeah I just confirmed it's a zone.js error. Filing a bug there.. https://github.com/angular/zone.js/issues/444
