### ISSUE TITLE
ng serve is not working

### ISSUE THREAD

**Issue by sureshjangid** [angular/angular-cli#21180]
![Screenshot (192)](https://user-images.githubusercontent.com/75411144/123034549-591f1180-d407-11eb-8147-3c3554c12a48.png)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
