### ISSUE TITLE
Allow to exclude chunks from source map generation and optimizations

### ISSUE THREAD

**Issue by dwilches** [angular/angular-cli#21187]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Currently it's not possible to exclude a certain lazy-loaded chunk from optimization nor source-map generation as the valid options are base on chunk type only, and in the case of optimizations, it's all or nothing:

```json
"configurations": {
    "dev": {
        "optimization": true,
        "sourceMap": {
            "scripts": true,
            "styles": true,
            "hidden": false,
            "vendor": false
        },
        "buildOptimizer": true
    },
}
```

The problem with this approach is that if we want source maps for some but not all libraries then it's not possible to do it with the CLI. Check [this SO question](https://stackoverflow.com/questions/68103428/how-to-lazy-load-a-very-large-library-reveal-bi) with an example of a library that currently can't be used with lazy-loading in the Angular CLI.

### Describe the solution you'd like

I would like to control the extent of source maps and optimizations by chunk names:
```json
"configurations": {
    "dev": {
        "optimization": {
            "default": true,
            "revealbi-deps": false,
        },
        "sourceMap": {
            "scripts": {
                "default": true,
                "revealbi-deps": false,
            },
            "styles": true,
            "hidden": false,
            "vendor": false
        },
        "buildOptimizer": true
    },
}
```

### If you have a solution in mind, please describe it.

I don't have any.

### Have you considered any alternative solutions or workarounds?

So far my workaround has been to add `script` tags to `body` at runtime, to cause the browser to load the libraries only when a certain page has been visited.

**Comment by alan-agius4** [comment]
Hi @dwilches,

Thanks for this feature request.
 
Adding this options to the Angular CLI public API is out-of-scope, you can you a third-party to achieve this, although this is not supported by the Angular team.

Regarding https://stackoverflow.com/questions/68103428/how-to-lazy-load-a-very-large-library-reveal-bi, likely you are hitting a memory limit during downlevelling, Do you need differential loading in the first place?.

The file Is 22Mb minified😱 , which has to be one of largest files I have ever seen. You can try to increase the memory limit using `node --max-old-space-size=4096 ./node_modules/@angular/cli/bin/ng build --configuration=production"`.

**Comment by dwilches** [comment]
Hello,

Yes, we need differential loading for one more year as we still have
customers that use IE11.

What third-party library do you mean? Like ejecting the Angular CLI config
and adding custom webpack instructions?

**Comment by dwilches** [comment]
About the memory limit, we use to give it 4GB, and because of this issue we
increased it to 8GB, with no luck.

But it looks to me increasing the memory so the CLI doesn't crash while
generating source maps I don't need is not the solution I should be looking
for.

**Comment by dwilches** [comment]
By the way, about the differential loading question: ecen though we need it
for the main app, we don't need it for this large library, as this feature
is not going to be supported by IE11 anyways. But there seems to not be a
way to disable differential loading for only one chunk?

**Comment by alan-agius4** [comment]
> What third-party library do you mean? Like ejecting the Angular CLI config
and adding custom webpack instructions?

Not ejecting, but extending the webpack configurations using third-party tools such as https://github.com/manfredsteyer/ngx-build-plus

> But there seems to not be a way to disable differential loading for only one chunk?

No, typically you don't want a portion of your app to work on IE 11 and another portion doesn't not. Also having a mixture of ES5 and ES2015 can cause unexpected behaviour. Example, trying to extend an ES2015 class in an ES5 bundle will fail.

> it looks to me increasing the memory so the CLI doesn't crash while generating source maps I don't need is not the solution I should be looking for.

Indeed, but this is really quite a specify use case. In your case also the file size it self is enormous 22mb minified and for this file to processed it is expected that a large amount of memory would be needed.
