### ISSUE TITLE
Support font inlining for additional fonts

### ISSUE THREAD

**Issue by mgechev** [angular/angular-cli#21186]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

We currently support Google font inlining. Ideally, we'd want to support additional providers - Adobe Typekit, etc...

**Comment by alan-agius4** [comment]
Following a convo with @mgechev we decided that for the time being we should add Adobe fonts , previously known as Adobe Typekit.
