### ISSUE TITLE
Worker no longer working in karma/jasmine after migrating from 12.0.0 to 12.0.5

### ISSUE THREAD

**Issue by mboughaba** [angular/angular-cli#21182]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.0.0

### Description

 A clear and concise description of the problem...

The code below used to work in 12.0.0 (The new URL wrapper was added when migrating from 11 to 12).
`const worker: Worker = new Worker(new URL('./logger.worker', import.meta.url), { name: 'log', type: 'module' });`

With version 12.0.5
Running tests leads to the error below:

`Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///C:/Users/..../logger.worker' cannot be accessed from origin 'http://localhost:9876'`

## 🔥 Exception or Error

<pre><code>

Uncaught SecurityError: Failed to construct 'Worker': Script at 'file:///C:/Users/..../logger.worker' cannot be accessed from origin 'http://localhost:9876'

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.5
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.5.5
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Solved via https://github.com/angular/angular-cli/pull/21160 which will be available in 12.0.6
