### ISSUE TITLE
Build does not transpile any of the .ts to the build directory

### ISSUE THREAD

**Issue by nyabwana** [angular/angular-cli#2118]
1. Ubuntu 16.04 Server

2. angular-cli: 1.0.0-beta.11-webpack.2
node: 4.2.6
os: linux x64

I created this app using cli. When I ran ng build -prod to create a production version. Nothing was transpiled and thus when I run http-server in order to have it run using pm2, I get no output. I hope I am being clear

**Comment by gelliott181** [comment]
`ng build -prod` is invalid syntax. You want `ng build --prod` or the shorthand, `ng build`, which will output a production build in `dist`.

**Comment by filipesilva** [comment]
`ng build -prod` should work. I tried it on a brand new `beta.15` project and it built the project onto `dist/`.

Maybe the problem was that you were expecting the files to get transpiled in place, but instead the build artifacts are in `dist/`?
