### ISSUE TITLE
Version 12.1 prints ENOENT no such file or directory

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#21202]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.0.x

### Description

Just updated to 12.1 through ng update and now buildings seems to be unable to clear old files correctly. I always get errors like "ENOENT: no such file or directory" or "Error parsing bundle asset "/Volumes/Development/*/dist/aqua/main.f0babc2fd4603c54a819.js": no such file"

## 🔬 Minimal Reproduction

1. ng new
2. ng build

## 🔥 Exception or Error

<pre><code>

[error] Error: ENOENT: no such file or directory, stat '/Volumes/Development/__temp/twelve-one/dist/twelve-one'
    at Object.statSync (node:fs:1526:3)
    at __node_internal_ (node:internal/fs/utils:767:8)
    at Object.rmdirSync (node:fs:1146:15)
    at Object.deleteOutputDir (/Volumes/Development/__temp/twelve-one/node_modules/@angular-devkit/build-angular/src/utils/delete-output-dir.js:21:10)
    at initialize (/Volumes/Development/__temp/twelve-one/node_modules/@angular-devkit/build-angular/src/browser/index.js:86:17)
    at async SwitchMapSubscriber.project (/Volumes/Development/__temp/twelve-one/node_modules/@angular-devkit/build-angular/src/browser/index.js:114:17)
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.0
Node: 16.3.0 (Unsupported)
Package Manager: npm 7.16.0
OS: darwin x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
This is due to a change in behavior in Node.js v16 which is not officially supported by Angular currently.
Switching to Node.js v14 should resolve the issue.
Alternatively, the `deleteOutputPath` may be set to `false`. However, depending on the project's overall build process, this may require manually removing the output directory.

**Comment by muuvmuuv** [comment]
I totally forgot that I am running 16 already. Yes, this is true. I will disable it for now since I still want to benefit from Node 16 on my M1.
