### ISSUE TITLE
Angular Library do not stop generating sourcemap & do not generate minified files

### ISSUE THREAD

**Issue by entrymon** [angular/angular-cli#21211]
- [x ] new

### Is this a regression? 

Yes, previously it was working with angular 10.

### Description

Angular libraries now do not stop generating sourcemap files and also do not generate minified files.

Looking for a way to configure lib to not generate *.js.map.

Also looking for a way to generate *.min.js files.

## 🔬 Minimal Reproduction

ng new my-workspace --create-application=false
cd my-workspace
ng generate library my-lib

Open -> tsconfig.lib.prod.json add below code snippet to 
```
    "sourceMap": false,
    "pretty": false,
    "inlineSourceMap": false,
    "inlineSources": false
```
Run

ng build --configuration production

## 🔥 Exception or Error

Go to dist and see the generated files still has sourcemap and no minified file is generated.

## 🌍 Your Environment
Angular CLI: 12.1.0
Node: 14.17.1
Package Manager: npm 7.19.0
OS: darwin x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
ng-packagr                      12.1.0
rxjs                            6.6.7
typescript                      4.3.4

**Comment by alan-agius4** [comment]
Hi @entrymon,

ng-packagr which is the tool used to build and bundle libraries follows the [APF](https://docs.google.com/document/u/0/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs/mobilebasic).

What you we requesting above is not possible as it doesn’t conform with this spec.

**Comment by entrymon** [comment]
Thanks @alan-agius4  for speedy response, I can understand it does not follows the specs.

Can someone help if we have to achieve it _external_ to ng-packagr how we can do it? Any pointers or examples would be good.

I am less worried about sourcemap we can just run a postscript and delete those, but if we could find a way to do ***.min.js** that can extend and plug into the build process would be helpful.
