### ISSUE TITLE
Paused on promise rejection: 'Failed to execute 'fetch' on 'Window': 1 argument required, but only 0 present.'

### ISSUE THREAD

**Issue by rubenv** [angular/angular-cli#2122]
1. OS?

Mac OSX 10.11.6 (El Capitan)

2. Versions. 

```
$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.14
node: 5.10.1
os: darwin x64
```

3. Repro steps.

Create a new project (`ng new`) and run it (`ng serve`). Open it with the Chrome inspector open.

This blocks loading on every refresh, which is quite annoying.

4. The log given by the failure.

Paused on promise rejection: 'Failed to execute 'fetch' on 'Window': 1 argument required, but only 0 present.'

![screen shot 2016-09-15 at 09 07 33](https://cloud.githubusercontent.com/assets/42904/18541202/e47800bc-7b23-11e6-9932-ecf35274073d.png)

**Comment by filipesilva** [comment]
I can't seem to repro this myself. On a new project, I started `ng serve`, opened Chrome, pressed F12 to have the inspector, put `http://localhost:4200/` on the address bar and pressed enter. App loaded and debugger did not pause, no console errors either.

Am I missing a step here?

**Comment by onkark** [comment]
I am also getting this error after updating to angular 2.0.0

**Comment by JanStureNielsen** [comment]
@rubenv -- are you seeing this after the upgrade to `beta.15`? 

@onkark -- what version of Angular CLI?

**Comment by onkark** [comment]
@JanStureNielsen -- I think is error may be not relevant to angular CLI. I am not using angular CLI. 
This may be related angular 2 loading

**Comment by JanStureNielsen** [comment]
OK, @onkark -- but this repository is for bugs and features in Angular CLI. For support, please use StackOverflow. 

I suspect both of you have dependency issues which are likely resolved in `beta.15`. Try creating a new project with `beta.15` and compare dependencies, or `ng init` your existing project with `beta.15` and look at the diffs...

**Comment by talsi** [comment]
@rubenv - i also see this error. this issue relates to zone.js ([Failed to execute 'fetch' on 'Window'](https://github.com/angular/zone.js/issues/446)). 
btw, this exception does appear to be getting caught. 
afaik it doesnt have any implications on my angular2 app. 

@filipesilva - make sure you have "Pause On Exceptions" ticked in devtools.
![capture](https://cloud.githubusercontent.com/assets/5717665/18807705/02d88f4c-8257-11e6-8fd6-93296b119148.PNG)

**Comment by rubenv** [comment]
Yup, this is indeed https://github.com/angular/zone.js/issues/446

Closing this one, it's a duplicate.
