### ISSUE TITLE
angular update issues

### ISSUE THREAD

**Issue by rekna1** [angular/angular-cli#21222]
Update angular projects still is quite a challenge. I want to list some of the problems encountered which maybe could help the angular/cli team to improve the upgrade process or provide some additional information on update.angular.io.

Here are some issues I've encountered while updating angular 8 application to angular 11 (of course following every step, 8->9->10->11)

`Conflicting peer dependency: @angular/compiler-cli@11.2.14
node_modules/@angular/compiler-cli
  peer @angular/compiler-cli@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.14
  node_modules/@angular-devkit/build-angular
    dev @angular-devkit/build-angular@"~0.1102.14" from the root project`

Apparently this seems to be an issue with npm version 7... Angular should warn for incompatible npm version or recommend npm version

`Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.`

Fixed this by remove 'extraCss':true in angular.json, why does ng update leaves this option in angular.json ?

`'node-sass' usage is deprecated and will be removed in a future major version. `

Fixed this by uninstalling node-sass (again shouldn't angular cli do this)

` codelyzer@5.2.2 requires a peer of @angular/compiler@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself.`

This is a frequently recurring warning when updating from older versions.  Fixed it by npm install codelyzer@6, angular shouldn't it be part of ng update ?

I'm by no means an npm expert, so every error requires time consuming searches on the internet and trying to find a solution by trial and error.

I have no clue if all migrations have run in every step of the upgrade. E.g. sometimes node_modules were completely removed and had to run npm install to be able to continue. 
Maybe some of the above issues might have been caused by the fact I started with npm 7 and had to downgrade to npm 6 to be able to continue.

**Comment by alan-agius4** [comment]
> Conflicting peer dependency: @angular/compiler-cli@11.2.14 node_modules/@angular/compiler-cli peer @angular/compiler-cli@"^11.0.0 || ^11.2.0-next" from @angular-devkit/build-angular@0.1102.14 node_modules/@angular-devkit/build-angular dev @angular-devkit/build-angular@"~0.1102.14" from the root project Apparently this seems to be an issue with npm version 7... Angular should warn for incompatible npm version or recommend npm version

While we do support NPM 7, this has a number of defects related SemVer dependency ranges. There are several options to workaround this problem.

- Passing the `--force` option to `ng update` which will be propagated to NPM.
- Downgrade to npm 6
- Switch to yarn as a package man

> Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR. Fixed this by remove 'extraCss':true in angular.json, why does ng update leaves this option in angular.json ? 

There is a migration for this, that will remove `extractCss` from your configuration. That is unless you are using an unsupported 3rd party builder.

> 'node-sass' usage is deprecated and will be removed in a future major version. Fixed this by uninstalling node-sass (again shouldn't angular cli do this)

This should be done by the user since switching from node-sass to dart-sass can result in undefined behaviour or broken builds. While these are very similar, there are some differences. See https://github.com/sass/dart-sass#behavioral-differences-from-ruby-sass

> codelyzer@5.2.2 requires a peer of @angular/compiler@>=2.3.1 <10.0.0 || >9.0.0-beta <10.0.0 || >9.1.0-beta <10.0.0 || >9.2.0-beta <10.0.0 but none is installed. You must install peer dependencies yourself. This is a frequently recurring warning when updating from older versions. Fixed it by npm install codelyzer@6, angular shouldn't it be part of ng update ?

There is a migration that updates `codelyzer` to version 6.

**Comment by rekna1** [comment]
I've run everything again. main problem seems to be npm7 which messed everything up.
So basically:
* don't use npm7 (yet) 
* node-sass warning can be ignored
* if something does go wrong before migration, best thing to do is probably ng update --migrate-only ?

does Angular team recommends yarn ?

**Comment by alan-agius4** [comment]
> node-sass warning can be ignored

You should plan to move from node-sass to dart-sass accordingly, eventually in version 13, support of node sass will be emerged.

> if something does go wrong before migration, best thing to do is probably ng update --migrate-only ?

Yes

> does Angular team recommends yarn ?

This is our preferred package managed.

**Comment by alan-agius4** [comment]
Anything else that, we can help with?
