### ISSUE TITLE
Postcss-loader plugins for webpack excluded files

### ISSUE THREAD

**Issue by vaggelanos** [angular/angular-cli#21220]
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

N/A

### Description

Postcss-loader (and specifically its plugins like tailwindcss) shouldn't be used for excluded files styles rules in webpack config.
The responsibility of including precompiled styles is on the external libraries and not angular itself.
This results in conflicts with libraries using tailwindcss and increased build time.

## 🔬 Minimal Reproduction

Run ng build or ng serve and grab a copy of generated webpack config.

On any rule for the different styles this is generated on excluded oneOf object 
<pre><code>
{
  "oneOf": [
    {
      "exclude": [
        "src/styles.scss"
      ],
      "use": [
        {
          "loader": "\\node_modules\\raw-loader\\dist\\cjs.js"
        },
        {
          "loader": "\\node_modules\\@angular-devkit\\build-angular\\node_modules\\postcss-loader\\dist\\cjs.js",
          "options": {
            "implementation": "smth",
            "postcssOptions": "see below"
          }
        }
      ]
    }
  ]
}
</pre></code>

postcssOptions.plugins
<pre><code>
[
  { postcssPlugin: 'postcss-import', Once: [Function: Once] },
  {
    postcssPlugin: 'postcss-cli-resources',
    Declaration: [AsyncFunction: Declaration]
  },
  {
    postcssPlugin: 'tailwindcss',
    plugins: [
      [Function (anonymous)],
      [Function (anonymous)],
      [Function: formatNodes]
    ]
  },
  [Function (anonymous)] {
    postcssPlugin: 'postcss-preset-env',
    postcssVersion: '7.0.36'
  }
]
</code></pre>

## 🌍 Your Environment

<pre><code>
"@angular/animations": "^12.1.0",
"@angular/common": "^12.1.0",
"@angular/compiler": "^12.1.0",
"@angular/core": "^12.1.0",
"@angular/forms": "^12.1.0",
"@angular/platform-browser": "^12.1.0",
"@angular/platform-browser-dynamic": "^12.1.0",
"@angular/router": "^12.1.0",
"@angular-builders/custom-webpack": "^12.1.0",
"@angular-devkit/build-angular": "^12.1.0",
"@angular/cli": "^12.1.0",
"@angular/compiler-cli": "^12.1.0",
"@angular/language-service": "^12.1.0",
"tailwindcss": "^2.2.0",
</code></pre>

**Anything else relevant?**
I wonder if this is intended or a misconfiguration.
And if it's intended provide the reasoning behind this.

Thanks

**Comment by alan-agius4** [comment]
This is expected since global stylesheet needs to be handled differently from components sheetsheets and hence the `oneOf` with `exclude`.

Can you please elaborate on the problem?there is no information on the actual problem that this is causing/increased time difference.

**Comment by vaggelanos** [comment]
I see the difference now. Wasn't sure if it was a bug or not. Thanks for your answer
