### ISSUE TITLE
Stylus support

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#21237]
Why was stylus removed as a stylesheet format option? I would like to this made available again.

**Comment by alan-agius4** [comment]
Stylus support in the CLI is deprecated and it will be removed in version 14. New projects should avoid using Stylus as eventually they'd need to migrate to a seperate pre-processor.

The main reason for this decision was that Stylus project itself dead and Stylus usage in the Angular CLI is around 0.3%.
