### ISSUE TITLE
karma preprocessors result is not replected to spec

### ISSUE THREAD

**Issue by han41858** [angular/angular-cli#21241]
# Bug Report

### Affected Package

`@angular-devkit` maybe

### Is this a regression?

Yes, the previous version in which this bug was working properly.

### Description

I created new workspace with `ng new`

I changed template file from `app.component.html` to `app.component.pug`
and installed `pug`, `karma-pug-preprocessor` packages.

I added some codes in `karma.conf.js`:

```javascript
...
plugins: [
...
require('karma-pug-preprocessor')
],
...
files: [
  'src/**/*.pug'
],
preprocessors: {
  'src/**/*.pug': ['pug']
},
...
```

and execute default specs using command `yarn test`.

With some log in `karma-pug-preprocessor`, I found this result.
Logs are added in `createPugPreprocessor` function in `node_modules/karma-pug-preprocessor/index.js`.

`karma-pug-preprocessor` is working properly, and result is good.
`content`, `processed` are as expected.

```bash
λ yarn test
yarn run v1.22.4
$ ng test
- Generating browser application bundles (phase: setup)...29 06 2021 00:19:34.067:FATAL [preprocessor.pug]: ### peprocessor.pug
\ Generating browser application bundles (phase: building)...29 06 2021 00:19:36.493:FATAL [preprocessor.pug]: ### peprocessor.pug function
29 06 2021 00:19:36.508:FATAL [preprocessor.pug]: ###  {
  file: File {
    path: 'D:/Workspace/cli12-pug/src/app/app.component.html',
    originalPath: 'D:/Workspace/cli12-pug/src/app/app.component.pug',
    contentPath: 'D:/Workspace/cli12-pug/src/app/app.component.pug',
    encodings: [Object: null prototype] {},
    mtime: 2021-06-28T14:44:56.676Z,
    isUrl: false,
    doNotCache: false,
    type: undefined,
    isBinary: null
  },
  content: '.content\r\n\tspan {{ title }} app is running!',
  processed: '\n<div class="content"><span>{{ title }} app is running!</span></div>'
}
```

But the component template in spec still remains a string of pug.
In `app.component.spec.ts` file, I added some log:

```typescript
it('should render title', () => {
    const fixture = TestBed.createComponent(AppComponent);
    fixture.detectChanges();
    const compiled = fixture.nativeElement;
    console.log(compiled);
    console.log(compiled.querySelector('.content span'));
    expect(compiled.querySelector('.content span').textContent).toContain('cli12-pug app is running!');
  });
```

The value of `compiled` is still a string of pug:

```html
<div id="root1" _nghost-a-c11="" ng-version="12.0.5">.content span cli12-pug app is running!</div>
```

So, `compiled.querySelector('.content span')` is `null` and spec failed.

Why the result of Karma preprocessor is not connected with component template in Karma?

## Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-jmchxw?file=src/karma.conf.js

## Exception or Error

no error in `serve` or `build`
just spec failed

## Your Environment

**Angular Version:**
<pre><code>
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.0.5
Node: 14.17.0
Package Manager: yarn 1.22.4
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

I LOVE Angular ❤️

**Comment by alan-agius4** [comment]
This is expected.

The Karma builders uses Webpack under the hood which by passes preprocessors.

To use `pug`, you will need to use a 3rd party builder like https://github.com/manfredsteyer/ngx-build-plus although by doing so you are leaving the supported path.
