### ISSUE TITLE
Angular 11 Optimization Build Parameter breaks Date format

### ISSUE THREAD

**Issue by Condra963** [angular/angular-cli#21266]
# 🐞 Bug report

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I'm not sure about this.

### Description

When i use the angular's formatDate pipe on localhost it was working, but when i deployed it on production my date format was apparently in UTC format. When i started digging deeper i found out the issue is in the build configuration 'optimization: true' parameter. I Removed that and my date format was correct. The date formats i am using are: shortDate, mediumDate, longDate, ...

If this is already solved in a newer version or this issue is already open, my apologies, i have looked for open or resolved issues but didn't found this one.

Thanks!

## 🌍 Your Environment

Windows, Chrome/Firefox/Edge, Angular 11

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Condra963** [comment]
@alan-agius4 ok i will do this as soon as possible.

**Comment by Condra963** [comment]
@alan-agius4 i close this issue because it was not related to any of this. When i run locally without any optimization, outputhash, ... parameter the date is shown correctly as expected, but when i was building it WITH the parameters it wasn't. This because a Date format getter that returns the format wasn't found (interface getter was not correctly overridden). That causes that the typed format will be handled in the current culture when running in development mode, when running in production mode the date will be formatted as UTC by default.
