### ISSUE TITLE
Where to add Images and other files in 1.0.0-beta.14

### ISSUE THREAD

**Issue by MateenKadwaikar** [angular/angular-cli#2126]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new Angu2Final.

I read online that in project we have public folder but when I pulled the code there was not public folder and when I did ng build I was not able to see my images .
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ciesielskico** [comment]
angular-cli.json

See the property 'assets'. 
This means images (or assets in general) have to be placed under _root/assets_, in this case it will be under `src/assets`.

```
"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": "assets",
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
```

**Comment by CraigWarford** [comment]
Okay, so...  It's copying /src/assets/images to /dist/assets/images, but it's not copying all files.  In my case, it copies the four .png files, and leaves the one .jpg file sitting there.
