### ISSUE TITLE
TypeError: this.computeFullOptions is not a function

### ISSUE THREAD

**Issue by niranjans3ln** [angular/angular-cli#2127]
Mac 10.11.16.

I was trying to build an app and here I find the following error message and I am not able to go further.

ERROR in ./src/index.ts
Module build failed: TypeError: this.computeFullOptions is not a function
    at Object.Linter (/Users/calvin/node_modules/tslint/lib/tslint.js:15:29)
 @ multi app

When I check page source on the browser it says "./src/index.ts" is not found, whereas it is very well present.

I have taken the sample project from : https://github.com/e-schultz/angular2-redux-example

This is from the blog: http://blog.rangle.io/getting-started-with-redux-and-angular-2/

Please help.

**Comment by kamkha** [comment]
This is not an issue with angular-cli but rather a change to how tslint must be used with Webpack. To use tslint as a preloader in Webpack, you now need to install *tslint-loader*.

`npm install --save-dev tslint-loader` should do the trick.

**Comment by filipesilva** [comment]
Can you add some repro steps and version information? It's hard/impossible for me to help you out without them.

**Comment by hansl** [comment]
Closing as deprecated.

**Comment by Brocco** [comment]
No reproduction steps provided in the last 4 months, closing.
