### ISSUE TITLE
Error: Cannot find name after Angular 9 update

### ISSUE THREAD

**Issue by fradev94** [angular/angular-cli#21270]
Hi, we're updating Angular from version 8.2 to 12 and we're proceeding step by step, updating first to version 9. After this first upgrade and after using the command npm start we're getting these errors:

![image](https://user-images.githubusercontent.com/79634994/124282223-e3275280-db4a-11eb-961c-56c78e6104f1.png)

You can find our Angular versions in the following picture:

![image](https://user-images.githubusercontent.com/79634994/124282437-1e298600-db4b-11eb-8abd-3edf43b323b0.png)

These are the definitions of the elements that caused the errors:
declare type DataSourceState = 'loading' | 'loaded' | 'error';
declare type ChartjsType = 'line' | 'bar' | 'horizontalBar' | 'radar' | 'pie' | 'doughnut' | 'polarArea' | 'bubble' | 'scatter';

Could someone help us, please? We've already tried a lot of solutions found on web. 
Thank you!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
