### ISSUE TITLE
D3-color while occured error when use @angular-devkit/build-optimizer/webpack-loader.

### ISSUE THREAD

**Issue by ietwangwei** [angular/angular-cli#21289]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 no.

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/12638284/124555849-22ff7a00-de6a-11eb-8cf4-264634ae960e.png)

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
