### ISSUE TITLE
ESLint strict linter checks - warnings with boilerplate code generated by angular 12 CLI

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#21281]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No

### Description
When linting a generated angular 12 application with angular CLI, ESLint raises warnings

## 🔬 Minimal Reproduction
- `npx @angular/cli@12 new web-apps --create-application false`
- `cd web-apps`
- Create `.eslintrc.json` and add this code snippet
 ```json
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "plugins": [],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": ["tsconfig.json"],
        "createDefaultProgram": true
      },
      "extends": [
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@angular-eslint/all"
      ],
      "rules": {
        "@angular-eslint/sort-ngmodule-metadata-arrays": "off"
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/all"],
      "rules": {
        "@angular-eslint/template/i18n": "off"
      }
    }
  ]
}

```
- `yarn ng add @angular-eslint/schematics`
- `yarn ng g @angular-eslint/schematics:app admin-console --routing --style css`
- Edit `.vscode/settings.json` and add this code snippet
	```json
	{
	  "eslint.validate": ["typescript", "html"]
	}
	```
- `yarn ng lint --project admin-console`

## 🔥 Exception or Error

<pre><code>
Linting "admin-console"...

/Users/<username>/web-apps/projects/admin-console/src/app/app.component.html
  399:5   error  click must be accompanied by either keyup, keydown or keypress event for accessibility  @angular-eslint/template/click-events-have-key-events
  405:5   error  click must be accompanied by either keyup, keydown or keypress event for accessibility  @angular-eslint/template/click-events-have-key-events
  411:5   error  click must be accompanied by either keyup, keydown or keypress event for accessibility  @angular-eslint/template/click-events-have-key-events
  417:5   error  click must be accompanied by either keyup, keydown or keypress event for accessibility  @angular-eslint/template/click-events-have-key-events
  423:5   error  click must be accompanied by either keyup, keydown or keypress event for accessibility  @angular-eslint/template/click-events-have-key-events
  429:5   error  click must be accompanied by either keyup, keydown or keypress event for accessibility  @angular-eslint/template/click-events-have-key-events
  443:13  error  The cyclomatic complexity 6 exceeds the defined limit 5                                 @angular-eslint/template/cyclomatic-complexity

/Users/<username>/web-apps/projects/admin-console/src/app/app.component.spec.ts
  32:11  error  Unsafe assignment of an `any` value                    @typescript-eslint/no-unsafe-assignment
  33:12  error  Unsafe member access .textContent on an `any` value    @typescript-eslint/no-unsafe-member-access
  33:12  error  Unsafe member access .querySelector on an `any` value  @typescript-eslint/no-unsafe-member-access
  33:12  error  Unsafe call of an `any` typed value                    @typescript-eslint/no-unsafe-call

/Users/<username>/web-apps/projects/admin-console/src/app/app.component.ts
  3:1  error  The changeDetection value of a component should be set to ChangeDetectionStrategy.OnPush  @angular-eslint/prefer-on-push-component-change-detection
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.1
Node: 16.4.1 (Unsupported)
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**
No

**Comment by prabh-62** [comment]
I disabled `@angular-eslint/template/i18n` rule for HTML files and if we enable that rule, there 'd be even more warnings

**Comment by alan-agius4** [comment]
I think we should be able to at least address some of these.

**Comment by alan-agius4** [comment]
I believe we fixed all the actionable issue here. 

The non actionable once are;
- 443:13  error  The cyclomatic complexity 6 exceeds the defined limit 5,  **moving the logic from template to TypeScript would increase the complexity to remove the default boilerplate template.**
- 3:1  error  The changeDetection value of a component should be set to ChangeDetectionStrategy.OnPush, **_ChangeDetectionStrategy.OnPush is opt-in_**
- i18n rules, **_we don't add i18n by default and hence it would be redundant to add the i18n attributes._**
