### ISSUE TITLE
Projects created wth ng new do not install

### ISSUE THREAD

**Issue by noce2** [angular/angular-cli#21288]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v11

### Description

 Projected created with `ng new` and routing fails to install.

## 🔬 Minimal Reproduction

1. Run `$ ng new gaya-web` - command fails
2. After, run: `cd gaya-web && npm install` - command fails with same error as above

## 🔥 Exception or Error

<pre><code>

gaya-web$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: gaya-web@0.0.0
npm ERR! Found: @angular/core@undefined
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"12.1.1" from @angular/animations@12.1.1
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~12.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/noce2/.npm/eresolve-report.txt for a full report.

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.1
Node: 12.20.0
Package Manager: npm 7.19.1
OS: linux x64

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a defect in NPM 7. 

Several options to workaround the problem with NPM 7 include:
* passing the `--force` option to `ng update` which will propagate the force flag to npm.
* Downgrade to NPM 6.
* Switch to `yarn` as a package manager.

**Comment by juanpicado** [comment]
I can confirm this issue, I run E2E against latest npm7 + angular-cli on every PR  
https://github.com/verdaccio/verdaccio/runs/3069577257?check_suite_focus=true

The last time this was green was 11 days ago
https://github.com/verdaccio/verdaccio/actions/workflows/e2e-angular-cli-workflow.yml

Steps to reproduce:

```
pm i -g npm@next-7 
ng new verdaccio-angular --interactive=false --force
⠋ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: verdaccio-angular@0.0.0
npm ERR! Found: jasmine-core@3.7.1
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.7.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

```

**Comment by Dr-NULL** [comment]
I have the same issue. Normally i update `@angular/cli` sometimes to check for new versions. I simply run:
```
npm install --g @angular/cli
```
...and:
```
ng new client
```
Got this result:
```
⠼ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: client@0.0.0
npm ERR! Found: jasmine-core@3.7.1
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.7.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\dr-null\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dr-null\AppData\Local\npm-cache\_logs\2021-07-14T19_46_53_813Z-debug.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
```

**Comment by alan-agius4** [comment]
Hi @noce2, unfortunately, this is not actionable by us. Please raise an issue in the NPM issue tracker. 

@juanpicado & @Dr-NULL, you are experiencing a different issue which should no longer be reproducible using the latest stable version of the Angular CLI.
