### ISSUE TITLE
Proxied Angular tries to get assets/artifacts through HTTP even though the browser navigated via HTTPS

### ISSUE THREAD

**Issue by lukaszpochron** [angular/angular-cli#21287]
# Bug Report

### Affected Package
@angular-devkit/build-angular@12.1.0

### Description
While...
1. served by .NET inside a Docker container with HTTP,
2. ran through a Nginx reverse proxy,
3. and navigated with the browser via HTTPS,

...a production build of Angular is trying to get its assets/artifacts such as `runtime.js`, `polyfills.js`, `main.js`, `favicon` through HTTP, which is causing a Mixed Media error in the browser. No additional packages that should impact this behaviour were used and there's only the default builder.

**Please scroll to the bottom for a temporary workaround in index.html.**

### Is this a regression?

Yes, the issue was caused by migration from Angular 7. I apologise for not having more precise information about the exact version causing regression. Will try to provide if it turns out to be necessary.

## Minimal Reproduction

1. The issue should apply to any Angular application serving via HTTP and running through a Nginx reverse proxy providing HTTPS connection - more detailed setup in Description above.
2. Observe main.js, styles, polyfills, favicon being requested through HTTP and being blocked by the security policy as below.

## Exception or Error
<pre><code>Mixed Content: The page was loaded over HTTPS, but requested an insecure X. This request has been blocked; the content must be served over HTTPS.</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular: 12.0.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1201.1
@angular-devkit/build-angular              12.1.1
@angular-devkit/core                       12.1.1
@angular-devkit/schematics                 12.0.5
@nguniversal/module-map-ngfactory-loader   6.1.0
@schematics/angular                        12.0.5
rxjs                                       6.6.7
typescript                                 4.2.4

</code></pre>

## Workaround
This issue can be temporarily fixed by adding the below in src/index.html:
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`

I think this is not a bad fix, although it should not be required. It has to be noted that there's good browser compatibility with the exception of the beloved Internet Explorer.

**Comment by petebacondarwin** [comment]
It would be helpful if you could provide the contents of your `index.html`.

**Comment by alan-agius4** [comment]
@lukaszpochron, as @petebacondarwin  can you please share the generated `index.html`.

**Comment by lukaszpochron** [comment]
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>Title</title>
  <base href="/en/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="stylesheet" href="styles.a36f351ab5d42cf04ccf.css" media="print" onload="this.media='all'"><noscript>
    <link rel="stylesheet" href="styles.a36f351ab5d42cf04ccf.css">
  </noscript>
</head>

<body>
  <app-root>
    <div>Loading...</div>
    <div id="warningPlaceholder"></div>
    <script>
      function getErrorMessage(language) {
        // (...)
        return "If the page is not working, ...";
      }

      setTimeout(function () {
        var div = document.querySelector("#warningPlaceholder");
        if (!div)
          return;
        var cookies = document.cookie;
        var languageCookieIndex = cookies.indexOf("mlang") + 6;
        var language = cookies.substr(languageCookieIndex, 2);
        var message = getErrorMessage(language);
        div.innerText = message;
      },
        5000);

    </script>
  </app-root>
  <script src="runtime-es2015.bd4ec30118b76f9d0778.js" type="module"></script>
  <script src="runtime-es5.bd4ec30118b76f9d0778.js" nomodule defer></script>
  <script src="polyfills-es5.53b9bf17f412cdfa5b01.js" nomodule defer></script>
  <script src="polyfills-es2015.0dd8f9173b4c3e2c7c5a.js" type="module"></script>
  <script src="main-es2015.c846710553afe6caf313.js" type="module"></script>
  <script src="main-es5.c846710553afe6caf313.js" nomodule defer></script>

</body>
</html>
```

**Comment by alan-agius4** [comment]
The resources are relative therefore if the application is accessed via HTTPS the resources will be served through HTTPs. 

That is, unless there is some missing configuration in the server or/and proxy.

**Comment by lukaszpochron** [comment]
@alan-agius4, is your first statement a rule in new Angular? I found some information saying that it will be the case on some servers, which is down to the configuration.

However I inspected the generated html (for the same input) and it doesn't seem that there's a difference in the url relativity, although the **script types** have changed.

Angular 7:
```
<script type="text/javascript" src="runtime.02a03fa6470f52c8f695.js"></script>	
<script type="text/javascript" src="polyfills.f62f4d69be6773ca5236.js"></script>	
<script type="text/javascript" src="main.0c1db0856f73d12db5af.js"></script>
```

Angular 12:
```
<script src="runtime-es2015.7a502e56e82e0a4faddb.js" type="module"></script>
<script src="runtime-es5.7a502e56e82e0a4faddb.js" nomodule defer></script>
<script src="polyfills-es5.3c32165e1e49fd3b5ec3.js" nomodule defer></script>
<script src="polyfills-es2015.770f5c7edebc94bf2a0f.js" type="module"></script>
<script src="main-es2015.f1a95f39387f19f16aa8.js" type="module"></script>
<script src="main-es5.f1a95f39387f19f16aa8.js" nomodule defer></script>
```

**Comment by alan-agius4** [comment]
> is your first statement a rule in new Angular?

No, this is how browsers works, therefore indeed it is likely that it’s some server / proxy configuration.

**Comment by prabh-62** [comment]
I have been using https://github.com/microsoft/reverse-proxy across different angular 12 workspaces and haven't noticed any HTTP/HTTPS issues.

**Comment by lukaszpochron** [comment]
Thanks, is your app HTTP and getting HTTPS from the proxy?

> No, this is how browsers works, therefore indeed it is likely that it’s some server / proxy configuration.

It looks a lot as if it was, but deployment of the app with Angular 12 into the test environment is introducing the issue and re-deployment of the one with Angular 7 is fixing it. The aforementioned fix does the trick, but I would like to get to the bottom of the issue so it's fully under control.

**Comment by prabh-62** [comment]
HTTPS Everywhere
 - During local development using https://github.com/microsoft/reverse-proxy
 - Staging/QA environments
 - Production environment


`dotnet dev-certs https --trust` provides SSL certificate for local development -> `https://localhost:443`

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
