### ISSUE TITLE
Angular 4 - Obfuscation issues

### ISSUE THREAD

**Issue by slopzslife** [angular/angular-cli#21283]
I have the dist files obfuscated using javascript-obfuscator, Everything has been working fine except for the lazy loaded modules.

`vendor.41de57e87964949c0586.bundle.js:1 ERROR Error: Uncaught (in promise): Error: Cannot find 'TesterModuleModule' in 'app/tester-module/tester-module.module'
Error: Cannot find 'TesterModuleModule' in 'app/tester-module/tester-module.module'`

The obfuscated paths look like this
`{'path':'test','loadChildren':_0xb27949(0x5b6)}]`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
