### ISSUE TITLE
Faster tests: Destroy test module after every test by default

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#21280]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
```shell
❯ npx @angular/cli@12 new web-apps --create-application false
❯ cd web-apps && yarn ng g app admin-console --routing --style scss
```
- Edit `projects/admin-console/src/test.ts` and update `TestEnvironmentOptions`
```ts
getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
  { teardown: { destroyAfterEach: true } }
);
```

### Describe the solution you'd like
The third argument `{ teardown: { destroyAfterEach: true } }` should be applied by default when creating application/library.

### Describe alternatives you've considered
N/A

Relevant blog post: [What's new in Angular 12.1?](https://blog.ninja-squad.com/2021/06/25/what-is-new-angular-12.1/)

**Comment by alan-agius4** [comment]
This definitely makes sense for new applications since eventually we’d like this to be the default.
