### ISSUE TITLE
Cant connect jQuery plugin

### ISSUE THREAD

**Issue by nikitarakitin** [angular/angular-cli#2129]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.14
node: 5.12.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
EXCEPTION: Error: Uncaught (in promise): EXCEPTION: Error in ./InitOrderComponent class InitOrderComponent_Host - inline template:0:0
ORIGINAL EXCEPTION: TypeError: jQuery(...).intlTelInput is not a function
ORIGINAL STACKTRACE:

intlTelInput.js:15 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ intlTelInput.js:15(anonymous function) @ intlTelInput.js:17
lang.js:310Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.

5. Mention any other details that might be useful.

I want to use jQuery plugin (https://github.com/jackocnr/intl-tel-input), but i cant connect it. I think that library cant connect with jQuery, because i can use jQuery in my project only that way: let jQuery = require('jQuery'); require('jquery') not working. 
My angular-cli.json:

{
  "project": {
    "version": "1.0.0-beta.11-webpack.8",
    "name": "order-page"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": "assets",
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css",
        "../node_modules/intl-tel-input/build/css/intlTelInput.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.js",
        "../node_modules/intl-tel-input/build/js/intlTelInput.js"
      ],
      "environments": {
        "source": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "dev": "environments/environment.dev.ts"
      }
    }
  ],
  "addons": [],
  "packages": [],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "lazyRoutePrefix": "+"
  }
}

package.json:

{
  "name": "order-page",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "core-js": "^2.4.0",
    "intl-tel-input": "9.0.9",
    "jquery": "^3.1.0",
    "moment": "^2.15.0",
    "ng2-bootstrap": "1.1.0",
    "process-nextick-args": "^1.0.7",
    "rxjs": "5.0.0-beta.11",
    "ts-helpers": "^1.1.1",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/jquery": "^1.10.31",
    "angular-cli": "1.0.0-beta.11-webpack.8",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "0.13.22",
    "karma-chrome-launcher": "0.2.3",
    "karma-jasmine": "0.3.8",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.3",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "^2.0.0"
  }
}

**Comment by ifaouibadi** [comment]
import * as $ from 'jquery';
window['$'] = window['jQuery'] = $;
this how i do it

**Comment by nikitarakitin** [comment]
cant find module 'jquery'

**Comment by ifaouibadi** [comment]
``` npm i --save jquery ```

**Comment by nikitarakitin** [comment]
@ifaouibadi after that command:

C:\Users\nnn93\Documents\taxilime\orderpage>npm i --save jquery
order-page@0.0.0 C:\Users\nnn93\Documents\taxilime\orderpage
+-- angular-cli@1.0.0-beta.11-webpack.8
| +-- UNMET PEER DEPENDENCY @angular/platform-server@^2.0.0-rc.5
| +-- compression-webpack-plugin@0.3.1
| | `-- node-zopfli@1.4.0
| |   +-- defaults@1.0.3
| |   `-- node-pre-gyp@0.6.30
| |     +-- rc@1.1.6
| |     `-- tar-pack@3.1.4
| |       +-- fstream-ignore@1.0.5
| |       +-- once@1.3.3
| |       +-- readable-stream@2.1.5
| |       | `-- buffer-shims@1.0.0
| |       `-- uid-number@0.0.6
| `-- UNMET PEER DEPENDENCY webpack@2.1.0-beta.21
+-- UNMET DEPENDENCY jquery@^3.1.0
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.11
`-- UNMET PEER DEPENDENCY typescript@2.0.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.5.0 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN @angular/compiler-cli@0.5.0 requires a peer of @angular/platform-server@^2.0.0-rc.5 but none was installed.
npm WARN @angular/core@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/http@2.0.0-rc.5 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/router@3.0.0-rc.1 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.
npm WARN string-replace-loader@1.0.3 requires a peer of webpack@1.x.x || 2.x.x but none was installed.
npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "--save" "jquery"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\jquery
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\jquery' -> 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\.jquery.DELETE'
npm ERR!     at moveAway (C:\Users\nnn93\AppData\Roaming\nvm\v6.5.0\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\nnn93\AppData\Roaming\nvm\v6.5.0\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\jquery' -> 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\.jquery.DELETE'
npm ERR!     at Error (native)
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\jquery' -> 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\.jquery.DELETE'
npm ERR!     at moveAway (C:\Users\nnn93\AppData\Roaming\nvm\v6.5.0\node_modules\npm\lib\install\action\finalize.js:38:5)
npm ERR!     at destStatted (C:\Users\nnn93\AppData\Roaming\nvm\v6.5.0\node_modules\npm\lib\install\action\finalize.js:27:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR!
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\jquery' -> 'C:\Users\nnn93\Documents\taxilime\orderpage\node_modules\.jquery.DELETE'
npm ERR!     at Error (native) parent: 'order-page' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\nnn93\Documents\taxilime\orderpage\npm-debug.log

**Comment by cricri92** [comment]
Is there any updates about this issue?

**Comment by nikitarakitin** [comment]
I am connect libraries using CDN, its working (jquery and jquery plugin)

**Comment by cricri92** [comment]
@nikitarakitin I'm not using CDN libraries. I did installation of the package via npm, then install `@types/jquery`, include it in `angular-cli.json`'s scripts entry, script from `node_modules` folder. After that, in my code just import jquery: `import * as $ from 'jquery';` and it's working for me.

**Comment by kiencoltech** [comment]
I got the same problem!
**1.** Install jquery using npm

> npm install jquery --save

**2** Install jQuery TypeScript autocomplete

> npm install @types/jquery --save-dev
**3** Adding to angular-cli.json 
"scripts": [
"../node_modules/jquery/dist/jquery.min.js"
]
- In package.json

> dependencies

> "jquery": "^3.2.1",

**4** I restart by : ng serve

But it is still occur message:

> scripts.bundle.js:17  Uncaught ReferenceError: jQuery is not defined

Anyone have solve?

**Comment by iosifpetre18** [comment]
I had the same error, I solved it by updating node to latest version: https://nodejs.org/en/download/
then "npm cache --force clean" and then "npm install"
