### ISSUE TITLE
`.editorconfig` disappeared from generated files

### ISSUE THREAD

**Issue by sarunint** [angular/angular-cli#2131]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
1.0.0-beta.14

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Just do `ng new` and `.editorconfig` does not appear in generated files

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We had a bug where this wasn't added to projects generated by `beta.14`, but it's now fixed in `beta.15`. You can find it here if you need to add it to your project: https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/ng2/files/.editorconfig
