### ISSUE TITLE
npm ERR! Could not resolve dependency: npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0

### ISSUE THREAD

**Issue by weirdyang** [angular/angular-cli#21326]
# 🐞 Bug report

### Command (mark with an `x`)

- [ x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

```
| Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: bulma-angular@0.0.0
npm ERR! Found: jasmine-core@3.7.1
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.7.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ads\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```

I get the following error when I try to create a new project. I've updated `ng cli` after reading this [issue](https://github.com/angular/angular-cli/issues/20719), but I'm still getting the error.

**Comment by weirdyang** [comment]
D:\personal\angular>ng v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.1.1
Node: 14.15.4
Package Manager: npm 7.19.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.1 (cli-only)
@angular-devkit/core         12.1.1 (cli-only)
@angular-devkit/schematics   12.1.1 (cli-only)
@schematics/angular          12.1.1 (cli-only)

**Comment by alan-agius4** [comment]
Looks like the issue is caused by a `karma-jasmine-html-reporter` release, were they dropped support for `jasmine-core` version `3.7` in a minor version. 

Removing the lower bounds of a peerDependency should be considered a breaking changed due to NPM 7 new peer dependencies behaviour. 

As a workaround you can do the following; 
```
ng new --skip-install
Open package.json and bump jasmine-core to `~3.8.0`
npm i
```

**Comment by weirdyang** [comment]
Thank you.
