### ISSUE TITLE
Angular CLI 12.x silently fails serving, testing, and building older Angular projects.

### ISSUE THREAD

**Issue by EvanCarroll** [angular/angular-cli#21322]
# 🐞 Bug report

If you create a project with angular-cli v11, and then upgrade angular-cli v12, you'll no longer be able to run numerous subcommands on the project. Those subcommands will silently fail and exit.

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [X] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes.

### Description

Applications created with Angular 11.x will not build with angular-cli 12.x

## 🔬 Minimal Reproduction

```sh
npm install -g @angular-cli@11
ng new foobar --skip-install
cd foobar;
```

edit your `package.json`, to upgrade your `@angular/cli` to 12.

    "@angular/cli": "~12",

Then run `npm install`

Now many of the `ng` commands will silently fail. 

    ng build
    ng serve
    ng test

## 🔥 Exception or Error

I would expect desire either,

* It works
* Or, an error is produced that notifies the user that @angular/cli version 12.x does not support projects created with @anguilar 11.x

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.1
Node: 14.17.3
Package Manager: npm 6.14.13
OS: linux x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      12.1.1
@angular/cli                    12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.1.6
</code></pre>

**Comment by alan-agius4** [comment]
Updating the dependency directly in your `package.json` is guaranteed to cause undefined or broken behaviour.

To update please follow the steps in https://update.angular.io/

**Comment by EvanCarroll** [comment]
@alan-agius4 sure, but that seems like something `ng` can/should warn about.

**Comment by rajjaiswalsaumya** [comment]
I used ng update to update my dependencies, I also see similar behavior.
