### ISSUE TITLE
Update the documentation on how to update to webpack

### ISSUE THREAD

**Issue by nbuso** [angular/angular-cli#2133]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux fedora 24

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

$ ng --version
(node:28399) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.10
node: 6.5.0
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@1.0.0-beta.10

move to a temporary directory and generate a new project
ng new beta10-update
cd beta10-update

follow the update guide
https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md

I past here the steps:
=======================
Global package:

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@webpack

Local project package:

# commit any changes you have to git first
rm -rf node_modules dist tmp typings
npm install --save-dev angular-cli@webpack

ng init
========================

4. The log given by the failure. Normally this include a stack trace and some
   more information.

with the last command 'ng init' you get the following message:
=========================
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12
=========================

5. Mention any other details that might be useful.
The documentation is saying "Upgrading from angular-cli@1.0.0-beta.10 to the angular-cli@webpack", that is exactly what I'm doing but the steps are leading to an error.

The error message provide another documentation page (https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12). That is even more confusing because try to explain how to move from "Beta.10 to Beta.12" that is overlapping with the other documentation title (angular-cli@webpack lead to beta.14 currently)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nbuso** [comment]
sorry guys I inadvertently used some formatting, I hope it's still comprehensible.

**Comment by nbuso** [comment]
I just noticed from https://github.com/angular/angular-cli

> Prerequisites
>
> The generated project has dependencies that require Node 4.x.x and NPM 3.x.x.

can I use node 6.5.0? is the prerequisites are node >= 4.x.x?

**Comment by aszechlicki** [comment]
you can certainly use Node 6.5.0
I'm not sure if the document is up to date, afaik minimum node version is 6.3.0 - someone correct me if i'm wrong

**Comment by jbeckton** [comment]
I too am having issues upgrading.. Two docs updated just 4 days apart, which is the correct document?

I started with this doc https://github.com/angular/angular-cli/blob/master/WEBPACK_UPDATE.md and got the same message as the OP when running "ng init" which led me to https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12 . 

Firstly, I do not see a Beta 12 release for the CLI webpack or otherwise.

Secondly I am getting a lot of errors when running the "sudo npm install -g angular-cli@latest"

````
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng

> node-zopfli@1.4.0 install /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.2 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.2.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/.node-gyp"
make: Entering directory `/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
make: *** No rule to make target `../.node-gyp/6.2.2/include/node/common.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 3.10.0-327.28.3.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 3.10.0-327.28.3.el7.x86_64
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/angular-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
node-pre-gyp ERR! node -v v6.2.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
/usr/local/lib
`-- angular-cli@1.0.0-beta.14 
  `-- UNMET PEER DEPENDENCY webpack@2.1.0-beta.22

````
