### ISSUE TITLE
Build fails at terser, after upgrading to 12 

### ISSUE THREAD

**Issue by papagei-ma** [angular/angular-cli#21336]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

Hi there, 
After upgrading  from 11 to 12. I started getting the error, when building  ng build --prod :

->
(main-es2015.21e5cf56d4f7287a5ce2.js from Terser
Name expected [main-es2015.21e5cf56d4f7287a5ce2.js:175349,5] ).
<-

Some INFOs. Im running an ionic on angular project. last version was angular 11. 
No custom webpack configuration. 

some dependancies ( through angular/cli )
@angular-devkit/build-webpack@0.1201.1
 webpack "5.41.1"
 terser "5.7.0"
 terser-webpack-plugin "5.1.3". 

Did somebody face something like this, even when upgrading from last versions?

Does anyone know where I should start digging? 

### Please provide the exception or error you saw

```true
Error: main-es2015.21e5cf56d4f7287a5ce2.js from Terser
Name expected [main-es2015.21e5cf56d4f7287a5ce2.js:175349,5] ).
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.1
Node: 14.17.3
Package Manager: yarn 1.22.10
OS: darwin x64
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
ng-packagr                      12.1.1
rxjs                            6.6.3
typescript                      4.3.5
```

**Comment by alan-agius4** [comment]
Hi @papagei-ma,


- Are you using custom webpack configuration?
- Are the below listed as dependencies in your package.json?
```
@angular-devkit/build-webpack@0.1201.1
webpack "5.41.1"
terser "5.7.0"
terser-webpack-plugin "5.1.3".
```

**Comment by papagei-ma** [comment]
No, I don't use a custom webpack configuration. 
No, they are in yarn.lock. So I guess they are dependancies from other packages, ,might be angular/cli itself.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by papagei-ma** [comment]
Hi @alan-agius4, so it seems really hard to reproduce. The case is, that it is an ionic on angular project, that has been around for a long time. First Ionic version I think was 3, and first used angular version was 6. And then it developed using ng upgrade whenever there was a new stable version. So I am saying that in a fresh new project, there is no problem with build at all. It is only there, when the mechanism that angular use webpack; and then its own of using Treser ( minimiser, optimizer) and somehow it fails :(. 
DO YOU HAVE ANY IDEA WHERE I SHOULD DIG DEEPER?

**Comment by papagei-ma** [comment]
Hi @alan-agius4, terser-webpack-plugin "5.1.3" seems to be causing the error.  when i explicitly choose 5.1.4 in Package.json, everything seems to work properly.  Would you say it is a safe approach?

**Comment by papagei-ma** [comment]
Hi all 
angular 12.1.2  => no problem with build at all. 
Thanks Team Angular :)
