### ISSUE TITLE
Builds started failing with OOM after angular 12 upgrade

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [angular/angular-cli#21333]
`ng build` works but ng build --prod fails 

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
No 

### Description

Builds failing when ng build --prod is run. I tried increasing node memory to 8 gb, as previous angular 9/10/11 threads about this issue says, but no luck.

## 🔬 Minimal Reproduction
I have this issue in an app which also has a library app in it. This is company owned app hence can't really share the app, although i want to.

**Comment by alan-agius4** [comment]
Please share memory heap snapshots from version 11 and version 12.

> @alan-agius4 How can produce a memory snapshot of `ng serve` for help to solve this issue?

1. `node --inspect-brk node_modules/@angular/cli/lib/init.js build --configuration production `
1. Open Chrome and type `chrome://inspect` in the address bar
1. Click on the `inspect` button from one of your applications in the Remote Target section.
1. Go to `Chrome DevTools` > `Memory`
1. Take a heap snapshot
1. Perform the action that causes OOM

**Comment by alan-agius4** [comment]
Also please share the output of `ng v`

**Comment by alan-agius4** [comment]
Closing due to lack of communication.
