### ISSUE TITLE
After Upgrade to Angular 12 styles.scss not found on some routes

### ISSUE THREAD

**Issue by FloMueh** [angular/angular-cli#21332]
Hello guys, 

i upgraded my medium complex application to angular 12. Its working well except one behavior.

I navigate to localhost:4200/login -> styles.scss loaded
After Login - whole application -> styles.scss loaded

when i reload on a page with a route like this: 
http://localhost:4200/projects/details;projectId=9580b137-7746-4284-91b2-8922a6b530f5;tabIndex=0;siteId=fa78e712-c8b3-4795-a93d-f73e7f054a9e -> **styles.scss not loaded. Because angular tries to load the file from localhost:4200/projects**. 

reload on a page like this: http://localhost:4200/projects -> styles.scss loaded 

any ideas how to solve this? i dont know why angular tries loading the styles.scss from a relativ path. 

Thanks, 
Florian

**Comment by alan-agius4** [comment]
Can you please share your index HTML file, thanks?

**Comment by FloMueh** [comment]
@petebacondarwin a runnable reproduction is not possible, sorry cause its owned by a company i work for. 

I can add the styles.**css** to the index.html, than the styles are there when i reload the page. But this seems not to be a good solution....

here is the index.html 
`<!DOCTYPE html>
<html style="height: 100%">

<head>
  <title>XXXXX</title>
  <base href="/">
  <meta charset="UTF-8">
  
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://unpkg.com/@ag-grid-community/all-modules@23.0.0/dist/styles/ag-theme-alpine.css">
  <link rel="stylesheet" href="https://unpkg.com/@ag-grid-community/all-modules@23.0.0/dist/styles/ag-grid.css">
  <link rel="stylesheet" href="https://unpkg.com/@ag-grid-community/all-modules@23.0.0/dist/styles/ag-theme-material.css">

  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-XXXXXXX');</script>
  

  
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXX"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXXX');
</script>

    

  <script>
    if (global === undefined) {
      var global = window;
    }

  </script>

<body style="height: 100%; background: #F2F2F2">

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=XXXXXXX"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  
  
  <pp-app-root>
<div id="loading" style="height: 100%; width: 100%; text-align: center; top: 50%; margin-top: -200px; position: absolute;">
    <img src="assets/loading-square.gif" width="400" height="400"/>
  </div>
</pp-app-root>
</body>

</html>
`

**Comment by alan-agius4** [comment]
Can you also please share the generated index.html?

**Comment by FloMueh** [comment]
yeah, of course. 

```html
<html style="height: 100%"><head><style>@charset "UTF-8";@import url(https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap);body{font-family:Roboto!important;font-size:15px!important;font-weight:400!important;line-height:19px!important;}:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning:#ffc107;--danger:#dc3545;--light:#f8f9fa;--dark:#343a40;--breakpoint-xs:0;--breakpoint-sm:576px;--breakpoint-md:768px;--breakpoint-lg:992px;--breakpoint-xl:1200px;--font-family-sans-serif:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans","Liberation Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";--font-family-monospace:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;}*,:after,:before{box-sizing:border-box;}html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-webkit-tap-highlight-color:rgba(0,0,0,0);}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,Liberation Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff;}img{border-style:none;}img{vertical-align:middle;}@media print{*,:after,:before{text-shadow:none!important;box-shadow:none!important;}img{page-break-inside:avoid;}@page {size:a3;}body{min-width:992px!important;}}</style><link rel="stylesheet" href="styles.15147a777f94fddfe938.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.15147a777f94fddfe938.css"></noscript>
  <title>YYYYYY</title>
  <base href="/">
  <meta charset="UTF-8">
  <!--Official Icon Styles from Material-->
  <style type="text/css">@font-face{font-family:'Material Icons';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/materialicons/v92/flUhRq6tzZclQEJ-Vdg-IuiaDsNa.woff) format('woff');}.material-icons{font-family:'Material Icons';font-weight:normal;font-style:normal;font-size:24px;line-height:1;letter-spacing:normal;text-transform:none;display:inline-block;white-space:nowrap;word-wrap:normal;direction:ltr;font-feature-settings:'liga';}@font-face{font-family:'Material Icons';font-style:normal;font-weight:400;src:url(https://fonts.gstatic.com/s/materialicons/v92/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.woff2) format('woff2');}.material-icons{font-family:'Material Icons';font-weight:normal;font-style:normal;font-size:24px;line-height:1;letter-spacing:normal;text-transform:none;display:inline-block;white-space:nowrap;word-wrap:normal;direction:ltr;-webkit-font-feature-settings:'liga';-webkit-font-smoothing:antialiased;}</style>
  <link rel="stylesheet" href="https://unpkg.com/@ag-grid-community/all-modules@23.0.0/dist/styles/ag-theme-alpine.css">
  <link rel="stylesheet" href="https://unpkg.com/@ag-grid-community/all-modules@23.0.0/dist/styles/ag-grid.css">
  <link rel="stylesheet" href="https://unpkg.com/@ag-grid-community/all-modules@23.0.0/dist/styles/ag-theme-material.css">
  <!-- https://github.com/aws/aws-amplify/issues/678 fix: -->
<!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-XXXXXX');</script>
  <!-- End Google Tag Manager -->

  <!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX-1aa"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXX-C');
</script>

    <!-- END Global site tag (gtag.js) - Google Analytics -->

  <script>
    if (global === undefined) {
      var global = window;
    }

  </script>
  <!-- https://github.com/aws/aws-amplify/issues/678 fix end-->

</head><body style="height: 100%; background: #F2F2F2">
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXX"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  
  <pp-app-root>
<div id="loading" style="height: 100%; width: 100%; text-align: center; top: 50%; margin-top: -200px; position: absolute;">
    <img src="assets/loading-square.gif" width="400" height="400">
  </div>
</pp-app-root>
<script src="runtime-es2015.f9216b4d65db97b75eda.js" type="module"></script><script src="runtime-es5.f9216b4d65db97b75eda.js" nomodule defer></script><script src="polyfills-es5.bd7e90c533152df553a7.js" nomodule defer></script><script src="polyfills-es2015.201b732a203f708ea93b.js" type="module"></script><script src="scripts.ea2ecd3af906e84c0c92.js" defer></script><script src="main-es2015.f2d8f7924425b4cc978a.js" type="module"></script><script src="main-es5.f2d8f7924425b4cc978a.js" nomodule defer></script>


</body></html>
```

**Comment by alan-agius4** [comment]
Okay, so looking again at the source of your index file. It appears that you don't have a closing `</head>`.

**Comment by FloMueh** [comment]
@alan-agius4 thank you mate! this causes the issue. Nobody from our team has recognized this 🥇

**Comment by karamjeetiron** [comment]
@FloMueh @alan-agius4  Did you notice another issue that inline style added with body min-width: 992px and this causing the problem in responsive devices?
