### ISSUE TITLE
NG generate web worker breaks unit tests in Angular 12 Part 2

### ISSUE THREAD

**Issue by lpierce1313** [angular/angular-cli#21348]
So I am going back to this issues https://github.com/angular/angular-cli/issues/21108. I cannot figure out what they are saying about this issue. How do I specify the path per @alan-agius4's comments. 

For existing projects, in angular.json you need to specify the web-worker tsconfig path in using the webWorkerTsConfigoption under the test builder.

Thanks!

**Comment by alan-agius4** [comment]
```diff
"test": {
  "builder": "@angular-devkit/build-angular:karma",
  "options": {
    "main": "src/test.ts",
    "polyfills": "src/polyfills.ts",
+   "webWorkerTsConfig": "tsconfig.worker.ts",
    "tsConfig": "tsconfig.spec.json",
    "karmaConfig": "karma.conf.js",
    "assets": [
      "src/favicon.ico",
      "src/assets"
    ],
    "styles": [
      "src/styles.scss"
    ],
    "scripts": []
  }
```
