### ISSUE TITLE
How to upgrade to final release of Angular

### ISSUE THREAD

**Issue by grunk** [angular/angular-cli#2134]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.11-webpack.8                                                                                                                                                     
node: 6.5.0                                                                                                                                                                              
os: win32 x64 

Hello,
is there any documentation on how to update to the final release of Angular 2 ?

My project is currently running the RC5 with 1.0.0-beta.11-webpack.8.

updating the package.json like #2121 is enough ? Should i also try to upgrade angular cli ?

Thanks :)

**Comment by ciesielskico** [comment]
The newest angular-cli beta.14 release includes updates to the dependencies as in the commit you mentioned.

1. Update angular-cli to beta.14 (both globally and locally in the project)
2. ng init (update package.json and peer dependencies)
3. ng serve
4. Welcome to 2.0.0 final :)

**Comment by hansl** [comment]
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12
