### ISSUE TITLE
Unable to upgrade to older Angular version due to old Node version

### ISSUE THREAD

**Issue by dummdidumm** [angular/angular-cli#21343]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, in the sense that this worked before Angular 12

### Description

I'm stuck on an old node version which is lower than the new minimum required node version since Angular 12. This seems to make upgrading to older versions impossible. I want to upgrade from Angular 8 to 9. This produces the following:

```
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via pnpm.
Installed packages for tooling via pnpm.
Node.js version v12.13.0 detected.
The Angular CLI requires a minimum Node.js version of either v12.14 or v14.15.
```

To me this sounds like the CLI wants to install version 12.x temporarily and fails to do so due to node version requirements.

## 🔬 Minimal Reproduction

1. Install old node version
2. Create a new project with Angular 8
3. run `ng update @angular/core@9 @angular/cli@9`

## 🔥 Exception or Error

<pre><code>
Node.js version v12.13.0 detected.
The Angular CLI requires a minimum Node.js version of either v12.14 or v14.15.
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.3.29
Node: 12.13.0
OS: win32 x64
Angular: 8.2.12
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       <error>
@angular-devkit/build-angular   0.803.29
@angular-devkit/core            <error>
@angular-devkit/schematics      <error>
@angular/animations             8.2.14
@angular/cdk                    8.2.3
@angular/cli                    8.3.29
@angular/flex-layout            8.0.0-beta.27
@angular/http                   7.2.15
@angular/material               8.2.3
@schematics/angular             <error>
@schematics/update              <error>
rxjs                            6.6.7
typescript                      3.5.3
</code></pre>

**Comment by alan-agius4** [comment]
Hi @dummdidumm,

There are a couple of way to get around this. 

1) Update to a more recent version of Node.Js (12.14 or later)
2) Use `NG_DISABLE_VERSION_CHECK=1` enviorment variable to disable the downloading of a temporary version of the Angular CLI during the update process. This will however cause the update to be performed using the installed version Angular CLI version, and therefore you will not avail of fixes targeting to the update pipeline.

**Comment by dummdidumm** [comment]
Due to corporate requirements I'm unable to upgrade the node version. Thank you for the hint with the version check!
