### ISSUE TITLE
ng serve fails after some modification to the source code - module.buildInfo.jsonData  TypeError: Cannot read property 'jsonData' of undefined

### ISSUE THREAD

**Issue by leonelvsc** [angular/angular-cli#21349]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.1.1

### Description

Run ng serve like allways

<pre>
<code>
Initial Chunk Files                                                                                     | Names         |      Size
vendor.js                                                                                               | vendor        |  17.10 MB
main.js                                                                                                 | main          |   7.20 MB
scripts.js                                                                                              | scripts       |   1.01 MB
styles.css                                                                                              | styles        | 846.56 kB
polyfills.js                                                                                            | polyfills     | 406.35 kB
runtime.js                                                                                              | runtime       |  13.86 kB

                                                                                                        | Initial Total |  26.54 MB

Lazy Chunk Files                                                                                        | Names         |      Size
src_app_ceramicos-la-plata_administracion_administracion_module_ts.js                                   | -             |   4.83 MB
default-src_app_ceramicos-la-plata_venta_venta_module_ts.js                                             | -             |   2.79 MB
src_app_madeco_venta_venta_module_ts.js                                                                 | -             |   1.87 MB
src_app_madeco_produccion_produccion_module_ts.js                                                       | -             |   1.62 MB
default-src_app_madeco_common-components_common-components_module_ts.js                                 | -             |   1.39 MB
src_app_madeco_proveedores_proveedores_module_ts.js                                                     | -             |   1.17 MB
src_app_ventas_ventas_module_ts.js                                                                      | -             |   1.16 MB
src_app_madeco_banco_bancos_module_ts.js                                                                | -             | 917.62 kB
src_app_ceramicos-la-plata_logistica_logistica_module_ts.js                                             | -             | 893.92 kB
src_app_contabilidad_contabilidad_module_ts.js                                                          | -             | 781.78 kB
default-src_app_madeco_custom-directives_custom-directives_module_ts-src_app_main_service_con-9c34b3.js | -             | 557.74 kB
src_app_ceramicos-la-plata_banco_banco_module_ts.js                                                     | -             | 482.17 kB
src_app_ceramicos-la-plata_logistica-handhelds_logistica-handhelds_module_ts.js                         | -             | 386.45 kB
src_app_ceramicos-la-plata_planeamiento_planeamiento_module_ts.js                                       | -             | 385.68 kB
src_app_ceramicos-la-plata_grupo_grupo_module_ts.js                                                     | -             | 302.96 kB
src_app_ceramicos-la-plata_facturacion_facturacion_module_ts.js                                         | -             | 277.80 kB
src_app_shared-components_lector-qr-web-worker_qr-decoder_worker_ts.js                                  | -             | 253.25 kB
src_app_ceramicos-la-plata_etiquetas_etiquetas_module_ts.js                                             | -             | 192.78 kB
default-src_app_ceramicos-la-plata_venta_caja-ventas_caja-ventas_component_ts-src_app_ceramic-ecd1a6.js | -             | 172.79 kB
node_modules_firebase_messaging_dist_index_esm_js.js                                                    | -             | 147.01 kB
src_app_administracion_administracion_module_ts.js                                                      | -             | 107.53 kB
default-src_app_madeco_logistica_logistica_module_ts.js                                                 | -             | 103.91 kB
src_app_ceramicos-la-plata_tablero_tablero_module_ts.js                                                 | -             |  55.45 kB
default-src_app_ceramicos-la-plata_administracion_ingreso-egreso-motivo_ingreso-egreso-motivo-f547ef.js | -             |  33.06 kB
default-src_app_ceramicos-la-plata_logistica_local-storage_local-storage-clp-logistica-strategy_ts.js   | -             |  23.66 kB
src_app_configuracion_configuracion_module_ts.js                                                        | -             |  19.57 kB
common.js                                                                                               | common        |   9.92 kB

</code>
</pre>

## 🔬 Minimal Reproduction

Modify some code then the error shows up after the rebuild of a lazy chunk

## 🔥 Exception or Error

<pre>
<code>
Generating browser application bundles.../home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/json/JsonGenerator.js:119
		let data = module.buildInfo.jsonData;
		                            ^

TypeError: Cannot read property 'jsonData' of undefined
    at JsonGenerator.getSize (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/json/JsonGenerator.js:119:31)
    at NormalModule.size (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:1224:43)
    at NormalModule.cleanupForCache (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModule.js:364:9)
    at NormalModuleFactory.cleanupForCache (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/NormalModuleFactory.js:670:11)
    at Compiler._cleanupLastNormalModuleFactory (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:383:34)
    at Compiler.createNormalModuleFactory (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1049:8)
    at Compiler.newCompilationParams (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1071:30)
    at Compiler.compile (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1082:23)
    at /home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Watching.js:188:19
    at Hook.eval [as callAsync] (eval at create (/home/naxs/Trabajo/NaxsCloud/NaxsCloudWeb/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.2
Node: 14.17.0
Package Manager: npm 7.19.1
OS: linux x64

Angular: 12.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.2
@angular-devkit/build-angular   12.1.2
@angular-devkit/build-webpack   0.1201.2
@angular-devkit/core            12.1.2
@angular-devkit/schematics      12.1.2
@angular/fire                   6.1.5
@schematics/angular             12.1.2
ng-packagr                      12.1.2
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.44.0
</code></pre>

**ng build works fine**

**Comment by terencehonles** [comment]
I just ran into this, so I'm glad this is already reported. It looks like it's possibly due to this: https://github.com/webpack/webpack/issues/13691 but I'm starting to second guess myself because you have webpack 5.44.0 and I have 5.42.0 which doesn't include this fix, but it looks like yours should

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/21352

**Comment by MelvilQ** [comment]
When can we expect the fix to be released?

**Comment by alan-agius4** [comment]
A release should happen later on today.

**Comment by hexsus** [comment]
still have the same issue on 12.1.3 @
