### ISSUE TITLE
Generate angular workspace/application with ChangeDetection onPush

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#21353]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

User should be able to generate angular applications/libraries with change detection enabled.
- `npx @angular/cli@12 new web-apps --create-application false --changeDetection onPush`
```
Unknown option: '--changeDetection'
Unknown option: 'onPush'
```
<img width="784" alt="npx_angular_cli_change_detection" src="https://user-images.githubusercontent.com/13006107/125985833-488f11f2-7435-4e75-9315-62ec8f9ae0d1.png">

### Describe the solution you'd like

Provide a flag to enable change detection

### Describe alternatives you've considered

Manually edit 
- `angular.json` and append `"changeDetection": "OnPush"` under `@schematics/angular:component` for every workspace application/library
- `projects/<app>/src/app/app.component.ts` and append `changeDetection: ChangeDetectionStrategy.OnPush` to `@Component` decorator

**Comment by alan-agius4** [comment]
This did come up when we discussed https://github.com/angular/angular-cli/issues/21278.

We feel that this is trivial enough to do and doesn't warrant to be included as an extra option in the various schematics. The fact that this option in the application schematic is already ambiguous enough. 

Remember that you can use the `ng config` command to set up the options.

```
ng new web-apps --no-create-application
ng config schematics.@schematics/angular:component.changeDetection OnPush
ng generate application app-one
```
