### ISSUE TITLE
Compilation is much slower during ng serve when multiple configurations provided.

### ISSUE THREAD

**Issue by cyraid** [angular/angular-cli#21356]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli, compiler

### Description

I wasn't sure where to put this but, currently when you ng serve --configuration conf1,conf2 it is quite a bit slower when saving a file and having it compile, than just copying your configuration options from one into the other.

The process when it says "building" and "sealing", is a quite a bit slower. Where the noticeable point is no longer snappy and instant which is what I love much about Angular. :)

### Proposed solution

Optimize the multiple configuration solution? Perhaps merge the configurations internally to save speed?

### Alternatives considered

Perhaps an 'extend' option can be used inside the configuration areas?

**Comment by clydin** [comment]
When composing multiple configurations, the options are concatenated once prior to initial execution via a series of object spread operations ([code](https://github.com/angular/angular-cli/blob/546efc83dff145c87a10eefad2717c9a72c136e5/packages/angular_devkit/architect/node/node-modules-architect-host.ts#L179-L185)) with the options in the later specified configurations replacing any former option values.  The application build process only interacts with the final composed options.

If one of the `ng serve` invocations is slower during the `sealing` phase then one of the most likely causes is that one of the invocations has optimizations enabled in some form.

To investigate further, please provide an example configuration file or a minimal reproduction exhibiting the issue.

**Comment by cyraid** [comment]
You guys led me on to some more testing, I was using ng serve with --configuration development,<conf> .. But apparently, you can use multiple configurations in serve with "browserTarget": "ext:build:<conf>,development". So once I started doing this, for some reason it's faster again. I am quite perplexed.. Guess I'll close this issue for now..
