### ISSUE TITLE
ng serve compile again for the first time after module installation 

### ISSUE THREAD

**Issue by kjteh** [angular/angular-cli#21361]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Can be simulate in Angular 11, at least

### Description

 
When run `ng serve` after `npm install`, there will be one extra compilation process after it prints out `Compiled Successfully`. 
I was able to know that the second time compilation (see below screenshot) could be due to the `ngcc` where it will generate some ivy-related files at the end which may causes the webpack to compile again due to file change (i guess)
![screenhot](https://user-images.githubusercontent.com/56550921/126036418-cf06f719-ad34-418c-87d4-16ddad79063d.PNG)

Question: Not sure whether this is a bug or not, but, is there anyway to avoid the second compilation? probably only let the webpack to listen the file changes after the ngcc compilation is done?
 I know we can do `ngcc` in `postinstall` but this will trigger bundling all the modules (include those that not used in the projects)

## 🔬 Minimal Reproduction
1. Create a new angular project
2. Run `npm start`
3. Observe the compilation process will happen twice.

Note: 
- This only happens for the first time of `ng serve` after `npm install`, subsequent `ng serve` will not have this issue again, until the next `npm install` happens (ngcc is need to do the bundle process). 

## 🔥 Exception or Error
None
<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.2
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1201.2
@angular-devkit/build-angular   12.1.2
@angular-devkit/core            12.1.2
@angular-devkit/schematics      12.1.2
@schematics/angular             12.1.2
rxjs                            6.6.7
typescript                      4.3.5
    

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This is actually working as expected.

This is an unfortunate side-effect of NGCC, unfortunately currently there is nothing we can do to tell webpack not to trigger the redundant rebuild. Eventually this will be fixed once NGCC is phased out.

**Comment by werwer748** [comment]
I have to this problem
To be soon auto compile loop....
I'm very sad.....

**Comment by alan-agius4** [comment]
> I have to this problem
> To be soon auto compile loop....
> I'm very sad.....

That sounds like a different issue. Please file a new issue and provide a minimal reproduction. Thanks.
