### ISSUE TITLE
ng serve with i18n should behave the same as with SSR

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular-cli#21374]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...
When working with i18n you need to create a configuration per language and serve each language with another language on another port. 

### Describe the solution you'd like

 If you have a solution in mind, please describe it.
When a project is i18n enabled, it should behave just like @nguniversal/builders:ssr-dev-server which serves all languages at the same time on the same port.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

I tried to abuse @nguniversal/builders:ssr-dev-server with no luck until now.

**Comment by alan-agius4** [comment]
What is the use-case that requires all of the languages to be compiled and available during development?

**Comment by mbeckenbach** [comment]
When building a multi-language and multi-culture app you have to deal with different lengths as well as texts, different date, number, etc. formats. When dealing with RTL & LTR this becomes even more important. 

I can remember that the material team a long time ago explained that RTL is the reason why some of their components use attributes like start and end instead of left and right.

Also one might want to test if features like a language switcher or saving & applying the user's language from the profile works. 

In some cases, you might even want to change Pictures or Fonts based on the locale. The font per locale is a quite common case for some non-Latin alphabets.

Sure you could test that by building and running the final build. But that also means you need a local dev server to route the requests for different language versions or you need to deploy somewhere to a server that does this. 

So at the end of the day, this is a development time convenience feature to make developers of such apps more productive. But I thought as the SSR project already has that, it might not be too hard to port and adopt it. Sure you could run multiple instances at multiple locales. But it is just not the same.

**Comment by alan-agius4** [comment]
Hi @mbeckenbach, 

Thanks for this request.

Typically during the normal development life cycle you don't want to build and translate multiple locales. Building multiple locales during development will increase rebuilds times. 

Let's re-consider this in the future if we see that more users would like to translate multiple locales during development.
