### ISSUE TITLE
Ng build does not export src/favicon to dist/ folder.

### ISSUE THREAD

**Issue by vinagreti** [angular/angular-cli#2137]
1. OS?
Ubuntu 16.04 x64

2. Versions. 
angular-cli: 1.0.0-beta.14
node: 4.2.6
os: linux x64

3. Repro steps.
Just run ng build and look inside dist/ folder to check if favicon.ico was exported.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
Failed to load favicon.ico. The file cannot be found on the server.

5. Mention any other details that might be useful.
I had to move my favicon to assets/img/favicon.ico and changed the index.html to point to taht place. Is it the correct configuration or the favicon should be placed inside src/ folder?

The same occurs for .htaccess file and any other file that we would like to insert in the root of the build folder.

**Comment by yuri1969** [comment]
+1

**Comment by vinagreti** [comment]
Same to .htaccess file.

**Comment by bthharper** [comment]
No assets either (although that's a topic of another issue).

It's not clear (to me anyway) if we should now copy these using a separate build script?

**Comment by tomwanzek** [comment]
Replicates for favicon (have not tested with other assets yet) on Windows 10 with
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: win32 x64

**Comment by filipesilva** [comment]
This is part of a bigger discussion going on in https://github.com/angular/angular-cli/issues/1942
