### ISSUE TITLE
Improved ng lint experience for new projects

### ISSUE THREAD

**Issue by mgechev** [angular/angular-cli#21387]
# 🚀 Feature request

Improve the `ng lint` experience for new projects.

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Describe the solution you'd like

Rather than throw an error with a message when the user runs `ng lint`, implement a more efficient workflow where we either:
1. Automatically run the `ng add` command with the only builder
1. Copy the `ng add` command to the clipboard

As discussed on Slack, option 1. would be less disruptive and provide better DX.

**Comment by santoshyadavdev** [comment]
Hey @alan-agius4 @mgechev can i take this up, can i get more details which do we need to add the typescript/eslint here?

**Comment by alan-agius4** [comment]
I think for starters we need to evacuate if we still want to do this.

I think we were hoping that this receives more interest from the community, which wasn’t the case.

**Comment by santoshyadavdev** [comment]
Cool I am sharing with the community to check if we get enough interest.

**Comment by LayZeeDK** [comment]
It's a little difficult to understand what is being proposed. Care to rephrase, @mgechev?

**Comment by twittwer** [comment]
IMO ihr would be nice to get a suggestion how to continue in the error message (like "You have no linter setup. Run ng add ... to do it now"), but doing it automatically seems a bit unexpected if you just want to lint your code.

**Comment by IKatsuba** [comment]
Why can't you add eslint when creating a project?

**Comment by martinmcwhorter** [comment]
Option 1.
