### ISSUE TITLE
Angular build index file: where does the injected style come from?

### ISSUE THREAD

**Issue by harleenarora** [angular/angular-cli#21383]
I have migrating from v11 to v12.1.1.  Inline style added with body min-width: 992px after build. 

`<style>@charset "UTF-8";@page {size:a3;}body{min-width:992px!important;}</style>`

This causing the problem in responsive devices. Please fix issue and provide a solution.

angular-cli:: 12.1.1

**Comment by alan-agius4** [comment]
In version 12, inlining of critical css has been enabled by default.

Unfortunately, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Please file a new issue and ensure you provide all of the required information when filling out the issue template and provide a minimal reproduction. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
