### ISSUE TITLE
After I upgraded from 11 to 12, the memory footprint increased from 2.75G to 4.1G

### ISSUE THREAD

**Issue by yutao331763646** [angular/angular-cli#21381]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

Yes

### Description

After I upgraded from 11 to 12, the memory footprint increased from 2.75G to 4.1G，

OS: MacOS m1 16G 1T
![image](https://user-images.githubusercontent.com/27717350/126420075-050c4bf5-1d1a-4067-9d20-c4533d949a32.png)

![image](https://user-images.githubusercontent.com/27717350/126420190-a0cf63fe-d50f-40b8-91a6-c8b88e544c99.png)

![image](https://user-images.githubusercontent.com/27717350/126420014-712fba8d-95c4-4e80-b528-ca38dd962d9b.png)

**Comment by alan-agius4** [comment]
Hi @yutao331763646, 

Can you please provide the following;
1. The output of `ng v`
2. Your `angular.json` configuration.
3. Access to the project (Even shared privately), or memory heap snapshots.

Thanks.

**Comment by yutao331763646** [comment]
Hi @alan-agius4 :

Both screenshots are screenshots after the initial ng serve.

and ng -v:

Angular CLI: 12.1.1
Node: 14.16.0
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5








angular.json:
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "newProjectRoot": "projects",
    "projects": {
        "bambooFxNg": {
            "root": "",
            "sourceRoot": "src",
            "projectType": "application",
            "prefix": "app",
            "schematics": {
                "@schematics/angular:component": {
                    "styleext": "scss"
                }
            },
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        "outputPath": "dist/bambooFxNg",
                        "index": "src/index.html",
                        "main": "src/main.ts",
                        "polyfills": "src/polyfills.ts",
                        "tsConfig": "src/tsconfig.app.json",
                        "assets": [
                            "src/favicon.ico",
                            "src/assets",
                            {
                                "glob": "**/*",
                                "input": "./node_modules/@ant-design/icons-angular/src/inline-svg/",
                                "output": "/assets/"
                            },
                            {
                                "glob": "**/*",
                                "input": "./node_modules/monaco-editor/min/vs",
                                "output": "/assets/vs/"
                            }
                        ],
                        "styles": [
                            "src/styles.scss",
                            "src/theme.less"
                        ],
                        "scripts": [],
                     
                        "vendorChunk": true,
                        "extractLicenses": false,
                        "buildOptimizer": false,
                        "sourceMap": true,
                        "optimization": false,
                        "namedChunks": true
                    },
                    "configurations": {
                        "development": {
                            "vendorChunk": true,
                            "extractLicenses": false,
                            "buildOptimizer": false,
                            "sourceMap": true,
                            "optimization": false,
                            "namedChunks": true
                        },
                        "production": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                }
                            ],
                            "optimization": true,
                            "outputHashing": "all",
                            "sourceMap": false,
                            "namedChunks": false,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "budgets": [
                                {
                                    "type": "initial",
                                    "maximumWarning": "10mb",
                                    "maximumError": "25mb"
                                }
                            ]
                        },
                        "hmr": {
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.hmr.ts"
                                }
                            ]
                        }
                    },
                    "defaultConfiguration": "production"
                },
                "serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "defaultConfiguration": "",
                    "options": {
                        "browserTarget": "bambooFxNg:build:development",
                        "disableHostCheck": true
                    },
                    "configurations": {
                        "production": {
                            "browserTarget": "bambooFxNg:build:production"
                        },
                        "hmr": {
                            "hmr": true,
                            "browserTarget": "bambooFxNg:build:hmr"
                        }
                    }
                },
                "extract-i18n": {
                    "builder": "@angular-devkit/build-angular:extract-i18n",
                    "options": {
                        "browserTarget": "bambooFxNg:build"
                    }
                },
                "test": {
                    "builder": "@angular-devkit/build-angular:karma",
                    "options": {
                        "main": "src/test.ts",
                        "polyfills": "src/polyfills.ts",
                        "tsConfig": "src/tsconfig.spec.json",
                        "karmaConfig": "src/karma.conf.js",
                        "styles": [
                            "src/styles.scss"
                        ],
                        "scripts": [],
                        "assets": [
                            "src/favicon.ico",
                            "src/assets"
                        ]
                    }
                },
                "lint": {
                    "builder": "@angular-devkit/build-angular:tslint",
                    "options": {
                        "tsConfig": [
                            "src/tsconfig.app.json",
                            "src/tsconfig.spec.json"
                        ],
                        "exclude": [
                            "**/node_modules/**"
                        ]
                    }
                }
            }
        },
        "bambooFxNg-e2e": {
            "root": "e2e/",
            "projectType": "application",
            "prefix": "",
            "architect": {
                "e2e": {
                    "builder": "@angular-devkit/build-angular:protractor",
                    "options": {
                        "protractorConfig": "e2e/protractor.conf.js",
                        "devServerTarget": "bambooFxNg:serve"
                    },
                    "configurations": {
                        "production": {
                            "devServerTarget": "bambooFxNg:serve:production"
                        }
                    }
                },
                "lint": {
                    "builder": "@angular-devkit/build-angular:tslint",
                    "options": {
                        "tsConfig": "e2e/tsconfig.e2e.json",
                        "exclude": [
                            "**/node_modules/**"
                        ]
                    }
                }
            }
        }
    },
    "defaultProject": "bambooFxNg",
    "cli": {
        "analytics": "2156055e-e0d9-4530-a5c0-adc5b8127c0d"
    }
}

    Thanks.

**Comment by alan-agius4** [comment]
The project does looks like it's properly configured, can you please share access to the project (Even shared privately), or memory heap snapshots from both v11 and v12?

Follow the below steps to generate the snapshots
1. `node --inspect-brk node_modules/@angular/cli/lib/init.js serve `
1. Open Chrome and type `chrome://inspect` in the address bar
1. Click on the `inspect` button from one of your applications in the Remote Target section.
1. Go to `Chrome DevTools` > `Memory`
1. Take a heap snapshot

**Comment by yutao331763646** [comment]
Hi @alan-agius4 
Like this?
![image](https://user-images.githubusercontent.com/27717350/126727919-b13c1159-39df-4692-b3fc-67d87311fec7.png)
Or do you need other operations, such as saving?

**Comment by alan-agius4** [comment]
Yeah, please save it and share it

**Comment by yutao331763646** [comment]
Hi @alan-agius4 

[Heap-20210723T143549.heapsnapshot.zip](https://github.com/angular/angular-cli/files/6866928/Heap-20210723T143549.heapsnapshot.zip)

**Comment by alan-agius4** [comment]
Hi @yutao331763646, 

It appears that you have shared the snapshot at the beginning of the build, can you please share a snapshot at the end of the build?

Does removing the `assets` referenced in `angular.json` reduce the memory usage?

**Comment by splincode** [comment]
Linked: https://github.com/angular/angular-cli/issues/21338

**Comment by alan-agius4** [comment]
@splincode, this seem to be slightly different from the linked issue. The one linked is for production builds, which to an extent increase in memory usage in the main process is expected.

Unfortunately, we don’t have much information on this one though.

**Comment by splincode** [comment]
@alan-agius4 sorry about

**Comment by alan-agius4** [comment]
Closing due to lack of response from the author. 

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
