### ISSUE TITLE
Live reload failing with  webpack 2.1.0-beta.22 , angular-cli: 1.0.0-beta.14

### ISSUE THREAD

**Issue by dessalines** [angular/angular-cli#2139]
I've noticed `ng serve` isn't picking up my file changes, and I have to rerun it every time I make a save. 

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: linux x64
```

**Comment by HamidHabib** [comment]
try: 
`
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@webpack
`

**Comment by HamidHabib** [comment]
`npm uninstall -g angular-cli`
`npm cache clean`
`npm install -g angular-cli@webpack`

**Comment by tchoulihan** [comment]
Just did this, didn't fix the issue. Did changing a file work for you?

**Comment by HamidHabib** [comment]
I didnt change anything. i just run those commands and got everything up and running to (v2.0.0 latest Angular) 
give this a try: 
watchman from npm and watchman from brew are 2 different things

` brew update`
` brew install watchman`

**Comment by tchoulihan** [comment]
I'm on linux. I mean, did you try changing a file to make sure its reloading webpack? I'm guessing the library is watchpack, mines on `watchpack@^0.2.1`. 

I just tried this on two different computers BTW, and live-reload isn't working.

**Comment by jabaa** [comment]
I have the same problem on Xubuntu 16.04. I got the same error message and I installed watchman from source as described in https://ember-cli.com/user-guide/#watchman. The error message is gone but the live reload isn't triggered on file change.

**Comment by osechet** [comment]
This issue looks similar to #1610.

**Comment by dessalines** [comment]
I fixed this by removing running rm -rf node_modules , and reinstalling angular-cli both globally and locally.
