### ISSUE TITLE
Cannot read property 'notifications' of undefined

### ISSUE THREAD

**Issue by danwkennedy** [angular/angular-cli#214]
If the package.json file doesn't have an "angular-cli" field, calls to `ng build` will fail with the following error:

```
TypeError: [DiffingTSCompiler]: Cannot read property 'notifications' of undefined
    at DiffingTSCompiler.showNotification (..../node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:196:38)
```

**Comment by filipesilva** [comment]
I believe this should be "fixed" in the latest master. By fixed though, I mean the notification functionality should be inadvertently gone and thus the notification check does not happen anymore.

@hansl can you chime in? I'm following info from https://github.com/angular/angular-cli/pull/134#issuecomment-185371952 together with https://github.com/angular/angular-cli/pull/206

**Comment by danwkennedy** [comment]
I found this on the latest master as of yesterday morning. I can try again on a later commit in a bit. The work around obviously is to add that option in package so it hasn't blocked me or anything

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/206 happened 16h ago, I think that is when it changed.

**Comment by danwkennedy** [comment]
Looks like it's fixed in 0.0.20 :+1:

**Comment by hansl** [comment]
@filipesilva: Yes, it was fixed. This is a non-issue for now :)

**Comment by filipesilva** [comment]
@hansl If it is indeed removed, then the rest of the changes introduced in the original PR should also be removed.

**Comment by hansl** [comment]
Agreed. If you don't have time for that I can do it.
