### ISSUE TITLE
New flag for component generation skip-style

### ISSUE THREAD

**Issue by MathRobin** [angular/angular-cli#21407]
Hello and many thanks for this great tool !

# 🚀 Feature request

### Command

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Most of my devs are based on bootstrap for style. If i need some specific styles, most of them are just new utilities which I want global so i put them into root styles.scss. I, most of the time (always?), don't need that the CLI creates for me a style file. So each time i generate a new component, the first thing i do is to remove the specific style file and the line into component.ts file. My proposal is to add a flag which just allow to skip this file creation

### Describe the solution you'd like

`--skip-style` as flag like `--skip-import`

### Describe alternatives you've considered

Use inline style flag and just remove the line concerned into component.ts file, but it's not really the ideal solution.

Again many thanks for your work

**Comment by alan-agius4** [comment]
You can use `—style none` option.

**Comment by MathRobin** [comment]
Oh ok, didn't knew, it's not in doc (cf. https://angular.io/cli/generate#component-command)

**Comment by alan-agius4** [comment]
I appears that there is an issue with the docs generation. @gkalpak is looking into it.

**Comment by MathRobin** [comment]
Great ! Many thanks again ! You changed my day ! Have a nice day too
