### ISSUE TITLE
Uncaught TypeError: rootNgProbe.inject is not a function

### ISSUE THREAD

**Issue by marcstee** [angular/angular-cli#2140]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   OSX El Capitan
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli: 1.0.0-beta.14
   node: 6.5.0
   os: darwin x64
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   I updated my project with latest angular-cli (previously was created with beta.webpack.11). Everything looks to be working just fine but following error is shown every time app loads.
4. The log given by the failure. Normally this include a stack trace and some
   more information.
   `angular2.ts:71Uncaught TypeError: rootNgProbe.inject is not a function
   Angular2Adapter._trackAngularChanges @ angular2.ts:71
   Angular2Adapter.setup @ angular2.ts:67
   (anonymous function) @ backend.ts:20
   __webpack_require__ @ bootstrap fc4d934…?76b3:19
   (anonymous function) @ bootstrap fc4d934…?76b3:39
   __webpack_require__ @ bootstrap fc4d934…?76b3:19
   (anonymous function) @ bootstrap fc4d934…?76b3:39
   (anonymous function) @ bootstrap fc4d934…?76b3:39`

**Comment by alexjoverm** [comment]
Same here

**Comment by filipesilva** [comment]
That sounds like it might be a `zone.js` version problem. What version are you using?

**Comment by alexjoverm** [comment]
@filipesilva I was using 0.6.23. Upgraded to 0.6.25 but still happening...

**Comment by marcstee** [comment]
Zone.js v0.6.23.

**Comment by filipesilva** [comment]
No idea of what can cause that... if you get me a repo, I can have a look.

**Comment by alexjoverm** [comment]
@filipesilva you can use the one in the `client` folder of my Footle repo: https://github.com/alexjoverm/Footle/tree/master/client

**Comment by filipesilva** [comment]
Closing as outdated.
