### ISSUE TITLE
The shortDate date pipe does not work when change the Locale_Id default language

### ISSUE THREAD

**Issue by juanjinario** [angular/angular-cli#21403]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

This ([LOCALE_ID](https://angular.io/api/core/LOCALE_ID)) documentation tells me that if we change the locale_Id it will change the default language of all texts that are produced in Angular's default pipes

## 🔬 Minimal Reproduction

1) Create new project
2) Set the new Locale_Id according to the documentation
// App.module
```
providers: [
    {
      provide: LOCALE_ID,
      useValue: 'es',
    },
    {
      provide: DEFAULT_CURRENCY_CODE,
      useValue: 'USD'
    },
  ],
```

3) Place the pipe shortDate
```
// App.component.html
<span>
  {{ myDate | date: 'shortDate' }}
</span>
```

## 🔥 Exception or Error

<pre><code>

Date not displayed
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular v12.1.1
</code></pre>

**Anything else relevant?**

I read that in old versions of angular RegisterLocaleData was used, but in the Angular documentation it says that it is deprecated.
( [RegisterLocaleData](https://angular.io/api/common/registerLocaleData) )

My question is: If the Locale_Id does not work what is the correct way to change the default language?

**Comment by alan-agius4** [comment]
If you are not using the `—localize` option, you need to import the global locale variant.

Got more into see  https://angular.io/guide/i18n#import-global-variants-of-the-locale-data

**Comment by juanjinario** [comment]
The documentation is not clear on this and says that the RegisterLocaleData is deprecated.

I have used what you have sent me and it does not work, it does not change the regional configuration

This is my app.module (I take this https://angular.io/guide/i18n#import-global-variants-of-the-locale-data like reference)
```
import '@angular/common/locales/global/es';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```


I don't want to have more languages ​​(not i18n) but I want to set the project in another regional configuration. 
According to the documentation that should have been enough, and it doesn't work.

If there is another way to do it, tell me
