### ISSUE TITLE
Regression: No more able to have separate baseHref & deployUrl values for serve configuration

### ISSUE THREAD

**Issue by Mereo4** [angular/angular-cli#21411]
### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, since you consider it now deprecated (https://angular.io/cli/serve), but without offering any other way to do it.

### Description

I need to specify `baseHref` and `deployUrl` parameters when deploying an application, but I also wish to serve it locally with no depth in URL (`baseHref` and `deployUrl` => `/`). This will no more be possible since you deprecated this feature.

Similar past issue: #19195

## 🔬 Minimal Reproduction

In any project, set values for `baseHref` and `deployUrl` params when serving your app (so in `serve` configuration).

## 🔥 Exception or Error

<pre><code>
Option "baseHref" is deprecated: Use the "baseHref" option in the browser builder instead.
Option "deployUrl" is deprecated: Use the "deployUrl" option in the browser builder instead.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.5
Node: 14.17.0
Package Manager: npm 7.19.1
OS: win32 x64

Angular: 12.0.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by alan-agius4** [comment]
The recommended approach is to configure these options in the browser builder and point your dev-server builder to use these options

Here's an example;
```json
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
    "scripts": []
  },
  "configurations": {
    "production": {
      "baseHref": "/en",
      "deployUrl": "http://foo.com",
      ...
    },
    "development": {
      "buildOptimizer": false,
      "optimization": false,
      "vendorChunk": true,
      "extractLicenses": false,
      "sourceMap": true,
      "namedChunks": true
    }
  },
  "defaultConfiguration": "production"
},
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "configurations": {
    "production": {
      "browserTarget": "app:build:production"
    },
    "development": {
      "browserTarget": "app:build:development"
    }
  },
  "defaultConfiguration": "development"
},
```

**Comment by Mereo4** [comment]
Yes, I'm already doing this, but the point was to override the values already set in `build` configurations by setting other values in `serve`.

For example, I want to serve my app locally using the "production" environment (for testing/development purpose), so overriding any values set for `baseHref` and `deployUrl` in `build`.

**Comment by alan-agius4** [comment]
In that case you can use multiple configurations which are merged from left to right.

```diff
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
      ...
  },
  "configurations": {
    "production": {
      "baseHref": "/en",
      "deployUrl": "http://foo.com",
      ...
    },
    "development": {
      ...
    },
+    "local: {
+      "baseHref": "/",
+      "deployUrl": "",
+   }
  },
  "defaultConfiguration": "production"
},
"serve": {
  "builder": "@angular-devkit/build-angular:dev-server",
  "configurations": {
    "production": {
+     "browserTarget": "app:build:production,local"
    },
    "development": {
      "browserTarget": "app:build:development"
    }
  },
  "defaultConfiguration": "development"
},
```

**Comment by Mereo4** [comment]
Ah so there is a way, sorry, I didn't see it.

I'm closing this issue now, thank you for your help! ;-)
