### ISSUE TITLE
Incorrect semver ranges used for new projects (~12.2.0-)

### ISSUE THREAD

**Issue by larixer** [angular/angular-cli#21413]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

After generating new project with `@angular/cli@next ng new foobar` command the newly created `package.json` contains dependencies with dangling dashes:
```json
  "dependencies": {
    "@angular/animations": "~12.2.0-",
    "@angular/common": "~12.2.0-",
    "@angular/compiler": "~12.2.0-",
    "@angular/core": "~12.2.0-",
    "@angular/forms": "~12.2.0-",
    "@angular/platform-browser": "~12.2.0-",
    "@angular/platform-browser-dynamic": "~12.2.0-",
    "@angular/router": "~12.2.0-",
    ...
 }
```

The ranges with dangling dashes are invalid according to `semver` package:
```js
const semver = require('semver');

console.log(new semver.Range(`~12.2.0-`));
```
yields:
```
TypeError: Invalid comparator: ~12.2.0-
    at Comparator.parse (/Users/victor/work/semver/node_modules/semver/classes/comparator.js:37:13)
    at new Comparator (/Users/victor/work/semver/node_modules/semver/classes/comparator.js:21:10)
```

## 🔬 Minimal Reproduction

1. Generate new Angular project via:
`npx @angular/cli@next ng new foobar`
2. Check that the dependencies with dangling dashes inside ranges are present.

Note, this is the reason for Yarn 2 E2E Angular over pnpify test failure:
https://github.com/yarnpkg/berry#current-status

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Addressed via https://github.com/angular/angular-cli/pull/21401
