### ISSUE TITLE
How to know if the html file added to assets in angular.json file is picked by ng serve?

### ISSUE THREAD

**Issue by kalyank23** [angular/angular-cli#21417]
We have added a.html file to the assets section in angular.json file and ran "ng serve" command

How do I access this a.html file in web browser? How do I know if "ng serve" command recognized that file? How do I know if I used the correct url to access a.html in web browser?

It is better to provide debug feature for the end users for easy debugging instead of asking angular team  for help

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
