### ISSUE TITLE
Can't make NG_PERSISTENT_BUILD_CACHE work

### ISSUE THREAD

**Issue by QuentinFarizon** [angular/angular-cli#21419]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I am trying to use the new NG_PERSISTENT_BUILD_CACHE=1 variable, but I don't see any improvements at all, so I'm looking to understand why it doesn't work.

I have debugged in Angular code to verify that NG_BUILD_CACHE is set (it is) and that NG_PERSISTENT_BUILD_CACHE is available in process.env (it is).

By debugging, I saw that this cache is supposed to be in node_modules/.cache/angular-webpack
Yet after a build I see nothing there.

What am I missing ?

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.0
Node: 14.17.0
Package Manager: npm 7.20.0
OS: linux x64

Angular: 12.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@angular/fire                   6.1.5
@schematics/angular             12.1.0
rxjs                            7.0.0-beta.10
typescript                      4.2.4
</code></pre>

**Comment by alan-agius4** [comment]
Indeed the cache is saved in `node_modules/.cache/angular-webpack`

Does this behaviour effect all builders in your case, or just a specific one?

Without a reproduction it would be hard to investigate this issue.

**Comment by QuentinFarizon** [comment]
After verifying, it works with serve, but not with build.

I am using Ionic, so I see that behaviour by running `ionic cordova build android` (doesn't work) vs `ionic cordova run android` (works)

**Comment by QuentinFarizon** [comment]
I have reproduced with an blank Ionic project.

```
ionic start myApp blank --type angular
cd myApp
 NG_PERSISTENT_BUILD_CACHE=1 ionic cordova build android
ls node_modules/.cache  -> nothing
```

**Comment by QuentinFarizon** [comment]
@alan-agius4 I see you've been working on this, thank you so much.
I have tested it on my Ionic project, it works fine !

My build time now down from 60 to 37 seconds

**Comment by alan-agius4** [comment]
@guillaumeleone, glad to hear that
