### ISSUE TITLE
PWA cannot be configured with the Module Federation

### ISSUE THREAD

**Issue by smasala** [angular/angular-cli#21422]
If the application is setup to use the module federation, the bootstrap section of the application is shifted out of the `main.ts` file into a `bootstrap.ts` file (https://github.com/angular-architects/module-federation-plugin)

**main.ts (in it's entirety):**
```typescript
import('./bootstrap').catch((err) => console.error(err));
```

The following function `findBootstrapModuleCall` doesn't look into any nested `import` statements and returns with the error `Bootstrap call not found` when running `ng add @angular/pwa --project myProject`:
https://github.com/angular/angular-cli/blob/d05559795487095d1b85f27a8159e4adde7b848a/packages/schematics/angular/utility/ng-ast-utils.ts#L54

**Comment by logitimate** [comment]
We just ran into this issue as well. Our internal ng add for our design system in a federated solution gets the same error. Would be nice to get this solved!

**Comment by manfredsteyer** [comment]
Please have a look here:
https://github.com/angular-architects/module-federation-plugin/issues/93

**Comment by alan-agius4** [comment]
Thanks @manfredsteyer for sharing that.

Closing as per above and since Module Federation and specific Webpack features are not supported by the Angular team.

**Comment by smasala** [comment]
@alan-agius4 is "closed" really the correct state of this bug? The link above by @manfredsteyer is surely a workaround and not an ideal solution?

**Comment by alan-agius4** [comment]
The Angular PWA schematic is intended to be used with the official builders. Third party tooling can easily extend the schematic functionality and customize it as needed.

The non standard bootstrapping is required by 3rd party builders to use Webpack’s specific features. Both of which are not supported by the Angular team. Please note that Webpack is to be considered an implementation detail in the CLI that can be replaced in the future.
