### ISSUE TITLE
Serve and build output different assets

### ISSUE THREAD

**Issue by originalfrostig** [angular/angular-cli#21427]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.x

### Description

Due to an update of copy-webpack-plugin (from 6.2.1 to 9.0.0 in version 12.1.x) the cli now outputs different assets when serving and building an application. This only occurs, when multiple asset configuration have the same output folder and use globs matching files with equal names. The reason for this is that copy-webpack-plugin (which is used when running `ng serve`) applies all globs in parallel and stores the result into a shared array. This leads to a race condition, as the order in which the asset files are copied to the output folder depend on how fast each glob is evaluated. This is not the case with `ng build` as the copy-webpack-plugin is not used at all, but all assets are copied sequentially by a utils function.

## 🔬 Minimal Reproduction

I created a [reproduction repo](https://github.com/originalfrostig/angular-assets-rc), with two asset configurations, where the first one should be overwritten by the second one. This is only the case for `ng build` and not for `ng serve`, due to a nested folder inside `src/assets` as it increases the duration for evaluating the first glob.

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.3
Node: 14.17.3
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.3.5

</code>
</pre>

**Anything else relevant?**
In my opinion this bug could be solved by utilizing the priority property, when converting `AssetPatternClass` (@angular/cli) to `Pattern` (copy-webpack-plugin). As a result the array mentioned above would be reordered before the files are copied, leading to a consistent behaviour when serving and building an application. If you agree with me this is a bug and should be fixed, I could create a PR.

**Comment by alan-agius4** [comment]
Hi @originalfrostig, indeed using the `priority` option should fix this. Feel free to create a PR.
