### ISSUE TITLE
Not able to create new angular project after upgrade 

### ISSUE THREAD

**Issue by santoshgistto** [angular/angular-cli#2144]
1. OS - ubuntu 14.04

2. ng --version :  not able to get version itself
3. Repro steps  - after install  ng --version 
4.Logs: 
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12

npm version : 3.10.3
node version : 6.5.0

**Comment by loiane** [comment]
+1
Same behaviour with Mac Os El Captan.

Executed
```
npm uninstall -g angular-cli
npm cache clean
```
before all attempts.
Tried these 3 install commands and error is the same:
```
npm install -g angular-cli@webpack
npm install -g angular-cli@latest
npm install -g angular-cli
```
Also tried `npm install --save-dev angular-cli@webpack`and `npm install -g angular-cli@latest` after global install inside a project and the command also did not work.

**Comment by andrevmatos** [comment]
Looks like duplicate of #2135

**Comment by kumarryogeshh** [comment]
Not able to install angular-cli
OS X El Captain
Version 10.11.2

$ sudo npm install -g angular-cli@latest
npm WARN peerDependencies The peer dependency webpack@1.x.x || 2.x.x included from string-replace-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@* included from html-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.4.4 (node-v46 ABI) (falling back to source compile with node-gyp) 
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli@latest"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.3 wants webpack@1.x.x || 2.x.x
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.4 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:

**Comment by gengiscb** [comment]
Same problem, OS: ubuntu 16.04, node: 6.5.0, npm : 3.10.3
I Solved the issue as follows:

- cd /usr/local/lib/node_modules/angular-cli/
- sudo npm install --save process-nextick-args
- sudo npm install --save util-deprecate

**Comment by albanx** [comment]
I solved by running the cli upgrade steps:

Global package:

```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
```
**IMPORTANT:** Local project package:

```
rm -rf node_modules dist tmp
npm install --save-dev angular-cli@latest
ng init
```

**Comment by loiane** [comment]
Update [workaround]: updating exiting angular-cli projects or as described above, creating a new directory and executing `ng init` is working fine.
Will use angular-cli with `ng init` while commands executed outside existing projects do not work.

**Comment by programmerinprogress** [comment]
Make sure you don't have a node_modules folder in your current directory that contains angular-cli, node will default to that one, and if it's outdated, you're going to get that error no matter how many times you reinstall node, I just found that out the hard way!

**Comment by filipesilva** [comment]
I could not reproduce this on beta.15 myself. If you still get this with the latest version, please let me know and I will reopen the issue.

**Comment by loiane** [comment]
Confirmed. Fixed on beta 15.

**Comment by santoshgistto** [comment]
@filipesilva  still i am facing the issue after upgrade
$ ng new myNewApp
result : Error 

there is no logs

**Comment by JanStureNielsen** [comment]
@santoshgistto -- what does `ng --version` say when you're not inside an existing node project?

**Comment by santoshgistto** [comment]
@JanStureNielsen 
ng --version 

angular-cli: 1.0.0-beta.15
node: 6.6.0
os: linux x6

**Comment by JanStureNielsen** [comment]
@santoshgistto -- so the original problem you reported in this issue is now gone, right? And this issue is closed. I suggest you open a question on StackOverflow for better support...

Does the `ng init` work-around sited above work for you?

    mkdir foo && cd foo && ng init

FWIW, my OpenSUSE 13.2 configuration is working fine with Node 6.5:

    jan@linux-zd16:~/src/fm-repos> ng --version
    angular-cli: 1.0.0-beta.15
    node: 6.5.0
    os: linux x64

so you might try downgrading Node to 6.5 -- remember to reinstall Angular CLI after your downgrade.

**Comment by thelgevold** [comment]
I ran into this issue as well, but it was a result of a lingering npm link against an earlier version from master a long time ago.

After doing `npm unlink angular-cli` I was able to install the latest version.

**Comment by elvisfernandes** [comment]
Thanks @thelgevold. `npm unlink angular-cli`, uninstall, cache clear and reinstall did the trick for me.

**Comment by Larisho** [comment]
This is still happening to me. I have tried all the suggestions in the comments and that didn't work. I have also tried completely uninstalling Node and NPM and reinstalling and that still didn't work.

CLI version: 1.0.0-beta.24
Node version: 6.10.3
NPM version: 4.6.1
OS: Win7

Upgrading to latest version is impossible at the moment because of other company dependencies.
