### ISSUE TITLE
First ng serve builds twice in quick succession

### ISSUE THREAD

**Issue by KissBalazs** [angular/angular-cli#21441]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] serve

### Is this a regression?
I am not sure.

### Description
After a fresh `npm i` install on a new repository, the first `ng serve` builds the app twice. 

## 🔬 Minimal Reproduction

1. ng new 
2. proceed to fill some default data, cd into the folder
3. ng serve

## 🔥 Exception or Error

<pre>
test$ ng serve
⠋ Generating browser application bundles (phase: setup)...Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
✔ Browser application bundle generation complete.

Initial Chunk Files | Names         |      Size
vendor.js           | vendor        |   2.09 MB
polyfills.js        | polyfills     | 128.54 kB
main.js             | main          |  54.68 kB
runtime.js          | runtime       |   6.56 kB
styles.css          | styles        | 119 bytes

                    | Initial Total |   2.27 MB

Build at: 2021-07-28T13:56:34.696Z - Hash: 9ae2012d70b750fb75b5 - Time: 10338ms

** Angular Live Development Server is listening on localhost:33525, open your browser on http://localhost:33525/ **

✔ Compiled successfully.
✔ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2021-07-28T13:56:35.493Z - Hash: 1b60cd5df3d3d625946b - Time: 439ms

✔ Compiled successfully.
</pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.3
Node: 16.3.0 (Unsupported)
Package Manager: npm 7.20.1
OS: linux x64

Angular: 12.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.3
@angular-devkit/build-angular   12.1.3
@angular-devkit/core            12.1.3
@angular-devkit/schematics      12.1.3
@schematics/angular             12.1.3
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

We are using different scripts which listens to the output of ng serve (for Cypress e2e test running). The initial "double" compilation causes our scripts to immediatly re-start. 

Tried using `ng serve --live-reload=false` but it had no effect either.

This seems to be happening only upon the first build in a clean folder. After the first `ng serve` all subsequent `ng serve` only outputs "Build at: .." and "Compiled successfully." etc. only once. 

Deleting the `node_modules/` folder, and executing a new `npm ci` causes the next `ng serve` to reproduce the said problem.

**Comment by alan-agius4** [comment]
This is working as expected.

See: https://github.com/angular/angular-cli/issues/21361
