### ISSUE TITLE
debugging with webstorm?

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#2145]
How do we debug with webstorm?
for example, one of things we need to do is configure
```
devtool: "source-map"1
```
which we don't have access to in ng-cli
did anyone configure debugging with webstorm with ng-cli?

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean

**Comment by aszechlicki** [comment]
I followed [this](https://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/) guide and made it working without problem

**Comment by born2net** [comment]
do you mind sharing your config?
in other words, what are supposed to map? the dist dir? or src dir? see attached image
tx for replying

![capture](https://cloud.githubusercontent.com/assets/5090936/18561932/b45bdfc6-7b36-11e6-8572-5525814e5210.PNG)


Sean

**Comment by aszechlicki** [comment]
you need to map location of you sources, like this:
![capture](https://cloud.githubusercontent.com/assets/9299507/18562685/14a6965c-7b85-11e6-81f7-b616efa17467.png)

**Comment by born2net** [comment]
tx ya tried it with no luck
webpack:////msweb/testNgCli (that's the root folder of my project)
did you need to enable source map somewhere?
I do have it enabled in tsconfig
```
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

```
but do we need to enable it somewhete for webpack?

**Comment by aszechlicki** [comment]
i didn't change anything else in config
in fact, my .tsconfig looks exactly like yours

**Comment by born2net** [comment]
mm ok tx :/

**Comment by born2net** [comment]
ok got it working tx to your image, needed to map both root and /src
TX!!!!
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate
Regards,

Sean
