### ISSUE TITLE
ng serve crashes on TS errors even with emitOnErrors: true

### ISSUE THREAD

**Issue by goldylucks** [angular/angular-cli#21453]
# 🐞 Bug report

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Don't know, I'm new to angular

### Description

even after extending angular's webpack config with `@angular-builders/custom-webpack` and configuring:
```
optimization: {
    emitOnErrors: true,
  },
```

`ng serve` still crashes on typescript errors. I have double checked and the webpack config is being loaded.

## 🔬 Minimal Reproduction

```
$ ng new foo
$ cd foo
$ npm install --save-dev `@angular-builders/custom-webpack`
# create webpack.config.js with
module.exports = {
  optimization: {
    emitOnErrors: true,
  },
}
# angular.json: change architect.build.builder to
"@angular-builders/custom-webpack:browser"
# angular.json: add to architect.builder.options:
            "customWebpackConfig": {
              "path": "./webpack.config.js"
            },
$ npm start
```
then create a typescript anywhere in the project

## 🔥 Exception or Error
whatever typescript error you'll create in the previous step

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.5
Node: 14.16.1
Package Manager: npm 7.15.0
OS: linux x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by alan-agius4** [comment]
Hi @goldylucks, 

The Angular tooling team doesn't support custom Webpack configurations. That said, from the looks of it you likely need to disable the dev-server `overlay`.
