### ISSUE TITLE
Angular cli 11 changes syntax after symbol '<' in jsp pages. 

### ISSUE THREAD

**Issue by QuaziBit** [angular/angular-cli#21462]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 In my project Java jsp page used as index page. The jsp page has Java block that that starts with '<%' and ends with '%>' tags. Between that tags I have List<SomeType>, so after running ng build --prod it will be changed to List<sometype>. For some reason ng build will make SomeType lover case that breaks jsp page.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Same as https://github.com/angular/angular-cli/issues/20276#issuecomment-800053465
