### ISSUE TITLE
Example Project to figure out angular-cli fails

### ISSUE THREAD

**Issue by lebsral** [angular/angular-cli#2147]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Mac OSX 10.11.6

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Yes cli.  See https://github.com/lebsral/FireBase2Example
4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
ection_capabilities.js:84Uncaught TypeError: Cannot read property 'annotations' of undefined
client?93b6:38[WDS] Errors while compiling.
VM47:27 [default] /Users/larsb/Documents/mycode/FireB3/src/app/app.component.ts:5:12 
Cannot find name 'module'.window.console.error @ VM47:27
VM47:27 [default] /Users/larsb/Documents/mycode/FireB3/src/app/app.component.ts:7:12 
Cannot find name 'require'.window.console.error @ VM47:27
VM47:27 [default] /Users/larsb/Documents/mycode/FireB3/src/app/app.component.ts:8:11 
Cannot find name 'require'.window.console.error @ VM47:27
VM47:27 [default] /Users/larsb/Documents/mycode/FireB3/src/main.ts:6:9 
Module '"/Users/larsb/Documents/mycode/FireB3/src/app/index"' has no exported member 'AppModule'.
```

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

I created a new cli based Angular FireBase installation.  See the errors above when I got done with the first page of the getting started guide.
Here it is...
https://github.com/lebsral/FireBase2Example

**Comment by filipesilva** [comment]
You'll have to ask the authors of this guide really... I don't know what the guide asks you to do, so I don't know how it goes wrong.
