### ISSUE TITLE
Proposal: Use ExtractTextPlugin for global styles

### ISSUE THREAD

**Issue by jimitndiaye** [angular/angular-cli#2148]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
1.0.0-beta.14

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
 Create a new app using ```ng new my-app```.
 Run ```ng serve```
 styles.css is loaded using style-loader causing flash during initial load

4. The log given by the failure. Normally this include a stack trace and some
   more information.
n/a

5. Mention any other details that might be useful.
Especially for production builds you'd get better UX by loading the styles as a static resource rather than waiting for JS to load and run. Even in dev builds live-reload still works with static files using ExtractTextPlugin
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Would you be willing to make a PR for this?

/cc @TheLarkInn

**Comment by jimitndiaye** [comment]
@filipesilva submitted PR #2646
