### ISSUE TITLE
Schematic input does not validate, data path must not have additional properties(spec)

### ISSUE THREAD

**Issue by blathersbugs** [angular/angular-cli#21489]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
yes

 Yes, the previous version in which this bug was not present was: ....
^11.2.12
### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

add to angular.json:
"@schematics/angular:component": {
          "spec": false
        }

run ng generate component blah

## 🔥 Exception or Error

<pre><code>

Schematic input does not validate against the Schema: {"style":"scss","spec":false,"name":"_component/ListNotificationsComponent","project":"xxxx"}
Errors:

  Data path "" must NOT have additional properties(spec).
</code></pre>

## 🌍 Your Environment
Schematic input does not validate against the Schema: {"style":"scss","spec":false,"name":"_component/ListNotificationsComponent","project":"hp-supplies-dataprovider"}
Errors:

  Data path "" must NOT have additional properties(spec).
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.1.4
Node: 14.17.3
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

seems to be basically the same as https://github.com/angular/angular-cli/issues/20848 which is already closed and locked

solution is probably the same, remove the setting by a migration
If I remove the spec: false, it works as expected
It would probably be a good idea to check if any other options have been removed and add migrations for them as well

**Comment by alan-agius4** [comment]
The spec option was removed in version 9 and we already have a migration that replaces the usage of this when upgrading from version 8 to 9.

 https://github.com/angular/angular-cli/blob/268a03b63094d9c680401bc0977edafb22826ce3/packages/schematics/angular/migrations/update-9/schematic-options.ts#L51

You can re-run the migration by using the below command

```
ng update @angular/cli —-migrate-only schematic-options-9
```

**Comment by blathersbugs** [comment]
It is possible one of the other developers updated angular outside of ng update.  Maybe it would be worth looking into a way to detect this and print a warning message.
