### ISSUE TITLE
How to use http in v1.0.0-beta.11-webpack.8  version

### ISSUE THREAD

**Issue by Hitman666** [angular/angular-cli#2149]
I initially tested and wrote a [tutorial for Pluralsight](http://tutorials.pluralsight.com/front-end-javascript/getting-started-with-angular-2-by-building-a-giphy-search-application) by using the version `1.0.0-beta.9`.

However, I've tried today with the [latest version](https://github.com/angular/angular-cli/releases/tag/v1.0.0-beta.11-webpack.8) and for the life of me I can't figure out how to use http to call some service. Is there maybe some example that you can share please?

---
Additional info:

1. OS
Mac OSX (El Capitan - 10.11.4)

2. Versions:
angular-cli: 1.0.0-beta.14
node: 4.4.2
os: darwin x64

3. Repro steps: Tried various ways and tuts to inject http but to no avail.

I'm not like looking for some hand-holding or something, am just looking for help to get going in the right direction.

Above all, thank you for this awesome project!

**Comment by JanStureNielsen** [comment]
The issue tracker is for bugs and feature requests in Angular CLI. Please consider posting a question on StackOverflow for these types of support requests.  You can find some [Angular 2 HTTP documentation here](https://angular.io/docs/ts/latest/guide/server-communication.html).

**Comment by Hitman666** [comment]
Ok, I figured what was the issue, so I may as well explain it here if someone else stumbles upon this issue themselves.

So, when I installed angular-cli with `npm install -g angular-cli` I haven't at first noticed this error:
`UNMET PEER DEPENDENCY webpack@2.1.0-beta.22`

What I ended up doing now was `npm install webpack -g && npm install webpack --save-dev` and now I can normally include Http into my component like this: `import { Http, Response } from '@angular/http';` and then use it within a class like this:

```
import { Component } from '@angular/core';
import { Http, Response } from '@angular/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';

  constructor(private http: Http){
  	let link = 'http://api.giphy.com/v1/gifs/search?api_key=dc6zaTOxFJmzC&q=';
		let apiLink = link + 'cats';

		this.http.request(apiLink).subscribe((res: Response) => {
			console.log(res.json());
		});
  }

}
```

Hope this helps someone.
