### ISSUE TITLE
Before and After hook in schematics

### ISSUE THREAD

**Issue by vaibhavsingh97** [angular/angular-cli#21494]
# 🚀 Feature request

**Problem:** Currently, Schematics can create files, refactor existing files, move files around and scaffold files. There is no way to show post message after schematics are done with installing packages, and scaffolding required files/

**Requirement:** Pre and post-hooks that can help in tasks like showing post messages after schematics done with scaffolding files, and installing packages, etc

I had found that schematics future development (https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/schematics/README.md#future-work) talks about this feature.

If this is already available, how can I use this? if not, then what's the estimated time for this feature to be released

**Comment by alan-agius4** [comment]
Hi @vaibhavsingh97, 

We do allow invoking a set of pre-defined tasks https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/schematics/tasks

You can use them in your schematic using the `context.addTask` API. 

```ts
import { NodePackageInstallTask } from '@angular-devkit/schematics/tasks';

function run() {
    return  (tree, context) => {
        context.addTask(new NodePackageInstallTask());
    };
}
```

Regarding custom tasks there is already a feature request https://github.com/angular/angular-cli/issues/12678 but there isn't any ETA for that.
