### ISSUE TITLE
Allow setting noEmitOnError 

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular-cli#21492]
Every typescript error causes the compiler to fail. This is very annoying when working in dev mode, because we don't want to spend time fixing these errors now.  For example:

> Property 'foo' is declared but its value is never read.

It will be really helpful to add a new configuration in angular.json that can disable this behavior based on environment.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/19948
