### ISSUE TITLE
Beta 14 build fails - @angular-cli/ast-tools

### ISSUE THREAD

**Issue by remotevision** [angular/angular-cli#2150]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Occurs on Mac OSX (El Capitan) and also Windows.

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```node v6.5.0```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Simply trying to ```npm install -g angular-cli```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 no such package available : @angular-cli/ast-tools
npm ERR! 404 
npm ERR! 404  '@angular-cli/ast-tools' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-cli'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by filipesilva** [comment]
Can you try the following set of steps?
```
npm uninstall -g angular-cli
npm cache clear
npm install -g angular-cli
```

**Comment by iradul** [comment]
I'm also getting this error on Windows and node 4 though :
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ ... \\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.j
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code E404

npm ERR! 404 no such package available : @angular-cli/ast-tools
npm ERR! 404
npm ERR! 404  '@angular-cli/ast-tools' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-cli'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by iradul** [comment]
Looks like this is related to a usage of private npm repository where private repo essentially is not been able to proxy scoped packages.
Quick workaround is to just temporarily remove private repo and then add it back later after you install `angular-cli`.
In my case (Windows) I just moved `.npmrc` file elsewhere from `%USERPROFILE%` directory and moved it back afterwards.

**Comment by filipesilva** [comment]
Oh that makes sense! I had heard that some private npm repos didn't support scoped packages well.

Closing then, there isn't anything we can do regarding that.

**Comment by Anthropic** [comment]
For anyone who finds this issue while searching, another temporary solution is to bypass a local npm proxy repo for the packaged repos. For the current version 1.0.0-beta.18 that only requires 4 bypass:

npm config set "@angular:registry" http://registry.npmjs.org/
npm config set "@angular-cli:registry" http://registry.npmjs.org/
npm config set "@ngtools:registry" http://registry.npmjs.org/
npm config set "@types:registry" http://registry.npmjs.org/
