### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined (v7-lts)

### ISSUE THREAD

**Issue by totszwai** [angular/angular-cli#21503]
Could an expert port this fix https://github.com/angular/angular-cli/pull/15705 to @angular-devkit/build-optimizer 0.13 (v7-lts)?

Related issue reference: https://github.com/angular/angular-cli/issues/15703

**Comment by alan-agius4** [comment]
Version 7 is no longer supported. Please update to a more recent Angular CLI version.

See: https://angular.io/guide/releases#support-policy-and-schedule
