### ISSUE TITLE
Unmet peer dependency ajv@6

### ISSUE THREAD

**Issue by ThomasKruegl** [angular/angular-cli#21509]
# 🐞 Bug report

### Command (mark with an `x`)
- [X] new
### Is this a regression?
 Yes, the previous version in which this bug was not present was:
cli@11.2.14 does not have that behaviour, i did not test older versions of cli@12

### Description
@angular-devkit/build-angular@12.2.0 uses (in the dependency chain) schema-utils@2.7.1, which has a peer dependency to ajv@6.12.6

@angular-devkit/build-angular@12.2.0 brings in  @angular-devkit/core, which in turn brings ajv, but version 8.

This leads to an unmet dependency warning from npm - and possibly broken features in schema-utils.

## 🔬 Minimal Reproduction

- use version 12.2.0 of @angular/cli
- "ng new my-app"
- in the newly created app, run "npm install"
- -> warning about unmet peer dependency

## 🔥 Exception or Error

<pre><code>
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.0
Node: 12.20.1
Package Manager: npm 6.14.10
OS: win32 x64

Angular: 12.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Comment by alan-agius4** [comment]
This seems a defect of NPM 6 module hoisting logic. Thus, I suggest to update to NPM 7 or use an alternate package manager such as Yarn.

See below;

NPM 6
```
npm ls ajv
├─┬ @angular-devkit/build-angular@12.2.0
│ ├─┬ @angular-devkit/core@12.2.0
│ │ ├── ajv@8.6.2
│ │ └─┬ ajv-formats@2.1.0
│ │   └── ajv@8.6.2  deduped
│ ├─┬ @jsdevtools/coverage-istanbul-loader@3.0.5
│ │ └─┬ schema-utils@2.7.1
│ │   └── UNMET PEER DEPENDENCY ajv@6.12.6
│ ├─┬ copy-webpack-plugin@9.0.1
│ │ └─┬ schema-utils@3.1.1
│ │   └── UNMET PEER DEPENDENCY ajv@6.12.6
│ ├─┬ css-minimizer-webpack-plugin@3.0.2
│ │ └─┬ schema-utils@3.1.1
│ │   └── UNMET PEER DEPENDENCY ajv@6.12.6
│ ├─┬ mini-css-extract-plugin@2.1.0
│ │ └─┬ schema-utils@3.1.1
│ │   └── UNMET PEER DEPENDENCY ajv@6.12.6
│ ├─┬ terser-webpack-plugin@5.1.4
│ │ └─┬ schema-utils@3.1.1
│ │   └── UNMET PEER DEPENDENCY ajv@6.12.6
│ ├─┬ webpack@5.47.1
│ │ └─┬ schema-utils@3.1.1
│ │   └── UNMET PEER DEPENDENCY ajv@6.12.6
│ ├─┬ webpack-dev-middleware@5.0.0
│ │ └─┬ schema-utils@3.1.1
│ │   └── UNMET PEER DEPENDENCY ajv@6.12.6
│ └─┬ webpack-dev-server@3.11.2
│   └─┬ schema-utils@1.0.0
│     └── UNMET PEER DEPENDENCY ajv@6.12.6
└─┬ @angular/cli@12.2.0
  └─┬ pacote@11.3.5
    └─┬ @npmcli/run-script@1.8.5
      └─┬ node-gyp@7.1.2
        └─┬ request@2.88.2
          └─┬ har-validator@5.1.5
            └── ajv@6.12.6

npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
npm ERR! peer dep missing: ajv@^6.9.1, required by ajv-keywords@3.5.2
```
NPM 7 
```
npm ls ajv
ajv-test@0.0.0 /Users/alanagius/cli-reproductions/ajv-test
├─┬ @angular-devkit/build-angular@12.2.0
│ ├─┬ @angular-devkit/core@12.2.0
│ │ ├─┬ ajv-formats@2.1.0
│ │ │ └── ajv@8.6.2 deduped
│ │ └── ajv@8.6.2
│ ├─┬ @jsdevtools/coverage-istanbul-loader@3.0.5
│ │ └─┬ schema-utils@2.7.1
│ │   ├─┬ ajv-keywords@3.5.2
│ │   │ └── ajv@8.6.2 deduped invalid: "^6.9.1" from node_modules/ajv-keywords
│ │   └── ajv@6.12.6
│ ├─┬ copy-webpack-plugin@9.0.1
│ │ └─┬ schema-utils@3.1.1
│ │   └── ajv@6.12.6
│ ├─┬ css-minimizer-webpack-plugin@3.0.2
│ │ └─┬ schema-utils@3.1.1
│ │   └── ajv@6.12.6
│ ├─┬ mini-css-extract-plugin@2.1.0
│ │ └─┬ schema-utils@3.1.1
│ │   └── ajv@6.12.6
│ ├─┬ terser-webpack-plugin@5.1.4
│ │ └─┬ schema-utils@3.1.1
│ │   └── ajv@6.12.6
│ ├─┬ webpack-dev-middleware@5.0.0
│ │ └─┬ schema-utils@3.1.1
│ │   └── ajv@6.12.6
│ ├─┬ webpack-dev-server@3.11.2
│ │ └─┬ schema-utils@1.0.0
│ │   ├─┬ ajv-errors@1.0.1
│ │   │ └── ajv@8.6.2 deduped invalid: "^6.9.1" from node_modules/ajv-keywords
│ │   └── ajv@6.12.6
│ └─┬ webpack@5.47.1
│   └─┬ schema-utils@3.1.1
│     └── ajv@6.12.6
└─┬ @angular/cli@12.2.0
  └─┬ pacote@11.3.5
    └─┬ @npmcli/run-script@1.8.5
      └─┬ node-gyp@7.1.2
        └─┬ request@2.88.2
          └─┬ har-validator@5.1.5
            └── ajv@6.12.6
```

Yarn
```
yarn why ajv
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "ajv"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ajv@6.12.6"
info Has been hoisted to "ajv"
info Reasons this module exists
   - Hoisted from "schema-utils#ajv"
   - Hoisted from "@angular-devkit#build-angular#webpack-dev-server#schema-utils#ajv"
   - Hoisted from "@angular-devkit#build-angular#babel-loader#schema-utils#ajv"
   - Hoisted from "@angular-devkit#build-angular#@jsdevtools#coverage-istanbul-loader#schema-utils#ajv"
   - Hoisted from "@angular#cli#pacote#@npmcli#run-script#node-gyp#request#har-validator#ajv"
info Disk size without dependencies: "1.12MB"
info Disk size with unique dependencies: "1.89MB"
info Disk size with transitive dependencies: "1.93MB"
info Number of shared dependencies: 5
=> Found "@angular-devkit/core#ajv@8.6.2"
info This module exists because "@angular-devkit#build-angular#@angular-devkit#core" depends on it.
info Disk size without dependencies: "2.4MB"
info Disk size with unique dependencies: "3.1MB"
info Disk size with transitive dependencies: "3.14MB"
info Number of shared dependencies: 5
=> Found "ajv-formats#ajv@8.6.2"
info This module exists because "@angular-devkit#build-angular#@angular-devkit#core#ajv-formats" depends on it.
✨  Done in 0.65s.
```

**Comment by ThomasKruegl** [comment]
Hm. Just had a look at npm7, the reason that it works with npm 7 is that npm now automatically installs (or tries to install) peer dependencies. Personally i don't think that is a good solution, but that aside:
In my current project we have a specific reason *not* to install specific peer dependencies (of not angular related packages). So if we would upgrade to npm 7, we would probably use "-legacy-peer-deps", problem still there.

We could solve this by adding ajv to our direct dependencies, but we do not actually need ajv. And if we did, we probably would want to have a newer version, making this solution impossible.

In my opinion, angular/cli should still take care that it brings in an ajv version that satisfies the peer dependency of its dependencies, and not rely on npm installing it additionally.

**Comment by clydin** [comment]
All of the versions referenced above of `schema-utils` have a direct dependency on a version of `ajv` that would satisfy the `ajv-keywords` peer dependency. ([1.0.0](https://github.com/webpack/schema-utils/blob/6ca2322d4c8c5818c4a8f71328ac88e3507ec4e8/package.json#L20), [2.7.1](https://github.com/webpack/schema-utils/blob/102d170506640346b8269d7e38a042b6b5b3a444/package.json#L46), [3.1.1](https://github.com/webpack/schema-utils/blob/faadaf950afd79352d7f9d0c3e0601b7ee45c5f2/package.json#L49))
Unfortunately, as mentioned, npm 6.x is not placing that version of `ajv` in the proper location to allow the peer dependency to be satisfied.

**Comment by ThomasKruegl** [comment]
Oh wow, i missed that, sorry. I think in this case that's exactly one of the use cases why npm 7 changed the peer dependency handling, as described here:
https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md#motivation

Thanks for the quick replies!
We have to see how we solve this, but closing this within angular/cli context now. :)

**Comment by clydin** [comment]
No problem at all.  Troubleshooting dependency issues such as this can be quite complicated given the large transitive dependencies trees.
