### ISSUE TITLE
Angular CLI 12.2.0 fails "ng add" with "Command aborted." without confirmation prompt

### ISSUE THREAD

**Issue by Jehoel** [angular/angular-cli#21512]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

**Did this behavior use to work in the previous version?**

Yes

**Yes, the previous version in which this bug was not present was: ....**

v11 (I haven't used other v12.x versions)

### Description and 🔬 Minimal Reproduction

* Running `ng add` always fails with "Command abort.ed" unless I add `--skip-confirmation`.
* Additionally, there is no difference in output with or without `--verbose`.

For example:

```
$ cd ~

$ mkdir test

$ cd test

$ npm install -g @angular/cli
# etc

$ ng add @angular-eslint/schematics@12.2.0
- Determining package manager...
i Using package manager: npm
- Loading package information from registry...
√ Package information loaded.
Command aborted.

$ ng add @angular-eslint/schematics --skip-confirmation
- Determining package manager...
i Using package manager: npm
- Searching for compatible package version...
√ Found compatible package version: @angular-eslint/schematics@12.3.1.
- Loading package information from registry...
√ Package information loaded.
- Installing package...
√ Package successfully installed.

    All @angular-eslint dependencies have been successfully installed 🎉

    Please see https://github.com/angular-eslint/angular-eslint for how to add ESLint configuration to your project.


    We detected that you have a single project in your workspace and no existing linter wired up, so we are configuring ESLint for you automatically.

    Please see https://github.com/angular-eslint/angular-eslint for more information.

CREATE .eslintrc.json (984 bytes)
UPDATE package.json (1445 bytes)
UPDATE angular.json (3333 bytes)
- Installing packages (npm)...
√ Packages installed successfully.
```

## 🌍 Your Environment

<pre><code>
$ node --version
v14.17.4

$ npm --version
7.20.3

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.2.0
Node: 14.17.4
Package Manager: npm 7.20.3
OS: win32 x64

Angular: 12.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

* Windows 10 x64
* Using git-bash as my shell in a mintty window.

------------------

I fiddled with `add-impl.js` to see why it wasn't prompting and I think the problem is `add-impl.js` has `if( !tty_1.isTTY ) {` but `prompt.js` has `if (!tty_1.isTTY()) {`, so is `isTTY` a function or a getter-property?

**Comment by Jehoel** [comment]
@alan-agius4 The `isTTY()` change you just made doesn't work for me because when I run it with my additions below, I get `typeof process.stdout.isTTY` is 'undefined'.

```
    this.logger.error( options.skipConfirmation ? 'options.skipConfirmation == true' : 'options.skipConfirmation == false' );
    this.logger.error( typeof tty_1.isTTY );
    this.logger.error( 'tty_1.isTTY ==' + ( tty_1.isTTY ? 'isTTY' : 'is NOT TTY' ) );
    this.logger.error( 'tty_1.isTTY() ==' + ( tty_1.isTTY() ? 'isTTY' : 'is NOT TTY' ) );
    this.logger.error( 'process.stdout.isTTY type == ' + ( typeof process.stdout.isTTY ) );
    this.logger.error( 'process.stdout.isTTY == ' + ( process.stdout.isTTY ) );
```

Gives me this output:

```
options.skipConfirmation == false
function
tty_1.isTTY ==isTTY
tty_1.isTTY() ==is NOT TTY
process.stdout.isTTY type == undefined
process.stdout.isTTY == undefined

```

**Comment by Jehoel** [comment]
After some more digging, when I try to get `stdout.isTTY` from anywhere before `add-impl.js` runs, such as in `init.js` or even in `ng` itself, I get errors.

Here's my code (in `C:\Users\me\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng`):

```
process.stdout.write("------------------------\n");
console.trace( "Stack trace\n" );
process.stderr.write("Writing to stderr\n");
process.stdout.write("Writing to stdout\n");
process.stdout.write("typeof stdout.isTTY === '" + typeof process.stdout.isTTY + "'\n");
try { process.stdout.write( process.stdout.isTTY ); }
catch( err ) { process.stdout.write( "Couldn't get isTTY: " + err ); }
process.stdout.write("\n");
process.stdout.write("------------------------\n");
```

Gives me this output:

```
$ ng add @angular-eslint/schematics
------------------------
Trace: ng: Stack trrace
    at Object.<anonymous> (C:\Users\David\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
Writing to stderr
Writing to stdout
typeof stdout.isTTY === 'undefined'
Couldn't get isTTY: TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined
```

And yet, running `node -p -e "process.stdout.isTTY"` directly still works just fine:

```
$ node -p -e "process.stdout.isTTY"
true
```

any ideas?

**Comment by alan-agius4** [comment]
That is interesting, not sure how to debug this from my end since I don’t have a Windows machine.

In the past we did see a number of TTY issues with GitBash and typically they were never actionable form our end. In most cases these were address by Node.JS as far as I can tell.

**Comment by Jehoel** [comment]
@alan-agius4 I just realised that the error is because `stdout.write` does not accept a `bool` parameter - but it's also reporting `isTTY` is undefined, so I've got my errors crossed - but it's still broken. I'll update this comment in a short while.

**Comment by Jehoel** [comment]
* `cmd.exe`, when running `node.exe myscript.js`  has `process.stdout.isTTY === true`.
* `cmd.exe`, when running `ng add foobar` to indirectly run my hacked `ng.js` script has `process.stdout.isTTY === true`.
* `bash` , when running `node.exe myscript.js`  has `process.stdout.isTTY === true`.
* `bash`, when running `ng add foobar` to indirectly run my hacked `ng.js` script has `process.stdout.isTTY === undefined`.

So that's narrowing it down...

**Comment by alan-agius4** [comment]
Does the below return the correct TTY value?

```
node node_modules/@angular/cli/lib/init.js add foobar

**Comment by Jehoel** [comment]
@alan-agius4

Correct, running `node node_modules/@angular/cli/lib/init.js add foobar` directly from git-bash has `stdout.isTTY === true`.

Running `node node_modules/@angular/cli/lib/init.js add @angular-eslint/schematics@12.2.0` succeeds **and** it asks me for a confirmation prompt.

So the problem then is to replace `exec node` with just `node` in the `ng` bash script, perhaps?

**Comment by Jehoel** [comment]
I've raised a bug with NodeJS here: https://github.com/nodejs/node/issues/39673

**Comment by alan-agius4** [comment]
@Jehoel, the mentioned bash script is actually generated by NPM and not Angular. 
Hence we have no controller of its contents.

**Comment by diegoatnqn** [comment]
All **_ng add_** commands are not working for me either.
`Angular CLI: 12.0.5
Node: 16.5.0
Package Manager: npm 7.20.0
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/cdk                    12.1.3
@angular/material               12.1.3
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4`
