### ISSUE TITLE
Angular workspace: nested project tsconfig.app.json should be just tsconfig.json

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#21522]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
N/A

### Description
When generating angular workspace, each project has its own `tsconfig.app.json`. However, VS Code requires that configuration file be named `tsconfig.json` in nested folders for editor to provide project aware analysis.

## 🔬 Minimal Reproduction
- `npx @angular/cli@12 new web-apps --create-application false`
- `cd web-apps`
- `yarn ng generate application admin-dashboard --prefix ad --routing --style css`
- `yarn ng generate application support-helpdesk --prefix sh --routing --style css`
- Edit `projects/support-helpdesk/tsconfig.app.json` and add ` "strictPropertyInitialization": false` under `compilerOptions`
- Edit `projects/support-helpdesk/src/app/app.component.ts` and add variable at the top of file `public applicationName: string;` 

## 🔥 Exception or Error

- Typescript language service running in Visual Studio Code complains that variable `applicationName` is not initialized. <img width="647" alt="angular_strict_initialization" src="https://user-images.githubusercontent.com/13006107/128577163-9452c603-4cbf-4f9e-b4af-d2b6a909dbbf.png">

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.0
Node: 16.6.1
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**
- Rename `projects/support-helpdesk/tsconfig.app.json` to `projects/support-helpdesk/tsconfig.json` and the visual studio code stops complaining.

**Comment by alan-agius4** [comment]
Related to https://github.com/angular/angular-cli/issues/20476

**Comment by alan-agius4** [comment]
Let’s continue tracking this as part of  #20476
