### ISSUE TITLE
ng update is trying to install non-stable versions 

### ISSUE THREAD

**Issue by e-oz** [angular/angular-cli#21534]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 12.1.x (before 12.2)

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
1. get package.json with dependencies to 11.2.3, like this:
```
    "@angular/animations": "^11.2.3",
    "@angular/cdk": "^11.2.2",
    "@angular/common": "^11.2.3",
    "@angular/compiler": "^11.2.3",
    "@angular/core": "^11.2.3",
    "@angular/forms": "^11.2.3",
    "@angular/localize": "^11.2.3",
    "@angular/material": "^11.2.2",
...
```

2. try to run ng update @angular/core

## 🔥 Exception or Error

<pre><code>
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 77 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/compiler-cli" (requires "^12.0.0 || ^12.2.0-next", would install "13.0.0-next.0")
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/localize" (requires "^12.0.0 || ^12.2.0-next", would install "13.0.0-next.0")
...
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.2
Node: 16.4.0
OS: darwin arm64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cdk                    11.2.2
@angular/cli                    11.2.2
@angular/material               11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.6.3
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi @e-oz, 

I am unable to replicate the above.

```
ng update @angular/core
Using package manager: 'npm'
Collecting installed dependencies...
Found 29 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular/forms" has a missing peer dependency of "@angular/platform-browser" @ "12.2.0".
    Updating package.json with dependency @angular/compiler-cli @ "12.2.0" (was "12.0.1")...
    Updating package.json with dependency @angular/animations @ "12.2.0" (was "11.2.14")...
    Updating package.json with dependency @angular/common @ "12.2.0" (was "11.2.14")...
    Updating package.json with dependency @angular/compiler @ "12.2.0" (was "11.2.14")...
    Updating package.json with dependency @angular/core @ "12.2.0" (was "11.2.14")...
    Updating package.json with dependency @angular/forms @ "12.2.0" (was "11.2.14")...
    Updating package.json with dependency @angular/localize @ "12.2.0" (was "11.2.14")...
  UPDATE package.json (1205 bytes)
```

Can you please sharing the complete package.json?

**Comment by e-oz** [comment]
```
"dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "^11.2.3",
    "@angular/cdk": "^11.2.2",
    "@angular/common": "^11.2.3",
    "@angular/compiler": "^11.2.3",
    "@angular/core": "^11.2.3",
    "@angular/forms": "^11.2.3",
    "@angular/localize": "^11.2.3",
    "@angular/material": "^11.2.2",
    "@angular/platform-browser": "^11.2.3",
    "@angular/platform-browser-dynamic": "^11.2.3",
    "@angular/platform-server": "^11.2.3",
    "@angular/router": "^11.2.3",
    "@angularclass/hmr": "^2.1.3",
    "@asymmetrik/ngx-leaflet": "^6.0.1",
    "@asymmetrik/ngx-leaflet-markercluster": "^3.0.0",
    "@mapbox/mapbox-gl-traffic": "^1.0.2",
    "@ngui/map": "^0.30.3",
    "@sentry/angular": "^5.29.2",
    "@types/googlemaps": "^3.30.8",
    "@types/leaflet.markercluster": "^1.4.0",
    "@types/mapbox-gl": "^1.12.5",
    "@types/uuid": "^8.3.0",
    "bootstrap": "^4.3.1",
    "centrifuge": "^2.6.4",
    "chart.js": "^2.7.2",
    "core-js": "^3.6.5",
    "dayjs": "^1.10.4",
    "eslint": "^6.8.0",
    "font-awesome": "^4.7.0",
    "humanize-duration": "^3.23.1",
    "immutable": "^4.0.0-rc.12",
    "leaflet": "^1.4.0",
    "leaflet.markercluster": "^1.4.1",
    "less": "3.11.1",
    "lodash": "^4.17.15",
    "lottie-web": "^5.6.5",
    "mapbox-gl": "^1.12.0",
    "ng-in-viewport": "^6.0.3",
    "ng-lint-staged": "^0.1.6",
    "ngx-google-analytics": "^11.2.0",
    "ngx-lottie": "^5.3.2",
    "ngx-toastr": "^12.0.0",
    "parse-duration": "^0.4.4",
    "rxjs": "^6.3.3",
    "swiper": "^6.7.1",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.2",
    "@angular/cli": "^11.2.2",
    "@angular/compiler-cli": "^11.2.3",
    "@angular/language-service": "^11.2.3",
    "@types/jasmine": "~3.6.4",
    "@types/jasminewd2": "~2.0.8",
    "@types/leaflet": "^1.5.23",
    "@types/node": "^14.14.31",
    "codelyzer": "^6.0.0",
    "husky": "4.2.5",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.1.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~4.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "karma-phantomjs-launcher": "^1.0.4",
    "lint-staged": "^10.1.7",
    "prettier": "2.0.5",
    "protractor": "~7.0.0",
    "rxjs-tslint": "0.1.8",
    "ts-node": "~8.9.0",
    "tslint": "~6.1.0",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "4.1.5",
    "webpack-bundle-analyzer": "^4.4.0"
  },
```

**Comment by alan-agius4** [comment]
I am seeing a different expected error.

```
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires "~4.0.0 || ~4.1.0", would install "4.3.5").
                  Package "@agm/core" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0 || ^7.0.0 || ^8.0.0" (extended), would install "12.2.0").
                  Package "@agm/core" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0 || ^7.0.0 || ^8.0.0" (extended), would install "12.2.0").
                  Package "@sentry/angular" has an incompatible peer dependency to "@angular/router" (requires "^10.0.3" (extended), would install "12.2.0").
```

Since the Angular CLI is also outdated, you'd need to run the below command
```
ng update @angular/cli @angular/core
```

For more information about the update process please see: https://update.angular.io/

**Comment by e-oz** [comment]
so "Installing a temporary version to perform the update." is not quite true :)
Thank you very much for your help and your time!

**Comment by alan-agius4** [comment]
It does download and latest CLI to perform/run the update. But this doesn't effect the CLI version in your workspace. 

Hence, if you are updating the Angular framework in your workspace to a different major version you'd also need to update the Angular CLI to match the framework version as otherwise you'll have mismatching versions.
