### ISSUE TITLE
switch for ng serve to clear console everytime it rebuilds

### ISSUE THREAD

**Issue by vmachacek** [angular/angular-cli#21559]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When I'm refactoring large code-base i revised folowing process:

-  i have ng serve running 
- i do some changes in bulk without save
- save all 
- i stop the process
- clear the console
- then start the ng serve again

I'm doing this to see in isolation what I break, fixed what are new issues etc. So I can focus only on what is relevant

### Describe the solution you'd like

it would be nice to have a switch to run ng serve which would clear console everytime it detects change

### Describe alternatives you've considered

Currently I'm doing it manually  - stopping the process, clearing console and starting ng serve again

**Comment by alan-agius4** [comment]
Thanks for this request. None-the-less, this is currently not in the roadmap. Let's re-consider this in the future if think change.
