### ISSUE TITLE
question: anyone knows if possible to use hot module reload with ng2 cli?

### ISSUE THREAD

**Issue by born2net** [angular/angular-cli#2156]
question: anyone knows if its possible to use hot module reload with this ng2 cli?

such as:
https://github.com/AngularClass/angular2-hmr-loader

regards

Sean

**Comment by splintercode** [comment]
Currently no there is not. One of the goals that is in early stages is to allow a way to access/extend the webpack config to allow additional features/loaders.

**Comment by born2net** [comment]
ok tx!
Regards,

Sean
Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/ng2Boilerplate

**Comment by filipesilva** [comment]
Issue tracked in https://github.com/angular/angular-cli/issues/893
