### ISSUE TITLE
Updating @angular-devkit/build-angular to 12.2.1 causes `styles.css` Error

### ISSUE THREAD

**Issue by pfeileon** [angular/angular-cli#21567]
## Description
Updated my app from Angular 11.1.1 to the newest stable version (= 12.2.1): `ng update @angular/cli`.

(
I found it weird that this alone also updated @angular/core. Updating @angular/core explicitly with `ng update @angular/cli@12 @angular/core@12` caused the CLI to install @angular/forms and other packages with version 13.0.0-next.1. [An issue which was reported but closed.](https://github.com/angular/angular-cli/issues/21534)
)

## Error
This caused the following error when I tried to start the application: `styles.css - Error: (0 , _identifier.getUndoPath) is not a function`.

## Additional Info
Found a [stackoverflow thread](https://stackoverflow.com/questions/68718162/error-upgrading-from-angular-11-2-to-12-2-styles-css-error-0-identifier) where the accepted answer is to downgrade @angular-devkit/build-angular.
=> Downgrading @angular-devkit/build-angular to 12.1.4 indeed fixes the issue.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by pfeileon** [comment]
After unsuccessfully trying to reproduce this issue on a clean project, I came to the conclusion that the issue is most likely due to a faulty package-lock.json. If anybody else has this issue, try deleting your node modules and your package-lock.json and reinstall.
