### ISSUE TITLE
@angular-devkit/build-angular 12.2.1 unit test failures - TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by rickvandermey** [angular/angular-cli#21588]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, this was introduced after upgrading from 12.1.4 to 12.2.1

### Description

After updating unit test will fail:

```
Failed: Cannot read property 'match' of undefined
        TypeError: Cannot read property 'match' of undefined
            at extractCommentsWithHash (node_modules/@angular/compiler/fesm2015/compiler.js:9555:1)
            at ShadowCss.shimCssText (node_modules/@angular/compiler/fesm2015/compiler.js:9118:1)
            at node_modules/@angular/compiler/fesm2015/compiler.js:22336:1
            at Array.map (<anonymous>)
            at compileStyles (node_modules/@angular/compiler/fesm2015/compiler.js:22335:1)
            at compileComponentFromMetadata (node_modules/@angular/compiler/fesm2015/compiler.js:21882:1)
            at CompilerFacadeImpl.compileComponentFromMeta (node_modules/@angular/compiler/fesm2015/compiler.js:22492:1)
            at CompilerFacadeImpl.compileComponent (node_modules/@angular/compiler/fesm2015/compiler.js:22482:1)
            at Function.get (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:27388:1)
            at getComponentDef (node_modules/@angular/core/__ivy_ngcc__/fesm2015/core.js:1108:1)
```

## 🌍 Your Environment

```
Angular CLI: 12.2.1
Node: 14.16.1
Package Manager: npm 7.12.0
OS: darwin x64

Angular: 12.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1202.1
@angular-devkit/build-angular              12.2.1
@angular-devkit/core                       12.2.1
@angular-devkit/schematics                 12.1.4
@nguniversal/express-engine                12.1.0
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        12.1.4
rxjs                                       6.6.7
typescript                                 4.3.5
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by rickvandermey** [comment]
That would be a bit of a problem, because its a private repo, and in my starterkit i updated to Jest.
In Jest there are no problems. but with Karma/Jasmine I get those errors

**Comment by alan-agius4** [comment]
Unfortunately without a reproduction it's hard to to tell what is happening, you don't need to share the private repository. You can create a minimal reproduction as described in the above comment using `ng new`.

**Comment by jpalmowski** [comment]
Facing the same issue after upgrading from 12.1.3 -> 12.2.2

I can't reproduce it in a clean new ng app though.  

For me it's related to the SCSS styles, they're undefined on the component metatdata and ultimately this leads to extractCommentsWithHash to be invoked with an undefined input.  

Will report back if I get any further

**Comment by jpalmowski** [comment]
So for some reason I had the following in my tsconfig.spec.json

`"module": "CommonJS",`

Removing that has solved this issue for me

**Comment by jpalmowski** [comment]
Here's a repro just for completeness: https://github.com/jpalmowski/public-repro

**Comment by alan-agius4** [comment]
While in this case you shouldn't be using `CommonJS` as module, this seems to be a regression.

**Comment by aidyclarke** [comment]
Hey - can anyone let me know what changed? We've used `CommonJS` as a module as part of our **tsconfig.spec.json**' in order to allow Jasmine to spyOn exported functions until now, and this hasn't been a problem.

Since this feels like something has changed, I'm curious if there is another solution - a fix for one thing is breaking something else.

**Comment by bobbyg603** [comment]
I would like to echo @aidyclarke, we need to be able to spy on exported functions in order to upgrade. Is there a way to do this without commonjs?
