### ISSUE TITLE
Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.0, but postcss-preset-env uses 7.0.36.

### ISSUE THREAD

**Issue by ShahViral6438** [angular/angular-cli#21583]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

While running ng test command, we are getting this error.
## 🔥 Exception or Error
<pre><code>

Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.0, but postcss-preset-env uses 7.0.36.
Below is package.json:

"dependencies": {
    "@angular/animations": "12.0.0",
    "@angular/cdk": "^12.0.0",
    "@angular/common": "~12.0.0",
    "@angular/compiler": "~12.0.0",
    "@angular/core": "^12.0.0",
    "@angular/forms": "~12.0.0",
    "@angular/localize": "~12.0.0",
    "@angular/material": "^12.0.0",
    "@angular/platform-browser": "~12.0.0",
    "@angular/platform-browser-dynamic": "~12.0.0",
    "@angular/router": "~12.0.0",
    "@azure/msal-angular": "^2.0.0",
    "@azure/msal-browser": "^2.14.1",
    "@microsoft/applicationinsights-web": "^2.6.2",
    "@microsoft/office-js": "^1.1.53",
    "@microsoft/office-js-helpers": "^1.0.2",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@progress/kendo-angular-buttons": "^6.2.0",
    "@progress/kendo-angular-common": "^2.0.1",
    "@progress/kendo-angular-dateinputs": "^5.2.0",
    "@progress/kendo-angular-dialog": "^5.0.1",
    "@progress/kendo-angular-dropdowns": "^5.3.0",
    "@progress/kendo-angular-editor": "^2.2.0",
    "@progress/kendo-angular-excel-export": "^4.0.1",
    "@progress/kendo-angular-grid": "^5.1.2",
    "@progress/kendo-angular-icons": "^0.4.3",
    "@progress/kendo-angular-indicators": "^1.1.0",
    "@progress/kendo-angular-inputs": "^7.3.0",
    "@progress/kendo-angular-intl": "^3.1.1",
    "@progress/kendo-angular-l10n": "^3.0.1",
    "@progress/kendo-angular-label": "^3.0.3",
    "@progress/kendo-angular-layout": "^6.1.5",
    "@progress/kendo-angular-listview": "^2.0.1",
    "@progress/kendo-angular-menu": "^3.0.2",
    "@progress/kendo-angular-notification": "^3.0.1",
    "@progress/kendo-angular-pager": "^2.0.1",
    "@progress/kendo-angular-pdf-export": "^3.0.1",
    "@progress/kendo-angular-popup": "^4.0.1",
    "@progress/kendo-angular-progressbar": "^2.0.1",
    "@progress/kendo-angular-toolbar": "^4.1.1",
    "@progress/kendo-angular-tooltip": "^3.0.2",
    "@progress/kendo-angular-treeview": "^5.3.1",
    "@progress/kendo-data-query": "^1.5.5",
    "@progress/kendo-drawing": "^1.10.1",
    "@progress/kendo-licensing": "^1.2.0",
    "@progress/kendo-svg-icons": "^0.1.2",
    "@progress/kendo-theme-default": "^4.38.1",
    "@types/office-js": "^1.0.181",
    "angular-material": "^1.2.2",
    "autoprefixer": "^9.8.6",
    "classlist.js": "^1.1.20150312",
    "guid-typescript": "^1.0.9",
    "office-ui-fabric-js": "^1.3.0",
    "officejs-mock": "^1.0.5",
    "postcss": "^8.3.6",
    "rxjs": "~6.6.0",
    "stream": "0.0.2",
    "tailwindcss": "^2.2.7",
    "timers": "^0.1.1",
    "tslib": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.11.4"
  },

  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.1",
    "@angular-eslint/builder": "12.0.0",
    "@angular-eslint/eslint-plugin": "12.0.0",
    "@angular-eslint/eslint-plugin-template": "12.0.0",
    "@angular-eslint/schematics": "12.0.0",
    "@angular-eslint/template-parser": "12.0.0",
    "@angular/cli": "~12.2.1",
    "@angular/compiler-cli": "~12.0.0",
    "@types/jasmine": "3.7.1",
    "@types/node": "^12.11.1",
    "@types/xml2js": "^0.4.8",
    "@typescript-eslint/eslint-plugin": "4.23.0",
    "@typescript-eslint/parser": "4.23.0",
    "eslint": "^7.26.0",
    "jasmine-core": "3.7.1",
    "jasmine-spec-reporter": "7.0.0",
    "karma": "~6.3.2",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.6.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "typescript": "~4.2.4"
  }
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 12.2.1
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.2.1
... cdk, cli, core, material

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1202.1
@angular-devkit/build-angular       12.2.1
@angular-devkit/core                12.2.1
@angular-devkit/schematics          12.2.1
@angular/animations                 12.0.0
@angular/common                     12.0.5
@angular/compiler                   12.0.5
@angular/compiler-cli               12.0.5
@angular/forms                      12.0.5
@angular/localize                   12.0.5
@angular/platform-browser           12.0.5
@angular/platform-browser-dynamic   12.0.5
@angular/router                     12.0.5
@schematics/angular                 12.2.1
rxjs                                6.6.7
typescript                          4.2.4
Production
</code></pre>

**Comment by alan-agius4** [comment]
Can you try like to delete the lock file and node_modules?

```
rm -rf node_modules package-lock.json
npm i
```

**Comment by vbraun** [comment]
For the record, the error persists after reinstalling node_modules for me. Downgrading to `@progress/kendo-theme-default@4.40.1` fixes it for me.

**Comment by ShahViral6438** [comment]
I tried both above options and none of them are working.

I cleared entire TFS mapped workspace, took the latest code, updated kendo-theme-default to 4.40.1, cleared node_modules and package-lock.json, rerun below commands but still getting same error:

npm install
ng build

Below are npm and node versions installed in my machine:
**node -v => V14.17.5
npm -v => 6.14.14**

**Comment by alan-agius4** [comment]
Can you please provide the output of `npm ls postcss`?

**Comment by ShahViral6438** [comment]
Here it is:

+-- @angular-devkit/build-angular@12.0.5
| +-- css-loader@5.2.4
| | `-- UNMET PEER DEPENDENCY postcss@8.3.6 
| +-- css-minimizer-webpack-plugin@3.0.0
| | `-- UNMET PEER DEPENDENCY postcss@8.3.6 
| +-- UNMET PEER DEPENDENCY postcss@8.3.0 
| +-- postcss-preset-env@6.7.0
| | +-- css-blank-pseudo@0.1.4
| | | `-- postcss@7.0.36  deduped
| | +-- css-has-pseudo@0.10.0
| | | `-- postcss@7.0.36  deduped
| | +-- css-prefers-color-scheme@3.1.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss@7.0.36  deduped
| | +-- postcss-attribute-case-insensitive@4.0.2
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-color-functional-notation@2.0.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-color-gray@5.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-color-hex-alpha@5.0.3
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-color-mod-function@3.0.3
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-color-rebeccapurple@4.0.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-custom-media@7.0.8
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-custom-properties@8.0.11
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-custom-selectors@5.1.2
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-dir-pseudo-class@5.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-double-position-gradients@1.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-env-function@2.0.2
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-focus-visible@4.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-focus-within@3.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-font-variant@4.0.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-gap-properties@2.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-image-set-function@3.0.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-initial@3.0.4
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-lab-function@2.0.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-logical@3.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-media-minmax@4.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-nesting@7.0.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-overflow-shorthand@2.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-page-break@2.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-place@4.0.1
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-pseudo-class-any-link@6.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-replace-overflow-wrap@3.0.0
| | | `-- postcss@7.0.36  deduped
| | +-- postcss-selector-matches@4.0.0
| | | `-- postcss@7.0.36  deduped
| | `-- postcss-selector-not@4.0.1
| |   `-- postcss@7.0.36  deduped
| `-- resolve-url-loader@4.0.0
|   `-- postcss@7.0.36  deduped
`-- autoprefixer@9.8.6
  `-- postcss@7.0.36

npm ERR! peer dep missing: postcss@^8.0.0, required by postcss-import@14.0.1
npm ERR! peer dep missing: postcss@^8.1.0, required by icss-utils@5.1.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-extract-imports@3.0.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-local-by-default@4.0.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-scope@3.0.0
npm ERR! peer dep missing: postcss@^8.1.0, required by postcss-modules-values@4.0.0
npm ERR! peer dep missing: postcss@^8.2.15, required by cssnano@5.0.7

**Comment by alan-agius4** [comment]
From the above, it seems that NPM 6 is dedupping postcss incorrectly as I am unable to find `postcss@8.3.0` in the package tree, which is incorrect since it's a direct dependency of `@angular-devkit/build-angular`.

My recommendation would be to use an alternate package manager such as Yarn or NPM 7.

**Comment by ShahViral6438** [comment]
I found out the issues. There were two errors:

1. Small error in one of the scss file (comma was missing). 
2. Installed postcss and postcss-loader packages as devDependencies.

After that, ng build and ng test started working fine.

**Comment by alan-agius4** [comment]
> Installed postcss and postcss-loader packages as devDependencies.

You shouldn't be needing this. By doing so, it's likely that you will encounter issues in the future.

Closing, since this is not actionable from our end and while the above works, ideally an alternate package manager is used.
