### ISSUE TITLE
ng serve with hmr hot update causes infinite fetch request calls to runtime.*.json

### ISSUE THREAD

**Issue by wendellestradairely** [angular/angular-cli#21580]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I don't know how to reproduce it but it happens when I make changes to my files and the hot update will trigger to apply the changes. But sometimes, it calls to the runtime.*.json infinitely and fills up my memory/CPU.

![image](https://user-images.githubusercontent.com/50942719/129508635-0c8ff4ba-8e77-4bfc-8450-4210af659b2a.png)

![image](https://user-images.githubusercontent.com/50942719/129511051-b029d53e-c267-4774-984e-7ad335fac215.png)

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.0
NodeJS: 12.11.1
Typescript: 4.2.4
```

### Anything else?
{
  "name": "i21restapi",
  "version": "0.0.0",
  "resolutions": {
    "webpack": "^5.0.0"
  },
  "scripts": {
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points",
    "ng": "ng",
    "start": "ng serve --port 4500 --hmr",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@cds/angular": "^5.5.1",
    "@cds/city": "^1.1.0",
    "@cds/core": "^5.5.1",
    "@clr/angular": "^5.4.1",
    "@clr/icons": "^5.4.1",
    "@clr/ui": "^5.4.1",
    "@microsoft/signalr": "^5.0.9",
    "@webcomponents/webcomponentsjs": "^2.5.0",
    "chart.js": "^2.9.4",
    "date-fns": "^2.21.1",
    "date-fns-tz": "^1.1.6",
    "indefinite": "^2.4.1",
    "lodash-es": "^4.17.15",
    "ng2-charts": "^2.4.2",
    "ng2-tooltip-directive": "^2.10.3",
    "ngx-bar-rating": "^2.0.0",
    "ngx-highlightjs": "^4.1.3",
    "prismjs": "^1.23.0",
    "rxjs": "~6.6.7",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.0",
    "@angular/cli": "~12.2.0",
    "@angular/compiler-cli": "~12.2.0",
    "@angular/language-service": "~12.2.0",
    "@types/node": "^12.11.1",
    "@types/lodash-es": "^4.17.3",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.4",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "~4.2.4"
  }
}

_No response_

**Comment by alan-agius4** [comment]
@wendellestradairely, unfortunately without a reproduction it’s hard to tell what is the root cause.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
