### ISSUE TITLE
installation d'angular

### ISSUE THREAD

**Issue by Florencemoya** [angular/angular-cli#21601]
npm WARN using --force Recommended protections disabled.

C:\Users\HP>npm cache clean --force
npm WARN using --force Recommended protections disabled.

C:\Users\HP>  npm install -g @angular/cli
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues

**Comment by alan-agius4** [comment]
These are just warnings which are coming from downstream dependencies and therefore there isn’t anything actionable here from our end.
