### ISSUE TITLE
scss files in the assets folder are treated as css when optimizer is enabled

### ISSUE THREAD

**Issue by kemsky** [angular/angular-cli#21617]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build
- [x] serve

### Is this a regression?

Yes, version 11 does not have this problem.

### Description

Previously it was ok to have scss files in the assets folder, but since version 12 it leads to errors during optimization because cli treats sccs files as css for some reason.

## 🔬 Minimal Reproduction

Just put any non-empty (e.g. define var) scss file into assets folder and do production build or serve with optimization enabled. 

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.0
Node: 14.17.0
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.0
@angular-devkit/build-angular   12.2.0
@angular-devkit/core            12.2.0
@angular-devkit/schematics      12.2.0
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
What’s the reason of having scss files that are copied uncompiled to the dist folder in the first place?

Note: this has be fixed in version 13 which is currently in prerelease via https://github.com/angular/angular-cli/pull/21535

**Comment by kemsky** [comment]
@alan-agius4, it was probably a mistake, but we spend a lot of time trying to figure out what exactly is wrong.

**Comment by alan-agius4** [comment]
Seeing that this will address in version 13, I am going to close this issue.

Unfortunately, there is no easy way to back port the fix to version 12.
