### ISSUE TITLE
cli compiler output to console is leaking some shady characters

### ISSUE THREAD

**Issue by webmandman** [angular/angular-cli#21611]
# 🐞 Bug report

- [ ] new
- [X ] build
- [X ] serve
- [ ] test
...

### Description

Not much to explain here, check out the screenshot for the best description you can get. 

## 🔬 Minimal Reproduction

Don't know how.

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.1.1
Node: 16.6.1 (Unsupported)
Package Manager: npm 7.20.3
OS: win32 x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.1.1
ng-packagr                      12.1.2
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

![image](https://user-images.githubusercontent.com/991677/130140761-c56213f6-9729-4c1e-9cf6-01f0dfa0670c.png)

**Comment by webmandman** [comment]
I'm not  sure when this started happening. just noticed it today.

**Comment by alan-agius4** [comment]
@webmandman without a reproduction it will be hard to get to the bottom of this. 

What is the output when stdout is redirected to a file where colors are not supporter?

```
ng build > log.txt
```

**Comment by webmandman** [comment]
[37m[39m
[37m[0m[1mInitial Chunk Files[22m              [2m | [22m[1mNames[22m        [2m | [22m     [1mSize[22m[0m[39m
[37m[0m[92mmain.4f450971069e8eee718f.js[39m[37m     [2m | [22mmain         [2m | [22m[96m852.69 kB[39m[37m[0m[39m
[37m[0m[92mstyles.db00f66c52ad028dbac8.css[39m[37m  [2m | [22mstyles       [2m | [22m[96m580.38 kB[39m[37m[0m[39m
[37m[0m[92mpolyfills.fe8ebe19d7929be49c0e.js[39m[37m[2m | [22mpolyfills    [2m | [22m [96m45.11 kB[39m[37m[0m[39m
[37m[0m[92mruntime.1aff551df05176b47fc2.js[39m[37m  [2m | [22mruntime      [2m | [22m  [96m2.86 kB[39m[37m[0m[39m
[37m[0m[0m[39m
[37m[0m[1m [22m                                [2m | [22m[1mInitial Total[22m[2m | [22m  [1m1.45 MB[22m[0m[39m
[37m[0m[0m[39m
[37m[0m[1mLazy Chunk Files[22m                 [2m | [22m[1mNames[22m        [2m | [22m     [1mSize[22m[0m[39m
[37m[0m[92m434.feffaf2160477170fee3.js[39m[37m      [2m | [22m-            [2m | [22m[96m604.08 kB[39m[37m[0m[39m
[37m[0m[92m370.c90e7893940b51d8ed30.js[39m[37m      [2m | [22m-            [2m | [22m[96m512.75 kB[39m[37m[0m[39m
[37m[0m[92m653.ae81570389d29565b9cd.js[39m[37m      [2m | [22m-            [2m | [22m[96m113.78 kB[39m[37m[0m[39m
[37m[0m[92m601.f683e4a9b535fc3f5bba.js[39m[37m      [2m | [22m-            [2m | [22m[96m112.59 kB[39m[37m[0m[39m
[37m[0m[92m905.bdc962704af2d4ba299a.js[39m[37m      [2m | [22m-            [2m | [22m [96m77.74 kB[39m[37m[0m[39m
[37m[0m[92m115.2e963c062eaacc1af0d1.js[39m[37m      [2m | [22m-            [2m | [22m [96m16.54 kB[39m[37m[0m[39m
[37m[0m[92m4.71d518719e4f2389cd91.js[39m[37m        [2m | [22m-            [2m | [22m [96m10.10 kB[39m[37m[0m[39m
[37m[0m[92mcommon.37e91decca098d3a4bc0.js[39m[37m   [2m | [22mcommon       [2m | [22m  [96m9.55 kB[39m[37m[0m[39m
[37m[0m[92m224.1cbb0757c739564fd98f.js[39m[37m      [2m | [22m-            [2m | [22m  [96m2.94 kB[39m[37m[0m[39m
[37m[0m[0m[39m
[37m[0mBuild at: [1m[37m2021-08-20T09:31:55.903Z[39m[37m[22m - Hash: [1m[37m11399ebe269932e19bc5[39m[37m[22m - Time: [1m[37m88441[39m[37m[22mms[0m[39m

**Comment by webmandman** [comment]
now that I'm seeing this output, looks like the 39m0m is a line ending character that is wrapping  into the next line.

**Comment by webmandman** [comment]
Sorry I won't be able to reproduce this repo. I tried to reproduce it in a new angular app, but all seems fine.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
