### ISSUE TITLE
ng build not working with pnpm

### ISSUE THREAD

**Issue by hungtcs** [angular/angular-cli#21622]
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

Without any file changes, the file sizes generated by the first build and the second build are inconsistent.

And the file generated by the first build does not work, error message is:

![image](https://user-images.githubusercontent.com/11692935/130317698-edfdcd3c-f63e-400d-917b-a8a96bc27d00.png)

The second and subsequent builds are working well.

## 🔬 Minimal Reproduction

The steps:
1. npm install -g pnpm
2. ng new --package-manager pnpm --skip-git --skip-install --skip-tests --strict --style scss pnpm-test
2. cd pnpm-test
3. pnpm install
4. pnpm run build (first build)
5. pnpm run build (build again)

the first build output:
![image](https://user-images.githubusercontent.com/11692935/130317804-308f64fa-11da-40c5-92c0-3f3ce9ed7204.png)

the second build output:
![image](https://user-images.githubusercontent.com/11692935/130317850-e007e7ec-e2f9-4ced-aa72-d6508507e5f5.png)

## 🔥 Exception or Error

<pre><code>ERROR TypeError: Cannot read property '11' of null
    at Xl (main.411f6f6ec351866530d7.js:1)
    at template (main.411f6f6ec351866530d7.js:1)
    at ir (main.411f6f6ec351866530d7.js:1)
    at nr (main.411f6f6ec351866530d7.js:1)
    at ur (main.411f6f6ec351866530d7.js:1)
    at main.411f6f6ec351866530d7.js:1
    at nr (main.411f6f6ec351866530d7.js:1)
    at Vs.create (main.411f6f6ec351866530d7.js:1)
    at t.bootstrap (main.411f6f6ec351866530d7.js:1)
    at main.411f6f6ec351866530d7.js:1
</code></pre>

## 🌍 Your Environment

<pre><code>Angular CLI: 12.0.5
Node: 14.16.1
Package Manager: pnpm 6.13.0
OS: darwin arm64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5 (cli-only)
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5 (cli-only)
@angular-devkit/schematics      12.0.5 (cli-only)
@schematics/angular             12.0.5 (cli-only)
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
`pnpm` is unfortunately incompatible with `ngcc` (the Ivy compatibility compiler).
The good news is that the new partial compilation support present in Angular v12 allows for a path away from the use of `ngcc`.  In addition, in Angular v13, the framework libraries will be transitioned to partial compilation which will allow a build experience that does not require `ngcc`.  This, however, is assuming that any third-party Angular libraries used in the project are also published with partial compilation support.  But the currently shipped library build system within the Angular CLI fully supports generating such libraries.
Yarn PnP is also incompatible and once it is considered compatible, `pnpm` should be so as well. Yarn PnP status can be tracked in the following issue:  https://github.com/angular/angular-cli/issues/16980
