### ISSUE TITLE
Component selector is unable to select element by id.

### ISSUE THREAD

**Issue by chozzz** [angular/angular-cli#2162]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
**Ubuntu 14.04**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
**angular-cli: local (v1.0.0-beta.14, branch: master)
node: 6.4.0
os: linux x64**

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Simply do this in your component
```
@Component({
    selector: '#top-navigation',
    templateUrl: './top-navigation.component.html',
    styleUrls: ['./top-navigation.component.scss']
})
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.
**No error log**

5. Mention any other details that might be useful.

**It should work as a native css selector. It goes fine if I do this.**
```
@Component({
    selector: '[id=top-navigation]',
    templateUrl: './top-navigation.component.html',
    styleUrls: ['./top-navigation.component.scss']
})
```

**Comment by filipesilva** [comment]
https://github.com/angular/angular seem like a better place for this issue, it doesn't seem CLI related.
