### ISSUE TITLE
App not working in production mode using ng build --prod

### ISSUE THREAD

**Issue by theunreal** [angular/angular-cli#2163]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Build on: Windows 10
Running on: Linux shared hosting

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

ng --version
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: win32 x64

3 + 4. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc. 

I created an Angular 2 project using Angular 2 CLI and used ng build --prod command and got no errors.

When I upload the dist folder into my website, I get the following error when the app loads:

http://i.stack.imgur.com/qEEEU.png

```
Uncaught TypeError: this._input.charCodeAt is not a function_Tokenizer._advance @ main .688167 c….bundle.js: 1716 _Tokenizer @ main .688167 c….bundle.js: 1716 tokenize @ main .688167 c….bundle.js: 1709 Parser.parse @ main .688167 c….bundle.js: 219 HtmlParser.parse @ main .688167 c….bundle.js: 380 DirectiveNormalizer.normalizeLoadedTemplate @ main .688167 c….bundle.js: 598 DirectiveNormalizer.normalizeTemplateSync @ main .688167 c….bundle.js: 598 DirectiveNormalizer.normalizeDirective @ main .688167 c….bundle.js: 598 RuntimeCompiler._createCompiledTemplate @ main .688167 c….bundle.js: 1090(anonymous
function) @ main .688167 c….bundle.js: 1090(anonymous
function) @ main .688167 c….bundle.js: 1090 RuntimeCompiler._compileComponents @ main .688167 c….bundle.js: 1090 RuntimeCompiler._compileModuleAndComponents @ main .688167 c….bundle.js: 1090 RuntimeCompiler.compileModuleAsync @ main .688167 c….bundle.js: 1090 PlatformRef_._bootstrapModuleWithZone @ main .688167 c….bundle.js: 717 PlatformRef_.bootstrapModule @ main .688167 c….bundle.js: 717(anonymous
function) @ main .688167 c….bundle.js: 1509 __webpack_require__ @ inline.js: 1(anonymous
function) @ main .688167 c….bundle.js: 2131 __webpack_require__ @ inline.js: 1 window.webpackJsonp @ inline.js: 1(anonymous
function) @ main .688167 c….bundle.js: 1
```
I'm using the latest Angular 2 CLI with webpack and Angular 2 RC.7

What could have gone wrong?

The this._input.charCodeAt is only used in the angular compiler folder as below: enter image description here

http://i.stack.imgur.com/XSoZH.png

**Comment by vapits** [comment]
Same issue here but with this versions:
```
angular-cli: 1.0.0-beta.11-webpack.8
node: 5.11.0
os: darwin x64
```

**Comment by jamesd-udley** [comment]
I'm also having build production failing.

global version:
````
angular-cli: 1.0.0-beta.14
node: 6.4.0
os: win32 x64
````
Create new project and run dev version
````
ng new testproj
ng serve
````
result:
![aa](https://cloud.githubusercontent.com/assets/12804982/18589935/77005a46-7bf2-11e6-839d-abfcb30bed30.png)

````
ng build --prod
````
result:
![bb](https://cloud.githubusercontent.com/assets/12804982/18589996/c511d3a4-7bf2-11e6-9fe4-81763bd425d8.png)

**Comment by filipesilva** [comment]
Does `ng server --prod` work? If so, this seems related with your deployment.

**Comment by theunreal** [comment]
It caused because my browser cached the inline.js. Adding some params to the inline.js fixed it.

**Comment by kylecordes** [comment]
I wonder if the contents of inline.js were/are intended to be, well, inlined into the HTML in a script tag. That would have prevented the problem here, and reduced all prod build deployments by one round-trip. From a quick look at the contents, it does seem suitable to inline.

**Comment by surjitsippy** [comment]
hi
i created and build a simple Angular 4 app and got a /dist folder without errors. As mentioned in documentation, I copied and pasted the contents of /dist folder to online Hosting server (in a new sub folder eg: abc.com/my_app) where another website is already running well. But the url to abc.com/my_app shows only "Loading...". i.e. the default text before starting loading the app. Nothing happens after that. Please help. Thank you.

**Comment by Maulik009** [comment]
@surjitsippy Can you check which errors are there in console ?
