### ISSUE TITLE
environment(.ts) vars not being overwritten (1.0.0-beta.11-webpack.8)

### ISSUE THREAD

**Issue by mcelliott** [angular/angular-cli#2164]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
 Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.11-webpack.8
node: 6.5.0
os: darwin x64
```
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
**After RC5 upgrade (and webpack) running `ng serve --environment=prod` [(or others)](https://github.com/angular/angular-cli#build-targets-and-environment-files)** 

4. The log given by the failure. Normally this include a stack trace and some
   more information.
**no errors or stack trace**

5. Mention any other details that might be useful.

package.json
```
"devDependencies": {
  ...
  "angular-cli": "1.0.0-beta.11-webpack.8"
  ...
}
```

angular-cli.json
```
"environments": {
  "source": "app/environments/environment.ts",
  "dev": "app/environments/environment.ts",
  "edge": "app/environments/environment.edge.ts",
  "staging": "app/environments/environment.staging.ts",
  "prod": "app/environments/environment.prod.ts"
}
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nicohabets** [comment]
Same here after upgrading to beta.14

**Comment by ciesielskico** [comment]
+1 angular-cli beta.14, angular 2.0 final

**Comment by ciesielskico** [comment]
Found the issue:

the environment folder moved to `/src/`, where as before it was under `/src/app`.
Moving the environments folder up by one fixes the issue.

**Comment by mcelliott** [comment]
Not working for me. We had already moved this folder: 

<img width="325" alt="screen shot 2016-09-26 at 16 54 31" src="https://cloud.githubusercontent.com/assets/1526700/18825086/edef05ca-8409-11e6-919b-2b25ad7a69d8.png">
