### ISSUE TITLE
Angular 12: Web Worker dependent files are too large, Unit Test cannot run

### ISSUE THREAD

**Issue by a1992012015** [angular/angular-cli#21650]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.2.2

### Description

Run ng test --code-coverage like allways
<pre><code>
/Users/xxxxx/.nvm/versions/node/v14.16.0/bin/node /Users/liujie/test-project/angular-demo-app/node_modules/@angular/cli/bin/ng test angular-test-app --karma-config /Applications/WebStorm.app/Contents/plugins/js-karma/js_reporter/karma-intellij/lib/intellij.conf.js --source-map --code-coverage
- Generating browser application bundles (phase: setup)...
26 08 2021 13:48:43.783:INFO [karma-server]: Karma v6.3.4 server started at http://localhost:9876/
26 08 2021 13:48:43.785:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
26 08 2021 13:48:43.789:INFO [launcher]: Starting browser Chrome
✔ Browser application bundle generation complete.
26 08 2021 13:48:51.699:INFO [Chrome 92.0.4515.159 (Mac OS 10.15.7)]: Connected on socket GuIG5xP1anTBGKRpAAAB with id 65731437

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
</code></pre>

## 🔬 Minimal Reproduction

After continuous inspection and testing, I discovered that it was because the processing method of my Web Worker relied on another file, and this file was referenced in the place where the Worker was created for processing that does not support Web Worker. When the content of the file is too large Will cause this problem when he is small enough, it will not appear

You can view the [map-svg-cut.component.ts](https://github.com/a1992012015/angular-demo-app/tree/master/src/app/features/map-svg-cut) file of my project

## 🔥 Exception or Error

Did not prompt me any warnings or errors

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.2
Node: 14.16.0
Package Manager: yarn 1.22.5
OS: darwin x64

Angular: 12.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@angular/localize               12.2.0
@schematics/angular             12.2.2
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
