### ISSUE TITLE
[REGRESSION][v12.2] Font is no longer loaded

### ISSUE THREAD

**Issue by hakimio** [angular/angular-cli#21662]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build
- [x] serve

### Is this a regression?

Yes, the previous version in which this bug was not present was: 12.1

### Description

I have attached a simple demo app which reproduces the issue. Basically following font import in `foo-bar.css` (included in `angular.json` styles section) is ignored in v12.2 but works as intended in v12.1:
```
@import 'https://fonts.googleapis.com/css2?family=Manrope:wght@500;800&display=swap';
```

## 🔬 Minimal Reproduction

- Install dependencies and run `ng serve` in the demo project provided

## 🌍 Your Environment

<pre><code>
@angular/cli 12.2.3
@angular-devkit/architect    0.1202.3
@angular-devkit/core         12.2.3
@angular-devkit/schematics   12.2.3
@schematics/angular          12.2.3

</code></pre>

## 🐛 Bug demo

[import-bug2.zip](https://github.com/angular/angular-cli/files/7066465/import-bug2.zip)

**Comment by hakimio** [comment]
@alan-agius4 Sorry to bother you again but can you please test another reproduction when you have some time.
Following is a little bit bigger project but the issue is exactly the same.

## Reproduction

1. Clone `ng-v12.2-bug` branch in `hakimio/ngx-ui-tour` git repo:
https://github.com/hakimio/ngx-ui-tour/tree/ng-v12.2-bug
2. Install dependencies
`yarn install`
3. Serve the demo app with `ng serve`
4. Check the "Network" tab to see if the "Manrope" font is loaded by searching for "Manrope" (browser cache should be disabled)
5. The search result should be empty and you should see that the font is not applied to the text of the app
6. However the font should be loaded since it is included the following way:
`angular.json styles section -> node_modules/@taiga-ui/core/styles/taiga-ui-theme.less -> theme/fonts.css -> @import 'https://fonts.googleapis.com/css2?family=Manrope:wght@500;800&display=swap';`

## Additional Info
If you downgrade Angular to **v12.1**, you should see that the font is being loaded:

![Angular downgrade](https://user-images.githubusercontent.com/768105/131470615-3254c6fd-9d6c-4996-9d04-ab3823dce463.PNG)

![Manrope font load](https://user-images.githubusercontent.com/768105/131470618-5921d661-0ad3-4a53-a135-67f15517446b.png)

**Comment by alan-agius4** [comment]
Look like it's working as expected 

![Screenshot 2021-08-31 at 10 56 20](https://user-images.githubusercontent.com/17563226/131473715-b427a8ea-c10d-436d-bdc3-7ef3f35e7a43.png)

**Comment by hakimio** [comment]
@alan-agius4 I can't see from that screenshot if the font `Manrope` font is loaded. Why did you attach that image?

**Comment by alan-agius4** [comment]
So indeed the `Monorope` font is not being loaded. I managed to track down the issue to [css-loader](https://github.com/webpack-contrib/css-loader), previously it moved absolute `@imports` to the top of the file but now they are not which causes the `@import` to become invalid since @import need to appear at the top of the file. https://developer.mozilla.org/en-US/docs/Web/CSS/@import#description

**Comment by hakimio** [comment]
Do you plan to open bug report in `css-loader` repo? Should `angular-cli` have some kind of workaround for `css-loader` bug?

**Comment by alan-agius4** [comment]
Opened an issue https://github.com/webpack-contrib/css-loader/issues/1365, let's see what's their response.

**Comment by hakimio** [comment]
Thank you.

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/21681
