### ISSUE TITLE
some time ng serve or other command to give result as "Error"

### ISSUE THREAD

**Issue by karthikkavin** [angular/angular-cli#2166]
I have used node v6.6.0 and npm 3.9.5 windows 10. 
I have successfully installed angular cli and build my existing version to new beta14.
Initially we do ng server its build and working good.
But sometime did not work. No error found, just display on command prompt "Error"
It doesn't run these commands concurenty.
>ng serve
Error
ng test
Error
my npm debug log file show error like below.

17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user1_000\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.6.0
20 error npm  v3.9.5
21 error code ELIFECYCLE
22 error grosspad-web@0.0.0 start: `ng serve`
22 error Exit status 1
23 error Failed at the grosspad-web@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the grosspad-web package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs grosspad-web
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls grosspad-web
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Please any one advise.

**Comment by bthharper** [comment]
I had this problem too, and ideally a more descriptive error would be displayed.  It often doesn't happen until you restart *ng* (serve or build) so you can be several edits down before you notice.

For information, my issue was with having duplicate entries in the "styles" element of angular-cli.json, just in case that helps.

**Comment by karthikkavin** [comment]
I did it new project and add styles and scripts are manually only. Some third party like moment packages are installed. 
I just started work now.

**Comment by blackfan23** [comment]
I had this error, while having a trailing comma in angular-cli.json. After removing it the message disappeared.

**Comment by karthikkavin** [comment]
I found the issue and fixed now. close this issue.
