### ISSUE TITLE
Install angular cli in locally getting this error. But installed.

### ISSUE THREAD

**Issue by karthikkavin** [angular/angular-cli#2167]
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [C:\MyProject\PrudenceMaster\GrosspadWeb\node_m
odules\node-zopfli\build\zopfli.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\MyProject\\PrudenceMaster\\GrosspadWeb\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=C:\\MyProject\\PrudenceMaster\\GrosspadWeb\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\MyProject\\PrudenceMaster\\GrosspadWeb\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-zopfli
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\MyProject\\PrudenceMaster\\GrosspadWeb\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1

> node-sass@3.10.0 install C:\MyProject\PrudenceMaster\GrosspadWeb\node_modules\node-sass
> node scripts/install.js

How to fix this.

**Comment by Aorewen** [comment]
Same. Related troubles imo : https://github.com/angular/angular-cli/issues/2135

**Comment by karthikkavin** [comment]
@Aorewen  Can you find the solution or any step to fix.

**Comment by Aorewen** [comment]
i m lost as u

**Comment by DavideViolante** [comment]
I've the same error when running:
`npm install -g angular-cli`
- Node 6.6.0
- npm 3.10.3
- Win 10 x64

**Comment by karthikkavin** [comment]
Yes cli installed successfully. Is there any problem in future.
