### ISSUE TITLE
Duplicated global styles 

### ISSUE THREAD

**Issue by FaizNL** [angular/angular-cli#21672]
# 🐞 Bug report

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The styles that are in styles.scss are duplicated only in production. 

## 🔬 Minimal Reproduction

Add styles in styles.scss and then run "ng build" you see that the styles are duplicated in document <style> tag and in the styles.xxxxxx.css file.

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.3
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 12.2.3
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

</code></pre>

**Comment by alan-agius4** [comment]
This is working as expected.

Critical styles from the global stylesheets are inlined in the HTML file to reduce render blocking requests and improve FCP and LCP.
