### ISSUE TITLE
@schematics/angular use typescript in third_party not in node_modules

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular-cli#21676]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes
### Description
when update v12,
`@schematics/angular`throw error
```log
src/types/update-base.ts:34:35 - error TS2345: Argument of type 'import("/Users/chen/my-project/prophet-schematics/node_modules/typescript/lib/typescript").SourceFile' is not assignable to parameter of type 'import("/Users/chen/my-project/prophet-schematics/node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript").SourceFile'.
  Types of property 'kind' are incompatible.
    Type 'import("/Users/chen/my-project/prophet-schematics/node_modules/typescript/lib/typescript").SyntaxKind.SourceFile' is not assignable to type 'import("/Users/chen/my-project/prophet-schematics/node_modules/@schematics/angular/third_party/github.com/Microsoft/TypeScript/lib/typescript").SyntaxKind.SourceFile'.

34         let result = insertImport(sourceFile, this.filePath, moduleName, filePath) as InsertChange;
                                     ~~~~~~~~~~


Found 1 error.
```
`typescript` dependency use `third_party` folder and get type conflict
 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
It’s looks like the root issue is that `prophet-schematics` is using parts of the private APi of `@schematic/angular` and the TypesScript minor version doesn’t match.

**Comment by wszgrcy** [comment]
> It’s looks like the root issue is that `prophet-schematics` is using parts of the private APi of `@schematic/angular` and the TypesScript minor version doesn’t match.

I use `import { insertImport } from '@schematics/angular/utility/ast-utils';`
it can be used by developer?

**Comment by alan-agius4** [comment]
Anything which is imported via a deep import is to be considered as private API.
