### ISSUE TITLE
Angular JSON | ASSETS | incorrect type. Expected 'object'

### ISSUE THREAD

**Issue by abelardovn** [angular/angular-cli#21674]
### Description

Hi there,

I am using Angular  CLI 11.2.14.

Inside angular.json, under [Assets Configuration](https://v11.angular.io/guide/workspace-config#asset-config), is stated that _An object containing paths to..._ but an array is found below:
![image](https://user-images.githubusercontent.com/87799097/131333620-2ec1ede6-f00d-46be-939a-ace378d93368.png)

When I wrote an array instead of object:
![image](https://user-images.githubusercontent.com/87799097/131333714-71d90c08-0e7c-4bf0-99f4-c9403e59c2ee.png)

If I write an object, I can't write more assets object.

What's the valid syntax for this object, please?
NPM version: 6.13.4
Node version: 12.14.0
Angular CLI: 11.2.14

Thanks

### Please provide the steps to reproduce the issue

Inside angular.json, write a basic configuration to set some assets by using Angular CLI 11.2.14

### Please provide the expected behavior vs the actual behavior you encountered

Expected behaviour:
I can write an array with several assets objetcts.

Actual behaviour:
A message indicates: "Incorrect type. Expected 'object'

**Comment by abelardovn** [comment]
Thanks and sorry for the inconveniences for opening this issue at other project.

**Comment by alan-agius4** [comment]
The above mentioned syntax is correct. I did try to replicate the issue locally using VSCode but I wasn't able.

**Comment by abelardolg** [comment]
Hi there, 

Which Angular version did you use, @alan-agius4? 

I would like to contrast your information with my workmates. Thanks.

**Comment by alan-agius4** [comment]
I used `11.2.14`

**Comment by abelardolg** [comment]
I just created an Angular 11.2.14 project and it happens:
![image](https://user-images.githubusercontent.com/22522883/131373245-20b69614-2ddc-4aad-9fb3-8eb4d68060f1.png)

Package.json dependencies:
![image](https://user-images.githubusercontent.com/22522883/131373394-e663c130-2fd5-4541-ae35-0c307ef9fcb1.png)

![image](https://user-images.githubusercontent.com/22522883/131373501-7a49b93d-4c4a-474c-baa2-7ef41e4f3af4.png)

Could you find out some differences with your package.json, @alan-agius4 , please?

Thanks.

**Comment by abelardolg** [comment]
My original issue happened on Windows 10. As you can see, I checked it out on Linux Ubuntu.

**Comment by abelardolg** [comment]
My fault, @alan-agius4 : 
I put "assets" under "server/configurations" and then "server/options".
Sorry for wasting your valuable time. Thanks and best regards.
