### ISSUE TITLE
valid app URL containing a period results in "Cannot GET" error

### ISSUE THREAD

**Issue by chalin** [angular/angular-cli#2168]
The ng2.io app has pages at URLs like

  http://localhost:4200/docs/ts/latest/quickstart.html

(note the `.html` suffix). I can navigate by clicking links in the app, but if I copy-paste a valid app URL (like the previous one), I get:
```
Cannot GET /docs/ts/latest/quickstart.html
```
And if we deploy to firebase, it all works fine. How can we coerce `ng serve` into playing nice?

1. OS?  OSX 10.11.6
2. Versions. 
angular-cli: 1.0.0-beta.14
node: 6.5.0
os: darwin x64

cc @filipesilva @ericjim

**Comment by chalin** [comment]
ping

**Comment by chalin** [comment]
Actually, a period anywhere in the URL causes this problem (Dart API URLs contain periods because of periods in library names like `angular2.common`).

@naomiblack

**Comment by denkomanceski** [comment]
+1

**Comment by denkomanceski** [comment]
One way how I resolved this temporary is stop using html5 style and use hashstrategy instead

**Comment by filipesilva** [comment]
As context, there seems to be a solution in https://github.com/webpack/webpack-dev-server/pull/303 but it requires rewriting on a case-by-case basis, which just wouldn't work for the CLI.

**Comment by filipesilva** [comment]
I've tested it and this option fixes our issue https://github.com/bripkens/connect-history-api-fallback/commit/ee8611164c4a06ed87d7b98b16dedb89f60ff3a3

But it's part of `1.3.0` of `connect-history-api-fallback` which is not yet required by `webpack-dev-server: https://github.com/webpack/webpack-dev-server/blob/master/package.json#L11
