### ISSUE TITLE
Update webpack-dev-server in @angular-devkit/build-angular@0.901.15

### ISSUE THREAD

**Issue by cronon** [angular/angular-cli#21686]
# 🐞 Bug report

### Description

@angular-devkit/build-angular@0.901.15 has dependency webpack-dev-server@3.11.0 which has a high severity vulnerability according to npm audit. It is fixed in webpack-dev-server@3.11.2

**Comment by alan-agius4** [comment]
Version 9 is no longer under LTS. Please update to a more recent version of Angular CLI. 

See: https://angular.io/guide/releases#support-policy-and-schedule for more information
