### ISSUE TITLE
Inlining of critical CSS causes security issue with Content-Security-Policy

### ISSUE THREAD

**Issue by jcmalek** [angular/angular-cli#21683]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 11 (sorry I can't be more specific)

### Description

The new inlining of critical CSS causes a security issue when server Content-Security-Policy has script-src-attr set to 'self' or 'none'.

## 🔬 Minimal Reproduction

(1) Build a web client project:
ng build
(2) Copy the contents of the "dist" folder to wherever you will be serving it from
(3) Set the web server header:
Content-Security-Policy: script-src-attr 'self';
(4) Start the web server
(5) Navigate to the main page in Chrome (index.html)
http://localhost:8888
(6) Open the Chrome inspector and see the error generated in the console (see below)

## 🔥 Exception or Error

<pre><code>
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src-attr 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
</code></pre>

Which refers to the following line from the associated Angular feature which is causing the problem:
<pre><code>
&lt;link rel="stylesheet" href="styles.579d5eb3749bba47a163.css" media="print" onload="this.media='all'"&gt;
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.2
Node: 14.17.3
Package Manager: yarn 1.17.3
OS: win32 x64

Angular: 12.2.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.2
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.2.2
@angular-devkit/schematics      12.2.2
@schematics/angular             12.2.2
rxjs                            7.3.0
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

This bug was introduced by pull 19449:
https://github.com/angular/angular-cli/pull/19449

The related RFC which mentions the offending "media" technique which is causing this issue:
https://github.com/angular/angular-cli/issues/18730

I am currently working around the problem by simply disabling the feature in angular.json:
          "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": true
              },

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/20864

**Comment by jcmalek** [comment]
Absolutely. Thanks. My bad. That didn't come up when I searched.
