### ISSUE TITLE
Deprecated packages warnings (resolve-url, urix, tslint, uuid, querystring, chokidar, request, fsevents) on npm install in Angular V10 and V11

### ISSUE THREAD

**Issue by FaabLondon** [angular/angular-cli#21697]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
- [x] install

### Is this a regression?

The previous version in which this bug was not present was: Angular V9
The issue started appearing after an upgrade to Angular V10 and kept appearing after a Angular V11 upgrade

### Description

After upgrading to Angular V10 and then to Angular 11.12.14 and running npm install,  I am getting quite a few warnings about deprecated packages within `angular-devkit/build-angular@0.1102.14` and `angular/cli@11.2.14` :
- resolve-url@0.2.1
- urix@0.1.0
- tslint@6.1.0
- uuid@3.4.0
- chokidar@2.1.8
- fsevents@1.2.13
- querystring@0.2.0
- request@2.88.2

Here is what I get hen running 
`Npm ls urix@0.1.0 resolve-url@0.2.1 querystring@0.2.0 request@2.88.2 tslint@6.1.0 uuid@3.4.0 fsevents@1.2.13 chokidar@2.1.8`

─┬ @angular-devkit/build-angular@0.1102.14
│ ├─┬ stylus@0.54.8
│ │ └─┬ css-parse@2.0.0
│ │   └─┬ css@2.2.4
│ │     ├─┬ source-map-resolve@0.5.3
│ │     │ ├── resolve-url@0.2.1
│ │     │ └── urix@0.1.0 deduped
│ │     └── urix@0.1.0
│ ├── tslint@6.1.0 deduped
│ ├─┬ webpack-dev-middleware@3.7.2
│ │ └─┬ webpack-log@2.0.0
│ │   └── uuid@3.4.0
│ ├─┬ webpack-dev-server@3.11.2
│ │ ├─┬ chokidar@2.1.8
│ │ │ └── fsevents@1.2.13
│ │ ├─┬ sockjs@0.3.21
│ │ │ └── uuid@3.4.0
│ │ └─┬ url@0.11.0
│ │   └── querystring@0.2.0
│ └─┬ webpack@4.44.2
│   ├─┬ micromatch@3.1.10
│   │ └─┬ snapdragon@0.8.2
│   │   └─┬ source-map-resolve@0.5.3
│   │     ├── resolve-url@0.2.1 deduped
│   │     └── urix@0.1.0 deduped
│   └─┬ watchpack@1.7.5
│     └─┬ watchpack-chokidar2@2.0.1
│       └─┬ chokidar@2.1.8
│         └── fsevents@1.2.13
├─┬ @angular/cli@11.2.14
│ ├─┬ pacote@11.2.4
│ │ └─┬ @npmcli/run-script@1.8.6
│ │   └─┬ node-gyp@7.1.2
│ │     └── request@2.88.2 deduped
│ └─┬ universal-analytics@0.4.23
│   ├── request@2.88.2 deduped
│   └── uuid@3.4.0

## 🔬 Minimal Reproduction

- rm -rf node_modules/ 
- npm cache clear --force 
- rm package-lock.json

Then
- npm install

## 🔥 Exception or Error
<pre><code>
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tslint@6.1.0: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.14
Node: 14.16.0
OS: darwin x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      12.2.3
@angular/cdk                    11.2.13
@angular/material               11.2.13
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.5.5
typescript                      4.0.7

</code></pre>

**Anything else relevant?**

OS: macOS Big Sur V 11.4
npm v7.21.1

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. 


All the below deprecations comes from transitive dependencies which we don't have control over. 
```
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
```

The below, is however actionable from your end. Tslib has been deprecated and users should move towards Eslint. See https://github.com/angular-eslint/angular-eslint#migrating-an-angular-cli-project-from-codelyzer-and-tslint for more information. 
```
npm WARN deprecated tslint@6.1.0: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
```

Unfortunately, there isn't anything that we action here.
