### ISSUE TITLE
Upgrade to webpack-dev-server 4 which is already out

### ISSUE THREAD

**Issue by AndriiNeverov** [angular/angular-cli#21703]
# 🚀 Feature request

### Command (mark with an `x`)

- [ x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

webpack-dev-server 3 depends on -> chokidar 2

which produces the following warnings and according to them may lead to breakages:

npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

### Describe the solution you'd like

Angular CLI should make a plan to upgrade to webpack-dev-server 4.

### Describe alternatives you've considered

Not aware of any alternatives.

**Comment by alan-agius4** [comment]
This has been addressed via https://github.com/angular/angular-cli/pull/21634 and is available in the version 13 prerelease.
