### ISSUE TITLE
ng build issue with docker

### ISSUE THREAD

**Issue by CleverMobile2811** [angular/angular-cli#21707]
After migration 11 to 12.

ng build works fine locally
but fail with docker.

/app/src/app/register/register.component.scss - Error: /app/src/app/register/register.component.scss from Css Minimizer
#15 113.9 Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at minify (/app/node_modules/@angular-devkit/build-angular/src/webpack/configs/styles.js:276:58)
#15 113.9     at minify (/app/node_modules/css-minimizer-webpack-plugin/dist/minify.js:15:32)
#15 113.9     at /app/node_modules/css-minimizer-webpack-plugin/dist/index.js:262:128
#15 113.9     at /app/node_modules/css-minimizer-webpack-plugin/node_modules/p-limit/index.js:23:31
#15 113.9     at run (/app/node_modules/css-minimizer-webpack-plugin/node_modules/p-limit/index.js:23:43)
#15 113.9     at /app/node_modules/css-minimizer-webpack-plugin/node_modules/p-limit/index.js:45:20

#15 113.9 Error: Optimization error [157.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [358.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [polyfills.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [574.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [947.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [171.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [935.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [main.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32
#15 113.9 
#15 113.9 Error: Optimization error [runtime.js]: Error: spawn Unknown system error -8
#15 113.9     at ChildProcess.spawn (node:internal/child_process:412:11)
#15 113.9     at Object.spawn (node:child_process:698:9)
#15 113.9     at ensureServiceIsRunning (/app/node_modules/esbuild/lib/main.js:1718:29)
#15 113.9     at Object.transform (/app/node_modules/esbuild/lib/main.js:1633:37)
#15 113.9     at default_1 (/app/node_modules/@angular-devkit/build-angular/src/webpack/plugins/javascript-optimizer-worker.js:18:43)
#15 113.9     at /app/node_modules/piscina/dist/src/worker.js:141:32

Please feel free to check and let me know what the problem is.

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by CleverMobile2811** [comment]
"@angular-devkit/build-angular": "^12.2.2",
"@angular/cli": "^12.2.2",
"@angular/compiler-cli": "~12.2.2",

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by clydin** [comment]
Is the node modules directory shared between the host machine and the docker image?
If so, are the two operating systems different?

**Comment by draggie** [comment]
@clydin I came here with the same problem and your comment helped me to fix this. Building application with Angular 12 on Windows for docker container - when added node_modules directory to .dockerignore the issue disappeared and optimization works fine!

**Comment by alan-agius4** [comment]
Closing as per above comment.
