### ISSUE TITLE
Problem compiling custom bootstrap in scss | Error with relative paths

### ISSUE THREAD

**Issue by gperdomor** [angular/angular-cli#2170]
> ## Please provide us with the following information:
1. OS? 
   macOS Sierra
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli: 1.0.0-beta.14
   node: 6.5.0
   os: darwin x64
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   Install bootstrap-sass and create a new scss file `src/scss/bootstrap.scss` and copy the content of the original bootstrap.scss in that file... Why create this file? because i need to import some extra files to override bootstrap styles
4. The log given by the failure. Normally this include a stack trace and some
   more information.
   ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/scss/bootstrap.scss
   Module not found: Error: Can't resolve '../fonts/bootstrap/glyphicons-halflings-regular.svg' in '/Users/xxxxxxxx/WebstormProjects/xxxxxxx/src/scss'
5. Mention any other details that might be useful.
   In previous project, using react, i need to configure resolve-url-loader in webpack:
   
   <pre><code>{
   test: /\.scss$/,
   loader: ExtractTextPlugin.extract("style", 'css?sourceMap!resolve-url!sass?sourceMap'),
   }
   </code></pre>

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by JanStureNielsen** [comment]
The issue tracker is for bugs and feature requests; see [CONTRIBUTING.md](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md). For better support, consider creating a question on StackOverflow with all the details.

**Comment by gperdomor** [comment]
@JanStureNielsen well, angular-cli don't have any config to include the resolve-url loader, so, i think this could be considered as a feature request :D

**Comment by j2L4e** [comment]
`$icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
@import "~bootstrap-sass/assets/stylesheets/bootstrap";`

is all you need...

**Comment by filipesilva** [comment]
@j2L4e seems like the right answer to me. He's configuring the directory used by bootstrap prior to importing it.

**Comment by gyoshev** [comment]
Just tried the suggestion with overriding the `$icon-font-path` variable, and it does not seem to work.

1. OS: Linux, Fedora 24
2. Versions: angular-cli: 1.0.0-beta.17, node: 4.6.0, os: linux x64
3. Repro steps ([repo with applied steps](https://github.com/gyoshev/angular-cli-font-icons), [hosted result](http://blog.gyoshev.net/angular-cli-font-icons/)):

   1. create app and add bootstrap-sass

             ng init --style=sass
             npm install --save bootstrap-sass

   2. change `src/app/app.component.html` to

             <span class="glyphicon glyphicon-camera"></span>

   3. edit `src/app/app.component.sass` to

             $icon-font-path: '~bootstrap-sass/assets/fonts/bootstrap/';
             @import '~bootstrap-sass/assets/stylesheets/bootstrap';

   4. run `ng serve`

The bootstrap CSS is now built correctly, but the browser then requests the wrong URL:

![image](https://cloud.githubusercontent.com/assets/90405/19561585/eb5beca2-96e1-11e6-89fc-09e68b7743fe.png)

**Comment by filipesilva** [comment]
Reopening to investigate @gyoshev's example.

**Comment by exequiel09** [comment]
Mine is set to this: 
```sass
$icon-font-path: if($bootstrap-sass-asset-helper, "bootstrap/", "../node_modules/bootstrap-sass/assets/fonts/bootstrap/")
```

`bootstrap.scss` is imported in `styles.sass` like this:

```sass
$bootstrap-sass-asset-helper: false
$icon-font-path: if($bootstrap-sass-asset-helper, "bootstrap/", "../node_modules/bootstrap-sass/assets/fonts/bootstrap/")
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap"
```

The `.woff` file is the renamed version of the glyphicon mainly because webpack renames it.

![screen shot 2016-11-09 at 5 45 20 am](https://cloud.githubusercontent.com/assets/19315680/20118554/e2941d2a-a63f-11e6-87a6-4528b49cc640.png)

**Comment by Krisa** [comment]
I have a similar problem with another library than bootstrap. The problem is actually quite "simple". In the library I'm using (like probably in bootstrap), the path between a css and an image is always relative to the css loading the file. It's not absolute or relative to anything else, because the library is not making any assumption where the module could be located. 

However Angular CLI tries to resolve the path, not relatively to the loaded file, but relatively to the package.json of the project (or maybe angular-cli.json). This cause every such library to fail because the asset can never be located correctly.

**Comment by rajasaur** [comment]
@Krisa : Did u get a solution for the above? Im having to delete the entries in _glyphicons-halflings.scss(that are relative paths) and replace the locations of the file as an absolute path to get "ng build" to work properly .

**Comment by intellix** [comment]
This works for me with font-awesome:

```
$fa-font-path: '../node_modules/font-awesome/fonts';
@import '~font-awesome/scss/font-awesome';
```
