### ISSUE TITLE
Library: Dynamic compile-time constants from environment

### ISSUE THREAD

**Issue by s-geiger-si** [angular/angular-cli#21716]
# 🚀 Feature request

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I have the requirement that I need to inject dynamically generated constants into the library during compile time. For example, I want to generate a unique version string (i.e., version string 1.0.0-dev.12345, build number 12345, git commit hash or commit/build date, etc.) from the CI/CD environment for each build and compile that string into the compiled library so it is available at runtime.

### Describe the solution you'd like

I want to create a metadata class that exposes the information at runtime of the library so that the library can provide information about it self to consumers of the library. The information should be injected at compile time by the CI/CD environment via Environment variables or command line options. In addition, the process should be in such a way, that it does not interrupt the developer workflow if these values are not present or undefined in the local developers work space in a dev environment.

Ideally, we could use the `environment.ts` and `environment.prod.ts` for this, where the `environment.ts` contains some default values such as `"version": '0.0.0'` and the `environment.prod.ts` receives that actual version during compile time from the CI/CD environment via some thing like `ng build my-lib --configuration production -D version=1.0.0-dev.12345 -D build-number=12345`. Note, that this line might not appear literally in a `package.json` but could be invoked from `npm run` via something like `npm run build:prod -- -D version=1.0.0-dev.12345 -D build-number=12345` assuming that the `build:prod` script resolves to `ng build my-lib --configuration production`.

### Describe alternatives you've considered

For plain Angular applications we are using the [custom-webpack][1] plugin, to modify the build process and inject values via Webpack's [DefinePlugin][2] or copy files via the [copy-webpack-plugin][3]. I just learned that when we are building libraries the Angular CLI uses [ng-packagr][4] and I do not see an equally straitforward way to inject custom build steps where I can integrate such steps.

It it possible at the moment and I just missed it? If not, are there known workarounds? If its not possible, could you add support for it? 

# PS

It seems what I am asking for is common in most programming languages. C/C++ has had pre-processor defines since forever and this is well integrated into higher level build tools like CMake, Autotools or Meson. In other environments like with MS dotnet we can [declare build-time properties][5] with the `-p` option. Its also possible in Java (`-D` option). Docker has `--build-arg` for this.

[1]: https://www.npmjs.com/package/@angular-builders/custom-webpack
[2]: https://webpack.js.org/plugins/define-plugin/
[3]: https://www.npmjs.com/package/copy-webpack-plugin/
[4]: https://github.com/ng-packagr/ng-packagr
[5]: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build#msbuild

**Comment by alan-agius4** [comment]
This looks like an ng-packagr feature request. Moving to ng-packagr.

**Comment by alan-agius4** [comment]
Opened https://github.com/ng-packagr/ng-packagr/issues/2070 since I cannot transfer cross-org.
