### ISSUE TITLE
ng serve no longer writes to disk

### ISSUE THREAD

**Issue by ericj79** [angular/angular-cli#2171]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.14
node: 6.3.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I updated my project from beta 9 to beta 14, which now uses web pack following the beta 10 to beta 12 guide. The upgrade went fine, but now when i run 'ng serve' I cannot find where anything is written to disk as a result of the transpiling. In the old version the files were written to disk.

4. The log given by the failure. Normally this include a stack trace and some
   more information.
There is no log. I just don't like the new behavior.

5. Mention any other details that might be useful.
In my environment my angular app is just a portion of a larger site. The app depends on some of these external resources. So I had a setup where I could run _ng serve_ in a window and edit my code in a separate window. When I was ready to test it I would save things, wait for _ng serve_ to compile the updates, then those new files would be synced to my server where I could test them. Now that _ng serve_ does not write things to the expected folder, or anywhere to disk that I am finding, I have to run _ng build_ instead. This means that the build is a complete build each time, which takes longer than a partial build, and there are more files to transfer over each time. The biggest pain is that I have to urn the command by hand, where _ng serve_ was just watching the file for me before.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kylecordes** [comment]
This is by design. In development ("serve") mode, the contents are compiled and served from memory. Among many other things, this greatly improved performance issues on Windows, where managing hundreds or thousands of temporary files is especially inefficient.

**Comment by ericj79** [comment]
I realize that the new behavior is probably much more efficient for most people, but is there a setting where I can tell it to write the output to disk, and accept the hit in general efficiency? this would help the efficiency of my non standard workflow?

**Comment by kylecordes** [comment]
I believe it is something like ```ng build --watch```.

**Comment by ericj79** [comment]
that solves my issue. Thanks
