### ISSUE TITLE
Angular Custom builder

### ISSUE THREAD

**Issue by ParulChak** [angular/angular-cli#21715]
How to add angular builder/custom webpack for different environment ?
 
Currently I am using the custom builder for "serve", like this
```
"serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "qcg-frontend:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "qcg-frontend:build:production"
            },
            "qa": {
              "browserTarget": "qcg-frontend:build:qa"
            },
            "local": {
              "browserTarget": "qcg-frontend:build:local"
            },
}

```
I have tried to add builder option inside "local" also, but it is not working
, so How we add this builder for "serve local" ?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
