### ISSUE TITLE
ng new [PROJECT NAME], eslint is not added by default. (Angular CLI: 12.2.4)

### ISSUE THREAD

**Issue by qyjs** [angular/angular-cli#21717]
### Description

Angular CLI: 12.2.4

ng new [PROJECT NAME]

After this command is executed, eslint is not added by default

### Proposed solution

Add eslint by default

### Alternatives considered

eslint

**Comment by alan-agius4** [comment]
Closing as this is indeed by design

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/20769
