### ISSUE TITLE
unable to load schemma

### ISSUE THREAD

**Issue by Arham1019** [angular/angular-cli#21724]
Unable to load schema from 'c:\Users\Aksystems\Desktop\Xynotech\si-integration\node_module\@angular\cli\lib\config\schema.json': ENOENT: no such file or directory, open 'c:\Users\Aksystems\Desktop\Xynotech\si-integration\node_module\@angular\cli\lib\config\schema.json
![Capture](https://user-images.githubusercontent.com/79666205/132506547-ca08efa6-350f-49ea-a486-67f028766add.PNG)

**Comment by alan-agius4** [comment]
The path of the schema isn’t correct.

```diff
- schema": "./node_module/@angular/cli/lib/config/schema.json",
+ schema": "./node_modules/@angular/cli/lib/config/schema.json",
```
