### ISSUE TITLE
Build error after Migration from Angular Version 11 to 12 with SVG resources

### ISSUE THREAD

**Issue by sven42** [angular/angular-cli#21738]
# 🐞 Bug report

### Command

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, it worked in many previous Angular versions up to latest Angular 11.2.14

### Description

After migrating our application to Angular Version 12, `ng build` and `ng serve ` report many errors, that module parsing failed, eg:
```
./node_modules/@jupyterlab/ui-components/style/icons/toolbar/undo.svg:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
...
```

The problem seems to be caused by the third-party javascript dependency @jupyterlab/* which uses some SVG-Resources in their CSS. 
I know that Angular 12 switched to use webpack 5, but as we do not customize webpack, I wonder what to do, if some third party javascript dependencies cause the error.

This could be a duplicate of https://github.com/angular/angular-cli/issues/20954
However, that issue was commented with "expected breaking change". 
The solution to solve the problem is unknown and the ticket was auto-closed. 
And the solution might be another, if the errors are caused by third party dependencies.

## 🔬 Minimal Reproduction

Here is a repository showing the problem: https://github.com/sven42/angular12-webpack5-svg-problem
1. check out
2. npm install
3. npm run build 

This is what I did in the repo, each step committed separately:
- Create new angular-project with Angular-CLI 12
- Add jupyter-cell.component.ts with dependencies from @jupyterlab, declare it in app.module.ts, set allowSyntheticDefaultImports to true to fix compiler error.
- Use jupyter-cell.component in app.component.html

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.5
Node: 14.17.6
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 12.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Comment by alan-agius4** [comment]
This is working as intended.

See one of the breaking changes in version 12 https://github.com/angular/angular-cli/commit/6732294ff34ca35698cec5a9ca91b664dd684289.

`@jupyterlab/ui-components` are importing SVG files as if they were ECMA modules (see link below) which is non standard syntax and is not support by the Angular CLI. While, the CLI is using Webpack, this is an implementation detail and Webpack specific features are not support.


https://github.com/jupyterlab/jupyterlab/blob/7c5092e0d8d5d8e7fc2d1e51f8e4f9258d49922d/packages/ui-components/src/icon/iconimports.ts 

As a workaround, you could use a 3rd party builder such as [ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus) to extend the Angular CLI and provide a custom Webpack configuration. It's important to point that custom Webpack configuration are not supporting by the Angular tooling team.
