### ISSUE TITLE
rename the generated index.html 

### ISSUE THREAD

**Issue by wyyufeng** [angular/angular-cli#21736]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I want to rename the index.html after the build,just like `html-webpack-plugin` `filename` option.
is there any way to  set it 🤔

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
You can use the `index` option in the browser builder
```json
"index": {
  "input": "src/index-prod.html",
  "output": "index.html"
}
```
