### ISSUE TITLE
`ng s` and `ng b` commands are very slow on Windows 10

### ISSUE THREAD

**Issue by m-primo** [angular/angular-cli#21731]
# 🐞 Bug report

### Command

- [x] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

The commands checked above are extremely slow. It was slow before, but is much slower than before.

## 🔥 Exception or Error

NONE.

## 🌍 Your Environment
<pre><code>
Windows 10 1809
Node 15.12.0
npm 7.6.3
Angular 12.0.1
</code></pre>

<pre><code>
Angular CLI: 12.0.1
Node: 15.12.0
Package Manager: npm 7.6.3
OS: win32 x64

Angular: 12.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.1
@angular-devkit/build-angular   12.0.1
@angular-devkit/core            12.0.1
@angular-devkit/schematics      12.0.1
@angular/cdk                    12.1.4
@angular/material               12.1.4
@schematics/angular             12.0.1
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

## Additional Details
 
It's not only slow in this environment only, it's slow in every project/environment I work on.

**Comment by alan-agius4** [comment]
Can you try using a supported Node.JS version? Ideally the latest LTS version?

If the problem persists can you please please provide CPU profiles of builds before and after the update?

**Comment by clydin** [comment]
Also, if possible, please try to update to the latest stable release of Angular (currently 12.2.5).

**Comment by alan-agius4** [comment]
Closing due to lack of communication.
