### ISSUE TITLE
Tailwind JIT not detecting changes (Angular 12).

### ISSUE THREAD

**Issue by harvanchik** [angular/angular-cli#21749]
### Which @angular/* package(s) are the source of the bug?

@angular/cli

### Is this a regression?

No

### Description

I updated from Angular 11 to 12, and now Tailwind JIT is not applying style changes when I add make changing in the HTML. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/BlockeySports/BlockeyHockeyWebApp

### Please provide the environment you discovered this bug in

<pre><code>Angular CLI: 12.2.5
Node: v12.14.1
Package Manager: npm 7.23.0
OS: Windows 10 x64

Angular: 12.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@angular/cdk                    11.2.13
@angular/material               11.2.13
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem using the reproduction provided.

Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
