### ISSUE TITLE
unable to install in windows 10

### ISSUE THREAD

**Issue by orlandocruz1** [angular/angular-cli#21741]
Itry to clean the cache and update de node.

**`PS C:\Users\useradmin> npm install -g @angular/c**li
npm : npm WARN deprecated har-validator@5.1.5: this library is no longer supported
At line:1 char:1
+ npm install -g @angular/cli
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN deprec...onger supported:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known 
to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 239 packages, and audited 240 packages in 22s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities`

**Comment by alan-agius4** [comment]
The above look like warnings which are non fatal.
