### ISSUE TITLE
Cannot install Angular Material

### ISSUE THREAD

**Issue by abutizi** [angular/angular-cli#21746]
Hi community

When I try to install Angular Material, I get the following error:
`ng add @angular/material`

`Your global Angular CLI version (12.2.5) is greater than your local version (12.1.4). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
ℹ Using package manager: npm
✔ Found compatible package version: @angular/material@12.2.5.
✔ Package information loaded.

The package @angular/material@12.2.5 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: salgskernen-cms@0.0.1
npm ERR! Found: @angular/core@12.1.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.1.1" from the root project
npm ERR!   peer @angular/core@"^12.0.0 || ^13.0.0-0" from @angular/material@12.2.5
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"12.2.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"12.2.5" from @angular/animations@12.2.5
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^12.0.0 || ^13.0.0-0" from @angular/material@12.2.5
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"12.2.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\hayda\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hayda\AppData\Local\npm-cache\_logs\2021-09-12T00_53_02_808Z-debug.log
✖ Package install failed, see above.`

I am using Angular 12 with ionic.

I have absolutely no clue what to do. I googled what equates to the combined weight of thousands of sea whales and caught nothing!  

Any help is greatly appreciated!

**Comment by alan-agius4** [comment]
This appears to be a defect within npm 7. Make sure you are using the latest version. If the problem persists, there are several workarounds.

* Downgrade to npm 6
* Switch to yarn as a package manager
