### ISSUE TITLE
Style loaders not injecting styles into HTML

### ISSUE THREAD

**Issue by dexster** [angular/angular-cli#21747]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes.
`@angular-devkit/build-angular 12.1.4` works correctly. Updating to `@angular-devkit/build-angular@12.2.x` causes the issue

### Description

When loading styles using !style-loader!css-loader the styles are not injected into the HTML `<head>` tag.

## 🔬 Minimal Reproduction

Create a test project - `ng new loaders`

Add my-style.css to the app folder with this:
```
body {
    background-color: red !important;
}
```

Add this to app.ts:
`import '!style-loader!css-loader!sass-loader!./my-style.css'`

Then `ng serve`

You will see the background is not red, Inspecting the body element will show the style is not present

Uninstall `@angular-devkit/build-angular@12.2.x` and install `@angular-devkit/build-angular@12.1.4` and serve again. The styles will be loaded

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.2.5
Node: 14.15.5
Package Manager: npm 7.22.0
OS: darwin x64

Angular: 12.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Comment by alan-agius4** [comment]
Webpack specific syntaxes are not support by the Angular CLI.

The fact that Angular CLI uses Webpack is an implementation detail.

**Comment by alan-agius4** [comment]
Closing as per above comment.
