### ISSUE TITLE
`ng generate guard` does not let you choose interfaces

### ISSUE THREAD

**Issue by joelkesler** [angular/angular-cli#21755]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] generate

### Is this a regression?

Yes, as the behavior is broken compared to the docs and other articles explaining how to use this feature

### Description

When using the cli to generate a new guard, the cli tool becomes stuck on the "Which interfaces would you like to implement?" step, which does not give you the ability to choose the interfaces.

## 🔬 Minimal Reproduction

In your terminal, run `ng generate guard`

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/303329/133366890-c1a15f75-f3ea-4865-85f5-a10fb7f4bd82.png)

There should be a multi-select to choose the interface. None is shown. If you type in an interface, you receive the following error:

![image](https://user-images.githubusercontent.com/303329/133366673-a5e983c5-5ab9-4341-bdfa-8562c059bd69.png)

<pre><code>
❯ ng generate guard
✔ What name would you like to use for the guard? · can-deactivate
✔ Which interfaces would you like to implement? · CanDeactivate
Property 'implements' does not match the schema. 'CanDeactivate' should be a 'array'.

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.4
Node: 14.17.3
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/fire                   6.1.4
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             12.1.4
ng-packagr                      12.2.0
rxjs                            6.6.7
typescript                      4.3.5
    

</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Unfortunately, we are unable to replicate the issue as described.  Does this issue occur within only this project or do all projects experience the problem (for example, a newly generated project)? If it does occur for all projects, if possible, can you try a different terminal application and shell?

**Comment by alan-agius4** [comment]
Closing due to lack of communication.
