### ISSUE TITLE
proxy config works for some urls but not others, illogical and inexplicable behavior

### ISSUE THREAD

**Issue by bojidaryovchev** [angular/angular-cli#21751]
my proxy.conf.json file:

````
{
  "/v1": {
    "target": "https://example.com/v1",
    "secure": true,
    "pathRewrite": {
      "^/v1": ""
    },
    "changeOrigin": true
  }
}
````

path that works:
````
/v1/api/controller/endpoint
````

path that does not work:
````
/v1/controller/endpoint
````

Given that I am proxying all urls that start with ```/v1``` I would expect both of the aforementioned paths to work however that is not the case, ```/v1/controller/endpoint``` returns 404 for some reason. I tried creating another entry in the proxy.conf.json with a completely arbitrary value like for example instead of ```/v1``` I used ```/cat``` and then my url looked like ```/cat/controller/endpoint``` but that did not work either... I find this completely illogical, I thought that if we have that ```/v1``` proxy key it would mean that any url that starts with ```/v1``` will be proxied, therefore it would be easy to just prefix whatever we need with ```/v1``` and be done with it, but nooooooo, it doesn't work and it is driving me crazy.

Both of the endpoints have been tested through Swagger and Postman and they both work, just unable to proxy to them from the Angular.

The actual paths exposed from the back end look like this:

````
/v1/api/users/count
/v1/auth/token
````

````
Angular CLI: 12.2.5
Node: 14.15.4
Package Manager: npm 6.14.10
OS: win32 x64

Angular: 12.2.5
... animations, cdk, cli, common, compiler, compiler-cli, core 
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5
````

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. 

The CLI uses webpack-dev-server as a development server which in turn uses [http-proxy-middleware](http-proxy-middleware)

Can you try the simplify the configuration to the below?
```
{
  "/v1": {
    "target": "https://example.com",
    "secure": true,
    "changeOrigin": true
  }
}
```

If the problem persists please contact the author(s) of [http-proxy-middleware](http-proxy-middleware) project or file an issue on their issue tracker.

**Comment by bojidaryovchev** [comment]
nope, that doesn't help... well thanks anyway, cheers
