### ISSUE TITLE
v12 Webpack Context.Keys().Map No Longer Works 

### ISSUE THREAD

**Issue by Marshal27** [angular/angular-cli#21764]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [X] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.2.14

### Description

- 11.2.14 the `context module API` for Webpack functioned properly, now any attempt to `filter` or `map` `context.keys()` fails/is ignored.

https://webpack.js.org/guides/dependency-management/#context-module-api

below official Webpack example to filter context keys no longer works.
```
const cache = {};

function importAll(r) {
  r.keys().forEach((key) => (cache[key] = r(key)));
}

importAll(require.context('../components/', true, /\.js$/));
// At build-time cache will be populated with all required modules.
```
## 🔬 Minimal Reproduction
`filter` or `map` keys in `test.ts` and notice all found spec.ts files from the regex and their respective modules will attempt to build

## 🔥 Exception or Error
Following exception from `/node_modules/@ngtools/webpack/src/ivy/loader.js:60:26` is generated regardless of `map` or `filter` attempts in above webpack example.

```
else {
                // File is not part of the compilation
                const message = `${this.resourcePath} is missing from the TypeScript compilation. ` +
                    `Please make sure it is in your tsconfig via the 'files' or 'include' property.`;
                callback(new Error(message));
            }
```

## 🌍 Your Environment

<pre><code>
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.5
Node: 14.16.0
Package Manager: npm 6.14.11
OS: linux x64

Angular: 12.2.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@angular/cli                    12.2.5
@schematics/angular             12.2.5
rxjs                            6.5.5
typescript                      4.3.5
webpack                         5.52.1
</code></pre>

**Comment by alan-agius4** [comment]
Thanks for opening the issue.

However,  Webpack specific features are not supported. Using Webpack specific features can break without a warning as Webpack is considered an implementation detail.

**Comment by Marshal27** [comment]
Hi Alan,

Thank you for the quick response. 

Should something like this be included in the list of breaking changes for Angular 12? 
 - Possibly it is documented and I missed it?
 - any help pointing me towards documentation on this piece would be much appreciated, to discuss internally with teams.
 - or any information to help understand why the change to angular 12 breaks this piece.
 
We would like to upgrade our main repo to v12 and later versions, but, this may be a blocker for us and pin us to only v11.

We use this feature heavily to manage what spec files run based on the `-c` passed into `ng test`

**Comment by Marshal27** [comment]
The CLI creates the `test.ts` file with the following via `ng new`

```
// And load the modules.
context.keys().map(context);
```

https://github.com/angular/angular-cli/blob/20fd33f6d4ce6cef1feb508a0221222e83a85630/packages/schematics/angular/application/files/src/test.ts.template#L27

**Comment by Marshal27** [comment]
To anyone who lands here experiencing the same issue, the problem was our use of `excludes` in the `tscofing` files... 
- The build process needs to resolve and build any modules found via `require.context('./', true, /\.spec\.ts$/);`
- If your `tsconfig` is set to excludes files found by this regex, it now throws the above exception prior to getting to the `keys().map`
