### ISSUE TITLE
@angular-devkit/build-angular@12.2.6 vulnerability dependence on chokidar/glob-parent

### ISSUE THREAD

**Issue by maxima120** [angular/angular-cli#21774]
`@angular-devkit/build-angular@12.2.6` has dependency on vulnerable version of `chokidar` because it depends on vulnerable version of `glob-parent` - see the picure.

I am waiting for this to be fixed since few months ago. Could you please change the dependency (my understanding is that it had been fixed a while ago in newer version of glob-parent).

![image](https://user-images.githubusercontent.com/10121753/133926702-fa298e95-7c73-4f94-985d-54482b1484a3.png)

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/21214

**Comment by maxima120** [comment]
github search should have been better. I searched for chokidar before posting and got nothing. also the suggested tickets when i typed all the relevant words in the title didnt show anything useful..
