### ISSUE TITLE
ng run build with app shell fails with called with multiple tsconfigs since 12.2.5 update

### ISSUE THREAD

**Issue by gabynevada** [angular/angular-cli#21770]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [X] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.2.4

### Description

When running ng run my-app:app-shell:production the build fails after output of error:
```
Called with multiple tsconfigs.
```

```
(base) my-app % ng run my-app:app-shell:production
⠋ Generating server application bundles (phase: setup)...⠋ Generating browser application bundles (phase: setup)...Called with multiple tsconfigs.
⠼ Generating browser application bundles (phase: setup)...%                                                                                                                                 
```

## 🔥 Exception or Error

<pre><code>
Called with multiple tsconfigs.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.6
Node: 14.17.6
Package Manager: npm 7.21.1
OS: darwin x64

Angular: 12.2.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.6
@angular-devkit/build-angular   12.2.6
@angular-devkit/core            12.2.6
@angular-devkit/schematics      12.2.6
@schematics/angular             12.2.6
rxjs                            7.3.0
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
The `Called with multiple tsconfigs.` error appears to be originating from the third-party builder `@angular-builders/custom-webpack` (https://github.com/just-jeb/angular-builders/blob/4a0ebae064fb8059939cee0ae5b308ba9dcd4be8/packages/custom-webpack/src/utils.ts#L6).

The `@angular-builders/custom-webpack` package is not maintained or supported by the Angular team.  If the issue persists, please consider opening an issue with the project: https://github.com/just-jeb/angular-builders/issues
