### ISSUE TITLE
glob-parent vulnerability in new angular project

### ISSUE THREAD

**Issue by DTanmoy** [angular/angular-cli#21788]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

![gob-path](https://user-images.githubusercontent.com/26085298/134317321-ce89476c-82c9-4396-b2f3-b5b2b5176f11.png)

**Comment by alan-agius4** [comment]
Duplicate of #21214
