### ISSUE TITLE
Docker: [error] TypeError: Cannot read property 'Workspace' of undefined

### ISSUE THREAD

**Issue by hamzou247** [angular/angular-cli#21791]
Hello i have been experimenting this error when building on a docker image for quite some time now. I have also been trying different versions of angular dependencies around angular 12.

The error: 

[error] TypeError: Cannot read property 'Workspace' of undefined
    at Object.getWorkspace (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/utilities/config.js:66:57)
    at BuildCommand.validateScope (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/models/command.js:97:67)
    at BuildCommand.validateAndRun (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/models/command.js:122:24)
    at Object.runCommand (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/models/command-runner.js:201:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

# 🐞 Bug report

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

It seems to work with version 9

### Description

The error happens when building on a docker image with a bitbucket pipeline. It does work when building on a windows local machine with the command: ng build --configuration=production && ng run safesante-ysera-front:server --configuration=production && npm run pack

## 🔬 Minimal Reproduction

ng build --configuration=production && ng run safesante-ysera-front:server --configuration=production && npm run pack

with the following configuration:

{
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "safesante-ysera-front": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
    
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/safesante-ysera-front",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }
            ],
            "styles": [
              "node_modules/font-awesome/css/font-awesome.min.css",
              "node_modules/@fortawesome/fontawesome-free/css/all.min.css",
              "node_modules/font-awesome-animation/dist/font-awesome-animation.css",
              "node_modules/font-awesome-animation/dist/font-awesome-animation.min.css",
              "node_modules/weather-icons/css/weather-icons.min.css",
              "design/css/fullcalendar-vendor.min.css",
              "node_modules/bootstrap/dist/css/bootstrap.min.css",
              "node_modules/angular2-multiselect-dropdown/themes/default.theme.css",
              "src/material-icons-font-face.scss",
              "src/ysera-styles-caro.css",
              "src/ysera-styles-faycal.css",
              "src/ysera-styles-max.css",
              "src/styles.scss"
            ],
            "scripts": [
              "./node_modules/jquery/dist/jquery.min.js",
              "./node_modules/bootstrap/dist/js/bootstrap.min.js",
              "./node_modules/detectrtc/DetectRTC.js",
              "src/assets/picture-in-picture.js",
              "src/assets/lib-jitsi-meet/lib-jitsi-meet.min.js",
              "./node_modules/fast-levenshtein/levenshtein.js",
              "node_modules/@fortawesome/fontawesome-free/js/all.min.js"
            ],
            "vendorChunk": true,
            "extractLicenses": false,
            "buildOptimizer": false,
            "aot": true,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true
          },
          "configurations": {
            "production": {
              "budgets": [],
              "index": {
                "input": "src/index.production.html",
                "output": "index.html"
              },
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "assets": [
                "src/favicon.ico",
                "src/assets",
                {
                  "glob": "**/*",
                  "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                  "output": "/assets/"
                },
                {
                  "glob": "Procfile",
                  "input": "src/",
                  "output": "./"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "aot": true,
              "buildOptimizer": true
            },
            "development": {
              "budgets": []
            },
            "remote": {
              "budgets": [],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.remote.ts"
                }
              ]
            }
          },
          "defaultConfiguration": ""
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "safesante-ysera-front:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "safesante-ysera-front:build:production",
              "proxyConfig": "proxy-production.config.json"

            },
            "development": {
              "browserTarget": "safesante-ysera-front:build:development",
              "proxyConfig": "proxy-development.config.json"
            },
            "remote": {
              "browserTarget": "safesante-ysera-front:build:remote",
              "proxyConfig": "proxy-remote.config.json"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "safesante-ysera-front:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.css"
            ],
            "scripts": [],
            "assets": [
              "favicon.png",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/locale",
                "output": "/assets/locale/"
              }
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/safesante-ysera-server",
            "main": "server.ts",
            "tsConfig": "src/tsconfig.server.json",
            "sourceMap": true,
            "optimization": false
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          },
          "assets": [
            {
              "input": "src/Procfile",
              "output": "./"
            }
          ],
          "defaultConfiguration": ""
        },
        "serve-ssr": {
          "builder": "@nguniversal/builders:ssr-dev-server",
          "options": {
            "browserTarget": "safesante-ysera-front:build",
            "serverTarget": "safesante-ysera-front:server"
            
          },
          "configurations": {
            "production": {
              "browserTarget": "safesante-ysera-front:build:production",
              "serverTarget": "safesante-ysera-front:server:production",
              "proxyConfig": "proxy-production.config.json"
            }
          }
        },
        "prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "browserTarget": "safesante-ysera-front:build:production",
            "serverTarget": "safesante-ysera-front:server:production",
            "routes": [
              "/"
            ]
          },
          "configurations": {
            "production": {}
          }
        }
      }
    },
    "safesante-ysera-front-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "safesante-ysera-front:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "safesante-ysera-front",
  "cli": {
    "analytics": false
  }
}

## 🔥 Exception or Error

> ng build --configuration=production && ng run safesante-ysera-front:server --configuration=production && npm run pack
An unhandled exception occurred: Cannot read property 'Workspace' of undefined
See "/tmp/ng-og2cCy/angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! safesante-ysera-front@0.0.9 build:ssr: `ng build --configuration=production && ng run safesante-ysera-front:server --configuration=production && npm run pack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the safesante-ysera-front@0.0.9 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output abov
</code></pre>

and:

+ cat /tmp/*/angular-errors.log
[error] TypeError: Cannot read property 'Workspace' of undefined
    at Object.getWorkspace (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/utilities/config.js:66:57)
    at BuildCommand.validateScope (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/models/command.js:97:67)
    at BuildCommand.validateAndRun (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/models/command.js:122:24)
    at Object.runCommand (/opt/atlassian/pipelines/agent/build/node_modules/@angular/cli/models/command-runner.js:201:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

## 🌍 Your Environment

Docker image: teracy/angular-cli

**Comment by clydin** [comment]
This type of error is generally caused by a mismatch of dependencies within the project.

Can you please provide the output of `ng version` as well as the output of `npm ls @angular-devkit/core`?

**Comment by hamzou247** [comment]
Thanks for considering the issue. here are the outputs:

 ng version:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.0.5
Node: 12.19.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.2.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.11
@angular-devkit/build-angular              12.2.6
@angular-devkit/core                       9.1.11
@angular-devkit/schematics                 9.1.11
@angular/cli                               12.0.5
@angular/flex-layout                       12.0.0-beta.34
@angular/http                              7.2.16
@nguniversal/builders                      9.1.1
@nguniversal/express-engine                9.1.1
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        9.1.11
rxjs                                       6.6.7
typescript                                 4.3.5
webpack                                    5.51.1




npm ls @angular-devkit/core:

safesante-ysera-front@0.0.9 C:\projects\safe-sante\ysera-front
+-- @angular-devkit/build-angular@12.2.6
| +-- @angular-devkit/architect@0.1202.6
| | `-- @angular-devkit/core@12.2.6  deduped
| +-- @angular-devkit/build-webpack@0.1202.6
| | `-- @angular-devkit/architect@0.1202.6
| |   `-- @angular-devkit/core@12.2.6
| `-- @angular-devkit/core@12.2.6
+-- @angular/cli@12.0.5 invalid
| `-- @angular-devkit/core@12.0.5  extraneous
+-- @nguniversal/builders@9.1.1
| +-- @angular-devkit/architect@0.901.11
| | `-- @angular-devkit/core@9.1.11  deduped
| `-- @angular-devkit/core@9.1.11
`-- @schematics/angular@9.1.11
  +-- @angular-devkit/core@9.1.11  deduped
  `-- @angular-devkit/schematics@9.1.11
    `-- @angular-devkit/core@9.1.11  deduped

npm ERR! invalid: @angular/cli@12.0.5 C:\projects\safe-sante\ysera-front\node_modules\@angular\cli
npm ERR! extraneous: @angular-devkit/core@12.0.5 C:\projects\safe-sante\ysera-front\node_modules\@angular\cli\node_modules\@angular-devkit\core


I can see there is an error. Is it causing the issue? How to solve it?

**Comment by hamzou247** [comment]
I have tried to downgrade to version 12.0.0 of angular/cli in order to resolve the issue

**Comment by clydin** [comment]
From the output, it appears that a version mismatch is indeed the issue.  `@schematics/angular` is included automatically by `@angular/cli` and most likely shouldn't be a direct dependency of the project.  `@nguniversal/builders` is also on version 9.x which will most likely be problematic with a 12.x CLI.  Updating that package would be recommended as well.
After adjusting those packages, deleting the package lock file and reinstalling may also be useful in these type of situations.
If issues are still occurring, please also attach the `dependency` and `devDependency` sections of the project's `package.json`.

**Comment by alan-agius4** [comment]
Note to update universal placates please use the below command.

```
ng update @nguniversal/express-engine
```

**Comment by hamzou247** [comment]
Many thanks, after taking into account the above remarks, the pipeline is now working. You are awesome guys

**Comment by clydin** [comment]
Glad you were able to get everything working.
