### ISSUE TITLE
ng install - don't work

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#218]
```shell
$ ng install ng2-cli-test-lib
version: 1.13.13
Installed packages for tooling via npm.
installing ng2
The `ember generate <entity-name>` command requires an entity name to be specifi
ed. For more details, use `ember help`.
```

How can I fix it?

**Comment by filipesilva** [comment]
That is due to us not doing a release in a while. 

You will have to use the instructions [here](https://github.com/angular/angular-cli#working-with-master) to work with the latest master version.

**Comment by filipesilva** [comment]
(I'm closing because I'm preeetty sure my answer will solve it, but please reopen if it doesn't)

**Comment by NathanWalker** [comment]
@filipesilva Sounds like `ng install` will be 'ripped out and not used':
https://github.com/angular/angular-cli/issues/236
Just curious the new direction you guys are thinking?

**Comment by Brocco** [comment]
@NathanWalker you are correct. The goals are to increase the robustness and usefulness, so we're taking it back to the drawing board to assure it satisfies key scenarios.

**Comment by NathanWalker** [comment]
:+1: awesome thanks!

**Comment by NathanWalker** [comment]
@robwormald made a good point early on to not become another package manager and I completely agree. I think as long as it stays out of the way of `managing` dependencies and instead just offers the nice conveniences of rapid development when working with many libs would be excellent.

**Comment by filipesilva** [comment]
I don't have a lot of insight on it right now, @hansl is the one working on it.
