### ISSUE TITLE
Upgrading from angular 11 to 12

### ISSUE THREAD

**Issue by kuljit3188** [angular/angular-cli#21806]
I'm trying  upgrade to angular 12 and i when run the "ng update @angular/core@12 @angular/cli@12", i get the following error:
Package specified by '@angular/core@12' does not exist within the registry.

Running "ng version" shows the following:
![image](https://user-images.githubusercontent.com/91268121/134517824-b33f6a51-bd2f-435f-85bc-12cb172e4ca6.png)

**Comment by alan-agius4** [comment]
I am unable to replicate this using the public NPM registry. If you are using a private NPM registry make sure that it is not stalled.
