### ISSUE TITLE
FATAL ERROR: v8::FromJust Maybe value is Nothing.

### ISSUE THREAD

**Issue by wupaz** [angular/angular-cli#21800]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

Since last verison 12.2.7 it seem our build didn't work, 

### Please provide the exception or error you saw

```true
Starting: Run node Build Fusion AOT copy
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --aot --localize
Option "--prod" is deprecated: Use "--configuration production" instead.
- Generating browser application bundles (phase: setup)...
Compiling @angular/core : es2015 as esm2015
...
Compiling ngx-image-cropper : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/material-moment-adapter : es2015 as esm2015
FATAL ERROR: v8::FromJust Maybe value is Nothing.
 1: 00007FF7534D4C9F napi_wrap+111007
 2: 00007FF753478226 v8::base::CPU::has_sse+59910
 3: 00007FF753479126 node::OnFatalError+294
 4: 00007FF753D37C85 v8::V8::FromJustIsNothing+53
 5: 00007FF75339FECA v8::internal::Isolate::isolate_root_bias+15114
 6: 00007FF75339FD6D v8::internal::Isolate::isolate_root_bias+14765
 7: 00007FF75339A3F0 v8::internal::HashTable<v8::internal::CompilationCacheTable,v8::internal::CompilationCacheShape>::HashTable<v8::internal::CompilationCacheTable,v8::internal::CompilationCacheShape>+42448
 8: 00007FF753527092 uv_pipe_pending_type+4242
 9: 00007FF753531B20 uv_loop_init+1024
10: 00007FF753531DCA uv_run+202
11: 00007FF7533BAECD v8::internal::wasm::SignatureMap::Freeze+35341
12: 00007FF7533B69A8 v8::internal::wasm::SignatureMap::Freeze+17640
13: 00007FF7535225BD uv_poll_stop+557
14: 00007FF7542CFA30 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+146176
15: 00007FF892627974 BaseThreadInitThunk+20
16: 00007FF892A2A2F1 RtlUserThreadStart+33
##[error]Process completed with exit code 134.
Finishing: Run node Build Fusion AOT copy
```

### Please provide the environment you discovered this bug in

```true
OS Windows Devops MS Host 
node 14.17.6 x64
Angular 12.2.7
npm 6.14.15
```

**Comment by JoostK** [comment]
Transferring to the CLI repo as I suspect this is related to esbuild-wasm, according to the stack. However, I'm afraid that without a reproduction this is otherwise unactionable for us at the moment.

**Comment by alan-agius4** [comment]
This does indeed seem related to esbuild wasn’t. However, without a reproduction it’s hard to tell what’s the problem.

**Comment by clydin** [comment]
Can you provide the version output from what was being used prior to the issue occurring?

**Comment by wupaz** [comment]
Output with version 12.2.5

Starting: Run node Build Fusion AOT copy
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --prod --aot --localize
Option "--prod" is deprecated: Use "--configuration production" instead.
- Generating browser application bundles (phase: setup)...
Compiling @angular/core : es2015 as esm2015
Compiling @angular/cdk/keycodes : es2015 as esm2015
Compiling @angular/animations : es2015 as esm2015
Compiling @angular/cdk/observers : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/animations/browser : es2015 as esm2015
Compiling @angular/cdk/platform : es2015 as esm2015
Compiling @angular/cdk/bidi : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/cdk/a11y : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/cdk/collections : es2015 as esm2015
Compiling @angular/platform-browser/animations : es2015 as esm2015
Compiling @angular/cdk/scrolling : es2015 as esm2015
Compiling @angular/cdk/portal : es2015 as esm2015
Compiling @angular/cdk/layout : es2015 as esm2015
Compiling @angular/material/core : es2015 as esm2015
Compiling @angular/cdk/overlay : es2015 as esm2015
Compiling @angular/common/http : es2015 as esm2015
Compiling @angular/cdk/text-field : es2015 as esm2015
Compiling @ng-idle/core : es2015 as esm2015
Compiling angular-draggable-droppable : es2015 as esm2015
Compiling @angular/material/form-field : es2015 as esm2015
Compiling @angular/material/button : es2015 as esm2015
Compiling @angular/material/tooltip : es2015 as esm2015
Compiling @angular/material/select : es2015 as esm2015
Compiling @angular/material/icon : es2015 as esm2015
Compiling angular-resizable-element : es2015 as esm2015
Compiling @angular/material/input : es2015 as esm2015
Compiling @angular/cdk/accordion : es2015 as esm2015
Compiling @angular/material/divider : es2015 as esm2015
Compiling @angular/cdk/stepper : es2015 as esm2015
Compiling @angular/cdk/table : es2015 as esm2015
Compiling @angular/material/paginator : es2015 as esm2015
Compiling @angular/material/sort : es2015 as esm2015
Compiling @angular/cdk/tree : es2015 as esm2015
Compiling @angular/material/checkbox : es2015 as esm2015
Compiling @angular/material/progress-spinner : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling @angular/router : es2015 as esm2015
Compiling @ng-idle/keepalive : es2015 as esm2015
Compiling angular-calendar : es2015 as esm2015
Compiling ngx-virtual-scroller : es2015 as esm2015
Compiling ngx-infinite-scroll : es2015 as esm2015
Compiling ngx-quill : es2015 as esm2015
Compiling @angular/material/menu : es2015 as esm2015
Compiling @angular/material/card : es2015 as esm2015
Compiling @angular/material/tabs : es2015 as esm2015
Compiling @angular/material/autocomplete : es2015 as esm2015
Compiling @angular/material/badge : es2015 as esm2015
Compiling @angular/material/bottom-sheet : es2015 as esm2015
Compiling @angular/material/button-toggle : es2015 as esm2015
Compiling @angular/material/chips : es2015 as esm2015
Compiling @angular/material/datepicker : es2015 as esm2015
Compiling @angular/material/dialog : es2015 as esm2015
Compiling @angular/material/expansion : es2015 as esm2015
Compiling @angular/material/grid-list : es2015 as esm2015
Compiling @angular/material/list : es2015 as esm2015
Compiling @angular/material/progress-bar : es2015 as esm2015
Compiling @angular/material/radio : es2015 as esm2015
Compiling @angular/material/sidenav : es2015 as esm2015
Compiling @angular/material/slide-toggle : es2015 as esm2015
Compiling @angular/material/slider : es2015 as esm2015
Compiling @angular/material/snack-bar : es2015 as esm2015
Compiling @angular/material/stepper : es2015 as esm2015
Compiling @angular/material/table : es2015 as esm2015
Compiling @angular/material/toolbar : es2015 as esm2015
Compiling @angular/material/tree : es2015 as esm2015
Compiling ngx-mat-select-search : es2015 as esm2015
Compiling ngx-toastr : es2015 as esm2015
Compiling ngx-image-cropper : es2015 as esm2015
Compiling @angular/cdk/drag-drop : es2015 as esm2015
Compiling @angular/material-moment-adapter : es2015 as esm2015
√ Browser application bundle generation complete.
√ Browser application bundle generation complete.
- Generating localized bundles...
√ Localized bundle generation complete.
- Copying assets...
√ Copying assets complete.
- Generating index html...
√ Index html generation complete.

Initial Chunk Files               | Names         |      Size
main.93475edc636e352a8a34.js      | main          |   4.80 MB
polyfills.9d94f4968ec080ecfb7f.js | polyfills     |   1.02 MB
styles.796faa8979af79bb433c.css   | styles        | 255.63 kB
runtime.2137b91cdd2139c6c3d1.js   | runtime       |   3.20 kB

| Initial Total |   6.08 MB

Lazy Chunk Files                  | Names         |      Size
161.7562832e0ab94f607bb6.js       | -             | 209.13 kB

Build at: 2021-09-22T23:32:32.905Z - Hash: b1021b8b8a16bac64aef - Time: 287267ms

**Comment by wupaz** [comment]
Nope

**Comment by wupaz** [comment]
I dont' know if I solve my issue or it's an another package, but I fix some scss ">>>" warning and now all work fine
