### ISSUE TITLE
JUnit xml format incorrect - update to correct/latests

### ISSUE THREAD

**Issue by SamanthaAdrichem** [angular/angular-cli#21802]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [x] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I don't know if it's already fixed in there, I've been searching the repo but can't even find anything related to JUnit.
The format of JUnit is incorrect/outdated. We're on CLI 10.2.0 (can't upgrade a.t.m. due to hybrid AngularJs issues)

For it to work in bitbucket pipelines it apparently needs the failures attributes (at least I think).

For example the following linting error does not match the XSD of JUnit
```
<?xml version="1.0" encoding="utf-8"?>
<testsuites package="tslint">
    <testsuite name="/opt/atlassian/pipelines/agent/build/src/app/app.module.ts">
        <testcase name="ordered-imports" classname="/opt/atlassian/pipelines/agent/build/src/app/app.module.ts">
            <failure type="error">Import sources within a group must be alphabetized. Line 65, Column 1</failure>
        </testcase>
    </testsuite>
</testsuites>
```

XSD: https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd
I tested it here: https://www.freeformatter.com/xml-validator-xsd.html

And it gives errors like
```
Cvc-complex-type.3.2.2: Attribute 'package' Is Not Allowed To Appear In Element 'testsuites'., Line '1', Column '30'.
Cvc-complex-type.4: Attribute 'package' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.4: Attribute 'id' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.4: Attribute 'timestamp' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.4: Attribute 'hostname' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.4: Attribute 'tests' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.4: Attribute 'failures' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.4: Attribute 'errors' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.4: Attribute 'time' Must Appear On Element 'testsuite'., Line '2', Column '82'.
Cvc-complex-type.2.4.a: Invalid Content Was Found Starting With Element 'testcase'. One Of '{properties}' Is Expected., Line '3', Column '113'.
Cvc-complex-type.4: Attribute 'time' Must Appear On Element 'testcase'., Line '3', Column '113'.
```

And it doesn't show up in pipelines
While the one from phpcs does work
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="PHP_CodeSniffer 3.6.0" errors="0" tests="2" failures="2">
    <testsuite name="/home/samantha/vhosts/finance.daisycon.com/src/Advertiser/Invoice.php" errors="0" tests="2" failures="2">
        <testcase name="PSR2R.Namespaces.UseInAlphabeticalOrder.Order at /home/samantha/vhosts/finance.daisycon.com/src/Advertiser/Invoice.php (10:1)">
            <failure type="error" message="Use classes must be in alphabetical order."/>
        </testcase>
    </testsuite>
</testsuites>
```

As you can see the big difference between the two is package vs name, and the errors / tests / failures counts

### Describe the solution you'd like

 
If it's already there, what version I would need at a minimum
If it's not there, where the code is located so I can create a PR for you guys, or a solution to match up with the latest junit xml format.

### Describe alternatives you've considered

 
I've contacted bitbucket to see for a solution. If there won't be a solution i'll write my own parser which will convert it.

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. 

The JUnit reports are generated by Tslint however is past it's end of life and is no longer supported. 

Therefor, I suggest you update to the latest version of the Angular CLI and migrate to Eslint.

For more information kindly see https://github.com/palantir/tslint/issues/4534 and https://github.com/angular-eslint/angular-eslint

**Comment by SamanthaAdrichem** [comment]
Hmz, thnx for the update, but it's not that easy either, for starters the new one does not support --files ...

I'll look into this further some day.. not now i'll just write my own fix because eslint is far from where it should be.
