### ISSUE TITLE
--localize and --deploy-url

### ISSUE THREAD

**Issue by bgardner-noggin** [angular/angular-cli#21823]
# 🚀 Feature request

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I would like the ability to invoke build once for multiple languages with both the --localize and --deploy-url options. I can see from https://github.com/angular/angular-cli/issues/17737#issuecomment-634023656 that this is not supported however as best as I can tell there is no alternative CDN solution here.

We have a large angular application that receives frequent updates. Each time an update is pushed through, a new version is generated. Our CDN retrieves a request for the root of the site eg https://example.com and determines which language the client is using and returns the correct index.html for that language. The contents of that index.html refers to all assets via a version and language specific path eg /assets/v1.234.5-es/img.png

Previously we were using --deploy-url to build per language which was working as above, but this was against an older version of angular that did not support the --localize option. Additionally, as more languages are being added, this solution does not scale.

There are no CDN options as best as I can tell that support

- Common urls for the application, eg using baseHref we end up with https://example.com/v1.234.5-es/section-a instead of https://example.com/section-a - breaking links and confusing users
- Minimising requests against the CDN for the same language / version
- New versions of the application coming through immediately without combining partials from old and new versions - chrome ignores cache headers when retrieving multiple assets from the same domain, it will retrieve the first couple, see 304's and then return the rest from cache.

**Comment by alan-agius4** [comment]
Hi @bgardner-noggin,

The `deployUrl` option is deprecated and will be removed in future.

This option was previously introduced to handle application that only assets are hosted on a CDN. This setup is now mostly considered as legacy as it is recommended that the entire application is hosted on a CDN. 

The problem in your case appears that while you are configuring `baseHref`, [`APP_BASE_HREF`](https://angular.io/api/common/APP_BASE_HREF) is not being configured. 

```bash
ng build ---base-href /v1.234.5-es/
```

```ts
providers: [{provide: APP_BASE_HREF, useValue: '/' }]
```

**Comment by bgardner-noggin** [comment]
From the docs

"If you're using PathLocationStrategy, you must provide a APP_BASE_HREF **_or_** add a <base href> element to the document." (emphasis mine)

It doesn't explicitly state that they are exclusive, but neither does it state that they can be used together.

I took the _or_ in the docs to mean that you used one or the other.

Thanks for the info.

**Comment by bgardner-noggin** [comment]
Also, the --deploy-url is not marked as deprecated in the docs, would have been helpful to know that we should no longer be using this option.

Thanks.

**Comment by clydin** [comment]
The deploy URL option is targeted to be deprecated in the upcoming v13 release but is not considered deprecated in v12 (the latest stable release).

**Comment by bgardner-noggin** [comment]
Using the APP_BASE_HREF in the app.module.ts and baseHref for the locales works. Closing this issue.

Thanks.
