### ISSUE TITLE
Switching to webpack but there is stil the system.config.ts...

### ISSUE THREAD

**Issue by bastienJS** [angular/angular-cli#2182]
"We changed the build system between beta.10 and beta.12, from SystemJS to Webpack."

I use the beta14 and created an application.

There is a file system-config.ts and I asked myself why is that file still there is you switched to Webpack?

Is this file still needed with webpack now?

**Comment by bonnici** [comment]
It's not needed, see upgrade instructions:

> 5. Delete files that are not needed anymore.

> rm src/system-config.ts
> rm src/typings.d.ts

**Comment by bastienJS** [comment]
@bonnici But why are these files not deleted in the latest download? I mean since when does the customer has to cleanup the product of the supplier?

That makes no sense to me.

Customers using the first time angular 2 cli have to delete files that the structure makes sense?

**Comment by bonnici** [comment]
That's just the price you have to pay when you use a beta I'm afraid. Also
they don't know what you might have done with that file so they don't just
want to delete it automatically.

**Comment by bastienJS** [comment]
Yes I was a bit pissed from the beta router/forms changes 5 times all together... Then I even did not correctly read "rm src/system-config.ts" I read tsconfig.json. For this I apologize to the developers!
