### ISSUE TITLE
CLI Version clarification.

### ISSUE THREAD

**Issue by sathishjayapal** [angular/angular-cli#21839]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Docs or angular.io issues at: https://github.com/angular/angular/issues/new/choose

For the time being, we keep Angular AIO issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
I have a global CLI installed in my machine, that is at version 8.1.x. But I got a project from another team where they are in Angular 11 version. But when I run npm install, and ng build/serve. I get the application working in localhost:4200. My clarification that am hoping in the documentation is, should I be worried that my angular CLI that is installed globally is not in sync with the project am compiling and running. How is the CLI able to run., thanks for helping out. I apologize if this is the not the right forum to ask this question and raise it as a documentation issue.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
