### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module in other installed dependencies

### ISSUE THREAD

**Issue by pieralukasz** [angular/angular-cli#21840]
# 🐞 Bug report

### Command 

- [x] npm install -g @angular-devkit/schematics-cli
- [x] schematics blank --name=my-component
- [x] npm install read-pkg-up (example package)
- [x] npm run build
- [x] schematics .:my-component

### Description

Hi! The problem appears in my own schematics when I want to download an external npm package. It doesn't just happen with certain packages. If I call a function from this package inside my schematics I get an error presented below. I normally work on a larger project where this error occurred. For the purposes of the issue, I created a completely new one to see if by any chance the error does not exist in my project. The idea to work around this was to write my own middleware, but I guess it misses the point.

This does not only happen with the read-pkg-up package, problems occurred in various e.g.:
- find-up,
- locate-path,
- path-exists

but e.g. there was no problem with using the express package.

<pre><code>
import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';
import { readPackageUpSync } from "read-pkg-up";

// You don't have to export the function as default. You can also have more than one rule factory
// per file.
export function myComponent(_options: any): Rule {
  return (tree: Tree, _context: SchematicContext) => {

    console.log(readPackageUpSync())
    return tree;
  };
}
</code></pre>

## 🔥 Exception or Error

<pre><code>
An error occured:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ~/Schematics/my-component/node_modules/read-pkg-up/index.js
require() of ES modules is not supported.
require() of ~/Schematics/my-component/node_modules/read-pkg-up/index.js from ~/Schematics/my-component/src/my-component/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename ~/Schematics/my-component/node_modules/read-pkg-up/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ~/Schematics/my-component/node_modules/read-pkg-up/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (~/Schematics/my-component/src/my-component/index.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
</code></pre>

## 🌍 Environment

<pre><code>
Angular CLI: 12.2.7
Node: 14.18.0
Package Manager: npm 6.14.15
OS: darwin x64

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.7 (cli-only)
@angular-devkit/core         12.2.7
@angular-devkit/schematics   12.2.7
@schematics/angular          12.2.7 (cli-only)
typescript                   4.3.5

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
What is happening here is the mentioned modules are in ESM format. But schematics at the moment only support CommonJS format.

A workaround would be to load these modules using a dynamic imports the problem here is that TypeScript will downlevel these to `require`. Therefore, you will need to create a helper method. 

```ts
import { Rule, SchematicContext, Tree } from '@angular-devkit/schematics';

export function myComponent(_options: any): Rule {
  return async (tree: Tree, _context: SchematicContext) => {
    const { readPackageUpSync } =
      (await loadEsmModule<typeof import('read-pkg-up')('read-pkg-up');

    console.log(readPackageUpSync());
  };
}

async function loadEsmModule<T>(modulePath: string): Promise<T> {
  return (await new Function('modulePath', `return import(modulePath);`)(modulePath)) as T;
}
```

**Comment by pieralukasz** [comment]
Thanks! It is working :)
