### ISSUE TITLE
ng serve command execution is slow.

### ISSUE THREAD

**Issue by vzan2012** [angular/angular-cli#21846]
Hello,

When I create a new app, the **_ng serve_** command executes and the application runs very quick.

But after adding one to two components, when I execute the **_ng serve_** command,
After few minutes, it starts to build the application. 

The execution process is very slow.

Is there any solution to speed up the process and I have followed lot of help documents,
executing the command like

_**ng serve --sourceMap=false**_

But still the issue exists.

I'm using **Windows** Operating System

Thank you

Please file any Angular CLI issues at: https://github.com/angular/angular-cli/issues/new

For the time being, we keep Angular CLI issues in a separate repository.

**Comment by alan-agius4** [comment]
Closing due to the lack of information.

**Comment by vzan2012** [comment]
Hello @alan-agius4,

Sorry for the late reply.

Here are the screenshots of my app..

(1) When I try to execute the app using **_ng serve_**
![image](https://user-images.githubusercontent.com/13725828/139646733-fcb2236d-27cc-473c-a064-afca960814b6.png)

(2) My angular version used in my system.
![image](https://user-images.githubusercontent.com/13725828/139646694-18f0c967-ab64-45ce-be78-d9ca00414b40.png)

**Comment by JoostK** [comment]
What hardware is that run on? Is it truly a 32-bit Windows installation, or is your NodeJS installation 32-bit?

**Comment by vzan2012** [comment]
Hello @JoostK ,

It is NodeJS installation 32-bit..

**Comment by JoostK** [comment]
Can you use a 64-bit NodeJS?

**Comment by vzan2012** [comment]
Hello @JoostK ,

Now I have installed the 64-bit NodeJS and now I see a big difference in the time consumption.

![image](https://user-images.githubusercontent.com/13725828/139652896-2f23a60c-f564-46c5-b925-fbb9b5a1be7c.png)

![image](https://user-images.githubusercontent.com/13725828/139652959-01be23a3-1f92-4874-b091-d1a83d05967e.png)
