### ISSUE TITLE
Angular - prismacloud raising an vulnerability due to SET-VALUE and GLOB_PARENT dependency on old version

### ISSUE THREAD

**Issue by cirotheodoro** [angular/angular-cli#21844]
We are currently using Angular 12.2.7 in our application, however, we use prismacloud to scan our containers to find vulnerabilities.

Prismacloud is complaining that we are using an indirect reference to SET-VALUE package 2.0.1 and GLOB_PARENT 3.1.0, however, we should be referencing SET-VALUE as 4.0.1 and GLOB_PARENT as 5.1.2.

It seems Angular is referencing the old versions yet. Any plans to upgrade it? Or any directions?

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/21214

Webpack-dev-server has been updating to version 4 in Angular CLI version 13, which is currently in prerelease. Unfortunately we cannot backport the fix due the breaking nature of the change.
