### ISSUE TITLE
Build error in GitLab pipeline for building angular lib after update to angular 12

### ISSUE THREAD

**Issue by patel-jeel92** [angular/angular-cli#21859]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

After updating to angular 12, Building an angular library project in the build pipeline fails. The build on when running locally works fine and has no issues.

### Directory Structure
```
project
│   tsconfig.app.json
│   tsconfig.json
│
└───projects
│   │   lib-1
│  
│   
└───src
    │   my-app

```
### lib-1 (tsconfig.lib.json) 
```
{
	"extends": "../../tsconfig.json",
	"compilerOptions": {
		"outDir": "../../out-tsc/lib",
		"target": "es2015",
		"declaration": true,
		"declarationMap": true,
		"inlineSources": true,
		"types": [],
		"lib": ["dom", "es2018", "es2015"]
	},
	"angularCompilerOptions": {
		"skipTemplateCodegen": true,
		"strictMetadataEmit": true,
		"enableResourceInlining": true
	},
	"exclude": ["src/test.ts", "**/*.spec.ts"]
}
```
### lib-1 (tsconfig-lib.prod.json)
```
{
	"extends": "./tsconfig.lib.json",
	"compilerOptions": {
		"declarationMap": false
	},
	"angularCompilerOptions": {
		"compilationMode": "partial"
	}
}
```
### lib-1 (package.json)
```
{
	"name": "my-lib",
	"version": "0.0.1",
	"peerDependencies": {
		"@angular/common": "^12.2.8",
		"@angular/core": "^12.2.8"
	},
	"postinstall": "ngcc",
	"dependencies": {
		"tslib": "^2.0.0"
	}
}
```

### lib-1 (ng-package.json)
```
{
	"$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
	"dest": "../../dist/lib-1",
	"assets": [
		"./src/**/*.scss"
	],
	"lib": {
		"entryFile": "src/public-api.ts"
	}
}
```

### my-app (package.json)
```
{
	"name": "my-app",
	"version": "0.1.3",
	"scripts": {
		"build": "run-s build:lib && run-s build:app",
		"build:app": "ng build --configuration=production",
		"build:lib": "ng build --configuration=production"
	},
	"dependencies": {
		"@angular/animations": "~12.2.8",
		"@angular/common": "~12.2.8",
		"@angular/compiler": "~12.2.8",
		"@angular/core": "~12.2.8",
		"@angular/elements": "^12.2.8",
		"@angular/forms": "~12.2.8",
		"@angular/platform-browser": "~12.2.8",
		"@angular/platform-browser-dynamic": "~12.2.8",
		"@angular/router": "~12.2.8",
		"@types/lodash": "^4.14.173",
		"clear": "^0.1.0",
		"d3": "^5.16.0",
		"document-register-element": "^1.7.2",
		"jwt-decode": "^3.0.0",
		"lodash": "^4.17.21",
		"rxjs": "~6.6.3",
		"tslib": "^2.0.0",
		"xstate": "^4.16.2",
		"zone.js": "~0.11.4"
	},
	"devDependencies": {
		"@angular-builders/custom-webpack": "^12.1.3",
		"@angular-devkit/build-angular": "^12.2.7",
		"@angular-eslint/builder": "12.5.0",
		"@angular-eslint/eslint-plugin": "12.5.0",
		"@angular-eslint/eslint-plugin-template": "12.5.0",
		"@angular-eslint/schematics": "12.5.0",
		"@angular-eslint/template-parser": "12.5.0",
		"@angular/cli": "~12.2.7",
		"@angular/compiler-cli": "~12.2.8",
		"@cypress/schematic": "^1.5.0",
		"@types/jasmine": "~3.6.0",
		"@types/jasminewd2": "~2.0.3",
		"@types/node": "^12.20.19",
		"@typescript-eslint/eslint-plugin": "4.28.2",
		"@typescript-eslint/parser": "4.28.2",
		"@xstate/inspect": "^0.4.1",
		"@xstate/test": "^0.4.1",
		"concurrently": "^5.3.0",
		"cypress": "8.2.0",
		"eslint": "^7.26.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-prettier": "^4.0.0",
		"fs-extra": "^9.0.1",
		"husky": "^7.0.0",
		"jasmine-core": "~3.6.0",
		"jasmine-spec-reporter": "~5.0.0",
		"karma": "~6.3.4",
		"karma-chrome-launcher": "~3.1.0",
		"karma-coverage": "~2.0.3",
		"karma-coverage-istanbul-reporter": "^3.0.3",
		"karma-jasmine": "~4.0.0",
		"karma-jasmine-html-reporter": "^1.5.0",
		"markdownlint-cli": "^0.28.1",
		"ng-packagr": "^12.2.2",
		"node-sass": "^4.13.0",
		"npm-run-all": "^4.1.5",
		"prettier": "2.3.2",
		"pretty-quick": "^3.1.0",
		"protractor": "~7.0.0",
		"start-server-and-test": "^1.14.0",
		"ts-node": "~8.3.0",
		"typescript": "~4.3.5"
	}
}
```

## 🔥 Exception or Error

<pre><code>
> ng build my-lib --configuration=production
Building Angular Package
------------------------------------------------------------------------------
Building entry point 'my-lib'
------------------------------------------------------------------------------
- Compiling with Angular sources in Ivy partial compilation mode.
runtime: nameOff 0x76313262 out of range 0xd840 - 0x201ac5
fatal error: runtime: name offset out of range
goroutine 1 [running]:
runtime.throw({0x83a95, 0x21})
	/usr/local/go/src/runtime/panic.go:1198 +0x7 fp=0x476858 sp=0x476830 pc=0x12000007
runtime.resolveNameOff(0xe2d7, 0x76313262)
	/usr/local/go/src/runtime/type.go:195 +0x37 fp=0x4768c0 sp=0x476858 pc=0x134e0037
runtime.name.pkgPath({0xe2d7})
	/usr/local/go/src/runtime/type.go:511 +0x21 fp=0x4768e8 sp=0x4768c0 pc=0x13530021
runtime.(*itab).init(0xc37098)
	/usr/local/go/src/runtime/iface.go:212 +0x1d fp=0x4769a8 sp=0x4768e8 pc=0x107a001d
runtime.getitab(0x42b40, 0x4c9c0, 0x1)
	/usr/local/go/src/runtime/iface.go:75 +0x22 fp=0x4769f0 sp=0x4769a8 pc=0x10760022
runtime.assertI2I2(0x42b40, {0xe74b8, 0x46a210})
	/usr/local/go/src/runtime/iface.go:467 +0x5 fp=0x476a18 sp=0x4769f0 pc=0x10870005
math/rand.New(...)
	/usr/local/go/src/math/rand/rand.go:67
math/rand.init()
	/usr/local/go/src/math/rand/rand.go:293 +0xe fp=0x476a68 sp=0x476a18 pc=0x1682000e
runtime.doInit(0x2edca0)
	/usr/local/go/src/runtime/proc.go:6498 +0x1e fp=0x476bb0 sp=0x476a68 pc=0x12a9001e
runtime.doInit(0x2f20a0)
	/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x476cf8 sp=0x476bb0 pc=0x12a90009
runtime.doInit(0x2f0d20)
	/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x476e40 sp=0x476cf8 pc=0x12a90009
runtime.doInit(0x2f1900)
	/usr/local/go/src/runtime/proc.go:6475 +0x9 fp=0x476f88 sp=0x476e40 pc=0x12a90009
runtime.main()
	/usr/local/go/src/runtime/proc.go:238 +0x24 fp=0x476fe0 sp=0x476f88 pc=0x121f0024
runtime.goexit()
	/usr/local/go/src/runtime/asm_wasm.s:431 +0x1 fp=0x476fe8 sp=0x476fe0 pc=0x13d10001
✖ Compiling with Angular sources in Ivy partial compilation mode.

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.2.7
Node: 14.18.0
Package Manager: npm 6.14.15
OS: linux x64
Angular: 12.2.8
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.7
@angular-devkit/build-angular   12.2.7
@angular-devkit/core            12.2.7
@angular-devkit/schematics      12.2.7
@angular/cli                    12.2.7
@schematics/angular             12.2.7
ng-packagr                      12.2.2
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This looks like an issue with Esbuild / Golang.

Unfortunately, this is not actionable from our end.
