### ISSUE TITLE
CLI Not Uninstalling Even After Following Uninstallation Steps

### ISSUE THREAD

**Issue by darrenbrett** [angular/angular-cli#2186]
I'm running the angular-cli: 1.0.0-beta.10 on a Macbook on OS X El Capitan 10.11.6, and even after following the steps to uninstall the cli and clean cache before updating to the new version, it's not actually being removed from my system. How can I force this?

**Comment by hansl** [comment]
What's the result of `npm bin`?

**Comment by darrenbrett** [comment]
/Users/darrenking/node_modules/.bin

**Comment by hansl** [comment]
You have a rogue node_modules folder in your home directory. Possibly likely due to a mistake during an installation. Delete that node_modules folder and reinstall angular-cli; that will fix it. Cheers!
