### ISSUE TITLE
buildDefaultPath is looking for 'extensions' property in project configuration

### ISSUE THREAD

**Issue by Teebo** [angular/angular-cli#21870]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc
Config
### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
version 9, 10
### Description
I am working with schematics, I have imported the function buildDefaultPath from `'@schematics/angular/utility/workspace';`
I am passing in a project object to the function, however I am getting the error.

`TypeError: Cannot read property 'projectType' of undefined`

I have then assigned my project object a property like  `project.extensions = project`. This circumvent the error.
I am wondering what and where the extension property should be coming from. the definition of the function is like below.

```
function buildDefaultPath(project) {
    const root = project.sourceRoot ? `/${project.sourceRoot}/` : `/${project.root}/src/`;
    const projectDirName = project.extensions['projectType'] === workspace_models_1.ProjectType.Application ? 'app' : 'lib';
    return `${root}${projectDirName}`;
}
```

This exists in `"@schematics/angular": "^12.2.8",`

Or am I lacking understanding of the workspace configurations of Angular projects?
Mainly what is the extensions property for?
 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
 Pass in a project configuration object to the the function.
 
```
const project = workspaceConfig.projects[projectName];
...
buildDefaultPath(project);
```

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @Teebo,

Anything which is not exported from `@schematics/angular` is considered as private API and it's usage is not supported outside of this package.

`extensions` is not an actual property in the workspace configuration, but it's a property in `ProjectDefinition` which is populated when the workspace is read using the [Workspace API](https://angular.io/guide/schematics-for-libraries#get-the-project-configuration). `extensions` contains the project options. https://github.com/angular/angular-cli/blob/4be6537ddf4b32e8d204dbaa75f1a53712fe9d44/packages/angular_devkit/core/src/workspace/definitions.ts#L17-L24

**Comment by Teebo** [comment]
@alan-agius4 OK I see, thanks a lot for the clarification
