### ISSUE TITLE
add support for webpack preload

### ISSUE THREAD

**Issue by abdulkareemnalband** [angular/angular-cli#21874]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

We have a analytics script which is fairly large and need to be initialized early during application is booting.
Script does not change too much , so if we dynamically import it, resulting chunk file has `stable hash` in it, and that hash rarely changes. 
Same Chunk file can be cached by browser, and used across different versions of our app.

Also we want to preload that analytics file, and webpack provides means for it. [see here](https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules)

But when we import it like this
```ts
async function initializeAnalytics() {
   const analyticsModule = await import(/* webpackPreload: true */  'analytics.js');
  analyticsModule.init();
}
```

I expected that following will be added to index.html
```
<link rel="preload" href="{link-to-analytics-chunk}" as="script">
```

It did not

### Describe the solution you'd like

Angular cli should honor webpack comments regarding chunking.

### Describe alternatives you've considered
none

**Comment by alan-agius4** [comment]
Thanks for this feature request. 

Webpack specific features are not supported by design.

 The fact that the Angular CLI users webpack is an implementation detail which can change in the future without warning.
