### ISSUE TITLE
@angular-devkit/build-angular upgrade causes material styles not to be loaded

### ISSUE THREAD

**Issue by rvanheest** [angular/angular-cli#21893]
### Description

I'm in the proces of upgrading a project from Angular 11 to Angular 12. Doing that I've noticed that the Material styles used in this project are not loaded or rendered anymore. By proces of elimination I found that the upgrade of `@angular-devkit/build-angular` is the cause of this problem. In particular between `12.1.x` and `12.2.x`; to be even more precise: between `12.2.0-next.0` and `12.2.0-next.2` (their was no release of `12.2.0-next.1`???).

An example of this problem:
Using `12.2.0-next.0` and earlier, I get a nicely rendered button like 
![image](https://user-images.githubusercontent.com/5938204/136358689-52b5db37-479a-454a-895f-214401b647cb.png)

Using `12.2.0-next.2` and higher I get 
![image](https://user-images.githubusercontent.com/5938204/136358588-807bff48-6d82-42dd-8b74-d6afc309ffdf.png)

What I noticed is that all CSS from the `@angular/material` package is missing in the latter variant. Only my own defined styling is there.

Any clue as to why this might happen?

## Your Environment
```
Angular CLI: 12.2.8
Node: 14.17.5
Package Manager: npm 7.23.0
OS: win32 x64

Angular: 12.2.8
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.8
@angular-devkit/build-angular   12.2.0-next.2
@angular-devkit/core            12.2.8
@angular-devkit/schematics      12.2.8
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             12.2.8
ng-packagr                      12.2.2
rxjs                            6.6.7
typescript                      4.3.5
```

**Anything else relevant?**
This isn't browser dependent; checked for this problem in multiple browsers

**Comment by alan-agius4** [comment]
Hi @rvanheest,

I looked into the reproduction. It appears that this is a storybook issue https://github.com/storybookjs/storybook/issues/15855

It appears that storybook depend on Webpack specific features and syntax to load the global CSS such as `import '!style-loader!css-loader!sass-loader!../assets/style.scss'. These syntaxes are not supported and can break in any version without warning.
