### ISSUE TITLE
Suggestions for Analytics Sharing

### ISSUE THREAD

**Issue by henry-alakazhang** [angular/angular-cli#21916]
# 🚀 Feature request

### Command

- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [x] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Hey all, I'm trying to set up analytics sharing to get some local build timings from the engineers in my org. It's quite cool and has the potential to be very useful, but I ran into a few issues:

#### 🐞 Bug (`ng config`) - The JSON schema for `cli.analyticsSharing.tracking` is wrong/overly restrictive
It currently enforces tracking IDs start with `GA-`, whereas my tracking ID is `UA-XXXXX-X` (and indeed the docs give a `UA-` tracking ID as an example). Google Analytics 4 has fully numeric IDs as well.

#### 📚 Docs - https://angular.io/cli/usage-analytics-gathering#per-user-tracking is out of date
It mentions per-user tracking and makes it seem optional, but it's not actually optional - shared tracking doesn't run if user is unset. The field is also `uuid`, and not `user` like the docs say. It's also not actually possible to disable the tracking via `ng config`, as `--remove` doesn't exist anymore and schema validation prevents setting to undefined/null.

#### 🚀 Feature request - report `AOT` as a custom dimension like Ivy (and not just a CLI flag)
https://github.com/angular/angular-cli/blob/master/docs/design/analytics.md suggests that usage of the `--aot` flag is passed to pageview analytics. I'm not sure if this is actually usable anymore due to changes to the CLI, but either way - it would be nice if all reporting (especially build timing `event`s) could report AOT status.

Specifically, we have configurations (rather than flags) that allow developers to disable AOT for speed, which obviously results in dramatically different build/rebuild times, and splitting by AOT would make the data more useful.

I should probably make separate issues. Please let me know if that would be better.

**Comment by alan-agius4** [comment]
Hi @henry-alakazhang,

Thanks for opening this issue. 

> 🐞 Bug (ng config) - The JSON schema for cli.analyticsSharing.tracking is wrong/overly restrictive

Can confirm that this is a bug which needs to be amended. (Will try to address this today)

> 📚 Docs - https://angular.io/cli/usage-analytics-gathering#per-user-tracking is out of date

The docs are indeed out of date . (Will try to address this today). To unset a field you can use `ng config cli.analyticsSharing.uuid undefined`.

> 🚀 Feature request - report AOT as a custom dimension like Ivy (and not just a CLI flag)

The aot flag is still a usable matrix, since users can still use JIT compilations. I think adding the `AOT` as dimension in the `build` and `rebuild` events would also be useful to use. **//cc** @mgechev what do you think? would you also find this useful from your end?

**Comment by alan-agius4** [comment]
> I can update these if you would like, though I guess I don't know the intended usage of some parts.
Thanks for the offer, although now I am almost done with the changes :)


> The suggested command doesn't actually work - it sets the field to the string "undefined", which is accepted by the CLI. universal-analytics then reports Invalid UUID format and defaults it to a generated one.

Undefined needs to be passed without it being wrapped in quotes, like the below

```
ng config cli.analyticsSharing.uuid undefined
```

**Comment by henry-alakazhang** [comment]
> Undefined needs to be passed without it being wrapped in quotes, like the below
> 
> ```
> ng config cli.analyticsSharing.uuid undefined
> ```

Ah yeah my bad, it's because I was using `yarn` to run the workspace `ng` and it was wrapping everything weirdly. `undefined` does indeed work.
