### ISSUE TITLE
Warnings in console

### ISSUE THREAD

**Issue by adibbz** [angular/angular-cli#21910]
I run my Angular 11 app with `ng serve --ssl` and see these warnings in the console. I've double checked and am not using these flags anywhere. These options are indeed set in `angular.json`. What am I missing?

<img width="1036" alt="Screen Shot 2021-10-08 at 1 33 22 PM" src="https://user-images.githubusercontent.com/6921939/136609271-371ea45b-0027-4db7-9ab7-14c8ee102667.png">

**Comment by alan-agius4** [comment]
In your angular.json, these options need to be moved from the dev-server (serve) to the browser (build) builder.
