### ISSUE TITLE
Fresh --style=stylus install does not work / runtime error

### ISSUE THREAD

**Issue by mwawrusch** [angular/angular-cli#2191]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

os: darwin x64
1. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.14
node: 6.1.0
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

ng new notworkingapp --style=stylus
1. The log given by the failure. Normally this include a stack trace and some
   more information.

It says that style.css needs to be an array of strings or something. Just run the install and open the app. Adding a style to styles.styl results in another error. 
1. Mention any other details that might be useful.

**Comment by bryanforbes** [comment]
One of the problems is that the application is generated with a `app.component.stylus` file and the webpack configuration is looking for `.styl` files. Renaming `app.component.stylus` to `app.component.styl` and changing the string in `app.component.ts` fixes the issue.

**Comment by bryanforbes** [comment]
After re-reading the README, I believe this is a documentation error. In the [CSS Preprocessor integration](https://github.com/angular/angular-cli/tree/bf9c8f1b2a8f0acac868d368cca2739a9a295df6#css-preprocessor-integration), it lists the three preprocessors supported by name (sass/scss, less, and stylus) and then gives an example of sass. This example works great if you substitute in the preprocessor names in the list above _except_ stylus. The extension that angular-cli's expects for stylus files is `styl`. There are two ways this could be solved: either update the README to document the valid values for the `--style` argument or when the user passes `--style=stylus`, set `styleExt` in the new project to `styl`. These two options aren't mutually exclusive, either.

**Comment by shahen94** [comment]
+1 Same issue on me
