### ISSUE TITLE
Unknown html tag mat-... etc. after ng build with Angular 12

### ISSUE THREAD

**Issue by EliasDerHai** [angular/angular-cli#21915]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Did this work before?

yes - I had projects for every major ng-version since ng 6 or so

### Description

Quite simple setup. I went:

    ng new test
    ng add @angular/material

I can code as i could with basicly any previous ng-version but after building i see just "unkown tags" (material components). (It stays like that until I reinstall npm modules...) Npm ci, deleting nodes_modules, reinstalling ng and node.js or changing minor package versions didn't help.

I even suspected Webstorm to be buggy so I went with vs-code but it's the same issue there.
<pre><code>
{
  "name": "path",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^12.1.0-",
    "@angular/common": "^12.1.0-",
    "@angular/compiler": "^12.1.0-",
    "@angular/core": "^12.1.0-",
    "@angular/forms": "^12.1.0-",
    "@angular/material": "^12.1.0",
    "@angular/cdk": "^12.1.0",
    "@angular/platform-browser": "^12.1.0-",
    "@angular/platform-browser-dynamic": "^12.1.0-",
    "@angular/router": "^12.1.0-",
    "rxjs": "~6.6.0",
    "tslib": "^2.2.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^12.1.3",
    "@angular/cli": "^12.1.3",
    "@angular/compiler-cli": "^12.1.0-",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.2"
  }
}
</pre></code>

## 🔥 Exception or Error

I do not get any bugs or error codes other than "Unknown Html tag ..."

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.9
Node: 14.18.0
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@schematics/angular             12.2.9
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

I already tried to get some help but I think I wont find it on stackoverflow
https://stackoverflow.com/questions/69509459/unknown-html-tag-mat-button-etc-after-ng-build-with-angular-12

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by EliasDerHai** [comment]
Hi here is my repo
https://github.com/EliasDerHai/AngularTwelve/

**Comment by alan-agius4** [comment]
@EliasDerHai, 

I am not understanding how to replicate the reported issue with the reproduction provided. Where and how to trigger the `unknown tags` error?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
