### ISSUE TITLE
Uncaught (in promise), Can't read configurator when opening new angular project

### ISSUE THREAD

**Issue by Elikill58** [angular/angular-cli#21922]
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, I just install everything with latest versions.

### Description

I just run the project and I can't use routes or something because of this error.

## 🔬 Minimal Reproduction

Run `ng new app-name --routing --defaults`

Then `ng serve` (compile sucessfull

## 🔥 Exception or Error

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'configurator')
    at testerMaker.js:1
    at c (testerMaker.js:1)
    at Generator._invoke (testerMaker.js:1)
    at Generator.next (testerMaker.js:1)
    at w (testerMaker.js:1)
    at r (testerMaker.js:1)
```

## 🌍 Your Environment

```
Angular CLI: 12.2.9
Node: 12.16.1
Package Manager: npm 8.0.0
OS: win32 x64

Angular: 12.2.9

@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@schematics/angular             12.2.9
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Elikill58** [comment]
With exact same version ? Do you have an idea where it can come from, such as third software that can manage this ?

Also, this is my `package.json` :
```json
{
  "name": "routing-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.9",
    "@angular/cli": "~12.2.9",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.3.5"
  }
}
```

**Comment by Elikill58** [comment]
Oh yes, just with incognito mode (which disable all extensions) there is no error.

I just check, and it's the `wanteeed` extension that create this issue. I will report it to us.

Thanks for taking time to reply, and sorry :/
