### ISSUE TITLE
Add dropConsole option for JavaScriptOptimizerPlugin for using in Terser

### ISSUE THREAD

**Issue by Serg-Mois** [angular/angular-cli#21923]
# 🚀 Feature request

### Command (mark with an `x`)
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Need to remove all console calls in production to minimize the bundle size, Terser plugin can do that, but we need to pass the option there. 

### Describe the solution you'd like

In https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts

```
optimizeWithTerser(
...
  const result = await minify(
    { [name]: code },
    {
      compress: {
        passes: advanced ? 2 : 1,
        pure_getters: advanced,
        drop_console: options.dropConsole // pass the option here 
      },
```

### Describe alternatives you've considered

It would be great if all plugins options would be configurable outside.

Before angular 12 it was possible to do that using custom webpack configs:

	config.optimization.minimizer
		.filter(({constructor: {name}}) => name === 'TerserPlugin')
		.forEach((terserPlugin: any) => {
			terserPlugin.options.terserOptions.compress.drop_console = true;
		});

**Comment by logerk46** [comment]
Hi all, 
could you explain in more detail how you solved of removing all console calls for production?
