### ISSUE TITLE
Files. destroy command does not remove directory.

### ISSUE THREAD

**Issue by MRokas** [angular/angular-cli#2194]
> Please provide us with the following information:
> ---------------------------------------------------------------

1\. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 16.0.4 64bit

2\. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
```
angular-cli: 1.0.0-beta.14                                                 
node: 6.6.0                                                                
os: linux x64 
```

3\. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
`ng generate component <name> && ng destroy component <name>`

4\. The log given by the failure. Normally this include a stack trace and some
   more information.
-

5\. Mention any other details that might be useful.
-
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We don't really support the `ng destroy` command, it was a leftover from `ember-cli` commands. https://github.com/angular/angular-cli/pull/2041 removes those commands from `ng help`,
