### ISSUE TITLE
Upgrading to 13.0.0-next.9 throws Error Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#21943]
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] build
- [ x] serve

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 13.0.0-next.7

### Description

I recently upgraded my Angular app to the latest version.

After upgrade when I try to build my app it throws below error:

`An unhandled exception occurred: Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined.
See "C:\Users\myuser\AppData\Local\Temp\ng-AkN2KG\angular-errors.log" for further details.`

## 🔬 Minimal Reproduction

Upgrade any app running on Angular CLI 13.0.0-next.7 to the latest version and I believe it will throw this error.

## 🔥 Exception or Error

An unhandled exception occurred: Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined.
See "C:\Users\myuser\AppData\Local\Temp\ng-AkN2KG\angular-errors.log" for further details.

[error] TypeError: Cannot destructure property 'styles' of 'buildOptions.sourceMap' as it is undefined.
    at getBrowserConfig (D:\MyProject\node_modules\@angular-devkit\build-angular\src\webpack\configs\browser.js:18:21)
    at D:\MyProject\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:127:44
    at D:\MyProject\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:71:16
    at generateWebpackConfig (D:\MyProject\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:60:40)
    at async generateBrowserWebpackConfigFromContext (D:\MyProject\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:122:20)
    at async generateI18nBrowserWebpackConfigFromContext (D:\MyProject\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:69:20)
    at async setup (D:\MyProject\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:124:47)

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.0.0-next.9
Node: 14.17.6
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.0.0-rc.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1300.0-next.9
@angular-devkit/build-angular    13.0.0-next.9
@angular-devkit/core             13.0.0-next.9
@angular-devkit/schematics       13.0.0-next.9
@angular/cdk                     13.0.0-next.8
@angular/cli                     13.0.0-next.9
@angular/fire                    7.1.0
@angular/google-maps             13.0.0-next.8
@angular/material                13.0.0-next.8
@angular/pwa                     13.0.0-next.9
@nguniversal/aspnetcore-engine   12.1.1
@nguniversal/builders            12.1.1
@nguniversal/common              12.1.1
@schematics/angular              13.0.0-next.9
rxjs                             6.6.7
typescript                       4.4.4

</code></pre>

**Anything else relevant?**

Below is my angular.json

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "MyProject": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "ngx-build-plus:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "progress": true,
            "aot": true,
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/manifest.json",
              "src/firebase-messaging-sw-v14.js"
            ],
            "styles": [
              "src/styles/site.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": false
                },
                "fonts": true
              },
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "serviceWorker": true
            }
          }
        },
        "serve": {
          "builder": "ngx-build-plus:dev-server",
          "options": {
            "browserTarget": "MyProject:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "MyProject:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "MyProject:build"
          }
        },
        "test": {
          "builder": "ngx-build-plus:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "inlineStyleLanguage": "scss",
            "scripts": [],
            "styles": [
            ],
            "assets": [
              "src/assets",
              "src/manifest.json"
            ]
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist-server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json",
            "sourceMap": true,
            "optimization": false
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "media",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "bundleDependencies": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "browserTarget": "MyProject:build:production",
            "serverTarget": "MyProject:server:production",
            "routes": [
              "/"
            ]
          },
          "configurations": {
            "production": {}
          }
        }
      }
    }
  },
  "defaultProject": "MyProject",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "styleext": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}
```

**Comment by alan-agius4** [comment]
This seems to be an issue with `ngx-build-plus` which is not compatible with version 13 of the Angular CLI.
