### ISSUE TITLE
Infer uniqueName of generated webpack chunks from project name

### ISSUE THREAD

**Issue by fischeversenker** [angular/angular-cli#21957]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Webpack 5 introduced ["automatic unique naming"](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-unique-naming) which takes the name from the closest `package.json` to use it as the name of the generated webpack chunk. This got rid of a lot of the global `webpackJsonp` issues that we've seen in the past.
In Angular workspaces with multiple projects and a single root `package.json` this still results in webpack chunks that are named the same (e.g. `webpackChunkmy_workspace`). It would be nice for the default `@angular-devkit/build-angular:browser` builder to be able to infer the `uniqueName` for the chunk from the project name. The use-case here is to be able to more easily generate multiple web component bundles from a single workspace without name clashes in the generated bundles.

### Describe the solution you'd like

I'd like to automatically get uniquely named webpack chunks from a regular out-of-the-box Angular build.

### Describe alternatives you've considered

The currently suggested approach to solve this is to switch to the `@angular-builders/custom-webpack:browser` builder and to provide a custom webpack config that specifies the `output.uniqueName` property. For a single property this change feels like overkill, especially since the name could easily be inferred from the project name.

**Comment by willyboy** [comment]
Will this be released as a fix for v12 or will we have to go to 13 to get this? @clydin @alan-agius4

**Comment by alan-agius4** [comment]
@willyboy, this is only included in v13.
