### ISSUE TITLE
Support Angular Json Version 2 With Standalone Configurations

### ISSUE THREAD

**Issue by kurtisblaine** [angular/angular-cli#21959]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [X] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Invalid format version detected - Expected [1] Found [2]. Support Angular Json Version 2 with standalone configurations ie project.json files and angular.json for monorepos.

### Describe the solution you'd like

Fetch app from angular file and find the project configuration and parse that instead. This should work with the schematic `@angular/pwa` collection.

**Comment by alan-agius4** [comment]
Closing as per above comment.
