### ISSUE TITLE
How to run my Angular application in IE-11 support ?

### ISSUE THREAD

**Issue by JKAngular** [angular/angular-cli#21954]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

Hi
I have developed angular application 12 version it is working good in Chrome and Mozila.
but  not working  Angular application in IE-11 support ?

by following this url for Angular run IE 11 

https://dev.to/getamano/angular-8-x-9-x-internet-explorer-not-working-quick-solution-3ha7

error shows like this

Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.6, but postcss-preset-env uses 7.0.36. Perhaps this is the source of the error below.

### Please provide a link to a minimal reproduction of the bug

Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.6, but postcss-preset-env uses 7.0.36. Perhaps this is the source of the error below.

### Please provide the exception or error you saw

```true
Hi
I have developed angular application 12 version it is working good in Chrome and Mozila.
but  not working  Angular application in IE-11 support ?

by following this url for Angular run IE 11 

https://dev.to/getamano/angular-8-x-9-x-internet-explorer-not-working-quick-solution-3ha7

error shows like this

Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.6, but postcss-preset-env uses 7.0.36. Perhaps this is the source of the error below.
```

**Comment by JKAngular** [comment]
Hi @petebacondarwin

I am using Angular version 12.0.5 version

**Comment by alan-agius4** [comment]
Can you try like to delete the lock file and node_modules?

```
rm -rf node_modules package-lock.json
npm i
```

If the problem persists please provide the output of `ng version` and `npm ls postcss`.
