### ISSUE TITLE
npm i --save-dev @angular-devkit/build-angular@0.1102.4 fails with error: unexpected end of JSON input while parsing near '...nt-hex-parser":"1.6.0'

### ISSUE THREAD

**Issue by elira** [angular/angular-cli#21950]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

While trying to install my angular 11 node modules, I got the following error:
unexpected end of JSON input while parsing near '...nt-hex-parser":"1.6.0'

I managed to track the npm package causing the issue:
`@angular-devkit/build-angular@0.1102.4`

I upgraded to 12 and that solved the issue. 
Recreating this is easy, just:
`npm i --save-dev @angular-devkit/build-angular@0.1102.4`

### Please provide the exception or error you saw

```true
npm ERR! Unexpected end of JSON input while parsing near '...nt-hex-parser":"1.6.0'

npm ERR! A complete log of this run can be found in:
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.5
Node: v12.22.0
Package Manager: npm 6.14.11
Os: Windows 10 proffesional 64 bit

This issue recreates in an empty npm package too.
```

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.
