### ISSUE TITLE
ng build doesnt copy assets without --prod

### ISSUE THREAD

**Issue by svrooij** [angular/angular-cli#21951]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Not sure, but it clearly worked before.

### Description

 Running `ng build` doesn't copy the assets folder on a newly generated angular project. If I however run `ng build --prod` it does copy the assets folder.

## 🔬 Minimal Reproduction

1. Run `ng new repo-app`
2. go to folder
3. Add any image to the `assets` folder
4. Run `ng build` (defaults to production, so it seems).
5. Check the `dist/assets` folder for the created image (doesn't exists)
6.  Run `ng build --prod`
7. Check the `dist/assets` folder again, the image is there.

## 🔥 Exception or Error

<pre><code>
> ng build --prod
Option "--prod" is deprecated: No need to use this option as this builder defaults to configuration "production".
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

</code></pre>

## 🌍 Your Environment

<pre><code>
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.2.8
Node: 16.8.0 (Unsupported)
Package Manager: npm 7.21.0
OS: win32 x64

Angular: 12.2.8
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.8
@angular-devkit/build-angular   12.2.8
@angular-devkit/core            12.2.8
@angular-devkit/schematics      12.2.8
@schematics/angular             12.2.8
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@svrooij, I am unable to replicate the issue with the steps provided above. Can you please share your `angular.json`?
