### ISSUE TITLE
Import component statement with slash facing wrong way in app.module.ts

### ISSUE THREAD

**Issue by jculverwell** [angular/angular-cli#2196]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

1.0.0-beta.14

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Creating a component in a sub folder using the either of the commands below:

```
ng g c \explorer\explorerrecordcontent  
ng g c /explorer/explorerrecordcontent  
```

results in the second slash facing the wrong direction in the generated import statement in app.module.ts

```
import { ExplorerrecordcontentComponent } from './explorer\explorerrecordcontent/explorerrecordcontent.component';
```

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/1961
