### ISSUE TITLE
Angular project's version updating is a extra hassel

### ISSUE THREAD

**Issue by sefatanam** [angular/angular-cli#21960]
Like when I try to update my angular version 11 project to angular version 12 , I run ``ng update`` then its shows 

```
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 0 dependencies.
    We analyzed your package.json, there are some packages to update:

      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       11.0.0 -> 12.2.10        ng update @angular/cdk
      @angular/cli                       11.2.0 -> 12.2.10        ng update @angular/cli
      @angular/core                      11.0.0 -> 12.2.10        ng update @angular/core
      @angular/material                  11.0.0 -> 12.2.10        ng update @angular/material
      @ngrx/store                        8.6.0 -> 12.5.0          ng update @ngrx/store

    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.
```

then I run ``ng update --allow-dirty --force --verbose`` & got same output as ``ng update``  all though ``--all`` is deprecated. I also runs ``ng update @angular/cdk @angular/cli @angular/core @angular/material ``

```
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 0 dependencies.
Package '@angular/cdk' is not a dependency.

```

Actually what is going on here. What's wrong ? I'm totally fed-up didn't get any useful solution on [https://angular.io/cli/update](https://angular.io/cli/update) here. Please make it more convenient and explain in more detail manner so that if someone want to update project he could easily update project without this kinda of common hassel.

Thanks

**Comment by sefatanam** [comment]
@LAlves91 I install npm again & also try npm update it successed but ng update still now not working.

**Comment by LAlves91** [comment]
@sefatanam 

After deleting node_modules and getting the same result as you, I've executed `npm install` and `ng update @angular/cli@12.2.10`. It worked as expected!

Did you run ng update specifying the packages @angular/cli and @angular/core?

**Comment by sefatanam** [comment]
yes, I tried. I think I tried everything I got from internet.

**Comment by sefatanam** [comment]
✔ It worked. Thanks  @LAlves91 for your support & patient.
