### ISSUE TITLE
angular-cli   install on windows 7 is not successful - node v4.5 & npm v3.10.8

### ISSUE THREAD

**Issue by blueRegen** [angular/angular-cli#2198]
> Please provide us with the following information:
> -angular-cli install on windows 7 is not successful
Tried installing using Powershell using admin mode. 

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 7 enterprise 

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
my node version is 4.5
NPM version 3.10.8

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Not applicable

4. The log given by the failure. Normally this include a stack trace and some
   more information.

https://drive.google.com/file/d/0B_pP_VR9rtNleFE3Sk9BZlU5TzA/view?usp=sharing

Log : 
[https://drive.google.com/file/d/0B_pP_VR9rtNleFE3Sk9BZlU5TzA/view?usp=sharing](url)

5. Mention any other details that might be useful.

112861 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
112862 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
112862 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
112862 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
112862 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
112863 warn string-replace-loader@1.0.4 requires a peer of webpack@1.x.x || 2.x.x || 2.x.x-beta but none was installed.
112864 verbose If you need help, you may report this error at:
112864 verbose     <https://github.com/npm/npm/issues>
112865 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\narasas\AppData\Roaming\npm\node_modules\.staging\abbrev-36f0a5d0' -> 'C:\Users\narasas\AppData\Roaming\npm

\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
112865 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
112865 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)
112865 verbose stack
112865 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Users\narasas\AppData\Roaming\npm\node_modules\.staging\abbrev-36f0a5d0' -> 'C:\Users\narasas\AppData\Roaming\npm

\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
112865 verbose stack     at Error (native)
112866 verbose cwd C:\ashok\per\dev\ang2
112867 error Windows_NT 6.1.7601
112868 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
112869 error node v4.5.0
112870 error npm  v3.10.8
112871 error path C:\Users\narasas\AppData\Roaming\npm\node_modules\.staging\abbrev-36f0a5d0
112872 error code ENOENT
112873 error errno -4058
112874 error syscall rename
112875 error enoent ENOENT: no such file or directory, rename 'C:\Users\narasas\AppData\Roaming\npm\node_modules\.staging\abbrev-36f0a5d0' -> 'C:\Users\narasas\AppData\Roaming\npm

\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
112876 error enoent ENOENT: no such file or directory, rename 'C:\Users\narasas\AppData\Roaming\npm\node_modules\.staging\abbrev-36f0a5d0' -> 'C:\Users\narasas\AppData\Roaming\npm

\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
112876 error enoent This is most likely not a problem with npm itself
112876 error enoent and is related to npm not being able to find a file.
112877 verbose exit [ -4058, true ]

**Comment by chumtoadafuq** [comment]
I'm having an issue on Windows 10.
https://github.com/angular/angular-cli/issues/2193

**Comment by martijnn** [comment]
This solved the issue for me:
```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest
```

**Comment by blueRegen** [comment]
Martijnn - Thanks for offering help.

Ok will try the recommendation.

**Comment by blueRegen** [comment]
Hi martijnn ,

That in addition to paying close attention to prequisites mentioned fixed the problem.
So I uninstalled node and reinstalled required versions.

thanks for your help.

**Comment by reddynr** [comment]
HI I am getting below error. any suggestion much appreciated. Thanks

Error: Cannot find module './internal/streams/BufferList'

**Comment by filipesilva** [comment]
@reddynr please open a new issue describing your problem.

**Comment by ramsunvtech** [comment]
Use Windows PowerShell which solved my issue

**Comment by NatarajanDesu** [comment]
Hi I am getting error like "notsup SKIPPING OPTIONAL DEPEDENCY: Unsupported platform for fsevents@1.1.2: wanted <"os":"darwin","arch":"any"> <current: <"os":"win32","arch":"x64">>."  and 
"angular/core@2.4.10 requires a peer of rxjs@^5.0.1 but none was installed"

Could you please help me for how to resolve this problem..
