### ISSUE TITLE
Add build flag to disable usage of esbuild in NG 12.2 and upward

### ISSUE THREAD

**Issue by L-X-T** [angular/angular-cli#21996]
# 🚀 Feature request

- [x] build

## Description

Since our build is running on a _Windows_ environment (plz don't ask why) and we're running into an error with "esbuild.exe" being blocked by the _Security Suite_ we wanted to ask for a build flag to disable esbuild usage (like until NG 12.1).

### Describe the solution you'd like

**ng build flag** to disable usage of **esbuild**

### Describe alternatives you've considered

If not provided of course we need to find another environment to build.

**Comment by alan-agius4** [comment]
@L-X-T, can you please provide the requested information above? Thanks.

**Comment by alan-agius4** [comment]
Closing due since the information required has not been provided.
