### ISSUE TITLE
Add @angular/cdk/a11y to the  `ng new` generated app

### ISSUE THREAD

**Issue by twerske** [angular/angular-cli#22021]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Add `@angular/cdk/a11y` to the  `ng new` generated app to encourage and surface the knowledge of the a11y package to new developers.

**Comment by twerske** [comment]
Definitely the first and not the latter. I think the "Next Steps" would be a suitable place (I opening an issue to discuss this topic since I wasn't sure the best place for it). I love that idea.

Also agreed that links to docs would make that 100% more valuable!

**Comment by alan-agius4** [comment]
@twerske do we still want to do this?

**Comment by twerske** [comment]
Closing
