### ISSUE TITLE
 %X_UA_COMPATIBLE% displayed in the runner web page in debug mode

### ISSUE THREAD

**Issue by sroucheray** [angular/angular-cli#22036]
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

### Description

The runner web page in debug mode displays an %X_UA_COMPATIBLE% text.
![image](https://user-images.githubusercontent.com/169818/139299936-cc7617f5-604b-42ea-8dc4-7311bc514a17.png)

## 🔬 Minimal Reproduction
```
# install the cli
npm install -g @angular/cli
# create a new project
ng new my-app
cd my-app
# launch the tests
ng test
# then open the debug page
```

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.9
Node: 14.18.0
Package Manager: yarn 1.22.15
OS: linux x64

Angular: 12.2.9
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.11
@angular-devkit/build-angular   12.2.9
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@schematics/angular             12.2.9
ng-packagr                      12.2.4
rxjs                            6.5.5
typescript                      4.3.5
webpack                         5.59.1
</code></pre>

**Anything else relevant?**

I originally posted [an issue](https://github.com/karma-runner/karma/issues/3711) on Karma's github issue tracker but while digging for this problem I realized this repo hold a duplicate of the Karma debug page so maybe the issue is here.
https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma-debug.html

**Comment by alan-agius4** [comment]
Fixed upstream via https://github.com/karma-runner/karma/pull/3718
