### ISSUE TITLE
Node (16.13.0) is not supported

### ISSUE THREAD

**Issue by pablorea** [angular/angular-cli#22041]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.2.11

### Description

 Node (16.13.0) is not supported

## 🔥 Exception or Error

<pre>Warning: The current version of Node (16.13.0) is not supported by Angular.<code>

</code></pre>

## 🌍 Your Environment

<pre>Angular CLI: 12.2.12
Node: 16.13.0 (Unsupported)
Package Manager: npm 8.1.0
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.12 (cli-only)
@angular-devkit/core         12.2.12 (cli-only)
@angular-devkit/schematics   12.2.12 (cli-only)
@schematics/angular          12.2.12 (cli-only)
    
Warning: The current version of Node (16.13.0) is not supported by Angular.
<code>

</code></pre>

**Anything else relevant?**

**Comment by Guezza** [comment]
Thanks a Lot

**Comment by inforalex** [comment]
Matriz de compatibilidade Angular CLI, Angular, Node.js, TypeScript e RxJS. Baseado em changelogs, metadados e experiência prática. As versões principais de Node.js e RxJS acima das versões oficialmente suportadas não estão listadas. Observe que as versões menores do TypeScript também contêm alterações importantes.

https://gist.github.com/LayZeeDK/c822cc812f75bb07b7c55d07ba2719b3
