### ISSUE TITLE
faster with  ng serve using native esm

### ISSUE THREAD

**Issue by John0King** [angular/angular-cli#22053]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

```
Angular CLI: 12.2.12
Node: 14.18.1
Package Manager: yarn 1.22.11
OS: win32 x64
```

today with a simple app created by `ng new`, it take 19+second to  complete with `ng server` , that feel really slower.

-----------------------------

update：  cold `ng s`(eg. first time build) take about 1min10s to complete on a HDD disk,   19s is for sub sequence `ng s`.

### Describe the solution you'd like

May take advantage of native esm  instead of compile all the dependencies 

### Describe alternatives you've considered

anything that can may `ng serve`  faster  on windows, 
`ng build` normally only effect release , but `ng serve` about about develop time  ,  a reasonable time is <= 6s

**Comment by alan-agius4** [comment]
Thanks for this feature request. 

This is actually something that we have been discussing recently and is definitly on our radar of this we want to investigate in the near future.

**Comment by Ottunger** [comment]
@alan-agius4 , do you know what changed with ng13?

Also, is there a way to disable obfuscation (actually minification) on dev-server `ng serve` of generated .js files? Not only makes it easier to debug with complete stacktraces rather than `on a.eT()` but also makes the build faster.

**Comment by alan-agius4** [comment]
@Ottunger, your issue seems to be off topic. Please file a new issue with a reproduction. Thanks.

**Comment by jpike88** [comment]
@alan-agius4 I would very much appreciate if the Angular team could focus, as priority number 1, on improving the performance of ng build, serve, etc, they are crazy slow and need dire attention.

**Comment by John0King** [comment]
any progress on this ?

**Comment by muhamedkarajic** [comment]
> Thank you for submitting your feature request! Looks like during the polling process it didn't collect a sufficient number of votes to move to the next stage.

Its probably not taking track cause the naming of the issue isn't obvious. I'm pretty sure a lot of people would like vite build like times.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
