### ISSUE TITLE
NG Build --prod, missing files from /dist/vendor

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#2207]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
$ ng --version
angular-cli: 1.0.0-beta.10
node: 4.4.7
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

Angular 2.0.0 (RTM), running ng build --prod

Only these folders are in /dist/vendor:
![image](https://cloud.githubusercontent.com/assets/14539000/18619643/f3227ee6-7e55-11e6-81f8-0618dec624db.png)

A lot of files are missing from /dist/vendor:

![image](https://cloud.githubusercontent.com/assets/14539000/18619642/e5c235b6-7e55-11e6-8739-c2d6a237a220.png)

**Comment by filipesilva** [comment]
Your error was due to a misconfiguration if 3rd party libs, which was admittedly hard in <beta.10. beta.15 and up make that much easier, see https://github.com/angular/angular-cli#webpack-update for upgrade instructions.
