### ISSUE TITLE
Webpack 5 + Angular 13.0.0 - asyncToGenerator failed to resolve

### ISSUE THREAD

**Issue by krusche** [angular/angular-cli#22073]
Similar issue as https://github.com/angular/angular-cli/issues/20800 but just with Angular 13

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

✍️--> Yes, the previous version in which this bug was not present was: 12.2.12

### Description

I just updated to Angular 13 in the project http://github.com/ls1intum/Artemis and received multiple issues (see below), which we never have seen before

## 🔬 Minimal Reproduction

1. Clone https://github.com/ls1intum/Artemis
2. Checkout the branch `chore/angular13` (see https://github.com/ls1intum/Artemis/tree/chore/angular13)
3. Execute `npm run webapp:build` (which is basically the same as `ng build --configuration development`)

Note: the same error also appears with `ng build --configuration production`

## 🔥 Exception or Error

<pre><code>
./src/main/webapp/app/exercises/programming/assess/programming-assessment-dashboard/programming-assessment-dashboard.component.ts:1:0-164 - Error: Module not found: Error: Can't resolve '~/Projects/Artemis/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/esm/asyncToGenerator' in '~/Projects/Artemis/src/main/webapp/app/exercises/programming/assess/programming-assessment-dashboard'
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.0
Node: 16.13.0
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 13.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.12
@angular-devkit/build-angular   13.0.0
@angular-devkit/core            12.2.12
@angular-devkit/schematics      13.0.0
@angular/cdk                    12.2.12
@schematics/angular             13.0.0
rxjs                            7.4.0
typescript                      4.4.4
webpack                         5.61.0

</code></pre>

**Anything else relevant?**

I am using macOS 12.0.1 on a 14" MacBook Pro (M1 Max), but I assume the issue is independent of the operating system.
The errors can also be seen on Github actions: https://github.com/ls1intum/Artemis/runs/4098095003

**Comment by clydin** [comment]
From reviewing the referenced project, it appears that the project is using a third-party builder package (`@angular-builders/custom-webpack`). This package is not maintained or supported by the Angular Team.  From the version output shown above (which contains both v12 and v13 package versions), `@angular-builders/custom-webpack` may not yet be compatible with Angular v13. Please open an issue with the `@angular-builders/custom-webpack` project regarding v13 support if this issue persists.

**Comment by maximedupre** [comment]
@just-jeb

**Comment by just-jeb** [comment]
Well, v13 is out for Angular Builder as well. Try to align the versions and see if it solves the problem. If not, try to regenerate your lock file, usually it helps.

**Comment by maximedupre** [comment]
@just-jeb Yeah I've updated both to v13 and tried deleting the `package-lock.json` and node_modules. Still failing, not sure what's going on 🤔

**Comment by just-jeb** [comment]
Would you mind opening an issue for this with a repro, so that I could take a look?

**Comment by maximedupre** [comment]
I'm not sure I'll have time to strip down everything to the minimum repro. This is from a huge repo at my job. But if I do I'll create a ticket. Also, not sure if this helps, but on our side, the issue only occurs when running tests (ng test).

**Comment by just-jeb** [comment]
Can you share your `package.json` and `package-lock.json`?

**Comment by maximedupre** [comment]
Sure! `package-lock.json` is a little bit too large to be posted here, so: https://www.dropbox.com/sh/tb747wjuoz9zd77/AADEaroPwVyVj36Jti4AhKq1a?dl=0

**Comment by just-jeb** [comment]
From what I can see in your `package.json` you're using builder v12 with Angular v13. 
As the [docs state](https://github.com/just-jeb/angular-builders#the-latest-version-of-all-the-builders-require-angular-cli-13) the major versions should match. Please try to use `@angular-builders/custom-webpack@13` and see if it solves your problem. Thank you.

**Comment by maximedupre** [comment]
That was honestly just a bad copy and paste. I reverted to builder 12 to change it back before sending it to you.

With that said...this morning I can't reproduce the issue after a `package-lock.json` and `node_modules` delete + reinstall. Not sure why, I did that multiple times last week 😅

Thanks for the support though 🙏
