### ISSUE TITLE
Feat: Provide findLazyModules functionality as separate package

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular-cli#2208]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
4. The log given by the failure. Normally this include a stack trace and some
   more information.
5. Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

I want to be able to use the feature that finds the `loadChildren` references and replaces them with the appropriate context in a vanilla webpack setup outside of using the CLI.

**Comment by hansl** [comment]
Closing this; there's a point in the roadmap to let addons and scripts be able to access that information. For the time being we won't expose those functions.
