### ISSUE TITLE
Service worker generation failed.  Update to version 13

### ISSUE THREAD

**Issue by blueiceprj** [angular/angular-cli#22089]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

I get this error message on build after updating to version 13 .

### Please provide the exception or error you saw

```true
✖ Service worker generation failed.
Must use import to load ES Module: ................../node_modules/@angular/service-worker/fesm2015/config.mjs
```

**Comment by Goldyi** [comment]
@alan-agius4 getting service worker generation failed error after upgrading to angular 13, also dont have any custom webpack.

![image](https://user-images.githubusercontent.com/94591567/142378988-7d3f7eb1-b9f9-44c0-9176-7c95f62fcc85.png)

**Comment by alan-agius4** [comment]
@Goldyi, please provide the output of `ng version`.

**Comment by Goldyi** [comment]
@alan-agius4  

![image](https://user-images.githubusercontent.com/94591567/142398749-8a7ef674-b20b-4fdf-a7e3-d4928b1ae361.png)

**Comment by alan-agius4** [comment]
It looks like you are using an outdated version fo @angular/server-worker.
