### ISSUE TITLE
Angular 13 Build crashes with Cannot find module 'webpack-sources'

### ISSUE THREAD

**Issue by bobskigit** [angular/angular-cli#22082]
Upgraded Angular 12.2 app to Angular 13, all migrations completed.

ng serve works

ng build --configuration production crashes with

[error] Error: Cannot find module 'webpack-sources'
Require stack:
- C:\Users\bobla\Documents\projects\videoads\node_modules\license-webpack-plugin\dist\WebpackAssetManager.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\license-webpack-plugin\dist\LicenseWebpackPlugin.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\license-webpack-plugin\dist\index.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular-devkit\build-angular\src\webpack\configs\common.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular-devkit\build-angular\src\webpack\configs\index.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular-devkit\build-angular\src\builders\browser\index.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular\cli\models\architect-command.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular\cli\commands\build-impl.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular\cli\models\command-runner.js
- C:\Users\bobla\Documents\projects\videoads\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\bobla\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\bobla\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\bobla\Documents\projects\videoads\node_modules\license-webpack-plugin\dist\WebpackAssetManager.js:4:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\bobla\Documents\projects\videoads\node_modules\license-webpack-plugin\dist\LicenseWebpackPlugin.js:12:29)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)

**Comment by alan-agius4** [comment]
Hi,

Can you please provide the below information:

- Output of `ng version`
- Are you using 3rd party builders?

**Comment by JoostK** [comment]
In #22076 it was sufficient to remove node_modules and lockfiles to make this work.

**Comment by bobskigit** [comment]
Angular: 13.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.1
@angular-devkit/build-angular   13.0.1
@angular-devkit/build-webpack   0.1300.1
@angular-devkit/core            12.2.12
@angular-devkit/schematics      12.2.12
@angular/cli                    13.0.1
@angular/pwa                    12.2.12
@schematics/angular             12.2.12
ng-packagr                      13.0.0
rxjs                            7.4.0
typescript                      4.4.4

No third party builders.

**Comment by alan-agius4** [comment]
@bobskigit, as suggested by @JoostK can you please try to remove node_modules and the lock file and see if this solved the problem?

**Comment by bobskigit** [comment]
I removed node_modules and lock file. Same problem but I them did a npm i --save webpack-sources and that now allows it to build successfully.

**Comment by nidri** [comment]
Thanks @bobskigit 
`npm i --save webpack-sources` worked

**Comment by thduttonuk** [comment]
I have this issue too running ```ng build --configuration=production --localize```. The above solved it.
