### ISSUE TITLE
USE CASE: Set up after we finish linting in order to prevent submissions to git with dirty code.

### ISSUE THREAD

**Issue by ocampd1** [angular/angular-cli#22095]
https://stackoverflow.com/questions/51141949/how-to-add-git-prehook-to-tslint

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
