### ISSUE TITLE
Official procedure of update Angular 9.0 to 10.0 fails

### ISSUE THREAD

**Issue by pdi-astec** [angular/angular-cli#22099]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes, the previous version in which this bug was not present was: 9.0

### Description
Within the update command using npx with @angular/cli@10 the required version of Node.js should be >=10.13.0 however the error message says that minimum version of Node.js has to be v12.20.
It looks like npx is using the last version of @angular/cli@13 instead of specified within the command.

## 🔬 Minimal Reproduction
<pre><code>
npx @angular/cli@10 update @angular/core@10 @angular/cli@10
</code></pre>
## 🔥 Exception or Error
<pre><code>
Node.js version v12.16.3 detected.
The Angular CLI requires a minimum Node.js version of either v12.20, v14.15, or v16.10.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 9.1.4
Node: 12.16.3
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cdk                      9.2.2
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
As a workaround you can use the below.

```
NG_DISABLE_VERSION_CHECK=1 ./node_modules/.bin/ng update @angular/cli@10 @angular/core@10
```

**Comment by EmaGht** [comment]
I'm not sure this is related to my issue but it sounds like it is...
I recently tried to run this command:

`ng update @angular/cli@^11 @angular/core@^11 @angular/material@^11 @angular/cdk @^11`

But i got a mixed install with the latest version 11 for some packages and the latest version 12 for others

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/22225
