### ISSUE TITLE
Angular 13 sending application/octet-stream MIME type for unknown files

### ISSUE THREAD

**Issue by acalvo** [angular/angular-cli#22091]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.x

### Description

Until now, a file without extension was served by Angular in dev mode (`ng serve`) with the `; charset=UTF8` `Content-Type` header, which enabled the MIME type sniffing making the browser treat it correctly. With Angular 13 the header changed to `application/octet-stream` which made the browser try to download it.

We set the appropriate headers to file in production, but this can't be done in the dev server as long as I know, so we relied in MIME type sniffing for dev mode until now.

## 🔬 Minimal Reproduction

Create any asset without extension (for example a simple html file without extension), run `ng serve` and navigate to that URL. In Angular12 it'll be displayed, in Angular13 the browser will ask to download it.

## 🔥 Exception or Error

-

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.1
Node: 14.17.1
Package Manager: npm 7.24.1
OS: darwin x64

Angular: 13.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.7
@angular-devkit/build-angular   13.0.1
@angular-devkit/core            12.2.7
@angular-devkit/schematics      13.0.1
@angular/cli                    13.0.1
@schematics/angular             13.0.1
rxjs                            6.6.7
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @acalvo, 

Using `application/octet-stream` in this case seems to be the correct behaviour for files without extensions, especially considering the `webpack-dev-server` uses Express engine under the hood. Related [test]( https://github.com/clshortfuse/webpack-dev-middleware/blob/b1fe6bd31e9b026c2e378ce1cb86c6805d23bf5d/test/middleware.test.js#L592-L602) in `webpack-dev-middleware`

This also aligns with the spec found in https://tools.ietf.org/html/rfc2045
> Any entity with an unrecognized Content-Transfer-Encoding must be treated as if it has a Content-Type of "application/octet-stream", regardless of what the Content-Type header field actually says.

Files without extensions are also handled different from one server engine to another and therefore I don't recommand using a file without extension, there is a good comparison [here](https://github.com/webpack/webpack-dev-middleware/issues/354#issuecomment-752833171).

**Comment by alan-agius4** [comment]
Closing as this seems to be working as design by Express engine.
