### ISSUE TITLE
error after 'ng serve'

### ISSUE THREAD

**Issue by krasevych** [angular/angular-cli#221]
```shell
$ ng serve
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
Warning: ignoring input sourcemap for vendor/systemjs/dist/system-polyfills.js b
ecause ENOENT: no such file or directory, open 'd:\Angular 2\examples\APP_INSTAL
L_LIB_TEST\tmp\source_map_concat-input_base_path-uhS507BL.tmp\0\vendor\systemjs\
dist\system-polyfills.js.map'
```

**Comment by krasevych** [comment]
and into console i see:
```shell

vendor.js:3318 Uncaught ReferenceError: System is not defined
libs.js:1 Uncaught ReferenceError: System is not defined
localhost/:16 Uncaught ReferenceError: System is not defined
```

**Comment by filipesilva** [comment]
I just did it myself, and couldn't replicate the issue. Are you using the latest master? We're a bit late on making a new version and there are loads of issues and functionality on the latest master.

You can see how to use it here: https://github.com/angular/angular-cli#working-with-master

**Comment by xmlking** [comment]
@filipesilva I followed  https://github.com/angular/angular-cli#working-with-master
I am getting same errors as described above 
my Env: node -v = v5.6.0,   tsc -v = Version 1.9.0-dev.20160218

**Comment by filipesilva** [comment]
Just verified myself, and getting the same thing. Will investigate a solution.

**Comment by filipesilva** [comment]
Will track this issue in #220, since they are the same.

**Comment by filipesilva** [comment]
@krasevych it should be fixed now, on latest master. Thank you for reporting this!
