### ISSUE TITLE
Migration to v13 crash webpack dev server

### ISSUE THREAD

**Issue by ahmad66617** [angular/angular-cli#22108]
Hey guys!
Please help with this trouble - 
when I upgrade angular from 12ver to 13ver - webpack dev server crash when app runs in docker.
When i started on localhost - all works good, but socket connection crash in docker container and hot reload not works

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
