### ISSUE TITLE
Angular 13 - ng serve isn't watching changes in node_modules anymore

### ISSUE THREAD

**Issue by mikerentmeister** [angular/angular-cli#22104]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I am currently developing a library and 2 other application side-by-side. The library is published to npm, and referenced within the package.json both of the other applications. In order to speed up local development when changes are needed in both places, I am using a 3rd party package called [deploy reloaded](https://github.com/mkloubert/vscode-deploy-reloaded) to watch file changes in my library, and then replace the files in the node_modules folder for my applications. My tsconfig.json is setup to include my specific mode modules folder in the compilation.

```
Application 1 - tsconfig.app.json
{
  "extends": "./tsconfig.json",
  "include": [
    "src/**/*.ts",
    "node_modules/@experlogix/common/lib/**/*.ts"
  ]
}
```

Up until Angular 13, this has worked beautifully. At first I was thinking this might be related to the [persistent disk caching](https://angular.io/cli/cache#persistent-disk-cache) feature. Therefore I went to my angular.json file and disabled the cache, called ng serve again, tried making a change to the library code in node_modules, and ng serve still didn't pick up the file changes like it used to. I then tried deleting the .angular/cache folder that was still on my disk and tried the process again, to no avail.

```
Application 1 - angular.json
"cli": {
  "packageManager": "yarn",
  "analytics": false,
  "cache": {
    "enabled": false,
    "environment": "all"
  }
}
```

What's funny about what I described above is that ng serve did output this to the console when the node_modules file changed, leading me to believe it did in fact detect a file change, but didn't compile the new file into the build...

![image](https://user-images.githubusercontent.com/18708788/140518193-a8019c01-3a13-4111-89e8-6c00be12e666.png)

Apart from what I have tried, is there anything else that I could try to not lose this behavior? A way to tell Angular to watch a specific path in node_modules for file changes as well? If this is not supported anymore, I would love some suggestions of other things that you can do to develop a library locally, and push changes to other applications while debugging.

Command used for ng serve:
ng serve --port 8013 --public-host avysta.design.cpq.experlogixlocal.com

### Please provide the environment you discovered this bug in

```true
Angular CLI: 13.0.1
Node: 16.13.0
Package Manager: yarn 1.22.15
Angular: 13.0.0
OS: Windows 10 x64
```

**Comment by alan-agius4** [comment]
This is expected because by default in version 13 caching is enabled. `node_modules` are considered as immutable unless the version in the `package.json` changes.

For more information, see:
https://webpack.js.org/configuration/other-options/#cachemanagedpaths
https://webpack.js.org/configuration/other-options/#immutablepaths

To disable this behaviour you can opt disable caching. You can read more about this [here](https://angular.io/cli/cache#enabling-and-disabling-the-cache).

**Comment by alan-agius4** [comment]
To continue on the above, this will also be experiencing when disk cache is not enabled. This is because since Webpack 5, the memory cache also assumes that node_modules are immutable.

**Comment by mikerentmeister** [comment]
@alan-agius4 

I've done as you suggested, and updated my library to build and watch. I've also updated my application's tsconfig. to have this path when using ng serve.

tsconfig.app.dev.json
```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@experlogix/common": ["../experlogix-common/dist/common"]
    }
  }
}
```

Calling ng serve builds and runs, however, when I go to actually open the angular app is throws module injection errors. I know it's hard to repro without the source, but from these screenshots can you see anything that I would need to tweak by chance?

Error:
![image](https://user-images.githubusercontent.com/18708788/140547973-b8827316-f9d6-48cc-a6c7-d5c0c166db32.png)

Library dist folder (the consuming application path is "repos/experlogix-design-studio/"):
![image](https://user-images.githubusercontent.com/18708788/140553046-0b146bb1-eded-46d7-8702-8850d14ebd61.png)

Other Files from the consuming application:

tsconfig.app.json
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/app",
    "types": []
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "src/test.ts",
    "src/**/*.spec.ts"
  ]
}
```

tsconfig.json
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "suppressImplicitAnyIndexErrors": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "downlevelIteration": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ],
    "paths": {
      "jszip": [
        "node_modules/jszip/dist/jszip.min.js"
      ]
    }
  },
  "angularCompilerOptions": {
    "enableIvy": true
  }
}
```

angular.json
```
  "architect": {
	"build": {
	  "builder": "@angular-devkit/build-angular:browser",
	  "options": {
		...
		"tsConfig": "tsconfig.app.dev.json",
		"assets": [
		  {
			"glob": "**/*",
			"input": "node_modules/@experlogix/common/assets",
			"output": "./assets/"
		  }
		],
		"styles": [
		  "./node_modules/@experlogix/common/styles/material-theme.scss",
		  "./node_modules/@experlogix/common/styles/main.scss"
		],
		"scripts": [],
		"allowedCommonJsDependencies": [
		  "devextreme"
		],
		"optimization": false,
		"aot": false,
		"vendorChunk": true,
		"extractLicenses": false,
		"buildOptimizer": false,
		"sourceMap": true,
		"namedChunks": true
	  },
	  "configurations": {
		"production": {
		  ...
		  "tsConfig": "tsconfig.app.json"
		},
	  },
	  "defaultConfiguration": ""
	},
	"serve": {
	  "builder": "@angular-devkit/build-angular:dev-server",
	  "options": {
		"browserTarget": "exp-app-design-studio:build",
		"open": false,
		"host": "0.0.0.0",
		"port": 80
	  },
	  "configurations": {
		"production": {
		  "browserTarget": "exp-app-design-studio:build:production"
		},
		"es": {
		  "browserTarget": "exp-app-design-studio:build:es"
		},
		"nl": {
		  "browserTarget": "exp-app-design-studio:build:nl"
		}
	  }
	}
  }
```

**Comment by alan-agius4** [comment]
The problem above is that you are using deep imports which are not valid when importing from a library.

The imports should be updated to import directly from the primary entry-point `@experlogix/common`.

**Comment by mikerentmeister** [comment]
@alan-agius4 - I have done as you pointed out, and change all imports to "@experlogix/common". Everything now builds and runs. However, even when doing "ng build --watch" on the library, and configuring the tsconfig paths to point to the libraries dist folder, ng serve is still not being detecting changes that occur to the library dist folder.
