### ISSUE TITLE
Angular 13 upgrade (Module build failed)

### ISSUE THREAD

**Issue by dean-g** [angular/angular-cli#22105]
### Which @angular/* package(s) are the source of the bug?

upgrade

### Is this a regression?

No

### Description

I am getting the following error with an upgrade. 

HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use '~@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Can you please check this and advise?

**Comment by alan-agius4** [comment]
The syntax should been migrated to `@use '@angular/material' as mat`.

Did you update `@angular/material` using `ng update`?

**Comment by dean-g** [comment]
Yeah. I used the ng update. thanks for the response. I am fixing it manually now!

**Comment by dean-g** [comment]
it worked!. thanks a lot!
