### ISSUE TITLE
When moving to Angular v9, icomoon fonts are loaded as weird symbols

### ISSUE THREAD

**Issue by Ronnysi** [angular/angular-cli#22110]
# 🐞 Bug report

### Command (mark with an `x`)

- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.14

### Description
Since upgrading our Angular version 8.214->9.1.13, some users (feels very randomly) are getting corrupted icons instead of our icomoon icons (set in the icon "content" property): 
![image](https://user-images.githubusercontent.com/63007691/140644664-c97f4c51-5c22-4205-9112-9d084baf8c40.png)
 
After clearing the cache, and sometimes after changing screen resolution - the problem is fixed. 

## 🔬 Minimal Reproduction
Couldn't repro, happen very randomly. 

## 🔥 Exception or Error
No exceptions. 

## 🌍 Your Environment

<pre><code>

Angular CLI: 9.1.15
Node: 14.17.1
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cdk                      9.2.0
@angular/cli                      9.1.15
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.6.7
typescript                        3.8.3
webpack                           4.43.0

</code></pre>

**Anything else relevant?**
* We suspect it has to do with Chromium, but since it's so random we are not sure...
* Looks like the same issue is described in: https://stackoverflow.com/questions/60659338/content-of-custom-icon-font-in-angular-is-a-strange-string/69872042#69872042

**Comment by alan-agius4** [comment]
Hi @Ronnysi,

A lot has changed since version 9 can you please update to a more recent version? The current latest stable version is 13.0.1.

Version 9 is also no longer supported. Please see https://angular.io/guide/releases#support-policy-and-schedule for more information about our support policy.
