### ISSUE TITLE
Can not run ng command after upgrading to v13

### ISSUE THREAD

**Issue by 123NeNaD** [angular/angular-cli#22114]
After I upgraded Angular CLI to v13, I can not run any "ng" command. Environment is Windows 10, and IDE is VS Code. I can not even run `ng v`. I tried both Command Prompt and PowerShell. I got the following message:

![image](https://user-images.githubusercontent.com/61844304/140704823-2988e9d9-0f21-4ec4-95be-6869f20966b7.png)
:

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
