### ISSUE TITLE
CLI Crashed!!!

### ISSUE THREAD

**Issue by kenkage** [angular/angular-cli#22126]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
I tried to run the project using the following command.
compilation code - node --max_old_space_size=11264 ./node_modules/@angular/cli/bin/ng serve --base-href /ui/

## 🔥 Exception or Error

<pre><code>

Assertion `!(n > 0) || (ret != nullptr)' failed.
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 9.1.15
Node: 14.17.3
OS: win32 ia32

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: No

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cdk                      9.2.4
@angular/cli                      9.1.15
@angular/material                 9.2.4
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.5.3
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @kenkage,

This seems to be a Node.js issue, please try to re-install Node.js.

Kindly note, that Angular version 9 is no longer supported. See https://angular.io/guide/releases#support-policy-and-schedule for more information.

**Comment by kenkage** [comment]
Hi @alan-agius4,

Thanks much for the suggestion. It got resolved by downgrading the Node.js version to 14.15.1.
