### ISSUE TITLE
Problem with build library package

### ISSUE THREAD

**Issue by Obliczeniowo** [angular/angular-cli#22129]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I have problem with build my library made in angular 12 and upgrade to angular 13

I know this is related to **package.json:** file of sub package:

```
{
  "ngPackage": {
    "lib": {
      "entryFile": "public-api.ts",
      "umdModuleIds": {
        "@angular/common": "@angular/common",
        "@angular/core": "@angular/core"
      }
    }
  },
  "dependencies": {
    "tslib": "^2.0.0"
  }
}
```

### Please provide the exception or error you saw

```true
Configuration doesn't match the required schema.
Data path "/lib" must NOT have additional properties (umdModuleIds).
```
```


### Please provide the environment you discovered this bug in

```true
Angular cli 13
```

**Comment by petebacondarwin** [comment]
This sounds like a problem with how ng-packagr has been configured.

**Comment by clydin** [comment]
As noted above, the `umdModuleIds` is not a valid option when using v13 as UMD files are no longer generated during builds.  The update process should executed a migration to removed the option.  Was the project updated to v13 via the `ng update` command?

**Comment by alan-agius4** [comment]
The migration doesn’t handle ng-packagr configurations in `package.json`.

We should fix this and we should also deprecate such configurations. The `package.json` isn’t the right place to configure tools.

**Comment by Obliczeniowo** [comment]
hm I try solution like:

```
{
  "entryFile": "public-api.ts",
  "perDependences": {
    "@angular/common": "@angular/common",
    "@angular/core": "@angular/core"
  },
  "dependencies": {
    "tslib": "^2.0.0"
  }
}
```

but then it's build in incorrect way

Can you point me how correctly update library with multiple entry points?

**Comment by Obliczeniowo** [comment]
> 
> 
> As noted above, the `umdModuleIds` is not a valid option when using v13 as UMD files are no longer generated during builds. The update process should have executed a migration to removed the option. Was the project updated to v13 via the `ng update` command?

I use:

`npx @angular/cli@13 update @angular/core@13 @angular/cli@13`
