### ISSUE TITLE
Support non optimizing ng serve

### ISSUE THREAD

**Issue by Ottunger** [angular/angular-cli#22136]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

`ng serve` does not support anymore to NOT optimize the built js files. While this already wasn't present using `angular.json` in ng12, one could use `ng serve --optimization=false`, but this option is no more available.
This not only makes it much easier to debug (stacktraces are complete rather than `on a.eT()`), but also makes build time faster.

PS: the option `--source-map=false` is also gone.

### Describe the solution you'd like

Be able to set `optimization=false` in `angular.json` for builds of type `dev-server`.

### Describe alternatives you've considered

To regain speed of build, all we can play with for now is ES target and build cache. This is not as of great benefit as disable optimization.

**Comment by clydin** [comment]
A newly generated project will have the `serve` target setup to use the `development` configuration of the `build` target.  This, in turn, will be setup to not use optimization for the project by default.
<details>
  <summary>Default Serve Target</summary>

  ```json
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "new-v13:build:production"
            },
            "development": {
              "browserTarget": "new-v13:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
  ```

</details>

<details>
  <summary>Default Build Development Configuration</summary>

  ```json
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
  ```

</details>

If your project is not serving a development build, please review the build and serve configurations for the project based on the settings shown above.

**Comment by Ottunger** [comment]
Hi there,

Thanks, it works for me!
Do you know when the change was made in config? It may be worth include in an upgrade guide.

Best

**Comment by clydin** [comment]
These changes were made in version 12 and an automatic migration when using `ng update` was included with the release.  Please note, however, that the use of third-party builders may prevent migrations from successfully completing.
