### ISSUE TITLE
Node-modules\@ionic-native\network\index.js depends on ‘rxjs/add/observable/merge’. CommonJS or AMD dependencies can cause optimization bailouts

### ISSUE THREAD

**Issue by Sureshc32** [angular/angular-cli#22144]
node modules\ @ionic-native\network\index.js depends on ‘rxjs/add/observable/merge’. CommonJS or AMD dependencies can cause optimization bailouts.

How to overcome this issue?
I am getting this issue on upgrade to Angular 10. Any suggestions?

Placing like this in angular.json clears warning message but How to resolve the actual issue.
“build”: {
“builder”: “@angular-devkit/build-angular:browser”,
“options”: {
“allowedCommonJsDependencies”: [
“rxjs/add/observable/merge”
]

**Comment by Sureshc32** [comment]
@angular-jira-bot @shlangus

**Comment by Sureshc32** [comment]
@mgechev Hi Sir could you help out me with this issue.

**Comment by alan-agius4** [comment]
@Sureshc32, this seems to be an issue with Ionic, but my guess would be to update the latest stable version.
