### ISSUE TITLE
[Angular 13] persistent build cache is dependent on absolute folder path of the project

### ISSUE THREAD

**Issue by Hypocrissy** [angular/angular-cli#22146]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

- When any parent folder of a project is renamed, the angular persistent build cache is recreated and will no longer use any "old" data
- This makes the cache basically non-existent in any CI scenario where the workspace folder is generated on demand (e.g. DroneCI on Windows)

## 🔬 Minimal Reproduction

- Folder: **C:\angular**
- ng new app
- ng build 
<pre>Build at: 2021-11-11T15:53:43.980Z - Hash: d4f16607c301d89a - Time: 16540ms</pre>
- ng build 
<pre>Build at: 2021-11-11T15:53:59.406Z - Hash: d4f16607c301d89a - Time: 4076ms</pre>
- Rename: **C:\angular** --> **C:\angular2**
- ng build 
<pre>Build at: 2021-11-11T15:55:55.631Z - Hash: d4f16607c301d89a - Time: 13954ms</pre>
- ng build 
<pre>Build at: 2021-11-11T15:56:08.950Z - Hash: d4f16607c301d89a - Time: 4124ms</pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.2
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
While, I am not familiar with DroneCI, CIs typically offer ways to always checkout code to the same path, at least this was always the case for the CIs providers I used (Circle, BuildKite, CodeFresh, Travis, AppVeyor and Team City).

I am sorry but, this is not something that we can action ourselves, since Webpack which is used to bundle apps and Rollup which is used to bundle libs both take into account paths.
