### ISSUE TITLE
Angular 13 build fails in webpack-sources - Maximum call stack size exceeded

### ISSUE THREAD

**Issue by thre3eye** [angular/angular-cli#22156]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No issues in Angular 12

### Description

Augular 13 builds break with sourceMap=true.
This has been discussed with quite some detail in the webpack-sources repo and seems to affect in particular Angular 13.

https://github.com/webpack/webpack-sources/issues/131

Stack trace below

## 🔬 Minimal Reproduction

Please see the discussion in the webpack-sources repo https://github.com/webpack/webpack-sources/issues/131

## 🔥 Exception or Error

<pre><code>
<e> [webpack-dev-middleware] HookWebpackError: Maximum call stack size exceeded
<e>     at makeWebpackError (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack\lib\HookWebpackError.js:48:9)
<e>     at C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack\lib\Compilation.js:3043:12
<e>     at eval (eval at create (C:\Dev\workspace\myapp\myapp-web-13\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:111:1)
<e>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
<e> -- inner error --
<e> RangeError: Maximum call stack size exceeded
<e>     at String.match (<anonymous>)
<e>     at OriginalSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\OriginalSource.js:64:32)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at ReplaceSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\ReplaceSource.js:175:44)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at streamAndGetSourceAndMap (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamAndGetSourceAndMap.js:27:53)
<e>     at CachedSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\CachedSource.js:208:35)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at ConcatSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at streamAndGetSourceAndMap (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamAndGetSourceAndMap.js:27:53)
<e>     at CachedSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\CachedSource.js:208:35)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at ConcatSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
<e> caused by plugins in Compilation.hooks.processAssets
<e> RangeError: Maximum call stack size exceeded
<e>     at String.match (<anonymous>)
<e>     at OriginalSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\OriginalSource.js:64:32)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at ReplaceSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\ReplaceSource.js:175:44)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at streamAndGetSourceAndMap (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamAndGetSourceAndMap.js:27:53)
<e>     at CachedSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\CachedSource.js:208:35)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at ReplaceSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\ReplaceSource.js:175:44)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at ConcatSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at streamAndGetSourceAndMap (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamAndGetSourceAndMap.js:27:53)
<e>     at CachedSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\CachedSource.js:208:35)
<e>     at module.exports (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\helpers\streamChunks.js:13:17)
<e>     at ConcatSource.streamChunks (C:\Dev\workspace\myapp\myapp-web-13\node_modules\webpack-sources\lib\ConcatSource.js:112:55)
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.2
Node: 16.13.0
Package Manager: npm 8.1.3
OS: win32 x64

Angular: 13.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            6.6.7
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @thre3eye,

Thanks for this issue.

But, based on the conversations going on in https://github.com/webpack/webpack-sources/issues/131 it seems that this is a `webpack-sources` bug and hence it is not actionable from our end.

**Comment by thre3eye** [comment]
Yes, thankfully my workaround hack seems to have helped identifying the issue and they are on it. Thanks for checking.
