### ISSUE TITLE
Error when trying to use any ng functions (like ng new X for example)

### ISSUE THREAD

**Issue by JoseRox** [angular/angular-cli#2216]
> Please provide us with the following information:
> ---------------------------------------------------------------

Mac OSX El Capitan.
node --version
v4.5.0
npm --version
2.15.9

I installed angular cli globally and I received this error, its happening with all ng functions, I cannot create a new project using ng.
please help.

ng --version / ng new PROG
fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Function.Version.fromProject (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:87:31)
    at Function.Version.isPreWebpack (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:111:31)
    at Function.Version.assertPostWebpackVersion (/usr/local/lib/node_modules/angular-cli/upgrade/version.js:97:18)
    at /usr/local/lib/node_modules/angular-cli/bin/ng:25:15
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:44:21
    at ondir (/usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:187:31)
    at /usr/local/lib/node_modules/angular-cli/node_modules/resolve/lib/async.js:153:39

**Comment by bohms27** [comment]
Having same issue

**Comment by bohms27** [comment]
Do you also have it installed locally? I had it installed globally and locally and received the error. Uninstalled the local version in the folder and it worked fine.

**Comment by JoseRox** [comment]
I created a new folder and tried to sudo ng new PROG....
do you create a package.json? before the new?

**Comment by bohms27** [comment]
Nope I didn't have it created before

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli#prerequisites

You need at least npm3 to run the CLI. I suggest installing Node 6 which comes with npm 3.

**Comment by adesugbaa** [comment]
I have npm3 and node 5/6. It gives the same errors above.

**Comment by JoseRox** [comment]
I installed the prerequisites,  latests npm and node (tried with all available versions).

**Comment by tamdao** [comment]
I have npm 3.x and node 6.x. But I have the same issue

**Comment by jsight** [comment]
@filipesilva - I have npm 3.10.8 and have the same issue. Maybe this project just doesn't work on Node 4.5?

**Comment by sebge23** [comment]
I have the same issue and i found this question on stackoverflow.

http://stackoverflow.com/questions/39541930/error-while-creating-new-project-with-angular-cli#comment66616273_39541930

**Comment by micahchiang** [comment]
This issue is not resolved. I get the same errors on node v6.60 and npm 3.10.3. Have tried everything suggested here.

**Comment by jsight** [comment]
Workaround: https://github.com/angular/angular-cli/pull/2355

**Comment by PsychoSpike** [comment]
I was having the same issue.
Uninstalled and reinstalled global angular-cli, no change.

**Not sure if it'll help you but**:
I'm in the habit of creating projects in one projectfolder, containing different angular trial projects.
After changing my projectfolder to a brandspanking new projectfolder, generating projects in there was possible again.

Somehow my old projectfolder had a node_modules folder. Could it be that was messing this up?

**Comment by vadost** [comment]
Simplest workaround to continue working in your project is comment line 25 of node_modules/angular-cli/bin/ng :
// Version.assertPostWebpackVersion();
Until it is fixed properly.

**Comment by filipesilva** [comment]
Really fixed in https://github.com/angular/angular-cli/pull/2178
