### ISSUE TITLE
Reconsidering the deprecation (and removal) of deployUrl

### ISSUE THREAD

**Issue by mpalourdio** [angular/angular-cli#22164]
Hello,

I'm opening this issue about the deprecation, and soon removal, of the `deployUrl` support.

I have make a quick [explanation](https://github.com/angular/angular-cli/issues/22113#issuecomment-964125948) on how it will impact us. We have tested the mix of `baseHref` and `APP_BASE_HREF` which will not work in our case.

Also, I just cannot see how one would handle the possibility to deploy generated scripts, css, and assets on CDN, like it's possible today. Or using a reverse proxy to serve scripts, like we're doing today.

My question is, would it possible to keep this optional, or is the removal definitive ? And apart using `APP_BASE_HREF` (which does not suit all the needs), how could implement suck a feature if we accept the penality of build time.

I can understand the need of removal this feature, but I hope we could find a durable alternative.

Thanks, and keep up the awesome work.

**Comment by alan-agius4** [comment]
@mpalourdio, lets continue tracking this subject in https://github.com/angular/angular-cli/issues/22113#issuecomment-964125948.

**Comment by mpalourdio** [comment]
good, closing now !
