### ISSUE TITLE
v13 modern namespace eslint error in `src/test.ts`

### ISSUE THREAD

**Issue by twerske** [angular/angular-cli#22171]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Sort of, new lint error introduced in the `ng update` or `ng new` in v13.

```
declare const require: {
  context(path: string, deep?: boolean, filter?: RegExp): {
    keys(): string[];
    <T>(id: string): T;
  };
};
```

should be 

```
declare const require: {
  context(path: string, deep?: boolean, filter?: RegExp): {
    <T>(id: string): T;
    keys(): string[];
  };
};
```

**Comment by alan-agius4** [comment]
Hi @twerske, 

I am unable to replicate the above with the below configuration, do you have custom rules enabled?


```json
{
  "root": true,
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking"
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "project": "tsconfig.json",
    "sourceType": "module"
  }
}
```

When updating to a new Eslint version during `ng update` I think it's faire to expected that there are new lint failures, but most of these should be able to be fixable by using the Eslint fixers which can be triggered using the [`--fix` ](https://eslint.org/docs/user-guide/command-line-interface#--fix) argument. 

It's also worth mentioned that the Eslint builder is not supported by the Angular team.

**Comment by twerske** [comment]
If you `ng new` a new project with the CLI in v13 in the `test.ts` file there's a lint error for the order of variable declarations where these two should be switched:

```
    keys(): string[];
    <T>(id: string): T;
```

to:

```
    <T>(id: string): T;
    keys(): string[];
```

 I think it's fair to expect that we update the `ng new` generated code to swap these two values since it's a quick fix and helps not introduce a lint error for new developers, but I'll leave it to the team if it's worth including in the migration (probably not since I agree that updating can introduce new lint errors)
