### ISSUE TITLE
ng generate does not accept schematic options of type "object"

### ISSUE THREAD

**Issue by jesusreal** [angular/angular-cli#22173]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

### Description

 
Given a custom schematic called `my-test-schematic` with its schema defining an `object` type, as for example the `localize` property below:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "MyTestSchematicsSchema",
  "title": "My test schematics Schema",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "localize": {
      "description": "Provide locale, localeFile to add it as an additional output of the application.",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "locale": {
          "type": "string",
          "title": "Single locale to use (besides the default)"
        },
        "localeFile": {
          "type": "string",
          "title": "Single locale file matching the given locale"
        }
      }
    }
  }
}
```

Running such schematic with `ng generate` command
```bash 
ng g ./dist/libs/schematics/collection.json:my-test-schematic --localize.locale=de
```
Produces the following error:
```
Unknown option: '--localize.locale'
```
 
Running the schematic with [`schematics`](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/schematics_cli) command
```bash 
schematics ./dist/libs/schematics/collection.json:my-test-schematic --localize.locale=de
```
The option is passed to the schematic:
```
My test schematic: {"localize":{"locale":"de"}}
```

I would expect `ng generate` to support schematic options of type `object`, the same way `schematics` does. [Here](https://github.com/angular/angular-cli/blob/master/packages/angular/cli/models/parser.ts#L238) is where extraction happens for `ng generate`, and [here](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/schematics_cli/bin/schematics.ts#L251) for `schematics`.

## 🔬 Minimal Reproduction

I created a public repository [here](https://github.com/jesusreal/angular-schematics-playground) that allows to reproduce the issue. All the relevant information is in the readme file.

## 🔥 Exception or Error

When running the schematic with `ng generate` command
<pre><code>

Unknown option: '--localize.locale'
</code></pre>

When running the schematic with `schematics` command, the option is properly passed to the schematic

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.3
Node: 14.17.6
Package Manager: npm 6.14.15
OS: darwin x64

Angular: <error>
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.3 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@angular/cli                    12.1.3 (cli-only)
@schematics/angular             12.1.3 (cli-only)
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**
No

**Comment by alan-agius4** [comment]
This is expected, the command line parser of the Angular CLI doesn’t expand properties with dots into objects. I am actually surprised that this work in the schematics CLI.

In a future major version we will be looking into using a common parser for all of the CLIs so that the parsing of arguments is consistent across the board. That said, it’s not very likely that the object expansion would be something that we’d want to allow.
