### ISSUE TITLE
v13 ng update only adds `.angular/.cache` not `.angular` to `.gitignore`

### ISSUE THREAD

**Issue by twerske** [angular/angular-cli#22170]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

`ng update` introduces caching files and the `.angular` file and in updating we only ignore the `.angular/.cache/` which may lead to people checking in many empty `.angular` folders by mistake. I think we shoud change the .gitignore to `.angular`

**Comment by alan-agius4** [comment]
This is intended, in future we may want to place files in `.angular` not related to caching, which we’d want people to check in.

Moreover, git doesn’t recognize and therefore doesn’t allow checking in empty directories unless a `.gitkeep` file is present, which is not in his case.

**Comment by alan-agius4** [comment]
Closing as per above explanation.
