### ISSUE TITLE
Installation fails with error code 1

### ISSUE THREAD

**Issue by lekhnath** [angular/angular-cli#2217]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

**Ubuntu 13.10**

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

**node v4.4.0
npm v3.10.5**

3. The log given by the failure. Normally this include a stack trace and some
   more information.

npm i angular-cli -g
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/home/lekhnath/.nvm/v4.4.0/bin/ng -> /home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/bin/ng

> execSync@1.0.2 install /home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> node-zopfli@1.4.0 install /home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.4.0 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:196,
                 from ../src/zopfli-binding.h:5,
                 from ../src/zopfli-binding.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:99:67: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
                                                                   ^
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::FunctionTemplate>::return_t Nan::imp::Factory<v8::FunctionTemplate>::New(Nan::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>)’:
../../nan/nan_implementation_12_inl.h:127:69: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
                                                                     ^
In file included from ../src/zopfli-binding.h:5:0,
                 from ../src/zopfli-binding.cc:3:
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../../nan/nan.h:1926:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:1931:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../../nan/nan.h:1969:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:1978:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h: In function ‘void Nan::SetNamedPropertyHandler(v8::Local<v8::ObjectTemplate>, Nan::PropertyGetterCallback, Nan::PropertySetterCallback, Nan::PropertyQueryCallback, Nan::PropertyDeleterCallback, Nan::PropertyEnumeratorCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2027:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:2032:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h:2038:57: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(query)));
                                                         ^
../../nan/nan.h:2044:59: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(deleter)));
                                                           ^
../../nan/nan.h:2050:62: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(enumerator)));
                                                              ^
../../nan/nan.h: In function ‘void Nan::SetIndexedPropertyHandler(v8::Local<v8::ObjectTemplate>, Nan::IndexGetterCallback, Nan::IndexSetterCallback, Nan::IndexQueryCallback, Nan::IndexDeleterCallback, Nan::IndexEnumeratorCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2097:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:2102:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h:2108:57: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(query)));
                                                         ^
../../nan/nan.h:2114:59: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(deleter)));
                                                           ^
../../nan/nan.h:2120:62: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(enumerator)));
                                                              ^
../../nan/nan.h: In function ‘void Nan::SetCallHandler(v8::Local<v8::FunctionTemplate>, Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2153:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(callback)));
                                                          ^
../../nan/nan.h: In function ‘void Nan::SetCallAsFunctionHandler(v8::Local<v8::ObjectTemplate>, Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2175:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(callback)));
                                                          ^
  CXX(target) Release/obj.target/zopfli/src/png/zopflipng.o
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:196,
                 from ../src/png/zopflipng.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan_implementation_12_inl.h:99:67: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
                                                                   ^
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::FunctionTemplate>::return_t Nan::imp::Factory<v8::FunctionTemplate>::New(Nan::FunctionCallback, v8::Local<v8::Value>, v8::Local<v8::Signature>)’:
../../nan/nan_implementation_12_inl.h:127:69: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , v8::External::New(isolate, reinterpret_cast<void *>(callback)));
                                                                     ^
In file included from ../src/png/zopflipng.cc:3:0:
../../nan/nan.h: In function ‘void Nan::SetAccessor(v8::Local<v8::ObjectTemplate>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute, Nan::imp::Sig)’:
../../nan/nan.h:1926:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:1931:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../../nan/nan.h:1969:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:1978:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h: In function ‘void Nan::SetNamedPropertyHandler(v8::Local<v8::ObjectTemplate>, Nan::PropertyGetterCallback, Nan::PropertySetterCallback, Nan::PropertyQueryCallback, Nan::PropertyDeleterCallback, Nan::PropertyEnumeratorCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2027:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:2032:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h:2038:57: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(query)));
                                                         ^
../../nan/nan.h:2044:59: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(deleter)));
                                                           ^
../../nan/nan.h:2050:62: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(enumerator)));
                                                              ^
../../nan/nan.h: In function ‘void Nan::SetIndexedPropertyHandler(v8::Local<v8::ObjectTemplate>, Nan::IndexGetterCallback, Nan::IndexSetterCallback, Nan::IndexQueryCallback, Nan::IndexDeleterCallback, Nan::IndexEnumeratorCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2097:56: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(getter)));
                                                        ^
../../nan/nan.h:2102:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(setter)));
                                                          ^
../../nan/nan.h:2108:57: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(query)));
                                                         ^
../../nan/nan.h:2114:59: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(deleter)));
                                                           ^
../../nan/nan.h:2120:62: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
       , New<v8::External>(reinterpret_cast<void *>(enumerator)));
                                                              ^
../../nan/nan.h: In function ‘void Nan::SetCallHandler(v8::Local<v8::FunctionTemplate>, Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2153:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(callback)));
                                                          ^
../../nan/nan.h: In function ‘void Nan::SetCallAsFunctionHandler(v8::Local<v8::ObjectTemplate>, Nan::FunctionCallback, v8::Local<v8::Value>)’:
../../nan/nan.h:2175:58: warning: ISO C++ forbids casting between pointer-to-function and pointer-to-object [enabled by default]
     , New<v8::External>(reinterpret_cast<void *>(callback)));
                                                          ^
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/cache.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/deflate.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/gzip_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/hash.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/katajainen.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/lz77.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/squeeze.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/tree.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/util.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zlib_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zopfli_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/zopflipng_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng_util.o
  SOLINK_MODULE(target) Release/obj.target/zopfli.node
  COPY Release/zopfli.node
  COPY /home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/node-zopfli/build'

> node-sass@3.10.0 install /home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/linux-x64-46_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.10.0/linux-x64-46_binding.node": ode:

ESOCKETTIMEDOUT

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g. 

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.10.0 postinstall /home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/build.js

"/home/lekhnath/.nvm/v4.4.0/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-46/binding.node" exists. 
 testing binary.
Bus error
/home/lekhnath/.nvm/v4.4.0/lib
└── (empty)

npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN string-replace-loader@1.0.4 requires a peer of webpack@1.x.x || 2.x.x || 2.x.x-beta but none was installed.
npm ERR! Linux 3.11.0-26-generic
npm ERR! argv "/home/lekhnath/.nvm/v4.4.0/bin/node" "/home/lekhnath/.nvm/v4.4.0/bin/npm" "i" "angular-cli" "-g"
npm ERR! node v4.4.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.10.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@3.10.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lekhnath/Documents/npm-debug.log
npm ERR! code 1

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jbeckton** [comment]
try sudo install ...

**Comment by lekhnath** [comment]
@jbeckton Its not going to help, as I've installed node and npm in my home directory, so no sudo is required.

**Comment by DILEEP-YADAV** [comment]
Same issue ! Angular CLI not supporting on my core 2 dual processor or  windows 7 System.

**Comment by n37r06u3** [comment]
Same issue ! Angular CLI not supporting on my windows10 64bit System

**Comment by filipesilva** [comment]
Seems to related to node-sass:
```
npm ERR! node-sass@3.10.0 postinstall: node scripts/build.js
npm ERR! Exit status 135
npm ERR! 
npm ERR! Failed at the node-sass@3.10.0 postinstall script 'node scripts/build.js'.
```

If you still get this with the latest CLI versions, please open an issue in https://github.com/sass/node-sass.
