### ISSUE TITLE
Allow customization of webpack config

### ISSUE THREAD

**Issue by girishla** [angular/angular-cli#2219]
Firstly, thanks to all the contributors for the excellent work on this repo.

I just wanted to find out if there is a plan to allow customization to webpack config files (Unless its already possible and I haven't figured out how to) ?

Many thanks.

**Comment by mchambaud** [comment]
Clone of [ISSUE 1656](https://github.com/angular/angular-cli/issues/1656)

**Comment by girishla** [comment]
thanks @mchambaud. Closing.
