### ISSUE TITLE
installation freeze at extract

### ISSUE THREAD

**Issue by vaurelios** [angular/angular-cli#2220]
1. OS?  **ArchLinux** up-to-date.

2. Versions.

```sh
~ node --version
v6.5.0
```

3. Repro steps. Issue in the terminal:

```sh
npm install -g angular-cli@webpack
```

4. The log given by the failure. 

```
~ sudo npm install -g angular-cli
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[             .....] | extract:angular-cli: sill doParallel extract 1192
```

5. Mention any other details that might be useful.

The installation stuck at this part, past hours and no change, heavily using CPU.

**Comment by xxxtonixxx** [comment]
I'm having same problem. My OS is Manjaro 16.08 (latest) and it's up-to-date too.
NPM: 3.10.7
NodeJS: 6.5.0

**Comment by xxxtonixxx** [comment]
@vaurelios I could install it with`nodejs 6.3.1` and `npm 3.10.1`. I did change version of node and npm with `n`. However, Angular-cli must not fail with 6.5.0, I think so...

I did use this command: `n 6.3.1`

I hope this helps :+1:

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1932
