### ISSUE TITLE
Vulnerability in @angular-devkit/build-angular@0.901.15

### ISSUE THREAD

**Issue by AlexeyGrigorievBoost** [angular/angular-cli#22206]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

@angular-devkit/build-angular@0.901.15 has a vulnerable dependency of glob-parent prior 5.1.2
```
└─┬ @angular-devkit/build-angular@0.901.15
  ├─┬ copy-webpack-plugin@6.0.3
  │ ├─┬ fast-glob@3.2.7
  │ │ └── glob-parent@5.1.2  deduped
  │ └── glob-parent@5.1.2 
  ├─┬ sass@1.26.3
  │ └─┬ chokidar@3.5.2
  │   └── glob-parent@5.1.2  deduped
  ├─┬ webpack@4.42.0
  │ └─┬ watchpack@1.7.5
  │   └─┬ watchpack-chokidar2@2.0.1
  │     └─┬ chokidar@2.1.8
  │       └── glob-parent@3.1.0 
  └─┬ webpack-dev-server@3.11.0
    └─┬ chokidar@2.1.8
      └── glob-parent@3.1.0
 ```
We have security scan failed because of [this problem ](https://github.com/advisories/GHSA-ww39-953v-wcq6) and we cannot update our app to the latest version of Angular
because of backward compatibility issues of a component framework that we're using.

Can all versions of glob-parent be updated to >=5.1.2 and released in the next version (@angular-devkit/build-angular@0.901.16)?

**Comment by alan-agius4** [comment]
Angular 9 is no longer supported. 

For more information about our support policy please see: https://angular.io/guide/releases#support-policy-and-schedule
