### ISSUE TITLE
Build fails Angular 13 warning: Expected identifier but found "*"

### ISSUE THREAD

**Issue by nolafs** [angular/angular-cli#22218]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Since 13 upgrade

### Description

Production build is failing. Development build is fine.

Warning:  > styles.2a3c9e1343ba4227.css:11601:2: warning: Expected identifier but found "*"
    11601 │   *display: inline;
          ╵   ^

## 🔬 Minimal Reproduction

Running ng build --prod

## 🔥 Exception or Error

<pre><code>
Warning:  > styles.2a3c9e1343ba4227.css:11601:2: warning: Expected identifier but found "*"
    11601 │   *display: inline;
          ╵   ^
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.2
Node: 14.15.5
Package Manager: npm 7.16.0
OS: darwin x64

Angular: 13.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@angular/fire                   7.2.0
@nguniversal/builders           13.0.1
@nguniversal/express-engine     13.0.1
@schematics/angular             13.0.2
ng-packagr                      13.0.3
rxjs                            7.4.0
typescript                      4.4.4
    
</code></pre>

**Comment by jkyoutsey** [comment]
I've found the same thing. I have some 3rd party ancient dependencies (like pure css) that have CSS selectors like:
`*width: ...` These are the source of these warnings. But I'm having a hard time figuring out what that * even means and I would be safe modifying these old CSS files.

**Comment by jkyoutsey** [comment]
Oh, and the build shouldn't be failing. These are warnings, not errors.
FYI, here is the explanation of the * before the property. It's all IE related, so, probably safe to delete rules with non-alphanumeric leading characters.

https://stackoverflow.com/questions/1690642/purpose-of-asterisk-before-a-css-property

**Comment by rsenoron** [comment]
We encountered this problemm too. Any solution?

**Comment by doover** [comment]
Can confirm I'm seeing this problem.

Warning: ▲ [WARNING] Expected identifier but found "*"

    styles.ba2b87a7234eee82.css:29979:2690:
      29979 │ ..._desc_disabled{cursor:pointer;*cursor:hand;background-repeat...

the problem is I can't find the file styles.ba2b87a7234eee82.css anywhere on my machine and if it is a compiled file, I can't figure out how it is generating it since I don't have any styles with "_desc_disabled" in the name.

**Comment by YurchenkoAndrew** [comment]
After updating the project from version 12 to version 13, when building the project, I also get  [WARNING] Expected identifier but found "*"
 styles.9e3a05709d44b4a0.css:4203:2:
      4203 │   *display: inline;
           ╵   ^

**Comment by m12lrpv** [comment]
I would also like to know how to resolve this. The first fix that is needed is to correctly identify the source file that contains this css element.

In my case i'm getting 
Warning: ▲ [WARNING] Expected identifier but found "*"

    styles.css:40:2:
      40 │   *zoom: 1;
         ╵   ^
and 

Warning: ▲ [WARNING] Expected identifier but found "*"

    styles.css:132:2:
      132 │   *zoom: 1;

But *zoom doesn't exist anywhere in my codebase nor my css so I cannot remove it. Angular cli is seeing it somewhere but where that location is is a mystery.
