### ISSUE TITLE
Angular 13 CLI not stopping after ctrl + c

### ISSUE THREAD

**Issue by danielehrhardt** [angular/angular-cli#22216]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v 12

### Description
With Angular 13 i have on Windows and Mac the Problem that the ng:serve command does not stop after i press ctrl + c. 
After i press ctrl+c in the Terminal the Angular CLI still produce cli output. 

## 🔬 Minimal Reproduction
npm start
press ctrl+c or command+c
wait a bit and see the console output in the Terminal. 

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.2
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 13.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      8.3.29
@angular/cli                    13.0.2
@nguniversal/builders           13.0.1
@nguniversal/express-engine     13.0.1
@schematics/angular             13.0.2
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This is related/caused by https://github.com/sindresorhus/ora/issues/156 and unfortunately there is no easy way to address this.

**Comment by johannesnormannjensen** [comment]
Experiencing the same thing with both build and serve.

If I try to stop the process with Ctrl + c in `phase: setup` it looks like the process stopped until it suddenly reaches `phase: building`

**Comment by spock123** [comment]
Same issue here

**Comment by Th3CracKed** [comment]
Same issue with `ng serve `

**Comment by danielehrhardt** [comment]
Still present with Angular 14

**Comment by mpumford** [comment]
Not specific to windows. Happens with `ng serve` and `ng build` on linux as well (Ubuntu 18)

For a production build the delay can be quite long so this is more than irritating.
