### ISSUE TITLE
Cannot upgrade to typescript 4.5.2 because `@angular-devkit/build-angular` requires typescript 4.3

### ISSUE THREAD

**Issue by jackwootton** [angular/angular-cli#22215]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

Cannot update typescript to version 4.5.2 because @angular-devkit/build-angular depends on typescript 4.3.

## 🔬 Minimal Reproduction

Ensure `package.json` contains the following `devDependencies`

- `"@angular-devkit/build-angular": "^13.0.3"`
- `"typescript": "^4.4.4"`

Run `ng update typescript`.

## 🔥 Exception or Error

<pre><code>
Using package manager: 'npm'
Collecting installed dependencies...
Found 56 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires "~4.4.3", would install "4.5.2").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-3bfFIb/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.3
Node: 14.18.1
Package Manager: npm 8.1.3
OS: linux x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            12.2.11
@angular-devkit/schematics      12.2.11
@angular/cli                    13.0.3
@angular/fire                   7.2.0
@angular/flex-layout            12.0.0-beta.35
@schematics/angular             12.2.11
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This is working as expected TypeScript 4.5 is not yet supported.

We are aiming to it support it 13.1.

Subscribe to https://github.com/angular/angular/pull/44164 for more info.
