### ISSUE TITLE
GitHub Pages deploying with custom base url

### ISSUE THREAD

**Issue by aralroca** [angular/angular-cli#2222]
**1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)**

Mac OSX El Capitan

**2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:**

angular-cli: 1.0.0-beta.11-webpack.8
node: 6.4.0
os: darwin x64

**3. Mention any other details that might be useful.**

My problem is deploying to GitHub Pages using `ng github-pages:deploy`. 

The base url is always changing to `<base href="/projectname/">` by default. This base url is not correct when you are using a custom domain in your GitHub pages, should be `<base href="/">`, and it's annoying to change manually after the `ng github-pages:deploy` command.

My suggestion is to modify the command to specify the base url, like `ng github-pages:deploy:base:"/"`. And if is not specified use `/projectname/` by default.

**Comment by dzonatan** [comment]
Such feature already exists. 
Use the `--base-href` (alias -bh) option like:
`ng github-pages:deploy --base-href /`

**Comment by aralroca** [comment]
Oh, thank you!!!
