### ISSUE TITLE
Request failed \"406 Not Acceptable\""

### ISSUE THREAD

**Issue by v-yunbin** [angular/angular-cli#22228]
when  i  run "yarn" to install dependent package, get follows error:
```
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://saucelabs.com/downloads/sc-4.6.4-linux.tar.gz: Request failed \"406 Not Acceptable\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/software/angular-cli/yarn-error.log".
```

**Comment by alan-agius4** [comment]
This seems like a problem with your node/npm and not with Angular CLI.

Please have a look at the fixing [npm permissions page](https://docs.npmjs.com/getting-started/fixing-npm-permissions), [common errors page](https://docs.npmjs.com/troubleshooting/common-errors), [npm issue tracker](https://github.com/npm/npm/issues), or open a new issue in that issue tracker if the problem you are experiencing isn't known.

**Comment by v-yunbin** [comment]
@alan-agius4  `https://saucelabs.com/downloads/sc-4.6.4-linux.tar.gz` the file not exists, you can double verify it

**Comment by alan-agius4** [comment]
The file does exist.

**Comment by v-yunbin** [comment]
but i can not download it and view it through the url
