### ISSUE TITLE
Migrating from Angular 12.2.13 to Angular 13.0.2 Unsuccessful

### ISSUE THREAD

**Issue by benedict-chng** [angular/angular-cli#22229]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi,

I'm unable to migrate our existing application from Angular 12.2.13 to Angular 13.0.2. It is a moderately complex application and use the following command to do the migration as advised by on:

https://update.angular.io/?l=2&v=12.0-13.0

Has anyone seen this?

Rgds,
Benedict

### Please provide the exception or error you saw

```true
Microsoft Windows [Version 10.0.19043.1348]
(c) Microsoft Corporation. All rights reserved.

C:\angular_upgrade\Nova>npx @angular/cli@13 update @angular/core@13 @angular/cli@13
Using package manager: 'npm'
Collecting installed dependencies...
An unhandled exception occurred: Could not find package.json
See "C:\Users\BENEDI~1\AppData\Local\Temp\ng-F4zzJ2\angular-errors.log" for further details.

C:\angular_upgrade\Nova>cd Avatar

C:\angular_upgrade\Nova\Avatar>npx @angular/cli@13 update @angular/core@13 @angular/cli@13
Using package manager: 'npm'
Collecting installed dependencies...
Found 79 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.0.3" (was "12.2.13")...
    Updating package.json with dependency @angular/cli @ "13.0.3" (was "12.2.13")...
    Updating package.json with dependency @angular/compiler-cli @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/language-service @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency typescript @ "4.4.4" (was "4.3.5")...
    Updating package.json with dependency @angular/animations @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/common @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/compiler @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/core @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/forms @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/localize @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/platform-browser @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/router @ "13.0.2" (was "12.2.13")...
  UPDATE package.json (5301 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

> Remove polyfills required only for Internet Explorer which is no longer supported.
  UPDATE package.json (5267 bytes)
  UPDATE apps/snapp/src/polyfills.ts (2961 bytes)
  UPDATE apps/member/src/polyfills.ts (3053 bytes)
  UPDATE apps/staff/src/polyfills.ts (2961 bytes)
✔ Packages installed successfully.
  Migration completed.

> Remove no longer valid Angular schematic options from `angular.json`.
  Migration completed.

> Remove deprecated options from 'angular.json' that are no longer present in v13.
  UPDATE angular.json (29522 bytes)
  Migration completed.

> Updating '.gitignore' to include '.angular/cache'.
  UPDATE .gitignore (547 bytes)
  Migration completed.

> Update library projects to be published in partial mode and removed deprecated options from ng-packagr configuration.
  Migration completed.

** Executing migrations of package '@angular/core' **

> Migrates `[routerLink]=""` in templates to `[routerLink]="[]"` because these links are likely intended to route to the current page with updated fragment/query params.
× Migration failed: Cannot read property 'readWorkspace' of undefined
  See "C:\Users\BENEDI~1\AppData\Local\Temp\ng-0SNaUB\angular-errors.log" for further details.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
C:\Workspace\Nova\Avatar>ng version

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.13
Node: 14.18.1
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.13.10
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            7.3.10
@angular-devkit/schematics      12.2.13
@schematics/angular             12.2.13
rxjs                            6.5.5
typescript                      4.3.5


C:\Workspace\Nova\Avatar>
```

**Comment by UlrichFrancomme** [comment]
Hi @alan-agius4 

I have the same issue. 
I tried your commands but still have the same error.

**Comment by alan-agius4** [comment]
@UlrichFrancomme, in your case is the error the same as mentioned above?

**Comment by UlrichFrancomme** [comment]
Yes, it's the same error

**Comment by benedict-chng** [comment]
Hi @alan-agius4, this is still a problem for me even though I have updated most of my third-party libraries to the latest...

Hi @UlrichFrancomme, which library did you update that fixed the problem?

Rgds,
Benedict

**Comment by alan-agius4** [comment]
@benedict-chng and @UlrichFrancomme, can you kindly share the `package.json` prior to the update?
I tried to replicate this locale but I wasn't successful as the migration worked as expected. 

```
ng update @angular/cli@13 @angular/core@13
Using package manager: 'npm'
Collecting installed dependencies...
Found 23 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "13.0.3" (was "12.2.13")...
    Updating package.json with dependency @angular/cli @ "13.0.3" (was "12.2.13")...
    Updating package.json with dependency @angular/compiler-cli @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency typescript @ "4.4.4" (was "4.3.5")...
    Updating package.json with dependency @angular/animations @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/common @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/compiler @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/core @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/forms @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/platform-browser @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.0.2" (was "12.2.13")...
    Updating package.json with dependency @angular/router @ "13.0.2" (was "12.2.13")...
  UPDATE package.json (1072 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@angular/cli' **

❯ Remove polyfills required only for Internet Explorer which is no longer supported.
  UPDATE src/polyfills.ts (2340 bytes)
  Migration completed.

❯ Remove no longer valid Angular schematic options from `angular.json`.
  Migration completed.

❯ Remove deprecated options from 'angular.json' that are no longer present in v13.
  Migration completed.

❯ Updating '.gitignore' to include '.angular/cache'.
  UPDATE .gitignore (620 bytes)
  Migration completed.

❯ Update library projects to be published in partial mode and removed deprecated options from ng-packagr configuration.
  Migration completed.

** Executing migrations of package '@angular/core' **

❯ Migrates `[routerLink]=""` in templates to `[routerLink]="[]"` because these links are likely intended to route to the current page with updated fragment/query params.
  Migration completed.

❯ In Angular version 13, the `teardown` flag in `TestBed` will be enabled by default.
  This migration automatically opts out existing apps from the new teardown behavior.
  Migration completed.
```

**Comment by benedict-chng** [comment]
Hi @alan-agius4,

I attach my package.json for your reference.

Rgds,
Benedict
[package.json.zip](https://github.com/angular/angular-cli/files/7615953/package.json.zip)

**Comment by alan-agius4** [comment]
Thanks for sharing those. 

The problem appears to be that you have an additional Angular CLI installed which is very old. This is causing weird module hoisting. 

```
├── @angular/cli@13.0.3 
└─┬ @nrwl/builders@7.8.7
  └── @angular/cli@7.3.1 
```


What you can do is to install `@angular-devkit/core` which should rectify the hoisting issue. 
```
npm i @angular-devkit/core@13 --save
```

**NB:** post migration, remember to uninstall the mentioned package.

**Comment by benedict-chng** [comment]
Hi @alan-agius4,

Thanks for the tip, the migration to 13 went through successfully. Unfortunately when I try to `ng serve` it, I got the following error. I did uninstall @angular-devkit/core. I also attached the package.json and package-lock.json for your investigation.

An unhandled exception occurred: ENOENT: no such file or directory, lstat 'C:\Workspace\Nova\Avatar\node_modules\angular-archwizard\archwizard.css'
See "C:\Users\BENEDI~1\AppData\Local\Temp\ng-4vfjyR\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\windows\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! avatar@0.0.0 staff: `ng s --project staff --port 4200 --ssl`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the avatar@0.0.0 staff script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\benedictc\AppData\Roaming\npm-cache\_logs\2021-12-07T00_59_01_098Z-debug.log

The error for angular-errors.log:

[error] Error: ENOENT: no such file or directory, lstat 'C:\Workspace\Nova\Avatar\node_modules\angular-archwizard\archwizard.css'
    at Object.realpathSync (fs.js:1646:7)
    at resolveGlobalStyles (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js:53:31)
    at getStylesConfig (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\webpack\configs\styles.js:86:70)
    at C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:128:43
    at C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:72:16
    at generateWebpackConfig (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:61:40)
    at async generateBrowserWebpackConfigFromContext (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:123:20)
    at async generateI18nBrowserWebpackConfigFromContext (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\utils\webpack-browser-config.js:70:20)
    at async setup (C:\Workspace\Nova\Avatar\node_modules\@angular-devkit\build-angular\src\builders\dev-server\index.js:124:47)

Rgds,
Benedict

[package.zip](https://github.com/angular/angular-cli/files/7664632/package.zip)
