### ISSUE TITLE
Update to pacote@12.0.2 in angular/cli@12 because of vulnerabilities

### ISSUE THREAD

**Issue by Aikidas** [angular/angular-cli#22233]
When installing an Angular app version 12, I noticed that it was being installed with '19 vulnerabilities (14 moderate, 5 high) '. 
Nom audit offers update to @ angular/cli@13.0.3 as a solution. However, this is not possible to update due to other dependencies.

Is there a possibility to update the dependency of the package "pacote" in the angular / cli @ 12 version to pacote @ 12?

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/22240
