### ISSUE TITLE
Providing .js extension for angular config file not just angular.json

### ISSUE THREAD

**Issue by 1aron** [angular/angular-cli#22234]
# 🚀 Feature request

### Description

Take a look [Semantic Release Config](https://semantic-release.gitbook.io/semantic-release/usage/configuration)
Accepting `js` extension can provide more flexible and deduplicated configuration.

### Describe the solution you'd like

Accepts `angular.js`, `angular.json`

### Describe alternatives you've considered

No

**Comment by alan-agius4** [comment]
Related to https://github.com/angular/angular-cli/issues/12943, please see @clydin comment https://github.com/angular/angular-cli/issues/12943#issuecomment-634746071
