### ISSUE TITLE
Use globally installed @angular/cli if it is latest instead of downloading it

### ISSUE THREAD

**Issue by Den-dp** [angular/angular-cli#22238]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Running `ng update @angular/cli @angular/core` in Angular 12 project is slower than needed since it downloads the latest `@angular/cli` ignoring the globally installed one.

```
> ng update @angular/cli @angular/core @angular/material
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
√ Package successfully installed.
```

### Describe the solution you'd like

Do not install a temporary version if a global `ng` installation with an appropriate version is found.

### Describe alternatives you've considered

Might be implemented as an opt-in feature via env variable

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version` when run outside of an Angular project?

**Comment by Den-dp** [comment]
@alan-agius4 sure
```
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.0.3
Node: 12.21.0
Package Manager: npm 6.14.15
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.3 (cli-only)
@angular-devkit/core         13.0.3 (cli-only)
@angular-devkit/schematics   13.0.3 (cli-only)
@schematics/angular          13.0.3 (cli-only)
```

**Comment by alan-agius4** [comment]
That is odd, because the global CLI should be used if it's greater than the local version of the CLI when running `ng update`.

**Comment by Den-dp** [comment]
@alan-agius4 thanks for the quick feedback! ⚡

**Comment by Den-dp** [comment]
@alan-agius4 thanks for the quick feedback! ⚡⚡⚡

After your confirmation that such feature was here all that time, I started my investigation of "what's wrong with my setup" and found a very frustrating thing.

So it's turned out that the problem was in the Terminal of WebStom/Intellij Idea since it has the following feature enabled by default: https://youtrack.jetbrains.com/issue/WEB-33571

![image](https://user-images.githubusercontent.com/1770529/143606366-fb171add-d860-4828-88b8-d8f6b1d48f6d.png)

As I understand lots of people who use this integrated Terminal are affected.
Personally, I've seen this message "The installed local Angular CLI version is older than the latest stable version." for years and didn't even realize that this was a problem with my IDE.

Should it be resolved on their side, or `@angular/cli` can help with a workaround for Intellij Idea users?

**Comment by alan-agius4** [comment]
Since the local `ng` will be added to`%PATH%` it will completely bypass the global CLI bootstrapping. I am surprised that this feature is actually turned on by default as myself I wouldn't expect that local binaries to be added to `%PATH%`.

I'll put this up for discussion with the rest of the team to see if we want to do anything around this.

**Comment by segrey** [comment]
JFYI, IntelliJ's behavior will be changed in 2021.3.1: `node_modules/.bin` will be added to the end of PATH, this should probably fix the issue with bypassing the global CLI bootstrapping.
https://youtrack.jetbrains.com/issue/WEB-33571#focus=Comments-27-5612968.0-0

**Comment by Den-dp** [comment]
@segrey This is great news! Thank you for your cooperation

**Comment by alan-agius4** [comment]
Closing since this will be addressed by Intellij as pointed out by @segrey in the above comment.
