### ISSUE TITLE
Change the title icon in angular 12

### ISSUE THREAD

**Issue by xswlw** [angular/angular-cli#22235]
# 🐞 Bug report
I changed the original icon image but with the same property and same name as favicon.ico, it's not working even you can click the href in index.html and the system shows the icon. I restarted the server multiple times, it seems not working anyway.

#✍️solution
Finally, I tried to put the new favicon.ico into the assets folder, change the route in angular.json. It works pretty well and you can put the icon in your web title with any form.

#☕️☕️code
icon with the png/jepg form

index.html

`<link rel="icon" type="image/x-icon" href="./assets/icon.png">`

##angular.json
"assets": [
              "src/assets/icon.png",
              "src/assets"
            ],

icon with the ico form

index.html

`<link rel="icon" type="image/x-icon" href="./assets/icon.ico">`

##angular.json
"assets": [
              "src/assets/icon.ico",
              "src/assets"
            ],

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
