### ISSUE TITLE
Re-implement route generation

### ISSUE THREAD

**Issue by Brocco** [angular/angular-cli#2225]
With all of the changes surrounding routing and multiple routers in angular2 the generation of routes had been disabled.

We will start to re-implement this feature starting with this issue...
# Generate a routing file

ng generate route <modulePath>

modulePath - argument which contains the relative path to a module file in your app to which this new routing file will be associated with

Given this app structure:

```
.root
+--src
  +--app
    +--feature1
      +--feature1.module.ts
```

Running this
`ng generate route feature1/feature1.module.ts` will yield

```
.root
+--src
  +--app
    +--feature1
      +--feature1.module.ts
      +--feature1.routing.ts
```

The other side effect will be the import of the new routing module into `feature1.module.ts`

```
import { RoutingModule } from './feature1.routing';
@NgModule({
  imports: [ ..., RoutingModule ]
})...
```

Alternatives to `modulePath` that will produce the same result (based upon the above example)
- feature1/feature1.module (by auto-adding `ts` extension)
- feature1 (by searching this directory for a single `*.module.ts` file
### Note: specific route generation

This issue is to handle the creation of routing files, the generation of specific routes may be handled later, this is the first step toward that

**Comment by otabekgb** [comment]
Is there any estimation for release of new route generation?

**Comment by Brocco** [comment]
@otabekgb at this point no... the CLI currently generates routing files (not specific routes) with new projects and with module generation.
