### ISSUE TITLE
Build is taking too much time in Docker

### ISSUE THREAD

**Issue by Hashimlokasher** [angular/angular-cli#22261]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
Running build command is taking too much time to build in Docker

Build at: 2021-12-01T07:15:05.208Z - Hash: 4302809658655ef241f8 - Time: 354339ms

## 🔬 Minimal Reproduction
npm run-script build -- --prod

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre>Dockerfile<code>

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0.102-1-buster-slim AS build

WORKDIR /src
COPY ["Web/TestProject.Web/TestProject.Web.csproj", "Web/TestProject.Web/"]
RUN dotnet restore "Web/TestProject.Web/TestProject.Web.csproj"
COPY . /src
WORKDIR "/src/Web/TestProject.Web"
RUN dotnet build "TestProject.Web.csproj" -c Release -o /app/build

FROM node:12.18-alpine AS client 
ARG skip_client_build=false 
WORKDIR /app 
COPY ["Web/TestProject.Web/ClientApp/", "."]
RUN  if [ "$skip_client_build" = "true" ] ; then echo "Skipping npm install" ; else npm install ; fi
RUN  if [ "$skip_client_build" = "true" ] ; then mkdir -p dist ; else npm run-script build -- --prod ; fi

FROM build AS publish
RUN dotnet publish "TestProject.Web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
ENV ASPNETCORE_URLS http://*:80

COPY --from=publish /app/publish .
COPY --from=client /app/dist /app/ClientApp/dist
ENTRYPOINT ["dotnet", "TestProject.Web.dll"]

</code></pre>

**Anything else relevant?**

<pre>
<b>Logs</b>
<code>
Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.

- Generating browser application bundles (phase: setup)...

✔ Browser application bundle generation complete.

Initial Chunk Files                                                                                     | Names         |      Size

vendor.js                                                                                               | vendor        |   5.51 MB

main.js                                                                                                 | main          |   2.70 MB

polyfills.js                                                                                            | polyfills     | 166.03 kB

styles.css                                                                                              | styles        |  27.13 kB

runtime.js                                                                                              | runtime       |  12.54 kB

| Initial Total |   8.42 MB

Lazy Chunk Files                                                                                        | Names         |      Size

src_app_fares_fares_module_ts.js                                                                        | -             | 731.25 kB

src_app_bookings_bookings_module_ts.js                                                                  | -             | 645.45 kB

src_app_permissions_permissions_module_ts.js                                                            | -             | 457.38 kB

src_app_itinerary_models_itinerary-view-model_ts-src_app_seats_seats_module_ts.js                       | -             | 437.18 kB

src_app_-showcase-showcase_module_ts.js                                                    | -             | 280.26 kB

src_app_quotes_quotes_module_ts.js                                                                      | -             | 182.87 kB

src_app_payments_payments_module_ts.js                                                                  | -             | 153.98 kB

src_app_confirmations_confirmations_module_ts.js                                                        | -             |  67.06 kB

default-src_app_confirmations_services_booking-create_service_ts-src_app_itinerary_models_iti-515600.js | -             |  31.84 kB

common.js                                                                                               | common        |   9.72 kB

Build at: 2021-12-01T07:15:05.208Z - Hash: 4302809658655ef241f8 - Time: 354339ms

** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **

✔ Compiled successfully.

15 unchanged chunks

Build at: 2021-12-01T07:21:08.495Z - Hash: edd14ea295c8b354d7e6 - Time: 360158ms

✔ Compiled successfully.

Warning: /app/src/app/seats/components/seatmap/seatmap.component.ts depends on 'snapsvg-cjs'. CommonJS or AMD dependencies can cause optimization bailouts.

For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

✔ Browser application bundle generation complete.
</code></pre>

**Comment by alan-agius4** [comment]
@Hashimlokasher, can you please provide the output of `ng version`, a CPU profile and also your `angular.json`?

**Comment by Hashimlokasher** [comment]
> @Hashimlokasher, can you please provide the output of `ng version`, a CPU profile and also your `angular.json`?

Angular.json is attached
[angular.json.txt](https://github.com/angular/angular-cli/files/7632601/angular.json.txt)

**Comment by alan-agius4** [comment]
@Hashimlokasher, the configuration looks good.

Can you kindly provide the additional requested information?

**Comment by Hashimlokasher** [comment]
> @Hashimlokasher, can you please provide the output of `ng version`, a CPU profile and also your `angular.json`?

**ng version output**
<pre>
<code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 12.2.5
Node: 14.15.5
Package Manager: npm 6.14.11
OS: linux x64

Angular: 12.2.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by Hashimlokasher** [comment]
> @Hashimlokasher, can you please provide the output of `ng version`, a CPU profile and also your `angular.json`?

How to get CPU Profile?

P.S npm build works fast on my windows but builds slow inside docker container

**Comment by alan-agius4** [comment]
In that case, this is not caused by Angular CLI, but likely a docker configuration issue. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
