### ISSUE TITLE
ERROR (do you think you need more information?)

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#2226]
1. I use MacOs El Capitan
2.  beta 14

4. I install project ng init I already run ng serve but today : ERROR

5. I do `ng serve` command I just receive _ERROR_ on my terminal! 

**GOOGLE CLEVER TEAM : WHAT IS YOUR PROBLEM TO GET MORE INFORMATION ABOUT ERROR?** 

This won't let me move !  I lost a lot time.

I hope read you ASAP, other than it's beta. 

please give us more detail about all your error ! 

![capture d ecran 2016-09-19 a 19 34 44](https://cloud.githubusercontent.com/assets/2789203/18642948/2566f632-7ea3-11e6-8b90-c329c50e2cdf.png)

**Comment by Brocco** [comment]
That's a great error, let's see if we can get a little bit more information...
Are you able to run `ng build`?
Are you able to share this project publicly?
Have you tried reinstalling the CLI?
```
npm uninstall angular-cli -g
npm cache clean
npm install angular-cli -g
```
Is this a new project?
  If not, what version of the CLI was it created with?
Can you run `ng serve` newly created applications?

**Comment by istiti** [comment]
`ng build` give me same error

I reinstall and clean cache ...

It's new project did with angular-cli beta 14


My package is: 
`{
  "name": "mtc",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@angular2-material/button": "^2.0.0-alpha.8-2",
    "@angular2-material/button-toggle": "^2.0.0-alpha.8-2",
    "@angular2-material/card": "^2.0.0-alpha.8-2",
    "@angular2-material/checkbox": "^2.0.0-alpha.8-2",
    "@angular2-material/core": "^2.0.0-alpha.8-2",
    "@angular2-material/grid-list": "^2.0.0-alpha.8-2",
    "@angular2-material/icon": "^2.0.0-alpha.8-2",
    "@angular2-material/input": "^2.0.0-alpha.8-2",
    "@angular2-material/list": "^2.0.0-alpha.8-2",
    "@angular2-material/menu": "^2.0.0-alpha.8-2",
    "@angular2-material/progress-bar": "^2.0.0-alpha.8-2",
    "@angular2-material/progress-circle": "^2.0.0-alpha.8-2",
    "@angular2-material/radio": "^2.0.0-alpha.8-2",
    "@angular2-material/sidenav": "^2.0.0-alpha.8-2",
    "@angular2-material/slide-toggle": "^2.0.0-alpha.8-2",
    "@angular2-material/slider": "^2.0.0-alpha.8-2",
    "@angular2-material/tabs": "^2.0.0-alpha.8-2",
    "@angular2-material/toolbar": "^2.0.0-alpha.8-2",
    "@angular2-material/tooltip": "^2.0.0-alpha.8-2",
    "@types/jasmine": "^2.2.30",
    "@types/hammerjs": "^2.0.32",
    "angular-cli": "1.0.0-beta.14",
    "angular2-mdl": "^1.7.1",
    "chart.js": "^2.2.2",
    "codelyzer": "~0.0.26",
    "hammerjs": "^2.0.8",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "ng2-charts": "^1.2.0",
    "protractor": "4.0.5",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}
`

**Comment by JanStureNielsen** [comment]
@istiti -- can you try changing directory to an uninitialized directory and type `ng --version`. If this works, try `ng new foo; cd foo; ng --version`. Can you reduce your project to the smallest possible and make it available somewhere like GitHub?

**Comment by Brocco** [comment]
FYI, I was able to do the following....
```
ng new foo
cd foo
npm i charts.js angular2-mdl ng2-charts --save
```
in `app.module.ts`
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';

import { MdlModule } from 'angular2-mdl';
import { ChartsModule } from 'ng2-charts/ng2-charts';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MdlModule,
    ChartsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
and then run this successfully
```
ng build
```

Can you please try what @JanStureNielsen suggested above?

**Comment by istiti** [comment]
I do not understand I just comment ChartsModule and decomment it again and install  again my 3rd party lib (even with npm error 'charts.js' is not in the npm registry.

Now it serve well again ! I do not understand why I didn't have more message error information 


thanks to you both for fast reply

**Comment by Brocco** [comment]
To clarify it is working now? If so, please close the issue (and celebrate)

Also of note regarding your dependencies... You will want to move a portion of your dependencies from `devDependencies` to `dependencies`. Think of them this way... if they are needed for your application to run, it goes in `dependencies` if I only need it for development then it goes in `devDependencies`. You can save them from the command line via `--save` or `--save-dev`
