### ISSUE TITLE
Angular 13: 'ng serve' does not proxy multiple websocket connections correctly and results in 'Invalid frame header' errors

### ISSUE THREAD

**Issue by brodziakm** [angular/angular-cli#22260]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 12.2.5

### Description

When the dev server is configured to proxy websockets, connections are rejected with 'Invalid frame header'

## 🔬 Minimal Reproduction

Establish a valid proxy configuration that includes multiple websocket URLs. Observe the behaviour in the Chrome devtools tab.

Expected behavior: websocket connections are established correctly
Actual behavior: Some websocket connections fail with 'Invalid frame header'

I have verified that direct connections to the websocket URL (bypassing the proxy altogether) work correctly.

## 🔥 Exception or Error

"Invalid frame header" errors are observed in Chrome devtools / network tab

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

</code></pre>

**Anything else relevant?**

Angular 12 used http-proxy-middleware v 0.19.1

Angular 13 uses http-proxy-middleware 2.0.1

This issue in http-proxy-middleware might be the root cause of the problem: 
https://github.com/chimurai/http-proxy-middleware/issues/463

There is a noted workaround that might be possible to include in the dev server.

Our workaround, in the interim, is to bypass the proxy for websocket connections.

**Comment by duxor** [comment]
@alan-agius4 ok, but waiting is not a solution, right? Is there any temporary way to avoid this?

**Comment by mojo2012** [comment]
Leaving the users alone with this problem is probably not the best way to keep the userbase, or even grow new users. Are there plans to help the webpack dev server(?) team out to fix this issue. Is there any communication at all? Or are you just waiting for the problem to go away?
Please don't just leave us out in the cold!

**Comment by atrillun** [comment]
Do we have any news about this issue ?

**Comment by sbrannstrom** [comment]
Also having the same issue as described, any news? 
The http-proxy-middleware issue hasn't been updated since 13th of March, 2021 (!!).
