### ISSUE TITLE
V 13.1.0-next.2 - Breaks contents of application/ld+json in Index.html file

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#22269]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] build
- [x] serve

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 13.1.0-next.1

### Description

After upgrading to 13.1.0-next.1, the below contents of application/ld+json tag in Index.html file is broken:

```
  <script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "Mustakbil",
        "description": "Mustakbil.com is a leading jobs site in Pakistan. It helps jobseekers in finding the jobs of their choice, while providing a unique platform for employers to advertise career opportunities and find valuable human resources for their organization.",
        "url": "https://www.mustakbil.com",
        "logo": "https://www.mustakbil.com/content/images/icon-512x512.png",
        "email": "support@mustakbil.com",
        "address": {
                        "@type": "PostalAddress",
                        "addressCountry": "PK",
                        "postalCode": "46000",
                        "streetAddress": "Jehlum Road, Rawalpindi"
        },
        "founder": {
                        "@type": "Person",
                        "name": "Naveed Ahmed",
                        "gender": "Male",
                        "jobTitle": "CEO",
                        "sameAs": [
                            "https://twitter.com/naveedahmed",
                            "https://linkedin.com/in/naveed1"
            ]
        },
        "foundingDate": "2004-10-07",
        "sameAs" : [
            "https://www.crunchbase.com/organization/mustakbil-com",
            "https://www.facebook.com/Mustakbil",
            "https://www.linkedin.com/company/mustakbil",
            "https://twitter.com/mustakbil"
        ],
        "contactPoint" : [
            {
                "@type" : "ContactPoint",
                "contactType" : "customer service",
                "email": "support@mustakbil.com",
                "telephone": "[+92-51-8313316]",
                "url": "https://www.mustakbil.com/contact"
            }
        ]
    }
  </script>
```

Is converted to:

```
<script type="application/ld+json">/contact"
            }
        ]
    }</script>
```

## 🔬 Minimal Reproduction

Add the below application/ld+json tag in Index.html file  and then publish the app and you will notice that the tag is broken:

```
  <script type="application/ld+json">
    {
        "@context": "http://schema.org",
        "@type": "Organization",
        "name": "Mustakbil",
        "description": "Mustakbil.com is a leading jobs site in Pakistan. It helps jobseekers in finding the jobs of their choice, while providing a unique platform for employers to advertise career opportunities and find valuable human resources for their organization.",
        "url": "https://www.mustakbil.com",
        "logo": "https://www.mustakbil.com/content/images/icon-512x512.png",
        "email": "support@mustakbil.com",
        "address": {
                        "@type": "PostalAddress",
                        "addressCountry": "PK",
                        "postalCode": "46000",
                        "streetAddress": "Jehlum Road, Rawalpindi"
        },
        "founder": {
                        "@type": "Person",
                        "name": "Naveed Ahmed",
                        "gender": "Male",
                        "jobTitle": "CEO",
                        "sameAs": [
                            "https://twitter.com/naveedahmed",
                            "https://linkedin.com/in/naveed1"
            ]
        },
        "foundingDate": "2004-10-07",
        "sameAs" : [
            "https://www.crunchbase.com/organization/mustakbil-com",
            "https://www.facebook.com/Mustakbil",
            "https://www.linkedin.com/company/mustakbil",
            "https://twitter.com/mustakbil"
        ],
        "contactPoint" : [
            {
                "@type" : "ContactPoint",
                "contactType" : "customer service",
                "email": "support@mustakbil.com",
                "telephone": "[+92-51-8313316]",
                "url": "https://www.mustakbil.com/contact"
            }
        ]
    }
  </script>
```

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.0-next.2
Node: 14.17.6
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.1.0-next.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, google-maps, language-service, material
... platform-browser, platform-browser-dynamic, platform-server
... pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.0-next.2
@angular-devkit/build-angular   13.1.0-next.2
@angular-devkit/core            12.2.10
@angular-devkit/schematics      12.2.10
@angular/fire                   7.2.0
@schematics/angular             12.2.10
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
@naveedahmed1, I am unable to replicate this issue using `13.1.0-next.3`
![Screenshot 2021-12-02 at 14 40 08](https://user-images.githubusercontent.com/17563226/144433068-6d638bdd-369e-42bd-8b0f-ccaca1fbfc1e.png)

**Comment by naveedahmed1** [comment]
Thank you @alan-agius4 for your reply.

Can you please check it in the Mustakbil Angular repo ( I think you are already added as contributor). Just uncomment the application/ld+json tag in index.html.

**Comment by alan-agius4** [comment]
@naveedahmed1, I wasn't able to reproduce using the reproduction provided.
![Screenshot 2021-12-02 at 15 56 21](https://user-images.githubusercontent.com/17563226/144446341-59bc1f6b-7761-4cc2-a58b-7d4c752f8acc.png)

**Comment by naveedahmed1** [comment]
That's strange, when I run `npm run build` and check `index.html` file in `/dist` folder it has below contents:

```
  <script type="application/ld+json">/mustakbil-com",
            "https://www.facebook.com/Mustakbil",
            "https://www.linkedin.com/company/mustakbil",
            "https://twitter.com/mustakbil"
        ],
        "contactPoint" : [
            {
                "@type" : "ContactPoint",
                "contactType" : "customer service",
                "email": "support@mustakbil.com",
                "telephone": "[+92-51-8313316]",
                "url": "https://www.mustakbil.com/contact"
            }
        ]
    }
  </script>
<script src="runtime.7dbce98fce83930a.js" type="module"></script><script src="polyfills.4a8cb5ead96ef4b4.js" type="module"></script><script src="main.cb70e5942930b516.js" type="module"></script></body>

```

Can you please confirm if you tried the production build i.e. `npm run build`?

**Comment by alan-agius4** [comment]
Yeah I confirm that I used that.

**Comment by naveedahmed1** [comment]
Thanks Alan for the confirmation, its strange, when I try it on my side I am facing this issue.

BTW for production builds, the file names of js bundles in index.html should have hashed file names, correct?

The filenames of js bundles shown in screenshot in https://github.com/angular/angular-cli/issues/22269#issuecomment-984703977 doesn't have hashed file names.

**Comment by naveedahmed1** [comment]
Investigated it further and it seems that it was a local issue, I downloaded files from github and replaced my local copy and it seems to be working fine now. Although its strange that the files on my local machine were identical. 

Thank you so much @alan-agius4 for your time, really appreciate.
