### ISSUE TITLE
Some unsupported code with es2015 target set

### ISSUE THREAD

**Issue by SetoKaiba** [angular/angular-cli#22270]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

![image](https://user-images.githubusercontent.com/159540/144287548-ce8a0ac7-9f65-418f-b296-45875f797526.png)
This is not supported for es2015. But it's still there after compile. I'm trying to write a webpage for OBS studio. The ?. is not supported I think. And I think it's not in es2015 as well.
![image](https://user-images.githubusercontent.com/159540/144287689-e2c21dd4-2042-406b-b5d1-65dae0a43037.png)
Here is the tsconfig. Set target to es2015 doesn't help. But the unsupported is gone if I set target to es5.
https://github.com/angular/angular/blob/b5ab7aff433a67cddaa55e621d17b1a1b07b57c2/packages/common/src/location/location_strategy.ts#L176-L178
Why this ?. is kept even I set target to es2015?

**Comment by JoostK** [comment]
The optional chaining support landed in Chrome 80, quite a while ago. Angular only supports the latest major of Chrome; if OBS is using an outdated version then Angular apps may break in unexpected ways.

The CLI has some heuristics to determine the output format to generate. It looks like it treats es5 targets differently than es2015. @alan-agius4 probably knows more about this, the output format of libraries might also depend on the browserslist configuration.

**Comment by alan-agius4** [comment]
In case the target is ES2019 or lower we should favour the FESM2015 entry-point.

**Comment by thw0rted** [comment]
I don't have a horse in the race, but I am curious.  If Angular only supports the latest major Chrome release, why do they still distribute / compile to (optionally) downleveled code?

**Comment by SetoKaiba** [comment]
Agreed. Angular should be a general web development platform for all users instead of latest chrome users.

**Comment by JoostK** [comment]
Sorry, my comment was ambiguous: I didn't mean to say that only Chrome is supported, I meant say that specifically for Chrome we only support the latest major. That means that we test against it to verify that things work, it doesn't mean that we're actively breaking older versions (except for IE11, for which support was dropped in Angular 13)

**Comment by thw0rted** [comment]
Ah, that makes more sense.  So, are the "heuristics" the CLI uses to choose which packaging to use documented somewhere public-facing?  I've always been kind of curious about the console output I see during a build, "Compiling @angular/core : es2015 as esm2015" etc.

**Comment by danilmoro3** [comment]
It doesn't work 
"target": "es2015" in tsconfig.json still generate ESM2020 module with .mjs files
