### ISSUE TITLE
NG_CLI_PROFILING and DEVKIT_PROFILING don't do anything

### ISSUE THREAD

**Issue by wesselvdv** [angular/angular-cli#22277]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [x] generate
- [x] add
- [x] update
- [x] lint
- [x] extract-i18n
- [x] run
- [x] config
- [x] help
- [x] version
- [x] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

I think this is a regression, just not sure when it worked for the last time.

### Description

When trying to get a cpu profile according to the docs a set of ENV variables can be used, but when enabled it does nothing.

## 🔬 Minimal Reproduction

`DEVKIT_PROFILING=devkit NG_CLI_PROFILING=ng DEBUG=ng:* ng build --progress --verbose`

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.0.4
Node: 16.13.0
Package Manager: npm 8.1.0
OS: linux x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.5.2
webpack                         5.64.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
We should update the docs, there are two ways to create a CPU profile.

```
NG_BUILD_PROFILING=1 ng build 
```

Or since you are using Node.js 16, you can use Node.Js new `--cpu-prof` flag.

```
node --cpu-prof node_modules/.bin/ng build
```

**Comment by wesselvdv** [comment]
@alan-agius4 interesting, I am trying to debug some seriously slow ng builds, so thanks for the suggestions!

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/22279
