### ISSUE TITLE
The dependence on @ampproject/remapping@1.0.1 should be updated to 1.0.2 due to a blocking issue during `ng build`

### ISSUE THREAD

**Issue by alessandro-tucci-visiontech** [angular/angular-cli#22280]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

`@angular-devkit/build-angular@12.2.13`  depends on `@ampproject/remapping@1.0.1`, which is affected by this blocking issue: https://github.com/ampproject/remapping/issues/153

The issue was quickly fixed and a new version `@ampproject/remapping@1.0.2` was released just yesterday.
Like reported in the linked page, the issue affects all the projects having at least one library containing at least one .js file made up of just a source map and no additional content. In my specific case, the impacted library is `@zxing/browser@~0.0.10`:

![image](https://user-images.githubusercontent.com/50661302/144427897-1b0f84d9-088a-4b0f-8469-b1521dc8a5f0.png)

Due to the blocking nature of the issue, I kindly ask you to publish a new `patch` version which depends on the fixed version of `@ampproject/remapping`.

## 🔬 Minimal Reproduction

Just launch `ng build` on a project which depends on `@angular-devkit/build-angular@12.2.13` and, for example, `@zxing/browser@~0.0.10` (like in my screenshot)

## 🔥 Exception or Error

Like reported on the linked issue, the following error is displayed:
<pre><code>
./node_modules/<JS file having only a source map reference> - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: Transformation map 0 must have exactly one source file.
Did you specify these with the most recent transformation maps first?
    at buildSourceMapTree (/cut/node_modules/@ampproject/remapping/dist/remapping.umd.js:729:23)
    at remapping (/cut/node_modules/@ampproject/remapping/dist/remapping.umd.js:831:23)
    at Object.result (/cut/node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js:202:54)
    at Object.<anonymous> (/cut/node_modules/babel-loader/lib/index.js:221:43)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/cut/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/cut/node_modules/babel-loader/lib/index.js:5:194)
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.13
Node: 16.13.0 (Unsupported)
Package Manager: npm 8.1.0
OS: win32 x64

Angular: undefined
...

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@angular/cli                    12.2.13
@angular/compiler-cli           12.2.13
@angular/language-service       12.2.13
@angular/service-worker         12.2.13
@schematics/angular             12.2.13
typescript                      4.3.5

</code></pre>

**Comment by alan-agius4** [comment]
Version 12, is currently in LTS were only security fixes released. 

Please update to a more recent version to avail from bug fixes.

**Comment by alan-agius4** [comment]
Merged into 13.0.x via https://github.com/angular/angular-cli/pull/22281#event-5707588199
