### ISSUE TITLE
In Angular 12 unable to open sourcemap files of my shared library project in devtools. 

### ISSUE THREAD

**Issue by megant** [angular/angular-cli#22282]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

I have an Angular 12 workspace with applications and a shared library with components. When I open Chrome devtools, the *.ts files are present and can debug them, but there are no ts files from shared library at all, even though components work. It worked with Angular 11.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.0.5
Node: 14.18.1
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/cdk                    12.2.10
@schematics/angular             12.0.5
ng-packagr                      12.2.3
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by alan-agius4** [comment]
@megant, do you have vendor sourcemaps enabled?

https://angular.io/guide/workspace-config#source-map-configuration

**Comment by megant** [comment]
This is my angular.json

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "allosoft": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "projects/allosoft",
      "sourceRoot": "projects/allosoft/src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/allosoft",
            "index": "projects/allosoft/src/index.html",
            "main": "projects/allosoft/src/main.ts",
            "polyfills": "projects/allosoft/src/polyfills.ts",
            "tsConfig": "projects/allosoft/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/allosoft/src/favicon.ico",
              "projects/allosoft/src/assets"
            ],
            "styles": [
              "projects/allosoft/src/styles.scss"
            ],
            "scripts": [
              "node_modules/moment/moment.js",
              "node_modules/chart.js/dist/Chart.js"
            ]
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "projects/allosoft/src/environments/environment.ts",
                  "with": "projects/allosoft/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "allosoft:build:production"
            },
            "development": {
              "browserTarget": "allosoft:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "allosoft:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/allosoft/src/test.ts",
            "polyfills": "projects/allosoft/src/polyfills.ts",
            "tsConfig": "projects/allosoft/tsconfig.spec.json",
            "karmaConfig": "projects/allosoft/karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/allosoft/src/favicon.ico",
              "projects/allosoft/src/assets"
            ],
            "styles": [
              "projects/allosoft/src/styles.scss"
            ],
            "scripts": []
          }
        },
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "allosoft:serve",
            "configFile": "projects/allosoft/cypress.json"
          },
          "configurations": {
            "production": {
              "devServerTarget": "allosoft:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false,
            "configFile": "projects/allosoft/cypress.json"
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "allosoft:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "allosoft:serve:production"
            }
          }
        }
      }
    },
    "core": {
      "projectType": "library",
      "root": "projects/core",
      "sourceRoot": "projects/core/src",
      "prefix": "lib",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:ng-packagr",
          "options": {
            "project": "projects/core/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/core/tsconfig.lib.prod.json"
            },
            "development": {
              "tsConfig": "projects/core/tsconfig.lib.json"
            }
          },
          "defaultConfiguration": "production"
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/core/src/test.ts",
            "tsConfig": "projects/core/tsconfig.spec.json",
            "karmaConfig": "projects/core/karma.conf.js"
          }
        },
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "core:serve",
            "configFile": "projects/core/cypress.json"
          },
          "configurations": {
            "production": {
              "devServerTarget": "core:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false,
            "configFile": "projects/core/cypress.json"
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "core:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "core:serve:production"
            }
          }
        }
      }
    },
    "playground": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "projects/playground",
      "sourceRoot": "projects/playground/src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/playground",
            "index": "projects/playground/src/index.html",
            "main": "projects/playground/src/main.ts",
            "polyfills": "projects/playground/src/polyfills.ts",
            "tsConfig": "projects/playground/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/playground/src/favicon.ico",
              "projects/playground/src/assets"
            ],
            "styles": [
              "projects/playground/src/styles.scss",
              "node_modules/primeng/resources/themes/saga-blue/theme.css",
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/primeicons/primeicons.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "projects/playground/src/environments/environment.ts",
                  "with": "projects/playground/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "playground:build:production"
            },
            "development": {
              "browserTarget": "playground:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "playground:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/playground/src/test.ts",
            "polyfills": "projects/playground/src/polyfills.ts",
            "tsConfig": "projects/playground/tsconfig.spec.json",
            "karmaConfig": "projects/playground/karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/playground/src/favicon.ico",
              "projects/playground/src/assets"
            ],
            "styles": [
              "projects/playground/src/styles.scss"
            ],
            "scripts": []
          }
        },
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "playground:serve",
            "configFile": "projects/playground/cypress.json"
          },
          "configurations": {
            "production": {
              "devServerTarget": "playground:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false,
            "configFile": "projects/playground/cypress.json"
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "playground:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "playground:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "allosoft"
}


As you can see, there is another "playground project". If I run playground's ng serve, I can see the sourcemapped .ts files of core library. But I'm unable to see from allosoft project.

**Comment by alan-agius4** [comment]
As suspected vendor sourcemaps is not enabled in your application development configuration.

Kindly see the above linked documentation on how to enable this feature.

**Comment by megant** [comment]
Well, configuration in allosoft and playground projects are the same, and I can see core library's component sources in playground.

**Comment by megant** [comment]
I updated my angular.json, but still does not work (tried the same before).

```
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "allosoft": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "projects/allosoft",
      "sourceRoot": "projects/allosoft/src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/allosoft",
            "index": "projects/allosoft/src/index.html",
            "main": "projects/allosoft/src/main.ts",
            "polyfills": "projects/allosoft/src/polyfills.ts",
            "tsConfig": "projects/allosoft/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/allosoft/src/favicon.ico",
              "projects/allosoft/src/assets"
            ],
            "styles": [
              "projects/allosoft/src/styles.scss"
            ],
            "scripts": [
              "node_modules/moment/moment.js",
              "node_modules/chart.js/dist/Chart.js"
            ]
          },
          "configurations": {
            "production": {
              "sourceMap": {
                "scripts": true,
                "styles": false,
                "hidden": true,
                "vendor": true
              },
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "10mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "projects/allosoft/src/environments/environment.ts",
                  "with": "projects/allosoft/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "allosoft:build:production"
            },
            "development": {
              "browserTarget": "allosoft:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "allosoft:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/allosoft/src/test.ts",
            "polyfills": "projects/allosoft/src/polyfills.ts",
            "tsConfig": "projects/allosoft/tsconfig.spec.json",
            "karmaConfig": "projects/allosoft/karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/allosoft/src/favicon.ico",
              "projects/allosoft/src/assets"
            ],
            "styles": [
              "projects/allosoft/src/styles.scss"
            ],
            "scripts": []
          }
        },
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "allosoft:serve",
            "configFile": "projects/allosoft/cypress.json"
          },
          "configurations": {
            "production": {
              "devServerTarget": "allosoft:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false,
            "configFile": "projects/allosoft/cypress.json"
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "allosoft:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "allosoft:serve:production"
            }
          }
        }
      }
    },
    "core": {
      "projectType": "library",
      "root": "projects/core",
      "sourceRoot": "projects/core/src",
      "prefix": "lib",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:ng-packagr",
          "options": {
            "project": "projects/core/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/core/tsconfig.lib.prod.json"
            },
            "development": {
              "tsConfig": "projects/core/tsconfig.lib.json"
            }
          },
          "defaultConfiguration": "production"
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/core/src/test.ts",
            "tsConfig": "projects/core/tsconfig.spec.json",
            "karmaConfig": "projects/core/karma.conf.js"
          }
        },
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "core:serve",
            "configFile": "projects/core/cypress.json"
          },
          "configurations": {
            "production": {
              "devServerTarget": "core:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false,
            "configFile": "projects/core/cypress.json"
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "core:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "core:serve:production"
            }
          }
        }
      }
    },
    "playground": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        },
        "@schematics/angular:application": {
          "strict": true
        }
      },
      "root": "projects/playground",
      "sourceRoot": "projects/playground/src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/playground",
            "index": "projects/playground/src/index.html",
            "main": "projects/playground/src/main.ts",
            "polyfills": "projects/playground/src/polyfills.ts",
            "tsConfig": "projects/playground/tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/playground/src/favicon.ico",
              "projects/playground/src/assets"
            ],
            "styles": [
              "projects/playground/src/styles.scss",
              "node_modules/primeng/resources/themes/saga-blue/theme.css",
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/primeicons/primeicons.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "fileReplacements": [
                {
                  "replace": "projects/playground/src/environments/environment.ts",
                  "with": "projects/playground/src/environments/environment.prod.ts"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "browserTarget": "playground:build:production"
            },
            "development": {
              "browserTarget": "playground:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "playground:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/playground/src/test.ts",
            "polyfills": "projects/playground/src/polyfills.ts",
            "tsConfig": "projects/playground/tsconfig.spec.json",
            "karmaConfig": "projects/playground/karma.conf.js",
            "inlineStyleLanguage": "scss",
            "assets": [
              "projects/playground/src/favicon.ico",
              "projects/playground/src/assets"
            ],
            "styles": [
              "projects/playground/src/styles.scss"
            ],
            "scripts": []
          }
        },
        "cypress-run": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "playground:serve",
            "configFile": "projects/playground/cypress.json"
          },
          "configurations": {
            "production": {
              "devServerTarget": "playground:serve:production"
            }
          }
        },
        "cypress-open": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "watch": true,
            "headless": false,
            "configFile": "projects/playground/cypress.json"
          }
        },
        "e2e": {
          "builder": "@cypress/schematic:cypress",
          "options": {
            "devServerTarget": "playground:serve",
            "watch": true,
            "headless": false
          },
          "configurations": {
            "production": {
              "devServerTarget": "playground:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "allosoft"
}

```
