### ISSUE TITLE
[v12 to v13] stuck on UPDATE package.json (2055 bytes)

### ISSUE THREAD

**Issue by indraraj26** [angular/angular-cli#22289]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: No

### Description

 A clear and concise description of the problem...
I am trying to update mine ionic app v12 to v13. command that I m using 
`ng update @angular/core @angular/cli  --force`
## 🔥 Exception or Error

<pre><code>

ng update @angular/core @angular/cli  --force
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 28 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-eslint/builder" has an incompatible peer dependency to "@angular/cli" (requires ">= 12.0.0 < 13.0.0", would install "13.0.4").
    Updating package.json with dependency @angular-devkit/build-angular @ "13.0.4" (was "12.1.4")...
    Updating package.json with dependency @angular/cli @ "13.0.4" (was "12.1.4")...
    Updating package.json with dependency @angular/compiler @ "13.0.3" (was "12.1.5")...
    Updating package.json with dependency @angular/compiler-cli @ "13.0.3" (was "12.1.5")...
    Updating package.json with dependency @angular/language-service @ "13.0.3" (was "12.0.5")...
    Updating package.json with dependency typescript @ "4.4.4" (was "4.2.4")...
    Updating package.json with dependency @angular/common @ "13.0.3" (was "12.1.5")...
    Updating package.json with dependency @angular/core @ "13.0.3" (was "12.1.5")...
    Updating package.json with dependency @angular/forms @ "13.0.3" (was "12.1.5")...
    Updating package.json with dependency @angular/platform-browser @ "13.0.3" (was "12.1.5")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "13.0.3" (was "12.1.5")...
    Updating package.json with dependency @angular/router @ "13.0.3" (was "12.1.5")...
  UPDATE package.json (2055 bytes)

</code></pre>

## 🌍 Your Environment

<pre><code>

ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.0
Node: 14.17.1
Package Manager: npm 6.14.13
OS: win32 x64

Angular: <error>
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.1.0 (cli-only)
@angular-devkit/schematics      12.1.0 (cli-only)
@angular/cli                    12.1.0 (cli-only)
@schematics/angular             12.1.0 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by indraraj26** [comment]
Hi @alan-agius4 ,

Solved. It might be due to low-end device. It is working fine in another device.

Thank you

**Comment by nstringham** [comment]
I was able to solve this problem by running
```
 npm i @angular-eslint/schematics@13
```
and
```
npm i @angular-eslint/builder@13 
```
