### ISSUE TITLE
ng g component .\components\side-panel creates wrong entry in app.module.ts file

### ISSUE THREAD

**Issue by nairvishal** [angular/angular-cli#2229]
Using :- 
angular-cli: 1.0.0-beta.14
node: 4.5.0
os: win32 x64

I created a components folder inside app folder. So to create my component files directly inside the 'components' folder i used  `ng g component .\components\side-panel` and it created the files correctly but the entry made in app.module.ts was like this 
`import { SidePanelComponent } from './components\side-panel/side-panel.component';`
and that caused the below error.
 
Error:-
ERROR in [default] F:\Angular2Projects\TrialApp\src\app\app.module.ts:9:35
Cannot find module './componentsside-panel/side-panel.component'.

I manually corrected the slash in the link.

**Comment by Meligy** [comment]
Try version 1.0.0-beta.**15**

f6fa1a5218e9b43ab3ce29151a95efe915742562 looks like it fixes this, and it's included in 1.0.0-beta.15.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/1961

**Comment by nairvishal** [comment]
I checked in 1.0.0-beta.15 its still creating backward slash instead of forward.
`import { HomeComponent } from './components\home/home.component';`

**Comment by filipesilva** [comment]
@nairvishal I just tried with `ng g component components/side-panel` on windows and the slashes were right. Bear in mind that for these commands need to be ran with forward slashes (other slashes can also be escapes).
