### ISSUE TITLE
generate directive - Unknown blueprint: directive

### ISSUE THREAD

**Issue by NathanWalker** [angular/angular-cli#223]
With latest:
```
$ ng g directive new-directive
version: 1.13.13
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Unknown blueprint: directive
```

Not sure if I'm missing something or if `directive` just doesn't work. All others work fine (component, pipe, service)...

**Comment by jkuri** [comment]
Nathan use master, I think it includes the blueprint for generating directives.

**Comment by Brocco** [comment]
@jkuri is correct, the generation of directives was added after the latest release to npm. Until another release is pushed to npm, please use the instructions in the README to work with the latest version.
