### ISSUE TITLE
@angular-devkit/architect published as `0.1300.4` npm

### ISSUE THREAD

**Issue by jackwootton** [angular/angular-cli#22303]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
N/A

### Description
The npm for [@angular-devkit/architect](https://www.npmjs.com/package/@angular-devkit/architect) is published as `0.1300.4` whereas other Angular CLI npms are published as `13.0.4` (for example [@angular-devkit/build-angular](https://www.npmjs.com/package/@angular-devkit/build-angular)). Is this a typo?

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

See `0.1300.4 • Public • Published 4 days ago` in the screenshot.
![image](https://user-images.githubusercontent.com/1623996/144753827-654e6a19-0558-42a7-b829-79b9d4579ac1.png)

## 🔥 Exception or Error

N/A

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.4
Node: 14.18.1
Package Manager: npm 8.1.3
OS: linux x64

Angular: <error>
... animations, cdk, common, compiler, compiler-cli, core, fire
... flex-layout, forms, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.4 (cli-only)
@angular-devkit/build-angular   <error>
@angular-devkit/core            12.0.4 (cli-only)
@angular-devkit/schematics      12.0.4 (cli-only)
@angular/cli                    12.0.4 (cli-only)
@schematics/angular             12.0.4 (cli-only)
rxjs                            6.6.7 (cli-only)
typescript                      <error>
</code></pre>

**Comment by alan-agius4** [comment]
The version is correct. This is the version strategy that we use for experimental packages that have yet to be released as stable.
