### ISSUE TITLE
Angular 13 SCSS is not supported

### ISSUE THREAD

**Issue by SamShekhovtsov** [angular/angular-cli#22300]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When I create a new project from scratch using scss - the scss files are completely ignored, styles are not used at all. There is something huge broken in Angular 13 in regards to SCSS.

### Please provide a link to a minimal reproduction of the bug

ng new angular-scss-demo

### Please provide the exception or error you saw

```true
there are no errors. SCSS styles are just now working.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.4
Node: 12.22.7
Package Manager: npm 8.1.0
OS: linux x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by SamShekhovtsov** [comment]
please take a look at this repository https://github.com/SamShekhovtsov/angular-scss-demo-y73bct

when css style is added to the ~/src/app/app.component.scss - it doesn't work. It doesn't work when adding styles to any component in that way.

when css or scss is added to the ~/src/styles.scss - it works, the CSS styles are generated and applied.

**Comment by alan-agius4** [comment]
Hi @SamShekhovtsov, 

That is working as expected and this is due to `View Encapsulation` which is `Emulated` by default. 

Please see https://angular.io/guide/view-encapsulation#view-encapsulation to learn more about view encapsulation.
