### ISSUE TITLE
ng serve --public-host issue in 13

### ISSUE THREAD

**Issue by NeilSorensen** [angular/angular-cli#22309]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, this was working in Angular 12

### Description

In spite of the `--public-host` parameter, webpack is attempting to establish a websocket with `wss://localhost/ws`.

We run our development environment through a reverse proxy to allow us to host several apps on the same "domain" to better simulate our production environment. After upgrading to Angular 13, an app hosted off the main path constantly refreshes because webpack is trying to connect to the app hosted at the root.

## 🔬 Minimal Reproduction

I've produced a repository that reproduces the issue at https://github.com/emmersion/repro-app.  
With both `base-href` set in `index.html` and `--public-host` set to `http://localhost/foo`, I expect webpack to attempt to connect to `wss://localhost/foo/ws`.
The easiest way to confirm this is to watch the network tab of the developer tools when loading the app.
Instead, it attempts to connect to `wss://localhost/ws`.
The problem is particularly acute in my actual dev environment because we host a different angular app at `http://localhost`, leading to constant reloading when the `foo` app connects to the root app's websocket.

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.0.4
Node: 14.18.1
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cli                    13.0.4
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

We're running an Nginx reverse-proxy server. I've included a docker-compose file for a simplified (no https) version of our proxy configuration in the repro-app repository.

**Comment by alan-agius4** [comment]
Hi @NeilSorensen,

As the option name indicated, the a host should be provided to the public host options. Path names are ignored.

I did have a look at the reproduction, and I think the root of the problem is actually that the base href is hardcoded in the `index.html`, This is used by the dev-server to determine which path to serve the assets and also the web socket path.

Can you try the below and see if this covers your use-case.

```
ng serve --port 1234
```

```json
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "baseHref": "/foo/",
      ...
  },
```

**Comment by NeilSorensen** [comment]
@alan-agius4 That did the trick, thanks! Sorry for listing it as a bug when it was just a misconfiguration on our part.

**Comment by alan-agius4** [comment]
@NeilSorensen, glad to hear that the issue is solved 😊
