### ISSUE TITLE
Migrating from Angular 12.2.13 to Angular 13.0.2 Unsuccessful Part 2

### ISSUE THREAD

**Issue by benedict-chng** [angular/angular-cli#22316]
Hi,

I raised a support request recently related to the migration of my application from 12.2.13 to 13.0.2 (https://github.com/angular/angular-cli/issues/22229) and @alan-agius4 suggested some way to get around the problem and it did fix the problem I'm facing during migration but when I tried to run the application, I got the following error.

I attach my package.json and package-lock.json for your investigation.

An unhandled exception occurred: ENOENT: no such file or directory, lstat 'C:\Workspace\Nova\Avatar\node_modules\angular-archwizard\archwizard.css'
See "C:\Users\BENEDI~1\AppData\Local\Temp\ng-4vfjyR\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\windows\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! avatar@0.0.0 staff: ng s --project staff --port 4200 --ssl
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the avatar@0.0.0 staff script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\benedictc\AppData\Roaming\npm-cache_logs\2021-12-07T00_59_01_098Z-debug.log

The error for angular-errors.log:

[error] Error: ENOENT: no such file or directory, lstat 'C:\Workspace\Nova\Avatar\node_modules\angular-archwizard\archwizard.css'
at Object.realpathSync (fs.js:1646:7)
at resolveGlobalStyles (C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\webpack\configs\styles.js:53:31)
at getStylesConfig (C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\webpack\configs\styles.js:86:70)
at C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\builders\dev-server\index.js:128:43
at C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\utils\webpack-browser-config.js:72:16
at generateWebpackConfig (C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\utils\webpack-browser-config.js:61:40)
at async generateBrowserWebpackConfigFromContext (C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\utils\webpack-browser-config.js:123:20)
at async generateI18nBrowserWebpackConfigFromContext (C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\utils\webpack-browser-config.js:70:20)
at async setup (C:\Workspace\Nova\Avatar\node_modules@angular-devkit\build-angular\src\builders\dev-server\index.js:124:47)

[package.zip](https://github.com/angular/angular-cli/files/7672073/package.zip)

**Comment by alan-agius4** [comment]
From the error above, it appears that one of the css files that you are referencing doesn’t exist 

```
An unhandled exception occurred: ENOENT: no such file or directory, lstat 'C:\Workspace\Nova\Avatar\node_modules \angular-archwizard\archwizard.css'
```

**Comment by alan-agius4** [comment]
From https://github.com/angular/angular-cli/issues/22322

> Hi @benedict-chng,
> 
> Apologies about that. Although the issue template was ignored and neglected to provide the required information to investigate an potentiation issue. I thought that the error was self explanatory enough (`An unhandled exception occurred: ENOENT: no such file or directory, lstat 'C:\Workspace\Nova\Avatar\node_modules\angular-archwizard\archwizard.css`.)
> 
> This indicates that you are referring an incorrect path likely you have some mis-configuration in your `angular.json`.
> 
> If the problem persists, ensure you provide all of the required information when filling out the issue template including a minimal reproduction. Issues without the required information will be closed. You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by benedict-chng** [comment]
Hi @alan-agius4,

I've figured out the problem.  Originally I have thought the library "angular-archwizard" is part of the Angular framework. They had moved the CSS file to another location and that is why our application no longer compiles. I have now fixed the issue by changing angular.json file to update the location of the css file.

You can now close the issue.

Thanks!
Benedict
