### ISSUE TITLE
Changing properties from "name" to "any variable" it breaks the schematics

### ISSUE THREAD

**Issue by aminetchitooss** [angular/angular-cli#22319]
# 🐞 Changing properties from "name" to "prop" it breaks the schematics

## 🔬Error
An error occured:
ReferenceError: prop is not defined
    at eval (eval at template (/Users/user/Desktop/schematics/create-file/node_modules/@angular-devkit/core/src/utils/template.js:254:16), <anonymous>:16:18)
 
## In schema.json
<pre><code>
 {
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "MyFullSchematicsSchema",
	"title": "My Full Schematics Schema",
	"type": "object",
	"properties": {
		"prop": {
			"type": "string",
			"x-prompt": "What is your prop?"
		}
	},
	"required": ["prop"]
}

</code></pre>

## 🌍 In the file to create

<pre><code>
  Hello <%= prop %>, I'm a schematic.

</code></pre>

After executing this :
<pre><code>
schematics .:my-full-schematic
</code></pre>

**Comment by alan-agius4** [comment]
You also need to change

  https://github.com/angular/angular-cli/blob/5e7fcee0eca85f8e08af371c16987a2a7548c27d/packages/angular_devkit/schematics_cli/schematic/files/src/my-full-schematic/index.ts#L48
