### ISSUE TITLE
ng generate service: Project "undefined" does not exist.

### ISSUE THREAD

**Issue by greenpau** [angular/angular-cli#22332]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No.

### Description

Failed generating Angular service.

I am working on creating a standalone service (later will publish to npm). My thinking is I need to generate a workspace and after that, I generate a service. Perhaps, I am missing a step.

## 🔬 Minimal Reproduction

First, cloned empty project and tested the generation of new Angular workspace.

```bash
mkdir ngx-authp-service
cd ngx-authp-service
ng new ngx-authp-service --create-application=false --commit=false --routing=false --style=scss --directory=./ --dry-run
```

The dry run has the following output:

```
CREATE README.md (1061 bytes)
CREATE .editorconfig (274 bytes)
CREATE .gitignore (620 bytes)
CREATE angular.json (139 bytes)
CREATE package.json (1033 bytes)
CREATE tsconfig.json (863 bytes)
CREATE .vscode/extensions.json (130 bytes)
CREATE .vscode/launch.json (474 bytes)
CREATE .vscode/tasks.json (938 bytes)
```

Next, created the workspace:

```bash
ng new ngx-authp-service --create-application=false --commit=false --routing=false --style=scss --directory=./ --skip-install=true
```

The state of the repo prior to trying to generate the service: https://github.com/greenpau/ngx-authp-service/commit/911cd3a4a1fe1c1106256768329f161474f54410

After that, attempted to create `ngx-authp-service` service:

```bash
ng generate service ngx-authp-service
```

## 🔥 Exception or Error

<pre><code>
$ ng generate service ngx-authp-service
Project "undefined" does not exist.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.0
Node: 14.17.6
Package Manager: npm 8.1.2
OS: linux x64

Angular: <error>
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.0 (cli-only)
@angular-devkit/core         13.1.0 (cli-only)
@angular-devkit/schematics   13.1.0 (cli-only)
@angular/cli                 13.1.0 (cli-only)
@schematics/angular          13.1.0 (cli-only)
rxjs                         6.6.7 (cli-only)
typescript                   4.4.3 (cli-only)
</code></pre>

**Anything else relevant?**

No.

**Comment by greenpau** [comment]
After I added the project manually,

```diff
diff --git a/angular.json b/angular.json
index 0763165..93ccf17 100644
--- a/angular.json
+++ b/angular.json
@@ -3,5 +3,12 @@
   "version": 1,
   "newProjectRoot": "projects",
   "projects": {
-  }
+      "ngx-authp-service": {
+          "projectType": "library",
+          "root": "projects/ngx-authp-service",
+          "sourceRoot": "projects/ngx-authp-service/src",
+          "prefix": "lib"
+      }
+  },
+  "defaultProject": "ngx-authp-service"
 }
```

The service generation worked.

```
$ ng generate service ngx-authp-service
CREATE projects/ngx-authp-service/src/lib/ngx-authp-service.service.spec.ts (404 bytes)
CREATE projects/ngx-authp-service/src/lib/ngx-authp-service.service.ts (144 bytes)
```

**Comment by MurhafSousli** [comment]
Hi @greenpau 👋

The `undefined` error you got was caused by the missing property `defaultProject` in angular.json file.

If you've used the command `ng g library ngx-authp-service` after you created the empty workspace, it would have set it automatically for you.

**Comment by alan-agius4** [comment]
The is working as intended as project need to be declared and configured in `angular.json`.

As mentioned above, a library project should be created using the `ng generate library` command.

See https://angular.io/guide/creating-libraries for more information.

**Comment by greenpau** [comment]
@MurhafSousli , @alan-agius4 , thank you for looking into this! 👍
