### ISSUE TITLE
Production build - "is not a function", works in Serve 

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#22346]
Hi i can imagine, it is very hard to debug this issue, but i have not  any chance how to provide minimaln reproduction.

When i serve production build:

node --max_old_space_size=8096 ./node_modules/@nrwl/cli/bin/nx serve app --configuration=production

everything works. But when i build:
node --max_old_space_size=8096 ./node_modules/@nrwl/cli/bin/nx serve app --configuration=production

application crashes when i input several chars into input (but only when 5ft element+).

![image](https://user-images.githubusercontent.com/10418323/145578296-6d029230-cae7-464e-a5aa-73dea6ab4423.png)

We are using 70 buildable libraries in NX monorepo.

maybe you will be able to find the cause... 

thanks you very much.

Strange is.. that if i delete all characters from input and start typing from start.. everything works.. until  5th char...

**Comment by montella1507** [comment]
I have found, that problem is:

`
import * as moment from 'moment';
...

 if (!!value && (value as unknown as string).length > 4
      && moment(value + '', [moment.ISO_8601], true).isValid()) {
      const date = new Date(value as unknown as string);
      if (date.toString() === 'Invalid Date') {
        super.setValue(value, options);
      } else {
        super.setValue(date, options);
      }
    } else {
      super.setValue(value, options);
    }


`

**Comment by alan-agius4** [comment]
@montella1507, please provide the output of `ng v`?

**Comment by montella1507** [comment]
Ah sorry, just forgot.

NX --version: 13.2.3
NG --version:  13.2.3
Node -v :  16.13.3
NPM -v:  8.1.2
```

"dependencies": {
    "@angular/animations": "13.0.0",
    "@angular/cdk": "13.0.0",
    "@angular/common": "13.0.0",
    "@angular/compiler": "13.0.0",
    "@angular/core": "13.0.0",
    "@angular/flex-layout": "^13.0.0-beta.36",
    "@angular/forms": "13.0.0",
    "@angular/material": "13.0.0",
    "@angular/platform-browser": "13.0.0",
    "@angular/platform-browser-dynamic": "13.0.0",
    "@angular/router": "13.0.0",
    "@angular/service-worker": "13.0.0",
    "@angularclass/hmr": "^2.1.3",
    "@asymmetrik/ngx-leaflet": "^8.1.0",
    "@babel/runtime": "^7.16.3",
    "@fullcalendar/core": "^4.1.0",
    "@google/maps": "^1.1.0",
    "@ngneat/transloco": "^2.23.5",
    "@ngrx/data": "13.0.1",
    "@ngrx/effects": "13.0.1",
    "@ngrx/entity": "13.0.1",
    "@ngrx/router-store": "13.0.1",
    "@ngrx/store": "13.0.1",
    "@ngrx/store-devtools": "13.0.1",
    "@ngworker/lumberjack": "^2.0.3",
    "@nrwl/angular": "13.2.3",
    "@nrwl/cli": "13.2.3",
    "@rx-angular/cdk": "^1.0.0-alpha.10",
    "@stomp/ng2-stompjs": "^8.0.0",
    "@tiptap/core": "^2.0.0-beta.129",
    "@tiptap/extension-bubble-menu": "^2.0.0-beta.43",
    "@tiptap/extension-character-count": "^2.0.0-beta.14",
    "@tiptap/extension-floating-menu": "^2.0.0-beta.37",
    "@tiptap/extension-font-family": "^2.0.0-beta.16",
    "@tiptap/extension-highlight": "^2.0.0-beta.26",
    "@tiptap/extension-link": "^2.0.0-beta.24",
    "@tiptap/extension-mention": "^2.0.0-beta.80",
    "@tiptap/extension-placeholder": "^2.0.0-beta.37",
    "@tiptap/extension-text-align": "^2.0.0-beta.24",
    "@tiptap/extension-text-style": "^2.0.0-beta.18",
    "@tiptap/extension-underline": "^2.0.0-beta.17",
    "@tiptap/starter-kit": "^2.0.0-beta.131",
    "@types/mousetrap": "^1.6.8",
    "@zxing/browser": "0.0.5",
    "@zxing/library": "^0.18.6",
    "@zxing/ngx-scanner": "^3.2.0",
    "ag-grid-angular": "^26.2.0",
    "ag-grid-community": "^26.2.0",
    "ag-grid-enterprise": "^26.2.0",
    "angular-calendar": "^0.28.28",
    "angular-resizable-element": "^3.4.0",
    "angular2-signaturepad": "^3.0.4",
    "bpmn-js": "^8.8.2",
    "bpmn-js-properties-panel": "^0.43.1",
    "chart.js": "^3.6.0",
    "chartjs-adapter-moment": "^1.0.0",
    "chartjs-gauge": "^0.3.0",
    "chartjs-plugin-annotation": "^1.0.2",
    "chartjs-plugin-datalabels": "^2.0.0",
    "ckeditor4-angular": "^1.1.0",
    "core-js": "^3.19.0",
    "dagre": "^0.8.5",
    "date-fns": "^2.25.0",
    "diagram-js": "^7.6.0",
    "dmn-js": "^11.0.2",
    "file-saver": "^2.0.2",
    "fullcalendar": "^3.10.4",
    "handlebars": "^4.7.7",
    "hast-util-to-html": "^7.1.3",
    "highlight.js": "^10.7.3",
    "html2canvas": "^1.3.2",
    "jexl": "^2.3.0",
    "jquery": "^3.6.0",
    "json-ast": "^2.1.7",
    "jsplumb": "^2.15.6",
    "jszip": "^3.7.1",
    "jwt-decode": "^2.2.0",
    "leaflet": "^1.6.0",
    "leaflet-draw": "^1.0.4",
    "lodash-es": "^4.17.21",
    "moment": "^2.29.1",
    "monaco-editor": "^0.21.3",
    "mousetrap": "^1.6.5",
    "net": "^1.0.2",
    "ngx-file-drop": "^11.2.0",
    "ngx-tiptap": "^3.0.4",
    "object-path": "^0.11.8",
    "partial-json-parser": "^1.2.2",
    "pica": "^7.1.0",
    "primeflex": "^3.1.0",
    "primeicons": "^5.0.0",
    "primeng": "^13.0.0",
    "resize-observer-polyfill": "^1.5.1",
    "rxjs": "7.4.0",
    "s": "^1.0.0",
    "sass": "^1.43.3",
    "stompjs": "^2.3.3",
    "stream": "0.0.2",
    "svg-parser": "^2.0.4",
    "terser": "4.6.7",
    "tippy.js": "^6.3.2",
    "to-json-schema": "^0.2.5",
    "tslib": "^2.3.1",
    "uuid": "^8.3.2",
    "whatwg-fetch": "^3.6.2",
    "xlsx": "^0.17.3",
    "xml-js": "^1.6.11",
    "zone.js": "0.11.4"
  },
  "devDependencies": {
    "@aerokube/cypress-moon": "^1.0.4",
    "@angular-devkit/build-angular": "13.0.3",
    "@angular-eslint/eslint-plugin": "12.6.1",
    "@angular-eslint/eslint-plugin-template": "12.6.1",
    "@angular-eslint/template-parser": "12.6.1",
    "@angular/cli": "13.0.3",
    "@angular/compiler-cli": "13.0.0",
    "@angular/language-service": "13.0.0",
    "@babel/core": "^7.15.8",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-proposal-private-methods": "^7.14.5",
    "@babel/plugin-syntax-class-properties": "^7.12.13",
    "@babel/preset-env": "^7.15.8",
    "@babel/preset-typescript": "^7.15.0",
    "@compodoc/compodoc": "^1.1.15",
    "@cypress/webpack-preprocessor": "^5.9.1",
    "@ngneat/transloco-keys-manager": "^2.7.5",
    "@ngrx/schematics": "13.0.1",
    "@nrwl/builders": "^7.8.7",
    "@nrwl/cypress": "13.2.3",
    "@nrwl/eslint-plugin-nx": "13.2.3",
    "@nrwl/jest": "13.2.3",
    "@nrwl/workspace": "13.2.3",
    "@types/file-saver": "^2.0.3",
    "@types/jest": "27.0.2",
    "@types/jquery": "^3.5.8",
    "@types/json-schema": "6.0.1",
    "@types/leaflet": "^1.7.5",
    "@types/node": "^14.14.33",
    "@types/svg-parser": "^2.0.3",
    "@typescript-eslint/eslint-plugin": "4.3.0",
    "@typescript-eslint/parser": "4.33.0",
    "babel-loader": "^8.2.3",
    "codelyzer": "^6.0.0",
    "copy-dir": "^1.3.0",
    "cypress": "^8.7.0",
    "cypress-file-upload": "^4.1.1",
    "dotenv": "10.0.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-cypress": "^2.12.1",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jsdoc": "30.7.6",
    "eslint-plugin-prefer-arrow": "1.2.2",
    "jest": "27.2.3",
    "jest-preset-angular": "11.0.0",
    "mocha": "^8.4.0",
    "mochawesome": "^6.3.1",
    "mochawesome-merge": "^4.2.0",
    "mochawesome-report-generator": "^5.2.0",
    "ng-packagr": "13.0.7",
    "ngx-build-plus": "^11.0.0",
    "ts-jest": "27.0.5",
    "ts-node": "^9.1.1",
    "typescript": "4.4.4",
    "webpack": "^5.64.4"
  }
```

**Comment by montella1507** [comment]
Moments imports in application (all occurrances):

import * as moment from 'moment';
import moment, {Moment} from 'moment';
import moment, {MomentInput} from 'moment';
import moment from "moment";

**Comment by alan-agius4** [comment]
@montella1507, it would be great if you can provide a minimal reproduction that we can clone and take a look at. Does this happen only in production mode?

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by montella1507** [comment]
Is IT possible to send you privately?

**Comment by alan-agius4** [comment]
Ideally it’s a minimal reproduction that contains the bare minimum code to reproduce the problem.

But sure you can share the reproduction privately. Check my GH profile.

**Comment by montella1507** [comment]
> Ideally it’s a minimal reproduction that contains the bare minimum code to reproduce the problem.
> 
> But sure you can share the reproduction privately. Check my GH profile.

will do our best.. we will try to provide as minimal code   as possible. ETA  14-15.12. Thanks.

**Comment by montella1507** [comment]
Hi @alan-agius4  here is the reproduction: 
[repro.zip](https://github.com/angular/angular-cli/files/7712033/repro.zip)


- extract
- npm ci 
- run  "nordic-prod-build" to build production build with builadble libraries  (**node --max_old_space_size=8096 ./node_modules/@nrwl/cli/bin/nx build nordic --configuration=production --output-hashing=all**)
- serve dist folder  ( **http-server --port=3000 --cors** ) 
- input  5+ characters to input 
![image](https://user-images.githubusercontent.com/10418323/146009366-6b02b13f-709c-4a93-838d-50c556d5f56f.png)


INFO:
- moment() is undefined in prod build  inside **tsm-form-control.ts** 
- it works when SERVING prod build 
- it works when SERVING non prod-build 
- DOESNT work when BUILD prod build and then serve with any http-server

**Comment by montella1507** [comment]
@alan-agius4  

// ERROR
import * as moment from 'moment';

// OK
import  moment from 'moment/moment';

however.. why it doesnt work ONLY in PROD BUILD and it works in PROD SERVE / non-prod serve / build...

Should't it throw an error during build then?

**Comment by alan-agius4** [comment]
Hi, 

The problem appears that moment is not being imported as recommended through the default import https://momentjs.com/docs/#/use-it/typescript/

```
import moment from 'moment';
```




The reason why this works in during serve, is that NX don't build the libraries as their own compilation unit, but they build the libraries as part of the application. This of course can lead to such inconsistent behaviour, since applications and libraries build pipeline is completely different. 

In fact during the library build you are shown warnings about possible issues with how moment is being used. 

```
WARNING: Cannot call a namespace ('moment')
```

**Comment by montella1507** [comment]
> In fact during the library build you are shown warnings about possible issues with how moment is being used.

> WARNING: Cannot call a namespace ('moment')

i didnt get any warning during build, what command are you running, please?

**Comment by alan-agius4** [comment]
Yeah you need to enable `allowSyntheticDefaultImports`.

 I got the warning by building using the Angular CLI.

**Comment by montella1507** [comment]
Okay, thank you very much for your time.
