### ISSUE TITLE
Webpack assets modules support

### ISSUE THREAD

**Issue by And2s** [angular/angular-cli#22351]
### Description

Until v13.1.0 was possible to use this implementation to import images:
new URL('./image.png', import.meta.url).pathname
provided by webpack documentation https://webpack.js.org/guides/asset-modules/

Since Angular v13.1.0 this approach does not work.

### Proposed solution

Implement support for Webpack asset modules support.
https://webpack.js.org/guides/asset-modules/

Sometimes it is much more convenient to write such imports and provide urls for reusable components  e.g. <app-landing-block [image]="url">. Without imports in .ts files, the images must be always predefined directly in component and imported through .scss / .less file. And such an approach sometimes becomes too difficult depending on situation.

### Alternatives considered

Currently it is only possible to import image through .scss / .less file or directly into assets folder.

**Comment by alan-agius4** [comment]
Hi @And2s, 

Thanks for opening this request. However, Webpack specific features are not supported by the Angular CLI. The fact that Webpack is used is an implementation detail that change can in the future.

The supported way to references assets in templates and TypeScript files is by using the the [`assets`](https://angular.io/guide/workspace-config#assets-configuration) option and reference the emitted file URL in the template/TS file.

**Comment by And2s** [comment]
Hi @alan-agius4, thanks for info. Will there be a support for something like webpack asset modules in the future? Personally I did not have many implementations but in some cases it is a very useful feature which helps to maintain clear structure.

**Comment by alan-agius4** [comment]
I noticed that when web-workers are enabled we allowing parsing `new URL` syntax which has the side-effect that Webpack will treat all assets as asset modules (https://webpack.js.org/guides/asset-modules/#url-assets).

This is an inconsistency that we should tackle.

**Comment by alan-agius4** [comment]
Hi @And2s,

We have discussed this during yesterday team meeting. 

We feel that we shouldn't enable assets modules as this is strictly a Webpack feature which will not work if in the future we move away to a different bundler.

We do agree that there is an inconsistency that we finger print assets in CSS but not in HTML templates. Let's continue tracking this in https://github.com/angular/angular-cli/issues/22510
