### ISSUE TITLE
Assets changes notified as Not Changed on ng serve in v13

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular-cli#22355]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v12

### Description

after `ng serve` when i try to modify the assets it. it is not reloading the page. In console it is printed as `Nothing Changed`.
But i actually changed a file content in assets.

## 🔬 Minimal Reproduction

clone this [repo](https://github.com/sheikalthaf/wind.git).
After `ng serve` try to change any content of svg file in assets and save it. And you will see that `Nothing Changed` in console. Also the app not get reloaded

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@angular/flex-layout            12.0.0-beta.35
@angular/pwa                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sheikalthaf** [comment]
@alan-agius4 update the minimal reproduction. Thanks

**Comment by alan-agius4** [comment]
@sheikalthaf, I don’t see any assets being referenced in the reproduction.

Where are the assets stored and how are they referenced ?

**Comment by sheikalthaf** [comment]
@alan-agius4 failed to commit the changes. Please check now. Sorry for the trouble

**Comment by alan-agius4** [comment]
Hi @sheikalthaf, 

Thanks for the reproduction. I did take a look and it appears that this is an issue with webpack/webpack-dev-server.

Unfortunately, this is not actionable from our end.
