### ISSUE TITLE
`JavaScript heap out of memory` after running serve

### ISSUE THREAD

**Issue by wesselvdv** [angular/angular-cli#22352]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

Angular CLI v12

### Description

Running `ng serve` with `NODE_OPTIONS=--max_old_space_size=8192` it will eventually give an out of memory error.

## 🔬 Minimal Reproduction

Running `ng serve` (`NODE_OPTIONS`) on my project causes it to fail with out of memory exception.

## 🔥 Exception or Error

<pre><code>
Warning: This is a simple server for use in testing or debugging Angular applications
locally. It hasn't been reviewed for security issues.

Binding this server to an open connection can result in compromising your application or
computer. Using a different host than the one passed to the "--host" flag might result in
websocket connection issues. You might need to use "--disable-host-check" if that's the
case.
⠙ Generating browser application bundles (phase: setup)...

Wrote snapshot to /workspace/apps/client/Heap.20211210.155509.82.0.001.heapsnapshot

<--- Last few GCs --->

[82:0x7fca98135330]    51036 ms: Scavenge 1019.0 (1042.8) -> 1017.5 (1042.8) MB, 3.4 / 0.0 ms  (average mu = 0.263, current mu = 0.204) allocation failure
[82:0x7fca98135330]    51052 ms: Scavenge 1019.3 (1042.8) -> 1017.9 (1043.1) MB, 3.1 / 0.0 ms  (average mu = 0.263, current mu = 0.204) allocation failure
[82:0x7fca98135330]    51066 ms: Scavenge 1019.7 (1043.1) -> 1018.3 (1047.6) MB, 3.2 / 0.0 ms  (average mu = 0.263, current mu = 0.204) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.1.0
Node: 16.13.0
Package Manager: npm 8.1.0
OS: linux x64

Angular: 13.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.0
@angular-devkit/build-angular   13.1.0
@angular-devkit/core            13.1.0
@angular-devkit/schematics      13.1.0
@schematics/angular             13.1.0
rxjs                            7.4.0
typescript                      4.5.3
webpack                         5.65.0
</code></pre>

**Anything else relevant?**

I am making use of `tailwindcss` 3 with JIT. As can be seen in the error message, I have a heapsnapshot of a failed `ng serve` with `NODE_OPTIONS=--max_old_space_size=1024`. This is a bit big to share easily (1.4G), so I'd like some advice on how best to disclose this.

**Comment by wesselvdv** [comment]
![pic-selected-211210-2128-42](https://user-images.githubusercontent.com/286577/145637368-337063be-c7f9-405e-b10b-3c7740056ef8.png)

**Comment by wesselvdv** [comment]
I could try to run it with generating a heap snapshot for when running `ng serve` with `NODE_OPTIONS=--max_old_space_size=8192`, it took almost 2 hours to get a heap snapshot with `NODE_OPTIONS=--max_old_space_size=1024`. Also I am not sure if I am still able to load a snapshot of that size into devtools in chrome afterwards.

**Comment by wesselvdv** [comment]
> I could try to run it with generating a heap snapshot for when running `ng serve` with `NODE_OPTIONS=--max_old_space_size=8192`, it took almost 2 hours to get a heap snapshot with `NODE_OPTIONS=--max_old_space_size=1024`. Also I am not sure if I am still able to load a snapshot of that size into devtools in chrome afterwards.

I tried to get a memory snapshot when running with `ng serve` with `NODE_OPTIONS=--max_old_space_size=8192`, but this ran for a day or so and eventually crashing without giving me a heap snapshot.

**Comment by alan-agius4** [comment]
@wesselvdv, 

Does it help to remove the cache directory?

```
rm -rf .angular
```

From the first stack it appears that the OOM is being thrown during the setup phase. If you project however is large, I'd expected this when using `--max_old_space_size=1024` since this is quite low considering the default is 2Gb.

It is also strange that it is taking so long to create a heap snapshot, are you using Chrome to create it or a different tool?

**Comment by wesselvdv** [comment]
> @wesselvdv,
> 
> Does it help to remove the cache directory?
> 
> ```
> rm -rf .angular
> ```
> 
> From the first stack it appears that the OOM is being thrown during the setup phase. If you project however is large, I'd expected this when using `--max_old_space_size=1024` since this is quite low considering the default is 2Gb.
> 
> It is also strange that it is taking so long to create a heap snapshot, are you using Chrome to create it or a different tool?

I am using the builtin mechanism in nodejs —heapsnapshot-near-heap-limit=1

**Comment by alan-agius4** [comment]
@wesselvdv, 

- What is the mean memory usage of your application build? There is a quite a gap better 1024 and 8194.
- Does this happen on the first build or after a number of rebuilds?
- Does the OOM happen when not using Tailwinds 2.x.x?

**Comment by wesselvdv** [comment]
> @wesselvdv,
> 
> * What is the mean memory usage of your application build? There is a quite a gap better 1024 and 8194.

I have no idea tbh, I just ran it with 4096 and an existing `.angular` and it crashes with an OOM during the first rebuild after a successful initial one in `ng serve`

> * Does this happen on the first build or after a number of rebuilds?

After `n` rebuilds, and clearing the .angular or increasing the memory seems to have a positive effect on `n`.

> * Does the OOM happen when not using Tailwinds 2.x.x?

I am not using TailwindCSS 2.x.x, I am using TailwindCSS 3.x.x. Should I try a downgrade?

I can btw. get a devtools attached that triggers a breakpoint when it goes OOM. I just can't get a heapsnapshot without crashing Chrome/Brave.

**Comment by alan-agius4** [comment]
> I am not using TailwindCSS 2.x.x, I am using TailwindCSS 3.x.x. Should I try a downgrade?
Just to confirm that you are using TailwindCSS V3 with Angular CLI 12?

> I can btw. get a devtools attached that triggers a breakpoint when it goes OOM. I just can't get a heapsnapshot without crashing Chrome/Brave.

I think the best action here, is to take snapshots after a couple of incremental builds, and compare to see which extra symbols are retained.

- Did you set any `max_old_space_size` in v12?
- Does the OOM happen when you modify a particular module/file or it's random?
- If does the OOM happen if you disable the cache completely `ng config cli.cache.enabled false`?

**Comment by wesselvdv** [comment]
> Just to confirm that you are using TailwindCSS V3 with Angular CLI 12?

No, I wasn't. I was using tailwindcss v2.x.x with JIT enabled. I believe the major change in Tailwindcss 3.x.x is that JIT is enabled by default.
 
> I think the best action here, is to take snapshots after a couple of incremental builds, and compare to see which extra symbols are retained.

What's the most robust method to get meaningful snapshots? I can't get it to build without setting max_old_space_size to 4096 or higher. Not sure if I can even get chrome to snapshot that.

> * Did you set any `max_old_space_size` in v12?
Yes, I did. I have put that to 8192 as long as I can remember tbh, and I have been using angular for roughly 5-6 years now.

> * Does the OOM happen when you modify a particular module/file or it's random?

I haven't paid that much attention as to when, but it seems the bigger the change the larger the chance it goes OOM.

> * If does the OOM happen if you disable the cache completely `ng config cli.cache.enabled false`?

I haven't tried this yet, will do and come back with results.

**Comment by wesselvdv** [comment]
@alan-agius4 I've been running a full day with cache disabled, memory usage still grows but it seems to stop and hover around 8Gb. It is however painfully slow, I have rebuilds that take more than a minute for a minute change.

**Comment by wesselvdv** [comment]
Unfortunately I just got another OOM, appears it just took a lot longer without cache, but it does still happen.

**Comment by alan-agius4** [comment]
@wesselvdv, unfortunately without memory heap snapshots there is not much we can investigate here.

**Comment by wesselvdv** [comment]
@alan-agius4 I agree, hence my question regarding those nearly a month back:

> What's the most robust method to get meaningful snapshots? I can't get it to build without setting max_old_space_size to 4096 or higher. Not sure if I can even get chrome to snapshot that.

I have no idea how to snapshot it, every attempt thus far resulted in a crash without a memory heap snapshot.

**Comment by jpike88** [comment]
Ridiculous use of memory with ng serve after a few refreshes. What exactly is deciding to retain that much memory? Why is this ok?

![Screen Shot 2022-01-25 at 16 36 43](https://user-images.githubusercontent.com/9585787/150950951-3b3c7d38-97ad-4be1-b729-6b28a0718ed7.png)

**Comment by alan-agius4** [comment]
@jpike88, again with memory snapshots we cannot determine what is the problem if any.

**Comment by alan-agius4** [comment]
Closing as we have not received a reproduction or memory snapshots.  Please update to the most recent version and If the problem persists in your application after upgrading, please open a new issue with all the necessary information.
