### ISSUE TITLE
Provide an ability to perform tree-shaking but retain symbol names

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular-cli#22354]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] build

### Description

Currently it's not possible to use `ng build` to perform dead code elimination via Terser, but retain symbol names in generated JS bundle. It'd be useful to have this capability to simplify bundle size-related investigations (which often times involves looking for retained symbols).

// cc @alan-agius4

**Comment by alan-agius4** [comment]
What myself and @AndrewKushnir observed was that using `NG_BUILD_MANGLE=0` caused a lot of dead code such as `DebugNode` to be retained.

```
ng config cli.cache.enabled false
NG_BUILD_MANGLE=0 ng build
```

**Comment by johncrim** [comment]
I use this to test non-mangled production output:

```cross-env NG_BUILD_DEBUG_OPTIMIZE=minify,beautify ng build --configuration production --output-hashing none ```

Does that suffer from the same problem?

**Comment by alan-agius4** [comment]
@johncrim, yeah since in that case mangled is disabled. At least in v13, you can verify this by looking for `DebugNode`, if it’s found  DCE didn’t fully work.
