### ISSUE TITLE
Named export 'UnaryOperator' not found. The requested module '@angular/compiler' is a CommonJS module, which may not support all module.exports as named exports

### ISSUE THREAD

**Issue by rat-matheson** [angular/angular-cli#22366]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.2.14

### Description

I just upgraded to angular 13 and now when I build a library in a repo using ```ng build @myproject/mylibrary``` I get the following error.

> Building Angular Package
> Named export 'UnaryOperator' not found. The requested module '@angular/compiler' is a CommonJS module, which may not support all module.exports as named exports.
> CommonJS modules can always be imported via the default export, for example using:
> 
> import pkg from '@angular/compiler';

I have other library projects which I have been able to upgrade successfully so it is unclear why this one in particular is having the problem.  No where in my project do I import UnaryOperator or anything from @angular/compiler

## 🔬 Minimal Reproduction

I am unable to recreate the issue in a general way.  It is not clear why every library in this one project workspace has the issue and I am not allowed to put the whole project workspace on github

## 🔥 Exception or Error

<pre><code>

Building Angular Package
Named export 'UnaryOperator' not found. The requested module '@angular/compiler' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@angular/compiler';
</code></pre>

## 🌍 Your Environment

<pre><code>

windows 10
node 16.13.1
angular 13.1.0
</code></pre>

**Anything else relevant?**

The particular library I'm building has no runtime dependencies on anything angular related. 

```
  "peerDependencies": {
    "@tower-poi/errors": "~2.0.0",
    "google-auth-library": "^7.10.4",
    "normalize-email": "^1.1.1",
    "rxjs": ">= 6.5.5"
  },
  "dependencies": {
    "tslib": "^2.0.0"
  }
```

@tower-poi/errors is in a different project workspace and builds fine with angular 13.  Its ​dependencies
​are:
```  
"peerDependencies": {
   ​"class-validator": "^0.13.1",
   ​"rxjs": ">= 6.5.5"
 ​},
 ​"peerDependenciesMeta": {
   ​"class-validator": {
     ​"optional": true
   ​},
   ​"rxjs": {
     ​"optional": true
   ​}
 ​},
 ​"dependencies": {
   ​"tslib": "^2.0.0"
 ​}
```

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by rat-matheson** [comment]
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / Γû│ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.1.1
Node: 16.13.1
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.1.0
... cdk, common, compiler-cli, core, forms, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.1
@angular-devkit/build-angular   13.1.1
@angular-devkit/core            13.1.1
@angular-devkit/schematics      13.1.1
@angular/cli                    13.1.1
@schematics/angular             13.1.1
ng-packagr                      13.1.1
rxjs                            7.4.0
typescript                      4.5.3
```

**Comment by JoostK** [comment]
The `UnaryOperator` export was added in Angular 10.1, and given that the error message mentions that `@angular/compiler` is in CommonJS format there must be an outdated version of `@angular/compiler` present somewhere, as v13 of Angular packages do not ship CommonJS format anymore.

Please list the output of `npm ls @angular/compiler` or `yarn why @angular/compiler` which may indicate where the dependency comes from.

**Comment by rat-matheson** [comment]
Fantastic.  Thanks for the help

```
$ npm ls @angular/compiler
tower-secure@1.1.0 C:\...\packages\myProject
Γö£ΓöÇΓö¼ @angular/compiler-cli@13.1.0
Γöé ΓööΓöÇΓöÇ @angular/compiler@9.0.0 invalid: "13.1.0" from node_modules/@angular/compiler-cli
ΓööΓöÇΓö¼ codelyzer@6.0.2
  ΓööΓöÇΓöÇ @angular/compiler@9.0.0 deduped invalid: "13.1.0" from node_modules/@angular/compiler-cli

npm ERR! code ELSPROBLEMS
npm ERR! invalid: @angular/compiler@9.0.0 C:\Users\...\packages\myProject\node_modules\@angular\compiler
```

So the issue was codelyzer.  I needed to remove it and install [angular-eslint](https://github.com/angular-eslint/angular-eslint) and follow the updating from v12 steps.  In addition, I had to remove my node_modules folder and reinstall @angular/compiler.  All is good now.

Thanks so much!

**Comment by JoostK** [comment]
Ok, that's a bit strange given that Codelyzer has an internal dependency on the compiler. A package manager should have installed that dependency locally to Codelyzer, but it seems like it was hoisted to your workspace root and became visible to all of the other dependencies as well. In such cases, removing the lockfile and node_modules and reinstalling from scratch usually helps to prevent the incorrectly hoisted dependency.

Thanks for following up with the resolution!
