### ISSUE TITLE
[Angular 13] Build not updating on referenced SCSS file changes when cache enabled

### ISSUE THREAD

**Issue by johncrim** [angular/angular-cli#22371]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I think so, but not 100% sure. I didn't experience this issue using the `NG_PERSISTENT_BUILD_CACHE=1` build cache in Angular 12.

### Description

Given SCSS errors in files that are inside the workspace, but outside the angular project folder, re-running the build with caching enabled gives me old SCSS errors (they have been fixed since the prior build). If I manually delete the `.angular` folder the error goes away, as expected.

## 🔬 Minimal Reproduction

I don't have a simple repro right now - I will work on creating one if this is not an obvious bug, and is not eg a webpack or non-angular issue.

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.1.1
Node: 16.12.0
Package Manager: yarn 1.22.15
OS: win32 x64

Angular: 13.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.1
@angular-devkit/build-angular   13.1.1
@angular-devkit/core            13.1.1
@angular-devkit/schematics      12.2.14
@angular/cli                    13.1.1
@schematics/angular             13.1.1
ng-packagr                      13.1.1
rxjs                            7.4.0
typescript                      4.4.4
webpack                         5.65.0
</code></pre>

**Comment by alan-agius4** [comment]
@johncrim, a reproduction would definitely be helpful here since this might be related to
Folder structure.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by johncrim** [comment]
Will do, working on it right now.

**Comment by johncrim** [comment]
I spent some time trying to create a repro case for this, and wasn't able to. The SCSS files that weren't rebuilding were transitive dependencies of the global `styles.scss` file (not transitive dependencies of component SCSS files as far as I could tell), referenced via `@use`. Creating a similar but simpler case for that has not worked for reproducing the issue.

After spending some time on the repro case, I now find that I'm not able to trigger this bug at all. So, closing the issue.

**Comment by michaelurban** [comment]
I'm seeing this too. If there's an error in my scss the cached, invalid, code will keep getting re-evaluated. All updates to the scss are ignored until the cache is deleted manually.

**Comment by alan-agius4** [comment]
@michaelurban, please file a new issue with a reproduction. Thank you.
