### ISSUE TITLE
Duplicate translations for message '9182224963637946835' when merging after update to Angular 13.1

### ISSUE THREAD

**Issue by hheexx** [angular/angular-cli#22398]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

After updating to Angular 13.1 i have ton of warnings in console that look like this:

WARNING [locales/messages.sr.xlf]: Duplicate translations for message '9088279543992873374' when merging

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 13.1.1
Node 16.13.1
npm 8.1.2
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by hheexx** [comment]
Ill try that in few weeks if it's not fixed by then.
Let's wait for now to see if I'm only one with this or there are more people....

Our usage of localization is pretty basic so I assume there will be more people.

**Comment by alan-agius4** [comment]
Does this happen during serve or build?

**Comment by hheexx** [comment]
serve

**Comment by JoniJnm** [comment]
I have the same problem after upgrading to v13

The warnings appears after the first rebuild (I mean, the first "build" while serving is ok, but if I modify a file I see this warnings)

I will try to create a new project to reproduce the problem

**Comment by hheexx** [comment]
I confirm same behavior.
@JoniJnm, have in mind that problem is just in 13.1. 13.0 is ok.

**Comment by JoniJnm** [comment]
The repository: https://github.com/JoniJnm/bug-22398

Use "npm start", modify a file and see the i18n warnings

**Comment by destus90** [comment]
We are facing the same issue after upgrading to the newest version. Glad to see we are not the only ones.

**Comment by bbarry** [comment]
I believe it was caused by https://github.com/angular/angular-cli/issues/16341

More specifically the reload here: https://github.com/angular/angular-cli/issues/16341 doesn't re-initialize `localeDescription.translation` between reloads so every reload, every translation is seen as a duplicate.

If only one translation file is permitted during `ng serve` then it should be easy to fix this with simply adding `localeDescription.translation = {};` before reloading. But if translations can cascade across multiple locales (not sure offhand if something like this is supported by Angular) then it is much more complex.

**Comment by hheexx** [comment]
@alan-agius4 we have repo. Update label please.

**Comment by dydek** [comment]
we've got the same issue after updating to 13.1

**Comment by rlejeune** [comment]
Same problem here also, started after upgrading to 13.1

**Comment by msalzig** [comment]
Same issue  after upgrading to 13.1

**Comment by dawda92** [comment]
We've got the same issue within our project.

**Comment by hheexx** [comment]
@alan-agius4 You added freq1: low tag. It's not low. It's bug in production version of Angular that affects everybody who use localization. That's not low number of people.
