### ISSUE TITLE
No compatible version found: angular-cli@webpack

### ISSUE THREAD

**Issue by thebishorup** [angular/angular-cli#2240]
**Windows_NT 10.0.10586**
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli@webpack"
npm ERR! **node v6.3.1**
npm ERR! **npm  v3.10.7**

npm ERR! **No compatible version found: angular-cli@webpack**
npm ERR! Valid install targets:
npm ERR! 1.0.0-beta.2-mobile.4, 1.0.0-beta.2-mobile.3, 1.0.0-beta.2-mobile.2, 1.0.0-beta.2-mobile.1, 1.0.0-beta.2-mobile, 1.0.0-beta.12-1, 1.0.0-beta.11-webpack.9-4, 1.0.0-beta.11-webpack.9-3, 1.0.0-beta.11-webpack.9-2, 1.0.0-beta.11-webpack.9-1, 1.0.0-beta.11-webpack.9, 1.0.0-beta.11-webpack.8, 1.0.0-beta.11-webpack.7, 1.0.0-beta.11-webpack.6, 1.0.0-beta.11-webpack.5, 1.0.0-beta.11-webpack.4, 1.0.0-beta.11-webpack.3, 1.0.0-beta.11-webpack.2, 1.0.0-beta.11-webpack, 1.0.0-beta.15, 1.0.0-beta.14, 1.0.0-beta.12, 1.0.0-beta.10, 1.0.0-beta.9, 1.0.0-beta.8, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.1, 1.0.0-beta.0, 0.1.0, 0.0.39, 0.0.37, 0.0.34, 0.0.33, 0.0.31, 0.0.30, 0.0.29, 0.0.28, 0.0.27, 0.0.26, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1, 0.0.0

**Comment by hansl** [comment]
The webpack tag does not exist anymore. You can replace the webpack tag by latest in your package.json. 

Thank you.

**Comment by thebishorup** [comment]
Perfect. Thanks.
