### ISSUE TITLE
@angular-devkit/build-angular v12+

### ISSUE THREAD

**Issue by yamissa** [angular/angular-cli#22405]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

The latest versions of this package (angular-devkit/build-angular v12+) use eslint-scope@3.7.2 which is reported as insecured : 

https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes

Regards

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by GregoireLgt** [comment]
Hi ! 

I have projects that were running correctly with Angular 12. Now i can't build / npm install because of eslint-scope@3.7.2.
 

Do you have any solution to solve this issue ? 

Thanks

**Comment by alan-agius4** [comment]
Closing as this is not actionable from our end. It appears that it is an upstream issue
