### ISSUE TITLE
Conditional using isDevMode() is not removed in production (v12)

### ISSUE THREAD

**Issue by klemenoslaj** [angular/angular-cli#22404]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, this used to work.

### Description

When using a clear condition with `isDevMode` the code should be properly tree-shaked, like example bellow:

```ts
  ngOnInit() {
    if (isDevMode()) {
      console.log('DEV MODE MESSAGE ONLY!');
    }
  }
```

However, this is not the case. In fact the `isDevMode()` is not resolved to `false`, rather the function is kept in the production build, resulting in production bundle like:

```js
ngOnInit(){El()&&console.log("DEV MODE MESSAGE ONLY!")}}
```

## 🔬 Minimal Reproduction

- Clone: https://github.com/klemenoslaj/angular-devmode-v12-issue
- Execute `ng build --prod`
- Search in dist for `DEV MODE MESSAGE ONLY` which is still in the `main.[hash].js` bundle

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.14
Node: 14.18.2
Package Manager: yarn 1.22.17
OS: darwin x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.14
@angular/cli                    12.2.14
@schematics/angular             12.2.14
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by diicar** [comment]
can you check it with plz : 
```
if (typeof ngDevMode === 'undefined' || ngDevMode) {
}
```

**Comment by klemenoslaj** [comment]
> typeof ngDevMode === 'undefined' || ngDevMode

I'm pretty sure this will work :+1:

It doesn't negate the issue I believe, as `isDevMode` is exposed as public API and is expected to have the same effect.

**Comment by JoostK** [comment]
The `isDevMode()` function from `@angular/core` is not designed as compile-time constant; it is switched at runtime.

You mention that this used to work, do you have an repo of that as well?

> can you check it with plz :
> 
> ```
> if (typeof ngDevMode === 'undefined' || ngDevMode) {
> }
> ```

Using `ngDevMode` is not publicly supported. With the `undefined` check it can be used safely but this pattern may change in the future.

**Comment by klemenoslaj** [comment]
@JoostK Really? I would bet big bucks that used to work 🤔  I will try to make a working reproduction and will come back to you.

**Comment by Totati** [comment]
I've tried to use `ngDevMode` in [my project](https://github.com/Totati/ngx-mat-errors/tree/feature/add-ng-dev-mode), but it won't run or build when it's in a different d.ts file (like in angular/components), I get a TS error:
```
error TS2304: Cannot find name 'ngDevMode'.
if (!this.ngxMatErrorDefFor && (typeof ngDevMode === 'undefined' || ngDevMode)) {
```
If I write the `declare const ngDevMode: object | null;` in the same file it works correctly (like in rx-angular/rx-angular). Any ide how to make it work?
