### ISSUE TITLE
Build fails due to tsparticles with Angular 13 due to @babel/runtime location

### ISSUE THREAD

**Issue by arobinson** [angular/angular-cli#22421]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Yes, working with Angular 11

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

running `ng b` fails, but `ng b -c production` is working for one of our projects

## 🔥 Exception or Error

<pre><code>

./node_modules/tsparticles/Core/Container.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Core'

./node_modules/tsparticles/Core/Loader.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Core'

./node_modules/tsparticles/Interactions/External/Attract/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/External/Attract'

./node_modules/tsparticles/Interactions/External/Bounce/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/External/Bounce'

./node_modules/tsparticles/Interactions/External/Bubble/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/External/Bubble'

m./node_modules/tsparticles/Interactions/External/Connect/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/External/Connect'

./node_modules/tsparticles/Interactions/External/Grab/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/External/Grab'

./node_modules/tsparticles/Interactions/External/Repulse/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/External/Repulse'

./node_modules/tsparticles/Interactions/External/Trail/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/External/Trail'

./node_modules/tsparticles/Interactions/Particles/Attract/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/Particles/Attract'

./node_modules/tsparticles/Interactions/Particles/Collisions/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/Particles/Collisions'

./node_modules/tsparticles/Interactions/Particles/Links/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/Particles/Links'

./node_modules/tsparticles/Interactions/Particles/Links/plugin.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Interactions/Particles/Links'

./node_modules/tsparticles/Plugins/Absorbers/plugin.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Plugins/Absorbers'

./node_modules/tsparticles/Plugins/Emitters/plugin.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Plugins/Emitters'

./node_modules/tsparticles/Plugins/PolygonMask/PolygonMaskInstance.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Plugins/PolygonMask'

./node_modules/tsparticles/Plugins/PolygonMask/plugin.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Plugins/PolygonMask'

./node_modules/tsparticles/Shapes/Circle/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Circle'

./node_modules/tsparticles/Shapes/Image/ImageDrawer.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Image'

./node_modules/tsparticles/Shapes/Image/Utils.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Image'

./node_modules/tsparticles/Shapes/Image/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Image'

./node_modules/tsparticles/Shapes/Line/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Line'

./node_modules/tsparticles/Shapes/Polygon/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Polygon'

./node_modules/tsparticles/Shapes/Square/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Square'

./node_modules/tsparticles/Shapes/Star/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Star'

./node_modules/tsparticles/Shapes/Text/TextDrawer.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Text'

./node_modules/tsparticles/Shapes/Text/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Shapes/Text'

./node_modules/tsparticles/Updaters/Angle/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Angle'

./node_modules/tsparticles/Updaters/Color/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Color'

./node_modules/tsparticles/Updaters/Life/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Life'

./node_modules/tsparticles/Updaters/Opacity/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Opacity'

./node_modules/tsparticles/Updaters/OutModes/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/OutModes'

./node_modules/tsparticles/Updaters/Roll/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Roll'

./node_modules/tsparticles/Updaters/Size/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Size'

./node_modules/tsparticles/Updaters/StrokeColor/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/StrokeColor'

./node_modules/tsparticles/Updaters/Tilt/index.jsm:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Tilt'

./node_modules/tsparticles/Updaters/Wobble/index.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Updaters/Wobble'

./node_modules/tsparticles/Utils/Utils.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles/Utils'

./node_modules/tsparticles/full.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles'

./node_modules/tsparticles/main.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles'

./node_modules/tsparticles/slim.js:3:24-181 - Error: Module not found: Error: Can't resolve '/Users/andrew/development/work/nw-login/node_modules/@angular-devkit/build-angular/node_modules/@babel/runtime/helpers/asyncToGenerator.js' in '/Users/andrew/development/work/nw-login/node_modules/tsparticles'
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.1.2
Node: 14.17.1
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
</code></pre>

**Anything else relevant?**

Happening after upgrading from Angular 11 to 13. It seems like this may potentially be a regression caused by https://github.com/angular/angular-cli/issues/20800

`@babel/runtime` is hoisted as multiple packages are using it in our project:
```
├─┬ @angular-devkit/build-angular@13.1.2
│ ├─┬ @babel/preset-env@7.16.4
│ │ └─┬ @babel/plugin-transform-regenerator@7.16.5
│ │   └─┬ regenerator-transform@0.14.5
│ │     └── @babel/runtime@7.16.3  deduped
│ └── @babel/runtime@7.16.3
├─┬ @angular-eslint/eslint-plugin-template@13.0.1
│ └─┬ aria-query@4.2.2
│   └── @babel/runtime@7.16.3  deduped
└─┬ broadcast-channel@4.8.0
  ├── @babel/runtime@7.16.3  deduped
  └─┬ unload@2.3.1
    └── @babel/runtime@7.16.3  deduped
```

It seems some code is assuming incorrectly that the @babel folder would not be hoisted and is assuming that it should be under `node_modules/@angular-devkit/build-angular/node_modules`

This is all that is under that folder:
```
ll node_modules/@angular-devkit/build-angular/node_modules
total 0
drwxr-xr-x  16 andrew  staff   512B Dec 22 14:25 core-js
drwxr-xr-x   7 andrew  staff   224B Dec 22 14:25 esbuild
drwxr-xr-x  75 andrew  staff   2.3K Dec 22 14:25 rxjs
```

**Comment by arobinson** [comment]
After deleting my working copy and re-cloning it from the server, it seems to be working. Even deleting the `node_modules` did not help. Not sure what happened. I did try using node 16 for a bit before going back to node 14, so perhaps it changed something in my working copy. 

Closing

**Comment by collindutter** [comment]
@arobinson It seems related to the new Angular 13 build caching. 

`rm package-lock.json && rm -rf node_modules/ && rm -rf .angular/cache/ && npm i` 

fixed it for me.
