### ISSUE TITLE
webpack-dev-server hot-reload issue after upgrade from 12.1.14 to 13.1.1

### ISSUE THREAD

**Issue by mbx2015** [angular/angular-cli#22426]
Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

_Originally posted by @alan-agius4 in https://github.com/angular/angular-cli/issues/22194#issuecomment-973189116_

Regarding this issue, I found that in dev mode I can't work with websocket when the backend listen to `/ws` but when I change the path to something else (e.a: /websocket) it works.

the problem is in the dev-server.

**Comment by alan-agius4** [comment]
Closing as the issue template has been deleted.
