### ISSUE TITLE
Angular cli error when install npm packagees

### ISSUE THREAD

**Issue by AnasSharif** [angular/angular-cli#2242]
![captures](https://cloud.githubusercontent.com/assets/20491569/18660728/fcf2f51a-7ec6-11e6-91ba-9358515cbeb3.PNG)
please tell me the solution of the above error

**Comment by ruffiem** [comment]
Try adding Python to the path ?

http://superuser.com/questions/143119/how-to-add-python-to-the-windows-path

**Comment by sajithaPriyankara** [comment]
Please follow this thread
https://github.com/angular/angular-cli/issues/1560#issuecomment-238349893

**Comment by elekzalan** [comment]
Yes, if you install [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) by running `npm install --global --production windows-build-tools` the python error disappears. 

Nevertheless, I'm still getting the `node-pre-gyp` errors saying that `node-zopfli` cannot be found.
![untitled](https://cloud.githubusercontent.com/assets/17826369/18663429/23f58258-7f27-11e6-8c55-e686c6c40225.png)

 @sajithaPriyankara : Yes I tried that thread/solution too. It keeps saying that `Failed to locate: "CL.exe".`

**Comment by sajithaPriyankara** [comment]
@elekzalan ,, Yes,, you are correct since most of the time node-gyp is being used as optional dependencies and --no-optional may solve it. 
But the thread I suggested fixed the very same issue  without any trouble..

**Comment by w0bbes** [comment]
ARe you running it as administrator?

**Comment by bonnici** [comment]
node-gyp installation has some fairly complicated requirements, check [their installation guide](https://github.com/nodejs/node-gyp#installation).

**Comment by filipesilva** [comment]
Dupe, see https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794 for clarification. You do not need `node-gyp` or anything else.
