### ISSUE TITLE
Optional chaining removed on some objects when target: es2020

### ISSUE THREAD

**Issue by johncrim** [angular/angular-cli#22431]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't know - I wasn't able to target es2020 before due to the zone.js issue. Per #18204 this should
have been fixed with webpack 5 support #17555, but it doesn't work.

Given this example:
```ts
export class AppComponent implements OnInit {
  b = 'uninitialized';
  environmentFoo?: string;

  ngOnInit() {
    const a: any = undefined;
    this.b = a?.foo ?? 'default value';
    this.environmentFoo = environment.optionalObject?.foo;
  }
}
```

The es2020 output is:
```js
class AppComponent {
    constructor() {
        this.b = 'uninitialized';
    }
    ngOnInit() {
        const a = undefined;
        this.b = a?.foo ?? 'default value';
        this.environmentFoo = _environments_environment__WEBPACK_IMPORTED_MODULE_0__.environment.optionalObject.foo;
    }
}
```

You can see that the `?.` is removed from `environment.optionalObject?.foo`. But the optional chaining on `a` is preserved.

### Description

When the tsconfig target is set to es2020 or later, optional chaining (eg `object?.property`) on some objects is removed in the build output, resulting in js output like `object.property`, causing a runtime error when object is undefined.

Initially I thought this was roughly the same bug as #18204, but it's not:
* It's a runtime error, not a compile error
* Most normal optional chaining works (the `?.` text is in the output)
* Some optional chaining, like on the `environment` object, is removed in the build output.

## 🔬 Minimal Reproduction

```
git clone git@github.com:johncrim/repro-ng13.git
yarn
yarn start
```

View in browser http://localhost:4200/

Or debug in VS Code.

## 🔥 Exception or Error

Running the repro results in an error:

<pre><code>
```
core.mjs:6484 ERROR TypeError: Cannot read properties of undefined (reading 'foo')
    at AppComponent.ngOnInit (app.component.ts:39)
    at callHook (core.mjs:2533)
    at callHooks (core.mjs:2502)
    at executeInitAndCheckHooks (core.mjs:2453)
    at refreshView (core.mjs:9499)
    at renderComponentOrTemplate (core.mjs:9598)
    at tickRootContext (core.mjs:10829)
    at detectChangesInRootView (core.mjs:10854)
    at RootViewRef.detectChanges (core.mjs:21425)
    at ApplicationRef.tick (core.mjs:26431)
```
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.2
Node: 16.12.0
Package Manager: yarn 1.22.15
OS: win32 x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
</code></pre>

## Workarounds

1. Set tsconfig target to `es2019`

Results in transpiling optional chaining:

```js
class AppComponent {
    constructor() {
        this.b = 'uninitialized';
    }
    ngOnInit() {
        var _a, _b;
        const a = undefined;
        this.b = (_a = a === null || a === void 0 ? void 0 : a.foo) !== null && _a !== void 0 ? _a : 'default value';
        this.environmentFoo = (_b = _environments_environment__WEBPACK_IMPORTED_MODULE_0__.environment.optionalObject) === null || _b === void 0 ? void 0 : _b.foo;
    }
}
```

2. Or: Store the environment object in a new variable. 
 
Given this example:
```ts
export class AppComponent implements OnInit {
  b = 'uninitialized';
  environmentFoo?: string;

  ngOnInit() {
    const a: any = undefined;
    this.b = a?.foo ?? 'default value';
    const obj = environment.optionalObject;
    this.environmentFoo = obj?.foo;
  }
}
```

The es2020 output is:
```js
class AppComponent {
    constructor() {
        this.b = 'uninitialized';
    }
    ngOnInit() {
        const a = undefined;
        this.b = a?.foo ?? 'default value';
        const obj = _environments_environment__WEBPACK_IMPORTED_MODULE_0__.environment.optionalObject;
        this.environmentFoo = obj?.foo;
    }
}
```

**Comment by alan-agius4** [comment]
Hi @johncrim, 

This appears to be an issue with Webpack, please see https://github.com/webpack/webpack/issues/15134

**Comment by johncrim** [comment]
Thanks @alan-agius4  - apologies for not finding that (but hopefully other devs won't report it due to this issue).

Here's another webpack issue, looks like it's been around for quite some time.
https://github.com/webpack/webpack/issues/12960
