### ISSUE TITLE
Make build optimizer work for all packages

### ISSUE THREAD

**Issue by pauldraper** [angular/angular-cli#22436]
It seems that build optimizer is stingy, and only applies to certain packages: https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts#L22

There are multiple issues here:

(1) node_modules/@angular/core etc might not be the fully resolved name of the package. For example, a user make symlink node_modules/@angular/core to angular-core-13.1.1. Actually, the Node.js docs on package managers suggests this sort of approach.

(2) This only works for @angular packages. Other packages matter too!

Perhaps there is a config option that would allow it?

**Comment by pauldraper** [comment]
Actually, given that webpack loaders already have mechanism for users to control which files they are applied to.....this all seems pretty silly for the Angular webpack loader to replicate that.

**Comment by alan-agius4** [comment]
The [@angular-devkit/build-optimizer](https://www.npmjs.com/package/@angular-devkit/build-optimizer) package is deprecated.

See: https://github.com/angular/angular-cli/issues/22401
