### ISSUE TITLE
Issue with using SCSS files

### ISSUE THREAD

**Issue by adaneam** [angular/angular-cli#2243]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 8

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.3.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new style-test --style=scss
add a scss file which imports another partial scss

4. The log given by the failure. Normally this include a stack trace and some
   more information.

ERROR in ./~/css-loader!./src/stylesheets/lc-extras.scss
Module build failed: CssSyntaxError: C:\css-loader!C:\Study\dump\style-test\src\stylesheets\lc-extras.scss:1:1: Unknown word
**You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser**
1 | // Core variables and mixins
| ^
2 | @import "bootstrap/variables";
3 | @import "bootstrap/mixins";

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Why do I get **You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser**?

**Comment by jdpipkin** [comment]
Try making the drive letter in your cmd line is the same capitalization as your computer.
For instance if your cmd line is out putting c:\ but your drive is actually C:\ you're going to have problems.

I ran into something very similar to this with webpack a while back. Took me ages to figure it out.

**Comment by adaneam** [comment]
Ok found the problem. This happens if you import .scss files in normal .css files. Renaming .css to .scss fixed it.
