### ISSUE TITLE
Make the generation of module and component optional

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#22449]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

When generating a lib using the angular cli it also creates a module.ts, why is that? what is it used for?
If this is a lib that only contains a service then I have no need for the module.. right?

We use mono-repos (using nx) and one of the concepts are data-access libraries that only contains services (more or less). So we need to constantly remove generated things for new libs :)

### Describe the solution you'd like
When using `ng generate library myLib` it should require flags for the creation of module/component..
The generation of module and component should be opt-in

**Comment by alan-agius4** [comment]
> When generating a lib using the angular cli it also creates a module.ts, why is that? what is it used for?

This is needed to register components, directives, pipes and dependent modules for the particular module.

> If this is a lib that only contains a service then I have no need for the module.. right?

It is very unlikely that you don't need a modules if you are developing a library. Modules are also needed to register DI dependencies.

If your data service depends on the HTTP client or a state management service from an external library, you need to register these as dependencies in the libraries's module.

```ts
@NgModule({
  imports: [
    HttpClientModule,
    ...,
  ],
})
export class MyLibModule {}
```

Overall, removing the component/module is trivial enough that this can be done manually without the need to extend the API. 

You can read more about modules here: https://angular.io/guide/ngmodules

**Comment by mackelito** [comment]
@alan-agius4 sure I see your point.. but is that not only true for buildable libs?

**Comment by alan-agius4** [comment]
@mackelito, libraries are always buildable in the Angular CLI.

**Comment by mackelito** [comment]
@alan-agius4 thx.. we use nx so the lines are kind of blurry some times :)
