### ISSUE TITLE
Angular build fails at 92% chunck asset optimization and dist folder is not getting created

### ISSUE THREAD

**Issue by sherinebeulah** [angular/angular-cli#22448]
@angular/cli : 1.3.1
node 12.18.0

getting error on angular build shows 92% chunk asset optimization and dist failed
showing additional errors like
/src/app/components/helpdesk/queue/queue.component.ts expected 3-8 arguments but got 10

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

@angular/cli 1.3.1 is very old, consider updating to a supported version.
