### ISSUE TITLE
Ng serve results in webpack dev server failure in Angular 13

### ISSUE THREAD

**Issue by caledbenne** [angular/angular-cli#22464]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 12

### Description

 After upgrading from version 9 to version 13, webpack appears to fail to start when running ng serve.

## 🔬 Minimal Reproduction

Minimal repro here: [https://github.com/caledbenne/angular-webpack-minimal-repro](https://github.com/caledbenne/angular-webpack-minimal-repro)

## 🔥 Exception or Error

<pre><code>

- Generating browser application bundles (phase: setup)...(node:2028) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'address' of undefined
    at <userfolder>\angular-webpack-minimal-repro\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:79:46
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2028) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

</code></pre>

<pre><code>

Angular CLI: 13.1.2
Node: 14.15.4
Package Manager: yarn 1.22.17
OS: win32 x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            6.5.5
typescript                      4.5.4

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
It appears that the issue is that both the SSL key and certificate are not present on disk and webpack-dev-server is not thowing a meaningful error.

**Comment by caledbenne** [comment]
Ah - so it is. Previously I had been using empty files without issue (just clicking past the error in chrome), I guess it requires a proper key and cert with v13. Generating one resolves the issue!
