### ISSUE TITLE
Visual Studio Unknown Compiler Option 'typeRoots'.

### ISSUE THREAD

**Issue by timojokinen** [angular/angular-cli#2246]
angular-cli: 1.0.0-beta.15
node: 4.5.0
os: win32 x64

I've created a angular-cli project in an existing .NET Project. I have TypeScript Version 2.0.2 globally installed as well as Visual Studio Extension TypeScript 2.0.2 Beta.

I can't build the project (only in Visual Studio. Build via cli works perfectly) because of a debug error "Build:Unknown compiler option 'typeRoots'."

I googled so much but I could not really find anything relative.

**Comment by Meligy** [comment]
This is not a CLI issue.

Check the .csproj file in a text editor. Look for the word typescript and see the typescript version stored in that.

Also, in VS `Tools` -> `Options`, go to `Projects and Solutions` -> `External Web Tools`. and uncheck anything that starts with `$(VSINSTALLDIR)`.

**Comment by SekThang** [comment]
its not working for me.. My project is Asp.net core web application (.NET Framework) --> Empty

tsconfig file is 
{
  "compilerOptions": {
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ],
    "types": [
      "jasmine"
    ]
  }
}
and Typescript version is 2.1.0
Node version is 7.0.0

**Comment by adrian-moisa** [comment]
@Meligy Thanks for solution, it worked!
