### ISSUE TITLE
Angular 12 - ng test fails on a newly created app - garbled text

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#22462]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

### Description
Running `ng test` on a new angular 12 throws garbled text

## 🔬 Minimal Reproduction

- `npx @angular/cli@12 new admin-console --style css --routing`
- `cd admin-console`
- `npm run test`

## 🔥 Exception or Error

<pre><code>
> admin-console@0.0.0 test
> ng test

undefined
undefined
undefined
                                   !             H|H|H|H|H           H__________________________________             H|┬º|┬º|┬º|H           H|* * * * * *|---------------------|             H|┬º|Γê₧|┬º|H           H| * * * * * |---------------------|             H|┬º|┬º|┬º|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher  
t═æ╠å═»═¿╠ô╠ó╠¿╠╡═ÿ═í═ç╠▓╠¬╠ƒ╠⌐e═ñ═«╠Å═å═ù═æ╠Ç═¿╠é═»╠í═¥╠º═¥╠¡╠│╠½╠⌐═Ö╠¥═ì╠½═ç╠Ñ╠Ñ╠Ñ╠ñ═Ä═ç╠¡═û═à╠á╠¼╠╝╠│═ö╠¬╠¼╠₧╠╗╠Ñ═ê╠▒╠│╠£═ê╠₧╠«╠⌐═ç╠¬╠Ö═ë╠¼╠ù╠▓═ô═ç═ö═ö═ò═Ö╠ƒ╠₧╠░╠ª╠▓╠▓╠⌐═û╠á╠¼═û═Ä╠╝╠û╠ƒ╠£═û╠▓s╠┐╠┐═é═¢═«╠â═¿═«═É╠Æ═é═ù═¡═ª╠å═¡╠É═é╠ô╠ó╠╢╠╕╠┤╠¢╠╝╠│═ò═ê╠Ö═ô╠½╠⌐═ê╠╣╠▓═ë╠│╠╣t═å╠Ç═ñ═¼═¬═Æ╠┐╠ç═¥═¥╠╡═ì╠¥═ô╠£╠╣╠╣╠Ö═ô╠▓╠ù═ê═ç╠╝╠ñ╠¥═ë╠á═Ä═Ä╠ª╠║╠▒╠▒╠▒═ò═ö╠╣═ç╠▓═ç╠ª╠ù═ë╠╗╠▒╠»═à╠úi═¢═î═½╠è╠à╠ü═ª═¡╠Æ╠ê╠í═ó╠¿ ╥ë╠╖═ë╠ñ╠«═ç═ê╠ª╠«═ì╠»═Ö╠½═ô╠½╠║═ò╠Ö╠⌐═ë═ô═à═à╠║╠½═Ö═ê╠ù═ò═ë╠▒═ç╠╝╠ÿ╠Ö╠¥n╠ë═¡═è╠à╠å═Ñ═æ╠ü═
</code></pre>
<img width="551" alt="ng_test_ng_12" src="https://user-images.githubusercontent.com/13006107/148783783-1f7a0d39-519e-42e2-8261-a16e5c93a9d8.png">

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.14
Node: 16.13.1
Package Manager: npm 7.20.1
OS: win32 x64

Angular: 12.2.15
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.14
@angular-devkit/build-angular   12.2.14
@angular-devkit/core            12.2.14
@angular-devkit/schematics      12.2.14
@angular/cli                    12.2.14
@schematics/angular             12.2.14
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
The is an interesting one, likely some transitive dependency is causing an issue.

**Comment by alan-agius4** [comment]
@pkozlowski-opensource, pointed out that likely this is an issue with [colors.js](https://github.com/Marak/colors.js/issues/285).

**Comment by jan-molak** [comment]
Try running `npm ls colors` to see what's pulling in this dependency

**Comment by baron1405** [comment]
This was caused by a [malicious change](https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6) in the [colors ](https://github.com/Marak/colors.js) package. The offending package versions have been removed from npm so things should start returning to normal. See [this issue](https://github.com/Marak/colors.js/issues/317) for the current status.
