### ISSUE TITLE
ng --version and ng new are not working on upgrade to beta.14 and beta.25

### ISSUE THREAD

**Issue by sudhashri** [angular/angular-cli#2247]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
>Windows 8

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
>`ng --version`
 It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.
To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12
`node --version`
> v4.5.0
`npm -v`
>3.10.6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
>Followed steps mention in [Upgrading from beta-10 to beta-14](https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14). 
>Step 1: Uninstalled and re-installed angular-cli
>`npm uninstall -g angular-cli`
>`npm cache clean`
>`npm install -g angular-cli@latest`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
>It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.
>To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by loiane** [comment]
Same as of #2144

**Comment by loiane** [comment]
Fixed on beta 15.

**Comment by sudhashri** [comment]
Thank you.
