### ISSUE TITLE
Build performance decreased from v12.2.x to v13.1.1 (process assets / seal compilation) if Bootstrap is imported in styles.scss

### ISSUE THREAD

**Issue by DavideViolante** [angular/angular-cli#22472]
### Which @angular/* package(s) are the source of the bug?

angular_devkit/build_angular

### Is this a regression?

Yes

### Description

I just upgraded a pretty big private project from v12 to v13 and the build time increased x10, can't really find why.
Just to be sure that it was Angular upgrade I tried to downgrade again and the performance restored as expected.
I post here a part of the verbose log of the build, **in particular note the extreme difference between v12 and v13 in assets time / seal compilation**:

## v12 (edit)
```
...
<t> record hash: 0.12885 ms
<t> module assets: 0.478536 ms
<t> create chunk assets: 6.774782 ms
<t> process assets: 30310.76689 ms <--------

LOG from webpack.Compiler
<t> make hook: 18985.143228 ms
<t> finish make hook: 0.206746 ms
<t> finish compilation: 72.86418 ms
<t> seal compilation: 32318.405325 ms <----------
<t> afterCompile hook: 0.280398 ms
...
```

## v13
```
...
<t> record hash: 0.130436 ms
<t> module assets: 0.797611 ms
<t> create chunk assets: 6.450294 ms
<t> process assets: 302297.57658 ms <-----------

LOG from webpack.Compiler
<t> make hook: 21553.025473 ms
<t> finish make hook: 0.179688 ms
<t> finish compilation: 86.421 ms
<t> seal compilation: 304301.925952 ms <-----------
<t> afterCompile hook: 0.207707 ms
...
```

tsconfig.json:
```js
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    //"strict": true,
    "noImplicitOverride": true,
    //"noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "lib": [
      "es2020",
      "dom"
    ]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

```

Any help to debug this issue deeply? What other tests could I do to find out more?

Thanks

### Please provide a link to a minimal reproduction of the bug

https://github.com/angular/angular/issues/44555#issuecomment-1005045938

### Please provide the exception or error you saw

Performance issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.3.0
OS: linux x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
```

### Anything else?

The issue is not present on development build (`-c development`)
The issue is present in v13.0.0 too

**Comment by JoostK** [comment]
Moving to the CLI repo as this seems to be about CSS processing/optimization performance.

**Comment by SebastianStehle** [comment]
In general: have you considered fast-scss-loader in the angular team?

**Comment by alan-agius4** [comment]
> In general: have you considered fast-scss-loader in the angular team?

One of the reasons why this is faster, is because this loader doesn't generate sourcemaps which makes this not a viable alternative in our case. In addition to that we try to stick with official plugins whenever possible.

**Comment by DavideViolante** [comment]
@alan-agius4 I just saw your PR (thanks), in which version of esbuild it was fixed? Can't figure it out from [their changelog](https://github.com/evanw/esbuild/releases).

**Comment by alan-agius4** [comment]
@DavideViolante, it appears that it has been addressed in `0.14.6`.

**Comment by DavideViolante** [comment]
I changed the version in my package-lock and the fix works. :+1: 
Compilation time on Github Action machine (not comparable with my machine) is just ~1min now.
```
Initial Chunk Files               | Names         |      Size
main.d84dddb592b6b05c9ce2.js      | main          | 854.30 kB
scripts.9e8c3619fe40c53a332e.js   | scripts       | 357.44 kB
styles.bf25deb546abd03ffa54.css   | styles        | 222.86 kB
polyfills.d22542734ce5b165217d.js | polyfills     |  36.19 kB
runtime.d4391d1428616e31d353.js   | runtime       |   1.02 kB

| Initial Total |   1.44 MB

Build at: 2022-01-11T16:40:38.854Z - Hash: 0e7843340e376ad4a4aa - Time: 55758ms
```
On my previous builds on Github Actions without the fix it was around 322943ms.

Thanks.

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/22477

**Comment by alexandis** [comment]
I am getting annoying messages after upgrading from v11 to v13 like this (several projects cause this kind of errors after just opening the folder, no build, no serve). Any ideas - where do I need to dig?

> [Info  - 02:44:41] Enabling Ivy language service for c:/CT/AbxEps.AbpModules/angular-modules/projects/abxeps/abxeps-modal-window-router-bootstrap/tsconfig.lib.json.
> [Error - 02:44:41] Failed to run ngcc for c:/CT/AbxEps.AbpModules/angular-modules/projects/abxeps/abxeps-modal-window-router-abstractions/tsconfig.lib.json, language service may not operate correctly:
>     ngcc for c:/CT/AbxEps.AbpModules/angular-modules/projects/abxeps/abxeps-modal-window-router-abstractions/tsconfig.lib.json returned exit code 177, stderr: Error: Timed out waiting 250s for another ngcc process, with id 62720, to complete.
> (If you are sure no ngcc process is running then you should delete the lock-file at c:/CT/AbxEps.AbpModules/angular-modules/node_modules/.ngcc_lock_file.)
>     at AsyncLocker.create (file:///c:/CT/AbxEps.AbpModules/angular-modules/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1691:11)
>     at async AsyncLocker.lock (file:///c:/CT/AbxEps.AbpModules/angular-modules/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1662:5)
>     at async file:///c:/CT/AbxEps.AbpModules/angular-modules/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:31:5
> [Info  - 02:44:41] Enabling Ivy language service for c:/CT/AbxEps.AbpModules/angular-modules/projects/abxeps/abxeps-modal-window-router-abstractions/tsconfig.lib.json.
> [Error - 02:44:41] Failed to run ngcc for c:/CT/AbxEps.AbpModules/angular-modules/projects/abxeps/abxeps-report-builder/tsconfig.lib.json, language service may not operate correctly:
>     ngcc for c:/CT/AbxEps.AbpModules/angular-modules/projects/abxeps/abxeps-report-builder/tsconfig.lib.json returned exit code 177, stderr: Error: Timed out waiting 250s for another ngcc process, with id 62720, to complete.
> (If you are sure no ngcc process is running then you should delete the lock-file at c:/CT/AbxEps.AbpModules/angular-modules/node_modules/.ngcc_lock_file.)
>     at AsyncLocker.create (file:///c:/CT/AbxEps.AbpModules/angular-modules/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1691:11)
>     at async AsyncLocker.lock (file:///c:/CT/AbxEps.AbpModules/angular-modules/node_modules/@angular/compiler-cli/bundles/chunk-K5FPDA5B.js:1662:5)
>     at async file:///c:/CT/AbxEps.AbpModules/angular-modules/node_modules/@angular/compiler-cli/bundles/ngcc/main-ngcc.js:31:5
> [Info  - 02:44:41] Enabling Ivy language service for c:/CT/AbxEps.AbpModules/angular-modules/projects/abxeps/abxeps-report-builder/tsconfig.lib.json.
