### ISSUE TITLE
Installtion of Node 10.18.0 binary file

### ISSUE THREAD

**Issue by sherinebeulah** [angular/angular-cli#22481]
Team,

For one of our existing project we have to use below versions of node and angular CLI
**@angular/cli: 1.3.1
node: 10.18.0**
os: win32 * 64
@angular/animations: 4.3.1
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.3.1
@angular/complier: 4.3.1
@angular/core: 4.3.1
@angular/forms: 4.3.1
@angular/http: 4.3.1
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.3.1
@angular/router: 4.3.1
@angular/cli: 1.3.1
@angular/complier-cli: 4.3.1

I have installed node 10.18.0 and Angular CLI 1.3.1 but whenever I try ng -version command it shows angular cli expects minimum node version 12.18.0. But with 10.18.0 and 1.3.1 only we can able to generate build dist folder.

So, one of my teammate suggested me to copy and paste the node 10.18.0 binary file. Team, could you please suggest how to get this file

**Comment by alan-agius4** [comment]
Angular CLI version 1 is no longer supported. Please update to a more recent version of Angular.

Please see for our support policy https://angular.io/guide/releases#support-policy-and-schedule

**Comment by sherinebeulah** [comment]
> Angular CLI version 1 is no longer supported. Please update to a more recent version of Angular.
> 
> Please see for our support policy https://angular.io/guide/releases#support-policy-and-schedule

Hi Alan,

Our project runs with this version only. Could you pl guide to install node 10.18.0 binary file

**Comment by sherinebeulah** [comment]
Hi Alan,

Our project runs with this version only. Could you pl guide to install node 10.18.0 binary file
