### ISSUE TITLE
ng build with --base-href cannot replace all urls

### ISSUE THREAD

**Issue by calidion** [angular/angular-cli#22485]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

use the following command:
```
ng build --prod --base-href=xxx.com
grep runtime -Rn dist/
```

you will find:
```
dist/index.html:16:<script src="runtime.3ff173917fb247e9.js" type="module"></script><script src="polyfills.914165029d2f89e7.js" type="module"></script><script src="main.4c5dae8ee353808e.js" type="module"></script>
```
this line is not replaced with base href, with makes the whole html output invalid.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.4
Node: 14.18.1
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.4
@angular-devkit/build-angular   13.0.4
@angular-devkit/core            13.0.4
@angular-devkit/schematics      13.0.4
@angular/cdk                    13.1.1
@angular/cli                    13.0.4
@angular/material               13.1.1
@schematics/angular             13.0.4
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

**Comment by calidion** [comment]
runtime.3ff173917fb247e9.js 
polyfills.914165029d2f89e7.js 
main.4c5dae8ee353808e.js
styles.c68f72f4e289a805.css
favicon.ico 
manifest.webmanifest

all these src or href should use absolute urls.

**Comment by alan-agius4** [comment]
This is working as expected.

The base-href value is set in base HTML element. The base HTML element specifies the base URL to use for all relative URLs in a document.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base for more information about base href.

**Comment by greenpau** [comment]
> The base-href value is set in base HTML element. The base HTML element specifies the base URL to use for all relative URLs in a document.

@alan-agius4 , that's not exactly what happens here ... 😞 

At least with Chrome, the browser tries fetching `/runtime.ab323423e04fe794.js`, not `/myapp/runtime.ab323423e04fe794.js`.

```
    <base href="/myapp/">
  <script src="runtime.ab323423e04fe794.js" type="module"></script><script src="polyfills.a524899eb97f2a08.js" type="module"></script><script src="main.b35f5251d84666fb.js"               type="module"></script>
```

**Comment by alan-agius4** [comment]
@greenpau, I am unable to replicate. Please file a new issue with a minimal reproduction.

**Comment by calidion** [comment]
When built for deployment, it is quite reasonable to remove the old base and absolutize all relative urls when a new base is provided.

**Comment by alan-agius4** [comment]
> When built for deployment, it is quite reasonable to remove the old base and absolutize all relative urls when a new base is provided.

That is not how base href HTML element work. For base href to have an effect, resources need to use **relative** urls.

You can learn more about the base href https://www.w3schools.com/tags/tag_base.asp and  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

**Comment by calidion** [comment]
As @greenpau  has explained, you may notify chrome team to learn how base should work.

The reason we want to build bundles is not to obey rules, but to keep projects non breaking.

Or maybe add an new instruction --absolutize to full absolutize urls to avoid deployment failures.

**Comment by calidion** [comment]
Mixing relative and absolute path with base generates a bundle of useless shit.

This is another shit generated by angular cli which is none usable when it is placed at a subdir.

https://node-aoa.github.io/tools/

**Comment by calidion** [comment]
it generates shit bundles even when the base tag is removed!

**Comment by calidion** [comment]
Finally solved!
1. remove `base` tag
2. ng build --base-href=https://node-aoa.github.io/tools/
