### ISSUE TITLE
Expected 3-8 arguments, but got 10.

### ISSUE THREAD

**Issue by sherinebeulah** [angular/angular-cli#22482]
Team I got below error for npm run build-qa

ERROR in ../src/app/containers/integration/logs/integration-log-list.component.ts (32,23): Expected 3-8 arguments, but got 10.
ERROR in ../src/app/containers/integration/logs/integration-log-list.component.ts (33,23): Expected 3-8 arguments, but got 10.
ERROR in ../src/app/containers/integration/mapping/mapping-list.component.ts (19,23): Expected 3-8 arguments, but got 10.
ERROR in ../src/app/containers/integration/mapping/mapping-rule-list.component.ts (47,23): Expected 3-8 arguments, but got 10.
ERROR in ../src/app/containers/integration/mapping/mapping-rule-list.component.ts (48,23): Expected 3-8 arguments, but got 10.
ERROR in D:/Sivalakshmi/ilex/help-desk/src/app/components/helpdesk/queue/queue.component.ts (451,24): Expected 3-8 arguments, but got 10.
ERROR in ../src/app/components/helpdesk/queue/queue.component.ts (510,31): Property 'filterValue' does not exist on type 'Column'.
ERROR in ../src/app/components/helpdesk/queue/queue.component.ts (512,75): Property 'filterValue' does not exist on type 'Column'.
ERROR in ../src/app/components/helpdesk/queue/queue.component.ts (517,34): Property 'filterValue' does not exist on type 'Column'.
ERROR in ../src/app/components/helpdesk/queue/queue.component.ts (6,43): Module '"./node_modules/comcast-ui/in
dex"' has no exported member 'filterValue'.

I'm using node 12.18.0, npm 6.14.4 and angular CLI 1.3.1

Anyone pl help on this issue

**Comment by alan-agius4** [comment]
Kindly fill the issue template together with a minimal reproduction.
