### ISSUE TITLE
'function insertImport' in node_modules/@angular-cli/asp-tools/src/route-utils.js  is different from 1.0.0-beta.15's source code

### ISSUE THREAD

**Issue by chgc** [angular/angular-cli#2249]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
cli version: 1.0.0-beta.15
node version : v6.6.0

3. Mention any other details that might be useful.
**function insertImport** in node_modules/@angular-cli/asp-tools/src/route-utils.js  is different from 
1.0.0-beta.15's source code:  packages/ast-tools/src/route-utils.ts. Why is that?

project folder/node_modules/@angular-cli/asp-tools/src/route-utils.js
![image](https://cloud.githubusercontent.com/assets/4550568/18670755/f3c5044e-7f73-11e6-83c4-032644834f4e.png)

1.0.0-beta.15 source code
![image](https://cloud.githubusercontent.com/assets/4550568/18670651/8bc470aa-7f73-11e6-9d8d-6beea0db3e76.png)

When I tried to build beta.15 source code from my local machine. the build output is same as source file. Please check that. Thanks

build from 1.0.0-beta.15 source code 
![image](https://cloud.githubusercontent.com/assets/4550568/18670983/d8a872bc-7f74-11e6-9501-a2ed303407c8.png)
![image](https://cloud.githubusercontent.com/assets/4550568/18671012/f96494d6-7f74-11e6-96fe-6cc5b340abf0.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ValeryVS** [comment]
`@angular-cli/asp-tools` is separate package. Now, it has version 1.0.1, published 7 days ago. Before #1961 
New release of `@angular-cli/asp-tools` will fix this.

**Comment by chgc** [comment]
@ValeryVS Got it. Thanks.
