### ISSUE TITLE
`Expected identifier but found ":"` for host + ng-deep + external styles

### ISSUE THREAD

**Issue by artaommahe** [angular/angular-cli#22506]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 12.2.x

### Description

multiple warnings like this
```
Warning: ▲ [WARNING] Expected identifier but found ":"

    /Users/drow/projects/tests/ng13-expected-identifier/src/app/app.component.scss:5:2:
      5 │   :host ::ng-deep {
        ╵   ^
```

for styles like

```
:host ::ng-deep {
  @import '../../node_modules/katex/dist/katex';
}
```

`katex.css` contains `@font-face` declarations and regular styles

## 🔬 Minimal Reproduction

- `git clone https://github.com/artaommahe/ng13-expected-identifier`
- `yarn install`
- `yarn build`
- see warnings

## 🔥 Exception or Error

```
Warning: ▲ [WARNING] Expected identifier but found ":"

    /Users/drow/projects/skyeng/skyeng-frontend/libs/shared/katex/src/component/katex/katex.scss:149:2:
      149 │   :host ::ng-deep {
          ╵   ^
```

## 🌍 Your Environment

<pre><code>
yarn run v1.22.17
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.3
Node: 16.13.0
Package Manager: yarn 1.22.17
OS: darwin arm64

Angular: 13.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@schematics/angular             13.1.3
rxjs                            7.4.0
typescript                      4.5.4
    
✨  Done in 1.20s.
</code></pre>

**Anything else relevant?**

We use such imports to scope global styles from external lib to current component.

**Comment by alan-agius4** [comment]
This seems to be an issue with [esbuild](https://github.com/evanw/esbuild). 

**Error**
```css
:host ::ng-deep {
  @font-face {
    font-family: "KaTeX_AMS";
    font-weight: normal;
    font-style: normal;
  }
}
```

**Works**
```css
:host ::ng-deep {
  div {
    color: red;
  }
}
```

**Comment by alan-agius4** [comment]
I looked into this a bit more and from my understanding the failure here is correct. 

 `@font-face` rules need to be defined either top-level or in [conditional group rules](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule#conditional_group_rules) to be valid.  So in your example, by nesting `@font-face` in the `:host` selector you are creating CSS which is not valid by standards therefore EsBuild is correctly issuing a warning about this. 

See https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face#description for more information.

**Comment by alan-agius4** [comment]
Closing since nesting `@font-face` is considered as non-valid CSS which from my understanding browsers don't support. Therefore, a warning in this case is the correct behaviour.
