### ISSUE TITLE
Installation of Tag v11-lts is broken due to removal of @angular-devkit/build-optimizer@0.1102.18

### ISSUE THREAD

**Issue by helmchen** [angular/angular-cli#22504]
# 🐞 Bug report

### Command (mark with an `x`)

npm install -g @angular/cli@v11-lts

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
Installation worked until yesterday.

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

npm install -g @angular/cli@v11-lts

## 🔥 Exception or Error

<pre><code>

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/build-optimizer@0.1102.18
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular-devkit/build-angular'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     c:\npm\cache\_logs\2022-01-13T13_14_16_418Z-debug.log
</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

Problem occurs while building an image with Dockerfile as well as locally on Windows.

**Comment by alan-agius4** [comment]
`@angular-devkit/build-optimizer@0.1102.18` does exist on NPM

https://www.npmjs.com/package/@angular-devkit/build-optimizer

**Comment by alan-agius4** [comment]
Closing as per above comment.
