### ISSUE TITLE
Export module in public api

### ISSUE THREAD

**Issue by gradzio** [angular/angular-cli#22511]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...
when generting module I would like to use a parameter to automatically add this moduel to public api of a project (library), this way I would not have to do it each time

### Describe the solution you'd like
ng g lib .... --addToPublicApi
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
alternatively we could use --skipPublicApic but that could be a killer for not well maintained apps
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
This is very similar to https://github.com/angular/angular-cli/issues/22511. Let's continue tracking this there.

**Comment by alan-agius4** [comment]
Edit: updated link above, as previously I linked the wrong issue.
