### ISSUE TITLE
Version 13: Data path "" must NOT have additional properties(i18nFile)

### ISSUE THREAD

**Issue by stanislavromanov** [angular/angular-cli#22517]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [x] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version we could serve a specific locale. Now we cannot, or the option changed and it is nowhere told how to do so.

### Description

Scenario is very simple. Application has 15+ languages and I need to serve a specific language, in my example: German. I can't anymore because it says that this is not a valid option.

## 🔬 Minimal Reproduction
Create an application with two locales and try to launch the one which is not set as default. It seems it's not possible anymore.

It used to be possible using this command: `ng serve --configuration=de`

```json
"de": {
  "i18nFile": "src/i18n/messages.de.xlf", <-- ERROR since v13
  "i18nFormat": "xlf", <-- ERROR since v13
  "i18nLocale": "de" <-- ERROR since v13
}
...
"de": {
  "browserTarget": "frontend:build:de"
},
```

## 🔥 Exception or Error

<pre>Data path "" must NOT have additional properties(i18nFile)<code>

</code></pre>

Build fails and application is not served. Since I see squiggly lines over all three options it is clear that all of them are not valid anymore.

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.1.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: darwin arm64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.3 (cli-only)
@angular-devkit/core         13.1.3 (cli-only)
@angular-devkit/schematics   13.1.3 (cli-only)
@schematics/angular          13.1.3 (cli-only)
</code></pre>

**Anything else relevant?**

**Comment by rw6bsc** [comment]
Same issue here with Angular v12.2.5. It worked before updating.

Since you closed this issue @stanislavromanov, did you solve it on your end?
If so, could you give me a pointer on how to fix this, please?

**Comment by stanislavromanov** [comment]
@rw6bsc They changed how you define locales. This is the file I used from their official website as a reference. https://stackblitz.com/run?file=angular.json

Now you have to specify an array with one element to launch a specific locale. Makes absolutely no sense, but hey - it's Angular and it seems that sometimes they just change options/configs for the sake of changing it and introducing breaking changes.

**Comment by alan-agius4** [comment]
This options have been removed since version 12. When updating using `ng-update` from v11 to v12 the configuration will be migrated automatically to the new format. That is, if you are using the official builders.

More information about the breaking changes can be found https://github.com/angular/angular-cli/releases/tag/v12.0.0
