### ISSUE TITLE
ng test error with PhantomJS 2.1.1 (Windows 8) ERROR SyntaxError: Use of reserved word 'class' at http://localhost:9876/_karma_webpack_/vendor.js:116:0

### ISSUE THREAD

**Issue by bxdadwhal** [angular/angular-cli#22512]
package.json :-
{
"name": "gd",
"version": "2.0.0",
"engines": {
"node": "6.11.0",
"npm": "3.10.10"
},
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build --prod",
"test": "ng test",
"lint": "ng lint --type-check",
"e2e": "ng e2e",
"serve": "ng serve --proxy-config proxy.conf.json",
"coverage": "ng test --code-coverage --reporters=coverage-istanbul"
},
"private": true,
"dependencies": {
"@angular/animations": "10.2.5",
"@angular/common": "10.2.5",
"@angular/compiler": "10.2.5",
"@angular/core": "10.2.5",
"@angular/forms": "10.2.5",
"@angular/http": "7.2.16",
"@angular/material": "^13.1.2",
"@angular/platform-browser": "10.2.5",
"@angular/platform-browser-dynamic": "10.2.5",
"@angular/router": "10.2.5",
"@babel/compat-data": "^7.8.0",
"@ngrx/store": "^9.2.0",
"core-js": "2.5.1",
"dexie": "2.0.1",
"immutable": "3.8.2",
"lodash": "4.17.4",
"ngx-bootstrap": "^6.2.0",
"pouchdb-browser": "6.3.4",
"rxjs": "6.6.7",
"rxjs-compat": "^6.0.0-rc.0",
"zone.js": "0.10.3"
},
"devDependencies": {
"@angular-devkit/build-angular": "^0.803.24",
"@angular/cli": "10.2.4",
"@angular/compiler-cli": "10.2.5",
"@types/jasmine": "2.6.0",
"@types/node": "^8.10.52",
"angular": "1.6.6",
"angular-in-memory-web-api": "0.4.6",
"angular-mocks": "1.6.6",
"angular-route": "1.6.6",
"angular-sanitize": "1.6.6",
"bootstrap": "3.3.7",
"codelyzer": "3.2.2",
"concurrently": "3.5.0",
"font-awesome": "4.7.0",
"grunt": "1.0.1",
"grunt-bower-task": "0.5.0",
"grunt-cli": "1.2.0",
"grunt-concurrent": "2.3.1",
"grunt-contrib-clean": "1.1.0",
"grunt-contrib-concat": "1.0.1",
"grunt-contrib-copy": "1.0.0",
"grunt-contrib-jshint": "1.1.0",
"grunt-contrib-less": "1.4.1",
"grunt-contrib-uglify": "3.1.0",
"grunt-contrib-watch": "1.0.0",
"grunt-exec": "3.0.0",
"grunt-open": "0.2.3",
"grunt-text-replace": "0.4.0",
"istanbul": "0.4.5",
"jasmine-core": "2.8.0",
"jasmine-spec-reporter": "4.2.1",
"jquery": "2.2.4",
"karma": "^5.0.0",
"karma-chrome-launcher": "^3.1.0",
"karma-cli": "1.0.1",
"karma-coverage": "1.1.1",
"karma-coverage-istanbul-reporter": "^1.3.0",
"karma-htmlfile-reporter": "0.3.5",
"karma-jasmine": "1.1.0",
"karma-jasmine-html-reporter": "0.2.2",
"karma-phantomjs-launcher": "1.0.4",
"karma-requirejs": "1.1.0",
"karma-sonarqube-unit-reporter": "0.0.13",
"load-grunt-tasks": "3.5.2",
"protractor": "5.2.0",
"requirejs": "2.3.5",
"time-grunt": "1.4.0",
"ts-node": "3.3.0",
"tslint": "~6.1.0",
"typescript": "^4.0.8",

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by bxdadwhal** [comment]
1. **version of Angular CLI used** - 10.2.4
2. **.angular-cli.json or angular.json configuration ;**
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "external": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "build",
            "index": "src/citations.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/favicon.ico",
              "src/components/**/*.html",
              "src/css/gd.min.css",
              "src/fonts",
              "src/images",
              "src/lib",
              "src/views",
              "src/gd.min.js",
              "src/index.html"
            ],
            "styles": [
              "src/styles.less"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "external:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "external:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "external:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [],
            "styles": [
              "src/styles.less"
            ],
            "assets": [
              "src/favicon.ico",
              "src/components/**/*.html",
              "src/css/gd.min.css",
              "src/fonts",
              "src/images",
              "src/lib",
              "src/views",
              "src/gd.min.js",
              "src/index.html"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "external-e2e": {
      "root": "e2e",
      "sourceRoot": "e2e",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "external:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "external",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "gd",
      "style": "less"
    },
    "@schematics/angular:directive": {
      "prefix": "gd"
    }
  }
}
3. ****version of Angular DevKit used :-** 
 ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.2.4
Node: 14.17.3
OS: win32 x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.4
@angular-devkit/build-angular   0.803.24
@angular-devkit/core            10.2.4
@angular-devkit/schematics      10.2.4
@angular/cli                    10.2.4
@angular/http                   7.2.16
@angular/material               13.1.2
@schematics/angular             10.2.4
@schematics/update              0.1002.4
rxjs                            6.6.7
typescript                      4.0.8
4. **3rd-party libraries and their versions - mentioned  in package.json file** 
package.json :-
{
"name": "gd",
"version": "2.0.0",
"engines": {
"node": "6.11.0",
"npm": "3.10.10"
},
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build --prod",
"test": "ng test",
"lint": "ng lint --type-check",
"e2e": "ng e2e",
"serve": "ng serve --proxy-config proxy.conf.json",
"coverage": "ng test --code-coverage --reporters=coverage-istanbul"
},
"private": true,
"dependencies": {
"@angular/animations": "10.2.5",
"@angular/common": "10.2.5",
"@angular/compiler": "10.2.5",
"@angular/core": "10.2.5",
"@angular/forms": "10.2.5",
"@angular/http": "7.2.16",
"@angular/material": "^13.1.2",
"@angular/platform-browser": "10.2.5",
"@angular/platform-browser-dynamic": "10.2.5",
"@angular/router": "10.2.5",
"@babel/compat-data": "^7.8.0",
"@ngrx/store": "^9.2.0",
"core-js": "2.5.1",
"dexie": "2.0.1",
"immutable": "3.8.2",
"lodash": "4.17.4",
"ngx-bootstrap": "^6.2.0",
"pouchdb-browser": "6.3.4",
"rxjs": "6.6.7",
"rxjs-compat": "^6.0.0-rc.0",
"zone.js": "0.10.3"
},
"devDependencies": {
"@angular-devkit/build-angular": "^0.803.24",
"@angular/cli": "10.2.4",
"@angular/compiler-cli": "10.2.5",
"@types/jasmine": "2.6.0",
"@types/node": "^8.10.52",
"angular": "1.6.6",
"angular-in-memory-web-api": "0.4.6",
"angular-mocks": "1.6.6",
"angular-route": "1.6.6",
"angular-sanitize": "1.6.6",
"bootstrap": "3.3.7",
"codelyzer": "3.2.2",
"concurrently": "3.5.0",
"font-awesome": "4.7.0",
"grunt": "1.0.1",
"grunt-bower-task": "0.5.0",
"grunt-cli": "1.2.0",
"grunt-concurrent": "2.3.1",
"grunt-contrib-clean": "1.1.0",
"grunt-contrib-concat": "1.0.1",
"grunt-contrib-copy": "1.0.0",
"grunt-contrib-jshint": "1.1.0",
"grunt-contrib-less": "1.4.1",
"grunt-contrib-uglify": "3.1.0",
"grunt-contrib-watch": "1.0.0",
"grunt-exec": "3.0.0",
"grunt-open": "0.2.3",
"grunt-text-replace": "0.4.0",
"istanbul": "0.4.5",
"jasmine-core": "2.8.0",
"jasmine-spec-reporter": "4.2.1",
"jquery": "2.2.4",
"karma": "^5.0.0",
"karma-chrome-launcher": "^3.1.0",
"karma-cli": "1.0.1",
"karma-coverage": "1.1.1",
"karma-coverage-istanbul-reporter": "^1.3.0",
"karma-htmlfile-reporter": "0.3.5",
"karma-jasmine": "1.1.0",
"karma-jasmine-html-reporter": "0.2.2",
"karma-phantomjs-launcher": "1.0.4",
"karma-requirejs": "1.1.0",
"karma-sonarqube-unit-reporter": "0.0.13",
"load-grunt-tasks": "3.5.2",
"protractor": "5.2.0",
"requirejs": "2.3.5",
"time-grunt": "1.4.0",
"ts-node": "3.3.0",
"tslint": "~6.1.0",
"typescript": "^4.0.8",
5. **### **and most importantly - a use-case that fails :**-**  
npm run coverage

> gd@2.0.0 coverage
> ng test --code-coverage --reporters=coverage-istanbul

10% building 2/2 modules 0 active16 01 2022 14:17:01.756:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
16 01 2022 14:17:01.762:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
16 01 2022 14:17:01.782:INFO [launcher]: Starting browser PhantomJS
16 01 2022 14:17:30.822:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: Connected on socket XQxX-OEy9tq2TBclAAAA with id 86752245
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at http://localhost:9876/_karma_webpack_/polyfills.js:9995
PS C:\Users\bdadwhal-etc\angular-migration8.1> git restore src/tsconfig.spec.json
PS C:\Users\bdadwhal-etc\angular-migration8.1> ng test --browsers=Chrome --codeCoverage=true
10% building 3/3 modules 0 active16 01 2022 14:19:15.217:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
16 01 2022 14:19:15.222:INFO [launcher]: Launching browser Chrome with unlimited concurrency
16 01 2022 14:19:15.234:INFO [launcher]: Starting browser Chrome
16 01 2022 14:19:47.841:INFO [Chrome 91.0.4472 (Windows 10.0.0)]: Connected on socket LEcl44HM0hMihb6PAAAA with id 44316134
Chrome 91.0.4472 (Windows 10.0.0) AppComponent should create the app FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.--Pending async tasks are: [type: macroTask, source: requestAnimationFrame, args: {isPeriodic:false,delay:undefined,args:[object Arguments],handleId:1}]
Chrome 91.0.4472 (Windows 10.0.0): Executed 2 of 191 (1 FAILED) (0 secs / 5.361 secs)
Chrome 91.0.4472 (Windows 10.0.0) AppComponent should create the app FAILED
        Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.--Pending async tasksChrome 91.0.4472 (Windows 10.0.0): Executed 189 of 191 (1 FAILED) (skipped 2) (7.237 secs / 7.036 secs)
Handlebars: Access has been denied to resolve the property "statements" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "branches" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "functions" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
Handlebars: Access has been denied to resolve the property "lines" because it is not an "own property" of its parent.
You can add a runtime option to disable the check or this warning:
See https://handlebarsjs.com/api-reference/runtime-options.html#options-to-control-prototype-access for details
PS C:\Users\bdadwhal-etc\angular-migration8.1> npm run coverage

> gd@2.0.0 coverage
> ng test --code-coverage --reporters=coverage-istanbul

10% building 3/3 modules 0 active16 01 2022 14:29:41.914:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
16 01 2022 14:29:41.919:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
16 01 2022 14:29:41.950:INFO [launcher]: Starting browser PhantomJS
15% building 44/46 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\core-js\modules\es.object.get-prototype-of.js16% building 51/52 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re16% building 55/57 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor16% building 56/57 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re16% building 57/59 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor16% building 58/59 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re16% building 58/60 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 59/60 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 59/61 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 60/61 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 60/62 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 61/62 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 61/63 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 62/63 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 62/64 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 63/64 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 63/65 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 64/65 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 64/66 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 65/66 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 65/67 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor17% building 66/67 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re17% building 66/68 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 67/68 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 67/69 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 68/69 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 68/70 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 69/70 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 69/71 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 70/71 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 70/72 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 71/72 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 71/73 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 72/73 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 72/74 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 73/74 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 73/75 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor18% building 74/75 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re18% building 74/76 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 75/76 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 75/77 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 76/77 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 76/78 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 77/78 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 77/79 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 78/79 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 78/80 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 79/80 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 79/81 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 80/81 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 80/82 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 81/82 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 81/83 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 82/83 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 82/84 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor19% building 83/84 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re19% building 83/85 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 84/85 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 84/86 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 85/86 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 85/87 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 86/87 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 86/88 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 87/88 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 87/89 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 88/89 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 88/90 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 89/90 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 89/91 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 90/91 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 90/92 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor20% building 91/92 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re20% building 91/93 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor21% building 92/93 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 92/94 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor21% building 93/94 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 93/95 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor21% building 94/95 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 94/96 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor21% building 95/96 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 95/97 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor21% building 96/97 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 96/98 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor21% building 97/98 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 97/99 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\cor21% building 98/99 modules 1 active ...ex.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 98/100 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\co21% building 99/100 modules 1 active ...x.js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re21% building 99/101 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\co

22% building 100/101 modules 1 active ....js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re22% building 100/102 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\c22% building 101/102 modules 1 active ....js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re22% building 101/103 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\c22% building 102/103 modules 1 active ....js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re22% building 102/104 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\c22% building 103/104 modules 1 active ....js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re22%
building 103/105 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\c22% building 104/105 modules 1 active ....js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re22% building 104/106 modules 2 active C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\@angular-devkit\build-angular\node_modules\c22% building 105/106 modules 1 active ....js??embedded!C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\cjs.js??re16 01 2022 14:30:14.772:INFO [PhantomJS 2.1.1 (Windows 8.0.0)]: Connected on socket 9bY0LiR23bRtqYW9AAAA with id 96151970
PhantomJS 2.1.1 (Windows 8.0.0) ERROR
  SyntaxError: Use of reserved word 'class'
  at http://localhost:9876/_karma_webpack_/vendor.js:116
PS C:\Users\bdadwhal-etc\angular-migration8.1>
