### ISSUE TITLE
Running tests with code coverage doesn't include files outside the sourceRoot directory

### ISSUE THREAD

**Issue by Michael-Ziluck** [angular/angular-cli#22531]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Any time before PR #11974

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

1. ng new test-app
2. create packages/test-package outside of src folder
3. add there simple test.component.ts and test.component.spec.ts
4. Modify test.ts file and add context of 'packages directory
replace
```javascript
const context = require.context('./', true, /\.spec\.ts$/);
context.keys().map(context1);
```
with
```javascript
const context1 = require.context('../packages', true, /\.spec\.ts$/);
const context2 = require.context('./', true, /\.spec\.ts$/);

context1.keys().map(context1);
context2.keys().map(context2);
```
5. Add "../packages/**/*.spec.ts", to tsconfig.spec.json in "include" section

6. Run `ng test --code-coverage` and open coverage/index.html

## 🔥 Exception or Error

No error but the files outside the directory are not included in the coverage report.

**Anything else relevant?**

This was reported previously on issue #12474. They simply dismissed it as saying only files under `sourceRoot` are listed on the coverage report. Having the intended behavior be where tests from outside `sourceRoot` are ran but not included in the coverage report seems counterintuitive. They should either both be ran and included in the coverage report or not included in either place.

**Comment by alan-agius4** [comment]
Hi @Michael-Ziluck, 

I general we don't expect users to amend the `require.context` statement, Having multiple `require.context` in this case can cause other undefined behaviour when using certain options such as [`--include`](https://angular.io/cli/test).

I think in this case we should issue an error/warning when
- detecting multiple `require.context
- trying to include sourcefiles outside of the source root folder.


Maybe we can also do a migration to remove all `require.context` from the `test.ts` and instead set the default value of `--include` to `**/*.spec.ts`

**Comment by Michael-Ziluck** [comment]
Just opened a PR to add docs around this until a solution is decided on. I think simply showing a warning when non-sourceRoot folders are included is fine. Maintaining this behavior would also force users to set up their project structure according to the guidelines from the docs.
