### ISSUE TITLE
npm run --production doesn't work in Angular apps

### ISSUE THREAD

**Issue by TatyanaMolchanova** [angular/angular-cli#22534]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

I tried on 2 projects to do below described things and got the same error in the both cases.

1. I deleted node_modules folder from the Angular app.
2. Then made:
npm install --production
with intention for faster and more optimized deploy without DevDependencies for the prod.
3. Then on 
npm run start
or 
npm run build
I got a such error:

![Screenshot_7](https://user-images.githubusercontent.com/44355525/150320366-b51aa840-672b-4aec-9f1e-ff37f5beb1fb.png)

There is the same on build - npm run build - command
![Screenshot_4](https://user-images.githubusercontent.com/44355525/150326018-eac1cb89-89d1-4aab-89e8-0838135ea087.png)

### Please provide a link to a minimal reproduction of the bug

https://github.com/TatyanaMolchanova/AngularBlog

### Please provide the exception or error you saw

```true
PS E:\myProjects\AngularBlog> npm run start

> blog@0.0.0 start E:\myProjects\AngularBlog
> ng serve

'ng' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blog@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the blog@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm-cache\_logs\2022-01-20T09_53_15_270Z-debug.log
PS E:\myProjects\AngularBlog>
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
Ivy Workspace: Yes

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1001.4
@angular-devkit/build-angular       0.1002.0
@angular-devkit/core                10.1.4
@angular-devkit/schematics          10.1.4
@angular/animations                 10.1.4
@angular/cli                        10.1.4
@angular/common                     10.1.4
@angular/compiler                   10.1.4
@angular/compiler-cli               10.1.4
@angular/forms                      10.1.4
@angular/platform-browser           10.1.4
@angular/platform-browser-dynamic   10.1.4
@angular/pwa                        0.1002.0
@angular/router                     10.1.4
@schematics/angular                 10.1.4
@schematics/update                  0.1001.4
rxjs                                6.6.3
typescript                          4.0.3
```

### Anything else?

'ng' is not recognized as an internal or external command

It's because the life meaning packages of Angular are in the DevDependincies. 
So, npm install --production doesn't work for all Angular apps. I count that it's very bad. 
It will be nice if this command work for Angular and then the deploy of Angular apps will be faster and lighter.

**Comment by alan-agius4** [comment]
Hi @TatyanaMolchanova, 

This is expected.

Most of the `devDependencies` are needed to build/test your Angular application. Typically `npm install --production` is used on production server to install only dependencies that are required to run and already built the application on such use case is for SSR apps.

`@angular/cli` itself have numerous transitive dependencies which are not intended to be installed on production environments.

In many case the installation time when using `npm install` vs `npm install --production` is negligible.

**Comment by TatyanaMolchanova** [comment]
I have the project with SSR - https://github.com/TatyanaMolchanova/tanechka and I run usual build for this app without problem:
npm run build:ssr
![Screenshot_1](https://user-images.githubusercontent.com/44355525/150624893-78f1a045-d3bb-4842-adc7-92a534a6b5f6.png)

But when I deleted node_modules and made:
1. npm install --production
2. npm run build:ssr
Build failed with the error - please, see screenshots.
![Screenshot_2](https://user-images.githubusercontent.com/44355525/150624894-19ff59cc-944f-4c88-9b1a-3a3040d78c9b.png)

So, this command npm install --production is not working for ALL Angular apps and I count that it's not good at all that the regular npm command is not working in any Angualr apps - client-side or server-side.

**Comment by TatyanaMolchanova** [comment]
I have the project with SSR - https://github.com/TatyanaMolchanova/tanechka and I run usual build for this app without problem:
npm run build:ssr
![Screenshot_1](https://user-images.githubusercontent.com/44355525/150624893-78f1a045-d3bb-4842-adc7-92a534a6b5f6.png)

But when I deleted node_modules and made:
1. npm install --production
2. npm run build:ssr
Build failed with the error - please, see screenshots.
![Screenshot_2](https://user-images.githubusercontent.com/44355525/150625380-69c71c56-cd0d-4828-8ab0-81a41d87500e.png)


So, this command npm install --production is not working for ALL Angular apps and I count that it's not good at all that the regular npm command is not working in any Angualr apps - client-side or server-side.

**Comment by alan-agius4** [comment]
This is expected since `ng` or the Angular CLI is not expected to be present on production servers. 

Typically you want to run `npm install --production` postbuild and not prebuild, as this command should install dependencies that are required for the runtime of the application.
