### ISSUE TITLE
[build_webpack] doesn't work with esm

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#22547]
when adding [build webpack](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_webpack) to an esm Angular project (a project has `type: module` in package.json and `module: ES2022` in tsconfig.json) got the following error
```
An unhandled exception occurred: Must use import to load ES Module: /home/projects/node-tyenbp/webpack.config.js
require() of ES modules is not supported.
```

**Comment by JoostK** [comment]
What's in `/home/projects/node-tyenbp/webpack.config.js`?

**Comment by eng-dibo** [comment]
> What's in `/home/projects/node-tyenbp/webpack.config.js`?

just an empty configuration for testing. I just want `build webpack` to properly import it as esm

webpack.config.js (esm)
```
export default {};
```

**Comment by alan-agius4** [comment]
What version of build-webpack and webpack are you using?

**Comment by JoostK** [comment]
Could you share a repro?

**Comment by alan-agius4** [comment]
Actually there isn’t a need for a reproduction as I managed to track down the issue.

**Comment by eng-dibo** [comment]
does this commit fix [this package](https://www.npmjs.com/package/@angular-devkit/build-angular) which hosted [here](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_webpack) or should we wait until it reflects there?

**Comment by eng-dibo** [comment]
> Could you share a repro?

a [minimal reproduction](https://stackblitz.com/edit/node-tyenbp?file=angular.json) 

run `npm run build`
a [pull request](https://github.com/angular/angular-cli/pull/22553) already committed thanks to @alan-agius4, waiting for [the package](https://www.npmjs.com/package/@angular-devkit/build-angular) to be updated
