### ISSUE TITLE
facing less error in angular 12 

### ISSUE THREAD

**Issue by bxdadwhal** [angular/angular-cli#22548]
./src/styles.less - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

Chunk.split is not a function

    at processResult (C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\webpack\lib\NormalModule.js:713:19)
    at C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\webpack\lib\NormalModule.js:819:5
    at C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.lessLoader (C:\Users\bdadwhal-etc\angular-migration8.1\node_modules\less-loader\dist\index.js:54:5)

**Comment by bxdadwhal** [comment]
**package.json**
{
  "name": "gd",
  "version": "2.0.0",
  "engines": {
    "node": "14.17.3",
    "npm": "8.3.0"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint --type-check",
    "e2e": "ng e2e",
    "serve": "ng serve --proxy-config proxy.conf.json",
    "coverage": "ng test --code-coverage --reporters=coverage"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/http": "7.2.16",
    "@angular/material": "^12.2.0",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@babel/compat-data": "^7.8.0",
    "@ngrx/store": "^9.2.0",
    "@types/jasminewd2": "^2.0.3",
    "core-js": "2.5.1",
    "dexie": "2.0.1",
    "immutable": "3.8.2",
    "karma-typescript": "^3.0.5",
    "lodash": "4.17.4",
    "ngx-bootstrap": "^7.0.0",
    "pouchdb-browser": "6.3.4",
    "rxjs": "6.6.0",
    "rxjs-compat": "^6.6.7",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.8",
    "@angular/cli": "~12.2.8",
    "@angular/compiler-cli": "~12.2.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "angular": "1.6.6",
    "angular-in-memory-web-api": "0.4.6",
    "angular-mocks": "1.6.6",
    "angular-route": "1.6.6",
    "angular-sanitize": "1.6.6",
    "bootstrap": "3.3.7",
    "codelyzer": "^6.0.0",
    "concurrently": "3.5.0",
    "font-awesome": "4.7.0",
    "grunt": "1.0.1",
    "grunt-bower-task": "0.5.0",
    "grunt-cli": "1.2.0",
    "grunt-concurrent": "2.3.1",
    "grunt-contrib-clean": "1.1.0",
    "grunt-contrib-concat": "1.0.1",
    "grunt-contrib-copy": "1.0.0",
    "grunt-contrib-jshint": "1.1.0",
    "grunt-contrib-less": "1.4.1",
    "grunt-contrib-uglify": "3.1.0",
    "grunt-contrib-watch": "1.0.0",
    "grunt-exec": "3.0.0",
    "grunt-open": "0.2.3",
    "grunt-text-replace": "0.4.0",
    "jasmine-core": "^3.8.0",
    "jasmine-spec-reporter": "^5.0.0",
    "jquery": "2.2.4",
    "karma": "^6.3.0",
    "karma-chrome-launcher": "^3.1.0",
    "karma-cli": "1.0.1",
    "karma-coverage": "^2.0.3",
    "karma-htmlfile-reporter": "0.3.5",
    "karma-jasmine": "^4.0.0",
    "karma-jasmine-html-reporter": "^1.7.0",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-requirejs": "1.1.0",
    "karma-sonarqube-unit-reporter": "0.0.13",
    "load-grunt-tasks": "3.5.2",
    "protractor": "^7.0.0",
    "requirejs": "2.3.5",
    "time-grunt": "1.4.0",
    "ts-node": "^8.3.0",
    "tslint": "^6.1.0",
    "typescript": "^4.3.5"
  }
}

**Comment by bxdadwhal** [comment]
i am able to compile the code successfully only facing less-loader error during unit test from npm run test

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by bxdadwhal** [comment]
@alan-agius4 https://github.com/bxdadwhal/angular12/

**Comment by alan-agius4** [comment]
@bxdadwhal, the above link results in a 404, is the above a private repro?

**Comment by bxdadwhal** [comment]
please try now @alan-agius4

**Comment by bxdadwhal** [comment]
@alan-agius4 are you able to reproduce and troubleshoot the above error ?

**Comment by bxdadwhal** [comment]
@JoostK @alan-agius4 please suggest any fix on this bug for angular version 12

**Comment by alan-agius4** [comment]
@bxdadwhal, kindly re-share the reproduction, without the reproduction we will be unable to look at this issue.

**Comment by bxdadwhal** [comment]
@alan-agius4 i am working on setting minimal repo , do not want to share the whole code

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.

If the problem persists please open a new issue with a minimal reproduction. Thanks.
