### ISSUE TITLE
Ability to specify webSocketURL for dev server

### ISSUE THREAD

**Issue by david-shortman** [angular/angular-cli#22549]
### Which @angular/* package(s) are relevant/releated to the feature request?

@angular/cli

### Description

Add ability to specify the `webSocketURL` for the dev server.

This would enable developers who run their Angular app behind another service/proxy locally to still have the webpack-dev-server work properly.

### Proposed solution

Something in the `angular.json` build configuration like 

```
"development": {
    "optimization": false,
    "sourceMap": true,
    "webSocketUrl": "localhost:4200" 
}
```

### Alternatives considered

The service/proxy in front of the development Angular server _could_ pass through websocket connections, although this may be nontrivial in many cases.

**Comment by alan-agius4** [comment]
You should be able to use the public-host option for this use-case.
See: https://angular.io/cli/serve
