### ISSUE TITLE
[build_webpack] extend the original Angular builder

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#22555]
in [your example](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_webpack) you have to create new build targets like "build-webpack" instead of just modifying the existing targets like "build".

 inspiring from [custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack) you better extend the original builder and just add a new options property `webpackConfig`

also does it support targets other than `build` and `serve` like `server`?

**Comment by alan-agius4** [comment]
`@angular-devkit/build-webpack` and `@angular-builders/custom-webpack` serve different purposes. 

The build-webpack package is intended to run webpack as an architect builder, Under the hood this is what `@angular-devkit/build-angular` uses to run `webpack`. As long as a valid configuration is provided, it can run it, independent on the platform. This package is considered experimental.

`@angular-builders/custom-webpack`, extends `@angular-devkit/build-angular` and allows additional webpack configuration to be added. While the Angular CLI allows to be extended, the fact that it uses Webpack is an implementation detail which can change in future, Changing the bundler shouldn't effect Angular CLI users that are on the supported path. Also, custom webpack configurations are also not supported by the Angular team.

**Comment by eng-dibo** [comment]
> also does it support targets other than `build` and `serve` like `server`?

**Comment by alan-agius4** [comment]
If you configure Webpack to target Node.js environments you can generate a server bundle.
