### ISSUE TITLE
`ng new --next`

### ISSUE THREAD

**Issue by dgp1130** [angular/angular-cli#22557]
# 🚀 Feature request

### Command (mark with an `x`)

- [X] new

### Description

For prerelease testing, it's pretty common to make a new application, switch it to `next` dependencies, and then test out a new feature. As it stands, we have to:

1. `ng new` a new application.
2. Update `package.json` to use `next` for all the Angular versions (where it is easy to miss one).
3. Run `npm install` to get updated dependencies.

### Describe the solution you'd like

Ideally we could just do something like `ng new --next` and generate the application with `next` in `package.json`. This would be useful for prerelease testing as well as for communicating to GDE's and other prerelease testers "Just run `ng new --next` and then try out the feature!"

**Comment by alan-agius4** [comment]
At the moment this can be done via `npx @angular/cli@next new ...`.

**Comment by alan-agius4** [comment]
Closing as per offline convo.
