### ISSUE TITLE
Upgrade of @angular-devkit/build-angular from 13.1.3 to 13.1.4, seeing BrowserslistError

### ISSUE THREAD

**Issue by jrdutton** [angular/angular-cli#22552]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular-devkit/build-angular 13.1.3

### Description

I have upgraded the version of @angular-devkit/build-angular from 13.1.3 to 13.1.4. The build appears fine until the SCSS compilation stage. Now I am seeing the error:

ERROR in ./projects/claims/src/styles-kendo.scss (./projects/claims/src/styles-kendo.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[5].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[5].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[5].rules[1].use[1]!./projects/claims/src/styles-kendo.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
BrowserslistError: Unknown version 95 of android
    at Function.select (<my path>\node_modules\autoprefixer\node_modules\browserslist\index.js:1147:17)
    at <my path>\node_modules\autoprefixer\node_modules\browserslist\index.js:341:33
    at Array.reduce (<anonymous>)
    at resolve (<my path>\node_modules\autoprefixer\node_modules\browserslist\index.js:320:18)
    at browserslist (<my path>\node_modules\autoprefixer\node_modules\browserslist\index.js:451:21)
    at Browsers.parse (<my path>\node_modules\autoprefixer\lib\browsers.js:54:12)
    at new Browsers (<my path>\node_modules\autoprefixer\lib\browsers.js:42:26)
    at loadPrefixes (<my path>\node_modules\autoprefixer\lib\autoprefixer.js:106:20)
    at Object.prepare (<my path>\node_modules\autoprefixer\lib\autoprefixer.js:120:22)
    at <my path>\node_modules\@angular-devkit\build-angular\node_modules\postcss\lib\lazy-result.js:149:39
 @ ./projects/claims/src/styles-kendo.scss

## 🔥 Exception or Error

<pre><code>
BrowserslistError: Unknown version 95 of android
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.4
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@angular/cli                    13.1.4
@schematics/angular             13.1.4
rxjs                            7.5.2
typescript                      4.4.4
</code></pre>

**Comment by alan-agius4** [comment]
Can you please try to remove the node_modules and lock file and try a fresh installation?

```
rm -rf node_modules package-lock.json
npm i
```

**Comment by jrdutton** [comment]
Apologies, npx browserslist@latest --update-db fixed this.
