### ISSUE TITLE
have issues while installing Angular CLI

### ISSUE THREAD

**Issue by ovais** [angular/angular-cli#2256]
> Please provide us with the following information:
> ---------------------------------------------------------------

Windows 10

Also tried using both normal and Admin access. 

here is the log

C:\WINDOWS\system32>npm install -g angular-cli
npm WARN peerDependencies The peer dependency webpack@* included from html-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> execSync@1.0.2 install C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular2-template-loader\node_modules\codecov\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn node-gyp ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn node-gyp',
  path: 'node-gyp',
  spawnargs: [ 'rebuild' ] }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/
> node-zopfli@1.4.0 install C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.5.0 (node-v46 ABI) (falling back to source compile with node-gyp)
\
C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modul(node "" clean ) ode-gyp.js" clean )  else |
|
C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\aoa\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\compression-webpack-plugin\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\Users\\aoa\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\compression-webpack-plugin\\node_modules\\node-zopfli\\lib\\binding\\node-v46-win32-x64"
gyp ERR! cwd C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Windows_NT 10.0.14393
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aoa\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\compression-webpack-plugin\\node_modules\\node-zopfli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli
node-pre-gyp ERR! node -v v4.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\compression-webpack-plugin\node_modules\node-zopfli\lib\binding\node-v46-win32-x64' (1)
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN optional dep failed, continuing node-zopfli@1.4.0
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
\
> node-sass@3.10.0 install C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.0/win32-x64-46_binding.node
Binary downloaded and installed at C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-46\binding.node

> node-sass@3.10.0 postinstall C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass
> node scripts/build.js

"C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-sass\vendor\win32-x64-46\binding.node" exists.
 testing binary.
Binary is fine; exiting.
C:\Users\aoa\AppData\Roaming\npm\ng -> C:\Users\aoa\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.22 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WINDOWS\system32\npm-debug.log

**Comment by splintercode** [comment]
@ovais Try running `npm install --global --production windows-build-tools` then try installing the CLI again. The previous command installs the C++ compilers that node-gyp needs. Windows by default does not have these installed and unfortunately this is just a quirk of working with nodejs on windows. 
https://www.npmjs.com/package/windows-build-tools

**Comment by Rellbits** [comment]
Same error here. Tried different things. Gave up for the moment.

Windows 7
Node: v6.6.0
npm:  3.10.8

I read in another post that it should not be a requirement to install windows-build-tools, which also installs python 2.7.11 and takes foverer to finish the installation (i did it anyway, but didnt help).

Looking at the log and for what i can understand, execsync v1.0.2 fails to compile native extensions and because of that falls back to node-gyp, which requires  windows-build-tools for Windows.
Is this correct?

**Comment by spillai98** [comment]
@splintercode Any way around for MAC users ?
using- Mac X El Capitan ( Version - 10.11. 3)

**Comment by adiachenko** [comment]
I can confirm that running `npm install --global --production windows-build-tools` **WILL NOT** fix this.

**Comment by Code-Bear** [comment]
I am getting the same errors on my Windows 10 install; looks like it can't find zopfli and then attempts to use python, which isn't installed.

**Comment by jcgomeztg** [comment]
i had same problem and noticed that angular-cli requires npm 3.x.x to be installed, after updating npm i could be installed **npm install npm -g**

**Comment by lekova** [comment]
I'm following the instructions in [Upgrade from Beta.10 to Beta.14](https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14) trying to migrate to angular-cli@latest, running on Windows 10. I have deleted node_modules, tmp and dist, upgraded the npm version, run the uninstall, cache clean and install, and I'm getting an error:
![angular-cli error](https://cloud.githubusercontent.com/assets/12982223/18727281/f0dee0fe-8015-11e6-8522-b9bf794d610d.png)

**Comment by filipesilva** [comment]
@ovais as @jcgomeztg mentioned, Angular CLI needs npm 3. The errors you are getting (`npm ERR! peerinvalid`) are due to npm 2.

@lekova there was a bug with beta.15 I believe, that gave you that message. Try beta.16 and if the problem persists please open a new issue.

**Comment by luismanuelmansilla** [comment]
Update Nodejs to version 4.
update NPM npm install npm@latest -g
and them install angular-cli -> npm install -g angular-cli

**Comment by Chembeti** [comment]
I had the same issue and after following luismanuelmansilla suggestions, I could install it. I have verified the installation with the commands "ng new" and "ng serve".

**Comment by joe-vella** [comment]
With "npm install -g angular-cli", new projects get angular release candidate bits and no modules. When I try "npm install -g angular-cli@latest" I get the same issues listed above. I am also on Window 10; I did try installing the windows-build-tools. I also tried "npm install npm -g" as suggested to only have that blow up too. I am currently at npm 3.0.0 and node 4.6.1.

**Comment by joe-vella** [comment]
SUCCESS! I ran "npm install npm@latest -g" which worked; I am now at npm 3.10.9. I then ran "npm install angular-cli@latest" which also, finally, worked and installed angular-cli 1.0.0-beta.18. I can now create a new project (at the correct angular2 version) and run it.

**Comment by grantmarch** [comment]
@joe-vella 's solution worked for me

**Comment by tylerlindell** [comment]
this does not fix it for me. 

`npm -v = 4.4.4`
`node -v = v7.8.0`
`ng -v = Error: Cannot find module 'C:\Users\tlindell\AppData\Roaming\npm\node_modules\an
gular-cli\bin\ng'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3`

**Comment by SatishMHiremath** [comment]
I have faced and fixed this issue relates node-sass and python error.Try installing latest angular cli command with the steps below

Set the system variable path as well:
C:\Users\windowsusername\AppData\Roaming\npm

C:\Users\windowsusername\AppData\Roaming\npm\node_modules\@angular\cli\bin;

C:\Program Files\nodejs;

Then start using angular cli command prompt using:
angular client project folder path>npm install -g @angular/cli@latest

angular client project folder path>npm install -g node-gyp
