### ISSUE TITLE
build keeps running when I use "ng serve"

### ISSUE THREAD

**Issue by satyacxloyalty** [angular/angular-cli#22578]
Hello,

When I run "ng serve" it keeps running with wired characters. Any help would be appreciated.

![image](https://user-images.githubusercontent.com/94636013/151199061-740dcf3c-cc07-4414-9d7c-932827bc7a10.png)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by alan-agius4** [comment]
@satyacxloyalty, try to remove the lock file and node_modules and do a fresh installation.
