### ISSUE TITLE
Importing 3rd party libs with/without type definitions [doc request]

### ISSUE THREAD

**Issue by matt-erhart** [angular/angular-cli#2257]
What's the angular-cli (webpack) way to import a js lib without any type definitions? 

For the doc request, can we get many more (and detailed) 3rd party examples in the docs? One of the biggest advantages of js is all the code out there. I think it would save people a lot of trouble if they had a lot of examples and explanations to guide them. I had this worked out with systemjs, but I ran into different issues for different libs. It would be great if someone who really understands angular-cli/webpack could try and use a wide variety of js libs (old/new, popular/obscure, with/without definitions) and just document what they did to get it to work--from download/install, config edits, type definition edits, hacks, all the way to the actual import statement (with location) they used. Would be especially great to have the logic of these steps explained.

**Comment by matt-erhart** [comment]
To answer my first question, 
```
npm install jslib --save 
//don't add anything to angular-cli.json
//then, in the file you want to use the jslib add:
var jslib = require('jslib')
```

**Comment by serhiisol** [comment]
It's not the case, you should provide definitions for typescript directly, but not to CLI.

**Comment by JanStureNielsen** [comment]
@matt-erhart - the issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

**Comment by filipesilva** [comment]
Heya, I added some documentation about this on #2487.
