### ISSUE TITLE
Error: NormalModuleFactory.beforeResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created. at: node_modules\webpack\lib\NormalModuleFactory.js:644:11 

### ISSUE THREAD

**Issue by MohammedAejazAhmed** [angular/angular-cli#22589]
issue resolved

**Comment by alan-agius4** [comment]
@MohammedAejazAhmed, custom webpack configurations are not supported by the Angular team.

It also appears that you are using a no longer supported version of Angular. Please see: https://angular.io/guide/releases#support-policy-and-schedule
