### ISSUE TITLE
Module generation has no documentation.

### ISSUE THREAD

**Issue by filipesilva** [angular/angular-cli#2259]
Currently we have no documentation for the `ng generate module` functionality, it would be helpful to have some in the readme.

**Comment by splintercode** [comment]
@filipesilva out of curiosity will documentation for the CLI remain as part of the repo or move its way over the angular.io docs?

**Comment by ShaneCourtrille** [comment]
The documentation for ng g component should also be updated to mention how you can have your component be added to an existing module.  From looking at the tests it seems like that's possible?

**Comment by Brocco** [comment]
The wiki has been updated with information regarding module generation. The documentation will continue to improve and will be tracked here #2711
