### ISSUE TITLE
Polyfill file for webworker

### ISSUE THREAD

**Issue by BenjaminHofstetter** [angular/angular-cli#22591]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ x] serve
- [ ] test
- [ ] e2e
- [x ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
The polyfille file is not included in the webworker build. At the moment i get an error in my webworker. 
`Uncaught (in promise) ReferenceError: global is not defined``

### Describe the solution you'd like

I would like to have a polyfill.ts for my webworker and add the following content. 

```typescript

(globalThis as any).process = require('process/browser');

(globalThis as any).global.Buffer =
  (globalThis as any).global.Buffer || require('buffer').Buffer;

(globalThis as any).global.util =
  (globalThis as any).global.util || require('util').util;

```

### Describe alternatives you've considered

At the moment i don't have a workaround. I checked out several webpack options

**Comment by alan-agius4** [comment]
This is expected as each worker runs in a dedicated global scope where the window global scope cannot be accessed.

In this case if you need to add polyfills you need import/add the above polyfills in each of your workers.

Side-note: in general it's not considered a good practice to polyfill Node.JS APIs in browsers, it is recommended to use libraries are written to be run in browser context.
