### ISSUE TITLE
[BUG] WebWorker is still typescript in dist folder. IE11 Support.

### ISSUE THREAD

**Issue by nawlbergs** [angular/angular-cli#22601]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

# tldr:
- im need to support IE11 (so still on v12)
- the web-worker file generated via cli is still a `.ts` file inside my dist folder (IE no likey)
- the docs that that show you how to get your web-worker url using `include.meta` did not return the correct path in IE11.

# What happened
1. Using https://v12.angular.io/guide/web-worker
2. I added web-worker via cli to my poject.. it added a tsconfig file.. updated my angular.json etc.
3. I moved my webworker code into a service and updated paths..
    ` Worker = new Worker(new URL('./../super-logic.worker', import.meta.url));`
4. Everything ran fine in chrome.. but now IE11 was throwing `Object doesn't not support this action`.

# What  was wrong

### First Issue
After farting around for a few hours (adding shims.. looking at compiled code etc etc).. i realized the actual file in the dist folder was not `.js` but still a `.ts` file!  The url being provided to the Worker via (`new URL('./../super-logic.worker', import.meta.url)`) was `...../survey/super-logic.ts`.. and obviously IE11 didnt like that. (`/survey` is my dist/route)

**My Fix**: Changed the worker to a `js` file and edited the `tsconfig.webworker.ts` to only include `.js` files:
```
  "include": [
    "src/**/*.worker.js"
  ]
```

### Second Issue
During my debugging... I added console logs to my service to print out the url to the service worker.  For some reason, IE11 was producing a different URL than what Chrome was.
- Chrome: `...mydomain.local/survey/8230219b602f9582c8b7.js`
- IE11: `...mydomain.local/survey/take/8230219b602f9582c8b7.js`
So again.. obviously IE could not find the file...   The service was provided in root.. but it might be important to note that this service was being injected from a module which was being lazy-loaded.

**My Fix**:  Since all the files are dumped in root of the dist folder... I just hard-coded the path to the dist folder into service and used the generated filename provided by the new URL:
```javascript
      const url = new URL('./../../shared/workers/logic-worker.worker', import.meta.url);
      // IE11 hack.. for some reason this is wrong.. just force to dist folder root
      const finalUrl = `/survey/${url.toString().split('/').pop()}`;
      this.worker = new Worker(finalUrl);
```

Hopefully this helps others with this issue if nothing else.  Thanks.

### Please provide a link to a minimal reproduction of the bug

https://github.com/nawlbergs/ng-webworker-bug

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.1.4
Node: 12.22.9
Package Manager: npm 7.24.2
OS: win32 x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@schematics/angular             12.1.4
ng-packagr                      12.2.6
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by JoostK** [comment]
That is a limitation of static analysis. But perhaps this can be improved/warned about.

**Comment by alan-agius4** [comment]
This is a known Webpack limitation, see https://github.com/webpack/webpack/issues/14960 and https://github.com/webpack/webpack/issues/15165

In v13, when not using `new Worker(new URL(..));` syntax the worker file will not be emitted.

I think in this case Webpack should provide an error or maybe this is an opportunity for the community to add an ESLint rule.

**Comment by nawlbergs** [comment]
So this is an issue.. but not really a bug.  Any updates to documentation would be nice.

I guess what IS a bug is the underlying issue which made me try to change the URL in the first place.. the fact that IE11 is resolving the url to the worker differently than Chrome:

Going to this `take` route loads my takeSurvey Module... module is what injects my worker.service (root)
```
  {
    path: 'take',
    loadChildren: () => import('./modules/survey-take/survey-take.module').then(m => m.SurveyTakeModule),
  },
```
inside my take component i inject worker.service
```
// worker.service
newWorker: () => {
  const worker = new Worker(new URL('./../workers/logic-worker.worker', import.meta.url));
}
```
when navigating to this url.. the workers fail to load in IE as its requesting wrong url in ie11
```
Chrome: ...mydomain.local/survey/8230219b602f9582c8b7.js
IE11: ...mydomain.local/survey/take/8230219b602f9582c8b7.js <-- breaks
```
