### ISSUE TITLE
ng new <project> generates for app.component.spec.ts errors

### ISSUE THREAD

**Issue by stefanaerts** [angular/angular-cli#2260]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX 

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
 ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.15
node: 6.5.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng g testApp

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

app.component.spec.ts shows "ts] Cannot find name 'describe'" 
[ts] Cannot find name 'beforeEach'.
any

![image](https://cloud.githubusercontent.com/assets/3684599/18705192/82689a34-7fed-11e6-965b-290e581bcbe9.png)

![image](https://cloud.githubusercontent.com/assets/3684599/18705207/9c8b486c-7fed-11e6-928e-eac599606c48.png)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by stefanaerts** [comment]
Is this again something related to typings or typescript?
I see in tsconfig.json this:
![image](https://cloud.githubusercontent.com/assets/3684599/18705612/3220180c-7fef-11e6-9be8-6dd78e5ceb82.png)

And when i go those types i see this in the metadata json file

![image](https://cloud.githubusercontent.com/assets/3684599/18705581/1c72b5d2-7fef-11e6-902b-1af207f175ce.png)

I see describe there as global.
So why do i get the error in the editor?
Is that path not good ?
 "typeRoots": [
      "../node_modules/@types"
    ]

**Comment by stefanaerts** [comment]
Ok, i found the problem. its not the CLI.
CLI works fine,the tests run as expected. 
But the editor needs to know the path to the correct typescript version.
So this i added to my user preferences(settings.json):
  "typescript.tsdk": "node_modules/typescript/lib",

![image](https://cloud.githubusercontent.com/assets/3684599/18706376/01e8940e-7ff2-11e6-8639-2a6af432e8ee.png)

**Comment by stefanaerts** [comment]
and some other maybe useful information.
if you use
 "typeRoots": [
      "../node_modules/@types"
    ],
together with 
"types": [
      "firebase"
    ]
you get errors.
So remove types, just use"typeRoots": [
      "../node_modules/@types"
    ]

**Comment by UncleGena** [comment]
...or, just add to tsconfig.json in src folder: 

`,
    "exclude": [
        "**/*.spec.ts"
    ]
`

**Comment by surya1104** [comment]
just add 
import { } from 'jasmine';
Helped me to resolve the errors

**Comment by Dhananjayi9** [comment]
I am facing same issue after upgrading to angular 6
