### ISSUE TITLE
support 'ng update' in nx

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular-cli#22608]
currently we cannot use ng update the way nx advocates manually

nx states

```
Running "ng update" can still be useful in some dev workflows, so we aren't planning to remove it.
If you need to use it, run "FORCE_NG_UPDATE=true ng update".
```

if we choose to operate this semantic we see the following

```
meanstack02@admin lmig % FORCE_NG_UPDATE=true ng update
Unable to read workspace file '/Users/meanstack02/lmig/lmig/angular.json': Invalid format version detected - Expected:[ 1 ] Found: [ 2 ]
```

semantics are confusing on the name of the file and build targets

**Comment by alan-agius4** [comment]
Hi @nhhockeyplayer,

The `angular.json` generated by NX is very different from the `angular.json` generated the Angular CLI and other than the name they don't share much else. These are not interchangeable as their schemas are different. NX's `angular.json` is the same as their `workspace.json`.

The `angular.json`, `project.json`, `workspace.json` schema generated by the NX are strictly controlled by them and therefore migration of these files should be provided by them.
