### ISSUE TITLE
typescript loading order

### ISSUE THREAD

**Issue by subarroca** [angular/angular-cli#2261]
I'm using angular-cli@1.0.0-beta.15 and angular@2.0.0.

I have a complete application working with system (beta9). I'm trying to update to webpack (beta15). Im facing a problem that seems related to loading order.
Some of my files need a module that is created afterwards hence the app fails.
Is there any way to tell angular-cli the order of build?

**Comment by JanStureNielsen** [comment]
@subarroca - the issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.
