### ISSUE TITLE
just need to update every time i need to uninstall and install again i need to migrate my project to latest one its not good

### ISSUE THREAD

**Issue by sambanthar** [angular/angular-cli#2262]
just need to update every time i need to uninstall and install again i need to migrate my project to latest one its not good can u suggest me any other way

**Comment by aszechlicki** [comment]
don't do this? :)

seriously though, last two or three versions I updated by just ``npm install angular-cli@latest``, then ``ng init`` and it worked fine
you can even skip ``ng init`` as long as there are no braking changes in the config or dependencies

**Comment by sambanthar** [comment]
o great thank @aszechlicki. you gave me a solution
