### ISSUE TITLE
Building library after upgrading to Angular 12 produces no output

### ISSUE THREAD

**Issue by vistiyos** [angular/angular-cli#22621]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Our current project produces a success build on Angular 11

### Description

Our team has developed a small component and we are on our way to upgrade to Angular 12. After following the upgrading guide on https://update.angular.io/?v=11.0-12.0 we just get the following output executing `ng build`:

`Building Angular Package`

## 🔬 Minimal Reproduction

As this component is a proprietary solution, I cannot provide much details about it.

## 🔥 Exception or Error

No error

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.16
Node: 14.17.2
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.2.16
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.3
@angular-devkit/build-angular   12.2.15
@angular-devkit/core            10.2.3
@angular-devkit/schematics      12.2.16
@angular/cdk                    11.2.13
@schematics/angular             12.2.16
ng-packagr                      12.2.7
rxjs                            6.6.3
typescript                      4.3.5

</code></pre>

**Anything else relevant?**

When trying to enable verbose mode, I get the following output:
```Unknown option: '--verbose'```

It only happens when trying to build the library, for building the application that integrates this component (which is in the same workspace), works fine. The problem mentioned above is not happening either for this application

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro —-no-create-application` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by vistiyos** [comment]
Hi @alan-agius4 

This is the repo containing the reproducible example:

https://github.com/vistiyos/failing-lib-ng-12

Let me know if something else is needed.

**Comment by vistiyos** [comment]
Hi @alan-agius4,

Your suggestion worked but I still think that there is a bug, so I would not expect that you close this issue because the problem is still there and IMO upgrading to Angular v13 to get the proper error message is not the proper solution

**Comment by alan-agius4** [comment]
To avail of the latest features and bug fixes you need to update to the latest major version (Currently v13). Version 12 is currently in LTS and as a general rule only newly identified security vulnerability or a regression, since the start of LTS, caused by a 3rd party change, such as a new browser version are to be fixed. 

You can read more of this in our [support policy and schedule](https://angular.io/guide/releases#support-policy-and-schedule) guide.
