### ISSUE TITLE
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular-cli#22637]
# 🐞 Bug report

### Command (mark with an `x`)
I have an Angular project which I just upgrade from 12 to 13.2
In this project I have my own schematics.
In the branch with new angular 13.2 I start to get error when I execute my schematics.
When I go back to the master branch with angular version 12 schematics work as should.

**The schematics that I'm executed:**
```
/versions/node/v16.10.0/bin/node" "/Users/ofirf 1/dev/singularity-ui/node_modules/@angular/cli/bin/ng" generate @sing/component ofir
```

**The error:**
```
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "/private/var/folders/64/rqq3mpzn6tx_8bgq7l7_md700000gp/T/ng-qCJE17/angular-errors.log" for further details.
```

**Log of file angular-errors.log:**
```
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/vocabularies/core/id.js:6:15)
    at keywordCode (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/validate/index.js:454:13)
    at /Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/validate/index.js:222:17
    at CodeGen.code (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/codegen/index.js:568:18)
    at iterateKeywords (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/validate/index.js:219:9)
    at groupKeywords (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/validate/index.js:208:13)
    at /Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/validate/index.js:192:13
    at CodeGen.code (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/codegen/index.js:439:13)
    at CodeGen.block (/Users/ofirf 1/dev/singularity-ui/node_modules/ajv/dist/compile/codegen/index.js:568:18)
```

- [X] generate

### Is this a regression?
Yes

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "/private/var/folders/64/rqq3mpzn6tx_8bgq7l7_md700000gp/T/ng-qCJE17/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.0
Node: 16.10.0
Package Manager: npm 7.6.0
OS: darwin x64

Angular: 13.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.0
@angular-devkit/build-angular   13.2.0
@angular-devkit/core            13.2.0
@angular-devkit/schematics      13.2.0
@schematics/angular             13.2.0
ng-packagr                      13.2.0
rxjs                            7.5.2
typescript                      4.5.5

</code></pre>

**Comment by alan-agius4** [comment]
This is expected.

In v13 we removed the deprecated behaviour to transform `id` to `$id` Since support for JSON Schema draft-04 and draft-06 was removed in v12.

Pleade see breaking changes in https://github.com/angular/angular-cli/releases/tag/13.0.0

**Comment by ofirrifo** [comment]
@alan-agius4 

I read this from the link above.
But I'm not sure what I need to do exactly.
```
With this change we drop support for the deprecated behaviour to transform id in schemas. Use $id instead.
Note: this only effects schematics and builders authors.

The deprecated JSON parser has been removed from public API. jsonc-parser should be used instead.
```

**Comment by alan-agius4** [comment]
In your schematics schemas you need to replace  `id` with `$id`. Since the former is not valid for json schemas draft-07.
