### ISSUE TITLE
Error while building 

### ISSUE THREAD

**Issue by kanishkatn** [angular/angular-cli#2264]
Hi,

I am getting this error while doing ng build. Please help

I am using the following on mac os x El Capitan v 10.11.6
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64
npm: 3.10.7

> ERROR in   TypeError: Cannot read property 'request' of undefined
>   
>   - ExternalModuleFactoryPlugin.js:37 handleExternals
>     [web]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
>   
>   - ExternalModuleFactoryPlugin.js:46 next
>     [web]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
>   
>   - ExternalModuleFactoryPlugin.js:59 handleExternals
>     [web]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
>   
>   - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
>     [web]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
>   
>   - NormalModuleFactory.js:177 
>     [web]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:177:3
>   
>   - Tapable.js:131 
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:131:11
>   
>   - NormalModuleReplacementPlugin.js:26 NormalModuleFactory.<anonymous>
>     [web]/[angular-cli]/[webpack]/lib/NormalModuleReplacementPlugin.js:26:11
>   
>   - Tapable.js:135 NormalModuleFactory.applyPluginsAsyncWaterfall
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:135:13
>   
>   - NormalModuleFactory.js:161 NormalModuleFactory.create
>     [web]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:161:8
>   
>   - Compilation.js:356 Compilation.process [as _addModuleChain]
>     [web]/[angular-cli]/[webpack]/lib/Compilation.js:356:16
>   
>   - Compilation.js:427 Compilation.process [as addEntry]
>     [web]/[angular-cli]/[webpack]/lib/Compilation.js:427:7
>   
>   - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
>     [web]/[webpack]/lib/SingleEntryPlugin.js:22:15
>   
>   - Tapable.js:156 Compiler.applyPluginsParallel
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:156:14
>   
>   - Compiler.js:431 Compiler.compile
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:431:7
>   
>   - Compiler.js:237 Compiler.runAsChild
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:237:7
>   
>   - compiler.js:70 
>     [web]/[html-webpack-plugin]/lib/compiler.js:70:19
>   
>   - debuggability.js:272 Promise._execute
>     [web]/[bluebird]/js/release/debuggability.js:272:9
>   
>   - promise.js:475 Promise._resolveFromExecutor
>     [web]/[bluebird]/js/release/promise.js:475:18
>   
>   - promise.js:77 new Promise
>     [web]/[bluebird]/js/release/promise.js:77:14
>   
>   - compiler.js:69 Object.compileTemplate
>     [web]/[html-webpack-plugin]/lib/compiler.js:69:10
>   
>   - index.js:47 Compiler.<anonymous>
>     [web]/[html-webpack-plugin]/index.js:47:40
>   
>   - Tapable.js:156 Compiler.applyPluginsParallel
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:156:14
>   
>   - Compiler.js:431 Compiler.compile
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:431:7
>   
>   - Compiler.js:191 Compiler.<anonymous>
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:191:10
>   
>   - Compiler.js:339 Compiler.readRecords
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:339:10
>   
>   - Compiler.js:188 Compiler.<anonymous>
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:188:9
>   
>   - Tapable.js:81 next
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:81:11
>   
>   - CachePlugin.js:34 Compiler.<anonymous>
>     [web]/[angular-cli]/[webpack]/lib/CachePlugin.js:34:58
>   
>   - Tapable.js:85 Compiler.applyPluginsAsync
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:85:13
>   
>   - Compiler.js:185 Compiler.<anonymous>
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:185:8
>   
>   - Tapable.js:81 next
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:81:11
>   
>   - NodeEnvironmentPlugin.js:23 Compiler.<anonymous>
>     [web]/[angular-cli]/[webpack]/lib/node/NodeEnvironmentPlugin.js:23:3
>   
>   - Tapable.js:85 Compiler.applyPluginsAsync
>     [web]/[angular-cli]/[tapable]/lib/Tapable.js:85:13
>   
>   - Compiler.js:182 Compiler.run
>     [web]/[angular-cli]/[webpack]/lib/Compiler.js:182:7
>   
>   - build-webpack.js:23 
>     [web]/[angular-cli]/tasks/build-webpack.js:23:29
>   
>   - build-webpack.js:22 Class.run
>     [web]/[angular-cli]/tasks/build-webpack.js:22:16
>   
>   - build.js:49 Class.run
>     [web]/[angular-cli]/commands/build.js:49:26
>   
>   - command.js:152 Class.<anonymous>
>     [web]/[angular-cli]/lib/models/command.js:152:17
>   
>   - rsvp.js:1036 lib$rsvp$$internal$$tryCatch
>     [web]/[rsvp]/dist/rsvp.js:1036:16
>   
>   - rsvp.js:1048 lib$rsvp$$internal$$invokeCallback
>     [web]/[rsvp]/dist/rsvp.js:1048:17
>   
>   - rsvp.js:1019 lib$rsvp$$internal$$publish
>     [web]/[rsvp]/dist/rsvp.js:1019:11
>   
>   - rsvp.js:1198 lib$rsvp$asap$$flush
>     [web]/[rsvp]/dist/rsvp.js:1198:9
>   
>   - next_tick.js:67 _combinedTickCallback
>     internal/process/next_tick.js:67:7
>   
>   - next_tick.js:98 process._tickCallback
>     internal/process/next_tick.js:98:9

**Comment by finleysa** [comment]
What version of Webpack are you using?

**Comment by eduardocorral** [comment]
Same here, building inside a Docker container

angular-cli@1.0.0-beta.15
webpack@2.1.0-beta.22 
npm@3.10.7

node: 6.6.0
os: linux x64

> ERROR in   TypeError: Cannot read property 'request' of undefined
>   
>   - ExternalModuleFactoryPlugin.js:37 handleExternals
>     [margin-client]/[webpack]/lib/ExternalModuleFactoryPlugin.js:37:33
>   
>   - ExternalModuleFactoryPlugin.js:46 next
>     [margin-client]/[webpack]/lib/ExternalModuleFactoryPlugin.js:46:8
>   
>   - ExternalModuleFactoryPlugin.js:59 handleExternals
>     [margin-client]/[webpack]/lib/ExternalModuleFactoryPlugin.js:59:7
>   
>   - ExternalModuleFactoryPlugin.js:79 ExternalModuleFactoryPlugin.<anonymous>
>     [margin-client]/[webpack]/lib/ExternalModuleFactoryPlugin.js:79:5
>   
>   - NormalModuleFactory.js:177 
>     [margin-client]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:177:3
>   
>   - Tapable.js:131 
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:131:11
>   
>   - NormalModuleReplacementPlugin.js:26 NormalModuleFactory.<anonymous>
>     [margin-client]/[angular-cli]/[webpack]/lib/NormalModuleReplacementPlugin.js:26:11
>   
>   - Tapable.js:135 NormalModuleFactory.applyPluginsAsyncWaterfall
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:135:13
>   
>   - NormalModuleFactory.js:161 NormalModuleFactory.create
>     [margin-client]/[angular-cli]/[webpack]/lib/NormalModuleFactory.js:161:8
>   
>   - Compilation.js:356 Compilation.process [as _addModuleChain]
>     [margin-client]/[angular-cli]/[webpack]/lib/Compilation.js:356:16
>   
>   - Compilation.js:427 Compilation.process [as addEntry]
>     [margin-client]/[angular-cli]/[webpack]/lib/Compilation.js:427:7
>   
>   - SingleEntryPlugin.js:22 SingleEntryPlugin.<anonymous>
>     [margin-client]/[webpack]/lib/SingleEntryPlugin.js:22:15
>   
>   - Tapable.js:156 Compiler.applyPluginsParallel
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:156:14
>   
>   - Compiler.js:431 Compiler.compile
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:431:7
>   
>   - Compiler.js:237 Compiler.runAsChild
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:237:7
>   
>   - compiler.js:70 
>     [margin-client]/[html-webpack-plugin]/lib/compiler.js:70:19
>   
>   - debuggability.js:299 Promise._execute
>     [margin-client]/[html-webpack-plugin]/[bluebird]/js/release/debuggability.js:299:9
>   
>   - promise.js:481 Promise._resolveFromExecutor
>     [margin-client]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:481:18
>   
>   - promise.js:77 new Promise
>     [margin-client]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:77:14
>   
>   - compiler.js:69 Object.compileTemplate
>     [margin-client]/[html-webpack-plugin]/lib/compiler.js:69:10
>   
>   - index.js:47 Compiler.<anonymous>
>     [margin-client]/[html-webpack-plugin]/index.js:47:40
>   
>   - Tapable.js:156 Compiler.applyPluginsParallel
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:156:14
>   
>   - Compiler.js:431 Compiler.compile
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:431:7
>   
>   - Compiler.js:191 Compiler.<anonymous>
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:191:10
>   
>   - Compiler.js:339 Compiler.readRecords
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:339:10
>   
>   - Compiler.js:188 Compiler.<anonymous>
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:188:9
>   
>   - Tapable.js:81 next
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:81:11
>   
>   - CachePlugin.js:34 Compiler.<anonymous>
>     [margin-client]/[angular-cli]/[webpack]/lib/CachePlugin.js:34:58
>   
>   - Tapable.js:85 Compiler.applyPluginsAsync
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:85:13
>   
>   - Compiler.js:185 Compiler.<anonymous>
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:185:8
>   
>   - Tapable.js:81 next
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:81:11
>   
>   - NodeEnvironmentPlugin.js:23 Compiler.<anonymous>
>     [margin-client]/[angular-cli]/[webpack]/lib/node/NodeEnvironmentPlugin.js:23:3
>   
>   - Tapable.js:85 Compiler.applyPluginsAsync
>     [margin-client]/[angular-cli]/[tapable]/lib/Tapable.js:85:13
>   
>   - Compiler.js:182 Compiler.run
>     [margin-client]/[angular-cli]/[webpack]/lib/Compiler.js:182:7
>   
>   - build-webpack.js:23 
>     [margin-client]/[angular-cli]/tasks/build-webpack.js:23:29
>   
>   - build-webpack.js:22 Class.run
>     [margin-client]/[angular-cli]/tasks/build-webpack.js:22:16
>   
>   - build.js:49 Class.run
>     [margin-client]/[angular-cli]/commands/build.js:49:26
>   
>   - command.js:152 Class.<anonymous>
>     [margin-client]/[angular-cli]/lib/models/command.js:152:17
>   
>   - -internal.js:215 tryCatch
>     [margin-client]/[rsvp]/dist/lib/rsvp/-internal.js:215:12
>   
>   - -internal.js:230 invokeCallback
>     [margin-client]/[rsvp]/dist/lib/rsvp/-internal.js:230:13
>   
>   - -internal.js:198 publish
>     [margin-client]/[rsvp]/dist/lib/rsvp/-internal.js:198:7
>   
>   - asap.js:82 flush
>     [margin-client]/[rsvp]/dist/lib/rsvp/asap.js:82:5
>   
>   - next_tick.js:67 _combinedTickCallback
>     internal/process/next_tick.js:67:7
>   
>   - next_tick.js:98 process._tickCallback
>     internal/process/next_tick.js:98:9
>

**Comment by JanStureNielsen** [comment]
@kanishkatn @eduardocorral -- did you `ng init` your project after you upgraded to `beta.15` and integrate the differences into your projects?

**Comment by eduardocorral** [comment]
Yeah. We're checking, but I think this has to do with the fact that webpack 1.X is being used, locally, instead of the global 2.X. Investigating now.

**Comment by eduardocorral** [comment]
Ok, this is it

```
root@935756d90c36:/margin-client# npm list webpack
npm info it worked if it ends with ok
npm info using npm@3.10.7
npm info using node@v6.6.0
calypso-margin-client@0.0.1-SNAPSHOT /margin-client
+-- UNMET PEER DEPENDENCY react-tap-event-plugin@^1.0.0
`-- webpack@1.13.1  extraneous

```

versus the global

```
root@935756d90c36:/margin-client# npm list -g webpack
npm info it worked if it ends with ok
npm info using npm@3.10.7
npm info using node@v6.6.0
/usr/local/lib
`-- angular-cli@1.0.0-beta.15
  `-- webpack@2.1.0-beta.22 

npm info ok 

```

and react-tap-event-plugin is brought in by material-ui. I don't know where this is coming, though. We're not declaring it.

**BTW, declaring webpack 2.X explicitly in devDependencies solves it**. I'd rather not do it, though. Still investigating.

**Comment by eduardocorral** [comment]
False alarm: I had a stale webpack in the local node_modules (1.x), **and wrongly assumed that the latest version, declared by angular-cli (2.x), would be pulled and used instead**. Which is an interesting behavior: shouldn't the old version be ignored? Anyway...

For those wondering: I'm building inside a docker container, by copying my app folder inside of it. Container is a clean node+angular-cli installation, but the stale node_modules folder was being copied every time.

**Comment by kanishkatn** [comment]
I couldn't get it working after trying so much. I ended up using a starter project for it. I will look into it this weekend and see if it gets me somewhere.

**Comment by filipesilva** [comment]
We don't support setups where there is another local webpack installed. This is unfortunate, but architectural.

**Comment by alejandrolsca** [comment]
didn't see a solution for this error, any suggestions?

**Comment by Pokom** [comment]
@alejandrolsca 

Check your listing for Angular-cli like so

```
npm list angular-cli
npm list -g angular-cli
```

I had webpack 1.13.3 installed instead of the webpack 2.x, which is what angular-cli requires. If you see the npm list-g angular-cli as listing webpack 1.13.x, you should clean your node_module and try to do a clean build and ensure you have webpack 2.x installed.

**Comment by alejandrolsca** [comment]
@Pokom 
Thank you for the response, our build process creates a virtual machine in docker every time there's a new build, the weird thing is that it always installed an 1.x version of webpack when installing the latest angular-cli, but thanks to your advice i realize about that, what i did was to add the 2.x webpack version literally in the package.json after the angular-cli y the dev dependencies, and now is working without errors :D thanks for the advice
