### ISSUE TITLE
New app generation requires git

### ISSUE THREAD

**Issue by gatos-cc** [angular/angular-cli#22651]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

11, although was also running into bug with `ng new` there - https://github.com/angular/angular-cli/issues/21326

### Description

 A clear and concise description of the problem...

When I run `ng new <appname>` on a system without git installed, it fails.  I don't think git should be a requirement for a new app generation (I don't believe it's a documented requirement).  New app generation should also be deterministic, not relying on a git repo that could change without notice.

## 🔬 Minimal Reproduction

In a docker container:
```
FROM centos:7

USER root
RUN yum update -y
RUN echo "Installing NVM" && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash && \
    export NVM_DIR="$HOME/.nvm" && \
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
RUN echo "Installing Node" && \
    nvm install 16 && \
    nvm alias default 16 && \
    nvm use 16 && \
    mkdir -pv /opt/node && \
    cp -rf ${HOME}/.nvm/versions/node/v*/* /opt/node && \
    export PATH="/opt/node/bin:${PATH}"
RUN echo "Installing Angular" && \
    npm install -g @angular/cli@12.2.16 && \
RUN echo "Upgrading npm." && \
    npm install -g npm@8.4.0
RUN node --version && \
    npm --version && \
    ng --version

ENTRYPOINT [ "sleep" ]
CMD [ "86400" ]
```

open up a bash session in the container, and run `ng new mytestapp`:
```
$ ng new mytestapp
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE mytestapp/README.md (1056 bytes)
CREATE mytestapp/.editorconfig (274 bytes)
CREATE mytestapp/.gitignore (604 bytes)
CREATE mytestapp/angular.json (3057 bytes)
CREATE mytestapp/package.json (1073 bytes)
CREATE mytestapp/tsconfig.json (783 bytes)
CREATE mytestapp/.browserslistrc (703 bytes)
CREATE mytestapp/karma.conf.js (1426 bytes)
CREATE mytestapp/tsconfig.app.json (287 bytes)
CREATE mytestapp/tsconfig.spec.json (333 bytes)
CREATE mytestapp/src/favicon.ico (948 bytes)
CREATE mytestapp/src/index.html (295 bytes)
CREATE mytestapp/src/main.ts (372 bytes)
CREATE mytestapp/src/polyfills.ts (2820 bytes)
CREATE mytestapp/src/styles.css (80 bytes)
CREATE mytestapp/src/test.ts (788 bytes)
CREATE mytestapp/src/assets/.gitkeep (0 bytes)
CREATE mytestapp/src/environments/environment.prod.ts (51 bytes)
CREATE mytestapp/src/environments/environment.ts (658 bytes)
CREATE mytestapp/src/app/app-routing.module.ts (245 bytes)
CREATE mytestapp/src/app/app.module.ts (393 bytes)
CREATE mytestapp/src/app/app.component.css (0 bytes)
CREATE mytestapp/src/app/app.component.html (24617 bytes)
CREATE mytestapp/src/app/app.component.spec.ts (1082 bytes)
CREATE mytestapp/src/app/app.component.ts (213 bytes)
⠹ Installing packages (npm)...
✔ Packages installed successfully.
/bin/sh: git: command not found
```

## 🔥 Exception or Error

<pre><code>

/bin/sh: git: command not found

</code></pre>

## 🌍 Your Environment

<pre><code>

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.2.16
Node: 16.13.2 (Unsupported)
Package Manager: npm 8.4.0
OS: linux x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.16 (cli-only)
@angular-devkit/core         12.2.16 (cli-only)
@angular-devkit/schematics   12.2.16 (cli-only)
@schematics/angular          12.2.16 (cli-only)

Warning: The current version of Node (16.13.2) is not supported by Angular.

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
You can disable this behaviour by using the`--skip-git` option.

See https://angular.io/cli/new for all the options.
