### ISSUE TITLE
error TS5024: Compiler option 'files' requires a value of type Array

### ISSUE THREAD

**Issue by TomMettam** [angular/angular-cli#22664]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Typescript supports semantics which specify if `include`, `exclude`, `files` and `types` (possibly others) will **replace** or **merge** when extending a base `tsconfig.json` file.

e.g this will blank the array that was set at a higher level:

```
"exclude": {
    "mode": "replace",
    "values": []
  }
```

However, angular-cli complains: "error TS5024: Compiler option 'files' requires a value of type Array"

### Describe the solution you'd like

Please add support for this semantic.

**Comment by alan-agius4** [comment]
HI @TomMettam,  

The TypeScript compiler doesn't support the illustrated syntax. Where have you seen that it supports it?

**Comment by alan-agius4** [comment]
Closing as per above
