### ISSUE TITLE
`npm install` errors while running `ng new`

### ISSUE THREAD

**Issue by alexbruno** [angular/angular-cli#22665]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: latest

### Description

 A clear and concise description of the problem...

I'm having `npm install` errors while running `ng new` to create a new app for Angular 11.

## 🔬 Minimal Reproduction
`npx -p @angular/cli@11 ng new ng-11-app`

## 🔥 Exception or Error

<pre><code>

npx -p @angular/cli@11 ng new ng-payout-manager
? Do you want to enforce stricter type checking and stricter bundle budgets in t
he workspace?
  This setting helps improve maintainability and catch bugs ahead of time.
  For more information, see https://angular.io/strict Yes
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/
documentation/syntax#scss                ]
CREATE ng-payout-manager/README.md (1024 bytes)
CREATE ng-payout-manager/.editorconfig (274 bytes)
CREATE ng-payout-manager/.gitignore (631 bytes)
CREATE ng-payout-manager/angular.json (3793 bytes)
CREATE ng-payout-manager/package.json (1207 bytes)
CREATE ng-payout-manager/tsconfig.json (783 bytes)
CREATE ng-payout-manager/tslint.json (3185 bytes)
CREATE ng-payout-manager/.browserslistrc (703 bytes)
CREATE ng-payout-manager/karma.conf.js (1434 bytes)
CREATE ng-payout-manager/tsconfig.app.json (287 bytes)
CREATE ng-payout-manager/tsconfig.spec.json (333 bytes)
CREATE ng-payout-manager/src/favicon.ico (948 bytes)
CREATE ng-payout-manager/src/index.html (301 bytes)
CREATE ng-payout-manager/src/main.ts (372 bytes)
CREATE ng-payout-manager/src/polyfills.ts (2830 bytes)
CREATE ng-payout-manager/src/styles.scss (80 bytes)
CREATE ng-payout-manager/src/test.ts (753 bytes)
CREATE ng-payout-manager/src/assets/.gitkeep (0 bytes)
CREATE ng-payout-manager/src/environments/environment.prod.ts (51 bytes)
CREATE ng-payout-manager/src/environments/environment.ts (662 bytes)
CREATE ng-payout-manager/src/app/app-routing.module.ts (245 bytes)
CREATE ng-payout-manager/src/app/app.module.ts (393 bytes)
CREATE ng-payout-manager/src/app/app.component.scss (0 bytes)
CREATE ng-payout-manager/src/app/app.component.html (25757 bytes)
CREATE ng-payout-manager/src/app/app.component.spec.ts (1090 bytes)
CREATE ng-payout-manager/src/app/app.component.ts (222 bytes)
CREATE ng-payout-manager/e2e/protractor.conf.js (904 bytes)
CREATE ng-payout-manager/e2e/tsconfig.json (274 bytes)
CREATE ng-payout-manager/e2e/src/app.e2e-spec.ts (668 bytes)
CREATE ng-payout-manager/e2e/src/app.po.ts (274 bytes)
⠼ Installing packages (npm)...npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: ng-payout-manager@0.0.0
npm ERR! Found: jasmine-core@3.6.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.6.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/alex.caceres.br/.npm/eresolve-report.txt for a full report.
​
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alex.caceres.br/.npm/_logs/2022-02-07T19_14_09_201Z-debug-0.log
✖ Package install failed, see above.
The Schematic workflow failed. See above.
</code></pre>

## 🌍 Your Environment

<pre><code>

npx -p @angular/cli@11 ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 11.1.2
Node: 14.19.0
OS: darwin x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1101.2 (cli-only)
@angular-devkit/core         11.1.2 (cli-only)
@angular-devkit/schematics   11.1.2 (cli-only)
@schematics/angular          11.1.2 (cli-only)
@schematics/update           0.1101.2 (cli-only)
</code></pre>

**Anything else relevant?**

I never use anything global in my env, only `node` and `npm`. So, when I need to run any CLI tool to create a project, I do it using NPX.

I need to create a new project with `ng 11` to maintain compatibility with non-IVY private libraries and other resources made at the company I work for, like automated publishing pipelines which I don't have access to update.

I think this is related to: https://github.com/angular/angular-cli/issues/20966, but that issue is locked and I can't comment there.

**Comment by alan-agius4** [comment]
This issue has already been solved, but in your case the issue here is expected. The problem is that using `npx -p @angular/cli@11` will use a cached version of the Angular CLI and not the latest v11 that is available on NPM, if the Angular CLI was already downloaded previously and the version specifier matches.

Please use one either of the below commands
```
npx @angular/cli@11.2.18 ng new
npx @angular/cli@v11-lts ng new
```
