### ISSUE TITLE
Make it possible to use relative paths with webpack on Windows.

### ISSUE THREAD

**Issue by Mithras** [angular/angular-cli#22667]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Webpack has optional __filename variable (https://webpack.github.io/docs/api-in-modules.html#__filename). It's very simple to use this variable as angular moduleId to allow relative paths. But on Windows webpack __filename has backward slashes and angular does not understand them. Of course I can write something like "moduleId: __filename.replace(/\/g, '/')" but this breaks AOT compilation (I don't remember the exact error but it's something about expressions are not allowed).

**Expected/desired behavior**
Make angular works with backward slashes in moduleId metadata.

**Reproduction of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** all
- **Language:** all

**Comment by alan-agius4** [comment]
Closing since `__filename` is no longer exposed in browsers builds as this is a Node.js API.
 
Please be aware that Webpack specific features are not supported by the Angular CLI.
