### ISSUE TITLE
Cannot find SourceMap

### ISSUE THREAD

**Issue by sonthosh** [angular/angular-cli#2266]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
No

4. The log given by the failure. Normally this include a stack trace and some
   more information.
WARNING in ./~/ng2-toastr/src/toast.module.js
Cannot find SourceMap 'toast.module.js.map': Error: Can't resolve './toast.module.js.map' in '\node_modules\ng2-toastr\src'
 @ ./~/ng2-toastr/ng2-toastr.js 9:9-38

5. Mention any other details that might be useful.
I am getting these warnings when i do ng test. Is there a way to suppress or generate the source map for missing 3rd party vendor libraries?
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JanStureNielsen** [comment]
@sonthosh - the issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.
