### ISSUE TITLE
outDir config value is ignored in build

### ISSUE THREAD

**Issue by ThorConzales** [angular/angular-cli#2267]
OS: Win 10
Version: 1.0.0-beta.15

When doing "ng build" then output dir is always generated as "dist" regardless what value is configured in outDir.

**Comment by nhodges** [comment]
I am also experiencing this -- seems it is being ignored.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2158

**Comment by fullstackdave** [comment]
Just downloaded the latest version of the CLI and ran into this issue today.  Ignores "outDir" and builds to the "dist" folder at the root...

**Comment by fullstackdave** [comment]
This error was caused for me by my addition of multiple SPA app declarations within the angular-cli.json "apps" : [{X},{Y},{Z}].  The CLI only builds the first SPA app in the array, but I had my other apps listed so I could swap them in an out quickly and build them as desired.  Once I removed the additional app declarations the build noticed my "outDir" setting.  I hope this helps someone.
