### ISSUE TITLE
CORS error when base href is set.

### ISSUE THREAD

**Issue by hrishavkmr** [angular/angular-cli#22676]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.2.13

### Description
When i try to build the angular app using angular cli 13, all the build files like "runtime.js", "main.js" loaded using `<script/>` tag in the `index.html` have attribute `type="module"`. This causes a CORS error when `<base href="">` inside `index.html` is set to a assets server(for ex: http://127.0.0.1:8443/static/), and `index.html` is loaded over another server(for ex: http://127.0.0.1:8080).

```
Access to script at 'http://localhost:8443/static/main.js' from origin 'http://127.0.0.1:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Even if `type="module"` from the `<script/>` tag is removed, all the other JS chunks (for ex: `663.js`) which are loaded in `main.js` or `runtime.js` are still showing CORS error.

## 🔬 Minimal Reproduction
1. Create a demo angular app using angular cli 13.
2. Add `baseHref` option as empty string(for now) in angular.json.
3. Build the app
    ```
    npm run build -- --configuration development
    ```
4. After building the app, separate out all the JS builds(runtime.js, main.js etc) in one folder and `index.html` in another folder.
5. Download `live-server`
    ```
    npm install -g live-server
    ```
    **Note**: You can use any other way to serve `index.html` and all other JS builds from other server with different domain.
6. Run `live-server` command in the folder containing JS bundles and the note the URL.
7. In the `index.html`, Update `<base href>` tag with URL in step 6, and run the `live-server` command.
8. Assuming the folder containing `index.html` is served through `http://127.0.0.1:8080`, go to `http://127.0.0.1:8080/index.html` and you should be able to see the CORS error in the console.

## 🌍 Your Environment
<pre><code>

Angular CLI: 13.0.2
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.2
@angular-devkit/build-angular   13.0.2
@angular-devkit/core            13.0.2
@angular-devkit/schematics      13.0.2
@angular/cli                    13.0.2
@schematics/angular             13.0.2
rxjs                            6.6.7
typescript                      4.4.4

</code></pre>

**Comment by alan-agius4** [comment]
This is expected to due the [security requirements](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#other_differences_between_modules_and_standard_scripts) of JavaScript modules.  You'd need to configure the [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin) response header.

**Comment by hrishavkmr** [comment]
@alan-agius4 why was this `type="module"` added in all the `<script/> tags?

**Comment by alan-agius4** [comment]
Previously, we only added this when differential loading was enabled. In version 13 we no longer support IE 11 which makes using JavaScript modules possible.

**Comment by hrishavkmr** [comment]
Ok. So whenever we are using base href, we would need to configure "Access-Control-Allow-Origin" response header, right?

**Comment by alan-agius4** [comment]
If you are not using a relative base-href, yes.
