### ISSUE TITLE
Karma Jasmine / Chrome Devtools: code execution not sync with the code source, breakpoints not available/buggy

### ISSUE THREAD

**Issue by serhioV** [angular/angular-cli#22689]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] test

### Is this a regression?
I don't know the previous version

### Description

Please see the detailed explanation on [SO](https://stackoverflow.com/q/71041539/961631)

## 🔬 Minimal Reproduction

I run my tests with `yarn test --watch true` command that gives

`ng test --code-coverage --watch false --watch true`

## 🔥 Exception or Error
there is any exception, but the code in the xxx.ts file is  not possible to debug, because breakpoints are decalated versus the code, I can hit F10 and it steps, but the code under the hignlighted line is not the really debugged code.

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.16
Node: 16.13.2 (Unsupported)
Package Manager: yarn 1.22.15
OS: win32 x64

Angular: 12.2.16
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.16
@angular-devkit/build-angular   12.2.16
@angular-devkit/core            12.2.16
@angular-devkit/schematics      12.2.16
@angular/cdk                    12.2.13
@schematics/angular             12.2.16
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Comment by alan-agius4** [comment]
Hi @serhioV, 

Unfortunately, without a working reproduction it's hard to tell what is happening. There were several improvements to the code-coverage pipeline in version 13. Can you please try to update to the latest stable version and check if the problem persists?.

If the problem persists in your application after upgrading, please provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by serhioV** [comment]
update to 13 angular cli, now is much better the same code
