### ISSUE TITLE
Force exclude files from build/serve

### ISSUE THREAD

**Issue by clabough** [angular/angular-cli#22682]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I'm using CDN to deliver the files for some node_modules packages, but am importing those packages into my components during the build. Because of that, they're being included in the build packages via ng build/serve.

### Describe the solution you'd like

A way to forcibly exclude files/folders from ng build/serve. Perhaps a "forceExclude" option in the angular.json

### Describe alternatives you've considered

I've tried every combination of paths in the tsconfig.json and tsconfig.app.json

**Comment by alan-agius4** [comment]
Hi @clabough,

- Are these packages meant to be used as global modules from the CDN?
- How are these referenced inside components?

**Comment by alan-agius4** [comment]
In this case, the best option would be to declare AmCharts as a global module and remove the the imports from your components.

types.d.ts
``` ts
import type * as amcharts5 from '@amcharts/amcharts5';
declare var am5: typeof amcharts5;
```

component.ts
```ts
am5.whateverMethod
```
