### ISSUE TITLE
How do I make angular run indefinitely on the server? With forever.

### ISSUE THREAD

**Issue by johanqnms** [angular/angular-cli#22699]
Greetings,

I have installed forever to run Angular on my AWS server. I have used the follow command:

`forever start node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --prod`

But show me an error:

```
error:   Cannot start forever
error:   script /home/ec2-user/angular01/backend-java-angular01/node_modules/@angular/cli/bin/node_modules/@angular/cli/bin/ng does not exist.

```

Do you know why forever is not working? Thanks

**Comment by alan-agius4** [comment]
Angular CLI server is meant to only be used as a local development server and should not be used on production environments.
