### ISSUE TITLE
Cannot uninstall or update angular-cli on Mac BigSur

### ISSUE THREAD

**Issue by dbnex14** [angular/angular-cli#22715]
# 🐞 Bug report

### Command (mark with an `x`)

- uninstall
- update

### Is this a regression?

NO

### Description

Cannot uninstall or upgrade angular-cli on Mac Big Sur.

## 🔬 Minimal Reproduction
**FOR UNINSTALLING**
```
sudo npm uninstall -g angular-cli
sudo npm uninstall -g @angular/cli
sudo npm cache clean --force
sudo npm cache verify --force
```
All of these commands reported no issues and appear to have executed just fine. However, if I issue ng version after issuing these commands, I still get my old versions like shown above.

**FOR UPDATING**

`sudo ng update`
, shows error as below.

-->

## 🔥 Exception or Error

The attempt to uninstall shows no error, all seam to be fine but reissuing ng version still shows old version (also tried restarting terminal and even machine but no effect).

The attempt to update angular-cli shows error:

<pre><code>
The "@angular-devkit/schematics" package cannot be resolved from the workspace root directory. This may be due to an unsupported node modules structure.
Please remove both the "node_modules" directory and the package lock file; and then reinstall.
If this does not correct the problem, please temporarily install the "@angular-devkit/schematics" package within the workspace. It can be removed once the update is complete.

</code></pre>

I am not inside any project folder so I dont understand why does it complain about node_modules directory or package.lock file.

## 🌍 Your Environment

<pre><code>
Angular CLI: 9.1.9
Node: 17.4.0
OS: darwin x64

Angular: 
... 
Ivy Workspace: 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.9
@angular-devkit/core         9.1.9
@angular-devkit/schematics   9.1.9
@schematics/angular          9.1.9
@schematics/update           0.901.9
rxjs                         6.5.4
e></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
To update the global CLI you’d need to run the below command.

```
npm install @angular/cli -g
```

`ng update` is meant to be used inside an Angular workspace.

**Comment by dbnex14** [comment]
> To update the global CLI you’d need to run the below command.
> 
> ```
> npm install @angular/cli -g
> ```
> 
> `ng update` is meant to be used inside an Angular workspace.

Yes, I did that as well.  The command executed fine with output:
```
sudo npm install @angular/cli -g
Password:

added 188 packages, and audited 189 packages in 9s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

I also run `npm fund `as suggested and had no error at all.
After this, I issued `ng version `again and got very same version that I had previously which is Angular CLI 9.1.9

**Comment by alan-agius4** [comment]
Hi @dbnex14, 

Are you running `ng version` inside or outside a workspace? It is expected that the `ng version` will return the same version if run inside a workspace since the local CLI version will be displayed.

**Comment by dbnex14** [comment]
No, I am not in any project at all as stated above in "Exception on Error" section.
