### ISSUE TITLE
Way to enable differential loading in Angular@13

### ISSUE THREAD

**Issue by xianshenglu** [angular/angular-cli#22714]
### Which @angular/* package(s) are relevant/releated to the feature request?

common, compiler-cli, compiler, core, platform-browser-dynamic, platform-browser, platform-server

### Description

Since Angular@13 drop the support of IE11 and differential loading, so do we have a way to enable differential loading for Angular@13?

### Proposed solution

```json
// tsconfig.json
{
  "angularCompilerOptions":{
     "differentialLoading": true
  }
}
```

### Alternatives considered

```json
// tsconfig.json
{
  "angularCompilerOptions":{
     "differentialLoading": true
  }
}
```

**Comment by alan-agius4** [comment]
differential loading has been removed in version 13 since IE 11 is no longer supported which makes differential loading redundant.

**Comment by xianshenglu** [comment]
> differential loading has been removed in version 13 since IE 11 is no longer supported which makes differential loading redundant.

In my case, I need to support Firefox 50 and chrome49. So, differential loading matters for my case because they don't support `script[type=module]`. So, do we have a workaround or solution?
