### ISSUE TITLE
scripts from angular.json not loading

### ISSUE THREAD

**Issue by sudhanshu-hytech** [angular/angular-cli#22711]
I am using angular 11

I have following scripts in angular.json

```
"scripts": [
              "node_modules/jquery/dist/jquery.js",
              "node_modules/admin-lte/plugins/jquery/jquery.min.js",
              "node_modules/datatables.net/js/jquery.dataTables.js",
              "node_modules/datatables.net-responsive/js/dataTables.responsive.js",
              "node_modules/datatables.net-colreorder/js/dataTables.colReorder.js",
              "node_modules/bootstrap/dist/js/bootstrap.min.js",
              "node_modules/admin-lte/plugins/bootstrap/js/bootstrap.bundle.js",
              "node_modules/admin-lte/plugins/raphael/raphael.js",
              "node_modules/admin-lte/plugins/jquery-mapael/jquery.mapael.js",
              "node_modules/admin-lte/plugins/chart.js/Chart.js",

              "node_modules/admin-lte/dist/js/adminlte.js",
              "node_modules/admin-lte/plugins/ion-rangeslider/js/ion.rangeSlider.min.js",
              "node_modules/admin-lte/plugins/bootstrap-slider/bootstrap-slider.min.js",
              "node_modules/select2/dist/js/select2.min.js",
              "node_modules/admin-lte/plugins/daterangepicker/daterangepicker.js",
              "node_modules/admin-lte/dist/js/pages/dashboard2.js",
              
              "node_modules/admin-lte/dist/js/demo.js"

            ]
```

now when I try to access $.fn.dataTable.ext.search.push(
I get the error:

core.js:6210 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ext')
TypeError: Cannot read properties of undefined (reading 'ext')
    at UserProfileComponent.<anonymous> (user-profile.component.ts:43:20)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73:42)
    at ZoneDelegate.invoke (zone-evergreen.js:372:1)
    at Object.onInvoke (core.js:28591:1)
    at ZoneDelegate.invoke (zone-evergreen.js:371:1)
    at Zone.run (zone-evergreen.js:134:1)
    at zone-evergreen.js:1276:1
    at ZoneDelegate.invokeTask (zone-evergreen.js:406:1)
    at Object.onInvokeTask (core.js:28578:1)
    at resolvePromise (zone-evergreen.js:1213:1)
    at zone-evergreen.js:1120:1
    at fulfilled (tslib.es6.js:73:85)
    at ZoneDelegate.invoke (zone-evergreen.js:372:1)
    at Object.onInvoke (core.js:28591:1)
    at ZoneDelegate.invoke (zone-evergreen.js:371:1)
    at Zone.run (zone-evergreen.js:134:1)
    at zone-evergreen.js:1276:1
    at ZoneDelegate.invokeTask (zone-evergreen.js:406:1)
    at Object.onInvokeTask (core.js:28578:1)

**Comment by alan-agius4** [comment]
Kindly follow the issue template as it is non optional. Also, please provide a minimal reproduction. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
