### ISSUE TITLE
Not respecting tsconfig location in angular-cli.json

### ISSUE THREAD

**Issue by httpdigest** [angular/angular-cli#2272]
In the angular-cli.json file in the root of my project, I changed the property "tsconfig" to `"./config/tsconfig.json"` and I have the tsconfig.json file inside config/, in order to unclutter the root directory a bit.
But when building the project, it seems that angular-cli is not respecting the new location of the tsconfig.json. I have set the "target" property to "es2015" but it still emits es5 code and prints error messages of it not finding "Promise", "Map", "MapContructor",....
However, it seems that it only _prints_ these error messages (in red) but the project still built fine.
It all works fine if I move the tsconfig.json file back to the root directory.

**Comment by httpdigest** [comment]
Sorry, nevermind. I made a mistake. The tsconfig.json file actually was under src/tsconfig.json. :(

**Comment by httpdigest** [comment]
Okay, the _actual_ issue is that when running Karma with `ng test`, and when the karma.conf.json resides in another directory other than the root directory of the project, then the Karma TypeScript compilation process will not find the tsconfig.json file anymore.

**Comment by filipesilva** [comment]
Heya @httpdigest, you can change the `karma.conf.js` location but you'll also have to change the reference to it in `angular-cli.json` (used for `ng test` to find the karma config), and also the path to `angular-cli.json` in `karma.conf.js` (used for karma to find the angular config).

**Comment by httpdigest** [comment]
Thanks for your reply. However, I did edit all reasonable places that needed editing of the paths earlier.
Please find the exact steps to reproduce the issue below:

* Starting from a clean installation of Node/npm:
* `npm install -g angular-cli`
* `ng new angular-test`
* create a new directory "conf/"
* move the karma.conf.js into conf/
* edit karma.conf.js at the following places:
  * line 15: `{ pattern: './src/test.ts', watched: false }` -> `{ pattern: '../src/test.ts', watched: false }`
  * line 18: `'./src/test.ts': ['angular-cli']` -> `'../src/test.ts': ['angular-cli']`
  * line 23: `lcovonly: './coverage/coverage.lcov'` -> `lcovonly: '../coverage/coverage.lcov'`
  * line 27: `config: './angular-cli.json',` -> `config: '../angular-cli.json',`
* edit the angular-cli.json at the following places:
  * line 37: `"config": "./karma.conf.js"` -> `"config": "./conf/karma.conf.js"`

Please reopen the issue.

**Comment by httpdigest** [comment]
**Please reopen the issue or reproducibly verify that the resolution actually works.**

**Comment by catull** [comment]
This worked for me; I am not sure it is what you want.
It works on non-Windows platforms.

`npm install -g @angular/cli`
`ng new angular-test`
`cd angular-test`
`mkdir conf`
`mv karma.conf.js conf/`
`cd conf`
`ln -s ../src ; cd ..`  # very important
edit conf/karma.conf.js `"config": './angular-cli.json',` => `"config": '../angular-cli.json',`
edit angular-cli.json `"config": "./karma.conf.js"` => `"config": "./conf/karma.conf.js"`
`ng test`

No errors, no warnings.

**Comment by filipesilva** [comment]
Closing as @catull seems to reporting the solution works.
