### ISSUE TITLE
Suggestion/request: Make Angular CLI a NX plugin - to help minimise the code maintained by Angular itself

### ISSUE THREAD

**Issue by Jordan-Hall** [angular/angular-cli#22727]
From my understanding, Google doesn't use Angular CLI. This means they are maintaining this for the good of the Angular community. With Nrwl NX starting to become standard in a lot of Angular applications. Would it now make sense to slimline Angular CLI to become a plugin built to NX/ a wrapper to NX CLI?

This could help community engagement, and you can focus on creating the generators and builders. 

If not drop would it be a worth pointing to a "community" alternative for people inside the documentation?

**Comment by mgechev** [comment]
Hey @Jordan-Hall, currently, the layering is a little different. Angular CLI provides the base functionality with its core modules - builders, schematics, etc. Nx has initially been an extension of the CLI, and it still provides a superset of the features that Angular CLI has.

Many developers extract value from the more minimalistic feature set of the CLI and other users enjoy the more complete experience Nx provides.

Given the layering and the different goals of the two tools, making an Angular CLI a plugin for Nx would be infeasible.

Additionally, Google uses the Angular CLI internally. The difference is in the build system and some custom schematics functionality to assist in the build file generation for Bazel.
