### ISSUE TITLE
Optimization breaks code

### ISSUE THREAD

**Issue by Teacup5000** [angular/angular-cli#22739]
The optimization process of Angular breaks code with side effects.

This literally wasted many dev hours of debugging to find out.

Optimization is must-have feature, otherwise the dist is 3-4 times the size. Side effects make up maybe 1% of that.

This can only be fixed by ugly workarounds, forcing to import scripts not in the intended "Angular" way.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
