### ISSUE TITLE
warning @angular-devkit/build-angular > stylus > css > source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular-cli#22748]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No
### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Install latest Angular13 app with CLI & yarn

warning @angular-devkit/build-angular > stylus > css > source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.4
Node: 14.18.2
Package Manager: yarn 1.22.17
OS: win32 x64

Angular: 13.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      10.2.4
@angular/cli                    13.2.4
@schematics/angular             13.2.4
rxjs                            7.5.4
typescript                      4.5.5

</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not actionable from our end.

please contact the authors of stylus.
