### ISSUE TITLE
Build-one, deploy-many support around base href

### ISSUE THREAD

**Issue by SeanKilleen** [angular/angular-cli#22758]
### Which @angular/* package(s) are relevant/releated to the feature request?

common

### Description

This feature request arises from the StackOverflow question here; https://stackoverflow.com/questions/71225918/how-can-i-set-the-angular-base-path-programmatically-prior-to-initialization/71226764

I have an Angular app that I am attempting to build once and deploy to multiple environments. In my case, an unfortunate client requirement is that each environment is in a folder of a CDN endpoint, e.g. `cdnendpoint.com/dev/[files]`.

This necessitates changing the baseHref for an application, which can be done at build time or as part of modifying the base tag in index.html. It looks like it can be done programmatically as well; however, my attempts to do that fail to load the built angular files themselves, e.g. main.js, because they are still hard-coded to load from the root of the endpoint.

### Proposed solution

In this case, I'm not certain there *is* a solution (but am happy to hear if I've been doing something wrong, and am submitting in case someone sees a solution where I do not). I suppose the built artifacts need to be referenced in some way from index.html and the base tag is the most reasonable way to do that.

It might be that a guide to build once, deploy many angular apps in the docs that covers things like externalizing config and things like this that might have to be done could be helpful.

### Alternatives considered

The StackOverflow in the description walks through the alternatives I've tried in detail.

Thank you for considering!

**Comment by alan-agius4** [comment]
Hi @SeanKilleen, 

I think this is quite a specific use-case that doesn't warrant to be included in `angular.json`.  Indeed changing the `base-href` would be the way to go in this case. 

I think the easiest and best option would be to modify the base-href in the HTML directly may as part of the deployment process. While this can be changed  programmatically, I feel that it will add unnecessary complexity.

Free free to comment down below, however I am closing this issue as this tracker is not suitable for support.  If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by SeanKilleen** [comment]
@alan-agius4 

My suggestion is not that this be included in `angular.json`; my suggestion is that guidance be created for build-once, deploy-many scenarios using Angular, in ways that are consistent with practices like 12Factor app development etc.

> I am closing this issue as this tracker is not suitable for support

No worries; this was not intended as a support request but as a feature for consideration. 

Given that it won't be addressed at the program level, is there a place best suited to opening up documentation suggestions? I'm willing to contribute PRs around it, but supporting information for build-once deploy-many approaches in the docs would be great.
