### ISSUE TITLE
import HttpModule, FormModule and ReactiveFormModule by default

### ISSUE THREAD

**Issue by elycheikhsmail** [angular/angular-cli#22753]
- [ ] new
- [ ] build
- [ ] generate
 

### Description
in most of web project we need to make http request and extract data from forms to send it via http request, instead of spending time to import those module why not import them by default in app.module or new angular app generated
 
### Describe the solution  
import  FormModule and ReactiveFormModule by default in app.module.ts and any angular created
if dev not need them there are 2 possibility
- ng build command remove unusued modules via tree shakin
-  or dev simply delete them delete is more easier than write

**Comment by alan-agius4** [comment]
Hi @elycheikhsmail, 

Thanks for this request.

In general we should keep the new application to the bare minium and avoid adding things that users might require to remove. 

Typically it's easier to add 2 imports over removing them as one can easily forget them. In additional to this, amending the `ng new` template can cause certain courses and training material.
