### ISSUE TITLE
Bug: ng serve failed to run on Angular 13 project because of UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by harounchebbi** [angular/angular-cli#22752]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, this bug was not present in previous versions, I need to manually install required Typescript version each time I initialize a new project with this specific Angular version. 

### Description

After initializing a new angular project, I proceed by running ng serve which unexpectedly failed because the Angular Compiler requires TypeScript >=4.4.2 and <4.5.0 but 4.5.5 was found instead.

## 🔬 Minimal Reproduction

```
ng new my-application
cd my-application
ng serve 
```

## 🔥 Exception or Error

![Capture](https://user-images.githubusercontent.com/24281282/155314758-ccba6b18-a146-42cc-a6d1-48be8308ffca.PNG)

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.1.4
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 13.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@schematics/angular             13.1.4
rxjs                            7.4.0
typescript                      4.5.5

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Please update to the most recent version to resolve the problem.

**Comment by maxima120** [comment]
I have latest cli and core but have similar error:
`(node:25928) UnhandledPromiseRejectionWarning: Error: The Angular Compiler requires TypeScript >=4.4.2 and <4.6.0 but 4.6.2 was found instead.`

versions:
```
Angular CLI: 13.2.5
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 13.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            8.3.29
@angular-devkit/schematics      8.3.29
@angular/cli                    13.2.5
@schematics/angular             12.2.16
rxjs                            7.5.4
typescript                      4.6.2
```
