### ISSUE TITLE
ng-deno cli experimental

### ISSUE THREAD

**Issue by elycheikhsmail** [angular/angular-cli#22754]
I hope ng cli be write ts-deno-first, the finale user don't care about it was writen but this make ng cli dev and maintenace more easier I think but sure this will in progressif way.

**Comment by alan-agius4** [comment]
Hi @elycheikhsmail,

Thanks for this feature request. 

Without significant user interest we believe that supporting Deno isn’t the best use of our resources. One thing to also take into consideration is that a large number of our dependencies are still in CJS which make supporting Deno more challenging. Also there will be definitely some overheads to support both Node.JS and Deno.

We definitely want to explore with Deno in the future but realistically this is not something immediate in our roadmap.

**Comment by elycheikhsmail** [comment]
Thank you @alan-agius4 
I'm agree with you and will close this
