### ISSUE TITLE
Serving through Express doesn't "live reload"

### ISSUE THREAD

**Issue by rkorebrits** [angular/angular-cli#22757]
### Is this a regression?

Yes

### Description

We have upgraded from Angular `12` to Angular `13.2.2` and are seeing some unwanted behaviour;

We use an Express server to proxy to our Angular projects, e.g.
* Angular project `a` on port `4300`
* Angular project `b` on port `4400`

Express routes traffic from:
`localhost:9000/a` -> `localhost:4300`
`localhost:9000/b` -> `localhost:4400`

Since the upgrade today, we are not experiencing live reloading of our Angular projects anymore.

Furthermore, when we `ctrl-C` when serving, we get the following error (with `node --trace-warnings`):

```
(node:18181) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Server]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:475:17)
    at Server.addListener (events.js:497:10)
    at Server.once (events.js:541:8)
    at Server.close (net.js:1627:12)
    at /Users/rkorebrits/workspace/core/web/upgrade/node_modules/webpack-dev-server/lib/Server.js:3301:25
    at new Promise (<anonymous>)
    at Server.stop (/Users/rkorebrits/workspace/core/web/upgrade/node_modules/webpack-dev-server/lib/Server.js:3299:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Any ideas why this may be happening?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.3
Node: 14.19.0
Package Manager: npm 6.14.16
OS: darwin arm64

Angular: 13.2.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1302.3
@angular-devkit/build-angular    13.2.3
@angular-devkit/core             13.2.1
@angular-devkit/schematics       13.2.3
@angular-devkit/schematics-cli   13.2.3
@angular/cli                     13.2.3
@angular/fire                    7.2.1
@angular/flex-layout             13.0.0-beta.38
@nguniversal/builders            13.0.2
@nguniversal/express-engine      13.0.2
@schematics/angular              13.2.3
ng-packagr                       13.2.1
rxjs                             6.6.7
typescript                       4.5.5
```

### Anything else?

I tried downgrading to `13.0.1` but same issue there

**Comment by alan-agius4** [comment]
Hi @rkorebrits, 

Without a reproduction it's hard to tell what is happening. One noticeable change however in v13 is that websockets are used to trigger live-reload, so make sure that your proxy can handle WS correctly.

**Comment by alan-agius4** [comment]
> Thanks @alan-agius4, how could I provide reproduction steps for this? Could I provide a ZIP file with a simple setup?

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by rkorebrits** [comment]
Thanks, that was very useful! We just had to add `ws: true` for it to work.

```js
  app.use(
    rewriteRootBase,
    createProxyMiddleware({
      target: `http://localhost:${port}/${rootPath}`,
      pathRewrite: { [`^${rewriteRootBase}`]: '' },
      ws: true,
    }),
  );
```

Hopefully someone else finds this useful
