### ISSUE TITLE
Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires "~4.2.3 || ~4.3.2", would install "4.5.5").

### ISSUE THREAD

**Issue by weirdyang** [angular/angular-cli#22763]
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [X ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I'm trying to upgrade my project from angular 12 to 13.

using the cmd provided from [here](https://update.angular.io/?v=12.0-13.0):

`npx @angular/cli@13 update @angular/core@13 @angular/cli@13`

## 🔬 Minimal Reproduction

run: 

`npx @angular/cli@13 update @angular/core@13 @angular/cli@13`

## 🔥 Exception or Error
<pre><code>
D:\personal\angular\bulma-angular>npx @angular/cli@13 update @angular/core@13 @angular/cli@13
Using package manager: 'npm'
Collecting installed dependencies...
Found 38 dependencies.
Fetching dependency metadata from registry...
Package '@angular/cli' is already up to date.
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires "~4.2.3 || ~4.3.2", would install "4.5.5").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\ads\AppData\Local\Temp\ng-5qeRWy\angular-errors.log" for further details.

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.5
Node: 14.15.4
Package Manager: npm 8.3.0
OS: win32 x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      13.2.5
@angular/cdk                    12.2.13
@angular/cdk-experimental       12.2.13
@angular/cli                    13.2.5
@schematics/angular             13.2.5
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Anything else relevant?**

**Comment by weirdyang** [comment]
If i run the commands separeately, I notice it's trying to install `14.0.0-next.3` instead

```
ng update @angular/cdk
Using package manager: 'npm'
Collecting installed dependencies...
Found 38 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/compiler-cli" (requires "^12.0.0 || ^12.1.0-next" (extended), would install "14.0.0-next.3").
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "typescript" (requires "~4.2.3 || ~4.3.2", would install "4.5.5").
                  Package "@angular/cdk-experimental" has an incompatible peer dependency to "@angular/cdk" (requires "12.2.13", would install "13.2.4").
                  Package "@fortawesome/angular-fontawesome" has an incompatible peer dependency to "@angular/core" (requires "^12.0.0" (extended), would install "14.0.0-next.3").× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "C:\Users\ads\AppData\Local\Temp\ng-mcuH34\angular-errors.log" for further details.
```

**Comment by alan-agius4** [comment]
Can you please share your package.json?

**Comment by weirdyang** [comment]
Hi,
I’ve resolved by first deleting node modules folder and lock file. Then updated local typescript, and finally reinstalled the packages then ran the update commands with the force flag.
