### ISSUE TITLE
@angular-devkit/schematics glossary is missing Task

### ISSUE THREAD

**Issue by samherrmann** [angular/angular-cli#22764]
The [Schematics Glossary](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/schematics#glossary) doesn't introduce what a `Task` is, making it difficult for new schematic developers to know what `Task`s should be used for and how they work.

The _Schematics for libraries_ page on angular.io [demonstrates an example for adding a task](https://angular.io/guide/schematics-for-libraries#providing-installation-support), but it also doesn't provide an explanation on what a `Task` is. When do they run (before/after the `Tree` has been transformed by `Rule`s)? Do they run in parallel? How do you manage `Task` dependencies?

This issue is to document `Task` in the Schematics Glossary table so that it's easier for developers to create their own `Task`s.

**Comment by AnjaliJha1221** [comment]
Hey, I would like to work on this issue, please guide me further on how to get started, as I am a total beginner.

**Comment by alan-agius4** [comment]
@AnjaliJha1221, you can start by going through our [contributing docs](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit). Let me know if you have any specific questions.

**Comment by adyngom** [comment]
hello @alan-agius4 looking at the contributing docs I'm not clear if you would assign the issue to yourself first before the submitting the PR or should one just start work on it and submit the PR when done

**Comment by alan-agius4** [comment]
@adyngom, you can just submit a PR.

**Comment by khushbubijawat** [comment]
Hey, I would like to work on this issue.

**Comment by m0-dev** [comment]
Hey @alan-agius4 I would like to contribute on this issue.

**Comment by hojjat-afsharan** [comment]
any updates on this issue?

**Comment by ArthurDibe** [comment]
Please let me know if I'm missing anything for the PR. Thanks in advance 😊
