### ISSUE TITLE
Optimized bundles contain \u0275 instead of ɵ

### ISSUE THREAD

**Issue by jbjhjm** [angular/angular-cli#22768]
I'm not sure if this is a regression or if concept was changed without mentioning it.

Last year there was a bug report about this topic: https://github.com/angular/angular-cli/issues/20255

Seeing the assigned tags and comments it looks like it was acknowledged.
But then the PR was closed without merging, without any explanation unfortunately.

Does that mean the \u0275 in (all es version) chunks is now official behavior? 
Or is this a regression and cli should create utf-8 based files with ɵ char?

**Comment by alan-agius4** [comment]
This is the expected behaviour. 

The main reason for this is that from conversations we had with the Chrome team it was recommend to use ASCII whenever possible as V8 parses and optimises it more efficiently. 

There is also a blog post about this https://v8.dev/blog/scanner
