### ISSUE TITLE
[@angular-devkit/build-angular] Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#22776]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

yes

### Description

when I build the server bundle using webpack it built but when serving the app I get
```
const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf( /*#__PURE__*/_wrapAsyncGenerator(function* () {})).prototype);
                                      ^

TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at Object.29221 (dist/server/main.js:347854:39)
    at __webpack_require__ (dist/server/main.js:639891:42)
    at Object.84167 (dist/server/main.js:345159:15)
    at __webpack_require__ (dist/server/main.js:639891:42)
    at Object.43806 (dist/server/main.js:348026:13)
    at __webpack_require__ (dist/server/main.js:639891:42)
    at Object.54832 (dist/server/main.js:344847:34)
    at __webpack_require__ (dist/server/main.js:639891:42)
    at Object.95254 (dist/server/main.js:343700:22)
```

I used custom-webpack to see the default webpack config by angular it self
replacing this loader with `ts-loader` it serves (but this will introduce other issues with angular linker)

## 🔬 Minimal Reproduction

I managed to create a minimal reproduction today and will be published [here](https://github.com/eng-dibo/issue-ng-build-server)

## 🌍 Your Environment

Angular CLI: 13.2.5
Node: 16.14.0
Package Manager: npm 8.3.1
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1301.3
@angular-devkit/core         13.1.3
@angular-devkit/schematics   13.2.5
@schematics/angular          13.2.5
typescript                   4.5.5
webpack                      5.69.1

**Comment by alan-agius4** [comment]
Hi @eng-dibo, the provided reproduction is empty. Did you forget to push?

**Comment by eng-dibo** [comment]
> the provided reproduction is empty

Thank you for donating your time, I'm trying to reduce my codebase as much as possible to point out what exactly causes this issue. when I finish the minimal reproduction I will mention you again.

temporarily I created [a branch](https://github.com/eng-dibo/dibo/tree/issue-ng-serve) to help you try out and understand the issue, but surely it needs to be minimized to easily get investigated. just take a look at README.md of this branch and run `npm start`

**Comment by alan-agius4** [comment]
I tried to take a look at the reproduction, but I got a number of TypeScript errors.

I’ll therefore wait for a minimal reproduction.

**Comment by eng-dibo** [comment]
the ts errors came from a conflict between dependencies.
for example @angular-devkit/* packages requires rxjs@6.6.7, and @angular/* packages accepts @rxjs@7.4.0. installing the dependencies puts rxjs@6.6.7 in the root node_modules and rxjs@7.4.0 inside each @angular/* package.

forcing installing rxjs@6.6.7 in the root node_modules and rxjs@7.4.0 under each @angula-/devkit package solving most of these errors.

it seems there was problems with some dependencies caused this issue, not the Angular builder directly. I solved the issue and the previously mentioned issue with dependencies and now the project could be served.

unfortunately, I couldn't mentain a minimal reproduction to help other people to understand the issue.
