### ISSUE TITLE
On Upgrading to Angular 10.2.4, The Variables added in typings.d.ts are being unable to be Referenced in the Component / Service files

### ISSUE THREAD

**Issue by sshanmu91** [angular/angular-cli#22773]
In Angular v10 & TypeScript v4.0.8

Application is build using "ng build --aot"

Getting the Following Error

![image](https://user-images.githubusercontent.com/36123879/155718643-e18d14a1-eb1a-4167-af22-66a6a05687bd.png)

In Service / Component :-

![image](https://user-images.githubusercontent.com/36123879/155718904-1b7f07ae-9b40-41d8-8d2f-8b660a973f53.png)

typings.d.ts :-

![image](https://user-images.githubusercontent.com/36123879/155719050-e7e13f7d-6659-4416-8031-65965bffe705.png)

package.json :-

![image](https://user-images.githubusercontent.com/36123879/155718318-535acf5a-077e-4995-ae5e-0f51c635fc61.png)

![image](https://user-images.githubusercontent.com/36123879/155718488-d6acb90d-f017-40e1-9350-872ad6f12eb4.png)

Attempted all the Below things. But of no luck.

tsconfig.json :-

![image](https://user-images.githubusercontent.com/36123879/155719123-1fbaa11d-1df1-4485-82c9-ea174351e239.png)

tsconfig.app.json :-

![image](https://user-images.githubusercontent.com/36123879/155719201-8d28f8bf-f361-49e2-9172-28c837f35ef1.png)

tsconfig.spec.json :-

![image](https://user-images.githubusercontent.com/36123879/155719288-5f7918f5-7465-4f6e-9f02-70deaed90c3e.png)

Please help on how to resolve this issue and to successfully access the Variables added in typings.d.ts

**Comment by sshanmu91** [comment]
tsconfig.json is present in the Application Folder - Client/

tsconfig.app.json & tsconfig.spec.json are present inside the src folder - Client/src/

Services & Components are added inside the app folder - Client/src/app

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
