### ISSUE TITLE
Angular 13 - ng build-watch inifinity loop

### ISSUE THREAD

**Issue by nathan30** [angular/angular-cli#22772]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11
### Description

 A clear and concise description of the problem...
I updated my project from Angular 11 to Angular 13
From now on, when I run a `ng build --watch` the command runs in an infinite loop

## 🔬 Minimal Reproduction

Here is my package.json : 

```{
    "name": "open-capture-for-invoices",
    "version": "2.1.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build-watch": "ng build --watch",
        "build:prod": "NODE_ENV=production ng build --configuration production",
        "reload-packages": "rm -Rf node_modules && rm package-lock.json && npm cache clean --force && npm i --force",
        "extract-translations": "ngx-translate-extract --input ./ --output ./src/assets/i18n/frontend/*.json --clean --sort --format namespaced-json --marker _"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~13.2.4",
        "@angular/cdk": "^13.2.4",
        "@angular/common": "~13.2.4",
        "@angular/compiler": "~13.2.4",
        "@angular/core": "~13.2.4",
        "@angular/forms": "~13.2.4",
        "@angular/material": "^13.2.4",
        "@angular/material-moment-adapter": "^13.2.4",
        "@angular/platform-browser": "~13.2.4",
        "@angular/platform-browser-dynamic": "~13.2.4",
        "@angular/router": "~13.2.4",
        "@biesbjerg/ngx-translate-extract-marker": "^1.0.0",
        "@fortawesome/fontawesome-free": "^6.0.0",
        "@ngx-translate/core": "^14.0.0",
        "@ngx-translate/http-loader": "^7.0.0",
        "@schematics/angular": "^13.2.5",
        "@swimlane/ngx-charts": "20.0.1",
        "@syncfusion/ej2": "^19.4.53",
        "jquery": "^3.6.0",
        "moment": "^2.29.1",
        "ng-click-outside": "^9.0.1",
        "ng-sortgrid": "^5.3.0",
        "ng2-datepicker": "^12.0.0",
        "ngx-file-drag-drop": "^5.1.3",
        "ngx-mat-select-search": "^4.0.2",
        "remove-accents": "^0.4.2",
        "rxjs": "~7.5.4"
    },
    "devDependencies": {
        "@angular-builders/custom-webpack": "^13.1.0",
        "@angular-devkit/build-angular": "^13.2.5",
        "@angular/cli": "~13.2.5",
        "@angular/compiler-cli": "~13.2.4",
        "@biesbjerg/ngx-translate-extract": "^7.0.4",
        "@types/d3-scale": "^4.0.2",
        "@types/d3-selection": "^3.0.2",
        "@types/node": "^17.0.21",
        "autoprefixer": "^10.4.2",
        "postcss": "^8.4.7",
        "tailwindcss": "^3.0.23",
        "ts-node": "^10.3.1",
        "tslint": "~6.1.3",
        "typescript": "~4.5.5",
        "zone.js": "~0.11.4"
    }
}
```

## 🔥 Exception or Error

<pre><code>
/usr/bin/npm run build-watch --scripts-prepend-node-path=auto

> open-capture-for-invoices@2.1.0 build-watch /var/www/html/opencaptureforinvoices
> ng build  --watch

⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
- @biesbjerg/ngx-translate-extract-marker [es2015/esm2015] (git+https://github.com/biesbjerg/ngx-translate-extract-marker.git)
- ng-sortgrid [es2015/esm2015] (git+https://github.com/kreuzerk/ng-sortgrid.git)
Encourage the library authors to publish an Ivy distribution.
✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files | Names         |  Raw Size | Estimated Transfer Size
main.js             | main          |   2.38 MB |               387.54 kB
styles.css          | styles        | 193.14 kB |                26.85 kB
scripts.js          | scripts       |  98.08 kB |                31.26 kB
polyfills.js        | polyfills     |  36.25 kB |                11.54 kB
runtime.js          | runtime       |   1.75 kB |               897 bytes

                    | Initial Total |   2.70 MB |               458.06 kB

Build at: 2022-02-25T10:26:46.590Z - Hash: fe49d0ef9ef41c8f - Time: 278344ms

Warning: /var/www/html/opencaptureforinvoices/node_modules/@swimlane/ngx-charts/fesm2015/swimlane-ngx-charts.mjs depends on 'clone-deep'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files | Names | Raw Size | Estimated Transfer Size
main.js             | main  |  2.38 MB |               387.50 kB

4 unchanged chunks

Build at: 2022-02-25T10:27:56.686Z - Hash: f8c2fee1caa5580f - Time: 82609ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

Initial Chunk Files | Names | Raw Size | Estimated Transfer Size
main.js             | main  |  2.38 MB |               387.18 kB

4 unchanged chunks

Build at: 2022-02-25T10:28:48.990Z - Hash: 0676e9987a5e28b7 - Time: 54989ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

5 unchanged chunks

Build at: 2022-02-25T10:29:02.132Z - Hash: 0676e9987a5e28b7 - Time: 12987ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

5 unchanged chunks

Build at: 2022-02-25T10:29:12.450Z - Hash: 0676e9987a5e28b7 - Time: 10184ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

5 unchanged chunks

Build at: 2022-02-25T10:29:22.540Z - Hash: 0676e9987a5e28b7 - Time: 9973ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

5 unchanged chunks

Build at: 2022-02-25T10:29:33.921Z - Hash: 0676e9987a5e28b7 - Time: 11259ms
✔ Browser application bundle generation complete.
✔ Index html generation complete.

5 unchanged chunks
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.5
Node: 14.19.0
Package Manager: npm 6.14.16
OS: linux x64

Angular: 13.2.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5

</code></pre>

**Anything else relevant?**

**Comment by nathan30** [comment]
Try with updated node and npm, the issue is still present

**Comment by alan-agius4** [comment]
I noticed that you are using `@angular-builders/custom-webpack` can you remove it’s usage and use the official builders and see it the problem persists?

If the problem persists please setup a minimal repro please.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by nathan30** [comment]
Hi @alan-agius4 

Thanks for you quick answer. I tried to made a repro-app, using the same package.json, angular.json etc.. but could reproduce the problem in a smaller app..

Could you check my project, I made a branch with my Angular 13 test ?

https://github.com/edissyum/opencaptureforinvoices/tree/repro_oc_angular_v13

Thanks in advance

**Comment by alan-agius4** [comment]
The issue appears to be caused by misconfiguration of tailwind css. This is causing the root directory to be added as a dependency.

This also causes redundant files and directory traversals which does cause the builds to be significantly slower.

```diff
content: [
-   '**/*.{html,ts}'
+   'src/frontend/**/*.{html,ts}'
],
```
