### ISSUE TITLE
ng serve & ng build not working after build a new project with ng new

### ISSUE THREAD

**Issue by ZoeChan2013** [angular/angular-cli#2277]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
   Mac OSX Yosemite

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
   angular-cli: 1.0.0-beta.14
   node: 5.11.1
   os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   `ng new angular2-demo`
   `cd angular2-demo`
   `ng serve`

4. The log given by the failure. Normally this include a stack trace and some
   more information.
    Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         options: {
           tslint: ...
         }
       })
     }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node['fs'] should be one of these:
   false | true | "mock"
 - configuration.node['crypto'] should be one of these:
   false | true | "mock"
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         options: {
           tslint: ...
         }
       })
     }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node['fs'] should be one of these:
   false | true | "mock"
 - configuration.node['crypto'] should be one of these:
   false | true | "mock"
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/shuyi_chen/github/angular2-demo/node_modules/webpack/lib/webpack.js:16:9)
    at Class.exports.default.Task.extend.run (/Users/shuyi_chen/github/angular2-demo/node_modules/angular-cli/tasks/serve-webpack.js:23:27)
    at /Users/shuyi_chen/github/angular2-demo/node_modules/angular-cli/commands/serve.js:84:26
    at tryCatch (/Users/shuyi_chen/github/angular2-demo/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:195:12)
    at invokeCallback (/Users/shuyi_chen/github/angular2-demo/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:210:13)
    at publish (/Users/shuyi_chen/github/angular2-demo/node_modules/es6-promise/dist/lib/es6-promise/-internal.js:178:7)
    at flush (/Users/shuyi_chen/github/angular2-demo/node_modules/es6-promise/dist/lib/es6-promise/asap.js:94:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

5. Mention any other details that might be useful.
    I use `ng new` create a project last week, all `ng` commands are still working for that project. I didn't update angular-cli after I create the old project. But today after use `ng new` to build a project, `ng server` &  `ng build` suddenly cannot work and throws error.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by petebacondarwin** [comment]
See  #2234

This should be fixed by upgrading to beta.15 and then completely reinstalling node_modules in your project

**Comment by JanStureNielsen** [comment]
And check SO: http://stackoverflow.com/questions/39600939/invalid-configuration-object-webpack-has-been-initialised-using-a-configuration/39601224#39601224
