### ISSUE TITLE
dependencies are not compatible

### ISSUE THREAD

**Issue by eng-dibo** [angular/angular-cli#22781]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

not sure

### Description

this is not actually an error but it introduces an issue when installing angular

`@angular-devkit/*` and `@angular/*` packages have different versions of dependencies that have breaking changes between them.

for example [@angular-devkit/core](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/package.json#L15) -> rxjs@6.6.7
and [@angular/core](https://github.com/angular/angular/blob/master/packages/core/package.json#L19) -> rxjs@^6.5.3 || ^7.4.0

in my root package.json , I use rxjs@^7.4.0 as a dependency, which is compatible with Angular
but when I run `npm install` the version 6.6.7 is installed in my root node_module dir because it is required by @angular-devkit/core. (even if my package.json requires v^7.4.0)

this makes the following line typely wrong if used inside an angular project (probably you may need to use a function or extend a class that uses rxjs.Observable from v7.4.0, but your root node_modules has rxjs v6.6.7)
```
import { Observable} from 'rxjs';
```

Observable from both versions (i.e 6.6.7 and 7.4.0) are not compatible because there are many [breaking changes](https://rxjs.dev/6-to-7-change-summary) between those versions, for example, `_isScalar` is removed from Observable at v7.0.0

> the property _isScalar is missing in Observable

this specially happens in monorepos, where the angular project is a workspace inside that monorepo and there is another workspace that extends its functionality.
in this case, the package managers may choose to install rxjs@6.6.7 in the root dir, and rxjs@7.4.0 inside the package's node_module dir.

**my suggestion** is to update dependencies in @angular-devkit packages to remove that breaking changes between rxjs versions

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
The RxJs version of the application and devkit packages and other node packages have different contexts and are not guaranteed to be always in sync.

The devkit packages also get synced inside of Google which is still dependent on RxJs 6.  While we are looking in updating to RxJs 7, this is not a trivial change due to large set of breaking changes.

> in this case, the package managers may choose to install rxjs@6.6.7 in the root dir, and rxjs@7.4.0 inside the package's node_module dir.

This is expected and correct behaviour from package manages. You may need to configure TypeScript path mappings to favour the resolution at package level.
 
Note: this isn’t a problem if you use the Angular CLI to manage your workspace.
