### ISSUE TITLE
Cannot find module 'ajv-formats' (angular update from 13.2.1 to 13..4)

### ISSUE THREAD

**Issue by eran10** [angular/angular-cli#22780]
Hi,
Our angular 13.2.1 works as expected. but after we update to angular 13.2.4 it seems that `ng build` broke and didn't pass due to error message :
"Cannot find module 'ajv-formats'"

here is the full error message:

$ cross-env NODE_ENV=production ng build
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'ajv-formats'
Require stack:
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\json\schema\registry.js
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\json\schema\index.js
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\json\index.js
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\experimental\jobs\simple-registry.js
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\experimental\jobs\index.js
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\experimental.js- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\index.js
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\utilities\config.js
- C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\lib\init.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\test\WebstormProjects\test-project\node_modules\@angular\cli\node_modules\@angular-devkit\core\src\json\schema\registry.js:34:39)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\node_modules\\@angular-devkit\\core\\src\\json\\schema\\registry.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\node_modules\\@angular-devkit\\core\\src\\json\\schema\\index.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\node_modules\\@angular-devkit\\core\\src\\json\\index.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\node_modules\\@angular-devkit\\core\\src\\experimental\\jobs\\simple-registry.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\node_modules\\@angular-devkit\\core\\src\\experimental\\jobs\\index.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\node_modules\\@angular-devkit\\core\\src\\experimental.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\node_modules\\@angular-devkit\\core\\src\\index.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\utilities\\config.js',
    'C:\\Users\\test\\WebstormProjects\\test-project\\node_modules\\@angular\\cli\\lib\\init.js'
  ]
}

has anyone faced that? we didn't change anything in the code and in 13.22.1 it works, am I missing something?

**Comment by alan-agius4** [comment]
Can you please try to delete the node_modules and lock files and do a fresh installation?

```
rm -rf node_modules package-lock.json
npm install
```

**Comment by eran10** [comment]
@alan-agius4 seems to work now, thank you!
