### ISSUE TITLE
5 rules skipped due to selector errors - when @import bootstrap.min.css in style.css

### ISSUE THREAD

**Issue by ChipClark** [angular/angular-cli#22797]
Similar to issue: https://github.com/angular/angular-cli/issues/20906 - but solution listed does not resolve this issue. 

# 🐞 Bug report

### Command (mark with an `x`)

- [ ] serve

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 11

### Description

Migrated application from Angular 11 to Angular 12. 
After running ```ng serve --port 3600``` getting console error: {message: '5 rules skipped due to selector errors:\n  0% -> Un…tched selector: %\n  100% -> Unmatched selector: %'}

If I remove:
@import "../node_modules/bootstrap/dist/css/bootstrap.min.css"; 
from style.css - the error does not appear. 
Obviously, I need to include this for style reasons. 

According to: https://github.com/angular/angular-cli/issues/20906
"The root cause seems to be a bug in [Critters](https://github.com/GoogleChromeLabs/critters) which doesn't handle properly the @import."  

However, as this is a local file, I cannot change this line to the index.html file: 

## 🔬 Minimal Reproduction

https://github.com/ChipClark/5-rules-skipped-errors.git 

## 🔥 Exception or Error

5 rules skipped due to selector errors

## 🌍 Your Environment

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1202.16
@angular-devkit/build-angular     12.2.16
@angular-devkit/build-optimizer   0.1202.16
@angular-devkit/build-webpack     0.1202.16
@angular-devkit/core              12.2.16
@angular-devkit/schematics        12.2.16
@angular/cdk                      12.2.13
@angular/material                 12.2.13
@ngtools/webpack                  12.2.16
@schematics/angular               12.2.16
@schematics/update                0.1102.18
rxjs                              6.6.3
typescript                        4.3.5
webpack                           5.70.0

ng-bootstrap/ng-bootstrap      9.1.3
bootstrap                                   5.1.3
ngx-bootstrap                            7.1.2

**Anything else relevant?**

Only tested with Chrome Version 98.0.4758.102

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by ChipClark** [comment]
I don't understand how this is fixed in a more recent release. 

I am running Angular/cli 12.2.16 - which is the latest v12.   IF what you're saying is upgrade to v13, that isn't an acceptable solution.    This was not an issue in v11.   

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1202.16
@angular-devkit/build-angular     12.2.16
@angular-devkit/build-optimizer   0.1202.16
@angular-devkit/build-webpack     0.1202.16
@angular-devkit/core              12.2.16
@angular-devkit/schematics        12.2.16
@angular/cdk                      12.2.13
@angular/http                     7.2.16
@angular/material                 12.2.13
@ngtools/webpack                  12.2.16
@schematics/angular               12.2.16
@schematics/update                0.1102.18
rxjs                              6.6.3
typescript                        4.3.5
webpack                           5.69.1

**Comment by alan-agius4** [comment]
Version 12 is currently in LTS and only security patches are applied. To avail of the latest fixes and features you need to update to the latest stable version, which is currently 13.2.6.

Please read more about our LTS policy here: https://angular.io/guide/releases#lts-fixes
