### ISSUE TITLE
Styles, `@import`'ed in `styles.scss` are not tree-shaked.

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular-cli#22809]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No sure

### Description

Any SCSS styles imported with @import remains in styles.css for production build with styles optimization

## 🔬 Minimal Reproduction
https://github.com/Lonli-Lokli/scss-ts

- Clone
- run ng build --prod

Expected - no ngx-toastr styles as we have styles optimization turned on
Current - all styles are presented
## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.5
Node: 14.18.2
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.2.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5
</code></pre>

**Comment by Lonli-Lokli** [comment]
Are you sure? Here is my repro
https://github.com/Lonli-Lokli/webpack-styles-ts/blob/master/config/webpack.config.common.js#L28

Clone/npm i/npm run build

Produces result in build folder will be different based on this `sideEffects` flag.

**Comment by Lonli-Lokli** [comment]
I just give an example of what webpack supports, my original sample was without it, 9nly pure @imports.

So if you think it's completely different way of how AngularCLIl handles this, can you share please ways how not required styles can be excluded, which you mentioned in your first response?

And can I convert this issue into feature Request?

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by Lonli-Lokli** [comment]
@alan-agius4 I have tried approach with PurgeCSS and now I understand your concern regarding enabling this as a part of build and completely agree with linting proposal.
