### ISSUE TITLE
FEATURE: Load third party css/javascript as external file

### ISSUE THREAD

**Issue by kchojhu** [angular/angular-cli#2280]
This is just a suggestion to have an option to include third party css/javascript to load as external link when I have below configuration

```
"styles": [
  "styles.css",
  "../node_modules/bootstrap/dist/css/bootstrap.css"
],
```

The main reason is that when I want to edit the style through debugger tools like firefox's tool "Style Editor", it only works when it's loaded externally.  If it's loaded as internally then it won't work since it only recognizes external file.

**Comment by leonardobazico** [comment]
+1

**Comment by arciisine** [comment]
I'm running into the same issue when attempting to use the https://ace.c9.io/.  It has it's own module system and requires the entire dist folder to be accessible at runtime.  Apart from manual intervention, I was hoping to be able to map a node_modules/&lt;package&gt;/&lt;subfolder&gt; to a path in assets/.  I realize a symlink could potentially handle this (though I did have some issue with symlinks and being picked up by the watcher), but that feels brittle to rely on git hooks to try to enforce some of this.

**Comment by filipesilva** [comment]
There isn't a reasonable way to allow both loading those files locally and externally. You can instead add script/style tags to index.html with the external links though.

**Comment by filipesilva** [comment]
Also related https://github.com/angular/angular-cli/issues/1310, it's roughly the same request (CDN support).
