### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'hooks') …/node_modules/@angular-devkit/build-angular/src/webpack/plugins/karma/karma.js:150

### ISSUE THREAD

**Issue by DerZyklop** [angular/angular-cli#22811]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I guess. I never saw it before.

### Description

Running `ng test` gives Error.

## 🔬 Minimal Reproduction

Run `ng test`. 
Not sure if this is enaugh. The app of my company is quite complex. If it needs more info, I will dig into it. 

## 🔥 Exception or Error

<pre>
DATETIME:ERROR [karma-server]: Server start failed on port 9876: 
TypeError: Cannot read properties of null (reading 'hooks') …/node_modules/@angular-devkit/build-angular/src/webpack/plugins/karma/karma.js:150
</pre>

## 🌍 Your Environment

<pre><code>Angular CLI: 12.2.11
Node: 16.13.2 (Unsupported)
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 12.2.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   12.2.11
@angular-devkit/core            12.2.11
@angular-devkit/schematics      12.2.11
@angular/fire                   6.1.5
@schematics/angular             12.2.11
rxjs                            6.6.7
typescript                      4.2.4
webpack                         5.61.0
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you try to update to the most recent version of Angular and see if it resolves the problem?

If the problem persists in your application after upgrading, please provide a simple repository reproducing the problem. You can use `ng new repro-app` to create a new project where you reproduce the problem.
