### ISSUE TITLE
main bundle size in MBs

### ISSUE THREAD

**Issue by a5hik** [angular/angular-cli#2281]
`angular-cli: 1.0.0-beta.14
node: 6.2.1
os: darwin x64`

I noticed that my app generates the main bundle in MBs .. here is my `package.json` dependencies entries.

`"dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "@angular2-material/button": "^2.0.0-alpha.8-1",
    "@angular2-material/button-toggle": "^2.0.0-alpha.8-1",
    "@angular2-material/card": "^2.0.0-alpha.8-1",
    "@angular2-material/checkbox": "^2.0.0-alpha.8-1",
    "@angular2-material/core": "^2.0.0-alpha.8-1",
    "@angular2-material/grid-list": "^2.0.0-alpha.8-1",
    "@angular2-material/icon": "^2.0.0-alpha.8-1",
    "@angular2-material/input": "^2.0.0-alpha.8-1",
    "@angular2-material/list": "^2.0.0-alpha.8-1",
    "@angular2-material/menu": "^2.0.0-alpha.8-1",
    "@angular2-material/progress-bar": "^2.0.0-alpha.8-1",
    "@angular2-material/progress-circle": "^2.0.0-alpha.8-1",
    "@angular2-material/radio": "^2.0.0-alpha.8-1",
    "@angular2-material/sidenav": "^2.0.0-alpha.8-1",
    "@angular2-material/slide-toggle": "^2.0.0-alpha.8-1",
    "@angular2-material/slider": "^2.0.0-alpha.8-1",
    "@angular2-material/tabs": "^2.0.0-alpha.8-1",
    "@angular2-material/toolbar": "^2.0.0-alpha.8-1",
    "@angular2-material/tooltip": "^2.0.0-alpha.8-1",
    "bootstrap": "^4.0.0-alpha.2",
    "c3": "^0.4.11",
    "clipboard": "^1.5.12",
    "core-js": "^2.4.1",
    "font-awesome": "^4.6.3",
    "hammerjs": "^2.0.8",
    "hover.css": "^2.0.2",
    "lodash": "^4.15.0",
    "ng2-accordion": "0.0.9",
    "ng2-bootstrap": "1.1.5",
    "ng2-file-upload": "^1.0.3",
    "ng2-slim-loading-bar": "^1.5.1",
    "randomcolor": "^0.4.4",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.12",
    "simplemde": "^1.11.2",
    "sortablejs": "^1.4.2",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  }`

The main.bundle.js size is 2.5 MB in Prod mode and it was 6.7 MB in Dev mode. I feel its huge and any clues to reduce the size would be much appreciated.

**Comment by ng-darren** [comment]
Found out that the main.bundle.js is not minified. I run my own minification script and managed to reduce main.bundle.js from 3MB to 0.9MB.

I guess until the team add minification into ng build, you could just do it yourself for the time being.

**Comment by antonybudianto7** [comment]
did you run `ng build -prod` ?

**Comment by kylecordes** [comment]
Could this be a case of docs-could-be-better? The README says "...using the --prod flag in ng build --prod or ng serve --prod will also make use of uglifying and tree-shaking functionality", which is true and good. Maybe it should also use the more general word "minification" in addition to (or instead of) the specific "uglifying"? That way someone searching the docs for "minifi" would find it.

**Comment by a5hik** [comment]
The main.bundle.js is minified indeed in prod mode. 
But still the minified version is 2.6 MB in size, looking for options to reduce it further.

I understand the AOT is still not supported in CLI, But what else I could do here to reduce the bundle size.

**Comment by a5hik** [comment]
@filipesilva Do you have any idea here?

**Comment by thibaultsavary** [comment]
Same story for me, the hello world is:
2.6 MB in dev
815 kB in production
186 kB when served via firebase (gzipp-ed) which still feels a big

Could someone enlighten us about why it's so big for an "empty" project ?

**Comment by elvirdolic** [comment]
And if you put some code in with some plugins like material the bundle size gets about 5mb in dev and 400kb gzipped. Looking forward for aot

**Comment by a5hik** [comment]
Found out that the WebPack Dev server is currently not serving the 'gzip' ed bundles. Thats the issue. 

https://github.com/angular/angular-cli/issues/2028
https://github.com/angular/angular-cli/issues/2340

After adding the `compress: true` option the `--prod` mode gets served with `gzip` ed bundles. 
And the size of the main bundle is reduced from 2.5 MB to 208 B. 

Still If we have the AOT, I can expect it be more faster.

**Comment by deebloo** [comment]
208 is the browser retrieving from cache. Gzipped for hello world is probably around 150kb

**Comment by a5hik** [comment]
@deebloo mine is not an hello world its a production ready product.

**Comment by deebloo** [comment]
@a5hik I am just saying double check your bundle size. It isn't possible that the bundle is 208B.

**Comment by a5hik** [comment]
@deebloo Thanks!.

I see still the 2.5 MB as the original size in the console.
![image](https://cloud.githubusercontent.com/assets/5074139/18935559/bbb20304-8595-11e6-85f3-f3b5bbf59514.png)

**Comment by a5hik** [comment]
The gzipped version is `594KB` on Disk.

**Comment by cschroeter** [comment]
```
ng build --prod --aot
```

to the rescue

**Comment by a5hik** [comment]
Is this possible to do with beta.16?

**Comment by a5hik** [comment]
I had updated to beta.16

`angular-cli: 1.0.0-beta.16
node: 6.2.1
os: darwin x64`

And running `ng build --prod --aot` is causing me an other issue on compilation.

`Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppThirdPartyModule in /src/app/app.thirdparty.module.ts, resolving symbol AppThirdPartyModule in /src/app/app.thirdparty.module.ts`

`@NgModule({
  imports: [CommonModule, XXXXModule.forRoot()],
  declarations: [],
  exports: [
    XXXXModule]
})`

I guess calling the XXXModule.forRoot() is causing the problem in module Imports.

**Comment by Delagen** [comment]
Seems to not support animation
```
Error encountered resolving symbol values statically. Calling function 'style', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol
```

```
 animations:  [
				   trigger("collapseAnimation", [
					   state("hidden", style({height: 0})),
					   state("visible", style({height: AUTO_STYLE})),
					   transition("* <=> *", animate("0.3s linear"))
				   ])
			   ],
```

**Comment by filipesilva** [comment]
Sorry, but there isn't much I can do to help you on this issue. I don't see an actionable CLI problem here. 

It's true that `--aot` helps with bundle size but it's not yet fully available as of beta.16.

**Comment by emaradevska** [comment]
Where did you add compress=true?

**Comment by paqogomez** [comment]
@emaradevska, something like this:

	plugins: [
		new webpack.optimize.AggressiveMergingPlugin(),
        new UglifyJsPlugin({
            sourceMap: false,
            uglifyOptions: {
                compress: {
                    sequences: true,
                    dead_code: true,
                    conditionals: true,
                    booleans: true,
                    unused: true,
                    if_return: true,
                    join_vars: true,
                    drop_console: true
                },
                mangle: {
                    //except: ['$super', '$', 'exports', 'require']
                },
                output: {
                    comments: false
                }
            }
		})]
