### ISSUE TITLE
ng --version gives Package Manager: <Error>

### ISSUE THREAD

**Issue by aakashwt** [angular/angular-cli#22827]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Framework issues at: https://github.com/angular/angular/issues/new/choose

For the time being, we keep Angular issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 13.2.6
Node: 16.14.0
Package Manager: <error>
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.6 (cli-only)
@angular-devkit/core         13.2.6 (cli-only)
@angular-devkit/schematics   13.2.6 (cli-only)
@schematics/angular          13.2.6 (cli-only)

When I am trying to create a new app, with ng new demo, it is failing with 

CREATE inc-app/angular.json (3045 bytes)
CREATE inc-app/package.json (1070 bytes)
CREATE inc-app/README.md (1052 bytes)
CREATE inc-app/tsconfig.json (863 bytes)
CREATE inc-app/.editorconfig (274 bytes)
CREATE inc-app/.gitignore (548 bytes)
CREATE inc-app/.browserslistrc (600 bytes)
CREATE inc-app/karma.conf.js (1424 bytes)
CREATE inc-app/tsconfig.app.json (287 bytes)
CREATE inc-app/tsconfig.spec.json (333 bytes)
CREATE inc-app/.vscode/extensions.json (130 bytes)
CREATE inc-app/.vscode/launch.json (474 bytes)
CREATE inc-app/.vscode/tasks.json (938 bytes)
CREATE inc-app/src/favicon.ico (948 bytes)
CREATE inc-app/src/index.html (292 bytes)
CREATE inc-app/src/main.ts (372 bytes)
CREATE inc-app/src/polyfills.ts (2338 bytes)
CREATE inc-app/src/styles.css (80 bytes)
CREATE inc-app/src/test.ts (745 bytes)
CREATE inc-app/src/assets/.gitkeep (0 bytes)
CREATE inc-app/src/environments/environment.prod.ts (51 bytes)
CREATE inc-app/src/environments/environment.ts (658 bytes)
CREATE inc-app/src/app/app.module.ts (314 bytes)
CREATE inc-app/src/app/app.component.html (23332 bytes)
CREATE inc-app/src/app/app.component.spec.ts (959 bytes)
CREATE inc-app/src/app/app.component.ts (211 bytes)
CREATE inc-app/src/app/app.component.css (0 bytes)
- Installing packages (npm)...
'npm' is not recognized as an internal or external command,
operable program or batch file.
× Package install failed, see above.
The Schematic workflow failed. See above.

npm -v
8.5.3

**Comment by alan-agius4** [comment]
Kindly see: https://stackoverflow.com/questions/20992723/npm-is-not-recognized-as-internal-or-external-command-operable-program-or-bat

**Comment by aakashwt** [comment]
I am able to see npm -v which gives 8.5.3,

The error is 

Angular CLI: 13.2.6
Node: 16.14.0
**_Package Manager: <error>_**
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1302.6 (cli-only)
@angular-devkit/core         13.2.6 (cli-only)
@angular-devkit/schematics   13.2.6 (cli-only)
@schematics/angular          13.2.6 (cli-only)


**Package Manager: <error>**
 I tried the solution and it is not working for me.

**Comment by alan-agius4** [comment]
On windows when you change the PATHS you might need to restart your machine to take full effect.
