### ISSUE TITLE
CSS sourcemap files aren't produced 

### ISSUE THREAD

**Issue by JWess** [angular/angular-cli#22834]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
I don't believe so, but I'm not for sure on that.

### Description

 
When building with `angular.json` => `{ sourcemaps: true, optimization: true }` (more specifically `optimization.styles.minify: true`), CSS sourcemap comments in `main.*.js` point to a non-existent `*.component.css.map` file:
```
/*sourceMappingURL=footer.component.css.map*/
```
The corresponding `footer.component.css.map` file is not created by the build.

Here is an example of an example app containing a FooterComponent built with four different `optimization` build settings in `angular.json` (but sourcemaps turned on in all four cases):

![image](https://user-images.githubusercontent.com/8697891/158031816-a3cbf094-7082-4fe0-a4ca-e31e9dc9cb80.png)

No `footer.component.css.map` file is ever created. When the app source code is viewed in Chrome Dev Tools, it tries and fails to load the non-existant CSS sourcemaps.

## 🔬 Minimal Reproduction

Build using `angular.json`:
```
{
  "sourcemaps": true,
  "optimization": true
}
```

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.6
Node: 16.14.0
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 13.2.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
</code></pre>

**Comment by alan-agius4** [comment]
Hi @JWess, that fact that the sourcemap is not generated is expected. See: https://github.com/angular/angular-cli/pull/15238. However, the `sourceMappingURL` comment shouldn't be included.

**Comment by alan-agius4** [comment]
Hi @JWess, 

I tried this locally and I wasn't able to replicate as for my case the `sourceMappingURL` wasn't generated. Can you please provide a reproduction? 

```js
return (
  (e.ɵfac = function (n) {
    return new (n || e)();
  }),
  (e.ɵcmp = qi({
    type: e,
    selectors: [["app-root"]],
    decls: 0,
    vars: 0,
    template: function (n, r) {},
    styles: ["a[_ngcontent-%COMP%]{color:#fff}"],
  })),
  e
);

```

**Comment by alan-agius4** [comment]
We have discussed this during our team meeting and we have determined that this is what needs to happen;

- Add warning during the build when optimizations and sourcemaps are able to notify the end user that components css sourcemaps will not be generated.
- Make an issue to add support for external CSS.

**Comment by JWess** [comment]
> 

Thanks for the report! When you say "add support for external CSS", that refers to what exactly? Will you be creating that Issue? Thanks again for your prompt effort on all of this.

**Comment by JWess** [comment]
> We have discussed this during our team meeting and we have determined that this is what needs to happen;
> 
> * Add warning during the build when optimizations and sourcemaps are able to notify the end user that components css sourcemaps will not be generated.
> * Make an issue to add support for external CSS.

Thanks for the report! When you say "add support for external CSS", that refers to what exactly? Will you be creating that Issue? Thanks again for your prompt effort on all of this.

**Comment by JWess** [comment]
> Basically what it means is, add support for CSS sourcemaps for components when optimization is enabled which can be done by instead of inline sourcemaps as base64 in the JS file we emit the sourcemap as an external file.
> 
> I'll be opening the feature request issue in the next couple of days.

Did this feature request issue ever get created?

**Comment by JWess** [comment]
@alan-agius4 Did this get lost in the shuffle?

**Comment by alan-agius4** [comment]
Hi @JWess, sorry for the delay.
I just created a opening the feature request https://github.com/angular/angular-cli/issues/24049.
