### ISSUE TITLE
How is "source": "/environments/environment.ts" used assuming it's used at all? 

### ISSUE THREAD

**Issue by Cogitaria** [angular/angular-cli#2283]
> Please provide us with the following information:
> ---------------------------------------------------------------

The **angular-cli.json** file has an environments object with a **source** property.  How is the referenced file used? Is it used?  I get the custom environments settings and using the command line switch, but what is this particular file doing (it never changes, it's not ignored in git). 

  "environments": {
        "source": "environments/environment.ts",

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

N/A

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

1.0.0-beta.15

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

N/A

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
It specifies the file that should be replaced with the dev/prod/etc file. We're considering just defaulting to `dev` though.
