### ISSUE TITLE
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID   (Angular 13)

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular-cli#22845]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: angular v11

### Description

 A clear and concise description of the problem...
After upgrading from v11 to v13 by running the following commands:
```
npx @angular/cli@12 update @angular/core@12 @angular/cli@12
npx @angular/cli@13 update @angular/core@13 @angular/cli@13
```
Then run `ng serve`, I got:
```
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID   
See "C:\xxx\angular-errors.log" for further details.
```
more details in `angular-errors.log`
```
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (c:\xxx\www\node_modules\@angular\cli\node_modules\ajv\dist\compile\codegen\index.js:568:18)


```

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.2.6
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            11.1.2
@angular-devkit/schematics      13.2.6
@schematics/angular             13.2.6
rxjs                            6.6.7
typescript                      4.5.5
    
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Looks like you have incompatible packages in your node modules tree
```
@angular-devkit/architect       0.1101.2
@angular-devkit/core            11.1.2
```

Can you please provide the output of 
```
npm ls @angular-devkit/architect
npm ls @angular-devkit/core
```

**Comment by UchihaYuki** [comment]
It is caused by this package:
```
  "devDependencies": {
    "@angular-builders/custom-webpack": "^11.1.1",
···
the upgrade command:
```
npx @angular/cli@12 update @angular/core@12 @angular/cli@12
```
doesn't modify it.

**Comment by alan-agius4** [comment]
That is expected since `@angular-builders/custom-webpack` is a third party package and hence is not supported by the Angular team.

Please update `@angular-builders/custom-webpack` to a version that supports Angular version 13. If the problem persists afterwards please file an issue with the authors of the mentioned package.
