### ISSUE TITLE
Extra comma when we using `--style=none` to generate a component

### ISSUE THREAD

**Issue by oidacra** [angular/angular-cli#22857]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

The problem persist since a long time ago. (https://github.com/angular/angular-cli/issues/13114#issue-386633859)

### Description

When use generate component with the flag --change-detection=onPush add a extra comma at the end of the preview line.

## 🔬 Minimal Reproduction

`npx ng new angular-tour-of-heroes`
`npx ng g c order-summary  --no-style --change-detection=OnPush`

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.0
Node: 16.14.0
Package Manager: npm 8.3.1
OS: darwin x64

Angular: 13.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.3.0
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@schematics/angular             13.3.0
rxjs                            7.5.5
typescript                      4.6.2

</code></pre>

**Anything else relevant?**
Screenshot
![Screen Shot 2022-03-17 at 12 07 34 AM](https://user-images.githubusercontent.com/1909643/158741187-d831e8ae-ebf1-4f33-93c9-a445f511fdae.png)

**Comment by alan-agius4** [comment]
Note this only happens when using `--no-style` option.

**Comment by oidacra** [comment]
Edited the minimal reproductions, thanks @alan-agius4
