### ISSUE TITLE
extract-i18n doesn't  work when $localize is used server side

### ISSUE THREAD

**Issue by manzonif** [angular/angular-cli#22868]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

in AppServerModule (universal) I have  the following service provided
`{
      provide: MetadataService,
      useClass: MetadataServiceServer
    }`
Using $ localize in that file does not produce any translation units.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1200.5
@angular-devkit/build-angular     12.0.5
@angular-devkit/build-optimizer   0.1200.5
@angular-devkit/core              12.0.1
@angular-devkit/schematics        12.0.1
@angular/flex-layout              12.0.0-beta.34
@angular/localize                 12.0.5
@nguniversal/builders             12.1.3
@nguniversal/common               12.0.0
@nguniversal/express-engine       12.0.0
@schematics/angular               12.0.1
rxjs                              7.4.0
typescript                        4.2.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by manzonif** [comment]
running extract-i18n will extract message from BrowserServiceService, but not from ServerServiceService.
[https://github.com/manzonif/ng-extract-i18n-server](repro app)
