### ISSUE TITLE
Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by parth-iqarena** [angular/angular-cli#22867]
# 🐞 Bug report

- [ ] new
- [X] build
- [X] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 When i try to serve the angular application it's giving me heap out of memory i tried with increasing max-out-space and unistalling the node and reinstalling the node again but nothing help.

## 🔬 Minimal Reproduction

[21898:0x7fa702100000]   306997 ms: Mark-sweep 8071.0 (8225.2) -> 8068.0 (8224.2) MB, 39062.0 / 0.1 ms  (average mu = 0.191, current mu = 0.008) allocation failure scavenge might not succeed
[21898:0x7fa702100000]   307245 ms: Scavenge 8083.7 (8224.2) -> 8082.4 (8240.2) MB, 100.4 / 0.0 ms  (average mu = 0.191, current mu = 0.008) allocation failure 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10d74f775 node::Abort() [/usr/local/bin/node]
 2: 0x10d74f8f8 node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x10d8c7707 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10d8c76a3 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x10da660e5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]
 6: 0x10da6494c v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]
 7: 0x10da712c0 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 8: 0x10da71341 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 9: 0x10da3e1b7 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/local/bin/node]
10: 0x10ddec2ae v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x10e18e359 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/usr/local/bin/node]
Simple steps to reproduce this bug.

I'm using ng serve command and tried to build but it's giving same error.

Here's version I'm currently on
<pre><code>

Angular CLI: 12.0.5
Node: 16.14.2
Package Manager: npm 8.5.0
OS: darwin x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@angular/cdk                    12.2.13
@angular/material               12.2.13
@schematics/angular             12.0.5
rxjs                            6.5.5
typescript                      4.2.4

</code></pre>

![Screenshot 2022-03-21 at 7 00 11 PM](https://user-images.githubusercontent.com/91815939/159271336-c35da2d8-66f6-4dee-8d69-3414d65855ff.png)

**Comment by alan-agius4** [comment]
Hi @parth-iqarena, can you please try to update to the latest stable? As since a lot has changed since version 12.0. If the problem persists after updating can you please provide the memory snapshots?

What was the memory usage prior to version 11?

**Comment by alan-agius4** [comment]
Closing due to lack of information.
