### ISSUE TITLE
Prototype Pollution in minimist

### ISSUE THREAD

**Issue by langthiennhai** [angular/angular-cli#22869]
Angular: 13
 Nodejs: 14.15.0

  ///////////////////////
  High            Prototype Pollution in minimist                               
  Package         minimist                                                      
  Patched in      No patch available                                            
  Dependency of   @angular-devkit/build-angular                                 
  Path            @angular-devkit/build-angular > @babel/core > json5 > minimist                                                      
  More info       https://github.com/advisories/GHSA-xvch-5gv4-984h        
  ///////////////////////

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/22865
