### ISSUE TITLE
ng build taking more time when running on kubernetes pod

### ISSUE THREAD

**Issue by suryabaiarava** [angular/angular-cli#22887]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x]  build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, It just work as expected in AWS EC2

### Description

Am trying to convert our existing CI(Continues integration) agents from AWS EC2 to kubernetes pods so when we are trying to build the same application in both type of agents we are observing build is taking long time in  kubernetes pods i.e build is taking 4Min in ec2 vs 10min in pod. 
We have provided same CPU, memory to our kubernetes pods also. when i tried to analyze the logs i see build is taking more time at this statement "**Browser application bundle generation complete."**. i tried setting **npm config set unsafe-perm true**, -**-max-old-space-size=10240** but its not helpful .
Please let me know if am missing any configuration. 
**Versions:**
npm 8.3.1
node version v16.14.0

## 🔬 Minimal Reproduction

Run the application using below base image and check the performance.

FROM ubuntu:18.04 

## 🔥 Exception or Error

its not error

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by suryabaiarava** [comment]
thanks @alan-agius4  for responding can you please share me any way or blog reference to debug the issue i tried adding verbose its not giving me more information why its taking more time so that i can debug further and make progress on this. currently as per logs its taking more time at this **✔ Browser application bundle generation complete.**
