### ISSUE TITLE
Add legacyPeerDeps option to NodePackageInstallTask

### ISSUE THREAD

**Issue by KirillMetrik** [angular/angular-cli#22886]
# 🚀 Feature request

### Description

Right now there is an opportunity to use `NodePackageInstallTask` when authoring schematics. This works well but there are cases when running simple `npm install` is not enough. For example, last version of NPM might throw "Unable to resolve dependency tree" error. This can be easily fixed with an `--legacy-peer-deps` option. Unfortunately, this option is not available for `NodePackageInstallTask`.

### Describe the solution you'd like

Add ability to provide `legacyPeerDeps` option to `NodePackageInstallTask`. Even better solution would be to add opportunity to provide any custom options to `NodePackageInstallTask`. They should be passed down to command line automatically.

### Describe alternatives you've considered

I've tried to write my own `NodePackageInstallTask` with an extra option. But this didn't work. I've discovered that provided options are just meta-data for the executor (https://github.dev/angular/angular-cli/blob/366cabc66c3dd836e2fdfea8dad6c4c7c2096b1d/packages/angular_devkit/schematics/tasks/package-manager/executor.ts#L112). From executor code it is clear that there is a predefined set of options for NPM task and there is no way to override or extend this.

**Comment by KirillMetrik** [comment]
@alan-agius4 i haven't found this option neither. Maybe I am looking wrongly. Could you give an example of it's usage?

**Comment by KirillMetrik** [comment]
@alan-agius4 and do you please have an example of calling `NodePackageInstallTask` from schematics code with `--force` enabled?

**Comment by alan-agius4** [comment]
That is not possible, since the `force` option is strictly controlled by the Angular CLI. We only allow using the force option in `ng update`.

**Comment by alan-agius4** [comment]
@mzocateli, why not amend the custom `ng-new` dependencies to not require `legacy-peer-deps` in the first place?

In general, using legacy-peer-deps is not recommended.

**Comment by mzocateli** [comment]
Indeed, I agree, it would be the ideal scenario.
But as it is a large company with a technology area with more than 20k people (even though it is not a technology company) and producing a range of internal packages, we are unable to control the peer dependencies of all these packages that eventually enter the distributed templates in our application.
Some of them are truly legacy packages despite modernization initiatives.

I know this isn't exactly angular's problem, but making this kind of coexistence easier would help a lot 😅

**Comment by alan-agius4** [comment]
I fell like it would be better to alter the custom schematic to add an `.npmrc` file in the project root to configure `legacy-peer-deps`, this would also effect `npm install` when executed outside of schematics.

**Comment by KirillMetrik** [comment]
A small update from me. In the end I've done significant efforts to resolve all peer dependencies conflicts, so node installation task works now.
But I still feel that it would be a great feature to allow to pass any options to npm installation task (not just legacyPeerDeps).

**Comment by alan-agius4** [comment]
@KirillMetrik, the Install task is packager manager agnostic.

I feel that if you need a to provide a specific option, likely you also need this when running NPM directly, and therefore in that case using a workspace level npm config file would be a better approach.

**Comment by mzocateli** [comment]
> I fell like it would be better to alter the custom schematic to add an `.npmrc` file in the project root to configure `legacy-peer-deps`, this would also effect `npm install` when executed outside of schematics.

It worked, at least for Angular 12+ projects using npm8, but I think that'll do it.

**Comment by alan-agius4** [comment]
Closing, as using legacyPeerDeps is not recommend.

In the case you need to use it, it would be better to configure this through an npmrc file, so that when running npm directly this setting is also applied.

Let’s reconsider this in the future if there is a bigger demand for this.
