### ISSUE TITLE
Error EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Ewuga** [angular/angular-cli#2289]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
    window 7 32bit
2. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:
   angular-cli:1.0.0-beta.15
   node :6.6.0
3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   ng new
4. The log given by the failure. Normally this include a stack trace and some
   more information.

> EISDIR: illegal operation on a directory, read
> Error: EISDIR: illegal operation on a directory, read
>     at Error (native)
>     at Object.fs.readSync (fs.js:731:19)
>     at tryReadSync (fs.js:486:20)
>     at Object.fs.readFileSync (fs.js:534:19)
>     at Object.getSource (C:\Users\hp\Documents\ENCENTRAL\tranquil\node_modules\@
> angular-cli\ast-tools\src\ast-utils.js:25:45)
>     at findLoadChildren (C:\Users\hp\Documents\ENCENTRAL\tranquil\node_modules\a
> ngular-cli\models\find-lazy-modules.js:8:30)
>     at C:\Users\hp\Documents\ENCENTRAL\tranquil\node_modules\angular-cli\models\
> find-lazy-modules.js:46:9
>     at Array.forEach (native)
>     at Object.findLazyModules (C:\Users\hp\Documents\ENCENTRAL\tranquil\node_mod
> ules\angular-cli\models\find-lazy-modules.js:45:10)
>     at Object.getWebpackCommonConfig (C:\Users\hp\Documents\ENCENTRAL\tranquil\n
> ode_modules\angular-cli\models\webpack-build-common.js:18:43)
>     at new NgCliWebpackConfig (C:\Users\hp\Documents\ENCENTRAL\tranquil\node_mod
> ules\angular-cli\models\webpack-config.js:13:30)
>     at Class.run (C:\Users\hp\Documents\ENCENTRAL\tranquil\node_modules\angular-
> cli\tasks\serve-webpack.js:19:22)
>     at C:\Users\hp\Documents\ENCENTRAL\tranquil\node_modules\angular-cli\command
> s\serve.js:84:26
>     at process._tickCallback (internal/process/next_tick.js:103:7)
1. Mention any other details that might be useful.
   I run CMD as an Administrator.
   It runs fine after the first ng serve but gives the above error in subsequent ng serve

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by rolandoldengarm** [comment]
I'm suddenly getting the same error. Any idea how to fix this?

**Comment by Ewuga** [comment]
I haven't gotten any solution yet.

**Comment by rolandoldengarm** [comment]
in my case, it was due to the fact I had added an i18n folder, with xlf extracted to .ts, but there were duplicates (i.e. two files exporting the same string constant).
Weird yeah.

**Comment by catull** [comment]
@Ewuga @rolandoldengarm Is this still an issue ?

**Comment by rolandoldengarm** [comment]
In my case, I've fixed it by removing the export of the same constant. Could be a different issue than @Ewuga

**Comment by hansl** [comment]
Closing this as obsolete.
