### ISSUE TITLE
 ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC

### ISSUE THREAD

**Issue by avnesh1** [angular/angular-cli#22904]
npm ERR! code ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC
npm ERR! errno ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/log4js: 14752:error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac:c:\ws\deps\openssl\openssl\ssl\record\ssl3_record.c:677:
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\........\AppData\Local\npm-cache\_logs\2022-03-28T17_43_49_464Z-debug.log

**Comment by Fernando-Braulio** [comment]
Conseguiu resolver @avnesh1 ? Estou com o mesmo desafio ao tentar executar npm install

**Comment by alrazihi** [comment]
Conseguiu resolver @avnesh1 ? Estou com o mesmo desafio ao tentar executar npm install

**Comment by zhanglufanboy** [comment]
just change the settings of the windows defender firewall.but The problem has not been solved
