### ISSUE TITLE
An unhandled exception occurred: Dev-server address info is not defined

### ISSUE THREAD

**Issue by GarfieldDeepClone** [angular/angular-cli#22903]
- [ x] serve

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12

When trying to run the application I get this error message:
Running "ng:serve" (ng) task

>>> Using Angular CLI => "ng serve"

Warning: Running a server with --disable-host-check is a security risk. See https://medium.com/webpack/webpack-dev-server-middleware-security-issues-1489d950874a for more information.
⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: Dev-server address info is not defined.
See "/private/var/folders/62/m5vqsbd1251d77334_xl_4x40000gp/T/ng-G32x8J/angular-errors.log" for further details.
⠙ Generating browser application bundles (phase: setup)...Warning: Task "ng:serve" failed. Use --force to continue.

The error is caused by this code in webpack.cli.js:
```
devServer.setupMiddlewares = (middlewares, devServer) => {
			if (!devServer) {
				throw new Error('webpack-dev-server is not defined');
			}

			devServer.app.get('/', function (req, res, next) {
				res.set({ 'Content-Security-Policy': props.devServer.csp });
				next();
			});
		};
```

I used devServer.before before upgrading from Angular 12 to 13.

The error from the mentioned angular-errors.log:
```
[error] Error: Dev-server address info is not defined.
    at xyz/node_modules/@angular-devkit/build-webpack/src/webpack-dev-server/index.js:63:27
```

which relates to this code snippet from @angular-devkit/build-webpack/src/webpack-dev-server/index.js
```
const address = (_a = devServer.server) === null || _a === void 0 ? void 0 : _a.address();
            if (!address) {
                obs.error(new Error(`Dev-server address info is not defined.`));
                return;
            }
```

So it seems that devServer.server is not defined. I debugged it with this command:
`node --inspect-brk node_modules/.bin/ng serve`

And I could see that the server property is not directly on the devServer object, instead it's nested one level deeper in an options object:
```
devServer = {
options: {
server: ...
}
}
```

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: Dev-server address info is not defined.
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.3.0
Node: 14.18.2
Package Manager: yarn 1.22.17
OS: darwin x64

Angular: 13.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, upgrade

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1303.0
@angular-devkit/build-angular      13.3.0
@angular-devkit/core               13.3.0
@angular-devkit/schematics         13.3.0
@angular/cdk                       13.3.1
@angular/material                  13.3.1
@angular/material-moment-adapter   13.3.1
@schematics/angular                13.3.0
rxjs                               6.6.3
typescript                         4.6.2
webpack                            5.70.0

</code></pre>

**Comment by alan-agius4** [comment]
Can you provide the output of `npm ls webpack-dev-server`?

Are you using any custom builders?

**Comment by GarfieldDeepClone** [comment]
@angular-devkit/build-angular@13.3.0
  └── webpack-dev-server@4.7.3

Yes, I'm using:
"builder": "@angular-builders/custom-webpack:dev-server",

**Comment by alan-agius4** [comment]
`devServer.options.server` is different from `devServer.server`. 

The Angular team doesn't support custom webpack configuration / custom builders. That said the issue might be that you the `setupMiddlewares` is not returning the `middlewares` array.

**Comment by GarfieldDeepClone** [comment]
Yes, the issue really was only that I didn't return the middlewares array :o
