### ISSUE TITLE
Can't load app.component.html with relative path

### ISSUE THREAD

**Issue by richavyas** [angular/angular-cli#2293]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
    Mac OSX (Yosemite)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.14
node: 6.1.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
   This app ran successfully with the latest webpack/angular-cli@latest but it's not loading `app.component.html` with relative path. 

source code:

#### app.component.ts
   ```
   styleUrls: ['./app.component.scss'],
   templateUrl: './app.component.html',
   ```

#### Error:
```zone.js:1241GET http://localhost:4200/app.component.html 404 (Not Found)
zone.js:344 Unhandled Promise rejection: Failed to load app.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load app.component.html undefined```

   #### Setup info:
   Router : upgraded to rc.7
   Webpack: "2.1.0-beta.22"
   angular-cli@latest

4. The log given by the failure. Normally this include a stack trace and some
   more information.
No error while ng build or serve. Build happens successfully but this does not load files with relative path.

5. Mention any other details that might be useful.
Things work upto certain extent when used complete folder structure like `app/app/component.html` or `app/components/...`

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by richavyas** [comment]
Closing this as everything started working with `angular-cli@1.0.0-beta.15`

**Comment by TeodorKolev** [comment]
Same here

**Comment by richavyas** [comment]
@TeodorKolev same here in what terms? Just in case, if you are still facing relative path issue, please match the options in `src/tsconfig.json` with https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14#steps-to-migrate `src.webpacktemplate/tsconfig.json`

**Comment by TeodorKolev** [comment]
I got` Failed to load app.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load app.component.html ` from [this ](https://angular.io/docs/ts/latest/guide/webpack.html#!#configure-webpack)tutorial. My repo: [repo](https://github.com/TeodorKolev/Angular2-starter)

**Comment by dokkis** [comment]
@richavyas @TeodorKolev same here, I temporary resolved by putting the complete path src/app/app.component.html, same for css:

@Component({
    selector: 'my-app',
    templateUrl: 'src/app/app.component.html',
    styleUrls: ['src/app/app.component.css']
})

In previous version of Angular you should put the whole path, I don't know if in Angular2 something changed and you can load it by relative path but for me currently it doesn't working. I followed the same tutorial.

**Comment by talhaamin** [comment]
add module:module.id as a first line in @Component directive.

**Comment by elebumm** [comment]
Was also having this problem and @talhaamin's solution worked for me. Thank you.

**Comment by iamsarav** [comment]
Even with `module:module.id ` i am getting the same error.
Cam some one explain me how is this relative path works, and from  where the relative path starts basically?

**Comment by avuletica** [comment]
Changing from  module:module.id  to moduleId: module.id worked for me.

**Comment by GabrielSimonMarian** [comment]
adding module:module.id does not work for me also. 
i've tried to apply dokkis's solution, but i do not found .map and .js files under src, in order to delete them
![image](https://cloud.githubusercontent.com/assets/19171289/21673970/52cbbbfe-d334-11e6-99db-bd1b15d9e1ea.png).
dokkis, can you provide here more help, please ?
thanks

**Comment by avuletica** [comment]
Did you try my solution with moduleId: module.id (notice Id in name on left side)

**Comment by GabrielSimonMarian** [comment]
Hi @avuletica,

I've tried also your solution, but if I understood correctly, as long as I have in my project webpack, this solution won't work. 
![image](https://cloud.githubusercontent.com/assets/19171289/21675113/3c07883a-d339-11e6-9783-834574462a13.png)
![image](https://cloud.githubusercontent.com/assets/19171289/21675129/45fc9b78-d339-11e6-8662-c278e1b22a41.png)

The interesting fact, is that my configuration has previously worked well.

**Comment by avuletica** [comment]
You are right, it seems If you are using webpack for bundling then you don't need  module.id in decorator. Webpack plugins auto handle (add it)  module.id in final bundle, did you check on angular official site:

![web](https://cloud.githubusercontent.com/assets/11634859/21675281/9f6ab134-d331-11e6-8c8a-98edb350b77b.png)

**Comment by GabrielSimonMarian** [comment]
Nope, does not works at all, the error is still there.
![image](https://cloud.githubusercontent.com/assets/19171289/21675521/be9b0032-d33a-11e6-927d-8ee2411affa4.png)
Should the taken into consideration the fact, that I do no use angular-cli ? (the project was implemented without angular-cli, but as I said previously has worked well).

**Comment by rahul-sivalenka-wtc** [comment]
Deleting the .js and .js.map files from the serving directory solved the problem for me

**Comment by loumorgsy** [comment]
adding 

moduleId: module.id 

in the component decorator worked for me

**Comment by gncstudios** [comment]
moduleId: module.id worked for me

**Comment by joe223** [comment]
Same error. It works if I use `app/dashboard.component.html`

**Comment by rameshpraja** [comment]
Same Error : Its work if we start the path from app directory.
for example :
templateUrl: './app/reactive/hero-form-reactive.component.html'

**Comment by sanaattar** [comment]
how module:module.id this thing fix issue? Can anybody explain plz
Need to understand logic

**Comment by Codefans-fan** [comment]
https://stackoverflow.com/questions/39503805/zone-js344-unhandled-promise-rejection-failed-to-load-app-template-html-in-ang

**Comment by sunkarashruthi** [comment]
@rameshpraja : 
I get 404: angular2.dev.js:20736 GET http://localhost:3000/app/contact-form.component.html 404 (Not Found) 
 even if i give the path from app directory.

@loumorgsy y should we give moduleId: module.id

when i gave it says cannot find module.

Pl let me know. TIA

**Comment by fedorov1997** [comment]
> templateUrl: './menu.component.html' 
to
> templateUrl: require('./menu.component.html')
works fine for me..

**Comment by nombrekeff** [comment]
> Deleting the **.js** and **.js.map** files from the serving directory and setting `compileOnSave: false` in **tsconfig.json** solved the problem for me

Yup, this also worked for me, thanks!
