### ISSUE TITLE
--cross-origin build option not respected by lazy loader

### ISSUE THREAD

**Issue by jjamid** [angular/angular-cli#22942]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12

### Description

In Android WebView, the default behavior for type="module" is not to send credentials, even for same origin.
Using the build option --cross-origin=use-credentials solves this problem for the initial scripts by 
adding it to the generated scripts.

ng build --configuration=production --cross-origin=use-credentials

However, the lazy loader does not respect this option and only checks the window.location.origin and doesn't add crossOrigin="use-credentials" to the lazy load requests for the same origin.
As a result the module loading fails.

One expects that it will respect the build option --cross-origin=use-credentials

As a work around, I manually change the runtime.js file after build to add the crossOrigin attribute.

## 🔬 Minimal Reproduction

Running an angular 13 application with lazy loading in an android WebView when cookies are needed for same origin.
## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by jjamid** [comment]
Here is the problematic minified line of code from the build itself inside runtime.js, it only adds crossOriging when the location.origin is different, and does not respect the build option

`0 !== t.src.indexOf(window.location.origin + "/") && (t.crossOrigin = "use-credentials")),`


And here is the ng version output

Angular CLI: 13.3.0
Node: 12.22.11
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 13.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.3.0
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@schematics/angular             13.3.0
ng-packagr                      13.3.0
rxjs                            6.6.7
typescript                      4.6.2

**Comment by jjamid** [comment]
> Can you please provide the output of `ng version`?
> 
> We do have a test that covers this case:
> 
> https://github.com/angular/angular-cli/blob/d163229a5ffd2b682786299544385bb2e82a83aa/packages/angular_devkit/build_angular/src/builders/browser/specs/cross-origin_spec.ts#L88

This test seems wrong. Checking if something contains a text anywhere is hardly a good check.

**Comment by alan-agius4** [comment]
This is not actionable from our end as that is how Webpack handles `crossOrigin`. https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/runtime/LoadScriptRuntimeModule.js#L89-L96

If you feel that this should be handled any different please file an issue with Webpack.

**Comment by jjamid** [comment]
> This is not actionable from our end as that is how Webpack handles `crossOrigin`. https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/runtime/LoadScriptRuntimeModule.js#L89-L96
> 
> If you feel that this should be handled any different please file an issue with Webpack.
Too bad.

So basically the build option is useless when using lazy loading with Android WebView. Perhaps it should be pointed out somewhere.  I will look for another workaround. Maybe even with the Android WebView Team.

Thanks anyway for the quick reply.
