### ISSUE TITLE
I cannot make bootstrap load in angular13

### ISSUE THREAD

**Issue by dgiglio** [angular/angular-cli#22945]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] serve

### Is this a regression?

Cannot say.

### Description

I cannot make bootstrap work in angular 13

## 🔬 Minimal Reproduction

I've installed the mandatory packages with:

`npm install jquery --save`
`npm install bootstrap --save`
`npm install popper.js --save`

## 🔥 Exception or Error

I get no error.

## 🌍 Your Environment

<pre><code>Angular CLI: 13.2.6
Node: 12.22.5
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 13.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
</code></pre>

**Anything else relevant?**

I've edited the `angular.json` this way
<pre><code>"styles": [
          "node_modules/bootstrap/dist/css/bootstrap.min.css"
        ],
        "scripts": [
          "node_modules/jquery/dist/jquery.min.js",
          "node_modules/popper.js/dist/umd/popper.min.js",
          "node_modules/bootstrap/dist/js/bootstrap.min.js"
        ]
</code></pre>

I've also added  `@import '~bootstrap/dist/css/bootstrap.css';` into `style.css` and `angular.json`.

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
