### ISSUE TITLE
environment variables in compiled code use different quotes than defined in environment.*.ts files

### ISSUE THREAD

**Issue by fxck** [angular/angular-cli#22948]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When I use single quotes, they end up being double quotes after the build

![image](https://user-images.githubusercontent.com/1303561/162005893-4526d280-89ad-45e0-8eba-d2bb1a4b551b.png)

When I use single quotes, but they have double quotes inside, the correct quotes are preserved, probably due to some magic 

![image](https://user-images.githubusercontent.com/1303561/162005920-e50c2029-f8bc-4597-9d4d-ad0f056d6607.png)

The problem is that I'm using a placeholder as a value, which then gets replaced after the build step with a json value, but since Angular decides to use double quotes (since probably no double quotes were found in my placeholder), this results into unparseable json.

Why aren't the exact quotes preserved, could they be? Is it something configurable and I missed the option?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 13.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@schematics/angular             13.3.1
rxjs                            7.4.0
typescript                      4.5.5
```

**Comment by JoostK** [comment]
This is the optimizer at work. I believe they generally choose a consistent quote to enable better compression. This is not configurable in the CLI and I don't think it should be; the optimizer is free to do such transforms and you shouldn't depend on the exact string output to achieve string replacements in a post-processing step. This can also be easily avoided by replacing the placeholder including the quotes.

**Comment by fxck** [comment]
Hm, I see your points, in my case I'm limited by the platform, which has replacement an a built-in option and only allow for the same start and end delimiter, so I can't use `"%%`, `%%"`. I could also just escape the json value, but that in my case would be a nonsystemic solution.

I still feel like this is something that might be worth being configurable just for those environment files (if it's something even possible), since they are more likely to be used for hacky stuff post processing stuff than other places. But I'm closing this for now.

Thank you.
