### ISSUE TITLE
rules skipped due to selector errors:   legend+* -> Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by gravityctrl** [angular/angular-cli#22958]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 12.2.5

### Description

When building angular using the `production` configuration together with bootstrap, the step `Generating index html...` produces following warning: 
`1 rules skipped due to selector errors:
  legend+* -> Cannot read property 'type' of undefined`

## 🔬 Minimal Reproduction

In Terminal:
```cmd
ng new testproject --style scss
cd testproject
ng add @ng-bootstrap/ng-bootstrap
npm run build
```

## 🔥 Exception or Error

```
1 rules skipped due to selector errors:
  legend+* -> Cannot read property 'type' of undefined
```

Screenshot:
![image](https://user-images.githubusercontent.com/34040477/162418338-9c00e040-a24d-4ddf-8cef-9a9ba5965385.png)

## 🌍 Your Environment

```
Angular CLI: 13.3.2
Node: 14.17.6
Package Manager: npm 8.1.3
OS: win32 x64

Angular: 13.3.2
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@schematics/angular             13.3.2
rxjs                            7.5.5
typescript                      4.6.3
```

**Other relevant package versions:**
ng-bootstrap: `12.0.2`
Bootstrap: `5.1.3`

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the https://github.com/GoogleChromeLabs/critters project or file an issue on their issue tracker.
