### ISSUE TITLE
Passing multiple --configuration options broken as of 14.0.0-next.5

### ISSUE THREAD

**Issue by bgotink** [angular/angular-cli#22956]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] extract-i18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, passing multiple `--configuration`s worked up to and including 14.0.0-next.4

## 🔬 Minimal Reproduction

```
ng test --configuration lorem --configuration ipsum
```

See https://stackblitz.com/edit/node-sxof7v?file=README.md for a minimalistic repro set-up.

## 🔥 Exception or Error

<pre><code>
$ ng test repro --configuration lorem --configuration ipsum
An unhandled exception occurred: targetConfiguration.split is not a function
See "/tmp/ng-38e66e/angular-errors.log" for further details.

$  cat /tmp/ng-38e66e/angular-errors.log
[error] TypeError: targetConfiguration.split is not a function
    at WorkspaceNodeModulesArchitectHost.getOptionsForTarget (/home/projects/node-sxof7v/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:158:56)
    at async TestCommandModule.runSingleTarget (/home/projects/node-sxof7v/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js:37:17)
    at async TestCommandModule.run (/home/projects/node-sxof7v/node_modules/@angular/cli/src/command-builder/architect-command-module.js:65:20)
    at async TestCommandModule.handler (/home/projects/node-sxof7v/node_modules/@angular/cli/src/command-builder/command-module.js:101:24)
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.0-next.8
Node: 16.14.2
Package Manager: npm 7.17.0 
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.2
@angular-devkit/core         13.3.2
@angular-devkit/schematics   14.0.0-next.8
@angular/cli                 14.0.0-next.8
@schematics/angular          14.0.0-next.8
</code></pre>

**Anything else relevant?**

n/a

**Comment by alan-agius4** [comment]
Actually in this case in version 13, the first configuration argument was ignored. Multiple configurations must be passed comma separated.

```
 ng test --configuration lorem,ipsum
```
