### ISSUE TITLE
ng serve takes 40 seconds to recompile

### ISSUE THREAD

**Issue by ranmedina** [angular/angular-cli#22964]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

Related to https://github.com/angular/angular/issues/42799

I just upgraded Angular 11 to Angular 13, and it takes minimum of 40 seconds to recompile.
Our application is relatively big, and not the most efficient one. However, it worked pretty fine on Angular 11.

![image](https://user-images.githubusercontent.com/36334461/162623359-6e18509e-2a1c-4db9-a997-e65747eed2fd.png)

In my old project we used `NG_BUILD_IVY_LEGACY=1` and it drastically improved loading times - it doesn't work now though.

```true
Angular CLI: 13.3.2
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.3.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@schematics/angular             13.3.2
rxjs                            7.5.5
typescript                      4.6.3
```

**Comment by JoostK** [comment]
This sounds like https://github.com/angular/angular-cli/issues/20792#issuecomment-875932223. It may also be due to incremental type-checking, but it's impossible to tell without a reproduction.

**Comment by ranmedina** [comment]
@JoostK 

Thanks for your reply! 
I've read couple of similar issues and understood that this is probably not a CLI issue but a configuration one. 

Apparently, we were using a new local environment that didn't have any configuration besides `fileReplacement`. Adding the next configuration solves the issue:

```
            "local": {
              "optimization": false,
              "outputHashing": "all",
              "sourceMap": true,
              "namedChunks": true,
              "extractLicenses": false,
              "vendorChunk": true,
              "buildOptimizer": false,
              "budgets": [],
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.local.ts"
                }
              ]
            },
``` 

If anyone encounters this issue and see this comment, please make sure take a look at your `angular.json` configuration, the issue is probably there :)
