### ISSUE TITLE
Dev-server error after setting proxy.conf.json loglevel to "verbose"

### ISSUE THREAD

**Issue by i3ene** [angular/angular-cli#22969]
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular v12

### Description

As of the new WebPack version in Angular v13 I changed the ```logLevel``` inside my ```proxy.conf.json``` from ```debug``` to ```verbose```.
Since then I receive on ```ng serve```:
> An unhandled exception occured: Dev-server address info is not defined.

#### To Note

I work inside an Angular "workspace", so my apps are inside the "projects" folder.

Also (when I remove ```logLevel```, so that the Dev-Server starts) I receive duplicate requests on my API end.
Some of my URLs go to ```/api/proxy/my-service``` and after WebPack proxy it should look like ```http://localhost:3005/proxy/my-service```. But I also receive a second request on ```http://localhost:3005/my-service```? Does it have a problem with the keyword "proxy" inside URLs?

## 🔬 Minimal Reproduction

1. Create a new workspace with ```ng new my-workspace --create-application false```
2. Inside this workspace, create new app with ```ng generate application my-first-app```
3. Inside this application ```C://.../my-workspace/projects/my-first-app``` create a ```proxy.conf.json``` with something like 
```json
{
  "/api/*": {
    "pathRewrite": {"^/api": ""},
    "target": "http://localhost:3005",
    "logLevel": "verbose"
  }
}
```
4. Inside workspace, add to ```angular.json```:
```json
{
 ...
 "projects": {
  ...
  "my-first-app": {
   ...
   "serve": {
    ...
    "options": {
            "proxyConfig": "projects/my-first-app/proxy.conf.json"
    },
    ...
   }
  ...
  }
 ...
 }
...
}
```
5. Run ```ng serve my-first-app``` and observe

## 🔥 Exception or Error

<pre><code>
[error] Error: Dev-server address info is not defined.
    at C:\Users\...\my-workspace\node_modules\@angular-devkit\build-webpack\src\webpack-dev-server\index.js:63:27

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.2
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13.3.2
... animations, cdk, cli, common, compiler, compiler-cli, core    
... forms, material, platform-browser, platform-browser-dynamic   
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.3.2
ng-packagr                      13.3.0
rxjs                            7.5.5
typescript                      4.6.3
</code></pre>

Output of ```npm ls webpack-dev-server```:
<pre><code>
my-workspace@0.0.0 C:\Users\...\my-workspace
└─┬ @angular-devkit/build-angular@13.3.2
  ├─┬ @angular-devkit/build-webpack@0.1303.2
  │ └── webpack-dev-server@4.7.3 deduped
  └── webpack-dev-server@4.7.3
</code></pre>

**Comment by alan-agius4** [comment]
I looks like we are not emitting proxy config errors. 

`verbose` is not a valid value for `logLevel `.

https://github.com/chimurai/http-proxy-middleware#options
> option.logLevel: string, ['debug', 'info', 'warn', 'error', 'silent']. Default: 'info'

**Comment by i3ene** [comment]
Argh, sorry, my bad.
But it seems there is another issues (in general) with logging of proxy? Since ```"logLevel": "debug"``` doesn't log anything in console. Not even with ```ng serve my-first-app --verbose```

**Comment by i3ene** [comment]
Yeah, I wondered, because I also saw it being set up but did not see the active proxy output.
