### ISSUE TITLE
Just upgraded from Ng12 to Ng13 and JavaScript heap is always out of memory (tested at 40gb)

### ISSUE THREAD

**Issue by CSworenI** [angular/angular-cli#22977]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Partially. Some max_old_space_size settings automatically crashed before the upgrade, but now I can't serve or build my app at all.

In V12.2.9, I could serve and build my app with 10gb or more of max_old_space_size.

### Description

As previously mentioned, I have gone from 12.2.9 and being able to serve and build my app without issue to 13.3.2 and not being able to serve or build my app with up to 40gb of max_old_space_size.

So far, I have either gotten a mixture of scavenge and mark-sweep related messages about the JavaScript heap or when using multiples of 8gb (8192, 16384) and a couple other random memory limits, I get this error (with no other information):
`<--- Last few GCs --->

<--- JS stacktrace --->

#
# Fatal javascript OOM in GC during deserialization
#`

It's a fairly small sized app (<60mb w/o node modules) with a large amount of processing power. There's almost no starting data, but it pulls in large amounts of data (manufacturing schedules in up to 5 year horizons; average of 35 designs per scenario; 13 data parameters per design) and performs analysis and utilizes Excel libraries (mostly Infragistics) for display.

## 🔬 Minimal Reproduction

I am and have been running with `node --max_old_space_size=10240 --report-on-fatalerror node_modules/@angular/cli/bin/ng s -o` (up to 40000). I would suggest that a small app with a lot of processing power built in 12.2.9 and then upgraded to 13.3.2 would reproduce this issue. It may require using some Infragistics components (data-grid, spreadsheet, chart), but I'm not sure since I've had IG in my build since I started it about 1.5 years ago.

My package.json:
`{
    "name": "commits",
    "scripts": {
        "ng": "ng",
        "start": "node --max_old_space_size=40000 --report-on-fatalerror node_modules/@angular/cli/bin/ng s -o",
        "build": "node --max_old_space_size=10240 node_modules/@angular/cli/bin/ng b",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "clean": "rmdir /q/s node_modules",
        "reinstall": "npm run clean && npm i increase-memory-limit --legacy-peer-deps",
        "rebuild": "npm run clean && npm i --legacy-peer-deps && npm run build"
    },
    "private": true,
    "dependencies": {
        "@angular-devkit/build-optimizer": "^0.1202.17",
        "@angular/animations": "~13.3.2",
        "@angular/cdk": "^13.3.2",
        "@angular/common": "~13.3.2",
        "@angular/compiler": "~13.3.2",
        "@angular/core": "~13.3.2",
        "@angular/forms": "~13.3.2",
        "@angular/material": "^13.3.2",
        "@angular/platform-browser": "~13.3.2",
        "@angular/platform-browser-dynamic": "~13.3.2",
        "@angular/router": "~13.3.2",
        "@azure/msal-angular": "^2.2.0",
        "@azure/msal-browser": "^2.23.0",
        "@igniteui/material-icons-extended": "^2.11.0",
        "@infragistics/igniteui-angular": "~13.1.8",
        "@microsoft/microsoft-graph-client": "^3.0.2",
        "@microsoft/microsoft-graph-types": "^2.18.0",
        "bootstrap": "^5.1.3",
        "classlist.js": "1.1.20150312",
        "file-saver": "^2.0.5",
        "guid-typescript": "^1.0.9",
        "igniteui-angular-charts": "^13.1.1",
        "igniteui-angular-core": "^13.1.1",
        "igniteui-angular-excel": "^13.1.1",
        "igniteui-angular-spreadsheet": "^13.1.1",
        "increase-memory-limit": "^1.0.7",
        "jquery": "^3.6.0",
        "jszip": "^3.9.1",
        "minireset.css": "~0.0.7",
        "msal": "^1.4.16",
        "resize-observer-polyfill": "^1.5.1",
        "rxjs": "~7.5.5",
        "tslib": "^2.3.1",
        "web-animations-js": "^2.3.2",
        "zone.js": "~0.11.5"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^13.3.2",
        "@angular/cli": "^13.3.2",
        "@angular/compiler-cli": "~13.3.2",
        "@igniteui/angular-schematics": "~13.1.911",
        "@types/file-saver": "^2.0.5",
        "@types/hammerjs": "^2.0.41",
        "@types/jasmine": "~4.0.2",
        "@types/jquery": "^3.5.14",
        "@types/node": "^17.0.23",
        "codelyzer": "^6.0.2",
        "jasmine-core": "~4.0.1",
        "jasmine-spec-reporter": "~7.0.0",
        "karma": "~6.3.17",
        "karma-chrome-launcher": "~3.1.1",
        "karma-coverage": "~2.2.0",
        "karma-jasmine": "~4.0.2",
        "karma-jasmine-html-reporter": "^1.7.0",
        "protractor": "~7.0.0",
        "ts-node": "~10.7.0",
        "tslint": "~6.1.0",
        "typescript": "~4.6.3"
    }
}`

error report log (only using 1.73gb of memory):
`{
  "header": {
    "reportVersion": 2,
    "event": "Allocation failed - JavaScript heap out of memory",
    "trigger": "FatalError",
    "filename": "report.20220411.154217.23116.0.001.json",
    "dumpEventTime": "2022-04-11T15:42:17Z",
    "dumpEventTimeStamp": "1649716937092",
    "processId": 23116,
    "threadId": 0,
    "cwd": "C:\\Users\\csworen\\source\\repos\\Commits\\UI",
    "commandLine": [
      "node",
      "--max_old_space_size=16000",
      "--report-on-fatalerror",
      "node_modules/@angular/cli/bin/ng",
      "s"
    ],
    "nodejsVersion": "v16.13.0",
    "wordSize": 32,
    "arch": "ia32",
    "platform": "win32",
    "componentVersions": {
      "node": "16.13.0",
      "v8": "9.4.146.19-node.13",
      "uv": "1.42.0",
      "zlib": "1.2.11",
      "brotli": "1.0.9",
      "ares": "1.17.2",
      "modules": "93",
      "nghttp2": "1.45.1",
      "napi": "8",
      "llhttp": "6.0.4",
      "openssl": "1.1.1l+quic",
      "cldr": "39.0",
      "icu": "69.1",
      "tz": "2021a",
      "unicode": "13.0",
      "ngtcp2": "0.1.0-DEV",
      "nghttp3": "0.1.0-DEV"
    },
    "release": {
      "name": "node",
      "lts": "Gallium",
      "headersUrl": "https://nodejs.org/download/release/v16.13.0/node-v16.13.0-headers.tar.gz",
      "sourceUrl": "https://nodejs.org/download/release/v16.13.0/node-v16.13.0.tar.gz",
      "libUrl": "https://nodejs.org/download/release/v16.13.0/win-x86/node.lib"
    },
    "osName": "Windows_NT",
    "osRelease": "10.0.19044",
    "osVersion": "Windows 10 Enterprise",
    "osMachine": "i686",
    "cpus": [
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 1038484,
        "nice": 0,
        "sys": 1540937,
        "idle": 13208453,
        "irq": 160406
      },
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 839921,
        "nice": 0,
        "sys": 964437,
        "idle": 13983328,
        "irq": 16453
      },
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 1545906,
        "nice": 0,
        "sys": 1332734,
        "idle": 12909046,
        "irq": 14062
      },
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 1137937,
        "nice": 0,
        "sys": 1257250,
        "idle": 13392500,
        "irq": 10593
      },
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 1247468,
        "nice": 0,
        "sys": 1341546,
        "idle": 13198656,
        "irq": 16031
      },
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 1041234,
        "nice": 0,
        "sys": 1081984,
        "idle": 13664453,
        "irq": 12171
      },
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 1252171,
        "nice": 0,
        "sys": 1345484,
        "idle": 13190015,
        "irq": 11953
      },
      {
        "model": "11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz",
        "speed": 2995,
        "user": 1304843,
        "nice": 0,
        "sys": 1126812,
        "idle": 13356015,
        "irq": 9218
      }
    ],
    "networkInterfaces": [
      {
        "name": "Ethernet",
        "internal": false,
        "mac": "00:05:9a:3c:7a:00",
        "address": "10.212.177.158",
        "netmask": "255.255.240.0",
        "family": "IPv4"
      },
      {
        "name": "Wi-Fi",
        "internal": false,
        "mac": "84:14:4d:13:86:0c",
        "address": "192.168.1.196",
        "netmask": "255.255.255.0",
        "family": "IPv4"
      },
      {
        "name": "Loopback Pseudo-Interface 1",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "::1",
        "netmask": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff",
        "family": "IPv6",
        "scopeid": 0
      },
      {
        "name": "Loopback Pseudo-Interface 1",
        "internal": true,
        "mac": "00:00:00:00:00:00",
        "address": "127.0.0.1",
        "netmask": "255.0.0.0",
        "family": "IPv4"
      }
    ],
    "host": "csworen-mobl1"
  },
  "javascriptStack": {
    "message": "No stack.",
    "stack": [
      "Unavailable."
    ],
    "errorProperties": {
    }
  },
  "javascriptHeap": {
    "totalMemory": 1729368064,
    "totalCommittedMemory": 1729368064,
    "usedMemory": 1539078096,
    "availableMemory": 2208273816,
    "memoryLimit": 3917479936,
    "heapSpaces": {
      "read_only_space": {
        "memorySize": 139264,
        "committedMemory": 139264,
        "capacity": 127292,
        "used": 127292,
        "available": 0
      },
      "old_space": {
        "memorySize": 1441984512,
        "committedMemory": 1441984512,
        "capacity": 1280304304,
        "used": 1280056088,
        "available": 248216
      },
      "code_space": {
        "memorySize": 20799488,
        "committedMemory": 20799488,
        "capacity": 14030368,
        "used": 14030368,
        "available": 0
      },
      "map_space": {
        "memorySize": 2895872,
        "committedMemory": 2895872,
        "capacity": 1762720,
        "used": 1762720,
        "available": 0
      },
      "large_object_space": {
        "memorySize": 246222848,
        "committedMemory": 246222848,
        "capacity": 242595996,
        "used": 242595996,
        "available": 0
      },
      "code_large_object_space": {
        "memorySize": 548864,
        "committedMemory": 548864,
        "capacity": 505632,
        "used": 505632,
        "available": 0
      },
      "new_large_object_space": {
        "memorySize": 0,
        "committedMemory": 0,
        "capacity": 8121856,
        "used": 0,
        "available": 8121856
      },
      "new_space": {
        "memorySize": 16777216,
        "committedMemory": 16777216,
        "capacity": 8121856,
        "used": 0,
        "available": 8121856
      }
    }
  },
  "nativeStack": [
  ],
  "resourceUsage": {
    "userCpuSeconds": 85.296,
    "kernelCpuSeconds": 12.531,
    "cpuConsumptionPercent": 134.01,
    "maxRss": 1925529600,
    "pageFaults": {
      "IORequired": 874282,
      "IONotRequired": 0
    },
    "fsActivity": {
      "reads": 15175,
      "writes": 531
    }
  },
  "libuv": [
    {
      "type": "async",
      "is_active": true,
      "is_referenced": false,
      "address": "0x0000000003f619d8"
    },
    {
      "type": "async",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000000035cfeb0"
    },
    {
      "type": "timer",
      "is_active": true,
      "is_referenced": true,
      "address": "0x00000000065a2dc8",
      "repeat": 0,
      "firesInMsFromNow": 32,
      "expired": false
    },
    {
      "type": "check",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000000065a2e28"
    },
    {
      "type": "idle",
      "is_active": true,
      "is_referenced": true,
      "address": "0x00000000065a2e64"
    },
    {
      "type": "prepare",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000000065a2ea0"
    },
    {
      "type": "check",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000000065a2edc"
    },
    {
      "type": "async",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000000065a2f18"
    },
    {
      "type": "async",
      "is_active": true,
      "is_referenced": false,
      "address": "0x00000000035cfe10"
    },
    {
      "type": "tty",
      "is_active": false,
      "is_referenced": true,
      "address": "0x00000000066aca78",
      "width": 235,
      "height": 17,
      "writeQueueSize": 0,
      "readable": false,
      "writable": true
    },
    {
      "type": "signal",
      "is_active": true,
      "is_referenced": false,
      "address": "0x0000000006875b70",
      "signum": 28,
      "signal": "SIGWINCH"
    },
    {
      "type": "tty",
      "is_active": false,
      "is_referenced": true,
      "address": "0x00000000066a7f90",
      "width": 235,
      "height": 17,
      "writeQueueSize": 0,
      "readable": false,
      "writable": true
    },
    {
      "type": "tty",
      "is_active": false,
      "is_referenced": true,
      "address": "0x00000000066b2638",
      "writeQueueSize": 0,
      "readable": true,
      "writable": false
    },
    {
      "type": "signal",
      "is_active": true,
      "is_referenced": false,
      "address": "0x000000000673a8f0",
      "signum": 2,
      "signal": "SIGINT"
    },
    {
      "type": "signal",
      "is_active": true,
      "is_referenced": false,
      "address": "0x000000000673a9c0",
      "signum": 15,
      "signal": "SIGTERM"
    },
    {
      "type": "tcp",
      "is_active": true,
      "is_referenced": true,
      "address": "0x00000000071c7d98",
      "localEndpoint": {
        "host": "csworen-mobl1.amr.corp.intel.com",
        "port": 4200
      },
      "remoteEndpoint": null,
      "sendBufferSize": 65536,
      "recvBufferSize": 65536,
      "writeQueueSize": 0,
      "readable": false,
      "writable": false
    },
    {
      "type": "pipe",
      "is_active": false,
      "is_referenced": false,
      "address": "0x0000000044746030",
      "localEndpoint": null,
      "remoteEndpoint": "\\\\?\\pipe\\uv\\FFFFFFFF-23116",
      "writeQueueSize": 0,
      "readable": true,
      "writable": true
    },
    {
      "type": "pipe",
      "is_active": true,
      "is_referenced": false,
      "address": "0x0000000044745270",
      "localEndpoint": null,
      "remoteEndpoint": "\\\\?\\pipe\\uv\\00000000-23116",
      "writeQueueSize": 0,
      "readable": true,
      "writable": true
    },
    {
      "type": "process",
      "is_active": true,
      "is_referenced": false,
      "address": "0x0000000003f8a3a0",
      "pid": 13924
    },
    {
      "type": "timer",
      "is_active": true,
      "is_referenced": false,
      "address": "0x0000000003ff7b78",
      "repeat": 0,
      "firesInMsFromNow": 3441,
      "expired": false
    },
    {
      "type": "loop",
      "is_active": true,
      "address": "0x0000000003859c90",
      "loopIdleTimeSeconds": 0.0058206
    }
  ],
  "workers": [
  ],
  "environmentVariables": {
    "=C:": "C:\\Users\\csworen\\source\\repos\\Commits\\UI",
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "APPDATA": "C:\\Users\\csworen\\AppData\\Roaming",
    "ATERNITY_AGENT_HOME": "C:\\Program Files (x86)\\Aternity Information Systems\\Agent\\",
    "BROWSERSLIST_IGNORE_OLD_DATA": "1",
    "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_2500_ONGTCPGFDBVGORDW",
    "COLOR": "1",
    "COLORTERM": "truecolor",
    "CommonProgramFiles": "C:\\Program Files (x86)\\Common Files",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "COMPUTERNAME": "CSWOREN-MOBL1",
    "ComSpec": "C:\\windows\\system32\\cmd.exe",
    "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
    "EDITOR": "notepad.exe",
    "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
    "FPS_BROWSER_USER_PROFILE_STRING": "Default",
    "GIT_ASKPASS": "c:\\Users\\csworen\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
    "HOME": "C:\\Users\\csworen",
    "HOMEDRIVE": "C:",
    "HOMEPATH": "\\Users\\csworen",
    "INIT_CWD": "C:\\Users\\csworen\\source\\repos\\Commits\\UI",
    "Intellogs": "C:\\Intel\\Logs",
    "LANG": "en_US.UTF-8",
    "LOCALAPPDATA": "C:\\Users\\csworen\\AppData\\Local",
    "LOGONSERVER": "\\\\ORSAMR606",
    "NODE": "C:\\Program Files (x86)\\nodejs\\node.exe",
    "NODE_EXE": "C:\\Program Files (x86)\\nodejs\\\\node.exe",
    "NPM_CLI_JS": "C:\\Users\\csworen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
    "npm_command": "start",
    "npm_config_cache": "C:\\Users\\csworen\\AppData\\Local\\npm-cache",
    "npm_config_email": "chris.sworen@intel.com",
    "npm_config_globalconfig": "C:\\Users\\csworen\\AppData\\Roaming\\npm\\etc\\npmrc",
    "npm_config_global_prefix": "C:\\Users\\csworen\\AppData\\Roaming\\npm",
    "npm_config_init_module": "C:\\Users\\csworen\\.npm-init.js",
    "npm_config_local_prefix": "C:\\Users\\csworen\\source\\repos\\Commits\\UI",
    "npm_config_metrics_registry": "https://registry.npmjs.org/",
    "npm_config_node_gyp": "C:\\Users\\csworen\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
    "npm_config_noproxy": "",
    "npm_config_prefix": "C:\\Users\\csworen\\AppData\\Roaming\\npm",
    "npm_config_userconfig": "C:\\Users\\csworen\\.npmrc",
    "npm_config_user_agent": "npm/8.1.4 node/v16.13.0 win32 ia32 workspaces/false",
    "npm_execpath": "C:\\Users\\csworen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
    "npm_lifecycle_event": "start",
    "npm_lifecycle_script": "node --max_old_space_size=16000 --report-on-fatalerror node_modules/@angular/cli/bin/ng s",
    "npm_node_execpath": "C:\\Program Files (x86)\\nodejs\\node.exe",
    "npm_package_json": "C:\\Users\\csworen\\source\\repos\\Commits\\UI\\package.json",
    "npm_package_name": "commits",
    "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\csworen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
    "NUMBER_OF_PROCESSORS": "8",
    "OneDrive": "C:\\Users\\csworen\\OneDrive - Intel Corporation",
    "OneDriveCommercial": "C:\\Users\\csworen\\OneDrive - Intel Corporation",
    "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
    "OS": "Windows_NT",
    "Path": "C:\\Users\\csworen\\source\\repos\\Commits\\UI\\node_modules\\.bin;C:\\Users\\csworen\\source\\repos\\Commits\\node_modules\\.bin;C:\\Users\\csworen\\source\\repos\\node_modules\\.bin;C:\\Users\\csworen\\source\\node_modules\\.bin;C:\\Users\\csworen\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Users\\csworen\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Oracle11gR2_x32\\product\\11.2.0\\client_1\\bin;C:\\app\\csworen\\product\\19.0.0\\client_1;C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\wbin;C:\\windows\\system32;C:\\windows;C:\\windows\\System32\\Wbem;C:\\windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Microsoft SQL Server\\150\\DTS\\Binn\\;C:\\Program Files\\Azure Data Studio\\bin;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files (x86)\\PuTTY\\;C:\\Program Files (x86)\\nodejs\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\120\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\130\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\140\\DTS\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Users\\csworen\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\csworen\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files\\Azure Data Studio\\bin;C:\\Users\\csworen\\AppData\\Roaming\\npm;C:\\Users\\csworen\\.dotnet\\tools",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
    "PROCESSOR_ARCHITECTURE": "x86",
    "PROCESSOR_ARCHITEW6432": "AMD64",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 140 Stepping 1, GenuineIntel",
    "PROCESSOR_LEVEL": "6",
    "PROCESSOR_REVISION": "8c01",
    "ProgramData": "C:\\ProgramData",
    "ProgramFiles": "C:\\Program Files (x86)",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "ProgramW6432": "C:\\Program Files",
    "PROMPT": "$P$G",
    "PSModulePath": "C:\\Users\\csworen\\OneDrive - Intel Corporation\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
    "PUBLIC": "C:\\Users\\Public",
    "SESSIONNAME": "Console",
    "STEELCENTRAL_ATERNITY_AGENT_HOME": "C:\\Program Files (x86)\\Aternity Information Systems\\Agent\\",
    "SystemDrive": "C:",
    "SystemRoot": "C:\\windows",
    "TEMP": "C:\\Users\\csworen\\AppData\\Local\\Temp",
    "TERM_PROGRAM": "vscode",
    "TERM_PROGRAM_VERSION": "1.66.1",
    "TMP": "C:\\Users\\csworen\\AppData\\Local\\Temp",
    "UATDATA": "C:\\windows\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77",
    "USERDNSDOMAIN": "AMR.CORP.INTEL.COM",
    "USERDOMAIN": "AMR",
    "USERDOMAIN_ROAMINGPROFILE": "AMR",
    "USERNAME": "csworen",
    "USERPROFILE": "C:\\Users\\csworen",
    "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
    "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\csworen\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
    "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\csworen\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
    "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-37edf79619-sock",
    "WEBPACK_SERVE": "true",
    "windir": "C:\\windows",
    "ZES_ENABLE_SYSMAN": "1",
    "_JAVA_OPTIONS": "-Djava.net.preferIPv4Stack=true"
  },
  "sharedObjects": [
    "C:\\Program Files (x86)\\nodejs\\node.exe",
    "C:\\windows\\SYSTEM32\\ntdll.dll",
    "C:\\windows\\System32\\KERNEL32.DLL",
    "C:\\windows\\System32\\KERNELBASE.dll",
    "C:\\windows\\System32\\WS2_32.dll",
    "C:\\windows\\System32\\RPCRT4.dll",
    "C:\\windows\\SYSTEM32\\dbghelp.dll",
    "C:\\windows\\System32\\PSAPI.DLL",
    "C:\\windows\\System32\\ucrtbase.dll",
    "C:\\windows\\System32\\ADVAPI32.dll",
    "C:\\windows\\System32\\msvcrt.dll",
    "C:\\windows\\SYSTEM32\\USERENV.dll",
    "C:\\windows\\System32\\sechost.dll",
    "C:\\windows\\SYSTEM32\\IPHLPAPI.DLL",
    "C:\\windows\\System32\\USER32.dll",
    "C:\\windows\\System32\\win32u.dll",
    "C:\\windows\\System32\\GDI32.dll",
    "C:\\windows\\System32\\gdi32full.dll",
    "C:\\windows\\System32\\msvcp_win.dll",
    "C:\\windows\\System32\\CRYPT32.dll",
    "C:\\windows\\System32\\bcrypt.dll",
    "C:\\windows\\SYSTEM32\\WINMM.dll",
    "C:\\windows\\SYSTEM32\\CRYPTBASE.DLL",
    "C:\\windows\\System32\\IMM32.DLL",
    "C:\\windows\\SYSTEM32\\powrprof.dll",
    "C:\\windows\\SYSTEM32\\UMPDC.dll",
    "C:\\windows\\system32\\uxtheme.dll",
    "C:\\windows\\System32\\combase.dll",
    "C:\\windows\\system32\\mswsock.dll",
    "C:\\windows\\SYSTEM32\\kernel.appcore.dll",
    "C:\\windows\\System32\\bcryptprimitives.dll",
    "C:\\windows\\System32\\NSI.dll",
    "C:\\windows\\SYSTEM32\\dhcpcsvc6.DLL",
    "C:\\windows\\SYSTEM32\\dhcpcsvc.DLL",
    "C:\\windows\\SYSTEM32\\DNSAPI.dll",
    "C:\\Windows\\System32\\rasadhlp.dll",
    "C:\\windows\\System32\\fwpuclnt.dll",
    "C:\\windows\\system32\\napinsp.dll",
    "C:\\windows\\system32\\pnrpnsp.dll",
    "C:\\windows\\system32\\wshbth.dll",
    "C:\\windows\\system32\\NLAapi.dll",
    "C:\\windows\\System32\\winrnr.dll"
  ]
}`

## 🔥 Exception or Error
Build error:
`Generating browser application bundles (phase: building)...
<--- Last few GCs --->

[23040:04804DB8]    83178 ms: Scavenge 1595.3 (1666.1) -> 1594.2 (1669.4) MB, 1280.3 / 0.0 ms  (average mu = 0.942, current mu = 0.959) allocation failure
[23040:04804DB8]    84766 ms: Scavenge 1598.4 (1669.4) -> 1597.3 (1672.6) MB, 1557.0 / 0.0 ms  (average mu = 0.942, current mu = 0.959) allocation failure
[23040:04804DB8]    85051 ms: Scavenge 1601.5 (1672.6) -> 1600.5 (1675.6) MB, 261.8 / 0.0 ms  (average mu = 0.942, current mu = 0.959) allocation failure

<--- JS stacktrace --->

FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory`

Serve error:
`
****************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.
It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
⠙ Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries:
Encourage the library authors to publish an Ivy distribution.
⠇ Generating browser application bundles (phase: building)...
<--- Last few GCs --->

[23116:03F63BB0]    71028 ms: Scavenge 1567.8 (1635.2) -> 1566.7 (1639.0) MB, 190.0 / 0.0 ms  (average mu = 0.898, current mu = 0.000) allocation failure
[23116:03F63BB0]    71293 ms: Scavenge 1571.5 (1639.0) -> 1570.3 (1642.0) MB, 252.6 / 0.0 ms  (average mu = 0.898, current mu = 0.000) allocation failure
[23116:03F63BB0]    71576 ms: Scavenge 1575.0 (1642.3) -> 1573.6 (1645.8) MB, 270.3 / 0.0 ms  (average mu = 0.898, current mu = 0.000) allocation failure

<--- JS stacktrace --->

FATAL ERROR: NewSpace::Rebalance Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20220411.154217.23116.0.001.json
Node.js report completed`

## 🌍 Your Environment
`Angular CLI: 13.3.2
Node: 16.13.0
Package Manager: npm 8.1.4
OS: win32 ia32

Angular: 13.3.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1303.2
@angular-devkit/build-angular     13.3.2
@angular-devkit/build-optimizer   0.1202.17
@angular-devkit/core              13.3.2
@angular-devkit/schematics        13.3.2
@schematics/angular               13.3.2
rxjs                              7.5.5
typescript                        4.6.3`

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Hi @CSworenI, unfortunately without a memory snapshot or a reproduction this isn't anything that we can look at.

**Comment by alan-agius4** [comment]
Closing due to lack for information.
