### ISSUE TITLE
Angular cache not updated when installing packed dependency (.tgz)

### ISSUE THREAD

**Issue by TJMaria** [angular/angular-cli#22982]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Introduced after upgrading from angular 10 to 13 (when cache was introduced)

### Description

 
When packaging a local angular library using `npm pack` and installing it in another angular project, the changes aren't shown until the cache is deleted. Is it possible that the angular cache doesn't recognize installing a packed dependency (.tgz) as a trigger to update the cache?

## 🔬 Minimal Reproduction

Angular library with components:
1. update css
2. package using npm pack

App project:
1. install dependency: npm i <path>/library.tgz
2. npm start
3. css changes not shown.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.2.6
Node: 16.12.0
Package Manager: <error>
OS: win32 x64

Angular: 13.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@angular/cdk                    13.2.1
@schematics/angular             13.2.2
ng-packagr                      13.3.0
rxjs                            7.5.4
typescript                      4.5.5

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
This is working as expected. 

Please see: https://github.com/angular/angular-cli/issues/22380

**Comment by TJMaria** [comment]
Ok thanks. I thought maybe it was packed dependency specific. It would be nice if this caveat was added to the angular cli cache docs, this is lacking detail at the moment.
