### ISSUE TITLE
ng destroy component does not remove component from app.module.ts file

### ISSUE THREAD

**Issue by Lasagna220** [angular/angular-cli#2299]
1. Operating System:
Mac OSX 0.11.6  El Capitan

2. Version:
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64

3. Steps to reproduce
`ng new new-app; cd new-app/src/app`
`ng g component foo`
`ng destroy component foo`
Notice that the src/app/app.module.ts file still has references to the foo component.

**Comment by Gutorov** [comment]
Hey, Im have same issue but cant find any info(

**Comment by filipesilva** [comment]
The `ng destroy` command isn't supported. It doesn't show in `ng help` anymore as well.

**Comment by MohamadAtieh** [comment]
@filipesilva What's the best way to destroy a generated component or directive then?

**Comment by mihailvalchev** [comment]
+1
How do we delete components properly if not with ``ng destroy``?

**Comment by filipesilva** [comment]
In my experience the best way is to use git to figure out what was added. It's usually easy to figure out the new files, but not so easy to figure out the added imports.

We've talked about how generators maybe shouldn't auto-add the imports, but haven't decided if it's worth to change it.

**Comment by MohamadAtieh** [comment]
@filipesilva Maybe list the files edited on generating new components + the new files?

**Comment by filipesilva** [comment]
That's a really good idea @MohamadAtieh. We list the *created* files but don't list the edited ones. I'll make an issue for it.
