### ISSUE TITLE
Angular2 Projects' initial commit message can contain more information

### ISSUE THREAD

**Issue by rodyhaddad** [angular/angular-cli#23]
Currently the initial commit message of newly generated projects is just [one line](https://github.com/angular/angular-cli/blob/master/addon/ng2/utilities/INITIAL_COMMIT_MESSAGE.txt).

We can expand this to links pointing to where issues can be reported, where to get help for Angular2 or the CLI tool, etc.

We can also include ASCII art [like ember-cli](https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/COMMIT_MESSAGE.txt).

This is just a nice to have.

**Comment by hansl** [comment]
I assume this is done and I'm closing it.
