### ISSUE TITLE
feat: add support for environment-based build pipeline

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular-cli#230]
In #215, where AppCache/ServiceWorker support was implemented, the feature was limited because there was no way to differentiate between a build for dev and a build for prod inside `lib/broccoli/angular2-app.js`. 

The service worker or app cache should not be installed for dev builds by default, since it would interfere with rapid change app > reload > repeat lifecycle.

I'm just opening this issue for discussion/tracking of allowing different behavior for different environments; I don't have a proposed design. Given that dev and prod builds should _generally_ not exhibit different behavior, this design should have good constraints to discourage abuse.

**Comment by cironunes** [comment]
I'm looking into this, but didn't make much progress yet.

**Comment by hansl** [comment]
I'll close this in favor of https://github.com/angular/angular-cli/issues/41. Cirocunes is already working on this.
