### ISSUE TITLE
New Command in order to list all available blueprints

### ISSUE THREAD

**Issue by Gillespie59** [angular/angular-cli#2300]
> Please provide us with the following information:
> ---------------------------------------------------------------

In order to know all available blueprints (service, component, class, pipe, ...), the only (I think), is to checkout the blueprints folder on Github. Am i right ? 

It should be interesting to add a new command in order to list these blueprints to the user, in order to know which element we can generate from angular-cli. 

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by feloy** [comment]
Is the following command doing what you describe?

$ ng --help generate

**Comment by filipesilva** [comment]
`ng --help generate` partially does it, but also lists a lot of stuff we don't actually support.

**Comment by Brocco** [comment]
For some reason there's a difference when running `ng --help generate` vs `ng generate --help` the former is controlled by ember-cli while the later allows our addon (the angular-cli) to override the generate command.
