### ISSUE TITLE
Add a default prompt to run `ng completion`

### ISSUE THREAD

**Issue by twerske** [angular/angular-cli#23003]
# 🚀 Feature request

### Command (mark with an `x`)

Prompt on any CLI without ng completion that hasn't been prompted before to run `ng completion` by default.

### Description

`ng completion` is the autocomplete feature I've always wanted, to improve CLI discoverability, prevent typos, and in general provide a better developer experience.

Adding this as a default prompt to CLI v14 users who have not run it yet helps make this improvement more built-in to the CLI instead of needing to advertise it and make it discoverable itself. This will greatly increase the number of developers who benefit from autocompletion.

### Describe the solution you'd like

Prompt CLI users to add completion and autocomplete to their `.bashrc`, `.bash_profile`, `.zshrc` or `.zsh_profile` by default (with user consent).

Angular team internal discussion here: [Thread](https://angular-team.slack.com/archives/C46U16D4Z/p1650310374177409)
Related PR here: https://github.com/angular/angular-cli/pull/22967

**Comment by dgp1130** [comment]
The base implementation is done, but we forgot about Windows which doesn't support this kind of autocompletion. I want to set up some tests to make sure these changes don't break the CLI on Windows, we don't prompt Windows users, and `ng completion` should fail with a clear message on Windows platforms.

**Comment by dgp1130** [comment]
Landed a Windows-specific error message in #23075. Didn't quite make the `14.0.0-next.13` cutoff, but should be in `14.0.0-rc.0`.
