### ISSUE TITLE
Angular 13 extractLicenses option doesnt work

### ISSUE THREAD

**Issue by mreorhan** [angular/angular-cli#23007]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 No

### Description

 After a few upgrade Angular, I realized that the 3rdpartylicenses generates nothing after the build. I also pass --extract-licenses=true flag to the ng build script.

angular.json
build.configurations.extractLicenses: true
## 🔥 Exception or Error

<pre>
There are no error, just this information:
3rdpartylicenses.txt
DEVELOPMENT MODE - LICENCES WILL SHOW UP AFTER PRODUCTION COMPILE<code>

</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 13.3.3
Node: 14.19.1
Package Manager: npm 6.14.16
OS: darwin x64

Angular: 13.3.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@schematics/angular             13.3.3
rxjs                            6.6.7
typescript                      4.6.3
</code></pre>

**Anything else relevant?**

**Comment by clydin** [comment]
Unfortunately, we are unable to replicate the issue as described.
Can you please provide a minimal reproduction that demonstrates the problem?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
