### ISSUE TITLE
angluar-cli is not FIPS Compatible

### ISSUE THREAD

**Issue by shawnweeks** [angular/angular-cli#23011]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

Much like https://github.com/angular/angular/issues/42577 the angular-cli also uses md5 hashes and fails to run a build on a Red Hat(Rocky) 8 system with FIPs enabled.

## 🔬 Minimal Reproduction

On a Red Hat(Rocky) 8

<pre><code>
# Enable FIPS Mode and Reboot
sudo fips-mode-setup --enable
sudo reboot now
# Install Red Hat 8 Node JS 16
sudo dnf module install nodejs:16

ng new my-app
cd my-app
# Fix FIPS issue in babel-loader
sed -i'' 's~md4\|md5~sha256~g' node_modules/babel-loader/lib/cache.js
ng build
</code></pre>

## 🔥 Exception or Error

<pre><code>
./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
    at /home/sweeks/Projects/my-app/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS
    at /home/sweeks/Projects/my-app/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.3
Node: 16.13.1
Package Manager: npm 8.7.0
OS: linux x64

Angular: 13.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@schematics/angular             13.3.3
rxjs                            7.5.5
typescript                      4.6.3
</code></pre>

**Anything else relevant?**

**Comment by shawnweeks** [comment]
Replacing md5 in the following files seems to resolve the issue so this should be fairly easy to fix.

```
sed -i'' 's~md5~sha256~g' node_modules/@ngtools/webpack/src/resource_loader.js
sed -i'' 's~md5~sha256~g' node_modules/@ngtools/webpack/src/ivy/plugin.js
```

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/23039/
