### ISSUE TITLE
How to include a ngModule in development but not for bundled in production

### ISSUE THREAD

**Issue by mattma** [angular/angular-cli#2303]
This is really a question, not an issue. 

I want to use an angular module for development only, and this module won't be included in the production build. Let me explain a little more,

For example, I use `ngrx/store` to manage my application state, then I use its development toolkit called [store-log-monitor](https://github.com/ngrx/store-log-monitor). I have setup my module following [this guide](https://github.com/ngrx/store-log-monitor#setup)

This module is ONLY used in development, to provide a visualization for application state, I would never ship it in the production build so that I use `environment.production` variable to check the current environment.

What I did in two different places. 

1> setup an local typescript private variable 'private env: environment.production' at file `app.component.ts`so that I could use it in my template `app.component.html` like this `<ngrx-store-log-monitor *ngIf="env"></ngrx-store-log-monitor>`

2> in `app.module.ts` file, I use the condition to check the current environment, to include the `StoreLogMonitorModule` and `StoreDevtoolsModule`. 

It is all good. but I put `store-log-monitor` module in `npm` `package.json` `devDependencies` object. In production build, it won't include this module. So that I put the condition on `import` statement. But the problem is that in ES2015 import statement cannot be wrapped inside a condition. It will raise an error here.

```
if (environment.production) {
  import { StoreDevtoolsModule } from '@ngrx/store-devtools';
  import { StoreLogMonitorModule, useLogMonitor } from '@ngrx/store-log-monitor';
}
```

Is there a better/clean way to handle building in production to not include the "development" related modules by using `ng build -prod` ?

**Comment by monojack** [comment]
Is it possible to abstract everything about this module so that none of the other modules or components reference anything it it? Like making it a separate route, lazy-load the module and then just comment the route before running `ng build`?

**Comment by mattma** [comment]
@monojack Sounds like an eligible idea. But I do not want to remember to comment out the module everytime that I do an development. If I want to deploy three a day, I have to have three extra PRs before each deployment.

**Comment by bonnici** [comment]
You should be able to do something like add a flag in your environment.ts to restrict access to the lazy-loaded module, then it won't be accessible in prod and it will never be loaded.

**Comment by mattma** [comment]
@bonnici Is there a code example anywhere for this kind of things?

If I have this dev-tool-monitor (development only module) in my `app.component.html`, which is the entry component. This component won't never be lazy loaded. Does it fall into that category?

**Comment by bonnici** [comment]
The official docs have some info on [lazy-loaded modules](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load) and the [can-activate guard](https://angular.io/docs/ts/latest/guide/router.html#!#can-activate-guard) you could use to restrict access. It sounds like you'd need to do a bit of restructuring to get it to work.

**Comment by filipesilva** [comment]
You can use the environment files functionality to have a file that's conditional on your environment. That comes with a caveat though: files must have the same external interface otherwise typechecking breaks.

See https://github.com/angular/angular-cli#build-targets-and-environment-files
