### ISSUE TITLE
Support font-inlining for global styles

### ISSUE THREAD

**Issue by twerske** [angular/angular-cli#23054]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] build

### Description

Currently, font inlining only works for font that are declared in the `index.html`.
 
```html
<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
```

However, fonts can also be imported in CSS files using the `@import` rule. 

```css
@import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap");
``` 

We should probably handle both cases.

**Comment by mgechev** [comment]
Ideally we'd like to keep the font inlining as an implementation detail and hide it from developers. Can we discover all the fonts in global styles/index.html and inline them?

**Comment by alan-agius4** [comment]
We already automatically inline all the Google and Adobe fonts found in the index.html.

Not entirely sure, what is being requested here.

**Comment by twerske** [comment]
This would be the same but for fonts found in `styles.css` and style files.

Additionally @jelbourn and I discussed a schematic for `ng add --font-inlining <font family>`

**Comment by alan-agius4** [comment]
Following a convo with @twerske on Slack, this request is to enable font-inline of fonts in global stylesheets. (I have update the issue to reflect this).

Regarding @jelbourn request, I am still not sure what it being requested. I also suggest that we keep one feature per issue as it would be easier to track.

**Comment by alan-agius4** [comment]
@twerske is this something that we still want to persue?
