### ISSUE TITLE
Provide an ability to tree-shake the code but avoid symbol renaming

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular-cli#23062]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] build

### Description

In order to investigate bundle size issues in a CLI app, it'd be very helpful to have an ability to apply tree-shaking (dead code elimination), but retain symbol names in the output, so that it's easier to figure out which code is retained and why. If I understand correctly, the `NG_BUILD_DEBUG_OPTIMIZE` doesn't provide an ability to configure `ng build` in this way.

**Comment by alan-agius4** [comment]
@AndrewKushnir, are you disabling the cache?

```
ng config cli.cache.enabled false
```

**Comment by AndrewKushnir** [comment]
@alan-agius4 thanks for the reply! The `NG_BUILD_DEBUG_OPTIMIZE` flag worked after disabling the cache :)

Just curious: do we take the `NG_BUILD_DEBUG_OPTIMIZE` flag (and its value) into account when we calculate the cache key?

(closing the ticket since the original issue is resolved)

**Comment by alan-agius4** [comment]
> Just curious: do we take the NG_BUILD_DEBUG_OPTIMIZE flag (and its value) into account when we calculate the cache key?

No, maybe we should.
