### ISSUE TITLE
Unable to resolve migrations for package

### ISSUE THREAD

**Issue by bmayen** [angular/angular-cli#23068]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
^12.0.0

### Description

 A clear and concise description of the problem...
I opened this issue for @angular/cdk https://github.com/angular/components/issues/24862, but I think this may instead be a CLI issue.

I have custom schematics that include @angular/cdk in the package.json "packageGroup". When running `ng update my-custom-schematics` I get the following error:

Unable to resolve migrations for package (@angular/cdk). [Package subpath '././schematics/migration.json' is not defined by "exports" in [project root]/node_modules/@angular/cdk/package.json]

At first I assumed this was an issue with CDK's package.json. However, this seems to work fine if I call `ng update` specifically for @angular/cdk. When updating through my custom schematics though, note the double '././' path reference in '././schematics/migration.json'. Looks like packagePath is not getting set properly and we're catching the exception here: https://github.com/angular/angular-cli/blob/1c634cd327e5a850553b258aa2d5e6a6b2c75c65/packages/angular/cli/src/commands/update/cli.ts#L494.

## 🔥 Exception or Error

<pre><code>

Unable to resolve migrations for package (@angular/cdk). [Package subpath '././schematics/migration.json' is not defined by "exports" in [project root]/node_modules/@angular/cdk/package.json]
</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by bmayen** [comment]
FYI, I'm actually running `npx ng update my-custom-schematics` because I don't have CLI installed globally.

So, if I run `npx ng version`, I get:
```
Angular CLI: 12.2.17
Node: 12.22.7
Package Manager: npm 8.2.0
OS: darwin x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.17
@angular-devkit/build-angular      12.2.17
@angular-devkit/core               12.2.17
@angular-devkit/schematics         12.2.17
@angular/cdk                       12.2.13
@angular/cli                       12.2.17
@angular/material                  12.2.13
@angular/material-moment-adapter   12.2.13
@schematics/angular                12.2.17
rxjs                               6.5.5
typescript                         4.3.5
```

I've also tried `npx -p @angular/cli@13 ng update my-custom-schematics` but get the same error.
`npx -p @angular/cli@13 ng version` yields:
```
Angular CLI: 13.3.4
Node: 12.22.7
Package Manager: npm 8.2.0
OS: darwin x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1202.17
@angular-devkit/build-angular      12.2.17
@angular-devkit/core               12.2.17
@angular-devkit/schematics         13.3.4
@angular/cdk                       12.2.13
@angular/cli                       13.3.4
@angular/material                  12.2.13
@angular/material-moment-adapter   12.2.13
@schematics/angular                13.3.4
rxjs                               6.5.5
typescript                         4.3.5

**Comment by bmayen** [comment]
Looks like if I manually install CLI at v13 globally and then run `ng update my-custom-schematic`, I don't get the error. Only happens with `npx ng update my-custom-schematic`.

**Comment by alan-agius4** [comment]
As far as I recall using npx `-p` will cause the version specifier to not be used, at least I remember several issues in the past about this.

Can you try to use the below command.

```
npx @angular/cli@13 update my-custom-schematics
```

**Comment by bmayen** [comment]
That doesn't work either. Same error. Looks like some discrepancy in the path resolution when npx installs a temporary version, vs if I have it installed globally.

**Comment by bmayen** [comment]
I don't know if this would make a difference, but I'm also using NVM to manage different Node versions. Perhaps an issue with that and npx?

**Comment by alan-agius4** [comment]
Unfortunately, without a reproduction it's hard to tell what is happening here. Can you please setup a minimal reproduction?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).
