### ISSUE TITLE
Uncaught Error: Cannot find module "../fonts/fontawesome-webfont.eot?v=4.6.3"

### ISSUE THREAD

**Issue by LucasReSilva** [angular/angular-cli#2309]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
 Microsoft Windows 10 Pro 10.0.10586

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
I put the styles on app's scss and works fine.
I put the styles on styles.scss, modify the paths, but i got (Uncaught Error: Cannot find module "../fonts/fontawesome-webfont.eot?v=4.6.3")

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ERROR in ./src/app/app.component.scss
Module build failed:
@import "../style";
^
      File to import not found or unreadable: ../style
Parent style sheet: stdin
      in (My Project)\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/app.component.ts 51:21-52
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/common/button/button.component.scss
Module build failed:
@import "../style";
^
      File to import not found or unreadable: ../style
Parent style sheet: (My Project)/src/app/app.component.scss
      in (My Project)\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/common/button/button.component.ts 28:21-55
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/common/login/login.component.scss
Module build failed:
@import "../style";
^
      File to import not found or unreadable: ../style
Parent style sheet: (My Project)/src/app/app.component.scss
      in (My Project)\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/common/login/login.component.ts 43:21-54
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/activities/description/description.component.scss
Module build failed:
@import "../style";
^
      File to import not found or unreadable: ../style
Parent style sheet: (My Project)/src/app/app.component.scss
      in (My Project)\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/activities/description/description.component.ts 45:21-60
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/activities/multi-choice/multi-choice.component.scss
Module build failed:
@import "../style";
^
      File to import not found or unreadable: ../style
Parent style sheet: (My Project)/src/app/app.component.scss
      in (My Project)\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/activities/multi-choice/multi-choice.component.ts 103:21-61
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/activities/activity/activity.component.scss
Module build failed:
@import "../style";
^
      File to import not found or unreadable: ../style
Parent style sheet: (My Project)/src/app/app.component.scss
      in (My Project)\src\app\app.component.scss (line 1, column 1)
 @ ./src/app/activities/activity/activity.component.ts 176:21-57
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.eot?v=4.6.3' in '(My Project)\src'
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:8161-8212
 @ ./src/styles.scss
 @ multi styles

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.eot' in '(My Project)\src'
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:8235-8278
 @ ./src/styles.scss
 @ multi styles

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.woff2?v=4.6.3' in '(My Project)\src'
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:8338-8391
 @ ./src/styles.scss
 @ multi styles

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.woff?v=4.6.3' in '(My Project)\src'
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:8424-8476
 @ ./src/styles.scss
 @ multi styles

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.ttf?v=4.6.3' in '(My Project)\src'
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:8508-8559
 @ ./src/styles.scss
 @ multi styles

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module not found: Error: Can't resolve '../fonts/fontawesome-webfont.svg?v=4.6.3' in '(My Project)\src'
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:8595-8646
 @ ./src/styles.scss
 @ multi styles

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
You have a typo there: `@import "../style";` should be **styles**.
