### ISSUE TITLE
ng update says there are incompatible peer dependencies

### ISSUE THREAD

**Issue by sixcorners** [angular/angular-cli#23102]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 no

### Description

 I run ng update and it says things are incompatible whether I try to update things all at once or one at a time.

## 🔬 Minimal Reproduction

```
$ npx @angular/cli update
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 28 dependencies.
    We analyzed your package.json, there are some packages to update:
    
      Name                               Version                  Command to update
     --------------------------------------------------------------------------------
      @angular/cdk                       12.1.1 -> 13.3.6         ng update @angular/cdk
      @angular/cli                       12.1.1 -> 13.3.5         ng update @angular/cli
      @angular/core                      12.1.1 -> 13.3.6         ng update @angular/core
      @angular/material                  12.1.1 -> 13.3.6         ng update @angular/material
    
    There might be additional packages which don't provide 'ng update' capabilities that are outdated.
    You can update the additional packages by running the update command of your package manager.
$ npx @angular/cli update @angular/cdk @angular/cli @angular/core @angular/material
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
✔ Package successfully installed.
Using package manager: 'npm'
Collecting installed dependencies...
Found 28 dependencies.
Fetching dependency metadata from registry...
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/compiler-cli" (requires "^13.0.0 || ^13.3.0-rc.0", would install "14.0.0-next.16")
                  Package "@angular-devkit/build-angular" has an incompatible peer dependency to "@angular/service-worker" (requires "^13.0.0 || ^13.3.0-rc.0", would install "14.0.0-next.16")
                  Package "@angular/animations" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
                  Package "@angular/common" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
                  Package "@angular/compiler" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
                  Package "@angular/animations" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16" (extended), would install "13.3.6").
                  Package "@angular/forms" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
                  Package "@angular/platform-browser" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
                  Package "@angular/platform-browser-dynamic" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
                  Package "@angular/router" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
                  Package "@angular/service-worker" has an incompatible peer dependency to "@angular/core" (requires "14.0.0-next.16", would install "13.3.6")
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-1U7dh6/angular-errors.log" for further details.
```

## 🔥 Exception or Error

<pre><code>
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
  See "/tmp/ng-1U7dh6/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment

<pre><code>
npx @angular/cli version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.1
Node: 16.15.0 (Unsupported)
Package Manager: npm 
OS: linux x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
    
Warning: The current version of Node (16.15.0) is not supported by Angular.
</code></pre>

**Anything else relevant?**
The truth is I don't know much about updating node projects. I think this update tool has worked for me in the past but most of the time I just "rebase" my code onto a new project. I'm used to spring boot where to get everything updated I have to copy/paste one or two versions belonging to "bom" bill of material dependencies that set the version for everything else transitively. When I run `ng update` or `npm audit fix --force` what is it trying to do? Every time I read an error from one of these things I feel like I need a visual aid to figure out which version is too far up or down from where the other versions want them to be.
`ng update` proposed that everything be set to 13.3.6/13.3.5. That sounded good. How is 14.0.0-next.16 entering the picture? I certainly didn't add it. Is there a full proof guide for everything I need to do to update things and make the vulnerabilities go away?

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/22654
