### ISSUE TITLE
Karma tests do not compile for target selected in src/tsconfig.json

### ISSUE THREAD

**Issue by httpdigest** [angular/angular-cli#2312]
Currently, when using Angular 2 CLI 1.0.0-beta.15 and using a target of es2015, the Karma tests do not seem to use this es2015 target from the src/tsconfig.json. We noticed that executing a Karma test for a test which uses ES2015 async/generator/yield feature, the console prints an error after running `ng test`:

```
Async functions are only available when targeting ECMAScript 2015 or higher.
```

**Comment by httpdigest** [comment]
Delving a bit into angular-cli sources, it seems that the `webpack-build-test.js` contains a hardcoded target value of "es5" for the typescript loader. It _must_ be configurable to be able to use the typescript version configured in the src/tsconfig.json.

**Comment by filipesilva** [comment]
@TheLarkInn do you know the reason for hardcoded target/module in `webpack-build-test.js`?

**Comment by catull** [comment]
I think this is not the case (any more).
`ng new test-app`
cd test-app
edit src/tsconfig.json with target: "es2016". Saved it.

`npm run test` , `npm test` # both work
`ng test` # fails, won't even start the tests, some weird issue with 'Promise'
