### ISSUE TITLE
defaultCollection is relative to where cmd is run not angular.json

### ISSUE THREAD

**Issue by kvart714** [angular/angular-cli#23136]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No, it's is duplicate of https://github.com/angular/angular-cli/issues/15014

### Description

![angular json - ng-g-c-bug - Visual Studio Code](https://user-images.githubusercontent.com/17424528/168476938-2639a3ec-262b-417e-85f9-19a72dfdc471.png)

## 🔬 Minimal Reproduction

Repo example: https://github.com/kvart714/ng-g-c-bug

It includes custom schematic.
Command `ng g c` works in project folder, but not works in nested folders due to relative path.

**Comment by kvart714** [comment]
@alan-agius4 I tried your fix. Now it works, but it works differently between default and custom schematics. This ignores any subfolders now.

In the screenshot, I ran the command twice from the same folder, but the components were created in different folders:
![image](https://user-images.githubusercontent.com/17424528/169662700-09fd9460-94b5-42f2-b1e6-32cc33598455.png)

**Comment by alan-agius4** [comment]
Hi @kvart714,
I have a PR in flight to address the above issue https://github.com/angular/angular-cli/pull/23198

For next time, it would be great if you could open a separate issue. Thanks.
