### ISSUE TITLE
Contributing Guidelines update regarding testing angular/cli locally

### ISSUE THREAD

**Issue by vugar005** [angular/angular-cli#23137]
Hi,
It would be better also if we include guidelines regarding testing `@angular/cli` in a demo application.
I am trying to make changes to `@angular/cli` and test changes on some demo app.
I setted debugger inside `@angular/cli` package but in order to trigger it in IDE(visual code) based on research we should link it.
Steps I did:
1. yarn build
2. navigate to `dist/@angular/cli`
3. yarn link
4. navigate to demo project and run yarn link `@angular/cli`
5. npm start

We would receive an error:

![image](https://user-images.githubusercontent.com/28726265/168491738-52a5c350-6b3c-498c-99e6-d006f41974b3.png)

I am using branch 13.3.x
Thanks in advance.

**Comment by alan-agius4** [comment]
Hi, 

This is covered in our [developer docs](https://github.com/angular/angular-cli/blob/main/docs/DEVELOPER.md).
