### ISSUE TITLE
Angular-CLI 14.0.0-rc.0 failed to generate new component

### ISSUE THREAD

**Issue by s-triar** [angular/angular-cli#23141]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
I don't know. the tutorial angular 14 especially for a standalone component on youtube shows that the angular-cli is working perfectly.

### Description

After run `npm i -g @angular/cli@next` to trying angular 14 RC, the angular-cli is failed to generate component using `ng g component <name-component>`

## 🔬 Minimal Reproduction

I am using windows 10.
1. Upgrade angular-cli to 14 rc using `npm i -g @angular/cli@next`
2. Create new project `ng new <name-project>`
3. Generate new component using `ng g component <name-component>`

below is the package.json I am currently using.
```
{
  "name": "berdikari",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "dev:ssr": "ng run berdikari:serve-ssr",
    "serve:ssr": "node dist/berdikari/server/main.js",
    "build:ssr": "ng build && ng run berdikari:server",
    "prerender": "ng run berdikari:prerender"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.0.0-rc.0",
    "@angular/cdk": "^14.0.0-rc.0",
    "@angular/common": "^14.0.0-rc.0",
    "@angular/compiler": "^14.0.0-rc.0",
    "@angular/core": "^14.0.0-rc.0",
    "@angular/forms": "^14.0.0-rc.0",
    "@angular/platform-browser": "^14.0.0-rc.0",
    "@angular/platform-browser-dynamic": "^14.0.0-rc.0",
    "@angular/platform-server": "^14.0.0-rc.0",
    "@angular/router": "^14.0.0-rc.0",
    "@angular/service-worker": "^14.0.0-rc.0",
    "@fortawesome/angular-fontawesome": "^0.10.2",
    "@nguniversal/express-engine": "^14.0.0-rc.0",
    "@zxing/browser": "^0.0.5",
    "@zxing/library": "^0.18.3",
    "@zxing/ngx-scanner": "3.1.3",
    "angular-oauth2-oidc": "^13.0.1",
    "angular-oauth2-oidc-jwks": "^13.0.1",
    "aspnet-prerendering": "^3.0.1",
    "express": "^4.15.2",
    "jwt-decode": "^3.1.2",
    "ng-thermal-print": "^1.0.3",
    "ngx-image-compress": "^11.0.3",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "uuid": "^8.3.2",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.0-rc.0",
    "@angular/cli": "~14.0.0-rc.0",
    "@angular/compiler-cli": "^14.0.0-rc.0",
    "@angular/language-service": "^14.0.0-rc.0",
    "@nguniversal/builders": "^14.0.0-rc.0",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.5.1",
    "@tailwindcss/line-clamp": "^0.4.0",
    "@tailwindcss/typography": "^0.5.2",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~4.0.0",
    "@types/node": "^14.15.0",
    "@types/uuid": "^8.3.3",
    "@types/w3c-web-serial": "^1.0.2",
    "@types/w3c-web-usb": "^1.0.5",
    "@types/web-bluetooth": "0.0.12",
    "autoprefixer": "^10.4.7",
    "jasmine-core": "~4.1.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "postcss": "^8.4.13",
    "tailwindcss": "^3.0.24",
    "tailwindcss-children": "^2.1.0",
    "typescript": "~4.6.2"
  }
}
```
## 🔥 Exception or Error

<pre><code>
An unexpected error occurred: {}
</code></pre>
![image](https://user-images.githubusercontent.com/34316314/168610969-d61c7861-d5ce-44da-b0cb-c815fabca2dd.png)

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.0-rc.0
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 14.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0-rc.0
@angular-devkit/build-angular   14.0.0-rc.0
@angular-devkit/core            14.0.0-rc.0
@angular-devkit/schematics      14.0.0-rc.0
@nguniversal/builders           14.0.0-rc.0
@nguniversal/express-engine     14.0.0-rc.0
@schematics/angular             14.0.0-rc.0
rxjs                            7.5.5
typescript                      4.6.4

</code></pre>

**Comment by dzhavat** [comment]
I just experienced the same error. My repo is here https://github.com/dzhavat/angular-standalone-components

Running `ng version` gives me this

![image](https://user-images.githubusercontent.com/1096332/168656481-d47c5050-07df-4fcc-955c-faab18defc90.png)

**Comment by s-triar** [comment]
I repro my repo also here https://github.com/s-triar/repro-ng-14-cli-failed-g-comp

**Comment by s-triar** [comment]
for some reason. `ng g directive <name-dir>` also has the same error

![image](https://user-images.githubusercontent.com/34316314/168742513-2f84e894-877f-42e5-9eff-13ce6fa45895.png)

**Comment by s-triar** [comment]
When I change the file according to https://github.com/angular/angular-cli/pull/23149/commits/f2764c6e188fd786cb5bbca90e39bd92f6bd667f

it happened because there is more than 1 module.
