### ISSUE TITLE
not able to install TinyMCE component to angular project

### ISSUE THREAD

**Issue by DipakDhande** [angular/angular-cli#23147]
Hi there,
I need to integration TinyMCE in angular project ( https://www.tiny.cloud/docs/integrations/angular/ ).
So I run **npm install --save @tinymce/tinymce-angular** command to do so.
But I am getting following errors. Can some please help me on this issue!

npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! While resolving: edx-subscriptions-ui@0.0.0
npm ERR! Found: rxjs@7.1.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.1.0" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.5.3" from @angular/core@12.0.5
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~12.0.5" from the root project
npm ERR!   peer @angular/core@"12.0.5" from @angular/common@12.0.5
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"~12.0.5" from the root project
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
