### ISSUE TITLE
Proxy-Mode removed httpClient-Postvalues

### ISSUE THREAD

**Issue by mwaldheim** [angular/angular-cli#23151]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I use the proxy conf for local development as per Angular instructions. I noticed that the post values are discarded in my request. 

Unfortunately, after more than 3 hours of research, I have not found a solution.

The request arrives at my local PHP server but has no post values. By using the bypass variant I could find out that the post values are not passed at all.

```json
{
  "/api/*": {
    "target": "https://pc057.mydomain.local/applikation",
    "secure": false,
    "changeOrigin": true,
    "pathRewrite": {"^/api" : ""}
  }
}
```

Request (TS)
```ts
  constructor(private http: HttpClient) {
  }

// userCredentials come from a FromGroup on Submit
  makeBasicAuth(userCredentials: BasicAuth): Observable<AuthResponse> {
    return this.http.post<AuthResponse>('/api/restlogin/api/REST_LOGIN', userCredentials);
  }
```

Image from the Request before Proxy: 
![image](https://user-images.githubusercontent.com/31657644/168783894-3eb1b190-fccc-4f55-9b6a-5eaa7f0e445f.png)

Request on the Server (Post empty)
![image](https://user-images.githubusercontent.com/31657644/168783950-3acec511-87be-4f77-96f3-51c3871ea946.png)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.5
Node: 16.15.0
Package Manager: npm 8.4.0
OS: win32 x64

Angular: 13.3.6
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.3.5
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.6.4
```

**Comment by alan-agius4** [comment]
@mwaldheim, can you try to set up the content type?

```
const httpOptions = {
  headers: new HttpHeaders({
    'Content-Type':  'application/json',
  })
};
```

https://angular.io/guide/http#adding-and-updating-headers

**Comment by mwaldheim** [comment]
Unfortunately, this changes nothing, same behavior. Post values are missing. Without proxy I can't do it otherwise, because I get a CORS error.

**Comment by alan-agius4** [comment]
@mwaldheim, I am unable to replicate this with a basic Node.js Server.

**app.component.ts**
```
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'proxy-test';
  constructor(private http: HttpClient) {
    this.http.post('/api/login', {  user: 'foo' }).subscribe();
  }
}

```

 **index.js**
```js
const express = require("express");
const app = express();

app.use(express.json()) 
app.post("/login", (request) => {
  console.warn({
      body: request.body
  });
});

app.listen(3003, () => {
  console.log("Server running on port 3003");
});
```

**proxy-config.json**
```json
{
  "/api/*": {
    "target": "http://localhost:3003",
    "secure": false,
    "changeOrigin": true,
    "pathRewrite": {"^/api" : ""}
  }
}
```

```bash
$ node index
Server running on port 3003
{ body: { user: 'foo' } }
```
Thus, likely this is a server configuration issue.

**Comment by mwaldheim** [comment]
For internal company reasons, I am not allowed to give this out.

I have copied your case exactly. With Express it really works. 

But as soon as I go to the local PHP client, it doesn't work again.

The server consists of an Apache PHP server based on Docker. I therefore address port 80, the request also arrives, but loses all its post values. The same applies to our company servers, which are public.

Translated with www.DeepL.com/Translator (free version)
