### ISSUE TITLE
ng serve not work

### ISSUE THREAD

**Issue by adittya321** [angular/angular-cli#23152]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by adittya321** [comment]
ng serve not working

**Comment by vzakharov-rxnt** [comment]
@adittya321 Have you considered adding **any** debug info to the ticket?

**Comment by adittya321** [comment]
no

**Comment by vzakharov-rxnt** [comment]
@adittya321 Please consider it.

**Comment by alan-agius4** [comment]
Closing due to lack of information. Please follow the issue template.

**Comment by adittya321** [comment]
ng serve
***************************************************************************************
This is a simple server for use in testing or debugging Angular applications locally.It hasn't been reviewed for security issues.

DON'T USE IT FOR PRODUCTION!
****************************************************************************************
An unhandled exception occurred: error TS18003: No inputs were found in config file 'C:/Users/91700/Frontend/tsconfig.app.json'. Specified 'include' paths were '["src/**/*.ts"]' and 'exclude' paths were '["src/test.ts","src/**/*.spec.ts"]'.

See "C:\Users\91700\AppData\Local\Temp\ng-UM8biC\angular-errors.log" for further details.

**Comment by adittya321** [comment]
any answer
