### ISSUE TITLE
Found mostly working esbuild Angular compiler - fix pending issues and use it for Angular CLI build?

### ISSUE THREAD

**Issue by vzakharov-rxnt** [angular/angular-cli#23153]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] build
- [x] serve

### Description

I found a mostly working esbuild compiler for Angular. I know Angular team is investigating this, so could be of some help.
- https://github.com/cherryApp/ngc-esbuild

### Describe the solution you'd like

Please expedite build speed improvements, current Angular 13.x builds are too slow, even my most simple app with 5k of own LOC and 1.8MB JS bundle size takes 2min to build on a CI/CD agent. I checked other questions here, I would be fine to not have type checking, I can add a parallel type check with `npm-run-all`, it would still be faster.

For example, one enterprise application that I have here, with 15MB bundle size (combined main and lazy chunks), takes 1min to build with Angular 13 CLI on my Ryzen 9 laptop. It's a mix of Angular 13 and Angular 1.x code. Another enterprise application with the same bundle size takes 30 seconds to build with `webpack/esbuild-loader` and type checks running in parallel. It only has Angular 1.x code, no Angular 13.

Assuming the above data and linear correlation between output bundle size and build time (15MB / 1.8MB * 2min), I estimate 16min on a CI/CD agent for our larger app.

### Describe alternatives you've considered

N/A

**Comment by alan-agius4** [comment]
One of the features of version 14 which is currently in RC stage is an experimental EsBuild browser builder. See https://github.com/angular/angular-cli/pull/22995 for more information. 

Closing since this feature is already present as an opt-in experiment.

**Comment by vzakharov-rxnt** [comment]
@alan-agius4 Thanks. Do you plan to support SCSS? Other unsupported features are probably fine, but I can't imagine anyone using raw CSS in 2022.

Also is there any ETA on this feature's release? I see

> This builder is considered experimental and is not recommended for production applications.

**Comment by alan-agius4** [comment]
Support for SCSS will be added down the line based on the feedback we receive. 

> But I can't imagine anyone using raw CSS in 2022.

Surprising a large percentage of users still use plain CSS.

**Comment by vzakharov-rxnt** [comment]
@alan-agius4 Does it mean SCSS is not planned for v14 ?
