### ISSUE TITLE
Getting Module parse failed: Unexpected character '#'

### ISSUE THREAD

**Issue by vishalshrm539** [angular/angular-cli#23162]
Hi,

I am getting this error when I try to use private fields in an Angular Project.

Error: ./src/app/_helpers/sample.js 6:11
Module parse failed: Unexpected character '#' (6:11)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.

sample.js:
class Sample {

  constructor() {
      this.#reloadConfig();   // 6th line
  }

  #reloadConfig() {
}
...

**Comment by alan-agius4** [comment]
Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
