### ISSUE TITLE
Build fails after upgrading to Angular 12

### ISSUE THREAD

**Issue by anshulsinha1101** [angular/angular-cli#23173]
I have recently upgraded my Angular 7 application to Angular 12 12.2.17, here the build fails whenever try to build my application with below error 
Error: Optimization error [src_app_modules_test_module_ts.a61aac0d1ddf3c99877b.js]: Error: The service was stopped

Error: Optimization error [default-src_app_modules_project_module_ts.b99413cbfdc9abde0360.js]: Error: The service is no longer running

I am using below command to build my application

"build:prod": "node --max_old_space_size=5500 ./node_modules/@angular/cli/bin/ng build --configuration production",

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
