### ISSUE TITLE
activatedRoute._loadedConfig.module.instance.constructor.ɵmod - imports and declarations is empty array in prod mod

### ISSUE THREAD

**Issue by Y4Rick** [angular/angular-cli#23187]
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

There is a root router resolver that gather all component's selectors whit are used or might be used (popups) on particular page. 

With the help of recursion and `activatedRoute.firstChild`s and the path `activatedRoute._loadedConfig.module.instance.constructor.ɵmod` I am able to get imports and declarations of the lazy-loading module. And then get all component's selectors. 

But **in prog mod imports and declarations is empty array** - so my method is not working.

I know that the `"optimization": true` option influences this, but this option is necessary for prog mod.
The static field in the module is also not acceptable because it influences the project size.

There was an issue https://github.com/angular/angular-cli/issues/21952#issuecomment-945752429 where was said that https://github.com/angular/angular-cli/issues/21952#issuecomment-945823144 @[clydin](https://github.com/clydin) `code adds metadata to the Angular module definitions at runtime`

So the question is - is there an access to this metadata in prod mod to get imports and declarations? Or is there exist another way to collect all component which might be used one the page before the view is rendered?  

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.3.3
Node: 12.22.4
Package Manager: npm 6.14.14
OS: darwin x64

Angular: 13.3.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@schematics/angular             13.3.3
rxjs                            6.6.7
typescript                      4.6.3

</code></pre>

**Comment by alan-agius4** [comment]
The `NgModule` metadata itself is internal and accessing `ɵmod` is not supported.  `activatedRoute._loadedConfig` is private as well. 

The problem can be avoided by exporting the list of declarations on a static field as described in https://github.com/angular/angular-cli/issues/21952#issuecomment-945752429
