### ISSUE TITLE
Get rid of .vscode directory

### ISSUE THREAD

**Issue by grosch** [angular/angular-cli#23215]
# 🚀 Feature request

### Command (mark with an `x`)

- [x ] new

### Description

Please provide an option to not generate the .vscode directory. I don't use VS Code, and don't want those files. Not sure why that specific editor config is being put by default. There are tons of editors for typescript, such as WebStorm, that you don't include configs for.

### Describe the solution you'd like

Either a --no-vscode option or, better yet, don't do it by default and add a --want-vscode or somesuch option.

### Describe alternatives you've considered

Yes, I can just delete the directory, but I shouldn't have to :)

**Comment by alan-agius4** [comment]
Thanks for this request. None-the-less, this is currently not in the roadmap. Let's re-consider this in the future if more users feel the same way.
