### ISSUE TITLE
Generating a module also generates an unwanted component, html, and stylesheet

### ISSUE THREAD

**Issue by zakdances** [angular/angular-cli#2322]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Mac OSX El Capitan

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

```angular-cli: 1.0.0-beta.15```

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

In console:

```ng g module my-module```

4. The log given by the failure. Normally this include a stack trace and some
   more information.

```
installing module
  create src/app/my-module/my-module.module.ts
installing component
  create src/app/my-module/my-module.component.scss
  create src/app/my-module/my-module.component.html
  create src/app/my-module/my-module.component.spec.ts
  create src/app/my-module/my-module.component.ts

```

5. Mention any other details that might be useful.

Generating a module should generate just that - *a module*. I **don't want** a component, html, or scss ***unless I specifically ask for them***.

I create many modules that are just services, pipes, etc. and I don't want or need components. Everytime I generate a module now, I'm forced to delete these unwanted party crashers.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Tobias4872** [comment]
+1

**Comment by filipesilva** [comment]
There's a couple of options to help with this, and we really should do a better job of documenting them:
- `--flat` to not make a folder
- `--inline-template` to inline html
- `--inline-style` to inline style
