### ISSUE TITLE
Installing angular@cli via npm is not working

### ISSUE THREAD

**Issue by AFKBETO** [angular/angular-cli#23241]
# 🐞 Bug report

### Command

I am having some issues with installing angular@cli via npm:
`npm i -g angular@cli`

### Description

This happens when I just updated both node (to v16.15.0) and npm (to v8.11.0).

I have another PC using older versions of both (node at v16.14.2 and npm at v8.6.0) and the installation still works.

## 🔥 Exception or Error

<pre><code>
npm ERR! code ETARGET
npm ERR! notarget No matching version found for angular@cli.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2022-05-27T09_38_56_432Z-debug-0.log
</code></pre>

## 🌍 Your Environment

I'm installing angular@cli via npm on Windows 10:
<pre><code>
Check                    Value  Recommendation/Notes
npm ping                 ok
npm -v                   ok     current: v8.11.0, latest: v8.11.0
node -v                  ok     current: v16.15.0, recommended: v16.15.0
npm config get registry  ok     using default registry (https://registry.npmjs.org/)
which git                ok     F:\Programs\Git\cmd\git.EXE
Verify cache contents    ok     verified 3 tarballs
</code></pre>

**Anything else relevant?**

I have installed another package (firebase) in this same PC and it works, so I wonder if it has anything to do with angular@cli.

[2022-05-27T09_38_56_432Z-debug-0.log](https://github.com/angular/angular-cli/files/8785778/2022-05-27T09_38_56_432Z-debug-0.log)

**Comment by alan-agius4** [comment]
Hi @AFKBETO,

That's because an invalid package specifier was used. `angular@cli` is not a valid package.

```
npm i -g @angular/cli
```

**Comment by AFKBETO** [comment]
Thanks, I was a bit dumb when installing angular cli in new machine :(
