### ISSUE TITLE
Modules imported for side effects are not included in optimized bundle

### ISSUE THREAD

**Issue by amitbeck** [angular/angular-cli#23246]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I have a `index.ts` which imports 2 modules (`abstract-control.ts` and `abstract-control.directive.ts`) for side effects, and exports another module (`custom-control-status.directive.ts`) therefore also acting as a barrel file. `custom-control-status.directive.ts` is imported through the barrel file (`index.ts`), therefore I thought `index.ts` and the 2 modules imported for side effects would be included in the bundle, but they're removed in the tree shaking process.
I tried both of the following:
* specifying `"sideEffects"` in `package.json`'s:
    1. `"sideEffects": ["<path>/index.ts", "<path>/abstract-control.ts" and "<path>/abstract-control.directive.ts"]` in the app's `package.json`
    2. Add a `package.json` to the directory and set `"sideEffects": ["./index.ts", "./abstract-control.ts" and "./abstract-control.directive.ts"]` in it
    3. Add a `package.json` to the directory and set `"sideEffects": true` in it
* specifying a rule in Webpack's `module.rules` that matches every TS file in the directory and set `sideEffects: true`

Despite that, they are all excluded from the bundle. Could this be an issue with [Angular's webpack config](https://github.com/angular/angular-cli/blob/13.2.x/packages/angular_devkit/build_angular/src/webpack/configs/common.ts) or [`@angular-builders/custom-webpack`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack)?

## 🔬 Minimal Reproduction

Reproduction repository: https://github.com/amitbeck/ng-webpack-sideEffects-repro
Either:
1. Run `npm run build` (alias for `ng build --configuration production`), or
2. Run `npm run serve` (alias for `ng serve --configuration production`) and access through http://localhost:4200. You should get the following error:
    > TypeError: this.formGroup.controls.text.setWarnings is not a function

`abstract-control.ts`, `abstract-control.directive.ts` and `index.ts` in `src/app/utils/forms/` are not included in the bundle.

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.6
Node: 16.13.1
Package Manager: npm 8.1.2
OS: darwin x64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.2.6
@angular/cdk                    13.2.6
@angular/cdk-experimental       13.2.6
@angular/cli                    13.2.6
@angular/material               13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
</code></pre>

**Anything else relevant?**

Possibly related to https://github.com/angular/angular-cli/issues/12912 and https://github.com/webpack/webpack/issues/15610.
Also asked [a question in SO](https://stackoverflow.com/questions/72390897/why-are-these-modules-imported-for-side-effects-not-included-in-webpack-bundle) and asked a Webpack team member for help in https://github.com/webpack/webpack/issues/15610#issuecomment-1138473225.

**Comment by amitbeck** [comment]
Not sure if this issue is most relevant to Angular CLI or Angular itself, so I opened https://github.com/angular/angular/issues/46178

**Comment by alan-agius4** [comment]
Hi @amitbeck, 

This seems to be a Webpack issue. 

The issue manifest itself when using barrel files. If you import the side-effectful modules without using a barrel file. It workers as expected.

```ts
import { CustomControlStatusDirective } from './utils/forms';
import './utils/forms/abstract-control';
import './utils/forms/abstract-control.directive';
``` 

Closing as this is not actionable from our end.

**Comment by amitbeck** [comment]
@alan-agius4 [According to a webpack team member, it seems that whatever's in `NgModule.declarations` isn't emitted to the output code](https://github.com/webpack/webpack/issues/15882#issuecomment-1144563708):
> so it looks like `declarations` directive doesn't work as expected in `app.module`: original code:
> 
> ```ts
> import { NgModule } from '@angular/core';
> import { ReactiveFormsModule } from '@angular/forms';
> import { BrowserModule } from '@angular/platform-browser';
> 
> import { AppComponent } from './app.component';
> import { CustomControlStatusDirective } from './utils/forms';
> 
> @NgModule({
>   declarations: [AppComponent, CustomControlStatusDirective],
>   imports: [BrowserModule, ReactiveFormsModule],
>   providers: [],
>   bootstrap: [AppComponent],
> })
> export class AppModule {}
> ```
> 
> results in non-minimized code
> 
> ```js
> let AppModule = /*#__PURE__*/(() => {
>   class AppModule {}
> 
>   AppModule.ɵfac = function AppModule_Factory(t) {
>     return new (t || AppModule)();
>   };
> 
>   AppModule.ɵmod = /*@__PURE__*/ɵɵdefineNgModule({
>     type: AppModule,
>     bootstrap: [AppComponent]
>   });
>   AppModule.ɵinj = /*@__PURE__*/ɵɵdefineInjector({
>     providers: [],
>     imports: [[BrowserModule, ReactiveFormsModule]]
>   });
>   return AppModule;
> })();
> ```
> 
> here there is no `CustomControlStatusDirective` usage. if just add
> 
> ```diff
> import { NgModule } from '@angular/core';
> import { ReactiveFormsModule } from '@angular/forms';
> import { BrowserModule } from '@angular/platform-browser';
> 
> import { AppComponent } from './app.component';
> import { CustomControlStatusDirective } from './utils/forms';
> 
> + console.log(CustomControlStatusDirective);
> @NgModule({
>   declarations: [AppComponent, CustomControlStatusDirective],
>   imports: [BrowserModule, ReactiveFormsModule],
>   providers: [],
>   bootstrap: [AppComponent],
> })
> export class AppModule {}
> ```
> 
> webpack will bundle all `utils/forms`

How is it possible that `CustomControlStatusDirective` (or anything in `NgModule.declarations`) isn't emitted to the output code?

**Comment by alan-agius4** [comment]
The Angular compiler will remove components which are unused.

https://github.com/angular/angular-cli/issues/21952#issuecomment-945752429

**Comment by amitbeck** [comment]
@alan-agius4 Thanks for the clarification. It's a bit of magic and voodoo, and definitely not expected.
