### ISSUE TITLE
Cannot get source maps with inlineSources using @ngtools/webpack

### ISSUE THREAD

**Issue by vasicvuk** [angular/angular-cli#23254]
# 🐞 Bug report

### Description

I am trying to get a source map with inlineSources for an Angular code within that is built with webpack and plugin **@ngtools/webpack** but I cannot get it to work.

In my tsconfig file I have:

```
"inlineSources": true
```

When I change loader from `@ngtools/webpack` to `ts-loader` correct source map file containing **sourcesContent** property is generated but I cannot get it to work with `@ngtools/webpack`.

Is there some way to generate source maps with **sourceContent** within by using @ngtools/webpack ?

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.5
Node: 14.17.6
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 13.3.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.5
@angular-devkit/build-angular   13.3.5
@angular-devkit/build-webpack   0.1302.6
@angular-devkit/core            13.3.5
@angular-devkit/schematics      13.3.5
@angular/cli                    13.3.5
@schematics/angular             13.3.5
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.5.5
webpack                         5.72.1
</code></pre>

**Comment by alan-agius4** [comment]
@vasicvuk what is the value of the sourceMap compiler option? [inlineSources](https://www.typescriptlang.org/tsconfig#inlineSources) requires either [sourceMap](https://www.typescriptlang.org/tsconfig#sourceMap) or [inlineSourceMap](https://www.typescriptlang.org/tsconfig#inlineSourceMap) to be set

**Comment by vasicvuk** [comment]
@alan-agius4  Sure both `inlineSources` and `sourceMap` are set to true.

Interesting thing is that actually there is `sourcesContent` but containing only **webpackUniversalModuleDefinition** function and no other code

**Comment by vasicvuk** [comment]
Seems odd but when I add `enableIvy: true` in `angularCompilerOptions` it generated the source map well? Should I have this flag for Angular 13?
