### ISSUE TITLE
Bring back `ng update --all` (includes: workaround with `jq`)

### ISSUE THREAD

**Issue by SamuelMarks** [angular/angular-cli#23261]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] update

### Description
```
$ ng update --all

        '--all' functionality has been removed as updating multiple packages at once is not recommended.
        To update packages which don’t provide 'ng update' capabilities in your workspace 'package.json' use 'npm update' instead.
        Run the package manager update command after updating packages which provide 'ng update' capabilities.
```

### Describe the solution you'd like

Bring back `--all`… maybe with a `-f`/`--force` so the warning can remain.

### Describe alternatives you've considered

```sh
ng update --force $(jq -r '.dependencies * .devDependencies | keys | map(select(startswith("@angular"))) | @tsv' package.json)
```

(then run: [`ncu`](https://www.npmjs.com/package/npm-check-updates) `-ux '/typescript|rxjs/'`)

**Comment by alan-agius4** [comment]
Hi @SamuelMarks, 

Thanks for this feature request, however this is currently out of scope. Let's re-consider this in the future if there is a larger demand for this.
