### ISSUE TITLE
Error when up I update from 13 to 14

### ISSUE THREAD

**Issue by danrald** [angular/angular-cli#23274]
I currently have Angular CLI 13.1.3
Node 14.15.1 
Package Manager 8.12.1
tsc 4.7.2
When I issue "ng update @angular/core@14 @angular/cli@14" I get the following:

The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 14.0.0 to perform the update.        
✔ Package successfully installed.
Error: Unknown arguments: update, @angular/core@14, @angular/cli@14

The upgrade did not work and I get the version, I still get Angular CLI: 13.1.3

**Comment by alan-agius4** [comment]
Can you please share your `package.json`?

**Comment by PzYon** [comment]
I have the same behavior:
`Error: Unknown arguments: update, @angular/core@14, @angular/cli@14`

I'm running Node on Windows:
- Node version: `14.17.1`
- NPM version: `8.12.1`

I get the behavior when I run
- `npx @angular/cli update @angular/core @angular/cli` or
- `ng update @angular/core@14 **@angular/cli@14`

`package.json` looks something like this:
```
{
  "name": "XXX",
  "version": "0.1.0",
  "scripts": {
    "concat": "concat",
    "ng": "ng",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "13.3.9",
    "@angular/cdk": "13.3.7",
    "@angular/common": "13.3.9",
    "@angular/compiler": "13.3.9",
    "@angular/core": "13.3.9",
    "@angular/elements": "13.3.9",
    "@angular/flex-layout": "13.0.0-beta.38",
    "@angular/forms": "13.3.9",
    "@angular/material": "13.3.7",
    "@angular/platform-browser": "13.3.9",
    "@angular/platform-browser-dynamic": "13.3.9",
    "@angular/router": "13.3.9",
    "@angular-extensions/elements": "13.0.0",
    "@fortawesome/angular-fontawesome": "0.10.2",
    "@fortawesome/fontawesome-svg-core": "6.1.1",
    "@fortawesome/free-solid-svg-icons": "6.1.1",
    "@ngx-translate/core": "14.0.0",
    "date-fns": "2.28.0",
    "document-register-element": "1.14.10",
    "material-design-icons": "3.0.1",
    "rxjs": "7.5.5",
    "tslib": "2.3.1",
    "zone.js": "0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "13.3.6",
    "@angular/cli": "13.3.6",
    "@angular/compiler-cli": "13.3.9",
    "@types/jasmine": "4.0.3",
    "@types/node": "16.11.36",
    "concat": "1.0.3",
    "http-server": "14.1.0",
    "jasmine-core": "4.1.1",
    "karma": "6.3.20",
    "karma-chrome-launcher": "3.1.1",
    "karma-coverage": "2.2.0",
    "karma-jasmine": "4.0.2",
    "karma-jasmine-html-reporter": "1.7.0",
    "typescript": "4.6.4"
  }
}
```

**Comment by alan-agius4** [comment]
@PzYon, what's your global Angular CLI version? 

You can find this by running `ng version` **outside** of an Angular workspace.

**Comment by PzYon** [comment]
@alan-agius4 , here you go:
```
Angular CLI: 13.3.7
Node: 14.17.1
Package Manager: npm 8.12.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.7 (cli-only)
@angular-devkit/core         13.3.7 (cli-only)
@angular-devkit/schematics   13.3.7 (cli-only)
@schematics/angular          13.3.7 (cli-only)
```

**Comment by r-hannuschka** [comment]
It seems they are missing

```bash
ng --help

  ng analytics                   Configures the gathering of Angular CLI usage metrics. See...
  ng cache                       Configure persistent disk cache and retrieve cache statistics.
  ng completion                  Set up Angular CLI autocompletion for your terminal.
  ng config [json-path] [value]  Retrieves or sets Angular configuration values in the angular.json file for...
  ng doc <keyword>               Opens the official Angular documentation (angular.io) in a browser, and searches ..
  ng new [name]                  Creates a new Angular workspace.                           
  ng version                     Outputs Angular CLI version.
```

there is no such command like update, serve, e2e, test

**Comment by alan-agius4** [comment]
`ng update` command is only available in an Angular workspaces and hence why it's not present when you run `ng --help`. 

Maybe you are running the `update` command outside of the workspace?

**Comment by r-hannuschka** [comment]
yeah i see this for serve, for me i think there is an other problem i run inside an nx workspace and this will not work but this is okay since angular is not nx.

**Comment by alan-agius4** [comment]
@danrald / @PzYon are you also using NX?

**Comment by PzYon** [comment]
If with "workspace" you mean the directory where the `package.json` and the `angular.json` is located, then yes! :)

**Comment by alan-agius4** [comment]
> @alan-agius4 , if with "workspace" you mean the directory where the `package.json` and the `angular.json` is located, then yes! :)

Yes. that is correct. I tried to replicate this on a separate project however I didn't have any luck. Are able to share a reproduction?

**Comment by PzYon** [comment]
I just realized that if I use the PowerShell-window it works. However when I use the terminal from WebStorm (which actually uses PowerShell too) it does not work. In other words: Problem is solved for me, but I don't understand why... ;) Maybe something related to paths/environment variables.

**Comment by PzYon** [comment]
@alan-agius4 , great, thanks for the update. Good point. Due to corporate regulations I am working with WebStorm version 2021.2 (not new ;)). I don't even have that checkbox available. ;) Thanks for your support!

**Comment by Abneco** [comment]
I had the same problem for upgrade angular cli here is what I had to do.

update node and npm
node : v16.15.1
npm : 8.12.1

```
npm uninstall -g @angular/cli
npm install -g @angular/cli@latest
```

And for the project
https://update.angular.io/?v=13.0-14.0
```
ng update @angular/core@14 @angular/cli@14
```

check
```
ng version
```
Angular CLI: 14.0.0
Node: 16.15.1
Package Manager: npm 8.12.1
OS: win32 x64

**Comment by danrald** [comment]
@alan-agius4 I am using an angular workspace. I created an whole new project using the ng 13 cli, then issued an @angular/core@14 @angular/cli@14. And everything worked fine. I can just force an upgrade in one mannor or another. Sometimes I'm just curious why I get the error.

**Comment by danrald** [comment]
@Abneco Yes, thanks, I was going to do that. But I just wanted to understand the error. Thanks

**Comment by alan-agius4** [comment]
@danrald, unfortunately I am unable to replicate this, thus without a reproduction it would be hard to get to the bottom of this.

**Comment by satanTime** [comment]
I see the same issue. Try to update master branch of https://github.com/ike18t/ng-mocks

npx @angular/cli@14 update @angular/core@14 @angular/cli@14. 

I'm on Mac with iterm.

**Comment by alan-agius4** [comment]
@satanTime, in your case I don't see any `angular.json` in your reproduction, therefore it doesn't seem that this repo is managed by the Angular CLI.

**Comment by satanTime** [comment]
It's under test-e2e directory. 

Another directory was e2e/a14 (it requires to reset head on several commits back), I tried there from 14-rc to stable and got the same error. Afterwards, updated manually.

On Monday I'm back to laptop and can try to extract the broken state with steps.

**Comment by alan-agius4** [comment]
@satanTime, are you running the `ng update` command in the `test-e2e` and `e2e/a14` directory? I only managed to replicate the mentioned error when the command was ran outside of this directories.

**Comment by satanTime** [comment]
I tried the root and e2e/a14, not in test-e2e. Why root didn't work - now it makes sense. However, a better error message would be better :) something like - no angular.json found, instead of unexpected params update @angular...

Regarding e2e/a14, I need to reset head back to reproduce it. I'll try on Monday.

**Comment by danrald** [comment]
@alan-agius4 I was indeed in the incorrect angular workspace. My humble apologies! Thanks
