### ISSUE TITLE
How to run angular 2 application on apache hosting server

### ISSUE THREAD

**Issue by nikvarma** [angular/angular-cli#2327]
Hi Guys,

I have hosting plan and i want to host my angular 2 application on the hosting server which have apache server.

The hosting server don't have a npm install.

after below command and getting a like the strc

file strc

image
![image](https://cloud.githubusercontent.com/assets/3116497/18807890/0be5c5ae-8208-11e6-9df9-3fd85c5aa8fd.png)

![image](https://cloud.githubusercontent.com/assets/3116497/18807891/0f6f7378-8208-11e6-9f03-47dfefe85eaf.png)

ng build --prod

and uploading to my hosting server, when i am accessing the my url

http://www.exmaple.com/ -- it's working properly
http://www.exmaple.com/home -- it's giving a error, the file is no found on the server - 404

but the same thing working on my machine, when i am trying using a cmd
ng serve - command

**Comment by kidshenlong** [comment]
Unless you're using the [HashLocation strategy](https://angular.io/docs/ts/latest/guide/router.html#browser-url-styles) you're going to run into 404s. Have a look at this https://github.com/mgechev/angular2-seed/wiki/Deploying-prod-build-to-Apache-2

**Comment by filipesilva** [comment]
Closing as a couple of good responses are here already.

**Comment by jbh** [comment]
I was still having this issue, even with the rewrites. I wanted to mention my solution for anyone still having the issue:

I was including `MultiViews` in `Options Indexes FollowSymLinks MultiViews` in my Apache configuration. Removing it will fix the problem. According to the [documentation](http://httpd.apache.org/docs/current/content-negotiation.html):

*The effect of MultiViews is as follows: if the server receives a request for /some/dir/foo, if /some/dir has MultiViews enabled, and /some/dir/foo does not exist, then the server reads the directory looking for files named foo.*, and effectively fakes up a type map which names all those files, assigning them the same media types and content-encodings it would have if the client had asked for one of them by name. It then chooses the best match to the client's requirements.

This was causing a 404 for any route other than `/`.

**Comment by jdpatel605** [comment]
try to using this rewrite rule for htaccess

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]

RewriteRule ^(.*) /index.html [NC,L]
