### ISSUE TITLE
Upgrade 13 to 14 build memory issue

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#23280]
Exception on ng build:

`(node:60532) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
\ Generating browser application bundles (phase: building)...
<--- Last few GCs --->

[60532:041F4940]    91104 ms: Mark-sweep 1005.3 (1045.5) -> 999.7 (1048.0) MB, 341.2 / 0.0 ms  (average mu = 0.195, current mu = 0.022) allocation failure scavenge might not succeed
[60532:041F4940]    91971 ms: Mark-sweep 1007.8 (1048.0) -> 1002.0 (1050.2) MB, 859.1 / 0.0 ms  (average mu = 0.085, current mu = 0.009) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00BFE90F v8::internal::Heap::AllocateExternalBackingStore+1551`

This is a regression from v13.1.

## Version

Angular CLI: 14.0.0
Node: 16.15.0
Package Manager: npm 8.12.1
OS: win32 ia32

Angular: 14.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/build-webpack   0.1400.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@angular/flex-layout            13.0.0-beta.38
@nguniversal/express-engine     14.0.0
@schematics/angular             14.0.0
ng-packagr                      14.0.0
rxjs                            7.5.5
typescript                      4.6.4
webpack                         5.73.0

**Comment by alan-agius4** [comment]
Are you using a custom webpack configuration by any chance?

If not, kindly provide CPU profiler snapshots before / after the update. Alternatively please provide a minimal reproduction.

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
It appears that you have an incorrect version of Node.js installed (win32 ia32). Unless your OS is 32bit.

You can use [NVM](https://github.com/coreybutler/nvm-windows) to easily manage Node.js versions or download the 64Bit LTS versions from [Node.js downloads page](https://nodejs.org/en/download/).

**Comment by akaufmann** [comment]
Since v12 and the internal upgrade to webpack 5, we are experiencing the same `JavaScript heap out of memory` error. Which looks very much like webpack 5 is the problem and there is a memory leak there. The upgrade to v12 just happened a few weeks ago and we don't have a custom webpack configuration, but it happens when we link a NG lib (via `yarn link`) in our very large app and the app is rebuilt by making an adjustment in the lib (the watcher kicks in).

I'm not sure how to provide a repo with a linked lib, but maybe you, @alan-agius4, can try a (large) v12 app and try to link a lib and trigger a rebuild by changing something in the lib if possible? Sorry I can't be more helpful yet but I hope this sheds some more light.

**Comment by zehavibarak** [comment]
@alan-agius4 works! thanks.
