### ISSUE TITLE
Angular CLI 14: running `ng test --watch=false` on Angular 13 or 12 project does not end process when complete

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [angular/angular-cli#23289]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, globally installing Angular CLI 13 worked with both Angular 13 and Angular 12 projects when running `ng test --watch=false`.

### Description

Installing Angular CLI 14 globally and running `ng test --watch=false` on an Angular 13 or Angular 12 application results in the process never terminating. This causes CI builds to hang indefinitely on any step that runs Angular unit tests using this command.

## 🔬 Minimal Reproduction

- Run `npm i @angular/cli@13 -g` to Install Angular CLI 13.
- Run `ng new` to create a new Angular application. I chose to add Angular routing and selected SCSS for the stylesheet format. Selecting SCSS seems to be required to reproduce the issue, but adding routing does not.
- Run `ng test --watch=false` and observe the tests running, then the process terminating after completion.
- Run `npm i @angular/cli@14 -g` to install Angular CLI 14.
- Run `ng test --watch=false`. The message `Your global Angular CLI version (14.0.0) is greater than your local version (13.3.7). The local Angular CLI version is used.` will be displayed. Observe the tests running, then the process continuing to run even after the tests complete.

## 🔥 Exception or Error

<pre><code>N/A</code></pre>

## 🌍 Your Environment

macOS 12.4
node 14.17.6
npm 6.14.15

### Global `ng version`
<pre><code>Angular CLI: 14.0.0
Node: 14.17.6
Package Manager: npm 6.14.15 
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.0 (cli-only)
@angular-devkit/core         14.0.0 (cli-only)
@angular-devkit/schematics   14.0.0 (cli-only)
@schematics/angular          14.0.0 (cli-only)</code></pre>

### `ng version` inside application directory
<pre><code>Angular CLI: 13.3.7
Node: 14.17.6
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cli                    13.3.7
@schematics/angular             13.3.7
rxjs                            7.5.5
typescript                      4.6.4</code></pre>

**Anything else relevant?**

I was not able to reproduce the issue if I selected "CSS" instead of "SCSS" when creating the SPA.

**Comment by alan-agius4** [comment]
This will be fixed once you update your project CLI to version 14. 

As an interim solution you can also downgrade the global CLI to version 13

**Comment by Blackbaud-PaulCrowder** [comment]
> This will be fixed once you update your project CLI to version 14.
> 
> As an interim solution you can also downgrade the global CLI to version 13

We did downgrade to Angular CLI 13 to get around the issue, but this is going to be problematic for developers who are maintaining both Angular 14 and Angular 13 projects or are gradually migrating multiple SPAs.

**Comment by Fly1nP4nda** [comment]
I encountered a similar issue here running `ng build` alone and using a global CLI version of 14 and a version 13 (and lower) project CLI. Downgrading did fix the issue but not ideal as @Blackbaud-PaulCrowder mentioned. 

My company CI (Concourse) builds were hanging indefinitely without any output until I associated it to the v14 release on 6/2
