### ISSUE TITLE
webstorm debugging only works after live reload or alert() statement

### ISSUE THREAD

**Issue by jasekiw** [angular/angular-cli#2328]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 4.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng serve --host 0.0.0.0 --port 4200 
setup webstorm debugging
urL: http://localhost:4200/
project remote url: webpack:///C:/Users/Jason/test-site
src remote url: webpack:///C:/Users/Jason/test-site/src
put break point in app.component.ts
break point is not hit.
put alert before break point.
break point is hit.
or if live reload is called, the break point is hit
4. The log given by the failure. Normally this include a stack trace and some
   more information.

No log available

**Comment by filipesilva** [comment]
I'm sorry but specific editor debugging integrations are out of scope for the CLI. If you are able to find the problem and submit a PR that fixes in a low impact way, we can review it.
