### ISSUE TITLE
 Generating browser application bundles (phase: sealing)...runtime: out of memory: cannot allocate 4194304-byte block (24838144 in use) fatal error: out of memory

### ISSUE THREAD

**Issue by danishkhan3621** [angular/angular-cli#23295]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes this happened when modified the Angular CLI version: ....

### Description

I want to create a build but when i run ng build  getting this error :
Generating browser application bundles (phase: sealing)...runtime: out of memory: cannot allocate 4194304-byte block (24838144
in use)
fatal error: out of memory when i delete my node modules folder and then reinstall it then i can create build but for only 1-2 times then again same error

## 🔥 Exception or Error

<pre><code>
 Generating browser application bundles (phase: sealing)...runtime: out of memory: cannot allocate 4194304-byte block (24838144
in use)
fatal error: out of memory

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI 12.2.11
Node 14.15.4
Package Managed : npm 6.14.10
OS win32 ia32
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
It appears that you have an incorrect version of Node.js installed (win32 ia32). Unless your OS is 32bit.

You can use [NVM](https://github.com/coreybutler/nvm-windows) to easily manage Node.js versions or download the 64Bit LTS versions from [Node.js downloads page](https://nodejs.org/en/download/).

**Comment by danishkhan3621** [comment]
Thanks @alan-agius4  This resolved the issues
