### ISSUE TITLE
Implement cache busting in the webpack flow

### ISSUE THREAD

**Issue by jasekiw** [angular/angular-cli#2329]
When is cache busting planned to be implemented?

I can see the ng build does not include cache busting.

Thanks

**Comment by kylecordes** [comment]
A production build ```ng build -prod``` includes a hash in the filename of the output bundles - is that when you mean by "cache busting"? Or something else?

**Comment by jasekiw** [comment]
This is actually what I mean. Must have missed that documentation, thanks!
