### ISSUE TITLE
v14: Error using modules in @schematics/angular/utility

### ISSUE THREAD

**Issue by michaelfaith** [angular/angular-cli#23290]
# 🐞 Bug report

### Is this a regression?

Yes, this worked in 13.2

### Description

My schematics unit tests are failing now, with an error:
`ENOENT: no such file or directory, open 'D:\src\fabric\node_modules\@schematics\angular\utility\test.js'`

Looking at the package structure on disk, it has an `index.js` under `utility/test`, but the package.json is directing everything under utility to `./utility/*.js`

```
"exports": {
    "./package.json": "./package.json",
    "./utility": "./utility/index.js",
    "./utility/*": "./utility/*.js",
    "./migrations/migration-collection.json": "./migrations/migration-collection.json",
    "./*": "./*.js",
    "./private/components": "./private/components.js"
  },
```

![image](https://user-images.githubusercontent.com/8071845/171937353-92033f36-7ce7-40cc-b547-086fab8721f6.png)

There is indeed no `test.js`.  So either it'd either need a test.js emitted or exports updated to include `utility/test`

## 🔥 Exception or Error

<pre><code>
ENOENT: no such file or directory, open 'D:\src\fabric\node_modules\@schematics\angular\utility\test.js'

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.0.0
Node: 16.14.2
Package Manager: yarn 1.22.18
OS: win32 x64
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             14.0.0
ng-packagr                      14.0.0
rxjs                            7.5.5
typescript                      4.7.2

</code></pre>

**Comment by alan-agius4** [comment]
Only `@schematics/angular/utility` is considered as public API that can be used externally.

Others paths, including sub paths are considered private APIs. `"./utility/*"` was added to allow `@angular/material` to gradually migrate to the public API.

**Comment by michaelfaith** [comment]
Thanks.  And yeah, I believe our approach was inspired by what material did.  So I guess we'll have to move off of it too.  Appreciate the feedback.
