### ISSUE TITLE
ng build --production does not fully uglify js classes

### ISSUE THREAD

**Issue by Jstreez** [angular/angular-cli#23317]
# 🐞 Bug report

### Command (mark with an `x`)

ng build --configuration production

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

Same, minification/uglification still appears to be incomplete or is this by design and intentional?

### Description

When creating a production angular build the output javascript bundles seem to be minified and uglified, but not to the extent that I was expecting.

When looking into the outputted files in the dist folder, parts of the file are indeed minified and uglified. Other parts of the file are in plain javascript and expose quite a lot about the application.

I have attached an example image whereby one can clearly read the app component in the main bundle after being minified and uglified. I would have expected this code to have been obfuscated too.

## 🔬 Minimal Reproduction

ng new repro-app

Ensure optimization is enabled on angular json for production

ng build --configuration production

Review the outputted bundles and see that for most angular components, the source code is human readable

## 🌍 Your Environment

node v18
npm v8

![Screenshot 2022-06-07 at 11 21 26](https://user-images.githubusercontent.com/107034467/172570772-e26ba678-c39f-408c-877d-daff621aa448.png)

**Comment by alan-agius4** [comment]
This is working as intended.

Mangling properties of objects and classes is considered dangerous and in most cases it is a code-breaking option unless used in a controlled environment example when not using 3rd party libraries.

It is also important to point out that the intended goal of mangling is to reduce the file size and not to increase the security of the application. If there is logic that shouldn't be accessible by the client then it would be better to place it to an API.
