### ISSUE TITLE
.angular-config.json not found in v14

### ISSUE THREAD

**Issue by ajuni880** [angular/angular-cli#23310]
Hi there,
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 13.3.10

### Description

I have installed the new version (v14) of angular, generated a workspace with one app. Integrated the repo with gitlab pipeline, inside the pipeline when running the `ng build -c production` it fails due to `ENOENT: no such file or directory, open '/nonexistent/.angular-config.json'`.

After digging to find the existence of `.angular-config.json` I found it in `~/.angular-config.json` in my local machine.

I deleted the mentioned file(from my machine), and run again the `ng build -c production` but it recreates again the file but first asks if I want to enable auto-completion and then it generates the file.

```json
{
  "cli": {
    "analytics": false
  },
  "version": 1
}
```

After downgrading the angular version to 13.3.10 the pipeline worked. And when running the build production command it does not generate the `.angular-config.json` file.

## 🔥 Exception or Error

<pre><code>
ENOENT: no such file or directory, open '/nonexistent/.angular-config.json'.

</code></pre>

## 🌍 Your Environment

<pre><code>
gitlab runner with node v14.
</code></pre>

**Anything else relevant?**

The build command generates the dist folder locally without the mentioned error.

**Comment by ajuni880** [comment]
@alan-agius4 thanks for the reply, should I close this issue then?

**Comment by alan-agius4** [comment]
@ajuni880 let’s close it for now. Feel free to re-open if it’s not solved in `@angular/cli@14.0.1`.
