### ISSUE TITLE
PWA ng-add schematic does not work if bootstrapApplication is used (standalone)

### ISSUE THREAD

**Issue by ngfelixl** [angular/angular-cli#23316]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

In the previous version of Angular (13) there was no support for standalone components.

### Description

The ng-add schematic for the package `@angular/pwa` does not work if the app bootstraps using `bootstrapApplication` from `@angular/platform-browser` instead of the good old `bootstrapModule` function in the apps **main.ts** file.

## 🔬 Minimal Reproduction

1.) Create a new Angular app with version 14:

```
npx @angular/cli@14 new pwa-test-app
cd pwa-test-app
```

2.) Remove the **app.module.ts** file and change the **app.component.ts** decorator to

```ts
@Component({
  standalone: true,
  selector: 'app-root',
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
```

3.) Change the **main.ts** file to

```ts
import { enableProdMode } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

bootstrapApplication(AppComponent);
```

4.) ng-add @angular/pwa

Run

```
npx ng add @angular/pwa
```

Answer yes to the following terminal output

```
ℹ Using package manager: npm
✔ Found compatible package version: @angular/pwa@14.0.0.
✔ Package information loaded.

The package @angular/pwa@14.0.0 will be installed and executed.
Would you like to proceed? (Y/n) y
```

## 🔥 Exception or Error

<pre><code>
Bootstrap call not found
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.0.0
Node: 16.14.0
Package Manager: npm 8.3.1 
OS: darwin x64

Angular: 14.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.3
</code></pre>

I would be very happy to support you with this issue if some guidance is provided.

**Comment by ngfelixl** [comment]
Instead of only looking for `bootstrapModule`, it should also search for `bootstrapApplication`. If the first one is found, nothing to be changed. If the second one is found it should add it to the providers array as it does for modules:

```ts
import { importProvidersFrom } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
// [...]

bootstrapApplication(AppComponent, {
  providers: [
    importProvidersFrom(
      ServiceWorkerModule.register('ngsw-worker.js', {
        enabled: environment.production,
        // Register the ServiceWorker as soon as the application is stable
        // or after 30 seconds (whichever comes first).
        registrationStrategy: 'registerWhenStable:30000',
      })
    ),
  ],
});

```

**Comment by clydin** [comment]
Developer Preview APIs currently do not have full tooling support.  Additional tooling support for Standalone Components will be added in the 14.x timeframe as the APIs are stabilized.

**Comment by ngfelixl** [comment]
I see! Thanks for the clarification 😊

**Comment by sefatanam** [comment]
i'm faced same issue today, detail I described here https://stackoverflow.com/questions/73274104/ng-add-angular-pwa-bootstrap-call-not-found-in-angular-standalone-project. Look forward to it ....

**Comment by DDD-fx** [comment]
Still waiting for the fix

**Comment by Yutsa** [comment]
Today I tried to add angular-pwa to my project running Angular v15 but unfortunately it still does not work with `bootstrapApplication` : 

```
The package @angular/pwa@15.2.4 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Bootstrap call not found

```

This is not a preview feature anymore right ?

**Comment by alan-agius4** [comment]
This is available in version 16 which is currently in prerelease.

**Comment by alan-agius4** [comment]
Closing as per above.
