### ISSUE TITLE
[Feature Request] Please add an option to watch changes

### ISSUE THREAD

**Issue by gperdomor** [angular/angular-cli#2332]
Hi :D...

ng serve is a great tool, but sometime, we need to write the files in some directory, for example to use with an express server inside the same repository (Yes, i know, angular is a frontend tool and should live in a separate repository, but is not always that way)...

So, i was thinking in something like `ng watch` which detect changes and compiles with webpack, without running the lite-server

**Comment by kingjordan** [comment]
I agree, My angular apps are often embedded in a web CMS and therefore they need to be compiled and delivered by a different server than the ng serve for development.  Having an "ng watch" that compiles changes ts files would be perfect

**Comment by TheLarkInn** [comment]
Would `ng build --watch` and then `run my lite server` in parallel not work currently?

**Comment by filipesilva** [comment]
The solution recommended by @TheLarkInn should work.
