### ISSUE TITLE
Lazy loading Routing

### ISSUE THREAD

**Issue by jeffnyalik** [angular/angular-cli#23331]
For  some reasons this code does not work when it comes to Lazy loading:
from the docs: https://angular.io/guide/lazy-loading-ngmodules

`{ path: 'orders', loadChildren: () => import('./modules/orders/orders.module').then(m => m.OrdersModule) },`

You have to do it this way for it to work:
`{ path: 'orders', loadChildren: () => OrdersModule}`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
