### ISSUE TITLE
Adding angular-cli to existing project

### ISSUE THREAD

**Issue by RodEsV** [angular/angular-cli#2334]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux ubuntu 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.3.1
os: linux x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I made an app using angular rc 6 without angular-cli, I wrote some modules, and I was using Ng2Bs3Modal for managing modal bootstrap in angular, I changed some inserts in systemjs.config
in order to that worked!

4. The log given by the failure. Normally this include a stack trace and some
   more information.

> rustick-stock@0.0.0 start /home/rodesv/projects/FRONT/rusticstock
> ng serve

EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:731:19)
    at tryReadSync (fs.js:486:20)
    at Object.fs.readFileSync (fs.js:534:19)
    at Object.getSource (/home/rodesv/projects/FRONT/rusticstock/node_modules/@angular-cli/ast-tools/src/ast-utils.js:25:45)
    at findLoadChildren (/home/rodesv/projects/FRONT/rusticstock/node_modules/angular-cli/models/find-lazy-modules.js:8:30)
    at /home/rodesv/projects/FRONT/rusticstock/node_modules/angular-cli/models/find-lazy-modules.js:46:9
    at Array.forEach (native)
    at Object.findLazyModules (/home/rodesv/projects/FRONT/rusticstock/node_modules/angular-cli/models/find-lazy-modules.js:45:10)
    at Object.getWebpackCommonConfig (/home/rodesv/projects/FRONT/rusticstock/node_modules/angular-cli/models/webpack-build-common.js:18:43)
    at new NgCliWebpackConfig (/home/rodesv/projects/FRONT/rusticstock/node_modules/angular-cli/models/webpack-config.js:13:30)
    at Class.exports.default.Task.extend.run (/home/rodesv/projects/FRONT/rusticstock/node_modules/angular-cli/tasks/serve-webpack.js:19:22)
    at /home/rodesv/projects/FRONT/rusticstock/node_modules/angular-cli/commands/serve.js:84:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! rustick-stock@0.0.0 start: `ng serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the rustick-stock@0.0.0 start script 'ng serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the rustick-stock package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs rustick-stock
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls rustick-stock
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rodesv/projects/FRONT/rusticstock/npm-debug.log

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rolandoldengarm** [comment]
Why do you have a systemjs config when you're using the webpack version?

**Comment by RodEsV** [comment]
The last version comes with webpack! 
I started it using systemjs and I'm not comfortable with webpack

**Comment by rolandoldengarm** [comment]
sorry but you should not use (or even can't use) systemjs with .beta-15, you'll need to downgrade to .beta-10

**Comment by RodEsV** [comment]
Is that a disadvantage ?
Can I ask you something ?
Is there any resource to learn webpack ?

**Comment by rolandoldengarm** [comment]
Github is not meant for support, but I can tell you that Webpack is blackboxed in Angular CLI, so you don't need to know how it works. 
With the old systemjs version you had to update systemjs config; with the Webpack version you can't even change the config.
So, you don't need to learn much about webpack when using Angular CLI.

**Comment by RodEsV** [comment]
So can I just copy and paste my app/source folder to the angular click
project ?
Thanks in advance

**Comment by filipesilva** [comment]
@rolandoldengarm advice is quite accurate. The CLI blackboxes a lot of things so mix-and-matching parts from different setups is not recommended. 

My recomendation for transitioning a project *into* the CLI is to make a brand new project via `ng new project-name`, then copy your TS Angular application into `src/`.
