### ISSUE TITLE
ng add @angular/pwa generate an unhandled exception occurred: Cannot find module '@schematics/angular/utility'

### ISSUE THREAD

**Issue by k4rm3l0** [angular/angular-cli#23343]
# 🐞 Bug report

### Command
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description
Command "ng add @angular/pwa" generate an unhandled exception occurred: Cannot find module '@schematics/angular/utility'

## 🔬 Minimal Reproduction

ng add @angular/pwa --project my.project

## 🔥 Exception or Error
ℹ Using package manager: npm
✔ Found compatible package version: @angular/pwa@14.0.0.
✔ Package information loaded.

The package @angular/pwa@14.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
An unhandled exception occurred: Cannot find module '@schematics/angular/utility'
Require stack:
- myproject/node_modules/@angular/cli/models/schematic-engine-host.js
See "/private/var/folders/kk/7f9l6gdn0mjcvzmzbn9vfxz40000gn/T/ng-lcv9gi/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 13.3.7
Node: 16.14.0
Package Manager: npm 8.3.1
OS: darwin arm64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cli                    13.3.7
@schematics/angular             13.3.7
rxjs                            7.5.5
typescript                      4.6.4
</code></pre>

**Comment by k4rm3l0** [comment]
@alan-agius4 it worked!

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/23344
