### ISSUE TITLE
Cannot run ng serve after updating Angular 13 to 14.0.1

### ISSUE THREAD

**Issue by steven-fernandez** [angular/angular-cli#23352]
### Which @angular/* package(s) are the source of the bug?

animations, common, compiler-cli, core, forms, router, upgrade

### Is this a regression?

No

### Description

After updating Angular 13 to 14.0.1 and I try to run "ng serve" I get this error:

This version of CLI is only compatible with Angular versions ^13.0.0 || ^13.3.0-rc.0,
but Angular version 14.0.1 was found instead.

Why? Any ideas?

### Please provide the exception or error you saw

```true
This version of CLI is only compatible with Angular versions ^13.0.0 || ^13.3.0-rc.0,
but Angular version 14.0.1 was found instead.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.1
Node: 14.17.0
OS: Windows 10
Angular: 14.0.1
... animations, cli, common, core, forms, router
```

**Comment by alan-agius4** [comment]
Are you using custom builders?

**Comment by steven-fernandez** [comment]
No, no custom builders...just the standard

**Comment by alan-agius4** [comment]
Can you please provide the output of `npm ls @angular-devkit/build-angular`?

**Comment by michaelbuller** [comment]
@alan-agius4 I am having the same issue and ran `npm ls @angular-devkit/build-angular` 

 npm ls @angular-devkit/build-angular

├─┬ @angular-builders/custom-webpack@13.1.0
│ └── @angular-devkit/build-angular@13.3.7
└── @angular-devkit/build-angular@14.0.1
I assume this means the the custom-webpack is the issue?

**Comment by alan-agius4** [comment]
@michaelbuller, in your case you are using 3rd party builders which don’t support Angular 14. See: https://github.com/just-jeb/angular-builders/issues/1219

**Comment by steven-fernandez** [comment]
> @alan-agius4 I am having the same issue and ran `npm ls @angular-devkit/build-angular`
> 
> npm ls @angular-devkit/build-angular
> 
> ├─┬ @angular-builders/custom-webpack@13.1.0 │ └── @angular-devkit/build-angular@13.3.7 └── @angular-devkit/build-angular@14.0.1 I assume this means the the custom-webpack is the issue?

```
+-- @angular-builders/custom-webpack@13.0.0        
| `-- @angular-devkit/build-angular@13.3.7  deduped
`-- @angular-devkit/build-angular@13.3.7
```

**Comment by alan-agius4** [comment]
@steven-fernandez, it seems that you are also using 3rd party custom builders which are not supported by the Angular team.

Please see https://github.com/just-jeb/angular-builders/issues/1219

**Comment by just-jeb** [comment]
`@angular-builders/custom-webpack@14` has been released, please update and it will solve the problem.

**Comment by steven-fernandez** [comment]
> `@angular-builders/custom-webpack@14` has been released, please update and it will solve the problem.

Updating this fixed the issue...thanks :)

**Comment by steven-fernandez** [comment]
> `@angular-builders/custom-webpack@14` has been released, please update and it will solve the problem.

Updating this fixed the issue...thanks :)
