### ISSUE TITLE
Cannot read properties of undefined (reading 'add')  in angular 14?

### ISSUE THREAD

**Issue by kapilSoni101** [angular/angular-cli#23356]
Hi Team,
I have migrate my project 8 to 14 version i have remove all errors during compile time as well as run time but after serve the project 
I got below error in the console:

**`Cannot read properties of undefined (reading 'add')`**

![image](https://user-images.githubusercontent.com/26578635/173279506-02394e47-7751-4941-a559-4ad5f78faf34.png)

![image](https://user-images.githubusercontent.com/26578635/173279819-392ece69-5275-42d3-8984-ca2767278d84.png)

**package.json**
`  "dependencies": {
    "@agm/core": "^1.0.0-beta.6",
    "@angular/animations": "~14.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~14.0.0",
    "@angular/compiler": "~14.0.0",
    "@angular/core": "~14.0.0",
    "@angular/forms": "~14.0.0",
    "@angular/platform-browser": "~14.0.0",
    "@angular/platform-browser-dynamic": "~14.0.0",
    "@angular/router": "~14.0.0",
    "@aspnet/signalr": "^1.1.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@progress/kendo-angular-buttons": "^5.0.0",
    "@progress/kendo-angular-charts": "^6.0.0",
    "@progress/kendo-angular-common": "^1.0.0",
    "@progress/kendo-angular-dateinputs": "^4.0.0",
    "@progress/kendo-angular-dropdowns": "^4.0.0",
    "@progress/kendo-angular-excel-export": "^3.0.0",
    "@progress/kendo-angular-grid": "^4.1.1",
    "@progress/kendo-angular-inputs": "^6.0.0",
    "@progress/kendo-angular-intl": "^2.0.0",
    "@progress/kendo-angular-l10n": "^2.0.0",
    "@progress/kendo-angular-pdf-export": "^2.0.0",
    "@progress/kendo-angular-popup": "^3.0.0",
    "@progress/kendo-angular-upload": "^6.0.0",
    "@progress/kendo-data-query": "^1.0.0",
    "@progress/kendo-drawing": "^1.0.0",
    "@progress/kendo-licensing": "^1.2.2",
    "@progress/kendo-theme-default": "latest",
    "@types/moment-timezone": "^0.5.12",
    "bootstrap": "^3.3.7",
    "classlist.js": "^1.1.20150312",
    "croppie": "^2.6.4",
    "google-libphonenumber": "^3.2.2",
    "hammerjs": "^2.0.8",
    "jquery": "^3.6.0",
    "moment": "^2.29.3",
    "moment-timezone": "^0.5.25",
    "ng-lazyload-image": "^9.1.0",
    "ng-search-filter": "^1.1.0",
    "ng2-search-filter": "^0.5.1",
    "ngx-device-detector": "^1.3.9",
    "ngx-print": "^1.2.1",
    "ngx-toastr": "^14.0.0",
    "oidc-client": "^1.7.1",
    "rxjs": "~7.5.5",
    "rxjs-compat": "^6.6.7",
    "stacktrace-js": "^2.0.0",
    "ts.validator.fluent": "^1.3.0",
    "tslib": "^2.4.0",
    "typescript-collections": "^1.3.2",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.0.0",
    "@angular-devkit/build-ng-packagr": "~0.801.3",
    "@angular/cli": "~14.0.0",
    "@angular/compiler-cli": "~14.0.0",
    "@angular/language-service": "~14.0.0",
    "@angular/localize": "^14.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/moment": "^2.13.0",
    "@types/node": "^8.9.5",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.3.20",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "ng-packagr": "^14.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tsickle": "^0.35.0",
    "tslint": "~5.15.0",
    "typescript": "~4.7.2"

-   }`

Team Can you please let me know what's the issue on that and how to fix it?

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Brandinga** [comment]
maybe because rxjs 7.x is not compatible with rxjs-compat 6.x

see: https://rxjs.dev/deprecations/breaking-changes

**Comment by alan-agius4** [comment]
@Brandinga, good catch. That might indeed be the root cause.

**Comment by kapilSoni101** [comment]
@Brandinga  thanks for the update sir......so now update rxjs-compat to 7 correct?

**Comment by alan-agius4** [comment]
@kapilSoni101, there is no `rxjs-compat` version 7. You need to update your code to be compatible with `rxjs` 7. Alternatively you can also downgrade `rxjs` to `^6.5.3`.

**Comment by kapilSoni101** [comment]
@alan-agius4 sir now my updated version of both rxjs and rxjs-compat is 
**"rxjs": "^6.6.7",
    "rxjs-compat": "^6.5.2"**

**Comment by alan-agius4** [comment]
@kapilSoni101, in that case we'd require a minimal reproduction to investigate any further.

**Comment by kapilSoni101** [comment]
@alan-agius4 sir actually issue is that my project is like a workspace in which 4 projects are added in single workspace so not possible to share all workspace

**Comment by alan-agius4** [comment]
@kapilSoni101, without a minimal reproduction we cannot investigate to determine if there is a bug or not.

**Comment by kapil26021994** [comment]
@alan-agius4 yes sir I agree with you but in my project it's a workspace it's including 4 different projects so it's difficult to share in repo.

**Comment by alan-agius4** [comment]
@kapilSoni101, I am not expecting you to share the entire workspace, but a minimal reproduction.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by kapilSoni101** [comment]
@alan-agius4 my issue fixed after remove  rxjs-compat from package.json?

**Comment by alan-agius4** [comment]
Unfortunately, we are unable to look any further into this issue as a reproduction was not provided. 

If the problem persists please open a new issue, provide a simple repository reproducing the problem. You can use `ng new repro-app` to create a new project where you reproduce the problem.
