### ISSUE TITLE
ng update @angular/core@14 got Package '@angular/core' is not a dependency.

### ISSUE THREAD

**Issue by chengB12** [angular/angular-cli#23368]
# 🐞 Bug report

### Command (mark with an `x`)

- [ X] update

### Is this a regression?

Yes, I used ng update to upgrade angular from v12 to v13, and there is no issue
### Description

when I use yarn ng update @angular/core@14 @angular/cli@14 --force --verbose 
I got 
<code>
Locating potential npmrc files:
Using package manager: npm
Collecting installed dependencies...
Found 0 dependencies.
Package '@angular/core' is not a dependency.
error Command failed with exit code 1.
</code>

## 🔬 Minimal Reproduction

I use yarn v1.22.7 instead of npm
yet log show ng update picked npm:
Using package manager: npm

I also use child packages, instead of root, while all 3rd packages installed on root

root/package.json
<code>
{
 "dependencies": {
    "@angular/core": "^13.0.1",
    ...
 },
"workspaces": [
    "packages/*"
  ]
}
</code>
root/packages/angular-app/package.json
root/packages/angular-app/angular.json

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 14.0.1
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.2
@angular-devkit/core         14.0.1
@angular-devkit/schematics   14.0.1
@schematics/angular          14.0.1
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
The CLI is likely picking npm as a package manager because either you have a `package-lock.json` or/and lack of `yarn-lock` file. 

You can configure which package manager the CLI uses the using the below command:
```
ng config cli.packageManager yarn
```

Yarn workspaces are not fully supported, please see: https://github.com/angular/angular-cli/issues/14841
