### ISSUE TITLE
Official procedure of update Angular 9.0 to 10.0 fails

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [angular/angular-cli#23366]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.0 and few months ago with v10 as well.

### Description

From clean project (generated with ng new) I'm not able to perform an upgrade from Angular v9 to Angular v10 without using a workaround ([link](https://github.com/angular/angular-cli/issues/22099#issuecomment-961870699)).

By the way the behavior is not consistent with the CLI code https://github.com/angular/angular-cli/blob/10.2.x/packages/angular/cli/lib/cli/index.ts#L31.

## 🔬 Minimal Reproduction

<pre><code>
npm install -g @angular/cli@9
ng new TestUpgrade
ng update @angular/core@10 @angular/cli@10
</code></pre>

## 🔥 Exception or Error

<pre><code>
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Node.js version v12.22.1 detected.
The Angular CLI requires a minimum Node.js version of either v14.15, or v16.10.
</code></pre>

## 🌍 Your Environment

<pre><code>
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.1.13
Node: 12.22.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.901.13
@angular-devkit/core         9.1.13
@angular-devkit/schematics   9.1.13
@schematics/angular          9.1.13
@schematics/update           0.901.13
rxjs                         6.5.4
</code></pre>

**Anything else relevant?**

- Similar issue [!22099](https://github.com/angular/angular-cli/issues/22099)

Current workaround ([link](https://github.com/angular/angular-cli/issues/22099#issuecomment-961870699))

```shell
NG_DISABLE_VERSION_CHECK=1 ./node_modules/.bin/ng update @angular/cli@10 @angular/core@10
```

**Comment by alan-agius4** [comment]
@alexis-landrieu-avanade, thanks for reporting this issue however this issue was already solved in more recent versions of Angular CLI. 

Please be aware that Angular versions prior to 12 are no longer under support. For more information about our support policy please see https://angular.io/guide/releases#support-policy-and-schedule
