### ISSUE TITLE
impossible to install angular with Ubuntu

### ISSUE THREAD

**Issue by Ep0ke** [angular/angular-cli#2336]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux Ubuntu

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

node version: 4.2.6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

I tried only to install angular via the terminal and in phpstorm

4. The log given by the failure. Normally this include a stack trace and some
   more information.

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng

> node-zopfli@1.4.0 install /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/.node-gyp"
make : on entre dans le répertoire « /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build »
make: ***  Aucune règle pour fabriquer la cible « ../.node-gyp/4.2.6/include/node/common.gypi », nécessaire pour « Makefile ». Arrêt.
make : on quitte le répertoire « /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-38-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/angular-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64' (1)
/usr/local/lib
└── angular-cli@1.0.0-beta.15 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/angular-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 (node_modules/angular-cli/node_modules/node-zopfli):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

5. Mention any other details that might be useful.

i have updated minimatch and graceful but it has'nt change anything

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jimmyjamieson** [comment]
Try node 6 with the newer version of npm

**Comment by Ep0ke** [comment]
i did but still i have this problem : 

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng

> node-zopfli@1.4.0 install /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
make : on entre dans le répertoire « /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build »
  CXX(target) Release/obj.target/zopfli/src/zopfli-binding.o
  CXX(target) Release/obj.target/zopfli/src/png/zopflipng.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/blocksplitter.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/cache.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/deflate.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/gzip_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/hash.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/katajainen.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/lz77.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/squeeze.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/tree.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/util.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zlib_container.o
  CC(target) Release/obj.target/zopfli/zopfli/src/zopfli/zopfli_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/zopflipng_lib.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng.o
  CXX(target) Release/obj.target/zopfli/zopfli/src/zopflipng/lodepng/lodepng_util.o
  SOLINK_MODULE(target) Release/obj.target/zopfli.node
  COPY Release/zopfli.node
  COPY /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node
  TOUCH Release/obj.target/action_after_build.stamp
make : on quitte le répertoire « /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build »
/usr/local/lib
└─┬ angular-cli@1.0.0-beta.15 
  ├─┬ compression-webpack-plugin@0.3.1
  │ └─┬ node-zopfli@1.4.0 
  │   ├── defaults@1.0.3 
  │   └─┬ node-pre-gyp@0.6.30 
  │     ├─┬ rc@1.1.6 
  │     │ └── ini@1.3.4 
  │     └─┬ tar-pack@3.1.4 
  │       ├── fstream-ignore@1.0.5 
  │       ├── once@1.3.3 
  │       ├─┬ readable-stream@2.1.5 
  │       │ └── buffer-shims@1.0.0 
  │       └── uid-number@0.0.6 
  └─┬ npm-run-all@3.1.0
    └── cross-spawn@4.0.2 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/angular-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by jimmyjamieson** [comment]
You might be missing some build tools. Try having a look at https://github.com/nodejs/node-gyp and http://www.hostingadvice.com/how-to/install-nodejs-ubuntu-14-04/

**Comment by Ep0ke** [comment]
Well i've checked and i'm also blocked with Grunt.. i have intalled it via NPM but it's not recognize when i call it...

Any clue ?

**Comment by filipesilva** [comment]
Please ensure your environment has the prerequisites: https://github.com/angular/angular-cli#prerequisites

I don't see any npm errors in the log you provided, see https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794 for more information about npm installs and node-gyp errors.

**Comment by shajay12** [comment]
Hi Everyone, Let me know if Angular JS is installed on my Ubuntu machine. 
node --version && ng --version
v8.11.3
The program 'ng' is currently not installed. You can install it by typing:
apt install ng-common
root@ssbroot-OptiPlex-3050:/opt#
"node version" gives output, but "ng version" does not gives any output. 

and How can i install Angular JS from TAR file, as internet is not available on my machine.
