### ISSUE TITLE
Add schema.json to package.json exports for @schematics/angular

### ISSUE THREAD

**Issue by james-schwartzkopf** [angular/angular-cli#23373]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I'm guessing this wasn't officially supported, so I guess this isn't a regression. 

I maintain a set of schematics that extend the @schematics/angular ones by using externalSchematic to call the @schematics/angular one, then adding my own changes.

One of the hardest parts when ever we upgrade angular versions is keeping up with changes to the options the base schematics support.  

To help with this, we have a set of unit test that compare the schema in @schematics/angular/*/schema.json to the schema for our schematic.

```
describe('Verify schema', () => {
  it('base schema has not changed', () => {
    let baseOptions = readJSON('@schematics/angular/component/schema.json').properties as SchemaProps;
    baseOptions = stripUserAnalytics(baseOptions);
    delete baseOptions.entryComponent;
    delete baseOptions.lintFix;

    let options = readJSON('src/table-component/schema.json').properties as SchemaProps;
    options = stripSnapOptions(options);
    options = stripUserAnalytics(options);

    options.displayBlock.default = false;
    options.style.default = 'css';

    expect(baseOptions).toEqual(options);
  });
});
```

With the update to Angular 14, these test broke.  require.resolve was no longer able to find the schema.json file.

Adding ```"./*/schema.json": "./*/schema.json"``` to the @schematics/angular/package.json exports allowed the test to pass.

Would you consider adding the schema.json to the package.json exports?

### Describe the solution you'd like

I would like to see the schema.json files added to the package.json exports.

### Describe alternatives you've considered

I'd have to find a different way to discover when new options are added or changed to keep my schematics in sync.

**Comment by alan-agius4** [comment]
This seems quite an edge case which should be pretty straight forward to resolve without modifying the package.


```js
const p = path.join(
  require.resolve(
    "@schematics/angular/package.json",
    "../component/schema.json"
  )
);
```

The above will return the resolve schema path, which that can be used to read the file.

**Comment by clydin** [comment]
In addition to the above, the schema location and filename within a package can be arbitrary. The canonical method to retrieve the JSON schema for a given schematic involves several steps:

1. Resolve and read a package's `package.json` file.
2. Access the `schematics` field and read the Schematics collection file at the specified location (paths are relative to the `package.json` file).
3. Access the schematic's entry in the collection file and use the `schema` field to find the location of the schematic's JSON schema (paths are relative to the collection file).
