### ISSUE TITLE
Running ng update @angular/core@13 @angular/cli@13 result on "No matching version found for @angular-devkit/architect@0.1303.8"

### ISSUE THREAD

**Issue by ignaciostellino** [angular/angular-cli#23378]
# 🐞 Bug report

### Command (mark with an `x`)

Running the command ng update @angular/core@13 @angular/cli@13 gives error "No matching version found for @angular-devkit/architect@0.1303.8".
I check npm page for devkit/architect https://www.npmjs.com/package/@angular-devkit/architect and I don't see version 0.1303.8 
- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Angular CLI: 12.2.17
Node: 12.22.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.2.16

Run ng update @angular/core@13 @angular/cli@13

## 🔥 Exception or Error

<pre><code>

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/architect@0.1303.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget
</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by jchrisjones** [comment]
I am getting this error too.

**Comment by stefnedelchev** [comment]
Confirmed, I get the same error

**Comment by simplejason** [comment]
Same error :(
```bash
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/build-webpack@0.1303.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@angular-devkit/build-angular'
npm ERR! notarget 
```

**Comment by agfonte** [comment]
Same error as well

**Comment by oritpersik** [comment]
Same error as well

**Comment by alan-agius4** [comment]
This is because we are currently cutting a release. Should be okay now.

**Comment by oritpersik** [comment]
Works. tnx.

**Comment by ignaciostellino** [comment]
Working now. Thank you! :)
