### ISSUE TITLE
Missing integrity attribute for lazy-loaded module in Angular 14

### ISSUE THREAD

**Issue by mredaelli** [angular/angular-cli#23370]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: latest 13

### Description
We just ported our project to Angular 14, and suddenly started getting this error:

> the script element has a malformed attribute in its integrity attribute: "undefined"

we tracked it down to a module being lazily loaded. Looking around, we found that its entry being missing from the `sriHashes` object in `runtime.js`.

Since:
- there is only one chunk missing in the object, and it's the one with `id` `0`,  and
-  adding `"namedChunks": true,` to the build configuration seems to solve the problem.

it is for me very tempting to think that it is excluded from the dict because it's falsy. But I'm far from being able to check this.

## 🔥 Exception or Error

<pre><code>
runtime.aee066f47596daf1.js:1 Error parsing 'integrity' attribute ('undefined'). The hash algorithm must be one of 'sha256', 'sha384', or 'sha512', followed by a '-' character.
r.l @ runtime.aee066f47596daf1.js:1
r.f.j @ runtime.aee066f47596daf1.js:1
(anonymous) @ runtime.aee066f47596daf1.js:1
r.e @ runtime.aee066f47596daf1.js:1
loadChildren @ 481.e2b93596f818f247.js:1
loadModuleFactoryOrRoutes @ main.310f6dcb216b5b59.js:1
loadChildren @ main.310f6dcb216b5b59.js:1
(anonymous) @ main.310f6dcb216b5b59.js:1
preload @ main.310f6dcb216b5b59.js:1
preloadConfig @ main.310f6dcb216b5b59.js:1
processRoutes @ main.310f6dcb216b5b59.js:1
processRoutes @ main.310f6dcb216b5b59.js:1
processRoutes @ main.310f6dcb216b5b59.js:1
(anonymous) @ main.310f6dcb216b5b59.js:1
Z @ main.310f6dcb216b5b59.js:1
G @ main.310f6dcb216b5b59.js:1
_next @ main.310f6dcb216b5b59.js:1
next @ main.310f6dcb216b5b59.js:1
_next @ main.310f6dcb216b5b59.js:1
next @ main.310f6dcb216b5b59.js:1
(anonymous) @ main.310f6dcb216b5b59.js:1
o @ main.310f6dcb216b5b59.js:1
next @ main.310f6dcb216b5b59.js:1
_next @ main.310f6dcb216b5b59.js:1
next @ main.310f6dcb216b5b59.js:1
(anonymous) @ main.310f6dcb216b5b59.js:1
_next @ main.310f6dcb216b5b59.js:1
next @ main.310f6dcb216b5b59.js:1
Z.subscribe.J @ main.310f6dcb216b5b59.js:1
_next @ main.310f6dcb216b5b59.js:1
next @ main.310f6dcb216b5b59.js:1
(anonymous) @ main.310f6dcb216b5b59.js:1
invoke @ polyfills.a47fa4e6e63a4ebe.js:1
onInvoke @ main.310f6dcb216b5b59.js:1
invoke @ polyfills.a47fa4e6e63a4ebe.js:1
run @ polyfills.a47fa4e6e63a4ebe.js:1
(anonymous) @ polyfills.a47fa4e6e63a4ebe.js:1
invokeTask @ polyfills.a47fa4e6e63a4ebe.js:1
onInvokeTask @ main.310f6dcb216b5b59.js:1
invokeTask @ polyfills.a47fa4e6e63a4ebe.js:1
runTask @ polyfills.a47fa4e6e63a4ebe.js:1
_ @ polyfills.a47fa4e6e63a4ebe.js:1
Promise.then (async)
q @ polyfills.a47fa4e6e63a4ebe.js:1
R @ polyfills.a47fa4e6e63a4ebe.js:1
scheduleTask @ polyfills.a47fa4e6e63a4ebe.js:1
onScheduleTask @ polyfills.a47fa4e6e63a4ebe.js:1
scheduleTask @ polyfills.a47fa4e6e63a4ebe.js:1
scheduleTask @ polyfills.a47fa4e6e63a4ebe.js:1
scheduleMicroTask @ polyfills.a47fa4e6e63a4ebe.js:1
te @ polyfills.a47fa4e6e63a4ebe.js:1
X @ polyfills.a47fa4e6e63a4ebe.js:1
(anonymous) @ polyfills.a47fa4e6e63a4ebe.js:1
H @ runtime.aee066f47596daf1.js:1
(anonymous) @ 924.955924dd1d522bd9.js:1
Show 12 more frames

</code></pre>

## 🌍 Your Environment

<pre><code>
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 14.0.1
Node: 16.15.0
Package Manager: yarn 1.22.18
OS: linux x64

Angular: 14.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            14.0.1
@angular-devkit/schematics      14.0.1
@schematics/angular             14.0.1
rxjs                            7.5.5
typescript                      4.7.3
</code></pre>

Not sure if it's relevant, but   

>  webpack-subresource-integrity "5.1.0"

**Comment by alan-agius4** [comment]
This does indeed seem like it might be an issue with `webpack-subresource-integrity`. However without a reproduction we cannot look into this further. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by mredaelli** [comment]
How would you suggest to generate a project with a chunk with id `0`?

I'd rather not go by trial and error :)

**Comment by alan-agius4** [comment]
Yeah, that does seem suspicious.

**Comment by alan-agius4** [comment]
Lets keep tracking this https://github.com/waysact/webpack-subresource-integrity/issues/181 since this is not caused by the Angular CLI.
