### ISSUE TITLE
NG Update --force not working

### ISSUE THREAD

**Issue by eluchsinger** [angular/angular-cli#23389]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No idea. Apparently it was fixed [before](https://github.com/angular/angular-cli/issues/15296) - [multiple times](https://github.com/angular/angular-cli/issues/10149) - , but it seems like it is not working now.

### Description

Running the `ng update` command with the `--force` flag does not apply the force.

## 🔬 Minimal Reproduction

Run the command `npm run ng update @angular/cli --force` while having the package `@angular-eslint/schematics@13.2.1`. This package requires `@angular/cli` `">= 13.0.0 < 14.0.0"`.

## 🔥 Exception or Error

<pre><code>
Package "@angular-eslint/schematics" has an incompatible peer dependency to "@angular/cli" (requires ">= 13.0.0 < 14.0.0", would install "14.0.2").
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.0.2
Node: 16.15.0
Package Manager: npm 8.5.5 
OS: darwin arm64

Angular: 14.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            13.3.6
@angular-devkit/schematics      13.3.6
@schematics/angular             14.0.2
rxjs                            6.6.7
typescript                      4.7.3
webpack                         5.72.1
</code></pre>

**Anything else relevant?**

This could be an issue when running the CLI using `npm run`.

**Comment by alan-agius4** [comment]
Can you please share the full output of `ng version` as it appears that it has been truncated above and also your `package.json`? Thanks

**Comment by clydin** [comment]
`npm` requires the use of `--` prior to any flags being specified to signal to `npm` that the flags are meant for the command being run and not `npm` itself.
Example: `npm run ng update @angular/cli -- --force`

**Comment by alan-agius4** [comment]
Closing as per above comment.
