### ISSUE TITLE
VSCode: unbound breakpoints on ng serve - angular 14

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#23383]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

### Description
When debugging a newly generated application within an angular 14 workspace, breakpoints are unbound(set but ignored by VSCode)

## 🔬 Minimal Reproduction

- `>  npx @angular/cli@14 new web-apps --create-application false --strict`
- `> cd web-apps`
- `> yarn ng generate app admin-console --routing --style css`
- Open this angular workspace in VSCode and set breakpoint on Line 9 of `projects/admin-console/src/app/app.component.ts` (any valid line) 
- Start debugging 

## 🔥 Exception or Error
<img width="1547" alt="ng_14_breakpoint_vscode_unbound" src="https://user-images.githubusercontent.com/13006107/173901226-cc86361e-bfb4-49f4-bc84-17b4aa2656c7.png">

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.1.0-next.1
Node: 18.3.0 (Unsupported)
Package Manager: npm 8.11.0 
OS: darwin arm64

Angular: 14.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0-next.1
@angular-devkit/build-angular   14.1.0-next.1
@angular-devkit/core            14.1.0-next.1
@angular-devkit/schematics      14.1.0-next.1
@angular/cli                    14.1.0-next.1
@schematics/angular             14.1.0-next.1
rxjs                            7.5.5
typescript                      4.7.3
</code></pre>

```
❯ code --version
1.68.1
30d9c6cd9483b2cc586687151bcbcd635f373630
arm64
```
<img width="256" alt="vscode_version" src="https://user-images.githubusercontent.com/13006107/173901719-6275b0e6-a262-40f8-8af6-e84e3dab2364.png">

<img width="579" alt="mac_os_version" src="https://user-images.githubusercontent.com/13006107/173901752-eea3f1ce-a16d-4aa3-9aef-9526e5c4f292.png">

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Unfortunately I am unable to replicate this locally. 

One thing I noticed is that you are using an unsupported version of Node.js can you please try using an LTS version of Node.js (14 or 16).

**Comment by alan-agius4** [comment]
Closing since Node.js 18 is not yet supported.
