### ISSUE TITLE
Ng build error with `Unknown argument: configuration`

### ISSUE THREAD

**Issue by squelix** [angular/angular-cli#23385]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 13.x

### Description

When i launch the command `yarn ng run loyalty-v3:build --configuration=production` on GitlabCI it's not working with error 
`Error: Unknown argument: configuration`. But on my localhost environment it's working :/

## 🔬 Minimal Reproduction

Launch command yarn ng run loyalty-v3:build --configuration=production on GitlabCI.

## 🔥 Exception or Error

<pre><code>
$ yarn ng run loyalty-v3:build --configuration=production
Error: Unknown argument: configuration
</code></pre>

## 🌍 Your Environment

I launched `yarn ng version` on the CI and this is the output:
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    
Angular CLI: 14.0.2
Node: 14.18.3
Package Manager: yarn 3.2.1 
OS: linux x64
Angular: 14.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@angular/cli                    14.0.2
@nguniversal/express-engine     14.0.1
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.3
</code></pre>

I launched `yarn ng version` on my localhost and this is the output:
<pre><code>
    _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.2
Node: 14.19.1
Package Manager: yarn 3.2.1 
OS: darwin x64

Angular: 14.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@angular/cli                    14.0.2
@nguniversal/express-engine     14.0.1
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.3
</code></pre>

**Anything else relevant?**

I'm using the builder custom webpack but I used the default buidler from angular and i have the same error. I submitted an Issue on the other repo too [here](https://github.com/just-jeb/angular-builders/issues/1223).

**Comment by Christiaanvv** [comment]
I was having the same problem. It seemed like all arguments were not working anymore (--gues-routes for angular universal also did not work anymore). Reinstalling angular cli globally (`npm uninstall -g @angular/cli` and `npm install -g @angular/cli@latest`) solved the problem for me.

**Comment by squelix** [comment]
> I was having the same problem. It seemed like all arguments were not working anymore (`--gues-routes` for angular universal also did not work anymore). Reinstalling angular cli globally (`npm uninstall -g @angular/cli` and `npm install -g @angular/cli@latest`) solved the problem for me.

On a local environment it should be a good fix but on CI it's using the local `@angular/cli` in `node_modules` :/

**Comment by squelix** [comment]
> That refers to commands which had `--prod` option, which `ng run` did not.

Yes but i did tried with `ng build` and i had the same error on my CI. I thought `ng run xxx:build` was just a shortcut for `ng build`.

**Comment by squelix** [comment]
> `ng run` is a generic command which can invoke any builders. `ng build` is a dedicated command to invoke the configured build builder.
> 
> These command have different syntaxes as described in the documentation:
> 
> ```
> ng run project:builder[:configuration]
> ng build [project] --configuration=production
> ```
> 
> More about these commands in the below links
> 
> * https://angular.io/cli/run
> * https://angular.io/cli/build

It's new, i guess, because before the update from 13 to 14 it was working well.

**Comment by alan-agius4** [comment]
We discussed this during yesterday triage meeting and we decided the we should include this as a breaking change in the release notes and also add a more actionable error message.
