### ISSUE TITLE
ng new + ng serve not working

### ISSUE THREAD

**Issue by ziyaaktas** [angular/angular-cli#2339]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
os: darwin x64

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 4.5.0
os: darwin x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
ng new dir_name
cd dir_name
ng serve

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ERROR in ./src/main.ts
Module not found: Error: Can't resolve '@angular/platform-browser-dynamic' in '/Users/itemdev/dev/angular2-cli-test/src'
 @ ./src/main.ts 2:0-75
 @ multi main

ERROR in ./src/main.ts
Module not found: Error: Can't resolve '@angular/core' in '/Users/itemdev/dev/angular2-cli-test/src'
 @ ./src/main.ts 3:0-47
 @ multi main

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
The error seems to indicate you have missing packages, try running `npm install` inside your project folder. Also, verify that you are using npm3 as per the the prerequisites https://github.com/angular/angular-cli#prerequisites
