### ISSUE TITLE
ng test --include is broken

### ISSUE THREAD

**Issue by politza** [angular/angular-cli#23396]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes.

### Description

Using the --include option of the test command won't find any tests, if the workspace property is non empty.

## 🔬 Minimal Reproduction

ng new issue-app
cd issue-app
ng g lib issue-lib
ng test issue-lib --include '**/*.spec.ts'

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: Specified patterns: "**/*.spec.ts" did not match any spec files.
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.2
Node: 16.14.2
Package Manager: npm 8.7.0 
OS: linux x64

Angular: 14.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@schematics/angular             14.0.2
ng-packagr                      14.0.2
rxjs                            7.5.5
typescript                      4.7.4
    

</code></pre>

**Anything else relevant?**

The logic [here](https://github.com/angular/angular-cli/blob/8da926966e9f414ceecf60b89acd475ce1b55fc5/packages/angular_devkit/build_angular/src/builders/karma/index.ts#L114) seems to assume that sourceRoot is relative to root.

**Comment by kshaw797** [comment]
@alan-agius4 , We are on angular 14.0.5 and `ng test --include` still does seem to work. Does this fix part of any upcoming release?

**Comment by alan-agius4** [comment]
@kshaw797, can you please provide the output of `ng v`?

**Comment by kshaw797** [comment]
@alan-agius4 , Attached is the screenshot of output of ng v

![Screenshot 2022-07-18 at 2 05 51 AM](https://user-images.githubusercontent.com/75499899/179460375-e333cc01-c8e4-4512-9481-9c3dbc617b37.png)

**Comment by alan-agius4** [comment]
With the versions installed the problem should have addressed. 

If the problem still persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
