### ISSUE TITLE
exclude '**/*.scss' in assetTree

### ISSUE THREAD

**Issue by xmlking** [angular/angular-cli#234]
please exclude common source files (scss, less etc) from   assetTree
or provide option to exclude file pattern in `ember-cli-build.js`  
angular2-app.js
```
    var assetTree = new Funnel(sourceTree, {
        include: ['**/*.*'],
        exclude: ['**/*.ts', '**/*.js',  '**/*.scss'],
        allowEmpty: true
    });
```

**Comment by hansl** [comment]
Why? These assets can be useful for debugging and you should not use the tool to release stuff in production. 

What is breaking your workflow?

**Comment by xmlking** [comment]
At this time I don't have sourcemaps enabled scss, so no use for actual source files in dist folder.
Why we are not copying .ts fils to dist folder? Can we keep source files in src folder and still provide sourcemaps?

**Comment by cironunes** [comment]
We need to serve the files over the http server to be able to access them in the Browser debugging tools.

**Comment by hansl** [comment]
I'm going to close this as this is not an issue per se. The build is currently not meant to be used in production and those files are simply there for debugging.
