### ISSUE TITLE
test/options/codeCoverageExclude option in angular.json is ignored in Angular 14

### ISSUE THREAD

**Issue by vzakharov-rxnt** [angular/angular-cli#23403]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After upgrading from Angular 13 to Angular 14, codeCoverageExclude is ignored by the test runner. I created a sample project on Github where the issue can be reproduced in a brand new Angular 14 boilerplate, with minimal changes. Please see the last commit for more details.

### Please provide a link to a minimal reproduction of the bug

https://github.com/vzakharov-rxnt/codeCoverageExclude-issue

### Please provide the exception or error you saw

```true
No error, but codeCoverageExclude does not do anything in Angular 14. Used to work in Angular 13.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.2
Node: 16.15.0
Package Manager: yarn 1.22.15
OS: win32 x64

Angular: 14.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.2
@angular-devkit/build-angular   14.0.2
@angular-devkit/core            14.0.2
@angular-devkit/schematics      14.0.2
@schematics/angular             14.0.2
rxjs                            7.5.5
typescript                      4.7.4
```

### Anything else?

I ran this command to produce the code coverage report:
```
"cover": "ng test --no-watch --code-coverage"
```

**Comment by alan-agius4** [comment]
Confirmed that this is a regression on Windows.

**Comment by vzakharov-rxnt** [comment]
@alan-agius4 Thanks for fixing. When is this planned for release?

**Comment by dgp1130** [comment]
This will be in 14.0.3 and 14.1.0-next.2. Our release yesterday got delayed due to some infrastructure issues, but hopefully it should go out today.

**Comment by VooDooTo** [comment]
I saw version 14.0.3 release 3 days ago, but nowhere I am able to find that this bug is fixed. Is there any changelog for smaller versions ?

**Comment by dgp1130** [comment]
GitHub releases include changelogs, this fix is listed there:
https://github.com/angular/angular-cli/releases/tag/14.0.3
