### ISSUE TITLE
Unable to install angular-cli on Windows 10

### ISSUE THREAD

**Issue by Shane-Lester** [angular/angular-cli#2341]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here: error with ng --version
node v 4.4.3 npm  v 3.10.8

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
Tried npm uninstall -g angular-cli, npm cache clean, restarted machine then npm install -g angular-cli

4. The log given by the failure. Normally this include a stack trace and some
   more information.
```
PS C:\Users\Shane> npm install -g angular-c
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nod
cli.js" "install" "-g" "angular-cli"
npm ERR! node v4.4.3
npm ERR! npm  v3.10.8

npm ERR! shasum check failed for C:\Users\S
oader-0.8.2.tgz
npm ERR! Expected: 7331296d13d5b3105cd905ce
npm ERR! Actual:   5c525a4bc29a85b3ae0f20f5
npm ERR! From:     https://registry.npmjs.o
npm ERR!
npm ERR! If you need help, you may report t
npm ERR!     <https://github.com/npm/npm/is

npm ERR! Please include the following file
npm ERR!     C:\Users\Shane\npm-debug.log

```

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JanStureNielsen** [comment]
@Shane-Lester -- the issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details, including the content of the `npm-debug.log` as noted in the error.

**Comment by mukesh51** [comment]
@Shane-Lester  You can try the following steps:

1) Install node-gyp from https://github.com/nodejs/node-gyp

npm install -g node-gyp

2) Install Windows build tool from https://github.com/felixrieseberg/windows-build-tools

npm install --global windows-build-tools

This will also install python

3) Install Angular-CLI

 npm install -g angular-cli
 
 This should install angular-cli without errors. hope that helps.

**Comment by loicsalou** [comment]
I had same issue and it disappeared as soon as I installed Node 6.6 + corresponding npm.
You should try this.
The only issue I have in win10 now is that the "ng new project" command never ends so I have to cancel it then I do manually the npm install and it's ok.

**Comment by Shane-Lester** [comment]
mukesh51- that worked for me. Thanks. Shane

**Comment by Lowell130** [comment]
@Shane-Lester, @mukesh51 your solution work great for me! Thank you

**Comment by plakhlani** [comment]
@mukesh51 your solution worked for me as well, except I required command prompt with run as administrator for  windows-build-tools installation.

**Comment by vinodkumar526** [comment]
@loicsalou  you are correct ,
Me also faced the same issue,now it is working fine for me by simply upgrading the node version from 6.3.0(my old version) to 7.9.0(latest)
