### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by Karman40** [angular/angular-cli#23413]
# 🐞 Bug report

### Command (mark with an `x`)
- [x] serve
- [x] config

### Description
I want to proxy static elements, such as images, locally, but I can't. I don't think there is a problem with the proxy settings because there are no problems with / api HTTP calls, they work.

There are times when random will work well again after a while it is not good.

Interestingly, I see that it redirects that content and doesn’t proxy the images. Redirection would also be good, but in this case the baseHref set under Angular will be inserted between the host and path, which will not be a good path.

## 🔬 Minimal Reproduction
<pre><code>{
  "/api": {
    "target": "https://localhost:3000",
    "secure": false
  },
  "/cdn": {
    "target": "https://dev.basecloud.hu",
    "secure": false
  }
}
</code></pre>
<pre>< img class="img-fluid" src="/cdn/logos/vertical.jpg" alt=""></pre>

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/32225709/175046501-153cb2bb-50a7-4584-b132-d353cfc7036c.png)
![image](https://user-images.githubusercontent.com/32225709/175046581-280c2232-5713-4061-b97d-c7fb6af478ec.png)
![image](https://user-images.githubusercontent.com/32225709/175046623-d6bbf35c-953d-4052-bcac-c68c2ae2c2ab.png)

## 🌍 Environment
<pre><code>Angular CLI: 14.0.1
Node: 16.15.0
Package Manager: npm 8.12.1
OS: win32 x64

Angular: 14.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/fire                   7.4.1
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.7.3
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Karman40** [comment]
@alan-agius4 thank you your answer. I'm crated your requested repro app.

https://github.com/Karman40/angular-proxy-repro

**Comment by alan-agius4** [comment]
@Karman40, I am not seeing any request to the proxy nor any base-href setting.

**Comment by Karman40** [comment]
@alan-agius4 true I forgot push commit and the baseHref setting. Sorry :/
 i fixed it.

**Comment by alan-agius4** [comment]
I took another look and it appears that the proxy config is not used at all in the reproduction. 

```diff
         "serve": {
           "builder": "@angular-devkit/build-angular:dev-server",
+          "options": {
+            "proxyConfig": "proxy.conf.json"
+          },
           "configurations": {
             "production": {
               "browserTarget": "porxy-repro:build:production"
             },
             "development": {
               "browserTarget": "porxy-repro:build:development"
             }  
           },
           "defaultConfiguration": "development"
         },
```

After this I was able to reproduce the problem. The problem appears to be because of the missing `changeOrigin` property which is needed for [name-based virtual hosted sites](http://en.wikipedia.org/wiki/Virtual_hosting#Name-based). More more context please see: https://github.com/chimurai/http-proxy-middleware#tldr-

**Comment by Karman40** [comment]
thanks for going to me already. Interestingly, I tried it before but it didn't improve, maybe the cache also played a role.
