### ISSUE TITLE
--legacy-peer-deps is not a dependency

### ISSUE THREAD

**Issue by JarVonDigital** [angular/angular-cli#23429]
**Version**
v16.15.1 / Node
v9-13 / Angular CLI

**What steps will reproduce the bug?**
When attempting to update an application from version 10 of angular or higher:

npx @angular/cli@11 update @angular/core@11 @angular/cli@11 --legacy-peer-deps

**How often does it reproduce? Is there a required condition?**
Issue is present during every attempt to update application.

**What do you see instead?**
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 11.2.19 to perform the update.
Installing packages for tooling via pm.
Installed packages for tooling via npm
Using package manager: 'npm'
Collecting installed dependencies.
Found 46 dependencies.
Package '--legacy-peer-deps' is not a dependency.

**Comment by alan-agius4** [comment]
To enable the `--legacy-peer-deps` option please use `--force` option instead.

```
ng update @angular/core@11 @angular/cli@11 --force
```
