### ISSUE TITLE
Include webpack plugin

### ISSUE THREAD

**Issue by daniele-zurico** [angular/angular-cli#2342]
Versions: 
angular-cli: 1.0.0-beta.15
node: 5.1.0
os: darwin x64

Is possible to install some plugin for webpack and include it?
One example is 

```
// webpack.config.js
module: {
  loaders: [
    {
      test: /\.yaml$/,
      include: path.resolve('data'),
      loader: 'yaml',
    },
  ],
}
```

**Comment by alexsorokoletov** [comment]
@daniele-zurico you might be interested in this issue https://github.com/angular/angular-cli/issues/1656

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/1656.
