### ISSUE TITLE
mononucleorepo simplex

### ISSUE THREAD

**Issue by vigouredelaruse** [angular/angular-cli#23437]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ x] serve
- [ x] test
- [ x] e2e
- [ ] generate
- [x ] add
- [ x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

managing npm update across dependency version updates is at the state that led to the .net common language runtime

### Describe the solution you'd like

package management should survive more scenarios that permit untenable discharges in the direction of one's foot

### Describe alternatives you've considered

there are no alteratives, are there?

![brittlenpm](https://user-images.githubusercontent.com/31052867/175839933-ff08c260-d057-4fb9-84d4-a47db9c3a7a0.png)

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
