### ISSUE TITLE
github-pages deploy fails if there is another git repo inside

### ISSUE THREAD

**Issue by cedvdb** [angular/angular-cli#2343]
Not sure if this is a bug but it annoyed me quite a lot today, so I thought I'd share.

1. OS?  Windows 7

2. Versions. beta 14

3. 

 - Create new project ng new myApp
 - Create subdirectory in src/app, for example a component `mycomponent`. 
 - `git init`, ` add .` , `commit -a ` and `push` it to a repo called `myExampleRepo` 
 - go back to myApp directory
 - add remote origin `myExampleRepo`
 - `ng github-pages:deploy --message "commit"`

4. 
```
Error: Command failed: git rm --cached -r .
error: the following file has staged content different from both the
file and the HEAD:
    src/app/mycomponent
(use -f to force removal)

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

5. Work around

Ultimately this is a **bad** (so bad) workaround, as one can just manually build the app and push the dist folder for the same effect, but here is how I just pushed it

```
git rm --cached -r -f src/app/mycomponent
git commit -a -m "commit"
cd dist
git init
git add .
git commit -a -m 
git remote add origin url
git checkout -b gh-pages
git push origin gh-pages 
```

Much better to just build the app and go into the dist folder, change `base` tag and push the dist to the remote I guess, but I was feeling like freestyling.

I hope someone can provide me with some insight on this.

**Comment by filipesilva** [comment]
Currently the github deploy functionality heavily relies on git manipulation and we don't support nested git repos. We're looking at rewriting it a bit so it's more robust.
