### ISSUE TITLE
TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point

### ISSUE THREAD

**Issue by durga12345-sketch** [angular/angular-cli#23433]
We are getting this issue when we are passing the user name as Hindi language. But we are gving user name as english language not getting any issue

Angular version: 9
Nodejs: 16

![image](https://user-images.githubusercontent.com/108118780/175518670-97cd7ccf-1a7a-4aa3-861b-7f812ac707cd.png)

**Comment by alan-agius4** [comment]
Hi @durga12345-sketch, 

Angular version 9 is no longer supported. Please see https://angular.io/guide/releases#support-policy-and-schedule.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
