### ISSUE TITLE
Method updateTsConfig doesn't validate if the short import is already added

### ISSUE THREAD

**Issue by Danils123** [angular/angular-cli#23449]
🐞 Bug report

[File]( https://github.com/angular/angular-cli/blob/main/packages/schematics/angular/library/index.ts)

### Command
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [X] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

When you call the method updateTsConfig and you already has this short import in paths.

## 🔥 Exception or Error
Duplicate Object key

## Proposed solution
```
export function updateTsConfig(packageName: string, ...paths: string[]) {
  return (host: Tree) => {
    if (!host.exists("tsconfig.json")) {
      return host;
    }

    const file = new JSONFile(host, "tsconfig.json");
    const jsonPath = ["compilerOptions", "paths", packageName.toLowerCase()];
    const value: string[] | undefined = file.get(jsonPath) as string[];
    let pathsFiltered: string[] = [];
    if (value) {
      pathsFiltered = paths?.filter((item) => !value!.some((path) => path === item));
    }

    file.modify(jsonPath, Array.isArray(value) ? [...value, ...pathsFiltered] : paths);
  };
}
```

**Comment by alan-agius4** [comment]
Can you please elaborate on the use case were you already have path for a library that doesn't exist? Likely if this path exist is not correct anyways so it should be overridden.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
