### ISSUE TITLE
Errors on npm -g install angular-cli

### ISSUE THREAD

**Issue by doubleUTF** [angular/angular-cli#2344]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Win7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
Node 6.2.1, npm 3.9.3

cannot run ng --version or ng --help as it leads to the following error:

> Cannot find module 'process-nextick-args'

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

> λ npm install -g angular-cli
> npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
> npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
> npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
> C:\Users\Big D\AppData\Roaming\npm\ng -> C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\bin\ng
> 
>  execSync@1.0.2 install C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\execSync
>  node install.js
> 
> [execsync v1.0.2] Attempting to compile native extensions.
> { Error: spawn node-gyp ENOENT
>     at exports._errnoException (util.js:1007:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
>     at onErrorNT (internal/child_process.js:348:16)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)
>     at Function.Module.runMain (module.js:577:11)
>     at startup (node.js:160:18)
>     at node.js:456:3
>   code: 'ENOENT',
>   errno: 'ENOENT',
>   syscall: 'spawn node-gyp',
>   path: 'node-gyp',
>   spawnargs: [ 'rebuild' ] }
> [execSync v1.0.2]
>     Native code compile failed!!
>     Will try to use win32 extension.
> 
>  node-zopfli@1.4.0 install C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
>  node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.2.1 (node-v48 ABI) (falling back to source compile with node-gyp)
> gyp ERR! configure error
> gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.3, which is not supported by gyp.
> gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
> gyp ERR! stack     at failPythonVersion (C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-gyp\lib\configure.js:454:14)
> gyp ERR! stack     at C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-gyp\lib\configure.js:443:9
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:198:7)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
> gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
> gyp ERR! stack     at emitOne (events.js:96:13)
> gyp ERR! stack     at Socket.emit (events.js:188:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:492:12)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Big D\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Big D\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\Users\\Big D\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
> gyp ERR! cwd C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
> gyp ERR! node -v v6.2.1
> gyp ERR! node-gyp -v v3.4.0
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
> node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> node-pre-gyp ERR! System Windows_NT 6.1.7601
> node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Big D\\AppData\\Roaming\\npm\\node_modules\\angular-cli\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli
> node-pre-gyp ERR! node -v v6.2.1
> node-pre-gyp ERR! node-pre-gyp -v v0.6.30
> node-pre-gyp ERR! not ok
> Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\Users\Big D\AppData\Roaming\npm\node_modules\angular-cli\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bonnici** [comment]
Try following the [node-gyp installation instructions](https://github.com/nodejs/node-gyp#installation). It's a hassle but it looks like it's required until someone fixes the pre-built version of zopfli.

**Comment by doubleUTF** [comment]
Gotcha, so it's zopfli's problem not mine. I'll check it out, thanks bonnici!

**Comment by zuo305** [comment]
Hi, I have same problem on mac.
And i try to install node-zopfli@1.4.0 using "npm install -g node-zopfli@1.4.0", but i got the same error.

**Comment by bonnici** [comment]
Looks like the zopfli version was bumped in the latest beta so the precompiled binaries for that version might be available during install.

**Comment by filipesilva** [comment]
Dupe, see https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794
