### ISSUE TITLE
Unable to install angular-cli on macOS

### ISSUE THREAD

**Issue by feamor84** [angular/angular-cli#2346]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

macOS Sierra 10.12

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

node 6.4.0, npm 3.10.8

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

-

4. The log given by the failure. Normally this include a stack trace and some
   more information.

In terminal I've got this:

npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

In log file this:

96328 verbose stack TypeError: uid must be an unsigned int
96328 verbose stack     at TypeError (native)
96328 verbose stack     at Object.fs.chown (fs.js:1190:11)
96328 verbose stack     at Object.chown (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:231:17)
96328 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
96328 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
96328 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
96328 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:211:18
96328 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)

5. Mention any other details that might be useful.

Install via sudo npm install angular-cli -g
I ran npm cache clean, but it didn't help

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
You seem to have some npm problems on your system. I'm sorry I can't help you more, but this problem doesn't seem related to the CLI itself.
