### ISSUE TITLE
Unable to Install in Mac (OSX Mavericks)

### ISSUE THREAD

**Issue by ziszo** [angular/angular-cli#2347]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX Mavericks

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
node v6.2.2
npm v3.9.5

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

598 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/index.js
129599 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/license
129600 silly gunzTarPerm extractEntry lib/node_modules/yargs/node_modules/camelcase/readme.md
129601 silly gentlyRm /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules is being purged
129602 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules
129603 silly vacuum-fs purging /usr/local/lib/node_modules/.staging/npm-697dfe0f/node_modules
129604 silly vacuum-fs quitting because other entries in /usr/local/lib/node_modules/.staging/npm-697dfe0f
129605 silly gentlyRm /usr/local/lib/node_modules/.staging/bower-f5744e65/node_modules is being purged
129606 verbose gentlyRm don't care about contents; nuking /usr/local/lib/node_modules/.staging/bower-f5744e65/node_modules
129607 verbose unlock done using /Users/roland/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
129608 silly rollbackFailedOptional Starting
129609 silly rollbackFailedOptional Finishing
129610 silly runTopLevelLifecycles Starting
129611 silly runTopLevelLifecycles Finishing
129612 silly install printInstalled
129613 verbose stack Error: Invalid name: "@angular/tsc-wrapped"
129613 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:300:15)
129613 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:204:5)
129613 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:30:38
129613 verbose stack     at Array.forEach (native)
129613 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:15)
129613 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:349:5)
129613 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
129613 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:295:20)
129613 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
129613 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:365:13)
129614 verbose cwd /Users/roland
129615 error Darwin 13.4.0
129616 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
129617 error node v6.6.0
129618 error npm  v3.10.3
129619 error Invalid name: "@angular/tsc-wrapped"
129620 error If you need help, you may report this error at:
129620 error     <https://github.com/npm/npm/issues>
129621 verbose exit [ 1, true ]

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by zuo305** [comment]
＋1

**Comment by ziszo** [comment]
Tried to force install as said by CanKer in #2161

> npm install -g -f angular-cli

but got the following errors:

```
uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "-f" "angular-cli"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8

npm ERR! uid must be an unsigned int
```

**Comment by filipesilva** [comment]
You seem to have some npm problems on your system. `@angular/tsc-wrapped` is definitely a valid name, maybe you're using a npm proxy or something.

I'm sorry I can't help you more, but this problem doesn't seem related to the CLI itself.
