### ISSUE TITLE
Cannot find module '@angular/cli/utilities/color'

### ISSUE THREAD

**Issue by Darker1998** [angular/angular-cli#23474]
![image](https://user-images.githubusercontent.com/47914523/176641984-b464233b-4164-4873-994e-d3f0c9647f99.png)

**Comment by alan-agius4** [comment]
It looks like this mentioned package is relying on private utils
https://unpkg.com/browse/ng-alain@13.5.1/ng-add/index.js#L3

Please file an issue with the author of `ng-alain`
