### ISSUE TITLE
Github Pages deploy works incorrect;

### ISSUE THREAD

**Issue by QuipHop** [angular/angular-cli#2348]
Github Pages deploy works icorrect;
I have a repo [https://github.com/QuipHop/angular2-clicker-arena](https://github.com/QuipHop/angular2-clicker-arena), When i run ng github-pages:deploy
CLI says that project uploaded to [https://quiphop.github.io/clicker/](https://quiphop.github.io/clicker/) , but there is nothing (404), and  the correct url [https://quiphop.github.io/angular2-clicker-arena/](https://quiphop.github.io/angular2-clicker-arena/) all the bundle files are missed, app won't work

1. xubuntu 16.04

2. angular-cli: 1.0.0-beta.14, node: 5.12.0, os: linux x64

3. Build project, deploy to github pages via ng github-pages:deploy

4. 

5.

**Comment by ouadie-lahdioui** [comment]
@QuipHop what's the name of your project in the package.json file ?

**Comment by QuipHop** [comment]
My bad @ouadie-lahdioui , there realy was wrong config.
Everything works fine now. Thanks!

**Comment by ouadie-lahdioui** [comment]
welcome @QuipHop ;)

Take a look at this one https://github.com/angular/angular-cli/issues/1362, we really have a work to do.
