### ISSUE TITLE
Please add `ng add -D package-name` for Christ sake

### ISSUE THREAD

**Issue by kasir-barati** [angular/angular-cli#23488]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

This feature addressed here too:
- https://github.com/angular/angular-cli/issues/15409
- https://github.com/angular/angular-cli/pull/15410

And IDK why not in official doc we have anything not anywhere else. So I decided to be the hero and open this feature request again to see what's going on from 2019 up until now, 2022 that we have not it, yet.

### Describe the solution you'd like

I have no solution except using `npm` or `pnpm` directly which I do not like when we have a wiry worrier named `ng add`

### Describe alternatives you've considered

No solution. Nothing. Just the good `ng add`

**Comment by alan-agius4** [comment]
Let’s continue tracking this https://github.com/angular/angular-cli/issues/11016

Also, please mind the language that you use.  See: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md

**Comment by kasir-barati** [comment]
@alan-agius4 :ok_hand: Thanks. I just was a little informal :sweat_smile:. No problem. I will follow the code of conduct.

**Comment by alan-agius4** [comment]
That’s actually not for you to configure. That setting must be set by the package author in their package.json. This is because in the majority of the cases the author of the package knows if the dependency should be saved as a dev dependency, dependency or not saved at all.

**Comment by kasir-barati** [comment]
@alan-agius4 Gotcha. Really cool. 

Side note but IMO related to this feature request if we call it feature: Now it seems a little better, However as you know we are developers and I think most of the times we wanna go on ourselves

**Comment by alan-agius4** [comment]
> However as you know we are developers and I think most of the times we wanna go on ourselves

That doesn’t necessarily end in the best outcome though. As an example `@angular/pwa` should never be saved as dev dependency or dependency and as I library author I know that, but other users might not know that.
