### ISSUE TITLE
Build fails after migrating from v13 to v14

### ISSUE THREAD

**Issue by SDAdham** [angular/angular-cli#23490]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 13.1.3

### Description

 A clear and concise description of the problem...
I am getting the following error:
```
✔ Browser application bundle generation complete.

./src/main.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit

Error: Failed to initialize Angular compilation - NGCC failed.
```

## 🔥 Exception or Error

<pre><code>

✔ Browser application bundle generation complete.

./src/main.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit

Error: Failed to initialize Angular compilation - NGCC failed.

</code></pre>

## 🌍 Your Environment

<pre><code>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.4
@angular-devkit/build-angular   14.0.4
@angular-devkit/core            14.0.4
@angular-devkit/schematics      13.3.6
@nguniversal/builders           14.0.2
@nguniversal/express-engine     14.0.2
@schematics/angular             14.0.4
rxjs                            7.5.5
typescript                      4.6.2
webpack                         5.73.0
</code></pre>

**Anything else relevant?**

Here is my dependencies:
```
    "@angular/animations": "^14.0.4",
    "@angular/cdk": "^14.0.4",
    "@angular/common": "^14.0.4",
    "@angular/compiler": "^14.0.4",
    "@angular/core": "^14.0.4",
    "@angular/forms": "^14.0.4",
    "@angular/localize": "^14.0.4",
    "@angular/platform-browser": "^14.0.4",
    "@angular/platform-browser-dynamic": "^14.0.4",
    "@angular/platform-server": "^14.0.4",
    "@angular/router": "^14.0.4",
    "@angular/service-worker": "^14.0.4",
...
    "@angular-devkit/build-angular": "^14.0.4",
    "@angular-eslint/builder": "^14.0.0",
    "@angular-eslint/eslint-plugin": "^14.0.0",
    "@angular-eslint/eslint-plugin-template": "^14.0.0",
    "@angular-eslint/schematics": "^14.0.0",
    "@angular-eslint/template-parser": "^14.0.0",
    "@angular/cli": "^14.0.4",
    "@angular/compiler-cli": "^14.0.4",
    "@angular/language-service": "^14.0.4",
    "@angular-devkit/build-angular": "^14.0.4",
    "@angular-eslint/builder": "^14.0.0",
    "@angular-eslint/eslint-plugin": "^14.0.0",
    "@angular-eslint/eslint-plugin-template": "^14.0.0",
    "@angular-eslint/schematics": "^14.0.0",
    "@angular-eslint/template-parser": "^14.0.0",
    "@angular/cli": "^14.0.4",
    "@angular/compiler-cli": "^14.0.4",
    "@angular/language-service": "^14.0.4",
```

**Comment by SDAdham** [comment]
I upgraded my global `ng` client and now it's:
```
Angular CLI: 14.0.4
Node: 14.15.3
Package Manager: npm 6.14.9 
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.4 (cli-only)
@angular-devkit/core         14.0.4 (cli-only)
@angular-devkit/schematics   14.0.4 (cli-only)
@schematics/angular          14.0.4 (cli-only)
```

**Comment by alan-agius4** [comment]
Hi @SDAdham, 

It looks like NGCC is failing. Do you have further logs prior to `Browser application bundle generation complete.`?

**Comment by SDAdham** [comment]
Hello @alan-agius4 , apparently a simple `node_modules` delete and then re-running `yarn install` solved the problem. Thanks.
