### ISSUE TITLE
Unable to use ng serve (1.0.0-beta.15)

### ISSUE THREAD

**Issue by NiklasTeich** [angular/angular-cli#2350]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-li: 1.0.0-beta.15
node: 6.3.0
os: win32 x64
npm: 3.10.6

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

No, i upgraded the angular-cli to 1.0.0-beta.15:

npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli@latest

ng new works fine without any errors.

4. The log given by the failure. Normally this include a stack trace and some
   more information.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve '@angular/platform-browser-dynamic' in 'C:\FOOPATH\src
'
 @ ./src/main.ts 2:0-75
 @ multi main

ERROR in ./src/polyfills.ts
Module not found: Error: Can't resolve 'zone.js/dist/zone' in 'C:\FOOPATH\src'
 @ ./src/polyfills.ts 16:0-27
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@angular/forms' in 'C:\FOOPATH\src\app'
 @ ./src/app/app.module.ts 12:0-45
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@angular/http' in 'C:\FOOPATH\src\app'
 @ ./src/app/app.module.ts 13:0-43
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./~/@angular/core/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\FOOPATH\node_modules\@angular\co
re\src\facade'
 @ ./~/@angular/core/src/facade/async.js 13:0-39 15:0-39
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main

ERROR in ./~/@angular/core/src/facade/async.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'C:\FOOPATH\node_modules\@angular
\core\src\facade'
 @ ./~/@angular/core/src/facade/async.js 14:0-45
 @ ./~/@angular/core/src/core.js
 @ ./~/@angular/core/index.js
 @ ./src/main.ts
 @ multi main

ERROR in [default] C:\FOOPATH\node_modules\@angular\common\src\facade\async.d.ts:8:24
Cannot find module 'rxjs/Subject'.

ERROR in [default] C:\FOOPATH\node_modules\@angular\common\src\facade\async.d.ts:9:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] C:\FOOPATH\node_modules\@angular\common\src\facade\async.d.ts:10:24
Cannot find module 'rxjs/Subject'.

ERROR in [default] C:\FOOPATH\node_modules\@angular\core\src\facade\async.d.ts:8:24
Cannot find module 'rxjs/Subject'.

ERROR in [default] C:\FOOPATH\node_modules\@angular\core\src\facade\async.d.ts:9:27
Cannot find module 'rxjs/Observable'.

ERROR in [default] C:\FOOPATH\node_modules\@angular\core\src\facade\async.d.ts:10:24
Cannot find module 'rxjs/Subject'.

ERROR in [default] C:\FOOPATH\src\app\app.module.ts:3:28
Cannot find module '@angular/forms'.

ERROR in [default] C:\FOOPATH\src\app\app.module.ts:4:27
Cannot find module '@angular/http'.

ERROR in [default] C:\FOOPATH\src\main.ts:3:39
Cannot find module '@angular/platform-browser-dynamic'.

5. Mention any other details that might be useful.

Everything worked until the beta15 update ...
I didn't change anything else, i just tried to create a new angular app (ng new) and serve it (ng serve).

Greetings!
Niklas

**Comment by robindijkhof** [comment]
Did you update your package.json?

**Comment by NiklasTeich** [comment]
Thanks for your answer!

Do i need to update the package.json in a freshly new created cli project? ...
The package.json looks good to me ...

{
  "name": "foo-test",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.15",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.5",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}

**Comment by robindijkhof** [comment]
Looks fine to me too

**Comment by NiklasTeich** [comment]
I solved it: While creating a new project, i think the "Installing packages for tooling via npm" was not finished successfully. I restarted (...) everything and now it works like a charm! But still - thanks for your feedback!
