### ISSUE TITLE
ng new: add engine section to define supported/required node/npm version

### ISSUE THREAD

**Issue by d-koppenhagen** [angular/angular-cli#23515]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [x] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

Checking out the release notes for major versions will contain information like this one:

> Support for Node.js v12 has been removed as it will become EOL on 2022-04-30. Please use Node.js v14.15 or later.

Such required engines can be defined in the `package.json` to give users a hint within the project they are using a non-supported version of node/npm.

Details: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines

### Describe the solution you'd like

Add/fill the `engines` part in the `package.json` when scaffolding a project with `ng new` and maintain this with schematic migrations on major version updates.

```
{
  ...
  "engines": {
    "node": ">=14.15 <17"
  }
}
```

### Describe alternatives you've considered

As an alternative the initial `engines` definition as shown above can be generated on `ng new` but users should update them manually later when the requirements are changing.

**Comment by alan-agius4** [comment]
We already define the "engines" fields in the NPM packages that we ship example: https://unpkg.com/browse/@angular/cli@14.0.5/package.json#L60. Adding this in the users workspace seems is unnecessary.
