### ISSUE TITLE
14.0.5 not installed globaly

### ISSUE THREAD

**Issue by sysmat** [angular/angular-cli#23518]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Is this a regression?

Yes, the previous version installed correctly

### Description
I'm not in any workspace 

1.  npm uninstall -g @angular/cli
2.  npm cache verify
3.  npm install -g @angular/cli
4. ng version

```
❯ ng version
Your global Angular CLI version (14.0.5) is greater than your local version (13.3.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.3.7
Node: 16.15.1
Package Manager: npm 8.5.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.7
@angular-devkit/core         13.3.7
@angular-devkit/schematics   13.3.7
@schematics/angular          13.3.7
```
 
5. ng config -g cli.warnings.versionMismatch false
```
Your global Angular CLI version (14.0.5) is greater than your local version (13.3.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Schema validation failed with the following errors:
  Data path "/cli" must NOT have additional properties(completion).
```
6. which ng

```
/c/Users/tomaz/AppData/Roaming/npm/ng
```
7.  in C:\Users\tomaz\AppData\Roaming\npm\node_modules\@angular\cli\package.json I see
```
"name": "@angular/cli",
  "version": "14.0.5",
  "description": "CLI tool for Angular",
  "main": "lib/cli/index.js",
  "bin": {
    "ng": "./bin/ng.js"
  },
```
8.   ng completion
```
The specified command ("completion") is invalid. For a list of available options,
run "ng help".

Did you mean "analytics"?
```

**Comment by alan-agius4** [comment]
There are two main issues errors here and both of which are caused by incompatibilities  between v14 and v13 Angular CLI. 

1) `cli.completion` property was not allowed in the Angular CLI version 13 and therefore when trying to set the config from a v13 workspace it will issue an error.  Workaround for this is to run the command from outside the v13 workspace.
```
  Data path "/cli" must NOT have additional properties(completion).
```

1) CLI version 13, doesn't support completion, in this case we should either disable completion or use the global CLI. 
```
The specified command ("completion") is invalid. For a list of available options.
```
