### ISSUE TITLE
WebpackOptionsValidationError on ng serve

### ISSUE THREAD

**Issue by BugsyFTW** [angular/angular-cli#2352]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS
Windows 10

2. Versions

angular-cli: 1.0.0-beta.14
node: 6.6.0
os: win32 x64

3. Repro steps.

ng serve gives me a WebpackOptionsValidationError

4. The log given by the failure. Normally this include a stack trace and some
   more information.

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: {
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           tslint: ...
         }
       })
     }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.node.global should be a boolean.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache? }
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (C:\Trabalho\SourceCode\UbiXploit Web Team2\GESFaturasWeb\node_modules\webpack\lib\webpack.js:16:9)
    at Class.run (C:\Trabalho\SourceCode\UbiXploit Web Team2\GESFaturasWeb\node_modules\angular-cli\tasks\serve-webpack.js:23:27)
    at C:\Trabalho\SourceCode\UbiXploit Web Team2\GESFaturasWeb\node_modules\angular-cli\commands\serve.js:84:26
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Nestyko** [comment]
Same problem after doing a fresh install of xubuntu, a git clone and npm install.
When trying "ng serve" it gives me the same error.

angular-cli: 1.0.0-beta.14
node: 6.6.0
os: Xubuntu 16.04 (64bits)

**Comment by jgo4th** [comment]
Same issue after cloning into new folder and npm install

angular-cli: 1.0.0-beta.14
node: 4.5.0
os: darwin x64

**Comment by jgo4th** [comment]
@Nestyko @BugsyFTW http://stackoverflow.com/questions/39600939/invalid-configuration-object-webpack-has-been-initialised-using-a-configuration/39601224#39601224 this link helped me fix my issue

**Comment by filipesilva** [comment]
Fixed in beta.16.
