### ISSUE TITLE
File replacement for prod release not working

### ISSUE THREAD

**Issue by narendrasinghrathore** [angular/angular-cli#23538]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
NA

### Description
Need to replace index.html with index.prod.html  when build with `ng build `

```
"configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                },
                {
                  "replace": "src/index.html",
                  "with": "src/index.prod.html"
                }
              ],
              "outputHashing": "all"
            },
```

## 🔥 Exception or Error

<pre><code>
Schema validation failed with the following errors:
  Data path "/fileReplacements/1" must have required property 'src'.
  Data path "/fileReplacements/1/replace" must match pattern "\.(([cm]?j|t)sx?|json)$".
  Data path "/fileReplacements/1" must match exactly one schema in oneOf.de></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.1.4
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1301.4
@angular-devkit/build-angular      13.3.5
@angular-devkit/core               13.1.4
@angular-devkit/schematics         13.1.4
@angular/cdk                       13.3.6
@angular/cli                       13.1.4
@angular/material                  13.3.6
@angular/material-moment-adapter   13.3.6
@schematics/angular                13.1.4
rxjs                               7.4.0
typescript                         4.5.5

</code></pre>

**Comment by alan-agius4** [comment]
This is working as intended.

See: https://github.com/angular/angular-cli/issues/14599

**Comment by narendrasinghrathore** [comment]
@alan-agius4 
<img height="404px" src="https://media2.giphy.com/media/4ZrFRwHGl4HTELW801/giphy.gif?cid=de9bf95e7j7t87v3znl90ru467vgw0xpww73krs0si0gs2vv&amp;rid=giphy.gif&amp;ct=g" width="404px" itemtype="http://schema.skype.com/Giphy" key="gif_0">

**Comment by narendrasinghrathore** [comment]
It seems while using index property we need to make sure have similar index.html. So let say you build with 
` "index":"src/index.prod.html", `
So when you run `ng build ` the output file will be  index.prod.html and it won't work. We need index.html
In that case we need to use a different folder with index.html that we need to deploy for prod and update the path in angular.json
` "index":"src/prod/index.html", `

So not having the option under filereplacements seems to add complexity and pretty fussy.

<img height="227.4774774774775px" src="https://media0.giphy.com/media/gd09Y2Ptu7gsiPVUrv/giphy.gif?cid=de9bf95exz71x9imw7y6grho5crzxuubcdwqw2187iepj57q&amp;rid=giphy.gif&amp;ct=g" width="404px" itemtype="http://schema.skype.com/Giphy" key="gif_1">

**Comment by alan-agius4** [comment]
You can use specify the output name when using the index output option.

```js
{
    "index": {"input": "src/index.prod.html", "output": "index.html"
}
```

`fileReplacements` is intended to only replace files that are in the TypeScript program.

**Comment by narendrasinghrathore** [comment]
Thanks.
