### ISSUE TITLE
Errors during JIT compilation of template for DashboardComponent: Opening tag "app-ui-help-tag" not terminated while running tests

### ISSUE THREAD

**Issue by swapnilfarande** [angular/angular-cli#23539]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Our application is working fine with older versions of Angular v12 and below. Issue observed only with v13 and v14 upgrades. Issue observed only while running unit tests.

### Description
We have a hybrid application (AngularJS and Angular), we keep the Angular version updated regularly and currently working fine on the v2 version.  Recently I tried to upgrade the application to v13, application upgraded successfully to v13 and working fine without any issues. But we are getting below exception while running unit tests for each of the components.

Note: This issue is only observed while running unit tests, serve is working fine. I tried to upgrade to v14, still it has the same issue.

## 🔬 Minimal Reproduction
NA

## 🔥 Exception or Error

<pre><code>
 ng test wifi-aware --watch=false --reporters spec,kjhtml,coverage,junit --browsers=ChromeHeadlessNoSandbox --code-coverage --progress false

    Stylus usage is deprecated and will be removed in a future major version. To opt-out of the deprecated behaviour, please migrate to another stylesheet language.

11 07 2022 09:57:04.179:INFO [karma-server]: Karma v6.4.0 server started at http://localhost:9881/
11 07 2022 09:57:04.190:INFO [launcher]: Launching browsers ChromeHeadlessNoSandbox with concurrency unlimited
11 07 2022 09:57:04.201:INFO [launcher]: Starting browser ChromeHeadless
11 07 2022 09:57:06.277:INFO [Chrome Headless 99.0.4844.74 (Mac OS 10.15.7)]: Connected on socket Uv0QiFWntPWc7I6tAAAB with id 98987548
Chrome Headless 99.0.4844.74 (Mac OS 10.15.7) LOG LOG: 'JQMIGRATE: Migrate is installed with logging active, version 3.3.2'
Chrome Headless 99.0.4844.74 (Mac OS 10.15.7) LOG: 'JQMIGRATE: Migrate is installed with logging active, version 3.3.2'
Chrome Headless 99.0.4844.74 (Mac OS 10.15.7) WARN LOG: 'JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray'

  DashboardPerformanceComponent
    ✗ should test parseClientsByAvgDataRateResponse
	Failed: Errors during JIT compilation of template for DashboardPerformanceComponent: Opening tag "app-ui-help-tag" not terminated. ("export default "[ERROR ->]<app-ui-help-tag [(uiHelpEnabled)]=\"helpEnabled\" [isParent]=\"false\">\n</app-ui-help-tag>\n<div #s"): ng:///DashboardPerformanceComponent/template.html@0:16, Unexpected closing tag "app-ui-help-tag". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("export default "<app-ui-help-tag [(uiHelpEnabled)]=\"helpEnabled\" [isParent]=\"false\">\n[ERROR ->]</app-ui-help-tag>\n<div #shadowElement class=\"mojo-dynamic-height-header mojo-shadow-on-scroll padd"): ng:///DashboardPerformanceComponent/template.html@0:90, Opening tag "div" not terminated. ("ault "<app-ui-help-tag [(uiHelpEnabled)]=\"helpEnabled\" [isParent]=\"false\">\n</app-ui-help-tag>\n[ERROR ->]<div #shadowElement class=\"mojo-dynamic-height-header mojo-shadow-on-scroll padding-top-15\"></div>\"): ng:///DashboardPerformanceComponent/template.html@0:110, Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags ("tag>\n<div #shadowElement class=\"mojo-dynamic-height-header mojo-shadow-on-scroll padding-top-15\">[ERROR ->]</div>\n<app-body-container [shadowElement]=\"shadowElement\">\n    <div class=\"container-fluid\">\n"): ng:///DashboardPerformanceComponent/template.html@0:204, Opening tag "app-body-container" not terminated. ("iv #shadowElement class=\"mojo-dynamic-height-header mojo-shadow-on-scroll padding-top-15\"></div>\n[ERROR ->]<app-body-container [shadowElement]=\"shadowElement\">\n    <div class=\"container-fluid\">\n        "): ng:///DashboardPerformanceComponent/template.html@0:212, Opening tag "div" not terminated. ("adow-on-scroll padding-top-15\"></div>\n<app-body-container [shadowElement]=\"shadowElement\">\n    [ERROR ->]<div class=\"container-fluid\">\n        <div class=\"row\" *ngIf=\"showInferenceWidget\">\n         "): ng:///DashboardPerformanceComponent/template.html@0:272, Opening tag "div" not terminated. ("app-body-container [shadowElement]=\"shadowElement\">\n    <div class=\"container-fluid\">\n        [ERROR ->]<div class=\"row\" *ngIf=\"showInferenceWidget\">\n            <div class=\"col-xs-12\">\n           "): ng:///DashboardPerformanceComponent/template.html@0:313, Opening tag "div" not terminated. (" class=\"container-fluid\">\n        <div class=\"row\" *ngIf=\"showInferenceWidget\">\n            [ERROR ->]<div class=\"col-xs-12\">\n                <app-inference-widget [inferenceParams]=\"appClientHealthW"): ng:///DashboardPerformanceComponent/template.html@0:376, Opening tag "app-inference-widget" not terminated.

</code></pre>

I verified that HTML markup is proper in templates.

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.3.8
Node: 16.15.1
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.8
@angular-devkit/build-angular   13.3.8
@angular-devkit/core            13.3.8
@angular-devkit/schematics      13.3.8 (cli-only)
@angular/cdk                    12.2.2
@angular/cli                    13.3.8
@schematics/angular             13.3.8 (cli-only)
ng-packagr                      13.3.1
rxjs                            7.5.5
typescript                      4.4.4

</code></pre>

**I tried switching between typescript version 4.4 and 4.6 (default installed with v13), still no luck.
Also, I tried clearing node_modules multiple times and install clean, issue was not resolved.**

I came across below issues, and tried multiple solutions from there, still no luck.

https://github.com/angular/angular-cli/issues/16873

https://github.com/angular/angular/issues/34387

**Comment by JoostK** [comment]
This would need a minimum reproduction, as it's not otherwise clear what is going on here.

**Comment by swapnilfarande** [comment]
The project is internal to our organization. I will try to create reproduction steps on fresh repository if possible. But can we have some guess where we are going wrong?

**Comment by alan-agius4** [comment]
Hi @swapnilfarande 

Custom builders or issues that arise from customizing the webpack configuration are not supported by the Angular team.

**Comment by sanaa5127** [comment]
> Hi @swapnilfarande
> 
> Custom builders or issues that arise from customizing the webpack configuration are not supported by the Angular team.

I updated Angular version for 7 to 14. I was using @angular-devkit, and after updating I was getting error of sass-loader, that an additional loader is required. when I used  Custom webpack it resolved this error. And now I am getting Error that 

`Uncaught Error: JIT compiler unavailable
    at Ya (main.js:1:1446217)
    at Module.z3 (main.js:1:1603347)
    at main.js:1:4524
    at 98133 (main.js:1:4785)
    at r (runtime.js:1:147)
    at 13098 (main.js:1:352008)
    at r (runtime.js:1:147)
    at Me (main.js:1:2250429)
    at main.js:1:2250450
    at s (runtime.js:1:4115)`

 I have tried so many solutions for my Problem but nothing worked.
I have uploaded my first error (which I was getting before Using Custom-webpack) and other detail here
[https://stackoverflow.com/questions/73078680/you-may-need-an-additional-loader-to-handle-the-result-of-these-loaders-angular](url)

**Comment by alan-agius4** [comment]
Closing as custom Webpack configurations are not supported by the Angular team.
