### ISSUE TITLE
`ng g` command does not recognize parameters from a custom schematic

### ISSUE THREAD

**Issue by Lipata** [angular/angular-cli#23548]
# 🐞 Bug report

### Command 

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: 13.3.8

### Description

`ng g` command does not recognize parameters from a custom schematic. 

```cosnsole
ng g @igniteui/angular-schematics:component --template=grid --name=newGrid --skipRoute=false
```

is throwing the following error:

```console
Error: Unknown argument: skipRoute
```
It does recognize the other two parameters --template and --name. 
[Here](https://github.com/IgniteUI/igniteui-cli/blob/master/packages/ng-schematics/src/component/schema.json) is the custom schematics schema.json. 

## 🔬 Minimal Reproduction

1. npm i -g @angular/cli
2. npm i @igniteui/angular-schematics
3. ng new test_proj
4. ng add igniteui-angular
5. ng g @igniteui/angular-schematics:component --template=grid --name=newGrid --skipRoute=false

## 🔥 Exception or Error
<pre><code>
Error: Unknown argument: skipRoute
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 14.0.5
Node: 16.13.0
Package Manager: npm 8.12.2
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1400.5 (cli-only)
@angular-devkit/core         14.0.5 (cli-only)
@angular-devkit/schematics   14.0.5 (cli-only)
@angular/cli                 14.0.5 (cli-only)
@schematics/angular          14.0.5 (cli-only)

</code></pre>

**Comment by alan-agius4** [comment]
Command line options needs to be provided in kebab case format.`--skip-route` instead of `--skipRoute`.

**Comment by Lipata** [comment]
@alan-agius4 thank you for the help! If I remember correctly this was working even with camelCase, prior to version 14? Is there documentation about that?
