### ISSUE TITLE
ng build and ng serve only use the source environment file

### ISSUE THREAD

**Issue by timric** [angular/angular-cli#2354]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.15
node: 6.2.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.

The following is an excerpt from my angular-cli.json file:
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.dev.ts",
        "prod": "environments/environment.prod.ts",
        "local": "environments/environment.local.ts"
      }

Each of the specified files has different information, most notably I switch on a field called env in my app.module.ts file. However, regardless of which flag I pass to ng build or ng serve I only get the values from the file tagged in 'source'.

Regardless of how I call the command I am unable to get values from my dev, prod, or local files.
examples of commands run:
ng serve --dev
ng serve --prod
ng serve --target=development --environment=dev
ng serve --target=development --environment=prod
ng serve --environment=dev
ng serve --environment=prod

4. The log given by the failure. Normally this include a stack trace and some
   more information.

No log information.

5. Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jgo4th** [comment]
I am having this same issue on Mac OSX

angular-cli: 1.0.0-beta.14
node: 4.5.0
os: darwin x64

**Comment by filipesilva** [comment]
Can you provide exact repro steps? I seem to be able to get values from different env files.

**Comment by jgo4th** [comment]
OS? Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OSX Yosemite 

Versions. Please run ng --version. If there's nothing outputted, please run
in a Terminal: node --version and paste the result here:

angular-cli: 1.0.0-beta.16
node: 4.5.0
os: darwin x64

Repro steps. Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

The app was created using the CLI and I have been steadily updating the versions as they've been released. I followed the guide to upgrade to the latest webpack build using the guide. 

When I run  `ng serve --prod ` or  `ng serve` . My application uses the same enviromental file, _enviroment.ts_ instead of the contents of _enviroment.prod.ts_ when I run the latter.

Content of angular-cli.json apps object. 
```
"apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": "assets",
      "index": "index.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts",
        "prodNonMini": "environments/environment.prodNonMini.ts"
      }
    }
  ]
```
The log given by the failure. Normally this include a stack trace and some more information.
No log information.

Mention any other details that might be useful.
I have moved the environment folder to the src folder as stated in the upgrading guide and 

Output of `ls` on the src folder
```
src/favicon.ico		src/polyfills.ts	src/tsconfig.json
src/index.html		src/styles.css		src/typings.d.ts
src/main.ts		src/test.ts

src/app:
app.component.html	app.routing.ts		pipes
app.component.scss	domain			rxjs-operators.ts
app.component.spec.ts	environment.ts		services
app.component.ts	images			shared
app.module.ts		index.ts		views

src/assets:
css	fonts	images

src/environments:
environment.prod.ts		environment.ts
environment.prodNonMini.ts

src/testing:
data		index.ts	router-stubs.ts
```

**Comment by filipesilva** [comment]
@jgo4th on a brand new project, I tried changing the following in `src/app/app.component`:
```
import { environment } from '../environments/environment';
console.log(environment);
```
Then I ran `ng serve --prod` and show this on the console `Object {production: true}`.

I wonder if this is related to how the import is being processed... Can you show me your import?

**Comment by filipesilva** [comment]
I also tried one level deeper, by doing `ng genererate class new-comp` and putting the import/log there:
```
import { environment } from '../../environments/environment';
console.log(environment);
```
```
main.4746ff9….bundle.js:1429 Object {production: true}
main.4746ff9….bundle.js:1976 Object {production: true}
```

**Comment by kernowjoe** [comment]
I had this issue that came from the angular-cli.json with duplicate/incorrect data, on both osx and linux.

From your example it seems `"dev": "environments/environment.ts",` isn't needed and I think this was similar to my set up, on removing the duplicate links to a file, things are working fine.

**Comment by timric** [comment]
Thank you for all of the suggestion. I seem to have found the solution to my particular issue.
My code exists on a separate drive from my system drive, however, I have this linked to a folder on windows using the command mklink /j <source> <destination>. Apparently environment flags get lost when using the command line from the linked folder, instead of directly in the source folder.
I have verified that when accessing the directory directly I am able to use the environment flags with no issue. I am curious if the same would be true for symlinks in Mac or Linux, but I am not sure.

**Comment by jgo4th** [comment]
@filipesilva 
There was a erroneous file left over in my transition between versions. In previous versions there was an environment file in the _app_ folder.

I didn't realize this file was no longer overwritten by the build tool and was referencing it. Once I reference the environment files from the _src/environments_ folder, it worked correctly. I would try and maybe clear this up in the guide to upgrade.

**Comment by filipesilva** [comment]
So glad to hear this feature is not broken, this issue was getting me worried! 

@jgo4th we did once have the files there, yeah. I don't wanna add it to the migration guide because it is *explicitly* for beta.10->beta.14, but I hope that whoever also has that problem finds your comment here.

**Comment by tdjordjevic-telesign** [comment]
try ng serve --env dev. That works
