### ISSUE TITLE
Vulnerabilities reported by `npm audit` for Angular CLI v13.2.3 project

### ISSUE THREAD

**Issue by sahilbabbar** [angular/angular-cli#23553]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

- [x] Other: `npm audit`
### Is this a regression?
Yes

### Description

`npm audit` reports few vulnerabilities, although they doesn't seem to ship with production package, but would like to remove them.

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Simply run `npm audit` on an Angular project made with `v13.2.3`.

## 🔥 Exception or Error

<pre><code>
 High            Inefficient Regular Expression Complexity in
                  chalk/ansi-regex

  Package         ansi-regex

  Dependency of   @angular/cli [dev]

  Path            @angular/cli > @schematics/angular >
                  @angular-devkit/schematics > ora > strip-ansi > ansi-regex

  More info       https://github.com/advisories/GHSA-93q8-gq69-wqmw

  High            Inefficient Regular Expression Complexity in
                  chalk/ansi-regex

  Package         ansi-regex

  Dependency of   @angular/compiler-cli [dev]

  Path            @angular/compiler-cli > yargs > cliui > wrap-ansi >
                  string-width > strip-ansi > ansi-regex

  More info       https://github.com/advisories/GHSA-93q8-gq69-wqmw

  High            Inefficient Regular Expression Complexity in
                  chalk/ansi-regex

  Package         ansi-regex

  Dependency of   @angular/cli [dev]

  Path            @angular/cli > pacote > @npmcli/run-script > node-gyp >
                  npmlog > gauge > wide-align > string-width > strip-ansi >
                  ansi-regex

  More info       https://github.com/advisories/GHSA-93q8-gq69-wqmw
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.3
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cli                    13.2.3
@schematics/angular             13.2.3
rxjs                            6.6.3
typescript                      4.4.4
</code></pre>

**Anything else relevant?**

**Comment by alan-agius4** [comment]
Thanks for reporting this. The effected package is a transitive dependency which is not used directly by the Angular packages. 

Lucky a new versions of this dependency has been released, as such please delete your lock file and run a fresh `npm install`.
