### ISSUE TITLE
Issue creating a child component, the Import statement uses backslash instead of forwardslash

### ISSUE THREAD

**Issue by scastaldi** [angular/angular-cli#2357]
> Please provide us with the following information:
> ---------------------------------------------------------------

1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 7

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.2.2
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
a - Create a Component
b - Create a child component

4. The log given by the failure. Normally this include a stack trace and some
   more information.
ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve './form-groupgroups/groups.component' in 'D:\Dev\a2cli\src\app'
 @ ./src/app/app.module.ts 16:0-71
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi main

5. Mention any other details that might be useful.
It is not a big deal, but I thought I would reported since it should be an easy fix.
When creating a child component ex.  ng g component parent/child, the cli creates with backslash instead of forward slash... 
**import { GroupsComponent } from './form-group\groups/groups.component';**

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment]
Logged with #2132. It's caused by the command line arg being directly inserted into the path, rather than being manipulated to match the OS slash preference. Just use forward slashes when you generate routes and everything is peachy.

**Comment by scastaldi** [comment]
works for me! thanks!
