### ISSUE TITLE
"@angular/cli": "14.0.5"  Unknown error: Error: Cannot find module '../commands/doc/cli'

### ISSUE THREAD

**Issue by Bernd-T** [angular/angular-cli#23580]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
yes

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

Updated my project from angular 13 to 14 today with v.14.0.6 and during build the following error occured:
```
Unknown error: Error: Cannot find module '../commands/doc/cli'
Require stack:
- C:\Repos\XXX\node_modules\@angular\cli\src\command-builder\command-runner.js
- C:\Repos\XXX\node_modules\@angular\cli\lib\cli\index.js
- C:\Repos\XXX\node_modules\@angular\cli\lib\init.js
```

Looking at the according **node_modules\@angular\cli\src\command-builder\command-runner.js** File in my **node_modules** folder if find the following code at **line 23**:
```
const cli_8 = require("../commands/doc/cli");
```
Looking in my folder structure at node_modules the **node_modules\@angular\cli\src\commands\doc** folder is missing.

Some days ago I've migrated another project from angular v.13 to 14, it was version v.14.0.5 and in that project, the **node_modules\@angular\cli\src\commands\doc** folder exists.

## 🌍 Your Environment

<pre><code>

Angular CLI: 10.2.3
Node: 16.15.1
OS: win32 x64

Angular: 14.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.6
@angular-devkit/build-angular   14.0.6
@angular-devkit/core            14.0.6
@angular-devkit/schematics      14.0.6
@angular/cdk                    13.3.9
@angular/material               13.3.9
@schematics/angular             14.0.6
@schematics/update              0.1002.3 (cli-only)
rxjs                            6.5.5
typescript                      4.6.4

</code></pre>

**Comment by alan-agius4** [comment]
From the `ng version` it seems that you are using `@angular/cli` version 10.

Can you please run the below and provide the output
```
npm ls @angular/cli
```

**Comment by alan-agius4** [comment]
No sure why `node_modules\@angular\cli\src\commands\doc` is being deleted in one of your projects but this is not caused by the Angular CLI.  

Maybe one of the dependencies is doing something funk?

**Comment by Bernd-T** [comment]
Don't know - I have to check the differences between the working project and the broken one. I did a step-by-step migration for both projects (one is a library, the other one the app which consumes the library) from Angular 11 to 14. Until v.13 both projects compiled and worked as intended, After the update from v.13 to 14 the library-project still compiled and worked but the app-project was broken.

I'll do a deeper research on monday. Thank you for your support so far @alan-agius4 and have a nice weekend.

**Comment by Bernd-T** [comment]
I've found the problem - it wasn't Angular CLI.
The problem was a file `.yarnclean` which existed in the root-directory of the broken project (and not in the other project) and was unchanged for ages.
This file contained an entry to delete all `doc` directories in the `node_modules ` folder during the cleanup step (and also all `test ` folders).  

**original `.yarnclean` file**
```
# test directories
__tests__
test
tests
powered-test

# asset directories
docs
doc
website
# images
# Assets

# examples
example
examples

# code coverage directories
coverage
.nyc_output
!istanbul-reports/lib/html/assets
!istanbul-api/node_modules/istanbul-reports/lib/html/assets

# build scripts
Makefile
Gulpfile.js
Gruntfile.js

# configs
.tern-project
.gitattributes
.editorconfig
.*ignore
.eslintrc
.jshintrc
.flowconfig
.documentup.json
.yarn-metadata.json
.*.yml
*.yml

# misc
*.gz
```

Workaround was to delete those entries in the file.

As this  `.yarnclean`  file wasn't touched for years in the project folder, I assume that in Angular v.14 there were some new require/input statements added to `node_modules@angular\cli\src\command-builder\command-runner.js`.

Kudos goes to this Stackoverflow thread: https://stackoverflow.com/questions/41966938/yarn-removes-folder-within-installed-dependency

Once again, thanks for your quick response and support @alan-agius4

**Comment by Bernd-T** [comment]
One final question: how can I tell my project to use the local CLI and not the global?

**Comment by alan-agius4** [comment]
By default the global CLI will use the local CI.

If you don’t have the global CLI install you can use `yarn ng`
