### ISSUE TITLE
build fails on memory

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#23598]
# 🐞 Bug report

```bash
ng build
```

fails with the following stack:

 Generating browser application bundles (phase: building)...node:internal/buffer:959
    super(bufferOrLength, byteOffset, length);
    ^

<pre>
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at new Uint8Array (<anonymous>)
    at new FastBuffer (node:internal/buffer:959:5)
    at createUnsafeBuffer (node:internal/buffer:1062:12)
    at Function.allocUnsafeSlow (node:buffer:388:10)
    at read (\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\serialization\FileMiddleware.js:597:32)
    at \node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\serialization\FileMiddleware.js:657:7
    at \node_modules\graceful-fs\graceful-fs.js:362:16
    at FSReqCallback.oncomplete (node:fs:201:23)

</pre>

## Environment

<pre><code>
Angular CLI: 14.0.3
Node: 18.5.0 (Unsupported)
Package Manager: npm 8.14.0
OS: win32 ia32

Angular: 14.0.3
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.3
@angular-devkit/build-angular   14.0.3
@angular-devkit/core            14.0.3
@angular-devkit/schematics      14.0.3
@angular/flex-layout            13.0.0-beta.38
@nguniversal/express-engine     14.0.2
@schematics/angular             14.0.3
ng-packagr                      14.0.2
rxjs                            7.5.5
typescript                      4.7.4
webpack                         5.73.0
</code></pre>

### More Info

Large project, 35Mb in previous development build.

Node environment variable set to --max-old-space-size=16384.

**Comment by zehavibarak** [comment]
apparently, ng writes to  .angular folder, which grow to > 350GB!!

**Comment by alan-agius4** [comment]
That is strange since we do purge old data from the `.angular`. 

Can you try to use a supported version of Node.JS version 14 or 16 and see if the problem persists?

**Comment by zehavibarak** [comment]
It does + removing it didn't solve the issue.

**Comment by zehavibarak** [comment]
any idea what would cause
```
 c:\ws\src\util-inl.h:378: Assertion `!(n > 0) || (ret != nullptr)' failed.
 1: 0137E318 v8::sampler::Sampler::Start+17832
```
?

**Comment by alan-agius4** [comment]
That typically indicates that you have the wrong architecture version of Node JS installed. 
I checked again the above `ng version` and it does appear that you have the 32bit version of Node.js installed which is obviously wrong.

It appears that installing the wrong version is a recurrent issue for you https://github.com/angular/angular-cli/issues/23280#issuecomment-1145979714, thus to mitigate this I highly suggest that you use [NVM](https://github.com/coreybutler/nvm-windows) to manage your Node versions, also please use only LTS versions of Node.JS as non LTS versions are not supported by the Angular CLI.

**Comment by zehavibarak** [comment]
holy shit! thanks
