### ISSUE TITLE
Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js): Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by avarndell** [angular/angular-cli#23597]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

 A clear and concise description of the problem...

I separated my code into modules and now I'm getting the following errors with no other explanation.  I tried cleaning out the node_modules folder, cleared cache, and delete the package-lock file.  

I also confirmed that I don't have overlapping module imports.

## 🔥 Exception or Error

<pre><code>

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Maximum call stack size exceeded

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Maximum call stack size exceeded
</code></pre>

## 🌍 Your Environment
<pre><code>

{
  "name": "src",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "start-dev": "ng serve --ssl --ssl-key xxxx.key --ssl-cert xxxxx.crt",
    "build": "ng build --configuration=production",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.0.6",
    "@angular/common": "^14.0.6",
    "@angular/compiler": "^14.0.6",
    "@angular/core": "^14.0.6",
    "@angular/forms": "^14.0.6",
    "@angular/platform-browser": "^14.0.6",
    "@angular/platform-browser-dynamic": "^14.0.6",
    "@angular/router": "^14.0.6",
    "@auth0/auth0-angular": "^1.10.0",
    "@fortawesome/angular-fontawesome": "^0.11.1",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@mobiscroll/angular": "^4.10.9",
    "@popperjs/core": "^2.11.5",
    "animate": "^1.0.0",
    "animate.css": "^4.1.1",
    "bootstrap": "^5.1.3",
    "core-js": "^3.23.3",
    "rxjs": "~7.4.0",
    "twilio-video": "^2.21.3",
    "util": "^0.12.4",
    "webpack": "^5.73.0",
    "wowjs": "^1.1.3",
    "zone.js": "^0.11.6"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.6",
    "@angular-eslint/builder": "14.0.2",
    "@angular-eslint/eslint-plugin": "14.0.2",
    "@angular-eslint/eslint-plugin-template": "14.0.2",
    "@angular-eslint/schematics": "14.0.2",
    "@angular-eslint/template-parser": "14.0.2",
    "@angular/cli": "^14.0.6",
    "@angular/compiler-cli": "^14.0.6",
    "@types/jasmine": "^4.0.3",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^18.0.0",
    "@types/offscreencanvas": "^2019.7.0",
    "@typescript-eslint/eslint-plugin": "5.29.0",
    "@typescript-eslint/parser": "5.29.0",
    "eslint": "^8.18.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-prettier": "^4.2.1",
    "jasmine-core": "~4.2.0",
    "karma": "^6.4.0",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "prettier": "^2.7.1",
    "prettier-eslint": "^15.0.1",
    "ts-node": "~10.8.1",
    "tslib": "^2.4.0",
    "typescript": "~4.7.4"
  }
}

tsconfig:
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "forceConsistentCasingInFileNames": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2017",
    "module": "es2020",
    "typeRoots": ["./types", "./node_modules/@types"],
    "lib": ["es2018", "dom"]
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  }
}
</code></pre>

**Anything else relevant?**

 No

no

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by richardDev79** [comment]
I get the same problem, after I separated my code into modules


![Capture d’écran 2022-07-21 215615](https://user-images.githubusercontent.com/36651778/180322053-5e2b6129-872b-4540-a64d-ca8ea001d6f9.png)

**Comment by NaeemKhan14** [comment]
I am having the same problem as @richardR59. I separated my code into different modules and that's when I started having this problem.

**Comment by fitprotracker** [comment]
I get the same problem.  I am using Nx with libraries.  Been running fine update until I did a manual rename of the Nx lib project.  After that, it is broken with the same messaging. 

I have removed the Nx lib project, then run again and it works.  But I create a new Nx lib project, it throws the error once I add it to the main app. 


![image](https://user-images.githubusercontent.com/52284584/181125097-b5cb0e89-5c73-4bd9-a0ee-2b0d38e6815a.png)

**Comment by alan-agius4** [comment]
@richardR59 & @fitprotracker can you please provide a minimal reproduction as otherwise I am afraid that we cannot investigate this issue.

**Comment by richardR59** [comment]
> @richardR59 & @fitprotracker can you please provide a minimal reproduction as otherwise I am afraid that we cannot investigate this issue.

@alan-agius4 I think Angular 14 version forces us to use standalone instead of module

**Comment by SebaInfante** [comment]
same problem. When working on a module it shows these errors. This module is the most complex, since it activates cameras and QR readers.

**Comment by codepip2007** [comment]
Same error when code-splitting.

**Comment by alan-agius4** [comment]
@richardR59, standalone components are on opt-in base. 

A minimal reproduction is required to investigate this issue.

**Comment by fitprotracker** [comment]
> @richardR59 & @fitprotracker can you please provide a minimal reproduction as otherwise I am afraid that we cannot investigate this issue.

@alan-agius4 I ended up removing the nx lib project and starting from scratch.  I think what happened was some sort of circular reference.  so I imported my project one by one and was able to get it to work.  

I think it does have something with an import in the lib project and the main app module with circular reference that caused it.

**Comment by richardR59** [comment]
@alan-agius4 & @fitprotracker 

I did a refactoring of all the modules as a standalone component and the project now works.

**Comment by kwesiandy** [comment]
> I get the same problem. I am using Nx with libraries. Been running fine update until I did a manual rename of the Nx lib project. After that, it is broken with the same messaging.
> 
> I have removed the Nx lib project, then run again and it works. But I create a new Nx lib project, it throws the error once I add it to the main app.
> 
> ![image](https://user-images.githubusercontent.com/52284584/181125097-b5cb0e89-5c73-4bd9-a0ee-2b0d38e6815a.png)

Circular reference in one more  modules import

**Comment by uibhanu5** [comment]
![Screenshot from 2022-08-24 10-55-35](https://user-images.githubusercontent.com/46883376/187918439-952bd8e9-3951-40ce-a9da-df26192c900f.png)
Hello sir @alan-agius4 facing this issue where i can able to run the same application successfully without any webpack build issue , but in my machine when i try to run getting this in terminal

**Comment by DundinathG** [comment]
@uibhanu5 Hello Bhanu, were you able to resolve this issue ?
If yes, Can you able to help me out with the solution - i am seeing this issue in my local as i am trying to upgrade the angular version to 14.2.2

**Comment by richardR59** [comment]
> @uibhanu5 Hello Bhanu, were you able to resolve this issue ? If yes, Can you able to help me out with the solution - i am seeing this issue in my local as i am trying to upgrade the angular version to 14.2.2

https://github.com/angular/angular-cli/issues/23597#issuecomment-1200565037

**Comment by avarndell** [comment]
There was an issue with one of my components.
