### ISSUE TITLE
Angular 14 Upgrade, removing deployUrl as a build option causing fail in loading chunk files from subfolder

### ISSUE THREAD

**Issue by kiranahid** [angular/angular-cli#23595]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

We have a scenario where we deploy the UI code under the subfolder wwwroot/approot in IIS server, we are using deployUrl as 'approot ' to load the lazy loaded chunk files. When we upgrade the Angular 14, deployUrl is deprecated and if we use baseHref, it's failing to load the chunk files. It's trying to load the chunk files from the main root i.e webroot but the files are under wwwroot/approot. I couldn't find any solution to acheive this without deployUrl.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.6
Node: 16.12.0
Package Manager: npm 8.1.0
OS: win32 x64
```

**Comment by kiranahid** [comment]
Adding to the above issue, we are in Hybrid application where both angularjs and Angular is running, we keep only Angular files under subfolder, deployUrl is helpful in this case. We have deployed both angularjs and Angular on IIS server.

**Comment by alan-agius4** [comment]
It seems that the base-href is not being set in the `index.html`, Maybe you are not using the `index.html` generated by the Angular CLI?

**Comment by kiranahid** [comment]
No, we are not using index.html generated by Angular CLI, We are using razor c#, we use index.cshtml, base-href cannot be set in cshtml this will redirect all other files to subfloder, only Angular files needs to be loaded from the subfolder.

**Comment by kiranahid** [comment]
yeah, we don't run Angular application on separate web server, let me check if the library is useful in our case. I saw many people are using deployUrl, this was easy to handle in such use cases.

**Comment by kiranahid** [comment]
Wwwroot is our server path, we have a subfolder inside that app2
![image](https://user-images.githubusercontent.com/109506512/180155527-8837233b-18ea-4d28-89b4-8d08950a0982.png)

 
In C# razor index.cshtml, we inject the main files and these files are also located in app2 folder. We keep Angular UI in app2 and angular js files in app. So, we cannot set base-href in Index.cshtml. 
 
Main files are loaded properly, but chunk files are failing to load because it’s not trying to load from app2. When we use base-href, wherever we deploy the main files, it should load the chunk files from the same location or there should be an option to give the path for chunk files.
When I google it, many people are struggling with this, there should be a way to give the path where angular has been deployed, deployUrl has that flexibility to keep the code wherever we want.
I saw the generated build files, it’s not adding deployUrl on compiling, whenever we make a call for the script, it will just add this path and load the scripts on runtime.
 
![image](https://user-images.githubusercontent.com/109506512/180155500-0c8f2972-57f9-4cc1-83dc-8d9a66a69478.png)


But now, adding this piece of code in main.ts works fine
import { environment } from './environments/environment';

declare var  __webpack_require__;
__webpack_require__.p = environment.deployUrl;

In environment file
export const environment = {
  production: false,
  deployUrl: 'app2/'
};


Is it the right way to do?

**Comment by alan-agius4** [comment]
Like any Webpack specific feature the usage of `webpack_require` is not supported. base-href by design and spec should not alter the contents of the JavaScript files. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base

You architecture it quite specific and not something that the Angular CLI was designed to handle. As such using a custom builder that extends the CLI is the recommended approach.

**Comment by kiranahid** [comment]
As you have suggested, using @angular-builders/custom-webpack:browser and setting the publicPath in custom webconfig file resolved the issue. 
Thanks for your suggestions @alan-agius4 .
