### ISSUE TITLE
ng install issues and proposals

### ISSUE THREAD

**Issue by xmlking** [angular/angular-cli#236]
### Issues
1. shouldn't allow `ng install *`
2. shouldn't create `dist\node_modules`
3. `ng install ng2-slimscroll` corrupt my code  

<img width="1233" alt="screen shot 2016-02-21 at 1 29 05 pm" src="https://cloud.githubusercontent.com/assets/627951/13205536/28742822-d89f-11e5-973d-bac7e0d2bfbf.png">

### NPM upgrade requests
1. Angular: 2.0.0-beta.7
2. rxjs: 5.0.0-beta.2
2. typescript : next

### Proposals 
when developer manually installed a lib via npm and add to  `vendorNpmFiles`  in `ember-cli-build.js`
```js
    vendorNpmFiles: [
        'moment/moment.js'
    ]
```
automatically add to `System.config` in `index.html ` 
```js
  paths: {
    'moment': 'vendor/moment/moment.js'
  }
```

**Comment by hansl** [comment]
We are well aware of issues with the third party installation and are in the process of formulating a better solution. The whole process is being thought out and we will carefully take this into consideration. 

As the thing will be likely ripped out and not used, I'll close this and suggest you wait for the new solution. You can for now install third parties from npm and manually add them to your build.

Cheers.

**Comment by NathanWalker** [comment]
It makes sense for the lib install tool to become a separate tool outside of angular-cli. 

@hansl Since the intent of the effort was community grown, we would appreciate some insight on what you guys are thinking?

**Comment by hansl** [comment]
There's a design that's being discussed on; https://github.com/angular/angular-cli/pull/255. This is still in design phase.

**Comment by NathanWalker** [comment]
Thank you @hansl ! Really like the sounds of that even at the early stage :+1:
