### ISSUE TITLE
[FEAT]: Use the appropriate package manager by default when using @angular to install

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular-cli#23617]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...

When using `yarn create @angular` to scaffold a new application, it still uses `npm` to install dependencies.

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

When using a different package manager` to scaffold a new application, it should use the package manager used to initiate the command.

npm init @angular - npm
yarn create @angular - yarn
pnpm create @angular - pnpm (if pnpm works?)

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

The alternative command works

```sh
yarn create @angular -- --package-manager yarn
```

**Comment by alan-agius4** [comment]
Love the idea @brandonroberts.

**Comment by brandonroberts** [comment]
Awesome!
