### ISSUE TITLE
`require` is failing in 3rd party library when running `ng test`

### ISSUE THREAD

**Issue by arturovt** [angular/angular-cli#23632]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] test

### Is this a regression?

Don't know

### Description

I've been searching for similar issues but haven't found anything related until I missed something. `require` calls are not proceeded by webpack in 3rd party libraries. This example demonstrates the issue with a simple library built with `ng-packagr`; in practice, there're more other libraries that use `require` inside.

The `require` may be replaced with `import` to fix the issue, but imports are hoisted and you may see the code on why `require` is used.

At the end, is there a way to fix that issue?

## 🔬 Minimal Reproduction

```sh
$ git clone git@github.com:arturovt/angular-test-require-in-3rd-party-lib.git
$ cd angular-test-require-in-3rd-party-lib
$ yarn
$ yarn ng build library-with-require
$ yarn ng test angular-test-require-in-3rd-party-lib --watch false

# Now go to `src/app/app.component.spec.ts` and see the commented line (it's `getSomethingBySelector('')`). Uncomment this line and run again:
$ yarn ng test angular-test-require-in-3rd-party-lib --watch false
```

## 🔥 Exception or Error

<pre><code>
Chrome 103.0.5060.134 (Linux x86_64) ERROR
  An error was thrown in afterAll
  Uncaught ReferenceError: require is not defined
  ReferenceError: require is not defined
      at Module.8688 (http://localhost:9878/_karma_webpack_/webpack:/projects/library-with-require/src/public-api.ts:9:11)
      at __webpack_require__ (http://localhost:9878/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
      at Module.4882 (http://localhost:9878/_karma_webpack_/main.js:13:78)
      at __webpack_require__ (http://localhost:9878/_karma_webpack_/webpack:/webpack/bootstrap:19:1)
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.9
Node: 16.10.0
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
ng-packagr                      13.3.1
rxjs                            7.5.6
typescript                      4.6.4
</code></pre>

**Comment by alan-agius4** [comment]
This is expected as `require` cannot be used in an ECMA module (mjs). Also `require` is indented to be used with CJS which is legacy module system for Node.js and is not supported in browser environments. 

I understand which you want to use `require`, in general I'd avoid creating patching in the library though as this are tests specific and as such should be moved to `test.ts`. You can provide a helper method that does the patching from a secondary entry-point ex: `library-with-require/testing`.
