### ISSUE TITLE
[Proposal] Simplify starter template by moving all static files and assets in a single folder

### ISSUE THREAD

**Issue by sinedied** [angular/angular-cli#23644]
# 🚀 Feature request

### Command (mark with an `x`)

- [x] new

### Description

The current Angular template generated by `ng new` provides a structure like this for static files and assets:

```bash
src/
  |- assets/
  |  |- .gitkeep
  |- index.html
  |- favicon.ico
  |- ...
```

This structure results in multiple (minor) inconveniences:
- You have to generate an empty `.gitkeep` file to keep the `assets` folder in git. The presence of this file and its purpose may be confusing for new developer.
- When referencing your static assets places in `assets` folder, you have to add the `./assets/` prefix in all your URLs. When you different kind of assets, you often end up with URLs like `./assets/images/my-image.jpg` adding an extra prefix, making your URLs longer.
- There's no way to add static files at the root of your `dist` folder directly without modifying the build in `angular.json` config.
- If you start to add static files to be copied at the root of your `dist` folder, your `src/` folder will start to be cluttered. Moreover, you'll have to add an entry fo each of the new files you want to add in the `angular.json` config.

### Describe the solution you'd like

I propose a small change in the structure that would solve all these issues at once:

```bash
src/
  |- public/
  |  |- index.html
  |  |- favicon.ico
  |- ...
```
And the `assets` section of `angular.json` becomes:
```json
            "assets": [
              {
                "glob": "**/*",
                "input": "src/public",
                "output": "."
              }
            ],
```

In addition to fixing all the issues listed above, this makes the starter template simpler, and use the same convention as all other major frameworks (ie Vue, React, Svelte...) for static assets.
I don't see any drawbacks from making this change, beside a small change in habits.

If you're willing to accept this change, I'm willing to make the PR for it 🙂 

### Describe alternatives you've considered

I considered 3 alternatives for the solution:

- Same solution as above, but putting everything  under `assets/` folder instead of `public`:
  * May be confusing for existing Angular developer, as this would remove the need for `./assets/` prefix in URLs
  * Static files like `index.html` can't really be called `assets`

- Keep existing `assets/` folder and add a `public/` folder
  * Doesn't solve the first 2 issues
  * May be confusing as to the difference between the two folders
  * `assets/` folder becomes redundant

- Same solution as above, but using a more explicit `static/` folder name instead of `public`:
  * The `public` convention is already used in a lot of frameworks and tools in the web ecosystem, so it doesn't feel right to add *yet another convention*.

**Comment by alan-agius4** [comment]
Hi @sinedied, 

Thanks for this feature request. While this might seem like a trivial change, this will have huge impact on the community and educational material as it will invalid a lot of these with an overall little perceived benefit. 

> You have to generate an empty .gitkeep file to keep the assets folder in git. The presence of this file and its purpose may be confusing for new developer.

I think the filename is quite self explanatory on why it is there. 

> When referencing your static assets places in assets folder, you have to add the ./assets/ prefix in all your URLs. When you different kind of assets, you often end up with URLs like ./assets/images/my-image.jpg adding an extra prefix, making your URLs longer.

I don't see this as a big problem. 

> There's no way to add static files at the root of your dist folder directly without modifying the build in angular.json config.

That is indeed correct but there are very few assets that are required to be in the root. It would also be confusing when checking the `dist` to identify copied assets and processed assets (example assets extracted by the css build pipeline). This would be an increase chance of colliding filenames.

> If you start to add static files to be copied at the root of your dist folder, your src/ folder will start to be cluttered. Moreover, you'll have to add an entry fo each of the new files you want to add in the angular.json config.

This seems would be a bad design choice, creating a separate a directory or renaming the `assets` and copy the contents of this directory to the root of the `dist` would be better.

Some other observations:
- Having a `public` directory under `src` is confusing as this is actually not the `public` folder. Users might think that the web-server should point to this directory. IMHO `assets` better describes the purpose of this directory.
- `index.html` should not be copied. This is not an asset nor a static resource. The `index.html` is used and heavily augmented by the build process.
- I do see that moving the `index.html` and `favicon.ico` into a separate directory to make the structure cleaner.
- This is possible to be archived without changing the default structure with minimal configuration changes.

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by sinedied** [comment]
Thanks @alan-agius4 for your detailed answer.

I agree that the biggest issue with this change would be regarding the existing learning materials, though sometimes it's worth breaking a few habits to make things simpler for the new and future Angular devs 🙂 

I also agree that in the end these are all minor inconveniences, and as said it can be fixed with a few changes. But IMHO, it's the addition of these small annoyances and extra work needed here and there that makes a lot of web devs turn away from Angular and use instead React, Vue, etc, especially newcomers.

Anyway, thanks for your time looking into this.
