### ISSUE TITLE
Angular 14.1.0 Cannot Build on RHEL 7.x when FIPS is enabled

### ISSUE THREAD

**Issue by blanchardjblake** [angular/angular-cli#23657]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [x] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Unknown - most likely not based on previous similar issue reports. Viewing similar closed issues did not yield a solution.

### Description

Angular 14.1.0 cannot build on RHEL 7.x when FIPS is enabled.

## 🔬 Minimal Reproduction
npm i
npm run build-prod

package.json
{
  "name": "excluded",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --configuration local",
    "build": "ng build",
    "build-prod": "ng build --output-hashing=none --output-path=../api/src/main/resources/static --base-href /excluded/",
    "test": "ng test",
    "unit": "ng test --watch=false",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.1.0",
    "@angular/cdk": "^14.1.0",
    "@angular/common": "^14.1.0",
    "@angular/compiler": "^14.1.0",
    "@angular/core": "^14.1.0",
    "@angular/forms": "^14.1.0",
    "@angular/platform-browser": "^14.1.0",
    "@angular/platform-browser-dynamic": "^14.1.0",
    "@angular/pwa": "^14.1.0",
    "@angular/router": "^14.1.0",
    "@angular/service-worker": "^14.1.0",
    "@elderbyte/ts-logger": "^0.1.2",
    "@elderbyte/ts-stomp": "^4.0.0",
    "core-js": "^3.24.0",
    "file-saver": "^2.0.5",
    "hammerjs": "^2.0.8",
    "jquery": "^3.6.0",
    "moment": "^2.29.4",
    "ng-recaptcha": "^10.0.0",
    "ngx-infinite-scroll": "^14.0.0",
    "rxjs": "^6.5.2",
    "zone.js": "^0.11.7"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~14.1.0",
    "@angular/cli": "~14.1.0",
    "@angular/compiler-cli": "^14.1.0",
    "@angular/language-service": "^14.1.0",
    "@types/file-saver": "^2.0.5",
    "@types/jasmine": "4.0.3",
    "@types/jasminewd2": "~2.0.10",
    "@types/jquery": "^3.5.14",
    "@types/node": "~18.6.1",
    "jasmine-core": "~4.3.0",
    "jasmine-spec-reporter": "~7.0.0",
    "karma": "^6.4.0",
    "karma-chrome-launcher": "~3.1.1",
    "karma-coverage-istanbul-reporter": "~3.0.3",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "node-sass": "^7.0.1",
    "protractor": "~7.0.0",
    "ts-mockito": "^2.6.1",
    "ts-node": "~10.9.1",
    "typescript": "~4.7.4"
  }
}

## 🔥 Exception or Error

./src/main.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS

./node_modules/css-loader/dist/runtime/api.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS

./node_modules/css-loader/dist/runtime/noSourceMaps.js - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):
Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS

## 🌍 Your Environment

Angular CLI: 14.1.0
Node: 16.15.0
Package Manager: npm 8.5.5
OS: linux x64

Angular: 14.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            6.6.7
typescript                      4.7.4

**Comment by alan-agius4** [comment]
Unfortunately this is not actionable from our end as Babel-loader doesn't work with FIPS.

See: https://github.com/babel/babel-loader/issues/910 and

**Comment by blanchardjblake** [comment]
Gotcha @alan-agius4 thank you for the direction.
