### ISSUE TITLE
Cannot run a single test file

### ISSUE THREAD

**Issue by PhiLhoSoft** [angular/angular-cli#23651]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 13

### Description

I can't find a way to run a single test file with Jest.

## 🔬 Minimal Reproduction

I have several projects testing Angular (libraries or applications) with Jest. Using @angular-builders/jest, jest-preset-angular and so on.
I used to run single test files (on Windows, simple terminal) with the following command:

ng test --testPathPattern=part-of-file-name

I believe the testPathPattern is an option of Jest, but it worked as is.

After upgrading the Angular 14.1.0 (and Jest 28, jest-preset-angular 12.2.0, etc.), it no longer work.

## 🔥 Exception or Error

<pre><code>
> ng test --testPathPattern=mention                                                                                                                                                Error: Unknown argument: testPathPattern

> ng test -- --testPathPattern=mention 
Option '--' has been specified multiple times. The value '--testPathPattern=mention' will be used.
Error: Schema validation failed with the following errors:
  Data path "/" must be array.

> ng test --include=./**/memo-mention*.ts     
Error: Unknown argument: include
</code></pre>

Note that include is mentioned in https://angular.io/cli/test, so it should work…

Note also I can use Jest Runner to run a single test; but it requires to have `import 'jest-preset-angular/setup-jest';` in `jest.setup.js` (as before) but if I have that, `ng test` complains with "Cannot set base providers because it has already been called" showing this line…

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.1.0
Node: 14.18.2
Package Manager: npm 7.24.2
OS: win32 x64

Angular: 14.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            7.5.6
</code></pre>

Extract from angular.json:

<pre><code>
        "test": {
          "builder": "@angular-builders/jest:run",
          "configurations": {
            "test": {
              "configPath": "jest.config.js"
            },
            "coverage": {
              "configPath": "jest-coverage.config.js"
            }
          },
          "defaultConfiguration": "test"
        }
</code></pre>

**Comment by alan-agius4** [comment]
The linked documentation only covers the official test builder `@angular-devkit/build-angular:karma` which this does have an `—include` option. 

The Jest builder, `@angular-builders/jest:run` is not supported by the Angular team. Please file an issue with the author of this package.
