### ISSUE TITLE
angular 13.2.6 is not running with aot "ng serve --aot"

### ISSUE THREAD

**Issue by venkatnarasimharao** [angular/angular-cli#23662]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>
Your global Angular CLI version (13.3.3) is greater than your local version (13.2.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Unknown option: '--aot'

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Anything else relevant?**

I'm trying to run using this command ng serve --aot  error: Unknown option: '--aot'

**Comment by alan-agius4** [comment]
This is working as intended. 

Please see the breaking changes section in https://github.com/angular/angular-cli/releases/tag/13.0.0
