### ISSUE TITLE
ng build --prod is not creating different hash for the main.[hash].js file

### ISSUE THREAD

**Issue by pancudaniel7** [angular/angular-cli#23672]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes

### Description

A problem when I am trying to rebuild Angular project using `ng build --prod`, the main.[hash].js file **does not change the hash** in the name of the file **for new modifications added in the code** after executing the **build command multiple times**.

The problem is that when you deploy new changes the chrome browser will not update you application on the UI.

## 🔬 Minimal Reproduction

Run first time `ng build --prod` and look at the main.[hash].js file in dist/
Run second time `ng build --prod` and look at the main.[hash].js file in dist/ (The hash looks the same)

## 🔥 Exception or Error

No

## 🌍 Your Environment

Angular CLI: 11.2.19
Node: 18.4.0
OS: darwin arm64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.19
@angular-devkit/build-angular   0.1102.19
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/cdk                    11.2.13
@angular/cli                    11.2.19
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             11.2.19
@schematics/update              0.1102.19
rxjs                            6.6.7
typescript                      4.1.6

**Anything else relevant?**

No

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
