### ISSUE TITLE
Proposition : Add flag to 'ng init/new' for angular material

### ISSUE THREAD

**Issue by thibaultsavary** [angular/angular-cli#2369]
Hey,
First, thanks for the amazing work to all the team.
It would be nice to have a flag option in order to initialize a project with the material dependencies that are available on npm such as:

`ng new myProject --material `
`ng new myProject -m `

`ng init myProject --material `
`ng init myProject -m `

**Comment by gelliott181** [comment]
+1 support from me!

Realistically though, Angular Material 2 is behind schedule and not even past Alpha. I wouldn't expect it to be integrated before the end of the year (unless the maintainers want to let us in on a secret!)

**Comment by filipesilva** [comment]
It's easy enough to install Material's dependencies after generating a new project, so I can't say we're looking at implementing such a thing.
