### ISSUE TITLE
@angular-devkit/build-angular:browser-esbuild throw error on scss import

### ISSUE THREAD

**Issue by PronDmytro** [angular/angular-cli#23698]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

I trying out the new experimental esbuild builder and got a lot of same erros with import scss files

## 🔬 Minimal Reproduction
angular.json
<pre><code>
...
  "builder": "@angular-devkit/build-angular:browser-esbuild"
...
</code></pre>

src/app/core/faq/faq.component.scss
<pre><code>
@import "src/assets/styles/variables";

.c-faq {

  &__header {
    color: $oxford-blue;
  }
}
</code></pre>

src/assets/styles/variables.scss
<pre><code>
$oxford-blue: rgba(51, 63, 82, 1);
</code></pre>

## 🔥 Exception or Error

<pre><code>
X [ERROR] [plugin angular-compiler] Could not resolve "src/assets/styles/variables"

    src/app/core/faq/faq.component.scss:1:8:
      1 │ @import "src/assets/styles/variables";
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.0.5
Node: 16.15.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 14.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.5
@angular-devkit/build-angular   14.0.5
@angular-devkit/core            14.0.5
@angular-devkit/schematics      14.0.5
@angular/cdk                    14.0.4
@schematics/angular             14.0.5
rxjs                            7.5.5
typescript                      4.7.4

</code></pre>

**Comment by alan-agius4** [comment]
This is because Sass by default is only able to resolve files relative to the containing file. Once no files matches the compile will fallback to resolve the files based on the [loadPaths/includePaths](https://sass-lang.com/documentation/js-api/interfaces/Options).

Under Webpack these work because additional paths are added in sass-loader to the include paths https://github.com/webpack-contrib/sass-loader/blob/49a578a218574ddc92a597c7e365b6c21960717e/src/utils.js#L306-L322.

You could add the `projectRoot` as `includePaths` in your `angular.json` to make this work.

**Comment by PronDmytro** [comment]
> 
Like this?
(that not working)
<pre><code>
"stylePreprocessorOptions": {
              "includePaths": [
                "src"
              ]
            },
</code></pre>

**Comment by PronDmytro** [comment]
not working(

**Comment by alan-agius4** [comment]
@PronDmytro, actually just noticed you are using 14.0 and not 14.1. SCSS support was only introduced in 14.1. 

Can you please update and see if the problem is resolved?

**Comment by alan-agius4** [comment]
@PronDmytro, that seems like indeed a bug that we need to address.
