### ISSUE TITLE
Schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

### ISSUE THREAD

**Issue by pancudaniel7** [angular/angular-cli#23692]
# 🐞 Bug report

```sh
ng build
```

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

It worked before on version 11

### Description

After running **ng build** I get this error:
**An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID**

## 🔬 Minimal Reproduction

Run **ng build** 

## 🔥 Exception or Error

<pre><code>
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.9
Node: 18.4.0 (Unsupported)
Package Manager: npm 8.0.0
OS: darwin arm64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    11.2.13
@angular/cli                    13.3.9
@angular/flex-layout            11.0.0-beta.33
@schematics/angular             13.3.9
rxjs                            6.6.7
typescript                      4.4.4
</code></pre>

**Comment by alan-agius4** [comment]
Are you using a custom builder? If so, please make sure you using a a compatible version. 

Unrelated to the above, from the `ng version` also you have various mismatching versions. Example, `@angular/cdk` is still on version `11`.

**Comment by pancudaniel7** [comment]
@alan-agius4 I am not using a custom builder. And I've increased the **cdk** version to 13.3.9 and I have the same error
```sh
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
```

**Comment by pancudaniel7** [comment]
New versions:
```sh
Angular CLI: 13.3.9
Node: 18.4.0 (Unsupported)
Package Manager: npm 8.0.0
OS: darwin arm64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             13.3.9
rxjs                            6.6.7
typescript                      4.4.4
```

**Comment by alan-agius4** [comment]
Are you using a custom builders? Please share your `angular.json`

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by pancudaniel7** [comment]
I've managed to solve this by correctly applying angular updates using [update.angular.io](https://update.angular.io/) from version **11** to **14**
