### ISSUE TITLE
Error: Optimization error [main-*.js] TypeError: Cannot read properties of undefined (reading 'comments_before') 

### ISSUE THREAD

**Issue by MH480** [angular/angular-cli#23703]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

i am using angular 13.3.9

When i run angular ng build , i encounter with error on build time, it seems the error happens in terser package , but the ng serve works fine , here is the full error coded below :

## 🔥 Exception or Error

<pre><code>
Error: Optimization error [main.99440f42c92dc940.js]: TypeError: Cannot read properties of undefined (reading 'comments_before')
#17 138.8     at AST_Return._do_print (/usr/src/app/node_modules/terser/dist/bundle.min.js:9867:47)
#17 138.8     at /usr/src/app/node_modules/terser/dist/bundle.min.js:9879:14
#17 138.8     at doit (/usr/src/app/node_modules/terser/dist/bundle.min.js:9296:13)
#17 138.8     at AST_Return.<anonymous> (/usr/src/app/node_modules/terser/dist/bundle.min.js:9303:13)
#17 138.8     at /usr/src/app/node_modules/terser/dist/bundle.min.js:10702:18
#17 138.8     at /usr/src/app/node_modules/terser/dist/bundle.min.js:8983:19
#17 138.8     at OutputStream.with_indent (/usr/src/app/node_modules/terser/dist/bundle.min.js:8948:38)
#17 138.8     at Object.with_block (/usr/src/app/node_modules/terser/dist/bundle.min.js:8982:9)
#17 138.8     at make_block (/usr/src/app/node_modules/terser/dist/bundle.min.js:10700:21)
#17 138.8     at /usr/src/app/node_modules/terser/dist/bundle.min.js:9671:9 
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.3.9
Node: 16.15.1
Package Manager: npm 8.12.1
OS: win32 x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@angular/fire                   7.4.1
@angular/flex-layout            13.0.0-beta.36
@angular/material               13.3.9
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.1.1
@schematics/angular             13.3.9
rxjs                            6.6.7
typescript                      4.6.4
webpack                         4.46.0
</code></pre>

**Anything else relevant?**

the error refers to this library code function :
<pre><code>
 /* -----[ exits ]----- */
    AST_Exit.DEFMETHOD("_do_print", function(output, kind) {
        output.print(kind);
        if (this.value) {
            output.space();
            const comments = this.value.start.comments_before; // here is error line
            if (comments && comments.length && !output.printed_comments.has(comments)) {
                output.print("(");
                this.value.print(output);
                output.print(")");
            } else {
                this.value.print(output);
            }
        }
        output.semicolon();
    });
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
