### ISSUE TITLE
feature: Generate multiple components or services with a single command

### ISSUE THREAD

**Issue by j2L4e** [angular/angular-cli#2370]
This is a minor feature request.

It would be nice to be able to generate multiple components/services/et cetera with a single command:

**Current behavior** 
`ng g c modules/main/components/{component1,component2}` which expands to
`ng g c modules/main/components/component1 modules/main/components/component2`

creates component1 as expected. Any further arguments are ignored.

**Expected behavior**
`ng g c modules/main/components/{component1,component2}` aka
`ng g c modules/main/components/component1 modules/main/components/component2`

should behave the same way as running
`ng g c modules/main/components/component1` and `ng c modules/main/components/component2` separately would.

My setup is as follows:
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: linux x64 (KDE neon 5.7.5 / Ubuntu 16.04)

**Comment by xinmeng1** [comment]
+1

**Comment by steelx** [comment]
+1

**Comment by hammadengin** [comment]
+1

**Comment by kuncevic** [comment]
It is exactly what I need right now

**Comment by filipesilva** [comment]
This isn't something we're looking at adding, but shell scripts are a viable alternative.

**Comment by vincenzorm117** [comment]
Just leaving this for those that are curious:
`ng g c {A,B}`
should generate components A and B. Note: there cannot be any white space between the curly's.

**Comment by salihsagdilek** [comment]
+1

**Comment by shiranfe** [comment]
I am using cmd var, to create all entity files.
in this example, I have already created an "admin" module (in app/admin folder). then I run all these commands together to create service, model, and components.  
just set entity, entModule vars, and then copy them all and paste in cmd

SET entity=player
SET entModule=admin
SET folder=%entModule%/%entity%/%entity%
ng g class %folder% --type=model
ng g service %folder%  --module %entModule%
ng g component %folder%List
ng g component %folder%Details
echo done!

the last row is not being commanded, so I just added "echo" command to be last.

**Comment by nikosgpet** [comment]
It would actually be a very practical feature 👍

**Comment by ranjit-redekar** [comment]
this also works,
for i in comp1 comp2; do ng g c "${i}"; done

**Comment by pascaliske** [comment]
I used the code from @ranjit-redekar and created a little bash function for me:
https://gist.github.com/pascaliske/efd0b4f21f31133533912f32a74be3d3

**Comment by Janatbek** [comment]
@ranjit-redekar, Thanks for this comment, I used it, but you could've write correct syntax or at least mention in what shell should one run this command.
