### ISSUE TITLE
msal library popup blocked issue after Angular 13 upgrade

### ISSUE THREAD

**Issue by anura-github** [angular/angular-cli#23705]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please file any Angular Framework issues at: https://github.com/angular/angular/issues/new/choose

For the time being, we keep Angular issues in a separate repository.

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
![image](https://user-images.githubusercontent.com/23335734/183424534-0c5f5b32-b0ec-473f-9732-87aad8ab6994.png)
Facing issue after angular upgrade 13
Whenever angular application makes sso call to microsoft azure, the popup window got stuck and this issue is occurring. When i clear cookies and cache everytime, i am not facing this issue. But everytime when i need to clear cache to load my application. 
Please help in resolving this issue

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
