### ISSUE TITLE
Just the main page works

### ISSUE THREAD

**Issue by alex-vido** [angular/angular-cli#23702]
OS: Ubuntu 22.03
All my programs in the actual version

My page, just work the main page. My page have the page products, cart and contact ether. But in this pages inform 404 page not found. In local, the program works very well. Can someone help me please? Is my firt contact with Angular.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
