### ISSUE TITLE
PWA White Page offline

### ISSUE THREAD

**Issue by DarkApocalypse** [angular/angular-cli#23742]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
I don't know

### Description
I got a white page without no error or 404 when i disconnect my devices(laptop, iphone, maybe android itou?).

## 🔬 Minimal Reproduction
ng new first-app --style=scss --skip-tests=true
cd first-app
ng add @angular/pwa
ng build --base-href=/first-app/
(upload dist/first-app/ folder on OVH)
(go on https://jc-webinfo.fr/first-app/)
(disconnect)
(reload)
(white page!)

## 🔥 Exception or Error
none

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.1.2
Node: 16.16.0
Package Manager: npm 8.17.0 
OS: linux x64

Angular: 14.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.2
@angular-devkit/build-angular   14.1.2
@angular-devkit/core            14.1.2
@angular-devkit/schematics      14.1.2
@schematics/angular             14.1.2
rxjs                            7.5.6
typescript                      4.7.4

</code></pre>

**Anything else relevant?**
I tried on iphone, and firefox on linux. same issue.

Zipfile here(builded and source inside folder): 
https://jc-webinfo.fr/first-app.zip

**Comment by alan-agius4** [comment]
Hi @DarkApocalypse, 

I tried visiting https://jc-webinfo.fr/first-app/ and the page is visible offline.

<img width="1723" alt="Screenshot 2022-08-15 at 08 28 38" src="https://user-images.githubusercontent.com/17563226/184587063-9e91225a-d9a4-4a58-96f7-44511ae43836.png">

**Comment by DarkApocalypse** [comment]
i use firefox 103.0.2 (64bits) snap version for Ubuntu to test for Laptop/PC,
kill ng serve to test offline cache, refresh firefox, and tada...

I use Safari on iOS 15.6.1: i add it on homescreen, kill Safari, disable wifi, open app from homescreen and tada...

I got same result from them.

**Comment by alan-agius4** [comment]
I am also unable to replicate this using FireFox offline mode. 
<img width="791" alt="Screenshot 2022-08-22 at 14 40 58" src="https://user-images.githubusercontent.com/17563226/185923470-d7776db1-2ff6-4db8-bf40-123fbc59b37b.png">

**Comment by DarkApocalypse** [comment]
I don't have anymore this trouble after rebuild it.
