### ISSUE TITLE
 show Description or logger on console before x-prompt question

### ISSUE THREAD

**Issue by nehaGI** [angular/angular-cli#23755]
Hi , 
I have a use case where I need to Display a message/description/logger/info kind of statement on console as soon as i run my command(let say ng g idp) and after displaying to message it should prompt for question. Currently what is happening x-prompt question prompt at very first and after that logger or message comes. Is there any property which we can use in schema.json that will display desired message.

I'm aware of this description property but is do not display anything on console.

required use case 
->ng g idp
This Generator create and add IDP code is your application. Please answer following question.
? enter name
? enter client id

and I don't want to use inquirer for prompting questions

**Comment by alan-agius4** [comment]
Hi @nehaGI, 

The `description` will be ignored when using prompts as in that case the value of `x-prompt` will be used as the question/description.

I am not following what you mean by you don't want to use inquirer for prompting questions. You are using `x-prompt` so inquirer will be used.

**Comment by nehaGI** [comment]
"properties": {
      "project": {
      "info": {
        "type": "string",
        "x-prompt": "ruf/idp-auth library lets you easily setup Infinity IdP Authentication for Client-side Web Apps. To set it up, it asks few questions. Details of the questions can be found on this page https://wiki.fnis.com/x/tQ_RYgI, Hit Enter to continue."
      },

I have above snippet , currently what is does is it x-prompt this as question and a ? comes before statement. What my requirement is that I was to show this statement on console as very first thing, and I want this statement to look like normal message not as a question.

you can ignore my words "and I don't want to use inquirer for prompting questions"

**Comment by alan-agius4** [comment]
@nehaGI, displaying a message prior to the prompts is not possible.

**Comment by alan-agius4** [comment]
Closing as per above comment.
