### ISSUE TITLE
Need hlep - ng serve failed

### ISSUE THREAD

**Issue by jdgabriel** [angular/angular-cli#23760]
I'm in a "legacy" project on the Angular 11 version, when I do the command ` ng server -o` I get the following error.

![image](https://user-images.githubusercontent.com/47068314/185155915-159d6e2b-8fce-49ca-bcb0-72d038a81738.png)

When I see the error.
![image](https://user-images.githubusercontent.com/47068314/185156080-5aef9276-54ad-4181-a231-f41367b63f6a.png)
Something related to `mini-css-extract-plugin `. I updated the webpack to the compatible version. And I have the same error.

Any solution?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
