### ISSUE TITLE
Feature Request: Custom Blueprints

### ISSUE THREAD

**Issue by alexweber** [angular/angular-cli#2377]
It would be great to be able to generate blueprints for the generator so that the community can build additional custom generators like for ngrx actions/effects, etc.  As far as I know the Ember CLI allows it but the cli addon overrides it.
Thanks!

**Comment by hansl** [comment]
Not going to happen until we have addon support.

**Comment by RicardoVaranda** [comment]
Any timing for when the addon support will be released?

**Comment by jusefb** [comment]
Anything happening with this? Our project is growing and this would be of great help when getting new people involved and to reduce the number of mistakes that devs make when adding new components to the application.

**Comment by brian428** [comment]
The ability to customize what gets generated seems like a must-have feature.

**Comment by forwardadvance** [comment]
We could totally do with this also. Specifically I'd like to write a generator that creates a smart-component that hooks into NGRX, with a spec that passes.

**Comment by filipesilva** [comment]
Support for custom blueprints was added in https://github.com/angular/angular-cli/pull/7090, available in `1.4.0-beta.1` and up. It's based on `@angular-devkit/schematics`: https://github.com/angular/devkit/tree/master/packages/schematics/angular.

We don't yet have documentation and examples of how you can make your own but @Brocco is working on it.

**Comment by leocaseiro** [comment]
I know @angular/cli just added support from blueprints. But I just found this library that works for any project. 

So we can use with NativeScript, for example: https://github.com/itslenny/scaffs

**Comment by CesarD** [comment]
@filipesilva any news on the documentation about the blueprints? Would be great to have some reference to start using them. Thanks!

**Comment by httpete** [comment]
I need to be able to customize the spec files generated to use mocha and not have expect be a global. @Brocco even a small pointer would be nice.

**Comment by CesarD** [comment]
Yup, we need at least some very basic documentation to start working with this feature.

**Comment by dnorthrupva** [comment]
Any update on documentation for this feature?

**Comment by skorunka** [comment]
Hello, any updates? Thank you.

**Comment by CesarD** [comment]
Still no updates on this? Are you guys willing to provide any documentation on this feature ever or at least refer us to another place to get it?
@hansl @filipesilva

Thanks

**Comment by leocaseiro** [comment]
@CesarD try watch some talks about `@angular/schematics`:
https://www.youtube.com/watch?v=LZxbDp1nOVo&list=PLw5h0DiJ-9PB8XH7k1bzD_UGPQ21mea0f

You can also read these articles:
https://blog.angular.io/schematics-an-introduction-dc1dfbc2a2b2
https://medium.com/@tomastrajan/%EF%B8%8F-how-to-create-your-first-custom-angular-schematics-with-ease-%EF%B8%8F-bca859f3055d

Or read the almost finished ebook https://leanpub.com/angular-schematics

**Comment by CesarD** [comment]
@leocaseiro thanks a lot!!
