### ISSUE TITLE
ng serve with faster HMR base on ESM something like esbuild、vite

### ISSUE THREAD

**Issue by sidaeren** [angular/angular-cli#23771]
# 🚀 Feature request

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Let’s continue tracking this in https://github.com/angular/angular-cli/issues/22053

Note: esbuild doesn’t support HMR. See: https://github.com/evanw/esbuild/issues/464
