### ISSUE TITLE
Node 16.17.0 not supported to angular/cli@13.3.5

### ISSUE THREAD

**Issue by vinaysomawat** [angular/angular-cli#23777]
My angular application was working fine for node version 14.15.0.

I upgrade my node version to 16.17.0 and deleted the node_modules folder and package-lock.json.

Now I'm trying to do npm install but I'm getting the below error.
![image](https://user-images.githubusercontent.com/30196269/185880585-23241379-e301-4f10-9da4-09d8d7ea1576.png)

**Comment by alan-agius4** [comment]
Do you have a direct dependency on `node-sass`, if so remove it. 

You can check by running he below command.
```
npm ls node-sass
```

**Comment by alan-agius4** [comment]
Can you please share the contents of your `package.json` please? Thanks.

**Comment by vinaysomawat** [comment]
@alan-agius4 The above issue is coming due to `node-sass` since [node-sass incompatibility with Node 16](https://github.com/sass/node-sass/issues/3077#issuecomment-834282177).

It works fine after setting the below flag

`CXXFLAGS="--std=c++14" npm install` worked for me as well on M14 Mac
