### ISSUE TITLE
Cannot install 'angular-cli@webpack'

### ISSUE THREAD

**Issue by axelerator** [angular/angular-cli#2378]
When running `--> npm install -g angular-cli@webpack`
I get the following:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/at/.nvm/versions/node/v6.3.0/bin/node" "/Users/at/.nvm/versions/node/v6.3.0/bin/npm" "install" "-g" "angular-cli@webpack"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: angular-cli@webpack
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0-beta.2-mobile.4, 1.0.0-beta.2-mobile.3, 1.0.0-beta.2-mobile.2, 1.0.0-beta.2-mobile.1, 1.0.0-beta.2-mobile, 1.0.0-beta.12-1, 1.0.0-beta.11-webpack.9-4, 1.0.0-beta.11-webpack.9-3, 1.0.0-beta.11-webpack.9-2, 1.0.0-beta.11-webpack.9-1, 1.0.0-beta.11-webpack.9, 1.0.0-beta.11-webpack.8, 1.0.0-beta.11-webpack.7, 1.0.0-beta.11-webpack.6, 1.0.0-beta.11-webpack.5, 1.0.0-beta.11-webpack.4, 1.0.0-beta.11-webpack.3, 1.0.0-beta.11-webpack.2, 1.0.0-beta.11-webpack, 1.0.0-beta.15, 1.0.0-beta.14, 1.0.0-beta.12, 1.0.0-beta.10, 1.0.0-beta.9, 1.0.0-beta.8, 1.0.0-beta.6, 1.0.0-beta.5, 1.0.0-beta.4, 1.0.0-beta.1, 1.0.0-beta.0, 0.1.0, 0.0.39, 0.0.37, 0.0.34, 0.0.33, 0.0.31, 0.0.30, 0.0.29, 0.0.28, 0.0.27, 0.0.26, 0.0.25, 0.0.24, 0.0.23, 0.0.22, 0.0.20, 0.0.19, 0.0.18, 0.0.17, 0.0.16, 0.0.15, 0.0.14, 0.0.13, 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8, 0.0.7, 0.0.6, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1, 0.0.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by thibaultsavary** [comment]
Webpack seems to be the default option right now. 

`$ npm i -g angular-cli` fetches the last webpack version of angular-cli without issues.

**Comment by filipesilva** [comment]
We've removed the `webpack` npm tag starting beta.12, now it's just `npm install angular-cli`

**Comment by axelerator** [comment]
works! thank you

**Comment by arunakshi** [comment]
I am trying to install angular-cli@webpack but I am still getting no compatible version.  No compatible version found: angular-cli@webpack

I read lot of posts referring to angular-cli@webpack, what am I doing wrong, please tell me. This is command I am using: npm install -g angular-cli@webpack

**Comment by Herbis** [comment]
@arunakshi  
if you would read the comments in this thread, you'd see that you no longer have to use 
`npm install -g angular-cli@webpack`
instead just use:
`npm install -g angular-cli`
as it's not the same as using angular-cli@webpack before.

**Comment by sireendra** [comment]
Thanks guys for you posts. But even npm install -g angular-cli is also not working fine. I am getting below error. Can anyone help me to solve this.

D:\>npm install -g angular-cli
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code E404
npm ERR! 404 no such package available : @angular-cli/ast-tools
npm ERR! 404
npm ERR! 404  '@angular-cli/ast-tools' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'angular-cli'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! Please include the following file with any support request:
npm ERR!     D:\npm-debug.log

**Comment by sudhakaran25** [comment]
Hi Guys,
 I am getting the error while installing npm install -g @angular/cli  any solution 

 But I installed npm i circular-dependency-plugin

npm ERR! notarget No matching version found for circular-dependency-plugin@^4.2.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@angular/cli'
npm ERR! notarget
