### ISSUE TITLE
Conflict with VirtualBox shared file system (vboxsf)

### ISSUE THREAD

**Issue by dtgriscom** [angular/angular-cli#2380]
> ## Please provide us with the following information:
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Vagrant virtual machine. Host system is OS X 10.10.5, guest system is Ubuntu 14.04.3.
1. Versions. Please run `ng --version`. If there's nothing outputted, please run
   in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.15
node: 6.6.0
os: linux x64
1. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? etc.
- Install Vagrant 1.8.5, VirtualBox 5.0.26 r108824, and Vagrant plugins vbguest and vagrant-host-shell.
- Create a directory on host system and copy attached Vagrantfile into directory

[Vagrantfile.zip](https://github.com/angular/angular-cli/files/502914/Vagrantfile.zip)
- "vagrant up" (which installs a variety of tools including angular-cli, and updates the VirtualBox Guest Additions), then when the provisioning is done "vagrant halt" and "vagrant up" (to get the additions running). (Output attached.)

[vagrant output.txt](https://github.com/angular/angular-cli/files/496708/vagrant.output.txt)
- "vagrant ssh" to get into the vagrant VM
- "cd /vagrant" to change to the Vagrant shared directory
- run "ng new cli-test"

Results: after about 3 minutes, the build fails, trying to access a very deeply nested file where almost none of the containing folders exist ("cli-test/node_modules/npm/node_modules/request/node_modules/http-signature/node_modules/sshpk/bin/sshpk-conv").
1. The log given by the failure. Normally this include a stack trace and some
   more information.

[npm-debug.log.zip](https://github.com/angular/angular-cli/files/496743/npm-debug.log.zip)
1. Mention any other details that might be useful.

This problem does NOT occur if running within one of the VM-native file systems (type ext4); in that case everything works fine and the project is created (although I haven't tested the project).

> ---
> 
> Thanks! We'll be in touch soon.

Happy to provide any desired details, or do whatever tests you like.

**Comment by sylar9232** [comment]
I just got the same error

**Comment by filipesilva** [comment]
Closing as outdated. If you still have problems with this usecase, let me know.
