### ISSUE TITLE
'build' makes bad output, but 'serve' works

### ISSUE THREAD

**Issue by ajackson-cpi** [angular/angular-cli#2381]
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: darwin x64  (El Capitan)

ng new something
add & use: 
   @angular2-material/checkbox
   @angular2-material/progress-circle
   angular2-highcharts

**ng serve
   Works
ng serve --prod
   Works**

ng build
   **fails**
   compiles without error, but result is not legal javascript:
   Unexpected End of Input
   Illegal Token

**Comment by bonnici** [comment]
How are you testing the built distribution? Are you running it through some sort of web server?

**Comment by JoshWilliams92** [comment]
I've had issues with the Nativescript CLI when using the current version of Node.js and not the latest stable version. Try downloading Node.js LTS v4.6.0 and see if it that works.

**Comment by ajackson-cpi** [comment]
Node 4.6.0 did not change anything. The Chrome browser continues to see those parse errors.

**Comment by filipesilva** [comment]
Can you give me a repository where I can see this happening?

**Comment by ajackson-cpi** [comment]
This was actually a case where it worked on another webserver, but these statics served on Apache-on-Vagrant broke. It was a surprising result since much larger JS assets were being served, but this configuration was truncating only angular-cli build results. It's a known Vagrant problem with SendFile
