### ISSUE TITLE
 Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js): Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Nomackleo** [angular/angular-cli#23814]
Reference to bug #23597

The same error happened to me. After trying to solve it, I noticed that it happens when I separate the modules manually. On the contrary, if I build the modules from scratch using CLI, the error does not appear.

However, it is a problem when it comes to scaling or maintaining an application.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
