### ISSUE TITLE
Build not working correctly with CompressionWebpackPlugin and property 'deleteOriginalAssets'

### ISSUE THREAD

**Issue by KristinaB162** [angular/angular-cli#23817]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 11

### Description

After updating Angular from version 11 to 14, the build no longer works correctly. The scripts tag (for runtime, polyfills and main) in the index.html are missing. 

I use the "@angular-builders/custom-webpack" with the Webpack CompressionPlugin. To not have the compressed and uncompressed files in the dist directory, the 'deleteOriginalAssets' property is set to true. If 'deleteOriginalAssets' is set to false, the build is working fine.

## 🔬 Minimal Reproduction

1. Set up a new project with angular cli (no routing, css)
`ng new repro-app`
3. Add in package.json in "devDependencies": 
```
"@angular-builders/custom-webpack":"^14.0.1",
"compression-webpack-plugin":"^10.0.0",
```
5. Add a new file in root directory called 'extra-webpack.config.js' 
6. Write this code into 'extra-webpack.config.js': 
```
const CompressionPlugin = require("compression-webpack-plugin");

module.exports = {
    plugins: [
        new CompressionPlugin({
            deleteOriginalAssets: true,
        })
    ],
};
```
7. In angular.json change the builder in build to `@angular-builders/custom-webpack:browser`
8. Add the option in build:             
```
"customWebpackConfig": {
              "path": "./extra-webpack.config.js"
            },
```
9. Run `npm i`
10. Run `npm run build`
11. In the dist directory you will see the zipped files and the index.html with missing scripts tag. (Running npm run build with deleteOriginalAssets set to false, the index.html is fine).

## 🔥 Exception or Error

The script tags in index.html are missing:
<pre><code>
<script src="runtime.dd33940cddb71537.js" type="module">
</script><script src="polyfills.240ce46083334aa2.js" type="module">
</script><script src="main.bed6caf36cdc29a3.js" type="module"></script>
</code></pre>

**Comment by alan-agius4** [comment]
Custom Webpack configurations are not support by the Angular tooling team.  Typically, gzip or Brotli compressions happen during request time by the server based on what the client browser support. 

That said, this seems to be working as intended by the author of the compression-webpack-plugin See: https://github.com/webpack-contrib/compression-webpack-plugin/issues/299
