### ISSUE TITLE
I am using target es5 but ivy is compiles as a esm5 module

### ISSUE THREAD

**Issue by smasoumi-up** [angular/angular-cli#23829]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I upgrade my project from angular8 to angular9, when I tried to deploy in production I get this compile error:
**error message: Compiling @angular/core : module as esm5**
How can I change it to disappear compile error? 

![image](https://user-images.githubusercontent.com/111997844/187560832-dc6ee410-6c95-4ea2-a159-77b2a48bd546.png)

### Please provide a link to a minimal reproduction of the bug

 tsconfig.json:

### Please provide the exception or error you saw

```true
{
  "compileOnSave": false,
  "compilerOptions": {
    "downlevelIteration": true,
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    // "noUnusedLocals": true,
    // "noUnusedParameters": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ],
    "module": "esnext"
  },
  "angularCompilerOptions": {
    "enableIvy": true,
    "preserveWhitespaces": false
  }
}
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.15
Node: 14.17.3
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.15
@angular-devkit/build-angular      0.901.15
@angular-devkit/build-optimizer    0.901.15
@angular-devkit/build-webpack      0.901.15
@angular-devkit/core               9.1.15
@angular-devkit/schematics         9.1.15
@angular/cdk                       9.2.4
@angular/cli                       9.1.15
@angular/flex-layout               9.0.0-beta.31
@angular/material                  9.2.4
@angular/material-moment-adapter   9.2.4
@ngtools/webpack                   9.1.15
@schematics/angular                9.1.15
@schematics/update                 0.901.15
rxjs                               6.6.7
typescript                         3.8.3
webpack                            4.42.0
```

### Anything else?
First I get this error **'Entry point '@ngx-translate/core' contains deep imports into'** So I do these steps:
1- Upgrade @ngx-translate/core to version 12.1.2
![image](https://user-images.githubusercontent.com/111997844/187562046-d6f9476a-9a50-4f73-a756-c6840d73144e.png)

2- then add ngcc file in the root project like this:
module.exports = {
  ignorableDeepImportMatchers: [/ol\//],
};
3- change package.json like this:
![image](https://user-images.githubusercontent.com/111997844/187562255-35aa0e5d-1638-4153-8fe0-fed22679240f.png)

finally the error for entry points gone but the this error appear:
**error message: Compiling @angular/core : module as esm5**

**Comment by JoostK** [comment]
Hi @smasoumi-up,

the message "Compiling @angular/core : module as esm5" is not an error, it's just that it's written [to _standard error_ because it's progress information](https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout).

If your deployment is failing because of this message then they're incorrectly treating stderr output as a failure; the deployment should be looking at the exit code instead.

Please note that Angular 9 is no longer supported; v12 is the earliest LTS at the moment.

**Comment by smasoumi-up** [comment]
Hi @JoostK ,
Thank you for your response. we did this changes on the Package.json and failing build is gone.

![image](https://user-images.githubusercontent.com/111997844/188010195-3e585d94-b2a6-4ab1-ba33-5de9822cba1e.png)
