### ISSUE TITLE
Angular proxy doesn't work on browser.

### ISSUE THREAD

**Issue by alchemist0404** [angular/angular-cli#23826]
Hi, I have a problem with Angular proxy configuration. Now I am using Angular 11.x

Here is my proxy configuration and ng cli command.

```
{
    "/service/*": {
      "target": "http://192.168.114.49:8080",
      "secure": false,
      "logLevel": "debug",
      "changeOrigin": true
    }
}
```

`ng serve --proxy-config proxy.conf.json --port 8000`

![image](https://user-images.githubusercontent.com/67555770/187439437-3a66cd99-ea64-45ff-92a9-c75683719200.png)

As you can see on this screenshot, on the cmd, it shows that the proxy is working correctly but on the browser the request is going to wrong host.

What's wrong?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Moreover Angular 11 is no longer supported.  Kindly see our [LTS policy](https://angular.io/guide/releases#support-policy-and-schedule).
