### ISSUE TITLE
ChunkLoadError After Upgrading to Angular Version 13.3.9

### ISSUE THREAD

**Issue by jatinkumar159** [angular/angular-cli#23834]
# 🐞 Bug report

### Is this a regression?

 Yes

### Description

After updating to Angular 13.3.9 from Angular 11, ChunkLoadError occurs when loading some modules.
Error comes in node_modules_stompjs_index_js  and custom module.

## 🔬 Minimal Reproduction
No

## 🔥 Please provide the exception or error you saw
Error: Uncaught (in promise): ChunkLoadError: Loading chunk node_modules_stompjs_index_js failed.
(error: http://localhost:4500/ng/node_modules_stompjs_index_js.js)
ChunkLoadError: Loading chunk node_modules_stompjs_index_js failed.

## 🌍 Your Environment

<pre>Angular CLI: 13.3.9
Node: 16.13.1
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.3
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
rxjs                            6.6.7
typescript                      4.6.4<code>

</code></pre>

**Anything else relevant?**
I am using Macbook Pro M1 chip

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by jatinkumar159** [comment]
Hi @alan-agius4 ,

Setting-up a minimal repo won't be possible. If required I can share with you the package.json and package-lock.json file with you.

**Comment by alan-agius4** [comment]
I am afraid that without a minimal reproduction we cannot action this issue. The package.json and package-lock.json alone will not be enough to reproduce the problem.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
