### ISSUE TITLE
NPM install @angular/cli@12 keeps installing @angular-devkit/build-angular 14.2.1

### ISSUE THREAD

**Issue by tekinet** [angular/angular-cli#23845]
### Command

version

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

I've been trying to upgrade an app from Angular 11 to Angular 12.  I get the following error:
This version of CLI is only compatible with Angular version 14.0.0, but Angular version 12.2.16 was found instead.

I uninstalled angular/CLI.  I cleaned the cache. Then, I installed @angular/cli@12

I keep getting @angular/-devkit/build-angular 14.2.1

I have tried to downgrade it to 12. I have done these steps multiple times. Please advise.

### Minimal Reproduction

Please see above steps explained.

### Your Environment

```text
Angular/cli 12.2.18
Angular-devkit/build-angular 14.2.1   <-- version issue.
angular/material 11.2.13    This is version 11 because it's having issues with version 12.
```

**Comment by alan-agius4** [comment]
Are you following to steps in https://update.angular.io/?v=11.0-12.0 to update?

**Comment by tekinet** [comment]
I just resolved the issue. I created a new branch so I can do a fresh install. I'm good to go. Thanks for your help.
