### ISSUE TITLE
ng g component <ComponentName> Failed with error "Project "undefined" does not exist."

### ISSUE THREAD

**Issue by laggage** [angular/angular-cli#23848]
### Command

generate

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

After updated to angular14, the `defaultProject`property in angular.json was removed after run `ng update`, however, when i 
try to create an component with `ng g component` command, it failed with "Project "undefined" does not exist." error, if i add  `defaultProject` back to angular.json, the command will success, but a warning appeared in the console output "DEPRECATED: The 'defaultProject' workspace option has been deprecated. The project to use will be determined from the current working directory."

### Minimal Reproduction

- run `ng g component <componentName>`

### Your Environment

```text
✗ npm run ng -- version

> blog-admin@0.0.0 ng
> ng version


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.1
Node: 16.13.1
Package Manager: npm 8.19.0 
OS: darwin x64

Angular: 14.2.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker
```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment]
The root problem here is that a project cannot be determined. You can either change the current working directory using (cd) or provide the name of the project using the `--project` option. 

We should update the error message to be more actionable.

**Comment by laggage** [comment]
@alan-agius4 

This error occurs even when i executed `ng g component` in the root directory of the project. I have no idea how the cli determine the current project, but i don't think is only things about the error message

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/38829279/188099751-ff47e887-c6aa-4595-ac7d-5cdd24edb855.png">

**Comment by alan-agius4** [comment]
Can you please share you `angular.json`? You can option the `architect` sections if you'd like.

**Comment by laggage** [comment]
@alan-agius4  You can see my angular.json below
<details open>
<summary>angular.json</summary>

```json
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "newProjectRoot": "projects",
    "projects": {
        "blog-admin": {
            "projectType": "application",
            "root": "",
            "sourceRoot": "src",
            "architect": {...},
    },
        "blog-admin-e2e": {
            "root": "",
            "sourceRoot": "",
            "projectType": "application",
            "architect": {
                "e2e": {
                    "builder": "@angular-devkit/build-angular:protractor",
                    "options": {
                        "protractorConfig": "./protractor.conf.js",
                        "devServerTarget": "blog-admin:serve"
                    },
                    "configurations": {
                        "ci": {
                            "protractorConfig": "./protractor.ci.conf.js"
                        }
                    }
                },
                "lint": {
                    "builder": "@angular-eslint/builder:lint",
                    "options": {
                        "lintFilePatterns": ["e2e/**/*.ts"]
                    }
                }
            }
        }
    },
    "schematics": {
        "@schematics/angular:component": {
            "prefix": "cnb",
            "style": "less"
        },
        "@schematics/angular:directive": {
            "prefix": "cnb"
        }
    }
}

```
</details>

**Comment by alan-agius4** [comment]
The problem here is that your projects are misconfigured in the `angular.json`. You have two projects in the same directory as the `root` is configured the same, as such the CLI cannot determine which project you intend to use. 

```json
     "blog-admin": {
            "projectType": "application",
            "root": "",
            "sourceRoot": "src",
    },
    "blog-admin-e2e": {
         "root": "",
         "sourceRoot": "",
```

**Comment by laggage** [comment]
After I changed `blog-admin-e2e.root` to `e2e`, things worked, thanks for help
