### ISSUE TITLE
upgrate the CLI issue

### ISSUE THREAD

**Issue by zhuyongzhen** [angular/angular-cli#2385]
Execute the command : ng build, then there is an hint below, but when I follow the link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12
it got many errors,  is there a good way to upgrate the CLI? Or if I choose not to upgrate the CLI, my
projects still can work.

It seems like you're using a project generated using an old version of the Angul
ar CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a si
mpler
workflow, a faster build and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this
 link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12

**Comment by filipesilva** [comment]
You can choose to not upgrade the CLI, but then you need to always use `beta.10` globally as well as locally.

What kind of errors are you getting while upgrading?

**Comment by filipesilva** [comment]
Closed as inactive.
