### ISSUE TITLE
@angular-devkit/schematics and @angular-devkit/core not getting updated to v14

### ISSUE THREAD

**Issue by maidmehic** [angular/angular-cli#23867]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Trying to update the app from v13 to v14. After running the `ng update @angular/core@14 @angular/cli@14`, everything gets updated just as expected except: `@angular-devkit/schematics` and `@angular-devkit/core`.

This is what's displayed with `ng version`:

> Angular CLI: 14.2.1
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

>Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... google-maps, language-service, platform-browser
... platform-browser-dynamic, router

>Package                         Version
>---------------------------------------------------------
>@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
**@angular-devkit/core**            **13.2.5**
**@angular-devkit/schematics**      **13.2.5**
@angular/cli                    14.2.1
@schematics/angular             14.2.1
rxjs                            7.5.4
typescript                      4.7.4

`@angular-devkit/schematics` and `@angular-devkit/core` are not part of the `package.json` though.

### Minimal Reproduction

Updated Angular 13 to Angular 14 via `ng update @angular/core@14 @angular/cli@14`

### Your Environment

```text
Angular CLI: 14.2.1
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 14.2.0
... animations, common, compiler, compiler-cli, core, forms
... google-maps, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.1
@angular-devkit/build-angular   14.2.1
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    14.2.1
@schematics/angular             14.2.1
rxjs                            7.5.4
typescript                      4.7.4
```

**Comment by alan-agius4** [comment]
Can you please provide the output of the below commands;
```
npm ls @angular-devkit/schematics
npm ls @angular-devkit/core
```

**Comment by maidmehic** [comment]
Thank you very much for the response!

`npm ls @angular-devkit/schematics` 

![Screenshot 2022-09-07 at 13 55 37](https://user-images.githubusercontent.com/45770647/188872514-b4092b73-ae80-4731-b3e5-b624a7e408d5.png)
  
`npm ls @angular-devkit/core`

![Screenshot 2022-09-07 at 13 56 37](https://user-images.githubusercontent.com/45770647/188872641-47579d64-4d96-4532-b341-55f8c74506c7.png)

**Comment by alan-agius4** [comment]
It looks like those dependencies versions are being installed transitive via `@storebook/` and `@compodoc/`. Nothing to worry about here.
