### ISSUE TITLE
VMWARE Horizon Users (Non-admin) unable to run Angular CLI

### ISSUE THREAD

**Issue by saasdevops** [angular/angular-cli#23860]
### Command

add

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Users who are not administrators cannot run the CLI Angular post installation. This issue is happening on virtual machines only. 

### Minimal Reproduction

Installed the CLI Angular on a master image for application publishing via Vmware Horizon but users are unable to run the CLI post-install. 
[](url)
[](url)
![Screenshot 2022-09-05 133929](https://user-images.githubusercontent.com/96929523/188510529-7ae78f82-573a-4e8d-9da4-148f0b520cbf.png)

### Your Environment

```text
VMWare Horizon
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
