### ISSUE TITLE
Broken build for lazy loaded feature-modules after using template strings expressions anywhere in component code

### ISSUE THREAD

**Issue by TamaraGalaktionova** [angular/angular-cli#23864]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When code contains template strings all calls of import function are ignored, when resolving peer dependencies for apps & libs. Build throws error - "Unable to write a reference to XXX", where XXX - any other import in lazy loaded feature.

### Minimal Reproduction

Angular 12 + Nx-monorepo

Need to lazy load some feature module in one of component's method.
As usual, wrote method for loading & rendering:

```
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  Component,
  Injector,
  ViewChild,
  ViewContainerRef,
  ɵcreateInjector as createInjector
} from '@angular/core'

@Component({
  selector: 'my-component,
  templateUrl: './my-component.component.html',
  styleUrls: ['./my-component.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MyComponent implements AfterViewInit {
  @ViewChild('container', { read: ViewContainerRef }) container: ViewContainerRef | undefined

  constructor(private injector: Injector) {}

 // code for implementing some business logic

  ngAfterViewInit(): void {
     if (this.container) {
      this.container.clear()
      this.renderLazyWidget()
    }
  }

  public someMethodWithTemplateString(item: string): string {
     return `${item}_123` // not important - any expression with template string
  }

  private renderLazyWidget(): void {
    import('@my_feature_module_via_alias').then(m => {
      const injector = createInjector(m.MyFeatureModule, this.injector)
      const module = injector.get(m.MyFeatureModule)
      // rendering logic of some widget in container - not important
    })
  }
}
```

nx run my-feature:build throws error

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/81412965/188660841-90a21fca-bf32-4e11-a5e5-0060673053f8.png">

where OuterClickDirective - any first import in lazy loaded feature or its nested dependencies

If I change the order of methods in my component code or remove template string expression, everything is working as expected.

Looks like broken file content parsing with backticks & template strings.

If I should address this issue to Nx-team, please inform me in comments 🙏 

### Exception or Error

Throws error:

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/81412965/188660841-90a21fca-bf32-4e11-a5e5-0060673053f8.png">

But the problem is that all necessary dependencies for lazy loaded module are not building at all, cause import function is "invisible" after broken file content parsing with template strings.

### Your Environment

```text
"devDependencies": {
    "@angular-architects/ddd": "^1.4.0",
    "@angular-builders/custom-webpack": "^12.1.2",
    "@angular-devkit/build-angular": "12.2.7",
    "@angular-devkit/build-webpack": "0.1202.7",
    "@angular-eslint/eslint-plugin": "^14.0.0",
    "@angular-eslint/eslint-plugin-template": "^14.0.0",
    "@angular-eslint/template-parser": "^14.0.0",
    "@angular/cli": "12.2.7",
    "@angular/compiler-cli": "12.2.7",
    "@angular/language-service": "12.2.7",

    "@nrwl/angular": "13.1.6",
    "@nrwl/cli": "13.1.6",
    "@nrwl/devkit": "13.1.6",
    "@nrwl/eslint-plugin-nx": "14.4.2",
    "@nrwl/jest": "13.1.6",
    "@nrwl/linter": "13.1.6",
    "@nrwl/workspace": "13.1.6",
    
    "typescript": "4.3.5"
  }
```

**Comment by JoostK** [comment]
I am afraid this would require a runnable reproduction for us to investigate. It might also help if you update to latest Angular; at least that particular compiler error has been improved to provide more details as to why import generation fails.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
