### ISSUE TITLE
Circular dependency issues are ignored

### ISSUE THREAD

**Issue by g-cheishvili** [angular/angular-cli#23894]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi, In our library we hoped that the compiler would warn us about circular dependencies, but it does not complain at all. Currently, we use angular 14 with NX + nx executors, but angular builders do not say anything at all too.

### Minimal Reproduction

https://github.com/SAP/fundamental-ngx/issues/8664

### Your Environment

```text
"@angular/cli": "~14.0.0",
    "@angular/compiler-cli": "14.0.2",
    "@angular/language-service": "14.0.2",
    "@angular/animations": "14.0.2",
    "@angular/cdk": "14.0.2",
    "@angular/common": "14.0.2",
    "@angular/compiler": "14.0.2",
    "@angular/core": "14.0.2",
    "@angular/forms": "14.0.2",
    "@angular/platform-browser": "14.0.2",
    "@angular/platform-browser-dynamic": "14.0.2",
    "@angular/router": "14.0.2",
    "@angular-builders/custom-webpack": "14.0.0",
    "@angular-devkit/build-angular": "14.0.2",
    "@angular-devkit/core": "14.0.2",
    "@angular-devkit/schematics": "14.0.2",
I had to copy from package.json
```

**Comment by JoostK** [comment]
This is listed as breaking change in the release notes of v14.0.0:

> The deprecated showCircularDependencies browser and server builder option has been removed. The recommended method to detect circular dependencies in project code is to use either a lint rule or other external tools.

It was removed as this check came with an enormous performance penalty, even in incremental rebuilds, and checking for circular dependencies is more suited for a linter tool than a build step (cycles in ES modules are allowed, after all).
