### ISSUE TITLE
Add new flag `--sfc` to create standalone, inline template and inline style components

### ISSUE THREAD

**Issue by pavankjadda** [angular/angular-cli#23901]
### Command

generate

### Description

After Standalone components rolled out in v14, many of the angular devs started using single file standalone components as default. They just look cleaner, less number of files and forces us to create simple components i.e. don't put too much in single file, hence increases the re-usability and readability

At present we use
```
ng generate component COMPONENT_NAME --standalone --inline-style --inline-template
```
this can be simplified to 
```
ng generate component COMPONENT_NAME --sfc
```

### Describe the solution you'd like

add a new flag called `--sfc` to CLI that creates standalone, inline template and inline style component

### Describe alternatives you've considered

At present we supply 3 flags to achieve this behaviour
```
ng generate component COMPONENT_NAME --standalone --inline-style --inline-template
```

**Comment by alan-agius4** [comment]
Actually @dgp1130, mentioned to combine `--inline-style` and `--inline-template` into a single option as it's likely that these are used together.

**Comment by pavankjadda** [comment]
> Actually @dgp1130, mentioned to combine `--inline-style` and `--inline-template` into a single option as it's likely that these are used together. 

Any plans to include standalone into that?

**Comment by dgp1130** [comment]
Yes, we did recently chat about merging these two options. I think @alxhub wanted a different name than `--sfc`, but I forget what his preference was.

We'd probably start out without standalone (though we'd probably support `--sfc --standalone`). If we ever decide to do standalone by default, then that would probably also apply to `--sfc` in the same way.
