### ISSUE TITLE
fileReplacements support for browser-esbuild

### ISSUE THREAD

**Issue by Jefftopia** [angular/angular-cli#23915]
### Command

build

### Description

The improved build times for experimental browser-esbuild are really promising, but absence of fileReplacements is a true blocker for workplaces with multiple environments, any enterprise at minimum. 

I took an initial look into this within the angular-cli project but didn't get far. It looks like esbuild's hooks are only available _after_ the angular-typescript program has been generated.

I am curious to know what other options there are and whether this is something the angular team is looking into. 

### Describe the solution you'd like

fileReplacements support for browser-esbuild

### Describe alternatives you've considered

Unclear whether esbuild can support this out of the box, perhaps support has to come from the compiler itself.

**Comment by clydin** [comment]
https://github.com/angular/angular-cli/pull/23924 should provide support for the option and will be released in v15.
