### ISSUE TITLE
Angular 11_ Dist folder includes duplicate module files

### ISSUE THREAD

**Issue by RtzS** [angular/angular-cli#23945]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am working on angular 11 project, where I have observed on **ng build** in dist folder duplicate chunks are generated. Please find more details below:

![image](https://user-images.githubusercontent.com/8089250/191742006-18c7cab8-1de2-4d30-98be-6930f9ed17be.png)

In above screen shot on highlighted dist folder's area indicates duplicate files for same module type. With 'default/~' annotation. I am not getting why these files are getting generated and those are getting added on site's module tree map which is impacting performance of my project.

![image](https://user-images.githubusercontent.com/8089250/191742713-411a6bf6-33d3-4d56-a482-31f14674b7ca.png)

Can any one help me to avoid these duplicate modules issue?

Thankyou in Advance..!

### Minimal Reproduction

Using below command to generate dist folder:

ng build  --aot true --build-optimizer true --common-chunk true --cross-origin none --delete-output-path true --extract-css false --extract-licenses false --fork-type-checker true --named-chunks true --output-hashing none --preserve-symlinks false --prod true --service-worker true --source-map false --stats-json false --subresource-integrity false --vendor-chunk true

![image](https://user-images.githubusercontent.com/8089250/191745188-8c93e716-6ff1-4c97-a851-2e0d309b7324.png)

### Your Environment

```text
Angular CLI: 11.2.14
Node: 12.22.12
OS: win32 x64

Angular: 11.0.2
animations, common, compiler, compiler-cli, core, forms
language-service, platform-browser, platform-browser-dynamic
router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1100.7
@angular-devkit/build-angular      0.1100.7
@angular-devkit/core               11.0.7
@angular-devkit/schematics         11.2.14
@angular/cdk                       11.2.13
@angular/cli                       11.2.14
@angular/localize                  11.2.14
@angular/material                  11.2.13
@angular/material-moment-adapter   11.2.13
@schematics/angular                11.2.14
@schematics/update                 0.1102.14
rxjs                               6.6.7
typescript                         4.0.5
```

**Comment by alan-agius4** [comment]
This is working as intended due to differential loading. 

Please be aware that Angular 11 is no longer supported. For more information about or support policy please see https://angular.io/guide/releases#support-policy-and-schedule.
