### ISSUE TITLE
Tailwind PostCSS Config not working

### ISSUE THREAD

**Issue by matdv** [angular/angular-cli#23944]
### Command

serve

### Description

I'm using tailwind and want to configure PostCSS to use custom plugins, such as nesting.
There is a configuration file (postcss.config.js) to specify this, but it is getting ignored and I found similar issues like #8427
I did not find a simple solution for this.

`postcss.config.js:`
```
module.exports = {
  plugins: {
    'postcss-import': {},
    'tailwindcss/nesting': {},
    'postcss-short': {},
    tailwindcss: {}
  },
}
```
When serving, i get the following warning and nesting does not work:
![image](https://user-images.githubusercontent.com/24583997/191701838-a47e08b4-2a88-475e-8a99-5277b4b76a69.png)

https://tailwindcss.com/docs/using-with-preprocessors#nesting confirms how the config should be used.

Can you please address this issue?

### Describe the solution you'd like

I'd like to load the postcss configuration file.
I can think of a flag or filename for the postcss config in another configuration file like the angular.json.
Also the default filename postcss.config.js could be loaded by default.

### Describe alternatives you've considered

I found that postcssOptions.config is set to false and hence the config file is not read.
A workaround can be done using @angular-builders/custom-webpack

`custom-webpack.config.js:`
```
module.exports = (config, options) => {  
  config.module.rules.find(x => x.test.toString().indexOf(':css') > -1).rules[0].oneOf.forEach(x => {
    x.use.filter(y => y.loader.indexOf('postcss') > -1).forEach(postCssEl => {  
      postCssEl.options.postcssOptions.config = true;
    });
  });
  return config;
};
```

**Comment by dgp1130** [comment]
We support Sass as well as Tailwind and they should be able to work together. I think if you just rename from `*.css` to `*.scss` that should support nesting. Does that address this use case or is there a reason we need to use Tailwind's implementation?

**Comment by matdv** [comment]
Thanks, I think Sass will suffice. I didn't want to add another dependency, but that's not an issue since Sass is already included.
PostCSS config might be only relevant again when using other custom plugins.

**Comment by alan-agius4** [comment]
Closing as per above.
