### ISSUE TITLE
compiler cannot build a simple with html or sass 

### ISSUE THREAD

**Issue by kenatwex** [angular/angular-cli#23948]
### Command

can someone talk to this please and offer some docs or standards? Also how this effects lazyloading in MFE's...thanks

standard angular use to be like this for scss code

`	background-image:  url("assets/images/login/background.png");`

now its unknown

`/Users/w509297/me/my/src/app/pages/login/login.component.scss:25:1: Can't resolve './assets/images/login/background.png' in '/Users/me/my/src/app/pages/login'`

what is putting the dot slash at the front? baseHref in tsconfig? I cant seem to change that for anything different.

BUT why does my webstorm IDE approve of and can navigate to it fine? Anything else dont navigate. My IDE KNOWS if the runtime for the cod is legit and this is hoakey

the only thing compiles is this

`	background-image:  url("/assets/images/login/background.png");`

and I dont want that I want to know whats messing up the root path to assets so I can have something predictable here for all my code

strange thing is if I put slash in front of the root of the path... IDE shows red error but cli compiles it fine
and Im confused about impact to all our code

### Is this a regression?

- [ X] Yes, this behavior used to work in the previous version

### Description

SUBJECT: compiler cannot build a simple with html or sass 

angular is broken it cannot compile. This is simple to reproduce with your own quick project generation

**tsconfig**
```
		"baseUrl": ".",
		"baseUrl": "./",
		"baseUrl": "",
```

tried all three nothing works

**login.scss**

```
	//background-image:  url("~/@mycorp/shared-root-ui-assets/assets/images/login/background.png");
	//background-image:  url("@mycorp/shared-root-ui-assets/assets/images/login/background.png");
	//background-image:  url("node_modules/@mycorp/shared-root-ui-assets/assets/images/login/background.png");
	//background-image:  url("assets/images/login/background.png");
	background-image:  url("/assets/images/login/background.png");
	//background-image:  url("./assets/images/login/background.png");
```

tried all 6 and only one compiles (the uncommented line)

**login.html**

functions do not work when they return the path to the asset
```
<img [src]="background()" />
<img [src]="logo()" />
```

```
<img src="assets/images/login/background.png" />
<img src="assets/images/logo.png"/>
<img src="./assets/images/login/background.png" />
<img src="./assets/images/logo.png"/>
<img src="/assets/images/login/background.png" />
<img src="/assets/images/logo.png"/>
```

```
	<img src={{image}} />
	<img src={{logo}}/>
```

The internet is littered with issues on this and theres no comprehensive documentation on how or why this is suppose to be coded.

Can someone help here?

Cannot compile sass url's pointing to assets
Cannot compile html templates with <img> and [src] pointing to assets
cannot display anything

The path the compiler is pivoting off of is either "." or the entire path of the working directory

regardless nothing works

### Minimal Reproduction

why is this not implemented

### Exception or Error

```text
An unhandled exception occurred: The ./dist/assets asset path must start with the project source root.
See "/private/var/folders/9f/4_c945294tncdc7vdd30b3bc0000gq/T/ng-pGC00X/angular-errors.log" for further details

/Users/me/my/src/app/pages/login/login.component.scss:26:1: Can't resolve './assets/images/login/background.png' in '/Users/me/my/src/app/pages/login'
```

### Your Environment

```text
nx report   

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.0
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.7.5
   @nrwl/angular : 14.7.5
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : 14.7.5
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @fortawesome/angular-fontawesome: 0.10.2
   	 @ngrx/component-store: 14.2.0
   	 @ngrx/effects: 14.2.0
   	 @ngrx/entity: 14.2.0
   	 @ngrx/router-store: 14.2.0
   	 @ngrx/store: 14.2.0
   	 apollo-angular: 4.0.1
   	 @buildmotion/angular: 13.0.1
   	 @ngrx/schematics: 14.2.0
   	 @ngrx/store-devtools: 14.2.0
   	 @storybook/angular: 6.5.12
```

### Anything else relevant?

one would think after all the years of angular releases since 2,4,5,6,7,8,9,10,11,12,13,14

that this would be implemented to some degree for transpilation to succeed

this is fundamental to all web pages for angular

it should be able to compile sass url'd assets
it should be able to compile templates assets

--base-href during build had no effect for development configuration

**Comment by alan-agius4** [comment]
Hi @kenatwex,

IMHO, the error is quite clear in the specific case. `assets/images/login/background.png` cannot be resolved relative to `/Users/w509297/me/my/src/app/pages/login/login.component.scss` during build time. As `/Users/w509297/me/my/src/app/pages/login/assets/images/login/background.png` does not exist. 

Call outs
- `./assets/images/login/background.png` is exactly the same as `assets/images/login/background.png` and are both relative paths, but not `/assets/images/login/background.png` is not, as it's absolute. (Will explain a bit more further down).
- The tsconfig `baseUrl` doesn't effect anyway the processing of CSS resources.

Unlike assets in templates, **relative resources in CSS such as images and fonts are "always" resolved relative to the file location** and are automatically written and fingerprinted at the root of the output (dist) folder. This means that these don't need to be added to the `assets` option in `angular.json`. 

This is briefly mentioned in https://angular.io/cli/build

If you don't want this behaviour and you want to bypass CSS resource processing and point to an asset that was copied using the "asset" option you have 2 ways.
1. Use absolute paths `/assets/images/login/background.png` which has the downside of causing the base-href to be ignored. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base for more information to why this happens. 
2. Prefix the uri of the resource with `^`, example `^assets/images/login/background.png`. This would cause bypassing css asset processing and during the build the caret will be removed.

**Comment by kenatwex** [comment]
Thank you friend

what would be the best path for soon to be coded i18n transloco dynamic
httploader url switching of language assets

Thank You

**Comment by alan-agius4** [comment]
If you will have different base-href for each locale, I'll definitely won't go with the absolute patch approach. In general, relative paths are the better option.
