### ISSUE TITLE
Node 4 vs Node 6

### ISSUE THREAD

**Issue by dagilleland** [angular/angular-cli#2395]
**Question** on the prerequisite of Node 4:

Since Angular's examples states

> Our examples require node **v5.x.x** or higher and npm 3.x.x or higher.

and the CLI states

> The generated project has dependencies that require **Node 4.x.x** and NPM 3.x.x.

does that mean there is a fundamental "inconsistency" between the CLI and Angular 2 proper? Anybody new who reads the docs on Angular.io would reasonably install Node 6 (the two Windows downloads, for example, are Node 4.6.0 or 6.7.0).
![image](https://cloud.githubusercontent.com/assets/2947017/18920718/7aa7ba7e-855f-11e6-91dc-c4b6e85815ce.png)

**Comment by hacknaked** [comment]
This issue was already reported, see discussion on #1046

**Comment by paihz** [comment]
Thanks for bring up this issue. I try to google search, maybe i use wrong keyword

**Comment by dagilleland** [comment]
Although already reported in #1046, it is not addressed as the ReadMe on the cli still contains an inconsistency.
