### ISSUE TITLE
Add `--standalone` option to `ng new`

### ISSUE THREAD

**Issue by Lonli-Lokli** [angular/angular-cli#23976]
### Command

new

### Description

Right now `ng new`  do not use standalone application bootstrap, but usual app instead. 
Nw option should change application to the standalone option, without AppModule

**Comment by Lonli-Lokli** [comment]
@alan-agius4 can you vote for this as well? :)

**Comment by mounilKshah** [comment]
If no one else is working on this issue, can I work on it?

**Comment by alan-agius4** [comment]
@mounilKshah, thanks for offering to take this up. The new project structure is still in its design phase.

**Comment by LMFinney** [comment]
Any update on where this is on the roadmap?

**Comment by arturober** [comment]
When creating an app with this option. Will the CLI generate standalone components/directives in the project by default? (not needing --standalone flag). What about generating functional guards/interceptors/resolvers by default?

Like @LMFinney said. Is there any information regarding when / how will this be implemented? . I've been using (and teaching) these lasts 2 months Angular 15 with standalone components and functional guards/interceptors/resolvers, and I find it simpler and cleaner. Sadly there are many libraries (including Universal) that still doesn't support apps without AppModule (using bootstrapApplication) and fail when executing ng add.

**Comment by zjkipping** [comment]
@mounilKshah @alan-agius4 Any updates on this? Seems like a pretty major thing to not include with the CLI now that the standalone api has shipped in v15. This is a pretty major setback for myself and the others at my company when it comes to teaching any curriculum related to Angular with the standalone api.

Unfortunately at this point, I will probably have to end up going with some version of a Nx workspace (or the `angular-standalone` preset Nx has). Nx has had this functionality for a while with their generators and this doesn't seem to have much priority for the Angular CLI.

**Comment by Flo0806** [comment]
I think the CLI need to have the `--standalone` flag, too. Please integrate it!

**Comment by Flo0806** [comment]
You guys are the best! 🎊 Thx!
