### ISSUE TITLE
Question about bundle

### ISSUE THREAD

**Issue by upta** [angular/angular-cli#2397]
Please forgive my ignorance, but I'm working to wrap my head around the Angular 2 ecosystem and to figure out if/how I can make it play with how our systems are setup here at my work.

It would definitely be nice to use "the official" tool instead of growing one myself.  One of the issues I currently see (and I may just be ignorant ;) is that our site is built out of many separate projects (in different IIS sub-applications), but they all load library scripts and such from a single shared location.

It seems that the CLI bundles all the angular code along with it when it builds.  Is there any way to make it not include Angular 2 itself and simply have that "pre-loaded" by the shared script?

Thanks for any insight!

**Comment by JanStureNielsen** [comment]
@upta -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

**Comment by filipesilva** [comment]
Heya @upta! We don't have a way to separate bundles the way you're describing, no. 

It's something that we've talked about, setting some dependencies to be loaded from a CDN or similar, but it's fallen out of relevance compared to other features. 

Our main approach at the moment is to make an app as small as possible via Ahead-of-Time compilation, tree-shaking and other production bundle techniques. This inherently means that the bundle for this app will contain as little as possible, but it cannot factor in what other common bits it has with other apps that are not part of the build process.

Hope this answered your question, cheers!

**Comment by upta** [comment]
Appreciate the response even though it's not really the answer I was hoping for.  Seems that we're basically going to have to completely up-end the way we do things to fit with the way the world is moving, or write our own solution.  Not exactly excited about either option so Angular 2 might go simmer on my back burner again for a while ;)

Appreciate the information!
