### ISSUE TITLE
Support Powershell Register-ArgumentCompleter

### ISSUE THREAD

**Issue by dirthsj** [angular/angular-cli#23975]
### Command

help

### Description

**Note: I was not able to select [completion](https://angular.io/cli/completion) in the dropdown for command, so I have selected `help` instead.**

Please support autocompletion in PowerShell via [Register-ArgumentCompleter](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter)

### Describe the solution you'd like

ng completion works on Powershell

### Describe alternatives you've considered

N/A

**Comment by alan-agius4** [comment]
Blocked on https://github.com/yargs/yargs/issues/1290

**Comment by alan-agius4** [comment]
Closing as this is not actionable by us until it's addressed upstream.
