### ISSUE TITLE
Unable to properly parse url(fonts) in css from 3rd party node_module

### ISSUE THREAD

**Issue by BppleMan** [angular/angular-cli#23984]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

no earlier version

### Description

I have an esm type library that I implemented as a minimal reproduction project at: https://github.com/BppleMan/esm-lib.git.
When I introduced the esm module in angular, I got error： unresolved token in css.
So I wrote a minimal webpack.config and used `@angular-builders/custom-webpack` with `webpack-merge` it into ng cli's own webpack config.
```
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const fs = require("fs");
const {lstatSync, readlinkSync} = fs;
const path = require("path");
const {resolve} = path;

let esmLibPath = resolve("node_modules", "esm-lib");
const stat = lstatSync(esmLibPath);
if (stat.isSymbolicLink()) {
    esmLibPath = resolve("node_modules", readlinkSync(esmLibPath));
}

console.log("monacoPath", esmLibPath);

module.exports = {
    mode: "development",
    output: {
        clean: true,
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                include: esmLibPath,
                use: [
                    MiniCssExtractPlugin.loader,
                    "css-loader"
                ]
            },
            {
                test: /\.ttf$/,
                include: esmLibPath,
                use: [
                    "file-loader"
                ]
            }
        ]
    },
    plugins: [
        new MiniCssExtractPlugin()
    ]
}

```

Above I get ng build/serve right, but when I look at the `dist` dir, I see that the `main.css` compiled by ng build resolves the font url to an absolute path, like:
```
@font-face {
	font-family: "codicon";
	font-display: block;
	src: url(file:///Users/bppleman/angular-demo/node_modules/.pnpm/github.com+BppleMan+esm-lib@41c013849040319f564dac_dhi5c3lxlelecow2p7n3vaxycy/node_modules/esm-lib/codicon.ttf) format("truetype");
}
```
The real problem this causes is when I run `ng serve`, I got error in the browser: Access to local files is not allowed: file:///Users/bppleman/angular-demo/node_modules/.pnpm/github.com+BppleMan+esm-lib@41c013849040319f564dac_dhi5c3lxlelecow2p7n3vaxycy/node_modules/esm-lib/codicon.ttf

I want to know how ng cli handles something like `src: url(xxxx.ttf)` when parsing .css$

### Minimal Reproduction

https://github.com/BppleMan/angular-ivy-srhfxs.git

### Your Environment

```text
Angular CLI: 14.2.4
Node: 16.16.0
Package Manager: npm 8.11.0 
OS: darwin arm64

Angular: 14.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.4 (cli-only)
@angular-devkit/build-angular   14.2.4
@angular-devkit/core            14.2.4 (cli-only)
@angular-devkit/schematics      14.2.4 (cli-only)
@schematics/angular             14.2.4 (cli-only)
rxjs                            7.5.7
typescript                      4.7.4
webpack                         5.74.0
```

**Comment by alan-agius4** [comment]
Hi @BppleMan, 

Thanks for opening the issue. Please be aware that custom Webpack configuration are not supported by the Angular team.
