### ISSUE TITLE
[Bug Report] [esm] [css] Can't load css files in 3rd party esm module correctly

### ISSUE THREAD

**Issue by BppleMan** [angular/angular-cli#23987]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have an esm type library that I implemented as a minimal reproduction project at: https://github.com/BppleMan/esm-lib.git.
When I introduced the esm module in angular, I got error:
```
$ ng build
✔ Browser application bundle generation complete.

./node_modules/.pnpm/github.com+BppleMan+esm-lib@41c013849040319f564dac_dhi5c3lxlelecow2p7n3vaxycy/node_modules/esm-lib/codicon.css:6:0 - Error: Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  *--------------------------------------------------------------------------------------------*/
|
> @font-face {
| 	font-family: "codicon";
| 	font-display: block;
```

### Minimal Reproduction

https://github.com/BppleMan/angular-ivy-srhfxs.git

### Exception or Error

```text
$ ng build
✔ Browser application bundle generation complete.

./node_modules/.pnpm/github.com+BppleMan+esm-lib@41c013849040319f564dac_dhi5c3lxlelecow2p7n3vaxycy/node_modules/esm-lib/codicon.css:6:0 - Error: Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  *--------------------------------------------------------------------------------------------*/
|
> @font-face {
| 	font-family: "codicon";
| 	font-display: block;
```
```


### Your Environment

```text
Angular CLI: 14.2.4
Node: 16.16.0
Package Manager: npm 8.11.0 
OS: darwin arm64

Angular: 14.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.4 (cli-only)
@angular-devkit/build-angular   14.2.4
@angular-devkit/core            14.2.4 (cli-only)
@angular-devkit/schematics      14.2.4 (cli-only)
@schematics/angular             14.2.4 (cli-only)
rxjs                            7.5.7
typescript                      4.7.4
webpack                         5.74.0
```

**Comment by alan-agius4** [comment]
The problem here is that the library is importing a CSS file as an ECMA module (https://github.com/BppleMan/esm-lib/blob/41c013849040319f564dac32be147669b33d787b/index.js#L1).  This is a non standard Webpack specific feature, which is not supported in the Angular CLI.

Use a `link` tag or [`styles`](https://angular.io/guide/workspace-config#style-script-config) to include a CSS stylehseet.

**Comment by BppleMan** [comment]
> The problem here is that the library is importing a CSS file as an ECMA module (https://github.com/BppleMan/esm-lib/blob/41c013849040319f564dac32be147669b33d787b/index.js#L1). This is a non standard Webpack specific feature, which is not supported in the Angular CLI.
> 
> Use a `link` tag or [`styles`](https://angular.io/guide/workspace-config#style-script-config) to include a CSS stylehseet.

got it, solved my doubts, thanks a lot
