### ISSUE TITLE
I18n is not working after deployment it is showing 404 error

### ISSUE THREAD

**Issue by otaku0304** [angular/angular-cli#23992]
### Command

extract-i18n

### Description

After successful deployment the web pages is showing 404 error and once I remove the localize : true in angular.json the webpage is coming but the translation is not working.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
