### ISSUE TITLE
Build fails Angular 14 warning: Expected identifier but found "*"

### ISSUE THREAD

**Issue by govind-sg** [angular/angular-cli#23995]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I would also like to know how to resolve this. The first fix that is needed is to correctly identify the source file that contains this CSS element.

In my case, I'm getting
Warning: ▲ [WARNING] Expected identifier but found "*"

```
styles.css:40:2:
  40 │   *zoom: 1;
     ╵   ^
```
and

Warning: ▲ [WARNING] Expected identifier but found "*"

```
styles.css:132:2:
  132 │   *zoom: 1;
```
But `*zoom` doesn't exist anywhere in my codebase nor my CSS so I cannot remove it. Angular CLI is seeing it somewhere but where that location is is a mystery.

### Minimal Reproduction

This I am facing while running the build command `npm run build`

### Your Environment

```text
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.4
Node: 14.20.0
Package Manager: npm 6.14.17
OS: darwin x64

Angular: 14.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1402.4
@angular-devkit/build-angular              14.2.4
@angular-devkit/core                       14.2.4
@angular-devkit/schematics                 14.2.4
@angular/cdk                               14.2.3
@angular/flex-layout                       12.0.0-beta.35
@angular/material                          14.2.3
@angular/pwa                               0.1102.19
@nguniversal/express-engine                12.1.3
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        14.2.4
rxjs                                       6.6.7
typescript                                 4.6.4
webpack                                    5.74.0

```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment]
The problematic CSS is likely from an NPM dependency. Did you look for `*zoom` one your node modules?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
