### ISSUE TITLE
When i am trying to install angular cli i am getting this error plz help me out ? node is correctly installed 

### ISSUE THREAD

**Issue by devrockzz** [angular/angular-cli#2399]
npm ERR! git clone --template=C:\Users\USER\AppData\Roaming\npm-cache\_git-remot
es\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\
Users\USER\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compres
sion-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undef
ined
npm ERR! git clone --template=C:\Users\USER\AppData\Roaming\npm-cache\_git-remot
es\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\
Users\USER\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compres
sion-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undef
ined
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USER\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\angular-cli\angular-cli-master\npm-debug.log

**Comment by vandut** [comment]
There is explanation in your log:
```
npm ERR! not found: git
```

**Comment by DimaGapfild** [comment]
I had same problem, after git install, check PATH, and you also may need to add

> C:\Program Files\Git\bin\git.exe;C:\Program Files\Git\cmd

**Comment by filipesilva** [comment]
Some `npm` operations rely on git got be installed, thus you do need git in your system.
