### ISSUE TITLE
Support fish shell on autocomplete

### ISSUE THREAD

**Issue by tarlepp** [angular/angular-cli#23993]
### Command

add, build, config, doc, e2e, extract-i18n, generate, help, lint, new, run, serve, test, update, version

### Description

Currently Angular CLI autocompletion only supports Bash or Zsh. It would be really nide that `ng completion` supports `fish` shell - https://fishshell.com/

### Describe the solution you'd like

Add support for `fish` shell.

**Comment by alan-agius4** [comment]
This needs to be done upstream first.

See https://github.com/yargs/yargs/issues/1904 and https://github.com/yargs/yargs/issues/1391
