### ISSUE TITLE
15.0.0-next.3 sets target to ES2022 and project can't be build anymore

### ISSUE THREAD

**Issue by e-oz** [angular/angular-cli#24007]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.0-next.0

### Description

```
 TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration. For more information, see https://github.com/browserslist/browserslist
```

Not every project is ready for ES2022. One example is Leaflet.
Please do not set "target' forcefully, or create some option to turn it off, or please create some small doc page how to control it - https://github.com/browserslist/browserslist has 0 information about it.

### Minimal Reproduction

1. Take some project which uses leaflet (better to take some 3-5 years old project).
2. Run `ng serve` or `ng build`

### Your Environment

```text
15.0.0-next.3
```

**Comment by alan-agius4** [comment]
@e-oz, I am not understanding the problem with Leaflet. Can you please elaborate and create a reproduction? Thanks.

**Comment by e-oz** [comment]
Problem is that code of the project is not ready for ES2022, and Angular CLI does not let to change "target", enforcing this value to be "ES2022" (there is no way to change it, I had to  downgrade to 15...next.0). Leaflet here is just for example, issue is not in Leaflet. 

I just think that it's obvious that some projects will not compile with target=ES2022, so there should be some way to prevent this behavior of Angular CLI.

**Comment by alan-agius4** [comment]
@e-oz, what are the errors that you are experiencing?  Please provide a minimal reproduction.

**Comment by e-oz** [comment]
Ok, I see. Maybe you don't believe that some projects are not ready for ES2022 and you think that enforcing the "target" value will bring no friction :) Then let me convert it to feature request - maybe not only I have to support projects, created before ES2022.
