### ISSUE TITLE
3rd party  (moment) is undefined

### ISSUE THREAD

**Issue by vlio20** [angular/angular-cli#2400]
Hi,
I have installed moment via npm.
Here is the `package.json`:
```
  "dependencies": {
...
    "moment": "^2.15.1",
...
  },
```
here is the `angular-cli.json`:
```
{
  "apps": [
    {
      "main": "src/main.ts",
      "tsconfig": "src/tsconfig.json",
      "scripts": [
        "../node_modules/moment/min/moment.min.js"
      ]
    }
  ],
  "project": {
...
}
```

Here is how I use it:
```
@Injectable()
export class Ng2AppComponent {
  title = '';

  constructor() {
    this.title = 'ng2-app works!' + moment();
  }
}
```

And I am getting the following error in console:
![ss](http://image.prntscr.com/image/7d21cdf4995b4af1a45a8f84c2146f4d.png)

What is wrong with my configuration?

**Comment by arlowhite** [comment]
Moment doesn't need to be setup as a global package.
Remove your **scripts** field and instead just do:

`import moment from 'moment';`

**Comment by arlowhite** [comment]
My old SystemJS build system worked with the import statement I gave you. But now that I've migrated to angular-cli it gives this error (removed paths):

> ERROR in [default]
> Module '"node_modules/moment/moment"' has no default export.

So instead, try changing the import to:
`import * as moment from 'moment';`

This at least builds for me, though I'm still working on finishing my migration, so haven't verified it works in a browser environment yet.

**Comment by letorn** [comment]
"import * as moment from 'moment';"  which file I need to write into ?

**Comment by vlio20** [comment]
I have changed it to `import * as moment from 'moment';` but now I am getting an XHR error:
![img](http://image.prntscr.com/image/3a64732128ae49c1907e754ae056e879.png)

**Comment by arlowhite** [comment]
Well, this isn't a bug in angular-cli.

1. Create a new project with: ng new
2. npm install --save moment

Try using moment.
**app.component.ts**
```
import { Component } from '@angular/core';
import * as moment from 'moment';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.sass']
})
export class AppComponent {
  title = moment().format('MMM Do YYYY');
}
```

So I'm guessing something is wrong with your project configuration.
Maybe create a new project with ng and do a directory diff with your project to examine the differences in your project's configuration.

You should probably close this issue as it's not a bug in angular-cli.

**Comment by vlio20** [comment]
@arlowhite , I have created a new project and still it is the same thing. Do you wont me to create a github repo?

**Comment by arlowhite** [comment]
Your version of angular-cli is old. Update it.

Maybe follow these instructions?
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14

**Comment by vlio20** [comment]
you are right, thanks!!!
