### ISSUE TITLE
index.ts file not being created when a component is created

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#2402]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Linux flow 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Versions.
$ ng --version
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: linux x64

### Repro steps.
ng g c TestComponent

### Mention any other details that might be useful.
I no longer see index.ts file?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by deebloo** [comment]
index.ts files are no longer generated since the move to NgModule. At the moment if you want to use barrels you have to manage them yourself.

**Comment by rajinder-yadav** [comment]
Would be nice to have a switch :) for those who don't want to do it manually.

**Comment by filipesilva** [comment]
The CLI follows the style-guide, and the recommendation changed to not have `index.ts` files overall. 

Reexporting is still useful, and we still generate `./src/index.ts` and `./src/shared/index.ts` on `ng new`, but we don't do that for other generators.

**Comment by speed-of-light** [comment]
hi @filipesilva 
Could you provide the source of where in the style-guide shows `index.ts` is recommended not to have? I'd like to know more detail about it. Thanks.

**Comment by filipesilva** [comment]
@speed-of-light it is not that the style guide recommends that one does not use `index.ts` files, but rather that it used to recommend you have it and now it doesn't.
