### ISSUE TITLE
Localization base HREF is not set

### ISSUE THREAD

**Issue by Rolandisimo** [angular/angular-cli#24040]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

After adding localization to my app, I read this part of the angular documentation

> The CLI also adjusts the HTML base HREF for each version of the application by adding the locale to the configured baseHref. 

The documentation keeps mentioning that it should happen automatically but I doubt it as adding the locale to my url breaks my router. Meaning, I would expect to also take into account all my current router defined routes. I'm guessing that again - no.

![baseHref](https://user-images.githubusercontent.com/9778368/194694561-329ab108-b4c8-4402-9e2c-e8b4df075062.png)
<img width="524" alt="angular" src="https://user-images.githubusercontent.com/9778368/194694559-fd63e029-49e0-463f-ae8c-c15c1837c984.png">

I am not sure what is wrong and the documentation is not helpful. The localization works btw. It does use the `lv` locale by default now but I want this to be dynamic from the url. Or if not the url, at least I'd like to see it documented on how else this dynamic lang changing can be achieved with Angular. If I can't solve this with native angular, then I will just switch to some other solution which seems counter productive to what angular would want e.g. https://www.freakyjolly.com/switch-multiple-languages-i18n-using-ngx-translate-in-angular-12/

### Please provide the exception or error you saw

```true
No exception. Base HREF is not being set.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.4
Node: 16.17.0
Package Manager: npm 8.15.0
OS: darwin x64

Angular: 14.2.3
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.4
@angular-devkit/build-angular   14.2.4
@angular-devkit/core            14.2.4
@angular-devkit/schematics      14.2.4
@angular/cli                    14.2.4
@schematics/angular             14.2.4
rxjs                            7.5.7
typescript                      4.7.4
```

### Anything else?

If I add baseHref manually under achitect -> build, then my route does prepend the `en` value.
```
"baseHref": "en",
"localize": ["lv"],
```

However, I also added the same baseHref to the locale and angular ignored it. So it seems that the baseHref I mentioned above makes the base href static (?). Not sure.
```
"i18n": {
  "sourceLocale": "en-US",
  "locales": {
    "lv": {
      "translation": "src/locale/messages.lv.xlf",
      "baseHref": "lv"
    }
  }
},
```

**Comment by alan-agius4** [comment]
Hi @Rolandisimo, I am trying to replicate this but I am not able to as the correct base href is being set when I run `ng build`.

```html
<!DOCTYPE html>
<html lang="lv" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>I18nReproduction</title>
    <base href="/lv/" />
```

Can you please provide a minimal reproduction? A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
