### ISSUE TITLE
For Angular 15, babel needs updating to (at least) 17.18.10

### ISSUE THREAD

**Issue by wratho** [angular/angular-cli#24056]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Please inform me if this belongs in a different category, but honestly none of them looked right.

I reported a bug in babel a while back and resolved here: https://github.com/babel/babel/pull/14752. The latest version of Angular targets ES2022, which will break any applications impacted by the babel issue.

**Comment by alan-agius4** [comment]
Babel packages are already updated to the latest versions https://github.com/angular/angular-cli/blob/979bce45e63eda9ac5402869ef3dc4c63aaca3f1/packages/angular_devkit/build_angular/package.json#L13-L21
