### ISSUE TITLE
Feature request: angular-cli.json > assets supporting array of values

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/angular-cli#2405]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
````
$ ng --version
angular-cli: 1.0.0-beta.15
node: 4.4.7
os: win32 x64
````

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I've got several asset folders under src: src/images, src/img, src/fonts that have to be copied to the dist folder.

When running ng build / ng build --prod, those resources are missing. 

The config option app-> assets only supports one string, not an array of strings.

**Comment by filipesilva** [comment]
I changed the title to better reflect what this issue is meant to be asking.
