### ISSUE TITLE
While upgrading the angular version from 8.2.14 to 9...getting error

### ISSUE THREAD

**Issue by PragGawande** [angular/angular-cli#24057]
### Command

help

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Command used

npx @angular/cli@9 update @angular/cli@9 @angular/core@9

also tried with command ng update

npm ERR! 404  '@angular/cli@9' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

node version
v16.17.0

### Minimal Reproduction

npx @angular/cli@9 update @angular/cli@9 @angular/core@9

ng update
npm update

### Your Environment

```text
Angular CLI: 8.3.29
Node: 16.17.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.29
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.3.29
@angular-devkit/schematics        8.3.29
@angular/cli                      8.3.29
@ngtools/webpack                  8.3.29
@schematics/angular               9.1.15
@schematics/update                0.803.29
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
```

**Comment by alan-agius4** [comment]
Hi @PragGawande, 

This looks like any issue with your environment, if you are using a private NPM repository make sure that is synced with the public repository. 

It is also important to point out that Angular versions older than version 12 are no longer supported. For more information please see https://angular.io/guide/releases#actively-supported-versions
