### ISSUE TITLE
Using open-props fails when switching to the experimental esBuild

### ISSUE THREAD

**Issue by SanderElias** [angular/angular-cli#24064]
### Description

When I have an app that uses [open-props](https://open-props.style/) it fails to build when I switch to the esBuild builder.

I create a small [reproduction repo ](https://github.com/SanderElias/ngEsbuild)

### Minimal Reproduction

pull this small [reproduction repo ](https://github.com/SanderElias/ngEsbuild) and run `ng build`
it will fail like this:

While `ng serve works and build with the webpack builder also works. (and both do pull in the asked-for CSS!)

### Exception or Error

![image](https://user-images.githubusercontent.com/1249083/195371833-e068cb89-6b8c-4c27-a5bf-e59e1c23ee20.png)

### Your Environment

```text
Angular CLI: 15.0.0-next.4
Node: 18.4.0 (Unsupported)
Package Manager: npm 8.18.0 
OS: linux x64

Angular: 15.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0-next.4
@angular-devkit/build-angular   15.0.0-next.4
@angular-devkit/core            15.0.0-next.4
@angular-devkit/schematics      15.0.0-next.4
@angular/cli                    15.0.0-next.4
@schematics/angular             15.0.0-next.4
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by clydin** [comment]
From examining the package, it appears that the error is legitimate.  The `open-props` package contains an `exports` field which prevents deep imports and only allows imports from listed paths.  In this case, the path suggested (`open-props/style`) should be used and will cause the build to succeed.

There, however, is a bug on the Webpack side where the suggested path does not work but should.  Further investigation is in progress to resolve this for the Webpack build.

**Comment by SanderElias** [comment]
@clydin Right! 
Because it worked with webpack I assumed an esbuild problem, instead of looking into it. (to be fair, the imports for open-props did change too, mine where the "old" way of importing)
Thaks for the pointer!
