### ISSUE TITLE
Install errors: node-pre-gyp ERR

### ISSUE THREAD

**Issue by rajinder-yadav** [angular/angular-cli#2406]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Linux ubuntu

### Versions.
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: linux x64

### Repro steps.
sudo su
pm install -g angular-cli@latest

### The log given by the failure.

<pre>
[execsync v1.0.2] Attempting to compile native extensions.
[execSync v1.0.2]
    Native code compile failed!!

> node-zopfli@2.0.1 install /opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz
 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@6.6.0 (node-v48 ABI) (falling back to sourc
e compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.6.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/opt/local/lib/node_modules/angular-cli/node_modules/nod
e-zopfli/.node-gyp"
make: Entering directory '/opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
make: *** No rule to make target '../.node-gyp/6.6.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/local/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276
:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "b
uild" "--fallback-to-build" "--module=/opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v
48-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/opt/local/lib/node_modules/angular-cli/node_modules/node
-zopfli/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/angular-cli/node_module
s/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/opt/local/lib/node_modules/angular-cli/node_modules/node-z
opfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/opt/local/lib/node_modules/angular-c
li/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/local/lib/node_modules/angular-cli/node_modules/node-pre-gy
p/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-38-generic
node-pre-gyp ERR! command "/opt/local/bin/node" "/opt/local/lib/node_modules/angular-cli/node_modules/.bin/node-pre-gyp" 
"install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/opt/local/bin/node /opt/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js buil
d --fallback-to-build --module=/opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linu
x-x64/zopfli.node --module_name=zopfli --module_path=/opt/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib
/binding/node-v48-linux-x64' (1)

> node-sass@3.10.0 install /opt/local/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/install.js

</pre>

**Comment by rajinder-yadav** [comment]
I do have node-gpy installed.

<pre>
# npm -g list node-gyp
/opt/local/lib
├─┬ angular-cli@1.0.0-beta.16
│ ├─┬ ember-cli@2.5.0
│ │ └─┬ npm@2.14.21
│ │   └── node-gyp@3.3.0 
│ └─┬ node-sass@3.10.0
│   └── node-gyp@3.4.0 
├── node-gyp@3.4.0 
├─┬ npm@3.10.8
│ └── node-gyp@3.4.0 
└─┬ pakmanager@0.12.1
  └─┬ pakman@0.11.5
    └─┬ npm@1.4.29
      └── node-gyp@1.0.1 
</pre>

**Comment by vlad-mk** [comment]
because of some reason node-gyp didn't load the nodejs headers.
I've found the following workaround:
/usr/lib/node_modules/npm/bin/node-gyp-bin/node-gyp node-pre-gyp install --fallback-to-build

**Comment by rajinder-yadav** [comment]
OK I run something similar, do I need to do anything else do do the install??

<pre>
# /opt/local/bin/node-gyp node-pre-gyp install --fallback-to-build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.6.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v6.6.0/node-v6.6.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.6.0/node-v6.6.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.6.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.6.0/SHASUMS256.txt
6.6.0
gyp info ok 
</pre>

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794
