### ISSUE TITLE
3rd party leaflet plugin doesn't extend 

### ISSUE THREAD

**Issue by ajainvivek** [angular/angular-cli#2408]
### OS?
> Mac OSX (El Capitan)

### Versions.
> angular-cli: 1.0.0-beta.15
node: 6.5.0

### Repro steps.
> I have installed leaflet 
npm install leaflet --save
npm install @types/leaflet --save-dev
included in angular-cli.json under scripts

> Importing leaflet works but I had to install leaflet plugin called **esr-leaflet** but unfortunately that doesn't work and never extends leaflet
npm install esri-leaflet --save 
included in angular-cli.json under scripts

**Comment by flumpt** [comment]
Hi @ajainvivek,

i am facing the same problem with the plugin leaflet-editable. Did you solve your problem and if so, how did you do it?

Thanks in advance!

**Comment by flumpt** [comment]
@k-vladisalv Thank you for your reply. I will try that asap.
