### ISSUE TITLE
Http Client in @angular-devkit/schematics

### ISSUE THREAD

**Issue by alexcibotari** [angular/angular-cli#24084]
### Command

add

### Description

When I write a new schematic command, I would like to make some HTTPS calls to get data from Cloud.
For example, I would like to sync some content or configuration from Cloud to a Local project.

### Describe the solution you'd like

Making Angular HTTP Client available in Schematics commands 

### Describe alternatives you've considered

I'm using external HTTP client

**Comment by alan-agius4** [comment]
Hi @alexcibotari, 

Thanks for this feature request. However, this is currently no in the Angular CLI roadmap. 

Let's reconsider this in the future if there are more users requesting it. 

Thanks.
