### ISSUE TITLE
[Angular 15] ng test: Add CLI flags to generate unit test report(xml) and code coverage report(Cobertura/JaCoCo) for CI

### ISSUE THREAD

**Issue by prabh-62** [angular/angular-cli#24094]
### Command

test

### Description

As per [Angular CLI v15 release notes](https://github.com/angular/angular-cli/releases/tag/15.0.0-next.4), `karma.conf.js` file will no longer be generated by default for newly generated applications/libraries.

What is the expected workflow for a developer to generate unit test report(xml) and code coverage report(Cobertura/JaCoCo) for Azure DevOps CI?

Below are the tasks available to collect unit test and code coverage reports in Azure DevOps:

- [Publish Test Results task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=trx%2Cyaml)
<img width="797" alt="azure_devOps_unit_tests" src="https://user-images.githubusercontent.com/13006107/195894532-f601009d-7365-44ab-8b39-68d842b4ce53.png">

******

- [Publish Code Coverage Results task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops)
<img width="808" alt="azure_devOps_code_coverage" src="https://user-images.githubusercontent.com/13006107/195894184-2118e7e5-cbff-48fe-b42b-9f6b234678ac.png">

******
Previous request: #21219

### Describe the solution you'd like

Provide CLI flags to generate unit test and code coverage reports
`ng test --project command-center --no-watch --code-coverage --code-coverage-report-format cobertura --tests-report-format junit`

Or, provide a command to generate a default `karma.conf.js` file
`ng generate tests-config --project command-center`

**Comment by alan-agius4** [comment]
In this case since you require customization it’s recommended that you create your own Karma configuration file.

**Comment by prabh-62** [comment]
How should I generate my own Karma configuration file (Assuming I **have no knowledge of previous angular releases** where a default `karma.conf.js` file was present)?

This is how a `tsconfig.json` file can be generated:
- `tsc --init`

**Comment by alan-agius4** [comment]
We are exploring various possibles to generate such config. Having it in a hidden directory, using a schematic, or coping it from a documentation portal.

Whichever approach we go for will be documented before the final v15 release.
