### ISSUE TITLE
Angular 11 : aot flag true makes a component to not load and throws console error

### ISSUE THREAD

**Issue by nirmal98kumar** [angular/angular-cli#24101]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

10

### Description

I have upgrade my application to Angular v11 . 
It seems one of the pages doesnot load when aot flag is enabled in angular.json.
I have attached the relevant error thrown in console.
Strangely the issue doesnot occur when aot is disabled.

### Minimal Reproduction

**angular.json**
            "optimization": true,
            "sourceMap": true,
            "outputHashing": "all",
            "namedChunks": false,
            "aot": true,
            "extractLicenses": true,
            "vendorChunk": false,
            "buildOptimizer": true

**code:**

_my-library.component.html_

```
<div class="container custom_container">
  <div class="Tabs-header">
    <div class="padding-left-0 padding-right-0">
      <div class="row  border_line my-library-tab">
        <div class="width_full" *ngFor="let item of panelObject; let i=index" (click)="toggleTabArrow(item.type,i)">
          <div class="card panel-tab-card">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```

### Exception or Error

```text
core.js:6210 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'selectors')
TypeError: Cannot read properties of null (reading 'selectors')
    at core.js:10350:55
    at La (core.js:10172:31)
    at core.js:14786:27
    at Module.Cl (core.js:14823:9)
    at template (my-library.component.html:1:1)
    at Sa (core.js:9614:9)
    at xa (core.js:9418:13)
    at Za (core.js:10698:5)
    at core.js:9283:9
    at xa (core.js:9443:13)
    at Gg.create (core.js:25141:13)
    at $h.createComponent (core.js:23180:47)
    at e.activateWith (router.js:5324:40)
    at it.activateRoutes (router.js:2134:40)
    at router.js:2085:18
    at Array.forEach (<anonymous>)
    at x (zone-evergreen.js:798:39)
    at x (zone-evergreen.js:750:21)
    at zone-evergreen.js:860:21
    at l.invokeTask (zone-evergreen.js:399:35)
    at Object.onInvokeTask (core.js:28578:33)
    at l.invokeTask (zone-evergreen.js:398:40)
    at s.runTask (zone-evergreen.js:167:51)
    at v (zone-evergreen.js:569:39)
    at u.invokeTask [as invoke] (zone-evergreen.js:484:25)
    at m (zone-evergreen.js:1621:18)
    at HTMLAnchorElement.y (zone-evergreen.js:1658:25)
```

### Your Environment

```text
Angular CLI: 11.2.19
Node: 14.15.1
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.19
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/cdk                    11.2.13
@angular/cli                    11.2.19
@angular/material               11.2.13
@schematics/angular             11.2.19
@schematics/update              0.1102.19
rxjs                            6.6.7
typescript                      4.1.6
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Closing as no reproduction provided. Please feel free to open a new issue with a reproduction if the problem persists.
