### ISSUE TITLE
Missing "Adding extra files to the build" section

### ISSUE THREAD

**Issue by datrinh** [angular/angular-cli#2411]
In the table of contents in the README there is a "Adding extra files to the build" section but without any content.

**Comment by vekexasia** [comment]
Lol i was looking at the same thing too. did you find the proper way? @datrinh ?

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2596, it should have been removed when we moved to webpack. You can add files to `src/assets/` and they will be copied as is to `dist/assets/`.
