### ISSUE TITLE
Turbopack

### ISSUE THREAD

**Issue by buu700** [angular/angular-cli#24139]
### Command

build, serve

### Description

For future versions of the CLI, it may be worth considering migrating from Webpack to [Turbopack](https://turbo.build/pack). Related:

* https://vercel.com/blog/turbopack
* https://turbo.build/pack/docs/migrating-from-webpack

The resource requirements of production builds have ballooned considerably in recent Angular releases, which is understandable given the continued output optimization and type checking strictness improvements, but it is nevertheless a major impact on Angular's developer experience. Perhaps Turbopack could be a solution for addressing this issue.

**Comment by alan-agius4** [comment]
Hi @buu700,

Thanks for bring this up. 

As always we will continue to watch and experiment with new bundlers. We will continue watching what is happening in this area including the future of Webpack and Turbopack.

Currently, we do offer an opt-in preview of an esbuild based browser builder.
