### ISSUE TITLE
Complete webpack build after every change

### ISSUE THREAD

**Issue by hemantjadon** [angular/angular-cli#2414]
### OS
> Mac OSX El Capitan
> os : darwin x64

### Versions.
> angular-cli: 1.0.0-beta.15
> node: 4.4.5

### Repro steps.

* Slow compilation of `styles` and `template` files

* Each time a file changes the complete Webpack build runs, which consumes time.

### Other details that might be useful.

* The normal compilation using typescript compiler and gulp or grunt helps to speed up the compilation of `styles` and `templates`, speeding up the development process.

* There should be a flag in `ng serve` which builds only the changed part of the code

* There might be such an option which I don't know or not documented.

* [Edit] :  There can be something like Hot module replacement, only for `styles` and `templates` if not complete.

**Comment by denkomanceski** [comment]
+1

**Comment by gelliott181** [comment]
This is listed as a priority for RC1 (https://github.com/angular/angular-cli/milestone/1).

**Comment by hemantjadon** [comment]
Is there any workaround for this issue for faster development ?

**Comment by filipesilva** [comment]
We already do incremental builds, that's included by default in webpack. What makes you say that everything is recompiled?

**Comment by denkomanceski** [comment]
I think the css assets are the ones that make this problem... the development is really slow.. we have to wait like 5 seconds before a refresh maybe even more.. I think the assets folder is big (with icons, svgs, csses) and this folders slows the whole refresh for some reason

**Comment by hemantjadon** [comment]
It is also pretty slow even when assets folder is not very large. I think it is due to the complete rebuild of whole project even when changes are only in one file. I don't know that it is a desired behavior or not but for fast template and css editing it hampers development speed alot.

But as it is duplicate of #1980 and is a milestone for RC it can be closed

**Comment by hemantjadon** [comment]
The task which I recently noticed taking the most time is `chunk asset optimization`. Will upload a screenshot soon.

**Comment by filipesilva** [comment]
@hemantjadon, unless there's something really wrong, there is no so thing as a full rebuild. Compare the total time of your first build with your rebuild, the rebuild should be faster.

That being said, there are reports of builds just being slow. For that, see #1980

**Comment by masaanli** [comment]
Having a big project and a fast pc. And the Building times are 16 seconds...

**Comment by hemantjadon** [comment]
@filipesilva You are right that the incremental compilation is done the first build takes about `14-15s` but the rebuilds take `5-6s`, though the rebuilds are faster than initial builds, but i think it doesn't solve the exact problem, when i change slight bit in styles or templates i have to wait `5s` every time before i can see my changes, I think it decreases the speed a lot.

I mean `angular-cli` was meant to increase the development speed, and it does in initialisation of the project and the boilerplate code, but rebuilds are slow and the waiting after the change to be reflected is quite painful

**Comment by masaanli** [comment]
First time is slower than the rebuilds. Here stated, my initial build is taking 60 seconds. And the rebuild time itself is 16 seconds.
