### ISSUE TITLE
Android 9 inset css property breaks older production compatibility with 14.2.4 cli

### ISSUE THREAD

**Issue by laurentperez** [angular/angular-cli#24157]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12

### Description

Hello

Our Android 9 customers and us are affected by the inset reduce of top/bottom/left/right mentionned in https://github.com/ionic-team/ionic-framework/issues/25929#issuecomment-1247004115

Does angular cli support Android 9 or is it deprecated ? It looks only supported by chrome on android starting from Sept. 28Th : https://caniuse.com/?search=inset

### Minimal Reproduction

see https://github.com/ionic-team/ionic-framework/issues/25929#issuecomment-1247004115

### Your Environment

```text
Angular CLI: 14.2.4
Node: 16.17.1
Package Manager: npm 8.15.0 
OS: linux x64

Angular: 14.2.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.4
@angular-devkit/build-angular   14.2.4
@angular-devkit/core            14.2.4
@angular-devkit/schematics      14.2.4
@angular/cdk                    14.2.3
@schematics/angular             14.2.4
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by alan-agius4** [comment]
Angular officially supports the 2 most recent major versions of Android which currently are 12 and 13, and the latest version of Chrome.

if you require additional support you can alter the browserslist configuration but you might run in other issues. 

See: https://angular.io/guide/browser-support

Closing as this is working as expected.
