### ISSUE TITLE
Removed test.ts introduces a breaking change for shallow component tests

### ISSUE THREAD

**Issue by JohannesHoppe** [angular/angular-cli#24153]
### Command

test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 14

### Description

In Angular v14 and before unknown elements caused a warning but no error for our unit tests. (`Error: NG0304: 'xxx' is not a known element...`)

Thanks to https://github.com/angular/angular/issues/36430 this behaviour can be adjusted now. (`errorOnUnknownElements: true`). But this new behaviour is still [disabled by default](https://github.com/angular/angular/blob/557cf7dc63fe768900f296252e1a96e6166b24df/packages/core/testing/src/test_bed_common.ts#L13).

New projects in Angular 15 will have no `test.ts` anymore. see https://github.com/angular/angular-cli/commit/56a1e8f9f52658488afb9d36007e96c96d08a03b

Now the testing environment is created like this:

```
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting(), {
  errorOnUnknownElements: true,
  errorOnUnknownProperties: true
});
```

I wonder if we should introduce this change so quickly. This will only affect new projects, but it is still a new behaviour. If the new behaviour is intended, then it should definitely be explained in detail in the changelog.

### Minimal Reproduction

Create a unit test with `TestBed` for a component with a child component, but do not declare the child.

### Exception or Error

```text
Error: NG0304: 'app-xxx' is not a known element (used in the 'AppComponent' component template):
1. If 'app-xxx' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
2. If 'app-xxx' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

### Your Environment

```text
15.0.0-rc.1
```

### Anything else relevant?

<img width="1556" alt="Screenshot 2022-10-27 at 17 46 52" src="https://user-images.githubusercontent.com/640639/198343284-fe7d6692-09d1-42c7-8cf0-8d6eea5db47f.png">

**Comment by alan-agius4** [comment]
This is indeed indented for new projects to avoid introducing “tech debt”.

Both options have been introduced in version 14 with a default value of `false` to retain backwards compatibility. This is also a way to give users enough time to adapt their existing codebases before flipping the default and doing the breaking change. 

While new projects in Angular 15 will have no `test.ts` anymore, this can be still created.

**Comment by JohannesHoppe** [comment]
Thank you for the quick clarification.
In that case this is not a real bug. 👍
