### ISSUE TITLE
Support for mochai, chai, sinon

### ISSUE THREAD

**Issue by nkimaina** [angular/angular-cli#2415]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here: 1.0.0-beta.15

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
Is it possible to add support for testing with mocha chai and sinon?
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We use karma, so you should be able to use whatever karma uses. You'll have to configure `karma.conf.js` yourself though.
