### ISSUE TITLE
Configurable websocket url

### ISSUE THREAD

**Issue by vmachacek** [angular/angular-cli#24161]
### Command

serve

### Description

I have a scenario when I'm running large system behind a proxy which simulates the production and there are several apps running in a background - that includes several Angular apps. I realized that hot reload would work for only one of them at the time - websocket url is rooted and cannot be changed. Would setting different URL for web-socket connection help to make them all work with hot reload?

### Describe the solution you'd like

I would like to have a way to customize the URL for the web-socket connection so that I can distinguish them and proxy them to correct angular dev server

### Describe alternatives you've considered

no alternatives considered

**Comment by alan-agius4** [comment]
Hi @vmachacek, 

In this scenario you can use the `--serve-path` option. 

See: https://angular.io/cli/serve for more information about all the available options in `ng serve`.
