### ISSUE TITLE
(another) ng build --prod issue

### ISSUE THREAD

**Issue by m4mbart** [angular/angular-cli#2417]
### OS?

macOS Siera (but previosly tested with Capitain)
### Versions.

angular-cli: 1.0.0-beta.16
nodejs: v6.4.0
### Repro steps.

App generated with CLI. Nothing changed in app.module structue. Only third party libs added to package.json
### The log given by the failure.

![prod-error](https://cloud.githubusercontent.com/assets/11663618/18954035/6f27de8e-8651-11e6-9b24-646454767de1.png)

ng serve works fine. ng build works fine too. This error only occurs with ng build --prod. Build process itself goes just fine. But when serving the output, one is presented with the stacktrace from the screenshot.

**Comment by filipesilva** [comment]
That error is not related to the CLI, but rather part of Angular 2 itself. It usually comes up when migrating an app to RC5/6/final, and indicates that a component wasn't added to a `NgModule`.

**Comment by m4mbart** [comment]
It started out as a RC6 project. So NgModules we're always there. I also have no issues or warnings during development. I am only using some external non Angular JS libs like Material Design Lite. Could it be caused by that and if so how can I solve it?

**Comment by m4mbart** [comment]
If I break on the exception. 't' in this case is the window object.

**Comment by filipesilva** [comment]
Hm... it might be related to third party libs then... Could you try to setup a repro repository in github? I can try to debug it.

**Comment by m4mbart** [comment]
I am not so sure about that. It is already quite a large project and it would be time consuming to strip al sensitive stuff from the source. Can I send you a publicly accessible, but hidden, URL of the test environment in a private message? Any solutions can of course be discussed publicly in this thread

**Comment by catull** [comment]
@m4mbart Is this still an issue ?

**Comment by m4mbart** [comment]
No I think it was a problem with some 'abstract' components I have been using. I removed those components and instead made the inheriting components composable. I will close this issue, thanks!
