### ISSUE TITLE
Is it possible to integrate postcss?

### ISSUE THREAD

**Issue by willgm** [angular/angular-cli#2420]
I would like to integrate postcss in order to use autoprefix and other plugins, but looks like it is not supported. So, two questions:

- Is it going to be supported in the future?

- Is there a easy way to integrate postcss in my current project with angular-cli?

Keep up the good work! =)

**Comment by shayan786** [comment]
+1

**Comment by scottwio** [comment]
See https://github.com/angular/angular-cli/issues/1656

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1512
