### ISSUE TITLE
After Ng serve and saving any changes it is Generating browser application bundles continously

### ISSUE THREAD

**Issue by anilpenumacha** [angular/angular-cli#24219]
### Command

run, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi Team,

After ng serve command, am saving my changes in ts file and it is generating the browser bundles continuously, So i had to stop the bundling by pressing ctrl + c key and doing ng serve every time. please help me on this issue.

tried with ng serve --watch and ng serve and npm start as well

### Minimal Reproduction

tried with ng serve --watch and ng serve and npm start as well

Steps to reproduce:
1) run the application
2) save any changes 
3) it is compiling and building the bundle generation continuously.

### Your Environment

```text
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.13
Node: 16.14.0 (Unsupported)
Package Manager: npm 8.3.1
OS: win32 x64

Angular: 12.2.14
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            9.0.7
@angular-devkit/schematics      9.0.7
@angular/cli                    12.2.13
@schematics/angular             9.0.7
rxjs                            6.6.7
typescript                      4.3.5

Warning: The current version of Node (16.14.0) is not supported by Angular.
```

**Comment by fmalcher** [comment]
Can you please elaborate what you mean by "it generates continuously"?
Your version of Angular is relatively old – please update to the latest Angular version (currently 14.x.x, v15 coming next week). 🙂

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
