### ISSUE TITLE
Rails and Angular deploy to heroku

### ISSUE THREAD

**Issue by naemcivic** [angular/angular-cli#2422]
I have just deployed an app with Rails as an API and Angular cli based Angular 2 app to Heroku. The build was fine except the app crashes with the status code returning 503. 
Heroku logs shows the following: 

at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=xxxxxx-sea-87329.herokuapp.com request_id=5e584530-d26c-4da0-9722-01b45bd20767 fwd="72.143.57.82" dyno= connect= service= status=503 bytes=

Is my port setting wrong? maybe that's why it's throwing a 503?

**Comment by filipesilva** [comment]
This issue is out of scope for the CLI repo. I'm sorry but we don't have the time and resources to pursue it.

It seems to be hero related and something about not being able to get the favicon.
