### ISSUE TITLE
 compiler does not remove source map reference comments when inlining the source maps

### ISSUE THREAD

**Issue by ryaa** [angular/angular-cli#24230]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The problem is reproducible in the ionic/angular application which uses angular cli for build and other commands.

When the application runs on an iOS device there is error logged saying that it can not find source map file. For example
```
Failed to load resource: The file “core.css.map” couldn’t be opened because there is no such file.
```
or see below
<img width="1379" alt="Screen Shot 2022-11-14 at 14 51 24" src="https://user-images.githubusercontent.com/3608222/201665540-f312e651-8112-4a53-af1d-868fd43527c2.png">

Please also see **Anything else relevant?** section below

### Minimal Reproduction

1) create new ionic project from one of the starter template projects (for example, by issuing the command `ionic start ryaa-use-issue-demo blank --type=angular --no-git --no-link --no-deps --project-id=com.ryaa.demo --package-id=com.ryaa.demo`)
2) in **src/global.scss** replace @import to @use (and update the imported links accordingly)
3) build and run the application on iOS device
Note that there is the below error shown in the console
```
Failed to load resource: The file “core.css.map” couldn’t be opened because there is no such file.
```

OR, you can clone this project https://github.com/ryaa/scss-use-issue-demo, change to the project directory, run `npm install` and then `ionic capacitor build ios` (assuming that you have all the required tools installed/configured), build/run the project on an iOS simulator or a real device and check the console for the above error.

This change/commit which makes the error to appear https://github.com/ryaa/scss-use-issue-demo/commit/e63717ffd10e169fd4237db64c548ec273052cd5

### Exception or Error

```text
Failed to load resource: The file “core.css.map” couldn’t be opened because there is no such file.
```

### Your Environment

```text
Angular CLI: 14.2.9
Node: 18.12.0 (Unsupported)
Package Manager: npm 9.0.0
OS: darwin x64

Angular: 14.2.10
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.9
@angular-devkit/build-angular   14.2.9
@angular-devkit/core            14.2.9
@angular-devkit/schematics      14.2.9
@angular/cli                    14.2.9
@schematics/angular             14.2.9
rxjs                            6.6.7
typescript                      4.7.4
```

### Anything else relevant?

Please note that everything works fine with @import but replacing it to @use in **src/global.scss** makes the generated **www/style.css** file to contain links to the source maps files which fail to load - see below

Here is the **www/style.css** file with @import  in **src/global.scss**. Note that there is only one and the correct **sourceMappingURL** entry in the file
<img width="1076" alt="Screen Shot 2022-11-14 at 14 40 47" src="https://user-images.githubusercontent.com/3608222/201667215-abe2a021-f8f8-4e1b-b044-38756f71f3f1.png">

Here is the **www/style.css** file with @use  in **src/global.scss**. Note that there are multiple and the invalid **sourceMappingURL** entries in the file
<img width="1257" alt="Screen Shot 2022-11-14 at 14 50 13" src="https://user-images.githubusercontent.com/3608222/201667561-afd8a941-cda4-462e-8a35-ee2e3e91ed86.png">
The above **sourceMappingURL** fails when the app runs.

Here is the original issue posted in the ionic repository https://github.com/ionic-team/ionic-framework/issues/26277

**Comment by alan-agius4** [comment]
Hi @ryaa, 

Unfortunately this seems to be an issue with Sass compiler itself. 

```
$ yarn sass src/styles.scss --load-path=node_modules | grep sourceMappingURL

/*# sourceMappingURL=core.css.map */
/*# sourceMappingURL=normalize.css.map */
/*# sourceMappingURL=structure.css.map */
/*# sourceMappingURL=typography.css.map */
/*# sourceMappingURL=display.css.map */
/*# sourceMappingURL=padding.css.map */
/*# sourceMappingURL=float-elements.css.map */
/*# sourceMappingURL=text-alignment.css.map */
/*# sourceMappingURL=text-transformation.css.map */
/*# sourceMappingURL=flex-utils.css.map */
```
