### ISSUE TITLE
Subdirectory files not watched using ng serve

### ISSUE THREAD

**Issue by kdorion** [angular/angular-cli#2423]
When I run 'ng serve', all my files are compiled correctly, but when I make a modification to a file in a subdirectory, nothing happens and I have to re-run ng serve manually.

File structure:

-  src
   -  main.ts --> this file is being watched
   -  app
      -  app.module.ts --> this file is being watched
      -  core
         -  core.module.ts --> this file is NOT being watched

### OS?
> Linux  ubuntu 16.04 LTS

### Versions.
angular-cli: 1.0.0-beta.15
node: 4.5.0
os: linux x64

### Repro steps.
App was created using the cli, subdirectories module were not created using the CLI (is this the problem?) I tried creating a module in a subdirectory using the cli, and it's still not being watched...

### The log given by the failure.
Nothing is logged when a file is modified.

**Comment by kdorion** [comment]
Well, it seemed that a computer reboot did the trick. Closing.

**Comment by kamalkech** [comment]
I have some probleme, angular-cli not compile files of subfolders like shared ..etc on mac 10.6.8

**Comment by MonikaL** [comment]
I have the same problem. Computer reboot doesn't help.
