### ISSUE TITLE
Better build time profiling

### ISSUE THREAD

**Issue by jpike88** [angular/angular-cli#24240]
### Command

build

### Description

I notice that using the es-build builder, there is a small reduction in startup build time and incremental build time. Yet it's quite a small reduction (0-10% at best). It's supposed to be many times faster than webpack, and for my non-angular projects runs extremely quickly.

I want an easy way for angular to spit out a detailed and clear report on the timing of individual build steps, so I can gain insight into where the bottlenecks are. Currently the `verbose` option doesn't give enough info.

### Describe the solution you'd like

maybe something like `ng build --timing`, with granular logs for things such as:

`moved asset y: 20ms`
`built file x using esbuild: 30ms`
`built file z using some other internal module: 30ms`

This would help us all understand better what the bottlenecks in the compiler are.

**Comment by jpike88** [comment]
Out of curiosity, how much do you project performance to improve as esbuild continues to be integrated?

Is it a situation where it will be given more and more share of the compilation step, and the end result becomes like a 90%+ improvement as an end result?

**Comment by alan-agius4** [comment]
I feel like @clydin could give better numbers. But expecting 90% improvements is unrealistic. 

There is about 25% improvement on cold builds for an `ng new` application. However, the 2nd build in Webpack is warm unlike esbuild which is cold. In this case the improvement is between 0~2% on a `ng new` application. This is because Webpack builder has persistant disk which is not yet implemented in the esbuild builder.

**Comment by jpike88** [comment]
side note: I tried ```NG_BUILD_DEBUG_PERF=1 ng build``` and got the below:

```
DURATION[NG_READ_CONFIG]: 0.015043625s
DURATION[NG_CREATE_PROGRAM]: 2.174621916s
DURATION[NG_ANALYZE_PROGRAM]: 0.907005500s
DURATION[NG_FIND_AFFECTED]: 2.779444541s
DURATION[NG_DIAGNOSTICS_TOTAL]: 2.970958583s
DURATION[NG_DIAGNOSTICS_SYNTACTIC]: 0.000839087s [count: 1981; avg: 0.000000424s; min: 0.000000166s; max: 0.000033208s]
DURATION[NG_DIAGNOSTICS_SEMANTIC]: 0.002564570s [count: 1981; avg: 0.000001295s; min: 0.000000417s; max: 0.000159333s]
DURATION[NG_DIAGNOSTICS_TEMPLATE]: 2.964532804s [count: 378; avg: 0.007842679s; min: 0.000001542s; max: 0.918945875s]
DURATION[NG_EMIT_TS*]: 29.843659383s [count: 355; avg: 0.084066646s; min: 0.000251625s; max: 0.332661750s]
DURATION[NG_EMIT_JS*]: 119.922952138s [count: 2167; avg: 0.055340541s; min: 0.000119500s; max: 2.558234625s]
```

The last two values don't make sense

**Comment by alan-agius4** [comment]
> The last two values don't make sense

Not sure what you mean by this.

**Comment by jpike88** [comment]
`29.843659383s` and `119.922952138s` for last to timing values, though total build time was only like 12 seconds

**Comment by alan-agius4** [comment]
That is because parts of those tasks have been done in parallel, the 119.922952138s and 29.843659383s are cumulative.

**Comment by jpike88** [comment]
Ah got it. Thanks for all the hard work
