### ISSUE TITLE
[Karma Jasmine] Error on spies and other types due to type constraints on Angular 14

### ISSUE THREAD

**Issue by argelj289** [angular/angular-cli#24244]
### Command

test

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 10

### Description

I am encounterring many issues about the types I pass to our functions with our unit tests using Karma Jasmine on Angular 14

I already disabled the noImplicitAny and some that was suggested but still this issue still never leaves

is there any other settings that I need to set in the tsconfig.json to make this type checking go away?

I don't need this kind of checking on our unit test as it errors all the Spy methods

### Minimal Reproduction

see attached error sample error:

![image](https://user-images.githubusercontent.com/40298377/202186550-db211e39-299b-46e8-95fb-5026f88eecac.png)

### Exception or Error

```text
Argument of type '() => { className: string; style: { display: string; }; }' is not assignable to parameter of type '(elementId: string) => HTMLElement'.
  Type '{ className: string; style: { display: string; }; }' is missing the following properties from type 'HTMLElement': accessKey, accessKeyLabel, autocapitalize, dir, and 275 more.
```

### Your Environment

```text
Your global Angular CLI version (14.2.6) is greater than your local version (14.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.7
Node: 14.19.3
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 14.2.8
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.7
@angular-devkit/build-angular   14.2.7
@angular-devkit/core            14.2.7
@angular-devkit/schematics      14.0.7
@angular/cli                    14.0.7
@angular/google-maps            11.2.13
@schematics/angular             14.0.7
rxjs                            7.5.7
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
