### ISSUE TITLE
bootstrap.css failed to decode downloaded font OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by daftster** [angular/angular-cli#2424]
> ## Please provide us with the following information:
### OS?

Windows 8.1
### Versions.

angular-cli: 1.0.0-beta.15
node: 6.3.0
os: win32x64
npm:3.10.3
### Repro steps.

Trying to use bootstrap.css only from bootstrap package.
1. npm install bootstrap --save
2. updated angular-cli.json with:
    "styles": [
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ],
### The log given by the failure.

Log from chrome console.
2016-08-07T23%3A59:1 Failed to decode downloaded font: http://localhost/448c34a56d699c29117adc64c43affeb.woff2
2016-09-29 10:56:10.687 2016-08-07T23%3A59:1 OTS parsing error: invalid version tag
2016-09-29 10:56:10.985 2016-08-07T23%3A59:1 Failed to decode downloaded font: http://localhost/fa2772327f55d8198301fdb8bcfc8158.woff
2016-09-29 10:56:10.985 2016-08-07T23%3A59:1 OTS parsing error: invalid version tag
### Mention any other details that might be useful.

during ng build, files like 448c34a56d699c29117adc64c43affeb.woff2 are built in dist directory

**Comment by andrelmp** [comment]
@daftster did you use IIS?
i was having that issue and solve by edit web.config
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <rule name="AngularJS" stopProcessing="true">
                    <match url="assets\/*|/*.js|/*.css|/*.map|/*.woff2|/*.woff|/*.svg|/*.ttf|/*.eot|index.html" />
                    <action type="None" />
                </rule>
                <rule name="AngularJS2">
                    <match url=".*" />
                    <action type="Rewrite" url="index.html" />
                </rule>
            </rules>
        </rewrite>
        <staticContent>
            <remove fileExtension=".woff" />
            <remove fileExtension=".eot" />
            <remove fileExtension=".ttf" />
            <remove fileExtension=".svg" />

            <mimeMap fileExtension=".eot" mimeType="application/vnd.ms-fontobject" />
            <mimeMap fileExtension=".ttf" mimeType="application/font-sfnt" />
            <mimeMap fileExtension=".svg" mimeType="image/svg+xml" />
            <mimeMap fileExtension=".woff" mimeType="application/font-woff" />
            <mimeMap fileExtension=".woff2" mimeType="application/font-woff2" />
        </staticContent>
    </system.webServer>
</configuration>
```

**Comment by mjaric** [comment]
angular-cli: 1.0.0-beta.18
node: 6.8.1
os: darwin x64


Same issue here on Mac OS X. Fonts are delivered from dev server as content-type: 'text/html'. BTW, this has nothing to do with IIS, since content is served using `ng server` command

**Comment by jnorkus** [comment]
angular-cli: 1.0.0-beta.19-3                                                                                                                                                             
node: 6.9.1                                                                                                                                                                              
os: win32 ia32

I am having the same issue. I use IIS, but it doesn't seem to be related as web.config changes have no effect.

**Comment by jnorkus** [comment]
If anyone needs a workaround, this is what I've done.

1. Copy bootstrap fonts to `src/assets/fonts`
2. Add following CSS to `app.component.css`
```
/* Workaround for issue: https://github.com/angular/angular-cli/issues/2424 */
@font-face {
  font-family: 'Glyphicons Halflings';

  src: url('assets/fonts/glyphicons-halflings-regular.eot');
  src: url('assets/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'), url('assets/fonts/glyphicons-halflings-regular.woff2') format('woff2'), url('assets/fonts/glyphicons-halflings-regular.woff') format('woff'), url('assets/fonts/glyphicons-halflings-regular.ttf') format('truetype'), url('assets/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

**Comment by delasteve** [comment]
Following the css bootstrap3 tutorial (below), except using the code snippet instead of the one provided, I was able to get glyphicons to work.

```html
<button type="button" class="btn btn-default" aria-label="Left Align">
   <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
</button>
```

Bootstrap tutorial:
https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-bootstrap.md

**Comment by hansl** [comment]
Closing as this seems to be fixed, from @delasteve comment.

**Comment by RainingNight** [comment]
angular-cli: 12.0
node: 8.1.3
os: windows10 x64

```console
Failed to decode downloaded font: http://localhost:4200/MaterialIcons-Regular.642aa7b0b9a5d6804ac6.woff2
dashboard:1 OTS parsing error: invalid version tag
dashboard:1 Failed to decode downloaded font: http://localhost:4200/MaterialIcons-Regular.3eac1f077c11eca36e5c.woff
dashboard:1 OTS parsing error: invalid version tag
dashboard:1 Failed to decode downloaded font: http://localhost:4200/MaterialIcons-Regular.4f16b06c1373d360e33e.ttf
dashboard:1 OTS parsing error: invalid version tag
```

I am having the same issue. I'm use `ng server` commadn.

**Comment by Rosseyn** [comment]
Had this issue randomly crop up seemingly out of nowhere. @delasteve 's guide link had solution for me. I was using the ~ shortcut for node_modules reference, and needed to switch to using relative pathing via ../../ etc.
