### ISSUE TITLE
ng update and ng install uses different typescript versions

### ISSUE THREAD

**Issue by ky-one** [angular/angular-cli#24255]
### Command

new

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

When I use `ng new` it installs `typescript: ~4.7.2`
When I use `ng update` it upgrades to `typescript: ~4.8.4`

I guess it should use the same typescript version, or?
Because the update.angular.io says: 
``Make sure that you are using a supported version of TypeScript before you upgrade your application. Angular v15 supports TypeScript version 4.8 or later.``

### Minimal Reproduction

npx -p @anuglar/cli@14 ng new test
ng update @angular/core@15 @angular/cli@15

### Your Environment

```text
Windows 10 with node v16.18.0 and no global cli
```

**Comment by alan-agius4** [comment]
It is expected that Angular CLI version 14 ng new generates a new project using TypeScript version 4.7. 

The statement implies that users should migrate their application to Typescript 4.8 (which is supported in version  14) prior of updated to Angular 15.

**Comment by ky-one** [comment]
Sure. But when you create a project with cli@14 and then upgrade to v15 the typescript version is ~4.8.4.
When you create a project with cli@15 then the typescript version is ~4.7.2.

**Comment by alan-agius4** [comment]
You are mistaken.

New version 15 projects use Typescript 4.8.

**Comment by ky-one** [comment]
Yes, your are right. When I use `npx -p @angular/cli@15 ng new test` it works right.
When I use `npx -p @angular/cli ng new test` it creates a v14.2 project. I expected when i skip the version it will use the global or the latest version. But I have no global version installed. Very strange.

Thanks for your help!

**Comment by alan-agius4** [comment]
> `npx -p @angular/cli ng new test` it creates a v14.2 project. I expected when i skip the version it will use the global or the latest version. But I have no global version installed. Very strange.
> 
> Thanks for your help!

That’s because you are using a the `-p` flag.  This flag causes not to resolve and download `@latest`.

Not using that flag, will cause the expected behaviour.
