### ISSUE TITLE
Each ng command doesn't have feedback

### ISSUE THREAD

**Issue by m44rt3np44uw** [angular/angular-cli#2426]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Mac OS X Sierra 10.12

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

node v6.7.0
npm 3.10.8

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

After installing each command doesn't have any feedback. Nothing is returned to the terminal. Terminal recording from Asciinema https://asciinema.org/a/650wdwkyucohugixdfoyyy1w9 

[![asciicast](https://asciinema.org/a/650wdwkyucohugixdfoyyy1w9.png)](https://asciinema.org/a/650wdwkyucohugixdfoyyy1w9)

### The log given by the failure.
> Normally this include a stack trace and some more information.

None given.

### Mention any other details that might be useful.

Tried to install it with sudo.
Reinstalled node.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rolandoldengarm** [comment]
I think you have to wait a bit longer, it just seems to be doing stuff.

**Comment by m44rt3np44uw** [comment]
I don't think that's the problem. Yesterday I waited around 15 minutes.

**Comment by andolf** [comment]
+1 on this issue. Can't get it running for whatever reason and it's driving me nuts.

**Comment by m44rt3np44uw** [comment]
@andolf Somehow I'm glad to hear I'm not the only one.

Below proof that I've been waiting 45 minutes.

[![asciicast](https://asciinema.org/a/7gfl3t4glr2a8uglt783uxju3.png)](https://asciinema.org/a/7gfl3t4glr2a8uglt783uxju3)

**Comment by m44rt3np44uw** [comment]
Small update, found out `sudo ng` is working.

I installed node & npm via brew.

[![asciicast](https://asciinema.org/a/dh95ogre8c2s5th94i6w9wdg0.png)](https://asciinema.org/a/dh95ogre8c2s5th94i6w9wdg0)

**Comment by jcheung0** [comment]
having the same issue I can no longer run any of the ng commands without sudo

**Comment by jtymes** [comment]
I had a very similar issue on OSX and this was due to having an issue with Watchman. Maybe that's causing an issue here?
I got the fix from https://github.com/facebook/watchman/issues/371:
`launchctl unload ~/Library/LaunchAgents/com.github.facebook.watchman.plist`

**Comment by filipesilva** [comment]
You seem to have some npm-related problems on your system. 

I'm sorry I can't help you more, but this problem doesn't seem related to the CLI itself.

**Comment by m44rt3np44uw** [comment]
@jtymes Thanks! This solved my problem. also, to be sure, I reinstalled watchman via brew.
