### ISSUE TITLE
Disable some css transformations (such as inset)

### ISSUE THREAD

**Issue by BojanKogoj** [angular/angular-cli#24275]
### Command

build

### Description

When building our project there seems to be some css optimizations we don't want. Specifically, this code will get optimized
```css
top: 0;
right: 0;
bottom: 0;
left: 0;
```
into 
```css
inset: 0;
```

This doesn't work on some [older browsers](https://caniuse.com/?search=inset), and breaks our UI completely. Seems like [this isn't done by SCSS](https://github.com/sass/dart-sass/issues/1613), and I can't find a way to disable it. Changing .browserslistrc doesn't seem to have an effect.

### Describe the solution you'd like

A way to disable some transformations.

**Comment by alan-agius4** [comment]
Hi @BojanKogoj, 

Can you please share the output of `ng version`, and your browserslist configuration?

**Side note** all the browsers that [Angular officially supports](https://angular.io/guide/browser-support#browser-support) do support inset.

**Comment by BojanKogoj** [comment]
```
$ ng version

     _                      _                 ____ _     ___   
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|  
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |   
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |   
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|  
                |___/
    

Angular CLI: 14.2.3
Node: 14.15.0
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 14.2.2
... animations, cdk, common, compiler, compiler-cli, core, form
s
... language-service, localize, platform-browser
... platform-browser-dynamic, router, youtube-player

Package                         Version
---------------------------------------------------------      
@angular-devkit/architect       0.1402.3
@angular-devkit/build-angular   14.2.3
@angular-devkit/core            14.2.3
@angular-devkit/schematics      14.2.3
@angular/cli                    14.2.3
@schematics/angular             14.2.3
ng-packagr                      14.3.0
rxjs                            7.5.6
typescript                      4.8.3
```

.browserslistrc
```
> 0.5%
last 2 versions
Firefox ESR
not dead
not IE 9-11 # For IE 9-11 support, remove 'not'.
```
But I've tried to change last version, no change. Our issue came from iPhone 11 pro (iOS 14), which seems is no longer supported?

**Comment by alan-agius4** [comment]
Indeed IOS 14 is no longer officially supported. However, adding `ios_14` to the browserslist configuration will generate the expected CSS.

styles.bed628adee984d5d.css: 
```css
*{top:0;right:0;bottom:0;left:0}
```

**Comment by BojanKogoj** [comment]
Unfortunately it doesn't work for some reason. If I use `ios_14`, I get
```
An unhandled exception occurred: Unknown browser query `ios_14`. Maybe you are using old Browserslist or made typo in query.
```
If I use `ios_saf 14` it will build but still use `inset`.

**Comment by alan-agius4** [comment]
It was supposed to be `ios 14` (without the underscore), although `ios_saf 14` does result in the same output.

<img width="1342" alt="Screenshot 2022-11-18 at 14 31 08" src="https://user-images.githubusercontent.com/17563226/202716428-2bddea03-3fd5-449e-a2da-777571ac426c.png">

One thing you could try is to re-generate the lock file. Maybe you have some outdated dependencies if the lock file is unmaintained.

```
rm -rf node_modules package-lock.json
npm i
```

**Comment by BojanKogoj** [comment]
You were right; the problem was our UI library was already transforming it. For some reason it wasn't transformed for storybook, but was transformed when building library.
