### ISSUE TITLE
Unmet peer dependencies after installing Bootstrap 3.3.7, but it works

### ISSUE THREAD

**Issue by jorgeas80** [angular/angular-cli#2427]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.7.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

ng new myapp
npm install --save bootstrap

### The log given by the failure.
> Normally this include a stack trace and some more information.

├── UNMET PEER DEPENDENCY @angular/common@2.0.0
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0
├── UNMET PEER DEPENDENCY @angular/core@2.0.0
├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
└── bootstrap@3.3.7 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.

### Mention any other details that might be useful.

Added this to angularcli.json apps[0].styles

"../node_modules/bootstrap/dist/css/bootstrap.min.css"

Bootstrap is available for the app, at the end. But those UNMET PEER DEPENDENCY asking for an upper version of some of the angular components bother me. Is there anything broken?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by rolandoldengarm** [comment]
Must be something else. Bootstrap does not have any dependencies on angular.
Try clearing your node_modules and run "npm install" again.

**Comment by jorgeas80** [comment]
With a fresh new install (starting with ng new) keeps happening. The same message.

Versions:

angular-cli: 1.0.0-beta.16
node: 6.7.0
npm: 3.10.3

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2387.
