### ISSUE TITLE
Support `--no-browsers` command line flag in karma builder

### ISSUE THREAD

**Issue by ersimont** [angular/angular-cli#24288]
### Command

test

### Description

I often prefer to run tests using Karma's `/debug.html`, instead of letting it auto-run. I usually set `browsers: []` in `karma.conf.js`, so that it doesn't auto-lunch a new browser. Instead I navigate to `/debug.html` myself.

Karma has a command line flag for this: [`--no-browsers`](https://karma-runner.github.io/6.4/config/configuration-file.html#browsers:~:text=%2D%2Dno%2Dbrowsers). When I try to use it I get this error:

```
$ ng test ng-core --no-browsers
Error: Schema validation failed with the following errors:
  Data path "/browsers" must be string.
```

### Describe the solution you'd like

Since Angular 15 no longer scaffolds `karma.conf.js`, it would be great to be able to use the [`--no-browsers`](https://karma-runner.github.io/6.4/config/configuration-file.html#browsers:~:text=%2D%2Dno%2Dbrowsers) command line flag, so I don't need to keep my entire config file just to modify `browsers`.

**Comment by alan-agius4** [comment]
Thanks for this request. 

However this currently do not fall in our roadmap.
