### ISSUE TITLE
Update Angular 14 to 15:  ERROR TypeError: Cannot read properties of null (reading 'flags')

### ISSUE THREAD

**Issue by musheghz** [angular/angular-cli#24289]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

core.mjs:9235 ERROR TypeError: Cannot read properties of null (reading 'flags')
    at hasStylingInputShadow (core.mjs:18077:19)
    at stylingFirstUpdatePass (core.mjs:17529:13)
    at checkStylingProperty (core.mjs:17440:9)
    at Module.ɵɵclassProp (core.mjs:17350:5)
    at MatFormField_Template (form-field.mjs:26:99)
    at executeTemplate (core.mjs:12190:9)
    at refreshView (core.mjs:12075:13)
    at detectChangesInternal (core.mjs:13352:9)
    at ViewRef$1.detectChanges (core.mjs:13824:9)
    at MatFormField.ngAfterViewInit (form-field.mjs:593:33)

### Minimal Reproduction

ng s 
 "dependencies": {
    "@ag-grid-community/all-modules": "*",
    "@ag-grid-community/angular": "*",
    "@ag-grid-community/core": "*",
    "@angular-material-components/datetime-picker": "^8.0.0",
    "@angular/animations": "15.0.0",
    "@angular/cdk": "15.0.0",
    "@angular/common": "15.0.0",
    "@angular/compiler": "15.0.0",
    "@angular/core": "15.0.0",
    "@angular/flex-layout": "10.0.0-beta.32",
    "@angular/forms": "15.0.0",
    "@angular/material": "15.0.0",
    "@angular/material-moment-adapter": "15.0.0",
    "@angular/platform-browser": "15.0.0",
    "@angular/platform-browser-dynamic": "15.0.0",
    "@angular/router": "15.0.0",
    "@ngrx/effects": "12.0.0",
    "@ngrx/router-store": "13.2.0",
    "@ngrx/store": "12.0.0",
    "@ngrx/store-devtools": "12.0.0",
    "@ngx-translate/core": "13.0.0",
    "@swimlane/dragula": "3.8.0",
    "@swimlane/ngx-charts": "9.0.0",
    "@swimlane/ngx-datatable": "^20.1.0",
    "@swimlane/ngx-dnd": "8.1.2",
    "@types/prismjs": "1.16.1",
    "ag-grid-angular": "^27.0.1",
    "ag-grid-community": "^27.0.1",
    "angular-calendar": "0.28.16",
    "angular-in-memory-web-api": "0.11.0",
    "angular2-csv": "~0.2.5",
    "angular2-moment": "1.9.0",
    "chart.js": "2.9.3",
    "chartjs-plugin-annotation": "0.5.7",
    "classlist.js": "1.1.20150312",
    "d3": "5.16.0",
    "date-fns": "1.30.1",
    "flag-icon-css": "3.5.0",
    "hammerjs": "^2.0.8",
    "lodash": "4.17.19",
    "moment": "2.27.0",
    "ng2-charts": "2.3.2",
    "ng2-file-upload": "1.4.0",
    "ng2-tooltip-directive": "2.10.3",
    "ngrx-store-freeze": "0.2.4",
    "ngx-color-picker": "8.2.0",
    "ngx-cookie-service": "2.4.0",
    "ngx-mat-select-search": "3.3.0",
    "ngx-moment": "3.5.0",
    "ngx-order-pipe": "2.0.4",
    "ngx-trend": "6.1.1",
    "perfect-scrollbar": "1.5.0",
    "postcss": "8.3.4",
    "postcss-scss": "4.0.0",
    "prismjs": "1.20.0",
    "rxjs": "6.6.0",
    "web-animations-js": "2.3.2",
    "zingchart-angular": "1.0.0",
    "zone.js": "~0.11.4"
  },

### Your Environment

```text
Angular CLI: 15.0.0
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 15.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@angular/flex-layout            10.0.0-beta.32
@schematics/angular             15.0.0
rxjs                            6.6.0
typescript                      4.9.3
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by musheghz** [comment]
I see problem in the browser console. app is served

**Comment by alan-agius4** [comment]
@musheghz without a reproduction we are unable to look into this any further.
