### ISSUE TITLE
esbuild - do not ignore d.ts files, please

### ISSUE THREAD

**Issue by e-oz** [angular/angular-cli#24316]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular/compiler-cli 15.0.1

### Description

Please do not ignore d.ts files in source code - esbuild fails because of it.

### Minimal Reproduction

ng build

### Your Environment

```text
all the latest versions of Angular libs
node 19
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by e-oz** [comment]
it's a bug, not a feature request, so reproduction is needed, sure. 
Right now I have a pretty busy day, sorry for the sloppy bug report.
I'll add repro tomorrow, I've posted it in hope that maybe you've added "*.d.ts" filter on purpose and then you would know what I'm talking about instantly, without repro :) 

Right now I can only show a folder in the project where this issue was found, later I'll add repro.
<img width="835" alt="Screenshot 2022-11-24 at 10 23 31" src="https://user-images.githubusercontent.com/526352/203746690-254c6982-37f5-4059-bd9a-91cb4001053f.png">

Error message:
```
✘ [ERROR] [plugin angular-compiler] File 'libs/monaco-editor/src/lib/editor.api.d.ts' is missing from the TypeScript compilation.

    libs/monaco-editor/src/lib/interfaces.ts:1:14:
      1 │ export * from './editor.api.d';
        ╵               ~~~~~~~~~~~~~~~~

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.
```

**Comment by e-oz** [comment]
Forgot to say: non-esbuild version works fine.

**Comment by e-oz** [comment]
While build a reproduction build, I found the workaround and what caused the problem - `export * from...`
And it's actually better to remove it from my code :)
