### ISSUE TITLE
Fail to build the app configured with Less (browser-esbuild issue)

### ISSUE THREAD

**Issue by Rub0013** [angular/angular-cli#24329]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I get "No loader is configured for '.less'" error while trying to build the app after updating  the '@angular-devkit/build-angular:browser' builder to new experimental '@angular-devkit/build-angular:browser-esbuild'

### Minimal Reproduction

Build Angular app (configured with Less) in Nx workspace.

`nx build <appName>`

### Your Environment

```text
15.2.1
```

**Comment by alan-agius4** [comment]
Thanks for opening the issue but this is expected as LESS is not yet supported in the experimental Esbuild builder.

Currently only Sass and CSS are supported. Support for Less will be added at a later stage.
