### ISSUE TITLE
Export standalone array from a library doesn't work in application

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular-cli#24327]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm building a library with the angular-cli and export an array of standalone components:

```ts
export const libImports = [FooComponent, BarComponent]
```

When installing and consuming the export via npm:

```ts
import { libImports } from '@mylib/name';

@Component({
  standalone: true,
  imports: [libImports]
})
export class AppComponent {}
```

I get the error: 
```
Value at position 4 in the AppComponent.imports of AppComponent is not a class
  Value is a reference to 'libImports'.

 export declare const libImports: (typeof FooComponent | typeof BarComponent)[];
```

### Minimal Reproduction

Create a library and do the same.

### Your Environment

```text
v14, v15
```

**Comment by JoostK** [comment]
Please follow https://github.com/angular/angular/issues/48089. Closing as duplicate.
