### ISSUE TITLE
New project generates incorrect routing export/import name with --routing

### ISSUE THREAD

**Issue by brandonroberts** [angular/angular-cli#2433]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
OSX Yosemite

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.16
node: 5.12.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Run `ng new testapp --routing`

The `app-routing.module.ts` file is generated with  `export class TestappRoutingModule { }` instead of `export class AppRoutingModule { }`

The `app.module.ts` import is incorrect for the routing file.

```
import { TestappRoutingModule } from './testapp-routing.module';
```
instead of 
```
import { AppRoutingModule } from './app-routing.module';
``` 

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by hantsy** [comment]
I encountered this same issue under Windows 10 64bit.
