### ISSUE TITLE
Browserslist unique for each project

### ISSUE THREAD

**Issue by metaloha** [angular/angular-cli#24339]
### Command

build

### Description

An Angular project with some shared functionality between multiple front-end applications (ex. `./projects/full-client` and `./projects/lite-client`) currently needs to be built via lowest common denominator. The "lite" client is targeting older browsers (like IE11, for example) while the "full" client targets evergreen browsers.

As it stands now, the root `.browserslistrc` file needs to include `ie11` in the list of supported browsers so the "lite" client will compile properly, but that forces the "full" client to compile for IE11 as well.

### Describe the solution you'd like

Each project folder should be able to specify their own `.browserslistrc` file that overrides a root-level one.

### Describe alternatives you've considered

We've moved shared functionality to a stand-alone library project, and the two front-ends are separate Angular projects. We'd love to be able to put all three of these under a single project folder and have `npm run build` just work.

**Comment by alan-agius4** [comment]
Each project does allow specifying a `.browserslist` configuration file. 

As a side note, IE 11 is no longer supported.

**Comment by metaloha** [comment]
I'm aware IE 11 isn't supported by current versions; it was just an example.

`.browserslist` or `.browserslistrc`? The documentation states that the file needs to be in the root folder (as I understand it), so perhaps the feature request is more of a documentation update than a build change.

**Comment by metaloha** [comment]
🤔 I guess that's what I mean. Those are referred to as applications (`ng new application`), and while the folder is usually `./projects`, it might not be (I usually rename it to either `./applications` or `./activities`, depending on the project). In the case of a singular Angular application, would `.browserslistrc` go in the root folder or `./src` - which one is considered the "project" folder?

Some clarification around that would be great. Maybe it needs to be located wherever a `tsconfig.app.json` file is?

**Comment by alan-agius4** [comment]
The project directory is the root directory  where the project is located which is also defined in `angular.json`

In case it a single project workspace the project directory is the root level directory in the workspace (`./`), in the case of a multi project repo the project directory is (`./project/<project-name>`).

The `./src` is the source directory of a project.

**Comment by metaloha** [comment]
The terminology is confusing. You're saying that a workspace is a project if there is a `./src` folder in the root, and applications in the `angular.json.newProjectRoot` folder are also projects. Can we link these ideas by noting that a project root is where the `tsconfig.app.json` file is (I don't think that's stated anywhere)? And maybe renaming or creating an alias for `ng new project` instead of `ng new application` so that the terminology is consistent would be a good idea (otherwise we should be talking about application roots, not project roots).

**Comment by alan-agius4** [comment]
There is an entire section dedicated to explained the workspace and project structure.

https://angular.io/guide/file-structure

**Comment by metaloha** [comment]
I don't think we're going to get on the same page here. I'm not explaining myself very effectively. I found it confusing, but now I know what it does, problem solved. Thanks for your time and patience.
