### ISSUE TITLE
'update' command using the last stable version introduces unnecessary node version requirements 

### ISSUE THREAD

**Issue by Jamesmcgeachie** [angular/angular-cli#24336]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If I try to run the `ng update` command with an old local version of the CLI, the CLI attempts to first acquire the 'latest stable version' before running `ng update`.

This creates a requirement for my environment to meet the dependencies of the latest version of the CLI.

This is a problem in some cases if the environment in question is locked to the needs of the version we're targetting. In this case, I'm targeting an update to ng11. However, ng15 requires node ^14.20. 

In the enterprise environment I'm working on we only have certain authorized node versions, none of which are ^14.20.

It seems undesirable to force a user of the CLI to update their environment to use higher versions than the dependencies of the Angular version they wish to update to. 

### Minimal Reproduction

- Have old CLI installed locally (e.g. cli@10.0)
- Have node version < 14.20 loaded 
- run `ng update @angular/core@11.0`
- See error requiring Node ^14.20

### Your Environment

```text
Sorry I can't share this as it's private
```

**Comment by alan-agius4** [comment]
Hi, 

This has been solved in recent versions. As a workaround you can use the `NG_DISABLE_VERSION_CHECK` environment variable. 

```
NG_DISABLE_VERSION_CHECK=1 ng update...
```
