### ISSUE TITLE
ng build always asks for ng completion

### ISSUE THREAD

**Issue by Heimo001** [angular/angular-cli#24342]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

Running `ng build` always asks for `ng completion` which causes my pipline to fail.

I've tried to add it to the Dockerfile, but it's still prompting and it's not possible to skip that.
In my opinion, there should be a global CI mode, not just for the analytics stuff, but for all interactive prompts.

### Minimal Reproduction

- run `ng build`

### Exception or Error

```text
? Would you like to enable autocompletion? This will set up your terminal so pressing TAB while typing Angular CLI 
commands will show possible options and autocomplete arguments. (Enabling autocompletion will modify configuration files
```

### Your Environment

```text
Angular CLI: 14.2.6
Node: 16.14.2
Package Manager: npm 8.5.0 
OS: linux x64
```

### Anything else relevant?

CLI / Container / CI

**Comment by alan-agius4** [comment]
Hi @Heimo001, 

We do have checks for CI. The prompt is not shown in cases where the terminal is not interactive.  Logic here: https://github.com/angular/angular-cli/blob/856720b913ec1ba82b96db2d3a61628cb3795f11/packages/angular/cli/src/utilities/tty.ts#L21 and https://github.com/angular/angular-cli/blob/4fa5b526e53fb9b142295ef361c3709151aa17da/packages/angular/cli/src/utilities/completion.ts#L137-L140

Is your CI setting the stdout as non TTY and/or the CI environment variable correctly?

**Comment by Heimo001** [comment]
> Hi @Heimo001,
> 
> We do have checks for CI. The prompt is not shown in cases where the terminal is not interactive. Logic here:
> 
> https://github.com/angular/angular-cli/blob/856720b913ec1ba82b96db2d3a61628cb3795f11/packages/angular/cli/src/utilities/tty.ts#L21
> 
> and
> https://github.com/angular/angular-cli/blob/4fa5b526e53fb9b142295ef361c3709151aa17da/packages/angular/cli/src/utilities/completion.ts#L137-L140
> 
> Is your CI setting the stdout as non TTY and/or the CI environment variable correctly?

Thanks for your answer alan, that's right, just without the interactive shell it works. 
But what can I do using VSCode `.devcontainer` in combination with npm `scripts`. 
In VSCode there is that play button next to the scripts defined in the `package.json`, running these scripts opens a terminal running the script and there it is again. 
Is there a way to run the commands non-interactive?
![image](https://user-images.githubusercontent.com/11391267/204516005-3a3f6d51-1179-4a19-9a81-3487b19fb25a.png)

**Comment by alan-agius4** [comment]
You can set the `NG_FORCE_TTY` environment variable to `false` or `0`.

See https://code.visualstudio.com/remote/advancedcontainers/environment-variables#_option-1-add-individual-variables

**Comment by Heimo001** [comment]
> You can set the `NG_FORCE_TTY` environment variable to `false` or `0`.
> 
> See https://code.visualstudio.com/remote/advancedcontainers/environment-variables#_option-1-add-individual-variables

That's exactly what I meant.
Thank you!

**Comment by alan-agius4** [comment]
Closing as per above
