### ISSUE TITLE
Live reload does not reflect all code changes

### ISSUE THREAD

**Issue by mattbodman** [angular/angular-cli#24354]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

Several of us working on the same project are encountering an issue where `ng serve` will reload on code changes as expected but not always reflect _all_ code changes.  The app will typically crash on a "missing" code block because it cannot find said block.  However, the block DOES exist, but may have just been added amongst other changes.  The workaround is to modify the block again (by adding a comment or console.log), forcing a fresh reload.  Invariably, this will rectify the issue.
We upgraded from v11 to v14 a few months ago and it is believed the issue has been introduced since then.  At that time, however, we started restructuring the app by using modules and lazy loading, in case that's relevant somehow.
I have been using Angular for many years and have not encountered this issue before.

### Please provide a link to a minimal reproduction of the bug

The error in the screenshot below was produced by adding a new method to this demo repo [https://github.com/mattbodman/reload-issue](https://github.com/mattbodman/reload-issue)

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/1994501/205180260-9144948a-bb5d-4954-a161-5bdd576ded75.png">

Whilst the screenshot shows the project successfully compiling after the error, our project frequently does not.  For some reason, the changes made to certain files (often the same files) are overlooked.

### Please provide the exception or error you saw

```true
The browser dev console will typically throw an error like:

`error TS2551: Property 'XYZ' does not exist on type 'MyService'. Did you mean 'XYZZ'?`

...even when the property absolutely DOES exist.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.9                                        
Node: 16.17.1                                              
Package Manager: npm 8.19.2                                
OS: win32 x64                                              
                                                           
Angular: 14.2.10                                           
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic   
... platform-server, router                                
                                                           
Package                         Version                    
---------------------------------------------------------  
@angular-devkit/architect       0.1402.9                   
@angular-devkit/build-angular   14.2.9                     
@angular-devkit/core            14.2.9                     
@angular-devkit/schematics      14.2.9                     
@angular/cdk                    14.2.7                     
@angular/cli                    14.2.9                     
@angular/language-service       14.2.2                     
@schematics/angular             14.2.9                     
rxjs                            7.5.7                      
typescript                      4.6.4                      
webpack                         5.75.0
```

**Comment by alan-agius4** [comment]
@mattbodman unfortunately without a reproduction this is not actionable.

**Comment by mattbodman** [comment]
@alan-agius4 thank you.  I've added more information.  Please let me know if I can provide anything else.  This is a real issue which we are keen to have resolved.

**Comment by alan-agius4** [comment]
Hi @mattbodman, 

Thanks for the reproduction. However, I am finding some trouble to understand how to reproduce this issue even with the reproduction.

What are the exact steps that I need to follow for the problem to occur?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by mattbodman** [comment]
@alan-agius4 thanks for you time.  Sadly, the issue is intermittent and likely caused by a race condition with multiple files saving simultaneously causing the Angular live reload to miss some changes.  A very hard, perhaps impossible, issue to reproduce.  Still an issue though and a real time-waster.  Is there an option, like there is with other live reload software (eg NodeMon), to add a delay to the reload to debounce changes?  This can help with these kinds of issues
