### ISSUE TITLE
Angular apps not working in Safari v15 due to `ReferenceError`

### ISSUE THREAD

**Issue by Meet1202** [angular/angular-cli#24355]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When we open angular.io website in safari browser in mac then it giving blank page and if we do refresh that page than also it's giving blank page and when we open inspect element from developer open in safari browser and do refresh that page then it open perfectly so it's an issue I have provided screenshot.

- This when I open angular.io link in Safari browser in Mac.
![Screenshot 2022-11-30 at 6 37 28 PM](https://user-images.githubusercontent.com/41354599/204804800-e682b1c1-e8e3-4f6e-b89e-128526cbb017.png)

- This when I open inspect element of safari browser and still website is not working.
![Screenshot 2022-11-30 at 6 39 15 PM](https://user-images.githubusercontent.com/41354599/204805119-0db38b62-6f5b-4e03-a382-2f1cbb7da64d.png)

- And at last this after opening Inspect element I refresh the page then website is working properly.
![Screenshot 2022-11-30 at 6 39 27 PM](https://user-images.githubusercontent.com/41354599/204805558-5cea7fb4-a1d6-44f9-af86-bd3750bfbbeb.png)

### Please provide a link to a minimal reproduction of the bug

https://angular.io

**Comment by yjaaidi** [comment]
In my understanding, this happened specifically with this component because it's using animations + content projection.
- Animations are causing the static block.
- Content projection causes the static block to access the `notification_component_c0 = ['*']` variable (outside the class) which breaks WebKit parser's scope analysis.
... but I might be totally wrong 🙃


The hardest thing here is to define what are other "similar" situations 😅

**Comment by albanx** [comment]
Had a similar issue on Safari Mobile on the iphone. I was able to fix only by reset the browserlistrc to
```
> 1%
last 2 versions
not ie > 0
not ie_mob > 0
not dead
```

**Comment by muratcanoguzhan** [comment]
> Had a similar issue on Safari Mobile on the iphone. I was able to fix only by reset the browserlistrc to
> 
> ```
> > 1%
> last 2 versions
> not ie > 0
> not ie_mob > 0
> not dead
> ```

While I was upgrading to Angular v15 browserlistsrc was deleted automatically.
