### ISSUE TITLE
Schematics progress reporting

### ISSUE THREAD

**Issue by dgp1130** [angular/angular-cli#24361]
### Command

generate

### Description

From http://b/188066584.

For long running schematics, it can sometimes be unclear if the schematic is stalled or just taking a long time. A loading spinner might be useful to communicate current status.

### Describe the solution you'd like

More comprehensive progress reporting would be very cool. I doubt we could do a proper progress bar, but even just a spinner which updates every frame would at least validate that the program is stalled in an infinite loop.

### Describe alternatives you've considered

I think schematics could implement this themselves via the logger to a certain extent, but it might get a bit tricky. Not sure if a loading spinner is feasible at all.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/12479
