### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by asmsk** [angular/angular-cli#2436]
Hi,

it seems at the moment there is a problem installing the CLI on Windows. This happened on a fresh node installation on Windows 7.

C:\Users\Alex>npm install -g angular-cli
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm
 ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
C:\Users\Alex\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\angular-cli\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Alex\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\Alex\AppData\Roaming\npm\node_modules\.staging\abbrev-1ea80297
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Alex\AppData\Roaming\npm\node_modules\.staging\abbrev-1ea80297' -> 'C:\Users\Alex\AppData\Roaming\npm\
node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Alex\AppData\Roaming\npm\node_modules\.staging\abbrev-1ea80297' -> 'C:\Users\Alex\AppData\Roaming\npm\
node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Alex\npm-debug.log
npm ERR! code 1

C:\Users\Alex>

**Comment by cclelio** [comment]
Same problem on Windows 10 x64

**Comment by JanStureNielsen** [comment]
@asmsk -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

Upgrade to Node 6:

  http://stackoverflow.com/questions/39812448/angular-cli-installation-failure

**Comment by asmsk** [comment]
@cclelio and @JanStureNielsen: Thank you. After upgrading to the newest node version and uninstalling before installing globally everything worked out fine. Thanks.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1190

**Comment by tech-tron** [comment]
@cclelio no clue why that worked, but it did and that's awesome
