### ISSUE TITLE
ng build always includes html/head tags, even when removed from src/index.html

### ISSUE THREAD

**Issue by lhanneman** [angular/angular-cli#24379]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11.2.19

### Description

When running `ng-build`, the generated index.html (dist/index.html) always includes the parent `<html>` and `<head>` tags around the `<app-root>`. Previously (this worked in 11.2.9) one could remove the `<html>` and `<head>` tags from src/index.html and they would not be included in dist/index.html on build. This is helpful when integrating an angular app with another (such as ASP.NET MVC) and the parent HTML/layout will already exist.

### Minimal Reproduction

1. Create a new angular 15 application using the latest CLI (or any CLI version after 12)
2. Update src/index.html to include only `<app-root></app-root>`
3. Run `ng build`

### Exception or Error

The output index.html in /dist contains `<html>`, `<head>`, and `<body>` tags, along with the generated scripts.

When following those same steps with version 11.2.19 of the CLI, the output in /dist will contain only `<app-root>` and the generated scripts.

### Your Environment

```text
Angular CLI: 15.0.2
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 15.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@schematics/angular             15.0.2
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by alan-agius4** [comment]
This is caused by the [critters](https://github.com/GoogleChromeLabs/critters/tree/main/packages/critters/src) package which is used to inline critical css which will always output a complete HTML page. 

In your case since the index file is not a complete html page you can disable this optimisation. See: https://angular.io/guide/workspace-config#styles-optimization-options
