### ISSUE TITLE
bug(cdk): Builds fail with cdk@15.0.1 due to parse5 library error

### ISSUE THREAD

**Issue by cskiwi** [angular/angular-cli#24375]
### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.0

### Description

When updating to the latest version: 15.0.1 of cdk, the builds start to fail,

Was introduced in update: https://github.com/angular/components/pull/26086

```
./node_modules/parse5-htmlparser2-tree-adapter/lib/index.js:3:16-52 - Error: Module not found: Error: Package path ./lib/common/doctype is not exported from package <project>\node_modules\parse5 (see exports field in <project>\node_modules\parse5\package.json)

./node_modules/parse5-htmlparser2-tree-adapter/lib/index.js:6:4-37 - Error: Module not found: Error: Package path ./lib/common/html is not exported from package <project>\node_modules\parse5 (see exports field in <project>\node_modules\parse5\package.json)

./node_modules/critters/dist/critters.mjs:38:2-14 - Error: export 'default' (imported as 'parse5') was not found in 'parse5' (possible exports: ErrorCodes, Parser, Token, Tokenizer, TokenizerMode, defaultTreeAdapter, foreignContent, html, parse, parseFragment, serialize, serializeOuter)

./node_modules/critters/dist/critters.mjs:55:9-25 - Error: export 'default' (imported as 'parse5') was not found in 'parse5' (possible exports: ErrorCodes, Parser, Token, Tokenizer, TokenizerMode, defaultTreeAdapter, foreignContent, html, parse, parseFragment, serialize, serializeOuter)
```

### Reproduction

Steps to reproduce:
1. update to the latest version of cdk
2. Build

### Expected Behavior

That the build would work

### Actual Behavior

Build is crashing

### Environment

- Angular: 15.0.1
- CDK/Material: 15.0.1
- Browser(s): x
- Operating System (e.g. Windows, macOS, Ubuntu): windows

**Comment by alan-agius4** [comment]
Hi @@cskiwi, 

Can you try to remove the lock file and node_modules and do a fresh installation?

**Comment by cskiwi** [comment]
Hi,

I've removed the lock file and did a fresh installation with the following versions changed:
- @angular/cdk: 15.0.0 -> 15.0.1
- @angular/material: 15.0.0 -> 15.0.1 

I was able to figure out, that this error only happens when I build the "server" for the angular universal side, the normal client seems to build just fine

Ouptut of `ng version` I wasn't able to figure out how get this, because I have a NX workspace. I tried running the alternatives that nx proved, all errored.

**Comment by alan-agius4** [comment]
@cskiwi, without a reproduction it's hard to tell what's wrong. Are you using the official Angular server builder?

**Comment by cskiwi** [comment]
I've tried to recreate in a separate project and wasn't able to reproduce it,

I still think there might be a version mismatch happening within the angular packages, but not giving an problem until some 3th party get's involved. 

So this issue can be closed, but maybe a version tree check might not be a bad thing, if someone can find the energy to do this.
