### ISSUE TITLE
--routing creates no default route

### ISSUE THREAD

**Issue by cre8** [angular/angular-cli#2438]
When you create a fresh project with `--routing` the browser console prints an error:
`Uncaught (in promise): Error: Cannot match any routes: ''`

A minimal project should not create any errors that could confuse the user.
So maybe there should be a component for this route that handles this error or the feature should be disabled if you want to have it as small as possible.

**Comment by wingsuitist** [comment]
As long as you don't add the <router-outlet> you I do not get an error in the current version.
At the moment there are no routes and in app.module.ts the import for the route module refers to a non existing file `import { AppnameRoutingModule } from './Appname-routing.module';`

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2435
