### ISSUE TITLE
Can't load bootstrap scss files

### ISSUE THREAD

**Issue by piernik** [angular/angular-cli#24387]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

I've made upgrade to `angular@15`. In my scss files I import bootstrap files using:
`@import "~bootstrap/scss/variables";`

Now it doesn't want to work giving me error:
```
./src/styles/motywy/dark/index.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @import "~bootstrap/scss/variables";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\styles\libraries\bootstrap-hacks\breadcrumb.scss 1:9  @import
  src\styles\libraries\bootstrap-hacks\index.scss 4:9       @import
  src\styles\libraries\bootstrap.scss 3:9                   @import
  src\styles\libraries\index.scss 1:9                       @import
  src\styles\motywy\common\_imports.scss 1:9                @import
  src\styles\motywy\dark\index.scss 3:9                     root stylesheet
```

### Minimal Reproduction

none

### Your Environment

```text
Angular CLI: 15.0.2
Node: 16.14.0
Package Manager: npm 8.5.3
OS: win32 x64

Angular: 15.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.2
@angular-devkit/build-angular   15.0.2
@angular-devkit/core            15.0.2
@angular-devkit/schematics      15.0.2
@angular/cdk                    15.0.1
@angular/google-maps            15.0.1
@schematics/angular             15.0.2
rxjs                            6.6.7
typescript                      4.8.4
```

bootstrap@5.2.3

**Comment by alan-agius4** [comment]
This is expected. 

> Deprecated support for tilde import has been removed. Please update the imports by removing the ~.
> **Before**
> ```
> @import "~font-awesome/scss/font-awesome";
> ```
>  **After**
> ```
> @import "font-awesome/scss/font-awesome";
> ```

Please see https://github.com/angular/angular-cli/releases/tag/15.0.0 for a complete list of breaking changes.

**Comment by piernik** [comment]
Thanks. I think it should be included on https://update.angular.io/
