### ISSUE TITLE
Bring back environment.ts to new projects

### ISSUE THREAD

**Issue by arambazamba** [angular/angular-cli#24381]
### Command

new

### Description

Not generating environment.ts in new ng 15 projects is a big breaking change. So you are so proud of stand alone components and single file components and you do everything to please React developers. They will still prefere React. But if you go on changing everything Angular developers are used to you will push them away!!!

### Describe the solution you'd like

I want environment.ts and envrionment.prod.ts generated when creating a new project. Or at least have a flag to indicate that I want this to be done

### Describe alternatives you've considered

Create manually or change to React

**Comment by prabh-62** [comment]
Agree with @alan-agius4 that we don't need `environment.ts` files created by default. There should be some mechanism to update content at runtime (like updating backend API from QA to Prod) but that should be coped separately

**Comment by clydin** [comment]
After the release of Angular CLI 15.1, a generation schematic will be available to add environment files for all existing build configurations within a project.
Example usage: `ng generate environments`

**Comment by arambazamba** [comment]
Great job … For simpler apps environment.ts and *.prod.ts was a good & simple solution to provide global vars like api url, … thanks a lot 👍 

I also want to mention that in my opinion and there should be a default simple solution for config and global vars. With the experience of having thought more than 50 Angular classes I can definitely say that „the many boilerplate files“ is not what is confusing people that want to learn Angular. If you want to make it easier for newbie’s take out Observables  and their operators 😜😝😉

**Comment by HCenggel** [comment]
environment.ts is very necessary for novices. The interface addresses of many project development environments and production environments are different.
Too unfriendly for novices.
Articles on the Internet are written according to the default existence of the environment.ts file.
The absence of environment.ts creates doubts for newcomers, who don't know what to do.

**Comment by HCenggel** [comment]
I think the generation of the environments file should be more appropriate to ask when ng new creates the project (just like choosing css scss).

**Comment by hosseinGanjyar** [comment]
> After the release of Angular CLI 15.1, a generation schematic will be available to add environment files for all existing build configurations within a project. Example usage: `ng generate environments`

But I've an **_error_** with this command: 
`Error: A collection and schematic is required during execution.`

**Comment by POORIANSARI** [comment]
After the release of Angular CLI 15.1 and you are using Angular CLI: 15.0.*;
