### ISSUE TITLE
ng test fails to finish when using portable browsers

### ISSUE THREAD

**Issue by cambamf** [angular/angular-cli#24419]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Currently (Angular 13) the way we run our angular tests in our CI system is we use portable versions of the browsers. You can download them here https://portableapps.com/apps/internet/google_chrome_portable. We use portable versions so that we can have multiple versions of the browser on the system and test several different versions by setting CHROME_BIN.
I am trying to upgrade to angular 14, and I am running into an isssue that is only seen when using a portable version of a browser. When you run ng test, the tests run and when they are done, the browser stays open and the command never finishes. The command we are using is ng test --no-watch --no-progress --browser=chrome. This poses and issue in a CI system that waits for the command to finish.
I am sure that this is just a small thing I am missing in the upgrade... If this was an intentional change, what is the preferred way to test across multiple versions of a browser? Multiple VMs? Anyways, thank you for your help with this.

### Please provide a link to a minimal reproduction of the bug

https://github.com/cambamf/AngularTest

### Please provide the exception or error you saw

```true
The browser never closes so the command never finishes. I started to see this with the upgrade to angular 14.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node: 16.18.1
Angular cli: 14.2.10
```

**Comment by alan-agius4** [comment]
Likely this is caused by a change that we no longer forcefully exit the process. From the looks of it the the Browser process is not being killed even though the `--no-watch` option is being used. This doesn't seem to be an issue caused by the CLI but more of a issue of the portable browsers, since this works for normal browsers, puppeteer and other services.

For multiple browsers version testing we typically use and suggest services like BrowserStack and Saucelabs.

**Comment by cambamf** [comment]
@alan-agius4 Thank you! That is very helpful! So that I can understand more and try and track down the issue on the browser side, can you point to me where in angular it was forcefully exiting the process? Obviously it wont be in the development, but if you could show me where it was happening in the 13 branch... I have been looking through pull requests and haven't been able to find the change...

**Comment by cambamf** [comment]
Also, I am looking more into browserstack, so thank you for the suggestion!

**Comment by alan-agius4** [comment]
Here is the PR that removed the forceful exiting https://github.com/angular/angular-cli/pull/23166/

**Comment by cambamf** [comment]
Perfect! Thank you so much! I will keep hunting down why the browser isn't closing! Thank you for your help and being very responsive!!

**Comment by simonchn160** [comment]
Were you able to find a solution to this? My unit tests are still not exiting in Continuous Integration even though I have the --no-watch flag in place
