### ISSUE TITLE
angular-in-memory-web-api undefined issue

### ISSUE THREAD

**Issue by ericel** [angular/angular-cli#2442]
angular-in-memory-web-api undefined issue following the Heroes tutorial.

**Comment by gelliott181** [comment]
This is the Git repo for the Angular CLI, not Angular. If you're using the CLI in place of the provided Angular 2 Quickstart project, you need to install dependencies not required by the CLI, such as `"angular-in-memory-web-api": "~0.1.1",` which is line 24 of the package.json for the base quickstart project, and listed in the package.json file on the [first page of the tutorial](https://angular.io/docs/ts/latest/quickstart.html).

**Comment by filipesilva** [comment]
Heya @ericel, I feel @gelliott181 has addressed your issue quite thoroughly, so I'll close it. Cheers @gelliott181 and thank you!
