### ISSUE TITLE
Is this where I should report electrum wallet issue? 

### ISSUE THREAD

**Issue by notinsync** [angular/angular-cli#2443]
When I send coin from one of my electrum wallets to another, according to blockchain it goes to a wallet with a large balance, much larger than I've ever had. Electrum page said to report bugs here. Not sure if this is a bug or not. I no longer have enough coin to post as a new member on bitcointalk. Is it possible someone hijacked this wallet? It's never been used for any purchases. It was created new and I simply moved coin from one existing wallet to the new one. Now my coin is in someone else's wallet!
 
> Please provide us with the following information:
> ---------------------------------------------------------------

win 7 OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment]
The Electrum page does not send you to the Angular-CLI for bug reports, it links directly to their Github on their [community page](https://electrum.org/#community). I highly recommend closing this issue and reopening it in the proper GitHub repo, otherwise you'll receive no help here.

**Comment by notinsync** [comment]
ok thank you
