### ISSUE TITLE
Branch coverage is broken after upgrading to angular 14

### ISSUE THREAD

**Issue by pain0486** [angular/angular-cli#24448]
### Command

test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

^13.3.11

### Description

After upgrading to angular 14 all tests pass, however the branch coverage reporting is reporting weird coverage issues around constructors similar to issues I have found when users were upgrading to angular 4 found [here](https://github.com/angular/angular-cli/issues/5526#issuecomment-324429322)

here are some examples
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/11378706/208153697-c152b913-70ce-4ab7-b043-c355ba7934ef.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/11378706/208153702-871fc7ca-16ab-4c95-ac65-c6cb6afc912d.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/11378706/208153706-74a1d679-a116-4f5d-96f2-2f7334c1c229.png)

### Minimal Reproduction

ng test --browsers=ChromeHeadless --no-watch --progress=false
results in 87.47% coverage where it was 100% before doing the upgrade
=============================== Coverage summary ===============================
Statements   : 100% ( 831/831 )
Branches     : 87.47% ( 433/495 )
Functions    : 100% ( 228/228 )
Lines        : 100% ( 812/812 )

### Exception or Error

```text
No errors
```

### Your Environment

```text
Angular CLI: 14.2.10
Node: 18.12.1 (Unsupported)
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@angular/flex-layout            14.0.0-beta.41
@angular/material               14.2.7
@schematics/angular             14.2.10
rxjs                            7.5.6
typescript                      4.6.4
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by pain0486** [comment]
issue can be resolved by removing    
 "emitDecoratorMetadata": true,
from the tsconfig.json file

source: https://github.com/istanbuljs/istanbuljs/issues/70#issuecomment-1340864994

**Comment by frankred** [comment]
@pain0486 but I have no `emitDecoratorMetadata` in my tsconfig.json.
