### ISSUE TITLE
Angular CLI is not installing

### ISSUE THREAD

**Issue by gitHubUser151** [angular/angular-cli#24452]
### Command

version

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

CLI is not installing. Gives following output.
Could you please take a look?

C:\WINDOWS\system32>npm install -g @angular/cli
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

changed 232 packages, and audited 233 packages in 23s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\WINDOWS\system32>ng help
'ng' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>node -v
v18.12.1

### Minimal Reproduction

npm install -g @angular/cli

### Exception or Error

npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

### Your Environment

```text
Microsoft Windows [Version 10.0.19045.2364]
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
