### ISSUE TITLE
Cannot install angular-cli

### ISSUE THREAD

**Issue by Pichchan9k** [angular/angular-cli#2445]
> Please provide us with the following information:
> ---------------------------------------------------------------
Error when install angular-cli "sudo npm install -g angular-cli"

### OS?
>Linux (Ubuntu 16.04 LTS)

### Versions.
> angular-cli: 1.0.0-beta.16
node: 6.7.0
npm: 3.10.3
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? ete? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/bin/ng -> /usr/lib/node_modules/angular-cli/bin/ng

> node-zopfli@2.0.1 install /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

>node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@6.7.0 (node-v48 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/pichchan9k/.node-gyp/6.7.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/.node-gyp"
make: Entering directory '/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
make: *** No rule to make target '../.node-gyp/6.7.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-36-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64"
gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/angular-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.0-36-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/angular-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/lib/node_modules/angular-cli/node_modules/node-zopfli
node-pre-gyp ERR! node -v v6.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v48-linux-x64' (1)
npm WARN install:node-zopfli@2.0.1 node-zopfli@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@2.0.1 Exit status 1

> node-sass@3.10.1 install /usr/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/install.js

Start downloading binary at https://github.com/sass/node-sass/releases/download/v3.10.1/linux-x64-48_binding.node
Binary downloaded and installed at /usr/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-48/binding.node

> node-sass@3.10.1 postinstall /usr/lib/node_modules/angular-cli/node_modules/node-sass
> node scripts/build.js

"/usr/lib/node_modules/angular-cli/node_modules/node-sass/vendor/linux-x64-48/binding.node" exists. 
 testing binary.
Binary is fine; exiting.
/usr/lib
└─┬ angular-cli@1.0.0-beta.16 
  ├── compression-webpack-plugin@0.3.2  (git://github.com/webpack/compression-webpack-plugin.git#7e55907cd54a2e91b96d25a660acc6a2a6453f54)
  ├─┬ css-loader@0.23.1
  │ ├─┬ cssnano@3.7.5
  │ │ └── postcss-convert-values@2.4.1 
  │ └── postcss@5.2.4 
  ├─┬ ember-cli@2.5.0
  │ ├─┬ bower-config@1.4.0
  │ │ └─┬ osenv@0.1.3
  │ │   └── os-homedir@1.0.2 
  │ ├─┬ broccoli-babel-transpiler@5.6.1
  │ │ └─┬ babel-core@5.8.38
  │ │   └─┬ is-integer@1.0.6
  │ │     └── is-finite@1.0.2 
  │ ├─┬ configstore@2.1.0
  │ │ └── os-tmpdir@1.0.2 
  │ ├─┬ inquirer@0.12.0
  │ │ └─┬ readline2@1.0.1
  │ │   └─┬ code-point-at@1.0.1 
  │ │     └── number-is-nan@1.0.1 
  │ └─┬ markdown-it@4.3.0
  │   └── argparse@1.0.9 
  ├─┬ fs-extra@0.30.0
  │ └── path-is-absolute@1.0.1 
  ├─┬ node-sass@3.10.1 
  │ └─┬ meow@3.7.0
  │   └─┬ loud-rejection@1.6.0
  │     └─┬ currently-unhandled@0.4.1
  │       └── array-find-index@1.0.2 
  └── parse5@2.2.2 

npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by isidroamv** [comment]
Duplicate of #2406

**Comment by krystalmonolith** [comment]
Very similar issue with a Fedora 24: I read in another article to use the "-f" force option .aka.:

`sudo npm install -g -f angular-cli
`

I was reluctant to use the -f force option to install it, but the ng command functionality now seems nominal after one weeks plus of usage. The errors listed above by @Pichchan9k persisted even with the -f option, the end difference being after completion ng works.

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794 for node-gyp errors.

Regarding sudo usage, see https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by ravindrakumarjrd** [comment]
How we can fix in windows os.
npm install -g @angular/cli
npm WARN optional Skipping failed optional dependency /@angular/cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.9
