### ISSUE TITLE
Angular CLI Not working with Typescript 4.9.4

### ISSUE THREAD

**Issue by JemiloII** [angular/angular-cli#24451]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Can we stop omitting minor versions? These are supposed to be bug fixes.

Typescript 4.9.4 is out, but cli doesn't want to work unless I downgrade to 4.9.0

Fix this to include all minor versions.

### Minimal Reproduction

Just install typescript 4.9.4

### Your Environment

```text
Issues will happen on any OS
```

**Comment by alan-agius4** [comment]
TypeScript 4.9 is not supported, TypeScript does not follow semver and minor versions typically contain breaking changes which need to be tacked at the Angular compiler level.
