### ISSUE TITLE
Support running ESM for SSR

### ISSUE THREAD

**Issue by magyargergo** [angular/angular-cli#24461]
### Command

run

## What we were trying to do
We are attempting to change the server-side build to output ECMAScript modules (ESM) in our Angular application. To do this, we modified the following file: `@angular-devkit/build-angular/src/webpack/configs/common.js` and applied the following patch:

```diff
diff --git a/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js b/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
index 3f469dc..eafca93 100644
--- a/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
+++ b/node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js
@@ -245,10 +245,14 @@ async function getCommonConfig(wco) {
             publicPath: (_b = buildOptions.deployUrl) !== null && _b !== void 0 ? _b : '',
             filename: `[name]${hashFormat.chunk}.js`,
             chunkFilename: `[name]${hashFormat.chunk}.js`,
-            libraryTarget: isPlatformServer ? 'commonjs' : undefined,
             crossOriginLoading,
             trustedTypes: 'angular#bundler',
             scriptType: 'module',
+            library: {
+              type: "module"
+            },
+            chunkLoading: "import",
+            chunkFormat: "module",
         },
         watch: buildOptions.watch,
         watchOptions: {
@@ -322,6 +326,7 @@ async function getCommonConfig(wco) {
             ],
         },
         experiments: {
+            outputModule: true,
             backCompat: false,
             syncWebAssembly: true,
             asyncWebAssembly: true,
```

We had to set the `TS_NODE_PROJECT` environment variable because some of the webpack plugins can only use the `paths` from the `tsconfig.json` file when it’s set. Additionally, we turned off the `bundleDependencies` for the server build.

The command looks like this:
```sh
ENV=$ENV \
IS_DEV_APP=true \
LOCALHOST_APP=$PROJECT \
IGNORE_MISSING_APPS=true\
NG_PERSISTENT_BUILD_CACHE=1 \
NODE_OPTIONS="--experimental-specifier-resolution=node --max_old_space_size=25600 --loader ./scripts/esm-interop/esm-main-loader.mjs" \
TS_NODE_PROJECT="./src/tsconfig.$PROJECT.server.json" \
./node_modules/.bin/ng run $PROJECT:serve-ssr${CONFIGURATION} $BUILD_ARGS
```

## What we have encountered with
However, upon attempting to build the application, we encountered an issue where Node.js is unable to import the correct bundle from the package.json file. It appears that Node.js is trying to use the "main" field in the package.json file, which refers to the legacy resolver, instead of the bundle that was built using the Angular Compatibility Compiler. The following error is thrown at runtime:
```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/gmagyar/freelancer-dev/fl-gaf/webapp/node_modules/@angular/core/fesm2015/core.mjs not supported.
Instead change the require of /Users/gmagyar/freelancer-dev/fl-gaf/webapp/node_modules/@angular/core/fesm2015/core.mjs to a dynamic import() which is available in all CommonJS modules.
    at /Users/gmagyar/freelancer-dev/fl-gaf/webapp/node_modules/@agm/core/bundles/agm-core.umd.js:2:76
    at Object.<anonymous> (/Users/gmagyar/freelancer-dev/fl-gaf/webapp/node_modules/@agm/core/bundles/agm-core.umd.js:5:2)
    at async Promise.all (index 0) {
  code: 'ERR_REQUIRE_ESM'
}
```

## What else we have tried
As a potential solution, we tried to use the `@angular/tools/esm-interop/*` module loader that was pushed a few days ago. However, this caused other issues during the build. When we were trying to troubleshoot this issue, we saw that the `globby` variable was undefined in the `./node_modules/copy-webpack-plugin/dist/index.js`. We also noticed that at the end of the compilation, `this.debug(...)` is undefined in the `./node_modules/minimatch/minimatch.js` file. There is a problem with the sub `node_modules/` resolution. Basically, the current implementation of `esm-interop` module won't look into the `./node_modules/copy-webpack-plugin/node_modules/` folder in this case.

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.1.3
Node: 16.14.0
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 14.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.3
@angular-devkit/build-angular   14.1.3
@angular-devkit/core            14.1.3
@angular-devkit/schematics      13.3.9
@angular/cdk                    14.2.5
@angular/fire                   7.3.0
@angular/material               14.2.5
@nguniversal/builders           14.0.3
@nguniversal/express-engine     14.0.3
@schematics/angular             14.1.3
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by alan-agius4** [comment]
This is definitely something that we want to do in the near future.

However SSR ESM support is currently blocked on https://github.com/angular/angular/issues/45062  Once the above is addressed support for ESM with SSR in the Angular CLI will be possible. 

Let's continue tracking this in the above issue.

**Comment by magyargergo** [comment]
I am aware of that issue but if we turn off `bundleDependencies` (which has been removed in v15) nodejs can take care or the module loader to import that dependency with the correct resolver.
