### ISSUE TITLE
Build fails after migrating from v11 to v15

### ISSUE THREAD

**Issue by vijaiselvam** [angular/angular-cli#24468]
### Command

serve, update

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

It was working on angular 11

### Description

./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.
./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

### Minimal Reproduction

"dependencies": {
    "@angular-material-extensions/password-strength": "^12.0.2",
    "@angular-redux/store": "^10.0.0",
    "@angular/animations": "^15.0.4",
    "@angular/cdk": "^15.0.3",
    "@angular/common": "^15.0.4",
    "@angular/compiler": "^15.0.4",
    "@angular/core": "^15.0.4",
    "@angular/forms": "^15.0.4",
    "@angular/language-service": "^15.0.4",
    "@angular/material": "^15.0.3",
    "@angular/platform-browser": "^15.0.4",
    "@angular/platform-browser-dynamic": "^15.0.4",
    "@angular/router": "^15.0.4",
    "@fortawesome/angular-fontawesome": "^0.12.0",
    "@fortawesome/fontawesome-svg-core": "^6.2.1",
    "@fortawesome/free-regular-svg-icons": "^6.2.1",
    "@fortawesome/free-solid-svg-icons": "^6.2.1",
    "@ng-bootstrap/ng-bootstrap": "^14.0.0",
    "@ng-select/ng-select": "10.0.1",
    "@ngx-loading-bar/core": "^6.0.2",
    "@ngx-loading-bar/router": "^6.0.2",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "@swimlane/ngx-charts": "^20.1.2",
    "angular-code-input": "^1.3.2",
    "angular-font-awesome": "^3.1.2",
    "angular-google-tag-manager": "^1.7.0",
    "angular2-notifications": "^12.0.0",
    "angular2-text-mask": "^9.0.0",
    "angularx-qrcode": "^15.0.1",
    "animate-sass": "^0.8.2",
    "bootstrap": "5.2.3",
    "bootstrap-icons": "^1.10.2",
    "file-saver": "^2.0.2",
    "flag-icon-css": "^3.5.0",
    "font-awesome": "^4.7.0",
    "ionicons": "^6.0.4",
    "jquery": "^3.6.3",
    "jsencrypt": "^3.3.1",
    "json-server": "^0.17.1",
    "jspdf": "^2.2.0",
    "linearicons": "^1.0.2",
    "loaders.css": "^0.1.2",
    "moment": "^2.29.4",
    "ng-bootstrap-form-validation": "^9.0.0",
    "ng-otp-input": "^1.8.5",
    "ng-recaptcha": "^11.0.0",
    "ng-select-autocomplete": "^1.4.1",
    "ngx-bootstrap": "^10.2.0",
    "ngx-clipboard": "^15.1.0",
    "ngx-daterangepicker-material": "^6.0.4",
    "ngx-device-detector": "^4.0.1",
    "ngx-dropzone": "^3.1.0",
    "ngx-flip": "^9.0.0",
    "ngx-infinite-scroll": "^15.0.0",
    "ngx-loading": "^14.0.0",
    "ngx-mat-select-search": "^7.0.0",
    "ngx-pagination": "^6.0.3",
    "ngx-perfect-scrollbar": "^10.0.1",
    "ngx-print": "^1.3.0",
    "ngx-select-dropdown": "^3.2.0",
    "ngx-slick-carousel": "^0.6.0",
    "ngx-swiper-wrapper": "^10.0.0",
    "ngx-textarea-autosize": "^2.0.3",
    "ngx-toastr": "^16.0.1",
    "ngx-ui-loader": "^13.0.0",
    "ngx-ui-switch": "^14.0.3",
    "pe7-icon": "^1.0.4",
    "redux": "4.2.0",
    "redux-devtools-extension": "^2.13.9",
    "rxjs": "^7.8.0",
    "sweetalert2": "^11.6.16",
    "swiper": "^8.4.5",
    "ts-md5": "^1.3.1",
    "uuid": "^9.0.0",
    "webpack-bundle-analyzer": "^4.7.0",
    "xlsx": "^0.18.5",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.4",
    "@angular/cli": "^15.0.4",
    "@angular/compiler-cli": "^15.0.4",
    "@angular/localize": "^15.0.4",
    "@fortawesome/fontawesome-free": "^6.2.1",
    "codelyzer": "^6.0.2",
    "jasmine-core": "~4.5.0",
    "jasmine-spec-reporter": "~6.0.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "^3.0.3",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "protractor": "~7.0.0",
    "ts-node": "~10.9.1",
    "tslint": "~6.1.3",
    "typescript": "^4.8.2"
  }

### Exception or Error

```text
./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.
./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.
```

### Your Environment

```text
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.0.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.0.3
@angular/material               15.0.3
@schematics/angular             15.0.4
rxjs                            7.8.0
typescript                      4.8.4
```

### Anything else relevant?

Please help to fix the issue.

**Comment by vijaiselvam** [comment]
| Generating browser application bundles (phase: setup)...Warning: Entry point 'ngx-swiper-wrapper' contains deep imports into 'D:/Codebase/noqodi-apps/noqodi-web-revamp/noqodi-ui/noqodi-customer-angular-ui/noqodi-customer-angular-u
i-frontend/src/main/ngapp_latest/node_modules/swiper/types/swiper-events'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Warning: Entry point 'angular2-text-mask' contains deep imports into 'D:/Codebase/noqodi-apps/noqodi-web-revamp/noqodi-ui/noqodi-customer-angular-ui/noqodi-customer-angular-ui-frontend/src/main/ngapp_latest/node_modules/text-mask-co
re/dist/textMaskCore'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
√ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
styles.css, styles.js | styles        |   1.49 MB |
polyfills.js          | polyfills     | 208.80 kB |
vendor.js             | vendor        | 208.04 kB |
scripts.js            | scripts       | 146.87 kB |
runtime.js            | runtime       |   6.53 kB |
main.js               | main          |   1.00 kB |

                      | Initial Total |   2.05 MB

Build at: 2022-12-26T07:16:20.398Z - Hash: 4a49a6a23a4453c6 - Time: 42102ms

./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Angular Material themes should be created from a map containing the keys "color", "typography", and "density". The color value should be a map containing the palette values for "primary", "accent", and "warn". See https://material.a
ngular.io/guide/theming for more information.

node_modules\@angular\material\core\theming\_theming.scss 185:5  define-light-theme()
src\assets\components\material\_base.scss 88:27                  @import
src\assets\base.scss 62:9                                        @import
src\styles.scss 1:9                                              root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2) or calc($custom-control-indicator-size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 559:49  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-height-inner * 3, 4) or calc($input-height-inner * 3 / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 577:45  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-height-inner, 2) or calc($input-height-inner / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 579:46  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-height-inner, 2) or calc($input-height-inner / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 579:72  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 303:31  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
148 repetitive deprecation warnings omitted.
Run in verbose mode to see all warnings.

null



./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

Error: Failed to initialize Angular compilation - The target entry-point "ngx-swiper-wrapper" has missing dependencies:
 - swiper/bundle




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


× Failed to compile.
√ Browser application bundle generation complete.

Initial Chunk Files | Names   | Raw Size
runtime.js          | runtime |  6.53 kB |

5 unchanged chunks

Build at: 2022-12-26T07:16:31.541Z - Hash: c3ad6d980cf1dfe7 - Time: 10024ms

./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Angular Material themes should be created from a map containing the keys "color", "typography", and "density". The color value should be a map containing the palette values for "primary", "accent", and "warn". See https://material.a
ngular.io/guide/theming for more information.

node_modules\@angular\material\core\theming\_theming.scss 185:5  define-light-theme()
src\assets\components\material\_base.scss 88:27                  @import
src\assets\base.scss 62:9                                        @import
src\styles.scss 1:9                                              root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($custom-control-indicator-size, 2) or calc($custom-control-indicator-size / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 559:49  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-height-inner * 3, 4) or calc($input-height-inner * 3 / 4)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 577:45  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-height-inner, 2) or calc($input-height-inner / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 579:46  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($input-height-inner, 2) or calc($input-height-inner / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 579:72  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
Deprecation Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($spacer, 2) or calc($spacer / 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

src\assets\components\bootstrap4\_variables.scss 303:31  @import
src\assets\base.scss 5:9                                 @import
src\styles.scss 1:9                                      root stylesheet


./src/styles.scss - Warning: Module Warning (from ./node_modules/sass-loader/dist/cjs.js):
148 repetitive deprecation warnings omitted.
Run in verbose mode to see all warnings.

null



./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
