### ISSUE TITLE
Index.html file in dist folder showing blank page in ng build/ ng build --configuration production

### ISSUE THREAD

**Issue by Ken2ie** [angular/angular-cli#24465]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

I.m having issues building for deployment in angular v15

1. First I have been trying to deploy my angular apps for a while now and the end result shows me a blank page.
2. I run `ng build` or `ng build --configuration production`
3. Then I open the dist folder to open the app, thus index.html file in the project folder in the dist folder.
4. When opened, the file is blank, there is absolutely nothing in the file nor front-end shown.

I surely know I'm doing something wrong and maybe the steps to view the front-end in the browser is wrong, please can someone 
help me out with this issue? Thank you.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Ken2ie** [comment]
Hi Alan Agius,
               Thank you very much for this email, I actually just found
the solution by God's Grace so I would put the solution right.
Thank you.👍
