### ISSUE TITLE
Not able to remove solution style tsconfig in Angular 13

### ISSUE THREAD

**Issue by cseas** [angular/angular-cli#24477]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

10

### Description

I just upgraded a project from Angular 12 to 13 but the CLI didn't touch the solution style `tsconfig.json` file at all. This file was automatically added in an Angular 10 migration earlier.

I'm trying to get Angular CLI to perform the migration by running the below command as suggested in
https://github.com/angular/angular-cli/issues/18744#issuecomment-712291063

```sh
ng update @angular/cli@10 --from=10.0.0 --to=10.1.3 --migrate-only
```

The command exits after `Found 91 dependencies.` and nothing changes in the project.

### Minimal Reproduction

- Upgrade a project from Angular 12 to 13 with a solution style tsconfig.
- Try to remove the solution style tsconfig file by running the below command:

```sh
ng update @angular/cli@10 --from=10.0.0 --to=10.1.3 --migrate-only
```

### Exception or Error

Not getting an error but the command exits after showing this:

```text
Using package manager: npm
Collecting installed dependencies...
Found 91 dependencies.
```

### Your Environment

```text
Your global Angular CLI version (15.0.4) is greater than your local version (13.3.10). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.10
Node: 16.14.2
Package Manager: npm 8.5.0
OS: darwin arm64

Angular: 13.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.10
@angular-devkit/build-angular   13.3.10
@angular-devkit/core            13.3.10
@angular-devkit/schematics      13.3.10
@angular/cdk                    13.3.9
@angular/cli                    13.3.10
@angular/flex-layout            12.0.0-beta.35
@angular/material               13.3.9
@schematics/angular             13.3.10
ng-packagr                      13.3.1
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by cseas** [comment]
Update: I removed it manually.
- Removed `tsconfig.json`
- Renamed `tsconfig.base.json` to `tsconfig.json`
- Replaced all references of `tsconfig.base.json` with `tsconfig.json` in the project.

Not sure if this steps are correct for the migration though. Can't find any mention in the docs of removing this file manually.

**Comment by clydin** [comment]
Those manual steps are what the migration would do automatically.
The reason the command (`ng update @angular/cli@10 --from=10.0.0 --to=10.1.3 --migrate-only`) doesn't work is that the `@10` part of the package specifier does not actually do anything in migrate only mode.  Ideally this should probably work as you expected it, but for the the interim, we can add a warning regarding the version specifier.

**Comment by cseas** [comment]
> Those manual steps are what the migration would do automatically. 

That's why the bug report. Command ran, didn't throw any error, and nothing changed in my project.

> the `@10` part of the package specifier does not actually do anything in migrate only mode.

I tried adding the `@10` part only after trying out the below command without it:

```sh
ng update @angular/cli --from=10.0.0 --to=10.1.3 --migrate-only
```

Neither worked. Had to figure out a manual solution. Would've been great if the manual solution was mentioned somewhere in the docs. I mostly figured out by hit and trial and then filed the issue to make sure I didn't do something I wasn't supposed to.

**Comment by alan-agius4** [comment]
The version specifier is indeed ignored when using `--migrate-only`. A warning was added in a more recent version of the CLI but since you are providing the `@` specifier, an old version of the CLI without the warning is being downloaded to run the update.

In your case it is assuming that all non optional migrations have been ran when updated from 10 to 11. In your cases likely this was not the case because of a manual update. 

Overall, I don't see anything actionable here, as I don't think this warrants any documentation changes. For starters versions older than 13 are no longer supported and if users are using Angular 12 or latest it is assumed that the migration was executed through `ng update` from updating from 10 to 11.
