### ISSUE TITLE
Cannot run ng serve Angular 14

### ISSUE THREAD

**Issue by amit2206** [angular/angular-cli#24486]
### Command

ng serve

### Description

My project is already updated to Angular 14 from angular13 which was working perfectly fine now suddenly on **ng serve,** it started following error -

# Fatal error in , line 0
# Fatal JavaScript invalid size error 169243484
#
#FailureMessage Object: 0x7ffc124030e0
 1: 0xb6d311  [ng s]
 2: 0x1bf5a04 V8_Fatal(char const*, ...) [ng s]
 3: 0xe74128  [ng s]
 4: 0x1022832  [ng s]
 5: 0x10231a9  [ng s]
 6: 0x11e32b3 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [ng s]
 7: 0x15e7819  [ng s]
[1]    23175 trace trap (core dumped)  ng s

My output of command:  
npm ls @angular-devkit/build-angular_    is as follows -

└── @angular-devkit/build-angular@14.2.6

Could anyone please suggest how to fix it ?

### Minimal Reproduction

ng s

### Your Environment

```text
Angular CLI: 14.2.6
Node: 16.13.1
Package Manager: npm 9.2.0 
OS: linux x64

Angular: 14.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cdk                    14.2.5
@angular/material               14.2.5
@schematics/angular             14.2.6
rxjs                            7.5.7
typescript                      4.8.4
```

### Anything else relevant?

I can see the similar issue -https://github.com/angular/angular-cli/issues/23352 but I am not using the custom builder so not sure how it is relavant

**Comment by clydin** [comment]
Does this issue happen with a newly generated v14 project? And if so, does it happen with a newly generated v15?

Also, it appears that the project above still contains some v13 dependencies:
```
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
```
This could indicate that either an update was not completed successfully or some third-party dependencies are not compatible with v14. Something else that could be tried is to delete the `node_modules` directory and any package manager lock files and then reinstall.

**Comment by amit2206** [comment]
Hi @clydin, Thanks for your response.
Actually these two dependencies are not directly in my project. please find below my package.json -

"dependencies": {
    "@angular-material-components/datetime-picker": "^8.0.0",
    "@angular-material-components/moment-adapter": "^8.0.0",
    "@angular/animations": "^14.2.6",
    "@angular/cdk": "^14.2.5",
    "@angular/common": "^14.2.6",
    "@angular/compiler": "^14.2.6",
    "@angular/core": "^14.2.6",
    "@angular/forms": "^14.2.6",
    "@angular/localize": "^14.2.6",
    "@angular/material": "^14.2.5",
    "@angular/platform-browser": "^14.2.6",
    "@angular/platform-browser-dynamic": "^14.2.6",
    "@angular/router": "^14.2.6",
    "@ctrl/ngx-codemirror": "^5.0.0",
    "@google/markerclustererplus": "^5.1.3",
    "@larscom/ngrx-store-storagesync": "^13.0.10",
    "@ng-idle/core": "^11.1.0",
    "@ng-idle/keepalive": "^11.0.3",
    "@ngrx/effects": "^14.3.2",
    "@ngrx/store": "^14.3.2",
    "@ngrx/store-devtools": "^14.3.2",
    "@ngx-translate/core": "^14.0.0",
    "@types/websocket": "^1.0.5",
    "angular-gridster2": "^14.1.1",
    "chart.js": "^2.9.4",
    "codemirror": "^5.65.2",
    "detect-browser": "^5.3.0",
    "file-saver": "^2.0.5",
    "ip-address": "^8.1.0",
    "is-cidr": "^4.0.2",
    "jasmine-marbles": "^0.9.2",
    "moment": "^2.29.4",
    "net": "^1.0.2",
    "ng-dynamic-component": "^10.5.1",
    "ng2-charts": "^2.4.3",
    "rxjs": "^7.5.7",
    "sonar-scanner": "^3.1.0",
    "ts-mockito": "^2.6.1",
    "tslib": "^2.4.0",
    "websocket": "^1.0.34",
    "xlsx": "^0.18.5",
    "zone.js": "^0.11.8"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.6",
    "@angular-eslint/builder": "^14.1.2",
    "@angular-eslint/eslint-plugin": "^14.1.2",
    "@angular-eslint/eslint-plugin-template": "^14.1.2",
    "@angular-eslint/schematics": "^14.1.2",
    "@angular-eslint/template-parser": "^14.1.2",
    "@angular/cli": "^14.2.6",
    "@angular/compiler-cli": "^14.2.6",
    "@angular/language-service": "^14.2.6",
    "@compodoc/compodoc": "^1.1.19",
    "@types/googlemaps": "^3.43.3",
    "@types/jasmine": "^4.3.0",
    "@types/jasminewd2": "^2.0.10",
    "@types/node": "^18.11.0",
    "@types/resize-observer-browser": "^0.1.7",
    "@typescript-eslint/eslint-plugin": "^5.40.0",
    "@typescript-eslint/parser": "^5.40.0",
    "angular-tslint-rules": "^1.20.4",
    "eslint": "^8.25.0",
    "jasmine-core": "^4.4.0",
    "jasmine-spec-reporter": "^7.0.0",
    "karma": "^6.4.1",
    "karma-cli":"2.0.0",
    "karma-chrome-launcher": "^3.1.1",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "^5.1.0",
    "karma-jasmine-html-reporter": "^2.0.0",
    "karma-sonarqube-reporter": "~1.4.0",
    "sonar-scanner": "^3.1.0",
    "ng-openapi-gen": "^0.23.0",
    "ngrx-store-freeze": "^0.2.4",
    "prompts": "^2.4.2",
    "protractor": "~7.0.0",
    "replace-in-file": "^6.3.5",
    "ts-node": "^10.9.1",
    "tslint-ngrx": "^1.0.9",
    "typescript": "4.8.4"
  }
  
SO this might be coming from any peer dependency, could you please suggest how to find and resolve it ?

**Comment by clydin** [comment]
Executing `npm ls @angular-devkit/core` within the project should list all packages that use the dependency.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
