### ISSUE TITLE
How to add js code in the html?

### ISSUE THREAD

**Issue by nikvarma** [angular/angular-cli#2449]
component page

import { Component } from "@angular/core";
@Component({
    templateUrl: "genres.html"
})
export class GenresComponent {
}

genres.html

there are a some javascript function used only for this page, but when i am trying to add a js in the html page it is not working

please can any one tell me, it's a bug or i am doing something wrong

**Comment by minuz** [comment]
You probably should be looking at Angular 2 quick start.
The TS file is your JS. 
Angular does not allow `<script>` inside the HTML. 
Create your javascript functions inside the class.
i.e.:
```javascript
export class GenresComponent{
    someFunction(){
        //your code...
    }
}
```

**Comment by filipesilva** [comment]
In addition to what @minuz said, you can also look at the `scripts` array in `angular-cli.json`: https://github.com/angular/angular-cli#global-library-installation
