### ISSUE TITLE
Uncaught Error: Incompatibile SockJS!

### ISSUE THREAD

**Issue by devrockzz** [angular/angular-cli#2450]
I am using angular cli the latest build and i have tried expected solution for it but it not working plz help me out and the webpack version is 2.1.0-beta.22

I am getting this error on the console loge . 
->sockjs.min.js:2 Uncaught Error: Incompatibile SockJS! Main site uses: "1.1.1", the iframe: "1.0.1".

**Comment by filipesilva** [comment]
Heya, I'm going to have to ask you to open a new issue answer the questions on the issue template. If you don't answer those it's very hard for us to help you out.

**Comment by devrockzz** [comment]
I have solved it by my self
