### ISSUE TITLE
Can't customize path for lazy loaded module chunks

### ISSUE THREAD

**Issue by heeeman** [angular/angular-cli#24512]
### Command

config

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

i have the sam problem as decribed in https://github.com/angular/angular-cli/issues/22418

Set APP_BASE_HREF does not work, cause it affected also the router. 

### Minimal Reproduction

Create a simple Angular application with a router, where files are located. The chunks are not loaded. For this example, let's say that the Angular.json file has following setting:

"outputPath": "../public/mysitefolder"

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.10
Node: 16.18.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.10 (cli-only)
@angular-devkit/core         14.2.10 (cli-only)
@angular-devkit/schematics   14.2.10 (cli-only)
@schematics/angular          14.2.10 (cli-only)
```

**Comment by alan-agius4** [comment]
Hi @heeeman, 

You'd need to configure the `baseHref` build option and not `APP_BASE_HREF` injection token. See https://angular.io/cli/build for more information about the build options.

If the problem persists, please provide a simple repository reproducing the problem.  You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by heeeman** [comment]
It does not work. The <base href> of the html page override the baseHref  build option

**Comment by alan-agius4** [comment]
@heeeman, it is the other way round the `baseHref` build option overrides what's in the HTML. 

Kindly provide a minimal reproduction of the problem otherwise we will be unable to look into this issue.

**Comment by heeeman** [comment]
I hope this works as reproducer:
https://github.com/heeeman/angularReproducer.git

**Comment by alan-agius4** [comment]
Thanks for the reproduction.

The problem here is that the base href in the CMS project is set incorrectly. As this is set to point to the application path and not were the resources are located. Relative resources (which lazy chunks are) are longer relative to the base href.

Also, `APP_BASE_HREF` also needs to be configured as otherwise the router will use the base href from HTML which would cause routing not to work correctly. 

Below find the diffs needed.

```diff
diff --git a/serverContent/cms/dynamic/path/angularembedded/index.html b/serverContent/cms/dynamic/path/angularembedded/index.html
index e896e29..8a6a3d3 100644
--- a/serverContent/cms/dynamic/path/angularembedded/index.html
+++ b/serverContent/cms/dynamic/path/angularembedded/index.html
@@ -3,10 +3,10 @@
 <head>
   <meta charset="utf-8">
   <title>CMS Page</title>
-  <base href="/cms/dynamic/path/angularembedded">
+  <base href="/standalone/">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="icon" type="image/x-icon" href="favicon.ico">
-  <link rel="stylesheet" href="/standalone/styles.css">
+  <link rel="stylesheet" href="styles.css">
 </head>
 <body>
 
@@ -24,7 +24,7 @@
 
   <div><a href="/">back to root</a></div>
 
-  <script src="/standalone/runtime.js" type="module"></script><script src="/standalone/polyfills.js" type="module"></script><script src="/standalone/main.js" type="module"></script>
+  <script src="runtime.js" type="module"></script><script src="polyfills.js" type="module"></script><script src="main.js" type="module"></script>
 
 </body>
 </html>
diff --git a/src/app/app.module.ts b/src/app/app.module.ts
index a9b3db1..b22a8a0 100644
--- a/src/app/app.module.ts
+++ b/src/app/app.module.ts
@@ -6,18 +6,22 @@ import { AppComponent } from './app.component';
 import { OtherPageModule } from './other-page/other-page.module';
 import { NicePageComponent } from './nice-page/nice-page/nice-page.component';
 import { NicePageModule } from './nice-page/nice-page.module';
+import { APP_BASE_HREF } from '@angular/common';
 
 @NgModule({
   declarations: [
     AppComponent
   ],
   imports: [
     BrowserModule,
     AppRoutingModule,
     // OtherPageModule,
     // NicePageModule
   ],
-  providers: [],
+  providers: [
+    {
+      provide: APP_BASE_HREF,
+      useValue: '/cms/dynamic/path/angularembedded',
+    },
+  ],
   bootstrap: [AppComponent],
 })
  export class AppModule { }

```

**Comment by heeeman** [comment]
The  cms path is not under my control and dynamic, that's the problem. Actually I read the base href from the cms site to set APP_BASE_HREF  for my routing. But it's not possible to set or change base href from the cms site.   

For the moment I have removed the lazy loading.

**Comment by alan-agius4** [comment]
You can set the `APP_BASE_HREF` dynamically by the means of a factory function. 

```ts
providers: [
  {
    provide: APP_BASE_HREF,
    useFactory: getAppBaseHref,
    deps: [HttpClient],
  }
],
…

function getAppBaseHref(http: HttpClient): string {
 // get value from config / dynamically from CMS
}
```

Closing as this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by heeeman** [comment]
so - there's no possibility for lazy loading, if it's not possible to set `<base href> `tag on the page.
