### ISSUE TITLE
optimization error when switching from 15.0.5 to 15.1.0

### ISSUE THREAD

**Issue by jnizet** [angular/angular-cli#24526]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.5

### Description

When switching from version 15.0.5 to version 15.1.0 of the CLI, the ng build command fails with the following error:

```
Error: Optimization error [main.4718ba8213dd7bf6.js]: SyntaxError: Unexpected token: punc (()
```

### Minimal Reproduction

See https://github.com/jnizet/decouvertes-nature/pull/521.

To reproduce locally:

- clone the project
- checkout to the branch `renovate/angular-cli-monorepo`
- run `yarn`
- run `ng build`

### Exception or Error

```text
Error: Optimization error [main.4718ba8213dd7bf6.js]: SyntaxError: Unexpected token: punc (()
```
```


### Your Environment

```text
Angular CLI: 15.1.0
Node: 16.15.0
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 15.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.1.0
@angular/fire                   7.5.0
@schematics/angular             15.1.0
rxjs                            7.8.0
typescript                      4.8.4
```
```


### Anything else relevant?

_No response_

**Comment by atsjo** [comment]
same for me...

**Comment by leonelvsc** [comment]
Same here

**Comment by clydin** [comment]
This appears to be a bug in esbuild which is used within the optimization pipeline.  An fix with esbuild will most likely be needed to resolve the issue.

**Comment by atsjo** [comment]
the newly released esbuild 0.16.17 fixes this. confirmed by overriding esbuild dependency via
  "resolutions": {
    "@angular-devkit/build-angular/esbuild": "0.16.17"
  }

**Comment by kwhjvdkamp** [comment]
Thanks @anisaboud !

**Comment by clydin** [comment]
For any projects encountering this issue, please update the Angular CLI to 15.1.1.
