### ISSUE TITLE
SCSS not compiled correctly -> no error/warning on console

### ISSUE THREAD

**Issue by meriturva** [angular/angular-cli#24532]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

Provided a repo to test it with angular 15.1.

https://github.com/meriturva/ng-scss-import-issue

Simply style on `body` (after all imports on file `style.scss`) is not produced without any error.
(see https://github.com/meriturva/ng-scss-import-issue/blob/main/src/styles.scss#L28 )

Just try to comment one of import on file `style.scss` `body` style start to be compiled/produced correctly.

I guess it is something related to memory but no error is logged on console.
Executing `ng serve --verbose` produces quite different logs:

When issue is present: https://raw.githubusercontent.com/meriturva/ng-scss-import-issue/main/log-when-issue-present.log
When issue is NOT present: https://raw.githubusercontent.com/meriturva/ng-scss-import-issue/main/log-when-issue-NOT-present.log

### Minimal Reproduction

To reproduce the issue just run `ng serve` on the repo provided and you will not see the page with a red background.

Commenting one of the imports on file `style.scss`  fix issue and page is now red.

### Your Environment

```text
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 15.1.0
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 15.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.0
@angular-devkit/build-angular   15.1.0
@angular-devkit/core            15.1.0
@angular-devkit/schematics      15.1.0
@schematics/angular             15.1.0
rxjs                            7.8.0
typescript                      4.9.4
```

### Anything else relevant?

Tested on two different windows machines.

**Note that `ng serve -c production` works as expected.**

**Comment by alan-agius4** [comment]
Hi @meriturva, 

Thanks for the issue but this is not a bug in the Angular CLI. 

The stylesheet is generated correctly, but the browser is giving up on rendering it as it's insanely large 46.52 MB. 

This is caused because importing each kendo-theme stylesheet individually is causing a large set of CSS rules to be duplicated. I suggest to file an issue with `@progress/kendo-theme-bootstrap` as using this package is considerable slowing down the SCSS compilation due the large set of duplicate CSS.

**Comment by meriturva** [comment]
Thanks for taking the time to inspect my test project @alan-agius4 .

As you already found `scss` is insanely large due to individual import but here we have a few aspects related to angular CLI:

1. Browser just downloads correct `style.css` file without any problems (file terminated correctly with sitemap url), so the problem is during the generation of the file
2. `ng build` produces a correct style.css file

So it is something related to CLI from my perspective. What do you think?
PS: I will open also an issue on progress side.

**Comment by alan-agius4** [comment]
> 1. `ng serve` Browser just downloads correct `style.css` file without any problems (file terminated correctly with sitemap url), so the problem is during the generation of the file

 This is expected, the browser can download such as large file without any issues, but rendering and apply all that CSS is another thing. 

> 2. `ng serve -c production` works correctly

This is also expected as during a production build the CSS optimizer will remove the duplicate CSS. 

> 3. `ng build` produces a correct style.css file

Same as point 2.

**Comment by alan-agius4** [comment]
One other thing to point out is that when `@progress/kendo-theme-bootstrap` is used, the build slows down drastically but to the SCSS exported by this package.

**Comment by meriturva** [comment]
Ok i have downloaded `style.css` file produced during `serve` phase and you are right, CLI works correctly.

Style:

```
body {
  background-color: red;
}
```

is present at the end of the file.
Thanks for your time and help.
