### ISSUE TITLE
missing "get-file-content" from "@schematics/angular/utility/test"

### ISSUE THREAD

**Issue by seneric** [angular/angular-cli#24547]
### Command

other

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.0.5

### Description

Since the 15.1.0 version the "test" has been removed in "node_modules/@schematics/angular/utility" folder.

If you inspect the "source code" zip (15.1.0) located here: https://github.com/angular/angular-cli/archive/refs/tags/15.1.0.zip the test folder is present.
But if you install the package (npm install @angular/cli@15.1.0) the folder is not present in the "node_modules/@schematics/angular/utility" folder 

 * 15.0.5 folder structure
<img width="840" alt="Capture d’écran 2023-01-13 à 13 38 30" src="https://user-images.githubusercontent.com/4995630/212322377-8eb5e72b-5b88-4fc1-b33f-c4877c9faabb.png">
* 15.1.0 folder structure
<img width="867" alt="Capture d’écran 2023-01-13 à 13 39 21" src="https://user-images.githubusercontent.com/4995630/212322477-05f64342-5607-41ee-9245-24e6be89315f.png">

angular-cli-15.1.0 zip contain
<img width="341" alt="Capture d’écran 2023-01-13 à 13 42 12" src="https://user-images.githubusercontent.com/4995630/212322972-0cc1dbc7-4c46-4dfc-aaac-d5ad3f5b6ec2.png">

### Minimal Reproduction

try to import fails
<img width="1101" alt="Capture d’écran 2023-01-13 à 13 44 35" src="https://user-images.githubusercontent.com/4995630/212323280-28345eec-b908-4b64-82f6-f6cf96789ea6.png">

### Your Environment

```text
Angular 15
```

**Comment by alan-agius4** [comment]
Hi @seneric,

Only exports from `@schematics/angular/utility` are considered as part public API. Anything else is considered as private API that can change in any version without warning.

See https://github.com/angular/angular-cli/pull/23041 for more context.

**Comment by seneric** [comment]
Why is it present in Zip file ?

**Comment by clydin** [comment]
That utility function is also outdated and will be completed removed from the source in the future.
The `Tree` instance itself now contains a `readText` method which can be used both within a schematic and a schematic test.
