### ISSUE TITLE
Allow ng serve to listen on unix socket

### ISSUE THREAD

**Issue by Socolin** [angular/angular-cli#24562]
### Command

serve

### Description

I'm working on multiple project and playing around with ports to avoid conflict, or being force to stop a project to start a new one is annoying, I would like to be able to start `ng serve` on an unix socket (Also [available on windows](https://batsov.com/articles/2022/01/20/unix-sockets-are-now-supported-on-windows))
This would allow me to dispatch through nginx to the expected project based on the domain name (I added domain in my `/etc/hosts` file)

A nice things is that the ports are not an issue anymore, I only need nginx to listen on 80/443 and then I don't have to find a new unused port for each project.

### Describe the solution you'd like

Allow `--host` syntax like `unix:///var/run/angular-serve.sock`

**Comment by alan-agius4** [comment]
Thanks for this feature request. Let re-consider this in the future if there is more interest for time from the community.
