### ISSUE TITLE
angular 15 how can I avoid long relative paths import

### ISSUE THREAD

**Issue by kaimmrt** [angular/angular-cli#24581]
Angular 15

I want to '@import 'variables.scss' like this instead of '@import '../../../assets/scss/variables.scss;'

my code in project.json file
```
   "stylePreprocessorOptions": {
                    "includePaths": ["apps/client/src/assets/scss","./node_modules"]
    },
```

I get an error like this when I defined this short '@import 'variables.scss'

Error: Transform failed with 1 error:
C:/my-project/home.component.scss:17: 100 : ERROR: Unterminated string token

**Comment by alan-agius4** [comment]
The `includePaths` are relative to the workspace root, so likely the correct path should be `src/apps/client/src/assets/scss` if you have a root level application. It is also worth mentioning that using `@import` is discouraged by the SASS team and it is being phased out.  See: https://sass-lang.com/documentation/at-rules/import
 
If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
