### ISSUE TITLE
Add script config for adding scripts as type="module"

### ISSUE THREAD

**Issue by tmcconechy** [angular/angular-cli#24592]
### Command

build, config

### Description

Looking at the script config https://angular.io/guide/workspace-config#style-script-config there does not seem to be any way to add the scripts as type="module" for esm.

If the third party script is delivered as an Es Module it cant be imported in the angular.json.

![Screenshot 2023-01-23 at 11 30 28 AM](https://user-images.githubusercontent.com/814283/214100400-3b461945-3870-4386-964d-e4c9e70cfaae.png)

Seems like there is some thought about this https://github.com/angular/angular-cli/blob/d086d170565304f82494745b1dd626f01093a512/packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts#L94

This comment may be the one of why it won't add type="module"https://github.com/angular/angular-cli/blob/d086d170565304f82494745b1dd626f01093a512/packages/angular_devkit/build_angular/src/utils/index-file/augment-index-html.ts#L79 -> but still think it should be possible.

### Describe the solution you'd like

Add a new setting to the script config, something like.

```
"scripts": [
  {
    "input": "node_modules/third-party/esm-script.js", 
    "inject": true,
    "scriptType": "module"
   }
],
```

### Describe alternatives you've considered

- can not use angular.json and
- manually add a script tag or
- just import the module in the Angular module code

**Comment by egorwow70** [comment]
@alan-agius4 
Hello, Alan. Is there any update regarding this issue?

**Comment by bernatgy** [comment]
Also interested if there is any progress in this... It's quite serious, because some third party libs started shipping/working with exclusively `.mjs` files. (eg. [mozilla/pdf.js](https://github.com/mozilla/pdf.js/pull/17055))

**Comment by alan-agius4** [comment]
When the script is in ESM, you can directly import it in `main.ts` or wherever it's required.

@bernatgy, it's preferable to use the explicitly imported script instead of relying on the prebuilt global script. This ensures that Dead Code Elimination (DCE) and tree-shaking optimizations can be applied to the library.

Example:
```ts
import { getDocument } from "pdfjs-dist";
const loadingTask = getDocument(pdfPath);
```

The `scripts` option should only be used for legacy scripts that are not ESM complaint.
