### ISSUE TITLE
Cannot find module 'glob'

### ISSUE THREAD

**Issue by doczoidberg** [angular/angular-cli#246]
I did a npm update on my cli project and now I get the error `Cannot find module 'glob'` when running ng serve.  Also the npm packages seem a bit outdated?

**Comment by filipesilva** [comment]
This issue is a duplicate of https://github.com/angular/angular-cli/issues/233.

The missing dependency has been fixed 3 days ago with https://github.com/angular/angular-cli/pull/238, but a release hasn't been cut yet. Using latest master has this fixed.
