### ISSUE TITLE
Upgrade Library Compatibility Checker

### ISSUE THREAD

**Issue by thatcort** [angular/angular-cli#24606]
### Which @angular/* package(s) are relevant/related to the feature request?

upgrade

### Description

The most difficult and time consuming part of upgrading Angular is determining whether all the library dependencies are compatible. This is currently a manual process and the blockers are not discovered until late in the upgrade process after already investing significant time. A tool that automatically checks the available versions of dependencies in advance would be a huge help here!

### Proposed solution

When considering an Angular upgrade there should be a tool that examines the package.json and then examines every dependency for a peer dependency on Angular. Any such libraries should be checked for a newer version on NPM that is compatible with the target Angular version. Finally, a report should be generated showing which versions are required or which libraries are currently blocking the upgrade.

### Alternatives considered

I am unaware of alternatives.

**Comment by thatcort** [comment]
I was unaware of this in `ng update` I'll give it a try.

**Comment by alan-agius4** [comment]
Closing as per above.
