### ISSUE TITLE
ChunkLoadError in Lazy Loading project

### ISSUE THREAD

**Issue by ponthousan** [angular/angular-cli#24603]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have two angular projects
https://palanichamytextiles.github.io/
https://ponthousan.github.io

1. First Project i have lazy loaded modules Login and Register
2. And using createCustomElement i have exported the AppComponent
3. In the second project i have imported the first project build file in index.html file

  <script src="https://palanichamytextiles.github.io/runtime.js" type="module"></script>
  <script src="https://palanichamytextiles.github.io/polyfills.js" type="module"></script>
  <script src="https://palanichamytextiles.github.io/main.js" type="module"></script>

4. when the site is render, first project lazy loaded modules(login, register) is referring the parent location(second project)

5. its throwing error loading chunk failed

![image](https://user-images.githubusercontent.com/19571611/214554690-1ae28a8a-cbc9-469d-bab1-5219dc5f569b.png)
 

### Minimal Reproduction

I have two angular projects
https://palanichamytextiles.github.io/
https://ponthousan.github.io

1. First Project i have lazy loaded modules Login and Register
2. And using createCustomElement i have exported the AppComponent
3. In the second project i have imported the first project build file in index.html file

  <script src="https://palanichamytextiles.github.io/runtime.js" type="module"></script>
  <script src="https://palanichamytextiles.github.io/polyfills.js" type="module"></script>
  <script src="https://palanichamytextiles.github.io/main.js" type="module"></script>

4. when the site is render, first project lazy loaded modules(login, register) is referring the parent location(second project)

5. its throwing error loading chunk failed

![image](https://user-images.githubusercontent.com/19571611/214554690-1ae28a8a-cbc9-469d-bab1-5219dc5f569b.png)
 

### Your Environment

```text
Angular CLI: 15.0.5
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64
Angular: 15.1.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
