### ISSUE TITLE
@angular-devkit/build-angular:browser-esbuild Error: Unknown arguments: proxy-config, hmr, port, open

### ISSUE THREAD

**Issue by mivanyna** [angular/angular-cli#24621]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When change "builder" setting for serve config in angular.json from @angular-devkit/build-angular:dev-server  to "@angular-devkit/build-angular:browser-esbuild" and try to run the app following error is shown:

Error: Unknown arguments: proxy-config, hmr, port, open

### Minimal Reproduction

run in command line `yarn start`

where `"start": "ng serve --proxy-config config/proxy.conf.js --hmr --port 3000 --open=true",`

### Exception or Error

```text
Error: Unknown arguments: proxy-config, hmr, port, open
```

### Your Environment

```text
@angular-devkit/schematics      15.1.1
@angular/cli                    15.1.1
@angular/compiler-cli           15.1.2
@schematics/angular             15.1.1
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by alan-agius4** [comment]
This is expected as  right now experimental esbuild builder does not provide dev-server capabilities. Support for this will be added in future before it becomes stable.

**Comment by harellevy** [comment]
please add the exclude option. it's very necessary for this experimental phase for some libs that won't pass the build and aren't really needed at this stage.
