### ISSUE TITLE
Access Angular [v14] outside localhost

### ISSUE THREAD

**Issue by rabeeshcharles** [angular/angular-cli#24628]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13

### Description

Current cli version 14

While running this command 
ng serve --host 0.0.0.0
ng serve --host 0.0.0.0 --disable-host-check

tried these two commands to access angular app from other ips.
but its throws ERR_SSL_PROTOCOL_ERROR
package.json file
![image](https://user-images.githubusercontent.com/30102705/215407142-d3f576cd-269b-403d-967b-dab8700507d0.png)

Command output
![image](https://user-images.githubusercontent.com/30102705/215407316-fec29dbe-1a10-4611-9cb4-1c6804f5368d.png)

### Minimal Reproduction

Command
node --max_old_space_size=8048 ./node_modules/@angular/cli/bin/ng serve --host=0.0.0.0 --port 4201 --disable-host-check

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 14.2.10
Node: 16.13.1
Package Manager: npm 8.9.0
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1402.10
@angular-devkit/build-angular      14.2.10
@angular-devkit/core               14.2.10
@angular-devkit/schematics         14.2.10
@angular/cdk                       13.3.7
@angular/cli                       14.2.10
@angular/flex-layout               13.0.0-beta.38
@angular/material                  13.3.7
@angular/material-moment-adapter   13.3.7
@schematics/angular                14.2.10
rxjs                               7.5.5
typescript                         4.6.4
```

**Comment by alan-agius4** [comment]
Are you using any proxies? `ERR_SSL_PROTOCOL_ERROR` indicates that the browser is requesting the the SSL certificate to establish a secure connection but in this case the dev-server does not have SSL enabled.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.
