### ISSUE TITLE
Experimental @angular-devkit/build-angular:browser-esbuild and material datepicker component MAT_DATE_LOCALE bug

### ISSUE THREAD

**Issue by schwarzwald4327** [angular/angular-cli#24623]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

with "builder": "@angular-devkit/build-angular:browser"

### Description

angular 15.1.3 and angular material 14.2.7 datepicker component with @angular-devkit/build-angular:browser-esbuild shows incorrect locale

how MAT_DATE_LOCALE  should work:
https://v14.material.angular.io/components/datepicker/overview#internationalization

### Minimal Reproduction

```
npx --package @angular/cli ng new angular-datepicker --defaults
ng add @angular/material @angular/cdk
ng add @angular/material-moment-adapter
npm install http-server -g
```

app.module.ts

```
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        BrowserModule,
        BrowserAnimationsModule,
        MatInputModule,
        MatDatepickerModule,
        MatMomentDateModule
    ],
    providers: [
        {
            provide: DateAdapter,
            useClass: MomentDateAdapter
        },
        {
            provide: MAT_DATE_FORMATS,
            useValue: MAT_MOMENT_DATE_FORMATS
        },
        {
            provide: MAT_DATE_LOCALE,
            useValue: 'de'
        }
    ],
    bootstrap: [AppComponent]
})
export class AppModule {
}
```

app.component.ts

```
@Component({
    selector: 'app-root',
    templateUrl: './app.component.html'
})
export class AppComponent {
}
```

app.component.html

```
<mat-form-field appearance="fill">
    <input matInput [matDatepicker]="picker">
    <mat-datepicker-toggle matSuffix [for]="picker"></mat-datepicker-toggle>
    <mat-datepicker #picker></mat-datepicker>
</mat-form-field>
```

"builder": "@angular-devkit/build-angular:browser"
```
ng build
http-server dist/angular-datepicker
```
datepicker shows correct date format (german locale)

"builder": "@angular-devkit/build-angular:browser-esbuild"
```
ng build
http-server dist/angular-datepicker
```
datepicker shows wrong date format (english locale)

### Your Environment

```text
Angular CLI: 15.1.3
Node: 18.13.0
Package Manager: npm 9.4.0
OS: win32 x64

Angular: 15.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.3
@angular-devkit/build-angular   15.1.3
@angular-devkit/core            15.1.3
@angular-devkit/schematics      15.1.3
@angular/cli                    15.1.3
@schematics/angular             15.1.3
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by clydin** [comment]
`moment` uses a dynamic require statement to attempt to load a given locale provided via a variable. esbuild does not currently support dynamic require statements. Webpack does support this. However, it will bundle every locale that `moment` supports into the application since Webpack doesn't know which one will be used at runtime.

As a workaround for the experimental builder, adding an additional import (within `main.ts`, for instance) for the locale used by the application will allow `moment` to find and use it.  When using the experimental esbuild-based builder, this also has the current advantage of not bundling all the `moment` locales into the output.

Example import:
```
import 'moment/locale/de';
```

**Comment by schwarzwald4327** [comment]
you're right, I don't know how I missed that part, now everything works correctly, I'm closing the ticket
