### ISSUE TITLE
ng serve Incremental Build Times Increased Massively When Upgrading From Angular v12 -> v15

### ISSUE THREAD

**Issue by fearghalom** [angular/angular-cli#24634]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.17

### Description

I recently tried to upgrade our large enterprise application (~1300 components) from Angular v12 to v15.  After the upgrade, I noticed that 'ng serve' incremental build times had increased from around (15s - 25s) on Angular v12 to (115s - 130s) on Angular v15. This kind of degradation in build performance was not expected.  Here are my settings in the angular.json file for our 'development' config. 

  "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true,
              "aot": false,
              "progress": true
            }

I tried a number of thing to see if I could bring down the time. One that gave a limited improvement was to move the entries from the "scripts" section in the angular.json file and directly reference them in the index.html file via script tags instead. This reduced the incremental build times to (95s - 100s) 

### Minimal Reproduction

I wasn't able to reproduce issue in a smaller application and I can't share our code base. 

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 15.0.4
Node: 14.21.2
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.0.3
@angular/flex-layout            14.0.0-beta.41
@angular/material               15.0.3
@schematics/angular             15.0.4
rxjs                            6.6.0
typescript                      4.8.4
```

**Comment by alan-agius4** [comment]
Can you please share the entire `build` and `serve` sections of your `angular.json` and the exact command that you are executing?

**Comment by fearghalom** [comment]
> Can you please share the entire `build` and `serve` sections of your `angular.json` and the exact command that you are executing?

        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "allowedCommonJsDependencies": [
              "lodash",
              "highcharts",
              "moment-timezone",
              "daterangepicker",
              "jquery",
              "wolfy87-eventemitter",
              "css-element-queries",
              "pdfmake/build/pdfmake",
              "pdfmake/build/vfs_fonts",
              "html2canvas",
              "ipaddr.js",
              "deepmerge",
              "moment/moment",
              "vis",
              "messageformat"
            ],
            "outputPath": "dist/my-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "preserveSymlinks": true,
            "assets": [
              "src/assets"
            ],
            "styles": [
              "./node_modules/please-wait/build/please-wait.css",
              "./node_modules/bootstrap/dist/css/bootstrap.min.css",        
              "./node_modules/vis/dist/vis.css",
              "./node_modules/fullpage.js/dist/jquery.fullpage.min.css",
              "./node_modules/ag-grid-community/dist/styles/ag-grid.css",
              "./node_modules/ag-grid-community/dist/styles/ag-theme-balham.css",
              "./node_modules/@angular/material/_theming.scss",
              "./node_modules/angular-archwizard/archwizard.scss",
              "./node_modules/daterangepicker/daterangepicker.css",
              "style.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/assets/sass"
              ]
            },
            "scripts": [
              "./node_modules/.../script1.js",
              "./node_modules/.../script2.js",
	      "./node_modules/.../script2.js",
            ]
          },
          "configurations": {
            "production": {
              "outputHashing": "none",
              "customWebpackConfig": {
                "path": "./custom-webpack.prod.js"
              },
              "buildOptimizer": true,
              "optimization": false,
              "sourceMap": false,
              "aot": true
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true,
              "aot": false,
              "progress": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "my-app:build:development",
            "port": 3000
          },
          "configurations": {
            "production": {
              "browserTarget": "my-app:build:production"
            },
            "development": {
              "browserTarget": "my-app:build:development"
            },
            "defaultConfiguration": "development"
          }
        },

The command: **node --max-old-space-size=16384 ./node_modules/@angular/cli/bin/ng serve**

**Comment by fearghalom** [comment]
I was using the custom 3rd party build for the production build but still using "@angular-devkit/build-angular:dev-server" for the dev build (ng serve). 
I updated the angular.json anyway to remove the usage of the custom builder but it made no impact to the build times.

        "build": {
          "builder": **"@angular-devkit/build-angular:browser",**
          "options": {
            "allowedCommonJsDependencies": [
              "lodash",
              "highcharts",
              "moment-timezone",
              "daterangepicker",
              "jquery",
              "wolfy87-eventemitter",
              "css-element-queries",
              "pdfmake/build/pdfmake",
              "pdfmake/build/vfs_fonts",
              "html2canvas",
              "ipaddr.js",
              "deepmerge",
              "moment/moment",
              "vis",
              "messageformat"
            ],
            "outputPath": "dist/my-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "preserveSymlinks": true,
            "assets": [
              "src/assets"
            ],
            "styles": [
              "./node_modules/please-wait/build/please-wait.css",
              "./node_modules/bootstrap/dist/css/bootstrap.min.css",        
              "./node_modules/vis/dist/vis.css",
              "./node_modules/fullpage.js/dist/jquery.fullpage.min.css",
              "./node_modules/ag-grid-community/dist/styles/ag-grid.css",
              "./node_modules/ag-grid-community/dist/styles/ag-theme-balham.css",
              "./node_modules/@angular/material/_theming.scss",
              "./node_modules/angular-archwizard/archwizard.scss",
              "./node_modules/daterangepicker/daterangepicker.css",
              "style.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "src/assets/sass"
              ]
            },
            "scripts": [
              "src/assests/script1.js",
              "src/assests/script2.js",
			  "src/assests/script2.js",
            ]
          },
          "configurations": {
            "production": {
              "outputHashing": "none",
              "customWebpackConfig": {
                "path": "./custom-webpack.prod.js"
              },
              "buildOptimizer": true,
              "optimization": false,
              "sourceMap": false,
              "aot": true
            },
            "development": {
              "buildOptimizer": false,
              "optimization": false,
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true,
              "aot": false,
              "progress": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "my-app:build:development",
            "port": 3000
          },
          "configurations": {
            "production": {
              "browserTarget": "my-app:build:production"
            },
            "development": {
              "browserTarget": "my-app:build:development"
            },
            "defaultConfiguration": "development"
          }
        },

**Comment by alan-agius4** [comment]
Hi @fearghalom, in that case we'd require an CPU profile to investigate this any further.

**Comment by fearghalom** [comment]
Hi Alan, do you have instructions on how to do that?

**Comment by alan-agius4** [comment]
See: https://github.com/angular/angular-cli/blob/main/docs/DEVELOPER.md#cpu-profiling

**Comment by fearghalom** [comment]
[cpuprofile.zip](https://github.com/angular/angular-cli/files/10568928/cpuprofile.zip)

**Comment by alan-agius4** [comment]
@fearghalom, are these profile for a build? I am not seeing much happening in these. Mostly it's just the process being idle.

<img width="1728" alt="Screenshot 2023-02-03 at 11 23 53" src="https://user-images.githubusercontent.com/17563226/216576487-7145d885-a939-46a0-b1c2-58708471b900.png">
<img width="1532" alt="Screenshot 2023-02-03 at 11 25 02" src="https://user-images.githubusercontent.com/17563226/216576494-81aa480a-b643-4899-8650-ffe71efc3dc5.png">

**Comment by fearghalom** [comment]
These cpu profile logs were recorded for 'ng serve':
node --cpu-prof --max-old-space-size=16384 ./node_modules/@angular/cli/bin/ng serve

I noticed that there were 5 .cpuprofile files produced during the initial build but nothing was logged after that.

**Comment by alan-agius4** [comment]
Since you are profiling a rebuild in this case it would probably better to profile manually using the steps mentioned in https://github.com/angular/angular-cli/issues/8259#issue-269908550

**Comment by fearghalom** [comment]
Here's the profile for the rebuild:
[rebuild_profile_CPU-20230203T225405.zip](https://github.com/angular/angular-cli/files/10583388/rebuild_profile_CPU-20230203T225405.zip)

**Comment by alan-agius4** [comment]
Thanks for the profile. 

I did take a look at it and I can see is that there are a lot of IO operations specifically `readlinkSync` with aggregated total time of `57.79s`.

See screenshots below; 
<img width="1614" alt="Screenshot 2023-02-08 at 12 09 50" src="https://user-images.githubusercontent.com/17563226/217516155-3c179034-abc7-4eb9-8384-20f9f0d0d0fe.png">
<img width="1665" alt="Screenshot 2023-02-08 at 12 20 41" src="https://user-images.githubusercontent.com/17563226/217516166-47de6a5a-f56e-4abb-a55c-f725c65d804f.png">

Also, I recommend is to update to Node.js 16, remove `--max-old-space-size=16384` which should not be needed with Node.js 16 and see if the problem is still reproducible.

That said, I highly doubt that this is something that we can action from our end.

**Comment by fearghalom** [comment]
Thanks Alan for taking a look. I had actually upgraded to Node v18.10.0 to perform the profiling as it was crashing when I tried to use v14.21.2. I gave Node v16 a go also but it didn't make any difference to the rebuild times. 

Can anything further be done on this? We probably can't move to v15 with these rebuild times. As I mentioned previously, I tried with angular 14  and the rebuild times were also slow but Angular 13 was comparable to Angular 12. 

One thing I did notice that brought down the rebuild time, was to remove the entries from the "scripts" section in the angular.json file and reference them directly in the index.html file. Doing this,  knocked about 30 seconds off the rebuild time. 
I profiled it and it seems that having even one item in the scripts section of the angular.json file, results in the Webpack DescriptionFileUtils.loadDescriptionFile() method being invoked for what looks like every dependency in the project. When I the leave the "scripts" entry blank in angular.json, the number of times DescriptionFileUtils.loadDescriptionFile() is invoked decreases significantly on rebuilds.

**Comment by alan-agius4** [comment]
`DescriptionFileUtils.loadDescriptionFile()` is used to load the package json file of each dependency, while indeed there are a lot of calls to this method, these are mostly cached. 

I tried to replicate your problem by adding 6 scripts, but the re-build performance was not impacted that much, in my case it was increased by less than 100ms. 

Can you try to replicate the issue in a ng-new application?

**Comment by fearghalom** [comment]
In a small application it doesn't seem to make a noticeable difference. However, in our large application, rebuilds are taking ~120s seconds in Angular v15, with about ~30 seconds of that down to specifying entries in the angular.json scripts section.

I created a new Angular application and modified _DescriptionFileUtils.loadDescrioptionFile()_ to add console logging. What I noticed when I added a single entry to the scripts section in angular.json, that the number of times the _loadDescriptionFile()_ method was invoked increased significantly, on the initial build and the rebuilds. 

Why would the addition of an external JS file result in additional lookups? Does the cache work differently, when a script is specified? I wouldn't have thought an external script would impact it.

**Comment by alan-agius4** [comment]
> In a small application it doesn't seem to make a noticeable difference.

If it is indeed `script` related, it should not make any difference if the application is small or large. `scripts` are handled completely different from application code. 

> I created a new Angular application and modified DescriptionFileUtils.loadDescrioptionFile() to add console logging. What I noticed when I added a single entry to the scripts section in angular.json, that the number of times the loadDescriptionFile() method was invoked increased significantly, on the initial build and the rebuilds. 

On an `ng new` application, `DescriptionFileUtils.loadDescrioptionFile()` is called thousands of times. To be precise (3373). Adding a script should only cause a couple of extra calls (3377). Can you provide more details about how are you seeing something different? 

> Why would the addition of an external JS file result in additional lookups? Does the cache work differently, when a script is specified? I wouldn't have thought an external script would impact it.

A script needs to be resolved and that is why the extra lookup. But this should only be a handful of lookups at most.

**Couple of other observations:**
- One thing I noticed is that you have enabled `preserveSymlinks`, can you try to remove it?
- Can you also please provide the output of `ng cache info`?

**Comment by fearghalom** [comment]
I created a new Angular project:

_Angular CLI: 15.1.4
Node: 16.19.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 15.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.4
@angular-devkit/build-angular   15.1.4
@angular-devkit/core            15.1.4
@angular-devkit/schematics      15.1.4
@angular/cli                    15.1.4
@schematics/angular             15.1.4
rxjs                            7.8.0
typescript                      4.9.5_


==============================================================================

I ran the following commands and noted the number of times DescriptionFileUtils.loadDescrioptionFile() was invoked:

1.  'ng cache clean'
2.  'ng serve' - loadDescriptionFile() invoked 5487 times
3.  'ng serve' - loadDescriptionFile() invoked 26 times
4.  'ng serve': loadDescriptionFile() invoked 26 times
5.  I made a trivial change to app.module.ts resulting in a rebuild:  loadDescriptionFile() invoked 4 times

I then installed bootstrap@5.2.3 and referenced the bootstrap.js in angular.json:

 "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/sample-application",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": [
              "zone.js"
            ],
            "tsConfig": "tsconfig.app.json",
            "inlineStyleLanguage": "scss",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              **"node_modules/bootstrap/dist/js/bootstrap.js"**
            ]
          },

I ran the same commands again and noted the number of times DescriptionFileUtils.loadDescrioptionFile() was invoked when an external script was added to the angular config:

1.  'ng cache clean'
2.  'ng serve' - loadDescriptionFile() invoked 6264 times 
3.  'ng serve' - loadDescriptionFile() invoked 1911 times
4.  'ng serve': loadDescriptionFile() invoked 1911 times
5.  I made a trivial change to app.module.ts resulting in a rebuild:  loadDescriptionFile() invoked 38 times


**Output of 'ng cache info':**
Enabled: yes
Environment: local
Path: C:\temp\angular15_clean\sample-application\.angular\cache
Size on disk: 82.90 MB
Effective status on current machine: enabled

**Comment by fearghalom** [comment]
I also examined the existing project where I noticed the initial problem but removed a large chunk of the code to reduce the build times. The difference in the rebuild times was still quite pronounced, when I included an external script in the angular config file as opposed to when I didin't. I removed the 'preserveSymlinks' setting as requested. The rebuild times (excluding the first rebuild) take ~3 seconds when no external script is specified, to about ~36 seconds when a single script (bootstrap.js) is specified in angular.json. 

_Angular CLI: 15.0.5
Node: 16.19.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 15.0.4
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.5
@angular-devkit/build-angular   15.0.5
@angular-devkit/core            15.0.5
@angular-devkit/schematics      15.0.5
@angular/cdk                    15.1.1
@angular/cli                    15.0.5
@angular/compiler-cli           15.1.1
@angular/flex-layout            15.0.0-beta.42
@angular/localize               15.1.1
@angular/material               15.1.1
@schematics/angular             15.0.5
rxjs                            7.5.7
typescript                      4.8.4_

==============================================================================

I ran the following commands and noted the number of times _DescriptionFileUtils.loadDescrioptionFile()_ was invoked:

1.  'ng cache clean'
2.  'ng serve' - loadDescriptionFile() invoked 350077 times
3.  'ng serve' - loadDescriptionFile() invoked 10468 times
4.  'ng serve' - loadDescriptionFile() invoked 10468  times
5.  I made a trivial change to app.module.ts resulting in a rebuild: loadDescriptionFile() invoked 323500 times (took ~29 secs)
6.  I made a 2nd trivial change to app.module.ts resulting in a rebuild: loadDescriptionFile() invoked 38 times (took ~3 secs)
7.   I made a 3rd trivial change to app.module.ts resulting in a rebuild: loadDescriptionFile() invoked 38 times (took ~3 secs)

I ran the same commands again and noted the number of times _DescriptionFileUtils.loadDescrioptionFile()_ was invoked when an external script (bootstrap.js) was added to the angular config:

1.  'ng cache clean'
2.  'ng serve' - loadDescriptionFile() invoked 630589 times
3.  'ng serve' - loadDescriptionFile() invoked 623009 times
4.  'ng serve' - loadDescriptionFile() invoked 623009 times
5.  I made a trivial change to app.module.ts resulting in a rebuild: loadDescriptionFile() invoked 599413 times  (took ~37 secs)
6.  I made a 2nd trivial change to app.module.ts resulting in a rebuild: loadDescriptionFile() invoked 596959 times (took ~36 secs)
7.   I made a 3rd trivial change to app.module.ts resulting in a rebuild: loadDescriptionFile() invoked 596983 times (took ~36 secs)

**Comment by alan-agius4** [comment]
Thanks for providing all this information. 

I continuing looking into it and extra calls to `loadDescriptionFile` are being done when the resolver is being retrieved. https://github.com/angular/angular-cli/blob/2a42f24cedf1785b0612467c6aa8848054d47b09/packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts#L103-L107

While, I don't understand exactly why Webpack is doing this as it should't. I do have some ideas. Can you try to apply the below two changes by copy and paste the contents of the below 2 files in `node_modules/@angular-devkit/build-angular/src/webpack/plugins/scripts-webpack-plugin.js` and see if any of these improve your re-build times.

https://gist.github.com/alan-agius4/c58eb1b5b08af81505bced60c3c4e2ad
https://gist.github.com/alan-agius4/6d23ce2af4cbfe2ba1b9096be5a15203

Thanks.

**Comment by fearghalom** [comment]
I tried both updates and they both brought down the number of invocations of _loadDescriptionFile()_ to a level similar to when no scripts are specified. The initial build with the second version of the script, seemed to have slightly less invocations of _loadDescrptionFile()_ for the initial build.

**Comment by fearghalom** [comment]
On rebuilds, it knocked ~35secs off the time.

**Comment by alan-agius4** [comment]
@fearghalom, thanks for the confirmation.

**Comment by fearghalom** [comment]
Another thing I've noticed is that there is a big time lapse between the display of the "√ Browser application bundle generation complete." message and the display of the build stats with the "√ Compiled successfully." message. The build time displayed doesn't seem to reflect the actual time until the build stats are displayed. 
The log messages in dev-server\index.js (logger.info) seem to be buffered or something. I added in console.log statements where the "Compiled successfully" message is logged and it was output a lot earlier (over a minute earlier) than the equivalent logger.info statements. 
I presume the cache is being updated after the bundles have been generated.

**Comment by fearghalom** [comment]
In the output below, the rebuild time is showing as **16069ms** but in the 'Compiled successfully' message isn't displayed until about ~90secs after the code change was made.


```
| Generating browser application bundles (phase: emitting)...
√ Browser application bundle generation complete.

Initial Chunk Files | Names   | Raw Size
main.js             | main    | 88.52 MB |
runtime.js          | runtime |  6.86 kB |

4 unchanged chunks

Build at: 2023-02-14T13:52:09.579Z - Hash: 2c7f512f92890b16 - Time: 16069ms

√ Compiled successfully.
```
