### ISSUE TITLE
ng serve is not working in windows 7

### ISSUE THREAD

**Issue by edcastpratosh** [angular/angular-cli#2463]
### OS?
> Windows 7

### Versions.
ngular-cli: 1.0.0-beta.15                                                                                                                                 
node: 6.3.0                                                                                                                                                
os: win32 x64 

### The log given by the failure.
> 0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\angular\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.5
3 info using node@v6.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle netninja@0.0.0~prestart: netninja@0.0.0
6 silly lifecycle netninja@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle netninja@0.0.0~start: netninja@0.0.0
8 verbose lifecycle netninja@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle netninja@0.0.0~start: PATH: C:\Users\angular\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;d:\workspace\angualr2\netninja\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files\Git\cmd;C:\Program Files\MongoDB\Server\3.0\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\angular\AppData\Local\Android\android-sdk\tools;C:\Users\angular\AppData\Local\Android\android-sdk\platform-tools;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\angular\AppData\Roaming\nvm;C:\Users\angular\AppData\Roaming\npm;C:\Program Files (x86)\Google\google_appengine\
10 verbose lifecycle netninja@0.0.0~start: CWD: d:\workspace\angualr2\netninja
11 silly lifecycle netninja@0.0.0~start: Args: [ '/d /s /c', 'ng serve' ]
12 silly lifecycle netninja@0.0.0~start: Returned: code: 3221225501  signal: null
13 info lifecycle netninja@0.0.0~start: Failed to exec start script
14 verbose stack Error: netninja@0.0.0 start: `ng serve`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\angular\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\angular\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid netninja@0.0.0
16 verbose cwd d:\workspace\angualr2\netninja
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\angular\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.3.0
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error netninja@0.0.0 start: `ng serve`
22 error Exit status 3221225501
23 error Failed at the netninja@0.0.0 start script 'ng serve'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the netninja package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ng serve
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs netninja
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls netninja
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by fullstackdave** [comment]
This looks like the error I received when I manually changed the version number in the angular-cli.json file.  If you make any modifications to the angular-cli.json file, make sure you do them one at a time and address any errors you may cause before moving on.

**Comment by filipesilva** [comment]
@edcastpratosh can you give me the console error you got when running `ng serve`?

**Comment by hantsy** [comment]
I got the similar **ELIFECYCLE** errors when upgrading to Angular  CLI 1.0.0-beta.17/Node 6.8.1. I removed node_modules, changed the version of  `angular-cli`  and upgrade my codes to Angular CLI 1.0.0-beta.17 from 1.0.0-beta.16. 

```
 $ npm run start                                                             
                                                                            
> angular2-sample@0.0.0 start E:\hantsylabs\angular2-sample\vanilla         
> ng serve                                                                  
                                                                            
Error                                                                       
                                                                            
npm ERR! Windows_NT 10.0.14393                                              
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\node
node_modules\\npm\\bin\\npm-cli.js" "run" "start"                           
npm ERR! node v6.8.1                                                        
npm ERR! npm  v3.10.8                                                       
npm ERR! code ELIFECYCLE                                                    
npm ERR! angular2-sample@0.0.0 start: `ng serve`                            
npm ERR! Exit status 1                                                      
npm ERR!                                                                    
npm ERR! Failed at the angular2-sample@0.0.0 start script 'ng serve'.       
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-sample p
ge,                                                                         
npm ERR! not with npm itself.                                               
npm ERR! Tell the author that this fails on your system:                    
npm ERR!     ng serve                                                       
npm ERR! You can get information on how to open an issue for this project wi
npm ERR!     npm bugs angular2-sample                                       
npm ERR! Or if that isn't available, you can get their info via:            
npm ERR!     npm owner ls angular2-sample                                   
npm ERR! There is likely additional logging output above.                   
                                                                            
npm ERR! Please include the following file with any support request:        
npm ERR!     E:\hantsylabs\angular2-sample\vanilla\npm-debug.log            
```

The `npm install` is executed successfully. But got warning like the following. It seems npm was trying to install the latest `@angular/platform-server@2.1.0`:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN @angular/compiler-cli@0.6.4 requires a peer of @angular/platform-server@2.0.2 but none was installed.
npm WARN @angular/platform-server@2.1.0 requires a peer of @angular/core@2.1.0 but none was installed.
npm WARN @angular/platform-server@2.1.0 requires a peer of @angular/common@2.1.0 but none was installed.
npm WARN @angular/platform-server@2.1.0 requires a peer of @angular/compiler@2.1.0 but none was installed.
npm WARN @angular/platform-server@2.1.0 requires a peer of @angular/platform-browser@2.1.0 but none was installed.
```

I installed `@angular/platform-server@2.0.2` to devDenpendencies, but no help.

**Comment by filipesilva** [comment]
@edcastpratosh this does sound like a `angular-cli.json` error, like @fullstackdave mentioned. In beta.18 we've improved the error message for that sort of error, but you still have to fix your `angular-cli.json` manually. 

Try to see what you changed relative to the default one.
