### ISSUE TITLE
Importing provider by short path makes lazy-route eager

### ISSUE THREAD

**Issue by Eugeno** [angular/angular-cli#24645]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

This lazy route:
```typescript
import { SomeService } from './some-path/some.service';

const routes: Routes = [
  {
    path: 'some-path',
    loadComponent: () => import('./some-path/some.component').then((m) => m.SomeComponent),
    providers: [SomeService],
  },
];
```
becomes eager when I create `index.ts` and export service:
```typescript
import { SomeService } from './some-path';
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.4
Node: 16.17.0
Package Manager: npm 8.3.0
OS: win32 x64

Angular: 15.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.4
@angular-devkit/build-angular   15.1.4
@angular-devkit/core            15.1.4
@angular-devkit/schematics      15.1.4
@angular/cdk                    14.2.7
@angular/cli                    15.1.4
@schematics/angular             15.1.4
rxjs                            7.8.0
typescript                      4.9.4
```

**Comment by alan-agius4** [comment]
Does the barrel files also exports the component? If so, this is working as expected as bundlers cannot perform code motion. 

See https://github.com/angular/angular/issues/37576#issuecomment-712735416

**Comment by Eugeno** [comment]
@alan-agius4 no, same behavior even if `index.ts` exports only this service.

**Comment by alan-agius4** [comment]
I am not able to replicate the issue using the provided code. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Eugeno** [comment]
I can't reproduce this in the new repository, will investigate the issue further.
Thank you for your time!
