### ISSUE TITLE
Angular CLI v15.1.4 is causing error 137 on AzureDev CI/CD Pipeline

### ISSUE THREAD

**Issue by thaoula** [angular/angular-cli#24647]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v15.1.3

### Description

The appears to be some memory regression that is causing v15.1.4 to fail during CI/CD builds with npm error 137 which is an out of memory exception.

We are already using --max_old_space_size=8096 to avoid this error but it now seems something in 15.1.4 is using more memory than 15.1.3.

### Minimal Reproduction

I cannot share our repository but we a simply using the following command: 
`ng build --configuration production`

Changing package json as below results in Error 137 on build pipeline. 
` "@angular/cli": "15.1.3" ->     "@angular/cli": "15.1.4"`

Reverting back results in a succesful build.

### Exception or Error

```text
- Generating browser application bundles (phase: setup)...
Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! jms@1.0.0 build.dist: `ng build $npm_package_config_app --configuration production`
npm ERR! Exit status 137
```

### Your Environment

```text
Angular CLI: 15.1.3
Node: 16.18.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.1.0
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.1
@angular-devkit/build-angular   15.1.1
@angular-devkit/core            15.1.1
@angular-devkit/schematics      15.1.1
@angular/cdk                    15.0.0
@angular/cli                    15.1.1
@schematics/angular             15.1.1
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by alan-agius4** [comment]
Hi @thaoula,

Thanks for reporting the issue. 

There has not been any changes in the `@angular/cli` package between 15.1.3 and 15.1.4. See the diff: https://github.com/angular/angular-cli/compare/15.1.3...15.1.4. 

The two changes were both in `@angular-devkit/build-angular`, and none of which effects `ng build`.

**Comment by thaoula** [comment]
Hi @alan-agius4,

Thanks for quick reply. 

I tried setting back to 15.1.4 today an it broke again. 

Would any dependancies have changed as part of the new release?

Just to be clear, I am assuming, the memory that is being referred to here by npm is the --max_old_space_size=8096 setting right?

FYI - The Azure DevOps agent only has 7gb of ram. 

Regards,
Tarek

**Comment by alan-agius4** [comment]
> Would any dependancies have changed as part of the new release?

No, and technically in the `@angular/cli` package there are no build related operations as it’s more of an orchestrator.

The `Killed` message makes me think the the process was killed by systems OOM killer, in this case the OS kills the process to avoid an OOM.  One reason for this might be that the `max_old_space_size` being set is larger than the free memory on the system. You stated that you have 7Gb available, but  you are setting this to 8Gb. Apart from the fact that you are setting a limit higher than what you have actually available, you are also not leaving any memory for other processes. So, my recommendation would be to try to remove this option, or reduce it to 6Gb.

probably suggest to either remove it or cap it at 6gb to leave some memory available for OS processes.

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by zeljkoantich** [comment]
Hey @thaoula can you share your package.json Angular v15.1.1, working dependencies?
I have something similar on AWS CodeBuild, it's failing with 137 exit code also.
