### ISSUE TITLE
Issue on building with production app-shell with different outputPath for 

### ISSUE THREAD

**Issue by Alessandroinfo** [angular/angular-cli#24657]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, core

### Is this a regression?

Yes

### Description

**What happen:**
When i try to run a build of app-shell production with  `ng run angular15-app-shell:app-shell:production
 ` i retrieve this error:

```
✖ Application shell generation failed.
Could not find server output directory: /Users/user/WebstormProjects/angular15-app-shell/dist/angular15-app-shell/server.
```

This happen when i change in `angular.json` the outputPath in `projects.angular15-app-shell.architect.build.outputPath`.
From `"outputPath": "dist/angular15-app-shell/browser"` to `"outputPath": "dist"`

**Step to reproduce:**
1. `npx -p @angular/cli@15.1.4 ng new angular15-app-shell` (with routing and select whatever stylesheet)
2. `cd angular15-app-shell`
3. npx ng g app-shell
4. Change outputPath for the build to `dist` (it will be `"outputPath": "dist"`)
5. npx ng run angular15-app-shell:app-shell:production

I tested on Angular 15.1.4 but it happen also on versione >14.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-huphbj

### Please provide the exception or error you saw

```true
The error happens only after changing  to ```dist```

```
✖ Application shell generation failed.
Could not find server output directory: /Users/user/WebstormProjects/angular15-app-shell/dist/angular15-app-shell/server.
```
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.4
Node: 14.21.2
Package Manager: npm 6.14.17
OS: darwin arm64

Angular: 15.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.4
@angular-devkit/build-angular   15.1.4
@angular-devkit/core            15.1.4
@angular-devkit/schematics      15.1.4
@angular/cli                    15.1.4
@schematics/angular             15.1.4
rxjs                            7.8.0
typescript                      4.9.5
```

### Anything else?

I run it on node v14.21.2.

**Comment by alan-agius4** [comment]
This is expected. 

The app-shell builder triggers 2 builds on to build the server and another one to build the browser. What is happening here is that browser build will cause the output of the server build located in `dist/angular15-app-shell/server` to be deleted since `deleteOutputPath` is enabled which subsequently causes the app-shell generation to fail with the above error. 

If you wish to keep the browser output to be directly in `dist` you have 2 options;
1. Disable `deleteOutputPath`
2. Change the server builder `outputPath` to be outside of `dist`, example: `"outputPath": "dist-server".`

**Comment by Alessandroinfo** [comment]
Thank you for the clarification.
I changed directories for both and now it builds correctly.  I believed that on compile it is created when not present.

Just as a clarification.
In this case what is compiled into the dist/server directory, what are the contained JS for?
I expect compiling the app shell there is just the index with the shell pre-rendered.

**Comment by alan-agius4** [comment]
In `dist/server` there is a server version of the application which is needed to generate the app-shell. Internally the app-shell builder will invoke this and generate the app-shell in the index.html file. 

Unless you are using SSR this does not need to be deployed.

**Comment by Alessandroinfo** [comment]
> 

Perfect now i have understood everything. Many thanks for your time @alan-agius4
