### ISSUE TITLE
Global styles linking in angular.json does not work is they come from library assets

### ISSUE THREAD

**Issue by yohny** [angular/angular-cli#24664]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I have an library project that includes some assets like icons and some global styles. Those are packaged in `assets` folder of library. Consuming application includes library assets by extending the `assets` section in its `angular.json`:
```json
"assets": [
    "projects/my-app/src/favicon.ico",
    "projects/my-app/src/assets",
    {
      "input": "dist/my-lib/assets", // with regular install this would go from node_modules instead of dist
      "glob": "**/*",
      "output": "assets/my-lib"
    }
  ],
```
when build, the library assets are copied into `assest/my-lib` folder of consuming application as expected.
The issue occurs when I want to use the library style from `assest/my-lib/styles.css`. If I add it to `styles` section of `angular.json` like this:
```json
"styles": [
    "projects/my-app/src/styles.css",
    "projects/my-app/src/assets/my-lib/styles.css" // added
  ],
```
it ends with error:  `Error: Can't resolve 'projects/my-app/src/assets/my-lib/styles.css'`
However when I add it in `index.html. like this `<link rel="stylesheet" href="assets/my-lib/styles.css">` it works as expected.

It looks like `styles` processing happens before `assets`copying, which results in the error. Expectation is that assets are copied before the styles/scripts linking because those can reference assets.

### Please provide a link to a minimal reproduction of the bug

https://github.com/yohny/assets-demo

### Please provide the exception or error you saw

```true
Error: Can't resolve 'projects/my-app/src/assets/my-lib/styles.css'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.4
Node: 16.19.0
Package Manager: npm 8.19.3
OS: linux x64

Angular: 15.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.4
@angular-devkit/build-angular   15.1.4
@angular-devkit/core            15.1.4
@angular-devkit/schematics      15.1.4
@angular/cli                    15.1.4
@schematics/angular             15.1.4
ng-packagr                      15.1.1
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
- When using the `styles` option you should not place the same stylesheet in the `assets` option. These option serve for different purposes. In your case you should  add`"dist/my-lib/assets/styles.css"` to the `styles` option and remove the `assets` entry. See: https://angular.io/guide/workspace-config for more information. 
- The error in this case is correct as indeed there is no such file as `projects/my-app/src/assets/my-lib/styles.css`.
- Be sure to build you library prior of building your application.
- You need to export the CSS/assets file https://angular.io/guide/creating-libraries#managing-assets-in-a-library

Closing as this issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
