### ISSUE TITLE
Loading google fonts with @import tag in scss doesn't work. Throws error.

### ISSUE THREAD

**Issue by purushottamjha** [angular/angular-cli#2466]
When I do this:
// Fonts
@import 'https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900';

I get this error:

ERROR in ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss
Module build failed: CssSyntaxError: css-loader-parser: /Users/purushottamj/workspaces/mithilatech/mithilatech-frontend/styles.scss:1:0: Unexpected formathttps://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900

> 1 | @import https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900;

### OS?
Mac OSX (Sierra)

### Versions.
angular-cli: 1.0.0-beta.16
node: 4.2.4
os: darwin x6

**Comment by grizzm0** [comment]
Can you try wrapping the path with url() ? I believe this is a libsass issue and not related to angular-cli.

**Comment by purushottamjha** [comment]
Wrapping it in url() works perfect. Thank you :)
