### ISSUE TITLE
Module build failed Error in compile time

### ISSUE THREAD

**Issue by DilipV2503** [angular/angular-cli#24675]
### Command

other

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

**Hii, 
I am getting this error while we connecting web-sdk into our angular project**

![InkedError](https://user-images.githubusercontent.com/83951998/217490308-6bd473c3-4cbf-49c7-b963-d92fb51854ab.jpg)

please help me out to solve this error.

Thank you

### Minimal Reproduction

NA

### Your Environment

```text
Angular CLI: 10.0.8
Node: 16.15.0
OS: win32 x64

Angular: 10.1.6
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
