### ISSUE TITLE
Jeet.gs and Rupture in Stylus, how configure?

### ISSUE THREAD

**Issue by nvrossett** [angular/angular-cli#2467]
Anybody know if Is possible add this features (Jeet.gs and Rupture) on the Stylus that is used with Angular-Cli?

**Comment by JanStureNielsen** [comment]
@nvrossett -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

**Comment by filipesilva** [comment]
We don't currently have a way to configure CSS proprocessors.

**Comment by gpradeepjain** [comment]
Hi,

Is there a way to configure rupture with angular cli now in 2017?

**Comment by LFeh** [comment]
Do you have a solution about it @nvrossett?

**Comment by nvrossett** [comment]
Hi @LFeh =)

Nothing, even stopped studying Angular 2 because I did not feel comfortable with the workflow without these tools, in fact today without Rupture

I do not know how you are today, but to this day I do not know any solution.

Today I am venturing with Vue.js and enjoying a lot, for me is what the Angular 2 should have become, has several similarities with AngularJS and React.

For me it joins the best of the 2 worlds

-------------

Nada, até deixei de estudar Angular 2 por que não me senti confortável com a workflow sem essas ferramentas, na verdade hoje sem o Rupture

Não sei como está hoje, mas até hoje não conheço nenhuma solução.

Hoje estou me aventurando com Vue.js e curtindo muito, para mim é o que o Angular 2 deveria ter se tornado, tem varias similaridades com o AngularJS e React.

Para mim une o melhor dos 2 mundos

**Comment by rohith** [comment]
FWIW, do `yarn add rupture -D` or `npm install rupture -D` then add `stylePreprocessorOptions` to `.angular-cli.json` file like so

```json
"styles": [
  "styles.styl"
],
"stylePreprocessorOptions": {
  "includePaths": [
  "../node_modules/rupture/"
  ]
}
```

rupture can now be accessed with `@import "rupture"` statement. Import it in the global `styles.styl` file to access rupture across the app without individual import statements in multiple files

**Comment by LFeh** [comment]
@rohith Does it works?

**Comment by LFeh** [comment]
Amazing.

And a PostCSS libs... do you have any solution to load with angular-cli?

**Comment by rohith** [comment]
nope :disappointed: I got nothing on PostCSS
