### ISSUE TITLE
ng update (all new package to latest version)

### ISSUE THREAD

**Issue by egonknapen** [angular/angular-cli#24683]
### Command

update

### Description

Every week I check the packages, and need to ng update every package. 

Meaning, that it first will install a temporary new angular cli, than install the new angular cli and the rest.

Can't we just have a 

ng update all

Which just updates everything, to the latest version ?

### Describe the solution you'd like

> ng update all

or something similar. I'm updating the cli and the core, I wouldn't care about updating the cli alone, without the core. Angular has progressed so far, there is no real use to only update the cli. And I'm using cdk too, so if I update one (the core), I will always update the other (cdk), if available.

If only the cli is updated, than a ng update all would only update the @angular/cli package ofcourse.

Just to make life a little simpler...

### Describe alternatives you've considered

Every week I type:

> ng update @angular/cli @angular/core @angular/cdk

**Comment by alan-agius4** [comment]
We did previously have this functionality but it was decided to remove it. See: https://github.com/angular/angular-cli/pull/22572.

https://github.com/angular/angular-cli/issues/23023 should be a better alternative which also covers your use-case. 

That said, `ng update` is also typically only needed to update major versions, as during minors and patches code migrations are not added.
