### ISSUE TITLE
Browserslist is ignored.

### ISSUE THREAD

**Issue by liesahead** [angular/angular-cli#24697]
### Command

build, serve, test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v14

### Description

Browserlistrc is ignored for some reason and this warning was not present in v14.

### Minimal Reproduction

Steps to reproduce

1. Run `ng new *proj_name*`;
2. Change `target` in `tsconfig` to `ES2020`;
3. Run `ng serve`;
4. See warning `TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration.`;
5. Run `ng generate config browserslist`;
6. Run `ng serve`;
7. See warning `TypeScript compiler options "target" and "useDefineForClassFields" are set to "ES2022" and "false" respectively by the Angular CLI. To control ECMA version and features use the Browerslist configuration.`.

### Your Environment

```text
Angular CLI: 15.1.5
Node: 18.14.0
Package Manager: npm 9.4.2
OS: win32 x64

Angular: 15.1.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.5
@angular-devkit/build-angular   15.1.5
@angular-devkit/core            15.1.5
@angular-devkit/schematics      15.1.5
@angular/cli                    15.1.5
@schematics/angular             15.1.5
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
The ECMA version output controlled via the browserslist configuration. In this case "ES2020" in the TypeScript configuration is ignored and hence the warning.

You can set the "target" to "ES2022" in your TypeScript configuration to remove the warning.

**Comment by liesahead** [comment]
Thanks, it's clear now.
