### ISSUE TITLE
Generate command take a long time to execute

### ISSUE THREAD

**Issue by boskiv** [angular/angular-cli#24702]
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18

### Description

running `ng g m dashboard` take 4 minutes. Is the way to debug it where it stuck?

### Minimal Reproduction

nvm use 19
ng new my-app

### Your Environment

```text
Angular CLI: 15.1.5
Node: 19.5.0 (Unsupported)
Package Manager: npm 9.3.1
OS: darwin arm64
```

### Anything else relevant?

switching to 18 nodejs fix the problem

**Comment by alan-agius4** [comment]
Node 19 is not yet officially supported. 

You can check why it’s slow by generating a CPU profile. See: https://github.com/angular/angular-cli/blob/main/docs/DEVELOPER.md#cpu-profiling
