### ISSUE TITLE
Native code compile failed

### ISSUE THREAD

**Issue by Mufasa** [angular/angular-cli#2471]
### OS?
> Mac OSX (El Capitan v10.11.6)

### Versions.
> `ng --version`:
> Could not start watchman; falling back to NodeWatcher for file system events.
> Visit http://ember-cli.com/user-guide/#watchman for more info.
> angular-cli: 1.0.0-beta.16
> node: 6.5.0
> os: darwin x64

### Repro steps.
> `sudo npm install -g angular-cli`

### The log given by the failure.
> ...
> execSync@1.0.2 install /usr/local/lib/node_modules/angular-cli/node_modules/execSync
> node install.js
> 
> [execsync v1.0.2] Attempting to compile native extensions.
> [execSync v1.0.2]
>    Native code compile failed!!
> 
> node-zopfli@2.0.1 install /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
> ...

### Mention any other details that might be useful.
I used to use `angular2-webpack-starter` and that also gave me this error on install. I was advised by someone to try `ng-cli` but get the same issue here with the error **Native code compile failed!!**. My app however still seems to function but no one seems to know why this error occurs or its implications.

**Comment by JanStureNielsen** [comment]
@Mufasa -- the GitHub issue tracker is for project bugs and project feature requests as
noted in CONTRIBUTING.md. For better support, consider creating a question on
StackOverflow with all the details.

See this for some background: http://stackoverflow.com/questions/39812448/angular-cli-installation-failure

**Comment by Mufasa** [comment]
I have raised his in StackOverflow as advised - see here: http://stackoverflow.com/questions/39820132/angular-cli-install-error-native-code-compile-failed
