### ISSUE TITLE
ng serve external style urls turns into Invalid Ones

### ISSUE THREAD

**Issue by Twista** [angular/angular-cli#2472]
### OS?

OSX - El Capitan
### Versions.

angular-cli: 1.0.0-beta.16
node: 5.2.0
os: darwin x64

Include of external styles causes INVALID_URL for images

1) created new app using angular-cli
2) installed Leaflet (trough npm)
3) added styles into angular-cli.json

```
...
 "apps": [
    {
...
      "styles": [
        "styles.css",
        "../node_modules/leaflet/dist/leaflet.css"  
      ],
```

3) created marker in Leaflet - which produces this code

![img](https://cloud.githubusercontent.com/assets/1297511/19022735/324a8ff8-88df-11e6-8f6f-56ea679f5d32.png)

also tried put `@import "../node_modules/leaflet/dist/leaflet.css";` into my `style.css` but same result

**Comment by grizzm0** [comment]
Use `@import "~leaflet/dist/leaflet.css"`

**Comment by Twista** [comment]
Just tried and it does not help. The result is the same

**Comment by dimitriy-k** [comment]
```
      "styles": [
        "../node_modules/bootstrap-sass/assets/stylesheets/_bootstrap.scss",
        "./assets/styles/styles.scss"
      ],
```

that works for me, but I'm using SASS

**Comment by hansl** [comment]
We don't use `style-loader` anymore, so this issue might be fixed. Closing as such.

**Comment by karim-dev** [comment]
how can i add a link to css like "http://my.link.to/style.css" to "styles" : [ ] ?
Tahnks

**Comment by karim-dev** [comment]
Answer: styleUrls: [ "styles.css", "http://my.link.to/style.css" ]
Thank me
