### ISSUE TITLE
Can you add a base-path parameter with ng generate command

### ISSUE THREAD

**Issue by lsa-shanghai** [angular/angular-cli#24729]
### Command

generate

### Description

When I build angular library with Secondary Entry Points in a sample layout as below:
```
my_package 
├── src
|   ├── public_api.ts
|   └── *.ts
├── ng-package.json
├── package.json
└── testing
    ├── src
    |   ├── public_api.ts
    |   └── *.ts
    └── ng-package.json
```

I need to use `ng g` command under main entry point and Secondary Entry Points. But the command just works with "src\lib" as base path. 

### Describe the solution you'd like

Could you provide "base-path" parameter with `ng g` command.

**Comment by alan-agius4** [comment]
Hey, let’s continue tracking the generation of second entry-points in https://github.com/angular/angular-cli/issues/19070.

`ng g library` is definitely not intended to be used to generate a secondary entry-point, as it creates and Angular library project inside a workspace.
