### ISSUE TITLE
eval and new Function in csp script-src without unsafe-eval

### ISSUE THREAD

**Issue by hoosayn** [angular/angular-cli#24730]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Each and every file in my index.html is hashed 
index.html(after build)
```
<link href="assets/style/css/bootstrap-ar.min.css" rel="stylesheet">
  <link href="assets/style/css/font-awesome.min.css" rel="stylesheet">
  <link id="alignCssFileId" href="assets/style/css/custom-ar.css" rel="stylesheet">
  
  <script type="text/javascript" src="assets/style/js/jquery-3.6.0.slim.min.js" integrity="sha384-Qg00WFl9r0Xr6rUqNLv1ffTSSKEFFCDCKVyHZ+sVt8KuvG99nWw5RNvbhuKgif9z" crossorigin="anonymous"></script>

  <script src="assets/config/env.js" nonce="envfile"></script>

  <script type="text/javascript" src="assets/js/paper-full.min.js" integrity="sha384-F2XIobYzyqtqgJtz47uxaaSZcW74BXtLyaFzwmDCyGpcJhlQ2uOUix5qhFCrBHCk" crossorigin="anonymous"></script>

  <script type="text/javascript" src="assets/js/sketch.js" integrity="sha384-7JZMJBSgTv2Y0cEIC5IkoFKfI98P1NPO3jqlUouOZNo17nZC+CsniI/NcdHy9BSZ"></script>
  
<link rel="stylesheet" href="styles.css" crossorigin="anonymous" integrity="sha384-QdNSfd/w2DkkeesZlP/b50EpjayV2yEMRXink+/oG8PXWqKe3oz4zyhzKw3+4tq5"></head>
<body>
<app-root></app-root>
<script src="runtime-es2015.js" crossorigin="anonymous" type="module" integrity="sha384-ri9cS+UB3Kg44oWcATihqM4JaLd/vPeH44VxPBjnwYxbTN3Z+5n715V6lu17N1zg"></script>
<script src="runtime-es5.js" crossorigin="anonymous" nomodule defer integrity="sha384-56+79AY2vtppdq3/S+YH+Uav2yUXXn+z1KLU+uKv5UTSpWd39ouBt5EqG1KEmY9V"></script>
<script src="polyfills-es5.js" crossorigin="anonymous" nomodule defer integrity="sha384-qjU37w6G6Z+qVDUk8Yzwu2N5V/jpyaNDu3eCO+2CXGW1J2l6JkViCSkED7EUCi7u"></script>
<script src="polyfills-es2015.js" crossorigin="anonymous" type="module" integrity="sha384-Qy1zDsv7ndcJumiNepT27qatHsVczLau/WF4kn5fhoiqxbzqWygjEt7ngjvpetXe"></script>
<script src="main-es2015.js" crossorigin="anonymous" type="module" integrity="sha384-FEAUc/jPR/Cpjr+XEDZqiqYTezE3ZU6lZiCoTf75l3AlCbAj+s2YTkl3HrJjvOg4"></script>
<script src="main-es5.js" crossorigin="anonymous" nomodule defer integrity="sha384-ebjkV4WAnT/NpJ9Ql5DhVLwX43B1EpGP+oS3ZXxQUxJ2tat9rzWuceWmpUOpUK4i"></script></body>
</html>
```
My csp header looks like this,
```
"script-src 'self' 'strict-dynamic' 'nonce-envfile' " +
                "'sha384-ri9cS+UB3Kg44oWcATihqM4JaLd/vPeH44VxPBjnwYxbTN3Z+5n715V6lu17N1zg' " +
                "'sha384-56+79AY2vtppdq3/S+YH+Uav2yUXXn+z1KLU+uKv5UTSpWd39ouBt5EqG1KEmY9V' " +
                "'sha384-qjU37w6G6Z+qVDUk8Yzwu2N5V/jpyaNDu3eCO+2CXGW1J2l6JkViCSkED7EUCi7u' " +
                "'sha384-Qy1zDsv7ndcJumiNepT27qatHsVczLau/WF4kn5fhoiqxbzqWygjEt7ngjvpetXe' " +
                "'sha384-FEAUc/jPR/Cpjr+XEDZqiqYTezE3ZU6lZiCoTf75l3AlCbAj+s2YTkl3HrJjvOg4' " +
                "'sha384-ebjkV4WAnT/NpJ9Ql5DhVLwX43B1EpGP+oS3ZXxQUxJ2tat9rzWuceWmpUOpUK4i' " +
                "'sha384-7JZMJBSgTv2Y0cEIC5IkoFKfI98P1NPO3jqlUouOZNo17nZC+CsniI/NcdHy9BSZ' " +  //sketch
                "'sha384-F2XIobYzyqtqgJtz47uxaaSZcW74BXtLyaFzwmDCyGpcJhlQ2uOUix5qhFCrBHCk' " +  //paper
                "'sha384-Qg00WFl9r0Xr6rUqNLv1ffTSSKEFFCDCKVyHZ+sVt8KuvG99nWw5RNvbhuKgif9z' " +  //jquery
                ";style-src 'self' 'unsafe-inline';");
```
I am still get EvalError at    'eval'   in paper-full.min.js and   'new Function'  in main.js

I have recently migrated my application from angular7 to angular11 

### Minimal Reproduction

{
  "name": "project-frontend",
  "version": "2.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "startWithProxy": "ng serve --proxy-config proxy.conf.json --host 0.0.0.0",
    "build": "ng build --prod --subresourceIntegrity=true",
    "build-prod": "ng build --prod --subresourceIntegrity=true",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.2.5",
    "@angular/common": "~11.2.14",
    "@angular/compiler": "~11.2.14",
    "@angular/core": "~11.2.14",
    "@angular/forms": "~11.2.14",
    "@angular/platform-browser": "~11.2.14",
    "@angular/platform-browser-dynamic": "~11.2.14",
    "@angular/router": "~10.2.5",
    "@ng-bootstrap/ng-bootstrap": "^4.2.2",
    "@ng-idle/core": "^8.0.0-beta.4",
    "@ng-idle/keepalive": "^8.0.0-beta.4",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/moment-duration-format": "^2.2.3",
    "@umalqura/core": "0.0.7",
    "angular2-moment": "^1.9.0",
    "chart.js": "^2.9.4",
    "core-js": "^2.5.4",
    "countly-sdk-nodejs": "^20.11.0",
    "countly-sdk-web": "^21.11.3",
    "crypto-js": "^4.1.1",
    "file-saver": "^2.0.2",
    "messageformat": "^2.3.0",
    "moment": "^2.24.0",
    "moment-duration-format": "^2.3.2",
    "ngx-pagination": "^3.2.1",
    "ngx-smart-modal": "^7.1.1",
    "ngx-translate-messageformat-compiler": "^4.5.0",
    "rxjs": "~6.6.7",
    "tslib": "^2.0.0",
    "xlsx": "^0.17.1",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.19",
    "@angular/cli": "~11.2.19",
    "@angular/compiler-cli": "^11.2.14",
    "@angular/language-service": "~11.2.14",
    "@angular/localize": "^11.2.14",
    "@types/crypto-js": "^4.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.0",
    "typescript": "4.0.8"
  }
}

### Exception or Error

```text
![image](https://user-images.githubusercontent.com/9818126/219277698-301a927a-b434-474b-b09e-be4714c29d87.png)
```

### Your Environment

```text
Angular CLI: 11.2.19
Node: 14.20.0
OS: win32 x64

Angular: 11.2.14
... common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.19
@angular-devkit/build-angular   0.1102.19
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/animations             10.2.5
@angular/cli                    11.2.19
@angular/router                 10.2.5
@schematics/angular             11.2.19
@schematics/update              0.1102.19
rxjs                            6.6.7
typescript                      4.0.8
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by hoosayn** [comment]
I posted this on stackoverflow as well, I did not receive any suggestion to deal with this issue, or probably it is a new feature request. If you are aware of anything related to these, please suggest.
