### ISSUE TITLE
Error from global error handler TypeError: Cannot read properties of undefined (reading 'add')

### ISSUE THREAD

**Issue by dhamuace** [angular/angular-cli#24749]
### Command

build, run, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Getting this error in my app. And not able to fix it. Tried may ways from past 1 month. Please help.

Issue getting from : node_modules\@angular\platform-browser\fesm2015\platform-browser.mjs

Line number : 622 and 625.

![image](https://user-images.githubusercontent.com/8780505/219854758-10fbb458-e582-4e4d-89b4-c0cbd9da4f14.png)
![image](https://user-images.githubusercontent.com/8780505/219854873-2c65855c-b670-4333-bd52-9a736d37f2dc.png)
![image](https://user-images.githubusercontent.com/8780505/219854901-0551fb12-2614-4fb3-b25b-568c7c5d0e3b.png)

### Minimal Reproduction

When I go to this page I am getting the error : 

https://app.lottosocial.com/mainTabs/tabs/syndicate

Vendor JS file : https://app.lottosocial.com/vendor.fabb00d05b4c73bf.js

### Exception or Error

```text
vendor.fabb00d05b4c73bf.js:1 Error from global error handler TypeError: Cannot read properties of undefined (reading 'add')
    at lt.value (vendor.fabb00d05b4c73bf.js:1:3156453)
    at ee.value (vendor.fabb00d05b4c73bf.js:1:3144328)
    at vendor.fabb00d05b4c73bf.js:1:2661404
    at Array.forEach (<anonymous>)
    at un.value (vendor.fabb00d05b4c73bf.js:1:2661367)
    at vendor.fabb00d05b4c73bf.js:1:2660728
    at l.value (vendor.fabb00d05b4c73bf.js:1:2829619)
    at un.value (vendor.fabb00d05b4c73bf.js:1:2660558)
    at un.value (vendor.fabb00d05b4c73bf.js:1:2660042)
    at Ri (vendor.fabb00d05b4c73bf.js:1:2721911)
    at Ji (vendor.fabb00d05b4c73bf.js:1:2721706)
    at Fi (vendor.fabb00d05b4c73bf.js:1:2721423)
    at zc (vendor.fabb00d05b4c73bf.js:1:2752414)
    at Gp (vendor.fabb00d05b4c73bf.js:1:2752688)
    at zc (vendor.fabb00d05b4c73bf.js:1:2752713)
    at Gp (vendor.fabb00d05b4c73bf.js:1:2752688)
    at zc (vendor.fabb00d05b4c73bf.js:1:2752713)
    at Gp (vendor.fabb00d05b4c73bf.js:1:2752688)
    at zc (vendor.fabb00d05b4c73bf.js:1:2752713)
    at Gp (vendor.fabb00d05b4c73bf.js:1:2752688)

Vendor file : https://app.lottosocial.com/vendor.fabb00d05b4c73bf.js
```

### Your Environment

```text
Angular CLI: 13.3.10
Node: 16.17.0
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 13.3.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.10
@angular-devkit/build-angular   13.3.10
@angular-devkit/core            13.3.10
@angular-devkit/schematics      13.3.10
@angular/cdk                    13.3.9
@angular/cli                    13.3.10
@angular/fire                   7.5.0
@angular/flex-layout            11.0.0-beta.33
@angular/material               13.3.9
@angular/pwa                    0.803.29
@schematics/angular             13.3.10
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

This may be due to the usage of an unsupported browser.
