### ISSUE TITLE
`ng update @angular/cli` for custom builders

### ISSUE THREAD

**Issue by wszydlak** [angular/angular-cli#24741]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Currently if I use custom builders (such as `@angular-builders/custom-webpack`) doing `ng update @angular/cli` skips some updates (for version 15 it doesn't update main karma file). This is due to migration step which checks if builder target is `@angular-devkit/build-angular:karma`. There should be a way to do migrations also for custom builders (which are using `@angular-devkit/build-angular` with webpack and index.html customizations under the hood).

At least i expect Angular migrations to work with community well known custom builders (such as `@angular-builders/custom-webpack` or `ngx-build-plus`), ideally it should work for any custom builders. Maybe migrations should not be checking only `@angular-devkit/build-angular` builders?

### Minimal Reproduction

1. Set `"builder": "@angular-builders/custom-webpack:karma",` for "test" architect in `angular.json` file
2. Run `ng update @angular/cli`

### Exception or Error

Main karma file is not updated, but it should be updated.

### Your Environment

```text
Angular CLI: 14.2.10
Node: 16.19.0
Package Manager: npm 8.19.3 
OS: darwin arm64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.10
@angular-devkit/core         14.2.10
@angular-devkit/schematics   14.2.10
@angular/cli                 14.2.10
@schematics/angular          14.2.10
rxjs                         7.5.7
typescript                   4.7.4
```

**Comment by alan-agius4** [comment]
Hi, this is behaviour is intended by design.

These 3rd party builders are not supported by the Angular team. Therefore it is the responsibility of the custom builder author to provide a migration as the Angular CLI does not know which options these builders provide, how they are used internally and how they interact together. 

If needed the migrations can be extended by the 3rd party author, this is already being done by other 3rd parties like NX.

**Comment by wszydlak** [comment]
Hi @alan-agius4, thanks for clarification, i already reported this problem in https://github.com/just-jeb/angular-builders/issues/1342
