### ISSUE TITLE
Bloated webpack  cache in .angular folder

### ISSUE THREAD

**Issue by PostalMike** [angular/angular-cli#24743]
### Command

config

### Description

Please see your issue 22323 and the related prior issue.

Just wondering about more granular control of the cache.  All of a sudden the webpack files were default added into TFS and caused a simply resolved muck-up.  Being new to this, got with my higher ups to confirm we just exclude .angular from check in -- intuitively obvious but still -- they were default selected for check in.  So naturally, ask why :)

How can we more granularly control the size of this cache and know what to delete safely?  There is supposedly a tool for this but I can't find where to download it.  So this may be the answer we're looking for.  Issue 22323 mentions this, again, I'll be derned if I can find it.

Main point is -- just arbitrarily caching all these entries did have the above mentioned side effect.

### Describe the solution you'd like

More clearly publish the location of this maintenance tool mentioned in issue 22323.  That's the best start.  If it doesn't work or some ideas come up for improvement after this I'll mention them.

### Describe alternatives you've considered

None.

**Comment by alan-agius4** [comment]
Indeed the `.angular` directory should be excluded from checkin. This directory is added in gitignore by default for new projects starting in version 13. In case you upgrading from an older version, the ignore entry was added through a migration when updating using `ng update`.  So, I am not quite sure why it is not in your project. 

Regarding cleaning the cache, you can use [`ng cache clean`](https://angular.io/cli/cache) which will delete the cache entirely.  Additionally, the Angular CLI also automatically deletes old stale cache data that were generated using previous versions of the CLI and are therefore stale.

For the full list of commands that the Angular CLI offers please see: https://angular.io/cli
