### ISSUE TITLE
Tailwind support in esbuild builder

### ISSUE THREAD

**Issue by eneajaho** [angular/angular-cli#24752]
### Command

build

### Description

Add support for tailwind just like in `@angular-devkit/build-angular:browser` builder.

**Comment by alan-agius4** [comment]
Thanks for this request.

The esbuild based builder is still experimental and it's not yet feature complete. Support for tailwind will be added down the line.

**Comment by eneajaho** [comment]
Hi, yeah makes sense. 

I opened this issue because that's the only reason why we're not using it for production builds.
