### ISSUE TITLE
adding proxy config runs minified code on development server ng serve

### ISSUE THREAD

**Issue by Suraj-Gupta-ML** [angular/angular-cli#24758]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi, i am using proxy config setup in my angular 8 application.

i am running below command to start the server,
`ng serve --port 4300 --proxy-config src/proxy.conf.json`

After compiling successfully, i am getting below output,
 ｢wdm｣: Compiled successfully.
```
[HPM] GET /styles.619f497b81ac514604bd.css -> https://<my-server-url>
[HPM] GET /runtime-es2015.cdfb0ddb511f65fdc0a0.js -> https://<my-server-url>
[HPM] GET /polyfills-es2015.7214e7f8190e9d99c095.js -> https://<my-server-url>
[HPM] GET /main-es2015.b11344c952cc03ebbfe1.js -> https://<my-server-url>
[HPM] GET /scripts.21a05e48cc6dd13c3d67.js -> https://<my-server-url>
```

### Minimal Reproduction

`ng serve --port 4300 --proxy-config src/proxy.conf.json`

### Your Environment

```text
"@angular/cli": "~8.3.29"
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

In addition to this, Angular 8 is no longer supported. Please see: https://angular.io/guide/releases#actively-supported-versions
