### ISSUE TITLE
--exclude option for ng test not working

### ISSUE THREAD

**Issue by Majed93** [angular/angular-cli#24759]
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi,

I'm trying to have 2 separate test runs, so i'm trying to include and exclude spec files.

I have this command to **include**
`ng test --watch=false --source-map=true --include='**/regression/*.spec.ts'`

Reading the [docs](https://angular.io/cli/test), I see **exclude** option, so using the same pattern:

`ng test --watch=false --source-map=true --code-coverage --exclude='**/regression/*.spec.ts'`

But i get the following error

```
ng test --watch=false --source-map=true --code-coverage --exclude='**/regression/*.spec.ts'

Error: Unknown argument: exclude

Process finished with exit code 1
```

I'm not sure if the docs are incorrect or if i'm doing something wrong? 

Any help would be much appreciated

### Minimal Reproduction

1. Run ng test command with --exclude option like so:
2. `ng test --watch=false --source-map=true --code-coverage --excludes='**/regression/*.spec.ts'`

### Exception or Error

```text
ng test --watch=false --source-map=true --code-coverage --exclude='**/regression/*.spec.ts'

Error: Unknown argument: exclude

Process finished with exit code 1
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 15.1.6
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 15.1.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.6
@angular-devkit/build-angular   15.1.6
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
Hi @Majed93, can you please share the `test` section of your `angular.json`?

**Comment by Majed93** [comment]
Aha! ...do i need to add 'exclude' to the options?

**Comment by alan-agius4** [comment]
`@angular-builders/custom-webpack:karma` which is a 3rd party builder and not supported by the Angular team does not provide the `exclude` option.

The `exclude` option is available when using the official builder `@angular-devkit/build-angular:karma`.
