### ISSUE TITLE
ES Build Angular - Uncaught TypeError: Class extends value undefined is not a constructor or null 

### ISSUE THREAD

**Issue by thaoula** [angular/angular-cli#24763]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi Team,

I have just tried to build our large Angular using the new brower-esbuild and the Angular CLI 15.2.0.

The ng build command takes about 40 seconds and on the surface appears to finish outputing just some minor warnings.

However, when I attempt to run the app, I get the following error in the browser console and the app does not run -

```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at app.security.ts:19:7 
```

Which points to this line 

`export class AppSecurityModule extends BaseSecurityModule<AppSecurityRight> {`

Just some points about our code base.

1. We use typescript paths so we can reference our code using @jms/xxxx
2. We have a model folder that is symlinked to appear as @jms\model in both our Angular App and NodeJS app. The code above is inside the symlinked folder.

Kind Regards,
Tarek

### Minimal Reproduction

I am not doing anything special to be honest..

I am just running ng build on an Angular project which appears to successfully run.

### Exception or Error

```text
Uncaught TypeError: Class extends value undefined is not a constructor or null appears in the browser console
```

### Your Environment

```text
Angular CLI: 15.2.0
Node: 16.18.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.2.0
@angular/cdk                    15.1.4
@schematics/angular             15.2.0
rxjs                            7.8.0
typescript                      4.8.4
```

**Comment by JoostK** [comment]
This typically happens in the presence of import cycles, but we'd need a reproduction to investigate this particular case.

**Comment by thaoula** [comment]
@JoostK 

By import cycles you mean? circular dependencies?

**Comment by JoostK** [comment]
Indeed.

**Comment by thaoula** [comment]
Hi,

We tracked this down some incorrect references. Thanks for the tip.

Regards,
Tarek
