### ISSUE TITLE
"Sealing" phase is stuck on

### ISSUE THREAD

**Issue by alexandis** [angular/angular-cli#24771]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.2.0

### Description

Generating browser applicaiton bundles (phase: sealing) - never ends.

### Minimal Reproduction

I've upgraded my solution from **Angular** 13.2.0 to 15.0.1...
I've successfully build all the projects both in Production and Development configurations. But I cannot get through "sealing" phase. I don't understand whose exactly this problem is and how to debug what is it stuck on?

![image](https://user-images.githubusercontent.com/6149843/220988612-a336b843-a57c-43a5-aff8-b416a6c8d170.png)

### Your Environment

```text
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.0.5
@angular-devkit/schematics      15.0.5
@schematics/angular             15.2.0
ng-packagr                      15.2.2
rxjs                            7.8.0
typescript                      4.8.4
```

**Comment by alan-agius4** [comment]
You could generate a CPU profile. 

 See: https://github.com/angular/angular-cli/blob/main/docs/DEVELOPER.md#cpu-profiling

**Comment by alexandis** [comment]
@alan-agius4 I've tried step 1. I don't get this error:

![image](https://user-images.githubusercontent.com/6149843/220993786-72b2cc06-f2cf-4a78-9798-efb0332cb885.png)

**Comment by alexandis** [comment]
UPDATE: after about 1.5 hour (!) of just stucking, it finally gave me the error:

![image](https://user-images.githubusercontent.com/6149843/220995852-abb5fac6-f9bd-4309-a2da-1779beb5aada.png)

I was unable to see the beginning of it in the console...

Question 1) it's not normal that it takes SO long to give me the error; so we still need to investigate the stuck issue running it again, right?
Question 2) I had no problems with referencing the CSS like that. Strange, but now it complains about "~" references and I need to use a long reference like "../../.. ....."

**Comment by alexandis** [comment]
Moving on. It does not look like something is happening at all during "sealing":

![image](https://user-images.githubusercontent.com/6149843/220998626-bda49453-ae6b-46de-b7ec-9d5b45450e23.png)

**Comment by alexandis** [comment]
Small note: the library where this wrong css reference happened is a 3rd party lib based on Angular **13.2.**0. We cannot rebuild it. Probably the "stuck problem has something to do with this?

**Comment by alexandis** [comment]
I've tried to debug "ng serve" and here's what is happening while "stuck" on "sealing" phase. I pressed "Pause" in debugger and there are numerous parsing errors inside this method which seem to silently "swallowed":

![image](https://user-images.githubusercontent.com/6149843/221002556-29986a1b-c97e-407c-a650-f57291c1780a.png)

**Comment by alan-agius4** [comment]
@alexandis, would please provide one of these error message in a gist?

**Comment by alexandis** [comment]
> @alexandis, would please provide one of these error message in a gist?
Sure. [Gist](https://gist.github.com/alexandis/e66eb151b030b9d64862c54e78ef22a9). Here are also configurations which might come handy.

**Comment by alan-agius4** [comment]
Thanks @alexandis, I did manage to get to the bottom of why the build is getting stuck and I have a PR to fix it. For the time being as a workaround you can run build/serve with the `--verbose` command line argument. 

Now, to the error itself, I don't know what's the root problem as I don't have context of how this stylesheet is being used in the application. How is this CSS being used?

**Comment by alexandis** [comment]
Bot closed this bug very soon... :)
OK - I've updated the library and built was successful. However, the error is the same. The question is: what am I doing wrong? Almost everything is default settings.

> Now, to the error itself, I don't know what's the root problem as I don't have context of how this stylesheet is being used in the application. How is this CSS being used? Are you importing the CSS file in your JS? In that case, you are problem encountered one of the breaking changes in version 14.

I found out the initial reason of the error (there were css-importing scripts in "Dist" folder - next to CSS files, I removed them). But I still cannot figure out what is happenind next prevening the successful compilation. Could you please give me a hint? I emphasize, that everything worked properly in Angular 13...

![image](https://user-images.githubusercontent.com/6149843/221324297-fda58800-f707-47f8-9a04-e3fafa1fc3a1.png)

**Comment by alan-agius4** [comment]
That is expected and is due to MDC changes in material version 15. Angular material 13 mixins are not compatible with version 15.

See: https://material.angular.io/guide/mdc-migration

**Comment by alexandis** [comment]
Thank you very much for the assitance!
