### ISSUE TITLE
Angular build is breaking New Relic browser agent snippet

### ISSUE THREAD

**Issue by patrickhousley** [angular/angular-cli#24794]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Good morning Angular Team,

My team has received two reports of Angular projects that are cutting off part of the New Relic browser agent snippet in the `index.html` file. I am currently investigating the issue but any assistance would be greatly appreciated. Below is a link to the latest reported issue.

https://github.com/newrelic/newrelic-browser-agent/issues/425

### Minimal Reproduction

I am currently able to reproduce this issue using the Angular Heroes example application.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.2.10
Node: 18.13.0 (Unsupported)
Package Manager: npm 8.19.3 
OS: linux x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            7.8.0
typescript                      4.8.4
    
Warning: The current version of Node (18.13.0) is not supported by Angular
```

**Comment by alan-agius4** [comment]
@patrickhousley, unfortunately without a reproduction we cannot investigate this issue.

**Comment by patrickhousley** [comment]
Below is a reproduction using Angular v14.

[angular14-toh.zip](https://github.com/angular/angular-cli/files/10852638/angular14-toh.zip)

**Comment by patrickhousley** [comment]
It looks like this is fixed in version 15, presumably with the update of the parse5 dependency to version 7. If that is the case, is there any way that update could be back ported to previous versions?

**Comment by alan-agius4** [comment]
Indeed this was fixed with the parse5 update.

 Verision 14 is currently in LTS meaning that only security fixes are applied.

See: https://angular.io/guide/releases#lts-fixes
