### ISSUE TITLE
Alternate way to compile non-ivy libraries after removal of ngcc in v16

### ISSUE THREAD

**Issue by iKrishnaSahu** [angular/angular-cli#24797]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Is there any alternate way to compile non-ivy packages after removal of ngcc in v16?

There are lots of unmaintained libraries like [angular2-query-builder](https://github.com/zebzhao/Angular-QueryBuilder/issues/257) which devs are using. Till we migrated to some other library which is ivy compiled, is there any way to keep using non-ivy packages with angular v16?

### Minimal Reproduction

NA

### Your Environment

```text
C:\Projects\projects\npm>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 15.1.1
Node: 16.19.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1501.1 (cli-only)
@angular-devkit/core         15.1.1 (cli-only)
@angular-devkit/schematics   15.1.1 (cli-only)
@schematics/angular          15.1.1 (cli-only)


C:\Projects\projects\npm>
```

**Comment by alan-agius4** [comment]
Hi, using no-Ivy libraries with version 16 will no longer be possible. 

IMHO, we did give plenty of time for users to migrate to libraries using Ivy.

**Comment by JoostK** [comment]
@jpike88 Please see https://github.com/ui-router/core/issues/822#issuecomment-1464678027 for the reason, resolution, and workaround.
