### ISSUE TITLE
Getting Error: Module parse failed: Unexpected character '@' in Angular CLI 15

### ISSUE THREAD

**Issue by ashfaq-shamsudeen** [angular/angular-cli#24790]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14.2.1

### Description

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-cursor-placeholder.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("czi-vars.css");
|
| .molm-czi-cursor-placeholder {

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-form.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .molm-czi-form {

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-icon.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .molm-czi-icon {
|   direction: ltr;
|   display: inline-block;

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-image-resize-box.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .molm-czi-image-resize-box {

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-image-view.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .molm-czi-image-view {

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-inline-editor.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .molm-czi-inline-editor {

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-loading-indicator.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .molm-czi-loading-indicator {
|   display: inline-block;
|   height: 13px;

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-video-upload-editor.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .czi-editor-frameset .molm-czi-image-upload-editor {

./node_modules/@modusoperandi/licit-multimedia/dist/ui/czi-video-url-editor.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .czi-editor-frameset .molm-czi-image-url-editor {

./node_modules/@modusoperandi/licit-multimedia/dist/ui/icon-font.css?ngGlobalStyle:3:0 - Error: Module parse failed: Unexpected character '@' (3:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* [FS] IRAD-1061 2020-09-19
| Now loaded locally, so that it work in closed network as well. */
> @font-face {
|   font-family: "Material Icons";
|   font-style: normal;

./node_modules/@modusoperandi/licit-ui-commands/dist/ui/czi-animations.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .czi-animation-fade-in {
|   animation-duration: 250ms;
|   animation-fill-mode: both;

./node_modules/@modusoperandi/licit-ui-commands/dist/ui/czi-color-editor.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .czi-color-editor {

./node_modules/@modusoperandi/licit-ui-commands/dist/ui/czi-custom-button.css?ngGlobalStyle:2:0 - Error: Module parse failed: Unexpected character '@' (2:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| /* <CustomButton /> */
> @import url("./czi-vars.css");
|
| .czi-custom-buttons {

./node_modules/@modusoperandi/licit-ui-commands/dist/ui/czi-pop-up.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
|
| .czi-pop-up-modal-mask,

./node_modules/@modusoperandi/licit-ui-commands/dist/ui/czi-tooltip-surface.css?ngGlobalStyle:1:0 - Error: Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> @import url("./czi-vars.css");
| @import url("./czi-animations.css");
|

### Minimal Reproduction

ng build

"dependencies": {
    "@angular/animations": "^15.2.0",
    "@angular/common": "^15.2.0",
    "@angular/compiler": "^15.2.0",
    "@angular/core": "^15.2.0",
    "@angular/forms": "^15.2.0",
    "@angular/platform-browser": "^15.2.0",
    "@angular/platform-browser-dynamic": "^15.2.0",
    "@angular/router": "^15.2.0",
    "@modusoperandi/licit-multimedia": "0.0.5",
    "@popperjs/core": "^2.11.6",
    "bootstrap": "^5.2.3",
    "prop-types": "^15.8.1",
    "prosemirror-model": "^1.19.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.12.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.2.0",
    "@angular/cli": "~15.2.0",
    "@angular/compiler-cli": "^15.2.0",
    "@types/jasmine": "~4.3.0",
    "ajv": "^7.2.4",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~4.8.4"
  }

### Your Environment

```text
Angular CLI: 15.2.0
Node: 18.14.2
Package Manager: npm 7.20.5
OS: win32 x64

Angular: 15.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.2.0
@angular-devkit/schematics      15.2.0
@schematics/angular             15.2.0
rxjs                            7.8.0
typescript                      4.8.4
```

### Anything else relevant?

Windows 10 Pro

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by ashfaq-shamsudeen** [comment]
Hope this helps to reproduce. Thanks!

1. npm install
2. ng build

[SampleAngular15.zip](https://github.com/angular/angular-cli/files/10852090/SampleAngular15.zip)

**Comment by alan-agius4** [comment]
Hi, the problem appears to be that `@modusoperandi/licit-multimedia` is importing CSS as ES Modules. This is a webpack specific feature which is not supported.

See breaking changes section in https://github.com/angular/angular-cli/releases/tag/14.0.0
