### ISSUE TITLE
Segmentation fault on "ng add @angular/pwa"

### ISSUE THREAD

**Issue by m-r-g-t** [angular/angular-cli#24795]
### Command

add

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am trying to add a service worker to https://github.com/m-r-g-t/liquality-reversi

Upon running:

yarn
ng add @angular/pwa

The second command throws the following error:

Skipping installation: Package already installed
Segmentation fault

I am on a Debian WSL, using node 8.14.2. I have tried reinstalling, to no avail. Any ideas where I am going wrong?

### Minimal Reproduction

yarn
ng add @angular/pwa

### Exception or Error

```text
Segmentation fault
```

### Your Environment

```text
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.6
Node: 18.14.2
Package Manager: yarn 1.22.19
OS: linux x64

Angular: 15.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, pwa, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0
@angular-devkit/build-angular   15.2.0
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
Please update `@angular/cli` to the latest version.

**Comment by m-r-g-t** [comment]
Thank you, upgrading the angular CLI to the current latest version (15.2.0) in line with the Angular version has resolved the issue.
