### ISSUE TITLE
Call retries were exceeded exception while ng build

### ISSUE THREAD

**Issue by YSFKBDY** [angular/angular-cli#24806]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

My Angular 10 project is getting bigger, and at some point I've started to get an error while trying to build with `ng build --prod`. When I try to build, I am getting an error at the point of Generating ES5 bundles for differential loading... and it says:

```
An unhandled exception occurred: Call retries were exceeded
See "...\angular-errors.log" for further details.
```

**Error Log:**
```
[error] Error: Call retries were exceeded
    at ChildProcessWorker.initialize (...\node_modules\jest-worker\build\workers\ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (...\node_modules\jest-worker\build\workers\ChildProcessWorker.js:274:12)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
```

I've noticed that **if I comment out around 1k lines of my code at any of my components** and try to build, it works. But when I re-open it and build again, then it gives the same error. I need to use differential loading, so I can't close it.

Node.js version: `v14.21.2`
Angular version: `~10.2.0`

**tsconfig.json:**
```{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2019",
      "es2018",
      "dom"
    ]
  }
}
```

**What I've tried so far?**
- Increased the memory for the build process up to 12 GB - **failed**
- Added "sideEffects": false to my package.json - **failed**
- Deleted and reinstalled node_modules - **failed**
- Setting "target": "es5" in tsconfig.json - **success** (But this disables the differential loading)

### Minimal Reproduction

I don't know how to reproduce the issue. My Angular 10 project is getting bigger, and at some point I've started to get an error while trying to build with `ng build --prod`.

### Exception or Error

```text
[error] Error: Call retries were exceeded
    at ChildProcessWorker.initialize (...\node_modules\jest-worker\build\workers\ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (...\node_modules\jest-worker\build\workers\ChildProcessWorker.js:274:12)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
```

### Your Environment

```text
Angular CLI: 10.2.0
Node: 14.21.2
OS: win32 x64

Angular: 10.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.0
@angular-devkit/build-angular   0.1002.0
@angular-devkit/core            10.2.0
@angular-devkit/schematics      10.2.0
@angular/cdk                    11.0.2
@angular/cli                    10.2.0
@angular/localize               11.0.3
@angular/material               11.0.3
@schematics/angular             10.2.0
@schematics/update              0.1002.0
rxjs                            6.6.3
typescript                      4.0.2
```

**Comment by alan-agius4** [comment]
Angular 10 is no longer supported. 

See: https://angular.io/guide/releases#actively-supported-versions
