### ISSUE TITLE
Using environment.ts value in proxy.config.mjs file

### ISSUE THREAD

**Issue by codesuman** [angular/angular-cli#24805]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We are trying to use **proxy.config.mjs** (located in src folder) as per [Angular Docs](https://angular.io/guide/build#proxy-multiple-entries) to talk to back-end API in Dev mode but we want to set target value in this proxy conf using environment.ts file.

Have followed all default configurations to set-up proxy.config.mjs, environment files but getting an exception when trying to run `ng serve`

<ins> **Repo Link for the same :** </ins>

https://github.com/codesuman/ng-proxy-test

### Minimal Reproduction

<ins> **UI / Angular Code :** </ins>

git clone https://github.com/codesuman/ng-proxy-test

<ins> **API / Node Code :** </ins>

`index.js`

```
const express = require('express')
const app = express()
const port = 3000

app.get('/', (req, res) => {
  res.send('Hello World!')
})

app.get('/api/tasks', (req, res) => {
  res.send(Array.from(Array(10).keys()).map(n => 't'+n))
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

### Exception or Error

```text
An unhandled exception occurred: Cannot find module '/proxy-test/src/environments/environment' imported from proxy-test/src/proxy.config.mjs
```

### Your Environment

```text
Angular CLI: 15.1.3
Node: 16.17.0
Package Manager: npm 8.15.0
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1501.3 (cli-only)
@angular-devkit/core         15.1.3 (cli-only)
@angular-devkit/schematics   15.1.3 (cli-only)
@schematics/angular          15.1.3 (cli-only)
```

**Comment by alan-agius4** [comment]
This is working as intended. 

The proxy configuration is not part of the TypeScript compilation of the application and thus it cannot use TypeScript files.

**Comment by codesuman** [comment]
@alan-agius4 any workaround ?? As in the question we need to use environment.ts variable value in proxy conf. Thanks in advance.

**Comment by codesuman** [comment]
@alan-agius4 thanks for replying. Is there any workaround ?? As in the question we need to use `environment.ts` variable value in `proxy conf`. 

I have tried couple of options [paths](https://www.typescriptlang.org/tsconfig#paths) & [jsonModule](https://www.typescriptlang.org/tsconfig#resolveJsonModule) but no luck.

Thanks in advance.
