### ISSUE TITLE
ng build Performance Has Degraded Significantly In Upgrade from Angular v12 -> v15

### ISSUE THREAD

**Issue by fearghalom** [angular/angular-cli#24808]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

12.2.17

### Description

I recently tried to upgrade our large enterprise application (~1300 components) from Angular v12 to v15. After the upgrade, I noticed that 'ng build'  times had increased from around ~13 mins on Angular v12 to 21 mins on Angular v15. 

Here's my project configuration:
"build": {
      "builder": "@angular-devkit/build-angular:browser",
      "options": {
        "allowedCommonJsDependencies": [
          "lodash",
          "highcharts",
          "moment-timezone",
          "daterangepicker",
          "jquery",
          "wolfy87-eventemitter",
          "css-element-queries",
          "pdfmake/build/pdfmake",
          "pdfmake/build/vfs_fonts",
          "html2canvas",
          "ipaddr.js",
          "deepmerge",
          "moment/moment",
          "vis",
          "messageformat"
        ],
        "outputPath": "dist/my-app",
        "index": "src/index.html",
        "main": "src/main.ts",
        "polyfills": [
          "zone.js"
        ],
        "tsConfig": "tsconfig.app.json",
        "inlineStyleLanguage": "scss",
        "preserveSymlinks": true,
        "assets": [
          "src/assets"
        ],
        "styles": [
          "./node_modules/please-wait/build/please-wait.css",
          "./node_modules/bootstrap/dist/css/bootstrap.min.css",        
          "./node_modules/vis/dist/vis.css",
          "./node_modules/fullpage.js/dist/jquery.fullpage.min.css",
          "./node_modules/ag-grid-community/dist/styles/ag-grid.css",
          "./node_modules/ag-grid-community/dist/styles/ag-theme-balham.css",
          "./node_modules/@angular/material/_theming.scss",
          "./node_modules/angular-archwizard/archwizard.scss",
          "./node_modules/daterangepicker/daterangepicker.css",
          "style.scss"
        ],
        "stylePreprocessorOptions": {
          "includePaths": [
            "src/assets/sass"
          ]
        },
        "scripts": [
          "./node_modules/.../script1.js",
          "./node_modules/.../script2.js",
      "./node_modules/.../script2.js",
        ]
      },
      "configurations": {
        "production": {
          "outputHashing": "none",
          "buildOptimizer": true,
          "optimization": false,
          "sourceMap": false,
          "aot": true
        },
        "development": {
          "buildOptimizer": false,
          "optimization": false,
          "vendorChunk": true,
          "extractLicenses": false,
          "sourceMap": true,
          "namedChunks": true,
          "aot": false,
          "progress": true
        }
      }
    },
    "serve": {
      "builder": "@angular-devkit/build-angular:dev-server",
      "options": {
        "browserTarget": "my-app:build:development",
        "port": 3000
      },
      "configurations": {
        "production": {
          "browserTarget": "my-app:build:production"
        },
        "development": {
          "browserTarget": "my-app:build:development"
        },
        "defaultConfiguration": "development"
      }
    },

Command used: **_node --max-old-space-size=16384 ./node_modules/@angular/cli/bin/ng build_**

### Minimal Reproduction

I wasn't able to reproduce issue in a smaller application and am unable to share our code base.

### Your Environment

```text
Angular CLI: 15.0.4
Node: 16.19.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.0.3
@angular/flex-layout            15.0.0-beta.42
@angular/material               15.0.3
@schematics/angular             15.0.4
rxjs                            6.6.0
typescript                      4.8.4
```

**Comment by fearghalom** [comment]
Attaching cpu profile 
[cpuprofile.zip](https://github.com/angular/angular-cli/files/10884059/cpuprofile.zip)

**Comment by JoostK** [comment]
Some of these profiles appear to indicate that a lot of time spent in SCSS compilation, although there's also a lot of waiting for background worders to complete. It's impossible to judge where time is spent now compared to where time used to be spent in v12.

Please be aware that using a custom builder (`@angular-builders/custom-webpack:browser`) is not supported by the Angular team, although I gather from #24634 (also yours) that this does occur with the stock builder as well.

**Comment by alan-agius4** [comment]
Can you please update to the latest stable version of `@angular-devkit/build-angular` and check if the problem persists?

**Comment by fearghalom** [comment]
> Some of these profiles appear to indicate that a lot of time spent in SCSS compilation, although there's also a lot of waiting for background workers to complete. It's impossible to judge where time is spent now compared to where time used to be spent in v12.
> 
> Please be aware that using a custom builder (`@angular-builders/custom-webpack:browser`) is not supported by the Angular team, although I gather from #24634 (also yours) that this does occur with the stock builder as well.

I had actually removed the usage of the custom builder before I had performed the profiling. I've updated the angular.json config above to reflect what was used.

**Comment by fearghalom** [comment]
> Can you please update to the latest stable version of `@angular-devkit/build-angular` and check if the problem persists?

I upgraded to v15.2.1 and there was some improvement in the ng build times. It's now taking ~17 mins (down from 21 mins). It's still 4 minutes slower than Angular v12.

**Comment by fearghalom** [comment]
> > It's now taking ~17 mins (down from 21 mins)
> 
> Dear god, that's an insane length of time. Might I ask how it's so long?
> 
> I thought 25 seconds is way too long already.

It's a large application with about ~1300 components

**Comment by jpike88** [comment]
@clydin I saw some efforts towards integrating esbuild into the toolchain, but seems to have been pretty quiet for a couple of weeks. Is this something that's planed? The pain of slow builds I would like to see go away one day

**Comment by fearghalom** [comment]
I did some investigation and noticed that the NgccProcessor.process() method takes a lot longer for Angular v15 over v12. It's about 9 mins on v15 and 2.5 mins on v12. This is just run once on a clean node_modules directory. 
Subsequent build times are comparable on v15 and v12.

**Comment by alan-agius4** [comment]
Hi @fearghalom, indeed NGCC is taking a considerable amount of time. Are there a lot of libraries that require NGCC?

**Comment by fearghalom** [comment]
Hi Alan, maybe 5 libraries. What I noticed is that the bulk of the time is spent determining the dependencies ( specifically host.collectDependenciesInFiles(rootFiles, dependencies); in ProgramBasedEntryPointFinder.getInitialEntryPointPaths() ). The processing of the legacy view engine libraries seems to take just about 10 seconds.

![image](https://user-images.githubusercontent.com/5666132/223789209-afa0c681-3284-4328-a099-3e48a38edaa8.png)

**Comment by alan-agius4** [comment]
That is interesting as there hasn’t been amy changes in NGCC.

**Comment by fearghalom** [comment]
Hi @alan-agius4, I profiled the _main-ngcc.js_ with the following command arguments:

node --cpu-prof .\node_modules\@angular\compiler-cli\bundles\ngcc\main-ngcc.js --source .\node_modules --properties es2020 es2015 browser module main --first-only --create-ivy-entry-points --async --tsconfig .\tsconfig.app.json --use-program-dependencies

[CPU.20230313.105243.34684.0.001.cpuprofile.zip](https://github.com/angular/angular-cli/files/10956663/CPU.20230313.105243.34684.0.001.cpuprofile.zip)

**Comment by fearghalom** [comment]
Our Angular project package.json file is read 637,823 times while ngcc is run (specifically in ModuleResolver.isEntryPoint()).

**Comment by alan-agius4** [comment]
Can you please share your tsconfig file?

**Comment by fearghalom** [comment]
[tsconfig.app.txt](https://github.com/angular/angular-cli/files/10966564/tsconfig.app.txt)
[tsconfig.txt](https://github.com/angular/angular-cli/files/10966567/tsconfig.txt)

**Comment by fearghalom** [comment]
[tsconfig.app.txt](https://github.com/angular/angular-cli/files/10966590/tsconfig.app.txt)
[tsconfig.txt](https://github.com/angular/angular-cli/files/10966591/tsconfig.txt)

**Comment by alan-agius4** [comment]
I suspect the performance issue is due to the `paths` settings. I am not too sure what you are trying to achieve, but that is an awful loot of lookup for every module.


```json
{...
  "paths": {
    "*": [
      "node_modules/*",
      "src/ng_app/src/main/ts/*",
      "src/meta/src/main/ts/*",
      "src/*",
      "src/infra/src/main/ts/*",
      "src/common/dist/src/main/ts/*",
      "src/common_generated/dist/src/main/ts/*",
      "src/comm/dist/src/main/ts/*",
      "src/comm_generated/dist/src/main/ts/*",
      "src/query/dist/src/main/ts/*",
      "src/domain_model/dist/src/main/ts/*",
      "src/domain_model_generated/dist/src/main/ts/*",
      "src/requests_generated/dist/src/main/ts/*"
    ]
  }
```

**Comment by fearghalom** [comment]
> I suspect the performance issue is due to the `paths` settings. I am not too sure what you are trying to achieve, but that is an awful loot of lookup for every module.
> 
> ```json
> {...
>   "paths": {
>     "*": [
>       "node_modules/*",
>       "src/ng_app/src/main/ts/*",
>       "src/meta/src/main/ts/*",
>       "src/*",
>       "src/infra/src/main/ts/*",
>       "src/common/dist/src/main/ts/*",
>       "src/common_generated/dist/src/main/ts/*",
>       "src/comm/dist/src/main/ts/*",
>       "src/comm_generated/dist/src/main/ts/*",
>       "src/query/dist/src/main/ts/*",
>       "src/domain_model/dist/src/main/ts/*",
>       "src/domain_model_generated/dist/src/main/ts/*",
>       "src/requests_generated/dist/src/main/ts/*"
>     ]
>   }
> ```
> 
> You can disable NGCC from processing all the files by setting the environment variable `BAZEL_TARGET=1`.

We don't use relative imports in our TS code but use Java like package imports instead. The path mapping allows us to do this. Some of the TS code directories can be 6 to 7 levels deep. 

I can see from profiling, that the path mapping does indeed result in a large performance overhead in Angular v15. Angular v12 seemed to handle our project structure a lot better. I've patched @angular/compiler-cli locally and brought the ngcc time down to about 35 seconds from around 10 minutes.
