### ISSUE TITLE
ng new generates a different route file from latest docs

### ISSUE THREAD

**Issue by osazemeu** [angular/angular-cli#2481]
## OS?
> Windows 8.1

### Versions.
> angular-cli: 1.0.0-beta.16
> node: 4.5.0
> os: win32 x64

### Repro steps.
It was created with angular-cli
> `ng new test_app`

There were no failures

I noticed that in the [latest docs](https://angular.io/docs/ts/latest/guide/router.html), the routing file is `app.routing.ts` but angular-cli generates `app-routing.module.ts`. 

Is this a bug or the docs are not upto date?

**Comment by Brocco** [comment]
The docs are behind on this one... updating our documentation is becoming a larger priority, sorry for the confusion.
