### ISSUE TITLE
browserslist discrepancy

### ISSUE THREAD

**Issue by johnnygerard** [angular/angular-cli#24826]
### Describe the problem that you experienced

On previous Angular projects, there was a .browserslistrc file at the root automatically generated by the CLI.

New projects don't have this file anymore.
We can still generate it by using `ng generate config browserslist`.

Without that file, `npx browserslist` outputs the default browser targets (which is a different configuration).

The official documentation does not mention anything about this change.

Can you clarify what browserslist configuration new Angular projects use?

### Enter the URL of the topic with the problem

https://angular.io/guide/build#configuring-browser-compatibility

**Comment by alan-agius4** [comment]
Hi @johnnygerard, the internal browserslist config is listed in the link you supplied

> Internally, the Angular CLI uses the below browserslist configuration which matches the [browsers that are supported](https://angular.io/guide/browser-support) by Angular.

> ```
> last 2 Chrome versions
> last 1 Firefox version
> last 2 Edge major versions
> last 2 Safari major versions
> last 2 iOS major versions
> Firefox ESR
> ```
