### ISSUE TITLE
Using 3rd party builders causes IDEs to show warnings when viewing angular.json

### ISSUE THREAD

**Issue by erictor** [angular/angular-cli#24821]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi, the below is the content of a bug I filed at https://developercommunity.visualstudio.com/t/Please-dont-put-warning-green-squiggle-/10294859
==================================================================
Please don't put warning green squiggle line under "builder" in angular.json when using ngx-build-plus
-
Reported Feb 28, 2023 8:56 PM
When using ngx-build-plus to bundle in Angular, one needs to set the “builder” line in angular.json to "builder": "ngx-build-plus:browser" but the key “builder” gets a warning green squiggle line underneath it when this is done.   Further info on the need to place this value in angular.json is at:  [https://github.com/manfredsteyer/ngx-build-plus/issues/157](github.com review baschtii 's 5-upvote answer)

Visual Studio
Windows 10.0
Visual Studio 2022 version 17.5

Microsoft Resolution - 
Maria Solano [MSFT]  
Closed - Other Product
This issue seems to be caused by Angular and not Visual Studio. Please file a ticket with that product at https://github.com/angular/angular/issues.

### Please provide the exception or error you saw

```true
[I'm not sure why the below stuff on ng version was auto-filled-in.  I'm not running linux.  Here are the actual results when I run ng version:]

Angular CLI: 15.1.6
Node: 18.14.0
Package Manager: npm 9.3.1
OS: win32 x64

Angular: 15.2.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.6
@angular-devkit/build-angular   15.1.6
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cdk                    15.2.1
@angular/cli                    15.1.6
@angular/flex-layout            15.0.0-beta.42
@angular/material               15.2.1
@angular/youtube-player         15.2.1
@schematics/angular             15.1.6
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by JoostK** [comment]
Do you have a $schema reference in your angular.json file?

**Comment by erictor** [comment]
Hi Joost!  Yes, the first line is `"$schema": "./node_modules/@angular/cli/lib/config/schema.json",`

**Comment by alan-agius4** [comment]
Hi @erictor,

I did try to replicate this issue using vscode and was not able. In addition to that I used an online tool to validate the `angular.json` with the schema does not shown any errors See: https://www.jsonschemavalidator.net/s/CQNd7pdM

This does seem to be an issue with Visual Studio that is not validating the schema correctly as the schema does not force usage of `@angular-devkit/build-angular:browser-esbuild`.

See related part of the schema https://github.com/angular/angular-cli/blob/f2cba37327ee0dcb361d89db184d49a548696eb8/packages/angular/cli/lib/config/workspace-schema.json#L346-L586

**Comment by erictor** [comment]
Hi Alan!  Thank you so much for taking the time to look at this.  -- Eric

**Comment by alan-agius4** [comment]
Closing as there isn't anything actionable from our end here.
