### ISSUE TITLE
Batch job is terminating even by typing letter N

### ISSUE THREAD

**Issue by akshaymagapu** [angular/angular-cli#2482]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here: angular-cli: 1.0.0-beta.15                                                                                                        

### Repro steps.

1. Start app through ng-serve
2. hold keys ctrl+c
3. Type N 

### Mention any other details that might be useful.
1. N should not terminate batch job.

**Comment by gelliott181** [comment]
This isn't a CLI issue, this is how Node works. Take any project (I used a HapiJS server), start it, and use Ctrl+C then enter N. No matter what, unless you specifically catch the Ctrl+C SIGINT in your code, Node will terminate. This is consistent with Unix operation, where a Ctrl+C SIGINT combo causes Node to immediately terminate unless your application specifically handles SIGINT differently.
