### ISSUE TITLE
"Port 4200 is already in use" when running the ng serve command

### ISSUE THREAD

**Issue by danielehrhardt** [angular/angular-cli#24881]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

- run ng serve
- kill ng serve with cmd + c 
- run ng serve again
- ➤ Port 4200 is already in use
- tmp fix: sudo kill $(sudo lsof -t -i:4200)

i had this already some years ago and now again
node -v
v18.12.1
npm -v
8.19.2

MacOS 13.2.1 (22D68)

### Minimal Reproduction

-

### Exception or Error

```text
-
```

### Your Environment

```text
Angular CLI: 15.2.4
Node: 18.12.1
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 15.2.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      14.0.6
@angular/cli                    15.2.4
@schematics/angular             15.2.4
rxjs                            7.8.0
typescript                      5.0.2
```

**Comment by MickL** [comment]
I am on macOS 13.2.1 as well, with also the latest Angular versions and dont have the same issue

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
