### ISSUE TITLE
ng build freeze on finish (tried on Windows / Linux / Local / Github actions)

### ISSUE THREAD

**Issue by DutchKevv** [angular/angular-cli#24914]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

So...

Short story: running ```ng-build``` makes the CLI freeze for a minute of 2-3

Long story:

So I create a new project, after updating @angular/cli@latest.... 

With this 100% fresh project (no file changes), I run ```ng build```

The compiler runs fine, but hangs for 2-3-4- minutes after finish...

Its on Windows, Linux, Github actions etc...

No body else got this problem?

### Minimal Reproduction

```ng new````

Create a project with routing, analytics etc

Run ```ng build````

The compiler hangs for 2-3 minutes

### Exception or Error

```text
No errors
```

### Your Environment

```text
WSL Windows

But also in Linux, Github actions etc
```

### Anything else relevant?

I tried to debug it, but every environment I run it on, has the same problem.

But, I can't find many reports about it on the big fat www....

My personal project got this problem about 4-5 weeks ago

So I made a 'fresh' new Angular project.. But still the same problem?

Nobody else?

**Comment by DutchKevv** [comment]
P.S.

I did fresh builds on many platforms, with a naked @angular/cli and with a naked project.. Still the same problem.. Also tried on VPS machines etc..

Is it possible, that my WSL windows machine, inject some kind of ***** that makes ALL builds go corrupt on all OS's?

**Comment by DutchKevv** [comment]
P.S. 2

It seems to be a problem with NODE > v19 

Nobody else?

**Comment by alan-agius4** [comment]
Node.js 19 is not supported. Please see: https://angular.io/guide/setup-local#prerequisites
