### ISSUE TITLE
Not able to debug with VSCode (I think is something related with how angular-cli uses webpack)

### ISSUE THREAD

**Issue by jorgeas80** [angular/angular-cli#2491]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Ubuntu 16.04

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.7.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

* ng new myapp
* open the project in vscode
* generate a new launch.json file to enable debug. Like [this one](https://github.com/roblourens/angular2-tour-of-heroes/blob/master/.vscode/launch.json). Just use port 4200 instead of 3000
* ng serve
* Put breakpoints in the code. They don't work. The chrome instance launchs properly but it doesn't stop in breakpoints.

Tried changing webRoot propery to "${workspaceRoot}/src". and "${workspaceRoot}/src/app". Didn't work either.

### The log given by the failure.
> Normally this include a stack trace and some more information.

No log, it just breakpoints don't work.

### Mention any other details that might be useful.
The same configuration for vscode launch for [this repo](https://github.com/roblourens/angular2-tour-of-heroes). You put breakpoints and they work. 

If I put "debugger;" at some point of my ts file, VSCode stops at the generated js file, not at the original ts one. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yuri1969** [comment]
@jorgeas80  Try the `package.json` examples proposed here #2453.

**Comment by jorgeas80** [comment]
Thanks! Finally worked. In a weird way (debugger opens to tabs, and I need to close one of them and then reload the other to make it work). But it works :-). Thanks!
