### ISSUE TITLE
Angular app that has jQuery and built via ESBuild crashes in runtime

### ISSUE THREAD

**Issue by pavankjadda** [angular/angular-cli#24934]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a project that uses jQuery data tables. When I import jQuery `import * as $ from 'jquery';` and build the I see below warning and this page fails at run time. 

```
▲ [WARNING] Calling "$" will crash at run-time because it's an import namespace object, not a function [call-import-namespace]

    src/app/app.component.ts:12:6:
      12 │       $('#title').text('jQuery Title');
         ╵       ^

  Consider changing "$" to a default import instead:

    src/app/app.component.ts:4:7:
      4 │ import * as $ from 'jquery';
        │        ~~~~~~
        ╵        $


▲ [WARNING] Module 'jquery' used by 'src/app/app.component.ts' is not ESM

```

I do know it's warning and esbuild is experimental, but the question is, 

1. Will it be fixed I v16 or later?
2. If not what are the alternatives?

### Minimal Reproduction

https://github.com/pavankjadda/angular-esbuild-bug

### Exception or Error

```text
▲ [WARNING] Calling "$" will crash at run-time because it's an import namespace object, not a function [call-import-namespace]

    src/app/app.component.ts:12:6:
      12 │       $('#title').text('jQuery Title');
         ╵       ^

  Consider changing "$" to a default import instead:

    src/app/app.component.ts:4:7:
      4 │ import * as $ from 'jquery';
        │        ~~~~~~
        ╵        $


▲ [WARNING] Module 'jquery' used by 'src/app/app.component.ts' is not ESM
```

### Your Environment

```text
Angular CLI: 15.2.4
Node: 18.15.0
Package Manager: npm 9.5.0
OS: darwin arm64

Angular: 15.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.2.4
@angular/cli                    15.2.4
@schematics/angular             15.2.4
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by clydin** [comment]
The warning is indicating a correctness issue within the application code. With `import * as $ from 'jquery';`, `$` is not callable based on the ECMAScript specification but is being used as if it were callable.  TypeScript itself has an option to adjust its behavior to be spec compliant as the assumptions it makes for CommonJS code are otherwise incorrect. The option is `esModuleInterop` and more information regarding the option can be found at https://www.typescriptlang.org/tsconfig#esModuleInterop.  This option is particularly useful when interacting with CommonJS code.  However, as the second warning mentions, CommonJS code is not recommended where possible as it cannot be efficiently bundled nor optimized.

**Comment by pavankjadda** [comment]
> The warning is indicating a correctness issue within the application code. With `import * as $ from 'jquery';`, `$` is not callable based on the ECMAScript specification but is being used as if it were callable. TypeScript itself has an option to adjust its behavior to be spec compliant as the assumptions it makes for CommonJS code are otherwise incorrect. The option is `esModuleInterop` and more information regarding the option can be found at https://www.typescriptlang.org/tsconfig#esModuleInterop. This option is particularly useful when interacting with CommonJS code. However, as the second warning mentions, CommonJS code is not recommended where possible as it cannot be efficiently bundled nor optimized.

Thanks. Adding "esModuleInterop":"true" in **tsconfig.json** and updating jQuery import fixed the issue for me.

**tsconfig.json**
```
"esModuleInterop":"true"
```
and updating
 ```
import * as $ from 'jquery';
``` 
to 
```
import $ from 'jquery';
``` 
fixed the issue for me
