### ISSUE TITLE
Protractor's browser.pause does not work via ng e2e

### ISSUE THREAD

**Issue by Blasz** [angular/angular-cli#2494]
### Versions.

```
$ ng --version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.2.1
os: linux x64
```
### Repro steps.

Add `browser.pause()` to an e2e test spec
### The log given by the failure.

No output is shown after running `ng e2e` and it hangs.
### Mention any other details that might be useful.

Running `npm run e2e -- protractor.conf.js` (the command that `ng e2e` wraps) shows the correct debugging output.

**Comment by maxbellec** [comment]
still doesn't work with `angular-cli: 1.0.0-beta.25.5`

**Comment by josersleal** [comment]
with ng2 v4 and ng-cli v1 this hapens, except the tests run to the end. 
The call to pause() is simply ignored.
But it seems to be a protractor issue not cli related according to https://github.com/angular/protractor/issues/1744

**Comment by filipesilva** [comment]
I tested this in a new project and it seems to be fine now.

**Comment by JWesorick** [comment]
this is not working for me.

```
/client (jw/angular-cli) $ng --version
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.2.6
node: 6.10.0
os: darwin x64
@angular/animations: 4.3.2
@angular/common: 4.3.2
@angular/compiler: 4.3.2
@angular/core: 4.3.2
@angular/forms: 4.3.2
@angular/http: 4.3.2
@angular/platform-browser: 4.3.2
@angular/platform-browser-dynamic: 4.3.2
@angular/router: 4.3.2
@angular/cli: 1.2.6
@angular/compiler-cli: 4.3.2
@angular/language-service: 4.3.2
```

**Comment by JWesorick** [comment]
` I/protractor - Encountered browser.pause(), but debugger already attached.`

**Comment by JWesorick** [comment]
It works for me if I call it multiple times:

```
[14:38:36] I/protractor - Encountered browser.pause(), but debugger already attached.
[14:38:37] I/protractor -
[14:38:37] I/protractor - Encountered browser.pause(). Attaching debugger...
```
