### ISSUE TITLE
Update from 11 to 12

### ISSUE THREAD

**Issue by Techman47** [angular/angular-cli#24947]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

11

### Description

I have an app which run through docker Image. It was running fine in angular 11 using command npm run watch. I update the app to v12 using `ng update @angular/core@12 @angular/cli@12` Now when I run build and run using npm run watch its showing blank app. I changed nothing just update. everything run fine in terminal and no issue is shown while updating. But issues in console
Error in console:
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### Minimal Reproduction

script in package.json
"watch": "npx ng build --watch",

### Exception or Error

```text
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

### Your Environment

```text
/ \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.18
Node: 16.17.0 (Unsupported)
Package Manager: npm 6.14.18
OS: linux x64

Angular: 12.2.17
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cli                    12.2.18
@angular/fire                   6.1.5
@schematics/angular             12.2.18
rxjs                            6.6.7
typescript                      4.3.5
webpack                         4.46.0
```

### Anything else relevant?

I am using docker so maybe It is related to docker or something

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
