### ISSUE TITLE
esbuild serve not using configured outputPath, all assets missing

### ISSUE THREAD

**Issue by jpike88** [angular/angular-cli#24967]
### Command

serve

### The previous version in which this bug was not present was

16.0.0-next-4 (this is a new feature)

### Description

Esbuild using `ng build` seems to work perfectly, assets, script, css etc all end up in the configured outputPath in my angular.json, ready to go.

However using `ng serve`, I notice some strange behaviour:

- it seems to build fine (see screenshot below)
![Screenshot 2023-04-06 at 2 24 12 pm](https://user-images.githubusercontent.com/9585787/230304564-d43fecc7-0f61-44f8-8656-a0c6938cc5a4.png). though the `Sourcemap for "/styles.css" points to missing source files` line I have no idea how to resolve.
- however, when I go to `http://127.0.0.1:4200/`, I see a blank page. It seems that generated files have been created and being served successfully, but any assets are not being served breaking the whole initialization phase of my application.
![Screenshot 2023-04-06 at 2 13 50 pm](https://user-images.githubusercontent.com/9585787/230302204-55ff9db9-7b39-4591-8c02-6d1232a94bc7.png)
- When I look in my outputPath folder (which for me is `cordova/www`, so a non-standard value), it's just empty. I can't find anywhere that the files are being hosted (e.g. searching for `chunk-Z53IBAJG.js` on my filesystem gives me nothing). I don't see a dist folder or something

### Minimal Reproduction

ng serve with `"@angular/cli": "^16.0.0-next.6"`

### Your Environment

```text
Angular CLI: 16.0.0-next.7
Node: 16.14.2
Package Manager: npm 9.6.3
OS: darwin arm64

Angular: 16.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1600.0-next.7
@angular-devkit/build-angular      16.0.0-next.7
@angular-devkit/core               16.0.0-next.7
@angular-devkit/schematics         16.0.0-next.7
@angular/cdk                       16.0.0-next.4
@angular/flex-layout               15.0.0-beta.42
@angular/material                  16.0.0-next.4
@angular/material-moment-adapter   16.0.0-next.4
@schematics/angular                16.0.0-next.7
rxjs                               7.8.0
    
```
```


### Anything else relevant?

_No response_

**Comment by gmfun** [comment]
I tried to to dug it

https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/builders/dev-server/vite-server.ts#L232

here `req.url` is set to `/@fs//Users/g.mukherjee/code/ng16/stellar/src/assets/images/quick-start/deploy-site-and-discover-services.jpg` where as it should be `/@fs/src/assets/images/quick-start/deploy-site-and-discover-services.jpg`

**Comment by gmfun** [comment]
I also notices
 changing

```json
{
						"glob": "**/*",
						"input": "projects/config/util/src/lib/swaggerK8s",
						"output": "/swaggerK8s"
					},
					{
						"glob": "**/*",
						"input": "node_modules/@volterra/ui-components/assets",
						"output": "/assets"
					},
                    {
                        "glob": "**/*",
                        "input": "node_modules/@volterra/bootstrap/assets/fonts/Inter",
                        "output": "/"
                    },
```

to 

```json
{
						"glob": "**/*",
						"input": "projects/config/util/src/lib/swaggerK8s",
						"output": "swaggerK8s" //removed / it the begining
					},
					{
						"glob": "**/*",
						"input": "node_modules/@volterra/ui-components/assets",
						"output": "assets"
					},
                    {
                        "glob": "**/*",
                        "input": "node_modules/@volterra/bootstrap/assets/fonts/Inter",
                        "output": ""
                    },
```

Another observation. Some of our assets have a query params to bust browser cache. example `/voltuiicons.woff?bkszux` these do not work now

**Comment by gmfun** [comment]
Looks like this is fixed for me in rc0
