### ISSUE TITLE
Bundle is now valid / invalid infinite loop

### ISSUE THREAD

**Issue by yusijs** [angular/angular-cli#2497]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 7

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.15                                                                                                                                    
node: 6.7.0                                                                                                                                                   
os: win32 x64              

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
I really didn't do anything special. Issue started in beta.15, and is prelevant af. 

### The log given by the failure.
> Normally this include a stack trace and some more information.
No error, just constantly gives 

> Bundle is now valid 

then instantly 

> Bundle is now invalid

Restarting the ng serve works fine, but once I do a change, it starts the loop again. 

### Mention any other details that might be useful.
Seems to be primarily in IE11, but also happens in chrome. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment]
Does this occur on a freshly installed CLI project?

**Comment by yusijs** [comment]
It's in an existing project, but happened ever since it was new (geberated with cli beta.15)

**Comment by JtheB** [comment]
I have the same loop with a new project. After _ng serve_ it stops at _webpack: bundle is now VALID_.
_ng --version:_
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: linux x64
I bascially followed this tutorial: http://stackoverflow.com/documentation/angular2/789/install-angular2/2814/install-angular2-with-angular-cli#t=201608072028333699125
to get to this point.

**Comment by filipesilva** [comment]
What editor are you using? I'm wondering if there's something touching the files on disk, triggering the watchers.

**Comment by yusijs** [comment]
Using the latest version of VS Code. It often follows up with "wait for *.js" (inline, main etc). 
I'm questioning if it's some scanner we run at work that messes with it, but it's hard to say. Can probably close this off, as I dont think this is a cli issue anymore.

**Comment by filipesilva** [comment]
Well, there's an undocumented option you can use that might help: https://github.com/angular/angular-cli/pull/1814. It was put in for a different scenario but maybe helps in yours.

**Comment by yusijs** [comment]
Will def give it a look, thanks!

Den man. 10. okt. 2016, 16:50 skrev Filipe Silva <notifications@github.com>:

**Comment by duyhoang** [comment]
I have the same problem while having VS Code opened. I close the VS Code and the loop stops.

**Comment by Krisa** [comment]
Same like @duyhoang. I checked that "auto save file" is off, I've deactivated all possible extensions, and yet it continues to happen

**Comment by Krisa** [comment]
I've put a watcher on the project to check which files are modified. Every 2 minutes, .git/FETCH_HEAD and .git/index.lock are modified. That's probably due to the built-in functionality of VS Code regularly pulling for changes on the Git remote repository. Now the question is why does the angular-cli watches for changes there?

**Comment by Krisa** [comment]
OK think I nailed down the issue with VS Code... Looks like the path where tsconfig.json itself is placed is actually watched. In my case, it was put at the root of my project, where .git/ is also located. When I moved tsconfig.json one level down where my Angular2 source code is located, the infinite rebuild loop was solved.
