### ISSUE TITLE
Static analysis to detect dead code, unused properties

### ISSUE THREAD

**Issue by jpike88** [angular/angular-cli#24979]
### Command

build, lint

### Description

I'm trying to figure out a way to perform some analysis on my codebase to detect dead code.

I already use this library which helps a little bit but is far more effective on my backend code, not so useful in my Angular project, as the issue I'm describing goes a little deeper: https://www.npmjs.com/package/ts-unused-exports

I've also read issues like this on the main TypeScript repo, but doubt they would cover references logic needed to understand the Angular AST: https://github.com/microsoft/TypeScript/issues/29293

The dead code I'm concerned about isolating falls mainly into two categories:

- I have various 'utility' classes with lots of `public static` methods on them, and have no way of knowing which are being used across my codebase or not
- I have various components with `public` methods/variables in them which are probably not used internally (including not used in the component's template) or referenced otherwise

I assume this kind of issue is not limited to just our project, but other Angular devs can benefit from it.

I'm looking for guidance or even a simple implementation as a starting point that I can leverage, does the Angular team know of anything here?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jpike88** [comment]
Instead of a useless canned response, I would have appreciated a little bit of input. I’ve been doing this for over a decade, I am not in need of a “support request”.

Based on the way this was closed, I will assume that no such tooling exists, and I need to roll my own?
