### ISSUE TITLE
When me upgrade angular to V.15,  npm survey-analytics don`t load some file css 

### ISSUE THREAD

**Issue by duckhiem2507** [angular/angular-cli#24985]
### Command

run, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

In version 14 my survey-analytics works fine when I upgrade to version 15 my survey-analytics doesn't work, when I delete that file data and I ctrl+z again my project runs normally usually, the error only occurs when i intentionally upgrade to version 15, i'm using webpack

### Minimal Reproduction

In version 14 my survey-analytics works fine when I upgrade to version 15 my survey-analytics doesn't work, when I delete that file data and I ctrl+z again my project runs normally usually, the error only occurs when i intentionally upgrade to version 15, i'm using webpack

### Your Environment

```text
Angular 15
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
