### ISSUE TITLE
Unexpected token . using --aot

### ISSUE THREAD

**Issue by elvirdolic** [angular/angular-cli#2499]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> Windows 8
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here: 
> angular-cli: 1.0.0-beta.16
> node: 5.11.0
> os: win32 x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> ng build --prod --aot
### The log given by the failure.

> Normally this include a stack trace and some more information.
>  10% building modules 3/6 modules 3 active ...ode_modules\style-loader\addStyles
> .jsSyntaxError: Unexpected token .
>     at WebpackResourceLoader._evaluate (C:\development\git**\node_modules\@ngtools\webpack\src\resource_loader.js:75
### Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

It doesnt occur if using wihtout --aot

**Comment by tdesmet** [comment]
I'm having the same issue, it crashes on the icon.css file of the @angular/material package (2.0.0-alpha.9-3)

In icon.css you have the following line: `/*# sourceMappingURL=icon.css.map */`
If I remove this line it continues and crashes on the next css file of @angular/material. (list.css)


> $ ng build --prod --aot
 10% building modules 3/6 modules 3 active ...ode_modules\style-loader\addStyles.jsC:/Workspace/diapers.tenant/node_modules/@angular/material/list/list.css:214
.ad8b839fa5fd1378d82f.bundle.map*/
^
SyntaxError: Unexpected token .
    at WebpackResourceLoader._evaluate (C:\Workspace\diapers.tenant\node_modules\@ngtools\webpack\src\resource_loader.js:75:24)
    at C:\Workspace\diapers.tenant\node_modules\@ngtools\webpack\src\resource_loader.js:95:52

**Comment by elvirdolic** [comment]
I think that the webpack resource loader should support this

**Comment by choeller** [comment]
Same here. Seems to crash in some CSS file...

**Comment by onedotover** [comment]
I was running into this as well. I just tried on the latest commit on master and it looks like it's been fixed.

**Comment by gitawego** [comment]
I have exactly the same problem.

**Comment by thibaultsavary** [comment]
Same issue here

**Comment by filipesilva** [comment]
Does this still happen in `beta.17`?

**Comment by elvirdolic** [comment]
with beta.17 im receiving

ENOENT: no such file or directory, stat '..src\app\index'
Error: ENOENT: no such file or directory, stat '..\src\app\index'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)    at _symbolImportLookup (C:\development\git\..\node_modules\@ngtools\webpack\src\entry_resolver.js:103:28)
    at Object.resolveEntryModuleFromMain (C:\development\git\\..\node_modules\@ngtools\webpack\src\entry_resolver.js:1
48:18)
    at AotPlugin._setupOptions (C:\development\git\..

**Comment by gitawego** [comment]
I got error with v1.1.0
```
module.path.startsWith is not a function                                                                       
```

**Comment by Piusha** [comment]
I also having wired issue 
`ERROR in Invalid or unexpected token`

when build angular6 application with --aot option cant even find where the error coming from 

any one having any clue
