### ISSUE TITLE
esbuild-builder: missing files when building basic Ionic app

### ISSUE THREAD

**Issue by hakimio** [angular/angular-cli#24990]
### Command

build

### Description

Ionic starter application (template "side-menu") built with `esbuild` builder seems to be missing files.

The demo app attached to this post.

[ionic-test.zip](https://github.com/angular/angular-cli/files/11200851/ionic-test.zip)

![image](https://user-images.githubusercontent.com/768105/231176353-d9efb655-93b3-4557-aa8c-d4dc97950c55.png)

### Minimal Reproduction

- Create a basic Ionic Angular application using Ionic cli wizard
- Build the application using `@angular-devkit/build-angular:browser-esbuild`
- Try to run the newly built app on your local http server

Result: the app doesn't start because of missing `ion-app_8.entry.js` file.

### Exception or Error

```text
Failed to fetch dynamically loaded module: ion-app_8.entry.js
```

### Your Environment

```text
Angular CLI: 15.2.5
Node: 18.15.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 15.2.6
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.5
@angular-devkit/build-angular   15.2.5
@angular-devkit/core            15.2.5
@angular-devkit/schematics      15.2.5
@angular/cli                    15.2.5
@schematics/angular             15.2.5
rxjs                            7.5.7
typescript                      4.8.4
```

**Comment by clydin** [comment]
This appears to be an issue with Ionic's Angular support.  Ionic is attempting to dynamically import components via runtime evaluation which is not supported.  The Ionic Angular package may need to be updated to setup in a similar way to the other framework packages which do not appear to rely on the runtime evaluation.

**Comment by alan-agius4** [comment]
Closing as this is not actionable from our end.
