### ISSUE TITLE
Add code coverage report

### ISSUE THREAD

**Issue by cironunes** [angular/angular-cli#25]
https://github.com/mochajs/mocha/wiki#test-coverage

**Comment by hansl** [comment]
Is this for the CLI itself or the scaffolded project?

**Comment by cironunes** [comment]
well, both? :)

**Comment by JimTheMan** [comment]
+1 for adding test coverage reports for the scaffolded project (Something similar to Istanbul for Angular 1 projects).

**Comment by filipesilva** [comment]
Closed in favor of https://github.com/angular/angular-cli/issues/883, since it has a bit more meaningful progress there.

Related PR https://github.com/angular/angular-cli/pull/895
