### ISSUE TITLE
get Error when run ng command

### ISSUE THREAD

**Issue by wor-k** [angular/angular-cli#2500]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Debian wheezy

### Versions.
> Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.7.0
os: linux x64

### Repro steps.
> Use node:6-wheezy image and install angular-cli@beta.16. Cannot run any command except help and version. Even ng new is not work.

### The log given by the failure.
> Normally this include a stack trace and some more information.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Error

### Mention any other details that might be useful.

> Not know how to investigate an issue

**Comment by wor-k** [comment]
It's just the wrong angular-cli.json as below. 
`
"environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.dev.ts",
        "prod": "environments/environment.prod.ts",
        "local": "environments/environment.local.ts"**,**
      }
`

**Comment by filipesilva** [comment]
What is the console output when you run `npm install -g angular-cli`? And what about when you do `ng version`.
