### ISSUE TITLE
esbuild ng serve not watching files outside project root

### ISSUE THREAD

**Issue by gmfun** [angular/angular-cli#25011]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16.0.0-next.7

### Description

Using nx workspace style project where app is in `apps/some-app` and it imports code from projects inside `projects/some-project`. When i use `ng serve some-app` with esbuild, changes in `projects/some-project` does not trigger reload.

The code in `project/some-project` is reference using `tsconfig.json` `paths`.

```json
{
  "compilerOptions": {
       "paths": {
              "@org/some-project": ["projects/some-project/src/index.ts"]
       }
}
```

This used to work in v16.0.0-next.7 and with webpack based ng serve

### Minimal Reproduction

- create a new nx workspace
- create an application
- create a library
- use the library in the application
- run `ng serve` with esbuild for the application
- make changes the the referenced library
- reload is not triggered

### Your Environment

```text
v16.0.0-rc-0
```

**Comment by esagawe** [comment]
I have this problem, too, with Angular 16.0.0 (final release). All changes to Nx libs are complety ignored, even after an explicit reload.

**Comment by pumano** [comment]
Also problem when using nx monorepo, when you create libs, and when libs changed, no rebuild / not watched

**Comment by pumano** [comment]
That issue is blocker for migrating to esbuild

**Comment by yharaskrik** [comment]
Also running into this with an Nx monorepo. Can confirm it does not work with stuff outside app dir but does for code within app dir.

**Comment by Zwergenpunk** [comment]
same issue here

**Comment by alan-agius4** [comment]
@dick2tick, the esbuilder is still experimental and thus it is not yet feature complete.

**Comment by dick2tick** [comment]
smart developer: I made a great car, the color is great, the comfort is great, everything is great; you can try it from v16
stupid developer: I can't start the car
smart developer: it's still an experimental car
stupid developer: ok, what's the point of a car!?!

**Comment by AdditionAddict** [comment]
Currently the watcher adds the `projectRoot` and some package manager changes but nothing else. 
Would need the option to configure or auto detect based off compilerOptions > paths to unblock

https://github.com/angular/angular-cli/blob/77f21c1ba1e9864ef7a7aea3c4e84b8f6428f5d7/packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts#L662

  watcher.add(normalizedOptions.projectRoot);

**Comment by pumano** [comment]
I test that feature, it's still not working. Watcher not checking tsconfig `paths`

**Comment by atsjo** [comment]
in 16.1 it works for .ts files, but still not for html or css in libraries...
