### ISSUE TITLE
Exclude folders from automatic build watchers

### ISSUE THREAD

**Issue by Biopenlandes** [angular/angular-cli#2502]
> Please provide us with the following information:
angular-cli beta.16, using webpack. project created with the CLI

Hi,

This is my project structure :

```
- server
   - server.js
- src
   - app
       - compoents & co
   - assets
   - index.html
```

I'm using server.js for handling upload request coming from one of my angular component.
The file is uploaded and I want to put it in the assets directory, so i can use it after in the app.

The problem is when I do such work (uploading a file in the assets folders) that make my angular-cli to re build the entire app (because  it detect a change in my files), so the app is reloaded in the browser and i cannot use it.

Is there a way to exclude somes folders (for me the 'assets' folder) for the "watch build" task of the CLI? so the CLI don't build the app again when i'm putting a new file into it?

Thank you for the answer, and thank you very much for you work !

**Comment by llekn** [comment]
Just for the record... this was also asked on #2425

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/2425#issuecomment-252453952

**Comment by moravcik** [comment]
Comment in #2425 doesn't say much, in that case the double recompilation was caused probably by bug.

Anyway, I think this is valid feature request, to enable excluding folders from build watchers or from build entirely. In my project I have also server code and every time I make some change in server code the client code is getting reuilt, which is not desired. 

Excluding folders/patterns from webpack rules is essential part of webpack config, so it shouldn't be a big issue to make this extra config option available.
