### ISSUE TITLE
ng commands don't exit

### ISSUE THREAD

**Issue by SmallhillCZ** [angular/angular-cli#25034]
### Command

build, version, maybe others

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Tried few older versions, but with no luck, maybe it's caused by something external? E.g. analytics (see comment below) responding with non standard error?

### Description

When I run 

### Minimal Reproduction

```
npm i -g @angular/cli@latest
ng version
```

### Your Environment

```text
Angular CLI: 15.2.6
Node: 18.16.0
Package Manager: npm 9.5.0
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1502.6 (cli-only)
@angular-devkit/core         15.2.6 (cli-only)
@angular-devkit/schematics   15.2.6 (cli-only)
@schematics/angular          15.2.6 (cli-only)
```

### Anything else relevant?

~~Works with node v18.12.1 on both Linux and Windows.~~

**Comment by SmallhillCZ** [comment]
Seems that it gets solved by `ng analytics disable --global`

**Comment by alan-agius4** [comment]
Hi @SmallhillCZ, so i the CLI exists correct with with Node.js18.12.1 but not 18.16.0?

**Comment by alan-agius4** [comment]
https://github.com/angular/angular-cli/pull/25035 should address the problem
