### ISSUE TITLE
`ng build` for production on ng16 (webpack builder) has significantly higher memory pressure

### ISSUE THREAD

**Issue by jpike88** [angular/angular-cli#25031]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.1.5 (typescript version 4.9.5)

### Description

After upgrading to ng16.0.0-RC0 (typescript 5.0.3), I've noticed a much higher load on my build runners, to the point of an out of memory error.

I run with `NODE_OPTIONS="--max-old-space-size=8192"` at all times.

Originally, builds would work fine on 
`buildjet-4vcpu-ubuntu-2204-arm`, but with 16-RC0, I had to try `buildjet-8vcpu-ubuntu-2204-arm`, then `buildjet-16vcpu-ubuntu-2204-arm` until the memory crash didn't occur.

Below are the stats, to show where I started and where I ended up.
vCPU	RAM	YAML runner tag
4 vCPU	6 GB	buildjet-4vcpu-ubuntu-2204-arm
8 vCPU	12 GB	buildjet-8vcpu-ubuntu-2204-arm
16 vCPU	24 GB	buildjet-16vcpu-ubuntu-2204-arm

So I went from just 6GB to needing somewhere between 12GB-24GB on my runners to not have an out of memory error. This cannot be easily explained by pointing at memory possibly used by other services.

Attached are two cpu profiles, named appropriately. These were taken on an M1 Max with 32GB RAM. Obviously the pipeline seemed to be quite different, so it's hard to tell where the memory bloat might be happening.

[cpuProfiles.zip](https://github.com/angular/angular-cli/files/11257711/cpuProfiles.zip)

### Minimal Reproduction

Do a production build (including optimizations etc) with 15.1.5, then try with 16-RC0, compare memory usage

### Your Environment

```text
n/a because comparing two seperate versions of ng and typescript
```

**Comment by alan-agius4** [comment]
Hi @jpike88, can you please provide heap memory snapshots which can be generated using the Chrome dev tool?

**Comment by jpike88** [comment]
<img width="1161" alt="Screenshot 2023-04-21 at 12 08 19 pm" src="https://user-images.githubusercontent.com/9585787/233545699-e6a7f9a1-ddfe-4759-a32c-ff1284dd408c.png">

heap snapshot links below:
https://drive.google.com/file/d/1-gvzK62UnaRTiVxM84l78_aZwuMyv12v/view?usp=sharing
https://drive.google.com/file/d/1GGTCwCkn8zebaHUfVwR7X2iDbSXRbHCO/view?usp=sharing
https://drive.google.com/file/d/1HjzbaUhSko4jfJtd4GSWcNc7JagABLir/view?usp=sharing
https://drive.google.com/file/d/1_U-kqfky5bFz2IQaf1Dywbevh8Mh4pMF/view?usp=sharing
https://drive.google.com/file/d/1qV9rhLZDdCc8jsO9fK1kZfz5uB06uJX1/view?usp=sharing

**Comment by jpike88** [comment]
![68747470733a2f2f6170692e676c6f62616467652e636f6d2f76312f636861727467656e2f737461636b65642d617265612f74696d652f63686172745f737461636b65645f617265615f74696d655f32623839373164612d626237312d343461622d613735312d396464663263316635656532](https://user-images.githubusercontent.com/9585787/234182424-b8a37318-9bfd-49c0-a755-08e7a9a3eae6.svg)

More profiling of the runner itself. `ng build` process begins at 05:21:45 and terminates near the end of the graph. Memory usage of the process rises to 2GB... then appears to spike to 5GB.

**Comment by jpike88** [comment]
![68747470733a2f2f6170692e676c6f62616467652e636f6d2f76312f636861727467656e2f737461636b65642d617265612f74696d652f63686172745f737461636b65645f617265615f74696d655f37613366343035312d333333332d343265612d386462352d346637303231393864383538](https://user-images.githubusercontent.com/9585787/234204967-a2230a2d-dc45-4f92-ac71-4b5e48125ab0.svg)

Memory profile of a much larger runner (The one that we're running with for now). Build begins just after the 05:40 mark, so that means the total build used over 6GB of memory... that's pretty excessive...

**Comment by jpike88** [comment]
![68747470733a2f2f6170692e676c6f62616467652e636f6d2f76312f636861727467656e2f737461636b65642d617265612f74696d652f63686172745f737461636b65645f617265615f74696d655f30343833313933332d616334392d343533632d393533392d383963616666653137376233](https://user-images.githubusercontent.com/9585787/234660163-1b27fc6e-3c47-411b-bb49-d4ccc4f25e81.svg)

Minor improvement, looks like peak of just over 4gb. Still too much for the runner we were using with ng15 however, which is weird because the runner says it has 6 GB... ah well I guess this will have to do.
