### ISSUE TITLE
Question:  using the CLI and Visual Studio Code and Launch using F5?

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#2504]
This is more of a question to the community, has anyone attempted to use Visual Studio Code Launch using F5 to debug a project that is created via the CLI?

I am struggling getting this to work.  This for sure can be a user error.  But I am curious if anyone has attempted this and if they are successful?

**Comment by splintercode** [comment]
hmm I would be interested in this as well. I know VSCode can debug node apps so I can't imagine that this is out of the realm of possibility.

**Comment by jmesa-sistel** [comment]
read this issue [2453](https://github.com/angular/angular-cli/issues/2453)
