### ISSUE TITLE
[Feature] - Linking library with application in Angular Multi Project Workspace by src path instead of dist/path - for hot reloads 

### ISSUE THREAD

**Issue by dinbtechit** [angular/angular-cli#25056]
### Command

generate

### Description

Currently, when you create a multi-project workspace with a library and application. To view the library changes you have first do `ng build my-lib --watch` and then `ng serve`. This is a bit clunky.
```
$ ng new base-workspace --no-create-application
$ ng g library  my-lib --root libs/my-lib
$ ng g application my-app
```
The problem is in `tsconfig.json` uses the path  to the `dist` folder.

```json
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "my-lib": [
        "dist/my-lib",  <<--------------<<<<
      ]
    },
```

### Describe the solution you'd like

Update `tsconfig.json` file to point to the src path rather than the dist path. This eliminates the need to build the library everytime you make a code change. Especially when you developing & testing locally. All you have to do is `ng serve` and the hot reload should take care of the rest.

```json
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "my-lib": [
        "libs/my-lib/src/public-api",       <<--------------<<<<
      ]
    },
```

### Describe alternatives you've considered

Currently I have to manually update the `tsconfig.json` file. It would be nice if angular cli can take care of this.

**Comment by alan-agius4** [comment]
Thanks for opening the issue, we do not recommend using this pattern.
Please see: https://angular.io/guide/creating-libraries#building-and-rebuilding-your-library

**Comment by dinbtechit** [comment]
Thank you for sharing the link. However, the link does not explain why a `mylist/src/public-api` pattern is bad. Is there any specific reason why we want use the `dist/path` over `mylib/src/`.

**Comment by alan-agius4** [comment]
From the link: 

> The CLI build command uses a different builder and invokes a different build tool for libraries than it does for applications.

> The build system for applications, @angular-devkit/build-angular, is based on webpack, and is included in all new Angular CLI projects
> The build system for libraries is based on ng-packagr. It is only added to your dependencies when you add a library using ng generate library my-lib.
> The two build systems support different things, and even where they support the same things, they do those things differently. This means that the TypeScript source can result in different JavaScript code in a built library than it would in a built application.

> For this reason, an application that depends on a library should only use TypeScript path mappings that point to the built library. TypeScript path mappings should not point to the library source .ts files.

Since building an app and library use different build pipeline there can be some difference in output. While in most cases this is not a problem, there are cases were it can cause broken behaviour. This is because when when pointing the path mappings to `src` of the library, this is built as part of the application using the application build pipeline. In other terms, it is no longer treated as a library, but rather it just another directory in the application.
