### ISSUE TITLE
route var name as parameter in ng g module --routing =true

### ISSUE THREAD

**Issue by windmillcode0** [angular/angular-cli#25057]
### Command

generate

### Description

We would like to be able to choose a specifc variable other than "routes" in the routing module when we generate modules and components that are to be routed we have a branch for it pulling from main however it seems we can push our branch for merge consideration

### Describe the solution you'd like

Here is the solution we have so far[](url)
from the respective index.ts,schema.json we would like an additional option
```  
export function addRouteDeclarationToModule(
  source: ts.SourceFile,
  fileToAdd: string,
  routeLiteral: string,
  routesVarNameParam?:string
): Change {
...
if (ts.isArrayLiteralExpression(routesArg)) {
    routesArr = routesArg;
  } else {
    const routesVarName = routesVarNameParam ?? routesArg.getText();
    let routesVar;
    if (routesArg.kind === ts.SyntaxKind.Identifier) {
      routesVar = source.statements.filter(ts.isVariableStatement).find((v) => {
        return v.declarationList.declarations[0].name.getText() === routesVarName;
      });
    }
...
}

```

### Describe alternatives you've considered

pulling down the source code and making our own schematic which is working well

**Comment by alan-agius4** [comment]
Hi @windmillcode0, 

Thanks for the issue but providing an option to change the variable name is not something that we'd like to add as a public API. 

In this case, extending the module schematic is the right approach. 

Thanks.
