### ISSUE TITLE
Webpack Asset Modules Support

### ISSUE THREAD

**Issue by olfek** [angular/angular-cli#25050]
### Command

build

### Description

Continuation of #22351 

In Angular, am I correct in saying that there is currently no way of doing this:

https://webpack.js.org/guides/asset-modules/#source-assets

?

### Describe the solution you'd like

Support for Asset Modules or something similar

### Describe alternatives you've considered

Currently, this can be done in Angular with

https://v4.webpack.js.org/loaders/raw-loader/

but it is DEPRECATED in favor of Asset Modules.

**Comment by alan-agius4** [comment]
Webpack specific features are not supported by design.

In this case, it recommended to either retrieve the text content through HTTP of place its content in as string.
