### ISSUE TITLE
ng build --prod  Does not iterate through apps [] within angular-cli.json

### ISSUE THREAD

**Issue by fullstackdave** [angular/angular-cli#2506]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 10 Development

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.16
node: 6.7.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

This app was created with the CLI then modified to be integrated into a pre-existing fullstack project.  The structure of the CLI has been completely changed to fit our needs but works fine.  When I run "ng build --prod" only the first application in the array gets built, if I want subsequent apps to be built I have to move them to the 0 index of the array of "apps": [] withn the anglular-cli.json.

### The log given by the failure.
> Normally this include a stack trace and some more information.

generates no errors

### Mention any other details that might be useful.

While this isn't a deal breaker for us, more of a time sink; one would assume that the array of app objects would be iterated.

Test project found here:
https://github.com/fullstackdave/angular2-multi-app

spa/app/* = "src" directory
public/js/app/* = "dist" directory

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We don't actually yet support building multiple apps. We chose that structure for the config in order to give us freedom to have multiple apps, but there are still other considerations that we need to address before actually supporting it.

**Comment by suplch** [comment]
I also create a issue https://github.com/angular/angular-cli/issues/3213,  I also hope to support build  multi-bundle at the same time. Because of in some time, we only want to provide a little function to user without download whole large code.

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/pull/5737 added documentation for how multiple apps can be built in the same project.
