### ISSUE TITLE
Error while building Angular 15 application

### ISSUE THREAD

**Issue by ShrutiThakur01** [angular/angular-cli#25075]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have upgraded my angular project from 8 to 15 . I am getting below error while "ng build" .
I have .net core 7 installed.
I have a Mac with M1 chip. 

### Minimal Reproduction

no steps to reproduce as its simply throwing error on build command

### Exception or Error

```text
[webpack-dev-middleware] HookWebpackError: Transform failed with 1 error:
<e> styles.css:1:71: ERROR: Expected ")" to end URL token
<e>     at makeWebpackError (/Users/shrutithakur/Documents/ClientApp/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/HookWebpackError.js:48:9)
<e>     at /Users/shrutithakur/Documents/ClientApp/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compilation.js:3060:12
<e>     at eval (eval at create (/Users/shrutithakur/Documents/ClientApp/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:132:1)
<e>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
<e> -- inner error --
<e> Error: Transform failed with 1 error:
<e> styles.css:1:71: ERROR: Expected ")" to end URL token
<e>     at failureErrorWithLog (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:1636:15)
<e>     at /Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:837:29
<e>     at responseCallbacks.<computed> (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:697:9)
<e>     at handleIncomingPacket (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:752:9)
<e>     at Socket.readFromStdout (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:673:7)
<e>     at Socket.emit (node:events:513:28)
<e>     at addChunk (node:internal/streams/readable:324:12)
<e>     at readableAddChunk (node:internal/streams/readable:297:9)
<e>     at Readable.push (node:internal/streams/readable:234:10)
<e>     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
<e> caused by plugins in Compilation.hooks.processAssets
<e> Error: Transform failed with 1 error:
<e> styles.css:1:71: ERROR: Expected ")" to end URL token
<e>     at failureErrorWithLog (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:1636:15)
<e>     at /Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:837:29
<e>     at responseCallbacks.<computed> (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:697:9)
<e>     at handleIncomingPacket (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:752:9)
<e>     at Socket.readFromStdout (/Users/shrutithakur/Documents/ClientApp/node_modules/esbuild/lib/main.js:673:7)
<e>     at Socket.emit (node:events:513:28)
<e>     at addChunk (node:internal/streams/readable:324:12)
<e>     at readableAddChunk (node:internal/streams/readable:297:9)
<e>     at Readable.push (node:internal/streams/readable:234:10)
<e>     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

### Your Environment

```text
Angular CLI: 15.2.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 15.2.8
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1502.7
@angular-devkit/build-angular              15.2.7
@angular-devkit/core                       15.2.7
@angular-devkit/schematics                 15.2.7
@angular/cli                               15.2.7
@nguniversal/express-engine                15.2.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        15.2.7
rxjs                                       7.8.0
typescript                                 5.0.4
```

### Anything else relevant?

my browser list file as below

# This file is used by the build system to adjust CSS and JS output to support the specified browsers below.
# For additional information regarding the format and rule options, please see:
# https://github.com/browserslist/browserslist#queries

# You can see what browsers were selected by your queries by running:
#   npx browserslist

last 1 Chrome version
last 1 Firefox version
last 2 Edge major versions
last 2 iOS major versions
Firefox ESR
not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
not ios_saf 15.2-15.3
not safari 15.2-15.3

**Comment by alan-agius4** [comment]
From the error is looks like there is an error in css syntax.

```
styles.css:1:71: ERROR: Expected ")" to end URL token
```

**Comment by ShrutiThakur01** [comment]
okay. Thanks for your response .

is it because of below line in style.css?

@import url('https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet"');

body {
  font-family: 'Calibri','Roboto', sans-serif;
  font-size: 12px;
  font-weight: normal;
  /*background: #e3e3e3;*/
   color: #444444;
  background: #ffffff;
}

**Comment by alan-agius4** [comment]
Yes

**Comment by ShrutiThakur01** [comment]
Is there anything I have missed while upgrading from Angular version 8 - 15? Because this runs perfectly on Angular 8.
When I comment this line , I get stylesheet error


./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: Emit attempted before Angular Webpack plugin initialization.

./src/styles.scss - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
1 │ @use 'igniteui-theming/sass/color/functions' as *;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/igniteui-angular/lib/core/styles/base/_mixins.scss 1:1   @forward
  node_modules/igniteui-angular/lib/core/styles/base/_index.scss 2:1    @use
  node_modules/igniteui-angular/lib/core/styles/themes/_core.scss 6:1   @forward
  node_modules/igniteui-angular/lib/core/styles/themes/_index.scss 1:1  @import
  src/styles.scss 6:9                                                   root stylesheet

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
