### ISSUE TITLE
Request to implement Idle timeout for ng serve process

### ISSUE THREAD

**Issue by softgandhi** [angular/angular-cli#25073]
### Command

serve

### Description

Hi there,
I would like to know if we have any feature that would kill or terminate the ng serve process automatically (without pressing ctrl + c manually) where requests are not being served for more than n minutes.

Why I need it?
most of the time, while doing multi-tasking, I forget to manually kill ng serve command even long after switching to another task or leaving the computer on and moving out of desk. ng serve keeps on running taking ˜2GB of ram blocking for other processes. so, its better to auto kill "ng serve" process when requests are not being served for more than n mins.

I am not sure if any similar feature is already there.
I hope other people would also be facing same issue especially on Mac M1 where I don't have option to upgrade my RAM. 

### Describe the solution you'd like

probably an idle timer implementation to auto stop ng serve process.

### Describe alternatives you've considered

I currently don't think of any good alternative.

**Comment by alan-agius4** [comment]
Hi @softgandhi, 

Thanks for this feature request.

However, this currently is not in scope.
