### ISSUE TITLE
Easily and continuously experiment with esbuild-based builder

### ISSUE THREAD

**Issue by pweyrich** [angular/angular-cli#25087]
### Command

build

### Description

Right now, one is not able to easily and continuously experiment with esbuild-based builder.

For instance, I would like to easily be able to run development builds (e.g. on CI) with esbuild but production builds still with webpack while making sure both builders share the same configuration.

### Describe the solution you'd like

There are two possible solutions that I can think of:

1. Be able to override the `builder` per configuration
```
projects: {
    project: {
      "architect": {
        "build": {
          "builder":  "@angular-devkit/build-angular:browser",
           "configurations: {
             "production": {...},
             "development": {
                "builder": "@angular-devkit/build-angular:browser-esbuild",
                ...
             }
           }
         },
      }
    }
```
2. Be able to reference another target in a custom build target similar to what we can do in the `serve` target right now.
```
  projects: {
    project: {
      "architect": {
        "build": {
          "builder":  "@angular-devkit/build-angular:browser",
           "configurations: {
             "production": {...},
             "development": {...}
           }
         },
        "build-esbuild": {
          "builder": "@angular-devkit/build-angular:browser-esbuild",
          "configurations": {
            "production": {
              "browserTarget": "project:build:production"
            },
            "development": {
              "browserTarget": "project:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
      }
    }
```

### Describe alternatives you've considered

Current solutions that I am aware of: 

1. Create another project in the workspace that uses `@angular-devkit/build-angular:browser-esbuild` as builder for the `build` target. 
Build can be invoked with `ng build <project>` then.
2. Add a new target (e.g. `build-esbuild`) to the current project that uses `@angular-devkit/build-angular:browser-esbuild` as builder. 
Build can be invoked with `ng run <project>:build-esbuild` then.

Both solutions require us to replicate the build config.

**Comment by alan-agius4** [comment]
Hi @pweyrich,

Thanks for this request. 

In this case replicating the config is the best option as it is is also more future proof.
