### ISSUE TITLE
`ng serve` esbuild is misreporting missing file in cli

### ISSUE THREAD

**Issue by jpike88** [angular/angular-cli#25080]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

n/a

### Description

See title

### Minimal Reproduction

See errors in red.
<img width="994" alt="Screenshot 2023-04-27 at 12 53 55 pm" src="https://user-images.githubusercontent.com/9585787/234771639-37a80c0d-f831-46b6-8092-ec2a8abee0cb.png">
<img width="996" alt="Screenshot 2023-04-27 at 12 54 45 pm" src="https://user-images.githubusercontent.com/9585787/234771783-22476cfa-d946-4985-9889-0482ce654846.png">

Yet in the browser, the file looks like it was bundled fine...
<img width="1234" alt="Screenshot 2023-04-27 at 12 54 58 pm" src="https://user-images.githubusercontent.com/9585787/234771812-98902013-4b03-4145-b81e-ed56de4d3e1a.png">

relevant configuration in my angular.json:

```
"assets": [
								{
									"glob": "**/*",
									"input": "src/assets/",
									"output": "/"
								},
								{
									"glob": "**/*",
									"input": "node_modules/ngx-extended-pdf-viewer/assets/",
									"output": "/assets/"
								}
							],
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.0-rc.2
Node: 16.14.2
Package Manager: npm 9.6.3
OS: darwin arm64

Angular: 16.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1600.0-rc.2
@angular-devkit/build-angular      16.0.0-rc.2
@angular-devkit/core               16.0.0-rc.2
@angular-devkit/schematics         16.0.0-rc.2
@angular/cdk                       16.0.0-rc.1
@angular/flex-layout               15.0.0-beta.42
@angular/material                  16.0.0-rc.1
@angular/material-moment-adapter   16.0.0-rc.1
@schematics/angular                16.0.0-rc.2
rxjs                               7.8.0
    

```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by jpike88** [comment]
[Archive.zip](https://github.com/angular/angular-cli/files/11341032/Archive.zip)

- npm ci in root dir
- npm ci in client dir
- go to root dir in terminal, run `npx gulp test` or `gulp test` and wait for server to start
- open the test.code-workspace in VSCode
- use the Client launch option to launch
- Red errors should appear

**Comment by alan-agius4** [comment]
I am unable to find the mentioned launcher. Does this issue only occur when using vscode?

**NB:** In future it would be great if you avoid using zip files and instead push into a public repository.

**Comment by jpike88** [comment]
Sorry the launch.json wasn't included in the archive. Here you go

https://github.com/jpike88/esbuild-issue

```
- `npm ci` in root dir
- `npm ci --legacy-peer-deps` in client dir
- go to root dir in terminal, run `npx gulp test` and wait for server to start
- open the test.code-workspace in VSCode
- use the Client launch option to launch
- Red errors should appear
```
