### ISSUE TITLE
Implement i18n functionality in esbuild-based browser application builder

### ISSUE THREAD

**Issue by clydin** [angular/angular-cli#25099]
### Command

build

### Description

Implement the `localize` option and related functionality for the esbuild-based browser application builder.

**Comment by zip-fa** [comment]
Any news?

**Comment by jcompagner** [comment]
is this error:

"Could not set Locale because angular locale could not be loaded."

the result of this problem?

**Comment by spock123** [comment]
@jcompagner Correct, i18n is not yet implemented in ESBuild. I'm also waiting for it :)

**Comment by alan-agius4** [comment]
Support for localization has been added in v17 which is currently in prerelease.
