### ISSUE TITLE
App served by `ng serve` is not accesible from inside Android Virtual Device

### ISSUE THREAD

**Issue by olfek** [angular/angular-cli#25105]
### Command

serve

### Is this a regression?

I don't know.

### Description

Following this guide:

https://developer.android.com/studio/run/emulator-networking

The web app should be accessible at `http://10.0.2.2:4200` via `ng serve` on the host machine.

But the request times out.

It _**does**_ work with `ng serve --host 0.0.0.0`

Why is `--host 0.0.0.0` necessary? It _**should**_ work with just `ng serve`.

### Minimal Reproduction

- see above for commands run
- no extra packages added
- no code changes or specific code required

### Your Environment

```text
Angular CLI: 15.1.6
Node: 18.14.0
Package Manager: npm 9.3.1
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1501.6 (cli-only)
@angular-devkit/core         15.1.6 (cli-only)
@angular-devkit/schematics   15.1.6 (cli-only)
@schematics/angular          15.1.6 (cli-only)
```

**Comment by clydin** [comment]
`ng serve` defaults to binding to `localhost` only.  This limits the potential to accidentally expose the development server to the entire local network. Binding to external interfaces must be explicitly opted-in but can be set as the default within the `angular.json` configuration for the development server using the `host` option.
