### ISSUE TITLE
Cap the .angular/cache size as default

### ISSUE THREAD

**Issue by AndreasPlahn** [angular/angular-cli#25116]
### Command

build, serve

### Description

When working as a developer with Angular 13 projects an ".angular/cache" directory is created. 
This directory goes up to around 10GB of space after a while, when working with the code base. 

Lets say you have 15 angular projects up and running as an angular developer. That is 150GB just for caching.
Would it be possible to set a default cap at 1GB or something reasonable? 

More info here regarding cache folder growing: 
https://github.com/angular/angular-cli/issues/22323

**Comment by alan-agius4** [comment]
Closing as per above.
