### ISSUE TITLE
tsconfig types not taken into account

### ISSUE THREAD

**Issue by vekexasia** [angular/angular-cli#2512]
> ## Please provide us with the following information:
### OS?

> Linux
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: linux x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

adding `types` within tsconfig.json or `exclude` have no affect on which types ges loaded when doing `ng serve` or `ng build`

**Comment by filipesilva** [comment]
Can you give me a specific repro of this problem?

**Comment by filipesilva** [comment]
https://github.com/angular/angular-cli/issues/4022#issuecomment-272784902
