### ISSUE TITLE
TypeError [Error]: Cannot read properties of undefined (reading 'column')  at convertSourceSpan

### ISSUE THREAD

**Issue by menelai** [angular/angular-cli#25134]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.2

### Description

Compilation fails on SASS processing

### Minimal Reproduction

node --max_old_space_size=8000 ./node_modules/@angular/cli/bin/ng serve --host=0.0.0.0 --disable-host-check --port=4700

maybe there must be an error in SASS files

### Exception or Error

```text
| Generating browser application bundles (phase: building)...
node:internal/event_target:1010
                           ^
TypeError [Error]: Cannot read properties of undefined (reading 'column')
    at convertSourceSpan (F:\frontend\node_modules\@angular-devkit\build-angular\src\sass\worker.js:146:30)
    at MessagePort.<anonymous> (F:\frontend\node_modules\@angular-devkit\build-angular\src\sass\worker.js:111:27)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:290:10)
    at [kOnMessage] (node:internal/worker:301:37)
    at MessagePort.<anonymous> (node:internal/worker:202:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.14.0
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.0
Node: 18.14.0
Package Manager: npm 9.1.3
OS: win32 x64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
This is a bit odd as a sass exception span should should always have these properties. 

Could you please provide the value of the `span` value that is being passed to `convertSourceSpan`, `console.log` should suffice.

**Comment by menelai** [comment]
```
- Generating browser application bundles (phase: building)...LazyFileSpan0 {
  '_lazy_file_span0$_builder': Parser_spanFrom_closure0 {
    '$this': SelectorParser0 {
      '_selector$_allowParent': true,
      '_selector$_allowPlaceholder': true,
      scanner: [SpanScanner],
      logger: [DeprecationHandlingLogger0],
      '_parser0$_interpolationMap': [InterpolationMap0]                     
    },                                                                      
    span: _FileSpan { file: [SourceFile], '_file$_start': 11, _end: 12 }    
  },                                                                        
  '_lazy_file_span0$_span': _FileSpan {                                     
    file: SourceFile {                                                      
      url: [_Uri],                                                          
      _lineStarts: [Array],                                                 
      _decodedChars: [Uint32Array],                                         
      _cachedLine: 17                                                       
    },                                                                      
    '_file$_start': 303,                                                    
    _end: 304                                                               
  }                                                                         
}
```

okay. How to reproduce it. Create SCSS like this:

```
@mixin dark {
  .red & {
    @content;
  }
}

@include dark {
  body {
    color: red;
  }
}
```

**Comment by alan-agius4** [comment]
Thanks for the info and reproduction code. I managed to track this down to a bug in Sass and filed an issue https://github.com/sass/dart-sass/issues/1952

**Comment by maxailloud** [comment]
Any news about this bug? Nothing in the issue you created but maybe you got some info through different channel.
And in the meantime are there any workaround for this bug? Such as downgrading sass version or another package.

I am hitting this bug right now after removing usage of `@import` and put `@use` instead.

**Comment by SoyDiego** [comment]
+1 here. I was working ok until appears this problem.
I can't compile :(

![imagen](https://github.com/angular/angular-cli/assets/19764334/48b7c4e4-1155-48e6-830c-529d964b7cce)

**Comment by AlexBilonog** [comment]
+1. Have the same error. 15.* works fine. 16.* throws error.

**Comment by k0nt1** [comment]
Same problem here. Version is *16.1.3*

**Comment by marsc** [comment]
Same problem here. My version is 16.1.3

**Comment by hadiamiri** [comment]
Same issue after upgrading from version 15 to 16
some.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Cannot read properties of undefined (reading 'column')

some.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Cannot read properties of undefined (reading 'column')

**Comment by javierverb** [comment]
> My version is 16.1.3. This happens when you use "&" in .scss without a wrapping element.
> 
> **Error** `&.some-class { ... }`
> 
> **Success** `.parent { &.some-class { ... } }`

thanks bro, just removing &.some-class that is not wrapped is enough, thanks!!!

**Comment by ovanderzee** [comment]
To me, this happened when I tried to do: '@extend p.tiny'. Selector 'p.tiny' was literally in another scss stylesheet.
Tried other element - classname combination. All led to this error.

```
Angular CLI: 16.1.3
Node: 16.20.0
Package Manager: npm 8.19.4
OS: darwin x64
```

**Comment by AzatKhalilov** [comment]
I have the same error with Angular 16.2.0 with selector:
.some-class:has(.some-internal-selector){
}
It's annoying

**Comment by sistla001** [comment]
Any update on this one? We have the same issue

**Comment by Arthur-Fedotiev** [comment]
> My version is 16.1.3. This happens when you use "&" in .scss without a wrapping element.
> 
> **Error** `&.some-class { ... }`
> 
> **Success** `.parent { &.some-class { ... } }`

This was my exact problem. I guess I've missed it since it was in media query and visually looked nested :) Nice error message would save a lot of time though

**Comment by alan-agius4** [comment]
> Any update on this one? We have the same issue on 16.2.0

@sistla001, this problem is not caused by Angular, Please see open issue in the Sass repository https://github.com/sass/dart-sass/issues/1952

**Comment by M0o4** [comment]
same issue got today with  &_disabled {}

**Comment by vamsiambati** [comment]
This happens in Angular 17.0.6 too.
until Angular 15 there is no issue

```
./src/styles/main.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

Cannot read properties of undefined (reading 'column')

./src/styles/main.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):

HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

Cannot read properties of undefined (reading 'column')
```
