### ISSUE TITLE
Expose the internal jest preset to be used for feature libs

### ISSUE THREAD

**Issue by henryruhs** [angular/angular-cli#25142]
### Command

test

### Description

In monorepo (app-shell + feature libs) we need to integrate Jest either by a custom integration or a tooling like NX - therefore this is out of the angular cli scope. Either way, it would make sense to export the `globalSetup` or a complete preset from  `@angular-devkit/build-angular/src/builders/jest'` as this is being used by the experimental Jest implementation already.

Related issue: https://github.com/thymikee/jest-preset-angular/issues/2058

### npm scripts
```
"test": "NODE_OPTIONS=--experimental-vm-modules jest",
```

### jest.config.mjs

```
import { globalSetup } from '@angular-devkit/build-angular/src/builders/jest';

module.exports =
{
	globalSetup
};
```

### current error

Of course this is not possible to import from node modules:
```
Directory import '[...]node_modules/@angular-devkit/build-angular/src/builders/jest' is not supported resolving ES modules imported from [..]jest.config.mjs
```

**Comment by alan-agius4** [comment]
Can you elloborate on which Jest features you need to configure? Also, the current experimental Jest builder does not use any presets.

**Comment by henryruhs** [comment]
Well, at least the globalSetup that comes with the TestBed and all the good stuff.

**Comment by alan-agius4** [comment]
> How would this be possible? There is no angular.json in the feature libs and therefore no Angular CLI support.

The Angular Jest integration requires that it runs against a known project. From my understanding when you create an NX feature library it is also created as a project in `workspace.json` or `project.json`.

> PS: I'm using Turbo Repo, therefore the test need to run independent from the app-shell.

Can you please elaborate I am not following what app-shell has to do with testing.  To build an app-shell a different command is used `ng run <project>:app-shell`.

**Comment by henryruhs** [comment]
Like I mentioned, I use Turbo Repo and not NX. Angular does not know about the feature libs and registering them does not make sense as Turbo Repo is running each NPM workspace independent from each other. That being said, I don't want to run testing of all feature libs via the app-shell.

**Comment by alan-agius4** [comment]
@henryruhs, thanks for explaining.

Unfortunately, similarly to how users cannot run `webpack` or `karma` binaries directly and use the inbuilt configs and plugins. Running `jest` without using a builder does not align with the Angular CLI design goals. As such in this case the given case will not be supported.
