### ISSUE TITLE
Proxy is not working when using esbuild

### ISSUE THREAD

**Issue by mslourens** [angular/angular-cli#25148]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When running an application using the esbuild the proxy config is ignored. After changing the builder back to the default, the proxy gets hit. 

### Minimal Reproduction

1. Create a new app in Angular 16 using `ng new proxy-test --standalone`
2. Change the builder option in `angular.json` to `@angular-devkit/build-angular:browser-esbuild`
3. Add a `proxyConfig` to the serve configuration
4. Run the proxy and the application
5. Endpoints using the defined proxy path are not received in the proxy.

Expected behavior: the proxy configured in the proxy.conf.json should be called when the defined endpoint is called.

Only after changing the builder option back to the default (`@angular-devkit/build-angular:browser`) is the proxy used.

### Exception or Error

```text
Nothing
```

### Your Environment

```text
Angular CLI: 16.0.0
Node: 16.14.0
Package Manager: npm 8.3.1
OS: linux x64

Angular: 16.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by clydin** [comment]
Can you provide an example proxy configuration that is exhibiting the issue?

**Comment by mslourens** [comment]
This is my proxy.conf.json:
```{
  "/api/*": {
    "target": "http://localhost:9020",
    "changeOrigin": true,
    "secure": false
  },
  "logLevel": "debug"
}
```

This is how I add it to my angular.json: 
```
{
  ...
  "serve": {
    "builder": "@angular-devkit/build-angular:dev-server",
    "configurations": {
      "production": {
        "browserTarget": "web-alliander-photostore-admin-app:build:production"
      },
      "development": {
        "browserTarget": "web-alliander-photostore-admin-app:build:development",
        "port": 4300
      },
      "proxy": {
        "browserTarget": "web-alliander-photostore-admin-app:build:proxy",
        "port": 4400,
        "proxyConfig": "proxy.conf.json"
      }
    },
    "defaultConfiguration": "development"
  }
}

```

When I used the default build option with this config, the proxy was working as expected but when I changed the build option to esbuild, the proxy was ignored.

**Comment by whyboris** [comment]
@clydin thank you for a/the solution - in my case removing the `*` from the path in `proxy.conf.json` solved the `404` I was seeing 🙇

**Comment by dick2tick** [comment]
I am using angular CLI 16.0.1 and still the proxy doesn't work although that should be fixed via https://github.com/angular/angular-cli/commit/2967705ed3f88c35e93866bca659222769664c62, the workaround (removing * or using @angular-devkit/build-angular:browser) works properly.
