### ISSUE TITLE
fileReplacement for less files

### ISSUE THREAD

**Issue by mannyNRECA** [angular/angular-cli#25152]
### Command

build

### Description

I've read multiple threads talking about fileReplacements.  One comment [#16779 comment ](https://github.com/angular/angular-cli/issues/16779#issuecomment-579183693) stated it was not meant for files outside of bundles.  If I'm not mistaken, styles are part of the bundle.

The problem: I'm using a styles package that I don't have control over.  It has a less variable for setting the base-href path for the assets.  
- When I serve it up at `/`, everything is fine
- When I serve it up at  `/some-path` I have to update this less variable to /some-path/assets

Now I have different configurations when I'm running the app locally and when I'm deploying it at /some-path on a server and angular fileReplacements doesn't support this scenario.

### Describe the solution you'd like

I'd like to be able to replace any file at the src root level for different configurations.  This would allow me to have:

- styles.base.less (all my imports and global styles)
- styles.less (import styles.base.less and modify the less variable)
- styles.local.less (import styles.base.less, no variable modification, use this to replace styles.less in local config)

### Describe alternatives you've considered

- Considered fileReplacement above ^
- Considered putting a file in assets, but I believe .less is a preprocessor on css and it would only copy the file
- Considered webpack.config.js but again it would just copy the file without doing the pre-processing
- Considered running a script right before build.  I'm using nx so none of my nx build commands would work without creating an npm script for each one

**Comment by alan-agius4** [comment]
Hi, `fileReplacements` is intended to work only on TypeScript source files. Expanding  this to other files types is not planned nor desired.

In this case, I would recommend that you use the same base-href for development and production. Alternatively, configure different LESS files in `styles` build option based on the build config.

```
“build”: {
   …
    "options": {
         …
         "styles": ["local.less"]
    },
    "configuration": {
          "production": {
               …
               "styles": ["prod.less"]
           }
    }
}

**Comment by mannyNRECA** [comment]
Your suggestion worked for me.  Thank you!

Re: base-href, I'd love to have them match but I've been struggling with that.  I'll have to give it another go later.
