### ISSUE TITLE
Module not found with relative imports with .js extension in a typescript project

### ISSUE THREAD

**Issue by magwas** [angular/angular-cli#25157]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I use relative imports with '.js' extension from TypeScript, the module is not found.
`./src/common/Synchronizer.ts:3:0-61 - Error: Module not found: Error: Can't resolve '../inez/repositories/actions.js' in '/home/mag/project/KodeKonveyor/angulartest/src/common`

I converted the code to this style because the unit testing tool I use can work reasonably fast (without bundling) with ESM modules.

I do believe that requiring relative imports with extensions for ESM modules in TypeScript is a bug of the TypeScript compiler, but they treat it as a feature. So here we are.

### Minimal Reproduction

Convert an import to relative one and add '.js' extension. 

### Your Environment

```text
Angular CLI: 15.2.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: linux x64

Angular: 15.2.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.7
@angular-devkit/build-angular   15.2.7
@angular-devkit/core            15.2.7
@angular-devkit/schematics      15.2.7
@angular/cli                    15.2.7
@schematics/angular             15.2.7
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
This should work when using the esbuild based builder which is currently in developer preview.
