### ISSUE TITLE
Tailwind CSS is not applied on Sass/Less with browser-esbuild

### ISSUE THREAD

**Issue by canserkanuren** [angular/angular-cli#25169]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello,

While trying to use the new esbuild system of Angular, shipped with v16, I realized that using Tailwind CSS with default configuration (explained [here](https://tailwindcss.com/docs/guides/angular)), CSS styles are not applied to current HTML (while they are currently applied by using Angular's default build system).

I have created a repository with the default configuration that reproduces the bug, available [here](https://github.com/canserkanuren/tailwind-angular).

Can you please help me out on this, as I'd like to use Angular's new build system based on esbuild :)

Thanks a lot for your help!

### Minimal Reproduction

use latest version of @angular/cli
ng new tailwind-test
cd tailwind-test
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init
ng serve 
it should be working by including basic tailwind CSS into the project.

switch to new esbuild build system
ng serve
Styles that were applied before are not applied with esbuild.

### Your Environment

```text
# canserkanuren @ macbook-pro-de-can in ~/workspace/Perso/todos-test on git:main o [20:58:53] 
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.0.0
Node: 16.19.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 16.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by clydin** [comment]
The linked project appears to be using Sass for the stylesheets.  If you use a CSS file for the global stylesheet then Tailwind CSS will be used to process the file.
Tailwind within a Sass file is currently not implemented in the esbuild-based build system. Could you provide additional information regarding your use case for combining Tailwind with Sass?

**Comment by canserkanuren** [comment]
> The linked project appears to be using Sass for the stylesheets. If you use a CSS file for the global stylesheet then Tailwind CSS will be used to process the file. Tailwind within a Sass file is currently not implemented in the esbuild-based build system. Could you provide additional information regarding your use case for combining Tailwind with Sass?

I'll try using a CSS file for Tailwind then.
I don't have any specific usecases for combining Sass with Tailwind at the moment but I'm using Sass by default when creating a new frontend application.
Do you have a roadmap regarding the implementation of Sass support in the esbuild-based system ?

**Comment by clydin** [comment]
Sass itself is fully supported.  Tailwind CSS, however, currently can only be used with CSS and is not available with either supported preprocessor (Less/Sass).

**Comment by pumano** [comment]
I have tailwind 3.2.4 and it works good with esbuild only since angular 16, but have problems with 15.x

**Comment by canserkanuren** [comment]
> I have tailwind 3.2.4 with CSS and it works good with esbuild only since angular 16, but have problems with 15.x

do you have an example in a repository so that I can check out what's different between our projects if that's ok with you ?

**Comment by sevaru** [comment]
> The linked project appears to be using Sass for the stylesheets. If you use a CSS file for the global stylesheet then Tailwind CSS will be used to process the file. Tailwind within a Sass file is currently not implemented in the esbuild-based build system. Could you provide additional information regarding your use case for combining Tailwind with Sass?

We're using sass/tailwind in most of our projects.
In some we've already had sass and than add tailwind later.
We use both tailwind utilities and sass mixins, functions, etc

So support for tailwind+sass would be great :)

**Comment by renatoaraujoc** [comment]
Just for personal input (my use case),

I am using Tailwind with tons of `.scss` on my project, the scss files are cluttered with `@apply` directives, etc. Simply doing an overhaul of the entire app to use `.css` will not happen to my end.

Tailwind + SCSS + Webpack works flawlessly, why shouldn't it also be ported to work with esbuild?

Sticking with webpack for now until the team decides to support this.

Thanks!
