### ISSUE TITLE
generators: allow dash `-` in selector before a number

### ISSUE THREAD

**Issue by sod** [angular/angular-cli#25164]
### Command

generate

### Description

We use jira. Tickets always follow the schema `<PROJECT>-<TICKETNUMBER>` so e.g. `Task-123`. If we do an a/b test, we like to postfix the files that mirror the control group with the ticket, so e.g `feature-task-123.component.ts`. But the cli right now doesn't allow this.

See `ng g c TodoItemTask123` neither the files nor the selector have the `-`. So `task-123` is actually `task123`:
<img width="819" alt="CleanShot 2023-05-08 at 13 48 53@2x" src="https://user-images.githubusercontent.com/905328/236816236-db3dccab-743d-43ba-b171-7d6309e49e1c.png">

So what I'd like to do would be one of these:
```
ng g c TodoItemTask-123
ng g c TodoItemTask123 --selector app-todo-item-task-123
```

but both commands get rejected with `Selector "app-todo-item-task-123" is invalid`:
<img width="602" alt="CleanShot 2023-05-08 at 13 46 29@2x" src="https://user-images.githubusercontent.com/905328/236815815-b1191559-ad0e-4418-9776-83d27473df1a.png">

### Describe the solution you'd like

I'd like if `ng g c TodoItemTask-123` was allowed and generates files like:
```
todo-item-task-123.component.ts
              ^ having the dash
```

### Describe alternatives you've considered

Renaming all the files and updating the NgModule by hand afterwards.

**Comment by sumitparakh** [comment]
Hi @alan-agius4. I would like to take this up

**Comment by alan-agius4** [comment]
@sumitparakh go for it.
