### ISSUE TITLE
Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)

### ISSUE THREAD

**Issue by andreescocard** [angular/angular-cli#25178]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am trying to use RxDB on latest version of Angular but cli fails to compile anything that contains await in the code.

### Minimal Reproduction

In this repository https://github.com/andreescocard/angular-tauri-rxdb is possible to reproduce the error using ng serve command.

### Exception or Error

```text
Error: Module parse failed: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
Error: The top-level-await experiment is not enabled (set experiments.topLevelAwait: true to enabled it)
```

### Your Environment

```text
Angular CLI: 16.0.0
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@schematics/angular             16.0.0
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else relevant?

Tried to install https://www.npmjs.com/package/@angular-builders/custom-webpack?activeTab=versions but is not compatible yet with Angular version 16 to add topLevelAwait using a custom webpack like specified on error.
Tried using ES2017 on tsconfig.json on target with no luck.

**Comment by alan-agius4** [comment]
Hi @andreescocard, thanks for this feature request. 

Top level await are problematic to support as they cannot be intercepted by Zone.js. Let's re-consider this in the future when Zone.js is not a hard requirement.

**Comment by FreedomRings** [comment]
I loathe appending a note to a closed issue, but I have the same issue with a requirement for crypto which is now part of Node in "node:crypto" and requires the await for the import - so my question is - does this decision not to support top-level-await until Zone.js goes away mean that Angular will no longer support crypto and I cannot encrypt anything using Angular and Node:Crypto?  I think I understand the problem with prerequisites, but closing the issue without offering any guidance for alternatives makes me feel a bit stranded.  Can someone point me to a best practices alternative that works so that I can include crypto functions in my Angular project now that I have upgraded my project?

**Comment by alan-agius4** [comment]
Using Node.JS specific APIs in general is a bad choice and should be avoided (Unless the API is being used in `server.ts`. 

Cross-platform APIs like Web crypto API should be preferred instead.

Regarding top-level await, other than Zone.js when the bundled cose can cause some undesired/unexpected behaviour.

See: https://github.com/evanw/tla-fuzzer

**Comment by FreedomRings** [comment]
Thank you for that.  Indeed - this is a server project.  I am looking at hapi/iron modules now and am trying to make a plan before I begin refactoring the authentication system.  At least I know I can stop banging my head against the node:crypto wall!
