### ISSUE TITLE
ng generate guard command does not use new schematics

### ISSUE THREAD

**Issue by dinnerhe** [angular/angular-cli#25191]
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am using angular cli version 15.2.8.
When I try to generate route guard using ng generate, the guard generated from it still uses old shematics(class based guards which are depreciated). Is the new schematic only available in newer version of cli (since right now the documentation outputs the new schematics)?

### Minimal Reproduction

```
ng new test-app
ng generate guard auth
```

### Your Environment

```text
Angular CLI: 15.2.8
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 15.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
This is expected in version 15. 

You need to use the `—functional` command line argument.
