### ISSUE TITLE
@types dependencies are missing in package.json

### ISSUE THREAD

**Issue by thomasfischl** [angular/angular-cli#2520]
Create a new angular2 project with ng new PROJECT_NAME. During the generation process, the typescript definition files are downloaded.

@types
-- jasmine
-- node
-- q
-- selenium-webdriver

The problem is, that some dependencies are not stored in the package.json file. 

> 
{
  "name": "primeng-demo",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/router": "3.0.0",
    "chart.js": "^2.3.0",
    "core-js": "^2.4.1",
    "font-awesome": "^4.6.3",
    "primeng": "^1.0.0-beta.17",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.16",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}``

The consequence is, that if you commit this project into a SCM and anyone wants to build the project, the typescript definitions files are missing and the build fails with an typescript error.

### OS?
> Windows 10

### Versions.
> 
angular-cli: 1.0.0-beta.16
node: 5.5.0
os: win32 x64

### Repro steps.
> ng new PROJECT_NAME
delete the node_modules folder
npm install
ng build --> typescript compile failure

**Comment by RoopeHakulinen** [comment]
Please refer to Meligy's awesome [answer](https://github.com/angular/angular-cli/issues/2559#issuecomment-252205693) for explanation on why the certain `@types/*` packages don't appear on the _package.json_ even though they are downloaded to _node_modules/_. In short, only `@types/jasmine` is actually needed by the application itself, others are for Angular CLI.
