### ISSUE TITLE
browser-esbuild does not support ".less" files. 

### ISSUE THREAD

**Issue by dmitryya-tr** [angular/angular-cli#25214]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when trying to migrate project that uses less as styles receiving an error 

there is currently no way to configure custom loader and no build in loader for this.  

### Minimal Reproduction

create project that uses less as style, replace builder to "@angular-devkit/build-angular:browser-esbuild". run ng build

### Exception or Error

```text
[ERROR] [plugin angular-compiler] No loader is configured for ".less" files.
```

### Your Environment

```text
Angular CLI: 14.2.6
Node: 16.13.0
Package Manager: npm 8.1.2 
OS: darwin x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.6 (cli-only)
@angular-devkit/core         14.2.6 (cli-only)
@angular-devkit/schematics   14.2.6 (cli-only)
@schematics/angular          14.2.6 (cli-only)
```

**Comment by alan-agius4** [comment]
Less support was added in version 16.
