### ISSUE TITLE
`ng new` adds unused `@angular/` dependencies

### ISSUE THREAD

**Issue by ampmonteiro** [angular/angular-cli#25219]
### Command

new

### Description

When is asked router and the answer is No.

Why the package is installed anyway?

### Describe the solution you'd like

The package should not be installed.
Which means should not be in package.json.

This also  related to #50305, because if you install Angular using npx, will take some time.

With this change will improve installation and setup time.

Of course if later on , the user change their mind, should exist a command to install and setup the router.
And this indication should be in the docs.

**Comment by alan-agius4** [comment]
If done, this sound be done in a major version since this will invalidate some education materials. 

That said, the benefits are very minimal as the installation time is not really relevant for this change.

**Comment by alan-agius4** [comment]
From https://github.com/angular/angular-cli/issues/25220, there are also a number of packages which are not used by default like `@angular/animation` and `@angular/forms` which we want want to consider not adding as a dependency by default.

**Comment by ampmonteiro** [comment]
> If done, this should be done in a major version since this will invalidate some education materials.
> 
> That said, the benefits are very minimal as the installation time is not really relevant for this change.

If you join router with animations and forms,  this will have impact on installation and maybe later on the build.

About education material, i dont think so because for example in router, it would only need to indicate a command to install and include router module.

Beside you also already do this when you use Angular material, you indicate that you  need animations module.


> From #25220, there are also a number of packages which are not used by default like `@angular/animation` and `@angular/forms` which we want want to consider not adding as a dependency by default.
> 
 recommend to combined with #25220 

> That said, I can also see that this can degraded DX for new users as they would need to install a number of packages when they need to user certain features.

To be honest i dont think so. You can see that other frameworks do the same or worst ( they need external deeps)

And this can  alleviate  the learning curve.

And i think Angular should adopt more  the mentality of an progressive framework, just install and use what you need.

**Comment by sod** [comment]
same with sass and everything else that cli supports. You can choose "css" but sass still works. Basically all of it thanks to https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/package.json#L9-L71

**Comment by sod** [comment]
If you remove typescript from the equasion (which is honking 40 mb in node_modules), then

`npm create vite@latest my-vue-app` adds 30mb of dependencies and
`ng new foo-bar` adds 480mb of dependencies

IMO there is room for healthy competition.

**Comment by dgp1130** [comment]
> With this change will improve installation and setup time.

> `npm create vite@latest my-vue-app` adds 30mb of dependencies and `ng new foo-bar` adds 480mb of dependencies

To be clear, if install weight and time are the main concerns, removing router, forms, or animations likely won't have a significant impact. I don't believe any of those introduce any significant amount of additional dependencies, so you're only saving the sizes of those individual packages, which is pretty minimal.

Most of an Angular application's weight is in its tooling, Webpack and that ecosystem in particular. One approach we're hoping to explore is only installing esbuild / Vite by default, where Webpack is an optional dependency which won't be included in new Angular apps by default. That would likely have a significant impact on install weight. Removing one Webpack allows NPM to drop a huge amount of transitive dependencies underneath it, which would add up to significantly larger improvement than the few unused `@angular/*` packages.

I think the core trade off here is whether cleaning up these extra packages in `ng new` is worth asking / documenting that users manually install these packages when they need them.

**Comment by alan-agius4** [comment]
Totally agree with @dgp1130.

i think overall the benefit of not installing this dependencies is negligible and that the bulk of the installation time is spent on tooling dependencies.

We should definitely continue investigating and reducing these sort of dependencies.

**Comment by sod** [comment]
found another benefit of leaner dependency graph. Online tools and reproductions like https://stackblitz.com/~/github.com/bjornharvold/ngrx-issue-4149 could load faster when less dependencies have to be installed.
