### ISSUE TITLE
No loader is configured for ".ttf" files

### ISSUE THREAD

**Issue by NatanCoralogix** [angular/angular-cli#25235]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.2.0

### Description

Trying to use esbuild, i get error:

` [ERROR] No loader is configured for ".ttf" files: node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf`

I used to have an `extra-webpack.config.js` file, which has some monaco editor style-loader.
not sure how/where to convert it to esbuild config?
`      {
        test: /\.css$/,
        include: MONACO_DIR,
        use: ["style-loader", {
          "loader": "css-loader",
          "options": {
            "url": false,
          },
        }],
      },`

### Minimal Reproduction

ng serve
see error

### Exception or Error

```text
[ERROR] No loader is configured for ".ttf" files: node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf
```

### Your Environment

```text
Angular CLI: 16.0.1
Node: 16.16.0
Package Manager: npm 8.11.0
OS: darwin arm64

Angular: 16.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1600.1
@angular-devkit/build-angular      16.0.1
@angular-devkit/core               16.0.1
@angular-devkit/schematics         16.0.1
@angular/flex-layout               14.0.0-beta.40
@angular/material                  15.2.9
@angular/material-moment-adapter   15.2.9
@schematics/angular                16.0.1
rxjs                               6.6.7
typescript                         4.9.5
```

**Comment by alan-agius4** [comment]
Monaco Editor is relies on Webpack specific features. 
See: https://github.com/microsoft/monaco-editor/issues/886
