### ISSUE TITLE
Question: Keep static files intact during ng build?

### ISSUE THREAD

**Issue by jtabet** [angular/angular-cli#2523]
Hello,

I have some json configuration files in my project that I use with a simple require, and when I build the project, these files are merged into the generated js files. Is there a way I can keep the distinct json files so I can edit the configs without having to re-build my project?

**Comment by Meligy** [comment]
I think the current supported way is to move these files to `src/assets`. This folder gets copied as-is to `<output-folder>/assets` (usually `dist/assets`).

**Comment by jtabet** [comment]
I was hoping for a better solution but yeah, it works for what I want to do, thanks
