### ISSUE TITLE
Automatically --skip-confirmation when no terminal detected

### ISSUE THREAD

**Issue by grosch-intl** [angular/angular-cli#25249]
### Command

add

### Description

When using git bash for Windows, and trying to do an add, I get this:

> No terminal detected. '--skip-confirmation' can be used to bypass installation confirmation. Ensure package name is correct prior to '--skip-confirmation' option usage.

### Describe the solution you'd like

I'd like a way to set a global config saying if I'm doing an `ng add` and there's no terminal detected, that it just automatically skips confirmation.

**Comment by alan-agius4** [comment]
Thanks for opening this feature request.

However, this feature is not in scope as this will increase the risk of security and DX problems from mistyping package names.

`ng add` similar to `npx` and other tools that require package installation prompt before installing a package.
