### ISSUE TITLE
Tree shaking: unused code remains in productive app

### ISSUE THREAD

**Issue by MrKanister2000** [angular/angular-cli#25287]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Hi,
I tried to upgrade from angular 15 to 16.0.3. The application works fine without the "optimization" flag set to true in the angular.json file. But when set to true, some code remains in the main....js that causes an error, when the page gets loaded.
The console log states "main.bc110eb6fa951c13.js:1 Uncaught ReferenceError: hd is not defined". 
Here is the part of the code, that causes this issue:

`class EP extends hd {
...
}
`

After some investigation (and also turning off the optimization flag), I found out that this code originally looked like that:

`
class ReferenceExpr extends ExpressionBase {
...
}
`

So the ExpressionBase class is missing. Which is also fine, I guess, since it is not used in the code and hence was removed by tree shaking. Also the ReferenceExpr class is, as far as I can tell, not used in the code. When I search for a usage of the class "EP" in the optimised code, there is no location where I could find it. 

Version 15.2.4 worked without any issues. Did I miss anything in the upgrade process, or is it a bug in the build optimisation?

### Please provide the exception or error you saw

```true
main.1dde1c799c90e486.js:1 Uncaught ReferenceError: hd is not defined
    at 83 (main.1dde1c799c90e486.js:1:290279)
    at a (runtime.de42e30e1a22c589.js:1:143)
    at main.1dde1c799c90e486.js:1:4227714
    at n (runtime.de42e30e1a22c589.js:1:951)
    at main.1dde1c799c90e486.js:1:55
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.3
Node: 18.12.1
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 16.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.0.3
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@schematics/angular             16.0.3
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by MrKanister2000** [comment]
I think I found the culprit. There was a legacy import statement `import '@angular/compiler';` in the main.ts file. 
After removing it, the app works fine. Should this still be treated as a bug? Or is anyway bad practice to import the compiler in the main.ts file?

**Comment by alan-agius4** [comment]
You should not be importing `import '@angular/compiler';` directly. The compiler is needed for JIT support and which does not support advanced levels of build-optimisation.

**Comment by MrKanister2000** [comment]
Yes, there was actually some code that used the JIT compiler in an older version of the application. But his feature was removed quite a while ago and removing this import was just forgotten. So I think this issue can be treated as solved :).

**Comment by ptatoChi** [comment]
For me, it was removing these: 

`import { JitCompilerFactory } from "@angular/platform-browser-dynamic";
import { Compiler, CompilerFactory, COMPILER_OPTIONS } from "@angular/core";`

It was used during Angular 4 days. Forgot to remove them
