### ISSUE TITLE
Remove protractor from @angular-devkit/build-angular

### ISSUE THREAD

**Issue by aljaznuncic** [angular/angular-cli#25298]
### Command

other

### Description

Given that protractor is deprecated and contains dependencies that have vulnerabilities (xml2js@0.4.23 and request@2.88.2), it would be good to remove protractor from the @angular-devkit/build-angular package if that's possible. Users that still use protractor can install it separately.

**Comment by alan-agius4** [comment]
Protractor is already an optional peer  dependency.  The builder will eventually be removed once the deprecation period is over and protractor in end of life.

Also, the mentioned vulnerabilities do not effect protractor as it is not intended to be used on production environments were malicious crafted requested / regexp can be done.
