### ISSUE TITLE
Esbuild keep reloading without project changes

### ISSUE THREAD

**Issue by NatanCoralogix** [angular/angular-cli#25316]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

we noticed Esbuild is very "sensitive" and reloading even when no changes where done.
for example, we have playwright tests running and at the end saving a report at the root folder (outside of src).
this report causes reloading, while its not part of the project, and not consumed by any module.

can we limit the detected parts to be only from the "src" folder?

### Minimal Reproduction

ng serve
create or save a file which is outside of the project, and not consumed by any part of the project.
see esbuild reloading

### Your Environment

```text
Angular CLI: 16.0.3
Node: 16.16.0
Package Manager: npm 8.11.0
OS: darwin x64

Angular: 16.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1600.3
@angular-devkit/build-angular      16.0.3
@angular-devkit/core               16.0.3
@angular-devkit/schematics         16.0.3
@angular/cdk                       16.0.1
@angular/flex-layout               14.0.0-beta.40
@angular/material                  15.2.9
@angular/material-moment-adapter   15.2.9
@schematics/angular                16.0.3
rxjs                               6.6.7
typescript                         4.9.5
```

**Comment by JeanMeche** [comment]
Hi, this issue is being tracked at @NatanCoralogix #25197
