### ISSUE TITLE
Error on fs.js path must be a string or Buffer

### ISSUE THREAD

**Issue by andrebaltieri** [angular/angular-cli#2531]
Hi guys, just did a fresh install of my Windows today, installed node (6.7.0) and tried to install angular-cli.
It seems to be installed OK, but got an error every time I try to run any ng <CMD>.

### OS
> Windows 10 Pro with Anniversary Update

### Log
fs.js:640 
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
TypeError: path must be a string or Buffer

Can someone help me on this?

**Comment by fullstackdave** [comment]
Make sure you have Git installed.

https://git-scm.com/downloads

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2178
