### ISSUE TITLE
Is there a way to specify which source maps to create with production build?

### ISSUE THREAD

**Issue by billdwhite** [angular/angular-cli#2533]
Since there is no access to the webpack.config.js (and it's devtool setting)  for angular-cli, is there any way to control which type of sourcemaps are generated in the production build?  I want the production build and compression, etc but I want usable TS sources as well so I can troubleshoot the code once it is deployed.  This that possible?

**Comment by filipesilva** [comment]
I think https://github.com/angular/angular-cli/pull/2519 fixes this.

**Comment by billdwhite** [comment]
I see this is waiting for a sync ("This branch is out-of-date with the base branch").  Any ETA on that?

**Comment by tomwanzek** [comment]
@filipesilva Just to clarify, are TS sourcemaps for `prod` build always enabled now? Or is there a build time command option to control whether source maps are created? Thx, in advance for a brief reply.

**Comment by billdwhite** [comment]
@filipesilva thanks!!

**Comment by filipesilva** [comment]
@tomwanzek always. That was the original intention but we forgot to correctly configure `UglifyJsPlugin`.

**Comment by maxailloud** [comment]
@filipesilva And if we don't want map files in prod is it possible to not have them?
Because if I want to deploy my website having a map file of like 10Mo is a bit too heavy, and as I don't need them. I would need them but not for my prod build, so maybe a parameter to configure it can be good.
Just tell me if it's possible/planned or not and I will deal with it.

**Comment by filipesilva** [comment]
@maxailloud not something that's specifically planned atm. Although to be honest there have been a fair number of these requests to further customise minor aspects of builds, so probably in the future we'll just have way more flags there.

For now though, I wouldn't expect it soon as there are way bigger fish to fry. In your specific case I'd make the file copy script ignore/delete the map files when deploying, there should be no problem.

**Comment by maxailloud** [comment]
@filipesilva Yeah sure I can definitley understand that there is more important stuff to do.
Yeah i will just delete the map file.

Thank you for your answer.

**Comment by Avien** [comment]
I also want an option to build without source maps, seems basic

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/3113
