### ISSUE TITLE
Installing the CLI within 30-60 seconds after its publication to npm causes error

### ISSUE THREAD

**Issue by Rutgerdj** [angular/angular-cli#25331]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I tried to install the `@angular/cli` package but got the following error:

```
2023-06-07T11:16:34.5123669Z npm ERR! code ETARGET
2023-06-07T11:16:34.5135901Z npm ERR! notarget No matching version found for @angular-devkit/core@16.0.5.
2023-06-07T11:16:34.5136229Z npm ERR! notarget In most cases you or one of your dependencies are requesting
2023-06-07T11:16:34.5136537Z npm ERR! notarget a package version that doesn't exist.
2023-06-07T11:16:34.5151588Z 
```

The npm cli was trying to install `@angular/cli` version `16.0.5` which has `@angular-devkit/core` version `16.0.5` as a dependency. 
The problem was that the `@angular-devkit/core` package was not published yet. 

While investigating I found out that there was a 60 second window where this could happen. 

Below is a table of publish times for both packages. You can see that the `@angular-devkit/core` package is usually published 30-60 seconds later than the cli package.

| Version         | CLI publish time     | devkit/core publish time | difference
|--------------|-----------|------------|--------|
| 16.0.0 | 2023-05-03T17:54:18.493Z | 2023-05-03T17:54:49.718Z | 31.2s |
| 16.0.1 | 2023-05-10T20:07:10.642Z | 2023-05-10T20:07:56.296Z | 45.7s |
| 16.0.2 | 2023-05-17T12:28:41.824Z | 2023-05-17T12:29:24.033Z | 42.2s |
| 16.0.3 | 2023-05-25T19:33:23.528Z | 2023-05-25T19:33:51.414Z | 27.9s |
| 16.0.4 | 2023-06-01T14:14:35.093Z | 2023-06-01T14:15:39.485Z | 64.4s |
| 16.0.5 | 2023-06-07T11:15:44.494Z | 2023-06-07T11:16:44.925Z | 60.4s |

publish times are acquired using the `npm show` command:
* `npm show @angular-devkit/core time --json`
* `npm show @angular/cli time --json`

### Minimal Reproduction

Run `npm install -g @angular/cli` within 30-60 seconds after a new package has been published.

### Exception or Error

```text
2023-06-07T11:16:34.5123669Z npm ERR! code ETARGET
2023-06-07T11:16:34.5135901Z npm ERR! notarget No matching version found for @angular-devkit/core@16.0.5.
2023-06-07T11:16:34.5136229Z npm ERR! notarget In most cases you or one of your dependencies are requesting
2023-06-07T11:16:34.5136537Z npm ERR! notarget a package version that doesn't exist.
2023-06-07T11:16:34.5151588Z
```

### Your Environment

```text
This is not relevant (ng was not installed yet)
```

**Comment by alan-agius4** [comment]
Hey @Rutgerdj,

Thanks for opening the issue.

There are a number of packages which we need to publish and 60s does seem a decent time for the publish to be performed and propagated on NPM. 

We could technically publish the packages without tagging them as latest and tag them all together at the end of the publishing process. 

However, following a convo @devversion we do feel that this adds unnecessary completely and this ~60s of mismatching tags is acceptable.
