### ISSUE TITLE
SassError after upgrading from v14 to v15

### ISSUE THREAD

**Issue by cabinwj** [angular/angular-cli#25357]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

<img width="2054" alt="image" src="https://github.com/angular/angular-cli/assets/2739730/89da1683-f21b-4451-ac12-7f40105e2675">
<img width="943" alt="image" src="https://github.com/angular/angular-cli/assets/2739730/e050bd82-f2e7-41b1-a7c5-eb374354c1c0">
<img width="429" alt="image" src="https://github.com/angular/angular-cli/assets/2739730/eefc2a7b-1191-4650-8859-19c04bdb27f5">

### Minimal Reproduction

npm install
ng cache clean && ng serve --port 7000

### Your Environment

```text
Angular CLI: 15.2.8
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

`xm-register-theme` is a SASS mixin not provided by Angular itself, likely a dependency. You are passing a SASS map where it appears that only a CSS color is expected.
