### ISSUE TITLE
Have angular project after making couple changes it starts spinning recompilation

### ISSUE THREAD

**Issue by DimitriLib** [angular/angular-cli#25358]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

Created  simple project. Included in angular.json assets that points to package in node-modules directory, to copy assets.
            "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "./node_modules/tinymce",
                "output": "/tinymce/"
              }
Restarted ng serve my-app.
After making couple changes, random changes really. Application start recompiling non stop.
 

### Please provide a link to a minimal reproduction of the bug

https://github.com/DimitriLib/angular-test

### Please provide the exception or error you saw

```true
√ Compiled successfully.
√ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2023-06-11T05:41:42.190Z - Hash: 2ca09f110fc834bc - Time: 138ms

√ Compiled successfully.
√ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2023-06-11T05:41:42.375Z - Hash: 2ca09f110fc834bc - Time: 125ms

√ Compiled successfully.
√ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2023-06-11T05:41:42.564Z - Hash: 2ca09f110fc834bc - Time: 138ms
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8                                        
Node: 18.12.1                                              
Package Manager: npm 8.19.2                                
OS: win32 x64                                              
                                                           
Angular: 15.2.9                                            
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     
                                                           
Package                         Version                    
---------------------------------------------------------  
@angular-devkit/architect       0.1502.8                   
@angular-devkit/build-angular   15.2.8                     
@angular-devkit/core            15.2.8                     
@angular-devkit/schematics      15.2.8                     
@angular/cli                    15.2.8                     
@schematics/angular             15.2.8                     
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by DimitriLib** [comment]
Hello,
Can you please provide update on this issue? 
Thank you

**Comment by uganjha** [comment]
Can anyone look into this? I am also facing this issue where it auto reload multiple times. It will be really helpful if someone can provide how we can debug this to check which file changes it is detecting before rebuilding again.

**Comment by alan-agius4** [comment]
You, can you use `—verbose` which among the output will also contain the file that changes and triggered the rebuild.

**Comment by DimitriLib** [comment]
@alan-agius4 It seems there is an issue with assets properties in angular.json and glob that exists in node-modules. 
          {
            "glob": "**/*",
            "input": "./node_modules/tinymce",
            "output": "/tinymce/"
          }
If remove that, it is not recompiling anymore. 

Please provide solution.

Thank you

**Comment by DimitriLib** [comment]
@alan-agius4 Can repo please get checked and possible finding root cause? We are loosing a lot of productivity because of recompile issue.

**Comment by alan-agius4** [comment]
I was not able to reproduce the reported behaviour using the reproduction provided. I suggest to run the build in verbose mode to check which file is causing the rebuild. 

Also if you are using an anti-virus try to disable it.

**Comment by DimitriLib** [comment]
@alan-agius4 
thank you for reply.
Here is the output from verbose:


LOG from angular.watch-files-logs-plugin
    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\src\app\app.component.ts

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

    Modified files:
    C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce

LOG from webpack.Compiler
<t> make hook: 102.239 ms
<t> finish make hook: 0.0083 ms
<t> finish compilation: 5.9535 ms
<t> seal compilation: 60.1301 ms
<t> afterCompile hook: 0.0175 ms
<t> emitAssets: 20.0784 ms
<t> emitRecords: 0.0099 ms

LOG from webpack.Compilation
<t> compute affected modules: 0.0035 ms
<t> finish modules: 3.6559 ms
<t> report dependency errors and warnings: 2.267 ms
<t> optimize dependencies: 1.0768 ms
<t> create chunks: 1.1463 ms
<t> compute affected modules with chunk graph: 0.002 ms
<t> optimize: 1.502 ms
    79 modules hashed, 0 from cache (0.31 variants per module in average)
<t> module hashing: 1.07 ms
    0% code generated (0 generated, 79 from cache)
<t> code generation: 0.4313 ms
<t> runtime requirements.modules: 0.0907 ms
<t> runtime requirements.chunks: 0.062 ms
<t> runtime requirements.entries: 0.2229 ms
<t> runtime requirements: 0.4376 ms
<t> hashing: initialize hash: 0.002 ms
<t> hashing: sort chunks: 0.0153 ms
<t> hashing: hash runtime modules: 0.6419 ms
<t> hashing: hash chunks: 0.2704 ms
<t> hashing: hash digest: 0.0093 ms
<t> hashing: process full hash modules: 0.0357 ms
<t> hashing: 1.0308 ms
    0% code generated (0 generated, 7 from cache)
<t> record hash: 0.0128 ms
<t> module assets: 0.0504 ms
<t> create chunk assets: 0.4508 ms
<t> process assets: 51.7951 ms

LOG from webpack.ResolverCachePlugin
    0% really resolved (0 real resolves with 0 cached but invalid, 45 cached valid, 0 concurrent)

LOG from webpack.FlagDependencyExportsPlugin
<t> restore cached provided exports: 1.5638 ms
<t> figure out provided exports: 1.588 ms
    1% of exports of modules have been determined (8 no declared exports, 3 not cached, 0 flagged uncacheable, 245 from cache, 0 from mem cache, 0 additional calculations due to dependencies)
<t> store provided exports into cache: 0.0094 ms

LOG from webpack.SideEffectsFlagPlugin
<t> update dependencies: 0.9695 ms

LOG from webpack.buildChunkGraph
<t> visitModules: prepare: 0.2398 ms
<t> visitModules: visiting: 0.7069 ms
    284 queue items processed (119 blocks)
    0 chunk groups connected
    0 chunk groups processed for merging (0 module sets, 0 forked, 0 + 0 modules forked, 0 + 0 modules merged into fork, 0 resulting modules)
    0 chunk group info updated (0 already connected chunk groups reconnected)
<t> visitModules: 0.743 ms
<t> connectChunkGroups: 0.0074 ms
<t> cleanup: 0.0022 ms

LOG from webpack.SplitChunksPlugin
<t> prepare: 0.0093 ms
<t> modules: 0.3752 ms
<t> queue: 0.058 ms
<t> maxSize: 0.002 ms

LOG from copy-webpack-plugin
    starting to add additional assets...
    starting to process a pattern from 'favicon.ico' using 'C:/Users/dimitri.liberman/angular-test/my-app/src/' context
    starting to process a pattern from '**\*' using 'C:/Users/dimitri.liberman/angular-test/my-app/src/assets/' context
    starting to process a pattern from '**\*' using 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/' context
    begin globbing 'C:/Users/dimitri.liberman/angular-test/my-app/src/favicon.ico'...
    begin globbing 'C:/Users/dimitri.liberman/angular-test/my-app/src/assets/**/*'...
    begin globbing 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/**/*'...
    'to' option '.' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/src/favicon.ico' should write to 'favicon.ico'
    finished to process a pattern from 'favicon.ico' using 'C:\Users\dimitri.liberman\angular-test\my-app\src' context
    finished to process a pattern from '**\*' using 'C:/Users/dimitri.liberman/angular-test/my-app/src/assets/' context to 'assets/'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/bower.json' should write to 'tinymce\bower.json'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/CHANGELOG.md' should write to 'tinymce\CHANGELOG.md'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/composer.json' should write to 'tinymce\composer.json'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/jquery.tinymce.js' should write to 'tinymce\jquery.tinymce.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/jquery.tinymce.min.js' should write to 'tinymce\jquery.tinymce.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/license.txt' should write to 'tinymce\license.txt'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/package.json' should write to 'tinymce\package.json'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/README.md' should write to 'tinymce\README.md'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/tinymce.d.ts' should write to 'tinymce\tinymce.d.ts'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/tinymce.js' should write to 'tinymce\tinymce.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/tinymce.min.js' should write to 'tinymce\tinymce.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/icons/default/icons.js' should write to 'tinymce\icons\default\icons.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/icons/default/icons.min.js' should write to 'tinymce\icons\default\icons.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/icons/default/index.js' should write to 'tinymce\icons\default\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/advlist/index.js' should write to 'tinymce\plugins\advlist\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/advlist/plugin.js' should write to 'tinymce\plugins\advlist\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/advlist/plugin.min.js' should write to 'tinymce\plugins\advlist\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autolink/index.js' should write to 'tinymce\plugins\autolink\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autolink/plugin.js' should write to 'tinymce\plugins\autolink\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autolink/plugin.min.js' should write to 'tinymce\plugins\autolink\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/anchor/index.js' should write to 'tinymce\plugins\anchor\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/anchor/plugin.js' should write to 'tinymce\plugins\anchor\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/anchor/plugin.min.js' should write to 'tinymce\plugins\anchor\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autoresize/index.js' should write to 'tinymce\plugins\autoresize\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autoresize/plugin.js' should write to 'tinymce\plugins\autoresize\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autoresize/plugin.min.js' should write to 'tinymce\plugins\autoresize\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autosave/index.js' should write to 'tinymce\plugins\autosave\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autosave/plugin.js' should write to 'tinymce\plugins\autosave\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/autosave/plugin.min.js' should write to 'tinymce\plugins\autosave\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/code/index.js' should write to 'tinymce\plugins\code\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/code/plugin.js' should write to 'tinymce\plugins\code\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/code/plugin.min.js' should write to 'tinymce\plugins\code\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/bbcode/index.js' should write to 'tinymce\plugins\bbcode\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/bbcode/plugin.js' should write to 'tinymce\plugins\bbcode\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/bbcode/plugin.min.js' should write to 'tinymce\plugins\bbcode\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/charmap/index.js' should write to 'tinymce\plugins\charmap\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/charmap/plugin.js' should write to 'tinymce\plugins\charmap\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/charmap/plugin.min.js' should write to 'tinymce\plugins\charmap\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/colorpicker/index.js' should write to 'tinymce\plugins\colorpicker\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/colorpicker/plugin.js' should write to 'tinymce\plugins\colorpicker\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/colorpicker/plugin.min.js' should write to 'tinymce\plugins\colorpicker\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/emoticons/index.js' should write to 'tinymce\plugins\emoticons\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/emoticons/plugin.js' should write to 'tinymce\plugins\emoticons\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/emoticons/plugin.min.js' should write to 'tinymce\plugins\emoticons\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/contextmenu/index.js' should write to 'tinymce\plugins\contextmenu\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/contextmenu/plugin.js' should write to 'tinymce\plugins\contextmenu\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/contextmenu/plugin.min.js' should write to 'tinymce\plugins\contextmenu\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/fullpage/index.js' should write to 'tinymce\plugins\fullpage\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/fullpage/plugin.js' should write to 'tinymce\plugins\fullpage\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/fullpage/plugin.min.js' should write to 'tinymce\plugins\fullpage\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/codesample/index.js' should write to 'tinymce\plugins\codesample\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/codesample/plugin.js' should write to 'tinymce\plugins\codesample\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/codesample/plugin.min.js' should write to 'tinymce\plugins\codesample\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/directionality/index.js' should write to 'tinymce\plugins\directionality\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/directionality/plugin.js' should write to 'tinymce\plugins\directionality\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/directionality/plugin.min.js' should write to 'tinymce\plugins\directionality\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/help/index.js' should write to 'tinymce\plugins\help\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/help/plugin.js' should write to 'tinymce\plugins\help\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/help/plugin.min.js' should write to 'tinymce\plugins\help\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/fullscreen/index.js' should write to 'tinymce\plugins\fullscreen\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/fullscreen/plugin.js' should write to 'tinymce\plugins\fullscreen\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/fullscreen/plugin.min.js' should write to 'tinymce\plugins\fullscreen\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/imagetools/index.js' should write to 'tinymce\plugins\imagetools\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/imagetools/plugin.js' should write to 'tinymce\plugins\imagetools\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/imagetools/plugin.min.js' should write to 'tinymce\plugins\imagetools\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/hr/index.js' should write to 'tinymce\plugins\hr\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/hr/plugin.js' should write to 'tinymce\plugins\hr\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/hr/plugin.min.js' should write to 'tinymce\plugins\hr\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/importcss/index.js' should write to 'tinymce\plugins\importcss\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/importcss/plugin.js' should write to 'tinymce\plugins\importcss\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/importcss/plugin.min.js' should write to 'tinymce\plugins\importcss\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/insertdatetime/index.js' should write to 'tinymce\plugins\insertdatetime\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/insertdatetime/plugin.js' should write to 'tinymce\plugins\insertdatetime\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/insertdatetime/plugin.min.js' should write to 'tinymce\plugins\insertdatetime\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/image/index.js' should write to 'tinymce\plugins\image\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/image/plugin.js' should write to 'tinymce\plugins\image\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/image/plugin.min.js' should write to 'tinymce\plugins\image\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/lists/index.js' should write to 'tinymce\plugins\lists\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/lists/plugin.js' should write to 'tinymce\plugins\lists\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/lists/plugin.min.js' should write to 'tinymce\plugins\lists\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/legacyoutput/index.js' should write to 'tinymce\plugins\legacyoutput\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/legacyoutput/plugin.js' should write to 'tinymce\plugins\legacyoutput\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/legacyoutput/plugin.min.js' should write to 'tinymce\plugins\legacyoutput\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/nonbreaking/index.js' should write to 'tinymce\plugins\nonbreaking\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/nonbreaking/plugin.js' should write to 'tinymce\plugins\nonbreaking\plugin.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/nonbreaking/plugin.min.js' should write to 'tinymce\plugins\nonbreaking\plugin.min.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/link/index.js' should write to 'tinymce\plugins\link\index.js'
    'to' option 'tinymce\' determinated as 'dir'
    determined that 'C:/Users/dimitri.liberman/angular-test/my-app/node_modules/tinymce/plugins/link/plugin.js' should write to 'tinymce\plugins\link\plugin.js'

**Comment by alan-agius4** [comment]
This does not appear to be an issue with the Angular CLI.

In this case the rebuild does seem genuine as there is something that is causing `C:\Users\dimitri.liberman\angular-test\my-app\node_modules\tinymce` to be modified/touched. Since you are using Windows, you can use [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) to determine which process is causing the file to be modified, I would suspect that this is an Anti-virus or something of that sort.

**Comment by DimitriLib** [comment]
@alan-agius4 Installed procmon. This is what i am seeing when capturing with procmon.
What exactly i am looking for here?

![image](https://github.com/angular/angular-cli/assets/66094347/83879616-1755-4e00-a6a9-44f432004a14)

**Comment by DimitriLib** [comment]
@alan-agius4 
hi Alan, do you think we can debug together through teams or something to get to the bottom of this issue?
Thank you

**Comment by alan-agius4** [comment]
Sorry for my late reply but I have been out on vacation.

This issue does not seem to be caused by the Angular CLI, as we were not able to reply this on Windows and Linux. Also, I would expect other users reporting the same issue it there was a bug in the watcher. 

Therefore, it seems that something within the environment is cause files to be touched, this can either be a setting in your editor or more commonly an anti-virus. I therefore, suggest that for starts you try to disable such software and see if the problem persist.
