### ISSUE TITLE
enable esbuild for SSR

### ISSUE THREAD

**Issue by its-dibo** [angular/angular-cli#25361]
### Command

build

### Description

we can use `@angular-devkit/build-angular:browser-esbuild` but cannot use `@angular-devkit/build-angular:server-esbuild`

error:
```
Cannot find builder "@angular-devkit/build-angular:server-esbuild"
```

**Comment by alan-agius4** [comment]
Thanks for this feature request. This is currently in the roadmap and will be available in an upcoming minor version within the v16 timeframe.

**Comment by its-dibo** [comment]
wow, great news
