### ISSUE TITLE
Jest compile out folder is not cleared between runs

### ISSUE THREAD

**Issue by gultyayev** [angular/angular-cli#25370]
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

With Jest enabled for the tests the CLI does not clear the `dist` folder from test output. This leads to "failed" tests that could be non-existent till that time or similar.

### Minimal Reproduction

Create a service. Have something injected in this service. Convert the test from TestBed to a regular TS with manual instantiation. Don't provide the injected service. Run the tests `ng test`. The test for the service should fail. Remove the test file from the filesystem. Run tests again. Notice how it persists in the test results.

### Your Environment

```text
Angular CLI and other packages 16.0.1
```

**Comment by alan-agius4** [comment]
Same root cause as  https://github.com/angular/angular-cli/issues/25308
