### ISSUE TITLE
Gulp support

### ISSUE THREAD

**Issue by psanchez1982** [angular/angular-cli#2539]
It would be useful the possibility to call ng commands vía gulp

### OS
Any

### Versions.
angular-cli: 1.0.0-beta.16
node: 6.7.0:

### Repro steps.
I had created a gulp file and invoked bower packages

### The log given by the failure.
This is not a failure. Is a feature

### Mention any other details that might be useful.

gulp is a defacto standard for automating things, so a gulp plugin could be things easier :-)

**Comment by RoopeHakulinen** [comment]
I've used Gulp for years, but my personal impression is that people are walking away from it nowadays in favor of things like npm scripts. For that reason I doubt there is going to be a plugin for Gulp. Also, you can use it with something like [gulp-exec](https://www.npmjs.com/package/gulp-exec).

**Comment by filipesilva** [comment]
Can't say we're looking to add such a thing. You can still use gulp of course, and just include calls to `ng` commands there.
