### ISSUE TITLE
esbuild dev server thowing error

### ISSUE THREAD

**Issue by gmfun** [angular/angular-cli#25392]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16.0.1

### Description

`Uncaught SyntaxError: The requested module '/.angular/cache/16.1.0/vite/deps/@angular_core.js?v=73a37d0a' does not provide an export named 'Signal'`

I am seeing the above error when running `ng serve` with esbuild

### Minimal Reproduction

- Create a new standalone app using nx (application should be inside apps directory)
- Add `someSignal: Signal<any> = signal('123')` in `app.component.ts`
- switch to esbuild

### Your Environment

```text
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cdk                    16.0.3
@angular/cli                    16.1.0
@schematics/angular             16.0.5
ng-packagr                      16.0.1
rxjs                            7.8.1
typescript                      5.0.4
```

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/25394
