### ISSUE TITLE
ng serve error

### ISSUE THREAD

**Issue by karjac14** [angular/angular-cli#254]
When I do `npm install -g angular-cli` I get the warning below, and `ng serve` is not working also.

````
$ npm install -g angular-cli
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash-node@2.4.1: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated lodash-node@3.10.2: This package has been discontinued in favor of lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng
/usr/local/lib
└── angular-cli@0.0.24
````
````
ng new test3
// all ok...
````
`ng build`
`ng serve`
````
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49153
Could not serve on http://localhost:4200. It is either in use or you do not have permission.
````

how should I properly update graceful and lodash? im doing `npm install lodash -g` and `npm install graceful-fs -g` succesfully. but the error above kees saying i have old versions

Thanks!

**Comment by jkuri** [comment]
Hi. Are you already running something on port 4200? If not try using some higher port: `ng serve --port 10000` for example. 
About warnings when installing `angular-cli`; just ignore them. It means that some `angular-cli` dependencies are using deprecated versions of packages.

**Comment by karjac14** [comment]
Thanks for the info. It lead me to find the fault. Had to enter `sudo ng serve` because of some permission error.

without the `sudo`, i get this:
````
Error: EACCES: permission denied, open '/Users/macbookuser/.config/configstore/ember-cli.json'
You don't have access to this file.
````

**Comment by imtiaz-emu** [comment]
@karjac14, did you managed to solved the problem? How to change the permission? I'm getting the same error without using `sudo`.
