### ISSUE TITLE
Object with a property called 'version' causes problems in testing

### ISSUE THREAD

**Issue by LMFinney** [angular/angular-cli#2540]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
Windows 7

### Versions.
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: win32 x64

### Repro steps.

- Create a new CLI project from scratch.
- Add the following to app.component.ts:
```typescript
  constructor() {
    console.log('Handle1', {id: 123, version: 4});
    console.log('Handle2', {id: 123, verion: 4});
  }
```
- run `ng test`
- You'll see that the second console logging statement prints, but the first doesn't.

### The log given by the failure.
No logging - that's the problem.

### Mention any other details that might be useful.
The original manifestation of this problem was that I put an object that looks like one of the objects above in an Immutable.js List, but then almost all of the methods on the List failed (i.e. `console.log(list.toArray())` never printed). Eventually, I was able to reproduce it in the simpler form that seemingly just the word "version" as a property name caused problems.

This has happened on two machines, one using the chrome launcher and one using the firefox launcher. I don't see the problem by trying to log a similar object literal in the node REPL, the Chrome console, or the Firefox console. 

I don't have the problem running the application in the browser - just in the karma test.

**Comment by RoopeHakulinen** [comment]
I don't think this is an issue with Angular CLI. Angular CLI will simply trigger the Karma and this error is even reproducible without usage of `ng test` using plain Karma. Please report this to the Karma if there isn't an issue about it yet.

**Comment by RoopeHakulinen** [comment]
@LMFinney Seems that it was my mistake. I ran the tests again, and now it produces the same result for me. So you are right and this seems like a legit problem. I'll take a look at what happens on the execution.

**Comment by LMFinney** [comment]
Thanks!

**Comment by filipesilva** [comment]
Whoa that's weird. I just tried it with the console logs outside of the constructor, just in `src/app/app.component.ts`, and could repro on `ng test` (but not on `ng serve`).

**Comment by filipesilva** [comment]
Even weirder... those console.log appear on the karma debugger:
![image](https://cloud.githubusercontent.com/assets/4172079/19234075/46e98394-8ee1-11e6-8ee8-67f0afe5d74c.png)
