### ISSUE TITLE
Runtime error with some projects since Angular CLI 16.1.0 when using esbuild.

### ISSUE THREAD

**Issue by wartab** [angular/angular-cli#25404]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.0.6

### Description

When runnning `ng serve` and then opening the project in the browser, the application fails to load printing errors in console.

This only happens with Angular CLI 16.1.0 in combination with esbuild. When using Angular CLI 16.0.6 with esbuild or Angular CLI 16.1.0 without esbuild, this error does not happen.

### Minimal Reproduction

The error is hard to reproduce, but I have an extract of our project in a Github repository where the error occurs. Unfortunately, I can't share it publicly, but can provide it privately if needed (I'm wartab in the Angular Discord if you need to contact me).

### Exception or Error

```text
template.html:26 NG0304: 'router-outlet' is not a known element (used in the '_a48' component template):
1. If 'router-outlet' is an Angular component, then verify that it is a part of an @NgModule where this component is declared.
2. If 'router-outlet' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
   template.html:1 NG0303: Can't bind to 'ngIf' since it isn't a known property of 'ng-container' (used in the '_a48' component template).
   If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is a part of an @NgModule where this component is declared.
```
```


### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.1.0
Node: 18.16.0
Package Manager: npm 9.6.4
OS: win32 x64

Angular: 16.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@schematics/angular             16.1.0
rxjs                            7.8.1
typescript                      5.1.3
```

**Comment by wartab** [comment]
Note that this seems related to 
https://github.com/angular/angular-cli/issues/25393

**Comment by clydin** [comment]
Can you try your project with the recently released 16.1.1 of the CLI and specifically `@angular-devkit/build-angular`?

If the version update does not resolve the issue can you also try with the cache off (`ng cache off`)?

**Comment by wartab** [comment]
It does not work with the new version. `ng cache off` doesn't help either. 

That said, I'm not sure if `ng cache off` works or what it actually does, but the .angular/cache directory is still being created after turning it off and filled with the same files and the same content.

**Comment by alan-agius4** [comment]
@wartab, can you confirm that you updated to `16.1.1`?

**Comment by wartab** [comment]
Yes, I did. Several times, even deleting node_modules and package-lock.json to make sure.

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by wartab** [comment]
I haven't been able to determine what causes it in our project. I have uploaded a private stripped down copy of the project on Github that still causes the problem. But I can unfortunately not share the project publicly. Is there a way to share it with you privately? I am currently in the Angular Discord if that helps communicate.

**Comment by wartab** [comment]
Yes, that was it. I can also confirm that applying your patch fixes the issue for us.
