### ISSUE TITLE
Build error with library dependency

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#25403]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.0.4

### Description

We're developing a library package that is locally hosted in a test app.
Building the library works. However, while running `build` on the app, we're getting:

` Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/tools/babel/webpack-loader.js):  `column` must be greater than or equal to 0 (columns start`

This is a regression from previous version.

### Minimal Reproduction

Not sure where the issue here.

### Your Environment

```text
Angular CLI: 16.1.0
Node: 18.16.0
Package Manager: npm 9.6.6
OS: win32 x64

Angular: 16.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.0
@angular-devkit/build-angular   16.1.0
@angular-devkit/core            16.1.0
@angular-devkit/schematics      16.1.0
@angular/cli                    16.1.0
@nguniversal/express-engine     16.1.0
@schematics/angular             16.1.0
ng-packagr                      16.1.0
rxjs                            7.8.1
typescript                      5.1.3
webpack                         5.87.0
```

### Anything else relevant?

Thanks

**Comment by zehavibarak** [comment]
> ng build my-library

OK!

> ng build

Generating browser application bundles...
Browser application bundle generation complete.

ERROR!

**Comment by zehavibarak** [comment]
I'm not using i18n, not intentionally.

**Comment by zehavibarak** [comment]
> Duplicate of #25414

This may not be that. Unable to compile still on @angular/compiler-cli@16.1.3

**Comment by zehavibarak** [comment]
@alan-agius4 please keep this issue open.

**Comment by alan-agius4** [comment]
This does look like https://github.com/angular/angular-cli/issues/25414 which is still open.

If you believe it’s not, kindly provide a minimal reproduction that we can take a look at, as it is currently missing from this issue which makes this in actionable.

**Comment by zehavibarak** [comment]
@alan-agius4 per repro above, please leave this open.

**Comment by alan-agius4** [comment]
Let’s keep tracking this in https://github.com/angular/angular-cli/issues/25414 as it’s the same root cause.
