### ISSUE TITLE
Operation Not Permitted

### ISSUE THREAD

**Issue by jezguitarist30** [angular/angular-cli#2541]
After I use ng build once and deploy my app in a dev server then did some modification locally and tried to run ng build again before updating my dev environment I got the error below.

EPERM: operation not permitted, lstat 'e:\Office Works\Wise Education Group\Projects\wise-student-portal\dist'

**Comment by RoopeHakulinen** [comment]
It seems that you are lacking the permissions required to the folder you trying to use. Since you have already ran `ng build` once successfully it seems that you don't have right to delete the existing files from that directory. Please check that you have access to that folder.

**Comment by filipesilva** [comment]
@RoopeHakulinen is right, this seems like an access thing.
