### ISSUE TITLE
ng serve method ip not open in another machines

### ISSUE THREAD

**Issue by gsivaprabu** [angular/angular-cli#2542]
### OS?
> Windows 8 

### Versions.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: linux ia32

After instal angular-cli for below step

##npm install -g angular-cli

##ng new PROJECT_NAME
##cd PROJECT_NAME

After given below command

#ng serve

http://localhost:4200  and http://127.0.0.1:4200 is working on same machine only if i open that machine ip with other machine means not opening. How to open the webpage in another machines, like that machine ip is 10.88.186.126 means how to open this url http://10.88.186.126:4200 in other machines browsers in the N/W.

**Comment by Coksnuss** [comment]
The solution is simple. Just bind to the correct interface address via `ng serve --host=0.0.0.0`

**Comment by gsivaprabu** [comment]
@Coksnuss ,

Hi thanks for your reply any possible way to **set in file for default ip** for run time

**Comment by gsivaprabu** [comment]
@Coksnuss ,

Is building this method but not running in browser

 **ng serve --host 10.0.136.126**

**Comment by Coksnuss** [comment]
Not sure about the run-time setting. Regarding the binding: Bind to `0.0.0.0` (literally).

**Comment by Coksnuss** [comment]
Looks like the default host address cannot be set in any other way.
The default setting (`localhost`) is hardcoded (https://github.com/angular/angular-cli/blob/master/packages/angular-cli/commands/serve.ts#L41) and ember CLI seems not to provide an alternative way to specify arguments (other than by passing it as argument switch) (https://ember-cli.com/api/files/lib_models_command.js.html)

However, you may set the `PORT` environment variable to override the default port 4200

**Comment by gsivaprabu** [comment]
Oh ok we can given manual at build time only correct.

**Comment by fedecordova** [comment]
10.0.136.126 is private ip, use the public ip ;)

**Comment by gsivaprabu** [comment]
@fedecordova private that one is ok how can i access in other machines that is a issue :+1:

**Comment by fedecordova** [comment]
use a digitalocean droplet, like ubuntu

**Comment by pradhyu** [comment]
using following in the package.json makes it accessible to the host machine
ng serve --host  0.0.0.0

**Comment by Tobiaqs** [comment]
In case you get `Invalid Host header`, use `ng serve --host=0.0.0.0 --disable-host-check`

**Comment by abhishekdgeek** [comment]
The option '--disable-host-check' is not registered with the serve command. Run `ng serve --help` for a list of supported options.

I got it working by actually putting my local ip in the host.

`ng serve --host=yourLocalIPHere`

Hope this helps. :)

**Comment by LordAlastair** [comment]
@Coksnuss thank you, I write these lines in the .angular-cli.json file
`  "defaults": {
    "serve": {
      "host": "0.0.0.0",
      "port": 4201
    },`
![image](https://user-images.githubusercontent.com/6444470/32495161-a0b1227e-c3ab-11e7-906c-e9b91b496820.png)
![image](https://user-images.githubusercontent.com/6444470/32495207-db759750-c3ab-11e7-9b29-e0a7915bd805.png)
All fine now XD

**Comment by Coksnuss** [comment]
@LordAlastair Thanks for pointing that out! Very helpful

**Comment by ammaralsayed** [comment]
@abhishekdgeek thank you, this problem drove me crazy
I put my local ip and it finally worked

**Comment by jqp5000** [comment]
If you want to save the effort of adding the --host flag everytime you run your app just add an entry to the 'defaults' prop in the angular-cli.json file like shown below:
.....
  "defaults": {
    "styleExt": "css",
    "component": {},
    "serve": {
      "host": "0.0.0.0",
      "port": 9876
    }

**Comment by holms** [comment]
In Dockerfile:

```
CMD ["ng", "serve", " --host 0.0.0.0", "--port 4201"]
```

```
frontend_1   | The option '--port 4201' is not registered with the serve command. Run `ng serve --help` for a list of supported options.
frontend_1   | ** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
```

Same goes for host is port parameter is not used.

**Comment by Coksnuss** [comment]
> CMD ["ng", "serve", " --host 0.0.0.0", "--port 4201"]

Should be CMD ["ng", "serve", " --host", "0.0.0.0", "--port", "4201"]

Or even Better
ENTRYPOINT ["ng", "serve"]
CMD [" --host", "0.0.0.0", "--port", "4201"]

**Comment by pallapraveen** [comment]
run angular with command -  ng serve --host=0.0.0.0 --disable-host-check
this will disable host check and allow to access with IPAddress

**Comment by Balajishivankar** [comment]
Run angular 4 project with this cmd 
ng serve --host  yourIPaddress 
i.e. ng serve --host 192.168.33.178

**Comment by vnextcoder** [comment]
I get   ``he option '--disable-host-check' is not registered with the serve command. Run `ng serve --help` for a list of supported options.``

**Comment by rizz5091660** [comment]
You guys are superb, i am noob in angular, been looking this answer for few days. Thanks a lot :)

**Comment by wdavilaneto** [comment]
on "serve" put somthing like
 "serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "options": {
                        "host": "0.0.0.0",
                        "browserTarget": "m3front:build",
                        "proxyConfig": "proxy.conf.json"
                    },
                    "configurations": {
                        "production": {
                            "browserTarget": "m3front:build:production"
                        }
                    }
                }
.....
