### ISSUE TITLE
Angular CLI Reference Update

### ISSUE THREAD

**Issue by shammelburg** [angular/angular-cli#2543]
The Angular CLI Reference PDF on [https://cli.angular.io/](https://cli.angular.io/reference.pdf) is great for in-depth information about each command.

Can you update this document with "**ng serve**" and maybe other commands that are available and not in the doc? 

I know the github page has,

**ng serve --host 0.0.0.0 --port 4201 --live-reload-port 49153**

A more informative explanation with would be great.

This tool is absolutely brilliant, thank you guys.

**Comment by arlowhite** [comment]
IMO you should just use the built-in help, though I suppose it's useful for people that don't have **ng** installed and want to see what it can do.

**Comment by filipesilva** [comment]
We're due on updating https://cli.angular.io/, and documentation in general. @Brocco is currently working on it and we aim to have it updated soon-ish.

**Comment by Brocco** [comment]
The documentation efforts are being tracked under #2711. Part of this process will include updating the documentation on cli.angular.io (likely not as a PDF).
