### ISSUE TITLE
'ng' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by SantosAlexandr** [angular/angular-cli#25439]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

node 14.19

### Description

so, im instaling node 14.19 for a work that needs that version, but i cant install angular with him:
c:\Users\'''''''>npm install -g @angular/cli@14
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
C:\Users\santosal\AppData\Roaming\npm\ng -> C:\Users\santosal\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng.js
+ @angular/cli@14
i really need help on this :/

### Minimal Reproduction

i tried to install angular 14.1.3 and it make the same error :/

### Your Environment

```text
'ng' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
