### ISSUE TITLE
ng build breaks when a dependency uses big integer literals (despite target ES2022)

### ISSUE THREAD

**Issue by sandrooco** [angular/angular-cli#25449]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

I do use the [optimization feature](https://angular.io/guide/workspace-config#optimization-configuration) for my production bundles. `architect.build.configurations.production.optimization`

In the latest release of [@arcgis/core](https://www.npmjs.com/package/@arcgis/core) (4.27.x+) some features were built on top of big integer literals. Running `ng serve` or `ng build` (without `"optimization": true`) works properly, but using `optimization` it will throw the error below.

My tsconfig.json has `"module": "esnext"` and ` "target": "ES2022"` which should be fine since big integer literals should be available since es2020. I have no idea where it takes `target environment` from?

### Please provide the exception or error you saw

```true
> Error: Optimization error [node_modules_arcgis_core_chunks_arcgis-knowledge-client-core-simd_js.72e7351a6891d11a.js]: ✘ [ERROR] Big integer literals are not available in the configured target environment ("chrome109.0", "edge112.0", "firefox102.0", "ios12.2", "opera97.0", "safari14.1")

>  node_modules_arcgis_core_chunks_arcgis-knowledge-client-core-simd_js.72e7351a6891d11a.js:968:17:
      968 │       o && (a = (1n << 64n) - 1n), fn(n, {
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.1
Node: 18.12.1
Package Manager: npm 9.4.1
OS: darwin arm64

Angular: 16.1.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.1
@angular-devkit/build-angular   16.1.1
@angular-devkit/core            16.1.1
@angular-devkit/schematics      16.1.1
@angular/cli                    16.1.1
@schematics/angular             16.1.1
rxjs                            7.8.1
typescript                      5.1.3
```

**Comment by JoostK** [comment]
The target browsers are automatically computed from your browserslist configuration, the `target` option in tsconfig is irrelevant.

**Comment by clydin** [comment]
As mentioned, the browsers specified in the browserslist configuration determine the output of the application.  Setting the TypeScript `target` to `ES2022` only ensures that TypeScript does not prematurely downlevel code that may otherwise be viable within the requested browsers. Many browsers support parts of the ES specs and the Angular CLI is setup to granularly downlevel based on individual browser support.

In this case, BigInt support cannot be effectively downleveled due to its behavioral effect on basic operators and the configured browsers for the project includes `ios12.2` which does not have BigInt support (https://caniuse.com/bigint).

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by sandrooco** [comment]
You are absolutely right, thanks for your help.
Maybe it could be added to the docs that it's always from browserslist?

**Comment by alan-agius4** [comment]
It's already in the docs https://angular.io/guide/typescript-configuration#target

**Comment by sandrooco** [comment]
This would make sense to be in [workspace config](https://angular.io/guide/workspace-config#optimization-configuration) too (or at least linked/referenced) since enabling/disabling `optimization` has an impact.
