### ISSUE TITLE
Thanks for opening the issue but this is expected as LESS is not yet supported in the experimental Esbuild builder.

### ISSUE THREAD

**Issue by qyjs** [angular/angular-cli#25452]
Thanks for opening the issue but this is expected as LESS is not yet supported in the experimental Esbuild builder.

Currently only Sass and CSS are supported. Support for Less will be added at a later stage.

_Originally posted by @alan-agius4 in https://github.com/angular/angular-cli/issues/24329#issuecomment-1329018904_

**Comment by alan-agius4** [comment]
LESS is now supported when using the experimental esbuild builder. Please update to the latest version.

**Comment by qyjs** [comment]
> LESS is now supported when using the experimental esbuild builder. Please update to the latest version.

which version

**Comment by alan-agius4** [comment]
Version 16.0.0 and later support LESS
