### ISSUE TITLE
Enable `useBuiltIns` for `@babel/preset-env`?

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#25450]
### Command

build

### Description

Some features seem not downgrade correctly when we target like `Chrome >= 69`, when I add `useBuiltIns: 'usage', corejs: '3'` at:

https://github.com/angular/angular-cli/blob/4cf83eb2cee63547498698a3f16e30c5e25a9338/packages/angular_devkit/build_angular/src/tools/babel/presets/application.ts#L205-L214

there will be no problem any more.

### Describe the solution you'd like

Add `useBuiltIns: 'usage', corejs: '3'` or at least add options support for this usage.

### Describe alternatives you've considered

N/A

**Comment by alan-agius4** [comment]
Angular only officially support the latest 2 versions of Chrome, moreover none of the supporters browsers require polyfills.

Please see: https://angular.io/guide/browser-support for a full list of supported browsers.

**Comment by alan-agius4** [comment]
Yes, you are free to add any polyfills that you need using the `polyfills` option. 

The CLI however does not add polyfills out of the box as these are not needed for any of the officially supported browsers.

That mentioned comment is also in context of the officially supported browsers, and refers to downlevelling of JS syntaxes such as optional chaining, nullish coercing etc…

**Comment by alan-agius4** [comment]
Closing as per above.
