### ISSUE TITLE
- Compiling with Angular sources in Ivy partial compilation mode. ✖ Compiling with Angular sources in Ivy partial compilation mode. Cannot read file xyz.component.html

### ISSUE THREAD

**Issue by anil9030** [angular/angular-cli#25486]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

angular build command is okay for all local libraries of my project except for one.
command i used to build this in jenkins pipeline is ng build xyz-lib
same command worked for all libraries except for one.

error: - Compiling with Angular sources in Ivy partial compilation mode. ✖ Compiling with Angular sources in Ivy partial compilation mode. Cannot read file xyz.component.html

this build is  working fine on local, but failing when implementing through jenkins.

### Minimal Reproduction

ng build xyz-lib

### Exception or Error

```text
- Compiling with Angular sources in Ivy partial compilation mode. ✖ Compiling with Angular sources in Ivy partial compilation mode. Cannot read file xyz.component.html
```

### Your Environment

```text
Your global Angular CLI version (13.3.1) is greater than your local version (13.1.4). The local Angular CLI version is used.
```

**Comment by anil9030** [comment]
FYI i have already added .browserslistrc and included browsers following https://stackoverflow.com/questions/70911458/angular-13-ng-build-library-fails-ivy-partial-compilation-mode

still facing the issue

**Comment by alan-agius4** [comment]
The browserslist in this case does not effect this particular outcome. From the error message it seems that the HTML is missing, can you verify that the file is available?

This seems like a bug but we'll need to look at a reproduction to find and fix the problem. 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. 
If the problem persists, we'd need a reproduction to look into it. Can you setup a minimal repro please? A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by anil9030** [comment]
like i mentioned previously 
Your global Angular CLI version (13.3.1) is greater than your local version (13.1.4). The local Angular CLI version is used.
developer is able to  build this lib locally. (ng build xyz-lib)

there are other files apart from html are
abc.component.html
abc.component.scss
abc.component.ts
abc.ts

this is html file for which jenkins build thrown the error:
projects/xyz-lib/src/lib/components/abc/abc.component.html

<div class="card" id="notification" *ngIf="showForm">
    <div class="card-header">
        <h1 class="h5 mb-0 text-gray-800">Notifications</h1>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col">
                <div class="alert alert-warning mt-1 mb-1" role="alert" *ngIf="contract?.checkWarningMessageCA != ''">
                    {{contract?.checkWarningMessageCA}}
                </div>
                <div class="alert alert-warning mt-1 mb-1" role="alert" *ngIf="contract?.checkWarningMessageOPP != ''">
                    {{contract?.checkWarningMessageOPP}}
                </div>
                <div class="alert mt-1 mb-1" [ngStyle]="{'background-color': contract?.fatcaCompliance.bgcolor }"
                    role="alert" *ngIf="contract?.fatcaCompliance && contract?.fatcaCompliance.msg">
                    {{contract?.fatcaCompliance.msg}}
                </div>
                <div class="alert alert-warning mt-1 mb-1" role="alert"
                    *ngIf="warning?.changePendingIndicators() != ''">
                    <p [innerHTML]="warning?.changePendingIndicators()"></p>
                </div>
                <div class="alert alert-warning mt-1 mb-1" role="alert" *ngIf="warning?.stopActionMessages() != ''">
                    <p [innerHTML]="warning?.stopActionMessages()"></p>
                </div>
                <div class="alert alert-warning mt-1 mb-1" role="alert" *ngIf="warning?.specialTitle() != ''">
                    <p [innerHTML]="warning?.specialTitle()"></p>
                </div>
                <div class="alert alert-warning mt-1 mb-1" role="alert" *ngIf="warning?.warningMessages() != ''">
                    <p [innerHTML]="warning?.warningMessages()"></p>
                </div>
                <div class="alert alert-warning mt-1 mb-1" role="alert" *ngIf="warning?.futureChangeInfo() != ''">
                    <p [innerHTML]="warning?.futureChangeInfo()"></p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col">

                <div *ngFor="let item of errorMsgs" class="alert alert-warning mt-1 mb-1" role="alert">
                    {{item.messageCode}}&emsp;{{item.messageText}}
                </div>

            </div>
        </div>

        <app-pending-transactions [fetchLatest]="fetchPT"></app-pending-transactions>

    </div>
</div>

<div class="card  mt-2" id="inLieu" *ngIf="showForm">
    <div class="card-header">
        <h1 class="h5 mb-0 text-gray-800">Pension to Life</h1>
    </div>
    <div class="card-body" [formGroup]="xyzForm">
        <fieldset class="border p-2">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group row" style="margin: 0.1rem;">
                        <label for="contractId" class="col-sm-6 col-form-label">Old Contract</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="contractId" formControlName="contractId"
                                (change)="toUpper($event)">
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group row " style="margin: 0.1rem;">
                        <label for="surname" class="col-sm-6 col-form-label">Surname</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="surname" formControlName="surname"
                                (change)="toUpper($event)">
                        </div>
                    </div>
                </div>
            </div>
                        more html content

			<div class="card-footer">
            <div class="row mt-2 mb-2">
                <div class="col">
                    <button type="button" class="btn btn-outline-info mr-2" [disabled]="!isAuahOp1ServiceHealthy"
                        (click)="cancel()">Cancel</button>
                    <button type="button" class="btn btn-primary mr-2" (click)="btnClickProcess()"
                        [disabled]="isProcBtnDisabled || readOnlyUser || !isAuahOp1ServiceHealthy">Process</button>
                    <button type="button" class="btn btn-primary mr-2" (click)="btnClickModify()" *ngIf="isRecall"
                        [disabled]="readOnlyUser || !isAuahOp1ServiceHealthy">Modify</button>
                    <button type="button" class="btn btn-danger mr-2" (click)="btnClickDelete()" *ngIf="isRecall"
                        [disabled]="readOnlyUser || isTrnsdeleted || !isAuahOp1ServiceHealthy">Delete</button>

                </div>
            </div>
        </div>
    </div>
</div>

**Comment by alan-agius4** [comment]
Unfortunately without a reproduction it's impossible for us to look into the issue. It is also worth mentioning that you are using a no longer supported version of Angular. See https://angular.io/guide/releases#actively-supported-versions for more info.

I suggest you update to a more recent version and try again. If the problem persists in your library after upgrading, please open a new issue, provide a simple repository reproducing the problem. You can use `ng new repro-app` to create a new project where you reproduce the problem.
