### ISSUE TITLE
@angular/pwa package readme is outdated and has typos

### ISSUE THREAD

**Issue by rkrisztian** [angular/angular-cli#25490]
### Command

doc

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The README at https://www.npmjs.com/package/@angular/pwa (or https://github.com/angular/angular-cli/tree/main/packages/angular/pwa) says:

> for adding [Progress Web App](https://web.dev/progressive-web-apps/) support

it's Progressive. 

> ng add @angular/pwa

I think it's better to match the guide at https://angular.io/guide/service-worker-getting-started , as in my case a project name was required:

```shell
ng add @angular/pwa --project <project-name>
```

For an Angular 14 project, I also had to add a version explicitly:

```none
✔ Found compatible package version: @angular/pwa@0.5.3.
(...)
The package @angular/pwa@0.5.3 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
NOT SUPPORTED: keyword "id", use "$id" for schema ID
```

### Minimal Reproduction

Should not be relevant, this is rather documentation...

### Your Environment

```text
Angular CLI: 14.1.0
Node: 16.20.1
Package Manager: npm 8.19.4 
OS: linux x64

Angular: 14.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1401.0
@angular-devkit/build-angular   14.1.0
@angular-devkit/core            14.1.0
@angular-devkit/schematics      14.1.0
@schematics/angular             14.1.0
rxjs                            7.8.1
typescript                      4.7.4
```

**Comment by HamdaanAliQuatil** [comment]
@alan-agius4 Can I work on this issue? Please assign this to me.

**Comment by alan-agius4** [comment]
@HamdaanAliQuatil, feel free to open a PR.
