### ISSUE TITLE
esbuild: styles.css can't have import of npm (node_modules) style sheets

### ISSUE THREAD

**Issue by jcompagner** [angular/angular-cli#25493]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

none esbuild

### Description

in my styles.css i have:

```
"~@ag-grid-community/styles/ag-grid.css",
"~@ag-grid-community/styles/agGridClassicFont.css",
"~@ag-grid-community/styles/ag-theme-alpine.css",
"~@fortawesome/fontawesome-free/css/all.css",

```

but that is not supported it seems, because i get:

✘ [ERROR] Could not resolve "~@fortawesome/fontawesome-free/css/all.css"

    src/styles.css:8:8:
      8 │ @import "~@fortawesome/fontawesome-free/css/all.css";
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "~@fortawesome/fontawesome-free/css/all.css" as external to exclude it from the bundle, which will remove this error.

also moving it to the angular.json file can only be done by having hard paths into it, which is a bit annoying because we have a nested structure of node_modules (parent,child) and then i always have to be really sure where that one is
so do i need todo 

./node_modules/

or

../node_modules/

it would be way nicer (in styles.clss or angular.json) to really be able to use ~ so the system just resolves it in a node_modules folder for me

### Minimal Reproduction

have styles.css (that is references in angular.json) with ~ urls

and using the esbuild builder.

### Exception or Error

```text
src/styles.css:8:8:
      8 │ @import "~@fortawesome/fontawesome-free/css/all.css";
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "~@fortawesome/fontawesome-free/css/all.css" as external to exclude it from the bundle, which will remove this error.
```

### Your Environment

```text
Angular CLI: 16.1.3
Node: 18.16.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.3
@angular-devkit/core         16.1.3
@angular-devkit/schematics   16.1.3
@schematics/angular          16.1.3
```

**Comment by alan-agius4** [comment]
This should work if you remove the tilde `~`. The tilde is also no longer supported in the webpack based builder.

**Comment by jcompagner** [comment]
ha, never though about just removing the tilde, but you are correct that works

I guess the current system just tries to find it on disk (so directly as a file) and if not it does try to match it in a npm package?
