### ISSUE TITLE
semver@7.3.5 vulnerabilities in Angular 13.3.x

### ISSUE THREAD

**Issue by thang1160** [angular/angular-cli#25535]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

13.3.x versions still use semver v7.3.5 which is vulnerable to [Regular Expression Denial of Service (ReDoS)](https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795)
https://github.com/angular/angular-cli/blob/30513671a2839714741eb7be5db24d3948841f12/packages/angular_devkit/build_angular/package.json#L59

Also, please upgrade core-js to >=3.23.3

Yarn didn't raise anything but npm does warn about this
```
npm WARN deprecated core-js@3.20.3:
core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues.
```

### Minimal Reproduction

package.json

### Your Environment

```text
Angular CLI: 14.2.1
Node: 14.20.0
Package Manager: yarn 1.22.17 
OS: linux x64
```

**Comment by Krishnajira7** [comment]
I am trying to use "@angular-devkit/build-angular": "^0.12.4", build failing with below error
403 -------------------->>> REQUESTED ITEM IS QUARANTINED -------------------->>> FOR DETAILS SEE ------>>> 
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
npm ERR! 403
npm ERR! 403 It was specified as a dependency of '@babel/helper-compilation-targets'

**Comment by Krishnajira7** [comment]
Dependency list,
 "dependencies": {
    "@angular/animations": "~12.2.6",
    "@angular/cdk": "~12.2.6",
    "@angular/common": "~12.2.6",
    "@angular/compiler": "12.2.16",
    "@angular/core": "~12.2.6",
    "@angular/elements": "~12.2.6",
    "@angular/forms": "~12.2.6",
    "@angular/platform-browser": "~12.2.6",
    "@angular/platform-browser-dynamic": "~12.2.6",
    "@angular/router": "~12.2.6",
    "@ng-idle/core": "9.0.0-beta.1",
    "@ng-idle/keepalive": "9.0.0-beta.1",
    "@ngrx/store": "9.2.0",
    "bootstrap": "~4.3.1",
    "core-js": "2.5.1",
    "dayjs": "^1.9.6",
    "jquery": "^3.3.1",
    "node-sass": "^4.14.1",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "sass-loader": "6.0.6",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.12.4",
    "@angular/cli": "^12.0.0",
    "@angular/compiler-cli": "12.2.16",
    "@angular/language-service": "~12.2.6",
    "@types/jasmine": "2.5.54",
    "@types/jasminewd2": "2.0.3",
    "@types/node": "^17.0.21",
    "codelyzer": "^5.0.1",
    "handlebars": "4.5.3",
    "jasmine-core": "^3.6.0",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "4.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "2.0.0",
    "karma-coverage-istanbul-reporter": "2.0.1",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.0",
    "karma-spec-reporter": "0.0.32",
    "protractor": "~5.4.0",
    "source-map-explorer": "^1.8.0",
    "ts-node": "^5.0.1",
    "tslib": "^1.9.0",
    "tslint": "^5.9.1",
    "typescript": "~4.8.0"
  },

**Comment by alan-agius4** [comment]
Angular 13 is no longer supported. Please update to a more recent version.

See: https://angular.io/guide/releases#actively-supported-versions
