### ISSUE TITLE
esbuild doesn't watch for local library changes while running dev server

### ISSUE THREAD

**Issue by fdsafasd423dfsfdsa** [angular/angular-cli#25569]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

see #25322
see #25568
see #25011
see #25395

all issues are closed and the functionality does not work
when using "@angular-devkit/build-angular:browser" instead of "@angular-devkit/build-angular:browser-esbuild" everything works fine

### Minimal Reproduction

see issues

### Your Environment

```text
Angular CLI: 16.1.5
Node: 18.17.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1601.5
@angular-devkit/build-angular      16.1.5
@angular-devkit/core               16.1.5
@angular-devkit/schematics         16.1.5
@angular/cdk                       16.1.5
@angular/cli                       16.1.5
@angular/flex-layout               14.0.0-beta.41
@angular/material                  16.1.5
@angular/material-moment-adapter   16.1.5
@schematics/angular                16.1.5
rxjs                               7.8.1
typescript                         5.1.6
zone.js                            0.13.1
```

**Comment by pascalmann** [comment]
In my Nx project, only the array files in the "styles" configuration (in build { options }) are not watched with esbuild.

An extra configuration should be to added to list files or folder to wacth.

**Comment by adsafawqew** [comment]
what additional configuration are you talking about?
I create a library according to https://angular.io/guide/creating-libraries

if the library works with "@angular-devkit/build-angular:browser", I expect it to work with  "@angular-devkit/build-angular:browser-esbuild" as well

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
