### ISSUE TITLE
Angular Production Build: Not able to remove the Dependencies Details from angular Build generated main[hash].js file

### ISSUE THREAD

**Issue by neil26** [angular/angular-cli#25568]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello Community,

I am Facing an issue in the Angular Production Build Generated main[hash].js file, the main file generated in builds shows all the information about dependencies, I have tried several things including custom-webpack, but I am unable to remove the details from the main.js file

<img width="362" alt="image" src="https://github.com/angular/angular-cli/assets/20343623/840826d7-9e6f-48f4-a46a-7b0269c4de39">

<img width="725" alt="image" src="https://github.com/angular/angular-cli/assets/20343623/6a23886e-bb70-4879-9998-3f4f03aecc64">

I want to remove the highlighted part from main[hash].js file generated with ng build --prod

### Minimal Reproduction

generated the build using ng build --prod

checked main[hash].js file in browser, dependencies and devDependencies details are still there.

### Exception or Error

```text
To remove Dependencies or devDependencies from the angular prod / UAT build generated main[hash].js
```

### Your Environment

```text
Angular CLI: 7.3.0
Node: 10.19.0
OS: win32 x64
Angular: 7.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.0
@angular-devkit/build-angular      0.13.0
@angular-devkit/build-optimizer    0.13.0
@angular-devkit/build-webpack      0.13.0
@angular-devkit/core               7.3.0
@angular-devkit/schematics         7.3.0
@angular/cdk                       7.3.0
@angular/cli                       7.3.0
@angular/flex-layout               7.0.0-beta.19
@angular/material                  7.3.0
@angular/material-moment-adapter   9.1.3
@ngtools/webpack                   7.3.0
@schematics/angular                7.3.0
@schematics/update                 0.13.0
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0
```

**Comment by JeanMeche** [comment]
The support for v7 was dropped long time ago. Please update your stack before opening a support request.

**Comment by neil26** [comment]
@JeanMeche  I Know, but this project is in Production and has some dependencies due to which I cannot upgrade the stack, appreciate it if you could provide any solution.

**Comment by clydin** [comment]
For license comments in the output chunks, the `extractLicenses` option can be used (enabled by default in production for newly generated projects).

As to the `package.json` content in the output chunks, the application code itself is most likely importing the project's `package.json`. This is something that would need to be fixed within the application's code and not the Angular CLI.
