### ISSUE TITLE
SASS breaks when New Components Added

### ISSUE THREAD

**Issue by lknutilla-ayah** [angular/angular-cli#2556]
### OS?
>Mac OSX - El Capitan

### Versions.
>
angular-cli: 1.0.0-beta.16
node: 6.6.0
os: darwin x64

### Repro steps.
>After adding new components using the Angular CLI, the SASS compiler appears to break. When new properties were added to a shared sass file, the new css property would be pre-pended with the property in the line above. The new components both referenced the shared sass file
#### Example SASS
```
.content
    display: flex //OLD CODE
    flex-direction: row //OLD CODE
    margin-top: 40px //NEW CODE
```
#### Compiled CSS
```
.content {
    display: flex;
    flex-direction: row;
    flex-direction-margin-top: 40px; //???
}
```
#### Directory Structure
```
├── app         
│   └── atest
│     └── ...
│     └── atest.component.ts       # refs app.component.sass as style url
│   └── btest
│     └── ...
│     └── btest.component.ts       # refs app.component.sass as style url
│   └── ...
│   └── app.component.sass

### The log given by the failure.
N/A

/cc @hansl @jesselpalmer

**Comment by filipesilva** [comment]
That's really weird. Will investigate.

**Comment by filipesilva** [comment]
Hm I tried to repro but couldn't. This is what I did:
- started `ng serve`
- changed `app.component.css` to `app.component.sass` and changed it's reference in `app.component.ts`
- add styles to it
```
.content
    display: flex //OLD CODE
    flex-direction: row //OLD CODE
```
- `ng g c atest`, `ng g c btest`
- change their styleUrls to `../app.component.sass`
- add `margin-top: 40px` to `app.component.sass`

Couldn't see what you described. Can you give me a repro?

**Comment by lknutilla-ayah** [comment]
This might be just lack of understanding (first time using angular-cli and new to angular2), but I actually created atest and btest as modules: `ng g module atest`. I'll try again with creating components.

**Comment by lknutilla-ayah** [comment]
it works!
