### ISSUE TITLE
Add Id to css files that get built

### ISSUE THREAD

**Issue by mthor** [angular/angular-cli#2557]
I have an app where the user can change themes.  in order to do this I access the stylesheet href and change it, but I cannot do this with angular-cli or I do not know how. I have a function that works with an index page that does not get built, but I need to have a built file and the css imported through the 'styles'[]

below is the function, I am just wondering if there is a way to add an id to the css styles for the build

changeTheme(event, theme) {
    let themeLink: HTMLLinkElement = <HTMLLinkElement> document.getElementById('theme-css');
    let layoutLink: HTMLLinkElement = <HTMLLinkElement> document.getElementById('layout-css');

    themeLink.href = 'resources/theme/theme-' + theme + '.css';
    layoutLink.href = 'resources/layout/css/layout-' + theme + '.css';
    event.preventDefault();
  }

**Comment by filipesilva** [comment]
Hm... no, there isn't a way to do exactly that, no. 

I know there are ways to dynamically add CSS, I think Angular Material does it.

On Angular 1 projects I've worked on, I used `ng-class` to conditionally add a wrapper class that determined the theme, and had all themes wrapped in that class. There are probably better techniques.

**Comment by mthor** [comment]
thanks for the response, I should of posted my solution for now, I have had to go about adding the css via js, I will be open or keep looking for other techniques.

**Comment by mthor** [comment]
here is what I did, this is for adding primeng, and allowing theme color changes

if (/localhost:4200/.test(window.top.location.host)) {
      document.write('<link rel="stylesheet" id="theme-css" type="text/css" href="resources/theme/theme-indigo.css" />');
      document.write('<link rel="stylesheet" id="layout-css" type="text/css" href="resources/layout/css/layout-indigo.css" />');
    }
