### ISSUE TITLE
Upgrading from Beta.10 to Beta.14 ... a suggestion

### ISSUE THREAD

**Issue by dematic-rodrigo-silveira** [angular/angular-cli#2558]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
$ node --version
v6.5.0
$ npm --version
3.10.3

### Repro steps.
> None

### The log given by the failure.
> None

### Mention any other details that might be useful.
The document could be improved by suggesting the migration of the e2e/ folder!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by RoopeHakulinen** [comment]
If you did this, could you possibly submit a PR with the instructions? :)

**Comment by dematic-rodrigo-silveira** [comment]
The correct place for the proposed change would be on the[ Wiki ](https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.14), as follows:

4a. (it should be placed right below item #4). Replace the e2e/ folder with your application's e2e/ folder:
````bash
mv e2e/ e2e.webpacktemplate/
mv ${OLD_PATH}/e2e e2e
````
Also, amend item 14. to suggest the deletion of all *..webpacktemplate/ folders

**Comment by filipesilva** [comment]
Added e2e `mv` as step 5, but did not add instructions to backup folder as no backup should be necessary.
