### ISSUE TITLE
Solution for component editing (delete, rename, move)

### ISSUE THREAD

**Issue by Sigmale1000** [angular/angular-cli#25595]
### Command

new

### Description

Is there any new ideas or updates on #900?

I feel like the feature request is still something a lot of people (pretty much everyone) would like to be added. 🙉  
Is there any way a solution could be found by the Angular Team or a developer with a bit of extra time?

### Describe the solution you'd like

New features eg. ng rename, ng remove, and ng move to work with components more efficiently. A solution could be found with creating a extension for at least VS Code or directly implementing the feature into the Angular CLI.

### Describe alternatives you've considered

We have to deal with workaround described eg. on https://armno.medium.com/renaming-an-angular-component-7f3990829e84

**Comment by Sigmale1000** [comment]
There is a VS Code extension / [Github Repo](https://github.com/tomwhite007/rename-angular-component), for renaming Angular components by a developer. I tried it, didn't work for me. Anyone had experience with the extension?

**Comment by alan-agius4** [comment]
Please see https://github.com/angular/angular-cli/issues/24489#issuecomment-1373729212
