### ISSUE TITLE
hmr can be broken when using module federation with shared config

### ISSUE THREAD

**Issue by JounQin** [angular/angular-cli#25596]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

https://webpack.js.org/concepts/module-federation/#uncaught-error-shared-module-is-not-available-for-eager-consumption

When `@angular/core` is shared with `eager: false`, this will result

```
Uncaught Error: Shared module is not available for eager consumption
```

at https://github.com/angular/angular-cli/blob/d4e541db3e4b495888f8b653d2141be112e7eef5/packages/angular_devkit/build_angular/src/tools/webpack/plugins/hmr/hmr-loader.ts#L22-L23

This can be fixed easily with:

```diff
-  import ngHmrAccept from '${hmrAcceptPath}';
-  ngHmrAccept(module);
+  import('${hmrAcceptPath}').then(({default:ngHmrAccept})=>ngHmrAccept(module));
```

### Minimal Reproduction

N/A

### Your Environment

```text
Angular CLI: 16.1.3
Node: 18.17.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.1.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.1.3
@schematics/angular             16.1.3
ng-packagr                      16.1.0
rxjs                            7.8.1
```

**Comment by alan-agius4** [comment]
Custom webpack setups are not supported by the Angular CLI.

That said, since this seems like a trivial fix, feel free to open a PR.
