### ISSUE TITLE
ESBUILD on Locked down corporate PC

### ISSUE THREAD

**Issue by NealGooch** [angular/angular-cli#25602]
### Command

new

### Description

This is a new variation of the ESBUILD not being signed issue that causes it not work if your company had locked down executables.

In this particular variation I'm doing "ng new demo" and the install phase fails as it trys to run ESBUILD during the installation. (I end up with no packages installed!).  I've tried Angular @angular/cli@16.0.0 and @angular/cli@16.1.6

The documentation at https://angular.io/guide/esbuild suggest that its a opt-in to use ESBUILD but this appears not to be the case anymore.

More importantly I can't find any instructions on how to change my config/setup so it still works - either with WEBPACK or ESBUILD-WASM.

Many thanks

### Minimal Reproduction

Run "ng new demo" with @angular/cli@16

### Your Environment

```text
Angular CLI: 16.1.6
Node: 16.15.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1601.6 (cli-only)
@angular-devkit/core         16.1.6 (cli-only)
@angular-devkit/schematics   16.1.6 (cli-only)
@schematics/angular          16.1.6 (cli-only)


```

### Anything else relevant?

None

**Comment by clydin** [comment]
The package installation that occurs within the `ng new` command disables package script execution.  No attempts to run esbuild (or any other package's postinstall script) should occur during the installation step.

If possible, please provide the console output of the failing `ng new`.

**Comment by NealGooch** [comment]
Well thats curious....I had the issue for several days on more than once PC and I've just gone to recreate it again to grab the full error message and it now works!

Sadly I've not kept a close enough track of things but now I think about it I suspect I've updated npm to the latest level in between times.
