### ISSUE TITLE
Remove unused css during build

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular-cli#25607]
### Command

build

### Description

It can be useful to be able to remove unused css styles during build, to reduce the overall size of the build. Our project mini css , for example, is as large as 11Mb due to 3rd party libraries of charts, etc.

### Describe the solution you'd like

Such a feature may be setup in angular.json, with a collection of ignore list:

```json
{
   "dropUnsedStyles": true,
   "keepStyles": ["my-css-decoration"]
}
```

### Describe alternatives you've considered

webpack has such a plugin, needs some adjustments to work with `ng build`.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/22809
