### ISSUE TITLE
build doesn't clean output-path

### ISSUE THREAD

**Issue by Meligy** [angular/angular-cli#2561]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Windows 8.1 x64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

```
angular-cli: 1.0.0-beta.16
node: 4.4.2
os: win32 x64
```

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Created using CLI

Run:

`ng build --aot`

Then run any of the following:

`ng build` or `ng serve`

Etc,. any build without AoT.

### The log given by the failure.
> Normally this include a stack trace and some more information.

The `dist` folder still has `ngfactory` folder created and left over.

### Mention any other details that might be useful.

In some cases I have seen also `out-tsc` and `out-tsc-e2e` folders left over in the `dist` folder on other developers machines also using the same version of the CLI.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
That should be fixed in `beta.17`.
