### ISSUE TITLE
command 'ng add @angular/pwa --project <project-name>' break with 'zsh: segmentation fault'

### ISSUE THREAD

**Issue by mrizzello** [angular/angular-cli#25610]
### Command

add

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

The command 'ng add @angular/pwa --project <project-name>' breaks with 'zsh: segmentation fault'. Do you know if this is a problem with angular-cli, angular/pwa, node, npm or my computer ? And how to solve it ?

### Minimal Reproduction

`
ng add @angular/pwa --project isotope
`

### Exception or Error

```text
ℹ Using package manager: npm
✔ Found compatible package version: @angular/pwa@15.2.9.
✔ Package information loaded.

The package @angular/pwa@15.2.9 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
zsh: segmentation fault  ng add @angular/pwa --project isotope
```

### Your Environment

```text
Angular CLI: 15.1.6
Node: 18.17.0
Package Manager: npm 9.6.7
OS: darwin arm64

Angular: 15.2.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@schematics/angular             15.1.6
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else relevant?

Chip : Apple M2 Pro
Mac OS Ventura - 13.5 (22G74)

**Comment by clydin** [comment]
Does this happen in a newly created project for you as well?

If possible, could you try creating a new v16 project and try the `ng add` command?
You should be able to quickly setup a project via `npx @angular/cli@latest new ngadd-test --defaults` (or any project name instead of `ngadd-test`).
