### ISSUE TITLE
In Windows ng g writes paths with wrong slashes

### ISSUE THREAD

**Issue by shahmuratov** [angular/angular-cli#2563]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.11-webpack.8
node: 5.7.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
run 
```
ng g component test
```
in app.module.ts import adds with wrong windows slashes wich prevent typescript compiling

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Meligy** [comment]
This should be fixed already in the latest beta (beta-16). I think the fix is included in beta-15 or so, but you are encouraged to try the latest beta directly of course.

Unless you still experience this with beta-16, you might want to close this issue.

Cheers,

**Comment by shahmuratov** [comment]
Thanks
