### ISSUE TITLE
Angular 15: ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by harleenarora** [angular/angular-cli#25669]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I can't seem to find anything through googling... the closest I get are references to "ResizeObserver loop completed with undelivered notifications". I'm puzzled by this, since it doesn't occur on the other page.

I get this error on production mode.

### Minimal Reproduction

"@angular/cli": "^15.0.1",

### Your Environment

```text
Angular: 15.0.1
Node: 14.21.3
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
