### ISSUE TITLE
Esbuild based dev server returns 404 if starting URL contains a dot (.)

### ISSUE THREAD

**Issue by preda7or** [angular/angular-cli#25671]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

non esbuild dev server

### Description

update: probably related to Vite bug: https://github.com/vitejs/vite/issues/2415

When the esbuild based dev server receives a staring URL that contains a dot (.) in it - instead of routing it to the index.html - it returns 404.

Using any URL with dot in it results in the same 404, any other URL works just fine.

Devtools in network tab/status column instead of the usual 404, show: `(failed) net::ERR_HTTP_RESPONSE_CODE_FAILURE`

### Minimal Reproduction

- setup angular minimal app
- use `"executor": "@angular-devkit/build-angular:browser-esbuild"`
- run `ng serve`
- in browser open: `localhost:4200/.a`

### Exception or Error

```text
Request in devtools looks like this:

http://localhost:4200/.a

#### Request:

GET /.a HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,hu;q=0.8
Connection: keep-alive
Cookie: ...
DNT: 1
Host: localhost:4200
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

#### Response:

HTTP/1.1 404 Not Found
Access-Control-Allow-Origin: *
Date: Fri, 11 Aug 2023 11:42:05 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 0

```

### Your Environment

```text
@angular/cli: 16.1.1
@angular-devkit/build-angular: 16.1.1

OS: Windows 10.0.19044 Build 19044 x64
Browser: Chrome 115.0.5790.171 64bit
Node: 16.20.0
```

### Anything else relevant?

My project is using Nrwl/Nx monorepo, but I don't that has to do anything with this issue.

**Comment by alan-agius4** [comment]
Closing as this is indeed a vite issue which has been addressed upstream and will be solved in the Angular CLI once this is released.
