### ISSUE TITLE
ng test does not load scripts from <head> tag / index.html

### ISSUE THREAD

**Issue by minnie80** [angular/angular-cli#25692]
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I included bootstrap in my angular app (created by `@angular/cli@16.2.0`) by defining links to CDN inside the `<head>` tag of the `index.html` and calling it in `app.component.ts` like the following:

```
declare const bootstrap: any;
ngOnInit(){
   console.log(bootstrap.Tooltip.VERSION);
}
```
`ng serve` worked with functions from bootstrap!

`ng test` (just the boilerplate tests) reported `ReferenceError: bootstrap is not defined` (while ng serve could display the page properly with bootstrap).

### Minimal Reproduction

https://github.com/minnie80/angular-test/tree/bootstrap-from-cdn

### Exception or Error

```text
>npm run test

> angular-test@0.0.0 test
> ng test

✔ Browser application bundle generation complete.
17 08 2023 09:29:31.039:WARN [karma]: No captured browser, open http://localhost:9876/
17 08 2023 09:29:31.059:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
17 08 2023 09:29:31.060:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
17 08 2023 09:29:31.077:INFO [launcher]: Starting browser Chrome
17 08 2023 09:29:32.148:INFO [Chrome 115.0.0.0 (Windows 10)]: Connected on socket s1JzHMXLfQQOZkwPAAAB with id 52028682
Chrome 115.0.0.0 (Windows 10) AppComponent should render title FAILED
        ReferenceError: bootstrap is not defined
            at AppComponent.call [as ngOnInit] (src/app/app.component.ts:13:17)
            at callHookInternal (node_modules/@angular/core/fesm2022/core.mjs:3940:14)
            at callHook (node_modules/@angular/core/fesm2022/core.mjs:3967:13)
            at callHooks (node_modules/@angular/core/fesm2022/core.mjs:3922:17)
            at executeInitAndCheckHooks (node_modules/@angular/core/fesm2022/core.mjs:3872:9)
            at refreshView (node_modules/@angular/core/fesm2022/core.mjs:12913:21)
            at detectChangesInternal (node_modules/@angular/core/fesm2022/core.mjs:12837:9)
            at RootViewRef.detectChanges (node_modules/@angular/core/fesm2022/core.mjs:13354:9)
            at ComponentFixture._tick (node_modules/@angular/core/fesm2022/testing.mjs:126:32)
            at node_modules/@angular/core/fesm2022/testing.mjs:139:22
Chrome 115.0.0.0 (Windows 10): Executed 3 of 3 (1 FAILED) (0.142 secs / 0.13 secs)
TOTAL: 1 FAILED, 2 SUCCESS
```

### Your Environment

```text
Angular CLI: 16.2.0
Node: 18.16.1
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by alan-agius4** [comment]
This is working as intended as the `index.html` is not used for Karma. To include additional `scripts` option.

**Comment by minnie80** [comment]
> ReferenceError: bootstrap is not defined



> This is working as intended as the `index.html` is not used for Karma. To include additional `scripts` option.

Thanks for the info. Yes, adding bootstrap to the `scripts` option in `angular.json` worked:
https://github.com/minnie80/angular-test/tree/a98aa8954214da4129b23b95811a781b48e0a4c5

Does this mean I have to sync scripts included in `index.html` and those in `angular.json` manually?
And what is the reason why the `index.html` is not used for `karma`? In my opinion tests should be done for as-real-as-possible apps. So I would ask to switch the issue from _bug_ to _feature_.

**Comment by alan-agius4** [comment]
> Does this mean I have to sync scripts included in index.html and those in angular.json manually?

You can defined your application and tests scripts in https://github.com/minnie80/angular-test/blob/a98aa8954214da4129b23b95811a781b48e0a4c5/angular.json#L35 and https://github.com/minnie80/angular-test/blob/a98aa8954214da4129b23b95811a781b48e0a4c5/angular.json#L98 so you have a sinlge file were you defin scripts. 

> And what is the reason why the index.html is not used for karma?

Karma has it's own `index.html` as it require special syntax in it's template. See: https://github.com/angular/angular-cli/blob/b09ce572ed72f19c353e71b7d9d751484c5db63a/packages/angular_devkit/build_angular/src/tools/webpack/plugins/karma/karma-debug.html#L26-L44 

> In my opinion tests should be done for as-real-as-possible apps. 

This is not really in scope of a unit test. Typically In unit tests, you typically want to test the smallest piece of code that can be logically tested in isolation to check whether code behaves as intended and does not typically include look and feel. What you are mentioning seems more in scope of an E2E, were your tests, check that the application behaves as expected.

**Comment by minnie80** [comment]
> You can defined your application and tests scripts in https://github.com/minnie80/angular-test/blob/a98aa8954214da4129b23b95811a781b48e0a4c5/angular.json#L35 and https://github.com/minnie80/angular-test/blob/a98aa8954214da4129b23b95811a781b48e0a4c5/angular.json#L98 so you have a sinlge file were you defin scripts.

Yes I could add scripts which are commited to my repo to `build` and `test` but not one from CDN (`Can't resolve` error). How to properly use scripts from CDN?

> 
> > And what is the reason why the index.html is not used for karma?
> 
> Karma has it's own `index.html` as it require special syntax in it's template. See:
> 
> https://github.com/angular/angular-cli/blob/b09ce572ed72f19c353e71b7d9d751484c5db63a/packages/angular_devkit/build_angular/src/tools/webpack/plugins/karma/karma-debug.html#L26-L44
> 

Thank you for the link.

> > In my opinion tests should be done for as-real-as-possible apps.
> 
> This is not really in scope of a unit test. Typically In unit tests, you typically want to test the smallest piece of code that can be logically tested in isolation to check whether code behaves as intended and does not typically include look and feel. What you are mentioning seems more in scope of an E2E, were your tests, check that the application behaves as expected.

Yes, scope of unit test is understood. Look and feel was actually not tested. The mention tests were just the boilerplate tests from angular. I think I am actually stucking at **properly adding scripts from CDN** so that `ng test` works though those scripts are not part of testing.

**Comment by JeanMeche** [comment]
Why would you depend on a CDN on the first place ? That file should come from your deps.

**Comment by minnie80** [comment]
> Why would you depend on a CDN on the first place ? That file should come from your deps.
I thought it's common to use bootstrap from CDN and angular should support this use case.

**Comment by alan-agius4** [comment]
> I thought it's common to use bootstrap from CDN and angular should support this use case.

This is indeed common, but might cause degradation CWV. Since unless you are using the same public CDN multiple times, there would an additional DNS resolutions, HTTP handshakes etc.. As opposed to when you serve it with your application which can be served from a CDN.

**Comment by minnie80** [comment]
> > I thought it's common to use bootstrap from CDN and angular should support this use case.
> 
> This is indeed common, but might cause degradation CWV. Since unless you are using the same public CDN multiple times, there would an additional DNS resolutions, HTTP handshakes etc.. As opposed to when you serve it with your application which can be served from a CDN.

@alan-agius4 Thanks for raising the interesting aspect of using CDN. As I am not knowledgeable about the topic, I asked ChatGPT "Does using resources from CDN (images, css, scripts) cause degradation of CWV?" 😊 and received the answer:

"Content Delivery Networks (CDNs) are typically designed to improve website performance and can actually help improve Core Web Vitals (CWV) when implemented correctly. Core Web Vitals are a set of metrics that measure the user experience on a website, and they include metrics like Largest Contentful Paint (LCP), First Input Delay (FID), and Cumulative Layout Shift (CLS). Let's discuss how CDNs can impact these metrics:

Largest Contentful Paint (LCP): LCP measures the loading performance of the largest element visible in the viewport. CDNs can help improve LCP by reducing the time it takes to deliver assets like images, CSS, and scripts to the user's device. CDNs are designed to distribute content from servers located closer to the user, reducing latency and speeding up the delivery of resources, which can improve LCP.

First Input Delay (FID): FID measures the time it takes for a user's first interaction (e.g., clicking a button) to be processed by the website. CDNs generally do not have a significant impact on FID because it is more related to the browser's processing capabilities and the website's JavaScript execution. FID improvements are typically achieved through code optimization and reducing render-blocking JavaScript.

Cumulative Layout Shift (CLS): CLS measures the visual stability of a web page. It can be affected by the loading behavior of assets like images and if they cause layout shifts as they load. CDNs themselves do not directly impact CLS, but how you implement and optimize resources can. Ensure that you set appropriate dimensions for images to prevent layout shifts as they load.

In summary, CDNs can help improve CWV metrics, especially LCP, by reducing the latency in delivering assets to users. However, the impact on CWV also depends on how you implement and optimize your resources. Properly configuring and optimizing resources for your website, regardless of whether you use a CDN, is essential for achieving good CWV scores. It's also important to regularly monitor and test your website's performance to identify and address any issues that may affect CWV."

To me both your opinion and ChatGPT answer are plausible. What I could come up with so far is "the impact on CWV also depends on how you implement and optimize your resources". That would mean using CDN could still be a relevant use case for angular apps.
