### ISSUE TITLE
Warning of deprecated referenced npms

### ISSUE THREAD

**Issue by advapiIT** [angular/angular-cli#25693]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I got the following warning while I'm doing yarn ci... they seems to start from @angular-devkit/build-angular 

```warning @angular-devkit/build-angular > guess-parser > @wessberg/ts-evaluator@0.0.27: this package has been renamed to ts-evaluator. Please install ts-evaluator instead
warning @angular-devkit/build-angular > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @angular-devkit/build-angular > webpack-dev-server > webpack-dev-middleware > memfs@3.6.0: this will be v4
warning @angular-devkit/build-angular > guess-parser > @wessberg/ts-evaluator > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.```

Are you also get them? How can i fix them?

Thanks




### Minimal Reproduction

Here's my package json

```
{
  "name": "moonshine",
  "version": "0.0.0",
  "scripts": {
    "ci": "yarn install --frozen-lockfile",
    "ng": "ng",
    "start": "ng serve",
    "start:docker": "ng serve --host=0.0.0.0 --disable-host-check --base-href=/",
    "build": "ng build --configuration production --extract-licenses=true && xcopy web.config dist\\ttg-crm",
    "build:linux": "ng build --configuration production --extract-licenses=true && cp web.config dist/ttg-crm",
    "build:staging": "ng build --configuration=staging --extract-licenses=true && xcopy web.config dist\\ttg-crm",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^16.2.1",
    "@angular/cdk": "^16.2.1",
    "@angular/common": "^16.2.1",
    "@angular/compiler": "^16.2.1",
    "@angular/core": "^16.2.1",
    "@angular/forms": "^16.2.1",
    "@angular/localize": "^16.2.1",
    "@angular/material": "^16.2.1",
    "@angular/platform-browser": "^16.2.1",
    "@angular/platform-browser-dynamic": "^16.2.1",
    "@angular/router": "^16.2.1",
    "@angular/service-worker": "^16.2.1",
    "@material/checkbox": "^15.0.0-canary.b994146f6.0",
    "@ng-bootstrap/ng-bootstrap": "^15.1.1",
    "@ngrx/effects": "^16.2.0",
    "@ngrx/store": "^16.2.0",
    "@popperjs/core": "^2.11.8",
    "@progress/kendo-angular-buttons": "13.3.0",
    "@progress/kendo-angular-charts": "^13.3.0",
    "@progress/kendo-angular-common": "13.3.0",
    "@progress/kendo-angular-dateinputs": "13.3.0",
    "@progress/kendo-angular-dialog": "13.3.0",
    "@progress/kendo-angular-dropdowns": "13.3.0",
    "@progress/kendo-angular-editor": "^13.3.0",
    "@progress/kendo-angular-excel-export": "13.3.0",
    "@progress/kendo-angular-grid": "^13.3.0",
    "@progress/kendo-angular-icons": "13.3.0",
    "@progress/kendo-angular-inputs": "13.3.0",
    "@progress/kendo-angular-intl": "13.3.0",
    "@progress/kendo-angular-l10n": "13.3.0",
    "@progress/kendo-angular-label": "13.3.0",
    "@progress/kendo-angular-layout": "13.3.0",
    "@progress/kendo-angular-navigation": "13.3.0",
    "@progress/kendo-angular-notification": "^13.3.0",
    "@progress/kendo-angular-pdf-export": "13.3.0",
    "@progress/kendo-angular-popup": "13.3.0",
    "@progress/kendo-angular-progressbar": "13.3.0",
    "@progress/kendo-angular-scheduler": "^13.3.0",
    "@progress/kendo-angular-toolbar": "13.3.0",
    "@progress/kendo-angular-treeview": "13.3.0",
    "@progress/kendo-angular-upload": "13.3.0",
    "@progress/kendo-angular-utils": "13.3.0",
    "@progress/kendo-data-query": "^1.6.0",
    "@progress/kendo-drawing": "^1.17.5",
    "@progress/kendo-licensing": "^1.3.1",
    "@progress/kendo-svg-icons": "^1.8.0",
    "@progress/kendo-theme-bootstrap": "^6.6.0",
    "@progress/kendo-theme-default": "^6.6.0",
    "@progress/kendo-theme-fluent": "^6.6.0",
    "@progress/kendo-theme-material": "^6.6.0",
    "@types/crypto-js": "^4.1.1",
    "bootstrap": "^5.3.1",
    "crypto-js": "^4.1.1",
    "hammerjs": "^2.0.8",
    "imagesloaded": "^5.0.0",
    "jquery": "^3.7.0",
    "jsencrypt": "^3.3.2",
    "lodash": "^4.17.21",
    "moment": "^2.29.4",
    "ngx-scanner-qrcode": "^1.6.2",
    "pace-js": "^1.2.4",
    "rxjs": "^7.8.1",
    "rxjs-compat": "^6.6.7",
    "sweetalert2": "^11.7.23",
    "tslib": "^2.6.1",
    "zone.js": "~0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^16.2.0",
    "@angular/cli": "~16.2.0",
    "@angular/compiler-cli": "^16.2.1",
    "@types/jasmine": "~4.3.5",
    "@types/lodash": "^4.14.197",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.2",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.1",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.1.6"
  }
}

```

### Exception or Error

_No response_

### Your Environment

```text
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by alan-agius4** [comment]
Hi @advapiIT,

These are not really actionable from your end, or for what matters not even from our end and in these case the packages are transitive dependency.

These warnings can be safely ignored.

**Comment by alan-agius4** [comment]
Closing as per above.
