### ISSUE TITLE
ng build/serve --watch should have a switch to clear the screen before each rebuild

### ISSUE THREAD

**Issue by axos88** [angular/angular-cli#25699]
### Command

build, serve

### Description

Reviving #21559, as I'd like to see the same thing implemented, to always have a clear view of what is actually an error and what has already been addressed. Without this it's very confusing to scroll back and forth to see where the last batch of errors are starting, and what was the output from the last build.

Description of #21559 below:

When I'm refactoring large code-base i revised folowing process:

i have ng serve running
i do some changes in bulk without save
save all
i stop the process
clear the console
then start the ng serve again
I'm doing this to see in isolation what I break, fixed what are new issues etc. So I can focus only on what is relevant

### Describe the solution you'd like

it would be nice to have a switch to run ng serve which would clear console everytime it detects change

### Describe alternatives you've considered

Currently I'm doing it manually - stopping the process, clearing console and starting ng serve again

**Comment by marvhen** [comment]
Here is my upvote for this.

**Comment by marvhen** [comment]
@alan-agius4 does `c` need to be pressed each time we want to clear the console?  Or does it tell the cli to clear on each rebuild?

**Comment by alan-agius4** [comment]
`C+ENTER` will need to be pressed everytime you'd want to clear the screen.

**Comment by marvhen** [comment]
But this is not much different than my current capability.  I can already press CTRL+L to clear my screen as needed.  The desired behavior is for it to automatically clear each time it begins to rebuild, without the need for user interaction.
