### ISSUE TITLE
proxy config json contents needs to be in sequence to work correctly

### ISSUE THREAD

**Issue by SciTechEnthusiast** [angular/angular-cli#25698]
### Command

other, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

I don't know

### Description

Below is the command I'm using 
`ng serve --proxy-config proxy.conf.json`

Contents of **proxy.conf.json** are:

```
{
    "/api/code": {
        "target": "http://localhost/api/code",
        "secure": false,
        "changeOrigin": true
    },
    "/api/codenames": {
        "target": "http://localhost/api/codenames",
        "secure": false,
        "changeOrigin": true
    }
}
```

If I make a call to  `GET /api/codenames` it gets called as  `GET /api/code/api/codenames`

Below is my angular http service code:

```
baseUrl = `${window.location.protocol}//${window.location.host}`
getCode(codename: string): Observable<any> {
    let payload = {
      'codename': codename,
    }
    return this.http.post(`${this.baseUrl}/api/code`, payload);
  }

  getCodeNames(): Observable<any> {
    return this.http.get(`${this.baseUrl}/api/codenames`);
  }

```

### Minimal Reproduction

`ng serve --proxy-config proxy.conf.json`

just make 2 dummy apis with similar name prefix 

e.g.

- `/api/test`
- `/api/testcases`

when you try to call `/api/testcases` it will call `/api/test/api/testcases`

### Your Environment

```text
Angular CLI: 16.1.1
Node: 18.16.0
Package Manager: npm 9.7.2
OS: darwin arm64

Angular: 16.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.1
@angular-devkit/build-angular   16.1.1
@angular-devkit/core            16.1.1
@angular-devkit/schematics      16.1.1
@angular/cdk                    16.1.4
@angular/cli                    16.1.1
@schematics/angular             16.1.1
rxjs                            7.8.1
typescript                      5.1.3
```

### Anything else relevant?

proxy resolving is just wrong I have to put the config in sequence like /codesnames first and then /code in order to make it work:

After changing sequence like below then only I'm able to call correct endpoint:

```
{
    "/api/codenames": {
        "target": "http://localhost/api/codenames",
        "secure": false,
        "changeOrigin": true
    },
    "/api/code": {
        "target": "http://localhost/api/code",
        "secure": false,
        "changeOrigin": true
    }
}
```

**Comment by alan-agius4** [comment]
Are you using the webpack based builder or esbuild based builder? What's the value of the "builder" option in the build section of your `angular.json`?

**Comment by alan-agius4** [comment]
Closing as author did not get back to use.

**Comment by SciTechEnthusiast** [comment]
`"builder": "@angular-devkit/build-angular:browser" `

in angular.json

**Comment by alan-agius4** [comment]
In that case, likely this is a problem with [http-proxy-middleware](https://github.com/chimurai/http-proxy-middleware#readme) which is a dependency of webpack-dev-server as for the webpack based dev-server we do not process the proxy configuration ourselves.
