### ISSUE TITLE
IvyPlugin is overriding tsconfig options in AngularWebpackPlugin which leads to coverage issues

### ISSUE THREAD

**Issue by tommyc38** [angular/angular-cli#25691]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I was running testing an angular buildable library using Storybook and Cypress.  I wanted coverage for my cypress tests but my coverage was thrown off because my source maps were partially compiled (e.g. decorators) so my line numbers were off. See [this issue](https://github.com/storybookjs/storybook/issues/21171) for a repro and more details.  I looked at the webpack config that was used to build storybook and noticed that AngularWebpackPlugin had `complierOptions.sourceMap = false` which was overriding my tsconfig which had `sourceMap = true`.  I set `sourceMap = true` in the webpack config at runtime and my source maps worked as expected.  I found the culprit in your source code [here](https://github.com/angular/angular-cli/blob/c3c4853d4d908025e2f9f0d32419f11459021bff/packages/angular_devkit/build_angular/src/tools/webpack/plugins/typescript.ts#L22C45-L22C45) and was wondering why you are explicitly setting these values and not letting tsconfig be the source of truth?  Is this a bug?  

### Minimal Reproduction

There is a repro in the referenced issue above.

### Exception or Error

```text
There are no errors just unexpected behavior.
```

### Your Environment

```text
// partial package.json. ng version doesn't work in nx project.
  "dependencies": {
    "@angular/animations": "16.1.8",
    "@angular/common": "16.1.8",
    "@angular/compiler": "16.1.8",
    "@angular/core": "16.1.8",
    "@angular/forms": "16.1.8",
    "@angular/platform-browser": "16.1.8",
    "@angular/platform-browser-dynamic": "16.1.8",
    "@angular/router": "16.1.8",
    "@nx/angular": "16.6.0",
    "rxjs": "7.8.1",
    "tslib": "^2.3.0",
    "zone.js": "0.13.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "16.1.8",
    "@angular-devkit/core": "16.1.8",
    "@angular-devkit/schematics": "16.1.8",
    "@angular-eslint/eslint-plugin": "16.0.3",
    "@angular-eslint/eslint-plugin-template": "16.0.3",
    "@angular-eslint/template-parser": "16.0.3",
    "@angular/cli": "~16.1.0",
    "@angular/compiler-cli": "16.1.8",
    "@angular/language-service": "16.1.8",

```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment]
This is intended. As the source-map option value is set in the `angular.json` via the builder settings. This is to avoid misalignment as multiple underlying tools like Sass, Babel, Terser, Esbuild in the compilation require the same value for source-map. This also reduces the need to create additional config files to disable the sourcemaps for example when building for production.

In the case of storybook, it would make sense that they enable sourcemaps forcefully when code coverage is, as it is somewhat expected that code coverage will be broken without them.
