### ISSUE TITLE
ng build does not display typescript errors when output is not a tty

### ISSUE THREAD

**Issue by arobinson** [angular/angular-cli#25702]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using an application to run `ng build` or piping the `ng build` output to a file, the typescript errors are not included, only the template warnings. When running it from a console/tty, the errors are correctly displayed. 

We used to not have Typescript and Angular strict mode on. We want to get to the point where we have it on, so we are trying to capture the issues in our CI build and report them to Sonar as code smells via a custom eslint report so that we can reduce the issues over time. The problem is that trying to capture the `ng build` output is failing to work, hence reporting this issue. Without being able to get the typescript error output, it blocks our ability to capture this information.

### Minimal Reproduction

No typescript errors reported:
```
ng build -c strict --no-progress 2>&1 >&- > /tmp/ng-output.txt
```

Typescript errors correctly reported:
```
ng build -c strict --no-progress
```

tsconfig.strict.json:
```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "baseUrl": "./",
    "strict": true
  },
  "angularCompilerOptions": {
    "preserveWhitespaces": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  }
}
```

angular.json:
```
{
  ...
          "configurations": {
            "strict": {
              "tsConfig": "./tsconfig.strict.json"
            },
  ....
}
```

I'm actually trying to capture it from Python3, and getting the same problem:
```
import subprocess as sp
if __name__ == "__main__":
    p = sp.Popen(
        ["ng", "build", "--no-progress", "-c", "strict"],
        stderr=sp.STDOUT,
        stdout=sp.PIPE,
        bufsize=1,
        universal_newlines=True,
    )
    for i, line in enumerate(p.stdout, 1):
        line = line.rstrip()
        print(line)
```

Once again, only the `Warning:` lines are seen, the typescript errors are lost

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.0.3
Node: 16.16.0
Package Manager: pnpm 7.27.0
OS: darwin arm64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1600.3
@angular-devkit/core         16.0.3
@angular-devkit/schematics   16.0.3
@schematics/angular          16.0.3
```
```


### Anything else relevant?

Mac OSX Ventura 13.4
Zsh command-line for the shell commands used above
Python 3.9.6 for the python code

Tried using `FORCE_COLOR` 3 and 0 and still no help

`ng build` seems to just be doing something really odd with its output when not a tty

**Comment by arobinson** [comment]
Work-around found at least:
https://py4u.org/questions/52954248/

Using python to create a psuedo tty, and using FORCE_COLOR=0 in the environment, I can fake `ng build` to correctly produce the needed output. Very messy, but it will work until this can be fixed

**Comment by alan-agius4** [comment]
Hi @arobinson, 

I did try the above and I was not able to replicate it to the fully.

While I did replicate it using the pipe command, you suggested I was not able to do so with the below;

Discard `stdout` and redirect `stderr` to file
```
ng build -no-progress 1>&- 2>&/tmp/ng-output.txt
```

Redirect both `stdout` and `stderr` to file
```
ng build -no-progress $> /tmp/ng-output.txt
```

I also tried to use the Python script and this worked as expected.

```python
import subprocess as sp
if __name__ == "__main__":
    p = sp.Popen(
        ["ng", "build", "bar", "--no-progress"],
        stderr=sp.STDOUT,
        stdout=sp.PIPE,
        bufsize=1,
        universal_newlines=True,
    )
    for i, line in enumerate(p.stdout, 1):
        line = line.rstrip()
        print('Log from PYI:' + line)

```

```
python build.pyi
Log from PYI:
Log from PYI:Error: projects/bar/src/app/app.module.ts:17:5 - error TS2552: Cannot find name 'AppRoutingMoxdule'. Did you mean 'AppRoutingModule'?
Log from PYI:
Log from PYI:17     AppRoutingMoxdule
```

**Comment by alan-agius4** [comment]
Closing as we are unable to replicate this. If the problem persists please re-open with more information.
