### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sebashotte** [angular/angular-cli#2571]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
El Capitan

### Versions.
node 6.7.0
npm 3.10.3

### Repro steps.
sudo npm install -g angular-cli

### The log given by the failure.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng

> fsevents@1.0.14 install /usr/local/lib/node_modules/angular-cli/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: node-pre-gyp: command not found
npm WARN install:fsevents@1.0.14 fsevents@1.0.14 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:fsevents@1.0.14 spawn ENOENT

> execSync@1.0.2 install /usr/local/lib/node_modules/angular-cli/node_modules/execSync
> node install.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
path.js:1144
          cwd = process.cwd();
                        ^

Error: EACCES: permission denied, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1144:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:509:3
/usr/local/lib
└── (empty)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! execSync@1.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the execSync@1.0.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the execSync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs execSync
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls execSync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
npm ERR! code 1

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gelliott181** [comment]
`Error: EACCES: permission denied, uv_cwd`
I'd say your problem is a lack of `sudo` as you're attempting to install globally (Meaning access to protected directories such as `/usr` is needed)

**Comment by filipesilva** [comment]
You seem to be getting some `Permission denied` errors. This is likely due to a faulty `npm` install. See https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by sebashotte** [comment]
I have uninstall and reinstall npm and this doesn't work. I was told is may have a problem with the new SIP from EL Capitan OS.
