### ISSUE TITLE
log to display prerendering routes instead of only count of routes

### ISSUE THREAD

**Issue by guoapeng** [angular/angular-cli#25719]
# Proposal
when prerendering the application, it only shows a very general information that how many routers are prerendered like below
```bash
Build at: 2023-05-08T04:01:05.767Z - Hash: bb19255f33cb87a0 - Time: 18098ms
⠦ Prerendering 3 route(s) to <ProjectRoot>\dist\application-name\browser..
```
when I open the browser folder, I can't easily figure out which files are generated by prerendering process since there are too many generated files by different tasks.

Moreover, it would be helpful to give some info from log that the prerendering routes are from which source since there are guess-router, routes specified by option routes or routes-file or from ng options --routes or --routers-file etc to avoid confusing on analyzing which option took effect when troubleshooting. actually I am facing an issue that there is unexpected prerending routes but I am confused where are them came from and feel hard to look into due to lack of helpful log.

#### What is the summary of the proposal?

1. add more log on prerendering routes
2. possibly printing source of the prerendering routes

**Comment by guoapeng** [comment]
thanks for the respnse on the proposal!  additional thoughts from me  if we can impement an cli option  for the feature to control printing the detailed log or printing a very brief log followd with a suggestion that tells users  there is an option for printing the detailed log for troubleshooting.  that's only additonal thoughts from me not to consider if too difficult to implement and it's up to you guys on how to improve the user experience.

**Comment by alan-agius4** [comment]
With the new application builder in version 17.0.0, we now generate a `prerendered-routes.json` which contains a list of all the routes that were prerendered.
