### ISSUE TITLE
Cannot use a dependency in a yarn workspace

### ISSUE THREAD

**Issue by Konubinix** [angular/angular-cli#25729]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi.

Thank you for the awesome work around angular. I don't know whether this is actually a bug or I did not understand something about any of yarn, typescript, esm, commonjs, angular, webpack...

When using a simple angular project as a yarn workspace, I cannot use the exports of a sibling project.

### Minimal Reproduction

Here is the description of how to reproduce the issue, I attached the whole project as well

[myproject.zip](https://github.com/angular/angular-cli/files/12464740/myproject.zip)

1. create a yarn workspace root package.json, pointing to the two workspaces we will create now
```json
{
  "name": "myproject",
  "private": true,
  "workspaces": [
    "angular",
    "lib"
  ]
}
```
2. create a simple angular project
`ng new angular` (then, keep the default value for everything that is asked)
3. add the "private": true entry in its package.json to indicate it is a workspace
4. create a very simple library called lib
with the following package.json
```json
{
    "name": "@mylib/lib",
    "version": "0.1.0",
    "private": true
}
```
and the following index.ts
```typescript
export const somevariable = "something";
```
5. indicate in the package.json of the angular workspace the dependency toward the sibling library, adding `"@mylib/lib": "^0.1.0",` in its dependency section.
6. in the root component on the angular workspace, make use of the variable
`import { somevariable } from '@mylib/lib';`
and then, set the title to somevariable 
```typescript
...
export class AppComponent {
  title = somevariable;
}
...
```
7. run `ng serve`

You will see that somevariable does not appear.
![image](https://github.com/angular/angular-cli/assets/1181438/7bc2edf6-3059-423e-a311-2d6bc6a289dd)

Strangely, changing `import { somevariable } from '@mylib/lib';` into `import { somevariable } from '../../../lib';` works around this issue. You need to `rm -rf .angular/ && ng serve` to actually see the impact of the change.

![image](https://github.com/angular/angular-cli/assets/1181438/fdf4e2a0-ee8f-4a27-8388-26edcef10df6)

### Your Environment

```text
✔  ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.0
Node: 18.15.0
Package Manager: npm 9.5.0
OS: linux x64

Angular: 16.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

### Anything else relevant?

Running `ng build` in development mode, I could find out that the webpack export was actually empty where `somevariable` should have been.

the bundled code looks like this
```
class AppComponent {
  constructor() {
    this.title = _mylib_lib__WEBPACK_IMPORTED_MODULE_0__.somevariable;
  }
}
```
With `_mylib_lib__WEBPACK_IMPORTED_MODULE_0__` defined like this `/* harmony import */ var _mylib_lib__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @mylib/lib */ 6479);`

Then, the content associated to 6479 is the following
```
/***/ 6479:
/*!***********************!*\
  !*** ../lib/index.ts ***!
  \***********************/
/***/ (() => {



/***/ })
```

I assume there has been some too eager tree-shaking somewhere.

Thank you again for angular. I hope this bug report is helpful. In case it is just me doing something wrong, I would be very welcome if you provided some guidance about how to make this work.

My best,

**Comment by Konubinix** [comment]
I realized that I did not give the instruction to use the myproject.zip
1. unzip myproject.zip
2. cd myproject
3. yarn 
4. cd angular
5. ng serve


Also, I realized that angular (or node, or typescript, or webpack, or... I'm not sure what tools is doing this) behaves differently when I move lib into node_modules.

`import { somevariable } from '../../../lib';` works well
but moving lib to node_modules and `import { somevariable } from '../../../node_modules/lib';` fails.

Therefore, to the best of my understanding, the fact that `import { somevariable } from '@mylib/lib';` gets the content from ../node_modules/@mylib/lib causes the issue.

For other dependencies work well in general and are also got from node_modules, I assume there is something I forgot to do to avoid `@mylib/lib` from being dropped. I hope someone in here could provide me with a hint of what I did wrong.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Konubinix** [comment]
Thank you for your answer. I will do this. At least this confirms that I need some guidance :-)
