### ISSUE TITLE
Firestore onSnapshot causes prerender to stuck

### ISSUE THREAD

**Issue by 10eputzen** [angular/angular-cli#25724]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders

### Is this a regression?
I do not know

### Description

The onSnapshot ([from firebase documentation](https://firebase.google.com/docs/firestore/query-data/listen#web-modular-api_3)) causes `npm run prerender` to get stuck when using the regular builder in angular.json

```
    "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
```

while generating the routes.

  ```
const unsubscribe = onSnapshot(q, (querySnapshot) => {
  const cities = [];
  querySnapshot.forEach((doc) => {
      cities.push(doc.data().name);
  });
  console.log("Current cities in CA: ", cities.join(", "));
});
```

When using esbuild - it works fine.
```
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser-esbuild",
```

## 🔬 Minimal Reproduction

- create a new project with routing
- add angular universal
- add a route
- add firebase with some mock data
- use onSnapshot on this collection for live updates
- `npm run prerender`

Here is my Bug Repo. You need to have a firestore config pasted into the environment.ts
https://github.com/10eputzen/angularBugRepo/tree/bug/angularUniversal

## 🔥 Exception or Error

Unfortunately there is no error - the prerendering is stuck here:
`Prerendering 1 route(s) to /angularBugRepo/dist/angularBugRepo/browser...`

I am getting this error as well, but I also get it with esbuild and everyhting works fine with dev:ssr 
`Unable to extract routes from application.`

## 🌍 Your Environment

<pre><code>
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.0
@angular/cli                    16.2.0
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.2.0
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1

</code></pre>

**Comment by NsovoBaloyi** [comment]
> > Having the same issue, but not related to firebase. I'm however not sure how to reproduce the issue as it works sometimes.
> 
> Does switching the builder to browser-esbuild help?

It seems to work with browser-esbuild, however, I can't use browser-esbuild yet

**Comment by alan-agius4** [comment]
@10eputzen, Is this still an issue with version 17? In the case it is can you please update the reproduction to reproduce the exact error without us having to setup firebase? 

Thanks.

**Comment by alan-agius4** [comment]
Closing as no further feedback was provided.
