### ISSUE TITLE
Doc: src/app/shared add documentation comments to index.ts

### ISSUE THREAD

**Issue by arlowhite** [angular/angular-cli#2572]
### Versions.
angular-cli: 1.0.0-beta.16
node: 6.3.1
os: linux x64

### Repro steps.
Create project with `ng new`

### Needed Documentation

angular-cli projects have a shared directory with this file _src/app/shared/index.ts_

I haven't read through all of the new NgModule docs on angular.io, so I wasn't sure what this was for.

Please add a comment to this file that links to angular.io:
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module

Also, maybe give a few example ng commands. (angular-cli/tests/acceptance has a couple examples)
`ng generate module shared/my-module`
`ng generate class shared/my-class`

#### Questions

Should the developer modify shared/index.ts?
Do they need to add `export * from './my-module'` as in _src/app/index.ts_?

Also, I noticed [angular-cli/tests/e2e/tests/build/ts-paths.ts](https://github.com/angular/angular-cli/blob/master/tests/e2e/tests/build/ts-paths.ts) modifies tsconfig.json so that you can `import '@shared/my-module;`
Should this be added to tsconfig.json by default or should it be documented somewhere?

----
**shared/index.ts**
```typescript
// Directory for Shared Modules
// https://angular.io/docs/ts/latest/guide/ngmodule.html#!#shared-module
//
// You can generate files here with ng, for example:
//  ng generate module shared/my-module
//  ng generate class shared/my-class
```

**Comment by filipesilva** [comment]
@Brocco what do you think about adding comment docs to `shared/`?

Regarding `@shared/my-module`, I don't think we should add documentation around it since it's a TypeScript feature. We simply added support for it.

**Comment by Brocco** [comment]
The idea of `shared/index.ts` is a hold over from supporting barrels, and can be removed from newly generated projects. I will submit a PR.
