### ISSUE TITLE
Exclude routes for pre-rendering

### ISSUE THREAD

**Issue by tmk1991** [angular/angular-cli#25728]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [X] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
 A clear and concise description of the problem or missing capability...
Adding option to `angular.json` for excluded routes

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
Ability to pass in an array of routes to exclude from pre-rendering but keep them as a part of the site. 

It would be "nice" to include wild cards as well.

**Comment by Exac** [comment]
What if the option to make a route not be pre-rendered was in the `Route` interface instead of `angular.json`?

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/28346
