### ISSUE TITLE
Help Request - Does the ngc work with Typescript Definition files?

### ISSUE THREAD

**Issue by mtycholaz** [angular/angular-cli#2573]
I'm building an Ionic 2 app that targets Windows 10 UWP. I access the winrt API's in my code directly, like this.
`var localFolder = Windows.Storage.ApplicationData.current.localFolder;`

And I've included the winrt definitelyType file in my typings.json config

```
{
  "dependencies": {},
  "devDependencies": {},
  "globalDependencies": {
    "angular-protractor": "registry:dt/angular-protractor#1.5.0+20160425143459",
    "core-js": "registry:dt/core-js#0.0.0+20160725163759",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:dt/node#6.0.0+20160831021119",
    "selenium-webdriver": "registry:dt/selenium-webdriver#2.44.0+20160317120654",
    "winrt": "registry:dt/winrt#0.0.0+20160622234326"
  }
}
```

Compiling with tsc works, but I get an error with the ngc. 
`Error at C:/source/repos/Ionic/.tmp/services/localstorage.service.ts:10:19: Cannot find name 'Windows'.`

This makes me think that either ngc doesn't support my Typescript definition files, or I've configured something wrong. 

Does anyone have ideas as to how to work around this problem?

**Comment by mtycholaz** [comment]
I bring tidings of great news! Right now my project is configured to use typings globally. However, I've found that if I manually add a reference to the definition file, the ngc uses it. Basically, put this at the top of your Typescript file, and then compile. Hope this helps someone.

`/// <reference path="../../typings/globals/winrt/index.d.ts" />`

**Comment by filipesilva** [comment]
Heya @mtycholaz, you should be able to do `npm install @types/winrt --save-dev` to get the typings, nothing else needed!
