### ISSUE TITLE
Specify rest api url after prod build?

### ISSUE THREAD

**Issue by dantullis** [angular/angular-cli#2574]
Is there a way to specify a back-end REST URL:Port after the CLI has built a --prod build? 

For example, say I have just one Angular 2 client distribution build and

it is put on http://www.clientURL-A.com and points to the REST API server of http://serverURL-A:8080 

Additionally, using that same build, I put it on http://www.clientURL-B.com and the REST API server for that client is http://serverURL-B:8181

How can I config the REST API server separately after doing a single build?

**Comment by intuitivepixel** [comment]
I would create separate environment files (https://github.com/angular/angular-cli/blob/master/README.md#build-targets-and-environment-files) one for each domain and use that env file when building your app.

**Comment by clydin** [comment]
This is really a question for SO.  Issues are meant for bug reports or feature requests.

But to answer your question, If you wanted to maintain one build, I would put the API server address in a json file that would then be loaded by the app (`http.get`).

**Comment by filipesilva** [comment]
Closing as I feel the answers so far are pretty good and should address the issue.
