### ISSUE TITLE
AotPlugin is not a constructor error in beta 17

### ISSUE THREAD

**Issue by kucharzyk** [angular/angular-cli#2575]
### OS
```
Windows 10
```

### Versions.
```
angular-cli: 1.0.0-beta.17
node: 6.7.0
os: win32 x64
```

### Repro steps.
```
mkdir bug
cd bug
ng init
ng build -prod --aot
```

### The log given by the failure.
```
C:\Users\tomasz\bug>ng build -prod --aot
webpack_1.AotPlugin is not a constructor
TypeError: webpack_1.AotPlugin is not a constructor
    at Object.exports.getWebpackAotConfigPartial (C:\Users\tomasz\bug\node_modules\angular-cli\models\webpack-build-typescript.js:57:13)
    at new NgCliWebpackConfig (C:\Users\tomasz\bug\node_modules\angular-cli\models\webpack-config.js:18:42)
    at Class.run (C:\Users\tomasz\bug\node_modules\angular-cli\tasks\build-webpack.js:17:22)
    at Class.run (C:\Users\tomasz\bug\node_modules\angular-cli\commands\build.js:50:26)
    at Class.<anonymous> (C:\Users\tomasz\bug\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (C:\Users\tomasz\bug\node_modules\rsvp\dist\lib\rsvp\-internal.js:215:12)
    at invokeCallback (C:\Users\tomasz\bug\node_modules\rsvp\dist\lib\rsvp\-internal.js:230:13)
    at C:\Users\tomasz\bug\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
    at flush (C:\Users\tomasz\bug\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by filipesilva** [comment]
`beta.17` is still being tested and not marked as latest yet. When it is marked as latest this error will go away since it's dependency related.

Meanwhile if you want to test the `experimental` tag you can fix this issue by doing by editing your local `./node_modules/angular-cli/package.json` to use `"@ngtools/webpack": "experimental",` and running `npm install` there.

**Comment by kucharzyk** [comment]
Thanks for your answer

**Comment by kucharzyk** [comment]
It's now working :)

**Comment by DnyaneshwarShivbhakta** [comment]
I am getting the same error while running production build through webpack command..Is there any way?

**Comment by jrafael83** [comment]
I am getting this error:
TypeError: AotPlugin is not a constructor

my @angular/cli": "^1.7.4"

my webpack.config:

const path = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const AotPlugin = require('@ngtools/webpack').AotPlugin;
const CheckerPlugin = require('awesome-typescript-loader').CheckerPlugin;
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

module.exports = (env) => {
    // Configuration in common to both client-side and server-side bundles
    const isDevBuild = !(env && env.prod);
    const sharedConfig = {
        stats: { modules: false },
        context: __dirname,
        resolve: { extensions: [ '.js', '.ts' ] },
        output: {
            filename: '[name].js',
            publicPath: 'dist/' // Webpack dev middleware, if enabled, handles requests for this URL prefix
        },
        module: {
            rules: [
                { test: /\.ts$/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader', 'angular2-router-loader'] : '@ngtools/webpack' },
                { test: /\.html$/, use: 'html-loader?minimize=false' },
                { test: /\.css$/, use: [ 'to-string-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize' ] },
                { test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' }
            ]
        },
        plugins: [new CheckerPlugin()]
    };

    // Configuration for client-side bundle suitable for running in browsers
    const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig, {
        entry: { 'main-client': './ClientApp/boot.browser.ts' },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // Plugins that apply in production builds only
                new UglifyJSPlugin({
                    uglifyOptions: {
                        warning: "verbose",
                        ecma: 6,
                        beautify: false,
                        compress: false,
                        comments: false,
                        mangle: false,
                        toplevel: false,
                        keep_classnames: true,
                        keep_fnames: true
                    }
                }),
            new AotPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.browser.module#AppModule'),
                exclude: ['./**///*.server.ts']
            })
        ])
    });

    // Configuration for server-side (prerendering) bundle suitable for running in Node
    const serverBundleConfig = merge(sharedConfig, {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot.server.ts' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ].concat(isDevBuild ? [] : [
            // Plugins that apply in production builds only
            new AotPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.server.module#AppModule'),
                exclude: ['./**///*.browser.ts']
            })
        ]),
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },
        target: 'node',
        devtool: 'inline-source-map'
    });

    return [clientBundleConfig, serverBundleConfig];
};
