### ISSUE TITLE
esbuild doesn't watch for local library changes while running dev server (cli-cache-enabled=false,preserveSymlinks=true)

### ISSUE THREAD

**Issue by adsafawqew** [angular/angular-cli#25753]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

see #25569

library changes are not reflected when using "cli-cache-enabled"=false and  "preserveSymlinks"=true and esbuild
when using "@angular-devkit/build-angular:browser" instead of "@angular-devkit/build-angular:browser-esbuild" everything works fine

angular.json
```
"cli": {
    "cache": {
        "enabled": false
    }
}
```

```
"options": {
    "preserveSymlinks": true
}
```

when using "cli-cache-enabled"=true and remove "preserveSymlinks" from otions everything works fine
when using "cli-cache-enabled"=false and remove "preserveSymlinks" application won't start

when using "cli-cache-enabled"=true and "preserveSymlinks"=true changes are not detected
when using "cli-cache-enabled"=true and "preserveSymlinks"=false everything works fine

when using "cli-cache-enabled"=false and "preserveSymlinks"=true changes are not detected
when using "cli-cache-enabled"=false and "preserveSymlinks"=false application won't start

everything works fine = ts and html changes from library work, scss from library doesn't work

I expected to change "@angular-devkit/build-angular:browser" to "@angular-devkit/build-angular:browser-esbuild" and everything would work, but now I will end up in psychiatry because of esbuild

### Minimal Reproduction

see #25569

### Your Environment

```text
Angular CLI: 16.2.1
Node: 18.17.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.1
@angular-devkit/build-angular      16.2.1
@angular-devkit/core               16.2.1
@angular-devkit/schematics         16.2.1
@angular/cdk                       16.2.2
@angular/cli                       16.2.1
@angular/flex-layout               14.0.0-beta.41
@angular/material                  16.2.2
@angular/material-moment-adapter   16.2.2
@schematics/angular                16.2.1
rxjs                               7.8.1
typescript                         5.1.6
zone.js                            0.13.1
```

**Comment by vfg12e9w** [comment]
see https://github.com/angular/angular-cli/issues/26585
see https://github.com/angular/angular-cli/commit/a8dbf1da27faf772a4df382b1301e95c32d1ba89

tested with angular v17.0.6 and https://github.com/angular/angular-cli/issues/26585#issuecomment-1840982411
still not working
ChatGPT says: one step closer to madness

problem is probably:
```
"cli": {
    "cache": {
        "enabled": false
    }
}
```

**Comment by 3z6tfx6d** [comment]
1. create test-lib
```
npx @angular/cli new test-lib --no-create-application --style=scss
cd test-lib
npx @angular/cli generate library test-lib
npx @angular/cli build --watch
```

2. create test-app and link test-lib
```
npx @angular/cli new test-app --routing=true --style=scss --ssr=false
cd test-app
npm link ../test-lib/dist/test-lib
```

3. change app.component.ts
```
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { TestLibComponent } from 'test-lib';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, TestLibComponent],
  template: '<lib-test-lib></lib-test-lib>',
  styleUrl: './app.component.scss'
})
export class AppComponent {
  title = 'test-app';
}
```

4. change package.json
```
"dependencies": {
	"test-lib": "file:../test-lib/dist/test-lib"
}
```

5. change angular.json
```
"builder": "@angular-devkit/build-angular:application",
"options": {
	"preserveSymlinks": true
}
```

6. start test-app
```
npm start
```

make some changes in test-lib.component.ts (html, ts or styles)
**Result is that no changes are reflected in your browser.**

7. change now angular.json
```
"builder": "@angular-devkit/build-angular:browser",
"options": {
	"preserveSymlinks": true,
	"main": "src/main.ts",
}
```

restart test-app
make some changes in test-lib.component.ts (html, ts or styles)
**Result is that changes are now reflected in your browser.**

something with new esbuild/application builder doesn't work for a long time...

**Comment by alan-agius4** [comment]
@3z6tfx6d, from the repro steps, it doesn’t look like your configuring the typescript path mappings are described in https://github.com/angular/angular-cli/issues/26585#issuecomment-1840982411

**Comment by xx11sw3om** [comment]
repeat the steps and you will see that it does not work regardless of whether you write the typescript path mappings (https://github.com/angular/angular-cli/issues/26585#issuecomment-1840982411) or not

I'm crazy, but I'm not that crazy

therefore it is questionable whether #26585 is actually fixed or not, because the steps are more or less the same

**Comment by e23gap32oq** [comment]
I can confirm that in version 17.0.7 it works with cli-cache-enabled=false and preserveSymlinks=true

**Comment by achrysanthakopoulou** [comment]
I have the same problem in 17.0.9 regardless of cli cache or preserveSymlinks properties.
Mostly library html and scss changes give me a "No output file changes".

That doesn't seems like everything is working fine:
> everything works fine = ts and html changes from library work, scss from library doesn't work

**Comment by jyounce-aim** [comment]
Hi everyone,

I to am seeing this issue after upgrading to Angular v17.1.0.

My Local Setup:
Mac Ventura v13.3
Angular v17.1.0
Node.js v20.11.0

fwiw, I have spent the last 6 hours trying to find a solution to no avail.

The problem:
Local application serves fine with my local library symlinked in. Library builds fine when I make changes but the browser does not reload with those changes. Investigating in the chrome console Sources tab I see the problem under:
webpack://
  node_modules
    my-lib
      my-file.mjs (is not updated with the changes)

So it seems to be a webpack caching issue.

Any help would be greatly appreciated, thank you.
