### ISSUE TITLE
Loading an assets file with relative path

### ISSUE THREAD

**Issue by phihochzwei** [angular/angular-cli#25768]
* **I'm submitting a ...**
```
- [X ] bug report
- [ ] feature request
- [ ] support request 
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
When trying to load assets files (json) from the assets folder with a relative path, the Universal version of our application fails to load them. The client version works fine. The files are intended to load via a service which is initiated via APP_INITIALIZER. The service starts up and works fine, just the files cant be loaded. Unless you load them with an absolute path (http://localhost:4000/assets...)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
- Create a service to load json-files via HttpClient.
- Call it via APP_INITIALIZER
- Turn on Universal according to https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/universal-rendering.md

* **What is the expected behavior?**
The expected behaviour would be that the files load as they do in the client version

* **Please tell us about your environment:**

- Angular version: 5.0
- Browser: [all]
- OS:  [Mac OS X | Windows ]
- Platform: [all | NodeJs ]

**Comment by igoraugustynski** [comment]
Isn't disabling outputHashing for the server target enough?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
