### ISSUE TITLE
Cookie domain is not set when code execute on server side

### ISSUE THREAD

**Issue by alexander-kiriliuk** [angular/angular-cli#25769]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [*] common
- [*] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.14

### Description

When we set cookie with specific domain on the server side, cookies without a domain arrive in the browser

## 🔬 Minimal Reproduction
Run dev server and add following code to your app component:
```
constructor(@Inject(RESPONSE) private response: Response){}

// ...

this.response.cookie("test-cookie", `test`, {domain: ".test.local"});
```

Or:

`this.response.setHeader("Set-cookie",`testcookie=test; Domain=.test.local; Path=/;`);`

## 🌍 Your Environment
<pre><code>

Angular CLI: 11.2.14
Node: 14.16.1
OS: win32 x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    11.2.13
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.2.1
@schematics/angular             11.2.14
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.1.6

</code></pre>
**Also i tested it in angular 12.1.1, the bug remained**

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
