### ISSUE TITLE
Prerender localize routes

### ISSUE THREAD

**Issue by raphdom** [angular/angular-cli#25766]
# 🚀 Feature request

Prerender localize routes

- [x ] builders

I have a use case that my routes are localize, like:

en/about
pt/sobre
es/acerca

### Describe the solution you'd like

Could be a possibility to have in the file that we specify for the prerender builder with the /en or /pt

This will allow the builder to generate only the one that is specific for this language

### Describe alternatives you've considered

The alternative is have one builder per language, but this case, I have 24 languages, it will be a huge config file because I need one for browser and one for server builds...

**Comment by alan-agius4** [comment]
How are localized routes being registered in the Angular app? IE: what is the logic determines if route `about` or `sobre` is registered in the router?

**Comment by alan-agius4** [comment]
Thanks for reporting this feature. However, you didn't provide sufficient information for us to understand how in your case routes are being localized.
