### ISSUE TITLE
vite - Expose ability to add middlewares to Vite dev server (or similar extensibility)

### ISSUE THREAD

**Issue by mattdsteele** [angular/angular-cli#25777]
### Command

serve

### Description

With the goal to move off the Webpack-based development server, we have a need to port some of the functionality currently supported by the `@angular-builders/custom-webpack` module.

In particular, we would like the ability to add custom middlewares to the dev server. In our case, this would be used to inject a connect-compatible middleware that acts as a means of providing authenticated access to proxied endpoints, by setting session cookies used for authorization.

### Describe the solution you'd like

Vite's dev server currently supports proxy endpoints via an embedded `http-proxy` module, and provides documentation on [customizing with additional middlewares](https://vitejs.dev/config/server-options.html#server-proxy):

> In some cases, you might also want to configure the underlying dev server (e.g. to add custom middlewares to the internal [connect](https://github.com/senchalabs/connect) app). In order to do that, you need to write your own [plugin](https://vitejs.dev/guide/using-plugins) and use [configureServer](https://vitejs.dev/guide/api-plugin#configureserver) function.

The `configureServer` method exposes the custom middleware hook:

```ts
const myPlugin = () => ({
  name: 'configure-server',
  configureServer(server) {
    server.middlewares.use((req, res, next) => {
      // custom handle request...
    })
  },
})
```

### Describe alternatives you've considered

Exposing direct access to the Vite API may not align with the philosophy of the Angular CLI, but supporting the extensibility via custom builders would make these use cases feasible.

I see similar requests in other issues such as https://github.com/angular/angular-cli/issues/24163 and https://github.com/just-jeb/angular-builders/issues/1288

On a side note, I'm very excited to see CLI's build process move over to Vite; I've been using it outside Angular, and have given talks about how much I've enjoyed it: https://steele.blue/vite-is-neat/

**Comment by lixaotec** [comment]
upvote

**Comment by clydin** [comment]
The ability to programmatically add middleware via a custom created builder is available in v17.  This does require the creation of a builder or for the availability of a third-party package similar to `custom-webpack` to leverage.
Please see this PR for further details: https://github.com/angular/angular-cli/pull/26212
Please note that, while available, the Angular team does not provide official support for the usage of programmatic APIs.
