### ISSUE TITLE
Install with angular 16.2.0 not working

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#25783]
### Command

add

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Just running `npm i`

### Exception or Error

```text
npm ERR! Found: @angular/compiler@16.2.0
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"16.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"16.2.3" from @angular/localize@16.2.3
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^16.0.0" from @ng-bootstrap/ng-bootstrap@15.1.1
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"15.1.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

### Your Environment

```text
N/A
```

**Comment by alan-agius4** [comment]
The error is stating that you have `@angular/compiler@16.2.0` installed but `@angular/compiler@16.2.3` is needed.

**Comment by gsebastianlopezillia** [comment]
I'm having the same issue, my project was working perfect, I do not changed any package/dependency. Today I deleted the `node_modules` and the `package-lock.json` to test a clean packages installation and this error appeared just trying to execute 'npm i -SE'. It don't even create the `node_modules` dir again before it crash. I already try with `npm cache clean -f` without any positive outcome.
Error displayed by console:
  `...> npm i -SE
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vantek-web@3.0.0
npm ERR! Found: @angular/compiler@16.2.2
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"16.2.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"16.2.3" from @angular/localize@16.2.3
npm ERR! node_modules/@angular/localize
npm ERR!   peer @angular/localize@"^16.0.0" from @ng-bootstrap/ng-bootstrap@15.1.1
npm ERR!   node_modules/@ng-bootstrap/ng-bootstrap
npm ERR!     @ng-bootstrap/ng-bootstrap@"15.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!`

**Comment by advgal** [comment]
ng update @angular/cli @angular/core

solved it for me
