### ISSUE TITLE
Option to disable CommonJS/AMD warnings.

### ISSUE THREAD

**Issue by fudom** [angular/angular-cli#25784]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

In a real world applications it's impossible to 100% avoid CommonJS/AMD dependencies. Either because of need or indirect dependencies which cannot be changed.

[Docs](https://angular.io/guide/build#configuring-commonjs-dependencies)

### Proposed solution

Instead of filling the `allowedCommonJsDependencies` array, add an option to disable all warnings.

### Alternatives considered

Or allow wildcard `*` to allow all.

**Comment by alan-agius4** [comment]
> In a real world applications it's impossible to 100% avoid CommonJS dependencies

I don't really agree with this statement. Can you provide some explains of which libraries you are having trouble with? In general CJS libraries are not meant to be used in the browser.

**Comment by alan-agius4** [comment]
PRs are welcome add wildcard support.
