### ISSUE TITLE
C:\Program Files (x86)\Git\bin\sh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

### ISSUE THREAD

**Issue by ganeshkbhat** [angular/angular-cli#2579]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10
[npm-debug.zip](https://github.com/angular/angular-cli/files/517342/npm-debug.zip)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.17
node: 5.7.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
Initial Project creation. No code changes

### The log given by the failure.
> Normally this include a stack trace and some more information.
NPM Log attached

### Mention any other details that might be useful.
Just wanted to upgrade to new ng-cli to use the angular2 production release
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
In your log I'm seeing a different relevant error:
```
3450 verbose cwd c:\Edureka-V2\Module 5\m5_7_unit_tests_ng2-cli\m5_7_2_unit_tests_final\ng-tests
3451 error Windows_NT 10.0.14393
3452 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
3453 error node v5.7.0
3454 error npm  v3.6.0
3455 error code 128
3456 error Command failed: git -c core.longpaths=true clone --template=C:\Users\ganes\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\ganes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5
3456 error Cloning into bare repository 'C:\Users\ganes\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5'...
3456 error Permission denied (publickey).
3456 error fatal: Could not read from remote repository.
3456 error
3456 error Please make sure you have the correct access rights
3456 error and the repository exists.
3457 error If you need help, you may report this error at:
3457 error     <https://github.com/npm/npm/issues>
3458 verbose exit [ 1, true ]
```

We currently have a npm dependency on a git repo, and it seems that your machine has some trouble accessing it.
