### ISSUE TITLE
Experiencing a problem during the update of my Angular project from version 9 to version 10. How can I address this issue?

### ISSUE THREAD

**Issue by JeevanMahesha** [angular/angular-cli#25815]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm encountering an issue while upgrading my Angular project from version 9 to version 10. How can I resolve this problem?

![Screenshot from 2023-09-11 12-14-00](https://github.com/angular/angular-cli/assets/34814862/53f7a996-cb46-4cc1-ac58-0ebf7f64d2a6)

I have followed the below link steps to update 

https://update.angular.io/?v=9.0-10.0

### Minimal Reproduction

step 1 :-  Angular Project with version 9

step 2 :-  Update the project to version 10 (use node version v12 or greater)

step 3 :- Open this Link https://update.angular.io/?v=9.0-10.0

step 4 :- nagivate to Update to the new version

step 5:- use this command `npx @angular/cli@10 update @angular/core@10 @angular/cli@10`

now you will get the above mentioned issue

### Your Environment

```text
i have use version 9 using npx 

npx @angular/cli@10 update @angular/core@10 @angular/cli@10
```

**Comment by gowthamnb** [comment]
I'm also facing the same issue

![Screenshot from 2023-09-11 11-59-45](https://github.com/angular/angular-cli/assets/101733013/b4f44686-9333-481c-9745-d2b651be0675)

**Comment by alan-agius4** [comment]
Seems like you are hitting a very old issue. 

You'd need to disable the automatic version updates by setting the `NG_DISABLE_VERSION_CHECK` env variable to `true`

Closing, as Angular versions prior to 14 are no longer supported. See https://angular.io/guide/releases#actively-supported-versions for more information.

**Comment by JeevanMahesha** [comment]
Thanks @alan-agius4
