### ISSUE TITLE
Angular CLI is up and running event ng test --watch false after finishing

### ISSUE THREAD

**Issue by pranasblk** [angular/angular-cli#2582]
I am preparing to run Angular 2.0 app on CI and stuck with multiple issues:

- `ng test --watch false` is not quitting if test false (probably issue of Jasmine or how params passed from ng ...)
-- `ng test --watch false` can't be executed 2nd time without warnings due to stale angular-cli

e.g.

`$ ng test --browsers PhantomJS --watch false --log-level debug` is successful for the first time, but 2nd invocation causes warnings:
WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
45:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
57:15 Critical dependency: the request of a dependency is an expression
08 10 2016 15:04:16.011:WARN [karma]: Port 9876 in use
08 10 2016 15:04:16.011:INFO [karma]: Karma v1.2.0 server started at http://localhost:9877/
08 10 2016 15:04:16.011:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
08 10 2016 15:04:16.014:INFO [launcher]: Starting browser PhantomJS

 

$ ng test --browsers PhantomJS --watch false --log-level debug

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Linux 3.10 x86_64

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.16
node: 6.7.0
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Run `ng test --watch false` multiple times and observe the warnings.

### The log given by the failure.
> Normally this include a stack trace and some more information.

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
45:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
57:15 Critical dependency: the request of a dependency is an expression
08 10 2016 15:04:16.011:WARN [karma]: Port 9876 in use

### Mention any other details that might be useful.
It would be great to have some README for CI set-up on the head-less linux.

Thanks!

**Comment by filipesilva** [comment]
I just ran it 3 times in a row with Chrome and it seems to be fine:

```
kamik@T460p MINGW64 /D/sandbox/master-proj (master)
$ ng test --watch false
10 10 2016 11:23:50.874:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
10 10 2016 11:23:50.877:INFO [launcher]: Launching browser Chrome with unlimited concurrency
10 10 2016 11:23:50.897:INFO [launcher]: Starting browser Chrome
10 10 2016 11:23:52.264:INFO [Chrome 53.0.2785 (Windows 10 0.0.0)]: Connected on socket /#lXfs-Nm-9HdJe9YAAAAA with id 44124239
Chrome 53.0.2785 (Windows 10 0.0.0): Executed 3 of 3 SUCCESS (0.178 secs / 0.173 secs)

kamik@T460p MINGW64 /D/sandbox/master-proj (master)
$ ng test --watch false
10 10 2016 11:25:44.512:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
10 10 2016 11:25:44.516:INFO [launcher]: Launching browser Chrome with unlimited concurrency
10 10 2016 11:25:44.573:INFO [launcher]: Starting browser Chrome
10 10 2016 11:25:45.934:INFO [Chrome 53.0.2785 (Windows 10 0.0.0)]: Connected on socket /#67JqrPKNIiiz022nAAAA with id 46346074
Chrome 53.0.2785 (Windows 10 0.0.0): Executed 3 of 3 SUCCESS (0.22 secs / 0.211 secs)

kamik@T460p MINGW64 /D/sandbox/master-proj (master)
$ ng test --watch false
10 10 2016 11:26:10.844:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/
10 10 2016 11:26:10.847:INFO [launcher]: Launching browser Chrome with unlimited concurrency
10 10 2016 11:26:10.947:INFO [launcher]: Starting browser Chrome
10 10 2016 11:26:12.225:INFO [Chrome 53.0.2785 (Windows 10 0.0.0)]: Connected on socket /#NAh6bPrWuZfZzlSDAAAA with id 48484382
Chrome 53.0.2785 (Windows 10 0.0.0): Executed 3 of 3 SUCCESS (0.169 secs / 0.162 secs)
```

Might be a PhantomJS issue, which overall is discouraged for Angular apps: https://github.com/angular/angular-cli/issues/132
