### ISSUE TITLE
ng2-material installation failed {typings: not found}

### ISSUE THREAD

**Issue by leoX2848** [angular/angular-cli#2583]
I am using latest version of angular-cli and i tried to install ng2-material am getting the following error.

zerocool@leox:~/workspace/workout/MaterialTest$ sudo npm install --save ng2-material @angular2-material/core
sudo: unable to resolve host leox
[sudo] password for zerocool: 

> ng2-material@0.6.1 postinstall /home/zerocool/workspace/workout/MaterialTest/node_modules/ng2-material
> typings install

sh: 1: typings: not found
material-test@0.0.0 /home/zerocool/workspace/workout/MaterialTest
+-- UNMET PEER DEPENDENCY @angular/common@2.0.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0
`-- @angular2-material/core@2.0.0-alpha.8-2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
npm WARN @angular2-material/checkbox@2.0.0-alpha.6 requires a peer of @angular/forms@^0.1.0 but none was installed.
npm WARN grunt-sass@1.2.1 requires a peer of grunt@>=0.4.0 but none was installed.
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "ng2-material" "@angular2-material/core"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! ng2-material@0.6.1 postinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ng2-material@0.6.1 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-material package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-material
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-material
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zerocool/workspace/workout/MaterialTest/npm-debug.log

**Comment by Meligy** [comment]
ng2-material seems like an unofficial try to implement Material in Angular 2. Their Github READM showing in their [NPM page](https://www.npmjs.com/package/ng2-material) has all tests broken.

The official Angular 2 Material package is called `@angular/material`.

For learning how to use the official Angular 2 Material check:
https://github.com/angular/material2/blob/master/GETTING_STARTED.md

## Apart from that

Assuming you do mean to install those particular packages you mentioned...

The problem seems to be that the package has a `postinstall` script that runs `typings install`. In that case, the package itself should have mentioned that it's dependent on `typings`, otherwise, it might be expecting you to have `typings` installed globally.

Either way, this wouldn't be a CLI issue.

**Comment by leoX2848** [comment]
The problem am facing with the official Material 2 is i can't find anything like Responsive grid layout

**Comment by Meligy** [comment]
That's alright. The other thing is that this seems to be a problem with ng2-material requiring typings. You can install typings manually and solve the ng2-material specific problem. This is not Angular CLI issue.

typings was a CLI package manager for TypeScript definitions. Now there's an official way to load these in TypeScript 2 that uses NPM, and doesn't need typings. The Angular CLI uses TypeScript 2. You can still install typings manually and point to the typings-installed definitions from your tsconfig. But all of that is not an Angular CLI  issue.

**Comment by filipesilva** [comment]
Libraries really shouldn't have a `postinstall: typings install` hook - it messes with consumers. There isn't anything that can be done on the CLI side about it.
