### ISSUE TITLE
Hi to get ssr running on a vm i need to upload the whole angular project instead of just the dist

### ISSUE THREAD

**Issue by justintim-es** [angular/angular-cli#25842]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

somehow the main.js throws a module not found if not the whole project is uploaded

### Minimal Reproduction

ng new buschug
ng build && ng run buschug:server

and try to host the application on a vm like ubuntu with systemd

### Your Environment

```text
ngular CLI: 15.1.6
Node: 16.18.0
Package Manager: npm 8.19.2
OS: linux x64

Angular: 15.2.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.9
@angular-devkit/build-angular   15.2.9
@angular-devkit/core            15.2.9
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@nguniversal/builders           15.2.1
@nguniversal/express-engine     15.2.1
@schematics/angular             15.1.6
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
