### ISSUE TITLE
Why "ng build" does not allow to generate group-writeable JS files ?

### ISSUE THREAD

**Issue by rivaros** [angular/angular-cli#25864]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

So here is part of result generated by "ng build". As you can see some files (like fonts and .css) have 664 permissions while
.js files have 644 permissions.

Umask of the user who was running "ng build" is 0002, so it permits to set writeable permission on group.

But Angular CLI seems to follow its own rules. Did not find a single doc on how to manage those permissions, and why .js files are treated differently from other assets. Stackoverflow was also parsed.

Pls help. Thanks.

```
-rw-rw-r--+ 1 ubuntu ubuntu  143258 Sep 19 09:34 MaterialIcons-Regular.4674f8ded773cb03e824.eot
-rw-rw-r--+ 1 ubuntu ubuntu  128180 Sep 19 09:34 MaterialIcons-Regular.5e7382c63da0098d634a.ttf
-rw-rw-r--+ 1 ubuntu ubuntu   57620 Sep 19 09:34 MaterialIcons-Regular.83bebaf37c09c7e1c3ee.woff
-rw-rw-r--+ 1 ubuntu ubuntu   44300 Sep 19 09:34 MaterialIcons-Regular.cff684e59ffb052d72cb.woff2
-rw-r--r--+ 1 ubuntu ubuntu   64988 Sep 19 09:34 polyfills-es2015.96cf669d6558fc641fed.js
-rw-r--r--+ 1 ubuntu ubuntu  162999 Sep 19 09:34 polyfills-es5.f8b560c2c61273df20bc.js
-rw-r--r--+ 1 ubuntu ubuntu    4324 Sep 19 09:34 runtime-es2015.3904e29b540996506cfd.js
-rw-r--r--+ 1 ubuntu ubuntu    4321 Sep 19 09:34 runtime-es5.3904e29b540996506cfd.js
-rw-rw-r--+ 1 ubuntu ubuntu  297681 Sep 19 09:34 styles.6723eb84e56b0055b1e6.css
-rw-r--r--+ 1 ubuntu ubuntu  716915 Sep 19 09:34 vendor-es2015.a078f9fc60e4c96e08e8.js
```

### Minimal Reproduction

build any simple angular project

### Your Environment

```text
Angular CLI: 11.2.11
Node: 12.14.0
OS: linux x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router, upgrade
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.11
@angular-devkit/build-angular      0.1102.11
@angular-devkit/core               11.2.11
@angular-devkit/schematics         11.2.11
@angular/cdk                       11.2.11
@angular/cli                       11.2.11
@angular/material                  11.2.11
@angular/material-moment-adapter   11.2.11
@schematics/angular                11.2.11
@schematics/update                 0.1102.11
rxjs                               6.6.7
typescript                         4.1.5
```

**Comment by JoostK** [comment]
Does this reproduce using latest Angular, i.e. Angular 16? Angular 11 is several years old and no longer supported.

**Comment by alan-agius4** [comment]
As @JoostK mentioned version 11 is not longer under support. Please see: https://angular.io/guide/releases#actively-supported-versions

What is worth the JS and CSS files are written to disk directly by webpack. Thus, we don’t control mode/permission of the create files.

**Comment by rivaros** [comment]
@alan-agius4 thanks for response. Yes, I know about supported versions but unfortunately that's legacy code of my colleague. Had to debug and figured out the problem was in that piece of code

```
    static copyEntryContent(entry, dest) {
        copy_file_1.copyFile(typeof entry === 'string' ? entry : entry.path, dest);
        if (process.platform !== 'win32') {
            // The cache writes entries as readonly and when using copyFile the permissions will also be copied.
            // See: https://github.com/npm/cacache/blob/073fbe1a9f789ba42d9a41de7b8429c93cf61579/lib/util/move-file.js#L36
            fs.chmodSync(dest, 0o644);
        }
    }
```

Angular 11 was using bundle cache (`node_modules/.cache`)   and when copying files from there ) which all were chmodede as r--r--r--, it was applying the 644 permissions.  In such way umask was simply ignored :)

Looks like version 16 is not using bundle cache.
