### ISSUE TITLE
State of 'deployUrl' option going forward

### ISSUE THREAD

**Issue by rakNeoQOWS101** [angular/angular-cli#25866]
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Are we still planning on deprecating the 'deployUrl' option, given the issues it presents, even after considering the alternative approach suggested by the Angular Team? @th0r has provided a detailed explanation of these concerns in the post https://github.com/angular/angular-cli/issues/22113.

https://github.com/angular/angular-cli/issues/22113#issuecomment-1036333580

The alternative approach to deployURL appears to require some cumbersome workarounds.

Could we potentially keep it as a flag-based solution? Those who want to use it can enable it, while others can choose not to.

### Minimal Reproduction

NA

### Exception or Error

```text
NA
```

### Your Environment

```text
Angular 15
```

**Comment by alan-agius4** [comment]
Hi, 

Please see official response https://github.com/angular/angular-cli/issues/22113#issuecomment-1099723870
> We are still planning to remove `deployUrl` eventually largely because of all the confusion it causes. The exact version it gets dropped is still TBH, but I can confidently say it will _not_ be removed in v14, so this shouldn't be an immediate problem for anyone. The blog post in particular should hopefully help address common use cases which have used `deployUrl` in the past and how we recommend moving forward for each of them. We're not expecting any existing use cases to suddenly become unsupported, just that the right approach for you will probably vary by your particular requirements.



It is also worth mentioned that `deployUrl` is not available in modern build pipeline which uses esbuild.
