### ISSUE TITLE
Implement module alias resolution in esbuild-based browser application builder

### ISSUE THREAD

**Issue by DallasHoff** [angular/angular-cli#25863]
### Command

build

### Description

I am working a project that uses the CesiumJS library which imports some built-in Node.js packages such as `zlib` and `http`. Initially, we would get the following error when trying to build the project.

`./node_modules/@cesium/engine/Source/Core/Resource.js:1864:30-44 - Error: Module not found: Error: Can't resolve 'zlib' in '.\node_modules\@cesium\engine\Source\Core'`

We fixed this under the Webpack 5-based builder by installing polyfills for the Node.js packages that CesiumJS requires and referencing them in the `tsconfig.json` like so.

```json
{
  "compilerOptions": {
    ...
    "paths": {
      "url": ["node_modules/url"],
      "http": ["node_modules/stream-http"],
      "https": ["node_modules/https-browserify"],
      "zlib": ["node_modules/browserify-zlib"],
      "stream": ["node_modules/stream-browserify"],
      "util": ["node_modules/util"],
      "assert": ["node_modules/assert"]
    }
  }
}
```

We are now trying out the esbuild-based builder, and `ng build` throws a similar error to what the Webpack builder did before.

`[ERROR] Could not resolve "zlib" node_modules/@cesium/engine/Source/Core/Resource.js:1864:37`

Note that `ng serve` does work. This error only happens under `ng build`.

### Describe the solution you'd like

It seems that the esbuild-based builder does not take into account the module aliases specified in the TypeScript config in the same way the Webpack-based builder did. This feature should be considered for addition to the new builder.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in version 17 which is currently in prerelease.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
