### ISSUE TITLE
ng serve ignores public-host when live reload disabled

### ISSUE THREAD

**Issue by shawnweeks** [angular/angular-cli#25874]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

For the test I setup an /etc/hosts entry for test.example.local pointing at 127.0.0.1 to simulate running ng serve behind a reverse proxy.

When running ng serve behind a reverse proxy where the public-host is not localhost you will receive and invalid host header if you disable live reload with `--no-live-reload` or `--live-reload=false`

### Minimal Reproduction

Add an /etc/hosts entry for test.example.local then run the following.

```shell
ng new public-host-test # Use all default options
cd public-host-test
ng serve --public-host test.example.local --no-live-reload
```

Then open a browser and try to access the app at `http://test.example.local:4200` where you'll notice the `Invalid Host header` error, if I leave live reload enabled this all works fine. I've confirmed this behavior on MacOS and RHEL 8. 

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.2.3
Node: 16.18.0
Package Manager: npm 9.6.5
OS: darwin arm64

Angular: 16.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.2.3
@angular/cli                    16.2.3
@schematics/angular             16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
