### ISSUE TITLE
Karma/Jasmine tests don't run after upgrading from Angular 14 to 15

### ISSUE THREAD

**Issue by ilyakonrad** [angular/angular-cli#25885]
### Command

test

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

14

### Description

After upgrading from Angular 14 to Angular 15, my Karma unit tests don't run anymore.
I have 10 on them, so I used to see `Executed 10 of 10 SUCCESS`, now I see `Executed 0 of 0 SUCCESS`.

I noticed that the upgrade removed few lines of code in `test.ts` but bringing them back doesn't help.

<img width="615" alt="image" src="https://github.com/angular/angular-cli/assets/25200186/d483a91e-87c3-467f-91c0-dcaa837eb32a">

[Playing around with `includes` property](https://stackoverflow.com/questions/74890907/after-migration-to-angular-15-context-was-removed-from-test-ts) in `angular.json` didn't help.

[This gentleman's solution](https://github.com/angular/angular-cli/issues/24389#issuecomment-1342861688) didn't help me either.

### Minimal Reproduction

1. Upgrade from 14 to 15.
2. Question life choices.

### Your Environment

```text
Angular CLI: 15.2.9
Node: 18.12.1
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 15.2.9
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1502.9
@angular-devkit/build-angular      15.2.9
@angular-devkit/core               15.2.9
@angular-devkit/schematics         15.2.9
@angular/cdk                       14.2.7
@angular/fire                      7.5.0
@angular/material                  14.2.7
@angular/material-moment-adapter   14.2.7
@schematics/angular                15.2.9
rxjs                               7.8.0
typescript                         4.8.4
webpack                            5.76.0
```

### Anything else relevant?

Here's my `tsconfig.spec.ts`

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "downlevelIteration": true,
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

Here's my test config in `angular.json`
```
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "preserveSymlinks": true,
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [],
            "styles": ["src/styles.css"],
            "assets": ["src/assets", "src/favicon.ico", "src/manifest.webmanifest"]
          }
        }
```

Here's my Karma config
```
// Karma configuration file, see link for more information
// https://karma-runner.github.io/1.0/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular-devkit/build-angular'],
    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-junit-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular-devkit/build-angular/plugins/karma')
    ],
    client:{
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: [ 'html', 'lcovonly' ],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'test'
    },
    reporters: ['progress', 'kjhtml'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false,
    junitReporter: {
      outputDir: process.env.TEST_RESULTS,
      outputFile: 'karma-results.xml',
      useBrowserName: false
    },
  });
};
```

Here's one of my tests
```
/* eslint-disable max-classes-per-file */

import { TestBed, waitForAsync, ComponentFixture } from '@angular/core/testing'
import { ActivatedRoute } from '@angular/router'
import { By } from '@angular/platform-browser'
import { BrowserAnimationsModule } from '@angular/platform-browser/animations'
import { TranslateModule } from '@ngx-translate/core'
import { Store } from '@ngxs/store'
import { Observable, of } from 'rxjs'

import { SharedModule } from '../../shared/modules/shared.module'
import { AuthService } from '../../core/services'
import { LoginComponent } from './login.component'
import { PhoneNumberModule } from '../../shared/modules/phone-number/phone-number.module'
import { Organization } from '../../core/interfaces/organization/organization'

describe('LoginComponent', () => {
  let fixture: ComponentFixture<LoginComponent>
  let fakeAuthService: AuthService

  class ActivatedRouteMock {
    queryParams = new Observable((observer) => {
      const urlParams = { redirectTo: '' }
      observer.next(urlParams)
      observer.complete()
    })
  }

  class StoreMock {}

  beforeEach(waitForAsync(() => {
    fakeAuthService = jasmine.createSpyObj<AuthService>('AuthService', {
      loginAdminDashboard: of({ clubs: [{ name: 'Organization' } as Organization], sponsors: [] })
    })

    TestBed.configureTestingModule({
      declarations: [LoginComponent],
      imports: [TranslateModule.forRoot(), BrowserAnimationsModule, SharedModule, PhoneNumberModule],
      providers: [
        { provide: ActivatedRoute, useClass: ActivatedRouteMock },
        { provide: Store, useClass: StoreMock },
        { provide: AuthService, useValue: fakeAuthService }
      ]
    }).compileComponents()

    fixture = TestBed.createComponent(LoginComponent)
    fixture.detectChanges()
  }))

  it('submits the form succesfully', () => {
    fixture.componentInstance.loginForm.patchValue({
      phoneCountryCode: '+47',
      phoneMobile: '91910101',
      password: 'password'
    })

    const form = fixture.debugElement.query(By.css(`[data-testid="form"]`))
    form.triggerEventHandler('ngSubmit')

    expect(fakeAuthService.loginAdminDashboard).toHaveBeenCalled()
  })

  it(`does not submit the form when it's not valid`, () => {
    fixture.componentInstance.loginForm.patchValue({
      phoneCountryCode: '+47',
      phoneMobile: '',
      password: ''
    })

    const form = fixture.debugElement.query(By.css(`[data-testid="form"]`))
    form.triggerEventHandler('ngSubmit')

    expect(fakeAuthService.loginAdminDashboard).not.toHaveBeenCalled()
  })
})
```

**Comment by alan-agius4** [comment]
What's the configured value of `root` and `sourceRoot` in your `angular.json`?

**Comment by alan-agius4** [comment]
And you spec files are located in `src`?

**Comment by ilyakonrad** [comment]
> And you spec files are located in `src`?

Sure.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by peperutka** [comment]
This helped me, to fix the issue, which you are dealing:
https://stackoverflow.com/questions/75429368/angular-update-from-14-to-version-15-and-now-ng-test-gets-no-specs-found/75429763#75429763

**Comment by ilyakonrad** [comment]
> This helped me, to fix the issue, which you are dealing: https://stackoverflow.com/questions/75429368/angular-update-from-14-to-version-15-and-now-ng-test-gets-no-specs-found/75429763#75429763

This got me one step further, it's 12 tests now (not 0, but weirdly not 10) but there's an error `Unhandled promise rejection: Error: NG0205: Injector has already been destroyed.`.

I guess I'll have to create a reproduction, but thanks for your comment anyway.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by ilyakonrad** [comment]
I was going to create a repro soon, don't have time now 😞

**Comment by alan-agius4** [comment]
Feel free to open another issue once you have a reproduction.

**Comment by ilyakonrad** [comment]
I solved the issue while trying to create a reproduction, classic 😏 
When generating a new app, I noticed some differences between what cli generated and my ancient setup.
I updated my app to match the newer setup and had to fix a few issues along the way.
