### ISSUE TITLE
angular-cli deploy to ftp with assets

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular-cli#2589]
Hi, very simple question here,

I would like to deploy my app via FTP. Which folders do I need to upload after it is built to `dist`?

I cannot upload just the `dist` folder because it does not contain my `assets`.

Do I need to upload my `dist` AND my `src` folder? The `src` folder contains the `assets` folder

It seems redundant if I have to upload my `dist` and the source JS files no?

**Comment by deebloo** [comment]
@dolanmiu everything you need should be in the dist folder. your assets should also be copied over based on the assets directory you define in your angular-cli.json file

**Comment by dolanmiu** [comment]
Are you sure?

![screen shot 2016-10-08 at 17 46 09](https://cloud.githubusercontent.com/assets/2917613/19214585/2970a418-8d7f-11e6-8906-c2ffd7ba540b.png)

Here is my `angular-cli.json`:

https://github.com/dolanmiu/qmtis-website/blob/master/angular-cli.json#L10

**Comment by dolanmiu** [comment]
Sorry, yeah I'm dumb, forgot to add `--prod` after `ng build`

`ng build --prod` fixes the issue

**Comment by dolanmiu** [comment]
Having said that.. the `favicon.ico` isnt copied over

**Comment by asaph26** [comment]
@dolanmiu This an open issue with the angular-cli that is not resolved yet. You have to copy the files manually or through a script.

More info here. https://github.com/angular/angular-cli/issues/2137

**Comment by dolanmiu** [comment]
I think the release today (`beta-17`) fixes this issue. I haven't used it yet, but from reading the commit history, I can see:

https://github.com/angular/angular-cli/compare/v1.0.0-beta.17...master#diff-ee1c44b86beb3967c38917e8b61c031aR12

**Comment by filipesilva** [comment]
@dolanmiu that commit does fix it, but was not included in beta.17. Should be in the next version.

**Comment by ElanMu** [comment]
I meet the same problem! 

My ng version id Beta.17 and I miss pictures in assets file after using "ng build --prod".

[
![image](https://cloud.githubusercontent.com/assets/22315478/19545667/b123156e-96ba-11e6-8dbf-757756105716.png)
](url)

[
![image](https://cloud.githubusercontent.com/assets/22315478/19545679/c5c44c18-96ba-11e6-8a7c-eb4e00e1e62d.png)
](url)

[
![image](https://cloud.githubusercontent.com/assets/22315478/19545689/d35b8fa8-96ba-11e6-8974-0238e2fb7ce1.png)
](url)


where is the problem?
