### ISSUE TITLE
Debugging Angular library not possible in application through `npm link`

### ISSUE THREAD

**Issue by twilker** [angular/angular-cli#25907]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a standard Angular 16 library and application in two different workspaces / repositories. I link the build library using `npm link` to the application and start it. I would expect to be able to debug the library sources from the application. But it does not work, as it can only debug to the level of the library.mjs. I have tested it with the chrome devtools and VSCode.

### Minimal Reproduction

1. Clone the minimal [app](https://github.com/twilker/vs-debug-angular-app) and [library](https://github.com/twilker/vs-debug-angular-library)
2. In the library project execute
```
npm i
npm run build
cd ./dist/library
npm link
```
3. In the app project execute
```
npm i
npm link library
```
4. Set breakpoint in app.component.ts L12
5. Start Debugging (F5)
6. Step Into -> leads to library.mjs although a source map exists for this file which would lead to the .ts source file
![mjs-not-resolved](https://github.com/angular/angular-cli/assets/2802526/00f385de-a914-40ea-a0e7-06cfd85bda5f)

### Exception or Error

See above

### Your Environment

```text
Angular CLI: 16.2.3
Node: 18.17.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 16.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.2.3
@angular/cli                    16.2.3
@schematics/angular             16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

### Anything else relevant?

I have opened another issue for VSCode [here](https://github.com/microsoft/vscode-js-debug/issues/1823). But as it does not work in VSCode and Chrome devtools I assumed the issue is with the Angular setup.

**Comment by alan-agius4** [comment]
This is working as expected.

Since you are using `npm link` you need to enable vendor sourcemaps, in your application build. 

See: https://angular.io/guide/workspace-config#source-map-configuration

**Comment by twilker** [comment]
I am sorry. My mistake. I assumed that `"sourceMap": true` automatically sets vendor to true too.
