### ISSUE TITLE
MacOS ZSH terminal stuck due to ng completion script

### ISSUE THREAD

**Issue by LennonReid** [angular/angular-cli#25910]
### Command

lint

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm an Angular developer and rely on Nx as my monorepo management tool. Lately, I've encountered an issue where the Nx Console doesn't function as expected. Simultaneously, I've been experiencing a slow initiation of the terminal in VSCode, accompanied by the error message 'Resolving shell environment fails.'

This situation prompted me to investigate the possibility of a problem with the environment variables in my .zshrc configuration file. Upon reviewing my user configuration, I suspect that a particular command in my bash file may be causing these issues. I can't recall when I added that command, but I noticed a significant improvement after either removing or commenting out that particular line.

I've come across a related issue on GitHub at https://github.com/angular/angular-cli/issues/25608. Unfortunately, the discussion there seems a bit confusing, and I'm unable to add any comments.

As a result, I've created a new issue to address this problem and offer a solution. This way, we can help others who might be facing the same issue.

### Minimal Reproduction

Open a new Window on MacOs and this will continue for about 2 minutes. <img width="585" alt="image" src="https://github.com/angular/angular-cli/assets/43192276/0171138b-110e-423a-b994-91c9e8e691c3">
Here is the related bash config 

```bash

...
# Load Angular CLI autocompletion.
source <(ng completion script)
...
```

### Your Environment

```text
OS:MacOS Ventura 13.5.2 (Macbook Air Apple M1)
The result after running `ng version`:
Angular CLI: 16.2.4
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1602.4 (cli-only)
@angular-devkit/core         16.2.4 (cli-only)
@angular-devkit/schematics   16.2.4 (cli-only)
@angular/cli                 16.2.4 (cli-only)
@schematics/angular          16.2.4 (cli-only)
```

**Comment by LennonReid** [comment]
I found a solution in https://stackoverflow.com/questions/50194674/ng-completion-no-longer-exists 
```bash

# Load Angular CLI autocompletion.
# source <(ng completion script)
NG_COMMANDS="add build config doc e2e generate help lint new run serve test update version xi18n"
complete -W "$NG_COMMANDS" ng
```
It works, but I'm unsure of the underlying rationale.
Is there an alternative solution that might be more effective?

**Comment by alan-agius4** [comment]
The above ZSH config disables the provided autocompletion for commands and options for the Angular CLI. Instead uses ZSH completion system which completes a limited set of declared commands and completion for options is not available.

What's your global Angular CLI version?

**Comment by LennonReid** [comment]
My global Angular CLI Version is 16.2.4.

```bash
Angular CLI: 16.2.4
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1602.4 (cli-only)
@angular-devkit/core         16.2.4 (cli-only)
@angular-devkit/schematics   16.2.4 (cli-only)
@angular/cli                 16.2.4 (cli-only)
@schematics/angular          16.2.4 (cli-only)
```

**Comment by alan-agius4** [comment]
What happens when you run `ng completion script` in your terminal?

**Comment by LennonReid** [comment]
This is what it shows now.
```bash
$ ng completion script
#compdef ng
###-begin-ng-completions-###
#
# yargs command completion script
#
# Installation: ng completion >> ~/.zshrc
#    or ng completion >> ~/.zprofile on OSX.
#
_ng_yargs_completions()
{
  local reply
  local si=$IFS
  IFS=$'
' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" ng --get-yargs-completions "${words[@]}"))
  IFS=$si
  _describe 'values' reply
}
compdef _ng_yargs_completions ng
###-end-ng-completions-###

(base) 

````

**Comment by alan-agius4** [comment]
@LennonReid, unfortunately I am not able to reproduce this.

**Comment by LennonReid** [comment]
Thank you, Alan, for your time. This isn't an urgent matter, so I'll go ahead and close it. If someone encounters a similar issue in the future, please don't hesitate to open a new ticket.
