### ISSUE TITLE
angular-cli installation fails in windows 10 with error code ENOENT and error no 4058

### ISSUE THREAD

**Issue by hi2suresh** [angular/angular-cli#2591]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
c:\learn\javascript\angular2naga>node --version
v6.7.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
npm install -g angular-cli

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be usc:\learn\javascript\angular2naga>npm install -g -f angular-cli
npm WARN using --force I sure hope you know what you are doing.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
C:\Users\Dell\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "-f" "angular-cli"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! path C:\Users\Dell\AppData\Roaming\npm\node_modules\.staging\abbrev-6fa77d19
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Dell\AppData\Roaming\npm\node_modules\.staging\abbrev-6fa77d19' -> 'C:\Users\Dell\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Dell\AppData\Roaming\npm\node_modules\.staging\abbrev-6fa77d19' -> 'C:\Users\Dell\AppData\Roaming\npm\node_modules\angular-cli\node_modules\npm\node_modules\abbrev'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     c:\learn\javascript\angular2naga\npm-debug.log
npm ERR! code 1eful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Dupe of #1190
