### ISSUE TITLE
Support multi-project workspaces with jest and karma tests

### ISSUE THREAD

**Issue by johncrim** [angular/angular-cli#25919]
### Command

test

### Description

Today one can run `ng test` to run tests across all projects with a configured `test` builder, or `ng test <project>` to run tests in a single project. However if the monorepo contains projects with both jest and karma tests it gets pretty clunky to run both. 

As Angular moves toward multiple test builders there should be support for running all tests globally for select types of tests.

### Describe the solution you'd like

Ideally `ng test` would run all tests across all projects using all configured test builders, and it would be possible to configure multiple test builders for a single project. And then it would be possible to only run tests for a single test builder using a property, like `ng test --runner=karma`, where the runner value is defined by the builder.

### Describe alternatives you've considered

The following can be added to angular.json for each project:
```json
"projects": {
    "mylib": {
      "projectType": "library",
      "root": "projects/mylib",
      "sourceRoot": "projects/mylib/src",
      "prefix": "lib",
      "architect": {
        "build": {
...
        },
        "test-karma": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "tsConfig": "projects/mylib/tsconfig.karma-spec.json",
            "polyfills": [
              "zone.js",
              "zone.js/testing"
            ],
            "include": [
              "**/*.karma-spec.ts"
            ],
            "codeCoverageExclude": [
              "**/*.jest-spec.ts"
            ]
          }
        },
        "test-jest": {
          "builder": "@angular-devkit/build-angular:jest",
          "options": {
            "tsConfig": "tsconfig.jest-spec.json",
            "polyfills": [
              "zone.js",
              "zone.js/testing"
            ],
            "include": [
              "**/*.jest-spec.ts"
            ]
          }
        }
      }
    },
```

Such a configuration supports 2 test builders for the project, so `ng mylib:test-karma` and `ng mylib:test-jest` works, but I can no longer `ng test` to run all tests in the workspace. Of course I could avoid leave one of the builder using `test` in all my projects, but it is still a limitation. 

The current lines in my package.json would have to be updated for each new project. The following is required for only 2 projects, and it would get unwieldy for 15-20 projects:

```json
  "scripts": {
    "test:karma": "ng run mylib:test-karma --watch false && ng run myapp:test-karma --watch false",
    "test:jest": "NODE_NO_WARNINGS=1 ng run mylib:test-jest && NODE_NO_WARNINGS=1 ng run myapp:test-jest"
```

This project (checkout the `dev/jest` branch) provides an example:
https://github.com/johncrim/ng16-yarn-pnp/tree/dev/jest

(Note also that running `yarn test:jest` runs all the jest tests 2x, presumably because the `tsconfig.jest-spec.json` references test files from multiple projects. Obviously this can be fixed with tsconfig files in each project)

**Comment by alan-agius4** [comment]
`ng test` already runs the tests of all the projects in the workspace.

I am not really understanding the rational behind someone wanting to have have multiple tests runners configured in the project. Can you please elloborate on this? 

While the Angular CLI is indeed moving providing multiple test runner. We don't recommend using multiple runners in the same project.

**Comment by johncrim** [comment]
We have used jest and karma together for years. We use jest for simpler, javascript-only tests - pure unit tests. We use karma for browser-integration tests - where the interaction between the code and the browser matters, and we want to test against multiple browsers - eg where CSS or positioning matters, or when using IndexedDb. In our experience it's useful to be able to use both types of tests within a single project. To put it another way, it's similar to dividing tests between karma and e2e - they work best for different layers of the test pyramid.

The sample project I referenced above just shows both kinds of tests in the same project - it is not an example of why we would partition tests between jest and karma.

We follow the Angular recommendation of placing test files in the same folder as the classes under test - this practice increases the need for selecting different test types and configuring multiple runners for a single project. I think it's generally a nice practice for code organization, but if we moved our tests of a certain flavor to a different project we would be able to run them all using `ng test`, though we would lose the benefit of having tightly coupled code close together.

Lmk if that makes sense or if you'd like further explanation. We're excited about using the jest builder, because handling the jest configuration ourselves (even with the help of `jest-preset-angular`) has been a fragile mess and often breaks during upgrades; and the approach taken by the new builder of using esbuild before running seems superior and more performant.

**Comment by alan-agius4** [comment]
Hi @johncrim, 

Thanks for opening the issue and the going in such a detailed explanation.  Whist having 2 tests runners might make sense in your use-case I believe this is rather uncommon. 

In addition, the implementation of this feature is also non trivial and does not fall in our current roadmap. Thus, let's re-consider this feature in the future if we see the more community users are running multiple unit tests frameworks in the same project.
