### ISSUE TITLE
unable to check angular version with node hydrogen version

### ISSUE THREAD

**Issue by dev-rajat-bacancy** [angular/angular-cli#25915]
### Command

add, build, config, doc, e2e, extract-i18n, generate, help, lint, new, other, run, serve, test, update, version

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

node 18.12.1

### Description

![image](https://github.com/angular/angular-cli/assets/144689525/778ad759-ed2c-43e1-925e-14fb836e4b1a)

![image](https://github.com/angular/angular-cli/assets/144689525/1d971e92-2962-459a-bcb3-06146cba85ef)

When I update to latest node version 18.18.0 all angular command is not working for any of my angular project.
When I am using 18.12.0 everything was working fine.

### Minimal Reproduction

hit any of **ng** command I am facting this issue

### Your Environment

```text
after executing any command that start from ng I'm getting this which opens new terminal.

-----Mg: version                          (fundamental)----All-------------------
(New file)
```

**Comment by JeanMeche** [comment]
You'll have to install the angular cli for that version of Node also. (with `nvm` globals are shared accros version).

**Comment by dev-rajat-bacancy** [comment]
![image](https://github.com/angular/angular-cli/assets/144689525/839bdf18-87a4-4891-babf-d732633120e3)


Here you can see but I have latest node version install the latest angular version locally
but still It is not resolved when I hit the ng new command I am getting this error

![image](https://github.com/angular/angular-cli/assets/144689525/deb8fc11-eeb2-4705-aeaf-b2b782a080aa)


@JeanMeche you can see this in the above image

**Comment by JeanMeche** [comment]
You didn't do a global install of the CLI (-g). 

if you type in `which ng`, you'll see that you're not pointing to the Angular CLI but the Mg editor (which has an alias on `ng`).

**Comment by dev-rajat-bacancy** [comment]
okay I got your point. I will try and update you. It is working on not. 
Pleasure to meet you @JeanMeche

**Comment by dev-rajat-bacancy** [comment]
![image](https://github.com/angular/angular-cli/assets/144689525/aa67a0b4-4bd7-42d3-8406-2c95fbea62d7)

@JeanMeche still same thing is there.

can we connect on google meet 😂😂😂 ( https://meet.google.com/hks-juaa-ppx )

**Comment by dev-rajat-bacancy** [comment]
@JeanMeche thanks !!! It's working fine now

I want to know about mg Editior. Please guide me
