### ISSUE TITLE
Enable a way to update packages that depend on Angular when `ng update` is ran

### ISSUE THREAD

**Issue by rcsilva83** [angular/angular-cli#25920]
### Command

update

### Description

On an Angular application we always use packages that depend on Angular, like `ng-bootstrap`. These libraries often have specific versions for each Angular version. In the case o `ng-bootstrap`, you have to use v14.x.x for Angular 15 and v15.x.x for Angular 16, but these dependencies must be manually updated and migrated when we update Angular.

### Describe the solution you'd like

It would be awesome if `ng update` could also update and migrate code from these external packages the same way if does for Angular components. The could be done by some kind of hook, like the `install` script that gets executed for all dependencies that have it when you `npm install` your application.

This should support updating Angular to an older version (`ng update @angular/cli@15 @angular/core@15`), as it would update `ng-bootstrap` to v14 instead of v15 and execute required code migrations for this version.

**Comment by alan-agius4** [comment]
Thanks for opening this issue.

The Angular CLI already supporters migrations and updates of 3rd party libraries.

In this case it’s a a matter that `ng-bootstrap` leverages this feature by setting the appropriate peer dependency ranges and implement their own code migrations.

**Comment by rcsilva83** [comment]
> Thanks for opening this issue.
> 
> The Angular CLI already supporters migrations and updates of 3rd party libraries.
> 
> In this case it’s a a matter that `ng-bootstrap` leverages this feature by setting the appropriate peer dependency ranges and implement their own code migrations.

Thank you for your response, @alan-agius4 . Can you point me the documentation about this support? I couldn't find it and I want to point that to `ng-bootstrap` team because, even though peer dependency ranges are defined (I get warnings on `yarn install --force` after `ng update`), the library wasn't updated.
