### ISSUE TITLE
No matching version found for @angular-devkit/core@16.2.4

### ISSUE THREAD

**Issue by Potapich** [angular/angular-cli#25929]
### Command

version

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.2

### Description

npm install -g @angular/cli@latest
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/core@16.2.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Minimal Reproduction

try to install in terminal:
npm install -g @angular/cli@latest

output error is:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @angular-devkit/core@16.2.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

### Your Environment

```text
on version 16.2.2 works fine
```

**Comment by JeanMeche** [comment]
There is likely an issue with your registry. 

`16.2.4` is available on the global registry : https://www.npmjs.com/package/@angular-devkit/core/v/16.2.4
