### ISSUE TITLE
Use esbuild's support for transforming async/await to generator

### ISSUE THREAD

**Issue by segevfiner** [angular/angular-cli#25921]
### Command

build

### Description

AFAIK Angular CLI is using Babel plugins to transform async/await to generators for zone.js support as that transformation wasn't supported by esbuils. But support has been added https://github.com/evanw/esbuild/issues/2780, which you might be able to use to speed up the build.

This is just letting you know, as I requested that feature while playing around with zone.js for a different non Angular based project where I have hit this limitation of zone.js which the Angular CLI hides from you.

### Describe the solution you'd like

Use the native esbuild transform for transforming async/awaitnto generators.

**Comment by alan-agius4** [comment]
Esbuild is already used to transform a async/await to generators when using the modern builds.
