### ISSUE TITLE
ng build caches old typescript code

### ISSUE THREAD

**Issue by bruceauyeung** [angular/angular-cli#26003]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

running `ng build mylibname` faces an issue with cached utils typescript code - new changes made in vscode doesn't reflect in build results file ( open built `*.mjs` file and check with my eyes ). utils functions gets cached and even re-run `ng build mylibname` doesn't help.
Only removing folder `.angular/cache` and then re-run `ng build mylibname` helps.

related issue: https://github.com/angular/angular-cli/issues/24916

### Minimal Reproduction

after `.angular/cache` removed, this wierd problem doesn't happen again, and i can not figure out how to reproduce 

### Your Environment

```text
Angular CLI: 13.3.7
Node: 18.15.0 (Unsupported)
Package Manager: npm 9.5.0
OS: linux x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cli                    13.3.7
@schematics/angular             13.3.7
ng-packagr                      13.3.1
rxjs                            7.5.0
typescript                      4.6.2
```

**Comment by alan-agius4** [comment]
Angular version 13 is no longer supported. See: https://angular.io/guide/releases#actively-supported-versions.

Please update to a more recent version and if the problem persists please open a new issue with a minimal reproduction.
