### ISSUE TITLE
Starting with typescript 2.1.0-dev.20160907, Angular Template Compiler (ngc) does not produce a compiled app dir

### ISSUE THREAD

**Issue by kesarion** [angular/angular-cli#2600]
ngc won't produce a compiled app dir anymore, all I get is '/compiled/node_modules/@angular/', no '/compiled/app/'. Everything works fine before [typescript 2.1.0-dev.20160907](https://github.com/Microsoft/TypeScript/issues/1664#issuecomment-245340547).

### OS?
MacOS Sierra

### Versions.
@angular/compiler-cli@0.6.4
typescript@2.1.0-dev.20160907 (or later)

### Repro steps.

In '/project_root/app/' add Quickstart files:
- app.component.ts
- app.module.ts

Plus AOT style main.ts:
```
import { platformBrowser } from '@angular/platform-browser';
import { AppModuleNgFactory } from '../compiled/app/app.module.ngfactory';

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```
tsconfig.aot.json:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitHelpers": true,
    "skipDefaultLibCheck": true,
    "strictNullChecks": false,
    "outDir": "tmp"
  },
  "exclude": [
    "node_modules",
    "compiled",
    "app/main.ts"
  ],
  "angularCompilerOptions": {
    "genDir": "compiled",
    "skipMetadataEmit" : true
  }
}
```

package.json as in [quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#config-files) otherwise.

ngc -p tsconfig.aot.json

### The log given by the failure.
> Normally this include a stack trace and some more information.

No errors, it's 'successful', but no compiled app.

### Mention any other details that might be useful.
typescript 2.1.0-dev.20160907 adds async/await support for es5 target in tsconfig.

**Comment by filipesilva** [comment]
https://angular.io/docs/ts/latest/quickstart.html#!#config-files refers to the https://github.com/angular/quickstart repo, that is where you should open your issue.

The CLI supports AoT via `ng build --aot` and `ng serve --aot`, but it's still experimental.
