### ISSUE TITLE
The twitter icon in the app template should be changed to the X logo

### ISSUE THREAD

**Issue by ocombe** [angular/angular-cli#26012]
### Command

new / generate

### Is this a regression?

No

### Description

Twitter is now X (sic...), the Twitter icon in the topbar of the app template should be the X icon instead, and the alt tag should be X
![image](https://github.com/angular/angular-cli/assets/265378/48cf628c-fdba-4e00-8c64-fa1537777719)

### Minimal Reproduction

Create a new angular workspace or generate a new application

### Your Environment

```text
Angular CLI: 17.0.0-next.7
Node: 20.4.0 (Unsupported)
Package Manager: npm 9.8.1
OS: win32 x64


Angular: 17.0.0-next.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.7
@angular-devkit/build-angular   17.0.0-next.7
@angular-devkit/core            17.0.0-next.7
@angular-devkit/schematics      17.0.0-next.7
@schematics/angular             17.0.0-next.7
ng-packagr                      17.0.0-next.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by SarthakD15** [comment]
Hey, I would like to work on this. Can you please assign it to me ?

**Comment by JeanMeche** [comment]
@SarthakD15 You can open submit a PR directly !

**Comment by SarthakD15** [comment]
#26031

**Comment by SarthakD15** [comment]
Hey, I have solved the issue and raised a PR :)
Please review the PR and suggest changes if any !
