### ISSUE TITLE
Unable to copy assets: An asset cannot be written to a location path.

### ISSUE THREAD

**Issue by sercancolak** [angular/angular-cli#26010]
### Command

build

### Description

Angular CLI: 16.2.5
Node: 18.18.0
Package Manager: npm 9.8.1
OS: win32 x64

I updated my project from Angular 12 to Angular 16 version. I was able to copy my Assets to outdir this way in Angular 12. 

![image](https://github.com/angular/angular-cli/assets/10668903/04efab2e-e16d-4244-bc88-f6dae1863b2e)

But I am getting this error in Angular 16.

![image](https://github.com/angular/angular-cli/assets/10668903/cd614c5a-10ce-49fb-8199-e2f5c9de8ba0)

 Is there a solution to copy assets to outdir for Angular 16 ?

**Comment by alan-agius4** [comment]
You need to copy such assets yourself using a different tool or script.
