### ISSUE TITLE
Add standalone and functional options by default in angular.json schematics

### ISSUE THREAD

**Issue by DimitriTsikaridze** [angular/angular-cli#26025]
### Command

new

### Description

when creating app with --standalone flag I think angular.json should automatically have 
```
@schematics/angular:component": {
  "style": "scss",
  "standalone": true
},
```

also since functional guards/interceptors/resolvers are preferred way and class based guards/interceptors/resolvers are deprecated.
I think it should be set to `"functional": true` by default when generating new project.

### Describe the solution you'd like

I think default angular json schematics config when creating app with --standalone flag should have `"standalone": true` set to true on  component, directive and pipe  schematics.

also guard, interceptor and resolver schematics should have `"functional": true` because it's the preferred way now and default solutions(class based) are deprecated.

**Comment by clydin** [comment]
Both standalone and functional will be the default for new projects in the upcoming v17 version which is currently in prerelease. You can try the prereleases by using the npm `next` tag for the CLI.
