### ISSUE TITLE
Application Builder outputs contents into /[OutputPath]/browser rather than /[OutputPath/

### ISSUE THREAD

**Issue by thaoula** [angular/angular-cli#26028]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi Team.

I just updated the builder on our application from 'build-angular:browser-esbuild' -> build-angular:application. 

I now see the build output is in a subdirectory called browser.

This change will require people to update container builds or CI build configurations. Is there anyway to disable this behaviour? 

Regards,
Tarek

### Minimal Reproduction

1. Change builder 'build-angular:browser-esbuild' -> build-angular:application'
2. Build
3. Dist folder will contain a folder called browser.

### Exception or Error

```text
Dist folder is not the dist folder. The browser subfolder folder is the dist folder
```

### Your Environment

```text
@angular-devkit/architect       0.1700.0-next.9
@angular-devkit/build-angular   17.0.0-next.9
@angular-devkit/core            17.0.0-next.9
@angular-devkit/schematics      17.0.0-next.9
@angular/cdk                    16.2.0
@angular/cdk-experimental       16.2.5
@angular/cli                    17.0.0-next.9
@schematics/angular             17.0.0-next.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by JeanMeche** [comment]
This is the espected behaviour since the new builder supports ssr. 

The regular/prerendered  spa app will be in `/browser` while the `ssr` app will be in `/server`.
