### ISSUE TITLE
Uncaught TypeError: Cannot read property 'visitExpression' of undefined

### ISSUE THREAD

**Issue by ericel** [angular/angular-cli#2603]
So I updated my app to the latest verion beta--17. Everything else seems to work just fine except when I create a new route using the 

> ng g component  auth

 I get this error:
`Uncaught TypeError: Cannot read property 'visitExpression' of undefined`

I thing I am getting this from abstract_emiter.js
```
 AbstractEmitterVisitor.prototype.visitAllExpressions = function (expressions, ctx, separator, newLine) {
        var _this = this;
        if (newLine === void 0) { newLine = false; }
        this.visitAllObjects(function (expr /** TODO #9100 */) { return expr.visitExpression(_this, ctx); }, expressions, ctx, separator, newLine);
    };
```

**Comment by ericel** [comment]
This was a syntax error on my part. In case anyone else runs into it:
```
{
    path: 'auth',
    component: AuthComponent,
    data: {
      title: 'Log in to your account'
    }
  },
,{
}
```

The double commas after the route in the route module.

**Comment by vburam** [comment]
i have faced this issue bcoz oz of syntax error . Extra comma.
{
      path:'register',
      component:RegisterComponent
    },
    
    , {
      path:'admin',
      component:AdminComponent
    },
