### ISSUE TITLE
Lack of clarity around the phasing out of browser-esbuild builder

### ISSUE THREAD

**Issue by jpike88** [angular/angular-cli#26043]
### Command

build

### Description

I see in the beta a new message:

"The 'browser-esbuild' builder is a compatibility builder which will be removed in a future major version in favor of the 'application' builder."

That may change the structure of the output, right? A possible server folder etc? I don't intend to and never intend to use SSR etc, I have a client going into a www folder and prefer things stay the same.

What's the situation here?

**Comment by alan-agius4** [comment]
The `browser-esbuild` builder acts as a compatibility layer for the application and webpack builder allows a project to switch back and forth without further configuration changes.

One of the main changes of the application builder is indeed the output structure where `/browser` will contain the files that require to be served by the web server, and `/server` containing the server applications and lastly other files such as statistics, licenses information etc… which are not required by the application to run will be outputted in `/`

**Comment by jpike88** [comment]
I see. So I had

`"outputPath": "cordova/www",`

This will be become instead like 

`"outputPath": "applicationOutputFolder",`

I am going to need an additional step to move `applicationOutputFolder/browser` to `cordova/www`?

Unrelated question, I have an error when attempting to use `@angular-devkit/build-angular:application` instead of `@angular-devkit/build-angular:browser-esbuild` on the latest beta.

```
Error: Schema validation failed with the following errors:
  Data path "" must have required property 'browser'.
undefined
```

I'm poking around in source trying to understand how schema validation is failing, the error doesn't seem to make clear what is wrong.

Angular.json attached
[angular.json](https://github.com/angular/angular-cli/files/12912647/angular.json)

**Comment by zip-fa** [comment]
Change main to browser in this line

```
"main": "src/components/bootstrap.ts"
```

**Comment by alan-agius4** [comment]
Moving to the application builder requires additional option changes, a guide is unfortunately not yet available but is in progress and will be available in the coming weeks.  As @zip-fa, the `main` fail was replaced with `browser`.

To move the files from `applicationOutputFolder/browser` to `cordova/www` you would indeed need an extra step. We could potentially add an option an option to allow users to change the `/browser` and `/server` directories if there is a high demanded for this from the community.

**Comment by jpike88** [comment]
that's fine I can work with that, I just needed to understand that and that's simpler to just deal with the change in the output bundle structure.

just been testing and everything seems fine otherwise, thanks
