### ISSUE TITLE
Peer invalid

### ISSUE THREAD

**Issue by joumenharzli** [angular/angular-cli#2606]
### OS?
> windows 10 64

### Versions.
> node 4.6.0
   ng --version ==> Cannot find module 'reflect-metadata'

### Repro steps.
> Just installing angular-cli

### The log given by the failure.
> 
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@2.1.0-beta.25 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer html-webpack-plugin@2.22.0 wants webpack@*
npm ERR! peerinvalid Peer karma-webpack@1.8.0 wants webpack@^1.1.0 || ^2 || ^2.1.0-beta
npm ERR! peerinvalid Peer sass-loader@3.2.3 wants webpack@^1.12.6 || ^2.1.0-beta
npm ERR! peerinvalid Peer string-replace-loader@1.0.5 wants webpack@1 || 2 || ^2.0.0-beta || ^2.1.0-beta
npm ERR! peerinvalid Peer webpack-dev-server@2.1.0-beta.3 wants webpack@^2.1.0-beta

**Comment by deebloo** [comment]
what version of NPM are you using?

**Comment by joumenharzli** [comment]
i have npm v2.15.9 it comes with node v4.6.0

**Comment by deebloo** [comment]
angular-cli needs npm > 3
https://github.com/angular/angular-cli#prerequisites
