### ISSUE TITLE
Browser showing 404 error for an image.

### ISSUE THREAD

**Issue by ahaan729** [angular/angular-cli#2607]
### OS?
> Windows 10

### Versions.
> angular-cli: 1.0.0-beta.17
> node: 6.7.0
> os: win32 x64

### Repro steps.
> Trying to display an 'img' folder which is located in the app folder with following image tag
   img src="../img/developer.jpg"

### The log given by the failure.
> The compilation doesn't show any error but the browser is showing "404 not found" for the image even though its there

### Mention any other details that might be useful.
It was working with beta-16 but now on beta-17 I'm facing this issue..
Running in development mode.
Since the cli doesn't show any error so I thought there isn't any error in the path but dont know why the error pops up in the browser.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by nivensookharan** [comment]
what was your fix for this?
