### ISSUE TITLE
Adding additional webpack processes (base64 images)

### ISSUE THREAD

**Issue by IljaDaderko** [angular/angular-cli#2608]
I am trying figure out a way to add custom webpack processes like converting images to base64 on build. I believe angular-cli has it's own webpack config, hence how can we add another one without creating interference?

**Comment by grizzm0** [comment]
Extending the webpack config is not possible at this time. Please see #1656 for more info.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1656

**Comment by jcperez-ch** [comment]
This is not exactly a duplicate of https://github.com/angular/angular-cli/issues/1656.  I also want to know if there is a way to process base64 images inside css/less/scss urls(). Not sure if we could re-open the discussion
