### ISSUE TITLE
`@angular-devkit/build-angular:browser-esbuild` reloads when navigating to lazy routes for the first time, causing navigation to fail.

### ISSUE THREAD

**Issue by HymanZHAN** [angular/angular-cli#26090]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Similar issue: https://github.com/angular/angular-cli/issues/25455

When serving with the Vite dev server, with caching enabled but no existing cache for lazy routes, the page will reload when I click on a link to a lazy route. And in some cases, the navigation will simply fail.

https://github.com/angular/angular-cli/assets/26806995/63dafb60-555e-4922-a808-fbab0a694420

My lazy route shows a list of items in my little test case, and I am using `ngFor` in the template. The navigation will proceed if the template is a simple `<p>lazy-list works!</p>`.

Despite the reply in the related issue (https://github.com/angular/angular-cli/issues/25455), I still expect/hope Angular cache and Vite play more nicely together because I want the cache enabled for faster dev builds. A _very very_ naive idea is that the Vite dev server only reads the cache when it first launches, only writes to the cache before it shuts down, and keeps behaving as if there is no such thing as a cache during the whole life cycle of its process.

### Minimal Reproduction

I have [a minimal repo](https://github.com/HymanZHAN/esbuild-issue) with the reproduction.

### Your Environment

```text
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.7
Node: 18.12.1
Package Manager: pnpm 7.25.1
OS: linux x64

Angular: 16.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.7
@angular-devkit/build-angular   16.2.7
@angular-devkit/core            16.2.7
@angular-devkit/schematics      16.2.7
@angular/cli                    16.2.7
@schematics/angular             16.2.7
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by iKrishnaSahu** [comment]
Facing the same issue in recently release 17rc version
