### ISSUE TITLE
Sub-optimal optimizations with ESBuild

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular-cli#26092]
### Command

build

### Description

I've written a demo App which is mostly this: 

```
export class AppComponent {
  constructor() {
    isDevMode() ? console.log('devMode') : console.log('prodMode');
  }
}
```

With Webpack, the first `console.log` is stripped out by optimization on `build` but with esbuild it isn't. 

Just for the sake of testing, I did try to  set `optimization: false` and then using the online REPL pass it through esbuild (just setting  `define: { ngDevMode: 'false'})`& terser : the 1st `console.log` is correctly removed. 

Are we missing some optimization here ? Or is that usecase far too simple to be relevant ? 

### Minimal Reproduction

https://github.com/jeanmeche/my-lib/tree/optim 

* `ng build demo`
* check the main.js in `dist`
* check the `console.log`

### Your Environment

```text
Node: 18.15.0
Package Manager: npm 9.5.0
OS: darwin x64

Angular: 17.0.0-rc.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.0
@angular-devkit/build-angular   17.0.0-rc.0
@angular-devkit/core            17.0.0-rc.0
@angular-devkit/schematics      17.0.0-rc.0
@schematics/angular             17.0.0-rc.0
ng-packagr                      17.0.0-next.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by alan-agius4** [comment]
This is expected and in Webpack this will only works in specific scenarios and circumstances, when `isDevMode` is hoisted and used the same bundle. 

As soon as this is moved to a seperate bundle ex. a lazy chunk it will stop being  removed.

Worth mention that, `isDevMode` was never meant to be used as a DCE mechanism for dev only code.

See also: https://github.com/evanw/esbuild/issues/2006#issuecomment-1034076043 and https://github.com/angular/angular-cli/issues/23738
