### ISSUE TITLE
how to use autoprefixer for css?

### ISSUE THREAD

**Issue by baschte** [angular/angular-cli#2609]
How is it possible to use autoprefixer on angular-cli?
Would be great if someone can help.

**Comment by goriunov** [comment]
Hello baschte , I found interesting article where explained how to add autoprefixer  to angular cli.
This is web site :
https://medium.com/@Ai_boy/configure-angular-2-cli-webpack-beta-14-5a7052ce6156#.q5tq08ea0

Use short way works fine. Long way too but you need to change some additional settings which is not shown in the article properly.

**Comment by baschte** [comment]
@goriunov thank you! i try it out.

**Comment by filipesilva** [comment]
Dupe of https://github.com/angular/angular-cli/issues/1512
