### ISSUE TITLE
Initial commit from ember-cli

### ISSUE THREAD

**Issue by jkuri** [angular/angular-cli#261]
We need to override the initial commit which is now
`Initial Commit from Ember CLI v1.13.15`

**Comment by filipesilva** [comment]
We have a new commit message, but I guess it's not being used?

https://github.com/angular/angular-cli/blob/master/addon/ng2/utilities/INITIAL_COMMIT_MESSAGE.txt

**Comment by jkuri** [comment]
No, I got the above message with the newest version from npm (0.0.24).

**Comment by cironunes** [comment]
Duplicate of #125
