### ISSUE TITLE
[esbuild] background-urls processed with errors while process .css files from node_modules without files

### ISSUE THREAD

**Issue by pumano** [angular/angular-cli#26105]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I use `.css` from `node_modules` (from my library) with background urls that is could not be resolved. When I use webpack, I have no errors about it (also not have warnings - I think it's not good also) but that not stop me with errors in node_modules css background urls which could not be resolved.

### Minimal Reproduction

Just add `some.css` file to any node_module library, and import it into `project.json` for processing. That .css should contain

```css
.something {
    background-image:url(assets/somefolder/my-header.jpg);
}
```

but we have no image in library. That's no problem for webpack. Webpack ignore it, but esbuild angular `css-resource-plugin` can't ignore it.

I'm trying to fix that by my own via to check `css-resource-plugin.js` and add some code to build.onResolve

```js
if (result.errors.length && kind === 'url-token' && importer.includes('node_modules') && result.errors[0].text.includes('Could not resolve') ) {
   result.warnings.push(result.errors[0])

   result.errors[0] = undefined;
   return {
       warnings: result.warnings,
       path: args.path,
       external: true,
   };
}
```
and that solve my problem but when `tailwindcss` process my in app background-image urls that importer is node_modules too via `node_modules/tailwindcss`. That leads to all errors processed by `tailwindcss` also been marked as warnings. That's not a good idea.

I'm add tailwindcss explicitly. Not the best way, but works)

```js
if (result.errors.length && kind === 'url-token' && (importer.includes('node_modules') && !importer.includes('tailwindcss')) && result.errors[0].text.includes('Could not resolve') ) {
   result.warnings.push(result.errors[0])

   result.errors[0] = undefined;
   return {
       warnings: result.warnings,
       path: args.path,
       external: true,
   };
}
```

That fixes problems and mark all `node_modules` css imports as warnings, and only process properly `tailwindcss`

### Exception or Error

```text
Could not resolve "assets/somefolder/my-header.jpg" [plugin angular-css-resource]

    node_modules/@org/ui-lib/some.css:1:63459:
      1 │ ...ound-image:url(assets/somefolder/my-header....
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "assets/somefolder/my-header.jpg" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

### Your Environment

```text
Angular CLI: 17.0.0-rc.0
Node: 18.16.1
Package Manager: yarn 3.6.3
OS: darwin arm64

Angular: 17.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.0
@angular-devkit/build-angular   17.0.0-rc.0
@angular-devkit/core            17.0.0-rc.0
@angular-devkit/schematics      17.0.0-rc.0
@schematics/angular             16.2.7
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

### Anything else relevant?

I can prepare PR if this solution is accepted by angular team.

**Comment by pumano** [comment]
If somehow I can mark it as external via builder config and mute errors - it's also an option!

**Comment by clydin** [comment]
The new build system provides the `externalDependencies` option which can be used in this case to notify the build system that these files should not be processed at build time.
Example:
```
"externalDependencies": ["assets/*"]
```

**Comment by pumano** [comment]
@clydin it's good, but I really want to process files from assets, but somehow ignore from `node_modules` library

**Comment by alan-agius4** [comment]
@pumano, assets are not intended to be processed by the build system. They are copied as are. Otherwise, you'll get double in the output if they are.
