### ISSUE TITLE
[esbuild] Incorrect error handling while processing background images

### ISSUE THREAD

**Issue by pumano** [angular/angular-cli#26106]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I create issue #25089 not so long ago about problem when using tilde "~" syntax when processing css resources, and looks like in issue #25089 it should be fixed and error message should be displayed, but it not displayed. Today I debugging some other issue, trying to debug this issue too, and found that code in `css-resource-plugin` not correctly works.

is looks like: 

```js
  if (result.errors.length && args.path[0] === '~') {
    result.errors[0].notes = [
      {
        location: null,
        text: 'You can remove the tilde and use a relative path to reference it, which should remove this error.',
      },
   ];
  }

```

but interface `Message` from `esbuild` don't know about "notes" property.

```js
interface Message {
  text: string;
  location: Location | null;
  detail: any; // The original error from a JavaScript plugin, if applicable
}
```

Looks like it should looks like:

```js
   if (result.errors.length && args.path[0] === '~') {
     result.errors[0] = {
        location: null,
        text: 'You can remove the tilde and use a relative path to reference it, which should remove this error.',
     };
   }
```

After it I see proper error message

Also I would suggest to add ^ sign too and both old "webpack" syntax properly error handled with tailored error messages. 

### Minimal Reproduction

add background-image url with tilde

```css
background-image: url('~assets/dashboard/products.jpg')
```

### Your Environment

```text
Angular CLI: 17.0.0-rc.0
Node: 18.16.1
Package Manager: yarn 3.6.3
OS: darwin arm64

Angular: 17.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.0
@angular-devkit/build-angular   17.0.0-rc.0
@angular-devkit/core            17.0.0-rc.0
@angular-devkit/schematics      17.0.0-rc.0
@schematics/angular             16.2.7
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

### Anything else relevant?

I can prepare PR if needed

**Comment by clydin** [comment]
Thank you for testing the prerelease of v17.

The type definition for esbuild's `Message` type in the latest version that is used in v17 prereleases is:
```
export interface Message {
  id: string
  pluginName: string
  text: string
  location: Location | null
  notes: Note[]

  /**
   * Optional user-specified data that is passed through unmodified. You can
   * use this to stash the original error, for example.
   */
  detail: any
}
```

There was a case where the warning would not be shown if the `url()` was in an imported Sass file.  This case along with the caret (`^`) warnings should be available in the next prerelease via #26108

If you are still encountering issues after that change, please provide a minimal reproduction demonstrating the problem so that further investigation can be performed.
