### ISSUE TITLE
npm install -g angular-cli with npm 3.10.8 FAIL [Work with npm@3.10.7 and node@4.6.0] 

### ISSUE THREAD

**Issue by Xopsy** [angular/angular-cli#2610]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX (El Capitan)

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.17
node: 4.6.0

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

So many times this error:

npm ERR! uid must be an unsigned int
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli"
npm ERR! node v4.6.0
npm ERR! npm  v3.10.8

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by m44rt3np44uw** [comment]
I can remember I received this error once when I tried to install it with sudo. Try `npm install -g angular-cli`

**Comment by filipesilva** [comment]
This seems to be a npm issue. See https://github.com/npm/npm/issues/13946 and https://docs.npmjs.com/getting-started/fixing-npm-permissions
