### ISSUE TITLE
Library - share source code?

### ISSUE THREAD

**Issue by Casimodo72** [angular/angular-cli#26101]
### Command

generate

### Description

Hi, I'm relatively new to Angular and would like to reuse some standalone components, services and just some other code in multiple projects (in a single workspace).
I learned that one can generate a "library" which needs to be build separately (lands in dist/lib) and is intended to be published (npm).
But what I'm envisioning is a library where I can just share the source code (like a .NET project or shared-code reference) without the hassle of building and publishing it (the latter not being possible for us anyway). Is this possible? Will this be supported someday?
From what I read Angular has issues when files located outside of the app folder are referenced.

Currently I'm thinking of putting my library code anywhere and creating a symlink to it so the CLI will treat it as part of the project. Is this the preferred handling of such a scenario?
(Hmm, now I'm wondering if symlinks could be a problem when using git) 

### Describe the solution you'd like

A library for sharing of source code (without the need to build it separately or publish it)

### Describe alternatives you've considered

Symlink to the shared code folder

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
