### ISSUE TITLE
Node 20 support

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular-cli#26114]
Mostly to help outsiders tracking the support of Node20. 

Currently it's not supported : 

https://github.com/angular/angular-cli/blob/65a26609d3c27d24dbccebba494e0869be915f12/packages/angular/cli/src/commands/version/cli.ts#L26

**Comment by marcj** [comment]
Indeed, I was just confused because I got a weird error during "ng build" on v17.rc-1 when using Node v20.

```
An unhandled exception occurred: Invalid URL
See "/private/var/folders/6q/zfv9dpln0k1897hvcd1r9ylr0000gn/T/ng-mRX4oW/angular-errors.log" for further details.
```

It goes away with using Node 18.

**Comment by daazb001** [comment]
Is this Info than still correct?

Here only versions 16 and 18 are listed as supported.

https://angular.io/guide/versions#:~:text=x%20%7C%7C%2016.2.x-,%5E16.14.0%20%7C%7C%20%5E18.10.0,-%3E%3D4.9.3%20%3C5.2.0

**Comment by JeanMeche** [comment]
For v16 yes. If you want Node20 support, you have to use v17.

**Comment by daazb001** [comment]
Okey, thanks. This is a bit unfortunate for our team, since we have to choose between a potencially unstable Angular Version 17 with support for the current LTS version of Node.js (20) or the LTS Version 16 of Angular with an older version of Node.js (18).

**Comment by Yogu** [comment]
Will support for Node 20 be backported to Angular 15 and 16?

**Comment by JeanMeche** [comment]
LTS versions only receive [security updates](https://angular.io/guide/releases#support-window).

**Comment by alan-agius4** [comment]
While the above mentioned PR doesn’t add any changes, there were other PRs that were landed before hand that were required to support Node 20 included but not limited to updateding NPM dependencies.
