### ISSUE TITLE
Issue running npm install -g angular-cli

### ISSUE THREAD

**Issue by Reozil** [angular/angular-cli#2612]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 14.04 LTS

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
ng --version throws errors first is: Error: Cannot find module 'process-nextick-args'
node --version v4.2.6

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
i was installing the cli with npm install -g angular-cli
First error is: 
node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v46-linux-x64.tar.gz

If i try this path with browser i get acces denied.

### The log given by the failure.
> Normally this include a stack trace and some more information.
npm install -g angular-cli
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash-node@2.4.1: This package is discontinued. Use lodash@^4.0.0.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/local/bin/ng -> /usr/local/lib/node_modules/angular-cli/bin/ng

> node-zopfli@2.0.1 install /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v2.0.1-node-v46-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@2.0.1 and node@4.2.6 (node-v46 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/rauno/.node-gyp/4.2.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
make: *** No rule to make target '../.node-gyp/4.2.6/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node" "--module_name=zopfli" "--module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64"
gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/angular-cli/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.4.0-38-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/usr/local/lib/node_modules/angular-cli/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli
node-pre-gyp ERR! node -v v4.2.6
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/local/lib/node_modules/angular-cli/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64/zopfli.node --module_name=zopfli --module_path=/usr/local/lib/node_modules/angular-cli/node_modules/node-zopfli/lib/binding/node-v46-linux-x64' (1)
npm WARN install:node-zopfli@2.0.1 node-zopfli@2.0.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@2.0.1 Exit status 1
/usr/local/lib
└─┬ angular-cli@1.0.0-beta.17 
  └── compression-webpack-plugin@0.3.2  (git://github.com/webpack/compression-webpack-plugin.git#7e55907cd54a2e91b96d25a660acc6a2a6453f54)

npm WARN optional Skipping failed optional dependency /angular-cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by DavideViolante** [comment]
I receive `node-pre-gyp ERR!` error too, but everything seem to work well anyway.
I'd like to know too if this can be ignored or...

**Comment by MyOnlyGH** [comment]
We too faced the same issue. We being behind a firewall were using proxies but still that error. Because of this error we are not able to proceed with CI as it fails npm install task

**Comment by ahaan729** [comment]
I also faced the same issue while installing angular-cli-beta17 on a new system.
FIX: 
1. I went through the logs and manually updated each of the packages (graceful-fs, minimatch, lodash etc..) to there updated version. 
2. Installed git on my system (From my past experience) as this is also a reason for cli install failure.

After this it installed without any errors.

**Comment by filipesilva** [comment]
See https://github.com/angular/angular-cli/issues/1560#issuecomment-240913794

**Comment by ericjamesjohnson672** [comment]
Ugh.  Too much time wasted chasing compatibility issues.
