### ISSUE TITLE
How to add a file to the build system (dist) folder

### ISSUE THREAD

**Issue by hassanasad** [angular/angular-cli#2613]
Hi!

Can someone please let me know how to add a simple file to the build system in angular-cli. For example, i want to keep a file called `web.config` in `dist` folder when the build is created. If i simply put it in my /src/ folder, it doesn't get copied. I am using beta.17 version of Angular-cli. 

Any help will be appreciated :)

**Comment by grizzm0** [comment]
The config key apps.assets accepts an array as of beta.17. You can now do the following.

```
"assets": [
  "assets",
  "favicon.ico"
]
```

**Comment by hassanasad** [comment]
I did try that - but its still not copying it.

This is my app.assets:
`"assets": ["assets", "web.config"]`

I ran the command `ng build --prod`

Still no web.config in `dist` folder even though its present in /src/

**Comment by hassanasad** [comment]
Actually - when i make `app.assets` an array, i dont even get my `assets` folder in the `dist` folder.

**Comment by grizzm0** [comment]
Sorry, my fault. It was merged after beta.17 was released. It's currently in master and will be released with beta.18.

**Comment by hassanasad** [comment]
oh - thanks grizzm0. Guess nothing more to do other than to wait for beta.18 :)

**Comment by grizzm0** [comment]
@filipesilva Could you close?

**Comment by bdv1234** [comment]
> The config key apps.assets accepts an array as of beta.17. You can now do the following.
> 
> ```
> "assets": [
>   "assets",
>   "favicon.ico"
> ]
> ```
hey, now apps.assets refer to the  ".angular-cli.json" right, if so, I added staticfile.txt in the assets array, but when I run "ng build --prod" command , it didn't create staticfile.txt in the dist folder.
