### ISSUE TITLE
Proxy Configuration Fails in Angular 15 with Node 18 When Targeting HTTPS Backends Due to OpenSSL 3 Restrictions

### ISSUE THREAD

**Issue by Neizan93** [angular/angular-cli#26134]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 15 with Node 16

### Description

When working with Angular 15 and Node 18 in a local development environment, the proxy configuration in Angular CLI fails to function as expected when targeting HTTPS backends on different environments (development, pre-production, production). The underlying cause seems to be the shift to OpenSSL 3 in Node 17 and above, which restricts connections to remote endpoints using TLS versions lower than 1.3 due to security concerns.

### Minimal Reproduction

- Set up a local development environment with Angular 15 and Node 18.
- Configure the proxy settings in Angular CLI to point to a backend using HTTPS with TLS 1.2.
- Attempt to access the backend via the proxy from the local development environment.
- Observe the failure in proxy configuration, preventing access to the backend.

### Exception or Error

```text
[HPM] Error occurred while trying to proxy request ***** from localhost:4200 to https://*****.*** (EPROTO) (https://nodejs.org/api/errors.html#errors_common_system_errors).
```

### Your Environment

```text
Angular Version: 15
Node.js Version: 18

Backend TLS Version: 1.2
```

### Anything else relevant?

Backend TLS Version: 1.2

_Node >=17 uses: OpenSSL Version: 3_

This issue disrupts our development workflow significantly as the proxy configuration is crucial for pointing to different backends from the local environment. It appears that the restriction on TLS versions is a security feature implemented in OpenSSL 3, which prevents connections to less secure protocols. However, a workaround or guidance on how to configure the proxy to work with backends using TLS 1.2 would be greatly beneficial.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by Neizan93** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

It is a BUG, it happens in Angular 15, 16, 17... Using Node 18, a version that Angular is supporting right now.
