### ISSUE TITLE
[Regression] Angular apps not working in Safari v15 due to `ReferenceError`

### ISSUE THREAD

**Issue by gbrunow** [angular/angular-cli#26154]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular-devkit/build-angular@16.1.6

### Description

We're experiencing the exact same issue reported on #24355 on Safari Version 15.5 (17613.2.7.1.8).
The issue started when updating from angular `16.1` to `16.2`, more specifically when we update `@angular-devkit/build-angular` from version `16.1.6` to `16.2.0`, and it reproduces on `16.2.8`. 

### Minimal Reproduction

See  #24355

### Your Environment

```text
Angular CLI: 16.2.8
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.0
@angular-devkit/build-angular   16.2.0
@angular-devkit/core            16.2.0
@angular-devkit/schematics      16.2.8
@angular/cdk                    16.2.10
@angular/cli                    16.2.8
@schematics/angular             16.2.8
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.1
```

**Comment by clydin** [comment]
Can you provide the contents of the projects browserslist file?

**Comment by gbrunow** [comment]
> Can you provide the contents of the project's browserslist file?

```
last 2 Chrome versions
last 1 Firefox version
last 2 Edge major versions
last 2 Safari major versions
last 2 iOS major versions
Firefox ESR
```

**Comment by clydin** [comment]
Thank you.

The last 2 Safari major versions are now 16 and 17.
https://browsersl.ist/#q=last+2+Safari+major+versions

Can you try increasing that to `last 3 Safari major versions`?
If you are still encountering the issue after that, let use know and we can investigate further.

**Comment by gbrunow** [comment]
Increasing the supported version to 3 solved it, thank you!

**Comment by clydin** [comment]
You’re welcome and good to hear.
