### ISSUE TITLE
Need an ability to generate style bundle separatelly under a directory

### ISSUE THREAD

**Issue by AshotAleqsanyan96** [angular/angular-cli#26161]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

Hello Friends,

After some research and reading the official documentation, I couldn't find any helpful information and I think it is not possible right now, to build the style files as a separate bundle under the subdirectory via the configuration in angular.json.

So let's say we have 2-3 theme CSS files 
1. `default-theme.scss`
2. `dark-theme.scss`
3. `system-theme.scss`

I want to build these scss files as a 3 separate bundles, fortunately it is possible via the angular.json configuration. I can add several lines and it will be ready:

`angular.json`: `projects.{PROJECT_NAME}.architect.build.options.styles`
```
...............................
"styles": [
         {
                "inject": false,
                "input": "src/themes/default-theme.scss",
          },
          {
                "inject": false,
                "input": "src/themes/dark-theme.scss",
          },
          {
                "inject": false,
                "input": "src/themes/system-theme.scss",
          },
]
...............................
```

and this will generate 3 separate files in the root directory in the `dist/{PROJECT_NAME}/`. 
1. `default-theme.css`
2. `dark-theme.css`
3. `system-theme.css`

I also noticed that the Style Object has one more additional property: `bundleName` which will help us to change the generated bundle name(which is good). 

But unfortunately, there is no way to generate these bundles under the sub-directory.

### Proposed solution

So it will be helpfull to modify the style object, by adding `output` property, that will get the path(`string`) as a value:

`angular.json`: `projects.{PROJECT_NAME}.architect.build.options.styles`
```
...............................
"styles": [
         {
                "inject": false,
                "input": "src/themes/default-theme.scss",
                "output": "themes",
                "bundleName": "default-theme"
          },
          {
                "inject": false,
                "input": "src/themes/dark-theme.scss",
                "output": "themes",
                "bundleName": "dark-theme"
          },
          {
                "inject": false,
                "input": "src/themes/system-theme.scss",
                "output": "themes",
                "bundleName": "system-theme"
          },
]
...............................
```

and by these configuration I expect to have, my generated bundles under the `themes` directory
1. `themes/default-theme.css`
2. `themes/dark-theme.css`
3. `themes/system-theme.css`

### Alternatives considered

The second option is to have some standard objects for example:

`$styles`, `$assets` by which we can have access to the generated styles and assets to manipulate with them in angular.json

For example, by using the above example:

`angular.json`: `projects.{PROJECT_NAME}.architect.build.options.styles`
```
...............................
"styles": [
         {
                "inject": false,
                "input": "src/themes/default-theme.scss",
          },
          {
                "inject": false,
                "input": "src/themes/dark-theme.scss",
          },
          {
                "inject": false,
                "input": "src/themes/system-theme.scss",
          },
]
...............................
```

We can use assets object to change the directories:

`angular.json`: `projects.{PROJECT_NAME}.architect.build.options.assets`
```
...............................
"assets": [
         {
                "input": "$styles['default-theme.css']",
                "output": "themes/default-theme.css",
                "glob": "compiled"                 <------------ this is also can be modified a little bit to indicate that the file is not static
          },
         {
                "input": "$styles['dark-theme.css']",
                "output": "themes/dark-theme.css",
                "glob": "compiled"                 <------------ this is also can be modified a little bit to indicate that the file is not static
          },
                   {
                "input": "$styles['system-theme.css']",
                "output": "themes/system-theme.css",
                "glob": "compiled"                 <------------ this is also can be modified a little bit to indicate that the file is not static
          },
]
...............................
```

**Comment by alan-agius4** [comment]
What is the use-case the these stylesheet must be under a different directly?

**Comment by AshotAleqsanyan96** [comment]
@alan-agius4 Thanks for the reply.

Actually, this is just an example for better understanding. the problem is a little bit different and connected with the server configurations. 

In the development mode I am changing the assets directories, to make it similar to the server environment, as in the server angular is configured under the folder with the nginx redirectons. It will be really hard to explain the server configurations, that's why I have explained by using this simple example. 

Best,
Ashot

**Comment by dgp1130** [comment]
Why are themes under `themes/` on the server? I would think that if styles are bundled as part Angular CLI, it would make more sense to use the paths Angular is putting them at and aligning the production server to match. You could always move the themes post-build, but that would likely be annoying to orchestrate and break `ng serve`.

Since the challenge is a disagreement about file location between Angular (which wants to put them in the root) and your production server (which wants them under `themes/`), why is aligning on the `themes/` directory better? Is there a reason it is difficult or impractical to avoid a `themes/` directory on the server?

**Comment by AshotAleqsanyan96** [comment]
Hello @dgp1130, 

As I said previously, the issue is a bit complicated and is not connected only with themes. The whole angular project is under the folder and the angular project is accessible by the nginx redirections, and this is the main problem. 

So why one style bundle is not working in our case:

In the project, we are using angular material, and the initial loading is important for us. Each theme bundle is ~80kb, so if we build 1 style bundle in the case of 3 themes the bundle will be ~240kb which is not good, in the case of separate bundles each theme bundle will be 80kb, so that's why we decide to proceed with this solution. 

Thanks

**Comment by dgp1130** [comment]
I get not wanting multiple style bundles, using different bundles for each theme and only downloading the one you want is pretty reasonable.

I'm less clear on what a separate `themes/` folder is desirable in the first place? Do you just want to do this because you feel it is better organized or is there a deeper configuration challenge with the server? I would assume it is possible for the server to serve or redirect at the paths Angular is generating, is that not feasible for some technical reason?

**Comment by AshotAleqsanyan96** [comment]
@dgp1130 no no, I don't want this change because of better organization. It is connected with the server configuration and the local development/testing: Let me clarify a bit the server configuration, it is a little bit messy but I hope it will be helpfull.

On the server the whole angular project is under folder let's say under folder `/angular` and by nginx configurations the requests are navigation to take the angular resources from the `/angular` folder, so for all of the images and all of the assets resources I am using the `/angular` as a prefix to be able to take the static resources from the assets. So everything is working as expected, but I have some additional logic for all of the static assets to generate an additional folder(`/angular`) for development/testing and  I am generation that by using the configuration for assets:

```
 {
                  "input": "projects/alison-core/src/lib/styles/fonts",
                  "output": "angular/assets/web-components/fonts",
                  "glob": "**/*"
                },
                {
                  "input": "src/assets",
                  "output": "angular/assets",
                  "glob": "**/*"
                }
``` 

this is generating:
```
other-bundles .......
/angular
    /assets/..................
    /assets/web-components/fonts
```

Thanks

**Comment by alan-agius4** [comment]
This case is quite particular use-case, and as of now, there isn't a plan to support the configuration of were styles are outputted.

 Let's reassess this in the future if there's increased demand for this feature from users.
