### ISSUE TITLE
CLI ng s cant be killed

### ISSUE THREAD

**Issue by web-dave** [angular/angular-cli#26178]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.x

### Description

When starting the dev process with ng server. This process can't be stoped.
only tasmkananger process kill works

### Minimal Reproduction

ng s

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.0-rc.2
Node: 18.18.2
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.0-rc.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.2
@angular-devkit/build-angular   17.0.0-rc.2
@angular-devkit/core            17.0.0-rc.2
@angular-devkit/schematics      17.0.0-rc.2
@angular/cli                    17.0.0-rc.2
@angular/ssr                    17.0.0-rc.2
@schematics/angular             17.0.0-rc.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.1
```

### Anything else relevant?

Sometimes this works like charm.

reproduce it:
ng s
wait some time.
strg+c no luck

**Comment by alan-agius4** [comment]
@web-dave, unfortunely I am not able to replicate this. Are you able to reproduce this on a new application?

**Comment by sod** [comment]
try `ctrl+c` instead of `cmd+c` 😬

**Comment by web-dave** [comment]
@alan-agius4 It is a new Project. created a few minutes ago.
No other dependencies added.

even if i close the terminal, the process is still running.

You can see this problem in my vod from monday. (https://www.twitch.tv/videos/1964316115) 
start ng s at 00:27:10.
try to stop with strg+C 00:28:20

**Comment by web-dave** [comment]
@alan-agius4 

new informations. this doesn't happen without ssr.

```cmd
ng new cli-test-no-ssr
styling scss
ssr No
```

**Comment by alan-agius4** [comment]
@web-dave, can you please check if this is still a problem with `@angular-devkit/build-angular` version `17.0.0-rc.3`?

**Comment by web-dave** [comment]
@alan-agius4 solved in rc.3
🎉
