### ISSUE TITLE
SSR and development bundler selection on create app

### ISSUE THREAD

**Issue by pdaneshmand** [angular/angular-cli#26226]
### Command

generate

### Description

It would be great if you could choose to run the server side, for example, between fastify or Express or any other framework. Also, choose the execution engine, for example, choose Viteas the default. The less time a developer spends on such issues, the more creative he will be.

### Describe the solution you'd like

For example ask me on app creation : 

Whats your favorite SSR engine (express default ) ?
1 - fastify
2 - Nest
3 - etc

Whats your favorite boundless (webpack default ) ?

1 - Vite
2 - etc

**Comment by alan-agius4** [comment]
Hi,

Thanks for this request.

This is defiantly something interesting, however  currently there is only support for Express. We could reconsider this in the future when support for other providers is added.

With regards to bundlers, the CLI is optioned about this and for new applications we believe that Esbuild + Vite provide a superior DX and will become the default in v17 which will be released as stable later next week.

**Comment by pdaneshmand** [comment]
WOW, good news about Vite. 
Thanks for your response. 👍
