### ISSUE TITLE
Improvement: Module creation and organization

### ISSUE THREAD

**Issue by bjornharvold** [angular/angular-cli#2624]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Mac OSX Sierra

### Versions.
> 1.0.0-beta.17

Once I start creating logical modules within my app using `ng g module`, how do I proceed with Angular CLI when I want to add more components, services and directives to that module?

I'm guessing at this point it is still a manual task.

Cheers and good work!
Bjorn

**Comment by leon** [comment]
You think you can type a path when generating...

```
ng g component mymodule/mycomponent
```

**Comment by bjornharvold** [comment]
Thanks Leon! Works like a charm :)
