### ISSUE TITLE
dev server is not starting on 17.0.0-rc4 with bunch of `will always be undefined` errors

### ISSUE THREAD

**Issue by zip-fa** [angular/angular-cli#26256]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

rc3

### Description

Hi.
After upgrading to rc4 my dev server is not starting with application builder. It throws errors on every file my project has, including on angular's ones.
Downgrading to rc3 resolved this.

### Minimal Reproduction

ng serve

### Your Environment

```text
Angular CLI: 17.0.0-rc.4
Node: 18.18.2
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.0-rc.3
... animations, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.4
@angular-devkit/build-angular   17.0.0-rc.4
@angular-devkit/core            17.0.0-rc.4
@angular-devkit/schematics      17.0.0-rc.3
@angular/cdk                    17.0.0-rc.2
@angular/cli                    17.0.0-rc.4
@angular/ssr                    17.0.0-rc.4
@schematics/angular             17.0.0-rc.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

### Anything else relevant?

▲ [WARNING] Import "bootstrapApplication" will always be undefined because the file "node_modules/@angular/platform-browser/fesm2022/platform-browser.mjs" has no exports [import-is-undefined]

    src/main.server.ts:2:9:
      2 │ import { bootstrapApplication } from '@angular/platform-browser';

▲ [WARNING] Import "enableProdMode" will always be undefined because the file "node_modules/@angular/core/fesm2022/core.mjs" has no exports [import-is-undefined]

    src/main.server.ts:1:9:
      1 │ import { enableProdMode } from '@angular/core';

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by zip-fa** [comment]
Is it possible to share my repo? I know you ask for little repro (how i do it usually), but i am a bit bored of creating them.
If not possible - i will dig deeper and find root of the problem

**Comment by alan-agius4** [comment]
@zip-fa, we can try.

**Comment by alan-agius4** [comment]
It seems that this is caused when having `allowJs` TSC option enabled.

**Comment by zip-fa** [comment]
I see you made a fix. Will wait for next rc and confirm then, instead of giving access to my repo :)

**Comment by alan-agius4** [comment]
@dgp1130, will be cutting another RC later today.
