### ISSUE TITLE
configuration via environment variables

### ISSUE THREAD

**Issue by Pertel** [angular/angular-cli#2625]
Hi
Is there a recommended way to provide configuration via environment variables, instead of hardcoding it in a specific environment.<env>.ts file, or rolling my own script to do it?

I'm not well versed in webpack, so perhaps there is a simple way to do it, which is not specific to angular-cli. On the other hand, the webpack configuration is mostly inaccessible, so perhaps that is not viable.

There are quite a few ways to do this of course, so I'm asking if there is a recommended / supported way of doing it, instead of everybody just rolling their own solutions.

Thanks

**Comment by filipesilva** [comment]
The way we support in the CLI is the environment files as documented in https://github.com/angular/angular-cli#build-targets-and-environment-files. There isn't any other way for now.

**Comment by tinchou** [comment]
Sorry to hijack the thread, but let me ask a related question: what if you want to have secrets that shouldn't be stored along with your code? It's pretty common to have configuration in environmental variables in your server (for example in Azure you set them up through an admin panel).

**Comment by Pertel** [comment]
That's a very relevant question, and it's the same reason I asked the original question. We deploy our apps using Docker, so all configuration is done using env variables. Besides, it's just not a good idea to store config in source control. Maybe it would be a good idea to have a template for the environment file, and have all the actual files in gitignore.

**Comment by filipesilva** [comment]
My recommendation in that case is to either:
- drop in one of these env files in a secure build environment, then build and deploy
- load configuration at runtime using a custom mechanism

**Comment by memark** [comment]
That's an interesting approach. Another common requirement is the "build once, deploy many" workflow (i.e. not rebuild each time for a new environment. My experience is that most enterprise devops pipelines work like that.) Are there any plans to support this?

In fact, I opened a SO question about this just yesterday.
https://stackoverflow.com/questions/41848495/build-once-deploy-many-with-angular-cli

**Comment by vol4life27** [comment]
Yea, not having any option to inject ENV variables besides having to make a custom solution just doesnt sound like the kind of framework Angular is supposed to be. And creating just another config file does solve the problem of needing 3+ different environments.

**Comment by filipesilva** [comment]
There's more information on this in https://github.com/angular/angular-cli/issues/3855/. Of special relevance is https://github.com/angular/angular-cli/issues/3855#issuecomment-274803729, which explains why the CLI isn't opinionated on runtime configs, and there's a simple example in a followup comment.

So that sort of thing is already supported, it just has nothing to do with the build system.

**Comment by db3dev** [comment]
Would like to add that if anyone is trying to build secrets into their webapp they're exposing those secrets to anyone who visits their website anyway. It would be better to have your secrets managed by a proxy.
