### ISSUE TITLE
Better error messages when switching from `browser-esbuild` to `application` builder

### ISSUE THREAD

**Issue by hakimio** [angular/angular-cli#26260]
### Command

build

### Description

When trying to switch from `browser-esbuild` to `application` builder like the deprecation warning suggests, I get the following cryptic messages:
- `Data path "" must have required property 'browser'.`: means `main` option was split to `browser` and `server` and you are supposed to add at least `browser` option: 
```
"architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "browser": "src/main.ts",
```
- `Data path "" must NOT have additional properties(main).`: `main` was replaced by `browser` and `server`.
- `Data path "/polyfills" must be array.`. `"polyfills": "src/polyfills.ts"` option should be replaced with `"polyfills": ["zone.js"]`

### Describe the solution you'd like

Better error messages.

**Comment by dgp1130** [comment]
Agreed the error message here is not great. Unfortunately, this one is generated from Architect which is too generic to really be more specific. It doesn't have the context to give more information here.

We have a more general issue tracking this here: https://github.com/angular/angular-cli/issues/11479

For `browser` / `browser-esbuild`  -> `application` specifically, we're working on a schematic to automatically perform this migration so users would never make this mistake in the first place.
