### ISSUE TITLE
Nested Workers application builder

### ISSUE THREAD

**Issue by JosefBredereck** [angular/angular-cli#26288]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular-devkit/build-angular:browser

### Description

Hello, I'm using the new `application` builder and I use nested workers.

On angular.dev I found the following known issue but no issue that tracks that this is still open.
https://angular.dev/tools/cli/esbuild#type-checking-of-web-worker-code-and-processing-of-nested-web-workers

Is the known issue, that nested workers are not working, or just that the type checking is not working?

### Minimal Reproduction

ng new repro-app
[ng generate web-worker](https://angular.dev/ecosystem/web-workers#)

include the worker in another worker

### Exception or Error

```text
Sourcemap for "../.angular/vite-root/cosmic-void/worker-HUU42S34.js" points to missing source files
```

### Your Environment

```text
Angular CLI: 17.0.0
Node: 18.14.0
Package Manager: npm 9.3.1
OS: win32 x64

Angular: 17.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment]
This is expected as stated in the docs nested workers nested workers will not be processed by the build system. This will be happened in a future release.
