### ISSUE TITLE
Angular/CLI v17.0.0 is not backwards compatible with older versions of Angular.

### ISSUE THREAD

**Issue by EliezerB123** [angular/angular-cli#26283]
### Command

build, new, run, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.10

### Description

**The Problem:**

Installing Angular globally by running `npm install -g @angular/cli`, then running `ng serve` on an older Angular Project (In our case, Angular 14, but the same problem occurs in Angular 15), will result in an error and `ng serve` will fail.

This is a regression, as running `npm install -g @angular/cli@16.2.10` will work perfectly fine when working with an Angular 14 project.

**Expected result:**

Installing Angular 17 globally via `npm install -g @angular/cli` should not cause Angular versions of <17 to fail to serve/build with an error message about Node.js. Instead, it should warn about a version mismatch between the global and local versions of @Angular/cli, but compile anyways.

### Minimal Reproduction

1. nvm use 14.20.1 (Install node 14.)
2. npm install -g @angular/cli@^15.2.0
3. ng new repro-app
4. npm install -g @angular/cli@^17.0.0
5. cd repro-app
6. ng serve

### Exception or Error

```text
Node.js version v14.20.1 detected.
The Angular CLI requires a minimum Node.js version of v18.13.

Please update your Node.js version or visit https://nodejs.org/
 for additional instructions.
```

### Your Environment

```text
Note: The same problem happens on Angular 14 as well!

But here's the ng version of Angular 15:


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.2.10
Node: 14.20.1
Package Manager: npm 6.14.17
OS: win32 x64

Angular: 15.2.10
... animations, cli, common, compiler, compiler-cli, core, form
s

... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.10
@angular-devkit/build-angular   15.2.10
@angular-devkit/core            15.2.10
@angular-devkit/schematics      15.2.10
@schematics/angular             15.2.10
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by Neizan93** [comment]
This is something you should know long time ago to be prepared... Check the version compatibility table: https://angular.io/guide/versions

**Comment by Neizan93** [comment]
Node 14 is not in active or security support, check this:
https://endoflife.date/nodejs

**Comment by ColinNg** [comment]
Thanks for testing versions, this gives us a workaround for our build pipeline. 

Yes, we should all be using the latest. Because it takes days to upgrade Angular, the entire population of Angular developers must do this, be forced to do this, for every client they've ever worked for - present and past, right?
