### ISSUE TITLE
Feature: Support --specs for e2e argument

### ISSUE THREAD

**Issue by IngvarKofoed** [angular/angular-cli#2628]
It would be very nice to be able not only run a single or some of the e2e tests.

Thanks :)

**Comment by leocaseiro** [comment]
The current angular-cli has the `--specs` for `e2e`.

Sorry if I'm wrong, but I think you can use it now.

https://github.com/angular/angular-cli/wiki/e2e



> `--specs` (alias: `-sp`) _default value: []_
> 
> Override specs in the protractor config. Can send in multiple specs by repeating flag (ng e2e --specs=spec1.ts --specs=spec2.ts).

**Comment by filipesilva** [comment]
Closing as answered by @leocaseiro, thanks!

There's also this feature request for a `--suite` flag: https://github.com/angular/angular-cli/issues/2628.
