### ISSUE TITLE
TypeError during ng update: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by SaranshChaudhary** [angular/angular-cli#26292]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Running `ng update` to upgrade various Angular packages results in a TypeError, halting the update process.

### Command
Executed command: `ng update @angular/cdk @angular/cli @angular/core @angular/fire @angular/material` (tried one at a time as well)

### Error
✖ Migration failed: Cannot convert undefined or null to object
  See "/private/var/folders/fr/nddjk7yj29v5f4058jgqbn400000gn/T/ng-JoOh2c/angular-errors.log" for further details.

### Error details from the log file
[error] TypeError: Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at _buildPackageInfo (/private/var/folders/fr/nddjk7yj29v5f4058jgqbn400000gn/T/angular-cli-packages-VL3Ti2/node_modules/@angular/cli/src/commands/update/schematic/index.js:434:52)
at /private/var/folders/fr/nddjk7yj29v5f4058jgqbn400000gn/T/angular-cli-packages-VL3Ti2/node_modules/@angular/cli/src/commands/update/schematic/index.js:708:53
at Map.forEach (<anonymous>)
at /private/var/folders/fr/nddjk7yj29v5f4058jgqbn400000gn/T/angular-cli-packages-VL3Ti2/node_modules/@angular/cli/src/commands/update/schematic/index.js:707:27
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async callRuleAsync (/private/var/folders/fr/nddjk7yj29v5f4058jgqbn400000gn/T/angular-cli-packages-VL3Ti2/node_modules/@angular-devkit/schematics/src/rules/call.js:77:18)

### Your Environment

```text
Angular CLI: 16.0.1
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 16.0.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.1
@angular-devkit/build-angular   16.0.1
@angular-devkit/core            16.0.1
@angular-devkit/schematics      16.0.1
@angular/fire                   7.5.0
@schematics/angular             16.0.1
ng-packagr                      16.0.1
rxjs                            7.5.7
typescript                      5.2.2
```

**Comment by alan-agius4** [comment]
Can you please share your package.json before the update?
