### ISSUE TITLE
`$ ng repair`

### ISSUE THREAD

**Issue by splincode** [angular/angular-cli#26295]
### Command

update

### Description

I think we have a useful nx command `$ nx repair`

https://nx.dev/nx-api/nx/documents/repair

why don't we have exactly the same one in angular?

<img width="647" alt="image" src="https://github.com/angular/angular-cli/assets/12021443/3644e68c-7d10-42b1-9b5b-5f051c614f10">

**Comment by alan-agius4** [comment]
To fix the above warning you can use the `ng update` command, which will run a migration and replace the usages of deprecated options.

I do like the concept of a repair/refactor though
