### ISSUE TITLE
@ngtools/webpack breaking changes - not possible to build with AOT=true

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#2629]
Hello, 
in version @ngtools/webpack@1.0.0, there is 
`export declare class NgcWebpackPlugin { `

Plugin but in new version is 

`export declare class AotPlugin { `

So it isn't even possible to build with angular-cli. 

because there is:
` plugins: [
            new webpack_1.NgcWebpackPlugin({
                project: path.resolve(projectRoot, appConfig.root, appConfig.tsconfig),
                baseDir: path.resolve(projectRoot, ''),
                entryModule: path.join(projectRoot, appConfig.root, 'app/app.module#AppModule'),
                genDir: path.join(projectRoot, appConfig.outDir, 'ngfactory')
            }),
        ]`

**Comment by filipesilva** [comment]
This should be fixed in beta.17.
