### ISSUE TITLE
Update default `tsconfig.json` options

### ISSUE THREAD

**Issue by dgp1130** [angular/angular-cli#26290]
### Command

new, update

### Description

It's been a while since we've looked at recent TypeScript configuration changes and refreshed the default Angular setup. We should review recent additions and changes to look for anything we want to enable in `ng new` as well as through `ng update` for existing apps.

Two options in particular which stand out:
* `moduleResolution: 'bundler'` - This seems appropriate given our esbuild / Webpack usage.
* `allowSyntheticDefaultImports: true` - I believe this is recommended by the TypeScript team.
* `esModuleInterop: true` - This is highly recommended for [our esbuild setup](https://angular.dev/tools/cli/esbuild#esm-default-imports-vs-namespace-imports) and maybe we should just make it the default.

We don't need to be specifically limited to these three options, but those are the immediate ones to consider.

**Comment by alan-agius4** [comment]
In version 17, for new apps we now enable `esModuleInterop`, which also enables `allowSyntheticDefaultImports`.

**Comment by zip-fa** [comment]
Also, should `downlevelIteration` be set to false by default in year of 2023? Do we really need to to support <ES2015?

**Comment by sonallux** [comment]
> Also, should `downlevelIteration` be set to false by default in year of 2023? Do we really need to to support <ES2015?

Starting with Angular CLI 17.0.1 in new generated workspaces `downlevelIteration` is no longer set (see https://github.com/angular/angular-cli/commit/f7f62c9d6988e6801981592f56137cd02bfe2316).

**Comment by alan-agius4** [comment]
Closing as this has been completed as part of version 18 where we added `moduleResolution: 'bundler'`
