### ISSUE TITLE
Expose postTransform to all builder APIs to allow index html manipulation

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#26299]
### Command

build, serve

### Description

We are dynamically generating our index.html through just-jeb/angular-builders because we have preconnect's set based on env vars and other stuff that cannot be done through JS.

Now we want to move to the Angular 17 application builders. But we cannot modify the index.html there. We already tried programmatically but buildApplication does not expose the transform plugin option from IndexHtmlGenerator.

### Describe the solution you'd like

The IndexHtmlGenerator already has an postTransformPlugin which only requires the option postTransform to be passed to it from the builders.

If we would pass this option to executePostBundleSteps and then to generateIndexHtml we can then modify the index.html.

### Describe alternatives you've considered

An angular.json property to a file that exports a default function that is passed to postTransform

**Comment by muuvmuuv** [comment]
[@angular-devkit__build-angular@17.0.0.patch](https://github.com/angular/angular-cli/files/13307133/%40angular-devkit__build-angular%4017.0.0.patch)

Here is a patch file that works.

**Comment by arnabk** [comment]
👍
