### ISSUE TITLE
application builder generates many initial chunks

### ISSUE THREAD

**Issue by jnizet** [angular/angular-cli#26307]
### Command

build

### Description

I just migrated a small project to v17 and the application builder.
The `ng build` command generates 13 *initial* (i.e. not lazy-loaded) bundles.

I don't know if it's expected or not, but if it is, I don't understand the point of having so many initial bundles (the browser builder used to generate only 3). 

Won't that automatically cause performance issues, given that browsers limit the number of concurrent requests to a given domain?

### Describe the solution you'd like

Unless there is a good reason (that I'm currently missing) for so many bundles, I'd like the builder to generate fewer bundles: one for the polyfills (that could be cached for a long time) and one for the application for example.

If there is a good reason for so many bundles, please enlighten me :-)

**Comment by pumano** [comment]
@jnizet that how esbuild works. If you don't use http/2 it's would be drop in core web vitals. esbuild has open issue https://github.com/evanw/esbuild/issues/207 but that is not implemented.

If you have http/2 setup that amount of chunks not an issue for you

**Comment by alan-agius4** [comment]
Indeed this is expected, this is becasue esbuild does cross chunk code motion which webpack does not, which results in a more smaller chunks. 

When using HTTP/2 or HTTP/3 the number of files does not have any performance penalty.

**Comment by jnizet** [comment]
OK. Too bad this isn't considered. 
Couldn't the CLI, which is able to know which chunks are initial and which chunks are lazy-loaded, concatenate the initial chunks generated by esbuild?

**Comment by alan-agius4** [comment]
@jnizet, containing the chunks will actually cause unnecessary code to be downloaded when navigating to a particular page. 

Thus, for a performance perspective, having a lot of chunks should be better if using modern HTTP protocols. Although I do see that sometimes esbuild does generate super small chunks under 1 kb, but that is by esbuild design.

Concatenating chunks is definitely not something the Angular CLI should be doing. The bundler has the full context of how chunks should be split to download as code as possible.

**Comment by elgerm** [comment]
@alan-agius4 when you say `should` be better, is this tested? How does esmbuild know which pages where are thus creating chunks per page as webpack builder does?

Our website shows very bad performance after upgrading to angular 17. Lighthouse reports too many chained requests (153 chunks!!):
![image](https://github.com/angular/angular-cli/assets/2996554/eeab1620-4bb2-4b30-81b0-37621566b128)

before with angular 16 it was only 3 chunks and much better perf:
![image](https://github.com/angular/angular-cli/assets/2996554/233d7321-a445-4e71-a9af-92ba66aae700)

**Comment by pumano** [comment]
@elgerm you are right, but check my message above, try to upgrade your http to http/2 or better http/3 to get better performance, because http 1.1 has only 6 parallel connections in browser, while http/2 has 100

**Comment by alan-agius4** [comment]
Hi @elgerm,

Which HTTP version are you using? In the case of HTTP 1 it is expected that there is a performance regression. It is also important mentioning that lighthouse should not ran against a the local dev-server. 

Esbuild performs code motion and splits the code based on it's usage which does create more chunks. This is described here: https://github.com/evanw/esbuild/blob/main/docs/architecture.md#code-splitting. Webpack has less chunks as it's unable to perform this sort of advanced optimization. 

What is the lighthouse score before and now?

**Comment by elgerm** [comment]
Hi guys, Lighthouse score went down from 70ish to 39.

We're behind cloudflare and have http3 enabled.

I switched back to 16 for now as this was unacceptable performance.

We get about 50k daily unique visitors from SE Asia, 33% use old devices and may find this unusable. Hence the question if it has been tested that so many small chunks don't degrade performance. There must be a penalty from loading and bootstrapping so many small chunks? 

Angular went from module based to component based and now switched to esbuild that now generates a chunk per component/directive/pipe. There's 450 chunks in the dist folder 🤯.

Is it possible to go back to webpack build w 17?

**Comment by pumano** [comment]
@elgerm its possível to use webpack with 17 angular. Just use browser target, not browser-esbuild

**Comment by SamanthaAdrichem** [comment]
Our system creates waay more than those 150 chunks, it's actually at 240 chunks. It is a rather large platform.

It's still fast though, but I would like the preload the be reduced/delayed.

Tbh, though Angular is made for larger systems. I often feel like they don't really test out the really really large systems like this.

**Comment by pumano** [comment]
what I really recommend to all as workaround is to use webpack for production and serve app for development with `--forceEsbuild=true` it run your project faster for development purposes, but production code build as previously using webpack. Some problems can be potentially found with background-image resolving difference, but in other cases all works same. We use it in our large app until `esbuild` not provide some solution for it.

**Comment by joewIST** [comment]
This is also an issue for us. Looks like we may need to revert to using webpack for production as well, as the chaining of chunks on initial load is causing non-trivial performance issues.

**Comment by born2net** [comment]
same here, our server is http (not http/2) and so we need a way to keep total files same as webpack. Any updates? solutions?

**Comment by sod** [comment]
> Any updates? solutions?

First step is look what is in those small chunks. Lets say it's lots of lodash-es code, because lodash is 200 little functions. You could use commonjs lodash instead. esbuild will still delete unused code, but won't rip it apart anymore, as it can't guarantee side effect freeness.

If your 500 byte chunks contain simple strings, you could move those strings behind a barrel.

e.g. if you have constants like here:
```ts
// constants-a.ts
export const foo = 'foo string';
export const bar = 'bar string';

// constants-b.ts
export const lorem = 'lorem string';
export const ipsum = 'ipsum string';
```

you create a barrel like:
```ts
// constants.ts
export * from './constants-a.ts';
export * from './constants-b.ts';
```

And if you `import {lorem} from 'constants'` it won't put `const lorem = 'lorem string';` into a chunk, as esbuild doesn't split chunks for barrels (at least right now, could of course change)

So there are some ways to bend esbuild to your will.

Third option might be, to contribute to esbuild something like a `minChunkSize` option like webpack has.

**Comment by SamanthaAdrichem** [comment]
Honestly I commented because the amount of chunks can be insane, and imho should be improved with better bundling/lazy loading.

but it is faster for us and working fine on chromebooks even. Cloudflare is caching it for free (and if you want you could even upload it to cloudflare workers)

Probably an Unpopular opinion, solutions because people are still on http1 should imho not happen. Use webpack then or upgrade your servers. Http 2 is from may 2015 and almost 9 years old now.

**Comment by LuisTovar0** [comment]
this issue is causing my colleagues to call me "the chunk man"

**Comment by mihailik** [comment]
How can we **post-process** this exponential explosion of files?

Shipping ESBuild mode in Angular without built-in handling of chunks makes it highly disruptive.

Apart from complicating debugging/diagnostics in browser, it rakes up deployment and support risks couple orders of magnitude.

Network errors during deployment are way more probable, being 100x more transactional updates to the filesystem.
It becomes impossible to spot partial/incomplete deployment.

Anecdotal case:

> * we used to have Angular15 deployment taking 20-30 minutes using rsync to transfer dist/ files
> * by using `webpack.optimize.MinChunkSizePlugin` we lowered it to 3-4 minutes
> * now we're risking going back to excessively long deployments, even way worse

If Angular team is not ready to improve the situation at this point, can you folks please give us direction and help adding customisations/plugin/script to implement chunk coalescing at the project side?
