### ISSUE TITLE
Upgrade Angular-CLI on Windows 10 with beta.17 fails to run

### ISSUE THREAD

**Issue by lekova** [angular/angular-cli#2631]
Tried to do the upgrade from beta.10 to beta.14 described in the wiki page and got a problem where the installation process is successful however I cannot run `ng --version`.

After couple of days I tried again (we are at beta.17) so I followed the same steps

- node update
- `npm uninstall angular-cli -g`
- `npm cache clean`
- `npm install angular-cli@latest -g`

I get the same problem as before:
![angular-cli windows](https://cloud.githubusercontent.com/assets/12982223/19241928/e1affbae-8ede-11e6-9767-b096bf5d346f.png)

**Comment by dzonatan** [comment]
Maybe you missed `version` property in `angular-cli.json` file. 
It should be updated to `1.0.0-beta.14` or `1.0.0-beta.17` as well.

**Comment by filipesilva** [comment]
Wait, is that *inside* the project? Since the upgrade process requires you to make a new project, your should do it outside of the existing project.

**Comment by lekova** [comment]
The `test` folder is empty. I tried to create new project inside it with `ng new test-project`. Just put `ng -v` there to demonstrate that `ng` is not running. Sorry for the confusion!

**Comment by filipesilva** [comment]
Hm.... this error can appear if there's a `node_modules` folder with an older version anywhere in the folder hierarchy. Do you get the same error if you do this in, say, `C:\test-folder\`?

**Comment by lekova** [comment]
@filipesilva, that is exactly the problem I had. There are projects with an older version in the folder tree where I was trying to install the latest angular-cli. So I did as you suggested, `cd to C:\`, `uninstall`, `cache clean` and `install latest`. Verified with `ng new` and `ng serve`. Thanks!!!

**Comment by filipesilva** [comment]
Glad to hear it's sorted!
