### ISSUE TITLE
Issue: Can't build/run a basic standalone Angular app SSR (or not) 

### ISSUE THREAD

**Issue by tom-laplace** [angular/angular-cli#26318]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I can't build/run a basic project using Angular 17. Even just after initialization.

### Minimal Reproduction

- ng new crash-test --standalone --ssr **OR** ng new crash-test --standalone
- npm i 
- npm run build **OR** npm run start

### Exception or Error

```text
src/app/app.component.ts:1:26:
      1 │ import { Component } from '@angular/core';
        ╵                           ~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@angular/core" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@angular/core" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@angular/common"

    src/app/app.component.ts:2:29:
      2 │ import { CommonModule } from '@angular/common';
        ╵                              ~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@angular/common" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@angular/common" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


✘ [ERROR] Could not resolve "@angular/router"

    src/app/app.component.ts:3:29:
      3 │ import { RouterOutlet } from '@angular/router';
        ╵                              ~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@angular/router" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@angular/router" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


✘ [ERROR] Could not resolve "@angular/router"

    src/app/app.config.ts:1:30:
      1 │ import { provideRouter } from '@angular/router';
        ╵                               ~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@angular/router" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@angular/router" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


✘ [ERROR] Could not resolve "@angular/common/http"

    src/app/app.config.ts:3:34:
      3 │ import { provideHttpClient } from '@angular/common/http';
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@angular/common" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@angular/common/http" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


✘ [ERROR] Could not resolve "@angular/platform-browser"

    src/main.ts:1:37:
      1 │ import { bootstrapApplication } from '@angular/platform-browser';
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "@angular/platform-browser" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "@angular/platform-browser" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


✘ [ERROR] Could not resolve "zone.js"

    angular:polyfills:angular:polyfills:1:7:
      1 │ import 'zone.js';
        ╵        ~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "zone.js" here because it's not listed as a dependency of this package:

    ../../../../.pnp.cjs:38:33:
      38 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "zone.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

### Your Environment

```text
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: linux x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0
@angular-devkit/core         17.0.0
@angular-devkit/schematics   17.0.0
@angular/cli                 17.0.0
@schematics/angular          17.0.0
```

**Comment by alan-agius4** [comment]
I am a bit confused, are you using Yarn PNP or NPM? In the repro steps you mention `npm i` but the errors suggest that you are using Yarn PNP

**Comment by tom-laplace** [comment]
> I am a bit confused, are you using Yarn PNP or NPM? In the repro steps you mention `npm i` but the errors suggest that you are using Yarn PNP

Yup that confuse me too as I’m using NPM and not Yarn

**Comment by alan-agius4** [comment]
@tom-laplace, I am unable to replicate this using the steps provided. Based on the error, It does look like you might have some Yarn PNP config up in the file system.

**Comment by tom-laplace** [comment]
> @tom-laplace, I am unable to replicate this using the steps provided. Based on the error, It does look like you might have some Yarn PNP config up in the file system.

Just erased all the installation of Yarn on my machine, still don't work.

The strangiest is that I created a project yesterday, worked perfectly and I can still run it.

**Comment by krasi** [comment]
Removing the nodeLinker (the whole .yarnrc.yml file) fixed it for me - https://yarnpkg.com/features/pnp#when-migrating-an-existing-project

**Comment by Tony133** [comment]
Hi all,
Today while I was testing the new version of Angular v17.x I also encountered a similar problem (see screenshot):

<img width="1449" alt="screen-error" src="https://github.com/angular/angular-cli/assets/11542387/033debd9-84a1-4732-919e-080eed1c3eba">

checking the hidden files in the root in my computer I noticed that there was a `pnp.cjs` file which I believe is generated there when I installed packages globally, pnpm or libraries for the various projects I am working on, and deleting this file the angular application works correctly and no longer gives me any errors.

The angular application was created by cli, to create a new project.

If you need it, I'll attach the file I deleted, I'll rewrite it here, it's called `pnp.cjs`

I hope I was helpful 🙂

**Comment by csisy-btw** [comment]
It seems someone else opened a similar issue but it was closed for whatever reason: #26379

**Comment by alan-agius4** [comment]
Based on the comments above and the existence of a `pnp.cjs` file this is working as expected. 

See: https://github.com/evanw/esbuild/issues/3338 and https://github.com/evanw/esbuild/issues/2495#issuecomment-1227269139

@csisy and @csisy-btw you issues are unrelated to this, so please open a new issue together with a minimal reproduction.

**Comment by Truenotierra73** [comment]
> Hi all, Today while I was testing the new version of Angular v17.x I also encountered a similar problem (see screenshot):
> 
> <img alt="screen-error" width="1449" src="https://user-images.githubusercontent.com/11542387/282246963-033debd9-84a1-4732-919e-080eed1c3eba.png">
> checking the hidden files in the root in my computer I noticed that there was a `pnp.cjs` file which I believe is generated there when I installed packages globally, pnpm or libraries for the various projects I am working on, and deleting this file the angular application works correctly and no longer gives me any errors.
> 
> The angular application was created by cli, to create a new project.
> 
> If you need it, I'll attach the file I deleted, I'll rewrite it here, it's called `pnp.cjs`
> 
> I hope I was helpful 🙂

It's correct. By deleting this file, the project is compiled again.

**Comment by Tweniee** [comment]
> > Hi all, Today while I was testing the new version of Angular v17.x I also encountered a similar problem (see screenshot):
> > <img alt="screen-error" width="1449" src="https://user-images.githubusercontent.com/11542387/282246963-033debd9-84a1-4732-919e-080eed1c3eba.png">
> > checking the hidden files in the root in my computer I noticed that there was a `pnp.cjs` file which I believe is generated there when I installed packages globally, pnpm or libraries for the various projects I am working on, and deleting this file the angular application works correctly and no longer gives me any errors.
> > The angular application was created by cli, to create a new project.
> > If you need it, I'll attach the file I deleted, I'll rewrite it here, it's called `pnp.cjs`
> > I hope I was helpful 🙂
> 
> It's correct. By deleting this file, the project is compiled again.

I am using Ubuntu 22.04 and i don't think this file is present in my system, not able to solve 
please share details

**Comment by kennethkeim** [comment]
Should this be picking up `.pnp.cjs` in the root of my computer as well? I removed it there and it's working now.
