### ISSUE TITLE
When less supports javascript, it always compiles 2 extra times.

### ISSUE THREAD

**Issue by cipchk** [angular/angular-cli#26310]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In #25572, to support less JavaScript issues, `javascriptEnabled` will be enabled only when a compile-time exception is attempted.

But as a result, less will be compiled twice every time it is updated under the `ng s` command. 

Hope the `javascriptEnabled` mark can be confirmed the first time.

### Minimal Reproduction

```
ng new demo
ng add ng-zorro-antd@17.0.0-beta.0
ng s --force-esbuild
```

### Your Environment

```text
Angular CLI: 17.0.0
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: darwin x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cli                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment]
Hi, 

Just to be clear, only the LESS file that requires `javascriptEnabled` are compiled twice. In general, allowing `javascriptEnabled` by default is not something that we want to do.

- This option has deprecated by LESS as it causes code injection vulnerabilities.
- Support for  `javascriptEnabled` will be removed in the Angular CLI version 19.

I would strongly recommend that if you are using libraries that require `javascriptEnabled`, you reach out to them to move away from the deprecated behaviour.

**Comment by cipchk** [comment]
I quite agree with you.

Currently, NG-ZORRO cannot break away from JavaScript, at least not in Angular 17.

I still hope that JavaScript support can be optimized. At the same time, we will try our best to solve the problem of no longer relying on JavaScript.

**Comment by alan-agius4** [comment]
Closing as per https://github.com/angular/angular-cli/issues/26310#issuecomment-1805301311
