### ISSUE TITLE
Migration failed: 404 Not Found - when upgrading angular project in a monorepo

### ISSUE THREAD

**Issue by vlio20** [angular/angular-cli#26311]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a monoripo project which contains both apps and libs. The libraries are not published on npm. When running the ng update command I am getting the following error:
Migration failed: 404 Not Found - GET https://registry.npmjs.org/@oogaday%2fshared - Not found

oogaday-shared is a shared library that I am using for my project.

Woraround: remove the lib dependancy and bring it back again after the update. 

### Minimal Reproduction

Create a monoripo with dependancy on a local package that is not published on npm.

This is how the monorepo package.json looks like:
```
{
  "name": "cockpit",
  "version": "1.0.0",
  "scripts": {
    "build": "",
    "start": ""
  },
  "author": "Vlad Ioffe",
  "workspaces": [
    // ....
    "apps/oogaday-webapp",
    "libs/oogaday-shared",  ],
  "dependencies": {
  }
}
```

And this is how the webapp package.json looks like:
```
  "dependencies": {
    //...
    "@oogaday/shared": "^1.0.0",
  },
  ```

### Exception or Error

```text
Migration failed: 404 Not Found - GET https://registry.npmjs.org/@oogaday%2fshared - Not found
```

### Your Environment

```text
Angular CLI: 16.2.2
Node: 18.14.1
Package Manager: npm 9.3.1
OS: darwin arm64

Angular: 16.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.2
@angular-devkit/build-angular   16.2.2
@angular-devkit/core            16.2.2
@angular-devkit/schematics      16.2.2
@angular/cdk                    16.2.4
@angular/cli                    16.2.2
@angular/material               16.2.4
@nguniversal/builders           16.2.0
@nguniversal/express-engine     16.2.0
@schematics/angular             16.2.2
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by alan-agius4** [comment]
`ng update` does not support `yarn workspaces`.  See: https://github.com/angular/angular-cli/issues/14841

**Comment by vlio20** [comment]
@alan-agius4 it is not a yarn workspace. It is an npm workspace. 
https://docs.npmjs.com/cli/v7/using-npm/workspaces

**Comment by alan-agius4** [comment]
Ah sorry you are right. Although there are the same concept.
