### ISSUE TITLE
ng serve not detecting file changes

### ISSUE THREAD

**Issue by KatzRuslan** [angular/angular-cli#26325]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

Generate a brand new project ng new project
Select scss and all other defaults
run npm start
any changes 4.a change *.ts 4.b change *.html 4.c change *.css
save file

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`

**Comment by KatzRuslan** [comment]
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)

Ruslan Katz




пт, 10 нояб. 2023 г. в 16:46, Alan Agius ***@***.***>:

**Comment by mguay22** [comment]
We're also seeing this from migrating to `@angular-devkit/build-angular:application`.

Interestingly the dev server is picking up changes to `ts` and `scss` but completely ignores `html`.

**Comment by KatzRuslan** [comment]
The dev server isn't picking up changes to ts, html and scss at all.
Do you have some solution?

Ruslan Katz




пт, 10 нояб. 2023 г. в 17:38, Michael Guay ***@***.***>:

**Comment by janerikmai** [comment]
cannot confirm 100%. watch and reload works for me on apple silicon with node 20.9 and cli@17.0.0 

<img width="752" alt="Screenshot 2023-11-10 at 21 55 31" src="https://github.com/angular/angular-cli/assets/2346648/cd240fa0-ad05-40b6-bb6e-ab532b13ac72">

<img width="707" alt="Screenshot 2023-11-10 at 21 50 31" src="https://github.com/angular/angular-cli/assets/2346648/4be9a65e-6e57-47d1-80ca-482424cd9d35">

but **does not** recover from error after fix and save for (s)css files.

broke scss, saved, fixed, saved,... will not recover from error
<img width="824" alt="Screenshot 2023-11-10 at 21 51 52" src="https://github.com/angular/angular-cli/assets/2346648/717089d7-69fe-4c42-95ae-eddc52e863b0">

**Comment by naveedahmed1** [comment]
I am also facing the same issue, it sometimes work and sometimes it doesn't. Most of the times it detect changes a few times and then suddenly stops deteting the changes.

**Comment by reduckted** [comment]
> BUT it seems not to recover from broken scss (angular-sass) code

This is exactly what I'm experiencing as well. Changes to `.scss` files are compiled by the CLI successfully and loaded correctly in the browser _until_ there's a compilation error. Once you fix that compilation error in the file, the CLI continues to report a compilation error.

**Comment by Alecto** [comment]
Confirm the same issue

**Comment by WDrzewiecki** [comment]
In my case, a similar problem began to occur after migrating to application builder (it was fine while using webpack). It turned out that the server did not detect file changes when the source directory name started with a dot (.). Changing the folder name so that it does not start with a dot solved the problem for me
