### ISSUE TITLE
Bring back --deploy-url

### ISSUE THREAD

**Issue by jsloyer** [angular/angular-cli#26357]
### Command

build

### Description

With Angular 16 you could build your app with `ng build --build-href=/my/awesome/app --deploy-url=/my/awesome/app`, this was incredibly useful for SSR and Universal.  Static assets and the node SSR server would run under the same URI's and assets and SSR functionality get served together.

With Angular 17 `--deploy-url` was removed.  The explanation at https://github.com/angular/angular-cli/issues/23765#issuecomment-1225508049 makes sense for a CSR app but not a SSR or SSG app.  The docs mention using `APP_BASE_HREF` and `base-href` but those URI's together do not move assets like `main.js`, `polyfills.js`, and `styles.js` to `/my/awesome/app`.

I understand if this was intentional but would love some documentation on a path forward here.  Obviously one solution would be to use Nginx and rewrite URL's on the fly.  If that is the official path, happy to do it but would love some guidance

**Comment by benbro** [comment]
I was using __webpack_public_path__ with the webpack builder to set the url dynamically. [esbuild doesn't support](https://github.com/evanw/esbuild/issues/1441) such setting.

**Comment by jsloyer** [comment]
@benbro got any code examples on your config? 😀

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

There is also large thread around `deploy-url` in https://github.com/angular/angular-cli/issues/22113.

**Comment by jsloyer** [comment]
opened up https://stackoverflow.com/questions/77482261/angular-universal-17-alternatives-to-deployurl

**Comment by TheTomasJ** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
> 
> There is also large thread around `deploy-url` in #22113.

did angular team ever considered following setup?:

APP_BASE_HREF = '/' because app should work under www.example.com
base-href = '/' because common relative links opened in new tab (ctrl + click) should work under www.example.com
deployUrl = 'www.cdn.com' because CDN is must?

i believ this scenario was never been considered and removing deployUrl was a mistake

**Comment by TheTomasJ** [comment]
> Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.
> 
> If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
> 
> There is also large thread around `deploy-url` in #22113.

Hello, did angular team ever considered following use case?

relative links opened on new tab (via ctrl + click) should still go under to '/'
assets links should point to different domain?

I still believe, removing deploy url is mistake and showstopper.
