### ISSUE TITLE
[esbuild] SSR: server.ts file ignored for "ng serve"

### ISSUE THREAD

**Issue by Burgov** [angular/angular-cli#26354]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

So we've been using SSR for a few years already and we have a lot of custom logic in our server.ts file. Most notably, it contains a proxy to the API (so that it can be deployed separately, but accessed by the browser on the same domain), but also some other special proxies like the webmanifest file, a styling file that the API generates (tenant specific) and a special reroute for print specific rendering.

While I was trying to get the new application builder to work with our code, I noticed that while running `ng serve`, the `server.ts` file is completely ignored. Only when running `ng build` and then running the output does this file get included. 

This is a change that I could not find documented anywhere and I'm wondering what the reason for this change is. It forces us to kind of redo this whole part altogether if we want to keep everything working while developing locally.

Apologies if this isn't the right place for this topic.

### Minimal Reproduction

-

### Your Environment

```text
Angular CLI: 17.0.0
Node: 18.17.1
Package Manager: npm 9.8.1
OS: darwin arm64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cdk                    17.0.0
@angular/cli                    17.0.0
@angular/fire                   16.0.0
@angular/google-maps            17.0.0
@angular/material               17.0.0
@angular/ssr                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
webpack                         5.88.2
zone.js                         0.14.2
```

**Comment by eneajaho** [comment]
This is almost the same as this issue: 
https://github.com/angular/angular-cli/issues/26323
