### ISSUE TITLE
Provide an option for library sourcemap for the application builder

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular-cli#26359]
### Command

build

### Description

When using the webpack builder we could use the `sourceMap: {vendor:true}` option to access the source map of libraries (like the Angular framework). 

This doesn't work anymore with the application builder (likely because there is no vendor chunk anymore).

**Comment by alan-agius4** [comment]
This option still exists and works in the application builder.

**Comment by JeanMeche** [comment]
Do you mind double checking @alan-agius4 ? It doesn't work for me on this repro: https://github.com/jeanmeche/animations.

**Comment by alan-agius4** [comment]
```
ng b --configuration=development
```

chunk-KZGAGCFB.js.map
```
{
  "version": 3,
  "sources": [
    "../../packages/animations/browser/src/error_helpers.ts",
    "../../packages/animations/browser/src/render/web_animations/animatable_props_set.ts",
    "../../packages/animations/browser/src/render/shared.ts",
    "../../packages/animations/browser/src/render/animation_driver.ts",
    "../../packages/animations/browser/src/dsl/style_normalization/animation_style_normalizer.ts",
    "../../packages/animations/browser/src/util.ts",
    "../../packages/animations/browser/src/dsl/style_normalization/web_animations_style_normalizer.ts",
    "../../packages/animations/browser/src/warning_helpers.ts",
    "../../packages/animations/browser/src/dsl/animation_transition_expr.ts",
    "../../packages/animations/browser/src/dsl/animation_ast_builder.ts",
    "../../packages/animations/browser/src/dsl/animation_timeline_instruction.ts",
    "../../packages/animations/browser/src/dsl/element_instruction_map.ts",
    "../../packages/animations/browser/src/dsl/animation_timeline_builder.ts",
    "../../packages/animations/browser/src/dsl/animation_transition_instruction.ts",
    "../../packages/animations/browser/src/dsl/animation_transition_factory.ts",
    "../../packages/animations/browser/src/dsl/animation_trigger.ts",
```

**Comment by JeanMeche** [comment]
Ok, I have the same output but neither Chrome nor Firefox are able to pick them up.

**Comment by alan-agius4** [comment]
For me it is working as expected.
<img width="763" alt="Screenshot 2023-11-15 at 11 00 57" src="https://github.com/angular/angular-cli/assets/17563226/0abcb46a-5e5c-49c2-95b1-69afa6ec2507">

**Comment by alan-agius4** [comment]
I did however notice that vendor sourcemaps are not working in vite. https://github.com/angular/angular-cli/pull/26363

**Comment by JeanMeche** [comment]
Thank you for the swift fix. Can confirm that it works correctly !
