### ISSUE TITLE
No matching version found for @angular/compiler@16.12.2

### ISSUE THREAD

**Issue by kupchic** [angular/angular-cli#26365]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

![image](https://github.com/angular/angular-cli/assets/60134428/c8ae44cd-0aea-4073-8c77-0f5512db235c)

### Minimal Reproduction

try to update ng version to 16 with `ng update` and manually. in both cases see this error

### Your Environment

```text
"dependencies": {
    "@angular-architects/module-federation": "^16.0.4",
    "@angular/animations": "~16.2.12",
    "@angular/cdk": "16.2.12",
    "@angular/common": "~16.2.12",
    "@angular/compiler": "~16.2.11",
    "@angular/core": "16.2.12",
    "@angular/elements": "~16.2.12",
    "@angular/forms": "~16.2.12",
    "@angular/localize": "~16.2.12",
    "@angular/platform-browser": "~16.2.12",
    "@angular/platform-browser-dynamic": "~16.2.12",
    "@angular/router": "~16.2.12",
```

**Comment by alan-agius4** [comment]
16.12.2 has been released on the public NPM registry 13 days ago. https://www.npmjs.com/package/@angular/compiler?activeTab=versions

If you are using a NPM proxy or mirror make sure that this a properly synced.
