### ISSUE TITLE
Support Raw Loading with `application` and `builder-esbuild`

### ISSUE THREAD

**Issue by mcdenhoed** [angular/angular-cli#26368]
### Command

build, serve

### Description

I have some raw text files that I need to include in my build. To load them with `builder`-based builds, I am using the webpack [raw-loader](https://www.npmjs.com/package/raw-loader) plugin.

I currently import them as follows:

```typescript
import contents from "raw-loader!./some-text-file.txt";
```

It would be amazing if I could do something similar from within the new `esbuild`-based loader. I saw that [`vite` allows for a `?raw` suffix on imports](https://vitejs.dev/guide/assets.html#importing-asset-as-string) to do just this, but it did not seem to work when I tried it in Angular.

Hopefully I'm just missing something here, but I didn't see this called out in the documentation.

**Comment by clydin** [comment]
You can actually use `import contents from "./some-text-file.txt";`

To avoid a TypeScript error, you'll also need to add a type definition file (e.g., `src/types.d.ts`) with the following:
```
declare module "*.txt" {
  const content: string;
  export default content;
}
```

**Comment by mcdenhoed** [comment]
Good to know, thanks! One follow-up question. Should this work for extensions other than `.txt`? I'm trying to use it on other extensions and am getting a message about no loader being configured for that extension.

**Comment by clydin** [comment]
Currently just `.txt` extensions but we are evaluating the inclusion an additional build option to support configuring other extensions.

**Comment by mcdenhoed** [comment]
That would be a big 👍 from me. My specific use-case is that I'm bundling `.frag` and `.vert` WebGL shader sources, and it's nice to keep those with their real extension so that the IDE handles them properly.

**Comment by clydin** [comment]
> That would be a big 👍 from me. My specific use-case is that I'm bundling `.frag` and `.vert` WebGL shader sources, and it's nice to keep those with their real extension so that the IDE handles them properly.

This is now in review here: https://github.com/angular/angular-cli/pull/26371

**Comment by mcdenhoed** [comment]
Awesome, thank you!!
