### ISSUE TITLE
Angular CLI should warn when configurations are being overriden.

### ISSUE THREAD

**Issue by roedoejet** [angular/angular-cli#26361]
### Command

build

### Description

Thanks for all your work on this great framework!

We have a single application that can has multiple different configurations depending on both the application and deployment environment. 

For example:

```json
"configurations": {
            "fr": {
              "fileReplacements": [
                {
                  "replace": "projects/word-weaver/src/config/config.ts",
                  "with": "projects/word-weaver/src/config/config.fr.ts"
                }
              ]
            },
            "moh": {
              "fileReplacements": [
                {
                  "replace": "projects/word-weaver/src/config/config.ts",
                  "with": "projects/word-weaver/src/config/config.moh.ts"
                }
              ]
            },
          "ghpages": {
              "fileReplacements": [
                {
                  "replace": "projects/word-weaver/src/environments/environment.ts",
                  "with": "projects/word-weaver/src/environments/environment.ghpages.ts"
                }
              ]
            },
            "netlify": {
              "fileReplacements": [
                {
                  "replace": "projects/word-weaver/src/environments/environment.ts",
                  "with": "projects/word-weaver/src/environments/environment.netlify.ts"
                }
              ]
            }
}
```

Currently, running `ng build --configuration=ghpages,moh` just silently ignores the file replacements defined by the `ghpages` configuration.

### Describe the solution you'd like

We would ideally like to build our application using the following commands:

`ng build --configuration=ghpages,fr` or `ng build --configuration=ghpages,moh` or `ng build --configuration=ghpages,fr` or `ng build --configuration=netlify,moh` depending on where we are deploying and how we want to configure our application.

However, as has been raised in multiple other issues (https://github.com/angular/angular-cli/issues/22424, https://github.com/angular/angular-cli/issues/11149, https://github.com/angular/angular-cli/issues/16688), merging `fileReplacements` across multiple configurations is not supported. 

I would strongly prefer (and indeed our entire team expected) the functionality to be as described [here](https://github.com/angular/angular-cli/issues/16688#issuecomment-603714485). But, in the absence of that being supported - I think there should be a warning produced by Angular CLI since currently running `ng build --configuration=ghpages,moh` just silently ignores the file replacements defined by the `ghpages` configuration.

### Describe alternatives you've considered

Currently we have to create different configurations for each combination which has quickly led to a dozen configurations in some projects which is frustrating to manage and not very DRY. I hope there is a better solution in the future, but a warning when certain configurations are being ignored would also be better than the current implementation.

**Comment by alan-agius4** [comment]
The Angular CLI similar to TypeScript works by overridden the options and not merging. This is documented in https://angular.io/guide/workspace-config#alternate-build-configurations.

This does not apply soley to the `fileReplacements` but all the options. In this case, adding warning for each override would be too verbose.
