### ISSUE TITLE
Autoprefixer Not Working on Serve and Build

### ISSUE THREAD

**Issue by emiryumak** [angular/angular-cli#26366]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.0.2

### Description

Autoprefixer not working on scss compiler. For example:

In component.scss file;
`mask-composite: exclude;`

On chromium based browser says;
Invalid property name.

In version 16, it also added `-webkit` and `-moz` version of properties.

### Minimal Reproduction

This issue occurs when `ng serve` and `ng build`

My `angular.json` architect.build 

```javascript
"build": {
	"builder": "@angular-devkit/build-angular:application",
	"options": {
		"outputPath": "dist/app",
		"index": "src/index.html",
		"browser": "src/main.ts",
		"polyfills": ["zone.js"],
		"tsConfig": "tsconfig.app.json",
		"inlineStyleLanguage": "scss",
		"assets": [
			"src/assets",
			"src/manifest.webmanifest"
		],
		"styles": [
			"src/assets/style/styles.scss"
		],
		"stylePreprocessorOptions": {
			"includePaths": ["src/assets/style"]
		},
		"scripts": [],
		"server": "src/main.server.ts",
		"prerender": false,
		"ssr": {
			"entry": "server.ts"
		}
	},
	"configurations": {
		"production": {
			"budgets": [
				{
					"type": "initial",
					"maximumWarning": "2mb",
					"maximumError": "5mb"
				},
				{
					"type": "anyComponentStyle",
					"maximumWarning": "6kb",
					"maximumError": "50kb"
				}
			],
			"fileReplacements": [
				{
					"replace": "src/environments/environment.ts",
					"with": "src/environments/environment.prod.ts"
				}
			],
			"outputHashing": "all"
		},
		"development": {
			"optimization": false,
			"extractLicenses": false,
			"sourceMap": true
		}
	},
	"defaultConfiguration": "production"
}
``` 

### Your Environment

```text
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin arm64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0 (cli-only)
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            16.0.6
@angular-devkit/schematics      17.0.0
@angular/cdk                    17.0.0
@angular/cli                    17.0.0
@angular/ssr                    17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

Package Manager: `npm`
OS: `MacOS`
Browser: `Arc Browser (Chromium based)`, `Mozilla Firefox Developer Edition`, `Safari` etc.

**Comment by alan-agius4** [comment]
In this case, Esbuild is not prefixing this particular property.

**Comment by Emil-Blomquist** [comment]
Experiencing a similar problem but with the `width: stretch` value.

**Comment by emiryumak** [comment]
This not just mask-composite. This property is an example. Also does not work on mask.

**Comment by AliKholmatov** [comment]
the same. are there any updates?

**Comment by AliKholmatov** [comment]
https://stackblitz.com/edit/stackblitz-starters-6xjpwo?file=my-app%2Fsrc%2Fapp%2Fapp.component.scss
just stackblitz for example , it is repro only for new build - esbuild

**Comment by Emil-Blomquist** [comment]
It seems that some properties are actually being handled. From a brand new angular project I obtained the following results when running `ng serve`.

in

```css
background: linear-gradient(to right, white, gray);
width: stretch;
user-select: none;
``` 

out (when inspecting the element)

```css
background: linear-gradient(to right, white, gray);
width: stretch;
-webkit-user-select: none;
user-select: none;
```

**Comment by alan-agius4** [comment]
The esbuild pipeline does not use autoprefixer, instead it relies on esbuild do the the vendor prefixing. 

In the case you are experiencing a property or value that is not being vendor prefixed correctly. Please feel free to file an issue directly with https://github.com/evanw/esbuild.

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/26440
