### ISSUE TITLE
Compared with the earlier version, the chunk-xxx.js file is added after the "builder": "@angular-devkit/build-angular:browser-esbuild" configuration is used. Why? Can chunk files not be generated, or can chunk file names be specified?

### ISSUE THREAD

**Issue by fengnian7** [angular/angular-cli#26377]
### Command

build

### Description

After the Angular is upgraded to version 16, the builder @angular-devkit/build-angular:browser-esbuild is used, Compared with the earlier version, the chunk-xxx.js file is added after the "builder": "@angular-devkit/build-angular:browser-esbuild" configuration is used. Why? Can chunk files not be generated, or can chunk file names be specified?

### Describe the solution you'd like

In some scenarios, compilation files need to be dynamically obtained. Currently, a chunk is added and its name is not fixed. Therefore, static files cannot be matched. So I hope chunk-xxx.js  is not generated or the file name can be customized.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
