### ISSUE TITLE
File 'src\main.ts' is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by toddhd** [angular/angular-cli#26379]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

 I am running Node v18.17.1 and Angular 17 which I just downloaded yesterday. I created a new project yesterday, it worked fine, went to bed. Got up, went to go keep working on the project, and got the error below (main.ts is missing).

After a while I gave up, decided to just create new project all over again, so I created a new project. (ng new test) and chose scss and no precompile support. When I go to run the project, I get the error again.

```
- Building...X [ERROR] File 'src\main.ts' is missing from the TypeScript compilation. [plugin angular-compiler]
  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.
```
Here is my package.json:
```
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/router": "^17.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.1",
    "@angular/cli": "^17.0.1",
    "@angular/compiler-cli": "^17.0.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.2.2"
  }
}
```

I'm not sure how to fix this?

### Minimal Reproduction

This happens upon creation of a new project for me. 

`ng new test`

When asked, select "SCSS" for CSS, and "No" to the question of precompilation features. 

When the project is complete, change to the newly created "test" folder and run

`ng s --o`

Error appears during build. 

### Exception or Error

```text
- Building...X [ERROR] File 'src\main.ts' is missing from the TypeScript compilation. [plugin angular-compiler]
  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.
```

### Your Environment

```text
Angular CLI: 17.0.1
Node: 18.17.1
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.1
@angular-devkit/build-angular   17.0.1
@angular-devkit/core            17.0.1
@angular-devkit/schematics      17.0.1
@angular/cli                    17.0.1
@schematics/angular             17.0.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

This was literally working the evening before. The last thing I did before bed was run the app. I woke up this morning, went to go run it again, and this error appeared. 

I would also like to note that I have also tried to uninstall (using npm uninstall, plus I cleared the cache) and reinstall Angular, it made no difference.

**Comment by alan-agius4** [comment]
Mind sharing the broken project please?

**Comment by toddhd** [comment]
Thanks Alan, please tell me the best way to do that? Should I zip up "test" and send it to you? (Perhaps minus the "node_modules")?

**Comment by toddhd** [comment]
FYI, I updated to the latest LTS of Node.js and NPM as well. 

$ npm -v
10.2.3

$ node -v
v20.9.0

Angular CLI: 17.0.0                                               
Node: 20.9.0                                                      
Package Manager: npm 10.2.3                                       
OS: win32 x64                                                     
                                                                  
Angular: 17.0.2                                                   
... animations, common, compiler, compiler-cli, core, forms       
... platform-browser, platform-browser-dynamic, platform-server   
... router                                                        
                                                                  
Package                         Version                           
---------------------------------------------------------         
@angular-devkit/architect       0.1700.0                          
@angular-devkit/build-angular   17.0.0                            
@angular-devkit/core            17.0.0                            
@angular-devkit/schematics      17.0.0                            
@angular/cli                    17.0.0                            
@angular/ssr                    17.0.0                            
@schematics/angular             17.0.0                            
rxjs                            7.8.1                             
typescript                      5.2.2                             
zone.js                         0.14.2                            

When I create a new project now, I see this at the end...



$ ng n test
? Which stylesheet format would you like to use? SCSS   [
https://sass-lang.com/documentation/syntax#scss                ]
? Do you want to enable Server-Side Rendering (SSR) and Static Site Generation
(SSG/Prerendering)? No
CREATE test/angular.json (2756 bytes)
CREATE test/package.json (1035 bytes)
CREATE test/README.md (1058 bytes)
CREATE test/tsconfig.json (877 bytes)
CREATE test/.editorconfig (274 bytes)
CREATE test/.gitignore (548 bytes)
CREATE test/tsconfig.app.json (263 bytes)
CREATE test/tsconfig.spec.json (273 bytes)
CREATE test/.vscode/extensions.json (130 bytes)
CREATE test/.vscode/launch.json (470 bytes)
CREATE test/.vscode/tasks.json (938 bytes)
CREATE test/src/main.ts (250 bytes)
CREATE test/src/favicon.ico (15086 bytes)
CREATE test/src/index.html (290 bytes)
CREATE test/src/styles.scss (80 bytes)
CREATE test/src/app/app.component.html (20884 bytes)
CREATE test/src/app/app.component.spec.ts (910 bytes)
CREATE test/src/app/app.component.ts (363 bytes)
CREATE test/src/app/app.component.scss (0 bytes)
CREATE test/src/app/app.config.ts (227 bytes)
CREATE test/src/app/app.routes.ts (77 bytes)
CREATE test/src/assets/.gitkeep (0 bytes)
√ Packages installed successfully.
warning: in the working copy of '.editorconfig', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.gitignore', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.vscode/extensions.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.vscode/launch.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.vscode/tasks.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'angular.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package-lock.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'package.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/app/app.component.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/app/app.component.spec.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/app/app.component.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/app/app.config.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/app/app.routes.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/main.ts', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/styles.scss', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tsconfig.app.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tsconfig.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tsconfig.spec.json', LF will be replaced by CRLF the next time Git touches it
    Successfully initialized git.

**Comment by toddhd** [comment]
[test.zip](https://github.com/angular/angular-cli/files/13379731/test.zip)
Here is the project, minus the node_modules

**Comment by alan-agius4** [comment]
The `LF will be replaced by CRLF the next time Git touches it` is just a warning that can safely be ignored. Regarding the errors I am unable to replicate using the reproduction provided.

```
ng s -o

Initial Chunk Files | Names         |  Raw Size
polyfills.js        | polyfills     |  82.71 kB |
main.js             | main          |  23.36 kB |
styles.css          | styles        |  96 bytes |

                    | Initial Total | 106.17 kB

Application bundle generation complete. [10.193 seconds]
Watch mode enabled. Watching for file changes...
  ➜  Local:   http://localhost:4200/
```

**Comment by toddhd** [comment]
Let me ask you this. It's weird that this is happening, and while I understand your comment about the LF's, I noted it to simply point out that something has "changed". I don't normally get those warninigs, and I didn't get them yesterday when I created the initial project which ran just fine... until this morning, when it STOPPED running fine. 

Which leads me to wonder if the problem has nothing to with what's on my PC, and perhaps everything to do with NPM? I know you probably aren't an NPM expert, but it is possible that when NPM goes to grab files for a build, that it is getting corrupt files? Does everyone get their NPM files from the same source, or is possible that someone in Boston is getting their files from a different location than someone in Los Angeles? If so, maybe you can't reproduce it because you aren't getting them from the same source as I am?

**Comment by alan-agius4** [comment]
> Let me ask you this. It's weird that this is happening, and while I understand your comment about the LF's, I noted it to simply point out that something has "changed". I don't normally get those warninigs, and I didn't get them yesterday when I created the initial project which ran just fine... until this morning, when it STOPPED running fine.

The mentioned warnings were always present on windows unless `core.autocrlf` was set to `false`. (via `git config --global core.autocrlf false`).

> Which leads me to wonder if the problem has nothing to with what's on my PC, and perhaps everything to do with NPM? I know you probably aren't an NPM expert, but it is possible that when NPM goes to grab files for a build, that it is getting corrupt files? Does everyone get their NPM files from the same source, or is possible that someone in Boston is getting their files from a different location than someone in Los Angeles? If so, maybe you can't reproduce it because you aren't getting them from the same source as I am?

The errors you are setting do not seem to be caused by corrupted NPM packages, to be honest I never encountered  corrupted NPM packages being downloaded from public NPM registry. While not everyone get the NPM package from the same server, there are checks in place for that to ensure that the downloaded package is not corrupted.

**Comment by toddhd** [comment]
Thanks. I'm not sure what else to try then? Here is a link to a video I made of what I'm doing, and what I'm seeing, on my end. Maybe this will help? 
https://www.youtube.com/watch?v=Ges2910U_gs

**Comment by alan-agius4** [comment]
```
PS C:\temp> ng new test
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
? Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No
CREATE test/angular.json (2756 bytes)
CREATE test/package.json (1035 bytes)
CREATE test/README.md (1058 bytes)   
CREATE test/tsconfig.json (877 bytes)
CREATE test/.editorconfig (274 bytes)
CREATE test/.gitignore (548 bytes)
CREATE test/tsconfig.app.json (263 bytes)
CREATE test/tsconfig.spec.json (273 bytes)
CREATE test/.vscode/extensions.json (130 bytes)
CREATE test/.vscode/launch.json (470 bytes)
CREATE test/.vscode/tasks.json (938 bytes)
CREATE test/src/main.ts (250 bytes)
CREATE test/src/favicon.ico (15086 bytes)
CREATE test/src/index.html (290 bytes)
CREATE test/src/styles.scss (80 bytes)
CREATE test/src/app/app.component.html (20884 bytes)
CREATE test/src/app/app.component.spec.ts (910 bytes)
CREATE test/src/app/app.component.ts (363 bytes)
CREATE test/src/app/app.component.scss (0 bytes)
CREATE test/src/app/app.config.ts (227 bytes)
CREATE test/src/app/app.routes.ts (77 bytes)
CREATE test/src/assets/.gitkeep (0 bytes)
✔ Packages installed successfully.
warning: LF will be replaced by CRLF in .editorconfig.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .gitignore.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .vscode/extensions.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .vscode/launch.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in .vscode/tasks.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in angular.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package-lock.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.component.html.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.component.spec.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.component.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.config.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/app/app.routes.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/main.ts.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in src/styles.scss.
The file will have its original line endings in your working directory
warning: adding embedded git repository: test
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint:   git submodule add <url> test
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint:   git rm --cached test
hint: 
hint: See "git help submodule" for more information.
warning: LF will be replaced by CRLF in tsconfig.app.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tsconfig.json.
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in tsconfig.spec.json.
The file will have its original line endings in your working directory
    Successfully initialized git.
PS C:\temp> cd .\test\
PS C:\temp\test> ng s 

Initial Chunk Files | Names         |  Raw Size
polyfills.js        | polyfills     |  82.71 kB |
main.js             | main          |  23.36 kB |
styles.css          | styles        |  96 bytes |

                    | Initial Total | 106.17 kB

Application bundle generation complete. [10.011 seconds]
Watch mode enabled. Watching for file changes...
  ➜  Local:   http://localhost:4200/
```

**Comment by toddhd** [comment]
Thanks, Also, to be fair, I also have a laptop setup for my dev work, so I just copied the files over there (from the original project) and it works just fine. I was also able to create a new project just fine on the laptop. So I guess it is something local to the PC. Do you happen to have any thoughts on where to even start looking?

**Comment by alan-agius4** [comment]
To be perfectly honest, I have no clue. 

But when I see utterly strange behaviour, I would try by reinstalling node.js. I would recommend using NVM.

**Comment by toddhd** [comment]
Ok thank you. You can probably close this ticket in that case. If I discover anything pertinent, I'll still update the ticket. Just FYI, I have seen other tickets about this, so it's something weird. I just don't know what. 
https://github.com/angular/angular-cli/issues/26284

**Comment by toddhd** [comment]
https://colin.is/blog/2020/error-main-ts-is-missing-from-the-typescript-compilation/

FYI, still testing, but I think I found the solution (although I can't explain why it worked yesterday).  Adding "preserveSymlinks" in the angular.json file seems to fix the issue. 

```
"architect": {
  "build": {
    "builder": "@angular-devkit/build-angular:browser",
    "options": {
      "preserveSymlinks": true,
```

**Comment by ccocker** [comment]
Had exactly the same issue, tried re-installing node etc, nothing worked until i too added the  "preserveSymlinks": true, to my angular.json

**Comment by alan-agius4** [comment]
That is interesting... There is only

**Comment by Wockeez** [comment]
I'm facing the same problem, only I still get the same error even after setting "preserveSymlinks": true, but its behavior is strange

- At the first initialization of `ng serve`, everything is fine, there is no error
- Then I change some file and save it.
- After that moment I get a message in the console with a link to this particular file that I am modifying.
<img width="1146" alt="image" src="https://github.com/angular/angular-cli/assets/59292278/ebfe1443-6f88-45df-8499-4364b77d254b">

my tsconfig.app

```json
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "outDir": "./out-tsc/app",
        "types": [
            "node"
        ]
    },
    "files": [
        "src/main.ts",
        "src/main.server.ts",
        "server.ts",
    ],
    "include": [
        "src/**/*.d.ts",
        "src/**/*.ts",
    ],
    "exclude": [
        "src/**/*.spec.ts"
    ]
}

```

I don't always have this problem, i.e. the file can be saved and there can be an error.

**Comment by kamrujama** [comment]
> https://colin.is/blog/2020/error-main-ts-is-missing-from-the-typescript-compilation/
> 
> FYI, still testing, but I think I found the solution (although I can't explain why it worked yesterday). Adding "preserveSymlinks" in the angular.json file seems to fix the issue.
> 
> ```
> "architect": {
>   "build": {
>     "builder": "@angular-devkit/build-angular:browser",
>     "options": {
>       "preserveSymlinks": true,
> ```

Thanks, It worked for me as well.

**Comment by brettaio** [comment]
JANK!

**Comment by toddhd** [comment]
> That is interesting... Is the app being created in a symlink?

I was using ConEmu as my console if that makes any difference?

**Comment by merlinwarage** [comment]
Add "preserveSymlinks": true into your angular.json

`"architect": {
       "build": {
               "builder": "@angular-devkit/build-angular:application",
               "options": {
 		    "preserveSymlinks": true,
...`

**Comment by tusharuit25** [comment]
sudo ng new test
Password:
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
? Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No
CREATE test/README.md (1058 bytes)
CREATE test/.editorconfig (274 bytes)
CREATE test/.gitignore (548 bytes)
CREATE test/angular.json (2756 bytes)
CREATE test/package.json (1035 bytes)
CREATE test/tsconfig.json (877 bytes)
CREATE test/tsconfig.app.json (263 bytes)
CREATE test/tsconfig.spec.json (273 bytes)
CREATE test/.vscode/extensions.json (130 bytes)
CREATE test/.vscode/launch.json (470 bytes)
CREATE test/.vscode/tasks.json (938 bytes)
CREATE test/src/main.ts (250 bytes)
CREATE test/src/favicon.ico (15086 bytes)
CREATE test/src/index.html (290 bytes)
CREATE test/src/styles.scss (80 bytes)
CREATE test/src/app/app.component.scss (0 bytes)
CREATE test/src/app/app.component.html (20884 bytes)
CREATE test/src/app/app.component.spec.ts (910 bytes)
CREATE test/src/app/app.component.ts (363 bytes)
CREATE test/src/app/app.config.ts (227 bytes)
CREATE test/src/app/app.routes.ts (77 bytes)
CREATE test/src/assets/.gitkeep (0 bytes)
✔ Packages installed successfully.
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint:   git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint:   git branch -m <name>
    Successfully initialized git.
macbook@Macbooks-MBP-2 angular_class % cd test           
macbook@Macbooks-MBP-2 test % ng s 
? Would you like to share pseudonymous usage data about this project with the Angular Team
at Google under Google's Privacy Policy at https://policies.google.com/privacy. For more
details and how to change this setting, see https://angular.io/analytics. No
An unhandled exception occurred: EACCES: permission denied, open '/Users/macbook/angular_class/test/angular.json'
See "/private/var/folders/0m/wz54_kk524s6pdp4fznrgcw40000gn/T/ng-PzYue2/angular-errors.log" for further details.
macbook@Macbooks-MBP-2 test % ng s 
? Would you like to share pseudonymous usage data about this project with the Angular Team
at Google under Google's Privacy Policy at https://policies.google.com/privacy. For more
details and how to change this setting, see https://angular.io/analytics. Yes
An unhandled exception occurred: EACCES: permission denied, open '/Users/macbook/angular_class/test/angular.json'
See "/private/var/folders/0m/wz54_kk524s6pdp4fznrgcw40000gn/T/ng-7AIsdQ/angular-errors.log" for further details.
macbook@Macbooks-MBP-2 test % sudo ng s 
? Would you like to share pseudonymous usage data about this project with the Angular Team
at Google under Google's Privacy Policy at https://policies.google.com/privacy. For more
details and how to change this setting, see https://angular.io/analytics. No
Global setting: enabled
Local setting: disabled
Effective status: disabled
⠸ Building...✘ [ERROR] Could not resolve "zone.js"

    angular:polyfills:angular:polyfills:1:7:
      1 │ import 'zone.js';
        ╵        ~~~~~~~~~

  The Yarn Plug'n'Play manifest forbids importing "zone.js" here because it's not listed as a dependency of this package:

    ../../.pnp.cjs:89:33:
      89 │           "packageDependencies": [\
         ╵                                  ~~

  You can mark the path "zone.js" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


Application bundle generation failed. [2.734 seconds]
Watch mode enabled. Watching for file changes...

**Comment by tusharuit25** [comment]
deleting Plug'n'Play manifest generated on MAC root deleted and application started working

**Comment by toddhd** [comment]
Thank you! I ran the command above and then attempted to create a new project. No errors this time! :)

**Comment by alan-agius4** [comment]
Thanks for the confirmation, this will be available on NPM later next week in 17.0.4.

PR that fixes the issue: https://github.com/angular/angular-cli/pull/26453

**Comment by DariusMuscalu** [comment]
> I'm facing the same problem, only I still get the same error even after setting "preserveSymlinks": true, but its behavior is strange
> 
> * At the first initialization of `ng serve`, everything is fine, there is no error
> * Then I change some file and save it.
> * After that moment I get a message in the console with a link to this particular file that I am modifying.
> 
> <img alt="image" width="1146" src="https://private-user-images.githubusercontent.com/59292278/284013335-ebfe1443-6f88-45df-8499-4364b77d254b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzczMDgsIm5iZiI6MTcwMTc3NzAwOCwicGF0aCI6Ii81OTI5MjI3OC8yODQwMTMzMzUtZWJmZTE0NDMtNmY4OC00NWRmLTg0OTktNDM2NGI3N2QyNTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDExNTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOTdjZWI1N2MwOGJlOTlhZTAxNGYzMjRhM2EwNTcyMTA0MzZmYTc3NGUwZjE4YzY1NzRmZDllYzQyYzhmNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.12AKzIfjUtgjnPOjt2qjkvWsXrCmh0Ll3jexAMEXlHU">
> my tsconfig.app
> 
> ```json
> /* To learn more about this file see: https://angular.io/config/tsconfig. */
> {
>     "extends": "./tsconfig.json",
>     "compilerOptions": {
>         "outDir": "./out-tsc/app",
>         "types": [
>             "node"
>         ]
>     },
>     "files": [
>         "src/main.ts",
>         "src/main.server.ts",
>         "server.ts",
>     ],
>     "include": [
>         "src/**/*.d.ts",
>         "src/**/*.ts",
>     ],
>     "exclude": [
>         "src/**/*.spec.ts"
>     ]
> }
> ```
> 
> I don't always have this problem, i.e. the file can be saved and there can be an error.
> 
> I use @angular/ssr by default, I don't know if there is such a bug in spa mode

I get the same behaviour. Did you manage to fix it?

**Comment by DariusMuscalu** [comment]
I decided to downgrade to v16 for the moment in order to avoid this

**Comment by alan-agius4** [comment]
@DariusMuscalu, you can still use the webpack based builders with version 17, there is no need to downgrade to version 16.

That said, unfortunately without a minimal reproduction we are not able to further action this problem as it appears that your issue does not share the same root cause of the original reported issue.

**Comment by DariusMuscalu** [comment]
> @DariusMuscalu, you can still use the webpack based builders with version 17, there is no need to downgrade to version 16.
> 
> That said, unfortunately without a minimal reproduction we are not able to further action this problem as it appears that your issue does not share the same root cause of the original reported issue.

Had some problems with firebase also, when I did ng add @angular/fire it was telling me that version 0.0.0 was only found and that's not a valid one. Tried using --force and got the same behavior. So for the moment, I decided to stick to v16.

**Comment by JeanMeche** [comment]
There was an issue with the firebase release I believe. Until 4 days ago, the `latest` tag didn't refere to the v17 version.
Did you give it a try since ?

**Comment by DariusMuscalu** [comment]
Tried to install specific versions also and it still said it only found 0.0.0 version.

**Comment by toddhd** [comment]
@DariusMuscalu  FWIW, I was able to get AngularFire 17.0.0 working with Angular 17.0.5, although I did create a project with the --no-standalone option in order to add the app.module.ts file to ease setup. It was not easy however and since everything is brand new there isn't much info yet on how to set it up.  Not that I fault you for going back to v16, I was prepared to do the same.

**Comment by DariusMuscalu** [comment]
I also had -no-standalone option. This version is still newly released and didn't manage to find anything related on the web, so I've decided to go with v16 as I am still new to angular and so I can speed up my learning.

**Comment by shibli21** [comment]
removing 

`"aot": false,`

from my angular.json config fixed my issue,

**Comment by anhallbe** [comment]
Still experiencing this issue with `"aot": false`. Also it seems like `ng serve` no longer detects changes at all in .html files.

```

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.6
Node: 20.9.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6
@angular-devkit/schematics      17.0.6
@schematics/angular             17.0.6
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by janfess** [comment]
I also have the same issue, build doesn't work and the REST API example endpoints in server.ts do not work. There is nothing logged in the console when i hit the endpoints it seems something could be wrong with server.ts
