### ISSUE TITLE
Unable to set the default ViewEncapsulation with AOT compiled build

### ISSUE THREAD

**Issue by Cammisuli** [angular/angular-cli#2638]
When doing a JIT build using the CLI, I can set the compiler options within `platformBrowserDynamic().bootstrapModule`. Compiler options allow me to set the default ViewEncapsulation for the whole application.

### OS?
>Mac OSX (Sierra)

### Versions.
> angular-cli: 1.0.0-beta.17

### Repro steps.
1. Create a default app `ng new app` 
2. Inside `main.ts` add compiler options like so `
platformBrowserDynamic().bootstrapModule(AppModule, { defaultEncapsulation: ViewEncapsulation.None });`
3. `ng serve`
4. Encapsulation is none
5. `ng serve --aot`
6. Encapsulation is back to Emulated

### The log given by the failure.
> No Error logs

### Mention any other details that might be useful.
I'm not actually sure how to do this with just ngc by itself, so maybe that could point me in the right direction.

**Comment by Cammisuli** [comment]
created a feature request for this at the compiler level here: angular/angular#12251

**Comment by filipesilva** [comment]
Closing as it doesn't seem to be a CLI issue.
