### ISSUE TITLE
@angular-devkit/build-angular 16.2 package Webpack version locked at 5.88.2

### ISSUE THREAD

**Issue by trickeyone** [angular/angular-cli#26382]
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.1.1

### Description

After upgrading Webpack (5.89.0), builds are failing due to @angular-devkit/build-angular 16.2 having an explicit Webpack requirement of 5.88.2. This is causing builds to fail:

### Minimal Reproduction

Create an Angular 16 project, upgrade Webpack to 5.89.0.

### Exception or Error

```text
⠙ Generating browser application bundles (phase: setup).../path/to/project/node_modules/webpack/lib/NormalModule.js:231
                        throw new TypeError(
                              ^   

TypeError: The 'compilation' argument must be an instance of Compilation
    at NormalModule.getCompilationHooks (/path/to/project/node_modules/webpack/lib/NormalModule.js:231:10)
    at WebpackAssetsManifest.handleCompilation (/path/to/project/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:784:18)
    at Hook.eval [as call] (eval at create (/path/to/project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:222:1)
    at Hook.CALL_DELEGATE [as _call] (/path/to/project/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1126:26)
    at /path/to/project/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1170:29
    at eval (eval at create (/path/to/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.10
Node: 20.5.1 (Unsupported)
Package Manager: npm 9.8.0
OS: darwin arm64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core
... elements, forms, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
webpack                         5.89.0
zone.js                         0.13.3
    
Warning: The current version of Node (20.5.1) is not supported by Angular.
```

### Anything else relevant?

All other dependencies are using Webpack 5.89.0
```shell
├─┬ @angular-devkit/build-angular@16.2.10
│ ├─┬ @angular-devkit/build-webpack@0.1602.10
│ │ └── webpack@5.89.0 deduped
│ ├─┬ @ngtools/webpack@16.2.10
│ │ └── webpack@5.89.0 deduped
│ ├─┬ babel-loader@9.1.3
│ │ └── webpack@5.89.0 deduped
│ ├─┬ copy-webpack-plugin@11.0.0
│ │ └── webpack@5.89.0 deduped
│ ├─┬ css-loader@6.8.1
│ │ └── webpack@5.89.0 deduped
│ ├─┬ less-loader@11.1.0
│ │ └── webpack@5.89.0 deduped
│ ├─┬ postcss-loader@7.3.3
│ │ └── webpack@5.89.0 deduped
│ ├─┬ sass-loader@13.3.2
│ │ └── webpack@5.89.0 deduped
│ ├─┬ source-map-loader@4.0.1
│ │ └── webpack@5.89.0 deduped
│ ├─┬ webpack-dev-middleware@6.1.1
│ │ └── webpack@5.89.0 deduped
│ ├─┬ webpack-dev-server@4.15.1
│ │ ├─┬ webpack-dev-middleware@5.3.3
│ │ │ └── webpack@5.89.0 deduped
│ │ └── webpack@5.89.0 deduped
│ ├─┬ webpack-subresource-integrity@5.1.0
│ │ └── webpack@5.89.0 deduped
│ └── webpack@5.88.2                  <---- Only instance of a different webpack version
├─┬ @types/webpack@5.28.5
│ └── webpack@5.89.0 deduped
├─┬ mini-css-extract-plugin@2.7.6
│ └── webpack@5.89.0 deduped
├─┬ webpack-assets-manifest@5.1.0
│ └── webpack@5.89.0 deduped
└─┬ webpack@5.89.0
  └─┬ terser-webpack-plugin@5.3.9
    └── webpack@5.89.0 deduped
```

**Comment by alan-agius4** [comment]
Why do you need to install webpack yourself?

**Comment by trickeyone** [comment]
If I remember correctly, we had to declare a limitation on the webpack version due to come conflicts back when we upgraded to Angular 12. It's been a few years, but I believe that was the reason. Also, if I remember correctly, there was a period of time where npm would complain about not requiring dependencies sometimes.

**Comment by alan-agius4** [comment]
Webpack is installed through `@angular-devkit/build-angular` and unless you have a custom webpack setup, you do not need to install webpack in your workspace.

**Comment by trickeyone** [comment]
We do use a custom webpack setup, as well. We use @angular-builders/custom-webpack to generate entrypoints and manifest to feed to Symfony for our backend.

**Comment by dgp1130** [comment]
Custom Webpack is not supported by the Angular team. My only suggestion is to let Angular CLI pick the version of Webpack, given that's the only one we test against. Beyond that, you can ask at `@angular-builders/custom-webpack` if anyone there can advise further.

**Comment by trickeyone** [comment]
@dgp1130 But that doesn't make any sense. There are no other dependencies that have an explicit version like this. If the version was using semver like all other dependencies, this wouldn't be a issue. As far as I can tell, this was new with v16, v15 didn't have this issue.

**Comment by dgp1130** [comment]
`@angular-builders/custom-webpack` is a community supported package, not an official one. We've pinned the Webpack dependency as far back as I can remember, [at least past v15](https://github.com/angular/angular-cli/blob/b479063ab5ef625a5ee883bf5cc335572bdcb83e/packages/angular_devkit/build_angular/package.json#L64).

**Comment by trickeyone** [comment]
Right, and my requirement is set to `^5.75.0` which was matched by v15's version. It just seems strange to me that a library would use a explicit version instead of a semver. Will there be a new v16 release to support webpack's newer versions, even patch? Seems like a lot of overhead.

This all came out me upgrading to v16 ad updating all other dependencies. 5.89.0 was webpack's most recent version, so that's what got installed.

All my tests run fine, it's only the build that failed since this package limited the webpack version, which caused object-type mismatches.

**Comment by dgp1130** [comment]
The fact that v15 happened to match your previous requirement of `^5.75.0` is completely coincidental, not a supported use of Angular CLI. So the fact that v16 doesn't match your new requirement of `^5.88.2` is also coincidental. We only support the version which is explicitly pinned as a dependency.

Pretty much all Angular packages pin the explicit version of direct dependencies. This is something we've learned over time as it results in more testable and reliable behavior. In older versions of Angular it was quite common for bad patch releases in dependencies to cause breakages, leading to a scramble to fix such breakages. Pinning dependencies to explicit patch versions makes this less likely and keeps Angular more stable.

We have automation and tooling to update these versions regularly (and run them through CI), so every patch release typically includes updated dependencies. However, v16 is now [considered LTS](https://angular.dev/reference/releases#lts-fixes) so we don't do regular updates except for security or stability. The version of Webpack used in v16 is highly unlikely to change.

**Comment by dgp1130** [comment]
Again, I would suggest reaching out to the `@angular-builders/custom-webpack` maintainers for advice here. My understanding is that the general suggestion is to use the version of Webpack pinned by Angular CLI, but they may have other tricks to leverage here.

**Comment by trickeyone** [comment]
> The fact that v15 happened to match your previous requirement of `^5.75.0` is completely coincidental, not a supported use of Angular CLI. So the fact that v16 doesn't match your new requirement of `^5.88.2` is also coincidental. We only support the version which is explicitly pinned as a dependency.
> 
> Pretty much all Angular packages pin the explicit version of direct dependencies. This is something we've learned over time as it results in more testable and reliable behavior. In older versions of Angular it was quite common for bad patch releases in dependencies to cause breakages, leading to a scramble to fix such breakages. Pinning dependencies to explicit patch versions makes this less likely and keeps Angular more stable.
> 
> We have automation and tooling to update these versions regularly (and run them through CI), so every patch release typically includes updated dependencies. However, v16 is now [considered LTS](https://angular.dev/reference/releases#lts-fixes) so we don't do regular updates except for security or stability. The version of Webpack used in v16 is highly unlikely to change.

Ok, that makes sense and is understandable. Sorry for the back-n-forth. It was just strange when I did the upgrade and his the issue. Whe I tracked the cause back to the fixed version, that's what prompted me creating this issue.

And you're completely right, the fact that my version constraint matched the fixed version was totally coincidental.

I only brought up `@angular-builders/custom-webpack` because of the other contributor mentioning a custom webpack setup.

Webpack 5.88.2 doesn't cause any problems with the compilations or anything.
