### ISSUE TITLE
SCSS partials not properly updating the files that import them

### ISSUE THREAD

**Issue by brianmtreese** [angular/angular-cli#26390]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After updating to angular 17, when making changes to SCSS partials used in components, the changes do not take effect unless you go into the file that's importing them and trigger a save.

You can easily see this by going to the link for the reproduction, changing the color to something else, like "purple", and then saving. The color will not be changed until going into the component stylesheet (test-component.component.scss) where the variable is imported and used, and triggering a save there instead. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-y1ihag?file=src%2Ftest-component%2F_test-import.scss

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 17.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
```

**Comment by alan-agius4** [comment]
I am not able to replicate this outside of stackblitz. If you are replicating it locally, can you please provide the output of `ng version`.

**Comment by brianmtreese** [comment]
Ok, no problem. I also created a brand new app and replicated the issue outside of stackblitz [(https://github.com/brianmtreese/scss-partials-issue).](https://github.com/brianmtreese/scss-partials-issue) 

Angular CLI: 17.0.1
Node: 18.18.0
Package Manager: npm 10.2.1
OS: win32 x64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.1
@angular-devkit/build-angular   17.0.1
@angular-devkit/core            17.0.1
@angular-devkit/schematics      17.0.1
@angular/cli                    17.0.1
@schematics/angular             17.0.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

**Comment by clydin** [comment]
Is this still an issue for you with `@angular-devkit/build-angular@17.0.2`?

**Comment by brianmtreese** [comment]
Nope, it appears to be fixed now. Thanks!

**Comment by brianmtreese** [comment]
Nope, it appears to be fixed now. Thanks!

**Comment by clydin** [comment]
Good to hear and thank you for confirming.
