### ISSUE TITLE
esbuild seems to hang and thus blocks execution of statements later in the chain

### ISSUE THREAD

**Issue by WillooWisp** [angular/angular-cli#26396]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Ionic apps are no longer transferred to device with "ionic cap run android -l --external" when using angular 17 and esbuild.

Before angular 17 and esbuild...
```
[ng] √ Compiled successfully.

[INFO] Development server running!

       Local: http://localhost:8100
       External: http://172.24.64.1:8100, http://192.168.1.36:8100, http://192.168.32.66:8100, http://172.18.224.1:8100

       Use Ctrl+C to quit this process

> capacitor.cmd run android --no-sync --target R5CW143GQFX
[capacitor] √ Running Gradle build in 97.27s
[capacitor] √ Deploying app-debug.apk to R5CW143GQFX in 18.53s

[INFO] App deployed to device!

       Development server will continue running until manually stopped.

       Use Ctrl+C to quit this process
```

After angular 17 and esbuild...
```
[ng] Application bundle generation complete. [12.499 seconds]
[ng] Watch mode enabled. Watching for file changes...
[ng]   ➜  Local:   http://localhost:8100/
[ng]   ➜  Network: http://172.24.64.1:8100/
[ng]   ➜  Network: http://169.254.8.211:8100/
[ng]   ➜  Network: http://192.168.1.36:8100/
[ng]   ➜  Network: http://192.168.32.66:8100/
[ng]   ➜  Network: http://172.18.224.1:8100/

Call to "capacitor.cmd run android --no-sync --target R5CW143GQFX" is missing here!
```

### Minimal Reproduction

1. Upgrade a new ionic framework template app to angular 17+.
2. Change to utilize esbuild through @angular-devkit/build-angular:application in angular.json.
3. Run "ionic cap run android -l --external", which just starts the dev server, but never deploys the apk.

### Your Environment

```text
Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
```

### Anything else relevant?

Issue reported to ionic cli repo, but the issue was reported back to problems with angular cli, https://github.com/ionic-team/ionic-cli/issues/5061

**Comment by clydin** [comment]
If the development server where to exit immediately, there would not be anything to response to client requests.
The problem appears to be within the ionic CLI itself:
https://github.com/ionic-team/ionic-cli/blob/d09653d21444cd8589e6451bd404487f1e4e1962/packages/%40ionic/cli/src/lib/project/angular/serve.ts#L170-L193

The code appears to scrape the console output for specific text to indicate readiness.  However, the new build system uses different text. As a result, the ionic CLI assumes the server didn't start and waits indefinitely.

**Comment by jcesarmobile** [comment]
Yeah, it's a problem on Ionic CLI, sorry for the inconvenience.

**Comment by WillooWisp** [comment]
[like]  Joel Fjordén reacted to your message:
________________________________

**Comment by WillooWisp** [comment]
[like]  Joel Fjordén reacted to your message:
________________________________
