### ISSUE TITLE
Silent errors in test.ts

### ISSUE THREAD

**Issue by renehamburger** [angular/angular-cli#2640]
I'm using angular-cli@1.0.0-beta.16, node@6.5.0 and karma@1.2.0 (on OS X El Capitan).

When an exception is thrown while the spec files and their dependencies are loaded in [test.ts](https://github.com/angular/angular-cli/blob/master/packages/angular-cli/blueprints/ng2/files/__path__/test.ts#L32), the output `__karma__.error()` is barely helpful. In Chrome only 'ERROR' is printed to the node console and it's close to impossible to break on such a caught exception due to too many false positives. PhantomJS prints out a error stack but not the error message.

It would be great if you could log the error before re-throwing it.

In my case, @ngrx/effects@1.1.1 wasn't compatible with @angular@2.0.1, which was difficult to spot without sufficient error logging.

**Comment by anton-107** [comment]
@renehamburger how did you find the error? Also a bit stuck on this, hints on how to tackle these type of issues would be helpful

**Comment by renehamburger** [comment]
You could add your own error logging by changing [src/test.ts line 32](https://github.com/angular/angular-cli/blob/f6fa1a5218e9b43ab3ce29151a95efe915742562/packages/angular-cli/blueprints/ng2/files/__path__/test.ts#L32) from 
```ts
  .then(context => context.keys().map(context))
```
to 
```ts
  .then(context => {
    try {
      return context.keys().map(context);
    } catch (e) {
      console.error(e.message, e.stack);
      throw e;
    }
  })
```
The error stack would refer to the bundled file though, which would make it less helpful. But the error message may be all you need to pinpoint the issue.

**Comment by filipesilva** [comment]
@renehamburger would you be interested in submitting a PR with this change? I'd be happy to review it, but would require you to give a short example/repro step of how the reported error changed.
