### ISSUE TITLE
Angular CLI cannot exit `ng serve` or force quit.

### ISSUE THREAD

**Issue by estrellajm** [angular/angular-cli#26413]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

While running ```ng serve``` when I try to cancel the process with  ```ctrl + c```, nothing happens.
 
with Node 20
<img width="619" alt="Screenshot 2023-11-18 at 17 39 15" src="https://github.com/angular/angular-cli/assets/7454322/9e547e7f-35a7-4098-894d-44ef78f1725b">

with Node 18 
<img width="632" alt="Screenshot 2023-11-18 at 23 03 57" src="https://github.com/angular/angular-cli/assets/7454322/d20f649e-77cd-4c24-9d7d-a52046dcef7f">

### Minimal Reproduction

Steps to reproduce

1. I set NVM to use 20 (v20.9.0) as default with the following command ```nvm alias default 20```
2. When I open a new terminal instance and run ```ng serve``` the angular project builds

I also get this issue when I am running Node 18, and the client is reloading

### Expected Behavior
When I try to cancel the process with  ```ctrl + c```, it should stop the process. 

### Actual Behavior
When I try to cancel the process with  ```ctrl + c```, nothing happens.
 
with Node 20
<img width="619" alt="Screenshot 2023-11-18 at 17 39 15" src="https://github.com/angular/angular-cli/assets/7454322/9e547e7f-35a7-4098-894d-44ef78f1725b">

with Node 18 
<img width="632" alt="Screenshot 2023-11-18 at 23 03 57" src="https://github.com/angular/angular-cli/assets/7454322/d20f649e-77cd-4c24-9d7d-a52046dcef7f">

### Exception or Error
sometimes I get this error even while running node v18

^C⠋ Changes detected. Rebuilding...Error: The service is no longer running
    at /Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1111:28
    at sendRequest (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:699:14)
    at triggerAnotherBuild (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1109:17)
    at /Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1119:15
    at ZoneAwarePromise (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/zone.js/fesm2015/zone-node.js:1342:21)
    at Object.rebuild (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1098:35)
    at #performBundle (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:141:53)
    at BundlerContext.bundle (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:120:49)
    at /Users/jestrella/Desktop/cs171-vis-jam/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:61:28
    at Array.map (<anonymous>)
Error: The service is no longer running
    at /Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1111:28
    at sendRequest (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:699:14)
    at triggerAnotherBuild (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1109:17)
    at /Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1119:15
    at ZoneAwarePromise (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/zone.js/fesm2015/zone-node.js:1342:21)
    at Object.rebuild (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/esbuild/lib/main.js:1098:35)
    at #performBundle (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:141:53)
    at BundlerContext.bundle (/Users/jestrella/Desktop/cs171-vis-jam/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:120:49)
    at /Users/jestrella/Desktop/cs171-vis-jam/node_modules/@angular-devkit/build-angular/src/tools/esbuild/bundler-context.js:61:28
    at Array.map (<anonymous>)
An unhandled exception occurred: The service is no longer running
See "/private/var/folders/hq/tyztmswd0ns4d89gyzvfcj2r0000gn/T/ng-DM7i97/angular-errors.log" for further details.
^C

### Your Environment

```text
Angular CLI: 17.0.1
Node: 20.9.0
Package Manager: yarn 1.22.21
OS: darwin arm64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.1
@angular-devkit/build-angular   17.0.1
@angular-devkit/core            17.0.1
@angular-devkit/schematics      17.0.1
@angular/cli                    17.0.1
@angular/fire                   17.0.0-next.0
@angular/ssr                    17.0.1
@schematics/angular             17.0.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

If you set NVM to 18 as default ```nvm alias default 18```, you can run ```ng serve``` and cancel the process with ```ctrl + c```.

If you then switch to v20 using the command ```nvm use 20```, it works as expected (described above). 

This bug only occurs when v20 is default in nvm ```nvm alias default 20```

**Comment by alan-agius4** [comment]
Hi @estrellajm, I did try to replicate this unfortunately I was not able.

**Comment by estrellajm** [comment]
Hi @alan-agius4, thanks for checking on this. Were you using nvm? I confirmed that I am on nvm 0.39.5 which is the latest release according to https://github.com/nvm-sh/nvm/releases.

For me this issue was only reproducible either when:
- node v20 was set to default, and I opened a new terminal
- node v18 was default, and the project detected a change and reloaded the client

What do you recommend that I do to pinpoint where this issue is coming from?

**Comment by estrellajm** [comment]
Hi @alan-agius4, I thought I restarted my computer before opening this ticket. 

Looks like restarting my computer remedied this situation. Closing this ticket.

**Comment by alan-agius4** [comment]
Glad to hear to found the solution
