### ISSUE TITLE
Injection errors when serving using `vite`

### ISSUE THREAD

**Issue by JelleBruisten** [angular/angular-cli#26416]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2

### Description

Injection errors when using `vite` and `esbuild` that are not present when using webpack as the dev server or when serving a static webserver from `dist` folder.

### Minimal Reproduction

I am currently facing a problem when serving the application using the `dev-server` with a buildTarget of  `browser-esbuild`/`application`
When opening the development environment I am getting the following error:
`Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.io/errors/NG0203`

When doing a build with `browser-esbuild` or `application` builder, and then serving the application using 
`http-server ./dist/foo/browser --port 4200 --proxy http://localhost:4200?`
There does not seem to be any problems, after some digging a bit more I changed:
`if (builderName === '@angular-devkit/build-angular:application' ||
            builderName === '@angular-devkit/build-angular:browser-esbuild' ||
            normalizedOptions.forceEsbuild) {
`

of the `build-angular\src\builders\dev-server\builder.js` to:
`if  (normalizedOptions.forceEsbuild)`
Therefore disabling `vite` when using `browser-esbuild`, when using the `webpack-server`  it also seems to work like normal.

Would this be a bug or what could I do to resolve this issue

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.1
Node: 18.13.0
Package Manager: yarn 3.2.4
OS: win32 x64

Angular: 17.0.3
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1700.1
@angular-devkit/build-angular     17.0.1
@angular-devkit/core              17.0.1
@angular-devkit/schematics        17.0.1
@angular-devkit/schematics-cli    17.0.1
@angular/cdk                      17.0.1
@angular/cli                      17.0.1
@angular/google-maps              17.0.1
@angular/material                 17.0.1
@angular/material-luxon-adapter   17.0.1
@schematics/angular               17.0.1
ng-packagr                        17.0.1
rxjs                              7.8.1
typescript                        5.2.2
webpack                           5.88.2
zone.js                           0.14.2
```

**Comment by clydin** [comment]
This appears to be a bug but we will need to look at a reproduction to find and fix the problem. Can you setup a minimal reproduction please? 

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal reproduction is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by JoostK** [comment]
Likely a duplicate of https://github.com/angular/angular/issues/52962. This error usually occurs when `@angular/core` is loaded multiple times, typically because of a particular `node_modules` layout. It's unclear though how the new builder would affect things here.

**Comment by clydin** [comment]
The output of `yarn list --pattern @angular/core` may also be useful in that case as well.

**Comment by JelleBruisten** [comment]
I have stripped down the application to 1 component with `hello world` no routing/other code in that one component or other dependencies.

```ts
// app.module.ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
  ],
  providers: [   
  ],
  bootstrap: [AppComponent],
})
export class AppModule { 
}
```

I am currently looking if it's one of the dependencies, this might take a while.

**Comment by JelleBruisten** [comment]
@JoostK The problem wasn't the builder itself, but only showed when using vite as the dev server. However I found the culprit:
```ts
// tsconfig.base.json
    "paths": {
      "@angular/*": ["./node_modules/@angular/*"],
      }
```
This has been in the workspace for over 3 years no idea why, after it still appearing when I had minimal dependencies I started comparing typescript and others configuration settings. Thanks for pointing me a bit in the direction why it was failing 😀

@clydin Also thank you for that command, however I am using yarn 3 which does not have that feature. but I did find a yarn why <package> command which seems to be similar.

**Comment by JoostK** [comment]
That's interesting, as such path mapping is typically done precisely to avoid this problem.

**Comment by JelleBruisten** [comment]
@JoostK I made a small new workspace with 1 main application and 1 library, with the same config:

```ts
// in tsconfig.base.json
"@angular/*": ["./node_modules/@angular/*"],
``` 
![image](https://github.com/angular/angular-cli/assets/4212850/3a403a0d-1fdb-40ae-b9cc-b34d7374a804)


When having this exact config it breaks there too, removing it will fix it.
![image](https://github.com/angular/angular-cli/assets/4212850/ff7770c7-57a8-4231-a37c-ba1d25fdc209)
