### ISSUE TITLE
Option to produce metafile with esbuild

### ISSUE THREAD

**Issue by SebastianStehle** [angular/angular-cli#26410]
### Command

build

### Description

Hi,

I have a long list of very small chunks and I would like to know where these are coming from.

I have seen that there are several build analyzers for esbuild, but they work based on the metafile. I would like to have an option to produce this file.

### Describe the solution you'd like

Build option to produce the esbuild metafile.

**Comment by clydin** [comment]
The `--stats-json` object will generate the metafile. When used a file named `stats.json` will be generated in the root of the configured output path.
