### ISSUE TITLE
Change the optimization minify option to allow removing whitespaces but keep comments

### ISSUE THREAD

**Issue by CarlosTorrecillas** [angular/angular-cli#26427]
### Description

At the moment, as far as I know and as per the docs, the `minify `option accepts only a boolean and does everything to reduce the size of the final CSS (removing excess of whitespaces and comments). This can become a problem if you run a postbuild task that removes the unused CSS using PurgeCSS for example. Since purge looks for comments such as `/* purgecss start ignore */` it won't find them and therefore it will remove the css block

### Proposed solution

Extend the minify option to accept either a boolean (right now) or two properties: `whitespaces `and `comments `so we are able to tweak accordingly

### Alternatives considered

Run another postbuild task that will remove the whitespaces "manually" after the CSS optimization

**Comment by alan-agius4** [comment]
In this case, you need to use CSS special comments,  `/*! comment here */` which CSS minifiers will not remove.

**Comment by CarlosTorrecillas** [comment]
Thank you very much. I think it would be good to get it in the minify reference section just to be aware that you can have comments using the syntax you described

**Comment by CarlosTorrecillas** [comment]
@alan-agius4 The trouble here is that PurgeCSS is not able to pick the comment like that (`/*! comment here */`) as it seems it needs exaclty `/* purgecss start ignore */`.

I guess under this circumstances perhaps you can reconsider the feature request? I think that would be useful for people who suddenly not see the expected behaviour, users that rely on comments being the exact same way as described on third party libraries docs for example

**Comment by alan-agius4** [comment]
Based on their docs (linked above) , purgeCSS does support the mentioned comment format.

**Comment by CarlosTorrecillas** [comment]
Yeah, I just saw. I'm getting in touch because it seems there is a bug

**Comment by alan-agius4** [comment]
That is expected with esbuild and is per design. Esbuild will remove any comments in JS and CSS unless they are "special". 

See https://github.com/evanw/esbuild/issues/221 for more context.

**Comment by CarlosTorrecillas** [comment]
OK - Then the comments disappearing on a brand new Angular 17 is expected. For new applications or for applications that we want to migrate, is there any example for configuring comments so that we can still use tools that rely on comments such as PurgeCSS?

**Comment by alan-agius4** [comment]
Esbuild by design does not allow standard comments to be retained, this includes all application both new and existing will have standard comments dropped. This also includes the Webpack build pipeline which under the hood esbuild is used as an JS and CSS minifier and optimizer.

Typically tools that rely on comments support In this case the special `/*! comment */`, which esbuild and other minifiers will not delete.

**Comment by alan-agius4** [comment]
Esbuild like other minifiers will not delete special comments.

**Comment by CarlosTorrecillas** [comment]
I will create the repro steps since I can reproduce the behavior that removes them

**Comment by CarlosTorrecillas** [comment]
Created this https://github.com/angular/angular/issues/53059 so that you can reproduce it
