### ISSUE TITLE
Allow programmatic/conditional configurations

### ISSUE THREAD

**Issue by rkrisztian** [angular/angular-cli#26429]
### Command

config, test

### Description

Angular should support conditional configurations like setting a value based on the presence of an environment variable. I see this as an issue in 2 places:

* `angular.json` does not support conditional setting of values via environment variables. I can't even add comments in a valid JSON.
* Because `ng test --codeCoverage` is a command-line option, I can't use it in `karma.conf.js`. This might be true to whatever replaced Karma recently (Jest by default?). Since I also use the Cypress component test runner, where I also enabled code coverage, an environment variable reused for both tools is more convenient.

Yes I understand that this makes migration scripts much harder to implement if not impossible. But look at how other frameworks work, e.g. Vite. You don't configure things in JSON, and it doesn't hide the option to enable code coverage behind a command-line flag or an `angular.json` property that I cannot control programmatically.

### Describe the solution you'd like

* `angular.json` should be JavaScript or TypeScript, not JSON.
* Let me use the option `ng test --codeCoverage` in `karma.conf.js` or whatever replaced Karma recently, so that I can enable code coverage conditionally.

**Comment by alan-agius4** [comment]
Closing as per https://github.com/angular/angular-cli/issues/12943#issuecomment-634746071 which is still valid.
