### ISSUE TITLE
(feat) JSON file to NEW/GEN project/files

### ISSUE THREAD

**Issue by esinek** [angular/angular-cli#2643]
Would be great if we could configure a JSON file to do the following:

- Create new project (ng new)
- Generate all types (ng generate ...)
- Option for JSON file per module (ng generate module and all its contained generate commands in one JSON file that is referenced from the "project" JSON file)

Additionally, would be nice if we could Reverse Generate the JSON file from project/files (so we can create the JSON file from a previously generate project/files - to use for incremental gen updates)

@kenhansen01 has a PR (https://github.com/angular/angular-cli/pull/1039) for some of this and hoping it makes it to master.

**Comment by filipesilva** [comment]
Closing together with #1039, reasoning mentioned https://github.com/angular/angular-cli/pull/1039#issuecomment-253889085
