### ISSUE TITLE
Segmentation fault with exit code 139 in supported node Docker image on ng build

### ISSUE THREAD

**Issue by paulThorsen** [angular/angular-cli#26448]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16

### Description

Building a Docker image (using a base image of a supported node version) in Angular v17 always results in a segmentation fault exiting with code 139 on the `npm run build` step. I've read online the 139 signal points to a memory issue of some sort. I haven't been able to narrow down what is causing it.

The `npm run build` script simply translates to `ng build`. This works fine in other versions of Angular, but not v17. I'm able to successfully build the image if I omit the build step. 

I'm using `node:18.13.0` as my base image, but experienced the same issue on `node:20.9.0`. `ng build` runs fine locally, but always fails as described when building Docker images, either locally or in a CI/CD pipeline/action.

### Minimal Reproduction

`ng new test-docker-build`
\> SCSS
\> n
\> Add a very simple Dockerfile:
```
FROM node:18.13.0
WORKDIR /app
COPY . /app
RUN npm i
RUN npm run build
```
`docker build -t test-docker-build .` 

### Exception or Error

```text
=> ERROR [5/5] RUN npm run build                                        1.1s
------                                                                        
 > [5/5] RUN npm run build:                                                   
0.968 
0.968 > test@0.0.0 build
0.968 > ng build
0.968 
1.052 Segmentation fault
------
Dockerfile:5
--------------------
   3 |     COPY . /app
   4 |     RUN npm i
   5 | >>> RUN npm run build
   6 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 139
```

### Your Environment

```text
Angular CLI: 17.0.0
Node: 18.13.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
```

**Comment by JoostK** [comment]
This does not reproduce for me, on macOS 14.1 (M1 Max), with Docker 24.0.2, build cb74dfc

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
