### ISSUE TITLE
Cannot generate a component after migrating project to standalone

### ISSUE THREAD

**Issue by brianreinhold** [angular/angular-cli#26454]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

After following the 'migration to standalone' it is no longer possible to create a component using Angular CLI. The following attempts

ng g c fhir-dashboard
ng g c fhir-dashboard --standalone
ng g c fhir-dashboard --skip-import

all give the same error which is:

Could not find a non Routing NgModule.
Modules with suffix '-routing.module.ts' are strictly reserved for routing.
Use the '--skip-import' option to skip importing in NgModule.

Of course there is no app.module.ts file in this standalone project.

### Please provide the exception or error you saw

```true
PS E:\projects\Angular\HubView\src\app> ng g c fhir-dashboard --skip-import

> hub-view@0.8 ng
> ng g c fhir-dashboard

Could not find a non Routing NgModule.
Modules with suffix '-routing.module.ts' are strictly reserved for routing.
Use the '--skip-import' option to skip importing in NgModule.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
PS E:\projects\Angular\HubView> npm run ng version

> hub-view@0.8 ng
> ng version


     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.8
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

---------------------------------------------------------
@angular-devkit/architect       0.1602.8
@angular-devkit/build-angular   16.2.8
@angular-devkit/core            16.2.8
@angular-devkit/schematics      16.2.8
@angular/cdk                    16.2.10
@angular/cli                    16.2.8
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

### Anything else?

The project builds and works after migration. 

I guess even though the Angular CLI is broken (or the migration is broken or both are broken), I should be able to add components manually.

**Comment by alan-agius4** [comment]
Using the `ng g c --standalone` flag should work, alternatively you can configure the CLI to generate standalone components using the below command
```
ng config projects.<project-name>.schematics.@schematics/angular:component.standalone true
```

If the problem persists, please provide a a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by brianreinhold** [comment]
My concern is that I have a large project which originally was NOT standalone but a short time ago I followed the instructions here https://angular.io/guide/standalone-migration to make it standalone since I noted that Angular 17 (which I want to migrate the project to) is going that way.

The ng g c command worked fine pre-migration. The migration steps required that I do extra work during the procedure to get the system to build after each step. The migration procedure DID say that extra steps might be needed. As a final step I deleted the app.modules file as it appeared it was not needed. There was nothing in the guide that talked about doing such. But the project built and ran fine without that file. 

I did not try to generate any new components at the time and did not think about that. Creating services through the CLI still works. But now I need a new component and no matter what I try I get the same error every time (using the CLI).  I have created the component manually in order to move forward.

Given the above I am at a loss to provide a means to reproduce the error without just using this project as is. It MUST have something to do with the migration as the CLI worked fine before

**Comment by alan-agius4** [comment]
Have you tried to use the above mentioned commands?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by brianreinhold** [comment]
I found I could do it if I added this to angular.json:

```
      "schematics": {
        "@schematics/angular:component": {
          "standalone": true
        }
      },
```
In the migration guide I don't recall this being mentioned. Since I came from a non-standalone project, this was not present. It's funny that the --standalone flag does not override the lack of this entry.
