### ISSUE TITLE
`ng update @angular/cli` breaks with gitlab.com npm packages in version 17.0.3

### ISSUE THREAD

**Issue by meierw** [angular/angular-cli#26456]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.2

### Description

When running `ng update @angular/cli` the latest version of the CLI (17.0.3) is downloaded and used. And then I get an error when trying to connect to our npm package hosted on gitlab.com. I'm using `pnpm` as the underlying package manager.

Previously (on v17.0.2) everything was fine. Just yesterday I was using `ng update` to update my Angular dependencies without issue. The `.npmrc` in the project root was respected and the package data/metadata was downloaded correctly.

This is a public gitlab.com project and the npm repo is also publicly available without any auth needed.

You can even try to open the failing URL specified in the error and you will see that it can be accessed.

### Minimal Reproduction

Have an Angular project which uses `pnpm`, and `@angular/cli@17.0.2`.

Have `.npmrc` with the following content in project root.
```
@solveri:registry=https://gitlab.com/api/v4/packages/npm/
auto-install-peers = true
```

Have a dev dependency for `@solveri/pulumi`. Can add it via `pnpm install -D @solveri/pulumi`.

Try running `ng update @angular/cli` and get error.

### Exception or Error

```text
[error] FetchError: request to https://gitlab.com/api/v4/packages/npm/@solveri%2fpulumi failed, reason: 
    at ClientRequest.<anonymous> (/home/waltm/git/signify/node_modules/.pnpm/minipass-fetch@3.0.4/node_modules/minipass-fetch/lib/index.js:130:14)
    at ClientRequest.emit (node:events:514:28)
    at _destroy (node:_http_client:875:13)
    at onSocketNT (node:_http_client:895:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Your Environment

```text
Angular CLI: 17.0.3
Node: 20.9.0
Package Manager: pnpm 8.10.2
OS: linux x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

This renders `ng update` pretty much useless, and I have to resort to updating the packages with `pnpm install` and `pnpm update`, which is an obvious step backwards in usability.

**Comment by alan-agius4** [comment]
Hi @meierw,

I am unable to replicate this issue. 
```
ng update @angular/cli --allow-dirty --force
Repository is not clean. Update changes will be mixed with pre-existing changes.
The installed Angular CLI version is outdated.
Installing a temporary Angular CLI versioned 17.0.3 to perform the update.
✔ Packages successfully installed.
Repository is not clean. Update changes will be mixed with pre-existing changes.
Using package manager: pnpm
Collecting installed dependencies...
Found 40 dependencies.
Fetching dependency metadata from registry...
    Updating package.json with dependency @angular-devkit/build-angular @ "17.0.3" (was "17.0.2")...
    Updating package.json with dependency @angular/cli @ "17.0.3" (was "17.0.2")...
UPDATE package.json (1820 bytes)
✔ Packages successfully installed.
```

The error itself indicates some sort of network error

Worth also mentioning that we did not do any changes related to the `ng update`.

**Comment by meierw** [comment]
Hi @alan-agius4 the problem has also magically fixed itself for me as well, when I ran it just now.

I suspect that gitlab.com was the culprit itself, and they had some networking issues.

Thanks for looking into it, and sorry for wasting your time.

**Comment by alan-agius4** [comment]
Glad to hear that it works for you too.
