### ISSUE TITLE
bug(esbuild): tsconfig path mapping doesn't applied to library 

### ISSUE THREAD

**Issue by leo6104** [angular/angular-cli#26467]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

tsconfig.paths  configuration doesn't applied to library's import path. 

### Minimal Reproduction

Here is the minimal repro case. 
I publish two libraries called `@com/print-js`, `@com/styled-components`.

In `@com/print-js` library, it use InjectionToken from `@com/styled-components` library. 
```
import { SOME_TOKEN } from '@com/styled-components';

@Injectable() 
export class PrintService {
    appConfig = inject(SOME_TOKEN); 
}
```

In my main project, 
it includes all files of `@com/styled-components` library codes and link the code directly by using path mapping config.
```
"paths": {
   "@com/styled-components": [ 
      "../../styled-components/src/index.ts", 
   ],
},
```

And then, i use `PrintService` from `@com/print-js` library in standalone component. 
```
import { PrintModule }  from '@com/print-js'; 

@Component({
   selector: 'comp',
   standalone: true,
   imports: [
      PrintModule, // which include PrintService 
   ],
   ...
}) 
export class Component {
    print = inject(PrintService); 
}
```

When i serve the main project with ESBuild, it raise error 
```
✘ [ERROR] Could not resolve "@com/styled-components"

    node_modules/@mapiacompany/print-js/fesm2022/mapiacompany-print-js.mjs:5:36:
      5 │ import { SOME_TOKEN } from '@com/styled-components';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@com/styled-components" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

With webpack serve, it works well. (correctly path mapping to `../../styled-components/src/index.ts` code)

### Your Environment

```text
Angular CLI: 17.0.2
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.2
@angular-devkit/build-angular   17.0.2
@angular-devkit/core            17.0.2
@angular-devkit/schematics      17.0.2
@angular/cdk                    17.0.1
@angular/cli                    17.0.2
@angular/material               17.0.1
@angular/ssr                    17.0.2
@angular/youtube-player         16.2.0
@schematics/angular             17.0.2
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
Please provide a minimal reproduction repro, as just the snippets do not provide the full picture, i.e. where does that `tsconfig.json` file exist on disk, what is the `baseUri` of the project, what is the workspace root, etc.

**Comment by MarcosPaulo775** [comment]
https://github.com/angular/angular-cli/issues/26476

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
