### ISSUE TITLE
node_modules/@angular/cli/src/utilities/config.d.ts:10:10 - error TS2305: Module '"./json-file"' has no exported member 'JSONFile'.

### ISSUE THREAD

**Issue by BenMakesGames** [angular/angular-cli#26477]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I receive this error when running `ng serve`. looking at `node_modules/@angular/cli/src/utilities/config.d.ts`, it contains the following line:

```
import { JSONFile } from './json-file';
```

adding the following to `node_modules/@angular/cli/src/utilities/json-file.d.ts` solves the issue:

```
export type JSONFile = {path:string, content: string};
```

modifying the files in `node_modules` is obviously madness, but it's a workaround that lets me keep going.

I originally encountered this issue when upgrading to Angular 15, I believe? some months or years ago. I had forgotten all about it until upgrading to 17 today, which I'm sure reset the files, so that "makes sense", in so far as this error makes sense :P

at first I didn't remember what caused the error - I had only a dim memory of encountering it before - so I did the usual things of deleting my `node_modules` dir, and `package-lock.json`... tried updating a few other npm packages...

I can't imagine this is affecting anyone else, but I also can't imagine how it's affecting me. I'm happy to provide any other info.

* I'm on Windows 10 Pro; fully windows update'd, as of today
* npm, node, and other versions are below
* my project was originally created on Angular 8 or 9? I forget. could my project be carrying any funny baggage around as a result?

here's my `package.json` file:
```json
{
  "name": "poppy-seed-pets-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.2",
    "@angular/common": "^17.0.2",
    "@angular/compiler": "^17.0.2",
    "@angular/core": "^17.0.2",
    "@angular/forms": "^17.0.2",
    "@angular/material": "^17.0.1",
    "@angular/platform-browser": "^17.0.2",
    "@angular/platform-browser-dynamic": "^17.0.2",
    "@angular/router": "^17.0.2",
    "@angular/service-worker": "^17.0.2",
    "d3": "^7.8.0",
    "d3-shape": "^3.2.0",
    "ngx-color-picker": "^15.0.0",
    "ngx-markdown": "^17.0.0",
    "qs": "^6.11.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "^0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.0",
    "@angular/cli": "^17.0.2",
    "@angular/compiler-cli": "^17.0.2",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "typescript": "~5.2.2"
  }
}
```

screenshot of the output, in case that's of any help:
![image](https://github.com/angular/angular-cli/assets/1587505/50903b49-0284-4975-89da-619a80e83d0b)
^ success after making the manual modification to `json-file.d.ts`

(running on https is maybe less common? but it's a very recent change for my local dev, anyway - maybe a month ago, tops.)

### Minimal Reproduction

running `ng serve` after a clean `npm install`

### Exception or Error

```text
Error: node_modules/@angular/cli/src/utilities/config.d.ts:10:10 - error TS2305: Module '"./json-file"' has no exported member 'JSONFile'.

10 import { JSONFile } from './json-file';
```

### Your Environment

```text
Angular CLI: 17.0.3
Node: 20.9.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@angular/material               17.0.1
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
This is indeed bug in the declaration files of `@angular/cli` due to the usage of `@internal` for `JSONFile`, but this file _should never be present_ in an application build. I suspect you have an import into the CLI's source files somewhere from your application code, which should be removed.

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by BenMakesGames** [comment]
with that clue, I was able to track it down. I had somehow accidentally pulled in `Options` from `@angular/cli` forever ago. probably IDE "helpfully" auto-importing something for me.

anyway, got it out; thanks!
