### ISSUE TITLE
Path mapping error

### ISSUE THREAD

**Issue by MarcosPaulo775** [angular/angular-cli#26476]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

When updating the builder to `@angular-devkit/build-angular:application` the Typescript Path Mappings stopped working

### Minimal Reproduction

- Update `@angular-devkit/build-angular:browser` to `@angular-devkit/build-angular:application`.
- Use typescript path mapping (`npm i tsconfig-paths -D`)

Example:

tsconfig.json
```json
"paths": {
  "@env/*": ["src/environments/*"],
  "@core/*": ["src/app/core/*"],
  "@shared/*": ["src/app/shared/*"]
}
```

src/app/app.component.ts
```typescript
import { Test } from '@shared/services/test.service';
```

### Exception or Error

```text
`Failed to resolve dependency: @shared/services/test.service, present in 'optimizeDeps.include'`
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.2
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.2
@angular-devkit/build-angular   17.0.2
@angular-devkit/core            17.0.2
@angular-devkit/schematics      17.0.2
@angular/cdk                    17.0.1
@angular/cli                    17.0.2
@angular/material               17.0.1
@schematics/angular             17.0.2
rxjs                            7.5.7
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
Please provide a reproduction. Also note that `tsconfig-paths` should be considered irrelevant for Angular's build pipeline, since that affects Node's module resolver but not that of many tools as used by the CLI.

**Comment by alan-agius4** [comment]
A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by MarcosPaulo775** [comment]
I'm trying to simulate it in a new project but with few imports I still haven't managed to do it.

In my project where the error is occurring depending on the file I import using path mapping works. Works with all interfaces that are isolated in a file. I'm going to start from this point to try to simulate.

Does the error have to do with this Vite config?

https://vitejs.dev/config/dep-optimization-options#optimizedeps-include

**Comment by MarcosPaulo775** [comment]
How configure this with angular ?

https://www.wolff.fun/path-mapping-typescript-vite/

**Comment by alan-agius4** [comment]
@MarcosPaulo775, the CLI does not expose that. It’s handled internally. Please provide a minimal reproduction of the problem you are experiencing.

**Comment by KarlXOL** [comment]
Have same issue

**Comment by KarlXOL** [comment]
> Starting from the idea that isolated files work, I tried with my environments files, which are very simple... but I return the following error
> 
> ![image](https://private-user-images.githubusercontent.com/32870576/285489317-b2f24eae-7dde-4c0f-9979-f404e78ee504.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNDQ5NzcsIm5iZiI6MTcwMTM0NDY3NywicGF0aCI6Ii8zMjg3MDU3Ni8yODU0ODkzMTctYjJmMjRlYWUtN2RkZS00YzBmLTk5NzktZjQwNGU3OGVlNTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDExNDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYmI3MmYxZmY3ODY0NGQzNjYyYTQwYjliODUzZWU2M2YxZmY0Y2MzMzdlOGY5MGFhMjY3NzQzYjY4ZjhmMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IJHBxjjeTVQqFkLahq9rljh4J50vPYPHbxBbdzcPFbo)

Have same issue

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
