### ISSUE TITLE
BUILD_IDENTIFIER as a built-in injectable token

### ISSUE THREAD

**Issue by TheTomasJ** [angular/angular-cli#26485]
### Command

build

### Description

Some build-version value which can be accessed in runtime out of the box would be nice.

### Describe the solution you'd like

Injection token provided on the backround is enough. It can be build hash or build timestamp.

### Describe alternatives you've considered

Extending build with custom script and replace-in-file is probably most common way.

**Comment by alan-agius4** [comment]
Hi @TheTomasJ, thanks for this feature request. However, this is not in scope of the CLI. There are a couple of ways you can currently achieve it. 

See: https://medium.com/@tolvaly.zs/how-to-version-number-angular-6-applications-4436c03a3bd3 and https://stackoverflow.com/questions/41733660/how-to-insert-a-build-number-or-timestamp-at-build-time-in-angularcli
