### ISSUE TITLE
SSR: Add a way to configure `externalDependencies` for the server bundle only with `@angular-devkit/build-angular:application` builder 

### ISSUE THREAD

**Issue by frankswarm** [angular/angular-cli#26487]
### Command

build

### Description

I would like to exclude some dependencies from being bundled but just for the server bundle. I can't find the proper way to do that using the @angular-devkit/build-angular:application builder. 

Adding `externalDependencies` to the `options` prevent the packages from being bundled in both the browser and the server bundles.

### Describe the solution you'd like

Maybe update the `ssr` option with an `externalDependencies` property that prevents the bundling just for the server.

### Describe alternatives you've considered

Stop using the `ssr` option  from `@angular-devkit/build-angular:application` and using a combination of the same with the `@angular-devkit/build-angular:server`builder... but, I'm still trying to figure that out too 😅 .

**Comment by alan-agius4** [comment]
What is the use-case case of having a dependency being external for the server but not for the browser bundle?

**Comment by frankswarm** [comment]
Hi, thanks for the quick response! I'm trying to integrate [opentelemetry](https://github.com/open-telemetry/opentelemetry-js) in the server to get traces and metrics. The tooling for NodeJS assumes that the packages are being loaded from node_modules (which is not a crazy assumption 😅) instead of coming from a bundle to be able to provide automatic instrumentations.

I saw this [issue](https://github.com/angular/angular-cli/issues/16348) that was also giving other reasons, but i think the resolution given there no longer applies.

**Comment by clydin** [comment]
You should be able to mark the relevant packages external such as `express`.  This shouldn't cause any issues with the browser build since those packages shouldn't be used in a browser anyway.

**Comment by frankswarm** [comment]
Hi @clydin thanks for your input. I'm using your suggestion as a workaround, but I do think there are scenarios in which it is necessary to be able to mark externals for each bundle: 

### Scenario 1: Universal/Isomorphic packages

For example, let's think of an isomorphic/universal package like [pino](https://www.npmjs.com/package/pino), it would be handy to exclude it from the server bundle and load it from node_modules and, at the same time, have it bundled for the browser.

### Scenario 2: Browser only packages

Packages that are exclusively meant for the browser and are just bloating the server bundle like [@opentelemetry/autoinstrumentations-web](https://www.npmjs.com/package/@opentelemetry/auto-instrumentations-web)

**Comment by alan-agius4** [comment]
Hey @frankswarm, appreciate the insights and scenarios. While I acknowledge their potential usefulness in certain situations, I feel these cases are somewhat uncommon.

Take Pino, for instance. Its reliance on the module being installed in node_modules seems more like a bug or limitation on their part. Bundling dependencies with node applications is a common practice nowadays.

Let's revisit this in the future,  if it's something the community expresses interest in.
