### ISSUE TITLE
Feature request: build should not clean WEB-INF

### ISSUE THREAD

**Issue by johanneslietz** [angular/angular-cli#2648]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
macOS Sierra

### Versions.
angular-cli: 1.0.0-beta.17
node: 4.6.0
os: darwin x64

### Repro steps.
My angular app will run in a JEE WAR container. The output path for the build command is my web app folder. The build command will clean it and delete the WEB-INF. It would be nice if the build command does not purge everything, but exclude certain files/folders from deleting.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
There's no plan for such a feature, but https://github.com/angular/angular-cli/pull/2570 would allow you to add it as an asset and auto-copy to the output path.
