### ISSUE TITLE
Can't exclude packages from the build in angular 17

### ISSUE THREAD

**Issue by noam-honig** [angular/angular-cli#26490]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

In previous versions of angular, I could define packages that will not be included in the browser bundler by adding the following key to the `package.json` file:
```json
 "browser": {
    "jsonwebtoken": false,
    "password-hash": false,
    "node-fetch": false,
    "fs": false,
    "iconv-lite": false,
    "@turf/turf": false,
    "path": false
  }
```

In the new version, this setting is ignored-  and I couldn't find an alternative.
I get the following error:
```
[ERROR] TS2307: Cannot find module 'fs' or its corresponding type declarations. [plugin angular-compiler]

    src/shared/TasksController.ts:7:28:
      7 │     const fs = await import('fs');
```

My code looks like this:
```ts
  static async setAllCompleted(completed: boolean) {
    const fs = await import('fs');
    fs.writeFileSync('tmp.txt', 'hello world');
    }
```

This code is intended to run on my backend but the method itself is referred to in the frontend for my own reasons :)

When I do the same with other vite based project, I make the following change to the vite.config.ts and it works:
```ts
  build: {
    rollupOptions: {
      external: ["fs", "nodemailer", "node-fetch", "puppeteer"],
    },
  },
```

Please help

### Minimal Reproduction

Add the following code to an angular project and import it from an angular component
export class TasksController {
  static async setAllCompleted(completed: boolean) {
    const fs = await import('fs');
    fs.writeFileSync('tmp.txt', 'hello world');
  }
}

### Exception or Error

```text
[ERROR] TS2307: Cannot find module 'fs' or its corresponding type declarations. [plugin angular-compiler]

    src/shared/TasksController.ts:7:28:
      7 │     const fs = await import('fs');
```

### Your Environment

```text
Angular CLI: 17.0.3
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.3
@angular-devkit/build-angular   17.0.3
@angular-devkit/core            17.0.3
@angular-devkit/schematics      17.0.3
@angular/cli                    17.0.3
@schematics/angular             17.0.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by JoostK** [comment]
The `browser` field in `package.json` is a Webpack feature, for this particular use-case Angular provides the `externalDependencies` property in `angular.json`.

The above is somewhat irrelevant though, since this error is reported by TypeScript, whereas the above is only relevant for the bundling phase (after TS has completed its work). You probably have `types: []` in your `tsconfig.json` (or `tsconfig.app.json`) which means that declarations in `node_modules/@types` are not automatically being included. If you rely on `@types/node` in your application code, then you'll have to include `node` in `types`.

**Comment by noam-honig** [comment]
@JoostK thanks for getting back to me.

You were right on, removing the types and adding the `externalDependencies` property to my `angular.json` file solved it.

I tried to read up on the externalDependencies property of angular.json and can't find doc's for it on:
https://angular.io/guide/workspace-config
If you can point me to the right place it'll be great.

Thanks

**Comment by alan-agius4** [comment]
You can read more about the build options in https://angular.io/cli/build

**Comment by noam-honig** [comment]
Thanks @JoostK & @alan-agius4
