### ISSUE TITLE
Add a shortcut for --dry-run as -d

### ISSUE THREAD

**Issue by DanielStoehr** [angular/angular-cli#26496]
### Command

generate

### Description

Right now i can run a dry run for generation components/services/etc. with the following command
`ng g c mytestcomponent --dry-run`

### Describe the solution you'd like

i want to generate stuff with a shortcut -d to have a shorter version of it. 
(I think in older angular versions it was possible)

**Comment by sasidharansd** [comment]
I would love to work on this

**Comment by JeanMeche** [comment]
Feel free to drop a PR !
