### ISSUE TITLE
ng init generate ember-cli-build.js

### ISSUE THREAD

**Issue by paseo** [angular/angular-cli#265]
When use ```ng init``` command, an ember-cli-build.js be created in root directory.
This is an ember-cli behavior.This command should create a file named angular-cli-build.js,i think.

**Comment by cironunes** [comment]
@paseo yep. We're aware of that. I'll try to make it all together with the production build story #41

**Comment by filipesilva** [comment]
I believe this to be fixed already, in the latest builds the `angular-cli-build.js` file is created.
