### ISSUE TITLE
ng d component 'component-name' does not delete the component if it was created using --flat

### ISSUE THREAD

**Issue by nitu-g** [angular/angular-cli#2650]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7

### Versions.

angular-cli :1.0.0-beta.16
node 6.5.0
os: win32 x64

### Repro steps.
>i created a 'flat' component using angular cli. The component got created successfully. But now for some reason I need to delete the component. When i use ng d component 'component-name' it is not deleted

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
We don't support the `ng destroy` functionality. It still runs as a `ember-cli` command.
