### ISSUE TITLE
Angular 17 Broke Older Updates

### ISSUE THREAD

**Issue by thatcort** [angular/angular-cli#26504]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

I'm trying to update an app from Angular 11 to 16. My update is failing on the first step: `ng update @angular/core@12 @angular/cli@12` which responds with an error message that NodeJS v18 is required.

I need to move from Node v14 to v16 (but not v18), but ideally during one of the later update steps, like hitting Angular v14. The current Angular CLI installed is 11.0.5. It seems that the ng update command is now demanding Node 18. There doesn't seem to be a way to proceed.

### Minimal Reproduction

Create an Angular project using v11. Try to upgrade to v12 using the command `ng update @angular/core@12 @angular/cli@12`

### Exception or Error

```text
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Node.js version v16.20.2 detected.
The Angular CLI requires a minimum Node.js version of v18.13.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
```

### Your Environment

```text
Angular CLI: 11.0.5
Node: 16.20.2
OS: linux x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.2.13
@angular/localize               11.2.14
@angular/material               11.2.13
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.7
typescript                      4.0.5
webpack                         4.46.0
```

**Comment by alan-agius4** [comment]
This should be fixed in more recent versions. 

In your case you can use the below command to update:

```
NG_DISABLE_VERSION_CHECK=1 npx @angular/cli@12 update @angular/core@12 @angular/cli@12
```
