### ISSUE TITLE
ERROR: Top-level await is not available in the configured target environment

### ISSUE THREAD

**Issue by x-wk** [angular/angular-cli#26507]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

```js
17349 │ /******/ __webpack_exports__ = globalThis.pdfjsLib = await (globalThis.pdfjsLibPromise = __webpack_exports__);


01:55:45 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/pdfjs-dist/build/pdf.mjs:17349:53: ERROR: Top-level await is not available in the configured target environment ("chrome118.0", "edge118.0", "firefox115.0", "
ios16.0", "safari16.0" + 7 overrides)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

**Comment by clydin** [comment]
From the logs, it appears that the project is using the new build system with Angular v16.  For v16, the build system was considered a developer preview and may not operate as expected in all cases.  Please consider updating to Angular v17 where the new build system is now stable and fully supported.

If you are still encountering issues after using v17, please provide an updated version output as well as a minimal reproduction demonstrating the problem so that we can investigate further.

**Comment by x-wk** [comment]
@clydin Thank you for your reply, here is a demo:

https://stackblitz.com/edit/npfsyd

**Comment by alan-agius4** [comment]
This is expected as top level awaits are not supported. 

Angular uses Zone.js which in requires always async/await to be downlevelled, in Esbuild this is done by enabling This is because we enable async/await downlevelling in esbuild which disables top level await usage. 

Let's keep tracking this in https://github.com/angular/angular-cli/issues/22191

**Comment by alan-agius4** [comment]
In this case adding the plugin in vite will only fix it it when running `ng serve`, however the application will not successfully build when running `ng build`.

**Comment by madurapa** [comment]
> @alan-agius4 Thank you for your reply, as far as I know this vite plugin `vite-plugin-top-level-await` can handle this situation, where should I add this plugin?

You can see how to config the plugin here https://www.npmjs.com/package/vite-plugin-top-level-await

**Comment by madurapa** [comment]
For those who experience the same issue in the both dev and build commands, add the following

> ```js
> // vite.config.js
> optimizeDeps: {
>   esbuildOptions: {
>     target: 'esnext'
>   }
> },
> build: {
>   target: 'esnext'
> }
> ```

**Comment by pablopla** [comment]
@madurapa can you please share the complete config file. I'm not sure where to add optimizeDeps and build.

**Comment by alan-agius4** [comment]
The vote config is internal to the CLI and cannot be modified.

As stated before top level await is not supported.

**Comment by benbro** [comment]
@alan-agius4 topLevelAwait is enabled by default in Webpack but [disabled in angular](
https://github.com/angular/angular-cli/blob/11d61223ae02c40b7197c8d6e62b871d5de76d64/packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts#L438). Is there a chance you could enable it so we won't need custom webpack builder?

**Comment by alan-agius4** [comment]
@benbro, no, as that would cause the application not to be buildable if you decide to migrate to the esbuild based builders. 

See https://github.com/angular/angular-cli/issues/26507#issuecomment-1829331289

**Comment by madurapa** [comment]
> @madurapa can you please share the complete config file. I'm not sure where to add optimizeDeps and build.

```js
export default defineConfig({
    optimizeDeps: {
        esbuildOptions: {
            target: 'esnext'
        }
    },
    build: {
        target: 'esnext'
    },
});

```

Put your config if you find it difficult to edit, I can include those values and past here
