### ISSUE TITLE
browser-esbuild: "The 'webWorkerTsConfig' option is not yet supported by this builder." 

### ISSUE THREAD

**Issue by alexciesielski** [angular/angular-cli#26538]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I just updated to Angular 17 with the hopes of benefiting of the speed improvements of esbuild but unfortunately I am getting the following warning:

`The 'webWorkerTsConfig' option is not yet supported by this builder.`

I searched Google for any hints and the only thing I found is [this issue](https://github.com/angular/angular-cli/issues/25101) mentioning the option and saying that it should have landed in 17.0.0-next.6.

So my question is, has it landed and should it work? And if yes, what may I be doing wrong?

If it matters I am using nx (also v17).

### Minimal Reproduction

```json
{
  "name": "app",
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "projectType": "application",
  "sourceRoot": "apps/app/src",
  "prefix": "app",
  "targets": {
    "build": {
      "executor": "@angular-devkit/build-angular:browser-esbuild",
       // ...
     }
  }
}
```

### Exception or Error

```text
The 'webWorkerTsConfig' option is not yet supported by this builder.
```

### Your Environment

```text
nx --version

Nx Version:
- Local: v17.1.3
- Global: v17.0.1

---

    "@angular/animations": "17.0.5",
    "@angular/cdk": "17.0.1",
    "@angular/common": "17.0.5",
    "@angular/compiler": "17.0.5",
    "@angular/core": "17.0.5",
    "@angular/forms": "17.0.5",
    "@angular/material": "17.0.1",
    "@angular/platform-browser": "17.0.5",
    "@angular/platform-browser-dynamic": "17.0.5",
    "@angular/router": "17.0.5",
    "@angular/service-worker": "17.0.5",
    "@angular-devkit/build-angular": "17.0.5",
    "@angular-devkit/core": "17.0.5",
    "@angular-devkit/schematics": "17.0.5",
```

**Comment by alan-agius4** [comment]
This is a known issue which is documented. Please see: https://angular.dev/tools/cli/esbuild#type-checking-of-web-worker-code-and-processing-of-nested-web-workers
