### ISSUE TITLE
Change app prefix

### ISSUE THREAD

**Issue by vlio20** [angular/angular-cli#2653]
Hi, 
Is there a way to change the app generated prefix + fixing the test warning: `"ObSomeComponent" should have prefix "app"`?  

I have tried to change the prefix property in the `angular-cli.json` but it didn't help.

**Comment by chadbr** [comment]
In my tslint.json, I set the check to off:

    "directive-selector-prefix": [false, "app"],

**Comment by vlio20** [comment]
thanks @chadbr !

**Comment by dahfazz** [comment]
Fixed it like this, in tslint.json

"component-selector": [
      true,
      "element",
      "ObSomeComponent",
      "kebab-case"
    ],
