### ISSUE TITLE
I am facing multiple issues while ng build and working fine with ng build --configuration=production Need help.

### ISSUE THREAD

**Issue by shashankagarwal1710** [angular/angular-cli#26544]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

When i am doing ng build its giving many errors like
1. Can not read properties of undefined
2. Can not read _rawValidators of undefined
Store null

some error in xhr 
and its not telling the source path of the error and working fine with ng build --configuration=production

I have already set sourceMap to true in angular json

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.5
Node: 18.17.1
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
