### ISSUE TITLE
`outputHashing` is ignored with lazy chunk files with esbuild angular 17

### ISSUE THREAD

**Issue by chintankavathia** [angular/angular-cli#26548]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

providing `outputHashing: none` still adds hash values to lazy chunk files with latest angular having `application` builder . 
I am not sure if this is an intended behavior.

### Minimal Reproduction

 generate the new angular application use angular cli.

do some lazy dynamic imports with `import('')`  in application module.

in angular.json add/update `outputHashing` to `none`.

Run ng build and see build output.

The lazy chunks still adds outputHash.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.5
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin arm64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@angular/cdk                    17.0.1
@angular/material               17.0.1
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by clydin** [comment]
This is expected behavior. The output hashing option applies to directly addressable files such as the initial entry points that would be injected into the index HTML.  Synthetic chunks also do not have name so would require some unique identifier regardless. The hash also guarantees name uniqueness and avoids the potential for file name overlap in the output.
