### ISSUE TITLE
The new vite dev server cannot handle URLs with a . in them - part 2

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular-cli#26551]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

angular 16

### Description

If you go to a URL with a . in it:
http://localhost:4200/something.somethingelse

with the esbuild builder, this will not go to the dev server anymore.

This is a re-opening of ticket:
https://github.com/angular/angular-cli/issues/26383

because it was closed as solved, but in both 17.0.5 as well as in 17.1.0-next this is still present

### Minimal Reproduction

just do an ng serve and go to an URL with a .

### Your Environment

```text
Angular CLI: 17.0.5
Node: 18.15.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1700.5
@angular-devkit/build-angular        17.0.5
@angular-devkit/core                 16.2.6
@angular-devkit/schematics           16.2.6
@angular/cdk                         16.2.12
@angular/fire                        16.0.0
@angular/google-maps                 16.2.12
@angular/material                    16.2.12
@angular/material-date-fns-adapter   16.2.12
@angular/youtube-player              16.2.12
@bazel/typescript                    5.8.1
@schematics/angular                  16.2.6
rxjs                                 7.8.1
typescript                           5.2.2
zone.js                              0.14.2
```

**Comment by alan-agius4** [comment]
@LanderBeeuwsaert, I am unable to replicate this with `@angular-devkit/build-angular` version `17.1.0-next.0`

**Comment by LanderBeeuwsaert** [comment]
@alan-agius4 apologies, I had updated angular-cli to 17.1.0-next.0 but not @angular-devkit/build-angular
By doing that it was solved. Thanks! closing
