### ISSUE TITLE
es-build regression 17.1.0-next.0 rebuild causes "the request url "..." is outside of Vite serving allow list."

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular-cli#26555]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.5

### Description

When having @angular-devkit/build-angular:browser-esbuild on
with build-angular and angular/cli on 17.1.0-next.0
any dev server rebuild causes:
The request url "..." is outside of Vite serving allow list for all assets

### Minimal Reproduction

I suppose it's down to my configuration somehow, but there's nothing that special to it.
reversing to 17.0.5 immediately solves this

### Your Environment

```text
Angular CLI: 17.1.0-next.0
Node: 18.15.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                              Version
--------------------------------------------------------------
@angular-devkit/architect            0.1701.0-next.0
@angular-devkit/build-angular        17.1.0-next.0
@angular-devkit/core                 16.2.6
@angular-devkit/schematics           16.2.6
@angular/cdk                         16.2.12
@angular/cli                         17.1.0-next.0
@angular/fire                        16.0.0
@angular/google-maps                 16.2.12
@angular/material                    16.2.12
@angular/material-date-fns-adapter   16.2.12
@angular/youtube-player              16.2.12
@bazel/typescript                    5.8.1
@schematics/angular                  16.2.6
rxjs                                 7.8.1
typescript                           5.2.2
zone.js                              0.14.2
```

**Comment by alan-agius4** [comment]
You can please share you assets configuration?

**Comment by LanderBeeuwsaert** [comment]
@alan-agius4 not entirely sure, but is this what you mean, at the start of angular.json?

<img width="750" alt="image" src="https://github.com/angular/angular-cli/assets/1098243/c1cc2d44-decc-42b3-b6ad-cda8812171a0">

**Comment by alan-agius4** [comment]
This should be fixed by https://github.com/angular/angular-cli/pull/26556 which will be available on NPM later this week.

**Comment by hillin** [comment]
In my case this seems fixed when running `ng serve`, but the same error occurs when hot reload is triggered.
```json
"@angular/cli": "17.1.0-next.1"
```

**Comment by LanderBeeuwsaert** [comment]
@hillin see the linked ticket #26624 , it's solved there, should probably be released this week
