### ISSUE TITLE
Live reloading not working after 3rd changes to the same file

### ISSUE THREAD

**Issue by radvil** [angular/angular-cli#26565]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, core

### Is this a regression?

Yes

### Description

After I change for example buttons color with different value let's say
- initial value was `red`
- change to `yellow` (this still works)
- change back to `red` (from here the change not working)

### Please provide a link to a minimal reproduction of the bug

https://github.com/radvil/angular-repro/tree/v17-hot-reload

### Please provide the exception or error you saw

```true
There was no errors nor exception found either in `angular-cli` output or in the `chrome-devtools` console
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
----------------
OS: Arch Linux x86_64
Host: Swift SF314-43 V1.06
Kernel: 6.1.64-1-lts
Packages: 1387 (pacman)

{
  "name": "angular-repro",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/router": "^17.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^17.0.5",
    "@angular/cli": "^17.0.5",
    "@angular/compiler-cli": "^17.0.0",
    "typescript": "~5.2.2"
  }
}
```

### Anything else?

my initial setup
- style=scss
- minimal
- skip-tests
- no ssr/ssg
- routing

I've been facing this issue since last couple weeks, I tried to search for the similar issue on this repo's issue list but I can't anything helpful, so I started this issue my own. TBH I still don't know whether this is related to my OS, kernel version, angular cli, or anything else.

**Comment by radvil** [comment]
I've updated the title just to clarify what happened. Also please note, I've been trying to remove `dist` + `.angular` folder just in case this might the causes, but still doesn't work.

**Comment by radvil** [comment]
Another info I can  provide
Before the stable release of v17, I've tried with `@angular/cli@next` (v17 next, I forget the specific version) which has signal already but haven't introduced the new control flow and `esbuild`. It worked fine until the stable of v17 announced..

**Comment by alan-agius4** [comment]
@radvil, I am unable to replicate this using the reproduction you provided. Can you please verify if you are still able to replicate it on your side?

**Comment by radvil** [comment]
> @radvil, I am unable to replicate this using the reproduction you provided. Can you please verify if you are still able to replicate it on your side?

Ah thanks for the response, I ll do it tonight using the same repo i provided, is it okay if record the screen ? I ll comeback soon..

**Comment by radvil** [comment]
Here is a link to video reproduction i've just recorded.

https://youtu.be/f49EWI9-6Tc

# Operating System
Arch Linux

# Terminal
tmux

# IDE
neovim

## steps

1. clone the repo
2. checkout to reproduction branch
3. npm install
4. npm start

## tested browsers

1. Google Chrome (private tab)
2. Firefox (private tab)
3. Brave (private tab)

I am investigating other possibilities maybe to toggle among other IDEs and not using tmux, or try a new release for `17.0.6`. I' ll tell you the results soon @alan-agius4

**Comment by radvil** [comment]
## UPDATE

This is my attempt after upgrade the packages. It still have the same behavior

```bash
❯ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.6
Node: 20.10.0
Package Manager: npm 10.2.4
OS: linux x64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6
@angular-devkit/schematics      17.0.6
@schematics/angular             17.0.6
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

Here is the latest repo: https://github.com/radvil/angular-repro/tree/v17-hot-reload-upgraded-version

It's weird for me, it works when I use `vscode` but not with `neovim` (I also tried using vanilla `neovim`),
When I try with the same setup on my other projects (based on the previous version, mostly `v16`), it just worked.

Do you think I should just create a separate issue for this @alan-agius4 ?

**Comment by radvil** [comment]
Just in case you need this information

```bash
❯ tmux -V
tmux 3.3a

❯ nvim -v
NVIM v0.10.0-dev-1764+g5b40a1c09

❯ kitty -v
kitty 0.31.0 created by Kovid Goyal
```

**Comment by alan-agius4** [comment]
Can you try use the snapshot version of 17.1.0 that includes https://github.com/angular/angular-cli/pull/26579

```
npm install git+https://github.com/angular/angular-devkit-build-angular-builds.git --dev --force
```

**Comment by radvil** [comment]
> Can you try use the snapshot version of 17.1.0 that includes #26579
> 
> ```
> npm install git+https://github.com/angular/angular-devkit-build-angular-builds.git --dev --force
> ```

This seems do the job, every changes now send the page reload.
When will be merged to stable ? I have one production app needs to be updated.

![image](https://github.com/angular/angular-cli/assets/36059968/5fe04dda-96e2-4dfc-a8b5-c1123708b893)
