### ISSUE TITLE
Esbuild does not work with custom Locale IDs

### ISSUE THREAD

**Issue by pjms** [angular/angular-cli#26563]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

The new builder (either one of `browser-esbuild` or `application`) seems to break the build(`exit code 1`) when ALL of following conditions are met:
- The build task is ran on a CI runner
- The project is enabled with Angular Localize
- **The project has one or more "custom" locale ids that is on the Angular repository but in a different case.**

For instance,
- "en" is on the ng's repository, and it does not break the build.
- "ja-jp" is not on the repository, but Angular manages to find alternative(`jp`), so it does not break the build either.
- "sw-ke" is on the repository but in a different case(`sw-KE`), the builder does manage to spot the corresponding locale, but the build exits with error code 1 nonetheless.

### Minimal Reproduction

This is my repro: https://gitlab.com/moonsub.um/repro-angular17-esbuild-localeid

This project consists of three locales:
- `en-US` as sourceLocale
- `ja-jp`
- `sw-ke`

also with repro build results:
- using `browser` builder (success): https://gitlab.com/moonsub.um/repro-angular17-esbuild-localeid/-/pipelines/1093519674
- using `browser-esbuild` builder (failed): https://gitlab.com/moonsub.um/repro-angular17-esbuild-localeid/-/pipelines/1093520358
- using `application` builder (failed): https://gitlab.com/moonsub.um/repro-angular17-esbuild-localeid/-/pipelines/1093519163

**The build was successful on the local environment, regardless of the builder used.**

### Exception or Error

```text
# In case of this project:

✘ [ERROR] Could not read from file: /builds/moonsub.um/repro-angular17-esbuild-localeid/node_modules/@angular/common/locales/global/sw-ke.js
    angular:polyfills:angular:polyfills:1:7:
      1 │ import 'angular:locale/data:sw-ke';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Application bundle generation failed. [10.672 seconds]


---
# An excerpt from another project with slightly different configuration(probably how polyfills is imported):

✘ [ERROR] ENOENT: no such file or directory, open '/builds/.../node_modules/@angular/common/locales/global/sw-ke.js' [plugin angular-compiler]
    angular:polyfills:angular:polyfills:3:7:
      3 │ import 'angular:locale/data:sw-ke';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~
  This error came from the "onLoad" callback registered here:
    node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compiler-plugin.js:295:18:
      295 │             build.onLoad({ filter: /\.[cm]?js$/ }, (0, load_resul...
          ╵                   ~~~~~~
    at setup (/builds/.../node_modules/@angular-devkit/build-angular/src/tools/esbuild/angular/compiler-plugin.js:295:19)
    at async handlePlugins (/builds/.../node_modules/@angular-devkit/build-angular/node_modules/esbuild/lib/main.js:1340:9)
```

### Your Environment

```text
Angular CLI: 17.0.5
Node: 18.17.0
Package Manager: npm 9.6.7
OS: darwin arm64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by clydin** [comment]
This should be addressed by #26566 and available in the next patch release later this week.
