### ISSUE TITLE
[es-build] Can the Browser file name be modified during ng build?

### ISSUE THREAD

**Issue by HCenggel** [angular/angular-cli#26569]
### Command

build

### Description

Our project is being upgraded to angular17, but ng build has caused a huge workload on our project, resulting in the possibility that the upgrade work will be terminated.

Is it possible to add something like --browser-output-path --server-output-path to solve this problem?

At present, I modified the source file of @angular-devkit to achieve the goal, but this is not a good solution.

Are there any official plans for this issue? This is very important for our company's subsequent upgrade work.

### Describe the solution you'd like

--browser-output-path --server-output-path ?

**Comment by HCenggel** [comment]
> Updating to Angular v17 does not require changing the build system. The existing `browser` builder is fully supported in v17. There are also two options for optionally moving to the new build system. One of which is designed for compatibility and requires minimal changes to move a project. For additional information please see the guide here: https://angular.dev/tools/cli/esbuild

Now after packaging, dist/xxx/browser and dist/xxx/server appear. I want to change the names of the browser and server folders, but it is not written in this document.

**Comment by alan-agius4** [comment]
At present the directory names cannot be changed through the `ng build` command. 

If you’d like to rename the directories to something else, you can use a a postscript.

**Comment by HCenggel** [comment]
> At present the directory names cannot be changed through the `ng build` command.
> 
> If you’d like to rename the directories to something else, you can use a a postscript.

I now directly change the node_modules\@angular-devkit\build-angular\src\tools\esbuild\utils.js file to implement

**Comment by HCenggel** [comment]
![image](https://github.com/angular/angular-cli/assets/24600623/d8f49d66-6094-4036-82ff-219cbe879666)
This is a temporary solution

**Comment by clydin** [comment]
As mentioned in the guide, updating to Angular v17 does not require changing the builder in the `angular.json` file for the project.  The `@angular-devkit/build-angular:browser` builder can continue to be used if preferred with v17.

Also, the `@angular-devkit/build-angular:browser-esbuild` builder provides the performance benefits of the new build system but operates in a similar manner to `@angular-devkit/build-angular:browser` including the output locations.

**Comment by HCenggel** [comment]
> As mentioned in the guide, updating to Angular v17 does not require changing the builder in the `angular.json` file for the project. The `@angular-devkit/build-angular:browser` builder can continue to be used if preferred with v17.
> 
> Also, the `@angular-devkit/build-angular:browser-esbuild` builder provides the performance benefits of the new build system but operates in a similar manner to `@angular-devkit/build-angular:browser` including the output locations.

I'm looking at the documentation

**Comment by HCenggel** [comment]
> At present the directory names cannot be changed through the `ng build` command.
> 
> If you’d like to rename the directories to something else, you can use a a postscript.

Thank you for your reply, finally I solved my problem using @angular-devkit/build-angular:browser-esbuild, thanks again

**Comment by HCenggel** [comment]
> As mentioned in the guide, updating to Angular v17 does not require changing the builder in the `angular.json` file for the project. The `@angular-devkit/build-angular:browser` builder can continue to be used if preferred with v17.
> 
> Also, the `@angular-devkit/build-angular:browser-esbuild` builder provides the performance benefits of the new build system but operates in a similar manner to `@angular-devkit/build-angular:browser` including the output locations.

Thank you for your reply, finally I solved my problem using @angular-devkit/build-angular:browser-esbuild, thanks again

**Comment by HCenggel** [comment]
Although the problem was solved with @angular-devkit/build-angular:browser-esbuild, it would be nice for @angular-devkit/build-angular:application to have the features I want
