### ISSUE TITLE
`ng serve` randomly stops watching for file changes

### ISSUE THREAD

**Issue by Carlosamouco** [angular/angular-cli#26562]
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

The `ng serve` randomly stops watching for file changes using the new builder after rebuilding a library in watch mode. 

### Minimal Reproduction

1. Create a new workspace: `ng new my-app`;
1. Create a library: `ng generate library my-lib`;
2. Run `ng build my-lib --watch`;
3. Run `ng serve`;
4. Save any *.ts file within "my-lib";

Result:
The application is rebuilt a couple of times in a row and the dev-server stops watching for file changes;
Sometimes it still works after saving a file for a couple of times and other times, it stops working just after the first save.

### Exception or Error

```text
N.A.
```

### Your Environment

```text
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.5
Node: 18.18.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

I am using vs code as IDEE.

From version 7.0.3 onwards, the dev server rebuilds twice in a row for any file change in a library, making the problem easier to reproduce. I think that's also a bug since in version 7.0.2 the application was rebuilding just once as it should. It seams the builder is picking up the *.ts file of the library as a trigger to rebuild.

**Comment by radvil** [comment]
This also happened to me, here is the the duplicated #26565

**Comment by JeanMeche** [comment]
Let's track this in a single issue then !

**Comment by alan-agius4** [comment]
@Carlosamouco, indeed this seems like a completely separate issue.

**Comment by HitkoDev** [comment]
I've been experiencing the same issue, `dist/my-lib` contains new files, but dev server keeps serving cached version until I delete `.angular` dir and restart the server.

**Comment by Carlosamouco** [comment]
@HitkoDev, in my case, the dev server stops rebuilding completely even if I change any file under the src/app dir. It's noticeable because I stop getting rebuild logs in the terminal where I am running `ng serve`.

**Comment by alan-agius4** [comment]
@Carlosamouco, is still still reproducible using `@angular-devkit/build-angular` version 17.0.6?
