### ISSUE TITLE
SSR: Request & Response objects

### ISSUE THREAD

**Issue by james-albanese** [angular/angular-cli#26581]
### Command

serve

### Description

It would be great to have access to the Request & Response objects. This was possible with `@nguniversal/express-engine` via the respective injection tokens. 

### Describe the solution you'd like

`REQUEST` & `RESPONSE` injection tokens.

These should be automatically accessible from the app when running on the dev server. They can then be provided from `server.ts` in a production environment.

**Comment by JeanMeche** [comment]
Hi, this is actively discussed at https://github.com/angular/angular-cli/issues/26323 !
