### ISSUE TITLE
ng github-pages:deploy with Travis CI

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular-cli#2658]
How would I set it up so that `ng github-pages:deploy` works with Travis CI?

When I run it in my `.travis.yml`, i get:

```
Command failed: git push origin gh-pages:gh-pages
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/dolanmiu/hingyman.git/'
```

How do I specify such username and password?

**Comment by scttcper** [comment]
You should setup a github token for travis to use.

this looks correct
https://github.com/steveklabnik/automatically_update_github_pages_with_travis_example

**Comment by filipesilva** [comment]
You need to setup git in your CI. It's not something we can do in the CLI.
