### ISSUE TITLE
Cannot install Angular ssr in existing project which upgrade to Angular 17

### ISSUE THREAD

**Issue by ranjeet1sn** [angular/angular-cli#26592]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I want to install angular ssr in my exsiting project but I am unable to do this.Because it is giving me dependency error.I have tried many solution but not working
![Screenshot 2023-12-06 105712](https://github.com/angular/angular-cli/assets/50514433/a2a4c560-f9a2-4ff1-bbf3-2081d0ca04a0)

### Minimal Reproduction

Install angular fire in new project and try then add ssr to angular  it is not allowing to install it 

### Your Environment

```text
Angular CLI: 17.0.5
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@angular/cdk                    17.0.2
@angular/fire                   16.0.0
@angular/material               17.0.2
@schematics/angular             17.0.5
rxjs                            7.8.1
typescript                      5.3.2
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment]
This problem because you are using a TypeScript version that is not yet supported.

This is causing a peer dependency mismatch during NPM install.

Downgrade to a supported TypeScript version 5.2.x should solve this issue.

**Comment by JoostK** [comment]
TypeScript 5.3 is not supported in Angular 17.0, support has only been added in 17.1 which hasn't been released yet.
