### ISSUE TITLE
favicon.ico is missing when run "ng build"

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/angular-cli#2659]
### OS
OS X El Capitan

### Versions
angular-cli: 1.0.0-beta.15
node: 6.3.1
os: darwin x64

### Repro steps
Just create a new project, and run `ng build --dev` or `ng build --prod`.
favicon.ico is not in the **dist** folder. Have to copy the icon to the folder by self.

**Comment by Anufriev** [comment]
Also robots.txt is missing

**Comment by grizzm0** [comment]
This has been fixed in #2570 making it possible to set an array of assets to copy over instead of a single directory. The patch will be shipped with the next npm release (probably beta.18).
