### ISSUE TITLE
Updating to angular 17 fails with error: No matching version found for node-releases@^2.0.14

### ISSUE THREAD

**Issue by markchagers** [angular/angular-cli#26598]
### Command

update

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.12

### Description

When upgrading our project to angular 17, we get a lot of incompatible peer dependency errors. Even when using --force or --legacy-peer-deps options. The final error message is always: 
```
notarget No matching version found for node-releases@^2.0.14.
```
See the terminal output and the npm log file as attached.

[2023-12-06T14_39_04_577Z-debug-0.log](https://github.com/angular/angular-cli/files/13587385/2023-12-06T14_39_04_577Z-debug-0.log)
[terminal-output.txt](https://github.com/angular/angular-cli/files/13587430/terminal-output.txt)

### Minimal Reproduction

ng update --force @angular/core@17 @angular/cli@17

### Exception or Error

```text
See the attached files
```

### Your Environment

```text
Angular CLI: 16.2.10
Node: 18.19.0
Package Manager: npm 10.2.3
OS: darwin x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

### Anything else relevant?

This happens when trying to update our project from angular 16 to angular 17 in VSCode

**Comment by alan-agius4** [comment]
node-release version 2.0.14 is available on the public NPM repository, see; https://www.npmjs.com/package/node-releases

if you are using a private NPM repository or proxy please make sure that this is syncing correctly.

Closing as this is not an issue with Angular CLI.
