### ISSUE TITLE
ng generate model create the file in incorrernt path.

### ISSUE THREAD

**Issue by paseo** [angular/angular-cli#266]
If a run the command ```ng generate model todo```.The created todo model file path is `/app/models/todo.js`.I think the current file path is `/src/app/models/todo.js`.

**Comment by Brocco** [comment]
Generating a model is not a supported a supported action in the angular-cli, it is a holdover as it is based upon the ember-cli.

I believe what you're trying to accomplish is generation of a service, in which case you'll want to use this command:

```
ng generate service todo
```

**Comment by paseo** [comment]
Thks.
I know angular-cli is based on ember-cli.But if some ember-cli commands are not supported in the angular-cli.I think the angular-cli should return the warning message and do nothing.

**Comment by Brocco** [comment]
Agreed, we will certainly investigate handling this gracefully
