### ISSUE TITLE
Node-sass building failure when upgrading to  1.0.0-beta.17

### ISSUE THREAD

**Issue by hantsy** [angular/angular-cli#2660]
Upgrading to 1.0.0-beta.17 and encounter this problem.  1.0.0-beta.16 worked well on my system. It is possible to provide bin for these dependencies when installing without compiling.

> Please provide us with the following information:
> -----------------------------------------------------------

<pre>
ble loss of data (compiling source file ..\src\custom_function_bridge.cpp) [E:\
hantsylabs\angular2-sample\vanilla\node_modules\node-sass\build\binding.vcxproj
]
  e:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\src\callback_bri
dge.h(162): warning C4267: 'argument': conversion from 'size_t' to 'int', possi
ble loss of data (compiling source file ..\src\custom_importer_bridge.cpp) [E:\
hantsylabs\angular2-sample\vanilla\node_modules\node-sass\build\binding.vcxproj
]
  e:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\src\callback_bri
dge.h(110): warning C4267: 'argument': conversion from 'size_t' to 'int', possi
ble loss of data (compiling source file ..\src\binding.cpp) [E:\hantsylabs\angu
lar2-sample\vanilla\node_modules\node-sass\build\binding.vcxproj]
  e:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\src\callback_bri
dge.h(162): warning C4267: 'argument': conversion from 'size_t' to 'int', possi
ble loss of data (compiling source file ..\src\binding.cpp) [E:\hantsylabs\angu
lar2-sample\vanilla\node_modules\node-sass\build\binding.vcxproj]
  e:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\src\callback_bri
dge.h(162): warning C4267: 'argument': conversion from 'size_t' to 'int', possi
ble loss of data (compiling source file ..\src\sass_context_wrapper.cpp) [E:\ha
ntsylabs\angular2-sample\vanilla\node_modules\node-sass\build\binding.vcxproj]
  e:\hantsylabs\angular2-sample\vanilla\node_modules\nan\nan_new.h(208): warnin
g C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss o
f data (compiling source file ..\src\sass_types\list.cpp) [E:\hantsylabs\angula
r2-sample\vanilla\node_modules\node-sass\build\binding.vcxproj]
  e:\hantsylabs\angular2-sample\vanilla\node_modules\nan\nan_new.h(208): warnin
g C4244: 'argument': conversion from 'std::size_t' to 'double', possible loss o
f data (compiling source file ..\src\sass_types\map.cpp) [E:\hantsylabs\angular
2-sample\vanilla\node_modules\node-sass\build\binding.vcxproj]

"E:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\build\binding.sln
" (default target) (1) ->
"E:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\build\binding.vcx
proj.metaproj" (default target) (2) ->
"E:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\build\binding.vcx
proj" (default target) (4) ->
(Link target) ->
  E:\Users\hantsy\.node-gyp\6.7.0\Release\node.lib : fatal error LNK1127: libra
ry is corrupt [E:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass\bui
ld\binding.vcxproj]

    18 Warning(s)
    1 Error(s)

Time Elapsed 00:01:03.43
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\hantsylabs\angular2-sample\vanilla\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\hantsylabs\\angular2-sample\\vanilla\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\hantsylabs\angular2-sample\vanilla\node_modules\node-sass
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
Build failed
angular2-sample@0.0.0 E:\hantsylabs\angular2-sample\vanilla
`-- (empty)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.10.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.10.1 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\hantsylabs\angular2-sample\vanilla\npm-debug.log
npm ERR! code 1
</pre>

### OS?
> Windows 10 

### Versions.
> angular-cli: 1.0.0-beta.17
>node: 6.7.0
>os: win32 x64

### Repro steps.
> When created a new project, it install the dependencies, but `node-sass` building caused failure

### The log given by the failure.
>  Attached my npm-debug.log
[npm-debug.zip](https://github.com/angular/angular-cli/files/523398/npm-debug.zip)

**Comment by filipesilva** [comment]
I'll bump this dependency but that's the best I can do.
