### ISSUE TITLE
Angular 17 prerendering global polyfill

### ISSUE THREAD

**Issue by submarines-and** [angular/angular-cli#26608]
### Command

build

### Description

We have a lot of depdendencies that rely on `document` calls, e.g. web components. When using `angular universal` for prerendering, we could fix this by having a document polyfill that we imported in `main.server.ts`.

```javascript
global.document = {
[...]
};
```

When moving to prerendering using `@angular/ssr`, this no longer works. Is there a way to similarily have a polyfill that is included in every chunk in angular 17? Adding it as a polyfill in angular.json does not work either.

### Describe the solution you'd like
Allow for a global polyfill that is included in every file during prerendering

**Comment by submarines-and** [comment]
That's the solution that does not work. Should `globalThis` in theory also become available for angular linraries and third party dependencies?

**Comment by alan-agius4** [comment]
Yes, in that case kindly provide a minimal reproduction.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
