### ISSUE TITLE
Renew  Angular Dependency 

### ISSUE THREAD

**Issue by goriunov** [angular/angular-cli#2661]
Hello I have noticed that you still have not renew Angular Dependency , it came out long time ago .
    "@angular/common": "~2.0.2",
    "@angular/compiler": "~2.0.2",
    "@angular/core": "~2.0.2",
    "@angular/forms": "~2.0.2",
    "@angular/http": "~2.0.2",
    "@angular/platform-browser": "~2.0.2",
    "@angular/platform-browser-dynamic": "~2.0.2",
    "@angular/router": "~3.0.2",
    "@angular/upgrade": "~2.0.2",

When are you going to do that ?

**Comment by grizzm0** [comment]
There is no need to change those dependencies after every release.

~2.0.0 simply means that this package will work with anything betweeen >=2.0.0 and <2.1.0. 
NPM will automatically download the latest release which is 2.0.2 atm.

**Comment by filipesilva** [comment]
@grizzm0 is correct.
