### ISSUE TITLE
checkout dev after gihub-page deploy stoped

### ISSUE THREAD

**Issue by FallenRiteMonk** [angular/angular-cli#2663]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> OpenSuse Tumbleweed
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
> angular-cli: 1.0.0-beta.17
> node: 6.7.0
> os: linux x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> - create a small project
> - deploy in on github pages
> - do some changes that do not affect the build (I don't know if this is actually needed)
> - rerun the github page deploy command
### The log given by the failure.

> Normally this include a stack trace and some more information.
> The project is build but it is says that the deploy has stopped due to no changes and exits
### Mention any other details that might be useful.

I think this is great, but it should still change back to the master server and not leave the gh-pages branch checked out on the repo

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by taylorjb** [comment]
@filipesilva I looked at #3030 originally without looking here too.  I'm sorry.
