### ISSUE TITLE
16.2.10 - ng build fails: Inlining of fonts failed, self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by awdorrin** [angular/angular-cli#26645]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.1.8

### Description

After updating to angular 16.2.10 our application builds are failing with:
```
✖ Index html generation failed.
Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap over the internet.
self-signed certificate in certificate chain
```
Our index.html contains:
```
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
```
Build works if I remove those lines, and fonts seem to be working fine, with an SCSS file importing the fonts with:
```
@import url('https://fonts.googleapis.com/css?family=Material+Icons');
@import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500');
```
Configuring .npmrc with cafile reference, or strict-ssl=false has no effect.

### Minimal Reproduction

Angular 16.2.10 application with index.html that contains link hrefs to fonts.googleapis.com
Example:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Test App</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <app-root></app-root>
</body>
</html>
```
Will build under 16.1.8, will not build under 16.2.10

### Exception or Error

```text
>ng build --configuration production
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✖ Index html generation failed.
Inlining of fonts failed. An error has occurred while retrieving https://fonts.googleapis.com/css?family=Roboto:300,400,500&display=swap over the internet.
self-signed certificate in certificate chain
```

### Your Environment

```text
Angular CLI: 16.2.10
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.10
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

### Anything else relevant?

Have not yet found a work-around other than removing the <link> references from index.html

**Comment by awdorrin** [comment]
I should add, I am behind a corporate proxy server.

**Comment by awdorrin** [comment]
Think I found a work around, but still would like to understand why this is happening.
In angular.json change:
```
          "configurations": {
            "production": {
              "optimization": true,
```
to
```
          "configurations": {
            "production": {
              "optimization": {
                "scripts": true,
                "styles": {
                  "minify": true,
                  "inlineCritical": true
                },
                "fonts": false
              },
```

**Comment by alan-agius4** [comment]
This is expected as disabling certificate validation during font inling was a potential security vulnerability see: https://github.com/angular/angular-cli/pull/25741.

You could try to use `NODE_OPTIONS=--use-openssl-ca` which tells Node.js to use the system CA instead of the built-in. See:  https://nodejs.org/api/cli.html#--use-bundled-ca---use-openssl-ca

**Comment by awdorrin** [comment]
Ok, I found if I define environmental variables, like you suggest, I can get the build to work:
```
NODE_OPTIONS=--use-openssl-ca
SSL_CERT_FILE=C:\mycerts\self-signed.pem
```
It would be great if I could:
1.  provide a URL instead of a file reference, 
2. put this in a configuration file like npmrc
but neither of those appear to be possible, from my limited Googling this afternoon.

**Comment by alan-agius4** [comment]
Since this is not an NPM config, you cannot specify this setting in npmrc.

You can configure `NODE_OPTIONS` environment variable in your bashrc, zshrc or similar although these would apply globally.

**Comment by awdorrin** [comment]
Sure, while we can set environmental variables, it would be much cleaner to define these within project specific configuration files, so that each developer doesn't have to reconfigure their local environment. 
Not to mention, these environmental variables now have to be added to every CI/CD pipeline once we upgrade those applications past 16.1.
