### ISSUE TITLE
ng serve not building correctly when save multiple files at once

### ISSUE THREAD

**Issue by akram1905** [angular/angular-cli#2665]
> ## Please provide us with the following information:
### OS?

> Windows 10.
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and angular-cli: 1.0.0-beta.15  
> node: 6.2.2  
> os: win32 x64   
### Repro steps.
- Run `ng serve`.
- Change code on multiple files.
- Use 'save all' command.

`ng serve` will now start build process.
The build will catch only one file's changes!
### The log given by the failure.

> Normally this include a stack trace and some more information.
### Mention any other details that might be useful.

I'm using Vs Code.

Depending on changes:
After `ng serve` build process finish, either I'll get an Typescript error or it'll not be updated.
If error happens, I'll go to re-save the file with errors (add empty line and save), but in browser I'll get: 

```
[WDS] App updated. Recompiling...
[WDS] Nothing changed.
```

**Comment by awerlang** [comment]
Starting in beta.30, I noticed this too.

```
@angular/cli: 1.0.0-beta.30
node: 6.9.1
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/cli: 1.0.0-beta.30
@angular/compiler-cli: 2.4.5
@angular/platform-server: 2.4.5
```

**Comment by filipesilva** [comment]
This is fixed in beta.31, via https://github.com/angular/angular-cli/pull/4542
