### ISSUE TITLE
upgrade boot

### ISSUE THREAD

**Issue by mouhebsa** [angular/angular-cli#26683]
### Command

generate, update

### Description

Is there any third part or AI tools that take care of all steps of migration of an angular app except ng-upgrade
i have a really complex app and upgrade always failing

### Describe the solution you'd like

Is there any thirdpart or AI that takes an entire repo and return the app with the latest version

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
