### ISSUE TITLE
Upgrading angular 14 to 16, breaking change on optimizer option activated on build productiton

### ISSUE THREAD

**Issue by Razgort** [angular/angular-cli#26697]
### Which @angular/* package(s) are the source of the bug?

compiler, core

### Is this a regression?

Yes

### Description

When I upgraded my application from 14 to 16.
Everything was smooth, and I thought the migration was complete.
But once I build on production, the build work and complete but as I launch the app, there is a console error loading module that is totally unclear. The error does not appear on dev build. And if I set the optimizer option to false on production build, everything work perfectly.
But the bundle size goes from 24MB to 74MB which is a huge loss in terms of performance issue.
I would like to know if you have any idea of what can be the issue.

Thanks in advance,
any kind of help or suggestion would be very much appreciated

![2023-12-18 10_43_04-angular json - ClientApp - Visual Studio Code](https://github.com/angular/angular/assets/9212658/445fdf65-b40c-4285-ab56-e635c48f2049)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.8
Node: 18.17.1
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 16.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.10
@angular-devkit/build-angular      16.1.8
@angular-devkit/build-ng-packagr   0.1000.5
@angular-devkit/core               16.1.8
@angular-devkit/schematics         16.1.8
@angular/cdk                       16.2.12
@angular/cli                       16.1.8
@angular/flex-layout               15.0.0-beta.42
@angular/material                  14.2.7
@angular/material-moment-adapter   16.2.12
@angular/pwa                       16.2.10
@angular/router                    16.2.12
@angular/service-worker            16.2.12
@schematics/angular                16.1.8
ng-packagr                         16.2.3
rxjs                               7.8.1
typescript                         5.1.6
webpack                            5.89.0
zone.js                            0.13.3
```

**Comment by JeanMeche** [comment]
Could you do a build without mangling ? : `NG_BUILD_MANGLE=0 npm run build`

**Comment by Razgort** [comment]
i still have the same exact issue with this command
![image](https://github.com/angular/angular-cli/assets/9212658/efe0affe-38fc-4ce7-bf4a-15c4aa88f328)

**Comment by Razgort** [comment]
okay it seems that with adding aot option at true solves the issue, but i don't know why leaving as it was working on 14 , optimizer at true and no option aot specified is breaking now

**Comment by alan-agius4** [comment]
Hi @Razgort, can you provide the error message after running

```
ng cache clean
NG_BUILD_MANGLE=0 npm run build
```

**Comment by rms2219** [comment]
We're having a similar issue where all of sudden (Angular 17 though) where everything works fine building for development, but on a production configuration (default config using optimizations), file imports seem to get mangled and seemingly completely random types replace other types in generic function calls. 

As an example, on a component initialization, we have the following service function call, where `User` is an exported class.

```
ngOnInit() {
    this.users$ = this.resourceMananger.getCollection<User>(User, {params: {sort: 'lastName', order: 'asc'}})
      .pipe(map(r => r.resources));
 }
```

User.ts
```
export class User extends Resource
{
  id!: number;
}
```

ResourceMananger.ts
```
public getCollection<T extends Resource>(
  type: new () => T,
  options?: {[key: string]: any}
): Observable<ResourceCollection<T>> {
   return this.httpClient
     .get(this.generateRoute(type), options)
     .pipe(map((data: any) => this.createResourceCollection(ResourceCollection<T>, type.name, data)));
}
```

This works fine on a development configuration AND when optimizations are turned off on a production configuration. However, when optimizations are on, for some reason the type `T` is changed from `User` with another type `File`.

File.ts
```
export class File extends Resource
{
  id!: number;
}
```

Other properties on these files have been removed for brevity/confidentiality.

**Comment by alan-agius4** [comment]
@rms2219, it appears that you are reporting a different issue. That said, class names are not guaranteed to be the same after bundling and optimization.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
