### ISSUE TITLE
ng update failure with old v9 'migrate-only' value

### ISSUE THREAD

**Issue by jitterbox** [angular/angular-cli#26703]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

unknown

### Description

Upgrading a huge old project from Angular 8 to 17. The upgrade from 8.2.14 to 9.1.13 partially succeeds but fails on the migration step, and the failure message states to use this command to run only the migration step later:
`ng update @angular/core --migrate-only migration-v9-undecorated-classes-with-di`

I ensured my global and local CLI versions matched @ v9.1.15, with compatible Node 12.11.1, but when running the command, it states:
"The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update."
...and fails, stating that it requires a minimum of Node 18.13.0

With Node 18.13.0 or 21.4.0, the command still errors with:
`Error: A single package must be specified when using the 'migrate-only' option.`

ChatGPT and some research suggest using `--from` and `--to`, and specifying a package version, but this variation also fails with the same error:
`ng update @angular/core@9 --migrate-only migration-v9-undecorated-classes-with-di --from 8.2.14 --to 9.1.13`

Any workarounds?

### Minimal Reproduction

Use a base Angular 9.1.13 project.
Execute `ng update @angular/core --migrate-only migration-v9-undecorated-classes-with-di`

### Exception or Error

```text
Error: A single package must be specified when using the 'migrate-only' option.
```

### Your Environment

```text
Angular CLI: 9.1.15
Node: 21.4.0
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cdk                      9.1.3
@angular/cli                      9.1.15
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.5.3
typescript                        3.8.3
webpack                           4.42.0
```

### Anything else relevant?

Full output of failed `ng update`:

Node.js version v21.4.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/previous-releases/.
(node:234636) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
The installed local Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Node.js version v21.4.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/previous-releases/.
Workspace extension with invalid name (defaultProject) found.
Error: A single package must be specified when using the 'migrate-only' option.

**Comment by clydin** [comment]
You should be able to use the environment variable `NG_DISABLE_VERSION_CHECK=1` on older versions to bypass the update version check and prevent the minimum Node.js version error.

**Comment by alan-agius4** [comment]
Closing as per above recommendation and Angular versions prior to version 15 are no longer supported.
