### ISSUE TITLE
How to use angular-cli in project that is not generated with angular-cli

### ISSUE THREAD

**Issue by denimaaark** [angular/angular-cli#2670]
Hello,

i have already Angular2Spa project and i want to use angular-cli for creating componens,
for example ng g component my-component. I thing this is good scaffolding start point, it saves me some time for copy-paste or doing same work with initial creating files.

I can't do this, i am getting error "You have to be inside an angular-cli project in order to use the generate command."

Please how to use angular-cli with projects that are not created with angular-cli ?

Thank You

**Comment by grizzm0** [comment]
You need angular-cli.json.

Please use stackoverflow for questions in the future.

**Comment by filipesilva** [comment]
You might have some success in having a `angular-cli.json` with config values at the root of your project, but at the moment we don't really support this usage so I can't guarantee it'll work or that you'll get support for it.
