### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'jquery')

### ISSUE THREAD

**Issue by hamzou247** [angular/angular-cli#26719]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When starting angular universal project, the following error occurs:

```
TypeError: Cannot read properties of undefined (reading 'jquery')
    at Object.jQueryDetection (C:\projects\admin-safesante-front\dist\admin\main.js:1:164461)
    at C:\projects\admin-safesante-front\dist\admin\main.js:1:164686
    at 23533 (C:\projects\admin-safesante-front\dist\admin\main.js:1:242774)
    at __webpack_require__ (C:\projects\admin-safesante-front\dist\admin\main.js:1:3315966)
    at C:\projects\admin-safesante-front\dist\admin\main.js:1:4130344
    at C:\projects\admin-safesante-front\dist\admin\main.js:1:4133949
    at Object.<anonymous> (C:\projects\admin-safesante-front\dist\admin\main.js:1:4134181)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
```
ng version:

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 17.0.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1700.7
@angular-devkit/build-angular      17.0.7
@angular-devkit/core               17.0.7
@angular-devkit/schematics         17.0.7
@angular/cdk                       17.0.4
@angular/flex-layout               15.0.0-beta.42
@angular/material                  17.0.4
@angular/material-moment-adapter   17.0.4
@schematics/angular                17.0.7
rxjs                               7.8.1
typescript                         5.2.2
zone.js                            0.14.2

### Minimal Reproduction

nx run admin:serve-ssr

    "serve-ssr": {
      "executor": "@angular-devkit/build-angular:ssr-dev-server",
      "options": {
        "browserTarget": "admin:build",
        "serverTarget": "admin:server"
      },
      "configurations": {
        "development": {
          "browserTarget": "admin:build:development",
          "serverTarget": "admin:server:development",
          "proxyConfig": "proxy-development.config.json"
        },
        "production": {
          "browserTarget": "admin:build:production",
          "serverTarget": "admin:server:production",
          "proxyConfig": "proxy-prod.config.json"
        }
      },
      "defaultConfiguration": "development"
    },

### Exception or Error

```text
TypeError: Cannot read properties of undefined (reading 'jquery')
    at Object.jQueryDetection (C:\projects\admin-safesante-front\dist\admin\main.js:1:164461)
    at C:\projects\admin-safesante-front\dist\admin\main.js:1:164686
    at 23533 (C:\projects\admin-safesante-front\dist\admin\main.js:1:242774)
    at __webpack_require__ (C:\projects\admin-safesante-front\dist\admin\main.js:1:3315966)
    at C:\projects\admin-safesante-front\dist\admin\main.js:1:4130344
    at C:\projects\admin-safesante-front\dist\admin\main.js:1:4133949
    at Object.<anonymous> (C:\projects\admin-safesante-front\dist\admin\main.js:1:4134181)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1700.7
@angular-devkit/build-angular      17.0.7
@angular-devkit/core               17.0.7
@angular-devkit/schematics         17.0.7
@angular/cdk                       17.0.4
@angular/flex-layout               15.0.0-beta.42
@angular/material                  17.0.4
@angular/material-moment-adapter   17.0.4
@schematics/angular                17.0.7
rxjs                               7.8.1
typescript                         5.2.2
zone.js                            0.14.2
```

**Comment by alan-agius4** [comment]
jQuery is a DOM manipulation library which is not compatible with Hydration and SSR.

Any of its usages need to be done in the `afterRender` and `afterNextRender` hooks.

See the below
- https://angular.io/api/core/afterNextRender
- https://angular.io/api/core/afterRender
