### ISSUE TITLE
Sass features don't work within components using inlineStyle within a library (published

### ISSUE THREAD

**Issue by LcsGa** [angular/angular-cli#26712]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

- I have a components library within an Nx monorepo.
- I use scss for my styling and need to use `@use` for some responsive mixins (since css variables don't work within media queries).
- I'm in inlineStyles mode.

### Please provide the exception or error you saw

```true
I published my library on npm (on my company's registry) and now the inlineStyle doesnt work 😢

Within a demo app in my monorepo, it works fine but when I download my lib and do the same in a completely different project (with the same angular.json options well set too) it doesn't work anymore... I have to put my styles using `@use` within .scss files to make it work...
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Nx Monorepo:

Angular CLI: 17.0.5
Node: 18.18.2
Package Manager: npm 10.2.0
OS: win32 x64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.0.5
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
ng-packagr                      17.0.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

My app:

Angular CLI: 17.0.7
Node: 18.18.2
Package Manager: npm 10.2.0
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@schematics/angular             17.0.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else?

In my app I have set `inlineStyleLanguage` to `scss` + and I added `stylePreprocessorOptions` with `includePaths` pointing to the scss file where my mixins are to be sure it works as expected

**Comment by alan-agius4** [comment]
Can you please share your ng-packagr configuration?

**Comment by LcsGa** [comment]
Sure, here it is

```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/libs/components",
  "assets": ["./assets", "./styles"],
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```

**Comment by alan-agius4** [comment]
@LcsGa, it looks like `inlineStyleLanguage` is not configured in your library.

```diff
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
+ "inlineStyleLanguage": "scss",
  "dest": "../../dist/libs/components",
  "assets": ["./assets", "./styles"],
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```

**Comment by LcsGa** [comment]
Really... I didn't even know we could do that in ng-packagr 😅
Amazing, thank you verry much!!

**Comment by LcsGa** [comment]
Just one question though: Is it still necessary to set the app `inlineStyleLanguage` to `scss` too or did I miss antoher thing (apparently yes, I still need it)?

**Comment by alan-agius4** [comment]
The app level setting is still needed if your application has inline styles that are written in SCSS.

**Comment by LcsGa** [comment]
okay but I apparently also need it even for my libs styles to work fine, even if my app itself doesn't have any inline scss

**Comment by LcsGa** [comment]
(I have this behavior in my monorepo demo app though, I'll check if that's the same when it's published + dl within a completely different app)

**Comment by alan-agius4** [comment]
It looks like you might be consuming the “library” using path mappings to the Typescript source during development instead of the built version of the library.

This fundamentally causes the “library”, to be built as part of the application.

**Comment by LcsGa** [comment]
Okay, thanks! Didn't think about it!

I set up the `inlineStyleLanguage` as you said in my ng-package.json but it still doesn't work though 😕
- I tried with relative paths but it didn't work => I thought it was due to packaging into one folder before that caused a wrong path
- Then I tried by adding absolute path with `stylePreprocessorOptions` adding styles folder (where my mixins file is) to the `includePaths` => it still doesn't work as expected

### `ng-package.json` of my lib
```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/libs/components",
  "inlineStyleLanguage": "scss",
  "assets": ["./assets", "./styles"],
  "lib": {
    "entryFile": "src/index.ts"
  }
}
```

### angular.json of my external app
```json
...
"inlineStyleLanguage": "scss",
"stylePreprocessorOptions": {
  "includePaths": ["node_modules/@kw/components/styles"]
},
```

=> within my components I do `@use 'responsive'` with things like `@include responsive.mobile { ... }` and in styles I directely have a `_responsive.scss` file

**Comment by alan-agius4** [comment]
You also need to configure the scss includes for your library build. 

```
{
  "lib": {
    "styleIncludePaths": ["../node_modules/@kw/components/styles"]
  }
}
```

**Comment by LcsGa** [comment]
I'm really sorry but I might be missing something else and can't figure out what in the docs (that I didn't read carefully enough yet, I admit):

- is the path through my styles folder relative to the project itself? If yes, I did 
```json
"styleIncludePaths": "./styles"
```
- my components are all built as secondary entry points, which means they also have their own ng-package.json => should I also configure theme with that `styleIncludePaths` and `inlineStyleLanguage` or is it enough to declare it globally, for the whole library?

**Comment by alan-agius4** [comment]
The `styleIncludePaths` needs also be to provided in secondary entry-points. The value, is relative to the configuration file.

**Comment by LcsGa** [comment]
okay, so I:
- added `inlineStyleLanguage` + `styleIncludePaths` in every secondary entry points
- kept `styleInlncludePaths` for the main ng-package.json since I also need it for a global style thing
- removed `inlineStyleLanguage` from the main ng-package.json of my lib since I don't have anything in src

=> it still doesn't work 😕 Am I still missing another thing? (I'm really sorry 😅)

**Comment by LcsGa** [comment]
Here is one of my ng-package.json from a secondary entry point
```json
{
  "inlineStyleLanguage": "scss",
  "lib": {
    "entryFile": "src/index.ts",
    "styleIncludePaths": ["../styles"]
  }
}
```

Here is the main one
```json
{
  "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
  "dest": "../../dist/libs/components",
  "assets": ["./assets", "./styles"],
  "lib": {
    "entryFile": "src/index.ts",
    "styleIncludePaths": ["./styles"]
  }
}
```

**Comment by LcsGa** [comment]
![image](https://github.com/angular/angular-cli/assets/58547290/1e443c2d-9b7f-4415-866d-4b864674f2c2)
![image](https://github.com/angular/angular-cli/assets/58547290/fc1b9571-8ef0-40c5-b121-9b8b18cc7181)
The paths seem to be good

**Comment by alan-agius4** [comment]
@LcsGa, can you please provide a minimal reproduction?

**Comment by LcsGa** [comment]
Here it is: https://github.com/LcsGa/angular-sass-issue-26712-nx

But currently I have a more explicit issue where, in this repo, it directly tells that it can't find the stylesheet
![image](https://github.com/angular/angular-cli/assets/58547290/6b961560-4418-48f2-a5ed-2e62e585d3cc)

> When I build the lib itself, the build succeeds though

> When I replace `@use 'responsive'` with `@use '../styles/responsive'` it works fine ! But what's strange is that I don't meet that issue within the real project, whereas the configuration is exactly the same

**Comment by alan-agius4** [comment]
This seems to be a problem with `@nx/angular`, https://github.com/nrwl/nx/tree/master/packages/angular/src/executors/package/ng-packagr-adjustments. When NX custom logic from the executor is removed the compilation works as expected.

**Comment by alan-agius4** [comment]
You can also verify this by replacing the executor from `@nx/angular:package` to `@angular-devkit/build-angular:ng-packagr`.

**Comment by LcsGa** [comment]
Oh okay! I could definitely never find by myself 😅 Thank you very much!
Is this issue already known from Nx? Is there a fix incomming or can I simply use `@angular-devkit/build-angular:ng-packagr` or are there some unwanted side effects?

**Comment by LcsGa** [comment]
I tried to replace `@nx/angular:package` with `@angular-devkit/build-angular:ng-packagr` but I still have the exact same issue
![image](https://github.com/angular/angular-cli/assets/58547290/87f62d2e-ed77-4091-9db8-1440cd88ba3d)
> I reset nx + rebuilt the lib + served the app

**Comment by alan-agius4** [comment]
Looking at the error again it looks like the error appears to be coming from the application compilation. This is caused by the following path mappings which causes the library to be compiled as part of the application. 

```js
"paths": {
  "@org/components": ["libs/components/src/index.ts"],
  "@org/components/button": ["libs/components/button/src/index.ts"]
}
```

This should be changed to 
```js
"paths": {
  "@org/components": ["dist/libs/components"],
  "@org/components/button": [""dist/libs/components"]
}
```

**Comment by LcsGa** [comment]
Yeah, about the error that's what I thought to but what I felt strange is that I don't have it in the real app 🤔

About the `paths` change, if I do that, I face a new error
![image](https://github.com/angular/angular-cli/assets/58547290/cc42ae97-43d3-4cd0-b67e-6c94591fe895)

Thanks for your answer about the builder!

Okay, I wasn't sure if I had to include `inlineStyleLanguage` to the root `ng-package.json`, thanks !

**Comment by alan-agius4** [comment]
There are two options to fix that. 

Either update the paths to the following;
```
"paths": {
    "@org/components": [
      "dist/libs/components",
      "libs/components/src/index.ts"
    ],
    "@org/components/*": [
      "dist/libs/components/*",
      "libs/components/button/src/index.ts"
    ]
  }
```

Or revert the paths changes in the root level tsconfig and add them in the `tsconfig.app.json`

**Comment by LcsGa** [comment]
Thanks @alan-agius4 ! I'll try all of that as a temporary fix and opened an issue on Nx (if you wanna take a look at it/correct me)!
Just one question though, I understood your first example adding multiple paths into my `tsconfig.base.ts` which works great, but I didn't understand the other one, especially when you say to "revert the paths changes" => do you mean removing all of it or simply reverting it "normally", like this:
```json
"paths": {
    "@org/components": ["libs/components/src/index.ts"],
    "@org/components/button": ["libs/components/button/src/index.ts"]
  }
```

**Comment by LcsGa** [comment]
Also I just tried to replace `@nx/angular:package` with `@angular-devkit/build-angular:ng-packagr` but I can't make it work in my real project since I have another library that `components` depends on 😬 Is there another thing I'm missing?
![image](https://github.com/angular/angular-cli/assets/58547290/d9216766-e05f-4579-9983-4c4a475f39e2)
![image](https://github.com/angular/angular-cli/assets/58547290/5839e55a-f07a-4cbd-a603-b5fb8a578cbe)

**Comment by alan-agius4** [comment]
`@kw/components/tabs` is dependent on a `@kw/angular-extensions/rxjs` which is either not built yet or the path mappings are not pointing to the built version of the said library.

**Comment by LcsGa** [comment]
Thanks, I added multpile paths as you showed me before and it built !

Now that I could build it, I retried to see how it behaves in the app but my scss rules are still not working. I published a new branch on my miniaml reproduction [here](https://github.com/LcsGa/angular-sass-issue-26712-nx/tree/attempt-1) if you want to take a look at it

**Comment by alan-agius4** [comment]
`inlineStyleLanguage` is still missing in https://github.com/LcsGa/angular-sass-issue-26712-nx/blob/ce7aac634c348bc7515f50396031475df0c74429/libs/components/ng-package.json

**Comment by LcsGa** [comment]
Indeed, sorry... I did it in the real project but forgot to do it there too 😅 Thanks! Everything works well except that I lose the nx incremental build! Now i simply need to wait for an answer from nx!

**Comment by LcsGa** [comment]
> There are two options to fix that.
> 
> Either update the paths to the following;
> 
> ```
> "paths": {
>     "@org/components": [
>       "dist/libs/components",
>       "libs/components/src/index.ts"
>     ],
>     "@org/components/*": [
>       "dist/libs/components/*",
>       "libs/components/button/src/index.ts"
>     ]
>   }
> ```
> 
> Or revert the paths changes in the root level tsconfig and add them in the `tsconfig.app.json`

One last question if I may ask: how can I do the second option? I couldn't find a way to handle it and I'd prefer having one path per file

**Comment by alan-agius4** [comment]
Just add the path mappings in the `tsconfig.app.json` instead of `tsconfig.json`

**Comment by LcsGa** [comment]
But the one to the `dist` right? If yes then I can't find which file to point to => for example on the button => should I do something like:
```json
"paths": {
    "@org/components/button": ["dist/libs/components/button/???"]
}
```
I tried with the esm/fesm folders, on .mjs files but it didn't work and I don't see any other option

**Comment by alan-agius4** [comment]
For secondary entry-point you need to use the wildcard. See: https://github.com/angular/angular-cli/issues/26712#issuecomment-1866306384
