### ISSUE TITLE
`ng e2e` and `ng lint` have to hit Enter twice to go on

### ISSUE THREAD

**Issue by doggy8088** [angular/angular-cli#26724]
### Command

e2e

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Please watch the video I prepared. YouTube: https://youtu.be/OMq-22_fsgI

### Minimal Reproduction

```sh
ng new demo1 --ssr=false --style=css
ng e2e
```

### Your Environment

```text
Angular CLI: 17.0.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@schematics/angular             17.0.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

`ng lint` have the same issue as well. When seeing `Would you like to proceed?`, I have to hit Enter twice to proceed.

**Comment by alan-agius4** [comment]
Hi @doggy8088, I am unable to replicate this on both Linux and Windows. Can you try using a different command line tool? Worth mentioning that we do not have special logic for this sort of prompt and we use [Inquirer.js](https://github.com/SBoudrias/inquirer.js/) directly hence if there is a bug it's unlikely that it is actionable from our end.

**Comment by doggy8088** [comment]
I tried Command Prompt (cmd.exe). It's the same issue.

**Comment by doggy8088** [comment]
I just tried `@inquirer/prompts` in my cmd.exe or pwsh.exe. It works fine. Only `ng e2e` have this issue.

**Comment by alan-agius4** [comment]
@doggy8088, managed to replicate on Windows with `cmd.exe` and I have a fix in flight for this in  https://github.com/angular/angular-cli/pull/26725.
