### ISSUE TITLE
The v17 version has abandoned the parameter 'resources output path'. What is the alternative?

### ISSUE THREAD

**Issue by sailengsi** [angular/angular-cli#26748]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

The v17 version has abandoned the parameter 'resources output path'. What is the alternative?

### Minimal Reproduction

The v17 version has abandoned the parameter 'resources output path'. What is the alternative?

### Your Environment

```text
The v17 version has abandoned the parameter 'resources output path'. What is the alternative?
```

**Comment by JeanMeche** [comment]
#26675, the new application builder will accept `outputPath` customization in 17.1. You can already test this with `17.1.0-next.3`
