### ISSUE TITLE
Any ways to run component outside ssr angular 17

### ISSUE THREAD

**Issue by W014ara** [angular/angular-cli#26747]
### Command

new, serve, update

### Description

Is there a way to bypass SSR for individual pages. Previously, before version 17 of Angular, this could be done by specifying the following code:

`
server.get("/no-ssr", (req, res) => {
    res.sendFile(browserFolder + "/index.html");
});
`

How can this be done now?

**Comment by JeanMeche** [comment]
Hi, this is basically due to #26323 : The vite devserver doesn't use the express config.

**Comment by W014ara** [comment]
@JeanMeche 
This is not an answer to the question, what are the alternatives in this case?
It was previously possible to not render pages as SSR using the old approach as described.
What to do now?

**Comment by alan-agius4** [comment]
The above approach still works with Angular v17. Although it will not be applied when running `no serve`.

**Comment by W014ara** [comment]
@alan-agius4 
Hi, 

After I run the `ng build` command I have a directory called dist/{project_name}
inside which the `browser` and `server` are specified.

When I run express server with following code:

`
const express = require("express");
const path = require("path");
const app = express();

app.use(express.static(path.join(__dirname, "dist/{project_name}/browser")));

const port = 4000;

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`);
});

`
and open the page with a route where SSR should not work, the page will still be pre-rendered and absolutely all markup will still be visible in the “view page code” browser tab.

I try to add

`
app.get("/not-found", function (req, res) {
    res.sendFile(path.join(__dirname, "dist/{project-name}/browser", "index.html"));
});
`
But this code does not work for me and i dont know what should i do.
