### ISSUE TITLE
Unable to create a local build in Angular 17

### ISSUE THREAD

**Issue by brianreinhold** [angular/angular-cli#26743]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 16.*

### Description

In Angular 16 I could use 
`ng build --base-href HubView --omit-dev`
to create a build that would run locally; that is I could click on the built index.html file and it would run in the browser. 
I had to do some modifications in the index.html file to get it to work (delete the `<base href="/">` element and remove the `type="module"` attributes in the script element. In addition, as pointed out in issue #25791, I had to edit the `main.c36c93e7c9c8f569.js` file to change the path to the resources in the assets file to be consistent with that generated by the build.

However, in Angular 17, I am no longer able to build the file such that it runs locally without modification of the angular.json file.

Am I missing something?

### Minimal Reproduction

Create an Angular 17 project
run 
`ng build --base-href HubView --omit-dev`
and edit the index.html file as instructed above. 
Click on the generated file - it will not run

If I modify the angular.json file as follows
```
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/hub-view-v5-17",
            "index": "src/index.html",
            "main": "src/main.ts",
```
the above technique works. THe build is much slower.

### Exception or Error

```text
The build does not run.
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular: 17.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.0.0
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@angular/cdk                    17.0.4
@angular/cli                    17.0.0
@angular/material               17.0.4
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment]
I am sorry, but I'm having trouble to understand the issue you're describing. In addition `--omit-dev` isn't an Angular CLI option.

**Comment by brianreinhold** [comment]
@alan-agius4 I have to agree that I don't find the --omit-dev described in any of the help options for 'build' or anywhere else for that matter. About 8 months ago when I first started working with Angular I was trying to do what I am trying to do now.  I want to build my application and then in the **/dist** directory where the build is created, I want to be able to click on the `index.html` file and have the program run. No server required. I found an answer on StackOverflow, and that is where I got the
`ng build --base-href HubView --omit-dev` command line expression as well as a description of the additional modifications one needs to make to the generated `index.html` file. It worked. The command line gave no error and so I never questioned it and I still don't understand what it does. I will try it without the `--omit-dev` part and see if it still works. However, doing an `ng build` alone does not work - I am unable to modify the generated `index.html` file to create a locally runnable application.

The other problem I am having is that I do not know the proper name to describe what I am trying to do. I call it a 'local build' but that is a totally made up name. Nobody knows what I am talking about. Maybe the correct expression is to generate an index.html file that renders in a browser.

IN any case I found a solution but I do not know if it is a good one. When generating a new Angular 17 project, the `angular.json` file contains the following:
```
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist/hub-view-v5-17",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": [
              "zone.js",
              "src/polyfills.ts"
            ],
```
I need to change it back to
```
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/hub-view-v5-17",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": [
              "zone.js",
              "src/polyfills.ts"
            ],
```
I don't know the consequences of such changes, but doing so allows me to create a build that can render locally once again.

**Comment by alan-agius4** [comment]
Using `--omit-dev` should give an error since it is not a known options. 

```
$ ng build --base-href HubView --omit-dev
Error: Unknown argument: omit-dev
```

`@angular-devkit/build-angular:browser` uses the webpack based build system whilst `@angular-devkit/build-angular:application` is uses Esbuild and Vite. 

I am still not understanding what the problem is here, I suggest you provide a minimal reproduction. A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by brianreinhold** [comment]
Whow! That was a quick response. Either you're a real early bird like me or in Europe!
In any case, I tried without the `--omit-dev` and it still worked. But I do not get an error if I include it. Someone much smarter than me posted this solution so I did not question it since it did work.

Do you understand what I am trying to do?

If I revert my angular.json file to use the default Esbuild system and create a build using `$ ng build --base-href HubView` without the `--omit-dev`,  I get a build, but after I make the changes to the `index.html` file, I get the following errors in the console when trying to render the `index.html` file:
```
polyfills-S4BUSWH3.js:1 TypeError: Class constructor e cannot be invoked without 'new'
    at polyfills-S4BUSWH3.js:2:12703
    at r.<computed> (polyfills-S4BUSWH3.js:1:13514)
    at main-HR3W6HNC.js:26:81619
    at new c (polyfills-S4BUSWH3.js:2:2128)
    at main-HR3W6HNC.js:26:81399
main-HR3W6HNC.js:15 ERROR TypeError: Cannot convert undefined or null to object
    at getOwnPropertyDescriptors (<anonymous>)
    at nt (main-HR3W6HNC.js:1:537)
    at polyfills-S4BUSWH3.js:2:7135
    at main-HR3W6HNC.js:16:152117
    at v.invoke (polyfills-S4BUSWH3.js:1:6453)
    at h.run (polyfills-S4BUSWH3.js:1:1819)
    at n.runOutsideAngular (main-HR3W6HNC.js:15:66181)
    at new e (main-HR3W6HNC.js:16:152002)
    at e.ɵfac [as factory] (main-HR3W6HNC.js:16:153413)
    at wu.hydrate (main-HR3W6HNC.js:15:22920)
```
I do not understand these errors. But from what I understand given the documentation, it is better to use the Esbuild default system. I will try making just the default Angular project (without any changes) and see if it illustrates the issue (cant create a build that renders locally without reverting back to the webpack based build system).

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by brianreinhold** [comment]
Its's not clear I even know how to describe the problem. It is clear what I mean by 'local rendering' of the application?

**Comment by alan-agius4** [comment]
From what I understand by "local rendering" you mean that the application is runnable without a web-server.
