### ISSUE TITLE
Avoid "LF will be replaced by CRLF the next time Git touches it" warning on Windows

### ISSUE THREAD

**Issue by doggy8088** [angular/angular-cli#26764]
### Command

new

### Description

I know the `LF will be replaced by CRLF the next time Git touches it` is a `warning` message that can safely be ignored. Some Angular newbies might feel confused sometimes. Is it possible to avoid this message been shown to the user?

### Describe the solution you'd like

I think this could be configurable for default newline characters. It can be detected easily for user's `core.autocrlf` setting of Git. So it's possible that change the newline of all the generated text file from LF to CRLF when needed.

### Describe alternatives you've considered

Workaround 1: Avoid `git init` after `ng new` and do it by user itself

```sh
ng new demo1 --skip-git
cd demo1
git init -b main
git config --local core.autocrlf false
git add . && git commit -m "Initial commit"
```

Workaround 2: Change `core.autocrlf` setting of Git to `false`

```sh
git config --global core.autocrlf false
```

**Comment by slavede** [comment]
To be honest, this has become anoying time. Even though I am using windows as development environment, I don't want that CLI generates OS specific files since we all agreed to use LF line endings.
I believe this should be configurable in cli

**Comment by alan-agius4** [comment]
@slavede, this has been solved. Please update to the latest stable version.

**Comment by slavede** [comment]
Is there a way of telling angular cli generate command to use LF (even though I'm on Windows)?
