### ISSUE TITLE
window.eval() accessing a method within a component is not working in angular 17

### ISSUE THREAD

**Issue by lonemanotzi** [angular/angular-cli#26763]
### Command

run

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

in ng 16, I was able to access a method defined in a component with window.eval.
```
@component{
     ...
      template:'<button (click)="methodB()">click</button>'
}
export class A{
methodA(){
         alert('alert');
     }
methodB(){
            window.eval('this.methodA();');
     }
}
```
in ng17, this returns 'this.methodA is undefined'.  Same result with ESBuild or Webpack build.
ng17 app is converted to standalone (module less) app

***
Before everyone goes EVIL on eval:
the app uses a dynamic configurator to run business logic based on predefined values (eg: hide a textbox if the value from the dropdown is "true"). This configuration is stored in a database, component will retrieve it and then run the logic after blur event.
in methodB, current model is evaluated and run logics on this object. 

### Minimal Reproduction

create a new app
add a method with a call to window.eval referencing another method in the same component

### Exception or Error

```text
this.<methodname> is undefined
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.0
Node: 20.9.0
Package Manager: npm 10.1.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.0 (cli-only)
@angular-devkit/core         17.0.0 (cli-only)
@angular-devkit/schematics   17.0.0 (cli-only)
@schematics/angular          17.0.0 (cli-only)
```

**Comment by JoostK** [comment]
`window.eval(...)` is an indirect call which is evaluated in the global scope, not the local scope. A direct `eval` call should be used instead.

**Comment by lonemanotzi** [comment]
Thanks @JoostK , it worked with just eval().
Not sure why ng 16 and below worked with window.eval().
