### ISSUE TITLE
Live Reload Fails on HTML Files After Extended Development Time

### ISSUE THREAD

**Issue by nicetomytyuk** [angular/angular-cli#26778]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Live reload functionality ceases to work for HTML files after a period of development. Changes in HTML files are not reflected in real-time, requiring a manual trigger through saving `.ts` or `.scss` files to initiate a live reload.

### Minimal Reproduction

1. Run `ng serve` to start the development server.
2. Initially, live reload works as expected for HTML, TS, and SCSS files.
3. After some time, live reload stops responding to changes in HTML files.

### Exception or Error

```text
Live reload should consistently update the application view when HTML files are modified, without requiring changes in TS or SCSS files as a trigger.
```

### Your Environment

```text
Angular CLI: 17.0.7
Node: 18.14.0
Package Manager: npm 9.3.1
OS: win32 x64

Angular:

@angular-devkit/architect    0.1700.7 (cli-only)
@angular-devkit/core         17.0.7 (cli-only)
@angular-devkit/schematics   17.0.7 (cli-only)
@schematics/angular          17.0.7 (cli-only)
```

### Anything else relevant?

- The issue has been observed in various Angular versions.
- The problem temporarily resolves after restarting the server with `ng serve`, but reoccurs after prolonged development.

**Comment by alan-agius4** [comment]
Can you please check if this is solved in version 17.1.0 which is currently in prerelease. You can update by using the below command.

```
ng update @angular/cli@next
```

**Comment by nicetomytyuk** [comment]
@alan-agius4 Just tried, still having the same issue, I'd attach two gifs, in one I save the `.html` file where nothing happens, in the second I just save the `.ts` which triggers the live reload.

![ddc085c449f958c0e88e9e4a8a0f63d1](https://github.com/angular/angular-cli/assets/30237552/89806937-184a-442d-be1e-b0f82aef2317)

![e32738f2a611ad6727a687ca1f3f3338](https://github.com/angular/angular-cli/assets/30237552/c9c25b41-81e4-444e-b0db-7a59d7185430)

**Comment by alan-agius4** [comment]
@nicetomytyukk, and still this doesn't happen consistently right?

**Comment by nicetomytyuk** [comment]
@alan-agius4 exactly, the issue seems to occur after the CLI or the page has been in idle for a while, but those are just thoughts, btw by working on the same project on a Mac with the cli@17.0.1 that issue does not occurs, I'd try to use that cli version on my computer.

**Comment by nicetomytyuk** [comment]
@alan-agius4 I've tried to use the same version of **cli** that is used on the Mac, but I'm still facing the same issue, at this point I think that the issue could be releated to some computer configuration (?)

But it is still weird as it shouldn't work at all at this point...

**Comment by alan-agius4** [comment]
Unfortunately, I am unable to replicate this on Windows.

**Comment by nicetomytyuk** [comment]
@alan-agius4 I'm not 100% sure but I think I've resolve the issue:

First of all I'm using `nvm` so I've done a complete cleanup by uninstalling the `@angular/cli` from all the node versions, then I still had the issue that after uninstalling the CLI with `npm uninstall -g @angular/cli`, the `ng version` was still working and returning version 16.X.X of `@angular/cli`, to resolve that, I've delete the `ng` file from `npm` folder and run `npm cache clean --force`

After it I've just installed freshly the `@angular/cli` again.

**Comment by nicetomytyuk** [comment]
Okay just made some more tries and even with the solution above the live-rendering stops, it just worked for some more time yesterday.

**Comment by alan-agius4** [comment]
Hey @IgorMinar, I'm a bit puzzled by what's going on here and why the watcher stops detecting changes after a while. Just to clarify, based on the video, it seems the issue isn't with live-reloading itself but rather that the watcher isn't registering the changes. You can try to run the build with the `--verbose` flag to verify this.

We changed the underlying watching implementation from chokidar to watchpack between versions 17.0.x and 17.1.x which in your case does not seem to help.

Couple of things you could try
- Try to update Node.js
- Check if you are able to reproduce this on an `ng new` application.

**Comment by nicetomytyuk** [comment]
Hi @alan-agius4 , with `--verbose` I can confirm that the issue is with the watcher, as files like `.scss` and `.ts` are logged, while when the issue happens the `.html` are not even logged, I'd give a try to your suggestions and will come back here with a feedback.

**Comment by nicetomytyuk** [comment]
@alan-agius4 after further investigation, I've been able to resolve the issue by deleting the `node_modules` and `package-lock.json` in the project and running `npm i`, the same issue I had even in older project but not with newly generated by using `ng new`.
