### ISSUE TITLE
esbuild with proxy doesn't return Content-Language headers for OPTIONS request

### ISSUE THREAD

**Issue by mivanyna** [angular/angular-cli#26782]
### Which @angular/* package(s) are the source of the bug?

upgrade, Don't known / other

### Is this a regression?

Yes

### Description

I upgraded my project to Angular 17 and switched to `"builder": "@angular-devkit/build-angular:browser-esbuild"`. For local env I use proxy config to redirect requests to test env.

I receive all the data, except for `OPTIONS` request there is no `Content-Language` header in response.
It works on prev version(Angular 16 and `"builder": "@angular-devkit/build-angular:browser"`)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.0.7
Node: 21.5.0 (Unsupported)
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@schematics/angular             17.0.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2

```

### Anything else?

I switched to `"builder": "@angular-devkit/build-angular:browser-esbuild"`
With proxy for the local env
package.json:
```
{
...
"start": "ng serve --proxy-config config/proxy.conf.js --hmr --port 3000 --open=true",
...
}
```
My proxy config looks like this:
```
const PROXY_CONFIG = [
  {
    context: [
      "/api"
    ],
    target: "test env link",
    secure: true,
    changeOrigin: true,
  }
]

module.exports = PROXY_CONFIG;
```

**Comment by mivanyna** [comment]
Please let me know if you need something from me

**Comment by mivanyna** [comment]
This one is very critical for me as it blocks development of some parts of the app

**Comment by alan-agius4** [comment]
Hi @mivanyna, to speed up our investigation kindly provide a minimal reproduction.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
@mivanyna, following an offline convo with @clydin, he correctly pointed out that an `OPTIONS` response has no content and thus, what is the reason of having a `content-language` header in the first place?

**Comment by mivanyna** [comment]
@alan-agius4 I get localizations in the header so I can then fetch the data with GET for the locale

**Comment by mivanyna** [comment]
Hi there, were you able to reproduce the issue?

**Comment by ipranjic** [comment]
Hi @mivanyna, look at this issue: https://github.com/angular/angular-cli/issues/25337
I think you have the same problem - the array form of proxy configuration is not yet supported by Vite. Instead you should do it like this:

```
module.exports = {
  "api/": { 
      target: "test env link",
      secure: true,
      changeOrigin: true
    }
 }
```

**Comment by mivanyna** [comment]
Hi @ipranjic , I don't think it's the case as I get all other data(GET, POST, etc)

**Comment by mivanyna** [comment]
@alan-agius4 here is the [repo](https://github.com/mivanyna/repro-app).

What I noticed is that even if the backend server is not running I get the response for OPTIONS request, seems like the dev-server returns it.

**Comment by alan-agius4** [comment]
@mivanyna, I managed to find the root cause and will be opening a PR shortly.

**Comment by mivanyna** [comment]
Thanks @alan-agius4
