### ISSUE TITLE
Angular 17 compiler errors have zero-based column, but one-based column would be more expected

### ISSUE THREAD

**Issue by segrey** [angular/angular-cli#26783]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Since Angular 17, compilation errors have zero-based column while having one-based line.
It would be more natural to have both line and column one-based.

### Minimal Reproduction

1. Generate an example Angular 17 app
2. Make an intentional compilation error, e.g. change `src/app/app.component.html` to
```
<span>{{ title.foo }} app is running!</span>
```
3. Run `ng serve`. The error with zero-based column (15) will appear:
```
✘ [ERROR] NG9: Property 'foo' does not exist on type 'string'. [plugin angular-compiler]

    src/app/app.component.html:1:15:
      1 │ <span>{{ title.foo }} app is running!</span>
        ╵                ~~~
```

Previously, in Angular 16, columns in errors were one-based:
```
Error: src/app/app.component.html:1:16 - error TS2339: Property 'foo' does not exist on type 'string'.

1 <span>{{ title.foo }} app is running!</span>
                 ~~~
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.8
Node: 18.19.0
Package Manager: npm 10.2.3
OS: darwin arm64

Angular: 17.0.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.8
@angular-devkit/build-angular   17.0.8
@angular-devkit/core            17.0.8
@angular-devkit/schematics      17.0.8
@schematics/angular             17.0.8
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by segrey** [comment]
Seems like the problem is that the column received from typescript is not incremented, while the line is incremented:

https://github.com/angular/angular-cli/blob/5bf0a0797c368f343674861c4fbec711afcaf130/packages/angular_devkit/build_angular/src/tools/esbuild/angular/diagnostics.ts#L43

**Comment by alan-agius4** [comment]
This is working as expected. 

Esbuild expects columns to be zero based while line numbers are 1 based.

See: https://github.com/evanw/esbuild/blob/35c0d65b9d4f29a26176404d2890d1b499634e9f/pkg/api/api.go#L192-L193

Unless this is changed in esbuild,  changing the column to a one-base would cause would cause error messages to be formatted incorrectly.
