### ISSUE TITLE
Expose webpack dev-server config to allow for multiple projects

### ISSUE THREAD

**Issue by n614cd** [angular/angular-cli#26798]
### Command

serve

### Description

Like others (https://github.com/angular/angular-cli/issues/12181), we are utilizing the multi-project features of Angular to create smaller and more efficient SPAs.
The production reality is they are served within separate URI contexts on a web server. 
Currently in development we are required to run multiple servers on separate ports. This is inefficient, and introduces more variables compared to production.
Therefore, it would be beneficial to allow webpack to with each application project underneath its own URI context. 

### Describe the solution you'd like

New command to the CLI such as "serveAll" which launches a single web server, with URI context defined for each project.

### Describe alternatives you've considered

Two solutions so far. Spin up Apache web server, and configure (using a sledge hammer for a nail).
Create a script which spawns "ng build --project=name" for each project with a standalone dev project with just webpack-dev-server in it. The webpack.config.js contains hard coded static sections for each project.

**Comment by alan-agius4** [comment]
Hi @n614cd, thanks for your feature request however exposing webpack specific functionality/configuration is not the goal of the Angular CLI.

For this approach, it is recommended to use a custom builder.

**Comment by n614cd** [comment]
@alan-agius4 

Where did I say expose webpack functionality? That was the solution some others tried on the previous ticket.
My ask is not the same. I just want to have all projects spin up at once under a single web-pack-dev server, with each project under its own URI context. 
Current work arounds are to run each project on separate ports. This is not conducive to keeping development and production as similar as possible.

Tim
