### ISSUE TITLE
EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by robertolabarca** [angular/angular-cli#268]
E:\SourceCode\personal\angular> **ng new with-angular-cli-example01**   
installing ng2
  create .clang-format
  create config\environment.js
  create e2e\app.e2e.ts
  create e2e\app.po.ts
  create e2e\tsconfig.json
  create angular-cli-build.js
  create .gitignore
  create karma-test-shim.js
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create src\app\with-angular-cli-example01.html
  create src\app\with-angular-cli-example01.spec.ts
  create src\app\with-angular-cli-example01.ts
  create src\app.ts
  create src\favicon.ico
  create src\index.html
  create src\tsconfig.json
  create src\typings.d.ts
  create tslint.json
  create typings.json
Successfully initialized git.
EPERM: operation not permitted, rename 'e:\npm\npm-cache\commander\2.9.0\package\package.json.dcc0148a4a57657dea7f79be92fd907d' -> 'e:\npm\npm-cache\commander\2.9.0\package\package.json'
Error: EPERM: operation not permitted, rename 'e:\npm\npm-cache\commander\2.9.0\package\package.json.dcc0148a4a57657dea7f79be92fd907d' -> 'e:\npm\npm-cache\commander\2.9.0\package\package.json'
    at Error (native)

**Comment by filipesilva** [comment]
That sounds like a npm cache/sudo issue. Can you try running `npm cache clean` and trying again?

**Comment by hansl** [comment]
Since there was no answer on this, I'll close it as resolved. If you see the problem occur again please file another bug (or reopen this one).
