### ISSUE TITLE
Version issue when initializing a new project

### ISSUE THREAD

**Issue by dev-garcia** [angular/angular-cli#26808]
### Command

new

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.1

### Description

When creating a new project the angular core version is in version 17.0.0 and the 'ng update' command does not find new versions, in projects that have been updated from version 16.2.10, when using the 'ng update' command, it finds the latest versions of angular core normally.

"dependencies": {
    "@angular/animations": "^17.0.0",
    "@angular/common": "^17.0.0",
    "@angular/compiler": "^17.0.0",
    "@angular/core": "^17.0.0",
    "@angular/forms": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    "@angular/platform-server": "^17.0.0",
    "@angular/router": "^17.0.0",
    "@angular/ssr": "^17.0.9",
    "express": "^4.18.2",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.2"
  },

### Minimal Reproduction

ng new project

ng update

### Exception or Error

```text
"We analyzed your package.json and everything seems to be in order. Good work!"
```

### Your Environment

```text
17.0.9
```

**Comment by clydin** [comment]
The contents of the project's package.json show above is expected and intended.  The caret (`^`) instructs the package manager to install the most recent version of that major version. Installing `@angular/core@^17.0.0` will currently install version 17.0.8. You can use the `ng version` command to show the versions in use for the project.
