### ISSUE TITLE
npm WARN deprecated abab@2.0.6

### ISSUE THREAD

**Issue by rodchenkov** [angular/angular-cli#26804]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi, I'm getting warning: **npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead**

**@angular-devkit/build-angular** uses **source-map-loader@4.0.1** that has dependency on deprecated **abab** package.
I think that you can just update **source-map-loader** to latest (4.0.2) version as it already do not have dependency on **abab** package and warning will disappear.

Thank you!

### Minimal Reproduction

setup new project with latest angluar/cli and run npm ci

you will get this warning message
`npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead`

### Your Environment

```text
Angular CLI: 17.0.8
Node: 18.16.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1700.8 (cli-only)
@angular-devkit/core         17.0.8 (cli-only)
@angular-devkit/schematics   17.0.8 (cli-only)
@schematics/angular          17.0.8 (cli-only)
```

**Comment by alan-agius4** [comment]
This has already been addressed in https://github.com/angular/angular-cli/pull/26757 which will be included as in 17.1.0 that will be released as stable later this month.
