### ISSUE TITLE
feat: intergrate eslint by default

### ISSUE THREAD

**Issue by xunjianxiang** [angular/angular-cli#26829]
### Command

new

### Description

don't want to run the command manually
```shell
ng add @angular-eslint/schematics
``` 

### Describe the solution you'd like

```
# add eslint by default
# provide a flag `--no-eslint` to ignore it
ng new xxx --no-eslint
```
or

```shell
# provide a flag `--eslint` to add `@angular-eslint/schematics`
ng new xxx --eslint
``` 

both ways are acceptable

**Comment by alan-agius4** [comment]
Lets keep tracking this in https://github.com/angular/angular-cli/issues/22978
