### ISSUE TITLE
NG_DISABLE_VERSION_CHECK not working

### ISSUE THREAD

**Issue by Quentigus** [angular/angular-cli#26836]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Launching this command on Angular 8 application is throwing this error :

```
NG_DISABLE_VERSION_CHECK=1 npx --yes @angular/cli@8 update @angular/common@8 @angular/cli@8 --allow-dirty --force --verbose
```

throw this error :
```
The installed Angular CLI version is older than the latest stable version.
Installing a temporary version to perform the update.
Installing packages for tooling via npm.
Installed packages for tooling via npm.
Node.js version v16.19.0 detected.
The Angular CLI requires a minimum Node.js version of v18.13.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
```

@angular/cli@17.0.9 is ignoring `NG_DISABLE_VERSION_CHECK` flag inside `ng.js` binary file

### Minimal Reproduction

- Generation of Angular v7 application
- Execute `npx --yes @angular/cli@8 update @angular/cli@8 @angular/core@8`

### Exception or Error

```text
Node.js version v16.19.0 detected.
The Angular CLI requires a minimum Node.js version of v18.13.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
```

### Your Environment

```text
ng version throws this error ...


Node.js version v16.19.0 detected.
The Angular CLI requires a minimum Node.js version of v18.13.

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.
```
```


### Anything else relevant?

_No response_

**Comment by alan-agius4** [comment]
`NG_DISABLE_VERSION_CHECK` wasn't available in Angular versions before version 9. Support for Angular versions earlier than 15 has been discontinued. For more information, refer to: https://angular.io/guide/releases#actively-supported-versions

**Comment by Quentigus** [comment]
All previous versions automatically download lastest version (v17.0.9) and this version doesn't support the flag.
Node version testing is in the ng.js file.

How can I disable node version check on latest cli?

**Comment by alan-agius4** [comment]
`NG_DISABLE_VERSION_CHECK` can be used to disable the node.js check on the latest version (version 17), however the problem is that you are using Angular CLI version 7 in your project were this functionality was not available. 

What you can do is following; 

Disable the below check in `node_modules/angular/cli/commands/update-impl.js`
https://github.com/angular/angular-cli/blob/6fb6b558d1554ba4269b6bdb93745e68b12f3bc4/packages/angular/cli/commands/update-impl.ts#L44

and run the update using:
```
ng update @angular/common@8 @angular/cli@8 --allow-dirty --force --verbose
```

**Comment by Quentigus** [comment]
I've tested the migration with the flag and latest release (17.0.10).

The Node error is shown from this line :
https://github.com/angular/angular-cli/blob/17.0.10/packages/angular/cli/bin/ng.js#L60
