### ISSUE TITLE
Merge build files into single one file in Angular 17

### ISSUE THREAD

**Issue by W014ara** [angular/angular-cli#26832]
### Command

build

### Description

Hello, I apologize if this question is not entirely relevant to this place, but as for me, the ideological nature of this option would be nice

After the migration of Angular 17 to vite, I encountered a problem that it was not possible to merge all new files into one single file without changing the builder to the old one `@angular-devkit/build-angular:browser`

I have already encountered a similar problem before, but the methods described in this problem do not work at all
https://github.com/angular/angular-cli/issues/3288

Unfortunately, instead of using the new builder with vite, you have to switch to the old one @angular-devkit/build-angular:browser
In this case, I use the following script file to assemble all the files into one:

```
const fs = require("fs-extra");
const concat = require("concat");

const componentPath = "./dist/build/bundle.js";

(async function build() {
    const files = [
        "./dist/angular-app/main.js",
        "./dist/angular-app/polyfills.js"
    ].filter(x => fs.pathExistsSync(x));
    await fs.ensureFile(componentPath);
    await concat(files, componentPath);
})();
```

What steps can I take now to solve my problem?

### Describe the solution you'd like

It would be great to have a ng build with --single-file option or something similar

**Comment by JeanMeche** [comment]
Hi, have a look at #26478, this has already been discussed.
