### ISSUE TITLE
Add packageManager `bun` to angular.json schema

### ISSUE THREAD

**Issue by MickL** [angular/angular-cli#26837]
### Command

add, new

### Description

Currently accepted package managers:

```
"npm",
"cnpm",
"yarn",
"pnpm"
```

### Describe the solution you'd like

Add option `bun`. It is a fully npm-compatible package manager and 17x faster than pnpn and 33x fast than yarn.

**Comment by MickL** [comment]
Sorry but this voting makes no sense. No one is checking the Github issues for upvoting features. It is common sense to support a package manager that is 33x faster than yarn.

**Comment by spock123** [comment]
Doesn't angular already work with bun? Yes, not in the schema, but in practise.
