### ISSUE TITLE
Extra configuration possibilities for Native Module Federation with Angular 

### ISSUE THREAD

**Issue by petereijgermans11** [angular/angular-cli#26839]
### Command

config

### Description

Is it possible to implement the following feature in esbuild and in angular.json for 'Native Module Federation'?
At this moment I use Angular 17 with 'Webpack Module Federation' and I want to step over to 'Native Module Federation'.

In Angular with 'Webpack Module Federation' you have the configuration option in angular.json to define an extraWebpackConfig. Esbuild does not support such a configuration option.

Why do I need this option?
I want different configuration files for different tasks (e.g. build and serve, e2e).

### Describe the solution you'd like

It would be very useful for my installation for Native Module Federation in Angular 17 to have the configuration option: extraEsBuildConfig in angular.json
I want to use different configuration files for different tasks, such as: build and serve, e2e ect

**Comment by alan-agius4** [comment]
`extraWebpackConfig` option is not provided nor supported by the Angular. CLI. This option is provided by 3rd party builders that extends the Angular CLI which are not supported by the Angular team. 

Support for micro fronteds is being tracked here: 
https://github.com/angular/angular-cli/issues/17556
