### ISSUE TITLE
When can we config Plugin or custom config for `builder: application` or `builder: browser-esbuild`

### ISSUE THREAD

**Issue by xkx-dev** [angular/angular-cli#26849]
### Command

build

### Description

Currently, we can not config the customer esbuild plugin for builders application and builder: browser:esbuild.

I see we have confined the Plugin interface inside, but it didn't expose outside, any plan release this out ?
We are looking forward it, thanks to

**Comment by alan-agius4** [comment]
You'd need to use a custom or 3rd party builder to add additional plugins. The Angular CLI builders do not expose this functionality directly.
