### ISSUE TITLE
Support for other service-workers

### ISSUE THREAD

**Issue by OysteinAmundsen** [angular/angular-cli#26857]
### Command

serve

### Description

I want to leverage todays file-watch when using `ng serve`. I also want to use WorkBox and not angular-serviceworker. This conflicts, for in order to compile my WorkBox template and inject built files into it it requires a second build step to be performed after angular has done emitting files to the output directory. I managed to get something like this working using a custom webpack configuration, but with angular 17 we are moving away from webpack and over to esbuild, and this customization is no longer available. 

### Describe the solution you'd like

In the angular.json config, a `serviceWorker` is either missing or declared as a pointer to an angular-serviceworker json config. 
I haven't thought this fully through yet, but something like the following config would be nice:
```
"targets": {
  "build": {
    "options": {
      "serviceWorker": {
        "path": "./sw.ts",
        "builder": "./path/to/buildScript.js"
      }
    }
  }
}
```

### Describe alternatives you've considered

The alternative is to give up HMR and `ng serve` completely, build angular first, then build and injectManifest into service worker and then run the entire project through a local http-server. This greatly reduces productivity.

**Comment by alan-agius4** [comment]
Hi, this can be achieved by a custom esbuilder where you can add additional plugins and run post build tasks.

**Comment by OysteinAmundsen** [comment]
Could you please point me in the direction where how I can plug a custom esbuilder into the angular build process is documented?

**Comment by OysteinAmundsen** [comment]
As far as I understand it, the only way to add a custom esbuild plugin is through nx where they override your @angular-devkit/build-angular with their custom @nx/angular builder. Then you have access to a `plugin` property where you can point to an esbuild plugin. 
But plugging ekstra code into the build process introduces at least two different problems:

1. you cannot specify an additional file to include as module in the build output. If you override the build options and include an ekstra entryPoint, this will be bundled in a way that makes it impossible to run as standalone code. You have to call an additional esbuild process to build out your service-worker template and overwrite the built code into the build process onEnd.
2. In the `onEnd` hook, the builders result.outputFiles does not include all files nescessary to inject into the workbox manifest. Only javascript chunks are present, not html, css or assets. 

Code example of such a plugin is presented in the following stackoverflow issue: https://stackoverflow.com/questions/77887040/building-workbox-into-angular-using-custom-esbuilder

It would be nice if angular would consider a better support for plugins, and documentation for how a normal use-case like this could be implemented.
