### ISSUE TITLE
Allow i18n translation files to be split in smaller parts

### ISSUE THREAD

**Issue by spock123** [angular/angular-cli#26856]
### Which @angular/* package(s) are relevant/related to the feature request?

localize

### Description

When projects become large, i18n-translation files become untenably large.
We use the simpler json format translation files, but it also becomes very large, thousands of lines.

I would be nice if it somehow were possible to split translation files into smaller portions.

Cheers

### Proposed solution

Allow splitting i18n json or xml translation files

### Alternatives considered

None

**Comment by clydin** [comment]
Using multiple translation files per locale is currently supported.  The files can even be in different formats if needed. The `translation` i18n option can be either a string or an array of strings.

**Comment by alan-agius4** [comment]
Closing as per above.
