### ISSUE TITLE
Allow custom vite configuration & plugins

### ISSUE THREAD

**Issue by bastiW** [angular/angular-cli#26859]
### Description

The Vite ecosystem is awesome. It is not only a fast dev tool, but it also provides a rich ecosystem of build tools that can be used across different frameworks. 

### Proposed solution

It should be possible to 

- Modify default [Vite Configuration](https://vitejs.dev/config/)
- Use the rich [Vite Ecosystem](https://github.com/vitejs/awesome-vite)

### Alternatives considered

-

**Comment by alan-agius4** [comment]
Exposing vite configuration does not align with the Angular CLI design goals.

To add additional Vite plugins please use a custom builder.

**Comment by LukasKlement** [comment]
I created a feature request in the angular-builders repo: https://github.com/just-jeb/angular-builders/issues/1617
Just like with custom webpack configs, where angular-builders was the solution, we would ideally have the same for vite.
