### ISSUE TITLE
Pwa And Angular

### ISSUE THREAD

**Issue by AliSafa** [angular/angular-cli#26868]
### Command

help

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

hi

Pwa And Angular 17.0.10

### Minimal Reproduction

1) ng new angular-pwa-chace
2) cd angular-pwa-cache
3) ng add @angular/pwa
4) npm i -g http-server
5) ng build --c "production"
6) http-server -p 8080 -c-1 dist/angular-pwa-cache

### Exception or Error

```text
Problems
a)"GET /manifest.webmanifest" Error (404): "Not found"
b)No Service Workers found
c)PWA not chace resource
thanks
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.10
Node: 20.10.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.10
@angular-devkit/build-angular   17.0.10
@angular-devkit/core            17.0.10
@angular-devkit/schematics      17.0.10
@angular/cli                    17.0.10
@angular/ssr                    17.0.10
@schematics/angular             17.0.10
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else relevant?

![image](https://github.com/angular/angular-cli/assets/19464475/a418e1a7-6f3e-437d-a6f1-dd9d527ed5af)

![image](https://github.com/angular/angular-cli/assets/19464475/0139a58a-a853-4e30-ad7f-9a71e7f52aee)

![image](https://github.com/angular/angular-cli/assets/19464475/61b2edf7-5265-4fda-a77e-193eee6a3460)

![image](https://github.com/angular/angular-cli/assets/19464475/956b8464-699e-47eb-8be6-acea06606519)

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.

<img width="710" alt="Screenshot 2024-01-15 at 09 09 58" src="https://github.com/angular/angular-cli/assets/17563226/c6d75ecc-4704-4e53-ac6a-d549f0685c89">

Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by AliSafa** [comment]
https://github.com/AliSafa/AngularPwaChace.git

**Comment by AliSafa** [comment]
> I'm sorry, but we can't reproduce the problem following the instructions you provided.
> <img alt="Screenshot 2024-01-15 at 09 09 58" width="710" src="https://private-user-images.githubusercontent.com/17563226/296691731-c6d75ecc-4704-4e53-ac6a-d549f0685c89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTI5MzAsIm5iZiI6MTcwNTMxMjYzMCwicGF0aCI6Ii8xNzU2MzIyNi8yOTY2OTE3MzEtYzZkNzVlY2MtNDcwNC00ZTUzLWFjNmEtZDU0OWYwNjg1Yzg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA5NTcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3ZDJiMzVjY2UxODUzZjQ2NDRkMjE1ZDVhMGY4MDJlMzE2MThjODFjM2JlZTkzYzAyMjM2MTQxNDFiMDMxODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SrDLShrOCx6YjK43_6ouft5CUNnvzipDmqLRyMS0Ax4">
> 
> Can you setup a minimal repro please? You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
> 
> This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

https://github.com/AliSafa/AngularPwaChace.git

**Comment by alan-agius4** [comment]
@AliSafa, it looks like you forgot to push.

**Comment by alan-agius4** [comment]
@AliSafa, actually I think I spotted your problem the http-server is being spawning with the wrong path. 

```diff
+ http-server -p 8080 -c-1 dist/angular-pwa-cache/browser
- http-server -p 8080 -c-1 dist/angular-pwa-cache
```

**Comment by AliSafa** [comment]
> @AliSafa, actually I think I spotted your problem the `http-server` is being spawning with the wrong path.
> 
> ```diff
> + http-server -p 8080 -c-1 dist/angular-pwa-cache/browser
> - http-server -p 8080 -c-1 dist/angular-pwa-cache
> ```

Perfect Sir

I was confused for two days
