### ISSUE TITLE
Dynamic routes SSR is not generating

### ISSUE THREAD

**Issue by AHA-Technocrats** [angular/angular-cli#26865]
### Which @angular/* package(s) are the source of the bug?

platform-server, router

### Is this a regression?

Yes

### Description

Most of the websites preferred SSR , optimised and SEO right ? I am super duper excited in angular 17 for SSR but one thing today when I built and deployed on server then SSR are only working in static routes only . 

What I mean by that ? 
   - SSR working in static route
      - Example : /blogs
   - Not working in dynamic routes
      - Example : /blog/:slug
         - Here in locally when when accessing route like
           -  /blog/what-is-ssr   
           - /blog/dynamic-route-in-angular-v17  
                 Then SSR working but after **ng build** deploying **_dist/(browser) folder in server then after accessing route_** 
        -  /blog/what-is-ssr   
        - /blog/dynamic-route-in-angular-v17  
           then only getting content index.html content. 

Please fix this or if already it's done but I wrongly build and deployed then please guide me.

You can see my deployed project here and [https://alal.test.ahatech1.cloud/](https://alal.test.ahatech1.cloud/). 

Thank you

### Please provide a link to a minimal reproduction of the bug

https://alal.test.ahatech1.cloud/

### Please provide the exception or error you saw

```true
SSR not working in dynamic routes
```

### Please provide the environment you discovered this bug in (run `ng version`)

```

Angular CLI: 17.0.9
Node: 18.17.0
Package Manager: npm 9.6.7
OS: win32 x64

Angular: 17.0.8
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.9
@angular-devkit/build-angular   17.0.9
@angular-devkit/core            17.0.9
@angular-devkit/schematics      17.0.9
@angular/cli                    17.0.9
@angular/ssr                    17.0.9
@schematics/angular             17.0.9
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

**Comment by jnizet** [comment]
The CLI can't possibly guess the slugs of your blog articles. But you can provide them. Follow the documentation at https://angular.dev/guide/prerendering:

> You can prerender parameterized routes using the routesFile option. An example of a parameterized route is product/:id, where id is dynamically provided. To specify these routes, they should be listed in a text file, with each route on a separate line.

**Comment by alan-agius4** [comment]
Closing as per above. Kindly check https://angular.dev/guide/prerendering

**Comment by AHA-Technocrats** [comment]
ok. thanks a lot
