### ISSUE TITLE
Working with Stencil.js components requires extra setup

### ISSUE THREAD

**Issue by riker09** [angular/angular-cli#26878]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

As stated in issue #26345 setting up Angular 17 with Stencil.js components needs some extra configuration, which is anything but obvious. Also, the mentioned ticked was locked due to inactivity, but aside from a workaround no work seems to have been done to solve the issue.

### Minimal Reproduction

The reproduction repo is taken from the other repo: https://github.com/zerock54/Angular-17-esbuild-Stencil-ng-serve-issue

### Your Environment

```text
Angular CLI: 17.0.10
Node: 18.16.1
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.10
@angular-devkit/build-angular   17.0.10
@angular-devkit/core            17.0.10
@angular-devkit/schematics      17.0.10
@angular/cli                    17.0.10
@schematics/angular             17.0.10
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else relevant?

The workaround provided in the other issue _does_ work, but as mentioned by comment https://github.com/angular/angular-cli/issues/26345#issuecomment-1842761606 I had to disable the Angular cache.

**Comment by alan-agius4** [comment]
Hi @riker09, 

Adding the below config as mentioned in https://stenciljs.com/docs/config-extras#enableimportinjection does work even with cache enabled.

```js
  extras: {
    enableImportInjection: true,
  },
```

**Comment by alan-agius4** [comment]
If the problem is that the changes to the components is not reflected in the browser. This is expected and since you are using `npm link`, you need to specify the linked library in the tsconfig path mappings. This will cause the library to be bundled as part of the application and not handled by vite optimizer.

```
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
     ...
    "paths": {
      "test-compo/loader": ["./node_modules/test-compo/loader"]
    }
}
```

**Comment by riker09** [comment]
Clarification: I actually don't use Stencil myself. It's a closed-source third-party component library that uses Stencil.js itself.

**Comment by riker09** [comment]
I will take it up with the authors of the third-party library. Thanks for your quick reply!
