### ISSUE TITLE
Failed to load url

### ISSUE THREAD

**Issue by JeffreyArt1** [angular/angular-cli#26882]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

v16

### Description

I'm encountering an issue with [Partytown](https://partytown.builder.io/). Despite the package appearing to load successfully, the terminal outputs the following error message every time the server reloads:

```
Failed to load url /~partytown/partytown.js (resolved id: /~partytown/partytown.js). Does the file exist?
```

Here's the relevant setup in my `angular.json`:
```JSON
  "assets": [
    "src/favicon.ico",
    "src/assets",
    {
      "glob": "**/*",
      "input": "node_modules/@builder.io/partytown/lib",
      "output": "/~partytown"
    }
  ]
```

The peculiar aspect is that the package seems to load correctly. Console messages confirm the package's presence and activity. This discrepancy between the terminal error and the actual functionality is puzzling. I'm curious if this is a known issue or a misconfiguration on my end. Any insights or suggestions would be greatly appreciated.

### Minimal Reproduction

To reproduce:
- create a new project with the latest version of angular
   - Setup SSR (`ng add @angular/ssr`)
- Install and setup partytown
- run `ng serve`

### Exception or Error

```text
Failed to load url /~partytown/partytown.js (resolved id: /~partytown/partytown.js). Does the file exist?
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.10
Node: 20.9.0
Package Manager: npm 10.1.0
OS: darwin x64

Angular: 17.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.10
@angular-devkit/build-angular   17.0.10
@angular-devkit/core            17.0.10
@angular-devkit/schematics      17.0.10
@angular/cli                    17.0.10
@angular/ssr                    17.0.10
@schematics/angular             17.0.10
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
This has been solved in 17.1.0 which is currently in prerelease and will be released as stable later today.
