### ISSUE TITLE
ng serve, ng create, ... ends with just "Error", no details, no stack. Worked  fine, then just stopped.

### ISSUE THREAD

**Issue by ev45ive** [angular/angular-cli#2689]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
WIndows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.17
node: 6.5.0
os: win32 x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
No idea. Just stopped working  at some point. Maybe after creating controller and removig it manually and not using ng destroy, but I am not sure that is the case

### The log given by the failure.
> Normally this include a stack trace and some more information.
```
Error
```
sic!

### Mention any other details that might be useful.
Can I somehow debug it? See more verbose errors? Stacktrace? how? 

Thanks!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ev45ive** [comment]
OK. 
did git checkout HEAD~1
and it worked
went back with git checkout HEAD  to see what changed 
and now ng serve (and others) works without this "Error" even the code is exactely the same it was when it was making this Error. 

Anyway - It would be awsome it all cases of just "Error" was removed and always any details. or at least Stack Trace was given. Thanks. 

and thanks for angular-cli - its speeds up things a lot!!! :-)

**Comment by CodeJason** [comment]
I had this problem a while ago and it drove me nuts!!
Anyway, I figured out it was the styles and scripts array in the `angular-cli.json` file. I had the wrong path or missed a comma somewhere. 
Could be a different issue for you though. Like you said, the error message is less than helpful.

**Comment by rwillmer** [comment]
I got this error by using single-quotes rather than double-quotes in the angular-cli.json file.

**Comment by filipesilva** [comment]
Sorry, the error message for invalid `angular-cli.json` was bugged, resulting in these messages.

@RoopeHakulinen gracefully fixed it in https://github.com/angular/angular-cli/pull/2565, and it should be out next release.
