### ISSUE TITLE
Question:  Can CLI version beta 17 run beta 15 projects?

### ISSUE THREAD

**Issue by daBishMan** [angular/angular-cli#2690]
Hello,

First off thank you for all your hard work on this CLI, it is AWESOME.

I have an application that we used beta 15 to build.   My question, if I upgrade my CLI to beta 17, would that cause a problem to running my project.  

I understand that you can upgrade, but assuming I do not want to upgrade this project to the latest version, would this continue to run?

**Comment by JanStureNielsen** [comment]
@daBishMan -- the GitHub issue tracker is for project bugs and project feature requests as noted in CONTRIBUTING.md. For better support, consider creating a question on StackOverflow with all the details.

**Comment by filipesilva** [comment]
@JanStureNielsen this is a perfectly reasonable question, as it's not really explained in the README or anywhere else.

@daBishMan overall, you *should* be ok with having a more recente global CLI version together with an older, local one. There are exceptions to this, as sometimes we have change the infrastructure that hooks them up one to another, but the intent is that it should work.
