### ISSUE TITLE
@angular-devkit/build-angular depends on vulnerable version of vite

### ISSUE THREAD

**Issue by ojpbay** [angular/angular-cli#26916]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Running npm audit on an Angular 16 project with version 16.2.11 of @angular-devkit/build-angular reports a security vulnerability with vite.

vite  4.0.0 - 4.5.1
Severity: high
Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem - https://github.com/advisories/GHSA-c24v-8rfc-w8vw
fix available via `npm audit fix --force`
Will install @angular-devkit/build-angular@17.1.0, which is a breaking change
node_modules/@angular-devkit/build-angular/node_modules/vite
  @angular-devkit/build-angular  16.0.0-next.0 - 17.0.10
  Depends on vulnerable versions of vite
  node_modules/@angular-devkit/build-angular
  
An update is needed to use the patched version of vite - 4.5.2. The recent revision of @angular-devkit-build-angular (https://github.com/angular/angular-cli/commit/e0e011fc47f2383f9be0b432066c1438ddab7103) only moved this up to 4.5.1 which is still affected (see link below).

https://github.com/advisories/GHSA-c24v-8rfc-w8vw

### Minimal Reproduction

1. Create an angular v16 project with version 16.2.11 of @angular-devkit/build-angular.
2. Run npm audit.

### Your Environment

```text
Angular CLI: 16.2.11
Node: 18.18.2
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1602.11
@angular-devkit/build-angular      16.2.11
@angular-devkit/core               16.2.11
@angular-devkit/schematics         16.2.11
@angular/cdk                       16.2.13
@angular/cli                       16.2.11
@angular/flex-layout               15.0.0-beta.42
@angular/material                  16.2.13
@angular/material-moment-adapter   16.2.13
@schematics/angular                16.2.11
rxjs                               7.8.1
typescript                         4.9.5
zone.js                            0.13.3
```

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/angular-cli/pull/26919

**Comment by ojpbay** [comment]
@alan-agius4 many thanks for the speedy response. Do you have an idea when the fix will be released?
