### ISSUE TITLE
Rebuilding on 'ng serve'. Removed css-resource:src (build-angular:application) 

### ISSUE THREAD

**Issue by p3t3r5** [angular/angular-cli#26918]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

We have a large project that takes longer than a minute to start. We upgraded from version 16 to version 17.1.0 and switched to 'build-angular:application.' Every time we start, we get the message: 'Changes detected. Rebuilding...' and the entire project is  rebuilded, taking a long time again. In verbose mode, I see that all CSS images are in the "removed" array. They are displayed, but rebuilding on serve is frustrating.

### Minimal Reproduction

- generate new project (ng new, SCSS)
- apend new class to styles.scss
`.test-resource {
	display: inline-block;
	min-width: 3em;
	min-height: 3em;
    background-image: url(./assets/icon.png);
    background-size: contain;
	background-position: 50%;
	background-repeat: no-repeat;
}`
- add some icon.png to src/assets
- add new element to app.component.html
`<span class="test-resource"></span>`
- start app: ng serve --verbose
`Changes detected. Rebuilding...
{
  "added": [],
  "modified": [],
  "removed": [
    "...\\css-resource:src\\assets\\icon.png"
  ]
No output file changes.
`

### Your Environment

```text
Angular CLI: 17.1.0
Node: 18.17.1
Package Manager: npm 10.3.0
OS: win32 x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by p3t3r5** [comment]
Thank you for the quick fix :) We have many css resources (pictures/fonts) from other folders (thirdparty). I hope this path fixes them too.

`...\\css-resource:node_modules\\@fortawesome\\...
...\\css-resource:vendor\\flags\\svg\\...`

**Comment by alan-agius4** [comment]
@p3t3r5, yes the fix handles all those.
