### ISSUE TITLE
/node_modules/../...js not found in index.html

### ISSUE THREAD

**Issue by leandropjp** [angular/angular-cli#2691]
MacOSX El Capitan
angular-cli: 1.0.0-beta.17

I am trying to add some script after npm install material-design-lite --save, I already tried with different packages and got the same error 
`http://localhost:4200/node_modules/material-design-lite/material.min.js 404 (Not Found)`  

this is my index.html

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Angular 2</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
 
  
</head>
<body>
<base href="/">
  <app-root>Loading...</app-root>

  <script src="/node_modules/material-design-lite/material.min.js"></script>

</body>
</html>
```

 I tried to find any solution here or in the stackoverflow but nothing worked.

**Comment by grizzm0** [comment]
node_modules is outside of the src folder. It should be ../node_modules. Or even better, use the apps[0].scripts array in angular-cli.json. See [this answer](https://github.com/angular/angular-cli/issues/2662#issuecomment-253448448).

**Comment by filipesilva** [comment]
Heya @leandropjp, when using Angular-CLI it takes over `index.html`, so it's usually a bad idea to add things there manually. 

When you want to add anything that needs a script tag, follow this: https://github.com/angular/angular-cli#global-library-installation
When you want to install a npm package, follow this instead: https://github.com/angular/angular-cli#3rd-party-library-installation

**Comment by leandropjp** [comment]
thanks @grizzm0! This worked for me! I just imported this to use some components that does not exist in the angular2-mdl like the selectfield.

This is my first project using Angular2, so I was following some tutorials that insert the scripts and css in the index.html and I was found a lot of examples using SystemJS and not Webpack, so I come here to ask but now I am putting everything that I need in the angular-cli.json. Thanks.

**Comment by filipesilva** [comment]
@leandropjp yeah there are a lot of way of setting up your project and it's often confusing to switch between them. Different tutorials assume different things from the environment :/
