### ISSUE TITLE
esbuild not support the  inline scss style as webpack

### ISSUE THREAD

**Issue by xkx-dev** [angular/angular-cli#26927]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

In a component, when I define the style as inline style  , 
and run build , it will give expect new line error. 

```
const SPINNER_VERTICAL_OFFSET = '20px';
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styles: [`
    :host { 
      height: 100 %;
      width: 100 %;
      #splash-container {
        top: calc(50 % + ${SPINNER_VERTICAL_OFFSET});
      }
    }
    `]
})
export class AppComponent {
  title = 'xkx-ng-esbuild';
  name = "This is name";
}
```

![image](https://github.com/angular/angular-cli/assets/147232556/b3975214-3efc-4f6f-9f33-512248700d0a)

### Minimal Reproduction

using basic ng-cli to new a project, and change the app-component style with inline styles.
please refer description 

### Exception or Error

```text
X [ERROR] Expected newline.
  ╷
2 │     :host {
  │           ^
  ╵
  src\app\app.component.ts 2:11  root stylesheet [plugin angular-sass]
```

### Your Environment

```text
17 latest
```

**Comment by xkx-dev** [comment]
I didn't find the "angular-sass" plugin source code also, where should we find this plugin code repo ?

**Comment by alan-agius4** [comment]
The error is expected and correct in this case as the above is not valid SCSS.

Unfortunately the Sass compiler in this case does not provide a very helpful error, but that is not actionable from our end.

Below find the correct version.

```scss
:host { 
  height: 100%;
  width: 100%;
  #splash-container {
    top: calc(50% + ${SPINNER_VERTICAL_OFFSET});
  }
}
```

**Comment by xkx-dev** [comment]
Sorry， not paste correctly with the repro step.

The error is caused by using the '"inlineStyleLanguage": "sass",' not scss.

**Comment by alan-agius4** [comment]
The code you've provided is not valid SASS syntax. SASS relies on indentation rather than curly brackets. Refer to the SASS documentation: https://sass-lang.com/guide/#nesting
