### ISSUE TITLE
Global styles for angular libraries

### ISSUE THREAD

**Issue by everton-auth** [angular/angular-cli#26934]
### Command

config

### Description

Utilizing global styles in the Angular library packaged by ng-packgr at the moment is impossible or at least missing documentation.
It would be nice to have global styles as in normal angular applications so that developers won't need to import, e.g. bootstrap into each component separately.

### Describe the solution you'd like

When specifying styleIncludePaths in ng-package.json, there should be an option that resolves and inlines css for each component globally.

### Describe alternatives you've considered

Be able to create a global style file for the library.

**Comment by alan-agius4** [comment]
You can use assets for this, which is covered in https://angular.io/guide/creating-libraries#managing-assets-in-a-library.

However, if you are using UI frameworks it is discouraged to import them directly and instead they should be explicitly imported in the application `styles.css` to avoid having duplicate CSS which may be the result of duplicate imports to same stylesheet. Example when both a library and the application depends on `bootstrap`.
