### ISSUE TITLE
proxy ignore !**/mypath not working with build-angular:application builder

### ISSUE THREAD

**Issue by GreedyA1** [angular/angular-cli#26942]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

angular 16: build-angular:browser builder

### Description

build-angular:browser proxy config supported ways to ignore some paths with syntax !**/
just the changing of builder breaks this behavior.

diff in branches 
![image](https://github.com/angular/angular-cli/assets/18186211/bd4d4a03-1187-441e-90ec-411833f78624)

### Minimal Reproduction

https://github.com/GreedyA1/test16/tree/main - with application builder
* run node server/server.js
* run ng serve --proxy-config=proxy.conf.js
<img width="873" alt="image" src="https://github.com/angular/angular-cli/assets/18186211/4b6f49aa-8fbe-46c2-a642-2d364b239062">

* checkout for previous builder to branch: browser-builder
https://github.com/GreedyA1/test16/tree/browser-builder - branch with browser builder
* run node server/server.js
* run ng serve --proxy-config=proxy.conf.js
<img width="873" alt="image" src="https://github.com/angular/angular-cli/assets/18186211/473ace4c-17ab-4aa9-9117-3de6644120d9">

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.0
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
The above proxy syntax is webpack-dev-server specific and is not handled by the underlying proxy package that is used by Vite. 

You could use `bypass` which makes the proxy compatible with webpack-dev-server and vite.

```js
const PROXY_CONFIG = [
  {
      context: [
        '/api/**',
      ],
      target: 'http://localhost:3000',
      secure: false,
      changeOrigin: true,
      logLevel: 'debug',
      bypass: function(req, res) {
        if (req.originalUrl.includes('/api/shmaybe')) {
          return req.originalUrl;
        }
    },
  },
]

module.exports = PROXY_CONFIG
```

**Comment by GreedyA1** [comment]
looks like I'm getting different results depending on builders. 

<img width="1060" alt="image" src="https://github.com/angular/angular-cli/assets/18186211/4ff42a30-f908-48a9-a657-4b3b9deed9aa">
vs webpack
<img width="1037" alt="image" src="https://github.com/angular/angular-cli/assets/18186211/8abb59c1-f72d-4bc4-ba47-67c55b79733b">

**Comment by alan-agius4** [comment]
That is due to https://github.com/angular/angular-cli/issues/26917
