### ISSUE TITLE
export/import interface met "reflection_capabilities.js:84Uncaught TypeError: Cannot read property 'annotations' of undefined"

### ISSUE THREAD

**Issue by keryhu** [angular/angular-cli#2694]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

export en interface in " app/a/a.interface.ts"

```
export interface PersonalSetInfo{
  userId:string;
  name:string;
}
```

**and import in another component   "app/b/b.component"**

`import {PersonalSetInfo} from "relative path";`

then met err:

`reflection_capabilities.js:84Uncaught TypeError: Cannot read property 'annotations' of undefined`

### The log given by the failure.
> Normally this include a stack trace and some more information.

`reflection_capabilities.js:84Uncaught TypeError: Cannot read property 'annotations' of undefinedReflectionCapabilities.annotations @ reflection_capabilities.js:84Reflector.annotations @ reflector.js:102NgModuleResolver.resolve @ ng_module_resolver.js:24CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:197RuntimeCompiler._compileComponents @ runtime_compiler.js:130RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:68RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:59PlatformRef_._bootstrapModuleWithZone @ application_ref.js:302PlatformRef_.bootstrapModule @ application_ref.js:284(anonymous function) @ main.ts:12__webpack_require__ @ bootstrap 32b1926…:52(anonymous function) @ zone.js:1327__webpack_require__ @ bootstrap 32b1926…:52webpackJsonpCallback @ bootstrap 32b1926…:23(anonymous function) @ main.bundle.js:1`

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
What did you do with the interface inside the class?

**Comment by keryhu** [comment]
below the folder where the interface is located：

when i add:

`export * from './a.interface.ts';`

the err "**reflection_capabilities.js:84Uncaught TypeError: Cannot read property 'annotations' of undefined**" appears:---

**Comment by filipesilva** [comment]
That doesn't answer my question though. For that error to appear, you must be using it somewhere in a component. I need the exact code that you're using to reproduce this error.

**Comment by keryhu** [comment]
3 places  used:  (a bit messy, i just copy)


component A:

`@Input() personalSetInfo: PersonalSetInfo;`

 component B who's child component is component A :

```
private personalSetInfo: PersonalSetInfo;

ngOnInit(): void {
    this.personalSetInfo = this.route.snapshot.data['personalSet'];
  }
```

and the  route resolve service:

```
resolve(route: ActivatedRouteSnapshot): Observable<PersonalSetInfo>|any{
// a service to get the PersonalSetInfo type Object
}
```

**Comment by filipesilva** [comment]
This doesn't seem like a CLI problem really, it seems like a Angular 2 problem. If you open the issue on https://github.com/angular/angular or http://stackoverflow.com/ it's more likely you'll get an answer.
