### ISSUE TITLE
CSS wrong import order with layer

### ISSUE THREAD

**Issue by csisy-btw** [angular/angular-cli#26940]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

By default the order of css imports are defined by the order of the import statements (see issue #5312).

However, if the import statement contains a layer specification (like `@import 'somefile' layer(somlayer);`) it is treated as a css import and is moved to the top of the generated css file.

**Why is this a problem?**

The order of css layers can be pre-defined by declaring them without any styles: `@layer lay1, lay2, lay3;`
However, if a css import is moved to the top of the generated css file, the layer order will be somewhat ignored, see repro.

**Why not just change the import orders?**

We have a situation where one lib's stylesheet is already put in a layer, while another is not, and we want to put it in a layer as well. However, the order of these layers are important, so we must specify it beforehand which is not possible due to the current behaviour.

### Minimal Reproduction

Original styles.scss
```
// this defines the order of layers
@layer lib1, lib2;

// this imports the actual files into a given layer
// note the order of imports: lib2 first, lib1 second
@import 'lib2' layer(lib2);
@import 'lib1' layer(lib1);
```

The expected behaviour:
```
@layer lib1, lib2;
@layer lib2{
  // ... lib2 content
}
@layer lib1{
  // ... lib1 content
}
```

The actual behaviour:
```
@layer lib2{
  // ... lib2 content
}
@layer lib1{
  // ... lib1 content
}
@layer lib1, lib2;
```

Also see repo for complete repro: https://github.com/csisy-btw/css-layer-import-repro

### Your Environment

```text
Angular CLI: 17.1.0
Node: 18.18.0
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the [sass](https://github.com/sass/dart-sass/issues) project or file an issue on their issue tracker.

```
$npx sass src/styles.scss

@import 'lib2' layer(lib2);
@import 'lib1' layer(lib1);
@layer lib1, lib2;
```

**Comment by csisy-btw** [comment]
Oh, I see, sorry for the inappropriate bug report. Thanks for the fast reply.
