### ISSUE TITLE
angular2-cli gives @multi styles error

### ISSUE THREAD

**Issue by agatsoh** [angular/angular-cli#2695]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Ubuntu 14.04 LTS

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
krishna@Krishna:~/angular2_migrate/webui$ ng version
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.17
node: 4.4.3
os: linux x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
It was an app created using cli
I started using angular2-cli recently and created a new project. I wanted to use bootstrap in my project hence I installed bootstrap and then wanted to import the bootstrap css file like it is shown in the the angular2-cli guide here. https://github.com/angular/angular-cli#global-library-installation After running ng serve I get the following error.
### The log given by the failure.
> Normally this include a stack trace and some more information.

`ERROR in multi styles Module not found: Error: Can't resolve '/home/krishna/angular2_migrate/webui/node_modules/bootstrap/dist/css/bootstrap.min.css' in '/home/krishna/angular2_migrate/webui/node_modules/angular-cli/models' @ multi styles`

### Mention any other details that might be useful.
node -v 
4.4.3
npm -v 
3.10.6
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ciesielskico** [comment]
The error says it all, bootstrap cannot be found in node_modules. Do you have it installed?

**Comment by filipesilva** [comment]
^ what @ciesielskico said 💃
