### ISSUE TITLE
documentation does not match code : ng serve

### ISSUE THREAD

**Issue by rwillmer** [angular/angular-cli#2697]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

OSX El Capitan

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17
node: 4.5.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

$ ng --help

### The log given by the failure.
> Normally this include a stack trace and some more information.

The help command gives this inconsistent information.

ng serve <options...>
  --host (String) (Default: localhost) Listens on all interfaces by default

Either : 
a) the default is "0.0.0.0", in which case "Listens on all interfaces by default" is correct; or
b) the default is "localhost", in which case "Listens on all interfaces by default" is incorrect.

Trial and error leads me to believe that the default is "localhost".

This caused me to spend debugging time, trying to understand why my "ng serve" docker container was not working.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Would you be willing to submit a PR changing this? 

This is the line from which `ng help` derives the description: https://github.com/angular/angular-cli/blob/master/packages/angular-cli/commands/serve.ts#L44
