### ISSUE TITLE
Proxy Not working 

### ISSUE THREAD

**Issue by perumalsamyrajaveni1518** [angular/angular-cli#26986]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Angular 17 application builder proxy HTTP request return source file content (index.html).

<img width="1680" alt="Screenshot 2024-01-29 at 7 01 02 PM" src="https://github.com/angular/angular-cli/assets/127523713/74669b39-2485-4afd-b072-af3a04182aa8">

### Minimal Reproduction

[GitHub](https://github.com/perumalsamyrajaveni1518/v17.git)

### Your Environment

```text
Angular CLI: 17.1.1
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
The proxy config does not path the request.

The request is `/json/` and the proxy is `/api/*`
