### ISSUE TITLE
Vite dev-server HTTP2 support

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular-cli#26980]
### Command

serve

### Description

Would it be possible or in scope to support HTTP2 for Vite dev-server?

There is this issue here that states Vite itself won't, but from one comment, a plugin can be created to use http2-proxy.

Issue: https://github.com/vitejs/vite/issues/4184
Possible solution: https://gist.github.com/xfournet/068592b3d1ddd488427b874b23f707bf

**Comment by alan-agius4** [comment]
Hi @muuvmuuv, 

HTTP2 does work unless the proxy option is enabled, which is the same with webpack-dev-server.  Using the mentioned package and plugin is not really an option as the it does not provide most of features that `node-http-proxy` supports.

Overall, this seems to be more of an issue that needs to be handled upstream.

**Comment by muuvmuuv** [comment]
OK, but it is quite common to use the proxy setting. But yes, would be more a task on Vite end. Just found that maintained fork here: https://github.com/unjs/httpxy
Just in case.
