### ISSUE TITLE
Code coverage with Cypress and Angular Esbuild

### ISSUE THREAD

**Issue by mpontreau** [angular/angular-cli#26984]
### Command

e2e

### Description

Hello,

We are trying currently trying to migrate our applications to the new esbuild.

The last issue we are facing is that it seems to have no solution to keep code coverage and esbuild for Cypress tests.
All solutions (for example this one https://lukas-klement.medium.com/implementing-code-coverage-with-angular-and-cypress-6ed08ed7e617) are using a custom webPack configuration which is no more allowed.

Did someone already faced this issue and found a solution ?

### Describe the solution you'd like

A way to keep code coverage with Cypress and esbuild.

### Describe alternatives you've considered

For now we are keeping the old Angular builder.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
