### ISSUE TITLE
indexHtmlTransformer for esbuild should be available in both application and browser-esbuild builders

### ISSUE THREAD

**Issue by wszydlak** [angular/angular-cli#26997]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Currently only `browser` and `application` builder allow for index.html post transform. For `application` builder it has been added here: #26667

This option should also be added to browser-esbuild builder.

### Minimal Reproduction

---

### Your Environment

```text
---
```

**Comment by alan-agius4** [comment]
The `browser-esbuild` is a compatibility builder, to avail from the latest features please use to the `application` builder.
