### ISSUE TITLE
Proxy Issues with @angular-devkit/build-angular:browser-esbuild on Angular 17

### ISSUE THREAD

**Issue by achraf-elk** [angular/angular-cli#26996]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.0

### Description

After updating an Angular application to version 17 and switching the build system from webpack (@angular-devkit/build-angular:browser) to esbuild (@angular-devkit/build-angular:browser-esbuild), the application fails to make successful API calls throught corporate proxy, that were previously working. The same setup continues to work without issues when reverted back to the webpack builder

### Minimal Reproduction

**Steps to Reproduce**

1.Update an existing Angular project to version 17.
2.Change the build architect in angular.json to use "builder": "@angular-devkit/build-angular:browser-esbuild".
2.Run ng serve --proxy-config proxy.conf.js 
3.Observe that API calls that go through the Angular proxy setup fail to reach the backend.

**Expected Behavior**
The application should be able to make API calls through the Angular proxy setup using esbuild, similar to how it functions with the webpack builder.

**Actual Behavior**
The application fails to communicate with the backend when using the esbuild builder, with API calls returning parsing errors indicating that the requests are not reaching the backend.

**Additional Information**

proxy conf: 
```
const { HttpsProxyAgent } = require('https-proxy-agent');
const proxyConfig = [
  {
    context: '/api',
    target: "corporate-target',
    secure: false,
    changeOrigin: true,
  },
];

function setupForCorporateProxy(proxyConfig) {
  const proxyServer = process.env.http_proxy || process.env.HTTP_PROXY;
  if (proxyServer) {
    const agent = new HttpsProxyAgent(proxyServer);
    console.log('Using corporate proxy server: ' + proxyServer);
    proxyConfig.forEach(function (entry) {
      entry.agent = agent;
    });
  }
  return proxyConfig;
}

module.exports = setupForCorporateProxy(proxyConfig);

```

The proxy setup is confirmed to be correct and works as expected with the webpack builder.
No errors are logged in the console that provide insight into why the esbuild build process might be failing

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.1
Node: 18.19.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by giuseppebrb** [comment]
I had the same problem with proxy after migrating from v16 to v17.
Finally I solved by changing my proxy file (in my case `proxy.config.json`) from
```
{
  "/api/*": {
    "changeOrigin": true,
    "headers": {
      "Connection": "keep-alive"
    },
    "logLevel": "info",
    "secure": false,
    "target": "https://<insert-your-target-here>"
  }
}
```
to

```
{
  "/api": {
    "changeOrigin": true,
    "headers": {
      "Connection": "keep-alive"
    },
    "logLevel": "info",
    "secure": false,
    "target": "https://<insert-your-target-here>"
  }
}

```
basically by removing the wildcard '*'

**Comment by achraf-elk** [comment]
@giuseppebrb l already had "/api", for now I just brought back the old builder

**Comment by alan-agius4** [comment]
Unfortunately, without a reproduction, investigating this issue won't be possible.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
