### ISSUE TITLE
can't install @angular/cli@17

### ISSUE THREAD

**Issue by htrex** [angular/angular-cli#26994]
### Command

version

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### Description

I'm trying to install v17 but npm installs v16 even when specifying the required version.
I've even tried to clean npm cache but it didn't solve, I'm not sure what's the problem and what to check, I'm using Angular from version 2 and never had this issue until now.

### Minimal Reproduction

npm remove -g @angular/cli
npm cache clean --force
npm i -g @angular/cli@17.1.1

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.10
Node: 20.11.0 (Unsupported)
Package Manager: npm 10.4.0
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1602.10 (cli-only)
@angular-devkit/core         16.2.10 (cli-only)
@angular-devkit/schematics   16.2.10 (cli-only)
@schematics/angular          16.2.10 (cli-only)
    
Warning: The current version of Node (20.11.0) is not supported by Angular.
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by htrex** [comment]
@alan-agius4 after a further check it seems that the globally installed angular-cli which issuing an ng version command reports itself as 16.2.10 generates a v17 project.
