### ISSUE TITLE
Unable to watch linked libraries when cache is enabled using the `application` builder

### ISSUE THREAD

**Issue by Carlosamouco** [angular/angular-cli#27001]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When running the `ng serve` command using the `application` builder and having cache enabled, the watcher and the builder do not work properly for linked libraries.

I tried what was suggested in https://github.com/angular/angular-cli/issues/26585#issuecomment-1840982411 and the watcher starts to picking up changes but only if that library is referenced directly and exclusivly in the application code. If the library that we are trying to rebuild is being imported indirectly through another library in the application, it does not work.

For example:
Having library A and library B where A depends on B.
If in the app.component.ts I only import A, changes in B are not picked up.
If I import both libraries at the same time at the app level, the code from library B ends up in the same chunk of the library A and also in the main chunk, and I start getting warnings referring the code [NG0912 ](https://angular.io/errors/NG0912) in the console.

Without cache enabled everything works fine.

### Minimal Reproduction

Setup the environment:
```bash
ng new my-workspace
ng new my-app

cd ./my-workspace
ng generate library lib-a
ng generate library lib-b
```

Edit `lib-a.service.ts` to depend on library B:
```ts
import { Injectable, } from '@angular/core';

import { LibBService } from 'lib-b';

@Injectable({
  providedIn: 'root'
})
export class LibAService {
  constructor(public libBService: LibBService) { }
}
```

In two different terminals run each command:
```bash
ng build lib-a --watch
ng build lib-b --watch
```
Install the libraries in the my-app:
```bash
npm install ../my-workspace/dist/lib-a
npm install ../my-workspace/dist/lib-b
```

Go to my-app and edit the `app.component.ts`:
```ts
import { Component, inject } from '@angular/core';
import { RouterOutlet } from '@angular/router';

import { LibAService } from 'lib-a';
import { LibBService } from 'lib-b';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.less'
})
export class AppComponent {
  title = 'my-app';

  libA = inject(LibAService);
  libB = inject(LibBService);
}
```

Edit the `tsconfig.json`:
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "paths": {
      "my-lib": [
        "./node_modules/my-lib"
      ],
      "my-lib2": [
        "./node_modules/my-lib2"
      ]
    },
....
```

Serve the app
```bash
ng serve
```

Issue 1:
In the console the error [NG0912 ](https://angular.io/errors/NG0912) appears.

Go to my-app and edit the `app.component.ts`:
```ts
import { Component, inject } from '@angular/core';
import { RouterOutlet } from '@angular/router';

import { LibAService } from 'lib-a';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.less'
})
export class AppComponent {
  title = 'my-app';

  libA = inject(LibAService);
}
```
Perform any change in the `my-lib-b.service`

Issue 2:
App is not recompiled.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.1
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     

Package                         Version
---------------------------------------------------------  
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
I am unable to replicate the reported problem with the steps provided.

[cast (2).webm](https://github.com/angular/angular-cli/assets/17563226/24f9949a-f645-4795-a53d-b5aba318f863)

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Carlosamouco** [comment]
Sorry, I forgot to mention that I had configured `preserveSymbLinks: true` in angular.json under the builder configuration.

Without setting that config, and adding the workaround mentioned in https://github.com/angular/angular-cli/issues/26585#issuecomment-1840982411, It works as you could see.

So to summarize the problem, to make linked libraries work either I have to:
* cache=off && preserveSymbLinks=true ✔️
* cache=on && tsconfig.json paths ✔️

But it does not work with:
* cache=on && preserveSymbLinks=true (with or without tsconfig.json paths) ❌

I have created a repro for a quick way to set everything up if needed
https://github.com/Carlosamouco/repro-linked-libs

**Comment by Carlosamouco** [comment]
Just on another note, the error that I mentioned can be reproduced with the repro above:
![image](https://github.com/angular/angular-cli/assets/9380964/a3f046e3-4035-4904-bcb7-156065c6f9a6)

But I think this is the side effect of having both tsconfig paths and preserveSymbLinks=true that causes the library to be referenced differently at the app and dependency level.

**Comment by Carlosamouco** [comment]
I also would like to add that the following:
* cache=on, tsconfig.json paths and preserveSymbLinks turned off

Is only fine if the libraries have no other external dependencies since those don't get resolver in build time properly when they are symb linked.

**Comment by pawelszatan** [comment]
Here is simple repro: https://github.com/hasano1990/esbuild

**Comment by Carlosamouco** [comment]
The commit [b59f663e5](https://github.com/angular/angular-cli/commit/b59f663e5715e009b05bf560637c1bca3b112784) added the option to define external dependencies that should not be pre bundle aka treated as source code. I think we can close this issue now?

One question remains in my mind, If I am linking a library that as other dependencies, I have to mark also those dependencies and the dependencies of those dependencies as external right?
