### ISSUE TITLE
ng test --no-browsers doesn't work unless we open a browser

### ISSUE THREAD

**Issue by alcfeoh** [angular/angular-cli#27008]
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I run the command `ng test --no-browsers`, it says:  "No captured browser, open http://localhost:9876/" as illustrated here - and no tests run as a result, unless we click on the link to open a browser, which defeats the purpose of that command:
![image](https://github.com/angular/angular-cli/assets/4699771/006402f7-803f-4f89-b4d0-2fa13cbfac1a)

This command ran right after creating a brand new project with Angular CLI 17.1.1:
![image](https://github.com/angular/angular-cli/assets/4699771/6f7601e2-f302-44ef-9807-aed35f5eeada)

### Minimal Reproduction

Install Angular CLI 17.1.1: `npm i @angular/cli@latest -g`
`ng new testproj`
`cd testproj`
`ng test --no-browsers`

### Your Environment

```text
Angular CLI: 17.1.1
Node: 18.17.1
Package Manager: npm 10.2.5
OS: win32 x64

Angular: 17.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.1.1
@angular-devkit/schematics      17.1.1
@schematics/angular             17.1.1
rxjs                            7.8.1
typescript                      5.3.3
```

**Comment by alan-agius4** [comment]
This is expected as this is how karma handles the no browser option

**Comment by alan-agius4** [comment]
Th

**Comment by alcfeoh** [comment]
So the option is pretty much pointless with Karma then? Perhaps the option should have a different name then, or give a warning when used with Karma, because everyone is going to think that this option doesn't work.

**Comment by alan-agius4** [comment]
Using `—no-browser` in Karma CLI and Angular CLI have the same behaviour.

Karma always requires a browser to run tests and whilst for your case it might be pointless it is not for other users as features was also added based on a number of requests from users asking for this option with the Karma behaviour to be available.

**Comment by consman** [comment]
😢
