### ISSUE TITLE
interactive key shortcuts

### ISSUE THREAD

**Issue by janmaliska** [angular/angular-cli#27015]
### Command

serve

### Description

hi, is it possible to disable this "interactive key shortcuts" console availability? Because, I cannot debug the code with source map, the mentioned console block the VSC to open Chrome with opened source map. Once I use 'q' shortcut in console, console is closed, then VSC opens the chrome, but it is already stopped the server... 

### Describe the solution you'd like

I prefer to have an argument with "ng serve" command, to disable the new functionality "interactive key shortcuts console": 
  Shortcuts
  press r + enter to force reload browser
  press u + enter to show server url     
  press o + enter to open in browser     
  press c + enter to clear console       
  press q + enter to quit

### Describe alternatives you've considered

alternative should by, not to block the chrome with source map opened,

**Comment by janmaliska** [comment]
Hi @alan-agius4, in older CLI versions, when the "interactive key shortcuts console" did not exist, the debugging worked well.
To debug I use Visual Studio Code -Run and Debug. I can provide you the launch.json and package.json in attachment which I use to run and debug the project. Once the "Run LKQ-cross" task is launched, it build and run the projec, when the console did not exist, it opened Chrome with opened source map immediately. Now it opens the chrome with source map, after the console is closed by commad 'q', but i also stop the server. 

Here you are the error:  _Could not read source map for chrome-error://chromewebdata/: Unexpected 503 response from chrome-error://chromewebdata/neterror.rollup.js.map: Unsupported protocol "chrome-error:"_

[launch.json](https://github.com/angular/angular-cli/files/14123423/launch.json)
[package.json](https://github.com/angular/angular-cli/files/14123401/package.json)

Here you are Steps by Steps screenshots:
![Step-1](https://github.com/angular/angular-cli/assets/57900212/815d0719-21f7-4f62-9b1a-c706c18d51b5)
![Step-2](https://github.com/angular/angular-cli/assets/57900212/5e7b7a61-0614-4a33-93d1-e8d691287b3e)
![Step-3](https://github.com/angular/angular-cli/assets/57900212/df4b1598-2208-4c53-a296-6501856b28c1)

**Comment by alan-agius4** [comment]
Thanks for the steps.

Unless I am missing something sourcemaps are resolved and loaded automatically in VSCode. I am not understanding what `Q+ENTER` in vscode does, as I am unable to find this keybinding in VSCode keyboard shortcuts, in fact VSCode does not have any keyboard shortcuts in the format of `ALPHANUMERIC CHARACTER + ENTER`.

**Comment by janmaliska** [comment]
Q+Enter is the command for the new functionality called "interactive key shortcuts console"

![image](https://github.com/angular/angular-cli/assets/57900212/69df3263-68a5-4244-a889-e3a99908369c)

**Comment by alan-agius4** [comment]
My question is why are you pressing `Q+ENTER` to quit the server when your intention is to debug the application? By doing so, you are intentionally shutting down the server which obviously will cause the debugger to fail.

**Comment by janmaliska** [comment]
Until I press Q+ENTER the code is not debugged, because the shortcut console is blocking the debugging by VSC, but as you wrote it stop the server and that is the issue. May I launch it without the "shortcut console"? Or may I close it without killing the server?

**Comment by janmaliska** [comment]
@alan-agius4 I found work-around, 

1. I have to execute server manually by "ng serve"
2. then I can join the VSC debugger by launching the task

In past, once the "shortcut console" was not implemented yet, it was able to launch the debugging by one step, with configuration attribute "preLaunchTask": "npm: start",

You can close this issue, thank you for your time!

**Comment by alan-agius4** [comment]
I am closing as it appears that a workaround was found. That being said, I do not replicate the above mentioned issue.

[vscode debug](https://github.com/angular/angular-cli/assets/17563226/ee2b5661-f53f-4e9d-ab6f-333bde790d8d)
