### ISSUE TITLE
Incorrect case-sensitivity in `ng generate` CLI console/info output

### ISSUE THREAD

**Issue by bastibense** [angular/angular-cli#27016]
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

While creating a new component with the command

     ng generate component Admin/Accounts

it'll output:

```
CREATE src/app/Admin/accounts/accounts.component.scss (0 bytes)
CREATE src/app/Admin/accounts/accounts.component.html (23 bytes)
CREATE src/app/Admin/accounts/accounts.component.spec.ts (610 bytes)
CREATE src/app/Admin/accounts/accounts.component.ts (243 bytes)
```

Apparently it will print out the `Admin` part of the path while generating the module, however the resulting files are correctly created lower-case at `src/app/admin/...`.

Probably just a missing lowercase-conversion in the CLI output.

### Minimal Reproduction

In an empty project, create two components.

    $ ng generate component FirstCompo

    $ ng generate component FirstCompo/SecondCompo

### Exception or Error

```text
The output should correctly print the created path with the correct case.
```

### Your Environment

```text
Clean docker node environment.
```

**Comment by alan-agius4** [comment]
The problem why the second portion containing the component name is lower cased is because in the template directory path we use `@dasherize` (Ex https://github.com/angular/angular-cli/tree/main/packages/schematics/angular/pipe/files/) I guess the original intention was to  have the directory named exactly the same as the component files.

That being said, the logs do match the generated file paths.

```
$ ng generate component FirstCompo/SecondCompo
CREATE src/app/FirstCompo/second-compo/second-compo.component.css (0 bytes)
CREATE src/app/FirstCompo/second-compo/second-compo.component.html (27 bytes)
CREATE src/app/FirstCompo/second-compo/second-compo.component.spec.ts (632 bytes)
CREATE src/app/FirstCompo/second-compo/second-compo.component.ts (257 bytes)
```

```
$ tree src/app
src/app
├── FirstCompo
│   └── second-compo
│       ├── second-compo.component.css
│       ├── second-compo.component.html
│       ├── second-compo.component.spec.ts
│       └── second-compo.component.ts
├── app.component.css
├── app.component.html
├── app.component.spec.ts
├── app.config.ts
└── app.routes.ts
```

Can you please provide the output of `ng version`?

**Comment by alan-agius4** [comment]
Following the style guide, it is recommended that the directory name aligns with the component file name. Given this guideline, determining a definitive "correct" answer might be subjective. In this context, I would opt to maintain the current behavior to avoid breaking changes. Reassessment can be considered in the future, especially during updates to the style guide.
