### ISSUE TITLE
Support for custom webpack configurations

### ISSUE THREAD

**Issue by DavidGoethCplace** [angular/angular-cli#27028]
### Command

I don't know which commands are affected

### Description

My company uses webpack module federation (by WebpackModuleFederation plugin) for a step-by-step migration from angular-js to latest angular version.
The problem we face is that a development build is not working due to the 'ngDevMode is not defined' problem as it is already reported here: [https://github.com/angular/angular-cli/issues/25830](https://github.com/angular/angular-cli/issues/25830)

We can workaround this by defining the ngDevMode manually:

```javascript
config.plugins.push(
new webpack.DefinePlugin({
      ngDevMode: config.mode === 'development'
}));
```

But that is an angular internal. 
I would appreciate it if the `AngularWebpackPlugin` would handle that directly.

### Describe the solution you'd like

A **rudimentary** custom webpack configuration support. So that at least simple custom webpack configurations are supported.

**Comment by alan-agius4** [comment]
By design, custom webpack configurations are not supported. Employing such custom configurations directs you towards an undesirable path.

**Comment by DavidGoethCplace** [comment]
@alan-agius4 : If it is done by design what would be your suggestion? How you would you solve the initial problem of module federation? As far as I know this is not possible without a custom webpack configuration.

**Comment by alan-agius4** [comment]
The tracking of official microfrontend support can be found at https://github.com/angular/angular-cli/issues/17556. However, it is important to note that there is currently no official support available.

Additionally, it's worth acknowledging that module federation is tied to the older build system utilizing Webpack, and it is not compatible with the new Esbuild pipeline, even with the use of custom plugins.

Nevertheless, there is an ongoing implementation by the community utilizing native import maps, which can be explored at https://www.npmjs.com/package/@angular-architects/native-federation.

**Comment by DavidGoethCplace** [comment]
ok, thank you
