### ISSUE TITLE
External library not excluded from build despite being defined in browser field

### ISSUE THREAD

**Issue by piozygmunt** [angular/angular-cli#27033]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

External library that is marked with `false` in `package.json` (`browser` field) is still added to final bundle. It seems that issue is only present when using esbuild (with webpack it works as expected - library is not included when building). This behavior is pretty easy to reproduce, just add `browser` field to `package.json` with chosen library and check that is still being added to final bundle.

### Minimal Reproduction

https://github.com/piozygmunt/angular-builder

Issue related lines:
https://github.com/piozygmunt/angular-builder/blob/master/package.json#L12
https://github.com/piozygmunt/angular-builder/blob/master/package.json#L27
https://github.com/piozygmunt/angular-builder/blob/master/src/main.ts#L17

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.2
Node: 18.19.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.3
```

### Anything else relevant?

Based on some simple debbuging it seems to me that the problem is either with esbuild itself or angular-complier plugin. Despite library is excluded, it still is proceseed by angular-compiler plugin and because it returns some contents (https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/tools/esbuild/angular/compiler-plugin.ts#L391 ) it ends up being added to bundle. I'm not sure if it is correct that esbuild invokes plugins for disabled libraries or maybe angular-plugin should filter disabled entries. 

Similar simple setup (esbuild + excluded library in browser field) but without angular works as expected.

**Comment by alan-agius4** [comment]
Hi @piozygmunt, thanks for opening this issue. It appears to be an esbuild issue https://github.com/evanw/esbuild/issues/3629

Unfortunately, this is not actionable from our end.
