### ISSUE TITLE
Inlined critical styles are kept in the linked css file

### ISSUE THREAD

**Issue by lukasmatta** [angular/angular-cli#27040]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

I'm wondering if it is expected that the inlined critical styles stay in the linked stylesheet file. Wouldn't it be beneficial to reduce the size of the linked stylesheet file by removing the styles that have already been inlined inside the `index.html` file? [The test](https://github.com/angular/angular-cli/blob/34dc6a1f6ea99ba24307a724d66a5cfb03275cab/packages/angular_devkit/build_angular/src/builders/application/tests/options/optimization-inline-critical_spec.ts) for this feature doesn't check the contents of the linked stylesheet file.

In specific cases, this might also cause different behavior in the runtime for the dev vs. production builds (I've stumbled upon this issue in the project in which we are reading css variables in the runtime, in the prod build they were doubled due to inline styles redundancy).

### Minimal Reproduction

Do the production build (inlineCritical set to true) of a project containing css that the builder considers to be critical (e.g. `:root` tag)

### Your Environment

```text
Angular CLI: 17.1.2
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
This is currently anticipated for several reasons:

- Modifying the file contents at this point would require regenerating the link tags if SRI is enabled.
- Enabling SSG/SSR could potentially result in a distinct stylesheet for each page, which is less than optimal due to the inability to cache the stylesheet across various requests.

**Comment by lukasmatta** [comment]
I see your point, thanks for the explanation and quick reply.
