### ISSUE TITLE
@import Sass from Angular CDK causes errors with browser-esbuild

### ISSUE THREAD

**Issue by JamesHStanlib** [angular/angular-cli#27050]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0

### Description

Error is raised when using Angular CDK style reference (no Angular Material, just CDK).

>  [ERROR] Could not resolve "~@angular/cdk/overlay-prebuilt.css"

### Minimal Reproduction

Sample repo: https://github.com/JamesHStanlib/AngularScssEsBuildError.git

Alternatively, follow these steps.
1. `ng new AngularScssEsBuildError --strict --style scss --package-manager npm`
2. `npm install --save  @angular/cdk`
3. create a reference to the @angular/cdk overlay pre-compiled css within your styles.scss file with `@import "~@angular/cdk/overlay-prebuilt.css";`
4. `ng serve` or `ng build`

### Exception or Error

```text
Application bundle generation failed. [2.657 seconds]
X [ERROR] Could not resolve "~@angular/cdk/overlay-prebuilt.css"

    src/styles.scss:1:8:
      1 │ @import "~@angular/cdk/overlay-prebuilt.css";
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "~@angular/cdk/overlay-prebuilt.css" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.2
Node: 20.10.0
Package Manager: npm 10.4.0
OS: win32 x64

Angular: 17.1.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
This is expected, please remove the tilde from the path.
