### ISSUE TITLE
esbuild dynamic import at runtime breaks ng serve

### ISSUE THREAD

**Issue by fabioemoutinho** [angular/angular-cli#27068]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

Yes

### Description

With esbuild, when using a dynamic import at runtime, like `import(url)`, I'm able to create a production build - and it works as expected - but when running ng serve it breaks.
For build configuration, I added `"externalDependencies": ["jquery-3.7.1.min.js"],` to angular.json, along with a `@ts-ignore` comment where it is used, and this allowed the import to be made in `app.component.ts` successfully at runtime.
Note that `externalDependencies` is not available on serve configuration.

Here's the AppComponent:
```
export class AppComponent {
  title = 'dynamic-imports-runtime';

  constructor() {
    // @ts-ignore
    import('https://code.jquery.com/jquery-3.7.1.min.js').then((jquery) =>
      console.log(jquery)
    );
  }
}
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/fabioemoutinho/dynamic-imports-runtime

### Please provide the exception or error you saw

```true
Application bundle generation complete. [1.474 seconds]
Watch mode enabled. Watching for file changes...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open 'https://code.jquery.com/jquery-3.7.1.min.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'https://code.jquery.com/jquery-3.7.1.min.js'
}

Node.js v18.19.0
➜  browser git:(main) ✗
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 18.19.0
Package Manager: npm 10.2.3
OS: darwin x64

Angular: 17.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@angular/cli                    17.1.2
@schematics/angular             17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else?

Let me know if I'm doing anything wrong, but this is the configuration that enabled me to run the import in production build successfully

**Comment by clydin** [comment]
This case will be automatically handled in the next path release but until then you should be able to accommodate this use case by adding the full import specifier to `externalDependencies`:
```
"externalDependencies": ["https://code.jquery.com/jquery-3.7.1.min.js"],
```

**Comment by fabioemoutinho** [comment]
> This case will be automatically handled in the next patch release but until then you should be able to accommodate this use case by adding the full import specifier to `externalDependencies`:
> 
> ```
> "externalDependencies": ["https://code.jquery.com/jquery-3.7.1.min.js"],
> ```

thanks! I don't know why I haven't used the full path, I believe I might have tried it with webpack and it didn't work, then used it this way with esbuild.
By the way, is it possible to ignore the TS error automatically when using externalDependencies to get rid of the `@ts-ignore`?

**Comment by clydin** [comment]
That is really a legitimate error and ideally should not be ignored.
You can add types to the project so that TypeScript does not error and usage is checked including autocomplete support.
In a separate file in the project (e.g., `types.d.ts` or similar), you can add:
```
declare module 'https://code.jquery.com/jquery-3.7.1.min.js' {
    export * from 'jquery'
}
```
You will also need to install the `@types/jquery` package to the project. For npm, `npm i -D @types/jquery`.

**Comment by fabioemoutinho** [comment]
> That is really a legitimate error and ideally should not be ignored. You can add types to the project so that TypeScript does not error and usage is checked including autocomplete support. In a separate file in the project (e.g., `types.d.ts` or similar), you can add:
> 
> ```
> declare module 'https://code.jquery.com/jquery-3.7.1.min.js' {
>     export * from 'jquery'
> }
> ```
> 
> You will also need to install the `@types/jquery` package to the project. For npm, `npm i -D @types/jquery`.

that makes sense. Thanks for the clarification!
