### ISSUE TITLE
breaking change in a minor: @angular-devkit/build-angular@17.1 put `browser-sync` to optional deps

### ISSUE THREAD

**Issue by Platonn** [angular/angular-cli#27078]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.0

### Description

_(I'm creating this new ticket, because the discussion in relevant [ticket](https://github.com/angular/angular-cli/issues/26349) and [PR](https://github.com/angular/angular-cli/pull/26587) is already locked and limited contributors only)_

After simple npm-bumping the version of `@angular-devkit/build-angular` from v17 to v17.1, and running the command `npm run dev:ssr` I got an error `"browser-sync" is not installed"`.

Note: I already migrated my app from ng16 to ng17 some time ago - so I'm still using the old builder `@angular-devkit/build-angular:ssr-dev-server`.

I've discovered only now there exists a 17.1 migration schematics for installing `browser-sync`. But when I'm bumping an Angular _minor_ I'm surprised I'm expected by the framework authors to run _migrations scripts_ - because minors shouldn't contain breaking changes. 🤔 

I've seen the comment: https://github.com/angular/angular-cli/issues/26349#issuecomment-1809580491
> Latest localtunnel (2.0.2) [is still using](https://unpkg.com/localtunnel@2.0.2/package.json) a vulnerable axios (0.21.4). There's already an issue filed to localtunnel to update the dependency: https://github.com/localtunnel/localtunnel/issues/632. > Until that's fixed, there's not much we can do about this.
> 
> browser-sync is only used for live reloading in ng serve and is used in local development only, so the risk here is fairly > minimal. Rennovate should automatically pick up a version bump when it is available.

And now I know I need to install `browser-sync` manually.

Instead of moving `browser-sync` to optional deps in v17.1, did you consider the following?:
- in v17.1 only bump version of the transitive dependency of browser-sync (for security reasons), but not move it to optional deps
- in the nearest major (v18) move `browser-sync` to optional deps + provide migrations for it

### Minimal Reproduction

1. migrate an Angular SSR app from ng16 to ng17.0.0 (not 17.1.0)
2. npm-install @angular-devkit/build-angular in version 17.1.0
3. run `npm run dev:ssr`

and get an error that `"browser-sync" is not installed"`.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.5
Node: 18.15.0
Package Manager: npm 9.5.0
OS: darwin arm64

Angular: 17.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, pwa, router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.5
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            17.0.5
@angular-devkit/schematics      17.0.5
@schematics/angular             17.0.5
ng-packagr                      17.0.3
rxjs                            7.8.1
typescript                      5.2.2
webpack                         5.76.3
zone.js                         0.14.2
```

**Comment by alan-agius4** [comment]
Hello @Platonn, in this particular scenario, the decision was made considering various factors. One significant factor was the lack of progress in resolving the security vulnerability at the time. This isn't the first instance of such an issue with browser-sync, given its reliance on a substantial number of older dependencies. Additionally, browser-sync is utilized in one of the less popular builders, `@angular-devkit/build-angular:ssr-dev-server`. Despite the inconvenience of resolving errors when browser-sync isn't installed, the process is relatively straightforward. Thus, for now, we prefer to maintain the current setup. 

Furthermore, it's worth noting that while migrations are typically reserved for major versions, there have been instances where migrations were included in minor versions. Migrations serve broader purposes beyond solely addressing breaking changes.
