### ISSUE TITLE
Remove/Delete Application

### ISSUE THREAD

**Issue by hannah23280** [angular/angular-cli#27074]
**Current Situation:** 
I create a new angular workspace, with a flag --no-create-application.  Then i start adding few new applications using  `ng generate application`  into the workspace.   When i decide to remove one of the application, i need to manually update the angular.json to remove the portion of the configuration related to the removed application.  
`

### Describe the solution you'd like

I would hope to have a new command such as `ng delete application` or `ng remove application` to enable the ease of removing the application.  Updating the angular.json manually is prone to accidental removing more than necessary.

**Comment by alan-agius4** [comment]
@hannah23280, we appreciate your feature request. However, incorporating this command isn't currently on our roadmap for several reasons:

The steps required to remove an application are straightforward.
Application deletion is infrequent.
