### ISSUE TITLE
An unhandled exception occurred: Cannot read property 'add' of undefined See "C:\Users\AH55278\AppData\Local\Temp\ng-K2A4IA\angular-errors.log" for further details.

### ISSUE THREAD

**Issue by raksha-acharya** [angular/angular-cli#27082]
![image](https://user-images.githubusercontent.com/54028291/304195814-a5c234be-ac69-41e1-a1f4-1fb88baa3560.png)

Below are the versions I am using in my project
Angular CLI: 12.1.3        
Node: 12.18.1
Package Manager: npm 6.14.5
OS: win32 x64

  "dependencies": {
    "@angular/animations": "~11.1.0",
    "@angular/cdk": "^11.1.0",
    "@angular/common": "~11.1.0",
    "@angular/compiler": "~11.1.0",
    "@angular/core": "~11.1.0",
    "@angular/forms": "~11.1.0",
    "@angular/material": "^11.1.0",
    "@angular/material-moment-adapter": "^11.1.1",
    "@angular/platform-browser": "~11.1.0",
    "@angular/platform-browser-dynamic": "~11.1.0",
    "@angular/router": "~11.1.0",
    "@datadog/browser-rum": "^4.44.2",
    "@fullcalendar/angular": "^5.6.0",
    "@fullcalendar/daygrid": "^5.6.0",
    "@fullcalendar/interaction": "^5.6.0",
    "@fullcalendar/resource-timeline": "^5.6.0",
    "@fullcalendar/timegrid": "~5.6.0",
    "@glidejs/glide": "^3.4.1",
    "@material-extended/mde": "^3.0.3",
    "@ng-bootstrap/ng-bootstrap": "^5.3.0",
    "@ngrx/component-store": "^11.1.1",
    "@ngrx/data": "^11.1.1",
    "@ngrx/effects": "^11.1.1",
    "@ngrx/entity": "^11.1.1",
    "@ngrx/router-store": "^11.1.1",
    "@ngrx/store": "^11.1.1",
    "@ngrx/store-devtools": "^11.1.1",
    "@types/snapsvg": "^0.5.0",
    "@webcomponents/custom-elements": "^1.4.3",
    "@webcomponents/shadydom": "^1.6.1",
    "@webcomponents/webcomponentsjs": "^2.5.0",
    "bootstrap": "^4.6.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.0",
    "d3": "^7.0.0",
    "d3-zoom": "^3.0.0",
    "es6-promise": "^4.2.8",
    "isomorphic-fetch": "^3.0.0",
    "line-awesome": "^1.3.0",
    "mat-timepicker": "^5.1.0",
    "material-icons-font": "^2.1.0",
    "moment": "^2.29.4",
    "moment-range": "^4.0.2",
    "moment-timezone": "^0.5.33",
    "ng-circle-progress": "^1.6.0",
    "ng2-search-filter": "^0.5.1",
    "ngx-image-cropper": "^5.0.1",
    "ngx-infinite-scroll": "^10.0.1",
    "ngx-pagination": "^5.1.1",
    "ngx-pipes": "^3.0.0",
    "ngx-toastr": "^13.2.1",
    "primeicons": "^4.1.0",
    "primeng": "^11.2.0",
    "ramda": "^0.27.2",
    "rxjs": "^6.6.3",
    "snap.svg.zpd": "^0.0.12",
    "snapsvg": "^0.5.1",
    "tslib": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "whatwg-fetch": "^3.6.2",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.1",
    "@angular/cli": "~11.1.1",
    "@angular/compiler-cli": "~11.1.0",
    "@angular/localize": "^11.1.2",
    "@types/d3": "^6.7.5",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "@types/ramda": "github:types/npm-ramda#dist",
    "codelyzer": "^6.0.0",
    "dotenv": "^10.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.2.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "mv": "^2.1.1",
    "protractor": "~7.0.0",
    "replace-in-file": "^6.2.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.2"
  }

**Comment by JeanMeche** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#question).
