### ISSUE TITLE
@angular/cli depends on vulnerable version of ip (NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks)

### ISSUE THREAD

**Issue by JainDhaval** [angular/angular-cli#27086]
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Running npm audit on Angular v16 project causes an error output, because @angular/cli depends on vulnerable version of npm ip.
See more details: [GHSA-78xj-cgh5-2h22](https://github.com/advisories/GHSA-78xj-cgh5-2h22)

### Minimal Reproduction

Create new Angular v16 project.
Run npm audit in the project folder

### Your Environment

```text
Angular CLI: 16.2.10
Node: 18.18.1
Package Manager: npm 10.2.0
OS: win32 x64

Angular: 16.2.12
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.10
@angular-devkit/build-angular   16.2.12
@angular-devkit/core            16.2.10
@angular-devkit/schematics      16.2.10
@angular/cli                    16.2.10
@schematics/angular             16.2.10
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.3
```

**Comment by alan-agius4** [comment]
Angular CLI version 16 does not have a direct or transtivie dependency on the `ip`.

**Comment by nfarrell-kx** [comment]
@alan-agius4 is this correct?

├─┬ @angular/cli@16.2.11
│ └─┬ pacote@15.2.0
│   └─┬ npm-registry-fetch@14.0.5
│     └─┬ make-fetch-happen@11.1.1        
│       └─┬ socks-proxy-agent@7.0.0       
│         └─┬ socks@2.7.1
│           └── ip@2.0.0
