### ISSUE TITLE
Tsconfig paths not working if package in node_modues refs a local package using `application` builder

### ISSUE THREAD

**Issue by Carlosamouco** [angular/angular-cli#27080]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

If I install/link a package in node_modules that imports a local package that as been configured with tsconfig `paths`, the `application` builder is not able to resolve the local package from the install package.
Using the `browser` builder It works as expected.

### Minimal Reproduction

Clone the repo: https://github.com/Carlosamouco/repro-tsconfig-paths
npm install;
ng build a;
ng serve;

library "a" is local and has tsconfig paths defined;
library "b" is installed in the node_modules;

### Exception or Error
![image](https://github.com/angular/angular-cli/assets/9380964/fd584fb3-252e-4caa-8b9d-46fd33af1383)

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.1.3
Node: 18.18.0
Package Manager: npm 10.4.0
OS: win32 x64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@schematics/angular             17.1.3
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by Carlosamouco** [comment]
The only way that I found to make this work is, to link all necessary local packages to node_modules. Since this works with the `browser` builder, is there anything preventing us from being able to do the same in the `application` builder?

**Comment by JoostK** [comment]
This is the sae as #26901, with https://github.com/angular/angular-cli/issues/26901#issuecomment-1907045285 as most relevant option. That configuration only works in the devserver when Vite's prebundling is disabled, which as of 17.1 requires fully disabling the cache. In 17.2 it should be possible to configure which packages to pre bundle, per #27021.

**Comment by Carlosamouco** [comment]
@JoostK, I am not sure if this the same problem of the issue you mentioned. I have tested with the version `17.2.0-rc.0` and I have disable pre bundle for lib `b` but the problem persists. I think excluding a lib from being pre bundled is mostly useful when you want to link a lib but want to treat it as if it was source code, so it does not cached.

**Comment by Carlosamouco** [comment]
Sorry I did not understand it at first, you are right it works with:

```json
"browser": {
    "a": "a"
}
```

Non the less, it feels very odd having to do this, since this was not required for the `browser` builder and lib `a` is seamless for browser and server.
