### ISSUE TITLE
Could you create a sample project for sass partials for a global stylesheet and a postcss processing?  

### ISSUE THREAD

**Issue by daddyschmack** [angular/angular-cli#2708]
Hi Guys,

If this is not the proper forum for this request, please advise.

I was wondering if you could create a sample project, based on webpack that uses sass with partials for the global stylesheet and also autoprefixer for post css processing?  

There is a tutorial on how to do it with broccoli, but not webpack
This issue:
https://github.com/angular/angular-cli/issues/1915
includes some information ,but it does not specify how to set up webpack to run global sass. 

Thanks,
John

**Comment by grizzm0** [comment]
Please use stackoverflow for questions in the future.

What do you mean by global sass?

You can not use postcss plugins atm. Please see #1656 for more info.

**Comment by daddyschmack** [comment]
@grizzm0:

I am sorry, i found out how to do this.  It is super simple.  We can close this..
