### ISSUE TITLE
serverless offline with angular cli application

### ISSUE THREAD

**Issue by edvenkat** [angular/angular-cli#27093]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

I am attempting to utilize the application builder instead of webpack as per the instructions provided in the link - https://angular.io/guide/esbuild. However, we encountered the following error while running the application in serverless offline.

undefined ERROR Uncaught Exception {
"errorType": "Runtime.ImportModuleError",
"errorMessage": "Error: Cannot find module './dist/server/server'\nRequire stack:\n- /var/task/lambda.js\n- /var/runtime/index.mjs",
"stack": [
"Runtime.ImportModuleError: Error: Cannot find module './dist/server/server",
"Require stack:",
"- /var/task/lambda.js",
"- /var/runtime/index.mjs",
" at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
" at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
" at async start (file:///var/runtime/index.mjs:1282:23)",
" at async file:///var/runtime/index.mjs:1288:1"
]
}

Please help on this.

### Minimal Reproduction

NA

### Exception or Error

```text
NA
```

### Your Environment

```text
17
```

### Anything else relevant?

NA

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
