### ISSUE TITLE
All ng command print "error" on the console 

### ISSUE THREAD

**Issue by nacimux** [angular/angular-cli#2710]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 801

### Versions.
angular-cli: 1.0.0-beta.15
node: 5.6.0
os: win32 x64

### Repro steps.
i create the app with cli, make ng serve then when i stop the server and mke again ng serve or all other ng command, print error on the console

No stack trace, juste the word "error" printed on the console

**Comment by nacimux** [comment]
Hi, i figure out what was the problem, in the angular-cli.json when you miss a semicolon or have a too many ligne space..etc that return this error, it will be great if the error provide stack trace !

**Comment by thephilwells** [comment]
Same thing happened to me. Someone put a line comment in angular-cli.json, and `ng build` just broke with the word "Error" and no stack trace. Can this exception be handled?

**Comment by filipesilva** [comment]
Next release will include https://github.com/angular/angular-cli/pull/2565 which does just that.
