### ISSUE TITLE
"./node_modules/@angular/*" cause NG0203: `inject()` must be called from an injection context such as a constructor

### ISSUE THREAD

**Issue by IdanSysmetricAcount** [angular/angular-cli#27122]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

hi

i use angular 17.1.2 and i change angular build from "build-angular:browser" to "@angular-devkit/build-angular:application" in angular.json and i get error "NG0203: inject() must be called from an injection context such as a constructor". i notice that the error is due the line in my "tsconfig.json": 
"paths": {
      "@angular/*": [ "./node_modules/@angular/*" ]
}

i need this line because i use base library (without it the signal wont fire).
if i remove this line all work find in development with "ng serve", but its not work in publish after "ng build".

what can i do for build with "@angular-devkit/build-angular:application" that will work with 
"@angular/": [ "./node_modules/@angular/" ] in the "tsconfig.json"?

thank you.

### Please provide the exception or error you saw

```true
"NG0203: inject() must be called from an injection context such as a constructor"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.1.2
Node: 20.10.0
Package Manager: npm 10.4.0
OS: win32 x64

Angular: 17.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.2
@angular-devkit/build-angular   17.1.2
@angular-devkit/core            17.1.2
@angular-devkit/schematics      17.1.2
@schematics/angular             17.1.2
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by JoostK** [comment]
The `paths` options causes `@angular/core` to be included in the `main.js` file in addition to the prebundled copy of `@angular/core` by Vite. Disabling the cache disables prebundling `ng cache off` and that avoids the issue. I'm not sure why the path mapping matters though.

**Comment by IdanSysmetricAcount** [comment]
the problem is if i remove @angular/": [ "./node_modules/@angular/" ] from tsconfig, the production version(ng build) will throw exceptions about signals.
what i can do is to create 2 tsconfig.app.json , 1 for develop (that work with ng serve) with NO PATH and 1 for production with PATH (work with ng build) and redirect them in angular.json.

is this the write solution for work with the new builder with multi directories? 
thank you.

**Comment by alan-agius4** [comment]
Please see: https://github.com/angular/angular-cli/issues/26513#issuecomment-1830434529
