### ISSUE TITLE
Path defined in tsconfig not working properly

### ISSUE THREAD

**Issue by laijuthomas** [angular/angular-cli#27128]
### Command

build, serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16.2.11

### Description

I have package named "fernet": "^0.4.0" which depends on crypto library, I have installed crypto-browserify package and added the alias in tsconfig file as "crypto": ["./node_modules/crypto-browserify"]. This was working fine until I upgraded my app to angular 17.

Now when I build the app I get an error Could not resolve "crypto" in node_modules/fernet/fernet.js

### Minimal Reproduction

add "fernet": "^0.4.0" and use any fernet function and try ng build

### Exception or Error

```text
Could not resolve "crypto"

    node_modules/fernet/fernet.js:9:21:
      9 │ var crypto = require('crypto');
  The package "crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

### Your Environment

```text
Angular CLI: 17.2.0
Node: 20.11.1
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0
@angular-devkit/build-angular   17.2.0
@angular-devkit/core            17.2.0
@angular-devkit/schematics      17.2.0
@angular/cdk                    17.2.0
@angular/cli                    17.2.0
@angular/ssr                    17.2.0
@schematics/angular             17.2.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by JoostK** [comment]
This is the same as https://github.com/angular/angular-cli/issues/26901, with https://github.com/angular/angular-cli/issues/26901#issuecomment-1907045285 as most relevant option. That configuration only works in the devserver when Vite's prebundling is disabled, which as of 17.1 requires fully disabling the cache. In 17.2 it should be possible to configure which packages to pre bundle, per https://github.com/angular/angular-cli/pull/27021.

**Comment by clydin** [comment]
Unfortunately, the package in question appears to not natively support a browser environment.  The ideal solution would likely be to open a feature request with the package to support browsers directly.
However, to workaround the issue you can follow the recommendations above.  By using the `browser` field in the project's `package.json` and excluding the package from prebundling in the development server via the following in the `dev-server` options in `angular.json`:
```
"prebundle": {
  "exclude": ["fernet"]
},
```

The tsconfig path mapping usage is not recommended by the TypeScript team: https://www.typescriptlang.org/docs/handbook/modules/reference.html#paths-should-not-point-to-monorepo-packages-or-node_modules-packages
