### ISSUE TITLE
crossOriginIsolated is false in SharedWorker despite correct COEP and COOP headers

### ISSUE THREAD

**Issue by Emil-Blomquist** [angular/angular-cli#27121]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

**Current behavior**

When creating a `SharedWorker` in an Angular application, the `crossOriginIsolated` property is `false` in the worker, even though it's `true` in the main thread and the server is sending the correct `Cross-Origin-Embedder-Policy` and `Cross-Origin-Opener-Policy` headers.

**Expected behavior**

The `crossOriginIsolated` property should be `true` in the shared worker if the server is sending the correct headers and the application is being served over HTTPS or from `localhost`.

### Minimal Reproduction

1. **Create a new Angular project**: Use Angular CLI to create a new project. In your terminal, run:

```bash
ng new cross-origin-isolation-repro
```

2. **Create a Shared Worker**: In the `src/app` directory of your new project, create a new file `my-worker.worker.ts` with the following content:

```typescript
console.log('Shared worker crossOriginIsolated:', self.crossOriginIsolated);
```

3. **Use the Shared Worker in AppComponent**: In `app.component.ts`, instantiate and use the worker:

```typescript
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
  title = 'cross-origin-isolation-repro';

  ngOnInit() {
    const sharedWorker = new SharedWorker(new URL('./my-worker.worker.ts', import.meta.url), { type: 'module' });
    console.log('Main thread crossOriginIsolated:', window.crossOriginIsolated);
  }
}
```

4. **Update angular.json**: In `angular.json`, under `projects > cross-origin-isolation-repro > architect > serve > options`, add the following headers:

```json
"headers": {
  "Cross-Origin-Embedder-Policy": "require-corp",
  "Cross-Origin-Opener-Policy": "same-origin"
}
```

5. **Serve the Application**: Run `ng serve` in your terminal to start the Angular dev server.

6. **Check the Console**: Open the application in the browser and check the console. The `crossOriginIsolated` value is `false` in the shared worker but `true` in the main thread.

### Your Environment

```text
Angular CLI: 17.2.0
Node: 18.15.0
Package Manager: npm 9.5.0
OS: linux x64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0
@angular-devkit/build-angular   17.2.0
@angular-devkit/core            17.2.0
@angular-devkit/schematics      17.2.0
@angular/cli                    17.2.0
@schematics/angular             17.2.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by alan-agius4** [comment]
It seems this isn't related to Angular. In fact, the headers are being properly set. 

According to my understanding of the specifications, the mentioned property isn't available in the global scope of a shared worker.

For reference, see: [HTML Living Standard - WindowOrWorkerGlobalScope](https://html.spec.whatwg.org/multipage/webappapis.html#windoworworkerglobalscope) and [HTML Living Standard - [SharedWorkerGlobalScope](https://html.spec.whatwg.org/multipage/workers.html#sharedworkerglobalscope)
