### ISSUE TITLE
`ng add @angular/material@16` fails with Angular 17

### ISSUE THREAD

**Issue by Gourav102** [angular/angular-cli#27126]
### Command

add

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

As mentioned in [Angular 17 release blog](https://blog.angular.io/introducing-angular-v17-4d7033312e4b), Angular 17 supports Angular 16 Material. But when we run command `ng add @angular/material@16`, The package.json gets updated but end up getting an error on terminal **"Can't find module "node_modules/@schematics/angular/private/component.js"**.

Same command works without error if Angular Material v17 is used.

### Minimal Reproduction

Steps: 
 - Create an Angular app with latest Angular version (**Angular 17.2.1**)
 - Use command `ng add @angular/material@16`

### Exception or Error

```text
"Can't find module "node_modules/@schematics/angular/private/component.js"
```

### Your Environment

```text
OS: MacOS Sonoma v14.3.1
Editor: VS Code
Angular: v17.2.1
```

**Comment by 73ch61rl** [comment]
I'm getting the same error:
Can't find module "node_modules\@schematics\angular\private\component.js"
when trying to install Ant: ng add ng-zorro-antd
OS: win32 x64 Windows 11 Enterprise, version 23H2, OS build 22631.3155.
Angular CLI: 17.2.1
Node: 20.11.1
Package Manager: npm 10.4.0

**Comment by dgp1130** [comment]
This [should be fixed](https://github.com/angular/angular-cli/commit/4fc5c6ab65671a7b535d36ef06ac78fa19dbed53) in `@schematics/angular@17.2.1`. If you're still seeing an issue, please make sure your dependencies are updated post your `ng version` so we can verify if this is still a problem.
