### ISSUE TITLE
Support either proxy-conf or use ssr entrypoint for @angular-devkit/build-angular:dev-server

### ISSUE THREAD

**Issue by asgerjensen** [angular/angular-cli#27144]
### Command

serve

### Description

I have a project using @angular-devkit/build-angular:application as executor. 
This project has SSR enabled, via `ssr: { entry: 'path/to/file' }` and `server: path-to-main.server.ts`

When i run `nx serve` it detects that i have SSR enabled, and helpfully starts the server side rendering, by bootstrapping the thing from `server` path (not the thing from `ssr.entry`)

I have an external api, that is usually mapped via proxyConf, but this seems not to take effect. Ie the client side requests for /api/ does not get proxied, but rather the requests get sent to the SSR part which then just renders index.html

And since its not using the ssr-entry point to run this server, i cant add, say, an express-proxy to the configuration.

### Describe the solution you'd like

I'd like to be able to proxy calls to third party, for browser side calls, on projects that use  build-angular:application and build-angular:dev-server

### Describe alternatives you've considered

I can inject the true host names for third party service, from server side variables into client side, but this adds CORS overhead and management issues during normal development.

**Comment by not-nemlig** [comment]
@asgerjensen Did you ever find a solution for this, or are you still waiting?

**Comment by asgerjensen** [comment]
Still waiting. Although for now, i've just not used proxy-conf and used direct endpoint addresses during test instead.
That, or just run a non-ssr instance when its for design work only.
