### ISSUE TITLE
Remove linefeed setting from editor config

### ISSUE THREAD

**Issue by JasonGoemaat** [angular/angular-cli#2716]
OS: Windows 10

Versions: 
angular-cli: 1.0.0-beta.15
node: 6.6.0
os: win32 x64

No failure, but the editor config"end_of_line = lf" is annoying for windows if the user has setup git with "core.autocrlf = true", which most people should have done by now.   I don't see why the angular-cli project should take a position on this preference, or really any of them.  Editorconfig is handy, but including a default one in any cli project can cause grief.  I prefer checking out crlf on windows and my editors handle that fine.  Having this in editorconfig would work if I set a local repository config for autocrlf=false or input, but then if I happen to use an editor that ignores the editorconfig I would end up committing crlf.  It caused some confusion with another team member because every time he did a checkout his editor would tell him all the files he had open have changed.

**Comment by filipesilva** [comment]
Would you be interested in making a PR to fix this? I'll review it.
