### ISSUE TITLE
[Regression] support for optimization with intact class names (JavaScriptOptimizerOptions.keepNames)

### ISSUE THREAD

**Issue by jbjhjm** [angular/angular-cli#27169]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

15.x

### Description

While updating our main repo from angular 15 to 17, I had to find out that inside JavaScriptOptimizerPlugin, support for passing  "keepNames" option to esbuild has been removed. ( option documentation: https://esbuild.github.io/api/#keep-names )

Digging through the source code I found some comments giving insight on it not being of much use anymore for angular itself.
So I am guessing it has been removed in assumption it would not matter, because angular does not rely on class names.
Unfortunately, other 3rd party libraries may depend on class names being intact.

With the keepNames option being removed, we can only build a working app with enabling keepIdentifierNames - which will result in a whopping 30-35 % code size increase.

Allowing devs to set this flag shouldn't be problematic or complex as it is just an additional option that can be passed to esbuild.

Right now our choices are to release a heavily bloated/unoptimized app or to rip apart JavaScriptOptimizerPlugin and re-implement it on our own - just to be able to set that one option again. :( 

Please consider reintroducing support for it.

### Minimal Reproduction

Due to the kind of issue, a reproduction makes no sense.

Execute compilation of any named class with buildOptions.keepNames = true.

Angular 15 would generate minified code with intact class names.
Angular 17 will generate code with obfuscated class names.

Responsible source code:
https://github.com/angular/angular-cli/blob/15.2.10/packages/angular_devkit/build_angular/src/webpack/plugins/javascript-optimizer-worker.ts#L174

### Your Environment

```text
Angular CLI: 17.1.3
Node: 18.17.0
Package Manager: npm 10.4.0
OS: win32 x64

Angular: 17.1.3
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.3
@angular-devkit/build-angular   17.1.3
@angular-devkit/build-webpack   0.1701.3
@angular-devkit/core            17.1.3
@angular-devkit/schematics      17.1.3
@angular/cdk                    17.1.2
@schematics/angular             17.1.3
rxjs                            7.8.1
typescript                      5.3.3
webpack                         5.74.0
zone.js                         0.14.3
```

**Comment by JeanMeche** [comment]
Hi, 
You can disable mangling by using the `NG_BUILD_MANGLE` flag as following while keeping optimisations on.  

`NG_BUILD_MANGLE=0 ng build`

**Comment by jbjhjm** [comment]
> Hi, You can disable mangling while keeping optimisations on by using the `NG_BUILD_MANGLE` flag as following
> 
> `NG_BUILD_MANGLE=0 ng build`

Thanks Jean, unfortunately this is just an alternative way to control keepIdentifierNames here:
https://github.com/angular/angular-cli/blob/30f182c7ad69c20a736e5194a6e99167f1f411c6/packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts#L302

So this will result in NO indentifiers being minified, which would increase bundle size by almost 2 MB in our case.
Thus disabling mangling/minified identifiers entirely is no viable option for us.

**Comment by clydin** [comment]
Unfortunately, the plugin in question is not part of the public API and should not be relied upon in any direct form.  This plugin may change at any time and is not guaranteed to exist in future versions. Customization of the Webpack configuration via a 3rd-party builder, while possible, is not a supported usage scenario.  However, if the Webpack configuration is already being altered in such a manner, this plugin may be completely removed and replaced with other optimization plugins if preferred or if it does not meet the needs of a project.
