### ISSUE TITLE
tsconfig.paths are not taken into account when compiling with ESBuild

### ISSUE THREAD

**Issue by jcompagner** [angular/angular-cli#27176]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

with "browser" builder (not application or esbuild)

### Description

there are already a few cases but those are closed like:
https://github.com/angular/angular-cli/issues/26467
and
https://github.com/angular/angular-cli/issues/26476

[tsconfigpaths.zip](https://github.com/angular/angular-cli/files/14432924/tsconfigpaths.zip)

But for me its quite easy to reproduce, just extract the attached zip, run "npm install" and then "npm run build" on it and you will get:

```
✘ [ERROR] File 'internalproject\servoy-public\src\public-api.ts' is missing from the TypeScript compilation. [plugin angular-compiler]

    externalproject/bootstrapcomponents/fesm2022/servoy-bootstrapcomponents.mjs:3:20:
      3 │ import * as i1 from '@servoy/public';
        ╵                     ~~~~~~~~~~~~~~~~

  Ensure the file is part of the TypeScript program via the 'files' or 'include' property.
```

but that project is there it is part of the main thing by using a tsconfig mapping:

```
"paths": {
      "@servoy/public": [
        "./internalproject/servoy-public/src/public-api",
      ]
    },
```

if i read this:
https://esbuild.github.io/api/#external

then i think if i could just provide that as an external thing that is solved at runtime this could work? 
(but i have no idea how to provide that with the angular builder)

So how can we make sure that the esbuilder (or angular/cli) does see those modules because they are there because the are part of the main source and specified as a path?

### Minimal Reproduction

unzip the given zip above
npm install
npm run build

### Exception or Error

```text
that it compiles fine
```

### Your Environment

```text
Angular CLI: 17.2.1
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.1
@angular-devkit/build-angular   17.2.1
@angular-devkit/core            17.2.1
@angular-devkit/schematics      17.2.1
@angular/cli                    17.2.1
@schematics/angular             17.2.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by jcompagner** [comment]
In my real project i get a slight different error:

```
⠸ Building...
✘ [ERROR] Could not resolve "@servoy/public"

    node_modules/@servoy/bootstrapcomponents/fesm2022/servoy-bootstrapcomponents.mjs:3:20:
      3 │ import * as i1 from '@servoy/public';
        ╵                     ~~~~~~~~~~~~~~~~

  You can mark the path "@servoy/public" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

**Comment by jcompagner** [comment]
hmm if i then add ""internalproject/servoy-public/src/public-api.ts"
to the files in the tsconfig.app.ts it starts to work. but this is not the case in my normal install. 
have to investigate what the difference is, or start the other way around (strip that install)

**Comment by jcompagner** [comment]
[test.zip](https://github.com/angular/angular-cli/files/14433932/test.zip)

i did it the other way around, stripping down our application
if that test.zip is unzipped you have in a root dir "package.json" and a "test" dir

run "npm install" in that root dir
then go into the test dir and run "npm install" and then "npm run build"

then the above error will appear

**Comment by JoostK** [comment]
The `application` and `browser-esbuild` builder no longer take `tsconfig` path mappings into account during module resolution of libraries. This does make some sense, as `tsconfig` concerns how TS compiles your `.ts` files, whereas library files are _not_ compiled by TypeScript.

**Comment by jcompagner** [comment]
hmm it really seems i need to build our own lib:

npm run build_lib

and then install it in ourself:

npm install dist/servoy/public

then it starts to work

then i wonder how our development will go, because normally we could just run "npm run build_debug" and be in watch mode and we could just change stuff in the public lib dir that would be picked up then (didn't test this yet)

**Comment by jcompagner** [comment]
yes this is now a bit annoying, so if we have sources (that means for us tsconfig.paths) of our plugin packages 
then it works, because source can find sources  (tsconfig.paths) just fine
those things can also find "binary" packages (compiled/installed packages) also just fine

But a binary package can't depend anymore on a tsconfig source package.

And because of that our development will be much harder because or we need to have it all as sources (so 1 big source tree) then we can debug and code through that all.
But we can't mix anymore because then our public library must be also an installed package which means no easy development for that anymore..

So this for us a kind of a big productivity loss

**Comment by jcompagner** [comment]
is there someway i can just tell esbuild to see this as an external thing (https://esbuild.github.io/api/#external0

because i really need this typescript feature to really work (https://www.typescriptlang.org/tsconfig#paths)

I really need those paths to get working because our core product also uses our public library (to inject stuff and also use stuff for of that)

But this is just a project of the main stuff, so now our core doesn;t build because it can't find the library if i don't include it as a path, but if i include it as a path then 3rd party components that can be installed into the product (which is core and the lib) then those don't work now.
If i install it as a npm package in core then i can't use path because it will see this then as a duplicate.. (i get stuff like that there is a "2" added like ServoyPublicModule2) and that one it can't load ofcourse there is no "2"
So i need to remove it as a tsconfig.paths thing but then our plain core build always needs an install of our lib (which is just part of the source)

So our esbuild starts also understanding tsconfig.paths or angular application/esbuilder gives us the option to exclude stuff because at runtime it will work (our public package will be in)

**Comment by alan-agius4** [comment]
The current behavior aligns with expectations, and it's worth noting that the pattern you're attempting to utilize isn't recommended by the TypeScript team. TypeScript has outlined the behavior for the paths option more formally. Specific guidance on this matter can be found in the TypeScript documentation here: [Paths should not point to monorepo packages or node_modules packages](https://www.typescriptlang.org/docs/handbook/modules/reference.html#paths-should-not-point-to-monorepo-packages-or-node_modules-packages). It clarifies that while module specifiers matching path aliases are bare specifiers, once the alias is resolved, module resolution proceeds as a relative path. Consequently, features like those for node_modules package lookups, including support for the package.json "exports" field, don't take effect when a paths alias is matched.

Unfortunately, as packages and projects increasingly adopt newer methods for defining package entry points, the current path mapping configuration may become problematic and could result in TypeScript and bundling errors.

The recommended solution, as outlined in the linked documentation, is to utilize the project's package manager to link the relevant packages into the node module hierarchy of the project.

**Comment by jcompagner** [comment]
Then for us coding our applicaiton will have a huge affect which is very pity

because what is the alternative for this? i don't see this

So moving to the esbuild builders has had some great effects on develop and maintenance stuff for now 2 issues

1> this issue, which really affects our development of our public api module that is part of our core but used as api for 3rd party stuff that hooks back into our core.

2> the lack of esbuild of doing dynamic loading of imports (with variables in the import statement) now i have to maintain that by hand by generating huge switch/case statements (and every release of various npm packages i need to check if they added a new one)

the new builders are very nice because of the huge speed improvements but in the development area they are really a big step backwards.. :(

**Comment by alan-agius4** [comment]
Changes in the linked package will be picked up during watch mode, given that the linked library is excluded from being pre-bundled.

```js
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "prebundle": {
              "exclude": ["my-lib"]
            }
          },
```

**Comment by jcompagner** [comment]
we don't use the dev-server we only need the output files so we just run;

ng build projectname --watch

so we can also add that same prebundle/exclude in the normal none production build?

i think what really would help us if we could just give this; https://esbuild.github.io/api/#external0 to the esbuilder...

i guess i just need then 2 command windows 1 doing:


ng build projectname --watch

and the other doing:

ng build @servoy/public --watch

and the second one output is installed in the first one..
