### ISSUE TITLE
npm ERR! Darwin 14.5.0

### ISSUE THREAD

**Issue by Chaklader** [angular/angular-cli#2719]
I was trying to install angular-cli using the following command 
 
npm install -g angular-cli@latest and the get the error described below, 

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "angular-cli@latest"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/compiler@2.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/compiler-cli@0.6.4 wants @angular/compiler@2.0.2
npm ERR! peerinvalid Peer @angular/platform-server@2.1.0 wants @angular/compiler@2.1.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Chaklader/npm-debug.log

What should I do to resolve the issue ?

**Comment by HuddleHouse** [comment]
I have this exact same issue! Arghh

**Comment by Chaklader** [comment]
I thought this may only the Mac Os issue. Today I try to install Angular 2 in Windows 10 and still having the same issue. Is that because this is still in the Beta version?

**Comment by HuddleHouse** [comment]
I used angular cli on my laptop earlier today. I don’t get it! Both of my computers are OS X .

**Comment by HuddleHouse** [comment]
uninstalling and reinstalling angular-cli should fix the issue

https://github.com/angular/angular-cli/issues/1190 <https://github.com/angular/angular-cli/issues/1190>

**Comment by filipesilva** [comment]
You need npm3 to install the CLI: https://github.com/angular/angular-cli#prerequisites.

You can update npm by doing `npm install -g npm`

**Comment by akshayextentia** [comment]
Thanks Filipesilva. Its good suggestion to check our NPM version. Its help me.
