### ISSUE TITLE
All angular commands in WSL2 take at least 40s

### ISSUE THREAD

**Issue by mangelozzi** [angular/angular-cli#27212]
### Command

version

### Description

`ng version` or `ng --help` or `ng g c FooComponent` all take 40 seconds to run. Every time I run a ng command it hangs, waits for something to time out, then runs the command.

### Minimal Reproduction

1. Setup WSL2 (not 1, must be WSL2) with Debian 12 (bookworm)
2. Create an angular project
3. Run `ng version`
4. Observe the long delay.

### Your Environment

```text
OS: WSL2, Debian 12 (bookworm)

Angular CLI: 16.2.0
```

**Comment by alan-agius4** [comment]
Hey @mangelozzi,

Are you the Angular project files located on the Windows or Linux file system?

**Comment by alan-agius4** [comment]
Closing due to lack of communication.

**Comment by mangelozzi** [comment]
Sorry for slow response, files are in Linux file system for speed.

For anyone else facing this issue: I had node installed in windows, and the angular CLI in the windows node, when running `ng serve`, my computer was using the windows global node module, and taking 40s to start up. Now I use the angular cli from my project's linux file system with `npm run ng serve` and it's instant.
