### ISSUE TITLE
Angular 17 - SSR - ng build --base-href 'path' doesn't work

### ISSUE THREAD

**Issue by matejlednar** [angular/angular-cli#27228]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

npx ng build --base-href 'path' doesn't change the  <base href="/"> to <base href="path">

### Please provide a link to a minimal reproduction of the bug

/dist/ssr-demo/browser/index.html

### Please provide the exception or error you saw

```true
none
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular/cli: ^17.2.3
node 20.11.0
```

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/angular-cli/issues/27229
