### ISSUE TITLE
Disabling deployUrl with dev-server breaks existing use case

### ISSUE THREAD

**Issue by karptonite** [angular/angular-cli#27224]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.2.2

### Description

In #27193, setting `deployUrl` with dev-server was disabled for the `browser-esbuild` builder. This breaks a development configuration that has worked since the beginning of angular-cli. As explained [here](https://github.com/angular/angular-cli/issues/27152#issuecomment-1979033125), the rationale for this removal seems to be that no one should have been using `deployUrl` with `dev-server`, and that it was being set erroneously with the webpack server as well. I commented on this in the pull request, but now that this has been released, it seemed that a bug report made sense.

Our use case, as I understand it, requires using `deployUrl` for serving with `dev-server`. If I am mistaken, I'd be happy to change our developer configuration accordingly, but I don't see how we can use `dev-server` without `deploy-url`.

### Minimal Reproduction

Our use case is as follows: In production, our application contains hybrid between an older, non-Angular parts and updated Angular parts. It is served primarily from an nginx/php server we'll call `example.com`. The angular code is build and served (with `deployUrl`) from a CDN. So, for example, a user might load `https://example.com/foo`, which might be an angular page (the php server will return the angular `index.html`, which then loads the rest of the angular from the CDN, due to `deployUrl`), and then click over to `https://example.com/bar`, which might be an old non-angular page, and thus will be served directly by the php server. It all works seamlessly to the user.

Our development environments mirror our production environment.  Each developer has a remote development server, e.g., `dev-devname.example.com`. Instead of deploying the fully compiled angular code to a CDN, each developer runs `ng serve` locally from localhost:4200. `deployUrl` is set to `//localhost:4200`, and we `rsync` a copy of `index.html` over to the dev server so that it can be served by our php application when appropriate. `localhost` acts exactly like the CDN in this scenario, and `deployUrl` is what makes it work. The developer loads, for example, `https://dev-devname.example.com/foo`, php serves up `index.html`, and Angular is loaded from `localhost` (our fake CDN, in this case).

This has worked well for us since Angular CLI was introduced, and, except for a small, easily remedied issue with the url for the vite server( #27152), worked well when we transitioned from webpack to the `es-build` server. I was super happy to see that `deployUrl` was being added for the `application` builder as well, and I hope that this issue can be resolved so that we can continue to keep up with the latest Angular improvements!

### Your Environment

```text
Angular CLI: 17.2.3
Node: 18.18.2
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 17.2.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.3
@angular-devkit/build-angular   17.2.3
@angular-devkit/core            17.2.3
@angular-devkit/schematics      17.2.3
@angular/cdk                    17.2.1
@schematics/angular             17.2.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
Thank you for bringing up this issue. 

It's important to note that `deployUrl` was primarily designed for specifying the base URL for deployed assets, rather than for use during development. While we understand that every development workflow is unique, the utilization of `deployUrl` for development purposes is not a common practice among Angular CLI users.

Considering the unconventional nature of your development workflow, it may be beneficial to explore implementing a custom builder. Custom builders offer a high level of flexibility and can be customized to better suit your specific requirements. For instance https://github.com/just-jeb/angular-builders/tree/master/packages/custom-esbuild.

While we may not fully grasp your workflow's intricacies, another approach worth considering is utilizing proxies. Proxies can effectively route requests during development, offering a more streamlined solution.

**Comment by karptonite** [comment]
First, for others who are running into this issue, here is a simple solution: As long as `publicHost` is set to your `localhost` in `ng serve` config, I believe that the only change needed to recover the old `deployUrl` behavior in development is to edit `index.html` such that the appropriate `src` and `href` attributes also point to your `localhost`. 

@alan-agius4 thank you for your considered response. 

However, I hope you understand that this is a bit frustrating. It was, for us anyway, a breaking change in a bugfix release. The one line fix from yesterday that (seemingly in response to a small issue I raised myself) disabled use of deployUrl with dev-server affected only us and whichever other teams are using deployUrl for dev-server, so essentially the response to "this doesn't work quite right" was, "you shouldn't have been doing that at all, and now you can't". 

Our use case has been fully functional since the creation of Angular CLI. Until a couple weeks ago, deployUrl was slated for complete removal, until those who did use it explained exactly why their use cases weren’t supported by baseUrl. How sure are you that you understand the needs of those who _do_ use deployUrl? Anyone who has deployUrl set in their main builder options to anything other than `/` (and who doesn't override it to `/` in their `serve` option) is likely to see a change in behavior.

I would be surprised if we are the only team who will be affected by this. Because we have a fix (above), **this is no longer a concern for us**, but out of consideration of others who might be surprised by this, it might be helpful to them if you changed how you rolled this out. You could do any or all of the following: 

- include a mention of this as a potentially breaking change in the Changelog. 
- Revert the change until a feature or major release, when breaking changes are more expected.
- keep this issue open, so that others who might be affected will find the solution more easily, and can report that it is an issue for them without opening new issues.
