### ISSUE TITLE
Cli needs extra information on task progress

### ISSUE THREAD

**Issue by klatort** [angular/angular-cli#27227]
### Command

add, new, update

### Description

Recently I've was making an Angular demo in my new job and waited a long time before realizing the "Installing packages" was taking a lot of time because it wasn't able to download the node modules because of a vpn. I think that showing process progress in some way could be a nice feature to have so when a problem like this one arises, more information can be gathered to solve the problem.

### Describe the solution you'd like

A progress bar/percentage of the current task progress

**Comment by alan-agius4** [comment]
Hi @klatort, as of now, there's a spinner displayed during NPM installations. Unfortunately, there's no API accessible to create a progress bar for NPM installations.

However, we could offer a `--verbose` flag that would display the NPM installation logs on the screen, akin to running `npm install --verbose`.

Let track this in https://github.com/angular/angular-cli/issues/19552
