### ISSUE TITLE
Angular 17 - SSR - relative paths don't work

### ISSUE THREAD

**Issue by matejlednar** [angular/angular-cli#27229]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

href attribute is not updated during the build.

app.component.html
<a routerLink="./home" routerLinkActive="router-link-active">Home</a>

index.html
<a _ngcontent-ng-c2813606955 routerlink="./home" routerlinkactive="router-link-active" href="/home">Home</a>

### Please provide a link to a minimal reproduction of the bug

/dist/ssr-demo/browser/index.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
angular/cli: ^17.2.3
node 20.11.0
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.`
