### ISSUE TITLE
Missing build duration display after ng build in Angular v17.1.0

### ISSUE THREAD

**Issue by HCenggel** [angular/angular-cli#27233]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.0

### Description

In Angular version 17.0.0, the ng build command used to display the duration of the build process in the console after the packaging was completed. However, starting from version 17.1.0, this helpful feature seems to be missing. As a result, developers are no longer provided with the build duration information, making it difficult to assess the performance and optimization of the build process. It is important to address this bug and restore the display of build duration in the console after executing ng build.

### Minimal Reproduction

no

### Exception or Error

```text
no
```

### Your Environment

```text
Angular CLI: 17.1.0
Node: 18.17.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@angular/cdk                    17.1.0
@angular/cli                    17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

**Comment by HyperLife1119** [comment]
The build time logs seems to be overwritten by warning logs:

<img width="337" alt="image" src="https://github.com/angular/angular-cli/assets/41798664/dd0d40d2-b6b9-4dcb-a3c4-2e733974729e">

Once I eliminated all the warnings, I could see the build time logs:

<img width="229" alt="image" src="https://github.com/angular/angular-cli/assets/41798664/1e04b2ac-1b69-47d2-bdf9-2192164517ae">

**Comment by HCenggel** [comment]
> The build time logs seems to be overwritten by warning logs:
> 
> <img alt="image" width="337" src="https://private-user-images.githubusercontent.com/41798664/310809091-dd0d40d2-b6b9-4dcb-a3c4-2e733974729e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDE1NzgsIm5iZiI6MTcwOTgwMTI3OCwicGF0aCI6Ii80MTc5ODY2NC8zMTA4MDkwOTEtZGQwZDQwZDItYjZiOS00ZGNiLWEzYzQtMmU3MzM5NzQ3MjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4NDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNTRiMDU2ZDM1YzIyMzA5ODU4NDBjOWE4YTY2OTgwMGE4NTBmMTQwNmZhNTJjNjg0ZmI3YzczMjg1NzVlMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L2zeraUMn_xlkqI7KzDUgcV-ZjnxjXiCbYgO13_GwTg">
> Once I eliminated all the warnings, I could see the build time logs:
> 
> <img alt="image" width="229" src="https://private-user-images.githubusercontent.com/41798664/310809530-1e04b2ac-1b69-47d2-bdf9-2192164517ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MDE1NzgsIm5iZiI6MTcwOTgwMTI3OCwicGF0aCI6Ii80MTc5ODY2NC8zMTA4MDk1MzAtMWUwNGIyYWMtMWI2OS00N2QyLWJkZjktMjE5MjE2NDUxN2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA4NDc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MDU3NzlmYjYzNGFkYjE0NTI3ZjZhMzU5NTQ5YmE0NzM5NGIzMTZlZWM0MWJmNTMzZmM0ZTA2YmUyODQwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qP-HVarBt8CRROCHrbqH4qjQXhuzTwjVrvZ6JGjPf6k">

This is helpful for me.
