### ISSUE TITLE
Github pages deploy has wrong root path

### ISSUE THREAD

**Issue by dolanmiu** [angular/angular-cli#2723]
I deployed my `angular-cli` project to `gh-pages` with the help of:

http://ricostacruz.com/cheatsheets/travis-gh-pages.html

But having this error:
![screen shot 2016-10-16 at 03 24 46](https://cloud.githubusercontent.com/assets/2917613/19414772/1f983ccc-9350-11e6-8d80-e2730e0848a4.png)

Ive tried setting my `base href` from `/` to `/hingyman` but both did not work.

Here is my `deploy.sh`:

https://github.com/dolanmiu/hingyman/blob/master/deploy.sh

And here is the website:

https://dolanmiu.github.io/hingyman/

**Comment by filipesilva** [comment]
Try `/hingyman/` I suppose... but this really isn't the place to ask about completely unrelated guides or deploy scripts.
