### ISSUE TITLE
Prerender not generating files when strict mode is true

### ISSUE THREAD

**Issue by guilhermebentomarques** [angular/angular-cli#27234]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When I run the command 

`node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng run ui:prerender:qa`

With the following config

```json
"prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "guessRoutes": false,
            "browserTarget": "ui:browser",
            "serverTarget": "ui:server",
            "routesFile": "./src/prerender-routes.txt",
            "numProcesses": 4
          },
          "configurations": {
            "production": {
              "browserTarget": "ui:browser:production",
              "serverTarget": "ui:server:production"
            },
            "qa": {
              "browserTarget": "ui:browser:qa",
              "serverTarget": "ui:server:qa"
            },
          }
        },
```
        
The prerender-routes.txt has only one line (for test)
       
` /about-us`

The step of prerendering routes never happpen.

tsconfig file with strict true.

`"strict": true,`

![image](https://github.com/angular/angular-cli/assets/10928446/d66f1b89-3f1a-4fe7-a5da-2f888d7fee0b)

But when the tsconfig file with strict false, everything works fine.

`"strict": false,`

![image](https://github.com/angular/angular-cli/assets/10928446/6c0b1372-7faf-4b32-af9b-be4f4a572804)

### Minimal Reproduction

node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng run ui:prerender

### Exception or Error

```text
There is no error or exception the process just finishes without prerendering the files with I'm using strict mode.
```

### Your Environment

```text
Angular CLI: 15.1.2
Node: 18.19.1
Package Manager: npm 9.7.2
OS: win32 x64

Angular: 15.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.2
@angular-devkit/build-angular   15.1.2
@angular-devkit/core            15.1.2
@angular-devkit/schematics      15.2.10
@angular/cli                    15.1.2
@nguniversal/builders           15.1.0
@nguniversal/common             15.1.0
@nguniversal/express-engine     15.1.0
@schematics/angular             15.2.10
rxjs                            7.5.5
typescript                      4.9.4
```

### Anything else relevant?

Is there any way that I can know the reason that the files are not being generated? No error or message is thrown.

**Comment by alan-agius4** [comment]
Hi @guilhermebentomarques, it's unclear what problem you're experiencing as we lack sufficient information to reproduce it accurately.

I recommend updating to the latest stable version, as significant changes have been made since version 15. If the issue persists, please consider opening a new issue with a minimal reproduction. To create a minimal reproduction, generate a new app using ng new repro-app and add the minimum necessary code to demonstrate the problem. Then, push this repository to GitHub and share the link here.

**Comment by guilhermebentomarques** [comment]
@alan-agius4 Thank you for the response. Is there any way that I can add something like "--verbose" to the prerender command to understand what is going on in the process? We can't update to the latest version of angular yet in this app. 

Thank you.

**Comment by alan-agius4** [comment]
You can add  `"verbose": true` to the server build section in your `angular.json`. However, I'm skeptical that this will be beneficial in this particular case.

Are any errors displayed at the top and Is the build existing with a non zero error code?
