### ISSUE TITLE
Make File Replacements work for all file types

### ISSUE THREAD

**Issue by shadow1349** [angular/angular-cli#27236]
### Command

build

### Description

I had an issue open in NX: https://github.com/nrwl/nx/issues/22000 regarding File Replacements not working for SCSS files. I understand this is by design for some reason, but it's extremely restrictive. I have certain workflows that would benefit from being able to replace all different types of files.

### Describe the solution you'd like

I'd love to be able to do file replacements with SCSS files or any type of file other than TS/JS files.

**Comment by alan-agius4** [comment]
Hi @shadow1349, thanks for opening this feature request. Following a convocation with @clydin we believe that in the long run it’s best to keep file replacements only for TypeScipt source.
