### ISSUE TITLE
Referencing fonts with caret inside path no longer possible - NG17 & Vite

### ISSUE THREAD

**Issue by weihsma** [angular/angular-cli#27239]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

# Referencing fonts with caret inside path no longer possible 
## Current situation

We have a angular libary which includes the Roboto fonts and the necessary font-face definition:
// folder structure:
```
|── lib-name
│   ├── assets
│   ├──   ├── fonts
│   ├──   ├──  ├── ...font-files
```

// fonts.scss
```
  @font-face {
    font-family: Roboto;
    font-weight: 400;
    font-style: normal;
    src: local('Roboto-Regular'), local('RobotoRegular'), url('**^**./assets/fonts/Roboto-Regular');
  }
```
  
We have this caret for a reason: teams consuming the library do deploy their applications sometime into subdirectories, so this caret was needed to resolve the path correctly.

// angular.json
  ````
{
    aplication: {
    architect: {
       "build": {
          "builder": "@angular-devkit/build-angular:browser-esbuild",
          "options": {
            "assets": [
            ...
              {
                "glob": "**/*",
                "input": "dist/lib-name/assets/",
                "output": "assets/"
              },
          }
    }          
}
``````

# After the upgrade to NG17 and vite builder  
Using the caret inside the font path is no longer possible (see provided error below). 

This leads to the issue that angular trys to load the fonts from **http://servername/assets/fonts** with the **base href value** being "/subfolder/smth/". 
All the necessary JS files are being loaded from the correct path: 
http://servername/subfolder/smth/main.hash.js 
but the font path does not change accordingly: 
http://servername/assets/fonts

These are the options I tried when going through a lot of issues & posts:

- **only tilde** in front of the path                       => url("~assets/fonts/Roboto-Regular");
- **tilde with slash** in front of the path              =>url("~/assets/fonts/Roboto-Regular");
- **dots** in front of the path                               => url("./assets/fonts/Roboto-Regular");
- **caret with absolute path in SCSS variable**    => url($varName + "/Roboto-Regular");       varName: '^./assets/fonts'
- wanted to write the baseHref value into a CSS-variable and use this inside the path: https://angular.io/api/common/LocationStrategy#getBaseHref

So my questions are: 
How can fonts be referenced, when the angular app is inside subdirectories?
Where can i find the  `externalDependencies` option the error message is pointing out?

Thanks in advance :)

P.S. i will try to provide a link to a repo, where this error occurs - but sadly i do have issues with my local right now which im trying to solve at the moment

### Please provide the exception or error you saw

```true
X [ERROR] Could not resolve "^./assets/fonts/Roboto-Regular" [plugin angular-css-resource]                            
                                                                                                                   
    apps/application/src/styles.scss:1806:60:                                                                    
      1806 │ ..., local("RobotoRegular"), url("^./assets/fonts/Roboto-Regular");
           ╵                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can remove the caret and add the path to the `externalDependencies` build option, which should remove this error.
Preprocessor stylesheets may not show the exact file location of the error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.1.1
Node: 21.1.0 (Unsupported)
Package Manager: npm 10.2.0
OS: win32 x64

Angular: 17.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, material, material-date-fns-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.1
@angular-devkit/build-angular   17.1.1
@angular-devkit/core            14.2.12
@angular-devkit/schematics      14.2.12
@schematics/angular             17.1.1
ng-packagr                      17.1.2
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

**Comment by alan-agius4** [comment]
The `externalDependencies` options is available in the build section of the `angular.json`. See: https://angular.io/cli/build

**Comment by weihsma** [comment]
> The `externalDependencies` options is available in the build section of the `angular.json`. See: https://angular.io/cli/build

I am shocked that i was to blind to find that option.. i knew it should be available for angular.json. Thanks for the guidance ;)

**Comment by weihsma** [comment]
> Tildes and carets are Webpack resolver features, which can no longer be used when using the application/esbuild builder. #27170 implements a migration that lands in 17.3 to update those import paths.

Thanks for the information, good to know that the fix is planned for 17.3.0 :) Appriciate your fast feedback

**Comment by weihsma** [comment]
> Tildes and carets are Webpack resolver features, which can no longer be used when using the application/esbuild builder. #27170 implements a migration that lands in 17.3 to update those import paths.

Hey once again @JoostK, 
i update to version 17.3.0 last week and i am still facing my reported issues. Are these change included in version 17.3.0 or are planned to be added in one of the upcoming minor versions?

Thanks in advance

**Comment by JoostK** [comment]
The migration in #27170 was part of 17.3, but it's not a fix per se; it requires running `ng update` to actually modify the application's source code.

**Comment by weihsma** [comment]
Hi @JoostK, thanks for your quick reply once again - sadly the issue still persists.

We did run the ng update command and have the version 17.3.0 installed, but it is still not possible to have a relative font-path in SCSS files.

Things we tryed:
- running ng update to 17.3.0 in current project
- using different NG 16 project, running ng update to 17.3.0 and switching to VITE builder
- creating new application and only adding font import to styles.scss file with **^./** path definition 
- added externalDependencies array and tested around with several paths. Should this be a folder or a file?
- we also added includePaths for the fontfiles in stylePreprocessorOptions although this is supposed to include scss files, right?

Could you provide me a step-by-step list of what i need to do to make it work? Sorry to bother you

**Comment by JoostK** [comment]
Oh, I see... #27170 only affects import specifiers, not `url`s.

I don't know what the `^` is supposed to do in Webpack, but it seems to make it output the module specifier verbatim without bundling it. That is what the `externalDependencies` is for for non-Webpack builds (the Webpack behavior is non-standard), so I suppose you'd need to include the exact module specifier in `externalDependencies` (i.e. the path within the `url`). These are educated guesses though as I have never dealt with `^` paths and/or `url` paths.
