### ISSUE TITLE
Do not use Karma via ng new

### ISSUE THREAD

**Issue by melroy89** [angular/angular-cli#27244]
### Command

new

### Description

Stop generating a Karma example framework via `ng new`. Karma is officially deprecated: https://github.com/karma-runner/karma?tab=readme-ov-file#karma-is-deprecated-and-is-not-accepting-new-features-or-general-bug-fixes

Currently `ng new` still seems to add packages like `karma`, `karma-jasmine` and more. And also use this configuration in `angular.json` by default.

### Describe the solution you'd like

Use another test framework, which is at least not deprecated. Like Jest maybe:

```
        "test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "tsConfig": "tsconfig.spec.json",
            "assets": ["src/assets", "src/favicon.ico"],
            "styles": ["src/styles.scss"],
            "scripts": []
          }
        },
```

**Comment by alan-agius4** [comment]
Hi @melroy89, thanks for this issue! 

We definitely want to get to this as soon as the Jest and Web Test Runner builders move out of the experimental phase.  In the meantime, let's keep an eye on a related issue #25854.
