### ISSUE TITLE
Module generation fails to create component for multi-word module names

### ISSUE THREAD

**Issue by Meligy** [angular/angular-cli#2724]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

macOS Sierra

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17
node: 6.7.0
os: darwin x64

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

```
ng new GreatApp
cd GreatApp
ng g module TwoWords
```

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing module
  create src/app/two-words/two-words.module.ts
installing component
Invalid path: "/Users/Meligy/Code/temp/GreatApp/src/app/TwoWords"" is not a valid path.
```

### Mention any other details that might be useful.

**[UPDATED]**

* Notice how generating the app worked even though `GreatApp` consists of 2 words
* Single-word names work just fine (ex: `ng g module Word`)
* Generating TwoWords components directly works just fine too (ex: `ng g component TwoWords`)
* Adding `--routing` to `ng new` and/or `ng g module` makes no difference
* I have also tested with latest linked CLI with no luck

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
@Brocco can you have a look?
