### ISSUE TITLE
Feature: add 'testDir' option to @angular-devkit/build-angular:web-test-runner 

### ISSUE THREAD

**Issue by halpneun** [angular/angular-cli#27273]
### Command

test

### Description

Right now [testDir](https://github.com/angular/angular-cli/blob/f452589e2c921448b76a138a5f34ba92ad05e297/packages/angular_devkit/build_angular/src/builders/web-test-runner/index.ts#L44C5-L44C37) is hardcoded, which is fine for a repository with a single angular application. But in a monorepo setup, when executing tests in parallel this does not work.

### Describe the solution you'd like

Provide a 'testDir' option

**Comment by alan-agius4** [comment]
Support for monorepos will be included in future updates. However, offering testDir as an option is not within scope.
