### ISSUE TITLE
feat(@angular/cli): add changeDetection flag for ng new

### ISSUE THREAD

**Issue by HaidarVladyslav** [angular/angular-cli#27298]
### Command

new

### Description

I think it would be good if we can configure changeDetection for components during project creation

**Comment by alan-agius4** [comment]
Hey @HaidarVladyslav, the adjustment needed for the initial component seems minor, so adding another option might be unnecessary. Additionally, you could consider using `ng config schematics.@schematics/angular:component.changeDetection OnPush` as an alternative.
