### ISSUE TITLE
@ngtools/webpack leaks TypeScript to subsequent loaders

### ISSUE THREAD

**Issue by bytenik** [angular/angular-cli#2730]
I've created a GitHub repository with a reproduction: https://github.com/bytenik/ngtools-webpack-babel

The repository is a nearly identical clone of your e2e test for @ngtools/webpack, except that I have installed babel-loader, added it into the webpack loaders in the config, and switched the tsconfig.json to target es2015. That last part actually doesn't matter -- this breaks even when targeting es5, but its hard to justify installing babel if you don't also have es2015 being spit out to babel. 😄 

You'll see that babel starts producing errors on the ngfactory TypeScript files. However, babel shouldn't be receiving those files, but rather it should only be receiving compiled JS from you.

**Comment by jquince** [comment]
The way I read the documentation on loaders you have the order reversed in your configuration.
You have 
  `{ test: /\.ts$/, loaders: ['@ngtools/webpack', 'babel-loader'] }`
Should be
 ` { test: /\.ts$/, loaders: ['babel-loader', '@ngtools/webpack' ] }`

See [Webpack Loaders](https://webpack.github.io/docs/using-loaders.html#usage)

**Comment by filipesilva** [comment]
Closing as answered by @jquince, thanks!
