### ISSUE TITLE
ng doc <keyword> update

### ISSUE THREAD

**Issue by thiryj** [angular/angular-cli#2731]
> ## Please provide us with the following information:
### OS?

Windows 10 ver 1607
### Versions.

angular-cli: 1.0.0-beta.17
node: 4.5.0
os: win32 x64
### Repro steps.

from terminal type: 'ng doc keyword'
### The log given by the failure.

result is browser (chrome Version 53.0.2785.143 m) does not display the desired doc page referenced by 'keyword'.  instead browser displays generic API reference page.  
### Mention any other details that might be useful.

Proposed fix:  change line 6 of packages/angular-cli/tasks/doc.ts 
from (broken)
const searchUrl = `https://angular.io/docs/ts/latest/api/#!?apiFilter=${keyword}`;
to (working)
const searchUrl = `https://angular.io/docs/ts/latest/api/#!?apiFilter=${keyword}&query=${keyword}`;

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
Good catch! Would you be willing to submit a PR to fix it? I'd review it.

**Comment by thiryj** [comment]
Ok – will give it a shot.

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/3383
