### ISSUE TITLE
Missing node_modules/@angular/cdk/bundles

### ISSUE THREAD

**Issue by Shilpa1TR** [angular/angular-cli#27315]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

angular 7

### Description

We are using angular 16 and trying to run script npm install in cmd prompt
node_modules are creating but inside node_modules/@angular/cdk bundles folder is missing and even scr folder and few other files are also missing.
Inside **@angular** folder for all the subfolders src folder and index.js file is missing.
Actually for bundling the files we are using gulp where we mapping the files into a single file.
Here we are getting error saying ./bundles/cdk-a11y.umd.js not found.
Please help us to resolve this issue.
**gulpfile.js**
"node_modules/@angular/cdk": {
                main: './bundles/cdk.umd.js',
                map: {
                    "./a11y": "./bundles/cdk-a11y.umd.js",
                    "./accordion": "./bundles/cdk-accordion.umd.js",
                    "./bidi": "./bundles/cdk-bidi.umd.js",
                    "./coercion": "./bundles/cdk-coercion.umd.js",
                    "./collections": "./bundles/cdk-collections.umd.js",
                    "./drag-drop": "./bundles/cdk-drag-drop.umd.js",
                    "./keycodes": "./bundles/cdk-keycodes.umd.js",
                    "./layout": "./bundles/cdk-layout.umd.js",
                    "./observers": "./bundles/cdk-observers.umd.js",
                    "./overlay": "./bundles/cdk-overlay.umd.js",
                    "./platform": "./bundles/cdk-platform.umd.js",
                    "./portal": "./bundles/cdk-portal.umd.js",
                    "./scrolling": "./bundles/cdk-scrolling.umd.js",
                    "./stepper": "./bundles/cdk-stepper.umd.js",
                    "./table": "./bundles/cdk-table.umd.js",
                    "./text-field": "./bundles/cdk-text-field.umd.js",
                    "./tree": "./bundles/cdk-tree.umd.js"
                }
            },

Please find the below Screenshot of angular 7 and angular 16
angular 7 :
![image](https://github.com/angular/angular-cli/assets/106945958/a4db76b5-5237-4435-ab4c-944f67292148)
angular 16 :
![image](https://github.com/angular/angular-cli/assets/106945958/4eb84c8a-9a0c-4556-8969-b7c1c26410ef)

### Minimal Reproduction

Used below code for npm install

<exec executable="cmd" dir="ng16" failonerror="true">
            <arg value="/c"/>
            <arg value="antnpm.bat install"/>
        </exec>
Below are he tsconfig and package json files
**tsconfig.json**
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
     "target": "es2018",
    "module": "node16",
    "useDefineForClassFields": false,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": ["node"],
    "lib": [
      "es2020",
      "dom"
    ]
    
  },"include": [
    "app/**/*", "src/**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "angularCompilerOptions": {
    "disableTypeScriptVersionCheck": true,
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true,
    "trace": true
  }
}

**package.json**

{
  "name": "xyz",
  "version": "0.0.0",
  "scripts": {},
  "private": true,
  "license": "UNLICENSED",
  "description": "Workflow UI", 
"dependencies": {
    "@angular/cdk": "16.2.12",
    "@angular/material": "16.2.12",
    "lodash": "4.17.21"
  },
  "devDependencies": {
    "@angular/animations": "16.2.12",
    "@angular/common": "16.2.12",
    "@angular/compiler": "16.2.12",
    "@angular/core": "16.2.12",
    "@angular/forms": "16.2.12",
    "@angular/platform-browser": "16.2.12",
    "@angular/platform-browser-dynamic": "16.2.12",
    "tslib": "^2.5.0",
    "rxjs": "^7.4.0",
    "systemjs": "0.21.5",
    "@angular/compiler-cli": "16.2.12",
    "@types/node": "^16.18.90",
    "@types/lodash": "4.14.202",
    "typescript": "~4.9.3",
    "zone.js": "~0.13.0",    
    "gulp-clean-css": "^4.2.0",
    "gulp-concat": "2.6.1"
  }
}

### Exception or Error

```text
Failure combining vendor level dependenciesError: Error on fetch for node_modules/@angular/cdk/bundles/cdk.umd.js
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.0.6
Node: 16.16.0
Package Manager: npm 8.11.0
OS: win32 x64

Angular: 16.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.12
@angular-devkit/build-angular   16.2.12
@angular-devkit/core            16.2.12
@angular-devkit/schematics      16.0.6
@angular/cdk                    16.2.14
@angular/cli                    16.0.6
@angular/material               16.2.14
@schematics/angular             16.0.6
rxjs                            7.8.1
typescript                      4.9.3
```

### Anything else relevant?

No.

**Comment by alan-agius4** [comment]
The UMD bundles have been removed from the Angular packages a number of major version ago. Angular packages are now distributed in ESM only.
