### ISSUE TITLE
Angular upgrade: ng update command not referring to directory level package.json file

### ISSUE THREAD

**Issue by umesh111111** [angular/angular-cli#27310]
### Command

update

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hi Team,
**My folder structure is like this.**

Projects
   - Lib1
       : package.json
   - Lib2
       : package.json
   - Lib3
        : package.json
        
Src
  - package.json
 

 I wanted to upgrade whole(All the package.json file) angular project from 9 to 10
 
 When I execute command __ng update @angular/core@10 @angular/cli@10__  from directory level Lib1 it is still referring to root level package.json file
 I want to start upgradation from Lib1, Lib2, Lib3 but _ng update_ only referring to root level package.json file (Able to upgrade root level project package.json but not child)
 
 Please let me know your thoughts on this.

### Minimal Reproduction

**Outer level angular.json file**

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "declare-angular-lib-app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {
        "@schematics/angular:component": {
          "style": "sass"
        }
      },
      "i18n": {
        "sourceLocale": "en-US",
        "locales": {
          "hi": "src/locale/messages.hi.xlf",
          "es": "src/locale/messages.es.xlf"
        }
      },
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/declare-angular-lib-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest",
              "src/web.config"
            ],
            "styles": [
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fontawesome.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-regular.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-brands.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-solid.css",
              "node_modules/ngx-toastr/toastr.css",
              "src/themes.sass",
              "src/styles.sass"
            ],
            "scripts": [
              "node_modules/exceljs/dist/exceljs.min.js"
            ],
            "serviceWorker": true,
            "aot": true,
            "extractLicenses": true,
            "vendorChunk": false,
            "buildOptimizer": true,
            "ngswConfigPath": "ngsw-config.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "ngswConfigPath": "ngsw-config.json",
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "10mb"
                }
              ],
              "serviceWorker": true,
              "scripts": [
                "node_modules/exceljs/dist/exceljs.min.js"
              ]
            },
            "es": {
              "localize": ["es"],
              "main": "src/locale/messages.es.xlf",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "ngswConfigPath": "ngsw-config.json",
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "10mb"
                }
              ],
              "serviceWorker": true,
              "scripts": [
                "node_modules/exceljs/dist/exceljs.min.js"
              ]
            },
            "es-debug": {
              "localize": ["es"],
              "scripts": [
                "node_modules/exceljs/dist/exceljs.min.js"
              ]
            },
            "hi": {
              "localize": ["hi"],
              "main": "src/locale/messages.hi.xlf",
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "ngswConfigPath": "ngsw-config.json",
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "10mb"
                }
              ],
              "serviceWorker": true,
              "scripts": [
                "node_modules/exceljs/dist/exceljs.min.js"
              ]
            },
            "hi-debug": {
              "localize": ["hi"],
              "scripts": [
                "node_modules/exceljs/dist/exceljs.min.js"
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "declare-angular-lib-app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "declare-angular-lib-app:build:production"
            },
            "hi":{
              "browserTarget": "declare-angular-lib-app:build:hi-debug"
            },
            "es":{
              "browserTarget": "declare-angular-lib-app:build:es-debug"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "declare-angular-lib-app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "node_modules/ngx-toastr/toastr.css",
              "src/themes.scss",
              "src/styles.sass"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets",
              "src/manifest.webmanifest",
              "src/web.config"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "declare-angular-lib-app-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "prefix": "",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "declare-angular-lib-app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "declare-angular-lib-app:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "declare-angular-base": {
      "root": "projects/declare-angular-base",
      "sourceRoot": "projects/declare-angular-base/src",
      "projectType": "library",
      "prefix": "mw",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/declare-angular-base/tsconfig.lib.json",
            "project": "projects/declare-angular-base/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/declare-angular-base/tsconfig.lib.prod.json"
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/declare-angular-base/src/test.ts",
            "tsConfig": "projects/declare-angular-base/tsconfig.spec.json",
            "karmaConfig": "projects/declare-angular-base/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/declare-angular-base/tsconfig.lib.json",
              "projects/declare-angular-base/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "declare-angular-security": {
      "root": "projects/declare-angular-security",
      "sourceRoot": "projects/declare-angular-security/src",
      "projectType": "library",
      "prefix": "mw",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/declare-angular-security/tsconfig.lib.json",
            "project": "projects/declare-angular-security/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/declare-angular-security/tsconfig.lib.prod.json"
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/declare-angular-security/src/test.ts",
            "tsConfig": "projects/declare-angular-security/tsconfig.spec.json",
            "karmaConfig": "projects/declare-angular-security/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/declare-angular-security/tsconfig.lib.json",
              "projects/declare-angular-security/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "declare-angular-metamodel": {
      "root": "projects/declare-angular-metamodel",
      "sourceRoot": "projects/declare-angular-metamodel/src",
      "projectType": "library",
      "prefix": "mw",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/declare-angular-metamodel/tsconfig.lib.json",
            "project": "projects/declare-angular-metamodel/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/declare-angular-metamodel/tsconfig.lib.prod.json"
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/declare-angular-metamodel/src/test.ts",
            "tsConfig": "projects/declare-angular-metamodel/tsconfig.spec.json",
            "karmaConfig": "projects/declare-angular-metamodel/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/declare-angular-metamodel/tsconfig.lib.json",
              "projects/declare-angular-metamodel/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "declare-angular-list": {
      "root": "projects/declare-angular-list",
      "sourceRoot": "projects/declare-angular-list/src",
      "projectType": "library",
      "prefix": "mw",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/declare-angular-list/tsconfig.lib.json",
            "project": "projects/declare-angular-list/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/declare-angular-list/tsconfig.lib.prod.json"
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/declare-angular-list/src/test.ts",
            "tsConfig": "projects/declare-angular-list/tsconfig.spec.json",
            "karmaConfig": "projects/declare-angular-list/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/declare-angular-list/tsconfig.lib.json",
              "projects/declare-angular-list/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "declare-angular-lookup": {
      "root": "projects/declare-angular-lookup",
      "sourceRoot": "projects/declare-angular-lookup/src",
      "projectType": "library",
      "prefix": "mw",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/declare-angular-lookup/tsconfig.lib.json",
            "project": "projects/declare-angular-lookup/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/declare-angular-lookup/tsconfig.lib.prod.json"
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/declare-angular-lookup/src/test.ts",
            "tsConfig": "projects/declare-angular-lookup/tsconfig.spec.json",
            "karmaConfig": "projects/declare-angular-lookup/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/declare-angular-lookup/tsconfig.lib.json",
              "projects/declare-angular-lookup/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "declare-angular-dashboard": {
      "root": "projects/declare-angular-dashboard",
      "sourceRoot": "projects/declare-angular-dashboard/src",
      "projectType": "library",
      "prefix": "mw",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-ng-packagr:build",
          "options": {
            "tsConfig": "projects/declare-angular-dashboard/tsconfig.lib.json",
            "project": "projects/declare-angular-dashboard/ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "projects/declare-angular-dashboard/tsconfig.lib.prod.json"
            }
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "projects/declare-angular-dashboard/src/test.ts",
            "tsConfig": "projects/declare-angular-dashboard/tsconfig.spec.json",
            "karmaConfig": "projects/declare-angular-dashboard/karma.conf.js"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "projects/declare-angular-dashboard/tsconfig.lib.json",
              "projects/declare-angular-dashboard/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "declare-angular-lib-app",
  "cli": {
    "analytics": false
  }
}

### Your Environment

```text
Global level angular CLI version : 17.3.0
Directory level : 17.3.0   
node version: v18.19.0

Note: Tried with globally and directory level with 10 CLI version too
```

**Comment by alan-agius4** [comment]
This expected because within an Angular CLI workspace, the `package.json` situated alongside the `angular.json` contains the development dependencies. The child `package.json` should not contain any of such dependencies.

**Comment by umesh111111** [comment]
Thank you for the quick response.
Then if I want to upgrade all the libraries Lib1, Lib2 from 9 to 10 then what is the best approach to do this?
