### ISSUE TITLE
ng build with the --watch flag applied makes it difficult to `npm link` as the the package version numbers dynamically change

### ISSUE THREAD

**Issue by robert-seymour-numerated** [angular/angular-cli#27320]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

every time `ng build --watch` rebuilds it updates the `package.json` with a dynamic version number (such as `"version": "0.0.0-watch+1710960420817"`).  Since `npm link` relies on `package-name@version`. I need to rerun `npm link my-package` after every build change to resync the link.  

example `npm list -g`
```
/Users/user/Library/Application Support/fnm/node-versions/v16.19.0/installation/lib
├── @angular/cli@7.3.3
├── @easternlabs/my-package@0.0.0-watch+1710958215295 -> ./../../../../../../../Projects/my-package/dist/my-package
├── corepack@0.15.1
└── npm@8.19.3
```
and after a build change and rerunning `npm link`
```
/Users/user/Library/Application Support/fnm/node-versions/v16.19.0/installation/lib
├── @angular/cli@7.3.3
├── @easternlabs/my-package@0.0.0-watch+1710959179214 -> ./../../../../../../../Projects/my-package/dist/my-package
├── corepack@0.15.1
└── npm@8.19.3
```
notice the version number has changed after re-linking

### Minimal Reproduction

- `ng build --watch` a library
- in a separate repo `npm link` your new package
- cause a rebuild in the library
- see that the changes are not reflected
- re run `npm link` for your new package
- see the changes are reflected

### Your Environment

```text
CLI: 14.2.10
Node: 16.19.0
Package Manager: npm 8.19.3 
OS: darwin x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.7
@angular/cli                    14.2.10
@angular/material               14.2.7
@schematics/angular             14.2.10
ng-packagr                      14.2.2
rxjs                            6.6.7
typescript                      4.6.4
```

**Comment by JoostK** [comment]
This is intentional, as without the version change the bundler would have a cache hit instead of rebundling with the changes.

I tried to replicate this and my NPM installation does not work like you describe; `npm link` creates a symlink in the global `node_modules` tree _without_ version specifier. I also cannot find anything in NPM's documentation, it never mentions the version number.

Please also note that both Angular 14 and Node 16 are unsupported.

**Comment by alan-agius4** [comment]
Closing as per @JoostK comment.

**Comment by robert-seymour-numerated** [comment]
Appreciate the quick reply, I think my issue actually may be a result of `https://github.com/angular/angular-cli/pull/16153` I'd like to watch changes in node_modules (was able to force expected behavior by triggering an unrelated reload in my angular app).  Is there a flag for `ng build` to re-enable watching node_modules (or a specific folder under node_modules preferably)?

**Comment by alan-agius4** [comment]
@robert-seymour-numerated, unless you are using polling explicitly node_modules should be watched.

It's important to mention that you're using version 14, which was last released in 2022 and is now unsupported. Many changes have occurred since then.
