### ISSUE TITLE
Using build artifacts as dependency

### ISSUE THREAD

**Issue by vlio20** [angular/angular-cli#2732]
Is there any way to use the build artifacts in other angular-cli project?
For example, I created project "A" built it and published. Then I have created project "B" and added A to its dependencies (node_modules).  
Currently this is the artifacts of project A:
[![111.png](https://s13.postimg.org/t74fnooyf/111.png)](https://postimg.org/image/f0oosge37/)
Lets say that Project A has some components I want to use in project B, how can I do it - is it even possible with the current cli version?

**Comment by Meligy** [comment]
Hello.
You might want to see my reply to a similar issue here https://github.com/angular/angular-cli/issues/2722#issuecomment-254035734.

**Comment by Meligy** [comment]
Oops. Sorry. You definitely read that before!

I'll delete the comment.

**Comment by filipesilva** [comment]
I don't have any specific support for that, no. The recommended approach would be to create a third project, like a library, that both apps depended on.

**Comment by BernhardRode** [comment]
I think building libraries is totally missing at the moment. We should try to get "ng release" command which npm releases a package that can be consumed easily by others.

Or did I miss something?!?

**Comment by filipesilva** [comment]
@BernhardRode that's being tracked in https://github.com/angular/angular-cli/issues/1692.
