### ISSUE TITLE
Angular 17 custom library issue

### ISSUE THREAD

**Issue by anushabalmane007** [angular/angular-cli#27326]
### Command

other

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

I have created my own custom library in angular 17, in that there are buttons with different sizes , and i am using this library in other project, as whole if i use the project the styles are properly effecting, but when i use single button with size='small' or 'medium' the styles are not visible

### Minimal Reproduction

1. create library with different compo or directives
2. use the library build in other project
3. create a button or whatever directive you have created with specific classes .
4. it will not effect in the other project after rebuilding also

### Your Environment

```text
17.2.0
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided. If the problem persists please open a new issue with a minimal reproduction.
