### ISSUE TITLE
Cannot import mapbox worker with application builder

### ISSUE THREAD

**Issue by BouckaertThibault** [angular/angular-cli#27378]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In the browser builder with webpack I was able to use
`workerClass: require("worker-loader!../../node_modules/mapbox-gl/dist/mapbox-gl-csp-worker").default,`
to import a worker. Using the new application builder I was using vite's way to import a worker which was through
```
import MapboxGLWorker from "mapbox-gl/dist/mapbox-gl-csp-worker?worker";
workerClass: MapboxGLWorker
```

This works but only when using the development server (ng serve). Building the application with `ng build` or when serving with the `--prebundle=false` argument results in a `main.ts:5 ERROR TypeError: ug.workerClass is not a constructor` error in the browser

I then came accross [this issue](https://github.com/angular/angular-cli/issues/27323) which was similar so I tried the `new Worker()` method which still results in the same error.

### Minimal Reproduction

1. Clone https://github.com/BouckaertThibault/angular-17-mapbox-csp (a dummy access token is already provided)
2. npm install
3. ng serve --prebundle=false

### Exception or Error

```text
ERROR TypeError: ug.workerClass is not a constructor
    at new hg (mapbox-gl-csp.js:3:304799)
    at WorkerPool.acquire (mapbox-gl-csp.js:3:305062)
    at new Dispatcher (mapbox-gl-csp.js:3:284920)
    at new Style (mapbox-gl-csp.js:3:693886)
    at Map._updateStyle (mapbox-gl-csp.js:3:828788)
    at Map.setStyle (mapbox-gl-csp.js:3:828538)
    at new Map (mapbox-gl-csp.js:3:818918)
    at _AppComponent.<anonymous> (app.component.ts:22:16)
    at Generator.next (<anonymous>)
    at main.js:72:61
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.3.2
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.3.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@angular/cli                    17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

**Comment by clydin** [comment]
mapbox appears to want a factory instead of an instance of a worker for the `workerClass` field.
Something similar to the following may be needed:
```
    mapboxgl.workerClass = function() { return new Worker(new URL('./mapbox.worker', import.meta.url)); };
```

**Comment by alan-agius4** [comment]
Closing as per above.
