### ISSUE TITLE
esmodule with .<folder name> causes ng serve to not execute

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular-cli#27384]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

When using a folder with a dot (.) prefix e.g. .shared it makes it so that the esmodule dose not rerender the application and therefor the changes are not adjusted. I believe it kind of messe the hole file change detection for Angular but I have not tested it that much to be 100% sure. I had wierd behavior.

### Please provide the exception or error you saw

```true
Simply its not rerending the changed value from the service. Nothing happens, this was hard to track down and be sure whats the issue cause I was using quit a big project. 
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.2
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 17.3.2
... cli, common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

### Anything else?
Not sure if thats the behavior how it should be but with webpack this was working. Someone might encounter it and its not backwards compatible so heads up.

**Comment by muhamedkarajic** [comment]
> I think there was some confusion, as you're talking about the file watching that `ng serve` does, not Angular's change detection. I'm going to transfer this over to our CLI team as `ngc` itself isn't responsible for file watching usually.

Sorry my bad, not sure how to properly 'word' it. I hope it was not a total waste of time. I wanted to point out this issue if someone encounters it that he knows it might be cause of that.

**Comment by alan-agius4** [comment]
It's anticipated that hidden directories, designated with a leading `.` in their names, aren't monitored for changes. This is due to the conventional usage of hidden directories for storing configuration files or system-related data that users generally don't need to directly interact with. Consequently, excluding these directories from monitoring helps prevent unnecessary cluttering of the monitoring process with updates that may not be relevant.
