### ISSUE TITLE
Angular wont reload after making any change

### ISSUE THREAD

**Issue by dombrga** [angular/angular-cli#27391]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Hello.

I am using WSL2 ubuntu to make an angular app.

The app does not reload after I make any change in any file.
<img width="360" alt="image" src="https://github.com/angular/angular-cli/assets/84841255/d2b3cb4e-45e1-4e1c-95e2-d6a6eca70e01">

But when I delete package-lock and node_modules, and run npm install again in Windows and not in WSL2, and run the app then make a change, it works perfectly fine.

Thank you!

### Minimal Reproduction

1. In wsl2, I installed angular cli by npm i -g @angular/cli
2. ng new <project-name>
3. npm run start/ng serve
4. The app runs, but when I make a change in the title property in the app.component.ts file, the changes do not reflect automatically.
<img width="337" alt="image" src="https://github.com/angular/angular-cli/assets/84841255/921ba5fe-d04e-4fb8-9522-67bc94ac7022">
<img width="896" alt="image" src="https://github.com/angular/angular-cli/assets/84841255/1c2e1271-6788-452c-9d39-876fc9068ff3">
<img width="813" alt="image" src="https://github.com/angular/angular-cli/assets/84841255/18078509-192c-4c55-9b20-ddcf329a6ed1">

The terminal just always looks like this whenever I make a change in html or ts files. No error in browser console as well.

### Exception or Error

```text
None.
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.2
Node: 20.11.1
Package Manager: npm 10.2.4
OS: linux x64

Angular: 17.3.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
```

### Anything else relevant?

I am using
1.  wsl2 ubuntu
2. visual studio code
3. microsoft edge browser

I just want to reiterate that it works perfectly fine on Windows (after deleting node_modules and package-lock file and doing npm i) and not on wsl2.

Thank you!

**Comment by alan-agius4** [comment]
This issue has surfaced previously, and it appears that Angular CLI might not be the culprit; instead, it seems to be a bug within WSL2. For further details, you can refer to the discussion here: https://github.com/microsoft/WSL/issues/4739
