### ISSUE TITLE
ng build consume too much memory

### ISSUE THREAD

**Issue by ankitjilka** [angular/angular-cli#27392]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when I run `ng build` command it occupy around 4 to 8 GB which is too high for me

### Minimal Reproduction

I'm unable to share details about reproduction as it involves sensitive data

### Exception or Error

```text
- If I not allocate more memory to node process it give me below error

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

1: 0xb6d470 node::Abort() [ng build --project=ER --base-href=./ --configuration=dev]

2: 0xa7e0a8 [ng build --project=ER --base-href=./ --configuration=dev]
```

### Your Environment

```text
version:
 - angular/cli: 15.0.5
 - node: 18.10.0
```

**Comment by alan-agius4** [comment]
Many updates have been implemented since version 15. Kindly upgrade to the latest stable version. If the issue persists, please create a new ticket and include memory snapshots for reference.

**Comment by ankitjilka** [comment]
@alan-agius4 https://github.com/angular/angular-cli/issues/27412
