### ISSUE TITLE
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory in ng build command

### ISSUE THREAD

**Issue by ankitjilka** [angular/angular-cli#27412]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

when I run `ng build` command it  give me error of heap out of memory.
and when I give more memory using `NODE_OPTIONS="--max-old-space-size=4096"`  env it consume around 4 to 8 GB memory.
- below error comes when I not give more memory using env

### Minimal Reproduction

I'm unable to share details about reproduction as it involves sensitive data

### Exception or Error

```text
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb6d470 node::Abort() [ng build --project=ER --base-href=./ --configuration=dev]
 2: 0xa7e0a8  [ng build --project=ER --base-href=./ --configuration=dev]
```

### Your Environment

```text
version:
 - angular/cli: 17.3.3
 - node: 18.10.0

System:
 - 16 GB RAM
 - 8 core CPU
```

### Anything else relevant?

@alan-agius4  as you suggest https://github.com/angular/angular-cli/issues/27392#issuecomment-2030481220 I am using latest version of @angular/cli and here I attaching snapshot of memory and CPU utilization

![image](https://github.com/angular/angular-cli/assets/76820541/2de2e213-4633-4760-ae56-fc24896347ce) 

I don't want to give more memory using `NODE_OPTIONS="--max-old-space-size=4096"` env. so anybody has solution of above error without giving more memory to process

**Comment by JoostK** [comment]
That's not a snapshot we're looking for. Node's [--heapsnapshot-near-heap-limitmax_count](https://nodejs.org/api/cli.html#--heapsnapshot-near-heap-limitmax_count) flag may be helpful here, where it writes a heap snapshot to disk when an OOM is about to occur.

**Comment by ankitjilka** [comment]
@JoostK When I used `--heapsnapshot-near-heap-limit=max_count` with `ng build` command heap-snapshot file created but It was blank file and `ng build` command not completed

**Comment by alan-agius4** [comment]
@ankitjilka, I'm unsure why the file is empty. Perhaps consider updating the Node.js version? Unfortunately, without the snapshot, we cannot investigate the issue.

**Comment by ankitjilka** [comment]
@alan-agius4 when I ran `npm run build-dev --heapsnapshot-near-heap-limit=1 --verbose ` command I got following error
```
<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb00e10 node::Abort() [ng build --project=ER --base-href=./ --configuration=dev]
 2: 0xa1823b node::FatalError(char const*, char const*) [ng build --project=ER --base-href=./ --configuration=dev]
 3: 0xcee09e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng build --project=ER --base-href=./ --configuration=dev]
 4: 0xcee417 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng build --project=ER --base-href=./ --configuration=dev]
 ```

**Comment by ankitjilka** [comment]
@JoostK  and @alan-agius4  I used `NODE_OPTIONS` for set `--heapsnapshot-near-heap-limit=1` flag but still `npm run build-dev` command not completed and heap snapshot files was empty. also I used node version 20.11.0

**Comment by alan-agius4** [comment]
Are you still getting OOM error when using `heapsnapshot-near-heap-limit`? As that might be the reason why it's empty.

**Comment by ankitjilka** [comment]
@alan-agius4 No, when I'm using `heapsnapshot-near-heap-limit` flag `npm run build-dev` command stuck and not completed and when I'm not using `heapsnapshot-near-heap-limit` flag I getting OOM error.

- here I'm attach output of `npm run build-dev` command when I'm using `heapsnapshot-near-heap-limit` flag and command stuck and not completed
![image](https://github.com/angular/angular-cli/assets/76820541/2b9c0887-67e8-497b-a984-5be8ebe1662a)

**Comment by alan-agius4** [comment]
@ankitjilka, unfortunately without a minimal reproduction or at the very minimum a memory snapshot we will not be able to assist further.

If you are still experiencing the problem please open a new issue with the needed information. Thank you.
