### ISSUE TITLE
Remove enviroment.ts related code from bundle

### ISSUE THREAD

**Issue by mackelito** [angular/angular-cli#27413]
### Command

build

### Description

If I have my environment file
````
export const environment = {
  production: true,
  featureAEnabled: false,
};
````

Then in a component 
````
if (environtment.featureAEnabled) {
// Doing stuff
}
````
This will still be a part of the bundle even do it will never be used, right?

I have little to none knowledge of the compiler so apologies if I'm totally of here :)

### Describe the solution you'd like

If this is never to change, remove it :)

### Describe alternatives you've considered

N/A

**Comment by mackelito** [comment]
@JoostK do you know if there are some more details to read on this topic? 

To me it seems strange not to remove code that will never run in that build. I assume that the reason for it is because of limits in the compiler but I would like to understand why as these case seems rather clear and straight forward :)

**Comment by JoostK** [comment]
Code elimination in these scenarios require code folding (aka inlining) of the condition expression to arrive at `if (false)`, but there are limits to how deep the inlining goes. With the environments file there is an indirection through a module import, which is supposedly too much for the optimizer to fully inline. I don't know the full extent of the inlining process (this is implemented in esbuild) and its limitations.

You may be able to achieve the desired elimination by using the CLI's recently introduced `define` option for the application builder, see #27047. This requires a bare identifier to be used as `if` condition expression as it won't replace expression (just variable names), but you can maybe achieve it with an intermediate variable assignment.
