### ISSUE TITLE
@angular-devkit/build-angular v17.3.3 uses webpack-dev-server v4.15.1 which is scanned as vulnerability

### ISSUE THREAD

**Issue by dashakureru** [angular/angular-cli#27417]
### Command

version

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

webpack-dev-server is scanned as a vulnerability. see reference below.

![image](https://github.com/angular/angular-cli/assets/42427219/69996f65-3b89-462c-8cc3-a063b8d1ad05)

I've already updated @angular-devkit/build-angular to v17.3.3 but it still uses 4.15.1
![image](https://github.com/angular/angular-cli/assets/42427219/4dd5b091-4bbc-400e-8548-3dc52d43cfcd)
![image](https://github.com/angular/angular-cli/assets/42427219/9a58ac19-3d43-4a14-9c90-c56397e2a41b)

I've also tried npm audit fix, it didn't work.

### Minimal Reproduction

use @angular-devkit/build-angular to v17.3.3 and it will install v4.15.1

### Your Environment

```text
Angular CLI: 17.3.3
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@angular/cdk                    16.2.14
@angular/material               16.2.14
@schematics/angular             16.2.13
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Hi, this is a duplicate of #27334.
