### ISSUE TITLE
css located in style tag inside of a template is not getting minified

### ISSUE THREAD

**Issue by Den-dp** [angular/angular-cli#27419]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Since `ng new` generates a project with css in <style> tag inside html template 

https://github.com/angular/angular-cli/blob/c0e68e86d4323bb7aae66edd1d1e40b31de3b4ca/packages/schematics/angular/application/files/common-files/src/app/app.component.html.template#L10-L17

so `ng build` results in a js bundle that has not minified CSS block

![image](https://github.com/angular/angular-cli/assets/1770529/97a18824-2800-45a2-8f1c-48ef53679f24)

which presents the framework not in a good light for newcomers who curious about minification capabilities

### Minimal Reproduction

```
ng new ng1733 --style=css
cd ng1733
npm run build
tail dist/ng1733/browser/main-*.js
```

### Exception or Error

```text
> tail dist/ng1733/browser/main-*.js
      width: max-content;
    }

    .divider[_ngcontent-%COMP%] {
      height: 1px;
      width: 100%;
      background: var(--red-to-pink-to-purple-horizontal-gradient);
      margin-block: 1.5rem;
    }
  }`]});let e=t;return e})();Cd(af,sf).catch(e=>console.error(e));
```

### Your Environment

```text
Angular CLI: 17.3.3       
Node: 18.17.1
Package Manager: npm 9.9.2
OS: win32 x64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.4
zone.js                         0.14.4
```

### Anything else relevant?

solutions I see:
* enable minification for such styles if possible
* if not possible - show build time warning (but this might be too obtrusive)
* rewrite demo app to use styles file (might be suboptimal cause it makes getting started experience worse)

**Comment by alan-agius4** [comment]
Thank you for raising this issue.

The current behavior works as intended since styles within the HTML file are not being processed. The main rationale behind incorporating these styles directly into the template is to minimize the number of files requiring deletion when creating a new application.

While as you highlighted there several potential solutions, the current approach is preferred.
