### ISSUE TITLE
Restart Build if changes occur during ng build --watch

### ISSUE THREAD

**Issue by dabasejumper** [angular/angular-cli#27424]
### Command

build

### Description

Just curious if it would be possible to cancel the current build if I change code in the middle of a build. I have a rather large project that takes around 15 seconds to complete. If I make a change in the middle of it, that obviously turns into 30 seconds.

### Describe the solution you'd like

I would love it if it immediately cancelled the current build, and started a new one.

**Comment by alan-agius4** [comment]
At the moment, this isn't possible. While it's a possibility for future implementation, it's not currently on our roadmap.
