### ISSUE TITLE
Cannot find namespace Jasmine

### ISSUE THREAD

**Issue by mangopop** [angular/angular-cli#2743]
### OS?
> Mac OSX ( El Capitan)

### Versions.
angular-cli: 1.0.0-beta.17
node: 6.2.0
os: darwin x64

On fresh project I'm trying to use jasmine, I'm getting Cannot find namespace Jasmine when trying to reference jasmine.spy

I cannot see any typings folder in the folder structure or a typings.json? Not sure how to bring this down again if it failed the first time?

Tried npm run postinstall, typings install. Neither working.

**Comment by mangopop** [comment]
Fixed this by using 

    typings install --global dt~jasmine

Not sure if this is how it's meant to work?

**Comment by filipesilva** [comment]
@mangopop we're using `@types/jasmine` to get typings, it might be your editor that's not yet using typescript 2.0 (needed for @types). You should be able to configure that.
