### ISSUE TITLE
SSR v17 app won't let docker expose application port

### ISSUE THREAD

**Issue by ProjectBay** [angular/angular-cli#27439]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Since Angular v17 and the new ssr update, docker can't expose the applications running port with the serve-target.
When running npx ng serve, logs of the application as well as docker inspect details show that the app is running on the right port and docker listens & exposes it - but the application is not reachable in the browser.

When changing the build target to the old configuration (<=v16) "serve-ssr", it works.

### Minimal Reproduction

I implemented a showcase repository to display the issue:
README: https://github.com/ProjectBay/ng-ssr-docker/tree/main/ssrtest

`git clone https://github.com/ProjectBay/ng-ssr-docker`
`cd ng-ssr-docker`
`pnpm install`
`pnpm run docker-build`
`pnpm run docker-run`

The workaround is in the "fix" branch.
You can inspect the diffs as well as read about it in the readme of that branch.
README: https://github.com/ProjectBay/ng-ssr-docker/tree/fix/ssrtest

`git checkout fix`
`pnpm install`
`pnpm run docker-build`
`pnpm run docker-run`

The application has been generated with a minimal setup through the v17 `ng new` command.

### Exception or Error

```text
No exception or error
```

### Your Environment

```text
Angular CLI: 17.3.3
Node: 18.14.1
Package Manager: pnpm 8.12.1
OS: darwin arm64

Angular: 17.3.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.0.0
@angular-devkit/schematics      17.0.0
@schematics/angular             17.0.0
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

**Comment by alan-agius4** [comment]
You need to make the application accessing externally by using the `--host` option.

```
ng serve --host=0.0.0.0
```
