### ISSUE TITLE
CSS source maps are not created with application builder (Angular 17)

### ISSUE THREAD

**Issue by githubuser578** [angular/angular-cli#27441]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular 16 (browser builder, webpack)

### Description

With the new application builder, the CSS source maps are not generated correctly during `ng serve`.

In Firefox I even get a warning in the console:

`Source map error: Error: request failed with status 404`

![image](https://github.com/angular/angular-cli/assets/131432701/96260925-b37d-487f-b23b-738f7f311a6a)

Result is, that the DEV tools do not point to the correct css source file, e.g.:

![image](https://github.com/angular/angular-cli/assets/131432701/2e968239-3677-49ce-8ade-394338cb3248)

![image](https://github.com/angular/angular-cli/assets/131432701/032f644e-0ba3-4671-9b05-5fb97448f9ef)

### Minimal Reproduction
Tour of Heroes live example from Angular tutorial:
https://stackblitz.com/edit/pgdhl1?file=src%2Fapp%2Fhero-search%2Fhero-search.component.css

- Open DEV-Tools
- Use Element selector to  select `Hero Search` label
- Component styles are marked as "inline" (Firefox) or "<style>" (Chrome)

![image](https://github.com/angular/angular-cli/assets/131432701/8cd2b572-fb60-42e9-b2f1-4df015a48067)

![source_map_error](https://github.com/angular/angular-cli/assets/131432701/f2ebbd06-6eaa-4468-bb07-1cd57e7627d9)

### Exception or Error

Warning (only in Firefox): Source map error: Error: request failed with status 404 

### Your Environment

```text
Angular CLI: 17.2.3
Node: 18.18.0
Package Manager: npm 10.2.3
OS: linux x64

Angular: 17.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.3
@angular-devkit/build-angular   17.2.3
@angular-devkit/core            17.2.3
@angular-devkit/schematics      17.2.3
@angular/cli                    17.2.3
@schematics/angular             17.2.3
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.14.4
```
angular.json:
```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "angular.io-example": {
      "projectType": "application",
      "root": "",
      "sourceRoot": "src",
      "prefix": "app",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:application",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "browser": "src/main.ts",
            "polyfills": ["zone.js"],
            "tsConfig": "tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "500kb",
                  "maximumError": "1mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "2kb",
                  "maximumError": "4kb"
                }
              ],
              "outputHashing": "all"
            },
            "development": {
              "optimization": false,
              "extractLicenses": false,
              "sourceMap": true
            }
          },
          "defaultConfiguration": "production"
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "configurations": {
            "production": {
              "buildTarget": "angular.io-example:build:production"
            },
            "development": {
              "buildTarget": "angular.io-example:build:development"
            }
          },
          "defaultConfiguration": "development"
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "buildTarget": "angular.io-example:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "polyfills": ["zone.js", "zone.js/testing"],
            "tsConfig": "tsconfig.spec.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "angular.io-example:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "angular.io-example:serve:production"
            }
          }
        }
      }
    }
  }
}
```

### Anything else relevant?

In my own application, it seems to work sporadically in Chrome. But in 99% of the cases I don't get any CSS source maps either.

**Comment by alan-agius4** [comment]
I couldn't reproduce this problem on Firefox when using the Angular CLI directly outside of StackBlitz. However, I did encounter it occasionally on Chrome. It appears to be more of a browser issue, as the problem resolves itself when the developer tools are closed and reopened, or when a different element is selected, indicating that the sourcemaps become bound.

For further details, refer to: https://g-issues.chromium.org/issues/40912699
