### ISSUE TITLE
Please add support for Cache Busting

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular-cli#2744]
Angular CLI is pretty great, but I believe the build tool lacks the support for cache bursting.

In order to making sure that the users’ browsers never use old code, there should be an option to append a hash of generated files to the end of file name. This will makes sure that any files that have changed will be fetched freshly from the server and any files that haven’t changed can be loaded safely from the cache.

**Comment by deebloo** [comment]
This already happens when creating a production build

**Comment by splintercode** [comment]
Cache busting is enable by running a production build `ng build --prod` or running `ng serve --prod`

**Comment by filipesilva** [comment]
^ what @deebloo and @splintercode said 💃

**Comment by TIIUNDER** [comment]
Since which version this is working?

**Comment by niteshluharuka** [comment]
Can we have a command to perform cache busting instead of running a prod build?
