### ISSUE TITLE
Could not resolve "zone.js/node"

### ISSUE THREAD

**Issue by its-dibo** [angular/angular-cli#27449]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

I'm using Angular v17 and I got this error when building the app
```

✘ [ERROR] Could not resolve "zone.js/node"

    angular:polyfills-server:angular:polyfills-server:1:7:
      1 │ import 'zone.js/node';
        ╵        ~~~~~~~~~~~~~~

  You can mark the path "zone.js/node" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```

I see this [comment](https://github.com/angular/angular-cli/issues/26508#issuecomment-1828647997)
> There is likely a pnp.cjs file on your computer.

but I searched for such a file (also .pnp.cjs), but there is no such a file in the whole system at all

### Minimal Reproduction

.

### Exception or Error

```text
✘ [ERROR] Could not resolve "zone.js/node"

    angular:polyfills-server:angular:polyfills-server:1:7:
      1 │ import 'zone.js/node';
        ╵        ~~~~~~~~~~~~~~

  You can mark the path "zone.js/node" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.
```
```


### Your Environment

```text
Angular CLI: 17.2.3
Node: 20.10.0
Package Manager: yarn 1.22.22
OS: linux x64

Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1702.3
@angular-devkit/core         17.2.3
@angular-devkit/schematics   17.2.3
@schematics/angular          17.2.3
rxjs                         7.8.1
```

**Comment by alan-agius4** [comment]
Are you running `ng version` inside the workspace as from the output it looks like you have a number of missing packages.

**Comment by its-dibo** [comment]
> Are you running `ng version` inside the workspace

you are absolutely right

```
Angular CLI: 17.3.3
Node: 20.10.0
Package Manager: yarn 1.22.22
OS: linux x64

Angular: 17.3.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.4
```

**Comment by alan-agius4** [comment]
I do see that zone.js installed so I am not quite sure what the problem is. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by its-dibo** [comment]
I carefully investigated the installed versions of zone.js, and I found an old one in the top-level root added by the outdated codelyzer. So, yarn installed the required version inside the project's node_modules rather than using the root one.

Removing codelyzer (replaced by angular-eslint) and the top-level zone.js, and installing the dependencies again solved the issue.

But I still wonder why Angular cannot resolve zone.js/node even though it is installed inside the workspace's node_modules?

**Comment by alan-agius4** [comment]
In an Angular workspace, there should only be a single root level `node_modules` directory. That being said, based on how node resolution work, if there is a nested `node_modules` in project directory this will be preferred over the workspace `node_modules`.

**Comment by its-dibo** [comment]
I have this structure:

monorepo
  - my-angular-workspace
  - other project

now zone.js exists inside my-angular-project/node_modules and removed from the top-level node_modules 
and now the issue occurs again
the packages are installed via pnpm
@alan-agius4
