### ISSUE TITLE
Support webpack-dev-server v5

### ISSUE THREAD

**Issue by pau1foster** [angular/angular-cli#27454]
### Command

build

### Description

Unable to resolve dependency peer webpack-dev-server@"^4.0.0" from @angular-devkit/build-webpack@0.1703.3

npm ERR! Could not resolve dependency:
npm ERR! peer webpack-dev-server@"^4.0.0" from @angular-devkit/build-webpack@0.1703.3
npm ERR! node_modules/@angular-devkit/build-webpack
npm ERR!   dev @angular-devkit/build-webpack@"0.1703.3" from the root project

### Describe the solution you'd like

Add support for webpack-dev-server v5

**Comment by alan-agius4** [comment]
Support for Webpack-dev-server version 5 will be available in version 18. See: https://github.com/angular/angular-cli/pull/27250
