### ISSUE TITLE
headers for dev-server not working anymore after upgrade from angular 16 to 17

### ISSUE THREAD

**Issue by piu130** [angular/angular-cli#27464]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I've created a new angular 17 app with `ng new angular-tour-of-heroes`.
After adding custom headers in angular.json:
```json
"serve" {
  "builder": "@angular-devkit/build-angular:dev-server",
  "options": {
    "headers": {
      "Cross-Origin-Opener-Policy": "same-origin",
      "Cross-Origin-Embedder-Policy": "require-corp"
    }
  }
}
```
they are not present in the initial localhost (index.html) request. All subsequent requests contains the headers.
When creating a new angular 16 app and adding the same config it works for the initial request as well.

### Please provide the exception or error you saw

```true
In the real code we see the error `Uncaught ReferenceError: SharedArrayBuffer is not defined` due to the missing headers.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.4
Node: 20.12.1
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 17.3.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.4
@angular-devkit/build-angular   17.3.4
@angular-devkit/core            17.3.4
@angular-devkit/schematics      17.3.4
@schematics/angular             17.3.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by NetWin** [comment]
I just noticed the same / a similar issue. These headers are also not available for `/media` files (i.e. files embedded / referenced from css files)

Using the "old" browser builder with a random custom header for demo purposes,

<img width="500px" src="https://github.com/angular/angular-cli/assets/7582077/93b77271-16df-4dd0-9479-31c7a57cb297">

results in these response headers (i simply `@import`'ed the [primeicons](https://github.com/primefaces/primeicons) css file in my `styles.scss`):

<img width="500px" src="https://github.com/angular/angular-cli/assets/7582077/4f4eb498-faaf-4b69-bf24-f8f670acd3fa">

But after updating (and switching to the application builder) the custom header is gone.

<img width="500px" src="https://github.com/angular/angular-cli/assets/7582077/20dfe69a-18a1-4ddf-a1ca-09b992e58157">

----

Additionally there is no `Access-Control-Allow-Origin` header anymore which is another problem for me. But that's not part of this Github issue

**Comment by PJozeph** [comment]
same issue here

**Comment by PJozeph** [comment]
so this is fixed ?

**Comment by alan-agius4** [comment]
Yes, it be released on NPM later on today.

**Comment by PJozeph** [comment]
sorry to ask again, but is it deployed if yes in which version ?

**Comment by PJozeph** [comment]
I am still having the same issue

**Comment by PJozeph** [comment]
For mw it work only locally, but not on PROD !
Is this the correct way of config ? 
![image](https://github.com/angular/angular-cli/assets/23094656/56cf8bc0-6d0a-4658-9721-5b7adee86318)

**Comment by alan-agius4** [comment]
@PJozeph, for the production server you need to configure your production server which settings will vary based on which server you are using.

The settings in `angular.json` are only apply to the development server.

**Comment by PJozeph** [comment]
@alan-agius4 
like this ? 
![Screenshot from 2024-04-26 11-29-33](https://github.com/angular/angular-cli/assets/23094656/3803db4e-ce26-4f6c-bd60-384712317d0a)

**Comment by alan-agius4** [comment]
@PJozeph, the `production` section solely effects the development server when executed with the production configuration ie: `ng serve --configuration=production`. In this scenario, the `headers` configuration is redundant, as it duplicates the one configured in the base options.

These settings do not affect your production server, as the configuration of the production server is outside the Angular CLI's.

**Comment by PJozeph** [comment]
@alan-agius4 I am really appreciate your help, thank you ! 

This is how I fixed the issue on PROD !

![image](https://github.com/angular/angular-cli/assets/23094656/26afbb50-003d-45fe-87ee-42604ce81495)
