### ISSUE TITLE
Routing not working in application under projects folder

### ISSUE THREAD

**Issue by iraviguggilam** [angular/angular-cli#27461]
### Command

generate

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Created new application using (ng g application < name >). When I'm trying to route to components in new application. it is not working.

### Minimal Reproduction

ng new main-app
ng g application app-1
ng g application app-2

create routing to app-1 & app-2 in main-app in app.routes.ts file

import { AppComponent as App1AppComponent } from '../../projects/app-1-app/src/app/app.component';
import { AppComponent as App2AppComponent } from '../../projects/app-2-app/src/app/app.component';
[
  {
     path:'app1',
     component:App1AppComponent
  },
  {
     path:'app2',
     component:App2AppComponent
  }
]

The above routing working fine.
But Routing in app-1 & app-2 applications are not working.

in previous version we have option of RouterModule.forChild(routes) is there to route to sub routes in application component.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.3.2
Node: 18.13.0
Package Manager: npm 8.19.3
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1703.2 (cli-only)
@angular-devkit/core         17.3.2 (cli-only)
@angular-devkit/schematics   17.3.2 (cli-only)
@schematics/angular          17.3.2 (cli-only)
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
