### ISSUE TITLE
Amount of spaces after ng generate

### ISSUE THREAD

**Issue by dombrga** [angular/angular-cli#27474]
### Command

generate

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

This is a very very small something that I noticed. When you create a component using **ng generate**, you get 2 spaces between the class name and the "implements" keyword.

<img width="358" alt="image" src="https://github.com/angular/angular-cli/assets/84841255/42c43d2b-ecf8-46a8-9586-55d12dab1105">

### Minimal Reproduction

ng g c sampleComponent

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.3.2
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.3.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.2
@angular-devkit/build-angular   17.3.2
@angular-devkit/core            17.3.2
@angular-devkit/schematics      17.3.2
@schematics/angular             17.3.2
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
```

**Comment by alan-agius4** [comment]
Hi @dombrga, there is strange as the Angular CLI no longer generates components with `implements` keyword.

Can you try to run
```
npm ls @schematics/angular
```

**Comment by alan-agius4** [comment]
This appears to be a bug in Ionic which have their own component schematics.

See: https://github.com/ionic-team/angular-toolkit/blob/bad1f939c788a8804e9a39a11b4651163dc72f78/packages/schematics/component/files/__name%40dasherize%40if-flat__/__name%40dasherize__.__type%40dasherize__.ts.template#L9
