### ISSUE TITLE
ng serve uses a lot of CPU % 

### ISSUE THREAD

**Issue by areijngoudt** [angular/angular-cli#2748]
Mac OSX El Capitan
### Versions.

angular-cli: 1.0.0-beta.17
node: 5.7.1
os: darwin x64

angular-cli uses about 85% CPU when I only use ng serve during development, also when I'n not changing code but just use the webapp in a browser.

**Comment by kylecordes** [comment]
I experienced the same thing here. Sitting idle, with nothing changing, approximately one CPU core burns 100% in ```ng serve```.  Latest node, latest OSX, CLI beta 17.

**Comment by mseemann** [comment]
`npm i fsevents` should solve this.

**Comment by masaanli** [comment]
Not working on Windows.

**Comment by areijngoudt** [comment]
installing fsevents solves this issue on mac. Thanks @mseemann

**Comment by rryter** [comment]
I don't think this issue should be closed. Manually installing fsevents can not be the longterm solution.

**Comment by benyaminshoham** [comment]
Does it make sense to add fsevents to the dependencies of @angular/cli?

**Comment by msnatu** [comment]
@mseemann Thanks a lot!

**Comment by jlberrocal** [comment]
fsevents only work for mac, but what about windows and linux, in my case what is literally eating is my ram, ng process consumes 1.2GB which i consider a lot for a process like that one

**Comment by JohannesRudolph** [comment]
Jose, please keep in mind that node is GC'd so it will happily use
available memory and won't collect aggressively until pressured by the OS
which doesn't happen if you have a lot of RAM ;-)
So unless ng is eating all your memory and your OS starts paging other
stuff you should be fine.

**Comment by Almenon** [comment]
have you tried using task manager to lower the affinity / priority of the process?

**Comment by chestercharles** [comment]
@Almenon 's solution to lower the affinity/priority of the process has been working for me. However, it is kinda tedious to do every time I run `ng serve`. 

If I don't manually lower the affinity/priority of the process, my CPU usage is at 99%.

**Comment by trumbitta** [comment]
@rryter also, if I add it to my package.json every build not happening under Mac OS will fail:

```
npm ERR! notsup Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

**Comment by trumbitta** [comment]
I ended up adding the following little script to my `postinstall`:

```js
const isMac = /^darwin/.test(process.platform);

if (isMac === true) {
  const process = require('child_process');
  process.execSync('npm install fsevents --no-save');
}
```

**Comment by rightisleft** [comment]
Using the `ng serve --poll` command causes my cpu to spike to %300 (3coresx100)

**Comment by smallg** [comment]
this is very useful

**Comment by alanchavez88** [comment]
Can somebody explain why `fsevents` solves this issue? Posting a solution without an explanation isn't helpful.

**Comment by sonjaerock** [comment]
What is solution on linux ?

**Comment by PyroSA** [comment]
@alanchavez88 fsevents allows the process to subscribe to File System EVENTS.

I can only assume angular-cli has logic built in that makes use of this if it's available.

This means that angular-cli no longer has to poll the actual files to see if changes occurred, it simply waits for OSX to notify it of a file change.

**Comment by electrichead** [comment]
It might have to do with chokidar, which is used by karma and the @angular/compiler-cli for watching files for changes. Chokidar is a wrapper around different ways to watch for files and fsevents is one of those. Chokidar has fsevents as an optional dependency - if it's present it will use it otherwise it has fallbacks. So if nothing else installs fsevents, chokidar goes with one of the alternatives and that eats up CPU because of polling. 

https://www.npmjs.com/package/chokidar#performance

**Comment by PyroSA** [comment]
Increasing the polling interval is enough to calm down the watching and will work even on non *nix.

I helped our Windows guys with their overeager virus scanners in the past.

**Comment by tebantebanteban** [comment]
same issue here 

```
Angular CLI: 6.1.1
Node: 10.7.0
OS: darwin x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.7.1
@angular/cli                      6.1.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.1
@schematics/update                0.7.1
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.8.3
```

**Comment by ryansigg** [comment]
Still seems to be an issue with CLI v 5.0.0.

Fixed with fsevents.
My ng process CPU usage went from 80-100% _all the time_ down to a max of 8% _only while compiling_ otherwise it's at 0 as expected.

**Comment by grantlucas** [comment]
This is still definitely an issue on linux in CLI 6.2.2

```
Angular CLI: 6.2.2
Node: 8.12.0
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.2
@angular-devkit/build-angular     0.8.2
@angular-devkit/build-optimizer   0.8.2
@angular-devkit/build-webpack     0.8.2
@angular-devkit/core              0.8.2
@angular-devkit/schematics        0.8.2
@angular/cli                      6.2.2
@ngtools/webpack                  6.2.2
@schematics/angular               0.8.2
@schematics/update                0.8.2
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.19.1
```

This is a major issue when running within a Vagrant machine for example. When I run this on my host machine (OSX) everything if fine with fsevents, but using poll in linux on the VM, both cores will steadily be at 80-90%+ usage.

**Comment by grantlucas** [comment]
@filipesilva Any chance at getting this issue re-opened? It still seems to be an issue.

**Comment by grantlucas** [comment]
In my other custom Webpack configs for other watchers, I normally have

```
        watchOptions: {
            ignored: /node_modules/,
            aggregateTimeout: 300,
            poll: 1000
        },
```

and that works great within Vagrant, without much CPU usage. Based on what I'm seeing in this repo when searching for `watchOptions`, I only ever see the poll flag set, nothing for `ignored`. Is it possible it's trying to watch the whole `node_modules` folder as well resulting in high CPU usage?

**Comment by grantlucas** [comment]
With some local exploration, I've found that adding the following to the [watchOptions in the common webpack config](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L264) resolved CPU usage issues in a Vagrant setup and allowed or 1 second polling without high CPU usage.

```
packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L264

        watchOptions: {
            ignored: /node_modules/,
            aggregateTimeout: 300,
            poll: buildOptions.poll
        },
```

With that, instead of adding _more_ flags for what to put into watchOptions, it'd be great to be able to specify the whole watch options block instead of just the poll option. Just in case this causes issues for other setups.

I can look into setting up a PR but it may take a while as I familiarize myself with the process for this project.

**Comment by grantlucas** [comment]
Hopefully the `ignored` flag can be exposed via #12313

**Comment by carl-parrish** [comment]
I've got a common.d.ts and no watchOptions in it.
