### ISSUE TITLE
Excessive modulepreload Links in Angular 18.0.0-next.4 Affecting Performance Metrics

### ISSUE THREAD

**Issue by manzonif** [angular/angular-cli#27490]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

No

### Description

I recently upgraded my Angular application to version 18.0.0-next.4 and migrated to esbuild and the new integrated SSR. However, I've noticed a significant impact on performance metrics, particularly First Contentful Paint (FCP) and Largest Contentful Paint (LCP), when using the new version.

Upon further investigation, I found that Angular now splits all JavaScript code into chunks and adds a ```<link rel="modulepreload">``` for each chunk in the ```<head>``` of the page. Although the scripts are loaded asynchronously with [@defer](https://angular.io/api/core/defer) method, the preloaded scripts seem to be affecting the rendering of critical content, delaying FCP and LCP.

I've conducted tests using Lighthouse, and the results show that removing the modulepreload links improves FCP and LCP metrics. This issue seems to be similar to what was reported in these GitHub discussions:

[GoogleChrome/lighthouse#11960](https://github.com/GoogleChrome/lighthouse/issues/11960#issuecomment-779049941)
[vitejs/vite#5991](https://github.com/vitejs/vite/issues/5991#issuecomment-1088711936)
In both discussions, users reported improvements in FCP and LCP metrics after disabling or reducing the number of modulepreload links.

Unfortunately, I couldn't find a way to selectively disable modulepreload links in Angular 18.0.0-next.4 based on specific use cases. Therefore, I would like to seek clarification and guidance on how to address this issue to improve performance.

**Steps to Reproduce:**

Upgrade an Angular application to version 18.0.0-next.4.
Enable SSR and use esbuild.
Analyze performance metrics using Lighthouse with and without the modulepreload links.
Expected Behavior:
I expect to see improved FCP and LCP metrics when excessive modulepreload links are removed or selectively disabled.

**Additional Information:**
I have attached screenshots of the Lighthouse test results, showing the impact of modulepreload links on performance metrics.

**Screenshots:**

Screenshot 1 - Lighthouse Test with modulepreload links

![Screenshot 2024-04-17 132612](https://github.com/angular/angular/assets/8948699/95b5a3ac-ac96-43a5-90f3-f538f900ec19)

Screenshot 2 - Lighthouse Test without modulepreload links
Performed by removing all modulepreload links server side: 
```typescript
        html = html.replace(
          /<link .?rel="modulepreload" .*?href="(?<href>.+?\.js)".*?>/g,
          ''
        );
```
![Screenshot 2024-04-17 132254](https://github.com/angular/angular/assets/8948699/0719109b-e98c-409b-9028-a72c4add7210)

Your assistance in resolving this issue would be greatly appreciated.

Thank you.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.0-next.2
Node: 20.11.1
Package Manager: yarn 1.22.21
OS: win32 x64

Angular: 18.0.0-next.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1800.0-next.2
@angular-devkit/build-angular     18.0.0-next.2
@angular-devkit/build-optimizer   0.1302.1
@angular-devkit/core              18.0.0-next.2
@angular-devkit/schematics        17.1.2
@angular/cli                      18.0.0-next.2
@angular/ssr                      18.0.0-next.2
@schematics/angular               18.0.0-next.2
rxjs                              7.8.1
typescript                        5.4.5
zone.js                           0.14.4
```

**Comment by manzonif** [comment]
@alan-agius4 Thank you for your response and for providing the solution.

I would appreciate it if you would consider implementing support for selective filtering of module preloading links. I believe a feature like this would be incredibly valuable, especially for larger applications where fine-grained control over resource loading can have a significant impact on performance.

The implementation described in the Vite.js pull request [#9938](https://github.com/vitejs/vite/pull/9938) seems to provide a robust solution by allowing users to define a resolveDependencies function to filter or modify the list of dependencies. This level of flexibility would empower developers to optimize resource loading based on specific use cases and performance requirements.

Are you planning to incorporate this functionality into Angular in the near future?

**Comment by alan-agius4** [comment]
@manzonif, I'm curious, how many preload links do you use?

Generally, offering such options doesn't really align with our design goals. Instead, we aim to provide a more responsive default that can cater to applications of all sizes.

There's definitely a correlation between Core Web Vitals (CWV) and preload tags. The more preload tags, the poorer the performance tends to becomes at least based on https://almanac.httparchive.org/en/2021/resource-hints#correlation-with-core-web-vitals

**Comment by manzonif** [comment]
I count about 50 modulepreload links, plus an image that is part of the LCP.

**Comment by manzonif** [comment]
I also noticed that Angular preloaded modules take precedence in the document head over those inserted inside a component. If what @patrickhulce reports [here ](https://github.com/GoogleChrome/lighthouse/issues/11960#issuecomment-929401366) is correct, the order of the preload hints is also important. Therefore, it would be necessary to ensure that the insertion of the module preloads is postponed, at least until after the ngOnInit lifecycle hook of the components.

If I add a preload as an image for an LCP image, it should have high priority.

**Comment by sod** [comment]
Esbuild can dump a `stats.json` via `ng build --stats-json` that contains the information which files are required to load lazy loaded chunks. See https://esbuild.github.io/api/#metafile (the outputs part)

Ssr could use the `stats.json` to only load the chunks required for the current route.

**Comment by alan-agius4** [comment]
The most recent RC version contains a change to only generate shallow preload links for initial files. You can find more details in PR https://github.com/angular/angular-cli/pull/27581.

@manzonif, could you please confirm if this resolves your issue?

@sod, in this situation, the issue lies not in the absence of preloads, but rather in having more than approximately 5 preloads, even for files essential to the route. Essentially, including a substantial number of preload links could create a performance bottleneck, more so when using SSR, as it might disrupt the browser's fetch priority.

**Comment by manzonif** [comment]
Hi @alan-agius4,

Sorry for the delay in replying.

The PR certainly addresses the issue of excessive preload links. However, I have a couple of remaining concerns:

1) If the order of links is important, I believe that those inserted by the component should take precedence over others. For example, in the case of an LCP (Largest Contentful Paint) image.

2) Limiting the preloads to the first three chunks might sometimes produce unexpected results. In my case, importing utility functions from other .ts files into the main component results in these small files being the three preload links. While I imagine this issue could be resolved by restructuring the imports, I wanted to bring it to your attention.

Below are some example images:

![Screenshot 2024-05-14 114606](https://github.com/angular/angular-cli/assets/8948699/775c92fb-82ee-40a0-aee4-0068a439bdb4)
![Screenshot 2024-05-14 114652](https://github.com/angular/angular-cli/assets/8948699/3ab07fb9-857c-418a-9851-697433241206)

**Comment by alan-agius4** [comment]
I believe that the issue with the order of links has likely been resolved. However, if the problem persists, please provide a reproduction. As for the issue with small chunks, it is currently being tracked here: https://github.com/angular/angular-cli/issues/27715.
