### ISSUE TITLE
sourcemap isn't working

### ISSUE THREAD

**Issue by robertIsaac** [angular/angular-cli#27504]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

in a new angular project all console logs are showing with the js files not ts files
![image](https://github.com/angular/angular-cli/assets/14242054/97a8d089-21be-440f-af96-c9be2a430594)
which makes it very hard to debug errors

### Minimal Reproduction

1. create a new project
2. add console.log anywhere in the application (in the image above I did it in `app.component.ts`

### Your Environment

```text
Angular CLI: 17.3.5
Node: 20.11.0
Package Manager: npm 10.4.0
OS: win32 x64

Angular: 17.3.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.5
@angular-devkit/build-angular   17.3.5
@angular-devkit/core            17.3.5
@angular-devkit/schematics      17.3.5
@schematics/angular             17.3.5
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.4
```

**Comment by JeanMeche** [comment]
Can you check the option is enabled in your browser ? 
![Screenshot 2024-04-19 at 23 23 33](https://github.com/angular/angular-cli/assets/1300985/0f8af2fe-2cde-459b-994a-b9be5003d1e7)

**Comment by robertIsaac** [comment]
oh I feel embarrassed now
