### ISSUE TITLE
Only reload on ng serve when change in code happen

### ISSUE THREAD

**Issue by n4-sgloxhuber** [angular/angular-cli#27501]
### Command

serve

### Description

Hello,
i have a litte and nitpicking feature request :) when you use ng serve to develop the application and the project has a compiler error, it would be great if the application don't reload constantly. It should only relaod after a new change. 

This behavior was in the older versions but now changed.

The constant reloading and screen flickering is super irritating while developing the application side by side with the IDE and the website.
I know the request is super nitpicking, it has no real benefit for development but it would be great if the change is only a small one to change. My concentration would be super thankful :)

### Describe the solution you'd like

Only reload after the code has changed

**Comment by alan-agius4** [comment]
Are you using the esbuild based builders and can you please provide the output of `ng v`?

When using the esbuild based builders, when there is an error the page is not refreshed instead an overlay is disabled with the error. 

Example
<img width="916" alt="Screenshot 2024-04-19 at 13 27 02" src="https://github.com/angular/angular-cli/assets/17563226/258d49f9-db05-4ebb-ac80-176fb12ffe12">

Is your request to disable showing the overlay?

**Comment by alan-agius4** [comment]
Closing as this should no longer be the case for version 17, if the problem persists please open a new issue.
