### ISSUE TITLE
[reopen] [proposal] auto polyfilling support via @babel/preset-env

### ISSUE THREAD

**Issue by MillerSvt** [angular/angular-cli#27510]
### Command

build, serve

---

I completely disagree with the fact that feature requests are closed without an exhaustive explanation. This is actually the scope of angular-cli. So, reopen: #17318 

---

### Description

According to [Official Document](https://angular.io/guide/browser-support#polyfills), polyfills can only be included manually.

Sometimes we somehow use ESNext features like Array.prototype.flatMap but forget adding its polyfill into polyfills.ts, it accidentally breaks on some browsers.

### Describe the solution you'd like

In https://github.com/alauda, we are using [@alauda/custom-webpack](https://www.npmjs.com/package/@alauda/custom-webpack) which pipes babel-loader after @ngtools/webpack in webpack config, so that we get auto polyfilling successfully via @babel/preset-env.

So I'm suggesting to add auto polyfilling support into @angular/cli.

### Describe alternatives you've considered

If we can build all .ts via @ngtools/webpack with targeting esnext, then we can use babel to compiling all ES syntaxes totally but are able to get types metadata still at the same time.

**Comment by alan-agius4** [comment]
Angular CLI doesn't automatically include polyfills for several reasons:

* **Modern Browser Support:** The officially supported browsers by Angular ([https://angular.io/guide/browser-support](https://angular.io/guide/browser-support)) often don't necessitate polyfilling.
* **Esbuild Integration:** Since version 17, Angular's build process leverages esbuild, prioritizing speed and efficiency. Including automatic polyfilling via Babel would introduce overhead.
* **Developer Choice:** By not imposing a specific polyfilling solution, Angular empowers developers to select the polyfills that best align with their project requirements and preferences.

**Comment by Char2sGu** [comment]
> Esbuild Integration: Since version 17, Angular's build process leverages esbuild, prioritizing speed and efficiency. Including automatic polyfilling via Babel would introduce overhead.

But, as far as I know, the new ESBuild based build system still uses babel under the hook, isn't it?

**Comment by MeMeMax** [comment]
From my perspective automatic polyfilling is a valid usecase. Consider the case that you have to support Chrome 88. Some time later your customer updates their Chrome and you only have to support Chrome 95. You would then have to determine which polyfills can be removed.

Also polyfilling based on the usage in your code base could be handled through babel.

The CLI might have a flag to enable/disable it (default disabled).

@MillerSvt Can you provide the webpack config to make auto polyfilling work?

**Comment by MillerSvt** [comment]
```
        module: {
            ...module,
            rules: [
                // Adding babel-loader before all others, because angular loader
                // should already receive a valid file with polyfiles as input
                {
                    test: /\.[cm]?[tj]sx?$/,
                    // Exclude libraries that don't need to be polyfilled
                    exclude: /node_modules[\\/](?!@some-untrusted-library)/,
                    use: {
                        loader: `babel-loader`,
                        options: {
                            presets: [
                                [
                                    `@babel/preset-env`,
                                    {
                                        corejs: `3.37`,
                                        useBuiltIns: `usage`,
                                    },
                                ],
                            ],
                        },
                    },
                },
                ...(module?.rules ?? []),
            ],
        },
```

**Comment by MeMeMax** [comment]
Thanks. Where does ...module come from? Is it a import from the angular cli webpack config?

**Comment by MillerSvt** [comment]
> Thanks. Where does ...module come from? Is it a import from the angular cli webpack config?

updated the example

**Comment by MeMeMax** [comment]
With your update the build works, but nothing is polyfilled.

**Comment by MillerSvt** [comment]
> With your update the build works, but nothing is polyfilled.

It works for me. What builder are you using? I use the `@nx/angular:webpack-browser` builder. I haven't tested it with the default builder.

**Comment by MeMeMax** [comment]
Yeah thats exactly my setup. NX with `@nx/angular:webpack-browser`. Here are a couple of questions:

- do you have an additional .babelrc?
- do you use a .browserslistrc?
- which version of nx/angular do you use? (I use angular v17, nx v18)
- did you specify the following in your nx.json?

   ```
 {
      "plugin": "@nx/webpack/plugin",
      "options": {
        "buildTargetName": "build",
        "serveTargetName": "serve"
      }
    }
```

**Comment by MillerSvt** [comment]
> * do you have an additional .babelrc?

no

---

> do you use a .browserslistrc?

yes:
```
extends @taiga-ui/browserslist-config
```

---

> * which version of nx/angular do you use? (I use angular v17, nx v18)

17

---

> * did you specify the following in your nx.json?
no

**Comment by MeMeMax** [comment]
Two last questions (sorry to bother you :D):
- Do you have a polyfills entry in your project.json? (zone.js should be there I suppose)
- Do you know how angular/webpack knows that it has to pass the polyfills from babel into the polyfills.***hash***.js?

**Comment by MillerSvt** [comment]
I have polyfills entry with only zone.js.

Babel compiles every source file and adds the necessary polyfills with imports to the same file. So it adds polyfills to the same entry where they are used, instead of adding them to a separate polyfills entry.

**Comment by MeMeMax** [comment]
That was the missing link. When creating an Angular NX project by default `outputHashing` is set to `all` in build -> configurations -> production. This results in files having such filenames: `main.cf0f75c4009e0a01.js`. When removing outputHashing it works. But I would like to keep outputHashing. Maybe I find a solution.

**Comment by MeMeMax** [comment]
Thanks again @MillerSvt for your help. I wrote a comprehensive guide with all my findings on stackoverflow: https://stackoverflow.com/a/78611674/6098257 maybe this helps someone.

**Comment by MillerSvt** [comment]
> * The officially supported browsers by Angular (https://angular.io/guide/browser-support) often don't necessitate polyfilling.

@alan-agius4 It's a bit confusing for me. This means that if we want to have support for `chrome >= 88 ' for example, then we can't upgrade above `Angular 11`? This is complete nonsense!
