### ISSUE TITLE
host property of the compoments not providing typings intellisense and also class applied to it not getting processed by tailwindcss

### ISSUE THREAD

**Issue by sheikalthaf** [angular/angular-cli#27512]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

host property of the components not providing any typings intellisense.
Also tailwind class applied to it not getting processed by tailwindcss.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
