### ISSUE TITLE
AotPlugin in @ngtools/Webpack is not generating ngfactories

### ISSUE THREAD

**Issue by qvazzler** [angular/angular-cli#2757]
### OS?
Win 8.1

### Versions.
```
node --version
v6.5.0
```

```
  "devDependencies": {
    "@angular/common": "^2.0.1",
    "@angular/compiler": "^2.0.1",
    "@angular/compiler-cli": "^2.1.0",
    "@angular/core": "^2.0.1",
    "@angular/platform-browser": "^2.0.1",
    "@angular/platform-browser-dynamic": "^2.0.1",
    "@angular/platform-server": "^2.0.1",
    "@ngtools/webpack": "^1.1.0",
    "@types/core-js": "^0.9.34",
    "@types/node": "^6.0.41",
    "angular2-template-loader": "^0.5.0",
    "awesome-typescript-loader": "^2.2.4",
    "core-js": "^2.4.1",
    "http-server": "^0.9.0",
    "raw-loader": "^0.5.1",
    "rxjs": "^5.0.0-beta.12",
    "typescript": "2.0.3",
    "webpack": "^2.1.0-beta.25",
    "zone.js": "^0.6.25"
  }
```

### Repro steps.
* Clone this (forked) repo: https://github.com/qvazzler/angular2-aot-webpack
* `npm install`
* `npm run-script "webpack-aot"`
* Look at "last modified" of the ngfactory files. No change.

### The log given by the failure.
(ngfactory files are not generated using aot webpack run script. They only get generated when using the ngc task via npm (or from terminal `ngc -p tsconfig.aot.json`)

Removing the ngfactory files also creates complaints.

### Mention any other details that might be useful.
I think AotPlugin is effectively broken until this is fixed.
Would love to know if this is going to be fixed soon, or if I should be looking at other options. Love what you've done so far!

**Comment by clydin** [comment]
The current version should be generating everything in memory.

**Comment by qvazzler** [comment]
@clydin I am developing a chrome extension that are enforced by CSP (which makes this static compiling invaluable!), but I need them to be in files... How can this be achieved?

**Comment by filipesilva** [comment]
@qvazzler if you need the files separately then you can just `ngc`. The webpack plugin is taking care of the file replacements in memory, and should just bundle up the factories in the final bundle. Check the generated bundle and the factories should be there.

**Comment by qvazzler** [comment]
@filipesilva I see what you mean, but I'm using webpack in watch mode because the files need to be present. I'm developing a chrome extension and I don't think there's a way for me to use any in-memory stuff as the files need to be declared in manifest.json. Please correct me if I'm wrong, but it would be great if Aotplugin could work for webpack in general and not just for the most popular way of using it.

Anyway i guess I'm a minority here, so it's your call.
