### ISSUE TITLE
Schematic blank command doesn't allow to specify the package manager.

### ISSUE THREAD

**Issue by Hyperxq** [angular/angular-cli#27571]
### Command

new

### Description

I cannot see that schematics cli commands added to the command select options. 

When you create a new schematic project you only have the ability to specify the name and the author. However, you cannot specify the package manager.

### Describe the solution you'd like

The `NodePackageInstallTask` already allows the package manager option. To support the package manager option we need to do:

1. We need to modify the factory: https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/schematics_cli/blank/factory.ts in the line 93, we need to add the package manager option.
![schematics blank](https://github.com/angular/angular-cli/assets/22332354/04372376-f435-44d1-a927-433b37807226)

2. We need to add the input to the schema.json: https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/schematics_cli/blank/schema.json
![schematic blank schema](https://github.com/angular/angular-cli/assets/22332354/28126193-0040-4e5f-8d12-05607283a471)

**Comment by ldavila777** [comment]
I would like to work on this issue. Could you please assign it to me?
