### ISSUE TITLE
Supporting Tailwind v4

### ISSUE THREAD

**Issue by inorganik** [angular/angular-cli#27585]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Tailwind v4 alpha is out and a stable release is imminent. The new CLI `@tailwindcss/cli` traverses files in your project and automatically finds the tailwind classes. It works without a tailwind config, which is what the angular builder looks for to support tailwind. The problem is, you have to setup an npm script to invoke the tailwind CLI, and it is seemingly impossible to integrate it into Angular's build process. I've tried lots of weird hacky things.

Alternatively, Tailwind v4 offers a new [postcss plugin](https://tailwindcss.com/blog/tailwindcss-v4-alpha#using-post-css), but again, there is no way to configure post css in Angular.

Other issues with using Tailwind v4 in an Angular project:
- `@angular-devkit/build-angular` (v16 and v17) has a peer dependency of `"tailwindcss": "^2.0.0 || ^3.0.0",`
- Tailwind support is currently [baked into the builder](https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/tools/webpack/configs/styles.ts#L78), making it impossible to support new major versions of tailwind. 

We ought to be able to use the latest and greatest in our Angular projects. As a start we should remove the peer dependency on old versions of tailwind. 

We ought to decouple tailwind integration out of this package so it can be configurable by devs.

### Minimal Reproduction

I have an angular 16 project [here](https://github.com/jamie-perkins-sp/angular16-test/tree/tailwind-v4) with tailwind v4 installed, you have to use the `--force` flag to install dependencies because of the incompatible tailwind peer dep. An npm script "tailwind"  has to be run separately from the build, so for every style change you have to rerun the command.

### Your Environment

```text
v16 and v17
```

**Comment by alan-agius4** [comment]
The Angular application builder supports custom PostCSS configuration files. The builder will automatically detect and use specific postcss configuration files if present in either the project root directory or the workspace root.

To utilize a custom PostCSS configuration:

1. **Create a JSON file** named either `postcss.config.json` or `.postcssrc.json` in your project's root directory. Project-level configurations override workspace-level ones.

2. **Define your plugins** within this file using either an array or object format:

   **Array Form:**
   ```json
   {
     "plugins": [
       "tailwindcss",
       ["rtlcss", { "useCalc": true }]
     ]
   }
   ```

   **Object Form:**
   ```json
   {
     "plugins": {
       "tailwindcss": {},
       "rtlcss": { "useCalc": true }
     }
   }
   ```

**Comment by inorganik** [comment]
Thanks @alan-agius4 ! In [this comment](https://github.com/angular/angular-cli/issues/22849#issuecomment-1070927143) I had read postCSS config wasn't supported but glad to be wrong about that. 

Following these instructions unfortunately I was not able to get v4 working. Here is my postcss.config.json file at the root of my project:
```json
{
  "plugins": {
    "@tailwindcss/postcss": {}
  }
}
```
The plugin name is from the [tailwind docs](https://tailwindcss.com/blog/tailwindcss-v4-alpha#using-post-css). I'm not seeing any error messages, but it is not compiling tailwind either. I pushed these changes to the postcss branch of my [test repo](https://github.com/jamie-perkins-sp/angular16-test/tree/postcss)

**Comment by alan-agius4** [comment]
@inorganik, custom postcss configuration is only available from Angular CLI versions 17.2 onwards.

**Comment by inorganik** [comment]
@alan-agius4 The postcss config works great in Angular 17! Only issue now is the peer deps - is there a way to not have to use the force flag for every npm install/build?

**Comment by alan-agius4** [comment]
You can add `legacy-peer-deps=true` to an `.npmrc` file located in your workspace.

**Comment by dgp1130** [comment]
We had a brief discussion within the team about this today. There's nothing too controversial here just a few different tasks we'll need to land. Tailwind v4 is still in alpha, so I don't think there's anything urgent here, but once it does release we'll want to:
* Update default configuration to use `@tailwindcss/postcss`.
* Update CSS file detection to look for `@import 'tailwind';`, since this seems to be an easier way of detecting which files use Tailwind.
* Consider directly supporting Tailwind in `@angular/build:application` instead of requiring PostCSS, this could give some performance improvments.
* Bump peer dep to include `^4.0.0`.

Angular still uses the presence of a Tailwind config file to know whether or not we need to run Tailwind. That probably won't change even in v4, even if Tailwind itself no longer requires a config file.

**Comment by alan-agius4** [comment]
Tailwind CSS 4 is still in alpha, with no ETA for the stable release. Let's revisit this when it's either close to or officially stable.
