### ISSUE TITLE
Invalid message about `publicHost` on `ng serve`

### ISSUE THREAD

**Issue by Ghostbird** [angular/angular-cli#27589]
### Command

serve

### Is this a regression?

I don't think so

### Description

When I run `ng serve` I use the builder `@angular-devkit/build-angular:dev-server`. However I get a message:

> The "publicHost" option will not be used because it is not supported by the "@angular-devkit/build-angular:application" builder.

This is odd, and erroneous:

- I'm not using `@angular-devkit/build-angular:application` as builder
- If I remove the "unused"  `publicHost` my development set-up doesn't work any more, because the public host is not set.

I think the message should not be shown.

### Minimal Reproduction

```sh
ng new app -gSst --style scss --ssr false
cd app
# Alternatively, manually set `projects.app.architect.serve.options.publicHost to "foo.bar" in angular.json
jq '.projects.app.architect.serve.options.publicHost = "foo.bar"' angular.json | sponge angular.json
ng serve
```

### Exception or Error

```text
The "publicHost" option will not be used because it is not supported by the "@angular-devkit/build-angular:application" builder.
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.6
Node: 22.0.0 (Unsupported)
Package Manager: npm 10.5.1
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1703.6 (cli-only)
@angular-devkit/core         17.3.6 (cli-only)
@angular-devkit/schematics   17.3.6 (cli-only)
@schematics/angular          17.3.6 (cli-only)
```

### Anything else relevant?

It doesn't actively break anything, but if you act on the message, you'll break things.

**Comment by alan-agius4** [comment]
@Ghostbird, the `publicHost` option is completely ignored when using the dev-server with the application builder. When using the reproduction steps provided the application builder is used unlike what you described in the issue.

**Comment by Ghostbird** [comment]
@alan-agius4 It seems you're right. I got confounded by something else that I have to look into. It's not toggled by the `publicHost` option after all.
