### ISSUE TITLE
Feature: @angular/build:ng-packagr

### ISSUE THREAD

**Issue by alexfriesen** [angular/angular-cli#27593]
### Command

build

### Description

I love the new `@angular/build` package and was a little surprised that the build instruction `@angular/build:ng-packagr` did not work. 

### Describe the solution you'd like

I would love to just use `@angular/build` and shake off some unnecessary dependencies.

### Describe alternatives you've considered

`@angular-devkit/build-angular:ng-packagr` still works great 👍

**Comment by clydin** [comment]
In addition to the `application` builder within `@angular/build`, we would also like to add a `library` builder as well. The new library builder would ideally be designed to take advantage and reuse much of the code present within the application builder including the Angular compiler abstractions and stylesheet processing. While we currently do not have an exact timeline for its inclusion, we will provide more details as the feature progresses.

**Comment by alexfriesen** [comment]
Thats sounds great! Thank you for the update.
