### ISSUE TITLE
Vulnerabilty with ejs which is dependant on @angular-eslint/builder 

### ISSUE THREAD

**Issue by pramodhcm** [angular/angular-cli#27596]
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Create new Angular v16 project.
Run npm audit in the project folder

The devDependencies 
@angular-eslint/builder": 16.2.0

### Minimal Reproduction

Create new Angular v16 project.
Run npm audit in the project folder
See more details: [1097210](https://github.com/advisories/GHSA-ghr5-ch3p-vcr6)

### Your Environment

```text
C:\Users\pramocm>ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 16.2.5
Node: 20.11.0 (Unsupported)
Package Manager: npm 10.3.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1602.5 (cli-only)
@angular-devkit/core         16.2.5 (cli-only)
@angular-devkit/schematics   16.2.5 (cli-only)
@schematics/angular          16.2.5 (cli-only)
```

**Comment by JeanMeche** [comment]
Hi, `@angular-eslint` is not maintained by the Angular team. Please refer to @angular-eslinthttps://github.com/angular-eslint/angular-eslint
