### ISSUE TITLE
Disable code splitting

### ISSUE THREAD

**Issue by Ghostbird** [angular/angular-cli#27601]
### Command

build

### Description

We build a web component for customers however the new `@angular-devkit/build-angular:application` builder doesn't seem to have an option to disable code splitting.

Previously we used `@angular-devkit/build-angular:browser` with `vendorChunk: true` and concatenated the output files into a single JS file to get a single JS file to give to our customers.

We have some customers whose policies demand that they only load javascript from their own domains. Being able to provide them a single JS file has made it very easy to accommodate them.

However the new builder splits our component into 13 JS files, none of which are actually lazy loaded, all are immediately requested on page load.

### Describe the solution you'd like

An option to limit, or turn off, code splitting. The old `vendorChunk` barely made it possible to publish a single JS file, and required some slightly hacky post-processing. It would be nice if such an option was offered natively.

As I understand, code splitting is an option that was added later to esbuild, so I'd think it would be easy to _not_ do that.

### Describe alternatives you've considered

We tried to use the `browser-esbuild` builder, for the web-component projects but:

> The 'vendorChunk' option is not used by this builder and will be ignored.

The built application is still split across 13 JS files that cannot be concatenated into one working file.

**Comment by Ghostbird** [comment]
@alan-agius4 Please don't close this so suddenly.

It's not a direct duplicate, #26478 was about single-entry. We'd really want a single-file.

That issue refers to https://github.com/angular/angular-cli/issues/23574:

> This however is possible using the esbuild builder by putting all the polyfills and scripts into the main file.

However I can't find any documentation backing that statement, and I have not found a way to actually do that. If this truly is possible, could you point out _how_?

**Comment by alan-agius4** [comment]
With the esbuild based builder, you can create a single bundle as explained in the above linked issue. For quick reference here's the comment https://github.com/angular/angular-cli/issues/26478#issuecomment-1828502818

**Comment by Ghostbird** [comment]
I have read that comment, but I guess I'm completely failing to understand it.
>If you do not use dynamic importing then there will be a single main JavaScript file and the polyfills JavaScript file generated in the output. 

1. I've managed to eliminate the `polyfill` as per your recommendation add it to `main.ts`.
2. I do not use dynamic imports.

Step 1 does work as you said. However step 2 doesn't result at all in:  "_there will be a single main JavaScript file_". I'm still stuck with 12 files.

**Comment by alan-agius4** [comment]
This should not be case, unless a dynamic import or some form of lazy-loading is used. It can also be that one of the libraries that you dependent on is using dynamic imports.

**Comment by Ghostbird** [comment]
Ah, thanks, I'll look into doing that.

**Comment by Ghostbird** [comment]
Thank you so much!

Apparently I really can't control the code splitting, but bundling the split results with `esbuild` in a post-build step works smoothly.

This is now run by my npm postbuild command:

```node
#!/bin/env node
{
  const esbuild = require('esbuild');
  const { mkdirSync } = require('fs');

  const srcDir = 'dist/fooComponent/browser';
  const destDir = 'dist/components';
  const destFileName = 'fooComponent.js';

  mkdirSync(destDir, { recursive: true });

  console.log(`Bundling ${destFileName}…`);
  esbuild
    .build({
      entryPoints: [`${srcDir}/main.js`],
      bundle: true,
      minify: true,
      sourcemap: false,
      outfile: `${destDir}/${destFileName}`,
      format: 'esm',
    })
    .then(
      () => console.info(`${destFileName} created successfully!`),
      (error) => console.error(error),
    );
}
```
