### ISSUE TITLE
npm start with .NET Core SPA

### ISSUE THREAD

**Issue by simonstyger** [angular/angular-cli#27612]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I use a .NetCore Service to host my Angular-Application as a SPA.

### Minimal Reproduction

When i start my .NET-Service to host the SPA, everything seems fine, but the console flashes up and closes directly. I was able to get a screenshot with a screenrecord-tool:

![image](https://github.com/angular/angular-cli/assets/5929796/3f55ac92-5df5-478f-97c0-3c9eddbaf621)

But when i run the same command "npm start" over console (so not hosting over SPA) it works fine:
![image](https://github.com/angular/angular-cli/assets/5929796/e63d9eda-37b0-4e5b-bc3f-aea88bde3ef2)

### Your Environment

```text
Angular CLI: 15.2.11
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 15.2.10
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.11
@angular-devkit/build-angular   15.2.11
@angular-devkit/core            15.2.11
@angular-devkit/schematics      15.2.11
@angular/cli                    15.2.11
@schematics/angular             15.2.11
rxjs                            7.8.1
typescript                      4.9.5
```

### Anything else relevant?

I use node and npn over nvm:
```
nvm list

    20.12.2
  * 16.13.2 (Currently using 64-bit executable)
    16.1.0
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by simonstyger** [comment]
Thank you for your response.
