### ISSUE TITLE
ng g directive generate wrong import in a module

### ISSUE THREAD

**Issue by akomm** [angular/angular-cli#2762]
### OS?
> Ubuntu 14.04 lts

### Versions.
> angular-cli: 1.0.0-beta.17
> node: 5.6.0

### Repro steps.
- ng new test
- cd test
- ng g module modulename
- cd src/app/modulename
- ng g directive directivename

### The log given by the failure.
No failure

### Expected result
Generates files:
- src/app/modulename/modulename.module.ts
- src/app/modulename/modulename.component.ts
- src/app/modulename/modulename.component..spec.ts
- src/app/modulename/modulename.component.html
- src/app/modulename/modulename.component.css
- **src/app/modulename/directivename/directivename.directive.ts**
- **src/app/modulename/directivename/directivename.directive.spec.ts**

Content of `src/app/modulename/modulename.module.ts`:
```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ModulenameComponent } from './modulename.component';
import { DirectivenameDirective } from './directivename/directivename.directive';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [ModulenameComponent, DirectivenameDirective]
})
export class ModulenameModule { }
```

### Actual result (what's wrong - DIFF)
- **src/app/modulename/directivename.directive.ts**
- **src/app/modulename/directivename.directive.spec.ts**

Content of `src/app/modulename/modulename.module.ts`:
```ts
// ...
import { DirectivenameDirective } from './modulename/directivename.directive';
// ...
```

### Problem

1. `ng g directive` does not behave like `ng g component`, which generate output similar to the `expected` one.
2. Ignoring the 1. problem, it still generates wrong import path, resolving relative to src/app and not src/app/module.

**Comment by akomm** [comment]
Found the difference is that the component blueprint has the option `flat` default set to `false` and the directive blueprint has it set by default to `true`. When I use `ng g directive modulename/directivename --flat=false` problem 1 is fixed, but problem 2 still exists.

**Comment by filipesilva** [comment]
@Brocco can you have a look?

**Comment by akomm** [comment]
If you want to know whether it was fixed in beta.18: No. Tested it :)

**Comment by Brocco** [comment]
This seems to be behaving as expected...
```bash
 ~/dev/mlb/bar (master): ng g module modulename
installing module
  create src/app/modulename/modulename.module.ts
installing component
  create src/app/modulename/modulename.component.css
  create src/app/modulename/modulename.component.html
  create src/app/modulename/modulename.component.spec.ts
  create src/app/modulename/modulename.component.ts
 ~/dev/mlb/bar (master): ng g directive directivename
installing directive
  create src/app/directivename.directive.spec.ts
  create src/app/directivename.directive.ts
```
modulename is created in it's own directory... as expected
directivename is created in the app directory... as expected
and directivename is imported and declared in app.module.ts... as expected (shown here)
```typescript
...
import { DirectivenameDirective } from './directivename.directive';
@NgModule({
  declarations: [
    AppComponent,
    DirectivenameDirective
  ]
...
```

**Comment by akomm** [comment]
You are not creating it in a module, as I'v shown in the reproduction. As I'v said:
`generates wrong import path, resolving relative to src/app and not src/app/module`

Since you'v created it in src/app, it obviously works.

**Comment by Brocco** [comment]
I followed your repro steps...
```
ng new test
cd test
ng g module modulename
ng g directive directivename
```
should they be?
```
ng new test
cd test
ng g module modulename
cd modulename
ng g directive directivename
```
