### ISSUE TITLE
How specify a folder for javascript and css with "ng build" (but with index.html on the root folder)

### ISSUE THREAD

**Issue by cesco69** [angular/angular-cli#27629]
### Command

build

### Description

I want take `index.html` on the root folder, but all js and css file in a sub folder (eg: "/static").

```
/
├── index.html
└── static/
    ├── runtime.09dbad26989ed44c.js
    ├── polyfills.7eddfc827f8797ce.js
    ├── main.b575f9ab98e16fd7.js
    └── styles.d518ebbd15507a10.css
```
and `index.html` become
```html
<!DOCTYPE html>
<html lang="en"> 
    <head>
        <link rel="stylesheet" href="static/styles.d518ebbd15507a10.css">
    </head>
    <body>
        <ac-root></ac-root>
        <script src="static/runtime.09dbad26989ed44c.js" type="module"></script>
        <script src="static/polyfills.7eddfc827f8797ce.js" type="module"></script>
        <script src="static/main.b575f9ab98e16fd7.js" type="module"></script>
    </body>
</html>
```

how do that?

**Comment by clydin** [comment]
You can use the `deployUrl` option to facilitate this use case when performing production builds. In this case with a value of `static/`.  Once the production build is complete with this option enabled, the relevant files can be deployed to the needed locations or can be served as appropriate depending on the server and/or hosting services used for the application.

**Comment by cesco69** [comment]
Hi @clydin is the normal behaviour that with deployUrl , eg.:

```
ng build --deploy-url /static/
```

the html is correct and become 

```html
<!DOCTYPE html>
<html lang="en"> 
    <head>
        <link rel="stylesheet" href="static/styles.d518ebbd15507a10.css">
    </head>
    <body>
        <ac-root></ac-root>
        <script src="static/runtime.09dbad26989ed44c.js" type="module"></script>
        <script src="static/polyfills.7eddfc827f8797ce.js" type="module"></script>
        <script src="static/main.b575f9ab98e16fd7.js" type="module"></script>
    </body>
</html>
```

but the js and css still in the root

```
/
├── index.html
├── runtime.09dbad26989ed44c.js
├── polyfills.7eddfc827f8797ce.js
├── main.b575f9ab98e16fd7.js
└── styles.d518ebbd15507a10.css
```

**Comment by alan-agius4** [comment]
@cesco69, the `deployURL` option in Angular doesn't change where your built files are saved. It modifies the base path used in `index.html` and component stylesheets, affecting how the URLs for resources are constructed. This is particularly used for specific deployments like Angular Elements or when using various CDN locations.
