### ISSUE TITLE
--skip-install is ignored when creating a new app with --ssr

### ISSUE THREAD

**Issue by KevTale** [angular/angular-cli#27631]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

This is a very specific situation but if you try to generate a new app (with `--ssr --skip-install`) inside an existing workspace, the `--skip-install` will be by-passed and it will still install the deps.

To reproduce:
1. run `npx @angular/cli@latest new myorg --skip-install` (with or without `--create-application=false`, it doesn't matter)
2. run `ng generate app my-app --ssr --skip-install`

It will still install the deps.

**edit**: the issue doesn't happen if on 2. I run `npx @angular/cli@latest generate app my-app --ssr --skip-install`.
I just noticed that when running `ng generate ...` I got a warning
```
Package dependency "@angular/ssr" already exists with a different specifier. "^17.3.7" will be replaced with "^17.0.0".
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update the global version of the Angulaer CLI to the most recent version by using `npm i @angular/cli -g` to resolve the problem.
