### ISSUE TITLE
No provider for RouterOutletMap!

### ISSUE THREAD

**Issue by chrillewoodz** [angular/angular-cli#2764]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS
Mac OSX (Sierra)

### Versions.
angular-cli: 1.0.0-beta.17
node: 6.7.0
os: darwin x64

### The log given by the failure.
error_handler.js:47EXCEPTION: Error in ./CoreComponent class CoreComponent - inline template:0:0 caused by: No provider for RouterOutletMap!ErrorHandler.handleError @ error_handler.js:47(anonymous function) @ application_ref.js:210ZoneDelegate.invoke @ zone.js:203onInvoke @ ng_zone_impl.js:43ZoneDelegate.invoke @ zone.js:202Zone.run @ zone.js:96(anonymous function) @ zone.js:462ZoneDelegate.invokeTask @ zone.js:236onInvokeTask @ ng_zone_impl.js:34ZoneDelegate.invokeTask @ zone.js:235Zone.runTask @ zone.js:136drainMicroTaskQueue @ zone.js:368
error_handler.js:49ORIGINAL EXCEPTION: No provider for RouterOutletMap!ErrorHandler.handleError @ error_handler.js:49(anonymous function) @ application_ref.js:210ZoneDelegate.invoke @ zone.js:203onInvoke @ ng_zone_impl.js:43ZoneDelegate.invoke @ zone.js:202Zone.run @ zone.js:96(anonymous function) @ zone.js:462ZoneDelegate.invokeTask @ zone.js:236onInvokeTask @ ng_zone_impl.js:34ZoneDelegate.invokeTask @ zone.js:235Zone.runTask @ zone.js:136drainMicroTaskQueue @ zone.js:368
error_handler.js:52ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:52(anonymous function) @ application_ref.js:210ZoneDelegate.invoke @ zone.js:203onInvoke @ ng_zone_impl.js:43ZoneDelegate.invoke @ zone.js:202Zone.run @ zone.js:96(anonymous function) @ zone.js:462ZoneDelegate.invokeTask @ zone.js:236onInvokeTask @ ng_zone_impl.js:34ZoneDelegate.invokeTask @ zone.js:235Zone.runTask @ zone.js:136drainMicroTaskQueue @ zone.js:368
error_handler.js:53Error: No provider for RouterOutletMap!
    at NoProviderError.Error (native)
    at NoProviderError.BaseError [as constructor] (http://localhost:4200/main.bundle.js:5463:34)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/main.bundle.js:41223:16)
    at new NoProviderError (http://localhost:4200/main.bundle.js:41254:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/main.bundle.js:57297:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/main.bundle.js:57325:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/main.bundle.js:57288:25)
    at ReflectiveInjector_.get (http://localhost:4200/main.bundle.js:57097:21)
    at NgModuleInjector.get (http://localhost:4200/main.bundle.js:42132:52)
    at ElementInjector.get (http://localhost:4200/main.bundle.js:57461:48)

### Mention any other details that might be useful.

The code is provided here:

http://stackoverflow.com/questions/40107861/angular-2-no-provider-for-routeroutletmap-when-lazy-loading/40108027?noredirect=1#comment67487321_40108027

**Comment by Meligy** [comment]
This is not really an Angular-CLI issue. I have left you a reply on the StackOverflow question.

Cheers,

**Comment by chrillewoodz** [comment]
Thanks. I'll have a look.

**Comment by chrillewoodz** [comment]
@Meligy http://stackoverflow.com/questions/40122820/angular-2-how-to-define-lazy-loaded-child-routes-of-a-parent-route-thats-also-l got any idea about this one? Can't find any info on this either.
