### ISSUE TITLE
ng serve fails to load app if url parameter contains a dot (.)

### ISSUE THREAD

**Issue by MurmursDev** [angular/angular-cli#27657]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

same to this issue https://github.com/angular/angular-cli/issues/26320

Now the Vite 5 is already out but this problem is still here. 

### Minimal Reproduction

`ng new test`

`cd test`

`ng generate component test`

change app.routes.ts

```
import { Routes } from '@angular/router';
import {TestComponent} from "./test/test.component";

export const routes: Routes = [
{
    path: 'welcome.html', component: TestComponent
 }
];
```

visit http://localhost:4200/welcome.html and got `Cannot GET /options.html`

### Your Environment

```text
Angular CLI: 17.3.7
Node: 18.20.2
Package Manager: npm 10.5.0
OS: darwin arm64

Angular: 17.3.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.7
@angular-devkit/build-angular   17.3.7
@angular-devkit/core            17.3.7
@angular-devkit/schematics      17.3.7
@angular/cli                    17.3.7
@schematics/angular             17.3.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.6
```

**Comment by MurmursDev** [comment]
`"@angular-devkit/build-angular": "17.1.0",` works

**Comment by MurmursDev** [comment]
17.1.1 works 
17.1.2+ doesn't work

**Comment by MurmursDev** [comment]
Is this the problem? [3deb0d4a1](https://github.com/angular/angular-cli/commit/3deb0d4a102fb8d8fae7617b81f62706371e03f5) 	fix 	return 404 for assets that are not found

# 17.1.2 (2024-01-31)

### @angular-devkit/build-angular

| Commit                                                                                              | Type | Description                                                      |
| --------------------------------------------------------------------------------------------------- | ---- | ---------------------------------------------------------------- |
| [6815f13e3](https://github.com/angular/angular-cli/commit/6815f13e3c87eff773aa914858293c75e4fae7d2) | fix  | add `required` modules as externals imports                      |
| [a0e306098](https://github.com/angular/angular-cli/commit/a0e306098147cf5fb7b51264c18860767fdf6316) | fix  | correctly handle glob negation in proxy config when using vite   |
| [235c8403a](https://github.com/angular/angular-cli/commit/235c8403a5bf8a2032da72a504e8cee441dd2d82) | fix  | handle regular expressions in proxy config when using Vite       |
| [5332e5b2e](https://github.com/angular/angular-cli/commit/5332e5b2ea0c9757f717e386fb162392ef2327a4) | fix  | resolve absolute `output-path` when using esbuild based builders |
| [3deb0d4a1](https://github.com/angular/angular-cli/commit/3deb0d4a102fb8d8fae7617b81f62706371e03f5) | fix  | return 404 for assets that are not found                         |

**Comment by alan-agius4** [comment]
Why do you include file extensions in your SPA routes? Including file extensions in routes is often due to legacy systems or a desire for clarity. However, this practice isn't ideal for SPAs as modern best practices favor clean, extensionless URLs. They enhance user experience, aid SEO, and ensure consistency across routes.

**Comment by MurmursDev** [comment]
I’m creating a chrome extension which only accepts html files. I have two
pages and need two html files. I choose use routing in one project and copy
final index file to two names, welcome.html and options.html.

Please let me know if there is better way to do this in one project.

**Comment by alan-agius4** [comment]
Why do you need two HTML files? The Chrome Extension can be a SPA where routing is managed by the Angular router.

**Comment by MurmursDev** [comment]
Because I have a welcome page and options page.

Thanks for your reminder, I just enabled withHashLocation configuration and
now am using one html file.

Previously without hash routing, I couldn't open the welcome page and
options page in one html file.
