### ISSUE TITLE
can not disable [suspicious-nullish-coalescing] for esbuild 

### ISSUE THREAD

**Issue by jeffschulzusc** [angular/angular-cli#27663]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

webpack build

### Description

converted to esbuild, getting warnings:
The "??" operator here will always return the left operand [suspicious-nullish-coalescing]

i tried to temporarily get rid of the warnings:
/* eslint-disable @typescript-eslint/no-non-null-asserted-nullish-coalescing */

but does not work ...
so what rule is 'suspicious-nullish-coalescing' ? and can i disable it ?

### Minimal Reproduction

"executor": "@angular-devkit/build-angular:browser-esbuild",

### Exception or Error

```text
[WARNING] The "??" operator here will always return the left operand [suspicious-nullish-coalescing]
```

### Your Environment

```text
Angular CLI: 17.1.4
Node: 21.5.0 (Unsupported)
Package Manager: yarn 1.22.21
OS: darwin arm64

Angular: 17.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                          Version
----------------------------------------------------------
@angular-devkit/architect        0.1701.4
@angular-devkit/build-angular    17.1.4
@angular-devkit/core             17.1.4
@angular-devkit/schematics       17.1.4
@angular/cdk                     16.2.3
@angular/cdk-experimental        16.2.13
@angular/cli                     17.1.4
@angular/material                16.2.3
@angular/material-experimental   16.2.13
@schematics/angular              17.1.4
rxjs                             7.8.1
typescript                       5.3.3
webpack                          5.89.0
zone.js                          0.14.4
```

**Comment by JoostK** [comment]
Please share the relevant code. Individual warnings cannot be disabled, but you may be able to adjust the code to avoid the warning.

**Comment by alan-agius4** [comment]
Closing as per answer above.
