### ISSUE TITLE
Option to generate component without stylesheet

### ISSUE THREAD

**Issue by pm20390** [angular/angular-cli#27679]
### Command

generate

### Description

For developers using tailwindcss, creating a CSS file when generating a component is unnecessary. It would be great to have an option to skip generating stylesheets.

### Describe the solution you'd like

A configuration in the angular.json file to skip generating stylesheets would be ideal.

**Comment by alan-agius4** [comment]
This is already supported. 

```
ng g component --style=none
```

See: https://angular.io/cli/generate#component-command

**Comment by pm20390** [comment]
Ah, apologies for that.
