### ISSUE TITLE
[Feature request - nice to haves] options to automatically run with proxy when proxy.conf.json file exists

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular-cli#2770]
### OS
> Windows 10.

### Versions.
>`1.0.0-beta.17`

This is not a bug, but a feature request, which should be a very low priority, but I thought I'd put it out anyway.

I have `proxy.conf.json` is place and every time I run `ng serve` I have to type in that lengthy `proxy-config proxy.conf.json` option. It'd be great if one could configure `cli` to run `ng serve` automatically with this option if the file is present.

**Comment by Meligy** [comment]
Hi @DmitryEfimenko. You probably do that already, but just in case, I wanted to mention that this is a very good use case for npm scripts.

In the generated project, the `start` script already calls `ng serve`. You can modify it to include the `proxy-config`, and then when you want to run the server, you just write `npm start`.

**Comment by DmitryEfimenko** [comment]
indeed this is a perfect use case for that. I do use npm scripts. My mind just for stuck on the use of angular-cli for starting. I'd say this issue can even be closed.
Thanks!
