### ISSUE TITLE
Dynamic inline module import is not working anymore

### ISSUE THREAD

**Issue by elementalTIMING** [angular/angular-cli#27710]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.3

### Description

In previous versions it was possible to import modules dynamically based on a variable inside of a method, like

	initTemplates(moduleName: string): Observable<ScoreboardModule> {

		// NOT WORKING ANYMORE
		let promise = import(`./layouts/${moduleName}/${moduleName}.module`);

		// THIS WORKS
		// let promise = import(`./layouts/BER/BER.module`);

		return from(promise).pipe(
			map(mod => mod.ScoreboardModule),
			map((module: any) => {
				// do some stuff

				return module;
			})
		);
	}

The `ng serve` output shows

	▲ [WARNING] The glob pattern import("./layouts/**/*/**/*.module") did not match any files [empty-glob]

	    src/app/mode.competition/components/scoreboard-viewer/scoreboardViewer.abstract.ts:30:29:
	      30 │ ...t promise = import(`./layouts/${moduleName}/${moduleName}.module`)
        	 ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

When accessing the code the application breaks with:

	 Error: Module not found in bundle: ./layouts/BER/BER.module
	    at chunk-SKK7EFDP.js:26:9

the additional paths are defined in `tsconfig.app.json` like this:

	{
		"extends": "./tsconfig.json",
		"compilerOptions": {
			"skipLibCheck": true,
			"outDir": "./out-tsc/app",
			"types": ["node"]
		},
		"files": ["src/main.ts", "src/polyfills.ts"],
		"include": ["src/**/*.d.ts", "src/app/mode.competition/components/scoreboard-viewer/layouts/**/*.ts"]
	}

This code was running as described above at least since Angular 13 and breaks suddenly now in Angular 18.

I'm assuming that the vite interprets the tsconfig include path in a wrong way, because `layouts/**/*/**/*.module` is nowhere defined but `layouts/**/*.ts`

Any ideas, on how to fix?

### Minimal Reproduction

The described issue is part of a real huge software package that cannot be extracted easily. I really hope that the error description is enough to identify the error, without a code example here.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 18.0.1
Node: 20.9.0
Package Manager: npm 10.8.0
OS: darwin arm64

Angular: 18.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker, youtube-player

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by elementalTIMING** [comment]
@alan-agius4 thx for your feedback, I tried, but it gives an error too.

	[WARNING] The glob pattern import("./layouts/**/*.module") did not match any files [empty-glob]

      src/app/mode.competition/components/scoreboard-viewer/scoreboardViewer.abstract.ts:32:29:
        32 │         let promise = import(`./layouts/${modulePath}.module`)
          ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

What make me so wonder is that it was working before v18 very well. Do you or anybody else have other ideas, please?

**Comment by alan-agius4** [comment]
Forgot to mention that you also need to include the extension. 

More information about glob style imports can be found https://esbuild.github.io/api/#glob

**Comment by elementalTIMING** [comment]
> Forgot to mention that you also need to include the extension.
> 
> More information about glob style imports can be found https://esbuild.github.io/api/#glob

Thx again for your feedback. But I thought it is already in the path. See my `tsconfig.app.json`

	{
		"extends": "./tsconfig.json",
		"compilerOptions": {
			"skipLibCheck": true,
			"outDir": "./out-tsc/app",
			"types": ["node"]
		},
		"files": ["src/main.ts", "src/polyfills.ts"],
		"include": ["src/**/*.d.ts", "src/app/mode.competition/components/scoreboard-viewer/layouts/**/*.ts"]
	}

Or is there anything other I need to do now in v18? This error is really confusing to me.

**Comment by alan-agius4** [comment]
The error arises because esbuild cannot find any files on disk that match `./layouts/**/*.module` relative to the import location. The setting in tsconfig configures which TypeScript files are included in the TypeScript program.

This issue is not due to a change in version 18, itself but rather a result of switching from webpack to esbuild. Did you switch from webpack to esbuild when updating to version 18?

**Comment by elementalTIMING** [comment]
> This issue is not due to a change in version 18, itself but rather a result of switching from webpack to esbuild. Did you switch from webpack to esbuild when updating to version 18?

ah, ok. Now I understand the reason.Thank you! But sorry for bothering - can you give me please a hint where and how I have to tell esbuild to use the path. I read the your send link https://esbuild.github.io/api/#glob, but the next steps are not clear to me. Sorry for my stupidity :-(

**Comment by alan-agius4** [comment]
Can you try to  add a `.ts` extension to the import?

**Comment by elementalTIMING** [comment]
> Can you try to add a `.ts` extension to the import?

Well, the warning message is gone but it gives now another runtime error

	The file does not exist at "/Volumes/Daten/Websites/SSCM.v3/.angular/cache/18.0.1/vite/deps/chunk-N6ABOZRB.js?v=86f604ff" which is in the optimize deps directory. The dependency might be incompatible with the dep optimizer. Try adding it to `optimizeDeps.exclude`.

I've already searched for `optimizeDeps.exclude` but it doesn't seem to exist or be considered in Angular.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by elementalTIMING** [comment]
> This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

I will try to do.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by shaktippatel** [comment]
I'm facing the same issue with dynamic inline module imports. My setup was working fine in previous Angular versions but breaks in Angular 18. The error message is:

`The glob pattern import("./abc/**/*/**/index.component") did not match any files [empty-glob]`

**Comment by carlos-morcillo** [comment]
I'm experiencing the same issue with dynamic inline module imports. My setup was working fine in previous versions of Angular but breaks in Angular 18.
