### ISSUE TITLE
After Upgrade from angular 17 to angular 18 the LOCALE_ID is always en_US

### ISSUE THREAD

**Issue by weberhofer** [angular/angular-cli#27722]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

In an existing project distributed for several locales, we are determining the current locale by:
```
export class MyClass {
...
	constructor(@Inject(LOCALE_ID) locale: string) { }
}
```
Up to angular 17 the value of LOCALE_ID always reflected the locale defined in the i18n section of the project's setting in angular.json; with Angular 18 the locale is always en_US. This is the case for "ng serve" builds as well as for distribution builds.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.1
Node: 20.12.1
Package Manager: npm 10.5.0
OS: linux x64

Angular: 18.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.1
@angular-devkit/build-angular   18.0.1
@angular-devkit/core            18.0.1
@angular-devkit/schematics      18.0.1
@angular/cli                    18.0.1
@schematics/angular             18.0.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by michaelkrog** [comment]
@alan-agius4 I am hitting the same issue.

I have tried to create a minimal repro from scratch.
https://github.com/michaelkrog/wrong-locale

I could only reproduce it if:
* The app uses ngmodule
* The app references a component in a library under another library.

Se https://github.com/angular/angular/issues/56182 for more details

**Comment by alan-agius4** [comment]
The problem is because in the library `import '@angular/localize/init'` is imported directly in your case. `@angular/localize/init` should not be imported, instead it should be added as a polyfill.

**Comment by michaelkrog** [comment]
@alan-agius4  🤥
You are totally right.
I forgot to rebuild the lib before serving the app again.

I can confirm that it works.

**Comment by weberhofer** [comment]
Sorry for the late response and thank you @michaelkrog for preparing the example and @alan-agius4 for the analysis.
The suggested way to include `@angular/localize/init` as polyfill solved the issue for me, too.
