### ISSUE TITLE
Keep CSS nesting in styles tags

### ISSUE THREAD

**Issue by Zefling** [angular/angular-cli#27729]
### Description

In Angular 17, it is possible to keep CSS nesting with this config:

```json
 "optimization": {
    "scripts": true,
    "styles": {
      "minify": false,
      "inlineCritical": true
    },
    "fonts": true
  }
```

![image](https://github.com/angular/angular/assets/3032555/5e26d35e-28c1-42af-a309-748651f992f9)

With Angular 18 this is no longer possible.

### Proposed solution

Add an option that allows you to keep CSS nesting

```json
      "CSSnesting": true,
```

### Alternatives considered

Or other option compilation option.

**Comment by alan-agius4** [comment]
@Zefling, I am not understanding the problem you are reporting.

**Comment by Zefling** [comment]
With angular 18, the CSS is flattened and doesn't have exactly the same behavior:
![image](https://github.com/angular/angular-cli/assets/3032555/6f6b753c-2f94-4389-8b37-5458616c0310)

**Comment by alan-agius4** [comment]
CSS will be transformed to a non-nested format if one or more browsers your application supports do not support nesting. Nesting will only be outputted if all supported browsers support fully this feature.

By default, Angular supports several browsers where nesting is not yet fully supported. These include:

```
Firefox 115 (Firefox ESR)
Safari 17.0 - 17.1
Safari 16.0 - 16.6
```

If you prefer not to support these browsers, you can update your browserslist configuration file. For more information, see: [Configuring Browser Compatibility](https://angular.dev/tools/cli/build#configuring-browser-compatibility) and [Angular Browser Support](https://angular.dev/reference/versions#browser-support).
