### ISSUE TITLE
Cannot find module 'ajv-formats'

### ISSUE THREAD

**Issue by ilyakonrad** [angular/angular-cli#27724]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

No idea, it's been appearing for more than 2 years.

### Description

It's been reported multiple times (https://github.com/angular/angular-cli/issues/22780, https://github.com/angular/angular-cli/issues/24291) but the issue comes back over and over.

We use Dependabot and in our setup it creates **minor** version upgrade PRs throughout the week and merges all of them every Monday morning, which triggers update of the server.

_Often_ times it results in the build error `An unhandled exception occurred: Cannot find module 'ajv-formats'`.

The way to "fix" it is to delete `yarn.lock` locally, reinstall `node_modules` and push the fresh yarn.lock file.

After doing so, with the help of version control system, you can see the "healing" changes in `yarn.lock`.

My question is why does it happen? Is it because Dependabot merges PRs some time after they were created and not right away?
But then, why does minor version upgrades break anything in the first place? And why is it always about `ajv-formats`?
Is it because it's alphabetically the first package that angular cli uses or is it the faulty package?

Anyway, I just don't think everything works perfectly if I have to manually solve random build errors every now and then.

### Minimal Reproduction

-

### Exception or Error

```text
An unhandled exception occurred: Cannot find module 'ajv-formats'
```

### Your Environment

```text
Angular CLI: 17.3.8
Node: 20.10.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.3.10
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@angular/fire                   17.0.1
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
webpack                         5.91.0
zone.js                         0.14.6
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by ilyakonrad** [comment]
@alan-agius4 I think it is an issue and I'm not the only one facing it, that's why I created an "issue".
But just in case it won't get fixed (because it hasn't been for so long), I would at least like to know the nature of it, that's why I added more questions in the description.

**Comment by ilyakonrad** [comment]
Thanks!

**Comment by ilyakonrad** [comment]
There aren't much details on the page you linked, so, for anyone interested, I've created a [new question](https://stackoverflow.com/questions/78539590/package-updates-often-cause-build-error-cannot-find-module-ajv-formats) on StackOverflow.
