### ISSUE TITLE
Module Aliasing

### ISSUE THREAD

**Issue by adstep** [angular/angular-cli#2772]
How do I build my project with a webpack config using a resolve.alias. I have a 3rd party library dependency that requires aliasing a module what is the best way of accomplishing this?

**Comment by filipesilva** [comment]
There is no way to directly access resolve.alias.

If you need typescript aliasing, you can just use the `paths` property in tsconfig.

If you need alias for sass/etc, this PR might help when it's merged: https://github.com/angular/angular-cli/pull/2747

**Comment by hyrumwhite** [comment]
@filipesilva File aliasing seems like a fairly trivial feature to add since it's built into webpack, and it's super helpful for keeping code clean. Any chance this feature is coming soon?
