### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by iraviguggilam** [angular/angular-cli#27737]
### Command

add, new

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

Routing not working inside project folder applications
localhost:4200/admin/dashboard

### Minimal Reproduction

Create New Project
`ng new <somename>` 
Create new application under projects
`ng g application admin` 
Add route in main app ( file name: app.routes.ts)
```
import { Routes } from '@angular/router';
import { AppComponent as AdminAppComponent } from '../../projects/admin/src/app/app.component';
export const routes: Routes = [
  {
    path: 'voice',
    component: AdminAppComponent,
  },
];
```
Create component under 
`ng g c dashboard`
Create route under Admin app
```
import { Routes } from '@angular/router';
import { AppComponent } from './app.component';
import { DashboardComponent } from './dashboard/dashboard.component';

export const routes: Routes = [
  {
    path: '',
    component: AppComponent,
    children: [
      { path: 'dashboard, component: DashboardComponent },
      { path: '**', redirectTo: 'dashboard' },
    ],
  },
];
```

### Your Environment

```text
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.3.8
Node: 20.12.0
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 17.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6
```

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
