### ISSUE TITLE
Sync with Angular 2.1 and TypeScript 2.0.3

### ISSUE THREAD

**Issue by tonysneed** [angular/angular-cli#2773]
Just wondering when Angular CLI will be updated for Angular 2.1 and TypeScript 2.0.3?

**Comment by Anufriev** [comment]
Were updated [chore: update typescript to ~2.0.3](ae56b89e728c69dc22fffec7ef6800c748d431e2) and [chore: update to Angular 2.1.0](bfc38626d4af47f8e9effc328a7a0b61fe470bee)

**Comment by tonysneed** [comment]
@Anufriev Thanks for the update! I'll stop rapping my fingers on the table for now. 😄

**Comment by grizzm0** [comment]
@tonysneed Could you please close as this has been resolved?

**Comment by tonysneed** [comment]
Yes, thanks for the update!
