### ISSUE TITLE
app doesnt rebuild when error in sass function is fixed

### ISSUE THREAD

**Issue by Siddhu-K** [angular/angular-cli#27750]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I am in the process of migrating to m3. 
I noticed that when mat.get-theme-color($theme, primary-container) gets an invalid parameter, I get an error in the terminal and fixing the parameter does not trigger a rebuild. I need to rerun ng s

### Minimal Reproduction

Use  mat.get-theme-color with incorrect color type like 'warn'.

ERROR
Valid color roles are: .......... Got: warn

fix warn with correct color type 'error'

app doesnt rebuild

### Your Environment

```text
Angular CLI: 18.0.2
Node: 20.11.1
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 18.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1800.2
@angular-devkit/core         18.0.2
@angular-devkit/schematics   18.0.2
@angular/build               18.0.2
@angular/cli                 18.0.2
@schematics/angular          18.0.2
rxjs                         7.8.1
typescript                   5.4.5
zone.js                      0.14.6
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by Siddhu-K** [comment]
@alan-agius4 I have created a minimal-repo.

https://github.com/Siddhu-K/repro-app

When I change the 'warn' to an accepted value such as 'error' in the component-theme.scss, the app doesn't rebuild. I need to terminate the process with 'ctrl+c' or kill the terminal and then run 'ng s' for it to work.
