### ISSUE TITLE
flag to run or skip all the optional migrations

### ISSUE THREAD

**Issue by alvaro-b-enguidanos** [angular/angular-cli#27751]
### Command

update

### Description

when running `ng update @angular/core@18 @angular/cli@18` a prompt appears  asking which migrations  would you like to run.

<img width="1131" alt="image" src="https://github.com/angular/angular-cli/assets/29378422/96364862-b45d-4078-912f-5589423eb78b">

In my company the migrations are executed through a CI system, so there are no human interaction. We just run a .sh that runs the needed commands for the update.
However, if now is required to manually interact with the prompting, our system will be no longer work.

I think that it will be very desirable to have some flag that allows to run the update completely automatically, by running or skipping all the optional migrations

### Describe the solution you'd like

Would be nice to have something like this:

`ng update @angular/core @angular/cli --runOptionalMigrations=true`

**Comment by alan-agius4** [comment]
Prompts are not displayed when the terminal is TTY. Typically on CI terminals are not. If for some reason your terminal is TTY, you can force disable TTY by using  the `NG_FORCE_TTY=false` environment variable.

**Comment by alvaro-b-enguidanos** [comment]
the issue isn't that the prompt is not displaying, the issues is that isn't possible nor desirable for us, to interact with the prompting. we can't depend on human interaction to run the update, ence, the need for the flag to avoid that prompting

**Comment by alan-agius4** [comment]
@alvaro-b-enguidanos, you can disable the prompts by using the `NG_FORCE_TTY=false` environment variable. 

Alternatively, you can also configure your CI environment to disable TTY, which in general it’s recommended, if it’s not done by default.
