### ISSUE TITLE
Angular 2 Unexpected value 'MyDirective' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular-cli#2776]
I am trying to create npm library with one directive and test it locally with the help of npm link.

But the problem is when I am including my directive in the declarations array I am getting this error:

`Unexpected value 'MyDirective' declared by the module 'AppModule'`

My library structure:

**package.json**

```js
{
   "name": "my-directive",
   "main": "./dist/index.js",
   "typings":  "dist/index.d.ts"
 }
```

**My src folder:**

**index.ts**

`export * from "./myDirective";`

**myDirective.ts**

```js
import {Directive} from '@angular/core';

@Directive({
  selector: "my-directive"
})
export class MyDirective {
  constructor() {
    console.log('directive works!');
  }
}
```

Now in my Angular 2 app that I'm linking this npm package:

```js
import { MyDirective } from "my-directive";

// This line indeed log the constructor function...
console.log(MyDirective);
 // function MyDirective() {
    // console.log('directive works!');
 // }

@NgModule({
  declarations: [
    AppComponent,
    MyDirective
  ]
})
```

It's throwing the error:
`Unexpected value 'MyDirective' declared by the module 'AppModule'`

**Comment by ShiftySituation** [comment]
[https://github.com/angular/angular-cli/issues/2775](url) Not sure if he means this was already fixed and just waiting on a new build.

**Comment by bstumbo** [comment]
The import in npm package should be `import { MyDirective } from "./my-directive";`

Not `import { MyDirective } from "my-directive";`

**Comment by ArielGueta** [comment]
It should be:
` import { MyDirective } from "my-directive";`

Because it is an npm module - I linked the package

**Comment by cacogr** [comment]
Try declaring and exporting the directive in its own module in the npm package and then importing (not declare) it in AppModule to see if it works.

**Comment by ArielGueta** [comment]
This is what I did. I mentioned that the import worked. If you read the code you will see that the console log indeed log the constructor function of the directive.

**Comment by filipesilva** [comment]
Think I've seen this before, and I don't think we can do anything about it. See https://github.com/angular/angular-cli/issues/1514#issuecomment-240910842
