### ISSUE TITLE
After migrating to vite, routes with a "." do not work anymore

### ISSUE THREAD

**Issue by nhnb** [angular/angular-cli#27760]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

After migrating to esbuild/vite, all routes with a dot in the URL will fail to load, if invoked directly from the browser address bar.

The same routes are working fine, if navigating to from within the Angular app.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/dots-in-url?file=src%2Fapp%2Fapp.routes.ts

### Please provide the exception or error you saw

Please add `/heroes-list.html` or `/crisis-list` to the end of the URL in the navigation bar on the right side of the source code.

`/crisis-list` works fine. But `/heroes-list.html` results in the following error message:

```
Cannot GET /heroes-list.html`
```

The stackblitz is just a small example. I am seeing this issue in a large Angular application, which worked fine with Webpack.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
@angular-devkit/architect       0.1800.2
@angular-devkit/build-angular   18.0.2
@angular-devkit/core            18.0.2
@angular-devkit/schematics      18.0.2
@angular/cli                    18.0.2
@schematics/angular             18.0.2
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.6


The same issue occurs on 17.3.4
```

### Anything else?

https://github.com/angular/angular-cli/issues/26881 claims that the issue was fixed in 17.1.0. But versions 17.3.4 and 18.0.0 are still broken as well.

**Comment by alan-agius4** [comment]
Why do you include file extensions in your SPA routes? Including file extensions in routes is often due to legacy systems or a desire for clarity. However, this practice isn't ideal for SPAs as modern best practices favor clean, extensionless URLs. They enhance user experience, aid SEO, and ensure consistency across routes.

**Comment by nhnb** [comment]
Exactly those two reasons:

1) Keeping existing URLs working

2) Communicating to users that this is a "stable" URL, that can safely be shared. Our users also work with Webflow based systems in which the URL consists of a flow key and will not work after logout / for other users.

So yeah, we could rewrite URLs on the webserver to deal with 1). And we could try to educate users, that the URLs in our system are stable for 2).

I did not test this case: Would an URL like https://example.com/angularapp/share/My+Thesis+1.+Draft cause the same issue?

I realize that the issue only affects developers, so it's not a big deal.

**Comment by alan-agius4** [comment]
> I did not test this case: Would an URL like https://example.com/angularapp/share/My+Thesis+1.+Draft cause the same issue?

No, that would work. The issue with `heroes-list.html` arises because the route contains a valid file extension, and hence the code path for static files is being triggered.
