### ISSUE TITLE
The way to different path mapping between server and browser when using application builder 

### ISSUE THREAD

**Issue by leo6104** [angular/angular-cli#27764]
### Command

build, serve

### Description

When i upgrade webpack builder to application builder, There is limits for server side rendering. 

I use `pdfjs-dist` which include `canvas.node` binding dependencies. 
In browser serving & build process, `pdfjs-dist` can be bundled without errors.
However, in server side, there is no `.node extension loader` so it raise `No loader is configured for ".node" files: node_modules/canvas/build/Release/canvas.node`. 

Previously, to avoid this problem with webpack builder, i just add `path mapping rule` in `tsconfig.server.json` only. 

```json
 "paths": {
    "pdfjs-dist": [ "../../mock/pdfjs.ts" ],
    ... 
 },
```

In @angular-devkit webpack or browser-esbuild, it is available to setup tsconfig for server side. 
In @angular-devkit/build-angular:application, it is not available to add `tsconfig.server.json` so cannot use this kind of path mapping. 

### Describe the solution you'd like

I saw 'webWorkerTsConfig' in `angular.json` schema. 

Can we add 'serverTsConfig' option like `webWorkerTsConfig`?

**Comment by alan-agius4** [comment]
Hi @leo6104, I am unable to replicate the reported problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by leo6104** [comment]
@alan-agius4 Thanks for comment 😊 

Here is repro repository.
https://github.com/leo6104/ng-app-builder-error 

Here is 3 commands i made in `package.json`
```command
npm run app:serve  -> it will raise error (canvas node binding) 
npm run webpack:serve -> correctly serving `pdf-viewer` component
npm run webpack:serve-ssr -> correctly serving `pdf-viewer.ssr` component with path mapping
```
