### ISSUE TITLE
Unsupported URL Type "workspace:": workspace:*

### ISSUE THREAD

**Issue by spc16670** [angular/angular-cli#27762]
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

`npm i -D @angular-builders/jest`

fails with 

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

### Minimal Reproduction

`npm i -D @angular-builders/jest`

### Your Environment

```text
Angular CLI: 18.0.2
Node: 20.14.0
Package Manager: npm 8.5.5
OS: win32 x64

Angular: 18.0.1
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1800.2
@angular-devkit/build-angular      18.0.2
@angular-devkit/core               18.0.2
@angular-devkit/schematics         18.0.2
@angular/cdk                       17.3.9
@angular/cli                       18.0.2
@angular/material                  17.3.9
@angular/material-moment-adapter   17.3.9
@schematics/angular                18.0.2
rxjs                               6.6.7
typescript                         5.4.5
zone.js                            0.14.5
```

**Comment by spc16670** [comment]
83 http fetch GET 200 https://registry.npmjs.org/protractor 52ms (cache revalidated)
84 silly fetch manifest @angular/platform-browser-dynamic@^18.0.1
85 http fetch GET 200 https://registry.npmjs.org/@angular%2fplatform-browser-dynamic 86ms (cache revalidated)
86 silly placeDep ROOT @angular-builders/jest@18.0.0-beta.2 OK for: myproject@0.0.0 want: *
87 silly fetch manifest jest-preset-angular@14.1.0
88 timing idealTree Completed in 6531ms
89 timing command:i Completed in 6538ms
90 verbose stack Error: Unsupported URL Type "workspace:": workspace:*
90 verbose stack     at unsupportedURLType (<pathonmymachine>\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:262:15)
90 verbose stack     at fromURL (<pathonmymachine>\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:322:13)
90 verbose stack     at Function.resolve (<pathonmymachine>\node_modules\npm\node_modules\npm-package-arg\lib\npa.js:80:12)
90 verbose stack     at <pathonmymachine>\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1054:38
90 verbose stack     at Array.map (<anonymous>)
90 verbose stack     at visit (<pathonmymachine>\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1053:56)
90 verbose stack     at visitNode (<pathonmymachine>\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:57:25)
90 verbose stack     at next (<pathonmymachine>\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:44:19)
90 verbose stack     at depth (<pathonmymachine>\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:82:10)
90 verbose stack     at depth (<pathonmymachine>\node_modules\npm\node_modules\treeverse\lib\depth.js:27:12)
91 verbose cwd <pathonmymachine>\myproject
92 verbose Windows_NT 10.0.22631
93 verbose argv "<pathtonode>\\20.14.0\\node.exe" "<pathonmymachine>\\node_modules\\npm\\bin\\npm-cli.js" "i" "-D" "@angular-builders/jest"
94 verbose node v20.14.0
95 verbose npm  v8.5.5
96 error code EUNSUPPORTEDPROTOCOL
97 error Unsupported URL Type "workspace:": workspace:*
98 verbose exit 1
99 timing npm Completed in 6731ms
100 verbose unfinished npm timer reify

**Comment by clydin** [comment]
`@angular-builders/jest` is a third-party package that is not maintained by the Angular team. Please open an issue for that package here: https://github.com/just-jeb/angular-builders
