### ISSUE TITLE
__filename is not defined

### ISSUE THREAD

**Issue by Jacky-Young1123** [angular/angular-cli#27777]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

While enabling SSR (Server-Side Rendering) in the development of a Solana Web3 application using Angular, such an error occurs. The packages used are solana-connect ^0.1.10 and @solana/wallet-adapter-base ^0.9.23.
![image](https://github.com/angular/angular/assets/171530490/6f9bbb82-60af-4517-906c-4c4fc646a141)

**Comment by alan-agius4** [comment]
This is expected since `__filename` is not available in ESM modules. You can polyfill this by adding `globalThis.__filename = import.meta.filename;` before the import in Node.js 20.11.x or later.
