### ISSUE TITLE
Sass errors after migrating from Angular 14 to 15

### ISSUE THREAD

**Issue by amalamalamal** [angular/angular-cli#27799]
### Command

serve

### Description

I migrate from angular 14 to angular 15, i'am using sass through bootstrap but when trying to start the application i have this error:

./src/sass/styles.scss - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: $color: inherit is not a color.
    ╷
185 │     "r": red($color),
    │          ^^^^^^^^^^^
    ╵
  bootstrap\scss\_functions.scss 185:10                             luminance()
  bootstrap\scss\_functions.scss 174:8                              contrast-ratio()
  bootstrap\scss\_functions.scss 159:22                             color-contrast()
  bootstrap\scss\_variables.scss 846:42                             @import

it seems that it is enable to import styles?

**Comment by alan-agius4** [comment]
Angular version 15 is no longer supported. 

See: https://angular.dev/reference/releases#actively-supported-versions

**Comment by amalamalamal** [comment]
Yes i know, but actually i have to use Angular 15, can you help with my problem please?

**Comment by JeanMeche** [comment]
@amalamalamal You should ask this question on either stackoverflow or the Angular discord. This is not a support forum.
