### ISSUE TITLE
Debugging in Visual Studio

### ISSUE THREAD

**Issue by chrstnbrn** [angular/angular-cli#2779]
OS: Windows 10
angular-cli: 1.0.0-beta.17
node: 6.5.0

I have an ASP.NET Core project in Visual Studio which includes an Angular app. The Angular app was not created by angular-cli but I've included it and it is working fine. I'm using ng build to build the application and set my outDir to wwwroot. I can then run my app using IIS Express. 

I would like to be able to debug my TypeScript files in Visual Studio. However if I set a breakpoint it is not being hit.  I've seen other issues here asking about debugging for Visual Studio Code and WebStorm, so I think there might be a similar solution. Does anyone have an idea how to achieve this in Visual Studio?

**Comment by filipesilva** [comment]
Flagging for community help, I don't have any specific help myself though.

**Comment by maxime1992** [comment]
I spent many hours on this and I finally figure it out.

See the [post](http://stackoverflow.com/questions/40443217/debug-with-visual-studio-code-not-working) on stackoverflow and the [answer](http://stackoverflow.com/a/40449023/2398593).

**Comment by filipesilva** [comment]
@maxime1992 this issue is for Visual Studio, not Visual Studio Code. Configurations for VS Code debugging can be found in https://github.com/angular/angular-cli/issues/2453.

**Comment by filipesilva** [comment]
(closed by mistake)

**Comment by chrstnbrn** [comment]
I just tried this again and I am now able to debug my TypeScript files in Visual Studio. I'm using angular-cli 1.0.0-beta.19-3 and am not aware of changing anything else that could be related to debugging.

**Comment by raberana** [comment]
@chrstnbrn what steps exactly did you follow to debug it with Visual Studio? (not vs code)

**Comment by rdesimone** [comment]
@chrstnbrn I would also be interested if you could share your configuration for Visual Studio (not VS Code). Thanks!

**Comment by challe** [comment]
@chrstnbrn me too.
