### ISSUE TITLE
--ssr upon ng build does not create a server.mjs file

### ISSUE THREAD

**Issue by notyodeas** [angular/angular-cli#27808]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

--ssr upon ng build does not create a server.mjs that is created without the ssr flag, all other mjs files do get created but not the one you can run on a remote machine

### Minimal Reproduction

ng new bugreport
choose css stylesheet
answer yes if you want to enable ssr
ng build --ssr

### Exception or Error

```text
not a single file that will run angular on its port in the dist/bugreport/server folder```


### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.7
Node: 18.20.3
Package Manager: npm 10.7.0
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1703.7 (cli-only)
@angular-devkit/core         17.3.7 (cli-only)
@angular-devkit/schematics   17.3.7 (cli-only)
@schematics/angular          17.3.7 (cli-only)
```

**Comment by alan-agius4** [comment]
By using `--ssr` option you are overriding the configuration present in `angular.json` from `"ssr": { "entry": "server.ts" }` to `"ssr": true`. 

In this case, you do not need to specify the `--ssr` option when running `ng build`.

```
$ ng build
$ node dist/bugreport/server/server.mjs
```

**Comment by ArnaudT** [comment]
Hello there,

We have the same issue. All the mjs files are generated but not the `server.mjs` file.

Did you found a solution?
