### ISSUE TITLE
Project that used to work no longer works.

### ISSUE THREAD

**Issue by dwatts1772** [angular/angular-cli#2780]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 and Linux Mint 18 Cinnamon 64-bit

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.17
node: 6.8.0
os: linux x64

Have tried on other versions of angular-cli (beta.15 and beta.16)
Have tried other version of node v6 (6.5.0, 6.8.1)

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Upgraded angular-cli to latest beta from beta.15 (might have initially upgraded to @angular 2.1.0).  When running `ng build` or `ng server` all I get is "Error" as well as an "Exit code 1".  No way to add more verbose logging to angular-cli itself??

### The log given by the failure.
> Normally this include a stack trace and some more information.

```
➜  GWDM git:(master) ✗ ng build
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Error

➜  GWDM git:(master) ✗ ng serve
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Error
```
### Mention any other details that might be useful.

I was able to get (at one point) the "Could not start watchman" to not be an issue but it would still error out giving the same "Error" exception.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dreadbeard** [comment]
Figured out what the issue was.  

Had a commented css file in my angular-cli.json
```
"styles": [
        //"../node_modules/bootstrap/dist/css/bootstrap.css",
        "../node_modules/tether/dist/css/tether.css",
        "./css/styles.scss"
      ],
```

....

**Comment by filipesilva** [comment]
Heya, glad to hear you've figured it out. We added better error reporting for `angular-cli.json` errors in https://github.com/angular/angular-cli/pull/2565, which is out with beta.18.
