### ISSUE TITLE
Incremental angular build with esbuild can't locate secondary entrypoints in 3rd party libraries

### ISSUE THREAD

**Issue by sonikasharma1403** [angular/angular-cli#27805]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Incremental build with angular esbuild (@nx/angular:browser-esbuild and buildLibsFromSource=false) fails if referencing library secondary entrypoints in the code. It works with webpack (@nx/angular:webpack-browser), or when referencing secondary entrypoints in external libraries (from npm) (3rd party modules)

### Please provide the exception or error you saw

```true
base.tsconfig.json has paths as `
  "paths": {
      "@cds/core": [
        "node_modules/@test/clr-core"
      ],
      "@cds/core/*": [
        "node_modules/@test/clr-core/*"
      ],

`
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
latest angular with Nx
```

### Anything else?

<img width="902" alt="image" src="https://github.com/angular/angular/assets/86649832/aebaea57-8b4c-4a13-9f78-3099c8c52766">

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by JoostK** [comment]
Does this also apply to `@angular/angular:browser-esbuild`, not Nx's variant? They are different builders.

**Comment by clydin** [comment]
If those secondary entrypoints are using the `package.json` `exports` field then this is expected behavior.  TypeScript specifically does not support this scenario and does not recommend using the `paths` option to map to node modules.
TypeScript Documentation on the topic: https://www.typescriptlang.org/docs/handbook/modules/reference.html#paths-should-not-point-to-monorepo-packages-or-node_modules-packages

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
