### ISSUE TITLE
prerender build failed to generate

### ISSUE THREAD

**Issue by rajasekar-d** [angular/angular-cli#27815]
### Command

build

### Description

Angular 18 failed to generate prerender

routes.txt
`/auth/register`

angular.json
```
"prerender": {
   "discoverRoutes": false,
   "routesFile": "routes.txt"
}
```

app.config.ts
```
provideRouter(
   routes,
   withPreloading(CustomPreloadingStrategy),
   withRouterConfig({
      onSameUrlNavigation: 'reload'
   }),
   withViewTransitions()
)
```
    
app.routes.ts
```
{ 
   path: 'auth/register',
   component: RegisterComponent
}
```

**ng build**

![Error](https://github.com/angular/angular-cli/assets/11868287/323f8f47-6a7f-45ff-aeda-22dc7a9248f9)

Disabling the prerender generates the build correctly but when i use prerender it throws below error 
```
code: 'ERR_INVALID_URL',
input: '/auth/register'
```
  

### Minimal Reproduction

Run
`ng b`

### Exception or Error

```
code: 'ERR_INVALID_URL',
input: '/auth/register'
```

### Your Environment

```text
18.0.3
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by rajasekar-d** [comment]
I identified the root cause of the issue: when i use `new URL(window.location.href).pathname` in the code, Angular to fail to prerender because the window object won't available on the server side.

You can close this issue.
