### ISSUE TITLE
Erro ao executar "ng serve" na pasta do projeto 

### ISSUE THREAD

**Issue by SamuelRenan** [angular/angular-cli#27821]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

Ao executar o comando "ng serve" na pasta do projeto aparece o seguinte erro: 

![image](https://github.com/angular/angular-cli/assets/103660872/0e0f551a-1414-465c-956b-c8da90b79756)

### Minimal Reproduction

Após a execução do "npm i"  depois de ter atualizado as dependências do Angular, para iniciar o meu projeto em PO-UI, após eu executar o "ng serve" aparece o seguinte erro: 

X [ERROR] TS2307: Cannot find module '@angular/ssr' or its corresponding type declarations. [plugin angular-compiler]

    server.ts:2:29:
      2 │ import { CommonEngine } from '@angular/ssr';
        ╵                              ~~~~~~~~~~~~~~

X [ERROR] TS7006: Parameter 'html' implicitly has an 'any' type. [plugin angular-compiler]

    server.ts:40:13:
      40 │       .then((html) => res.send(html))
         ╵              ~~~~

X [ERROR] TS7006: Parameter 'err' implicitly has an 'any' type. [plugin angular-compiler]

    server.ts:41:14:
      41 │       .catch((err) => next(err));
         ╵               ~~~

X [ERROR] TS2307: Cannot find module '@angular/platform-server' or its corresponding type declarations. [plugin angular-compiler]

    src/app/app.module.server.ts:2:29:
      2 │ import { ServerModule } from '@angular/platform-server';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~

X [ERROR] TS-991010: Value at position 1 in the NgModule.imports of AppServerModule is not a reference
  Value could not be determined statically. [plugin angular-compiler]

    src/app/app.module.server.ts:8:11:
      8 │   imports: [
        ╵            ^

  Unknown reference.

    src/app/app.module.server.ts:10:4:
      10 │     ServerModule,
         ╵     ~~~~~~~~~~~~

X [ERROR] Could not resolve "@angular/platform-server"

    angular:server-render-utils:angular:server-render-utils:2:66:
      2 │ ..., renderModule, ɵSERVER_CONTEXT } from '@angular/platform-server';
        ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@angular/platform-server" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@angular/platform-server"

    src/app/app.module.server.ts:3:29:
      3 │ import { ServerModule } from '@angular/platform-server';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@angular/platform-server" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

X [ERROR] Could not resolve "@angular/platform-server/init"

    angular:polyfills-server:angular:polyfills-server:2:7:
      2 │ import '@angular/platform-server/init';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@angular/platform-server/init" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

Watch mode enabled. Watching for file changes... 

### Exception or Error

```text
X [ERROR] TS2307: Cannot find module '@angular/ssr' or its corresponding type declarations. [plugin angular-compiler]

    server.ts:2:29:
      2 │ import { CommonEngine } from '@angular/ssr';
        ╵                              ~~~~~~~~~~~~~~


X [ERROR] TS7006: Parameter 'html' implicitly has an 'any' type. [plugin angular-compiler]

    server.ts:40:13:
      40 │       .then((html) => res.send(html))
         ╵              ~~~~


X [ERROR] TS7006: Parameter 'err' implicitly has an 'any' type. [plugin angular-compiler]

    server.ts:41:14:
      41 │       .catch((err) => next(err));
         ╵               ~~~


X [ERROR] TS2307: Cannot find module '@angular/platform-server' or its corresponding type declarations. [plugin angular-compiler]

    src/app/app.module.server.ts:2:29:
      2 │ import { ServerModule } from '@angular/platform-server';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~


X [ERROR] TS-991010: Value at position 1 in the NgModule.imports of AppServerModule is not a reference
  Value could not be determined statically. [plugin angular-compiler]

    src/app/app.module.server.ts:8:11:
      8 │   imports: [
        ╵            ^

  Unknown reference.

    src/app/app.module.server.ts:10:4:
      10 │     ServerModule,
         ╵     ~~~~~~~~~~~~


X [ERROR] Could not resolve "@angular/platform-server"

    angular:server-render-utils:angular:server-render-utils:2:66:
      2 │ ..., renderModule, ɵSERVER_CONTEXT } from '@angular/platform-server';
        ╵                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@angular/platform-server" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


X [ERROR] Could not resolve "@angular/platform-server"

    src/app/app.module.server.ts:3:29:
      3 │ import { ServerModule } from '@angular/platform-server';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@angular/platform-server" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


X [ERROR] Could not resolve "@angular/platform-server/init"

    angular:polyfills-server:angular:polyfills-server:2:7:
      2 │ import '@angular/platform-server/init';
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@angular/platform-server/init" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.


Watch mode enabled. Watching for file changes...
```

### Your Environment

```text
Angular CLI: 18.0.3
Node: 20.14.0
Package Manager: npm 10.7.0
OS: win32 x64

Angular: 18.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.3
@angular-devkit/build-angular   18.0.3
@angular-devkit/core            18.0.3
@angular-devkit/schematics      18.0.3
@angular/cli                    18.0.3
@schematics/angular             18.0.3
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by alan-agius4** [comment]
As shown in `ng version` these packages are not installed, likely this is because they are not listed as dependencies in your `package.json`.


Can you please provide the reproduction steps on how your project ended in this state?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.
