### ISSUE TITLE
After upgrade from Angular 17 to 18:  Builder Updated Automatically From @angular-devkit/build-angular:browser to @angular-devkit/build-angular:application

### ISSUE THREAD

**Issue by ChaitanyaBabar** [angular/angular-cli#27839]
### Command

update

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17

### Description

I have upgrade from Angular 17 to 18 with:

```
ng update @angular/core@18 @angular/cli@18 --force
ng update @angular/material@18 --force
```

### Two Issues.

1. Running above *commands auto-upgraded* my builder from `"builder": "@angular-devkit/build-angular:browser" `to `"builder": "@angular-devkit/build-angular:application`".

But as per docs [here](https://angular.dev/tools/cli/build-system-migration) it *should not*.

![image](https://github.com/angular/angular-cli/assets/6712223/be96bfa2-d165-4bf0-9e97-ff5cf570d32f)

2. As in new `"builder": "@angular-devkit/build-angular:application",` Angular cli defaults the **target to 2022** as per release docs [here](https://github.com/angular/angular-cli/blob/main/CHANGELOG.md).

![image](https://github.com/angular/angular-cli/assets/6712223/d97bdf62-38f9-4c9b-8bbb-75f25575bf4d)

**How should *we add support to browsers* that do not support "ES2022" features as we new builder is targeting to "ES2022".**

### Minimal Reproduction

N/A

### Exception or Error

```text
N.A
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 18.0.3
Node: 20.12.2
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 18.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1800.3
@angular-devkit/build-angular      18.0.3
@angular-devkit/build-ng-packagr   0.1000.7
@angular-devkit/core               18.0.3
@angular-devkit/schematics         18.0.3
@angular/cli                       18.0.3
@schematics/angular                18.0.3
ng-packagr                         18.0.0
rxjs                               6.5.5
typescript                         5.4.5
zone.js                            0.14.5
```

### Anything else relevant?

N/A

**Comment by alan-agius4** [comment]
> Running above commands auto-upgraded my builder from "builder": "@angular-devkit/build-angular:browser" to "builder": "@angular-devkit/build-angular:application".

Indeed this is an opt-in migration when running `ng update` you get asked if you'd like to update. If you choose no, you will not be updated. 

> As in new "builder": "@angular-devkit/build-angular:application", Angular cli defaults the target to 2022 as per release docs [here](https://github.com/angular/angular-cli/blob/main/CHANGELOG.md).

This is the same as per the webpack based builder and has been been the case since version 15. The browserslist configuration is used to determine the supported syntax. See: https://angular.dev/tools/cli/build#configuring-browser-compatibility
