### ISSUE TITLE
[Discussion] testing stub location

### ISSUE THREAD

**Issue by intellix** [angular/angular-cli#2784]
I'm attempting to test a component that takes an `:id` ActivatedRoute param. 
Looking through the testing documentation I stumbled upon this snippet of information for creating a stub: https://angular.io/docs/ts/latest/guide/testing.html#!#_observable_-test-double

```
We recommend locating such helpers in a testing folder sibling to the app folder. This sample keeps ActivatedRouteStub in testing/router-stubs.ts
```

I've created a directory as suggested: `src/testing` but no matter what I do to import it, it's not able to find it. I assume angular-cli has webpack setup for importing only from `node_modules` or `src/app`.

I'd prefer if Angular provided some of these stubs inside `@angular/router/testing` but that doesn't seem to be the case and we may need custom stubs in the future anyway.

Where should stubs live and what should they be named regarding convention?

Maybe: `activated-route.stub.ts`, `activated-route.stub.spec.ts`, `activated-route-stub.service.ts`

**Comment by filipesilva** [comment]
@intellix we do have some webpack config to limit the loading context, but it should be set to `src/` so your setup should work. Can you give me a small repro that I can run that exhibits the failure?

**Comment by intellix** [comment]
I guess we can kill this now. I just tested again and it works:

file: `src/testing/something.mock.ts`
used by: `import { SomethingMock } from 'testing/something.mock';`
