### ISSUE TITLE
accept git remote as an option for github pages deploy

### ISSUE THREAD

**Issue by craigmichaelmartin** [angular/angular-cli#2786]
Feature request: accepting a git remote name as an option for github pages deploy. If acceptable, I would be happy to implement.

Use cases
- Devs who use a different upstream remote name than `origin`.
- Devs who wish to deploy to their fork as part of a review step.

Workarounds
- `git remote rename`

Alternatives
- If not acceptable, I'd be happy to submit a PR to add a note to the README and/or the output message when there is no remote found for `origin`.

**Comment by filipesilva** [comment]
I'm happy to review a PR for this enhancement, but would like to mention that we're likely reworking the github deploy functionality to use the `docs` folder as mentioned in https://github.com/blog/2228-simpler-github-pages-publishing.

**Comment by filipesilva** [comment]
Closed via https://github.com/angular/angular-cli/pull/4385.
