### ISSUE TITLE
"fatal: bad object 7e55907cd54a2e91b96d25a660acc6a2a6453f54" error on 1.0.0-beta.15 and above

### ISSUE THREAD

**Issue by aitoribanez** [angular/angular-cli#2788]
I'n on a linux mint machine with 4.4.0-31 kernel, 5.12.0 node version and 3.10.8 npm version.

* Steeps:

1.- I install angular-cli using npm => npm install -g angular-cli.
2.- I create a new project => ng new my-super-app

This is the package.json file content at this point:

[{
  "name": "my-super-app",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "~2.0.0",
    "@angular/compiler": "~2.0.0",
    "@angular/core": "~2.0.0",
    "@angular/forms": "~2.0.0",
    "@angular/http": "~2.0.0",
    "@angular/platform-browser": "~2.0.0",
    "@angular/platform-browser-dynamic": "~2.0.0",
    "@angular/router": "~3.0.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.17",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.9",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}](url)

I get the "fatal: bad object 7e55907cd54a2e91b96d25a660acc6a2a6453f54" during ng new my-super-app.

If I change 1.0.0-beta.17 dependency for 1.0.0-beta.15, the installation goes well. If I try with 1.0.0-beta.16 I get the same error.

Thanks!

**Comment by filipesilva** [comment]
I think I know what it is. https://github.com/angular/angular-cli/commit/b57d1bd1468f1605c9d1c01b815e7ddd8095138f should fix it and be included in beta.18.

**Comment by aitoribanez** [comment]
Fixed on beta.18. Right! :-)

Great job! 
The best!
