### ISSUE TITLE
Snapdragon X Elite Arm / Windows , No native build was found for platform=win32 arch=arm64

### ISSUE THREAD

**Issue by ssdeepak** [angular/angular-cli#27882]
### Which @angular/* package(s) are the source of the bug?

compiler, core, Don't known / other

### Is this a regression?

Yes

### Description

 I tried Angular 18 on my  new Snapdragon X Elite

When I try to run the project from VSCode I get this error. 
No native build was found for platform=win32 arch=arm64 runtime=node abi=127 uv=1 armv=8 libc=glibc node=22.3.0
    attempted loading from: D:\Junk\my-app\node_modules\lmdb and package: @lmdb/lmdb-win32-arm64
 

### Please provide the exception or error you saw

```true
ng serve --o
Application bundle generation failed. [0.406 seconds]

X [ERROR] No native build was found for platform=win32 arch=arm64 runtime=node abi=127 uv=1 armv=8 libc=glibc node=22.3.0
    attempted loading from: D:\Junk\my-app\node_modules\lmdb and package: @lmdb/lmdb-win32-arm64
 [plugin angular-compiler]
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.0.4
Node: 22.3.0
Package Manager: npm 10.8.1
OS: win32 arm64

Angular: 18.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cli                    18.0.4
@schematics/angular             18.0.4
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

### Anything else?

React JS works Fine on the same platform

**Comment by alan-agius4** [comment]
I have reported an issue to the upstream repository: [GitHub Issue #295](https://github.com/kriszyp/lmdb-js/issues/295).

**Comment by sykum** [comment]
same here it's annoing to stuck on angular 17 😢

**Comment by alan-agius4** [comment]
This should no longer error when using Angular CLI version 18.1.

**Comment by sykum** [comment]
Thank you very much for the info and I look forward to testing it and will give feedback.

**Comment by atsjo** [comment]
Why not add imdb as an optional dependency instead since it actually is from 18.1 @alan-agius4 ? My project now fails pnpm install on windows arm64, and I worked around this by adding:

```
  "pnpm": {
    "overrides": {
      "@angular/build>lmdb": "-"
    }
  },
  "optionalDependencies": {
    "lmdb": "3.1.3"
  }
```

If lmdb was added via optionalDependencies in @angular/build then pnpm install would work without workarounds, and just drop install and show your runtime warning on unsupported platforms...
