### ISSUE TITLE
feature 🏗 option to generate cfile compatible error file

### ISSUE THREAD

**Issue by Milldrew** [angular/angular-cli#27884]
### Command

serve

### Description

```
ng serve --error-file
```

This command would generate a file in the root of the angular workspace that would track the current errors

error-file.txt
```
/Users/milldrew/readme.txt:2:2:angular error code message
/Users/milldrew/readme.txt:10:2:angular error code message
```

within vim we could run the cfile command to go directly to the line and column of the error
```
:cfile error-file.txt
```
to read about cfile in vim
```
:h cfile
```
This will make it easy for vim users to write small vim scripts that handle angular project navigation powerfully

I can build this feature for the command line and write the docs if this feature is approved. Unless someone else wants to.

Thanks!!

### Describe alternatives you've considered

I didn't see any existing ways to do this. please let me know if there is. Thanks!

**Comment by alan-agius4** [comment]
Hello @Milldrew, thank you for your request. Unfortunately, incorporating this option is not currently part of our plans. You should be able to redirect/pipe the output to generate the required format.
