### ISSUE TITLE
Sudden Error: "Looks like you have a different program called watchman"

### ISSUE THREAD

**Issue by HomeboxJim** [angular/angular-cli#2789]
Mac OSX 10.11.6

Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://ember-cli.com/user-guide/#watchman for more info.

ng -v:
angular-cli: 1.0.0-beta.15
node: 4.5.0
os: darwin x64

I was happily developing on my project. Then I hit ctrl + C to end the watching process in the terminal. Now my project is completely broken, and when running ng serve I get this useless error message:

Looks like you have a different program called watchman, falling back to NodeWatcher.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Error

How can I fix this??

**Comment by nikejaycn** [comment]
https://github.com/angular/angular-cli/issues/2755#issuecomment-254436966

**Comment by filipesilva** [comment]
If you're just seeing the message 'Error', this might be a broken `angular-cli.json`. https://github.com/angular/angular-cli/pull/2565 fixed the message but was included only on beta.18. I recommend updating and opening a new issue if the problem persists.
