### ISSUE TITLE
Upgrade TypeScript to 1.8

### ISSUE THREAD

**Issue by jpdonaghy** [angular/angular-cli#279]
CLI currently depends on TypeScript ~1.7.3, please upgrade to support TypeScript 1.8.

From the /node_modules/angular-cli/package.json of a project generated by angular-cli 0.0.24.

"dependencies": {
    "broccoli": "^0.16.9",
    "broccoli-concat": "0.0.13",
    "broccoli-funnel": "^1.0.1",
    "broccoli-merge-trees": "^1.0.1",
    "broccoli-writer": "^0.1.1",
    "chalk": "^1.1.0",
    "ember-cli": "1.13.15",
    "exit": "^0.1.2",
    "fs-extra": "^0.18.4",
    "leek": "0.0.19",
    "lodash": "^3.10.0",
    "node-notifier": "^4.4.0",
    "resolve": "^1.0.0",
    "shelljs": "^0.5.3",
    "silent-error": "^1.0.0",
    "symlink-or-copy": "^1.0.1",
**    "typescript": "~1.7.3",**
    "typings": "^0.6.2"
  }

**Comment by Brocco** [comment]
TypeScript was updated prior to v0.0.24.... [reference](https://github.com/angular/angular-cli/blob/97590906bc9a927fa372ec9773024f8d656271d0/addon/ng2/blueprints/ng2/files/package.json#L36)

Can you try clearing your npm cache and recreate your project?

**Comment by jpdonaghy** [comment]
The package.json on master says 1.7.3

**Comment by jpdonaghy** [comment]
I see that the blueprint package.jsons have 1.8 but only after I update the dependency in the main package.json on my fork and then npm link does ng start using tsc 1.8.  Seems odd to me.

**Comment by zackarychapple** [comment]
I was able to replicate this as well.  I generated a new project.  Added a single string literal to the generated app ts and got compile errors. 

`Error: [DiffingTSCompiler]: Typescript found the following errors:
  app/blah.ts (22, 9): Type expected.
  app/blah.ts (22, 9): The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
  app/blah.ts (22, 18): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
  app/blah.ts (22, 27): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
  app/blah.ts (22, 40): The right-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.
  app/blah.ts (23, 1): Declaration or statement expected.
    at DiffingTSCompiler.doFullBuild (/Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:202:29)
    at DiffingTSCompiler.rebuild (/Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:101:18)
    at DiffingPluginWrapper.rebuild (/Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/lib/broccoli/diffing-broccoli-plugin.js:87:45)
    at /Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/node_modules/angular-cli/node_modules/broccoli/lib/api_compat.js:42:21
    at lib$rsvp$$internal$$tryCatch (/Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/chapplez/Desktop/temp/blah/node_modules/angular-cli/node_modules/angular-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
`

**Comment by cironunes** [comment]
This is because we didn't have a release after updating to TS 1.8, so you need to `npm link` against the current master to get the changes. This will be fixed by the next release, in the meanwhile you can use this workaround.

Feel free to reopen if you think that this is still an issue.

**Comment by cironunes** [comment]
Oh, I just realized that current master didn't update to 1.8 yet. My mistake.

**Comment by jpdonaghy** [comment]
@cironunes Thanks for the confirmation.  I'll run off my CLI fork until the main project upgrades.

**Comment by cironunes** [comment]
Would you like to create a PR updating to 1.8?

Ciro Nunes
http://cironunes.com

**Comment by jpdonaghy** [comment]
@cironunes Zack beat me to it. :) https://github.com/angular/angular-cli/pull/280
