### ISSUE TITLE
Basic ng -version slow (needs wtachma\\

### ISSUE THREAD

**Issue by megabyzus** [angular/angular-cli#2790]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

### The log given by the failure.
> Normally this include a stack trace and some more information.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JohannesRudolph** [comment]
this appears to be a incomplete duplicate of #2791 , please delete

**Comment by megabyzus** [comment]
(inadvertently repeated.  closed.)
