### ISSUE TITLE
Basic 'ng --version' slow (needs 'watchman')

### ISSUE THREAD

**Issue by momoadeli** [angular/angular-cli#2791]
> ## Please provide us with the following information:
### OS?

macOS Sierra
### Versions: (error and versions below)

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.17
node: 5.11.1
os: darwin x64
### Repro steps.

`npm install angular-cli -g` and simply type `ng --version`.
### The log given by the failure.

N/A/See above

Anything I do with ng is very slow.  Note `ng new <PROJ>` is indefinite and seems hung. Aborting and using `ng new <PROJ> --skip-npm` works but is still slow.  But let's start with a simple `ng --version` first.  Takes 'long' and the 'watchman' error shows.

Many thanks!
Mo

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by tucq88** [comment]
Please install watchman 
`brew install --HEAD watchman`
The key is `HEAD` option, I cant' get it work without that one.

**Comment by megabyzus** [comment]
@tucq88, although the error indicates that, watchman is not listed in the pre-requisites.  I suppose it isn't installed by the angular-cli installer...?

**Comment by hassanasad** [comment]
@megabyzus Perhaps because the npm package for watchman is different. 

Ref: https://ember-cli.com/user-guide/#watchman
```
For complete installation instructions, refer to the docs on the Watchman website. Note, there exists a similarly named npm package (watchman) which is not the intended installation.
```

**Comment by megabyzus** [comment]
@hassanasad, thanks for response.  However, although angular-cli is rooted on ember-cli, the instructions do not presume that.  Again, the only installation instructions are `npm install -g angular-cli`.  I'd really like to focus on that and not presume anything. If there are pre-requisites, then it should be mentioned in the README.  I presume, as of now, there aren't.

Given this, what are the formal instructions from the angular-cli team?

Thanks,
Mo

**Comment by tucq88** [comment]
I think they was under development and BETA so they may not keep it in mind. But actually I still able to work with ng-cli without watchman, e.g serving and watching. ng-cli used a fallback for watchman already so it's not "actual" pre-requisite. Only got into this trouble when I have to change styleExt (but it could be done manually without using cli command) 
Btw, we could make a PR to them about this thing. It's up to their decision anyway.

**Comment by megabyzus** [comment]
(still issue).  UPDATE:

Here is the timing of the ng -v command execution: 

> (time ng -v)

results:

> angular-cli: 1.0.0-beta.18
> node: 6.8.1
> os: darwin x64

(BTW, I've updated to latest node and cli beta.18.)

**Comment by filipesilva** [comment]
The watchman thing has to do with the ember-cli addon system. I don't think we use watchman anywhere really.

There might be a way to completely bypass this check, but probably it'll be a hack.

**Comment by megabyzus** [comment]
@filipesilva , Thanks.  I understood early on watchman was ancillary to this lagging issue. Note, it's taking approx 17 seconds to execute 

> ng -v

with or without watchman.

Thanks for looking into this.
