### ISSUE TITLE
environment variables no longer added to main.js with application build

### ISSUE THREAD

**Issue by graphicsxp** [angular/angular-cli#27927]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

After upgrading to angular 18 and the new build system, the output main.js file no longer contains environment variables. 

My environment.prod.ts file looks like this:

export const environment = {
  production: true,
  aadClientId: '{#Config:Op.Front.MyApp:AzureAd:ClientId#}',
  // more variables here
  }

and the deployment pipeline in azure would search in main.xxx.js to replace placeholders with appropriate values based on environment (dev, staging, prod)

however with the new angular build system, the generated main file ( for example browser/main-Y276RYOS.js')  no longer contains the placeholder. 

Why is that ? Is there a way to keep the old behavior ? Otherwise my deployment pipeline in azure just doesn't work anymore and I'm not sure how to refactor this ..

### Minimal Reproduction

steps are described above in description

### Your Environment

```text
Angular CLI: 18.0.4
Node: 20.11.1
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 18.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.4
@angular-devkit/build-angular   18.0.4
@angular-devkit/core            18.0.4
@angular-devkit/schematics      18.0.4
@angular/cli                    18.0.4
@schematics/angular             18.0.4
ng-packagr                      18.0.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.2
```

**Comment by graphicsxp** [comment]
> Hi @graphicsxp, file replacements still work the same way. Could you please share your `angular.json` file?

Hello.  Sure, here it is
[angular.json](https://github.com/user-attachments/files/15985970/angular.json)

I have not changed anything about fileReplacements. As you can see only parts related to new builder were changed automatically during upgrade.

**Comment by alan-agius4** [comment]
This should work. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by graphicsxp** [comment]
I can try but that's not easy. Did you see my angular.json ?  It's an angular workspace made of several app/libraries.....

Before that, could you at least tell me where the content of environment.prod.ts is going after build run ?  Used to be in main.xxx.js but what about now with the new build ?

**Comment by alan-agius4** [comment]
> Before that, could you at least tell me where the content of environment.prod.ts is going after build run ? Used to be in main.xxx.js but what about now with the new build ?

It depends on the usage, if it is used in multiple chunks, it can be located in a shared bundle (chunk-xxxx.js)

**Comment by graphicsxp** [comment]
> It depends on the usage, if it is used in multiple chunks, it can be located in a shared bundle (chunk-xxxx.js)
right. with webpack the content of the environment file was always in main.xxx.js.  So I'll have to find out in which file it is and adapt my azure pipeline to replace tokens in that file instead. I had a quick look last night but I didn't see it in other files, I will loook again.

**Comment by graphicsxp** [comment]
@alan-agius4 , you were right !  I found my environment placeholders in one of the chunk file. I'll update my pipeline accordingly. 
Thanks a lot !
