### ISSUE TITLE
dev-server does not run dependencies

### ISSUE THREAD

**Issue by fhaag** [angular/angular-cli#27937]
### Command

run

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

In my `project.json` file, I have a `build` target using the `@angular-devkit/build-angular:browser` executor. I can add another target `testoutput` to its `dependsOn` array.

If I invoke `build` directly (`nx run build`) or indirectly (`nx run testcaller`, where `testcaller` is a target that depends on `build`), `testoutput` is run before `build`.

If `build` is run as the build target of `@angular-devkit/build-angular:dev-server`, on the other hand, `testoutput` is _not_ run before each build.

This renders it difficult to enrich the build process with pre-processing/code generation steps.

### Minimal Reproduction

Just start with the default sample and init NX.

In the `project.json` file, add the following two targets:
```json
"testoutput": {
	"command": "echo 'TEST'"
},
"testcaller": {
	"dependsOn": ["build"],
	"command": "echo 'CALLER'"
}
```

Then modify the `build` target to depend on `testoutput`:
```json
"build": {
	"executor": "@angular-devkit/build-angular:browser",
		"dependsOn": ["testoutput"],
		"options": {
```

Now, run:

- `nx run build` - will display `TEST` and then execute the build process, as expected
- `nx run testcaller` - will display `TEST`, then execute the build process, and then execute `CALLER`, as expected
- `nx run serve` - will just execute the build process; **unexpectedly, the `TEST` output is nowhere to be seen**

---

The minimal sample with the above modifications is available for testing here: https://github.com/fhaag/angular-cli-bug-repro/tree/dev-server-build-dependency-issue

### Your Environment

```text
Angular CLI: 15.2.11
Node: 18.17.0
Package Manager: npm 8.9.0
OS: win32 x64

Angular: 15.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.11
@angular-devkit/build-angular   15.2.11
@angular-devkit/core            15.2.11
@angular-devkit/schematics      15.2.11
@angular/cli                    15.2.11
@schematics/angular             15.2.11
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular CLI. Please contact the author(s) of the NX project or file an issue on their issue tracker.

**Comment by fhaag** [comment]
@alan-agius4 I'll happily file this as a bug in the NX project, but as far as I've observed, the issue occurs specifically with the `@angular-devkit/build-angular:dev-server` executor, which is - as far as I understand - a part of this project here, Angular CLI. The issue does not occur when using other executors.

Or do you mean it's likely the issue is caused by some built-in part of NX that is called upstream by `@angular-devkit/build-angular:dev-server`?
