### ISSUE TITLE
Dynamic template compilation breaks with aot and webpack builder

### ISSUE THREAD

**Issue by aueelis** [angular/angular-cli#27955]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm building an application that can load component templates from anywhere and use them as dynamic components in my application. With a fresh Angular 18 setup, this works perfectly fine, even with AOT, but when switching to the webpack builder (which we unfortunately need for unrelated reasons), I'm getting trouble with not being able to use any imported modules (including, e.g., CommonModule).

Without AOT, everything works perfectly fine.

### Minimal Reproduction

Repo: https://github.com/aueelis/dynamic-template-issue

In `main.ts`, I fetch the `dynamic-template.html`, which is then used to create a simple `DynamicComponent`. This is then declared in a `DynamicModule`, which is also importing the `CommonModule` to support `*ngIf`.

```ts
@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <ng-template #dynamicContainer></ng-template>
  `,
})
export class App implements AfterViewInit {
  name = 'Angular';

  @ViewChild('dynamicContainer', { read: ViewContainerRef, static: true })
  dynamicContainer: ViewContainerRef = {} as ViewContainerRef;

  constructor(private httpClient: HttpClient) {}

  ngAfterViewInit(): void {
    this.httpClient
      .get('dynamic-template.html', { responseType: 'text' })
      .subscribe((template) => this.useTemplate(template));
  }

  private useTemplate(template: string): void {
    const { component, moduleRef } = this.createDynamic(template);
    this.dynamicContainer.clear();
    this.dynamicContainer.createComponent(component, {
      environmentInjector: moduleRef.injector,
    });
  }

  private createDynamic(template: string): {
    component: any;
    moduleRef: NgModuleRef<any>;
  } {
    const component = this.createComponent(template);
    const module = this.createModule(component);
    const moduleRef = createNgModule(module, this.dynamicContainer.injector);

    return { component, moduleRef };
  }

  private createComponent(template: string) {
    return Component({
      template,
    })(class DynamicComponent {});
  }

  private createModule(component: any) {
    return NgModule({
      imports: [CommonModule],
      declarations: [component],
    })(class DynamicModule {});
  }
}

bootstrapApplication(App, { providers: [provideHttpClient()] });
```

When switching from `@angular-devkit/build-angular:application` to `@angular-devkit/build-angular:browser` (and renaming the option `browser` to `main` in `angular.json`, the application still compiles, but breaks during runtime.

The dynamic template for testing could be `<div *ngIf="true">If you see this, it's working</div>`

### Exception or Error

```text
NG0303: Can't bind to 'ngIf' since it isn't a known property of 'div' (used in the 'DynamicComponent' component template).
If the 'ngIf' is an Angular control flow directive, please make sure that either the 'NgIf' directive or the 'CommonModule' is a part of an @NgModule where this component is declared.
```

### Your Environment

```text
Angular CLI: 18.0.6
Node: 18.20.3
Package Manager: npm 10.2.3
OS: linux x64

Angular: 18.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1800.6
@angular-devkit/build-angular   18.0.6
@angular-devkit/core            18.0.6
@angular-devkit/schematics      18.0.6
@angular/cli                    18.0.6
@schematics/angular             18.0.6
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by alan-agius4** [comment]
This issue is very similar to the one described in https://github.com/angular/angular-cli/issues/22570. In summary, the interoperation between JIT which in this case is being used to compile the template during runtime and AOT compilation is not a supported use case in Angular CLI. 

Moreover, it's important to note that JIT compilation is intended for development environments only, not for production. Consequently, when performing a production build with the application builder, this approach will not work as expected.
