### ISSUE TITLE
Angular CLI Cache with Serve ignores custom builder

### ISSUE THREAD

**Issue by kukjevov** [angular/angular-cli#27956]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

When using @angular-builders/custom-esbuild:application together with plugin https://github.com/fal-works/esbuild-plugin-global-externals it is working when you use build and run http server to serve files, but when you run ng serve with @angular-builders/custom-esbuild:dev-server and your angular.json cli.cache.enabled is set to true that plugin is ignored and application is not working.

I have also reported this to *angular-builders* and they say its problem withing CLI.

### Minimal Reproduction

`git checkout https://github.com/kukjevov/ng-universal-demo`
`cd ng-universal-demo`
`git checkout cache/2.0`
`npm install`
`npm start`
`open http://localhost:8888`
`log in as admin admin`

### Your Environment

```text
Libs
- @angular/core version: 17.3.6
- @angular-devkit/build-angular version: 17.3.6
- @angular-builders/custom-esbuild version: 17.1.2

For Tooling issues:
- Node version: 20.13.0
- Platform:   Windows
```

**Comment by alan-agius4** [comment]
When running `ng serve` with cache enabled, `node_modules` are not processed by esbuild. Instead, they are handled by Vite, which means esbuild plugins are not applied.

If you need plugins to run on code within `node_modules`, you must disable caching. Alternatively, you can exclude the specific node packages you need to transform from being prebundled by using the dev-server's `prebundle` option.

Example:
```json
"serve": {
    "builder": "@angular-devkit/build-angular:dev-server",
    "options": {
        "prebundle": {
            "exclude": ["lib"]
        }
    }
}
```
