### ISSUE TITLE
Package subpath error with plugin for Custom esbuild builder

### ISSUE THREAD

**Issue by jonmarozick** [angular/angular-cli#27963]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I'm trying to use the [anolilab unplugin-favicons](https://github.com/anolilab/unplugin-favicons) package to generate favicons in an Angular 18 application. I'm using the [@angular-builders/custom-esbuild:application](https://www.npmjs.com/package/@angular-builders/custom-esbuild?activeTab=readme) builder so I can add plugins into the esbuild system. I've looked at their [examples ](https://github.com/just-jeb/angular-builders/tree/master/examples/custom-esbuild)but have had no luck.

### Minimal Reproduction

[Here is a Stackblitz](https://stackblitz.com/edit/stackblitz-starters-lc9upn?file=angular.json) that shows the issue.

### Exception or Error

```text
The message I get is: An unhandled exception occurred: Package subpath './esbuild' is not defined by "exports" in C:\Projects\a18\esbuildtest\node_modules@anolilab\unplugin-favicons\package.json
```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.7
Node: 20.12.1
Package Manager: npm 10.5.2
OS: win32 x64

Angular: 17.3.9
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.7
@angular-devkit/build-angular   17.3.7
@angular-devkit/core            17.3.7
@angular-devkit/schematics      17.3.7
@angular/cli                    17.3.7
@schematics/angular             17.3.7
ng-packagr                      17.3.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.6
```

**Comment by alan-agius4** [comment]
`@angular-builders/custom-esbuild:application` is not supported by the Angular team.
