### ISSUE TITLE
Is there a way to load different javascript for different component?

### ISSUE THREAD

**Issue by basherr** [angular/angular-cli#2797]
Can we get a way to also load Javascript files such like css file in the component section though I am oon Typescript Angular.

`@Component({
  selector: 'app-company',
  templateUrl: './company.component.html',
  jsUrl: ['somejs.js']
})`

**Comment by grizzm0** [comment]
This has nothing to do with angular-cli.

See angular/angular#4903

**Comment by filipesilva** [comment]
@grizzm0 is correct, this is not an issue to be opened on the CLI repo, but rather on https://github.com/angular/angular.

**Comment by thandonguocmo2020** [comment]
ngAfterViewInit(){
        var  str_Elemenr = `
        <script type="text/javascript" src="http://localhost:9045/js/script_1.js"></script>
        <script type="text/javascript" src="http://localhost:9045/js/script_2.js"></script>
        <script type="text/javascript" src="http://localhost:9045/js/script_3.js"></script>
        <script type="text/javascript" src="http://localhost:9045/js/script_4.js"></script>
        <script type="text/javascript" src="http://localhost:9045/js/script_5.js"></script>
        `;
        var nodeElement =   this.createDiv("div",str_Elemenr);
        document.body.appendChild(nodeElement);
    }


    createDiv(node_name,textElement) {
              var _nodeElement = document.createElement(node_name);
              _nodeElement.innerHTML = textElement;
              return _nodeElement;
    }
