### ISSUE TITLE
Reduce angular uses of file watcher by leveraging folder watcher (ex: ng serve)

### ISSUE THREAD

**Issue by MathieuGirard** [angular/angular-cli#27982]
### Command

serve

### Description

I keep reaching the ENOSPC watcher errors with angular.

It would be nice for angular `ng serve` to be less ressource hungry by reusing folder watchers instead of file watchers. This would also reduce the need for "file watch filtering".

### Describe the solution you'd like

According to inotify man page angular watcher could use folder watches instead of watching file reducing the amount of watcher greatly (reusing a single inotify watcher per watched folder instead of one watcher file actual file).

The code would have to do the actual filtering on event reception to known if the item was watched (the event includes a file `name` attribute for folder watch allowing to known which file changed).

```
NAME         [top](https://www.man7.org/linux/man-pages/man7/inotify.7.html#top_of_page)
       inotify - monitoring filesystem events
DESCRIPTION         [top](https://www.man7.org/linux/man-pages/man7/inotify.7.html#top_of_page)
       The inotify API provides a mechanism for monitoring filesystem
       events.  Inotify can be used to monitor individual files, or to
       monitor directories.  When a directory is monitored, inotify will
       return events for the directory itself, and for files inside the
       directory.

[...]

The name field is present only when an event is returned for a
       file inside a watched directory; it identifies the filename
       within the watched directory.  This filename is null-terminated,
       and may include further null bytes ('\0') to align subsequent
       reads to a suitable address boundary.
```

### Describe alternatives you've considered

The suggested alternative on the internet is to increase the sysctl limit for watchers at the cost of a kernel memory usage increase.

**Comment by alan-agius4** [comment]
The Angular CLI uses [watchpack](https://github.com/webpack/watchpack) under the hood as a file watcher. As mentioned in their readme, watchpack already uses directory watchers to minimize the number of individual file watchers.
