### ISSUE TITLE
Add support for esbuild chunkNames option

### ISSUE THREAD

**Issue by Fluccioni** [angular/angular-cli#27984]
### Command

build

### Description

The application builder does not provide all the options esbuild does ; I think the possibility to customize further the output location is interesting though.

As esbuild propose options to control the file names of automatically generated chunks (https://esbuild.github.io/api/#chunk-names), it could be a nice addition of options available through the application builder schema.

The same strategy could maybe be applied with similar `assetNames` option.

### Describe the solution you'd like

To be able to control it for all chunks, I guess a good location for this templating string would be in the `outputPath` object like

```json
{
  "build": {
    "executor": "",            
    "options": {
      "outputPath": {
        "base": "dist",
        "browser": "prod",
        "server": "server",
        "media": "media",
        "browserChunkNames": "front-[ext]/[name]_[hash]",
        "serverChunkNames": "example--[hash]"
      },
  ...
  }
}
```

### Describe alternatives you've considered

I'm currently using the application builder via the @nx/angular:application that, in addition of the cli builder features, add the suport of providing esbuild plugins.

Unfortunately I didn't manage to find or write a plugin that can infer on the generated files, issues are open on this subject on esbuild to have callbacks such as "onEmit" for instance but as there is an existing option for the scenario, better use it.

Thanks for reading.

**Comment by Fluccioni** [comment]
not saying it is necessary but could offer more flexibility, as to simply keep generated css & js files in different folders inside the dist directory for instance ; to help people used to configure this kinkd of stuff via webpack output config migrate to the new preferred builder without impacting too much the file structure at the end

**Comment by alan-agius4** [comment]
Thank you for your request.

While this feature was possible using a custom Webpack configuration and third-party custom builder, it was never supported by the Angular CLI. Developers who used custom Webpack configurations opted to go on an unsupported path. Therefore, unless there is a compelling use-case that necessitates this option, we should not expand the API to include it.
