### ISSUE TITLE
Allow creating git local user with new project before making first commit

### ISSUE THREAD

**Issue by moniuch** [angular/angular-cli#27999]
### Command

new

### Description

I need to keep multiple git identities on my computer. When creating `ng new` I need to have control over which identity is used to create the project, as I don't always want to use the `--global` git user. I often forget run into situations where I create a new project with wrong identity.

### Describe the solution you'd like

The solution I'd prefer would be some sort of micro-routine that would allow creating local project `user.*` config and then make the initial commit utilizing it, without the need of using the commit skipping flag.

Imagine this syntax (just an example):

  `ng new --git-local-user` or `ng new -G`

The script creates a new project, but before it gets to making git commit, it shows a radio-button menu:
```
(*) create local git user
( ) use global git user (abcxyz)
```

Selecting create would prompt for user name and then user email and once done, make the first commit as it would normally do.

### Describe alternatives you've considered

You can either:

1. `--commit false` and then manually: create local user, `git add .`, `git commit` 
2. Erase `git config --global user.*` entries to deliberately make the git fail, but this is kind of harsh

None of those offers nice Dx.

With just one new flag you'd get a nice and consistent cli behavior and would get the entire flow with some extra git helper routine.

**Comment by alan-agius4** [comment]
Hi @moniuch, thanks for your request. This seems to be a quite specific use case, and since there is already a pretty easy workaround, we prefer not to provide additional prompts and options.
