### ISSUE TITLE
Migrate cli builder based on Webpack to Esbuild

### ISSUE THREAD

**Issue by AnnaKozlova** [angular/angular-cli#28001]
### Command

build, serve

### Description

Hello! 
After Angular introduced support for esbuild and vite, my team and I were excited to try them out with our application.

Our project currently uses custom builders and Angular 17.3.10. Specifically, our builder adds plugins to webpack for handling fonts and SVGs from assets, which are subsequently included in indexHtml, along with additional scripts.

I attempted to use a `buildApplicationInternal` equivalent for esbuild, but I encountered difficulties retrieving fonts and SVG information in the `onEnd` callbacks to use later in `indexHtmlTransformer` - not all information about media files is returned in metafile.

I would like to ask for guidance on the best approach to take when working with esbuild, considering the need to maintain our existing logic.
Is it save to use `buildApplicationInternal` in the future?

Additionally, I tried to run the project with ng serve. However, instead of launching Vite, webpack is initiated.

This might be because `ng serve `uses the `isEsbuildBased` function for verification, which only checks:
```
function isEsbuildBased(builderName) {
    if (builderName === '@angular-devkit/build-angular:application' ||
        builderName === '@angular-devkit/build-angular:browser-esbuild') {
        return true;
    }
    return false;
}
```

i have my custom builder name there.

I might be missing something here, but there is no documentation for these cases. As I am not an expert, it has been quite challenging to understand how this should work. I would greatly appreciate any help you can provide!

Thank you in advance for your assistance.

### Describe the solution you'd like

I would like to have the ability to obtain information about the processed media files and run ng serve with vite.

### Describe alternatives you've considered

Tried to access the media folder in `onEnd`, but the files were not yet written.

**Comment by alan-agius4** [comment]
As the name suggests, `buildApplicationInternal` is an internal function. If you want to create a custom esbuild builder, `buildApplication` is the public API to use.

Although the Angular CLI does allow additional plugins through its API, these plugins are not officially supported. By using these APIs, you choose to follow the unsupported path.

With the application builder, files are written to disk at a later stage, not during the `onEnd` callback. Additionally, it is worth mentioning that an application is compiled using multiple instances of esbuild, unlike with Webpack.

This issue tracker is not suitable for support requests. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using the `angular-cli` tag.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
