### ISSUE TITLE
ng build fails on different OS's because of missing 'imports'.

### ISSUE THREAD

**Issue by MrHus** [angular/angular-cli#2800]
### OS

Linux

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:   trusty
### Versions.

angular-cli: 1.0.0-beta.17
node: 6.5.0
os: linux x64
### Repro steps.

Somewhere in a service I need the 'ConnectableObservable' which I import from the following
location: `import { ConnectableObservable } from 'rxjs/Observable/ConnectableObservable';`

When I build using `./node_modules/.bin/ng build` it fails with the following errors:

```
 94% asset optimizationError in bail mode: [default] /var/lib/jenkins/workspace/MoreStorage/morestorage-ui/snapshotter/src/app/utils/crud.service.ts:9:38 
Cannot find module 'rxjs/Observable/ConnectableObservable'.
```

The reason I build without using a globally installed 'ng' is because this error
is produced by a 'Jenkins' server on which we do not want to install angular-cli
globally so multiple projects can use a different version of 'ng'. 

On the server the following global packages are installed:

```
npm list -g --depth=0

/var/lib/jenkins/.nvm/versions/node/v6.5.0/lib
└── npm@3.10.3
```

The interesting part is that this compiler error does not occur on my desktop
machine. Which is a Mac which runs with the following version:

angular-cli: 1.0.0-beta.17
node: 6.5.0
os: darwin x64

Anyone have any clues?

**Comment by filipesilva** [comment]
I tried a local reproduction and couldn't get this error. I opened `src/app/app.component.ts` and added this:

```
import { ConnectableObservable } from 'rxjs/Observable/ConnectableObservable'

console.log(ConnectableObservable)
```

Both `ng build` and `./node_modules/.bin/ng build` completted successfully. 

I understand that you currently have this problem on your CI server, and a problem exists, but without a way to reproduce it I cannot debug and try to fix. If it's not a build problem per se, it can be a dependency problem where that `rxjs/Observable/ConnectableObservable` does not actually exist.

**Comment by MrHus** [comment]
Thanks @filipesilva for your response, I'm looking into finding a way to reproduce this.

On you suggestion that the 'file' might not exists on the build-server I went digging for:
'rxjs/Observable/ConnectableObservable' does exist in the following file:

`node_modules/rxjs /observable/ConnectableObservable.js`

**Comment by filipesilva** [comment]
Hm... maybe it's a case thing? you say `observable` exists, but you're importing `rxjs/**Observable**/ConnectableObservable` instead.

**Comment by MrHus** [comment]
Case sensitivity does not matter, locally it works regardless of case.

For example these all work:

1. - RXJS/Observable/ConnectableObservable
2. - rxjs/observable/connectableobservable
3. - RXJS/Observable/CONNECTABLEObservable

**Comment by filipesilva** [comment]
Actually, yesterday I spent some 3 hours working on a similar issue where our CI on a file check and it was due to case sensitivity. Our team mostly works on either Windows and Mac, where case sensitivity doesn't matter. But on Linux it does matter.

Windows:
```
$ mkdir folder-one
-> ok
$ mkdir Folder-one
-> mkdir: cannot create directory ‘Folder-one’: File exists
$ touch Folder-One/file.txt
-> ok
```
OSX (same as Windows):
```
$ mkdir folder-one
-> ok
$ mkdir Folder-one
-> mkdir: Folder-one: File exists
$ touch Folder-One/file.txt
-> ok
```
Linux (different from windows/OSX):
```
$ mkdir folder-one
-> ok
$ mkdir Folder-one
-> ok
$ touch Folder-One/file.txt
-> touch: cannot touch 'Folder-One/file.txt': No such file or directory
```

Now it's true that you're trying to do an import and that mostly depends on however webpack+typescript do things, but I wanted to point out that it might be related.

**Comment by MrHus** [comment]
Ok we fixed this issue ... by working around it.

We changed the way we import ConnectableObservable, it now looks like this:

```
import { Observable, ConnectableObservable } from 'rxjs';
```

This works locally and on the Jenkins server. 

The reason why the old variant did not work is still unclear to me. Changing the import to match the file capitalisation, as @filipesilva suggested, on the Jenkins server dit not solve the problem.

I'm happy that the issue is resolved, but not satisfied with its conclusion. Hopefully one day we will discover the reason for this.

I consider this issue resolved.

**Comment by intellix** [comment]
This worked locally on OSX but failed on Heroku after pushing:
```ts
import { ConnectableObservable } from 'rxjs/Observable/ConnectableObservable';
```

This worked locally AND on Heroku. It makes sense because the folder is a lowercase `o`.
```ts
import { ConnectableObservable } from 'rxjs/Observable/ConnectableObservable';
```
