### ISSUE TITLE
Enhance the `--output-path` command to accept configurations for different output directories

### ISSUE THREAD

**Issue by framasev** [angular/angular-cli#28015]
### Command

build

### Description

Application builder outputs publicly accessible files in the `browser` directory and SSR files in the `server` directory (see [issue](https://github.com/angular/angular-cli/issues/26304) and [comment](https://github.com/angular/angular-cli/issues/26304#issuecomment-1804389033)). This was addressed by configuring `outputPath` in `angular.json`:

```json
"outputPath": {
  "base": "dist/project-name",
  "browser": "dist/browser",
  "server": "dist/server"
}
```

The current `--output-path` command does not support configuring separate directories for `browser`, `server`, and other outputs. This limitation creates challenges in managing and organizing build outputs, especially in multi-target applications.

### Describe the solution you'd like

Enhance the `--output-path` command to accept configurations for different output directories, such as:

```
--output-path.browser=dist/browser
--output-path.server=dist/ssr
```

**Comment by alan-agius4** [comment]
Could you please elaborate on the challenges this creates? It's a bit puzzling that the `outputPath` sub-paths need to be so frequently based on the build.

**Comment by alan-agius4** [comment]
Closing due to insufficient information.
