### ISSUE TITLE
ViewChild not find and bundle same size when compile using AoT

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#2801]
please apologize after  tried gitter, then stackoverflow, I need to open issue here, to check question follow: http://stackoverflow.com/questions/40154485/viewchild-not-find-and-bundle-same-size-when-compile-using-aot

**Comment by filipesilva** [comment]
I read your issue but I don't see anything in it that indicates there is a problem with the CLI. If you can get me a reproduction that doesn't depend on third-party libs, I can investigate.

**Comment by istiti** [comment]
@filipesilva  To inform you ([check my second question on stack](http://stackoverflow.com/questions/40172545/referenceerror-x-viewchild-is-not-defined-when-compile-with-aot?noredirect=1#comment67613951_40172545))
I never write semis, so when I do not use --aot flag all compile but with --aot flag we can't write our ViewChild without semis. 

I wonder why with AoT the parsing process isn't same, I expect from ngc  to add semis automatically as when I build --prod only ! 

Any idea ? Is this bug ?

**Comment by filipesilva** [comment]
@istiti I can't do any debugging or anything without a repro.
