### ISSUE TITLE
The installation doesn't work

### ISSUE THREAD

**Issue by EliorSastiel123** [angular/angular-cli#2802]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS?
> Windows 10

### Versions.
> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
node --version
v6.8.0

I have seen some open and closed isuues about that but I don't see any active conversation and I'm facing that error for a week+-.

What are your recommendations?

```
npm ERR! git clone --template=C:\Users\eliorsastiel\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\eliorsastiel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undefined
npm ERR! git clone --template=C:\Users\eliorsastiel\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:webpack/compression-webpack-plugin.git C:\Users\eliorsastiel\AppData\Roaming\npm-cache\_git-remotes\git-github-com-webpack-compression-webpack-plugin-git-7e55907cd54a2e91b96d25a660acc6a2a6453f54-e286d0b5: undefined
```

**Comment by mahyari** [comment]
I have same problem with the following information:
`
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\XXX\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "angular-cli"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code 128
`

**Comment by d-fournier** [comment]
I have the same issue in the node docker image (node:latest)

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/2709, out in beta.18.

**Comment by d-fournier** [comment]
After my test, I confirm
