### ISSUE TITLE
Angular devkit 18.0.7 not compatible with Bootstrap 5.3.3

### ISSUE THREAD

**Issue by watchity** [angular/angular-cli#28035]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

13.0

### Description

I updated from Angular 13 to latest 18.0.0 and this bug has arisen.

```
./libs/shared/styles/src/index.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
From line 30, column 13 of node_modules/bootstrap/scss/_grid.scss: 
   ╷
30 │             @extend %responsive-container-#{$breakpoint};
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
You may not @extend selectors across media queries.
   ╷
30 │             @extend %responsive-container-#{$breakpoint};
   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/bootstrap/scss/_grid.scss 30:13               @content
  node_modules/bootstrap/scss/mixins/_breakpoints.scss 62:7  media-breakpoint-up()
  node_modules/bootstrap/scss/_grid.scss 19:5                @import
  node_modules/bootstrap/scss/bootstrap.scss 16:9            @import
```

### Minimal Reproduction

1. Install Angular 18.0
2. Install Bootstrap 5.3.3
3. Run ng serve --ssl

### Your Environment

```text
ng version                                                                       1 ✘  wct_socketmix_38 3.8.18   20.11.1  

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.0.7
Node: 20.11.1
Package Manager: yarn 1.22.22
OS: linux x64

Angular: 18.0.6
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.0
@angular-devkit/build-angular   18.1.0
@angular-devkit/core            18.0.7
@angular-devkit/schematics      18.0.7
@angular/material               18.1.0
@schematics/angular             18.0.7
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.7
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by watchity** [comment]
I can't reproduce it either in a fresh repo, please don't close the issue as I've been trying to have the problematic repo for this week. @angular-devkit/architect is really unstable and has a lot of problems in all versions, but it seems to work well enough in small simple apps. That's why I keep developing the repo to have a more complex app.
