### ISSUE TITLE
New Builder Polyfills Attempt to Call `Symbol.asyncIterator` on Synchronous Iterator

### ISSUE THREAD

**Issue by johnameyer** [angular/angular-cli#28048]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

The new builders `@angular-devkit/build-angular:browser-esbuild` / `@angular-devkit/build-angular:application` seem to have subtle differences in their treatment of `yield *` and generators which is a breaking change from the old browser builder. Namely, there seems to be a [pollyfill](https://github.com/evanw/esbuild/blob/a7fcc43fdb6b6edc58f781fe96328f4867f4b33e/internal/runtime/runtime.go#L392-L393) for `yield *` that attempts to access `Symbol.asyncIterator` which is not technically correct when the generator or iterable is fully synchronous / only exposes `Symbol.iterator`. This causes code that functions fine using the old builder to fail to run using the new builder.

### Please provide a link to a minimal reproduction of the bug

https://github.com/johnameyer/async-iterator-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.1.0
Node: 20.5.0
Package Manager: pnpm 9.0.1
OS: darwin x64

Angular: 18.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.0
@angular-devkit/build-angular   18.1.0
@angular-devkit/core            18.1.0
@angular-devkit/schematics      18.1.0
@schematics/angular             18.1.0
rxjs                            7.8.1
typescript                      5.5.3
zone.js                         0.14.7
```

### Anything else?

Likely this may be an issue with esbuild itself but I am unaware of what in the Angular wrapping would convince esbuild this would be async.

**Comment by JoostK** [comment]
This does appear a bug with esbuild's polyfill, as [the ECMAScript standard](https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-generator-function-definitions-runtime-semantics-evaluation) specifies that the `GetIterator` procedure is dependent on the generator's kind.

**Comment by clydin** [comment]
We can report this upstream to the esbuild project. But from the reproduction this appears to be a fairly uncommon usage scenario and it may take some time for a change to become available. It appears that the upstream behavior in this case could be made to match more strictly in regards to the specification.  However, the reproduction code itself has several errors which, if corrected, would also rectify the issue as well. Currently the proxy handler is ignoring (via `@ts-expect-error`) several TypeScript errors regarding the property key value. This leads to incorrect execution behavior if a non-present symbol key is used with the object. For example, `makeLazyMultiIterable(generator())[Symbol.toStringTag]` will cause the same error without any yield star usage.
While an upstream change to the yield start behavior would fix the issue in the reproduction, it would not fix any other usage such as the aforementioned.

Also of interest is that moving the reproduction to zoneless also bypasses the reproduction's yield start problem as the helper is no longer present in that case.  However, that is a larger application-wide change which may not be acceptable and is also considered experimental as of v18.

Based on this, there are mainly three possible options to rectify the issue:
* Wait for an upstream change to the yield star behavior
* Add property key logic to handle non-number values
* Move the application to zoneless (https://angular.dev/guide/experimental/zoneless)

**Comment by alan-agius4** [comment]
Closing as per above.
