### ISSUE TITLE
Favicon not copied to dist folder

### ISSUE THREAD

**Issue by meeroslav** [angular/angular-cli#2804]
Favicon doesn't get copied to dist folder on production build.
Moving `favicon.ico` to `assets` folder solves the issue of course.
Potential solutions are to change blueprint and move file to assets by default or check why copying fails on `--prod`.

### OS?
Windows 7 (others as well, but not tested)

### Versions.
angular-cli: 1.0.0-beta.16
node: 5.10.1
os: win32 x64

### Repro steps.
Run `ng build --prod`. Start the app from `dist` folder

### The log given by the failure.
404 in browser for `favicon.ico`

**Comment by grizzm0** [comment]
This has been fixed in #2570 and will be released with beta 18. This issue can be closed.

**Comment by Splaktar** [comment]
beta.18 is out today and includes this fix! Just verified in my project.

**Comment by filipesilva** [comment]
^ what @grizzm0 and @Splaktar just said 💃 

It's worth mentioning that it works *because* `assets` now accepts an array, meaning if you have an existing projects and want favicon to be copied, you should add it to the array as shows in #2570.
