### ISSUE TITLE
.js files no longer packaged with @angular-cli packages

### ISSUE THREAD

**Issue by garkbit** [angular/angular-cli#2805]
### OS?
OSX 10.10.5

### Versions.
@angular-cli/ast-tools v1.0.4
@angular-cli/base-href-webpack v1.0.3

### Repro steps.
Install latest beta, try to do something. Cannot find @angular-cli packages

### The log given by the failure.
```
Error: Cannot find module '@angular-cli/ast-tools'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<path>/node_modules/angular-cli/utilities/ast-utils.js:4:19)
```

### Mention any other details that might be useful.
Can be worked around by explicitly installing previous versions:
```
"devDependencies": {
  "angular-cli": "1.0.0-beta.18",
  "@angular-cli/ast-tools": "<1.0.4",
  "@angular-cli/base-href-webpack": "<1.0.3"
}
```

**Comment by filipesilva** [comment]
Can verify and confirm. We haven't yet pushed this versions to `latest` on npm, so existing users should not have any problems. We are working on fixing this.

**Comment by filipesilva** [comment]
Should be fixed now, we published new versions of the packages tagged as latest.

**Comment by alxhub** [comment]
Fixed in the latest patch versions.
