### ISSUE TITLE
Background image introduction error

### ISSUE THREAD

**Issue by HCenggel** [angular/angular-cli#28050]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.1.0

### Description

# scss
background: url("/images/header_bg.png") no-repeat center;

# index.html
<base href="./">

# Website Address Example（）
www.test.com/fileName

# bg url
www.test.com/images/header_bg.png (Not Found)
The correct answer should be【www.test.com/fileName/images/header_bg.png】

### Minimal Reproduction

Simply create a new project to

### Exception or Error

```text
# scss
background: url("/images/header_bg.png") no-repeat center;

# index.html
<base href="./">

# url
www.test.com/fileName

# bg url
www.test.com/images/header_bg.png (Not Found)
The correct answer should be【www.test.com/fileName/images/header_bg.png】
```

### Your Environment

```text
Angular CLI: 18.1.0
Node: 18.20.3
Package Manager: npm 10.7.0
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1801.0 (cli-only)
@angular-devkit/core         18.1.0 (cli-only)
@angular-devkit/schematics   18.1.0 (cli-only)
@schematics/angular          18.1.0 (cli-only)
```

**Comment by HCenggel** [comment]
I put the pictures in public/images

**Comment by clydin** [comment]
This is working as expected. `/images/header_bg.png` is a root-relative URL which is relative to the host not the current path.
For additional information please see:
https://developer.mozilla.org/en-US/docs/Web/API/URL_API/Resolving_relative_references#root_relative

**Comment by HCenggel** [comment]
> This is working as expected. `/images/header_bg.png` is a root-relative URL which is relative to the host not the current path. For additional information please see: https://developer.mozilla.org/en-US/docs/Web/API/URL_API/Resolving_relative_references#root_relative

But you can’t write background: url("./images/header_bg.png") no-repeat center;
Writing like this will result in an error

**Comment by HCenggel** [comment]
How should I write it? My project is not in the root directory of the website domain name, but there is an additional file name

**Comment by HCenggel** [comment]
This is also wrong to write
background: url("images/header_bg.png") no-repeat center;
But you can write
<img width="66" src="images/header_bg.png" />

**Comment by clydin** [comment]
The path should be relative to the containing file at build time (source code on disk).  This will be processed by the build system which will automatically add it to the output and and adjust the reference in the built code for the output structure of the application.
Files referenced should not also be in the public folder since that would cause two copies of the file to be present in the application output.

**Comment by HCenggel** [comment]
> The path should be relative to the containing file at build time (source code on disk). This will be processed by the build system which will automatically add it to the output and and adjust the reference in the built code for the output structure of the application. Files referenced should not also be in the public folder since that would cause two copies of the file to be present in the application output.

I know this, this way of writing is fine in v17, why is it not okay in v18?

**Comment by HCenggel** [comment]
I have reverted to v17 and gave up upgrading to 18

**Comment by HCenggel** [comment]
> This is working as expected. `/images/header_bg.png` is a root-relative URL which is relative to the host not the current path. For additional information please see: https://developer.mozilla.org/en-US/docs/Web/API/URL_API/Resolving_relative_references#root_relative
The problem is not solved yet

**Comment by clydin** [comment]
This behavior has been in place since the first versions of Angular CLI and has not changed.
Relative file references within CSS files must be build time resolvable unless explicitly marked as external via the `externalDependencies` option.
