### ISSUE TITLE
Update "Code scaffolding" section in README.md generated automatically

### ISSUE THREAD

**Issue by reuse-ay** [angular/angular-cli#28059]
### Command

new

### Description

Current "Code scaffolding" section in README.md generated automatically when executing ng new don't include all schematic. 

This is current "Code scaffolding" section.

## Code scaffolding

Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.

I'm a developer using Angular. I finished Tour of Heroes, but a year later I discovered the existence of interceptors and resolvers. By including these in the readme, I think more developers will be aware of their existence.

### Describe the solution you'd like

include all schematic like this.

## Code scaffolding

Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module|app-shell|application|config|environments|interceptor|library|resolver|service-worker|web-worker`.

**Comment by alan-agius4** [comment]
I agree that we should improve this section. Instead of adding more schematics, we should include a link instead.

**Comment by alan-agius4** [comment]
@aparzi feel free to open a PR.

**Comment by aparzi** [comment]
Thanks

**Comment by MrJithil** [comment]
Since no further movements in this ticket, I have raised a PR with the proposed changes. 

Thank you @aparzi and @alan-agius4
