### ISSUE TITLE
Create folder if not exist when generating components

### ISSUE THREAD

**Issue by warriorkitty** [angular/angular-cli#2806]
`ng generate component tasks/tasks-list`

If the `tasks` folder doesn't exist, you will get an error. Is there a way to force creating folders?

**Comment by filipesilva** [comment]
@Brocco what do you think?

**Comment by Brocco** [comment]
This previously was the behavior, but it was removed to allow for the project's structure to grow organically. This was also to prevent the issue of typos in paths... if you're generating something 5 layers deep, and type the 2nd dir name wrong. You wonder where your component is that you just generated.

My initial thought is to reject this, but am open to being convinced. I don't think the default behavior should be changed, but could be open to a flag being added.

Convince me...

**Comment by warriorkitty** [comment]
Hmm, now that you mentioned it... I was doing a small test app and this was a good idea then. Now when I think about it, if I have a 5 layered app and I put a wrong path by mistake, it would make me really mad. :)

**Comment by cnwilkin** [comment]
How difficult would it be to autocomplete the path with existing directories? On Windows when using the `cd` command you can press tab and it will autocomplete the directory based off what directories are available and match what you have already typed.

**Comment by Brocco** [comment]
@cnwilkin you can find that info [here](https://github.com/angular/angular-cli#commands-autocompletion)

**Comment by Brocco** [comment]
@warriorkitty while I agree that this could be overridden via a flag, I think leaving the functionality as is for now is for the best right now. This could/should be reconsidered in the future.
