### ISSUE TITLE
Esbuild issue with web workers?

### ISSUE THREAD

**Issue by danilobassi8** [angular/angular-cli#28078]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Hi, I don't know if this is an issue or it should be a feature request. The thing is I'm using web workers in my Angular app, and I have found some issues while deploying it.

In my service, I'm importing the web worker as the Angular doc says.

``` typescript
this.worker = new Worker(new URL('../utils/workers/myworker.worker', import.meta.url), 
   {name: 'worker', type: 'module'}
)
```

during development (`ng serve`) it works as expected. 

But when I build, I see in my dist folder a new file called `worker-<HASH>`
I'm building with @angular-devkit/build-angular:browser-esbuild using this command:
- `ng build --configuration=production --deploy-url "https://${CLOUDFRONT_URL}/${VERSION}"`

CLOUDFRONT_URL is the URL of my AWS CDN.

The main issue is, that I'm not able to locate the file. Because "import.meta.url" is not the current URL I'm using for the web page.

Example: 
- Lets say that my page is hosted at www.mypage.com
- My files are hosted on a cloudfront cdn, thus, files lives on s3, and I'm able to download it using the CLOUDFRONT_URL mentioned above. (that's why I'm using the --deploy-url param)

Another thing that I noted is that, when I do something like this:

``` typescript
// my typescript code

if(environment.name === 'development'){
    this.worker = new Worker(new URL('../utils/workers/myworker.worker', import.meta.url),
        {name: 'worker', type: 'module'}
     )
} else {
    this.worker = new Worker(new URL('../utils/workers/myworker.worker', 'https://mypage.com')
        {name: 'worker', type: 'module'}
    )
}

```

its gets transpiled to something like this:

``` typescript
if(environment.name === 'development'){
    this.worker = new Worker(new URL('worker-F4AB9Z', import.meta.url),
        {name: 'worker', type: 'module'}
     )
} else {
    this.worker = new Worker(new URL('../utils/workers/myworker.worker', 'https://mypage.com')
        {name: 'worker', type: 'module'}
    )
}
```

Note that Esbuild replaced the `../utils/workers/myworker.worker` with the compiled filename `worker-F4AB9Z`.
But it is not doing the same with any string other than "import.meta.url" for the URL of the new worker.

If I try to do something like
``` typescript
const url = new URL('../utils/workers/myworker.worker', import.meta.url)
```
I wont work. Esbuild will only replace the file path with the compiled filename if I put the `new URL( ... )` inside the Worker constructor. Is that expected?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.3.8
Node: 20.9.0
Package Manager: npm 10.7.0
OS: linux x64

Angular: 17.3.10
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cdk                    16.2.14
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            6.6.7
typescript                      5.3.3
zone.js                         0.14.6
```

### Anything else?

Another question: Is there any way that I could have the output filename ( the `worker-F4AB9Z` ) in a variable? 
Because currently I'm manually deploying the web worker to s3 and hardcoding the URL in the code.
But as you may know, the hash of the file changes on every deploy, or at least when the worker code changes. And its annoying.

**Comment by clydin** [comment]
This behavior is not specific to esbuild.  In fact, esbuild itself does not currently support automatic bundling of WebWorkers. This is a feature the Angular CLI adds to provide parity with other bundlers.  Other major bundlers such as Webpack and Vite operate in the same way. Only `new Worker(new URL('<relative_build_time_path>', import.meta.url))` is considered for processing.  Any other form is an external reference to a worker and cannot be automatically processed.

Additionally, `import.meta.url` is the absolute URL of the containing file. As long as the generated worker file is deployed and available adjacent to the JavaScript bundle that is referencing it, it will be found at run time. If the application JavaScript is hosted on a CDN, the worker file should be as well.

**Comment by danilobassi8** [comment]
@clydin That is good to know. The main issue with that implementation is that I don't know the worker hash before the build. Even if I hardcode the hash in my code, it will change on every deploy.
Is there a way to know or store the "compiled name" in a variable so I can use it on a CDN?

**Comment by clydin** [comment]
Can you expand on what you mean by "use it on a CDN"?
The build will automatically process and add the correct reference to your code.  As long as all the built browser files are deployed on the CDN correctly, no further action should be required.

**Comment by danilobassi8** [comment]
@clydin for example, let say that my page is hosted on www.mypage.com, if I do something like
 ``` typescript
    this.worker = new Worker(new URL('../utils/workers/myworker.worker', import.meta.url),
        {name: 'worker', type: 'module'}
     )
```

import.meta.url wont be pointing to the CDN url, but to www.mypage.com instead. 
And the url will be something like: `www.mypage.com/worker-<hash>.js`

in that case, I wont be able to fetch the worker code from my S3 bucket.

I'd need to be be able to produce the `worker-<hash>.js` somehow, because I already have the CLOUDFRONT_URL and VERSION variable.

**Comment by clydin** [comment]
`import.meta.url` will be the absolute URL of the JavaScript file containing the Worker constructor code.  If deploy URL is used as above then the value of `import.meta.url` will be `https://${CLOUDFRONT_URL}/${VERSION}/main-<hash>.js` (with values replaced as appropriate). Combine that with `new URL('worker-F4AB9Z.js', import.meta.url)` from the generated code and the `Worker` constructor will fetch `https://${CLOUDFRONT_URL}/${VERSION}/worker-F4AB9Z.js`.

**Comment by muhamedkarajic** [comment]
Hi I have this issue: https://github.com/nrwl/nx/issues/26861

Apperently its not Nx but Angular?

**Comment by danilobassi8** [comment]
Update: I think angular should provide a way to store the filename in a variable instead of parsing it automatically if they are in a Web Worker constructor. Because I read that web workers can not be user if they have different origins.
I could use the trick to fetch the js code and then use a Blob object like this:
``` typescript
  const workerUrl = 'MY-WEB-WORKER-URL'
  const js = await fetch(workerUrl).then((r) => r.text());
  const blob = new Blob([js], { type: 'application/javascript' });
  const  url = URL.createObjectURL(blob);
  const worker = new Worker(url, {name: 'worker', type: 'module' } )
```

But as far as I know, there's no way to get the correct file path if we do not create a new URL inside the worker constructor.
In the provided example, I am missing the `workerUrl` value.

**Comment by alan-agius4** [comment]
Supporting the use of variables to store filenames is not planned because tools like esbuild, Rollup, and Vite do not support this pattern. For example, see [how esbuild handles it](https://esbuild.github.io/try/#YgAwLjIzLjAALS1idW5kbGUAZQBlbnRyeS5qcwBjb25zdCB4ID0gJy4vYS5qcyc7CmltcG9ydCh4KQo). This approach complicates static analysis.

Unfortunately, manually setting a web worker name is also not possible at this time. In your case, you can have the workers as static JS files in the assets/public directory.

**Comment by danilobassi8** [comment]
@alan-agius4 is there any guide to do that?
I know how to add a .js script into my assets folder, but in this case the setup is very different.
I'll need to do several steps if I have a worker code written in Typescript.

1 - Compile my workers code (Angular does that, but it assign a random hash, so its impossible to know the name of the transpiled file).
2 - I'll need to move the compiled .js to the assets folder
3 - Deploy it
4 - Import it.

In this case, steps 1 and 2 are not clear for me. How do we manage to compile code that should be in the asset folder?

**Comment by muhamedkarajic** [comment]
I'm also interested in this, can't be that we just have to live with this.
