### ISSUE TITLE
onProxyReq does not work

### ISSUE THREAD

**Issue by shipengqi** [angular/angular-cli#28073]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.3.1

### Description

After upgrading to 18.1.1, the `onProxyReq` in the `proxy.config.js` file does not work, as does `on.ProxyReq`. The following is my `proxy.config.js` file:

```javascript
const PROXY_CONFIG = [
  {
    context: ["/v2.0", "/v3.0", "/api"],
    target: "http://localhost:9980/self-service",
    changeOrigin: true,
    secure: false,
    logLevel: 'debug',
    on: {
      proxyReq: (proxyReq) => {
        console.log("set headers in on.proxyReq")
      }
    },
    onProxyReq: (proxyReq) => {
      console.log("set headers in onProxyReq")
    },
  }
];

module.exports = PROXY_CONFIG;
```

### Minimal Reproduction

1. use `ng update @angular/core@18 @angular/cli@18` command to upgrade
2. start dev server `ng serve --proxy-config proxy.conf.js`

### Your Environment

```text
Angular CLI: 18.1.1
Node: 18.20.3
Package Manager: npm 8.5.1
OS: win32 x64

Angular: 18.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router, upgrade

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.1
@angular-devkit/build-angular   18.1.1
@angular-devkit/core            18.1.1
@angular-devkit/schematics      18.1.1
@schematics/angular             18.1.1
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.8
```

### Anything else relevant?

`http-proxy-middleware`:

```
$ npm list http-proxy-middleware
idm-admin-ui@1.24.0 C:\Code\work-repos\idm-admin-general\idm-admin-ui
`-- @angular-devkit/build-angular@18.1.1
  +-- http-proxy-middleware@3.0.0
  `-- webpack-dev-server@5.0.4
    `-- http-proxy-middleware@2.0.6
```

**Comment by alan-agius4** [comment]
Which build builder are you using?

**Comment by shipengqi** [comment]
> Which build builder are you using?

I only used `@angular/cli`

**Comment by alan-agius4** [comment]
You can check your builder by checking the `builder` name in the `build` section of the `angular.json`.

Example
```js
"build": {
  "builder": "@angular-devkit/build-angular:application",
```

**Comment by shipengqi** [comment]
> You can check your builder by checking the `builder` name in the `build` section of the `angular.json`.
> 
> Example
> 
> ```js
> "build": {
>   "builder": "@angular-devkit/build-angular:application",
> ```

```
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "buildTarget": "idm-admin-ui:build"
          },
          "configurations": {
            "development": {
              "buildTarget": "idm-admin-ui:build:development"
            }
          }
        },
```

**Comment by clydin** [comment]
The `configure` option should provide these capabilities:
```
const PROXY_CONFIG = [
  {
    context: ["/v2.0", "/v3.0", "/api"],
    target: "http://localhost:9980/self-service",
    changeOrigin: true,
    secure: false,
    logLevel: "debug",
    configure(proxy) {
      proxy.on("proxyReq", (proxyReq) => {
        console.log("set headers in on.proxyReq");
      });
    },
  },
];

module.exports = PROXY_CONFIG;
```

**Comment by shipengqi** [comment]
> The `configure` option should provide these capabilities:
> 
> ```
> const PROXY_CONFIG = [
>   {
>     context: ["/v2.0", "/v3.0", "/api"],
>     target: "http://localhost:9980/self-service",
>     changeOrigin: true,
>     secure: false,
>     logLevel: "debug",
>     configure(proxy) {
>       proxy.on("proxyReq", (proxyReq) => {
>         console.log("set headers in on.proxyReq");
>       });
>     },
>   },
> ];
> 
> module.exports = PROXY_CONFIG;
> ```

Thanks a lot, it works for me

**Comment by shipengqi** [comment]
@alan-agius4 @clydin thanks for your help
