### ISSUE TITLE
Updating to 1.0.0-beta.18 issue

### ISSUE THREAD

**Issue by hassanasad** [angular/angular-cli#2808]
### OS?

MacOS Seirra

I just updated my local angular-cli version from `1.0.0-beta.17` to `1.0.0-beta.18`

Now its giving this error on All `ng` commands:

```
It seems like you're using a project generated using an old version of the Angular CLI.
The latest CLI now uses webpack and includes a lot of improvements, include a simpler
workflow, a faster build and smaller bundles.

To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12
```

Anyone facing similar issues?

**Comment by grizzm0** [comment]
Are you sure you had this working with beta 17? Sounds like your project was created using beta 10 (pre-webpack). If so, you need to upgrade using the article linked.

To upgrade between recent versions you can run `ng init`. This will ask you to overwrite, diff or skip any changes between your project and the latest blueprints.

**Comment by hassanasad** [comment]
@grizzm0 yeah, it was working fine with beta 17. I was just waiting for the assets array implementation in beta 18 (you helped me in that thread as well :))

Yeah - my project started when it was pre-webpack versions. When i upgraded with each new update and was on 17. 

I cannot run `ng init` because all `ng` commands give the error in my first comment :(

**Comment by antonybudianto7** [comment]
my workaround is changing the angular-cli version directly in package json and do `npm i`, then try `ng init` again

**Comment by hassanasad** [comment]
thats what i do always :) Didn't work this time though

**Comment by hassanasad** [comment]
Ok its working now.

- I created a new project in another directory using `ng new dummy` command. 
- Updated/added some of the packages in the `devDependency` section. 
- Updated my angular-cli.json file and matched it with the dummy project's structure. 
- Copied the `src/typings.d.ts` file into my project. 
- Removed `node_modules` folder
- `npm i`

Now its working as expected :)

P.S: Seems to me either there was something missing in angular-cli.json file or a devDependency such as `@types/node` was missing.

**Comment by tomwanzek** [comment]
@hassanasad I just updgraded from beta.17 to beta.18 and I have the same issue: `ng init` is not working.

angular-cli: 1.0.0-beta.18
node: 6.5.0
os: win32 x64

While I appreciate your work-around from above (I will try it shortly), I don't think this issue should be closed. Quite to the contrary, it should be elevated in priority for actual resolution w/o work-around.

I have consistently been able to upgrade from beta.15 -> beta.16 -> beta.17. Minimal effort, never had an issue  with `ng init`. Simply loved it.

This is the first time, I encountered a problem, so there probably should be a more 'at the root' solution w/o a need for a work-around.

**Comment by hassanasad** [comment]
@tomwanzek I thought there was something wrong with only my install as no one seemed to be facing it. I will reopen it now - Probably someone more experienced can have a better look at this.

**Comment by tomwanzek** [comment]
Alright, so I went back over it and it worked now (roughly as previously) I will note that, I got a message that the `--link-cli` option is not supported. No longer I suppose? Will have to test things out by migrating another project, when I have a minute.

So, not sure, why I did not get `ng init` to work the first time around. Apologies, must have just been a crazy day today...

**Comment by jmlivingston** [comment]
I had the same problem, though I was able to work around it. I believe I may have caused it by two things: 

1. I had upgraded Angular to 2.1.0. 
2. I have been experimenting with Yarn package manager instead of npm.

My solution was reverting Angular back to 2.0.0, and exclusively using npm per the upgrade steps.

https://github.com/angular/angular-cli#updating-angular-cli

**Comment by chumtoadafuq** [comment]
Also having this same problem when going from beta16 to beta18.

angular-cli: 1.0.0-beta.18
node: 6.2.1
os: win32 x64

None of the ng commands work, so the upgrade steps can't be followed.

**Comment by filipesilva** [comment]
Fixed by https://github.com/angular/angular-cli/pull/2870
