### ISSUE TITLE
esbuild minifies css without charset=utf8 and converts unicode chars incorrectly

### ISSUE THREAD

**Issue by lorenzbaier** [angular/angular-cli#28099]
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have a stylesheet for mapping font icons which looks like:
```scss
:root {
  --icon-menu: "\e600";
  --icon-calendar: "\e601";
}
```
When serving locally with `optimzation.styles.minify = false` the resulting css looks something like (just like i expected):
```css
:root {
  --icon-menu: "";
  --icon-calendar: "";
}
```
However if i turn on the style minify optimization (in the prod build or with any other config) the unicode characters will be escaped as documented here https://esbuild.github.io/api/#charset by esbuild when running minify without the charset=utf8

Now I am asking whether this could be a bug in https://github.com/angular/angular-cli/blob/847083698d217a4949d68642fb153d17be8e8e9d/packages/angular_devkit/build_angular/src/tools/webpack/plugins/css-optimizer-plugin.ts#L148 where I think this minification process is called or is there another side to that story?

### Minimal Reproduction

create a scss file like:
```scss
:root {
  --icon-menu: "\e600";
  --icon-calendar: "\e601";
}
```
set `optimzation.styles.minify = true`
run `ng build`
look at the generated output stylesheet -> the unicode characters are escaped but should not

### Your Environment

```text
Angular CLI: 17.3.8
Node: 18.18.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 17.3.11
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
... service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1703.8
@angular-devkit/build-angular      17.3.8
@angular-devkit/core               17.3.8
@angular-devkit/schematics         17.3.8
@angular/cdk                       17.3.10
@angular/cli                       17.3.8
@angular/material                  17.3.10
@angular/material-moment-adapter   17.3.10
@angular/pwa                       17.3.8
@schematics/angular                17.3.8
rxjs                               7.8.1
typescript                         5.4.5
zone.js                            0.14.7
```

**Comment by dgp1130** [comment]
My intuition is that `optimization.styles.minify = false` should leave any unicode character sequences alone. `optimization.styles.minify = true` would transform them to the raw characters (assuming `--charset=utf8` is set which seems reasonable to me given that we generate `<meta charset="utf-8">` in `ng new`). This is probably a question for @clydin though.

**Comment by alan-agius4** [comment]
This is working as intended. In production builds, the output is ASCII-only, regardless of the meta tag in the HTML. This is mainly because ASCII code is faster for browsers to parse.
