### ISSUE TITLE
Inline SCSS/Template

### ISSUE THREAD

**Issue by montella1507** [angular/angular-cli#2809]
Hello, how does it exactly work in angular-cli@1.0.0-beta.18?? 

I have 
```
  "styles": [
        "content/styles/style.scss"
      ],

...

  "inline": {
      "style": true,
      "template": false
    },
```

In my angular-cli but the style is still in <style> tag.. is that bug? or i am just missing some information and shoulda close this ?

**Comment by grizzm0** [comment]
The defaults is default arguments when you create a new component. If the template and style should be inlined in the component or creating a separate html/css file.

The global styles are currently written to a js file which appends all styles to your head upon loading. There's nothing wrong here.

**Comment by montella1507** [comment]
Ah so.. so my fault.. i though its additional functionality, where i cant choose if the styles should be rendered to the DOM, or loaded as .css files with map files :-(

**Comment by grizzm0** [comment]
angular-cli does not let you configure any of the output.

#2646 is hopefully what you're looking for.

**Comment by montella1507** [comment]
thank you..i cant wait for it
