### ISSUE TITLE
Angular 18.1.1  is not adding CSP nonce attribute to script tags generated during build(main.ts,polyfills.js etc...)

### ISSUE THREAD

**Issue by sagartalaviya91** [angular/angular-cli#28102]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I want to implement strict CSP policy for my project, so replaced unsafe-eval and unsafe-inline with nonce-dynamicnonce.
But Angular version 18.1.1 is not adding nonce to script tags of main.js, polyfills.js etc. 
Because of that it is considering this scripts tags as unsafe and browser is blocking its execution.
In below stackblitz I used 18.1.1 and added nonce using CSP_NONCE and ngCspNonce. But it is not adding nonce to script tags. Please inspect and check in Dom.
Stackblitz URL: https://stackblitz.com/edit/stackblitz-starters-wr9a9h?file=src%2Fapp%2Fapp.config.ts

As per below merged Issue, It should work in 18.1.1. But it is not working.
https://github.com/angular/angular-cli/pull/27875

Kindly check!!
Thanks in advanced!

### Minimal Reproduction

1) apply nonce using ngCspNonce and CSP_NONCE provider
2) using dev tools check script tags  in DOM.
3) It is not adding nonce to script tags of main.js,polyfills.js etc..

### Your Environment

```text
18.1.1
```

**Comment by JoostK** [comment]
When running `ng build`, it does copy the `ngCspNonce` attribute value to style and script elements as `nonce` attribute. This is unlike `ng server`, which doesn't at the moment.

Note that using both `ngCspNonce` _and_ providing `CSP_NONCE` is superfluous; the former will be used to provide `CSP_NONCE` by default.
