### ISSUE TITLE
Incorrect line numbers in sourcemaps

### ISSUE THREAD

**Issue by dballance** [angular/angular-cli#2811]
### OS?
Windows 10

### Versions.
```
angular-cli: 1.0.0-beta.18
node: 6.5.0
os: win32 x64
```
Checked a beta.17 project, does not appear to occur there. Lines seem to be correct for debugging.

### Repro steps.

- `ng new source-map`
- `cd source-map`
- `ng serve` 
- Open `src/app/app.component.ts` and add some testing code

```
export class AppComponent {
  title = 'app works!';

  ngOnInit(){
    let value = true;
    if (value){
      value = false;
    }
  }
}

```

- Open devtools (tested in Chrome)
- `ctrl+p` and open `app.component.ts`
- Set breakpoint on line 12 (`let value = true`) and line 14 (`value = false`)
- Refresh page
- Hit breakpoint on line 12, notice call stack is outside `ngOnInit` even though breakpoint is within
- Hit breakpoint on line 14, notice call stack is within `ngOnInit` but `value = undefined`
- Step and see code execute as expected, but highlighted line to be shifted by a few lines

### Other useful info
Seems to shift by ~ 5 lines in my local project, not sure if it is the same shift in the repro (repro shift looks like 3?). Shift can be seen in VS Code Chrome Debugging - where line numbers are given for the mappings. 

Maps 48991 (actual line in `main.bundle.js` that breakpoint is set to in vscode) to 48986 (where the breakpoint actually is during runtime)

**Comment by dballance** [comment]
I believe this may be related to use of cheap-module-source-map change from #2619

**Comment by SebastianSchenk** [comment]
I have also issues with debugging and breakpoints since beta.18. Breakpoints are jumping sometimes (click on line 15, jumps to line 19) and execution doesn't stop at breakpoint.

**Comment by rob3c** [comment]
Btw it looks like there's a "help wanted" issue in the webpack 2 repo for trying to audit and fix source-maps:
https://github.com/webpack/webpack/issues/3165

**Comment by un33k** [comment]
I also confirm the line number issue in beta.18. Is there any workaround at this time?

**Comment by chadbr** [comment]
Thanks @un33k

**Comment by istvanszoboszlai** [comment]
Works like charm and it is not even slower for me in a moderately complex project.

**Comment by radoslavpetranov** [comment]
I have the same problem and it was killing me trying to debug some issues. @un33k's fix worked like a charm - thanks heaps!

**Comment by Splaktar** [comment]
@filipesilva Changing back to `source-map` from `cheap-module-source-map` fixed this issue for me in Chrome DevTools on OS X.

**Comment by filipesilva** [comment]
Indeed my change has broken sourcemaps. My initial testing seemed to indicate it was fine, but it's not. 

I'll keep an eye out for https://github.com/webpack/webpack/issues/3165 and see where it comes out.

**Comment by jmlivingston** [comment]
Huge thanks @un33k. Worked like a champ. Not being able to debug effectively was tough.

**Comment by dsm0880** [comment]
I'm glad I found this thread. Unfortunately this fix did not work for me or my team. We run on Windows 10 using vsCode. I changed the file as @un33k suggested but no go. Looking at the code that was checked in to fix this issue, it seems to be identical to what @un33k suggested, so I fear that the next release won't address the issue for some. Happy to provide more information to help find the root of the issue.

**Comment by emcpadden** [comment]
Thanks @un33k !!!  You saved me from going insane :)

**Comment by un33k** [comment]
@dsm0880 Follow the ngCLI upgrade [procedure](https://github.com/angular/angular-cli#updating-angular-cli) one more time and ensure that you are not [Working](https://github.com/angular/angular-cli#working-with-master) with master. Post your finding back.

**Comment by dsm0880** [comment]
Thanks @un33k, not sure if this was obvious or not but I had only changed the global version of this file. Reading your post again you said "in your project", so after fixing the local version of the angular-cli package it now works. Not sure if the changing the global file is even necessary. Anyways thanks! This made my day.

**Comment by un33k** [comment]
@dsm0880 The global version helps you type "ng" anywhere on the command line and the local version is what you really pin your project to.  Something like that. :)

**Comment by zackarychapple** [comment]
This issue should get re-opened as it is the same as #2909

**Comment by Splaktar** [comment]
It is fixed in master and does not need to be reopened. The other issue is a duplicate.
