### ISSUE TITLE
[lexical][prism] The code seems to have been incorrectly elevated while minimizing

### ISSUE THREAD

**Issue by wszgrcy** [angular/angular-cli#28128]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I built it using Angular CLI
Import Lexical package
Everything is normal during development
But there were problems with the packaging during production
Finally, it was found that the position of the prism code introduced by Lexical was different from that during development

### Minimal Reproduction

demo: https://github.com/wszgrcy/angular-lexical-build-error

### Exception or Error

During development:

![image](https://github.com/user-attachments/assets/ab46e960-a3b2-44a4-a6eb-5dea3beda28e)

During production:
![image](https://github.com/user-attachments/assets/60343447-c387-40a7-b6c7-78bb05b312c7)
![image](https://github.com/user-attachments/assets/82bd2fb4-9d2b-493e-82b1-6eb236e84627)
![image](https://github.com/user-attachments/assets/6fda5854-9fb0-4d61-ae23-1a6a6ad91830)

### Your Environment

```text
Angular CLI: 18.1.2
Node: 20.12.1
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 18.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.2
@angular-devkit/build-angular   18.1.2
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

### Anything else relevant?

esbuild error:  https://github.com/evanw/esbuild/issues/3850
I think it might be an issue with esbuild, so I submitted it to esbuild first
If there are updates to esbuild, please synchronize the upgrade dependencies

**Comment by alan-agius4** [comment]
It seems that Esbuild is causing an issue.
