### ISSUE TITLE
Improve visibility of "Re-optimizing dependencies because lockfile has changed" state

### ISSUE THREAD

**Issue by Yogu** [angular/angular-cli#28137]
### Command

serve

### Description

If you server an app for the first time, and it has a substantial size of libraries, you get this experience

- Building...
- Application bundle generation complete. and browser opens
- Browser shows a blank page for a few seconds, and nothing happens
- After a few seconds, the app loads normally

This is the output:

```
Application bundle generation complete. [8.275 seconds]

Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
Re-optimizing dependencies because lockfile has changed
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help
```

If you don't pay very close attention, you might not see the "Re-optimizing" line. And even if you do, you don't necessarily link it to your page not loading, because it just says something about "re-optimizing", which does not sound like it's a mandatory build step. After all, there already was the output "bundle generation complete".

-> it just looks like your app is broken, and you start opening the devtools to figure out what went wrong.

### Describe the solution you'd like

I think it would be good if `ng serve` stayed in the "Building" phase while dependencies are "optimized" the first time, so that the app immediately loads when it opens in the browser.

**Comment by alan-agius4** [comment]
The message "Re-optimizing dependencies because lockfile has changed" is crucial for Vite's speed. This step happens after code bundling and application compilation, so the log order is correct.

Generally, the server should be considered unavailable until its address is printed in the console, as it is here.

We could try to modify the logs as you suggested, but the effort may outweigh the benefits and would require managing logs from multiple tools. Additionally, the "Re-optimizing dependencies because lockfile has changed" log would be lost with the suggested change.

For now, I am inclined to leave things as they are and reconsider the log changes if this becomes a recurring issue for our users.

**Comment by Yogu** [comment]
> Generally, the server should be considered unavailable until its address is printed in the console, as it is here.

I agree with that. However, the server even stays unavailable after the address is printed in the console, for an unknown amount of time. The only way to know when the server is ready is to open the page at some point, and then wait until the page fully loads. I think my bullet points were a bit unclear about that.

You get this experience

- Building... (takes 10-14 seconds)
- Application bundle generation complete. `  ➜  Local:   http://localhost:4200/` is printed on the console. Browser opens.
- Browser shows a blank page
- Nothing visibly happens for another ~20 seconds. Browser is still showing a blank page, spinner is spinning. Console looks like everything is done.
- After a few seconds, the app loads normally. Nothing is printed on the console when this happens.

Is this expected, or is there an issue (possibly on my setup)?

**Comment by Yogu** [comment]
ok so I guess the problem is that the [function that logs the message](https://github.com/vitejs/vite/blob/fac3a8ed6855c4ab3032957137b74f21ec501e72/packages/vite/src/node/optimizer/index.ts#L367) only *deletes*  the cache, and does not rebuild it, and it's probably not even easily known which of the dependencies will be requested by the page.
