### ISSUE TITLE
Infinite Reload-Loop on application startup

### ISSUE THREAD

**Issue by davidbilge** [angular/angular-cli#2816]
### OS?

Windows 10, Chrome (Version 54.0.2840.71 m)
### Versions.

```
λ ng version
angular-cli: 1.0.0-beta.18
node: 5.7.0
os: win32 x64
```
### Repro steps.

When serving my app with beta.18's new `--ssl` option, I get an endless reload-loop in Chrome. I.e.: I navigate to `https://localhost:4200/`, the app loads and initializes completely and then reloads (as if I had hit F5).

Angular CLI's output does change (stays at `webpack: bundle is now VALID.`). The issue might have been caused by files being touched by another process, triggering a rebuild in angular-cli and thus a reload in the browser. This does _not_ happen.

I can reproduce the problem with the "blank" app as created by `ng init`, but it does not occur everytime like it does with my (more complex) app:
![reload-loop](https://cloud.githubusercontent.com/assets/762988/19599916/f6820582-97a2-11e6-989b-51946e9a0ec4.gif)

The problem does not occur in Firefox. I tried this Chrome's incognito mode to avoid plugin-problems, but the problem still occurs.

Also, when I switch away to another tab, the cycle stops. The reload itself still works: when I change a file on the filesystem, angular-cli correctly picks that up, rebuilds, triggers a reload and the browser is not sent into the infinite loop.

It feels like this is a timing issue between the reload-script running in the browser and the application's initialization.

As a sidenote: I tried to disable live-reloading (using `--live-reload=false`) but that does not seem to work.
### The log given by the failure.

No error is logged, neither on the command line nor in the browser's console.

Chrome's devtools' network view looks like this:
![reload-loop-2](https://cloud.githubusercontent.com/assets/762988/19599946/1ad9eabc-97a3-11e6-8792-d1063534deed.gif)

**Comment by filipesilva** [comment]
Heya, I can investigate, but can you give me exact repro steps, i.e. what you used for `--ssl`, or something I can use myself.

**Comment by davidbilge** [comment]
Hi, thanks for taking the time to look into this!

I simply used `ng serve --ssl`.

You can do this in the default app as generated by angular-cli, but that does not always trigger the problem (chances seem to improve if it is opened in a new browser tab or window). Chances also seem to improve if used on a more complex app.

**Comment by filipesilva** [comment]
Closing in favor of https://github.com/angular/angular-cli/issues/5826, it has some extra details about the issue cause.

**Comment by nasiruddin-saiyed** [comment]
same here without ssh on local with

**Comment by extrablind** [comment]
Had the same problem here. 
I work with atom. It automatically had an extra carriage return at the end of the file which is deleted by webpack at build, but recreate by atom immediatly, forcing rebuild, and so on...
You can monitor this issue by looking at the created webpack hashs which will be the same one after the other : one for extra carriage return, one for no carriage return. 
So closing index.html (or configure your ide) will do the trick; well it does for me. 
Good luck !

**Comment by Kolezhniuk** [comment]
The same problem too. Please help!!!!!
Your global Angular CLI version (1.6.3) is greater than your local
version (1.6.2). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.2
Node: 6.11.0
OS: win32 x64
Angular: 4.4.6
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... tsc-wrapped

@angular/cli: 1.6.2
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.2
@schematics/angular: 0.1.17
typescript: 2.7.2
webpack: 3.10.0

**Comment by silentsnooc** [comment]
@extrablind What IDE are you using? I'm getting this too.

**Comment by extrablind** [comment]
@silentsnooc : working with atom. Double check auto format options from Prettier / beautifier add on... or native atom settings. Regards.
