### ISSUE TITLE
rollup 

### ISSUE THREAD

**Issue by istiti** [angular/angular-cli#2817]
ENHANCEMENT:

Adding rollup ?!!

**Comment by gelliott181** [comment]
We literally just went through this with SystemJS -> Webpack, and Webpack is going to work better for the generalized case that the CLI is designed to cover.

**Comment by istiti** [comment]
@gelliott181 dude i know that,  there isn't better three shaking method than rollup so my issue is an enhancement or not ? please tag it as must have feature that's all?!!! by your comment I think now angular-cli do regression by passing to webpack without keep rollup !!!  is this agile method 😁?  Please apologize but stop tell me "dont have to use cli if don't like" thanks for response anyway

**Comment by gelliott181** [comment]
This isn't about tree shaking being better in Rollup than in Webpack, or any specific feature. This isn't Agile (A development process, not a build tool). I'm not saying "Don't use the CLI." I also will not be apologizing for laying out an informed and reasoned disagreement with your feature, specifically pointing out just how far the Angular-CLI team would backtrack (Again) in their progress, along with Rollup not providing features Webpack has brought to the table.

The cons outweigh the pros, and if we need tree-shaking I have a feeling the CLI team is more than capable of integrating that with Webpack. Not only that, but we have Webpack plugins already available (TS: https://github.com/blacksonic/typescript-webpack-tree-shaking, Babel: https://github.com/blacksonic/babel-webpack-tree-shaking). While they're not perfect, that's the beauty of open source: If you find it deficient, you can help to improve it yourself. 

With that, my final thoughts on this: We all have things we wish would happen, but every time the needs of the many will outweigh the needs of the few in these sorts of generalized tooling projects. When your needs diverge you can either continue to work with a large group of people all fighting for their needs to be heard, or you can take a fork in the road and find a way that works for you. Nothing in my statements has said you can't integrate Rollup into the CLI and submit a PR for the CLI maintainers to approve. I simply said the development team has made their decisions and is now at a point where they're unlikely to back out as it takes an already delayed schedule and delays it further for little to no benefit for most users.

**Comment by istiti** [comment]
Incredible, 6 chars get you arrogant. I won't write a novel, don't want dedicate time for this. But, I'm not convicted (I know you will say you don't try to get me convicted) anyway, always think "**adding rollup is must have feature**". They are Google Developers, big contrubutors , webpack and ember cli tools... IMHO I expect more than that from them.  BYE (yes I know I can stop use cli lol)

**Comment by JohannesRudolph** [comment]
I agree that unsubstantiated suggestions to replace a major component of the cli should be disregarded. However, I'm wondering about the claims that the current webpack implementation in the cli does not perform tree shaking? From a cursory glance at the aot bundles generated in - - prod mode this appears correct unfortunately...

**Comment by webmutation** [comment]
If you run **ng build --prod** or **ng build --prod --aot** it outputs removed functions so it is doing tree shaking, if you want to compare UglifyJs with Rollup tree shaking that is another thing (Rollup may be better). 

As far as i can tell CLI beta18 is performing tree shaking.

> WARNING in main.641d46f2cf1bf4ab5876.bundle.js from UglifyJs
> Dropping unused function scheduleMicroTask [c:/DEV/cli-tools-exp/cli-test/~/@angular/compiler/src/facade/lang.js:21,0]
> Dropping unused function getTypeNameForDebugging [c:/DEV/cli-tools-exp/cli-test/~/@angular/compiler/src/facade/lang.js:28,0]
> Dropping unused function isDate [c:/DEV/cli-tools-exp/cli-test/~/@angular/compiler/src/facade/lang.js:47,0]
> Dropping unused function noop [c:/DEV/cli-tools-exp/cli-test/~/@angular/compiler/src/facade/lang.js:50,0]
> Dropping unused function looseIdentical [c:/DEV/cli-tools-exp/cli-test/~/@angular/compiler/src/facade/lang.js:101,0]

**Comment by istiti** [comment]
@webmaxru dude, thanks but I know that. lol (anyway right persons know about what i'm speakin)

**Comment by mohammedzamakhan** [comment]
I don't think this is an unreasonable request, even rollup is used for benchmarking angular 2 performance with other frameworks at https://github.com/krausest/js-framework-benchmark by @robwormald. Probably Rob can put more light onto whether using webpack for treeshaking or rollout with closure compiler?

**Comment by filipesilva** [comment]
We're not looking at changing the build engine again. For the foreseeable future we'll focus of making it as good as possible using webpack.

**Comment by istiti** [comment]
Why closing this enhancement! Im not telling change build engine but only tree shaking method ! So maybe help webpack team to get webpack using or do better than rollup... I was thinking they are on it ! Still not understand why close enhancement request

**Comment by robwormald** [comment]
@istiti what you're asking for would be a feature request to webpack, and such functionality is already being discussed here https://github.com/webpack/webpack/issues/2873

**Comment by istiti** [comment]
that I agree, maybe better write request to webpack

**Comment by manifestarium** [comment]
*fans self with magazine* jer-RY! jer-RY! jer-RY!

**Comment by istiti** [comment]
?
