### ISSUE TITLE
You cannot use the new command inside an angular-cli project.

### ISSUE THREAD

**Issue by qwert789** [angular/angular-cli#2818]
Installed latest version of angular-cli on my windows pc trying just to create new project with:
ng new project_name 
getting error: You cannot use the new command inside an angular-cli project.
Tried to remove , reinstall with npm cache clean, nothing helps :(
![clibug](https://cloud.githubusercontent.com/assets/1618071/19602917/bb18e67c-97b7-11e6-9247-8bc1debcae5c.PNG)
### OS?

Windows 10 x64.
### Versions.

angular-cli: 1.0.0-beta.17
node: 6.4.0
os: win32 x64
### Repro steps.

ng new project_name
### The log given by the failure.

> Normally this include a stack trace and some more information.

**Comment by grizzm0** [comment]
Is there a file called angular-cli.json on your desktop?

**Comment by qwert789** [comment]
No, there is no angular-cli.json on my desktop
![clibug2](https://cloud.githubusercontent.com/assets/1618071/19604025/335637d0-97bc-11e6-9307-1eee609990a6.PNG)

**Comment by megabyzus** [comment]
@qwert789 This might be same issue others have encountered before.  instead of `ng new <project>`, try `ng new <project> --skip-npm` which should end up with the project folder.  Go to it and type npm install to get the modules.  Obviously not intended to work this way.

**Comment by ogix** [comment]
What if you try to run this command in another folder?

**Comment by JiaHongL** [comment]
Is there a file called  package.json alone in other places  ?
Deletes it , may solve the problem.
<img width="415" alt="2016-10-27 1 43 53" src="https://cloud.githubusercontent.com/assets/6601449/19755891/818fa5f6-9c4b-11e6-8402-5d6d396b425a.png">

**Comment by filipesilva** [comment]
Somewhere in the folders above your current one there is either a `node_modules/` folder or a `angular-cli.json`. Basically the command is detecting that you are already a npm project.

Try checking these folders for node_modules/` or `angular-cli.json` and delete it:
```
C:\
C:\Users\
C:\Users\Admin-PC\
C:\Users\Admin-PC\Desktop\
```

Alternatively, make your project in another folder e.g. `C:\test\`,

**Comment by ofirrifo** [comment]
work for me 10x 👍

**Comment by nikhilknoldus** [comment]
If you are using linux, go to home and find package.json and remove that. 
Keep rocking :+1:

**Comment by sherifsaleh** [comment]
on macOs I did what @nikhilknoldus said about removing the package.json in the home directory it worked for me.

**Comment by sumanthkumar93** [comment]
worked for me after deleting package.json file

**Comment by sahilkatia** [comment]
Faced same issue but didn't work for me if I deleted Package.json from home directory

**Comment by f0ru0l0rd** [comment]
I have the same issue. I am on a different drive. it's one folder removed from the root. There is no package.json in the root. There is no node_module in the root.
I am using windows 10, node 7.4.0, @angular/cli 1.2.0

Any ideas or reasons why? This is becoming such a pain.

**Comment by bluebaroncanada** [comment]
Yup.  Me, too.  Empty directory.

**Comment by fanfanpsu** [comment]
To above:
If you are using windows 10, do a global search for package.json to see if you have it in your destination folder's parent folder. I found mine in c:\user\myname and once I removed it everything works fine.

**Comment by bluebaroncanada** [comment]
It's basing its decision on whether you have  `"@angular/cli": "^1.3.1"` as a dependency in your package file.  This is usually because you're creating an angular project inside another project that may or may not be angular.
If you get the warning: 
```
Unable to find "@angular/cli" in devDependencies.

Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest" 
```
don't do what it says.  It'll be part of the package.json when you `ng new ....`

**Comment by pavankumar58** [comment]
Guys I have a similar problem 
I have created a complete new folder 
included my package.json and node_modules from npm and when I tried to create client folder using ng new client, the error was you cant new command inside Angular CLI project (This was in my D Drive)
Then I changed my project drive to C: and copied and pasted all the files except package.json and tried ng new client it worked and client folder is created. 
But when I tried to start the server using npm start, another error saying package.json file is missing?? 

Any solution for this confusion?
Thanks.

**Comment by rajatmohanty** [comment]
In Mac, press **Shift+Command+H**  or select **Finder** then press **Go** option on top toolbar and finally select **Home** option. Now select `package.json` and `package-lock.json` file and delete both the file.

Restart your terminal and you are ready to go.

**Comment by beginfarming** [comment]
If you are using Linux, go to home and find package.Json and remove that.

**Comment by Skaldrick** [comment]
go to your package.json in your project folder, remove the following code from it and it should work fine

"devDependencies": {
    "@angular/cli": "^1.4.9"
  }

says to do the following
Please take the following steps to avoid issues:
"npm install --save-dev @angular/cli@latest"

DO NOT DO IT, this is what caused the issue for me

**Comment by leotm** [comment]
I was trying to install angular as the front-end, for my existing back-end project. E.g. `my-project/angular-app`.
Was getting what @bluebaroncanada mentioned.
What worked was `ng new` outside my existing project.

**Comment by AnandaRisyad** [comment]
You must initialize npm before creating new angular project, i have the same problem but when i try to init npm, it works

**Comment by shahrishabhptechnical** [comment]
I was facing same problem. I deleted package.json from project and applied necessary command, It worked

**Comment by rcarnauba** [comment]
After deleting package.json file at user folder, it worked. (Windows 10)

**Comment by ASrima** [comment]
I had the similar problem and nothing was working out but then when I ran cmd as administrator it worked for me. First run the Command Prompt as administrator ans then create the new project and if it still doesn't create the project run the code rm -r -f // and then run ng new and then run ng serve and it should work. If nothing works just uninstall node and every other file related to it th and run the previous code again it will work.

**Comment by andreobueno** [comment]
I'm using MacOS and I had this problem today... The way I fixed it was:

1 - I had no idea why, but there was a node_modules and a package.json on my home folder... I removed them;
2 - I also removed a node_modules and package.json from my current project folder
3 - Then, ng new project-name worked :) 

I hope it helps somebody else...

p.s.: Please, angular@cli people, take a look at this weird thing going on... I don't know why angular@cli is creating such files in the home o.O

**Comment by sanjeevSOPRA** [comment]
I had the same problem, i deleted the package.json file from the folder, after that it works :)

**Comment by breninrice** [comment]
I had the same problem, i deleted the package.json file from the folder, after that it works :) me too!
working now!!!!!!!!!!

**Comment by rajendharitguy** [comment]
actually, you don't need to delete the whole package.json file, just if you can delete angular cli in devdependendy line. that how worked for me

**Comment by fahedalh** [comment]
_**

> Search on the root folder for a file called package.json then delete it .
> 
> It will solve the problem.

**_

**Comment by Piuu** [comment]
I had the same problem. It works fine now after deleting package.json thanks a lot you guys. May I know the actual use of that file? How the existence of it cause this problem... I have some other file "package-lock.json" which bothers me than this. ;)

**Comment by vivekgupta135** [comment]
Hi All,
I have faced this issue but got this solution 
1) Create a dir test
2) Cd test
3) run npm init command 
4) ng new Ang5App
5) Finally, it works for me

**Comment by amjayesh07** [comment]
@ # # @

- [ ] 

- 1.

**Comment by mkadhim** [comment]
thanks a lot ,it works for me .Allah bless you

**Comment by thiagofrancisquete** [comment]
I haven't any _package.json_ file in my root directory or _node_modules_ or _angular.json_ and I still can't run `ng new something` inside of a CLI project and the new project has to be inside of this CLI project. So what I have to do?

**Comment by rheineo** [comment]
excecute npm install --save-dev @angular/cli@latest into dir work.. (example: Desktop)
