### ISSUE TITLE
Option 'declarationDir' cannot be specified with option 'outFile'.

### ISSUE THREAD

**Issue by penglipengli** [angular/angular-cli#28188]
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

A new library is created in the angular15 project, and the dependency of package.json in the library is set to unpeerdependencies. I hope that this library will be packaged into an index.js that contains all dependencies (when using it, there is no need to introduce dependencies from node_module), in tsconfig When configuring outFile, an error occurs during build: Option 'declarationDir' cannot be specified with option 'outFile'.

### Minimal Reproduction

my tsconfig:
`/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "./tsconfig.lib.json",
  "compilerOptions": {
    "declarationMap": false,
    "outFile": "../../dist/dai-sdk/index.js",
    "module": "AMD",
  },
  "angularCompilerOptions": {
    "compilationMode": "partial"
  }
}
`
tsconfig.lib.json:
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "declaration": true,
    "declarationMap": true,
    "inlineSources": true,
    "types": []
  },
  "exclude": [
    "**/*.spec.ts"
  ],
  "include": ["**/*"]
}

tsconfig.json:
/* To learn more about this file see: https://angular.io/config/tsconfig. */
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "resolveJsonModule": true,
    "lib": [
      "ES2021",
      "dom"
    ],
    "paths": {
      "src/*": ["projects/dai-sdk/src/lib/mbi/*"],
      
    },
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true
  }
}

### Exception or Error

```text
error info:Option 'declarationDir' cannot be specified with option 'outFile'.

can library build as a index.js and containes all dependencies?
```

### Your Environment

```text
Angular CLI: 15.2.9
Node: 20.12.0 (Unsupported)
Package Manager: npm 10.5.0
OS: win32 x64

Angular: 15.2.9
```

**Comment by JoostK** [comment]
No, libraries will not vendor in external packages into the built output, and this cannot be accomplished using the default tooling. You could potentially postprocess the output to accomplish this on your behalf.
