### ISSUE TITLE
Followup of #24916 ng serve often caches old component code

### ISSUE THREAD

**Issue by jmozmoz** [angular/angular-cli#28209]
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I have exactly the same problem as reported in #24916:

`ng server` (and also if I serve the project by `http-server` after calling `ng build --configuration production --aot --output-hashing=none`) results in old source code being used.

I do not have a reproducible example but it seems to be related to the file time stamps:

The problem mostly appears, if I switch between `ng serve` and `http-server` and if `http-server` had an old build. Then switching back to `ng serve` also seemingly uses the old source files. Delete `.angular` and even the `nodes_modules` did not help.

What helped was running `find . | xargs touch` in the folder of the angular project (using cygwin on Windows). But I have no idea, where the cached files were located.

### Minimal Reproduction

Sorry, I do not have an example. But my guess would be you can somehow reproduce this as described above:

Switch between serving with `ng serve` and `http-server` and changing source code but manually switch back the time stamps of the files and remove the cache folders.

### Your Environment

```text
Angular CLI: 18.1.4
Node: 20.12.2
Package Manager: npm 10.5.0
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1801.4 (cli-only)
@angular-devkit/core         18.1.4 (cli-only)
@angular-devkit/schematics   18.1.4 (cli-only)
@schematics/angular          18.1.4 (cli-only)
```

**Comment by alan-agius4** [comment]
@jmozmoz, thanks for opening this issue. However, without detailed steps or a clear method to reproduce the problem, we're unable to take further action on it from our end.

**Comment by jmozmoz** [comment]
I can partially reproduce it:

Using conda with the conda-forge channel:

```
conda create -n nodejs
conda activate nodejs
conda install nodejs
```

This installs:
```
nodejs-22.6.0              |       h57928b3_0        25.1 MB  conda-forge
```
Now
```
npm install -g @angular/cli
ng new testjs
cd testjs
ng serve
ng build --configuration production --aot --output-hashing=none
npm install -g http-server
cd dist\testjs\browser
http-server . -p 4201
```
Both serve the same (original) version.

Now modify `app.component.html`
```
cd ..\..\..
ng serve
```
The modified version is accessible
```
ng build --configuration production --aot --output-hashing=none
cd dist\testjs\browser
http-server . -p 4201
```
Still serves the old version!

Remove `.angular` and `dist` folders:
```
cd ..\..\..
rd /s /q .angular
rd /s /q dist
ng build --configuration production --aot --output-hashing=none
cd dist\testjs\browser
http-server . -p 4201
```
Still serves the old version!
```
cd ..\..\..
ng serve
```
Serves the new version.

**Comment by jmozmoz** [comment]
Okay. It looks like this is related to caching of the Webbrowser (Firefox for tests, QtWebEngine for the full case): If I use the same port, the old version is displayed for both, `ng serve` and `http-server`. If I use a new, not used before port, the current version is displayed.

For the `http-server` case, I found this solution: https://stackoverflow.com/a/50511913:
`--output-hashing=all`

But how to solve this for `ng serve`?

**Comment by alan-agius4** [comment]
@jmozmoz, hard reload or disabling caching so solve this.
