### ISSUE TITLE
 Support Custom Loaders for File Extensions in@angular-devkit/build-angular:browser-esbuild

### ISSUE THREAD

**Issue by ankurthakur-tyler** [angular/angular-cli#28201]
### Command

build, config, serve

### Description

I'm using the **@angular-devkit/build-angular:browser-esbuild** builder for my Angular project and attempting to convert from the **@angular-builders/custom-webpack:browser**
builder. During this process, I've encountered a limitation when trying to handle custom file extensions, such as .less, within the ESBuild configuration. Currently, the browser-esbuild builder doesn't seem to support the configuration of custom loaders directly for specific file extensions, which restricts the ability to manage styles or other non-standard assets that require preprocessing. This limitation makes the transition from custom-webpack to browser-esbuild challenging, as it complicates the handling of various assets that were previously managed through custom Webpack configurations.

### Describe the solution you'd like

Like to add loaders option as available in **@angular-devkit/build-angular:application**

### Describe alternatives you've considered

I attempted to use @angular-devkit/build-angular
for my hybrid app, but it required extensive modifications and customizations across multiple files. This approach isn't practical, especially considering the large number of apps we already have configured with @angular-builders/custom-webpack

**Comment by alan-agius4** [comment]
The `browser-esbuild` builder is a compatibility builder, allowing users to switch between webpack and esbuild-based builders. Therefore, it must offers the same options.

The `application` builder, is the recommended option if you want to use new features and options. New features and options are exclusively added to the `application` builder as it is the preferred choice if you want to use specific esbuild features.
