### ISSUE TITLE
support playwright in ng e2e

### ISSUE THREAD

**Issue by reuse-ay** [angular/angular-cli#28216]
### Command

e2e

### Description

If you run `ng e2e` before adding an e2e framework, you will be presented with a choice of e2e test frameworks to choose from and you can add an e2e test framework. Currently, Playwright is not included in these choices, even though it is becoming more and more popular.

### Describe the solution you'd like

Add playwright as an option.

### Describe alternatives you've considered

You can use the command [`npm init playwright`](https://playwright.dev/docs/intro), but the integration with Angular is not perfect.

**Comment by alan-agius4** [comment]
The frameworks listed all provide schematics, playwright does not. We'll added once https://github.com/microsoft/playwright/issues/11258 is addressed.
