### ISSUE TITLE
Updating: don't delete old file but keep it for comparison

### ISSUE THREAD

**Issue by cre8** [angular/angular-cli#2821]
When you have to update a project and you need content from new new file and content from your current file there is no way to have both files on your system. You can say `y` for overwrite and `n` for not overwrite.
So why there is no option to keep the old file as a kind of backup, e.g. old `package.json` will become `package.json.old` so after the whole project is updated I can look at both files and add the lines of my old file to the new one?

**Comment by gelliott181** [comment]
in the `Yndh` options the `d` stands for `diff` which will show you a comparison of the two files in question.
