### ISSUE TITLE
Report which route failed during pre-rendering. 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular-cli#28212]
### Description

While build a pre-rendered app, I'm greeted with the following error : 

```
Exception:
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<ne>".
ERROR
```

This error makes it hard to investigate the cause as it only happens during pre-rendering (dev mode serve is fine). 

It'd be great to have some details, like for example which route is throwing while being pre-rendered.

**Comment by alan-agius4** [comment]
@JeanMeche, how can we reproduce this?
