### ISSUE TITLE
Add more feature to generation schematics

### ISSUE THREAD

**Issue by Maryannah** [angular/angular-cli#28220]
### Command

generate, new

### Description

Add new flags for the generation of applications & components, mainly : 

- `--display-block` on `ng new`
- `--change-detection` on `ng new`
- `--zoneless` on `ng new`
- `--export-default` on `generate component` (for routing purposes)

**Comment by alan-agius4** [comment]
Introducing numerous options to the `ng-new` command doesn't align with our objectives. That said, many of these options have already been addressed. In some instances, it's simple enough to implement workarounds or make manual adjustments.

See:

- https://github.com/angular/angular-cli/issues/21353
- https://github.com/angular/angular-cli/issues/25023

Regarding zoneless options, we will certainly consider them for a future release once certain gaps are addressed.
