### ISSUE TITLE
How to customize the behavior of the build process?

### ISSUE THREAD

**Issue by shicechi** [angular/angular-cli#2824]
Hello, I am wondering how to customize the behavior of `ng build --prod`. 
Such as passing in `ascii_only: true` option to UglifyJS.

Any help is greatly appreciated!

**Comment by grizzm0** [comment]
There is currently no built in way to customize the build process. The only current way would be to fork the repo and edit the fork to fit your needs. 

See:
https://github.com/angular/angular-cli#development-hints-for-hacking-on-angular-cli
https://github.com/angular/angular-cli/tree/master/packages/angular-cli/models

**Comment by filipesilva** [comment]
What @grizzm0 said 💃
