### ISSUE TITLE
Compile-time constant replacement (like DefinePlugin)

### ISSUE THREAD

**Issue by amakhrov** [angular/angular-cli#28242]
### Command

build

### Description

In our app, we use Sentry. It ships debug code by default, with instructions for tree-shaking in prod.
Such tree-shaking is based on replacing a global constant at compile time. https://docs.sentry.io/platforms/javascript/configuration/tree-shaking/#tree-shaking-with-webpack
e.g
```
new webpack.DefinePlugin({
      __SENTRY_DEBUG__: false,
      __SENTRY_TRACING__: false,
      __RRWEB_EXCLUDE_IFRAME__: true,
      __RRWEB_EXCLUDE_SHADOW_DOM__: true,
      __SENTRY_EXCLUDE_REPLAY_WORKER__: true,
    }),
```

Angular doesn't expose the underlying webpack configuration for extending (for good reasons). Unfortunately for us, it means the prod bundles include debug code, which we cannot tree-shake at the compile time

### Describe the solution you'd like

Ability to define compile-time constants replacements, abstracted away from the underlying build tool (whether webpack or esbuild).

**Comment by alan-agius4** [comment]
This is already possible with the application builder, which includes a `define` option. For more details, refer to this PR: https://github.com/angular/angular-cli/pull/27047.

**Comment by amakhrov** [comment]
I'm getting
```
Error: Schema validation failed with the following errors:
  Data path "" must NOT have additional properties(define).
```
Is there documentation on how to use it correctly?

**Comment by JeanMeche** [comment]
Against which version are you testing this ? Care to share the `angular.json` you tried ?

**Comment by amakhrov** [comment]
We use the `"@angular-devkit/build-angular:browser"` builder.

**Comment by JeanMeche** [comment]
As Alan mentionned, this is only for the application builder.

**Comment by amakhrov** [comment]
Is there a plan to port this functionality to the webpack-based builder?

**Comment by alan-agius4** [comment]
No, generally new features are not added to the webpack based builders.

**Comment by amakhrov** [comment]
Thanks!
