### ISSUE TITLE
Failed to resolve import "./chunks/helpers.segment.js" from ".angular/vite-root/project_name/scripts.js".

### ISSUE THREAD

**Issue by kartikth40** [angular/angular-cli#28259]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

Angular v16

### Description

I have migrated a project to Angular v18 and on running ng serve got this error on runtime - 

```
...
Watch mode enabled. Watching for file changes...
NOTE: Raw file sizes do not reflect development server per-request transformations.
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: kaios 2.5, op_mini all
  ➜  Local:   http://localhost:4200/
  ➜  press h + enter to show help
1:14:31 PM [vite] Internal server error: Failed to resolve import "./chunks/helpers.segment.js" from ".angular/vite-root/project_name/scripts.js". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/microservices/project_name/.angular/vite-root/project_name/scripts.js:6:901
...
```

### Minimal Reproduction

The error occurs on runtime during the following command execution -
```ng serve```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 18.2.0
Node: 20.16.0
Package Manager: npm 10.8.1
OS: win32 x64

Angular: 18.2.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-luxon-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.0
@angular-devkit/build-angular   18.2.0
@angular-devkit/core            18.2.0
@angular-devkit/schematics      18.2.0
@schematics/angular             18.2.0
rxjs                            7.8.1
typescript                      5.4.5
zone.js                         0.14.10
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by lionelgaillard** [comment]
Hi,

Had the same problem.
Resolved by downgrading chart.js from version 4 to 3.

Have a good day
