### ISSUE TITLE
Autoprefixer and --prod flag , do not load all styles.

### ISSUE THREAD

**Issue by goriunov** [angular/angular-cli#2827]
> ## Please provide us with the following information:
> 
> I am compiling a Angular  2 application with --prod flag and get file style.000.bundle.js which contain 
> all my styles. Ass well i have added Auctoprefixer to Angular CLI and it works well. And in my style.0000.bundle.js i have all styles which added with autoprefixer however this styles are not loaded to browser, but if i do not use --prod flag everything is  working well and all styles are loading to the browser.
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
> Mac OS Capitan
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:
> beta 18
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.
> I added autoprefixer to Angular CLI
### The log given by the failure.

> Normally this include a stack trace and some more information.
### Mention any other details that might be useful.

Does not load all styles if i am using --prod flag

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by filipesilva** [comment]
How exactly did you add autoprefixer?

**Comment by peterblazejewicz** [comment]
@filipesilva 
I believe I've the same issue.
To recreate with *.21:
CSS rule in SCSS:
```scss
.card-columns--custom {
  column-width: 18rem;
  column-count: 3;
}
```
- default (behind --dev) inlined 
```text
.card-columns--custom {
  -webkit-column-width: 18rem;
     -moz-column-width: 18rem;
          column-width: 18rem;
  -webkit-column-count: 3;
     -moz-column-count: 3;
          column-count: 3; }  
```
- production (behind --prod), bundled:
```text
.card-columns--custom{column-width:18rem;column-count:3}
```
I'm using everything default that comes with CLI, touching only `angular-cli` settings.
Thanks!

**Comment by filipesilva** [comment]
Fixed in https://github.com/angular/angular-cli/pull/3402, but pending release.
