### ISSUE TITLE
Error in config file :  Cannot find module 'angular-cli/plugins/karma'

### ISSUE THREAD

**Issue by jeremythille** [angular/angular-cli#2828]
> ## Please provide us with the following information:
### OS?

> Windows 10 x64
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.18
node: 6.4.0
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

Created the app usin the CLI (updated yesterday to the latest version). The app works and loads in Chrome. For now there's just an input field.
I created a service using "ng g myservice"
Then I wrote some tests in myservice.service.ts
I ran "ng test"
### The log given by the failure.

> Normally this include a stack trace and some more information.

$ ng test --watch=false
22 10 2016 11:05:54.156:ERROR [config]: Error in config file!
 { Error: Cannot find module 'angular-cli/plugins/karma'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (D:\dev\wiki_a2\karma.conf.js:12:7)
    at Object.parseConfig (D:\dev\wiki_a2\node_modules\karma\lib\config.js:377:5)
    at new Server (D:\dev\wiki_a2\node_modules\karma\lib\server.js:56:20)
    at C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\tasks\test.js:25:31
    at Class.exports.default.Task.extend.run (C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\tasks\test.js:15:16)
    at Class.TestCommand.extend.run (C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\commands\test.js:26:25)
    at Class.<anonymous> (C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\node_modules\angular-cli\lib\models\command.js:152:17)
    at tryCatch (C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp-internal.js:215:12)
    at invokeCallback (C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp-internal.js:230:13)

```
at C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\then.js:29:16
at flush (C:\Users\Elg\AppData\Roaming\npm\node_modules\angular-cli\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9) code: 'MODULE_NOT_FOUND' }
```
### Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.

**Comment by bothbears** [comment]
Hi,

I'm experiencing the same issue -> fresh node and angular-cli installation, everything works, just the ng test doesn't (same error message and no karma plugin found).

Cheers

**Comment by Caballerog** [comment]
Hi,

I'm experiencing the same issue.

angular-cli: 1.0.0-beta.16
node: 6.6.0
os: Linux x64

**Comment by Caballerog** [comment]
I found my error which was that I had not provider a service. This service is used in the component that I want to test.

**Comment by Caballerog** [comment]
In my particular case, this error don't happen.

**Comment by filipesilva** [comment]
Closing as inactive.

**Comment by juhap** [comment]
Check if angular-cli/plugins/karma exists in the node_modules directory. 

In my case the problem was that I had migrated to @angular/cli package, but karma.conf.js was still referencing the angular-cli paths.  I updated my references by comparing to the karma.conf.js from this repo: https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng2/files/karma.conf.js

**Comment by ahelord** [comment]
@juhap  this work for me but in the karma.conf.js have issue 
Error: No provider for "framework:angular-cli"! (Resolving: framework:angular-cli)

**Comment by sjcetx** [comment]
@ahelord check the answer provided by @juhap there are multiple locations that angular-cli needs to be changed to @angular/cli

**Comment by frank-productops** [comment]
@juhap It seems that your link is broken. Could you take a look and fix it please? I'm also having a similar issue.

**Comment by BaronChen** [comment]
@frank-productops  New link you can check out: https://github.com/angular/angular-cli/blob/b15d1f37b6c6d7e57d969359b8b7d8a916465362/packages/%40angular/cli/blueprints/ng/files/karma.conf.js

**Comment by ahelord** [comment]
@frank-productops i modify proyect little bit https://github.com/ahelord/angular-cli-primeng-example

**Comment by softgandhi** [comment]
Hi,
When I updated from angular-cli to @angular/cli, i also faced the same issue:
`Error: Cannot find module 'angular-cli/plugins/karma'`

The **solution worked for me** is to update the karma.conf.js file present in root folder of the project.
```
frameworks: ['jasmine', '@angular/cli'],
...
plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-remap-istanbul'),
      require('@angular/cli/plugins/karma')
    ],
...
preprocessors: {
      './src/test.ts': ['@angular/cli']
    },
...
```
After this change, ng test should work.

**Comment by Abekonge** [comment]
Detailed guide on changes to `karma.conf.js` after upgrading to @angular/cli rc1: https://github.com/angular/angular-cli/wiki/stories-rc.0-update

**Comment by droppedoncaprica** [comment]
Since Google highly prefers Github issues instead of StackOverflow when it comes to debugging Angular 2 applications, I figured I would chime in here.

The issue is that the Node package for Angular's CLI was changed from `angular-cli` to `@angular/cli`.  If you go through your `karma.conf.js` file and replace all instances of `angular-cli` you should be good to go.

Shout out to [this StackOverflow post](https://stackoverflow.com/a/42632294/23875) that got me to the correct answer.  Also shout out to @softgandhi  for answering the same thing.  Unfortunately for him I lack reading comprehension.

**Comment by ahelord** [comment]
I had a project in angular2, primeng and angular-cli. I decided to migrate angular4 and @ angular-cli
  When with the own guide angular but I did not work out errors when finding the core module. Then I decided to create a new project with the new @ angular-cli and pass the source code, there were errors where we had to add the Angular animations module and update Primeng.

**Comment by MeltdownZA** [comment]
You may also need to update the environments section in angular-cli.json

**Old version**
`"environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }`

**New version**
`"environmentSource": "environments/environment.ts",
      "environments": {        
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }`
