### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by zackarychapple** [angular/angular-cli#283]
Now that typescript 1.8+ and beta.8 are both in the cli is it possible to get a release?

**Comment by hansl** [comment]
Done with #285.

**Comment by doczoidberg** [comment]
is there any plan/roadmap when npm packages are updated?

**Comment by filipesilva** [comment]
@doczoidberg what do you mean?

**Comment by doczoidberg** [comment]
I am new to npm. Maybe I understand something wrong but via npm I get not the latest packages:
```

c:\temp\app1>npm outdated
Package                Current        Wanted        Latest  Location
angular-cli             0.0.20        0.0.20        0.0.25  angular-cli
angular2          2.0.0-beta.0  2.0.0-beta.0  2.0.0-beta.9  angular2
es6-shim               0.33.13       0.33.13        0.35.0  es6-shim
karma                  0.13.21       0.13.22       0.13.22  karma
reflect-metadata         0.1.2         0.1.2         0.1.3  reflect-metadata
rxjs              5.0.0-beta.0  5.0.0-beta.0  5.0.0-beta.2  rxjs
systemjs                0.19.4        0.19.4       0.19.24  systemjs
zone.js                 0.5.10        0.5.10         0.6.2  zone.js
```

**Comment by hansl** [comment]
Your CLI isn't the latest. You need to upgrade it.

We definitely have the latest for most of those (not all?).

**Comment by doczoidberg** [comment]
how can I update CLI? I tried `npm update angular-cli` but `npm outdated` results are the same

**Comment by filipesilva** [comment]
You probably need to update both the local `angular-cli` installation and your global one. Start with the global install:

```
npm install -g angular-cli
```

Now, there is a second issue at play: your project was generated with an older version of the CLI, and thus the generated `package.json` has old versions. Just updating the local `angular-cli` won't be enough. You need the new `package.json` that newly generated projects have.

You can either generate a new project, or just directly replace your `package.json` with the following: 

```
{
  "name": "app1",
  "version": "0.0.0",
  "license": "Apache-2.0",
  "angular-cli": {},
  "scripts": {
    "start": "ng server",
    "postinstall": "typings install --ambient",
    "lint": "tslint src/**/*.ts",
    "format": "clang-format -i -style=file --glob=src/**/*.ts",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "angular2": "2.0.0-beta.9",
    "clang-format": "^1.0.35",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.20",
    "zone.js": "0.5.15"
  },
  "devDependencies": {
    "angular-cli": "0.0.*",
    "angular-cli-github-pages": "^0.2.0",
    "ember-cli-inject-live-reload": "^1.3.0",
    "glob": "^6.0.4",
    "jasmine-core": "^2.3.4",
    "jasmine-spec-reporter": "^2.4.0",
    "karma": "^0.13.15",
    "karma-chrome-launcher": "^0.2.1",
    "karma-jasmine": "^0.3.6",
    "protractor": "^3.0.0",
    "silent-error": "^1.0.0",
    "ts-node": "^0.5.5",
    "tslint": "^3.3.0",
    "typescript": "^1.8.7",
    "typings": "^0.6.6"
  }
}
```

Afterwards run `npm install` on your project folder and you should have the latest version of everything.

In there future there will be a smoother upgrade path for cli versions, but at the moment it is not done.
